### ISSUE TITLE
Add Android Support

### ISSUE THREAD

**Issue by logomancer** [pbek/QOwnNotes#1]
It's possible to [port a Qt 5 program to Android](http://doc.qt.io/qt-5/portingtoandroid.html). Might be worth looking into.

**Comment by pbek** [comment]
Yes, that's true. The same goes for iOS. But a lot of parts will need to be rewritten, for example currently the syncing is done by ownCloud, under iOS and Android the ownCloud API would need to be used...
Maybe I'll dive deeper into this topic. ;)

**Comment by pbek** [comment]
There now is an Android App: https://www.qownnotes.org/getting-started/qownnotes-android.html.
