### ISSUE TITLE
Windows version is missing toolbar icons

### ISSUE THREAD

**Issue by janhenke** [pbek/QOwnNotes#10]
The Windows version is currently missing the icons in the toolbar. The two buttons are present, but have no icons. On Linux it works, so it seems a packaging issue.

I just extracted the supplied zip file as is and run the executable from it.

**Comment by pbek** [comment]
It works on Windows 7, we have to think about a way to solve this under Windows 8... I guess its a problem to view SVGs under Windows 8.

**Comment by janhenke** [comment]
That is strange. There should be no major difference between Windows 7 and 8. I had a similar problem some time ago on Linux, where the Qt SVG library was missing as far as I remember, but I see it is supplied in the zip file.

I guess we need to trace whether it is loaded correctly on start up by the dynamic linker?

**Comment by pbek** [comment]
I installed a Win 8.1 VM and already tried a lot. No progress so far...

**Comment by pbek** [comment]
The last build of QOwnNotes for Windows (please redownload) has now finally also icons for Windows 8.1.
Can you confirm that?

**Comment by janhenke** [comment]
Yes, now it works here as well.

**Comment by pbek** [comment]
Great, thanks again for the report!
