### ISSUE TITLE
Feature request: Support moving notes via drag and drop

### ISSUE THREAD

**Issue by Letterus** [pbek/QOwnNotes#100]
Currently you have to switch to the Finder (Mac OS X) to move a note in or out of QOwnNotes.

Proposal: Support drag and drop into and from the window/list (and icon?) of QOwnNotes to move note files.

**Comment by pbek** [comment]
Thank you for your report, @Letterus!
So you want to move notes from a folder in Finder to QOwnNotes, am I correct?
I'm not sure how good that will work cross platform and cross file browser, but I will look into it.

**Comment by Letterus** [comment]
Yep. Great, thanks. :-)

**Comment by pbek** [comment]
In v1.1.4 there will be support for copying notes from a file manager to QOwnNotes via drag and drop.

**Comment by pbek** [comment]
Version 1.1.4 is now out, could you be so kind and report if it works as desired.

**Comment by Letterus** [comment]
Yeah, great, that works! Thank you!

Even more useful for me would be if 
- you could drag the file on the QOwnNote application icon as well
- the other way around was possible, too. ;-)

**Comment by pbek** [comment]
Can you please describe both cases in more detail.

**Comment by Letterus** [comment]
Of course:
1. Drag a txt/md-file onto the icon of the app (OS X: either in Finder or in the Dock) - the result should be the same as with the current change: copy of the file into QOwnNotes/the notes directory.
2. Drag a note out of the list and move it (a file icon or something should show up to symbolize the process) to a place within the file manager: the file should be copied to this place.

One further wish: Make a preference for choosing the result of the drag-and-drop-actions: either move (what I would prefer) or copy (what others might prefer).

**Comment by pbek** [comment]
I will investigate some more...

**Comment by pbek** [comment]
> 1. Drag a txt/md-file onto the icon of the app (OS X: either in Finder or in the Dock) - the result should be the same as with the current change: copy of the file into QOwnNotes/the notes directory.

I have not yet found a way to do that in Qt. Do you know a Qt application (with source code) that is able to accept drops on the application icon of the running app in the task bar?

**Comment by Letterus** [comment]
In the moment I can't remember one.

But maybe this does help? http://doc.qt.io/qt-4.8/qfileopenevent.html

**Comment by pbek** [comment]
Thank you, I will investigate. ;)

**Comment by pbek** [comment]
Sad: This class is currently supported for OS X only.

**Comment by pbek** [comment]
I will close this issue until there are more news...
