### ISSUE TITLE
Feature request: add todo.txt support

### ISSUE THREAD

**Issue by joede** [pbek/QOwnNotes#1001]
I love to use QOwnNotes to manage an ever growing number of Markdown files. After a server crash and some sync trouble with the new server, I decided to replace Nextcloud with SyncThing.

I'm using the TODO-lists of [todo.txt](https://todotxt.org) with the command line and the GNOME shell. Since these "databases" are simple text files, it is easy to sync them.

Is it possible to add a "todo-plugin" for this file format?

IMO this would perfectly match into the scope of QOwnNotes.

With [Todour](https://github.com/SverrirValgeirsson/Todour), there exists a Qt implementation of the format. Maybe it is possible to reuse some code. ;-)

**Comment by joede** [comment]
I haven't found this (closed) issue. May be I've accidentally searched with is:open.

I don't want a custom highlighter. Since I don't use a public Nextcloud anymore, I can't try the "Tasklist View" (here "Aufgabenliste anzeigen") of QOwnNotes. I think it would be nice to have a common view for both TODO backends.

Adding support for this TODO-Backend would make QOwnNotes independent of Nextcloud. Since this is already the case for the notes, it would be completed by the TODO backends.

The scripting solution would "only" change the view of the note, wouldn't ti?

**Comment by pbek** [comment]
> Adding support for this TODO-Backend would make QOwnNotes independent of Nextcloud.

You can use every caldav server for it. There is no "todo-backend" solution in QOwnNotes. The Todo-List dialog "just" accesses a caldav server and manages its entries...

You cannot access a todo.txt from your mobile phones todo list application...

But there is a script `Checkbox preview and export` in the script directory that you may want to take a look at.

**Comment by joede** [comment]
> There is no "todo-backend" solution in QOwnNotes.

I know. That the reason for the feature request. ;-)

> You cannot access a todo.txt from your mobile phones todo list application...

I've tried [Markor](https://github.com/gsantner/markor) which can be seen as a Android counterpart to QOwnNotes. This app was the reason to add this feature request.

> But there is a script `Checkbox preview and export` in the script directory

Thanks. I will give it a try at the weekend.

**Comment by pbek** [comment]
QOwnNotes is about note taking in Markdown, not a gui for todo.txt files. There are other solutions for that. ;) Even the CalDAV feature shouldn't really be in there...

**Comment by pbek** [comment]
Thank you for your kind words and you concern.
