### ISSUE TITLE
AppImage not starting: "QOwnNotes: no version information available (required by QOwnNotes)"

### ISSUE THREAD

**Issue by kiuuik** [pbek/QOwnNotes#1002]
I tested in debian9 and ubuntu 1804.

I downloaded the appimage from opensuse site that your homepage links to. Then I made the file executable (which suffices for other appimages I have used). Then I try to execute it but just get this.

Do I miss something?
 
    ./QOwnNotes-1535197953.42c3b95c-Build1.1.glibc2.14-x86_64.AppImage 
    AppImage 
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: QOwnNotes: no version information available (required by QOwnNotes)
    QOwnNotes: relocation error: QOwnNotes: symbol  version  not defined in file  with link time reference

**Comment by pbek** [comment]
Strange, the AppImages are built by OBS, I haven't change anything since quite a while.

**Comment by pbek** [comment]
I've the same problem, but there is nothing I can do at the moment... Build log looks ok: <https://build.opensuse.org/package/live_build_log/home:pbek:QOwnNotes/desktop/AppImage/x86_64>

**Comment by pbek** [comment]
The problem still persists and I haven't found the cause or a solution.

**Comment by fodrice** [comment]
That's not only yours problem
https://github.com/AppImage/AppImageKit/issues/344
https://github.com/probonopd/linuxdeployqt/issues/313

" reference the error (no version information available (required by ./Ktube_Media_Downloader-x86_64.AppImage))
is usually given by ldd its not a fault of appimagekit."

**Comment by fodrice** [comment]
It seems there are some missing libs 
Launching old appimage gives libfuse error
"./QOwnNotes-1508773117.d18a9407-Build1.1.glibc2.3-i686.AppImage: error while loading shared libraries: libfuse.so.2: cannot open shared object file: No such file or directory"

**Comment by pbek** [comment]
Who can fix that? :/

**Comment by pbek** [comment]
@fodrice, thank you very much for your pull request! That did the trick!

I just tested https://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/AppImage/QOwnNotes-latest-x86_64.AppImage and it works again!

@kiuuik, @fodrice can you confirm that?

**Comment by fodrice** [comment]
Works for me.

**Comment by pbek** [comment]
Great, thank you for testing!
