### ISSUE TITLE
Download order on your webpage

### ISSUE THREAD

**Issue by kiuuik** [pbek/QOwnNotes#1003]
just a short, wild idea. Delete it without comment if you don't like it. I hope I don't tread on someones toes. 

If I go to https://www.qownnotes.org/installation I don't see the windows option because it's at the bottom of the page. Most people are used to windows (and mac) on the top. 

Linux users on the other hand are used to scrolling and picking the right package for their distribution. They have to carefully read the list and scroll anyways.

Maybe this would allow more people to benefit from your software who currently miss the windows optio - I know in theory you should scroll and also read all menu options but I regularly fail, see my "Schlagwort hinzufügen"-button-width issue.

**Comment by pbek** [comment]
I now move Windows or macOS to the top if those operating systems are detected on https://www.qownnotes.org/installation.

Does that work for you?

**Comment by rakekniven** [comment]
Gave it a try on Windows and Ubuntu. Works well. Will open it on my Mac at home later today.

You are fast as light :+1:

**Comment by pbek** [comment]
> Gave it a try on Windows and Ubuntu. Works well. Will open it on my Mac at home later today.

great, thank you!

> You are fast as light +1

Oh, I certainly try not to. I'm usually the considerate type of person. :)

**Comment by pbek** [comment]
Great, thank you for testing!
