### ISSUE TITLE
Find Action - extend with fuzzy search

### ISSUE THREAD

**Issue by kiuuik** [pbek/QOwnNotes#1007]
The "Find Action" window is really useful. But I think it could be even more so if the matching was more flexible.

If I type "export pdf" or "pdf export" I get no hits because the command ist "Export note as PDF".

**Comment by pbek** [comment]
## 18.08.10
- the **Find action** dialog now searches for every entered word (for [#1007](https://github.com/pbek/QOwnNotes/issues/1007))
    - all menu items that have one of the words in them will be shown

**Comment by pbek** [comment]
## 18.08.11
- the **Find action** dialog now searches for every entered word on in `and`-fashion
  (for [#1007](https://github.com/pbek/QOwnNotes/issues/1007))
    - all menu items that have all of the entered words (or parts of them) in 
      the name or tooltip will be shown

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
