### ISSUE TITLE
Reader Mode

### ISSUE THREAD

**Issue by jwfx** [pbek/QOwnNotes#1008]
Is there a way to turn this application into "reader mode"?

Basically I would like to see the same thing as the "Minimal" workspace, but instead of the editor being shown it should be only the preview (plus some navigation panels on the left side).

With a single button click it should be possible to get back to the regular edit mode. I guess that could already be done with two workspaces.

Maybe it is already possible and I couldn't find it, but in case it isn't, I think all that would be required to do is put the editor itself in a toggle-able and movable panel.

**Comment by pbek** [comment]
Yes, as you said: Just use two workspaces. And there is a button to activate the last active workspace. You can use that for toggling.

**Comment by jwfx** [comment]
But how can I hide the editor and only show the preview?

**Comment by jwfx** [comment]
Very nice, totally overlooked that option.

The tooltip of that option says panels would automatically resize on window resize. Is there anything that could be done against that?

In Visual Studio Code for example the left side panels always stays the same size, no matter of window size and only the rest of the panels in the window is auto-fitted to fill up the window. I find that a very user-friendly behavior.

Is there a way to achieve similar behavior?

**Comment by pbek** [comment]
> Is there a way to achieve similar behavior?

Yes, if the checkbox is turned on. :) Then the note-edit-panel acts as central widget and the layout manager will use it if the window gets resized.

**Comment by pbek** [comment]
> The tooltip of that option says panels would automatically resize on window resize. Is there anything that could be done against that?

something needs to be resized when the window gets resized...

**Comment by jwfx** [comment]
Well, sure. But it makes no sense to suddenly have all the small panels like tags and search, etc. take 50% of the screen. Those panels should stay at a fixed size on the side of the window and only the main panels like editor and preview should resize.

**Comment by pbek** [comment]
There were already long discussions about this topic, you can look it up in the other issues... The only solution that fitted almost all needs and was technically possible was this one checkbox. ;)

**Comment by jwfx** [comment]
That's disappointing, especially since literally every other application with panels works that way (Visual Studio, Visual Studio Code, Thunderbird, just to name a few). Then again I never touched Qt, so no idea what is possible there or not.

Anyways, thanks for your answers and your time.

**Comment by pbek** [comment]
That it's not even possible to lock the size of a dock widget dynamically is only one aspect of it...
An other are layouts like this: ![image](https://www.qownnotes.org/var/bekerle/storage/images/_aliases/frontpage_slider_full2/qownnotes/frontpage-slider/dockable-panels/4114-1-eng-GB/Dockable-panels.png)

**Comment by pbek** [comment]
If you are using the note edit panel as Central widget like those other applications do you don't have the resizing problem

Turning it off and gaining more flexibility is just an extra feature

**Comment by IzzySoft** [comment]
> There is an option you can turn off in the panel settings...

I couldn't find any matching option there. I toggled off "Use the note edit panel as fixed central widget" – but that was not the desired result (and unfortunately affected all workspaces). It then would be positioned differently, but not turned off. And if you referred to the *Window › Panels* menu: that doesn't list the editor window in its options. I'd prefer there was an option to expand the preview to cover the place the editor is using. Could e.g.

* be bound to the F4 function (jump to edit when not in it, toggle it off when in it) or
* be bound to the "disallow all note editing"
* be separate from both (e.g. a new icon with an "eye symbol" (aka "view only") and its own hotkey)

Also, using a different workspace just for reading mode *if you already have several other workspaces* (yes, I found the toggle button :wink:) requires multiple clicks (open the dropdown, click the desired workspace) – while the above could be achieved via a single hotkey.

The best I currently achieved was to minimize the editor to a "single row". What did I miss?

**Comment by pbek** [comment]
Yes, it's `Use the note edit panel as fixed central widget`. Then you can position all panels as you like.

> be bound to ...

did you check the *Shortcuts settings*? you can rewire most actions there

**Comment by IzzySoft** [comment]
Ugh. OK, not very intuitive, but possible. And then, how to "hide" the edit window?

**Comment by pbek** [comment]
> Ugh. OK, not very intuitive

it's meant for users that know why they want it (with all pros and contras)

> And then, how to "hide" the edit window?

"Window Menu, Panels", like every panel

**Comment by IzzySoft** [comment]
> "Window Menu, Panels", like every panel

Well, can you please look into that menu and tell me what item should correspond? Quoting myself from 4 comments above:

> And if you referred to the *Window › Panels* menu: that doesn't list the editor window in its options.

**Comment by pbek** [comment]
Did you turn off `Use the note edit panel as fixed central widget`?
