### ISSUE TITLE
Feature request: Support OPML

### ISSUE THREAD

**Issue by Letterus** [pbek/QOwnNotes#101]
For a long time my favorite app for taking notes (Mac OS X) was OmniOutliner. I do not want to use it anymore because of its proprietary file format. But I'd like to take notes using the OPML standard.

This would/should bring the following benefits (and maybe some more):
- structured notes using hierarchy
- folding and unfolding of structures in the UI - better overview
- creating tables (using multiple attributes in the corresponding OPML/XML file)
- adding notes to a node of the hierarchy
- an open, machine-readable standard, compatible to outliners, mind mapping software etc.

I know this is quite hard to implement, but it would be a killer feature I think. ;-)

**Comment by pbek** [comment]
Thank you for your request, @Letterus!
Wouldn't that break compatibility with ownCloud notes and the iOS and Android apps? :smile_cat:

**Comment by Letterus** [comment]
Hm, true. :-)
Would only be useful if those apps ignored anything but .md/.txt notes.

**Comment by pbek** [comment]
In my opinion OPML is far too much markup and not very suited for to be written by human hand. The same goes for HTML... QOwnNotes is for *plain text* notes, formatting is done with markdown syntax.

**Comment by Letterus** [comment]
Yes, plain text editing would be no solution for this. ;-)

**Comment by pbek** [comment]
I will close this feature request for now, but thank you for your suggestions!
