### ISSUE TITLE
[I] Moving multiple tags doesn't work

### ISSUE THREAD

**Issue by kthejoker** [pbek/QOwnNotes#1014]
#### Expected behaviour

Choosing multiple tags and "moving" them under a tag will move all selected tags under that parent tag.

#### Actual behaviour

The first selected tag moves under the parent tag, and then a random set of tags move under the tag.

#### Steps to reproduce

1. Select multiple tags.
2. Right click and move to a parent tag.

#### Relevant log output in the Log panel

```
[13:18:50] [status] Moved tag '@EdParker' to new tag
[13:18:50] [status] Moved tag '@BradMay' to new tag

When choosing @EdParker and @JohnDoe as tags to move.
```

#### Information about the application, settings and environment

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Thu Sep 6 13:20:31 2018`
**Version**: `18.08.11`
**Build date**: `Aug 29 2018`
**Build number**: `3817`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.10.1`
**Qt Version (runtime)**: `5.10.1`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\kyle.m.hale\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\content\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `23`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `21`
**localPath**: `C:\content\QOwnNotes\notes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\content\QOwnNotes\notes\notes.sqlite`

### Note folder `Work Week`

**id**: `2`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `C:\Users\kyle.m.hale\Nextcloud\Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\kyle.m.hale\Nextcloud\Notes\notes.sqlite`

## Settings

**ActiveNoteHistoryItem**: *empty*
**Debug/fakeOldVersionNumber**: `false`
**Debug/fileLogging**: `false`
**DistractionFreeMode/isEnabled**: `false`
**DistractionFreeMode/menuBarGeometry**: `<binary data>`
**DistractionFreeMode/menuBarHeight**: `21`
**DistractionFreeMode/menuBarVisible**: `true`
**DistractionFreeMode/windowState**: `<binary data>`
**Editor/CurrentSchemaKey**: `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing**: `true`
**Editor/autoBracketRemoval**: `true`
**Editor/editorWidthInDFMOnly**: `true`
**Editor/highlightCurrentLine**: `true`
**Editor/vimMode**: `false`
**IssueAssistantDialog/geometry**: `<binary data>`
**LastUpdateCheck**: `2018-09-06T13:04:19`
**LinkDialog/geometry**: `<binary data>`
**LogWidget/criticalLog**: `true`
**LogWidget/debugLog**: `true`
**LogWidget/fatalLog**: `true`
**LogWidget/infoLog**: `true`
**LogWidget/scriptingLog**: `true`
**LogWidget/statusLog**: `true`
**LogWidget/warningLog**: `true`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `24`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `Courier New,14,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `MS Shell Dlg 2,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl**: `false`
**MainWindow/showNotesFromAllNoteSubFolders**: `true`
**MainWindow/tagTreeWidgetExpandState-1**: `16`
**MessageBoxOverride/note-replace-links**: `16384`
**MessageBoxOverride/remove-note**: `16384`
**MessageBoxOverride/update-and-restart**: `16384`
**PiwikClientId**: `<hidden>`
**SearchEngineId**: `2`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**ShowSystemTray**: `false`
**StartHidden**: `false`
**UpdateDialog/geometry**: `<binary data>`
**WelcomeDialog/geometry**: `<binary data>`
**acceptAllExternalModifications**: `false`
**allowDifferentNoteFileName**: `false`
**allowNoteEditing**: `true`
**allowOnlyOneAppInstance**: `false`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `false`
**appMetrics/notificationShown**: `true`
**automaticNoteFolderDatabaseClosing**: `false`
**closeTodoListAfterSave**: `false`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**currentWorkspace**: `aeb0da30-69f4-4253-957f-374c177098b6`
**cursorWidth**: `1`
**customNoteFileExtensionList**: *empty*
**darkMode**: `false`
**darkModeColors**: `false`
**darkModeTrayIcon**: `false`
**defaultNoteFileExtension**: `md`
**demoNotesCreated**: `true`
**disableAutomaticUpdateDialog**: `false`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: *empty*
**fullyHighlightedBlockquotes**: `false`
**gitCommitInterval**: `30`
**gitExecutablePath**: *empty*
**gitLogCommand**: *empty*
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**imageScaleDown**: `false`
**imageScaleDownMaximumHeight**: `1024`
**imageScaleDownMaximumWidth**: `1024`
**insertTimeFormat**: *empty*
**interfaceLanguage**: *empty*
**internalIconTheme**: `false`
**itemHeight**: `15`
**localTrash/autoCleanupDays**: `30`
**localTrash/autoCleanupEnabled**: `true`
**localTrash/supportEnabled**: `true`
**markdownHighlightingEnabled**: `true`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `2`
**newNoteAskHeadline**: `false`
**noteEditIsCentralWidget**: `true`
**noteListPreview**: `false`
**noteSaveIntervalTime**: `10`
**noteSubfoldersPanelDisplayAsFullTree**: `true`
**noteSubfoldersPanelHideSearch**: `false`
**noteSubfoldersPanelOrder**: `0`
**noteSubfoldersPanelShowFullPath**: `false`
**noteSubfoldersPanelShowNotesRecursively**: `false`
**noteSubfoldersPanelShowRootFolderName**: `true`
**noteSubfoldersPanelSort**: `0`
**notesPanelOrder**: `0`
**notesPanelSort**: `1`
**notesPath**: `C:/content/QOwnNotes/notes`
**notifyAllExternalModifications**: `false`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: *empty*
**ownCloud/supportEnabled**: `false`
**ownCloud/todoCalendarBackend**: `3`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloud/userName**: *empty*
**previousWorkspace**: `9456950f-be91-4dd8-a1c9-839930b3e7d4`
**restoreCursorPosition**: `true`
**savedSearches/noteFolder-1**: `Note 2018-09-06T13.02.45, Note 2018-09-06T13.02.30, Note 2018-09-05T19.54.39, 2018 July Ignition Feedback, 2018.09.03 EDPR Deal Shaping, 2018.09.03, 2018, Note 2018-08-27T15.22.49, Note 2018-08-27T12.15.06, Note 2018-08-27T07.30.25, Ignition Presentation Feedback, Ignition Todo, Priority Skills Dashboard Stuff, Note 2018-08-08T11.17.11, Note 2018-08-07T12.06.51, Note 2018-08-07T10.28.56, Note 2018-08-07T10.01.19, Note 2018-08-04T12.15.32, Ignition Analytics, Food Options, AT&T WOrkshop Email`
**showMenuBar**: `true`
**showStatusBar**: `true`
**skipVersion**: `18.09.0`
**tagWasAddedToNote**: `true`
**taggingShowNotesRecursively**: `false`
**tagsPanelHideSearch**: `false`
**tagsPanelOrder**: `0`
**tagsPanelSort**: `0`
**toolbar/1/items**: `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name**: `mainToolBar`
**toolbar/1/title**: `main toolbar`
**toolbar/2/items**: `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name**: `formattingToolbar`
**toolbar/2/title**: `formatting toolbar`
**toolbar/3/items**: `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name**: `insertingToolbar`
**toolbar/3/title**: `inserting toolbar`
**toolbar/4/items**: `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name**: `encryptionToolbar`
**toolbar/4/title**: `encryption toolbar`
**toolbar/5/items**: `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name**: `windowToolbar`
**toolbar/5/title**: `window toolbar`
**toolbar/6/items**: `action_Quit`
**toolbar/6/name**: `quitToolbar`
**toolbar/6/title**: `quit toolbar`
**toolbar/size**: `6`
**useUNIXNewline**: `false`
**workspace-9456950f-be91-4dd8-a1c9-839930b3e7d4/name**: `full`
**workspace-9456950f-be91-4dd8-a1c9-839930b3e7d4/noteSubFolderDockWidgetVisible**: `true`
**workspace-9456950f-be91-4dd8-a1c9-839930b3e7d4/windowState**: `<binary data>`
**workspace-aeb0da30-69f4-4253-957f-374c177098b6/name**: `AI`
**workspace-aeb0da30-69f4-4253-957f-374c177098b6/noteSubFolderDockWidgetVisible**: `true`
**workspace-aeb0da30-69f4-4253-957f-374c177098b6/windowState**: `<binary data>`
**workspace-e225f185-cadc-4789-8a61-b6fa47889713/name**: `minimal`
**workspace-e225f185-cadc-4789-8a61-b6fa47889713/noteSubFolderDockWidgetVisible**: `true`
**workspace-e225f185-cadc-4789-8a61-b6fa47889713/windowState**: `<binary data>`
**workspaces**: `9456950f-be91-4dd8-a1c9-839930b3e7d4, e225f185-cadc-4789-8a61-b6fa47889713, aeb0da30-69f4-4253-957f-374c177098b6`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\kyle.m.hale\AppData\Roaming`
**ChocolateyInstall**: `C:\ProgramData\chocolatey`
**ChocolateyLastPathUpdate**: `Wed Sep 13 18:42:55 2017`
**ChocolateyToolsLocation**: `C:\tools`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `WIN-DQBIHXO1VL`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**FSHARPINSTALLDIR**: `C:\Program Files (x86)\Microsoft SDKs\F#\10.1\Framework\v4.0\`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\kyle.m.hale`
**LOCALAPPDATA**: `C:\Users\kyle.m.hale\AppData\Local`
**LOGONSERVER**: `\\FRAPDCCP02`
**MSMPI_BIN**: `C:\Program Files\Microsoft MPI\Bin\`
**NUMBER_OF_PROCESSORS**: `4`
**OneDrive**: `C:\Users\kyle.m.hale\OneDrive - Avanade`
**OS**: `Windows_NT`
**Path**: `C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\PuTTY\;C:\WINDOWS\System32\OpenSSH\;C:\Users\kyle.m.hale\AppData\Roaming\Microsoft\ToolsForAI\RuntimeSDK\cntk\cntk;C:\Users\kyle.m.hale\AppData\Local\Programs\Python\Python35\Scripts\;C:\Users\kyle.m.hale\AppData\Local\Programs\Python\Python35\;C:\Oracle;C:\Oracle\bin;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 142 Stepping 9, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `8e09`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\;C:\Program Files\WindowsPowerShell\Modules\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\Storage\`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\KYLEM~1.HAL\AppData\Local\Temp`
**TMP**: `C:\Users\KYLEM~1.HAL\AppData\Local\Temp`
**UATDATA**: `C:\windows\CCM\UATData\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77`
**USERDNSDOMAIN**: `CORP.AVANADE.ORG`
**USERDOMAIN**: `AVANADE-CORP`
**USERDOMAIN_ROAMINGPROFILE**: `AVANADE-CORP`
**USERNAME**: `kyle.m.hale`
**USERPROFILE**: `C:\Users\kyle.m.hale`
**VS140COMNTOOLS**: `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\`
**windir**: `C:\WINDOWS`

**Comment by pbek** [comment]
## 18.09.1
- prevented possible misbehavior when moving multiple tags to another tag

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by kthejoker** [comment]
I can confirm this is working as intended in the new release. Thanks for the quick response!

**Comment by pbek** [comment]
Great, thank you for testing!
