### ISSUE TITLE
[I] Error opening linked note when its name Cyrillic

### ISSUE THREAD

**Issue by Snousmoumryk** [pbek/QOwnNotes#1017]
#### Expected behaviour

Links to notes with Cyrillic file names should not be punycode translated because they are links to files in local file system

#### Actual behaviour

Links to notes with cyrillic file names are treated like web links and translated to punycode, which causes a note search error.

#### Steps to reproduce

* Create two notes, one with English name and the other with Cyrillic (for example "гастрономия", punycode "xn--80afqpefbnik3m")
* Make link in English note to Cyrillic note
* Try to follow the link and get error "Note xn--80afqpefbnik3m not found"

#### Relevant log output in the Log panel

```
[15:56:05] [debug] on_noteTextView_anchorClicked - 'url': QUrl("note://xn--80afqpefbnik3m")
```

#### Information about the application, settings and environment

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Пт сен 7 15:56:39 2018`
**Version**: `18.09.0`
**Build date**: `Sep  6 2018`
**Build number**: `3826`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.10.1`
**Qt Version (runtime)**: `5.10.1`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\serge\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Program Extra\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `ru_RU`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `23`
**Enabled scripts**: `2`

## Server Info

**serverUrl**: `http://192.168.1.2:60080/nextcloud`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `13.0.6.1`
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `по умолчанию`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `1`
**localPath**: `C:\Users\serge\Nextcloud\Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\serge\Nextcloud\Notes\notes.sqlite`

### Script `Checkbox preview and export`

**id**: `1`
**path**: `C:\Users\serge\AppData\Roaming\PBE\QOwnNotes\scripts\export-checkboxes\export-checkboxes.qml`
**variablesJson**: *empty*
**identifier**: `export-checkboxes`
**version**: `0.0.2`
**minAppVersion**: `17.12.0`

### Script `Disable read-only mode on note double-click`

**id**: `2`
**path**: `C:\Users\serge\AppData\Roaming\PBE\QOwnNotes\scripts\disable-readonly-mode\disable-readonly-mode.qml`
**variablesJson**: *empty*
**identifier**: `disable-readonly-mode`
**version**: `1.0.0`
**minAppVersion**: `18.08.1`

## Settings

**ActiveNoteHistoryItem**: *empty*
**Debug/fakeOldVersionNumber**: `false`
**Debug/fileLogging**: `false`
**Editor/CurrentSchemaKey**: `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing**: `true`
**Editor/autoBracketRemoval**: `true`
**Editor/editorWidthInDFMOnly**: `true`
**Editor/highlightCurrentLine**: `true`
**Editor/vimMode**: `false`
**IssueAssistantDialog/geometry**: `<binary data>`
**LastUpdateCheck**: `2018-09-07T15:45:02`
**LinkDialog/geometry**: `<binary data>`
**LinkDialog/lastSelectedFileUrl**: `file:///C:/Users/serge/Nextcloud/Notes/%D0%9F%D0%BE%D0%BA%D1%83%D0%BF%D0%BA%D0%B8/%D0%93%D0%B8%D0%B3%D0%B8%D0%B5%D0%BD%D0%B0.md`
**LogWidget/criticalLog**: `true`
**LogWidget/debugLog**: `true`
**LogWidget/fatalLog**: `true`
**LogWidget/infoLog**: `true`
**LogWidget/scriptingLog**: `true`
**LogWidget/statusLog**: `true`
**LogWidget/warningLog**: `true`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `42`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `Courier New,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `MS Shell Dlg 2,8.14286,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl**: `false`
**MainWindow/showNotesFromAllNoteSubFolders**: `false`
**NoteDialog/geometry**: `<binary data>`
**PiwikClientId**: `<hidden>`
**ScriptRepositoryDialog/geometry**: `<binary data>`
**ScriptRepositoryDialog/mainSplitterState**: `<binary data>`
**SearchEngineId**: `0`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**ShowSystemTray**: `false`
**StartHidden**: `false`
**TodoDialog/geometry**: `<binary data>`
**TodoDialog/mainSplitterState**: `<binary data>`
**TodoDialog/showCompletedItems**: `0`
**TodoDialog/todoListSelectorSelectedItem**: `Личное`
**UpdateDialog/geometry**: `<binary data>`
**WelcomeDialog/geometry**: `<binary data>`
**acceptAllExternalModifications**: `false`
**allowDifferentNoteFileName**: `false`
**allowNoteEditing**: `true`
**allowOnlyOneAppInstance**: `true`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `false`
**appMetrics/notificationShown**: `true`
**automaticNoteFolderDatabaseClosing**: `false`
**closeTodoListAfterSave**: `false`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**currentWorkspace**: `7e3c68c8-49f7-4c80-ba10-06a8c3db230c`
**cursorWidth**: `1`
**customNoteFileExtensionList**: *empty*
**darkMode**: `false`
**darkModeColors**: `false`
**darkModeTrayIcon**: `false`
**defaultNoteFileExtension**: `md`
**disableAutomaticUpdateDialog**: `false`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: *empty*
**fullyHighlightedBlockquotes**: `false`
**gitCommitInterval**: `30`
**gitExecutablePath**: *empty*
**gitLogCommand**: *empty*
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**imageScaleDown**: `false`
**imageScaleDownMaximumHeight**: `1024`
**imageScaleDownMaximumWidth**: `1024`
**insertTimeFormat**: *empty*
**interfaceLanguage**: *empty*
**internalIconTheme**: `false`
**itemHeight**: `25`
**localTrash/autoCleanupDays**: `30`
**localTrash/autoCleanupEnabled**: `true`
**localTrash/supportEnabled**: `true`
**markdownHighlightingEnabled**: `true`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `2`
**newNoteAskHeadline**: `false`
**noteEditIsCentralWidget**: `true`
**noteListPreview**: `false`
**noteSaveIntervalTime**: `10`
**noteSubfoldersPanelDisplayAsFullTree**: `true`
**noteSubfoldersPanelHideSearch**: `false`
**noteSubfoldersPanelOrder**: `0`
**noteSubfoldersPanelShowFullPath**: `false`
**noteSubfoldersPanelShowNotesRecursively**: `true`
**noteSubfoldersPanelShowRootFolderName**: `true`
**noteSubfoldersPanelSort**: `0`
**notesPanelOrder**: `0`
**notesPanelSort**: `0`
**notesPath**: `C:/Users/serge/Nextcloud/Notes`
**notifyAllExternalModifications**: `false`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: `http://192.168.1.2:60080/nextcloud`
**ownCloud/supportEnabled**: `true`
**ownCloud/todoCalendarBackend**: `3`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/todoCalendarDisplayNameList**: `Личное`
**ownCloud/todoCalendarEnabledList**: `Личное`
**ownCloud/todoCalendarEnabledUrlList**: `http://192.168.1.2:60080/nextcloud/remote.php/dav/calendars/Sergey/personal/`
**ownCloud/todoCalendarUrlList**: `http://192.168.1.2:60080/nextcloud/remote.php/dav/calendars/Sergey/personal/`
**ownCloud/userName**: `Sergey`
**ownCloudInfo/appIsValid**: `true`
**ownCloudInfo/connectionErrorMessage**: `Неизвестная ошибка`
**ownCloudInfo/notesPathExistsText**: `yes`
**ownCloudInfo/serverVersion**: `13.0.6.1`
**previousWorkspace**: `63208677-c9ad-4f72-8e54-e29c661289d3`
**restoreCursorPosition**: `true`
**savedSearches/noteFolder-1**: `test-note, Все покупки, Гастрономия, Колониальные, Птица, Мясо, Кондитерские, Фрукты, Овощи, Заморозка, Молочные, Гигиена, Консервы, Табак, Хлопья, Приправы, Канцелярия`
**showMenuBar**: `true`
**showStatusBar**: `true`
**tagWasAddedToNote**: `true`
**taggingShowNotesRecursively**: `true`
**tagsPanelHideSearch**: `false`
**tagsPanelOrder**: `0`
**tagsPanelSort**: `0`
**toolbar/1/items**: `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name**: `mainToolBar`
**toolbar/1/title**: `Главная панель инструментов`
**toolbar/2/items**: `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name**: `formattingToolbar`
**toolbar/2/title**: `панель инструментов форматирования`
**toolbar/3/items**: `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name**: `insertingToolbar`
**toolbar/3/title**: `панель инструментов вставки`
**toolbar/4/items**: `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name**: `encryptionToolbar`
**toolbar/4/title**: `панель инструментов шифрования`
**toolbar/5/items**: `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name**: `windowToolbar`
**toolbar/5/title**: `панель инструментов окна`
**toolbar/6/items**: `action_Quit`
**toolbar/6/name**: `quitToolbar`
**toolbar/6/title**: `Панель инструментов выхода`
**toolbar/size**: `6`
**useUNIXNewline**: `false`
**workspace-63208677-c9ad-4f72-8e54-e29c661289d3/name**: `на весь экран`
**workspace-63208677-c9ad-4f72-8e54-e29c661289d3/noteSubFolderDockWidgetVisible**: `true`
**workspace-63208677-c9ad-4f72-8e54-e29c661289d3/windowState**: `<binary data>`
**workspace-7e3c68c8-49f7-4c80-ba10-06a8c3db230c/name**: `минимальный`
**workspace-7e3c68c8-49f7-4c80-ba10-06a8c3db230c/noteSubFolderDockWidgetVisible**: `true`
**workspace-7e3c68c8-49f7-4c80-ba10-06a8c3db230c/windowState**: `<binary data>`
**workspaces**: `63208677-c9ad-4f72-8e54-e29c661289d3, 7e3c68c8-49f7-4c80-ba10-06a8c3db230c`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\serge\AppData\Roaming`
**CARBON_MEM_DISABLE**: `1`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `MOOMINPAPPA`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**configsetroot**: `C:\WINDOWS\ConfigSetRoot`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\serge`
**KOMPAS_SDK**: `C:\Program Files\ASCON\KOMPAS-3D v17 Study\SDK\`
**LOCALAPPDATA**: `C:\Users\serge\AppData\Local`
**LOGONSERVER**: `\\MOOMINPAPPA`
**NUMBER_OF_PROCESSORS**: `4`
**OneDrive**: `C:\Users\serge\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\PuTTY\;C:\Users\serge\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 142 Stepping 9, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `8e09`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\serge\AppData\Local\Temp`
**TMP**: `C:\Users\serge\AppData\Local\Temp`
**USERDOMAIN**: `MOOMINPAPPA`
**USERDOMAIN_ROAMINGPROFILE**: `MOOMINPAPPA`
**USERNAME**: `serge`
**USERPROFILE**: `C:\Users\serge`
**VBOX_MSI_INSTALL_PATH**: `C:\Program Files\Oracle\VirtualBox\`
**windir**: `C:\WINDOWS`

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue. Might be an internal thing of Qt's `QUrl` and hard to get around...

**Comment by pbek** [comment]
When I created a link it gave me `[гастрономия](note://гастрономия)` and that link worked for me. How did you get your link?

**Comment by Snousmoumryk** [comment]
Android [Nextcloud Notes](https://github.com/stefan-niedermann/nextcloud-notes) makes *Categories* (note labels) as Notes subfolders and moves md files to them. I've got my *master note* and *linked subnotes* in one of these subfolders.
Reported error occurs in two steps scenario:
1. Choose desired subfolder in the **left** pane *Nested folders* block, then point to *master note* to see its content in the **right** pane.
2. Move cursor in *Nested folders* block to any other folder, then try to follow the link in the **right** pane where the *master note* is still active.

**Comment by Snousmoumryk** [comment]
Did extra tests and here is my observation:
* linked notes are searched within folder/subfolder where the note itself is located
* *Link insert* menu shows available  notes from the folder selected in the *Nested folders* block
* Reported error mistakenly linked the **Interface focus lost** to **Note name encoding** and should be renamed.

Do you have any objections to renaming?

**Comment by pbek** [comment]
> inked notes are searched within folder/subfolder where the note itself is located
> Link insert menu shows available notes from the folder selected in the Nested folders block

yes, that's true

> Reported error mistakenly linked the Interface focus lost to Note name encoding and should be renamed.

I'm not sure I understand what you are talking about :)

And I don't understand your first comment neither. :)
Are we still talking about linking notes here?

**Comment by Snousmoumryk** [comment]
At first I thought the error was related to the Cyrillic name of the note.

Subsequent tests have shown that the problem occurs when:
* you change current  folder on the **left** pane,
* but app does not change the content on the **right** pane
* and tries to follow the links in an new current folder.

Looking at the links for one folder and follow them in another folder...
Do you think it's wrong app behavior?

**Comment by pbek** [comment]
So what you were talking about is the fish to link to notes in other sub-folders? Like: #478

**Comment by pbek** [comment]
> Looking at the links for one folder and follow them in another folder...
> Do you think it's wrong app behavior?

the links always work just in the current note folder...
I'm not sure if the current note should vanish from the note edit if the note folder was changed just to prevent your described behavior...

**Comment by Snousmoumryk** [comment]
> the links always work just in the current note folder...

That's fine and we can name it _feature_ but not a _bug_.

Why, then, the **app UI** (Ctrl-L menu) **allows user** to insert links to notes from a different folder?

Following the logic in the quote above, such an attempt should be rejected with a warning message.

**Comment by pbek** [comment]
> Why, then, the app UI (Ctrl-L menu) allows user to insert links to notes from a different folder?

thank you, I will take a look at this

**Comment by pbek** [comment]
> Why, then, the app UI (Ctrl-L menu) allows user to insert links to notes from a different folder?

It currently only allows that if `All notes` is selected in the note folder panel.

**Comment by pbek** [comment]
Please jump to #478, I now implemented linking to notes in note sub-folders.
