### ISSUE TITLE
Make updating easier on OS X

### ISSUE THREAD

**Issue by Letterus** [pbek/QOwnNotes#102]
Currently updating the app is a little bit complicated using OS X: You have to download the dmg file, install the app manually and then change the security settings (right click, open, admin password) to make the app run after an update.

Proposals:
1. Sign the app using a certificate from Apple to make the app run after an update immediately (via click into the dock f.e.)
2. Use an automated updating solution
     a. The app store (limited to OS X)
     b. Using the Qt Installer Framework - http://doc.qt.io/qtinstallerframework/index.html - I've no experiences with this. Looks like it would require to build and update the app in splitted packages?

**Comment by pbek** [comment]
Thank you for your suggestions!
1. Yes, would be great, although it requires a 100 EUR per year Apple Developer Account
2. Suggestions are welcome what would work here for Qt
3. Yes, would be nice, although it requires a 100 EUR per year Apple Developer Account, is a big pain to create and maintain (can't be automated), each update can take a week or two until Apple approves it and it's not even clear if Apple will allow a Qt App
4. I have to look into that, if that's what ownCloud is using for it's client then it needs even more clicks. :)

**Comment by dgirke** [comment]
how about delivering upates less often? Every two weeks or so. In the meantime I'lI switch to manual update check. For me the app is great as it is, but smaller improvements (even those i can't imagine) are very much appreciated 😀

**Comment by pbek** [comment]
I see only disadvantages in letting everyone who has requested a feature (including myself) wait for an arbitrary time. You can always turn off the update dialog in the settings, you will then still see if there is an update in the status bar.

**Comment by minthemiddle** [comment]
Maybe Mendeley's Updater library might work, as described [here](http://stackoverflow.com/a/7378048). It was built for Qt.

**Comment by pbek** [comment]
Thank you for your suggestions, I noted it. Seems like quite some work, I will look at that some day.

**Comment by minthemiddle** [comment]
There was a link to another library which might be simpler to implement. I'm just adding it (despite not knowing much about `Qt`): [Fervor](https://github.com/klokantech/fervor) (I linked to the most recent and recommended fork of it).

**Comment by pbek** [comment]
It must be able to build with qmake and cmake and somehow be able to do that from Travis CI and Appveor...

**Comment by pbek** [comment]
@markandrewj was mentioning Sparkle in #314.

The update detection part is already implemented, only something to download and install the new package (for both Windows and OS X) would be needed. Plus I'm not sure if that would work under OS X without having an Apple certificate.

**Comment by markandrewj** [comment]
Hey, sounds great. I left a little bit more information on sparkle and another package that could be an option on our other thread. You do not need an Apple certificate https://sparkle-project.org/documentation/ "Sign the dmg using macOS 10.11.5 or later if you have a Developer ID Application certificate available from Apple". I did not realize you were done the implementation though. Happy to hear that.

**Comment by pbek** [comment]
I meant you already should get an update dialog with the changes from the changelog and a download button. But you need to install the dmg yourself.

**Comment by markandrewj** [comment]
I do already, however with the package being rebuilt so frequently it is somewhat inconvenient. The one day this week I installed the new package three times in a row, where about 5 minutes after installing there was a new package :)

I am glad is being developed actively though.

**Comment by pbek** [comment]
That must have been a very old update dialog, I guess there were no two updates on one day for a long time...

**Comment by markandrewj** [comment]
That is strange, because it was a fresh install and happened on both desktop clients (Linux and Mac).

**Comment by pbek** [comment]
There are two ways that come to mind.
1) The app already has opened an update notification that wasn't reacted to and thus didn't open a new notification (the following days). (I will see if I can improve that)
2) The app was installed and by coincidence some time later there already was an update.

**Comment by pbek** [comment]
## 16.09.6
- when automatically checking for application updates the update dialog
  will now be refreshed even if it is already open if there is an even
  newer version available
    - this should prevent the user from downloading an old version and
      getting a new update dialog after updating and starting the
      application again

@markandrewj, this should prevent the "old version" problem

**Comment by Siedlerchr** [comment]
I would really like to have an installer for Windows, too!
On another open Source project (Java) I contribute too, [JabRef](https://github.com/JabRef/jabref) , we use CircleCI/Travis CI to automatically build binaries and an installer. We are using install4j, but that seems to only work with Java.

**Comment by pbek** [comment]
Are we talking about installers (where there are also people that are glad that there isn't one under Windows) or "automatic updates"? In what way would an installer help?

**Comment by Siedlerchr** [comment]
@pbek  Both! Real installers. With uninstall support. On Windows I hate zip files.
Reason is simple: No manual cleanup. No manual copying/extracting files to dirs.

Regarding updates: Either a direct update or the option to download the latest version of the installer and upgrading the app on installing.

**Comment by pbek** [comment]
I'm all open for pull requests. 🎉

**Comment by pbek** [comment]
@Siedlerchr 
Since a week I'm working on an auto updater for Windows... Very hard labor with a lots of road blocks.
I've made a different issue for it, so you can subscribe and we can discuss: #376

Afterwards I will start a similar thing for Mac OS...

**Comment by pbek** [comment]
If all works well we'll have an updater for macOS this week... I had to sort out a lot of problems with the Qt library in the macOS build first... a very painful job...

**Comment by markandrewj** [comment]
That would be awesome :D I was going to give this a go if nothing changed, I am happy to hear that you may have it figured out though.

**Comment by pbek** [comment]
## 16.11.3
- there are now **automatic updates** for **macOS**
    - in the update dialog you will see a new `Update` button
    - if you press it a script will be loaded after a confirmation to 
      download the latest version of QOwnNotes and update your current
      installation
    - after the update QOwnNotes will be started again
    - please use the checkbox `Fake old version number to trigger update`
      in the `Debug options` and click `Check for updates` in the `Help`
      main menu to test the update process and provide feedback

There now is a new release, could you please test it and report if the new features work for you?

**Comment by pbek** [comment]
@Letterus @dgirke @minthemiddle @markandrewj can you please test the new updater under macOS ;)

**Comment by Letterus** [comment]
Thanks a lot for implementing this! I hope I'll have some spare time tomorrow. Then I'd really like to test it.

**Comment by pbek** [comment]
Thank you @Letterus, you can update to 16.11.3 manually and then use the debug setting to update to the same version again via the updater.

The update systems were quite some troublesome work. I hope they are of some use and are actually working for everyone.

**Comment by minthemiddle** [comment]
Thanks a lot for the updater! Sure will I test it on macOS, I just downloaded `16.11.3` and am waiting for updates. The update window looks fine and I'm optimistic that the updates will work as well. Will comment once the first auto update happened.

**Comment by pbek** [comment]
@minthemiddle 

> you can update to 16.11.3 manually and then use the debug setting to update to the same version again via the updater

**Comment by minthemiddle** [comment]
Oh, got it. For everyone else struggling to find the `debug setting`, it is in the general settings' window:

![bildschirmfoto 2016-11-05 um 11 55 45](https://cloud.githubusercontent.com/assets/1950766/20029523/7a3813c4-a34e-11e6-9152-2bd1d8f29cc2.png)

**Comment by minthemiddle** [comment]
Actually, I get an error message (in a terminal that opens) when trying to trigger update via the debug option:

```
Last login: Sat Nov  5 11:50:32 on ttys002
You have mail.
/Applications/QOwnNotes.app/Contents/MacOS/update.command ; exit;
main~ main$ /Applications/QOwnNotes.app/Contents/MacOS/update.command ; exit;
QOwnNotes macOS updater script

diskImageUrl is empty
```

**Comment by Letterus** [comment]
Just tried it. ;)
The script seems not to anything:

`/Applications/QOwnNotes.app/Contents/MacOS/update.command ; exit;`
QOwnNotes macOS updater script
diskImageUrl is empty
Press [Enter] key to end...

**Comment by Letterus** [comment]
Ah. Two tests, same result. ;)

**Comment by pbek** [comment]
Thank you for testing. The parameters for the script are passed as environment variables to the updater script (because there was no other way to do it in macOS).

That works perfectly on my MacBook, but it seems it doesn't work for you.

Could you please edit `QOwnNotes.app/Contents/MacOS/update.command` and add an `env` to (for example) line 7 to output the enviroment and start the update process again.

**Comment by pbek** [comment]
There should be a `QOWNNOTES_RELEASE_URL` and a `QOWNNOTES_APPLICATIONS_PATH` variable...

**Comment by Letterus** [comment]
No, there is none of those in the output.

**Comment by pbek** [comment]
macOS doesn't routes those parameters when the script is opened with `open` (and we need to do that otherwise we get no visible terminal)

**Comment by pbek** [comment]
it took me three hours to figure a way to pass parameters...

**Comment by Letterus** [comment]
Ah, weird. Maybe hardcode an API URL and then get the needed parameters using curl and the script location?

**Comment by pbek** [comment]
That will not work that way...
I'm now creating a temporary script file with the parameters hard-wired and run this script.

When <https://travis-ci.org/pbek/QOwnNotes/jobs/173483105> is done building you should be able to see a disk image on <https://github.com/pbek/QOwnNotes/releases>.

The file you are looking for will be named `QOwnNotesDev-73428d7799094b512e861eefd05512898942948a.dmg`. Can you please test the update process with it (after you installed it manually).

**Comment by pbek** [comment]
the dmg is ready: <https://github.com/pbek/QOwnNotes/releases/download/dev-macosx-b2446-120104/QOwnNotesDev-73428d7799094b512e861eefd05512898942948a.dmg>

**Comment by markandrewj** [comment]
The updater seemed to work ok for me. The only thing that is a bit weird is that it opens terminal, and I use iterm, but it is much less of a hassle then downloading the new images. It may have been easier to make a cask for this though: [https://caskroom.github.io/](https://caskroom.github.io/). You were asking if this feature was really of any use for people, and for myself I can say it is. With the Travis builds, I get asked to update fairly frequent. If I only had to upgrade every 5 months, it wouldn't be as much of a bother. For Linux, I do my upgrades through the console, and it is much cleaner then the GUI that was available previously.

![screen shot 2016-11-05 at 11 38 55 pm](https://cloud.githubusercontent.com/assets/142597/20035603/66b36ee4-a3b1-11e6-813d-f18efd087fe3.png)

**Comment by pbek** [comment]
@markandrewj thank you for testing!

> The updater seemed to work ok for me.

Which version of QOwnNotes were you testing? The regular 16.11.3 or the dmg of my above comment?
From the looks it was the regular version.
Could you please also test the latest version: <https://github.com/pbek/QOwnNotes/releases/download/dev-macosx-b2446-120104/QOwnNotesDev-73428d7799094b512e861eefd05512898942948a.dmg>
It's the same script but with parameters hard-coded because @Letterus and @minthemiddle seemed to had problems with the regular version.

> I also worry a little when I see my other partitions.

You can take a look at the script, it's printed in the first line of your output.
It just mounts the QOwnNotes.dmg and uses rsync to copy the files.
Homebrew would be nice, but how many people would use it?

> The only thing that is a bit weird is that it opens terminal.

The homebrew version of Qt 5.7 (I would have needed 5.7 for downloading the QOwnNotes.dmg because GitHub uses http redirects) wasn't deployable because of library path problems... So I ended up with a script.
I put much effort to use a visible script so that the user at least sees what happens...

> For Linux, I do my upgrades through the console.

What distribution (and version) do you use? Ubuntu 14.04? Because there are repositories for almost everything else on <http://www.qownnotes.org/installation>...

**Comment by markandrewj** [comment]
Hey @pbek, no problem. Thanks for working on this. I was trying the regular 16.11.3. I will give the latest a try tomorrow for you, I am just heading to bed at the moment. I will take a look at the script. If you look at the screen shot though, there was one issue. It runs find and receives permission denied for .trashes. To bad that homebrew was not viable. I do not have a problem with it opening the terminal, I just meant I usually use [https://www.iterm2.com/](https://www.iterm2.com/), not apple terminal. So I end up with an extra terminal when I have iterm open, which is not a big issue. It is probably the right choice to see what is happening, but part of me just wants to background the script. As far as Linux, I was saying it is easy to upgrade, not hard. I use Ubuntu 16.04 and upgrade using apt.

**Comment by pbek** [comment]
> It runs find and receives permission denied for .trashes.

Thank you for your feedback, @markandrewj. I rewrote that part so that no warning will be triggered in <https://github.com/pbek/QOwnNotes/releases/download/dev-macosx-b2451-075959/QOwnNotesDev-1f5e375a273af876c6f07619a5b343c22a0460d5.dmg>

> To bad that homebrew was not viable.

It would if all macOS users would use it...

> I just meant I usually use https://www.iterm2.com/, not apple terminal.

I just do an `open` command on a command script. Apple decides what terminal application to use...

> I use Ubuntu 16.04

So (I hope) you do use the Ubuntu Launchpad repository of QOwnNotes, don't you?

**Comment by pbek** [comment]
## 16.11.4
- the process for the automatic updates in macOS was improved because of
  problems of some users

@markandrewj 
There now is a new release, could you please test it and report if the update process worked (and then test a 2nd time with the debug setting to update with the new update script)

@Letterus,  @minthemiddle you will have to use the manual update and then test the update process with the debug settings

**Comment by Letterus** [comment]
Tested 16.11.4: I get a GUI error message: "Could not find updater file:
update.command"

**Comment by pbek** [comment]
I'm getting the same message now and I have no idea why I didn't get it earlier... Seems to be a working path problem, I will put the script in a resource file... The endless wonders of macOS. :) Thank you for confirming, @Letterus.

**Comment by pbek** [comment]
@Letterus, can you please try <https://github.com/pbek/QOwnNotes/releases/download/dev-macosx-b2456-164348/QOwnNotesDev-bd14e381850b56af35bef732854f1d7212866c9b.dmg>

**Comment by Letterus** [comment]
@pbek Yep, works. And most interesting: I do not even reauth with admin privileges for starting without dev certificate. Seems the macOS sandbox is easily crackable or it recognized the files did not change. ;)

**Comment by pbek** [comment]
With the update script I never had to do any manual intervention... Did you have to do anything at any time with a version of the script?

**Comment by Letterus** [comment]
Nope, it just ran. Seems like a very nice solution. Maybe the sandbox will pop up once there are binary changes, but we will see. :)

**Comment by pbek** [comment]
There should be binary changes. Didn't your rsync sync something?

**Comment by Letterus** [comment]
It did. I just did not follow it in detail. ;-)

**Comment by markandrewj** [comment]
Hey @pbek, I used the recent update you suggested @Letterus try, and it worked for me as well. 

```
 tinymouse@mybighost ~  /var/folders/mq/kk__tp6j39z082r1dn9d4rh40000gn/T/QOwnNotes-Updater-f22732.command ; exit;
QOwnNotes macOS updater script

Created temporary directory /var/folders/mq/kk__tp6j39z082r1dn9d4rh40000gn/T/tmp.qhSw1VF8
Downloading https://github.com/pbek/QOwnNotes/releases/download/macosx-b2455-085744/QOwnNotes-16.11.4.dmg...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   598    0   598    0     0   1143      0 --:--:-- --:--:-- --:--:--  1143
100 19.3M  100 19.3M    0     0  1395k      0  0:00:14  0:00:14 --:--:-- 1583k
Checksumming Protective Master Boot Record (MBR : 0)…
Protective Master Boot Record (MBR :: verified   CRC32 $4C331E01
Checksumming GPT Header (Primary GPT Header : 1)…
 GPT Header (Primary GPT Header : 1): verified   CRC32 $F2C51D38
Checksumming GPT Partition Data (Primary GPT Table : 2)…
GPT Partition Data (Primary GPT Tabl: verified   CRC32 $1A2AE433
Checksumming  (Apple_Free : 3)…
                    (Apple_Free : 3): verified   CRC32 $00000000
Checksumming disk image (Apple_HFS : 4)…
......................................................................................................................................................................................................
          disk image (Apple_HFS : 4): verified   CRC32 $BB91BB2F
Checksumming  (Apple_Free : 5)…
                    (Apple_Free : 5): verified   CRC32 $00000000
Checksumming GPT Partition Data (Backup GPT Table : 6)…
GPT Partition Data (Backup GPT Table: verified   CRC32 $1A2AE433
Checksumming GPT Header (Backup GPT Header : 7)…
  GPT Header (Backup GPT Header : 7): verified   CRC32 $8E22A43A
verified   CRC32 $F727703A
/dev/disk3          	GUID_partition_scheme          	
/dev/disk3s1        	Apple_HFS                      	/private/var/folders/mq/kk__tp6j39z082r1dn9d4rh40000gn/T/tmp.QZfhIiQj
Syncing /var/folders/mq/kk__tp6j39z082r1dn9d4rh40000gn/T/tmp.QZfhIiQj/QOwnNotes.app to applications folder
building file list ... 
138 files to consider
QOwnNotes.app/
QOwnNotes.app/Contents/
QOwnNotes.app/Contents/Info.plist
         686 100%    0.00kB/s    0:00:00 (xfer#1, to-check=135/138)
QOwnNotes.app/Contents/PkgInfo
           9 100%    0.21kB/s    0:00:00 (xfer#2, to-check=134/138)
QOwnNotes.app/Contents/Frameworks/
QOwnNotes.app/Contents/Frameworks/QtCore.framework/
QOwnNotes.app/Contents/Frameworks/QtCore.framework/Versions/
QOwnNotes.app/Contents/Frameworks/QtCore.framework/Versions/5/
QOwnNotes.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
     5895708 100%   14.27MB/s    0:00:00 (xfer#3, to-check=126/138)
QOwnNotes.app/Contents/Frameworks/QtCore.framework/Versions/5/Resources/
QOwnNotes.app/Contents/Frameworks/QtCore.framework/Versions/5/Resources/Info.plist
         708 100%    1.75kB/s    0:00:00 (xfer#4, to-check=124/138)
QOwnNotes.app/Contents/Frameworks/QtGui.framework/
QOwnNotes.app/Contents/Frameworks/QtGui.framework/Versions/
QOwnNotes.app/Contents/Frameworks/QtGui.framework/Versions/5/
QOwnNotes.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
     5773480 100%    7.26MB/s    0:00:00 (xfer#5, to-check=117/138)
QOwnNotes.app/Contents/Frameworks/QtGui.framework/Versions/5/Resources/
QOwnNotes.app/Contents/Frameworks/QtGui.framework/Versions/5/Resources/Info.plist
         706 100%    0.91kB/s    0:00:00 (xfer#6, to-check=115/138)
QOwnNotes.app/Contents/Frameworks/QtNetwork.framework/
QOwnNotes.app/Contents/Frameworks/QtNetwork.framework/Versions/
QOwnNotes.app/Contents/Frameworks/QtNetwork.framework/Versions/5/
QOwnNotes.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
     1329924 100%    1.56MB/s    0:00:00 (xfer#7, to-check=108/138)
QOwnNotes.app/Contents/Frameworks/QtNetwork.framework/Versions/5/Resources/
QOwnNotes.app/Contents/Frameworks/QtNetwork.framework/Versions/5/Resources/Info.plist
         714 100%    0.86kB/s    0:00:00 (xfer#8, to-check=106/138)
QOwnNotes.app/Contents/Frameworks/QtPrintSupport.framework/
QOwnNotes.app/Contents/Frameworks/QtPrintSupport.framework/Versions/
QOwnNotes.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/
QOwnNotes.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport
      350200 100%  419.11kB/s    0:00:00 (xfer#9, to-check=99/138)
QOwnNotes.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/Resources/
QOwnNotes.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/Resources/Info.plist
         724 100%    0.87kB/s    0:00:00 (xfer#10, to-check=97/138)
QOwnNotes.app/Contents/Frameworks/QtQml.framework/
QOwnNotes.app/Contents/Frameworks/QtQml.framework/Versions/
QOwnNotes.app/Contents/Frameworks/QtQml.framework/Versions/5/
QOwnNotes.app/Contents/Frameworks/QtQml.framework/Versions/5/QtQml
     4109160 100%    3.82MB/s    0:00:01 (xfer#11, to-check=90/138)
QOwnNotes.app/Contents/Frameworks/QtQml.framework/Versions/5/Resources/
QOwnNotes.app/Contents/Frameworks/QtQml.framework/Versions/5/Resources/Info.plist
         706 100%  114.91kB/s    0:00:00 (xfer#12, to-check=88/138)
QOwnNotes.app/Contents/Frameworks/QtSql.framework/
QOwnNotes.app/Contents/Frameworks/QtSql.framework/Versions/
QOwnNotes.app/Contents/Frameworks/QtSql.framework/Versions/5/
QOwnNotes.app/Contents/Frameworks/QtSql.framework/Versions/5/QtSql
      253852 100%   26.90MB/s    0:00:00 (xfer#13, to-check=81/138)
QOwnNotes.app/Contents/Frameworks/QtSql.framework/Versions/5/Resources/
QOwnNotes.app/Contents/Frameworks/QtSql.framework/Versions/5/Resources/Info.plist
         706 100%   76.61kB/s    0:00:00 (xfer#14, to-check=79/138)
QOwnNotes.app/Contents/Frameworks/QtSvg.framework/
QOwnNotes.app/Contents/Frameworks/QtSvg.framework/Versions/
QOwnNotes.app/Contents/Frameworks/QtSvg.framework/Versions/5/
QOwnNotes.app/Contents/Frameworks/QtSvg.framework/Versions/5/QtSvg
      359584 100%    5.04MB/s    0:00:00 (xfer#15, to-check=72/138)
QOwnNotes.app/Contents/Frameworks/QtSvg.framework/Versions/5/Resources/
QOwnNotes.app/Contents/Frameworks/QtSvg.framework/Versions/5/Resources/Info.plist
         706 100%    9.99kB/s    0:00:00 (xfer#16, to-check=70/138)
QOwnNotes.app/Contents/Frameworks/QtWidgets.framework/
QOwnNotes.app/Contents/Frameworks/QtWidgets.framework/Versions/
QOwnNotes.app/Contents/Frameworks/QtWidgets.framework/Versions/5/
QOwnNotes.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
     6588984 100%   15.48MB/s    0:00:00 (xfer#17, to-check=63/138)
QOwnNotes.app/Contents/Frameworks/QtWidgets.framework/Versions/5/Resources/
QOwnNotes.app/Contents/Frameworks/QtWidgets.framework/Versions/5/Resources/Info.plist
         714 100%    1.71kB/s    0:00:00 (xfer#18, to-check=61/138)
QOwnNotes.app/Contents/Frameworks/QtXml.framework/
QOwnNotes.app/Contents/Frameworks/QtXml.framework/Versions/
QOwnNotes.app/Contents/Frameworks/QtXml.framework/Versions/5/
QOwnNotes.app/Contents/Frameworks/QtXml.framework/Versions/5/QtXml
      278036 100%  662.24kB/s    0:00:00 (xfer#19, to-check=54/138)
QOwnNotes.app/Contents/Frameworks/QtXml.framework/Versions/5/Resources/
QOwnNotes.app/Contents/Frameworks/QtXml.framework/Versions/5/Resources/Info.plist
         706 100%    1.68kB/s    0:00:00 (xfer#20, to-check=52/138)
QOwnNotes.app/Contents/Frameworks/QtXmlPatterns.framework/
QOwnNotes.app/Contents/Frameworks/QtXmlPatterns.framework/Versions/
QOwnNotes.app/Contents/Frameworks/QtXmlPatterns.framework/Versions/5/
QOwnNotes.app/Contents/Frameworks/QtXmlPatterns.framework/Versions/5/QtXmlPatterns
     4536896 100%    6.59MB/s    0:00:00 (xfer#21, to-check=45/138)
QOwnNotes.app/Contents/Frameworks/QtXmlPatterns.framework/Versions/5/Resources/
QOwnNotes.app/Contents/Frameworks/QtXmlPatterns.framework/Versions/5/Resources/Info.plist
         722 100%    1.07kB/s    0:00:00 (xfer#22, to-check=43/138)
QOwnNotes.app/Contents/MacOS/
QOwnNotes.app/Contents/MacOS/QOwnNotes
     6257444 100%    6.26MB/s    0:00:00 (xfer#23, to-check=41/138)
QOwnNotes.app/Contents/MacOS/update.command
        1744 100%    1.79kB/s    0:00:00 (xfer#24, to-check=40/138)
QOwnNotes.app/Contents/PlugIns/
QOwnNotes.app/Contents/PlugIns/bearer/
QOwnNotes.app/Contents/PlugIns/bearer/libqcorewlanbearer.dylib
      117576 100%  120.10kB/s    0:00:00 (xfer#25, to-check=37/138)
QOwnNotes.app/Contents/PlugIns/bearer/libqgenericbearer.dylib
       59604 100%   60.82kB/s    0:00:00 (xfer#26, to-check=36/138)
QOwnNotes.app/Contents/PlugIns/imageformats/
QOwnNotes.app/Contents/PlugIns/imageformats/libqdds.dylib
       57592 100%   58.71kB/s    0:00:00 (xfer#27, to-check=34/138)
QOwnNotes.app/Contents/PlugIns/imageformats/libqgif.dylib
       42912 100%   43.70kB/s    0:00:00 (xfer#28, to-check=33/138)
QOwnNotes.app/Contents/PlugIns/imageformats/libqicns.dylib
       50248 100%   51.11kB/s    0:00:00 (xfer#29, to-check=32/138)
QOwnNotes.app/Contents/PlugIns/imageformats/libqico.dylib
       41268 100%   41.94kB/s    0:00:00 (xfer#30, to-check=31/138)
QOwnNotes.app/Contents/PlugIns/imageformats/libqjp2.dylib
      622536 100%  594.86kB/s    0:00:01 (xfer#31, to-check=30/138)
QOwnNotes.app/Contents/PlugIns/imageformats/libqjpeg.dylib
      284696 100%   45.25MB/s    0:00:00 (xfer#32, to-check=29/138)
QOwnNotes.app/Contents/PlugIns/imageformats/libqmng.dylib
      365220 100%   38.70MB/s    0:00:00 (xfer#33, to-check=28/138)
QOwnNotes.app/Contents/PlugIns/imageformats/libqsvg.dylib
       37112 100%    3.54MB/s    0:00:00 (xfer#34, to-check=27/138)
QOwnNotes.app/Contents/PlugIns/imageformats/libqtga.dylib
       30976 100%    2.69MB/s    0:00:00 (xfer#35, to-check=26/138)
QOwnNotes.app/Contents/PlugIns/imageformats/libqtiff.dylib
      433256 100%    5.74MB/s    0:00:00 (xfer#36, to-check=25/138)
QOwnNotes.app/Contents/PlugIns/imageformats/libqwbmp.dylib
       31624 100%  423.05kB/s    0:00:00 (xfer#37, to-check=24/138)
QOwnNotes.app/Contents/PlugIns/imageformats/libqwebp.dylib
      450992 100%    5.59MB/s    0:00:00 (xfer#38, to-check=23/138)
QOwnNotes.app/Contents/PlugIns/platforms/
QOwnNotes.app/Contents/PlugIns/platforms/libqcocoa.dylib
      921428 100%    6.06MB/s    0:00:00 (xfer#39, to-check=21/138)
QOwnNotes.app/Contents/PlugIns/printsupport/
QOwnNotes.app/Contents/PlugIns/printsupport/libcocoaprintersupport.dylib
       28272 100%  189.11kB/s    0:00:00 (xfer#40, to-check=19/138)
QOwnNotes.app/Contents/PlugIns/sqldrivers/
QOwnNotes.app/Contents/PlugIns/sqldrivers/libqsqlite.dylib
     1137408 100%    5.17MB/s    0:00:00 (xfer#41, to-check=17/138)
QOwnNotes.app/Contents/Resources/
QOwnNotes.app/Contents/Resources/QOwnNotes.icns
      118318 100%  547.61kB/s    0:00:00 (xfer#42, to-check=15/138)
QOwnNotes.app/Contents/Resources/QOwnNotes_ar.qm
      123836 100%  567.76kB/s    0:00:00 (xfer#43, to-check=14/138)
QOwnNotes.app/Contents/Resources/QOwnNotes_de.qm
      122803 100%  560.40kB/s    0:00:00 (xfer#44, to-check=13/138)
QOwnNotes.app/Contents/Resources/QOwnNotes_en.qm
        1585 100%    7.23kB/s    0:00:00 (xfer#45, to-check=12/138)
QOwnNotes.app/Contents/Resources/QOwnNotes_es.qm
      122405 100%  478.14kB/s    0:00:00 (xfer#46, to-check=11/138)
QOwnNotes.app/Contents/Resources/QOwnNotes_fr.qm
      127285 100%  493.26kB/s    0:00:00 (xfer#47, to-check=10/138)
QOwnNotes.app/Contents/Resources/QOwnNotes_hu.qm
      118561 100%  457.64kB/s    0:00:00 (xfer#48, to-check=9/138)
QOwnNotes.app/Contents/Resources/QOwnNotes_it.qm
      125279 100%  479.78kB/s    0:00:00 (xfer#49, to-check=8/138)
QOwnNotes.app/Contents/Resources/QOwnNotes_ja.qm
       90695 100%  345.97kB/s    0:00:00 (xfer#50, to-check=7/138)
QOwnNotes.app/Contents/Resources/QOwnNotes_nl.qm
      121113 100%  460.21kB/s    0:00:00 (xfer#51, to-check=6/138)
QOwnNotes.app/Contents/Resources/QOwnNotes_pl.qm
      121466 100%  459.76kB/s    0:00:00 (xfer#52, to-check=5/138)
QOwnNotes.app/Contents/Resources/QOwnNotes_pt.qm
      120939 100%  454.25kB/s    0:00:00 (xfer#53, to-check=4/138)
QOwnNotes.app/Contents/Resources/QOwnNotes_ru.qm
      121455 100%  449.27kB/s    0:00:00 (xfer#54, to-check=3/138)
QOwnNotes.app/Contents/Resources/QOwnNotes_zh.qm
       91809 100%  338.33kB/s    0:00:00 (xfer#55, to-check=2/138)
QOwnNotes.app/Contents/Resources/empty.lproj
           0 100%    0.00kB/s    0:00:00 (xfer#56, to-check=1/138)
QOwnNotes.app/Contents/Resources/qt.conf
          78 100%    0.29kB/s    0:00:00 (xfer#57, to-check=0/138)

sent 41994986 bytes  received 1760 bytes  16798698.40 bytes/sec
total size is 41983682  speedup is 1.00
"disk3" unmounted.
"disk3" ejected.
Removing temporary files...
Starting QOwnNotes...

[Process completed]
```

**Comment by pbek** [comment]
@markandrewj thank you for testing. I will then just try to add a line to the temporary script to remove itself (if that's possible) when it's done...

**Comment by pbek** [comment]
## 16.11.5
- fixed a problem when QOwnNotes didn't detect the macOS updater script
  for some users and added removing of the temporary updater script
  after the update

There now is a new release, could you please test it and report if the new features work for you?

**Comment by dgirke** [comment]
Hi Patrizio,

works very good. I appreciate your great work.
By starting the update-dialogue, first the terminal window opens, then I can
follow an rsync-like download and install process on the cmd (your new script)
and after installation I just have to close the terminal window and that´s it.

Thanks a lot.

Cheers

Detlef


Am 07.11.16 um 19:24 schrieb Patrizio Bekerle:

**Comment by pbek** [comment]
@dgirke thank you for testing!

**Comment by Letterus** [comment]
Great work! Thank you very much!

**Comment by pbek** [comment]
I'm glad it now seems to work... I hadn't imagine in what kind of troubles I would run with the updater and what I had to do to get around them. And other troubles (like some permission restrictions) never occurred at all...
