### ISSUE TITLE
[F] 24 hour

### ISSUE THREAD

**Issue by Webxorcist** [pbek/QOwnNotes#1020]
#### Expected behaviour

ToDo list shows me time in normal ti... eh I mean 24 hour format :)

#### Actual behaviour

Only shows this AM/PM stuff

#### Steps to reproduce

Make a ToDo item and set a reminder

#### Relevant log output in the Log panel

```

```

#### Information about the application, settings and environment

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mon Sep 10 14:51:40 2018`
**Version**: `18.09.1`
**Build date**: `Sep  9 2018`
**Build number**: `476`
**Platform**: `linux`
**Operating System**: `openSUSE Leap 15.0`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.9.4`
**Qt Version (runtime)**: `5.9.4`
**Portable mode**: `no`
**Settings path / key**: `/home/ricardo/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/ricardo/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `3`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://owncloud.x-labs.nl`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `10.0.8.5`
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/ricardo/ownCloud/Ricardo/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/ricardo/ownCloud/Ricardo/Notes/notes.sqlite`

## Settings

**ActiveNoteHistoryItem**: *empty*
**Debug/fakeOldVersionNumber**: `false`
**Debug/fileLogging**: `false`
**Editor/CurrentSchemaKey**: `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing**: `true`
**Editor/autoBracketRemoval**: `true`
**Editor/editorWidthInDFMOnly**: `true`
**Editor/highlightCurrentLine**: `true`
**Editor/vimMode**: `false`
**IssueAssistantDialog/geometry**: `<binary data>`
**LastUpdateCheck**: `2018-09-10T14:32:11`
**LogWidget/criticalLog**: `true`
**LogWidget/debugLog**: `true`
**LogWidget/fatalLog**: `true`
**LogWidget/infoLog**: `true`
**LogWidget/scriptingLog**: `true`
**LogWidget/statusLog**: `true`
**LogWidget/warningLog**: `true`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `48`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `Cantarell,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `Cantarell,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl**: `false`
**MainWindow/showNotesFromAllNoteSubFolders**: `true`
**PiwikClientId**: `<hidden>`
**SearchEngineId**: `0`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**ShowSystemTray**: `true`
**StartHidden**: `false`
**TodoDialog/geometry**: `<binary data>`
**TodoDialog/mainSplitterState**: `<binary data>`
**TodoDialog/showCompletedItems**: `2`
**TodoDialog/todoListSelectorSelectedItem**: `Logius`
**WelcomeDialog/geometry**: `<binary data>`
**acceptAllExternalModifications**: `false`
**allowDifferentNoteFileName**: `false`
**allowNoteEditing**: `true`
**allowOnlyOneAppInstance**: `true`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `false`
**appMetrics/notificationShown**: `true`
**automaticNoteFolderDatabaseClosing**: `false`
**closeTodoListAfterSave**: `false`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**currentWorkspace**: `0d18b033-d98d-4df3-82ab-e2685ae67a3f`
**cursorWidth**: `1`
**customNoteFileExtensionList**: *empty*
**darkMode**: `true`
**darkModeColors**: `true`
**darkModeTrayIcon**: `true`
**defaultNoteFileExtension**: `md`
**demoNotesCreated**: `true`
**disableAutomaticUpdateDialog**: `true`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: `gedit`
**fullyHighlightedBlockquotes**: `false`
**gitCommitInterval**: `30`
**gitExecutablePath**: *empty*
**gitLogCommand**: *empty*
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**imageScaleDown**: `false`
**imageScaleDownMaximumHeight**: `1024`
**imageScaleDownMaximumWidth**: `1024`
**insertTimeFormat**: `dd-MM-yyyy hh:mm:ss`
**interfaceLanguage**: *empty*
**internalIconTheme**: `false`
**itemHeight**: `39`
**localTrash/autoCleanupDays**: `30`
**localTrash/autoCleanupEnabled**: `true`
**localTrash/supportEnabled**: `true`
**markdownHighlightingEnabled**: `true`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `2`
**newNoteAskHeadline**: `false`
**noteEditIsCentralWidget**: `true`
**noteListPreview**: `false`
**noteSaveIntervalTime**: `10`
**noteSubfoldersPanelDisplayAsFullTree**: `true`
**noteSubfoldersPanelHideSearch**: `false`
**noteSubfoldersPanelOrder**: `0`
**noteSubfoldersPanelShowFullPath**: `false`
**noteSubfoldersPanelShowNotesRecursively**: `false`
**noteSubfoldersPanelShowRootFolderName**: `true`
**noteSubfoldersPanelSort**: `0`
**notesPanelOrder**: `0`
**notesPanelSort**: `1`
**notesPath**: `/home/ricardo/ownCloud/Ricardo/Notes`
**notifyAllExternalModifications**: `false`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: `https://owncloud.x-labs.nl`
**ownCloud/supportEnabled**: `true`
**ownCloud/todoCalendarBackend**: `3`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/todoCalendarDisplayNameList**: `Personal, Logius, X-Labs`
**ownCloud/todoCalendarEnabledList**: `Personal, Logius, X-Labs`
**ownCloud/todoCalendarEnabledUrlList**: `https://owncloud.x-labs.nl/remote.php/dav/calendars/ricardo/personal/, https://owncloud.x-labs.nl/remote.php/dav/calendars/ricardo/logius/, https://owncloud.x-labs.nl/remote.php/dav/calendars/ricardo/x-labs/`
**ownCloud/todoCalendarUrlList**: `https://owncloud.x-labs.nl/remote.php/dav/calendars/ricardo/personal/, https://owncloud.x-labs.nl/remote.php/dav/calendars/ricardo/logius/, https://owncloud.x-labs.nl/remote.php/dav/calendars/ricardo/x-labs/`
**ownCloud/userName**: `ricardo`
**ownCloudInfo/appIsValid**: `true`
**ownCloudInfo/connectionErrorMessage**: `Unknown error`
**ownCloudInfo/notesPathExistsText**: `yes`
**ownCloudInfo/serverVersion**: `10.0.8.5`
**previousWorkspace**: `e42d3f74-afd8-4fca-8188-7af62a656779`
**restoreCursorPosition**: `true`
**showMenuBar**: `true`
**showStatusBar**: `true`
**taggingShowNotesRecursively**: `false`
**tagsPanelHideSearch**: `false`
**tagsPanelOrder**: `0`
**tagsPanelSort**: `0`
**toolbar/1/items**: `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name**: `mainToolBar`
**toolbar/1/title**: `main toolbar`
**toolbar/2/items**: `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name**: `formattingToolbar`
**toolbar/2/title**: `formatting toolbar`
**toolbar/3/items**: `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name**: `insertingToolbar`
**toolbar/3/title**: `inserting toolbar`
**toolbar/4/items**: `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name**: `encryptionToolbar`
**toolbar/4/title**: `encryption toolbar`
**toolbar/5/items**: `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name**: `windowToolbar`
**toolbar/5/title**: `window toolbar`
**toolbar/6/items**: `action_Quit`
**toolbar/6/name**: `quitToolbar`
**toolbar/6/title**: `quit toolbar`
**toolbar/size**: `6`
**useUNIXNewline**: `false`
**workspace-0d18b033-d98d-4df3-82ab-e2685ae67a3f/name**: `minimal`
**workspace-0d18b033-d98d-4df3-82ab-e2685ae67a3f/noteSubFolderDockWidgetVisible**: `true`
**workspace-0d18b033-d98d-4df3-82ab-e2685ae67a3f/windowState**: `<binary data>`
**workspace-e42d3f74-afd8-4fca-8188-7af62a656779/name**: `full`
**workspace-e42d3f74-afd8-4fca-8188-7af62a656779/noteSubFolderDockWidgetVisible**: `true`
**workspace-e42d3f74-afd8-4fca-8188-7af62a656779/windowState**: `<binary data>`
**workspaces**: `e42d3f74-afd8-4fca-8188-7af62a656779, 0d18b033-d98d-4df3-82ab-e2685ae67a3f`

## System environment

**HOSTTYPE**: `x86_64`
**XAUTHLOCALHOSTNAME**: `echelon`
**LESSCLOSE**: `lessclose.sh %s %s`
**XKEYSYMDB**: `/usr/X11R6/lib/X11/XKeysymDB`
**XDG_MENU_PREFIX**: `gnome-`
**LANG**: `en_US.UTF-8`
**WINDOWMANAGER**: `gnome`
**LESS**: `-M -I -R`
**DISPLAY**: `:1`
**JAVA_ROOT**: `/usr/lib64/jvm/jre`
**HOSTNAME**: `echelon`
**CONFIG_SITE**: `/usr/share/site/x86_64-unknown-linux-gnu`
**CSHEDIT**: `emacs`
**GPG_TTY**: `not a tty`
**AUDIODRIVER**: `pulseaudio`
**LESS_ADVANCED_PREPROCESSOR**: `no`
**COLORTERM**: `1`
**USERNAME**: `ricardo`
**JAVA_HOME**: `/usr/lib64/jvm/jre`
**ALSA_CONFIG_PATH**: `/etc/alsa-pulse.conf`
**MACHTYPE**: `x86_64-suse-linux`
**XDG_VTNR**: `2`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**QEMU_AUDIO_DRV**: `pa`
**MINICOM**: `-c on`
**QT_SYSTEM_DIR**: `/usr/share/desktop-data`
**OSTYPE**: `linux`
**XDG_SESSION_ID**: `1`
**USER**: `ricardo`
**PAGER**: `less`
**DESKTOP_SESSION**: `gnome`
**MORE**: `-sl`
**PWD**: `/home/ricardo`
**SSH_ASKPASS**: `/usr/lib/ssh/ssh-askpass`
**HOME**: `/home/ricardo`
**JOURNAL_STREAM**: `9:38390`
**SSH_AGENT_PID**: `3072`
**HOST**: `echelon`
**XNLSPATH**: `/usr/share/X11/nls`
**XDG_SESSION_TYPE**: `x11`
**XDG_DATA_DIRS**: `/home/ricardo/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share`
**XDG_SESSION_DESKTOP**: `gnome`
**PROFILEREAD**: `true`
**GTK_MODULES**: `canberra-gtk-module`
**FROM_HEADER**: *empty*
**MAIL**: `/var/spool/mail/ricardo`
**WINDOWPATH**: `2`
**LESSKEY**: `/etc/lesskey.bin`
**SHELL**: `/bin/bash`
**TERM**: `xterm`
**XCURSOR_THEME**: `DMZ`
**XDG_CURRENT_DESKTOP**: `GNOME`
**PYTHONSTARTUP**: `/etc/pythonstart`
**SHLVL**: `0`
**XDG_SEAT**: `seat0`
**G_FILENAME_ENCODING**: `@locale,UTF-8,ISO-8859-15,CP1252`
**MANPATH**: `/usr/local/man:/usr/share/man`
**XSESSION_IS_UP**: `yes`
**GDMSESSION**: `gnome`
**LOGNAME**: `ricardo`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XAUTHORITY**: `/run/user/1000/gdm/Xauthority`
**INPUT_METHOD**: `ibus`
**JRE_HOME**: `/usr/lib64/jvm/java-10-openjdk-10/jre`
**XDG_CONFIG_DIRS**: `/etc/xdg`
**PATH**: `/home/ricardo/bin:/usr/local/bin:/usr/bin:/bin:/usr/lib/mit/sbin`
**JAVA_BINDIR**: `/usr/lib64/jvm/jre/bin`
**SDL_AUDIODRIVER**: `pulse`
**G_BROKEN_FILENAMES**: `1`
**HISTSIZE**: `1000`
**CPU**: `x86_64`
**CVS_RSH**: `ssh`
**LESSOPEN**: `lessopen.sh %s`
**QT_IM_MODULE**: `ibus`
**XMODIFIERS**: `@im=ibus`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**SESSION_MANAGER**: `local/echelon:@/tmp/.ICE-unix/2978,unix/echelon:/tmp/.ICE-unix/2978`
**GIO_LAUNCHED_DESKTOP_FILE**: `/home/ricardo/.config/autostart/albert.desktop`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `3342`

**Comment by pbek** [comment]
If I set a reminder the time selector uses a 24h clock. I didn't even know it's possible to now have a 24h clock there. Might be some local setting of your distribution.

**Comment by pbek** [comment]
A http://doc.qt.io/qt-5/qdatetimeedit.html is used as time picker.

**Comment by Webxorcist** [comment]
Thanks for your reply. My whole system (as far as I know and use) is set to 24-hour. I'll go look in to it.

**Comment by pbek** [comment]
I will close this issue until there is more information.
