### ISSUE TITLE
"Move to subfolder" list not in alphabetical order

### ISSUE THREAD

**Issue by geckolinux** [pbek/QOwnNotes#1022]
Hi there, I'm running QOwnNotes 18.03.2 - OBS - build 422 on openSUSE Tumbleweed.

There's a little issue when moving notes to a subfolder. The list of available subfolders is not alphabetically sorted.

![screenshot from 2018-09-11 13-18-39](https://user-images.githubusercontent.com/2692138/45379570-095c5c00-b5c6-11e8-9b8a-f74e1404af8f.png)

Thanks a lot!

**Comment by pbek** [comment]
That's true, because they are sorted by last modified date.

**Comment by geckolinux** [comment]
Thanks. By "last modified" do you mean the last folder that had note activity in it, or the last created folder itself?

**Comment by pbek** [comment]
I would need to look that up, but I guess I will sort the tree alphabetically, might make more sense.

**Comment by pbek** [comment]
## 18.09.2
- the list of note sub-folders in the note list when moving notes to note 
  sub-folders is now sorted alphabetically

**Comment by geckolinux** [comment]
Excellent, thanks a lot!

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by geckolinux** [comment]
Works perfect now, thanks for being responsive to suggestions!

**Comment by pbek** [comment]
Great, thank you for testing!
