### ISSUE TITLE
Providing scripts with installation

### ISSUE THREAD

**Issue by fodrice** [pbek/QOwnNotes#1026]
It would be useful if scripts (at least stable) from repository will be packaged with application (e. g. for no-network installations).
scripts-master size 500 kb so it cost almost nothing to package application with scripts (useful if there no internet).

**Comment by pbek** [comment]
Nice idea, but I guess it would be a lot of work to integrate that in every way on distribution as well as to find a way to integrate that in to the application (for every way of distribution)...

It would be much easier if you down load the archive yourself for places where you have no internet...
