### ISSUE TITLE
OSX Version - Fullscreen Note selection

### ISSUE THREAD

**Issue by kione** [pbek/QOwnNotes#1028]
While the window is maximized aka. Fullscreen, I can't select a single Note, the program shows multiple selections after clicking a few, but they do not open.

#### Expected behaviour
Selecting a single note for viewing or editing
#### Actual behaviour
Selections keep persistent on all clicked Notes
#### Steps to reproduce
Maximize Program QOwnNotes - version 18.09.2  in OSX Version Mojave

**Comment by kione** [comment]
Checked on different machine with High Sierra = same effect.
QTKit 7.7.3, Copyright 2003-2012, Apple Inc.
      Location: /System/Library/Frameworks/QTKit.framework

**Comment by pbek** [comment]
True, I can also confirm that. But regardless I can switch notes...
Still seems like a Qt-bug of QTreeWidget in fullscreen mode...

**Comment by pbek** [comment]
It's really strange, I don't have the issue in the tag and sub-folder panel, even if they are sharing the same selection mode.

And I don't have the issue in the note-list when building the app with Qt 5.7. Might be a Qt 5.11.2 issue.

**Comment by pbek** [comment]
Seems to be fixed by now.

**Comment by kione** [comment]
Indeed! Thank you :)
