### ISSUE TITLE
Can hide toolbar, can't show it again!

### ISSUE THREAD

**Issue by praxiq** [pbek/QOwnNotes#103]
Most of the app's functionality is accessible through the toolbar at the top of the window. On OSX, when I right-click on that toolbar, it opens a menu with a single checkbox and no text. When I select that menu item, the toolbar disappears.

The only way I could find to get the toolbar back was to go to _Settings > General > Clear app data and exit_. 

It should either be impossible to remove this toolbar, or else it should be possible to both hide and show the toolbar through a command in a menu (perhaps the Edit menu) or at least a checkbox in Settings.

**Comment by pbek** [comment]
Thank you for your report, @praxiq!
I think that's true, QOwnNote stores the state of the toolbar (you can also move it around). If someone would remove it that would be saved too.
I will look into that.

**Comment by pbek** [comment]
Version 1.1.2, where I made a new menu entry for it, is out now. Does that solve your problem, @praxiq?

**Comment by praxiq** [comment]
Yes, perfect! 11-hour turnaround between reporting a bug and a new release that fixes it? I'm impressed! :)

**Comment by pbek** [comment]
Thank you, I had to finish the #86 task first. :)
