### ISSUE TITLE
Syntax highlighted in the YAML header

### ISSUE THREAD

**Issue by bepolymathe** [pbek/QOwnNotes#1031]
I use a script to automatically create new documents in Rmarkdown (.rmd), with a YALM header. This then allows me to generate with Pandoc in.pdf,.odt,.docx, etc.

I simply have a problem highlighting the text in the header.

#### Expected behaviour

The last field of the YALM header is not considered a title.

#### Actual behaviour

The last field of the YALM header is considered as a title.

![capture du 2018-09-22 10-21-16](https://user-images.githubusercontent.com/29939805/45915213-db8ed700-be51-11e8-95d2-de94dec2a615.png)

**Comment by pbek** [comment]
Since QOwnNotes doesn't support YAML headers because of its ties to Nextcloud notes I'm not sure I will implemented that... And there isn't even *one* standard for the headers.

**Comment by pbek** [comment]
- `---` also marks a headline
- doing multiline syntax highlighting is quite some work
- there are different standards for marking YAML headers in markdown files

**Comment by besswein** [comment]
Maybe we could say if the first line is `---` everything until the second `---` is considered as YAML and thus not formated or grayed out or even completly striped away.

This might also be a good thing for a script, might look into that incase I switch to YAML tags some day (won't happen in the next time)

**Comment by pbek** [comment]
Maybe everything inside the `---` block can be stripped away before it reaches the hoedown markdown to html converter.

**Comment by besswein** [comment]
A hook to be able to modify what is passed to the markdown to html converter could be useful.

I already came across this need a few days ago then I was trying to write a script that renders LaTeX math on the fly.

**Comment by pbek** [comment]
A hook doesn't solve the need of extending the highlighting mechanism.

And there is http://docs.qownnotes.org/en/develop/scripting/README.html#notetomarkdownhtmlhook

**Comment by besswein** [comment]
I know this hook, but as far of my understanding it is called after the internal markdown converter interpreted the note. I thought about stripping / replacing markdown text before the internal markdown converter interprets it.

**Comment by pbek** [comment]
## 19.10.8
- **frontmatter blocks** are now **highlighted** as masked syntax and are also
  **ignored in the preview**
    - the frontmatter block has to start and end with a `---` line, it has to
      be at the beginning of the note and only one block can exist per note

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by bessw** [comment]
Looks good to me.

It would be nice if the first line after the frontmatter was used as filename if `Allow note file name to be different from headline` is set to false.
But I think we could also live without, if thats too much hassle.

**Comment by pbek** [comment]
I guess I could do that in `Note::handleNoteTextFileName()`. Meanwhile it could be done with http://docs.qownnotes.org/en/develop/scripting/README.html#handlenotetextfilenamehook in a sript.

**Comment by pbek** [comment]
## 19.10.10
- if a **frontmatter** was detected at the beginning of a note the **filename of the note**
  now will be the **first non-empty line after the frontmatter** instead of the
  first line of the note

**Comment by pbek** [comment]
There now is a new release building, could you please test it.

**Comment by bessw** [comment]
Looks good to me.

**Comment by pbek** [comment]
And very useful, thank you for testing!
