### ISSUE TITLE
New line insertion

### ISSUE THREAD

**Issue by fodrice** [pbek/QOwnNotes#1032]
It would be nice to add an editor switchable option "Insert markdown's new line on line break" (two spaces I mean), and/or add shortcut to insert markdown new line. 
#### By default it works like this:
- Shift+Enter -- makes new line in markdown
- Enter -- makes new line in file without new line in rendered layout
#### Option in editor switches behaviour to opposite:
- Shift+Enter -- makes new line in file without new line in rendered layout
- Enter -- makes new line in markdown

**Comment by pbek** [comment]
You can create a script with a custom a action that uses http://docs.qownnotes.org/en/develop/scripting/README.html#write-text-to-the-note-text-edit to insert any text you like. Then you could give that custom action a shortcut in the shortcut settings.

Does this answer your question?

**Comment by pbek** [comment]
But you don't want to overwrite the behavior of Enter and Shift + Enter because that would be an app-wide setting.

**Comment by pbek** [comment]
I will close this issue until there is more information.

**Comment by fodrice** [comment]
Te idea is to allow user simply add new line in markdown editor with pressing shift+enter not by adding to spaces and press enter (VNote have this behaviour and it's really better). And one more: it could be more simper for users not familiar with .md files to do this like in common document editors (Enter adds new paragraph and Shift+Enter adds only new line). So switching behaviour in editor's menu will be nice. 
And I can't do this, I don't know c++ and qml enough to do this. So it's just proposal.

**Comment by pbek** [comment]
Ah, I was misguided by the title of this issue. I will consider this, thank you.

**Comment by pbek** [comment]
## 18.09.5
- you can now create markdown new-lines (with two spaces at the end) by pressing
  <kbd>Shift</kbd> + <kbd>Return</kbd> in the note editor

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
Great, thank you for testing!
