### ISSUE TITLE
Reminders/Todo Features

### ISSUE THREAD

**Issue by Paulactea** [pbek/QOwnNotes#1036]
Hi there. Is there a way to synchronize the todo list feature of QOwnnotes with Android? I mean to be able to get reminders at the indicated time/hour? When synchronized with the Nextcloud app I don't get the reminders, I cannot even see the "tasks" unless I go to the web version. Is there any other android app that can work with it?

Another thing. Last night I set up a few reminders for this morning at 8am, but I was able to turn on the computer at 8:10 am and I opened QOwnnotes expecting it will send me the reminders even though it was past the time for a few minutes, but it didn't reminded me anything.  Would be good if we got the past-due reminders regardless of the time we open QOwnnotes.

I really like QOwnnotes and wish the todo aspect of it was more robust in general. I'am hoping and trying to use it as my main todo list.

Thank you for your work, it's a great program that I hope to keep using for a long time.

**Comment by pbek** [comment]
I use Nextcloud on a server to store todo lists and DAVdroid on Android to sync them with my phone.

> Would be good if we got the past-due reminders regardless of the time we open QOwnnotes.

QOwnNotes just acts as "cache" for your server's todo lists and those cached items are very volatile. It's best to get your notification from an other device.

Does this answer your question?

**Comment by Paulactea** [comment]
I also have Nextcloud on my VPS, but haven't used DAVdroid. Will check it out. 

`Does this answer your question?`

I think so. Thank you, I really like QOn, keep up the great work: )

**Comment by pbek** [comment]
Thank you. ;)
