### ISSUE TITLE
GTK+ theme broken when using Ubuntu 18.10 (beta)

### ISSUE THREAD

**Issue by Jakethethird** [pbek/QOwnNotes#1040]
#### A grey 1990's style theme appears. Fusion and Windows work OK.

Possibly this is due to the new Community theme Yaru being installed as a snap and Qownnotes not seeing it?

I appreciate 18.10 is still in beta, so it is a good moment to look at this before the official release in a couple of weeks.

**Comment by pbek** [comment]
If you were using the snap than what you can only use the styling that is accessible to the snap... I don't think there currently is a way around this. Best use the PPA version of QOwnNotes in this case (there already is a cosmic version of QOwnNotes)...

Does this answer your question?

**Comment by Jakethethird** [comment]
Yes it does. I'll continue to use the snap with the (decent) Fusion theme for now. 

I am assuming that their Yaru theme is still a snap because that is how it was available in 18.04 and it is how they are distributing other basic functions (calculator, system monitor, logs). But having said that, it is not in my ~/snap folder.

**Comment by pbek** [comment]
Yes, maybe you simply have to wait until it gets available...

**Comment by guttermonk** [comment]
According to the solution from @hackel to this [Stackexchange question](https://askubuntu.com/questions/806668/how-to-change-the-theme-of-snap-apps), snaps can have GTK theme support. I'm attempting to use arc-dark and I have the gtk-common-themes snap installed, but I'm unable to get that editor theme to load. Any suggestions?

**Comment by pbek** [comment]
I'm sorry, I never really used GTK. 😬
