### ISSUE TITLE
[Q] Problem with tags

### ISSUE THREAD

**Issue by Deboart** [pbek/QOwnNotes#1042]
#### General question

after replasing the database stopping working tagging. The tag tree is displayed  in the main window of program, but in the note none of the tags is assigned and, moreover, no new are created. I looked at the notes database, but did not find any obvious errors. The integrity check was also successful. What could be the reason? and how I can solve this проблему?

#### Relevant log output in the Log panel

```

```

#### Information about the application, settings and environment

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Вт окт 9 16:17:28 2018`
**Version**: `18.10.0`
**Build date**: `Oct  5 2018`
**Build number**: `3872`
**Platform**: `windows`
**Operating System**: `Windows Server 2016 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.10.1`
**Qt Version (runtime)**: `5.10.1`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\DeBo\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `D:\Program Files (x86)\QOwnNotes`, `\QOwnNotes.exe`, `--after-update`, `C:\Users\DeBo\AppData\Local\Temp\1\QOwnNotes-VjEQAF-updater.bat`
**Qt Debug**: `0`
**Locale (system)**: `ru_RU`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `319`
**Enabled scripts**: `9`

## Server Info

**serverUrl**: `https://deboart.dhis.org/nextcloud`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `13.0.4.0`
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `111`

### Note folder `notes`

**id**: `111`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `D:\DEBO\NextCloud\notes`
**remotePath**: `notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `Writer`
**database file**: `D:\DEBO\NextCloud\notes\notes.sqlite`

### Script `@tag tagging in note text (experimental)`

**id**: `1`
**path**: `C:\Users\DeBo\AppData\Roaming\PBE\QOwnNotes\scripts\in-note-text-tagging\in-note-text-tagging.qml`
**variablesJson**: 
```
{
    "tagHighlightColor": "purple",
    "tagMarker": "@"
}
```
**identifier**: `in-note-text-tagging`
**version**: `0.0.8`
**minAppVersion**: `17.09.9`

### Script `Favorite note`

**id**: `2`
**path**: `C:\Users\DeBo\AppData\Roaming\PBE\QOwnNotes\scripts\favorite-note\favorite-note.qml`
**variablesJson**: *empty*
**identifier**: `favorite-note`
**version**: `0.0.1`
**minAppVersion**: `17.05.6`

### Script `Image preview`

**id**: `3`
**path**: `C:\Users\DeBo\AppData\Roaming\PBE\QOwnNotes\scripts\image-preview\image-preview.qml`
**variablesJson**: 
```
{
    "maxWidth": 640
}
```
**identifier**: `image-preview`
**version**: `1.0.0`
**minAppVersion**: `17.11.6`

### Script `Insert symbol buttons`

**id**: `4`
**path**: `C:\Users\DeBo\AppData\Roaming\PBE\QOwnNotes\scripts\symbol-buttons\symbol-buttons.qml`
**variablesJson**: 
```
{
    "symbolString": "∑ ∫ ∮© ® ₽ ☺"
}
```
**identifier**: `symbol-buttons`
**version**: `0.0.1`
**minAppVersion**: `17.05.8`

### Script `Add Multiple tags`

**id**: `5`
**path**: `C:\Users\DeBo\AppData\Roaming\PBE\QOwnNotes\scripts\add-multiple-tags\add-multiple-tags.qml`
**variablesJson**: *empty*
**identifier**: `add-multiple-tags`
**version**: `0.0.1`
**minAppVersion**: `17.06.2`

### Script `Checkbox preview and export`

**id**: `6`
**path**: `C:\Users\DeBo\AppData\Roaming\PBE\QOwnNotes\scripts\export-checkboxes\export-checkboxes.qml`
**variablesJson**: *empty*
**identifier**: `export-checkboxes`
**version**: `0.0.2`
**minAppVersion**: `17.12.0`

### Script `Insert Table of Contents (TOC)`

**id**: `7`
**path**: `C:\Users\DeBo\AppData\Roaming\PBE\QOwnNotes\scripts\insert-toc\insert-toc.qml`
**variablesJson**: 
```
{
    "tocTitle": "Table of Contents"
}
```
**identifier**: `insert-toc`
**version**: `0.0.3`
**minAppVersion**: `17.06.2`

### Script `Note link to clipboard`

**id**: `8`
**path**: `C:\Users\DeBo\AppData\Roaming\PBE\QOwnNotes\scripts\note-link-to-clipboard\note-link-to-clipboard.qml`
**variablesJson**: *empty*
**identifier**: `note-link-to-clipboard`
**version**: `0.0.2`
**minAppVersion**: `17.02.4`

### Script `Unique note id`

**id**: `9`
**path**: `C:\Users\DeBo\AppData\Roaming\PBE\QOwnNotes\scripts\unique-note-id\unique-note-id.qml`
**variablesJson**: *empty*
**identifier**: `unique-note-id`
**version**: `1.0.1`
**minAppVersion**: `18.05.1`

## Settings

**AboutDialog/geometry**: `<binary data>`
**ActiveNoteHistoryItem**: *empty*
**Debug/fakeOldVersionNumber**: `false`
**Debug/fileLogging**: `false`
**Editor/CurrentSchemaKey**: `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing**: `true`
**Editor/autoBracketRemoval**: `true`
**Editor/editorWidthInDFMOnly**: `true`
**Editor/highlightCurrentLine**: `true`
**Editor/vimMode**: `false`
**FileDialog/LastPath**: `D:/PROJECTS/AllMedia/PR-##-Customer.MediaName`
**FileDialog/LastPath-ImportTextFiles**: `D:/PROJECTS/AllMedia/PR-##-Customer.MediaName`
**FileDialog/LastPath-NoteMarkdownExport**: `D:/PROJECTS/AllMedia/PR-##-Customer.MediaName`
**IssueAssistantDialog/geometry**: `<binary data>`
**LastUpdateCheck**: `2018-10-09T15:53:51`
**LinkDialog/geometry**: `<binary data>`
**LogWidget/criticalLog**: `true`
**LogWidget/debugLog**: `true`
**LogWidget/fatalLog**: `true`
**LogWidget/infoLog**: `true`
**LogWidget/scriptingLog**: `true`
**LogWidget/statusLog**: `true`
**LogWidget/warningLog**: `true`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `30`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-111**: `notes/Deboart, Documents, Documents/ID, notes/Инфотека, Infoteka, notes, Deboart, Projects`
**MainWindow/noteTextEdit.code.font**: `Courier New,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `MS Shell Dlg 2,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `MS Shell Dlg 2,7.8,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl**: `false`
**MainWindow/showNotesFromAllNoteSubFolders**: `false`
**MainWindow/tagTreeWidgetExpandState-111**: `67, 89, 71`
**MessageBoxOverride/move-notes**: `16384`
**NoteDiffDialog/geometry**: `<binary data>`
**PiwikClientId**: `<hidden>`
**ScriptRepositoryDialog/geometry**: `<binary data>`
**ScriptRepositoryDialog/mainSplitterState**: `<binary data>`
**SearchEngineId**: `2`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**ShareDialog/geometry**: `<binary data>`
**ShowSystemTray**: `false`
**StartHidden**: `false`
**TodoDialog/geometry**: `<binary data>`
**TodoDialog/mainSplitterState**: `<binary data>`
**TodoDialog/showCompletedItems**: `0`
**TodoDialog/todoListSelectorSelectedItem**: `Личное`
**UpdateDialog/geometry**: `<binary data>`
**WelcomeDialog/geometry**: `<binary data>`
**acceptAllExternalModifications**: `true`
**allowDifferentNoteFileName**: `false`
**allowNoteEditing**: `true`
**allowOnlyOneAppInstance**: `true`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `true`
**appMetrics/notificationShown**: `true`
**automaticNoteFolderDatabaseClosing**: `false`
**closeTodoListAfterSave**: `false`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `111`
**currentWorkspace**: `29e118f9-b437-40a4-a332-628bfecf813d`
**cursorWidth**: `1`
**customNoteFileExtensionList**: *empty*
**darkMode**: `false`
**darkModeColors**: `false`
**darkModeTrayIcon**: `false`
**defaultNoteFileExtension**: `md`
**disableAutomaticUpdateDialog**: `false`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: *empty*
**fullyHighlightedBlockquotes**: `true`
**gitCommitInterval**: `30`
**gitExecutablePath**: *empty*
**gitLogCommand**: *empty*
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**imageScaleDown**: `false`
**imageScaleDownMaximumHeight**: `1024`
**imageScaleDownMaximumWidth**: `1024`
**insertTimeFormat**: *empty*
**interfaceLanguage**: *empty*
**internalIconTheme**: `false`
**itemHeight**: `18`
**localTrash/autoCleanupDays**: `30`
**localTrash/autoCleanupEnabled**: `true`
**localTrash/supportEnabled**: `true`
**markdownHighlightingEnabled**: `true`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `2`
**newNoteAskHeadline**: `false`
**noteEditIsCentralWidget**: `true`
**noteListPreview**: `false`
**noteSaveIntervalTime**: `10`
**noteSubfoldersPanelDisplayAsFullTree**: `true`
**noteSubfoldersPanelHideSearch**: `false`
**noteSubfoldersPanelOrder**: `0`
**noteSubfoldersPanelShowFullPath**: `false`
**noteSubfoldersPanelShowNotesRecursively**: `true`
**noteSubfoldersPanelShowRootFolderName**: `true`
**noteSubfoldersPanelSort**: `0`
**notesPanelOrder**: `0`
**notesPanelSort**: `1`
**notesPath**: `D:/DEBO/NextCloud/notes`
**notifyAllExternalModifications**: `false`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: `https://deboart.dhis.org/nextcloud`
**ownCloud/supportEnabled**: `true`
**ownCloud/todoCalendarBackend**: `3`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/todoCalendarDisplayNameList**: `Личное, DeboartCloud`
**ownCloud/todoCalendarEnabledList**: `Личное, DeboartCloud`
**ownCloud/todoCalendarEnabledUrlList**: `https://deboart.dhis.org/nextcloud/remote.php/dav/calendars/debo/personal/, https://deboart.dhis.org/nextcloud/remote.php/dav/calendars/debo/deboartcloud-1/`
**ownCloud/todoCalendarUrlList**: `https://deboart.dhis.org/nextcloud/remote.php/dav/calendars/debo/personal/, https://deboart.dhis.org/nextcloud/remote.php/dav/calendars/debo/deboartcloud-1/`
**ownCloud/userName**: `debo`
**ownCloudInfo/appIsValid**: `true`
**ownCloudInfo/connectionErrorMessage**: `Неизвестная ошибка`
**ownCloudInfo/notesPathExistsText**: `yes`
**ownCloudInfo/serverVersion**: `13.0.4.0`
**previousWorkspace**: `878a5693-9e14-4930-99f6-85c1ebfaf873`
**recentNoteFolders**: `D:/DEBO/NextCloud`
**restoreCursorPosition**: `true`
**savedSearches/noteFolder-111**: `Светлые, 2018-09-03T10.48.56 2018-10-03T16.54.52, Note 2018-10-03T11.05.49, Note 2018-10-01T21.46.48, Note 2018-10-01T21.38.04, Note 2018-09-25T17.36.24, правило 5-ти, PR-##-Customer, Summer_2018`
**showMenuBar**: `true`
**showStatusBar**: `true`
**skipVersion**: `18.09.1`
**tagWasAddedToNote**: `true`
**taggingShowNotesRecursively**: `true`
**tagsPanelHideSearch**: `false`
**tagsPanelOrder**: `0`
**tagsPanelSort**: `0`
**toolbar/1/items**: `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name**: `mainToolBar`
**toolbar/1/title**: `Главная панель инструментов`
**toolbar/2/items**: `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name**: `formattingToolbar`
**toolbar/2/title**: `панель инструментов форматирования`
**toolbar/3/items**: `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name**: `insertingToolbar`
**toolbar/3/title**: `панель инструментов вставки`
**toolbar/4/items**: `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name**: `encryptionToolbar`
**toolbar/4/title**: `панель инструментов шифрования`
**toolbar/5/items**: `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name**: `windowToolbar`
**toolbar/5/title**: `панель инструментов окна`
**toolbar/6/items**: `action_Quit`
**toolbar/6/name**: `quitToolbar`
**toolbar/6/title**: `Панель инструментов выхода`
**toolbar/size**: `6`
**useUNIXNewline**: `false`
**workspace-29e118f9-b437-40a4-a332-628bfecf813d/name**: `Debo`
**workspace-29e118f9-b437-40a4-a332-628bfecf813d/noteSubFolderDockWidgetVisible**: `true`
**workspace-29e118f9-b437-40a4-a332-628bfecf813d/windowState**: `<binary data>`
**workspace-494cb6a2-b3d8-4b76-b93b-7cbc7155a202/name**: `на весь экран`
**workspace-494cb6a2-b3d8-4b76-b93b-7cbc7155a202/noteSubFolderDockWidgetVisible**: `true`
**workspace-494cb6a2-b3d8-4b76-b93b-7cbc7155a202/windowState**: `<binary data>`
**workspace-878a5693-9e14-4930-99f6-85c1ebfaf873/name**: `минимальный`
**workspace-878a5693-9e14-4930-99f6-85c1ebfaf873/noteSubFolderDockWidgetVisible**: `true`
**workspace-878a5693-9e14-4930-99f6-85c1ebfaf873/windowState**: `<binary data>`
**workspaces**: `494cb6a2-b3d8-4b76-b93b-7cbc7155a202, 878a5693-9e14-4930-99f6-85c1ebfaf873, 29e118f9-b437-40a4-a332-628bfecf813d`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\DeBo\AppData\Roaming`
**CLASSPATH**: `.;C:\Program Files (x86)\QuickTime\QTSystem\QTJava.zip`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `ROBOTICS`
**ComSpec**: `C:\Windows\system32\cmd.exe`
**destination**: `"D:\Program Files (x86)\QOwnNotes"`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**FSHARPINSTALLDIR**: `C:\Program Files (x86)\Microsoft SDKs\F#\10.1\Framework\v4.0\`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\DeBo`
**INTEL_DEV_REDIST**: `C:\Program Files (x86)\Common Files\Intel\Shared Libraries\`
**LOCALAPPDATA**: `C:\Users\DeBo\AppData\Local`
**LOGONSERVER**: `\\ROBOTICS`
**MIC_LD_LIBRARY_PATH**: `C:\Program Files (x86)\Common Files\Intel\Shared Libraries\compiler\lib\mic`
**MSMPI_BIN**: `C:\Program Files\Microsoft MPI\Bin\`
**NUMBER_OF_PROCESSORS**: `4`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;D:\Program Files\ImageMagick;C:\Program Files\Microsoft MPI\Bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Calibre2\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\dotnet\;D:\Program Files (x86)\Pandoc\;C:\Program Files\Git\cmd;C:\Users\DeBo\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Nmap`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 158 Stepping 9, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `9e09`
**PROG27B48B2C051**: `1`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PROMPT**: `$P$G`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Intel\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\`
**PUBLIC**: `C:\Users\Public`
**qownnotesCommand**: `"D:\Program Files (x86)\QOwnNotes"\QOwnNotes.exe --after-update C:\Users\DeBo\AppData\Local\Temp\1\QOwnNotes-VjEQAF-updater.bat `
**QTJAVA**: `C:\Program Files (x86)\QuickTime\QTSystem\QTJava.zip`
**SESSIONNAME**: `Console`
**source**: `C:\Users\DeBo\AppData\Local\Temp\1\QOwnNotes-VjEQAF.zip`
**SystemDrive**: `C:`
**SystemRoot**: `C:\Windows`
**TEMP**: `C:\Users\DeBo\AppData\Local\Temp\1`
**TMP**: `C:\Users\DeBo\AppData\Local\Temp\1`
**unzipCommand**: `C:\Users\DeBo\AppData\Local\Temp\1\QOwnNotes-VjEQAF-unzip.exe -o C:\Users\DeBo\AppData\Local\Temp\1\QOwnNotes-VjEQAF.zip -d "D:\Program Files (x86)\QOwnNotes"`
**unzipExecutable**: `C:\Users\DeBo\AppData\Local\Temp\1\QOwnNotes-VjEQAF-unzip.exe`
**USERDOMAIN**: `ROBOTICS`
**USERDOMAIN_ROAMINGPROFILE**: `ROBOTICS`
**USERNAME**: `DeBo`
**USERPROFILE**: `C:\Users\DeBo`
**VS140COMNTOOLS**: `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\`
**windir**: `C:\Windows`

**Comment by pbek** [comment]
> after replasing the database stopping working tagging

what exactly did you do?

so what is the content of the table that links notes to tags in `D:\DEBO\NextCloud\notes\notes.sqlite`?

**Comment by pbek** [comment]
Ah, you are using the script `@tag tagging in note text (experimental)`. So this is more a question regarding a script. You should ask the authors of the script directly, best on https://github.com/qownnotes/scripts/issues.

**Comment by pbek** [comment]
The script removes all your local tags from the sqlite database and uses the tags that are embedded in your note text files.

**Comment by pbek** [comment]
See the script description:

```
If you install this script you will loose all links between notes and tags and instead your in-note tags will be used!
```

**Comment by pbek** [comment]
Does this answer your question?
