### ISSUE TITLE
Remembering position in notes not only for the last note after restart

### ISSUE THREAD

**Issue by illucent** [pbek/QOwnNotes#1044]
#### Expected behaviour
Switching between notes focus / mouse position at the bottom of the page.
Default position at the top of the note page.
#### Actual behaviour
Switching between notes resets mouse position and focus / resets / autoscrolls to the top of the page / note.
#### Steps to reproduce
Switch between multiple notes in 'Note list' sidebar.
#### Output from the debug section in the settings dialog
n/a
#### Relevant log output in the Log panel
n/a

**Comment by pbek** [comment]
Can you please explain in more detail and step by step what you did, what happened and what you expected.

Could you please use the issue assistant in the `Help` menu to post this issue so you can provide needed information more easily?

The menu entry is named `Post questions, feature requests or issues`.

**Comment by pbek** [comment]
Thank you for the more detailed report. If I close QOwnNotes the cursor position AND and the scrollbar position are restored when I start QOwnNotes again. This also works for you as I can see in the video. But you want that the position of every note that you viewed is restored, correct?

**Comment by illucent** [comment]
yes

**Comment by pbek** [comment]
## 18.10.3
- the last 200 entries of the note history will now be stored when you switch 
  note folders or quit the application and will be restored accordingly
    - please visit [QOwnNotes shortcuts](https://www.qownnotes.org/shortcuts/QOwnNotes)
      for a list of all shortcuts to navigate the note history
    - if you have enabled the setting `Restore cursor position when opening a note`
      in the *General settings* your position in notes will be restored if 
      you restart the application or switch between note folders

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by illucent** [comment]
Works. Thanks a lot.
`QOwnNotes - version 18.10.5 - OBS - build 486`

**Comment by pbek** [comment]
Great, thank you for testing! It was a lot of work but I love the feature ;)
