### ISSUE TITLE
Problems Installing QOwnNotes

### ISSUE THREAD

**Issue by Ivan64** [pbek/QOwnNotes#1045]
I'm running Debian Testing (currently Buster). Tried to install the repository but I get these errors:

W: GPG error: http://ppa.launchpad.net/pbek/qownnotes/ubuntu cosmic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54223C6547878405
E: The repository 'http://ppa.launchpad.net/pbek/qownnotes/ubuntu cosmic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

The error message conflicts with the warning message.

**Comment by pbek** [comment]
1) I guess you forgot to import the key. 2) Why are you using Ubuntu PPAs in Debian? :)

Better use https://www.qownnotes.org/installation#Debian

Does this answer your question?

**Comment by Ivan64** [comment]
yes, I deleted the Ubuntu PPA and installed QOwnNotes. I messed up somewhere, thanks for your patience.

**Comment by pbek** [comment]
Great ;)
