### ISSUE TITLE
Import from evernote ENEX format does not handle code blocks

### ISSUE THREAD

**Issue by Gazoo** [pbek/QOwnNotes#1047]
#### Expected behaviour
When importing notes from Evernote ENEX format code blocks should be wrapped within markdown code tags ```.

#### Actual behaviour
Code blocks are not wrapped in markdown code tags  ``` .

#### Steps to reproduce
Export note into ENEX format from evernote.

#### Operating system
WIndows 10, using QOwnNotes version 18.10.4 build 3899
![evernote]

####  Screens
Evernote
![evernote](https://user-images.githubusercontent.com/379016/47266374-c2318700-d4f2-11e8-9120-07cec8d42e25.png)

After Import
![after import](https://user-images.githubusercontent.com/379016/47266383-d37a9380-d4f2-11e8-904e-d5484b4de2d2.png)

**Comment by pbek** [comment]
Thank you for your suggestion.
Could you please post an enex file with a code block.

**Comment by Gazoo** [comment]
Here is a test enex I exported that contains a code block. I had to zip it up as github doesn't allow attaching .enex files.

[test.zip](https://github.com/pbek/QOwnNotes/files/2499455/test.zip)

**Comment by pbek** [comment]
Thank you!

**Comment by pbek** [comment]
It was a bit tricky, but I think I've got it working now (without regressions).

## 18.10.5
- the **Evernote importer** is now able to import **code blocks**

**Comment by Gazoo** [comment]
Thanks man!

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you (when the build is done)?

**Comment by Gazoo** [comment]
Sure thing. I'll update this with my results.

**Comment by Gazoo** [comment]
Unfortunately they still don't import properly.

Evernote Note
![evernote](https://user-images.githubusercontent.com/379016/47448703-eb197c80-d77d-11e8-91e6-c609daefeb43.png)

After Import
![import](https://user-images.githubusercontent.com/379016/47448712-f076c700-d77d-11e8-84f5-936ffcd63f2e.png)

Sample ENEX used.
[Colorized grep.zip](https://github.com/pbek/QOwnNotes/files/2511569/Colorized.grep.zip)

**Comment by pbek** [comment]
I worked on your previous example and an other I found. I'll take a look. But I cannot promise a lot, the syntax for code blocks in the enex file is very wonky.

**Comment by pbek** [comment]
phew, took quite some time...

## 18.10.6
- improved code block import of the **Evernote importer**
    - some other issues were also fixes

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Gazoo** [comment]
Sorry man still doesn't import properly. I suggest that you might want to just give up on this one :(

Evernote
![2018-10-29_10h19_00](https://user-images.githubusercontent.com/379016/47664278-54c1ce00-db64-11e8-85af-b018c121fab3.png)

After Import
![2018-10-29_10h18_50](https://user-images.githubusercontent.com/379016/47664294-5be8dc00-db64-11e8-9e2f-3bfb656866e4.png)

Enex file
[Evernote.zip](https://github.com/pbek/QOwnNotes/files/2526109/Evernote.zip)

**Comment by pbek** [comment]
I'll check the new examples... ;)

**Comment by pbek** [comment]
Your latest example uses a slightly other notation for code blocks, I integrated that one too now.

## 18.11.0
- improved code block import of the **Evernote importer**

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Gazoo** [comment]
The new release fixed it. My notes import properly now :) Thanks man!

**Comment by pbek** [comment]
Finally! :)
