### ISSUE TITLE
Best way to create new notes quickly? 

### ISSUE THREAD

**Issue by MarkQueppet** [pbek/QOwnNotes#1048]
In Evernote I'm reliant on being able to quickly press ctrl+alt+n to create a new window where I can quickly jot down a note no matter what I'm doing which then gets saved to my inbox without messing up whatever view I'm currently working in.

I'm trying to figure out how to replicate this behavior in QOwnNotes, as this is a critical part of my workflow. 

I saw in #44 that you aren't able to set up global shortcuts natively, so I don't expect you to implement what Evernote does. 

Is there a way I can simply add notes from an external source? I tried creating new notes by just adding them to the notes folder using an external editor, but the notes are not recognized in QOwnNotes (probably because they aren't added to the database or something when I just create them externally?)

Is there any recommended work around for this? 

I appreciate any help you can offer as I REALLY love what you've done with this app... it's really incredible in terms of an attempt at "futureproofing" your own knowledge base... but if I can't quickly capture thoughts to an inbox I'll probably have to keep relying on Evernote. 

---
**EDIT**
For some reason I can easily create a new note externally now. I think I unknowingly was filtering by a tag and couldn't see my new notes. Sorry for the inconvenience - please mark this as closed. 

However, this does make me incredibly excited - this app is extremely cool 👍

**Comment by pbek** [comment]
You can also use some other tool to place a shortcut on opening the QOwnNotes app itself, that would bring the app to the foreground. Would that be an alternative for you?

**Comment by pbek** [comment]
You can also use some other tool to place a shortcut on opening the QOwnNotes app itself, that would bring the app to the foreground. Would that be an alternative for you?

**Comment by MarkQueppet** [comment]
@pbek only if I could make it possible that the next note I create goes to my "inbox" folder. 

So if I was working on a specific project in QOwnNotes, I'd likely have the associated project files selected. If I in the middle of that I had an idea for some OTHER task or project, simply focusing QOwnNotes would then require me to navigate to the inbox folder to make the quick note, and then navigate back to where I was at. 

Often thoughts flash through my mind and if I don't capture them immediately in a specific place that I consistently review/refile etc. I lose them. Constantly interrupting my current workspace to capture such notes is equally as unhelpful. 

If you can think of a better way to implement this sort of "capture" behavior in QOwnNotes I'm all ears! Evernote, OneNote and many task management applications just utilize the global shortcut approach.

**Comment by pbek** [comment]
I guess you could create some custom actions (that you could give some shortcuts) to jump to a specific note folder with the help of http://docs.qownnotes.org/en/develop/scripting/README.html#jumping-to-a-note-subfolder

**Comment by pbek** [comment]
> However, this does make me incredibly excited

The mysteries of technology make me excited too! :smile: 

> this app is extremely cool

thank you! :pray:

**Comment by pbek** [comment]
Meanwhile there also is a browser companion for QOwnNotes: https://www.qownnotes.org/Knowledge-base/QOwnNotes-Web-Companion-browser-extension

I will close this issue until there is more information.

**Comment by pbek** [comment]
You may want to test https://github.com/pbek/QOwnNotes/issues/44, @MarkQueppet

**Comment by pbek** [comment]
## 20.3.8
- added experimental **global keyboard shortcut support** (for [#44](https://github.com/pbek/QOwnNotes/issues/44))
    - <kbd>Meta + Shift + N</kbd> will now create a new note

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
## 20.3.9
- you can now also manage **global keyboard shortcuts** in the *Shortcuts settings*
  (for [#44](https://github.com/pbek/QOwnNotes/issues/44))
    - there you can set a global shortcut to every action of the main menu,
      including custom scripting actions
    - you can also search for global shortcuts in the `Search for shortcut` line edit
    - by default there are no global shortcuts activated

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
