### ISSUE TITLE
[I] Can't share files to owncloud

### ISSUE THREAD

**Issue by jtfilion** [pbek/QOwnNotes#1049]
#### Expected behaviour

I hit the share button, which brings up a dialog with a check box.  I click the check box.  I would think the file would be posted on OwnCloud.

#### Actual behaviour

ownCloud / Nextcloud server error: Wrong path, file/folder doesn't exist
Please check your ownCloud / Nextcloud configuration.

Perhaps I don't understand how the notes are to be shared on OwnCloud.  The setup dialog doesn't seem to have any trouble connecting to my server once I created a 'Notes' folder.

#### Steps to reproduce

Create a note and hit the 'share' button.

#### Relevant log output in the Log panel

```
[00:00:58] [status] Stored 1 note(s) to disk
[00:00:59] [status] Notes directory was modified externally
[00:00:59] [status] Note was modified externally: /Users/John/Nextcloud/Notes/General Notes 2018-10-22T23_40_52.md
```

#### Information about the application, settings and environment

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Oct 23 00:02:29 2018`
**Version**: `18.10.4`
**Build date**: `Oct 21 2018`
**Build number**: `3884`
**Platform**: `macosx`
**Operating System**: `macOS High Sierra (10.13)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.11.2`
**Qt Version (runtime)**: `5.11.2`
**Portable mode**: `no`
**Settings path / key**: `/Users/John/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/John/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`, `-psn_0_1458532`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `4`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `http://jtvfilion.mywire.org/owncloud`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `10.0.10.4`
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/Users/John/Nextcloud/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/Users/John/Nextcloud/Notes/notes.sqlite`

## Settings

**AKLastCheckInAttemptDate** (QDateTime): `2018-05-26T11:55:32.422`
**AKLastCheckInSuccessDate** (QDateTime): `2018-05-26T11:55:33.234`
**AKLastEmailListRequestDateKey** (QDateTime): `2018-07-17T10:25:00.370`
**AKLastIDMSEnvironment** (qlonglong): `0`
**ASIX Elec/ AX88179** (QString): `1`
**Amazon Kindle** (QString): `1`
**Country** (QString): `US`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**DisplayLink USB to DVI-17** (QString): `1`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/vimMode** (bool): `false`
**Generic USB Storage** (QString): `1`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**Kingston DataTraveler 2/0** (QString): `1`
**LastUpdateCheck** (QDateTime): `2018-10-22T23:03:26.410`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MCT Corp/ MCT USB3/0 External Graphics Device** (QString): `1`
**MainWindow/mainToolBar.iconSize** (qlonglong): `32`
**MainWindow/noteTextEdit.code.font** (QString): `Monaco,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `.SF NS Text,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Monaco,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `.SF NS Text,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**Monster MONSTER DIGITAL** (QString): `1`
**NA Wireless Audio** (QString): `1`
**NVIDIA Corp/ APX** (QString): `1`
**NoteHistory-1** (QVariantList): `<variant list with 5 item(s)>`
**NoteHistoryCurrentIndex-1** (qlonglong): `4`
**PKSecureElementAvailableFlags** (qlonglong): `1`
**PiwikClientId** (QString): `<hidden>`
**Realtek RTL2838UHIDIR** (QString): `1`
**SanDisk Cruzer Glide** (QString): `1`
**Seagate BUP Slim SL** (QString): `1`
**SearchEngineId** (qlonglong): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**USB Disk 2/0** (QString): `1`
**USB Reader USB Mass Storage Device** (QString): `1`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowDifferentNoteFileName** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `false`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (bool): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (qlonglong): `1`
**currentWorkspace** (QString): `b2087ff8-9f88-4095-8e66-db70a0e348e5`
**cursorWidth** (qlonglong): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (bool): `true`
**disableAutomaticUpdateDialog** (bool): `false`
**dockWasInitializedOnce** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (qlonglong): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (qlonglong): `1024`
**imageScaleDownMaximumWidth** (qlonglong): `1024`
**insertTimeFormat** (QString): *empty*
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (qlonglong): `18`
**localTrash/autoCleanupDays** (qlonglong): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (qlonglong): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (qlonglong): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (qlonglong): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (qlonglong): `0`
**notesPanelOrder** (qlonglong): `0`
**notesPanelSort** (qlonglong): `1`
**notesPath** (QString): `/Users/John/Nextcloud/Notes`
**notifyAllExternalModifications** (bool): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): `http://jtvfilion.mywire.org/owncloud`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (qlonglong): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Personal`
**ownCloud/todoCalendarEnabledList** (QStringList): `Personal`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `http://jtvfilion.mywire.org/owncloud/remote.php/dav/calendars/john/personal/`
**ownCloud/todoCalendarUrlList** (QStringList): `http://jtvfilion.mywire.org/owncloud/remote.php/dav/calendars/john/personal/`
**ownCloud/userName** (QString): `john`
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `10.0.10.4`
**previousWorkspace** (QString): `7dcafa6b-1b7a-4c11-a51e-347b4e753287`
**restoreCursorPosition** (bool): `false`
**savedSearches/noteFolder-1** (QStringList): `General Notes`
**showMenuBar** (bool): `false`
**showStatusBar** (bool): `true`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (qlonglong): `0`
**tagsPanelSort** (qlonglong): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (qlonglong): `6`
**useUNIXNewline** (bool): `false`
**workspace-7dcafa6b-1b7a-4c11-a51e-347b4e753287/name** (QString): `full`
**workspace-7dcafa6b-1b7a-4c11-a51e-347b4e753287/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-7dcafa6b-1b7a-4c11-a51e-347b4e753287/windowState** (QByteArray): `<binary data>`
**workspace-b2087ff8-9f88-4095-8e66-db70a0e348e5/name** (QString): `minimal`
**workspace-b2087ff8-9f88-4095-8e66-db70a0e348e5/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-b2087ff8-9f88-4095-8e66-db70a0e348e5/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `7dcafa6b-1b7a-4c11-a51e-347b4e753287, b2087ff8-9f88-4095-8e66-db70a0e348e5`

## System environment

**__CF_USER_TEXT_ENCODING**: `0x1F5:0x0:0x0`
**TMPDIR**: `/var/folders/wz/kfm7qbhs1h5710jgvykr9slw0000gn/T/`
**HOME**: `/Users/John`
**SHELL**: `/bin/bash`
**Apple_PubSub_Socket_Render**: `/private/tmp/com.apple.launchd.9Sdf0bN7pz/Render`
**SSH_AUTH_SOCK**: `/private/tmp/com.apple.launchd.DOxglIH7fM/Listeners`
**DBUS_LAUNCHD_SESSION_BUS_SOCKET**: `/private/tmp/com.apple.launchd.0qLQs900qz/unix_domain_listener`
**DISPLAY**: `/private/tmp/com.apple.launchd.YaVwUFaitL/org.macosforge.xquartz:0`
**PATH**: `/usr/bin:/bin:/usr/sbin:/sbin`
**LOGNAME**: `John`
**XPC_SERVICE_NAME**: `com.apple.xpc.launchd.oneshot.0x10000021.QOwnNotes`
**COMMAND_MODE**: `unix2003`
**USER**: `John`
**XPC_FLAGS**: `0x0`
**QT_LOGGING_RULES**: `qt.network.ssl.warning=false`

**Comment by pbek** [comment]
> I would think the file would be posted on OwnCloud.

No, it will use the Nextcloud / ownCloud share api to create a publicly available link of your remote note file on your server. You still have to sync your files yourself.

Does this answer your question? :)

**Comment by pbek** [comment]
I made a note to myself to put some more text to the dialog if that was unclear.

**Comment by jtfilion** [comment]
Thanks for the quick reply.  How do I do the sync?  Is there another app to
do that?

Thanks,
John

**Comment by pbek** [comment]
https://nextcloud.com/install/#install-clients

**Comment by jtfilion** [comment]
Maybe I don't understand how the program works.  I had thought that I could
link owncloud and then any notes that I make on one computer would show up
on another computer linked to the same owncloud account.  I have two
computers, and I created a note on one, and I don't see it on the other.  I
also tried to go in the other direction, but I don't see anything.  That's
why I thought I needed to share or sync.  But now I don't know if that
feature doesn't exist, or if it exists, but isn't working for me.

Thanks,
John

**Comment by jtfilion** [comment]
You can ignore my last email.  I found the help that I needed in the
Knowledge Base section. When I saw that the API only handles trashed notes
and note versions, I realized that I needed to install the owncloud client
on each machine so that I could synchronize the files between systems.
Thanks again for your help and your patience.

John

**Comment by pbek** [comment]
Great we could spread some light on the issue. :)

**Comment by pbek** [comment]
## 18.10.5
- added a notification that you have to sync your notes yourself when sharing notes

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by jtfilion** [comment]
Hi Patrizio,

I updated and tried it on the macOS and Windows clients, and it appears to
work fine.  A couple of comments, though:


* The confusion I had was on the owncloud section of the preferences.  The
issue was with the term 'sync tool'.  As far as I can tell, this is the
windows or macOS client program.  Owncloud refers to this on the download
page as the 'desktop client'.  I had thought that the sync tool was an app
that I couldn't find in the owncloud appstore.  I'm not sure others have
this same confusion.
* In the share pop-up message, where it says "you still have sync", it
should say "you still have to sync".  But I think the message may not be
needed, as explained below.
* I don't know what the check box does in the share dialog.  The message
associated with the checkbox also adds to the confusion.  It makes it sound
like checking the box will cause the note to be shared.  But, it actually
is just providing a link that others who want to share the note can use.
Once the share icon on the top toolbar is selected, I suggest that it
should just open a dialog that shows the link to use, and then provide
'OK'.  It could have a 'Copy' button as well for the user's convenience.
Of course, it should also have a description to go with the link.  I think
something like "Send this link to the party or parties you wish to share
this note with:"
* The other source of confusion was actually in the handling of the error.
Since I was not putting my notes on owncloud, there was no way for your
tool to set up a link for others to use.  If the message stated that the
share link cannot be made because the note only exists locally, that
probably would have been more helpful.

Just my two cents.  I hope it helps.  I'm looking forward to using the
program now that I have it set up properly.

Thanks,
John

**Comment by pbek** [comment]
> I suggest that it
should just open a dialog that shows the link to use, and then provide
'OK'.  It could have a 'Copy' button as well for the user's convenience.

that doesn't work this way, you only get the link from NC / oC if you actually are sharing the file

**Comment by pbek** [comment]
## 18.10.6
- added more information to the note sharing dialog and the sharing notification

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by jtfilion** [comment]
I downloaded the new version and tried to share.  It presented the dialog
box that said "Keep in mind...", but when I hit OK, the box was not
checked, and there was no link provided.  I tried to disable the message
with the "Don't show again" check box, but it seems to do the same thing.

My owncloud server is a little flaky right now, but QOwnNotes seems to be
working fine otherwise.

Thanks,
John

**Comment by pbek** [comment]
Please enable the log panel, you should get an error message...

**Comment by jtfilion** [comment]
I enabled the log file, which has the following path:
C:\Users\User\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.log

I tried the share again, but I can't find the log file. If the path doesn't
exist, will your program build it? I do not have an AppData directory, so
that whole directory branch would need to be built. Is there a way to
change the location of the log file?

Thanks,
John

**Comment by pbek** [comment]
Of course the log file will be created, but I was talking about the log panel (Menu: Windows / Panels)

**Comment by jtfilion** [comment]
OK, I found it.  But it doesn't show any messages when I repeat the
experiment.
