### ISSUE TITLE
Feature request: Paste and drag-and-drop of images

### ISSUE THREAD

**Issue by praxiq** [pbek/QOwnNotes#105]
The existing "Insert Image" command is great, but it'd be nice if we could also get images into notes by pasting them from the clipboard, or by dragging and dropping an image file into the note. The result of either of these should be the same as the current "Insert Image" command - the image file would be copied into (or when pasting, created in) a "media" directory inside the notes directory. (I don't know how hard it might be to implement these in a cross-platform way.)

**Comment by pbek** [comment]
Thank you for your suggestion, @praxiq. I will look into that!

**Comment by pbek** [comment]
- added support for dragging and dropping images into notes
- added support for copying and pasting images into notes from a file manager
- added support for copying and pasting images from an image manipulation software into a note

**Comment by pbek** [comment]
Version 1.1.4 is now out, could you be so kind and report if it works as desired.

**Comment by pbek** [comment]
ping @praxiq

**Comment by offerlam** [comment]
Hi

None of it works on the windows version?

im still learning though so i may do some wrong?

im right that Qownnotes should work with the ownnote app in owncloud right?

so im assuming that i make my notes in the left windows and should be able to drag and drop images into the right windows when in the Edit tap.

If this is true its not working in windows application

**Comment by pbek** [comment]
Thank you for your report, @offerlam 

No, QOwnNotes doesn't support ownNote.
<http://www.qownnotes.org/Knowledge-base/Does-QOwnNotes-support-ownNote>

If you drop an image into a note some markdown code should be inserted. Does this work as I described it?

**Comment by offerlam** [comment]
im not sure what you mean.. 

If i drag and drop and image from my desktop into the edit tap of a note i can see it just points to file:///C:/bla/bla/bla

after a little while i get this next to the text [Absalom_map](file://media/24205.jpg)

If i go to the markdown tap I can see the same line

file:///c:/bla/bla/bla and than there is a little paper icon next to it... 

hope that helped..

regarding qownnote support of notes.. I get now that it support the built it note taking app of owncloud.. right?.. and don't care what i use... as long as it works with owncloud and as long as i can drag and drop.. 

I have a bunch of onenote pages that i need to transfere and it would be easiest if i could just highlight the entire content of a page and copy paste it into a note in QOwnNote

**Comment by pbek** [comment]
Thanks again for reporting this, @offerlam. It seems that no Windows users inserted images so far. :smile: 
The following should now be fixed under Windows:
- dragging and dropping of images into notes
- the image preview in markdown mode
- opening of links to local files

Can you please try again with version 1.1.5, that was just released and is currently building. Thanks a lot.

Regarding your notes:
Yes, QOwnNotes works with the ownCloud notes app. ;)
Yes, you can copy and paste your ownNote notes to QOwnNotes but you will loose formatting and stuff since ownNote uses a rich text editor and HTML and the ownCloud notes are plain text.

**Comment by offerlam** [comment]
testing now.. hold on

**Comment by offerlam** [comment]
its working with drag and dropping a picture.. 

but if i go to a homepage with screenshots say a guide to setup something and I mark it all and say copy. I don't get the screenshots when i paste. Only the text.

this goes aswell for owncloud pages contaning pictures..

**Comment by pbek** [comment]
Thank you for testing!
Currently you can paste an image that was in the clipboard.
Getting images out of copied rich text would be a completely different matter, that I can investigate if you open a new issue for it.

**Comment by offerlam** [comment]
i will.. and no problem

**Comment by pbek** [comment]
Thank you! I will close this issue now.

**Comment by praxiq** [comment]
Copying images and pasting them using the "Paste HTML or Media" option works great on OSX! And dragging an image file from the Finder works well too, but dragging an image from, say, a web browser, which works in many other apps, doesn't do anything. That'd be a nice feature, but it is by no means high-priority.

(It might be nice if "Paste HTML or Media" was invoked automatically in cases where it was the only valid option, i.e. regular paste produces no content.)

**Comment by pbek** [comment]
> dragging an image from, say, a web browser, which works in many other apps, doesn't do anything.

I will take a look at that.

> It might be nice if "Paste HTML or Media" was invoked automatically

I will see how hard it is to intercept default pasting...

**Comment by pbek** [comment]
both is now implemented in 1.1.7

**Comment by pbek** [comment]
@praxiq, v1.1.7 is out now (currently building). Does it work for you?
