### ISSUE TITLE
[I] Interpret lists as such without preceeding empty line

### ISSUE THREAD

**Issue by NicolasToussaint** [pbek/QOwnNotes#1050]
#### Expected behaviour

The following md text should interpreted  the list as such:

Foo
- one
- two

I didn't find the entry in the Markdown specifications, but all MD Editors I have tried behave this way.

#### Actual behaviour

The following md text is interpreted as one single line "Foo - one - bar":

Foo
- one
- two

To has a list, one must insert an empty line above the start of the list.

Foo

- one
- two

#### Steps to reproduce

Foo
- one
- two

#### Relevant log output in the Log panel

```

```

#### Information about the application, settings and environment

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `mar. oct. 23 17:55:36 2018`
**Version**: `18.10.1`
**Build date**: `Oct  9 2018`
**Build number**: `482`
**Platform**: `linux`
**Operating System**: `Ubuntu 18.04.1 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.9.5`
**Qt Version (runtime)**: `5.9.5`
**Portable mode**: `no`

**Comment by pbek** [comment]
GitHub interpreted your markdown code, but I think I know what you were talking about.

I'm sorry, that's the way the hoedown library works. But you can always switch to the "markdown-it" parser, by using similar named script from the script repository.

Does this answer your question?

**Comment by NicolasToussaint** [comment]
Hi pbek,
Magic, works like a charm, thanks !

**Comment by pbek** [comment]
Great ;)
