### ISSUE TITLE
Note disappeared

### ISSUE THREAD

**Issue by nosalan** [pbek/QOwnNotes#1051]
I use QOwn notes with Google sync of notes folder + I have git installed.

On October 5th morning I created (or started editing) a _blockchain.md_ note and was editing it for few hours.
Till today I thought I had this note, but
- it's not in QOwnNotes
- it's not on Google backup
- it's not in any of git commits
- it's not anywhere on my harddrive (I searched all files with Total Commander)

There are two traces of the note:
1. The commit of image that I pasted to that note:
![image](https://user-images.githubusercontent.com/2273250/47428763-8f0e2280-d794-11e8-8521-3e92fc8d1231.png)
Weird is that the commit only included the png file. It did not include the missing note which I pasted the image to. The adjacent commits also don't include that note. I vaguely recall that when I pasted this image from clipboard, it did not show in preview window but considered it a temporary glitch.

2. The entry in _notes.sqlite_ file, _trashItem_ table:
![image](https://user-images.githubusercontent.com/2273250/47428994-30957400-d795-11e8-8f1c-c303fb9151c6.png)

I suppose it points to trash file named _30_, but the file has 0 bytes in trash folder. I'm sure I didn't delete that note so it must have happened automatically.

Since, the note is not in any of git commits, I think QOwnNotes did not save this note to disk and allowed me to edit it without me knowing it was not saved to disk at all. Or it may have deleted the note while I was still editing it somehow.

In debug.log I found one line:
[0927/155608.964:**ERROR**:file_io_win.cc(243)] SetEndOfFile: **The requested operation cannot be performed on a file with a user-mapped section open. (0x4C8)**

The date is a bit earlier but I tend to keep the app open all the time.

#### Steps to reproduce
Don't know

#### Output from the debug section in the settings dialog
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed Oct 24 13:50:28 2018`
**Version**: `18.10.1`
**Build date**: `Oct  9 2018`
**Build number**: `3878`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.10.1`
**Qt Version (runtime)**: `5.10.1`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\REPLACED_USERNAME\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\A_SOFT\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `27`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Note folders

**currentNoteFolderId**: `8`

### Note folder `default`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `C:\Users\REPLACED_USERNAME\Documents\QOwnNotes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\REPLACED_USERNAME\Documents\QOwnNotes\notes.sqlite`

### Note folder `new folder`

**id**: `11`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `C:\Users\REPLACED_USERNAME\Nextcloud\Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\REPLACED_USERNAME\Nextcloud\Notes\notes.sqlite`

### Note folder `das Privatleben`

**id**: `10`
**isCurrent**: `no`
**activeTagId**: `-1`
**localPath**: `C:\Users\REPLACED_USERNAME\Documents\QOwnNotes\das Privatleben`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\REPLACED_USERNAME\Documents\QOwnNotes\das Privatleben\notes.sqlite`

### Note folder `die Technologie`

**id**: `8`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `C:\Users\REPLACED_USERNAME\Documents\QOwnNotes\die Technologie`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\REPLACED_USERNAME\Documents\QOwnNotes\die Technologie\notes.sqlite`

### Note folder `die Anstellung`

**id**: `9`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `C:\Users\REPLACED_USERNAME\Documents\QOwnNotes\die Anstellung`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\REPLACED_USERNAME\Documents\QOwnNotes\die Anstellung\notes.sqlite`

## Settings

**ActiveNoteHistoryItem**: *empty*
**Debug/fakeOldVersionNumber**: `false`
**Debug/fileLogging**: `false`
**Editor/CurrentSchemaKey**: `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing**: `true`
**Editor/autoBracketRemoval**: `true`
**Editor/editorWidthInDFMOnly**: `true`
**Editor/highlightCurrentLine**: `true`
**Editor/vimMode**: `false`
**FileDialog/LastPath**: `C:/Program Files (x86)/Git/cmd`
**FileDialog/LastPath-GitExecutable**: `C:/Program Files (x86)/Git/cmd`
**IssueAssistantDialog/geometry**: `<binary data>`
**LastUpdateCheck**: `2018-10-24T13:07:19`
**LinkDialog/geometry**: `<binary data>`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `24`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-8**: `Other, Web tech`
**MainWindow/noteTextEdit.code.font**: `Courier New,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl**: `false`
**MainWindow/showNotesFromAllNoteSubFolders**: `false`
**PiwikClientId**: `<hidden>`
**SearchEngineId**: `2`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**ShareDialog/geometry**: `<binary data>`
**ShowSystemTray**: `false`
**StartHidden**: `false`
**UpdateDialog/geometry**: `<binary data>`
**WelcomeDialog/geometry**: `<binary data>`
**acceptAllExternalModifications**: `false`
**allowDifferentNoteFileName**: `false`
**allowNoteEditing**: `true`
**allowOnlyOneAppInstance**: `true`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `false`
**appMetrics/notificationShown**: `true`
**automaticNoteFolderDatabaseClosing**: `false`
**closeTodoListAfterSave**: `false`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `8`
**currentWorkspace**: `d84f8904-80fd-4449-afb8-6dc33d737caf`
**cursorWidth**: `1`
**customNoteFileExtensionList**: *empty*
**darkMode**: `false`
**darkModeColors**: `false`
**darkModeTrayIcon**: `false`
**defaultNoteFileExtension**: `md`
**demoNotesCreated**: `true`
**disableAutomaticUpdateDialog**: `false`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: *empty*
**fullyHighlightedBlockquotes**: `false`
**gitCommitInterval**: `30`
**gitExecutablePath**: `C:/Program Files (x86)/Git/cmd/git.exe`
**gitLogCommand**: *empty*
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**imageScaleDown**: `false`
**imageScaleDownMaximumHeight**: `1024`
**imageScaleDownMaximumWidth**: `1024`
**insertTimeFormat**: *empty*
**interfaceLanguage**: *empty*
**internalIconTheme**: `false`
**itemHeight**: `15`
**localTrash/autoCleanupDays**: `30`
**localTrash/autoCleanupEnabled**: `true`
**localTrash/supportEnabled**: `true`
**markdownHighlightingEnabled**: `true`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `2`
**newNoteAskHeadline**: `false`
**noteEditIsCentralWidget**: `true`
**noteListPreview**: `false`
**noteSaveIntervalTime**: `10`
**noteSubfoldersPanelDisplayAsFullTree**: `true`
**noteSubfoldersPanelHideSearch**: `false`
**noteSubfoldersPanelOrder**: `0`
**noteSubfoldersPanelShowFullPath**: `false`
**noteSubfoldersPanelShowNotesRecursively**: `true`
**noteSubfoldersPanelShowRootFolderName**: `true`
**noteSubfoldersPanelSort**: `0`
**notesPanelOrder**: `0`
**notesPanelSort**: `1`
**notesPath**: `C:/Users/REPLACED_USERNAME/Documents/QOwnNotes/die Technologie`
**notifyAllExternalModifications**: `false`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: *empty*
**ownCloud/supportEnabled**: `false`
**ownCloud/todoCalendarBackend**: `3`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloud/userName**: *empty*
**ownCloudInfo/appIsValid**: `false`
**ownCloudInfo/connectionErrorMessage**: *empty*
**ownCloudInfo/notesPathExistsText**: *empty*
**ownCloudInfo/serverVersion**: *empty*
**previousWorkspace**: `4f9e23c3-0a4a-43a7-93d3-4d045b5249c5`
**recentNoteFolders**: `C:/Users/REPLACED_USERNAME/Documents/QOwnNotes/das Privatleben, C:/Users/REPLACED_USERNAME/Documents/QOwnNotes/die Anstellung, C:/Users/REPLACED_USERNAME/Documents/QOwnNotes, C:/Users/REPLACED_USERNAME/Documents/QOwnNotes/M, C:/Users/REPLACED_USERNAME/Documents/QOwnNotes/IMW know-how, C:/Users/REPLACED_USERNAME/Documents/QOwnNotes/Knowledge (common), C:/Users/REPLACED_USERNAME/Documents/QOwnNotes/Knowledge (Java), C:/Users/REPLACED_USERNAME/Documents/QOwnNotes/Knowledge (.NET)`
**restoreCursorPosition**: `true`
**savedSearches/noteFolder-1**: `Note 2018-08-28T13.36.39, Note 2018-08-14T15.05.45, Note 2018-08-14T12.15.55`
**savedSearches/noteFolder-10**: `Note 2018-09-10T22.46.08`
**savedSearches/noteFolder-8**: `soft, Note 2018-10-23T13.31.30, Note 2018-10-23T09.45.29, Note 2018-10-21T19.42.09, Note 2018-10-21T19.32.40, Note 2018-10-21T18.11.06, Note 2018-10-21T17.46.38, Note 2018-10-13T22.18.14, Note 2018-10-13T21.04.08, Note 2018-10-12T15.56.30, Note 2018-10-11T16.03.03, Note 2018-10-05T09.54.58, Note 2018-10-05T07.34.56, Note 2018-10-04T18.16.37, Note 2018-10-04T17.36.46, Note 2018-10-04T12.13.09, Note 2018-10-04T12.05.13, Note 2018-10-04T11.19.43, Note 2018-09-28T11.04.19, Note 2018-09-28T09.52.02, Note 2018-09-07T14.05.28, debu`
**savedSearches/noteFolder-9**: `Note 2018-09-13T11.41.56`
**showMenuBar**: `true`
**showStatusBar**: `true`
**skipVersion**: `18.10.4`
**taggingShowNotesRecursively**: `false`
**tagsPanelHideSearch**: `false`
**tagsPanelOrder**: `0`
**tagsPanelSort**: `0`
**toolbar/1/items**: `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name**: `mainToolBar`
**toolbar/1/title**: `main toolbar`
**toolbar/2/items**: `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name**: `formattingToolbar`
**toolbar/2/title**: `formatting toolbar`
**toolbar/3/items**: `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name**: `insertingToolbar`
**toolbar/3/title**: `inserting toolbar`
**toolbar/4/items**: `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name**: `encryptionToolbar`
**toolbar/4/title**: `encryption toolbar`
**toolbar/5/items**: `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name**: `windowToolbar`
**toolbar/5/title**: `window toolbar`
**toolbar/6/items**: `action_Quit`
**toolbar/6/name**: `quitToolbar`
**toolbar/6/title**: `quit toolbar`
**toolbar/size**: `6`
**useUNIXNewline**: `false`
**workspace-4f9e23c3-0a4a-43a7-93d3-4d045b5249c5/name**: `minimal`
**workspace-4f9e23c3-0a4a-43a7-93d3-4d045b5249c5/noteSubFolderDockWidgetVisible**: `true`
**workspace-4f9e23c3-0a4a-43a7-93d3-4d045b5249c5/windowState**: `<binary data>`
**workspace-d84f8904-80fd-4449-afb8-6dc33d737caf/name**: `full`
**workspace-d84f8904-80fd-4449-afb8-6dc33d737caf/noteSubFolderDockWidgetVisible**: `true`
**workspace-d84f8904-80fd-4449-afb8-6dc33d737caf/windowState**: `<binary data>`
**workspaces**: `d84f8904-80fd-4449-afb8-6dc33d737caf, 4f9e23c3-0a4a-43a7-93d3-4d045b5249c5`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\REPLACED_USERNAME\AppData\Roaming`
**CLASSPATH**: `C:\Program Files (x86)\IBM\RationalSDLC\ClearQuest\cqjni.jar`
**CLEARQUEST_HOME**: `C:\Program Files (x86)\IBM\RationalSDLC\ClearQuest`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `REPLACED_USERNAME-02`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DOCKER_API_VERSION**: `1.24`
**DOCKER_CERT_PATH**: `C:\Users\REPLACED_USERNAME\.docker\machine\`
**DOCKER_HOST**: `tcp://192.168.99.140:2376`
**DOCKER_TLS_VERIFY**: `1`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\REPLACED_USERNAME`
**IBMLDAP_ALTHOME**: `C:\Program Files (x86)\IBM\RationalSDLC\common\codeset`
**JAVA_HOME**: `C:\A_SOFT\jdk\jdk8u66_x64`
**JRE_HOME**: `C:\Program Files (x86)\IBM\RationalSDLC\Common\Java5.0\jre`
**LOCALAPPDATA**: `C:\Users\REPLACED_USERNAME\AppData\Local`
**LOGONSERVER**: `\\ZPL13DSDC801`
**NUMBER_OF_PROCESSORS**: `8`
**OneDrive**: `C:\Users\REPLACED_USERNAME\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\python_37\Scripts\;C:\python_37\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\IBM\RationalSDLC\common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\IBM\RationalSDLC\ClearCase\bin;C:\Program Files (x86)\IBM\gsk8\lib;C:\Program Files (x86)\IBM\gsk8\bin;C:\Program Files (x86)\IBM\RationalSDLC\ClearCase\RemoteClient\cteapis;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Git\mingw32\bin;C:\Program Files (x86)\Git\usr\bin;C:\A_SOFT\zookeeper-3.4.10.tar\zookeeper-3.4.10\bin;C:\Users\REPLACED_USERNAME\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\NuGet\;C:\Program Files\nodejs\;C:\Program Files\dotnet\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\GitExtensions\;C:\Users\REPLACED_USERNAME\AppData\Local\Microsoft\WindowsApps;C:\Users\REPLACED_USERNAME\AppData\Roaming\npm;C:\Users\REPLACED_USERNAME\AppData\Local\Programs\Microsoft VS Code\bin`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 158 Stepping 9, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `9e09`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\VMware\Infrastructure\PowerCLI\Modules`
**PUBLIC**: `C:\Users\Public`
**RATIONAL_COMMON**: `C:\Program Files (x86)\IBM\RationalSDLC\Common`
**RATIONAL_COMMON_LIB**: `C:\Program Files (x86)\IBM\RationalSDLC\Common\lib`
**RATIONAL_HOME**: `C:\Program Files (x86)\IBM\RationalSDLC`
**RATIONAL_ICU4J_DIR**: `C:\Program Files (x86)\IBM\RationalSDLC\common\java\icu;C:\Program Files (x86)\IBM\RationalSDLC\common\java\icu`
**RATIONAL_ICU4J_VERSION**: `4_8;4_8`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\REPLACED_USERNAME\AppData\Local\Temp`
**TISDIR**: `C:\Program Files (x86)\IBM\RationalSDLC\common`
**TMP**: `C:\Users\REPLACED_USERNAME\AppData\Local\Temp`
**USERDNSDOMAIN**: `DS.MOT.COM`
**USERDOMAIN**: `DS`
**USERDOMAIN_ROAMINGPROFILE**: `DS`
**USERNAME**: `REPLACED_USERNAME`
**USERPROFILE**: `C:\Users\REPLACED_USERNAME`
**VBOX_MSI_INSTALL_PATH**: `C:\Program Files\Oracle\VirtualBox\`
**VS140COMNTOOLS**: `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\`
**windir**: `C:\WINDOWS`
**WIX**: `C:\Program Files (x86)\WiX Toolset v3.11\`
**ZOOKEEPER_HOME**: `C:\A_SOFT\zookeeper-3.4.10.tar\zookeeper-3.4.10`

**Comment by pbek** [comment]
> I suppose it points to trash file named 30, but the file has 0 bytes in trash folder. I'm sure I didn't delete that note so it must have happened automatically.

trashing may also happens if your current note gets removed outside of QOwnNotes or if you rename your note (e.g. by renaming the headline of it)

> noteSaveIntervalTime: 10

...so the note should be saved every 10 sec (that's default)

> [0927/155608.964:ERROR:file_io_win.cc(243)] SetEndOfFile: The requested operation cannot be performed on a file with a user-mapped section open. (0x4C8)

I've never seen this before. I tried searching for that error on the internet and found a lot of hits but didn't find one "solution"...
Maybe your filesystem has some troubles?

**Comment by pbek** [comment]
ad note saving: note saving will also be logged to the log widget if you have turned on status message logging in that widget

**Comment by nosalan** [comment]
I didn't experience file system issues so far. Although there is Google Backup and Sync which is transferring notes files and scanning software: Symantec and Carbon Black.

After googling _"google backup and sync locking files"_ I found several reports that google sync process may take lock on files.

Would it be possible that QOwnNotes was not able to modify the file due to another process holding it and it failed silently?

**Comment by pbek** [comment]
> Would it be possible that QOwnNotes was not able to modify the file due to another process holding it and it failed silently?

failing, yes. silently, no. an error should be printed to the log widget. are you able to reproduce that issue with an other note?

**Comment by nosalan** [comment]
Logging widget? Do you mean Settings -> Debug -> Debug Options -> Enable logging to file ?
It was disabled, I just enabled it.

So if I had this disabled it means I couldn't know it failed to append to file?

I don't know how to reproduce the issue yet.

**Comment by pbek** [comment]
You'll find the logging panel in *Window / Panels*.

**Comment by pbek** [comment]
I will close this issue until there is more information.

**Comment by nosalan** [comment]
Note is gone when you rename it and new name only differs with casing, e.g. Angular -> AngulaR
Then restart the app - the note is gone

**Comment by pbek** [comment]
Sounds like https://github.com/pbek/QOwnNotes/issues/1190
