### ISSUE TITLE
Auto format table

### ISSUE THREAD

**Issue by codito** [pbek/QOwnNotes#1052]
Currently the text editor in QOwnNotes understands and marks the tables as `code`. This is an enhancement request to also auto format the table when user inputs a separator `|`.

Example: 
1. Assume given text as below
```
| header 1 | header 2 |
| content abc 
```
2. User inputs `|` after *abc*
3. Expected output - note how the `|` after *header 1* auto indented itself
```
| header 1    | header 2 |
| content abc |
```

This makes the content more readable.

Copied from issue at https://github.com/pbek/qmarkdowntextedit/issues/13

**Comment by pbek** [comment]
Thank you for your suggestion.

I'm still not sure if that should be done automatically, because it would eat a lot of resources to test if a table is present on every keystroke...

**Comment by pbek** [comment]
## 18.11.0
- you can now **auto format** spaces in a **markdown table** at the current cursor
  position with *Edit / Edit / Auto format table*
    - the auto complete shortcut <kbd>Ctrl</kbd> + <kbd>Space</kbd> also will
      attempt to auto-format the table

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by codito** [comment]
It works great!

The formatting goes to new line if one of the rows is longer. While I'd expect the rows are expanded to the longest one, observation is smaller rows just end up at left margin.

Example
```
| KOS Type | Inclusions |
| -- | -- |
| Thesaurus | Collection of Items in a selected Domain; can specify Attributes and Relations (Equivalence, Hierarchical, Associative, Contrast) |
```

Use auto format. Output (highlighted the misalignment in image):
```
| KOS Type  | Inclusions                                                                                                                        |
| --        | --                                                                                                                                |
| Thesaurus | Collection of Items in a selected Domain; can specify Attributes and Relations (Equivalence, Hierarchical, Associative, Contrast) |
```

![image](https://user-images.githubusercontent.com/28766/47953471-226d0200-dfa4-11e8-99d2-4f7380ba6cb2.png)

**Comment by pbek** [comment]
I guess you are misled by the soft-wrap feature in the Window menu, please try to turn it off, then the table row really should stay in one line.

**Comment by codito** [comment]
thanks, turning off soft-wrap, everything works as expected.

**Comment by sanderboom** [comment]
Whoohah! this is an amazing improvement, cheers!!

**Comment by pbek** [comment]
I'm happy you like it @sanderboom ;)

**Comment by pbek** [comment]
## 18.11.1
- the **auto formatter** of **markdown tables** is will now also to automatically
  increase the size of the headline separator

**Comment by sanderboom** [comment]
This was exactly my next question :yum: Nice man!

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by codito** [comment]
tested the latest bits, auto expansion of headline separator is working great!

**Comment by pbek** [comment]
Awesome! :)
