### ISSUE TITLE
External editor Can not opened when it have the same parent folder.

### ISSUE THREAD

**Issue by zaazbb** [pbek/QOwnNotes#1055]
I use ReText as the external editor.

when i install it in D:\work\repository\my\mynote, and QOwnNotes in this folder also. i can't open the external editor now. the config in QOwnNotes.ini as below:
```
externalEditorPath=../../ReTextPortable/ReTextPortable.exe
[FileDialog]
LastPath=D:/work/repository/my/mynote/ReTextPortable
LastPath-ExternalEditor=D:/work/repository/my/mynote/ReTextPortable
```

when i install it in C:/, everything is ok. now  the config in QOwnNotes.ini as below:
```
externalEditorPath=C:/ReTextPortable/ReTextPortable.exe
[FileDialog]
LastPath=C:/ReTextPortable
LastPath-ExternalEditor=C:/ReTextPortable
```

maybe the externalEditorPath config with relative path is incorrectly.

**Comment by pbek** [comment]
I'm sorry, the `externalEditorPath` only takes absolute paths. You could try to get around this with a qml script. See https://docs.qownnotes.org.

**Comment by pbek** [comment]
Since you didn't use the issue assistant I can only do wild guessing what you are up to...

**Comment by zaazbb** [comment]
the externalEditorPath config was generated by QOwnNotes, I can't control it use absolute path or relative path.

**Comment by pbek** [comment]
that's true

**Comment by zaazbb** [comment]
I select the right path in setting dialog, but it generate a relative path now.

**Comment by pbek** [comment]
Could you please use the issue assistant in the `Help` menu to post this issue so you can provide needed information more easily?

The menu entry is named `Post questions, feature requests or issues`.

**Comment by zaazbb** [comment]
sorry, i don't know how to use issue assistant.

if i edit QOwnNotes.ini  manually, change the externalEditorPath to absolute path, the external editor can open correctly.
```
externalEditorPath=D:/work/repository/my/mynote/ReTextPortable/ReTextPortable.exe
```

**Comment by pbek** [comment]
> sorry, i don't know how to use issue assistant.

how can I help you?

**Comment by pbek** [comment]
I will close this issue until there is more information.
