### ISSUE TITLE
Syntax highlighting support

### ISSUE THREAD

**Issue by Gazoo** [pbek/QOwnNotes#1057]
It would be nice if QOwnNotes could support language specific syntax highlighting for code blocks.

A PHP Example:
```
```php
<?php
// The "i" after the pattern delimiter indicates a case-insensitive search
if (preg_match("/php/i", "PHP is the web scripting language of choice.")) {
    echo "A match was found.";
} else {
    echo "A match was not found.";
}
?>
```
Would look like:
```php
<?php
// The "i" after the pattern delimiter indicates a case-insensitive search
if (preg_match("/php/i", "PHP is the web scripting language of choice.")) {
    echo "A match was found.";
} else {
    echo "A match was not found.";
}
?>
```
More information:
https://help.github.com/articles/creating-and-highlighting-code-blocks/

I think that most of the markdown editors that I've seen that support this are using codemirror to handle the syntax highlighting: https://codemirror.net/

**Comment by pbek** [comment]
I'm sorry, please see #1039 and other same questions.

**Comment by Gazoo** [comment]
Wouldn't this still be possible?
https://stackoverflow.com/questions/7451444/using-multiple-qsyntaxhighlighter-in-one-qplaintextedit

qsyntaxhighlighter
http://doc.qt.io/archives/qt-4.8/qsyntaxhighlighter.html

**Comment by pbek** [comment]
Yes, by writing syntax highlighter for every language and attempting to integrate them into code blocks. I guess that would be several month of work, any volunteers?

**Comment by pbek** [comment]
I'm not aware of any existing Qt library (even from KDE) that is able to do a QSyntaxHighligther in an other QSyntaxHighligther, but I really would love to have it.

**Comment by Gazoo** [comment]
Sorry I don't know that much about Qt. After a quick Google search the only other thing I found was this project: http://srchiliteqt.sourceforge.net/

Their example:
```
QTextEdit *editor = new QTextEdit;
srchiliteqt::Qt4SyntaxHighlighter *highlighter =
new srchiliteqt::Qt4SyntaxHighlighter(editor->document());
highlighter->init("java.lang");
```

Not sure if it would work for you though.

**Comment by pbek** [comment]
I played around with <https://markdown-it.github.io/markdown-it/> and <https://highlightjs.org/> in a qml script (like the one from `markdown-it` in the script repository) but had not much luck with it.

**Comment by Gazoo** [comment]
Did you try https://codemirror.net/ ? Take a look at the comments from @CapelliC where he interfaced CodeMirror in Qt WebView.

**Comment by Gazoo** [comment]
Sorry here is the link : https://stackoverflow.com/questions/16175811/qt5-html5applicationviewer-c-call

**Comment by pbek** [comment]
We don't have a Qt WebView...

**Comment by pbek** [comment]
But you can play around with https://github.com/qownnotes/scripts/tree/master/markdown-it. If you get a highlighter javascript running that would be great indeed.

**Comment by Gazoo** [comment]
Sorry I don't know anything about QT. Someone else would have to tackle this :(

**Comment by pbek** [comment]
The script is more about javascript... ;)

**Comment by pbek** [comment]
Meanwhile @Waqar144 did a lot for syntax highlighting.
