### ISSUE TITLE
Editor does not honor natural scrolling with mouse wheel

### ISSUE THREAD

**Issue by frankgerhardt** [pbek/QOwnNotes#1059]
#### Expected behaviour

I learned to love natural scrolling on macOS and configured my Debian 8 Mate desktop to do the same. 

`xmodmap -e "pointer = 1 2 3 5 4"`

The "wrong" way is like with roller blinds on a real window. You pull down and the blinds go up. Natural is you pull down and the content area of the editor moves down, not up. With a touch pad this is even more natural.

#### Actual behaviour

Scrolling goes in the wrong direction as if natural scrolling would not be enabled. 

#### Steps to reproduce

Move the mouse wheel (don't know about touch pad).

**Comment by pbek** [comment]
How scrolling is handled is foremost defined by your operating system and 2nd by Qt. If I move the mouse wheel it scrolls how I have set it up.

**Comment by frankgerhardt** [comment]
Right, most apps work correctly on my desktop, most importantly all the web browsers and the JetBrains tools. Some file managers work the wrong way. I used the word honor because I have made the setting and it works most of the time. QOwnNotes is just one of the exceptions. 

I found out about QOwnNotes only today and have been looking for such a tool. I used several other personal wiki tools with MANY files. I really like QOwnNotes, thank you!

**Comment by pbek** [comment]
Do other Qt 5 apps honor your settings? QOwnNotes has no special scrollbar handling other than Qt's.

> I really like QOwnNotes, thank you!

thank you :)

**Comment by pbek** [comment]
>  PCManFM https://en.wikipedia.org/wiki/PCMan_File_Manager however does and it is based on Qt.

are you really using the Qt version of it? it seems to be GTK+ by default

**Comment by frankgerhardt** [comment]
The About dialog says: Built on Nov 1 2018 with Qt 5.3.2.

**Comment by pbek** [comment]
Weird!

**Comment by pbek** [comment]
I will close this issue until there is more information.
