### ISSUE TITLE
Feature request: show note file/directory in file manager

### ISSUE THREAD

**Issue by praxiq** [pbek/QOwnNotes#106]
For those of us who don't use OwnCloud but store our files locally, and sometimes want to do something with the files outside of QOwnNotes, it'd be awesome if, when right-clicking on a note, there was a "Show in Finder/Explorer/Whatever" option that would navigate to that location in the OS-appropriate file manager.

**Comment by pbek** [comment]
Thank you for your suggestion, @praxiq! I'm not sure how to do that cross platform, but I will look into it. Currently there is a *open note in external editor* function and you can configure that editor in the settings.

**Comment by pbek** [comment]
In the current version 1.1.9:
- you can now show the current note in your file manager with a new menu item
    - use <kbd>Alt</kbd> + <kbd>⇧</kbd> + <kbd>F</kbd> as shortcut
    - under OS X the folder of the note is opened in Finder, but the note is 
      not selected

please be so kind and report back if it works for you
