### ISSUE TITLE
Search behaviour (Strg-F)

### ISSUE THREAD

**Issue by Reuce** [pbek/QOwnNotes#1061]
#### Expected behaviour
Pressing Strg+F. When entering a search string the first matched word should be found and the highlighted word should stay there. Only when a key is pressed that doesn't belong to the highlighted word, the next hit should be highlighted.
#### Actual behaviour
Pressing Strg+F. When entering a search string the highlighted word jumps to the next hit after every single added letter.
#### Steps to reproduce
You have a note that contains several "ThisIsADemoString". You enter Strg+F. You enter "T". This highlights the first "ThisIsADemoString". You enter "h". This highlights the second "ThisIsADemoString". You enter "i". The highlights the third "ThisIsADemoString". And so fourth. (Expected: The first "ThisIsADemoString" stays highlighted.)

**Comment by pbek** [comment]
Can you please fill out `Steps to reproduce`.

**Comment by pbek** [comment]
I'm sorry the `QPlainTextEdit::find` method does not allow much flexibility... Would be hard to get around this.
