### ISSUE TITLE
New line

### ISSUE THREAD

**Issue by subi54** [pbek/QOwnNotes#1062]
This is actually not an issue but more of a feature request. Apologies if it is in the wrong place.

Is it possible to have new lines as new lines without the double spacing? In bullets a new line can be added with `&nbsp;` or `<br>` probably.

**Comment by pbek** [comment]
Can you please explain in more detail and step by step what you did, what happened and what you expected.

**Comment by subi54** [comment]
There is no problem. It's more of a formatting thing.

When writing in markdown, for a new line two spaces are required, yes?
I was simply asking if there was a way to toggle for those who want to use a new line as a new line, without the two trailing spaces.

In a bullet list, you can use `&nbsp;` or `<br>` for new lines.

**Comment by pbek** [comment]
> When writing in markdown, for a new line two trailing spaces are required, yes?

yes, or a 2nd newline

> I was simply asking if there was a way to toggle for those who want to use a new line as a new line, without the two trailing spaces.

Are you talking about the preview? You could try the markdown-it preview from the script repository. Or press `Shift+ Return`.

**Comment by subi54** [comment]
Markdown-it preview doesn't use 2 trailing spaces?
I was under the impression that shift+enter added two spaces.

**Comment by pbek** [comment]
> Markdown-it preview doesn't use 2 trailing spaces?

I don't know, there are a lot of settings.

> I was under the impression that shift+enter added two spaces.

exactly

**Comment by pbek** [comment]
>  And thank you for all your hard work.

thank you! ;)

btw., `breaks:       true` is the markdown-it setting you are looking for
