### ISSUE TITLE
[I] panel layout test 

### ISSUE THREAD

**Issue by pihentagy** [pbek/QOwnNotes#1064]
When running `QOwnNotes --session panellayouttest --clear-settings` I got the following screen:
![image](https://user-images.githubusercontent.com/29916/48403845-22e96380-e72f-11e8-8b97-46c53627ecb0.png)

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Nov 13 10:29:45 2018`
**Version**: `18.11.2`
**Build date**: `Nov 12 2018`
**Build number**: `490`
**Platform**: `linux`
**Operating System**: `Linux Mint 19`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.9.5`
**Qt Version (runtime)**: `5.9.5`
**Portable mode**: `no`
**Settings path / key**: `/home/pihentagy/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/pihentagy/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `Mint-Y`
**Notes in current note folder**: `4`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `0`

### Note folder `default`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/pihentagy/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/pihentagy/Notes/notes.sqlite`

## Settings

**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `true`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-22da8ecb-98b6-4c7a-8231-5b3833d8e43f`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/vimMode** (bool): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2018-11-13T10:25:13`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Monospace,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Monospace,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Noto Sans,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteHistory-0** (QVariantList): `<variant list with 7 item(s)>`
**NoteHistoryCurrentIndex-0** (QString): `6`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowDifferentNoteFileName** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `false`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentWorkspace** (QString): `55ea34e7-c50e-4b58-930e-1f7db985cf97`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (bool): `true`
**dockWasInitializedOnce** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `true`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**insertTimeFormat** (QString): *empty*
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (int): `19`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `false`
**noteListPreview** (bool): `true`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/pihentagy/Notes`
**notifyAllExternalModifications** (bool): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): *empty*
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloud/userName** (QString): *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `82d5a242-ebaf-4bf2-b072-7dec36cd46f0`
**restoreCursorPosition** (bool): `true`
**savedSearches/noteFolder-0** (QString): `Note 2018-11-12T09.08.47`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useUNIXNewline** (bool): `false`
**workspace-55ea34e7-c50e-4b58-930e-1f7db985cf97/name** (QString): `minimal`
**workspace-55ea34e7-c50e-4b58-930e-1f7db985cf97/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-55ea34e7-c50e-4b58-930e-1f7db985cf97/windowState** (QByteArray): `<binary data>`
**workspace-82d5a242-ebaf-4bf2-b072-7dec36cd46f0/name** (QString): `preview only`
**workspace-82d5a242-ebaf-4bf2-b072-7dec36cd46f0/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-82d5a242-ebaf-4bf2-b072-7dec36cd46f0/windowState** (QByteArray): `<binary data>`
**workspace-92e58ed3-9d17-423b-a69e-526f553f8280/name** (QString): `full`
**workspace-92e58ed3-9d17-423b-a69e-526f553f8280/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-92e58ed3-9d17-423b-a69e-526f553f8280/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `92e58ed3-9d17-423b-a69e-526f553f8280, 55ea34e7-c50e-4b58-930e-1f7db985cf97, 82d5a242-ebaf-4bf2-b072-7dec36cd46f0`

## System environment

**J2SDKDIR**: `/usr/lib/jvm/java-8-oracle`
**USER**: `pihentagy`
**LANGUAGE**: `en_US`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `1199`
**J2REDIR**: `/usr/lib/jvm/java-8-oracle/jre`
**SHLVL**: `0`
**HOME**: `/home/pihentagy`
**DESKTOP_SESSION**: `cinnamon`
**GTK_MODULES**: `gail:atk-bridge`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**LC_MONETARY**: `hu_HU.UTF-8`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**MANDATORY_PATH**: `/usr/share/gconf/cinnamon.mandatory.path`
**QT_QPA_PLATFORMTHEME**: `qt5ct`
**LOGNAME**: `pihentagy`
**DEFAULTS_PATH**: `/usr/share/gconf/cinnamon.default.path`
**XDG_SESSION_ID**: `c1`
**PATH**: `/home/pihentagy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin`
**GDM_LANG**: `en_US`
**DERBY_HOME**: `/usr/lib/jvm/java-8-oracle/db`
**LC_ADDRESS**: `hu_HU.UTF-8`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**DISPLAY**: `:0`
**LANG**: `en_US.UTF-8`
**LC_TELEPHONE**: `hu_HU.UTF-8`
**XDG_SESSION_DESKTOP**: `cinnamon`
**XAUTHORITY**: `/home/pihentagy/.Xauthority`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/pihentagy`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**LC_NAME**: `hu_HU.UTF-8`
**SHELL**: `/bin/bash`
**QT_ACCESSIBILITY**: `1`
**GDMSESSION**: `cinnamon`
**LC_MEASUREMENT**: `hu_HU.UTF-8`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**LC_IDENTIFICATION**: `hu_HU.UTF-8`
**XDG_VTNR**: `7`
**JAVA_HOME**: `/usr/lib/jvm/java-8-oracle`
**PWD**: `/home/pihentagy`
**XDG_DATA_DIRS**: `/usr/share/cinnamon:/usr/share/gnome:/home/pihentagy/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-cinnamon:/etc/xdg`
**LC_NUMERIC**: `hu_HU.UTF-8`
**LC_PAPER**: `hu_HU.UTF-8`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**GTK_OVERLAY_SCROLLING**: `1`
**SESSION_MANAGER**: `local/thinkpad:@/tmp/.ICE-unix/1133,unix/thinkpad:/tmp/.ICE-unix/1133`
**XDG_CURRENT_DESKTOP**: `X-Cinnamon`

**Comment by pbek** [comment]
I can't produce this on other Linux distributions like KDE Neon or Manjaro (KDE). Did you also experience this with a previous release of QOwnNotes or is this your first install?

**Comment by pbek** [comment]
I now did a fresh Linux Mint 19 Cinnamon installation for testing.
This is what I get:

![virtualbox_linux mint_13_11_2018_11_13_15](https://user-images.githubusercontent.com/1798101/48406593-2f70ba80-e735-11e8-9b78-463fa401637d.png)

**Comment by pihentagy** [comment]
I've installed QOwnNotes before.

I just ran the command `QOwnNotes --session panellayouttest --clear-settings` to help test the new panellayouttest.

**Comment by pbek** [comment]
Strange. It maybe that your desktop environment is doing to the window. For me it forced it to be maximized once...

**Comment by pihentagy** [comment]
Sorry, `QT_SCALE_FACTOR` was set to `0.5`

**Comment by pbek** [comment]
That was enough for a nearly empty dialog?

**Comment by pihentagy** [comment]
Yes, after unsetting it, it displayed correctly. FYI this setting was to correct the scale for viber app.
