### ISSUE TITLE
[I] "Encrypt note" dialog has Cancel button inactive until you type matching passwords.

### ISSUE THREAD

**Issue by selivan** [pbek/QOwnNotes#1065]
#### Expected behaviour

In the "Encrypt node" dialog Cancel button should be always active.

#### Actual behaviour

In the "Encrypt node" dialog Cancel button becomes active only when user types matching passwords in both input fileds.

#### Steps to reproduce

Edit -> Encryption -> Encrypt node

#### Relevant log output in the Log panel

```

```

#### Information about the application, settings and environment

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed Nov 14 15:27:53 2018`
**Version**: `18.11.2`
**Build date**: `Nov 12 2018`
**Build number**: `490`
**Platform**: `linux`
**Operating System**: `Ubuntu 16.04.5 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AppImage`
**Qt Version (build)**: `5.6.2`
**Qt Version (runtime)**: `5.6.2`
**Portable mode**: `no`
**Settings path / key**: `/home/user/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/user/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `Adwaita`
**Notes in current note folder**: `5`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Script `New script`

**id**: `1`
**path**: *empty*
**variablesJson**: *empty*

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `25`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/ColorSchemes** (QString): `EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColorEnabled_-1** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColorEnabled_0** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColorEnabled_1** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColorEnabled_11** (QString): `false`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColorEnabled_12** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColorEnabled_13** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColorEnabled_14** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColorEnabled_15** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColorEnabled_16** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColorEnabled_17** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColorEnabled_18** (QString): `false`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColorEnabled_19** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColorEnabled_2** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColorEnabled_21** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColorEnabled_22** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColorEnabled_23** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColorEnabled_25** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColorEnabled_3** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColorEnabled_4** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColorEnabled_8** (QString): `false`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColor_-1** (QColor): `#ffffff`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColor_0** (QColor): `#fff8ef`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColor_1** (QColor): `#fff2e4`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColor_11** (QColor): `#aaf7ff`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColor_12** (QColor): `#f1f1f4`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColor_13** (QColor): `#f1f1f4`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColor_14** (QColor): `#f1f1f4`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColor_15** (QColor): `#f1f1f4`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColor_16** (QColor): `#f1f1f4`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColor_17** (QColor): `#f1f1f4`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColor_18** (QColor): `#f5f9d8`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColor_19** (QColor): `#e2e7e2`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColor_2** (QColor): `#fff2e4`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColor_21** (QColor): `#ebebeb`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColor_22** (QColor): `#f7f6ff`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColor_23** (QColor): `#eaebea`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColor_25** (QColor): `#fffae2`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColor_3** (QColor): `#edffed`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColor_4** (QColor): `#eaebea`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/BackgroundColor_8** (QColor): `#dbf9e5`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/Bold_12** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/Bold_13** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/Bold_14** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/Bold_15** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/Bold_16** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/Bold_17** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/Bold_8** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/FontSizeAdaption_12** (QString): `200`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/FontSizeAdaption_13** (QString): `160`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/FontSizeAdaption_14** (QString): `130`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/FontSizeAdaption_15** (QString): `100`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/FontSizeAdaption_16** (QString): `90`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/FontSizeAdaption_17** (QString): `90`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/FontSizeAdaption_8** (QString): `100`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_-1** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_0** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_1** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_10** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_11** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_12** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_13** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_14** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_15** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_16** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_17** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_18** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_19** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_2** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_20** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_21** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_22** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_23** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_24** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_26** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_3** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_4** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_5** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_6** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_7** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_8** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColorEnabled_9** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_-1** (QColor): `#000000`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_0** (QColor): `#fc7e00`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_1** (QColor): `#fc7e00`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_10** (QColor): `#a3007b`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_11** (QColor): `#ababab`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_12** (QColor): `#00316e`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_13** (QColor): `#00316e`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_14** (QColor): `#00316e`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_15** (QColor): `#00316e`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_16** (QColor): `#00316e`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_17** (QColor): `#00316e`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_18** (QColor): `#aa0000`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_19** (QColor): `#008000`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_2** (QColor): `#fc7e00`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_20** (QColor): `#3d3d3d`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_21** (QColor): `#393939`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_22** (QColor): `#4e18b9`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_23** (QColor): `#008000`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_24** (QColor): `#cccccc`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_26** (QColor): `#ff5500`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_3** (QColor): `#00bf00`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_4** (QColor): `#008000`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_5** (QColor): `#3d3d3d`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_6** (QColor): `#3d3d3d`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_7** (QColor): `#0057ae`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_8** (QColor): `#00428a`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/ForegroundColor_9** (QColor): `#a3007b`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/Italic_7** (QString): `true`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/Name** (QString): `Light - my`
**EditorColorSchema-5f413842-cc41-495e-91c3-ba25d924a8fb/Underline_26** (QString): `true`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2018-11-14T15:23:42`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `it`
**MainWindow/noteTextEdit.code.font** (QString): `Monospace,14,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Ubuntu,14,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Monospace,14,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Ubuntu,14,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/local-trash-notes-removed** (QString): `1024`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteHistory-1** (QVariantList): `<variant list with 10 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `9`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `true`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**insertTimeFormat** (QString): *empty*
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `19`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `0`
**newNoteAskHeadline** (QString): `true`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/user/test/qownnotes`
**notifyAllExternalModifications** (QString): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): *empty*
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloud/userName** (QString): *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `rsync-example-config, rsync3, rsync2, rsync, Note 2018-11-13T21.45.11, Note 2018-11-13T21.44.45`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useUNIXNewline** (QString): `false`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**XDG_VTNR**: `7`
**LC_PAPER**: `en_US.UTF-8`
**LC_ADDRESS**: `en_US.UTF-8`
**XDG_SESSION_ID**: `c4`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/user`
**LC_MONETARY**: `en_US.UTF-8`
**CLUTTER_IM_MODULE**: `xim`
**SESSION**: `ubuntu`
**TERM**: `xterm-256color`
**VTE_VERSION**: `4205`
**XDG_MENU_PREFIX**: `gnome-`
**SHELL**: `/bin/bash`
**QT_LINUX_ACCESSIBILITY_ALWAYS_ON**: `1`
**WINDOWID**: `81788938`
**LC_NUMERIC**: `en_US.UTF-8`
**OLDPWD**: `/home/user/`
**UPSTART_SESSION**: `unix:abstract=/com/ubuntu/upstart-session/1000/16120`
**GNOME_KEYRING_CONTROL**: *empty*
**GTK_MODULES**: `gail:atk-bridge:unity-gtk-module`
**USER**: `user`
**QT_ACCESSIBILITY**: `1`
**LC_TELEPHONE**: `en_US.UTF-8`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**UNITY_HAS_3D_SUPPORT**: `true`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**SESSION_MANAGER**: `local/note:@/tmp/.ICE-unix/16413,unix/note:/tmp/.ICE-unix/16413`
**DEFAULTS_PATH**: `/usr/share/gconf/ubuntu.default.path`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg`
**UNITY_DEFAULT_PROFILE**: `unity`
**DESKTOP_SESSION**: `ubuntu`
**PATH**: `/tmp/.mount_QOwnNotUOLAD/usr/bin/:/tmp/.mount_QOwnNotUOLAD/usr/sbin/:/tmp/.mount_QOwnNotUOLAD/usr/games/:/tmp/.mount_QOwnNotUOLAD/bin/:/tmp/.mount_QOwnNotUOLAD/sbin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
**QT_IM_MODULE**: `ibus`
**QT_QPA_PLATFORMTHEME**: `appmenu-qt5`
**LC_IDENTIFICATION**: `en_US.UTF-8`
**XDG_SESSION_TYPE**: `x11`
**PWD**: `/home/user/distr`
**JOB**: `unity-settings-daemon`
**XMODIFIERS**: `@im=none`
**EDITOR**: `vim`
**GNOME_KEYRING_PID**: *empty*
**LANG**: `en_US.UTF-8`
**GDM_LANG**: `en`
**MANDATORY_PATH**: `/usr/share/gconf/ubuntu.mandatory.path`
**LC_MEASUREMENT**: `en_US.UTF-8`
**COMPIZ_CONFIG_PROFILE**: `ubuntu`
**IM_CONFIG_PHASE**: `1`
**PS1**: `\[\e[01;32m\]\u\[\e[0m\]@\[\e[01;32m\]\h\[\e[0m\]:\[\e[1;34m\]\w\[\e[0m\]$ `
**PAPERSIZE**: `letter`
**GDMSESSION**: `ubuntu`
**SESSIONTYPE**: `gnome-session`
**GTK2_MODULES**: `overlay-scrollbar`
**SHLVL**: `1`
**HOME**: `/home/user`
**XDG_SEAT**: `seat0`
**LANGUAGE**: `en`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**UPSTART_INSTANCE**: *empty*
**UPSTART_EVENTS**: `xsession started`
**XDG_SESSION_DESKTOP**: `ubuntu`
**LOGNAME**: `user`
**COMPIZ_BIN_PATH**: `/usr/bin/`
**DBUS_SESSION_BUS_ADDRESS**: `unix:abstract=/tmp/dbus-yzBhkTlelF`
**XDG_DATA_DIRS**: `/tmp/.mount_QOwnNotUOLAD/usr/share/:/usr/share/ubuntu:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop`
**QT4_IM_MODULE**: `xim`
**INSTANCE**: *empty*
**UPSTART_JOB**: `unity7`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**DISPLAY**: `:0`
**XDG_CURRENT_DESKTOP**: `Unity`
**GTK_IM_MODULE**: `xim`
**LESSCLOSE**: `/usr/bin/lesspipe %s %s`
**LC_TIME**: `en_US.UTF-8`
**LC_NAME**: `en_US.UTF-8`
**XAUTHORITY**: `/home/user/.Xauthority`
**_**: `./QOwnNotes-1542051463.b9fc9164-Build1.1.glibc2.14-x86_64.AppImage`
**APPIMAGE**: `/home/user/distr/QOwnNotes-1542051463.b9fc9164-Build1.1.glibc2.14-x86_64.AppImage`
**ARGV0**: `./QOwnNotes-1542051463.b9fc9164-Build1.1.glibc2.14-x86_64.AppImage`
**APPDIR**: `/tmp/.mount_QOwnNotUOLAD`
**OWD**: `/home/user/distr`
**PYTHONHOME**: `/tmp/.mount_QOwnNotUOLAD/usr/`
**LD_LIBRARY_PATH**: `/tmp/.mount_QOwnNotUOLAD/usr/lib/:/tmp/.mount_QOwnNotUOLAD/usr/lib/i386-linux-gnu/:/tmp/.mount_QOwnNotUOLAD/usr/lib/x86_64-linux-gnu/:/tmp/.mount_QOwnNotUOLAD/usr/lib32/:/tmp/.mount_QOwnNotUOLAD/usr/lib64/:/tmp/.mount_QOwnNotUOLAD/lib/:/tmp/.mount_QOwnNotUOLAD/lib/i386-linux-gnu/:/tmp/.mount_QOwnNotUOLAD/lib/x86_64-linux-gnu/:/tmp/.mount_QOwnNotUOLAD/lib32/:/tmp/.mount_QOwnNotUOLAD/lib64/:`
**PYTHONPATH**: `/tmp/.mount_QOwnNotUOLAD/usr/share/pyshared/:`
**PERLLIB**: `/tmp/.mount_QOwnNotUOLAD/usr/share/perl5/:/tmp/.mount_QOwnNotUOLAD/usr/lib/perl5/:`
**GSETTINGS_SCHEMA_DIR**: `/tmp/.mount_QOwnNotUOLAD/usr/share/glib-2.0/schemas/:`
**QT_PLUGIN_PATH**: `/tmp/.mount_QOwnNotUOLAD/usr/lib/qt4/plugins/:/tmp/.mount_QOwnNotUOLAD/usr/lib/i386-linux-gnu/qt4/plugins/:/tmp/.mount_QOwnNotUOLAD/usr/lib/x86_64-linux-gnu/qt4/plugins/:/tmp/.mount_QOwnNotUOLAD/usr/lib32/qt4/plugins/:/tmp/.mount_QOwnNotUOLAD/usr/lib64/qt4/plugins/:/tmp/.mount_QOwnNotUOLAD/usr/lib/qt5/plugins/:/tmp/.mount_QOwnNotUOLAD/usr/lib/i386-linux-gnu/qt5/plugins/:/tmp/.mount_QOwnNotUOLAD/usr/lib/x86_64-linux-gnu/qt5/plugins/:/tmp/.mount_QOwnNotUOLAD/usr/lib32/qt5/plugins/:/tmp/.mount_QOwnNotUOLAD/usr/lib64/qt5/plugins/:`
**PYTHONDONTWRITEBYTECODE**: `1`

**Comment by pbek** [comment]
Thank you for reporting.

**Comment by pbek** [comment]
## 18.11.3
- the `Cancel` button of the note encryption password dialog is now always enabled

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by selivan** [comment]
Yep, it's fixed :+1:

**Comment by pbek** [comment]
Great, thank you for testing!
