### ISSUE TITLE
note search panel - add option to change key to create new note

### ISSUE THREAD

**Issue by kiuuik** [pbek/QOwnNotes#1066]
I hope I didn't miss a built-in feature (or another issue during my search) ...

In the note search panel if I enter a string that doesn't match an existing note name a new note is created. This is great for users of NVAlt but not for me: From search engines, database interfaces and my desktop search engine (recoll) I'm accustomed to press enter to trigger a search: I more or less automatically press "enter" so that I regularly have to delete new notes I accidentally created (also when I mistype). For me it would be nice if a new note would only be created with "ctrl+enter". It would be great if there were an option to configure this behavior. 

Thanks for this great piece of software!

P.S.: The  panel layout selector in the welcome dialogue for 18.11.3 works for me (though I only tested two layouts in linux mint 19 with the most recent appimage). That's a very useful feature.

**Comment by pbek** [comment]
Can you please explain step by step what you did, what happened and what you expected (like suggested in the issue template). It's easier to read and less prone to misunderstandings. 😬

**Comment by kiuuik** [comment]
This is a feature request. 

#### Steps to reproduce
1. click/focus on the "Note search panel"
2. enter a string that doesn't match an existing file (more precise: a file name without extension) in the  note folder path. Now the "Note list panel" will be empty.
3. Press Enter 

#### Actual behaviour
Result: new note is created with the filename "string I entered under Nr. 2" + ".md".

#### Expected behaviour
Result: nothing happens. 

(A new note note is only created if I press "Ctrl+Enter")

#### Motivation/Reasoning
In many other contexts where you enter a string into a line to search something "Enter" just starts the search. So after I type in some characters I more or less automatically press "enter". At the moment this means that I regularly have to delete new notes I accidentally created. I run into the same problem when I mistype. For me it would be nice if a new note would only be created if I press an additional modifier key. It would be great if there were an option to configure this behaviour.


#### Output from the debug section in the settings dialog
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fri Nov 16 12:20:50 2018`
**Version**: `18.11.3`
**Build date**: `Nov 14 2018`
**Build number**: `491`
**Platform**: `linux`
**Operating System**: `Linux Mint 19`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AppImage`
**Qt Version (build)**: `5.6.2`
**Qt Version (runtime)**: `5.6.2`
**Portable mode**: `no`
**Settings path / key**: `/home/kiuuik/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/kiuuik/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `Adwaita`
**Notes in current note folder**: `6`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/kiuuik/Nextcloud/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/kiuuik/Nextcloud/Notes/notes.sqlite`

## Enabled scripts

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2018-11-16T12:08:49`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Noto Sans,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 6 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `5`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `true`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**externalEditorPath** (QString): `/usr/bin/emacs`
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**insertTimeFormat** (QString): *empty*
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `19`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/kiuuik/Nextcloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): *empty*
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `2`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloud/userName** (QString): *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `sdf, six, four, three, two, one, eatere, cheater`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useUNIXNewline** (QString): `false`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**USER**: `kiuuik`
**LANGUAGE**: `en_US`
**XDG_SEAT**: `seat0`
**COMPIZ_CONFIG_PROFILE**: `mate`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `1489`
**SHLVL**: `0`
**HOME**: `/home/kiuuik`
**DESKTOP_SESSION**: `mate`
**GTK_MODULES**: `gail:atk-bridge`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**LC_MONETARY**: `de_DE.UTF-8`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**MANDATORY_PATH**: `/usr/share/gconf/mate.mandatory.path`
**QT_QPA_PLATFORMTHEME**: `qt5ct`
**LOGNAME**: `kiuuik`
**DEFAULTS_PATH**: `/usr/share/gconf/mate.default.path`
**XDG_SESSION_ID**: `c1`
**CLUTTER_BACKEND**: `x11`
**PATH**: `/tmp/.mount_QOwnNoQT26Qy/usr/bin/:/tmp/.mount_QOwnNoQT26Qy/usr/sbin/:/tmp/.mount_QOwnNoQT26Qy/usr/games/:/tmp/.mount_QOwnNoQT26Qy/bin/:/tmp/.mount_QOwnNoQT26Qy/sbin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`
**GDM_LANG**: `en_US`
**LC_ADDRESS**: `de_DE.UTF-8`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**DISPLAY**: `:0`
**LANG**: `en_US.UTF-8`
**XDG_CURRENT_DESKTOP**: `MATE`
**LC_TELEPHONE**: `de_DE.UTF-8`
**XDG_SESSION_DESKTOP**: `mate`
**XAUTHORITY**: `/home/kiuuik/.Xauthority`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/kiuuik`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**LC_NAME**: `de_DE.UTF-8`
**SHELL**: `/bin/bash`
**QT_ACCESSIBILITY**: `1`
**GDMSESSION**: `mate`
**LC_MEASUREMENT**: `de_DE.UTF-8`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**LC_IDENTIFICATION**: `de_DE.UTF-8`
**XDG_VTNR**: `7`
**PWD**: `/home/kiuuik`
**XDG_DATA_DIRS**: `/tmp/.mount_QOwnNoQT26Qy/usr/share/:/usr/share/mate:/home/kiuuik/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-mate:/etc/xdg`
**LC_NUMERIC**: `de_DE.UTF-8`
**LC_PAPER**: `de_DE.UTF-8`
**MATE_DESKTOP_SESSION_ID**: `this-is-deprecated`
**SESSION_MANAGER**: `local/kiuuikkiuuik:@/tmp/.ICE-unix/1127,unix/kiuuikkiuuik:/tmp/.ICE-unix/1127`
**GTK_OVERLAY_SCROLLING**: `0`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**QT_SCALE_FACTOR**: `1`
**INSIDE_CAJA_PYTHON**: *empty*
**APPIMAGE**: `/home/kiuuik/Downloads/QOwnNotes-1542211924.8aab8a5f-Build1.1.glibc2.14-x86_64.AppImage`
**ARGV0**: `/home/kiuuik/Downloads/QOwnNotes-1542211924.8aab8a5f-Build1.1.glibc2.14-x86_64.AppImage`
**APPDIR**: `/tmp/.mount_QOwnNoQT26Qy`
**OWD**: `/home/kiuuik/Downloads`
**PYTHONHOME**: `/tmp/.mount_QOwnNoQT26Qy/usr/`
**LD_LIBRARY_PATH**: `/tmp/.mount_QOwnNoQT26Qy/usr/lib/:/tmp/.mount_QOwnNoQT26Qy/usr/lib/i386-linux-gnu/:/tmp/.mount_QOwnNoQT26Qy/usr/lib/x86_64-linux-gnu/:/tmp/.mount_QOwnNoQT26Qy/usr/lib32/:/tmp/.mount_QOwnNoQT26Qy/usr/lib64/:/tmp/.mount_QOwnNoQT26Qy/lib/:/tmp/.mount_QOwnNoQT26Qy/lib/i386-linux-gnu/:/tmp/.mount_QOwnNoQT26Qy/lib/x86_64-linux-gnu/:/tmp/.mount_QOwnNoQT26Qy/lib32/:/tmp/.mount_QOwnNoQT26Qy/lib64/:`
**PYTHONPATH**: `/tmp/.mount_QOwnNoQT26Qy/usr/share/pyshared/:`
**PERLLIB**: `/tmp/.mount_QOwnNoQT26Qy/usr/share/perl5/:/tmp/.mount_QOwnNoQT26Qy/usr/lib/perl5/:`
**GSETTINGS_SCHEMA_DIR**: `/tmp/.mount_QOwnNoQT26Qy/usr/share/glib-2.0/schemas/:`
**QT_PLUGIN_PATH**: `/tmp/.mount_QOwnNoQT26Qy/usr/lib/qt4/plugins/:/tmp/.mount_QOwnNoQT26Qy/usr/lib/i386-linux-gnu/qt4/plugins/:/tmp/.mount_QOwnNoQT26Qy/usr/lib/x86_64-linux-gnu/qt4/plugins/:/tmp/.mount_QOwnNoQT26Qy/usr/lib32/qt4/plugins/:/tmp/.mount_QOwnNoQT26Qy/usr/lib64/qt4/plugins/:/tmp/.mount_QOwnNoQT26Qy/usr/lib/qt5/plugins/:/tmp/.mount_QOwnNoQT26Qy/usr/lib/i386-linux-gnu/qt5/plugins/:/tmp/.mount_QOwnNoQT26Qy/usr/lib/x86_64-linux-gnu/qt5/plugins/:/tmp/.mount_QOwnNoQT26Qy/usr/lib32/qt5/plugins/:/tmp/.mount_QOwnNoQT26Qy/usr/lib64/qt5/plugins/:`
**PYTHONDONTWRITEBYTECODE**: `1`

#### Relevant log output in the Log panel

[12:58:40] [status] Stored 1 note(s) to disk

or

[12:58:56] [status] Stored current note to disk

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
Qt's method `MainWindow::on_searchLineEdit_returnPressed()` also triggers on the shift-key. I would need to rewrite a lot of stuff...

**Comment by kiuuik** [comment]
Obviously this "issue" is not important. I hoped that it's a quick fix that you liked. I was wrong ... Thanks for your time researching this issue (and again for this software in general).

**Comment by pbek** [comment]
Thank you @kiuuik.
I'd rather close this ticket then.
