### ISSUE TITLE
Feature request: Secure, portable encryption

### ISSUE THREAD

**Issue by praxiq** [pbek/QOwnNotes#107]
Being able to encrypt notes is a pretty cool feature. As I understand it, the "Encrypt note" command uses [SimpleCrypt](https://wiki.qt.io/Simple_encryption_with_SimpleCrypt) - is that correct?

There are two main problems with this approach:

- SimpleCrypt does *not* provide strong encryption! In fact, reading their description of the algorithm, it hardly qualifies as encryption at all, by the modern, commonly-used definition of the word. "Obfuscation" might be a better description of what it's doing - if the algorithm hasn't been cracked yet, it's only because there's no incentive, because nobody is using it for anything truly sensitive :)
- The other issue is that if for some reason, at some point in the future, I don't have QOwnNote on my computer, I won't be able to decrypt my notes anymore.

Off the top of my head, I can think of one very easy-to-use, simple, secure, cross-platform file format - encrypted zip files! What if, instead of using SimpleCrypt, the Encrypt Note command created a password-protected zip file. That zip might be put in the media folder, and the contents of the note replaced with the URL of the zip. Not only is this more secure (The zip spec includes AES encryption), but every Mac and Windows system (and probably just about every *nix system as well) already comes with the tools to decrypt these files, making it possible to recover your data even without access to QOwnNotes.

**Comment by pbek** [comment]
Thank you for your suggestion, @praxiq! You are right about SimpleCrypt. It's not using a strong encryption. We need something that can be integrated into Qt (a Qt library would be *very* handy, ideally without crazy dependencies) and works cross platform.
Do you have any suggestions?
My next best choice would be to put it in the hands of the users and add two lines in the settings, one for a command to decrypt, one for encryption. The user could then setup and use GPG by hin/herself.
What do you think?

**Comment by praxiq** [comment]
I don't see an easy library to handle any of the encrypted zip formats. Offloading the work to a command-line tool makes sense - GPG could work. 7zip is a bit more user-friendly, especially for windows/mac and gui users. (The basic "zip" command-line tool has encryption, but I don't think it's very secure.)

**Comment by pbek** [comment]
So I guess, unless someone else has a great idea which Qt library to use we'll stick with a configurable, external tool.

**Comment by Letterus** [comment]
As far as I know NaCl is a secure encryption solution providing a C++ interface. Even though it is not a Qt library: https://nacl.cr.yp.to/

**Comment by pbek** [comment]
Thank you for your suggestion, @Letterus!
Hm, the latest version is five years old and I can't find a license agreement...
The package has quite some files and they say: `NaCl works on a wide variety of UNIX-like systems, including Linux, BSD, Solaris, etc. `... Nothing about OS X and Windows. :)

I have to investigate more...

**Comment by Letterus** [comment]
I think it should work on OS X, but I'm unsure of Windows. libsodium seems to fill this gap as a newer piece of software - but I have no information about its cryptographic quality: https://github.com/jedisct1/libsodium

**Comment by Letterus** [comment]
But, to be true: What I'd like the most would be a solution compatible with a JS crypto lib. That way it would be possible to develop a JS client, booted from an ownCloud app, which could handle the encrypted notes within a browser and thus giving nice app-independend end-to-end-encryption.

**Comment by pbek** [comment]
Are the two compatible? That would be awesome. So far I haven't found out if you can encrypt a string just with a password...

**Comment by Letterus** [comment]
Seems to be so. API wise you might compare https://download.libsodium.org/doc/secret-key_cryptography/authenticated_encryption.html
and
https://github.com/jedisct1/libsodium.js/blob/master/wrapper/symbols/crypto_secretbox_easy.json

**Comment by pbek** [comment]
As long as we can use the note to store the encrypted text and the user only needs to remember a password it should be ok.

**Comment by Letterus** [comment]
"The crypto_secretbox_open_easy() function verifies and decrypts a ciphertext produced by crypto_secretbox_easy()." Those two functions should do it.

**Comment by pbek** [comment]
So far I don't even remotely get it to work with QOwnNotes... :/

**Comment by Letterus** [comment]
What do you mean by "remotely"?

**Comment by pbek** [comment]
that I failed on many levels... so I wanted to try QCA (and its ng fork), that both are terribly unmaintained and I fear even if I get it QCA to work on every platform in QOwnNotes (it has a lot of dependencies) it will increase the double of QOwnNotes.

**Comment by pbek** [comment]
If anyone knows a small Qt C++ library I'm all ears...

**Comment by Letterus** [comment]
Maybe http://botan.randombit.net/manual/cryptobox.html would work? It is used by Kullo.net for their Qt application.

**Comment by pbek** [comment]
Do they have a C++ Qt client on <https://github.com/kullo>?

**Comment by Letterus** [comment]
At least partly as their libkullo. See https://github.com/kullo/client-libkullo/blob/master/kulloclient/crypto/symmetriccryptor.cpp

But I don't think their rather complex private-/public-key encryption is what you need. But maybe it helps for implementing the Botan lib. But I think using the cryptobox function is an easier solution than using the "Pipe and Filter" API.

**Comment by pbek** [comment]
This might even be a better lead: <https://github.com/qtproject/qt-creator/tree/master/src/libs/3rdparty/botan>

**Comment by pbek** [comment]
The question remains if there is a js/php library to de- and encrypt that is compatible with botan's way of doing it (and which encryption from botan to use in the first place)... (I don't know if libsodium.js can do that)

**Comment by Letterus** [comment]
Would be nice to have a crypto expert who could say if AES-256 or something would be the way to go. Then it would be easily testable.

**Comment by pbek** [comment]
I was working with Botan the last days and was able integrate it into QOwnNotes. I will attempt to integrate AES-256 encryption for notes today.

**Comment by pbek** [comment]
After a lot of integration work and re-writing some major stuff I have botan now integrated into QOwnNotes and am using AES-256 encryption for the notes.
@praxiq and @Letterus can you please test the current version 1.2.1 and tell me if you run into problems...

**Comment by Letterus** [comment]
Works well! Thank you very much.

Only two things behave not the way I would expect:
1. When I encrypt a note or leave the "edit" mode of an encrypted note (edit view shows the encrypted note) I still can see the content of the note when I switch to the markdown view. I would expect that all unencrypted contents of the notes are removed from RAM and app views when I encrypt it.
2. When I edit an encrypted note and switch to the markdown view and then back to the edit view I only see the encrypted note. I would expect to stay in the "edit" mode and see the unencrypted text until I switch to another note or leave the edit mode explicitly.

**Comment by pbek** [comment]
Thank you for your review, @Letterus!

1. As long as the password is cached (10min) you are able to see the decrypted note in the markdown view.
2. I'm not sure yet if I think that's a good idea...

**Comment by Letterus** [comment]
Ok, I did not know about the caching behaviour. For me as user it would be more transparent if I could influence the time when to forget the password by myself.

**Comment by pbek** [comment]
Maybe there will be a setting for that some point of time. :grin:

**Comment by Letterus** [comment]
You implemented this feature before Apple did with their Notes app: https://support.apple.com/de-de/HT205750
;-)

**Comment by pbek** [comment]
Hahaha, that's called foresight :)
