### ISSUE TITLE
[F] Issue Submission Typo

### ISSUE THREAD

**Issue by zorglups** [pbek/QOwnNotes#1075]
If you don't want most spell checkers to choke on your automated issue submission, I suggest to change:
#### Actual behaviour

To:
#### Actual behavior

:-)

**Comment by pbek** [comment]
One is British English, the other is American English.

**Comment by pbek** [comment]
Google Chrome doesn't complain about it.

**Comment by zorglups** [comment]
Probably a regional thing.
My Chrome installation underline behaviour in curly red.

![image](https://user-images.githubusercontent.com/7338241/48767980-44f75e80-ecb8-11e8-93ad-8de6fe0d24ea.png)

I guess you can just ignore this ;-)

**Comment by pbek** [comment]
Nextcloud also uses the british word:
https://github.com/nextcloud/server/issues/new

And it is used in the source code quite a lot. So I will stay with it.
