### ISSUE TITLE
[I] Task list not working with Davical

### ISSUE THREAD

**Issue by Glandos** [pbek/QOwnNotes#1078]
#### Expected behaviour

I should be able to list task from a Davical instance

#### Actual behaviour

The refresh task list does not complete

#### Steps to reproduce

Configure "other caldav server" with the URI of your davical server

#### Relevant log output in the Log panel

```
[22:17:49] [status] 1 note enregistrée sur le disque
```

#### Information about the application, settings and environment

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `lun. nov. 26 22:18:12 2018`
**Version**: `18.11.6`
**Build date**: `Nov 23 2018`
**Build number**: `494`
**Platform**: `linux`
**Operating System**: `Debian GNU/Linux buster/sid`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.7.1`
**Qt Version (runtime)**: `5.11.2`
**Portable mode**: `no`
**Settings path / key**: `/home/user/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/user/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `fr_FR`
**Locale (interface)**: *empty*
**Icon theme**: `Adwaita`
**Notes in current note folder**: `3`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `14.0.4.2`
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `par défaut`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/user/Documents/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/user/Documents/Notes/notes.sqlite`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/vimMode** (bool): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2018-11-26T21:57:17.672`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**NoteHistory-1** (QVariantList): `<variant list with 5 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `4`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (int): `2`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Main calendar`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowDifferentNoteFileName** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (bool): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (bool): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**dockWasInitializedOnce** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (int): `17`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/user/Documents/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/ignoreNonTodoCalendars** (bool): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): *empty*
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (int): `2`
**ownCloud/todoCalendarCalDAVPassword** (QString): ``
**ownCloud/todoCalendarCalDAVServerUrl** (QString): `https://caldav.example.com/caldav.php/user/home/`
**ownCloud/todoCalendarCalDAVUsername** (QString): `user`
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Main calendar`
**ownCloud/todoCalendarEnabledList** (QStringList): `Main calendar`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://caldav.example.com/caldav.php/user/home/`
**ownCloud/todoCalendarUrlList** (QStringList): `https://caldav.example.com/caldav.php/user/home/`
**ownCloud/userName** (QString): *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Erreur inconnue`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `14.0.4.2`
**restoreCursorPosition** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `barre d'outils principale`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `barre d'outils de formatage`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `barre d'outils d'insertion`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `barre d'outils de chiffrement`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `barre d'outils de fenêtre`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quitter la barre d’outils`
**toolbar/size** (int): `6`
**useUNIXNewline** (bool): `false`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**COLORTERM**: `truecolor`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**DESKTOP_SESSION**: `xfce`
**DISPLAY**: `:0.0`
**ENABLE_D_LOG**: `0`
**ENABLE_SL_LOG**: `0`
**GDMSESSION**: `xfce`
**GLADE_CATALOG_PATH**: `:`
**GLADE_MODULE_PATH**: `:`
**GLADE_PIXMAP_PATH**: `:`
**HOME**: `/home/user`
**LANG**: `fr_FR.utf8`
**LOGNAME**: `user`
**PATH**: `/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`
**PWD**: `/home/user`
**QT_ACCESSIBILITY**: `1`
**SESSION_MANAGER**: `local/complexe:@/tmp/.ICE-unix/845,unix/complexe:/tmp/.ICE-unix/845`
**SHELL**: `/usr/bin/fish`
**SHLVL**: `1`
**SSH_AGENT_PID**: `835`
**SSH_AUTH_SOCK**: `/tmp/ssh-pVEwOARLjkFD/agent.800`
**TERM**: `xterm-256color`
**TILIX_ID**: `0b0f39b6-6c33-47e5-b838-744f99386d35`
**USER**: `user`
**VTE_VERSION**: `5402`
**XAUTHORITY**: `/home/user/.Xauthority`
**XDG_CONFIG_DIRS**: `/etc/xdg`
**XDG_CURRENT_DESKTOP**: `XFCE`
**XDG_DATA_DIRS**: `/usr/share/xfce4:/usr/local/share/:/usr/share/:/usr/share`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm/data/user`
**XDG_MENU_PREFIX**: `xfce-`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_SEAT**: `seat0`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_DESKTOP**: `xfce`
**XDG_SESSION_ID**: `1`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**XDG_SESSION_TYPE**: `x11`
**XDG_VTNR**: `7`
**__DM_LOCAL_HID_TIMEOUT_ENV__**: `20000`
**__DM_LOCAL_INTERVAL_ENV__**: `1`
**__DM_OEM_ENV__**: `Lexmark`
**__DM_SANE_BACKEND_NAME_ENV__**: `lexmark_nscan`
**__DM_SCAN_IMAGE_PARAM_ENV__**: `--source='Flatbed'`
**__DM_SCAN_IMAGE_PATH_ENV__**: `export SCAN_SCRIPT_PATH=/usr/lexscan/bin/; /usr/lexscan/bin/scanSaveToPHOTO.sh`
**__DM_VID_PID_PAIRS_ENV__**: *empty*

**Comment by pbek** [comment]
Are you sure your caldav url <https://caldav.example.com/caldav.php/user/home> is correct? There must be more messages in the log widget (are debug messages enabled in the widget?)

**Comment by pbek** [comment]
Well, at least some data is returned. 
You could check `/home/user/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite` if there are any calendar items imported (you would need a sqlite database tool for that).

**Comment by Glandos** [comment]
The table `calendarItem` is empty after clicking on the reload button.
After trying to add an item (using the "Search or create item" field), it adds an entry in this table, and I'm able to see the task in Lightning (the Thunderbird addon). But it's still invisible in QOwnNotes UI.

**Comment by Glandos** [comment]
I just tested with a [Radicale](https://radicale.org/) instance. There is exactly the same behavior.

It seems that the CalDAV standard is not currently well implemented in some parts of QOwnNotes.

**Comment by pbek** [comment]
It is working for ownCloud / Nextcloud and some other CalDav providers. If you find some flaw in <https://github.com/pbek/QOwnNotes/blob/develop/src/services/owncloudservice.cpp> or <https://github.com/pbek/QOwnNotes/blob/develop/src/entities/calendaritem.cpp> please let me know. There you will find the CalDAV implementation.

**Comment by pbek** [comment]
I will close this issue until there is more information.
