### ISSUE TITLE
Windows 10 Error on start up on the latest update

### ISSUE THREAD

**Issue by Servh37** [pbek/QOwnNotes#1079]
i have just completed an update on my windows 10 to the latest.

and not my Qownnotes wont open.

See Even log below.

Faulting application name: QOwnNotes.exe, version: 0.0.0.0, time stamp: 0x5bf81fa5
Faulting module name: Qt5Core.dll, version: 5.10.1.0, time stamp: 0x5a7d85e6
Exception code: 0xc0000005
Fault offset: 0x00212799
Faulting process id: 0x2684
Faulting application start time: 0x01d485e1c424213c
Faulting application path: C:\QOwnNotes\QOwnNotes.exe
Faulting module path: C:\QOwnNotes\Qt5Core.dll
Report Id: 03fad0c5-37b4-42c3-bf00-2628f0fe3bbe
Faulting package full name: 
Faulting package-relative application ID: 

i tried to a fresh install to make sure that, that was not the issue.

**Comment by pbek** [comment]
I've never seen a crash on the Qt core library directly. Hard to tell what's going on on your system. 

> i tried to a fresh install to make sure that, that was not the issue.

did you try `QOwnNotes.exe --session test` to start it in a new (settings) session?

**Comment by pbek** [comment]
> when i my other PC i have don't the same and it is working all fine.

I don't understand this sentence :)

**Comment by Servh37** [comment]
@pbek i the PC that does not have the issue i have changed the Folder to the Synology Drive folder and it works fine.

so i think it is just this PC that has the issue.

**Comment by pbek** [comment]
Ok

If it is a mutex problem reboot your computer.
If it is a settings problem you could clear them with the parameter `--clear-settings`.

**Comment by Servh37** [comment]
@pbek, have had completed a restart.

it looks to be a setting thing cause when i clear the setting it works.

and if i leave the default it works.

but when i remove a folder or add a new one the App stops working.

**Comment by pbek** [comment]
> but when i remove a folder or add a new one the App stops working.

a folder where?

Can you please explain in more detail and step by step what you did, what happened and what you expected.

**Comment by Servh37** [comment]
sorry @pbek 

1. ran `QOwnNotes.exe --clear-settings` application starts
2. clicked next next next then finished. (application is running)
3. go to file -> setting
4. add Synology Drive folder, C:\Users\<username>\SynologyDrive\Notes\Work or remove a folder already in the list.
5. tick all boxes.
6. click ok.
7. application crashes

i would expected that it should close the windows and start loading the notes that are in the folder.

**Comment by pbek** [comment]
Thank you for explaining.
Do you get the same effect with other note folders too, or just with above one? I've no clue what is happening on your system. Can you maybe try and stop the SynologyDrive service, maybe it's removing the sqlite database that will be created by QOwnNotes...

**Comment by Servh37** [comment]
thank you for all your help i think i have found the issue a corrupted `notes.sqlite` i had deleted it and now it is working as it should.

**Comment by pbek** [comment]
great!
really interesting, I wonder what corrupted it

**Comment by Servh37** [comment]
may be the sync form my other PC. i don't know.
