### ISSUE TITLE
Bug: 1.1.3 lost preferences after installation

### ISSUE THREAD

**Issue by Letterus** [pbek/QOwnNotes#108]
After installing version 1.1.3 on OS X I was asked to select the Notes directory. QOwnNotes forgot this setting as well as ownCloud main-dir, server-credentials, update-interval and sending of debug information/heartbeat.

**Comment by pbek** [comment]
Thank you for reporting, @Letterus!
I just updated as well under OS X and I can't reproduce your problems.
I'm currently searching the source code for changes that would make that happen.

**Comment by pbek** [comment]
I can't find anything unusual.
Also nothing unusual while building <https://travis-ci.org/pbek/QOwnNotes/jobs/113434419>
Did you update from version 1.1.2 to 1.1.3?

**Comment by Letterus** [comment]
Uh, no. From 1.1.1 to 1.1.3.

**Comment by pbek** [comment]
I just updated an other Mac from 1.1.2 to 1.1.3 and still didn't have your issues.
Did you loose all your settings or just the one you mentioned?

**Comment by pbek** [comment]
I updated several Linux boxes. No troubles...

**Comment by Letterus** [comment]
I did not loose all settings. Font settings seem to have survived.

Maybe just close this issue. I'll report when I know something new.

**Comment by pbek** [comment]
I can't think of anything other that might have cause this than something happend to the settings plist file.
Feel free to open the issue again if you found something!

**Comment by Letterus** [comment]
Hm, after updating to 1.1.4 the same happened again. Weird: Some preferences were kept: The ownCloud password (all other login information was lost) and the interval for saving the file.

**Comment by pbek** [comment]
I have updated to OS X systems and had no problem... Maybe a permission problem on your Mac? Maybe fixing the disk file permissions with disk utility helps?

**Comment by Letterus** [comment]
Good idea. I'm gonna try.
