### ISSUE TITLE
[Q] view edit note panel

### ISSUE THREAD

**Issue by jakesgithub** [pbek/QOwnNotes#1080]
#### General question

I have two instances of qownnotes on two identical machines running the 18.10.4 and one of them has the option to "show edit panel"  the other does not - I like to toggle between a workspace that has the notes column/search notes sharing a same column and the preview as the main window then toggle vis Alt-Shift-P to switch between it and just the editor by itself. I figured out how to do this on one machine after many hours of playing around but cannot figure out how I did it.

#### Relevant log output in the Log panel

```

```

#### Information about the application, settings and environment

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed Nov 28 21:47:22 2018`
**Version**: `18.11.6`
**Build date**: `Nov 29 2018`
**Build number**: `494`
**Platform**: `linux`
**Operating System**: `Arch Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.11.2`
**Qt Version (runtime)**: `5.11.2`
**Portable mode**: `no`
**Settings path / key**: `/home/jake/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/jake/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `75`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-2`
**localPath**: `/home/jake/Documents/Nextcloud/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/jake/Documents/Nextcloud/Notes/notes.sqlite`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**DistractionFreeMode/editorWidthMode** (QString): `2`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `0`
**DistractionFreeMode/menuBarVisible** (QString): `false`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/vimMode** (bool): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2018-11-28T21:34:04.287`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Hack,16,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,14,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Hack,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 31 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `30`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowDifferentNoteFileName** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `true`
**darkModeColors** (bool): `true`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**dockWasInitializedOnce** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (int): `24`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/jake/Documents/Nextcloud/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): *empty*
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloud/userName** (QString): *empty*
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `initial`
**recentNoteFolders** (QString): `/home/jake/Documents/Nextcloud`
**restoreCursorPosition** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2018-11-03T11.31.08, Rsynic'ing the Servers, server`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useUNIXNewline** (bool): `false`
**workspace-20b1e344-1c0f-44e7-9e67-1ce22e407d45/name** (QString): `minimal`
**workspace-20b1e344-1c0f-44e7-9e67-1ce22e407d45/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-20b1e344-1c0f-44e7-9e67-1ce22e407d45/windowState** (QByteArray): `<binary data>`
**workspace-af7da0ed-478f-4bb1-b26e-e70e49f6c11e/name** (QString): `full`
**workspace-af7da0ed-478f-4bb1-b26e-e70e49f6c11e/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-af7da0ed-478f-4bb1-b26e-e70e49f6c11e/windowState** (QByteArray): `<binary data>`
**workspace-d00b5cb4-303f-4652-9f94-b4b67cf497e2/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-d00b5cb4-303f-4652-9f94-b4b67cf497e2/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `af7da0ed-478f-4bb1-b26e-e70e49f6c11e, 20b1e344-1c0f-44e7-9e67-1ce22e407d45, initial`

## System environment

**GS_LIB**: `/home/jake/.fonts`
**KDE_FULL_SESSION**: `true`
**LANG**: `en_US.UTF-8`
**DISPLAY**: `:0`
**OLDPWD**: `/home/jake`
**QT_SCREEN_SCALE_FACTORS**: `eDP-1=1;HDMI-1=1;`
**MOZ_PLUGIN_PATH**: `/usr/lib/mozilla/plugins`
**XDG_VTNR**: `1`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**XDG_SESSION_ID**: `2`
**USER**: `jake`
**DESKTOP_SESSION**: `/usr/share/xsessions/plasma`
**PWD**: `/home/jake`
**HOME**: `/home/jake`
**XDG_SESSION_TYPE**: `x11`
**XDG_DATA_DIRS**: `/usr/share:/usr/share:/usr/local/share`
**XDG_SESSION_DESKTOP**: `KDE`
**GTK_MODULES**: `canberra-gtk-module`
**MAIL**: `/var/spool/mail/jake`
**SHELL**: `/bin/zsh`
**XDG_SESSION_CLASS**: `user`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XCURSOR_THEME**: `breeze_cursors`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_SEAT**: `seat0`
**SHLVL**: `1`
**LOGNAME**: `jake`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XAUTHORITY**: `/home/jake/.Xauthority`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
**KDE_SESSION_UID**: `1000`
**KDE_SESSION_VERSION**: `5`
**_**: `/usr/bin/kwrapper5`
**SESSION_MANAGER**: `local/al1:@/tmp/.ICE-unix/1042,unix/al1:/tmp/.ICE-unix/1042`

**Comment by pbek** [comment]
For certain more complex layouts you may want to turn off the central widget in the *Panels settings* first. 

Does this answer your question?

**Comment by pbek** [comment]
`noteEditIsCentralWidget` is currently turned on for you

**Comment by jakesgithub** [comment]
Yes, I actually noticed the difference in the debug output between the two machines right after I submitted this and edited the conf file directly setting noteEditIsCentralWidget to false. Can't believe I missed that - I must have compared the two settings screens visually a dozen times lol. Thanks. I really appreciate this product - excellent!

**Comment by jakesgithub** [comment]
Just donated a bit to the cause - thank you.

**Comment by jakesgithub** [comment]
Thanks

**Comment by pbek** [comment]
great, thanks a lot! ;)

**Comment by pbek** [comment]
> Thanks. I really appreciate this product - excellent!

And thank you for your kind words!

**Comment by pbek** [comment]
> Just donated a bit to the cause - thank you.

that wasn't "a bit". :laughing:
