### ISSUE TITLE
Support categories

### ISSUE THREAD

**Issue by schiessle** [pbek/QOwnNotes#1081]
Both the web version of the Notes app (https://github.com/nextcloud/notes) and the Android Notes app (https://github.com/stefan-niedermann/nextcloud-notes) support categories in Nextcloud. Categories are basically sub-folder in the Notes folder. Would be nice if QOwnNotes would support this as well.

**Comment by schiessle** [comment]
Just saw that you can enable the support of sub folders which basically solves the problem

**Comment by pbek** [comment]
Correct :smile:

**Comment by pbek** [comment]
And I'm quite happy that Nextcloud notes finally supports sub-folders (although notes seem to be sorted alphabetically if you select a sub-folder in Nextcloud notes).
