### ISSUE TITLE
Keeping original file name when linking or inserting a file  

### ISSUE THREAD

**Issue by JPR56400** [pbek/QOwnNotes#1082]
#### Expected behaviour

Link : When you are linking a file named FILEaaa this file will be copied in /Notes/attachments under name FILEaaa.png

Insert : When you are inserting a file named FILEaaa this file will be copied in /Notes/media under name FILEaaa.png

#### Actual behaviour

Actually when you are linking a file name FILEaaa this file is copied in /Notes/attachments under name like 77297407.png

Insert : When you are inserting a file named FILEaaa this file is copied in /Notes/media under name like 543021970.png

**Comment by pbek** [comment]
Using the original filenames is always bothersome, because one never knows if they will work on all file systems or even in a file url.

**Comment by andtheWings** [comment]
Got it, sounds like you have the most fail-proof system in place.
