### ISSUE TITLE
Massive icons and toolbar, no where near previous layout

### ISSUE THREAD

**Issue by mvhconsult** [pbek/QOwnNotes#1084]
#### Expected behaviour
Normal windows as on your screenshots (and how it was until the recent update)

#### Actual behaviour
18.12.2 update generates massive icons and the subscreens cannot be resized.

#### Steps to reproduce
Update from older, or install fresh new version..

#### Output from the debug section in the settings dialog
**Current Date**: `do dec 6 07:46:57 2018`
**Version**: `18.12.2`
**Build date**: `Dec  4 2018`
**Build number**: `3981`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.10.1`
**Qt Version (runtime)**: `5.10.1`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\SENSOR\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Users\SENSOR\AppData\Local\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `nl_NL`
**Locale (interface)**: `en`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `236`
**Enabled scripts**: `0`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (int): `31`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**EvernoteImportDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2018-12-06T07:41:43`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `36`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,8,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/update-and-restart** (int): `16384`
**NoteHistory-6** (QVariantList): `<variant list with 5 item(s)>`
**NoteHistory-7** (QVariantList): `<variant list with 1 item(s)>`
**NoteHistoryCurrentIndex-6** (int): `4`
**NoteHistoryCurrentIndex-7** (int): `0`
**PiwikClientId** (QString): `<hidden>`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `ac1a1af1-244a-4db4-9409-02ba7994f810`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**externalEditorPath** (QString): *empty*
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceLanguage** (QString): `en`
**internalIconTheme** (QString): `false`
**itemHeight** (int): `21`
**markdownHighlightingEnabled** (QString): `true`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**noteEditIsCentralWidget** (QString): `true`
**noteSaveIntervalTime** (int): `10`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `C:/Users/SENSOR/Documents/QOwnNotes`
**notifyAllExternalModifications** (QString): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): *empty*
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `2`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloud/userName** (QString): *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `initial`
SENSOR
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**skipVersion** (QString): `18.02.0`
**tagWasAddedToNote** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useUNIXNewline** (QString): `false`
**workspace-1604e011-cdcc-4638-a041-80ccdafcc216/name** (QString): `Personal`
**workspace-1604e011-cdcc-4638-a041-80ccdafcc216/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-1604e011-cdcc-4638-a041-80ccdafcc216/windowState** (QByteArray): `<binary data>`
**workspace-ab1d9f7d-2124-4705-881e-c1ad3b2f7237/name** (QString): `Xarayahosting.nl`
**workspace-ab1d9f7d-2124-4705-881e-c1ad3b2f7237/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-ab1d9f7d-2124-4705-881e-c1ad3b2f7237/windowState** (QByteArray): `<binary data>`
**workspace-ac1a1af1-244a-4db4-9409-02ba7994f810/name** (QString): `MVH Consult`
**workspace-ac1a1af1-244a-4db4-9409-02ba7994f810/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-ac1a1af1-244a-4db4-9409-02ba7994f810/windowState** (QByteArray): `<binary data>`
**workspace-bc211d58-dfea-4542-a3db-be223fdffe69/name** (QString): `WV Merenwijk`
**workspace-bc211d58-dfea-4542-a3db-be223fdffe69/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-bc211d58-dfea-4542-a3db-be223fdffe69/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `1604e011-cdcc-4638-a041-80ccdafcc216, ac1a1af1-244a-4db4-9409-02ba7994f810, ab1d9f7d-2124-4705-881e-c1ad3b2f7237, bc211d58-dfea-4542-a3db-be223fdffe69, initial`

**Comment by pbek** [comment]
Please look into your Interface Settings:

```
MainWindow/mainToolBar.iconSize (int): 36
```

**Comment by mvhconsult** [comment]
A new setting refuses to save: every time after restart or change these values are back to 36/21px

**Comment by pbek** [comment]
> A new setting refuses to save

that settings is veeeery old

>  every time after restart or change these values are back to 36/21px

I cannot reproduce that. Did you try to reset your application in the General settings?

**Comment by mvhconsult** [comment]
> that settings is veeeery old
Yes, sorry for being an old time user
 
> I cannot reproduce that. Did you try to reset your application in the General settings?
I just pressed "Reset message boxes" to no avail.

**Comment by pbek** [comment]
> I just pressed "Reset message boxes" to no avail.

`Clear application data and exit` is the thing you are looking for

**Comment by mvhconsult** [comment]
ok, that helped for the icon trouble, but now I lost all my folders/settings...
