### ISSUE TITLE
Icon dpi scaling issue on windows 

### ISSUE THREAD

**Issue by ptoussai** [pbek/QOwnNotes#1085]
On win10, the icons don't seem to scale properly.

Everything else seems to scale properly.

I use 150% which makes the icons very pixelated, cf. picture.

![scaling issue](https://user-images.githubusercontent.com/35198053/49767155-b8005d80-fcd7-11e8-8819-a0dbad9a9843.jpg)

I tried different compatibility settings, but I cannot get it to scale properly.

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Dec 11 00:07:03 2018`
**Version**: `18.12.2`
**Build date**: `Dec  4 2018`
**Build number**: `3981`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.10.1`
**Qt Version (runtime)**: `5.10.1`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\pht\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Program Files (x86)\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `42`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `C:\Users\pht\OneDrive\Documents\notes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\pht\OneDrive\Documents\notes\notes.sqlite`

## Settings

**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (int): `18`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/ColorSchemes** (QStringList): `EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColorEnabled_-1** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColorEnabled_0** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColorEnabled_1** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColorEnabled_11** (QString): `false`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColorEnabled_12** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColorEnabled_13** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColorEnabled_14** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColorEnabled_15** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColorEnabled_16** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColorEnabled_17** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColorEnabled_18** (QString): `false`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColorEnabled_19** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColorEnabled_2** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColorEnabled_21** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColorEnabled_22** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColorEnabled_23** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColorEnabled_25** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColorEnabled_3** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColorEnabled_4** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColorEnabled_8** (QString): `false`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColor_-1** (QColor): `#ffffff`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColor_0** (QColor): `#fff8ef`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColor_1** (QColor): `#fff2e4`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColor_11** (QColor): `#aaf7ff`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColor_12** (QColor): `#f1f1f4`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColor_13** (QColor): `#f1f1f4`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColor_14** (QColor): `#f1f1f4`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColor_15** (QColor): `#f1f1f4`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColor_16** (QColor): `#f1f1f4`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColor_17** (QColor): `#f1f1f4`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColor_18** (QColor): `#f5f9d8`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColor_19** (QColor): `#e2e7e2`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColor_2** (QColor): `#fff2e4`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColor_21** (QColor): `#ebebeb`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColor_22** (QColor): `#f7f6ff`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColor_23** (QColor): `#eaebea`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColor_25** (QColor): `#fffae2`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColor_3** (QColor): `#edffed`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColor_4** (QColor): `#eaebea`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/BackgroundColor_8** (QColor): `#dbf9e5`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/Bold_12** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/Bold_13** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/Bold_14** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/Bold_15** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/Bold_16** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/Bold_17** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/Bold_8** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/FontSizeAdaption_12** (QString): `200`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/FontSizeAdaption_13** (QString): `160`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/FontSizeAdaption_14** (QString): `130`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/FontSizeAdaption_15** (QString): `100`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/FontSizeAdaption_16** (QString): `90`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/FontSizeAdaption_17** (QString): `90`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/FontSizeAdaption_8** (QString): `100`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_-1** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_0** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_1** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_10** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_11** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_12** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_13** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_14** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_15** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_16** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_17** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_18** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_19** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_2** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_20** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_21** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_22** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_23** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_24** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_26** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_3** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_4** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_5** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_6** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_7** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_8** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColorEnabled_9** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_-1** (QColor): `#000000`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_0** (QColor): `#fc7e00`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_1** (QColor): `#fc7e00`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_10** (QColor): `#a3007b`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_11** (QColor): `#ababab`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_12** (QColor): `#00316e`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_13** (QColor): `#00316e`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_14** (QColor): `#00316e`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_15** (QColor): `#00316e`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_16** (QColor): `#00316e`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_17** (QColor): `#00316e`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_18** (QColor): `#aa0000`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_19** (QColor): `#008000`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_2** (QColor): `#fc7e00`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_20** (QColor): `#3d3d3d`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_21** (QColor): `#393939`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_22** (QColor): `#4e18b9`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_23** (QColor): `#008000`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_24** (QColor): `#cccccc`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_26** (QColor): `#ff5500`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_3** (QColor): `#00bf00`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_4** (QColor): `#008000`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_5** (QColor): `#3d3d3d`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_6** (QColor): `#3d3d3d`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_7** (QColor): `#0057ae`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_8** (QColor): `#00428a`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/ForegroundColor_9** (QColor): `#a3007b`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/Italic_7** (QString): `true`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/Name** (QString): `Light (Copy)`
**EditorColorSchema-43392020-b140-45e2-99d5-eb85144e3697/Underline_26** (QString): `true`
**FileDialog/LastPath** (QString): `C:/Users/pht/Downloads`
**FileDialog/LastPath-InsertImage** (QString): `C:/Users/pht/OneDrive/Pictures/Library`
**FileDialog/LastPath-SettingsExport** (QString): `C:/Users/pht/Downloads`
**LastUpdateCheck** (QDateTime): `2018-12-11T00:05:54`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `18`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Consolas,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Segoe UI,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Consolas,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Segoe UI,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `true`
**NoteHistory-1** (QVariantList): `<variant list with 29 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `28`
**OrphanedAttachmentsDialog/geometry** (QByteArray): `<binary data>`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `true`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `true`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `true`
**itemHeight** (int): `12`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `C:/Users/pht/OneDrive/Documents/notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): *empty*
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloud/userName** (QString): *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2018-12-10T23.38.45`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useUNIXNewline** (QString): `false`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\pht\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `PHT-X1`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**configsetroot**: `C:\WINDOWS\ConfigSetRoot`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\pht`
**IPG_Dir**: `C:\Program Files\Intel\Power Gadget 3.5`
**IPG_Ver**: `3.0`
**JAVA_HOME**: `C:\Program Files\Java\jdk-10.0.2`
**LOCALAPPDATA**: `C:\Users\pht\AppData\Local`
**LOGONSERVER**: `\\PHT-X1`
**NUMBER_OF_PROCESSORS**: `8`
**OneDrive**: `C:\Users\pht\OneDrive`
**OneDriveConsumer**: `C:\Users\pht\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\pht\AppData\Local\GitHubDesktop\app-1.2.6\resources\app\git\cmd\;C:\Users\pht\AppData\Local\GitHubDesktop\app-1.2.6\resources\app\git\usr\bin;C:\Program Files\Java\jdk-10.0.2\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\pht\AppData\Local\Microsoft\WindowsApps;C:\Users\pht\AppData\Local\GitHubDesktop\bin;C:\Users\pht\AppData\Local\Microsoft\WindowsApps;;C:\Users\pht\AppData\Local\Programs\Microsoft VS Code\bin`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 142 Stepping 10, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `8e0a`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\pht\AppData\Local\Temp`
**TMP**: `C:\Users\pht\AppData\Local\Temp`
**USERDOMAIN**: `PHT-X1`
**USERDOMAIN_ROAMINGPROFILE**: `PHT-X1`
**USERNAME**: `pht`
**USERPROFILE**: `C:\Users\pht`
**VBOX_MSI_INSTALL_PATH**: `C:\Program Files\Oracle\VirtualBox\`
**windir**: `C:\WINDOWS`
**__COMPAT_LAYER**: `PerProcessSystemDPIForceOff`

**Comment by pbek** [comment]
Thank you for reporting. The icons are all SVG (vector graphics) and the toolbar is drawn by Qt itself. I'm not sure how to get around that...

**Comment by pbek** [comment]
Maybe the same with #1005.

**Comment by pbek** [comment]
## 18.12.3
- an attempt was made to fix icon scaling problems on high dpi *Windows* or *macOS* systems

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by ptoussai** [comment]
It works! It looks great now.
Btw, I did not find the release in github, but only in the CI.

**Comment by ptoussai** [comment]
Well, maybe not great, but much better :)
I'm not sure what the problem is this time. It seems like there is 0 antialiazing which could be the cause for the curves appearing that way.

So it's not perfect, but very usable in that state.

![scaling issue](https://user-images.githubusercontent.com/35198053/49827518-cad36a80-fd89-11e8-9c80-163357ad11a9.jpg)

**Comment by pbek** [comment]
> Btw, I did not find the release in github, but only in the CI.

thank you, I fixed that now

> Well, maybe not great, but much better :)

At least something, thanks a lot for testing! :) High dpi zooming is still messy in Qt...
