### ISSUE TITLE
System icon theme (Breeze Dark) isn't respected.

### ISSUE THREAD

**Issue by ongun-kanat** [pbek/QOwnNotes#1086]
QOwnNotes doesn't use my system icon theme although all other Qt based apps (qbittorrent, kid3-qt, etc.) work perfectly.

![screenshot_20181211_014931](https://user-images.githubusercontent.com/3601965/49770922-02d5a180-fce7-11e8-9ceb-8a9144553fe1.png)

Interface settings:

![screenshot_20181211_015422](https://user-images.githubusercontent.com/3601965/49771073-b343a580-fce7-11e8-9082-915b20f5b386.png)

#### Expected behaviour
System theme (Breeze Dark) is used for icons.

#### Actual behaviour
Breeze icon theme is used. 

Could be related with #39 but that issue is too old.

**Comment by pbek** [comment]
QOwnNotes uses freedesktop theme icons. I've no ideas where you are using QOwnNotes.
Can you please fill out the issue template so that I may help you (especially the settings text and so on).

**Comment by pbek** [comment]
For me under KDE Neon Dark Breeze icons work flawlessly.

**Comment by ongun-kanat** [comment]
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Dec 11 14:41:23 2018`
**Version**: `18.12.2`
**Build date**: `Dec 11 2018`
**Build number**: `497`
**Platform**: `linux`
**Operating System**: `Arch Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.12.0`
**Qt Version (runtime)**: `5.12.0`
**Portable mode**: `no`
**Settings path / key**: `/home/ongun/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/ongun/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `29`
**Enabled scripts**: `0`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/editorWidthMode** (QString): `1`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `30`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-3bdec0ed-eb9c-424c-9c9b-b6a76e087531`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2018-12-11T14:40:06.208`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Source Code Pro,10,-1,0,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Source Code Pro,10,-1,0,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/tag-notes** (QString): `16384`
**NoteHistory-1** (QVariantList): `<variant list with 28 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `27`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (QString): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Default`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**VersionDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `5f1f584b-e4d8-4a30-839f-9da7ff690725`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**dockWasInitializedOnce** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `24`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**networking/ignoreSSLErrors** (QString): `false`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `false`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/ongun/Cloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): `https://storage.ongunkanat.com`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/userName** (QString): `ongun`
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `083c416c-2f1b-4e08-8e10-1dd3ad3d892a`
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): 
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useUNIXNewline** (QString): `false`
**versionSplitterSizes** (QByteArray): `<binary data>`
**workspace-083c416c-2f1b-4e08-8e10-1dd3ad3d892a/name** (QString): `full`
**workspace-083c416c-2f1b-4e08-8e10-1dd3ad3d892a/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-083c416c-2f1b-4e08-8e10-1dd3ad3d892a/windowState** (QByteArray): `<binary data>`
**workspace-5f1f584b-e4d8-4a30-839f-9da7ff690725/name** (QString): `minimal`
**workspace-5f1f584b-e4d8-4a30-839f-9da7ff690725/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-5f1f584b-e4d8-4a30-839f-9da7ff690725/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `083c416c-2f1b-4e08-8e10-1dd3ad3d892a, 5f1f584b-e4d8-4a30-839f-9da7ff690725`

**Comment by ongun-kanat** [comment]
The issue got weird. I think I might have some problems since QtCreator's icons also broken. But compiling simple QtWidgets applications perfectly work on my desktop. Also as in the original bug report the other Qt applications (even manually built ones) work perfectly. I also written a simple single file Qt application to test it and it worked for both Breeze Dark and Papirus-Dark. Do you use any other method than `QIcon::fromTheme` to get icons from theme?



The application code:
```c++
#include <QApplication>
#include <QMainWindow>
#include <QLabel>
#include <QVBoxLayout>
#include <QIcon>


int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    QMainWindow mw;
    QVBoxLayout *layout = new QVBoxLayout;

    QLabel *lbl = new QLabel();
    lbl->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Preferred);
    lbl->setPixmap(QIcon::fromTheme("document-new").pixmap(256));
    layout->addWidget(lbl);

    QWidget *central = new QWidget();
    central->setLayout(layout);
    mw.setCentralWidget(central);

    mw.setFixedSize(250,250);
    mw.show();
    return a.exec();
}
```

And the results:

Breeze-dark:
![screenshot_20181214_192541](https://user-images.githubusercontent.com/3601965/50020541-90124200-ffd6-11e8-8281-58f4ae6d73c1.png)

Papirus-dark:
![screenshot_20181214_192510](https://user-images.githubusercontent.com/3601965/50020589-b637e200-ffd6-11e8-9458-ae3ad08fd2e5.png)

**Comment by ongun-kanat** [comment]
It seems like Qt 5.12 changed some things as well as KF5 5.53 causing `QIcon::themeName()` (checked [here](https://github.com/pbek/QOwnNotes/blob/23869cbcb78a2b767a4032b6de94bf6b5cc8ab8f/src/main.cpp#L119) ) to return empty string. I had reported the Qt problem to Archlinux bugtracker and they escaleted it to KDE. The issue seems closed I guess. 

BTW, Qt 5.12 has introduced new functions to handle fallback themes namely: [`QIcon::setFallbackThemeName`](https://doc.qt.io/qt-5/qicon.html#setFallbackThemeName) and `QIcon::setFallbackSearchPaths`](https://doc.qt.io/qt-5/qicon.html#setFallbackSearchPaths). You can use them when you start building for Qt 5.12.

**Comment by pbek** [comment]
Thank you for checking!

> You can use them when you start building for Qt 5.12.

That depends on the destination operating system's version of bundled Qt... :sweat_smile:
