### ISSUE TITLE
Disabling search history suggestion dropdown menu

### ISSUE THREAD

**Issue by beemill** [pbek/QOwnNotes#1087]
Is there a way to disable the dropdown box that shows the history of searches when you type in a search for a note? 

Here's are screenshots of the menu dropping down.
![](https://i.imgur.com/0VczvuG.gif)

Is there a way to disable this dropdown box? It's kind of redundant in my view and it gets in the way of the list of notes below.

Loving QownNotes so far, thank for you for this app and thank you for all the hard work!

**Comment by pbek** [comment]
> Is there a way to disable the dropdown box that shows the history of searches when you type in a search for a note?

no, currently not.

> Loving QownNotes so far, thank for you for this app and thank you for all the hard work!

Thank you for your kind words!

**Comment by beemill** [comment]
i guess another way of asking this or looking at this... maybe,  in the "QOwnNotes.conf", under the [savedSearches], i noticed the searches get saved underneath right there in the conf file:

> [savedSearches]
> noteFolder-0=hello, search1, search2, search3, search4, etc, speedbump, dropbox, disable, search5, etcetc

i currently just delete the line at the start up of QOwnnotes:

      [code] sed -i '/noteFolder-0=/d' ./QOwnNotes.conf [/code]

But if there was a way to disable it or prevent it from saving the searches in the first place then this would prevent the dropdown box happening? i would love to be able to disable this and prevent the dropbox from appearing, it'll be one less speedbump and I can go completely mouseless when using QOwnNotes.

**Comment by pbek** [comment]
I already noted your request as feature request. :smile:

**Comment by pbek** [comment]
## 18.12.4
- you can now disable the auto-completion of previous searches in the search 
  panel by turning it off in the *Panel settings*
    - also some memory optimization when adding new searches was done

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by beemill** [comment]
Just downloaded 18.12.4 and disabled it auto-completion and it's working great! Thank you so much!

**Comment by pbek** [comment]
Great, thank you for testing!
