### ISSUE TITLE
[I] bold not working in preview mode

### ISSUE THREAD

**Issue by Mya512** [pbek/QOwnNotes#1088]
#### Expected behaviour

** bold text ** should create bold text in preview mode

#### Actual behaviour

markdown editor shows bold text while preview does not. Please refer to: https://postimg.cc/bS2tsvH7

#### Steps to reproduce

Please note this version is 18.11.6 from the Manjaro repository.

#### Relevant log output in the Log panel

```

```

#### Information about the application, settings and environment

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed Dec 12 17:44:34 2018`
**Version**: `18.11.6`
**Build date**: `Nov 24 2018`
**Build number**: `494`
**Platform**: `linux`
**Operating System**: `Manjaro Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.11.2`
**Qt Version (runtime)**: `5.11.2`
**Portable mode**: `no`
**Settings path / key**: `/home/username/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/username/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `deepin`
**Notes in current note folder**: `21`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/username/Nextcloud/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/username/Nextcloud/Notes/notes.sqlite`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `22`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2018-12-12T17:25:50.198`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Noto Mono,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Noto Mono,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Noto Sans,9,-1,5,50,0,0,0,0,0`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 18 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `17`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**TableDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `7520dd0d-6c5b-4f54-9ed3-c05ff05d81a2`
**darkMode** (QString): `false`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**dockWasInitializedOnce** (QString): `true`
**initialLayoutIdentifier** (QString): `minimal`
**itemHeight** (QString): `17`
**markdownHighlightingEnabled** (QString): `true`
**noteEditIsCentralWidget** (QString): `true`
**notesPath** (QString): `/home/username/Nextcloud/Notes`
**ownCloud/supportEnabled** (QString): `false`
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `initial`
**savedSearches/noteFolder-1** (QStringList): `modprobe, /etc/modules-load.d,
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**workspace-7520dd0d-6c5b-4f54-9ed3-c05ff05d81a2/name** (QString): `Preview`
**workspace-7520dd0d-6c5b-4f54-9ed3-c05ff05d81a2/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-7520dd0d-6c5b-4f54-9ed3-c05ff05d81a2/windowState** (QByteArray): `<binary data>`
**workspace-8acd8778-36d5-4907-9885-d8582a78b73f/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-8acd8778-36d5-4907-9885-d8582a78b73f/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 7520dd0d-6c5b-4f54-9ed3-c05ff05d81a2`

## System environment

**LC_MEASUREMENT**: `en_US.UTF-8`
**LC_PAPER**: `en_US.UTF-8`
**LC_MONETARY**: `en_US.UTF-8`
**LANG**: `en_US.UTF-8`
**DISPLAY**: `:0`
**EDITOR**: `/usr/bin/nano`
**MOZ_PLUGIN_PATH**: `/usr/lib/mozilla/plugins`
**XDG_VTNR**: `1`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `26650`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**LC_NAME**: `en_US.UTF-8`
**XDG_SESSION_ID**: `c2`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/username`
**USER**: `username`
**DESKTOP_SESSION**: `deepin`
**GTK2_RC_FILES**: `/home/username/.gtkrc-2.0`
**PWD**: `/home/username`
**HOME**: `/home/username`
**XDG_SESSION_TYPE**: `x11`
**XDG_DATA_DIRS**: `/home/username/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop`
**XDG_SESSION_DESKTOP**: `deepin`
**QT_SCALE_FACTOR**: `1.00`
**LC_ADDRESS**: `en_US.UTF-8`
**LC_NUMERIC**: `en_US.UTF-8`
**GTK_MODULES**: `canberra-gtk-module`
**_JAVA_OPTIONS**: *empty*
**MAIL**: `/var/spool/mail/username`
**SHELL**: `/bin/bash`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_CURRENT_DESKTOP**: `Deepin`
**GIO_LAUNCHED_DESKTOP_FILE**: `/usr/share/applications/PBE.QOwnNotes.desktop`
**SHLVL**: `0`
**XDG_SEAT**: `seat0`
**LC_TELEPHONE**: `en_US.UTF-8`
**GDMSESSION**: `deepin`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**LOGNAME**: `username`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XAUTHORITY**: `/home/username/.Xauthority`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**PATH**: `/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin`
**LC_IDENTIFICATION**: `en_US.UTF-8`
**LC_TIME**: `en_US.UTF-8`

**Comment by pbek** [comment]
I'm sorry, `** bold **` is not valid markdown, please use `**bold**`. Not even GitHub or the Markdown-It renderer seem to support it.
