### ISSUE TITLE
Bug/Problem: Move/copy a note via context menu

### ISSUE THREAD

**Issue by Letterus** [pbek/QOwnNotes#109]
When I right click a note in the notes list (OS X), I get a context menu that shows some items, two of them: "Move to…" and "Copy to…" When I select them I get a submenu showing one empty item (no text).

I suppose these menu items are to copy/move the note(s) to a different place in the file system? When it should be this way I would expect the menu item to open a dialog which would let me select the place which to copy/move to (instead of showing the empty submenu).

**Comment by pbek** [comment]
These context menus are for copying/moving notes to other notes folders. I guess you haven't selected an other note folder yet.

**Comment by Letterus** [comment]
Ah, now I understood. I tried to create a folder in the notes folder but it was not recognized. When changed the base notes dir it worked. ;)

But: If I have chosen only one notes dir I would the expect the context menu to be disabled (and the submenu empty) or to be informed about what to do: "Choose a second notes folder using the Notes menu to enable this feature." or something similar.

**Comment by pbek** [comment]
I will look into that.

**Comment by pbek** [comment]
> But: If I have chosen only one notes dir I would the expect the context menu to be disabled (and the submenu empty) or to be informed about what to do: "Choose a second notes folder using the Notes menu to enable this feature." or something similar.

This is already implemented. You should not get a context menu for moving and copying notes if your note folder history is empty. Could you please send me the line with `recentNoteFolders` from the debug information in the settings dialog to see what's in there...

**Comment by pbek** [comment]
Any news on this issue?

**Comment by Letterus** [comment]
Not yet. Gonna have to reset the settings and test again.

**Comment by Letterus** [comment]
I resetted the setting and the app behaves as expected now. I think somehow I managed to save an empty path for this setting. When I am able to reproduce it I will report here.

**Comment by pbek** [comment]
> I think somehow I managed to save an empty path for this setting.

That's why I wanted to take a look at them. ;)

Thank you for testing! Keep in mind that there also is a button for emptying the notes folder history in the settings.
I will close this issue until you open it again.
