### ISSUE TITLE
[F] Wrap embedded note tags in HTML comments

### ISSUE THREAD

**Issue by onesentforth** [pbek/QOwnNotes#1092]
Feature request:

I'm using the "in-note-text-tagging.qml" script.
Is it possible to automatically wrap all tags in HTML comments at the top of the note?
For example:

`<!--  tags: #tag1 #tag2  -->`

Right now, the script creates the tags and embeds them into each note as expected.

Is this something that can be added to the next version of the script, or can someone give me some direction regarding how to edit the script?

**Comment by pbek** [comment]
Can you please post this on https://github.com/qownnotes/scripts/issues and mention the authors of the script, so they are able to respond.
