### ISSUE TITLE
Subfolders panel hides immediately upon creating a subfolder if sub-folders are turned off on Windows

### ISSUE THREAD

**Issue by manad777** [pbek/QOwnNotes#1093]
**Issue resolved, see 2nd comment below**

#### Expected behaviour
Can use subfolders panel

#### Actual behaviour
Subfolders panel crashes immediately upon creating a subfolder

#### Steps to reproduce
1. Make Subfolders panel visible
2. In the subfolders panel, right-click and click New Subfolder
3. Enter a name in the new dialog and click OK
4. As soon as you click OK in the name dialog, the subfolders panel closes

#### Output from the debug section in the settings dialog
https://pastebin.com/raw/bBiY33Rc

#### Relevant log output in the Log panel
[04:43:11] [debug] buildNotesIndex - 'noteSubFolderId': 0
[04:43:11] [debug] setupNoteFolderTables - 'database version': 13
[04:43:11] [debug] filterNotesByTag - 'tags': (Tag: <id>3 <name>"test1" <parentId>0 ) 
[04:43:11] [debug] filterNotesByTag - 'fileNameList': ()
[04:43:11] [debug] reloadNoteSubFolderTree
[04:43:11] [debug] notesDirectoryWasModified: "C:/Users/username/Documents/toolsLocal/QOwnNotes/Data/Notes"
[04:43:11] [status] Notes directory was modified externally
[04:43:11] [debug] buildNotesIndex - 'noteSubFolderId': 0
[04:43:11] [debug] setupNoteFolderTables - 'database version': 13
[04:43:11] [debug] updateNoteText: true
[04:43:11] [debug] setCurrentNote - 'note': Note: <id>0 <name>"" <fileName>"" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>true - 'updateNoteText': true - 'updateSelectedNote': true
[04:43:11] [warning] QTextCursor::setPosition: Position '4' out of range

**Comment by manad777** [comment]
Note that by crash, I mean that the panel itself closes, not that the application crashes.

**Comment by manad777** [comment]
I found the issue. You have to go in Settings > Folders and check Use Subfolders or this feature doesn't work.

The actual bug for this issue, then, is that I was able to enable the Subfolders folder from the context menu of the other panels.

However, instead of just fixing the context menu bug, I would advise leaving Subfolders always visible in both menus, but disable it (grayed out), and have the tooltip for that entry say "Subfolders disabled in Settings > Note Folders".

**Comment by pbek** [comment]
The problem is that you could turn on sub-folders for one folder and disable them for another folder and then switch between these folders...

**Comment by pbek** [comment]
I now tested under windows.

> Make Subfolders panel visible

how did you make it visible?

not via the *Window* / *Panels* menu, because the menu entry is not present if note folders are disabled
the only way would be by right-clicking the main menu, and unfortunately I have no control of this menu, it's generated by Qt

**Comment by pbek** [comment]
I found a way to turn of the toolbar context menus altogether.

**Comment by manad777** [comment]
> how did you make it visible?
> 
> not via the _Window_ / _Panels_ menu, because the menu entry is not present if note folders are disabled

That's right, I opened #1094 explaining how I made it visible, back when I thought it was a separate UI bug. To repeat: with Subfolders disabled in Settings, and panels unlocked in Settings > Window (so that their titlebars become dark gray), I right-clicked any open panels (such as Navigation), and clicked the Subfolders entry.

Feel free to close this issue.

**Comment by pbek** [comment]
I closed the other one because it was a feature, not an issue. :)

And toolbar context menus will be gone in the next release. About greying out. I'll have to see about that...

**Comment by pbek** [comment]
> About greying out. I'll have to see about that...

will do

**Comment by pbek** [comment]
## 18.12.5
- the automatically generated toolbar context menus are now disabled to prevent 
  enabling of the note sub-folder toolbar if sub-folders are disabled for the
  current note folder
    - the *note sub-folder* menu entry is now disabled in the *Panels menu*
      instead of hidden if sub-folders are not enabled for current note folder

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by manad777** [comment]
The Window > Panels entry is disabled, but the context menu entry from the other panels is still enabled, I can still show the Subfolders panel, and it still closes when you create a new folder.

Here's the exact reproduction steps to reproduce it from a fresh install:

1. Download latest build for Windows, extract to new directory
2. Run QOwnNotesPortable.bat
3. In intro wizard, set UI to Full
4. Menu > Window > Unlock Panels
5. Right-click Tags panel in top left, then click Subfolders
6. Try to create a new subfolder

**Comment by pbek** [comment]
> Menu > Window > Unlock Panels

Ah, nice find. I didn't even know there was a context menu on the panels if they are floating.

**Comment by pbek** [comment]
## 18.12.6
- the automatically generated context menus for floating panels are now disabled
  to prevent enabling of the note sub-folder toolbar if sub-folders are disabled
  for the current note folder

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by manad777** [comment]
Can't see the context menu anymore, feel free to close!

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by pbek** [comment]
## 18.12.7
- added support for the new [QOwnNotes Chrome Web Companion extension](https://github.com/qownnotes/chrome-web-companion/)
  to add selected text as new note (for [#330](https://github.com/pbek/QOwnNotes/issues/330))
    - you can download the current release of the extension at
      [QOwnNotes Chrome Web Companion 18.12.0](https://github.com/qownnotes/chrome-web-companion/releases/tag/18.12.0),
      just drop the file into Chrome to install the extension
