### ISSUE TITLE
Option to show Subfolders panel doesn't appear in Window menu

### ISSUE THREAD

**Issue by manad777** [pbek/QOwnNotes#1094]
**UPDATE: see reply below, the bug is something else.**
.

#### Expected behaviour
Show the Subfolders panel from main menu's Window > Panels. The other 9 panels are there.

#### Actual behaviour
Subfolders is hidden.

The only way to show it, is to use Window > Unlock Panels, then right-click the title of any other panel. In the context menu, all 10 panels can be checked/unchecked, including Subfolders.

#### Output from the debug section in the settings dialog
https://pastebin.com/raw/bBiY33Rc

#### Relevant log output in the Log panel
(from fresh start)
[04:54:40] [debug] filterNotesByTag - 'tags': (Tag: <id>3 <name>"test1" <parentId>0 ) 
[04:54:40] [debug] filterNotesByTag - 'fileNameList': ()

**Comment by manad777** [comment]
I found the issue. You have to go in Settings > Folders and check Use Subfolders or this feature doesn't work.

The actual bug for this issue, then, is that I was able to enable the Subfolders folder from the context menu of the other panels.

However, instead of just fixing the context menu bug, I would advise leaving Subfolders always visible in both menus, but disable it (grayed out), and have the tooltip for that entry say "Subfolders disabled in Settings > Note Folders".

**Comment by pbek** [comment]
We'll close this for #1093.
