### ISSUE TITLE
Feature request: encrypt entire folder or subfolder rather than individual note

### ISSUE THREAD

**Issue by manad777** [pbek/QOwnNotes#1095]
Currently, you can encrypt any single note. This can be useful for people who put their passwords there instead of in a password manager for some reason, I guess.

However, for people who want to save a lot of private notes, encrypting each note individually is tedious. There should be an option to mark an entire (sub)folder as encrypted. All existing notes would be encrypted with the given password, and all future notes in that (sub)folder would be encrypted as well.

**Comment by pbek** [comment]
Thank you for your suggestion, but I don't think that makes a lot of sense since there are numerous 3rd party tools to encrypt folders. Plus you are loosing the ability to search in the nodes or use 3rd party tools to edit them.
Please also see #423.
