### ISSUE TITLE
[I] Cannot use external storage for notes folder (snap & flatpak)

### ISSUE THREAD

**Issue by smmalmansoori** [pbek/QOwnNotes#1097]
#### Expected behaviour

My notes folder is in an external HDD (NTFS filesystem since I use it in Windows too) which in Ubuntu is listed under the `/media` directory. I should be able to simply specify the path under *Note folder path* in the  *Note folders* section in *Settings*.

#### Actual behaviour

snap: The `/media` directory is empty when attempting to specify the path through the folder chooser dialog under *Note folder path*
flatpak: The `/media` directory is not listed in the folder chooser dialog under *Note folder path*

Note: The drive and its contents are visible in the native file manager (Dolphin - KDE)

#### Steps to reproduce

1. Install snap or flatpak package
2. Attempt to specify a path to your NTFS formatted external storage

#### Relevant log output in the Log panel

```
[02:01:14] [status] Stored 1 note(s) to disk
[02:04:01] [status] Stored 1 note(s) to disk
```

#### Information about the application, settings and environment

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mon Dec 24 02:04:26 2018`
**Version**: `18.12.5`
**Build date**: `Dec 23 2018`
**Build number**: `500`
**Platform**: `linux`
**Operating System**: `Linux 4.15.0-43-generic`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `TuxFamily`
**Qt Version (build)**: `5.11.3`
**Qt Version (runtime)**: `5.11.3`
**Portable mode**: `no`
**Settings path / key**: `/home/username/.var/app/org.qownnotes.QOwnNotes/config/PBE/QOwnNotes.conf`
**Application database path**: `/home/username/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze`
**Notes in current note folder**: `3`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/username/Nextcloud/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/username/Nextcloud/Notes/notes.sqlite`

### Note folder `external`

**id**: `2`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/username/Nextcloud/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/username/Nextcloud/Notes/notes.sqlite`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/vimMode** (bool): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2018-12-24T01:29:18.385`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Hack,9,-1,7,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Hack,9,-1,7,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.rtl** (bool): `false`
**NoteHistory-1** (QVariantList): `<variant list with 3 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `2`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowDifferentNoteFileName** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (int): `28`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/username/Nextcloud/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): *empty*
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloud/userName** (QString): *empty*
**restoreCursorPosition** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useUNIXNewline** (bool): `false`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**KDE_FULL_SESSION**: `true`
**GS_LIB**: `/home/username/.fonts`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**USER**: `username`
**LC_TIME**: `en_US.UTF-8`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `1402`
**SHLVL**: `0`
**HOME**: `/home/username`
**DESKTOP_SESSION**: `/usr/share/xsessions/plasma`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**KDE_SESSION_VERSION**: `5`
**LC_MONETARY**: `en_US.UTF-8`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**MANDATORY_PATH**: `/usr/share/gconf//usr/share/xsessions/plasma.mandatory.path`
**LOGNAME**: `username`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**DEFAULTS_PATH**: `/usr/share/gconf//usr/share/xsessions/plasma.default.path`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_ID**: `3`
**LC_COLLATE**: `en_US.UTF-8`
**PATH**: `/app/bin:/usr/bin`
**LC_ADDRESS**: `ar_AE.UTF-8`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**XCURSOR_THEME**: `breeze_cursors`
**DISPLAY**: `:99.0`
**LANG**: `en_US.UTF-8`
**XDG_CURRENT_DESKTOP**: `KDE`
**LC_TELEPHONE**: `ar_AE.UTF-8`
**XDG_SESSION_DESKTOP**: `KDE`
**XAUTHORITY**: `/run/user/1000/Xauthority`
**SSH_AUTH_SOCK**: `/tmp/ssh-cSiLpqznrAaB/agent.1346`
**LC_NAME**: `ar_AE.UTF-8`
**SHELL**: `/bin/sh`
**QT_ACCESSIBILITY**: `1`
**LC_MEASUREMENT**: `C`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**LC_IDENTIFICATION**: `ar_AE.UTF-8`
**XDG_VTNR**: `1`
**PWD**: `/home/username`
**XDG_DATA_DIRS**: `/app/share:/usr/share:/usr/share/runtime/share:/run/host/share`
**XDG_CONFIG_DIRS**: `/app/etc/xdg:/etc/xdg`
**LC_NUMERIC**: `en_US.UTF-8`
**LC_PAPER**: `ar_AE.UTF-8`
**KDE_SESSION_UID**: `1000`
**SESSION_MANAGER**: `local/machine:@/tmp/.ICE-unix/1456,unix/machine:/tmp/.ICE-unix/1456`
**GST_PLUGIN_SYSTEM_PATH**: `/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/gstreamer-1.0`
**QT_PLUGIN_PATH**: `/app/lib64/plugins:/app/lib/plugins:/usr/share/runtime/lib/plugins`
**GI_TYPELIB_PATH**: `/app/lib/girepository-1.0`
**QML2_IMPORT_PATH**: `/app/lib64/qml:/app/lib/qml`
**DCONF_USER_CONFIG_DIR**: `.config/dconf`
**KDE_FORK_SLAVES**: `1`
**FLATPAK_SANDBOX_DIR**: `/home/username/.var/app/org.qownnotes.QOwnNotes/sandbox`
**XDG_DATA_HOME**: `/home/username/.var/app/org.qownnotes.QOwnNotes/data`
**XDG_CONFIG_HOME**: `/home/username/.var/app/org.qownnotes.QOwnNotes/config`
**XDG_CACHE_HOME**: `/home/username/.var/app/org.qownnotes.QOwnNotes/cache`
**AT_SPI_BUS_ADDRESS**: `unix:path=/run/user/1000/at-spi-bus`

**Comment by pbek** [comment]
> Cannot use external storage

Thank you for reporting, but I'm sorry, this is a feature of the snap confinement. Applications are not allowed to access most parts of your hard disk.

You may want to use one of the many other distribution types on <https://www.qownnotes.org/installation>.

**Comment by pbek** [comment]
I am not maintainer of of the flatpack, maybe you could ask them for help

**Comment by pbek** [comment]
https://github.com/flathub/org.qownnotes.QOwnNotes

**Comment by stobbsm** [comment]
Flatpak is much the same unfortunately. You would need to remove confinement for it to work.

I don't think there is a way to remove it fully at this point, you can use the --filesystem=/path/to/filesystem when launching to allow access.

**Comment by smmalmansoori** [comment]
Thanks! It doesn't work with the first run wizard, but it does work afterwards.
