### ISSUE TITLE
[I] get error when starting QOwnNotes after installing versions > QOwnNotes-18.12.5.deb

### ISSUE THREAD

**Issue by solettitiger** [pbek/QOwnNotes#1099]
#### Expected behaviour

normal starting

#### Actual behaviour

QOwnNotes: error while loading shared libraries: libQt5WebSockets.so.5: cannot open shared object file: No such file or directory

#### Steps to reproduce

just trying to start QOwnNotes. Using Ubuntu Linux 18.04.1

#### Relevant log output in the Log panel

```
QOwnNotes: error while loading shared libraries: libQt5WebSockets.so.5: cannot open shared object file: No such file or directory
```

#### Information about the application, settings and environment

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fr. Dez. 28 00:36:57 2018`
**Version**: `18.12.5`
**Build date**: `Dec 23 2018`
**Build number**: `3994`
**Platform**: `linux`
**Operating System**: `Ubuntu 18.04.1 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.6.2`
**Qt Version (runtime)**: `5.9.5`
**Portable mode**: `no`
**Settings path / key**: `/home/kan/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/kan/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/opt/QOwnNotes/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: `de`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `14`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://elektronischesbuero.at/nxt`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `13.0.4.0`
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `2`

### Note folder `Notizen`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `-2`
**localPath**: `/home/kan/ownCloud/Notes/NOTIZEN`
**remotePath**: `Notes/NOTIZEN`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/kan/ownCloud/Notes/NOTIZEN/notes.sqlite`

### Note folder `Heute`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/kan/ownCloud/Notes/HEUTE`
**remotePath**: `Notes/HEUTE`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/kan/ownCloud/Notes/HEUTE/notes.sqlite`

### Note folder `Ideen`

**id**: `3`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/kan/ownCloud/Notes/SOMETIME`
**remotePath**: `Notes/SOMETIME`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/kan/ownCloud/Notes/SOMETIME/notes.sqlite`

### Note folder `Archiv`

**id**: `4`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/kan/ownCloud/Notes/ARCHIV`
**remotePath**: `Notes/ARCHIV`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/kan/ownCloud/Notes/ARCHIV/notes.sqlite`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/editorWidthMode** (QString): `4`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `22`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/ColorSchemes**: *empty*
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**EvernoteImportDialog/geometry** (QByteArray): `<binary data>`
**FileDialog/LastPath** (QString): `/home/kan/Desktop/twentysixteen`
**FileDialog/LastPath-InsertImage** (QString): `/home/kan/Desktop/twentysixteen`
**FileDialog/LastPath-NoteHTMLExport** (QString): `/home/kan/Desktop`
**FileDialog/LastPath-NoteMarkdownExport** (QString): `/home/kan/Desktop`
**FileDialog/LastPath-NotePDFExport** (QString): `/home/kan/Desktop`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2018-12-28T00:25:06`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/showAtStartup** (QString): `false`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Monospace,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Ubuntu,12,-1,5,57,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Monospace,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Ubuntu,12,-1,5,57,0,0,0,0,0`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `true`
**MessageBoxOverride/move-notes** (QString): `16384`
**MessageBoxOverride/remove-todo-items** (QString): `16384`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteHistory-1** (QVariantList): `<variant list with 20 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 62 item(s)>`
**NoteHistory-3** (QVariantList): `<variant list with 1 item(s)>`
**NoteHistory-4** (QVariantList): `<variant list with 13 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `19`
**NoteHistoryCurrentIndex-2** (QString): `61`
**NoteHistoryCurrentIndex-3** (QString): `0`
**NoteHistoryCurrentIndex-4** (QString): `12`
**OrphanedAttachmentsDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExport** (QByteArray): `<binary data>`
**Printer/NotePrinting** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TagAddDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `2`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Aufgaben`
**TrashDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**VersionDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `true`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `false`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `2`
**currentWorkspace** (QString): `984b4f9f-65ce-46b6-a803-a7d8e7d3c8c5`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `txt`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `false`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `true`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `true`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): `de`
**interfaceStyle** (QString): `Windows`
**internalIconTheme** (QString): `true`
**itemHeight** (QString): `19`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `false`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `true`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `0`
**notesPath** (QString): `/home/kan/ownCloud/Notes/HEUTE`
**notifyAllExternalModifications** (QString): `true`
**oneColumnModeEnabled** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): `https://elektronischesbuero.at/nxt`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): `https://apidata.googleusercontent.com/caldav/v2/solettitiger%40gmail.com/user`
**ownCloud/todoCalendarCalDAVUsername** (QString): `solettitiger@gmail.com`
**ownCloud/todoCalendarDisplayNameList** (QString): `Aufgaben`
**ownCloud/todoCalendarEnabledList** (QString): `Aufgaben`
**ownCloud/todoCalendarEnabledUrlList** (QString): `https://elektronischesbuero.at/nxt/remote.php/dav/calendars/admin/qowntasks/`
**ownCloud/todoCalendarUrlList** (QString): `https://elektronischesbuero.at/nxt/remote.php/dav/calendars/admin/qowntasks/`
**ownCloud/userName** (QString): `admin`
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unbekannter Fehler`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `13.0.4.0`
**previousWorkspace** (QString): `fb4e8413-64b5-4373-b847-3ea1d64a87bb`
**recentNoteFolders** (QStringList): `/home/kan/ownCloud/Notes/ARCHIV, /home/kan/ownCloud/Notes/NOTIZEN, /home/kan/ownCloud/Notes/SOMETIME, /home/kan/ownCloud/Notes, /home/kan/ownCloud/3. HEUTE, /home/kan/ownCloud/3. SOMETIME, /home/kan/ownCloud/3. ARCHIV, /home/kan/Nextcloud/Notes`
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Marathon - DSGVO, CLS-Homepage - Ergänzugen, Aupair.Click - Datensicherung, Note 2018-04-10T11.23.46, Söllradl - SpamSentinel Update 2018, KAPPA - Probs mit SMTPUTF8, FFK - Website, Lime-DMC - Wordpress installieren, Marathon - Todo-Liste, Marathon - Newsletter, Marathon - Spendenübergabe DVO, BTF-Chemiepark  - SSL-Zertifikat abgelaufen, Söllradl - Fehlerbehebungen, Marathon - JHV 2018, Marathon - 3-Tagesausflug organisieren, Carmanama - Probs mit Typo3, Kappa - Änderungen kappaFM, Opal4You - Lösung für MusicPlayer, Maleewan - Homepage, Aupair - Formularanwendung, CLS - Homepage neu, Söllradl - Win2016 Server, Update Domino, 20180107 Update Domino, 20180106, Note 2018-01-05T08.51.52, Note 2017-05-08T23.34.55, Note 2017-05-08T23.33.38, Note 2017-03-18T15.22.10, Note 2017-03-01T08.06.12, Note 2017-02-15T16.21.38, Note 2017-02-11T01.42.38, Note 2017-02-11T01.42.11, Note 2017-02-06T11.18.04, Note 2017-02-01T16.39.01, Note 2017-01-23T23.26.09, Note 2017-01-23T16.06.29, backup, Note 2017-01-23T14.11.41, Note 2017-01-23T09.50.13, Note 2017-01-19T20.00.59, Note 2017-01-17T20.28.55, Note 2017-01-15T17.44.21, Note 2017-01-12T23.58.00, Note 2017-01-12T15.40.13, Note 2017-01-10T16.57.21, Note 2017-01-09T10.00.21, Note 2017-01-07T16.01.05, Note 2017-01-06T00.13.18, Note 2017-01-05T11.19.41, Note 2017-01-02T10.55.50, Note 2016-12-22T19.14.02, Note 2016-12-22T12.03.22, Note 2016-12-22T12.02.01, Note 2016-12-21T10.44.47, Note 2016-12-05T14.35.25, Note 2016-11-24T08.21.31, Note 2016-11-07T10.48.41, Note 2016-11-05T21.36.06, Note 2016-11-05T01.41.46, Note 2016-11-04T14.43.16, Note 2016-11-03T17.37.15, Note 2016-10-24T21.06.26, Note 2016-10-24T21.05.14, Note 2016-10-24T08.54.56, Note 2016-10-17T09.45.11, Note 2016-10-12T23.00.45, Note 2016-10-12T10.42.19, Persönlich, Note 2016-10-03T21.11.22, Note 2016-09-28T11.11.58, Note 2016-09-27T01.30.23, Note 2016-09-26T23.26.19`
**savedSearches/noteFolder-2** (QStringList): `20181225, 20181223, Note 2018-12-21T10.25.15, 20181220, 20181219, 20181218, 20181217, 20181214, Note 2018-12-12T11.53.00, Note 2018-12-04T11.27.14, 2018-11-30, Marathon - Homepage, 20181127, Note 2018-11-17T10.25.39, Note 2018-11-10T17.03.56, Note 2018-11-07T10.44.20, 20181008, 20180930, 20180929, 20180928, 20180927, Note 2018-09-14T08.16.52, Note 2018-09-11T12.29.44, Note 2018-09-11T11.31.29, Note 2018-09-10T20.50.00, Note 2018-09-08T15.17.50, Note 2018-09-07T16.17.59, Note 2018-09-06T00.12.38, Note 2018-09-04T14.15.44, Note 2018-09-04T10.45.45, Note 2018-09-04T09.10.56, domino`
**savedSearches/noteFolder-4** (QStringList): `0. Störungen, PHP-Version per .htaccess ändern, FS20-Einstellungen, Zugangsdaten Carmanama`
**showMenuBar** (bool): `true`
**showNoteListUnderTagPane** (QString): `false`
**showStatusBar** (bool): `true`
**showTagPaneUnderNavigationPane** (QString): `true`
**skipVersion** (QString): `18.12.7`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `true`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Hauptsymbolleiste`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `Formatierungs-Werkzeugleiste`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `Einfügen-Werkzeugleiste`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `Werkzeugleiste Verschlüsselung`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `Fenster-Werkzeugleiste`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `Beenden - Symbolleiste`
**toolbar/size** (QString): `6`
**trashSplitterSizes** (QByteArray): `<binary data>`
**useSoftWrapInNoteEditor** (QString): `false`
**useUNIXNewline** (QString): `false`
**versionSplitterSizes** (QByteArray): `<binary data>`
**workspace-984b4f9f-65ce-46b6-a803-a7d8e7d3c8c5/name** (QString): `default`
**workspace-984b4f9f-65ce-46b6-a803-a7d8e7d3c8c5/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-984b4f9f-65ce-46b6-a803-a7d8e7d3c8c5/windowState** (QByteArray): `<binary data>`
**workspace-a83d5e75-046f-4092-808e-fc23fa1375f9/name** (QString): `focus`
**workspace-a83d5e75-046f-4092-808e-fc23fa1375f9/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-a83d5e75-046f-4092-808e-fc23fa1375f9/windowState** (QByteArray): `<binary data>`
**workspace-fb4e8413-64b5-4373-b847-3ea1d64a87bb/name** (QString): `preview`
**workspace-fb4e8413-64b5-4373-b847-3ea1d64a87bb/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-fb4e8413-64b5-4373-b847-3ea1d64a87bb/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `984b4f9f-65ce-46b6-a803-a7d8e7d3c8c5, fb4e8413-64b5-4373-b847-3ea1d64a87bb, a83d5e75-046f-4092-808e-fc23fa1375f9`

## System environment

**J2SDKDIR**: `/usr/lib/jvm/java-8-oracle`
**USER**: `kan`
**LANGUAGE**: `de_DE:en`
**LC_TIME**: `de_AT.UTF-8`
**TEXTDOMAIN**: `im-config`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `3189`
**J2REDIR**: `/usr/lib/jvm/java-8-oracle/jre`
**SHLVL**: `0`
**QT4_IM_MODULE**: `xim`
**HOME**: `/home/kan`
**DESKTOP_SESSION**: `ubuntu`
**GTK_MODULES**: `gail:atk-bridge`
**GNOME_SHELL_SESSION_MODE**: `ubuntu`
**LC_MONETARY**: `de_AT.UTF-8`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**MANDATORY_PATH**: `/usr/share/gconf/ubuntu.mandatory.path`
**IM_CONFIG_PHASE**: `2`
**LOGNAME**: `kan`
**GTK_IM_MODULE**: `ibus`
**DEFAULTS_PATH**: `/usr/share/gconf/ubuntu.default.path`
**USERNAME**: `kan`
**XDG_SESSION_ID**: `3`
**WINDOWPATH**: `2`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin`
**DERBY_HOME**: `/usr/lib/jvm/java-8-oracle/db`
**PAPERSIZE**: `a4`
**LC_ADDRESS**: `de_AT.UTF-8`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**DISPLAY**: `:1`
**LANG**: `de_DE.UTF-8`
**XDG_CURRENT_DESKTOP**: `ubuntu:GNOME`
**LC_TELEPHONE**: `de_AT.UTF-8`
**XDG_SESSION_DESKTOP**: `ubuntu`
**XMODIFIERS**: `@im=ibus`
**XAUTHORITY**: `/run/user/1000/gdm/Xauthority`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**LC_NAME**: `de_AT.UTF-8`
**SHELL**: `/bin/bash`
**QT_ACCESSIBILITY**: `1`
**GDMSESSION**: `ubuntu`
**LC_MEASUREMENT**: `de_AT.UTF-8`
**TEXTDOMAINDIR**: `/usr/share/locale/`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**LC_IDENTIFICATION**: `de_AT.UTF-8`
**XDG_VTNR**: `2`
**QT_IM_MODULE**: `ibus`
**JAVA_HOME**: `/usr/lib/jvm/java-8-oracle`
**PWD**: `/home/kan`
**CLUTTER_IM_MODULE**: `xim`
**XDG_DATA_DIRS**: `/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-ubuntu:/etc/xdg`
**LC_NUMERIC**: `de_AT.UTF-8`
**LC_PAPER**: `de_AT.UTF-8`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**XDG_MENU_PREFIX**: `gnome-`
**SESSION_MANAGER**: `local/PC03:@/tmp/.ICE-unix/3111,unix/PC03:/tmp/.ICE-unix/3111`
**GIO_LAUNCHED_DESKTOP_FILE**: `/usr/share/applications/QOwnNotes.desktop`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `29864`
**GJS_DEBUG_OUTPUT**: `stderr`
**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`

**Comment by pbek** [comment]
Thank you for reporting, I just saw that the Travis CI `deb` file uses it's own version of <https://github.com/pbek/QOwnNotes/blob/develop/travis/build/DEBIAN/control> where `libqt5websockets5` is not required. I'll fix that in the next release. The Launchpad and OBS releases should already include the `libqt5websockets5` package.

**Comment by pbek** [comment]
The library was included for #330. Is now fixed in https://github.com/pbek/QOwnNotes/commit/164e39fe8948f96df295396ed6e1af0949d7e1f6

**Comment by pbek** [comment]
In general it would be easier for you to use the Launchpad repository from <https://www.qownnotes.org/installation#Linux>.

**Comment by pbek** [comment]
## 18.12.9
- added missing `libqt5websockets5` dependency to Travis CI Debian package

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by solettitiger** [comment]
Thank you so much! Now qownnotes works again for me. I use it a lot and it is really great software!

**Comment by pbek** [comment]
Thank you for your kind words!
