### ISSUE TITLE
QOwnNotes removes whitespace from saved notes

### ISSUE THREAD

**Issue by valmar** [pbek/QOwnNotes#11]
First of all, thanks for this awesome program. I am now using this as a full Evernote replacement.

I imported into the note folder some external notes that I previously wrote with Markdown in Haroopad. I can see them and edit them just fine in QOwnNotes, but when they are autosaved, all unnecessary whitespace (white lines, etc, not the space between words) is removed and the name of the note (and of the file) is set to the first line of the Markdown note. So for example, if the imported Markdown note looks like this:

`## THIS IS MY NOTE`
` `
`Test test`

The note becomes:

`## THIS IS MY NOTE`
`Test test`

The name of the note becomes `## THIS IS MY NOTE`

Is this the expected behavior? This happens for me with build 25

**Comment by pbek** [comment]
Thank you for your kind words, @valmar!

The first line has to be the name of the name of the note (minus the ".txt"), that behaviour is enforced by the ownCloud note webapp, so I had to implement it the same way.

As for whitespaces, they should not get removed in the editor mode (but the markdown view ignores them). How did you get the notes into QOwnNotes? Did you put text files into the folder or did you use copy/paste?

**Comment by valmar** [comment]
Sorry @pbek for the delayed response
No I moved the notes just by putting the text files into the folder. I then edited them with QOwnNotes and when I went back to them they were like I said, without whitespace...

Thanks for looking into it!

**Comment by pbek** [comment]
No worries, @valmar. ;)
I think I found the problem, it happens when a file gets renamed, if the first line of the file doesn't match the file name.
It should be fixed now, can you please head over to http://www.qownnotes.org/ and fetch the latest build (building is in process, you have to wait until it shows you today's date). Please tell me if you still got the problem.

**Comment by valmar** [comment]
@pbek, it seems to be fixed! Thank you!

**Comment by pbek** [comment]
Great, @valmar! Thanks again for reporting!
