### ISSUE TITLE
HTML Issue

### ISSUE THREAD

**Issue by mjbrancato** [pbek/QOwnNotes#110]
When saving HTML code as your note, there is no way to go back and edit the HTML because the application shows it as HTML, when it should be as pure text.

**Comment by pbek** [comment]
Thank you for your report, @mjbrancato!
Can you please describe in more detail what you are doing, I can't reproduce this behavior.

**Comment by pbek** [comment]
I will close this issue now for lack of feedback, feel free to open it again if you have more information.
