### ISSUE TITLE
Missing preferences option ? [Ubuntu 18.10]

### ISSUE THREAD

**Issue by repsorp** [pbek/QOwnNotes#1100]
Hi,

Not any preferences option anywhere here...
(+ a weird central black screen...)

Ubuntu 18.10
Gnome-shell 3.30.1
QOwnNotes 18.12.8

Thanks

![screenshot from 2018-12-27 21-09-10](https://user-images.githubusercontent.com/6297032/50499909-b364d480-0a4d-11e9-83f8-82e37cf6d65a.png)

**Comment by pbek** [comment]
Without seeing your settings, because you didn't post them as advised I would see you are using a dark theme for your editor. (Take a look at the *Editor settings*).

Does this answer your question?

**Comment by repsorp** [comment]
Hi,

sorry, my bad
Previous theme  was effectively Arc-darker.
Preferences option are still missing though with other themes as you can see on the screenshots.

Shell is Default shell. 
Been testing with other shells (Arc, Pop, Nextik) but no change, preferences still missing.

Default theme (Adwaita):
![screenshot from 2018-12-28 12-57-25](https://user-images.githubusercontent.com/6297032/50515072-b4742100-0aa2-11e9-93e0-99bb20badf96.png)
![screenshot from 2018-12-28 12-58-33](https://user-images.githubusercontent.com/6297032/50515077-b76f1180-0aa2-11e9-887b-695c89f59424.png)

Numix theme:
![screenshot from 2018-12-28 12-57-09](https://user-images.githubusercontent.com/6297032/50515086-cf469580-0aa2-11e9-9ee4-d0302fed6f1b.png)
![screenshot from 2018-12-28 12-56-47](https://user-images.githubusercontent.com/6297032/50515089-d1105900-0aa2-11e9-8747-18dd40159070.png)

HighContrast theme!
![screenshot from 2018-12-28 12-57-18](https://user-images.githubusercontent.com/6297032/50515094-da99c100-0aa2-11e9-8485-9f048766bfb5.png)
![screenshot from 2018-12-28 12-49-09](https://user-images.githubusercontent.com/6297032/50515095-dc638480-0aa2-11e9-9493-84dd8b561d01.png)

**Comment by pbek** [comment]
> but no change, preferences still missing.

what are you talking about? the menu bar?

**Comment by pbek** [comment]
If you have turned it off by hand you can turn it on with `Ctrl + Shift + M`. If your desktop environment is hiding it you have to ask the developers of it how they handle Qt apps...

**Comment by repsorp** [comment]
Silly me...
Didn't know about ctrl-shift-M
Preferences option back now
Thanks for your help and sorry for the noise
Have a nice day

**Comment by pbek** [comment]
Great! Have a nice day yourself too!
