### ISSUE TITLE
Failed Dependency Updating Fedora 28

### ISSUE THREAD

**Issue by progkix** [pbek/QOwnNotes#1101]
#### Expected behaviour
qownnotes-18.12.9-1.1.x86_64 should update properly

#### Actual behaviour
error: Failed dependencies:
	qt5-qt5websockets is needed by qownnotes-18.12.9-1.1.x86_64

#### Steps to reproduce
rpm -Uvh qownnotes-18.12.9-1.1.x86_64

**Comment by pbek** [comment]
`qt5-qt5websockets` is already included  <https://build.opensuse.org/package/view_file/home:pbek:QOwnNotes/desktop/qownnotes.spec?expand=1>. I guess you are not using the repository directly, correct? Because I guess that would install all dependencies automatically... If you are doing it by hand you would need to install `qt5-qt5websockets` by hand too.

**Comment by progkix** [comment]
Ok, just added QOwnnotes Fedora 28 repo. Here's the output of dnf upgrade qownnotes*

dnf upgrade qownnotes*
QOwnNotes (Fedora_28)                                                                             3.3 kB/s | 2.8 kB     00:00    
Last metadata expiration check: 0:00:00 ago on Sat 29 Dec 2018 05:34:15 AM EST.
Dependencies resolved.

 Problem: cannot install the best update candidate for package qownnotes-18.12.5-1.1.x86_64
  - nothing provides qt5-qt5websockets needed by qownnotes-18.12.9-1.1.x86_64
==================================================================================================================================
 Package                     Arch                     Version                         Repository                             Size
==================================================================================================================================
Skipping packages with broken dependencies:
 qownnotes                   x86_64                   18.12.9-1.1                     home_pbek_QOwnNotes                   2.9 M

Transaction Summary
==================================================================================================================================
Skip  1 Package

Tried uninstall old version (qownnotes-18.12.5-1.1.x86_64) and then dnf install qownnotes with this output:

dnf install qownnotes
Last metadata expiration check: 0:00:00 ago on Sat 29 Dec 2018 05:38:24 AM EST.
Error: 
 Problem: conflicting requests
  - nothing provides qt5-qt5websockets needed by qownnotes-18.12.9-1.1.i686
  - nothing provides qt5-qt5websockets needed by qownnotes-18.12.9-1.1.x86_64

**Comment by nitishd** [comment]
The package name is qt5websockets.

Pull request for the fix #1102.

**Comment by progkix** [comment]
thanks, i thought it might be a typo

**Comment by pbek** [comment]
> The package name is qt5-qtwebsockets.
> 
> Pull request for the fix #1102.

thanks a lot, @nitishd! I also updated <https://build.opensuse.org/package/view_file/home:pbek:QOwnNotes/desktop/qownnotes.spec>. Packages are currently rebuilding.
