### ISSUE TITLE
Feature Request: Web Clipper

### ISSUE THREAD

**Issue by TinfoilBat** [pbek/QOwnNotes#1103]
Hey there,

The app sure looks great and easy to use. I was wondering if a web clipper could be a possible feaure to add in the feature, or if it would be out of the scope of this app. 

Joplin has it, but it's quite a PITA to use for now. Understandable, since it's only one dev; and it already is some great work.

Is it remotely possible or easy to do?

Thanks for your great work!

**Comment by pbek** [comment]
That was what I was adding in the last releases. :) You can test and comment directly in #330.

**Comment by pbek** [comment]
I now also added the extension to the [Chrome Web Store](https://chrome.google.com/webstore/detail/qownnotes-web-companion/pkgkfnampapjbopomdpnkckbjdnpkbkp).

**Comment by TinfoilBat** [comment]
Okay, my bad. I'm pretty new to everything in general. Gotta tame down the n00b beast yet.

Thanks!

**Comment by pbek** [comment]
The extension is pretty new itself. :smile: Feel free to comment on it.
