### ISSUE TITLE
[F] Animated GIF viewer

### ISSUE THREAD

**Issue by jjisnow** [pbek/QOwnNotes#1104]
#### Expected behaviour

GIFs referenced in the markdown should have the image animate in the preview

#### Actual behaviour

Static image of gif is shown

#### Steps to reproduce

Place gif in markdown file, view file

**Comment by pbek** [comment]
Thank you for your suggestion. I guess that will only work if the preview is a fully fledged browser (with all its advantages and disadvantages) and no `QTextBrowser`.

**Comment by pbek** [comment]
## 19.1.10
- animations of embedded gif images should now animate in the preview (a big thank you to @liulex)

**Comment by pbek** [comment]
As mentioned on #1125 it does not really play animations for me all the time on

**Platform**: `linux`
**Operating System**: `KDE neon User Edition 5.14`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Self-build`
**Qt Version (build)**: `5.11.2`
**Qt Version (runtime)**: `5.11.2`

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by jjisnow** [comment]
Trialling out version 19.1.10 on Windows 7 x86_64, I note that the embedded gif images are still static, but step through the frames as you click on the images individually or even click on the "About QOwnNotes" option from the menu.

**Comment by pbek** [comment]
thank you for testing, maybe the latest changes from @liulex will help

**Comment by pbek** [comment]
@jjisnow could you please test https://ci.appveyor.com/api/buildjobs/9fy9p3w8pni0exb0/artifacts/appveyor%2FQOwnNotes.zip if the animation works with this build? Under Linux the problem was fixed by #1126.

**Comment by pbek** [comment]
## 19.1.11
- fixed gif animations in the preview (thank you @liulex)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by jjisnow** [comment]
@pbek version 19.1.11 build 4137 works perfectly displaying previews of GIFs. Thanks for the fixes!

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by bipox** [comment]
Hey,

On Linux (KDE Neon) GIFs are correctly previewed if present on the computer, but online gifs are shown as a static image

I tested with this gif you linked in another thread
![onlinegif](https://camo.githubusercontent.com/115c41c61997934ec6213597ba702139d01eda95/68747470733a2f2f6d6572616268656a612e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031362f31302f33396362316539306337643930313333326230323336633133613438366636372e676966)

If downloaded to the computer however, motion works

I also tested with a gif with the extension .gif in the URL, same problem.

**Comment by pbek** [comment]
Yes, the QTextBrowser of the preview doesn't support animated GIFs. @liulex implemented that for local images.

**Comment by bipox** [comment]
Oh, I didn't get it when reading the threads, sorry about that.

**Comment by pbek** [comment]
You can take a look at the code at #1125

**Comment by r3d9u11** [comment]
@pbek 

Hello, is it work or no?
I'm seeing static image instead of animated gif (I'm on KDE Neon)

**Comment by pbek** [comment]
Animations works fine for me in the preview on KDE Neon with local gifs.

**Comment by r3d9u11** [comment]
@pbek Yep, I've copied remote gif to local machine. Now it works, thanks!
