### ISSUE TITLE
Closing port 22222

### ISSUE THREAD

**Issue by adamsson6** [pbek/QOwnNotes#1105]
Hi, I recently saw than the port 22222 was used by qownnotes. Is it possible please to add a function do disable this usage ? I don't want to use the websocket as I prefer to use the app offline. Thanks !

**Comment by pbek** [comment]
## 19.1.1
- you can now disable the socket server in the *Browser extension settings*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by adamsson6** [comment]
Thank you very much, it's working. I tried on fedora 29 but it should be ok on other distros (i will try with ubuntu and debian).
No need to restart the app, it's working immediatly.

**Comment by pbek** [comment]
Thank you for testing!

> No need to restart the app, it's working immediatly.

I wrote it that way, but the port was sometimes still open, so I wanted to make sure
