### ISSUE TITLE
dev releases are marked as 'Latest release' in github

### ISSUE THREAD

**Issue by core-code** [pbek/QOwnNotes#1109]
i expect only stable versions that are linked from the homepage to be marked as 'Latest release' and dev-releases to be marked as 'Prerelease'

**Comment by pbek** [comment]
Thank you for your concern. If you find a way to do that with Travis CI please let me know.

**Comment by core-code** [comment]
seems to be possible, see here at the bottom:
https://docs.travis-ci.com/user/deployment/releases
or here:
https://github.com/travis-ci/dpl/issues/234

**Comment by pbek** [comment]
Nice, we soon will see on https://github.com/pbek/QOwnNotes/releases if it worked for the macOS dev build.

**Comment by pbek** [comment]
https://github.com/pbek/QOwnNotes/releases/tag/dev-macosx-b4045-110710 is marked as pre-release now, does that work for you for <https://github.com/Homebrew/homebrew-cask/pull/57152>?

**Comment by core-code** [comment]
thanks. now the 'dev-macosx-b4044-055059' is marked as "latest release" but this should be fixed as soon as a new release is done. thanks, looks good.

**Comment by pbek** [comment]
https://api.github.com/repos/pbek/QOwnNotes/releases/latest doesn't seem to be uptodate yet

> Please keep in mind that the "latest release" must not necessary always be the macOS release, that just depends on what build is finished last (Linux, Windows, macOS)

I guess that also true for: https://api.github.com/repos/pbek/QOwnNotes/releases/latest

**Comment by core-code** [comment]
> https://api.github.com/repos/pbek/QOwnNotes/releases/latest doesn't seem to be uptodate yet

i think it is. the issue is that the latest real releases ( windows-b4048, macosx-b4034-122701, linux-b4034-121748) aren't marked as 'Latest Release', so the API doesn't pick them up

> I guess that also true for: https://api.github.com/repos/pbek/QOwnNotes/releases/latest

as long as the releases are in-sync thats not a problem. an automated way to keep up with non-beta releases is definitely helpful e.g. for the homebrew-cask project that helps macOS users quickly install QOwnNotes

**Comment by pbek** [comment]
> i think it is. the issue is that the latest real releases ( windows-b4048, macosx-b4034-122701, linux-b4034-121748) aren't marked as 'Latest Release', so the API doesn't pick them up

I guess only the latest release (regardless of what is released) might be marked as "latest release" by GitHub

I have no idea why https://github.com/pbek/QOwnNotes/releases/tag/dev-macosx-b4035-123314 is currently the "latest release"

but https://www.qownnotes.org/api/v1/last_release/QOwnNotes/macosx.json is always the correct place to look

> for the homebrew-cask project that helps macOS users quickly install QOwnNotes

thank you for your work on that!

**Comment by core-code** [comment]
> but https://www.qownnotes.org/api/v1/last_release/QOwnNotes/macosx.json is always the correct place to look

thanks i've added this to homebrew-cask just yesterday ;)

**Comment by pbek** [comment]
> thanks i've added this to homebrew-cask just yesterday ;)

yes, I saw that :)
