### ISSUE TITLE
Cannot connect to my Qownnote from ubuntu desktop to my owncloud Qownnote API on amazon EC2

### ISSUE THREAD

**Issue by minusquare** [pbek/QOwnNotes#111]
Hi! 
(1)Created Webserver https://magicbits.net on amazon ec2 micro instance also running on ubuntu server 14.04 LTS (JUST TRYING)
(2)Installed owncloud 8.2  in /var/www/html/cloud [SUBDIRECTORY OF MY WEBROOT /var/www/html.
(3)Installed and enabled various apps including Qownnote API
 [OWNCLOUD 8.2 SHOWS IT AS EXPERIMENTAL]
(4)My cloud is perfectly accessible via https://magicbits.net/cloud
(5)Installed Qownnotes on my PC (Ubuntu 14.04)
(6)In File->Settings->owncloud entered proper username and password
(7)Clicked connect To Owncloud Server
(8)Error shown "Username" and Password Not Correct" [ RECHECKED MANY TIMES THAT WHAT I USE ARE CORRECT AND ALLOW ME TO LOGIN TO MY OWNCLOUD]
RESULT: Cannot connect to QOwnnoteAPI
================      debug log pasted below =============================
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mon Mar 7 19:58:23 2016`
**Version**: `1.0.3`
**Build date**: `Feb 20 2016`
**Build number**: `1067`
**Platform**: `linux`
**Operating System**: `Ubuntu 14.04.4 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version**: `5.4.2`

## Server Info

**serverUrl**: `https://magicbits.net/cloud`
**appIsValid**: `no`
**connectionErrorMessage**: `Error downloading https://magicbits.net/cloud/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/ - server replied: Internal Server Error`

## Settings

**GAnalytics-cid**: `<hidden>`
**LastUpdateCheck**: `2016-03-07T19:33:26`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `24`
**MainWindow/markdownDefaultViewMode**: `false`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `Courier,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `Courier,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/showRecentNoteFolderInMainArea**: `false`
**MainWindow/windowState**: `<binary data>`
**ShowSystemTray**: `false`
**SortingModeAlphabetically**: `false`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `false`
**appMetrics/notificationShown**: `true`
**cryptoKey**: `<hidden>`
**defaultNoteFileExtension**: `txt`
**demoNotesCreated**: `true`
**disableAutomaticUpdateDialog**: `false`
**externalEditorPath**: *empty*
**interfaceLanguage**: *empty*
**mainSplitterSizes**: `<binary data>`
**noteSaveIntervalTime**: `10`
**notesPath**: `/home/srvadmin/Documents/owncloud_Notes`
**notifyAllExternalModifications**: `false`
**ownCloud/localOwnCloudPath**: `/home/srvadmin/Documents/owncloud_Notes`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: `https://magicbits.net/cloud`
**ownCloud/todoCalendarBackend**: `1`
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloud/userName**: `admintejas`
**recentNoteFolders**: *empty*
=============================================================================
Any clues??? Thanks in advance.

**Comment by pbek** [comment]
Can you please test if task syncing works. It doesn't need the QOwnNotesAPI.
Do you have access to your server's Apache and ownCloud error logs? It seems you are getting a `Internal Server Error`.

**Comment by pbek** [comment]
I will close this issue now for lack of feedback, feel free to open it again if you have more information.
