### ISSUE TITLE
Question: Can QOwnNotesAPI functionality be achieved with standard API?

### ISSUE THREAD

**Issue by brainchild0** [pbek/QOwnNotes#1112]
_Note: I have used QOwnNotes for a short time now, and in that time the availability of this software was the deciding factor for my choosing to migrate to Nextcloud.  So QOwnNotes was the "killer app" for me to finally migrate my cloud solution.  The interface is very clean and appealing, and the feature set is quite impressive for a small-scale project.  Most open source projects are filled with bugs and flaws unless they are maintained by a more substantial community.  And while the power user is clearly the target, the design manages to make basic use easy to understand.  As I have become more familiar with Nextcloud, I find I have some questions about how it and QOwnNotes can most effectively interact._

---

Currently, QOwnNotes supports advanced cloud features, such as versioning and trash management, only when the custom app QOwnNotesAPI is installed on the remote cloud instance.  But this requirement imposes a limitation on clients without administrative access to the cloud instance, and also complicates administration even when access is not an issue.

__Question:__ _Both the Versions and Trashbin apps on Nextcloud have RESTful APIs.  Do these interfaces make it possible, in principle, to enhance the client such that it produces the same functionality, without dependence on the custom server-side extension?_

**Comment by pbek** [comment]
Thank you for your kind words!

As to your question, I don't know. At the time I wrote the API there weren't any ownCloud / Nextcloud APIs for it that could be used for QOwnNotes... Since when do this APIs exist and is there a documentation in both projects?

**Comment by brainchild0** [comment]
There is limited documentation in [the developer manual](https://docs.nextcloud.com/server/stable/developer_manual/).  See the _Client APIs_ section.  It may not be enough detail to resolve the answer, though.  Development appears to be very active with documentation lagging behind.

**Comment by pbek** [comment]
I guess then qownnotesapi would be a safe bet. :)

**Comment by brainchild0** [comment]
I understand.  The question may be worth reconsidering in the future, but stability and clarity of the current interface is a valid concern.
