### ISSUE TITLE
Mac Won't Shut Down

### ISSUE THREAD

**Issue by bisherbas** [pbek/QOwnNotes#1113]
Help menu didn't work so I am submitting the issue directly from GitHub.

`QOwnNotes - version 19.1.2 - Travis CI - build 4056`
`Mac Mojave 10.14.2`

Shut down on my Macbook Air fails when the app is open or minimized. Notes are synced to my own Nextcloud server. Otherwise everything else works fine.

![image](https://user-images.githubusercontent.com/42714627/51095872-e0232680-1785-11e9-89d1-e8442fdae295.png)

**Comment by pbek** [comment]
Can you please post the output from the debug settings.
And is there any useful log output if you enable the log widget?
Can you quit QOwnNotes by hand?

**Comment by bisherbas** [comment]
1. Can you tell me how to acquire the debug output? I see `[debug]` lines in the log widget but none of them are relevant to the issue at hand.
2. Log widget doesn't show anything out of ordinary.
3. Yes.

Two additional pieces of information:

1. One of my notes have an image embedded:

`![sample image](file://media/1506515572.png)`

2. macOS's built-in firewall is enabled. I have already clicked on the `Allow` button upon starting the app several times. But each time I launch the app, the same popup appears (see below).

![image](https://user-images.githubusercontent.com/42714627/51150747-cc36fd80-1835-11e9-8223-6f85b8e7825d.png)

As you seen below in the firewall settings, the app is already allowed incoming connections. Odd that I am asked to allow every time I start the app. This issue is not present with the other apps like Firefox, Skype etc.

![image](https://user-images.githubusercontent.com/42714627/51150793-02747d00-1836-11e9-8ab2-0a5cb722fd3b.png)

**Comment by pbek** [comment]
> Can you tell me how to acquire the debug output? I see [debug] lines in the log widget but none of them are relevant to the issue at hand.

the issue template explained two methods 🙄 😉 

> As you seen below in the firewall settings, the app is already allowed incoming connections.

I don't know what is happening on your computer, but one thing that comes to mind is that there is an ongoing network connection in QOwnNotes that is blocking the shutdown...

**Comment by pbek** [comment]
> firewall

if you want to be sure you would need to shut down your firewall and try again...

**Comment by pbek** [comment]
That seems to be a side effect of "minimize on close" for #1098, I can only turn that off again, any thoughts @Letterus and @acbalingit?

**Comment by pbek** [comment]
macOS seems to send the same event for the "Quit" on the application icon and the "x" on the window, so I can only remove both. If anyone wants to improve on that, I'm open for pull requests.

**Comment by Letterus** [comment]
I'll have a look into it if I find some time. It seems quit actions should call a different event than "x" on the window. Probably you are catching both using the same method?

> By default on the Mac, Qt will create an Apple Menu | Quit if a menubar doesn't exist with either quit or exit entry. That default created entry will call QApplication::quit() which will not trigger your MyWindow::closeEvent().

https://stackoverflow.com/questions/23274983/qt-mainwindow-closeevent-mac-cmdq

**Comment by pbek** [comment]
## 19.1.10
- disabled the application hiding of [#1098](https://github.com/pbek/QOwnNotes/issues/1098),
  because the close event is also fired when the application will be quit in
  the dock menu on macOS

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Letterus** [comment]
> I will later try if there is a way to distinguish the events

That would be nice, thank you.

> 
> > I don't know what this is for, is it possible to disable this server using the settings?
> 
> there already is

Thanks for that hint, I did not know that. When I disable the websocket server I do not get that message anymore!

**Comment by pbek** [comment]
> When I disable the websocket server I do not get that message anymore!

you shouldn't do that, you should try the browser extension https://chrome.google.com/webstore/detail/qownnotes-web-companion/pkgkfnampapjbopomdpnkckbjdnpkbkp :laughing:

**Comment by Letterus** [comment]
That addon sounds really great (in fact I manage most bookmarks using QOwnNotes and not using Firefox), but I think I will have to find a way to get rid of this annoying message then. It keeps popping up even if I manually allow incoming connections using the firewall settings.

**Comment by pbek** [comment]
> That addon sounds really great 

you may want to take a look at https://www.qownnotes.org/Knowledge-base/QOwnNotes-Web-Companion-browser-extension

> and not using Firefox

there also is a Firefox extension :wink: 

>  It keeps popping up even if I manually allow incoming connections using the firewall settings.

QOwnNotes starts a socket server at port 22222, you can also change that port.

**Comment by pbek** [comment]
> It keeps popping up even if I manually allow incoming connections using the firewall settings.

maybe a port below 1024 will sooth your firewall?

**Comment by Letterus** [comment]
> maybe a port below 1024 will sooth your firewall?

Good idea, that did it! But now I have a problem using the Firefox plugin. I set the port to 999 and it tells "Socket error: undefined" ;-)

**Comment by pbek** [comment]
> I set the port to 999 and it tells "Socket error: undefined" ;-)

I wasn't even allowed to start a socket server: `[10:19:03] [warning] "Could not start QOwnNotes server on port 999!"`. I just remembered that using privileged ports is not allowed for normal users on Linux. You also should have received that error message.

**Comment by pbek** [comment]
> I will later try if there is a way to distinguish the events

the events are the same :disappointed: I'll close this issue then...
