### ISSUE TITLE
macOS: an app from an unidentified developer

### ISSUE THREAD

**Issue by woj-tek** [pbek/QOwnNotes#1114]
Hi,
Would it be possible to distribute the app in a way that doesn't trigger " Open an app from an unidentified developer? (https://support.apple.com/kb/PH25088?locale=en_US)

There are two ways (I guess it relates to signing / having apple account?) and with correctly signed applications not from appstore there is a dialogue that informs that the app was downloaded from internet (i.e. not app-store) and I can confirm that I trust it and want to open it. In case of QOwnNotes however I have to go to preferences and confirm it there, which is kinda annoying (not that happy with overprotective osx…) and this wouldn't normally be the problem, but given the fast cadence of updates (every couple of days) I have to go to preferences basically every couple of days…

(I'm using brew so the app is updated automatically)

**Comment by nitishd** [comment]
You could install the app directly from the website instead of homebrew cask and let QOwnNotes internal updater take care of the updates. It doesn't trigger the security dialog on every new update.

**Comment by woj-tek** [comment]
Fair enough - I went ahead and switched to internal updater :-) I think this issue can be closed.
