### ISSUE TITLE
Assign/unassign tags by double-click

### ISSUE THREAD

**Issue by IzzySoft** [pbek/QOwnNotes#1116]
Had that on my list for years, now I finally installed this great app – thanks a lot!

Making myself known with the app it took me quite a while to figure how to add a tag to the currently open note – which I didn't find really intuitive:

#### Expected behaviour
Double-clicking on an existing tag assigns it to the currently open note (or un-assigns it if it was assigned).

#### Actual behaviour
Double-clicking a tag does nothing. After a while I realized I had to manually enter the tag name (even if the tag already exists) – which bears the risk of spelling errors and creation of "duplicate tags", apart from the "extra work" of typing.

Thanks for considering!

<sub>PS: I searched existing issues before opening this one – and find it hard to believe I didn't find a matching one. Apologies if I missed it/them!</sub>

**Comment by pbek** [comment]
Thank you for your kind words.

Right-clicking the tag in the tag tree also works (there you get a context menu). And there is even a own panel to assign tags with auto-completion. Right clicking the note also works. And you can tag via the scripting engine.

But I will see if your suggestion is in conflict with anything else. :)

**Comment by IzzySoft** [comment]
Thanks for your fast response!

> Right-clicking the tag in the tag tree

... confused me as "add tag" is ambiguous. As it's in the tag pane, I'd rather expect that to add a new tag without assigning it anywhere. Which is what it does: it asks me for a name with the title "add new tag". Do I miss something? All entries I can see in the context menu deal only with the tag itself: add a new one, rename, assign color, disable color, remove tag, move tags. (in case it matters: latest version, just downloaded today: 19.1.4)

> there is even a own panel to assign tags with auto-completion

Now that I have a few tags (and played a bit around), I found that (behind the "add tag" button). 😃 

> Right clicking the note also works.

Oh, please say in which pane – I was pretty confused about the different menu right-clicking in the edit panel 🤣 Yes, found that in the left panel then.

> But I will see if your suggestion is in conflict with anything else.

That'd be great, thanks!

**Comment by pbek** [comment]
Tags are already assigned with a double click on the tag in the tag-tree. Did that not work for you?

**Comment by IzzySoft** [comment]
No. I just tried again, no dice. This install is on Win10 if it matters.

**Comment by IzzySoft** [comment]
OK, I played with it a little – so let me clarify:

* double-clicking a tag that was NOT yet assigned to an open note indeed adds it to the note, BUT:
* while the tag shows up as attached in the lower-left corner, the number of notes using that tag (next to the tag in the tag tree) is NOT increased (correct number only shows up after restarting the application). It is however correctly DECREASED when removing the tag
* another double.click on the tag does NOT remove it from the open note

So it generally works – but if one is not (yet) familiar with QON, it's a bit confusing 😉

**Comment by pbek** [comment]
> while the tag shows up as attached in the lower-left corner, the number of notes using that tag (next to the tag in the tag tree) is NOT increased (correct number only shows up after restarting the application). It is however correctly DECREASED when removing the tag

yes, that's a tricky one, tricky to get around too

> another double.click on the tag does NOT remove it from the open note

I'm not sure if that feature would make sense to me, please use one of the other myriad ways to achieve that :laughing:

**Comment by pbek** [comment]
## 19.1.9
- if a tag in the *Tags panel* is double-clicked the current tag will not only
  be tagged with the clicked tag, but also the tag will be remove if it already
  was tagged with it

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
Great ;)

**Comment by IzzySoft** [comment]
Thanks again, Patrizio: I can confirm it works perfectly now! 👍

**Comment by pbek** [comment]
Great, thank you for testing!
