### ISSUE TITLE
Formatting of ordered lists with code in preview

### ISSUE THREAD

**Issue by IzzySoft** [pbek/QOwnNotes#1117]
#### Expected behaviour
The "leading numbers" of an ordered list all have the same size in preview.

#### Actual behaviour
If an item starts with "code" (in back-ticks), numbers are much smaller.

#### Steps to reproduce
Enter the folloing:

<pre>
1. Foo
2. `foobar`
3. Baz
</pre>

Look at the preview. It seems the number is taken into the "code". For completeness:

    4. baz `foobar`

will be rendered correctly; the problem only seems to appear if the first non-whitespace character after the "leading number" and its dot is the back-tick. Using `<code>` instead doesn't solve it, btw. To verify that this is *not* "normal Markdown behavior":

1. Foo
2. `foobar`
3. Baz

Screenshot:

![screenshot](https://i.imgur.com/Qwuvqhm.png)

Ugly when you need to write technical documentation 🙄 

Trying to take a closer look, the underlying problem seems to be that "preformatted text" is **NOT** zoomed (i.e. it stays small – say at 11px even if you zoomed the (other) text to 48px). But that's not the only thing: the "numbers" are not aligned either, zoomed or not (the *text* is, but the numbers of those "code items" are farther left than the others – and when zoomed in enough, first they are aligned and then farther right 😱 ).

**Comment by pbek** [comment]
I'm sorry, that is a "thing" of the `QTextBrowser` component of Qt and I think there are already issues filed for it... It can't be fixed in QOwnNotes.

**Comment by pbek** [comment]
I think #437 is about a similar problem.
