### ISSUE TITLE
Feature Request: copy paste highlighted text and images into QownNotes

### ISSUE THREAD

**Issue by offerlam** [pbek/QOwnNotes#112]
Hi, 

When i highlight text and images say a installation guide from a homepage or other media I only get the text pasted in QownNotes when i paste it. It would be nice if it took everything like pictures and such.

Also samething happens when doing this from Microsoft OneNote. This feature would be REALLY great for people who needs to migrate many pages in OneNote. OneNote has no export feature for this.

hope i made sense?

**Comment by pbek** [comment]
Thank you for your idea! That is certainly no easy feat to do, I will investigate.

**Comment by pbek** [comment]
Some work, but doable! :+1:

**Comment by offerlam** [comment]
GREAT! looking forward to test it!!.... in a couple of hours :P

**Comment by pbek** [comment]
Now implemented in v1.1.6, that is currently building:
- you can now **paste html** in notes with <kbd>Ctrl</kbd> + <kbd>⇧</kbd> + 
  <kbd>V</kbd>
  - html tags like `strong`, `b`, `em`, `i`, `a`, `h1`, `h2`, `h3`, `h4`, 
    `h5`, `br` will be translated to markdown
  - images from `img` tags will be downloaded and inserted as markdown images

Can you please be so kind and test if it works for you.

**Comment by offerlam** [comment]
testing now .. hold on

**Comment by offerlam** [comment]
as a test I highlighted this entire page

https://support.office.com/en-us/article/Download-and-install-or-reinstall-Office-365-Office-2016-or-Office-2013-on-your-PC-7a28382b-7015-4b5a-9d9b-650d15742c95

but pasting it in QownNotes removed all the formats.. and it didn't add the pictures either.. 

i simply copy pasted it into the edit tap of a new note and checked Markdown to see if it looked right.

**Comment by pbek** [comment]
The article worked here under OS X and Linux. How did you paste it? Did you use the `paste html and media` function?

**Comment by pbek** [comment]
@offerlam, I just tested with Google Chrome under Windows and it worked fine.
Although it didn't work with Internet Explorer. IE does things differently...
I tried to fix stuff now for IE in the current version 1.1.8, can you please test again.

**Comment by offerlam** [comment]
No i just used Ctrl c and than Ctrl v. Was that wrong?

Sendt fra min telefon med CyanogenMod

Den 11/03/2016 22.18 skrev Patrizio Bekerle <notifications@github.com>:

The article worked here under OS X and Linux. How did you paste it? Did you use the paste html and media function?

**Comment by pbek** [comment]
Please use <kbd>Ctrl</kbd> + <kbd>⇧</kbd> + <kbd>V</kbd>. Normal pasting pastes plain text, as it should be.

**Comment by offerlam** [comment]
Hi pbek,

sorry for the late respons.. i will test it ASAP this week. but im pretty hung today the next. But it seems i did it wrong...

**Comment by pbek** [comment]
Happy un-hunging. :)

**Comment by offerlam** [comment]
Hi pbek,

I have been so extreamly HUNG these two weeks :P <= ha ha, it  should have said hung up :)

I tested with CTRL + arrow up + V

It did keep some of the formatting.. i can see some of the text is different. but i didn't grap any pictures from the page.

I tested from the same page as above.. 

I went and highligted the page and went CTRL + C to copy

then i went to a new note in Qownnote and did CTRL + Arrow up + V first holding CTRL down. While holding it down i clicked arrow and holded that down ending with the V key in the same way.

**Comment by pbek** [comment]
<kbd>⇧</kbd> is the shift key. :)
Why don't you just use the menu entry? ,)

**Comment by offerlam** [comment]
embarrassing :P but i can take it :P hold on

**Comment by offerlam** [comment]
pbek: Mission Accomplished :) Despite weird Hung statements and literal conclusions of drawings

**Comment by pbek** [comment]
Great! :) Did it work now?
Have a love-ly day. :grin:

**Comment by offerlam** [comment]
yes it did :) on windows... :) now i just need to activate notes on my owncloud server and start the tedius copy process :)
