### ISSUE TITLE
Completing Tasks

### ISSUE THREAD

**Issue by tigexplorer** [pbek/QOwnNotes#1121]
#### Expected behavior
Completing a task may also on the server marked as completed.

#### Actual behavior
A completed task is removed from the task list, but not marked as completed on the server.
By reloading from the server, all previous as completed marked tasks are displayed again as not completed.

#### Steps to reproduce
Mark a task complete.

## General Info

**Current Date**: `Do. Jan. 24 17:35:33 2019`
**Version**: `19.1.8.1`
**Build date**: `Jan 23 2019`
**Build number**: `513`
**Platform**: `linux`
**Operating System**: `Ubuntu 16.04.5 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.5.1`
**Qt Version (runtime)**: `5.5.1`
**Portable mode**: `no`
**Settings path / key**: `/home/my/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/my/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `5`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://my.com/nextcloud`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `14.0.4.2`
**appVersion**: *empty*

#### Relevant log output in the Log panel
```
[Jan 24 17:25:11] [debug]: Reply from  "/nextcloud/remote.php/dav/calendars/my/mytodo/"
[Jan 24 17:25:11] [debug]: Reply from ownCloud calendar todo list page
[Jan 24 17:25:19] [debug]: on_todoList_itemChanged  - 'item':  0x8d658e0
[Jan 24 17:25:19] [debug]: generateNewICSData  - 'icsData before':  "BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:+//IDN bitfire.at//ical4android\r\nBEGIN:VTODO\r\nDTSTAMP:20180829T212318Z\r\nUID:384b055d-5905-45a5-bd11-bc7978c99eef\r\nCREATED:20180829T211612Z\r\nLAST-MODIFIED:20180829T211612Z\r\nSUMMARY:https://mytask\r\n im-signatur/\r\nSTATUS:NEEDS-ACTION\r\nEND:VTODO\r\nEND:VCALENDAR\r\n"
[Jan 24 17:25:19] [debug]: generateNewICSData  - 'icsData after':  "BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:+//IDN bitfire.at//ical4android\nBEGIN:VTODO\nPRIORITY:0\nDESCRIPTION:\nPERCENT-COMPLETE:100\nCOMPLETED:20190124T172519\nDTSTAMP:20180829T212318Z\nUID:384b055d-5905-45a5-bd11-bc7978c99eef\nCREATED:\nLAST-MODIFIED:\nSUMMARY:https://mytaskim-signatur/\nSTATUS:COMPLETED\nEND:VTODO\nEND:VCALENDAR\n"
[Jan 24 17:25:19] [debug]: postCalendarItemToServer  - 'body':  "BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:+//IDN bitfire.at//ical4android\nBEGIN:VTODO\nPRIORITY:0\nDESCRIPTION:\nPERCENT-COMPLETE:100\nCOMPLETED:20190124T172519\nDTSTAMP:20180829T212318Z\nUID:384b055d-5905-45a5-bd11-bc7978c99eef\nCREATED:\nLAST-MODIFIED:\nSUMMARY:https://mytaskim-signatur/\nSTATUS:COMPLETED\nEND:VTODO\nEND:VCALENDAR\n"
[Jan 24 17:25:19] [debug]: Reply from  "/nextcloud/remote.php/dav/calendars/my/mytodo/384b055d-5905-45a5-bd11-bc7978c99eef.ics"
[Jan 24 17:25:19] [warning]: "QNetworkReply error 299 from url https://myserver.com/nextcloud/remote.php/dav/calendars/my/mytodo/384b055d-5905-45a5-bd11-bc7978c99eef.ics: " "Error downloading https://myserver.com/nextcloud/remote.php/dav/calendars/my/mytodo/384b055d-5905-45a5-bd11-bc7978c99eef.ics - server replied: Unsupported Media Type"
[Jan 24 17:25:19] [debug]: Reply from ownCloud calendar item ics page
```

**Comment by pbek** [comment]
It guess you might want to take a look at #966 and https://github.com/pbek/QOwnNotes/issues?utf8=%E2%9C%93&q=Unsupported+Media+Type

**Comment by pbek** [comment]
I will close this issue until there is more information.
