### ISSUE TITLE
[I] Ugly fonts on macOS Mojave

### ISSUE THREAD

**Issue by lassana** [pbek/QOwnNotes#1123]
#### Expected behaviour

Fonts are rendered anti-aliased

#### Actual behaviour

No anti-aliasing in the app:
![screen shot 2019-01-26 at 4 55 59 pm](https://user-images.githubusercontent.com/2004960/51788224-9296b880-218c-11e9-980a-af02cf92100d.png)
![screen shot 2019-01-26 at 4 56 17 pm](https://user-images.githubusercontent.com/2004960/51788227-97f40300-218c-11e9-8f7e-79ba9bb98de2.png)

#### Steps to reproduce

1. Install QOwnNotes from Homebrew (I'm on MacBook Pro 13-inch, Mid 2012)
2. Start the app

#### Relevant log output in the Log panel

```

```

#### Information about the application, settings and environment

QOwnNotes Debug Information
===========================

<details><summary>Expand</summary>

## General Info

**Current Date**: `Sat Jan 26 17:00:47 2019`
**Version**: `19.1.9`
**Build date**: `Jan 26 2019`
**Build number**: `4106`
**Platform**: `macosx`
**Operating System**: `macOS 10.14`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.12.0`
**Qt Version (runtime)**: `5.12.0`
**Portable mode**: `no`
**Settings path / key**: `/Users/user/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/user/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `1`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-2`
**localPath**: `/Volumes/Documents/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/Volumes/Documents/Notes/notes.sqlite`

## Settings

** USB DISK 2/0** (QString): `1`
**646F6E7A_00000000_00000001_6E7A6361_696D6963** (qlonglong): `1`
**AKLastCheckInAttemptDate** (QDateTime): `2019-01-26T00:29:02.622`
**AKLastCheckInSuccessDate** (QDateTime): `2019-01-26T00:29:04.335`
**AKLastEmailListRequestDateKey** (QDateTime): `2019-01-16T17:23:14.236`
**AKLastIDMSEnvironment** (qlonglong): `0`
**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Alcor Micro Mass Storage Device** (QString): `1`
**Android Android** (QString): `1`
**CGDisableCursorLocationMagnification** (bool): `true`
**CGFontRenderingFontSmoothingDisabled** (bool): `false`
**Country** (QString): `US`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/vimMode** (bool): `false`
**FileDialog/LastPath** (QString): `/Volumes/Documents/legal/army`
**FileDialog/LastPath-InsertAttachment** (QString): `/Volumes/Documents/legal/army`
**General UDisk** (QString): `1`
**Google Android** (QString): `1`
**HUAWEI Mobile** (QString): `1`
**Huawei IDEOS X5** (QString): `1`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**JMicron Samsung M3 Portable** (QString): `1`
**JetFlash Mass Storage Device** (QString): `1`
**LastUpdateCheck** (QDateTime): `2019-01-26T16:54:14.623`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**Logitech HID compliant keyboard** (QString): `1`
**Logitech USB Receiver** (QString): `1`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (qlonglong): `32`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Monaco,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `.SF NS Text,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Monaco,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Sana,13,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.rtl** (bool): `false`
**MediaTek MT65xx Android Phone** (QString): `1`
**MessageBoxOverride/readonly-mode** (qlonglong): `1024`
**MultipleSessionEnabled** (bool): `false`
**NoteHistory-1** (QVariantList): `<variant list with 4 item(s)>`
**NoteHistoryCurrentIndex-1** (qlonglong): `3`
**PKSecureElementAvailableFlags** (qlonglong): `1`
**PKSecureElementAvailableFlagsByHost** (qlonglong): `1`
**PiwikClientId** (QString): `<hidden>`
**Samsung Electronics Co/, Ltd/ ML-1670 Series** (QString): `1`
**Samsung ML-1670 Series** (QString): `1`
**SearchEngineId** (qlonglong): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**SyncServicesServerWasActive** (bool): `true`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WebAutomaticSpellingCorrectionEnabled** (bool): `true`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**_HIHideMenuBar** (bool): `false`
**acceptAllExternalModifications** (bool): `false`
**allowDifferentNoteFileName** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `false`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (bool): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (qlonglong): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (qlonglong): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (bool): `true`
**disableAutomaticUpdateDialog** (bool): `false`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (bool): `true`
**enableSocketServer** (bool): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (qlonglong): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (qlonglong): `1024`
**imageScaleDownMaximumWidth** (qlonglong): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (qlonglong): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (qlonglong): `18`
**localTrash/autoCleanupDays** (qlonglong): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (qlonglong): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (qlonglong): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (qlonglong): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (qlonglong): `0`
**notesPanelOrder** (qlonglong): `0`
**notesPanelSort** (qlonglong): `1`
**notesPath** (QString): `/Volumes/Documents/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): *empty*
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (qlonglong): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloud/userName** (QString): *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (bool): `false`
**savedSearches/noteFolder-1** (QStringList): `Note 2019-01-26T16.55.48, Note 2019-01-26T16.48.09`
**showMenuBar** (bool): `false`
**showStatusBar** (bool): `true`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (qlonglong): `0`
**tagsPanelSort** (qlonglong): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `action_Quit`
**toolbar/5/name** (QString): `quitToolbar`
**toolbar/5/title** (QString): `quit toolbar`
**toolbar/6/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/6/name** (QString): `windowToolbar`
**toolbar/6/title** (QString): `window toolbar`
**toolbar/size** (qlonglong): `6`
**useUNIXNewline** (bool): `false`
**userMenuExtraStyle** (qlonglong): `0`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (qlonglong): `22222`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`
**xiaomi Redmi 3s** (QString): `1`

## System environment

**SHELL**: `/usr/local/bin/bash`
**LSCOLORS**: `ExFxBxDxCxegedabagacad`
**XPC_FLAGS**: `0x0`
**TERM_PROGRAM_VERSION**: `421.1`
**QT_LOGGING_RULES**: `qt.network.ssl.warning=false`
**SSH_AUTH_SOCK**: `/private/tmp/com.apple.launchd.Ogu4dnQp0Z/Listeners`
**TERM_SESSION_ID**: `EA99796B-FA85-4DEF-9B6C-2438E73968D5`
**EDITOR**: `/usr/local/bin/mate -w`
**PWD**: `/Users/user`
**LOGNAME**: `user`
**HOME**: `/Users/user`
**LANG**: `en_US.UTF-8`
**TMPDIR**: `/var/folders/tw/p2nlzmq56zb20vkg1dhvmzs40000gn/T/`
**CLICOLOR**: `1`
**ANDROID_NDK_HOME**: `/usr/local/share/android-ndk`
**DBUS_LAUNCHD_SESSION_BUS_SOCKET**: `/private/tmp/com.apple.launchd.u91ZoSeua8/unix_domain_listener`
**GEM_HOME**: `/Users/user/.gem`
**TERM**: `xterm-256color`
**USER**: `user`
**DISPLAY**: `/private/tmp/com.apple.launchd.2e3rlpGn6C/org.macosforge.xquartz:0`
**SHLVL**: `1`
**ANDROID_SDK_ROOT**: `/usr/local/share/android-sdk`
**XPC_SERVICE_NAME**: `0`
**Apple_PubSub_Socket_Render**: `/private/tmp/com.apple.launchd.XfbUFN0H2r/Render`
**PATH**: `/Users/user/.gem/bin:/usr/local/sbin:/usr/local/opt/openssl/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands`
**TERM_PROGRAM**: `Apple_Terminal`
**_**: `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**__CF_USER_TEXT_ENCODING**: `0x1F5:0:0`

</details>

**Comment by pbek** [comment]
Thank you for reporting. Seems to be a Qt thing. Haven't heard from that before. I think I will have to install Mojave to see for myself... (and btw. nice trick with `<details><summary>Expand</summary>`, I'll put that into the issue assistant :smile:)

**Comment by pbek** [comment]
Did you already play with settings like in <https://www.howtogeek.com/358596/how-to-fix-blurry-fonts-on-macos-mojave-with-subpixel-antialiasing/>?

And I wonder where all those settings in your dump that aren't originally from QOwnNotes come from...

**Comment by lassana** [comment]
@pbek yeah, it might be a Qt bug, I found a few similar reports on bugreports.qt.io although none of them is exactly what I see.

Yes, I have earlier set `CGFontRenderingFontSmoothingDisabled` to `false` by running `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`, it slightly improves font rendering on non-retina displays on macOS Mojave.

If I run `defaults write -g CGFontRenderingFontSmoothingDisabled -bool YES`, QOwnNotes looks better. Unfortunately, this setting changes font rendering in the whole system so it's not a workaround for me:

![screen shot 2019-01-26 at 5 20 09 pm](https://user-images.githubusercontent.com/2004960/51788394-b6f39480-218e-11e9-8c62-cb2272dd9411.png)

**Comment by pbek** [comment]
I just upgraded my MacBook Air 2014 to Mojave, QOwnNotes fonts look nice like before. So I cannot reproduce your issue...

**Comment by lassana** [comment]
FYI: in fact I can set `CGFontRenderingFontSmoothingDisabled` for QOwnNoets specifically:

   `defaults write com.PBE.QOwnNotes CGFontRenderingFontSmoothingDisabled -bool YES`

This is probably the best I can do for now.

**Comment by lassana** [comment]
The problem with the workaround from my last message is that now fonts are rendered not like in other apps. Here is the difference (QOwnNotes is on top, default macOS TextEdit is on bottom):

![screen shot 2019-01-27 at 1 54 57 pm](https://user-images.githubusercontent.com/2004960/51800063-2c1ca380-223b-11e9-91c3-afe4ea289e01.png)


As you can see, the text in QOwnNotes is slightly more narrow than in TextEdit. Well, this is what `CGFontRenderingFontSmoothingDisabled` actually does. The font I used to demonstrate the difference is Lucida Grande (13).

**Comment by pbek** [comment]
Is there anything I can do about it?

**Comment by lassana** [comment]
There's probably nothing to do, I believe it's a macOS bug.
I remembered another rendering issue I had earlier on Mojave: text selection with Graphite color simply didn't work. So I tried to change it and surprisingly I don't observe the font rendering issue in QOwnNotes anymore (regardless of value in `CGFontRenderingFontSmoothingDisabled` preference):
![screen shot 2019-01-28 at 10 04 37 am](https://user-images.githubusercontent.com/2004960/51819709-6f7f1c80-22e4-11e9-96e7-eb7f27f130cc.png)

**Comment by lassana** [comment]
@pbek FYI: I recently updated from 19.2 to 19.7 and now fonts in the app look fantastic, I barely see the difference between QOwnNotes and native Cocoa apps. Several weeks I got the same problem with the Anki app, and it was caused by [this Qt bug](https://bugreports.qt.io/browse/QTBUG-71946), apparently. Anyway, now it's resolved. Thank you for using the latest Qt 👍

**Comment by pbek** [comment]
Maybe it was a side effect from the high dpi stuff I did :cat:  and using the newest Qt also (almost) always help :smile:
