### ISSUE TITLE
Preview should respect the font background settings.

### ISSUE THREAD

**Issue by gerroon** [pbek/QOwnNotes#1124]
Hi

It would be nice if the preview actually respects the background settings of the editor fonts. 

Please see the image for what is going on. I removed all the background stuff from fonts because they just look ugly and distracting. Removing bg from fonts work in the editor but preview still shows them

![screenshot_2019-01-26_21-40-05](https://user-images.githubusercontent.com/8519469/51796201-99054e80-21e5-11e9-8598-6bd5d4c4ec76.png)

thanks

**Comment by gerroon** [comment]
Ok see this again









#### Expected behaviour
I expect both the editor and the preview to have the same look


#### Actual behaviour
Editor and the preview looks different. 


#### Steps to reproduce
* Open your editor text font settings.

* Choose the dakr theme and clone the it

* Now open the clone theme and remove backgrounds from all the fonts, so they do not render with any background


* Add some inline code in the editor now 


* Enable preview

Now you will see that how it looks in the editor is different than how it looks in the preview. In the preview pane it will still render lines with backgrounds like in the image


I am using

QOwnNotes - version 19.1.9 - Travis CI - build 4106
QOwnNotes is the notepad and todo list manager with markdown support for GNU/Linux, macOS® and Windows® (it is written in C++/Qt®), that works together with the notes application of ownCloud and Nextcloud. 
Built on Jan 26 2019 with Qt 5.6.2.

**Comment by pbek** [comment]
The styling of the preview doesn't have much to do with the edit pane. One is markdown the other shows html. There is a script in the script repository to alter the styling of the preview. 

Does this answer your question?

**Comment by gerroon** [comment]
Well sure, I see the logic, but the thing is that the final result looks ugly. 

I will try the script to see if I can leverage the preview a bit to what general look of the editor's.

thanks
