### ISSUE TITLE
[I] `script.triggerMenuAction(…, 0);` causes the menu item to toggle rather than uncheck

### ISSUE THREAD

**Issue by smokris** [pbek/QOwnNotes#1127]
#### Expected behaviour

When my script runs the command `script.triggerMenuAction("actionAllow_note_editing", 0);`, I'd like it to unconditionally uncheck the "Allow all note editing" menu item, always placing the editor into read-only mode.

#### Actual behaviour

Every time my script runs that command, the status toggles, so if the editor was already in read-only mode, it becomes writable.

#### Steps to reproduce

Run this script — the allow-editing status toggles every second, instead of staying off.

    import QtQml 2.0
    import QOwnNotesTypes 1.0
    
    QtObject {
    	property QtObject timer: Timer {
    		interval: 1000
    		repeat: true
    		running: true
    		onTriggered: {
    			script.triggerMenuAction("actionAllow_note_editing", 0);
    		}
    	}
    }

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
20:31:59] [scripting] loading script file: /Users/smokris/Library/Application Support/QOwnNotes/test.qml
[20:31:59] [status] The scripting engine was reloaded
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sun Jan 27 20:38:27 2019`
**Version**: `19.1.10`
**Build date**: `Jan 27 2019`
**Build number**: `4114`
**Platform**: `macosx`
**Operating System**: `macOS 10.14`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.12.0`
**Qt Version (runtime)**: `5.12.0`
**Portable mode**: `no`
**Settings path / key**: `/Users/smokris/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/smokris/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Users/smokris/Applications/Text Editor/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `2022`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `1`
**localPath**: `/Users/smokris/Dropbox/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/Users/smokris/Dropbox/Notes/notes.sqlite`

### Script `test`

**id**: `1`
**path**: `/Users/smokris/Library/Application Support/QOwnNotes/test.qml`
**variablesJson**: *empty*

## Settings

**AKLastCheckInAttemptDate** (QDateTime): `2019-01-27T19:29:00.062`
**AKLastCheckInSuccessDate** (QDateTime): `2019-01-27T19:29:00.804`
**AKLastEmailListRequestDateKey** (QDateTime): `2019-01-24T16:20:31.588`
**AKLastIDMSEnvironment** (qlonglong): `0`
**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**ContextMenuGesture** (qlonglong): `0`
**DataDetectorsSettings** (QVariantMap): *empty*
**DataDetectorsUI** (QVariantMap): *empty*
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**DistractionFreeMode/isEnabled** (bool): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (qlonglong): `0`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-9c24397c-3122-4a0d-bc05-1989bdc7fa01`
**Editor/autoBracketClosing** (bool): `false`
**Editor/autoBracketRemoval** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `false`
**Editor/vimMode** (bool): `false`
**acceptAllExternalModifications** (bool): `false`
**allowDifferentNoteFileName** (bool): `true`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `false`
**appMetrics/disableAppHeartbeat** (bool): `true`
**appMetrics/disableTracking** (bool): `true`
**appMetrics/notificationShown** (bool): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (qlonglong): `1`
**currentWorkspace** (QString): `cf7302f4-745d-4c5e-b09a-f004c9739b67`
**cursorWidth** (qlonglong): `2`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `true`
**darkModeColors** (bool): `true`
**darkModeTrayIcon** (bool): `true`
**defaultNoteFileExtension** (QString): `txt`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `true`
**dockWasInitializedOnce** (bool): `true`
**enableSocketServer** (bool): `false`
**externalEditorPath** (QString): `/Users/smokris/Applications/Text Editor/TextMate_2.0-rc.16.app`
**fullyHighlightedBlockquotes** (bool): `true`
**gitCommitInterval** (qlonglong): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**iTunesVersionCheck** (double): `1268887680`
**ignoreAllExternalModifications** (bool): `true`
**ignoreAllExternalNoteFolderChanges** (bool): `true`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (qlonglong): `1024`
**imageScaleDownMaximumWidth** (qlonglong): `1024`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (qlonglong): `11`
**interfaceLanguage** (QString): *empty*
**interfaceStyle** (QString): `macintosh`
**internalIconTheme** (bool): `false`
**itemHeight** (qlonglong): `20`
**localTrash/autoCleanupDays** (qlonglong): `30`
**localTrash/autoCleanupEnabled** (bool): `false`
**localTrash/supportEnabled** (bool): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (bool): `true`
**mouseDriverPrevOptionKeyToggle** (bool): `false`
**navigationPanelHideSearch** (bool): `true`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (qlonglong): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (qlonglong): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (qlonglong): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (qlonglong): `0`
**notesPanelOrder** (qlonglong): `0`
**notesPanelSort** (qlonglong): `0`
**notesPath** (QString): `/Users/smokris/Dropbox/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): *empty*
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (qlonglong): `1`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloud/userName** (QString): *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `28b0ab63-4ace-4842-a2cd-5d21b82ceca8`
**restoreCursorPosition** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `cmake, test, ruori 2019, visualists, epylog, qt widge, youtube-dl, rebase, lynne, preproces, qown, Luddism, unnecess, humanoid, typora, portlan, dsl, 10.14, unwind, libunw, CPU Thermal Throttling, GPU Load, pmset, C++ Named Parameters, postgres, VCV Rack, wraith, cats, benchmark, p`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**tagWasAddedToNote** (bool): `true`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `true`
**tagsPanelOrder** (qlonglong): `0`
**tagsPanelSort** (qlonglong): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (qlonglong): `6`
**useUNIXNewline** (bool): `false`
**userMenuExtraStyle** (qlonglong): `2`
**webSocketServerService/port** (qlonglong): `22222`
**workspace-28b0ab63-4ace-4842-a2cd-5d21b82ceca8/name** (QString): `full`
**workspace-28b0ab63-4ace-4842-a2cd-5d21b82ceca8/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-28b0ab63-4ace-4842-a2cd-5d21b82ceca8/windowState** (QByteArray): `<binary data>`
**workspace-cf7302f4-745d-4c5e-b09a-f004c9739b67/name** (QString): `minimal`
**workspace-cf7302f4-745d-4c5e-b09a-f004c9739b67/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-cf7302f4-745d-4c5e-b09a-f004c9739b67/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `28b0ab63-4ace-4842-a2cd-5d21b82ceca8, cf7302f4-745d-4c5e-b09a-f004c9739b67`
</details>

**Comment by pbek** [comment]
## 19.1.11
- fixed checked state detection for scripting function `triggerMenuAction`
  (thank you @smokris)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by smokris** [comment]
Confirmed that it works in 19.1.11.  Thanks!

**Comment by pbek** [comment]
Great, thank you for fixing and testing!
