### ISSUE TITLE
Insert newlines along with code blocks

### ISSUE THREAD

**Issue by robled** [pbek/QOwnNotes#113]
Let' say I have this code in a note:

```
array=( one two three )
for i in "${arrayName[@]}"; do
   # do whatever on $i
done
```

If I highlight that text and press the "Insert code block" button, the tickmarks will be inserted at the beginning and end of existing lines like so:

```
`array=( one two three )
for i in "${arrayName[@]}"; do
   # do whatever on $i
done`
```

The next thing that a user may want to do is copy that code, but having the tick marks inserted on the same line as the code makes it hard to easily copy the code for use in other programs.  I suggest that a newline is added at the head and tail ends like the Github editor does:

```
`
array=( one two three )
for i in "${arrayName[@]}"; do
   # do whatever on $i
done
`
```

**Comment by pbek** [comment]
I'm not sure if this behaviour will improve the current situation. Not always the newlines would be nice to have when using *Insert code block*. What if you just want to use it inline?
As far as I can see it the GitHub editor also doesn't add newlines...
Or do you propose to just add newlines if the pasted text has at least one newline in it?

**Comment by pbek** [comment]
When inserting code blocks there will be added a new line on top and at the bottom of the selected text if the selected text has multiple lines in version 1.2.0.

**Comment by pbek** [comment]
Version 1.2.0 is now out, could you please be so kind and report back if it works for you, @robled?

**Comment by robled** [comment]
Works great, thank you!
