### ISSUE TITLE
Html export looks crappy :(

### ISSUE THREAD

**Issue by gerroon** [pbek/QOwnNotes#1130]
#### Expected behaviour
Well exported html that is readable

#### Actual behaviour
Jumbled html print with weird foreground background seperattion

#### Steps to reproduce

Copy the dark theme in the editor settings

Remove all the backgrounds from all the special texts , so no text is rendered with special bg

Enable the modified dark theme 

Add some code in a new note

Select all the code text and tab indent for 

Select the note and export as html

See the image for what I am getting here

#### Sample to try

	import bpy
	
	
	def update_func(self, context):
	    print("my test function", self)
	
	bpy.types.Scene.testprop = bpy.props.FloatProperty(update=update_func)
	
	bpy.context.scene.testprop = 11.0
	
	# >>> my test function <bpy_struct, Scene("Scene")>

#### System

Windows 10
QOwnNotes - version 19.1.9 - AppVeyor - build 4120
Built on Jan 26 2019 with Qt 5.11.2.
Copyright 2014-2019 by Patrizio Bekerle

I doubt the logging is relevant here

What I see with the .html export, sample  image

![firefox_qupyd1wock](https://user-images.githubusercontent.com/8519469/51815936-261ad700-22bc-11e9-9cb0-b5f4da311fd3.png)

**Comment by pbek** [comment]
Can you please add the exported html, since you are talking about the html export.

**Comment by gerroon** [comment]
sure

[property_update.py.html.zip](https://github.com/pbek/QOwnNotes/files/2801625/property_update.py.html.zip)

**Comment by gerroon** [comment]
https://paste.debian.net/hidden/6482a686/

**Comment by pbek** [comment]
It's not just about the settings....

```
<!--
If you are able to open the application the best way gather all needed
information and post questions, feature requests or issues is to use
the issue assistant in the "Help menu"!
```

alternatively:

```
The menu entry is named "Post questions, feature requests or issues".
-->

#### Output from the debug section in the settings dialog
```

**Comment by pbek** [comment]
Did you close this by accident?

**Comment by pbek** [comment]
## 19.1.11
- improved styling for note html export
    - adapted background colors for dark mode
- the note preview is now regenerated after the settings dialog is closed or the
  scripting engine is manually reloaded in the main menu, so that you immediately
  will see effects by scripts
- the `<body>` tag of the generated html of a note will now have a css class
  `preview` for the preview and and `export` for the export, so that you can more
  easily append different styles for the preview and export

**Comment by gerroon** [comment]
Thanks for the fixes. I will give it a spin. The bad news is that I think pdf had the same issue. Do you need a separate report for it?

**Comment by pbek** [comment]
> Do you need a separate report for it?

no, that is also fixed

**Comment by gerroon** [comment]
Thanks, sounds good.

**Comment by pbek** [comment]
There now is a new release (currently building), could you please test it and report if it works for you?

**Comment by gerroon** [comment]
sure, thanks for the heads up

**Comment by gerroon** [comment]
Hi

The html issue seems to be fixed but the issue still seems to be in the pdf version (attached)

[restart.py.pdf.zip](https://github.com/pbek/QOwnNotes/files/2805140/restart.py.pdf.zip)

**Comment by pbek** [comment]
the pdf export captures what is shown in the preview (or text edit), so this should be alright. or did you want to point me to something special?

**Comment by gerroon** [comment]
Well, the pdf(text) version is also the same? I assumed Pdf(text) captures the text edit pane, then should not it export like the Html export? 

I can see that the regular Pdf is aligned with the preview pane, but I personally expect that the text version is more aligned with the html version. But it is up to you, I merely reported it as inconsistency as  a user. feel free to close the bug, since my original report was about the html one.


thanks

**Comment by pbek** [comment]
The preview will never look like a html in the browser, because the preview is a QTextBrowser and no fully fledged browser. You could also use https://pandoc.org/ in a script to convert markdown to pdf. It does a pretty good job.
