### ISSUE TITLE
[I] Cmd+up doesn't jump to note start

### ISSUE THREAD

**Issue by bendem** [pbek/QOwnNotes#1131]
#### Expected behaviour

Typing cmd+up in the editor should set the cursor position to 1:1.

#### Actual behaviour

Typing cmd+up in the editor does nothing.

#### Steps to reproduce

Create a note, type some text, hit cmd+up, your cursor didn't move to 1:1 (Same thing for cmd+down)

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Jan 29 14:32:10 2019`
**Version**: `19.1.11`
**Build date**: `Jan 28 2019`
**Build number**: `4123`
**Platform**: `macosx`
**Operating System**: `macOS 10.14`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.12.0`
**Qt Version (runtime)**: `5.12.0`
**Portable mode**: `no`
**Settings path / key**: `/Users/benjamin/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/benjamin/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `1`
**Enabled scripts**: `5`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `3`

### Note folder `QNotes`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `-1`
**localPath**: `/Users/benjamin/Documents/QNotes`
**remotePath**: *empty*
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/Users/benjamin/Documents/QNotes/notes.sqlite`

### Note folder `Secure notes`

**id**: `2`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/Volumes/Keybase (benjamin)/private/bendem/QSecureNotes`
**remotePath**: *empty*
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/Volumes/Keybase (benjamin)/private/bendem/QSecureNotes/notes.sqlite`

### Script `Keybase Encryption`

**id**: `3`
**path**: `/Users/benjamin/Library/Application Support/PBE/QOwnNotes/scripts/encryption-keybase/encryption-keybase.qml`
**variablesJson**: 
```
{
    "kaybasePath": "/usr/local/bin/keybase",
    "kaybaseUser": "bendem"
}
```
**identifier**: `encryption-keybase`
**version**: `0.0.1`
**minAppVersion**: `17.05.7`

### Script `Support for PlantUML in notes`

**id**: `5`
**path**: `/Users/benjamin/Library/Application Support/PBE/QOwnNotes/scripts/render-plantuml/render-plantuml.qml`
**variablesJson**: 
```
{
    "javaExePath": "java",
    "plantumlJarPath": "/opt/softs/plantuml/plantuml.jar",
    "workDir": "/tmp"
}
```
**identifier**: `render-plantuml`
**version**: `0.0.4`
**minAppVersion**: `17.05.7`

### Script `Custom note preview styling`

**id**: `6`
**path**: `/Users/benjamin/Library/Application Support/PBE/QOwnNotes/scripts/preview-styling/preview-styling.qml`
**variablesJson**: 
```
{
    "customStylesheet": "img {\n  display: block;\n  max-width: 100%;\n}\n\npre { background-color: #333; }\ncode { background-color: transparent; }"
}
```
**identifier**: `preview-styling`
**version**: `0.0.2`
**minAppVersion**: `17.05.7`

### Script `Custom user interface styling`

**id**: `7`
**path**: `/Users/benjamin/Library/Application Support/PBE/QOwnNotes/scripts/custom-stylesheet/custom-stylesheet.qml`
**variablesJson**: 
```
{
    "customStylesheet": "#noteTextView {\n    padding: 1em 0.5em;\n}"
}
```
**identifier**: `custom-stylesheet`
**version**: `0.0.1`
**minAppVersion**: `17.05.7`

### Script `in-note-text-tagging`

**id**: `8`
**path**: `/Users/benjamin/projects/github/QOwnNotesScripts/in-note-text-tagging/in-note-text-tagging.qml`
**variablesJson**: 
```
{
    "putToBeginning": true,
    "tagHighlightColor": "#ffbbff",
    "tagMarker": "@"
}
```

## Settings

** USB DISK 2/0** (QString): `1`
** USB DISK 3/0** (QString): `1`
**646F6E7A_00000000_00000001_6E7A6361_696D6963** (qlonglong): `1`
**ADATA USB Flash Drive** (QString): `1`
**AKLastCheckInAttemptDate** (QDateTime): `2019-01-29T13:02:52.302`
**AKLastCheckInSuccessDate** (QDateTime): `2019-01-29T13:02:52.734`
**AKLastEmailListRequestDateKey** (QDateTime): `2019-01-29T13:02:21.673`
**AKLastIDMSEnvironment** (qlonglong): `0`
**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**AliTV Remote V1 Airmouse** (QString): `1`
**Arduino (www/arduino/cc) IOUSBHostDevice** (QString): `1`
**Burr-Brown from TI USB audio CODEC** (QString): `1`
**Canon iR1435** (QString): `1`
**Conexant CONEXANT USB AUDIO** (QString): `1`
**Country** (QString): `BE`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**DistractionFreeMode/editorWidthMode** (qlonglong): `2`
**DistractionFreeMode/isEnabled** (bool): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (qlonglong): `0`
**DistractionFreeMode/menuBarVisible** (bool): `false`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-9c24397c-3122-4a0d-bc05-1989bdc7fa01`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/vimMode** (bool): `false`
**Essential Products PH-1** (QString): `1`
**FileDialog/LastPath** (QString): `/Users/benjamin/Desktop`
**FileDialog/LastPath-ImportTextFiles** (QString): `/Users/benjamin/Documents/tmp-notes-transform`
**FileDialog/LastPath-NoteHTMLExport** (QString): `/Users/benjamin/Desktop`
**FileDialog/LastPath-NotePDFExport** (QString): `/Users/benjamin/Desktop`
**FileDialog/LastPath-ScriptPath** (QString): `/Users/benjamin/projects/github/QOwnNotesScripts/in-note-text-tagging`
**General USB Flash Disk** (QString): `1`
**Generic Mass Storage** (QString): `1`
**Hewlett Packard MFP M476dn** (QString): `1`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**JMicron USB to ATA·ATAPI Bridge** (QString): `1`
**LGE Nexus 5X** (QString): `1`
**LastUpdateCheck** (QDateTime): `2019-01-29T14:09:24.069`
**Lexar USB Flash Drive** (QString): `1`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**Logicool G430 Gaming Headset** (QString): `1`
**Logitech G430 Gaming Headset** (QString): `1`
**Logitech USB Receiver** (QString): `1`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (qlonglong): `12`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Hack,18,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Hack,18,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Hack,18,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Hack,18,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MainWindow/tagTreeWidgetExpandState-1** (QStringList): *empty*
**MessageBoxOverride/remove-notes** (qlonglong): `16384`
**MessageBoxOverride/remove-script** (qlonglong): `16384`
**MessageBoxOverride/remove-tag-from-notes** (qlonglong): `16384`
**MessageBoxOverride/remove-tags** (qlonglong): `16384`
**MessageBoxOverride/restore-note** (qlonglong): `16384`
**MessageBoxOverride/script-install-successful** (qlonglong): `1024`
**MessageBoxOverride/settings-shortcut-already-assigned** (qlonglong): `16384`
**MessageBoxOverride/tag-notes** (qlonglong): `16384`
**MessageBoxOverride/tag-removed-from-notes** (qlonglong): `1024`
**MessageBoxOverride/update-and-restart** (qlonglong): `16384`
**MultipleSessionEnabled** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 123 item(s)>`
**NoteHistory-3** (QVariantList): `<variant list with 1 item(s)>`
**NoteHistoryCurrentIndex-1** (qlonglong): `122`
**NoteHistoryCurrentIndex-3** (qlonglong): `0`
**PKSecureElementAvailableFlags** (qlonglong): `3`
**PKSecureElementAvailableFlagsByHost** (qlonglong): `3`
**PNY Transformer** (QString): `1`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**Philips USB Flash Drive** (QString): `1`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExportOrientation** (qlonglong): `0`
**Printer/NotePDFExportPageSize** (qlonglong): `4`
**Printer/NotePrinting** (QByteArray): `<binary data>`
**Realtek USB 10·100·1000 LAN** (QString): `1`
**Samsung CLX-3180 Series** (QString): `1`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (qlonglong): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-action_Encrypt_note** (QString): `⌘E`
**Shortcuts/MainWindow-action_Find_text_in_note** (QString): `⌘F`
**ShowSystemTray** (bool): `false`
**Sierra Wireless, Incorporated MC7304** (QString): `1`
**StartHidden** (bool): `false`
**TOSHIBA External USB 3/0** (QString): `1`
**TagAddDialog/geometry** (QByteArray): `<binary data>`
**USB Disk 2/0** (QString): `1`
**USB Flash Disk** (QString): `1`
**USBest Technology USB Mass Storage Device** (QString): `1`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**VASCO DIGIPASS 870** (QString): `1`
**VIA Technologies Inc/ USB 2/0 BILLBOARD** (QString): `1`
**WebAutomaticSpellingCorrectionEnabled** (bool): `true`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**Yubico Yubikey 4 OTP+U2F+CCID** (QString): `1`
**Yubico Yubikey NEO OTP+U2F+CCID** (QString): `1`
**acceptAllExternalModifications** (bool): `false`
**allowDifferentNoteFileName** (bool): `true`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `false`
**appMetrics/disableAppHeartbeat** (bool): `true`
**appMetrics/disableTracking** (bool): `true`
**appMetrics/notificationShown** (bool): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**com/logitech/akebono/loggingLevel** (QString): `3`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (qlonglong): `3`
**currentWorkspace** (QString): `initial`
**cursorWidth** (qlonglong): `2`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `true`
**darkModeColors** (bool): `true`
**darkModeTrayIcon** (bool): `true`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (bool): `true`
**disableAutomaticUpdateDialog** (bool): `false`
**disableSavedSearchesAutoCompletion** (bool): `true`
**dockWasInitializedOnce** (bool): `true`
**enableSocketServer** (bool): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `true`
**gitCommitInterval** (qlonglong): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): `git l`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (qlonglong): `1024`
**imageScaleDownMaximumWidth** (qlonglong): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (qlonglong): `16`
**interfaceLanguage** (QString): *empty*
**interfaceStyle** (QString): `macintosh`
**internalIconTheme** (bool): `true`
**itemHeight** (qlonglong): `20`
**localTrash/autoCleanupDays** (qlonglong): `7`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `true`
**networking/ignoreSSLErrors** (bool): `false`
**networking/proxyType** (qlonglong): `2`
**newNoteAskHeadline** (bool): `true`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (qlonglong): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (qlonglong): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (qlonglong): `0`
**notesPanelOrder** (qlonglong): `0`
**notesPanelSort** (qlonglong): `0`
**notesPath** (QString): `/Users/benjamin/Documents/QNotes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `true`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): *empty*
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (qlonglong): `2`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloud/userName** (QString): *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**recentNoteFolders** (QStringList): `/Users/benjamin/Documents/QNotes, /Volumes/Keybase (benjamin)/private/bendem/QSecureNotes`
**restoreCursorPosition** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Rock64 board, Server parts, Note 2019-01-25T09.07.36, IKEA, Note 2019-01-24T17.47.51, Write an integration testing tool build on the same principle as phpt, Write a terminal emulator, Write a scrapper to build a db of android apps searchable by name, category, rating, in-app purchase, Write a jfx frontend for keybase, Write a java, Write a custom nio filesystem for encrypted container files (just to see how nio works), What I want in a note taking program, WebGL, Web design, Untitled, Typescript native runtime, TowerJS (still not done), Tool to find similar files, Time machine cleanup, The future of GUI application is html∕css and a native backend, Testing, test, Test point in time, fs level, db backups, Sql modeler tool in jfx, Spark like prefix for git using libgit2, some cli tool that can given some command do stuff with both its stdout and its stderr, Social engineering, server names, Selectos, Read more about linear optimization (ask lol768 if needed), Protocols, Performance, One browser to rule them all, Notifications from weechat to phone, Next languages to learn, Network Stratego in C++ using GTK+-3, Native html∕js∕css thing, Mutualité et incapacité de travail, Modelize montains from height maps in 3D, MacOS Hubs, Learn how to package applications (deb∕rpm), Learn how to (C) libraries (so, lo, a, dll, JMH Benchmark resources, JFX app to merge javadocs with search features and everything, Java packaging, Introduction to maths for programmers, Interesting JS stuff, Implement control with unix socket in everything always, https& x3A;∕∕data, http& x3A;∕∕blog, GRPC, GPG Setup, get a fucking whiteboard, Generative art, Frontend library to connect to postgres without backend, Frontend css components, Encryption based sharing platform, Electronic signature, Easter egg in mumble, Downtime excuses, Docker, Data Science cheat sheet, Console calendar, Comics, Collaborative writing site, Code review, Chess AI, Checkout https& x3A;∕∕github, Check out what Turing did, Check if it'd be possible to stream using html5∕js only technology, BPMN, Blog posts to write, Backups, Attachments handling, Angular Component frameworks, Analytics, Accounting, A TCP reverse proxy that can be configured dynamically, 000 Old Wunderlist Tasks, Testing 2019-01-24T12.59.23, Web design 2019-01-24T12.59.21, Angular Component frameworks 2019-01-24T12.59.19, data, What I want in a note taking program 2019-01-24T12.59.16, blog, BPMN 2019-01-24T12.59.14, A TCP reverse proxy that can be configured dynamically 2019-01-24T12.59.13, Blog posts to write 2019-01-24T12.59.12, Data Science cheat sheet 2019-01-24T12.59.12, Generative art 2019-01-24T12.59.09, Code review 2019-01-24T12.59.08, JMH Benchmark resources 2019-01-24T12.59.07, Note 2019-01-23T16.43.08, Note 2019-01-23T16.32.46, Note 2019-01-23T16.32.27, Note 2019-01-23T16.31.54, Note 2019-01-23T16.24.31, Note 2019-01-23T16.24.15, Note 2019-01-23T16.23.53, Note 2019-01-23T16.23.29`
**showMenuBar** (bool): `false`
**showStatusBar** (bool): `true`
**taggingShowNotesRecursively** (bool): `true`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (qlonglong): `0`
**tagsPanelSort** (qlonglong): `0`
**toolbar/1/items** (QStringList): *empty*
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): *empty*
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): *empty*
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): *empty*
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (qlonglong): `6`
**useUNIXNewline** (bool): `true`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (qlonglong): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (bool): `false`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`
**©Microsoft Corporation Controller** (QString): `1`

## System environment

**BREW_PREFIX**: `/usr/local`
**AUTOJUMP_ERROR_PATH**: `/Users/benjamin/Library/autojump/errors.log`
**HOMEBREW_AUTO_UPDATE_SECS**: `7200`
**TMPDIR**: `/var/folders/5t/6hpmgtb91t15s5b9k_zj35ch0000gn/T/`
**LSCOLORS**: `Gxfxcxdxbxegedabagacad`
**TERM_PROGRAM**: `Apple_Terminal`
**MOSH_TITLE_NOPREFIX**: *empty*
**__CF_USER_TEXT_ENCODING**: `0x1F5:0:0`
**OLDPWD**: `/Users/benjamin`
**SHELL**: `/usr/local/bin/zsh`
**LESS**: `-R`
**QT_LOGGING_RULES**: `qt.network.ssl.warning=false`
**HOME**: `/Users/benjamin`
**PERL5LIB**: `/Users/benjamin/perl5/lib/perl5`
**LC_ALL**: `en_US.UTF-8`
**OPENSSL_LIB_DIR**: `/usr/local/opt/openssl@1.1/lib`
**_**: `/usr/bin/open`
**SSH_AUTH_SOCK**: `/private/tmp/com.apple.launchd.BzpzU2r7h2/Listeners`
**PAGER**: `less`
**GRADLE_OPTS**: `-Dmaven.repo.local=/Users/benjamin/.m2/repository`
**TERM_PROGRAM_VERSION**: `421.1`
**ANSIBLE_REMOTE_USER**: `benjamin.demarteau`
**SHLVL**: `2`
**TERM_SESSION_ID**: `B305534B-B3D6-470A-B09A-E0B6A2B06411`
**ZSH**: `/Users/benjamin/.oh-my-zsh`
**Apple_PubSub_Socket_Render**: `/private/tmp/com.apple.launchd.yus7FGkxOm/Render`
**EDITOR**: `nvim`
**DISPLAY**: `/private/tmp/com.apple.launchd.LQwPpJpsyo/org.macosforge.xquartz:0`
**TERM**: `xterm-256color`
**PERL_MB_OPT**: `--install_base "/Users/benjamin/perl5"`
**PATH**: `/usr/local/opt/openssl@1.1/bin:/Users/benjamin/perl5/bin:/Users/benjamin/Library/Haskell/bin:/Users/benjamin/Library/Python/3.7/bin:/Users/Benjamin/.cargo/bin:/Users/Benjamin/.bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin,:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/benjamin/tools/apache-cxf-3.1.12/bin`
**LOGNAME**: `benjamin`
**LC_CTYPE**: `UTF-8`
**XPC_SERVICE_NAME**: `com.PBE.QOwnNotes.31364`
**PERL_MM_OPT**: `INSTALL_BASE=/Users/benjamin/perl5`
**LANG**: `en_US.UTF-8`
**OPENSSL_DIR**: `/usr/local/opt/openssl@1.1`
**GRADLE_HOME**: `/usr/local/opt/gradle/libexec`
**AUTOJUMP_SOURCED**: `1`
**OPENSSL_INCLUDE_DIR**: `/usr/local/opt/openssl@1.1/include`
**PERL_LOCAL_LIB_ROOT**: `/Users/benjamin/perl5`
**USER**: `benjamin`
**XPC_FLAGS**: `0x0`
**PWD**: `/var/folders/5t/6hpmgtb91t15s5b9k_zj35ch0000gn/T/tmp.EX7C7JKR`
</details>

**Comment by pbek** [comment]
I'm not sure why that should be an issue, it's just how Qt's QPlainTextEdit behaves...

**Comment by bendem** [comment]
Would the keybinding be consider for inclusion as it will only affect mac users and won't surprise any of them since that's how it works in other text editing programs?

**Comment by bendem** [comment]
Alright, I'll look into it.

**Comment by pbek** [comment]
## 19.2.0
- enabled scrolling to top and bottom in the note text edit on macOS

**Comment by bendem** [comment]
Should I update manually or is it going through the release process?

**Comment by pbek** [comment]
There now is a new release (building), could you please test it and report if it works for you?

**Comment by bendem** [comment]
I confirm that this works.

**Comment by pbek** [comment]
Great, thank you for testing!
