### ISSUE TITLE
[I] Fetching of tasks does not work because the CalDAV URL that is generated is wrong

### ISSUE THREAD

**Issue by AMTQ** [pbek/QOwnNotes#1137]
#### Expected behaviour

Tasks should get fetched from CalDAV.

#### Actual behaviour

Calendars/Task-Lists from CalDAV are correctly shown, but no tasks can be created or downloaded. Consulting the log the issue seems clear:
[00:04:55] [warning] "QNetworkReply error 203 from url https://apps.kolabnow.com/calendars/xxx.yyy%40myfancyurl.tu/calendars/xxx.yyy@myfancyurl.tu/965b9cd6-5d1f-4627-bfe4-a64e7753eccb/: " "Error transferring https://apps.kolabnow.com/calendars/xxx.yyy%40myfancyurl.tu/calendars/xxx.yyy@myfancyurl.tu/965b9cd6-5d1f-4627-bfe4-a64e7753eccb/ - server replied: Not Found"

valid URL https://apps.kolabnow.com/calendars/xxx.yyy%40myfancyurl.tu/965b9cd6-5d1f-4627-bfe4-a64e7753eccb/
URL from QOwnNotes https://apps.kolabnow.com/calendars/xxx.yyy%40myfancyurl.tu/calendars/xxx.yyy@myfancyurl.tu/965b9cd6-5d1f-4627-bfe4-a64e7753eccb/

somehow there seems to be an issue with the creation of the URL after correctly identifying the existing task lists on the server.

#### Steps to reproduce

Opening configuration for Tasks:

(X) other CalDAV server
Calendar Basis-URL: https://apps.kolabnow.com/calendars/xxx.yyy@myfancyurl.tu
user: xxx.yyy@myfancyurl.tu
pass: *********

In the configuration window the existing task list is fetched and must be selected.

Try to load the tasks from the server (ctrl+shift+T), then the above log gets generated.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[00:04:55] [warning] "QNetworkReply error 203 from url https://apps.kolabnow.com/calendars/xxx.yyy%40myfancyurl.tu/calendars/xxx.yyy@myfancyurl.tu/965b9cd6-5d1f-4627-bfe4-a64e7753eccb/: " "Error transferring https://apps.kolabnow.com/calendars/xxx.yyy%40myfancyurl.tu/calendars/xxx.yyy@myfancyurl.tu/965b9cd6-5d1f-4627-bfe4-a64e7753eccb/ - server replied: Not Found"
[00:05:47] [status] 1 Notiz auf Datenträger gespeichert
[00:10:25] [status] 1 Notiz auf Datenträger gespeichert
[00:11:08] [status] 1 Notiz auf Datenträger gespeichert
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Do. Jan 31 00:14:28 2019`
**Version**: `19.1.11`
**Build date**: `Jan 28 2019`
**Build number**: `4137`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.11.2`
**Qt Version (runtime)**: `5.11.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\xxxxxxx\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `H:\Diverses\Notizen\QOwnNotes\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `de_CH`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `3`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Standard`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `H:\Diverses\Notizen\QOwnNotes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `H:\Diverses\Notizen\QOwnNotes\notes.sqlite`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2019-01-31T00:02:17.833`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `true`
**NoteHistory-1** (QVariantList): `<variant list with 2 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `1`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (int): `2`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Tasks`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `false`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (int): `15`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `H:/Diverses/Notizen/QOwnNotes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): *empty*
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `2`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): `https://apps.kolabnow.com/calendars/xxx.yyy@myfancyurl.tu`
**ownCloud/todoCalendarCalDAVUsername** (QString): `xxx.yyy@myfancyurl.tu`
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Aufgaben - Tasks_shared_xxxxxx » xxx, Tasks, Tasks_ML, Tasks_ML » Tasks_L, Tasks_ML » Tasks_M`
**ownCloud/todoCalendarEnabledList** (QStringList): `Aufgaben - Tasks_shared_xxxxx » xxx, Tasks, Tasks_ML, Tasks_ML » Tasks_L, Tasks_ML » Tasks_M`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://apps.kolabnow.com/calendars/xxx.yyy@myfancyurl.tu/5e49a323-164f-4306-a155-727495d3b105/, https://apps.kolabnow.com/calendars/xxx.yyy@myfancyurl.tu/965b9cd6-5d1f-4627-bfe4-a64e7753eccb/, https://apps.kolabnow.com/calendars/xxx.yyy@myfancyurl.tu/9b336f800549-cea7b5e95646-1fa74c5d/, https://apps.kolabnow.com/calendars/xxx.yyy@myfancyurl.tu/20ad7d4d-7993-4927-94ea-7244c73d9bcb/, https://apps.kolabnow.com/calendars/xxx.yyy@myfancyurl.tu/bf4a13c5-3f09-431e-b1fc-12132a6f2130/`
**ownCloud/todoCalendarUrlList** (QStringList): `https://apps.kolabnow.com/calendars/xxx.yyy@myfancyurl.tu/5e49a323-164f-4306-a155-727495d3b105/, https://apps.kolabnow.com/calendars/xxx.yyy@myfancyurl.tu/965b9cd6-5d1f-4627-bfe4-a64e7753eccb/, https://apps.kolabnow.com/calendars/xxx.yyy@myfancyurl.tu/9b336f800549-cea7b5e95646-1fa74c5d/, https://apps.kolabnow.com/calendars/xxx.yyy@myfancyurl.tu/20ad7d4d-7993-4927-94ea-7244c73d9bcb/, https://apps.kolabnow.com/calendars/xxx.yyy@myfancyurl.tu/bf4a13c5-3f09-431e-b1fc-12132a6f2130/`
**ownCloud/userName** (QString): *empty*
**restoreCursorPosition** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Hauptsymbolleiste`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `Formatierungs-Werkzeugleiste`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `Einfügen-Werkzeugleiste`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `Werkzeugleiste Verschlüsselung`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `Fenster-Werkzeugleiste`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `Beenden - Symbolleiste`
**toolbar/size** (int): `6`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\xxx\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `xxx-PC`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**FP_NO_HOST_CHECK**: `NO`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\xxx`
**INTEL_DEV_REDIST**: `C:\Program Files (x86)\Common Files\Intel\Shared Libraries\`
**LOCALAPPDATA**: `C:\Users\xxx\AppData\Local`
**LOGONSERVER**: `\\xxx-PC`
**MOZ_PLUGIN_PATH**: `C:\PROGRAM FILES (X86)\FOXIT READER\plugins\`
**NUMBER_OF_PROCESSORS**: `4`
**OneDrive**: `C:\Users\xxx\OneDrive`
**OPENSSL_CONF**: `C:\OpenSSL-Win32\bin\openssl.cfg`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32\mpirt;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32\compiler;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files (x86)\Common Files\Acronis\Timounter\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\OpenVPN\bin;C:\Program Files (x86)\Disconnect\Disconnect Desktop\openvpn\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\Program Files (x86)\LyX 2.2\Perl\bin;C:\WINDOWS\System32\OpenSSH\;C:\opencv;C:\Users\xxx\AppData\Local\Microsoft\WindowsApps;C:\android-sdk\platform-tools;C:\Users\xxx\AppData\Roaming\MiKTeX\2.9\miktex\bin\;C:\Program Files (x86)\Microsoft VS Code\bin;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 42 Stepping 7, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `2a07`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\`
**PUBLIC**: `C:\Users\Public`
**SBSIDir**: `C:\Program Files (x86)\Festo\SBS Vision Sensor`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\xxx\AppData\Local\Temp`
**TMP**: `C:\Users\xxx\AppData\Local\Temp`
**USERDOMAIN**: `xxx-PC`
**USERDOMAIN_ROAMINGPROFILE**: `xxx-PC`
**USERNAME**: `xxx`
**USERPROFILE**: `C:\Users\xxx`
**VS140COMNTOOLS**: `I:\ProgrammeInstall\Common7\Tools\`
**windir**: `C:\WINDOWS`
**windows_tracing_flags**: `3`
**windows_tracing_logfile**: `C:\BVTBin\Tests\installpackage\csilogfile.log`
</details>

**Comment by pbek** [comment]
I'm sorry, I'm not sure how I can help you, since you are using a custom caldav server.

**Comment by AMTQ** [comment]
Hi! It just seems that the method for generating the URL is inserting the same string

> calendars/xxx.yyy%40myfancyurl.tu

twice instead of only once. Maybe this is standard behavior for (other) CalDAV servers or CalDAV URLs, in this case all is well and it just does not work in my specific case. :(

**Comment by AMTQ** [comment]
Ah, never mind. With the new version 19.2 it works, thanks!

**Comment by pbek** [comment]
> Ah, never mind. With the new version 19.2 it works, thanks!

I wouldn't know why, nothing changed there :)

**Comment by AMTQ** [comment]
I know, I know, I read the changelog and could not find anything related 
to it...

But anyway, it looks like a really cool tool (QOwnNotes), thank you very 
much for making it available and maintaining it!

---
\\\\ AMTQ

Am 01.02.2019 07:08, schrieb Patrizio Bekerle:

**Comment by pbek** [comment]
Thank you for your kind words! :)
