### ISSUE TITLE
Feature Request: Insert pasted images in a resource folder

### ISSUE THREAD

**Issue by gerroon** [pbek/QOwnNotes#1138]
Hi

When I "copy" and paste an image from the browser (Firefox) into a markdown note , it paste a local url of the image (on Windows) from the %TEMP% which is fine. 

Open the link 
https://i.stack.imgur.com/rkr21.png

- Right Click on the image and "Copy Image" (not the link)

- Open a .md text file in QownN

- Paste

- It pastes something like this ``file:///C:/Users/USER/AppData/Local/Temp/rkr21.png` which is great, it copies the image locally.

The issue is that the pasted local image url is outside of the note folder, therefor it will never get synced or rendered. What would be nice is that, when such action is taken QOwnNotes actually creates something like ".pasted_resources" folder where the root note folder is, then copies the pasted resource into there, then creates a proper local link to it with an image tag so the document can be rendered properly.

Now you might say why not use "insert image" function from the tool bar? Well the pasted url's slashes are all reversed so Windows does not like it (say you pasted in the image browser window), the user has to edit the whole thing etc, creates  many additional steps to get it going. 

This could be as simple as pasting the image and done.

thanks

**Comment by pbek** [comment]
Can you please do me a favor and use the issue assistant from the help menu. That would make things a lot easier.

When I paste an image that way I get a link like `![media-Ujwpas](file://media/78678331.png)`. If that doesn't work for you you can also try to use `Paste html or media`.

**Comment by gerroon** [comment]
I just tested this on Linux and the result is like yours, so as expected I presume. However on Windows I get path from user's temp.


I will file a proper bug report  when I have time later. I did not think that it was a broken feature

**Comment by gerroon** [comment]
Sure but the thing is that the same "copy" that is in the clipboard produces an image in Gimp (pasted to empy document_ and  a resource in Joplin like `![c8023f220a4866ee277467681e5bd107.png](:/b941e9decb4e4212ac53c7c0a6672943)` which is rendered as an actual image in the rendered .md

So this could be a Windows platform related bug

**Comment by pbek** [comment]
Could be a Qt thing...

**Comment by pbek** [comment]
> Right Click on the image and "Copy Image" (not the link)

I just tested it under Windows 10 with Chrome and it worked for me.

**Comment by pbek** [comment]
I will close this issue until there is more information.
