### ISSUE TITLE
The colors in the diff dialog don't follow the "dark mode" setting

### ISSUE THREAD

**Issue by maples3** [pbek/QOwnNotes#1139]
# Expected behaviour
The red/green colors in the note history diff screen should change when "dark mode" is enabled.

# Actual behaviour
The red/green colors in the note history diff screen are too bright and are barely readable in dark mode.
![image](https://user-images.githubusercontent.com/15505712/52169951-82dc1e80-270e-11e9-824e-b2bf5153fdad.png)

# Steps to reproduce
Check "Enable Dark Mode" in the Interface settings.
Open a note and open the History panel
View the diff of the note

# Output from the debug section in the settings dialog
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sat Feb 2 17:25:36 2019`
**Version**: `19.2.0`
**Build date**: `Jan 31 2019`
**Build number**: `517`
**Platform**: `linux`
**Operating System**: `Debian GNU/Linux 9 (stretch)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.7.1`
**Qt Version (runtime)**: `5.7.1`
**Portable mode**: `no`
**Settings path / key**: `/home/anthony/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/anthony/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `30`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://anthonymapes.com/nextcloud`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `15.0.2.0`
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/anthony/anthony/documents/Notes`
**remotePath**: `Files/documents/Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/anthony/anthony/documents/Notes/notes.sqlite`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/vimMode** (bool): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2019-02-02T16:45:37`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 6 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `5`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `true`
**StartHidden** (bool): `true`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Personal`
**VersionDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowDifferentNoteFileName** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `true`
**darkModeColors** (bool): `true`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `txt`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableSocketServer** (bool): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `true`
**itemHeight** (int): `15`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `false`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `false`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `30`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/anthony/anthony/documents/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): `https://anthonymapes.com/nextcloud`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Personal, NKU Classes, Work, Newman`
**ownCloud/todoCalendarEnabledList** (QStringList): `Personal, NKU Classes, Work, Newman`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://anthonymapes.com/nextcloud/remote.php/dav/calendars/anthony/personal/, https://anthonymapes.com/nextcloud/remote.php/dav/calendars/anthony/nku-classes/, https://anthonymapes.com/nextcloud/remote.php/dav/calendars/anthony/work/, https://anthonymapes.com/nextcloud/remote.php/dav/calendars/anthony/newman/`
**ownCloud/todoCalendarUrlList** (QStringList): `https://anthonymapes.com/nextcloud/remote.php/dav/calendars/anthony/personal/, https://anthonymapes.com/nextcloud/remote.php/dav/calendars/anthony/nku-classes/, https://anthonymapes.com/nextcloud/remote.php/dav/calendars/anthony/work/, https://anthonymapes.com/nextcloud/remote.php/dav/calendars/anthony/newman/`
**ownCloud/userName** (QString): `anthony`
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `15.0.2.0`
**restoreCursorPosition** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useUNIXNewline** (bool): `false`
**versionSplitterSizes** (QByteArray): `<binary data>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**USER**: `anthony`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `1443`
**HOME**: `/home/anthony`
**DESKTOP_SESSION**: `LXDE`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**GTK_MODULES**: `gail:atk-bridge`
**QT_LINUX_ACCESSIBILITY_ALWAYS_ON**: `1`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**LOGNAME**: `anthony`
**XDG_SESSION_ID**: `2`
**SAL_USE_VCLPLUGIN**: `gtk`
**PATH**: `/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`
**GDM_LANG**: `en_US.utf8`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_MENU_PREFIX**: `lxde-`
**DISPLAY**: `:0`
**LANG**: `en_US.UTF-8`
**XDG_CURRENT_DESKTOP**: `LXDE`
**XDG_SESSION_DESKTOP**: `lightdm-xsession`
**XAUTHORITY**: `/home/anthony/.Xauthority`
**XDG_CONFIG_HOME**: `/home/anthony/.config`
**XDG_DATA_HOME**: `/home/anthony/.local/share`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm/data/anthony`
**SSH_AUTH_SOCK**: `/tmp/ssh-zoUCZ66qTQK0/agent.1410`
**SHELL**: `/bin/bash`
**GDMSESSION**: `lightdm-xsession`
**QT_ACCESSIBILITY**: `1`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**XDG_VTNR**: `7`
**PWD**: `/home/anthony`
**XDG_DATA_DIRS**: `/usr/local/share:/usr/share:/usr/share/gdm:/var/lib/menu-xdg:/usr/local/share/:/usr/share/:/usr/share/gdm/:/var/lib/menu-xdg/`
**_LXSESSION_PID**: `1410`
**XDG_CONFIG_DIRS**: `/etc/xdg`

# Relevant log output in the Log panel
```
[17:24:40] [status] Note versions are currently loaded from your ownCloud / Nextcloud server
[17:24:40] [debug] loadVersions - 'serverPath': "/Files/documents/Notes/Technology/New Laptop Todo.txt"
[17:24:41] [debug] Reply from "/nextcloud/index.php/apps/qownnotesapi/api/v1/note/versions"
[17:24:41] [debug] Reply from version list
[17:24:41] [status] Done with loading note versions
[17:24:48] [debug] storing note file: "New Laptop Todo.txt"
[17:24:48] [debug] stored note: Note: <id>17 <name>"New Laptop Todo" <fileName>"New Laptop Todo.txt" <noteSubFolderId>1 <relativePath>"Technology" <hasDirtyData>false
[17:24:48] [debug] storeUpdatedNotesToDisk - 'count': 1
[17:24:48] [status] Stored 1 note(s) to disk
```

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by maples3** [comment]
Yes!  The colors are much more readable now:
![image](https://user-images.githubusercontent.com/15505712/52309347-d7c9a000-296d-11e9-8213-da787f55624a.png)
Thanks!
