### ISSUE TITLE
Installation on Elementary OS

### ISSUE THREAD

**Issue by fotastisch** [pbek/QOwnNotes#114]
Hi!

QOwnNotes is awesome! I'm using it on Arch and Windows. Unfortunately I'm running into problems installing it on Elementary OS, which is based on Ubuntu 14.04. I followed the instructions for Ubuntu < 15.04, but receive the following errors:

W: Failed to fetch http://ppa.launchpad.net/pbek/qownnotes/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/pbek/qownnotes/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

Does anyone have any ideas (what I've done wrong ;))?

Thank you!

**Comment by pbek** [comment]
Thank you for your kind words, @fotastisch!

There is no package on Launchpad for Trusty because Launchpad can't build it because of the Qt 5.3+ dependencies.

If you install Qt 5.5 yourself you can either install the deb-Packages directly or use the Open Build Service repository at <https://build.opensuse.org/package/binaries/home:pbek:QOwnNotes/desktop?repository=xUbuntu_15.10>

**Comment by pbek** [comment]
I now added instructions on how to add the Ubuntu 15.10 repository from Open Build Service on <http://www.qownnotes.org/installation#Linux>.

Does this help you?

**Comment by fotastisch** [comment]
I think it does. I'll try tonight when I'm back home and post my results!

Thank you very much!

**Comment by pbek** [comment]
Until then... :grin:

**Comment by fotastisch** [comment]
Just a small update, I'm still working on it. ;) libqt5core5a and libstdc++6 are unmet dependencies, so now I'll try to figure out how to install them from the right repo.

**Comment by pbek** [comment]
Did you try the Ubuntu 15.10 repository? Too bad! Can you modify the install instructions to use 15.04 instead and try again?

**Comment by pbek** [comment]
Do you have any feedback or anything I can help you with, @fotastisch?

**Comment by fotastisch** [comment]
Hi!

Sorry for the late reply. So far I couldn't revert to the 15.04 repository and unfortunately I'm away from my PC right now. I'll get back working on it as soon as I can.

Thank you very much for your help!

**Comment by pbek** [comment]
Thank you for experimenting with it, @fotastisch!

**Comment by pbek** [comment]
Any news on this issue, @fotastisch?

**Comment by pbek** [comment]
I am closing this issue until there is feedback.
