### ISSUE TITLE
[Bug] Note lost after changing its title and switching to another note

### ISSUE THREAD

**Issue by liulex** [pbek/QOwnNotes#1142]
Steps to reproduce:
1. Change note A's **title**.
2. Before the auto save timer times out, switch to another note, say note B.
3. Wait until the auto save timer fires.
4. Change the content of note B.
5. Wait for the time out of the auto save timer.
6. Boom. Note A is lost!

![note_lost_bug](https://user-images.githubusercontent.com/2010459/52283366-4a05a900-299d-11e9-84b0-0febd67f8bc4.gif)

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue.

**Comment by pbek** [comment]
Phew, seems to be a complicated one. Some kind of race condition. At least the removed note appears in the local trash for me.

**Comment by pbek** [comment]
Seems to be this issue: #522

**Comment by liulex** [comment]
Yes, #522 is the same problem.
I just found a fix #1143. It works for me, but I'm not sure if it would cause other problems, could you please have a check?

**Comment by pbek** [comment]
## 19.2.2
- fixed lost note after changing its title and switching to another note
  (for [#522](https://github.com/pbek/QOwnNotes/issues/522) and
  [#1142](https://github.com/pbek/QOwnNotes/issues/1142), a big thank you to @liulex)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by liulex** [comment]
Yes, it's fixed now ;)

**Comment by pbek** [comment]
Thank you again for your help! :+1: You really did a great job in finding and fixing the bug!
