### ISSUE TITLE
Crash on fresh installation

### ISSUE THREAD

**Issue by liulex** [pbek/QOwnNotes#1146]
https://github.com/pbek/QOwnNotes/blob/dcae09602ecf2208c1c8d36541962764d63708cd/src/mainwindow.cpp#L120-L124

On fresh installation, this condition will be entered and Line 122 would cause a crash. since `_customActionToolbar` is not initialized.

**Comment by pbek** [comment]
Yeah, just saw that myself :)

**Comment by pbek** [comment]
Was introduced with #1135.

**Comment by pbek** [comment]
## 19.2.3
- fixed a crash on first start introduced with feature [#1135](https://github.com/pbek/QOwnNotes/issues/1135)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by liulex** [comment]
Yeah, fixed. 😄
