### ISSUE TITLE
[F] Support for letter-ordered lists

### ISSUE THREAD

**Issue by Airgunster** [pbek/QOwnNotes#1148]
#### Expected behaviour

Letter-ordered lists are recognized, i.e. if you press `ENTER` after `A)` it will automatically create `B)`,

Examples,

```
A) Text
B) Text
C) Text
```

```
a) Text
b) Text
c) Text
```

```
(a) Text
(b) Text
(c) Text
```

```
A. Text
B. Text
C. Text
```

```
a. Text
b. Text
c. Text
```

#### Actual behaviour

Not implemented, i.e. if you press `ENTER` after `A)` it just insert empty line.

#### Steps to reproduce

Type `A)` and press `ENTER`.
Type `a)` and press `ENTER`.
Type `(A)` and press `ENTER`.
Type `(a)` and press `ENTER`.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fri Feb 15 11:06:00 2019`
**Version**: `19.2.3`
**Build date**: `Feb 10 2019`
**Build number**: `4148`
**Platform**: `macosx`
**Operating System**: `macOS 10.14`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.12.0`
**Qt Version (runtime)**: `5.12.0`
**Portable mode**: `no`
**Settings path / key**: `/Users/user/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/user/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_IE`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `293`
**Enabled scripts**: `0`

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
Numbered lists are actually done in markdown like this:

```
1.  Bird
2.  McHale
3.  Parish
```

**Comment by pbek** [comment]
## 19.8.8
- added support for **automatic numbering and indentation of ordered lists**
    - if you press <kbd>Enter</kbd> after `1. a list item` you will get a `2. ` in the next line 
    - if you press <kbd>Enter</kbd> after `1. ` it will remove the current line 
    - if you press <kbd>Tab</kbd> after `1. ` it will indent the current line 
    - if you press <kbd>Shift</kbd> + <kbd>Tab</kbd> after `1. ` it will un-indent the current line

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by rakekniven** [comment]
Hey, great feature!

Will give it try tomorrow.
Missed it last friday ;-)

**Comment by pbek** [comment]
Did it work for you, @rakekniven? :smiley:

**Comment by rakekniven** [comment]
> 
> ## 19.8.8
> 
>     * added support for **automatic numbering and indentation of ordered lists**
>       
>       * if you press Enter after `1. a list item` you will get a `2. ` in the next line
>       * if you press Enter after `1. ` it will remove the current line
>       * if you press Tab after `1. ` it will indent the current line
>       * if you press Shift + Tab after `1. ` it will un-indent the current line

Tested it and works like expected. :+1:

**Comment by pbek** [comment]
Perfect, thank you!
