### ISSUE TITLE
Move notes to another folder

### ISSUE THREAD

**Issue by mlimacarlos** [pbek/QOwnNotes#115]
Hi @pbek, 

  Is it possible to move notes to another presset folder or open a file explorer? i can't change my recent notes directory. 

tks in advance, 
Marcos

**Comment by pbek** [comment]
If you set a new notes folder with *Note / Set notes folder* you should see a recent notes folder. Then you should also be able to move notes to it. Does this help you?

**Comment by mlimacarlos** [comment]
I select my notes folder but i cant see recent notes folder. For now i move file to archived notes directory inside notes folder. My recent notes directory is empty and i cant change this value.

**Comment by pbek** [comment]
Could you please post your **notesPath** and **recentNoteFolders** variables from the Debug tab in the settings?

And afterwards you can also find a button to delete your notes history in the settings dialog.

**Comment by mlimacarlos** [comment]
The information is below: 
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `ter mar 22 14:43:39 2016`
**Version**: `1.2.0`
**Build date**: `Mar 15 2016`
**Build number**: `120`
**Platform**: `linux`
**Operating System**: `Fedora 23 (Workstation Edition)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version**: `5.5.0`

## Server Info

**serverUrl**: `https://nuvem.sisgracom.com.br`
**appIsValid**: `no`
**connectionErrorMessage**: *empty*

## Settings

**LastUpdateCheck**: `2016-03-22T14:11:31`
**MainWindow/mainToolBar.iconSize**: `24`
**MainWindow/markdownDefaultViewMode**: `false`
**MainWindow/noteTextEdit.code.font**: `Courier,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `Cantarell,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `Courier,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `Cantarell,11,-1,5,50,0,0,0,0,0`
**MainWindow/showRecentNoteFolderInMainArea**: `true`
**PiwikClientId**: `<hidden>`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `false`
**appMetrics/notificationShown**: `true`
**cryptoKey**: `<hidden>`
**defaultNoteFileExtension**: `txt`
**disableAutomaticUpdateDialog**: `true`
**externalEditorPath**: *empty*
**interfaceLanguage**: *empty*
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `0`
**noteSaveIntervalTime**: `10`
**notesPath**: `/home/marcos/nuvem/Notas`
**notifyAllExternalModifications**: `false`
**ownCloud/localOwnCloudPath**: `/home/marcos/nuvem`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: `https://nuvem.sisgracom.com.br`
**ownCloud/todoCalendarBackend**: `1`
**ownCloud/todoCalendarEnabledList**: `admin`
**ownCloud/todoCalendarEnabledUrlList**: `https://nuvem.sisgracom.com.br/remote.php/calendarplus/calendars/admin/admin/`
**ownCloud/todoCalendarUrlList**: `https://nuvem.sisgracom.com.br/remote.php/calendarplus/calendars/admin/anivers%c3%a1rios/, https://nuvem.sisgracom.com.br/remote.php/calendarplus/calendars/admin/admin/`
**ownCloud/userName**: `admin`
**recentNoteFolders**: *empty*
**versionSplitterSizes**: `<binary data>`

**Comment by pbek** [comment]
Your **notesPath** is set, that's good. Your **recentNoteFolders** is empty, that means you haven't selected an other folder yet, did you?

**Comment by mlimacarlos** [comment]
Ok. Now i understand this!  Is there another way to select a folder without having to be entering a previous folder? if this folder was a pre selection?
These steps works ok with i needed, but it is confuse.
tks in advance, 
Marcos

**Comment by pbek** [comment]
> without having to be entering a previous folder

What do you mean by that?
You simply have to open the **Note** menu and select **Set notes folder**. The old folder will then be remembered and you can switch back and forth between the folders. You can also enable a setting to have a new select box with all your folders you every selected.

**Comment by mlimacarlos** [comment]
if instead a recent folder qownnotes have another function called preset folder. Usually i move notes from other directory categorized by subject. If i preset this folder instead memorize previous folder will be amazing! Now i have to enter in directory i want to move and set previous directory to memorize a recent folder. It is a suggestion that made my experience easiest.
I dont know what it is meaning from other users. 
tks in advance,
Marcos

**Comment by pbek** [comment]
Please tell me more about what the advantage of these *preset folder* would be over the current *recent folders* or how they work differently.

Somewhere in the future it will be possible to select folders alongside with their counterpart on your ownCloud server (for those who are using ownCloud). But since a lot of changes have to be made to make this possible you will have to stick with *recent note folders* for a while.

**Comment by mlimacarlos** [comment]
I see these advantages for preset folders instead a recent folders:

1. If you work with a high quantity of notes you can categorize by subject
or any criteria in directories.
2. Qownnotes run faster.
3. You can move you notes to another directory by preset folder without
entering that. (if qownnotes memorize a 5 presets, better)
5. preset directories allow you to move quick as shortcuts to categorize.
6. if link for media folder can be valid when you move to other folders
from owncloud root path, great! Media links and notes links doesn't work
when you move notes to another folder.
7. You increase organization methods.

i will send more...



Marcos de Lima Carlos
mail to: mlimacarlos@gmail.com
http://blog.sirandsir.com/  <http://blog.sirandsir.com/> - Blog da Sir & Sir
http://inventory.sirandsir.com/ - Sir&Sir inventory!

<http://www.sirandsir.com>


2016-03-22 15:57 GMT-03:00 Patrizio Bekerle <notifications@github.com>:

**Comment by pbek** [comment]
I'm very sorry, I still can't see the difference to what QOwnNotes is currently capable of doing. :smile_cat: 
You can do all that in the current state, including (6) because each notes folder has it's own media folder.
Can you please tell me what the difference should be in the user interface and technically.

**Comment by mlimacarlos** [comment]
OK. With recent notes i work fine. I divide my notes in categories directories indeed to make more easiest my organization. Preset directories diff from recent directories because i choose directories first. I don't needed to enter in directory and choose another for memorize it. But i don't know this resource util i open this issue. This works from me.

tks, 
Marcos

**Comment by pbek** [comment]
Can I summize that the current functionality works for you? :)

**Comment by mlimacarlos** [comment]
Yes.
