### ISSUE TITLE
Custom Stylesheet for selection-background-color not working on QTreeWidget

### ISSUE THREAD

**Issue by mleo2003** [pbek/QOwnNotes#1151]
I saw an earlier ticket (#399) that shows how to use selection-background-color to set different colors on selections, but for the QTextEdit area. However, I can't get it to work for that or QTreeWidget (where I really wanted it). According to https://doc.qt.io/qt-5/stylesheet-reference.html it should support this attribute.

Am I missing something with setting this up?

```
import QtQml 2.0

/**
 * This script adds custom styles to the application
 * 
 * You can get the object names from the *.ui files, for example
 * https://github.com/pbek/QOwnNotes/blob/develop/src/mainwindow.ui
 * 
 * Take a look at http://doc.qt.io/qt-5/stylesheet-reference.html for
 * a reference of what styles are available.
 */
QtObject {
    /**
     * Adds custom styles
     */
    function init() {
        // add a custom stylesheet to increase font size in the note list and set a font
        script.addStyleSheet("QTreeWidget#noteTreeWidget { selection-background-color: #073642; }");
    }
}
```

**Comment by pbek** [comment]
The style `QTreeWidget#noteTreeWidget { selection-background-color: #073642; }` worked for me in the `Custom user interface styling` script.

**Comment by mleo2003** [comment]
That's where I tried it first, and it isn't working for me. I tried it in Dark Mode first, but then again in regular (light) mode as well.

Could other scripts be messing with this? I don't think I have anything else different (some custom colors on a theme) that would affect this.

**Comment by pbek** [comment]
I can't tell, you didn't post what was asked in the issue template :)

**Comment by mleo2003** [comment]
Heh, sorry, was at work on that laptop, with not a lot of time.

I took some time this evening on my personal laptop, and changed my settings back to light color, not dark mode, etc., and only one script, the Custom user interface styling one with that line. No go.

So, I went nuclear: I deleted the registry key for all QOwnNotes, downloaded the latest version from the website, and ran the portable.bat for it. I added that one script, and the line you posted. Still nothing.

Here's the debug information for that install:


QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fri Feb 15 21:17:07 2019`
**Version**: `19.2.3`
**Build date**: `Feb 10 2019`
**Build number**: `4162`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.11.2`
**Qt Version (runtime)**: `5.11.2`
**Portable mode**: `yes`
**Settings path / key**: `C:/Users/mrobinson/Downloads/QOwnNotes/Data/PBE/QOwnNotes.ini`
**Application database path**: `C:\Users\mrobinson\Downloads\QOwnNotes\Data\QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes.exe`, `--portable`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `3`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `C:\Users\mrobinson\Downloads\QOwnNotes\Data\Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\mrobinson\Downloads\QOwnNotes\Data\Notes\notes.sqlite`

## Enabled scripts

### Script `Custom user interface styling`

**id**: `1`
**path**: `C:\Users\mrobinson\Downloads\QOwnNotes\Data\scripts\custom-stylesheet\custom-stylesheet.qml`
**variablesJson**: 
```
{
    "customStylesheet": "QTreeWidget#noteTreeWidget { selection-background-color: yellow; }"
}
```
**identifier**: `custom-stylesheet`
**version**: `0.0.1`
**minAppVersion**: `17.05.7`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**LastUpdateCheck** (QDateTime): `2019-02-15T21:13:38.839`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 3 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `2`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `false`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `15`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): *empty*
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloud/userName** (QString): *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\mrobinson\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPOSE_CONVERT_WINDOWS_PATHS**: `true`
**COMPUTERNAME**: `MATTHEW-LAPTOP`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DOCKER_CERT_PATH**: `C:\Users\mrobinson\.docker\machine\machines\default`
**DOCKER_HOST**: `tcp://192.168.99.100:2376`
**DOCKER_MACHINE_NAME**: `default`
**DOCKER_TLS_VERIFY**: `1`
**DOCKER_TOOLBOX_INSTALL_PATH**: `C:\Program Files\Docker Toolbox`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**FP_NO_HOST_CHECK**: `NO`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\mrobinson`
**LOCALAPPDATA**: `C:\Users\mrobinson\AppData\Local`
**LOGONSERVER**: `\\MATTHEW-LAPTOP`
**MOZ_PLUGIN_PATH**: `C:\PROGRAM FILES (X86)\FOXIT SOFTWARE\FOXIT READER\plugins\`
**NO_PROXY**: `192.168.99.100`
**NUMBER_OF_PROCESSORS**: `4`
**OneDrive**: `C:\Users\mrobinson\OneDrive`
**OPENSSL_CONF**: `C:\Users\mrobinson\scoop\apps\openssl\current\bin\cnf\openssl.cnf`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;c:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Calibre2\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Pandoc\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Pandoc\;C:\Users\mrobinson\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\mrobinson\AppData\Local\Programs\Python\Python37\;C:\Users\mrobinson\scoop\apps\openssl\current\bin;C:\Users\mrobinson\scoop\shims;C:\Users\mrobinson\AppData\Local\Microsoft\WindowsApps;C:\Users\mrobinson\AppData\Local\atom\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\mrobinson\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Docker Toolbox`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 69 Stepping 1, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `4501`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PROMPT**: `$P$G`
**PSModulePath**: `C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files (x86)\AutoIt3\AutoItX;C:\Program Files (x86)\AutoIt3\Beta\AutoItX`
**PUBLIC**: `C:\Users\Public`
**SCITE_USERHOME**: `C:\Users\mrobinson\AppData\Local\AutoIt v3\SciTE`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\MROBIN~1\AppData\Local\Temp`
**TMP**: `C:\Users\MROBIN~1\AppData\Local\Temp`
**USERDOMAIN**: `Matthew-Laptop`
**USERDOMAIN_ROAMINGPROFILE**: `Matthew-Laptop`
**USERNAME**: `mrobinson`
**USERPROFILE**: `C:\Users\mrobinson`
**VBOX_MSI_INSTALL_PATH**: `C:\Program Files\Oracle\VirtualBox\`
**VIM**: `C:\Users\mrobinson\scoop\apps\vim\current`
**windir**: `C:\WINDOWS`

**Comment by mleo2003** [comment]
What's really weird, is when I install that script, the default changes to the font family and size works just fine, so I know QOwnNotes sees the script and is loading it and applying styles. It just doesn't like the selection-background-color property for me.

**Comment by pbek** [comment]
Since you only have one script there should be no interference. I can't tell what's going on.

**Comment by mleo2003** [comment]
Yeah, I was trying to eliminate anything else that could have been breaking me, in hopes I was just doing something dumb. I'm also at a loss, other than this is just a Windows thing. I do see the color change for highlights when I swap from light theme to dark theme, and such, but I seem unable to do anything to it myself. Even was able to change the background color for those, just not selection-background-color.

Oh well, program still works wonderfully, not having a highlight color on one area is fine with me. Thanks for trying to help me with it.

**Comment by liulex** [comment]
@mleo2003 Try `QTreeView#noteTreeWidget::item:selected:active { background: #073642;}`

**Comment by mleo2003** [comment]
@liulex Thanks for the suggestion, but it also failed to work.

**Comment by iolivier87** [comment]
The topic is getting old but I used these custom styles successfuly : 
```
QTreeWidget#noteTreeWidget {color:#ffffff;}
QTreeWidget#noteTreeWidget::item:selected {background:#297acc;}
QTreeWidget#noteTreeWidget::item:hover {background:#80c0ff;color:#000000;}

QTreeWidget#noteSubFolderTreeWidget {color:#ffffff;}
QTreeWidget#noteSubFolderTreeWidget::item:selected {background:#297acc;}
QTreeWidget#noteSubFolderTreeWidget::item:hover {background:#80c0ff;color:#000000;}
QTreeWidget#noteSubFolderTreeWidget::item:open:!selected:!hover {color:#80c0ff;}
```
Would it be possible to have different colors for items in noteTreeWidget depending on whether they belong to a folder or a subfolder? It would make easier to sort the notes that were wrongly located at the root when the notes from subfolders are shown.

**Comment by pbek** [comment]
> Would it be possible to have different colors for items in noteTreeWidget depending on whether they belong to a folder or a subfolder?

I'm sorry, I don't know of a way to inject custom style attributes.

**Comment by iolivier87** [comment]
Ok, thank you for your reply.

**Comment by pbek** [comment]
I will close this issue until there is more information.
