### ISSUE TITLE
Auto-Format when trying to write a number that has a zero as second digit

### ISSUE THREAD

**Issue by bigbear42** [pbek/QOwnNotes#1152]
#### Expected behaviour
Typing a number like "2019" should just remain a number (did work before)

#### Actual behaviour

Auto-Format when trying to write a number that has a zero as second digit like e.g.  "2019"

#### Steps to reproduce
see attached screenshot

#### Output from the debug section in the settings dialog
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `So Feb 17 12:21:48 2019`
**Version**: `19.2.4`
**Build date**: `Feb 16 2019`
**Build number**: `4181`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.11.3`
**Qt Version (runtime)**: `5.11.3`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\xxxxxxx\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `I:\Users\xxxxxxx\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: `de`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `9`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://xxxecloud.de`
**appIsValid**: `yes`
**notesPathExists**: `not found`
**serverVersion**: `15.0.4.0`
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `2`

### Note folder `I:/Users/xxxxxxx/cloud`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `I:\Users\xxxxxxx\Cloud\Notes`
**remotePath**: `https://xxxecloud.de`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `I:\Users\xxxxxxx\Cloud\Notes\notes.sqlite`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `true`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `i:/Users/xxxxxxx/Documents/Atem-und-Stimmtechnik`
**FileDialog/LastPath-InsertImage** (QString): `i:/Users/xxxxxxx/Documents/Atem-und-Stimmtechnik`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2019-02-17T12:06:15.601`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/markdownDefaultViewMode** (QString): `false`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `true`
**NoteHistory-2** (QVariantList): `<variant list with 6 item(s)>`
**NoteHistoryCurrentIndex-2** (int): `5`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `2`
**currentWorkspace** (QString): `6f73b103-7b95-42db-93a9-4d958b37dd64`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `txt`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `false`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): `de`
**internalIconTheme** (QString): `false`
**itemHeight** (int): `15`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `false`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `I:/Users/xxxxxxx/Cloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/localOwnCloudPath** (QString): *empty*
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): `https://xxxecloud.de`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList** (QStringList): `default, familie`
**ownCloud/todoCalendarEnabledList** (QStringList): `default`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://xxxecloud.de/remote.php/dav/calendars/xxxxchef/default/`
**ownCloud/todoCalendarUrlList** (QStringList): `https://xxxecloud.de/remote.php/dav/calendars/xxxxchef/default/, https://xxxecloud.de/remote.php/dav/calendars/xxxxchef/familie/`
**ownCloud/userName** (QString): `xxxxchef`
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unbekannter Fehler`
**ownCloudInfo/notesPathExistsText** (QString): `not found`
**ownCloudInfo/serverVersion** (QString): `15.0.4.0`
**previousWorkspace** (QString): `1548499d-2c0b-4bd9-a37a-7962dd2a86a0`
**recentNoteFolders** (QStringList): `I:/Users/xxxxxxx/ownCloud/Notes`
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-2** (QStringList): `Note 2019-02-17T12.11.03, Note 2017-09-30T11.45.45, Note 2017-09-24T15.50.55, Note 2017-08-19T22.31.53, Note 2017-08-19T22.29.19`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Hauptsymbolleiste`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `Formatierungs-Werkzeugleiste`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `Einfügen-Werkzeugleiste`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `Werkzeugleiste Verschlüsselung`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `Fenster-Werkzeugleiste`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `Beenden - Symbolleiste`
**toolbar/size** (int): `6`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-1548499d-2c0b-4bd9-a37a-7962dd2a86a0/name** (QString): `Minimal`
**workspace-1548499d-2c0b-4bd9-a37a-7962dd2a86a0/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-1548499d-2c0b-4bd9-a37a-7962dd2a86a0/windowState** (QByteArray): `<binary data>`
**workspace-6f73b103-7b95-42db-93a9-4d958b37dd64/name** (QString): `Vollständig`
**workspace-6f73b103-7b95-42db-93a9-4d958b37dd64/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-6f73b103-7b95-42db-93a9-4d958b37dd64/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `6f73b103-7b95-42db-93a9-4d958b37dd64, 1548499d-2c0b-4bd9-a37a-7962dd2a86a0`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\xxxxxxx\AppData\Roaming`
**asl.log**: `Destination=file`
**CLASSPATH**: `.;C:\Program Files (x86)\Java\jre1.8.0_131\lib\ext\QTJava.zip`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `BLACKmxxxx`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\xxxxxxx`
**LOCALAPPDATA**: `C:\Users\xxxxxxx\AppData\Local`
**LOGONSERVER**: `\\BLACKmxxxx`
**MOZ_PLUGIN_PATH**: `C:\Program Files\Tracker Software\PDF Viewer\Win32`
**NUMBER_OF_PROCESSORS**: `4`
**OneDrive**: `C:\Users\xxxxxxx\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Python27\;C:\Program Files (x86)\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Calibre2\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Python27;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\WINDOWS\System32\OpenSSH\;C:\Users\xxxxxxx\AppData\Local\Microsoft\WindowsApps;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 60 Stepping 3, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `3c03`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Python27`
**PUBLIC**: `C:\Users\Public`
**QTJAVA**: `C:\Program Files (x86)\Java\jre1.8.0_131\lib\ext\QTJava.zip`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\xxxxxxx\AppData\Local\Temp`
**TMP**: `C:\Users\xxxxxxx\AppData\Local\Temp`
**USERDOMAIN**: `BLACKmxxxx`
**USERDOMAIN_ROAMINGPROFILE**: `BLACKmxxxx`
**USERNAME**: `xxxxxxx`
**USERPROFILE**: `C:\Users\xxxxxxx`
**windir**: `C:\WINDOWS`

#### Relevant log output in the Log panel

![2019-02-17 12_14_06-window](https://user-images.githubusercontent.com/15572017/52912172-0de01b80-32ae-11e9-9887-477eebfd1214.png)

**Comment by pbek** [comment]
I'm sorry, can't make out what you exactly are talking about.
In your screenshot you had 2019 typed and it wasn't formatted...

**Comment by liulex** [comment]
He means typing `0` gets <code>`</code>. It should be induced by https://github.com/pbek/qmarkdowntextedit/pull/15.
Are you using any keyboard mapping software? @bigbear42

**Comment by bigbear42** [comment]
No Keyboard mapping software, just a plain Win 10 setup. I even tested 
an alternative logitech K120 keyboard, just to make sure the wireless I 
am using is OK.

I have checked again and it is the "0" that starts it all.  A "0" is 
translated into ` `  even when starting a line with it. But if you have 
letter first the "0" remains a "0".


Am 18.02.2019 um 12:03 schrieb Le Liu:

**Comment by liulex** [comment]
@bigbear42 Thanks for testing! Finally I managed to reproduce it with the `0` in the numpad.
Now fixed in https://github.com/pbek/qmarkdowntextedit/pull/20. Please wait for a release.

**Comment by bigbear42** [comment]
The new release works fine. Thank you!

**Comment by pbek** [comment]
Great, thank you for testing!
