### ISSUE TITLE
Feature Request: keyboard shortcut to navigate "note folder" panel subfolders

### ISSUE THREAD

**Issue by Gregory-K** [pbek/QOwnNotes#1153]
QOwnNotes has excellent support for keyboard shortcuts, except for this little thing that asks for mouse action.  
I searched at `settings`, at https://www.qownnotes.org/shortcuts/QOwnNotes, previous issues and the scripts repository and I didn't find a solution.

Is it possible to add keyboard shortcuts to navigate the "note folder" panel subfolders? 
Something equivalent to the `alt+up/down` for the notes list panel it would be useful, I think.  
...or, when using the shortcut to select "note folder", it could be possible to "escape" to the subfolder list bellow...

Thanks anyway for your time.

**Comment by pbek** [comment]
Thank you for your suggestion. Maybe there will be a shortcut for reaching the note sub-folder panel in the future.

**Comment by pbek** [comment]
## 19.3.2
- there are now shortcuts to jump to the *note list* (<kbd>F5</kbd>), the *note subfolder panel* (<kbd>F6</kbd>) and the *tags panel* (<kbd>F7</kbd>)
    - please visit [QOwnNotes shortcuts](https://www.qownnotes.org/shortcuts/QOwnNotes) for a list of all shortcuts

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Gregory-K** [comment]
Tested and is working fine, thanks.

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by Gregory-K** [comment]
Sorry ...  

MacOS: Working  

Windows: not working and I cannot find the shortcut in settings
(tested twice by downloading a fresh copy and running it as portable)

Linux: n/a, only CLI

**Comment by pbek** [comment]
> Windows: not working and I cannot find the shortcut in settings

https://ci.appveyor.com/project/pbek/qownnotes/builds/23160409/job/slwkfcgbgx0jdwu6 is not done yet building version 19.3.2, please try again later...

**Comment by Gregory-K** [comment]
I thought of that (not built yet). OK, I 'll test it when it's done, although I have no reason to believe it won't work like on the other OSs.

**Comment by Gregory-K** [comment]
Windows: Working (v19.3.3)
