### ISSUE TITLE
Feature request: Shortcut for creating subfolder

### ISSUE THREAD

**Issue by gerroon** [pbek/QOwnNotes#1154]
Hi

It seems like creating a subfolder is not listed as a shortcut option under the shorcut editor. It would be nice to be able to define a shortcut for this function, otherwise the only option is to open the folders panel and right click to create a subfolder.

thanks

**Comment by pbek** [comment]
Thank you for your suggestion.
Doesn't note sub-folder always need a parent? Maybe using #1153 to get to the panel and then use the context menu of a sub-folder would be the better choice.

**Comment by gerroon** [comment]
Well sure it needs a parent. But if the parent is already selected, would not it be just easier to create a subofolder with  a shortcut easier?

**Comment by pbek** [comment]
#1153 is now implemented. So you could use use a *context menu* key to add a new subfolder. Unfortunately I wasn't able to emulate such a key for all who don't have such a key on their keyboard. :disappointed:

**Comment by pbek** [comment]
finally...

## 19.3.3
- you now can activate the context menu of the current widget with the shortcut <kbd>F10</kbd>
    - please visit [QOwnNotes shortcuts](https://www.qownnotes.org/shortcuts/QOwnNotes)
      for a list of all shortcuts

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
