### ISSUE TITLE
Feature Request: Show file extensions

### ISSUE THREAD

**Issue by gerroon** [pbek/QOwnNotes#1157]
Hi

It would be very nice if the note list pane actually shows the extensions, optionally. I looked around settings but I cant seem to spot such feature.

Basically the note list pane looks confusing if one has txt type files with different extensions. I guess it is ok if all one has .md but in a mixed folder it is hard to say what is .py or .txt or .log or even a .md etc

thanks

**Comment by pbek** [comment]
QOwnNotes is centered around notes, not files (like a file editor). Showing a file extension would need more bending, if the note filename can differ from the note headline (because notes are renamed in the note list).

**Comment by gerroon** [comment]
Sure but if the note is allowed to have its own name, this can work. Also it does not need to be like regular file.extension look. The extension can be shown as an icon or a tag etc.

**Comment by gerroon** [comment]
In any case it is just a suggestion, which can expand the use case.

**Comment by pbek** [comment]
## 19.8.1
- in the **note list** now the **note filename with extension** is showed in the
  **tooltips** instead of just the note name

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
