### ISSUE TITLE
ToDo list be and offline and sync

### ISSUE THREAD

**Issue by Servh37** [pbek/QOwnNotes#1158]
#### Expected behaviour
- to allow the Todo list to be accessible of line and not a direct connect to Nextcloud.
- possible to save to local PC and sync back to nextcloud once be online.

#### Actual behaviour
will only work when you are online and have a connection to Nextcloud.

**Comment by pbek** [comment]
I'm sorry. That will likely never be possible. The whole process depends on the WebDAV communication.

**Comment by Servh37** [comment]
All good if no one ask we will never know.
