### ISSUE TITLE
massive write I/O while starting 

### ISSUE THREAD

**Issue by GregorB54321** [pbek/QOwnNotes#1159]
#### Expected behaviour
only moderate or even no writings to storage while starting the application

#### Actual behaviour
massive I/O while starting

#### Steps to reproduce
sudo apt install iotop
sudo iotop  -o -a
QOwnNotes
or: strace -e pwrite64  QOwnNotes

#### Output from the debug section in the settings dialog
attached
[QOwnNotes.log.txt](https://github.com/pbek/QOwnNotes/files/2917685/QOwnNotes.log.txt)
[QOwnNotes Debug Information.md.txt](https://github.com/pbek/QOwnNotes/files/2917686/QOwnNotes.Debug.Information.md.txt)

#### Relevant log output in the Log panel
```
  TID  PRIO  USER     DISK READ  **DISK WRITE**  SWAPIN     IO>    COMMAND          
23308 be/4 gregor        0.00 B    **588.39 M**  0.00 % 56.68 % QOwnNotes
```

**Comment by pbek** [comment]
Nothing comes to mind what could cause this...
Maybe your todo lists are causing it, could you please turn off all todo list calendars in the settings and try again

**Comment by pbek** [comment]
I will close this issue until there is more information.
