### ISSUE TITLE
Compilation error on arm

### ISSUE THREAD

**Issue by octogene** [pbek/QOwnNotes#116]
Since 1.2.1, compiling QOwnNotes on raspbian jessie returned this error : 

> g++ -c -pipe -fPIC -fpermissive -finline-functions -Wno-long-long -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIE -DBOTAN_DLL= -DBOTAN_TARGET_OS_HAS_GETTIMEOFDAY -DBOTAN_HAS_ALLOC_MMAP -DBOTAN_HAS_ENTROPY_SRC_DEV_RANDOM -DBOTAN_HAS_ENTROPY_SRC_EGD -DBOTAN_HAS_ENTROPY_SRC_FTW -DBOTAN_HAS_ENTROPY_SRC_UNIX -DBOTAN_HAS_MUTEX_PTHREAD -DBOTAN_HAS_PIPE_UNIXFD_IO -DBOTAN_TARGET_OS_IS_LINUX -DBOTAN_TARGET_OS_HAS_CLOCK_GETTIME -DBOTAN_TARGET_OS_HAS_DLOPEN -DBOTAN_TARGET_OS_HAS_GMTIME_R -DBOTAN_TARGET_OS_HAS_POSIX_MLOCK -DBOTAN_HAS_DYNAMICALLY_LOADED_ENGINE -DBOTAN_HAS_DYNAMIC_LOADER -DBOTAN_BUILD_COMPILER_IS_GCC -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DQT_SCRIPT_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I. -Ilibraries -Ilibraries/qmarkdowntextedit -Ilibraries/qmarkdowntextedit -Ilibraries/qmarkdowntextedit -Ilibraries/piwiktracker -Ilibraries -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -isystem /usr/include/arm-linux-gnueabihf/qt5/QtSvg -isystem /usr/include/arm-linux-gnueabihf/qt5/QtWidgets -isystem /usr/include/arm-linux-gnueabihf/qt5/QtXml -isystem /usr/include/arm-linux-gnueabihf/qt5/QtScript -isystem /usr/include/arm-linux-gnueabihf/qt5/QtNetwork -isystem /usr/include/arm-linux-gnueabihf/qt5/QtSql -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I. -o botan.o libraries/botan/botan.cpp
libraries/botan/botan.cpp:46208:21: fatal error: cpuid.h: Aucun fichier ou dossier de ce type
   #include <cpuid.h>
                     ^
compilation terminated.
Makefile:1149: recipe for target 'botan.o' failed
make: *** [botan.o] Error 1

After some search i've found a fix by using this patch on botan library : https://codereview.qt-project.org/#/c/79728/1

Don't know if it's the best way to go but it actually works. Maybe a more recent version of the lib is needed ?

**Comment by pbek** [comment]
Thank you for reporting, I also saw that error yesterday on <https://build.opensuse.org/package/live_build_log/home:pbek:QOwnNotes/desktop/openSUSE_Factory_ARM/armv7l>

So far I wasn't aware that anyone actually is using QOwnNotes on ARM. :) :+1: 

As far as I remember QOwnNotes uses the latest stable Botan version.
It seems the patch got abandoned, is that a good or a bad sign? :grin: 

Thank you for your help!
I will test it later today! Of course by using it we will deviate from the original version of Botan...

**Comment by pbek** [comment]
I now used the botan version from <https://codereview.qt-project.org/#/c/79728/1>, it seems to work her on Intel 64bit Linux. The ARM worker on OBS is currently malfunctioning. Could you please try to build the develop branch of QOwnNotes on the Pi?

**Comment by octogene** [comment]
Compilation went fine :+1: 
QOwnNotes works, i didn't test it extensively but it seems to work without flaw and encryption also works.

If you need, i uploaded the compilation log there : http://pastebin.com/4VAa2vtK

**Comment by pbek** [comment]
Awesome, thank you for your help!
The OBS ARM build went through too now!
I'll close this issue now. Have a great day!

**Comment by pbek** [comment]
@octogene, in case you are using Ubuntu on your Raspberry Pi some day... There are now arm packages for QOwnNotes on Ubuntu Launchpad. :tada: 
<https://launchpad.net/~pbek/+archive/ubuntu/qownnotes/+packages>
