### ISSUE TITLE
Add ability to tag folders

### ISSUE THREAD

**Issue by schiessle** [pbek/QOwnNotes#1162]
I used to have many folders, e.g. one folder for every project I'm working on. As you can imagine the list of folders can grow quite fast. Until now I move project folders to an "Archive"-folder once a project is finished. Having the ability to tag folders as "finished" would allow me to keep all projects in the same root folder but still filter my view to only see active projects, all finished projects, etc.

**Comment by pbek** [comment]
I can't even grasp the technological implications and room for regressions it would have trying to implement that. :smile: I can't see that implemented anytime soon.

Maybe you should go with adding a tag to all your notes in "finished" folders.
