### ISSUE TITLE
Small Issues with Windows Auto Updater

### ISSUE THREAD

**Issue by knobhead** [pbek/QOwnNotes#1164]
Hi Patricio,

for a long time I hat small issues with the Auto-updater 

#### Expected behaviour

Update dialogue finds new version, I click "Update" button. 
Update is being downloaded.
Updater starts in Shell window.
QOwnNotes closes. 
Update is extracted.
QOwnNotes re-opens. 
Shell window closes.

#### Actual behaviour

Update dialogue finds new version, I click "Update" button. 
Update is being downloaded and QOwnNotes closes. 
That's it.

When I run the updater.bat with appropriate parameters, updater runs. 
QOwnNotes opens, but shows me the first-run wizard (*as if* ignores the `--portable` flag)

#### Steps to reproduce

* QOwnNotes 19.3.0
* Windows 7 Professional
* QOwnNotes runs in portable mode
* QOwnNotes directory is user-writeable
* QOwnNotes directory path has a space in it

## General Info

**Current Date**: `Mo Mrz 11 17:12:40 2019`
**Version**: `19.3.0`
**Build date**: `Mar  3 2019`
**Build number**: `4192`
**Platform**: `windows`
**Operating System**: `Windows 7 SP 1 (6.1)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.11.3`
**Qt Version (runtime)**: `5.11.3`
**Portable mode**: `yes`
**Settings path / key**: `D:/Firstname Lastname/Tools/QOwnNotes/Data/PBE/QOwnNotes.ini`
**Application database path**: `D:\Firstname Lastname\Tools\QOwnNotes\Data\QOwnNotes.sqlite`
**Application arguments**: `D:\Firstname Lastname\Tools\QOwnNotes\QOwnNotes.exe`, `--portable`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: `en`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `49`
**Enabled scripts**: `0`

#### Relevant log output in the Log panel

`[Mrz 11 16:44:50] [debug]: initializeWindowsUpdateProcess  - 'parameters':  ("C:\\Users\\firstname.lastname\\AppData\\Local\\Temp\\QOwnNotes-NgDvcz.zip", "D:\\firstname lastname\\Tools\\QOwnNotes", "C:\\Users\\firstname.lastname\\AppData\\Local\\Temp\\QOwnNotes-NgDvcz-unzip.exe", "--portable")`

→ Are the double backslashes `\\` correct here? When I try to launch the `updater.bat` with appropriate parameters, it does not work with double backslashes

#### Additional Info

I think the issue that QOwnNotes portable re-opens with the first-run wizard is that the `updater.bat` calls it from the wrong directory (i.e. not the application directory):
If I change line 46 to have the `start` command include a directory for the command to run in, it works:

`start /b /d %destination% call %%qownnotesCommand%%`

Thanks!

**Comment by pbek** [comment]
I just tested the update in portable mode and it worked for me. But I got a dialog after the download was finished that asked me if I really want to update now. Maybe you said "No" once and checked "Don't ask me again". So maybe you want to reset those dialogs in the *General settings* and try again.

**Comment by knobhead** [comment]
Thanks for you quick reply... your support is amazing :)

Unfortunately, your suggestion doesn't solve it.
I've reset the messages/confirmation dialogues in *General Settings* and tried again. The confirmation dialogue pops up, I click "yes" and QOwnNotes closes with the `initializeWindowsUpdateProcess`-Line being the last thing that is written to `QOwnNotes.log`.

I couldn't exactly locate in the source code how and where the `updater.bat` ist launched by QOwnNotes.

Can I help diagnosing with more debug information? if so, which?

Regards

**Comment by pbek** [comment]
> I couldn't exactly locate in the source code how and where the updater.bat ist launched by QOwnNotes.

https://github.com/pbek/QOwnNotes/blob/8a550caff5ae1bf31b14da32f1b8662901907d79/src/dialogs/updatedialog.cpp#L512-L525

I don't know how I could help to debug that process on your side. :/
But you can force QOwnNotes to think it has an earlier version in the `Debug options` settings so you can repeatedly update.

**Comment by pbek** [comment]
I will close this issue until there is more information.
