### ISSUE TITLE
[I] Tags lost when renaming directories/folders

### ISSUE THREAD

**Issue by jjisnow** [pbek/QOwnNotes#1166]
#### Expected behaviour

Tags present in a folder are kept

#### Actual behaviour

Tags deleted when renaming folders

#### Steps to reproduce

1. Rename folder
2. Look for tags on files under folder
3. Curse at having to retag the files

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fri Mar 15 08:22:26 2019`
**Version**: `19.3.0`
**Build date**: `Mar  3 2019`
**Build number**: `4192`
**Platform**: `windows`
**Operating System**: `Windows 7 SP 1 (6.1)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.11.3`
**Qt Version (runtime)**: `5.11.3`
**Portable mode**: `no`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Enabled scripts**: `0`
</details>

**Comment by pbek** [comment]
Since notes can only be referenced by filename and path it certainly is impossible to maintain the tagging information if folders are renamed outside of QOwnNotes. Inside QOwnNotes it would be possible to implement it.

A quick fix for your needs would be to store the tags inside the notes (for example with one of the note tagging scripts in the script repository).

**Comment by pbek** [comment]
## 19.3.1
- implemented preserving of note tag links when renaming note sub-folders

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by jjisnow** [comment]
Works for me! Thx.

**Comment by pbek** [comment]
Great, thank you for testing!
