### ISSUE TITLE
Scripting function request: select 

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#1167]
As discussed, o.a. for https://github.com/qownnotes/scripts/pull/57 it would be nice to have functionality exposed to scripting that enables to:
- select parts of the note (especially the current line)
- receive the selection 
- create (or reapply) a selection

Goal in the `toggle-checkbox` script:
- single checkbox/line:
  - user has cursor on a line in a note
  - presses shortcut
  - current line is selected
  - content available to script
  - scripts toggles checkbox
  - note content is updated
- multiple lines:
  - user selected lines
  - presses shortcut
  - content available to script
  - script toggles checkboxes
  - note content is updated
  - content keeps selection / selection is reapplied

Hope this is clear, thanks in advance!

**Comment by pbek** [comment]
You will get this in the next release

**Comment by pbek** [comment]
Don't forget to bump the minimum version in your script 😉

**Comment by pbek** [comment]
## 19.3.2
- there now is a new *script settings variable* for select-boxes
    - you can define items with an index and a text
    - you will receive the selected index
    - for more information please take a look at the [scripting documentation](https://docs.qownnotes.org/en/develop/scripting/README.html#registering-script-settings-variables)

**Comment by sanderboom** [comment]
> You will get this in the next release

'this' === dropdown in settings?
Awesome! :raised_hands: 

This issue is actually about being able to set/get the selected text in a note :wink:

**Comment by pbek** [comment]
lol, I totally thought you were talking about the select box feature

**Comment by pbek** [comment]
@sanderboom what beside `current line is selected` doesn't work yet?

**Comment by pbek** [comment]
> reapply a selection

that will never work if the text in the note text edit was changed

**Comment by pbek** [comment]
You can read the selected text in the note text edit with <http://docs.qownnotes.org/en/develop/scripting/README.html#read-the-selected-text-in-the-note-text-edit> and overwrite it with <http://docs.qownnotes.org/en/develop/scripting/README.html#write-text-to-the-note-text-edit>, can't you?

**Comment by pbek** [comment]
## 19.3.2
- there now is a new scripting command `script.noteTextEditSelectCurrentLine()`
  to select the current line in the note text edit
    - for more information please take a look at the [scripting documentation](https://docs.qownnotes.org/en/develop/scripting/README.html#select-the-current-line-in-the-note-text-edit)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by sanderboom** [comment]
> there now is a new scripting command script.noteTextEditSelectCurrentLine() to select the current line in the note text edit 

Works grrreat :smiley:  

Implemented the 2 new features right away: https://github.com/qownnotes/scripts/pull/58

> > reapply a selection
> 
> that will never work if the text in the note text edit was changed

Can you pass the start- and end-postiion of the selection? All we need then is a method to apply a selection from start- to end-position... Idea?

**Comment by pbek** [comment]
> Can you pass the start- and end-postiion of the selection? All we need then is a method to apply a selection from start- to end-position... Idea?

those are just absolute positions (the Xth character) in the text edit. if you change the text those positions would change too :/

**Comment by pbek** [comment]
see: https://doc.qt.io/qt-5/qtextcursor.html#position

**Comment by sanderboom** [comment]
> those are just absolute positions (the Xth character) in the text edit. if you change the text those positions would change too :/

I think I can work with that. I know what I change so I should be able to figure out what the new end position for the selection needs to be. The starting position will stay the same. Apply the new selection would be the last thing to do in the customAction.

The goal is to make the multiline-toggle as easy as the single-line: without manual reselecting:
![Peek 2019-03-19 10-05](https://user-images.githubusercontent.com/5956570/54593373-b361e880-4a2e-11e9-8474-b50131028ca5.gif)

What do you think?

**Comment by pbek** [comment]
So what scripting functionality would you need? An api to read the position of the current selection (e.g. https://doc.qt.io/qt-5/qtextcursor.html#selectionStart) and a method to set a selection (from / to).

**Comment by sanderboom** [comment]
Yes, get the selectionStart, get the selectionEnd and setSelection from/to would be perfect!

**Comment by pbek** [comment]
You will get those commands in the next release.

**Comment by pbek** [comment]
## 19.3.3
- there now are new scripting commands `script.noteTextEditSetSelection()`,
  `script.noteTextEditSelectionStart()` and `script.noteTextEditSelectionEnd()`
  to set and get the currently selected text in the note text edit
    - for more information please take a look at the
      [scripting documentation](https://docs.qownnotes.org/en/develop/scripting/README.html#set-the-currently-selected-text-in-the-note-text-edit)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by sanderboom** [comment]
Strange, `yay -Syyu --devel` does not present the new version. I am building now from the snapshot download from the AUR directly.

**Comment by sanderboom** [comment]
The new functions work great. Didn't have to use the endPos at all, I just have startPos + new length :wink: 

Apparently the `.length` is  utf-8 proof :+1: 

![Peek 2019-03-20 08-33](https://user-images.githubusercontent.com/5956570/54666764-f97c8200-4aea-11e9-9106-6032def62a86.gif)

BTW, I do this: `var resultText = lines.join('\n');`, do I need to take Windoze users into account? How to know whether I should use `\r\n` instead?

**Comment by pbek** [comment]
Awesome!

> do I need to take Windoze users into account

good question, most of the time I also just take `\n` into account...
