### ISSUE TITLE
Move notes - Bug?

### ISSUE THREAD

**Issue by mlimacarlos** [pbek/QOwnNotes#117]
When i move notes from other directory, if note will be moved are open, the program recreate a note again.

**Comment by pbek** [comment]
Can you please describe step by step what you are doing so I can try and reproduce your problem.

**Comment by mlimacarlos** [comment]
1. Open a note 
2. Move opened note to another directory
3. You'll see that note was moved but a new note was created because this note was opened.

**Comment by pbek** [comment]
Can you please describe how you move the note (externally, with QOwnNotes, ...)

**Comment by pbek** [comment]
I can reproduce what you are describing when moving the current note with QOwnNote and I'm looking for a solution.

**Comment by pbek** [comment]
This problem should be fixed in the next version (1.2.7). Can you please be so kind and test it after the next version is out.

**Comment by mlimacarlos** [comment]
Of course.

**Comment by mlimacarlos** [comment]
Hi... there is another issue. When i change default folder, if a text file was appear the notes, it migrates to the new folder at the left panel (describe notes). The steps are below: 

1. Work on a folder with notes. 
2. choose another folder, set default. 
3. after you choose another folder you will see the note at left panel.

**Comment by pbek** [comment]
Thank you for the report! Can you please open an other issue for that problem, I will take a look at it later.

**Comment by pbek** [comment]
I can't reproduce your last problem. How did you choose an other folder? Did you select a recent notes folder or did you set a new folder? (I can't reproduce it both ways.)

**Comment by pbek** [comment]
Meanwhile I released v1.2.7.

**Comment by mlimacarlos** [comment]
Ok. I will close this issue and open another.
