### ISSUE TITLE
Feature Request: Shortcut for open/closing the editor

### ISSUE THREAD

**Issue by 2Fake** [pbek/QOwnNotes#1170]
Hi. 
as mentioned above, it would be nice if there is a shortcut to open/close the edit view.

2Fake

**Comment by pbek** [comment]
Just turn off that the note edit panel is a fixed central panel in the *Panel settings*, then you can use workspaces with and without the note edit panel.

Does this answer your question?

**Comment by 2Fake** [comment]
Is there a shortcut to switch between these workspaces? I know I can disable the edit field, but I have several notes, that I edit only a few times and most of the time I just want to view the notes preview

**Comment by pbek** [comment]
There is a shortcut to switch between the last two Workspaces

2Fake <notifications@github.com> schrieb am Do., 28. März 2019, 19:25:

> Is there a shortcut to switch between these workspaces? I know I can
> disable the edit field, but I have several notes, that I edit only a few
> times and most of the time I just want to view the notes preview
>
> Am 28. März 2019, 18:03, um 18:03, Patrizio Bekerle <

**Comment by 2Fake** [comment]
Ok, will try it and inform you. Thanks for the help.

**Comment by 2Fake** [comment]
That's exactly, what i needed. Thank you!
