### ISSUE TITLE
build-for-aur.sh security issue

### ISSUE THREAD

**Issue by dandelionred** [pbek/QOwnNotes#1175]
First of all: I've never heard about tuxfamily.org so please don't blame me in case I hurt your feelings about it. All I know about the site atm is this https://siterankdata.com/tuxfamily.org (look at the wide graph in the page's bottom) which says after six consecutive years spent in alexa top 100k it was suddenly wiped out of alexa top 1m and never reentered there since Sep 16 2017.

Back to the issue.

https://github.com/pbek/QOwnNotes/blob/867172de9665f02c71bc64551d2c947a760a4922/build-systems/aur/build-for-aur.sh#L61

So in case tuxfamily.org is hacked (or does it on intention) it is possible for the AUR pkgbuild to deliver modified sources with valid sha256 sum.

**Comment by pbek** [comment]
this script is called immediately after the package is uploaded to tuxfamily, so someone would have just a few seconds to "hack" it...

**Comment by pbek** [comment]
>  I've never heard about tuxfamily.org

I just needed a free file hosting for FOSS projects, Sourceforge was down too often...

**Comment by dandelionred** [comment]
In case the site is hacked malicious patching can be done automaticly on package upload hook.
Even more. wget manual (in ubuntu) says
> The only timeout enabled by default is a 900-second read timeout.

Since the script doesn't set any timeout on the wget call it is possible for the call to last for 900s at least which is pretty much enough for tampering even without automation.

**Comment by pbek** [comment]
> Since the script doesn't set any timeout on the wget call it is possible for the call to last for 900s at least which is pretty much enough for tampering even without automation.

I sit in front of my computer and wait until the deployment scripts are finished

what do you want to achieve with this issue you posted?

**Comment by dandelionred** [comment]
> this script is called immediately after the package is uploaded to tuxfamily, so someone would have just a few seconds to "hack" it...
Please, consider reusing local checksums generated in build-tuxfamily-src.sh without relying on some remote party to store it for those few seconds.

**Comment by pbek** [comment]
I will consider, thank you for your feedback

**Comment by dandelionred** [comment]
> I sit in front of my computer and wait until the deployment scripts are finished
> what do you want to achieve with this issue you posted?

I'm reading into the sources and the build scripts. I like the thing you've made very much and would like more people to use it. Fixing things which look like security issues is important in not averting people from using it.

**Comment by pbek** [comment]
My main script is <https://github.com/pbek/QOwnNotes/blob/develop/build-systems/build-all.sh>, from there I upload the source bundles and then run all deployment scripts in parallel via tmux...

**Comment by dandelionred** [comment]
Slackware and gentoo builds believe in tuxfamily as well and generate checksums out of downloaded files.
https://github.com/pbek/QOwnNotes/blob/867172de9665f02c71bc64551d2c947a760a4922/build-systems/slackware/build-for-slackware.sh#L47-L51

https://github.com/pbek/QOwnNotes/blob/867172de9665f02c71bc64551d2c947a760a4922/build-systems/gentoo/build-for-gentoo.sh#L46-L49

---

snapcraft.yaml doesn't utilize `source-checksum` feature and believes in tuxfamily
https://github.com/pbek/QOwnNotes/blob/867172de9665f02c71bc64551d2c947a760a4922/build-systems/snap/snapcraft/snapcraft.yaml#L30-L35

(also notice the URL to the qmake plugin redirects to https://docs.snapcraft.io/writing-local-plugins/5125. Should it be https://docs.snapcraft.io/the-qmake-plugin/8628 ?)

Here is a sample how source-checksum is used
https://github.com/snapcrafters/gimp/blob/a388e709da9352444e8c69093b4eafa1a05d5c79/snap/snapcraft.yaml#L171-L172

**Comment by pbek** [comment]
If you want you can alter the tuxfamily script export a environment variable with the checksum and modify the other script to optionally (if available) use that variable to set the checksum instead of downloading the remote checksum. I'm open for a pull requests. :smile_cat:

**Comment by dandelionred** [comment]
Great to see you're already fixing the problem!

But why still attempting to use remote checksums here?
https://github.com/pbek/QOwnNotes/blob/0be6ef54a3f422354b543b953b1cfe2572ec059c/build-systems/aur/build-for-aur.sh#L60-L66

It should be an immediate exit in case $QOWNNOTES_ARCHIVE_SHA256 is not set.

For example when we install packages with apt from some (probably compromised) mirror there is no such problem as tampered packages with valid checksums because there is another layer of security: the gpg-signed `Release` file like the one under http://ftp.ubuntu.com/ubuntu/dists/trusty/. _More details about the matter: https://wiki.debian.org/SecureApt_

Since you don't sign anything when uploading to the remote, the stuff downloaded back from there is absolutely not trusted, you can't check if it was tampered or not. Basicly it is the reason why we have hashes explicitly inside PKGBUILD/snaps/flatpaks: a package can be tampered by the remote side but it can't fake the hash because the hash comes from another source (e.g. PKGBUILD).

**Comment by pbek** [comment]
> Great to see you're already fixing the problem!

Problem is that exporting environment variables doesn't work across scripts, so this attempt doesn't work. :disappointed: 

> But why still attempting to use remote checksums here?

because the scripts need to work stand alone too if need arises
I need an other solution for the checksums... any suggestions?

**Comment by dandelionred** [comment]
> Problem is that exporting environment variables doesn't work across scripts, so this attempt doesn't work. 

Mby build-tuxfamily-src.sh should produce a temporary file `vars` with all the hashes used in the various build scripts
```
QOWNNOTES_ARCHIVE_MD5=...
QOWNNOTES_ARCHIVE_SHA256=....
QOWNNOTES_ARCHIVE_SHA512=....
```

and the build scripts should source the file on start
```sh
#!/bin/bash

if [[ ! -f vars ]]; then
	echo "vars" doesn't exist. build-tuxfamily-src.sh must be run ahead of any other build scripts!
	exit 1
fi

source vars

# the rest of the code, all hashes should be taken from the vars only now
```

**Comment by pbek** [comment]
now it should work for the AUR

**Comment by dandelionred** [comment]
> now it should work for the AUR

Great! Will you also fix the same for slackware, gentoo and snapcraft as per https://github.com/pbek/QOwnNotes/issues/1175#issuecomment-480812966 ?

**Comment by dandelionred** [comment]
> now it should work for the AUR

Also this
https://github.com/pbek/QOwnNotes/blob/97e6889498941dae96e7e88a2c2a00859faa97c1/build-systems/aur/build-for-aur.sh#L69-L75

should be patched as
```diff
--- <unnamed>
+++ <unnamed>
@@ -1,7 +1 @@
-# check variable from build-systems/tuxfamily/build-tuxfamily-src.sh
-if [ -z ${QOWNNOTES_ARCHIVE_SHA256} ]; then
-    echo "QOWNNOTES_ARCHIVE_SHA256 was not set! downloading checksum..."
-    ARCHIVE_SHA256=`wget -qO- https://download.tuxfamily.org/qownnotes/src/qownnotes-${QOWNNOTES_VERSION}.tar.xz.sha256`
-else
-    ARCHIVE_SHA256=${QOWNNOTES_ARCHIVE_SHA256}
-fi
+ARCHIVE_SHA256=${QOWNNOTES_ARCHIVE_SHA256}
```

**Comment by pbek** [comment]
Now everything should be in place. Did you see anything else?

**Comment by dandelionred** [comment]
Nope, that was all I noticed related to the original AUR flaw.
