### ISSUE TITLE
QOwnNotes still uses dark grey icons despite me running a dark system theme

### ISSUE THREAD

**Issue by danbohea** [pbek/QOwnNotes#1177]
_First up, thank you for QOwnNotes. This software looks great and I'm looking forward to digging in to it much deeper :)_

#### Expected behaviour

QOwnNotes should use suitable (i.e. light) icons when I use a dark theme for my system. Perhaps it should provide a setting so that I can specify that I'm running a dark system theme. I don't want to use QOwnNotes' in-built dark mode, nor should I have to.

#### Actual behaviour

My system uses a dark theme but when I run QOwnNotes the icons are dark grey which makes them hard to see due to the low contrast.

![image](https://user-images.githubusercontent.com/6885065/55806957-37146f80-5ad9-11e9-9230-ec2a83c17f60.png)

#### Steps to reproduce

1. Install & enable a dark system theme (I'm using Arc Dark).
2. Launch QOwnNotes
3. In "Settings" > "Interface" ensure that "Enable dark mode" is unchecked.

![55805304-13035f00-5ad6-11e9-8c97-bfdcc846a8c5](https://user-images.githubusercontent.com/6885065/55806723-bd7c8180-5ad8-11e9-98ca-9c1d07df54da.png)

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Apr 9 14:56:39 2019`
**Version**: `19.4.1`
**Build date**: `Apr  5 2019`
**Build number**: `529`
**Platform**: `linux`
**Operating System**: `KDE neon User Edition 5.15`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.9.5`
**Qt Version (runtime)**: `5.12.0`
**Portable mode**: `no`
**Settings path / key**: `/home/dan/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/dan/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_GB`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `58`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://cloud.bohea.co.uk`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `15.0.5.3`
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `2`

### Note folder `default`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `1`
**localPath**: `/home/dan/Nextcloud/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/dan/Nextcloud/Notes/notes.sqlite`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-9c24397c-3122-4a0d-bc05-1989bdc7fa01`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2019-04-09T14:40:31.068`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/mainToolBar.iconSize** (QString): `16`
**MainWindow/noteSubFolderTreeWidgetExpandState-2** (QStringList): `inkdrop, cloud`
**MainWindow/noteTextEdit.code.font** (QString): `Hack,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Hack,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**NoteHistory-2** (QVariantList): `<variant list with 118 item(s)>`
**NoteHistoryCurrentIndex-2** (int): `117`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `2`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**interfaceStyle** (QString): `kvantum-dark`
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `22`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/dan/Nextcloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): `https://cloud.bohea.co.uk`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList** (QString): `Personal`
**ownCloud/todoCalendarEnabledList** (QString): `Personal`
**ownCloud/todoCalendarEnabledUrlList** (QString): `https://cloud.bohea.co.uk/remote.php/dav/calendars/dan/personal/`
**ownCloud/todoCalendarUrlList** (QString): `https://cloud.bohea.co.uk/remote.php/dav/calendars/dan/personal/`
**ownCloud/userName** (QString): `dan`
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `15.0.5.3`
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-2** (QStringList): `Note 2019-04-09T14.41.20, Configuration Parameters — Nextcloud 15 Administration Manual 15 documentation 2019-04-09T12.26.41, Configuration Parameters — Nextcloud 15 Administration Manual 15 documentation, Does the Thinkpad X1 Carbon (3 4 5 gen) have touchpad issues on Linux linuxhardware, Note 2019-04-09T12.06.25, Note 2019-04-09T12.04.50`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**KDE_FULL_SESSION**: `true`
**GS_LIB**: `/home/dan/.fonts`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**USER**: `dan`
**LANGUAGE**: `en_GB`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `3013`
**SHLVL**: `0`
**XCURSOR_SIZE**: `0`
**HOME**: `/home/dan`
**DESKTOP_SESSION**: `/usr/share/xsessions/plasma`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**KDE_SESSION_VERSION**: `5`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**MANDATORY_PATH**: `/usr/share/gconf//usr/share/xsessions/plasma.mandatory.path`
**LOGNAME**: `dan`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**DEFAULTS_PATH**: `/usr/share/gconf//usr/share/xsessions/plasma.default.path`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_ID**: `3`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**XCURSOR_THEME**: `breeze_cursors`
**DISPLAY**: `:0`
**LANG**: `en_GB.UTF-8`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_SESSION_DESKTOP**: `KDE`
**XAUTHORITY**: `/home/dan/.Xauthority`
**SSH_AUTH_SOCK**: `/tmp/ssh-Y5NLjAYSVNOE/agent.2964`
**SHELL**: `/bin/bash`
**QT_ACCESSIBILITY**: `1`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**XDG_VTNR**: `1`
**PWD**: `/home/dan`
**XDG_DATA_DIRS**: `/usr/share//usr/share/xsessions/plasma:/home/dan/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-/usr/share/xsessions/plasma:/etc/xdg`
**KDE_SESSION_UID**: `1000`
**SESSION_MANAGER**: `local/dan-desktop:@/tmp/.ICE-unix/3083,unix/dan-desktop:/tmp/.ICE-unix/3083`
</details>

**Comment by pbek** [comment]
thank you for your kind words. 

I am sorry, there actually is no light theme. There just is the dark theme and the theme your system dictates.

**Comment by danbohea** [comment]
After a bit more digging it seems that if I switch my _system icons_ to something other than Breeze Dark (which is what I normally use), save, then switch back to Breeze Dark and save again, QOwnNotes displays nice white icons. But this only lasts until I restart QOwnNotes, after which the app reverts back to the dark grey icons in my original screenshot.

This behaviour doesn't seem to apply to just the Arc Dark theme. Breeze Dark (the theme) does the same thing (white icons persist only until the app is restarted).

**Comment by danbohea** [comment]
I should add that QOwnNotes is the only QT app on my system that behaves like this to my knowledge (Dolphin & KOrganizer for example display white icons just fine).

**Comment by pbek** [comment]
I will investigate that.

**Comment by pbek** [comment]
It seems a problem of KDE (or KDE Neon). The theme of the desktop environment doesn't get reported by `QIcon::themeName()`. And the new `QIcon::fallbackThemeName()` reports `breeze`, even if I have `breeze-dark` activated. This works with other desktop environment, as my current metrics show.

**Comment by pbek** [comment]
## 19.4.2
- for Linux there there now is a setting in the *Interface settings* to enforce
  the system icon theme in case your desktop environment doesn't report the icon
  theme correctly
    - KDE currently seems to have this problem on Qt 5.12
    - in addition if built on Qt 5.12 or newer there now also will be tried to
      check if there is a fallback icon theme in case there is no icon theme reported

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by danbohea** [comment]
Top work! I'll test this as soon as I can.

Has the KDE bug been reported do you know?

**Comment by danbohea** [comment]
This works great, thank you!

**Comment by pbek** [comment]
> Has the KDE bug been reported do you know?

I don't know if it even is a bug...

Thank you for reporting and testing!

**Comment by thegreatyellow67** [comment]
Hi, I'm using QOwnNotes version 19.7.0 (Launchpad PPA - build 549) in Linux Mint 19.1 Cinnamon, unfortunately despite having activated the option "Enforce system icon theme" I have the same problem previously reported by the user danbohea

![Screenshot from 2019-06-30 21-29-53](https://user-images.githubusercontent.com/41580754/60401242-b23c6d80-9b7e-11e9-88d6-e46ec36b0d5d.png)

I've tried all the options related to icons, but nothing.

Following there's my configuration:
OS: Linux Mint 19.1 Tessa x86_64
Kernel: 4.15.0-54-generic
DE: Cinnamon 4.2.0
WM: Mutter (Muffin)
WM Theme: Mint-Y-Dark-Aqua
Theme: Mojave-dark-solid-alt [GTK2/3]
Icons: Papirus-Dark [GTK2/3]

Thanks!

**Comment by pbek** [comment]
I can't tell much of your settings, because you didn't post them. Did you also enable the dark mode icons manually?

**Comment by thegreatyellow67** [comment]
Sorry, I've opened a new issue and I reply to your answer there. See QOwnNotes still uses dark grey icons (Cinnamon DE) #1229
