### ISSUE TITLE
Context-menu option in Note List for "Copy Note Link"

### ISSUE THREAD

**Issue by clintonthegeek** [pbek/QOwnNotes#1179]
Hey Patrizio! QOwnNotes is still the engine of my creative writing, and I'm loving it! Thanks again.

I was going through my Note List and found one called 'cyberia' I wanted to link to in a new note. Could you please add an option called something like "Copy Note Link" to the context menu of the title in the Note List, so that the text

     [cyberia](note://cyberia)

is added to my clipboard for a quick paste?

**Comment by pbek** [comment]
> Hey Patrizio! QOwnNotes is still the engine of my creative writing, and I'm loving it! Thanks again.

:pray: 

> is added to my clipboard for a quick paste?

Check the script repository: `Note link to clipboard` :smile: 

Does this answer your question?

**Comment by clintonthegeek** [comment]
Silly me! Yes it does. :stuck_out_tongue:
