### ISSUE TITLE
Tags? Workbooks?

### ISSUE THREAD

**Issue by GHuze** [pbek/QOwnNotes#118]
QOwnNotes is great for taking notes, but currently its serchable only via direct content. Two enhancements could be:

- Hierarchal tags (Colors > Blue) etc.
- Hierarchal notebooks (School>Work>Chemistry; similar to what OneNote offers)

:)

**Comment by pbek** [comment]
Thank you for your kind words and your ideas!
But as long as QOwnNotes doesn't want to use a database to store the notes and wants to maintain compatibility to ownCloud Notes and the iOS and Android apps this will not be possible. :/

**Comment by pbek** [comment]
There also was an other feature request about keywords here #5.

**Comment by pbek** [comment]
You can now configure your note folders in version 1.2.8.

**Comment by pbek** [comment]
By public demand a tag implementation is currently in the works.

Each note folder will have its own database (with tags and their links to certain note files). The database is a sqlite file, that will be stored directly in the note folder.

I hope it will play together with syncing the database-file via ownCloud and with external changes of the database-file.

**Comment by pbek** [comment]
Version 1.3.7 with tagging support is now out. Can you please test it and report issues?

- you can turn on tagging with <kbd>Alt</kbd> + <kbd>⇧</kbd> + <kbd>T</kbd>
- tags and their associations to note files are stored in each note folder
  individually in a SQLite database
- if notes are renamed by QOwnNotes the tags will be moved to the renamed
  notes
- if notes are move to an other folder their associated tags are lost 
- <kbd>Alt</kbd> + <kbd>⇧</kbd> + <kbd>A</kbd> adds a new tag to a note

**Comment by pbek** [comment]
I am closing this issue until there is feedback.

**Comment by eemantsal** [comment]
I subscribe totally the OP's whish of "workbooks". Tags aren't always the best solution nor everybody needs/likes them; let's not say if one just wants to copy/move/delete/compress/whatever some notes. Sorry for my ignorance, but what has to do a directory (or "workbook") hierarchy with databases? Is a database need in every program that uses a directory stucture? Excuse if my question is too elementary, as I've said I have no idea of writing software, but would it be really so incompatible a simple directory structure. For coding illiterates like me sounds like it should be a basic, elementary thing. Could you illustrat us a bit?

**Comment by pbek** [comment]
In the futures I plan to implement hierarchical tags, but the notes will all be in the same folder.
You can configure as many different folders as you like.
I don't want to keep the notes in a database because that would break the compatibility with ownCloud.
And hierarchical folder structures aren't supported by ownCloud notes as well. (Neither are our tags, which are sitting in a SQLite database for each folder)... Does this answer your question?

**Comment by eemantsal** [comment]
I suppose it does.
I suppose I'll go one of these days and ask OC developers how is possible that if we can create folder, and subfolders in owncloud, their notes app can't handle them.
Software development, how plenty of misteries art thou! xD
Thank for you answer. :)

**Comment by pbek** [comment]
You are free to create feature requests for ownCloud notes and the mobile apps. ;)

**Comment by bdillahu** [comment]
Any thoughts about being able to either export tags as part of the note export, or (my preference) somehow store the tag as text in the actual note.

Maybe YAML at the top of the note, or (easier I expect) some standard "#tag" line at the bottom or something.

Just trying to avoid having metadata that can only be found in the sqlite database.

Thanks for a great tool!

**Comment by pbek** [comment]
@bdillahu, there is an example script to store the tags in the filename at <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/use-tag-names-in-filename.qml>
Does this script help you?

**Comment by bdillahu** [comment]
Ah, that might do it... I'll play with it.

Thanks!
