### ISSUE TITLE
Outdated qmarkdowntextedit submodule reference in index

### ISSUE THREAD

**Issue by dandelionred** [pbek/QOwnNotes#1180]
```
$ git clone --depth=1 https://github.com/pbek/QOwnNotes.git
....
$ cd QOwnNotes
$ git submodule update --init
....
$ git submodule status
 8f1a58e5e2aff87a0bf40b078e32ae2779dca213 src/libraries/fakevim (heads/master)
 54283fa55d520002fbdb8686621eb161ebea82ce src/libraries/piwiktracker (heads/master)
 1aa4474f929cdb3df6811ec65fb3b9afa8558124 src/libraries/qkeysequencewidget (1.0.1-3-g1aa4474)
 =====> d8475618f355ffa1ee4e585c66e28df0f76f2ba4 src/libraries/qmarkdowntextedit (2019.4.0~1)
 db3e9a816d91a4773b61312cafa25eff4ddec91c src/libraries/qtcsv (v1.2.2-7-gdb3e9a8)
 612029c45b7b6c38be8ffe7c600ae6a10edb9006 src/libraries/qttoolbareditor (heads/master)
```

Please, notice d847561 for https://github.com/pbek/qmarkdowntextedit.git is HEAD~1, not HEAD. Is it done on intention?

---

Also, shouldn't .gitmodules be patched like this
```diff
$ git diff .gitmodules
diff --git a/.gitmodules b/.gitmodules
index 5a38f03..4a8e21c 100644
--- a/.gitmodules
+++ b/.gitmodules
@@ -1,6 +1,7 @@
 [submodule "src/libraries/qmarkdowntextedit"]
        path = src/libraries/qmarkdowntextedit
        url = https://github.com/pbek/qmarkdowntextedit.git
+       branch = develop
 [submodule "src/libraries/piwiktracker"]
        path = src/libraries/piwiktracker
        url = https://github.com/pbek/qt-piwik-tracker.git
```

because otherwise `git submodule update --remote` drops back to master's HEAD which is the initial commit made in 2016.

**Comment by pbek** [comment]
Thank you for paying so much close attention to minor details. :) Nothing that is of consequence to QOwnNotes was changed in the last commits of qmarkdowntextedit, so no need to switch to the latest develop state.

If that that answers your question feel free to close the issue.

**Comment by dandelionred** [comment]
Ok, and what are your thoughts about `branch = develop` in .gitmodules?

**Comment by pbek** [comment]
> Ok, and what are your thoughts about branch = develop in .gitmodules?

that could break an already working build in the future if it isn't compatible any more with the current develop branch
