### ISSUE TITLE
Set root folders to display alphabetically

### ISSUE THREAD

**Issue by truthsword** [pbek/QOwnNotes#1181]
How can I get the root folders to display alphabetically (with "default" on top). Here is what I see

![](https://i.imgur.com/JwXAB5b.png)

![](https://i.imgur.com/85ujTmS.png)

#### Expected behaviour
Folder order displayed alphabetically.

#### Actual behaviour
Folder order displayed with first created on top.

**Comment by pbek** [comment]
I'm sorry, you can only do that with note sub-folders. The note folders are in the order you created them.

**Comment by dandelionred** [comment]
@pbek Isn't the `priority` field in the `noteFolder` table from `.local/share/PBE/QOwnNotes/QOwnNodes.sqlite` sets the order? I've just tried manually changing the priority values there and after restart the showing order was changed accordingly.

**Comment by pbek** [comment]
yes, it's just not implemented in the user interface

**Comment by truthsword** [comment]
OK. Thanks... I edited QOwnNodes.sqlite (thanks @dandelionred ) but made a hash of things, so I'm deleting and re-adding folders to achieve alphabetization... but this is not a long-terms solution.

**Comment by pbek** [comment]
## 19.4.3
- you can now reorder your note folders in the *Note folders settings* via drag and drop

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by truthsword** [comment]
I'm only finding 19.4.2 for Windows... Link please?

**Comment by pbek** [comment]
the build process does take a while, keep patient :smile:

**Comment by truthsword** [comment]
Small problem...
![](https://i.imgur.com/YMe4hQW.png)
I can't launch. Initially I used the internal updater. When that wouldn't launch, I tried the zip file to overwrite my installation.

**Comment by pbek** [comment]
Damn, that new Qt 5.12 is still not working on AppVeyor. 😢 
Can you please try the zip from https://ci.appveyor.com/project/pbek/qownnotes/builds/23976436/job/f8bx4l5yltocgn5n/artifacts when it is built.

**Comment by pbek** [comment]
That version works for me.

**Comment by truthsword** [comment]
Perfect. Works well. I prefer this over alpha-sort as I use "almost" alpha. Thank you.

**Comment by pbek** [comment]
Great, thank you for testing! 😄
