### ISSUE TITLE
Low visibility of taskbar icon

### ISSUE THREAD

**Issue by animeshb** [pbek/QOwnNotes#1184]
#### Expected behaviour
Taskbar icon to be visible clearly.

#### Actual behaviour
Taskbar icon has low visibility and is not quickly identifiable among other icons.

#### Steps to reproduce
Open application on Linux machine with tint2 as the taskbar
[Associated tint2rc](https://gist.github.com/animeshb/267f5cbbc40f45562aaf5a8fc5679447)

Low visibility might not be the right word, but Qownnotes taskbar icon is not easily visible to me on my taskbar. May be some contrast thing or invisible borders on the icon. I hope I can get my point across. Please see the screenshots attached of taskbar icon of active and inactive window. 

**qownnotes-active-window:**
![qownnotes-active-window png](https://user-images.githubusercontent.com/1550696/56384321-c1777480-6239-11e9-9c17-1f8e07a3275a.png)

**qownnotes-inactive-window:**
![qownnotes-inactive-window](https://user-images.githubusercontent.com/1550696/56384323-c1777480-6239-11e9-9403-bf4f865bc190.png)

Yes, you might say there it is the icon besides Firefox, but it is not as highlighted as it needs to be IMHO. Even the dark VSCode and terminal icon is visible clearly. Most other icons, in the screenshot, have some kind of notion of a light source falling on the icon from an angle which catches the attention of the eye. Especially the inactive window screenshot above showcases what I am trying to say.

This is also a major pain when there is no other icon on the taskbar.

![qownnotes-active-window-single](https://user-images.githubusercontent.com/1550696/56384770-e1f3fe80-623a-11e9-9ded-243552024221.png)

Hope I am able to make my pain clear.

OS: Debian

Thank you.

Edit: Added OS.

**Comment by pbek** [comment]
I'm sorry, I know nothing of tint2, but there is a darkmode icon for QOwnNotes, you could use that icon.

**Comment by pbek** [comment]
https://github.com/pbek/QOwnNotes/blob/develop/src/images/icon-dark.svg

**Comment by animeshb** [comment]
That is a great icon! It is much better for me now. Thank you so much. I am back to being a happy customer.

![qownnotes-inactive-window-darkmode](https://user-images.githubusercontent.com/1550696/56410046-4f367c80-6299-11e9-9e44-bbb31b18386c.png)

**Comment by pbek** [comment]
I didn't even know I had customers. :smile_cat:

**Comment by animeshb** [comment]
Non paying customer, but more like a follower and promoter. 🙂
