### ISSUE TITLE
qownnotes entry point not found

### ISSUE THREAD

**Issue by miltosc** [pbek/QOwnNotes#1186]
Hello , 
in portable version i get this error after the last update i cannot run it at all

![image](https://user-images.githubusercontent.com/9156710/56438258-f394df00-62ea-11e9-88e7-b61d8ab90d61.png)

Please advise

**Comment by pbek** [comment]
Yes, the new Qt 5.12 is still not working on AppVeyor. I already fixed that in https://github.com/pbek/QOwnNotes/releases/tag/windows-b4238.

**Comment by pbek** [comment]
If that that answers your question feel free to close the issue.

**Comment by miltosc** [comment]
ok i know i just send you if it helps you for debugging
thanks
