### ISSUE TITLE
PDFs appearing in orphaned images

### ISSUE THREAD

**Issue by truthsword** [pbek/QOwnNotes#1187]
![](https://i.imgur.com/v1dfxB6.png)

#### Expected behaviour
PDFs would appear under Manage orphaned attachments

#### Actual behaviour
PDFs appear under Manage orphaned images

When I add an orphaned PDF "image" to a note and delete the leading "!" to form a hyperlink to the file, the file reappears under "Manage orphaned images".

Win10 x64... QON v.19.4.2 and 19.4.3

**Comment by pbek** [comment]
Can you please explain in more detail and step by step what you did, what happened, what you expected and upload your pdf and the markdown you used.

**Comment by truthsword** [comment]
First of all... PDFs don't belong in orphaned images, but rather orphaned files.

Here is the md text:

---
![Beware_of_Ex-Dividend_Dates](file://media/Beware_of_Ex-Dividend_Dates.pdf)
---
[Beware of Ex-Dividend Dates](file://media/Beware_of_Ex-Dividend_Dates.pdf)
---
The first line is what QON adds when I select the orphaned PDF Image and then the button "+ Add to Note"
This line **is not visible** in the QON preview panel.

The second line I created by changing the QON line so that a hyperlink would exist from which I could call the document.  When I delete the apostrophe the PDF is then re-included among the "orphaned images" list. 

Attached is the PDF used here.

**Comment by truthsword** [comment]
Maybe a video will help (attached, but if too large github see link)

http://ge.tt/9u4epev2
approx: 2MB
[2019-04-19_17h26_50.zip](https://github.com/pbek/QOwnNotes/files/3099352/2019-04-19_17h26_50.zip)

**Comment by pbek** [comment]
Thank you, I think I see what happened.

The `media` folder is just for images that were automatically placed there by QOwnNotes when you insert them via `Insert image`. I guess you placed your PDF there manually, correct?
The `attachments` folder is for files that were automatically placed there by QOwnNotes when you insert them via `Insert attachment`.

If that that answers your question feel free to close the issue.

**Comment by truthsword** [comment]
Ooops. User error. Yes, my note import scheme added the PDF files into the media folder.
