### ISSUE TITLE
avoiding blank lines at the bottom of a (scripted) new note 

### ISSUE THREAD

**Issue by FBachofner** [pbek/QOwnNotes#1188]
Hi @pbek

Subsequent to making comments in the [template enhancement request thread](https://github.com/pbek/QOwnNotes/issues/296#issuecomment-485007633) yesterday, I implemented my first "new note" QON script based on your "custom-new-note-headline.qml"

My only problem is that I end up with a few blank lines beneath the "revision history" section.

This seems to be related to the fact that QON by default creates a headline and then adds a couple blank lines beneath it.

Would there be a simple (scripted?) way to avoid these blank lines.  My alternative idea would be to add my text to the bottom of a newly created note (rather than messing with headline creation as I have done here), but I can't figure it out so far . . .

The code below works for my basic purposes, but is sub-optimal as discussed above.

Thanks in advance for any insights.

```
import QtQml 2.0
import QOwnNotesTypes 1.0

/**
 * This script will add a revision history section to the bottom of new notes
 * based on: https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/custom-new-note-headline.qml
 */
QtObject {
    /**
     * This function is called before a note note is created
     * 
     * It allows you to modify the headline of the note before it is created
     * Note that you have to take care about a unique note name, otherwise
     * the new note will not be created, it will just be found in the note list
     *
     * You can use this method for creating note templates
     * 
     * @param headline text that would be used to create the headline
     * @return {string} the headline of the note
     */
    function handleNewNoteHeadlineHook(headline) {
        var AutoGeneratedNoteName = headline + "\n";
        var underline = "===";

//      Date section
//      get today's date
        var date = new Date();
//      format the date, pull into variable: split('T') will "break off" the ISO datetime starting with the T (time) section
        var FormattedDate = date.toISOString().split('T')[0];

//      additional text strings
        var Section_RevisionHistory = "\n\n\n(3 code-block tick marks here - edited out for GitHub)\n---------------------\nrevision history\n	";
        var Create_Date = "	first version / file created";

//      output
        return AutoGeneratedNoteName + underline + Section_RevisionHistory + FormattedDate + Create_Date;
    }
}
```

**Comment by pbek** [comment]
> My only problem is that I end up with a few blank lines beneath the "revision history" section.

what "revision history section"? you are talking of your script already, right?

I think it would be better to use http://docs.qownnotes.org/en/develop/scripting/README.html#creating-a-new-note to create a new note in a custom action where you have control over the whole note text.

**Comment by FBachofner** [comment]
Thanks Patrizio.

I didn't see that before.  I'll look and see what I can come up with.

**Comment by FBachofner** [comment]
OK, @pbek -- these custom actions are pretty cool, but (as I am in the habit of pressing ctrl-N for creating a new note) I would still like to figure out how to move to the bottom of a newly created (in the standard way) note and either:
* insert text there, or
* delete the extra (blank) lines my script creates

Using a custom action for creating a new note for _alternative_ scenarios is obviously useful!

I'll keep playing around with it a bit tonight.

**Comment by pbek** [comment]
The lines are created here <https://github.com/pbek/QOwnNotes/blob/5b992bed103a786f8794b134e89eac4ca21f58f1/src/mainwindow.cpp#L5177>, because the hook is supposed to just setup a headline.

> as I am in the habit of pressing ctrl-N for creating a new note

of course you could rewire the shortcut and use Ctrl+N for your custom action

**Comment by FBachofner** [comment]
Hi @pbek:

> of course you could rewire the shortcut and use Ctrl+N for your custom action

While I can add Ctrl+N for my custom action, it does *not* seem possible to remove it for a new (generic) note.  I can attempt to remove the shortcut by double-clicking it in: Note/Settings/Shortcuts/Note (New Note) which makes it "undefined"  --   However, as soon as I come back there it once again shows a new note will be invoked by "Ctrl+N"

Now "Ctrl+N" does not invoke anything -- QON seems to be "confused" as to what it is to do!  ;-)  [ Apparently two "Ctrl+N" shortcuts are registered! ]

Perhaps "Ctrl+N" is semi-hardcoded and this now causes a conflict?

**Comment by FBachofner** [comment]
>The lines are created here
```
QOwnNotes/src/mainwindow.cpp
Line 5177 in 5b992be
noteText.append("\n\n"); 
```

By the way, this seems a really simple and excellent demonstration of why a templating system would be useful.  You have hardcoded a text stream into each document and the only way of overcoming that is with _scripting_, which is beyond the reach of most users.

A templating system would likely make creating different note types much more approachable.  Even more so if one has a number of different (common -- and "complex") note types

In my opinion, what makes QOwnNotes remarkable is the file management, markdown parsing, tagging, searching, editor/layout/ NextCloud integration (although I don't personally use NC integration), etc.

The way QON *forces* layout is *_not_* among (in my opinion, of course) its desirable features.  I change every auto-generated title underline every time . . . now I am starting to script that . . .

**Comment by pbek** [comment]
> Perhaps "Ctrl+N" is semi-hardcoded and this now causes a conflict?

Did you assign a new shortcut to `New note` first?

> The way QON forces layout is not among (in my opinion, of course) its desirable features. I change every auto-generated title underline every time . . . now I am starting to script that . . .

There is a script for an other main headline as far as I remember. The current headline comes from the restriction of Nextcloud notes (first line of note = filename).

**Comment by pbek** [comment]
I will close this issue until there is more information.
