### ISSUE TITLE
funny time insertion "problem"

### ISSUE THREAD

**Issue by FBachofner** [pbek/QOwnNotes#1189]
Hi @pbek

As you know, I am starting to experiment with scripting, including automatically adding dates, times, etc.

In conjunction with that I have (finally) quickly played with "insert current time" (Ctrl-T) as implemented in Settings/Interface/Editor

The format I had there was (apparently) the default one: `yyyy-mm-dd -- hh:mm`  [ I am pretty sure I have never touched this setting. ]

of course because of the "mm" in the date position it is reporting something illogical:

right now:  2019-34-21 -- 00:34

Last time I checked, Earth does not have 34 months in a year -- *_although I would likely appreciate the extra time each year if it did!_*  ;-)

So of course the "correct" format would be: `yyyy-MM-dd -- hh:mm`

Did someone play an April fools' joke on me or has this setting been following me as a fairly long-time user of QOwnNotes?

**Comment by pbek** [comment]
The method is just using <https://doc.qt.io/qt-5/qdatetime.html#toString>. Did you take a look at <http://docs.qownnotes.org/en/develop/time-formats.html>?

**Comment by pbek** [comment]
Remove the line in the settings to use the default timeformat of your operating system.

**Comment by pbek** [comment]
If that that answers your question feel free to close the issue.

**Comment by pbek** [comment]
I will close this issue until there is more information.
