### ISSUE TITLE
3rd Pane

### ISSUE THREAD

**Issue by GHuze** [pbek/QOwnNotes#119]
IF a tag & workbooks feature are considered, then in addition to the tags pane (with search bar on top like the notes pane), the notes pane, the editor pane, it would be useful also to have a viewer pane also.

Currently the viewer pane is a tab in the same pane as the editor. The editor colors the formatting appealingly, but a juxtaposed live rendered preview is useful.

It would be even better if multiple selected notes could be viewed togather in the preview pane (with a line break in between)

**Comment by pbek** [comment]
Thank you for your suggestions, but currently #118 isn't likely to happen.

**Comment by pbek** [comment]
> live rendered preview

does this have anything to do with the 3rd pane or is this a different feature request?
If the latter is the case please create a new issue and tell us more. :)

**Comment by pbek** [comment]
By public demand a tag implementation is currently in the works.

Each note folder will have its own database (with tags and their links to certain note files). The database is a sqlite file, that will be stored directly in the note folder.

I hope it will play together with syncing the database-file via ownCloud and with external changes of the database-file.

**Comment by pbek** [comment]
Version 1.3.7 with tagging support is now out. Can you please test it and report issues?

- you can turn on tagging with <kbd>Alt</kbd> + <kbd>⇧</kbd> + <kbd>T</kbd>
- tags and their associations to note files are stored in each note folder
  individually in a SQLite database
- if notes are renamed by QOwnNotes the tags will be moved to the renamed
  notes
- if notes are move to an other folder their associated tags are lost 
- <kbd>Alt</kbd> + <kbd>⇧</kbd> + <kbd>A</kbd> adds a new tag to a note

**Comment by pbek** [comment]
Added in the current version 1.4.1:

- **live markdown preview**
  (for [Issue #119](https://github.com/pbek/QOwnNotes/issues/119))
    - the **markdown note view** is now optionally **visible all the time**
    - <kbd>Ctrl</kbd> + <kbd>E</kbd> now toggles the markdown view mode
    - the markdown preview will be updated every 2 sec 
    - todo: linked scrolling between note edit and markdown view
    - todo: markdown preview update when editing encrypted notes 

Could be please be so kind and give some feedback.

**Comment by eemantsal** [comment]
Live MD preview works great, although I don't know if the color for links, orange, is the best election, instead the "standarized" blue. Anyway, that doesn't depend on preview "mechanism" nor it's too important; regarding prview, no flaws so far, even if scrolling isn't still linked between both views, on my system it renders correctly, both just text notes and illustrated ones. Cool!. :dancer:  :)
But I'd suggest to split the view panel horizontally better than vertically, configurable, better, and let the user decide. In modern panoramic monitors is common to have two apps at once on screen, so vertical splitting makes lines a bit too short and displaces the text too much. I think horizontal distorts less the views.

**Comment by pbek** [comment]
Thank you for your feedback and your suggestions. As for blue, I very dislike the color. :)
As for vertical splitting, I guess nowadays most of the people have more horizontal real estate... Maybe in the future we can have a 2nd option...

**Comment by eemantsal** [comment]
I 'd never had suspected that people uses today's 20+ inches multimegapixel panoramic monitors to show one only text application at one time. O_O. How do you read those extremely long lines without losing the refernce for the next one?
Well, I'm just thinking aloud. I think it's a nice featue, but if I'm the only one who seems interested, I guess it' not a prioritary feature, at all, hehe. Let's hope in the future it' implemente. ;)
Thanks for taking it into account anyways.

**Comment by pbek** [comment]
That's why QOwnNotes now has four panes. :)

**Comment by pbek** [comment]
I'm closing this issue now and keep the vertical splitting in mind.

**Comment by pbek** [comment]
Christmas came early this year. :)
In v16.04.13 you can now also **split** the note edit pane and note markdown preview **vertically** instead of horizontally to gain more space on screens with lower vertical resolution.
Can you please test and report back?

**Comment by pbek** [comment]
Version 16.04.13 is out now. :tada:

**Comment by eemantsal** [comment]
Great. Of course, I'll test and report. when I have time I hope along the day.

**Comment by eemantsal** [comment]
Works beautifully. :)
I can have on my 1920x1200 screen a document, email, webpage on the left and QON on the right, and just select some text I want to include in my notes on the left window, move my mouse to the right and middle click to paste it and start editing and see just below, the preview perfectly ever if my notes' lines have a normal book width.
Grat job, Patrizio! :+1: 

But, if you allow another suggestion, and being fully aware that this isn't a very important one, could be possible to supponer drag and drop? It's no annoyance at all to middle click to paste (gods bless Linux desktops, heheh), but if not too difficult, just dragging and dropping content on QON¡s windows would even be handier.

**Comment by pbek** [comment]
Thank you for your kind words, @eemantsal. Some things can already be dropped into QOwnNotes, like notes and images. see: <http://www.qownnotes.org/changelog/QOwnNotes> (search for `drop`)
