### ISSUE TITLE
Markdown file gets removed after changing case of title on NTFS filesystem

### ISSUE THREAD

**Issue by mendaxca** [pbek/QOwnNotes#1190]
Hi pbek, I just installed QOwnNote version 19.4.3 build b4238 on Windows 10.
#### Steps to reproduce
1. Create a new note.
2. Change the title to something like "fixing tethering on android", still good now.
3. Select an alphabet in title and transform it to uppercase. In my case, select the first alphabet 'f', and change it to 'F'.
4. Wait for the auto save and then go to the note folder, the markdown file "fixing tethering on android.md" somehow disappeared (it has been moved to trash). In QOwnNote, the note lost too.

This behavior can be reproduced every time I try this.

**Comment by pbek** [comment]
Sounds like a Filesystem problem or a problem with Qt and the file system.
what Filesystem does your partition with your notes have?

mendaxca <notifications@github.com> schrieb am Mo., 22. Apr. 2019, 06:58:

**Comment by pbek** [comment]
At least on Linux with ext4 I can't reproduce this issue.

**Comment by mendaxca** [comment]
That's true, I've just tested this on fedora with xfs, no issues.
On windows, the notes are putted in ntfs partition.

**Comment by pbek** [comment]
## 19.4.4
- fixed renaming issue on case-insensitive file-systems

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by mendaxca** [comment]
Wow, thank you very much. The new version is running smoothly now.

**Comment by pbek** [comment]
Great, thank you for reporting and testing!
