### ISSUE TITLE
Feature request: task lists in tje sidebar

### ISSUE THREAD

**Issue by jeroenpraat** [pbek/QOwnNotes#1191]
It would be great if it's possible to add the task lists to the left side sidebar, below the notes. 

Just as the notes (in minimal view) it needs two panels; one for the lists, one for the tasks. The content of the tasks can than be displayed in the large panel on the right, or as a popup window like the tasks are displayed at this moment.

See the simplified image (for minimal layout):

![qownnotes](https://user-images.githubusercontent.com/41594439/56508480-af8d1e80-6524-11e9-8318-23b24c9d8392.png)

**Comment by pbek** [comment]
I'm sorry, that would require a lot of rewriting of some major stuff.

**Comment by jeroenpraat** [comment]
Wow, what a rude reply. Bye!

**Comment by pbek** [comment]
I think I fail to see my rudeness, could you give me a hint please

**Comment by jeroenpraat** [comment]
I'm not going to waste my time about that. Sorry! :roll_eyes:

**Comment by pbek** [comment]
Never mind then. 😁

**Comment by pbek** [comment]
see also #758 and #275
