### ISSUE TITLE
On Windows portable version, moving QOwnNotes to a different drive causes git versioning to silently fail

### ISSUE THREAD

**Issue by Krabbyos** [pbek/QOwnNotes#1192]
So i'm on Windows and have git installed on my E: drive. I originally also had QOwnNotes portable version also on the E: drive. I moved the entire QOwnNotes folder to my Z: drive. 

About 5 months later, QOwnNotes crashed while saving a note. Note empty; data lost. Checked the git repository; last commit was about 5 months ago despite versioning being on the entire time. 
### On Windows Portable mode
git executable: `E:\Program Files\Git\bin\git.exe`
turns to this after oking the settings dialog: `E:/Notes/QOwnNotes/Data/../../../Program Files/Git/bin/git.exe`
git versioning through OQwnNotes works fine

### After moving QOwnNotes folder to Z: drive
path shown in settings: `Z:/Notes/QOwnNotes/Data/../../../Program Files/Git/bin/git.exe`
git versioning fails silently (nothing exists at that path)

### Reselecting path to git executable (which is now on a different drive)
before oking settings: `E:\Program Files\Git\bin\git.exe`
after oking settings:  `Z:/Notes/QOwnNotes/Data/E:/Program Files/Git/bin/git.exe`
git versioning silently fails (also that's not a valid path)

## Expected Behavior
Expected QOwnNotes to popup an error message or something instead of silently failing the commit. Also shouldn't QOwnNotes test if the rewritten path actually points to a git executable? Currently, the git path selection dialog allows you to select any file at all (even non .exe files). And the path rewriting can result in invalid paths.

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
> after oking settings: Z:/Notes/QOwnNotes/Data/E:/Program Files/Git/bin/git.exe
> git versioning silently fails (also that's not a valid path)

Yes, Windows doesn't allow relative paths to an other drive.

> actually points to a git executable

it could also be a script or something else... we could test with https://doc.qt.io/qt-5/qfileinfo.html#isExecutable

**Comment by pbek** [comment]
> git versioning silently fails

you should get a warning in the log widget

**Comment by pbek** [comment]
## 19.4.5
- you now will get a warning dialog if your git client couldn't be executed when a git command is issued
    - you can disable that dialog

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Krabbyos** [comment]
Confirming that the warning popup shows

**Comment by pbek** [comment]
Great, thank you for testing!
