### ISSUE TITLE
Version 19,4,3,-1 is the last working on Manjaro KDE

### ISSUE THREAD

**Issue by Pierrep56** [pbek/QOwnNotes#1195]
On Manjaro Linux, KDE edition, versions superior to 19.4.3-1 (as at the moment, the last version being 19.4.5-1) are not working. 
Downgrading to 19.4.3-1 works as a workaround.
The same occurs for me on 2 different hardware , both with the same Linux OS.

#### Expected behaviour
Program would launch 

#### Actual behaviour
Nothing happen

#### Steps to reproduce
Just upgrade to any version > 19.4.3-1

**Comment by pbek** [comment]
Strange, I have just upgraded to 19.4.5 on my Manjaro KDE laptop.
What happens if you for example run `QOwnNotes --session test`?

**Comment by Pierrep56** [comment]
Well, I feel stupid... All is working. now. 
Seems that the last update of the Qt5 libraries in the "testing" branch a few hours ago resolved the issue. 
Sorry for the false alert.

**Comment by pbek** [comment]
No problem :smile:
