### ISSUE TITLE
blockquotes indentation preview and PDF

### ISSUE THREAD

**Issue by Kvcd12** [pbek/QOwnNotes#1197]
Hi,

I am not sure if this is a problem or user error or incorrect user expectation.

#### Expected behaviour

blockquotes in exported PDF are indented similar to their indentation in the note preview panel

#### Actual behaviour

blockquotes in exported PDF are indented one character

#### Steps to reproduce

Installed QOwnNotes 19.4.5 in Windows 7 64-bit (also tried it in MX Linux). Took defaults.  Exported the "Markdown Cheatsheet" note using Export note as PDF (preview).

![blockquotes](https://user-images.githubusercontent.com/50029431/56832667-9d6bf280-683a-11e9-841e-d0d2ef9df33b.png)

Thanks.

**Comment by pbek** [comment]
Can you please explain in more detail and step by step what you did, what happened and what you expected. 
And can you please post the output from the debug settings.

**Comment by pbek** [comment]
And maybe some example markdown code.

**Comment by Kvcd12** [comment]
Windows ... I downloaded the latest release - 19.4.5.  Placed it on the Desktop.  Unzipped to the Desktop.  Took the defaults at setup.  Didn't change any settings.  There are three Markdown files that are included with the installation.  One is "Markdown Cheatsheet".  From the menu ... Note - Export - Export note as PDF (preview).  (I get the same result when I tried in MX Linux.)

In the screen print in my original post, the edit side is on the left, the preview side is on the right and below both of them is the PDF.

I expected the blockquotes in the PDF to be indented more, similar to what is shown in the preview panel.

**Comment by Kvcd12** [comment]
If I output the same file using:  Note - Export - Export note as HTML

The indents are similar to the preview:

![blockquotes_html](https://user-images.githubusercontent.com/50029431/56836805-479d4780-6846-11e9-858e-7ebf2f8424f0.png)

**Comment by pbek** [comment]
I guess that's simply the way it looks in a pdf, you could add a `qDebug() << html;` to 
`MainWindow::on_action_Export_note_as_PDF_markdown_triggered()` to how the exported HTML would look like before it gets converted to a PDF.

https://github.com/pbek/QOwnNotes/blob/5b992bed103a786f8794b134e89eac4ca21f58f1/src/mainwindow.cpp#L5957

**Comment by Kvcd12** [comment]
Thank you and thank you for providing the next steps.  I am not a programmer, so it may take me awhile to figure all of that out.  

An FYI ... I took a fresh install and installed the script Custom note preview styling 0.0.4.  I added this into the Custom stylesheet:  blockquote {margin-left: 80px;}.  This basically doubled the default indentation in the preview.  Virtually no impact on the exported PDF.  Export HTML:  similar to the preview.  I added this into the Custom stylesheet:  h1 {margin-left: 20px;}.  The preview shows the indentation, the exported PDF displays an one character indentation, and the exported HTML is similar to the preview.  Using this - blockquote {margin-left: 200px;} - on the Custom stylesheet does have an impact on the exported PDF ... the indentation is similar to the preview's default indentation.

**Comment by pbek** [comment]
Thank you for the feedback!

**Comment by Kvcd12** [comment]
Attached is a text file containing the html created with the `qDebug() << html;`.  Hopefully, I did this right.  There is proper indentation when the html file is opened in a browser.

[html_used_by_pdf.txt](https://github.com/pbek/QOwnNotes/files/3143555/html_used_by_pdf.txt)
