### ISSUE TITLE
Feature Request: Integrate with Nextcloud Bookmarks app

### ISSUE THREAD

**Issue by sunjam** [pbek/QOwnNotes#1198]
I tested the excellent _Web Companion_ extension and was wondering about the possibility to import from the [Nextcloud Bookmarks app](https://github.com/nextcloud/bookmarks).  Turning URL's into notes is an excellent idea, but I'd love to select from the bookmarks already present on my Nextcloud servers.

Nextcloud bookmarks have a [Rest API documented here](https://github.com/nextcloud/bookmarks/blob/master/API.md).
Each can contain a Title, URL, description, date added and tags.

[There is a long standing interest in converting Nextcloud bookmarks to notes/articles](https://github.com/nextcloud/bookmarks/issues/438).  Thanks for reading. :)

**Comment by pbek** [comment]
Is your feature request about importing the Nextcloud bookmarks as bookmarks in QOwnNotes like `- [Regex Tester - Javascript, PCRE, PHP](http://www.regexpal.com/) #dev` or importing a Nextcloud bookmark as a new note? I'm not sure if the latter would make sense to me.

**Comment by pbek** [comment]
## 19.5.0
- you are now able to **import bookmarks** from [Nextcloud bookmarks](https://github.com/nextcloud/bookmarks) in the *Notes / Import* menu
    - the bookmarks will be imported to your bookmarks note 
    - for more information about the **bookmarks feature** please visit
      [Web Companion browser extension](https://www.qownnotes.org/Knowledge-base/QOwnNotes-Web-Companion-browser-extension)

**Comment by pbek** [comment]
Maybe the NC Bookmarks API only returns 10 bookmarks by default, I will take a look at this.

**Comment by pbek** [comment]
@iSpeeX, @sunjam there now is a new release, could you please test it and report if it works for you?

**Comment by iSpeeX** [comment]
Well, sadly I still have only 10 bookmarks detected by Qownnotes.
Do you want me to send some informations about my Qownnotes software ?

**Comment by pbek** [comment]
Can you please post the output from the debug settings.
And is there any log output if you enable the log widget and turn on debug logging in the widget when you are importing the bookmarks?

**Comment by pbek** [comment]
I will close this issue until there is more information.
