### ISSUE TITLE
provide repository for Fedora 30

### ISSUE THREAD

**Issue by favadi** [pbek/QOwnNotes#1199]
#### Expected behaviour

Repository is available for Fedora 30.

#### Actual behaviour

No repository is available for Fedora 30.

#### Steps to reproduce

Looking for Fedora 30 repository in https://www.qownnotes.org/installation.

**Comment by pbek** [comment]
As soon OBS has a build target on <https://build.opensuse.org/project/add_repository_from_default_list/home:pbek:QOwnNotes>

**Comment by pbek** [comment]
Until then I guess you will survive with the Fedora 29 repository. :smile_cat:

**Comment by favadi** [comment]
I confirm that Fedora 29 repository works without any problem :).

**Comment by pbek** [comment]
## 19.5.1
- there now is a software repository for **Fedora 30**
    - please visit the [Fedora installation page](https://www.qownnotes.org/installation#Fedora)
      for instructions

**Comment by favadi** [comment]
Confirm that the new repo works fine.

**Comment by pbek** [comment]
Great, thank you for testing!
