### ISSUE TITLE
Add alphabetical sorting 

### ISSUE THREAD

**Issue by janhenke** [pbek/QOwnNotes#12]
Currently the list of notes is sorted by modification date/time. It would be nice and helpful to switch to an alphabetical sorting. Especially for people maintaining a systematic naming scheme to find specific notes more easily.

**Comment by pbek** [comment]
Thanks for the idea. Would be nice. Maybe someone (or me) will do something about it. ^_^

**Comment by pbek** [comment]
Done with the help of @pmarki !
