### ISSUE TITLE
Notes can still open when change default folder -  BUG? 

### ISSUE THREAD

**Issue by mlimacarlos** [pbek/QOwnNotes#120]
Hi @pbek 

i open this issue for new problem. I test in version 1.2.7 and occurs. I detailed the steps below:

1. Create a default notes with subfolders wich contain notes. 
2. Open a subfolder with a note with **set default notes folder**
3. Now, rollback this action and open a main folder with **set default notes folder**. The note opened in subfolder still open in main folder. 

If you cant reproduce this steps i will post a video.

**Comment by pbek** [comment]
Thank you for the report, which operating system are you using?

**Comment by mlimacarlos** [comment]
Fedora Linux 23
Em 26/03/2016 11:27, "Patrizio Bekerle" <notifications@github.com> escreveu:

**Comment by pbek** [comment]
> Create a default notes with subfolders wich contain notes.

What do you mean by that? What is *a default notes* and what subfolders?

> Open a subfolder with a note with set default notes folder

Do you mean the menu entry *set notes folder*?

> Now, rollback this action and open a main folder with set default notes folder. The note opened in subfolder still open in main folder.

I'm not sure what you mean by *rollback* in this context, but every time I set a new note folder QOwnNotes shows me the notes in that folder and no other notes...

Maybe a video really would be best to let me understand what you are doing. :smile_cat:

**Comment by pbek** [comment]
And might you be able to take a look at version 1.2.8 if there are any improvements for you?

**Comment by mlimacarlos** [comment]
OK. The issue solved. That's a great thing!!

**Comment by pbek** [comment]
perfect! :)
