### ISSUE TITLE
"Do you want the application "QOwnNotes.app" to accept incoming network connections?"

### ISSUE THREAD

**Issue by vitobotta** [pbek/QOwnNotes#1200]
Hi, I just downloaded the Mac app and this dialog popped up. Why does the app require I enable incoming connections?
 
Thanks!

**Comment by vitobotta** [comment]
Uhm. It also opened a terminal in which I can see the log ""QOwnNotes server listening on port 22222"". What is the app doing??

**Comment by dandelionred** [comment]
A quick search over the code gives this https://github.com/pbek/QOwnNotes/blob/develop/CHANGELOG.md#18126

**Comment by vitobotta** [comment]
Thanks a lot @dandelionred ! I was a bit worried since I didn't know about this app until a few minutes ago but it looks like there is nothing to worry about :) I don't think I will use the web scraper though so I have disabled the setting I found in the preferences after reading those release notes. One other question, when I launch the app it's launched via a terminal. Not a big issue but is it possible to open it directly? Thanks!

**Comment by dandelionred** [comment]
@vitobotta I never used macos so idk

**Comment by vitobotta** [comment]
Np. I'm closing this anyway as it's not an issue :)

**Comment by pbek** [comment]
I've you have installed the DMG from www.qownnotes.org you get a "normal" app that doesn't need a terminal. But I don't know what 3rd party software you have installed (e.g. like your firewall).

**Comment by vitobotta** [comment]
Hi @pbek , yep I have installed from the DMG. It seems like it's not opening the terminal now that I have disabled that feature. Thanks for the app!
