### ISSUE TITLE
"Note was modified externally"

### ISSUE THREAD

**Issue by vitobotta** [pbek/QOwnNotes#1201]
Hi! I am having a weird issue. When I save manually or when a note is saved automatically, I see the message "Note was modified externally" in the status bar and the editor loses focus or something, jumping to the top of the note and I seem to be unable to edit it unless I click on another note first, and on then on the note I was editing. What could cause this? Thanks!

**Comment by vitobotta** [comment]
OK it looks like the problem that I can't edit after saving and that it scrolls to the top of the note, happens when the filename is different from the title of the note. Somehow I have a note that doesn't update the filename if I change the title... If I set the title of the note to the same name of the actual file, then the automatic scrolling doesn't happen and I can continue editing the note. Any idea?

**Comment by pbek** [comment]
something like this: #656 ?

**Comment by vitobotta** [comment]
HI @pbek , not sure it's the same. It has only happened with that note for some reason (after checking better it didn't happen with other notes), I would change the title of the note but the filename would not change. I just recreated the note to workaround.

**Comment by pbek** [comment]
It's hard to tell, since you didn't provided any information of the issue template.

**Comment by vitobotta** [comment]
I'm sorry, I'll try to do it next time :) I'm closing since it's not happening anymore. Thanks!
