### ISSUE TITLE
Zooming in preview window fixed font size (Linux)

### ISSUE THREAD

**Issue by jd666** [pbek/QOwnNotes#1202]
#### Expected behaviour
Zooming in preview window (CTRL+ mouse scroll) should scale all fonts

#### Actual behaviour
The default fonts are scaled, however the fixed font for code blocks does not scale

#### Steps to reproduce
Create mixed text with ```test text``` and try scaling it with CTRL+mouse scroll.

#### Output from the debug section in the settings dialog
.. no output logged..

##### General Info

**Current Date**: `Wed May 8 15:14:25 2019`
**Version**: `19.5.2`
**Build date**: `May  8 2019`
**Build number**: `536`
**Platform**: `linux`
**Operating System**: `Ubuntu 18.04.2 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.9.5`
**Qt Version (runtime)**: `5.9.5`
**Portable mode**: `no`
**Settings path / key**: `/home/adreyer/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/adreyer/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_GB`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `101`

**Comment by pbek** [comment]
Thank you for your suggestion. I'll take a look into it.

**Comment by pbek** [comment]
The mouse wheel zooming feature in the QTextBrowser seems pretty undocumented. I haven't found out a lot about it, especially why it doesn't seem to zoom monospaced fonts.

**Comment by pbek** [comment]
Could be this problem: https://bugreports.qt.io/browse/QTBUG-52751

**Comment by pbek** [comment]
https://doc.qt.io/qt-5/qtextedit.html#using-qtextedit-as-a-display-widget says:
`Note: Zooming into HTML documents only works if the font-size is not set to a fixed size.`

**Comment by pbek** [comment]
## 19.6.5
- there now is a new checkbox `Ignore code font size to allow zooming` in the
  *Preview settings* to allow zooming of code fonts

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by jd666** [comment]
Tested and works great.
Thank you!

**Comment by pbek** [comment]
Great, thank you for testing!
