### ISSUE TITLE
How do you pronounce QOwnNotes?

### ISSUE THREAD

**Issue by animeshb** [pbek/QOwnNotes#1203]
For something that I am going to use every waking moment, I need to know this. It would make it easier to recommend it to my colleagues or friends when speaking to them in person.

Some possibilities include 

- Queue Own Notes
- Cone Notes 
- Connotes
- QNote
- QNotes

**Comment by pbek** [comment]
Q - Own - Notes
`Q` from https://www.qt.io/
`Own` because you own your own notes
`Notes` for notes :smile_cat: 

> For something that I am going to use every waking moment

very well! :smile: 

If that that answers your question feel free to close the issue.
