### ISSUE TITLE
[Q] Global Search

### ISSUE THREAD

**Issue by truthsword** [pbek/QOwnNotes#1204]
#### General question

How can I search across all folders (not just folder/subfolder, w/Alt-F)

For example my notes are stored...

c:/qon/activities
c:/qon/activities/running
c:/qon/activities/cycling
c:/qon/hobbies
c:/qon/recipes
c:/qon/misc

I want to search across all folders, not just the selected folder (for example, hobbies)

Thank you

**Comment by pbek** [comment]
Are you talking about across all note folders? That's not possible. Only the notes of one note folder are loaded to conserve memory. That's the reason you can have multiple note folder.

If that that answers your question feel free to close the issue.

**Comment by truthsword** [comment]
Yes... all note folders. Understood.
