### ISSUE TITLE
Folders should list all nested notes, no matter the nesting depth (IMHO)

### ISSUE THREAD

**Issue by danbohea** [pbek/QOwnNotes#1206]
#### Expected behaviour

Selecting a folder that contains further subfolders of notes should list all of the notes, no matter how deeply nested. Also, the note count beside the folder should be calculated from the sum of all nested notes.

IMHO this would be much more useful than the current behaviour which misses much of the benefit of being able to nest folders. If my preference is considered divisive then perhaps we could consider a config option to set it one way or the other.

#### Actual behaviour

Only the notes that are stored within the selected folder are listed. Notes that are more deeply nested are not listed. The note count beside the folder is based only on the notes stored directly within that folder.

![Parent folder selected](https://user-images.githubusercontent.com/6885065/57968031-31723b00-795d-11e9-8a85-adb3c208c6ce.png)

![Subfolder selected](https://user-images.githubusercontent.com/6885065/57968032-3505c200-795d-11e9-84b3-45f79f2ee7f3.png)

**Comment by pbek** [comment]
> Selecting a folder that contains further subfolders of notes should list all of the notes, no matter how deeply nested. 

Are you talking about the "Show all notes in a folder..." checkbox in the *Panels settings*?

**Comment by danbohea** [comment]
Aha, yes! That solves most of the issue for me - thank you, I hadn't spotted that.

The note count beside each folder in the folders panel is still misleading to me though. Perhaps the setting you mentioned could also toggle how note count is calculated?

**Comment by pbek** [comment]
## 19.5.3
- if the setting `Show all notes in a folder including their subfolders` is
  activated now the note-subfolder list will show the note count recursively for
  all children note-subfolders

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by danbohea** [comment]
Just tested and am pleased to say that it appears to work really well :)

Once again, thank you for your time & effort!

**Comment by pbek** [comment]
Great, thank you for testing! :smile:
