### ISSUE TITLE
New editor schema: Solarized Light

### ISSUE THREAD

**Issue by fairplay** [pbek/QOwnNotes#1208]
I want to submit a new editor schema.

[Solarized Light.zip](https://github.com/pbek/QOwnNotes/files/3206591/Solarized.Light.zip)

**Comment by pbek** [comment]
Thank you, I'll take a look at it!

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

## 19.5.4
- added a new editor color schema *Solarized Light* by @fairplay

**Comment by fairplay** [comment]
Works nice, thanks!

**Comment by pbek** [comment]
Thank you for the schema! :smile_cat:
