### ISSUE TITLE
Support for macOS dark mode

### ISSUE THREAD

**Issue by janprzy** [pbek/QOwnNotes#1209]
Are there any plans to support the dark mode added in macOS Mojave? I know the app has its own dark mode, but, for example, the title bar and popups are still using the light theme, which looks weird when the rest of the system is dark.

**Comment by pbek** [comment]
I don't know about your setup (since you didn't post it) or how QOwnNotes looks on your system (a screenshot would do wonder), but did you already play around with the script `Custom user interface styling`? You could set colors there and then let me know if you were able to set the missing colors.

**Comment by pbek** [comment]
And I read something about adding two lines to the `Info.plist` file for the title bar:

```
<key>NSRequiresAquaSystemAppearance</key>
<string>false</string>
```

**Comment by janprzy** [comment]
# By default it looks like this
## Dark mode disabled
![Default](https://user-images.githubusercontent.com/41625296/58380259-3499a680-7faf-11e9-87e3-46215eaf6fb5.png)

## This is what QOwnNotes own dark mode looks like
Note that the title bar is still bright
![Dark](https://user-images.githubusercontent.com/41625296/58380273-5a26b000-7faf-11e9-81ed-a6ff85064547.png)

## File selector
![Bildschirmfoto 2019-05-26 um 12 20 11](https://user-images.githubusercontent.com/41625296/58380392-cf46b500-7fb0-11e9-9a2d-4f258c5327be.png)


# After making the changes to `Info.plist`
## Default
It is actually using the system's dark mode now. However, the toolbar icons are still light grey. This is exactly the same as Issue #1177 
![system dark mode](https://user-images.githubusercontent.com/41625296/58380283-880bf480-7faf-11e9-9532-e204b8d2910d.png)
### File selector
![Bildschirmfoto 2019-05-26 um 12 20 52](https://user-images.githubusercontent.com/41625296/58380388-c950d400-7fb0-11e9-90e5-bd90a9f272b5.png)


## Own dark mode
![dark2](https://user-images.githubusercontent.com/41625296/58380314-e76a0480-7faf-11e9-911c-b550f00449ca.png)

Something else I noticed: When the app's internal dark mode is enabled, it does not use the system's checkboxes, buttons etc.: 
![Bildschirmfoto 2019-05-26 um 12 12 57](https://user-images.githubusercontent.com/41625296/58380351-4cbdf580-7fb0-11e9-9ac6-aee16983e0a4.png)
![Bildschirmfoto 2019-05-26 um 12 13 23](https://user-images.githubusercontent.com/41625296/58380352-4e87b900-7fb0-11e9-9620-3e05cff3d26c.png)

# About screen
![Bildschirmfoto 2019-05-26 um 11 42 00](https://user-images.githubusercontent.com/41625296/58380405-eb4a5680-7fb0-11e9-9471-a970a5b0c851.png)

[According to this website](https://doc.qt.io/qt-5/macos.html), apps need to be built against the macOS 10.14 SDK to support dark mode. If I understand correctly, Qt supports it since version 5.12.

**Comment by pbek** [comment]
Thank you for your feedback. Unfortunately Travis-CI still uses the 10.13 SDK according to https://docs.travis-ci.com/user/reference/osx#macos-version

**Comment by janprzy** [comment]
> You can use another version of macOS (and Xcode) by specifying the corresponding osx_image key from the following table

**Comment by pbek** [comment]
I'm trying the parameter in <https://travis-ci.org/pbek/QOwnNotes/builds/537612056>.

**Comment by pbek** [comment]
You could try out the app from https://github.com/pbek/QOwnNotes/releases/download/dev-macosx-b4264-161911/QOwnNotesDev-46aeb84ec2b727b278d1a737c5b1954e485302b9.dmg

**Comment by janprzy** [comment]
You accidentally sent the link to build 4264 instead of 4265.
I downloaded and tried 4265, it's using the system's dark mode correctly now, thanks!
The only problem is that now the icons are dark gray on a slightly darker background, exactly like Issue #1177 (see the 4th screenshot in my previous comment, that's exactly what it looks like now.

**Comment by pbek** [comment]
Sorry for the confusion and thank you for testing. Do you also have turned on the QOwnNotes dark mode?

**Comment by pbek** [comment]
For me everything seems to be fine:

![Bildschirmfoto 2019-05-28 um 05 45 16](https://user-images.githubusercontent.com/1798101/58449440-dcc48200-810b-11e9-96a0-c3f1cd4fe0ae.png)

**Comment by janprzy** [comment]
If I turn on QOwnNotes dark mode, it looks like it does in your screenshot.
If you turn it off, you should also get the problem with the icons.

**Comment by pbek** [comment]
> If I turn on QOwnNotes dark mode, it looks like it does in your screenshot.

so is there still a problem for you?

>  If you turn it off, you should also get the problem with the icons.

which one? the ones in the toolbar? which problem and why do you want to turn dark mode off?

**Comment by janprzy** [comment]
> which one? the ones in the toolbar?

Yes, exactly. They're light gray on a dark gray background:
![system dark mode](https://user-images.githubusercontent.com/41625296/58690216-4dc49d80-8389-11e9-8bfe-4824231e719f.png)

Like I said, it's exactly like issue #1177. Despite using a dark system theme, the default icons are used. This should be solvable in the same way:

Changed in 19.4.2:
> for Linux there there now is a setting in the Interface settings to enforce
the system icon theme in case your desktop environment doesn't report the icon
theme correctly

I think enabling this on macOS too should do the trick.


> why do you want to turn dark mode off?

There's a difference between QOwnNotes' own dark mode and the system dark mode (which is used when the native one is turned off)
Native:
![Bildschirmfoto 2019-05-26 um 12 13 23](https://user-images.githubusercontent.com/41625296/58690778-a0eb2000-838a-11e9-975b-f4d7089ff724.png)

System:
![Bildschirmfoto 2019-05-26 um 12 12 57](https://user-images.githubusercontent.com/41625296/58690791-a7799780-838a-11e9-8ec8-38b6cdf77639.png)

**Comment by pbek** [comment]
#1177 is different because KDE uses free desktop theme icons that QOwnNotes can use and macOS does not have that. I have no way to detect in what mode macOS is running.

**Comment by pbek** [comment]
## 19.6.0
- You are now able to distinctively tell QOwnNotes to use the **dark mode icon theme**
  without using the *dark mode* in the *Interface settings*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by janprzy** [comment]
It works now, that's exactly what I was talking about. Thank you for your patience and keep on the great work!

![Bildschirmfoto 2019-06-02 um 10 35 32](https://user-images.githubusercontent.com/41625296/58758867-3ec52300-8522-11e9-8e8b-80da45cb65b3.png)

**Comment by pbek** [comment]
Great, thank you for testing! 😄
