### ISSUE TITLE
[Feature request] Highlighting tags of notes

### ISSUE THREAD

**Issue by wiktor2200** [pbek/QOwnNotes#1210]
#### Expected behaviour
When I select note from `Note list panel` tags which are added for selected note should be highlighted or bold on `Tags panel`. If it's hard to implement, it would be nice to print tags on hover on selected note (now there is name and last modification date).

#### Actual behaviour
Now to check if note is tagged and what this tag is I have to right click and select from menu: `Remove tag from selected notes...` and that's the place where added tags are shown.

**Comment by pbek** [comment]
Thank you for your suggestion. Currently there is a whole panel just for viewing, adding and removing tags of a note.

**Comment by wiktor2200** [comment]
Oh.. I have missed it. It solves my problem :+1: but for example bolding could be useful.

**Comment by pbek** [comment]
## 19.5.7
- if the current note has a certain tag it will be now highlighted as bold in the tags panel

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by wiktor2200** [comment]
Awesome! That was exactly what I needed. Works well with single and multi tags. Thanks a lot :)

**Comment by pbek** [comment]
Great, thank you for testing!
It should also work with selecting multiple notes. 😉

**Comment by wiktor2200** [comment]
Tested and confirmed that it works also with multiple notes. :)

**Comment by pbek** [comment]
Great! :smile_cat:
