### ISSUE TITLE
[I] Repeated requests to paste security token when creating note from web page

### ISSUE THREAD

**Issue by truthsword** [pbek/QOwnNotes#1211]
#### Expected behaviour

Create note from page (HTML import) badly broken. Each time I try this I get a pop-up to past security code. I've done that many times... even reset the code. Bookmarking seems to work but security code broke all.

Maybe this is too simple for me to comprehend.

#### Actual behaviour

Right-click web page, select Create note from page (HTML import). Nothing happens except security code paste pop-up.

#### Steps to reproduce

Right-click web page, select Create note from page (HTML import). Nothing happens except security code paste pop-up.

#### Information about the application, settings and environment

version 19.5.5

**Comment by pbek** [comment]
Please click on your QOwnNotes icon in your browser toolbar or open the extension settings and enter the code from the dialog (assuming you have the latest version of the browser extension installed).

See: https://www.qownnotes.org/changelog/QOwnNotes

If that that answers your question feel free to close the issue.

**Comment by truthsword** [comment]
Did that.

Next, I added my own security jumble. Added it to extension. Couldn't find it in app settings so I forced the pop-up window and added it there. Still no joy.

**Comment by truthsword** [comment]
Here's a video of what I see...
https://screenpresso.com/=mJUUc

**Comment by pbek** [comment]
Thank you for the video, I will look into that!

**Comment by pbek** [comment]
I moved the issue to https://github.com/qownnotes/web-companion/issues/10
