### ISSUE TITLE
Blank notes created on importing enex files into a subfolder

### ISSUE THREAD

**Issue by jjisnow** [pbek/QOwnNotes#1212]
#### Expected behaviour
When importing notes from .enex files into a subfolder, the program creates the correct note.

#### Actual behaviour
When importing notes from .enex files into a subfolder, the program creates the correct note, but also another similarly titled, but empty note in the Notes parent folder

#### Steps to reproduce
import .enex file into a subfolder.

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue. Do you have an enex file as example?

**Comment by pbek** [comment]
## 19.5.6
- fixed creation of empty notes at the note root folder when importing Evernote enex
  files into a note sub-folder

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by jjisnow** [comment]
Tested - 19.5.6 fixed the problem and imports now download much faster too!

**Comment by pbek** [comment]
> imports now download much faster too

yes, I now also blocked the "file change in note folder" detection while importing ;)

**Comment by pbek** [comment]
Thank you for testing!
