### ISSUE TITLE
Cosmetic issue... unnecessary scroll bar

### ISSUE THREAD

**Issue by truthsword** [pbek/QOwnNotes#1213]
Go to Note>Settings>Browser extension.

Scroll bar appears in default window, unnecessarily.

![](https://i.imgur.com/lYAjQ99.png)

**Comment by pbek** [comment]
Thank you for reporting, I will fix that!

**Comment by pbek** [comment]
## 19.5.7
- fixed unnecessary scrolling and dark mode link colors in the *Browser extension* settings

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by truthsword** [comment]
Resolved. Thank you.

**Comment by pbek** [comment]
Thank you for testing!
