### ISSUE TITLE
Feature Request: Folders and notes - tree view

### ISSUE THREAD

**Issue by l-wilk** [pbek/QOwnNotes#1214]
It would be nice if both notes and folders could be shown in the tree view. Instead of first selecting folder in Subfolders panel and then selecting note in Note list panel, everything could be accessible in single panel.

It would greatly improve usability for people that often switch between notes in different subfolders.

**Comment by pbek** [comment]
I'm sorry, that didn't work out for 1000s of notes and would be a hell to implement.

see #790 and others

**Comment by pbek** [comment]
Please head over to #790 for an update on a note tree in the note list panel.
