### ISSUE TITLE
Can't type the apostrophe...

### ISSUE THREAD

**Issue by vitobotta** [pbek/QOwnNotes#1215]
Hi! I don't know if I have pressed some weird combination that might have caused this, but I suddenly can't type the apostrophe in notes while I can in any other app.... any idea? I have tried reinstalling but it's the same. Thanks

**Comment by pbek** [comment]
No I've no idea how you did that. But if you want to try with fresh settings you can do something like `QOwnNotes --session test`.

**Comment by pbek** [comment]
I will close this issue until there is more information.
