### ISSUE TITLE
Add option to restore warning messages (e.g. for when you delete a Note, to double-confirm it)

### ISSUE THREAD

**Issue by Airgunster** [pbek/QOwnNotes#1217]
#### Expected behaviour
An option to restore confirmation dialogues exist (e.g. for when you delete a Note, to double-confirm it via dialogue with `Yes` or `No`).

#### Actual behaviour
There's no option in Settings to restore confirmation dialogues (e.g. for when you delete a Note, to double-confirm it via dialogue with `Yes` or `No`).

#### Steps to reproduce
1. Create a new Note;
2. Delete a Note;
3. Observe that confirmation dialogue appears;
4. Tick on `Don't ask again!` and select`Yes`;
5. Create a new Note, and try to delete it;
6. Observe that there's no confirmation dialogue appeared, and there's no possibility to have that confirmation dialogue back;

#### Output from the debug section in the settings dialog
N/A

#### Relevant log output in the Log panel
N/A

Thanks in advance,
Alexey

**Comment by pbek** [comment]
Please take a look at the *General settings*, you may find what you were looking for. (You can also search for `dialog` in the settings.)

**Comment by Airgunster** [comment]
@pbek, Thanks Patrizio! (was searching though the settings before filing this, but missed it somehow)

**Comment by pbek** [comment]
There also is a search field to search in the settings. ;)
