### ISSUE TITLE
Changing Custom Note default Format 

### ISSUE THREAD

**Issue by santiyounger** [pbek/QOwnNotes#1219]
Hi Patrizio,

Truly love QOwnNotes, it's an amazing program and I'm really happy with it.

I don't know anything about programing, but I've been trying to learn a little bit so that I can customize the default note name.

When a new note is created the default name is 
**Note 2019-06-17T08.06.56**

I would like to be able to customize the **Time Format** and delete the word **"Note"**

I tried the suggestion you made on this issue 
https://github.com/pbek/QOwnNotes/issues/854
but that only seems to change the **Insert Current Time** function not the **default name of the new note.**

I want the new note to be named like this 
**201906170810**
just as one number without dashes
Seems like this is the format I need based on the[ **Time Formats** ](http://docs.qownnotes.org/en/develop/time-formats.html)your provided
**yyyyMMddhhmm**

I don't know how to do the customizable scrpting that you suggest [here](http://docs.qownnotes.org/en/develop/scripting/README.html#registering-a-custom-action). Although I did understand the simple concept of using a pre-made QML like the ones that can be installed in the **Scripriting** section of options within QOwnNotes.

I would appreaciate it you can walk me through a simple way to solve this if possible.

Thank you so much for your help and amazing program!

-Santi

**Comment by pbek** [comment]
Thank you for your kind words!

If you want to change the headline of every note then you might want to take a look at http://docs.qownnotes.org/en/develop/scripting/README.html#handlenewnoteheadlinehook

Example to set a headline for new notes with the current Jalaali date and time:
https://github.com/qownnotes/scripts/blob/master/solar-calendar-integration/solar-calendar-integration.qml

**Comment by pbek** [comment]
From https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/meeting-note.qml you can get a glimpse of how to get a date string to use in your headline.

**Comment by pbek** [comment]
https://stackoverflow.com/questions/3552461/how-to-format-a-javascript-date can also help you with date formatting.

**Comment by santiyounger** [comment]
Perfect thank you so much for your kind help! keep doing what you are doing!!

**Comment by pbek** [comment]
If you come up with a great solution to use your own date format string to create a date feel free to post a pull request on https://github.com/qownnotes/scripts ;)

**Comment by ExceptionGit** [comment]
Bad solution (I could not find how to do it without hack), but work (can easy change date/name format):
```javascript
import QtQml 2.0
import QOwnNotesTypes 1.0

/**
 * This script modify the headline of new notes
 * 
 * Note that you have to take care about a unique note name, otherwise
 * the new note will not be created, it will just be found in the note list
 */

QtObject {
    // EDIT IF YOU WANT CHANGE DATE FORMAT
    function dateFormat() {
        // new date
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
        var today  = new Date();
        var date = "[" +
                   ("0" + today.getDate()).slice(-2) + "." +
                   ("0" + (today.getMonth()+1)).slice(-2) + "." +
                   today.getFullYear() + " " +
                   ("0" + today.getHours()).slice(-2) + "." +
                   ("0" + today.getMinutes()).slice(-2) + "." +
                   ("0" + today.getSeconds()).slice(-2) +
                   "]";

        return date;
    }

    // EDIT IF YOU WANT CHANGE NAME FORMAT
    function nameFormat(noteName) {
        var autoName = "Note " + dateFormat();            // when you don't set a name for new notes
        var customName = noteName + " " + dateFormat();   // when you set a name for new notes

        return nameIsAutoGenerated(noteName) ? autoName : customName;
    }


    // HACK check name "Note 2019-12-30T23.59.59"
    function nameIsAutoGenerated(noteName) {
        return noteName.match(/^Note [0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}\.[0-9]{2}\.[0-9]{2}$/);
    }

    /**
     * This function is called before a note note is created
     * 
     * It allows you to modify the headline of the note before it is created
     * Note that you have to take care about a unique note name, otherwise
     * the new note will not be created, it will just be found in the note list
     *
     * @param headline text that would be used to create the headline
     * @return {string} the headline of the note
     */
    function handleNewNoteHeadlineHook(headline) {
        // new headline
        var text = nameFormat(headline) + "\n";

        // add the underline
        var underline = "";
        for (var i = 0; i < (text.length - 1); i++) {
            underline += "=";
        }

        return text + underline;
    }
}
```

result:
- for auto name `Note [30.12.2019 23.59.59]`
- for custom name "test" `test [30.12.2019 23.59.59]`

template: https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/custom-new-note-headline.qml
