### ISSUE TITLE
Vim as external editor

### ISSUE THREAD

**Issue by bepolymathe** [pbek/QOwnNotes#1220]
Hello,

I'm looking to put vim as an external text editor because I use a non-standard keyboard layout (bépo). 

I use Tilix and I try this: 

"tilix -e vim" 

But it doesn't work. Any ideas?

**Comment by pbek** [comment]
So what did you do? Did you try to enter a cli application as external editor in the *General settings*? Any log output?

**Comment by bepolymathe** [comment]
I'm looking to launch vim inside a terminal. 
I tried to run it through the settings: 

"tilix -e vim" or "gnome-terminal -e vim"

But it works with gvim

**Comment by pbek** [comment]
Any log output?
Did you try to create a shell script of your call? `tilix -e vim` isn't really a executable...

**Comment by bepolymathe** [comment]
Yes i try with a script like this

```
#! /bin/sh
#
# Qvim.sh
# Copyright (C) 2019 manu <manu@manu>
#
# Distributed under terms of the MIT license.
#


tilix -e vim
```

And the link to this executable like :

`/home/me/script.sh 
`
In the external editor preference.

**Comment by pbek** [comment]
I guess you may need to add a parameter to the call, like `tilix -e vim $1`

**Comment by bepolymathe** [comment]
Yes, you to make 

`tilix -e vim "$1"
`

Thanks
