### ISSUE TITLE
Do not default to use option keybindings on Mac OS

### ISSUE THREAD

**Issue by xiamaz** [pbek/QOwnNotes#1222]
#### Expected behaviour

Enter option-<Key> should insert custom accent keys.

#### Actual behaviour

Some combinations such as option-shift-u will trigger qownnotes shortcuts on default.

#### Steps to reproduce

Enter option-shift-u.

Option keybindings in Mac should be reserved for inputting special characters in different languages. Since there is no distinction between Alt and AltGr as in Windows or Linux this default behavior might be annoying to users depending on using these key combinations.

#### Proposed solution

Either change combinations to cmd keybindings or unset them.

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
## 19.6.6
- the default shortcuts were changed from the Opt-key to the Ctrl-key on macOS to prevent
  blocking of accent characters when writing text

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by xiamaz** [comment]
Yes all default keybindings seem to be working for me. Thanks for fixing the issue!

**Comment by pbek** [comment]
Great, thank you for testing!
