### ISSUE TITLE
Feature Request: Allow item highlight color change in Dark Mode

### ISSUE THREAD

**Issue by JoshStrobl** [pbek/QOwnNotes#1223]
#### Expected behaviour

The expected behavior when changing to Dark Mode is to have the ability within the Interface category (or a sub-category) to change the background and foreground colors of highlighted items away from orange.

#### Actual behaviour

Under the light theme of QOwnNotes, highlighted items in the notes tree and list are a cool blue, with white text. However, under the Dark Theme, this is changed to an (IMO less pleasant) orange color with black text. There is no option to revert this back to blue or change the background and foreground colors of those highlighted options (at least from what I can see).

#### Steps to reproduce

1. Go to Note -> Settings
2. Go to Interface and check "Enable dark mode" 
3. Restart QOwnNotes.
4. Observe items are orange.

![Screenshot from 2019-06-24 11-51-00](https://user-images.githubusercontent.com/156574/60005003-5b163480-9676-11e9-860b-070dd529da4b.png)

#### Output from the debug section in the settings dialog

**Current Date**: `Mon Jun 24 11:51:17 2019`
**Version**: `19.6.5`
**Build date**: `Jun 24 2019`
**Build number**: `547`
**Platform**: `linux`
**Operating System**: `Solus 4.0 Fortitude`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Solus`
**Qt Version (build)**: `5.12.3`
**Qt Version (runtime)**: `5.12.3`
**Portable mode**: `no`
**Settings path / key**: `/home/joshua/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/joshua/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `12`
**Enabled scripts**: `0`

**Comment by pbek** [comment]
You could install the script `Custom user interface styling` and add some styling yourself.
You will be looking for a style for `QTreeWidget`, see https://doc.qt.io/qt-5/stylesheet-reference.html

**Comment by JoshStrobl** [comment]
Ah yea, that'll do the trick just fine! Thanks for letting me know about that, I admittedly haven't dived that much into all the QOwnNotes scripts (the vast majority of QOwnNotes already does what I need it to do :D).

**Comment by pbek** [comment]
Great ;)

**Comment by mrvanes** [comment]
For those wondering and looking for a solution, these seem all the references to  `#c64a13;` orange in the original `qdarkstyle/style.qss`
```
QWidget {
  selection-background-color: #c64a13;
}
QWidget:item:selected {
    background-color: #c64a13;
}
QMenuBar::item:pressed {
    background-color: #c64a13;
}
QPushButton:focus {
    background-color: #c64a13;
}
QComboBox {
  selection-background-color: #c64a13;
}
QComboBox QAbstractItemView {
  selection-background-color: #c64a13;
}
QListView::item:selected:hover, QListView::item:selected:hover, QTreeView::item:selected:hover  {
  background: #c64a13;
}
QTableView::item:selected:active, QTreeView::item:selected:active, QListView::item:selected:active  {
    background: #c64a13;
}
QToolBox::tab:selected {
  border-color: #c64a13;
}
```
