### ISSUE TITLE
Can't update QOwnNotes

### ISSUE THREAD

**Issue by santiyounger** [pbek/QOwnNotes#1224]
Hey! Loving the program and I'm still happy with the current version, but there are some features I'd love to get from the update.
I've been trying to update QOwnNotes but it doesn't seem to be working

First I click on update
![2019-06-25 (3)](https://user-images.githubusercontent.com/51902730/60073191-ac2a3500-9717-11e9-8073-caa44ae7cf4a.png)

Then it loads correctly 
![2019-06-25 (4)](https://user-images.githubusercontent.com/51902730/60073193-af252580-9717-11e9-838c-a491f7e07999.png)

Then I restart QOwnNotes
![2019-06-25 (5)](https://user-images.githubusercontent.com/51902730/60073201-b3e9d980-9717-11e9-90ce-25c5bf963e0c.png)

After I install it, it still show's me a message of a new version available for updates 
![2019-06-25 (6)](https://user-images.githubusercontent.com/51902730/60073222-c19f5f00-9717-11e9-87a8-a090dbfd6744.png)

I've tried the whole process several times without luck

I tried to use the "just download" but I don't know how to do it without loosing all of my notes and functions. Should I delete and reinstall saving a back up of "Data"?

I don't know programing, but it'd be awesome if there are easy steps to follow to make it work, either by deleting the app, creating back ups and installing it again without loosing my data an modifications.

Thanks,
-Santi

**Comment by pbek** [comment]
Can you please post the output from the debug settings.
And is there any useful log output if you enable the log widget?

**Comment by pbek** [comment]
There is no "installation" or "uninstallation", QOwnNotes is just executed from the folder you downloaded and unzipped it to. You can do that as often as you like without loosing your settings.

**Comment by pbek** [comment]
If that that answers your question feel free to close the issue.

**Comment by santiyounger** [comment]
Thanks for the help!
