### ISSUE TITLE
Application window doesn't remember size and reverts to default size and placement each start

### ISSUE THREAD

**Issue by pull2play** [pbek/QOwnNotes#1225]
When I'm trying to set application window size either by doing this manually with mouse or by use of Sizer application, QOwnNotes resets it to some arbitrary custom size and placement each time I'm relaunching it. 

I did reset application with dedicated feature in option and even tried removing all associated files (everything that I could possibly find) and nothing has changed this behavior. I also tried running it as admin and as you suggested @pbek on telegram with `--session test` parameter and this didn't changed the issue.

I believe this can't be the issue of either Sizer or my system because I have also TeamSpeak installed and it also uses Qt5 library but doesn't behave in such way (it does remember manual resize and placement as well as Sizer application placement).

I'm using Windows 10 x64 PLK, v 1903, build 18362.113, application is placed in C:\Program Files folder, while notes.sqlite and md files are present on D: partition within user profile.

**Comment by pbek** [comment]
Thank you for reporting.
Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log widget?

**Comment by pull2play** [comment]
Sorry, there you have:
[QOwnNotes.log](https://github.com/pbek/QOwnNotes/files/3339130/QOwnNotes.log)
[QOwnNotes Debug Information.log](https://github.com/pbek/QOwnNotes/files/3339137/QOwnNotes.Debug.Information.log)

**Comment by pbek** [comment]
## 19.6.6
- the storing of the main window position was re-enabled after being disabled in
  [#1015](https://github.com/pbek/QOwnNotes/issues/1015)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pull2play** [comment]
The issue is resolved - thank you @pbek !

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by johanricher** [comment]
I still have the issue when in dark mode. (Ubuntu, v17.7.3)

**Comment by pbek** [comment]
Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log widget?

**Comment by johanricher** [comment]
Sorry, I removed my comment where I said that I still had the issue in dark mode.

Now I think it might be related to dual screen. I will investigate a bit more before coming back with the informations you request.
