### ISSUE TITLE
[FR] Nextcloud Text image support

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1226]
[Nextcloud Text](https://github.com/nextcloud/text) supports images from inside the Nextcloud instance.

I intend to implement support for automatically downloading images like `![squirrel.jpg](/core/preview?fileId=16796&x=1024&y=1024&a=true#mimetype=image%2Fjpeg&hasPreview=true&fileId=16796)` from your Nextcloud instance and embed them in the preview to be viewed.

**Comment by pbek** [comment]
## 19.7.0
- added support for a real time preview of [Nextcloud Text](https://github.com/nextcloud/text) images
    - the preview image tags from Nextcloud Text will be transformed to inline images
    - no caching can currently be done because images could be modified on the Nextcloud server

**Comment by pbek** [comment]
There now is a new release, could anyone please test it and report if it works for you?

**Comment by pbek** [comment]
## 19.9.4
- fixed the real time preview of [Nextcloud Text](https://github.com/nextcloud/text) images (for a regression in [#266](https://github.com/pbek/QOwnNotes/issues/266))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by MathiasRenner** [comment]
@pbek Yes, it works for me, when adding a pix inside Nextloud Text via Browser. 

Now it's the other way around missing, right? Adding an image in QOwnNotes and then uploading it to the cloud? :-)

**Comment by pbek** [comment]
Thank you for testing.

> Adding an image in QOwnNotes and then uploading it to the cloud?

But be nice, but really a lot of work and it seems no one is using the current feature yet. :)

**Comment by pbek** [comment]
## 20.2.0
- remote images and Nextcloud text images are now cached after being downloaded
  for the preview until another note was be selected (for [#1244](https://github.com/pbek/QOwnNotes/issues/1244))
    - this improves writing speed because the images now don't need to be
      downloaded again every time the preview is refreshed
- remote images and Nextcloud text images are now (like local images) resized in
  the preview if the width of the preview panel is smaller than the image width
  (for [#1597](https://github.com/pbek/QOwnNotes/issues/1597))

There now is a new release, could you please test it and report if it works for you?
