### ISSUE TITLE
QOwnNotes still uses dark grey icons (Cinnamon DE)

### ISSUE THREAD

**Issue by thegreatyellow67** [pbek/QOwnNotes#1229]
Hi, I'm using QOwnNotes version 19.7.0 (Launchpad PPA - build 549) in Linux Mint 19.1 Cinnamon, unfortunately despite having activated the option "Enforce system icon theme" I have the same problem previously reported in issue #1177 by danbohea

![Screenshot from 2019-06-30 21-29-53](https://user-images.githubusercontent.com/41580754/60401242-b23c6d80-9b7e-11e9-88d6-e46ec36b0d5d.png)

I've tried all the options related to icons, but nothing.

Following there's my configuration:

OS: Linux Mint 19.1 Tessa x86_64
Kernel: 4.15.0-54-generic
DE: Cinnamon 4.2.0
WM: Mutter (Muffin)
WM Theme: Mint-Y-Dark-Aqua
Theme: Mojave-dark-solid-alt [GTK2/3]
Icons: Papirus-Dark [GTK2/3]

Thanks!

**Comment by thegreatyellow67** [comment]
As you can see in the following screenshot, I've enable dark mode icon theme:

![Screenshot from 2019-06-30 22-00-06](https://user-images.githubusercontent.com/41580754/60401498-9aff7f00-9b82-11e9-8de7-f27ed39c150b.png)

but no success.

Sure I'm missing something, because I've verified that in my another stable Linux Mint 19.1 system with Cinnamon, Papirus icon theme and a dark GTK3 theme in QOwnNotes icons are displayed correctly (white colors).

Please help me to further understand how to solve the problem.
Feel free to ask me more informations related to my system or about QOwnNotes settings.
Thanks for your kind attention.

**Comment by pbek** [comment]
It would be actually much easier if you have followed the issue template and posted your settings or use the issue assistant of QOwnNotes... It would even tell what icon theme QOwnNotes found.

I can't reproduce your issue on KDE Neon.

**Comment by thegreatyellow67** [comment]
Sorry, I didn't know about Issue assistant :-(
Now, I've just found it. I can send to you a QOwnNotes Debug Information file.

[QOwnNotes Debug Information.txt](https://github.com/pbek/QOwnNotes/files/3343304/QOwnNotes.Debug.Information.txt)

I hope this time will be helpful.

**Comment by thegreatyellow67** [comment]
Ok, problem solved so fast!

Simply using in my home dir a .xsessionrc file with inside:
export QT_QPA_PLATFORMTHEME=gtk2

In the debug file was:
**QT_QPA_PLATFORMTHEME**: `qt5ct`

so this simple trick helped me to solve.
Thanks a lot for your kind help!

**Comment by pbek** [comment]
Ah, nice. Thank you for the feedback!

**Comment by bipox** [comment]
@thegreatyellow67 I had the same problem in Linux Mint Cinnamon and this fixed it, thank you

**Comment by Fratt** [comment]
Thanks @thegreatyellow67, you helped me as well! Mint Cinnamon 19.3

**Comment by guttermonk** [comment]
Thank you, @thegreatyellow67 - just wanted to add that you need to log out and log back in after adding the .xsessionrc file. This worked for me on Ubuntu 20.04.

And thank you @pbek for the great program.

**Comment by pbek** [comment]
Thank you, @guttermonk! Brightens up my day. 😁
