### ISSUE TITLE
Number and bullet lists issue with inline code tag

### ISSUE THREAD

**Issue by zmni** [pbek/QOwnNotes#1230]
#### Expected behaviour

Keep formating.

#### Actual behaviour

Number dissapear, bullet get push back.

#### Steps to reproduce

Create number/bullet list, start sentence with inline code (backtick).

**Bullet lists**
![bullet](https://user-images.githubusercontent.com/841523/60498765-67873680-9ce1-11e9-88fc-ab7c349fd142.gif)

**Number lists**
![number](https://user-images.githubusercontent.com/841523/60498766-681fcd00-9ce1-11e9-8a82-27b38eaa626c.gif)

#### Output from the debug section in the settings dialog

[Debug is here](https://gist.github.com/zmni/ea05e7866050fc8302baa7af52c16428).

#### Relevant log output in the Log panel

This single warning: `[15:43:26] [warning] QTextCursor::setPosition: Position '215' out of range`.

**Comment by pbek** [comment]
Are you talking just about the preview?

**Comment by zmni** [comment]
Yes. Also happened when you export the preview to pdf.

[Tes_preview.zip](https://github.com/pbek/QOwnNotes/files/3350050/Tes_preview.zip)

**Comment by zmni** [comment]
Also this, the preview bug when you put unordered list after ordered list or ordered list after unordered list. A gap in the last line of the top list. Affecting pdf export.

![1](https://user-images.githubusercontent.com/841523/60514461-b940b880-9d03-11e9-857a-9515458564df.JPG)
![2](https://user-images.githubusercontent.com/841523/60514462-b940b880-9d03-11e9-888a-182cbcb34b0a.JPG)

**Comment by pbek** [comment]
The gaps are long known Qt bugs, I guess you are talking about this #1117 or #437, right?

**Comment by zmni** [comment]
Wow, I should've search it more thoroughly. Thanks @pbek.

**Comment by pbek** [comment]
Sorry that I couldn't help. ;)
