### ISSUE TITLE
New editor schema: <MountainDebo>

### ISSUE THREAD

**Issue by Deboart** [pbek/QOwnNotes#1232]
[MountainDebo.zip](https://github.com/pbek/QOwnNotes/files/3358158/MountainDebo.zip)

I want to submit a new editor schema.

(upload your schema)
![MountainDebo](https://user-images.githubusercontent.com/7719584/60651683-66741780-9e4f-11e9-937d-1dcdc7bb9b62.PNG)

**Comment by pbek** [comment]
Thank you

**Comment by pbek** [comment]
Your *Masked syntax* foreground color is the same as your *Current line background* color. I will change the *Masked syntax* foreground color otherwise links with titles are not readable.

**Comment by pbek** [comment]
## 19.7.2
- added a new editor color schema *MountainDebo* by @Deboart

**Comment by Deboart** [comment]
Патрицио, привет! Спасибо, я заметил этот баг, но ещё не выложил
исправленную версию.

Patrizio, hello!  Thank you, I noticed this bug, but have not yet posted
the corrected version.

сб, 6 июл. 2019 г., 16:18 Patrizio Bekerle <notifications@github.com>:

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Deboart** [comment]
Ок! I will definitely test! Thank you

сб, 6 июл. 2019 г., 17:14 Patrizio Bekerle <notifications@github.com>:

**Comment by Deboart** [comment]
> Your _Masked syntax_ foreground color is the same as your _Current line background_ color. I will change the _Masked syntax_ foreground color otherwise links with titles are not readable.

Thank You

**Comment by pbek** [comment]
I guess that means it works :)
Thank you for your contribution!
