### ISSUE TITLE
Dependency is not satisfiable: libqt5websockets5

### ISSUE THREAD

**Issue by zenny** [pbek/QOwnNotes#1233]
Hi,

followed the instructions at http://www.qownnotes.org/installation and ended up with the:

```
$ sudo gdebi Downloads/markdown-editors/QOwnNotes-19.7.2.deb 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Building data structures... Done 
Building data structures... Done 
This package is uninstallable
Dependency is not satisfiable: libqt5websockets5
```

Still in ubuntu 14.04 (due to opacity of systemd to debug with later versions). Read @pbek saying at https://github.com/pbek/QOwnNotes/issues/1099#issuecomment-450296399 that the library is not mandatory.

Any inputs?

Cheers,
/z

**Comment by pbek** [comment]
Phew, I have no 14.04 around any more to check that and I can't really tell what the `beineri/opt-qt58-trusty` PPA is providing nowadays.

Maybe you can try the QOwnNotes AppImage instead...

**Comment by zenny** [comment]
@pbek Thanks. Tried with the Appimage, and it has two issues:

1. It warns (not error):

```
Warning: libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))
```

2. I tried to change to the dark them, everything became dark except the editor itself (which is the most important for me to avoid straining eyes) :-)

Just my two cents to your useful work.

**Comment by pbek** [comment]
Thank you ;)

1) You can ignore those, only too verbose Qt warnings that you cannot get rid of
2) You need to set your theme on a different settings page (Editors fonts & colors)
