### ISSUE TITLE
Cannot Remove Note Folders

### ISSUE THREAD

**Issue by teamayu** [pbek/QOwnNotes#1234]
Hello,

Great software, thank you.

The issue I have is, I click to add a note folder, it works fine. But, if I click to remove it, nothing happens. I've got 5 note folders, but can`t remove any of them. Is there a setting somewhere I need to enable?

Thank you.

**Comment by pbek** [comment]
I cannot reproduce that. Removing note sub-folders works fine for me.

Could you please use the issue assistant in the `Help` menu to post this issue so you can provide needed information more easily?

The menu entry is named `Post questions, feature requests or issues`.

**Comment by pbek** [comment]
And are you talking about `Note Folders`? Or note sub-folders?

**Comment by teamayu** [comment]
The note folders. So, by clicking 'Note > Setup note folders'. I have found the issue. :)

If you click to remove a note folder and check the 'Dont ask again' checkbox, but don't remove the note (So, click 'No') the note doesn't delete as expected. But then if you click to remove a note, nothing happens. So, clicking 'Dont ask again' suppresses the message box, but also kills the delete process.

**Comment by pbek** [comment]
Ok, so you really were talking about Note Folders. ;)

**Comment by pbek** [comment]
## 19.7.6
- the **immediate focus** on the `Don't ask again!` **checkbox** for
  **message dialogs** was now **disabled**, because this would lead to
  accidentally checking the checkbox

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by teamayu** [comment]
Thanks Patrizio, seems to be fine now.

**Comment by pbek** [comment]
Great, thank you for testing!
