### ISSUE TITLE
Duplicating note folder shortcuts in shortcut settings when switching note folders

### ISSUE THREAD

**Issue by teamayu** [pbek/QOwnNotes#1235]
Hello,

I have added two Note folders, 'Notes' & 'Development'. In the shortcuts option, I see both listed 5 times. What are they all for?

![1](https://user-images.githubusercontent.com/10624092/61168081-7d66e800-a57a-11e9-967a-ec3803900634.png)
![2](https://user-images.githubusercontent.com/10624092/61168082-7dff7e80-a57a-11e9-85b2-ce1f96ecc48a.png)

Thank you.

**Comment by teamayu** [comment]
Ok, it seems to have corrected itself now. So, looks like qutting the software and re-opening it did the trick.

This can be closed, thank you.

**Comment by pbek** [comment]
Thank you for reporting, this was supposed to be fixed a long while ago.

**Comment by teamayu** [comment]
No problem. It just came back again, so seems intermittent.

**Comment by pbek** [comment]
## 19.7.3
- disabled shortcuts for the *Note folders* menu in the *Shortcuts settings* because shortcuts for them are not supported

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by teamayu** [comment]
Yes, works great. btw, thanks Patrizio for this fabulous software.

**Comment by teamayu** [comment]
No, still the same. When I launched the software after applying the update, it was ok. The later on, all the Note folders are duplicated again.

**Comment by pbek** [comment]
Are you sure you were using version 19.7.3? You shouldn't see `Note folders` at all in the list.

**Comment by teamayu** [comment]
Sorry Patrizio, my fault. You were right, I hadn`t updated the system correctly. It's working fine now.

**Comment by pbek** [comment]
Great, thank you for testing!
