### ISSUE TITLE
Note folder name not shown in main menu

### ISSUE THREAD

**Issue by teamayu** [pbek/QOwnNotes#1236]
Hi Patrizio,

When you add a Note folder, you specify a name. The tooltip says 'This name will be viewed in all the menus'. But in the tree menu it's actually showing the folder name.

![1](https://user-images.githubusercontent.com/10624092/61168973-c6be3400-a588-11e9-942f-efef7a7a65de.png)
![2](https://user-images.githubusercontent.com/10624092/61168974-c6be3400-a588-11e9-950b-981c32688bac.png)

That a setting I'm missing?

Thank you.

**Comment by pbek** [comment]
Without providing your settings and so on (please read the issue template) it's very hard to help you.

**Comment by teamayu** [comment]
I thought the screenshot would say it all? The name isn't being used.

Not a big deal anyway.

**Comment by pbek** [comment]
> 'This name will be viewed in all the menus'. But in the tree menu it's actually showing the folder name

the note subfolder widget isn't supposed to show the note folder name. there is the note folder widget for that... there are a lot of ways to customize the the sub folder widget in the panels settings.

> I thought the screenshot would say it all? The name isn't being used.

A screenshot doesn't tell me anything about which version you are using or on which platform you are using QOwnNotes or what your settings actually are...
