### ISSUE TITLE
Cannot Set External Editor

### ISSUE THREAD

**Issue by teamayu** [pbek/QOwnNotes#1237]
Hi Patrizio,

The option to set an external editor does not work. The path is all wrong.

QOwnNotes is located at:
C:/Portable-Software/QOwnNotes/

My editor (CudaText) is at:
C:/Portable-Software/CudaText

When I enter the path to the external editor as:
C:/Portable-Software/CudaText/cudatext.exe

Then save, QOwnNotes saves it as:
C:/Portable-Software/QOwnNotes/Data/../../CudaText/cudatext.exe

And of course it doesn't work.

**Comment by pbek** [comment]
Can you please post the output from the debug settings (see issue template).

**Comment by pbek** [comment]
The path `C:/Portable-Software/QOwnNotes/Data/../../CudaText/cudatext.exe` looks ok to me, it should amount to `C:/Portable-Software/CudaText/cudatext.exe`. The portable mode needs to use relative paths to access other directories...

**Comment by teamayu** [comment]
Ok, no problem. Sorry, I will post the output next time. With the above paths, nothing happens when I click to open the note in an external editor. Again, not a big deal.

**Comment by pbek** [comment]
Without the debug output and your system configuration I cannot help you.

**Comment by teamayu** [comment]
I understand, sorry. It`s Windows 10, 64bit portable btw.

I have installed the 'External note open' script and that works great. I double click a note, it opens in the external editor. And the script setting shows the correct path. It's just the actual setting to use an external editor that doesn't work for me.

**Comment by pbek** [comment]
Without the debug output and your system configuration I cannot help you.
