### ISSUE TITLE
QOwnNotes crashes when navigating to next note using Alt-Down/Up

### ISSUE THREAD

**Issue by animeshb** [pbek/QOwnNotes#1238]
#### Expected behaviour

Navigate to next note without crashing.

#### Actual behaviour

Application crashes (quits) instead of navigating to next note.

#### Steps to reproduce

Open next note using keyboard shortcut Alt-Up or Alt-Down

#### Output from the debug section in the settings dialog

Nothing is being written to the debug section in the log panel or the debug log that is available at `.local/share/PBE/...` when I press the shortcut key Alt-Up or Alt-Down. I did not notice this until this version. I have always used note navgation keyboard shortcuts.

#### Relevant log output in the Log panel

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sun Jul 14 10:39:24 2019`
**Version**: `19.7.2`
**Build date**: `Jul  6 2019`
**Build number**: `551`
**Platform**: `linux`
**Operating System**: `BunsenLabs GNU/Linux 8.9 (Hydrogen)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.7.1`
**Qt Version (runtime)**: `5.11.3`
**Portable mode**: `no`
**Settings path / key**: `/home/animesh/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/animesh/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note fol

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue.

**Comment by pbek** [comment]
That is a regression ("over-optimization") from version 19.7.1.

## 19.7.3
- fixed a crash when navigating between notes with the <kbd>Alt + Up</kbd> and
  <kbd>Alt + Down</kbd> keys

**Comment by animeshb** [comment]
I appreciate your quick response. You are awesome!

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by animeshb** [comment]
I use the Debian repository for updates. I will wait and test it when it is available.

Regards.

**Comment by animeshb** [comment]
It works now! :+1:

**Comment by pbek** [comment]
Great, thank you for testing!
