### ISSUE TITLE
OS X: Right click in Edit view opens context menu too far to the left

### ISSUE THREAD

**Issue by Commenter123** [pbek/QOwnNotes#124]
Steps to reproduce:
1. Open a new Note
2. Right click in the Edit window (where you type in your text)
3. See the screenshot below

![bildschirmfoto 2016-03-29 um 16 58 41](https://cloud.githubusercontent.com/assets/13712808/14112631/c09f201e-f5cf-11e5-931c-b4099661cbbb.png)

**Comment by pbek** [comment]
Now that's interesting, thank you for the report!

**Comment by pbek** [comment]
Will be fixed in the next release, could you please then be so kind and report if it worked for you?

**Comment by pbek** [comment]
Version 1.3.0 is now released.
