### ISSUE TITLE
Option to set hotkey to open application from system tray

### ISSUE THREAD

**Issue by teamayu** [pbek/QOwnNotes#1241]
Not sure if this option could be added in a future version? The ability to set a hotkey to open the application when closed/minimized to the tray. Rather that clicking the icon each time.

Thank you.

**Comment by pbek** [comment]
That's very tricky. Please head over to #44.

**Comment by teamayu** [comment]
Thank you.

**Comment by pbek** [comment]
You may want to test https://github.com/pbek/QOwnNotes/issues/44, @teamayu

**Comment by teamayu** [comment]
Excellent, thanks Patrizio, that works great.

**Comment by pbek** [comment]
Thank you. Soon you will get served at #1324. :grin:
