### ISSUE TITLE
[Q] Setup dialog randomnly appears on launch

### ISSUE THREAD

**Issue by teamayu** [pbek/QOwnNotes#1242]
When I launch QOwnNotes, sometimes the setup dialog appears. This is random, it doesn't happen all the time. Debug info enclosed.

![img1](https://user-images.githubusercontent.com/10624092/61197304-b7fd8b80-a706-11e9-9b98-a0a1139e8167.png)

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mon Jul 15 13:43:43 2019`
**Version**: `19.7.3`
**Build date**: `Jul 14 2019`
**Build number**: `4388`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.12.2`
**Qt Version (runtime)**: `5.12.2`
**Portable mode**: `yes`
**Settings path / key**: `C:/Portable-Software/QOwnNotes/Data/PBE/QOwnNotes.ini`
**Application database path**: `C:\Portable-Software\QOwnNotes\Data\QOwnNotes.sqlite`
**Application arguments**: `C:\Portable-Software\QOwnNotes\QOwnNotes.exe`, `--portable`
**Qt Debug**: `0`
**Locale (system)**: `en_GB`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `133`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Note folders

**currentNoteFolderId**: `2`

### Note folder `Notes`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `-1`
**localPath**: `C:\Portable-Software\QOwnNotes\Data\Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Portable-Software\QOwnNotes\Data\Notes\notes.sqlite`

### Note folder `Development`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `C:\Portable-Software\QOwnNotes\Data\Dev`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `XXX`
**database file**: `C:\Portable-Software\QOwnNotes\Data\Dev\notes.sqlite`

### Script `External note open`

**id**: `1`
**path**: `C:\Portable-Software\QOwnNotes\Data\scripts\external-note-open\external-note-open.qml`
**variablesJson**: 
```
{
    "executablePath": "C:\\Portable-Software\\CudaText\\cudatext.exe"
}
```
**identifier**: `external-note-open`
**version**: `1.0.0`
**minAppVersion**: `18.05.4`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `23`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `C:/Portable-Software/QOwnNotes/_Backup`
**FileDialog/LastPath-ExternalEditor** (QString): `C:/Portable-Software/CudaText`
**FileDialog/LastPath-ScriptSettingsFile-external-note-open-executablePath** (QString): `C:/Portable-Software/CudaText`
**FileDialog/LastPath-SettingsExport** (QString): `C:/Portable-Software/QOwnNotes/_Backup`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2019-07-15T13:36:51.345`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-2** (QStringList): `In Progress`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,11,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Calibri,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Courier New,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Calibri,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 24 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 46 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `23`
**NoteHistoryCurrentIndex-2** (int): `45`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `true`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `2`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableSocketServer** (QString): `false`
**externalEditorPath** (QString): `../../CudaText/cudatext.exe`
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full-vertical`
**insertTimeFormat** (QString): `dd-MM-YYYY hh:mm:ss`
**interfaceFontSize** (QString): `12`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `15`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `false`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `0`
**notesPath** (QString): `Dev`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): *empty*
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloud/userName** (QString): *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `initial`
**recentNoteFolders** (QStringList): `C:/Portable-Software/QOwnNotes/Data/Notes, C:/Portable-Software/QOwnNotes/Data/../../../Users/David/Dropbox/Ayumi/_NOTES/_NOTES`
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2019-07-13T15.58.27, Note 2019-07-13T15.56.42, Note 2019-07-13T15.56.29, Note 2019-07-13T15.56.22, Note 2019-07-13T15.56.07, Note 2019-07-13T15.55.14, Note 2019-07-13T15.55.07, Note 2019-07-13T15.53.11, Note 2019-07-13T15.52.10, Note 2019-07-13T15.41.08, Note 2019-07-13T14.03.56, Note 2019-07-12T17.24.10, Note 2019-07-12T17.22.07, Note 2019-07-12T16.37.06, Note 2019-07-07T19.40.22, Note 2019-07-07T19.40.10`
**savedSearches/noteFolder-2** (QStringList): `Note 2019-07-15T11.36.55, Note 2019-07-14T00.33.49, Note 2019-07-13T16.46.25, Note 2019-07-13T16.45.58, Note 2019-07-13T16.36.26, Note 2019-07-13T16.34.28, Note 2019-07-13T16.29.03, Note 2019-07-13T16.18.42, Note 2019-07-13T16.17.16, Note 2019-07-13T16.16.42`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `false`
**skipVersion** (QString): `19.7.3`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `true`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Export_note_as_PDF_text, actionShow_local_trash`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QString): `actionInsert_image`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Main Interface`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\David\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `DESKTOP-RJH6M2Q`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\David`
**LOCALAPPDATA**: `C:\Users\David\AppData\Local`
**LOGONSERVER**: `\\DESKTOP-RJH6M2Q`
**NUMBER_OF_PROCESSORS**: `4`
**OneDrive**: `C:\Users\David\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files (x86)\AOMEI Backupper;C:\Users\David\AppData\Local\Microsoft\WindowsApps;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PORTABLEPATH**: `C:\Portable-Software`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `AMD64 Family 22 Model 48 Stepping 1, AuthenticAMD`
**PROCESSOR_LEVEL**: `22`
**PROCESSOR_REVISION**: `3001`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\David\AppData\Local\Temp`
**TMP**: `C:\Users\David\AppData\Local\Temp`
**USERDOMAIN**: `DESKTOP-RJH6M2Q`
**USERDOMAIN_ROAMINGPROFILE**: `DESKTOP-RJH6M2Q`
**USERNAME**: `David`
**USERPROFILE**: `C:\Users\David`
**windir**: `C:\WINDOWS`
</details>

**Comment by pbek** [comment]
When that happens QOwnNotes can't find its settings. Do you always have permissions to your `C:/Portable-Software/QOwnNotes/` folder, especially to `C:/Portable-Software/QOwnNotes/Data/PBE/QOwnNotes.ini`? Do you run QOwnNotes in different folders and maybe without `--portable` parameter?

**Comment by pbek** [comment]
The welcome dialog also is shown if the note folder doesn't exist...
https://github.com/pbek/QOwnNotes/blob/05066880fdba21e91451c6fd0c8f6208ffb49197/src/main.cpp#L211-L218

**Comment by teamayu** [comment]
No, I only have QOwnNotes in the one place and it's the portable version. I have it in the tray, so when I click to open it's fine. But if I close it and re-open, randomnly that dialog appears. Not a big deal. If I can find some pattern to it happening I'll let you know.

Should I still use the --portable param for the portable version?

**Comment by pbek** [comment]
The only way to make the welcome dialog pop up is if QOwnNotes doesn't find a note path setting or the note folder doesn't exist...

Are you really using QOwnNotes in a "portable" (as on a removable medium, that you are carrying around)? It doesn't seem to me. I guess you don't need the portable mode, QOwnNotes doesn't install anything. The only difference you would "feel" is that your settings would be written to your registry, but you can always remove them with QOwnNotes.

**Comment by teamayu** [comment]
No, you are right, I don't. At the moment they are on the C drive. My external drive recently gave in, so I moved everything over from a backup. I haven`t copied them back to removeable media yet.

So, best to close this message now and if the problem persists when I`m back on an external drive I'll let you know. I do need the external drive as I have several laptops and it's pretty handy.

**Comment by pbek** [comment]
The portable mode seems to work for a few 100 people. I'm not sure what went wrong for you.

**Comment by teamayu** [comment]
It happens almost every time I launch the program. Maybe it's something to do with having the software load in the tray at startup? I'll disable that option and see if it makes any difference.

**Comment by pbek** [comment]
Have you also lost your settings when you get the welcome dialog?

**Comment by teamayu** [comment]
No, the settings are in the same place as always. Sometimes I close the software, re-open and on maybe the 4th or 5th time it loads ok. The other times the setup dialog appears.

**Comment by pbek** [comment]
You could try to enable the debug log file to see if anything gets loggend (but will get turned off if you loose your settings)... You could also try to run QOwnNotes in your terminal (`cmd.exe`) to see if there are any errors.

**Comment by teamayu** [comment]
Ok, thanks Patrizio. It's not bothering me too much, once it opens it's all good.

**Comment by pbek** [comment]
ok :)

**Comment by teamayu** [comment]
As a follow up..

Double clicking the exe file always launches the setup dialog using the portable version. Even on an external drive. Using the --portable param does fix the issue, so all good.

**Comment by pbek** [comment]
Could something block QOwnNotes to write to the registry?

**Comment by pbek** [comment]
Ah. Sorry. Portable version. No registry there.

**Comment by teamayu** [comment]
Yes. I don`t think anything is blocking it, I have too many portable programs all working fine from the same location. As I said, it's not an issue as the --portable param works great.

**Comment by redsigma** [comment]
I am facing this problem as well and i did some workarounds to get it working but now i wanted to make a .desktop shortcut and it doesn't seem to work. I am using debian 11

I need to use the app in `--portable` mode. I have noticed that this problem happens when i launch the app from a different folder

Example:

1. App is in `~/.local/apps/bin/qownnotes.AppImage`
2. `cd ~/.local/apps/`
3. running `./bin/qownnotes.AppImage --portable &` causes the dialog to show
4. `cd ~/.local/apps/bin/`
5. running `./qownnotes.AppImage --portable &` launches properly

Now if i try to make a `.desktop` file in `~/.local/share/applications/qownnotes.desktop` and launch it from the `Application Finder` menu, then the welcome dialogue shows.

Same dialogue shows if i add the absolute path  `~/.local/apps/bin/qownnotes.AppImage --portable `to the list of `Session and Startup`apps`  apps

I think a fix can be to have a bash script which cds into the `~/.local/apps/bin/` folder and then launches it from there on startup but this doesn't look like a solution.

As for my workaround, i keep a backup  of  `QOwnNotes.sqlite`  and `PBE/QOwnNotes.ini` so i can easily replace them in case the app gets fully reset again. By fully reset i mean that all the settings/scripts are being lost after i complete the `welcome setup dialogue`. Fortunately the notes are still present.

I think the best solution is for the app to have an argument where i can specify the location of the Notes. The command could look like:

1.  `~/.local/apps/bin/qownnotes.AppImage --portable --path_data "~/.local/apps/bin/"`  
2.  `~/.local/apps/bin/qownnotes.AppImage --portable --path_data "~/.config/qownnotes/"`  

I believe this solution would be good because currently i have all my app configs in the `./config` folder and only qownnotes config is handled separately

**Comment by pbek** [comment]
> I think the best solution is for the app to have an argument where i can specify the location of the Notes

There currently is a workaround for AppImages in that takes the AppData path from the full path of the AppImage...

https://github.com/pbek/QOwnNotes/blob/a7c56f879c7b1097c68d3c45ba92315d78cd1a9f/src/utils/misc.cpp#L568-L574

If you have an issue with that best open a new issue and link this comment.
