### ISSUE TITLE
opensuse download mirrors failing since couple of days

### ISSUE THREAD

**Issue by animeshb** [pbek/QOwnNotes#1245]
#### Expected behaviour
Program gets updated when I run apt-get
#### Actual behaviour
apt-get unable to connect to http://download.opensuse.org
#### Steps to reproduce
run apt-get on debian machine
#### Relevant log output in the Log panel

```

Err:9 http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Debian_9.0  InRelease
  Cannot initiate the connection to download.opensuse.org:80 (2620:113:80c0:8::13). - connect (101: Network is unreachable) Could not connect to download.opensuse.org:80 (195.135.221.134), connection timed out
Reading package lists... Done                                 
W: Failed to fetch http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Debian_9.0/InRelease  Cannot initiate the connection to download.opensuse.org:80 (2620:113:80c0:8::13). - connect (101: Network is unreachable) Could not connect to download.opensuse.org:80 (195.135.221.134), connection timed out

```

**Comment by pbek** [comment]
I can open <http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Debian_9.0> just fine. Updates also work on an other device of mine.

What does a traceroute with e.g. `mtr download.opensuse.org` tell you?

**Comment by animeshb** [comment]
80.231.153.66 and ae-1-3113.ear2.London1.Level3.net

is where the packets are dropping.

**Comment by pbek** [comment]
I don't have that hop in my list. I think you have a routing problem to ftp.opensuse.org. May you can try some vpn service to get around your routing problems..

**Comment by animeshb** [comment]
Okay, good to know the mirror is not down or unreachable.
I will research a bit more and see what I can do. Thanks for checking.

**Comment by pbek** [comment]
http://download.opensuse.org is no mirror, it's **the** server 😆 (the open build server)

**Comment by animeshb** [comment]
Sorry.
It works now.

**Comment by pbek** [comment]
Great :)
