### ISSUE TITLE
Respect user's cursor blink setting and/or provide checkbox to turn blink on or off

### ISSUE THREAD

**Issue by mark-summerfield** [pbek/QOwnNotes#1246]
On Windows Qt apps generally respect the user's cursor blink setting (off in my case). However on Linux Qt 5 apps don't seem to respect the Gtk setting nor the qt5ct (Qt 5 configuration tool) setting.
Some people (including me) cannot use s/w that has a blinking cursor. See [Blinking](http://www.jurta.org/en/prog/noblink).
It is an easy setting to add: just a checkbox and set QApplication cursorFlashTime.

**Comment by pbek** [comment]
To my knowledge you cannot force a Qt app to abide to a arbitrary cursor blinking setting (without injecting shared libraries into the application).

But I could implement a setting to use <https://doc.qt.io/qt-5/qapplication.html#cursorFlashTime-prop> to turn it off.

**Comment by pbek** [comment]
## 19.7.8
- you can now turn off cursor blinking in the *Editor settings*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by mark-summerfield** [comment]
I can see that the packages are building... I've now tried the Ubuntu bionic AMD64 build. I started it and the caret was blinking. Then I went to Note->Settings->Editor and checked the Disable Blinking checkbox and blinking stopped. I then quit and restarted and the setting was preserved.
Thank you!

**Comment by pbek** [comment]
Great, thank you for testing!
