### ISSUE TITLE
Option for next, previous or go the exact matched record

### ISSUE THREAD

**Issue by prog20901** [pbek/QOwnNotes#1247]
After search, it would be great if we can go to exact matched record count or next record found or previous match found.

**Comment by pbek** [comment]
Thank you for your suggestion.
I guess you are talking about the global search (over all notes in the note folder).

**Comment by prog20901** [comment]
Yes, you are right

**Comment by pbek** [comment]
## 19.7.9
- if you are browsing notes while there are **words in the note search panel**
  the **search dialog in the note** will now be **opened automatically** and
  **search for the words** entered in the note search panel

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Airgunster** [comment]
Originally replied in https://github.com/pbek/QOwnNotes/issues/1248, but actually this one is more relevant for this issue.

@pbek just checked new release (v. 19.7.10), and still see same issue, tried to search for queries like `"tcp/"` and "running slow", still see search on the Note appearing with double quotes (and with double quotes it doesn't work on the Note itself). Here is the screenshot for more details,
<img width="1495" alt="2019-07-29 - Exact search v  19 7 10" src="https://user-images.githubusercontent.com/7937957/62015026-c1273780-b19f-11e9-9977-56492a0fb430.png">

P.S. Thanks anyway for all the work done!

**Comment by pbek** [comment]
Thank you, I will take a look at that!

**Comment by pbek** [comment]
## 19.7.11
- `"` characters will be now cut out of the search text in the local search text
  when searching for text globally

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Airgunster** [comment]
Thanks @pbek ! Works like a charm!

**Comment by pbek** [comment]
Great (finally), thank you for testing! :)

**Comment by pbek** [comment]
## 19.8.1
- you will now see how many **search results** there are when **searching in a note**
  and at **what search result** you **currently** are
    - the search will now start from top when search parameters are changed 
    - regular expression search restart at top was fixed
    - the text cases in the note text edit search bar are now fixed and more
      tooltips are added


There now is a new release, could you please test it and report if it works for you?
