### ISSUE TITLE
Narrow down the search results with count

### ISSUE THREAD

**Issue by prog20901** [pbek/QOwnNotes#1248]
Number of hits found should be part of the search. Ex: 
Branham - 1000 hits
Branham is a propher of God - 500 hits
Branham is a prophet of God for this generation - 230 hits
This will help the user to narrdown the search more..

might be bit sluggish however the narrow down of results are very important when the number of hits found are huge....Any user would always like to search and lookup for few records and not all always.

**Comment by pbek** [comment]
Thank you for your suggestion.

For me it usually is more important to see in how many notes the keyword is found.
Do you have any suggestions in what way (in the user interface) this information should be presented?

**Comment by prog20901** [comment]
Just like Google Search which shows the results and in the brackets give the count found for the given text

**Comment by pbek** [comment]
Google search is a web page 😄  QON is a desktop application. I have no really good place in the user interface to put such information.

**Comment by prog20901** [comment]
Why don't you display in the search bar itself in brackets the count. Example, go to http://table.branham.org/#/main and type "holy ghost" and you will see the list with count. Just an example

**Comment by pbek** [comment]
Thank you for your example but this still is a web page and no Qt application 😁

**Comment by prog20901** [comment]
Example of desktop application - https://raw.githubusercontent.com/xiaoniu-578fa6bff964d005/docfetcher/type-ahead/dev/screenshots/type-ahead-search.gif

**Comment by prog20901** [comment]
Another example of desktop application. However you need to bring the search in a new window - https://www.prabhupada.com/Vedabase/images/VB-programscr4.jpg

**Comment by pbek** [comment]
> Example of desktop application - https://raw.githubusercontent.com/xiaoniu-578fa6bff964d005/docfetcher/type-ahead/dev/screenshots/type-ahead-search.gif

this one might work, but I would have to do some experiment if I can properly add and remove new columns and persuade the user interface to resize the other column to show the amount of hits in a note

the latter example seems to need a different "advanced" dialog

**Comment by pbek** [comment]
...was a bit tricky

## 19.7.9
- if you **search for text in all notes** you will now **see how many times**
  the first word of your **search term occurred** in each note in the note list
  in a new column
    - the new column will be automatically resized to be visible next to the
      note name without scrolling

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by prog20901** [comment]
I have tested. one issue is

typed a word and it shows the list of files the occurances found. However i
am unable to find the exact match. it goes with or condition

i searched for The Mystery it returns several results. However it puts OR
condition.

The | Mystery

I am unable to find the exact word

Example

When i searched like "The Mystery" like in google it gives empty results.

Need a help or good documentation if the above search approach is wrong

**Comment by pbek** [comment]
> However it puts OR condition.

Yes, it was working that way and still is.

**Comment by Airgunster** [comment]
@pbek Thanks for that feature (really love it)!

> Yes, it was working that way and still is.
I think the issue here is when you use exact match, i.e. for queries like `"tcp /"` or `"this is what you're looking for exactly"`. If you type `"tcp /"` or `"this is what you're looking for exactly"` type of queries in global search it will show _Find and Replace_ dialogue inside the Note itself and will not allow you to search on the note via that exact word query.

Would be nice to have it fixed (to be able to do a global search with exact words and be able select a Note and continue that exact words search inside that selected Note).

Thanks a lot in advance!

**Comment by pbek** [comment]
## 19.7.10
- the search result count ([#1248](https://github.com/pbek/QOwnNotes/issues/1248))
  and the automatic search inside the current note ([#1247](https://github.com/pbek/QOwnNotes/issues/1247))
  will now also support exact searches like `"exact phrase"`

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by iolivier87** [comment]
This feature is awesome ! Thank you
"exact phrase" works very well for me

But if I search 2 words or more without quotes, the "find" box becomes "replace" and my words are displayed in it like this : (diff\érent|du)

> the new column will automatically be resized to be visible next to the
> note name without horizontal scrolling
The automatic display is good for me but a useless horizontal slider appears at the bottom. It is useless because when I use it, it shows empty space at the right of the number instead of the end of the note title

**Comment by pbek** [comment]
Multiple words are searched via regular expressions. 

The scrollbar is created automatically by the QTreeWidget, there is not much I can do about that.

**Comment by pbek** [comment]
And I will rather take the scrollbar then loosing more of the note name.

**Comment by iolivier87** [comment]
Ok

**Comment by Airgunster** [comment]
@pbek just checked new release (v. 19.7.10), and still see same issue, tried to search for queries like `"tcp/"` and "running slow", still see search on the Note appearing with double quotes (and with double quotes it doesn't work on the Note itself). Here is the screenshot for more details,
<img width="1495" alt="2019-07-29 - Exact search v  19 7 10" src="https://user-images.githubusercontent.com/7937957/62015026-c1273780-b19f-11e9-9977-56492a0fb430.png">

**Comment by pbek** [comment]
Thank you, I will take a look at that!

**Comment by pbek** [comment]
But I guess you are talking about #1247, right?

**Comment by pbek** [comment]
Thanks ;)

**Comment by pbek** [comment]
## 19.7.11
- the column size of the search count in the note list was reduced

the scroll bar is still there, but a bit smaller

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by iolivier87** [comment]
Yes, it is much better now : I can even avoid the scrollbar by adjusting the panel width.
Thank you very much

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by iolivier87** [comment]
Surprisingly, the scrollbar comes back each time now. I don't understand why it disappeared on my computer last night. It's not very annoying, though.

**Comment by prog20901** [comment]
I observed the same..However it works like awesome....Also, replace button is coming by default when we do just a search. Replace can be made other option instead of part of the search or configurable to bring replace with search.

**Comment by pbek** [comment]
The "replace button" also shows a "Mode selector" that is switched to "Regular expression".

**Comment by pbek** [comment]
## 19.10.5
- a setting to disable the search result count calculation was added to improve search speed
  in note folders with a lot of notes (for [#1248](https://github.com/pbek/QOwnNotes/issues/1248), thank you @smokris)

**Comment by pbek** [comment]
There now is a new release, @smokris could you please test it and report if it works for you?

**Comment by smokris** [comment]
Works as expected.  Thanks!

**Comment by pbek** [comment]
Great! Thank you!
