### ISSUE TITLE
Keep tab position

### ISSUE THREAD

**Issue by toxpal** [pbek/QOwnNotes#1249]
It would be very useful if QOwnNotes editor keeps tab position like virtually all other text editors.

Now, if I use TAB before writing some text, it's only valid for current line. As soon as I press ENTER, I need to manually insert TAB again, which isn't super-exciting when working with medium or large lists.

I looked at settings, but couldn't find such option. Once again, thank you for your consideration.

**Comment by pbek** [comment]
Where in markdown there can be a `Tab` that does anything on its own? The only place that comes to mind is in lists, like `<Tab>-`. And in lists the Tab-depth is restored. Where do you use those Tabs?

**Comment by toxpal** [comment]
I use them in every single note. See screenshot (blue line indicates 1 x TAB, red line indicates 2 x TABS) - https://i.postimg.cc/14h80WVh/tabs.png

**Comment by pbek** [comment]
Ok, I see. You are not using markdown in QOwnNotes. :)

I'll still add the FR to my list. ;)

**Comment by toxpal** [comment]
> Ok, I see. You are not using markdown in QOwnNotes. :)

I do, but not all the time. Very often I paste content into QOwnNotes from other text files, and this is when I need to manually press TAB for every new item in the list.

**Comment by pbek** [comment]
## 19.7.11
- whitespaces at the beginning of the current line are now reproduced in the
  next line too when pressing <kbd>Return</kbd> in the note editor

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by toxpal** [comment]
Installed and tested - works great. Thank you for such extremely fast response.

**Comment by pbek** [comment]
Great, thank you for testing!
