### ISSUE TITLE
[F] Go to Option like Find, Previous, Next

### ISSUE THREAD

**Issue by prog20901** [pbek/QOwnNotes#1250]
#### Expected behaviour

Assume a word exist in 100 places. Now want to go to the 95th place. Currently there is no way to go to the exact match place. It would be great if an option is provided.

#### Actual behaviour

Currently there is no way to go to the exact match place.

#### Steps to reproduce

1. Search for a text which appears in multiple places
2. How to go to the nth place?

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

**Comment by pbek** [comment]
Why would like to have this feature and how should that look in the user interface?

**Comment by prog20901** [comment]
Many has the goto option and it is not something new. Example, you can include in the find option itself as a text field with go if possible (Ex: https://superuser.com/questions/487507/how-can-i-find-nth-character-in-notepad/487521 and https://stackoverflow.com/questions/8863802/in-notepad-how-do-i-find-the-nth-occurrence-of-a-string/10803179). That gives more usability and flexibility for the user.

**Comment by pbek** [comment]
I still fail to see a use case for this feature, did you try to play with regular expressions?

**Comment by prog20901** [comment]
Can you please help with few sample of regular expressions? That would be
great if already available. Also, add them to documentation if missed out.

**Comment by pbek** [comment]
https://lmgtfy.com/?q=regular+expression+nth+match

**Comment by prog20901** [comment]
I saw the gif..but user has to try several regular expression by
searching..an example would be easy to follow for all

ex: search for word "test" in all the notes

**Comment by pbek** [comment]
I don't have an example. I would need to experiment with regular expressions just like you would.

**Comment by pbek** [comment]
I will close this issue until there is more information.
