### ISSUE TITLE
Readable or non-editable by default

### ISSUE THREAD

**Issue by prog20901** [pbek/QOwnNotes#1251]
I have huge text files and imported the same. However i don't want to edit even mistakenly.

Can we have a configuration or setting or option to make the notes non-editable ? By default it is editable, however we can able to make it as non-editable.

I am planning to use this as read-only for search purposes...In this way i can also gave the exact folder to other user as portable so that they can open and do the search and couldn't modify by default.

**Comment by pbek** [comment]
There already is a button in the main menu for that. Plus you can just press „Escape“ while in the note text edit to turn the „read only mode" on.

**Comment by smokris** [comment]
You can create a script that automatically changes to read-only when you open a note:

    import QtQml 2.0
    import QOwnNotesTypes 1.0
    
    QtObject {
    	function noteOpenedHook(note) {
    		script.triggerMenuAction("actionAllow_note_editing", 0);
    	}
    }

**Comment by pbek** [comment]
Thank you @smokris, I totally forgot that I added a 2nd parameter to `triggerMenuAction`. :laughing: 
http://docs.qownnotes.org/en/develop/scripting/README.html#triggering-a-menu-action

I guess that answers that question.

**Comment by prog20901** [comment]
Please add the above to documentation if possible.

**Comment by pbek** [comment]
You can create a wiki page at https://github.com/pbek/QOwnNotes/wiki if you want.
