### ISSUE TITLE
Import evernote files with same title overwrites some files

### ISSUE THREAD

**Issue by jjisnow** [pbek/QOwnNotes#1252]
#### Expected behaviour
Upon importing some 100 evernote files with the same name from an 'enex' file, the import engine appends the timestamp and a counter if imported in the same second.

#### Actual behaviour
QownNotes overwrites files with similar or the same name in the same second

#### Steps to reproduce
Import 100 evernote notes from 1 file with differing content

**Comment by pbek** [comment]
Could you please provide an enex file where that happens.

**Comment by pbek** [comment]
And can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log widget?

**Comment by pbek** [comment]
I don't have this issue for example if I import the same enex file twice. The note files from the 2nd import get an other file name.

**Comment by jjisnow** [comment]
It has to be identical note names imported in the same second from a single
enex file. If send it, but I'm away from the main computer atm

**Comment by pbek** [comment]
## 19.8.1
- when a **note** is about to get the **same filename** as an existing note now
  a **number** is **added** instead of the current date and time to prevent name
  clashes when multiple notes are created in the same second

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by jjisnow** [comment]
sorry for the delay, here's the file with the notes, but there's an error in the new release - it doesn't import 142 notes, only 117 out of the total.



[Fuel notes.zip](https://github.com/pbek/QOwnNotes/files/3488416/Fuel.notes.zip)

**Comment by pbek** [comment]
Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging.

**Comment by pbek** [comment]
> Fuel notes.zip

I'm sorry, I couldn't extract the zip on Linux nor Windows.

**Comment by jjisnow** [comment]
It should be a simple .enex file and it seemed to work opening it in 7zip after redownloading it on windows here.

**Comment by jjisnow** [comment]
Here it is again.
[Fuel-notes.zip](https://github.com/pbek/QOwnNotes/files/3489033/Fuel-notes.zip)

**Comment by pbek** [comment]
> Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging.

**Comment by jjisnow** [comment]
This may be a bit long winded, but maybe it has something in the first few renames from the debug log. I can't import the log directly as there is a 65536 limit on comments.

[debug.zip](https://github.com/pbek/QOwnNotes/files/3489860/debug.zip)

**Comment by pbek** [comment]
Thank you, so which notes were actually not imported for example?

**Comment by jjisnow** [comment]
Not sure exactly, it's just the total number of notes that doesn't line up

**Comment by pbek** [comment]
Then I'll move this to #1261, because I'm not sure yet when I have time to manually compare 142 entries in the enex file with 117 note files. 😆
