### ISSUE TITLE
Need to type "i" to type into a note

### ISSUE THREAD

**Issue by PurplePlums** [pbek/QOwnNotes#1253]
#### Expected behaviour

I expect that I can type into a note right away

#### Actual behaviour

The app starts with any input to be a "command" (as shown in the left bottom corner)

#### Steps to reproduce

If I press "i", "insert" appears and typing becomes possible

#### Output from the debug section in the settings dialog

Didn't figure out that yet, sorry...

**Comment by pbek** [comment]
Can you please post the output from the debug settings (see issue template).

**Comment by pbek** [comment]
It almost appears you have the vi-mode turned on.

**Comment by PurplePlums** [comment]
That's right, thank you.
