### ISSUE TITLE
Hide search bar when note was created

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1255]
Hiding the search bar when note was created via shortcut or via the note search.

**Comment by pbek** [comment]
via Telegram by @santiyounger

**Comment by pbek** [comment]
The search bar was a side effect from #1247. It was a bit tricky to not cause any more side effects. :smile: 

## 19.8.1
- when a note was created via shortcut or via the note search the search bar in
  the note edit will now be reset to default properties and hidden

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by iolivier87** [comment]
It works well for me.

I notice that in the created note, the cursor is now located at the begining of the title. It was more convenient to me when it was on a new line below it.

**Comment by pbek** [comment]
> I notice that in the created note, the cursor is now located at the begining of the title. It was more convenient to me when it was on a new line below it.

Thank you for reporting. It only happens if you are using the search panel for creating the note, right? (not the keyboard shortcut) I'll look into that.

**Comment by iolivier87** [comment]
Yes. The cursor is in the title when I am using the search panel, but it is on a new line below if the note is created by other way.

**Comment by pbek** [comment]
## 19.8.2
- the cursor will now be positioned in the 4th line again after creating a new
  note with the note search panel

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by iolivier87** [comment]
Perfect ! Thanks

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by santiyounger** [comment]
Hey Patrizio,

You are awesome man, really appreciate it, it works perfect now. When I create the new note the Search/ Replace doesn't pop automatically anymore, I love that since it was taking unnecessary space for me and I had to constantly close it. It's a lot better to just use the shortcut when I need it.

That's perfect now, really appreciate it!

**Comment by pbek** [comment]
Thank you for your kind words, I appreciate them. 🤗
