### ISSUE TITLE
[F] Enable "trash" to be hidden folder, e.g. ".trash"

### ISSUE THREAD

**Issue by destogl** [pbek/QOwnNotes#1258]
#### Expected behaviour

Trash files are stored in '.trash' subfolder. It would be nice to configure that so that the trash is not synchronized all the time.

#### Actual behaviour

Currently 'trash' folder ist used.

#### Steps to reproduce

Just delete something.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

Debug ist not important.
</details>

**Comment by pbek** [comment]
I'm sorry, it is supposed to be synced. Also the database entries in `notes.sqlite` need the trash folder to be synced. But you could always just exclude it from being synced in your sync client.

**Comment by destogl** [comment]
Ok, thanks! I thought that trash is not so important....

**Comment by pbek** [comment]
Don't you know? Trash is a valuable resource nowadays! :smile:

**Comment by pbek** [comment]
Plus I'm not sure if `.trash` is working on all file systems (Windows, NTFS / FAT) or may even conflict with the operating system (like on macOS)...
