### ISSUE TITLE
Filename for Note can contain "forbidden" characters

### ISSUE THREAD

**Issue by workflowsguy** [pbek/QOwnNotes#126]
When creating a new note, the first line is used as the file name.
If this line contains non-letters or non-digits, this can lead to unallowed characters in the file name.

E.g.
if the first line contains

> EyeTV: zu automatisierende Funktionen

the resulting file will be named

> EyeTV/ zu automatisierende Funktionen.txt

which will cause problems when opening. I am experiencing this on OS X.
I would suggest replacing those problematic characters with an "_".

Thanks,
Guy

**Comment by pbek** [comment]
Thank you for the report!
 
There are no problems here with `EyeTV: zu automatisierende Funktionen` on Linux. Neither are there any problems with it when creating such a note with the ownCloud notes app. Are you using ownCloud too? If yes, could you please be so kind to test it on our instance?

 I will later test it on OS X.

**Comment by pbek** [comment]
Yes, under OS X the file will be named like you said, but I had no troubles opening it with QOwnNotes or TextEdit. What problems are you perceiving?

**Comment by pbek** [comment]
Characters like `:`, `/` and `\`, as well as multiple whitespace characters will now be removed from the note file name if the first line of the note is containing them in version 1.3.4. Can you please test if this solves your problems?
