### ISSUE TITLE
Auto-update error

### ISSUE THREAD

**Issue by iolivier87** [pbek/QOwnNotes#1260]
I have problems with auto-updates since 19.8.1 (with Windows 10)

- Auto-update worked to install 19.8.1 from a previous version
- Since 19.8.1 I haven't any notification for new versions. If I go to check for updates I have this message : Update-checker error "Network reply error: 99"

- Same thing with 19.8.2 and 19.8.3

I just tried on my other computer. Auto-update worked from 19.7.11 to 19.8.3. But if I check now for updates, the same error occurs.

**Comment by iolivier87** [comment]
I got the update notification with the 19.7.10 you sent me in the other thread.
I updated it to 19.8.3 and the error 99 is there again.

**Comment by pbek** [comment]
I guess you have the same issue with networking like @truthsword in #1256 with the new release. Can you please also try https://ci.appveyor.com/project/pbek/qownnotes/builds/26596919/job/r7pijdphvn9apaw6/artifacts

**Comment by iolivier87** [comment]
Yes, it's the same as @truthsword in #1244 

"Check for updates" seems to work with the build you just linked 👍

**Comment by pbek** [comment]
Can you please try the preview of this in the Qt 5.13 version from 10 hours ago. Do you see both images or just one? I need to find out if it's a SSL library problem (that I don't seem to have under Windows 10).

```
## https
![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 1")

## http
![snap](http://www.httrack.com/hts2/snap1.gif)
```

**Comment by iolivier87** [comment]
In 19.8.3 / Qt 5.13, I can see the second image but not the first one.
In 19.8.3 / Qt 5.12 I can see both images

I believe I had a Windows Defender alert at first launch that ask me if I want to allow traffic (and I said yes). I shouldn't this alert with Qt 5.13.

**Comment by truthsword** [comment]
> In 19.8.3 / Qt 5.13, I can see the second image but not the first one.
> In 19.8.3 / Qt 5.12 I can see both images

This is my experience... no https. The launch popup mentioned by @iolivier87 is a firewall permission request, which I accept.

**Comment by pbek** [comment]
Could you please take the DLLs from http://wiki.overbyte.eu/arch/openssl-1.1.1c-win32.zip and put them in your Qt 5.13 version of QON 19.8.3 and try to view the images again (after a restart). Although I'm not sure about the file names and you will need to remove the files present in https://github.com/pbek/QOwnNotes/tree/develop/appveyor/OpenSSL from your QOwnNotes folder. :|

**Comment by pbek** [comment]
Could be something like back with #413, but the error message is different.

**Comment by truthsword** [comment]
Seems fine... Using:
**Version**: `19.8.3`
**Build date**: `Aug  9 2019`
**Build number**: `4458`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.13.0`
**Qt Version (runtime)**: `5.13.0`

![](https://i.imgur.com/CcFsClV.png)

FWIW... none of those files were in the previous QON version...

![](https://i.imgur.com/rbTfwzR.png)

**Comment by iolivier87** [comment]
It works with Qt 5.13 and the additionnal files in the folder. The Firewall request is back and I can see both images in preview.

**Comment by truthsword** [comment]
... and we still have update notification working

![](https://i.imgur.com/bpFuA5E.png)

**Comment by pbek** [comment]
Great new, thank you for testing (I have to do this completely blind, since I can't seem to reproduce the problem).

Can you please remove `openssl.exe` and the three DLLs of <https://github.com/pbek/QOwnNotes/tree/develop/appveyor/OpenSSL> from your QOwnNotes folder and try again.

**Comment by truthsword** [comment]
When I do that (only 2 DLLs to remove), which returns this to stock 19.8.3 IIRC, HTTPS is broken again and Error 99 appears on update check.

**Comment by iolivier87** [comment]
@truthsword there are 3 DLL. Look the link in his last reply

It still works with the 3 DLL removed from the folder

**Comment by truthsword** [comment]
> When I do that (only 2 DLLs to remove), which returns this to stock 19.8.3 IIRC, HTTPS is broken again and Error 99 appears on update check.

Just to add, "openssl.exe" does not seem necessary. HTTPS & Update check both work with only the  *1_1.dll's (removing either of those breaks the program).

**Comment by iolivier87** [comment]
The 3 DLL you can remove are : 
libeay32.dll
libssl32.dll
ssleay32.dll

**Comment by truthsword** [comment]
> @truthsword there are 3 DLL. Look the link in his last reply

OK. This is then confusing. I was sent a zipfile link with the files shown in my post above. We are using different DLLs apparently ???

**Comment by iolivier87** [comment]
You add the 2 DLL from the zip file and remove the 3 from the link above about OpenSSL

**Comment by truthsword** [comment]
> You add the 2 DLL from the zip file and remove the 3 from the link above about OpenSSL

OK... too many emails... missed that one... 

Deleted those dlls and added the 2 new ones. All is well.

**Comment by pbek** [comment]
Ok, great! Thank you for all the feedback. :) I'll make a new release today.

**Comment by pbek** [comment]
This build is with Qt 5.13 and OpenSSL v1.1.1c: https://ci.appveyor.com/project/pbek/qownnotes/builds/26606177/job/82f92y9w8859w0et/artifacts

There will be a release soon.

**Comment by pbek** [comment]
There now is a new release (should be on https://www.qownnotes.org/installation#Windows soon), could you please test it and report if it works for you?

**Comment by iolivier87** [comment]
It works for me 👍

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by truthsword** [comment]
It works here... however the last page I viewed yesterday had quite a few graphics so the app was "unresponsive" upon opening until it downloaded everything. I'll need to remember to exit on a note that has minimal graphic content.

**Comment by pbek** [comment]
> until it downloaded everything

yes, that of course takes time...

**Comment by truthsword** [comment]
Just fyi... but I went back to 19.7.10 and then took the offered upgrade to 19.8.4. As you're likely aware, the unneeded dll files were not removed. 

I'm guessing the installer simply expands the zip file into the existing folder, without cleaning up any orphaned files.

**Comment by pbek** [comment]
That's correct. As far that's no problem it's the saver route.

**Comment by pbek** [comment]
> any orphaned files

like all the notes and settings in portable mode? :smile:

**Comment by pbek** [comment]
**Instructions on how to fix this issue**

Please download the latest release of QOwnNotes from <https://www.qownnotes.org/installation#Windows> manually once.
