### ISSUE TITLE
Log windows bloked open 

### ISSUE THREAD

**Issue by zackles** [pbek/QOwnNotes#1262]
#### Expected behaviour
Could be able to show or hide log window
#### Actual behaviour
Once open, impossible to hide "log window". The icon "show log" is not highligth.
#### Steps to reproduce
Windows > show > show log
#### Output from the debug section in the settings dialog
nothing related
#### Relevant log output in the Log panel
nothing

Version QOwnNotes - version 19.8.3 - AppVeyor - build 4458
Win 10

**Comment by HardCoreXXL** [comment]
Try the new Version 19.8.4
https://www.qownnotes.org/installation#Windows

**Comment by zackles** [comment]
Same bug

**Comment by pbek** [comment]
Try Window / Panels

**Comment by pbek** [comment]
`Show log` is just a "shortcut" for those who can't find `Window / Panels / Show log panel`. 😄 

If that that answers your question feel free to close the issue.

**Comment by zackles** [comment]
Thanks.
First time using your software. Bug too obious to not be reported even if it is a shortcut.
Newcomers like me may have a first non good impression with a thing like this.
By the way there is too much word for a menu in the french.
It is hard to find something at first sight 
https://ibb.co/QJC37xc

**Comment by pbek** [comment]
> Bug too obious to not be reported even if it is a shortcut.

The `Show log` menu item does not have a checkbox, it is not supposed to be turned on/off, just like `Show all panels`.

> https://ibb.co/QJC37xc

The list is automatically created with all panels existing, what's why the menu item is called `Panels`

**Comment by zackles** [comment]
So it is a normal behavior. Did not clearly understand until now.
I have not paid attention to the"align left" style icon.
It is a common icon to say "show (only)"?
it may sounds like a dumb question but hamburger menu icon is also strange for me.

**Comment by pbek** [comment]
>  It is a common icon to say "show (only)"?

Which icon?

>  it may sounds like a dumb question but hamburger menu icon is also strange for me.

I've seen other apps doing it, like Dolphin (the file manager) and Virtual Box.

**Comment by GarryFlemings** [comment]
A bunch of years later, this status seems unchanged. Maybe it's quirky; it's not "bad".

Like zackles, I found `Windows > Show > Show log`. I assumed it would toggle; it didn't. Version 24.6.0; Windows 10.

This Git Issue includes, "`Show log` is just a "shortcut" for those who can't find `Window / Panels / Show log panel`. 😄" Or at least, haven't found it yet.

FWIW: Coming in cold, it first seems easier for both controls to toggle each way--functionally identical controls! Maybe the user doesn't care about the shortcut characteristic of one of them.

Or maybe, if the log is displayed and the user uses `Windows > Show > Show log`, show them `Window / Panels / Show log panel` so they know about the other control and can toggle there.

**Comment by pbek** [comment]
> Like zackles, I found Windows > Show > Show log. I assumed it would toggle; it didn't. Version 24.6.0; Windows 10.

It does enable the log panel. Maybe it's just resized very small? You should be able to see it if you enable `Unlock panels`.
