### ISSUE TITLE
[I] After storing note to disk, changes detected and cursor moves back to top of note

### ISSUE THREAD

**Issue by donaldsycamore** [pbek/QOwnNotes#1265]
#### Expected behaviour

While typing, I expect the same behaviour I get with any other text editor - the cursor continues to follow where I am typing.

#### Actual behaviour

While typing I see:
1. the status bar says that the note has been stored to disk
2. the status bar says "Loading external changes from filename.md"
3. the cursor moves to the top left of the document
4. new characters appear at the top left of the document (thus changing the note name)

#### Steps to reproduce

1. running Nextcloud sync version 2.5.2git, build 20190319
2. running QOwnNotesAPI 19.4.0
3. create a new note
4. start typing
5. watch the cursor occasionally jump to the top left of the document, while typing

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[11:12:48] [status] Stored current note to disk
[11:12:58] [status] Stored 1 note(s) to disk
[11:12:58] [status] Current note was modified externally
[11:12:58] [status] Loading external changes from: Note 2019-08-15T11.12.48.md
[11:12:58] [status] Notes directory was modified externally
[11:12:59] [status] Stored 1 note(s) to disk
[11:13:14] [status] Stored 1 note(s) to disk
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Thu Aug 15 11:13:47 2019`
**Version**: `19.8.4`
**Build date**: `Aug 10 2019`
**Build number**: `4464`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.13.0`
**Qt Version (runtime)**: `5.13.0`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\don\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Users\don\Apps\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `en_NZ`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `440`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: `https://nextcloud.sycamore.nz`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `15.0.8.1`
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `C:\Users\don\Nextcloud\Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `assignments`
**database file**: `C:\Users\don\Nextcloud\Notes\notes.sqlite`

### Script `Note stats`

**id**: `1`
**path**: `C:\Users\don\AppData\Roaming\PBE\QOwnNotes\scripts\note-stats\note-stats.qml`
**variablesJson**: 
```
{
    "charSpaceName": "Chars",
    "readTimeName": "Reading time",
    "readTimeRate": 300,
    "wordsName": "Words"
}
```
**identifier**: `note-stats`
**version**: `0.0.2`
**minAppVersion**: `17.06.3`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2019-08-15T10:31:28.625`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Point, KCML, Preaching, KCML/Block courses`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteHistory-1** (QVariantList): `<variant list with 99 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `98`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `true`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `49a99d6a-c369-4e15-a61b-56e80d134e76`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (int): `15`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `false`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `C:/Users/don/Nextcloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): `https://nextcloud.sycamore.nz`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloud/userName** (QString): `donald`
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `15.0.8.1`
**previousWorkspace** (QString): `57cdcba0-fa55-4b28-942f-2eb44d869485`
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2019-08-15T11.12.48, house to home, terms of call agenda, acronis trueimage, 20190811 lois, waddell, lawyer blair, 20190804 col 3 1-11, TODAY, orac, acc alternative, 20190707 Rory, competition entries, 20190709, 20190714 Mt 8 23-27, 20190707 2 kings 5 1-14, 20180610 acts 2 37-47 sermon, 20180603, worship - communion, class sermons, theological reflection interfauth, devotions, study schedule 2019, 20190622, evangelism - MiC, theological reflection class presentations, leadership, VC4, colloquium, sung theology, RTN, Messenger printing, Note 2018-04-24T14.49.01, Note 2018-01-31T18.48.34, sermon joshua jericho aargh, pp telco, sermon joshua jericho, prayer thingy, CHth331 forgiveness, CHTH331 VC4 M3 WAR AND CHRISTIANITY`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**skipVersion** (QString): `19.6.4`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-49a99d6a-c369-4e15-a61b-56e80d134e76/name** (QString): `minimal`
**workspace-49a99d6a-c369-4e15-a61b-56e80d134e76/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-49a99d6a-c369-4e15-a61b-56e80d134e76/windowState** (QByteArray): `<binary data>`
**workspace-57cdcba0-fa55-4b28-942f-2eb44d869485/name** (QString): `full`
**workspace-57cdcba0-fa55-4b28-942f-2eb44d869485/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-57cdcba0-fa55-4b28-942f-2eb44d869485/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `57cdcba0-fa55-4b28-942f-2eb44d869485, 49a99d6a-c369-4e15-a61b-56e80d134e76`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\don\AppData\Roaming`
**asl.log**: `Destination=file`
**ChocolateyInstall**: `C:\ProgramData\chocolatey`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `SILVER`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DokanLibrary1**: `C:\Program Files\Dokan\Dokan Library-1.0.1\`
**DokanLibrary1_LibraryPath_x64**: `C:\Program Files\Dokan\Dokan Library-1.0.1\lib\`
**DokanLibrary1_LibraryPath_x86**: `C:\Program Files\Dokan\Dokan Library-1.0.1\x86\lib\`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\don`
**LOCALAPPDATA**: `C:\Users\don\AppData\Local`
**LOGONSERVER**: `\\SILVER`
**MOZ_PLUGIN_PATH**: `C:\Program Files (x86)\Foxit Software\Foxit Reader\plugins\`
**NUMBER_OF_PROCESSORS**: `4`
**OneDrive**: `C:\Users\don\OneDrive`
**OneDriveConsumer**: `C:\Users\don\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\don\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Calibre2\;C:\Program Files\Microsoft\Web Platform Installer\;C:\ProgramData\chocolatey\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ZeroTier\One\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Common Files\Acronis\VirtualFile\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile64\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files (x86)\Common Files\Acronis\FileProtector\;C:\Program Files (x86)\Common Files\Acronis\FileProtector64\;C:\Users\don\AppData\Local\atom\bin;C:\Users\don\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Nmap;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 58 Stepping 9, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `3a09`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\`
**PUBLIC**: `C:\Users\Public`
**SciTE_HOME**: `C:\ProgramData\SciTE`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\don\AppData\Local\Temp`
**TMP**: `C:\Users\don\AppData\Local\Temp`
**USERDOMAIN**: `SILVER`
**USERDOMAIN_ROAMINGPROFILE**: `SILVER`
**USERNAME**: `don`
**USERPROFILE**: `C:\Users\don`
**VBOX_MSI_INSTALL_PATH**: `C:\Program Files\Oracle\VirtualBox\`
**VS140COMNTOOLS**: `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\`
**windir**: `C:\WINDOWS`
</details>

**Comment by pbek** [comment]
That happens on some systems when some external process is also mingling with the directories. In such cases you can for example turn off that the cursor position will be restored when the note opens in the *General settings*. You could also even turn off that external changes are watched.

If that that answers your question feel free to close the issue.

**Comment by donaldsycamore** [comment]
Thanks @pbek.  That does help.

**Comment by donaldsycamore** [comment]
I've discovered this is caused by Acronis True Image's "Active Protection" against ransomware/etc.  If you turn that Acronis off, then QOwnNotes works fine, no config adjustments necessary.

**Comment by pbek** [comment]
I guess it is writing to the notes folder.
