### ISSUE TITLE
[I] Renaming the title deletes the note

### ISSUE THREAD

**Issue by visika** [pbek/QOwnNotes#1268]
#### Expected behaviour

The file should not be deleted.

#### Actual behaviour

The note disappears from the list in the app and from the folder in the file manager. 
It becomes impossible to edit the note: I can only move the cursor but keypresses don't change the text. 
If I change note, it's impossible to get back to the specified note.

#### Steps to reproduce

Create a new note. 
Write something in the body. 
Change the format of the title from === notation to # notation, so that we have # + space + title. 
Now delete the title and leave just # + space. 
After some seconds the note disappears from the list and you can't edit the text anymore.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[17:34:58] [status] Nota attuale salvata su disco
[17:35:01] [status] La cartella delle note è stata modificata esternamente
[17:35:02] [status] 1 nota è stata salvata su disco
[17:35:05] [status] La cartella delle note è stata modificata esternamente
[17:35:05] [status] 1 nota è stata salvata su disco
[17:35:08] [status] La cartella delle note è stata modificata esternamente
[17:35:22] [status] 1 nota è stata salvata su disco
[17:35:25] [status] La cartella delle note è stata modificata esternamente
[17:35:25] [status] 1 nota è stata salvata su disco
[17:35:26] [status] La nota è stata salvata esternamente: .md
[17:35:28] [status] La cartella delle note è stata modificata esternamente
[17:35:29] [status] La nota è stata salvata esternamente: .md
[17:36:06] [status] La cartella delle note è stata modificata esternamente
[17:36:07] [status] La nota è stata salvata esternamente: .md
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `sab ago 17 17:36:37 2019`
**Version**: `19.8.6`
**Build date**: `Aug 17 2019`
**Build number**: `567`
**Platform**: `linux`
**Operating System**: `Ubuntu 19.04`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.12.2`
**Qt Version (runtime)**: `5.12.2`
**Portable mode**: `no`
**Settings path / key**: `~/.config/PBE/QOwnNotes.conf`
**Application database path**: `~/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `it_IT`
**Locale (interface)**: *empty*
**Icon theme**: `Flat-Remix-Red`
**Notes in current note folder**: `171`
**Calendar items**: `23`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: ``
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `16.0.3.0`
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `2`

### Note folder `default`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `-1`
**localPath**: ``
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: ``

### Note folder `default`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: ``
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: ``

### Script `Checkbox preview and export`

**id**: `1`
**path**: `~/.local/share/PBE/QOwnNotes/scripts/export-checkboxes/export-checkboxes.qml`
**variablesJson**: *empty*
**identifier**: `export-checkboxes`
**version**: `0.0.3`
**minAppVersion**: `17.12.0`

## Settings

**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `0`
**DistractionFreeMode/menuBarVisible** (QString): `false`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2019-08-17T17:27:23.396`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-2**: *empty*
**MainWindow/noteTextEdit.code.font** (QString): `Hack,10,-1,7,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Hack,9,-1,7,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteHistory-1** (QVariantList): `<variant list with 34 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 45 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `33`
**NoteHistoryCurrentIndex-2** (QString): `44`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `2`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full-vertical`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `24`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `false`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `false`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/mariano/Note`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): ``
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList** (QString): ``
**ownCloud/todoCalendarEnabledList** (QString): ``
**ownCloud/todoCalendarEnabledUrlList** (QString): ``
**ownCloud/todoCalendarUrlList** (QString): ``
**ownCloud/userName** (QString): ``
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Errore sconosciuto`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `16.0.3.0`
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): ``
**savedSearches/noteFolder-2** (QStringList): ``
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Barra degli strumenti principale`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `barra degli strumenti formattazione`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `barra degli strumenti "inserisci"`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `barra degli strumenti di crittografia`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `barra degli strumenti della finestra`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `esci dalla barra degli strumenti`
**toolbar/size** (QString): `6`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Verticale completo`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**KDE_FULL_SESSION**: `true`
**GS_LIB**: `~/.fonts`
**USER**: `mariano`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**LC_TIME**: `it_IT.UTF-8`
**LANGUAGE**: `it:en_GB:pt`
**XDG_SEAT**: `seat0`
**QT_SCREEN_SCALE_FACTORS**: `eDP-1=1;DP-1=1;HDMI-1=1;DP-2=1;HDMI-2=1;`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `1128`
**SHLVL**: `0`
**XCURSOR_SIZE**: `0`
**HOME**: ``
**DESKTOP_SESSION**: `plasma`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**KDE_SESSION_VERSION**: `5`
**LC_MONETARY**: `it_IT.UTF-8`
**LC_CTYPE**: `pt_PT.UTF-8`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**MANDATORY_PATH**: `/usr/share/gconf/plasma.mandatory.path`
**LOGNAME**: `mariano`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**XDG_SESSION_CLASS**: `user`
**DEFAULTS_PATH**: `/usr/share/gconf/plasma.default.path`
**XDG_SESSION_ID**: `3`
**LC_COLLATE**: `it_IT.UTF-8`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**LC_ADDRESS**: `pt_PT.UTF-8`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XCURSOR_THEME**: `breeze_cursors`
**DISPLAY**: `:0`
**LANG**: `it_IT.UTF-8`
**XDG_CURRENT_DESKTOP**: `KDE`
**LC_TELEPHONE**: `pt_PT.UTF-8`
**XDG_SESSION_DESKTOP**: `KDE`
**XAUTHORITY**: `/tmp/xauth-1000-_0`
**SSH_AUTH_SOCK**: `/tmp/ssh-dtxHzlvSmNtR/agent.1061`
**SHELL**: `/bin/bash`
**LC_NAME**: `pt_PT.UTF-8`
**QT_ACCESSIBILITY**: `1`
**LC_MEASUREMENT**: `it_IT.UTF-8`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**LC_IDENTIFICATION**: `pt_PT.UTF-8`
**XDG_VTNR**: `1`
**PWD**: `/home/mariano`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-plasma:/etc/xdg:/usr/share/kubuntu-default-settings/kf5-settings`
**XDG_DATA_DIRS**: `/usr/share/plasma:/home/mariano/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop`
**LC_NUMERIC**: `it_IT.UTF-8`
**LC_PAPER**: `pt_PT.UTF-8`
**KDE_SESSION_UID**: `1000`
**GTK_RC_FILES**: ``
**GTK2_RC_FILES**: ``
**SESSION_MANAGER**: ``
</details>

**Comment by Gregory-K** [comment]
yep, an old one

the note is not deleted, it is saved on disk as `.md`

**Comment by pbek** [comment]
Yes. The setting is the key.

**Comment by pbek** [comment]
If that that answers your question feel free to close the issue.
