### ISSUE TITLE
Authentication error CloudNotes/CloudNews/QOwnNotes

### ISSUE THREAD

**Issue by handswork** [pbek/QOwnNotes#127]
Hi,

I would like report a issue, I will just link to the original report

See this;
owncloud/core#23739

Thanks

**Comment by pbek** [comment]
Thank you for the report! Is there anything I can do about it? QOwnNotesAPI simply uses the auth methods from ownCloud.

**Comment by handswork** [comment]
Thanks for looking at it :)

I don't know where the issue is, I was just told to report it here as well.

**Comment by pbek** [comment]
Since I don't think I can do anything about the ownCloud API I will close this issue now. Feel free to open it again if you know something different. :)

**Comment by handswork** [comment]
Okay.

And thanks for your good work on the QOwnNotes :)

**Comment by pbek** [comment]
thank you! ;)

**Comment by handswork** [comment]
It seems that upgrading to php7 from php5.6 and reinstalling redis for php7 solve the issue
It also solve some issues I had with the news app on the web interface. I had some issues activating the app. And it solved a cronjob issue I also had.
