### ISSUE TITLE
[I] Support keyboard shortcuts in search box

### ISSUE THREAD

**Issue by divergio** [pbek/QOwnNotes#1270]
#### Expected behaviour

On Mac and nvAlt, I have ctrl-/ tied to "insert current date"
I use this all the time to create notes of the style "2019-08-22 work" 
I was pleased to find I could map this keyboard shortcut in QOwnNotes (in the Insert section, insert timestamp).

I use this to search for all notes affiliated with the current date, as well. 

When the cursor is in the search box and I press this shortcut, I expect it to paste the date into the search box.

#### Actual behaviour

Instead of pasting into the search box, it pastes it into the current note.

#### Steps to reproduce

Make a shortcut for "Insert current time"
Select the search box
Press the shortcut

**Comment by pbek** [comment]
> it pastes it into the current note.

It is supposed to do that.

You can change the name of new note with a script.
See: http://docs.qownnotes.org/en/develop/scripting/README.html#handlenotenamehook

If that that answers your question feel free to close the issue.

**Comment by divergio** [comment]
I guess I expect it to always insert text at the cursor, not in any other box. 

However, if pasting into the current note despite cursor position is your expected behavior, I'll just have to look for an external text macro utility for Windows.

I will make one last argument for the behavior I'm describing: it's really nice to be able to search for all the notes that have today's timestamp in them. It's a quick way to filter notes.

**Comment by pbek** [comment]
You could write a script that copies the current time to the clipboard: <http://docs.qownnotes.org/en/develop/scripting/README.html#copying-text-into-the-clipboard>

**Comment by pbek** [comment]
Would a scripting function that could insert text in the focused widget help you?

**Comment by pbek** [comment]
I will close this issue until there is more information.
