### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1271]
We may want a full-screen mode.

**Comment by pbek** [comment]
## 19.8.8
- there now is a **full-screen mode** that can be toggled with <kbd>F11</kbd>
  - the shortcut is <kbd>⌘</kbd> + <kbd>F11</kbd> on macOS

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by iolivier87** [comment]
It works correctly on my computer with Win10 and 150% dpi

**Comment by pbek** [comment]
Awesome, thank you for testing!
