### ISSUE TITLE
Print the preview properly

### ISSUE THREAD

**Issue by nayessiva** [pbek/QOwnNotes#1273]
### Expected behaviour

To have a nice print or PDF export on a A4 sheet of paper. with correct return to the ligne 

#### Actual behaviour

Print without seeing that the sentense is out of the page.

#### Version 

QOwnNotes - version 19.8.8 - AppVeyor - build 4509
On Windows 10

**Comment by pbek** [comment]
>  with correct return to the ligne

What does `with correct return to the ligne` mean? Can you please explain in more detail and step by step what you did, what happened and what you expected.

**Comment by nayessiva** [comment]
I've just realised that i use Qownnote just with bulleted lists.
When i print it : if the sentence is too long it doesn't goes to the line when printing.
Here is a ex.

Anyway, thanks for the program : works well ! light and powerful ; & for the quick response.

[test_text.pdf](https://github.com/pbek/QOwnNotes/files/3540222/test_text.pdf)
[test_preview.pdf](https://github.com/pbek/QOwnNotes/files/3540223/test_preview.pdf)

**Comment by nayessiva** [comment]
Oups.
Nevermind, i used the wrong markdown command apparently : the "*" instead of "-".
I close the subject.

**Comment by pbek** [comment]
Lists also work with `*` like:

```markdown
* line 1
* line 2
* line 3
```

**Comment by nayessiva** [comment]
If you use the star as you suggest, when you print there is no "return to the line".
However with the "-" it works well

**Comment by pbek** [comment]
What is a `return to the line`?

This:

```markdown
List test
=======

Text above

* line 1
* line 2
* line 3

Text below
```

Gets me: [List test.pdf](https://github.com/pbek/QOwnNotes/files/3540328/List.test.pdf)

**Comment by nayessiva** [comment]
I get this in preview.

[test_preview.pdf](https://github.com/pbek/QOwnNotes/files/3540400/test_preview.pdf)

Sorry for my english, to me return to the line is when you write a paragraph and it's very long. so if the sentence is only on one line it get's out of the paper unless you return to the line.

**Comment by pbek** [comment]
Can you please use my markdown in your test. The newlines above and below the list are crucial in markdown.

**Comment by pbek** [comment]
```markdown
List test
=======

Text above

* long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line 
* long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line 
* long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line long line 

Text below
```

Gives me: 
[List test.pdf](https://github.com/pbek/QOwnNotes/files/3540506/List.test.pdf)

**Comment by pbek** [comment]
I think I now knew what you did, you placed a <kbd>Tab</kbd> in front of your `*` and thus marked it as code block. That was your issue, right?

**Comment by nayessiva** [comment]
I was using the tab + * to create a list. the * alone works as the - 
however the tab + * is not responding the same.

[test_preview.pdf](https://github.com/pbek/QOwnNotes/files/3540523/test_preview.pdf)

**Comment by nayessiva** [comment]
> I think I now know what you did, you placed a Tab in front of your * and thus marked it as code block. That was your issue, right?

Exact

**Comment by pbek** [comment]
Yes, you can use different level only if you have the previous level present, like:

```markdown
* first
	* 2nd
	* also 2nd
* first again
```

**Comment by nayessiva** [comment]
True.
But if you go straight to tab + * it's wierd : grey highlight + preview out of the page

**Comment by pbek** [comment]
>  straight to tab + * it's wierd : grey highlight + preview out of the page

<kbd>Tab</kbd> + anything is use as a code block.

The <kbd>Tab</kbd> marks it as code block.
See: https://daringfireball.net/projects/markdown/syntax#precode
