### ISSUE TITLE
[Feature Request] Add option to sort notes in sub folder by name

### ISSUE THREAD

**Issue by maqp** [pbek/QOwnNotes#1274]
#### Expected behaviour

When a note subfolder is selected, notes in the `Note list panel` are displayed. The order of these notes keeps changing when notes are edited (most recent on top), but occasionally this makes it harder to find some note and/or keep them tidy. Being able to right click the `Note list panel` and select something like `Sort notes by name` would make this much easier.

**Comment by pbek** [comment]
Did you already visit `Note / Sort by` in the main menu?

**Comment by maqp** [comment]
No I did not :see_no_evil: Thank you!
