### ISSUE TITLE
[Q] Preview window colors

### ISSUE THREAD

**Issue by truthsword** [pbek/QOwnNotes#1277]
#### General question

How do I change the display in the preview window. For example, the inline code is white text on black background. I wish to change this to black text on light gray background. 

Themes seem only to affect the edit panel.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Sep 3 08:59:02 2019`
**Version**: `19.8.8`
**Build date**: `Aug 23 2019`
**Build number**: `4509`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.13.0`
**Qt Version (runtime)**: `5.13.0`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\Username\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `D:\Program Files (x86)\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `36`
**Calendar items**: `0`
**Enabled scripts**: `1`
</details>

**Comment by pbek** [comment]
You have removed your settings-dump, so I can't tell for sure... But it seems you have turned on dark-mode preview colors.

**Comment by pbek** [comment]
I will close this issue until there is more information.
