### ISSUE TITLE
Can ctrl-backspace be supported in textfields like 'Search notes' and 'Find in text'?

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#1278]
#### Expected behaviour
Pressing `ctrl-backspace` (on Linux this is) the previous word should be removed. This behavior does work in e.g. the 'Find setting' and 'Find action' textfields.

#### Actual behaviour
Nothing happens.

#### Steps to reproduce
- Type some words in 'Search notes' or 'Find in text' (possibly other textfieldfs as well)
- Press `ctrl-backspace`
- See that nothing happens

#### Output from the debug section in the settings dialog

**Version**: `19.9.0`
**Build date**: `Sep  3 2019`
**Build number**: `570`
**Platform**: `linux`
**Operating System**: `Manjaro Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.13.0`
**Qt Version (runtime)**: `5.13.0`
**Portable mode**: `no`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `866`
**Calendar items**: `2`
**Enabled scripts**: `7`

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
For some reason I cannot capture the left control key in line edits, but I can capture the shift key so I will use that. Btw. the right control key works out of the box.

**Comment by sanderboom** [comment]
That's weird. This shortcut is coming from the OS (KDE Sytem Settings > Workspace > Shortcuts > Standard Shortcuts):

<img width="259" alt="image" src="https://user-images.githubusercontent.com/5956570/64329342-67e8ca00-cfcf-11e9-848b-154413097697.png">

It works everywhere I interact with text. Instead of trying to capture it, maybe search for something that is blocking default behavior?

Also:
> This behavior does work in e.g. the 'Find setting' and 'Find action' textfields.

What is different regarding these fields?

**Comment by pbek** [comment]
That's strange, so far I haven't found anything that could do that.

**Comment by sanderboom** [comment]
Maybe your shortcut setting is different? `ctrl+backspace` and `ctrl+delete` are pretty universal (at least in my experience).

**Comment by pbek** [comment]
I finally found the culprit. There is are main menu items for deleting the current word and the current line with the shortcut <kbd>Ctrl + Backspace</kbd> and <kbd>Alt + Backspace</kbd>. There already was a workaround in place so other widgets can get a special event with the shortcut passed through. That event is for some reason ignored by the `QLineEdit` so I now implemented special workarounds for the two incidents.

**Comment by pbek** [comment]
## 19.9.3
- you now can press <kbd>Ctrl</kbd> + <kbd>Backspace</kbd> to **remove the current word**
  and <kbd>Alt</kbd> + <kbd>Backspace</kbd> to **remove the whole text** in **line edits**
  like the note text search

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by sanderboom** [comment]
Thanks for the quick fix!

**Comment by pbek** [comment]
Great, thank you for testing!
