### ISSUE TITLE
Scroll notes panel to top when searching for note

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#1279]
#### Expected behaviour
When searching (or actually filtering) notes using the 'Search or create note' textfield, ensure the notes pane is scrolled all the way to the top, so that the highest ranked searchresult is in view.

#### Actual behaviour
While filtering, the notes pane does not move. When initially not positioned at the top, the most relevant results are not in view.

#### Steps to reproduce
- Scroll down in the notes pane
- Start filtering with the 'Search or create note' with some string that is contained in a lot of notes
- Miss the most relevant result as this is placed at the top of the notes pane, but this is not in view as the pane does not scroll

#### Output from the debug section in the settings dialog
**Version**: `19.9.0`
**Build date**: `Sep  3 2019`
**Build number**: `570`
**Platform**: `linux`
**Operating System**: `Manjaro Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.13.0`
**Qt Version (runtime)**: `5.13.0`
**Portable mode**: `no`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `866`
**Calendar items**: `2`
**Enabled scripts**: `7`

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
## 19.9.2
- when you **search for notes** in the note search line edit the **note list**
  will be now **scrolled to the top** so you can see the first search results

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by sanderboom** [comment]
Great :+1:

**Comment by pbek** [comment]
Great, thank you for testing!
