### ISSUE TITLE
Feature request: Enable editing when sharing Nextcloud links

### ISSUE THREAD

**Issue by MathiasRenner** [pbek/QOwnNotes#1280]
Earlier this year, Nextcloud included a web-based text editor that allows parallel text editing for multiple users in real time.

To allow the editing functionality in Nextcloud, you activate a checkbox saying "allowing editing":
![image](https://user-images.githubusercontent.com/2377464/64264855-42f24980-cf32-11e9-9c2e-5faf7b425683.png)

QOwnNotes already allows to share documents. What about extending this feature (see following screenshot) with a checkbox "allow editing"?

![image](https://user-images.githubusercontent.com/2377464/64265949-117a7d80-cf34-11e9-9cf3-c205660d57ea.png)

**Comment by pbek** [comment]
Seems like a good idea.

Where can I find this checkbox and what exactly does it do? I don't seem to have it on my 16.0.4 NC installation.

Is there an api documentation for it?

**Comment by pbek** [comment]
Are we talking about Nextcloud text? (like in https://github.com/pbek/QOwnNotes/issues/1226)

**Comment by MathiasRenner** [comment]
Yep, this is Nextcloud Text as in the issue you referenced.
This is an add-on you have to install in NC. 
With next version 17 (will be released probably this week) or 18, it will be included in the base installation.

I haven't check API docu yet.

**Comment by pbek** [comment]
I have Nextcloud Text installed but I can't see the menu item

**Comment by MathiasRenner** [comment]
Hmm, it only works on text-based files - for me it works on .md and .txt at least.

**Comment by pbek** [comment]
> Hmm, it only works on text-based files - did you try it on .md and .txt ?

yes, I tried it on my notes... I can edit them with NC Text when left-clicking them in the Files app. But I don't see the checkbox and I have no idea what it might do.

**Comment by leander091** [comment]
The option to enable editing on a text file is a part of the share menu. You will need to create a shared link before getting the menu to enable editing. Like this:
![image](https://user-images.githubusercontent.com/5831104/64380157-c1351580-d030-11e9-99f8-86120c852935.png)

**Comment by pbek** [comment]
Ah, thank you @leander091! It used a PUT request to an url like <https://server/ocs/v2.php/apps/files_sharing/api/v1/shares/1111?format=json>. Can it be used externally too (no cors) and do you know if there is a documentation for it?

**Comment by pbek** [comment]
Too bad that it seems editing the shared file without logging in causes the current version to be overwritten without creating a new version. So basically it looks like I edited the file myself instead of someone else edited it...

**Comment by pbek** [comment]
## 19.9.4
- you can now **allow note editing** when **sharing notes** on your **Nextcloud**
  server with the share dialog
    - the person who receives the share link will then be able to edit your note
      with [Nextcloud Text](https://github.com/nextcloud/text)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

And could you also please (if you care to) test the image support from https://github.com/pbek/QOwnNotes/issues/1226, there was a regression I now fixed...

**Comment by MathiasRenner** [comment]
@pbek Wow, you are awesome. I successfully tested it. It works as I expected, I have NC 16.04. Thank you so much!! 

There's only one bug missing. When I remove the checkbox for sharing, I get this error:
![image](https://user-images.githubusercontent.com/2377464/64437443-95646f00-d0c6-11e9-9523-747ee4e58e85.png)

**Comment by leander091** [comment]
Nice :), it works as expected. Also the image support in  #1226 works pretty well :).

I can also confirm the issue when removing the allow editing checkbox.

**Comment by pbek** [comment]
Thank you for testing! :) I'll take a look at the error, was in introduced with this release?

**Comment by MathiasRenner** [comment]
@pbek Nice, thanks! I don't know if this error has been introduced with this release, sorry...

**Comment by pbek** [comment]
## 19.9.5
- fixed incorrect note share status update

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by MathiasRenner** [comment]
@pbek It works, nice! I like your super low response time... Good work! I'll definitely make sure my donations will at least stay on the same leve as of now :-)

**Comment by pbek** [comment]
Thanks a lot! 😃
