### ISSUE TITLE
Error during opening application

### ISSUE THREAD

**Issue by npodbielski** [pbek/QOwnNotes#1281]
Since some update (there was some problems and update failed) I have error message during every application start.

---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Runtime Error!

Program: C:\Users\Natan\AppData\Roaming\QOwnNotes\QOwnNotes.exe

R6034

An application has made an attempt to load the C runtime library incorrectly.
Please contact the application's support team for more information.

---------------------------
OK   
---------------------------

After clicking OK application starts.

I think it is caused by some broken update that happened some time ago. Application failed to update. I started it again and afters some other errors I managed to update application.

**Comment by pbek** [comment]
Please see #1259, you will need to download the latest version manually.
