### ISSUE TITLE
No html tags anymore?

### ISSUE THREAD

**Issue by RaZorHack** [pbek/QOwnNotes#1283]
Hallo,

For the design of my notes I also use html-tags
` <br> | <center> | <span>` - etc.
 
Until recently, everything worked fine.
However, these have no effect in the last two versions of QOwnNotes in the preview.

Is this a bug or a feature? :-)

Best regards

---
**Info:**
OS: Windows 10 1903 x64
QOwnNotes 19.9.4 | used in Portable Mode

**Comment by pbek** [comment]
Thank you for reporting, sounds like a side effect from all the efforts I put into #266. I'll take a look into it!

**Comment by pbek** [comment]
It seems https://github.com/pbek/QOwnNotes/blob/fccf3b1932056a1ccfd06eaccc1e06729215447c/src/entities/note.cpp#L1834-L1850 needs a check if the linked file exists.

**Comment by pbek** [comment]
...or check if `.` exists in the filename

**Comment by RaZorHack** [comment]
**Text:**

![text1](https://user-images.githubusercontent.com/54993833/64460317-60720f80-d0fa-11e9-951f-bce04226aec6.png)

**Preview:**

![text](https://user-images.githubusercontent.com/54993833/64460367-826b9200-d0fa-11e9-89ad-998be04c8054.png)

**Comment by pbek** [comment]
## 19.9.5
- the preview of html tags now works again
    - html tags also are now not highligted as link

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by RaZorHack** [comment]
The update function of 19.9.4 will not find a new version.
On the homepage is: currently 19.9.5 - on the download page
https://www.qownnotes.org/installation#Windows
but only the 19.9.4 is available.
Also at GitHub
https://github.com/pbek/QOwnNotes/releases
I can not find a download of 19.9.5 for Windows.

**Comment by RaZorHack** [comment]
Alright ... - now the download is available :-)
I have updated to 19.9.5 - everything works fine again!

thank you very much...
You are doing a great job...

**Comment by pbek** [comment]
Great, thank you for reporting and testing! :smile:
