### ISSUE TITLE
AppData Cache Folder Created

### ISSUE THREAD

**Issue by teamayu** [pbek/QOwnNotes#1284]
I thought the portable version store everything in the application folder?

I have this folder:
AppData\Local\PBE\QOwnNotes\cache\qmlcache\*

**Comment by pbek** [comment]
Interesting, I didn't even know that there is a `qmlcache` folder, must be generated by Qt directly.
Where is the folder `AppData\Local\PBE\QOwnNotes\cache\` located? 
And can you please post the output from the debug settings (see issue template).

**Comment by teamayu** [comment]
Hi Patrizio,

On my system it is located at:
C:\Users\David\AppData\Local\PBE\QOwnNotes\cache\qmlcache

![screenshot-10-09-2019_133758](https://user-images.githubusercontent.com/10624092/64587379-c815ac80-d3d1-11e9-9092-24ce94702af9.png)

Here is the debug output:
===========================

## General Info

**Current Date**: `Tue Sep 10 13:48:30 2019`
**Version**: `19.9.6`
**Build date**: `Sep  9 2019`
**Build number**: `4540`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.13.0`
**Qt Version (runtime)**: `5.13.0`
**Portable mode**: `yes`
**Settings path / key**: `Q:/Portable-Software/QOwnNotes/Data/PBE/QOwnNotes.ini`
**Application database path**: `Q:\Portable-Software\QOwnNotes\Data\QOwnNotes.sqlite`
**Application arguments**: `Q:\Portable-Software\QOwnNotes\QOwnNotes.exe`, `--portable`
**Qt Debug**: `0`
**Locale (system)**: `en_GB`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `134`
**Calendar items**: `0`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Note folders

**currentNoteFolderId**: `2`

### Note folder `Notes`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `-1`
**localPath**: `Q:\Portable-Software\QOwnNotes\Data\Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `Q:\Portable-Software\QOwnNotes\Data\Notes\notes.sqlite`

### Note folder `Development`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `Q:\Portable-Software\QOwnNotes\Data\Dev`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `Maian Lockbox`
**database file**: `Q:\Portable-Software\QOwnNotes\Data\Dev\notes.sqlite`

## Enabled scripts

### Script `External note open`

**id**: `1`
**path**: `Q:\Portable-Software\QOwnNotes\Data\scripts\external-note-open\external-note-open.qml`
**variablesJson**: 
```
{
    "executablePath": "Q:\\Portable-Software\\CudaText\\cudatext.exe"
}
```
**identifier**: `external-note-open`
**version**: `1.0.0`
**minAppVersion**: `18.05.4`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `23`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `false`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/vimMode** (bool): `false`
**FileDialog/LastPath** (QString): `Q:/Portable-Software/CudaText`
**FileDialog/LastPath-ExternalEditor** (QString): `Q:/Portable-Software/CudaText`
**FileDialog/LastPath-NotePDFExport** (QString): `C:/Users/David/Desktop`
**FileDialog/LastPath-ScriptSettingsFile-external-note-open-executablePath** (QString): `Q:/Portable-Software/CudaText`
**FileDialog/LastPath-SettingsExport** (QString): `Q:/Portable-Software/QOwnNotes/_Backup`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2019-09-10T13:40:49.274`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-2** (QStringList): `In Progress`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Calibri,14,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Courier New,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Calibri,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/issue-dialog-new-issue** (int): `16384`
**NoteHistory-1** (QVariantList): `<variant list with 24 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 49 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `23`
**NoteHistoryCurrentIndex-2** (int): `48`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExportOrientation** (QString): `0`
**Printer/NotePDFExportPageSize** (QString): `4`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `true`
**StartHidden** (bool): `true`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowDifferentNoteFileName** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `true`
**appMetrics/disableTracking** (bool): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `2`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableSocketServer** (bool): `false`
**externalEditorPath** (QString): `../../CudaText/cudatext.exe`
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full-vertical`
**insertTimeFormat** (QString): `dd-MM-YYYY hh:mm:ss`
**interfaceFontSize** (int): `12`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (int): `15`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `false`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `0`
**notesPath** (QString): `Dev`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): *empty*
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloud/userName** (QString): *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `initial`
**recentNoteFolders** (QStringList): `Q:/Portable-Software/QOwnNotes/Data/Notes, Q:/Portable-Software/QOwnNotes/Data/../../../Users/David/Dropbox/Ayumi/_NOTES/_NOTES`
**restoreCursorPosition** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2019-07-13T15.58.27, Note 2019-07-13T15.56.42, Note 2019-07-13T15.56.29, Note 2019-07-13T15.56.22, Note 2019-07-13T15.56.07, Note 2019-07-13T15.55.14, Note 2019-07-13T15.55.07, Note 2019-07-13T15.53.11, Note 2019-07-13T15.52.10, Note 2019-07-13T15.41.08, Note 2019-07-13T14.03.56, Note 2019-07-12T17.24.10, Note 2019-07-12T17.22.07, Note 2019-07-12T16.37.06, Note 2019-07-07T19.40.22, Note 2019-07-07T19.40.10`
**savedSearches/noteFolder-2** (QStringList): `Note 2019-09-09T13.11.52, Note 2019-07-15T11.36.55, Note 2019-07-14T00.33.49, Note 2019-07-13T16.46.25, Note 2019-07-13T16.45.58, Note 2019-07-13T16.36.26, Note 2019-07-13T16.34.28, Note 2019-07-13T16.29.03, Note 2019-07-13T16.18.42, Note 2019-07-13T16.17.16, Note 2019-07-13T16.16.42`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `false`
**skipVersion** (QString): `19.7.3`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `true`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Export_note_as_PDF_text, actionShow_local_trash`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_image`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useUNIXNewline** (bool): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Main Interface`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\David\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `DESKTOP-RJH6M2Q`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DokanLibrary1**: `C:\Program Files\Dokan\Dokan Library-1.1.0\`
**DokanLibrary1_LibraryPath_x64**: `C:\Program Files\Dokan\Dokan Library-1.1.0\lib\`
**DokanLibrary1_LibraryPath_x86**: `C:\Program Files\Dokan\Dokan Library-1.1.0\x86\lib\`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\David`
**LOCALAPPDATA**: `C:\Users\David\AppData\Local`
**LOGONSERVER**: `\\DESKTOP-RJH6M2Q`
**NUMBER_OF_PROCESSORS**: `4`
**OneDrive**: `C:\Users\David\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files (x86)\AOMEI Backupper;C:\Users\David\AppData\Local\Microsoft\WindowsApps;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PORTABLEPATH**: `C:\Portable-Software`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `AMD64 Family 22 Model 48 Stepping 1, AuthenticAMD`
**PROCESSOR_LEVEL**: `22`
**PROCESSOR_REVISION**: `3001`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\David\AppData\Local\Temp`
**TMP**: `C:\Users\David\AppData\Local\Temp`
**USERDOMAIN**: `DESKTOP-RJH6M2Q`
**USERDOMAIN_ROAMINGPROFILE**: `DESKTOP-RJH6M2Q`
**USERNAME**: `David`
**USERPROFILE**: `C:\Users\David`
**windir**: `C:\WINDOWS`
</details>

**Comment by pbek** [comment]
The QML script you are using is causing those cache files.
The QML cache path cannot be configured yet (see https://bugreports.qt.io/browse/QTBUG-58858).

I will attempt to disable QML caching in portable mode.

**Comment by teamayu** [comment]
No problem, thank you. Or I can disable the script?

**Comment by pbek** [comment]
Just wait for today's release, I need you for testing. :) 😄

**Comment by pbek** [comment]
## 19.9.7
- disabled QML caching (for the scripts of the scripting engine) in portable mode because
  the QML cache path cannot be configured

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you? (best remove the cache files first to see if they stay gone)

**Comment by teamayu** [comment]
Thanks Patrizio, confirmed as working great now. No cache folder created. Thank you.

**Comment by pbek** [comment]
Great, thank you for testing!
