### ISSUE TITLE
Insert image dialog with preview, scaling and clipboard support

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1285]
There will be a new *Insert image* dialog with preview, scaling and clipboard support.

**Comment by pbek** [comment]
## 19.9.6
- there now is a new **Insert image dialog** with **preview, scaling and clipboard** support
    - if an image was in the clipboard it will be automatically loaded and previewed
    - you can also select an image from your file system
    - you can scale the image by setting the width or a scale factor, the preview
      will be updated accordingly

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
## 19.9.7
- the **Insert image dialog** was further improved
    - you can now paste **remote urls** that will be **automatically downloaded**
      and previewed in the dialog
        - local `file://` urls are also supported
    - the dialog will **detect** if you have **file paths or urls** in the
      **clipboard** when it is opened
    - there now is a new checkbox `Don't copy image to media folder` that allows to
      **directly insert urls or local paths**
        - paths to files will be made relative to the current note
        - the state of the checkbox will be persisted for more convenience
    - the maximal scaling in the slider was set to 2 for more usability

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by bipox** [comment]
Yes, it's fixed, thanks!

And I just tested the add picture preview, very nice. I like the choice to add the pic to the media folder or not.

**Comment by pbek** [comment]
Thank you for testing and your feedback!
