### ISSUE TITLE
Images linked from web not showing in preview pane

### ISSUE THREAD

**Issue by bipox** [pbek/QOwnNotes#1286]
Images stored on computer are shown correctly, but anything linked from the web just shows an empty white file icon in the preview.

Here is the error message:
`[19:25:17] [warning] QString::replace: invalid QRegularExpression object`

**Comment by pbek** [comment]
Thank you for reporting, I guess that will be a side effect from #266. I will look into it.

**Comment by pbek** [comment]
Note: Support for remote images was implemented recently in #1244.

**Comment by pbek** [comment]
@bipox, meanwhile you could test the new image dialog (release 19.9.6, currently building) from https://github.com/pbek/QOwnNotes/issues/1285 that also uses the new image link format (see https://github.com/pbek/QOwnNotes/issues/266).

**Comment by pbek** [comment]
## 19.9.7
- fixed preview of remote images

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
I guess your comment in #1285 meant that it is fixed, right? :smile:

**Comment by bipox** [comment]
Yes :smile:

**Comment by pbek** [comment]
Thanks ;)
