### ISSUE TITLE
[F] Allow image cropping in image dialog

### ISSUE THREAD

**Issue by euneuber** [pbek/QOwnNotes#1288]
#### Expected behaviour

There is an option to select  a rectangular portion of the image to actually save.

#### Actual behaviour

Image is saved as big as it was in the clipboard

#### Steps to reproduce

Insert an image from clipboard

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mi. Sep. 11 15:50:59 2019`
**Version**: `19.9.7`
**Build date**: `Sep 10 2019`
**Build number**: `577`
**Platform**: `linux`
**Operating System**: `openSUSE Leap 15.1`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.9.4`
**Qt Version (runtime)**: `5.9.7`
**Portable mode**: `no`
**Settings path / key**: `/home/eugen/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/eugen/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Icon theme**: `breeze`
**Notes in current note folder**: `1`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Note folders

**currentNoteFolderId**: `2`

### Note folder `Standard`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `-1`
**localPath**: `/home/eugen/Nextcloud/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/eugen/Nextcloud/Notes/notes.sqlite`

### Note folder `Javascript`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/eugen/Nextcloud/Notes/Javascript`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/eugen/Nextcloud/Notes/Javascript/notes.sqlite`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/vimMode** (bool): `false`
**ImageDialog/disableCopying** (bool): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2019-09-11T15:12:33`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Hack,13,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,13,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Hack,13,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Noto Sans,13,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteHistory-1** (QVariantList): `<variant list with 4 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 1 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `3`
**NoteHistoryCurrentIndex-2** (int): `0`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowDifferentNoteFileName** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (int): `2`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (int): `24`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/eugen/Nextcloud/Notes/Javascript`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): *empty*
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloud/userName** (QString): *empty*
**recentNoteFolders** (QStringList): `/home/eugen/Nextcloud/Notes`
**restoreCursorPosition** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2019-08-26T09.13.07, Note 2019-07-05T13.51.19`
**savedSearches/noteFolder-2** (QStringList): `Note 2019-09-11T15.25.54`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Hauptsymbolleiste`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `Formatierungs-Werkzeugleiste`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `Einfügen-Werkzeugleiste`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `Werkzeugleiste Verschlüsselung`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `Fenster-Werkzeugleiste`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `Beenden - Symbolleiste`
**toolbar/size** (int): `6`
**useUNIXNewline** (bool): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**webSocketServerService/token** (QString): `eAK9AsPC`
**workspace-initial/name** (QString): `Vollständig`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**GS_LIB**: `/home/eugen/.fonts`
**KDE_FULL_SESSION**: `true`
**HOSTTYPE**: `x86_64`
**XAUTHLOCALHOSTNAME**: `linux-5ved`
**LESSCLOSE**: `lessclose.sh %s %s`
**XKEYSYMDB**: `/usr/X11R6/lib/X11/XKeysymDB`
**LANG**: `de_DE.UTF-8`
**WINDOWMANAGER**: `/usr/bin/startkde`
**LESS**: `-M -I -R`
**DISPLAY**: `:0`
**JAVA_ROOT**: `/usr/lib64/jvm/jre-11-openjdk`
**HOSTNAME**: `linux-5ved`
**CONFIG_SITE**: `/usr/share/site/x86_64-unknown-linux-gnu`
**CSHEDIT**: `emacs`
**AUDIODRIVER**: `pulseaudio`
**GPG_TTY**: `kein Terminal`
**LESS_ADVANCED_PREPROCESSOR**: `no`
**COLORTERM**: `1`
**QT_SCREEN_SCALE_FACTORS**: `DP-0=1.3;DP-1=1.3;HDMI-0=1.3;DP-2=1.3;DP-3=1.3;DP-4=1.3;DP-0.3=1.3;`
**JAVA_HOME**: `/usr/lib64/jvm/jre-11-openjdk`
**ALSA_CONFIG_PATH**: `/etc/alsa-pulse.conf`
**MACHTYPE**: `x86_64-suse-linux`
**XDG_VTNR**: `7`
**QEMU_AUDIO_DRV**: `pa`
**SSH_AUTH_SOCK**: `/tmp/ssh-AhrHI1vU9j5e/agent.2675`
**MINICOM**: `-c on`
**QT_SYSTEM_DIR**: `/usr/share/desktop-data`
**OSTYPE**: `linux`
**XDG_SESSION_ID**: `2`
**USER**: `eugen`
**PAGER**: `less`
**DESKTOP_SESSION**: `/usr/share/xsessions/plasma5`
**MORE**: `-sl`
**PWD**: `/home/eugen`
**SSH_ASKPASS**: `/usr/lib/ssh/ssh-askpass`
**HOME**: `/home/eugen`
**SSH_AGENT_PID**: `2746`
**HOST**: `linux-5ved`
**XNLSPATH**: `/usr/share/X11/nls`
**XDG_SESSION_TYPE**: `x11`
**XDG_DATA_DIRS**: `/home/eugen/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share`
**XDG_SESSION_DESKTOP**: `KDE`
**PROFILEREAD**: `true`
**GTK_MODULES**: `canberra-gtk-module`
**FROM_HEADER**: *empty*
**MAIL**: `/var/spool/mail/eugen`
**LESSKEY**: `/etc/lesskey.bin`
**TERM**: `xterm`
**SHELL**: `/bin/bash`
**XDG_SESSION_CLASS**: `user`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**QT_IM_MODULE**: `xim`
**XMODIFIERS**: `@im=local`
**XCURSOR_THEME**: `breeze_cursors`
**XDG_CURRENT_DESKTOP**: `KDE`
**PYTHONSTARTUP**: `/etc/pythonstart`
**SHLVL**: `1`
**XDG_SEAT**: `seat0`
**G_FILENAME_ENCODING**: `@locale,UTF-8,ISO-8859-15,CP1252`
**MANPATH**: `/usr/local/man:/usr/local/share/man:/usr/share/man`
**XSESSION_IS_UP**: `yes`
**LOGNAME**: `eugen`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XAUTHORITY**: `/home/eugen/.Xauthority`
**JRE_HOME**: `/usr/lib64/jvm/java-11-openjdk-11`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**XDG_CONFIG_DIRS**: `/etc/xdg`
**PATH**: `/home/eugen/bin:/usr/local/bin:/usr/bin:/bin`
**JAVA_BINDIR**: `/usr/lib64/jvm/jre-11-openjdk/bin`
**KDE_SESSION_UID**: `1000`
**KDE_SESSION_VERSION**: `5`
**SDL_AUDIODRIVER**: `pulse`
**QT_IM_SWITCHER**: `imsw-multi`
**G_BROKEN_FILENAMES**: `1`
**HISTSIZE**: `1000`
**CPU**: `x86_64`
**CVS_RSH**: `ssh`
**LESSOPEN**: `lessopen.sh %s`
**GTK_IM_MODULE**: `cedilla`
**_**: `/usr/bin/kwrapper5`
**SESSION_MANAGER**: `local/linux-5ved:@/tmp/.ICE-unix/2816,unix/linux-5ved:/tmp/.ICE-unix/2816`
**LANGUAGE**: *empty*
</details>

**Comment by pbek** [comment]
## 19.9.10
- removed 2px offset when selection-rubberband is created while cropping in the image dialog

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
## 19.9.11
- adapted the offset when the selection-rubberband is created while cropping in
  the image dialog for all user interfaces

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by euneuber** [comment]
Works great! Thank you very much!

**Comment by pbek** [comment]
Great, thank you for testing!
