### ISSUE TITLE
Can't connect to owncloud

### ISSUE THREAD

**Issue by tes5884** [pbek/QOwnNotes#129]
Getting the following error: "Connection error message: Es konnte keine SSL-Kontextstruktur erzeugt werden ()"

This happens on the 'Settings' > 'ownCloud' page..

Any ideas?

**Comment by pbek** [comment]
- Which operating system are you using?
- Do you use https to connect to your ownCloud server?
    - Do you have a signed SSL certificate?
    - have you tried to turn of SSL error messages in the networking settings of QOwnNotes?

**Comment by tes5884** [comment]
- Windows 10
- yes
 - yes, using letsencrypt
 - yes

**Comment by pbek** [comment]
I found the English string for the German error message.
`Error creating SSL context`

Could you try to install the *Microsoft Visual C++ 2008 SP1 Redistributable Package*:
<http://www.microsoft.com/en-us/download/details.aspx?id=5582>

Source: <http://stackoverflow.com/questions/4511767/qt-creating-ssl-context-error-in-few-computers>

**Comment by pbek** [comment]
But it's still strange, because I deliberately included all the OpenSSL libraries with QOwnNotes so you don't have to install anything extra...
like here: <http://stackoverflow.com/questions/18894056/error-creating-ssl-context-qt>

**Comment by pbek** [comment]
I just tried to use a freshly downloaded QOwnNotes 1.3.5 with Win 10 and my Server with a Let's encrypt cert and had no troubles... Is there any network proxy you have to use?

**Comment by tes5884** [comment]
I do use a proxy, but I tried without the proxy and it still didn't work.

That link for the SSL libs doesn't actually download..

**Comment by pbek** [comment]
I also get a gateway timeout when I try to download the file from the Microsoft webpage.
I guess one of the other download pages will work:
<https://duckduckgo.com/?q=Microsoft+Visual+C%2B%2B+2008+SP1+Redistributable+Package>

It seems like a problem with OpenSSL to me...

**Comment by pbek** [comment]
And are you able to surf the internet (making a https connection) without using your proxy? (keep in mind that your browser might automatically use your proxy)

**Comment by tes5884** [comment]
I can browse the web without the proxy just fine.

I will post results once I get the SSL libs installed

**Comment by pbek** [comment]
Please do so, I wonder what the problem is.

**Comment by tes5884** [comment]
Sorry no luck.

I'm going to be using a different solution for now. If you want me to try something else, I'm more then happy to do that.

**Comment by pbek** [comment]
Sorry, I wasn't of much help. If I come up with a new idea I will open this issue again.

Keep in in mind that you don't need the the ownCloud configuration in QOwnNotes for note syncing, that is still done by ownClouds' own sync client. Just the access of note versions and the trash on the server uses that configuration.

**Comment by DeastinY** [comment]
Same issue, same setup 😢
