### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by jjgalvez** [pbek/QOwnNotes#1293]
#### Expected behaviour
successful application build. Building application on Arch from the AUR with makepkg

#### Actual behaviour
Build fails with a compilation error:
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.archlinux.org/> for instructions.
make: *** [Makefile:3041: linkdialog.o] Error 1
In file included from /usr/include/qt/QtNetwork/QAuthenticator:1,
                 from ./services/owncloudservice.h:5,
                 from ./dialogs/settingsdialog.h:14,
                 from mainwindow.h:39,
                 from mainwindow.cpp:15:
/usr/include/qt/QtNetwork/qauthenticator.h:63:25: internal compiler error: Segmentation fault
   63 |     inline bool operator!=(const QAuthenticator &other) const { return !operator==(other); }
      |                         ^~
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.archlinux.org/> for instructions.
make: *** [Makefile:2974: mainwindow.o] Error 1
==> ERROR: A failure occurred in build().
#### Steps to reproduce
download snapshot from the AUR, expand and makepkg

#### Output from the debug section in the settings dialog
See above
#### Relevant log output in the Log panel
see above

**Comment by pbek** [comment]
I just built QOwnNotes on Manjaro from the AUR and had no troubles.


> /usr/include/qt/QtNetwork/qauthenticator.h:63:25: internal compiler error: Segmentation fault
> 63 | inline bool operator!=(const QAuthenticator &other) const { return !operator==(other); }

That doesn't ring any bell, is that something you exclusively have installed on your box?

**Comment by jjgalvez** [comment]
Not that I can remember, Although a long list of QT libraries were updates today on my system




Get Outlook for Android







On Mon, Sep 16, 2019 at 4:12 PM -0400, "Patrizio Bekerle" <notifications@github.com> wrote:












I just built QOwnNotes on Manjaro from the AUR and had no troubles.



/usr/include/qt/QtNetwork/qauthenticator.h:63:25: internal compiler error: Segmentation fault

63 | inline bool operator!=(const QAuthenticator &other) const { return !operator==(other); }



That doesn't ring any bell, is that something you exclusively have installed on your box?

**Comment by jjgalvez** [comment]
I'll try it on a clean install to see if that fixes the issue




Get Outlook for Android







On Mon, Sep 16, 2019 at 4:12 PM -0400, "Patrizio Bekerle" <notifications@github.com> wrote:












I just built QOwnNotes on Manjaro from the AUR and had no troubles.



/usr/include/qt/QtNetwork/qauthenticator.h:63:25: internal compiler error: Segmentation fault

63 | inline bool operator!=(const QAuthenticator &other) const { return !operator==(other); }



That doesn't ring any bell, is that something you exclusively have installed on your box?

**Comment by jjgalvez** [comment]
Sorry a reboot fixed the issues on my end. package builds as expected

**Comment by pbek** [comment]
Great :)
