### ISSUE TITLE
[I] Improper font size

### ISSUE THREAD

**Issue by jncolin** [pbek/QOwnNotes#1295]
#### Expected behaviour

I would expect to have the QOwnNote interface have the same appearance as the other windows in terms of font and widget sizes

#### Actual behaviour

The size of fonts and widgets is not properly scaled, which make the qownnotes window way too big for the screen

#### Steps to reproduce

Install Qownnotes on Fedora 30 running the standard window manager.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `jeu. sept. 19 14:15:53 2019`
**Version**: `19.9.14`
**Build date**: `Sep 18 2019`
**Build number**: `584`
**Platform**: `linux`
**Operating System**: `Fedora 30 (Workstation Edition)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.12.1`
**Qt Version (runtime)**: `5.12.4`
**Portable mode**: `no`
**Settings path / key**: `/home/jnc/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/jnc/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `Adwaita`
**Notes in current note folder**: `81`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://home.erigo.be/nextcloud`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `16.0.4.1`
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/jnc/Nextcloud/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/jnc/Nextcloud/Notes/notes.sqlite`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/vimMode** (bool): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2019-09-19T14:11:43.107`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Source Code Pro,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Cantarell,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Source Code Pro,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Cantarell,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 2 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `1`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `true`
**StartHidden** (bool): `true`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowDifferentNoteFileName** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**interfaceStyle** (QString): `Adwaita`
**internalIconTheme** (bool): `false`
**itemHeight** (int): `25`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/jnc/Nextcloud/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): `https://home.erigo.be/nextcloud`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Work, Personal, Erigo`
**ownCloud/todoCalendarEnabledList** (QStringList): `Work, Personal, Erigo`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://home.erigo.be/nextcloud/remote.php/dav/calendars/jnc/work/, https://home.erigo.be/nextcloud/remote.php/dav/calendars/jnc/personal/, https://home.erigo.be/nextcloud/remote.php/dav/calendars/jnc/erigo/`
**ownCloud/todoCalendarUrlList** (QStringList): `https://home.erigo.be/nextcloud/remote.php/dav/calendars/jnc/work/, https://home.erigo.be/nextcloud/remote.php/dav/calendars/jnc/personal/, https://home.erigo.be/nextcloud/remote.php/dav/calendars/jnc/erigo/`
**ownCloud/userName** (QString): `jnc`
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `16.0.4.1`
**restoreCursorPosition** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useUNIXNewline** (bool): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**SHELL**: `/bin/bash`
**SESSION_MANAGER**: `local/unix:@/tmp/.ICE-unix/15091,unix/unix:/tmp/.ICE-unix/15091`
**HISTCONTROL**: `ignoredups`
**XDG_MENU_PREFIX**: `gnome-`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**HISTSIZE**: `1000`
**HOSTNAME**: `chewie`
**LANGUAGE**: *empty*
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**XMODIFIERS**: `@im=ibus`
**DESKTOP_SESSION**: `gnome`
**LC_MONETARY**: `fr_BE.UTF-8`
**XDG_SEAT**: `seat0`
**ENV**: `/usr/share/Modules/init/profile.sh`
**PWD**: `/home/jnc`
**LOGNAME**: `jnc`
**XDG_SESSION_DESKTOP**: `gnome`
**XDG_SESSION_TYPE**: `wayland`
**MODULESHOME**: `/usr/share/Modules`
**MANPATH**: `:`
**WINDOWPATH**: `2`
**GDM_LANG**: `en_US.UTF-8`
**HOME**: `/home/jnc`
**USERNAME**: `jnc`
**LC_PAPER**: `fr_BE.UTF-8`
**LANG**: `en_US.UTF-8`
**XDG_CURRENT_DESKTOP**: `GNOME`
**MODULEPATH_modshare**: `/usr/share/modulefiles:1:/usr/share/Modules/modulefiles:1:/etc/modulefiles:1`
**XDG_SESSION_CLASS**: `user`
**LESSOPEN**: `||/usr/bin/lesspipe.sh %s`
**USER**: `jnc`
**MODULES_RUN_QUARANTINE**: `LD_LIBRARY_PATH`
**LOADEDMODULES**: *empty*
**QT_DBL_CLICK_DIST**: `22`
**SHLVL**: `0`
**BASH_ENV**: `/usr/share/Modules/init/bash`
**QT_IM_MODULE**: `ibus`
**LC_MEASUREMENT**: `fr_BE.UTF-8`
**XDG_VTNR**: `2`
**XDG_SESSION_ID**: `15`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**LC_TIME**: `fr_BE.UTF-8`
**XDG_DATA_DIRS**: `/home/jnc/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/`
**PATH**: `/home/jnc/.local/bin:/home/jnc/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin`
**MODULEPATH**: `/etc/scl/modulefiles:/etc/scl/modulefiles:/etc/scl/modulefiles:/etc/scl/modulefiles:/etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles`
**GDMSESSION**: `gnome`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**MAIL**: `/var/spool/mail/jnc`
**QT_SCALE_FACTOR**: `1.50`
**LC_NUMERIC**: `fr_BE.UTF-8`
**GOPATH**: `/home/jnc/dev/go`
**MODULES_CMD**: `/usr/share/Modules/libexec/modulecmd.tcl`
**BASH_FUNC_switchml%%**: 
```
() {  typeset swfound=1;
 if [ "${MODULES_USE_COMPAT_VERSION:-0}" = '1' ]; then
 typeset swname='main';
 if [ -e /usr/share/Modules/libexec/modulecmd.tcl ]; then
 typeset swfound=0;
 unset MODULES_USE_COMPAT_VERSION;
 fi;
 else
 typeset swname='compatibility';
 if [ -e /usr/share/Modules/libexec/modulecmd-compat ]; then
 typeset swfound=0;
 MODULES_USE_COMPAT_VERSION=1;
 export MODULES_USE_COMPAT_VERSION;
 fi;
 fi;
 if [ $swfound -eq 0 ]; then
 echo "Switching to Modules $swname version";
 source /usr/share/Modules/init/bash;
 else
 echo "Cannot switch to Modules $swname version, command not found";
 return 1;
 fi
}
```
**BASH_FUNC_module%%**: 
```
() {  unset _mlshdbg;
 if [ "${MODULES_SILENT_SHELL_DEBUG:-0}" = '1' ]; then
 case "$-" in 
 *v*x*)
 set +vx;
 _mlshdbg='vx'
 ;;
 *v*)
 set +v;
 _mlshdbg='v'
 ;;
 *x*)
 set +x;
 _mlshdbg='x'
 ;;
 *)
 _mlshdbg=''
 ;;
 esac;
 fi;
 unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" -a "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "`eval 'echo ${'$_mlv'+x}'`" ]; then
 _mlre="${_mlre:-}${_mlv}_modquar='`eval 'echo ${'$_mlv'}'`' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='`eval 'echo ${'$_mlrv':-}'`' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 eval `eval ${_mlre}/usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl bash '"$@"'`;
 else
 eval `/usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl bash "$@"`;
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 if [ -n "${_mlshdbg:-}" ]; then
 set -$_mlshdbg;
 fi;
 unset _mlshdbg;
 return $_mlstatus
}
```
**BASH_FUNC_scl%%**: 
```
() {  if [ "$1" = "load" -o "$1" = "unload" ]; then
 eval "module $@";
 else
 /usr/bin/scl "$@";
 fi
}
```
**GIO_LAUNCHED_DESKTOP_FILE**: `/usr/share/applications/PBE.QOwnNotes.desktop`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `18128`
**DISPLAY**: `:0`
**WAYLAND_DISPLAY**: `wayland-0`
**GJS_DEBUG_OUTPUT**: `stderr`
**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`
</details>

![Screenshot from 2019-09-19 14-18-26](https://user-images.githubusercontent.com/3629802/65243322-6eeffc00-dae8-11e9-9fe9-8715c0633198.png)

**Comment by pbek** [comment]
I see you have set the environment variable QT_SCALE_FACTOR: 1.50
This may causing the resize.

You can also set your font and icon sizes in the QOwnNotes settings.

**Comment by jncolin** [comment]
Thanks, forcing 0 to QT_SCALE_FACTOR works. But I could not find where it was set to 1.50

**Comment by pbek** [comment]
Great 😁
