### ISSUE TITLE
[F] Optimize Icon für QOwnNotes.exe

### ISSUE THREAD

**Issue by daniel-volz** [pbek/QOwnNotes#1297]
#### Expected behaviour

Clean Blue Icon for QOwnNotes.exe without white border

#### Actual behaviour

The Icon of the QOwnNotes.exe has a white Border around it.  
Is this the normal Icon? It looks strange

#### Steps to reproduce

Fresh Installation of QOwnNotes

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `So Sep 22 13:52:30 2019`
**Version**: `19.9.15`
**Build date**: `Sep 19 2019`
**Build number**: `4577`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.13.0`
**Qt Version (runtime)**: `5.13.0`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\Daniel Volz\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\_VOLZ\Tools\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `6`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://cloud.volzmedien.de`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `16.0.4.1`
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `3`

### Note folder `Standard`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `-1`
**localPath**: `C:\Users\Daniel Volz\Nextcloud\Notizen`
**remotePath**: *empty*
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\Daniel Volz\Nextcloud\Notizen\notes.sqlite`

### Note folder `VOLZMEDIEN`

**id**: `2`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `C:\Users\Daniel Volz\Nextcloud\Notizen\VOLZMEDIEN`
**remotePath**: *empty*
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\Daniel Volz\Nextcloud\Notizen\VOLZMEDIEN\notes.sqlite`

### Note folder `VOLZMEDIEN Webseite`

**id**: `3`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `W:\Webgestaltung\volzmedienDE\notizen`
**remotePath**: *empty*
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `W:\Webgestaltung\volzmedienDE\notizen\notes.sqlite`

### Note folder `Kundenprojekte`

**id**: `4`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `C:\Users\Daniel Volz\Nextcloud\Notizen\VOLZMEDIEN\Kundenprojekte`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\Daniel Volz\Nextcloud\Notizen\VOLZMEDIEN\Kundenprojekte\notes.sqlite`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `C:/Users/Daniel Volz/Desktop`
**FileDialog/LastPath-InsertImage** (QString): `C:/Users/Daniel Volz/Desktop`
**ImageDialog/disableCopying** (QString): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2019-09-22T13:49:19.697`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-2** (QStringList): `Dokumentationen`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `true`
**MessageBoxOverride/update-and-restart** (int): `16384`
**NoteHistory-1** (QVariantList): `<variant list with 1 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 22 item(s)>`
**NoteHistory-3** (QVariantList): `<variant list with 17 item(s)>`
**NoteHistory-4** (QVariantList): `<variant list with 2 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `0`
**NoteHistoryCurrentIndex-2** (int): `21`
**NoteHistoryCurrentIndex-3** (int): `16`
**NoteHistoryCurrentIndex-4** (int): `1`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `true`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `3`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `false`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (int): `15`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `W:/Webgestaltung/volzmedienDE/notizen`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/password** (QString): `<hidden>`
**ownCloud/serverUrl** (QString): `https://cloud.volzmedien.de`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Ferien, Feiertage, Urlaub Daniel, Termine, Bereitschaft, Müllentsorgung`
**ownCloud/todoCalendarEnabledList** (QStringList): `Ferien, Feiertage, Urlaub Daniel, Termine, Bereitschaft, Müllentsorgung`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://cloud.volzmedien.de/remote.php/dav/calendars/danielvolz/ferien-2018/, https://cloud.volzmedien.de/remote.php/dav/calendars/danielvolz/feiertage/, https://cloud.volzmedien.de/remote.php/dav/calendars/danielvolz/urlaub/, https://cloud.volzmedien.de/remote.php/dav/calendars/danielvolz/termine/, https://cloud.volzmedien.de/remote.php/dav/calendars/danielvolz/bereitschaft/, https://cloud.volzmedien.de/remote.php/dav/calendars/danielvolz/mllentsorgung/`
**ownCloud/todoCalendarUrlList** (QStringList): `https://cloud.volzmedien.de/remote.php/dav/calendars/danielvolz/ferien-2018/, https://cloud.volzmedien.de/remote.php/dav/calendars/danielvolz/feiertage/, https://cloud.volzmedien.de/remote.php/dav/calendars/danielvolz/urlaub/, https://cloud.volzmedien.de/remote.php/dav/calendars/danielvolz/termine/, https://cloud.volzmedien.de/remote.php/dav/calendars/danielvolz/bereitschaft/, https://cloud.volzmedien.de/remote.php/dav/calendars/danielvolz/mllentsorgung/`
**ownCloud/userName** (QString): `danielvolz`
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unbekannter Fehler`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `16.0.4.1`
**recentNoteFolders** (QStringList): `C:/Users/Daniel Volz/Nextcloud/Notizen/VOLZMEDIEN/Kundenprojekte, C:/Users/Daniel Volz/Nextcloud/Notizen/VOLZMEDIEN, C:/Users/Daniel Volz/Nextcloud/Notizen`
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-2** (QStringList): `ports`
**savedSearches/noteFolder-3** (QStringList): `Note 2019-08-30T21.58.53, Note 2019-08-30T21.13.10, Note 2019-08-29T22.24.12, Note 2019-08-29T22.22.47, Note 2019-08-29T22.21.18, Note 2019-08-29T22.19.57, Note 2019-08-29T22.18.01`
**savedSearches/noteFolder-4** (QStringList): `Note 2019-09-11T20.05.04`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Hauptsymbolleiste`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `Formatierungs-Werkzeugleiste`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `Einfügen-Werkzeugleiste`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `Werkzeugleiste Verschlüsselung`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `Fenster-Werkzeugleiste`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `Beenden - Symbolleiste`
**toolbar/size** (int): `6`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Vollständig`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\Daniel Volz\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `VOLZ-PC`
**ComSpec**: `C:\Windows\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\Daniel Volz`
**INTEL_DEV_REDIST**: `C:\Program Files (x86)\Common Files\Intel\Shared Libraries\`
**JD2_HOME**: `C:\Program Files (x86)\jDownloader`
**LOCALAPPDATA**: `C:\Users\Daniel Volz\AppData\Local`
**LOGONSERVER**: `\\VOLZ-PC`
**MIC_LD_LIBRARY_PATH**: `C:\Program Files (x86)\Common Files\Intel\Shared Libraries\compiler\lib\mic`
**NUMBER_OF_PROCESSORS**: `24`
**OneDrive**: `C:\Users\Daniel Volz\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files (x86)\Common Files\Acronis\VirtualFile\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile64\;C:\Program Files (x86)\Common Files\Acronis\FileProtector\;C:\Program Files (x86)\Common Files\Acronis\FileProtector64\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Smart Projects\IsoBuster;C:\Users\Daniel Volz\AppData\Local\Microsoft\WindowsApps;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD`
**PROCESSOR_LEVEL**: `23`
**PROCESSOR_REVISION**: `0101`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Intel\Wired Networking\`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\Windows`
**TEMP**: `C:\Users\DANIEL~1\AppData\Local\Temp`
**TMP**: `C:\Users\DANIEL~1\AppData\Local\Temp`
**USERDOMAIN**: `VOLZ-PC`
**USERDOMAIN_ROAMINGPROFILE**: `VOLZ-PC`
**USERNAME**: `Daniel Volz`
**USERPROFILE**: `C:\Users\Daniel Volz`
**windir**: `C:\Windows`
</details>

**Comment by pbek** [comment]
Try the icon in a dark taskbar, then you'll find out that you almost can't see the dark blue logo. That's why it got the border. :smile:

**Comment by pbek** [comment]
I will close this issue until there is more information.
