### ISSUE TITLE
gibberish (decrypt)

### ISSUE THREAD

**Issue by manamaori** [pbek/QOwnNotes#1299]
I decrypted one of my notes and got the following result. Other notes are decrypting properly why not this one? How would I be able to remedy this? Plse help.
![gibberish](https://user-images.githubusercontent.com/20309708/65841508-8d26e900-e37f-11e9-8369-24a01207e56d.png)

**Comment by pbek** [comment]
Can you please fill out the issue template so that I may help you.

**Comment by pbek** [comment]
Do you have a older backup of the note file? Maybe a character got replaced in the note file, that could destroy the encrypted note.

**Comment by manamaori** [comment]
sorry but I can't find the issue template.. unfortunately I don't have an older backup of the note. Basically the note was something like this... <!-- BEGIN ENCRYPTED TEXT --YMtbyHQl9...  As I normally do I selected decrypt and entered the password (now I may have entered the wrong password but QOwnNotes usually gives an error/retry). In this case the entire note switched to gibberish as seen above. The decrypt button is blanked out so that option is unavailable.

**Comment by pbek** [comment]
> sorry but I can't find the issue template

well, when you created this issue you saw it

QOwnNotes doesn't allow editing of the still encrypted note, maybe you added some characters to the encrypted text in an other application.

Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging.

**Comment by manamaori** [comment]
damn... logging was unticked. If the note is still encrypted is there a way of decrypting it within or without QOwnNotes? as I haven't lost the access password.

**Comment by pbek** [comment]
Is there any useful log output when you access the note if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging.

**Comment by pbek** [comment]
I will close this issue until there is more information.
