### ISSUE TITLE
Existing Subfolders with QOwnNotes

### ISSUE THREAD

**Issue by chalbersma** [pbek/QOwnNotes#130]
So I have a directory sturcture for my notes as follows:

```
Notes
├── Thing 1
├── Other Thing
├── Project X
├── Angry Reddit Posts
...

However only markdown notes direclty under Notes show up in QOwnNotes. Is it possible to get QOwnNotes to support Subfolders?

**Comment by pbek** [comment]
That is true, only notes from the current folder will be in the note list. It is mimicking the behavior of the ownCloud notes app (and the iOS and Android clients).

Although you can configure as many note folders as you like in the note folder settings.
Does this answer your question?

**Comment by chalbersma** [comment]
So what do you do when you need to organize your notes? Is there a best
practice?

**Comment by pbek** [comment]
I personally have about 1000 notes in my note folder and do a full text search when I need something from the far past. Additionally I have an `Archive` folder where I put stuff I haven't needed for very long.

I don't want to click through a tree or tag structure to find something, I just press `Ctrl + Shift + F` and search for a word.

**Comment by pbek** [comment]
By public demand a tag implementation is currently in the works.

Each note folder will have its own database (with tags and their links to certain note files). The database is a sqlite file, that will be stored directly in the note folder.

I hope it will play together with syncing the database-file via ownCloud and with external changes of the database-file.

**Comment by chalbersma** [comment]
Thanks!

**Comment by pbek** [comment]
Version 1.3.7 with tagging support is now out. Can you please test it and report issues?

- you can turn on tagging with <kbd>Alt</kbd> + <kbd>⇧</kbd> + <kbd>T</kbd>
- tags and their associations to note files are stored in each note folder
  individually in a SQLite database
- if notes are renamed by QOwnNotes the tags will be moved to the renamed
  notes
- if notes are move to an other folder their associated tags are lost 
- <kbd>Alt</kbd> + <kbd>⇧</kbd> + <kbd>A</kbd> adds a new tag to a note

**Comment by pbek** [comment]
I am closing this issue until there is feedback.
