### ISSUE TITLE
Quotation marks are present in the filenames of all newly create files.

### ISSUE THREAD

**Issue by paulcalabro** [pbek/QOwnNotes#1300]
#### Expected behaviour

As a user, I would expect that  quotation marks would not be automatically added to filenames.
  
e.g.   
  
```  
-rw-r--r-- 1 www-data www-data   1743 Oct  1 21:22 'Book Notes Getting Things Done by David Allen.md'
```

#### Actual behaviour

Quotation marks are present in the filenames of all newly create files.

#### Steps to reproduce

1. Create a note using the OSX version of the application  
2. Go to your Notes directory and examine the filenames. You should see quotation marks in the filenames which were not provided by the user.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Oct 1 14:33:51 2019`
**Version**: `19.10.0`
**Build date**: `Sep 30 2019`
**Build number**: `4585`
**Platform**: `macosx`
**Operating System**: `macOS Mojave (10.14)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.12.2`
**Qt Version (runtime)**: `5.12.2`
**Portable mode**: `no`
**Settings path / key**: `/Users/<REDACTED>/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/<REDACTED>/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `26`
**Calendar items**: `13`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://nextcloud.<REDACTED>`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `16.0.4.1`
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/Users/<REDACTED>/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/Users/<REDACTED>/Nextcloud/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://nextcloud.<REDACTED>`
**username**: `<REDACTED>`

## Settings

**646F6E7A_00000000_00000001_6E7A6361_696D6963** (qlonglong): `1`
**AKLastCheckInAttemptDate** (QDateTime): `2019-10-01T09:44:10.684`
**AKLastCheckInSuccessDate** (QDateTime): `2019-10-01T09:44:11.370`
**AKLastEmailListRequestDateKey** (QDateTime): `2019-08-17T15:36:49.072`
**AKLastIDMSEnvironment** (qlonglong): `0`
**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Cypress Semiconductor Type-C DP Dongle** (QString): `1`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**DistractionFreeMode/isEnabled** (bool): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (qlonglong): `0`
**DistractionFreeMode/menuBarVisible** (bool): `false`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**EPSON DS-80W** (QString): `1`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/vimMode** (bool): `false`
**EvernoteImport/AttachmentImportCheckBoxChecked** (bool): `true`
**EvernoteImport/ImageImportCheckBoxChecked** (bool): `true`
**EvernoteImport/MetaDataUnCheckedList** (QStringList): `, `
**EvernoteImportDialog/geometry** (QByteArray): `<binary data>`
**FileDialog/LastPath** (QString): `/Users/<REDACTED>/Desktop`
**FileDialog/LastPath-EvernoteImport** (QString): `/Users/<REDACTED>/Desktop`
**FileDialog/LastPath-InsertImage** (QString): `/Users/<REDACTED>/Desktop`
**HP OfficeJet 4650 series** (QString): `1`
**ImageDialog/disableCopying** (bool): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2019-10-01T13:56:51.567`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (qlonglong): `32`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Personal`
**MainWindow/noteTextEdit.code.font** (QString): `Monaco,18,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `.SF NS Text,18,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Monaco,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `.SF NS Text,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**MediaTek MT65xx Preloader** (QString): `1`
**MessageBoxOverride/move-notes** (qlonglong): `16384`
**MessageBoxOverride/remove-notes** (qlonglong): `16384`
**MessageBoxOverride/update-and-restart** (qlonglong): `16384`
**Microsoft Controller** (QString): `1`
**NoteHistory-1** (QVariantList): `<variant list with 75 item(s)>`
**NoteHistoryCurrentIndex-1** (qlonglong): `74`
**PKSecureElementAvailableFlags** (qlonglong): `3`
**PKSecureElementAvailableFlagsByHost** (qlonglong): `3`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (qlonglong): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (qlonglong): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Personal`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**VersionDialog/geometry** (QByteArray): `<binary data>`
**WebAutomaticSpellingCorrectionEnabled** (bool): `true`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**Xerox Global Print Driver PCL6** (QString): `1`
**acceptAllExternalModifications** (bool): `false`
**allowDifferentNoteFileName** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `false`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (bool): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**com/omnigroup/OmniGraffle7:4** (QByteArray): `<binary data>`
**com/omnigroup/OmniGraffle7:7:3** (QByteArray): `<binary data>`
**com/omnigroup/OmniGraffle7:7:4** (QByteArray): `<binary data>`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (qlonglong): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (qlonglong): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `true`
**darkModeColors** (bool): `true`
**darkModeIconTheme** (bool): `true`
**darkModeTrayIcon** (bool): `true`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (bool): `false`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (bool): `true`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (qlonglong): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (qlonglong): `1024`
**imageScaleDownMaximumWidth** (qlonglong): `1024`
**initialLayoutIdentifier** (QString): `full-vertical`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (qlonglong): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (qlonglong): `18`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (qlonglong): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `false`
**networking/proxyType** (qlonglong): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `false`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (qlonglong): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (qlonglong): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (qlonglong): `0`
**notesPanelOrder** (qlonglong): `0`
**notesPanelSort** (qlonglong): `1`
**notesPath** (QString): `/Users/<REDACTED>/Nextcloud/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (qlonglong): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Personal, Family, Work`
**ownCloud/todoCalendarEnabledList** (QStringList): `Personal, Family, Work`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://nextcloud.<REDACTED>/remote.php/dav/calendars/<REDACTED>/personal/, https://nextcloud.<REDACTED>/remote.php/dav/calendars/<REDACTED>/family/, https://nextcloud.<REDACTED>/remote.php/dav/calendars/<REDACTED>/work-1/`
**ownCloud/todoCalendarUrlList** (QStringList): `https://nextcloud.<REDACTED>/remote.php/dav/calendars/<REDACTED>/personal/, https://nextcloud.<REDACTED>/remote.php/dav/calendars/<REDACTED>/family/, https://nextcloud.<REDACTED>/remote.php/dav/calendars/<REDACTED>/work-1/`
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `16.0.4.1`
**restoreCursorPosition** (bool): `false`
**savedSearches/noteFolder-1** (QStringList): `Note 2019-10-01T13.56.57, Note 2019-10-01T10.10.13, Email - Nextcloud, Note 2019-09-23T14.47.19, Note 2019-09-20T10.42.14, Note 2019-09-18T14.32.43, How to secure Postfix using Let's Encrypt - UpCloud, Note 2019-09-15T09.49.56, RFC 7208 - Sender Policy Framework (SPF) for Authorizing Use of Domains in Email, Version 1, How does power affect soldering irons Is 30 Watts enough - Electrical Engineering Stack Exchange, Note 2019-09-12T13.16.58, Note 2019-09-11T23.00.50, Note 2019-09-10T22.47.17, Note 2019-09-10T13.26.08, Note 2019-09-08T20.37.51, Note 2019-09-07T14.57.28, Note 2019-09-06T20.41.43, Note 2019-09-06T14.35.44, Note 2019-09-06T09.36.53, Note 2019-09-06T01.29.34`
**showMenuBar** (bool): `false`
**showStatusBar** (bool): `true`
**systemIconTheme** (bool): `false`
**tagWasAddedToNote** (bool): `true`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (qlonglong): `0`
**tagsPanelSort** (qlonglong): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (qlonglong): `6`
**useUNIXNewline** (bool): `false`
**versionSplitterSizes** (QByteArray): `<binary data>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (qlonglong): `22222`
**webSocketServerService/token** (QString): `u87GUqZt`
**workspace-initial/name** (QString): `Full vertical`
**workspace-initial/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**TMPDIR**: `/var/folders/zx/rtb43kw13mb2sx_307kh2r903934n9/T/`
**__CF_USER_TEXT_ENCODING**: `0x69192A9:0x0:0x0`
**HOME**: `/Users/<REDACTED>`
**SHELL**: `/bin/zsh`
**Apple_PubSub_Socket_Render**: `/private/tmp/com.apple.launchd.k8Fv4JzxUX/Render`
**SSH_AUTH_SOCK**: `/private/tmp/com.apple.launchd.GJWywzM73c/Listeners`
**PATH**: `/usr/bin:/bin:/usr/sbin:/sbin`
**LOGNAME**: `<REDACTED>`
**DISPLAY**: `/private/tmp/com.apple.launchd.HNJu2tZ4qe/org.macosforge.xquartz:0`
**XPC_SERVICE_NAME**: `com.PBE.QOwnNotes.11588`
**USER**: `<REDACTED>`
**XPC_FLAGS**: `0x0`
**QT_LOGGING_RULES**: `qt.network.ssl.warning=false`
</details>

**Comment by pbek** [comment]
I cannot reproduce this on Mojave, my new note is named `Note 2019-10-02T05.32.18.md`. Can you please elaborate on your point 1. What exactly did you do?

**Comment by pbek** [comment]
And is there any useful log output while you are creating that note if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging.

**Comment by paulcalabro** [comment]
Here's a video that reproduces the issue (the gif was too large to insert here):

https://nextcloud.paulcalabro.com/s/gtj5Paz8RJJYdWM

And here's the debug log:

```
[21:46:55] [debug] setCurrentNote - 'note': Note: <id>13 <name>"Test title" <fileName>"Test title.md" <noteSubFolderId>1 <relativePath>"Test" <hasDirtyData>false - 'updateNoteText': true - 'updateSelectedNote': false
[21:46:55] [debug] cloudConnection: CloudConnection: <id>1 <name>"Default" <serverUrl>"https://nextcloud.paulcalabro.com" <username>"paulcalabro" <priority>1
[21:46:55] [debug] added to history: NoteHistoryItem: <noteName>"Test title" <noteSubFolderPathData>"Test" <cursorPosition>0 <relativeScrollBarPosition>0
[21:46:55] [debug] cloudConnection: CloudConnection: <id>1 <name>"Default" <serverUrl>"https://nextcloud.paulcalabro.com" <username>"paulcalabro" <priority>1
[21:46:55] [debug] on_action_Open_note_in_external_editor_triggered - 'url': QUrl("file:///Users/pcalabro/Nextcloud/Notes/Test/Test title.md")
[21:46:57] [debug] Reply from "/ocs/v2.php/apps/files_sharing/api/v1/shares"
[21:46:57] [debug] Reply from share api
[21:46:57] [debug] updateNoteShareStatusFromShare - 'status': "ok\n"
[21:46:57] [debug] Reply from "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[21:46:57] [debug] Reply from app version test
[21:46:57] [debug] notesDirectoryWasModified: "/Users/pcalabro/Nextcloud/Notes/Test"
[21:46:57] [status] Notes directory was modified externally
[21:46:57] [debug] buildNotesIndex - 'noteSubFolderId': 0
[21:46:57] [debug] buildNotesIndex - 'noteSubFolderId': 1
[21:46:57] [debug] buildNotesIndex - 'noteSubFolderId': 2
[21:46:57] [debug] buildNotesIndex - 'noteSubFolderId': 3
[21:46:57] [debug] setupNoteFolderTables - 'database version': 13
[21:46:57] [debug] cloudConnection: CloudConnection: <id>1 <name>"Default" <serverUrl>"https://nextcloud.paulcalabro.com" <username>"paulcalabro" <priority>1
[21:46:57] [debug] fetchShares - 'url': QUrl("https://nextcloud.paulcalabro.com/ocs/v2.php/apps/files_sharing/api/v1/shares")
[21:46:57] [debug] updateNoteText: false
[21:46:57] [debug] setCurrentNote - 'note': Note: <id>13 <name>"Test title" <fileName>"Test title.md" <noteSubFolderId>1 <relativePath>"Test" <hasDirtyData>false - 'updateNoteText': false - 'updateSelectedNote': true
[21:46:57] [debug] added to history: NoteHistoryItem: <noteName>"Test title" <noteSubFolderPathData>"Test" <cursorPosition>0 <relativeScrollBarPosition>0
[21:46:57] [debug] notesWereModified: "/Users/pcalabro/Nextcloud/Notes/Test/Test title.md"
[21:46:58] [debug] Reply from "/ocs/v2.php/apps/files_sharing/api/v1/shares"
[21:46:58] [debug] Reply from share api
[21:46:58] [debug] updateNoteShareStatusFromShare - 'status': "ok\n"
[21:47:11] [debug] filterNotesByNoteSubFolders - 'noteSubFolderIds': (1)
[21:47:42] [debug] openLinkAtCursorPosition - 'emit urlClicked( urlString )': ""
```

**Comment by pbek** [comment]
https://nextcloud.paulcalabro.com/s/gtj5Paz8RJJYdWM shows "forbidden" to me. 

> [21:46:57] [debug] notesWereModified: "/Users/pcalabro/Nextcloud/Notes/Test/Test title.md"

nothing seems out of order here with this filename

**Comment by pbek** [comment]
> [21:46:55] [debug] on_action_Open_note_in_external_editor_triggered - 'url': QUrl("file:///Users/pcalabro/Nextcloud/Notes/Test/Test title.md")

this looks fine too

**Comment by paulcalabro** [comment]
Ahhh, sorry. I have AWS WAF setup to restrict access to the site only from the US. That's why you're getting denied.

Here's what I'm seeing in my Notes directory:

```
root@nextcloud:/var/www/html/data/paulcalabro/files/Notes# ls -ltr
total 304
-rw-r--r--  1 www-data www-data    129 Sep  6 22:24 ' DNS Information of ALB.md'
-rw-r--r--  1 www-data www-data    431 Sep  6 22:24 'Instructions for Installing 7 Days to Die Mods.txt'
-rw-r--r--  1 www-data www-data   9750 Sep  6 22:24 'Server Aptitude Logs.txt'
drwxr-xr-x  2 www-data www-data   4096 Sep 12 06:16  Work
-rw-r--r--  1 www-data www-data    254 Sep 12 20:17 'Note 2019-09-12T13.16.58.md'
-rw-r--r--  1 www-data www-data    518 Sep 13 19:58  Bookmarks.md
-rw-r--r--  1 www-data www-data   4005 Sep 13 20:00 'How does power affect soldering irons Is 30 Watts enough - Electrical Engineering Stack Exchange.md'
-rw-r--r--  1 www-data www-data 157189 Sep 15 13:08 'RFC 7208 - Sender Policy Framework (SPF) for Authorizing Use of Domains in Email, Version 1.md'
-rw-r--r--  1 www-data www-data   2732 Sep 15 17:15 "Notes for Configuring Let's Encrypt.md"
-rw-r--r--  1 www-data www-data  34650 Sep 15 19:05 '[httpsupcloud.comcommunitytutorialssecure-postfix-using-lets-encrypt](httpsupcloud.comcommunitytutorialssecure-postfix-using-lets-encrypt)**.md'
drwxr-xr-x  2 www-data www-data   4096 Sep 16 23:43  media
-rw-r--r--  1 www-data www-data     66 Sep 17 05:41 'Personal Website Ideas.md'
-rw-r--r--  1 www-data www-data    477 Sep 17 16:08 'Adblock Filters List.md'
drwxr-xr-x  2 www-data www-data   4096 Sep 17 17:05  attachments
-rw-r--r--  1 www-data www-data     78 Oct  1 17:10 'Note 2019-10-01T10.10.13.md'
-rw-r--r--  1 www-data www-data  45056 Oct  2 04:59  notes.sqlite
drwxr-xr-x  2 www-data www-data   4096 Oct  2 04:59  trash
drwxr-----+ 3 www-data www-data   4096 Oct  2 04:59  Personal
```

**Comment by paulcalabro** [comment]
That note created above also had quotes around its filename as well.

**Comment by paulcalabro** [comment]
Here's the mp4 zipped up:

[issue.mp4.zip](https://github.com/pbek/QOwnNotes/files/3682102/issue.mp4.zip)

**Comment by pbek** [comment]
The Let's encrypt note even has a `"` (I guess because of the `'` in `Let's`, I've never seen that before. :laughing:

**Comment by pbek** [comment]
> root@nextcloud:/var/www/html/data/paulcalabro/files/Notes# ls -ltr

What are you showing me here? the notes that got synced to you Nextcloud server?  So is the Nextcloud sync client causing this? Not QOwnNotes?

**Comment by pbek** [comment]
The video also show you listing the files on your Nextcloud instance. QOwnNotes has no influence on how Nextcloud is storing your files on your server and why do you care as long the files are synced correctly to other devices. I thought you were talking about your local note folder.

**Comment by paulcalabro** [comment]
Nevermind, I figured it out :-)
Apparently my Docker instances has some weird version of `coreutils` that adds quotes to files when they contain spaces:

```
root@nextcloud:/var/www/html/data/paulcalabro/files/Notes# ls -ltr
total 304
-rw-r--r--  1 www-data www-data    129 Sep  6 22:24 ' DNS Information of ALB.md'
-rw-r--r--  1 www-data www-data    431 Sep  6 22:24 'Instructions for Installing 7 Days to Die Mods.txt'
-rw-r--r--  1 www-data www-data   9750 Sep  6 22:24 'Server Aptitude Logs.txt'
drwxr-xr-x  2 www-data www-data   4096 Sep 12 06:16  Work
-rw-r--r--  1 www-data www-data    254 Sep 12 20:17 'Note 2019-09-12T13.16.58.md'
-rw-r--r--  1 www-data www-data    518 Sep 13 19:58  Bookmarks.md
-rw-r--r--  1 www-data www-data   4005 Sep 13 20:00 'How does power affect soldering irons Is 30 Watts enough - Electrical Engineering Stack Exchange.md'
-rw-r--r--  1 www-data www-data 157189 Sep 15 13:08 'RFC 7208 - Sender Policy Framework (SPF) for Authorizing Use of Domains in Email, Version 1.md'
-rw-r--r--  1 www-data www-data   2732 Sep 15 17:15 "Notes for Configuring Let's Encrypt.md"
-rw-r--r--  1 www-data www-data  34650 Sep 15 19:05 '[httpsupcloud.comcommunitytutorialssecure-postfix-using-lets-encrypt](httpsupcloud.comcommunitytutorialssecure-postfix-using-lets-encrypt)**.md'
drwxr-xr-x  2 www-data www-data   4096 Sep 16 23:43  media
-rw-r--r--  1 www-data www-data     66 Sep 17 05:41 'Personal Website Ideas.md'
-rw-r--r--  1 www-data www-data    477 Sep 17 16:08 'Adblock Filters List.md'
drwxr-xr-x  2 www-data www-data   4096 Sep 17 17:05  attachments
-rw-r--r--  1 www-data www-data     78 Oct  1 17:10 'Note 2019-10-01T10.10.13.md'
-rw-r--r--  1 www-data www-data  45056 Oct  2 04:59  notes.sqlite
drwxr-xr-x  2 www-data www-data   4096 Oct  2 04:59  trash
drwxr-----+ 3 www-data www-data   4096 Oct  2 04:59  Personal
```
```
root@nextcloud:/var/www/html/data/paulcalabro/files/Notes# export QUOTING_STYLE=literal
root@nextcloud:/var/www/html/data/paulcalabro/files/Notes# ls -ltr
total 304
-rw-r--r--  1 www-data www-data    129 Sep  6 22:24  DNS Information of ALB.md
-rw-r--r--  1 www-data www-data    431 Sep  6 22:24 Instructions for Installing 7 Days to Die Mods.txt
-rw-r--r--  1 www-data www-data   9750 Sep  6 22:24 Server Aptitude Logs.txt
drwxr-xr-x  2 www-data www-data   4096 Sep 12 06:16 Work
-rw-r--r--  1 www-data www-data    254 Sep 12 20:17 Note 2019-09-12T13.16.58.md
-rw-r--r--  1 www-data www-data    518 Sep 13 19:58 Bookmarks.md
-rw-r--r--  1 www-data www-data   4005 Sep 13 20:00 How does power affect soldering irons Is 30 Watts enough - Electrical Engineering Stack Exchange.md
-rw-r--r--  1 www-data www-data 157189 Sep 15 13:08 RFC 7208 - Sender Policy Framework (SPF) for Authorizing Use of Domains in Email, Version 1.md
-rw-r--r--  1 www-data www-data   2732 Sep 15 17:15 Notes for Configuring Let's Encrypt.md
-rw-r--r--  1 www-data www-data  34650 Sep 15 19:05 [httpsupcloud.comcommunitytutorialssecure-postfix-using-lets-encrypt](httpsupcloud.comcommunitytutorialssecure-postfix-using-lets-encrypt)**.md
drwxr-xr-x  2 www-data www-data   4096 Sep 16 23:43 media
-rw-r--r--  1 www-data www-data     66 Sep 17 05:41 Personal Website Ideas.md
-rw-r--r--  1 www-data www-data    477 Sep 17 16:08 Adblock Filters List.md
drwxr-xr-x  2 www-data www-data   4096 Sep 17 17:05 attachments
-rw-r--r--  1 www-data www-data     78 Oct  1 17:10 Note 2019-10-01T10.10.13.md
-rw-r--r--  1 www-data www-data  45056 Oct  2 04:59 notes.sqlite
drwxr-xr-x  2 www-data www-data   4096 Oct  2 04:59 trash
drwxr-----+ 3 www-data www-data   4096 Oct  2 04:59 Personal
```

More information here:
https://superuser.com/questions/1376351/why-does-ls-wrap-some-filenames-in-single-quotes

Thanks for your help!

**Comment by pbek** [comment]
Nice, good to know that this is even possible. :) I already thought that it was a problem of your `ls`, but I couldn't find any clue in your macOS env. But since you were talking about your docker container... 😄

**Comment by paulcalabro** [comment]
Yeah, I had no idea that feature existed either. Good to know! 😄
