### ISSUE TITLE
Unicode emojis don't show

### ISSUE THREAD

**Issue by Xananax** [pbek/QOwnNotes#1301]
If you have a bare bones desktop (in my case: X + I3), you might find that emojis don't display properly in QT apps.

Instead of "🙂,🇨🇦,🤩,🥳 or 🦮", you will see "▯,▯,▯,▯ or ▯". Pretty annoying.

### Solution!

*(found [here](https://chrpaul.de/2019/07/Enable-colour-emoji-support-on-Manjaro-Linux.html))*

**Step 1**: Install `noto-fonts`
```sh
yay -S noto-fonts
```
*note*: we actually need only `noto-fonts-emoji`, but for the setup below to be copy-pastable as is, you need the other noto fonts too. So, for simplicity, install the meta-package.

**Step 2**: Create or edit the file `~/.config/fontconfig/conf.d/01-emoji.conf`

Paste the following:

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
 <alias>
   <family>sans-serif</family>
   <prefer>
     <family>Noto Sans</family>
     <family>Noto Color Emoji</family>
     <family>Noto Emoji</family>
     <family>DejaVu Sans</family>
   </prefer> 
 </alias>

 <alias>
   <family>serif</family>
   <prefer>
     <family>Noto Serif</family>
     <family>Noto Color Emoji</family>
     <family>Noto Emoji</family>
     <family>DejaVu Serif</family>
   </prefer>
 </alias>

 <alias>
  <family>monospace</family>
  <prefer>
    <family>Noto Mono</family>
    <family>Noto Color Emoji</family>
    <family>Noto Emoji</family>
   </prefer>
 </alias>
</fontconfig>
```

Save. 

**Step 3**: ...?

**Step 4**: Open QownNotes. Hopefully, it must've worked, and you can now see emojis. Profit!

**Comment by pbek** [comment]
Great, thank you for the documentation. Will surely help others with the same problem!

**Comment by Zack-83** [comment]
Apparently the described folder is read-only and just a mirror of the other folder `/usr/share/fontconfig/conf.avail/` (as explained in the README file)

Therefore i would correct your documentation like that:

**Step 2**: Create a file 01-emoji.conf on your desktop with the following content: ...
**Step 2 bis**: Move the file with admin privileges, for instance via command line:
```
sudo mv ~/Desktop/01-emoji.conf /usr/share/fontconfig/conf.avail/
```
**Step 3**: Restart your system

...

**Comment by Zack-83** [comment]
Hallo,
with country flags it does not work. The strange thing is, until two weeks ago (with Ubuntu 18.04 64 bit) it worked perfectly. After reinstalling the operating system several times, it does not work any more.
