### ISSUE TITLE
BUG: Crash after exiting full screen mode

### ISSUE THREAD

**Issue by ivanpirog** [pbek/QOwnNotes#1302]
**System**: Windows 32bit

1. The QON starts in full screen mode.
2. When I exit full screen mode, the QON crashes.

**Video**: https://youtu.be/1EnOBP3nFsM

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue.

**Comment by pbek** [comment]
Do you have a strack trace of the crash?

**Comment by ivanpirog** [comment]
> Do you have a strack trace of the crash?

How to get stack trace?
I have log file only, but nothing interesting inside.

BTW, the same problem on Windows 10 64bit on my another computer.
It seems that the version of windows doesn't matter.

**Comment by pbek** [comment]
How did you start QOwnNotes in fullscreen mode? That's not a feature of QOwnNotes.

**Comment by ivanpirog** [comment]
> How did you start QOwnNotes in fullscreen mode? That's not a feature of QOwnNotes.

I just close QON in fullscreen mode:

1. QON in normal window mode
2. Press Ctrl+Shift+D - Turn on the distraction free mode
3. Press F11 - Turn on fullscreen mode
4. Press Alt+F4 - Close App
5. Run QON again

And then QON starts in fullscreen mode.

There is [qon.reg](https://www.ivanpirog.com/uploads/qon.reg) file with my settings. Try to import this registry value:

`HKEY_CURRENT_USER\Software\PBE\QOwnNotes\workspace-initial\windowState`

**Comment by ivanpirog** [comment]
Pay attention to this registry value:

`HKEY_CURRENT_USER\Software\PBE\QOwnNotes\MainWindow\geometry`

When I deleted this value QON starts in the normal window mode. Just try to import this value from my qon.reg file.

**Comment by ivanpirog** [comment]
> I just close QON in fullscreen mode:
>     1. QON in normal window mode
>     2. Press Ctrl+Shift+D - Turn on the distraction free mode
>     3. Press F11 - Turn on fullscreen mode
>     4. Press Alt+F4 - Close App
>     5. Run QON again
>
> And then QON starts in fullscreen mode.

Hmm... I can't repeat issue with these steps. Only after exporting the registry file do I get a problem. I'm exploring for now...

**Comment by ivanpirog** [comment]
Yeah! I found how to run in full screen :)

1. QON in normal window mode
2. **Press Ctrl+Shift+D - Turn on the distraction free mode**
3. **Press F11 - Turn on fullscreen mode**
4. Press Alt+F4 - Close App
5. Run QON again

Just swap steps 2 and 3 :-) The sequence of steps is very important!!

**Here is the complete instruction:**

1. QON in normal window mode
2. Press F11 - Turn on fullscreen mode
3. Press Ctrl+Shift+D - Turn on the distraction free mode
4. Press Alt+F4 - Close App
5. Run QON again

**Video here:** https://youtu.be/J1-aFCtMLEo

**Comment by pbek** [comment]
Thank you.
(Note: regression from #1271)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by ivanpirog** [comment]
Works fine! Thank you 👍

**Comment by pbek** [comment]
Great, thank you for testing!
