### ISSUE TITLE
[I] QON crashes when i click owncloud/nextcloud settings in first run after install from ppa

### ISSUE THREAD

**Issue by Coshibu** [pbek/QOwnNotes#1303]
#### Expected behaviour

open nextcloud server setting

#### Actual behaviour

app crashes

#### Steps to reproduce

install QON from ppa, run, at the end of setup click : Owncloud/nextcloud settings -> crashes

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `tis okt. 8 13:06:53 2019`
**Version**: `19.10.1`
**Build date**: `Oct  4 2019`
**Build number**: `592`
**Platform**: `linux`
**Operating System**: `Ubuntu 18.04.3 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.9.5`
**Qt Version (runtime)**: `5.9.5`
**Portable mode**: `no`
**Settings path / key**: `/home/masi/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/masi/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `ubuntu-mono-dark`
**Notes in current note folder**: `3`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/masi/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/masi/Nextcloud/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2019-10-08T13:04:06`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `bce33966-e826-4d80-bb75-780a17d84d00`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `17`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/masi/Nextcloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `48a1e734-b761-46d5-b947-764411ab12fe`
**restoreCursorPosition** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-48a1e734-b761-46d5-b947-764411ab12fe/name** (QString): `full`
**workspace-48a1e734-b761-46d5-b947-764411ab12fe/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-48a1e734-b761-46d5-b947-764411ab12fe/windowState** (QByteArray): `<binary data>`
**workspace-bce33966-e826-4d80-bb75-780a17d84d00/name** (QString): `minimal`
**workspace-bce33966-e826-4d80-bb75-780a17d84d00/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-bce33966-e826-4d80-bb75-780a17d84d00/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `48a1e734-b761-46d5-b947-764411ab12fe, bce33966-e826-4d80-bb75-780a17d84d00`

## System environment

**USER**: `masi`
**LC_TIME**: `sv_SE.UTF-8`
**TEXTDOMAIN**: `im-config`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `3150`
**SHLVL**: `0`
**QT4_IM_MODULE**: `xim`
**HOME**: `/home/masi`
**DESKTOP_SESSION**: `ubuntu`
**GTK_MODULES**: `gail:atk-bridge`
**GNOME_SHELL_SESSION_MODE**: `ubuntu`
**LC_MONETARY**: `sv_SE.UTF-8`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**IM_CONFIG_PHASE**: `2`
**LOGNAME**: `masi`
**GTK_IM_MODULE**: `ibus`
**USERNAME**: `masi`
**XDG_SESSION_ID**: `2`
**WINDOWPATH**: `2`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
**LC_ADDRESS**: `sv_SE.UTF-8`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**DISPLAY**: `:0`
**LANG**: `en_US.UTF-8`
**XDG_CURRENT_DESKTOP**: `ubuntu:GNOME`
**LC_TELEPHONE**: `sv_SE.UTF-8`
**XDG_SESSION_DESKTOP**: `ubuntu`
**XMODIFIERS**: `@im=ibus`
**XAUTHORITY**: `/run/user/1000/gdm/Xauthority`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**LC_NAME**: `sv_SE.UTF-8`
**SHELL**: `/bin/bash`
**QT_ACCESSIBILITY**: `1`
**GDMSESSION**: `ubuntu`
**LC_MEASUREMENT**: `sv_SE.UTF-8`
**TEXTDOMAINDIR**: `/usr/share/locale/`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**LC_IDENTIFICATION**: `sv_SE.UTF-8`
**XDG_VTNR**: `2`
**QT_IM_MODULE**: `ibus`
**PWD**: `/home/masi`
**CLUTTER_IM_MODULE**: `xim`
**XDG_DATA_DIRS**: `/usr/share/ubuntu:/home/masi/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-ubuntu:/etc/xdg`
**LC_NUMERIC**: `sv_SE.UTF-8`
**LC_PAPER**: `sv_SE.UTF-8`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**XDG_MENU_PREFIX**: `gnome-`
**SESSION_MANAGER**: `local/masibuntu:@/tmp/.ICE-unix/3030,unix/masibuntu:/tmp/.ICE-unix/3030`
**GIO_LAUNCHED_DESKTOP_FILE**: `/usr/share/applications/PBE.QOwnNotes.desktop`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `20318`
**GJS_DEBUG_OUTPUT**: `stderr`
**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`
</details>

**Comment by pbek** [comment]
Thank you for reporting!

**Comment by pbek** [comment]
This seems to be a regression from the efforts made to be able to manage multiple cloud connections.

**Comment by pbek** [comment]
## 19.10.2
- fixed a crash when opening the settings dialog in the welcome dialog

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
You can test it with `QOwnNotes --clear-settings --session test` without losing any data.

**Comment by Coshibu** [comment]
The problem was fixed for me! Thanks for making such cool software, I have been looking for a note taking app for a while and now settled with QOwnNotes!

**Comment by pbek** [comment]
Great, thank you for testing and for your kind words! :smile:
