### ISSUE TITLE
All settings are reset when the note folder isn't found

### ISSUE THREAD

**Issue by iolivier87** [pbek/QOwnNotes#1307]
### Expected behaviour
Before 19.10.2, when the note folder wasn't found, I clicked on cancel, restored the note folder, and restarted QON. Then, all was good, all my settings where recovered.

#### Actual behaviour
With 19.10.2 / 19.10.3 / 19.10.4, if the note folder isn't found, all my settings are reset, even if I click on cancel when it asks me where the notes are. Then I have to manually import settings, locate the note folder, add my scripts, and custom my toolbar.

#### Steps to reproduce
- Hide the note folder by renaming or moving it. In my case it happens each time I forget to open the vault where my notes are encrypted.
- Start QON and click on cancel
- Restore the note folder
- Restart QON

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue.

**Comment by pbek** [comment]
It's tricky. I needed to remove the settings because I didn't want that the system gets "polluted" when initial setup (that is not initial in your case) is canceled. I'll see what I can do.

**Comment by pbek** [comment]
## 19.10.5
- if you start the application but your **note folder wasn't found** you now are
  able to **select a new note folder**
    - you will not get into the *Welcome dialog* any more where your settings
      will be removed if you cancel it

**Comment by pbek** [comment]
...took a while to make that work

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by iolivier87** [comment]
Yes, it's perfect ! Thank you very much @pbek !

**Comment by pbek** [comment]
Great, thank you for testing!
