### ISSUE TITLE
Latex support?

### ISSUE THREAD

**Issue by F-A** [pbek/QOwnNotes#131]
Is there any plans for supporting latex rendering?

I kow this is not part of the markdown framework but some implementations support it.

**Comment by pbek** [comment]
No, sorry. Currently there are no plans to support Latex. Does this answer your question?

**Comment by F-A** [comment]
Thank you for your answer.

I was considering to move from Laverna to QOwnNotes but Latex support is a prerequisite in my case.

**Comment by pbek** [comment]
Sorry I couldn't help.

**Comment by pbek** [comment]
You now could now convert Latex code to an image with a script, see #499.
