### ISSUE TITLE
Suggestions to integrate 20 Years effort.....

### ISSUE THREAD

**Issue by prog20901** [pbek/QOwnNotes#1310]
background:  Keyman - With over 20 years of development history. Fully Open source - Free - With keyboards for over 1000 languages, Keyman Desktop lets you type in your language even when Windows doesn't.

https://keymanweb.com/ and https://keyman.com/developer/keymanweb/

Integrate Keyboard layout to keyin multi-language characters.

I know many languages other than english..But unfortunately unable to keyin the text of other languages and need additional softwares...Similarly many layman are finding very difficult to enter other language text.....

It would be great if we can integrate the keymen web or keyman desktop to this application to work in the web or desktop via a configuration setting so that it doesn't come up for all

Rememebr it tooks 20 years to develop it....Attached the screenshot...

Whenever multi-lingual option is enabled, we need to enable the keyboard layout near to the search box to keyin

![image](https://user-images.githubusercontent.com/30680308/66798131-b2dcf200-ef2a-11e9-95ac-ecb115a80050.png)

**Comment by pbek** [comment]
> https://keymanweb.com/ and https://keyman.com/developer/keymanweb/

I'm sorry, QOwnNotes is no web application. It's written in C++ / Qt.

**Comment by prog20901** [comment]
However desktop version is also available..https://keyman.com/desktop/  --> Is it possible to have a keyboard layout for atleast major languages such as english, hindi, tamil, etc., in the desktop QT, hope it would be easy since the logic is already in place in script format.

**Comment by pbek** [comment]
> However desktop version is also available..https://keyman.com/desktop/ --> Is it possible to have a keyboard layout for atleast major languages such as english, hindi, tamil, etc.

I'm not sure why a desktop application needs an integrated on screen keyboard. There are plenty of 3rd party solutions that could just "type" into the QPlainTextEdit. What would be the advantage of an integration over a 3rd party app?

And especially why would a Qt app want to integrate non-Qt user interface elements? The UX would suffer a lot.

> in the desktop QT, hope it would be easy since the logic is already in place in script format.

what script format?

**Comment by prog20901** [comment]
English is the primary language throughout the world..We have english in the Windows OS...However we need to have additional softwares to keyin the values for the same...Integration of 3rd party is to keyin or switch multiple languages quickly...We can have different languages files which can be imported...so it would be easy to switch and search..Example a person may know more than 2 languages..so it will be a heavy burden for the user to find out language specific softwares and access the same..Also, the font used in the Qownnotes will not be matching when we type outside...

script - i meant the keymanweb source code already exist for reference.

**Comment by pbek** [comment]
> so it would be easy to switch and search..Example a person may know more than 2 languages..so it will be a heavy burden for the user to find out language specific softwares and access the same..

To my knowledge that all would be possible with an external 3rd party software. E.g. fcitx is able to hook into text editors. Isn't Keyman also able to to something similar?

As far as I can see on https://github.com/keymanapp/keyman/tree/master/linux Keyman also works as 3rd party software, or am I wrong?

> Also, the font used in the Qownnotes will not be matching when we type outside...

there is no font. QOwnNotes is no rich text editor, just plain text

**Comment by pbek** [comment]
I cannot even see a hint on https://github.com/keymanapp/keyman that you can "integrate" Keyman into an other C++ application.

**Comment by Waqar144** [comment]
Why not just use the "keyboard switcher" provided by the OS?

**Comment by prog20901** [comment]
Not all languages are installed in OS by default. Keyboard switcher will work only all the language packages are installed by default. Windows doesn't install all languages by default due to custom option. Laymen users who doesn't have the language packages installed will get into installation issues.

**Comment by pbek** [comment]
I think we can close this issue since Keyman is no library that can be used with Qt apps and it wouldn't make a lot of sense to include it even if it were a library.
