### ISSUE TITLE
Fully Configurable Menus

### ISSUE THREAD

**Issue by prog20901** [pbek/QOwnNotes#1311]
Qownnotes is awesome in speed and features without a question of doubt...It needs a fully configurable menu options...

Reason: Huge menus is not required by many.....For example we just need the import and search option only (example - http://table.branham.org/#/main and https://lwbcast.org/Mobile/)...

By default you can provide all the menus and options to the users..However there should be a way to remove many menus via configuration....

It would be great if the configuration can be exported to xml or some file and can be imported...

So that we can send the configuration to many.....

**Comment by prog20901** [comment]
instead of turning off the entire menu,..may be options can be switched off..

**Comment by pbek** [comment]
> may be options can be switched off..

what options?

And what's the use case?
And do you have examples of popular desktop applications with configurable main menus?

**Comment by prog20901** [comment]
Notepad++ would be the best example.

![image](https://user-images.githubusercontent.com/30680308/66857267-8a91d980-efa4-11e9-84f9-f71247e3faae.png)

**Comment by pbek** [comment]
What do you want me to tell with this screenshot?

**Comment by pbek** [comment]
I cannot find any hint on https://duckduckgo.com/?q=Notepad%2B%2B+configure+main+menu&t=canonical that Notepad++ can configure its main menu.

**Comment by Waqar144** [comment]
> Notepad++ would be the best example.
> 
> [image]

This is just the preferences window of Notepad++. As far as I recall Notepad++ doesn't have configurable menus.

I haven't ever come across any application with configurable menus. It could be implemented with something similar to the Toolbar configuration albeit it'd be rather complex and unnecessary.

Menus are meant for providing options, all of the options available. Making it configurable would kill the purpose of the menu(to provide options). For something simpler, turning off the menu and using the toolbar is the right way in my opinion.

**Comment by pbek** [comment]
> And what's the use case?
> And do you have examples of popular desktop applications with configurable main menus?

**Comment by pbek** [comment]
You seem to misunderstand the scope of your request... It simply would be a tremendous amount of work and then when it's done everything needs to be translated again in all target languages.

**Comment by prog20901** [comment]
i thought the design would be having navigation configuration where all the menus will be designed. whenever it is not required, you can take away a menu...

sorry if i mis-understood the design might have done in that way...

**Comment by pbek** [comment]
Qt uses ui-files where the user interface can be designed. Plus you can do it programmatically. Both ways are used in QOwnNotes. And menus and menu items are often generated, disabled or hidden dynamically.
