### ISSUE TITLE
[I] Images files with jpeg extension not listed in insert dialog

### ISSUE THREAD

**Issue by hallamjeff** [pbek/QOwnNotes#1314]
#### Expected behaviour

Choosing to insert an image, the file open dialog should list all image file types (within reason) or have an option to list all files.

#### Actual behaviour

A file with extension ".jpeg" is not shown in the directory listing provided by the open dialog and the file types appear to filter to only three file extensions. There is no option to display all files.

#### Steps to reproduce

Have an image with ".jpeg" extension. Select insert image button from the toolbar and browse to the directory containing the file. Note that it is not listed.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
No log output was generated when I clicked the "Refresh" button in the Issue assistant.
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed Oct 16 16:35:48 2019`
**Version**: `19.10.5`
**Build date**: `Oct 12 2019`
**Build number**: `596`
**Platform**: `linux`
**Operating System**: `Ubuntu Core 16`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Snapcraft`
**Qt Version (build)**: `5.5.1`
**Qt Version (runtime)**: `5.5.1`
**Portable mode**: `no`
**Settings path / key**: `/home/user/snap/qownnotes/3042/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/user/snap/qownnotes/3042/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/snap/qownnotes/3042/usr/bin/QOwnNotes`, `-style=Fusion`, `--snap`
**Qt Debug**: `0`
**Locale (system)**: `en_CA`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `3`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/user/Documents/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/user/Documents/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `/home/user/Downloads`
**FileDialog/LastPath-InsertImage** (QString): `/home/user/Downloads`
**ImageDialog/disableCopying** (QString): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2019-10-16T16:31:07`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `23`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `DejaVu Sans,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `DejaVu Sans,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 3 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `2`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (bool): `false`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `ee65c734-825e-4f96-94ac-019546e484fa`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `19`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/user/Documents/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**previousWorkspace** (QString): `db667d1d-dc79-4ec2-86d6-0b2836ae62aa`
**restoreCursorPosition** (QString): `true`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-db667d1d-dc79-4ec2-86d6-0b2836ae62aa/name** (QString): `minimal`
**workspace-db667d1d-dc79-4ec2-86d6-0b2836ae62aa/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-db667d1d-dc79-4ec2-86d6-0b2836ae62aa/windowState** (QByteArray): `<binary data>`
**workspace-ee65c734-825e-4f96-94ac-019546e484fa/name** (QString): `full`
**workspace-ee65c734-825e-4f96-94ac-019546e484fa/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-ee65c734-825e-4f96-94ac-019546e484fa/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `ee65c734-825e-4f96-94ac-019546e484fa, db667d1d-dc79-4ec2-86d6-0b2836ae62aa`

## System environment

**XDG_VTNR**: `7`
**MATE_DESKTOP_SESSION_ID**: `this-is-deprecated`
**QT_SELECT**: `snappy-qt5`
**XDG_SESSION_ID**: `c2`
**GST_PLUGIN_SCANNER**: `/snap/qownnotes/3042/usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner`
**XLOCALEDIR**: `/snap/qownnotes/3042/usr/share/X11/locale`
**DBUS_STARTER_ADDRESS**: `unix:path=/run/user/1000/bus,guid=c019e1832d49b58be32537845da50b5e`
**CLUTTER_IM_MODULE**: `xim`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/user`
**XDG_DATA_HOME**: `/home/user/snap/qownnotes/3042/.local/share`
**LIBVA_DRIVERS_PATH**: `/snap/qownnotes/3042/usr/lib/x86_64-linux-gnu/dri`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `31826`
**GDK_PIXBUF_MODULEDIR**: `/snap/qownnotes/3042/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**QTWEBENGINEPROCESS_PATH**: `/snap/qownnotes/3042/usr/lib/x86_64-linux-gnu/qt5/libexec/QtWebEngineProcess`
**QML2_IMPORT_PATH**: `/snap/qownnotes/3042/lib/x86_64-linux-gnu`
**SHELL**: `/bin/bash`
**SNAP_USER_COMMON**: `/home/user/snap/qownnotes/common`
**BAMF_DESKTOP_FILE_HINT**: `/var/lib/snapd/desktop/applications/qownnotes_QOwnNotes.desktop`
**SNAP_CONTEXT**: `cNJ53FGFcYkLWBfQg5wRbJN5YVS1FFnKGmXjw9DTthj9`
**TMPDIR**: `/tmp`
**__EGL_VENDOR_LIBRARY_DIRS**: `/var/lib/snapd/lib/glvnd/egl_vendor.d`
**GIO_MODULE_DIR**: `/home/user/snap/qownnotes/common/.cache/gio-modules`
**GTK_MODULES**: `appmenu-gtk-module:gail:atk-bridge:canberra-gtk-module`
**PULSE_SERVER**: `unix:/run/user/1000/snap.qownnotes/../pulse/native`
**LOCPATH**: `/snap/qownnotes/3042/usr/lib/locale`
**SNAP_REEXEC**: *empty*
**USER**: `user`
**FONTCONFIG_FILE**: `/snap/qownnotes/3042/etc/fonts/fonts.conf`
**GST_PLUGIN_SYSTEM_PATH**: `/snap/qownnotes/3042/usr/lib/x86_64-linux-gnu/gstreamer-1.0`
**LIBGL_DRIVERS_PATH**: `/snap/qownnotes/3042/usr/lib/x86_64-linux-gnu/dri`
**QT_ACCESSIBILITY**: `1`
**INVOCATION_ID**: `6e1a2c669d0b4e05bf67ab46cbcda4bb`
**LD_LIBRARY_PATH**: `/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void::/snap/qownnotes/3042/lib:/snap/qownnotes/3042/usr/lib:/snap/qownnotes/3042/lib/x86_64-linux-gnu:/snap/qownnotes/3042/usr/lib/x86_64-linux-gnu:/snap/qownnotes/3042/usr/lib/x86_64-linux-gnu/mesa:/snap/qownnotes/3042/usr/lib/x86_64-linux-gnu/mesa-egl:/snap/qownnotes/3042/usr/lib/x86_64-linux-gnu/mesa:/snap/qownnotes/3042/usr/lib/x86_64-linux-gnu/mesa-egl:/snap/qownnotes/3042/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**SNAP_LIBRARY_PATH**: `/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void`
**SESSION_MANAGER**: `local/desktop:@/tmp/.ICE-unix/3033,unix/desktop:/tmp/.ICE-unix/3033`
**SNAP_INSTANCE_NAME**: `qownnotes`
**DEFAULTS_PATH**: `/usr/share/gconf/mate.default.path`
**SNAP_COMMON**: `/var/snap/qownnotes/common`
**SNAP_USER_DATA**: `/home/user/snap/qownnotes/3042`
**GIO_LAUNCHED_DESKTOP_FILE**: `/var/lib/snapd/desktop/applications/qownnotes_QOwnNotes.desktop`
**XDG_CONFIG_DIRS**: `/snap/qownnotes/3042/etc/xdg:/etc/xdg/xdg-mate:/etc/xdg`
**SNAP_DATA**: `/var/snap/qownnotes/3042`
**FONTCONFIG_PATH**: `/snap/qownnotes/3042/etc/fonts`
**PATH**: `/snap/qownnotes/3042/usr/lib/x86_64-linux-gnu/qt5/bin:/snap/qownnotes/3042/usr/sbin:/snap/qownnotes/3042/usr/bin:/snap/qownnotes/3042/sbin:/snap/qownnotes/3042/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`
**DESKTOP_SESSION**: `mate`
**QTCHOOSER_NO_GLOBAL_DIR**: `1`
**QT_IM_MODULE**: `ibus`
**QT_QPA_PLATFORMTHEME**: `gtk2`
**TEMPDIR**: `/tmp`
**GDK_PIXBUF_MODULE_FILE**: `/home/user/snap/qownnotes/common/.cache/gdk-pixbuf-loaders.cache`
**PWD**: `/home/user`
**XDG_SESSION_TYPE**: `x11`
**XMODIFIERS**: `@im=ibus`
**XKB_CONFIG_ROOT**: `/snap/qownnotes/3042/usr/share/X11/xkb`
**LANG**: `en_CA.UTF-8`
**GDM_LANG**: `en_CA`
**MANDATORY_PATH**: `/usr/share/gconf/mate.mandatory.path`
**IM_CONFIG_PHASE**: `2`
**UBUNTU_MENUPROXY**: `1`
**COMPIZ_CONFIG_PROFILE**: `mate`
**QT_QPA_PLATFORM**: `xcb`
**XCURSOR_PATH**: `/snap/qownnotes/3042/usr/share/icons`
**GDMSESSION**: `mate`
**GPG_TTY**: `not a tty`
**SNAP_REVISION**: `3042`
**DBUS_STARTER_BUS_TYPE**: `session`
**HOME**: `/home/user/snap/qownnotes/3042`
**SHLVL**: `0`
**XDG_SEAT**: `seat0`
**XDG_CONFIG_HOME**: `/home/user/snap/qownnotes/3042/.config`
**SNAP_NAME**: `qownnotes`
**LANGUAGE**: `en_CA:en`
**DISABLE_WAYLAND**: `1`
**QT_PRINTER_MODULE**: `qtubuntu-print`
**QTCOMPOSE**: `/snap/qownnotes/3042/usr/share/X11/locale`
**SNAP_COOKIE**: `cNJ53FGFcYkLWBfQg5wRbJN5YVS1FFnKGmXjw9DTthj9`
**GTK_OVERLAY_SCROLLING**: `0`
**GTK_PATH**: `/snap/qownnotes/3042/usr/lib/x86_64-linux-gnu/gtk-2.0`
**XDG_CACHE_HOME**: `/home/user/snap/qownnotes/common/.cache`
**XDG_SESSION_DESKTOP**: `mate`
**LOGNAME**: `user`
**XDG_DATA_DIRS**: `/home/user/snap/qownnotes/3042/.local/share:/home/user/snap/qownnotes/3042:/snap/qownnotes/3042/usr/share:/usr/share/mate:/usr/local/share:/usr/share:/var/lib/snapd/desktop`
**GSM_SKIP_SSH_AGENT_WORKAROUND**: `true`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus,guid=c019e1832d49b58be32537845da50b5e`
**QT4_IM_MODULE**: `xim`
**GST_PLUGIN_PATH**: `/snap/qownnotes/3042/usr/lib/x86_64-linux-gnu/gstreamer-1.0`
**QT_SCALE_FACTOR**: `1`
**SNAP_ARCH**: `amd64`
**JOURNAL_STREAM**: `9:42052`
**MANAGERPID**: `3014`
**SNAP_VERSION**: `19.10.5`
**TEXTDOMAIN**: `im-config`
**DISPLAY**: `:0`
**XDG_RUNTIME_DIR**: `/run/user/1000/snap.qownnotes`
**QT_PLUGIN_PATH**: `/snap/qownnotes/3042/usr/lib/x86_64-linux-gnu/qt5/plugins`
**SNAP_LAUNCHER_ARCH_TRIPLET**: `x86_64-linux-gnu`
**SNAP**: `/snap/qownnotes/3042`
**XDG_CURRENT_DESKTOP**: `MATE`
**GTK_IM_MODULE**: `xim`
**TEXTDOMAINDIR**: `/usr/share/locale/`
**SNAP_INSTANCE_KEY**: *empty*
**XAUTHORITY**: `/home/user/.Xauthority`
</details>

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
## 19.10.7
- now **all supported image formats** can be **selected with the file picker** of the **Image dialog**
    - in addition you can now also choose `Any file` in the file picker

**Comment by hallamjeff** [comment]
Yes, it works great now. Nice one.

**Comment by pbek** [comment]
Great, thank you for testing!
