### ISSUE TITLE
Nextcloud/ownCloud-Serverfehler: Falscher Pfad, Datei/Ordner existiert nicht

### ISSUE THREAD

**Issue by Kallle98** [pbek/QOwnNotes#1316]
Nach Start von QOwnNotes 19.10.6 sagt der Verbindungsstatus (Einstellungen > Nextcloud/owncloud), dass alle 7 Bedingungen "ok" sind. "Verbindung wurde erfolgreich hergestellt. Server-Version: 16.0.5.1, QOwnNotesAPI-Version: 19.9.0".
Aber sobald ich eine Notiz "teilen" will, kommt der Fehler: "Nextcloud/ownCloud-Serverfehler: Falscher Pfad, Datei/Ordner existiert nicht. Bitte überprüfen Sie Ihre Server_Einstellungen."
Dann öffne ich die Einstellungen und erhalte wieder die Mitteilung, dass alle 7 Bedingungen "ok" sind. (siehe oben). 
In QOwnNotes.log erscheint die Meldung:
"[Okt 17 11:31:38] [warning]: "QNetworkReply error 203 from url https://cloud.xxxxxx.de/ocs/v2.php/apps/files_sharing/api/v1/shares: " "Error transferring https://cloud.xxxxxx.de/ocs/v2.php/apps/files_sharing/api/v1/shares - server replied: Not Found""

Ja, richtig. Im Nextcloud-Verzeichnis **apps/files_sharing** gibt es kein Unterverzeichnis namens **api**.
Was muss ich tun, um es da hineinzubekommen? Die Apps "File Sharing" 1.8.0 und "Share Path" 0.0.1 sind aktiv? Was fehlt jetzt noch?

Viele Grüße, Kallle98
![Bild 001](https://user-images.githubusercontent.com/56676092/66998635-e0659f00-f0d4-11e9-95dc-61c2cf540812.png)
![Bild-002x](https://user-images.githubusercontent.com/56676092/66998636-e0659f00-f0d4-11e9-8bcc-06fa7b7cc9e0.png)
![Bild-003x](https://user-images.githubusercontent.com/56676092/66998637-e0fe3580-f0d4-11e9-897e-f0f65253c651.png)

**Comment by pbek** [comment]
Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging.

Are you using ownCloud or Nextcloud?

**Comment by pbek** [comment]
Does sharing files work if you are using the Nextcloud files app?

**Comment by Kallle98** [comment]
> Does sharing files work if you are using the Nextcloud files app?

Yes, without problems!
Also, the Nextcloud Sync client, which synchronizes all folders with the corresponding local folders, works flawlessly.

**Comment by pbek** [comment]
I cannot help you a lot since you haven't posted any information about your system and what happens in your QOwnNotes instance...

**Comment by pbek** [comment]
> Yes, without problems!

If you enable the development tools in your browser while visiting your Nextcloud files application and then share a file you could post the content of the *Network* tab to let me see what requests are made in your Nextcloud instance while sharing files. QOwnNotes uses the same...

**Comment by Kallle98** [comment]
Here the log:
[Okt 17 11:31:25] [debug]: Set proxy configuration to use NO proxy
[Okt 17 11:31:26] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[Okt 17 11:31:27] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://cloud.psychodynamisches-institut.de" <username>"PinCloud" <priority>1
[Okt 17 11:31:27] [debug]: loadNoteDirectoryList
[Okt 17 11:31:28] [debug]: reloadTagTree
[Okt 17 11:31:28] [debug]: reloadTagTree  - 'noteSubFolderIds':  (-1)
[Okt 17 11:31:28] [debug]: reloadNoteSubFolderTree
[Okt 17 11:31:28] [debug]: reloadTagTree
[Okt 17 11:31:28] [debug]: reloadTagTree  - 'noteSubFolderIds':  (-1)
[Okt 17 11:31:28] [debug]: loadNoteDirectoryList
[Okt 17 11:31:28] [debug]: reloadTagTree
[Okt 17 11:31:28] [debug]: reloadTagTree  - 'noteSubFolderIds':  (-1)
[Okt 17 11:31:28] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://cloud.psychodynamisches-institut.de" <username>"PinCloud" <priority>1
[Okt 17 11:31:28] [debug]: reloadTagTree
[Okt 17 11:31:28] [debug]: reloadTagTree  - 'noteSubFolderIds':  (-1)
[Okt 17 11:31:35] [debug]: updateDialog  - 'note':  Note: <id>1 <name>"Note 2019-10-16T17.35.42" <fileName>"Note 2019-10-16T17.35.42.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false
[Okt 17 11:31:38] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://cloud.psychodynamisches-institut.de" <username>"PinCloud" <priority>1
[Okt 17 11:31:38] [debug]: shareNote  - 'note':  Note: <id>1 <name>"Note 2019-10-16T17.35.42" <fileName>"Note 2019-10-16T17.35.42.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false
[Okt 17 11:31:38] [debug]: shareNote  - 'url':  QUrl("https://cloud.psychodynamisches-institut.de/ocs/v2.php/apps/files_sharing/api/v1/shares")
[Okt 17 11:31:38] [debug]: shareNote  - 'postData':  "shareType=3&path=%2FNotes%2FNote%202019-10-16T17.35.42.md"
[Okt 17 11:31:38] [debug]: Reply from  "/ocs/v2.php/apps/files_sharing/api/v1/shares"
**[Okt 17 11:31:38] [warning]: "QNetworkReply error 203 from url https://cloud.psychodynamisches-institut.de/ocs/v2.php/apps/files_sharing/api/v1/shares: " "Error transferring https://cloud.psychodynamisches-institut.de/ocs/v2.php/apps/files_sharing/api/v1/shares - server replied: Not Found"**
[Okt 17 11:31:38] [debug]: Reply from share api
[Okt 17 11:31:38] [debug]: updateNoteShareStatusFromShare  - 'status':  "failure\n"
[Okt 17 11:31:40] [debug]: Set proxy configuration to use NO proxy
[Okt 17 11:31:40] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://cloud.xxxxxx-institut.de" <username>"xxxxxx" <priority>1
[Okt 17 11:31:40] [debug]: Set proxy configuration to use NO proxy
[Okt 17 11:31:41] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://cloud.xxxxxx-institut.de" <username>"xxxxxx" <priority>1
[Okt 17 11:31:41] [debug]: Reply from  ""
[Okt 17 11:31:41] [debug]: Reply from main server url
[Okt 17 11:31:41] [debug]: Reply from  "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[Okt 17 11:31:41] [debug]: Reply from app info
[Okt 17 11:31:41] [debug]: Reply from  ""
[Okt 17 11:31:41] [debug]: Reply from main server url
[Okt 17 11:31:41] [debug]: Reply from  "/ocs/v1.php/cloud/capabilities"
[Okt 17 11:31:41] [debug]: Reply from capabilities page
[Okt 17 11:31:41] [debug]: Reply from  "/ocs/v1.php"
[Okt 17 11:31:41] [debug]: Reply from ownCloud test page
[Okt 17 11:31:41] [debug]: Reply from  "/ocs/v1.php/cloud/capabilities"
[Okt 17 11:31:41] [debug]: Reply from capabilities page
[Okt 17 11:31:41] [debug]: Reply from  "/ocs/v1.php"
[Okt 17 11:31:41] [debug]: Reply from ownCloud test page
[Okt 17 11:31:41] [debug]: Reply from  "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[Okt 17 11:31:41] [debug]: Reply from app info
*******************************

**The problem is obviously the Nextcloud server! Not on the local PC** There is no subdirectory named api in the Nextcloud apps / files_sharing directory.
Who or what is responsible for making it appear there?

What do I have to do to get it there? The apps "File Sharing" 1.8.0 and "Share Path" 0.0.1 are active? What is missing now?

And one question: Does QOwnnotes somehow work with the Dropbox process dbxsvc?
If not, I will remove the same on my PC.

**Comment by Kallle98** [comment]
I am not good at English and do everything about Google Translator. That's why I need a long time for reactions.

**Comment by pbek** [comment]
> The problem is obviously the Nextcloud server! Not on the local PC There is no subdirectory named api in the Nextcloud apps / files_sharing directory.

why should there? <https://github.com/nextcloud/server/blob/master/ocs/v2.php> is handling those calls

> The apps "File Sharing" 1.8.0 and "Share Path" 0.0.1 are active? 

How should I know? :)

<https://cloud.psychodynamisches-institut.de/ocs/v2.php/apps/files_sharing/api/v1/shares> seems to throw an error.

> What is missing now?

I don't know yet, I cannot even reach <https://cloud.psychodynamisches-institut.de/>. I also use Nextcloud 16.0.5 and never had any issue.

If you enable the development tools in your browser while visiting your Nextcloud files application and then share a file you could post the content of the Network tab to let me see what requests are made in your Nextcloud instance while sharing files. QOwnNotes uses the same...

**Comment by pbek** [comment]
> And one question: Does QOwnnotes somehow work with the Dropbox process dbxsvc?

no, it doesn't

> I am not good at English and do everything about Google Translator. That's why I need a long time for reactions.

It would be better to use English, since most of the users don't speak German. But if you must you can post in German, but you possibly will get less help that way. :)

**Comment by Kallle98** [comment]
It is a **closed** internal cloud that is already **productive**. 
Is it actually ensured that everything I share here remains PRIVATE?

Is this network protocol helpful?

[networkanalysis_Archive [19-10-17 13-29-00].zip](https://github.com/pbek/QOwnNotes/files/3738993/networkanalysis_Archive.19-10-17.13-29-00.zip)

Maybe Qowncloud was an attempt that overwhelmed me.

**Comment by pbek** [comment]
> It is a **closed** internal cloud that is already **productive**.
> Is it actually ensured that everything I share here remains PRIVATE?

no, the information here is public, this is a free open source project 

> 
> Is this network protocol helpful?
> 
> [networkanalysis_Archive [19-10-17 13-29-00].zip](https://github.com/pbek/QOwnNotes/files/3738993/networkanalysis_Archive.19-10-17.13-29-00.zip)

yet it is (just the urls that were loaded would have been enough).
it is showing that also <https://cloud.psychodynamisches-institut.de/ocs/v2.php/apps/files_sharing/api/v1/shares> was used, but in your log there was a `**[Okt 17 11:31:38] [warning]: "QNetworkReply error 203 from url https://cloud.psychodynamisches-institut.de/ocs/v2.php/apps/files_sharing/api/v1/shares: " "Error transferring https://cloud.psychodynamisches-institut.de/ocs/v2.php/apps/files_sharing/api/v1/shares - server replied: Not Found"**`, so something is blocking or rejecting your requests. Maybe a firewall?

> 
> Maybe Qowncloud was an attempt that overwhelmed me.

I think I don't understand the meaning of this sentence. :)

**Comment by Kallle98** [comment]
The firewall on my local PC explicitly allows inbound and outbound traffic from QownNotes.
The Nextcloud installation does not have its own webfirewall (at least I have none installed).

I think some app would have had to install the api / v1 / shares under Nextcloud / apps / files_sharing. That did not happen.

*******************
> I do not think I understand the meaning of this sentence. :)

Yes, Google Translator also has its problems. He should not translate "overwhelmed" but "**overtaxed**".

By that I mean that I lack both a deeper understanding of programming and deeper English skills. I build websites and administer them. I can do a bit of php, html and css (with a lot of help from the internet). This cloud is my first. And this request on Github too.

Apparently other laws apply here than in the support forums of individual developers i.e. Joomla and its extensions. Since I've come so far (thanks to Google translator) always cope.
But here and now I have the feeling of being overstrained/overtaxed - among experts, for whom a lot is self-evident, whose meaning I first have to research cumbersomely.

For "self-protection", I will follow my previous "survival strategy" and reset the current attempt with QownNotes. Maybe the problem has - where it is - done in 1 or 2 years. And then I start a new  attempt.

Many thanks for the help so far!

**Comment by pbek** [comment]
> I think some app would have had to install the api / v1 / shares under Nextcloud / apps / files_sharing. That did not happen.

It already seems to work fine in your browser.

> This cloud is my first. And this request on Github too.

Isn't that exciting? :smile_cat: 

> Apparently other laws apply here than in the support forums of individual developers i.e. Joomla and its extensions. 

Which laws do you think would apply? You are posting in an open GitHub issue tracker.

> Maybe the problem has - where it is - done in 1 or 2 years. And then I start a new attempt.

:laughing:

**Comment by Kallle98** [comment]
> Isn't that exciting? 😸
Yes, it is. And there are also people who regard excitement as something good and desirable. But since childhood I am a vegetative over-excitable sympathico-tonic. I basically avoid excitement. And earlier (as an employee) I took tons of diazepam to handle it.

> Which laws do you think would apply? You are posting in an open GitHub issue tracker.
Maybe on "normal support forums" or ticket systems it is less demanding, so that my simple skills are sufficient there.
But it may also have to do something with the fact that the developers are interested in keeping their **paying** customers and therefore downgrading to the level of these customers, who are mostly not programmers.

The latter, I could imagine, because I too act so that I keep my customers. Ie. I try to understand what my opponent knows and then go into his abilities. Also, I can usually explain technical issues in understandable language - as long as I understand them myself.
