### ISSUE TITLE
Enhancement: Mermaid

### ISSUE THREAD

**Issue by mtompkins** [pbek/QOwnNotes#132]
Great app. Love the owncloud integration.
Please consider adding [Mermaid](https://github.com/knsv/mermaid) to your solution for some out-of-the-box diagramming.

Cheers

**Comment by pbek** [comment]
Thank you for your kind words!

The library from the link you sent me only works in the web. Is there something that works on the desktop (C++ Qt) too?

**Comment by mtompkins** [comment]
I was hoping you might be able to integrate the `cli` component from that source. I also wasn't sure if your markdown rendering engine might support `.js`. I guess with such standards like highlight.js not integrated I should have concluded that wasn't the case.

Here is the link to the webpage with more integration information if you haven't had a look. http://knsv.github.io/mermaid/

I'm not sure if the cli or API is an option for you.

**Comment by pbek** [comment]
Mermaid relies on Javascript (also uses the D3 library). The "markdown to html" converter QOwnNotes uses just converts markdown to simple html. QOwnNotes doesn't need a Webkit browser to view that.

**Comment by pbek** [comment]
I'm not sure what the CLI version does or needs (I guess node,js)... We can't depend on that everyone has it installed.

**Comment by mtompkins** [comment]
The following Github project [CuteMarkEd](https://github.com/cloose/CuteMarkEd) is a QT / C++ app that makes use of `mermaid` If you find the motivation, perhaps you can have a look at the source to see how it is using the component.

HTH

**Comment by pbek** [comment]
Thank you for the reference. As I can see they are not using any highlighting in the editor, but the generator in a (I guess full-WebKit) browser widget. That's an option but will increase the packages for Windows and OS X dramatically. If QOwnNotes will get a full browser built inside in the future I will consider Mermaid integration.

**Comment by pbek** [comment]
I will close this issue until there is a full blown browser as preview in QOwnNotes.

**Comment by SeriousM** [comment]
> I will close this issue until there is a full blown browser as preview in QOwnNotes.

Is that now the case?

**Comment by pbek** [comment]
> Is that now the case?

no, it isn't

**Comment by e-alfred** [comment]
it would be awesome to have Mermaid.js support now that the Nextcloud Markdown editor supports it:

https://github.com/icewind1991/files_markdown#create-graph-using-mermaidjs

**Comment by Simarion** [comment]
> it would be awesome to have Mermaid.js support now that the Nextcloud Markdown editor supports 

Hi, as though I'd love to see a support for mermaid as well, I don't think it works that way. If I understand pbek correctly, markdown is just converted to html. 

Mermaid needs a (webkit) browser to render the html and that's not 'on board'. Although: it looks like the webkid widget is on the roadmap...

BTW thx for the worderful work pbek!

**Comment by pbek** [comment]
@Simarion thank you for your kind words and yes, a fully fledged browser is needed.

**Comment by pbek** [comment]
Maybe you want to look for `mermaid` in the script repository, added by https://github.com/qownnotes/scripts/pull/135.
