### ISSUE TITLE
Feature request: hotkey to activate/iconify to/from tray

### ISSUE THREAD

**Issue by uffejakobsen** [pbek/QOwnNotes#1324]
Feature request: hotkey to activate/iconify to/from tray

Thanks for a truly great noteapp !!! :-)

It would be nice it QOwnNotes had a configurable hotkey that would activate/iconify QOwnNotes to from the tray

Thanks :-)

**Comment by pbek** [comment]
Thank you for your kind words.

I guess we are talking about #44 or #1241, right? Can you please head over to those issues.

**Comment by pbek** [comment]
You may want to test https://github.com/pbek/QOwnNotes/issues/44, @uffejakobsen

**Comment by uffejakobsen** [comment]
Thanks for the heads up - but that was not really what I was asking for - but it is a good start :-)

I was requesting a global hotkey that would unhide/hide the whole application and noting more :-)

**Comment by pbek** [comment]
> I was requesting a global hotkey that would unhide/hide the whole application and noting more :-)

I guess we needed global shortcut support first, right? :grin:

**Comment by uffejakobsen** [comment]
> I guess we needed global shortcut support first, right? grin
Yes, I guess that would be the easiest way to make it work :grin:

**Comment by pbek** [comment]
## 20.4.0
- you now can **show and hide the application window** with a new action `Show/Hide application`
  in the *Window / Show* menu
    - this should work with and without enabled tray icon
    - assign a global keyboard shortcut to the action in the *Shortcuts settings*
      to make use of it properly

@teamayu, @uffejakobsen

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by uffejakobsen** [comment]
I can confirm it works here (apart from the meta key (which I can see is tracked in a separate issue)

Thanks a lot :-) :+1:

**Comment by pbek** [comment]
Great, thank you for testing! :grin:
