### ISSUE TITLE
scripting feature: pre markdown converter hook

### ISSUE THREAD

**Issue by bessw** [pbek/QOwnNotes#1328]
A hook to be able to modify what is passed to the markdown to html converter could be useful.

I think about something like:
```js
/**
 * This function is called before the markdown html of a note is generated
 *
 * It allows you to modify what is passed to the markdown to html converter.
 *
 * The method can for example be used in multiple scripts to render code (like LaTeX math or mermaid) to its grafical representation for the preview.
 *
 * (the modification will only be applyed to the view, but not saved to the actual markdown note file)
 *
 * @param {NoteApi} note - the note object
 * @return {string} the modified note that should be passed to the md2html converter or an empty string if nothing should be modified
 */
function preNoteToMarkdownHtmlHook(note);
```

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
## 19.10.11
- there now is a **new scripting hook** `preNoteToMarkdownHtmlHook(note, markdown)`
  that is **called before the markdown html of a note is generated**
    - it allows you to modify the markdown before it is converted to html
    - it can for example be used in multiple scripts to render code (like LaTeX math or mermaid)
      to its graphical representation for the preview
    - there is an example call in
      [preview-styling.qml](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/preview-styling.qml)
  - for more information please take a look at the
    [scripting documentation](https://docs.qownnotes.org/en/develop/scripting/README.html#preNoteToMarkdownHtmlHook)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by r00tr4v3n** [comment]
@bessw Any update on the script? 
@pbek Why should I prefer the markdown hook for an (Latex) image instead of the more powerful html with the corresponding hook?

**Comment by pbek** [comment]
@r00tr4v3n can you please elaborate on your question.

**Comment by r00tr4v3n** [comment]
You mention LaTeX math and mermaid explicitly in the docs of `preNoteToMarkdownHtmlHook`.
But it only allows changes in the markdown file like replacing a `$x^2$` to `![img](path)`. Why shouldn't be the `noteToMarkdownHtmlHook` preferred where I can inject a 
`<img src="http://latex-gen.org/x^2">` for the equation?

**Comment by bessw** [comment]
I think I was tinkering on two scripts where I tried to use it mainly to get better performance on big notes with LaTeX math:
- In the first one I was trying to generate LaTeX equations and mermaid graphs asynchronously and injecting them later in the `noteToMarkdownHtmlHook`
- And the second one was the markdown-it processor script where I tried speeding up preview generation by not running it after the internal one and thus generating the html twice (generating the html from the `preNoteToMarkdownHtmlHook` returning an empty string and inserting the md-it html later in the `noteToMarkdownHtmlHook`.

But after some time I got frustrated by Qt's javascript engine not supporting any library I wanted to use and the preview not supporting any advanced html and thus the need to modify libraries I wanted to use and the need to generate images and saving them in tmp files to display anything except text.

In the end I turned to Electron / cordova, chained some libraries together that are around on the web and got an editor with LaTeX and mermaid working in no time compared to my tries to get this in QOwnNotes using the scripting engine.
(since this is a huge project its vary WIP and many features that QOwnNotes has aren't jet or anywhere soon implemented)

**Comment by r00tr4v3n** [comment]
> In the end I turned to Electron / cordova, chained some libraries together that are around on the web and got an editor with LaTeX and mermaid working in no time compared to my tries to get this in QOwnNotes using the scripting engine.
> (since this is a huge project its vary WIP and many features that QOwnNotes has aren't jet or anywhere soon implemented)

So you build your own Electron based notes app with LaTex support?

**Comment by bessw** [comment]
I'm trying, but it's a long way.
