### ISSUE TITLE
Better utilize Tag view window/frame

### ISSUE THREAD

**Issue by Airgunster** [pbek/QOwnNotes#1333]
This is a feature request, which would be very nice to implement (as it will increase productivity working with Tags).

#### Expected behaviour
Show all Tags in Tag view window/frame as a list (instead of one line), decrease font size (or make it configurable) for Tags in Tag view window/frame.

#### Actual behaviour
All Tags are listed in Tag view window/frame as one line, i.e. if you have a 2-5 Tags, then you have one looong line.

Here is how it is now,
<img width="1495" alt="Screenshot 2019-10-28 at 20 09 42" src="https://user-images.githubusercontent.com/7937957/67714452-d3438c80-f9bf-11e9-9f11-f706a4d2d058.png">

#### Steps to reproduce
* Create Tag `A`;
* Create sub-tag `A > test tag with some words one`;
* Create sub-tag `A > test tag with some words two`;
* Observe tags listed as one line in Tag view window/frame;

**Comment by pbek** [comment]
This panel wasn't meant to be used that way. Why don't you just solely use the tag tree for managing your tags? You can also see which note is tagged there and tag notes by just double-clicking on the tag.

> or make it configurable

there is a script `Custom user interface styling` in the script repository ;)

**Comment by pbek** [comment]
btw. you can also move the panel below the note list to gain more horizontal space

**Comment by Airgunster** [comment]
@pbek, Thanks,
> This panel wasn't meant to be used that way.
I actually thought that this panel was created to show existing tags on a Note.

> Why don't you just solely use the tag tree for managing your tags? You can also see which note is tagged there and tag notes by just double-clicking on the tag.
Yep, I use Tags panel to assign Tags by double-clicking (thanks for this hint btw, you've shared it some time ago already), however I can't use Tag panel to view the tags quickly as I have a lot of Tags, so I need to scroll a lot and there's a possibility that I can miss some Tags due to speed scrolling.

> there is a script Custom user interface styling in the script repository ;)
Nice, was not really aware of it, will have a look.

> btw. you can also move the panel below the note list to gain more horizontal space
Any ideas how I can do that? Ideally I'd like to have it at the bottom of the window (under notes list and note itself). Probably via `Custom user interface styling`?

Thanks a lot in advance!

**Comment by pbek** [comment]
> I actually thought that this panel was created to show existing tags on a Note.

yes, it shows the tags horizontally in a scroll area

> Any ideas how I can do that? Ideally I'd like to have it at the bottom of the window (under notes list and note itself)

button in the center unlocks the panels

![image](https://user-images.githubusercontent.com/1798101/67765252-f451bf00-fa4b-11e9-86ac-877ef0ead3ba.png)

then you can drag them around, create different workspaces if you want to switch between different layouts

**Comment by Airgunster** [comment]
@pbek, I wasn't aware of that functionality either. Wow, how much I like QOwnNotes, such a powerful tool, thanks a lot!

**Comment by pbek** [comment]
In the settings there is also an area for "layouts" where I preset some common panel configurations...

One day I will create a "Did you know that..." dialog at startup (that everyone will dismiss immediately) for all those things. :laughing:
