### ISSUE TITLE
Directory of different instances changes when a note of one instance is edited

### ISSUE THREAD

**Issue by maqp** [pbek/QOwnNotes#1336]
Version affected: 19.10.11 (possibly others)
Platform: Ubuntu 19.10

Pre-conditions: Allow multiple instances in QOwnnotes setting must be enabled

Steps to reproduce:

1. Open QOwnNotes
2. Select a subdirectory and a note
3. Open one or more new instances of QOwnnotes
4. Navigate new instances to different subdirectories (in this test, I used siblings of the first instance)
5. Edit the titles of the notes
7. Press Ctrl + S or wait for the note to be saved
8. Subdirectories of other instances changes

This is problematic because the main purpose of multiple instances (at least for me) is to have different subdirectories open for each instance.

**Comment by pbek** [comment]
If you start QOwnNotes multiple times (and don't disallow that behavior in the settings) the same settings will be shared.

The only way to really get different sessions is with the `--session` parameter. See: http://docs.qownnotes.org/en/develop/cli-parameters.html

**Comment by maqp** [comment]
Ah I see!  :smile: Thank you!
