### ISSUE TITLE
Unable to start QOwnNotes from cmd on windows 7

### ISSUE THREAD

**Issue by giovi321** [pbek/QOwnNotes#134]
I tried to start QOwnNotes from the command line on windows 7 but I get the following error:
"The application failed to start because it could not find or load the Qt platform plugin "windows".
Resinstalling the application may fix this problem."

**Comment by pbek** [comment]
All the necessary DLL-files should be included in the ZIP archive.

Which version of QOwnNotes did you download? Did you extract all files from the ZIP archive to a directory? Could you please post a screenshot of how your your QOwnCloud folder looks like.

**Comment by pbek** [comment]
And a very important question: Did you enter the directory where you extracted the ZIP archive before you started QOwnNotes? Because QOwnNotes needs the Qt libraries there, you have to set the working directory to the directory where the exe resides.

**Comment by pbek** [comment]
I reproduced your problem on Windows 7. The solution: above comment of me
Does this work for you?

**Comment by giovi321** [comment]
Thanks, fixed. Either you use a shortcut or the following batch:

`cd C:\path\to\qownnotes`
`start qownnotes.exe`

**Comment by pbek** [comment]
Great that it now worked!
