### ISSUE TITLE
[F] Open 'Minimized to tray"

### ISSUE THREAD

**Issue by truthsword** [pbek/QOwnNotes#1341]
l#### Expected behaviour

QON shortcut on Desktop. Properties set to Run Minimized
![](https://i.imgur.com/SnNKD3e.png)
Double-click shortcut... opens "minimized" (to tray).

#### Actual behaviour

When shortcut is launched, QON opens maximized (present in tray).

#### Steps to reproduce

Create shortcut
Set shortcut properties to "Run Minimized"
Save shortcut
Double-click shortcut/

Overall my object is to have QON launch silently to tray on login (shortcut located in Startup folder).

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed Oct 30 13:27:29 2019`
**Version**: `19.10.12`
**Build date**: `Oct 29 2019`
**Build number**: `4714`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.13.0`
**Qt Version (runtime)**: `5.13.0`
**Portable mode**: `no`
</details>

ready in your clipboard.

**Comment by pbek** [comment]
There is an option for starting the application hidden in the *Interface settings*, if that is what you asking for...

**Comment by pbek** [comment]
Does that also happen if you start a new session with `QOwnNotes.exe --session test`?

**Comment by truthsword** [comment]
> Does that also happen if you start a new session with `QOwnNotes.exe --session test`?

That wants to create a new folder for my Notes... Not sure I can find my way back to my current setup, so I canceled out.

**Comment by pbek** [comment]
It's a completely different settings session. No harm will be done to your main session.

**Comment by truthsword** [comment]
OK... When I launch that, having quit from a maximized window, I get a very brief full window flash, and then only the tray icon appears.

**Comment by pbek** [comment]
So it seems it's a setting in your main session.

**Comment by truthsword** [comment]
> So it seems it's a setting in your main session.

Well... that was painful, but I found it... a script (I only had one)... import_tags.qml. When I removed it, my default setup went to the tray on start (with the momentary window flash). Then I added the script to the "clean" test shortcut, and it now opened to a window.

**Comment by pbek** [comment]
I wonder what in the script does that. 😆

**Comment by truthsword** [comment]
Ha. I'll leave that to you. This isn't a script I often use, so I'll leave it unchecked 😁

Thanks for helping me locate the issue.

**Comment by pbek** [comment]
Great! 😄
