### ISSUE TITLE
[F] Make spell checking work on snap version

### ISSUE THREAD

**Issue by tonyarnold99** [pbek/QOwnNotes#1348]
#### Expected behaviour

Spell checking has been recently added to QOwnNotes, however, this is not working on the snap version. I would expect that when spell checking is enabled, that misspelt words are highlighted.

#### Actual behaviour

When starting QOwnNotes from command line, several warnings are issued saying cannot find dictionaries:

```
Warning: "Object path cannot be empty" ((null):0, (null))
Warning: No language dictionaries for the language: "en_GB" ((null):0, (null))
Warning: No language dictionaries for the language: "en_GB" ((null):0, (null))
Warning: No language dictionaries for the language: "en_GB" ((null):0, (null))
Warning: No language dictionaries for the language: "en_GB" ((null):0, (null))
Warning: No language dictionaries for the language: "en_GB" ((null):0, (null))
Warning: No language dictionaries for the language: "en_GB" ((null):0, (null))
Warning: No language dictionaries for the language: "en_GB" ((null):0, (null))
/usr/share/libdrm/amdgpu.ids: No such file or directory
Info: "QOwnNotes server listening on port 22222" ((null):0, (null))
```

and no spell checking is performed.

#### Steps to reproduce

On Ubuntu 19.10
Install QOwnNotes snap (`snap install qownnotes`)
Install hunspell-en-gb package (`sudo apt install hunspell-en-gb`)
Copy all files from `/usr/share/hunspell/*` to `~/.local/share/hunspell` as advised in issue #125
Run from command line
Note warnings
In app make sure spell checking is enabled
Note lack of high lighting of misspelt words

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fri Nov 1 12:32:28 2019`
**Version**: `19.11.1`
**Build date**: `Nov  1 2019`
**Build number**: `606`
**Platform**: `linux`
**Operating System**: `Ubuntu Core 16`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Snapcraft`
**Qt Version (build)**: `5.5.1`
**Qt Version (runtime)**: `5.5.1`
**Portable mode**: `no`
**Settings path / key**: `/home/tony/snap/qownnotes/3207/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/tony/snap/qownnotes/3207/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/snap/qownnotes/3207/usr/bin/QOwnNotes`, `-style=Fusion`, `--snap`
**Qt Debug**: `0`
**Locale (system)**: `en_GB`
**Locale (interface)**: *empty*
**Icon theme**: `Adwaita`
**Notes in current note folder**: `186`
**Calendar items**: `4`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://tonyarnold.owncube.com`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `15.0.5.3`
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-2`
**localPath**: `/home/tony/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/tony/Nextcloud/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://tonyarnold.owncube.com`
**username**: `me`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2019-11-01T12:13:14`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `DejaVu Sans,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `DejaVu Sans,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**MainWindow/tagTreeWidgetExpandState-1** (QStringList): `4, 5`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteHistory-1** (QVariantList): `<variant list with 79 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `78`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `true`
**TagAddDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `true`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `19`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/tony/Nextcloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `15.0.5.3`
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-1** (QString): `Note 2019-11-01T10.51.33`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `true`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**QT_SELECT**: `snappy-qt5`
**SSH_AGENT_PID**: `30846`
**GST_PLUGIN_SCANNER**: `/snap/qownnotes/3207/usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner`
**XLOCALEDIR**: `/snap/qownnotes/3207/usr/share/X11/locale`
**CLUTTER_IM_MODULE**: `ibus`
**XDG_DATA_HOME**: `/home/tony/snap/qownnotes/3207/.local/share`
**LIBVA_DRIVERS_PATH**: `/snap/qownnotes/3207/usr/lib/x86_64-linux-gnu/dri`
**GDK_PIXBUF_MODULEDIR**: `/snap/qownnotes/3207/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**QTWEBENGINEPROCESS_PATH**: `/snap/qownnotes/3207/usr/lib/x86_64-linux-gnu/qt5/libexec/QtWebEngineProcess`
**QML2_IMPORT_PATH**: `/snap/qownnotes/3207/lib/x86_64-linux-gnu`
**VTE_VERSION**: `5802`
**SHELL**: `/bin/bash`
**SNAP_USER_COMMON**: `/home/tony/snap/qownnotes/common`
**XDG_MENU_PREFIX**: `gnome-`
**TERM**: `xterm-256color`
**SNAP_CONTEXT**: `7f5hgvbR5r2v2sNWtT5wYgp2TFQ27kJCrSVnrbRX9rsj`
**TMPDIR**: `/tmp`
**GJS_DEBUG_OUTPUT**: `stderr`
**GNOME_TERMINAL_SCREEN**: `/org/gnome/Terminal/screen/6def62ee_60cf_475f_854e_92fd9440ef92`
**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`
**GIO_MODULE_DIR**: `/home/tony/snap/qownnotes/common/.cache/gio-modules`
**GTK_MODULES**: `gail:atk-bridge`
**PULSE_SERVER**: `unix:/run/user/1000/snap.qownnotes/../pulse/native`
**LOCPATH**: `/snap/qownnotes/3207/usr/lib/locale`
**SNAP_REEXEC**: *empty*
**XDG_SESSION_CLASS**: `user`
**USER**: `tony`
**FONTCONFIG_FILE**: `/snap/qownnotes/3207/etc/fonts/fonts.conf`
**GST_PLUGIN_SYSTEM_PATH**: `/snap/qownnotes/3207/usr/lib/x86_64-linux-gnu/gstreamer-1.0`
**LIBGL_DRIVERS_PATH**: `/snap/qownnotes/3207/usr/lib/x86_64-linux-gnu/dri`
**LS_COLORS**: `rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:`
**INVOCATION_ID**: `5986a61e42e94c45b481dfeb908eb6e7`
**LD_LIBRARY_PATH**: `/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void::/snap/qownnotes/3207/lib:/snap/qownnotes/3207/usr/lib:/snap/qownnotes/3207/lib/x86_64-linux-gnu:/snap/qownnotes/3207/usr/lib/x86_64-linux-gnu:/snap/qownnotes/3207/usr/lib/x86_64-linux-gnu/mesa-egl:/snap/qownnotes/3207/usr/lib/x86_64-linux-gnu/mesa:/snap/qownnotes/3207/usr/lib/x86_64-linux-gnu/mesa:/snap/qownnotes/3207/usr/lib/x86_64-linux-gnu/mesa-egl:/snap/qownnotes/3207/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl`
**GNOME_TERMINAL_SERVICE**: `:1.279`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**SNAP_LIBRARY_PATH**: `/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void`
**SESSION_MANAGER**: `local/circus:@/tmp/.ICE-unix/31014,unix/circus:/tmp/.ICE-unix/31014`
**SNAP_INSTANCE_NAME**: `qownnotes`
**USERNAME**: `tony`
**DEFAULTS_PATH**: `/usr/share/gconf/gnome-xorg.default.path`
**SNAP_COMMON**: `/var/snap/qownnotes/common`
**LIBVIRT_DEFAULT_URI**: `qemu:///system`
**SNAP_USER_DATA**: `/home/tony/snap/qownnotes/3207`
**XDG_CONFIG_DIRS**: `/snap/qownnotes/3207/etc/xdg:/etc/xdg/xdg-gnome-xorg:/etc/xdg`
**SNAP_DATA**: `/var/snap/qownnotes/3207`
**FONTCONFIG_PATH**: `/snap/qownnotes/3207/etc/fonts`
**PATH**: `/snap/qownnotes/3207/usr/lib/x86_64-linux-gnu/qt5/bin:/snap/qownnotes/3207/usr/sbin:/snap/qownnotes/3207/usr/bin:/snap/qownnotes/3207/sbin:/snap/qownnotes/3207/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`
**DESKTOP_SESSION**: `gnome-xorg`
**QTCHOOSER_NO_GLOBAL_DIR**: `1`
**QT_QPA_PLATFORMTHEME**: `appmenu-qt5`
**QT_IM_MODULE**: `ibus`
**TEMPDIR**: `/tmp`
**GDK_PIXBUF_MODULE_FILE**: `/home/tony/snap/qownnotes/common/.cache/gdk-pixbuf-loaders.cache`
**PWD**: `/home/tony`
**XDG_SESSION_TYPE**: `x11`
**XMODIFIERS**: `@im=ibus`
**XKB_CONFIG_ROOT**: `/snap/qownnotes/3207/usr/share/X11/xkb`
**LANG**: `en_GB.UTF-8`
**MANDATORY_PATH**: `/usr/share/gconf/gnome-xorg.mandatory.path`
**IM_CONFIG_PHASE**: `1`
**QT_QPA_PLATFORM**: `xcb`
**XCURSOR_PATH**: `/snap/qownnotes/3207/usr/share/icons`
**GDMSESSION**: `gnome-xorg`
**GTK2_MODULES**: `overlay-scrollbar`
**SNAP_REVISION**: `3207`
**HOME**: `/home/tony/snap/qownnotes/3207`
**SHLVL**: `1`
**XDG_CONFIG_HOME**: `/home/tony/snap/qownnotes/3207/.config`
**SNAP_NAME**: `qownnotes`
**LANGUAGE**: `en_GB:en`
**DISABLE_WAYLAND**: `1`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**QT_PRINTER_MODULE**: `qtubuntu-print`
**QTCOMPOSE**: `/snap/qownnotes/3207/usr/share/X11/locale`
**SNAP_COOKIE**: `7f5hgvbR5r2v2sNWtT5wYgp2TFQ27kJCrSVnrbRX9rsj`
**GTK_PATH**: `/snap/qownnotes/3207/usr/lib/x86_64-linux-gnu/gtk-2.0`
**XDG_CACHE_HOME**: `/home/tony/snap/qownnotes/common/.cache`
**XDG_SESSION_DESKTOP**: `gnome-xorg`
**LOGNAME**: `tony`
**XDG_DATA_DIRS**: `/home/tony/snap/qownnotes/3207/.local/share:/home/tony/snap/qownnotes/3207:/snap/qownnotes/3207/usr/share:/usr/share/gnome-xorg:/home/tony/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**QT4_IM_MODULE**: `ibus`
**GST_PLUGIN_PATH**: `/snap/qownnotes/3207/usr/lib/x86_64-linux-gnu/gstreamer-1.0`
**SNAP_ARCH**: `amd64`
**LESSOPEN**: `| /usr/bin/lesspipe %s`
**JOURNAL_STREAM**: `9:325985`
**MANAGERPID**: `30649`
**WINDOWPATH**: `2`
**SNAP_VERSION**: `19.11.1`
**DISPLAY**: `:0`
**XDG_RUNTIME_DIR**: `/run/user/1000/snap.qownnotes`
**QT_PLUGIN_PATH**: `/snap/qownnotes/3207/usr/lib/x86_64-linux-gnu/qt5/plugins`
**SNAP_LAUNCHER_ARCH_TRIPLET**: `x86_64-linux-gnu`
**SNAP**: `/snap/qownnotes/3207`
**XDG_CURRENT_DESKTOP**: `GNOME`
**GTK_IM_MODULE**: `ibus`
**LESSCLOSE**: `/usr/bin/lesspipe %s %s`
**SNAP_INSTANCE_KEY**: *empty*
**XAUTHORITY**: `/run/user/1000/gdm/Xauthority`
**COLORTERM**: `truecolor`
</details>

**Comment by pbek** [comment]
fyi, @Waqar144

**Comment by pbek** [comment]
@Waqar144, maybe the `~` doesn't get resolved, there is `QDir::homePath()` for that? Plus snaps also have their own home-directory. I usually do a `path.remove(QRegularExpression(R"(snap\/qownnotes\/\w\d+\/)"));` to cut out the snap part of a path, like here:

https://github.com/pbek/QOwnNotes/blob/eae27c374d46f82c4d895bb487a217689a48987d/src/utils/misc.cpp#L395-L427

**Comment by Waqar144** [comment]
What would the full home path in a snap look like?

**Comment by pbek** [comment]
e.g. `/home/username/snap/qownnotes/3217`, but we only want `/home/username`

**Comment by pbek** [comment]
`path.remove(QRegularExpression(R"(snap\/qownnotes\/\w\d+\/)"));` does the trick

**Comment by Waqar144** [comment]
> `path.remove(QRegularExpression(R"(snap\/qownnotes\/\w\d+\/)"));` does the trick

I did that already. Let's see.
I just wanna be more sure about the path.
Sending in the PR in a moment

**Comment by tonyarnold99** [comment]
On Fri, 2019-11-01 at 05:52 -0700, Patrizio Bekerle wrote:
> e.g. /home/username/snap/qownnotes/3217, but we only want
> /home/username

Spell checking works if I copy the dictionary files to
/home/username/snap/qownnotes/current/.local/share/hunspell

so removing the snap part of the path as per Patrizio's suggestion
should do the trick.

Regards,
Tony.
-- 
Tony Arnold MBCS, CITP | Senior IT Security Analyst | Directorate of IT Services | G64, Kilburn Building | The University of Manchester | Manchester M13 9PL | T: +44 161 275 6093 | M: +44 773 330 0039

**Comment by Waqar144** [comment]
> `path.remove(QRegularExpression(R"(snap\/qownnotes\/\w\d+\/)"));` does the trick

Since it is in the code already and works, I used this Regex. However as I understand it, the last part of the regex `\w\d+` would catch `a12345` and not `current ` or anything.
If it works, then great, otherwise \w+ should do the trick i think.

**Comment by Waqar144** [comment]
> > `path.remove(QRegularExpression(R"(snap\/qownnotes\/\w\d+\/)"));` does the trick
> 
> Since it is in the code already and works, I used this Regex. However as I understand it, the last part of the regex `\w\d+` would catch `a12345` or something else with a different first char and not `current ` or anything.
> If it works, then great, otherwise \w+ should do the trick i think.

**Comment by pbek** [comment]
Inside the snap the IDs are used.

**Comment by Waqar144** [comment]
> Inside the snap the IDs are used.

Ahh okay

**Comment by pbek** [comment]
## 19.11.3
- attempted to fix inclusion of spellchecker dictionaries for Snap package
  (for [#1348](https://github.com/pbek/QOwnNotes/issues/1348), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by tonyarnold99** [comment]
Still not working. Hunspell dictionaries have been copied to ~/.local/share/hunspell, qoownnotes is still reporting no language dictionaries for the language: "en_GB".

Copying the dictionary files back to the ~/snap/qownnotes/current/.local/share/hunspell fixes it again.

**Comment by pbek** [comment]
Are you on the `stable` channel?

**Comment by tonyarnold99** [comment]
Yes. Version 19.11.3.

**Comment by pbek** [comment]
Strange, I see no reason why #1350 should not fix the path issue...

**Comment by Waqar144** [comment]
> Strange, I see no reason why #1350 should not fix the path issue...

I fear snap package can't access .local and such directories

https://forum.snapcraft.io/t/desktop-allow-access-to-host-system-fonts/1796

**Comment by Waqar144** [comment]
A more easier and straightforward way could be to symlink /usr/share/hunspell 
That'd work

A script for it could be like:

```
#!/bin/bash
mkdir -p ~/snap/qownnotes/usr/share
ln -s /usr/share/hunspell ~/snap/qownnotes/usr/share
```

OR

```
#!/bin/bash
mkdir -p ~/snap/qownnotes/current/usr/share
ln -s /usr/share/hunspell ~/snap/qownnotes/current/usr/share
```

**Comment by tonyarnold99** [comment]
I've tried that and it does not work or something similar. I tried:

ln -s /usr/share/hunspell ~/snap/qownnotes/common/.local/share/hunspell

Looks like the snap containment is smart enough to realise it's accessing folders that its' not supposed to!

**Comment by Waqar144** [comment]
> Looks like the snap containment is smart enough to realise it's accessing folders that its' not supposed to!

I guess then a script to copy all the dictionaries to the snap directory can be a solution.
Unless @pbek is ready to package dicts in the snap :package:   :smile: 

There is a hunspell dictionaries snap package(the one you @pbek tried to plug into in a previous commit) to which we could connect and get the dictionaries but that requires installing that package first.

**Comment by pbek** [comment]
I don't understand why it doesn't work. The access to the note files in the home directory works the same way.

**Comment by Waqar144** [comment]
> I don't understand why it doesn't work. The access to the note files in the home directory works the same way.

I guess snap doesn't allow access to *all* places in /home, only some, like Documents etc

**Comment by tonyarnold99** [comment]
If I try to import a file from ~/.local, qownnotes shows .local as empty! Also if I export to it, it appears to work but the exported file does not appear in .local. Must be something about .local. Or even hidden directories. Tried exporting to .hunspell and that didn't work either.

**Comment by tonyarnold99** [comment]
This confirms my suspicions about hidden files:

https://forum.snapcraft.io/t/use-of-home-and-network-plugs/2587

**Comment by pbek** [comment]
Maybe point-directories really are not allowed. Could make sense.

**Comment by pbek** [comment]
For me it was the same, I was able to set `/home/username/.local/share/0ad` as note folder, but I wasn't able to read from or write to the folder.

**Comment by pbek** [comment]
`/home/username/Documents` or `/home/omega/Temp/SomeName` worked great

**Comment by pbek** [comment]
A folder `/home/omega/.hunspell` did not work. `/home/omega/hunspell` did work.

## 19.11.4
- added `~/hunspell` as path for spellchecker dictionaries for Snap package

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by tonyarnold99** [comment]
Yes, version 19.11.4 snap works with the dictionaries copied to ~/hunspell.

**Comment by pbek** [comment]
Great, thank you for testing!
