### ISSUE TITLE
Feature request: Custom editor width

### ISSUE THREAD

**Issue by ivanpirog** [pbek/QOwnNotes#1349]
It would be great to add a new option "Custom width" in Main Menu -> Window -> Editor width. And two new hotkeys for increase and decrease editor width ("`Ctrl+Shift+[`" and "`Ctrl+Shift+]`").

That is, we need a new variable `customCharacterAmount` which will be stored in the options. Key `Ctrl+Shift+[` will decrease the value by 2. Key `Ctrl+Shift+]` will increase the value by 2. And auto refresh editor margins happens immediately.

If the current option is the **Narrow** editor width (or another preset) and user pressed `Ctrl+Shift+[` or `Ctrl+Shift+]` , then the option switches to the **Custom width** and following steps is executed:

1. customCharacterAmount = narrowCharacterAmount (amount from current preset)
2. if increaseKeyPressed then customCharacterAmount += 2
3. if decreaseKeyPressed then customCharacterAmount -= 2
4. set current option to the Custom Editor Width

User can also go to the menu `Main Menu -> Window -> Editor width -> Custom width...`. Then a dialog box appears with the ability to enter value for the `customCharacterAmount` variable. Then user presses OK or Enter and the editor width is automatically updated.

I think this is a cool feature :)

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
You'll get that in #1604, but minus the shortcuts (that would be a bit too complex).
