### ISSUE TITLE
tagging multiple notes

### ISSUE THREAD

**Issue by dh-connect** [pbek/QOwnNotes#135]
the tagging function is really great, i was waiting for that, it would be awesome to tag multiple notes at ones because i have plenty of notes, I would like to search for them by entering a key word and tag them all at ones, thanks !

**Comment by pbek** [comment]
Thank you for your feedback. Do you mean a functionality where you are able to tag all selected notes from the note list?

**Comment by dh-connect** [comment]
yes that would be great, maybe to drag and drop them on a tag in the left tag windows

**Comment by pbek** [comment]
That would be a great idea, although I once tried to enable drag and drop for the notes and I didn't like the experience a lot. You cannot select multiple notes that easily and you always have to be careful to just click and not drag the notes...
Maybe we just do a right click menu for tagging.

**Comment by pbek** [comment]
Will be done in version 1.4.1.

**Comment by pbek** [comment]
Version 1.4.1 is out now. Could be please be so kind and give some feedback.

**Comment by dh-connect** [comment]
works great, thank you so much !

**Comment by pbek** [comment]
I'm glad you like it! :)
