### ISSUE TITLE
[I] Trailing "======" artifacts are appended to Notes

### ISSUE THREAD

**Issue by truthsword** [pbek/QOwnNotes#1351]
#### Expected behaviour

Trailing "============" does not append to the copied web note.

#### Actual behaviour

When copying web pages using web-companion (chrome) a series of "equals" marks are appended to the note.

"============"

This occurs in all copy instances (html/screenshot/text selection).

This appears to be related to modifying the default editor font,

#### Steps to reproduce

For example...

With these settings all is fine (no trailing ======)
![](https://i.imgur.com/4jMDaQP.png)

But if I increase the MS Shell Dlg font...say to 12
![](https://i.imgur.com/ktMQBj6.png)

then I get this...
![](https://i.imgur.com/fBnG6bU.png)

Also, note that changing the MS Shell Dlg 2 default font changes its appearance on the setting page. This does not happen when changing the Code font.

Bringing the font back to "8" "fixes" things... except for my eyesight 😣

I discovered this with a new profile, and when I went back to my profile and reset the font to "8", the trailing "============" no longer occurred.

Hopefully, you can reproduce/fix 😉 Thanks!

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sat Nov 2 13:07:47 2019`
**Version**: `19.11.0`
**Build date**: `Oct 31 2019`
**Build number**: `4732`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.13.0`
**Qt Version (runtime)**: `5.13.0`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\username\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `D:\Program Files (x86)\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `50`
**Calendar items**: `0`
**Enabled scripts**: `0`
</details>

**Comment by pbek** [comment]
I set my font veeeeery large and still wasn't able to reproduce your issue.

The new note is created with:

https://github.com/pbek/QOwnNotes/blob/8c02dfb7571dc6cbaf54001affc6789412467fcf/src/mainwindow.cpp#L4040-L4089

I see no obvious fault with that...
You didn't post your full Debug settings output. Are there any scripts interfering or other non-default settings?

**Comment by truthsword** [comment]
The screenshots I posted were for a fresh session, so basically default settings with no scripts present. The only change was for the extension security token and font size. I should have posted the debug, but since I thought I had nailed the cause/effect, so I did not. I misestimated that.

This is a stubborn issue on my PC. Sometimes I see 3 '=', and sometimes 12. Out of frustration, I tried different font settings for the edit window and had Arial 12 working on the fresh session. I exported those settings and imported them into my working set. For now, the '=' is absent. I remapped all my folders, and am slowly tweaking the interface (saving the settings each time in case I need to rollback).

If this issue returns, and I can pinpoint the cause, I'll post the debug along with the info

Since I seem to be the only one seeing this, maybe it is unique to my system.

**Comment by pbek** [comment]
It sounds like a timing problem and like two things happening at the same time.
If it's fixable I'd like to fix it. :smile:

**Comment by pbek** [comment]
Did this problem only appear recently or also in older versions of QON?

**Comment by pbek** [comment]
And there is another regression, @Waqar144 :laughing: 

https://github.com/pbek/QOwnNotes/blob/8c02dfb7571dc6cbaf54001affc6789412467fcf/src/mainwindow.cpp#L4077

`\n\n` is missing. :grin: 

@truthsword, that might have caused it, we'll see...

**Comment by truthsword** [comment]
This has been around for quite some time. I don't recall a time when it didn't happen, I just thought it was part of HTML capture (I rarely/never use screenshot w/QON), but when I noticed it with text capture, I wasn't sure whether it was an HTML artifact - although I know that HTML codes aren't used (bold/italic..) when capturing text.

Largely I ignored it and deleted it from the edit window,

**Comment by truthsword** [comment]
Copying text from my post above, it's back...
![](https://i.imgur.com/SJhYsw7.png)

**Comment by pbek** [comment]
ouchy, @Waqar144. It seems that basically ALL `\n` strings got missing in your refactoring. :smiling_imp: I'm currently seeking a way to get them back without checking every line of your commit.

**Comment by Waqar144** [comment]
> ouchy, @Waqar144. It seems that basically ALL `\n` strings got missing in your refactoring. 😈 I'm currently seeking a way to get them back without checking every line of your commit.

I will look into it immediately(if you haven't already) . I used regex to replace them, going through each of them one by one.

**Comment by pbek** [comment]
I tried to fix some of the damage in https://github.com/pbek/QOwnNotes/commit/0f6cf8b1c5b4e775f37327b871ca2c610af67ab5, but I don't know if any other characters got removed or if there are other commits (I've at least seem one other).

**Comment by Waqar144** [comment]
> I tried to fix some of the damage in [0f6cf8b](https://github.com/pbek/QOwnNotes/commit/0f6cf8b1c5b4e775f37327b871ca2c610af67ab5), but I don't know if any other characters got removed or if there are other commits (I've at least seem one other).

I will go through it all line by line and fix everything (by hand).

**Comment by pbek** [comment]
But my fixes didn't fix the problem of this issue...

@truthsword, it turned out the font size wasn't the issue, it was about if the `=` headline markings were breaking into the next line in the note text edit

**Comment by pbek** [comment]
It was really tricky to track that issue down...

## 19.11.3
- fixed wrong note text insertion from the web companion and other parts of the
  application if the `=` headline markings were breaking into the next line in
  the note text edit
- fixed many optimization regressions from [7848f4de14fd152be8a8ffc7c8d97f8f37d1a431](https://github.com/pbek/QOwnNotes/commit/7848f4de14fd152be8a8ffc7c8d97f8f37d1a431)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by truthsword** [comment]
So far, so good... text capture/screenshot/html copy, all without "="

I went back to some web pages copied this week that had the "=" appended and I recopied them without all that stuff at the end. I hope this holds up. Thanks!

**Comment by pbek** [comment]
Great, thank you for testing! 😄
