### ISSUE TITLE
Right clicking on note list crashes QOwnNotes

### ISSUE THREAD

**Issue by maqp** [pbek/QOwnNotes#1353]
This problem started today when I updated to 19.11.2: When the note list is right-clicked 

(to be more specific, right-clicking a note works, when the empty white space under the existing notes is right-clicked) 
![](https://i.imgur.com/TJMBMAw.png)

the program crashes.

Here's the output on terminal

    $ QOwnNotes 
    Info: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway. ((null):0, (null))
    Info: "QOwnNotes server listening on port 22222" ((null):0, (null))
    Segmentation fault (core dumped)

**Comment by pbek** [comment]
It doesn't crash for me on Linux, macOS or Windows...

Can you please post the output from the debug settings (see issue template).

**Comment by maqp** [comment]
# Log panel output

[17:42:37] [info] "QOwnNotes server listening on port 22222"
[17:42:37] [debug] on_noteTreeWidget_currentItemChanged
[17:42:37] [debug] setCurrentNote - 'note': Note: <id>4 <name>(redacted) <fileName>(redacted) <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false - 'updateNoteText': true - 'updateSelectedNote': false
[17:42:37] [debug] Loading trigrams from ":/libraries/sonnet/src/trigrams.map"
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for "\t* Uutiset"
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] No scores for (redacted)
[17:42:37] [debug] Unable to identify string with dictionaries: (redacted)
[17:42:37] [debug] added to history: NoteHistoryItem: <noteName>(redacted) <noteSubFolderPathData>"" <cursorPosition>20 <relativeScrollBarPosition>0

# Debug information

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `su marrask. 3 17:35:27 2019`
**Version**: `19.11.2`
**Build date**: `Nov  1 2019`
**Build number**: `607`
**Platform**: `linux`
**Operating System**: `Ubuntu 19.10`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.12.4`
**Qt Version (runtime)**: `5.12.4`
**Portable mode**: `no`
**Settings path / key**: `<redacted>`
**Application database path**: `<redacted>`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `Papirus`
**Notes in current note folder**: `163`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `<redacted>`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `<redacted>`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `<redacted>`

### Note folder `testdir`

**id**: `2`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `<redacted>`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `<redacted>`

## Cloud connections

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Enabled scripts

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `true`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `<redacted>`
**FileDialog/LastPath-ScriptPath** (QString): `<redacted>`
**FileDialog/LastPath-SettingsExport** (QString): `<redacted>`
**LastUpdateCheck** (QDateTime): `2019-11-03T17:35:20.873`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `<redacted>`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MainWindow/tagTreeWidgetExpandState-3**: *empty*
**MessageBoxOverride/log-file-cleared** (QString): `1024`
**MessageBoxOverride/remove-note-folder** (QString): `16384`
**NoteHistory-1** (QVariantList): `<variant list with 23 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `22`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**SettingsExport/platform** (QString): `linux`
**Shortcuts/MainWindow-actionInsert_current_time** (QString): `Ctrl+Shift+?`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TagAddDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `true`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `false`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `17`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `false`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `true`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `1`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `<redacted>`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/ignoreNonTodoCalendars** (QString): `true`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `2`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): `<redacted>`
**ownCloud/todoCalendarCalDAVUsername** (QString): `<redacted>`
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**recentNoteFolders** (QStringList): `<redacted>`
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `<redacted>`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**HOME**: `<redacted>`
**LANG**: `en_US.UTF-8`
**LC_ADDRESS**: `fi_FI.UTF-8`
**LC_IDENTIFICATION**: `fi_FI.UTF-8`
**LC_MEASUREMENT**: `fi_FI.UTF-8`
**LC_MONETARY**: `fi_FI.UTF-8`
**LC_NAME**: `fi_FI.UTF-8`
**LC_NUMERIC**: `fi_FI.UTF-8`
**LC_PAPER**: `fi_FI.UTF-8`
**LC_TELEPHONE**: `fi_FI.UTF-8`
**LC_TIME**: `fi_FI.UTF-8`
**LOGNAME**: `<redacted>`
**PATH**: `<redacted>/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
**SHELL**: `/bin/bash`
**USER**: `<redacted>`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**GTK_MODULES**: `gail:atk-bridge`
**XDG_DATA_DIRS**: `/usr/share/ubuntu-wayland:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**DESKTOP_SESSION**: `ubuntu-wayland`
**GDMSESSION**: `ubuntu-wayland`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**GNOME_SHELL_SESSION_MODE**: `ubuntu`
**PWD**: `<redacted>`
**QT_IM_MODULE**: `ibus`
**SESSION_MANAGER**: `local/<redacted>:@/tmp/.ICE-unix/1427,unix/<redacted>:/tmp/.ICE-unix/1427`
**SHLVL**: `0`
**SSH_AGENT_LAUNCHER**: `gnome-keyring`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**USERNAME**: `<redacted>`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-ubuntu-wayland:/etc/xdg`
**XDG_CURRENT_DESKTOP**: `ubuntu:GNOME`
**XDG_MENU_PREFIX**: `gnome-`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_DESKTOP**: `ubuntu-wayland`
**XDG_SESSION_TYPE**: `wayland`
**XMODIFIERS**: `@im=ibus`
**_**: `/usr/bin/gnome-session`
**MANAGERPID**: `1313`
**INVOCATION_ID**: `993088edebf94290abc7d738e4934066`
**JOURNAL_STREAM**: `9:38058`
**DISPLAY**: `:0`
**XAUTHORITY**: `/run/user/1000/.mutter-Xwaylandauth.4MVLA0`
**WAYLAND_DISPLAY**: `wayland-0`
**GJS_DEBUG_OUTPUT**: `stderr`
**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`
**GIO_LAUNCHED_DESKTOP_FILE**: `/usr/share/applications/PBE.QOwnNotes.desktop`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `16041`

**Comment by maqp** [comment]
So all in all, nothing seems to be logging into the system. I'll see if I can remove profiles and reset everything to see if that will fix it.

**Comment by maqp** [comment]
I get the same exact crash with clean Ubuntu 19.10 virtual machine.

**Comment by pbek** [comment]
I've no troubles on Ubuntu or Manjaro (both with KDE). Which Desktop Environment are you using? Is there any crash dump (do you have the QOwnNotes debug symbols installed)?

**Comment by pbek** [comment]
Maybe some input method that can cause troubles? (`ibus`)

**Comment by pbek** [comment]
> Which Desktop Environment are you using? 

Gnome it seems...

**Comment by maqp** [comment]
I'm using Ubuntu 19.10 that comes with GNOME 3.34.1. Just a moment, I'll see if the crash also happens on Kubuntu 19.10 (KDE).

**Comment by maqp** [comment]
Yes, same issue with Kubuntu 19.10? Are you using the LTS version? Also, is there a way to install previous versions of QOwnnotes with APT or some other way so I could test those?
![](https://i.imgur.com/hOv8o2b.png)

**Comment by maqp** [comment]
I'm getting the same crash on Windows 10 after updating its installation of QOwnnotes from 19.10.10 (no way to check if that was the last version where it worked, it just happened to be installed) to 19.11.3. 

Before update
![](https://i.imgur.com/RN7ZdPd.png)

After update
https://i.imgur.com/iW9yXDK.mp4

**Comment by Waqar144** [comment]
Crashing for me as well.

**Comment by Waqar144** [comment]
I fixed it,
Though I can't understand why it's not happening to you :laughing:

**Comment by pbek** [comment]
>  Though I can't understand why it's not happening to you laughing

Strange...

**Comment by Waqar144** [comment]
> I'm getting the same crash on Windows 10 after updating its installation of QOwnnotes from 19.10.10 (no way to check if that was the last version where it worked, it just happened to be installed) to 19.11.3.
> 
> Before update
> ![](https://camo.githubusercontent.com/df6c514f5372dc4f5a9efc2ab7e276ef30051b3b/68747470733a2f2f692e696d6775722e636f6d2f524e375a6450642e706e67)


Look at the menu in this pic. I think it's the incorrect menu. Menu for empty space is different one(NoteSubFolderContextMenu)

**Comment by pbek** [comment]
## 19.11.4
- fixed a possible crash when right-clicking on the note list
  (for [#1353](https://github.com/pbek/QOwnNotes/issues/1353), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by maqp** [comment]
The program no longer crashes, hooray! :tada:  Unfortunately, there's a problem with right-click context menu not working. I created a separated ticket for it: https://github.com/pbek/QOwnNotes/issues/1361

**Comment by pbek** [comment]
Great, thank you for testing!
