### ISSUE TITLE
[I] New Folder default folder location

### ISSUE THREAD

**Issue by truthsword** [pbek/QOwnNotes#1354]
#### Expected behaviour

In Setup note folders, when I click the New Folder button, the note folder path changes to 

C:\User\<username>\Nextcloud\Notes

This is not an existing path on my PC. How can I set this to point to the default location where my Notes are stored... for example

G:\User\<username>\Documents\QOwnNotes\

#### Actual behaviour

Open Settings>Note Folders... click on "Add folder" button...

Note folder path changes to
C:\User\<username>\Nextcloud\Notes

#### Steps to reproduce

Open Settings>Note Folders... click on "Add folder" button...

Note folder path changes to
C:\User\<username>\Nextcloud\Notes

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[10:10:47] [warning] OpenType support missing for "MS Shell Dlg 2", script 12
[10:10:47] [warning] OpenType support missing for "Arial", script 12
[10:10:47] [warning] OpenType support missing for "MS UI Gothic", script 12
[10:10:47] [warning] OpenType support missing for "SimSun", script 12
[10:10:47] [warning] OpenType support missing for "Arial Unicode MS", script 12
[10:10:47] [warning] OpenType support missing for "MS Shell Dlg 2", script 11
[10:10:47] [warning] OpenType support missing for "Arial", script 11
[10:10:47] [warning] OpenType support missing for "MS UI Gothic", script 11
[10:10:47] [warning] OpenType support missing for "SimSun", script 11
[10:10:47] [warning] OpenType support missing for "MS Shell Dlg 2", script 13
[10:10:47] [warning] OpenType support missing for "Arial", script 13
[10:10:47] [warning] OpenType support missing for "MS UI Gothic", script 13
[10:10:47] [warning] OpenType support missing for "SimSun", script 13
[10:10:47] [warning] No language dictionaries for the language: "en_US"
[10:10:47] [warning] No language dictionaries for the language: "en_US"
[11:09:04] [status] Stored current note to disk
[11:09:09] [status] Stored 1 note(s) to disk
[11:09:20] [status] Stored current note to disk
[11:09:29] [status] Stored 1 note(s) to disk
[11:09:46] [status] Stored current note to disk
[11:09:49] [status] Stored 1 note(s) to disk
[11:11:09] [status] Stored 1 note(s) to disk
[11:11:19] [status] Stored 1 note(s) to disk
[12:28:00] [warning] No language dictionaries for the language: "en_US"
[12:28:00] [warning] No language dictionaries for the language: "en_US"
[12:28:00] [warning] No language dictionaries for the language: "en_US"
[12:28:00] [warning] No language dictionaries for the language: "en_US"
[12:28:00] [warning] No language dictionaries for the language: "en_US"
[12:28:00] [warning] No language dictionaries for the language: "en_US"
[12:28:00] [warning] No language dictionaries for the language: "en_US"
[12:28:00] [warning] No language dictionaries for the language: "en_US"
[12:28:00] [warning] No language dictionaries for the language: "en_US"
[12:28:00] [warning] No language dictionaries for the language: "en_US"
[12:28:00] [warning] No language dictionaries for the language: "en_US"
[12:28:00] [warning] No language dictionaries for the language: "en_US"
[12:28:00] [warning] No language dictionaries for the language: "en_US"
[12:28:00] [warning] No language dictionaries for the language: "en_US"
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sun Nov 3 12:38:09 2019`
**Version**: `19.11.2`
**Build date**: `Nov  1 2019`
**Build number**: `4743`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.13.0`
**Qt Version (runtime)**: `5.13.0`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\UserName\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `D:\Program Files (x86)\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `56`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Note folders

**currentNoteFolderId**: `4`

### Note folder `default`

**id**: `8`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `E:\Users\UserName\Documents\QOwnNotes\_notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `E:\Users\UserName\Documents\QOwnNotes\_notes\notes.sqlite`

### Note folder `demo`

**id**: `4`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `E:\Users\UserName\Documents\QOwnNotes\demo`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `E:\Users\UserName\Documents\QOwnNotes\demo\notes.sqlite`

### Note folder `docker`

**id**: `5`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `E:\Users\UserName\Documents\QOwnNotes\docker`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `E:\Users\UserName\Documents\QOwnNotes\docker\notes.sqlite`

### Note folder `new folder`

**id**: `17`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `C:\Users\UserName\Nextcloud\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\UserName\Nextcloud\Notes\notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `F:/bak/qon`
**FileDialog/LastPath-SettingsExport** (QString): `F:/bak/qon`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2019-11-03T12:11:26.320`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `31`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Arial,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Courier New,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.064,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `true`
**MessageBoxOverride/delete-files** (int): `16384`
**MessageBoxOverride/remove-note-folder** (int): `16384`
**MessageBoxOverride/remove-notes** (int): `16384`
**NoteHistory-1** (QVariantList): `<variant list with 6 item(s)>`
**NoteHistory-15** (QVariantList): `<variant list with 1 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 1 item(s)>`
**NoteHistory-3** (QVariantList): `<variant list with 1 item(s)>`
**NoteHistory-4** (QVariantList): `<variant list with 5 item(s)>`
**NoteHistory-5** (QVariantList): `<variant list with 3 item(s)>`
**NoteHistory-8** (QVariantList): `<variant list with 5 item(s)>`
**NoteHistory-9** (QVariantList): `<variant list with 1 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `5`
**NoteHistoryCurrentIndex-15** (int): `0`
**NoteHistoryCurrentIndex-2** (int): `0`
**NoteHistoryCurrentIndex-3** (int): `0`
**NoteHistoryCurrentIndex-4** (int): `4`
**NoteHistoryCurrentIndex-5** (int): `2`
**NoteHistoryCurrentIndex-8** (int): `4`
**NoteHistoryCurrentIndex-9** (int): `0`
**OrphanedImagesDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**SettingsExport/platform** (QString): `windows`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `true`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (QString): `false`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (int): `8`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `false`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (int): `19`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `E:/Users/UserName/Documents/QOwnNotes/_notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**recentNoteFolders** (QStringList): `E:/Users/UserName/Documents/QOwnNotes/_notes/, E:/Users/UserName/Documents/QOwnNotes/docker, E:/Users/UserName/Documents/QOwnNotes/demo, E:/Users/UserName/Documents/QOwnNotes`
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-8** (QStringList): `[I] Trailing ====== artifacts are appended to Notes · Issue #1351 · pbek QOwnNotes 2019-11-03T11.09.46, [I] Trailing ====== artifacts are appended to Notes · Issue #1351 · pbek QOwnNotes 2019-11-03T11.09.20, [I] Trailing ====== artifacts are appended to Notes · Issue #1351 · pbek QOwnNotes, Projects · pbek QOwnNotes`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**webSocketServerService/token** (QString): `c0ldbeer`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\UserName\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `PC`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**configsetroot**: `C:\WINDOWS\ConfigSetRoot`
**DokanLibrary1**: `D:\Program Files\Dokan\Dokan Library-1.0.1\`
**DokanLibrary1_LibraryPath_x64**: `D:\Program Files\Dokan\Dokan Library-1.0.1\lib\`
**DokanLibrary1_LibraryPath_x86**: `D:\Program Files\Dokan\Dokan Library-1.0.1\x86\lib\`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**FP_NO_HOST_CHECK**: `NO`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\UserName`
**LOCALAPPDATA**: `C:\Users\UserName\AppData\Local`
**LOGONSERVER**: `\\PC`
**NUMBER_OF_PROCESSORS**: `8`
**OneDrive**: `C:\Users\UserName\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;D:\Program Files (x86)\IsoBuster;D:\SyMenu;D:\Program Files\Adobe\Adobe PDF iFilter 11\bin;D:\Program Files\Process Lasso;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\UserName\AppData\Local\Programs\Python\Python37;D:\Program Files\Pandoc;D:\Program Files\Adobe\Adobe PDF iFilter 11\bin\;C:\Users\UserName\AppData\Local\Microsoft\WindowsApps;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 58 Stepping 9, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `3a09`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\UserName\AppData\Local\Temp`
**TMP**: `C:\Users\UserName\AppData\Local\Temp`
**USERDOMAIN**: `PC`
**USERDOMAIN_ROAMINGPROFILE**: `PC`
**USERNAME**: `Bob`
**USERPROFILE**: `C:\Users\UserName`
**windir**: `C:\WINDOWS`
</details>

**Comment by pbek** [comment]
Thank you for your suggestion, but there is no simple way to find out where your notes are currently stored (if you already have some), because they are just simple markdown files. The default folder is the folder that you would use if Nextcloud was used. `ownCloud` will be used if there is such a folder.

Searching all harddisks for `notes.sqlite` would be very hard and take quite long.

**Comment by truthsword** [comment]
I get that... for the first new folder. but I thought it would remember the path once a user changes it. So when I add multiple folders, the "New Folder" path defaults to my specified path, or the last path used.

But... not a frequent deal... I thought I could find the new folder path in the registry, but no, so I suppose it's coded.

Thanks anyway.

**Comment by pbek** [comment]
Now I know what you are talking about. I can do that, it's a good idea.

## 19.11.4
- when creating a new note folder now by default the local path of the active
  note folder will be used

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by truthsword** [comment]
That is 95% there... a small tweak to consider...

If I set the default path to
c:\QOwnNotes

When I create a new folder, for example, "builds", can we add that folder as appended to the default path? Such as...
c:\QOwnNotes\builds

That way I can enter a series of new folders under the default path, simply by entering the folder name, and then hitting the Enter key. For example... in the folder name box...

dogs<Enter>
cats<Enter>
cows<Enter>

thereby creating 
c:\QOwnNotes\dogs
c:\QOwnNotes\cats
c:\QOwnNotes\cows

Just a thought...

>Now I know what you are talking about

At times I confuse myself.

**Comment by pbek** [comment]
> When I create a new folder, for example, "builds", can we add that folder as appended to the default path? Such as...
> c:\QOwnNotes\builds

How should a program logic decide what sub-folder it should add to the current note folder?

> At times I confuse myself.

:laughing:

**Comment by truthsword** [comment]
>How should a program logic decide what sub-folder it should add to the current note folder?

I was thinking that subfolders could be appended to the "Note folder path:" specified in the field box, simply by adding changing the folder "Name:" field and hitting the Enter key (or clicking "OK" to close the settings window.
![](https://i.imgur.com/SjiQBv5.png)

**Comment by pbek** [comment]
I want to leave that field read-only to prevent wrong note paths (they are essential).

**Comment by truthsword** [comment]
Fine. What you have already done is quite helpful for me. Thank you.

**Comment by pbek** [comment]
Thank you for suggesting it!

**Comment by compumatter** [comment]
Totally lost on the creating a folder feature.  After a fresh install (no nextcloud / owncloud relationship) I right click on the left panel say create new folder, give the folder a name and then nothing appears - anywhere. 

Is this a feature I am missing placement of, or a bug?  Thanks.

**Comment by pbek** [comment]
What happens if you reload the note folder (see note menu). Does the folder also not appear in an external file manager?
