### ISSUE TITLE
Menu item doesn't open and copy and paste doesn't work, Ubuntu  18.04.1

### ISSUE THREAD

**Issue by dh-connect** [pbek/QOwnNotes#1355]
#### Expected behaviour

On click of menu item, it opens
Using Ctrl + C on marked text copies it into clipboard

#### Actual behaviour

On click of menu item, it highlights but no menu opens
Using Ctrl + C doesn't copy

#### Steps to reproduce

using version QOwnNotes 19.11.2 on Linux Ubuntu 18.04.1

**Comment by woodpenker** [comment]
Did you use gnome as default windows manager? Make sure u don't have any key binding conflicts by gnome and qownnotes or any other plugins. Try using` stty -a` to find if ctrl+c is bind to copy text, something like this `intr = ^C;`

**Comment by Waqar144** [comment]
@dh-connect Do you mean the Right click menu?

Right click menu (Context menu) is also broken due to the new spellchecker feature.

**Comment by pbek** [comment]
## 19.11.4
- fixed the default text edit context menu for the spellchecker
  (for [#1355](https://github.com/pbek/QOwnNotes/issues/1355), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by dh-connect** [comment]
I tested it, copy and paste seems to work, but now the menu bar is gone, don't know how to get it back, context menu is also not working, is there a way to reset the editor in linux to default settings? e.g. delete a config file somewhere? maybe that would fix my problems. It tried apt purge qownnotes and apt install qownnotes, but that didn't help

My workaround for copy & paste was to open the note in external editor(button left next to save button), opened it up in pluma and copy it from there, thank you for your support

**Comment by Waqar144** [comment]
> I tested it, copy and paste seems to work, but now the menu bar is gone, don't know how to get it back,

Try, `Ctrl + Shift + M`. It will hide/ show the menu

context menu is also not working, is there a way to reset the editor in linux to default settings? e.g. delete a config file somewhere? maybe that would fix my problems. It tried apt purge qownnotes and apt install qownnotes, but that didn't help

Yes, you can reset the app.
### First way
Go to Main Menu, open `Note->Settings`
OR
Press `Ctrl + ,`
Settings dialog will open. On the left hand side click on `General`. On the right hand side, you will see a button `Clear app data and exit`. This will reset your QOwnNotes installation.

### Second way:
- Open file manager.
- Go to your home folder and unhide folders (`Ctrl + H`).
- You will see a `.config` folder. Open it.
- Inisde you will find a folder named `PBE`. Delete that folder.
- Next go to your Notes folder, for e.g `~/Documents/Notes`.
- Inisde that folder you will see a file named `notes.sqlite`. This is the database file.
- Delete this file
Done.

> My workaround for copy & paste was to open the note in external editor(button left next to save button), opened it up in pluma and copy it from there, thank you for your support

Please try the above and let me know if it solves your issue. Thank you.

**Comment by pbek** [comment]
> is there a way to reset the editor in linux to default settings? 

see: http://docs.qownnotes.org/en/develop/cli-parameters.html
