### ISSUE TITLE
Spell checking performance issues on macOS

### ISSUE THREAD

**Issue by smokris** [pbek/QOwnNotes#1359]
Since spell checking (#125) was added, QOwnNotes takes a very long time to display a note after I select it in the note list (tested with QOwnNotes 19.11.3 on macOS 10.14.6).  It grows linearly with the size of the note:

   - 3KB note — 1 second
   - 18KB note — 5 seconds
   - 46KB note — 11 seconds
   - 159KB note — 58 seconds

I ran a time profile while waiting for a note to load, and most of the time is spent doing language detection:
![Screen Shot 2019-11-04 at 09 09 42](https://user-images.githubusercontent.com/190164/68127782-87737480-fee4-11e9-9125-f8f043886eb4.png)

If I go to Edit > Languages and pick (for example) American English, note selection is somewhat faster:

   - 46KB note — 2 seconds
   - 159KB note — 12 seconds

And if I disable spell checking entirely, it's back to normal (before QOwnNotes added spell checking) speed:

   - 46KB note — < 1 second
   - 159KB note — 1 second

Perhaps QOwnNotes could run language detection on only a subset of each note, to speed it up?  And maybe perform spell checking asynchronously and/or only on the visible text in the current viewport?

**Comment by Waqar144** [comment]
Thank you very much for the profiling, it gives a better idea of what's happening on Mac, since I have never been able to build or try it on mac and I have no one to work with me interactively so that we can try to improve the performance on Mac.

The culprit in this case seems to be the native spell checker for Mac. Either it is being used wrong or there is something else. I am not sure.

I have given some possible solutions in #125, one of them being switching to Hunspell for Mac. The decision rests with @pbek

**Comment by Waqar144** [comment]
If anyone has better suggestions or ideas or is willing to help in any way, feel free to write please.

**Comment by pbek** [comment]
> I have given some possible solutions in #125, one of them being switching to Hunspell for Mac. The decision rests with @pbek

I'm ok with using hunspell, if the native spellchecker support doesn't work out... Or I wonder if you want to go multithreaded, @Waqar144

**Comment by Waqar144** [comment]
> > I have given some possible solutions in #125, one of them being switching to Hunspell for Mac. The decision rests with @pbek
> 
> I'm ok with using hunspell, if the native spellchecker support doesn't work out... Or I wonder if you want to go multithreaded, @Waqar144

I can try going multi-threaded again, there is some problems with handling signals across threads but I am sure there will be a way around it. The thing is, the numbers are too high for Mac, multi threading will speed up note loading but the spellchecker will remain terribly slow.

I will try jumping onto some obj-cxx project's irc channels and ask someone to take a look at our code, it's just 100 - 200 lines, maybe someone can help.

Also, the function `updateCurrentNote()` is causing performance issues as well. I wonder if there is a way to not call it for every block.

**Comment by pbek** [comment]
## 19.11.5
- did highlighting and spellchecking speed improvements and improved initial note
  loading performance (for [#1359](https://github.com/pbek/QOwnNotes/issues/1359), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by smokris** [comment]
> There now is a new release, could you please test it and report if it works for you?

Thanks!  I just updated to 19.11.5.  With spell checking disabled it's noticeably faster:

   - 159KB note — 0.25 seconds (Δ-0.75 seconds — nice!)

With spell checking and language detection enabled, there's some improvement, but large notes are still slow to load:

   - 3KB note — 1 second
   - 18KB note — 4 seconds (Δ-1 second)
   - 46KB note — 10 seconds (Δ-1 second)
   - 159KB note — 50 seconds (Δ-10 seconds)

> @smokris Out of curiosity, how many lines are there in the 159K note?

About 2,500 lines and 18,900 words.

**Comment by Waqar144** [comment]
@smokris 

Can you test the latest build and tell me if the performance is better? 
https://github.com/pbek/QOwnNotes/releases

**Comment by artmg** [comment]
With version `QOwnNotes - version 19.11.5 - Travis CI - build 4756` I performed an unscientific check which leads me to suspect that the performance is no better, but that it might actually be taking longer than before? However if you tell me which previous version to compare against I could try reloading it and doing measured performance tests if you prefer. Thanks

**Comment by Waqar144** [comment]
> With version `QOwnNotes - version 19.11.5 - Travis CI - build 4756` I performed an unscientific check which leads me to suspect that the performance is no better, but that it might actually be taking longer than before? However if you tell me which previous version to compare against I could try reloading it and doing measured performance tests if you prefer. Thanks

Can you try this one? Build 4764
https://github.com/pbek/QOwnNotes/releases/tag/dev-macosx-b4764-085701

**Comment by artmg** [comment]
@Waqar144 here are the test results

```
File A = 44,000 words in 300 lines (272k)
File B = 44,000 words in 4000 lines (274k)
Human measured timing rounded to half seconds and average of three

QOwnNotes - version 19.11.5 - Travis CI - build **4764**
No Spell Checking:    A neg   B neg (negligible, too quick to measure)
Specific Language:    A=9.5s  B=10s 
Automatically detect: A=16.5s B=17s 

QOwnNotes - version 19.11.5 - Travis CI - build **4756**
No Spell Checking:    A neg   B neg
Specific Language:    A=9.5s  B=10s 
Automatically detect: A=16.5  B=17s 

QOwnNotes - version 19.11.0 - Travis CI - build **4712**
No Spell Checking:    A neg   B=1s (noticeable!)
Specific Language:    A=9.5s  B=11s 
Automatically detect: A=16.5s B=18s 
```

On file B things improved from 19.11.0 to .5, but otherwise little difference.

**Comment by pbek** [comment]
My QOwnNotes Todo note still takes 11 sec with automatic spellchecking and only 2.5 sec when I set British English.

**Comment by pbek** [comment]
## 19.11.6
- attempted to improve macOS spellchecker performance
  (for [#1359](https://github.com/pbek/QOwnNotes/issues/1359), thank you @Waqar144)

**Comment by Waqar144** [comment]
> @Waqar144 here are the test results
> 
> ```
> File A = 44,000 words in 300 lines (272k)
> File B = 44,000 words in 4000 lines (274k)
> Human measured timing rounded to half seconds and average of three
> 
> QOwnNotes - version 19.11.5 - Travis CI - build **4764**
> No Spell Checking:    A neg   B neg (negligible, too quick to measure)
> Specific Language:    A=9.5s  B=10s 
> Automatically detect: A=16.5s B=17s 
> 
> QOwnNotes - version 19.11.5 - Travis CI - build **4756**
> No Spell Checking:    A neg   B neg
> Specific Language:    A=9.5s  B=10s 
> Automatically detect: A=16.5  B=17s 
> 
> QOwnNotes - version 19.11.0 - Travis CI - build **4712**
> No Spell Checking:    A neg   B=1s (noticeable!)
> Specific Language:    A=9.5s  B=11s 
> Automatically detect: A=16.5s B=18s 
> ```
> 
> On file B things improved from 19.11.0 to .5, but otherwise little difference.

I think you have a faster machine, at least faster than @smokris. That's why notes are loading faster.

Overall it shows that basically nothing has improved on the spell checking front. Not surprising.

As hard as it is, I think it's best to switch to Hunspell for now. NSSpellchecker is the best option(auto dictionary detection, native) , but unfortunately we can't get it to work well. 

@pbek maybe revert the commits? 

I will go ahead and enable Hunspell for now.

@sandsmark Sonnet on MacOS with NSSpellchecker plugin works really slow. It may be a bug on your side, or it maybe that we have done something wrong. I wanted to let you know and maybe you can help.

**Comment by pbek** [comment]
> maybe revert the commits?

which one? todays?
you can if they are serving no purpose, but I don't care for now if they aren't messing anything up

**Comment by pbek** [comment]
In any case, I just released 19.11.6.

**Comment by Waqar144** [comment]
> > maybe revert the commits?
> 
> which one? todays?

Yes.

> you can if they are serving no purpose, but I don't care for now if they aren't messing anything up

well then let's leave em in.

**Comment by artmg** [comment]
I'd vote to leave them in for now, until `hunspell` works properly to replace it. I had to create an excessively large file on purpose to perform these tests, so perhaps the incidence of this issue is marginal.

In the meantime, there is a simple workaround for this specific issue:

**Menu / Edit / Check Spell** - _untick_ this option to turn the new spelling feature back off

Please let me know if you want any more testing - Thanks

**Comment by pbek** [comment]
@Waqar144 is working on a Hunspell implementation. :) see #1372

**Comment by Waqar144** [comment]
> I'd vote to leave them in for now, until `hunspell` works properly to replace it. I had to create an excessively large file on purpose to perform these tests, so perhaps the incidence of this issue is marginal.

Hunspell is already in place and working quite well on other platforms so the Mac switch is just a few lines of code being moved.

Native support is the best, the user doesn't have to install any dictionaries or download/copy dictionaries. Things work out of the box but the performance is really terrible for now. (See @smokris benchmark, 50seconds for 159 KB file, crazy).

Meanwhile, I will keep trying to find someone who can work on this. Perhaps @pbek can create a help wanted issue for this. I have tagged the **Sonnet** maintainer and maybe he can help us get around this. I will also go ahead and file a bug report on the KDE bugzilla.
 
> In the meantime, there is a simple workaround for this specific issue:
> 
> **Menu / Edit / Check Spell** - _untick_ this option to turn the new spelling feature back off

> Please let me know if you want any more testing - Thanks

We always need testers and thank you so much for bearing with me through all this going back and forth. The spellchecker would never have reached this point without your support. Hunspell is working beautifully, but you will need to download dictionaries for it.

And if you still insist on having Native support, I can configure a separate build for you, and you can use that :wink:

**Comment by pbek** [comment]
> Perhaps @pbek can create a help wanted issue for this.

just create one, I'll tag it

**Comment by artmg** [comment]
> Hunspell is working beautifully, but you will need to download dictionaries for it.

So would it be possible to have the best of both worlds:

* the code for both sonnet and hunspell included in the build. 
   * That way the people with lots of small notes just have it working out of the box, 
   * and people with crazily long lists of things to do (😉) can follow...
* a clearly documented (or scripted) procedure to download 
* and enable (via preferences?) the hunspell dictionaries

**Comment by pbek** [comment]
> That way the people with lots of small notes just have it working out of the box,

It's crazy slow even for short notes...

> a clearly documented

http://docs.qownnotes.org/en/develop/spellchecking.html

> (or scripted) procedure to download

I wonder if we should implement a dictionary downloader... It would likely break at some time in the future because that dictionary pages are moving targets.

Most of it could also be done with the QOwnNotes scripting engine.

**Comment by artmg** [comment]
> It's crazy slow even for short notes...

Oh sorry, I don't have much of a problem - most of my Notes are under 30K and those are the large ones. 

Well perhaps the 'out of the box' Mac configuration could be Spell Checking on Demand (click a button). People who want it automatic could choose it (if their config is suitable) or install the hunspell dictionaries:

```
FOLDER=en
LANG=en_GB
pushd ~/Library/Spelling/
curl --remote-name-all https://github.com/LibreOffice/dictionaries/blob/master/$FOLDER/$LANG.dic https://github.com/LibreOffice/dictionaries/blob/master/$FOLDER/$LANG.aff
popd
```

In the longer run, if people don't like downloading dicts, might there perhaps be some way to perform the calls in the background –  asynchronously instead – if the editor's architecture permits? Otherwise simply spell check the paragraph the cursor is on!

**Comment by pbek** [comment]
> pushd ~/Library/Spelling/

This doesn't create the directory first, right?

**Comment by Waqar144** [comment]
> So would it be possible to have the best of both worlds:
> 
>     * the code for both sonnet and hunspell included in the build.
>       
>       * That way the people with lots of small notes just have it working out of the box,
>       * and people with crazily long lists of things to do (wink) can follow...

Mmm... Sonnet is the library we are using and Sonnet requires 'plugins' to do the actual spell checking. There are many plugins, one of them being Hunspell and another NSSpellChecker(native one). When I switched to Hunspell, I just changed the plugin. Now, we *can* use multiple backends(plugins) at the same time, and have both NSS and Hunspell working (only one would work at a time). But it's going to be quite a challenge having both plugins built statically into QOwnNotes and working correctly. It would have been easier if Sonnet was being used dynamically(we wouldn't be including any sonnet code in our own code) but then we would be sacrificing overall performance and making our jobs more difficult cross compiling things and fighting the poor Travis-CI.
 
>     * and enable (via preferences?) the hunspell dictionaries

You won't feel any difference. Everything will be the same. The only difference is that now you have to download dictionaries and place them in ~/Library/Spelling.



> I wonder if we should implement a dictionary downloader... It would likely break at some time in the future because that dictionary pages are moving targets.

@pbek Maybe we can host all dictionaries in one place, the QOwnNotes site? along with the docs. I don't think a builtin downloader is necessary for such a trivial job.

> Well perhaps the 'out of the box' Mac configuration could be Spell Checking on Demand (click a button). People who want it automatic could choose it (if their config is suitable) or install the hunspell dictionaries:

It sounds good, but this configuration is going to have to be exclusively for Mac(provided NSS can be statically built alongwith hunspell). It would however complicate things for the user. There would be an option to choose between the two. After choosing, a restart of the application would probably be necessary.

> In the longer run, if people don't like downloading dicts, might there perhaps be some way to perform the calls in the background – asynchronously instead – if the editor's architecture permits? Otherwise simply spell check the paragraph the cursor is on!

People in Windows land and some people in the Linux world have to download dicts to get spell checking to work.

Asynchronous sounds like a good idea, but if the actual logic is bad, or the thing you are trying to make asynchronous is slow, you will have red lines appearing after 5, 10 or maybe 20 seconds and who knows, maybe other problems. That's taking it easy. GUI has to stay in the main thread, the logic can be asynchronous though. If there is so much delay, I can't even imagine what it would be like.

**Comment by pbek** [comment]
> Maybe we can host all dictionaries in one place, the QOwnNotes site? 

We could upload them the "TuxFamily" (where the src-files are currently hosted)
Or just directly link to the current ones on the documentation page...

> I don't think a builtin downloader is necessary for such a trivial job.

Never underestimate the laziness of users. :laughing: Especially macOS users are very prone to want to get served everything on a silver tray :rofl:

**Comment by Waqar144** [comment]
> We could upload them the "TuxFamily" (where the src-files are currently hosted)
> Or just directly link to the current ones on the documentation page...

Sounds great!
 
> > I don't think a builtin downloader is necessary for such a trivial job.
> 
> Never underestimate the laziness of users. laughing Especially macOS users are very prone to want to get served everything on a silver tray rofl

:rofl:

**Comment by pbek** [comment]
## 19.11.7
- the macOS version of QOwnNotes now also uses the Hunspell spellchecker for more performance
  (for [#1359](https://github.com/pbek/QOwnNotes/issues/1359), thank you @Waqar144)
    - visit [QOwnNotes Spellchecking](http://docs.qownnotes.org/en/develop/spellchecking.html)
      for more information

**Comment by pbek** [comment]
maybe @artmg whats to volunteer updating https://github.com/pbek/QOwnNotes/blob/develop/doc/spellchecking.rst :wink:

**Comment by pbek** [comment]
Example links would be `https://raw.githubusercontent.com/LibreOffice/dictionaries/master/af_ZA/af_ZA.aff` and `https://raw.githubusercontent.com/LibreOffice/dictionaries/master/af_ZA/af_ZA.dic`

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by artmg** [comment]
Wow - 19.11.7 - build 4776 is instantaneous, at least to a meat-sack like me.

The code snippet above is exactly what I used to download - sorry I omited the `mkdir -p ~/Library/Spelling/`

**Comment by artmg** [comment]
Oh, sorry, but every word is underlined, so it's extremely quick, but totally inaccurate. Is there some config I need to set, or some logs I can check?

**Comment by Waqar144** [comment]
> Oh, sorry, but every word is underlined, so it's extremely quick, but totally inaccurate. Is there some config I need to set, or some logs I can check?

It's probably set to the wrong language. Did you  check Edit - > Languages?

**Comment by pbek** [comment]
> builtin downloader

see #1378

**Comment by pbek** [comment]
## 19.11.8
- there now is a new menu entry `Manage dictionaries` in the *Edit* menu to download
  and remove spellchecker dictionaries (for [#1378](https://github.com/pbek/QOwnNotes/issues/1378))
    - if you are missing a dictionary to download please look for it at
      [LibreOffice dictionaries](https://github.com/LibreOffice/dictionaries) and edit
      the [dictionary manager dialog](https://github.com/pbek/QOwnNotes/blob/develop/src/dialogs/dictionarymanagerdialog.cpp)
    - visit [QOwnNotes Spellchecking](http://docs.qownnotes.org/en/develop/spellchecking.html)
      for more information
- personal dictionary will now be stored in the portable data path when using QOwnNotes
  in portable mode (for [#1378](https://github.com/pbek/QOwnNotes/issues/1378), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by artmg** [comment]
Works perfectly for me - I downloaded the dictionary and it spells with no noticeable delay 😀 well done

**Comment by artmg** [comment]
> maybe @artmg whats to volunteer adding dictionary download links to all the languages

I was too 'lazy' to do this by hand, so I learned github api and jq instead:

```
# Yes you _can_ get info from a json with pure bash, 
but there lies insanity
# simply install the fast and dependency free `jq`
REPO=LibreOffice/dictionaries
SHA=`curl https://api.github.com/repos/$REPO/commits | jq -r '.[0].sha'`
curl https://api.github.com/repos/$REPO/git/trees/$SHA?recursive=1 | jq -r '.tree[].path' | grep -e '\.dic' -e '\.aff'
```
Just install the tiny `jq` and paste the above into your terminal to get the full listing of dictionary file paths on github/LibreOffice. To look up the IETF language codes  http://www.lingoes.net/en/translator/langcode.htm is a reasonable start

**Comment by Waqar144** [comment]
> > maybe @artmg whats to volunteer adding dictionary download links to all the languages
> 
> I was too 'lazy' to do this by hand, so I learned github api and jq instead:
> 
> ```
> # Yes you _can_ get info from a json with pure bash, 
> but there lies insanity
> # simply install the fast and dependency free `jq`
> REPO=LibreOffice/dictionaries
> SHA=`curl https://api.github.com/repos/$REPO/commits | jq -r '.[0].sha'`
> curl https://api.github.com/repos/$REPO/git/trees/$SHA?recursive=1 | jq -r '.tree[].path' | grep -e '\.dic' -e '\.aff'
> ```
> 
> Just install the tiny `jq` and paste the above into your terminal to get the full listing of dictionary file paths on github/LibreOffice. To look up the IETF language codes http://www.lingoes.net/en/translator/langcode.htm is a reasonable start

That's awesome and some not very easy to understand scripting :laughing: 
Great work @artmg :+1:

**Comment by artmg** [comment]
> That's awesome and some not very easy to understand scripting 😆

I added some comments to help

**Comment by pbek** [comment]
## 19.11.9
- did some optimization for spellchecking auto detect mode
  (for [#1359](https://github.com/pbek/QOwnNotes/issues/1359), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Waqar144** [comment]
@pbek isn't the initial performance issue solved on mac now since we have switched to hunspell?

**Comment by pbek** [comment]
You are right. Or can we also already close?

**Comment by Waqar144** [comment]
> You are right. Or can we also already close?

We should close this. Performance stuff will keep happening, but the current issue is now solved.
