### ISSUE TITLE
Feature Request: Limit running QOwnNotes instances to 1 

### ISSUE THREAD

**Issue by xenithorb** [pbek/QOwnNotes#136]
Preferably a checkbox that I would most likely expect to see in Settings -> General. 

- [ ]  Allow only one instance of QOwnNotes to run

I thought at first that this was the default behavior when I had the tray icon enabled, but discovered later when I looked at the expanded tray that I had 5 instances open!

**Comment by pbek** [comment]
I will see how this can be made possible.

**Comment by pbek** [comment]
Did you start QOwnNotes manually multiple times or did you just click the tray icon multiple times?
On which OS did you work?

**Comment by Loelo** [comment]
Hi  I have the same problem : I open QOwnNote with a keyboard command that trigger /usr/bin/QOwnNotes opening each time a new instance.
(I use  with Autokey (on Linux, Debian 8, XFCE). But XFCE shortcut does the same.)

**Comment by pbek** [comment]
@Loelo, do you have the QOwnNotes tray icon turned on?

**Comment by Loelo** [comment]
Yes and I have as much tray icons visible as opened instances.

**Comment by pbek** [comment]
That's strange...

**Comment by Marsup** [comment]
FWIW same behavior on KDE, with or without tray icon. Running it from the K menu.

**Comment by pbek** [comment]
Thank you for reporting, that's the default behaviour of all programs. If you start them a 2nd time they run a 2nd time. But I'm already working on a single process feature. tricky, tricky...

**Comment by xenithorb** [comment]
I would agree with you that your program exhibits the typical behavior of all programs, except for that fact that sending it to the tray *usually*, but not always, implies that it also will only run one instance. Mainly because it's the very reason you're sending it to the tray in the first place (to keep a persistent instance of the program) 

Thanks for your work on this and in general, greap app love what you're doing!

**Comment by pbek** [comment]
Thank you for your kind words, @xenithorb 

Back to my question to you 6 days ago:
Did you start QOwnNotes manually multiple times or did you just click the tray icon multiple times?
On which OS did you work?

**Comment by pbek** [comment]
In the just released v16.04.14 there is a setting to disallow multiple instances to start. Can you all please test if it works for you?

**Comment by Marsup** [comment]
It seems to do the trick for me. If I may ask, could you also detect whether the window is minimized and show it if it's the case ? Currently it's just highlighting it in the task bar.

**Comment by Loelo** [comment]
Hi, thanks. Just tested. No change here : still multiple instances. (Debian 8.4, XFCE 4.10 (but Xfwm (the Xfce window manager at 4.12).

**Comment by pbek** [comment]
@Marsup, I will see if I can change that.
@Loelo, thank you for testing. :)

**Comment by xenithorb** [comment]
Works, thanks! :)

**Comment by pbek** [comment]
@Marsup in v16.04.15 when in single application mode the app will now come up again if it was   minimized and started a second time. (tested unter Ubuntu 15.10 with KDE), can you please report back if it works for you when the version is released?

**Comment by pbek** [comment]
v16.04.15 is out now

**Comment by Loelo** [comment]
Hello thank you for v16.04.15 !
I noticed a regression : the pref window width is too wide again as it was before.

A saw a few corrections I will add to the french translation.

**Comment by pbek** [comment]
@Loelo I can't reproduce a problem with the settings dialog, where did you get it? Did you maximize it by accident?
Thanks for your hard work translating QOwnNotes!

**Comment by Loelo** [comment]
![23](https://cloud.githubusercontent.com/assets/11534708/14722050/f4450de2-0809-11e6-991c-5091468821ae.jpg)
This is what I use to see when opening settings (this screenshot show all the width of my 1024pix screen). The window is too wide (I would say 100 to 150 pixel too wide) and can not be reduced (this is the minimum window size). So I have to move the window to be able to click on the OK button. 
But with v16.04.14  the setting window was just fine, around 950 pixel wide.
And with v16.04.15 the setting window has gone wide again.
This not a big problem though.

**Comment by pbek** [comment]
That really is strange. I will try to find out what the cause of this. Thanks a lot for the report!

**Comment by pbek** [comment]
I did some fixes to the settings dialog to support small screen widths again. They will be released with v16.04.16. The strange thing is that in addition I try to resize the dialog to the smallest possible size when the dialog is opened but that doesn't work everywhere...

**Comment by pbek** [comment]
@Loelo, v16.04.16 is now out. Does the width of the settings dialog work for you now?

**Comment by Loelo** [comment]
Hi ! Thanks for v16.04.16 ! I like the new icon ☺
However no changes in the width of the setting dialog. Still too wide.
If you could send me a .deb of the v16.04.14 I could check again if the width was smaller in this version as I remember. (because the could no find older .deb at https://build.opensuse.org/package/binaries/home:pbek:QOwnNotes/desktop?repository=Debian_8.0)

**Comment by pbek** [comment]
Thank you for testing. Yes, nice icon. :) It was done be Alex from the KDE V Design Group. 🎉 
Here is the past release, built on travis: <https://github.com/pbek/QOwnNotes/releases/tag/linux-b1437-165106>

**Comment by Loelo** [comment]
Thanks, I had found the past releases .deb on github, but they do not work on my system. Installation is ok but the app does not lauch
`bash: /usr/bin/QOwnNotes: cannot execute binary file: Erreur de format pour exec()`
(wrong format for exec)

**Comment by pbek** [comment]
Too bad. Can you measure the minimum size of the settings dialog on your screen? (like with kruler)

**Comment by Loelo** [comment]
Hi, actual min size is around 1140 pix. In v16.04.14 the width was around 950 pix which was fine. (my screen is 1024pix wide). Just tested with an eeepc and debian 8.4 (screen 1024x600) : the setting dialog is too wide as well.

**Comment by pbek** [comment]
Mine is at about 890px in Manjaro Linux under KDE at version 19.04.16. What desktop environments are you using?

**Comment by Loelo** [comment]
Debian 8.4, XFCE 4.10

**Comment by pbek** [comment]
Now I see what's "wrong". I was testing it in English and German and you were using it in French. :)
In French I measure about 1018px width because of some long translations. I guess some buttons and checkboxes (the text can't wrap there) might be the problem. Is it possible to save some characters there in the French translation?
It's usually the same game in German, but this time we are at a mere 920px there.

**Comment by Loelo** [comment]
Ok, thanks, I'll shorten the long translation…

**Comment by Loelo** [comment]
Can the problem (long translation) be in another tab than the first one ?

**Comment by pbek** [comment]
Yes, in every tab.

**Comment by Loelo** [comment]
I noticed that the window can be reduced with all other tabs than "folder" and "task" (tested in english and french). If I reduce the window size and click on one of these two tabs the windows resize up to their min size: strange...

**Comment by pbek** [comment]
Strange, I can't manage to reduce the width any further in every tab.

**Comment by Loelo** [comment]
![capture d ecran - 25042016 - 18 10 19](https://cloud.githubusercontent.com/assets/11534708/14790324/11fc05b6-0b11-11e6-90e0-7c378b4d0e5c.png)
Some text does wrap well, others do not.

**Comment by pbek** [comment]
I think to really get to the root of this you would need to play around with the settings dialog in Qt Creator... <http://www.qownnotes.org/installation#building>

**Comment by Loelo** [comment]
I'll try that depending on the size of qtcreator.

I have shorten a few translation to see how it goes in the next version.

**Comment by pbek** [comment]
Meanwhile v16.04.17 got released (in case some strings go shorter now)..

**Comment by Loelo** [comment]
Hi, my translation changes were not selected on crowdin. It appears that I can not change (and thus shorten) a translation that has been approved by you. If you agree, maybe there is some settings to change so that I could.

**Comment by pbek** [comment]
I would love to make you some kind of manager of the French language, but I found no way to do this in Crowdin. :(

I approved those where the string would be different than it was before. Can you link some translations that you have shortened?

**Comment by Loelo** [comment]
I guess the change you made ih crowdin made me some kind of manager (I had an email notif about that) and the fact is that I can now change the translations by approving a new ones. I'll have a look at that tonight. Now I have to go to work. Have a nice day !

**Comment by pbek** [comment]
Yeah, I tried for a second if I could make you manager over just a language, which didn't work. :/
I approved some more translations from you I found on <https://crowdin.com/project/qownnotes/fr/activity> but most of them were the same as the old translation (at least I could see no difference).

Have a great day at work and thank you!

**Comment by Loelo** [comment]
Hi, so I had shortened a few french sentences (the ones visible in the settings) and they are changed in the new version, but the setting window is still too large with the french translation (it is ok with the english text) and I can not find where the problem come from. Hopefuly this is not a big issue.

**Comment by pbek** [comment]
Thank you for helping! I think to really tackle the problem you would need to install QtCreator and build QOwnNotes yourself...

**Comment by Loelo** [comment]
Yes, but my computer has a small hard drive and I also fear to clutter my system with Qtcreator and its building dependencies. I could do this in a virtual machine, but I do not find it worth the time. The strange thing is that all other translations do not show this problem.

**Comment by pbek** [comment]
You are right, QtCreator is huge...
Let's leave it as it is, thank a lot for your help!
