### ISSUE TITLE
Right-click context menu does not appear unless note is selected

### ISSUE THREAD

**Issue by maqp** [pbek/QOwnNotes#1361]
1. If the note directory selected is empty, right-clicking on the empty space won't open the context-menu at all
![](https://i.imgur.com/lrkcdBe.png)

2. If notes exist in the selected directory, a note must be clicked and highlighted before the right-click context menu on empty space works.

a) When note directory is selected and note is not selected:
![](https://i.imgur.com/z7AIdaR.png)

Right-clicking the empty space will only lightly highlight the existing note but not open context menu:

Left-clicking the empty space will also only lightly highlight the existing note, and right-clicking on empty space after that does not open context-menu. 

![](https://i.imgur.com/xJmIfDO.jpg)
(Side note: I'm taking photos when screenshot utility alters the final result, in this case shift+PrintScrn makes the light highlight disappear)

b) However, when a note is first selected by clicking on it, right-clicking the empty-space correctly opens the context-menu

![](https://i.imgur.com/MgWHnlq.jpg)

**Comment by pbek** [comment]
@Waqar144 😄

**Comment by Waqar144** [comment]
Ahh yes.
Will be fixed today.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by maqp** [comment]
@pbek It's working perfectly! Thank you so much :smile:

**Comment by pbek** [comment]
Great, thank you for testing!
