### ISSUE TITLE
Unify Note folder and Note list panels to a single tree panel

### ISSUE THREAD

**Issue by brx75** [pbek/QOwnNotes#1366]
This is a feature request.
It would be nice to have a single tree panel showing both folders and notes files.
Showing subfolder as child of the parent NOTE (against actually being child of parent FOLDER). 
Zim Note taking app uses this kind of behavior. 
This feature makes navigation through your knowledge base saved as text notes faster.

**Comment by pbek** [comment]
Please see #790

**Comment by pbek** [comment]
You can also provide feedback there...
