### ISSUE TITLE
Feature request: Tag with hierarchical structure

### ISSUE THREAD

**Issue by jakekei** [pbek/QOwnNotes#137]
Hello,
I just tried QOwnNotes and found that it's a nice simple program with markdown support (syntax highlight and instant render).

I have been using gmail to organize my notes for a few years (cross platform with internet access) and believe that I can use QOwnNotes instead.  However, I wonder is it possible to have tag with hierarchical structure similar to the gmail tag function?  This will be helpful when you are accumulating notes for serious use of QOwnNotes.

Best,
Jake

**Comment by pbek** [comment]
I was planning to "upgrade" the tag functionality from a "list" to a "tree" in some near future release.

**Comment by pbek** [comment]
@jakekei, version 16.04.15 is out now, could you please test it and report back?

- tags can now have a hierarchical structure
	- there is a number right of each tag name in the tag tree that indicates how many notes are tagged with the tag
	- you are able to search for tags in your tag tree with the `find or create tag` line edit by typing in it
		- if you press enter a new tag with the content of the line edit is created at the root level
	- you are able to move selected tags to an other tag by right-clicking on them and select *Move tags to...*
	- you are able to remove selected tags by right-clicking on them and select *Remove tags*
	- you are able to edit the name of selected tags by right-clicking on them and select *Edit tag* or double-clicking on it
	- you are able to tag selected notes by right-clicking on the notes and select *Tag selected notes with...*
	- you are able to remove a tag from selected notes by right-clicking on the notes and select *Remove tag from selected notes...*
	- the name of a tag has to be unique for its parent
		- so you can create tags with the same name under different tags
		- you cannot move a tag to an other tag if a tag with the same name already exists there

**Comment by jakemkc** [comment]
It works as expected, thanks!

**Comment by pbek** [comment]
Thank you for reporting back!

**Comment by dskopa-softdev** [comment]
Guys, what is the point of having hierarchical tags without actual hierarchical functionality? Don't you expect clicking on the top tag cause selection of all notes tagged with child tags as well? As I understand, current implementation it's only about representation of the tag list panel. But the reason people usually use hierarchy is to utilize aggregation.

Let's say I have a tag structure: Animals > Mammals > Wolfs. What I expect, is when I tag some note with a Wolf tag, I can find it later using Animals tag. And I assume I don't have to put the whole chain of parent tags to the note to be able to do this. Also tag counter in the tags panel (next to the tag name) could aggregate nested counters.

I know, SQL doesn't fit well for tree structures but it's still possible to fetch all nested children tags in a single sql query quite fast if we use [nested sets](https://en.wikipedia.org/wiki/Nested_set_model).

Another option is to use CTE (it's supported by recent sqlite as i know) to fetch tag tree branches.

What do you think?

**Comment by pbek** [comment]
> What I expect, is when I tag some note with a Wolf tag, I can find it later using Animals tag. And I assume I don't have to put the whole chain of parent tags to the note to be able to do this. Also tag counter in the tags panel (next to the tag name) could aggregate nested counters.

Something similar is currently already done for sub-folders.
You can create a new feature request for that if you want...

**Comment by pbek** [comment]
## 17.12.3
- you now can choose to show all notes of a tag including the notes of their children-tags
    - there is a new setting `Show all notes of a tag including the notes of their children-tags` in the *Panel settings*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by dskopa-softdev** [comment]
@pbek wow, you're fast! Now it works exactly as I meant, thank you!

**Comment by pbek** [comment]
Great, thank you for testing!
