### ISSUE TITLE
Navigate search results in note sub-folders

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#1371]
#### Expected behaviour
After a search it should be possible to navigate the results.

#### Actual behaviour
The results are lost when selecting a result that is in a subdirectory. The list of results is replaced by a list of items from that subdirectory.

#### Steps to reproduce
Set the following option:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/5956570/68319464-a9c0ea00-00be-11ea-8bd4-c0a33eb54973.png">
- search
- select search result (that lives in a subdirectory)
- see the list of results change to a list of items in the subdirectory

**Comment by sanderboom** [comment]
>  Maybe there is a way around it, will not be easy and another source for regressions.

Other options (?):
- navigate to the subfolder, but only show items that comply with the search, and make it easy to go back to the global search results (clicking the top 'directory' but keeping the search terms)
- open a temporary panel for search results that stays in view, and can be closed manually

**Comment by pbek** [comment]
## 19.11.8
- automatic switching of note subfolders is now prevent if the setting to show notes in
  note subfolders recursively is enabled (for [#1371](https://github.com/pbek/QOwnNotes/issues/1371))
    - this is still experimental and might have side effects

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by sanderboom** [comment]
Looks good, thanks!

**Comment by pbek** [comment]
Great, thank you for testing!
