### ISSUE TITLE
Feature request: support online translation

### ISSUE THREAD

**Issue by data-man** [pbek/QOwnNotes#1374]
Firstly, many thanks for the great app!

Back to the topic: e.g. via [QOnlineTranslator](https://github.com/crow-translate/QOnlineTranslator).

**Comment by pbek** [comment]
> Firstly, many thanks for the great app!

Thank you for your kind words!

> support online translation

Thank you for your suggestion, can you please elaborate on what you mean by "support".
You currently can write scripts that are able to for example search for the selected word on a web service of your choice... or fetch data from a web service.

See http://docs.qownnotes.org/en/develop/scripting/README.html

**Comment by data-man** [comment]
> You currently can write scripts

Sure, it's most awesome feature for me!
But it's hard for non-programmers.

> fetch data from a web service

Should user (especially non-programmer) study web service's API?
BTW if QOwnNote will provide universal API via scripting, it will be simpler.

**Comment by pbek** [comment]
>  But it's hard for non-programmers.

That's why there is the scripting repository. One can just create a script and make a pull request there so everyone can install it from inside QOwnNotes.

>  BTW if QOwnNote will provide universal API via scripting, it will be simpler.

What is a "universal API" in your view?

> Thank you for your suggestion, can you please elaborate on what you mean by "support".

And I still don't know what you want to achieve... :) What are you expecting to happen in QOwnNotes in the user interface?

**Comment by data-man** [comment]
> What is a "universal API" in your view?

Something like:
```qml
script.translate(fromLanguageName, toLanguageName, text)
```
It would also be nice to have the ability to enumerate available languages.

> What are you expecting to happen in QOwnNotes in the user interface?

E.g. via context menu:
_Translate selected text (or whole note) to/from language._

**Comment by pbek** [comment]
You currently can do that all by directly querying for example http://translate.googleapis.com/translate_tts with http://docs.qownnotes.org/en/develop/scripting/README.html#downloading-an-url-to-a-string and showing it in the auto-completer with http://docs.qownnotes.org/en/develop/scripting/README.html#autocompletionhook

**Comment by pbek** [comment]
The library doesn't seen too complicated to integrate but it seems it will break our Windows XP build (mingw53_32) with its MinGW 7 + requirement. :frowning_face:

**Comment by pbek** [comment]
And I would need to conjure up cmake support...

**Comment by data-man** [comment]
Ok, thanks!
I'll be back. :-D
