### ISSUE TITLE
插入图片我觉得可以改善

### ISSUE THREAD

**Issue by ctlddey** [pbek/QOwnNotes#1375]
基于html格式的话，把日记中的图片显示出来应该会更好一些

**Comment by pbek** [comment]
I'm sorry. We currently can only support issues in English :grimacing:

**Comment by pbek** [comment]
Google says: I can improve the insertion of the picture. Based on the html format, it should be better to display the images in the diary.

Can you please clarify.

**Comment by Waqar144** [comment]
Maybe he wants to contribute😉

**Comment by ctlddey** [comment]
@Waqar144 oh，I'm sorry

**Comment by pbek** [comment]
I will close this issue until there is more information. :grin:
