### ISSUE TITLE
Preview only mode

### ISSUE THREAD

**Issue by Waqar144** [pbek/QOwnNotes#1376]
### Explanation
A preview only mode where text editor is hidden and only the preview is visible.

### Use case: 
The preview is much better for reading notes than the editor. If someone is going through their past notes, preview only mode could be a better option

**Comment by pbek** [comment]
You can already do that. You need to disable the `Use the note edit panel as fixed central widget to be resized if the window or other panels are resized` setting and just hide the note edit panel. If you create a new workspace first you can toggle between the layouts. If you unlock the panels you can also drag them around.

**Comment by pbek** [comment]
If you want that automated you could do so by implementing it in the layout settings.

**Comment by pbek** [comment]
Make sure to add a nice screenshot if you do so. :laughing:

**Comment by Waqar144** [comment]
> If you want that automated you could do so by implementing it in the layout settings.

Yes! like an `eye` icon button in the toolbar to quickly toggle it.

**Comment by pbek** [comment]
> Yes! like an eye icon button in the toolbar to quickly toggle it.

No no, you need a restart of you use the layout settings in the settings dialog. They are just for the initial setup of the application and then later if you are not aware of what QOwnNotes is capable.

There is a select box in the toolbar to switch between workspaces and there is a button to toggle between the last workspace and the current.

**Comment by Waqar144** [comment]
> > Yes! like an eye icon button in the toolbar to quickly toggle it.

Ah I was talking about adding a button to quickly do it. 

> No no, you need a restart if you use the layout settings in the settings dialog. They are just for the initial setup of the application and then later if you are not aware of what QOwnNotes is capable.

> There is a select box in the toolbar to switch between workspaces and there is a button to toggle between the last workspace and the current.

Ahhh just what I wanted! 

Oh man, I love this app more and more everyday! 😍

**Comment by Waqar144** [comment]
> If you want that automated you could do so by implementing it in the layout settings.

Implementing it would be a repetition of things I think. 

However I can give a Screenshot of what I just did. It's looking awesome 🤣

**Comment by pbek** [comment]
> Ahhh just what I wanted!

And seems to be hidden too well...

**Comment by pbek** [comment]
> Implementing it would be a repetition of things I think.

There surely will be no extra button. I started with manually layout different layouts and have extra "modes" for them, but people never stopped asking for new ones. Then I implemented dock widgets...

If you want new users to immediately be able to use a "preview only layout" the layout settings is the place to add it.

> However I can give a Screenshot of what I just did. It's looking awesome rofl

Sure. :grin:

**Comment by Waqar144** [comment]
> And seems to be hidden too well...

Takes a while to get used to +also because i never read the docs till i am stuck :laughing: 
There is a way for everyone. Too many options to make it work the way you like.

![image](https://user-images.githubusercontent.com/7696024/68410168-1cf35a80-01aa-11ea-8145-5e330a1e5fae.png)


Black mac
:stuck_out_tongue_winking_eye:

**Comment by pbek** [comment]
Looking good!

**Comment by pbek** [comment]
>  i never read the docs till i am stuck

what docs? there are none! :laughing:

**Comment by Waqar144** [comment]
> > i never read the docs till i am stuck
> 
> what docs? there are none! laughing

Really? :laughing: 
I thought there were docs for everything, like we made the docs for spellchecker :thinking:

**Comment by pbek** [comment]
> I thought there were docs for everything

and that's another problem, the docs that exists are spread everywhere :laughing:

**Comment by Waqar144** [comment]
> > I thought there were docs for everything
> 
> and that's another problem, the docs that exists are spread everywhere laughing

Maybe we should try and combine them. Make a small booklet or something like a user guide

**Comment by pbek** [comment]
It will be hard to combine them with https://www.qownnotes.org/changelog/QOwnNotes, https://www.qownnotes.org/Knowledge-base, https://www.qownnotes.org/shortcuts/QOwnNotes and all the other stuff. :grimacing:

**Comment by Waqar144** [comment]
> It will be hard to combine them with https://www.qownnotes.org/changelog/QOwnNotes, https://www.qownnotes.org/Knowledge-base, https://www.qownnotes.org/shortcuts/QOwnNotes and all the other stuff. grimacing

Maybe we shouldn't combine them but write everything from scratch. It doesn't have to cover all the features and settings, but only the basic stuff so that the user knows where to find things easily.

**Comment by pbek** [comment]
https://github.com/pbek/QOwnNotes/tree/develop/doc is all yours :grin:

**Comment by Waqar144** [comment]
It will be a laborious and slow and also boring task :rofl:

**Comment by stevenfang1997** [comment]
> You can already do that. You need to disable the `Use the note edit panel as fixed central widget to be resized if the window or other panels are resized` setting and just hide the note edit panel. If you create a new workspace first you can toggle between the layouts. If you unlock the panels you can also drag them around.

Would you plan to make `Use the note edit panel as fixed central widget to be resized if the window or other panels are resized` and preview only mode compatible? If there is only preview panel without note edit panel, all panels just mess up together.

**Comment by pbek** [comment]
> Would you plan to make Use the note edit panel as fixed central widget to be resized if the window or other panels are resized and preview only mode compatible?

No sorry, the central widget cannot be turned off if there is a central widget.

> If there is only preview panel without note edit panel, all panels just mess up together.

How do they "mess up"?

**Comment by stevenfang1997** [comment]
Thanks for your reply.

> How do they "mess up"?

If I enable `Use the note edit panel as fixed central widget to be resized if the window or other panels are resized`, a note edit panel just appear in the "preview only" workspace and there is no way to turn the note edit panel off. But yeah I understand, you have to have a note edit panel if you want to enable this setting.

**Comment by stevenfang1997** [comment]
> > a note edit panel just appear in the "preview only" workspace and there is no way to turn the note edit panel off.
> 
> You should be able to turn it off like every other panel in the _Window / Panels_ menu. And you can create different workspaces with the note edit panel turned off and on.

Actually I can't. The note edit setting under "window" just disappears for some reasons. This setting will reappear when you recreate new workspaces.

**Comment by pbek** [comment]
That's strange, it should only be disabled if `Use the note edit panel as fixed central widget` is activated.
If you can reproduce that the setting is off and the panel item is deactivated please open an issue.
