### ISSUE TITLE
Question about Shift-Enter in editor

### ISSUE THREAD

**Issue by uffejakobsen** [pbek/QOwnNotes#1377]
Question:
When pressing Shift-Enter in editor - it adds two spaces at the existing cursor position followed by Enter.

Is that intentional ?

**Comment by pbek** [comment]
Yes, it forces a new line in markdown.

**Comment by uffejakobsen** [comment]
Ahhh, yes ok - thanks :-)

IMHO: not the best choise by the inventors of markdown syntax - most normal programming/code/text editors will strip trailing spaces on save - hence destroying parts of the markdown layout. But that is not really changeable that the syntax is established now.

I'm closing this question :-)
