### ISSUE TITLE
Spellchecker dictionary download manager

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1378]
There will be a dialog for downloading dictionaries.
The dictionaries will be stored in the application's data path so they also will be available in portable mode.

**Comment by pbek** [comment]
@Waqar144, does our spellchecker currently store some data locally? If yes, we need to make it so that it does it in the data path, so the rest of the system doesn't get "polluted" in portable mode.

**Comment by Waqar144** [comment]
> @Waqar144, does our spellchecker currently store some data locally? If yes, we need to make it so that it does it in the data path, so the rest of the system doesn't get "polluted" in portable mode.

I guess  *personal dictionary* is stored locally at ~/.hunspell_langCode
it could be stored anywhere else

**Comment by pbek** [comment]
Good question, are those shared with other applications like LibreOffice?

I guess at least in portable mode (`Utils::Misc::isInPortableMode()`) they must reside in a directory in `Utils::Misc::appDataPath()`.

**Comment by Waqar144** [comment]
> Good question, are those shared with other applications like LibreOffice?

- LibreOffice stores its *personal dictionary* data in ~/.config/libreoffice on linux. On windows/Mac it will be something similar.
- Chrome/ Firefox also store their data in separate places. I just tried and they are not detecting the words I added to my personal hunspell dict created using QOwnNotes/Kde apps
- In KDE land, since everything is using sonnet(i think), the personal dictionary is shared between all kde apps, as well as QOwnNotes.
- In Gnome land, I can't be sure, since I haven't tested it. I think it doesn't using hunspell, maybe enchant or something else. So I am 90% sure, QOwnNotes's personal dicts aren't shared there, unless of course you install some kde app.

> I guess at least in portable mode (`Utils::Misc::isInPortableMode()`) they must reside in a directory in `Utils::Misc::appDataPath()`.

Sounds good. Because what's the use of *personal dict* if you are not going to carry it with you. So, yeah I agree, in portable mode the path for personal dict should be set using `portableDataPath()`

**Comment by pbek** [comment]
> Sounds good. Because what's the use of personal dict if you are not going to carry it with you. So, yeah I agree, in portable mode the path for personal dict should be set using portableDataPath()

Could you do that please? :smile_cat:

**Comment by Waqar144** [comment]
> > Sounds good. Because what's the use of personal dict if you are not going to carry it with you. So, yeah I agree, in portable mode the path for personal dict should be set using portableDataPath()
> 
> Could you do that please? smile_cat

Okay let's do this. :wink:

**Comment by pbek** [comment]
## 19.11.8
- there now is a new menu entry `Manage dictionaries` in the *Edit* menu to download
  and remove spellchecker dictionaries (for [#1378](https://github.com/pbek/QOwnNotes/issues/1378))
    - if you are missing a dictionary to download please look for it at
      [LibreOffice dictionaries](https://github.com/LibreOffice/dictionaries) and edit
      the [dictionary manager dialog](https://github.com/pbek/QOwnNotes/blob/develop/src/dialogs/dictionarymanagerdialog.cpp)
    - visit [QOwnNotes Spellchecking](http://docs.qownnotes.org/en/develop/spellchecking.html)
      for more information
- personal dictionary will now be stored in the portable data path when using QOwnNotes
  in portable mode (for [#1378](https://github.com/pbek/QOwnNotes/issues/1378), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Waqar144** [comment]
Working great!

**Comment by pbek** [comment]
Awesome. It was a lot of work. 😅
But OBS is still broken from a PR 🙁😁

**Comment by data-man** [comment]
> 19.11.8-1

Broken in AUR? :(

**Comment by Waqar144** [comment]
@data-man 
@pbek 
Just fixed it. Should build without any problems.

**Comment by Waqar144** [comment]
> > 19.11.8-1
> 
> Broken in AUR? :(

It shouldn't be broken in AUR, which distro are you on? Arch? Manjaro?

**Comment by Waqar144** [comment]
> Awesome. It was a lot of work. sweat_smile
> But OBS is still broken from a PR slightly_frowning_facegrin

I will send in a PR with more dictionaries later. The list is too small for a big program like QON :stuck_out_tongue_winking_eye:

**Comment by data-man** [comment]
@Waqar144 
> which distro are you on?
Arch with yay.

Can be PKGBUILD changed for obtaining sources from Github?

**Comment by Waqar144** [comment]
> Arch with yay.
> 
> Can be PKGBUILD changed for obtaining sources from Github?

Can you tell me the error you get when compiling?
I am on Manjaro, this can't possibly fail to build on Arch.

**Comment by data-man** [comment]
> Can you tell me the error you get when compiling?

No, error isn't during compiling!

yay qownnotes

> 2 aur/qownnotes 19.11.8-1 (+88 4.04%) (Installed: 19.11.7-1)

> ERROR: Failure while downloading https://download.tuxfamily.org/qownnotes/src/qownnotes-19.11.8.tar.xz

**Comment by pbek** [comment]
> The list is too small for a big program like QON

I even updated http://docs.qownnotes.org/en/develop/spellchecking.html to encourage people to do pull requests with languages. :smile:

**Comment by pbek** [comment]
> ERROR: Failure while downloading https://download.tuxfamily.org/qownnotes/src/qownnotes-19.11.8.tar.xz

lately there are more and more troubles with uploading to tuxfamily :cry: 
should work now
