### ISSUE TITLE
saved searches

### ISSUE THREAD

**Issue by dh-connect** [pbek/QOwnNotes#138]
maybe something for a future version, I've noticed that I always look for notes by searching for certain keyword in the notes search bar, now I can tag these notes, but I would be great to have something like a saved search or a search history which always have the latest results on certain keywords so it's easier to find them, maybe also with a few more search options like a logical operator "search for keyword1 and keyword2 and not keyword3"

**Comment by pbek** [comment]
Wouldn't a search history pile up very fast with keywords one possibly doesn't need...
As for the logical operators, I fear without a search index system that would be hard to achieve and also slow, I would have to test that...

**Comment by dh-connect** [comment]
yes that's true maybe it's better to save certain searches you realy need and keep it simple, 

hey when we talk about to simplify the search, the two search bars confuse me the one above the note list searches in the notes keywords and the notes text and the one below the notes text search only within a selected note, right? I only use the global one because this ones also highlightes all the matches in the notes text which I like, I think a comined field would be easier to understand, the jump function (to jump from match to match can be also integrated in the other one, you click with cursor in a note and outgoing from this mark you jump to the next one and if you reach the last match in one note you jump to the first match in the next note

**Comment by pbek** [comment]
- the note search line above the note list does a global search and you are able to create new notes with it
    - only one search result per note will be highlighted
- the search line on the bottom of a note (you only get it by pressing `Ctrl + F`) searches in a note
    - you can jump forward between spots where the word you entered where found

In my eyes they are very different and I wouldn't want to use the mouse to quickly search for something in the current note. Can you please try to make it clearer to me how your suggestion would improve on that. :)

**Comment by dh-connect** [comment]
or may place the search bar for the notes text right above the note text next to the other search bar, so they are all in one line 

the search bar above the note list highlightes all the search words in the notes (what I like), i miss this function in the notes text search that's why i don't use it, because it is much better to see all the search word highlighted 

in the beginning I though the search funtion above the notes list only searches in the notes head lines and maybe tags, but it does a full text search, so besides the missing jump forward this is all you really need.

**Comment by pbek** [comment]
I will test how it will look above the note edit...

**Comment by pbek** [comment]
From the v16.06.2 changelog:
- you now can **search for multiple words** in notes
    - by default notes that contain every single word will be found, `word1 
      word2` will find all notes that are containing `word1` and `word2`
    - you can search for longer texts by using quotes, `"this word1" word2` 
      will find all notes that are containing `this word1` and `word2`
- there now is a **search history**
    - your last 100 note searches will be stored and you can access them as 
      completer in the note search line edit
    - for every note folder a different search history will be kept
    - your whole search history will be shown if you press the <kbd>Down</kbd> 
      button in the note search line edit

**Comment by pbek** [comment]
v16.06.2 is now released, can you please test it and report if the new features work for you
