### ISSUE TITLE
organize tags

### ISSUE THREAD

**Issue by dh-connect** [pbek/QOwnNotes#139]
I would like to organize my tags because I have 1 tag which has too many notes, so it would be great to rename a tag and also select a list of notes and delete a certain tag, this way I could split my notes to 2 tags

**Comment by pbek** [comment]
Thank you for your suggestion. It's already possible to rename tags. Just double click on it.
As for deleting of tags in notes... sounds like a good idea.

**Comment by dh-connect** [comment]
wow cool, i only tried the context menue with a right click

**Comment by pbek** [comment]
In the just release version 1.4.3 you can now **remove a tag from multiple notes** by selecting them, then right-clicking on the notes and selecting *Remove tag from selected notes...*. Can you please test that and report back?

**Comment by pbek** [comment]
any feedback, @dh-connect ?

**Comment by dh-connect** [comment]
works good, by the way, how do I delete a tag that I don't need anymore ?

**Comment by pbek** [comment]
Thank you for reporting back!
You can delete one or multiple tags by selecting them in the tag list and hitting `Del`.

**Comment by dh-connect** [comment]
hmm there is no del Button on Mac when I hit the usual back button which deletes on mac nothing happens, is there an option in the menue bar? maybe a context menu would help?

**Comment by pbek** [comment]
`Fn + Backspace` would do the trick, but I guess I will add support for just `Backspace`.

**Comment by dh-connect** [comment]
cool that works

**Comment by pbek** [comment]
great :)

**Comment by pbek** [comment]
v16.04.14 will bring backspace support ;)

**Comment by pbek** [comment]
In the just released v16.04.14 there is backspace support and also a context menu ;)
Can you please test if it works for you?

**Comment by dh-connect** [comment]
works great, also special thanks for the context menu, I really like that !

**Comment by pbek** [comment]
great, thank you for reporting back!
