### ISSUE TITLE
Do not dim the main edit panel content on mouseover when 'dark mode' is enabled

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#1394]
### Expected behaviour
When the main edit panel is active (mouseover), don't dim the content. If anything, dim the content when it is not active. Even better: don't dim the content at all.

#### Actual behaviour
When the main edit panel is active (mouseover), the contents are dimmed.

![Peek 2019-11-09 16-34](https://user-images.githubusercontent.com/5956570/68531126-54c7e280-030f-11ea-8430-3c2b35d4f325.gif)

#### Steps to reproduce
- enable 'dark mode' via Settings > Interface > Enable dark mode
- add content to a node
- mouseover/out of the main content panel

#### Relevant log output in the Log panel

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `za nov. 9 16:39:12 2019`
**Version**: `19.11.9`
**Build date**: `Nov  9 2019`
**Build number**: `614`
**Platform**: `linux`
**Operating System**: `Manjaro Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.13.1`
**Qt Version (runtime)**: `5.13.1`
**Portable mode**: `no`
**Application arguments**: `QOwnNotes`, `--session`, `test`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `4`
**Calendar items**: `0`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*

### Script `journal-entry`

**id**: `1`
**path**: `/qownnotes/scripts/journal-entry/journal-entry.qml`
**variablesJson**: 
```
{
    "defaultTags": "journal",
    "noteBodyTemplate": "tewrewrew",
    "singleJournalPerDay": true
}
```

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**LastUpdateCheck** (QDateTime): `2019-11-09T16:30:57.009`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `IBM Plex Mono,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `IBM Plex Sans Condensed,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `IBM Plex Mono,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `IBM Plex Sans Condensed,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 2 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `1`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `33`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-1** (QString): `Note 2019-03-17T10.21.37`
**showMatches** (QString): `true`
**showMenuBar** (bool): `false`
**showStatusBar** (bool): `true`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

**Comment by pbek** [comment]
Interesting, since when was that a thing? Was that always the case?

**Comment by sanderboom** [comment]
Not sure, just recently (last 2 weeks or so?) it started to bother me :wink:

**Comment by pbek** [comment]
I bisected my way back until 2018 in git in the source code and it was always the same. The highlighting happens. I suppose it's a newer version of Qt that does this. 

I guess you could try out some focus-styling with the script `Custom user interface styling`.

**Comment by Waqar144** [comment]
There's another issue like this one. If you try to search in the Textedit, the background of the `Find` turns light bluish and text becomes very difficult to read

**Comment by Waqar144** [comment]
![image](https://user-images.githubusercontent.com/7696024/68533545-e05f6480-034b-11ea-9620-b1042b403b30.png)

Like this

**Comment by pbek** [comment]
> If you try to search in the Textedit, the background of the Find turns light bluish and text becomes very difficult to read

for me it's a good red or green

![image](https://user-images.githubusercontent.com/1798101/68533547-62d72c80-032a-11ea-9123-e74b31daed3f.png)

**Comment by pbek** [comment]
Have you enabled the dark mode? Or are you using the (dark) colors from your desktop environment's theme...

**Comment by Waqar144** [comment]
> Have you enabled the dark mode? Or are you using the (dark) colors from your desktop environment's theme...

dark from desktop

**Comment by pbek** [comment]
I wonder if we need an option "use dark mode settings but not actually use the dark mode application theme" :laughing:

**Comment by Waqar144** [comment]
> I wonder if we need an option "use dark mode settings but not actually use the dark mode application theme" laughing

I think the dark mode should enable dark editor by default. Makes more sense. :thinking:

**Comment by pbek** [comment]
Yes, maybe. But then it also needs to force the light editor theme if it is unset.

**Comment by Waqar144** [comment]
> Yes, maybe. But then it also needs to force the light editor theme if it is unset.

Yes of course

**Comment by pbek** [comment]
I'm sure it will annoy some people, but help a lot more...

**Comment by sanderboom** [comment]
> I wonder if we need an option "use dark mode settings but not actually use the dark mode application theme" laughing

:blush: Too many options... this is already a bit the case IMO:

<img width="290" alt="image" src="https://user-images.githubusercontent.com/5956570/68548222-b4df8700-03ea-11ea-929e-728c2331f9a4.png">

Quite convoluted. If possible, try to go the way of less settings instead of more, although I'm not sure whether that is really feasible :sweat_smile: 

Maybe always follow the Desktop Environment for the general UI and only have a setting for 'Editor fonts & color'?

BTW, any example of an (Qt) applications that handles this really well?

**Comment by pbek** [comment]
> Maybe always follow the Desktop Environment for the general UI and only have a setting for 'Editor fonts & color'?

To my knowledge the DE doesn't tell if if it uses a dark or a light theme. And I also don't know about macOS and Windows.

**Comment by pbek** [comment]
> BTW, any example of an (Qt) applications that handles this really well?

I suppose most apps just have their light and dark theme (or none at all) and that it. We have the option "use the system colors" and "dark theme".

**Comment by sanderboom** [comment]
> To my knowledge the DE doesn't tell if if it uses a dark or a light theme. And I also don't know about macOS and Windows.

Doesn't the DE color almost the whole app without the developers intervention? Referring to System Settings > Colors on Plasma. At least for Linux this would simplify things a bit.

**Comment by pbek** [comment]
> Doesn't the DE color almost the whole app without the developers intervention?

yes, we are using that. but the "almost" is the problem and the issue that we don't know what colors are used.

**Comment by pbek** [comment]
## 19.11.21
- fixed dark mode hover color for newer Qt versions

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by ivanpirog** [comment]
Mac & Win version works fine! :)

**Comment by pbek** [comment]
Great, thank you for testing!
