### ISSUE TITLE
Feature Request: Provide Ubuntu PPA

### ISSUE THREAD

**Issue by janhenke** [pbek/QOwnNotes#14]
Right now the software is released as stand alone .deb files. It would improve user experience to publish the software instead in a personal package archive (PPA).

This would also allow the package to be build separately for all current releases. Thereby making changes in dependencies between different Ubuntu releases manageable.

**Comment by pbek** [comment]
Thank you, Jan
To create a PPA is a long wanted wish of me and still on my todo list after some attempts. It's far from trivial to create one. :)
I will make some more attempts.

**Comment by janhenke** [comment]
Well the PPA is not difficult, but you need working Debian packaging for it. It is not as difficult as it seems (if you start with manual pushing).

**Comment by pbek** [comment]
I will have to learn my way into the debian toolchain... But I want that done on Travis CI in the end... I would even more like to use the OpenSuse build service to build on a lot more platforms... But that's quite some learning task in itself.

**Comment by janhenke** [comment]
You cannot upload binary packages to a PPA. You have to upload a source package and it will be build by the PPA service.

**Comment by pbek** [comment]
Yeah, but I would want to do that after a successful build on the master branch. And I would have to rewrite the internal QOwnNotes update service... That will be fun. :)

**Comment by janhenke** [comment]
Well you could add a compile option to simply deactivate the update service (since the OS takes care of that).
For building, it would be a good idea anyway to support building the master from the command line.

**Comment by pbek** [comment]
Much food for thought...
The open suse build service is still a bit more appealing to me, it would solve the problem with building for different (Linux) platforms...

**Comment by janhenke** [comment]
In the end it is a matter of user experience for the end user. I honestly think the Suse build service is the exactly wrong way to serve Ubuntu users.

As I was trying to point out, you need the ability to build in an automated fashion anyway. You also need proper Debian packaging files as well, no matter where to build. The final step to build it in a PPA is then the least work/concern.

**Comment by janhenke** [comment]
If it is just about setting up the PPA, I could look into it, but I am currently time constraint, so I cannot create a full debian/ folder with all the things needed to build a Debian package.

**Comment by pbek** [comment]
Some help/hints with setting up a ppa for QOwnNotes would be gladly appreciated!

Currently I build the project for Linux and create a Debian package in Travis (which was a great deal of work to get it running with QT 5.4 and all) and deploy it from there to GitHub releases.
<https://github.com/pbek/QOwnNotes/blob/develop/.travis.yml>

I'm using a pre-prepared Debian package (which I made locally) and the meta files in <https://github.com/pbek/QOwnNotes/tree/develop/travis/build/DEBIAN> (I alter in the deployment process).

**Comment by pbek** [comment]
I (very proudly) present:

`bash
sudo add-apt-repository ppa:pbek/qownnotes
sudo apt-get update
sudo apt-get install qownnotes
`

**Comment by pbek** [comment]
We even have builds for openSUSE now. ;)
Check out the [QOwnNotes installation page](http://www.qownnotes.org/installation)
