### ISSUE TITLE
style issue

### ISSUE THREAD

**Issue by calis2002** [pbek/QOwnNotes#140]
Notice the small line behind the "Notiz erstellen oder suchen" field
![qownnotes](https://cloud.githubusercontent.com/assets/4539953/14519438/2ac0c492-021f-11e6-8ea8-dfe58763d944.png)

**Comment by pbek** [comment]
Thank you for reporting! Funny, I can't see it under Linux and I have no idea what it might be. What operating system were you using?

**Comment by calis2002** [comment]
Windows 10

**Comment by pbek** [comment]
will be fixed in version 1.4.2, thanks again for the report!

**Comment by pbek** [comment]
Version 1.4.2 is out now, could you please give some feedback on it.
