### ISSUE TITLE
Html chars after .enex imported

### ISSUE THREAD

**Issue by willbasky** [pbek/QOwnNotes#1400]
[Evernote.enex.zip](https://github.com/pbek/QOwnNotes/files/3831867/Evernote.enex.zip)
![Screenshot_20191111_200421](https://user-images.githubusercontent.com/28530747/68597271-7f0bd280-04be-11ea-95f4-81b12803eca3.png)

#### Expected behaviour
Text looks like: "У меня дома  ..."

#### Actual behaviour
Now `&#1059; &#1084;&#1077;&#1085;&#1103; &#1076;&#1086;&#1084;&#1072; ...`

#### Steps to reproduce
Import .enex to QOwnNotes

**Comment by pbek** [comment]
Evernote didn't just exported your text as UTF-8 text, but it included all those characters encoded like this: `&#1059; &#1084;&#1077;&#1085;&#1103; &#1076;&#1086;&#1084;&#1072; &#1076;&#1074;&#1077; &#1082;&#1086;&#1084;&#1085;&#1072;&#1090;&#1099;, &#1082;&#1091;&#1093;&#1085;&#1103;, &#1090;&#1091;&#1072;&#1083;&#1077;&#1090; &#1080; &#1074;&#1072;&#1085;&#1085;&#1072;. &#1042;`

Is that a special setting? This doesn't seem to happen for example with German umlauts in German Evernote notes...

**Comment by willbasky** [comment]
Not special at all. Some cirilic notes imported well, other like this. Maybe cause is '| Source | mobile.android |', that these notes created in android evernote.

**Comment by pbek** [comment]
That was very tricky to get a hold of, but I finally did it!

## 19.11.10
- improved special character detection in the Evernote import, the HTML import
  from the clipboard and the title detection of the link dialog
  (for [#1400](https://github.com/pbek/QOwnNotes/issues/1400))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by willbasky** [comment]
Yeah, now, it works like a charm. 

Thank you!

**Comment by pbek** [comment]
Great, thank you for testing! It was quite some work (especially to not to break anything else). :smile:

**Comment by Onair-santa** [comment]
And .md import not work with cyrilic
Only this
РљР°Рє Рё РїРѕС‡С‚Рё Р»СЋР±РѕРµ РіРѕС‚РѕРІРѕРµ Р±Р»СЋРґРѕ, РєСѓРїР»РµРЅРЅРѕРµ РІ РјР°РіР°Р·РёРЅРµ, СЃРѕР»РµРЅР°СЏ РёРєСЂР° РјРёРЅС‚Р°СЏ - РїРѕР»РЅР°СЏ РіР°РґРѕСЃС‚СЊ, РІ СЃСЂР°РІРЅРµРЅРёРё СЃ С‚РµРј, С‡С‚Рѕ РІС‹ РјРѕР¶РµС‚Рµ СЃРґРµР»Р°С‚СЊ СЃР°РјРё. РРєСЂР°, РґРѕ СѓР¶Р°СЃР° РЅР°РїРёС‡РєР°РЅРЅР°СЏ СЃРѕР»СЊСЋ, СЂР°Р·РЅС‹РјРё РєРѕРЅСЃРµСЂРІР°РЅС‚Р°РјРё РµС‰Рµ Рё СЂР°Р·Р±Р°РІР»РµРЅРЅР°СЏ РјР°РЅРєРѕР№ .... РЅСѓ РІС‹ РїРѕРЅСЏР»Рё )))

**Comment by Onair-santa** [comment]
And this. Import not work good
![image](https://github.com/pbek/QOwnNotes/assets/42511409/5cfb0fa8-a820-414a-919c-b29e918fc751)

**Comment by pbek** [comment]
Can you please open a new issue, @Onair-santa to show your setup, and also provide example enex files?

**Comment by Onair-santa** [comment]
Unfortunately, I have already deleted the application.
1. Import does not work. From any files
2. Markdown does not show correctly if you simply move the files to the program folder and open them inside.
3. There is no desire to redo hundreds of files.
4. Constant lags and freezes of the application. Startup speed...
5. The images inside are not displayed, you need to edit each file again.
The idea is good and I thought that I had finally found what I was looking for, but it is significantly inferior to both Obsidian and MNK in work. Good luck.

**Comment by pbek** [comment]
I wonder what behemoth you tried to import. 😁
