### ISSUE TITLE
Please allow sorting tickets by importance

### ISSUE THREAD

**Issue by Chealer** [pbek/QOwnNotes#1403]
I am considering to use QOwnNotes as a replacement for KNotes. Unfortunately, it is proving too difficult to evaluate its quality with the number of issue reports.

Please let potential users sort tickets according to the issue's importance. Simply separating issues in 5 categories (lowest, low, medium, high, highest) would suffice for me. This would allow to estimate quality by looking solely at high importance issues and at the number of lower-importance issues.

**Comment by pbek** [comment]
We are using the GitHub issue tracker for questions, feature requests and bugs/regressions. The issues are almost all labeled accordingly.

**Comment by pbek** [comment]
> it is proving too difficult to evaluate its quality

maybe you should just try it out 😆

**Comment by pbek** [comment]
> Please let potential users sort tickets according to the issue's importance. Simply separating issues in 5 categories (lowest, low, medium, high, highest) would suffice for me.

...but in general it sounds like a good idea. Do you have some suggestions for a best practice for the label naming (I'd like some kind of prefix) and some bigger project that is using such a schema successfully.

**Comment by Waqar144** [comment]
> > Please let potential users sort tickets according to the issue's importance. Simply separating issues in 5 categories (lowest, low, medium, high, highest) would suffice for me.
> 
> ...but in general it sounds like a good idea. Do you have some suggestions for a best practice for the label naming (I'd like some kind of prefix) and some bigger project that is using such a schema successfully.

A high/medium/low sounds good to me.

**Comment by pbek** [comment]
No prefix? Like `sev-high`?

**Comment by Waqar144** [comment]
> No prefix? Like `sev-high`?

I have never seen a sev-high/serverly-high. However something like `urgent`, `high` can work in such situations

**Comment by pbek** [comment]
Done for now. So I'll close this until something else comes up.

**Comment by Chealer** [comment]
> We are using the GitHub issue tracker for questions, feature requests and bugs/regressions. The issues are almost all labeled accordingly.

If you mean this tracker is not limited to issues but also contains questions, that's a good point, but it should be clarified. Either the "Issues" tab should be renamed something like "Issues & Questions", or questions should be split to somewhere else (I would favor that avenue).

**Comment by Chealer** [comment]
> > it is proving too difficult to evaluate its quality
> 
> maybe you should just try it out laughing

Trying software takes a lot of time. Unless you actually test the software, it will take years to spot corner/edge cases. Often, new issues will be introduced faster than you identify issues. And trying will fail to identify most security vulnerabilities (and in some cases, discovering a security flaw while you try software is just too late).
When I was young, I tried lots of software products, but nowadays, I value my time too much to start evaluating with a trial right away.

**Comment by Chealer** [comment]
> > Please let potential users sort tickets according to the issue's importance. Simply separating issues in 5 categories (lowest, low, medium, high, highest) would suffice for me.
> 
> ...but in general it sounds like a good idea. Do you have some suggestions for a best practice for the label naming (I'd like some kind of prefix) and some bigger project that is using such a schema successfully.

The Tiki project has an Importance field which goes from 1 to 10: https://dev.tiki.org/Wishlist
Of course, it can get difficult to rate as precisely as that. This also has the downside of suggesting that an Importance 10 issue is only 10 times as important as an Importance 1 issue, while the Importance range normally covers several orders of magnitude.

CLDR has a Priority field with words as values: "TBD", "trivial", "minor", "medium", "major", "critical" and "blocker"
https://unicode-org.atlassian.net/projects/CLDR/issues

**Comment by Chealer** [comment]
@pbek is this solved and if so, can you explain how?
One caveat is the field's naming - "Severity" represent a bug's importance, but does not apply to other issues, such as mere requests for enhancement (or, technically, it does, but would be null for all of these).

**Comment by pbek** [comment]
>  Either the "Issues" tab should be renamed something like "Issues & Questions", 

Are you talking of the GitHub issues tab? That's not possible to my knowledge.

> or questions should be split to somewhere else (I would favor that avenue).

that's why there is a `question` label, if you want bug, just switch to the label `bug`

**Comment by pbek** [comment]
> CLDR has a Priority field with words as values: "TBD", "trivial", "minor", "medium", "major", "critical" and "blocker"
> https://unicode-org.atlassian.net/projects/CLDR/issues

thank you, I'll add more labels when need arises

> One caveat is the field's naming - "Severity" represent a bug's importance, but does not apply to other issues, such as mere requests for enhancement (or, technically, it does, but would be null for all of these).

let's try `priority` then

> is this solved and if so, can you explain how?

is there anything you'd still like to know?

**Comment by Waqar144** [comment]
@Chealer 
What are the features that are most important for you in a note taking app? Perhaps we can give you a direct answer.

We don't have any major outstanding bug right now, but we do have usability bugs I think. Somethings aren't as obviously understandable as they should be.

**Comment by Chealer** [comment]
> > Either the "Issues" tab should be renamed something like "Issues & Questions",
> 
> Are you talking of the GitHub issues tab?

Yes


> > or questions should be split to somewhere else (I would favor that avenue).
> 
> that's why there is a `question` label, if you want bugs, just switch to the label `bug`

So does the label `bug` include RFE-s (issues which are not bugs)?

**Comment by Chealer** [comment]
> [...]
> 
> > One caveat is the field's naming - "Severity" represent a bug's importance, but does not apply to other issues, such as mere requests for enhancement (or, technically, it does, but would be null for all of these).
> 
> let's try `priority` then

I advise against `priority` (if I had to choose between "priority" and "severity", I would prefer the latter). Priority is related to importance, but cost/difficulty also comes into the equation. To use a simple model, priority is importance divided by cost. Suppose you have 2 issues, #1 requesting to support the foo OS, and #2 requesting to support the bar OS. Let us suppose both OS-s are used by 10 million users and both have an importance of 10 000 000 €/year. If foo is twice as complicated as bar, so that solving #1 costs 20 000 €, while solving #2 costs only 10 000 €, these 2 issues both have the same importance, but the priority (return on investment) of #1 is 500/year while the priority of #2 is double that (1000/year).

> > is this solved and if so, can you explain how?
> 
> is there anything you'd still like to know?

@pbek and @Waqar144 I did not mean this ticket as a support request, but really as a request to improve the issue tracking system.
I asked if this was solved because I still do not see how I could sort tickets by importance.

**Comment by pbek** [comment]
> So does the label bug include RFE-s (issues which are not bugs)?

What do you mean by RFE? "Request For Enhancement"?

Things that need clarification are usually labeled as bugs, questions or enhancements. now and then they stay at "question"...

Or did you mean CVE?

**Comment by Chealer** [comment]
@pbek yes I meant mere requests for enhancement. If a `question` label is used both for user interface issues (lack of clarity) and for support requests, then it gets difficult to separate issues from the rest...

**Comment by pbek** [comment]
> "priority" and "severity"

neither of them are fitting for all cases. :smile: 

> I could sort tickets by importance.

I guess you would need to ask GitHub directly for that.

> @pbek yes I meant mere requests for enhancement. If a question label is used both for user interface issues (lack of clarity) and for support requests, then it gets difficult to separate issues from the rest...

so what labels should exist in your opinion?

**Comment by pbek** [comment]
> I still do not see how I could sort tickets by importance.

Whom importance? There is no company behind QOwnNotes and there is no funding. It's a passion project. :smiley_cat: :heart:

**Comment by Chealer** [comment]
I do not know labels well but I think they are designed for a wide variety of needs. I cannot say what the full list of labels used by a project I do not master should be.
What I can say is that it needs to be obvious for [prospective] users how to list (or search) issue reports, and only these. This can be done either by using "Issues" only for issues, or by introducing an `issue` label to identify issues (or perhaps sub-labels like "issue::bug", "issue::rfe"), or a `non-issue` label to identify tickets other than issue reports.

**Comment by pbek** [comment]
> What do you mean by RFE? "Request For Enhancement"?

**Comment by Chealer** [comment]
> 
> 
> > I still do not see how I could sort tickets by importance.
> 
> Whom importance? There is no company behind QOwnNotes and there is no funding. It's a passion project. 😺 ❤️

There is no doubt that importance is contextual, and different for different persons. It is difficult (read: impossible) to accurately measure any issue's importance. The way I think about it is as the sum of the importance for everyone. So in the example of supporting foo OS, we could say:
If there are 10 million users of foo OS in the next year, and using QOwnNotes instead of the note-taking solution they currently use would save them each 1 € in the next year, and we assume that they would all start using QOwnNotes as soon as support is introduced, then for these 10 million persons issue #1 has an importance of 10 000 000 € per year.
If introducing foo support has no value for the remaining 6900 000 000 humans, we could estimate a solution has an importance of 0 for these persons.
So in total, the global importance is estimated at 10 000 000 € for the following year.

**Comment by Chealer** [comment]
> 
> 
> > What do you mean by RFE? "Request For Enhancement"?

Yes, mere requests for enhancement, whether the enhancement in question is a clarification, "enhancing" an existing feature, or addition of a new feature. As opposed to requests for bug-fixes.

**Comment by Waqar144** [comment]
> I do not know labels well but I think they are designed for a wide variety of needs. I cannot say what the full list of labels used by a project I do not master should be.
> What I can say is that it needs to be obvious for [prospective] users how to list (or search) issue reports, and only these. This can be done either by using "Issues" only for issues, or by introducing an `issue` label to identify issues (or perhaps sub-labels like "issue::bug", "issue::rfe"), or a `non-issue` label to identify tickets other than issue reports.

The issues that are bugs are labeled as `bug`
The issues that are feature requests are labeled as `enhancments`
The issues that are not a problem on our side are labeled as `upstream-problem`

**Comment by Waqar144** [comment]
If I were you, I would filter issues labeled as `bugs` and `upstream-problems` first and go through them. Then I would check out the `feature requests`/`enhancements` to see what features might be missing and whether I need them.

**Comment by Chealer** [comment]
Thanks @Waqar144 
Regarding the `upstream-problem` label, I would advise **against** using that one **instead of** a ticket type label such as `question` or `bug`, as seems to be done in most cases. For QOwnNotes users, whether or not the issue comes from upstream, it causes a bug or a missing feature for them. They don't care if the issue comes from an included library or from QOwnNotes's own code. So if a bug comes from an upstream library, it should be labelled both `bug` and `upstream`.
