### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by robertzajda** [pbek/QOwnNotes#141]
Hi,

Firstly, thanks for your work. I replaced 'zim' with QOwnNotes and I'm really happy with that.

I have some fixes/proposals:

- [ ]  Headers when are one by one have no vertical margin in this example:
```
this is header1
====

## this is header2
```

- [ ]  Code blocks have extra space at the end.

- [ ] Code blocks or inline code blocks shoud have a lightgray background (like github).

- [ ] Code hilighting.

- [ ] When "Note > Sort > Alpabetically" is enabled, currently edited note jumps at first position.

- [ ] Feature request: attachments panel. Possibility to add/remove files attached to note. Media files, but also other files attached.

- [ ]  Format icons in menu.

- [ ]  Linking to other folder notes:

```
<note://../other-dir/04_Mynote>
```

Any chanses to include some of above?

Regards
Robert

**Comment by pbek** [comment]
Thank you for your suggestion, I will take a closer look at them.

**Comment by pbek** [comment]
Which version of QOwnNotes are you using?

>  Headers when are one by one have no vertical margin in this example:

Is that the desired behavior or did you see that somewhere, in both cases: where?

> Code blocks have extra space at the end.

Is that the desired behavior or did you see that somewhere, in both cases: where?

> Code blocks or inline code blocks shoud have a lightgray background (like github).

Currently the background is green-gray. Do you propose that this background should be changed to gray?

> Code hilighting.

Do you know a platform independent Qt component that could help with that?

> Format icons in menu.

Like bold and italic?

> Linking to other folder notes

That would only work on one computer but not when notes are synced over different desktop computers.

**Comment by robertzajda** [comment]
Thanks for quick reply.

I just installed version 1.4.1.

And as I see it has very confortable preview panel, **but there is no view only mode (hidden editor)**.

Layout fixes look [here](http://i.share.pho.to/8e073126_o.png).

> > Code hilighting.
>
> Do you know a platform independent Qt component that could help with that?

[qscintilla](https://riverbankcomputing.com/software/qscintilla/intro)?

> > Format icons in menu.
> 
> Like bold and italic?

Yes. enderline

> > Linking to other folder notes
>
> That would only work on one computer but not when notes are synced over different desktop computers.

If the path will be realted it will work. It also can be: `<note://mynote-dir/04_Mynote>` where mynote-dir is note directory added to qownnote.

**Comment by pbek** [comment]
> but there is no view only mode (hidden editor).

no, there isn't, but you can simply resize the edit area to 0.

> Layout fixes look here.

 Ah, you are talking about the markdown view. We can do that...

> qscintilla

thank you for your suggestion, but qscintilla is Python, we have C++
and to build upon an other editor component would be weeks of work...

> Yes. enderline

Markdown doesn't have a defined syntax to underline text.

> If the path will be realted it will work. It also can be: <note://mynote-dir/04_Mynote> where mynote-dir is note directory added to qownnote.

Every client can has it's own note folders (you can define as many as you like) and they can have different names across the synced clients.

**Comment by pbek** [comment]
>  When "Note > Sort > Alpabetically" is enabled, currently edited note jumps at first position.

...will be fixed in version 1.4.2

**Comment by pbek** [comment]
In 1.4.2 there also will be the modifications in the markdown html be made. ...everything but the spaces at the end of the headline. the html is correct, that space seems to be a thing of the used QTextBrowser. I haven't found a solution for it yet, maybe you can find anything...

**Comment by pbek** [comment]
I also now inserted buttons for *bold* and *italic* in the main menu.

**Comment by pbek** [comment]
Version 1.4.2 is out now, could you please give some feedback on it.

**Comment by eemantsal** [comment]
I agree, deeply, about the format icons menu. Most users don't know Markdown syntax, nor should be mandatory to know it. If we have GUIs is precisely for things like that, for showing the common user what he can do with a program, no? Well, I think a simple menu with icons for the format that can be given with Markdown would be an usability improvement. You could add them in a secondary toolbar, like we have in many other apps: a main toolbar and then other ones that the user can hide or show depending on their needs. A "format" toolbar with those buttons and icons would be great, average users would love it, and power users would just hide it and keep typing their MD "code".

**Comment by pbek** [comment]
For now you will find some in the main menu and in the `Edit` menu. :) Your format menu bar suggestion is noted.

**Comment by eemantsal** [comment]
Well, I was talking about toolbars, with icons and buttons instead of menu entries, like that in Kmail, for example: if you right click on that row of icons at the top of Kmail's mail composer windows, just below the menu bar, several options appear, one of them is «Configure toolbars» (or smething like that, my system isn't in english), and in the dialog box that is open, you can configure what icons appear on each toolbar, the main one, the HTML one, etc. I don't recall well now, maybe Konqueror? there's a lot of time I don't have it installed anymore, but there are other KDE apps that also allow the user to choose which toolbars to be shown. A toolbar with all the buttons to format the text I think would be an optimal solution for those who don't know Markdown, and experienced Markdown users could unclutter their interfaces just hiding it.

Cheers.

**Comment by pbek** [comment]
Sorry, I also was talking about a toolbar (plus menu entries). But the configurable toobar is a KDE feature. ;)

**Comment by pbek** [comment]
In version 16.04.12 (new release versioning) the main toolbar is now split into multiple toolbars that you can rearrange or hide by themselves. You you please test this when the version is released?

**Comment by eemantsal** [comment]
Clear. I'll update my installation and comment my experiecne with the new tool bar.

**Comment by robertzajda** [comment]
I just updated to 16.04.13. Works great. Many, many thank's for readonly mode.

One small notice...
When enabling/disabling editor window, the first panel (with notes list) is resizing (growing width).

I'm using qownnotes as a helpdesk in my office. I checked some solutions and in my opinion qownnotes is the best solution.

Great Work! Thanks.

**Comment by pbek** [comment]
Thank you. :sunny: 

When one pane is disabled the layout manager gives the space to all the remaining panes. If you don't want to spend the horizontal space then maybe new the vertical splitting (since v16.04.13) is for you.
<http://www.qownnotes.org/changelog/QOwnNotes>

**Comment by robertzajda** [comment]
Yes. I can see that. Nice feature. But in large documents it's inconvenient to use vertical view. Secondly as I see when resizing main window, only notes list panel is resizing. This is not so important but other apps with sidebars (firefox, thunar) has sidebar panel stable when resizing.

One other small thing. Settings  window by default is very high (I cant see buttons on my TV 1360x768px).

**Comment by pbek** [comment]
It currently has the minimum possible height. Maybe I can restructure the content of the settings to fit more in.

**Comment by robertzajda** [comment]
I can resize the window manually to fit my screen and minimum height is ok. But by default when opening its large.

**Comment by pbek** [comment]
I guess that will be depending on the DPI of the screen. Higher DPI screens needs higher font sizes, but the dialog size stays the same... I will see what I can do.

**Comment by eemantsal** [comment]
I second robertzajda, new configurable toolbars work great, and unclutters the interface if we don't usually need some of the tools. +1: 
But, why, in the format toolbar, are only italics, code and bold buttons; what about font size, color or font family? i don't use those too much, maybe when I elaborate my notes in a ODT document, but not for initial notes, but probably some users do. Also, perhaps a title size button -h1, h2, etc- would also be nice.

**Comment by pbek** [comment]
Thank you for your feedback! In Markdown there is not font size or family. QOwnNotes is a plain text editor. And headings are simply achieved with `#`, `##`, `###` and so on before the headline.

**Comment by eemantsal** [comment]
Oh, ignorant me, heheh. But about the headings on could also argue that bold and italics are also simply achieved with ** and *, that is even simpler than ###. I think that a complete format toolbar could include headings format and a line creation button, even if they are easily achieved just typing, but that's what are buttons for, no? for, handyness sake.

**Comment by pbek** [comment]
You can also select a text and then press the bold button (or `Ctrl + B`), that's what they are for. Same goes for code and italic. It even goes for links, images or tasks. The link, image or the task will be then linked to the text.

**Comment by pbek** [comment]
@robertzajda in the just released v16.04.14 I did a lot of improvements for the settings dialog, can you please test if it works better for you now

**Comment by robertzajda** [comment]
Settings dialog now works perfect.

Last few days I'm working a lot with this app. I can't see any problems. It's fast and stable.
Functionality is enaugh. Maybe one thing I was speaking, you can think about. Attachments pane (list/add/remove). Now we can put images, but we cannot remove them (by the app) from media folder.
Whatever, it's not really a problem. Just a small tip.

Thanks!

**Comment by pbek** [comment]
Thank you for your feedback! As for the removing of media files, I already have a task on my todo list to look for files in the media folder, that are not used in notes. I will report back in this issue when I completed that. ;)

**Comment by pbek** [comment]
## 16.09.16
- you now can **delete orphaned images** in a dialog with an image preview
    - you will find a new menu entry in the edit menu to open the dialog 

There now is a new release, could you please test it and report if the new features work for you?
