### ISSUE TITLE
Highlighting of trailing spaces

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1416]
Trailing spaces will be highlighted in the note editor in the next release.

**Comment by Waqar144** [comment]
Can't wait to see it in action. 😉

**Comment by pbek** [comment]
## 19.11.13
- trailing spaces are now highlighted in the note editor
    - you can set a custom background color in the *Edit fonts & colors settings*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Waqar144** [comment]
Working great :+1:

**Comment by pbek** [comment]
Great, thank you for testing!
