### ISSUE TITLE
[Windows] Open note in default external editor not work

### ISSUE THREAD

**Issue by piyo-gh** [pbek/QOwnNotes#142]
If path to external editor is empty, nothing happens when I click 'Open note in external editor'.
I don't know why.

I'm using on Windows 10 x64.

**Comment by pbek** [comment]
Thank you for the report. I will take a look at that!

**Comment by pbek** [comment]
Will be fixed in version 1.4.3, thanks again for the report!

**Comment by pbek** [comment]
Version 1.4.3 is now released. Can you please test and report back?

**Comment by piyo-gh** [comment]
Solved this problem. Thank you. :)
