### ISSUE TITLE
Text jumps up and down as I type on Windows 10 if interface font size is overridden

### ISSUE THREAD

**Issue by raelb** [pbek/QOwnNotes#1422]
Likely related to Windows scaling settings

OS: Windows 10. Scaling 150%
![image](https://user-images.githubusercontent.com/13108198/69002661-2a23ee00-08fc-11ea-9b8c-5c73b460cd08.png)

Interface settings:
![image](https://user-images.githubusercontent.com/13108198/69002663-390aa080-08fc-11ea-9092-2070d27df24c.png)

![image](https://user-images.githubusercontent.com/13108198/69002669-44f66280-08fc-11ea-8b89-fe65caa60868.png)

Small video demonstrating the problem:
[jumping text.zip](https://github.com/pbek/QOwnNotes/files/3855203/jumping.text.zip)

**Comment by pbek** [comment]
Thank you for reporting, I don't think I've seen that on Windows systems I've access to yet. At least on one I've 150% scaling enabled on Windows.

Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging.

**Comment by pbek** [comment]
And does this also happen if you set the scale to 100% in Windows?

**Comment by pbek** [comment]
5) Do you get that jumping also if you type not at the end of the line, but inside?

**Comment by raelb** [comment]
The template says:
"Please also enable debug output in the options of panel.". I did not understand what this was referring to/where to do this?

Let me go backwards :).
5. No. If I type in the middle of the line it does not occur.
4. No...
3. I will test and get back to you on that.
2. I don't think so. It just says:
``` 
[12:37:47] [warning] Unable to find any suggestion for "Here"
[12:37:47] [warning] Unable to find any suggestion for "Here"
[12:37:47] [warning] Unable to find any suggestion for "Here "
[12:37:47] [warning] Unable to find any suggestion for "Here "
[12:37:47] [warning] Unable to find any suggestion for "Here i"
```
I don't see where to enable debug logging.
1. [QOwnNotes Debug Information.zip](https://github.com/pbek/QOwnNotes/files/3855482/QOwnNotes.Debug.Information.zip)

**Comment by pbek** [comment]
> Please also enable debug output in the options of panel.

You can edit some options if you right-click the debug log panel.

>  5. No. If I type in the middle of the line it does not occur.

I think I have a clue where that comes from: #1416 

But it is only happening on Windows and I have no idea why. Currently you can get around it by going into the *Editor fonts & colors settings*, copying your *Color schema* and turning down the font size for *Trailing spaces* to 90%.

**Comment by raelb** [comment]
I did initially try to right click in the panel, however I got the wrong popup:
![image](https://user-images.githubusercontent.com/13108198/69007431-5cf2d400-0946-11ea-901b-4ab51d8935db.png)
Perhaps your dictionary popup can also include items from the other popup... I was also looking for a clear log button, but could not get to it!

With regard to your suggestion, it does fix the problem. Thank you.

Perhaps related to the next issue I will post.

**Comment by pbek** [comment]
> Perhaps your dictionary popup can also include items from the other popup..

@Waqar144, do you think we could manage that for the note edit? And we could completely disable the spell-checking in the log panel.

**Comment by pbek** [comment]
@raelb, do you have the problem (jumping text) if you start a different QOwnNotes session with for example `QOwnNotes.exe --session test`?

**Comment by pbek** [comment]
You can also do this in portable mode.

**Comment by raelb** [comment]
Initially not.

If I make this change, then I still do not get it.

![image](https://user-images.githubusercontent.com/13108198/69008065-c971d100-094e-11ea-9f12-ee0449aa4526.png)

If I set font size to 10px then I get the jumping text:

![image](https://user-images.githubusercontent.com/13108198/69008029-739d2900-094e-11ea-86cc-aad8b63268cf.png)

**Comment by pbek** [comment]
Ah, so the size locking in #1423 is the issue. The trailing spaces simply have a different size because of the font size override.

**Comment by pbek** [comment]
I'll see if I can solve #1423 together with it.

**Comment by Waqar144** [comment]
> > Perhaps your dictionary popup can also include items from the other popup..
> 
> @Waqar144, do you think we could manage that for the note edit?.

Other pop up? Which one? The normal one with copy / paste / export stuff?

> And we could completely disable the spell-checking in the log panel

Yes, that we should.

**Comment by pbek** [comment]
> Other pop up? Which one? The normal one with copy / paste / export stuff?

Currently the spellchecker context menu has priority over the context menu with cut/copy/... (plus our custom stuff). It would be great if the spellchecking suggestions would be in the latter popup (if that is possible)

**Comment by Waqar144** [comment]
> Currently the spellchecker context menu has priority over the context menu with cut/copy/... (plus our custom stuff).

Spellchecker menu only gets triggered in case we have a misspelled word, otherwise it always gets ignored.

> It would be great if the spellchecking suggestions would be in the latter popup (if that is possible)

It is possible, however there is just one issue. The size of the normal context menu is already quite big and introducing spellchecker menu in there would clutter it up. You can see how mozilla does it, everything in one context menu, but their context menu is quite small so it looks okayish.

Now if we introduce it in a submenu, it would be okay but then it wouldn't be as quick as before.

**Comment by Waqar144** [comment]
> Currently the spellchecker context menu has priority over the context menu with cut/copy/... (plus our custom stuff).

Spellchecker menu only gets triggered in case we have a misspelled word, otherwise it always gets ignored.

> It would be great if the spellchecking suggestions would be in the latter popup (if that is possible)

It is possible, however there is just one issue. The size of the normal context menu is already quite big and introducing spellchecker menu in there would clutter it up. You can see how mozilla does it, everything in one context menu, but their context menu is quite small so it looks okayish.

Now if we introduce it in a submenu, it would be okay but then it wouldn't be as quick as before.

**Comment by pbek** [comment]
@Waqar144, I delete the duplicate comment :grin: 

> Now if we introduce it in a submenu, it would be okay but then it wouldn't be as quick as before.

As you said, Firefox simply just adds the spell checking to the top. Do you think that would make our context menus too high?

**Comment by raelb** [comment]
Why is the spell checker active in the log window?

**Comment by Waqar144** [comment]
Yes

> @Waqar144, I delete the duplicate comment grin
> 
> > Now if we introduce it in a submenu, it would be okay but then it wouldn't be as quick as before.
> 
> As you said, Firefox simply just adds the spell checking to the top. Do you think that would make our context menus too high?

Yes very very high.

**Comment by pbek** [comment]
Let's move the spellchecker context menu conversation to #1426.

**Comment by pbek** [comment]
For some reason I cannot reproduce this problem anywhere than on Windows 10, even on Windows 8.1 it works as it should.

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mi Nov 20 16:24:51 2019`
**Version**: `19.11.17`
**Build date**: `Nov 20 2019`
**Build number**: `622`
**Platform**: `windows`
**Operating System**: `Windows 8.1 (6.3)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `Self-build`
**Qt Version (build)**: `5.13.1`
**Qt Version (runtime)**: `5.13.1`

**Comment by pbek** [comment]
This was tedious to fix...

## 19.11.18
- fixed possible jumping of text on Windows 10 if the interface font size was overwritten
- fixed custom editor font size on Windows 10 if the interface font size was overwritten

There now is a new release, could you please test it and report if it works for you?

**Comment by raelb** [comment]
It seems to work ok. Well done :)

**Comment by pbek** [comment]
Great, thank you for testing it!
