### ISSUE TITLE
Provide a way to bulk-toggle checkboxes

### ISSUE THREAD

**Issue by markusdd** [pbek/QOwnNotes#1424]
This is a feature suggestion.

I commonly use QOwnnotes for checklists that I need again and again (travel etc.).

For that it would be super convenient to select a bunch of lines or the whole list and have a bulk check/uncheck function.

**Comment by pbek** [comment]
Thank you for your suggestion.
I'm not sure if that's even possible in the preview...
But at least in the note edit panel you could do that with the scripting engine.
Do you want to attempt to write a script? I could help you.

**Comment by sanderboom** [comment]
Or use: [Toggle Checkbox script](https://github.com/qownnotes/scripts/tree/master/toggle-checkbox)


> This script creates a menu item and a button to toggle checkbox state. Change one or more selected lines regarding checkboxes: plainlist -> unchecked, unchecked -> checked, checked -> unchecked. Hint: assign a shortcut.

Works for me :yum:

**Comment by fnkabit** [comment]
@pbek Do you think this one could be closed ?

**Comment by pbek** [comment]
Thanks for the heads up.
