### ISSUE TITLE
Merge spellchecker context menu and general context menu

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1426]
Moved conversation from #1422 to this issue.

**Comment by pbek** [comment]
@Waqar144 

> > As you said, Firefox simply just adds the spell checking to the top. Do you think that would make our context menus too high?

> Yes very very high. 

Maybe we can just put the general context menu in a sub-menu if the spellchecker context menu is shown. I don't know how "easy" that can be implemented.

**Comment by Waqar144** [comment]
> Maybe we can just put the general context menu in a sub-menu if the spellchecker context menu is shown. I don't know how "easy" that can be implemented.

This would be difficult and wouldn't look very pretty(a small context menu with a huge submenu). The reverse is relatively easier, spellchecker menu inside the general context menu.

However, I am still of the opinion that the way it is, it is more clean. You don't get the spellchecker context menu unless you right-click on a misspelled word. It is smart enough to realize when the general context menu should be drawn instead of the spellchecker one.

**Comment by pbek** [comment]
On the other hand... KMail also has two context menus

**Comment by Waqar144** [comment]
> On the other hand... KMail also has two context menus

For spellchecking or something else? :thinking:

**Comment by pbek** [comment]
> For spellchecking or something else? thinking

Like we currently have it. There is the custom context menu and then there is a different context menu for spellchecking.

**Comment by Waqar144** [comment]
> > For spellchecking or something else? thinking
> 
> Like we currently have it. There is the custom context menu and then there is a different context menu for spellchecking.

Ahh.. Not surprising. I guess they are using Sonnet too in the same way we are. Two context menus keep it really clean ;)

**Comment by pbek** [comment]
> Ahh.. Not surprising. I guess they are using Sonnet too in the same way we are. 

Yes, they also use Sonnet.

> Two context menus keep it really clean ;)

Or they simply didn't care to integrate them. 😆

**Comment by Waqar144** [comment]
> Or they simply didn't care to integrate them. laughing

Maybe :laughing:

**Comment by Waqar144** [comment]
done with https://github.com/pbek/QOwnNotes/pull/2373

**Comment by pbek** [comment]
Awesome! I already thought there was something different about the context menu. 😆

**Comment by pbek** [comment]
## 22.1.5
- the spell-checker context menu of the note edit was integrated into the general
  context menu (for [#1426](https://github.com/pbek/QOwnNotes/issues/1426), thank you @Waqar144)
