### ISSUE TITLE
I'm doing some zh-cn translation

### ISSUE THREAD

**Issue by Admiraldesvl** [pbek/QOwnNotes#1427]
Hi!
I found that some texts are not translated into zh-cn. So I'm trying to offer some zh-cn translation.

I think it's important to show some details to prevent troubles.
1. The file is \QOwnNotes\src\languages\QOwnNotes_zh_CN.ts
2. I'm using Linguist 5.9.8 MinGW 5.3.0 32bit
3. My OS is windows 10 EDU

To start from scratch, I will first translate some simple words such as "OK" "Cancel" "Title", etc. And I will follow the preceding translation style. For example, "Cancel" will be translated into "取消" since other translators did so.

Feel free to tell me anything that you think I should do in my translation work and I'll do my best!

**Comment by Waqar144** [comment]
Hi!
Thanks for your interest.

Translations are being managed at Crowdin: https://crowdin.com/project/qownnotes/invite

You can read this for more info:
https://www.qownnotes.org/Knowledge-base/How-can-I-help-to-translate-QOwnNotes

**Comment by Admiraldesvl** [comment]
So instead of creating a PR, I committed a lot of translation on Crowdin. Feel free to check it. Many of them are trivial but I hope my work helps.

**Comment by Waqar144** [comment]
> So instead of creating a PR, I committed a lot of translation on Crowdin. Feel free to check it. Many of them are trivial but I hope my work helps.

Everything helps. Thanks for all your efforts :heart:

**Comment by pbek** [comment]
## 19.11.17
- added more Catalan, Vietnamese, Dutch, Spanish, Italian, **Chinese Simplified**,
  Russian, Greek, German translation (thank you MGuerra, Fabijenna, richarson,
  mlocati, **admiraldesvl**, unchase, athrouss, rakekniven)

Thank you! :smile_cat:
