### ISSUE TITLE
[Windows] Open note in custom external editor with multibyte character filename

### ISSUE THREAD

**Issue by piyo-gh** [pbek/QOwnNotes#143]
When I set custom external editor, file with multibyte character filename doesn't open.
Filename seems to be encoded with utf-8.
I think internal encoding of cmd.exe is unicode, it cannot handle utf-8 filename.

**Comment by pbek** [comment]
Thank you for the report. Who had the multibyte filename? The editor or the note? Can you please show me some examples? Which Windows operating system did you use? Windows 10?

**Comment by pbek** [comment]
Will be fixed in version 1.4.3!

**Comment by pbek** [comment]
Version 1.4.3 is now released. Can you please test and report back?

**Comment by piyo-gh** [comment]
Solved this problem. Thank you. :)
