### ISSUE TITLE
AppVeyor QT 5.13 builds are failing

### ISSUE THREAD

**Issue by FBachofner** [pbek/QOwnNotes#1431]
Hi Patrizio:

Are you aware that apparently all QT 5.13 builds (this now includes the 32 bit builds) have been failing for 3 or more days?

Interestingly, I spot checked the 5.7 builds and they all seem OK.

**Comment by pbek** [comment]
Yes, they are failing since Sunday since https://github.com/pbek/QOwnNotes/releases doesn't work any more. The GitHub support couldn't tell me when that will be fixed again.

**Comment by pbek** [comment]
Luckily QOwnNotes 19.11.13 for Windows is still downloadable...

**Comment by pbek** [comment]
I don't understand the relation between our `test.exe` and GitHub, but former builds that went through don't work too, like https://ci.appveyor.com/project/pbek/qownnotes/build/job/50kryd1hsscdb4ld

**Comment by pbek** [comment]
I made an other test and a former build went through now... https://ci.appveyor.com/project/pbek/qownnotes/builds/28877369/job/buew6pldiuy956fi

Seems like the test binary can't run on AppVeyor any more with Qt 5.13.2

**Comment by pbek** [comment]
## 19.11.16
- fixed AppVeyor Windows build

**Comment by pbek** [comment]
Qt 5.13.2 build runs again! :tada:

**Comment by FBachofner** [comment]
>Qt 5.13.2 build runs again! 🎉

Congratulations!

So what was the issue?

You may want to document here for future reference . . .

**Comment by pbek** [comment]
Qt 5.13.2 on AppVeyor was not able to run the build tests with the Sonnet spellchecker, I had to remove them. Qt 5.9 worked fine.
