### ISSUE TITLE
Ctrl + Shift + Z does undo instead of redo in note text edit

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1433]
@Waqar144, this seems like a regression from the custom undo handling, right?

#### Expected behavior

`Ctrl + Shift + Z` does redo in note text edit (like shown in context menu)

#### Actual behavior

`Ctrl + Shift + Z` also does undo in note text edit like `Ctrl + Z`

## General Info

**Current Date**: `Mi. Nov. 20 11:48:07 2019`
**Version**: `19.11.16`
**Build date**: `Nov 19 2019`
**Build number**: `621`
**Platform**: `linux`
**Operating System**: `KDE neon User Edition 5.17`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.9.5`
**Qt Version (runtime)**: `5.13.2`

**Comment by Waqar144** [comment]
> @Waqar144, this seems like a regression from the custom undo handling, right?

Yeah, I think
 
> `Ctrl + Shift + Z` does redo in note text edit (like shown in context menu)
> #### Actual behavior
> 
> `Ctrl + Shift + Z` also does undo in note text edit like `Ctrl + Z`

Seems like we have to handle the redo part ourselves too.

**Comment by pbek** [comment]
:grin:

**Comment by pbek** [comment]
Are you checking the key events manually? Maybe `Ctrl + Shift + Z` falls into the `Ctrl + Z` case.

**Comment by Waqar144** [comment]
> Are you checking the key events manually? Maybe `Ctrl + Shift + Z` falls into the `Ctrl + Z` case.

Yes that seems to be the case.

**Comment by pbek** [comment]
Works again, thank you!
