### ISSUE TITLE
Highlighting of <http://hostname> doesn't work correctly

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1436]
#### Expected behaviour

The first `<` in `<http://hostname>` is masked (grey).

#### Actual behaviour

The first `<` in `<http://hostname>` is not masked (black).

![image](https://user-images.githubusercontent.com/1798101/69356288-8af85100-0c83-11ea-976a-eef55d87ce07.png)

Possibly a regression from #742, @Waqar144?

#### Steps to reproduce

Write `<http://hostname>` in a note.

#### Output from the debug section in the settings dialog

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Do. Nov. 21 17:21:23 2019`
**Version**: `19.11.17`
**Build date**: `Nov 20 2019`
**Build number**: `622`
**Platform**: `linux`
**Operating System**: `KDE neon User Edition 5.17`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.9.5`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`

**Comment by Waqar144** [comment]
Can't reproduce it. It has only one color, dark blue, on my side with `<http://hostname>`and light blue with `.com` at the end.
(Tried in qmarkdownedit and QOwnNotes both)

**Comment by pbek** [comment]
Now that's strange, I can reproduce it on different computers.

**Comment by Waqar144** [comment]
> Now that's strange, I can reproduce it on different computers.

Oh wait, I only tried on headings 😬

It's probably because of #742 since that's the only recent change done in the highlighting part.

**Comment by pbek** [comment]
No, I guess it was my fault. Will be fixed in the next release.

**Comment by pbek** [comment]
## 19.11.20
- fixed highlighting for links like `<http://hostname>`

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Waqar144** [comment]
working great!

**Comment by pbek** [comment]
Great, thank you for testing! (PS: check your emails) :grin:

**Comment by Waqar144** [comment]
> Great, thank you for testing! (PS: check your emails) grin

Just did. Awesome! :grin:
