### ISSUE TITLE
Wiki Links or Internal Links?

### ISSUE THREAD

**Issue by mlevison** [pbek/QOwnNotes#1437]
I'm trying to see if I can use QOwnNotes to implement the Zettelkasten process for note taking. Rather tagging a note, you link a to other notes it might be related to. 

The obvious approach would be to copy GitHub's: https://stackoverflow.com/questions/7653483/github-relative-link-in-markdown-file - specifically: 
`[Some other wiki page](path/to/some-other-wiki-page)`

**Comment by mlevison** [comment]
...just playing with MindForger - it supports:
Link to a Note in active MindForger repository:
`* [MF motivation](./why-mindforger.md#motivation)`

**Comment by pbek** [comment]
> [Some other wiki page](path/to/some-other-wiki-page)

You could do links like `[Some other wiki page](path/to/some-other-wiki-page.md)` or `<path/to/some-other-wiki-page.md>`. See #266. Just press `Ctrl + L` to link to a note.

**Comment by mlevison** [comment]
Ok - you're in fact two steps ahead of me - Thanks

**Comment by pbek** [comment]
:wink:
