### ISSUE TITLE
Repeatedly entering and exiting fullscreen breaks

### ISSUE THREAD

**Issue by Modelmat** [pbek/QOwnNotes#1438]
### Expected behaviour
Be able to go in and out of fullscreen as much as possible
#### Actual behaviour
"leave" accumulates in the footer and it becomes impossible to leave fullscreen.
![image](https://user-images.githubusercontent.com/25718989/69389318-cc3e3e80-0d1f-11ea-84a6-71b050ea2f26.png)

#### Steps to reproduce
1. Press F11 multiple times over and 
#### Relevant log output in the Log panel
Nothing shows?

**Comment by pbek** [comment]
Thank you for reporting, I wonder when that happened. 😁

**Comment by pbek** [comment]
Back with #1302 it worked like it should, I guess things have changed with the latest Qt version... Will be fixed in the next release.

**Comment by pbek** [comment]
## 19.11.20
- fixed a problem with the `leave` button showing up multiple times when repeatedly
  entering and exiting full-screen mode

**Comment by Modelmat** [comment]
Thanks!
Could you push the change out to the AUR package / other repos please?

**Comment by pbek** [comment]
There will be a release today.

**Comment by Modelmat** [comment]
Oh, I thought it had already been released given the changelog on the website.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Modelmat** [comment]
It is fixed now.

**Comment by pbek** [comment]
Great, thank you for testing!
