### ISSUE TITLE
Snap is using Qt 5.5.1, the version that comes with Ubuntu Xenial

### ISSUE THREAD

**Issue by pachulo** [pbek/QOwnNotes#1439]
#### Expected behaviour
As far as I can see here:

- https://github.com/pbek/QOwnNotes/blob/develop/snap/snapcraft.yaml#L7

Snap should be build using `base: core18`, and its corresponding Qt version: 5.9.5

- https://packages.ubuntu.com/bionic-updates/libqt5gui5

#### Actual behaviour
The snap is still using Qt 5.5.1, the version included in Ubuntu Xenial:

- https://packages.ubuntu.com/xenial-updates/libqt5gui5

Am I missing something?

Thanks!

**Comment by pbek** [comment]
Currently there are two snap releases in parallel:

1) https://code.launchpad.net/~pbek/+snap/qownnotes that uses https://github.com/pbek/QOwnNotes/blob/develop/build-systems/snap/snapcraft/snapcraft.yaml is used for releases only supports Core 16
2) https://build.snapcraft.io/user/pbek that uses https://github.com/pbek/QOwnNotes/blob/develop/snap/snapcraft.yaml doesn't support automatic releasing and is only used in the edge channel.

**Comment by pbek** [comment]
If there is a way to make 2) support automatic releases to the stable channel for anything that is build in the master git branch I'm all ears.

**Comment by pbek** [comment]
But it also would need the have the correct version number inserted like in 1).

**Comment by pachulo** [comment]
I'm not really sure I understand the problem with option (1...why do you say it does not support core18? I mean, even if it does not appear as an option when building snaps, if the `snapcraft.yaml` uses the `base: core18` and the “**Series**” option is set to “**Ubuntu Bionic, for Ubuntu Core 16**” everything should be fine.

**Comment by pbek** [comment]
> if the snapcraft.yaml uses the base: core18 and the “Series” option is set to “Ubuntu Bionic, for Ubuntu Core 16” everything should be fine.

are you sure that works with Launchpad? you still only can select the core 16 and last time I used another ubuntu version the snap didn't build because they Canonical didn't added support for the other selections yet.

![Screenshot 2019-12-01 at 06 36 45](https://user-images.githubusercontent.com/1798101/69910061-4d26c580-1405-11ea-8cc9-0d1b0a43e78b.png)

**Comment by pachulo** [comment]
Yeah, pretty sure; I'm using it for 2 snaps. More info:

- https://forum.snapcraft.io/t/core18-base-in-build-snapcraft-io/7715/2

**Comment by pbek** [comment]
That is awesome, I will try that, thank you very much! 👍🏻

**Comment by pbek** [comment]
## 19.12.1
- attempted to switch to Core18 for the snap release on Launchpad

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
Great, Core18 is working for me. Thanks again for the heads up!

## General Info

**Current Date**: `Di. Dez. 3 21:43:26 2019`
**Version**: `19.12.1`
**Build date**: `Dec  3 2019`
**Build number**: `630`
**Platform**: `linux`
**Operating System**: `Ubuntu Core 18`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Snapcraft`
**Qt Version (build)**: `5.9.5`
**Qt Version (runtime)**: `5.9.5`

**Comment by pachulo** [comment]
Great! Now that this is on place maybe we can make it look better, doing something similar to what they did here:

- https://github.com/keepassxreboot/keepassxc/pull/3057
- https://github.com/keepassxreboot/keepassxc/pull/2832

If I have some time I will be proposing the fixes soon.

Thanks to you for this software!

**Comment by pbek** [comment]
Great! :grin:
