### ISSUE TITLE
Link to note with multibyte character title

### ISSUE THREAD

**Issue by piyo-gh** [pbek/QOwnNotes#144]
Currently link to note doesn't support multibyte character title.
For example, any 3 character title like 'テスト' or 'ノート' become the same '&lt;note://___&gt;'.

Is there any plan to support in future version ?
Thanks,

**Comment by pbek** [comment]
I will look into that.

**Comment by pbek** [comment]
@piyo-gh, in case you want to help translating QOwnNotes into your wonderful language (I boldly assume you are Japanese) you can do so at: <https://crowdin.com/project/qownnotes/invite>
I'd really love to add Japanese as new language to QOwnNotes, since I love the Japanese culture so much. :bow:

**Comment by piyo-gh** [comment]
Ok, translation is done.

**Comment by pbek** [comment]
Three words... You Are Amazing! Thank you so much. I will integrate it into today's release!

**Comment by pbek** [comment]
I found a solution to support such links! It will be integrated into version 1.4.3.
Links like `<note://テスト>` can be generated and will be interpreted correctly. Can you please test this and report back when v1.4.3 is out?

**Comment by pbek** [comment]
Version 1.4.3 is now released.

**Comment by piyo-gh** [comment]
First of all, I appreciate for your work.
Most of the cases, link to note works fine without problem or with small adjustment.
It's great, even though it is may not perfect.
Thank you very much. :)

One thing that I felt strange is full width numbers.

- Make a new note titled '４月１６日'.
- Insert a link to this page with link dialog. ( &lt;note://４月１６日&gt; )

Above step is perfect but ...

- Click this link on preview panel.

Nothing happens. But instead &lt;note://\_月__日&gt; can jump.

**Comment by pbek** [comment]
It seems that somehow the full with numbers get translated to "normal" numbers by Qt, I'm not sure yet if I can fix that... :/

**Comment by piyo-gh** [comment]
Thank you for your explaining.

In that case, it is Ok. This was just a test.
I usually don't use full width numbers, so this is not a problem for me.

Now, I will close this issue. Thank you very much for your time.

**Comment by pbek** [comment]
Last night I was thinking of a workaround. I will test my idea today... Maybe I can do something about it. 😸

**Comment by pbek** [comment]
In 16.04.12 I added support for full width numbers in note names when linking notes with unicode characters! Can you please test it when it is release?

**Comment by piyo-gh** [comment]
Thank you for trying.
But unfortunatelly, it doesn't work as expected.

- I made 4 notes.

`一月` (chinese numeral)
`２月` (full width)
`３月` (full width)
`五月` (chinese numeral)

- And I made 7 links to notes and clicked. `4月` (digit) and `七月` (chinese numeral) are invalid links.

`<note://一月>` 一月 was opened (correct)

`<note://２月>` 一月 was opened (wrong)

`<note://３月>` 一月 was opened (wrong)

`<note://4月>` 一月 was opened (wrong)

`<note://五月>` 五月 was opened (correct)

`<note://6月>` 一月 was opened (wrong)

`<note://七月>` no note was opened (correct)

**Comment by pbek** [comment]
The workaround for the number problem was to enter a wildcard character instead of the numbers if unicode characters where used. That's why other notes can be found...

Can you please write down all full width numbers for me. What does `一` represent? 0?

**Comment by pbek** [comment]
I gave it an other hour, but then I realised Qt doesn't support version 3 (with regular expressions) of SQLite. I fear I can't make a workaround for this QTextEdit behaviour... I will close this issue until I find an other solution.

**Comment by pbek** [comment]
I really found an other way to deal with it.
These notes will now be recognized correctly.
```
<note://４月１６日>
<note://６月１６日>
```

I will try and make you a new release tomorrow. Can you please test it then?

**Comment by pbek** [comment]
Version 16.04.13 is out now. :tada:

**Comment by piyo-gh** [comment]
Yes, it works, thank you.
This workaround is enough for me.

**Comment by pbek** [comment]
great!
