### ISSUE TITLE
MacOS: Indentation on mouseover in the folders and notes panel

### ISSUE THREAD

**Issue by ivanpirog** [pbek/QOwnNotes#1444]
Video: https://youtu.be/DtLKlg814e4

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue on macOS (can't reproduce it on KDE Neon).

**Comment by pbek** [comment]
Can you please post the output from the debug settings (see issue template).

**Comment by ivanpirog** [comment]
[QOwnNotes Debug Information.txt](https://github.com/pbek/QOwnNotes/files/3882990/QOwnNotes.Debug.Information.txt)

**Comment by ivanpirog** [comment]
> Thank you for reporting, I will try to reproduce your issue on macOS (can't reproduce it on KDE Neon).

**Comment by pbek** [comment]
> QOwnNotes Debug Information.txt

thank you, but please paste the text directly to the issue next time (there is a button for that in the *Debug settings*). otherwise everyone needs to download and open the file first. 😁

**Comment by pbek** [comment]
I spent more than half an hour on https://github.com/pbek/QOwnNotes/blob/develop/src/libraries/qdarkstyle/style.qss, but I can't find a way to force a negative distance between icon an text in `QListView::item`

**Comment by Waqar144** [comment]
Can't reproduce it on Linux. It looks very nice though :grin: 
@pbek have you been able to reproduce it yourself on macOS?

**Comment by pbek** [comment]
>  @pbek have you been able to reproduce it yourself on macOS?

Yes, but I couldn't find a CSS selector to work on the space between icon and text on hover.

> it looks very nice though 😁

I think so too, let's just call it a macOS exclusive feature! 😆
