### ISSUE TITLE
Bug: Cannot enter image size in insert image dialogue

### ISSUE THREAD

**Issue by Modelmat** [pbek/QOwnNotes#1445]
#### Expected behaviour
Typing in a number (e.g. 100px) into the size box should change the size of the image to that value, much like moving the slider.
#### Actual behaviour
The image remains the same size.
![image](https://user-images.githubusercontent.com/25718989/69492565-97d1aa80-0ef8-11ea-9634-1f0d116727c9.png)
![image](https://user-images.githubusercontent.com/25718989/69492613-13335c00-0ef9-11ea-9d83-0e6e7d54c0e0.png)

#### Steps to reproduce
1. Grab a URL/file and open the insert image dialogue
2. Type in the scaling width box a new number
#### Output from the debug section in the settings dialog
NIL?
#### Relevant log output in the Log panel
NIL?

**Comment by pbek** [comment]
Thank you for reporting, I think I haven't implemented that yet. 😆

**Comment by pbek** [comment]
## 19.11.21
- you can now also set the horizontal pixels directly in the *Image dialog*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Modelmat** [comment]
Yup, it does. Thanks!

**Comment by pbek** [comment]
Great, thank you for testing!
