### ISSUE TITLE
Feature Request: Enter Text When Inserting Tables

### ISSUE THREAD

**Issue by Modelmat** [pbek/QOwnNotes#1446]
![image](https://user-images.githubusercontent.com/25718989/69492759-77a2eb00-0efa-11ea-8d97-e5db4c903f3d.png)

Entering values in this manner in the create table dialogue does not create a table containing these values. This is unintuitive, and it seems to be only used for selecting what squares you want.

I would like to see the ability to enter text here and the rows x columns be defined to where the text is at.

**Comment by pbek** [comment]
Thank you for your suggestion.
Currently that table grid is only there to be able to select your table size. I didn't even try to add text in it so I didn't disable the editing. 😁

**Comment by Modelmat** [comment]
Haha :)

**Comment by pbek** [comment]
## 19.11.21
- you can now not only select the table layout in a table widget in the *Table dialog*,
  but also **enter text directly in the fields** which will be used as table text when
  inserting the table
    - if you enter text then all the spinboxes to define the table specs will
      be updated automatically
    - if you select a table layout via mouse after text was added to the table
      the spinboxes will now only update if you are selecting a larger range
      than the text entered

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by iolivier87** [comment]
Yeah, I like it ! It works for me.

A few comments :
- only 2 or 3 caracters are visible for now. 6 as suggested by @Modelmat (or more) should be better.
- row or column can't be removed : once the text is erased, the row/column numbers remain the same. Then, empty row/column are inserted and cause formating errors.

**Comment by pbek** [comment]
Great, thank you for testing!

> only 2 or 3 caracters are visible for now. 6 as suggested by @Modelmat (or more) should be better.

for me 6 are visible (on KDE Neon)

> row or column can't be removed : once the text is erased, the row/column numbers remain the same. Then, empty row/column are inserted and cause formating errors.

the main function of this dialog is to give you a scaffolding for an empty table in your note edit... and it's a one way thing, you cannot edit your dialog with this dialog. it would need a lot more spreadsheet software functionality to really make that useful...
but right now at least you can press `Ctrl + Space` inside your markdown table to adapt all column widths

**Comment by iolivier87** [comment]
> for me 6 are visible (on KDE Neon)
Another computer with Windows 10 and I have 4 to 5 characters.
it seems to be screen dependant

> but right now at least you can press `Ctrl + Space` inside your markdown table to adapt all column widths
Thanks, i didn't know this shortcut.

**Comment by Modelmat** [comment]
This works for me.
One minor annoyance is that pressing enter does not go down a line (like in Excel) but instead adds the table. I can, of course, use the down arrow, but I would prefer the enter key to go down a row and ctrl+enter to add.

**Comment by pbek** [comment]
> One minor annoyance is that pressing enter does not go down a line (like in Excel) but instead adds the table. 

I will ignore the Enter key for the whole dialog.

**Comment by pbek** [comment]
## 19.11.22
- the return key is now ignored in the *Table dialog* so you can better edit text
  in the table

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by iolivier87** [comment]
Yes, the return key is ignored now.

**Comment by pbek** [comment]
Great, thank you for testing!
