### ISSUE TITLE
GUI interface suggestions

### ISSUE THREAD

**Issue by Loelo** [pbek/QOwnNotes#145]
Hi, first thanks a lot for this wonderful app that replace nvpy for me (and notational velocity when I used mac os, now I'm on Linux). I just jumped from 1.2.n to 1.4.2 and I am bothered by two things that could be easily corrected I guess:

- icons next to the note titles :  could be option-able,

- more important : the markdown tab have disappeared and having two windows/panes next to each others is not usable on my 1024pixel width screen : too narrow. I really preferred the tabs. So maybe two options, or buttons and/or in menu to make it usable : 1- vertical split / horizontal split for the two windows/panes (with markdown down the screen for horizontal split), 2- markdown only (useful to simply read notes) / text only, when only one window is open.

Keep on the good work and have a nice day !

**Comment by pbek** [comment]
Thank you for your kind words and your suggestions. I will look into them!

**Comment by pbek** [comment]
In version 16.04.12 it will be possible again to toggle the note edit pane. Can you please test that after it was released?

**Comment by Loelo** [comment]
Hi, yes, sure, as long as I have a .deb to test.
Actual version is 1.4.3, and I do not understand the "16.04.12" number.
Strangely, with 1.4.3, when I toggle the markdown pane/view/windows nothing happen and no markdown pane shows up.

**Comment by pbek** [comment]
QOwnNotes now switched the release versioning to a more *rolling release style*, so it doesn't get confused with semantic versioning
`<year of release>.<month of release>.<release number in the month>` 

Can you try to pull it out from the left side of the QOwnNotes window? Maybe the markdown view just has a width of 0.

**Comment by Loelo** [comment]
1. I see for numbering. Thanks for the precision.
2. Yes indeed the pane was 0 pix width. Sorry about that. So it toggles well but panes are narrow and less usable for me than the 1.3.9 tabs. Is there a difference compared to 1.4.2 ?
![off](https://cloud.githubusercontent.com/assets/11534708/14586093/39a2c3b4-048d-11e6-998b-dc43c22576eb.png)
![on](https://cloud.githubusercontent.com/assets/11534708/14586094/39a37390-048d-11e6-9e2e-ab6b4bd44eef.png)

**Comment by pbek** [comment]
Yes, the difference is you can now have edit and preview panes side by side. In the next version it also will be possible to turn off the edit pane to kind of mimic the old behavior.

**Comment by Loelo** [comment]
Thanks for the precision. So "turning off and on/toggle the edit pane" will be in the next version (which will be numbered 16.02.12 instead of 1.4.4 if I understand it well). So I will test that when it is out of "the opensuse building box". As for the side by side panes I think that an optionable horizontal split with the markdown pane below the edit pane (instead of the vertical split with markdown pane at the right side) would be a useful addition for people with rotated screen like me and for people who prefer this layout.

**Comment by pbek** [comment]
I will consider a vertical split.
Meanwhile v16.04.12 is released (currently building on OBS).

**Comment by Loelo** [comment]
Thanks. I'll test v16.04.12 when available.  Have a nice sunday ! ☺

**Comment by pbek** [comment]
I just installed it under Manjaro. ;) Have a nice Sunday too!

**Comment by Loelo** [comment]
Just tested. Toggle works but **notes list pane keeps changing width** as toggle in on or off : would it be possible to block note list pane width to the value chosen by the user and to only allow changes for the two others panes (editor and markdown) ?

**Comment by pbek** [comment]
What is it that you are trying to achieve?

**Comment by Loelo** [comment]
Thank you for your fast answer, I am impressed by the way by on much development you have done in QOwnNotes since a few weeks ! 
I just try to mimic the 1.3.8 on click tab behavior (that is an easy switch between text editor and markdown view in all the space right to the note list, that stayed with a fixed width.

Here is the behavior I have:

Editor view:
![1](https://cloud.githubusercontent.com/assets/11534708/14587817/07bf7e32-04ba-11e6-81e3-5fa09dee01de.png)

One click to toggle on markdown view:
![3](https://cloud.githubusercontent.com/assets/11534708/14587829/26025d92-04ba-11e6-92ef-6e9e66ca8883.png)

Another click to toggle off editor view:
![2](https://cloud.githubusercontent.com/assets/11534708/14587821/1319538e-04ba-11e6-936b-c9b61201a378.png)

**Comment by pbek** [comment]
What is your workflow? You edit a note and then you want to switch to the markdown view to see how it looks in markdown?

**Comment by Loelo** [comment]
Yes, just like with the tabs in <=1.3.8 versions.

**Comment by pbek** [comment]
And you can't live with seeing the markdown view and the note edit view at the same time?
... with the prospect of having a vertical view some day

**Comment by Loelo** [comment]
No problem, that's all right, I'm just trying to help improve QOwnNotes and test the features, but of course I can adapt myself to it 😌. And you're right, the vertical split will solve this layout issue for narrow screens or narrow windows.

**Comment by pbek** [comment]
Let's wait for it then. ^_^

**Comment by pbek** [comment]
Christmas came early this year. :)
In v16.04.13 you can now also **split** the note edit pane and note markdown preview **vertically** instead of horizontally to gain more space on screens with lower vertical resolution.
Can you please test and report back?

**Comment by pbek** [comment]
Version 16.04.13 is out now. :tada:

**Comment by Loelo** [comment]
Hi ! Wow that was fast and it works perfectly ! This is far better for narrow screen like mine when I want to use live markdown preview or switch to markdown preview only. Thanks a lot ! 
![](https://handylinux.org/forum/plugins/ezbbc/style/smilies/merci.gif)

**Comment by pbek** [comment]
Great, makes me happy. :) Since you now have more screen real estate for your note edit pane I will close this issue.

**Comment by pbek** [comment]
@Loelo btw. if you are speaking an other language than English and you want to help translating QOwnNotes you can happily do so at <https://crowdin.com/project/qownnotes/invite>. :tada:

**Comment by Loelo** [comment]
Ok, I'll have a look at the french translation to contribute to. (I tought it was 100% but I just saw it is near 60%).

**Comment by pbek** [comment]
That's awesome, thank you very much! :clap:
