### ISSUE TITLE
[Feature request] Improve HTML generation and CSS styling

### ISSUE THREAD

**Issue by neirenoir** [pbek/QOwnNotes#1453]
While the current Markdown to HTML transpiler works right for the purposes of a quick preview, it is far from "pretty" or human readable. While this is not an issue in and on itself, it also makes styling or editing via noteToMarkdownHtmlHook really difficult.

#### Actual behaviour
Markdown to HTML generation produces a "dirty"-looking document with: inline styling, tags as styling aids (the text of title nodes consists of two \<span\> tags that separate the first character of the title and the rest of it, for no particular reason), and also doesn't respect text blocks, such as the code block, which, instead of producing a \<pre\> box that opens and closes whenever the original Markdown document does, produces a different \<pre\> box every time there is a double linebreak.

#### Expected behaviour
Markdown to HTML generation produces a "clean" document that can be both modified and styled via noteToMarkdownHtmlHook, or styled later when included inside another webpage (think someone writing their blog entries using QOwnNotes).

#### Proposed solution
I'm not sure if this is a limitation of Hoedown, or if it can be configured in any other way to generate a cleaner HTML document. Given Hoedown seems to be unmaintained now, if such a thing is not possible with the current version of the library, it may be a good time to consider moving to a different library. 
Alternatively, something that would make QOwnNotes very flexible would be implementing a method in the scripting API to allow a script to replace the Markdown to HTML generation. While doing so in JS doesn't seem the most efficient thing, it would also allow users to include parsers with custom tags, or even write renderers for languages other than Markdown, such as org-mode.
Also, from what I am seeing (correct me if I am wrong), it seems HTML generation is also used for PDF rendering; if the aforementioned suggestion is implemented, it could be a good idea to let the script know whether it is rendering for the preview/HTML or a PDF. Allowing users to easily style the resulting PDF using CSS could be a huge deal if implemented, to the point I would consider dropping other WYSIWYG editors I use for day to day writing.
**EDIT:** just realized noteToMarkdownHtmlHook DOES allow the replacement of hoedown, sort of. It does not skip the generation of HTML via hoedown, but it works for the time being.

With that out of the way, I would also like to congratulate the developers on the program. The workflow is superb and everything I had been looking for in a text editor, let alone a note taking program. :)

**Comment by pbek** [comment]
Why don't you just use https://pandoc.org/ to convert markdown to HTML? You could write a QOwnNotes script to do that.

**Comment by shirona** [comment]
Pandoc could work for publishing. I mean, maybe it could work for the preview as well if used with noteToMarkDownHtmlHook and startSynchronousProcess. Not sure about the performance implications of that, but I can probably work with it. Thank you!

**Comment by Waqar144** [comment]
> While the current Markdown to HTML transpiler works right for the purposes of a quick preview, it is far from "pretty" or human readable. 

Hi, I am not sure what you mean. The HTML is pretty readable to me (apart from the injected CSS at the top)

> Markdown to HTML generation produces a "dirty"-looking document with: inline styling, tags as styling aids (the text of title nodes consists of two <span> tags that separate the first character of the title and the rest of it, for no particular reason)

I just tested with a simple document and then exported it via 'Export to HTML' option in the menu. I don't see any any multiple span tags separating first character and the rest. Can you give an example doc? This maybe related to another bug that drives me crazy sometimes.

> #### Proposed solution
> 
> I'm not sure if this is a limitation of Hoedown, or if it can be configured in any other way to generate a cleaner HTML document. Given Hoedown seems to be unmaintained now, if such a thing is not possible with the current version of the library, it may be a good time to consider moving to a different library.

IMO, hoedown is the best we got as far as I know. If you know about any recent forks of hoedown, feel free to let me know. Hoedown is pretty solid in what it does though, and it is FAST, which is very important when it comes to showing live preview.

**Comment by shirona** [comment]
>I just tested with a simple document and then exported it via 'Export to HTML' option in the menu.

Ah, that's where I did wrong. I right-clicked the preview and selected `Export generated raw HTML`, which has the result linked below. Using the `Export to HTML` option in the menu produces a rather clean looking HTML. So yeah, I think this was just PEBCAK on my part.

[sampledown.txt](https://github.com/pbek/QOwnNotes/files/3890337/sampledown.txt)

**Comment by pbek** [comment]
`Export generated raw HTML` is more for debugging or if you really want what was generated in the preview...

**Comment by Waqar144** [comment]
> > I just tested with a simple document and then exported it via 'Export to HTML' option in the menu.

Also look at #1421

**Comment by r00tr4v3n** [comment]
This might be what you were looking for concerning the PDF export: [PR](https://github.com/pbek/QOwnNotes/pull/1769)

**Comment by pbek** [comment]
I will close this issue until there is more information.
