### ISSUE TITLE
Disabling tab-to-spaces conversion?

### ISSUE THREAD

**Issue by shirona** [pbek/QOwnNotes#1455]
Currently, QOwnNotes replaces any tab presses with four spaces to transform indented paragraphs into code blocks. While this is helpful when copy-pasting tab-indented code from somewhere else, it doesn't let "normal" paragraphs (paragraphs with an indented first line, which is used in literature or more formal documents) be written without being automatically detected as code.

I've been searching through the settings menu in 19.11.14 and the Issues list, but I can't find any switch that lets me disable this. Is there any option for it?

**Comment by pbek** [comment]
> it doesn't let "normal" paragraphs (paragraphs with an indented first line, which is used in literature or more formal documents) be written without being automatically detected as code.

Are you using that in Markdown? Markdown doesn't care about what kind of whitespaces are used.

> I've been searching through the settings menu in 19.11.14 and the Issues list, but I can't find any switch that lets me disable this. Is there any option for it?

No sorry, currently that's all hard-coded on a lot of places.

**Comment by shirona** [comment]
>Are you using that in Markdown?

No, I don't use tabs in other Markdown editors, sorry. Tabs in vanilla Markdown are a tricky subject, given the web-centric nature of it; people often resort to dirty CSS hacks to implement tabs or tab-like behaviour, usually because of the way Markdown-formatted plaintext is converted to HTML. HTML itself hates tabs and whitespace in general, so I guess that's the reason Markdown was designed without a feature to translate tabs into web-friendly whitespace.
However, if QOwnNotes was able to keep tabs in the editor when inserted, it could easily be kept in the compiled document with some preNoteToMarkdownHtmlHook replacements. The easiest way would be replacing tabs with four hard spaces, but replacing it with a styled \<span\> could work as well.
Right now, you can simulate tabs in the preview by writing `&nbsp;` several times, but it kind of defeats the purpose of using Markdown in the first place.

>No sorry, currently that's all hard-coded on a lot of places.

Could such a toggle be implemented without much trouble? I would love such a feature.

**Comment by pbek** [comment]
> Could such a toggle be implemented without much trouble? I would love such a feature.

It would be complex, because then a "Tab as X spaces" handling would be needed to be implemented for everything including highlighter, block intention, etc

**Comment by pbek** [comment]
> Currently, QOwnNotes replaces any tab presses with four spaces to transform indented paragraphs into code blocks.

Where does that happen for you? QOwnNotes works with tabs...

**Comment by pbek** [comment]
## 19.12.10
- you now can choose if you want to use a **<kbd>Tab</kbd> or spaces** to **indent text**
  in the *Editor settings*
    - you can also choose how many spaces should be used
    - this also works with indenting selected text and in lists
    - now **by default four spaces** will be used to **indent text** instead of a <kbd>Tab</kbd>

**Comment by sanderboom** [comment]
Great feature! Using the default (4 spaces) makes unindentation (`shift-tab`) less functional:

![Peek 2019-12-18 12-43](https://user-images.githubusercontent.com/5956570/71083887-58fbe100-2194-11ea-845c-4cd721138e60.gif)

Most editors unindent by the same type/amount of spaces as indent. Is this something you can add? Cheers.

**Comment by pbek** [comment]
Upgrading the inline indenting is still very tricky and possibly on my todo list, but if you select the whole block you can already indent and un-indent with the same characters. (there will be more of the latter later today)

**Comment by pbek** [comment]
## 19.12.11
- improved text indentation of selected text blocks

**Comment by pbek** [comment]
This one is for you, @sanderboom...

## 19.12.12
- improved text un-indentation of list elements

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by sanderboom** [comment]
> This one is for you, @sanderboom...

Haha, thanks for thinking about me man!

I don't want to act spoiled, but.. it looks like it's not working. My test:

```
- test
    - test
    - test<cursor_here>
```

And pressing `shift+tab`. Nothing happens :cry:

**Comment by pbek** [comment]
That never worked, didn't it?
I was improving the thing you tested in above video. You press enter in a list, you get a new empty list item, you are able to un-indent it by 4 spaces.

**Comment by sanderboom** [comment]
Ah I see. The distinction is between unindenting for an list-item with text and without text. Unindenting without text works! Unindenting with text does not work (yet? :wink: )

**Comment by pbek** [comment]
## 19.12.14
- you can now remove multiple indent-character inside of text when indenting with spaces

**Comment by pbek** [comment]
@sanderboom you can use this one for un-indenting when the cursor is in the area with the spaces

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by sanderboom** [comment]
> @sanderboom you can use this one for un-indenting when the cursor is in the area with the spaces

Tested and now `shift-tab` does the right thing when:
- when the indented listitem is empty
- when the cursor is the area before `-`

Not yet:
- when the indented listitem is not empty and the cursor is on the text

On the right track, thanks! :raised_hands:

**Comment by pbek** [comment]
> when the indented listitem is not empty and the cursor is on the text

I'll save that one for a rainy day :smile:

**Comment by sanderboom** [comment]
> I'll save that one for a rainy day 

/me goes off to check your weather forecast :wink: 

It seems so easy: 

- `shift+tab` is registered
- if no selection present
- get current line
- look up indentation style (`\t` or nr of spaces)
- chop of 1 instance of indentation from the start
- replace current line with outcome

But probably there are complicating factors  :sweat_smile:
