### ISSUE TITLE
Lots of alerts when the note folder is lost

### ISSUE THREAD

**Issue by iolivier87** [pbek/QOwnNotes#1456]
#### Expected behaviour
If the notefolder isn't found anymore while QON is opened, only one alert should be displayed.

#### Actual behaviour
Lots of alerts are displayed :
![alerts](https://user-images.githubusercontent.com/21123707/69578766-71337280-0fd1-11ea-8c27-da0f3a3f8750.png)

#### Steps to reproduce
Open QON and move or rename the note folder.
It happens on my computers when my encrypted vault closes itself (for some unknown reason).

#### Request
Add a button in the alert to reload the notefolder. For now, I restart QON to do that.

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
I only get one error message when I rename the note folder.

**Comment by pbek** [comment]
Every time the note index is (re-)created (`MainWindow::buildNotesIndex`) it is possible to get such an error message. I guess your vault was modifying a lot of files over a short period if time and every time the note index got rebuilt.

Can you really reproduce your issue with renaming the note folder?

**Comment by iolivier87** [comment]
You're right, I have only one alert if I rename the note folder. The numerous alerts are only when I close the encrypted vault while QON is opened.

**Comment by pbek** [comment]
I cannot even close my vault while QOwnNotes is open.

**Comment by iolivier87** [comment]
It doesn't matter, this issue is quite rare and seems to be specific to Cryptomator.

**Comment by pbek** [comment]
Ok, I will close this issue until there is more information.
