### ISSUE TITLE
bug: text cursor jumps to last search word

### ISSUE THREAD

**Issue by dh-connect** [pbek/QOwnNotes#146]
when you search for a word (above the notes list) and you start to work is that selected note (without removing the search word) on a different position in the notes text, the cursor jumps to the last search word in the text after saving, so you loose focus each time the note is saved, when you are writing you suddenly start to write on a different position

version: 1.4.2
workaround: deselect search word by clicking the x next to it

**Comment by pbek** [comment]
I wonder when that crept in. Thank you for the report!

**Comment by pbek** [comment]
I could reproduce the problem under the condition that the note folder is modified externally while editing the note. The notes will get reloaded then and the filtering takes place again. I found a workaround and integrated it in the the future version 1.4.3.
Could be please be so kind and test the version when it will be released later today?

**Comment by pbek** [comment]
Version 1.4.3 is now released.

**Comment by dh-connect** [comment]
good jobs, works now
