### ISSUE TITLE
[Feature Request] Style generated HTML off Editor Colours

### ISSUE THREAD

**Issue by Modelmat** [pbek/QOwnNotes#1462]
Change editor colours inside the editor pane should reflect any changes in the preview pane. For example, changing the title colour to blue should change the title in the preview to blue as well.

This is currently possible to writing the CSS using the custom preview CSS script, however, being able to sync the changes between both the editor and the preview in terms of colours and font sizes would be great.

**Comment by pbek** [comment]
Although parts of the styling of the markdown text doesn't make much sense in the preview, I guess that could be done.

**Comment by Modelmat** [comment]
Yeah, of course.
Thanks a lot for the quick fixes, I'll test when released.

**Comment by pbek** [comment]
Not done yet.

**Comment by pbek** [comment]
Was a bit tricky to implement but looks quite funny. :grin:

**Comment by Modelmat** [comment]
Oh, I thought that 4f3263b67e2eca1bc303d74bf674c7a153bf49e4 had fixed it.
What exactly look strange?

**Comment by pbek** [comment]
>  What exactly look strange?

No, I like it.

**Comment by Modelmat** [comment]
Oh okay. Could I see a screenshot?

Thanks for implementing, QOwnNotes is awesome!

**Comment by pbek** [comment]
## 19.11.23
- now most of the editor styling will be also used in the preview by default
    - this can be turned off in the *Preview settings*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Modelmat** [comment]
Yup, it works. It looks great too.

**Comment by pbek** [comment]
Great, thank you for testing!
