### ISSUE TITLE
little enhancement: renaming tags

### ISSUE THREAD

**Issue by dh-connect** [pbek/QOwnNotes#147]
when you rename a tag the number in the braket will become part of the tag if you dont delete it, it would be better when you double click just to edit the name without the number

**Comment by pbek** [comment]
Oh, you are right. I will look into that. Thanks for the report!

**Comment by pbek** [comment]
It took quite a while, but I found a workaround for that problem. It is implemented in version 16.04.12. Can you please test it when it will be released (in the next 30min)?

**Comment by dh-connect** [comment]
yes works good

**Comment by pbek** [comment]
great, thanks
