### ISSUE TITLE
Connecting to NextCloud storage

### ISSUE THREAD

**Issue by raelb** [pbek/QOwnNotes#1472]
Hi there,
I just want to confirm I understand correctly. The only reason to connect to NextCloud storage is to gain access to past revisions of a note and deleted notes.

As far as syncing is concerned this is not handled by QOwnNotes. This is handled by the NextCloud desktop client. (on Windows)
Thanks!

**Comment by pbek** [comment]
Correct, see https://www.qownnotes.org/Knowledge-base/Why-isn-t-QOwnNotesAPI-syncing-my-notes

> The only reason to connect to NextCloud storage is to gain access to past revisions of a note and deleted notes.

and you can of course use the NC Notes web and mobile apps.

**Comment by raelb** [comment]
Thanks for the quick response.

OT: Is there only 1 NC Notes mobile app? I found this https://play.google.com/store/apps/details?id=it.niedermann.owncloud.notes&hl=en. It looks like the main app, but I thought it somewhat strange that there is a fee.

**Comment by pbek** [comment]
Yes, that's the one and (afaik) it's done by a private individual. You can also get it for free on F-Droid.
