### ISSUE TITLE
Headline background highlighting

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1473]
#### Expected behaviour

Headline background highlighting across whole line.

#### Actual behaviour

Headline background highlighting only after `#` characters.

![image](https://user-images.githubusercontent.com/1798101/69974521-b30a6e80-1525-11ea-925d-efd26ef424a0.png)

## General Info

**Version**: `19.12.0`
**Build date**: `Dec  1 2019`
**Build number**: `629`
**Platform**: `linux`
**Operating System**: `KDE neon User Edition 5.17`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.9.5`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`

**Comment by pbek** [comment]
Seems like a regression from https://github.com/pbek/qmarkdowntextedit/pull/30, @Waqar144

**Comment by Waqar144** [comment]
Ah yes,

Here I believe

https://github.com/pbek/qmarkdowntextedit/blob/fee1302fae77bb0b70ce0ed1f6a23fe521a45505/markdownhighlighter.cpp#L485

**Comment by pbek** [comment]
## 19.12.1
- fixed headline background highlighting (for [#1473](https://github.com/pbek/QOwnNotes/issues/1473), thank you @Waqar144)
