### ISSUE TITLE
Problem toggling markdown and tag panels

### ISSUE THREAD

**Issue by scantem** [pbek/QOwnNotes#148]
Not sure what I've done but for some reason I can no longer view the markdown and tag panels. When I click the toggle markdown icon on the tab bar or in the dropdown menu nothing happens, when I click the toggle tag button the "Add Tag" button displays at the bottom but I don't see the list of tags. Strangely this happens with both QownNotes on my Windows machine and on my Linux laptop (with the notes shared via Owncloud) so I'm wondering if it's something to do with my notes themselves.

Below is debug info from my Windows box:

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mon Apr 18 11:48:01 2016`
**Version**: `16.04.12`
**Build date**: `Apr 17 2016`
**Build number**: `1410`
**Platform**: `windows`
**Operating System**: `Windows 8.1`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version**: `5.5.1`

## Server Info

**serverUrl**: `http://owncloud.app`
**appIsValid**: `yes`
**serverVersion**: `8.1.1.3`
**appVersion**: `0.4.2`

## Settings

**DistractionFreeMode/editorWidthMode**: `2`
**DistractionFreeMode/isEnabled**: `false`
**DistractionFreeMode/mainSplitterSizes**: `<binary data>`
**DistractionFreeMode/menuBarGeometry**: `<binary data>`
**DistractionFreeMode/menuBarHeight**: `21`
**DistractionFreeMode/windowState**: `<binary data>`
**LastUpdateCheck**: `2016-04-18T11:34:37`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `24`
**MainWindow/markdownDefaultViewMode**: `true`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `Courier,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `Courier,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/showRecentNoteFolderInMainArea**: `false`
**MainWindow/windowState**: `<binary data>`
**PiwikClientId**: `<hidden>`
**ShowSystemTray**: `false`
**SortingModeAlphabetically**: `false`
**TodoDialog/geometry**: `<binary data>`
**TodoDialog/mainSplitterState**: `<binary data>`
**TodoDialog/showCompletedItems**: `0`
**TodoDialog/todoListSelectorSelectedItem**: `personal`
**activeTagId**: `0`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `false`
**appMetrics/notificationShown**: `true`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**darkModeColors**: `false`
**defaultNoteFileExtension**: `md`
**demoNotesCreated**: `true`
**disableAutomaticUpdateDialog**: `false`
**externalEditorPath**: *empty*
**interfaceLanguage**: *empty*
**mainSplitterSizes**: `<binary data>`
**markdownViewEnabled**: `false`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `0`
**noteEditPaneEnabled**: `true`
**noteSaveIntervalTime**: `10`
**notesPath**: `C:/Users/Simon/ownCloud/Notes`
**notifyAllExternalModifications**: `false`
**ownCloud/localOwnCloudPath**: `C:/Users/Simon/ownCloud`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: `http://owncloud.app`
**ownCloud/todoCalendarBackend**: `0`
**ownCloud/todoCalendarEnabledList**: `personal`
**ownCloud/todoCalendarEnabledUrlList**: `http://owncloud.app/remote.php/caldav/calendars/simon/personal/`
**ownCloud/todoCalendarUrlList**: `http://owncloud.app/remote.php/caldav/calendars/simon/personal/`
**ownCloud/userName**: `simon`
**recentNoteFolders**: *empty*
**skipVersion**: `1.4.3`
**tagsEnabled**: `false`
**versionSplitterSizes**: `<binary data>`

**Comment by scantem** [comment]
Trashing the sqlite db and starting again has fixed this, I've kept a copy of the broken db file if you'd like to investigate what happened.

Thanks for the great app, I'm using it daily.

**Comment by pbek** [comment]
@scantem thank you for your kind words and your report. Did you also trash your settings? Because my wild guess is that the panels you couldn't see just had a width of 0 and needed to be "pulled out" of the left or right side of the screen. I think I might integrate something that does that automatically.

**Comment by scantem** [comment]
I made a backup of C:\Users\%user%\AppData\Roaming\PBE\QOwnNotes (containing the sqlite file) and then ran _Clear app data and exit_, were the settings in the sqlite DB or do you store them in the registry? I can check my Linux desktop when I get home later today, I haven't fixed that one yet.

I was thinking that the panels were just hidden at the side and tried hovering by the edge of the window to grab them but couldn't get that to work.

**Comment by pbek** [comment]
The settings are stored in the manner the OS is preferring it to store. Win: Registry, OS X: Plist, Linux: Ini. So under Windows the settings are gone.

If it was a 0 size problem you should be able to resize the panel if it is also set to "visible" (with their toggle-button). 

It would help if you could recheck under Linux.

**Comment by scantem** [comment]
I ssh'd home and checked it via VNC and tried grabbing the edges after making sure the markdown panel was turned on but it just resized the entire window. The config is as follows:

```
[General]
LastUpdateCheck=@Variant(\0\0\0\x10\0%\x7f\x99\x3\x41G\xa6\xff)
PiwikClientId=80ca5f76fedc8da4
ShowSystemTray=false
SortingModeAlphabetically=false
activeTagId=0
cryptoKey=*redacted*
currentNoteFolderId=1
darkModeColors=false
defaultNoteFileExtension=md
disableAutomaticUpdateDialog=true
externalEditorPath=
interfaceLanguage=
mainSplitterSizes=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x4\0\0\0\0\0\0\0\xfb\0\0\x3\xb2\0\0\0\0\x1\0\0\0\0\x1\0\0\0\x1\0)
markdownViewEnabled=true
noteSaveIntervalTime=10
notesPath=/home/simon/ownCloud/Notes
notifyAllExternalModifications=false
recentNoteFolders=
tagsEnabled=false

[MainWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\x1\x43\0\0\0\x17\0\0\x6-\0\0\x3\x91\0\0\x1M\0\0\0\x44\0\0\x6#\0\0\x3\x87\0\0\0\0\0\0\0\0\a\x80)
mainToolBar.iconSize=24
markdownDefaultViewMode=false
menuBarGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\0\0\0\0\0\0\0\0\x4\xd6\0\0\0\x13\0\0\0\0\0\0\0\0\xff\xff\xff\xff\xff\xff\xff\xff\0\0\0\0\0\0\0\0\a\x80)
noteTextEdit.code.font="Courier,9,-1,5,50,0,0,0,0,0"
noteTextEdit.font="Sans Serif,9,-1,5,50,0,0,0,0,0"
noteTextView.code.font="Courier,9,-1,5,50,0,0,0,0,0"
noteTextView.font="Sans Serif,9,-1,5,50,0,0,0,0,0"
showRecentNoteFolderInMainArea=false
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x4\xd7\0\0\x2\xf3\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\x16\0m\0\x61\0i\0n\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)

[TodoDialog]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\x1\xa2\0\0\0\x1f\0\0\x6\xbe\0\0\x4\x1e\0\0\x1\xac\0\0\0\x44\0\0\x6\xb4\0\0\x4\x14\0\0\0\0\0\0\0\0\a\x80)
mainSplitterState=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x1\x12\0\0\x1r\x1\xff\xff\xff\xff\x1\0\0\0\x1\0)
showCompletedItems=0
todoListSelectorSelectedItem=personal

[appMetrics]
disableAppHeartbeat=false
disableTracking=false
notificationShown=true

[networking]
ignoreSSLErrors=true
proxyType=0

[ownCloud]
localOwnCloudPath=/home/simon/ownCloud
password=*redacted*
serverUrl=http://owncloud.app
todoCalendarBackend=0
todoCalendarEnabledList=personal
todoCalendarEnabledUrlList=http://owncloud.app/remote.php/caldav/calendars/simon/personal/
todoCalendarUrlList=http://owncloud.app/remote.php/caldav/calendars/simon/personal/
userName=simon
```

**Comment by pbek** [comment]
I guess you might not have reached the handle via VNC.
In 16.04.13 I disabled collapsing for all panels in the main window, so they can't be hidden by accident. It will be released later today. Can you then please try if you are still able to get in to such panel conditions.

**Comment by pbek** [comment]
Version 16.04.13 is out now. :tada:

**Comment by scantem** [comment]
You're right, I tested it when I got home and managed to get the arrow to expand the panel. 16.04.13 seems to be working well, I can't accidentally hide the panels anymore.

Thanks for all your help.

**Comment by pbek** [comment]
Great, thank you for reporting!
