### ISSUE TITLE
[I] Gentoo EBuilds use depcrecated EAPI5

### ISSUE THREAD

**Issue by jpdigital** [pbek/QOwnNotes#1484]
Please paste the text from the issue assistant here. It should be already in your clipboard.#### Expected behaviour

Gentoo EBuilds should use EAPI6 or EAPI7

#### Actual behaviour

EBuilds use EAPI5 which causes Portage (2.3.79, current stable) to print to following message for every ebuild in the overlay:

ERROR: app-office/qownnotes-19.12.0::qownnotes-overlay failed (depend phase):
 *   qmake-utils.eclass: unsupported EAPI=5
 * 
 * Call stack:
 *                  ebuild.sh, line 616:  Called source '/usr/local/portage/qownnotes-overlay/app-office/qownnotes/qownnotes-19.12.0.ebuild'
 / *   qownnotes-19.12.0.ebuild, line  11:  Called inherit 'qmake-utils' 'eutils'
 *                  ebuild.sh, line 317:  Called __qa_source '/usr/portage/eclass/qmake-utils.eclass'
 *                  ebuild.sh, line 112:  Called source '/usr/portage/eclass/qmake-utils.eclass'
 *         qmake-utils.eclass, line  20:  Called die
 * The specific snippet of code:
 *   [[ ${EAPI:-0} == [012345] ]] && die "qmake-utils.eclass: unsupported EAPI=${EAPI:-0}"
 * 
 * If you need support, post the output of `emerge --info '=app-office/qownnotes-19.12.0::qownnotes-overlay'`,
 * the complete build log and the output of `emerge -pqv '=app-office/qownnotes-19.12.0::qownnotes-overlay'`.
 * Working directory: '/usr/lib64/python3.6/site-packages'

#### Steps to reproduce

Try emerge --update or emerge qownnotes

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[17:33:00] [status] 1 Notiz auf Datenträger gespeichert
[17:33:10] [status] 1 Notiz auf Datenträger gespeichert
[17:33:20] [status] 1 Notiz auf Datenträger gespeichert
[17:33:30] [status] 1 Notiz auf Datenträger gespeichert
[17:33:40] [status] 1 Notiz auf Datenträger gespeichert
[17:33:50] [status] 1 Notiz auf Datenträger gespeichert
[17:34:00] [status] 1 Notiz auf Datenträger gespeichert
[17:34:10] [status] 1 Notiz auf Datenträger gespeichert
[17:34:20] [status] 1 Notiz auf Datenträger gespeichert
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Do. Dez. 5 20:51:26 2019`
**Version**: `19.12.0`
**Build date**: `Dec  1 2019`
**Build number**: `629`
**Platform**: `linux`
**Operating System**: `Gentoo/Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Gentoo`
**Qt Version (build)**: `5.12.5`
**Qt Version (runtime)**: `5.12.5`
**Portable mode**: `no`
**Settings path / key**: `/home/jensp/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/jensp/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Icon theme**: `breeze`
**Notes in current note folder**: `283`
**Calendar items**: `196`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://cloud.jp-digital.de`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `15.0.5.3`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `de_AT, de_CH, de_DE, en_AU, en_CA, en_GB, en_US, en_ZA`
**Language names**: `Österreichisches Deutsch (Österreich), Schweizer Hochdeutsch (Schweiz), Deutsch (Deutschland), Australian English (Australia), Canadian English (Canada), British English (United Kingdom), American English (United States), English (South Africa)`
**Application dictionaries path**: `/home/jensp/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Standard`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `5`
**localPath**: `/home/jensp/cloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/jensp/cloud/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://cloud.jp-digital.de`
**username**: `jensp`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/editorWidthMode** (QString): `1`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `19`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `/home/jensp/Downloads/tmp`
**FileDialog/LastPath-NotePDFExport** (QString): `/home/jensp/Downloads/tmp`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2019-12-05T20:05:50.102`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Sans Serif,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Sans Serif,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**MainWindow/tagTreeWidgetExpandState-1** (QStringList): `18`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteHistory-1** (QVariantList): `<variant list with 107 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `106`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExport** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `true`
**TableDialog/geometry** (QByteArray): `<binary data>`
**TagAddDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Konferenzen`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `a9ff04fa-34a2-48cb-a3e3-70107ed445a7`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `14`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `false`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `false`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `false`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `false`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/jensp/cloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `0`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList** (QStringList): `konferenzen, defaultcalendar`
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList** (QStringList): `https://cloud.jp-digital.de/remote.php/caldav/calendars/jensp/konferenzen/, https://cloud.jp-digital.de/remote.php/caldav/calendars/jensp/defaultcalendar/`
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `15.0.5.3`
**previousWorkspace** (QString): *empty*
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Besprechung 2019-12-05, Besprechung 2019-12-04, Interessante Freie Software, ScientificCMS 7.0 Publications ToDo, Konferenzen 2020, ACT Rules Test Cases, Freemarker Themes ToDo, SSO per LDAP für CCM 2.x, Shibboleth Docker Image, Behindertenverbände etc, Evaluation, Politikwissenschaft Einführung, sed, SoWi 2019-07-03, web-a11y-auditor.net Passwörter, Jenkins, lib32 rebuild failed packages, Aktuelle PHP Versione für Debian, Barrierefreiheit - für wen eigentlich?, Java Debugger Parameter, WebPage Microscope Tests, SoWi Besprechung 2019-05-21, ldap, webpage microscope ui urls, postgres permissions large objects, OpenLDAP Installation und Einrichtung, hibernate_sequence, SoWi 2019-04-02, FrOSCon 2019, Typo3 Notes, ToDo Freemarker für 2.3.x, Einkaufsliste 2019-03-23, Akonadi DB Troubleshooting, Tablets, webpage-microscope Tests, hibernate5-ddl-maven-plugin ToDo, W4A 2019 Submission, Marktplatz Software, Literatur SuUB Sicherheitsanalyse Webanwendungen, Netflix Kategorien, Honorverse Chronologie, Success Criteria für AutoRepair, Auto WCAG Rules für AutoRepair, LeaseLife ToDo Antrag Technischer Teil, Gliederung Accessibility Book, Drupal Devel Links, Fragen an BKB/Serge 2018-11-13, Interessante Bücher SuUB, Ontologies in Use: A survey, LeaseLife Google Drive, App für Patienten, Login/Session mit HTTPie, Mögliche Stellen für Bewerbung, Fragebogen für Evaluation, LaTeX Pakete für Fragebögen, Gewinnspiele, 2018-08-15, TinyMCE, WoZi Server, Success Criteria für Testversion Aug 2018, FrOSCon 2018, React Native, WoZi IT, Nächste Besprechung WoZi vor Ort, Webshop Software für LeaseLife, EARL, Literatur zu Big Data, Machine Learning SuUB, Besprechung 2018-06-20, WebDAV für Themes Aufwandsabschätzung, Struktur für Ontologie Dokumentation, Aufwand Wartung Linux Server, Aufwand Wartung Wordpress, Stand Datenschutzerklärungen, WoZi Tura, LeaseLife, ITB Besprechung, Bildgrößen für Webseite, CMS Evaluierung, Aufgaben Zugfahrt 21. April und 26. April 2018, Papers für Journals, Reisekosten w4A 2018, Auto WCAG Rules zum bearbeiten, Besprechungen Themensammler, Leseliste, Literatur Dissertation Related Work, ToDo web-a11y, Progressive WebApps, Hometrainer, Heimkinoprogramm, Filme, Uni Bremen Redesign 2017/18, devres queries, Useful SPARQL Queries, DOL Fragen, Test Bootable Devices and ISOs with QEMU, Mount ISO, elektronik lernpakete, OWL Closed World for Object Property, SELinux Zugriff auf /srv erlauben, Integration CKEditor`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**skipVersion** (QString): `17.05.8`
**spellCheckLanguage** (QString): `auto`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Hauptsymbolleiste`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `Formatierungs-Werkzeugleiste`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `Einfügen-Werkzeugleiste`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `Werkzeugleiste Verschlüsselung`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `Fenster-Werkzeugleiste`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `Beenden - Symbolleiste`
**toolbar/size** (QString): `6`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-a9ff04fa-34a2-48cb-a3e3-70107ed445a7/name** (QString): `Standard`
**workspace-a9ff04fa-34a2-48cb-a3e3-70107ed445a7/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-a9ff04fa-34a2-48cb-a3e3-70107ed445a7/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `a9ff04fa-34a2-48cb-a3e3-70107ed445a7`

## System environment

**GS_LIB**: `/home/jensp/.fonts`
**KDE_FULL_SESSION**: `true`
**LANG**: `de_DE.UTF-8`
**QT_GRAPHICSSYSTEM**: `raster`
**LESS**: `-R -M --shift 5`
**DISPLAY**: `:0`
**OPENGL_PROFILE**: `xorg-x11`
**CONFIG_PROTECT_MASK**: `/etc/sandbox.d /etc/php/cli-php7.3/ext-active/ /etc/php/cgi-php7.3/ext-active/ /etc/php/apache2-php7.3/ext-active/ /etc/fonts/fonts.conf /etc/gentoo-release /etc/gconf /etc/terminfo /etc/dconf /etc/ca-certificates.conf /etc/texmf/web2c /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/revdep-rebuild`
**EDITOR**: `/usr/bin/vi`
**PRELINK_PATH_MASK**: `/usr/lib64/klibc`
**JAVA_HOME**: `/home/jensp/.gentoo/java-config-2/current-user-vm`
**GCC_SPECS**: *empty*
**XDG_VTNR**: `1`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**SSH_AUTH_SOCK**: `/tmp/ssh-sGHC13ERWtaD/agent.3100`
**XDG_SESSION_ID**: `1`
**VBOX_APP_HOME**: `/opt/VirtualBox`
**USER**: `jensp`
**PAGER**: `/usr/bin/less`
**DESKTOP_SESSION**: `/usr/share/xsessions/plasma`
**PWD**: `/home/jensp`
**SSH_ASKPASS**: `/usr/bin/ksshaskpass`
**HOME**: `/home/jensp`
**MANPAGER**: `manpager`
**SSH_AGENT_PID**: `3101`
**XDG_SESSION_TYPE**: `x11`
**GSETTINGS_BACKEND**: `dconf`
**XDG_DATA_DIRS**: `/usr/local/share:/usr/share`
**JDK_HOME**: `/home/jensp/.gentoo/java-config-2/current-user-vm`
**XDG_SESSION_DESKTOP**: `KDE`
**GTK_MODULES**: `canberra-gtk-module`
**_JAVA_OPTIONS**: `-Dawt.useSystemAAFontSettings=lcd`
**MAIL**: `/var/mail/jensp`
**CONFIG_PROTECT**: `/usr/share/maven-bin-3.0/conf /usr/share/maven-bin-3.3/conf /usr/share/maven-bin-3.6/conf /usr/share/gnupg/qualified.txt /usr/share/config /usr/lib64/libreoffice/program/sofficerc`
**SHELL**: `/bin/bash`
**XDG_SESSION_CLASS**: `user`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**JAVAC**: `/home/jensp/.gentoo/java-config-2/current-user-vm/bin/javac`
**XCURSOR_THEME**: `breeze_cursors`
**XDG_CURRENT_DESKTOP**: `KDE`
**OPENCL_PROFILE**: `nvidia`
**XDG_SEAT**: `seat0`
**SHLVL**: `1`
**MANPATH**: `/home/jensp/.gentoo/java-config-2/current-user-vm/man:/usr/share/gcc-data/x86_64-pc-linux-gnu/9.2.0/man:/usr/share/binutils-data/x86_64-pc-linux-gnu/2.32/man:/usr/lib/llvm/8/share/man:/etc/java-config-2/current-system-vm/man/:/usr/lib64/php7.3/man/:/usr/local/share/man:/usr/share/man:/usr/share/rust-1.37.0/man`
**LOGNAME**: `jensp`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XAUTHORITY**: `/home/jensp/.Xauthority`
**ANT_HOME**: `/usr/share/ant`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**XDG_CONFIG_DIRS**: `/etc/xdg`
**PATH**: `/usr/lib/llvm/8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin`
**KDE_SESSION_UID**: `1000`
**KDE_SESSION_VERSION**: `5`
**INFOPATH**: `/usr/share/gcc-data/x86_64-pc-linux-gnu/9.2.0/info:/usr/share/binutils-data/x86_64-pc-linux-gnu/2.32/info:/usr/share/info`
**LESSOPEN**: `|lesspipe %s`
**_**: `/usr/bin/kwrapper5`
**SESSION_MANAGER**: `local/jp-workstation:@/tmp/.ICE-unix/3202,unix/jp-workstation:/tmp/.ICE-unix/3202`
**LANGUAGE**: *empty*
</details>

**Comment by internethering** [comment]
same error here. pls fix. and one hint: please reduce the ebuilds in the overlay. the latest 5-10 are enough.

**Comment by pbek** [comment]
If it's just a little change in https://github.com/pbek/QOwnNotes/blob/develop/build-systems/gentoo/qownnotes.ebuild please open a pull request.

**Comment by pbek** [comment]
## 19.12.3
- the Gentoo EBuilds now are using EAPI7 (for [#1484](https://github.com/pbek/QOwnNotes/issues/1484), thank you @internethering)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
I don't know why this issue got closed (automatically?), but since you already created new ones I leave it closed. :grin: 

..I guess because you used "fix" in the commit message.
