### ISSUE TITLE
Todo - Show Todo List should bring focus to Todo List and call the window to the foreground

### ISSUE THREAD

**Issue by jdkruzr** [pbek/QOwnNotes#1485]
#### Expected behaviour

It only does this if it was not already opened.

#### Actual behaviour

If it isn't already opened, nothing happens.

#### Steps to reproduce

This is on MacOS 10.15.1 as well as 10.14.whateverthelatestwas.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fri Dec 6 15:36:20 2019`
**Version**: `19.12.0`
**Build date**: `Dec  1 2019`
**Build number**: `4974`
**Platform**: `macosx`check
**Operating System**: `macOS 10.15`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
**Settings path / key**: `/Users/jtd/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/jtd/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `124`
**Calendar items**: `55`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: 
**appIsValid**: `no`
**notesPathExists**: `unknown`
**connectionErrorMessage**: 

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/Users/jtd/Library/Application Support/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/Users/jtd/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/Users/jtd/Nextcloud/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: 
**username**: `jtd`

## Settings

** USB DISK 3/0** (QString): `1`
**646F6E7A_00000000_00000001_6E7A6361_656D6963** (qlonglong): `1`
**AKLastCheckInAttemptDate** (QDateTime): `2019-12-01T16:30:39.800`
**AKLastCheckInSuccessDate** (QDateTime): `2019-12-01T16:30:50.979`
**AKLastEmailListRequestDateKey** (QDateTime): `2019-12-06T15:23:31.276`
**AKLastIDMSEnvironment** (qlonglong): `0`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Android Android** (QString): `1`
**Android OnePlus** (QString): `1`
**Brother DCP-L5500DN series** (QString): `1`
**Brother MFC-J5845DW** (QString): `1`
**Brother MFC-L3770CDW series** (QString): `1`
**Canon D1300 Series** (QString): `1`
**Canon MB2100 series** (QString): `1`
**Country** (QString): `US`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**DisplayLink I1659FWUX** (QString): `1`
**EPSON WF-2750 Series** (QString): `1`
**EPSON WF-2760 Series** (QString): `1`
**EPSON XP-340 Series** (QString): `1`
**EPSON XP-440 Series** (QString): `1`
**EPSON XP-640 Series** (QString): `1`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/centerCursor** (bool): `false`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/vimMode** (bool): `false`
**General UDisk** (QString): `1`
**Generic Mass Storage** (QString): `1`
**Google AOSP on walleye** (QString): `1`
**Google Android** (QString): `1`
**Google Pixel 2** (QString): `1`
**HP ColorLaserJet MFP M278-M281** (QString): `1`
**HP DeskJet 2600 series** (QString): `1`
**HP DeskJet 3700 series** (QString): `1`
**HP ENVY 4510 series** (QString): `1`
**HP ENVY 4520 series** (QString): `1`
**HP ENVY 5540 series** (QString): `1`
**HP LaserJet MFP M227-M231** (QString): `1`
**HP OfficeJet 3830 series** (QString): `1`
**HP OfficeJet 4650 series** (QString): `1`
**HP OfficeJet Pro 6970** (QString): `1`
**HP OfficeJet Pro 8710** (QString): `1`
**HP OfficeJet Pro 8720** (QString): `1`
**Hewlett Packard MFP M426fdw** (QString): `1`
**Hewlett Packard MFP M477fdw** (QString): `1`
**Hewlett Packard MFP M477fnw** (QString): `1`
**Huawei Nexus 6P** (QString): `1`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**Kingston DataTraveler 2/0** (QString): `1`
**LastUpdateCheck** (QDateTime): `2019-12-06T15:15:14.937`
**Lexmark Pro700 Series** (QString): `1`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**Logitech USB Receiver** (QString): `1`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (qlonglong): `32`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Monaco,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `.SF NS Text,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Monaco,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `.SF NS Text,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**MessageBoxOverride/remove-notes** (qlonglong): `16384`
**MessageBoxOverride/update-and-restart** (qlonglong): `16384`
**Mobvoi TicWatch Pro** (QString): `1`
**MultipleSessionEnabled** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 82 item(s)>`
**NoteHistoryCurrentIndex-1** (qlonglong): `81`
**OnePlus Android** (QString): `1`
**OnePlus ONEPLUS A3000** (QString): `1`
**PKSecureElementAvailableFlagsByHost** (qlonglong): `1`
**PNY USB 3/0 FD** (QString): `1`
**PiwikClientId** (QString): `<hidden>`
**PreSonus AudioBox iTwo** (QString): `1`
**Qualcomm CDMA Technologies MSM QUSB__BULK** (QString): `1`
**Samsung Flash Drive** (QString): `1`
**SanDisk Cruzer Blade** (QString): `1`
**SanDisk Ultra Fit** (QString): `1`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (qlonglong): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**Staples Relay UFD** (QString): `1`
**StartHidden** (bool): `false`
**SyncServicesServerWasActive** (bool): `true`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (qlonglong): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Work`
**USB Disk 2/0** (QString): `1`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WS USB Gigabit LAN** (QString): `1`
**WebAutomaticSpellingCorrectionEnabled** (bool): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**Western Digital Elements 25A1** (QString): `1`
**Western Digital My Passport 25E4** (QString): `1`
**acceptAllExternalModifications** (bool): `false`
**allowDifferentNoteFileName** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `false`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (bool): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**com/barebones/bbedit~E46B3974D4E65CEFE7053592E7C49D80E1014420** (QByteArray): `<binary data>`
**com/omnigroup/OmniGraffle6:6:2** (QByteArray): `<binary data>`
**com/omnigroup/OmniGraffle7:7:3** (QByteArray): `<binary data>`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (qlonglong): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (qlonglong): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (bool): `true`
**disableAutomaticUpdateDialog** (bool): `false`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (bool): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (qlonglong): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (qlonglong): `1024`
**imageScaleDownMaximumWidth** (qlonglong): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (qlonglong): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (qlonglong): `18`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (qlonglong): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `false`
**networking/proxyType** (qlonglong): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (qlonglong): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (qlonglong): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (qlonglong): `0`
**notesPanelOrder** (qlonglong): `0`
**notesPanelSort** (qlonglong): `1`
**notesPath** (QString): `/Users/jtd/Nextcloud/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/ignoreNonTodoCalendars** (bool): `false`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (qlonglong): `2`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): 
**ownCloud/todoCalendarCalDAVUsername** (QString): `jtd`
**ownCloud/todoCalendarCloudConnectionId** (qlonglong): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Personal, Reticulum, Work`
**ownCloud/todoCalendarEnabledList** (QStringList): `Personal, Reticulum, Work`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): 
**ownCloud/todoCalendarUrlList** (QStringList): 
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): 
**ownCloudInfo/notesPathExistsText** (QString): `unknown`
**ownCloudInfo/serverVersion** (QString): *empty*
**recentNoteFolders** (QStringList): `/Users/jtd/Nextcloud/QOwnNotes`
**restoreCursorPosition** (bool): `false`
**savedSearches/noteFolder-1** (QStringList): `Note 2019-12-02T08.41.25, Note 2019-11-27T14.17.00, Note 2019-11-19T14.10.12, Note 2019-11-05T23.39.17, Note 2019-11-04T09.33.49, Note 2019-10-08T14.37.01, Note 2019-09-29T18.34.41, Note 2019-08-24T01.07.07, Note 2019-08-22T13.55.30, Note 2019-08-06T13.04.14, Note 2019-08-03T21.14.57, Note 2019-07-11T16.36.15`
**showMatches** (bool): `true`
**showMenuBar** (bool): `false`
**showStatusBar** (bool): `true`
**systemIconTheme** (bool): `false`
**tagWasAddedToNote** (bool): `true`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (qlonglong): `0`
**tagsPanelSort** (qlonglong): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/2/name** (QString): `insertingToolbar`
**toolbar/2/title** (QString): `inserting toolbar`
**toolbar/3/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/3/name** (QString): `encryptionToolbar`
**toolbar/3/title** (QString): `encryption toolbar`
**toolbar/4/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/4/name** (QString): `windowToolbar`
**toolbar/4/title** (QString): `window toolbar`
**toolbar/5/items** (QStringList): `action_Quit`
**toolbar/5/name** (QString): `quitToolbar`
**toolbar/5/title** (QString): `quit toolbar`
**toolbar/6/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/6/name** (QString): `formattingToolbar`
**toolbar/6/title** (QString): `formatting toolbar`
**toolbar/size** (qlonglong): `6`
**useUNIXNewline** (bool): `false`
**userMenuExtraStyle** (qlonglong): `1`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (qlonglong): `22222`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**USER**: `jtd`
**DISPLAY**: `/private/tmp/com.apple.launchd.aYptfF6vBr/org.macosforge.xquartz:0`
**LOGNAME**: `jtd`
**PATH**: `/usr/bin:/bin:/usr/sbin:/sbin`
**SSH_AUTH_SOCK**: `/private/tmp/com.apple.launchd.VBjJfpHA9P/Listeners`
**HOME**: `/Users/jtd`
**SHELL**: `/bin/zsh`
**__CF_USER_TEXT_ENCODING**: `0x56DE0884:0x0:0x0`
**TMPDIR**: `/var/folders/_v/g0j17cts4tv7gdb45fz2flldbdw244/T/`
**XPC_SERVICE_NAME**: `com.PBE.QOwnNotes.2980`
**XPC_FLAGS**: `0x0`
**QT_LOGGING_RULES**: `qt.network.ssl.warning=false`
</details>

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
## 19.12.3
- dialogs like the *Todo dialog*, the *Issue assistant dialog* or the *Action dialog*
  will now raise across other windows if activated while already active

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by jdkruzr** [comment]
This is a huge help, thank you! Yes, working.

**Comment by pbek** [comment]
Great, thank you for testing!
