### ISSUE TITLE
#1484 is not complete resolved

### ISSUE THREAD

**Issue by internethering** [pbek/QOwnNotes#1487]
please update ALL ebuilds older qownnotes-19.12.3.ebuild, because they throw the error from #1484 furthermore

**Comment by internethering** [comment]
maybe cleanup before, so you've update only a small number of ebuilds:  #1488 :)

**Comment by pbek** [comment]
You can go crazy on https://github.com/pbek/qownnotes-overlay/tree/master/app-office/qownnotes if you like.

**Comment by seeeebastien** [comment]
I made a pull request to fix it
[https://github.com/pbek/qownnotes-overlay/pull/3](url)

**Comment by pbek** [comment]
Thank you!
