### ISSUE TITLE
cleanup gentoo overlay

### ISSUE THREAD

**Issue by internethering** [pbek/QOwnNotes#1488]
370 (!) ebuilds are too much, this costs unnecessary resources at every emerge -u @world :/
please cleanup! last 5-10 ebuilds are enough

**Comment by pbek** [comment]
If you want you can adapt https://github.com/pbek/QOwnNotes/blob/develop/build-systems/gentoo/build-for-gentoo.sh to remove older releases.

**Comment by Zorziel** [comment]
I am a Gentoo user and can confirm that the initial sync does bring in hundreds of ebuilds.  However, each repo sync (either with layman or emaint or rsync (emerge --sync)) should only bring in the delta so each sync should be minimal and not bring in more than a few ebuilds, depending on how long your last sync was.  

That said, the current count of over 670 ebuilds is quite high, considering you probably don't want to be allowing users to install some of those extremely older versions.  

Unless we're keeping those older ebuilds for any legacy testing, I don't mind forking the [gentoo-overlay](https://github.com/qownnotes/gentoo-overlay), adding an archive folder and a .gitignore, and submitting a pull.    

I'll also start this issue over there too.

**Comment by pbek** [comment]
> Unless we're keeping those older ebuilds for any legacy testing

I don't see any reason for this.

> I don't mind forking the gentoo-overlay, adding an archive folder and a .gitignore, and submitting a pull.

Yes, please do so, a cleanup would be great!

**Comment by Zorziel** [comment]
This issue can now be closed per https://github.com/qownnotes/gentoo-overlay/pull/4

**Comment by pbek** [comment]
Thank you!
