### ISSUE TITLE
Notes are not shown if no note sub-folder was selected

### ISSUE THREAD

**Issue by thomascrisan** [pbek/QOwnNotes#1489]
Allowed application to update itself to windows.  Upon restart, all of my notes disappeared.

Reinstalled v5038 manually by copying downloaded zip file contents and obtained same result.  Checked setup directories and server entries and all was okay.  Re-read directories but again, all notes were missing

Reverted to v5030 and restored functionality in Windows.  No notes were altered by new version, they simply were not being read and made visible.

[QOwnNotes.log](https://github.com/pbek/QOwnNotes/files/3935201/QOwnNotes.log)

**Comment by jebrosen** [comment]
Same issue here with version 19.12.3 (Arch Linux, via AUR) - the sidebar on the left side with the list of notes always appears empty.

**Comment by thomascrisan** [comment]
That's odd; my usual desktop is Arch Linux and when I installed version 19.12.3 via AUR earlier, everything works as expected.  The left sidebar is fully populated.

**Comment by Waqar144** [comment]
Seems like note directory isn't read, everything is empty in your log. Very weird...

**Comment by pbek** [comment]
I neither can reproduce this on Manjaro (AUR). @Waqar144, could #1483 do this?

**Comment by dm2912** [comment]
Same problem here in Mint 19.2

**Comment by Waqar144** [comment]
> I neither can reproduce this on Manjaro (AUR). @Waqar144, could #1483 do this?

Seems like it.

**Comment by pbek** [comment]
I was able to reproduce it. I had to click on a note sub-folder to see any notes. If sub-folders weren't activated I never got any notes in the list. #1483 was the culprit. It worked after I reverted it.

**Comment by pbek** [comment]
## 19.12.4
- fixed a problem with loading notes if no note sub-folder was selected

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by thomascrisan** [comment]
release 5050 fixed the issue for me on the Windows version.  Thanks.

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by dm2912** [comment]
fine here in mint now
