### ISSUE TITLE
Feature request: Search and replace

### ISSUE THREAD

**Issue by eemantsal** [pbek/QOwnNotes#149]
I think the title says it all. Would be nice a search and replace tool like in text editors. I don't think explanations are needed; it's a really useful feature that saves tons of time when editing any text, be it common "human" text, computer code, numbers...

**Comment by pbek** [comment]
Thank you for your suggestions. Replacing is already on my todo list. ;) And searching already works with `Ctrl + F`.

**Comment by pbek** [comment]
In the just released version 16.04.17 you can now replace found text in the current note with <kbd>Ctrl</kbd> + <kbd>R</kbd>. Could you please test it and report back?

**Comment by eemantsal** [comment]
Sorry for the delay. I haven't had much free time.
Ok, the replace text function works perfectly. :) I'm not so sure about having two buttons, one for searching and another one for replacing. The search one opens the search box, and at the very right of the search box, the 3rd icon, changes the simple search box to the replace box, which is also a search tool. If the Replace tool is also a Search tool, wouldn't be better and simpler just having a "Search or Replace" button? The search box takes less space and is cleaner than the replace box, that's richt, but one can toggle search/replace with the third button at the very right of the search or replace box.
Well, I'm a great enemy of cluttered interfaces, I must admit, perhaps other people prefer to have these two buttons. Who knows.

**Comment by pbek** [comment]
Thank you for your feedback, maybe I'll remove one of them or move both of them to a new toolbar in the future.
