### ISSUE TITLE
Preventing to log out of KDE/Plasma

### ISSUE THREAD

**Issue by joel-porquet** [pbek/QOwnNotes#1496]
When I log out of Plasma/KDE, all the apps should get closed. Unfortunately, QOwnnotes doesn't quit which prevents KDE from terminating the currrent session. It seems to be caused by the "minimize when closing window" option.

KeePassXC had the same issue, I'm linking it here: https://github.com/keepassxreboot/keepassxc/issues/2692

All the details are the same, and probably the same kind of workaround can be found.

Thanks!

**Comment by pbek** [comment]
Thank you for your hint. We already talked quite a while about this issue in #1269.

**Comment by pbek** [comment]
And can you please post the output from the debug settings (see issue template).

**Comment by pbek** [comment]
And are you only having this issue when QOwnNotes is hidden ("to tray") when you shutdown KDE?

**Comment by pbek** [comment]
## 19.12.6
- fixed a problem when logging out of KDE while application is minimized to tray

There now is a new release, could you please test it and report if it works for you?

**Comment by joel-porquet** [comment]
Hey, thanks for fixing this so quickly! I just tried, and it seems to be working since I was able to log out while qownnotes was minimized in the try.

**Comment by pbek** [comment]
Great, thank you for testing!
