### ISSUE TITLE
Ubuntu Packageing: Update dependency on libicu

### ISSUE THREAD

**Issue by janhenke** [pbek/QOwnNotes#15]
The Debian/Ubuntu package currently depends on the libicu52 package. This package is gone in Ubuntu 15.10, being replaced with a new libicu55 package.

Please build separate packages for Ubuntu 15.10 and above, which depend on the new package. Since the old package is complete gone from the archive, the package is currently not installable on this Ubuntu release.
If #14 is solved first, this one should be fairly simple.

**Comment by pbek** [comment]
Thank you pointing out the issue with 15.10, Jan!

I will have to change the build, release and deployment processes as well as the update mechanism in the app to achieve this, because so far there only is a 'Linux' build. 
Creating a PPA would be nice.

**Comment by pbek** [comment]
I now removed the (by default installed and co-dependent) libicu52 dependency from the deb-package for compatibility with Ubuntu 15.10. The next release (0.54+) will be compatible. Thanks again for reporting @janhenke !
