### ISSUE TITLE
Feature Request: Add option to skip standard note header

### ISSUE THREAD

**Issue by minthemiddle** [pbek/QOwnNotes#150]
By default, QOwnNotes creates a header with each new note. It looks like this: `Note 2016-04-26T09.51.13
========================`. This may be a good fit for many, but probably many have a different setup. I use `## Header` style and don't care about the date and thus and would prefer to start form scratch with every note. Right now I start with deleting the default header.

It would be very nice - and probably beneficial for many others - to give an option to skip the default header (easy) or set your own default template (probably rather difficult).

**Comment by pbek** [comment]
Thank you for your suggestion, but since the note file name is generated from the first line of the note (like ownCloud Notes does) a unique first line is mandatory after the note was created. You can change it at any time and QOwnNotes will make sure the note name stays unique.

So we can't have an option to skip the default header.

If one wants to note something quickly using the timestamp makes sense and one can always change the note name later by overwriting the first line...

**Comment by minthemiddle** [comment]
I don't use ownCloud Notes, I use a folder which holds my notes as markdown plaintext. Despite thousands of notes I never had any problems whatsoever. 

Again, the setup might make sense for some workflows, but is a hindrance for others. Nvalt, Resophnote and 1Writer which I also use for notes also use the first line for the notes' filename - without using a timestamp. Hence it seems to be possible.

If you don't want to enable that, fair enough, but maybe consider that others use the application in another way.

**Comment by pbek** [comment]
The timestamp is just a practical default value. You can (and are supposed to) change the headline (first line) of your note like you want. QOwnNotes will also ignore a leading `#` from the headline in the filename.

**Comment by minthemiddle** [comment]
Ok, never mind. I can live with it. As long as `ResophNotes` can't handle two or more separate note folders, `QOwnNotes` is the best option for Windows.

**Comment by minthemiddle** [comment]
By the way, when you search for a note and don't find anything and create a note from that search, you don't get the standard first line. That is exactly like `Resophnote` and `nvalt` work and is exactly what I was looking for.

**Comment by pbek** [comment]
That's why the line edit is called `search or create note`. :grin: 
I thought we were talking about that the file name is the note headline and that `====` is used and not `#`.

**Comment by pbek** [comment]
In the just released version 16.05.5...

- you can new use a new setting in the general settings to **allow that the 
  note file name is different from the note headline**
    - this allows you to keep your old note files regardless of what the content
      of them is
    - the note name will also be found in the note search
    - you are able to **rename your note files** by double-clicking on the note 
      name in the note list
        - renaming will fail if there already exists a note with the same name
        - some characters are also not allowed in the file name, they will be 
          removed automatically
    - be aware of that ownCloud notes needs the note file name to be the same 
      as the note headline

In case this is something for you could you please test this new feature and report back?
