### ISSUE TITLE
Images added through the "Insert image" window not copied to media folder

### ISSUE THREAD

**Issue by bipox** [pbek/QOwnNotes#1500]
Hi,

QOwnNotes 19.12.6 on latest KDE Neon (user edition)

I believe when I pasted an image url inside the "insert image" window, it would work as intended, copying the image to my media folder and showing the downloaded file in my note.

Now when I click OK nothing happens. Log doesn't show anything. 

It stopped working a while ago

Adding an image through this window and checking "don't copy image to media folder" still works.

#### Expected behaviour

Image gets added to media folder and on-device link added to the note

#### Actual behaviour

After clicking "OK", the window closes and nothing happens.

#### Relevant log output in the Log panel

Nothing relevant appears in log.

**Comment by pbek** [comment]
I wonder when that happened...

**Comment by pbek** [comment]
Will be fixed in the next release.

**Comment by bipox** [comment]
So you could reproduce it?

I tested it on 2 machines running KDE Neon and it wouldn't work. However I didn't think to try it on another distro until now, and it works correctly on Linux Mint

**Comment by pbek** [comment]
> and it works correctly on Linux Mint

It did? You would have needed to set another cropping factor for it to have worked in the current release.

**Comment by bipox** [comment]
> > and it works correctly on Linux Mint
> 
> It did? You would have needed to set another cropping factor for it to have worked in the current release.

You're right, I did crop it on Linux Mint. Cropping the image on KDE fixes the problem too. 

I really thought I tried it...

**Comment by pbek** [comment]
## 19.12.7
- fixed inserting of images from urls in the *Image dialog*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by bipox** [comment]
> There now is a new release, could you please test it and report if it works for you?

It does. That was quick!

Feel free (of course) to ignore this tiny detail, but it came up when I was testing: often copied text will insert a space at the end, in which case it isn't recognize as a picture (which made me think it didn't work at first). Maybe it could show an error message (or ignore the spaces)? I just thought I should mention it.

**Comment by pbek** [comment]
Thank you for mentioning, I will just trim them!

**Comment by pbek** [comment]
## 19.12.8
- trailing and leading spaces will now be trimmed from pasted urls in the *Image dialog*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by bipox** [comment]
> There now is a new release, could you please test it and report if it works for you?

Everything works perfectly now!

**Comment by pbek** [comment]
Great, thank you for testing!
