### ISSUE TITLE
Doesn't Compile on ARM

### ISSUE THREAD

**Issue by travankor** [pbek/QOwnNotes#1506]
#### Expected behaviour
Compiles on ARM (Linux) architectures.

#### Actual behaviour
Does not compile on ARM architectures (aarch64-musl in this case).

#### Steps to reproduce
Cross compile with Qmake with release build set.
```
In file included from libraries/botan/botanwrapper.h:13,
                 from libraries/botan/botanwrapper.cpp:1:
libraries/botan/botan.h:293:6: error: #error "Trying to compile Botan configured as x86_64 with non-x86_64 compiler."
  293 |     #error "Trying to compile Botan configured as x86_64 with non-x86_64 compiler."
      |      ^~~~~
libraries/botan/botanwrapper.cpp: In constructor 'BotanWrapper::BotanWrapper(QObject*)':
libraries/botan/botanwrapper.cpp:9:23: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<unsigned char, Botan::secure_allocator<unsigned char> >::size_type' {aka 'long unsigned int'} [-Wsign-compare]
    9 |     for (int i = 0; i < mSalt.size(); i++) {
      |                     ~~^~~~~~~~~~~~~~
libraries/botan/botanwrapper.cpp: In member function 'void BotanWrapper::setSalt(QString)':
libraries/botan/botanwrapper.cpp:203:23: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<unsigned char, Botan::secure_allocator<unsigned char> >::size_type' {aka 'long unsigned int'} [-Wsign-compare]
  203 |     for (int i = 0; i < mSalt.size(); i++) {
      |                     ~~^~~~~~~~~~~~~~
make: *** [Makefile:19096: botanwrapper.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by pbek** [comment]
Strange, QOwnNotes is also built for ARM (e.g. see https://build.opensuse.org/package/show/home:pbek:QOwnNotes/desktop) and I have it running on ARM computers. Which operating system do you need?

@Waqar144, do you know more?

**Comment by Waqar144** [comment]
> error "Trying to compile Botan configured as x86_64 with non-x86_64 compiler."`

It only gets configured as `x86_64` if your system is x86.

I don't know of an easy way to cross compile amalgamated Botan for multiple archs. So no wonder it failed while cross compiling.

**Comment by travankor** [comment]
I noticed that there is a `USE_SYSTEM_BOTAN` flag for the .pri file in the botan folder, but there is no option there for the cmake file.

Further, I try to pass `-DUSE_SYSTEM_BOTAN=1` to qmake but it seems I am doing something wrong because it says `Unknown option -DUSE_SYSTEM_BOTAN=1`.

Maybe some additional docs on how to use system botan library would help? :)

**Comment by Waqar144** [comment]
> I noticed that there is a `USE_SYSTEM_BOTAN` flag for the .pri file in the botan folder, but there is no option there for the cmake file.

That is because qmake is the main build system we are using and no one configured cmake for `USE_SYSTEM_BOTAN` :grimacing: 

To use that, you would need to exclude the embedded botan library from cmake. Then you can just use pkgconfig to set up botan.

> Further, I try to pass `-DUSE_SYSTEM_BOTAN=1` to qmake but it seems I am doing something wrong because it says `Unknown option -DUSE_SYSTEM_BOTAN=1`.

Just put this, `USE_SYSTEM_BOTAN = 1`, at the top of botan.pri file

I should warn you that this option hasn't really been tested a lot and it isn't being used in any of our build. I just left it in there for some reason i can't remember :laughing:

**Comment by travankor** [comment]
>Just put this, USE_SYSTEM_BOTAN = 1, at the top of botan.pri file

Wow, I didn't think that would work but it did. 👍

>I should warn you that this option hasn't really been tested a lot and it isn't being used in any of our build. I just left it in there for some reason i can't remember 😆

I hope you guys don't remove this option because that would break cross-compilation support 🙁
I'm not sure what distro you test with, but I think that both OpenSUSE/Fedora use native ARM builders for their CI and thus avoid any cross-compilation problems.

Anyways, thank you guys for your work and time on this project 🙏

**Comment by pbek** [comment]
Thank you for your kind words! :pray:
