### ISSUE TITLE
[F] Highlight all occurrences of an in-note search string

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#1512]
#### Expected behaviour

When searching for a string in a note, see all occurrences of this string highlighted. Maybe with a toggle (see e.g. Firefox).

<img width="447" alt="image" src="https://user-images.githubusercontent.com/5956570/71084980-c446b280-2196-11ea-815d-ae97cc5f6c9c.png">

#### Actual behaviour

Only the currently selected search item is highlighted.

#### Steps to reproduce

- Open note with contents
- Start search (`ctrl+f`)

#### Information about the application, settings and environment

**Version**: `19.12.10`

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
## 20.1.16
- all search results in the note text edit are now highlighted while searching
  - the speed of the search was slightly improved
  - you can now do regular expressions searches also case insensitive

There now is a new release, could you please test it and report if it works for you?

**Comment by sanderboom** [comment]
Tested and works, thanks!!

**Comment by pbek** [comment]
Great, thank you for testing!
