### ISSUE TITLE
[F] Syntax highlighting: alias typescript to javascript until this is implemented

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#1513]
See title :)

**Comment by Waqar144** [comment]
Hi,
Would it be possible if you could provide these?
- Keywords
- Basic types
- Most used library functions/stuff
- Comment style
- Any other special thing?

**Comment by pbek** [comment]
## 19.12.11
- added typescript highlighting support (for [#1513](https://github.com/pbek/QOwnNotes/pull/1513), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by sanderboom** [comment]
Wow, that's fast! :rocket:  
Syntax highlighting really takes QON to the next level :metal:

**Comment by pbek** [comment]
Yes, awesome work by @Waqar144. :+1: I started to put source code in every note just to revel in the beauty of the highlighting. :laughing:
