### ISSUE TITLE
Skipping updates on app auto-launch closes app when app is started hidden on Windows

### ISSUE THREAD

**Issue by truthsword** [pbek/QOwnNotes#1514]
I'm using 19.12.5 and have the app to launch to the tray automatically with Windows 10. 

Occasionally I get a popup window informing me of an app update when this happens. If I select "Skip Update", the app closes and does not end up in the tray. I must then relaunch the app manually

On occasions where the app is already running and I'm informed of an update when I select "Skip update", the update windows closes, however, the app continues to run (as you would expect it.

I classify this bug as a nuisance, particularly given the frequency of updates.

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue.

**Comment by truthsword** [comment]
This also happens if I select "Download".

**Comment by pbek** [comment]
> Occasionally I get a popup window informing me of an app update when this happens. If I select "Skip Update", the app closes and does not end up in the tray. I must then relaunch the app manually

I couldn't reproduce that on Windows. Neither with the "Download". Does the app crash for you? Is there any crash report? Maybe any log output (if you are using a log file) or output on the terminal (if you run QOwnNotes on the terminal)?

**Comment by truthsword** [comment]
I tried to log this during the recent update but discovered that my debug log option was unchecked When I activated the debug log and rebooted, the updater didn't run at startup, so the app opened in the tray as I expected.

I don't think it is crashing; I believe it is just closing when I either skip update/download for later or "x" out (or Cancel) the update notification window.

Maybe the easier solution is to prevent the update window from appearing until the app is opened from the tray, but since you can't reproduce this, that's probably unnecessary work. I'll wait for the next update and see if I can capture this in the debug log.

**Comment by pbek** [comment]
> I tried to log this during the recent update but discovered that my debug log option was unchecked 

There also is a debugging option to pretend you are on an old version so you'll get the update dialog.

**Comment by truthsword** [comment]
OK... I booted up this morning with QON set to start w/Windows, and go minimized to tray. When QON launched I received an update window and noticed that the app appeared in the tray at this time. Windows' Task Manager showed:
![](https://i.imgur.com/aQXPmwp.png)

I clicked "Skip Update" and the update window closed, and the app icon disappeared from the tray. I then manually relaunched QON. At that point, I grabbed the debug log (below)

<details><summary>Expand</summary>

```
[Dec 22 11:54:29] [debug]: Set proxy configuration to use NO proxy
[Dec 22 11:54:29] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[Dec 22 11:54:29] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
[Dec 22 11:54:29] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[Dec 22 11:54:29] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:54:29] [debug]: buildNotesIndex  - 'noteSubFolderId':  0
[Dec 22 11:54:29] [debug]: setupNoteFolderTables  - 'database version':  14
[Dec 22 11:54:29] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
[Dec 22 11:54:29] [debug]: loadNoteDirectoryList
[Dec 22 11:54:29] [debug]: reloadTagTree
[Dec 22 11:54:29] [debug]: reloadTagTree  - 'noteSubFolderIds':  ()
[Dec 22 11:54:29] [debug]: loadNoteDirectoryList
[Dec 22 11:54:29] [debug]: reloadTagTree
[Dec 22 11:54:29] [debug]: reloadTagTree  - 'noteSubFolderIds':  ()
[Dec 22 11:54:29] [debug]: reloadNoteSubFolderTree
[Dec 22 11:54:30] [debug]: reloadTagTree
[Dec 22 11:54:30] [debug]: reloadTagTree  - 'noteSubFolderIds':  (0)
[Dec 22 11:54:30] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:54:30] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:54:30] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:54:30] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:54:30] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:54:30] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:54:30] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:54:30] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:54:30] [info]: "QOwnNotes server listening on port 22222"
[Dec 22 11:54:30] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:54:30] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:54:30] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:54:30] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:54:30] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:54:30] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:54:30] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:54:30] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:54:30] [debug]: reloadTagTree
[Dec 22 11:54:30] [debug]: reloadTagTree  - 'noteSubFolderIds':  ()
[Dec 22 11:54:30] [debug]: on_noteTreeWidget_currentItemChanged
[Dec 22 11:54:30] [debug]: setCurrentNote  - 'note':  Note: <id>1 <name>"How to improve your computer performance and SSD life span with a RAM disk" <fileName>"How to improve your computer performance and SSD life span with a RAM disk.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
[Dec 22 11:54:30] [debug]:  added to history:  NoteHistoryItem: <noteName>"How to improve your computer performance and SSD life span with a RAM disk" <noteSubFolderPathData>"" <cursorPosition>0 <relativeScrollBarPosition>0
[Dec 22 11:54:30] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:56:01] [debug]: skip version
[Dec 22 11:56:01] [debug]: storeSettings  - 'noteHistoryItem':  NoteHistoryItem: <noteName>"How to improve your computer performance and SSD life span with a RAM disk" <noteSubFolderPathData>"" <cursorPosition>0 <relativeScrollBarPosition>0
[Dec 22 11:56:01] [debug]: deleting 0x3a83450 for "en_US"
[Dec 22 11:56:28] [debug]: Set proxy configuration to use NO proxy
[Dec 22 11:56:28] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[Dec 22 11:56:29] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
[Dec 22 11:56:29] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[Dec 22 11:56:29] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:56:29] [debug]: buildNotesIndex  - 'noteSubFolderId':  0
[Dec 22 11:56:29] [debug]: setupNoteFolderTables  - 'database version':  14
[Dec 22 11:56:29] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
[Dec 22 11:56:29] [debug]: loadNoteDirectoryList
[Dec 22 11:56:29] [debug]: reloadTagTree
[Dec 22 11:56:29] [debug]: reloadTagTree  - 'noteSubFolderIds':  ()
[Dec 22 11:56:29] [debug]: loadNoteDirectoryList
[Dec 22 11:56:29] [debug]: reloadTagTree
[Dec 22 11:56:29] [debug]: reloadTagTree  - 'noteSubFolderIds':  ()
[Dec 22 11:56:29] [debug]: reloadNoteSubFolderTree
[Dec 22 11:56:29] [debug]: reloadTagTree
[Dec 22 11:56:29] [debug]: reloadTagTree  - 'noteSubFolderIds':  (0)
[Dec 22 11:56:29] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:56:29] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:56:29] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:56:29] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:56:29] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:56:29] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:56:29] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:56:29] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:56:29] [info]: "QOwnNotes server listening on port 22222"
[Dec 22 11:56:29] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:56:29] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:56:29] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:56:29] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:56:29] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:56:29] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:56:29] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:56:29] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Dec 22 11:56:29] [debug]: reloadTagTree
[Dec 22 11:56:29] [debug]: reloadTagTree  - 'noteSubFolderIds':  ()
[Dec 22 11:56:30] [debug]: on_noteTreeWidget_currentItemChanged
[Dec 22 11:56:30] [debug]: setCurrentNote  - 'note':  Note: <id>1 <name>"How to improve your computer performance and SSD life span with a RAM disk" <fileName>"How to improve your computer performance and SSD life span with a RAM disk.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
[Dec 22 11:56:30] [debug]:  added to history:  NoteHistoryItem: <noteName>"How to improve your computer performance and SSD life span with a RAM disk" <noteSubFolderPathData>"" <cursorPosition>0 <relativeScrollBarPosition>0
[Dec 22 11:56:30] [debug]: updatePanelMenu  - 'updatePanelMenu'

```
</details>

Judging the time break, I'd say that entries prior to 11:56:01 are the ones that contain the initial auto-launch and update notification.

I don't believe the app crashes. My guess is the app closes as it would have had I chosen the "update" button. So whether I chose skip/download/cancel in the update notification window, the app closes just as it would have had I chosen to update. I've no proof of that, but it seems a reasonable guess.

Hope this helps.

**Comment by truthsword** [comment]
This is still happening (I'm at 20.1.11 now).

When I launch QON it is set to go directly to the tray. If an update notification window appears on launch, and I do not accept it, the program closes. No crash. No debug info.

However, if after the notification window appears, I open the program window from the tray using "Open QOwnNotes", I can then close the update notification, and the program remains active.

But... as I said, if I close the notification window, before opening the freshly launched program window from the tray icon, the program closes, and the tray icon vanishes.

**Comment by pbek** [comment]
> When I launch QON it is set to go directly to the tray. If an update notification window appears on launch, and I do not accept it, the program closes. No crash. No debug info.

Funny, I could reproduce that on Windows. I wonder if that also happens on Linux.

**Comment by pbek** [comment]
No, doesn't happen on Linux. App stays in the tray if `Cancel` is pressed.

**Comment by truthsword** [comment]
Iv Windows doing nearly anything that doesn't permit updating closes the freshly launched app. For example "x" out the update window, or select the "Just Download" button.

**Comment by truthsword** [comment]
Here's another twist on this same problem. 

I freshly launched QON to the tray, then got an update notification. As noted above, if I open the QON window via the tray "OpenQOwnNotes", and then close the update window (red "x" upper right corner), QON remains open. 

So I did that, but then...

I minimized QON back to the tray. Then reopened the QON window via the tray "OpenQOwnNotes". With QON open, I selected "Help" > "Check for updates" and the update window opened informing me that there was an update(s) available. So far... unremarkable.... but...

I then sent the QON window back to the tray (red "x") and closed the update window (red "x" upper right corner)... OON vanished (closed).

So... this issue isn't limited to a fresh launch. Any time QON's update window is terminated without updating QON will close if QON is in tray mode.

![](https://i.imgur.com/syqfvDJ.png)

**Comment by pbek** [comment]
## 20.1.17
- on Windows the application will now automatically be shown if the the update
  dialog is triggered, because otherwise Windows seems to quit the application
  when the update dialog is closed while the application is hidden

**Comment by pbek** [comment]
...found no other way around it. the application simply will be quit if the last open window is closed.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

You can test it by enabling the "fake old version number" in the *Debugging options* settings and restarting the app to trigger the dialog.

**Comment by truthsword** [comment]
That works!

**Comment by pbek** [comment]
Great, thank you for testing!
