### ISSUE TITLE
Inline codes are grayed out instead of green

### ISSUE THREAD

**Issue by Primokorn** [pbek/QOwnNotes#1516]
Hello,

Sorry but I found no information about. Could you please tell why all inline codes are not green?
Thanks!

![image](https://user-images.githubusercontent.com/5938828/71156302-07109500-2240-11ea-8364-e1d4f0b1203c.png)

Full code from QOwnNotes:
````
## Pièce pré-enregistrée - Parked document
Impossible de l'annuler en `FB08`. Passer par `FBV0` : document > supprimer

---

## Ouverture / Fermeture des intervalles comptables et des périodes
* `OB52` : intervalles FI (fait manuellement sur les filiales)
* `MMPV` : translation de période pour intégration MM-SD  
(prendre la date uniquement, pas période/exercice) (table MARV)
* `MMRV` pour modifier les autorisations dans le passe
* `OKP1` : intervalles CO`
````

`QOwnNotes - version 19.12.11 - AppVeyor - build 5104`

**Comment by pbek** [comment]
Interesting, only happens in lists with dark mode. I'll see if I can improve that.

**Comment by pbek** [comment]
## 19.12.12
- improved dark mode code block highlighting in the preview if editor highlighting
  styles are used

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Primokorn** [comment]
Fixed, thanks!

![image](https://user-images.githubusercontent.com/5938828/71237118-f5db8d00-2300-11ea-8284-def90023212f.png)

**Comment by pbek** [comment]
Great, thank you for testing!
