### ISSUE TITLE
Feature: Todo-List

### ISSUE THREAD

**Issue by maenujem** [pbek/QOwnNotes#1517]
It would be very cool if there would be a view (similar to the tags-view or using the "show todo list") that would collect/aggregate the tasks `- [ ] do this` from within the notes, grouped by note. 
Having this would make it easy to have notes and tasks together by topic (md-file) but also be able to manage/focus on the tasks/todo only without removing them from their context.

The todo-format in task-lists could also be extendet to the [todo.txt-format](https://github.com/todotxt/todo.txt) to be eg: `- [ ] (A) do this @email +football + sports due:2019-12-20`

**Comment by pbek** [comment]
It would be nice, but extremely un-performant to parse all notes for checkbox lists all the time if you have 1000+ notes. And this almost sounds like a different app, because you would also need to be able to search and filter notes and also write note files...

**Comment by pbek** [comment]
And I use markdown headlines to group tasks. That also would need to be taken into account.

**Comment by Waqar144** [comment]
> It would be nice, but extremely un-performant to parse all notes for checkbox lists all the time if you have 1000+ notes. And this almost sounds like a different app, because you would also need to be able to search and filter notes and also write note files...

Theoretically speaking, it could be done without parsing. Every time a checkbox is entered, we can store its block number, note_id/name in the database. Every change to the element would be reflected in the database. This can work with new tasks, but, there is no other way to find the existing tasks in notes without parsing.

**Comment by data-man** [comment]
[Taskwarrior](https://taskwarrior.org) is awesome.
Can be used as a command-line app (in QON scripts) and as a library.

**Comment by maenujem** [comment]
It might have similar performance as a quick search over all the notes plus some time to copy the matching lines to the output. Similar to what IntelliJ does for the TODO entries in all code: list matches grouped by file with click-navigation to the entry. 
On command line it would be `grep -iR '\- \[ \]' ./` .

**Comment by pbek** [comment]
IntelliJ takes several GB of memory (at least PhpStorm or Clion do) to keep track of everything. :laughing:

**Comment by Neko150** [comment]
i wonder
