### ISSUE TITLE
Highlighting of checked and unchecked checkboxes in note edit

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1519]
I want a highlighting of checked and unchecked checkboxes in the note edit.
And I want a way to inherit styling information from one schema to another to not have to include new styles for all existing schemes beside `Light` and `Dark`.

**Comment by Waqar144** [comment]
How would you highlight them as?

**Comment by pbek** [comment]
> How would you highlight them as?

Just the `- [ ]` and `- [x]` part to make it easier to spot done and undone tasks in text...

**Comment by pbek** [comment]
## 19.12.14
- checked and unckecked **checkboxes** are now **highlighted** in the note editor
