### ISSUE TITLE
Feature Request: Calculator

### ISSUE THREAD

**Issue by dasmaetthes** [pbek/QOwnNotes#152]
Calculator - Allows computing the answer to equations in the note, with the answer inserted directly after the equation.

**Comment by pbek** [comment]
Thank you for your suggestion, sounds interesting,

**Comment by pbek** [comment]
Did you see a similar feature in an other application?
Where do you see the advantage of this feature over a calculator app and copy & pasting the result from there to QOwnNotes?

**Comment by dasmaetthes** [comment]
Tomboy has something similar.
http://www.robpvn.net/calcaddin/

**Comment by pbek** [comment]
Thank you for your example. But I still don't know how to represent that in markdown and what the use case for it would be. 😸

**Comment by eemantsal** [comment]
Well, for people who use their notes app to keep record of they expenses/incomes, etc, I think it would be a rather handy tool. Clear that they can use a calculator and pasting the results, but dasmaetthes' suggestion would save them a nice time. I don't think I'd use it at all, but if it can be implemented without increasing a lot the code and its complexity, other type of users would probably find it very practical.

**Comment by pbek** [comment]
How would the representation look like in markdown (since there is no syntax for it)?

**Comment by dasmaetthes** [comment]
The use case is as eemantsal already said for expenses, incomes. Or on weekend I wrote down a trip planing with distances per stage and it would be easier and faster just have a build in option to calculate the sum. I don't think there is some special markdown needed you just would write 20+45= and the result would be added.

**Comment by pbek** [comment]
where would you write that? in a new dialog that opens with a shortcut/button/menu-entry?

**Comment by dasmaetthes** [comment]
in markdown

**Comment by pbek** [comment]
In your opinion how should the calculation be triggered and by what mean should be decided what is equation to be calculated and what not? and how would it be possible to recalculate the equation?

**Comment by dasmaetthes** [comment]
For a simple method a equation would start with the first number write down and end with the equals sign between would be only numbers and the 4 stand operations allowed maybe also sqrt and ^x, if there are any other characters between it wouldn't be a equation. Recalculation could work on delete the result and equals sign, change numbers and  enter the equals again.

**Comment by pbek** [comment]
To do that in real time the whole note file would have to be reparsed again over and over again and probably the markdown parser changed, both a major pain in the a** and very slow. And still not all people (and the rest not all the time) would like auto detection and calculation of equations.

**Comment by pbek** [comment]
I think I found a solution.
In version 16.05.2 <kbd>Ctrl</kbd> + <kbd>Space</kbd> now tries to solve simple equations like
 `(4+5)*3=` in the current line in front of the cursor.
The result will be put into the note if the cursor is after the `=`.
Can you please test that when the version is released?

**Comment by pbek** [comment]
Version 16.05.2 is now out.
