### ISSUE TITLE
Feature request: Customize image and attachment Path

### ISSUE THREAD

**Issue by gongway** [pbek/QOwnNotes#1521]
QOwnNotes is very nice, I like it very much, unfortunately it has no APP for Android phone, finally I found an app called [easymark](https://play.google.com/store/apps/details?id=me.tshine.easymark) works well on Android, but the app is not maintained anymore.

The problem is that the EasyMark APP saves image and attachment in ./assets folder as default, but QOwnNotes saves image in ../media folder, and attachment in ../attachments folder as default.

I was wondering if it be possible to customize the default image and attachment path in QOwnNotes? or put a path parameter in the ini file?

Thank you very much.

**Comment by Waqar144** [comment]
Have you tried the Markor app?

**Comment by pbek** [comment]
I QOwnNotes images and attachments are handled differently, so they need different folders. But you can always put your images where you want manually and also create markdown image tags manually, QOwnNotes should not have problems with them.

**Comment by gongway** [comment]
> Have you tried the Markor app?

Tried, Markor cannot sync automatically, EasyMark can sync by WebDav automatically.

**Comment by gongway** [comment]
> I QOwnNotes images and attachments are handled differently, so they need different folders. But you can always put your images where you want manually and also create markdown image tags manually, QOwnNotes should not have problems with them.

Thank you for your reply.
The key point is that EasyMark can only select one folder to synchronize by WebDav, so it can 
 only recognize images in ./assets, which is the subfolder of current folder, but QOwnNotes stores images in ../media folder, which is the sibling of current markdown file folder, so I need to change the default image foleder, like what we can do in [Typora ](https://support.typora.io/media/about-image/Snip20161117_2.png)or MarkText.

**Comment by pbek** [comment]
You could try to close QON, rename the media folder to assets (for easymark) and create a symbolic link for assets with the name media (for QON).
