### ISSUE TITLE
New editor schema: Nord

### ISSUE THREAD

**Issue by salopst** [pbek/QOwnNotes#1522]
I want to submit a new editor schema. It is based on https://www.nordtheme.com/docs/colors-and-palettes, and is in no way officially supported by the creator of Nord. Obvs, delete the .txt extension to import.

[Nord.ini.txt](https://github.com/pbek/QOwnNotes/files/3994306/Nord.ini.txt)

**Comment by pbek** [comment]
Looking nice, thank you.

**Comment by pbek** [comment]
## 19.12.16
- added a **new editor color schema** *Nord* by @salopst

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
