### ISSUE TITLE
[Q] scripting language "vex" (sidefx houdini)

### ISSUE THREAD

**Issue by ballinger** [pbek/QOwnNotes#1529]
#### General question

is it possible to integrate houdini sidefx vex coding language into qownnotes? found something for sublime and vs studio..
https://github.com/teared/vex
https://github.com/melMass/vscode-vex

thanks

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Dec 31 13:07:31 2019`
**Version**: `20.1.0`
**Build date**: `Dec 31 2019`
**Build number**: `647`
**Platform**: `linux`
**Operating System**: `Fedora 30 (Thirty)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.12.1`
**Qt Version (runtime)**: `5.12.5`
**Portable mode**: `no`
**Settings path / key**: `/home/phil/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/phil/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `2560x1440`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `264`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://next.3demo.info`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `17.0.2.1`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_AG, en_AU, en_BS, en_BW, en_BZ, en_CA, en_DK, en_GB, en_GH, en_HK, en_IE, en_IN, en_JM, en_MW, en_NA, en_NG, en_NZ, en_PH, en_SG, en_TT, en_US, en_ZA, en_ZM, en_ZW`
**Language names**: `English (Antigua & Barbuda), Australian English (Australia), English (Bahamas), English (Botswana), English (Belize), Canadian English (Canada), English (Denmark), British English (United Kingdom), English (Ghana), English (Hong Kong SAR China), English (Ireland), English (India), English (Jamaica), English (Malawi), English (Namibia), English (Nigeria), English (New Zealand), English (Philippines), English (Singapore), English (Trinidad & Tobago), American English (United States), English (South Africa), English (Zambia), English (Zimbabwe)`
**Application dictionaries path**: `/home/phil/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/phil/nextcloud/Notes`
**remotePath**: *empty*
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/phil/nextcloud/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://next.3demo.info`
**username**: `phil`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `28`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2019-12-31T12:55:36.586`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Monospace,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Sans Serif,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Monospace,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Sans Serif,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/remove-note** (QString): `16384`
**NoteHistory-1** (QVariantList): `<variant list with 51 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `50`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-togglePanel-notePreviewDockWidget** (QKeySequence): `Alt+``
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowDifferentNoteFileName** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `true`
**darkModeColors** (bool): `true`
**darkModeIconTheme** (bool): `true`
**darkModeTrayIcon** (bool): `true`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (int): `23`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `false`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `1`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/phil/nextcloud/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `17.0.2.1`
**previousWorkspace** (QString): `31164118-03ec-4e44-9545-61655d4a5fc9`
**recentNoteFolders** (QString): `/home/phil/nextcloud`
**restoreCursorPosition** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2019-12-08T21.11.16, Note 2019-12-07T20.29.27, Note 2019-12-01T10.53.27, vex, Note 2019-11-28T23.56.13, Note 2019-11-27T20.02.33, Note 2019-09-22T22.09.25`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `1`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useUNIXNewline** (bool): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-31164118-03ec-4e44-9545-61655d4a5fc9/name** (QString): `preview`
**workspace-31164118-03ec-4e44-9545-61655d4a5fc9/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-31164118-03ec-4e44-9545-61655d4a5fc9/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `false`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 31164118-03ec-4e44-9545-61655d4a5fc9`

## System environment

**SHELL**: `/bin/bash`
**XDG_CONFIG_DIRS**: `/etc/xdg:/usr/share/kde-settings/kde-profile/default/xdg`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**HISTCONTROL**: `ignoredups`
**XDG_MENU_PREFIX**: `kf5-`
**HOSTNAME**: `workstation`
**HISTSIZE**: `1000`
**SSH_AUTH_SOCK**: `/tmp/ssh-8HKq1myiWK9w/agent.1647`
**DESKTOP_SESSION**: `/usr/share/xsessions/plasma`
**SSH_AGENT_PID**: `1667`
**GDK_CORE_DEVICE_EVENTS**: `1`
**XDG_SEAT**: `seat0`
**PWD**: `/home/phil`
**LOGNAME**: `phil`
**XDG_SESSION_DESKTOP**: `KDE`
**XDG_SESSION_TYPE**: `x11`
**XAUTHORITY**: `/home/phil/.Xauthority`
**GTK2_RC_FILES**: `/home/phil/.gtkrc-2.0-kde4`
**HOME**: `/home/phil`
**SSH_ASKPASS**: `/usr/bin/ksshaskpass`
**LANG**: `en_US.UTF-8`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**KDE_SESSION_UID**: `1000`
**XDG_SESSION_CLASS**: `user`
**LESSOPEN**: `||/usr/bin/lesspipe.sh %s`
**USER**: `phil`
**KDE_SESSION_VERSION**: `5`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**DISPLAY**: `:0`
**SHLVL**: `1`
**XDG_VTNR**: `1`
**XDG_SESSION_ID**: `2`
**GS_LIB**: `/home/phil/.fonts`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**KDEDIRS**: `/usr`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**XCURSOR_THEME**: `breeze_cursors`
**XDG_DATA_DIRS**: `/home/phil/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share`
**KDE_FULL_SESSION**: `true`
**PATH**: `/home/phil/.local/bin:/home/phil/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**MAIL**: `/var/spool/mail/phil`
**_**: `/usr/bin/kwrapper5`
**SESSION_MANAGER**: `local/unix:@/tmp/.ICE-unix/1790,unix/unix:/tmp/.ICE-unix/1790`
</details>

**Comment by pbek** [comment]
Can you please elaborate on what you mean by "integrate".

**Comment by ballinger** [comment]
a syntax checker or/and a vex dictionary would be awesome, but i was more thinking about marking code segments that belong together.  not sure what it is called... syntax highliting?

**Comment by pbek** [comment]
@Waqar144 is this something you want to wrap your head around

**Comment by Waqar144** [comment]
Alright, I will try to get this done soon.

**Comment by pbek** [comment]
@ballinger are we talking about code block syntax highlighting for "vex"?

**Comment by ballinger** [comment]
hey, sounds promising :) i personally cant code. i usually get lost in those few code lines that i write for vfx projects. so thats why i was searching for some syntax highlighting thing for vex. code block syntax highlight sounds about right. marking code blocks that belong together with colours.
thanks for looking into that!

**Comment by Waqar144** [comment]
> hey, sounds promising :) i personally cant code. i usually get lost in those few code lines that i write for vfx projects. so thats why i was searching for some syntax highlighting thing for vex. code block syntax highlight sounds about right. marking code blocks that belong together with colours.
> thanks for looking into that!

It would be great if you could provide some example codes of this language.

**Comment by ballinger** [comment]
sure,
here: https://github.com/kiryha/Houdini/wiki/vex-snippets
and here: http://www.tokeru.com/cgwiki/index.php?title=HoudiniVex

**Comment by pbek** [comment]
## 20.1.2
- added vex code block highlighting support (for [#1529](https://github.com/pbek/QOwnNotes/issues/1529), thank you @Waqar144)

There now is a new release, could you please test it and report if it works for you?

**Comment by ballinger** [comment]
you guys are too quick for me  :) thanks works great!

**Comment by pbek** [comment]
Great, thank you for testing!
