### ISSUE TITLE
Feature Request: Note TableOfContent

### ISSUE THREAD

**Issue by dasmaetthes** [pbek/QOwnNotes#153]
Note TableOfContent - Displays in a menu the table of content of the current note. Headers are guessed from heading layer e.g.: "#" - 1. Layer; "###" 3. Layer.

**Comment by pbek** [comment]
Thank you for your suggestion, that's a good idea, I already had something like that in mind.

**Comment by pbek** [comment]
This is now implemented in the current release 16.05.0. Can you please test it and report back?
It supports all markdown header types that QOwnNotes supports.

**Comment by dasmaetthes** [comment]
Thx, I will test it in next time

**Comment by dasmaetthes** [comment]
Very nice future.
But it seems that the jump to the headline doesn't work correct. When I click in the navigation a headline (Füllung) you can only see the start of this part. See attached picture. Nice would be when it would scroll the note down so that the headline would be the first visible row or scrolling down as much as possible

http://owncloud.infogeneration.de/index.php/s/Ri6SKpptWeokL1S

**Comment by pbek** [comment]
It sets the cursor position to the headline. The scrolling is done automatically by the text edit. I'm not sure yet if I can fulfill your wish.

**Comment by pbek** [comment]
In version 16.05.2 when clicking a headline in the navigation bar the text beneath the headline will be now made fully visible by scrolling more intelligently. Can you please test that when it is released?

**Comment by pbek** [comment]
Version 16.05.2 is now out.
