### ISSUE TITLE
Caldav server settings 

### ISSUE THREAD

**Issue by jacme31** [pbek/QOwnNotes#1530]
#### Expected behaviour
I'am trying to use my Synology caldav server in the Todo settings. 

#### Actual behaviour
No response and no calendar appears in the list. 
It seems hat a propfind request with depth= infinity is not allowed on my server (see debug)

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```cloudConnection:  CloudConnection: <id>1 <name>"Par défaut" <serverUrl>"" <username>"" <priority>1
[déc 31 15:24:55] [debug]: Reply from  "/Documents/Jacme31/Calendrier/"
[déc 31 15:24:55] [warning]: "QNetworkReply error 201 from url http://192.168.0.100:5005/Documents/Jacme31/Calendrier/: " "Error transferring http://192.168.0.100:5005/Documents/Jacme31/Calendrier/ - server replied: Forbidden"
[déc 31 15:24:55] [debug]: Reply from ownCloud calendar page "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>403 Forbidden</title>\n</head><body>\n<h1>Forbidden</h1>\n<p>PROPFIND requests with a Depth of \"infinity\" are not allowed for /Documents/Jacme31/Calendrier/.</p>\n</body></html>\n"
[déc 31 15:24:55] [debug]: parseCalendarData  - 'data':  "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>403 Forbidden</title>\n</head><body>\n<h1>Forbidden</h1>\n<p>PROPFIND requests with a Depth of \"infinity\" are not allowed for /Documents/Jacme31/Calendrier/.</p>\n</body></html>\n"


```
</details>

**Comment by pbek** [comment]
> [déc 31 15:24:55] [warning]: "QNetworkReply error 201 from url http://192.168.0.100:5005/Documents/Jacme31/Calendrier/: " "Error transferring http://192.168.0.100:5005/Documents/Jacme31/Calendrier/ - server replied: Forbidden"


did you check on that?

**Comment by pbek** [comment]
If you want to play around with the `PROPFIND` you can do so here:

https://github.com/pbek/QOwnNotes/blob/9bbeb8d284d5c62cd66f6742267111b81b2d9e0f/src/services/owncloudservice.cpp#L619-L627

**Comment by jacme31** [comment]
Thanks,  
I play some URL with CURL . The only way to work with my CALDAV Server was
`curl` -v -X PROPFIND --H "Depth:1" -H "Content-Type: text/xml"
-H "Brief:t" -d "<D:propfind xmlns:D='DAV:' xmlns:ns0='DAV:'><D:prop><D:displayname/></D:prop></D:propfind>" http://192.168.0.100:5005/Documents/Jacme31/Calendrier/jacme31` 

**--H "Depth:1"** seems mandatory to get a list in the response 

It is what I understand but I am not an expert ...

**Comment by pbek** [comment]
Adding this header seems to work with Nextcloud, so I will attempt to add it in the next release.

**Comment by pbek** [comment]
## 20.1.1
- attempted to add support for the Synology CalDAV server

There now is a new release, could you please test it and report if it works for you?

**Comment by jacme31** [comment]
It still does not work.
To help you, I attach an extract of a wireshark trace with the Qownnotes request which does not work and a request which works.
Thank you very much for your great responsiveness. My problem is not blocking nor very serious. Do not consider it a priority.
[Note 2020-01-02T19.55.41.pdf](https://github.com/pbek/QOwnNotes/files/4017035/Note.2020-01-02T19.55.41.pdf)

**Comment by pbek** [comment]
Seems like I messed up that header, I'll try again in the next release.

**Comment by pbek** [comment]
## 20.1.2
- again attempted to add support for the Synology CalDAV server

There now is a new release, could you please test it and report if it works for you?

**Comment by jacme31** [comment]
It works.
I can manage my tasks.
For the moment I have a unique calendar where tasks and events are mixed and I see everything. I will try to refine my server configuration. I will tell you later if I believe there is an other  QownNotes problem.
Thanks and have a nice week end

**Comment by pbek** [comment]
Great, thank you for testing! Also have a great weekend! :grin:
