### ISSUE TITLE
Force close when opening a note: Visual C++ Runtime Library

### ISSUE THREAD

**Issue by Primokorn** [pbek/QOwnNotes#1532]
Hello,
Back from vacation I've upgraded from v19.12.13 to v20.1.0. (.exe file launched on a Windows 7 computer).
I can no longer open a note (no issue with most notes). Here is the message I get then QOwnNotes is force closed:
![image](https://user-images.githubusercontent.com/5938828/71656616-334a0c80-2d3c-11ea-8ad1-6741c36bd35a.png)

Full code of the note [here](https://framabin.org/p/?f8cc46f05e7efc01#jZacqjO5nE1VY6uPeR2uS7KEG9hyUUlRNtoC+vYEVAY=)

Thanks in advance.

EDIT: log once the above pop-up is here
![image](https://user-images.githubusercontent.com/5938828/71656743-e155b680-2d3c-11ea-9995-3830638efbab.png)

**Comment by pbek** [comment]
What happens if you run QOwnNotes in a new session, like `QOwnNotes.exe --session test2020`?

**Comment by pbek** [comment]
@Waqar144, this is also reproducible under Linux. It's a crash in the preview. If you turn the preview off the crash doesn't happen.

**Comment by Primokorn** [comment]
> QOwnNotes.exe --session test2020

I copied the code and it works.

**Comment by pbek** [comment]
> I copied the code and it works.

As long as you have no preview turned on, right?

**Comment by Primokorn** [comment]
Exactly.

**Comment by Waqar144** [comment]
It's access out of bounds probably.

Will fix it by tonight.

**Comment by pbek** [comment]
The crash happens in `CodeToHtmlConverter::highlightComment` and the note works until you add the 2nd last line `* [IP lock](http://zend.snr.fr/technique/tools/serviceDesk/IncidentManagement/ticket/detail/id/518834)`.

**Comment by pbek** [comment]
But simply fixing the "access out of bounds" didn't help, because if the method returns a `-1` you'll get into an infinite loop. :grin:

**Comment by Waqar144** [comment]
> But simply fixing the "access out of bounds" didn't help, because if the method returns a `-1` you'll get into an infinite loop. grin

Yeah but its really very much impossible to get a -1 out of there. :rofl:

The problem here is that it is trying to highlight text it shouldn't be. The reason is code blocks are kind of inline so it confuses the highlighter.

The highlighter works on the assumption that ` ``` ` is on a separate line.

**Comment by pbek** [comment]
Great, worked for me!

**Comment by Primokorn** [comment]
What's working? Do you expect new test from me?

**Comment by Waqar144** [comment]
Not yet.
@pbek is talking about the latest changes.

There will be a new release soon, then you will be able to test

**Comment by pbek** [comment]
## 20.1.1
- fixed possible crash for inline code blocks in preview highlighter
  (for [#1532](https://github.com/pbek/QOwnNotes/issues/1532), thank you @Waqar144)

There now is a new release, could you please test it and report if it works for you?

**Comment by Primokorn** [comment]
Fixed, well done guys!

**Comment by pbek** [comment]
Great, thank you for testing!
