### ISSUE TITLE
 How to install Raspberry Pi native system?

### ISSUE THREAD

**Issue by bluehysteric** [pbek/QOwnNotes#1533]
How to install QOwnNotes on Raspberry Pi native system?

**Comment by pbek** [comment]
> How to install Raspberry Pi native system?

Can you please elaborate on what you are talking about?

**Comment by bluehysteric** [comment]
How to install QOwnNotes on Raspbian Linux 10

**Comment by pbek** [comment]
It depends on your operating system: https://www.qownnotes.org/installation

**Comment by pbek** [comment]
> How to install QOwnNotes on Raspbian Linux 10

https://www.qownnotes.org/installation#Debian

**Comment by bluehysteric** [comment]
Thanks! I'll try

**Comment by pbek** [comment]
And there also is a Raspbian 10 release: https://build.opensuse.org/package/binaries/home:pbek:QOwnNotes/desktop/Raspbian_10
(you only need to change to repository url in the Debian instruction)

**Comment by bluehysteric** [comment]
Ok i am preparing to do this

**Comment by bluehysteric** [comment]
Can I install it with the command?
`wget https://build.opensuse.org/package/binaries/home:pbek:QOwnNotes/desktop/Raspbian_10/Release.key -O - | sudo apt-key add -


sudo bash -c "echo 'deb https://build.opensuse.org/package/binaries/home:pbek:QOwnNotes/desktop/Raspbian_10/ /' >> /etc/apt/sources.list.d/qownnotes.list"


sudo apt-get update


sudo apt-get install qownnotes`

**Comment by pbek** [comment]
The key-file doesn't exists, you could try <http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Debian_10/Release.key>.

**Comment by bluehysteric** [comment]
ok,
Let me try

**Comment by bluehysteric** [comment]
It prompts me that I cannot find the package
`sudo apt-get install qownnotes
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package qownnotes`

**Comment by bluehysteric** [comment]
Can you add the Raspberry Pi installation method in the installation instructions?

**Comment by pbek** [comment]
You didn't get an error at `sudo apt-get update`? Please try that again...

> Can you add the Raspberry Pi installation method in the installation instructions?

I have no Raspberry Pi with Raspian 10 to test it.

**Comment by pbek** [comment]
And which architecture is your Raspberry Pi using, the package is only built for armhf.

**Comment by pbek** [comment]
In case you are using a Raspberry Pi 4, I now added `aarch64` to the build config, it is currently building on OBS: https://build.opensuse.org/package/live_build_log/home:pbek:QOwnNotes/desktop/Raspbian_10/aarch64

**Comment by bluehysteric** [comment]
I am using Raspberry Pi 4 and I am testing it

**Comment by pbek** [comment]
So was you able to install the package?

**Comment by pbek** [comment]
I now also added installation instructions to https://www.qownnotes.org/installation#Raspbian
