### ISSUE TITLE
Cannot use ibus

### ISSUE THREAD

**Issue by K73SK** [pbek/QOwnNotes#1535]
#### Expected behaviour
When using ibus, I should be able to use input methods, such as anthy	
#### Actual behaviour
It doesn't read any input from it
#### Steps to reproduce
Start ibus, install an input method such as anthy, and then try to use it in QOwnNotes. Nothing :(

I know it's configured correctly as I use it in the browser and such all the time.

**Comment by pbek** [comment]
Did you make your input method work with other Qt applications? See: https://wiki.archlinux.org/index.php/IBus

**Comment by K73SK** [comment]
Yes, it works fine with other Qt applications. Just tested it in not just the browser, but tested it in OpenOffice Writer, Discord, and a few other apps. However it doesn't work in ALL of them (i.e. Clementine music player).

I do have the proper locales uncommented in my `locale.gen` file. I also did setup the environment properly:
```
$ env|grep ibus
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
GTK_IM_MODULE=ibus
```

**Comment by pbek** [comment]
> However it doesn't work in ALL of them (i.e. Clementine music player).

Maybe your distribution (you didn't post any information about your system, like advised in the issue template) needs a qt-dbus package or extra configuration for Qt.

**Comment by K73SK** [comment]
Sorry, there was a slew of information I didn't just want posted on a github board lol. Didn't have enough time to go through all of it that it was printing out, but saw it did print out a lot of ENV variables. I'm working on gentoo.
```
$ uname -a
Linux gentoosystem 4.19.86-gentoo #2 SMP Wed Nov 27 23:19:37 CST 2019 x86_64 Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz GenuineIntel GNU/Linux

$ emerge --search dev-qt/qtdbus
  
[ Results for search key : dev-qt/qtdbus ]
Searching...

*  dev-qt/qdbus
      Latest version available: 5.13.2
      Latest version installed: 5.13.2
      Size of files: 8,897 KiB
      Homepage:      https://www.qt.io/
      Description:   Interface to Qt applications communicating over D-Bus
      License:       || ( GPL-2 GPL-3 LGPL-3 ) FDL-1.3

*  dev-qt/qtdbus
      Latest version available: 5.13.2
      Latest version installed: 5.13.2
      Size of files: 47,594 KiB
      Homepage:      https://www.qt.io/
      Description:   Qt5 module for inter-process communication over the D-Bus protocol
      License:       || ( GPL-2 GPL-3 LGPL-3 ) FDL-1.3
```

**Comment by pbek** [comment]
I'm sorry, I'm not much on a Gentoo expert. :sweat_smile: maybe @internethering or @jpdigital can help.

**Comment by pbek** [comment]
I will close this until there is more information.
