### ISSUE TITLE
Feature: Add setting for default note title

### ISSUE THREAD

**Issue by rakekniven** [pbek/QOwnNotes#1537]
#### Expected behaviour
Be able to set my personal note title pattern

When creating a new note it should be like this for me:
```
2020-01-03 Notiz: <>
========================
```
#### Actual behaviour
Found no setting.
When creating a new note it shows up like:

```
Note 2020-01-03T08.12.41
========================
```

**Comment by pbek** [comment]
You can do that with the scripting engine: http://docs.qownnotes.org/en/develop/scripting/README.html#handlenewnoteheadlinehook

**Comment by rakekniven** [comment]
Ok, will adapt it.
Thank you and happy new year.

Any schedule how many releases you will do this year? :-)

**Comment by pbek** [comment]
> Ok, will adapt it.

great :grin: 

> Thank you and happy new year.

To you too! Thank you for all the translation work!

> Any schedule how many releases you will do this year? :-)

As many as needed. :laughing:
