### ISSUE TITLE
Problems with calculations in list-items

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#1539]
#### Expected behaviour
Calculations should produce predictable results in lists (discard the list-character for running the calculation).

#### Actual behaviour
```
1+1=2

- within a list
- 1+1=0

* within an other list type
* 1+1=nan

+ this list seems to work (coincidentally?)
+ 1-1=0
```

Clearly the list-character is taken into account when running the calculations.

Possible solution(s):
- force calculations to not use inner spaces
- disregard list-characters at the beginning of the line when processing calculations

Version: qownnotes 19.12.16-1

**Comment by pbek** [comment]
Yes, currently those calculations only work in an empty line.

**Comment by sanderboom** [comment]
> Yes, currently those calculations only work in an empty line.

Well, for the record: the following also works:
```
testing a line containing calculations: 1+1=2
```

**Comment by pbek** [comment]
Oh, seems like I already added some conveniences. :laughing:

**Comment by pbek** [comment]
## 20.1.2
- again attempted to add support for the Synology CalDAV server

There now is a new release, could you please test it and report if it works for you?

**Comment by sanderboom** [comment]
Awesome quick fix, thanks!  :rocket:

One more thing that caught me by surprise:

Second calculation on the same line is incorrect:
```
A first calculation: 1+1=2. A second calculation on the same line: 100*2=2
```

*but* if I decrease the width of the editing pane and the lines wrap, the result is correct:

```
A first calculation: 1+1=2. A second calculation
on the same line: 100*2=200
```

So the wrapping is not a real 'soft wrap' (I think I saw this before regarding list generation)? 

- Is there a fix to have multiple correct calculations on the same line?
- Is there a way to implement real 'soft wrapping' (maybe even with an icon and visual indent like in the following screenshot:)

<img width="265" alt="image" src="https://user-images.githubusercontent.com/5956570/71765447-27557a80-2ef5-11ea-8d88-ff4572e5db9c.png">

I know I'm asking a lot :wink:

**Comment by pbek** [comment]
> Second calculation on the same line is incorrect:

that was never supported, feel free to open a different feature request

> but if I decrease the width of the editing pane and the lines wrap, the result is correct:

that works by accident because I jump to `StartOfLine` and not `StartOfBlock` (so I now discovered the difference, thank you :laughing: )

https://github.com/pbek/QOwnNotes/blob/1cd6040e30c5a5c0cd3d97667d80fc3a3157efcc/src/mainwindow.cpp#L9151

**Comment by sanderboom** [comment]
> (so I now discovered the difference, thank you)

You're welcome :yum:
