### ISSUE TITLE
[I] Connection to CALDav Server (Fastmail) results in "server replied: Unsupported Media Type"

### ISSUE THREAD

**Issue by chuckgit123** [pbek/QOwnNotes#1544]
#### Expected behaviour

Successful connect to the Fastmail CalDav server.

#### Actual behaviour

As soon as the details are configured and the "Get Calendar List" button is clicked, the server responds with (from the log output where I anonymized USERNAME and UID):
```
[11:30:20] [warning] "QNetworkReply error 299 from url https://caldav.fastmail.com/dav/calendars/user/USERNAME@fastmail.net/b12345fa-d123-12ae-ba1a-937a21c20d36: " "Error transferring https://caldav.fastmail.com/dav/calendars/user/USERNAME@fastmail.net/b12345fa-d123-12ae-ba1a-937a21c20d36 - server replied: Unsupported Media Type"
```

#### Steps to reproduce

Configure Todos with a Calendar URL.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[11:30:20] [warning] "QNetworkReply error 299 from url https://caldav.fastmail.com/dav/calendars/user/USERNAME@fastmail.net/b12345fa-d123-12de-ba1a-937a21c20d36: " "Error transferring https://caldav.fastmail.com/dav/calendars/user/USERNAME@fastmail.net/b12345fa-d123-12de-ba1a-937a21c20d36 - server replied: Unsupported Media Type"
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sa. Jan. 4 11:52:50 2020`
**Version**: `20.1.0`
**Build date**: `Dec 31 2019`
**Build number**: `647`
**Platform**: `linux`
**Operating System**: `Fedora 30 (Workstation Edition)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.11.1`
**Qt Version (runtime)**: `5.12.5`
**Portable mode**: `no`
**Settings path / key**: `/home/USERNAME/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/USERNAME/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1680x1050`
**Screen resolution(s)**: `1680x1050, 2560x1440`
**Icon theme**: `Adwaita`
**Notes in current note folder**: `244`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/USERNAME/Documents/notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `Notes`
**database file**: `/home/USERNAME/Documents/notes/notes.sqlite`

## Settings

**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-01-04T11:48:44.408`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Rezepte`
**MainWindow/noteTextEdit.code.font** (QString): `Source Code Pro,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Cantarell,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Source Code Pro,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Cantarell,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/calendar-cache-emptied** (int): `1024`
**NoteHistory-1** (QVariantList): `<variant list with 11 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `10`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowDifferentNoteFileName** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (bool): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (bool): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (bool): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (int): `22`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/USERNAME/Documents/notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/ignoreNonTodoCalendars** (bool): `false`
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (int): `2`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): `https://caldav.fastmail.com/dav/calendars/user/USERNAME@fastmail.net/b12345fa-d123-12de-ba1a-937a21c20d36`
**ownCloud/todoCalendarCalDAVUsername** (QString): `USERNAME@fastmail.net`
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**restoreCursorPosition** (bool): `true`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useUNIXNewline** (bool): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`
</details>

**Comment by pbek** [comment]
Did this work before with Fastmail?
Can you please also try the latest release of QOwnNotes.

**Comment by chuckgit123** [comment]
Never tried before, sorry.
I just tried with version 20.1.2 - same behavior ...

**Comment by pbek** [comment]
I don't think `https://caldav.fastmail.com/dav/calendars/user/USERNAME@fastmail.net/b12345fa-d123-12de-ba1a-937a21c20d36` is the correct server url. Can you please try `https://caldav.fastmail.com`, see <https://www.fastmail.com/help/technical/servernamesandports.html#calendar>.

**Comment by chuckgit123** [comment]
I should've mentioned that I tried that first - with the following result:

`[11:43:23] [warning] "QNetworkReply error 203 from url https://caldav.fastmail.com: " "Error transferring https://caldav.fastmail.com - server replied: Not Found"
`

**Comment by pbek** [comment]
Did you make your fastmail caldav already work with some other application?

**Comment by pbek** [comment]
And maybe what's about `https://caldav.fastmail.com/dav/calendars/user/USERNAME@fastmail.net`?

**Comment by chuckgit123** [comment]
When I use `https://caldav.fastmail.com/dav/calendars/user/USERNAME@fastmail.net` I get

`
[11:50:19] [warning] "QNetworkReply error 299 from url https://caldav.fastmail.com/dav/calendars/user/USERNAME@fastmail.net: " "Error transferring https://caldav.fastmail.com/dav/calendars/user/USERNAME@fastmail.net - server replied: Unsupported Media Type"
`

I use the fastmail calendars from iOS ...

**Comment by chuckgit123** [comment]
Hm, maybe fastmail doesn't support Todo items ... I didn't find any information about that at fastmail.
The "Ignore calendars that don't support todo items" checkbox lead me to the conclusion that if the server wouldn't support todo items the app would handle that (somehow) ... so I wasn't expecting these log entries.

**Comment by Waqar144** [comment]
> When I use `https://caldav.fastmail.com/dav/calendars/user/USERNAME@fastmail.net` I get

You have to replace `USERNAME` with your username, e.g:
```
waqar@fastmail.net
```

**Comment by chuckgit123** [comment]
Naja, sure - thats what I did (I‘m just a bit paranoid, thats why I replaced it with USERNAME when posting it). 😀

**Comment by chuckgit123** [comment]
Ok, I did a little research: I had a look into the code and posting via curl the XML from the `owncloudservice.cpp` file at line 619 resulted in:

```
[...]
<h1>Unsupported Media Type</h1>
<p>This method requires an XML body</p>
[...]
```

Therefore I changed the lines 632 and 696 of `owncloudservice.cpp` to use `application/xml` instead of `application/x-www-form-urlencoded`:

```c++
    r.setHeader(QNetworkRequest::ContentTypeHeader,
                QStringLiteral("application/xml"));
```
Now retrieving calendars seems to work - if I specify the full path incl. calendar I just see one entry, if I use `https://caldav.fastmail.com/dav/calendars/user/USERNAME@fastmail.net` I see a list of calendars.

So far so good - I guess this is the expected behavior, right?

But now I can't save any new entries:
```
"QNetworkReply error 201 from url https://caldav.fastmail.com/dav/calendars/user/USERNAME@fastmail.net/be74e123-1924-4115-800b-6cb3ca23c009/qownnotes-aa7c2e2f-4f82-465c-858c-1e57a4f0fa01.ics: " "Error transferring https://caldav.fastmail.com/dav/calendars/user/USERNAME@fastmail.net/be74e123-1924-4115-800b-6cb3ca23c009/qownnotes-aa7c2e2f-4f82-465c-858c-1e57a4f0fa01.ics - server replied: Forbidden"
```

But at least one step further ...

**Comment by pbek** [comment]
Switching those headers to application/xml seems to have no effect on Nextcloud, so I changed them now.

## 20.1.3
- improved Fastmail CalDav server support

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by chuckgit123** [comment]
Thanks! Now I see the calendars in the settings.

But I'm still not able to save them (still get a "server replied: Forbidden") - even though I've chosen a calendar which supports todo items (by checking "Ignore calendars that don't support todo items").

Not sure how to proceed here. Is there an easy way to enable a more verbose (debug) logging to see whats going on?

**Comment by pbek** [comment]
I'm already outputting the whole error message :grimacing:

**Comment by chuckgit123** [comment]
I was hoping to increase the log level to a point where I can see what exactly was sent to the server.
If this is an issue on fastmail side, that would be helpful for opening a ticket there. It also might be useful to gain more insights on what exactly is going on ...

**Comment by pbek** [comment]
You already were build QON yourself, weren't you? You can output anything you like as debug message then.

**Comment by pbek** [comment]
I will close this issue until there is more information.
