### ISSUE TITLE
Export to Epub

### ISSUE THREAD

**Issue by eemantsal** [pbek/QOwnNotes#155]
Of course the ability of exporting to PDF is almost obligatory for every rich text and graphic insertion capable programs, but Epub has some advantages when we don't need that our notes layout and design remains unvriable: it is not only the standard (don't know if real or just "de facto", but it indeed is) for electronic book publishing but also adapts the layout to screen sizes and shapes, whle PDF doesn't, so if you read a PDF on a tablet or phone and you turn your device so the screen orientation becomes horizontal, the PDF layout remains the same, whereas Epub adapts the text and image disposition; besides, Epub permits to increase the text size in your reader software whereas PDF doesn't. Each format has its advantages; I think the ability to choose between both formats would be perfect.

**Comment by pbek** [comment]
Thank you for your suggestion, I did not know someone was using QOwnNotes as authoring software.
Do you know a ready to use C++ library that can generate Epub from markdown (or at least from html)?

**Comment by eemantsal** [comment]
Well, 90% of my notes are simple and brief text notes, but sometimes I wirte more complex and long ones, and since QownNotes is becoming more efficacious each day, I'm using less LibreOffice and doing more complex thing with QON.

I'm not a developer, o I don't know much about technical matters, but [here](https://puppet.com/blog/how-we-automated-our-ebook-builds-pandoc-and-kindlegen) they talk about a tool, Pandoc, to export to ePub format. Tehre's more info about Pandoc at [their site](http://pandoc.org/), I don't know if it has anything to do with C++ libraries, though. [Here's another tool](http://www.sitepoint.com/building-epub-with-php-and-markdown/), based on PHP, but I don't know if it is useful to you.

Sorry I can't be of more help. Let's hope someone more versed in programming reads this and can recommend exactly something 100% adequated for what you ask for.

**Comment by pbek** [comment]
Thank you for the links, unfortunately pandoc seems to be written in Haskell and the other tool is a PHP tutorial. But are of not much help yet. 😸

**Comment by eemantsal** [comment]
Well, I don't even know what is Haskell nor if PHP had anything to do with C++ (which I only know of because of it's fame) :sweat_smile:. Excuse my ignorance, heheh.
Well, let's try something else: in [this site](http://stackoverflow.com/questions/15997794/epub-library-for-c) someone mentions [this software](https://github.com/Sigil-Ebook/Sigil). In reality that person jut says «Take a look at Sigil and see how they do it», so I'm not very sure what he means, perhaps some piece of its code can serve for generating ePub files. I'm sure you will be able to find it out much better than me. :grin:

**Comment by pbek** [comment]
Thank you for researching that, I will look into it.

**Comment by jerger** [comment]
Hi, did you hear about [gitbook](https://www.gitbook.com/blog) already? They can generate ebup / mobi / pdf / website out of markdown files.
If you going to support their directory structure & git as storage backend - it seems to me you will get the generation for free. 

BDW: Their rich client editor is not really usable - so Im going to try out, how good your qownnotes will fit into this scenario ...

**Comment by pbek** [comment]
Gitbook is looking nice, but it's a paid piece of software, isn't it? <https://www.gitbook.com/pricing>

**Comment by jerger** [comment]
The hosting service is commercial, the gitbook rich client editor is closed source but free.
But fortunately the gitbook generator itself is apache2 licensed: https://github.com/GitbookIO/gitbook

**Comment by pbek** [comment]
Ah, I see. It's an electron app... That will not help us with an epub export. ;)

**Comment by PiotrDuda** [comment]
Epub is simply html (subset) files packed in zip archive with some metadata, images and optionally fonts.

**Comment by Letterus** [comment]
Maybe intregation of pandoc as external tool or of MultiMarkdown will do? See issue #573. I'm using QOwnNotes for authoring as well. ;-)

**Comment by pbek** [comment]
That's what the scripting engine is for (see #573). :) I think I will close this feature request.
