### ISSUE TITLE
Two-line headline highlighting broken while typing

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1552]
#### Expected behaviour

First line should be highlighted as headline while entering `=` in the 2nd line.

#### Actual behaviour

First line is highlighted as normal text

#### Steps to reproduce

- enter `Headline` in note
- press return
- enter `===`
- no highlighting of the first line occurs

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

## General Info

**Version**: `20.1.3`
**Build date**: `Jan  6 2020`
**Build number**: `650`
**Platform**: `linux`
**Operating System**: `KDE neon User Edition 5.17`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.9.5`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`

</details>

**Comment by pbek** [comment]
@Waqar144, I found a highlighting regression. :grin:

**Comment by Waqar144** [comment]
I doubt it was always like this. :grimacing:

**Comment by pbek** [comment]
I had to do quite some jumping through hoops to make that work back when I wrote it. :grinning:

**Comment by Waqar144** [comment]
We still don't support 'Multiline headings' ...

**Comment by pbek** [comment]
> We still don't support 'Multiline headings' ...

Please elaborate.

**Comment by Waqar144** [comment]
> > We still don't support 'Multiline headings' ...
> 
> Please elaborate.

Text:
```
Heading on first line
Second line
=============
```

-------------------

Actual result:

Heading on first line

Second line
=============


--------------------


Expected result:

Heading on first line
Second line
=============

**Comment by pbek** [comment]
Right, that never worked. Is that even part of markdown?

**Comment by Waqar144** [comment]
> Right, that never worked. Is that even part of markdown?

Well you can see that github highlights it. Its part of the CommonMark standard. Officially known as [Setext heading](https://spec.commonmark.org/0.29/#setext-heading)

**Comment by pbek** [comment]
> Well you can see that github highlights it. Its part of the CommonMark standard. Officially known as Setext heading

I learned something new. :laughing:
