### ISSUE TITLE
Markdown code blocks are no longer formatted

### ISSUE THREAD

**Issue by smokris** [pbek/QOwnNotes#1558]
#### Expected behaviour
In 20.1.2 and prior, Markdown code blocks (4 spaces indented) are properly formatted (font and colors are applied):
![20 1 2](https://user-images.githubusercontent.com/190164/72001897-5da43a00-3214-11ea-8197-66d6fcc4bb23.png)

#### Actual behaviour
In 20.1.3 and 20.1.5, the same text is no longer formatted:
![20 1 3 and 20 1 5](https://user-images.githubusercontent.com/190164/72001914-68f76580-3214-11ea-8623-934dfd124dd2.png)

#### Steps to reproduce
Create a note with 4-space-indented text.

**Comment by pbek** [comment]
Confirmed. Thank you for reporting.

@Waqar144, another regression?

**Comment by pbek** [comment]
## 20.1.6
- fixed four spaces code blocks (for [#1558](https://github.com/pbek/QOwnNotes/issues/1558), thank you @Waqar144)

**Comment by pbek** [comment]
Btw. it would be much better to use the code blocks with "ticks", then you can also profit from code block syntax highlighting.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by smokris** [comment]
Yes, I confirmed that in 20.1.6, four-space code blocks are formatted again.  Thanks, @pbek and @Waqar144!

> Btw. it would be much better to use the code blocks with "ticks", then you can also profit from code block syntax highlighting

The syntax highlighting looks nice!  I've started using it for some code blocks.  (Though for very short snippets, like in my screenshot above, I prefer the more concise four-space syntax.)

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by smokris** [comment]
I just updated to 20.1.13, and four-space code blocks are broken again.  😇

**Comment by Waqar144** [comment]
Can you share a screenshot?

**Comment by smokris** [comment]
(It's exactly the same as the screenshots at the top of this case.)

**Comment by Waqar144** [comment]
Ah yes,
The Library got updated, QON didn't. I guess it will be working in the next release.

**Comment by smokris** [comment]
Sounds good.  Thanks.

**Comment by pbek** [comment]
## 20.1.14
- fixed four spaces code blocks again (for [#1558](https://github.com/pbek/QOwnNotes/issues/1558), thank you @Waqar144)

There now is a new release, could you please test it and report if it works for you?

**Comment by smokris** [comment]
Thanks; that's an improvement — if I add a blank line between the `##` heading and the four-space code block, the code block is properly formatted.  But if the heading and the four-space code block are adjacent, the code block isn't formatted — could you fix that?

| No blank line; code block _isn't_ formatted | Has blank line; code block _is_ properly formatted |
| - | - |
| ![Screen Shot 2020-01-22 at 1 48 17 PM-scaled](https://user-images.githubusercontent.com/190164/72923951-01fea400-3d1e-11ea-8655-2d05db763821.png) | ![Screen Shot 2020-01-22 at 1 48 25 PM-scaled](https://user-images.githubusercontent.com/190164/72923953-03c86780-3d1e-11ea-9b4d-1f29fff30019.png) |

**Comment by Waqar144** [comment]
Hi.
That was a recent change to become more CommonMark compliant. CommonMark requires a space between an indented code block and preceding paragraph: https://spec.commonmark.org/0.29/#indented-code-block

**Comment by smokris** [comment]
Ah, thanks for the reference.  Yes, for paragraphs, it requires a blank line, but if I understand correctly, it does not require a blank line after a header.  On that page, example 85 says "indented code can occur immediately before and after other kinds of blocks" and demonstrates it by showing a heading followed by a four-space code block, without a blank line.

**Comment by Waqar144** [comment]
Now it allows `indented code block` after a heading (just like in the preview). For all other types of paragraphs, it will not work unless there is a blank line in between

**Comment by pbek** [comment]
## 20.1.15
- fixed stacked code block highlighting and improved non-fenced code block highlighting (thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by smokris** [comment]
20.1.15 looks great.  Thanks!

**Comment by pbek** [comment]
Great, thank you for testing!
