### ISSUE TITLE
Numeric literal preview problem in code block

### ISSUE THREAD

**Issue by samael205** [pbek/QOwnNotes#1559]
#### Expected behaviour

The same text on the source Markdown and the rendered markdown pannel

#### Actual behaviour

Hi, copying and pasting CSS code, QOwnnotes Do that:

![image](https://user-images.githubusercontent.com/649740/72065883-8ba28080-32df-11ea-864b-8f86fada7926.png)

#### Steps to reproduce

Paste this:

Botones
=======

```
.boton2 
    {
        background: #898989;
        border:0px;
        color:White;
        border-radius: 3px;
        padding: 6px 20px;
        font-size: 14px;
    }
    .boton2:focus 
    {
        outline:0px;
    }
    .boton2:hover 
    {
        background: #6E6E6E;   
    }
```

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Funny one. Thank you for reporting.

@Waqar144, a preview bug again. 😁

**Comment by pbek** [comment]
## 20.1.6
- fixed a numeric literal code block highlighting problem (for [#1559](https://github.com/pbek/QOwnNotes/issues/1559), thank you @Waqar144)

**Comment by Waqar144** [comment]
You can also use ` ```css ` style code blocks for better highlighting 😉

**Comment by pbek** [comment]
@Waqar144, now it looks like this::

![image](https://user-images.githubusercontent.com/1798101/72153452-4c8f3080-33ae-11ea-948e-a83608df6300.png)

    
```
    .boton2 
    {
        background: #898989;
        border:0px;
        color:White;
        border-radius: 3px;
        padding: 6px 20px;
        font-size: 14px;
    }
    .boton2:focus 
    {
        outline:0px;
    }
    .boton2:hover 
    {
        background: #6E6E6E;   
    }
```

**Comment by Waqar144** [comment]
fixed

**Comment by pbek** [comment]
> fixed

I think your PR is for the wrong branch.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
