### ISSUE TITLE
Exporting page size

### ISSUE THREAD

**Issue by eemantsal** [pbek/QOwnNotes#156]
It seems QON exports always to A4 sized page (or I haven't been able to find any configuration tool for this). Would be nice that the user could configure that; maybe one wants to print some brief notes in small A6 size sheets, put a staple and carry them into his pocket, or on the contrary, maybe one wants to make a big notice to put on some board and wants to use a plotter to print an A2 sheet. Think of any use case you can fit in some times. So, I think a simple page config dialog when exporting to PDF would be rather useful; and if it also permits to configure margin sizes, better than better.

**Comment by pbek** [comment]
Thank you for your suggestion, I will look into this.

**Comment by pbek** [comment]
In the just released version 16.05.6 you can now select the page format when exporting notes as PDF. Could you please test it and report if it works for you?

**Comment by pbek** [comment]
I just saw that it doesn't work under OS X, I will try to find out why later...
It works fine under Linux, KDE Neon.

**Comment by pbek** [comment]
in 16.05.7...
- made a workaround for the not working page setup dialog for the PDF 
  export under OS X and Windows 
  (for [Issue #156](https://github.com/pbek/QOwnNotes/issues/156))
    - you can select page sizes from A0 to A9
    - you can select the page orientation (portrait and landscape)

**Comment by eemantsal** [comment]
Well, yes and no. It does work well most of the time, but not always. :-/
I haven't tried all the page sizes, only A5 and A6; they permit to get 2 or 4 notes from a standard A4 sheet and easyly cut it in smaller sheets that are very practical for independent buying lists or things one need to comment to someone, for example, and fit in a shirt or pants pocket. But I don't see why other size should behave differently, so I suppose it's the same for any.
Well, as I said, most of the time we make text only notes, and when choosing a small size everything is ok, but if a note contains an image, or more, that is bigger than the export size, the disaster is served: the images overflow the page, and the text get mounted over the images, so you end with the text superposed on the image, and this one, cut between two pages, and with the areas that don't fit in the page, cut and missing.
I suppose that the "culprit" isn't the page size option, but the lack in QON of a image resize tool. As I commented days before, other Markdown editors have it; if it were fairly easy to implent some, would be cool you tried to do it, but if it is way too complication, you probably should add some warning  in the page size configuration dialog to inform the users that correct image sizing and page layout only works for A4.

**Comment by pbek** [comment]
I guess it would be easier to do more complex page styling operations in a 3rd party tool... from what I can see not a lot of people are embedding images anyway. We already deviated a lot from "simple note taking" to "how can I use QOwnNotes as desktop publishing software". 😸
