### ISSUE TITLE
Print and print preview not  working on the flatpak app

### ISSUE THREAD

**Issue by zendre4** [pbek/QOwnNotes#1560]
When try to print a note, the flatpak QOwnNotes crashed (close). The same problem appear when try to view the print preview.

Note I have try on Ubuntu 18.04 and Ubuntu 19.10.

#### Expected behaviour
Print a note
#### Actual behaviour
The app crashes when try to print
#### Steps to reproduce

- Install the flatpak app (hosted on flathub)
- Start the app and write a note
- Press CTRL + P or got to "Note -> Print -> Print Note"

At this time the app are crashed (closed)

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

[Jan 09 14:21:09] [debug]: Set proxy configuration to use NO proxy
[Jan 09 14:21:10] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[Jan 09 14:21:10] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
[Jan 09 14:21:10] [debug]: loadNoteDirectoryList
[Jan 09 14:21:10] [debug]: reloadTagTree
[Jan 09 14:21:10] [debug]: reloadTagTree  - 'noteSubFolderIds':  ()
[Jan 09 14:21:10] [debug]: filterNotesByTag  - 'tags':  (Tag: <id>5 <name>"Reunion" <parentId>0 ) 
[Jan 09 14:21:10] [debug]: filterNotesByTag  - 'fileNameList':  ("Réunion générale 31 janvier")
[Jan 09 14:21:10] [debug]: filterNotesByTag  - 'tags':  (Tag: <id>5 <name>"Reunion" <parentId>0 ) 
[Jan 09 14:21:10] [debug]: filterNotesByTag  - 'fileNameList':  ("Réunion générale 31 janvier")
[Jan 09 14:21:10] [debug]: reloadNoteSubFolderTree
[Jan 09 14:21:10] [debug]: reloadTagTree
[Jan 09 14:21:10] [debug]: reloadTagTree  - 'noteSubFolderIds':  (0)
[Jan 09 14:21:10] [debug]: loadNoteDirectoryList
[Jan 09 14:21:10] [debug]: reloadTagTree
[Jan 09 14:21:10] [debug]: reloadTagTree  - 'noteSubFolderIds':  (0)
[Jan 09 14:21:10] [debug]: filterNotesByTag  - 'tags':  (Tag: <id>5 <name>"Reunion" <parentId>0 ) 
[Jan 09 14:21:10] [debug]: filterNotesByTag  - 'fileNameList':  ("Réunion générale 31 janvier")
[Jan 09 14:21:10] [debug]: filterNotesByTag  - 'tags':  (Tag: <id>5 <name>"Reunion" <parentId>0 ) 
[Jan 09 14:21:10] [debug]: filterNotesByTag  - 'fileNameList':  ("Réunion générale 31 janvier")
[Jan 09 14:21:10] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
[Jan 09 14:21:10] [debug]: filterNotesByTag  - 'tags':  (Tag: <id>5 <name>"Reunion" <parentId>0 ) 
[Jan 09 14:21:10] [debug]: filterNotesByTag  - 'fileNameList':  ("Réunion générale 31 janvier")
[Jan 09 14:21:10] [debug]: reloadTagTree
[Jan 09 14:21:10] [debug]: reloadTagTree  - 'noteSubFolderIds':  ()
[Jan 09 14:21:17] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
[Jan 09 14:22:10] [debug]: Set proxy configuration to use NO proxy
[Jan 09 14:22:11] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[Jan 09 14:22:11] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
[Jan 09 14:22:11] [debug]: loadNoteDirectoryList
[Jan 09 14:22:11] [debug]: reloadTagTree
[Jan 09 14:22:11] [debug]: reloadTagTree  - 'noteSubFolderIds':  ()
[Jan 09 14:22:11] [debug]: filterNotesByTag  - 'tags':  (Tag: <id>5 <name>"Reunion" <parentId>0 ) 
[Jan 09 14:22:11] [debug]: filterNotesByTag  - 'fileNameList':  ("Réunion générale 31 janvier")
[Jan 09 14:22:11] [debug]: filterNotesByTag  - 'tags':  (Tag: <id>5 <name>"Reunion" <parentId>0 ) 
[Jan 09 14:22:11] [debug]: filterNotesByTag  - 'fileNameList':  ("Réunion générale 31 janvier")
[Jan 09 14:22:11] [debug]: reloadNoteSubFolderTree
[Jan 09 14:22:11] [debug]: reloadTagTree
[Jan 09 14:22:11] [debug]: reloadTagTree  - 'noteSubFolderIds':  (0)
[Jan 09 14:22:11] [debug]: loadNoteDirectoryList
[Jan 09 14:22:11] [debug]: reloadTagTree
[Jan 09 14:22:11] [debug]: reloadTagTree  - 'noteSubFolderIds':  (0)
[Jan 09 14:22:11] [debug]: filterNotesByTag  - 'tags':  (Tag: <id>5 <name>"Reunion" <parentId>0 ) 
[Jan 09 14:22:11] [debug]: filterNotesByTag  - 'fileNameList':  ("Réunion générale 31 janvier")
[Jan 09 14:22:11] [debug]: filterNotesByTag  - 'tags':  (Tag: <id>5 <name>"Reunion" <parentId>0 ) 
[Jan 09 14:22:11] [debug]: filterNotesByTag  - 'fileNameList':  ("Réunion générale 31 janvier")
[Jan 09 14:22:11] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
[Jan 09 14:22:11] [debug]: filterNotesByTag  - 'tags':  (Tag: <id>5 <name>"Reunion" <parentId>0 ) 
[Jan 09 14:22:11] [debug]: filterNotesByTag  - 'fileNameList':  ("Réunion générale 31 janvier")
[Jan 09 14:22:11] [debug]: reloadTagTree
[Jan 09 14:22:11] [debug]: reloadTagTree  - 'noteSubFolderIds':  ()
[Jan 09 14:22:11] [debug]: Set proxy configuration to use NO proxy
</details>

#### Relevant log output in the Log panel

(Empty)

#### Bash Output (start the app via "flatpak run org.qownnotes.QOwnNotes") 

<details><summary>Expand</summary>
Gtk-Message: 14:14:40.426: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:14:40.426: Failed to load module "canberra-gtk-module"
Warning: Qt: Session management error: None of the authentication protocols specified are supported ((null):0, (null))
Info: "QOwnNotes server listening on port 22222" ((null):0, (null))
Warning: Missing trigrams for languages: QSet("en_PH", "en_BZ", "en_ZW", "en_BS", "en_NA", "en_CA", "en_MW", "en_NZ", "en_JM", "en_TT", "en_GH", "en_AU", "en_ZA", "en_IE", "en_IN") ((null):0, (null))
</details>

**Comment by pbek** [comment]
Thank you for reporting.

@stobbsm created the flatpak on https://github.com/flathub/org.qownnotes.QOwnNotes, maybe he can reproduce the issue and knows something about it

**Comment by pbek** [comment]
Maybe you want to post an issue directly on https://github.com/flathub/org.qownnotes.QOwnNotes.

**Comment by pbek** [comment]
I will close this issue until there is more information.
