### ISSUE TITLE
Whole app freezes when pasting (asterisks in text) markdown from clipboard :(

### ISSUE THREAD

**Issue by dodancs** [pbek/QOwnNotes#1561]
#### Expected behaviour
Open app, add new note, press tick-mark sign (\`) 3 times to create a markdown code block, insert text from clippboard, everything works and the text is properly formatted.

#### Actual behaviour
After pasting a text like this:
```
.vs
Debug
x64/Debug
*/*.vcxproj.filters
*/*.vcxproj.user
*/*/*.vcxproj.filters
*/*/*.vcxproj.user
```

The app compeltely freezes.
![QOwnNotes freeze](https://i.imgur.com/SpbQ1nH.png)

#### Steps to reproduce
I found out, that the issue happens when you have the markdown code block, and you want to write `*/**`, it instantly breaks.

Alternatively, try pasting the above mentioned code into a markdown code block.

All settings are default - I only set my language to English and set-up a nextcloud connection.

This means that there is an issue with the markdown processing and maybe it tries to format text inside of a code block? Since an asterisk (\*) means italic text? Not sure.

#### Output from the debug section in the settings dialog

There is no log output (enabled + debug -> nothing relevant appears in the log file

#### Relevant log output in the Log panel

There is no log output (enabled + debug -> nothing relevant appears in the log file)

**Comment by pbek** [comment]
Confirmed, thank you for reporting.

@Waqar144, another code block regression.

**Comment by Waqar144** [comment]
A quick fix for this would be to use ` ```sh `, meanwhile I will disable comments highlighting in no language code block.

**Comment by pbek** [comment]
## 20.1.6
- fixed multiple multiline comments in same code block causing freezes (for [#1561](https://github.com/pbek/QOwnNotes/issues/1561), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
