### ISSUE TITLE
MD4C preview integration

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1567]
We want to integrate the markdown to html library <https://github.com/mity/md4c> instead of hoedown for the preview.

#1563 was the first step

## Still missing

- [ ] Underline rendering

**Comment by pbek** [comment]
@Waqar144 our new base for discussion

**Comment by pbek** [comment]
@Waqar144, do you see anything (beside underline rendering) that prevents us from "going live" with MD4C?

**Comment by Waqar144** [comment]
Not really.

I think we are good to go. The feature request for underlining is here: https://github.com/mity/md4c/issues/101

There are problems with it in hoedown. Consider the word `foo_bar_baz`, bar will be underlined and things might look weird.

**Comment by pbek** [comment]
## 20.1.6
- the markdown to html library [MD4C](https://github.com/mity/md4c) was integrated
  to be used in the preview instead of hoedown (for [#1567](https://github.com/pbek/QOwnNotes/issues/1567), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
Underline works great!
