### ISSUE TITLE
Line Break with copy -> paste text from a bulleted list

### ISSUE THREAD

**Issue by Primokorn** [pbek/QOwnNotes#1568]
QOwnNotes 20.1.5

Hello,
At first, I only noticed this issue when using a bulleted list.

Code:
````
 * Highlight `THIS` and paste it into Word for example.
````

You will get a line break before getting the text.

**Comment by pbek** [comment]
Can you please explain in more detail and step by step what you did, what happened and what you expected.

**Comment by Primokorn** [comment]
1. Open a note and enter the above code
2. Copy the text "THIS"
3. Paste into Word

A line break is added before the texte and we shouldn't have it. Only "THIS" should be copied with no line break.

**Comment by pbek** [comment]
I cannot reproduce this on KDE Neon. There is no line break for me, just `THIS` is inserted.

**Comment by Primokorn** [comment]
Where do you copy `THIS`? In Libreoffice Writer?
Do you write the text into a bulleted list?
Could you try with a Windows VM?

**Comment by pbek** [comment]
I simply followed your instructions.

**Comment by Primokorn** [comment]
Then "Could you try with a Windows VM?"

**Comment by pbek** [comment]
I will when I have access to one.

**Comment by Primokorn** [comment]
FWIW here is a [quick video](https://drive.google.com/file/d/1ej35nDh9cdaiUgXiwWW1smUIf7A4g0XM/view?usp=sharing).

**Comment by pbek** [comment]
Now I get what you mean. You didn't tell us that we need to copy the text from the preview. :laughing: 

It seems like the `QTextBrowser` is taking into account that the text stems from a list. If I paste the `THIS` into LibreOffice Writer I get a list item.

**Comment by Primokorn** [comment]
Oh yes you are right sorry :smile:

**Comment by pbek** [comment]
:grin:

**Comment by Primokorn** [comment]
@pbek Why did you close the issue? Did you change something in the code?
Normally a fix is mentioned before closing the issue.
Thanks.

**Comment by pbek** [comment]
I don't know if there is anything to "fix" or in what way you want it to be fixed. It's simple how things are behaving.

- the `QTextBrowser` of the preview treats text copied from list items as list item (html is copied)
- if you paste html in the note text edit the html gets converted to a text representation, in case of a html list item it receives a line break for each list item

so where do you see the "error"? and both would be Qt default behaviors...

**Comment by Primokorn** [comment]
Gotcha. I though something could be done for QOwnNotes :disappointed_relieved:

**Comment by pbek** [comment]
I'm sorry :grimacing:

**Comment by Primokorn** [comment]
@pbek 
Same information as #1619 
I tested with another note taking software which supports markdown and I do not have this issue.

**Comment by pbek** [comment]
Can you propose a fix? (I'm also open for pull requests.)

**Comment by Primokorn** [comment]
Well I'm not a developer...

**Comment by Waqar144** [comment]
Maybe We can somehow override the copying of text from there and fix the problematic part. It would fix this problem but it will likely introduce many others.

Ideally this should be looked at/fixed in the Qt code.

**Comment by Primokorn** [comment]
@pbek 
Another editor where I don't have this issue: https://github.com/tamlok/vnote.
 Can it help?

**Comment by pbek** [comment]
Seems like they are using a QTextEdit (which we are not). https://github.com/tamlok/vnote/blob/master/src/vedit.h

Hard to tell what the difference in their implementation is. If you find something out please let me know...

**Comment by Waqar144** [comment]
> Seems like they are using a QTextEdit (which we are not). https://github.com/tamlok/vnote/blob/master/src/vedit.h

[QWebEngineView](https://github.com/tamlok/vnote/blob/073431cb20850e09b3453eb14e46153e676e4655/src/vwebview.cpp) as well.
@Primokorn it depends where you copy the text from. If it was from the webView, thats a totally different thing. If it was from the editor then its weird because QTextBrowser == QTextEdit

> Hard to tell what the difference in their implementation is. If you find something out please let me know...

**Comment by Primokorn** [comment]
@Waqar144 The copy is done from the Webview.

**Comment by Waqar144** [comment]
I will see if we can change this behaviour somehow
