### ISSUE TITLE
Markdown highlight issue for numbered list

### ISSUE THREAD

**Issue by ivanpirog** [pbek/QOwnNotes#1573]
![qon - markdown highlight](https://user-images.githubusercontent.com/8699212/72217535-efbf8180-3537-11ea-82c4-f02be4e5d3e3.png)

#### Expected behaviour

Standard color for item number 3.

#### Actual behaviour

Invalid color for the third item.

**Comment by pbek** [comment]
Thank you for reporting.

@Waqar144 have you seen that before? It seems the other list items aren't highlighted any more.

**Comment by ivanpirog** [comment]
> It seems the other list items aren't highlighted any more.

Just numbered list. '*' and '-' and '+' lists signs highlighted as expected.

> Invalid color for the third item.

So, correct issue is "Invalid color for the first and second items" :-)

**Comment by pbek** [comment]
> So, correct issue is "Invalid color for the first and second items" :-)

Exactly :grin: 

@Waqar144 added a speed improvement that seems to have ruled out ordered list items :grin:  The 3rd item got it right because of the `+` (unordered list marker).

**Comment by pbek** [comment]
## 20.1.7
- fixed highlighting of ordered lists

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by ivanpirog** [comment]
Yeah. Ordered lists looks nice now.

**Comment by pbek** [comment]
Great, thank you for testing!
