### ISSUE TITLE
Folder contents are not updated when two instances of the application are running

### ISSUE THREAD

**Issue by ivanpirog** [pbek/QOwnNotes#1574]
I launched two instances of the application. In the first instance, I created a note in a folder. In the second instance, I don't see this note, even when I change the folder.

#### Expected behaviour

Track changes in folders to detect adding or removing notes. When changing folders, update the contents.

#### Actual behaviour

The list of notes in the folder doesn't change when you create or delete a new note from another application.

**Comment by pbek** [comment]
I don't know about the platform or settings (you didn't post any of that). Have you turned off the detection for changes in the *General settings*? Are you using two different sessions of QOwnNotes (`--session` parameter)?

**Comment by ivanpirog** [comment]
**Platform**: Win10.

> Have you turned off the detection for changes in the General settings?

![QOwnNotes_6AtQCGcDku](https://user-images.githubusercontent.com/8699212/72218628-99593f80-3545-11ea-8d4f-0d47c1ccd564.png)


> Are you using two different sessions of QOwnNotes (--session parameter)?

I don't know. I just uncheck the "Only allow one app instance at the same time" option and run QON twice without any command line parameters.

**Comment by pbek** [comment]
I guess your operating system doesn't send events for file system changes.

You are able to see them in the log widget (you didn't send any dump).

**Comment by ivanpirog** [comment]
Hmmm... Very strange! Today QON works as expected... I create note in folder and app see changes.

**Comment by ivanpirog** [comment]
> I guess your operating system doesn't send events for file system changes.

It seems like that.

**Comment by pbek** [comment]
> I don't know. I just uncheck the "Only allow one app instance at the same time" option and run QON twice without any command line parameters.

keep in mind that both instances are using the same settings pool, it's not very safe to use QON that way :grin:

**Comment by ivanpirog** [comment]
> keep in mind that both instances are using the same settings pool

It's ok for me :-)

**Comment by pbek** [comment]
> It seems like that.

you can always use `Ctrl + Shift + R` to reload the note folder

**Comment by pbek** [comment]
> It's ok for me :-)

then it's ok :)
may I ask why you are using two instances? I'm curious...

**Comment by ivanpirog** [comment]
> you can always use `Ctrl + Shift + R` to reload the note folder

I propose to add the "Reload folder" item to the folder context menu (I searched for it there).

**Comment by pbek** [comment]
> I propose to add the "Reload folder" item to the folder context menu (I searched for it there).

Hm, currently it's in the `Note` main menu.

**Comment by pbek** [comment]
Many people (like me) aren't using note sub-folders...

**Comment by pbek** [comment]
And you can also search for such actions in the `Help` menu.

**Comment by ivanpirog** [comment]
> Hm, currently it's in the Note main menu.

Yes, now I know about it. For me it's more intuitive to right-click on a folder and click on the "update" item in the context menu. I think it's better to duplicate that item for more convenient and intuitive use.

> And you can also search for such actions in the Help menu.

Nice. Thanks I'll know!

> Many people (like me) aren't using note sub-folders...

I have a separate folder for each project, a separate folder for the diary, and a separate folder with instructions and algorithms for generating ideas.

It is very comfortable. I can’t imagine what would happen if I stored all this in one folder. That would be chaos %)

> may I ask why you are using two instances? I'm curious...

The situation is like this. In one folder I store notes with instructions for generating ideas. In another note, I generate ideas for a project. I need to look periodically at notes from the instructions folder. It’s more convenient for me to press Alt + Tab than go to the instructions folder, look at the note, then go back to the working folder and select the working note there.

**Comment by ivanpirog** [comment]
BTW, I often work with several notes at once. Sometimes they are in the same folder, sometimes in different ones. It’s most convenient to press Alt + Tab than switch between notes.

**Comment by pbek** [comment]
> For me it's more intuitive to right-click on a folder and click on the "update" item in the context menu. 

The reload is for the whole note folder, not for individual sub-folders.

> It is very comfortable. I can’t imagine what would happen if I stored all this in one folder. That would be chaos %)

I use tags, but of course they are less portable.

> BTW, I often work with several notes at once. Sometimes they are in the same folder, sometimes in different ones. It’s most convenient to press Alt + Tab than switch between notes.

Yes, QON has no multi document interface (MDI).
Since all my notes are in one folder I see the most currently updated ones on the top and switch between the last notes... Plus I can use the bookmark feature to jump between notes. Or I can use the the note history...

**Comment by pbek** [comment]
> The reload is for the whole note folder, not for individual sub-folders.

But of course I can add a menu item to that context menu in any case.

**Comment by pbek** [comment]
## 20.1.7
- added the main menu entry `Reload note folder` also to the context menu in the
  note sub-folder panel

**Comment by ivanpirog** [comment]
> But of course I can add a menu item to that context menu in any case.

This is a good option.

When I needed to update folder contents, the first thought was to search in the folder context menu. Then I pressed F5 with no result. Then I pressed Ctrl+R.

Finally, I searched in the main menu, but I didn't look in the Note menu, because I was sure that there were no actions related to the folder :-)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by ivanpirog** [comment]
Works fine!

**Comment by pbek** [comment]
Great, thank you for testing! :grin:
