### ISSUE TITLE
Unexpected clode block highlighting in editor

### ISSUE THREAD

**Issue by msbentley** [pbek/QOwnNotes#1577]
#### Expected behaviour

Editor highlighting for code blocks only applies to explicit code blocks. 

#### Actual behaviour

The below case seems to highlight additional content, only in the editor

#### Steps to reproduce

See the attached markdown file and screenshot.

![image](https://user-images.githubusercontent.com/1671065/72243021-0ffc4880-35eb-11ea-81bc-372b7002a0b7.png)

[This is a test note.zip](https://github.com/pbek/QOwnNotes/files/4052700/This.is.a.test.note.zip)

**Comment by pbek** [comment]
I think I can't follow you. :grin: 

Can you please explain in more detail and step by step what you did, what happened and what you expected.

**Comment by msbentley** [comment]
haha, sorry - in the above note, I didn't understand why the text in the editor is highlighted as a code block (yellow background in the screenshot) - it may well be user error, though ;-)

**Comment by pbek** [comment]
> I didn't understand why the text in the editor is highlighted as a code block

It's a markdown code block: https://daringfireball.net/projects/markdown/syntax#precode

**Comment by msbentley** [comment]
Ahhhhhh, so indeed user error - thanks for pointing me in the right direction!

**Comment by pbek** [comment]
:grin:
