### ISSUE TITLE
copy code block menu-item greyed out

### ISSUE THREAD

**Issue by Gregory-K** [pbek/QOwnNotes#1578]
#### Expected behaviour

The `right click / context menu` inside a code block should offer a `menu-item` with the title `Copy code block` to copy the whole code block.

#### Actual behaviour

The described above menu-item is not working (greyed out) when a "language" suffix (info string) is describing the code block. e.g.

```
'''python
print('Hello world!')
'''
```

#### Steps to reproduce

screen recording (telegram messenger)  
https://t.me/QOwnNotes/3008

---

Related Issue: #1077

**Comment by pbek** [comment]
Thank you, will be fixed in the next release.

**Comment by pbek** [comment]
## 20.1.8
- enable `Copy code block` menu entry for code blocks with language suffix (for [#1578](https://github.com/pbek/QOwnNotes/issues/1578), thank you @Waqar144)

There now is a new release, could you please test it and report if it works for you?

**Comment by Gregory-K** [comment]
OK, the `copy code block` feature is working again

**Comment by pbek** [comment]
Great, thank you for testing!
