### ISSUE TITLE
Fix or get rid of stupid "Please update" message

### ISSUE THREAD

**Issue by zapalotta** [pbek/QOwnNotes#158]
The "please update" message is broken. I update QOwnNote with apt-get within my system. Every few days, sometimes a few times a day, the message pops up.
"Skip Version" won't help, it will pop up a few hours later again.

Please fix or get rid of the message. Thanks.

**Comment by pbek** [comment]
Thank you for your report, are you sure there was no new version, that popped up? *Skip version* skips the current version. If there is a new update you will get a new notification. You can turn off those notifications in the General settings.

**Comment by zapalotta** [comment]
Sometimes the Dialog pops up ten times a day (happened already about ten versions ago) and I click "skip", I don't compare the minor-minor versions, but if you don't release ten versions on some days, it pops up again.
I already disabled the "Show update dialogue" Setting a while ago, it keeps popping up, last time this morning ...

**Comment by pbek** [comment]
Are you sure there is no 2nd instance of QOwnNotes running?

**Comment by pbek** [comment]
I just checked the functionality. Skipping and disabling are working as intended in 16.05.01 on Ubuntu 16:04.

**Comment by zapalotta** [comment]
I have the notification icon running but no instance of QOwnNote. I will take notes what happens. Thanks.

**Comment by pbek** [comment]
What notification icon? What does `ps fax | grep QOwnNotes` report?

**Comment by zapalotta** [comment]
Hi,

sorry, I didn't have time time to reply before.

I watched it for a while now. Since 6:30 in the morning (it is 12:24
now) the "Update available"-Dialog popped up about 6 times.

Please see the screenshots of my settings and the notification icon.

ps faux only shows one running instance of qownnotes...

Best,
Dirk

**Comment by pbek** [comment]
The screenshots didn't get through...
Ubuntu Launchpad had some problems on the amd64 and i386 architectures. They needed until recently to build software on that architectures. You should not have this problem any more.
