### ISSUE TITLE
[I] The '<' and '>' characters not visible when used in code block

### ISSUE THREAD

**Issue by gwojcieszczuk** [pbek/QOwnNotes#1580]
Please paste the text from the issue assistant here. It should be already in your clipboard.#### Expected behaviour

When I'm using <> characters in code block, they should be displayed literally.
Example:

```
~~~
command [option] <arg> 
~~~
```

or

~~~
```
command [option] <arg>
```
~~~

#### Actual behaviour

Entire `<arg>` string is not visible in rendered view.

#### Steps to reproduce

Use the markdown code mentioned in "expected behavior"

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[09:47:01]
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Jan 14 09:51:40 2020`
**Version**: `20.1.8`
**Build date**: `Jan 13 2020`
**Build number**: `5213`
**Platform**: `linux`
**Operating System**: `Ubuntu 18.04.3 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.6.2`
**Qt Version (runtime)**: `5.9.5`
**Portable mode**: `no`
**Settings path / key**: `/home/gwojcieszczuk/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/gwojcieszczuk/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/opt/QOwnNotes/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_IE`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1600x900`
**Icon theme**: `ubuntu-mono-dark`
**Notes in current note folder**: `17`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Spellchecking

**Enabled**: `false`
**Selected language**: `en_US`
**Language codes**: `en_US`
**Language names**: `American English (United States)`
**Application dictionaries path**: `/home/gwojcieszczuk/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/gwojcieszczuk/Nextcloud2/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `bingo`
**database file**: `/home/gwojcieszczuk/Nextcloud2/Notes/notes.sqlite`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `false`
**Editor/autoBracketRemoval** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**EvernoteImport/AttachmentImportCheckBoxChecked** (QString): `true`
**EvernoteImport/ImageImportCheckBoxChecked** (QString): `true`
**EvernoteImport/MetaDataUnCheckedList** (QStringList): `, `
**EvernoteImportDialog/geometry** (QByteArray): `<binary data>`
**FileDialog/LastPath** (QString): `/home/gwojcieszczuk/Pictures`
**FileDialog/LastPath-ImportTextFiles** (QString): `/home/gwojcieszczuk/Downloads/Linux Performance Tuning/TUNED`
**FileDialog/LastPath-InsertImage** (QString): `/home/gwojcieszczuk/Nextcloud2/Notes/media`
**FileDialog/LastPath-NoteMarkdownExport** (QString): `/home/gwojcieszczuk/Pictures`
**FileDialog/LastPath-NotePDFExport** (QString): `/home/gwojcieszczuk/Downloads`
**ImageDialog/disableCopying** (bool): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-01-14T09:32:46`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Linux Lab Guides, Linux Instructor Guides`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `false`
**MainWindow/noteTextView.useEditorStyles** (QString): `false`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/readonly-mode-allow** (QString): `65536`
**MessageBoxOverride/share-sync-information** (QString): `1024`
**NoteHistory-1** (QVariantList): `<variant list with 25 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `24`
**OrphanedAttachmentsDialog/geometry** (QByteArray): `<binary data>`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExport** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**VersionDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `true`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `false`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `true`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `19`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `5`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/gwojcieszczuk/Nextcloud2/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList** (QString): `Personal`
**ownCloud/todoCalendarEnabledList** (QString): `Personal`

**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `17.0.2.1`
**recentNoteFolders** (QString): `/home/gwojcieszczuk/Nextcloud/Notes`
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2020-01-14T09.42.39, Note 2020-01-13T17.35.50, Note 2020-01-13T17.11.21, Note 2020-01-13T17.07.16, Note 2020-01-13T16.09.53, Note 2020-01-13T13.55.27, 1, 2, 3, 4, 5, 6, 7, Note 2020-01-07T21.39.33, Note 2020-01-07T12.22.04, Note 2020-01-07T11.36.43`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**skipVersion** (QString): `20.1.7`
**spellCheckLanguage** (QString): `en_US`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useUNIXNewline** (QString): `false`
**versionSplitterSizes** (QByteArray): `<binary data>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**USER**: `gwojcieszczuk`
**LANGUAGE**: `en_IE:en`
**TEXTDOMAIN**: `im-config`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `8095`
**SHLVL**: `0`
**QT4_IM_MODULE**: `xim`
**HOME**: `/home/gwojcieszczuk`
**DESKTOP_SESSION**: `ubuntu`
**GTK_MODULES**: `gail:atk-bridge`
**GNOME_SHELL_SESSION_MODE**: `ubuntu`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**LIBVIRT_DEFAULT_URI**: `qemu:///system`
**MANDATORY_PATH**: `/usr/share/gconf/ubuntu.mandatory.path`
**IM_CONFIG_PHASE**: `2`
**LOGNAME**: `gwojcieszczuk`
**GTK_IM_MODULE**: `ibus`
**DEFAULTS_PATH**: `/usr/share/gconf/ubuntu.default.path`
**USERNAME**: `gwojcieszczuk`
**XDG_SESSION_ID**: `2`
**WINDOWPATH**: `2`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
**S_COLORS**: `auto`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**DISPLAY**: `:1`
**LANG**: `en_IE.UTF-8`
**XDG_CURRENT_DESKTOP**: `ubuntu:GNOME`
**XDG_SESSION_DESKTOP**: `ubuntu`
**XMODIFIERS**: `@im=ibus`
**XAUTHORITY**: `/run/user/1000/gdm/Xauthority`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**SHELL**: `/bin/bash`
**QT_ACCESSIBILITY**: `1`
**GDMSESSION**: `ubuntu`
**TEXTDOMAINDIR**: `/usr/share/locale/`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**XDG_VTNR**: `2`
**QT_IM_MODULE**: `ibus`
**PWD**: `/home/gwojcieszczuk`
**CLUTTER_IM_MODULE**: `xim`
**XDG_DATA_DIRS**: `/usr/share/ubuntu:/home/gwojcieszczuk/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-ubuntu:/etc/xdg`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**XDG_MENU_PREFIX**: `gnome-`
**SESSION_MANAGER**: `local/t430:@/tmp/.ICE-unix/7998,unix/t430:/tmp/.ICE-unix/7998`
**GIO_LAUNCHED_DESKTOP_FILE**: `/usr/share/applications/QOwnNotes.desktop`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `31682`
**GJS_DEBUG_OUTPUT**: `stderr`
**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`
</details>

**Comment by Waqar144** [comment]
Cannot reproduce it. Can you explain a little more? What are the exact steps you did to encounter this issue? Are you specifying a language with the codeblock?

Currently I can't reproduce it with `inline code`/`Code Fence`/`Indented Code block`

**Comment by pbek** [comment]
I cannot reproduce that neither.

**Comment by gwojcieszczuk** [comment]
I tested it again, and it seems like when using ``` quotes is working now. But, the ~~~ still don't work. Attaching screenshot.
![Screenshot from 2020-01-14 12-25-12](https://user-images.githubusercontent.com/6558849/72344450-27a9fe80-36c9-11ea-985d-db2f86ad4fe7.png)

**Comment by pbek** [comment]
`~~~` are not supported as code block fence. In what markdown syntax do they exist?

**Comment by Waqar144** [comment]
Yeah we don't support `~~~` yet.

@pbek they are in CommonMark, and also work in github (though github is using commonmark)

**Comment by gwojcieszczuk** [comment]
https://www.markdownguide.org/extended-syntax/
Search for "Fenced Code Blocks". It mentions that both ``` and ~~~ are valid.

**Comment by gwojcieszczuk** [comment]
> Yeah we don't support `~~~` yet.
> 
> @pbek they are in CommonMark, and also work in github (though github is using commonmark)

But it seems that ~~~ work in qownnotes perfectly.

**Comment by pbek** [comment]
Haven't seem them in the wild yet. @Waqar144 do we have any plans supporting them?
Surely would be a great deal of work and a source for a lot of regressions. When they are used together. :grin: 

```
~~~
```

~~~
```
~~~

**Comment by pbek** [comment]
> But it seems that ~~~ work in qownnotes perfectly.

there is no highlighting

**Comment by gwojcieszczuk** [comment]
> Haven't seem them in the wild yet. @Waqar144 do we have any plans supporting them?
> Surely would be a great deal of work and a source for a lot of regressions. When they are used together. grin
> 
> ```
> ~~~
> ```
> 
> ```
> ```
> ```

I only want to use ```, but as I pointed, some characters like < > and / are not properly displayed in rendered view. Have a look at another example:

![Screenshot from 2020-01-14 12-31-54](https://user-images.githubusercontent.com/6558849/72345082-bbc89580-36ca-11ea-872b-40b62082a019.png)

**Comment by pbek** [comment]
I guess our new markdown to html converter MD4C does support it (because it supports common mark). But "tags" like your `<arg>` get interpreted.

![image](https://user-images.githubusercontent.com/1798101/72345491-3518b600-36d4-11ea-9f39-95718b043d60.png)

**Comment by Waqar144** [comment]
> Haven't seem them in the wild yet. @Waqar144 do we have any plans supporting them?
> Surely would be a great deal of work and a source for a lot of regressions. When they are used together. grin
> 
> ```
> ~~~
> ```
> 
> ```
> ```
> ```

It's easy to detect the code block and highlight in the editor. (at first glance) Problem is that if a codeBlock starts with tildes, it needs to end with the tildes. So that would mean that we need extra flags in the Highlighter. That's probably the easy part.

Hard part is when you do the highlighting in the preview. It's basically one long string, and I look for all the backticks and run a loop to highlight them. But when you have two types of code fences, i have to look for both, and then look for code block ends with matching characters. Looking for errors/mismatches would be very difficult (unless we build some sort of AST or a proper parser, just for extracting the code blocks!)

I am pretty sure what i wrote above wouldnt make sense to a lot of people :rofl:

**Comment by gwojcieszczuk** [comment]
> I guess our new markdown to html converter MD4C does support it (because it supports common mark). But "tags" like your `<arg>` get interpreted.

I'm sometimes using Joplin and Typora MD editors, and they properly handle those characters in preview. I'm now switching to qownnotes, as I see it as much better solution. It would be good if you guys preserve this compatibility with other MD editors.

**Comment by pbek** [comment]
> Hard part is when you do the highlighting in the preview. It's basically one long string, and I look for all the backticks and run a loop to highlight them. But when you have two types of code fences, i have to look for both, and then look for code block ends with matching characters. Looking for errors/mismatches would be very difficult (unless we build some sort of AST or a proper parser, just for extracting the code blocks!)

That's exactly the problem. When the fences are cascaded. :grin:
Would be interesting to write an AST for it. :laughing: (and a lot of work to implement)

**Comment by Waqar144** [comment]
> I only want to use ```, but as I pointed, some characters like < > and / are not properly displayed in rendered view. Have a look at another example:

Thats a bug indeed. I will fix it later.

**Comment by Waqar144** [comment]
> > I guess our new markdown to html converter MD4C does support it (because it supports common mark). But "tags" like your `<arg>` get interpreted.
> 
> I'm sometimes using Joplin and Typora MD editors, and they properly handle those characters in preview. I'm now switching to qownnotes, as I see it as much better solution. It would be good if you guys preserve this compatibility with other MD editors.

I don't know about Joplin much, but Typora is an electron based app and hence has the ease of having everything available in 5 lines of code (too many libraries, and ready made stuff). QOwnNotes is pure Qt/C++ desktop software. We have to do it all by hand(even the highlighting). While we can do what they do to some extent it creates a lot of problems when you are supporting multiple 
arches+OSes.

I will look into this, 
There will be a way to get them both running.

However, it wouldnt matter whether you use backticks or tildes, at the end of the day, the underlying parser/highlighter is going to be the same for both, hence they will have the same bugs.

**Comment by pbek** [comment]
Joplin is also an Electron app. 😁

**Comment by gwojcieszczuk** [comment]
> Joplin is also an Electron app. grin

Yeah, I know :) C/C++ developers making fun of evil javascript :) javascript is bloat, agreed !!!

**Comment by Waqar144** [comment]
> > Joplin is also an Electron app. grin
> 
> Yeah, I know :) C/C++ developers making fun of evil javascript :) javascript is bloat, agreed !!!

Wouldn't say that exactly, though life in JS can be easier sometimes :smile: you just can't beat the lightness and speed of the desktop apps(yet). You'd be surprised to know the @pbek is an expert web dev too :wink: 

And while we are talking about web, be sure to check out the web browser extensions for QON(might come in handy)

**Comment by pbek** [comment]
> And while we are talking about web, be sure to check out the web browser extensions for QON(might come in handy)

I can't live without my bookmarks in markdown files! :laughing:

**Comment by pbek** [comment]
## 20.1.9
- added support for tilde code fence highlighting (for [#1580](https://github.com/pbek/QOwnNotes/issues/1580), thank you @Waqar144)
    - the preview also works correctly now
    - you can also fence triple-tick code blocks with tilde-fences and vice versa

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by gwojcieszczuk** [comment]
> There now is a new release, could you please test it and report if it works for you?

Just tested. All working fine. Using special characters (<>/) within code block  (~~~ and ```) is properly rendered in the preview.

One thing: when I first openend version 20.1.9 of Qownnotes I noticed that rendered preview of problematic code was still incorrect. Only when I started editing that note, note's preview got fixed. To test it further, I created simple MD note outside of Qownnotes containing problem combination of characters. After viewing that MD note in new 20.1.9 version, everything was rendered correctly. Are you guys caching rendered note views, or rendering occurs every time i view note?

**Comment by Waqar144** [comment]
Can you share a screen shot?
Rendering occurs every second(if there was a change in the note)

**Comment by gwojcieszczuk** [comment]
> Can you share a screen shot?
> Rendering occurs every second(if there was a change in the note)

Unfortunately, I didn't take a screenshot when it was happening, but I think information you provided may explain symptoms I observed for short period of time.

The reason I asked about this is simply a concern about existing notes. If I don't edit them, and they contain problematic MD code, do I have to manually do some small edit to each affected note in order for the preview rendering to be corrected?

**Comment by Waqar144** [comment]
Yeah, the preview is created every time you load a note /edit it.

But until I reproduce this, I won't be able to fix this. So maybe some example code or something? And in what way was the rendering incorrect?

**Comment by gwojcieszczuk** [comment]
I think, we can close this case. If I encounter such problem in the future, I will report it to you, guys.

Thank you again very much for your hard work.

You're awsome !!!
