### ISSUE TITLE
Feature Request: The ability to make QOwnNotes open with a blank editor panel instead of the previous note

### ISSUE THREAD

**Issue by timunrau** [pbek/QOwnNotes#1588]
#### Expected behaviour
I would like the option to make the Editor panel to be blank when I first launch QOwnNotes instead of showing the previous note that I had open. 

#### Actual behaviour
QOwnNotes will show the previous note that I had open. This can lead to privacy issues when launching QOwnNotes in front of other people. 

#### Steps to reproduce
1. Launch QOwnNotes
2. Watch as your last note with potentially private information is displayed.

**Comment by pbek** [comment]
Thank you for your suggestion.

Meanwhile you can simply write a script that jumps to a certain note when the script engine initializes (e.g. at startup).
See: http://docs.qownnotes.org/en/develop/scripting/README.html#jumping-to-a-note

**Comment by timunrau** [comment]
This could work for my purposes. I will look into that! Thanks!

**Comment by pbek** [comment]
If you have too private information in notes you better want to encrypt it, then you would need to enter the password before you can read the note.

**Comment by pbek** [comment]
## 20.1.10
- it is now possible to disable the opening of the last accessed note at startup
  in the *General settings*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by timunrau** [comment]
It's working as expected. Thank you for implementing this feature!

**Comment by pbek** [comment]
Great, thank you for testing!
