### ISSUE TITLE
Easy Updates

### ISSUE THREAD

**Issue by dgirke** [pbek/QOwnNotes#159]
Hi All,
I really love QOwnNotes. It is the first ever notetaking program which is really useful for me. Thanks a lot for your effort. But there is one thing that is annoying me from time to time: it´s the updates. I don´t care about frequent updates. But when they come so often, the update procedure should be easier, i.e. just click on "install and restart" like some other apps do. This is really the only issue I  can provide. It´s one of the best things I have seen for the last years. Absolutely great job. I will see where I can spend some money to support you.
Btw: I am using the Mac OS version.
Thanks
Detlef

**Comment by pbek** [comment]
Thank you very much for your kind words!
On what platform are you using QOwnNotes?
You could for example support QOwnNotes by working on the German (or any other) translation at <https://crowdin.com/project/qownnotes/invite> (I boldly assumed you are German) 😸

**Comment by dgirke** [comment]
Germany´s correct. It´s Mac OS. Ok, I will try to  give some input for the german translatiion.
Thanks and regards
Detlef

**Comment by pbek** [comment]
Thank you for your help on the translation and sorry I seem to have missed that you are using OS X.
There already is a similar issue: #102 (I'll close this one)
But the case is complicate. Even if there were an autoupdater it could not install the app if it is not signed by Apple and to do that the developer (me) would need to pay Apple 100 EUR each year.
