### ISSUE TITLE
Doesn't respond if Preview enabled

### ISSUE THREAD

**Issue by Primokorn** [pbek/QOwnNotes#1592]
Hello,
Similar issue than #1532 ?

QOwnNotes crashes with **Preview panel ON** while using this code:
````
Étapes | TIERS  | BANQUE écrit.man. | BQ écrit.auto | Charge/Produit | Environnements
:--- | :---: | :---: | :---: | :---: | :---:
**OKTZ (Material Ledger)<br/>[Ex Ticket](http://..../detail/id/513306)** |  |  |  | **Si impact prod (rubrique) - IT et BR** | **OT**
````

QOwnNotes 20.1.9
Windows 7 Pro 64bits

**Comment by pbek** [comment]
It doesn't crash for me, but it freezes.

@Waqar144, an other regression? :grin:

**Comment by Primokorn** [comment]
yes it freezes and I have to force close.

**Comment by Waqar144** [comment]
> It doesn't crash for me, but it freezes.
> 
> @Waqar144, an other regression? grin

Its in MD4C I think, not our side. Probably an infinite loop.
The output from isn't correct as well

CC: @mity

**Comment by mity** [comment]
Ack. Looking at it.

**Comment by Waqar144** [comment]
> Ack. Looking at it.

Seems to me as if it's stuck in `md_process_normal_block_contents()`:
```c
    /* Free any temporary memory blocks stored within some dummy marks. */
    for(i = PTR_CHAIN.head; i >= 0; i = ctx->marks[i].next)
        free(md_mark_get_ptr(ctx, i));
```

**Comment by mity** [comment]
Fixed in MD4C's master. Note I have encountered yet another bug (double free) in some input so you may wait a little while until I fix that too.

**Comment by Waqar144** [comment]
Alright thanks!

**Comment by mity** [comment]
Fixed the other bug too.

(Note both seem to be regressions introduced after the latest release and they would likely be caught during some testing for the next release. You should generally stick to the release tags.)

**Comment by Waqar144** [comment]
Thanks a lot for such swift action. 

I am sure @pbek will take that into account.

**Comment by pbek** [comment]
@Waqar144 are you creating a pull requests or should I pull the library?

**Comment by pbek** [comment]
I will do it. 😁

**Comment by pbek** [comment]
Works like a charm, @mity! Thanks a lot!

**Comment by pbek** [comment]
## 20.1.11
- fixed an infinite loop in the preview with complex markdown tables (for [#1592](https://github.com/pbek/QOwnNotes/issues/1592), thank you @mity)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Primokorn** [comment]
@pbek Updated and I can confirm that it's fixed. Thanks!

**Comment by pbek** [comment]
Great, thank you for testing!
