### ISSUE TITLE
Doesn't show images from directory with spaces

### ISSUE THREAD

**Issue by ptah-alexs** [pbek/QOwnNotes#1595]
edited 18.01.20 19:43 UTC
![screenshot](https://user-images.githubusercontent.com/705210/72669416-df813800-3a4a-11ea-98e7-8a053ca3908d.png)
[log file](https://github.com/pbek/QOwnNotes/files/4081627/20200118182002.-.QOwnNotes.log)

source of note:
```
![](file://media/-qdf9s_vh19u5bxltwg59ye7_2o.png)

![](file://Test test/media/-qdf9s_vh19u5bxltwg59ye7_2o.png)
```
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `сб янв. 18 22:02:31 2020`
**Version**: `20.1.9`
**Build date**: `Jan 15 2020`
**Build number**: `656`
**Platform**: `linux`
**Operating System**: `Debian GNU/Linux bullseye/sid`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.11.3`
**Qt Version (runtime)**: `5.12.5`
**Portable mode**: `no`
**Settings path / key**: `/home/user/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/user/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `ru_RU`
**Locale (interface)**: `ru`
**Primary screen resolution**: `1829x1029`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `759`
**Calendar items**: `0`
**Enabled scripts**: `7`

## Server Info

**serverUrl**: ``
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `ru_RU`
**Language codes**: `ru_RU`
**Language names**: `русский (Россия)`
**Application dictionaries path**: `/home/user/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `по умолчанию`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/user/MyDownloads/notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `Test test`
**database file**: `/home/user/MyDownloads/notes/notes.sqlite`

### Cloud connection `По умолчанию`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://ptah-user.info/owncloud`
**username**: `ptah_user`

### Script `Selected Markdown to BBCode`

**id**: `4`
**path**: `/home/user/.local/share/PBE/QOwnNotes/scripts/selected-markdown-to-bbcode/selected-markdown-to-bbcode.qml`
**variablesJson**: 
```
{
    "pandocPath": "pandoc"
}
```
**identifier**: `selected-markdown-to-bbcode`
**version**: `1.0.3`
**minAppVersion**: `17.05.8`

### Script `Insert Table of Contents (TOC)`

**id**: `7`
**path**: `/home/user/.local/share/PBE/QOwnNotes/scripts/insert-toc/insert-toc.qml`
**variablesJson**: 
```
{
    "tocLinks": true,
    "tocTitle": "Содержание"
}
```
**identifier**: `insert-toc`
**version**: `0.0.3`
**minAppVersion**: `17.06.2`

### Script `Checkbox preview and export`

**id**: `8`
**path**: `/home/user/.local/share/PBE/QOwnNotes/scripts/export-checkboxes/export-checkboxes.qml`
**variablesJson**: *empty*
**identifier**: `export-checkboxes`
**version**: `0.0.3`
**minAppVersion**: `17.12.0`

### Script `Paste Latex Image`

**id**: `11`
**path**: `/home/user/.local/share/PBE/QOwnNotes/scripts/paste-latex-image/paste-latex-image.qml`
**variablesJson**: *empty*
**identifier**: `paste-latex-image`
**version**: `0.0.1`
**minAppVersion**: `17.05.6`

### Script `Export notes as one HTML file`

**id**: `13`
**path**: `/home/user/.local/share/PBE/QOwnNotes/scripts/export-notes-as-one-html/export-notes-as-one-html.qml`
**variablesJson**: *empty*
**identifier**: `export-notes-as-one-html`
**version**: `1.0.0`
**minAppVersion**: `18.03.7`

### Script `External note open`

**id**: `18`
**path**: `/home/user/.local/share/PBE/QOwnNotes/scripts/external-note-open/external-note-open.qml`
**variablesJson**: 
```
{
    "executablePath": "kate"
}
```
**identifier**: `external-note-open`
**version**: `1.0.0`
**minAppVersion**: `18.05.4`

### Script `Un-wrap Text`

**id**: `19`
**path**: `/home/user/.local/share/PBE/QOwnNotes/scripts/unwrap/unwrap.qml`
**variablesJson**: *empty*
**identifier**: `unwrap`
**version**: `1.0.0`
**minAppVersion**: `18.04.3`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `true`
**DistractionFreeMode/editorWidthMode** (QString): `1`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `32`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `/home/user/MyDownloads`
**FileDialog/LastPath-InsertImage** (QString): `/home/user/MyDownloads/notes/Копипасты/media`
**FileDialog/LastPath-NoteHTMLExport** (QString): `/home/user/MyDownloads`
**FileDialog/LastPath-NoteMarkdownExport** (QString): `/home/user/MyDownloads`
**FileDialog/LastPath-NotePDFExport** (QString): `/home/user/MyDownloads`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-01-18T21:59:11.011`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `18`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Копипасты_files, Копипасты, Интересные факты`
**MainWindow/noteTextEdit.code.font** (QString): `Hack,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Hack,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/readonly-mode-allow** (QString): `16384`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteHistory-1** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `199`
**OrphanedAttachmentsDialog/geometry** (QByteArray): `<binary data>`
**OrphanedImagesDialog/geometry** (QByteArray): `<binary data>`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PersistentScripting/MdNT/pandocCommand** (QString): `pandoc`
**PersistentScripting/MdNT/pandocVersion** (QString): `2.2.1`
**PersistentScripting/MdNT/pyCommand** (QString): `python3`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExport** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `defaultcalendar`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**VersionDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `true`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `406f162d-2402-40ea-9ee2-5117a9ba96df`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `800`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): `ru`
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `24`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `false`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `false`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `false`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `0`
**notesPath** (QString): `/home/user/MyDownloads/notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `5f0aa16f-11e6-4c76-8f9b-bffcea8850d4`
**recentNoteFolders** (QStringList): `/home/user/tagspaces, /home/user/ownCloud`
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Как работают двоичные нейронные сети, Iridium: принимаем и декодируем сигналы группировки спутников у себя дома, Гречка или Повесть о народной крупе, Принимаем и декодируем аналоговое ТВ с помощью SDR и Python, Приключения немецкого обедненного гексафторида урана в России, Как работает видеокодек, Inmarsat: принимаем и декодируем сигнал со спутника у себя дома, Note 2019-12-14T20.49.53, Правда о железнодорожных тормозах, Как два байта переслать, Изучаем основы письменности Майя, Климатические катастрофы, Немного о достаточно приметном изменении протестных лозунгов в Гонконге, Apollo Guidance Computer. Часть 2, Apollo Guidance Computer. Часть 1, Таймеры и триггеры CODESYS. Еще один шаг Arduino к классическому ПЛК, Преобразуем изображение в звук, 04. Будущее компьютерных архитектур, 04. будущее компьютерных архитектур, Создание Djvu документов в Linux, Камеры глубины — тихая революция, Изготовление чипа, Проектирование ЦП, Основы архитектуры компьютеров, Как машины предсказывают нам погоду, Вычислительная Фотография, Тюнинг переходных отверстий печатных плат, «Чернобыльская аптечка» беларуского фармацевта, Акихабара, Память на цилиндрических магнитных доменах, Кондиционеры которым 2 тысячи лет, Люди бездны, Япония, Кипр, Православие или… что, Опусы про Его Величество Клей, Делаем простой гидроакустический модем, Адаптивные антенные решётки, Управление HD44780 по линии питания, Метастабильность триггера и межтактовая синхронизация, Мох и мамонты. Часть 2, Мох и мамонты. Часть 1, Note 2019-04-22T19.42.12, Можно ли рендерить реалистичные изображения без чисел с плавающей запятой, Технологии микроэлектроники на пальцах, Скрытное подсоединие к оптоволокну, Note 2019-04-05T19.02.10, Паровые турбины, DCF77. Как работает система передачи сигналов точного времени, Реализация страничной памяти, Галоп пикселя, Как я пишу конспекты по математике на LaTeX в Vim, Пиво насущное, Разбираемся в протоколе консенсуса Stellar, Самодельный гранатомёт PIRA ирландского сопротивления, qownnotes web-companion Browser extension to browse bookmarks and create notes in QOwnNotes, Мифы современной популярной физики Хабр, закладки, Катастрофа бронзового века 2, Пара слов об управляемом термоядерном синтезе, Как отопить комнату одной свечой, Картофель. Часть третья, Картофель. Часть вторая, Как бороться с флотом, не имея флота, Картофель. Часть первая, Картофель. Часть первая, или Трудный путь к нашему столу, Плазменный электролиз позволяет получать аммиак из азота и воды без катализатора, Итальянская Enigma, Да вы задолбали своим информационным обществом, Исландия, Австралия, Переобученные нейросети в дикой природе и у человека, Мангровый лес, Уязвимости в прошивках австралийских животных, Филиппины, Кто такие «седые странники» Австралии, Фаял - место встречи в Атлантике, Остров Пику, пишем трассировщик лучей с нуля за несколько часов, Кирпичная пещера 2019-01-20T16.41.18, Кирпичная пещера, Закат эпохи хабра-банана, Страничная организация памяти, Радио-банан, test, Азоры: последний резерв флоры в середине Атлантического океана, Где и как делают атомные реакторы, Банановая шкурка наносит ответный удар, Инструкция по борьбе с ультрафиолетом, Хурма, Зеленый банан или не забудь покормить микробиоту, Пишем собственную виртуальную машину, Представляем вакуумный транзистор, LibreRouter и другие свободные маршрутизаторы, Два бита на транзистор, Самодельная лазерная установка «Lightsaber», Изучаем азотные лазеры. Лазеры продольного разряда, Изучаем азотные лазеры — часть 2. Лазеры продольного разряда, Легкодоступная левитация в ультразвуке, Премия Дарвина, 1641 год`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `ru_RU`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Главная панель инструментов`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `панель инструментов форматирования`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `панель инструментов вставки`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `панель инструментов шифрования`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `панель инструментов окна`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `Панель инструментов выхода`
**toolbar/size** (QString): `6`
**useUNIXNewline** (QString): `false`
**versionSplitterSizes** (QByteArray): `<binary data>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-406f162d-2402-40ea-9ee2-5117a9ba96df/name** (QString): `минимальный`
**workspace-406f162d-2402-40ea-9ee2-5117a9ba96df/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-406f162d-2402-40ea-9ee2-5117a9ba96df/windowState** (QByteArray): `<binary data>`
**workspace-5f0aa16f-11e6-4c76-8f9b-bffcea8850d4/name** (QString): `на весь экран`
**workspace-5f0aa16f-11e6-4c76-8f9b-bffcea8850d4/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-5f0aa16f-11e6-4c76-8f9b-bffcea8850d4/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `5f0aa16f-11e6-4c76-8f9b-bffcea8850d4, 406f162d-2402-40ea-9ee2-5117a9ba96df`

## System environment

**KDE_FULL_SESSION**: `true`
**GS_LIB**: `/home/user/.fonts`
**USER**: `user`
**LANGUAGE**: `ru`
**XDG_SEAT**: `seat0`
**QT_SCREEN_SCALE_FACTORS**: `DisplayPort-0=1.4;HDMI-A-0=1.4;DVI-D-0=1.4;`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `1843`
**SHLVL**: `0`
**XCURSOR_SIZE**: `36`
**HOME**: `/home/user`
**DESKTOP_SESSION**: `/usr/share/xsessions/plasma`
**GTK_MODULES**: `gail:atk-bridge`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**KDE_SESSION_VERSION**: `5`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**LOGNAME**: `user`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_ID**: `3`
**PATH**: `/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/user/bin`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XCURSOR_THEME**: `breeze_cursors`
**DISPLAY**: `:0`
**LANG**: `ru_RU.UTF-8`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_SESSION_DESKTOP**: `KDE`
**XAUTHORITY**: `/home/user/.Xauthority`
**SSH_AUTH_SOCK**: `/tmp/ssh-Xl9Y2sS2trX4/agent.1805`
**SHELL**: `/bin/bash`
**QT_ACCESSIBILITY**: `1`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**XDG_VTNR**: `7`
**PWD**: `/home/user`
**XDG_DATA_DIRS**: `/usr/share:/usr/share:/usr/local/share`
**KDE_SESSION_UID**: `1000`
**SESSION_MANAGER**: `local/user:@/tmp/.ICE-unix/1934,unix/user:/tmp/.ICE-unix/1934`

**Comment by Waqar144** [comment]
Thank you for reporting.

Could you please explain a little more as in, what happened and what were you expecting?

PS: Would you mind adding the screen shot directly in the github? Helps a tiny bit.

**Comment by ptah-alexs** [comment]
In last version images in notes doesn't show if path to image contain spaces e.g. /Test test/, though /Test_test/ is worked.
![20200118181146 - Screenshot_20200118_221055](https://user-images.githubusercontent.com/705210/72669416-df813800-3a4a-11ea-98e7-8a053ca3908d.png)

**Comment by pbek** [comment]
How did you insert the image?
Usually a space should be escaped with `%20`, so instead of `file://Test test/media/-qdf9s_vh19u5bxltwg59ye7_2o.png` it should be `file://Test%20test/media/-qdf9s_vh19u5bxltwg59ye7_2o.png`.

**Comment by pbek** [comment]
I just inserted an image via the image dialog and checked the box not to copy it to the media folder. It inserted an image like `![img](../../Downloads/Qt5Concurent at DuckDuckGo_files/private-searches.svg)` and that worked in the preview.

**Comment by ptah-alexs** [comment]
I'm direct write image links or copy from other programs, but don't use image insert dialog. OK, replace spaces on %20 solves the problem, but spaces worked in previous version.

**Comment by pbek** [comment]
> but spaces worked in previous version.

what version was that?

I any case, URLs need to be url-encoded to be valid. But I would refrain to use absolute file urls for images, since they will only work on your computer and they will break if you move the note or move the image. Better use the QOwnNote's internal media library or use relative paths, like in my example above (then you can also use spaces).

**Comment by ptah-alexs** [comment]
At least it worked about half year ago. I'm always use relative path e.g. "file://media/-qdf9s_vh19u5bxltwg59ye7_2o.png".

**Comment by pbek** [comment]
You are not bound to use file urls any more now, see #266.

**Comment by ptah-alexs** [comment]
OK, I'm understand, going to go replace path in all my 700+ notes. Issue may close.
