### ISSUE TITLE
No icons on ubuntu 14.04

### ISSUE THREAD

**Issue by lukosanthropos** [pbek/QOwnNotes#16]
Hey,
This is most likely a Software Wetware interface issue but I don't have any icons (I am assuming there are editor icons which should be displayed) 

I'm running Xfce4 on Ubuntu 14.04 (x64) and I installed 0.55 using the pre-compiled deb. Any ideas what could be causing this ? 
![ownnote issue](https://cloud.githubusercontent.com/assets/594625/10913305/4206dcea-8245-11e5-8f70-650da9683794.png)

**Comment by pbek** [comment]
Looks like troubles with libqt5svg5, is it installed on your system? Which version of Qt do you have?

**Comment by lukosanthropos** [comment]
I'm running QT5, I don't get any error messages when running QOwnNotes from the terminal, I have just installed libqt5svg5 and the application now works perfectly. Can I suggest that this and the qt networking module (which I did get a command line error about) be marked as dependencies in the deb package, just to prevent this from occurring for other people.

Other than that this is a brilliant application, something I've been looking for since I started using owncloud

**Comment by lukosanthropos** [comment]
Closing as this is now fixed

**Comment by pbek** [comment]
Thank you for your kind words, @lukosanthropos! I "scratched my own itch" with QOwnNotes. ;)

And thank you even more for your report! I now added libqt5svg5 and libqt5network5 to the package control file, the new deb-file will be available soon. I didn't even realize that the two were missing!
