### ISSUE TITLE
can't connect QOwnNotes to my owncloud server

### ISSUE THREAD

**Issue by udo-hase** [pbek/QOwnNotes#160]
Hi,
i tried to connect but qonnotes can not find the owncloud webserver. I can connect via webbrowser and also the Desktop-App can sync with my owncloud-server.
Owncloud-version 8
My Desktop is Ubuntu 16.4
i use ssl and use a self signed certificate. I think, that i have to tell qownnote to accept this self signed certificate like in the webbrowser?? But were??

See the debug info below:
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mi. Mai 4 21:07:41 2016`
**Version**: `16.05.1`
**Build date**: `May  2 2016`
**Build number**: `152`
**Platform**: `linux`
**Operating System**: `Ubuntu 16.04 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version**: `5.5.1`

## Server Info

**serverUrl**: `https://raspi2/owncloud`
**appIsValid**: `no`
**connectionErrorMessage**: `Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten.`

## Settings

**DistractionFreeMode/isEnabled**: `false`
**DistractionFreeMode/mainSplitterSizes**: `<binary data>`
**DistractionFreeMode/menuBarGeometry**: `<binary data>`
**DistractionFreeMode/menuBarHeight**: `0`
**DistractionFreeMode/windowState**: `<binary data>`
**LastUpdateCheck**: `2016-05-04T20:40:45`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `24`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/showRecentNoteFolderInMainArea**: `false`
**MainWindow/windowState**: `<binary data>`
**PiwikClientId**: `<hidden>`
**ShowSystemTray**: `false`
**SortingModeAlphabetically**: `false`
**allowOnlyOneAppInstance**: `true`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `false`
**appMetrics/notificationShown**: `true`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**darkModeColors**: `true`
**defaultNoteFileExtension**: `txt`
**disableAutomaticUpdateDialog**: `false`
**externalEditorPath**: *empty*
**interfaceLanguage**: `de`
**mainSplitterSizes**: `<binary data>`
**markdownViewEnabled**: `true`
**networking/ignoreSSLErrors**: `false`
**networking/proxyType**: `2`
**noteEditPaneEnabled**: `true`
**noteListSplitterState**: `<binary data>`
**noteSaveIntervalTime**: `10`
**notesPath**: `/home/un/ownCloud/Notes`
**notifyAllExternalModifications**: `false`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: `https://raspi2/owncloud`
**ownCloud/todoCalendarBackend**: `0`
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloud/userName**: `un`
**skipVersion**: `16.05.2`
**verticalNoteFrameSplitterState**: `<binary data>`

Any helpare highly welcome.

best regards Uwe

**Comment by pbek** [comment]
Thank you for your report. Please take a deeper look in the network tab of the settings dialog. There you will find that setting. Does it solve your problem?

**Comment by udo-hase** [comment]
great!! many thanks for the hint :-)

**Comment by udo-hase** [comment]
great work!! thanks for the software!!

**Comment by pbek** [comment]
Thank you and great it helped! 😸 
If you want to do something good you can now and then lay your caring eyes on the German translation at <https://crowdin.com/project/qownnotes/invite> That would be of an awesome lot of help! 😃
