### ISSUE TITLE
Feature request: More editor width options or increase current available widths

### ISSUE THREAD

**Issue by nsrosenqvist** [pbek/QOwnNotes#1604]
#### Expected behaviour

The editor width should take into account different dpi settings.

#### Actual behaviour

It does not. What you see in the attached screenshot is the widest available setting.

![editor](https://user-images.githubusercontent.com/1303475/72968996-f2866600-3dc4-11ea-8d58-63a0c8ef3924.png)

#### Steps to reproduce

Open the QOwnNotes application window on a high DPI display and set the editor width to the widest setting.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `tor jan 23 09:41:14 2020`
**Version**: `20.1.12`
**Build date**: `Jan 20 2020`
**Build number**: `5295`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\nikla\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Users\nikla\Apps\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `sv_SE`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `103`
**Calendar items**: `8`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://cloud.nsrosenqvist.com`
**appIsValid**: `no`
**notesPathExists**: `unknown`
**connectionErrorMessage**: `Host cloud.nsrosenqvist.com not found`

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\nikla\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `standard`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `C:\Users\nikla\Nextcloud\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `RV101`
**database file**: `C:\Users\nikla\Nextcloud\Notes\notes.sqlite`

### Cloud connection `Standard`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://cloud.nsrosenqvist.com`
**username**: `niklas`

## Settings

**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/editorWidthMode** (int): `3`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `false`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-01-23T09:05:32.999`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/mainToolBar.iconSize** (int): `27`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `RV101`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 2 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `1`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (int): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Personal`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `false`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (int): `16`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `C:/Users/nikla/Nextcloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Personal, Secondary`
**ownCloud/todoCalendarEnabledList** (QStringList): `Personal, Secondary`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://cloud.nsrosenqvist.com/remote.php/dav/calendars/niklas/personal/, https://cloud.nsrosenqvist.com/remote.php/dav/calendars/niklas/secondary/`
**ownCloud/todoCalendarUrlList** (QStringList): `https://cloud.nsrosenqvist.com/remote.php/dav/calendars/niklas/personal/, https://cloud.nsrosenqvist.com/remote.php/dav/calendars/niklas/secondary/`
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): `Host cloud.nsrosenqvist.com not found`
**ownCloudInfo/notesPathExistsText** (QString): `unknown`
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `TODO, Note 2020-01-22T10.41.36, Note 2020-01-21T13.50.15, Note 2020-01-21T08.25.17`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `false`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `huvudverktygsfältet`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formateringsverktygsfältet`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `infogar verktygsfält`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `krypteringsverktygsfältet`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `verktygsfältet`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `avsluta verktygsfältet`
**toolbar/size** (int): `6`
**useSoftWrapInNoteEditor** (QString): `true`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\nikla\AppData\Roaming`
**CAMLIBS**: `C:\Program Files\darktable\lib\libgphoto2\2.5.21`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `DESKTOP-NNDD7JS`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\nikla`
**IOLIBS**: `C:\Program Files\darktable\lib\libgphoto2_port\0.12.0`
**LOCALAPPDATA**: `C:\Users\nikla\AppData\Local`
**LOGONSERVER**: `\\DESKTOP-NNDD7JS`
**MAGICK_HOME**: `C:\Program Files\darktable\lib\GraphicsMagick-1.3.31\modules-Q8\coders`
**NUMBER_OF_PROCESSORS**: `8`
**OneDrive**: `C:\Users\nikla\OneDrive`
**OneDriveConsumer**: `C:\Users\nikla\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Microsoft\Web Platform Installer\;C:\Users\nikla\AppData\Local\Microsoft\WindowsApps;;C:\Users\nikla\AppData\Local\Programs\Microsoft VS Code\bin`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 142 Stepping 10, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `8e0a`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\nikla\AppData\Local\Temp`
**TMP**: `C:\Users\nikla\AppData\Local\Temp`
**USERDOMAIN**: `DESKTOP-NNDD7JS`
**USERDOMAIN_ROAMINGPROFILE**: `DESKTOP-NNDD7JS`
**USERNAME**: `nikla`
**USERPROFILE**: `C:\Users\nikla`
**VBOX_MSI_INSTALL_PATH**: `C:\Program Files\Oracle\VirtualBox\`
**windir**: `C:\WINDOWS`
**__COMPAT_LAYER**: `DetectorsMessageBoxErrors`
</details>

**Comment by pbek** [comment]
I'm not sure I understand what you are talking about. Can you please explain in more detail and step by step what you did, what happened and what you expected.

**Comment by nsrosenqvist** [comment]
@pbek yes of course. So the editor supports setting a fixed width to the content area (if settings > editor > "only use editor width setting in distraction free mode" is unchecked - not sure what the correct english label is). The options available are (translated from Swedish):

- narrow
- medium
- wide
- full

The screenshot I attached was of the "wide" setting. This is what "narrow" looks like for example:

![narrow](https://user-images.githubusercontent.com/1303475/72976314-a7734f80-3dd2-11ea-8729-a74a461f0f19.png)

The issue I reported is that surely "wide" is meant to be wider than what it currently is (it doesn't even take up half of the available space) and I assumed it was because of CSS rules at High DPI resolutions or something similar (this may not be case). If it does scale as intended then there should surely be some additional options in between "wide" and "full", or that the width increase should be yet increased between each option.

So if it isn't a scaling bug, then I'd propose to make "narrow" equal to the width of what "medium" is currently, "medium" the same as "wide" and make "wide" yet wider.

I guess this feature request is also applicable: https://github.com/pbek/QOwnNotes/issues/1349

**Comment by pbek** [comment]
The width is calculated by amount of characters 60, 80, 100.

**Comment by nsrosenqvist** [comment]
Ok, then I must apologize for my incorrect assumption. Can the widths be increased?

**Comment by pbek** [comment]
Sure, but only in the source code. :laughing:

**Comment by nsrosenqvist** [comment]
@pbek I renamed the issue to reflect that it now is a feature request instead

**Comment by Waqar144** [comment]
1349 already exists for that

**Comment by nsrosenqvist** [comment]
@Waqar144 It's similar but not the same, that one is for a custom width, this one suggests that the currently available widths should be increased. If you prefer resolving this via the possibility of setting a custom width then I'll happily close this issue.

**Comment by pbek** [comment]
## 20.1.16
- you now can set a custom editor width in the `Window / Editor width` menu

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
@ivanpirog, this one is also for you

**Comment by nsrosenqvist** [comment]
@pbek this works great! Thank you!

**Comment by pbek** [comment]
Great, thank you for testing!
