### ISSUE TITLE
Link highlighting of checkboxes (?)

### ISSUE THREAD

**Issue by msbentley** [pbek/QOwnNotes#1606]
This may be another question of user error/misunderstanding, but I noticed recently that when I use the checkbox markdown (either checked or un-checked) the syntax highlighting treats it as a link - is this expected?

![image](https://user-images.githubusercontent.com/1671065/73135456-7d27c900-4042-11ea-9c55-8989913762ff.png)

Thanks!

**Comment by pbek** [comment]
I never used ordered lists together with a checkbox and they aren't officially supported.
I use unordered lists: `- [ ] checkbox`
In the preview the checkboxes technically are links, the can be clicked (the supported ones).

**Comment by msbentley** [comment]
OK, thanks - it looked a bit odd, so I just wanted to check it was expected.

**Comment by pbek** [comment]
Better use `- [ ] checkbox` :grin:
