### ISSUE TITLE
Unable to check checkboxes in latest release

### ISSUE THREAD

**Issue by fqjin** [pbek/QOwnNotes#1607]
Clicking checkboxes (`- [ ]`) in the markdown previewer to check them is no longer working in release `windows-b5324`, but is working in the previous one `windows-b5319`. It's probably a bug in the recent markdown list rewrite.

**Comment by pbek** [comment]
Thank you for reporting. @Waqar144, it stopped working from 20.1.16 to 20.1.17.

**Comment by Waqar144** [comment]
Will be fixed in the next release I guess

**Comment by pbek** [comment]
## 20.1.18
- fixed checking of checkboxes in checkbox lists in the preview
  (for [#1607](https://github.com/pbek/QOwnNotes/issues/1607), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by fqjin** [comment]
Checkboxes now work in 20.1.18. Thank you

**Comment by pbek** [comment]
Great, thank you for testing!
