### ISSUE TITLE
App crashes after adding new sub task to empty task list

### ISSUE THREAD

**Issue by rakekniven** [pbek/QOwnNotes#1609]
#### Expected behaviour
The app should not crash

#### Actual behaviour
App crashes

#### Steps to reproduce
1. Open QOwnNotes
2. Open ToDo list
3. Everything is empty
4. Select right mouse click menu and add sub task
5. Enter name for sub task
6. Press enter
7. App crashes

## General Info

**Current Date**: `Mo Jan 27 17:22:08 2020`
**Version**: `20.1.17`
**Build date**: `Jan 26 2020`
**Build number**: `5324`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `yes`
**Settings path / key**: `C:/Users/xxx/PortableApps/more/QOwnNotes/Data/PBE/QOwnNotes.ini`
**Application database path**: `C:\Users\xxx\PortableApps\more\QOwnNotes\Data\QOwnNotes.sqlite`
**Application arguments**: `C:\Users\xxx\PortableApps\more\QOwnNotes\QOwnNotes.exe`, `--portable`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `92`
**Calendar items**: `1`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://xxx.xxxx.com`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `18.0.0.10`
**appVersion**: *empty*

#### Relevant log output in the Log panel

[Jan 27 17:25:59] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"https://xxx.xxx.com" <username>"xxx" <priority>1
[Jan 27 17:25:59] [debug]: Reply from  "/remote.php/dav/calendars/xxx/xxx/"
[Jan 27 17:25:59] [debug]: Reply from ownCloud calendar todo list page

</details>

**Comment by pbek** [comment]
> Everything is empty

should it have been empty? were there really no items in that calendar?
was a calendar selected in the todo dialog?

it's hard to make out was was happening on your computer with no actual information about your todo list settings (that you truncated from your debug dump and log entries...

**Comment by pbek** [comment]
> Select right mouse click menu and add sub task

ah now I see. thank you for bringing that up. you can get the context menu without any actual selected item, I'll fix that.

**Comment by pbek** [comment]
## 20.1.18
- fixed displaying of context menu in the task list of the todo list dialog
  if no task is present

**Comment by rakekniven** [comment]
Hey, you are fast as always. Just tried the crash on MacOS and it crashed as well.
Thank you.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by rakekniven** [comment]
Works!

**Comment by pbek** [comment]
Great, thank you for reporting and testing!
