### ISSUE TITLE
Choose relative/absolute path for inserted images

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#161]
I really like your app and want to use it with my android phone. 
I store many images in my notes so I can't use plain text editors to view them on phone. I'm trying to use android markdown editors instead, MarkdownX for now. 
When I insert image QOwnNotes stores image and makes a relative link for it which I find very useful. However none of the android markdown editors I've tried are able to parse such links. 
Trying to workaround this issue I've recreated path to phone notes dir on the root of my desktop, so absolute paths for images on the desktop and phone are the same. However I still need to change relative path for every image I insert to absolute by hand. 
I ask to consider making an ability to insert an absolute path for stored inserted images, maybe a mode setting in app options for android users like me. Maybe absolute path without storing would be useful too.

Thanks.

**Comment by pbek** [comment]
Thank you for your kind words and your suggestion. Currently the inserted images are copied to a media folder inside the note folder and are getting a new, generic name. The note preview then loads them from there. There were not meant to be loaded from anywhere else yet and absolute paths wouldn't work across multiple computers if the file structure isn't exactly the same. How you you want to achieve that with your Android device?

**Comment by Maboroshy** [comment]
I do understand it. However to undergo limitations of android apps I've made fie structure of my linux desktop and android phone the same - I've recreated exact path from phone's root on desktop. For now  QOwnNotes on desktop and MarkdownX on phone open images from the very same absolute path.
I understand that it's not a straightforward solution. But it's the way to make your app useful with android counterparts.
Maybe the more straight solution would be to add some special export mode which would change relative path to the absolute with user entering absolute path parameters to adapt it to export target environment. However making it work for 2-side sync would be lot of work. Absolute/relative modes sounds like much less.
Or maybe you should just write an android counterpart for your app. ;) I'd paid for one for sure.

**Comment by pbek** [comment]
Why don't you just setup an ownCloud instance like [here](https://www.digitalocean.com/features/one-click-apps/owncloud/?refcode=a46a4d6212ea) and use <https://f-droid.org/app/org.aykit.MyOwnNotes> on Android to sync the notes?

**Comment by Maboroshy** [comment]
Isn't MyOwnNotes a plain text app? I found nothing about its ability to show inline images so I've gone another way. Maybe I was wrong.

**Comment by pbek** [comment]
To be true, I don't own an Android phone, but MyOwnNotes is the app people are using for accessing their ownCloud Notes on Android. Since ownCloud notes doesn't support images I'll assume MyOwnNotes will not neither.

**Comment by Maboroshy** [comment]
I've found an issue for markdown support on their github and it's "won't fix". It only opens .md-s like plain text. 
So for now I consider my weird way of syncing your app with android phone a most feature rich solution. It would be also trouble free if my feature request would be accepted.

**Comment by pbek** [comment]
Using absolute paths for inserted media files make hardly any sense to me. It would be only useful for your one edge case. Why don't you hone up your software development skills yourself and try to write an Android app? I also started QOwnNotes because I had an itch to scratch. ;)

**Comment by Maboroshy** [comment]
That is due to my development skills are absent. I'm a professional lawyer.
Guess I'll go to MarkdownX github or what do they use for relative link support then. But the chance they'll say about "edgy case" are high. :)
Maybe I'll write some crazy bash script for link changing but making it 2-sided blows my mind. Maybe changing paths by hand is simpler.

**Comment by Maboroshy** [comment]
I found their github dead for half a year. So I'll go for script then. 2-sided isn't needed if I'll keep an exact path. So I'll put it into cron and let it spin.

**Comment by pbek** [comment]
If you are a lawyer you are already understanding difficult pieces of text. :) Code is only slightly different. :)

It makes much more sense to for MarkdownX to support relative links...
I just tested of absolute links would work in the QOwnNotes preview. Yes, they do! You don't need to make your transformation two-way. Making such a script should be one line of code now.

But I still don't think it's a good idea, you would never be able to change your folder structure, user name, operating system or just copy the note to somewhere else or give it to someone...

If you like QOwnNotes and are speaking more languages than English you can help translating QOwnNotes to your language at <https://crowdin.com/project/qownnotes/invite>. :tada:

**Comment by Maboroshy** [comment]
Not 1 line really, because I will make it path aware so it'll put different paths for different notes dir. Two-way would solve the portability issue you are mentioning. It would be like export mode I described in message 3 of this thread. Downside is having a second set of dirs for phone, not a big deal. 

How about a hook to run custom script on note save then. It would made such crazy exports easier. Its a few lines of code really and powerful feature to have. 

For me having my notes on phone worth any hassle. There is almost none file oriented linux-android note app sets and I'm just few steps off having a good one.

Looks like next thing I'm going to ask is getting a tag info to feed the script. :)

PS My preferred localization is very complete so thanks to the guys that were here before me.

**Comment by pbek** [comment]
> How about a hook to run custom script on note save then.

If something changes the current note every few seconds and QOwnNotes would give you a "note was modified externally" message every time you would go crazy.

> Its a few lines of code really and powerful feature to have.

I wish it were only a few lines of code. :)
It#s more like a few hours work to make that happen on every platform and so on...

**Comment by Maboroshy** [comment]
Tried to edit a note with kwrite but got no warning. Checked "notify about all external modifications" but still nothing. Maybe it's dependant on owncloud integration which I don't use.

Don't know much about c++ or programming at all but isn't making a hook is like putting some "and then run a shell command located in this var" line into save sequence? Then you could define this var in a options field or .conf file. 
It would be up to user if it's "bash export.sh", "export.cmd.", "rm -rf" or "format c:". 

I can still use inotify hook but in-app solution would be more elegant. Maybe few hooks here and there will make kind of plugin engine for your app.

**Comment by pbek** [comment]
I also had some inotify troubles under Linux, interestingly there are no troubles under OS X or Windows. I'm not sure yet where these troubles come from...

Yes, a plugin system for QOwnNotes would be very nice. :)

**Comment by pbek** [comment]
I just tested on a Manjaro laptop and had no problems, I guess it depends on how many files are already opened by inotify...

**Comment by pbek** [comment]
@Maboroshy btw. does the file update checker work when you change your note with for example: `echo test >> your-note.md`?

**Comment by Maboroshy** [comment]
It doesn't. That's what I tried to tell in my previous message. 
I opened them externally with kwrite, put some text. I open note in the app - text is there but it said nothing. Checked "notify about all external modifications" but still nothing.
In file props I see that it is recreated with kwrite saving. Creation and modification time are the same. Same after changes with the app. It's on BTRFS partition if it'll explain anything.

**Comment by Maboroshy** [comment]
I want to wrap this issue since it's subject is "no fix".

Rare guys like me wanting to change relative paths of note images to absolute can run the following script from the dir where all notes dirs are stored:

#!/bin/bash
IFS=$'\n'
for d in *
do ( cd $d && sed -i -e "s|file://media|file://$PWD/media|g" *.md )
done 

I'm no scripting genius so if it'll destroy all your notes or kill your dog - it's all your fault.

With this script having notes stored on my desktop in the exact path as on android phone I can see all images in MarkdownX editor on my phone.

**Comment by pbek** [comment]
KWrite doesn't seem to simply overwrite the file in a way the Qt directory watcher can recognize it as file change. That's why asked for `echo test >> your-note.md`, which works for me on the same system where KWrite doesn't.

**Comment by pbek** [comment]
Better make a backup of all your files before you run your script so that my imaginary dog doesn't have to suffer a tragic end :) Since your script seems to work you are a scripting genius now!

**Comment by Maboroshy** [comment]
When I'm in the note and "echoing" it - warning shows up. If I'm in some other note - no warning and no warning on entering changed note. "Notify about all external modifications" still checked.

**Comment by pbek** [comment]
Only the current note gets such a warning, the other notes simple get re-read. I guess in KWrite (and it seems also in ownCloud sync) files get stored temporarily and then moved over the old file...

**Comment by Maboroshy** [comment]
It works then. Maybe that should be clarified somewhere. Because my first thoughts were that warning should pop-up after opening edited notes. 
"Notify about all external modifications" for my untechy eyes should definitely make a lot of pop-ups. :)

**Comment by pbek** [comment]
It used to work also for kwrite and owncloud sync, but something changed, maybe in qt, maybe in kde, maybe in owncloud sync... if a program removes a note (it is dropped by the directory watcher then because it disappeared) and then adds a new file with the same name that technically is no "change". I will see if there is a workaround...

**Comment by pbek** [comment]
@Maboroshy in version 16.05.9 I built in a small remedy to the Linux missing external changes problem. Could you please report if it lessens the problem for you? 

And currently I'm working on a scripting system for QOwnNotes. ;)

**Comment by Maboroshy** [comment]
1. "Notify about all external modifications" unchecked:
a) "Echoing" or "kwriting" opened note brings "current note modified externally" message in status bar for about 1 second;
b) "Echoing" other than opened note brings "note was modified externally: [path]" message in status bar for about 1 second. No message or pop-up on opening note.
c) "Kwriting" other than opened note brings "note directory was modified externally" message in status bar for about 1 second.

2. "Notify about all external modifications" checked:
a) "Echoing" opened note brings "Note was modified externally!" pop-up dialog;
b) "Kwriting" opened note brings "Note was modified externally!" on first edit in kwrite even before saving.
b) "Echoing" other than opened note brings "note was modified externally: [path]" message in status bar for about 1 second. No message or pop-up on opening note.
c) "Kwriting" other than opened note brings "note directory was modified externally" message in status bar for about 1 second.

All works on my Manjaro Linux but I get pop-up only on editing opened note. Don't know if it's supposed to work like this by design. This way the "Notify about all external modifications" is little misleading. As a user I expect something more when I check option with "all" in it. Maybe something like "Display pop-up notification when current note modified externally" will be closer description.

Also I find timeout for status bar message too short. I had to run some test for 3 times to read full message for posting it here. The easy way as I see it would be increase timeout, harder and maybe more proper way would be showing message till obtaining a user input in app window (typing or clicking) but no less than 3 seconds.

**Comment by pbek** [comment]
Thanks a lot for testing and your suggestions!
I will change the wording of the settings and add `of the current note`, because that's what the setting is supposed to do.
And I will increase the viewing time of these status messages a bit (they initially were only meant for debugging).

**Comment by pbek** [comment]
@Maboroshy, if you want you can be the first tester of the new, experimental **scripting support** in QOwnNotes!

I also made it possible to alter the media links in scripts and also implemented the absolute link functionality for you as a script. :smile: 
<https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/absolute-media-links.qml>

Please tell me if it works and what you think.

## 16.05.10
- QOwnNotes now has experimental **scripting support**
	- by using the power of the QQmlEngine and QML files you are now able
	  to script some behaviors in the application yourself
	- you will find a new *Scripting* tab in the settings dialog where you can 
	  add as many scripts to QOwnNotes as you like
	- it is possible to disable or remove scripts
	- you may need to restart QOwnNotes to let changes in a script take action 
	- I prepared some
	  [examples](https://github.com/pbek/QOwnNotes/tree/develop/doc/scripting)
	  to play around with
	- if you need access to a certain functionality in QOwnNotes or have 
	  questions or ideas please open an issue on the 
	  [QOwnNotes issue page](https://github.com/pbek/QOwnNotes/issues)

**Comment by Maboroshy** [comment]
Excellent news! Your development speed is absolutely crazy. Compiling new version now.
It will take me a while to learn QML but I'm looking forward to it. I'll try to play with it on the weekend.

**Comment by pbek** [comment]
Watch out in the next version: the function `modifyMediaMarkdown` will be renamed to `insertMediaHook` for more consistency.

**Comment by pbek** [comment]
You can use <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/absolute-media-links.qml> in the just released version 16.05.11. I also renamed it in the examples.
