### ISSUE TITLE
Wonky web page graphic links

### ISSUE THREAD

**Issue by truthsword** [pbek/QOwnNotes#1610]
When I try to capture:
https://www.labnol.org/internet/amazon-price-tracker/28156/
using create note from html import, the major graphics come across as oddly coded links, for example,

```
[
](/static/e2bb44389bb00a8772245e6e69ae327e/6c190/amazon-product-links.png)
```
Needless to say, the graphics are not viewable. 

Why is this?

**Comment by pbek** [comment]
Well, the HTML is the wonkiest I've seen. :laughing: I even can't find the images from the markdown after I captured it (like `amazon-price-tracker.png`) in the HTML source. I don't know how on improve the process for that page.

**Comment by truthsword** [comment]
I guess the "good news" is that it's not just me. No worries then 8-)

**Comment by pbek** [comment]
Converting very complex Web-Pages to markdown will never work satisfactorily. :grimacing: I guess I close this then.
