### ISSUE TITLE
Crash when showing note versions

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1611]
@Waqar144, I'm getting hard to reproduce crash in QON when showing the note versions of a note in the current release. But it's only happening in release mode and it seems it's happening in the highlighter. 

```
1   Note::getFileURLFromFileName(QString) const                                                            0x5555556ebeb4 
2   Note::fetchByRelativeFileName(QString const&) const                                                    0x5555556ec132 
3   QOwnNotesMarkdownHighlighter::highlightBrokenNotesLink(QString const&)                                 0x5555557401af 
4   QOwnNotesMarkdownHighlighter::highlightBlock(QString const&)                                           0x55555574107f 
5   ??                                                                                                     0x7ffff68e2660 
6   ??                                                                                                     0x7ffff68e2820 
7   QMetaObject::activate(QObject *, int, int, void * *)                                                   0x7ffff4b29805 
8   QTextDocument::contentsChange(int, int, int)                                                           0x7ffff6b550ca 
9   QTextDocumentPrivate::finishEdit()                                                                     0x7ffff689d8a1 
10  ??                                                                                                     0x7ffff7187913 
11  QMarkdownTextEdit::setPlainText(QString const&)                                                        0x5555557f1010 
12  VersionDialog::on_versionListWidget_currentRowChanged(int)                                             0x5555556d15df 
13  VersionDialog::qt_metacall(QMetaObject::Call, int, void * *)                                           0x55555594bbae 
14  QMetaObject::activate(QObject *, int, int, void * *)                                                   0x7ffff4b298c9 
15  QListWidget::currentRowChanged(int)                                                                    0x7ffff7243b71 
16  ??                                                                                                     0x7ffff7244662 
17  QMetaObject::activate(QObject *, int, int, void * *)                                                   0x7ffff4b29805 
18  QItemSelectionModel::currentChanged(QModelIndex const&, QModelIndex const&)                            0x7ffff4aa212a 
19  QItemSelectionModel::setCurrentIndex(QModelIndex const&, QFlags<QItemSelectionModel::SelectionFlag>)   0x7ffff4aa23b6 
20  QListWidget::setCurrentRow(int)                                                                        0x7ffff7244aa6 
... <More>
```

It seems it is caused by your changes on 15.01.2020 going from `QOwnNotesMarkdownHighlighter::updateCurrentNote(const Note &_note)` to `QOwnNotesMarkdownHighlighter::updateCurrentNote(Note *_note)` in https://github.com/pbek/QOwnNotes/commit/a8e876b4b89f9c4edb67ddf2d48b3e818565d31f.

QOwnNotes Debug Information
===========================

## General Info

**Version**: `20.1.18`
**Build date**: `Jan 27 2020`
**Build number**: `665`
**Platform**: `linux`
**Operating System**: `KDE neon User Edition 5.17`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.9.5`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`

**Comment by pbek** [comment]
It crashes at accessing `noteSubFolderId` in `Note::getFileURLFromFileName`. How is that even possible!?

**Comment by Waqar144** [comment]
Possibly because the `currentNote` gets changed and hence the old pointer becomes invalid resulting in invalid memory access.

**Comment by pbek** [comment]
Exactly.

**Comment by pbek** [comment]
Beware of the next release, it will be release number 666! :laughing:

**Comment by Waqar144** [comment]
> Beware of the next release, it will be release number 666! 😆

🤣

**Comment by pbek** [comment]
## 20.1.19
- fixed a possible crash in the broken link highlighter
  (for [#1611](https://github.com/pbek/QOwnNotes/issues/1611), thank you @Waqar144)
