### ISSUE TITLE
Key 7 of the keyboard doesn't insert the right caracter

### ISSUE THREAD

**Issue by Primokorn** [pbek/QOwnNotes#1619]
Hello,

In a new note, I press the key "7" on the keyboard to insert this letter in QOwnNotes:
![jelly_comb_keyboard_french_azerty_11754](https://user-images.githubusercontent.com/5938828/74017948-58faaf00-4995-11ea-9b38-4c4635d14ef7.png)

This symbol is actually added into QOwnNotes:
![jelly_comb_keyboard_french_azerty_11754_2](https://user-images.githubusercontent.com/5938828/74018006-70399c80-4995-11ea-993b-88dd40d351ee.png)

![2020-02-07 10_30_16-QOwnNotes 20 2 2](https://user-images.githubusercontent.com/5938828/74018026-73cd2380-4995-11ea-99b5-54cee250cfff.png)

Normally I can only use the symbols at the bottom right when using ALT GR key.
Caps / Shift is not enabled.

My keyboard is Azerty and I don't have this issue with my web browser for example.

QOwnNotes 20.2.2

**Comment by pbek** [comment]
When I press `7` then `7` is inserted.

Can you please explain in more detail and step by step what you did, what happened and what you expected.

**Comment by Primokorn** [comment]
1. Create a new note
2. Be sure that **caps** is disabled
3. Press the key "è" (the same one as "7")

`è` should be inserted into the note but I get ```

**Comment by pbek** [comment]
I have a QWERTZ keyboard. I need to press ``` and `e`. I get `è` as result.

**Comment by Primokorn** [comment]
Do you consider this as the normal behaviour? I've never seen this on Github or on various forums which support markdown.

**Comment by pbek** [comment]
I haven't seen it any different anywhere.

**Comment by Primokorn** [comment]
It's different here, on Github.
I can press `backtick` then `e` or directly press `è`.

**Comment by pbek** [comment]
I don't think that has anything to do with GitHub, but rather with your web browser and the integration of your input system. In the case of QON it would be a thing between Qt, your input system and your operating system.

**Comment by Primokorn** [comment]
OK. Here are some information if it can help:
* Keyboard: Dell KB216 Wired Keyboard
Driver date: 06.21.2006 - Version 6.1.7601.23403
* Windows 7 Pro SP1

**Comment by pbek** [comment]
I don't think that something I can fix. 🙁

**Comment by Primokorn** [comment]
FWIW I tested with another note taking software which supports markdown and I do not have this issue.

**Comment by pbek** [comment]
I'm open for pull requests.

**Comment by Primokorn** [comment]
The [other software](https://github.com/laurent22/joplin) is open source. Can it help?

**Comment by pbek** [comment]
No. Joplin is an Electron app. It runs in a browser.

**Comment by Primokorn** [comment]
Today I don't have the problem with version 20.3.1... Did you do something special?

**Comment by pbek** [comment]
Nothing that I'm aware of. Maybe your operating system fixed it?

**Comment by Primokorn** [comment]
Honestly I have no idea.
