### ISSUE TITLE
Can't build 16.05.3 on Linux

### ISSUE THREAD

**Issue by jfebrer** [pbek/QOwnNotes#162]
I'm using Debian sid with Qt 5.5.1 and GCC 5.3.1, previously I could build QOwnNotes 16.04.14 successfully but not with the latest version.
This is the error:

mainwindow.cpp: In member function ‘void MainWindow::on_actionReplace_in_current_note_triggered()’:
mainwindow.cpp:4810:31: error: ‘class QTextEditSearchWidget’ has no member named ‘activateReplace’
     textEdit->searchWidget()->activateReplace();
                               ^
Makefile:1336: recipe for target 'mainwindow.o' failed

**Comment by pbek** [comment]
It seems you didn't update all git submodules.
Please try calling a `git submodule update --init`. It should work then.
You can also use the source archives from <https://sourceforge.net/projects/qownnotes/files/src/> or use the pre-build packages at <http://www.qownnotes.org/installation#Debian>.

Did this help you?

**Comment by jfebrer** [comment]
Thank you!

I just did git pull and didn't update all submodules, after your instructions I could build it again.

**Comment by pbek** [comment]
Great to hear!
