### ISSUE TITLE
Feature Request: Ability to duplicate notes

### ISSUE THREAD

**Issue by timunrau** [pbek/QOwnNotes#1622]
#### Expected behaviour
Right click on a note to duplicate it. Then QOwnNotes would create a copy of that note in the same folder. 

The use case would be for me to create note templates and then be able to duplicate them whenever I want to create a note with that template. 

#### Actual behaviour
No option to duplicate the note. 

#### Steps to reproduce
1. Right click on a note. 
2. See how there is no option to duplicate it. :)

**Comment by pbek** [comment]
You could easily do that with the scripting engine in a custom action by

- taking the text of the current note
- copying it to the clipboard
- creating a new note
- selecting the whole text of the (new) current note
- pasting the text from the clipboard

see: https://docs.qownnotes.org/en/develop/scripting/README.html

Are you up to the challenge? :muscle:

**Comment by pbek** [comment]
It's actually even easier:

- taking the text of the current note
- creating a new note with the text

**Comment by Waqar144** [comment]
You can also do it by just doing `Ctrl+C` and `Ctrl+V` the note :rofl:

**Comment by timunrau** [comment]
I realize that all three of these options are ways to do this, but they would require more steps than just right clicking on a note

**Comment by fnkabit** [comment]
@timunrau Added a simple script for creating a duplicate note. It adds a 'Duplicate selected note' entry in the context menu. 
The script is called 'Duplicate note'.

**Comment by pbek** [comment]
Thank you, @fnkabit! I will close this issue until there is more information.

**Comment by timunrau** [comment]
> @timunrau Added a simple script for creating a duplicate note. It adds a 'Duplicate selected note' entry in the context menu.
> The script is called 'Duplicate note'.

Thanks @fnkabit, this works great.

**Comment by fnkabit** [comment]
@timunrau That's great, thank you for testing it !
