### ISSUE TITLE
No mountable file system on macOS

### ISSUE THREAD

**Issue by sabinomaggi** [pbek/QOwnNotes#1630]
Any idea why on macOS I get a "no mountable file system" while trying to mount the `.dmg`?
I have tried the latest releases (20.2.4 and 20.2.2) and also the last beta with the same results.

![Screen Shot 2020-02-15 at 11 11 08](https://user-images.githubusercontent.com/582340/74586066-04ce7b00-4fe4-11ea-9302-55e3f36735c8.png)

**Comment by pbek** [comment]
I'm sorry, I've no troubles mounting it. Are you sure your download didn't went wrong? What is the filesize of the dmg and what does `shasum QOwnNotes-20.2.4.dmg` say for you in the terminal?

```
228504a9c496abb7d21bb59f1a51a0240e358c55  QOwnNotes-20.2.4.dmg
```

**Comment by sabinomaggi** [comment]
Shasum is ok:
> $ shasum QOwnNotes-20.2.4.dmg 
> 228504a9c496abb7d21bb59f1a51a0240e358c55  QOwnNotes-20.2.4.dmg

Also, my md5 is
> $ md5 QOwnNotes-20.2.4.dmg 
> MD5 (QOwnNotes-20.2.4.dmg) = d11748a29f8934c9dd0bf5e7251ee9bd

I have tried many times to download the file, and I always get the same result. I have also tried to download previous versions, down to about 19.x and I always get the same result. By the way, on my Mac I have 16.12.9 and that works well.
For what versions of macOS did you compile the latest versions of QOwnNotes?

**Comment by pbek** [comment]
Qt 5.13 works with all recent versions of macos. Lots of people are using qownnotes on macos. But this doesn't matter. You can't even mount the dmg.

**Comment by sabinomaggi** [comment]
I think I have understood the issue. 
> $ hdiutil verify QOwnNotes-20.2.4.dmg

reports among other info that the disk image is made using APFS and not HFS+
> ...
> disk image (Apple_APFS : 4): verified   CRC32 $EDF37C20
> ...

so it won't work on all versions of macOS that do not support APFS, i.e. from High Sierra amd above. The Mac I have used for these tests runs El Capitan (much stabler and reliable than later macOS versions) and that is the reason it does not open the `dmg` file.

Could you please add a page on the website or on github, listing for each of the last versions of macOS the stable compatible versions of QOwnNotes?
For instance, QOwnNotes is compatible with El Capitan up to version xx, Sierra/High Sierra up to version yy and the like?

**Comment by pbek** [comment]
I run QOwnNotes on 10.15.3 right now and every previous version before.

The dmg is created by this line:
https://github.com/pbek/QOwnNotes/blob/f8561c311d1c678a91d07af7d34cc0685b0164e1/travis/create-dmg.sh#L119

**Comment by pbek** [comment]
According to https://de.wikipedia.org/wiki/Universal_Disk_Image_Format `UDBZ` isn't obsolete.

**Comment by sabinomaggi** [comment]
You are right, UDBZ is ok. For better compatibility, you could try to add a `-fs` switch with the option JHFS+ (or simply HFS+), more or less like this

```
hdiutil create -srcfolder ./$TEMPDIR -ov -format UDBZ  -fs JHFS+ ./$APP.dmg 
```
(`-ov` ensures that the new image overwrites an already existing one, otherwise `hdiutil create` fails).

**Comment by pbek** [comment]
Ok, we'll try that then.

## 20.2.5
- attempted to fix rare QOwnNotes disk image mount problems under macOS

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by sabinomaggi** [comment]
Yes, now I can open the dmg file without any problem. Many thanks for the quick fix!

Unfortunately the latest versions of QOwnNotes run only on more recent versions of macOS than El Capitan, but that is another question. Do you have an idea which versions of macOS does QOwnNotes 20.2.5 need to run? It would also be nice to know which was the latest version of QOwnNotes working on El Capitan (which is still very popular).

**Comment by pbek** [comment]
I think the currently used Qt 5.13.2 is supported on macOS 10.13 upwards, see https://doc.qt.io/qt-5/macos.html

Of course you can build QOwnNotes yourself, it works on Qt 5.3 upwards.
See https://www.qownnotes.org/installation#building

**Comment by pbek** [comment]
It seems https://doc-snapshots.qt.io/qt5-5.11/supported-platforms.html is the last supported release for macOS 10.11.
