### ISSUE TITLE
[I] QNetworkReply error 204 from url myserver/remote.php/webdav/: Host requires authentication

### ISSUE THREAD

**Issue by acloudadmin** [pbek/QOwnNotes#1631]
Please paste the text from the issue assistant h#### Expected behaviour

When trying to set the Nextcloud folder where my notes are stored, I expect to see a list of my Nextcloud folders

#### Actual behaviour

In the Notes Folders dialogue window, I click on the folders icon next to the "Path on your Nextcloud" field. 

For a moment, I see the message "Loading folders from server" underneath the large blank box. Then for a moment I see the message "no more folders were found in the current folder."

I have Nextcloud enabled and seven green OKs under the 'connection status' in the Nextcloud dialogue box

The log says: "QNetworkReply error 204 from url myserver/remote.php/webdav/: " "Host requires authentication"

#### Steps to reproduce

Open QOwn notes. Successfully connect to Nextcloud server with QOwn API app installed. Go to "Setup Note Folders" dialogue and push the folder icon next to the "Path on your Nextcloud" field.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[Feb 15 13:48:51] [warning]: "QNetworkReply error 204 from url https://aaacloud.ddns.net/remote.php/webdav/: " "Host requires authentication"
[Feb 15 13:48:51] [debug]: Reply from ownCloud webdav
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sat Feb 15 13:56:45 2020`
**Version**: `20.2.4`
**Build date**: `Feb 13 2020`
**Build number**: `5381`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\sss\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `E:\media1\Software\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1600x900`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `52`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https:.net`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `18.0.1.3`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\sss\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `E:\media1\Family\admin`
**remotePath**: *empty*
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `E:\media1\Family\admin\notes.sqlite`

### Cloud connection `acloud`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://net`
**username**: `acloud`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `true`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-02-15T13:24:54.927`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `21`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,14,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.14286,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/remove-notes** (int): `16384`
**NoteHistory-1** (QVariantList): `<variant list with 8 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `7`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `txt`
**disableAutomaticUpdateDialog** (QString): `false`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `1col`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `12`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (int): `16`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `false`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `E:/media1/Family/admin`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `18.0.1.3`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2020-02-15T08.58.45`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Single column`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `false`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\sss\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: ``
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\sss`
**LOCALAPPDATA**: `C:\Users\sss\AppData\Local`
**LOGONSERVER**: `\\D`
**NUMBER_OF_PROCESSORS**: `4`
**OneDrive**: `C:\Users\sss\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\ProgramData\Oracle\Java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\quicktime alternative\qtsystem;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Users\sss\AppData\Local\Microsoft\WindowsApps`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 60 Stepping 3, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `3c03`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\sss\AppData\Local\Temp`
**TMP**: `C:\Users\sss\AppData\Local\Temp`
**USERDOMAIN**: ``
**USERDOMAIN_ROAMINGPROFILE**: ``
**USERNAME**: `sss`
**USERPROFILE**: `C:\Users\sss`
**windir**: `C:\WINDOWS`
**__COMPAT_LAYER**: `RunAsAdmin Installer`
</details>

**Comment by pbek** [comment]
Strange, it works for me.
Are you able to access your Nextcloud/ownCloud trash via QOwnNotes?

**Comment by acloudadmin** [comment]
You mean it works for you on your own setup?

When I try to access show remote trash, I get "Cannot connect to nextcloud / owncloud server. check your configuration error." But when I check configuration I'm still getting 7 green OKs. 

no obvious signs of trouble in the logs:

[Feb 15 17:43:15] [status]: Trashed notes are currently loaded from your Nextcloud / ownCloud server
[Feb 15 17:43:15] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"acloud" <serverUrl>"https://aaacloud.ddns.net" <username>"acloud" <priority>1
[Feb 15 17:43:22] [debug]: Reply from  "/index.php/apps/qownnotesapi/api/v1/note/trashed"
[Feb 15 17:43:22] [debug]: Reply from trash list
[Feb 15 17:43:22] [status]: Done with loading trashed notes
[Feb 15 17:45:33] [debug]: Set proxy configuration to use NO proxy
[Feb 15 17:45:34] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"acloud" <serverUrl>"https://aaacloud.ddns.net" <username>"acloud" <priority>1
[Feb 15 17:45:34] [debug]: Set proxy configuration to use NO proxy
[Feb 15 17:45:35] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"acloud" <serverUrl>"https://aaacloud.ddns.net" <username>"acloud" <priority>1
[Feb 15 17:45:36] [debug]: Reply from  "/ocs/v1.php"
[Feb 15 17:45:36] [debug]: Reply from ownCloud test page
[Feb 15 17:45:36] [debug]: Reply from  ""
[Feb 15 17:45:36] [debug]: Reply from main server url
[Feb 15 17:45:36] [debug]: Reply from  ""
[Feb 15 17:45:36] [debug]: Reply from main server url
[Feb 15 17:45:36] [debug]: Reply from  "/ocs/v1.php/cloud/capabilities"
[Feb 15 17:45:36] [debug]: Reply from capabilities page
[Feb 15 17:45:37] [debug]: Reply from  "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[Feb 15 17:45:37] [debug]: Reply from app info
[Feb 15 17:45:38] [debug]: Reply from  "/ocs/v1.php"
[Feb 15 17:45:38] [debug]: Reply from ownCloud test page
[Feb 15 17:45:38] [debug]: Reply from  "/ocs/v1.php/cloud/capabilities"
[Feb 15 17:45:38] [debug]: Reply from capabilities page
[Feb 15 17:45:39] [debug]: Reply from  "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[Feb 15 17:45:39] [debug]: Reply from app info

**Comment by acloudadmin** [comment]
You mean it works for you on your own setup?

When I try to access show remote trash, I get "Cannot connect to nextcloud / owncloud server. check your configuration error." But when I check configuration I'm still getting 7 green OKs.

no obvious signs of trouble in the logs:

[Feb 15 17:43:15] [status]: Trashed notes are currently loaded from your Nextcloud / ownCloud server
[Feb 15 17:43:15] [debug]: cloudConnection: CloudConnection: 1 "acloud" "https:net" "acloud" 1
[Feb 15 17:43:22] [debug]: Reply from "/index.php/apps/qownnotesapi/api/v1/note/trashed"
[Feb 15 17:43:22] [debug]: Reply from trash list
[Feb 15 17:43:22] [status]: Done with loading trashed notes
[Feb 15 17:45:33] [debug]: Set proxy configuration to use NO proxy
[Feb 15 17:45:34] [debug]: cloudConnection: CloudConnection: 1 "acloud" "https:" "acloud" 1
[Feb 15 17:45:34] [debug]: Set proxy configuration to use NO proxy
[Feb 15 17:45:35] [debug]: cloudConnection: CloudConnection: 1 "acloud" "https:" "acloud" 1
[Feb 15 17:45:36] [debug]: Reply from "/ocs/v1.php"
[Feb 15 17:45:36] [debug]: Reply from ownCloud test page
[Feb 15 17:45:36] [debug]: Reply from ""
[Feb 15 17:45:36] [debug]: Reply from main server url
[Feb 15 17:45:36] [debug]: Reply from ""
[Feb 15 17:45:36] [debug]: Reply from main server url
[Feb 15 17:45:36] [debug]: Reply from "/ocs/v1.php/cloud/capabilities"
[Feb 15 17:45:36] [debug]: Reply from capabilities page
[Feb 15 17:45:37] [debug]: Reply from "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[Feb 15 17:45:37] [debug]: Reply from app info
[Feb 15 17:45:38] [debug]: Reply from "/ocs/v1.php"
[Feb 15 17:45:38] [debug]: Reply from ownCloud test page
[Feb 15 17:45:38] [debug]: Reply from "/ocs/v1.php/cloud/capabilities"
[Feb 15 17:45:38] [debug]: Reply from capabilities page
[Feb 15 17:45:39] [debug]: Reply from "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[Feb 15 17:45:39] [debug]: Reply from app info

**Comment by pbek** [comment]
> When I try to access show remote trash, I get "Cannot connect to nextcloud / owncloud server. check your configuration error." But when I check configuration I'm still getting 7 green OKs.

Did you install qownnotesapi on your Nextcloud server?

> You mean it works for you on your own setup?

yes, but I just found one other device where it doesn't, after digging a lot deeper I found out that Nextcloud 18 seems to reply a `CSRF check not passed` even if the correct auth header is sent, which is very strange because I already did that by hand on other Nextcloud server.

**Comment by acloudadmin** [comment]
Hi,

Yes, I've install successfully installed the API. Like I said, the "Nextcloud/Owncloud" page of the settings shows all OK.

![connected1](https://user-images.githubusercontent.com/55052096/74603552-98ef1f80-5082-11ea-9724-2c3049859952.jpg)

In case it helps, I'm running Nextcloud 18.01.03 on Daniel Hansson's 40gb VM running on a Ubuntu server 18.04 VM running on VirtualBox on a Windows machine. I'm using apache and PHP 7.4

**Comment by pbek** [comment]
Phew, this took several hours to get right.

## 20.2.5
- fetching of remote note folders in the *Note folders settings* now should
  work properly with Nextcloud
    - using different cloud connections now also works properly with the remote
      note folder selector
    - switching to another cloud connection in the *Note folders settings* now
      also triggers a reload of the remote note folder selector if it is visible

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by acloudadmin** [comment]
It works! Thanks so much for all your work on this!

**Comment by pbek** [comment]
Great, thank you for testing! 😁
