### ISSUE TITLE
Note to note links are broken in edit mode

### ISSUE THREAD

**Issue by Airgunster** [pbek/QOwnNotes#1632]
#### Expected behaviour
* Hit CMD+L/CTRL+L inside a Note and create a link to a Note.
* Click hit CMD+LEFT_CLICK on a Note and move to a linked Note.

#### Actual behaviour
* Hit CMD+L/CTRL+L inside a Note and create a link to a Note.
* Click hit CMD+LEFT_CLICK on a Note and observe that nothing is happening.

#### Steps to reproduce
Described above.

#### Output from the debug section in the settings dialog
**Version**: `20.2.4`
**Operating System**: `macOS 10.15`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`

**Comment by pbek** [comment]
> Steps to reproduce

Can you please explain in more detail what happened with all the text you entered, all the text that was put in your note and note names and so on.

Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging.

**Comment by pbek** [comment]
Note linking works just as it should for me under macOS...

**Comment by Airgunster** [comment]
@pbek, You're right, I should provide a better reproduction steps, apologies for that.

> Can you please explain in more detail what happened with all the text you entered, all the text that was put in your note and note names and so on.

I was actually able to find the reason Note to Note links were broken in my case, that was due to `(` and `)` characters in the Title of the Note.

* Create new Note A with `Title (Test)` text.
* Create new Note B, hit CMD+L/CTRL+L inside a Note and create a link to Note A.
* Click hit CMD+LEFT_CLICK in Note B for a link to Note A and observe that nothing is happening.

> Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging.

Only that single line is produced,
```
[Feb 16 20:39:47] [debug]: openLinkAtCursorPosition  - 'emit urlClicked( urlString )':  "Title (Test"
```

**Comment by pbek** [comment]
Brackets naturally don't work at all in file names with markdown links. If you really want to use them you can try to turn back on the legacy linking in the *General settings* and create new links. They should look like `note://filename`. There are some chances that this will work.

**Comment by pbek** [comment]
If the "legacy links" work maybe I can add that as fallback.

**Comment by Airgunster** [comment]
@pbek,
> Brackets naturally don't work at all in file names with markdown links.

That's interesting, do you know why they don't work at all? I mean what's the reason behind? I don't see any issues having `<`,`>`,`(`,`)`,`[`,`]` characters in the filename path from filesystem point of view (at least for APFS/HFS+/Ext3/Ext4/Xfs).

I've actually tried to use `[` and `]` brackets instead, and Note to Note links are working with them fine,

```
[Feb 16 22:16:58] [debug]: openLinkAtCursorPosition  - 'emit urlClicked( urlString )':  "Note [Test].md"
[Feb 16 22:16:58] [debug]: fileUrlInCurrentNoteFolderToRelativePath  - 'path':  "/Users/airgunster/Documents/Inbox/Note [Test].md"
[Feb 16 22:16:58] [debug]: fileUrlInCurrentNoteFolderToRelativePath  - 'canonicalFilePath':  "/Users/airgunster/Documents/Inbox/Note [Test].md"
[Feb 16 22:16:58] [debug]: setCurrentNote  - 'note':  Note: <id>2 <name>"Note [Test]" <fileName>"Note [Test].md" <noteSubFolderId>1 <relativePath>"Inbox" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  true
[Feb 16 22:16:58] [debug]:  added to history:  NoteHistoryItem: <noteName>"Note [Test]" <noteSubFolderPathData>"Inbox" <cursorPosition>0 <relativeScrollBarPosition>0
```

Only highlighting is broken,
<img width="424" alt="Screenshot 2020-02-16 at 22 36 30" src="https://user-images.githubusercontent.com/7937957/74614111-0051b180-510d-11ea-9eb8-2e44608bfdc7.png">

With _Use legacy way to link to notes_ enabled, same issue, no change for `(`,`)`, while with `[`,`]` it does work same as without _Use legacy way to link to notes_ being enabled,
```
[Feb 16 22:35:54] [debug]: openLinkAtCursorPosition  - 'emit urlClicked( urlString )':  "Note (Test"
[Feb 16 22:35:58] [debug]: openLinkAtCursorPosition  - 'emit urlClicked( urlString )':  "Note [Test].md"
[Feb 16 22:35:58] [debug]: fileUrlInCurrentNoteFolderToRelativePath  - 'path':  "/Users/airgunster/Documents/Inbox/Note [Test].md"
[Feb 16 22:35:58] [debug]: fileUrlInCurrentNoteFolderToRelativePath  - 'canonicalFilePath':  "/Users/airgunster/Documents/Inbox/Note [Test].md"
[Feb 16 22:35:58] [debug]: setCurrentNote  - 'note':  Note: <id>2 <name>"Note [Test]" <fileName>"Note [Test].md" <noteSubFolderId>1 <relativePath>"Inbox" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  true
[Feb 16 22:35:58] [debug]:  added to history:  NoteHistoryItem: <noteName>"Note [Test]" <noteSubFolderPathData>"Inbox" <cursorPosition>0 <relativeScrollBarPosition>0
```

**Comment by pbek** [comment]
If you ctrl + click the link some nifty code (written by me) tries to detect what part near the clicked text could be a link. Those extra brackets disturb that process (as well as the highlighting) because they are part of the markdown syntax. 😁

**Comment by pbek** [comment]
> With Use legacy way to link to notes enabled, same issue, no change for (,), while with [,] it does work same as without Use legacy way to link to notes being enabled,

how did you link look like?

**Comment by pbek** [comment]
## 20.2.6
- more improvements to the link dialog were made
    - entering of `]` characters in link name line edit is now disabled since
      they would break the markdown link
        - they also will be removed from the link name automatically if they
          were part of the note file name 
    - if one of the link characters `<>()` were found in the note url the legacy
      way of linking will be used because otherwise the url would break the
      markdown link

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Airgunster** [comment]
@pbek, apologies for the extreme delay with reply.

I'm currently using v. 20.3.6 and links works perfect (with _Use legacy way to link notes, images and attachments_ un-ticked). However there's a small syntax highlighting issue with `Note [Test]` Note,

<img width="383" alt="Screenshot 2020-03-20 at 22 16 05" src="https://user-images.githubusercontent.com/7937957/77210242-6b214e80-6af8-11ea-9b0b-109702f1738f.png">

That's due to `[` `]` characters. Is it possible to correct this and ignore one `]` character for Note links which contains `[` `]` characters?

Thanks again for the help!

**Comment by pbek** [comment]
I'm sorry, the `Test` part is already a correct link. You are not supposed to have other brackets in there. Even GitHub here would render it the same...

`[test [test](test.md)`: [test [test](test.md)

**Comment by Airgunster** [comment]
@pbek, Cool, no problem at all. Thanks again for such a wonderful software!

**Comment by pbek** [comment]
thank you, @Airgunster :smile_cat:
