### ISSUE TITLE
Not Displaying images in Version 20.2.6 on Windows

### ISSUE THREAD

**Issue by docfactory37** [pbek/QOwnNotes#1635]
#### Expected behaviour
* I have updated to the latest stabe version on **Windows** 20.2.6.
i have tried adding now images and they do not display on the preview panel.

![image](https://user-images.githubusercontent.com/20963053/74696083-65f78800-524a-11ea-9d49-f22c65f3b650.png)
****

#### Actual behaviour
* when images is add it should display the images or if have script image preview should display thumbail.

#### Steps to reproduce
* Click on insert image and add image then click ok
* Copy image then do Ctrl ->Shift -> V

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Feb 18 12:32:55 2020`
**Version**: `20.2.6`
**Build date**: `Feb 17 2020`
**Build number**: `5398`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\robertg01\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\QOwnNotes\QOwnNotes.exe`, `--after-update`, `C:\Users\robertg01\AppData\Local\Temp\QOwnNotes-aVYaZg-updater.bat`
**Qt Debug**: `0`
**Locale (system)**: `en_AU`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080, 1920x1080`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `166`
**Calendar items**: `0`
**Enabled scripts**: `16`

## Server Info

**serverUrl**: `http://cloud.mediafactory.ddns.net`
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `en_AU`
**Language codes**: `en_AU`
**Language names**: `Australian English (Australia)`
**Application dictionaries path**: `C:\Users\robertg01\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Work`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `C:\Users\robertg01\Nextcloud\Notes\Work`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: `Meeting`
**database file**: `C:\Users\robertg01\Nextcloud\Notes\Work\notes.sqlite`

### Note folder `Personal`

**id**: `2`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `C:\Users\robertg01\Nextcloud\Notes\Personal`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\robertg01\Nextcloud\Notes\Personal\notes.sqlite`

### Note folder `University`

**id**: `3`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `C:\Users\robertg01\Nextcloud\Notes\University`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\robertg01\Nextcloud\Notes\University\notes.sqlite`

### Note folder `Tablet-Notes`

**id**: `4`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `C:\Users\robertg01\Nextcloud\Notes\Markor`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\robertg01\Nextcloud\Notes\Markor\notes.sqlite`

### Cloud connection `New connection`

**id**: `2`
**isCurrent**: `no`
**serverUrl**: `https://cloud.mediafactory.ddns.net`
**username**: `robertg`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `http://cloud.mediafactory.ddns.net`
**username**: `robertg`

### Script `Checkbox preview and export`

**id**: `1`
**path**: `C:\Users\robertg01\AppData\Roaming\PBE\QOwnNotes\scripts\export-checkboxes\export-checkboxes.qml`
**variablesJson**: *empty*
**identifier**: `export-checkboxes`
**version**: `0.0.3`
**minAppVersion**: `17.12.0`

### Script `External note diff`

**id**: `2`
**path**: `C:\Users\robertg01\AppData\Roaming\PBE\QOwnNotes\scripts\external-note-diff\external-note-diff.qml`
**variablesJson**: 
```
{
    "executablePath": "C:\\Program Files (x86)\\Meld\\Meld.exe"
}
```
**identifier**: `external-note-diff`
**version**: `0.0.1`
**minAppVersion**: `17.07.8`

### Script `Insert Table of Contents (TOC)`

**id**: `3`
**path**: `C:\Users\robertg01\AppData\Roaming\PBE\QOwnNotes\scripts\insert-toc\insert-toc.qml`
**variablesJson**: 
```
{
    "tocLinks": true,
    "tocTitle": "Table of Contents"
}
```
**identifier**: `insert-toc`
**version**: `0.0.3`
**minAppVersion**: `17.06.2`

### Script `List maker`

**id**: `4`
**path**: `C:\Users\robertg01\AppData\Roaming\PBE\QOwnNotes\scripts\list-maker\list-maker.qml`
**variablesJson**: 
```
{
    "setLetters": "abcdefghijklmnopqrstuvwxyz",
    "setMarkers": "- • ‣"
}
```
**identifier**: `list-maker`
**version**: `0.0.2`
**minAppVersion**: `17.07.8`

### Script `Meeting note`

**id**: `5`
**path**: `C:\Users\robertg01\AppData\Roaming\PBE\QOwnNotes\scripts\meeting-note\meeting-note.qml`
**variablesJson**: 
```
{
    "defaultFolder": "Work/Meeting",
    "defaultTags": "meeting",
    "headlinePrefix": "Teammeeting",
    "noteBodyTemplate": "",
    "timeInNoteName": true
}
```
**identifier**: `meeting-note`
**version**: `1.2.0`
**minAppVersion**: `17.05.7`

### Script `@tag tagging in note text (experimental)`

**id**: `6`
**path**: `C:\Users\robertg01\AppData\Roaming\PBE\QOwnNotes\scripts\in-note-text-tagging\in-note-text-tagging.qml`
**variablesJson**: 
```
{
    "tagHighlightColor": "purple",
    "tagMarker": "@"
}
```
**identifier**: `in-note-text-tagging`
**version**: `0.0.8`
**minAppVersion**: `17.09.9`

### Script `Favorite note`

**id**: `7`
**path**: `C:\Users\robertg01\AppData\Roaming\PBE\QOwnNotes\scripts\favorite-note\favorite-note.qml`
**variablesJson**: *empty*
**identifier**: `favorite-note`
**version**: `0.0.1`
**minAppVersion**: `17.05.6`

### Script `Add Multiple tags`

**id**: `8`
**path**: `C:\Users\robertg01\AppData\Roaming\PBE\QOwnNotes\scripts\add-multiple-tags\add-multiple-tags.qml`
**variablesJson**: *empty*
**identifier**: `add-multiple-tags`
**version**: `0.0.1`
**minAppVersion**: `17.06.2`

### Script `Markdown-it markdown parser`

**id**: `9`
**path**: `C:\Users\robertg01\AppData\Roaming\PBE\QOwnNotes\scripts\markdown-it\markdown-it.qml`
**variablesJson**: 
```
{
    "customStylesheet": "",
    "options": "{\n    //html:         false,        // Enable HTML tags in source\n    //xhtmlOut:     false,        // Use '/' to close single tags (<br />)\n    //breaks:       false,        // Convert '\\n' in paragraphs into <br>\n    //langPrefix:   'language-',  // CSS language prefix for fenced blocks\n    //linkify:      false,        // autoconvert URL-like texts to links\n\n    // Enable some language-neutral replacements + quotes beautification\n    //typographer:  false,\n\n    // Double + single quotes replacement pairs, when typographer enabled,\n    // and smartquotes on. Could be either a String or an Array.\n    //\n    // For example, you can use '«»„“' for Russian, '„“‚‘' for German,\n    // and ['«\\xA0', '\\xA0»', '‹\\xA0', '\\xA0›'] for French (including nbsp).\n    //quotes: '\\u201c\\u201d\\u2018\\u2019', /* “”‘’ */\n\n    // Highlighter function. Should return escaped HTML,\n    // or '' if the source string is not changed and should be escaped externaly.\n    // If result starts with <pre... internal wrapper is skipped.\n    //\n    // function (/*str, lang*/) { return ''; }\n    //\n    //highlight: null,\n\n    //maxNesting:   100            // Internal protection, recursion limit\n}"
}
```
**identifier**: `markdown-it`
**version**: `1.3`
**minAppVersion**: `17.08.2`

### Script `Text Highlights`

**id**: `10`
**path**: `C:\Users\robertg01\AppData\Roaming\PBE\QOwnNotes\scripts\text-highlights\text-highlights.qml`
**variablesJson**: 
```
{
    "backgroundColor": "#FFFF00"
}
```
**identifier**: `text-highlights`
**version**: `0.0.3`
**minAppVersion**: `17.06.2`

### Script `Selected Markdown to Slack`

**id**: `11`
**path**: `C:\Users\robertg01\AppData\Roaming\PBE\QOwnNotes\scripts\selected-markdown-to-slack\selected-markdown-to-slack.qml`
**variablesJson**: *empty*
**identifier**: `selected-markdown-to-slack`
**version**: `0.0.1`
**minAppVersion**: `17.05.7`

### Script `Export notes as one HTML file`

**id**: `13`
**path**: `C:\Users\robertg01\AppData\Roaming\PBE\QOwnNotes\scripts\export-notes-as-one-html\export-notes-as-one-html.qml`
**variablesJson**: *empty*
**identifier**: `export-notes-as-one-html`
**version**: `1.0.0`
**minAppVersion**: `18.03.7`

### Script `Fix list numbers`

**id**: `14`
**path**: `C:\Users\robertg01\AppData\Roaming\PBE\QOwnNotes\scripts\fix-list-numbers\fix-list-numbers.qml`
**variablesJson**: *empty*
**identifier**: `fix-list-numbers`
**version**: `1.0.0`
**minAppVersion**: `18.04.3`

### Script `Insert symbol buttons`

**id**: `15`
**path**: `C:\Users\robertg01\AppData\Roaming\PBE\QOwnNotes\scripts\symbol-buttons\symbol-buttons.qml`
**variablesJson**: 
```
{
    "symbolString": "∑ ∫ ∮"
}
```
**identifier**: `symbol-buttons`
**version**: `0.0.1`
**minAppVersion**: `17.05.8`

### Script `Toggle checkbox`

**id**: `16`
**path**: `C:\Users\robertg01\AppData\Roaming\PBE\QOwnNotes\scripts\toggle-checkbox\toggle-checkbox.qml`
**variablesJson**: 
```
{
    "multipleLinesMethod": "cycleIndividually"
}
```
**identifier**: `toggle-checkbox`
**version**: `1.0.0`
**minAppVersion**: `19.3.2`

### Script `Image preview`

**id**: `17`
**path**: `C:\Users\robertg01\AppData\Roaming\PBE\QOwnNotes\scripts\image-preview\image-preview.qml`
**variablesJson**: 
```
{
    "maxWidth": 640
}
```
**identifier**: `image-preview`
**version**: `1.0.0`
**minAppVersion**: `17.11.6`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**AttachmentDialog/geometry** (QByteArray): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**DistractionFreeMode/editorWidthMode** (int): `1`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-3bdec0ed-eb9c-424c-9c9b-b6a76e087531`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/useTabIndent** (QString): `true`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `C:/Users/robertg01/Pictures`
**FileDialog/LastPath-GitExecutable** (QString): `C:/Program Files/Git/bin`
**FileDialog/LastPath-InsertAttachment** (QString): `C:/Users/robertg01/Pictures`
**FileDialog/LastPath-InsertImage** (QString): `C:/Users/robertg01/Pictures`
**FileDialog/LastPath-ScriptSettingsFile-external-note-diff-executablePath** (QString): `C:/Program Files (x86)/Meld`
**ImageDialog/disableCopying** (QString): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-02-18T12:19:52.210`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `ServerNow/New-ServiceNow, ServerNow/Service-Now Improvements, ServerNow/SNow-2.0, Core-Team, ServerNow, App-Support, Dynamic AX`
**MainWindow/noteSubFolderTreeWidgetExpandState-2** (QStringList): `Server Note's, Server Note's/Server Install Guide/Xpenology, Server Note's/Server Install Guide/Ubuntu 16.04, Server Note's/Server Install Guide/Ubuntu 18.04, Server Note's/Server Install Guide/Ubuntu Server 18.04, Desktop Install Guide, Server Note's/Server Install Guide`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Calibri,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Courier New,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Calibri,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/delete-conflicted-database-files** (int): `16384`
**MessageBoxOverride/update-and-restart** (int): `16384`
**NoteHistory-1** (QVariantList): `<variant list with 79 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 63 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `78`
**NoteHistoryCurrentIndex-2** (int): `62`
**OrphanedAttachmentsDialog/geometry** (QByteArray): `<binary data>`
**OrphanedImagesDialog/geometry** (QByteArray): `<binary data>`
**PersistentScripting/MdNT/pyCommand** (QString): *empty*
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**VersionDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `true`
**checkSpelling** (QString): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `false`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `true`
**gitCommitInterval** (int): `600`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): `"%notePath%"`
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `true`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**interfaceStyle** (QString): `Fusion`
**internalIconTheme** (QString): `true`
**itemHeight** (int): `15`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `true`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `true`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `0`
**notesPath** (QString): `C:/Users/robertg01/Nextcloud/Notes/Work`
**notifyAllExternalModifications** (QString): `true`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/ignoreNonTodoCalendars** (QString): `true`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `2`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): `http://cloud.mediafactory.ddns.net/remote.php/dav/`
**ownCloud/todoCalendarCalDAVUsername** (QString): `b2e050ec-0552-4b65-92ed-9ff62cc6d63a`
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**recentNoteFolders** (QStringList): `C:/Users/robertg01/Nextcloud/Notes/Personal, C:/Users/robertg01/Nextcloud/Notes/University, C:/Users/robertg01/Nextcloud/Notes`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `testing images, Teammeeting 2020-02-12T09.38, Note c21e4946-d9a1-4fa2-9396-e4e42f2b3e1a, Note f544b49c-028f-4fa9-b2ce-cd0d30739f16, Prod-Items, Note 9da60577-e0d4-4945-8a7e-8b3a5fffecdf, Table of Cointents, Standard Change Proposal, Change Request - Normal Type, Change Request - Emergency Type, Change Management - Test Plan, Test-Cases Check List, Azure DevOps - Configure a release pipeline, ServiceNow Integration, ServiceNow, workshp, CAF-REPO, Items TODO, items, Enable Open As Administrator On Ubuntu, Enable Open As Administrator On Ubuntu 16.04 | 17.10 | 18.04, Azure CLI, Creating JIRA Projects, Upskilling, Time logging, time`
**savedSearches/noteFolder-2** (QStringList): `Install DSM 6.1-15047 in VirtualBox, theme, KODI Fix, Raspberry Pi with RetroPie, IUnstall Kodi on RetroPie, Themes, Enable Open As Administrator on Ubuntu 16.04 17.10 18.04 Website for Students`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**spellCheckLanguage** (QString): `en_AU`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `true`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, customAction_meetingNote, action_Find_note, action_Print_note_markdown, action_Remove_note, actionDelete_orphaned_images, actionManage_orphaned_attachments, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_note_git_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote, actionCheck_spelling`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_attachment, actionInsert_table, actionInsert_current_time, actionImport_notes_from_text_files`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `actionMarkdown_cheatsheet, action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useUNIXNewline** (QString): `true`
**versionSplitterSizes** (QByteArray): `<binary data>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**webSocketServerService/token** (QString): `rq3BUpTB`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\robertg01\AppData\Roaming`
**ASANY9**: `C:\Program Files\Sybase\SQL Anywhere 9`
**ASANYSH9**: `C:\Program Files\Sybase\Shared`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `NGFBLNV2`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**destination**: `C:\QOwnNotes`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**HOMEDRIVE**: `U:`
**HOMEPATH**: `\`
**HOMESHARE**: `\\rhod-fs-01.live.picklesauctions.com.au\RobertG01$`
**LOCALAPPDATA**: `C:\Users\robertg01\AppData\Local`
**LOGONSERVER**: `\\RHOD-DC-01`
**NUMBER_OF_PROCESSORS**: `8`
**OneDrive**: `C:\Users\robertg01\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Sybase\SQL Anywhere 9\x64;C:\Program Files\Sybase\SQL Anywhere 9\win32;C:\Program Files\Sybase\Shared\win32;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\AOMEI Backupper;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git\cmd;C:\Users\robertg01\AppData\Local\Microsoft\WindowsApps;;C:\Users\robertg01\AppData\Local\Programs\Microsoft VS Code\bin`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 142 Stepping 10, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `8e0a`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PROMPT**: `$P$G`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**qownnotesCommand**: `C:\QOwnNotes\QOwnNotes.exe --after-update C:\Users\robertg01\AppData\Local\Temp\QOwnNotes-aVYaZg-updater.bat `
**SESSIONNAME**: `Console`
**source**: `C:\Users\robertg01\AppData\Local\Temp\QOwnNotes-aVYaZg.zip`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\ROBERT~1\AppData\Local\Temp`
**TMP**: `C:\Users\ROBERT~1\AppData\Local\Temp`
**unzipCommand**: `C:\Users\robertg01\AppData\Local\Temp\QOwnNotes-aVYaZg-unzip.exe -o C:\Users\robertg01\AppData\Local\Temp\QOwnNotes-aVYaZg.zip -d C:\QOwnNotes`
**unzipExecutable**: `C:\Users\robertg01\AppData\Local\Temp\QOwnNotes-aVYaZg-unzip.exe`
**USERDNSDOMAIN**: `LIVE.PICKLESAUCTIONS.COM.AU`
**USERDOMAIN**: `LIVE`
**USERDOMAIN_ROAMINGPROFILE**: `LIVE`
**USERNAME**: `robertg01`
**USERPROFILE**: `C:\Users\robertg01`
**windir**: `C:\WINDOWS`

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by docfactory37** [comment]
If images are existing they are bing displayed this is only for now images

**Comment by Waqar144** [comment]
The images are local or from internet? If they are from internet, can you share the link?

**Comment by pbek** [comment]
I can't reproduce that.

Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging.

Can you please attach those two images from your media folder here.

**Comment by docfactory37** [comment]
> The images are local or from internet? If they are from internet, can you share the link?

the images are local stored in the default media folder for that note space

**Comment by docfactory37** [comment]
@pbek if i copy and image for the web and past with Ctrl -> Shift -> V i get the below logs

`[09:12:08] [status] Downloading https://images-na.ssl-images-amazon.com/images/I/316IOIzHq7L._AC_SY400_.jpg
[09:12:08] [status] Downloading images finished
[09:12:08] [status] Notes directory was modified externally
[09:12:08] [status] Stored 1 note(s) to disk`

if i insert for local i get the below.

`[09:13:55] [status] Stored 1 note(s) to disk
[09:14:35] [status] Stored 1 note(s) to disk`

**Comment by pbek** [comment]
@docfactory37, can you please attach those two images from your media folder here.

> @pbek if i copy and image for the web and past with Ctrl -> Shift -> V i get the below logs

which webpage?

**Comment by docfactory37** [comment]
@pbek i had done some investiagion and it look like it in issolated the my work PC i have tryed it on my personal pc and have had no issue.

is there away to remove Cache?

**Comment by pbek** [comment]
Great!

> is there away to remove Cache?

there is no persistent cache

**Comment by pbek** [comment]
but since you didn't ever post those images for inspection it's hard to help you in that case... I still suspect that those images look exactly like in your screenshot

**Comment by docfactory37** [comment]
@pbek the images dose not mater, as this is happening for all images no mater where i get the imges from.
![tree-736885_1280](https://user-images.githubusercontent.com/20963053/74983409-11425000-548a-11ea-8445-040499a2a66c.jpg)

**Comment by docfactory37** [comment]
@pbek i have work out what the issue is lookslike it is a bug see below 

When copying with  `Ctrl -> Shift -> V` or when using inster image butten it constructs the below:

`![media-qDQxyT](../../../media/4656.jpeg)`

where is should be constructing with the below:

`![media-qDQxyT](file://media/4656.jpeg)`

i have tested this and once i have change to `file://` im able to see the image in the previewer.

**Comment by pbek** [comment]
Ah, I see. Your script `Markdown-it markdown parser` seems to blocking those. You might want to try switching to legacy linking in the *General settings* to get the old media links when inserting images (or turn off the script).

**Comment by docfactory37** [comment]
Thank you @pbek found it, now it is working again.

**Comment by pbek** [comment]
Great 😁
