### ISSUE TITLE
Edit encrypted note shortcut doesn't seem to work

### ISSUE THREAD

**Issue by truthsword** [pbek/QOwnNotes#1637]
When I select an encrypted note and press Crtl-Shift-E, nothing happens. Am I overlooking something?

Latest QON/Win10 on board.

**Comment by pbek** [comment]
I get the dialog to enter the password.

Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging.

**Comment by truthsword** [comment]
I get this from the log panel...
[09:40:51] [warning] QAction::event: Ambiguous shortcut overload: Ctrl+Shift+E
[09:40:52] [warning] QAction::event: Ambiguous shortcut overload: Ctrl+Shift+E

**Comment by pbek** [comment]
Seems like you have it already assigned. 😁

**Comment by truthsword** [comment]
How would I find that?

**Comment by pbek** [comment]
:laughing:

**Comment by pbek** [comment]
I guess I will remove the 2nd shortcut. Or do you have proposal for a shortcut for one of the two?

**Comment by truthsword** [comment]
> do you have proposal for a shortcut for one of the two?

Not really. My mail client uses Ctrl-Shift-A for attachments, but you're using that for "Find Action" (I'm not sure what that is).

Just don't delete the edit encrypted shortcut... I "forgot" a password the other day, and had to try several. Mousing through the menus was exhausting, lol.

**Comment by pbek** [comment]
> Just don't delete the edit encrypted shortcut...

If you don't find another good shortcut then it needs to go :stuck_out_tongue_closed_eyes: :grin: 

> I "forgot" a password the other day, and had to try several. Mousing through the menus was exhausting, lol.

then "Find action" is exactly what you need! :laughing:

**Comment by pbek** [comment]
## 20.2.9
- the default shortcut for `Insert attachment` was changed to <kbd>Ctrl + Shift + X</kbd>
  because of clashing with `Edit encrypted note`
    - please visit [QOwnNotes shortcuts](https://www.qownnotes.org/shortcuts/QOwnNotes)
      for a list of all shortcuts

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by truthsword** [comment]
Works fine... Both shortcuts tested and work as expected.

Thank you Patrizio 🍺

**Comment by pbek** [comment]
Great, thank you for testing! :smile:
