### ISSUE TITLE
Crash when entering css code

### ISSUE THREAD

**Issue by Kakupakat** [pbek/QOwnNotes#1638]
Adding the following code causes qownnotes to crash:

\```css

.post, .hentry {border-bottom:15px solid #f2f2f2;} 

\```

#### Expected behaviour

Code is added to the note and highlighted.

#### Actual behaviour

QOwnNotes crashes.

#### Steps to reproduce

Write or paste the code above in a note.

**Comment by Waqar144** [comment]
Confirmed

**Comment by pbek** [comment]
## 20.2.10
- fixed a possible crash with the CSS code block highlighter
  (for [#1638](https://github.com/pbek/QOwnNotes/issues/1638), thank you @Waqar144)

There now is a new release, could you please test it and report if it works for you?

**Comment by Kakupakat** [comment]
In 20.2.10 entering the above css code does not cause a crash anymore.
Thank you for the quick fix!

**Comment by pbek** [comment]
Great, thank you for testing!
