### ISSUE TITLE
Enhancement: styling preview

### ISSUE THREAD

**Issue by rootion** [pbek/QOwnNotes#164]
Hello,

Thanks so much for this fantastic app. I felt in love with it and immediately ditched evernote :-)

Is it possible to offer more options to customize the view in the preview mode? I tried in ubuntu and windows 7, they both look slightly different, and I can specify the font-family and font-size in options but I can't specify line-height or how certain elements are going to be rendered. The quote preview in windows for me looks strange, it almost doesn't look like a quote and it's not easy to read.

I work as a designer & front-end developer and unfortunately I can only think in terms of css and stylesheets at the moment—I am obviously aware that's not the way an .exe application works. But is there room for contributions in terms of visual enhancement and styling? If so, I will happy to contribute.

**Comment by pbek** [comment]
Thank you very much for your kind words!

When you say "quote" you you mean to preview of `> quoted text`?
Right now the preview is no fully fledged web-browser but only a [QTextBrowser](http://doc.qt.io/qt-5/qtextbrowser.html) with a very limited subset of CSS: <http://doc.qt.io/qt-5/richtext-html-subset.html>

I'm not sure yet if we should migrate to a full web-browser (and increase the size of the app dramatically).

You can however provide some stylesheets for the current preview (and possibly even one for a future fully fledged web-browser version).

**Comment by pbek** [comment]
If you want to play around with the styling build QOwnNotes yourself:
<http://www.qownnotes.org/installation#building>
and take a look at `QString Note::toMarkdownHtml` at <https://github.com/pbek/QOwnNotes/blob/develop/src/entities/note.cpp#L782>
This is where the preview styling happens.

**Comment by pbek** [comment]
In version 16.05.15:

- there now is a new scripting hook `noteToMarkdownHtmlHook(note, html)`
  that is called when the markdown html of a note is generated
  (for [Issue #164](https://github.com/pbek/QOwnNotes/issues/164))
    - it allows you to modify this html
    - this is for example called before by the note preview
    - there is an example call in
      [example.qml](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/example.qml)

Now you could easily play around with the CSS styles...

**Comment by rootion** [comment]
Fantastic, thanks a lot for the update. I am swamped with work at the moment, but I will play around with css when I have a bit of time and report back.

**Comment by rootion** [comment]
Unfortunately I didn't manage to modify any css. I got stuck trying to build the souce using Qt Creator as the installation guide specifies (Qt crashes constantly in Ubuntu 14.04 when I try to open the source file). 

Could you generate maybe a html output and give me a base stylesheet so I could play around with that and send it back?

**Comment by pbek** [comment]
You don't need to compile QOwnNotes to use above scripting examples. You just load the script in the scripting settings at runtime.
Plus you can also export a note as html (although the generated html is a bit different that the one used in the preview).

**Comment by pbek** [comment]
I will close this issue until there is more information.

**Comment by Siedlerchr** [comment]
QT has the new QTWebEngine module which could be used as a replacement for the QTextBrowser, it supports also javascript:
http://doc.qt.io/qt-5/qtwebengine-overview.html

Don't know if that's much effort, but would be very cool.

**Comment by pbek** [comment]
> QT has the new QTWebEngine

I know and it only works from Qt 5.4 on. QOwnNotes also supports Qt 5.3 (mainly for Debian 8.0).
QtWebEngine doesn't yet support printing (and exporting) and it will eat up a lot of RAM, not everyone would like that. QtWebEngine does need opengl, I've no idea if that will add some additional troubles...
The old QWebView is practically deprecated...

**Comment by Siedlerchr** [comment]
Ah okay. Thanks for clarification 👍  Better to wait until it gets better and more supported.
