### ISSUE TITLE
Every 2nd note folder reload there are no notes in the note list

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1640]
Every 2nd note folder reload (also manually via shortcut) there are no notes in the note list.
I'm seeing this today for the first time on multiple boxes.
@Waqar144, do you also have this issue?
Is this some Qt 5.14.1 thing? I also have some strange issue in the settings dialog which I already fixed in https://github.com/pbek/QOwnNotes/commit/980337a3dcaf59d9b360d1657eedd139fbf47c63.

## General Info

**Version**: `20.2.10`
**Build date**: `Feb 25 2020`
**Build number**: `677`
**Platform**: `linux`
**Operating System**: `Manjaro Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.14.1`
**Qt Version (runtime)**: `5.14.1`
**Portable mode**: `no`

**Comment by pbek** [comment]
I'm not having this issue if the app was built on Qt 5.9.5, but only runs on Qt 5.14.1.

**Comment by pbek** [comment]
@Waqar144, I "git bisect"ed the problem back to your https://github.com/pbek/QOwnNotes/pull/1636, the commit before I merged your PR it is working if built on Qt 5.14.1.

**Comment by pbek** [comment]
`MainWindow::buildNotesIndexAndLoadNoteDirectoryList` is the method you want to look at

**Comment by pbek** [comment]
@Waqar144, I found the culprit, see https://github.com/pbek/QOwnNotes/commit/3ab7f96d05fda057f7f039158ee4aff65fca9c2d

Do you care to take a closer look at that? The currently used code is now deprecated (I guess that's you tried to fix).

**Comment by pbek** [comment]
## 20.2.11
- fixed a note folder reload problem if application was built on Qt 5.14 or higher

**Comment by Waqar144** [comment]
> @Waqar144, I found the culprit, see [3ab7f96](https://github.com/pbek/QOwnNotes/commit/3ab7f96d05fda057f7f039158ee4aff65fca9c2d)
> 
> Do you care to take a closer look at that? The currently used code is now deprecated (I guess that's you tried to fix).

Yes, but it's incorrectly implemented by me. I will fix that 😬

PS: Sorry for the delay

**Comment by pbek** [comment]
:tada: :laughing:

**Comment by pbek** [comment]
Still on my radar. :grin:
