### ISSUE TITLE
Strike through highlighting in markdown links

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1642]
@Waqar144, I saw that there is strike through highlighting in markdown links.

```markdown
- <http://test.com?parameter=~strike~>
- [test](http://test.com?parameter=~strike~)
```

![image](https://user-images.githubusercontent.com/1798101/75427579-10f0fb80-5947-11ea-8d28-03b5a91d32d9.png)

## General Info

**Version**: `20.2.11`
**Build date**: `Feb 26 2020`
**Build number**: `678`
**Platform**: `linux`
**Operating System**: `KDE neon User Edition 5.18`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.9.5`
**Qt Version (runtime)**: `5.14.1`
**Portable mode**: `no`

**Comment by Waqar144** [comment]
> @Waqar144, I saw that there is strike through highlighting in markdown links.
> 
> ```gfm
> - <http://test.com?parameter=~strike~>
> - [test](http://test.com?parameter=~strike~)
> ```
> 
> ![image](https://user-images.githubusercontent.com/1798101/75427579-10f0fb80-5947-11ea-8d28-03b5a91d32d9.png)
> ## General Info
> 
> **Version**: `20.2.11`
> **Build date**: `Feb 26 2020`
> **Build number**: `678`
> **Platform**: `linux`
> **Operating System**: `KDE neon User Edition 5.18`
> **Build architecture**: `x86_64`
> **Current architecture**: `x86_64`
> **Release**: `Launchpad PPA`
> **Qt Version (build)**: `5.9.5`
> **Qt Version (runtime)**: `5.14.1`
> **Portable mode**: `no`

Where did you even find links like that? 😅😅

I will look into this. I fear this would be tough to crack. 😬

Ideally this would be fixed if we implement a proper links parser.

**Comment by pbek** [comment]
> Where did you even find links like that?

In an api url for the Alma library system we use at TU Graz :smile: 

> I will look into this. I fear this would be tough to crack. grimacing

then you are exactly the right man for the job :laughing:

**Comment by pbek** [comment]
## 20.3.0
- fixed strike-through highlighting being applied to links
  (for [#1642](https://github.com/pbek/QOwnNotes/issues/1642), thank you @Waqar144)

**Comment by pbek** [comment]
Thank you, @Waqar144, it works great (if the the links are marked as links via markdown). So `http://test.com?parameter=~strike~` is still striked out (as you mentioned).
