### ISSUE TITLE
Color Hightling preview messes up with PlantUML plugin

### ISSUE THREAD

**Issue by Beurt** [pbek/QOwnNotes#1643]
Hi,

I discovered that the color highlighting is messing up PlantUML.

For instance, 

~~~

```plantuml
@startgantt
[Prototype design] lasts 13 days and is colored in Lavender/LightBlue
[Test prototype] lasts 9 days and is colored in Coral/Green and starts 3 days after [Prototype design]'s end
[Write tests] lasts 5 days and ends at [Prototype design]'s end
[Hire tests writers] lasts 6 days and ends at [Write tests]'s start
[Init and write tests report] is colored in Coral/Green
[Init and write tests report] starts 1 day before [Test prototype]'s start and ends at [Test prototype]'s end
@endgantt

```
~~~
Should render as: 

![gantt-diagram-ihqvgvsm](https://user-images.githubusercontent.com/12588136/75547259-c8ab0980-5a2a-11ea-9479-f019e0c4ea92.png)

And is rendering as:

![165_1](https://user-images.githubusercontent.com/12588136/75547278-d1034480-5a2a-11ea-8f63-927a4f4ecce1.png)

As you can see, the span added for syntax highlighting (`<span class="code-literal">` and so on) is responsible for altering the rendering of PlantUML.

For that reason PLantUML plugin is not working anymore (any kind of graph).

**Comment by pbek** [comment]
Can you please explain in more detail and step by step what you did, what happened and what you expected.

**Comment by pbek** [comment]
(see issue template)

**Comment by Waqar144** [comment]
Ah.
I guess we'll have to turn code-highlighting off for `plantuml`

**Comment by Beurt** [comment]
@pbek 

With the plugin PlantUML active:

Create a note.

Copy-paste the following:
 ~~~

```plantuml
@startgantt
[Prototype design] lasts 13 days and is colored in Lavender/LightBlue
[Test prototype] lasts 9 days and is colored in Coral/Green and starts 3 days after [Prototype design]'s end
[Write tests] lasts 5 days and ends at [Prototype design]'s end
[Hire tests writers] lasts 6 days and ends at [Write tests]'s start
[Init and write tests report] is colored in Coral/Green
[Init and write tests report] starts 1 day before [Test prototype]'s start and ends at [Test prototype]'s end
@endgantt

```

~~~

The plantUML rendering is broken (see the snapshots in https://github.com/pbek/QOwnNotes/issues/1643#issue-572725230 )

@Waqar144 

Maybe we can turn it off in PlantUML plugin?

**Comment by Waqar144** [comment]
> Maybe we can turn it off in PlantUML plugin?

Nah.

It was being incorrectly interpreted as C++ lol
Will be fixed in the next release

**Comment by Beurt** [comment]
OK. @Waqar144 

Thanks. I'm waiting the release.

**Comment by pbek** [comment]
## 20.3.0
- fixed cpp being used for unknown code block languages in the note edit highlighter
  (for [#1643](https://github.com/pbek/QOwnNotes/issues/1643), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Beurt** [comment]
Thank you, I'm waiting for the 20.3.0 [appimage](https://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/AppImage/)¹ to be released. I keep you posted ASAP.

¹: My Linux distrib' is Mageia

**Comment by pbek** [comment]
It is already released on https://build.opensuse.org/package/binaries/home:pbek:QOwnNotes/desktop/AppImage

**Comment by pbek** [comment]
@Beurt, since OBS supports Mageia I tried to enable the builders for QOwnNotes but the Qt libraries are not found, see https://build.opensuse.org/package/show/home:pbek:QOwnNotes/desktop

If you want to tinker with https://build.opensuse.org/package/view_file/home:pbek:QOwnNotes/desktop/qownnotes.spec?expand=1 and are able to add Mageia support to it ping me. :wink:

**Comment by Beurt** [comment]
Thank you!

You don't need to add support for Mageia, Appimage is fine for me (indeed I prefer, for many odd reasons QownNotes as an appimage than a regular packet).

Thanks to https://build.opensuse.org/package/binaries/home:pbek:QOwnNotes/desktop/AppImage, I was able to test 2.30.0 and PlantUML plugin is still not working very well. After some investigations I think that it is still related to the way QOwnNotes handles quoted content.

For instance, copy-pasting in a note the following (it is an [example from the PlantUML website](https://plantuml.com/en/gantt-diagram))

~~~
```plantuml
@startgantt
[Prototype design] lasts 13 days and is colored in Lavender/LightBlue
[Test prototype] lasts 9 days and is colored in Coral/Green and starts 3 days after [Prototype design]'s end
[Write tests] lasts 5 days and ends at [Prototype design]'s end
[Hire tests writers] lasts 6 days and ends at [Write tests]'s start
[Init and write tests report] is colored in Coral/Green
[Init and write tests report] starts 1 day before [Test prototype]'s start and ends at [Test prototype]'s end
@endgantt

```
~~~

Ends up with a render error from PlantUML.

My first investigation shows that some characters crash the PlantUML render, such as `/` (slash) or `'` (single quote). I'm wondering if these characters are now escaped or transformed to entities by QOwnNotes?

**Comment by Beurt** [comment]
Further investigation shows that quoted text special characters are converted to numerical entities during HTML transformation for preview (maybe by https://github.com/pbek/QOwnNotes/blob/develop/src/helpers/codetohtmlconverter.cpp, but I am not sure since C++ is not my strong suit).

I am not sure what is the correct course with that information? I think modifying the [PlantUML support script](https://github.com/Beurt/Qownnotes-scripts/tree/master/render-plantuml) is not that easy since it needs to restore characters from entities (not that easy with QML I guess) or to use another hook ([preNoteToMarkdownHtmlHook](https://docs.qownnotes.org/en/develop/scripting/README.html#prenotetomarkdownhtmlhook)) which means rewriting most of the code (and I’m not sure considering my current knowledge to be able to do that).

I can’t get a grasp on the reason why, in the first place, there is a conversion of special characters to entities for every quoted text?

**Comment by Waqar144** [comment]
Conversion to HTML entities is very important for the preview. If we don't do it, it can be considered as 'html code', which can lead to incorrect rendering of the code text.

That being said, we can certainly make an exception for plantuml so that it doesn't get escaped and is returned as is.

It might take a little while for me to push the changes as I am away from my pc so, if you are eager you can try to fix it yourself. It's pretty easy and straightforward.

You just need to add another `case` for `PlantUML` like so
```cpp
//file: CodeToHtmlConverter.h
Langs{
...
CodePlantUML
}

...
//file: CodeToHtmlConverter.cpp
initCodelangs(){
... 
{QStringLiteral("plantuml"), CodeToHtmlConverter::CodePlantUML}};

... 

//in func process() 
case CodePlantUML:
return _input.toQString();
```

**Comment by Beurt** [comment]
Thanks for your answer @Waqar144 !

Some conversion to HTML entities was already done by QOwnNotes before. It was working fine with PLantUML because the PlantUML support plugin has some code to transform some entities back to standard characters: https://github.com/Beurt/Qownnotes-scripts/blob/master/render-plantuml/render-plantuml.qml#L87). My understanding is that now **all** the special characters are transformed instead of only some of the ones used by HTML tags (`<`, `>`, `"`, `'`, `/`, `&` at least). It implies transforming back all entities, and I can’t find any QML built-in function to help with that.

I’m not sure if the wisest option is to create an exception for PlantUML in CodeToHtmlConverter.h. I mean, some other plugin could need to postprocess quoted text for other purposes than PlantUML plugin.

Maybe the best course of action for now is to make deep changes to the PlantUML plugin in order to use preNoteToMarkdownHtmlHook. I’m a bit busy this week, but I will try to look into that much transformation of the plugin ASAP.

**Comment by Beurt** [comment]
I made a clumsy pull request on the plugin for the PlantUML support here https://github.com/qownnotes/scripts/pull/80 that should solve the issue without changing CodeToHtmlConverter.h.

**Comment by Beurt** [comment]
I updated the plugin from QOwnNotes, and everything works fine. Thanks @pbek and @Waqar144 !
