### ISSUE TITLE
Improve CSS support by upgrading to Qt >= 5.14.1

### ISSUE THREAD

**Issue by ky7749** [pbek/QOwnNotes#1646]
I have been playing with the script 'Custom note preview styling'. Ultimately it amounts to writing some custom CSS.

Current QOwnNotes (20.3.0) was compiled against Qt 5.13.2 which does not support some CSS properties; for example border-collapse. See [here](https://doc.qt.io/archives/qt-5.13/richtext-html-subset.html).

It seems that Qt 5.14.1 does support it, among others. see: [here](https://doc.qt.io/qt-5/richtext-html-subset.html).

So by upgrading Qt to the said version (at least), CSS support will be improved for free.

**Comment by pbek** [comment]
Thank you for letting us know.
But since you didn't fill out the issue template (😉 ) I have no idea on which platform you are running QOwnNotes.

**Comment by pbek** [comment]
For example on KDE Neon or Manjaro Linux I run QOwnNotes with Qt 5.14.1...

**Comment by ky7749** [comment]
Sorry didn't fill in the issue template, because it looked like to be designed for bug reporting - mine is more like a feature request.

Anyway I run QOwnNotes 20.3.0 on Windows 10 Enterprise LTSC v1809 x64.

A newer Qt version 5.14.**2** is to be released in March. Hopefully it won't have too many memory leaks.

**Comment by pbek** [comment]
> Sorry didn't fill in the issue template, because it looked like to be designed for bug reporting - mine is more like a feature request.

Still I need to know what we are talking about. :grin: 
The *Help* menu in QOwnNotes helps you with filing feature requests (as stated in the issue template). :wink: 

> Anyway I run QOwnNotes 20.3.0 on Windows 10 Enterprise LTSC v1809 x64.

Thank you.
QOwnNotes for Windows is built on https://ci.appveyor.com/project/pbek/qownnotes.
AppVeyor is still at Qt 5.13.2, but you can always switch out the Qt DLLs yourself or also build it yourself until 5.14 arrives.

See: https://www.qownnotes.org/installation#building
