### ISSUE TITLE
import folder

### ISSUE THREAD

**Issue by pipiscrew** [pbek/QOwnNotes#1647]
hi all,

The **import text** files working well, currently there is a need to import ~2500 text files from **multiple folders & subfolders**.... Copying into dbase folder, doing nothing as records have to be added into SQLite dbase... 

Assuming, that the physical folder structure will added as tag & sub tags, for example :

when we have 
> c:\test\html\javascript\arrays

and user selects the **test** folder, will create **tags** as : 

> parent - html
> ^---- items - files[]
> subnode1 - javascript
> ^---- items - files[]
> subnode2 - arrays
> ^---- items - files[]

waiting for your thoughts

**Comment by pbek** [comment]
Can you please post the output from the debug settings (see issue template).
And I'm not very sure how your note files you are trying to add look like. Are they markdown files? Do you have some examples of the content of the files?

**Comment by pipiscrew** [comment]
clone 
https://github.com/pipiscrew/code_snippets

all are plain text files with extension **.js**, rename it all to **.md**.

I dont know what you mean by 
>  post the output from the debug settings (see issue template)

thank you

**Comment by pbek** [comment]
Are you intending to use QOwnNotes to work with JavaScript files? I don't think it's the best tool for that job. QON is meant to work with Markdown files.

If you still insist to use QON for JavaScript files you can simple tell QON to also use `js` files in the settings. And you also can set that the headline and the filenames are not connected. Then you can work with the `js` files directly.

**Comment by pipiscrew** [comment]
how can I adjust this setting^ ? Will still have the folder structure (as tags) ?

**Comment by pbek** [comment]
> how can I adjust this setting^ ?

in the settings dialog, it has a search function

> Will still have the folder structure (as tags) ?

yes and no, the folder structure will be a (note sub-)folder structure in QON

**Comment by pipiscrew** [comment]
I see^.

Seems in that way, the **folders** is not getting read, as result is not appear on the list... :( 

lists only the **root** file items.

**Comment by pbek** [comment]
You still haven't shared the output from your *Debug settings*, so it's hard to tell what you are doing. But I suspect you might not have turned on sub-folder support for your note folder.

**Comment by pipiscrew** [comment]
Hi @pbek,

done.

![778](https://user-images.githubusercontent.com/3852762/75707106-ff04b500-5cc6-11ea-9a46-dbe555491c77.png)


thank you for your time.

**Comment by pbek** [comment]
Great! :grin:
