### ISSUE TITLE
Inline code will not get highlighted if link is in same line

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1649]
@Waqar144, inline code will not get highlighted if link is in same line.

#### Expected behaviour

```markdown
<http://alink.com> with `inline code`
```

#### Actual behaviour

![image](https://user-images.githubusercontent.com/1798101/75789264-b520db00-5d69-11ea-8a3d-2dbc077e01c4.png)

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

## General Info

**Version**: `20.3.0`
**Build date**: `Feb 29 2020`
**Build number**: `679`
**Platform**: `linux`
**Operating System**: `KDE neon User Edition 5.18`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.9.5`
**Qt Version (runtime)**: `5.14.1`
**Portable mode**: `no`
</details>

**Comment by Waqar144** [comment]
I think this is somehow related to the recent change I did for the strike through link

**Comment by pbek** [comment]
Thank you very much, @Waqar144!
