### ISSUE TITLE
Table of content scrolling doesn't work in markdown mode

### ISSUE THREAD

**Issue by dasmaetthes** [pbek/QOwnNotes#165]
Table of contents scroll to content works only in edit mode but not in markdown mode

**Comment by pbek** [comment]
Thank you for your report.
If you mean the note preview with "markdown mode"...
Are you sure you are testing the latest version of QOwnNotes? This was already fixed a few releases ago.

**Comment by dasmaetthes** [comment]
Yes I mean the note preview.
I was testing it with 16.05.6 release

**Comment by pbek** [comment]
So you clicked on a headline in the navigation bar and it didn't scroll in the note preview?

**Comment by dasmaetthes** [comment]
Yes, it was only scrolling in edit mode

**Comment by pbek** [comment]
Thank you, I will test that when I'm at my desk again.

**Comment by pbek** [comment]
I'm sorry, I could not reproduce your problem under Windows 8.1 with QOOwnNotes 16.05.7. Jumping to headlines works fine in the preview. Can you please test if with 16.05.7 on your and possibly other computers too or provide some additional information.

**Comment by dasmaetthes** [comment]
Okay, it seems to workmost of time.
When it doesn't work is:
 1. Open QOwnNotes (only preview mode is active)
 2. Change size of window
 3.Click a headline in navigation bar

**Comment by pbek** [comment]
I could reproduce that also on Linux. If the note textedit wasn't active at least once the jumping doesn't work. Thanks for the report, I will look into that.

**Comment by pbek** [comment]
This should be fixed in the just released version 16.05.8. Could you please test it and report back?

**Comment by dasmaetthes** [comment]
Now it works well

**Comment by pbek** [comment]
Great to hear! Thank you for reporting and testing!
