### ISSUE TITLE
RFE: after delete of note, do not jump to the top

### ISSUE THREAD

**Issue by btong** [pbek/QOwnNotes#1650]
Wow what an app!

I am currently importing a lot of notes to QOwnNotes. It's great. Could the behaviour be tweaked so that when I delete a note, I don't lose my place? I have tried changing sorting to by name, but when I delete a note I would like to stay where I am in the list of notes (or one below). Thanks.

p.s. maybe there could also be a no-sort option for when doing lots of changes at once, then I won't lose my place so easily.

**Comment by pbek** [comment]
> I am currently importing a lot of notes to QOwnNotes. It's great. Could the behaviour be tweaked so that when I delete a note, I don't lose my place? I have tried changing sorting to by name, but when I delete a note I would like to stay where I am in the list of notes (or one below). Thanks.

most of the time removing a note triggers the note folder to be reloaded because of changes in the folder which causes the top most note to be selected, it will be hard to improve on that... I'll put it on my todo list. :grin: 

> p.s. maybe there could also be a no-sort option for when doing lots of changes at once, then I won't lose my place so easily.

what is "no-sort"? a list always has an order :grinning:

**Comment by btong** [comment]
> what is "no-sort"? a list always has an order grinning

While I am reordering my mass of notes with bad titles, etc. I would like the order to stay as it is, not sorted by date or title. I'd like to work my way through notes one by one. Maybe there could be a way to sort the notes on demand instead?

**Comment by pbek** [comment]
> Maybe there could be a way to sort the notes on demand instead?

No, sorry. QON has no persistent database of notes. The markdown files in the folders are the "single source of truth".

**Comment by pbek** [comment]
You could try to turn off all detection of note folder changes temporary until you are done. But I'm not 100% sure if some reloads will be triggered anyway.

**Comment by pbek** [comment]
## 20.3.2
- when removing single or multiple notes the note folder will now not be reloaded,
  instead the notes will just be removed in the note list and the next existing
  note will be selected

**Comment by pbek** [comment]
> p.s. maybe there could also be a no-sort option for when doing lots of changes at once, then I won't lose my place so easily.

you can also sort alphabetically

> Maybe there could be a way to sort the notes on demand instead?

or I would just jump to the last item in the note list and change the name of that item if you want to give all your notes new headlines...

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by btong** [comment]
Works great - thanks a lot!

**Comment by pbek** [comment]
Great, thank you for testing!
