### ISSUE TITLE
Icons missing at KDE

### ISSUE THREAD

**Issue by 2Fake** [pbek/QOwnNotes#1652]
#### Expected behaviour
All icons displayed

#### Actual behaviour
Some icons are missing
![image](https://user-images.githubusercontent.com/17730741/76216418-db82c280-6210-11ea-9d2c-c9601ac2aa14.png)

#### Steps to reproduce
Open qownnotes

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mo. März 9 14:17:52 2020`
**Version**: `20.3.2`
**Build date**: `Mar  6 2020`
**Build number**: `681`
**Platform**: `linux`
**Operating System**: `Ubuntu 18.04.4 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.9.5`
**Qt Version (runtime)**: `5.9.5`
**Portable mode**: `no`
**Settings path / key**: `/home/Markus.Bong/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/Markus.Bong/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `42`
**Calendar items**: `38`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://nc.famabo.de`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `17.0.3.1`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `de_AT, de_AT_frami, de_CH, de_CH_frami, de_DE, de_DE_frami, en_US`
**Language names**: `Österreichisches Deutsch (Österreich), Österreichisches Deutsch (Österreich), Schweizer Hochdeutsch (Schweiz), Schweizer Hochdeutsch (Schweiz), Deutsch (Deutschland), Deutsch (Deutschland), American English (United States)`
**Application dictionaries path**: `/home/Markus.Bong/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `2`

### Note folder `Standard`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/Markus.Bong/Nextcloud/Lokal/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `devolo`
**database file**: `/home/Markus.Bong/Nextcloud/Lokal/Notes/notes.sqlite`

### Note folder `Standard`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/Markus.Bong/Nextcloud/Lokal/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `Allgemein`
**database file**: `/home/Markus.Bong/Nextcloud/Lokal/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://nc.famabo.de`
**username**: `markus`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**LastUpdateCheck** (QDateTime): `2020-03-09T14:16:24`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-2** (QStringList): `Betriebliche Informationssysteme`
**MainWindow/noteTextEdit.code.font** (QString): `Hack,9,-1,7,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Hack,9,-1,7,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/share-sync-information** (QString): `1024`
**NoteHistory-1** (QVariantList): `<variant list with 3 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 44 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `2`
**NoteHistoryCurrentIndex-2** (QString): `43`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (QString): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-actionSwitch_to_previous_workspace** (QString): `F3`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `2`
**currentWorkspace** (QString): `0260845e-a855-4aac-a8d9-bb397fa01be0`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `24`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `false`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/Markus.Bong/Nextcloud/Lokal/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Persönlich, Arbeit`
**ownCloud/todoCalendarEnabledList** (QStringList): `Persönlich, Arbeit`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://nc.famabo.de/remote.php/dav/calendars/markus/personal/, https://nc.famabo.de/remote.php/dav/calendars/markus/arbeit/`
**ownCloud/todoCalendarUrlList** (QStringList): `https://nc.famabo.de/remote.php/dav/calendars/markus/personal/, https://nc.famabo.de/remote.php/dav/calendars/markus/arbeit/`
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unbekannter Fehler`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `17.0.3.1`
**previousWorkspace** (QString): `initial`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**savedSearches/noteFolder-2** (QStringList): `Note 2020-03-03T18.01.09, Note 2020-03-03T18.00.47, Note 2020-02-27T13.48.18, Note 2020-02-27T09.41.26, Note 2020-02-06T10.35.10, Note 2020-01-24T09.03.55, Note 2019-10-30T15.59.51, Note 2019-10-01T20.51.53`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Hauptsymbolleiste`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `Formatierungs-Werkzeugleiste`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `Einfügen-Werkzeugleiste`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `Werkzeugleiste Verschlüsselung`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `Fenster-Werkzeugleiste`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `Beenden - Symbolleiste`
**toolbar/size** (QString): `6`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-0260845e-a855-4aac-a8d9-bb397fa01be0/name** (QString): `Ansicht`
**workspace-0260845e-a855-4aac-a8d9-bb397fa01be0/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-0260845e-a855-4aac-a8d9-bb397fa01be0/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Vollständig`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 0260845e-a855-4aac-a8d9-bb397fa01be0`

## System environment

**KDE_FULL_SESSION**: `true`
**GS_LIB**: `/home/Markus.Bong/.fonts`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**USER**: `Markus.Bong`
**XDG_SEAT**: `seat0`
**QT_SCREEN_SCALE_FACTORS**: `eDP-1=1;DP-1=1;HDMI-1=1;DP-2=1;HDMI-2=1;DP-1-1-8=1;DP-1-1-1-8=1;DP-1-1-1-1=1;DP-1-1-1=1;DP-1-1=1;DP-1-2=1;DP-1-3=1;`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `1823`
**SHLVL**: `0`
**XCURSOR_SIZE**: `24`
**HOME**: `/home/Markus.Bong`
**DESKTOP_SESSION**: `plasma`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**KDE_SESSION_VERSION**: `5`
**DBUS_SESSION_BUS_ADDRESS**: `unix:abstract=/tmp/dbus-V7zZ2Qd3x1,guid=ba1af65cd04d7d26fc34244d5e663e15`
**LIBVIRT_DEFAULT_URI**: `qemu:///system`
**MANDATORY_PATH**: `/usr/share/gconf/plasma.mandatory.path`
**LOGNAME**: `Markus.Bong`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**DEFAULTS_PATH**: `/usr/share/gconf/plasma.default.path`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_ID**: `3`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**XCURSOR_THEME**: `breeze_cursors`
**DISPLAY**: `:0`
**LANG**: `de_DE.UTF-8`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_SESSION_DESKTOP**: `KDE`
**XAUTHORITY**: `/home/Markus.Bong/.Xauthority`
**SSH_AUTH_SOCK**: `/tmp/ssh-Pv6HO51Ze91u/agent.1743`
**SHELL**: `/bin/bash`
**PAM_KWALLET_LOGIN**: `/run/user/1000/kwallet.socket`
**QT_ACCESSIBILITY**: `1`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**XDG_VTNR**: `1`
**PWD**: `/home/Markus.Bong`
**XDG_DATA_DIRS**: `/usr/share/plasma:/usr/local/share:/usr/share:/var/lib/snapd/desktop`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-plasma:/etc/xdg:/usr/share/kubuntu-default-settings/kf5-settings`
**KDE_SESSION_UID**: `1000`
**SESSION_MANAGER**: `local/L003617UX:@/tmp/.ICE-unix/1884,unix/L003617UX:/tmp/.ICE-unix/1884`
**LANGUAGE**: *empty*

</details>

**Comment by pbek** [comment]
It seems like you are using dark-mode icons (they are very light) together with a non-dark-mode user interface. Just turn off dark-mode icons in the settings.

**Comment by 2Fake** [comment]
Thanks. That solved it

**Comment by pbek** [comment]
Great. :grin:
