### ISSUE TITLE
"Maximum file size exceeded" error for Arch package download from opensuse.org

### ISSUE THREAD

**Issue by boskote** [pbek/QOwnNotes#1653]
#### Expected behaviour
Arch package downloads 

#### Actual behaviour

```
$ sudo pacman -S qownnotes
resolving dependencies...
looking for conflicting packages...

Packages (1) qownnotes-20.3.2-1

Total Download Size:    3.50 MiB
Total Installed Size:  18.68 MiB
Net Upgrade Size:       0.27 MiB

:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
error: failed retrieving file 'qownnotes-20.3.2-1-x86_64.pkg.tar.xz' from download.opensuse.org : Maximum file size exceeded
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.
```

#### Steps to reproduce

`sudo pacman -S qownnotes`

Here is my pacman.conf config block for the opensuse.org repo;
```
[home_pbek_QOwnNotes_Arch_Extra]
SigLevel = Optional TrustAll
Server = http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Arch_Extra/$arch
```
In the meantime, this is my workaround in pacman.conf:
`IgnorePkg   = qownnotes`

Which gives this output:
qownnotes: ignoring package upgrade (20.3.0-1 => 20.3.2-1)

**Comment by pbek** [comment]
Thank you for reporting. OBS has a download problem. The download currently only works when logged in. I now reported that issue in the `#opensuse-buildservice` IRC chat on freenode.

**Comment by pbek** [comment]
I tested today and I was able to download <http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Arch_Extra/x86_64/qownnotes-20.3.2-1-x86_64.pkg.tar.xz>. Do you still have this issue?

**Comment by johnnydvc** [comment]
I do:
Fehler: Konnte Datei 'qownnotes-20.3.2-1-x86_64.pkg.tar.xz' nicht von download.opensuse.org übertragen : Maximum file size exceeded

**Comment by pbek** [comment]
I don't know what is causing your issue on your system.

**Comment by pbek** [comment]
Did you already try the advices from <https://www.reddit.com/r/archlinux/comments/2axo9x/unable_to_update_using_pacman_maximum_file_size/>?

**Comment by boskote** [comment]
> I tested today and I was able to download http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Arch_Extra/x86_64/qownnotes-20.3.2-1-x86_64.pkg.tar.xz. Do you still have this issue?

Same for me, I didn't change anything and now I am able to download the package as expected. Since others are reporting the problem continuing I'm not closing the issue now even though it is resolved for me.

**Comment by pbek** [comment]
@boskote, does `sudo pacman -S qownnotes` now work for you?
@johnnydvc, does it for you?

**Comment by boskote** [comment]
> @boskote, does `sudo pacman -S qownnotes` now work for you?
Yes

**Comment by johnnydvc** [comment]
> @boskote, does `sudo pacman -S qownnotes` now work for you?
> @johnnydvc, does it for you?

Hi, it still deosn't work.
I get the error message
`Fehler: Konnte Datei 'qownnotes-20.3.2-1-x86_64.pkg.tar.xz' nicht von download.opensuse.org übertragen : The requested URL returned error: 404`
Strange

**Comment by pbek** [comment]
> The requested URL returned error: 404

20.3.3 was released meanwhile, so the old file may be gone

> I don't have the curl line in my pacman.conf

what curl line?

**Comment by johnnydvc** [comment]
> > The requested URL returned error: 404
> 
> 20.3.3 was released meanwhile, so the old file may be gone
> 
> > I don't have the curl line in my pacman.conf
> 
> what curl line?
I mean your advice from the reddit post that suggests enabling curl with XferCommand
in the pacman.conf. Mine only has a XferCommand line with wget.

**Comment by pbek** [comment]
Ah, ok. Can't help with that. I use the AUR. :grin:

**Comment by alsternerd** [comment]
> I tested today and I was able to download http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Arch_Extra/x86_64/qownnotes-20.3.2-1-x86_64.pkg.tar.xz. Do you still have this issue?

The issue now exists for 'qownnotes-24.7.2-1-x86_64.pkg.tar.zst on download.opensuse.org : Maximum file size exceeded

**Comment by pbek** [comment]
What did you do to get the error?

`wget http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Arch_Extra/x86_64/qownnotes-24.7.2-1-x86_64.pkg.tar.zst` works just fine for me.

**Comment by alsternerd** [comment]
> What did you do to get the error?
> 
> `wget http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Arch_Extra/x86_64/qownnotes-24.7.2-1-x86_64.pkg.tar.zst` works just fine for me.

At the same time OP got his error, also using pacman. I got this error two ago, too, it worked fine in the meantime, until today.

**Comment by pbek** [comment]
I wonder what Arch does differently... 🤔

**Comment by alsternerd** [comment]
> I wonder what Arch does differently... 🤔

As a longterm Debian user I sadly have no idea, but running into the same thing several times is something.
But yes it works perfectly fine with curl, too.
Maybe there's some problem with the redirect from download.opensuse.org to ftp.gwdg.de or the filesize is not delivered correctly.

**Comment by alsternerd** [comment]
Ah, I think I found it.

The repository database has wring information about the filesize of the package and pacman then tells curl to only download the given size, which brakes if the file is bigger.

Got to it by this comment here: https://github.com/msys2/MSYS2-packages/issues/1025#issuecomment-508950464

**Comment by pbek** [comment]
Hah, interesting!
