### ISSUE TITLE
The option "Show root folder name" doesn't work.

### ISSUE THREAD

**Issue by ShantyHoz** [pbek/QOwnNotes#1654]
#### Expected behaviour
I would like the option "Show root folder name" that is on the path "Setting-Panels" will be works.
#### Actual behaviour
The option "Show root folder name" doesn't work.
#### Steps to reproduce
**1.** The root folder name is "Notes" (by default)
**2.** I checked the option "Show root folder name" on the path "Setting-Panels"
**3.**  The root folder name is "Note folder". It's not hidden now despite I checked option "Show root folder name"
#### Output from the debug section in the settings dialog
Nothing..

![Screen](https://user-images.githubusercontent.com/18642327/76234646-0bdf5680-623b-11ea-9031-bbf726c49098.png)
![Screen](https://user-images.githubusercontent.com/18642327/76234719-21ed1700-623b-11ea-96d6-7d382e79d709.png)

**Comment by pbek** [comment]
Can you please post the output from the debug settings (see issue template).
Seems to work fine for me.

![image](https://user-images.githubusercontent.com/1798101/76239279-9327cc80-6231-11ea-8bd0-a2551342d51c.png)

**Comment by pbek** [comment]
I will close this issue until there is more information.
