### ISSUE TITLE
Location of localization files

### ISSUE THREAD

**Issue by DeadMozay** [pbek/QOwnNotes#1657]
Can I find out why you chose this location for localization files?
`/usr/share/QOwnNotes/languages/`
https://github.com/pbek/QOwnNotes/blob/7ab3e6cd1a46f963011a1e0121790868b66741f8/src/main.cpp#L50
https://github.com/pbek/QOwnNotes/blob/7ab3e6cd1a46f963011a1e0121790868b66741f8/src/main.cpp#L60
qt5 applications default location
`/usr/share/qt5/translations/`
Then they will not need to be installed manually, for rpm distributions it is enough to specify the macro `%find_lang`
then the localization files will be installed and packaged in automatic mode.
there is also no need for the repository to keep compiled localization files, this is best done at compile time with qt5-linguist
`lrelease-qt5 QOwnNotes.pro`
will generate all localizations specified in the file QOwnNotes.pro

**Comment by pbek** [comment]
There was no particular reason beside "it did work", and it still does.
Do you have a specific proposal (best in form of a pull requests to talk about) that doesn't break all build systems and platforms? :grimacing:

**Comment by DeadMozay** [comment]
you can look at my project on OBS, it works, I think that on other platforms problems should not arise either
https://build.opensuse.org/package/show/home:Dead_Mozay/qownnotes

**Comment by pbek** [comment]
On what in particular should I look at?

**Comment by DeadMozay** [comment]
https://build.opensuse.org/package/view_file/home:Dead_Mozay/qownnotes/translations.patch?expand=1
You can see in the specs that the localization files no longer need manual installation
https://build.opensuse.org/package/view_file/home:Dead_Mozay/qownnotes/qownnotes.spec?expand=1
The macro is responsible for the search and installation
`%find_lang QOwnNotes --with-qt`
he searches for localization files and installs them in the right place on his own.
You just need to change the path in main.cpp and edit it wherever it is indicated for building systems, if you want, I can later send a PR, so that you read

**Comment by pbek** [comment]
If you want to send a PR I'll take a look. But things have to work again on all platforms on https://www.qownnotes.org/installation and also in some other places like chocolatey, brew, flathub, ... :grimacing:  that's why I'm "a bit" cautious. :thinking: :grin:

**Comment by DeadMozay** [comment]
https://github.com/pbek/QOwnNotes/pull/1660

**Comment by pbek** [comment]
Let's hope it doesn't break too much. :grimacing:

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
There are as well three new translations (Zulu, Sinhala and Khmer) in it that should only work with the new translation files places, so you can test those translations too.

**Comment by DeadMozay** [comment]
I checked in the same distributions as before, the localization is switched, including new ones that appeared in this release, Everything works 💪

**Comment by pbek** [comment]
Yes, looks good so far. I ask myself if the old translations are removed (so that they may not get priority over updated translations of the same language)

**Comment by pbek** [comment]
`/usr/share/QOwnNotes/languages` was removed when updating from the Launchpad PPA plus you removed the reference to it in `main.cpp`. Great job, thank you very much :+1: I guess we can close this then!
