### ISSUE TITLE
Cannot add key in Arch Linux

### ISSUE THREAD

**Issue by nivaca** [pbek/QOwnNotes#1661]
When I try to add they key in Arch Linux as per your instructions:
`sudo pacman-key --lsign-key FFC43FC94539B8B0`
I get this error:
`==> ERROR: FFC43FC94539B8B0 could not be locally signed.
`
I tried doing this:
```
sudo rm -fr /etc/pacman.d/gnupg
sudo pacman-key --init
sudo pacman-key --populate archlinux
```
but the problem persists.

**Comment by pbek** [comment]
You could try the QOwnNotes release in the AUR

**Comment by nivaca** [comment]
I do, but as there are frequent updates, my system has to compile the application every time.
I prefer the other way (incremental updates, no need to compile), but I cannot manage to do that anymore.

**Comment by pbek** [comment]
Keys and builds are generated by OBS, you could ask in their irc channel on freenode `#opensuse-buildservice`

**Comment by pbek** [comment]
Were you already able to solve your issue?

**Comment by pbek** [comment]
I will close this until there is more information.

**Comment by 5472qaywsx** [comment]
Turns out that "FFC43FC94539B8B0" was possibly wrong?
I extracted the *keyid* with the command `sudo pacman-key --list-keys` and searching for the key from *home: pbek OBS Project* and then I could sign the key.

**Comment by pbek** [comment]
Like I said, I don't think I have control over those key files. They are generated by OBS directly. 😬  I've anyone finds something out please let me know. 

>  instead of giving it explicitly on page https://www.qownnotes.org/installation/arch.html#pacman?

You could edit the documentation yourself (`Help us improve this page!` on the bottom) 😉
