### ISSUE TITLE
Duplicate graphics downloaded

### ISSUE THREAD

**Issue by truthsword** [pbek/QOwnNotes#1664]
I've noticed that some web sites give me duplicate graphics with HTML import... for example...

```
![media-NtaVeC](media/30939.png)
![media-WgXbIC](media/16703.png)
```
When I examine the web page in the browser, there is only one graphic apparent.

Here is an example...
https://www.groovypost.com/howto/hack-rwpfe-water-filters-ge-fridge/

Is this just me?

Win10 x64 QON 20.3.7

**Comment by pbek** [comment]
What HTML import? Can you please explain in more detail and step by step what you did. And do you have a screenshot of your preview?

**Comment by truthsword** [comment]
Load above link in a web browser. Copy page w/QON extension...

![](https://i.imgur.com/8oUTZ9o.png)

QON result:

![](https://i.imgur.com/i0Qqlnp.png)

Nearly every graphic on this page was duplicated in the preview, each with 2 separate files with same image.

**Comment by pbek** [comment]
The image is twice in the html code. I guess that what is causing it...

![image](https://user-images.githubusercontent.com/1798101/77361151-0ca1dd80-6d4f-11ea-9913-dcd3f5b45e40.png)

**Comment by truthsword** [comment]
Ouch! I should have checked for that. 
Here... have a cookie!  🍪 🍪 🍪

**Comment by pbek** [comment]
😆 *munch munch* 🐒 

Shtay shave shoo!
