### ISSUE TITLE
Pasting in vim mode

### ISSUE THREAD

**Issue by dylanpjx** [pbek/QOwnNotes#1665]
I'm using QOwnNotes for Windows

Pasting in vim mode doesn't work as intended. 
Pressing "P" in command mode works only when you cut/yank something from the editor. Pasting from external sources (WIndows clipboard) doesn't work with the vim editor which shouldn't be the behaviour.

**Comment by pbek** [comment]
Thank you for your suggestion. :grin:  Pull requests are welcome.

**Comment by Waqar144** [comment]
have you tried `"+p` or `"*p`?

there's an option to pass control key but i dont think we have it implemented

**Comment by Waqar144** [comment]
There's support for `Passing Control Key` and other stuff such as reading a `vimrc` file. We will need another settings page / group for this. Here's what fakevim settings looks like in QtCreator:

![Screenshot from 2020-06-11 11-32-05](https://user-images.githubusercontent.com/7696024/84352707-44465600-abd7-11ea-9fed-c7321893cd1b.png)

**Comment by pbek** [comment]
@dylanpjx, can you please test @sahensley 's suggestion with version v21.11.10 (see #2247).

**Comment by pbek** [comment]
I will close this issue until there is more information.
