### ISSUE TITLE
Build error with Qt 5.15

### ISSUE THREAD

**Issue by data-man** [pbek/QOwnNotes#1666]
Arch Linux, KDE-Unstable.
The patch resolves this problem:
```diff
@@ -22,6 +22,7 @@
#include <QKeyEvent>
#include <QLayout>
#include <QPainter>
+#include <QPainterPath>
#include <QRegularExpression>
```

**Comment by pbek** [comment]
Thank you, do you care to open a pull request with the change?

**Comment by data-man** [comment]
Sure!
https://github.com/pbek/qmarkdowntextedit/pull/112

**Comment by pbek** [comment]
Thank you very much, merged and included now!
