### ISSUE TITLE
Change/add markdown syntax via scripts

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#167]
How about an ability to change pmh_grammar.leg (and maybe some other in-app vars) via scripts. It will make all sorts of customized markdown possible without touching app sources. I've seen guys wanting to put in some tables and diagram stuff. It can all be scripts instead off in-app.

**Comment by pbek** [comment]
This file is part of the lexer and has to be compiled. It cannot be changed via a script at runtime.

**Comment by Maboroshy** [comment]
It was worth a try. :)

**Comment by pbek** [comment]
;)
