### ISSUE TITLE
[F] scroll past end feature request

### ISSUE THREAD

**Issue by RichardBaker3020** [pbek/QOwnNotes#1670]
Thanks for your works and I really love the Qownnotes! But I find it a little bit inconvenient that editor doesn't allow scrolling past the end of the document, I hope this handy feature could be added in the future:)

**Comment by pbek** [comment]
Thank you for your kind words. You can enable the Typewriter mode if you want that. Or do you see another use-case for scrolling past the end of the document?

**Comment by RichardBaker3020** [comment]
> Thank you for your kind words. You can enable the Typewriter mode if you want that. Or do you see another use-case for scrolling past the end of the document?

Thx:) Typewriter mode works for me.

**Comment by pbek** [comment]
Great. 😁
