### ISSUE TITLE
Meta key can't be used in keyboard shortcuts

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1671]
It doesn't seem to work properly to use the Meta key in keyboard shortcuts (reported in #44). This happens at least in Linux with KDE and I also glimpsed troubles under Windows 10.

@Maboroshy and @uffejakobsen also confirmed troubles

There was a Qt issue reported for that at [QTBUG-62102](https://bugreports.qt.io/browse/QTBUG-62102). Could be a problem with [QKeySequenceEdit](https://doc.qt.io/qt-5/qkeysequenceedit.html) or the input methods.

It could also be that the issue comes from KDE's effort to treat the Meta modifier as "normal" key to be able to open the start menu with it.

### General Info

**Version**: `20.3.9`
**Build date**: `Mar 30 2020`
**Build number**: `688`
**Platform**: `linux`
**Operating System**: `KDE neon User Edition 5.18`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.9.5`
**Qt Version (runtime)**: `5.14.1`
**Portable mode**: `no`

**Comment by pbek** [comment]
@Maboroshy and @uffejakobsen, I kind of tried to work around the problem...

## 20.4.1
- you can now use the **Meta key in keyboard shortcuts** in the *Shortcuts settings*
  - if you have troubles with a 2nd Meta key showing up while entering the shortcut
    you can press <kbd>Enter</kbd> or <kbd>Escape</kbd> to finish the shortcut entering

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by uffejakobsen** [comment]
If works great - thanks a lot.

BTW: in case of 2nd Meta showing up - taping the Meta key once again fixes it - just like the ESC key

**Comment by Maboroshy** [comment]
Same for me. :+1:

**Comment by pbek** [comment]
Thank you for testing! Using another modifier before Meta also helped for me.
