### ISSUE TITLE
Reference style links point to an invalid location

### ISSUE THREAD

**Issue by atosscsd-bb** [pbek/QOwnNotes#1673]
When writing reference style links in markdown, the links in the rendered document point to an invalid location.

Consider following snippet:
```
Git has built-in command [git-request-pull][g-1] to handle pull requests.

[g-1]: (https://git-scm.com/docs/git-request-pull)
```

The link in the generated HTML or PDF document will point to `file:///tmp/(https://git-scm.com/docs/git-request-pull)`.

I'm running QOwnNotes - version 20.4.1 - Launchpad PPA - build 690

**Comment by pbek** [comment]
You need to use `[g-1]: https://git-scm.com/docs/git-request-pull`, without brackets.

**Comment by atosscsd-bb** [comment]
Thanks. I should have looked closely into the [documentation](https://github.com/pbek/QOwnNotes/blob/develop/src/demonotes/Markdown%20Cheatsheet.md).
