### ISSUE TITLE
[Feature Request] sort by created date option

### ISSUE THREAD

**Issue by davuses** [pbek/QOwnNotes#1674]
It will be awesome if notes and subfolder can be sorted by created date:)

**Comment by pbek** [comment]
Thank you for your suggestion. What's the use case for that?

**Comment by RichardBaker3020** [comment]
> Thank you for your suggestion. What's the use case for that?

The order of notes or subfolders won't change so often if they're sorted by created date, and it will be easier to remember their relative position. Also, notes are always created in a logical order, their initial order is important and it's better not to change it by modifying.

**Comment by pbek** [comment]
Thank you. It's a lot of effort to do that, so it will probably never happen.
