### ISSUE TITLE
Tray icon not appearing on Cinnamon

### ISSUE THREAD

**Issue by grosjo** [pbek/QOwnNotes#1675]
#### Expected behaviour

Tray icon appearing

#### Actual behaviour

No tray icon

#### Steps to reproduce

Start the app with Cinnamon dektop (any distro)

## General Info

**Current Date**: `Sun Apr 5 19:17:53 2020`
**Version**: `20.4.1`
**Build date**: `Apr  4 2020`
**Build number**: `690`
**Platform**: `linux`
**Operating System**: `Arch Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.14.2`
**Qt Version (runtime)**: `5.14.2`
**Portable mode**: `no`
**Settings path / key**: `/home/joan/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/joan/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `Mint-X-Brown`
**Notes in current note folder**: `3`
**Calendar items**: `20`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://grosjo.net/cloud`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `18.0.3.0`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_US, en_US-large, es_ANY, fr_BE, fr_CA, fr_CH, fr_FR, fr_LU`
**Language names**: `American English (United States), American English (United States) [large], español de España (España), français (Belgique), français canadien (Canada), français suisse (Suisse), français (France), français (Luxembourg)`
**Application dictionaries path**: `/home/joan/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/joan/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/joan/Nextcloud/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://grosjo.net/cloud`
**username**: `joan`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**LastUpdateCheck** (QDateTime): `2020-04-05T19:01:04.855`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Sans,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Sans,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**MessageBoxOverride/layoutwidget-use-layout** (QString): `16384`
**NoteHistory-1** (QVariantList): `<variant list with 3 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `2`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `UpTvY2Gwb99U`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `1col`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (int): `15`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/joan/Nextcloud/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `18.0.3.0`
**restoreCursorPosition** (bool): `true`
**restoreLastNoteAtStartup** (bool): `true`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useUNIXNewline** (bool): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-UpTvY2Gwb99U/name** (QString): `Single column`
**workspace-UpTvY2Gwb99U/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-UpTvY2Gwb99U/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Single column`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, UpTvY2Gwb99U`

## System environment

**SHELL**: `/bin/bash`
**SESSION_MANAGER**: `local/gjlaptop:@/tmp/.ICE-unix/1068,unix/gjlaptop:/tmp/.ICE-unix/1068`
**JAVA_OPTIONS**: `-Djava.io.tmpdir=/var/tmp`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**GRADLE_HOME**: `/usr/share/java/gradle`
**SVN_EDITOR**: `vim`
**CINNAMON_VERSION**: `4.4.8`
**DESKTOP_SESSION**: `cinnamon`
**GTK_MODULES**: `canberra-gtk-module`
**XDG_SEAT**: `seat0`
**PWD**: `/home/joan`
**XDG_SESSION_DESKTOP**: `cinnamon`
**LOGNAME**: `joan`
**XDG_SESSION_TYPE**: `x11`
**XAUTHORITY**: `/run/user/1000/gdm/Xauthority`
**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`
**WINDOWPATH**: `2`
**GDM_LANG**: `en_US.utf8`
**WINEARCH**: `win32`
**HOME**: `/home/joan`
**USERNAME**: `joan`
**LANG**: `en_US.utf8`
**ANDROID_EMULATOR_USE_SYSTEM_LIBS**: `1`
**XDG_CURRENT_DESKTOP**: `X-Cinnamon`
**GJS_DEBUG_OUTPUT**: `stderr`
**XDG_SESSION_CLASS**: `user`
**ANDROID_HOME**: `/opt/android-sdk`
**GTK_OVERLAY_SCROLLING**: `1`
**USER**: `joan`
**DISPLAY**: `:0`
**SHLVL**: `0`
**STUDIO_VM_OPTIONS**: `-Djava.io.tmpdir=/var/tmp/`
**XDG_VTNR**: `2`
**XDG_SESSION_ID**: `2`
**MOZ_PLUGIN_PATH**: `/usr/lib/mozilla/plugins`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_DATA_DIRS**: `/home/joan/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
**GDMSESSION**: `cinnamon`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**HG**: `/usr/bin/hg`
**MAIL**: `/var/spool/mail/joan`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `22909`
**GIO_LAUNCHED_DESKTOP_FILE**: `/usr/share/applications/PBE.QOwnNotes.desktop`

**Comment by pbek** [comment]
> ShowSystemTray (bool): false

Maybe you want to turn the tray icon on?

**Comment by grosjo** [comment]
PLease stop making fun of people, your behavior is really unbearable.

Where in your app is that option ?

**Comment by pbek** [comment]
I'm sorry. It was not clear to me that you don't know you need to turn that feature on before expecting it to work.

![image](https://user-images.githubusercontent.com/1798101/78535903-334f2200-77ed-11ea-8327-248eae23a99b.png)

**Comment by PurplePlums** [comment]
Settings, -> interface -> "enable dark mode application and tray icon".

**Comment by PurplePlums** [comment]
You either find actions in 

„Help“ -> „find action“

or „Scripting“ -> „script settings“
