### ISSUE TITLE
Feature Request - Title bar text

### ISSUE THREAD

**Issue by whollaus** [pbek/QOwnNotes#1677]
#1676 

Currently "Note name - QOwnNotes Version" is displayed.

If there are multiple folders (but only if), a more detailed description would be helpful:

"Note name - Folder name - QOwnNotes Version"

Basically, this would also be useful for different sessions. ("QOwnNotes --session Work" should display the session name)

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
## 20.4.2
- some title bar improvements were made
    - if more than one note folder exists then the name of the current note folder
      will be shown in the title bar
    - if a session was set with the `--session` cli parameter then it will be
      shown in the title bar

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by whollaus** [comment]
Perfect!!!

**Comment by pbek** [comment]
Great, thank you for testing!
