### ISSUE TITLE
Open note-preview in different window

### ISSUE THREAD

**Issue by cberetta** [pbek/QOwnNotes#1678]
#### Expected behaviour
Have the possibility to open the note in **preview-mode** in a different window, as already is possible for the note via "Note" => "View Note" => "Open Note in different Window" menù.

#### Actual behaviour
At the moment the note preview is only available via the "Preview Panel"

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
## 20.4.3
- when right-clicking a note in the note list and clicking `Open note in different window`
  you can now also show a **preview of your note** instead of the note text

There now is a new release, could you please test it and report if it works for you?

**Comment by cberetta** [comment]
I've tested the new release. It's perfect. It's exactly what I was thinking of.

Great work !!!

**Comment by pbek** [comment]
Great, thank you for testing! 😁
