### ISSUE TITLE
[I] Auto save makes editing impossible on MacOS

### ISSUE THREAD

**Issue by testcocoon** [pbek/QOwnNotes#1681]
#### Expected behaviour

Auto saving should not influence the editing.
Also, an option to disable the auto saving would be a workaround.

#### Actual behaviour

Each time that QOwnCloud saves the currect document, the cursor position is changing to a unpredictable position and some character typed are lost.

Using the QOwnCloud editor is really a pain due to this and the only solution is to use an external editor.

#### Steps to reproduce

Use a very long text and edit it in the middle

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `ven. avr. 10 16:14:47 2020`
**Version**: `20.4.3`
**Build date**: `Apr  9 2020`
**Build number**: `5474`
**Platform**: `macosx`
**Operating System**: `macOS 10.15`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
**Settings path / key**: `/Users/sfri/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/sfri/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: `fr`
**Primary screen resolution**: `1680x1050`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `39`
**Calendar items**: `1`
**Enabled scripts**: `5`

## Server Info

**serverUrl**: `https://fricker.mooo.com:/owncloud`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `10.3.2.2`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `fr`
**Language codes**: `fr`
**Language names**: `français`
**Application dictionaries path**: `/Users/sfri/Library/Application Support/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `par défaut`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/Users/sfri/ownCloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/Users/sfri/ownCloud/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://fricker.mooo.com:/owncloud`
**username**: `sfri`

### Script `External note diff`

**id**: `1`
**path**: `/Users/sfri/Library/Application Support/PBE/QOwnNotes/scripts/external-note-diff/external-note-diff.qml`
**variablesJson**: 
```
{
    "executablePath": "/usr/local/bin/vimdiff"
}
```
**identifier**: `external-note-diff`
**version**: `0.0.1`
**minAppVersion**: `17.07.8`

### Script `Note stats`

**id**: `4`
**path**: `/Users/sfri/Library/Application Support/PBE/QOwnNotes/scripts/note-stats/note-stats.qml`
**variablesJson**: 
```
{
    "charSpaceName": "Chars",
    "paragraphsLeftName": "",
    "paragraphsLeftTarget": 0,
    "paragraphsName": "Paragraphs",
    "readTimeName": "Reading time",
    "readTimeRate": 150,
    "wordsName": "Words"
}
```
**identifier**: `note-stats`
**version**: `0.0.2`
**minAppVersion**: `17.06.3`

### Script `Custom note preview styling`

**id**: `6`
**path**: `/Users/sfri/Library/Application Support/PBE/QOwnNotes/scripts/preview-styling/preview-styling.qml`
**variablesJson**: 
```
{
    "customStylesheet": "h1 {font-size: xx-large;margin-left: 20px; margin-right: 20px; text-align: center; text-decoration:underline; font-variant: small-caps; }\nh2 {font-size: x-large;margin-left: 20px; margin-right: 20px; text-align: center; text-decoration:underline; font-variant: small-caps;}\nh3 {font-size: large;margin-left: 20px; margin-right: 20px; text-align: center; text-decoration:underline; font-variant: small-caps;}\nh4 {font-size: medium;margin-left: 20px; margin-right: 20px; text-align: center; text-decoration:underline; font-variant: small-caps;}\nh5 {font-size: small;margin-left: 20px; margin-right: 20px; text-align: center; text-decoration:underline; font-variant: small-caps;}\nblockquote { font-style:italic; }\np { text-indent: 10px; align:justify; }"
}
```
**identifier**: `preview-styling`
**version**: `0.0.4`
**minAppVersion**: `17.05.7`

### Script `Export notes as one HTML file`

**id**: `7`
**path**: `/Users/sfri/Library/Application Support/PBE/QOwnNotes/scripts/export-notes-as-one-html/export-notes-as-one-html.qml`
**variablesJson**: *empty*
**identifier**: `export-notes-as-one-html`
**version**: `1.0.0`
**minAppVersion**: `18.03.7`

### Script `External note open`

**id**: `8`
**path**: `/Users/sfri/Library/Application Support/PBE/QOwnNotes/scripts/external-note-open/external-note-open.qml`
**variablesJson**: 
```
{
    "executablePath": ""
}
```
**identifier**: `external-note-open`
**version**: `1.0.0`
**minAppVersion**: `18.05.4`

## Settings

**ADATA Portable HDD SH93** (QString): `1`
**AKLastCheckInAttemptDate** (QDateTime): `2019-10-09T08:21:38.239`
**AKLastCheckInSuccessDate** (QDateTime): `2019-10-09T08:21:47.349`
**AKLastEmailListRequestDateKey** (QDateTime): `2020-03-30T10:36:54.417`
**AKLastIDMSEnvironment** (qlonglong): `0`
**AREXX RF_USB** (QString): `1`
**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Android Android** (QString): `1`
**Canon MB5100 series** (QString): `1`
**Country** (QString): `DE`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**DistractionFreeMode/editorWidthMode** (qlonglong): `4`
**DistractionFreeMode/isEnabled** (bool): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (qlonglong): `0`
**DistractionFreeMode/menuBarVisible** (bool): `false`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/centerCursor** (bool): `false`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (qlonglong): `4`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**FileDialog/LastPath** (QString): `/Users/sfri/ownCloud/Notes`
**FileDialog/LastPath-NotePDFExport** (QString): `/Users/sfri/ownCloud/Notes`
**FileDialog/LastPath-ScriptSettingsFile-inbox-noteFolder** (QString): `/Users/sfri/ownCloud/Notes`
**FileDialog/LastPath-SettingsExport** (QString): `/Users/sfri/ownCloud/Notes`
**Freescale SemiConductor Inc NS Blank CODEX** (QString): `1`
**GENERAL - UVC** (QString): `1`
**Generic USB Mass Storage Device Generic USB Mass Storage Device** (QString): `1`
**HP DeskJet 3700 series** (QString): `1`
**HP LaserJet MFP M129-M134** (QString): `1`
**Hewlett Packard MFP M477fdw** (QString): `1`
**Intenso External USB-3/0** (QString): `1`
**Intenso portable SSD** (QString): `1`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**Kobo eReader-0/0/0** (QString): `1`
**Kobo eReader-3/18/0** (QString): `1`
**Kobo eReader-3/19/5761** (QString): `1`
**Kobo eReader-4/15/12920** (QString): `1`
**Kobo eReader-4/2/8432** (QString): `1`
**Kobo eReader-4/3/8842** (QString): `1`
**Kobo eReader-4/3/8945** (QString): `1`
**Kobo eReader-4/4/9344** (QString): `1`
**Kobo eReader-4/5/9587** (QString): `1`
**Kobo eReader-4/6/9995** (QString): `1`
**Kobo eReader-4/7/10413** (QString): `1`
**LastUpdateCheck** (QDateTime): `2020-04-10T16:06:56.218`
**Linux 2/6/35/3-850-gbc67621+ with fsl-usb2-udc RNDIS·Ethernet Gadget** (QString): `1`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**Logitech USB Receiver** (QString): `1`
**Logitech Wireless Headset** (QString): `1`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (qlonglong): `32`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Monaco,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `.SF NS Text,16,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Monaco,11,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Arial,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**MessageBoxOverride/move-notes** (qlonglong): `16384`
**MessageBoxOverride/tag-notes** (qlonglong): `16384`
**MessageBoxOverride/update-and-restart** (qlonglong): `16384`
**MultipleSessionEnabled** (bool): `true`
**NoteFolder-1/allowDifferentNoteFileName** (bool): `false`
**NoteHistory-1** (QVariantList): `<variant list with 185 item(s)>`
**NoteHistoryCurrentIndex-1** (qlonglong): `184`
**PKSecureElementAvailableFlags** (qlonglong): `1`
**PKSecureElementAvailableFlagsByHost** (qlonglong): `1`
**PersistentScripting/MdNT/pandocCommand** (QString): `/usr/local/bin/pandoc`
**PersistentScripting/MdNT/pandocVersion** (QString): *empty*
**PersistentScripting/MdNT/pyCommand** (QString): *empty*
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExportOrientation** (qlonglong): `0`
**Printer/NotePDFExportPageSize** (qlonglong): `4`
**Printer/NotePrinting** (QByteArray): `<binary data>`
**SAMSUNG Gadget Serial** (QString): `1`
**SAMSUNG SAMSUNG_Android** (QString): `1`
**SanDisk Cruzer Fit** (QString): `1`
**SanDisk Cruzer Micro** (QString): `1`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (qlonglong): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (qlonglong): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `sfri`
**USB DISK 2/0** (QString): `1`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**VersionDialog/geometry** (QByteArray): `<binary data>`
**WebAutomaticSpellingCorrectionEnabled** (bool): `true`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**_HIHideMenuBar** (bool): `false`
**acceptAllExternalModifications** (bool): `true`
**allowNoteEditing** (bool): `false`
**allowOnlyOneAppInstance** (bool): `false`
**appMetrics/disableAppHeartbeat** (bool): `true`
**appMetrics/disableTracking** (bool): `true`
**appMetrics/notificationShown** (bool): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (bool): `false`
**com/logitech/akebono/logTags** (QString): `-* +DevioManager +MouseMonitorThread +AsyncJobManager +Condition +JobTargetManager +PubNub +AK1814FeatureImplementation +AKPDeviceImplementation +AKSamarkandDevice +AKUIFlowStatusItem +Flow +FlowAutoDiscoveryJob +FlowRecoverHostsJob +Flow_MarconiProxy +ScopeTimer +Pasteboard +Pasteboard/SourceCacheItem +Pasteboard/SourceItem +Pasteboard/Transfer +Pasteboard/TransferDisplay +Pasteboard/Utils +AK40A3FeatureImplementation +AKFnKeyAction +AK650xGesture_Custom`
**com/logitech/akebono/loggingLevel** (QString): `3`
**com/logitech/devio/logTags** (QString): `-*`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (qlonglong): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (qlonglong): `3`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `true`
**darkModeColors** (bool): `true`
**darkModeIconTheme** (bool): `true`
**darkModeTrayIcon** (bool): `true`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (bool): `true`
**disableAutomaticUpdateDialog** (bool): `false`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (bool): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `true`
**gitCommitInterval** (qlonglong): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (qlonglong): `1024`
**imageScaleDownMaximumWidth** (qlonglong): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (qlonglong): `11`
**interfaceLanguage** (QString): `fr`
**internalIconTheme** (bool): `false`
**itemHeight** (qlonglong): `22`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (qlonglong): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (qlonglong): `0`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (qlonglong): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (qlonglong): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (qlonglong): `0`
**notesPanelOrder** (qlonglong): `0`
**notesPanelSort** (qlonglong): `1`
**notesPath** (QString): `/Users/sfri/ownCloud/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/ignoreNonTodoCalendars** (bool): `false`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (qlonglong): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): `https://fricker.mooo.com:5232/sfri/`
**ownCloud/todoCalendarCalDAVUsername** (QString): `sfri`
**ownCloud/todoCalendarCloudConnectionId** (qlonglong): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Personal`
**ownCloud/todoCalendarEnabledList** (QStringList): `Personal`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://fricker.mooo.com/owncloud/remote.php/dav/calendars/sfri/personal/`
**ownCloud/todoCalendarUrlList** (QStringList): `https://fricker.mooo.com/owncloud/remote.php/dav/calendars/sfri/personal/`
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `10.3.2.2`
**restoreCursorPosition** (bool): `true`
**restoreLastNoteAtStartup** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2020-04-10T16.07.29, sat, Note 2020-03-28T13.31.12, Note 2020-02-18T09.16.33, Note 2020-02-05T22.30.06, Note 2020-01-26T16.35.19, Note 2019-12-22T22.54.56, Note 2019-12-15T21.58.51, Note 2019-12-15T21.11.27, Note 2019-11-06T20.17.45, Note 2019-10-12T14.43.09, Note 2019-09-28T17.08.34, Note 2019-06-01T21.28.58, Note 2019-05-05T18.35.49, Note 2019-04-20T16.30.48, Note 2019-03-21T23.18.40, Mon pari avec Alessandra, Gavage d'une oie blanche (2), Gavage d'une oie blanche (1), Le fauteuil, Ma masseuse et moi - Histoire Erotique HDS, Une première plutôt hype - Histoire Erotique HDS, Réflexions autour de la sodomie, Sexualité ces trucs que je ne veux pas (re)tenter, LES FEMMES ET LA SODOMIE TÉMOIGNAGES FÉMININS Lignes de force, Mon homme veux me sodomiser - Dois-je accepter, Pourquoi j'aime sodomiser mon homme avec un gode-ceinture 69Desirs, Note 2019-02-01T14.46.34, Les Sensations de la Sodomie » MonsieurMadameX, Note 2019-02-01T14.17.44, Note 2019-02-01T11.47.02, Shopfinder, Note 2019-01-26T17.12.45, Acte XI des « gilets jaunes », en direct  22 000 manifestants en France à la mi-journée, Amazon.fr - Die Deutschlehrerin - Judith W. Taschler - Livres, Acte XI des « gilets jaunes », en direct  plusieurs défilés et assemblées rassemblent quelques milliers de manifestants, Acte XI des « gilets jaunes », en direct  plusieurs défilés et assemblées rassemblent quelques milliers de manifestants 2019-01-26T15.38.05, Le compositeur Michel Legrand est mort 2019-01-26T15.27.34, Le compositeur Michel Legrand est mort, p7_190125_2015_4bb05a69_godzilla.jpg (JPEG Image, 320 × 240 pixels), QOwnNotes Markdown Cheatsheet.md at develop · pbek QOwnNotes · GitHub, Note 2019-01-25T08.42.57, Note 2019-01-16T11.25.08, Note 2019-01-11T09.19.45`
**showMatches** (bool): `true`
**showMenuBar** (bool): `false`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `fr`
**systemIconTheme** (bool): `false`
**tagWasAddedToNote** (bool): `true`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `true`
**tagsPanelOrder** (qlonglong): `0`
**tagsPanelSort** (qlonglong): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `barre d'outils principale`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `barre d'outils de formatage`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `barre d'outils d'insertion`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `barre d'outils de chiffrement`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `barre d'outils de fenêtre`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quitter la barre d’outils`
**toolbar/size** (qlonglong): `6`
**useSoftWrapInNoteEditor** (bool): `true`
**useUNIXNewline** (bool): `false`
**versionSplitterSizes** (QByteArray): `<binary data>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (qlonglong): `22222`
**workspace-initial/name** (QString): `Interface minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**ITERM_PREV_PS1**: `\[]133;D;$?]133;A\]\h:\W \u\$ \[]133;B\]`
**PWD**: `/var/folders/73/lkck1y454wb70s1_4r188y8m0000gn/T/tmp.wr2CxIy0`
**PKG_CONFIG_PATH**: `/usr/X11/lib/pkgconfig/:/usr/local/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig/`
**USER**: `sfri`
**ITERM_ORIG_PS1**: `\h:\W \u\$ `
**LANG**: `fr_FR.UTF-8`
**CAML_LD_LIBRARY_PATH**: `/Users/sfri/.opam/4.07.0/lib/stublibs:/Users/sfri/.opam/4.07.0/lib/ocaml/stublibs:/Users/sfri/.opam/4.07.0/lib/ocaml`
**CMMERGE_DIR**: `/Users/sfri/squishcoco/build/release/testcocoon/src/cmmerge`
**LOGNAME**: `sfri`
**TERM**: `xterm-256color`
**PATH**: `/usr/local/opt/llvm/bin:/usr/local/opt/zip/bin:/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:/Users/sfri/.opam/4.07.0/bin:/Users/sfri/squishcoco/build/release/testcocoon/src/coveragescanner/wrapper:/Users/sfri/bin:/Users/sfri/.opam/4.07.0/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Applications/SquishCoco:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/git/bin:/Users/sfri/squishcoco/build/release/testcocoon/src/coveragescanner:/Users/sfri/squishcoco/build/release/testcocoon/src/coveragebrowser/coveragebrowser.app/Contents/MacOS:/Users/sfri/squishcoco/build/release/testcocoon/src/cmcsexeimport:/Users/sfri/squishcoco/build/release/testcocoon/src/cmmerge:/Users/sfri/squishcoco/build/release/testcocoon/src/cmreport`
**COVERAGEBROWSER_DIR**: `/Users/sfri/squishcoco/build/release/testcocoon/src/coveragebrowser/coveragebrowser.app/Contents/MacOS`
**COCO_DIR**: `/Users/sfri/squishcoco/build/release`
**DISPLAY**: `/private/tmp/com.apple.launchd.TaLeWQIR5C/org.macosforge.xquartz:0`
**EDITOR**: `/usr/bin/vim`
**TERM_SESSION_ID**: `F92BD4E3-1386-41E7-BBEE-4BA08C17C72F`
**CMCSEXEIMPORT_DIR**: `/Users/sfri/squishcoco/build/release/testcocoon/src/cmcsexeimport`
**SHLVL**: `2`
**COVERAGESCANNER_DIR**: `/Users/sfri/squishcoco/build/release/testcocoon/src/coveragescanner`
**TERM_PROGRAM_VERSION**: `433`
**SSH_AUTH_SOCK**: `/private/tmp/com.apple.launchd.O1JXseYqWF/Listeners`
**ARCHFLAGS**: `-arch x86_64`
**_**: `/usr/bin/open`
**OCAML_TOPLEVEL_PATH**: `/Users/sfri/.opam/4.07.0/lib/toplevel`
**HOME**: `/Users/sfri`
**LC_ALL**: `en_US.utf-8`
**QT_LOGGING_RULES**: `qt.network.ssl.warning=false`
**WRAPPER_DIR**: `/Users/sfri/squishcoco/build/release/testcocoon/src/coveragescanner/wrapper`
**OPAM_SWITCH_PREFIX**: `/Users/sfri/.opam/4.07.0`
**SHELL**: `/bin/bash`
**OLDPWD**: `/Users/sfri`
**__CF_USER_TEXT_ENCODING**: `0x1F5:0x0:0x1`
**TERM_PROGRAM**: `Apple_Terminal`
**CMREPORT_DIR**: `/Users/sfri/squishcoco/build/release/testcocoon/src/cmreport`
**TMPDIR**: `/var/folders/73/lkck1y454wb70s1_4r188y8m0000gn/T/`
**XPC_SERVICE_NAME**: `com.PBE.QOwnNotes.4464`
**XPC_FLAGS**: `0x0`
</details>

**Comment by pbek** [comment]
Can be something that writes in your note folder. Please check #689 or similar. If nothing helps you can also turn off restoring of the cursor in the General settings.

Feel free to report back if you found something.

**Comment by pbek** [comment]
You can also increase the auto-save time.

**Comment by testcocoon** [comment]
I think that  #689  was the issue. BTW, I was not modifying the default settings. 
Certainly this restore cursor position may not be a good default.

**Comment by pbek** [comment]
I don't know. Most of the people including myself don't have this issue, even on macOS.

**Comment by pbek** [comment]
I would rather see this issue on some Computers fixed. But as long as I can't even reproduce it that's difficult.

**Comment by pbek** [comment]
@testcocoon, I just saw that `restoreCursorPosition` is off by default on macOS, was that not the case for you?

**Comment by pbek** [comment]
And can you please try turning `restoreCursorPosition` on again and test 20.4.4.

## 20.4.4
- some improvements for possible "cursor jumping to the top" issues were made

There now is a new release, could you please test it and report if it works for you?

**Comment by testcocoon** [comment]
It is possible that I have changed the defaults for a long time.
I'm playing with the 20.4.4. Give me 2-3 days to see if the problem occurs again.

**Comment by pbek** [comment]
Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging.

**Comment by testcocoon** [comment]
I have build QOwnNotes from the sources. Can you give me some functions on which I can set a breakpoint so that I can faster investigate your issue?
I will try to implement a fix, if I can understand what happens.

**Comment by pbek** [comment]
Oh, nice.

The jumping should happen in https://github.com/pbek/QOwnNotes/blob/cd6e29937a1263cfd1e495808c59feb371ea7688/src/entities/notehistory.cpp#L87

**Comment by pbek** [comment]
And the jumping will be triggered because some external process is modifying your note folder (e.g. Spotlight?) and thus the note folder is reloaded.

**Comment by testcocoon** [comment]
No idea, let see what I can find. I hope that the debug mode does not alter a runtime behavior that make the issue impossible to reproduce.

**Comment by pbek** [comment]
Thank you for your effort!

**Comment by testcocoon** [comment]
When the issue occurs then the corresponding line is not executed (https://github.com/pbek/QOwnNotes/blob/cd6e29937a1263cfd1e495808c59feb371ea7688/src/entities/notehistory.cpp#L87). Has something different to do. I suspect that the document get refreshed and the cursor position is automatically moved to the begin.

**Comment by pbek** [comment]
> When the issue occurs then the corresponding line is not executed

Ah, I see. 

> I suspect that the document get refreshed and the cursor position is automatically moved to the begin.

Ideally it should jump to the current line ("remembered" in the note history) when the document is refreshed. Even more ideally the document shouldn't be refreshed at all.

**Comment by testcocoon** [comment]
Let see if I can find the function which refresh the document.

**Comment by pbek** [comment]
> Let see if I can find the function which refresh the document.

`MainWindow::buildNotesIndexAndLoadNoteDirectoryList` is called (on many occasions)
