### ISSUE TITLE
Internal Links to notes not working when using subdirectories on Windows in portable mode if note folder lies outside of application folder

### ISSUE THREAD

**Issue by chrixxxx** [pbek/QOwnNotes#1682]
I'm using the last stable version of the application with Windows 7 Pro 64bit.

Internal Links to other notes when you use subdirectories is completely broken.

If I have a note named "my target note.md" in my current base note directory and I create a second note in the same dir and I link the previous note, I obtain something like that in the editor:

`[My Target Note](my%20target%20note.md)`

And when I click the link in the preview it's ok, it works, it opens the desired target note.

But if I use subdirectories (and in my projects I need a lot of them) then links to other notes don't work anymore (except if the point to notes placed in the "root" directory).

An example: I have a subdirectory in my  current base note directory named "subdir"; I create there a note called "sub note target.md".. and .. well..  there's NO WAY to have other notes to link to this one, being in the same subdirectory or in the root directory, it simply doesn't matter: the generated link NEVER works, it ALWAYS opens the "note not find" dialog box, with the option to create a new one.

The editor shows :

`[link to a note in a subdirectory](subdir%2Fsub%20note%20target.md)`

But the target doesn't open, it ALWAYS appears the dialog box telling me that the note doesn't exist and asking me if I want to create one.

**Comment by pbek** [comment]
I could not reproduce our issue (under Linux). Links to notes in subfolders like `[test](a%20sub%20folder%202/dfolder%202%2Ftest.md)` worked fine in the preview and the note edit.

Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging.

**Comment by pbek** [comment]
I also had no issues under Windows 8.

## General Info

**Version**: `20.4.3`
**Build date**: `Apr 11 2020`
**Build number**: `692`
**Platform**: `windows`
**Operating System**: `Windows 8.1 (6.3)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `Self-build`
**Qt Version (build)**: `5.13.1`
**Qt Version (runtime)**: `5.13.1`
**Portable mode**: `no`

**Comment by chrixxxx** [comment]
> I could not reproduce our issue (under Linux). Links to notes in subfolders like `[test](a%20sub%20folder%202/dfolder%202%2Ftest.md)` worked fine in the preview and the note edit.
> 
> Can you please post the output from the debug settings (see issue template).
> And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging.

You mean this ? 
alpha1.md, alpha2.md are the two files I tried to link each other, they're in the subdir "subd", while K:/[documenti]/[QOwnNotes] Notes/ is the "base" directory for my notes I choosed and K:/ QOwnNotes [portable] where I installed the program (I run it in portable mode, K: it's an external hard drive)

> [apr 11 11:16:02] [debug]: Set proxy configuration to use NO proxy
> [apr 11 11:16:06] [debug]: initShortcuts  - 'menuBarIsVisible':  true
> [apr 11 11:16:06] [debug]: fileUrlInCurrentNoteFolderToRelativePath  - 'path':  "K:/QOwnNotes [portable]/Data/../../[Documenti]/[QOwnNotes] Notes/subd/Alpha2.md"
> [apr 11 11:16:06] [debug]: fileUrlInCurrentNoteFolderToRelativePath  - 'canonicalFilePath':  "K:/[Documenti]/[QOwnNotes] Notes/subd/Alpha2.md"
> [apr 11 11:16:06] [debug]: fileUrlInCurrentNoteFolderToRelativePath  - 'path':  "K:/QOwnNotes [portable]/Data/../../[Documenti]/[QOwnNotes] Notes/subd/Alpha1.md"
> [apr 11 11:16:06] [debug]: fileUrlInCurrentNoteFolderToRelativePath  - 'canonicalFilePath':  "K:/[Documenti]/[QOwnNotes] Notes/subd/Alpha1.md"
> [apr 11 11:16:06] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Predefinito" <serverUrl>"" <username>"" <priority>1
> [apr 11 11:16:06] [debug]: buildNotesIndex  - 'noteSubFolderId':  0
> [apr 11 11:16:06] [debug]: buildNotesIndex  - 'noteSubFolderId':  1
> [apr 11 11:16:06] [debug]: buildNotesIndex  - 'noteSubFolderId':  2
> [apr 11 11:16:06] [debug]: buildNotesIndex  - 'noteSubFolderId':  3
> [apr 11 11:16:06] [debug]: buildNotesIndex  - 'noteSubFolderId':  4
> [apr 11 11:16:06] [debug]: buildNotesIndex  - 'noteSubFolderId':  5
> [apr 11 11:16:06] [debug]: setupNoteFolderTables  - 'database version':  14
> [apr 11 11:16:06] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Predefinito" <serverUrl>"" <username>"" <priority>1
> [apr 11 11:16:06] [debug]: loadNoteDirectoryList
> [apr 11 11:16:06] [debug]: reloadTagTree
> [apr 11 11:16:06] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector()
> [apr 11 11:16:06] [debug]: reloadNoteSubFolderTree
> [apr 11 11:16:06] [debug]: reloadNoteSubFolderTree
> [apr 11 11:16:06] [debug]: reloadTagTree
> [apr 11 11:16:06] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(0)
> [apr 11 11:16:07] [debug]: loadNoteDirectoryList
> [apr 11 11:16:07] [debug]: reloadTagTree
> [apr 11 11:16:07] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(0)
> [apr 11 11:16:07] [debug]: reloadNoteSubFolderTree
> [apr 11 11:16:07] [debug]: reloadTagTree
> [apr 11 11:16:07] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector()
> [apr 11 11:16:09] [debug]: on_noteTextView_anchorClicked  - 'url':  QUrl("file:///K:/QOwnNotes %5Bportable%5D/Data/../../%5BDocumenti%5D/%5BQOwnNotes%5D Notes/subd/Alpha2.md")
> [apr 11 11:16:09] [debug]: fileUrlInCurrentNoteFolderToRelativePath  - 'path':  "K:/QOwnNotes [portable]/Data/../../[Documenti]/[QOwnNotes] Notes/subd/Alpha2.md"
> [apr 11 11:16:09] [debug]: fileUrlInCurrentNoteFolderToRelativePath  - 'canonicalFilePath':  "K:/[Documenti]/[QOwnNotes] Notes/subd/Alpha2.md"
> [apr 11 11:16:25] [debug]: on_noteTextView_anchorClicked  - 'url':  QUrl("file:///K:/QOwnNotes %5Bportable%5D/Data/../../%5BDocumenti%5D/%5BQOwnNotes%5D Notes/subd/Alpha2.md")
> [apr 11 11:16:25] [debug]: fileUrlInCurrentNoteFolderToRelativePath  - 'path':  "K:/QOwnNotes [portable]/Data/../../[Documenti]/[QOwnNotes] Notes/subd/Alpha2.md"
> [apr 11 11:16:25] [debug]: fileUrlInCurrentNoteFolderToRelativePath  - 'canonicalFilePath':  "K:/[Documenti]/[QOwnNotes] Notes/subd/Alpha2.md"
> [apr 11 11:16:34] [debug]: updatePanelMenu  - 'updatePanelMenu'
> [apr 11 11:16:34] [debug]: updatePanelMenu  - 'updatePanelMenu'
> [apr 11 11:16:34] [debug]: updatePanelMenu  - 'updatePanelMenu'
> [apr 11 11:16:35] [debug]: updatePanelMenu  - 'updatePanelMenu'
> [apr 11 11:16:35] [debug]: updatePanelMenu  - 'updatePanelMenu'
> [apr 11 11:16:35] [debug]: updatePanelMenu  - 'updatePanelMenu'
> [apr 11 11:16:35] [debug]: updatePanelMenu  - 'updatePanelMenu'
> [apr 11 11:16:35] [debug]: updatePanelMenu  - 'updatePanelMenu'
> [apr 11 11:16:35] [debug]: updatePanelMenu  - 'updatePanelMenu'
> [apr 11 11:16:35] [debug]: updatePanelMenu  - 'updatePanelMenu'
> [apr 11 11:16:35] [debug]: updatePanelMenu  - 'updatePanelMenu'
> [apr 11 11:16:35] [debug]: updatePanelMenu  - 'updatePanelMenu'
> [apr 11 11:16:35] [debug]: updatePanelMenu  - 'updatePanelMenu'
> [apr 11 11:16:35] [debug]: updatePanelMenu  - 'updatePanelMenu'
> [apr 11 11:16:35] [debug]: updatePanelMenu  - 'updatePanelMenu'
> [apr 11 11:16:35] [debug]: updatePanelMenu  - 'updatePanelMenu'
> [apr 11 11:16:35] [debug]: updatePanelMenu  - 'updatePanelMenu'
> [apr 11 11:16:35] [debug]: updatePanelMenu  - 'updatePanelMenu'
> [apr 11 11:16:35] [debug]: storeSettings  - 'noteHistoryItem':  NoteHistoryItem: <noteName>"inizio" <noteSubFolderPathData>"" <cursorPosition>54 <relativeScrollBarPosition>0

**Comment by pbek** [comment]
Yes, and:

> Can you please post the output from the debug settings (see issue template).

**Comment by chrixxxx** [comment]
> Yes, and:
> 
> > Can you please post the output from the debug settings (see issue template).

I think you mean this.. ?

> ## Settings
> 
> **ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
> **Debug/fakeOldVersionNumber** (QString): `false`
> **Debug/fileLogging** (QString): `true`
> **Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
> **Editor/autoBracketClosing** (QString): `true`
> **Editor/autoBracketRemoval** (QString): `true`
> **Editor/disableCursorBlinking** (QString): `false`
> **Editor/editorWidthInDFMOnly** (QString): `true`
> **Editor/highlightCurrentLine** (QString): `true`
> **Editor/indentSize** (QString): `4`
> **Editor/useTabIndent** (QString): `false`
> **Editor/vimMode** (QString): `false`
> **LastUpdateCheck** (QDateTime): `2020-04-11T11:41:45.618`
> **LinkDialog/geometry** (QByteArray): `<binary data>`
> **MainWindow/geometry** (QByteArray): `<binary data>`
> **MainWindow/mainToolBar.iconSize** (QString): `24`
> **MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
> **MainWindow/noteSubFolderTreeWidgetExpandState-1**: *empty*
> **MainWindow/noteSubFolderTreeWidgetExpandState-2** (QString): `Youtubers`
> **MainWindow/noteTextEdit.code.font** (QString): `Courier New,10,-1,2,50,0,0,0,0,0`
> **MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,11,-1,5,50,0,0,0,0,0,Normale`
> **MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
> **MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
> **MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
> **MainWindow/noteTextView.rtl** (QString): `false`
> **MainWindow/noteTextView.underline** (QString): `true`
> **MainWindow/noteTextView.useEditorStyles** (QString): `true`
> **MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
> **MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
> **NoteHistory-1** (QVariantList): `<variant list with 13 item(s)>`
> **NoteHistory-2** (QVariantList): `<variant list with 17 item(s)>`
> **NoteHistoryCurrentIndex-1** (QString): `12`
> **NoteHistoryCurrentIndex-2** (QString): `16`
> **PiwikClientId** (QString): `<hidden>`
> **SearchEngineId** (QString): `2`
> **SettingsDialog/geometry** (QByteArray): `<binary data>`
> **SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
> **ShowSystemTray** (QString): `false`
> **StartHidden** (QString): `false`
> **WelcomeDialog/geometry** (QByteArray): `<binary data>`
> **acceptAllExternalModifications** (QString): `false`
> **allowNoteEditing** (bool): `true`
> **allowOnlyOneAppInstance** (QString): `true`
> **appMetrics/disableAppHeartbeat** (QString): `false`
> **appMetrics/disableTracking** (QString): `false`
> **appMetrics/notificationShown** (QString): `true`
> **automaticNoteFolderDatabaseClosing** (QString): `false`
> **checkSpelling** (bool): `false`
> **closeTodoListAfterSave** (QString): `false`
> **cryptoKey** (QString): `<hidden>`
> **currentNoteFolderId** (QString): `1`
> **currentWorkspace** (QString): `initial`
> **cursorWidth** (QString): `1`
> **customNoteFileExtensionList**: *empty*
> **darkMode** (QString): `false`
> **darkModeColors** (QString): `false`
> **darkModeIconTheme** (QString): `false`
> **darkModeTrayIcon** (QString): `false`
> **defaultNoteFileExtension** (QString): `md`
> **demoNotesCreated** (QString): `true`
> **disableAutomaticUpdateDialog** (QString): `false`
> **disableSavedSearchesAutoCompletion** (QString): `false`
> **dockWasInitializedOnce** (QString): `true`
> **enableNoteTree** (QString): `false`
> **enableSocketServer** (QString): `false`
> **externalEditorPath** (QString): *empty*
> **fullyHighlightedBlockquotes** (QString): `false`
> **gitCommitInterval** (QString): `30`
> **gitExecutablePath** (QString): *empty*
> **gitLogCommand** (QString): *empty*
> **guiFirstRunInit** (bool): `true`
> **ignoreAllExternalModifications** (QString): `false`
> **ignoreAllExternalNoteFolderChanges** (QString): `false`
> **ignoreNoteSubFolders** (QString): `^\.`
> **imageScaleDown** (QString): `false`
> **imageScaleDownMaximumHeight** (QString): `1024`
> **imageScaleDownMaximumWidth** (QString): `1024`
> **initialLayoutIdentifier** (QString): `minimal`
> **insertTimeFormat** (QString): *empty*
> **interfaceFontSize** (QString): `11`
> **interfaceLanguage** (QString): `en`
> **internalIconTheme** (QString): `false`
> **itemHeight** (QString): `15`
> **legacyLinking** (QString): `false`
> **localTrash/autoCleanupDays** (QString): `30`
> **localTrash/autoCleanupEnabled** (QString): `true`
> **localTrash/supportEnabled** (QString): `true`
> **markdownHighlightingEnabled** (QString): `true`
> **navigationPanelHideSearch** (QString): `false`
> **networking/ignoreSSLErrors** (QString): `true`
> **networking/proxyType** (QString): `2`
> **newNoteAskHeadline** (QString): `false`
> **noteEditIsCentralWidget** (QString): `true`
> **noteListPreview** (QString): `false`
> **noteSaveIntervalTime** (QString): `10`
> **noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
> **noteSubfoldersPanelHideSearch** (QString): `false`
> **noteSubfoldersPanelOrder** (QString): `0`
> **noteSubfoldersPanelShowFullPath** (QString): `false`
> **noteSubfoldersPanelShowNotesRecursively** (QString): `false`
> **noteSubfoldersPanelShowRootFolderName** (QString): `true`
> **noteSubfoldersPanelSort** (QString): `0`
> **notesPanelOrder** (QString): `0`
> **notesPanelSort** (QString): `1`
> **notesPath** (QString): `../../[Documenti]/[QOwnNotes] Notes`
> **notifyAllExternalModifications** (QString): `false`
> **overrideInterfaceFontSize** (QString): `false`
> **ownCloud/supportEnabled** (QString): `false`
> **ownCloud/todoCalendarBackend** (QString): `3`
> **ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
> **ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
> **ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
> **ownCloud/todoCalendarCloudConnectionId** (QString): `1`
> **ownCloud/todoCalendarDisplayNameList**: *empty*
> **ownCloud/todoCalendarEnabledList**: *empty*
> **ownCloud/todoCalendarEnabledUrlList**: *empty*
> **ownCloud/todoCalendarUrlList**: *empty*
> **ownCloudInfo/appIsValid** (bool): `false`
> **ownCloudInfo/connectionErrorMessage** (QString): *empty*
> **ownCloudInfo/notesPathExistsText** (QString): *empty*
> **ownCloudInfo/serverVersion** (QString): *empty*
> **recentNoteFolders** (QString): `K:/QOwnNotes [portable]/Data/../../[Documenti]/[QOwnNotes] Notes/Gaming`
> **restoreCursorPosition** (QString): `true`
> **restoreLastNoteAtStartup** (QString): `true`
> **savedSearches/noteFolder-1** (QStringList): `Note 2020-04-11T08.36.20, Note 2020-04-11T08.05.27, Note 2020-04-11T08.04.56`
> **savedSearches/noteFolder-2** (QStringList): `Note 2020-04-11T07.54.09, Note 2020-04-11T07.53.55, Note 2020-04-11T07.46.02, Note 2020-04-11T06.18.11, Note 2020-04-11T06.16.58`
> **showMatches** (QString): `true`
> **showMenuBar** (bool): `true`
> **showStatusBar** (bool): `true`
> **systemIconTheme** (QString): `false`
> **tagWasAddedToNote** (QString): `true`
> **taggingShowNotesRecursively** (QString): `false`
> **tagsPanelHideSearch** (QString): `false`
> **tagsPanelOrder** (QString): `0`
> **tagsPanelSort** (QString): `0`
> **todoCalendarSupport** (QString): `true`
> **toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
> **toolbar/1/name** (QString): `mainToolBar`
> **toolbar/1/title** (QString): `Barra degli strumenti principale`
> **toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
> **toolbar/2/name** (QString): `formattingToolbar`
> **toolbar/2/title** (QString): `barra degli strumenti formattazione`
> **toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
> **toolbar/3/name** (QString): `insertingToolbar`
> **toolbar/3/title** (QString): `barra degli strumenti "inserisci"`
> **toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
> **toolbar/4/name** (QString): `encryptionToolbar`
> **toolbar/4/title** (QString): `barra degli strumenti di crittografia`
> **toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
> **toolbar/5/name** (QString): `windowToolbar`
> **toolbar/5/title** (QString): `barra degli strumenti della finestra`
> **toolbar/6/items** (QString): `action_Quit`
> **toolbar/6/name** (QString): `quitToolbar`
> **toolbar/6/title** (QString): `esci dalla barra degli strumenti`
> **toolbar/size** (QString): `6`
> **useNoteFolderButtons** (QString): `false`
> **useUNIXNewline** (QString): `false`
> **webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
> **webSocketServerService/bookmarksTag** (QString): `bookmarks`
> **webSocketServerService/port** (QString): `22222`
> **workspace-initial/name** (QString): `Minimale`
> **workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
> **workspace-initial/windowState** (QByteArray): `<binary data>`
> **workspaces** (QString): `initial`

**Comment by pbek** [comment]
> I think you mean this.. ?

1) You removed the upper part, can you please add all of the dump. (you make it very hard to help you, there is an issue assistant in the *Window settings* of QOwnNotes for dealing with all this...) :sweat_smile: 

2) Are you in portable mode? I now tested in Linux and Windows with portable mode and didn't have your issue.

3) What happens if you use `/` in your note links, instead of `%2F`, like `[link to a note in a subdirectory](subdir/sub%20note%20target.md)`?

**Comment by pbek** [comment]
4) What happens if you rename `[portable]` to `portable`? (using such characters could always be tricky)

**Comment by chrixxxx** [comment]
> 1. What happens if you rename `[portable]` to `portable`? (using such characters could always be tricky)

That's the issue. 
I can confirm that if I remove square brackets from the paths (and the links) everything works at it should.

I usually use brackets in directory and file names in Windows because it's a convenient way to sort and "highlight" stuff... 

I think the problem may be the way your application parse and treat those bracket when they're part of a file path and not a sort of "syntax internal to the program itself.

**Comment by pbek** [comment]
I'll try to reproduce your situation.

**Comment by pbek** [comment]
I now renamed multiple folders (including the one the QOwnNotes binary is located) to something with `[]` on Windows and still had no issues.

**Comment by pbek** [comment]
What happens when you copy your notes folder inside the QOwnNotes folder? (and 1) and 2) are also still "open")

**Comment by chrixxxx** [comment]
> What happens when you copy your notes folder inside the QOwnNotes folder? (and 1) and 2) are also still "open")

Yes, it works this way for me too,  even with [ ] both in the program and notes folders names.

So the problem is not having square brackets in the path-filenames but when the notes folder is placed OUTSIDE the /data subdirectory from where you start the application (as it was for me in the beginning ... before following your previous advices and suggestions).

I think the application uses relative paths (at least in portable mode) and when the notes are placed in folder OUTSIDE it's directory something doesn't work anymore (at least on windows).

This was how the program stored the path name in the "node folder" settings page (it's a relative "addressing" from the application base directory):

"K:/QOwnNotes [portable]/Data/../../[Documenti]/[QOwnNotes] Notes"

Something goes wrong then the editor parses this for internal links, I suppose (if the note folder is placed OUTSIDE the program directory at least ).

**Comment by pbek** [comment]
Yes, all paths are relative path in portable mode, that's the reason it exists. At least I can reproduce it now.

**Comment by pbek** [comment]
I guess meanwhile you can always switch to "legacy links" in the *General settings*.

**Comment by chrixxxx** [comment]
> I guess meanwhile you can always switch to "legacy links" in the _General settings_.

Don't worry, I can keep them inside the application folder for now and switch later, since once you select a base folder for notes all the links are relative to that folder, so no problem, I'll change my notes directory in the future.

"Legacy Links" option works (I tried it before posting) but they only link "referring" to the note names, so if I have two or more notes with the same name (using subdirs it's possibile) it's impossibile to specify what note to "point at" with this option.

Thank you for having replied so fast and for the interest you showed up!!

**Comment by chrixxxx** [comment]
> Yes, all paths are relative path in portable mode, that's the reason it exists.

Yes, I know.

It may seem strange seeing someone using an application in portable mode and then storing data OUTSIDE it's folder, but it has its sense.

I have a drive with many applications that I use only in portable mode, because I like having their settings and everything related in the "right" place (the application directory)  and not having to search for them everywhere in system/user folders when I need them xD

But I keep ALL my user DATAs and documents for every portable application I use in another specific directory: and not only because it's easier to find them, but - more important - it's practical to backup them - all at the same time - without having to include every application folder with binaries, dlls and related stuff together with them.

**Comment by pbek** [comment]
Took a while...

## 20.4.5
- fixed note linking with sub-folders if note folder is outside of the application
  directory in portable mode

**Comment by pbek** [comment]
And it promptly breaks other stuff... :disappointed:

**Comment by chrixxxx** [comment]
> And it promptly breaks other stuff...

The programmer's life...

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by chrixxxx** [comment]
> There now is a new release, could you please test it and report if it works for you?

Just tried .. and everything seems fine : links between notes are working now, even if the notes are stored in a folder outside the mai program directory (in portable mode).

Thanks! That's really awesome:  problem solved after only few hours!!
: )

**Comment by pbek** [comment]
Thank you for testing.

It was a PITA to tackle... 😅  I hope it will not break too much other stuff. 😬 It might cause problems when people are working with symbolic links, because I had to use canonical paths to resolve the relative links that are outside the application folder.
