### ISSUE TITLE
[I] None Empty Sub Folders Cannot Be Renamed via Context Menu on Windows

### ISSUE THREAD

**Issue by teamayu** [pbek/QOwnNotes#1683]
#### Expected behaviour

Sub folder to be renamed after 'Rename subfolder' context menu is used.

#### Actual behaviour

When you right click a folder that has sub folders or notes and select "Rename subfolder", it cannot be changed. It reverts back after save. Empty folders are fine.

#### Steps to reproduce

Right click a none empty folder in the menu and from the context menu, select "Rename subfolder". Enter new name, hit return, folder reverts back to previous name.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[17:22:31] [debug] updatePanelMenu - 'updatePanelMenu'
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sat Apr 11 17:23:08 2020`
**Version**: `20.4.2`
**Build date**: `Apr  7 2020`
**Build number**: `5509`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `yes`
**Settings path / key**: `Q:/Portable-Software/QOwnNotes/Data/PBE/QOwnNotes.ini`
**Application database path**: `Q:\Portable-Software\QOwnNotes\Data\QOwnNotes.sqlite`
**Application arguments**: `Q:\Portable-Software\QOwnNotes\QOwnNotes.exe`, `--portable`
**Qt Debug**: `0`
**Locale (system)**: `en_GB`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1366x768`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `152`
**Calendar items**: `0`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `Q:\Portable-Software\QOwnNotes\Data\dicts`

## Note folders

**currentNoteFolderId**: `2`

### Note folder `Notes`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `-1`
**localPath**: `Q:\Portable-Software\QOwnNotes\Data\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `Q:\Portable-Software\QOwnNotes\Data\Notes\notes.sqlite`

### Note folder `Development`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `Q:\Portable-Software\QOwnNotes\Data\Dev`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `ANDROID & JAVA`
**database file**: `Q:\Portable-Software\QOwnNotes\Data\Dev\notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

### Script `External note open`

**id**: `1`
**path**: `Q:\Portable-Software\QOwnNotes\Data\scripts\external-note-open\external-note-open.qml`
**variablesJson**: 
```
{
    "executablePath": "Q:\\Portable-Software\\CudaText\\cudatext.exe"
}
```
**identifier**: `external-note-open`
**version**: `1.0.0`
**minAppVersion**: `18.05.4`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `23`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `false`
**Editor/autoBracketRemoval** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `Q:/Portable-Software/QOwnNotes/_Backup`
**FileDialog/LastPath-ExternalEditor** (QString): `Q:/Portable-Software/CudaText`
**FileDialog/LastPath-NotePDFExport** (QString): `C:/Users/David/Desktop`
**FileDialog/LastPath-ScriptSettingsFile-external-note-open-executablePath** (QString): `Q:/Portable-Software/CudaText`
**FileDialog/LastPath-SettingsExport** (QString): `Q:/Portable-Software/QOwnNotes/_Backup`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-04-11T16:33:03.540`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-2** (QStringList): `In Progress, In Progress/Maian Coin, ANDROID & JAVA/Course Apps, ANDROID & JAVA`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Calibri,14,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Courier New,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Calibri,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/issue-dialog-new-issue** (QString): `16384`
**MessageBoxOverride/move-notes** (QString): `16384`
**MessageBoxOverride/remove-folders** (QString): `16384`
**MessageBoxOverride/remove-notes** (QString): `16384`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteFolder-2/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 30 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `29`
**NoteHistoryCurrentIndex-2** (QString): `199`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExportOrientation** (QString): `0`
**Printer/NotePDFExportPageSize** (QString): `4`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `true`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `2`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `false`
**externalEditorPath** (QString): `../../CudaText/cudatext.exe`
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): `dd-MM-YYYY hh:mm:ss`
**interfaceFontSize** (QString): `12`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `24`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `true`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `0`
**notesPath** (QString): `Dev`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `44df9646-6cbc-49e8-b845-2bf19b0fdf56`
**recentNoteFolders** (QStringList): `Q:/Portable-Software/QOwnNotes/Data/Notes, Q:/Portable-Software/QOwnNotes/Data/../../../Users/David/Dropbox/Ayumi/_NOTES/_NOTES`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2020-02-29T14.27.21, Note 2020-01-18T12.46.12, Note 2019-07-13T15.58.27, Note 2019-07-13T15.56.42, Note 2019-07-13T15.56.29, Note 2019-07-13T15.56.22, Note 2019-07-13T15.56.07, Note 2019-07-13T15.55.14, Note 2019-07-13T15.55.07, Note 2019-07-13T15.53.11, Note 2019-07-13T15.52.10, Note 2019-07-13T15.41.08, Note 2019-07-13T14.03.56, Note 2019-07-12T17.24.10, Note 2019-07-12T17.22.07, Note 2019-07-12T16.37.06, Note 2019-07-07T19.40.22, Note 2019-07-07T19.40.10`
**savedSearches/noteFolder-2** (QStringList): `Note 2020-04-11T14.52.15, Note 2020-04-11T14.27.01, Note 2020-04-08T15.58.15, Note 2020-04-08T15.21.25, Note 2020-04-08T14.56.19, Note 2020-04-01T16.44.59, Note 2020-03-27T15.14.54, Note 2020-03-27T12.59.32, Note 2020-03-27T12.53.45, Note 2020-03-27T11.51.20, Note 2020-03-26T15.56.55, Note 2020-03-26T14.57.14, Note 2020-03-26T14.12.11, Note 2020-03-19T17.42.05, Note 2020-03-19T10.24.46, Note 2020-03-19T00.14.37, Note 2019-11-13T11.58.56, Note 2019-10-25T13.27.15, Note 2019-09-09T13.11.52, Note 2019-07-15T11.36.55, Note 2019-07-14T00.33.49, Note 2019-07-13T16.46.25, Note 2019-07-13T16.45.58, Note 2019-07-13T16.36.26, Note 2019-07-13T16.34.28, Note 2019-07-13T16.29.03, Note 2019-07-13T16.18.42, Note 2019-07-13T16.17.16, Note 2019-07-13T16.16.42`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `false`
**skipVersion** (QString): `19.7.3`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `true`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Export_note_as_PDF_text, actionShow_local_trash`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QString): `actionInsert_image`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-44df9646-6cbc-49e8-b845-2bf19b0fdf56/name** (QString): `Media`
**workspace-44df9646-6cbc-49e8-b845-2bf19b0fdf56/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-44df9646-6cbc-49e8-b845-2bf19b0fdf56/windowState** (QByteArray): `<binary data>`
**workspace-NuQkVAeD3P2U/name** (QString): `Daves Space`
**workspace-NuQkVAeD3P2U/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-NuQkVAeD3P2U/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Main Interface`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 44df9646-6cbc-49e8-b845-2bf19b0fdf56, NuQkVAeD3P2U`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\David\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `TEAM-AYU-HP`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DokanLibrary1**: `C:\Program Files\Dokan\Dokan Library-1.1.0\`
**DokanLibrary1_LibraryPath_x64**: `C:\Program Files\Dokan\Dokan Library-1.1.0\lib\`
**DokanLibrary1_LibraryPath_x86**: `C:\Program Files\Dokan\Dokan Library-1.1.0\x86\lib\`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\David`
**LOCALAPPDATA**: `C:\Users\David\AppData\Local`
**LOGONSERVER**: `\\TEAM-AYU-HP`
**NUMBER_OF_PROCESSORS**: `4`
**OneDrive**: `C:\Users\David\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;;C:\WINDOWS\System32\OpenSSH\;C:\Users\David\AppData\Local\Microsoft\WindowsApps;C:\Program Files\nodejs\;C:\Program Files (x86)\AOMEI Backupper;C:\Users\David\AppData\Local\Microsoft\WindowsApps;C:\Users\David\AppData\Roaming\npm`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PORTABLEPATH**: `Q:\Portable-Software`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `AMD64 Family 22 Model 48 Stepping 1, AuthenticAMD`
**PROCESSOR_LEVEL**: `22`
**PROCESSOR_REVISION**: `3001`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\David\AppData\Local\Temp`
**TMP**: `C:\Users\David\AppData\Local\Temp`
**USERDOMAIN**: `TEAM-AYU-HP`
**USERDOMAIN_ROAMINGPROFILE**: `TEAM-AYU-HP`
**USERNAME**: `David`
**USERPROFILE**: `C:\Users\David`
**VBOX_HWVIRTEX_IGNORE_SVM_IN_USE**: `1`
**windir**: `C:\WINDOWS`
**QML_DISABLE_DISK_CACHE**: `true`
</details>

**Comment by pbek** [comment]
Strange, I cannot reproduce that (on Linux) renaming note-subfolders with notes or other folders works fine.

**Comment by pbek** [comment]
I could reproduce this on Windows, very strange. Thank you for reporting.

**Comment by teamayu** [comment]
No problem. At the moment I can only get it to change if I rename the folder in explorer.

Here is a screen cap.

![ss](https://user-images.githubusercontent.com/10624092/79040674-b5d84700-7c1c-11ea-8481-6d9c2e3006bf.gif)

**Comment by teamayu** [comment]
I have closed and re-opened the software, but still the same result.

**Comment by teamayu** [comment]
> I could reproduce this on Windows, very strange. Thank you for reporting.

You are welcome Patrizio, glad you could replicate it.

**Comment by pbek** [comment]
Working on it for several hours now, the only thing I found out is that under Windows the renaming of the QDir fails, I've still no idea why. It works everywhere else.

https://github.com/pbek/QOwnNotes/blob/25068e622e4ad4c315b2f7e5a1d208a21ed7bc44/src/entities/notesubfolder.cpp#L185

**Comment by teamayu** [comment]
Is it a permissions issue? When I try to rename in explorer it gives me an error saying that the folder is already open in another application. If I close QON then it works. So, maybe the rename is along the same lines? It can't rename the folder because the folder is active?

**Comment by pbek** [comment]
> When I try to rename in explorer it gives me an error saying that the folder is already open in another application. 

I suspected such a thing, but I can't prove that because `QDir::rename` just returns `false`. But your test maybe helped me to get in the right direction.

But I don't know why there should be a file open. All notes are in memory.

**Comment by pbek** [comment]
Maybe it's the file system watcher.. But that shouldn't be the case.

**Comment by pbek** [comment]
I hope I can find a workaround, will not be easy. Windows is pretty adamant about access to "open files". For now I do this:

## 20.4.5
- now an error message in the log is shown if renaming of note subfolders fail

**Comment by teamayu** [comment]
> I hope I can find a workaround, will not be easy. Windows is pretty adamant about access to "open files". For now I do this:
> 
> ## 20.4.5
> * now an error message in the log is shown if renaming of note subfolder fails

That's fine. I assume earlier versions were the same? I'm surprised this issue hasn't been reported before on Windows.

**Comment by pbek** [comment]
Yes, it's an "issue" of Windows in general. I also wonder why that wasn't reported before.

**Comment by pbek** [comment]
I can rename sub-folders if they contain notes. But they must not contain other sub-folders.

**Comment by teamayu** [comment]
Same here.

**Comment by pbek** [comment]
I was able to rename if if I created the child-sub-folder outside of QON and QON didn't recognize the child-sub-folder yet :grin:

**Comment by teamayu** [comment]
Makes sense. For me it's not that big an issue, I'm happy to close the software, rename the folders in explorer and open again. I don't rename them that often, which is probably why I never saw this issue before and I'm guessing other people either don't bother renaming or just don't have many sub folders?

**Comment by pbek** [comment]
Hah, found it. It's Qt's noteDirectoryWatcher, that watches over changes of files and directories. As long a sub-folder of a folder to rename is watched Windows blocks the renaming.

**Comment by teamayu** [comment]
Fantastic.

**Comment by pbek** [comment]
## 20.4.6
- fixed renaming of note sub-folders under Windows if the folders contain other sub-folders

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by teamayu** [comment]
Confirmed as working. Thanks for the fix. :)

**Comment by pbek** [comment]
Great, thank you for testing!
