### ISSUE TITLE
to much white space in distraction free mode

### ISSUE THREAD

**Issue by schiessle** [pbek/QOwnNotes#1684]
For my taste the distraction free mode has to much white space left and right, leaving to less space for the actual content. Therefore I would suggest two improvements:

1. let the user configure how much characters should fit into one line. I think that's the most generic metric to define the length of a line, 80 chars seems to be a good default.
2. If the user increases the font size, the distraction free mode should stick to the number of characters as long as they fit in one line.

This would solve two problems: Users could configure the size of the content area of the distraction free mode and with increasing/decreasing the font size they can adjust it to the screen size.

What do you think?

**Comment by pbek** [comment]
1) That's already implemented in the Windows menu, isn't it? You can choose a custom width.
2) The problem with that is you can ever set a content margin in pixel, I always need to try to estimate the pixels by measuring the width of one "standard character". Better stick to 1)

**Comment by schiessle** [comment]
perfect, didn't saw this setting before! :smile:

**Comment by pbek** [comment]
:D
