### ISSUE TITLE
Fix invalid "help" link to time formats

### ISSUE THREAD

**Issue by gelldur** [pbek/QOwnNotes#1685]
In settings as you can see on image:
![image](https://user-images.githubusercontent.com/175790/79064097-53c42400-7ca6-11ea-88e0-528d21307d9f.png)

There is link: http://docs.qownnotes.org/en/develop/time-formats.html
It should be: http://docs.qownnotes.org/en/latest/editor/time-formats/

----
App: QOwnNotes - version 20.4.2 - AUR - build 691
Built on Apr 8 2020 with Qt 5.14.1.

**Comment by pbek** [comment]
Thank you for reporting, that's a regressions from the documentation page relaunch.

**Comment by pbek** [comment]
## 20.4.5
- fixed the time formats link in the *Editor settings*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by gelldur** [comment]
Confirm it is working ;)

**Comment by pbek** [comment]
Great, thank you for testing!
