### ISSUE TITLE
[Feature request] an option to hide/show the editor panel. 

### ISSUE THREAD

**Issue by chrixxxx** [pbek/QOwnNotes#1687]
I appreciate very much the possibility to create custom workspaces, but I found that it's impossible to create a workspace where the editor panel/window is hidden. It's the only panel without an option to show/hide.

When I search through my notes (using tags) and read them, clicking on links to open the browser or to switch to some other notes, I like to have a workspace showing the preview panel/window but not the editor panel/window, Having both these panels active in the same workspace is necessary and useful when you're creating and writing notes, but  when you're simply browsing through them it's not: it's only confusing and the editor panel steals some precious space too.

**Comment by pbek** [comment]
Again and for all reported feature requests / issues / questions. Please fill out the issue template or use the issue assistant of QOwnNotes. It's hard to know what we are talking about if you don't. 😆 

You can hide it. This might help you: https://github.com/pbek/QOwnNotes/issues/1170#issuecomment-477665766

If that that answers your question feel free to close the issue.

**Comment by chrixxxx** [comment]
> You can hide it. This might help you: [#1170 (comment)](https://github.com/pbek/QOwnNotes/issues/1170#issuecomment-477665766)

HOW COULD I MISS it ?????

Thanks again, closing it now.
