### ISSUE TITLE
Enhancement: Keyboard shortcut for switching note folder

### ISSUE THREAD

**Issue by dwu** [pbek/QOwnNotes#169]
I use a number of note folders for storing my notes and keeping private and work notes as well as different projects separate.

Switching note folders currently seems to be possible only via the "Note" -> "Note folders" menu. Would it be possible to additionally allow switching note folders via a keyboard shortcut?

The keyboard shortcut could e.g. open a dialog showing a list of the configured note folders and maybe an incremental filter bar for filtering by folder name (visually similar to the "search or create note" filter).

![select_note_folder](https://cloud.githubusercontent.com/assets/91804/15281357/abc72cdc-1b3a-11e6-8490-b95393dc8c4e.png)

**Comment by pbek** [comment]
If you go to the interface settings there is a checkbox `Show note folders in main area`. If you check it you'll see an additional select box. Would it be sufficient to add a shortcut for that select box? Hm, maybe even showing it just for the selection-duration if the checkbox wasn't checked...

**Comment by pbek** [comment]
On a side note: In your example you used different folders for each project, was that on purpose? Because there also are tags in QOwnNotes. ;)

**Comment by dwu** [comment]
Great, hadn't seen the option for showing the folder select box. Thanks for the hint! Having a keyboard shortcut for focusing that select box would be absolutely sufficient for my needs.

Regarding the reason for using folders instead of tags: I really like the tags feature and use it heavily on my personal notes. Using different folders for different projects however has the advantage of per-project media folders for automatic attachment handling while still having self-contained projects.

**Comment by pbek** [comment]
I will see what I can do.

> Regarding the reason for using folders instead of tags

Sounds legit :)

**Comment by pbek** [comment]
for the next release:

- there now is a new shortcut <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>F</kbd>
  that lets you select a different note folder

**Comment by dwu** [comment]
Wow, that was fast. :) Thanks a lot!

**Comment by pbek** [comment]
16.05.13 is now released

**Comment by dwu** [comment]
I've just tested the feature. Works great.

There's one minor issue I noticed where I'm not sure whether this was intentional or not. When "Show note folders in main area" is unchecked and the folder selection is canceled by pressing Escape, the drop-down menu remains visible until another folder is selected successfully.

**Comment by pbek** [comment]
Thank you for testing. Yes, I know. I found now way around that yet... Maybe I'll find a workaround...

**Comment by pbek** [comment]
Oh wow, that took hours... but now it works...

will be in 16.05.15...

- the note folder select box is now hidden correctly every time, if it should
  not be viewed and was triggered by the shortcut
  (for [Issue #169](https://github.com/pbek/QOwnNotes/issues/169))
