### ISSUE TITLE
Move notes to subfolders

### ISSUE THREAD

**Issue by sciurius** [pbek/QOwnNotes#1692]
#### General question

I have a single notes collection with several (sub)folders. I can't seem to find how to move notes between subfolders.

The context menu does not have a "move note" choice.

Drag/drop a note from the notes list doesn't work (dragging just selects more notes).

I'm probably overlooking something trivial, but what?

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Apr 14 15:00:40 2020`
**Version**: `20.4.6`
**Build date**: `Apr 13 2020`
**Build number**: `695`
**Platform**: `linux`
**Operating System**: `Fedora 31 (MATE-Compiz)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.12.5`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
**Settings path / key**: `/home/jv/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/jv/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_GB`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `mate`
**Notes in current note folder**: `65`
**Calendar items**: `0`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: `https://cloud.squirrel.nl`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `18.0.3.0`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: `auto`
**Language codes**: `en_AG, en_AU, en_BS, en_BW, en_BZ, en_CA, en_DK, en_GB, en_GH, en_HK, en_IE, en_IN, en_JM, en_MW, en_NA, en_NG, en_NZ, en_PH, en_SG, en_TT, en_US, en_ZA, en_ZM, en_ZW`
**Language names**: `English (Antigua & Barbuda), Australian English (Australia), English (Bahamas), English (Botswana), English (Belize), Canadian English (Canada), English (Denmark), British English (United Kingdom), English (Ghana), English (Hong Kong SAR China), English (Ireland), English (India), English (Jamaica), English (Malawi), English (Namibia), English (Nigeria), English (New Zealand), English (Philippines), English (Singapore), English (Trinidad & Tobago), American English (United States), English (South Africa), English (Zambia), English (Zimbabwe)`
**Application dictionaries path**: `/home/jv/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/jv/QNotes`
**remotePath**: `Notes/NCNotes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `xfer`
**database file**: `/home/jv/QNotes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://cloud.squirrel.nl`
**username**: `jv`

### Script `Toggle checkbox`

**id**: `1`
**path**: `/home/jv/.local/share/PBE/QOwnNotes/scripts/toggle-checkbox/toggle-checkbox.qml`
**variablesJson**: 
```
{
    "multipleLinesMethod": "cycleIndividually"
}
```
**identifier**: `toggle-checkbox`
**version**: `1.0.0`
**minAppVersion**: `19.3.2`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**FileDialog/LastPath** (QString): `/home/jv/tmp/xx`
**FileDialog/LastPath-ExternalEditor** (QString): `/home/jv/bin`
**FileDialog/LastPath-ImportTextFiles** (QString): `/home/jv/tmp/xx`
**FileDialog/LastPath-InsertImage** (QString): `/home/jv/tmp/markdown-here.wiki/images`
**FileDialog/LastPath-NotePDFExport** (QString): `/home/jv/tmp`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-04-14T14:51:24.342`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Liberation Sans,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Liberation Sans,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `false`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `199`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExport** (QByteArray): `<binary data>`
**Printer/NotePrinting** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `true`
**StartHidden** (bool): `false`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `personal`
**VersionDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `true`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): `/home/jv/bin/cemacs`
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): `yyyy-MM-dd hh:mm`
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (int): `17`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `false`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `0`
**notesPath** (QString): `/home/jv/QNotes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/ignoreNonTodoCalendars** (QString): `false`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (int): `2`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): `https://davical.squirrel.nl`
**ownCloud/todoCalendarCalDAVUsername** (QString): `jv`
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `18.0.3.0`
**previousWorkspace** (QString): `2bf359de-3071-4537-aafb-d13fdf98e843`
**recentNoteFolders** (QStringList): `/home/jv/Cloud/Nextcloud/Notes/NCNotes`
**restoreCursorPosition** (bool): `true`
**restoreLastNoteAtStartup** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2020-03-18T11.06.19`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (bool): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**versionSplitterSizes** (QByteArray): `<binary data>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-2bf359de-3071-4537-aafb-d13fdf98e843/name** (QString): `minimal`
**workspace-2bf359de-3071-4537-aafb-d13fdf98e843/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-2bf359de-3071-4537-aafb-d13fdf98e843/windowState** (QByteArray): `<binary data>`
**workspace-957d56a6-f31f-4cfb-9fa7-1653ec4d8a8f/name** (QString): `full`
**workspace-957d56a6-f31f-4cfb-9fa7-1653ec4d8a8f/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-957d56a6-f31f-4cfb-9fa7-1653ec4d8a8f/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `957d56a6-f31f-4cfb-9fa7-1653ec4d8a8f, 2bf359de-3071-4537-aafb-d13fdf98e843, initial`

## System environment

**SHELL**: `/bin/tcsh`
**IMSETTINGS_INTEGRATE_DESKTOP**: `yes`
**SESSION_MANAGER**: `local/unix:@/tmp/.ICE-unix/6608,unix/unix:/tmp/.ICE-unix/6608`
**CVSROOT**: `:pserver:cvs@phoenix.squirrel.nl:/usr/local/cvs`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**LESSCHARSET**: `utf-8`
**GROUP**: `jv`
**MACHTYPE**: `x86_64`
**HOSTNAME**: `phoenix.squirrel.nl`
**PSRESOURCEPATH**: `/home/jv/lib/fonts/upr::`
**I_WANT_A_BROKEN_PS**: `yes`
**X_NUM_SCREENS**: `1`
**SSH_AUTH_SOCK**: `/run/user/2048/keyring/ssh`
**RCSINIT**: `-zLT`
**XMODIFIERS**: `@im=none`
**DESKTOP_SESSION**: `mate`
**SSH_AGENT_PID**: `6576`
**GPG_TTY**: `/dev/pts/1`
**LMOD_DIR**: `/usr/share/lmod/lmod/libexec`
**EDITOR**: `cemacs`
**XDG_SEAT**: `seat0`
**MATE_DESKTOP_SESSION_ID**: `this-is-deprecated`
**PWD**: `/home/jv/tmp`
**RSYNC_RSH**: `ssh`
**LOGNAME**: `jv`
**XDG_SESSION_DESKTOP**: `mate`
**XDG_SESSION_TYPE**: `x11`
**X_WIDTH**: `1920`
**MODULESHOME**: `/usr/share/lmod/lmod`
**MANPATH**: `:/usr/share/lmod/lmod/share/man:/usr/local/share/man:/usr/share/man`
**PGPPATH**: `/home/jv/.pgp`
**XAUTHORITY**: `/run/lightdm/jv/xauthority`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/jv`
**CVSREAD**: `1`
**HOME**: `/home/jv`
**LANG**: `en_GB.utf8`
**XDG_CURRENT_DESKTOP**: `MATE`
**LMOD_SETTARG_FULL_SUPPORT**: `no`
**OSTYPE**: `linux`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**PERL5LIB**: `/home/jv/lib/perl5`
**TARG_TITLE_BAR_PAREN**: ` `
**LMOD_VERSION**: `8.1.17`
**IMSETTINGS_MODULE**: `none`
**TT2SITE_LIB**: `/home/jv/src/tt2site/lib`
**MODULEPATH_ROOT**: `/usr/share/modulefiles`
**XDG_SESSION_CLASS**: `user`
**LMOD_PKG**: `/usr/share/lmod/lmod`
**TERM**: `xterm-256color`
**GTK_OVERLAY_SCROLLING**: `0`
**HOST**: `phoenix.squirrel.nl`
**USER**: `jv`
**VISUAL**: `cemacs`
**DISPLAY**: `:0`
**LMOD_ROOT**: `/usr/share/lmod`
**LMOD_SETTARG_CMD**: `:`
**SHLVL**: `1`
**LOCPATH**: `/home/jv/.config/locale`
**BASH_ENV**: `/usr/share/lmod/lmod/init/bash`
**PAGER**: `less`
**LMOD_sys**: `Linux`
**QT_IM_MODULE**: `xim`
**CVS_RSH**: `ssh`
**XDG_VTNR**: `1`
**XDG_SESSION_ID**: `2`
**XDG_RUNTIME_DIR**: `/run/user/2048`
**S_COLORS**: `auto`
**QUOTING_STYLE**: `literal`
**KDEDIRS**: `/usr`
**PERL6LIB**: `/home/jv/lib/perl6`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**VENDOR**: `unknown`
**X_HEIGHT**: `1080`
**PATH**: `/bulk/perlbrew/bin:.:/home/jv/bin:/home/jv/.perl6/bin:/home/jv/.local/bin:/home/jv/node_modules/.bin:/usr/local/bin:/bin:/usr/bin`
**MODULEPATH**: `/etc/modulefiles:/usr/share/modulefiles:/usr/share/modulefiles/Linux:/usr/share/modulefiles/Core:/usr/share/lmod/lmod/modulefiles/Core`
**GDMSESSION**: `mate`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/2048/bus`
**LMOD_CMD**: `/usr/share/lmod/lmod/libexec/lmod`
**MAIL**: `/var/spool/mail/jv`
**HOSTTYPE**: `x86_64-linux`
**QT_SCALE_FACTOR**: `1`
**ROOT_BGCOLOR**: `LightSkyBlue3`
**WINDOWID**: `102760482`
**XTERM_VERSION**: `XTerm(351)`
**XTERM_LOCALE**: `en_GB.utf8`
**XTERM_SHELL**: `/bin/tcsh`
**LS_COLORS**: `no=0:fi=0:di=0:ln=0:pi=0:so=0:bd=0:cd=0:ex=0:mi=1;31:or=1;31`
**PERLBREW_CSHRC_VERSION**: `0.62`
**PERLBREW_HOME**: `/home/jv/.perlbrew`
**PERLBREW_ROOT**: `/bulk/perlbrew`
**PERLBREW_MANPATH**: *empty*
**PERLBREW_PATH**: `/bulk/perlbrew/bin`
**PERLBREW_VERSION**: `0.62`
**PATH_WITHOUT_PERLBREW**: `.:/home/jv/bin:/home/jv/.perl6/bin:/home/jv/.local/bin:/home/jv/node_modules/.bin:/usr/local/bin:/bin:/usr/bin`
**MANPATH_WITHOUT_PERLBREW**: `/usr/share/lmod/lmod/share/man:/usr/local/share/man:/usr/share/man`
**BODHI_USER**: `sciurius`
</details>

![x](https://user-images.githubusercontent.com/1118804/79228217-5fa81580-7e61-11ea-9947-dbf3d1f44e4b.png)

**Comment by PurplePlums** [comment]
![Bildschirmfoto 2020-04-14 um 15 07 48](https://user-images.githubusercontent.com/32141324/79228446-bdd4f880-7e61-11ea-9b46-7bb94e792a1b.png)
and there you should find the option to move notes...

**Comment by sciurius** [comment]
![x](https://user-images.githubusercontent.com/1118804/79228625-0e4c5600-7e62-11ea-8ee1-fa20ca617bd7.png)

**Comment by pbek** [comment]
@sciurius, you are using the experimental note tree feature (#790), correct? That may not be implemented yet.

If that that answers your question feel free to close the issue. :grin:

**Comment by sciurius** [comment]
I wasn't aware this was experimental. Sorry to bother.

I heavily depend on hierarchically structured notes, so I have to postpone further evaluation until this is operational.

**Comment by pbek** [comment]
> I wasn't aware this was experimental.

The checkbox in the settings tells you :grin: 

> I heavily depend on hierarchically structured notes

A note tree doesn't scale with 1000s of notes and a lot of folders. Thus the sub-folder tree widget plus the separate note list.

**Comment by sciurius** [comment]
There are several implementations of tree widgets that support lazy loading, so scaling doesn't need to be an issue.

**Comment by pbek** [comment]
Are you talking about C++/Qt TreeWidgets here?

But in any way I wasn't talking about the application performance. I was talking about that is was hard to look at a tree of 10 levels deep with 100s of notes in each folder. So the community decision (after people with a lot of notes tested my initial note tree implementation) was not to have a tree of notes and folders together. :grin:

**Comment by sciurius** [comment]
I think it is up to me to decide whether (and how) I want to look at a tree of 10 levels deep with 100s of notes in each folder...

Anyway, now I have a tree view of the folders, and clicking on a folder shows the notes in this folder. Great, I can live with that. Thanks!

**Comment by pbek** [comment]
Strong words. Let's now see some action. You don't need to live with it, I am now thrilled to receive your pull requests to improve the work in progress! 👍🏻
