### ISSUE TITLE
Clearing Shortcuts

### ISSUE THREAD

**Issue by kghenderson** [pbek/QOwnNotes#1693]
How do I clear a shortcut in the settings menu?

I've tried backspace, delete, etc, but I want to make it unassigned,
the clear button reverts to the QON default. 

Ideally for me, there would be a picklist at the top to read basic keymap files,
then all of the keybindings could be imported from those defaults.

then the buttons next to the functions could clear the value and not revert. 

This way we could eventually have multiple/changeable/importable configurations
for different systems that are also portable.

**Comment by pbek** [comment]
> How do I clear a shortcut in the settings menu?

Currently you cannot set a shortcut to nothing (at least not in the settings dialog, you could maybe tweak it in the settings). I need to evaluate how easy it would be to allow that.

> Ideally for me, there would be a picklist at the top to read basic keymap files,

Who defines those?

> This way we could eventually have multiple/changeable/importable configurations
for different systems that are also portable.

Currently you could export your settings in the *General settings* and extract the keybindings part and remove the rest. This files should be importable somewhere else.

**Comment by kghenderson** [comment]
That's really cool, I didn't realize you could import settings in parts! 

I'd just like to be able to share my bindings with others without them needing to have their entire configuration set back. I've spent quite a lot of time sorting out shortcuts that work consistently across many applications and teammates have asked for them.  Others I know are particular about there own. They could export their own, try something else and switch them back.

I think initially just the QON defaults of course, like you have, but maybe there are different schemes in the future which people could contribute in some form. I could see a case for vim-like, emacs-like, intellij, vscode, etc. 

If you check out VSCode actually, there's a 'Keyboard Shortcuts' to look up and define your own, but there's also 'Keymaps' which have many various conventions. 

Some examples:
![image](https://user-images.githubusercontent.com/3522168/79333709-ff5eb580-7eec-11ea-8d3f-7c9793e908f7.png)

![image](https://user-images.githubusercontent.com/3522168/79333815-2ae1a000-7eed-11ea-8f93-8e5aaa7016dd.png)

**Comment by kghenderson** [comment]
And to be clear, really my simple issue is that I want to use a custom binding but something else already has it assigned but I can't clear the other one, so I have to make new ones up for those that won't be used, like ctrl+alt+shift+f1. 

Having pre-configurable ones just takes it a step further and allows for better/easier/more portable integration, but it's a nice to have and not super critical or anything.

**Comment by pbek** [comment]
> Keymaps

Are you willing to define (and maintain for future actions with shortcuts) such different keymaps for different scenarios? For example as settings dump.

**Comment by kghenderson** [comment]
I think that QON is a really awesome application. I use it myself (amongst a few others) and have personally installed and configured it on probably 6 or 7 other people's machines. True story, the last developer I was training I showed 4 or 5 different notetaking applications to and I said she could choose any of them but she had to pick one and learn it, and she chose yours and said 'I'll use this one, I like this one.'  and now it's been a few months since then and she still does!  :-D  

For this particular shortcuts issue, I really just want a way to clear the built-in shortcuts so I could define my own, because I'm personally just particular about having them be consistent across the different applications I use, it lowers the friction :-) 

I didn't mean to suggest that you, me, or anyone, need to build all of those out for every editor, I was simply trying to help by demonstrating that it's something that some other apps do. I think that QON is the kind of application that attracts people who might want to set their own anyway, but when people are first learning it becomes ingrained and so those initial defaults can sometimes be important.  

... All that said, I think your answer/question is completely reasonable and you've clearly put a tremendous amount of effort into building a great solution for us all, and you owe me/us nothing, and if we ask for something, we should be willing to give something back :-)

I'm happy to provide my own shortcuts/configuration and contribute back to the application, and yes, I will _consider_ doing that for some other apps too (can't for at least a few weeks), but what would be _ideal_ would be a basic standard that could be integrated and shared with apps as well, or even better to find and improve an existing one. 

For better or worse, VSCode is open source, cross platform, and drawing the most developer attention these days and the configuration is all basic JSON, so maybe there's a way to leverage it directly? 

Look how many of them there are! 

https://marketplace.visualstudio.com/search?target=VSCode&category=Keymaps&sortBy=Relevance

Anyway, sorry for the long post, got carried away :-) This isn't actually a huge issue for me to set a fake shortcut, just thought I'd raise it. If I was pulling favors there are other things I would choose :-D

Hope your doing well, happy quarantine :-)

**Comment by pbek** [comment]
Thank you for your QON-Success-Story! :laughing: :partying_face: 
I clearly will look into the "clearing shortcuts matter". :grin: 

If someone is starting to contribute shortcut settings I surely will investigate more on how to integrate importing and exporting them more easily (maybe like with the editor schemes). Meanwhile importing them as settings file should work.

**Comment by pbek** [comment]
Wasn't easy, but it should work now. :grin: 

## 20.4.8
- you can now also **clear local shortcuts** in the *Shortcuts settings*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by kghenderson** [comment]
I saw the update come and it brought me much joy, 
It's perfect, you are amazing, thank you. :-)

**Comment by pbek** [comment]
🎉 Great, thank you for testing! 😁
