### ISSUE TITLE
New editor schema: Atom One Dark Reasonable

### ISSUE THREAD

**Issue by leoniscsem** [pbek/QOwnNotes#1694]
I want to submit a new editor schema. It is _loosely_ based on the **Atom One Dark Reasonable** colour scheme from [highlight.js](https://github.com/highlightjs/highlight.js/blob/master/src/styles/atom-one-dark-reasonable.css), adapted from the built-in set Dark. Yet I had to make some changes, as the colour scheme could not be converted 100% to QownNote's notation.

Works best with (boring standard) font settings:
**Sans-Serif**: 11
**Monospace**: 10

![atom-one-dark-resonable](https://user-images.githubusercontent.com/6514726/79465377-d560dc80-802d-11ea-8364-39a149967d47.png)

[Atom-One-Dark-Reasonable.zip](https://github.com/pbek/QOwnNotes/files/4487579/Atom-One-Dark-Reasonable.zip)

**Comment by pbek** [comment]
Looking good, thank you very much! :grin:

**Comment by pbek** [comment]
## 20.4.7
- added a **new editor color schema** *Atom One Dark Reasonable* by @leoniscsem

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by leoniscsem** [comment]
Whoa, you were fast with updating the PPA. Yes, works perfectly fine. I might tinker with the scheme a while and tinker with the font settings, especially for the code rendering.

(_& an schean Gruaß noch Graz_)

**Comment by pbek** [comment]
Sure. Thank you for testing. :wink: 

(liebe Grüße nach Beijing :smile:)
