### ISSUE TITLE
May I ask you to publish preliminary releases less often?

### ISSUE THREAD

**Issue by mrkaban** [pbek/QOwnNotes#1695]
May I ask you to publish preliminary releases less often?

Your program is published on a site with traffic of 1,500 people a day, and I need to update links, including download links, so I need a subscription to new versions, but so many notifications are unbearable. I got up in the morning, and there are 15 notifications.

**Comment by bendem** [comment]
You might want to automate your site's update (or just link to the download page, why aren't you?).

It's fairly easy to ask github for the latest release: 
```bash
➜  ~ curl -s https://api.github.com/repos/pbek/QownNotes/releases | jq '[.[] | select(.prerelease == false) | { tag_name, link: (.assets[].browser_download_url) }] | .[:3]'  
[
  {
    "tag_name": "windows-b5554",
    "link": "https://github.com/pbek/QOwnNotes/releases/download/windows-b5554/QOwnNotes.zip"
  },
  {
    "tag_name": "macosx-b5516-170140",
    "link": "https://github.com/pbek/QOwnNotes/releases/download/macosx-b5516-170140/QOwnNotes-20.4.7.dmg"
  },
  {
    "tag_name": "linux-b5516-165503",
    "link": "https://github.com/pbek/QOwnNotes/releases/download/linux-b5516-165503/QOwnNotes-20.4.7.deb"
  }
]
```

**Comment by mrkaban** [comment]
> You might want to automate your site's update (or just link to the download page, why aren't you?).
> 
> It's fairly easy to ask github for the latest release:
> 
> ```shell
> ➜  ~ curl -s https://api.github.com/repos/pbek/QownNotes/releases | jq '[.[] | select(.prerelease == false) | { tag_name, link: (.assets[].browser_download_url) }] | .[:3]'  
> [
>   {
>     "tag_name": "windows-b5554",
>     "link": "https://github.com/pbek/QOwnNotes/releases/download/windows-b5554/QOwnNotes.zip"
>   },
>   {
>     "tag_name": "macosx-b5516-170140",
>     "link": "https://github.com/pbek/QOwnNotes/releases/download/macosx-b5516-170140/QOwnNotes-20.4.7.dmg"
>   },
>   {
>     "tag_name": "linux-b5516-165503",
>     "link": "https://github.com/pbek/QOwnNotes/releases/download/linux-b5516-165503/QOwnNotes-20.4.7.deb"
>   }
> ]
> ```

The option is certainly interesting, but you still need to fill in the versions. Therefore, no less work.

**Comment by bendem** [comment]
I was implying that you could write a script that does the update for you, and run it every day or so. Or since it's a website, a piece of javascript that loads the latest version of QOwnNotes when the user loads the page.

No hard feelings, but as a user, I wouldn't want to get features less frequently just because a third party is manually encoding updates in an unrelated website.

**Comment by mrkaban** [comment]
> I was implying that you could write a script that does the update for you, and run it every day or so. Or since it's a website, a piece of javascript that loads the latest version of QOwnNotes when the user loads the page.
> 
> No hard feelings, but as a user, I wouldn't want to get features less frequently just because a third party is manually encoding updates in an unrelated website.

There is logic in your words, and I understand you well. But you understand me, I like the program, but getting 100 notifications per day from one page is too much. Unfortunately, using a script is not suitable.

It turns out tupit, you do not want it to be as convenient to me, but I do not want the way it would be convenient for you.

**Comment by pbek** [comment]
> May I ask you to publish preliminary releases less often?

What exactly are we talking about? 
"Things that are published to https://github.com/pbek/QOwnNotes/releases"?

You could use the release RSS Feed https://feeds.feedburner.com/QOwnNotesReleases (that will be generated from the ChangeLog).

**Comment by mrkaban** [comment]
> > Могу ли я попросить вас публиковать предварительные релизы реже?
> 
> О чем конкретно мы говорим?
> «Вещи, которые опубликованы на https://github.com/pbek/QOwnNotes/releases »?

Yes.

> 
> Вы можете использовать выпуск RSS Feed https://feeds.feedburner.com/QOwnNotesReleases (который будет сгенерирован из ChangeLog).

Oh yes, RSS is the perfect solution. An RSS client is not a mail notification. Thanks!

**Comment by pbek** [comment]
Great. 🎉 😁 

Between me and you an advice from my content-creation times, you really should think about automating stuff. It will save you a lot of time in the end. 😉
