### ISSUE TITLE
Note in 2nd level sub-folder not shown in note-list after clicking on `All notes` in subfolder panel and filtering by tag

### ISSUE THREAD

**Issue by chrixxxx** [pbek/QOwnNotes#1696]
This bug only happens if you have more than one level of sub-folders.

To replicate is quite easy:

1 .Create a subfolder named Alpha
2. Go into this sub-folder and create inside another subfolder into it, name it "subAlpha"
3. Create a note into this "2nd level" subfolder ( [baseNoteDir]/Alpha/subAlpha ).
4. Add a tag to this note ("test tag")
5. Select all the notes.
6. Now try filtering through the tag "test tag".
7. No results are shown.

Tag is still associated to the note but when you filter by tags the note from the second level of subfolders (subAlpha) is not shown among the results.

Here's a video, to make it easier at possibile to replicate the issue.
[2020-04-17-18-51-46.zip](https://github.com/pbek/QOwnNotes/files/4494260/2020-04-17-18-51-46.zip)

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue.

**Comment by pbek** [comment]
Took a while to reproduce it (you really don't like to fill out the issue template, don't you? :grin:)

**Comment by pbek** [comment]
By `5. Select all the notes.` you meant `5. Click on "All notes" in the sub-folder panel`, right?

**Comment by pbek** [comment]
## 20.4.9
- notes in 2nd level sub-folders (or deeper) are now shown correctly in the note-list after
  clicking on `All notes` in the subfolder panel and filtering by tag

**Comment by pbek** [comment]
And this one is also for you, so I can at least see if you are in portable mode (because you hardly ever fill out the issue template) :stuck_out_tongue: 

## 20.4.9
- if the application is in "portable mode" then this will now also be shown in
  the title bar

There now is a new release, could you please test it and report if it works for you?

**Comment by chrixxxx** [comment]
Tested 20.4.9 all yesterday, and this morning.. did it **very thoroughly**  (that's the reason why I'm posting this only now).

In these last 30 minutes  I did the same with the new 20.4.10 .. and i can confirm the issue with not showing items in subfolders when filtering through tags seems to be resolved.

But while doing so many test I found two new issues: 

1. some "inconsistencies" in the number of notes shown in the tag panel (the numbers sometimes shows right values, other times not)

2.  when you rename a note it keeps its tags..  and even if you rename the folder the note is contained into tags are kept (that's perfect) - BUT ('cause there's a BUT.. sadly) if this folder you rename has a subfolder inside, all notes that are in this subfolder lose their tags.

Ok.. I'll close this issue now .. Later I'll open the two new issues, now after all this testing I have an headache xD

Thanks for actively solving issues, it's unbelievable how fast you work and solve issues, this is surely the most active development of an application, listening and helping users,  I've ever seen!!!

**Comment by pbek** [comment]
Thank you for testing, it seems not many people are using (internal) tagging AND sub-folders as persistently as you. :grin:

> 1) some "inconsistencies" in the number of notes shown in the tag panel (the numbers sometimes shows right values, other times not)

It's hard to determine what exactly to show when multiple tags and multiple sub-folders can be selected, with all the extra settings and special cases that are possible and things are changing left and right. :) We can talk about that in another issue.

> 2) when you rename a note it keeps its tags.. and even if you rename the folder the note is contained into tags are kept (that's perfect) - BUT ('cause there's a BUT.. sadly) if this folder you rename has a subfolder inside, all notes that are in this subfolder lose their tags. 

Yes, that mechanism simply isn't implemented yet and it is complex to implement. But you may open a feature requests if you want.

>  this is surely the most active development of an application, listening and helping users, I've ever seen!!!

thank you very much! :grin: 

there are even people complaining that development is too active (too many releases) :laughing:
