### ISSUE TITLE
[I] "Remove notes" in context menu doesn't do anything

### ISSUE THREAD

**Issue by Omrigan** [pbek/QOwnNotes#1697]
#### Expected behaviour

It removes notes

#### Actual behaviour

Doesn't do anything

#### Steps to reproduce

Always reproduces on QOwnNotes installed from AUR.

Wayland compositor: sway 1.4

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[15:55:53] [debug] Reply from "/ocs/v1.php/cloud/capabilities"
[15:55:53] [debug] Reply from capabilities page
[15:55:59] [debug] getDiskDatabasePath - 'databaseFileName': "/home/omrigan/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite"
[15:56:05] [debug] Set proxy configuration to use NO proxy
[15:56:05] [warning] Wayland does not support QWindow::requestActivate()
[15:56:05] [debug] initShortcuts - 'menuBarIsVisible': true
[15:56:06] [debug] cloudConnection: CloudConnection: 

[15:56:06] [debug] buildNotesIndex - 'noteSubFolderId': 0
[15:56:06] [debug] buildNotesIndex - 'noteSubFolderId': 7
[15:56:06] [debug] buildNotesIndex - 'noteSubFolderId': 8
[15:56:06] [debug] buildNotesIndex - 'noteSubFolderId': 9
[15:56:06] [debug] buildNotesIndex - 'noteSubFolderId': 5
[15:56:06] [debug] buildNotesIndex - 'noteSubFolderId': 6
[15:56:06] [debug] buildNotesIndex - 'noteSubFolderId': 10
[15:56:06] [debug] buildNotesIndex - 'noteSubFolderId': 1
[15:56:06] [debug] buildNotesIndex - 'noteSubFolderId': 2
[15:56:06] [debug] buildNotesIndex - 'noteSubFolderId': 3
[15:56:06] [debug] buildNotesIndex - 'noteSubFolderId': 4
[15:56:06] [debug] buildNotesIndex - 'noteSubFolderId': 11
[15:56:06] [debug] buildNotesIndex - 'noteSubFolderId': 12
[15:56:06] [debug] buildNotesIndex - 'noteSubFolderId': 13
[15:56:06] [debug] buildNotesIndex - 'noteSubFolderId': 14
[15:56:06] [debug] buildNotesIndex - 'noteSubFolderId': 15
[15:56:06] [debug] buildNotesIndex - 'noteSubFolderId': 16
[15:56:06] [debug] setupNoteFolderTables - 'database version': 14

[15:56:06] [debug] loadNoteDirectoryList
[15:56:06] [debug] reloadTagTree
[15:56:06] [debug] reloadTagTree - 'noteSubFolderIds': QVector()

[15:56:06] [debug] reloadNoteSubFolderTree
[15:56:06] [debug] reloadNoteSubFolderTree
[15:56:06] [debug] reloadTagTree
[15:56:06] [debug] reloadTagTree - 'noteSubFolderIds': QVector(0)
[15:56:06] [debug] loadNoteDirectoryList
[15:56:06] [debug] reloadTagTree
[15:56:06] [debug] reloadTagTree - 'noteSubFolderIds': QVector(0)
[15:56:06] [debug] reloadNoteSubFolderTree

[15:56:06] [debug] reloadTagTree
[15:56:06] [debug] reloadTagTree - 'noteSubFolderIds': QVector()
[15:56:06] [debug] Reply from "/ocs/v2.php/apps/files_sharing/api/v1/shares"
[15:56:06] [debug] Reply from share api
[15:56:06] [debug] updateNoteShareStatusFromShare - 'status': "ok\n"
[15:56:22] [debug] openLinkAtCursorPosition - 'emit urlClicked( urlString )': ""
[15:56:38] [warning] Wayland does not support QWindow::requestActivate()
[15:57:20] [debug] openLinkAtCursorPosition - 'emit urlClicked( urlString )': ""
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sat Apr 18 15:59:19 2020`
**Version**: `20.4.1`
**Build date**: `Apr  2 2020`
**Build number**: `690`
**Platform**: `linux`
**Operating System**: `Arch Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.14.1`
**Qt Version (runtime)**: `5.14.2`
**Portable mode**: `no`
**Settings path / key**: `/home/omrigan/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/omrigan/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_GB`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `hicolor`
**Notes in current note folder**: `119`
**Calendar items**: `15`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: ``
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `18.0.1.3`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/home/omrigan/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/omrigan/box2/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/omrigan/box2/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: ``
**username**: `omrigan`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**FileDialog/LastPath** (QString): `/home/omrigan/main/notes-export/!actual`
**FileDialog/LastPath-ImportTextFiles** (QString): `/home/omrigan/main/notes-export/!actual`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-04-18T15:13:55.958`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `notes, !actual`
**MainWindow/noteTextEdit.code.font** (QString): `JetBrains Mono,9,-1,5,75,1,0,0,0,0,Bold Italic`
**MainWindow/noteTextEdit.font** (QString): `Sans Serif,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `JetBrains Mono,14,-1,5,75,1,0,0,0,0,Bold Italic`
**MainWindow/noteTextView.font** (QString): `Sans Serif,14,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `false`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**MessageBoxOverride/copy-notes** (QString): `16384`
**MessageBoxOverride/local-trash-notes-restored** (QString): `1024`
**MessageBoxOverride/local-trash-restore-notes** (QString): `16384`
**MessageBoxOverride/move-notes** (QString): `16384`
**MessageBoxOverride/readonly-mode-allow** (QString): `16384`
**MessageBoxOverride/remove-folders** (QString): `16384`
**MessageBoxOverride/remove-note** (QString): `16384`
**MessageBoxOverride/remove-notes** (QString): `65536`
**MessageBoxOverride/remove-workspace** (QString): `16384`
**MessageBoxOverride/restore-note** (QString): `65536`
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 138 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `137`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-action_Remove_note** (QKeySequence): `Del`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Task`
**VersionDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `fc9ab6d1-2b5f-4af8-8c81-eaeb611ff9da`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `true`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**interfaceStyle** (QString): `Fusion`
**internalIconTheme** (bool): `false`
**itemHeight** (int): `15`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `false`
**localTrash/supportEnabled** (bool): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/omrigan/box2/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Task`
**ownCloud/todoCalendarEnabledList** (QStringList): `Task`

**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `18.0.1.3`
**previousWorkspace** (QString): `vvTaqTgT4WHZ`
**recentNoteFolders** (QStringList): `/home/omrigan/main/box2/Notes, /home/omrigan/box/notes2`
**restoreCursorPosition** (bool): `true`
**restoreLastNoteAtStartup** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): ``
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useUNIXNewline** (bool): `false`
**versionSplitterSizes** (QByteArray): `<binary data>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**webSocketServerService/token** (QString): `TxrgYsub`
**workspace-fc9ab6d1-2b5f-4af8-8c81-eaeb611ff9da/name** (QString): `main`
**workspace-fc9ab6d1-2b5f-4af8-8c81-eaeb611ff9da/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-fc9ab6d1-2b5f-4af8-8c81-eaeb611ff9da/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspace-vvTaqTgT4WHZ/name** (QString): `Full`
**workspace-vvTaqTgT4WHZ/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-vvTaqTgT4WHZ/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, vvTaqTgT4WHZ, fc9ab6d1-2b5f-4af8-8c81-eaeb611ff9da`

## System environment

**ARCHFLAGS**: `-arch x86_64`
**AUTOJUMP_ERROR_PATH**: `/home/omrigan/.local/share/autojump/errors.log`
**AUTOJUMP_SOURCED**: `1`
**COLORFGBG**: `15;0`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**DISPLAY**: `:0`
**ECORE_EVAS_ENGINE**: `wayland_egl`
**EDITOR**: `nvim`
**ELM_ENGINE**: `wayland_egl`
**GOPATH**: `/home/omrigan/go`
**HOME**: `/home/omrigan`
**I3SOCK**: `/run/user/1000/sway-ipc.1000.1056.sock`
**INVOCATION_ID**: `b9ae532a02b84b59a55a3a11f8b5d7d7`
**JOURNAL_STREAM**: `9:21400`
**LANG**: `en_US.UTF-8`
**LANGUAGE**: *empty*
**LC_ALL**: `en_GB.utf-8`
**LESS**: `-R`
**LOGNAME**: `omrigan`
**LSCOLORS**: `Gxfxcxdxbxegedabagacad`
**LS_COLORS**: `rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:`
**MAIL**: `/var/spool/mail/omrigan`
**MANPATH**: `/usr/local/man:/usr/local/man:`
**MOZ_PLUGIN_PATH**: `/usr/lib/mozilla/plugins`
**NIX_PATH**: `nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixpkgs:/nix/var/nix/profiles/per-user/root/channels`
**NIX_PROFILES**: `/nix/var/nix/profiles/default /home/omrigan/.nix-profile`
**NIX_REMOTE**: `daemon`
**NIX_SSL_CERT_FILE**: `/etc/ssl/certs/ca-certificates.crt`
**NIX_USER_PROFILE_DIR**: `/nix/var/nix/profiles/per-user/omrigan`
**OLDPWD**: `/home/omrigan`
**PAGER**: `less`
**PASSWORD_STORE_DIR**: `/home/omrigan/box2/passwords/pass`
**PATH**: `/home/omrigan/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/omrigan/go/bin:/home/omrigan/scripts:/home/omrigan/.cargo/bin:/home/omrigan/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
**PWD**: `/home/omrigan`
**SDL_VIDEODRIVER**: `wayland`
**SHELL**: `/bin/zsh`
**SHLVL**: `3`
**SSH_AGENT_PID**: `911`
**SSH_AUTH_SOCK**: `/tmp/ssh-OUlmCEfYa5YI/agent.910`
**SWAYSOCK**: `/run/user/1000/sway-ipc.1000.1056.sock`
**TERM**: `xterm-256color`
**USER**: `omrigan`
**WAYLAND_DISPLAY**: `wayland-0`
**WINDOWID**: `0`
**XCURSOR_SIZE**: `24`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_SEAT**: `seat0`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_ID**: `1`
**XDG_SESSION_TYPE**: `wayland`
**XDG_VTNR**: `1`
**ZSH**: `/home/omrigan/.oh-my-zsh`
**_**: `/usr/bin/QOwnNotes`
**_JAVA_AWT_WM_NONREPARENTING**: `1`
**QT_QPA_PLATFORM**: `wayland-egl`
</details>

**Comment by pbek** [comment]
Do you also also get this issue on the latest release?

**Comment by pbek** [comment]
I can't reproduce your issue, but I see you have a few `MessageBoxOverride` settings. Maybe you told the delete message box to always say "no"? You can reset that in the settings.

**Comment by Omrigan** [comment]
Right, thanks, this helped.

Perhaps the option to make delete message always say "no" is a bit weird and should be explicitly forbidden :)

**Comment by pbek** [comment]
Took a while to hopefully not cause any regressions...

## 20.4.10
- for all question dialogs where you clicked the checkbox `Don't ask again!` you
  will be now asked again next time if you answer the dialog question with `No`
  and remembering that decisions makes no sense
    - this will help you in case when you accidentally clicked the checkbox and
      then pressed `No`, for example with shortcut-triggered dialogs like
      `Remove current note`
    - for all dialogs where remembering your `No` makes sense all of your
      decisions will be still remembered, for example with the dialog
      `Note editing is currently disabled, do you want to allow it again?`
      when you try to edit a note in read-only mode

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Omrigan** [comment]
> There now is a new release, could you please test it and report if it works for you?

Yes, it works. Thanks so much for such a rapid change!
It is a pleasure to use QOwnNotes with such high-quality support :+1:

**Comment by pbek** [comment]
Great, thank you :grin:  and thank you for testing!
