### ISSUE TITLE
Allow creation of note by clicking on non-legacy note-link if link is broken

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1698]
It would be nice if there was a way to allow the creation of the note if a non-legacy note link is broken (like it works with `note://note-name` links in #736).

Of course this is a lot more complex.

Links like `[Deep-Note](a%20sub%20folder%202%2Fdfolder%202%2FDeep-Note2.md)` are currently (rightfully) detected as external files if the linked note doesn't exist in the current note folder (detected in `Note::fileUrlIsNoteInCurrentNoteFolder`).

And beside the note name of course the correct sub-folder also needs to be detected (maybe even optionally created?). Extra warnings are needed if sub-folders are disabled for the current note-folder.

**Comment by Waqar144** [comment]
Where will be the note created? you mean new note?

**Comment by pbek** [comment]
Yes, the new note would (should) be created in the sub-folder the link points to.

**Comment by pbek** [comment]
@fnkabit, that would also be a nice feature in case you are looking for more. 😁

**Comment by fnkabit** [comment]
@pbek Thanks! Will look into this one next.

**Comment by pbek** [comment]
Hehe, awesome! 🎉  I hoped you would "bite". 😀

**Comment by pbek** [comment]
## 20.10.8
- you can now choose to create the note of broken note links when you <kbd>Ctrl</kbd> + Click
  on the note in the note text edit (for [#1698](https://github.com/pbek/QOwnNotes/issues/1698), thank you @fnkabit)

**Comment by pbek** [comment]
## 20.10.9
- you can now also choose to create the note of broken note links when clicking
  on the note in the note preview (for [#1698](https://github.com/pbek/QOwnNotes/issues/1698), thank you @fnkabit)
    - if note subfolders are disabled for your note folder you will now also get
      a proper error message when trying to create notes in subfolders
