### ISSUE TITLE
[I] Can't update Qownnotes

### ISSUE THREAD

**Issue by wtrmrk** [pbek/QOwnNotes#1699]
Please paste the text from the issue assistant here. It should be already in your clipboard.

#### Expected behaviour

I should just click on update. It'll download the update, exits, and I turn it on and it should be running on the new version.

#### Actual behaviour

What happens is that I am still stuck to the old version and a pop up for a new update shows up again.

#### Steps to reproduce

I just click on update.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Apr 21 14:40:16 2020`
**Version**: `20.4.3`
**Build date**: `Apr  9 2020`
**Build number**: `5512`
**Platform**: `windows`
**Operating System**: `Windows 7 SP 1 (6.1)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\MARK ISIDRO\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Users\MARK ISIDRO\Documents\_incoming\Misc\Ins\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1366x768`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `48`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\MARK ISIDRO\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `C:\Users\MARK ISIDRO\OneDrive\Documents\notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\MARK ISIDRO\OneDrive\Documents\notes\notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**AttachmentDialog/geometry** (QByteArray): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `true`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/editorWidthMode** (int): `1`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (int): `20`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-3bdec0ed-eb9c-424c-9c9b-b6a76e087531`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `false`
**Editor/indentSize** (int): `4`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-04-21T14:26:35.936`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `daily notes, qown, qown/Blog Post`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `true`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/allowDifferentNoteFileName** (QString): `true`
**NoteHistory-1** (QVariantList): `<variant list with 77 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `76`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `277bf3fc-4a8f-48e5-bd82-6bd5adf5c102`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `false`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**interfaceStyle** (QString): `Fusion`
**internalIconTheme** (QString): `false`
**itemHeight** (int): `13`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `C:/Users/MARK ISIDRO/OneDrive/Documents/notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/ignoreNonTodoCalendars** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `2`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `4b59f713-70be-4d11-92ea-c9aaea61f390`
**recentNoteFolders** (QStringList): `C:/Users/MARK ISIDRO/OneDrive/Documents/notes/daily notes`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `041920, How to Work from Home, 041820, Note 2020-04-17T18.59.47, 041720, Note 2020-04-16T08.24.56, 041620, Note 2020-04-15T04.34.58, Lessons in Constr, 041420, 041, Daily schedule, Note 2020-04-12T14.41.13, to, 041220, #041120 2020-04-11T10.33.28, Note 2020-04-11T04.52.23, Note 2020-04-10T17.47.21`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `false`
**skipVersion** (QString): `20.4.9`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (QString): `false`
**useSoftWrapInNoteEditor** (QString): `true`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-277bf3fc-4a8f-48e5-bd82-6bd5adf5c102/name** (QString): `Simple`
**workspace-277bf3fc-4a8f-48e5-bd82-6bd5adf5c102/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-277bf3fc-4a8f-48e5-bd82-6bd5adf5c102/windowState** (QByteArray): `<binary data>`
**workspace-4b59f713-70be-4d11-92ea-c9aaea61f390/name** (QString): `Editing`
**workspace-4b59f713-70be-4d11-92ea-c9aaea61f390/noteSubFolderDockWidgetVisible** (QString): `false`
**workspace-4b59f713-70be-4d11-92ea-c9aaea61f390/windowState** (QByteArray): `<binary data>`
**workspace-59d9yALsYar6/name** (QString): `Minimal`
**workspace-59d9yALsYar6/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-59d9yALsYar6/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 277bf3fc-4a8f-48e5-bd82-6bd5adf5c102, 59d9yALsYar6, 4b59f713-70be-4d11-92ea-c9aaea61f390`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\MARK ISIDRO\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `DATAGATEWAY-PC`
**ComSpec**: `C:\Windows\system32\cmd.exe`
**FP_NO_HOST_CHECK**: `NO`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\MARK ISIDRO`
**LOCALAPPDATA**: `C:\Users\MARK ISIDRO\AppData\Local`
**LOGONSERVER**: `\\DATAGATEWAY-PC`
**NUMBER_OF_PROCESSORS**: `4`
**OneDrive**: `C:\Users\MARK ISIDRO\OneDrive`
**OneDriveConsumer**: `C:\Users\MARK ISIDRO\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 60 Stepping 3, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `3c03`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Windows\system32\WindowsPowerShell\v1.0\Modules\`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\Windows`
**TEMP**: `C:\Users\MARKIS~1\AppData\Local\Temp`
**TMP**: `C:\Users\MARKIS~1\AppData\Local\Temp`
**USERDOMAIN**: `DATAGATEWAY-PC`
**USERNAME**: `MARK ISIDRO`
**USERPROFILE**: `C:\Users\MARK ISIDRO`
**windir**: `C:\Windows`
**windows_tracing_flags**: `3`
**windows_tracing_logfile**: `C:\BVTBin\Tests\installpackage\csilogfile.log`
</details>

**Comment by pbek** [comment]
1) Do you have write permissions to `C:\Users\MARK ISIDRO\Documents\_incoming\Misc\Ins\QOwnNotes`?
2) Is the Update-Scripted executed (it should show up as windows)? If yes, are there any errors reported in it?

**Comment by pbek** [comment]
3) Do you have the `Debug/fakeOldVersionNumber` setting enabled on purpose? But that shouldn't be an issue since you didn't seem to get the latest version. What version is reported to you as latest version?

**Comment by wtrmrk** [comment]
1. Yes.
2. Yes. There are no errors.
3. It says there on the post about updating qownnotes.

> Please use the checkbox Fake old version number in the Debug options to trigger an update and click Check for updates in the Help main menu to test the update process and provide feedback.

It shows version 20.4.3

**Comment by pbek** [comment]
> It says there on the post about updating qownnotes.

This settings only sense when you are at the latest version and still want to trigger the update-dialog. :grin: 

> It shows version 20.4.3

The update dialog shows that your latest version is 20.4.3?
We currently are at 20.4.11 (and I successfully updated to it yesterday on a Windows box).

![image](https://user-images.githubusercontent.com/1798101/79835013-48f84600-83ae-11ea-857d-54b45357a802.png)

**Comment by pbek** [comment]
What happens when you click `Check for updates` in the `Help` menu?

**Comment by wtrmrk** [comment]
I am sorry I misunderstood your question. 

Yes it shows 20.4.11 for the latest version available but my qownnotes version is at version 20.4.3

**Comment by wtrmrk** [comment]
A window shows up saying a new update is available

**Comment by pbek** [comment]
Something seems to be blocking that the new files are written to `C:\Users\MARK ISIDRO\Documents\_incoming\Misc\Ins\QOwnNotes`. I guess the easiest would be to just download (https://www.qownnotes.org/installation) and un-zip the application's zip to that directory again.

Make sure QOwnNotes is not running when you do that. (And maybe double check file permissions.) :grin:

**Comment by pbek** [comment]
You can re-test the update process with the next release (most likely later today) again.

**Comment by wtrmrk** [comment]
Ok thank you. I will try that. I appreciate your prompt response. Keep it up. I am enjoying this note app you created.

**Comment by pbek** [comment]
Thank you for your kind words. :grinning:

**Comment by pbek** [comment]
Are you able to update now?

**Comment by pbek** [comment]
I will close this until there is more information.
