### ISSUE TITLE
Notizen Ordner unabhängig vom Synchronisieren der gesamten Owncloud mit dem PC

### ISSUE THREAD

**Issue by alex1702** [pbek/QOwnNotes#17]
Für die Funktionen Versionen und gelöschte Notizen, muss der Notizen Ordner im Owncloud Ordner lokal liegen, der komplett mit Owncloud synchronisiert wird. Da aber für die API nur der Ordnername + Pfad der in Owncloud für die Notizen verwendet wird benötigt wird, reicht es doch ein Eingabefeld in den Einstellungen zu implementieren.

**Comment by pbek** [comment]
But what will happen if the user switches to an other notes folder, let us say an archive folder?

**Comment by alex1702** [comment]
Also auf einen Notizenordner, der dann nicht synchronisiert wird per Owncloud Client? Hmm vllt dann eine Sicherheitsabfrage mit dem hinweis, dass es zu konflikten kommen kann, wenn man den Ordner ändert und dieser nicht synchronisiert wird. Aber vllt sollte man dann das gesamte Konzept der Accounts nochmal neu aufbauen. Im Sinne von dass man Offline/Online Notizenquellen hinzufügen kann, bei offline werden die Owncloud daten erst garnicht abgefragt und bei online kann man ja noch prüfen ob der notizenordner mit dem in der owncloud übereinstimmt und gegebenfalls eine warnung ausgeben.

**Comment by pbek** [comment]
Wenn man ownCloud nicht nutzt, dann braucht man den ganzen Tab in den Settings gar nicht ausfüllen. Wenn man nur offline oder mit einem anderen Sync-Dienst arbeitet muss QOwnNotes nur wissen wo man seinen Notizen speichern will. ;) Die Einstellungen sind nur dafür da um das Versioning und Trash Feature vom ownCloud Server zu benutzen. Der Sync passiert über den ownCloud Sync Client, nicht QOwnNotes.
Mehrere voll konfigurierbare Quellen zu haben (wie das multi-account-feature beim ownCloud client) wäre möglich, dafür müsste man aber recht viel umschreiben.

**Comment by pbek** [comment]
I will close this issue until there is more information.
