### ISSUE TITLE
Question : how to decrypt AES files without QOwnNotes ?

### ISSUE THREAD

**Issue by bflorat** [pbek/QOwnNotes#1707]
I would like to be able to decrypt my wallet file encrypted by QOwnNotes from my android device.

I see in your code that you use a AES256/CBC/PKCS#7 scheme but I didn't find a simple way to decrypt it from the data (fetched from my nextcloud android app).

Any idea ? Thanks.

**Comment by pbek** [comment]
I don't know what counts as "easy way" for you is. :grin:
You would need something that base64-decodes and AES-decrypts the text, like it is done in `BotanWrapper::Decrypt`.

You can also script encryption in QOwnNotes, if you prefer another way of encryption.
See: https://docs.qownnotes.org/en/latest/scripting/hooks/#encryptionhook

**Comment by bflorat** [comment]
Thanks. I spent a whole day searching but I didn't find a suitable solution for decrypt easily from a browser or a android device.

I wrote  openssl and pgp-with password scripts but I had to give up. 
Moreover, it's not clear how to call a bash script from a QOwnotes script  and escape the input text (I used 
```
 script.writeToFile(text,'/tmp/file');
var command = "gpg  --pinentry-mode loopback -a -r "+publicKey+" --passphrase="+password +(decrypt === true ?" --decrypt ":" --encrypt") 
             +" < /tmp/file" ;
return script.startSynchronousProcess("/bin/bash",["-c",command]);  
```

but I had different issues

I guess I'll stay with the default Botan encryption scheme  on PC.

**Comment by bflorat** [comment]
BTW, I figured out something strange during my investigations :  given the same clear text and same password, I always get the same encrypted string. AFAIK, it shouldn't be the case because of the salt added during the encryption and added into the encrypted text...

**Comment by pbek** [comment]
> Moreover, it's not clear how to call a bash script from a QOwnotes script and escape the input text (I used

On which operating system are working? Linux or macOS. You don't need bash for Linux, for macOS it's something like: https://github.com/pbek/QOwnNotes/blob/29311c01870738487d054f2b34906ff6cc327850/src/utils/misc.cpp#L414-L415

**Comment by bflorat** [comment]
I'm under Linux.

**Comment by pbek** [comment]
> escape the input text

why did you need to escape it, doesn't gpg do the base64 encoding for you like in https://github.com/pbek/QOwnNotes/blob/develop/docs/content/scripting/examples/encryption-pgp.qml?

> script.writeToFile(text,'/tmp/file');

You don't need a temp file, you can write `text` directly to stdin of gpg (see https://docs.qownnotes.org/en/latest/scripting/methods-and-objects/#starting-an-external-program-and-wait-for-the-output)

**Comment by pbek** [comment]
You could also use https://keybase.io/ to encrypt your notes on your desktop with QOwnNotes (via gpg) and decypt the text of your note with their Android app.

script see: https://github.com/pbek/QOwnNotes/blob/develop/docs/content/scripting/examples/encryption-keybase.qml

**Comment by pbek** [comment]
> I'm under Linux.

you can run the command directly with `startSynchronousProcess` and pass all parameters as one array

**Comment by bflorat** [comment]
> You could also use https://keybase.io/ to encrypt your notes on your desktop with QOwnNotes (via gpg) and decypt the text of your note with their Android app.
> 
> script see: https://github.com/pbek/QOwnNotes/blob/develop/docs/content/scripting/examples/encryption-keybase.qml

Thanks, I tried and installed it but :
- I didn't manage to make it work with so few documentation. 
- Keybase requires to send GPG private keys to each device
- I want a interactive password (like your default AES implementation) and don't rely on a local PGP key. I want to be forced to type a password  for each access.

**Comment by pbek** [comment]
Ok, then keybase.io can't help you...

**Comment by bflorat** [comment]
FYI, I finally switched to a specialized wallet solution that works for me but I still use your default AES 256 for less sensible text.

BTW, did you see my remark about salting ? It's a bit frightening. I tried to create new notes with same content / password and still get the same encrypted value...  If the encrypted text is not salted, it is very vulnerable to brute force attacks using rainbow tables...

**Comment by pbek** [comment]
> FYI, I finally switched to a specialized wallet solution that works for me but I still use your default AES 256 for less sensible text.

what solution is that, if I may ask?
so did you write your own QON encryption script?
can you now access your encrypted notes on your mobile device?

sorry, forgot to answer about this:

> AFAIK, it shouldn't be the case because of the salt added during the encryption and added into the encrypted text...

yes, but the salt is always the same, otherwise you wouldn't be able to decrypt your note on an other installation of QOwnNotes or share your note

>  If the encrypted text is not salted, it is very vulnerable to brute force attacks using rainbow tables...

Of course could it be brute forced, it's only as safe as your password. how should it be salted and stay portable (for example shareable with other people)? If I send you my keepassx file and it hasn't a 2nd factor for auth and you brute-force the password (or I tell it to you), you can also access the data, can't you?

**Comment by bflorat** [comment]
Sorry, I prefer not to detail for security reasons. Yes, it is available on mobile and uses 2FA with a token.

It is good to use a pepper but even better to use a salt (the salt is stored in clear in the encrypted text itself and changes at each encryption). So it is possible to decrypt the text on any device with the encrypted text (including the salt) + the key.

If you want to make sure only a given installation of QOwnNotes can decrypt the text, you can use both salt and pepper, the pepper being only available on our device. But it means that  only QOwnNotes can decrypt the text. It's a business choice.

**Comment by pbek** [comment]
> It is good to use a pepper but even better to use a salt (the salt is stored in clear in the encrypted text itself and changes at each encryption). So it is possible to decrypt the text on any device with the encrypted text (including the salt) + the key.

There should be a salt:

https://github.com/pbek/QOwnNotes/blob/ea726a9185fbf61818788880dcae7f059acf22ef/src/libraries/botan/botanwrapper.cpp#L62-L89

> But it means that only QOwnNotes can decrypt the text. It's a business choice.

I like QOwnNotes to be "replaceable".

**Comment by pbek** [comment]
I will close this until there is more information.
