### ISSUE TITLE
Tag tree counter

### ISSUE THREAD

**Issue by r00tr4v3n** [pbek/QOwnNotes#1709]
There are the note list panel options "Show all notes in a folder including their subfolders" and "Show all notes of a tag including the notes of their children-tags".
It would be great if the tag counter would work accordingly.

#### Expected behaviour
Root tag counts all notes associated with itself or its children.
/animals/birds/ducks
1 tag in animal, 1 tag in birds and 1 tag in ducks should yield 3 notes for animals, 2 for birds and 1 for ducks

#### Actual behaviour
Tags only count notes associated with themselves: 1 note in animals, 1 note in birds, 1 note in ducks

#### Suggestions
- make the tag counter include all its childrens' notes
- turn on the list panel options per default

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
> turn on the list panel options per default

Is there any other application that does that by default? Or are there other examples that suggest that's a good decision?

**Comment by pbek** [comment]
## 20.4.15
- when the setting to show all notes of a tag including the notes of their
  children-tags is turned on now the note-count in the tag tree is adapted to
  also count the notes of the children-tags

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by r00tr4v3n** [comment]
Awesome, works as described! Thank you very much!
>      Is there any other application that does that by default? Or are there other examples that suggest that's a good decision?

I checkd with [Digikam](https://github.com/KDE/digikam), it sums up the image count if collapsed and reduces the parent's count to its own tagged images when expended:
- places (10)
expands to
- places (2)
-- cities (4)
-- mountains (4)

This might even be better since it provides both information?

**Comment by pbek** [comment]
> This might even be better since it provides both information?

I don't know. Isn't the information only correct if the "recursive tag list" setting is on.

**Comment by pbek** [comment]
QON has too many settings and too many features. You have no idea how many cases there need to be thought of for even doing something simple as note counting... :grimacing: I think tag counting needs to work with 4 different settings and all permutations of them (that 16 different cases). :grimacing:

**Comment by r00tr4v3n** [comment]
> Isn't the information only correct if the "recursive tag list" setting is on.

That might depend on your preference. I'd say it rather depends on nested tags altogether. If you nest and don't count and filter accordingly, what's the point of them? (apart from a more organized tag overview but then you could just use `add tag` with the auto completion)

> QON has too many settings and too many features.

That's one of many reasons why people love it :smiley:

**Comment by Waqar144** [comment]
while we are at it, it would be best to add an option to disallowing showing tag count and there by increasing performance for people who have lots of tags.

**Comment by pbek** [comment]
> what's the point of the hierarchy

the same structure like with folders, I say I just let it they way it is. I'm not convinced of the "expanse/collapse switching" plus everything will need to be rewritten to be redrawn with expanse/collapse. and even if I do that then it should need to be done in all tree views...

**Comment by pbek** [comment]
> while we are at it, it would be best to add an option to disallow showing tag count, hence increasing performance for people who have lots of tags.

yes, it slows down the app. do you care for a pull request? 😁

**Comment by r00tr4v3n** [comment]
> the same structure like with folders, I say I just let it they way it is. I'm not convinced of the "expanse/collapse switching" plus everything will need to be rewritten to be redrawn with expanse/collapse. and even if I do that then it should need to be done in all tree views...

Fair enough. The new counter is great and enough for now, I can see if a root tree is empty without the need of completely expanding the tree.

**Comment by r00tr4v3n** [comment]
Memo: the tag counter counts the tags, not the notes (sounds correctly)
So a note with animal/dogs and animals/cats would be counted as 2 for animals. 
This might be counter-intuitive with the "All notes" heading/tag having less than the sum of all root tags.

**Comment by pbek** [comment]
> Memo: the tag counter counts the tags, not the notes (sounds correctly)

These numbers in the tag trees are counted notes, not tags:

![image](https://user-images.githubusercontent.com/1798101/80302826-ba6c3600-87ac-11ea-95f1-885ac302219a.png)

**Comment by r00tr4v3n** [comment]
I have a single file in this note folder:
![image](https://user-images.githubusercontent.com/6073574/80491538-242e4080-8963-11ea-8669-b64cdb41e6ca.png)

**Comment by pbek** [comment]
You are right, currently there the amount of note-tag-links is counted.

**Comment by pbek** [comment]
And getting those counts again got much more complex and error prone to work in all combinations of settings... :laughing: 

## 20.4.18
- the counts in the tag tree are now showing the amount of linked notes and not
  the amount of note-links of a tag

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
@r00tr4v3n, any news on that?

**Comment by r00tr4v3n** [comment]
Works as expected, thank you!

**Comment by pbek** [comment]
Great, thank you for testing!
