### ISSUE TITLE
[Windows] Repeating error "note changed by external application" when using Dropbox folder

### ISSUE THREAD

**Issue by minthemiddle** [pbek/QOwnNotes#171]
I keep getting an error message saying that the message I'm working on was changed by an external application. I am on Windows 10 on 16.05.13. The notes are saved in a Dropbox folder. I do not get this bugging window when I use a standard folder.

Probably Dropbox does some non-standard saving, but still it is very annoying as the note itself is definitely not changed externally.

**Comment by pbek** [comment]
QOwnNotes shows this message if the current note was modified by an external process while you are editing the note and the new content of the note file differs from you have in your note in QOwnNotes...

This notification is vital if for example ownCloud or Dropbox syncs to your note from an other device / the cloud. How would you handle this?

**Comment by minthemiddle** [comment]
Yes, I would agree if only the content of the current note changed and there would be any chance of anyone editing the note outside fo QON. But this is not happening here: I am working solely within QON and noone is editing it externally. Most probably Dropbox is saving some metadata, but the content cannot possibly change. I get this error message for every new line that I insert in QON. As I only change the files in QON, I would be happy to just disable all warnings.

**Comment by pbek** [comment]
Is there a option in your Dropbox client that allows it to modify the content of text files, for example line endings?

**Comment by minthemiddle** [comment]
I'm using the official client. I could not find any settings related to text files or editing files in general. Some even report that Dropbox is [file agnostic](http://superuser.com/questions/323843/does-dropbox-change-linebreaks-in-files).

**Comment by pbek** [comment]
Maybe I should include a setting in QOwnNotes to ignore external changes while editing a note. I will see what I can do...

**Comment by minthemiddle** [comment]
Cool.

**Comment by pbek** [comment]
From the just released v16.05.14:
- you are now able to ignore all external modifications of your note file 
  while you are editing your note in the note diff dialog
  (for [Issue #171](https://github.com/pbek/QOwnNotes/issues/171))
    - you can turn the ignore off in the settings 

Can you please test if that solves your problem?

**Comment by minthemiddle** [comment]
Yes, it works really well. Thanks.

**Comment by pbek** [comment]
Great!

**Comment by pbek** [comment]
@minthemiddle, maybe #1041 will also help you!
