### ISSUE TITLE
UpdateService exposes tracking/telemetry-like user system information

### ISSUE THREAD

**Issue by simeonmiteff** [pbek/QOwnNotes#1711]
#### Expected behaviour

When Tracking and AppHeartBeat are disabled in settings, QOwnNotes should not expose user system information.

Ideally, the user should be able to configure QOwnNotes not to make network connections (1st prize this is either the default, or UpdateService is opt-in).

#### Actual behaviour

UpdateService exposes tracking/telemetry-like user system information: client OS, OS version, architecture is sent to the server.

#### Steps to reproduce

- Configure proxy in the settings to localhost
- Install `mitmproxy`, and configure the self-signed CA certificate to be trusted in the OS
- Run QOwnNotes, observe UpdateService request to www.qownnotes.org

#### Additional notes

For now I have added www.qownnotes.org to by hosts file to disable this behaviour

**Comment by pbek** [comment]
Thank you for your concern. So you are suggesting that if metrics are turned off then there should be no update-mechanism (because without information about the current version and operating system no download-link and change-log diff can be generated).

I don't think all users would expect that and I guess it would increase the amount of support tickets with not-up-to-date versions of QOwnNotes.

**Comment by simeonmiteff** [comment]
@pbek 

Thanks for your response. I don't disagree that most users might want the update mechanism. Personally, I'm happy to upgrade to new releases when they're available via the PPA (like other software on my system). Would you consider adding an option to disable update checks?

**Comment by pbek** [comment]
> Would you consider adding an option to disable update checks?

Yes, I considered multiple times. But I always decided against it because I want the user to at least be reminded in the status bar about new versions. I still see too many ancient versions on various download webpages and in action. I don't want to support those on a daily basis. :grimacing:

**Comment by pbek** [comment]
I will close this until there is more information.
