### ISSUE TITLE
Doubleclicking tags QoL suggestion

### ISSUE THREAD

**Issue by r00tr4v3n** [pbek/QOwnNotes#1712]
In correlation to [scripts #84](https://github.com/qownnotes/scripts/issues/84) a QoL suggestion:
Double clicking a tag counts as double click and as normal click since it adds/removes the tag and then jumps to its filter. Especially when removing a tag, jumping to an empty tag list and reselecting the original note is frustrating.
It would be a nice improvement if those two click actions could be separated. (double click prevents normal click)

**Comment by pbek** [comment]
> Double clicking a tag counts as double click and as normal click

This is the way Qt handles it. And a lot of functionality already relies on this behavior.

**Comment by r00tr4v3n** [comment]
Too bad. How about a ctrl-click or checkboxes?

**Comment by pbek** [comment]
> How about a ctrl-click or checkboxes?

To do what?

**Comment by r00tr4v3n** [comment]
To add tags without selecting/jumping to them.

**Comment by pbek** [comment]
The Qt selection mechanism (and all the Qt tooling around it) doesn't work that way :grimacing: This would mean to write our own QTreeWidget and QTreeWidgetItem :laughing:

**Comment by r00tr4v3n** [comment]
In Java/Swing I'd just extend the Widget, custom build the nodes and override the onClick mechanics.. But as I type, I feel like blowing this out of proportions without even knowing how Qt handles stuff.
In retrospect this might not be a good idea after all. Considering the UI of other applications like [Notable](https://github.com/notable/notable) or [Digikam](https://github.com/KDE/digikam) the tag overview is used for navigation only.
I still miss another way to add tags since jumping (and refiltering the note list) to tag is annoying and the `Add tag` textfield does not handle nested tags well (in addition to forcing the user to switch between mouse and keyboard for typing). Digikam uses a 2nd tag panel with checkboxes on the right side and a context menu (with recent tags) to add tags.
QON has an entire menu just for the item `Add tag to note` to jump to the textfield in the bottom. It could be extended with `Add tag ->` (list of tag tree opening) and `Add recent tag ->` (list of recent tags opening). This could also be used in the context menu when clicking on the note text.

![image](https://user-images.githubusercontent.com/6073574/80456741-69844b00-892e-11ea-8d0c-54f0f069a8f5.png)

**Comment by pbek** [comment]
> I still miss another way to add tags since jumping (and refiltering the note list)

There are already many ways to add tags (I guess too many)... And you can add multiple more with the scripting engine, can't you?

> does not handle nested tags well 

If a tag already exists it will take that

> in addition to forcing the user to switch between mouse and keyboard for typing

there is a shortcut for that (see Tag menu)

**Comment by r00tr4v3n** [comment]
>And you can add multiple more with the scripting engine, can't you?

I missed those bool options in the end of `registerCustomAction` but they don't allow sub-menus yet? 
>If a tag already exists it will take the existing tag

It doesn't differentiate between hierarchies to animal/dogs and dogs yields two 'dogs' entries. This might not a concern in real life usage though, just something I noticed in my test folder.

**Comment by pbek** [comment]
> I missed those bool options in the end of registerCustomAction but they don't allow sub-menus yet?

no, but you can give custom actions a shortcut. and you can open dialogs in custom actions.

> It doesn't differentiate between hierarchies to animal/dogs and dogs yields two 'dogs' entries.

yes, that's why you also can tag in the tag tree and via the note list

**Comment by pbek** [comment]
I think you solved that with a script, didn't you?
