### ISSUE TITLE
Disallow All Note Editing indicator is reveresed

### ISSUE THREAD

**Issue by vortsg** [pbek/QOwnNotes#1715]
### Expected behaviour
When the feature "Disallow All Note Editing" is engaged, then Notes should be locked and not allow editing.

### Actual behaviour
QOwnNotes is installed on three computer and they all behave the same way.  The "Disallow All Note Editing" appears to be turned on, but notes are editable. If I turn the feature off, then they appear to be locked. This behaviour is the **reverse** of what I would expect.

When notes are editable, this is what the application shows.
![QOwnNotes Dissallow Note Editing](https://user-images.githubusercontent.com/38059624/80418767-83c21880-889d-11ea-964e-6a500ae4d61d.png)

Is this correct, or am I misinterpreting the use of this feature.

**Comment by r00tr4v3n** [comment]
You click to disallow it.
Might be an ui philosophy issue between "show the current setting" and "show what happens if item is clicked".

**Comment by vortsg** [comment]
Follow the UI philosophy comment.
My interpretation is that as per the screenshot, the feature is "active" and since it is active, then it is **disallowing edits**. But, that is opposite of what is happening as when it is active, edits are allowed. 
Perhaps my brain works backwards :)

**Comment by pbek** [comment]
First I did it the way you think. Then there were complains by users who didn't understand it, so I changed the text for clicked and un-clicked the way it is now. 😅  It's hard to please both parties at the same time.

**Comment by vortsg** [comment]
Thanks for the clarification. I really like QOwnNotes.

**Comment by pbek** [comment]
Thank you. :grin:
