### ISSUE TITLE
Media/Attachment hook suggestion

### ISSUE THREAD

**Issue by r00tr4v3n** [pbek/QOwnNotes#1716]
If I understand correctly, importing files hashes/randomizes their name to avoid conflicts in in the media/attachment folders. I'd like to be able to search for the files from the file manager and in case something happens to the note or QON though.
This hook covers the markdown link in the note. 
#### Suggestion A
Could it (or another hook) also handle to the file name?
`function insertMediaHook(fileName, mediaMarkdownText);`
e.g. `function insertMediaFileHook(fileName);`?
Then I could just use a script and prefix the file names like "realfilename_1234567890.pdf".
`script.insertMediaFile()` is not convenient for this since it does handle drag and drop.
#### Suggestion B
Retrieving multiple files would also be great, for instance via context menu: "Save all (selected) files as *.zip"

**Comment by pbek** [comment]
Can't you already use https://docs.qownnotes.org/en/latest/scripting/hooks/#insertmediahook and rename the file it gets and then output the respective markdown for the link?

**Comment by r00tr4v3n** [comment]
You mean via OS application call? The `fileName` is just the path to the added/dropped file, not the target path within QON isn't it?

**Comment by pbek** [comment]
> You mean via OS application call? 

Yes

> The fileName is just the path to the added/dropped file, not the target path within QON isn't it?

Yes, you are right. But you could get the information out of the `mediaMarkdownText`.

Are you already happy if I include a stripped down version (dangerous characters removed like that https://regex101.com/r/zxi1zg/1/) of the filename (base name of the file) into the name of the media file by default?

**Comment by r00tr4v3n** [comment]
I'd rather avoid an OS call for this for compatibility reasons and since QON handles moving notes already very nicely. Awesome work on the "move note and keep the media links intact"-feature by the way!

> But you could get the information out of the mediaMarkdownText.

Yes, but I can only read the information, not change it without leaving QON (OS call).

> Are you already happy if I include a stripped down version (dangerous characters removed like that https://regex101.com/r/zxi1zg/1/) of the filename (base name of the file) into the name of the media file by default?

Yes, that would cover **A** quiet nicely since that's what I would have done with the hook anyway :)
But you would keep a random number in case of mundane file names like 'file.pdf'?
I can't think of another use case other than changing the default media folders to a decentralized system like mentioned here [1645](https://github.com/pbek/QOwnNotes/issues/1645). But as you explained that would open other issues.

**Comment by pbek** [comment]
> handles moving notes already very nicely.

which was far too much work to make it happen in the scripting engine :sweat_smile: 

>  Awesome work on the "move note and keep the media links intact"-feature by the way!

that was a how different category of "a lot of work" :laughing: 

> But you would keep a random number in case of mundane file names like 'file.pdf'?

Yes, if course it would keep the random numbers. Files with the same name can be thrown in. And they can also come from different computers and be synced at a later time.

**Comment by r00tr4v3n** [comment]
Would you prefer the download zip feature as a script? I could glue something together but it would probably work on Linux only.

**Comment by pbek** [comment]
> Retrieving multiple files would also be great, for instance via context menu: "Download all (selected) files as *.zip"

which files are we talking about here?

**Comment by r00tr4v3n** [comment]
Selected files (attachments and media) in the note.

**Comment by pbek** [comment]
> Selected files (attachments and media) in the note.

Ok, the "Download" irritated me, you mean "Save all selected local images and file-links as ZIP file".
That could already be done in a script.

**Comment by pbek** [comment]
## 20.4.17
- if you insert media files or attachments now a stripped-down version of the
  files's original basename will be included into the filename of resulting file
  in the `media` or `attachments` directory

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by r00tr4v3n** [comment]
> Ok, the "Download" irritated me, you mean "Save all selected local images and file-links as ZIP file"?
> That could already be done in a script.

Yes, sorry for the confusion. I'm working on the script, this just feels like a default feature, not an opt-in one.
File import works as described, thank you!
Two side notes:
- When drag&dropping an entire folder, a link is created but the folder not copied. Is folder import not supported and just not blocked?
- Is there a context menu hook for the preview panel?

**Comment by pbek** [comment]
> When drag&dropping an entire folder, a link is created but the folder not copied. Is folder import not supported and just not blocked?

No, there is no folder import. You can drop multiple files.

> Is there a context menu hook for the preview panel?

No, but for the note edit. Working with selected html in the preview isn't a good way to do things, since the generated html can look pretty different from on other installations of QOwnNotes.

**Comment by r00tr4v3n** [comment]
> No, but for the note edit. Working with selected html in the preview isn't a good way to do things, since the generated html can look pretty different from on other installations of QOwnNotes.

That makes sense. 
There is an `insertMediaHook`. Why isn't there an `insertAttchamentHook`?
For now I just want to add a newline after every insert to make it more readable. Yes, QON is a notes and library manager now :smile:

**Comment by pbek** [comment]
> There is an insertMediaHook. Why isn't there an insertAttchamentHook?

I guess no one needed it yet, those hooks take a lot of time to implement.
And there also is `insertingFromMimeDataHook`.

**Comment by r00tr4v3n** [comment]
OK, I expected the insert hooks to be quite similar. 
`insertingFromMimeDataHook` does not provide the markdown link for adjustment, does it? It's also not called for normal drag&drop attachments. I guess, I'll have to add a 'format attachments' script for the context menu.

**Comment by pbek** [comment]
There is https://www.qownnotes.org/scripting/hooks.html#insertattachmenthook now for attachments.
