### ISSUE TITLE
[I] Can't show sub-folders starting with "."

### ISSUE THREAD

**Issue by tomintaiga** [pbek/QOwnNotes#1718]
#### Expected behaviour

I want to create folder (subfolder) with name ".NET Core" and nothing happen. I've check this with different names, if it starts from "." folder is not created.

#### Actual behaviour

When I write folder name started from "." it creates

#### Steps to reproduce

Right click on any folder, then click on "create subfolder", then type ".NET CORE" and pres "OK"

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[09:09:11] [warning] QTextCursor::setPosition: Position '-2' out of range
[09:09:11] [warning] QTextCursor::setPosition: Position '2' out of range
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `ср апр. 29 09:09:42 2020`
**Version**: `20.4.16`
**Build date**: `Apr 26 2020`
**Build number**: `705`
**Platform**: `linux`
**Operating System**: `Ubuntu 19.10`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.12.4`
**Qt Version (runtime)**: `5.12.4`
**Portable mode**: `no`
**Settings path / key**: `/home/tom/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/tom/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `ru_RU`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `Yaru`
**Notes in current note folder**: `43`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://cloud.elefant.su`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `18.0.4.2`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_AU, en_CA, en_GB, en_US, en_ZA, ru_RU`
**Language names**: `Australian English (Australia), Canadian English (Canada), British English (United Kingdom), American English (United States), English (South Africa), русский (Россия)`
**Application dictionaries path**: `/home/tom/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `по умолчанию`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/tom/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `Программирование`
**database file**: `/home/tom/Nextcloud/Notes/notes.sqlite`

### Cloud connection `По умолчанию`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://cloud.elefant.su`
**username**: `tom`

## Settings

**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**AttachmentDialog/geometry** (QByteArray): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `/home/tom/Документы/md/s7com_plus_images`
**FileDialog/LastPath-InsertAttachment** (QString): `/home/tom/Документы/protocols/s7comm_plus`
**FileDialog/LastPath-InsertImage** (QString): `/home/tom/Документы/md/s7com_plus_images`
**ImageDialog/disableCopying** (bool): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-04-29T08:58:03.866`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `АСУТП, Программирование`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**NoteHistory-1** (QVariantList): `<variant list with 51 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `50`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `false`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `147f3c7b-673f-4d3a-aa8c-10970a46efc9`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `17`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/tom/Nextcloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Неизвестная ошибка`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `18.0.4.2`
**previousWorkspace** (QString): `initial`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2020-04-29T09.01.34, Note 2020-04-29T08.59.41, Note 2020-04-29T08.58.40, Note 2020-04-29T08.57.46, Note 2020-04-29T08.56.34, Note 2020-04-29T08.46.41, Note 2020-04-29T08.45.53, Note 2020-04-29T08.43.27, Note 2020-04-29T08.40.09, Note 2020-04-29T08.36.05, Note 2020-04-29T08.10.21, Note 2020-04-29T08.03.00, Note 2020-04-29T07.57.38, Note 2020-04-28T22.13.35, Note 2020-04-28T22.08.16, Note 2020-04-28T22.02.03, Note 2020-04-28T16.44.23, Note 2020-04-28T16.41.10, Note 2020-04-28T16.35.50, Note 2020-04-28T16.30.21, Note 2020-04-28T16.27.06, Note 2020-04-28T16.21.35, Note 2020-04-28T16.19.56, Note 2020-04-28T16.15.01, Note 2020-04-28T16.13.16, Note 2020-04-28T16.11.29, Note 2020-04-28T15.31.44, Note 2020-04-28T15.29.42, Note 2020-04-28T15.26.05, Note 2020-04-28T15.24.26, Note 2020-04-28T15.23.33, Note 2020-04-28T15.20.53, Note 2020-04-28T15.20.17, Note 2020-04-28T15.06.53`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (bool): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-147f3c7b-673f-4d3a-aa8c-10970a46efc9/name** (QString): `С предпросмотром`
**workspace-147f3c7b-673f-4d3a-aa8c-10970a46efc9/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-147f3c7b-673f-4d3a-aa8c-10970a46efc9/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Минимальный`
**workspace-initial/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 147f3c7b-673f-4d3a-aa8c-10970a46efc9`

## System environment

**HOME**: `/home/tom`
**LANG**: `ru_RU.UTF-8`
**LANGUAGE**: `ru:en`
**LC_ADDRESS**: `ru_RU.UTF-8`
**LC_IDENTIFICATION**: `ru_RU.UTF-8`
**LC_MEASUREMENT**: `ru_RU.UTF-8`
**LC_MONETARY**: `ru_RU.UTF-8`
**LC_NAME**: `ru_RU.UTF-8`
**LC_NUMERIC**: `ru_RU.UTF-8`
**LC_PAPER**: `ru_RU.UTF-8`
**LC_TELEPHONE**: `ru_RU.UTF-8`
**LC_TIME**: `ru_RU.UTF-8`
**LOGNAME**: `tom`
**PATH**: `/home/tom/.npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
**SHELL**: `/bin/bash`
**USER**: `tom`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**GTK_MODULES**: `gail:atk-bridge`
**XDG_DATA_DIRS**: `/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop`
**CLUTTER_IM_MODULE**: `ibus`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**DEFAULTS_PATH**: `/usr/share/gconf/ubuntu.default.path`
**DESKTOP_SESSION**: `ubuntu`
**DISPLAY**: `:1`
**GDMSESSION**: `ubuntu`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**GNOME_SHELL_SESSION_MODE**: `ubuntu`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**GTK_IM_MODULE**: `ibus`
**IM_CONFIG_PHASE**: `1`
**MANDATORY_PATH**: `/usr/share/gconf/ubuntu.mandatory.path`
**PWD**: `/home/tom`
**QT4_IM_MODULE**: `ibus`
**QT_IM_MODULE**: `ibus`
**SESSION_MANAGER**: `local/hp:@/tmp/.ICE-unix/2042,unix/hp:/tmp/.ICE-unix/2042`
**SHLVL**: `0`
**SSH_AGENT_PID**: `1945`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**USERNAME**: `tom`
**WINDOWPATH**: `2`
**XAUTHORITY**: `/run/user/1000/gdm/Xauthority`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-ubuntu:/etc/xdg`
**XDG_CURRENT_DESKTOP**: `ubuntu:GNOME`
**XDG_MENU_PREFIX**: `gnome-`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_DESKTOP**: `ubuntu`
**XDG_SESSION_TYPE**: `x11`
**XMODIFIERS**: `@im=ibus`
**_**: `/usr/bin/dbus-update-activation-environment`
**MANAGERPID**: `1791`
**INVOCATION_ID**: `293ef7f135e944458fc158c0755ace0a`
**JOURNAL_STREAM**: `9:43951`
**GJS_DEBUG_OUTPUT**: `stderr`
**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`
**GIO_LAUNCHED_DESKTOP_FILE**: `/usr/share/applications/PBE.QOwnNotes.desktop`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `9217`
</details>

**Comment by pbek** [comment]
I guess the folder got created in your file system, right?
Folders and files on Linux starting with a `.` are hidden. It will get you into all kinds of troubles if you want to work with such note sub-folders (e.g. syncing). :grimacing: In QOwnNotes they are also ignored. Although there is a setting in the *Panels settings* that you can tweak, but currently it still doesn't allow them to be loaded, I guess there need to be some special flags to be set in Qt to even be able to fetch them.

**Comment by tomintaiga** [comment]
Well, yes, such folders are hidden, but I didn't get any message that such folder is hidden or not allowed. Maybe add some sort of QMessageBox with help about it?

**Comment by pbek** [comment]
As I thought, you need to set a special flag to allow listing of hidden files with `QDir::entryList`. In the next release you will be able to clear your `Ignored sub-folders` setting to allow folders to start with `.`.

**Comment by pbek** [comment]
## 20.4.18
- you now are able to show invisible sub-folders (folders starting with `.`) in
  the note sub-folder panel if you clear the default `Ignored sub-folders`
  setting in the *Panels settings*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by tomintaiga** [comment]
Wow! That is realy cool! First time, someone made a release special for me! Thanks a lot!

Yes, now I can create subfolder like ".NET core".

But, if I set `Ignored sub-folders` to `^\.` back and try to create such folder - no message at all. I belive, that in such situation, user shoud have some message. Without It, user can't understand what happen, did he do something wrong, or program error happend?

**Comment by pbek** [comment]
It was more complex to implement this then anticipated...

## 20.5.0
- you will now get a warning dialog if you attempt to create a note sub-folder
  that will be ignored by the application, because the name is either used
  internally or ignored in the *Panels settings*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by tomintaiga** [comment]
Just perfect! It's now clear for user what happen and what he can do with that.

**Comment by pbek** [comment]
Great, thank you for testing!
