### ISSUE TITLE
[I] Script setting for interpreter doesn't work 

### ISSUE THREAD

**Issue by ZiluTian** [pbek/QOwnNotes#1719]
Please paste the text from the issue assistant here. It should be already in your clipboard.

#### Expected behaviour

Specifing the Python interpreter should make the script run (merge selected notes).

#### Actual behaviour

I specifed the full path of the Python interpreter (I triple checked through the terminal to make sure the path is correct and satisfies the version requirement), but the prompt keeps saying "Invalid command or path for python interpreter". I also tried changing the slashes to a different direction or surround it with quotes, but none worked. 

#### Steps to reproduce

Install "Merge notes" from script repository. Specify the full path of python interpreter. Prompt keeps denying the entry saying it is invalid

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[15:06:54] [scripting] loading script file: /Users/ztian/Library/Application Support/PBE/QOwnNotes/scripts/export-notes-as-one-html/export-notes-as-one-html.qml
[15:06:54] [scripting] loading script file: /Users/ztian/Library/Application Support/PBE/QOwnNotes/scripts/merge-notes/merge-notes.qml
[15:09:21] [scripting] loading script file: /Users/ztian/Library/Application Support/PBE/QOwnNotes/scripts/export-notes-as-one-html/export-notes-as-one-html.qml
[15:09:21] [scripting] loading script file: /Users/ztian/Library/Application Support/PBE/QOwnNotes/scripts/merge-notes/merge-notes.qml
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed Apr 29 15:07:47 2020`
**Version**: `20.4.17`
**Build date**: `Apr 28 2020`
**Build number**: `5555`
**Platform**: `macosx`
**Operating System**: `macOS 10.15`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
**Settings path / key**: `/Users/ztian/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/ztian/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_CH`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1440x900`
**Screen resolution(s)**: `1440x900, 1920x1200`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `8`
**Calendar items**: `0`
**Enabled scripts**: `2`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/Users/ztian/Library/Application Support/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/Users/ztian/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/Users/ztian/Nextcloud/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

### Script `Export notes as one HTML file`

**id**: `1`
**path**: `/Users/ztian/Library/Application Support/PBE/QOwnNotes/scripts/export-notes-as-one-html/export-notes-as-one-html.qml`
**variablesJson**: *empty*
**identifier**: `export-notes-as-one-html`
**version**: `1.0.0`
**minAppVersion**: `18.03.7`

### Script `Merge selected notes`

**id**: `2`
**path**: `/Users/ztian/Library/Application Support/PBE/QOwnNotes/scripts/merge-notes/merge-notes.qml`
**variablesJson**: 
```
{
    "deleteMerged": true,
    "mergeToFirst": true,
    "pyCommand": "\\usr\\bin\\python3"
}
```
**identifier**: `merge-notes`
**version**: `0.0.3`
**minAppVersion**: `17.08.5`

## Settings

**AKLastCheckInAttemptDate** (QDateTime): `2019-11-06T20:48:58.828`
**AKLastCheckInSuccessDate** (QDateTime): `2019-11-06T20:48:59.684`
**AKLastEmailListRequestDateKey** (QDateTime): `2020-04-29T14:08:34.602`
**AKLastIDMSEnvironment** (qlonglong): `0`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Analogix Slimport Type-C to Legacy Adapter** (QString): `1`
**Android Android** (QString): `1`
**Country** (QString): `CH`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `true`
**EPSON XP-442 445 Series** (QString): `1`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (qlonglong): `4`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**FileDialog/LastPath** (QString): `/Users/ztian/anaconda3/bin`
**FileDialog/LastPath-ScriptSettingsFile-merge-notes-pyCommand** (QString): `/Users/ztian/anaconda3/bin`
**Generic USB Audio** (QString): `1`
**HP DeskJet 3630 series** (QString): `1`
**HP ENVY 4520 series** (QString): `1`
**HP ENVY 5000 series** (QString): `1`
**HP OfficeJet 4650 series** (QString): `1`
**HUAWEI FRD-L04** (QString): `1`
**Hewlett Packard MFP M277dw** (QString): `1`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-04-29T14:56:40.362`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**Logitech Wireless Headset** (QString): `1`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (qlonglong): `32`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `.SF NS Mono,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `.AppleSystemUIFont,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `.SF NS Mono,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `.AppleSystemUIFont,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MultipleSessionEnabled** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 8 item(s)>`
**NoteHistoryCurrentIndex-1** (qlonglong): `7`
**PKSecureElementAvailableFlagsByHost** (qlonglong): `1`
**PersistentScripting/MdNT/pyCommand** (QString): *empty*
**PiwikClientId** (QString): `<hidden>`
**Realtek USB 10·100·1000 LAN** (QString): `1`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (qlonglong): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-customAction_exportHTML** (QString): *empty*
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**TISRomanSwitchState** (qlonglong): `0`
**VIA Technologies Inc/ USB 2/0 BILLBOARD** (QString): `1`
**WebAutomaticSpellingCorrectionEnabled** (bool): `true`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `false`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (bool): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (qlonglong): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (qlonglong): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (bool): `true`
**disableAutomaticUpdateDialog** (bool): `false`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (bool): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (qlonglong): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (qlonglong): `1024`
**imageScaleDownMaximumWidth** (qlonglong): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (qlonglong): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (qlonglong): `18`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (qlonglong): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (qlonglong): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (qlonglong): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (qlonglong): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (qlonglong): `0`
**notesPanelOrder** (qlonglong): `0`
**notesPanelSort** (qlonglong): `1`
**notesPath** (QString): `/Users/ztian/Nextcloud/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (qlonglong): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (qlonglong): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (bool): `false`
**restoreLastNoteAtStartup** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Stlc The Simply Typed Lambda-Calculus 2020-04-29T14.31.35, Stlc The Simply Typed Lambda-Calculus 2020-04-29T14.30.20, Stlc The Simply Typed Lambda-Calculus 2020-04-29T14.30.03, Stlc The Simply Typed Lambda-Calculus 2020-04-29T14.15.08, Stlc The Simply Typed Lambda-Calculus 2020-04-29T14.14.45, Stlc The Simply Typed Lambda-Calculus`
**showMatches** (bool): `true`
**showMenuBar** (bool): `false`
**showStatusBar** (bool): `true`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (qlonglong): `0`
**tagsPanelSort** (qlonglong): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (qlonglong): `6`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (qlonglong): `22222`
**webSocketServerService/token** (QString): `pktXGad2`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**USER**: `ztian`
**DISPLAY**: `/private/tmp/com.apple.launchd.zDaI71ctCB/org.macosforge.xquartz:0`
**LOGNAME**: `ztian`
**PATH**: `/usr/bin:/bin:/usr/sbin:/sbin`
**SSH_AUTH_SOCK**: `/private/tmp/com.apple.launchd.qiAMStYBUp/Listeners`
**HOME**: `/Users/ztian`
**SHELL**: `/bin/bash`
**__CF_USER_TEXT_ENCODING**: `0x1F6:0x0:0x2`
**TMPDIR**: `/var/folders/64/74g3scgd54721f5ctbqllg2h0000gp/T/`
**XPC_SERVICE_NAME**: `com.PBE.QOwnNotes.14564`
**XPC_FLAGS**: `0x0`
**QT_LOGGING_RULES**: `qt.network.ssl.warning=false`
</details>

**Comment by pbek** [comment]
That sounds like a script issue. Can you please move your issue to https://github.com/qownnotes/scripts/issues/ and mention the author(s).

**Comment by pbek** [comment]
> Specify the full path of python interpreter. Prompt keeps denying the entry saying it is invalid

and please mention what you have entered
