### ISSUE TITLE
Feature request: tabs/shortlist

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#1720]
Reason: tabs/shortlist would be an awesome feature!

Opening a feature request as I've been told it is presents-give-away-time :wink: 

Copy/paste of my message on Telegram, dd April 29:

> My most wanted feature is tabs. I just want a shortlist of notes that I'm dealing with right now. I know tabs is difficult, but would it be possible to have a new panel that shows a shortlist of notes? Maybe the notes get a temporary tag and the panel shows the notes for this tag. A shortcut/button or drag n drop could assign this special tag. Maybe you could turn this in a more general feature: add panel with note list per tag, or would that be too heavy. Just thinking out loud here 🤔😉

**Comment by pbek** [comment]
:wink:

**Comment by pbek** [comment]
## 20.5.0
- you now can right-click on a note in the note list and click `Open note in tab`
  to **open the note in a new tab** in the note edit panel
    - those tabs can be individually be closed and moved
    - opening notes without the new context menu action will open the note in
      the current tab
    - if only one tab is open the tabbed interface will be hidden
    - since right-clicking a note in the note list also already opens the note
      a click on the new context menu action will attempt to open the last note
      to really open a new tab if only one tab was open

**Comment by pbek** [comment]
just for you, @sanderboom... but I think @Waqar144 might also like it :grin:

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
20.5.1
- you can now jump to the previous or next note tab with <kbd>Alt + PageUp</kbd>
  and <kbd>Alt + PageDown</kbd>
    - please visit [QOwnNotes shortcuts](https://www.qownnotes.org/shortcuts/QOwnNotes)
      for a list of all shortcuts

**Comment by sanderboom** [comment]
Like I wrote in Telegram:  Wooohah! This is a big one! 😁 🚀 🎉 

For me this means going from 4+ open instances of QON to 1 instance with smooth tabbing. Thanks for the present :wink: I am sure a lot of users will enjoy this feature. 

Regarding shortcuts: can I suggest <kbd>Ctrl + w</kbd> for closing a tab?

I will set switching tabs to <kbd>Ctrl + Tab</kbd> and <kbd>Ctrl + Shift + Tab</kbd> - because that's what I'm used to in like in browsers/Dolphin.

If I find any glitches I'll report, but everything seems smooth for now.

**Comment by pbek** [comment]
> Regarding shortcuts: can I suggest Ctrl + w for closing a tab?

Good idea!

> I will set switching tabs to Ctrl + Tab and Ctrl + Shift + Tab - because that's what I'm used to in browsers/Dolphin.

For me that switches between (KDE) desktops. Do you use different virtual desktops?

**Comment by sanderboom** [comment]
> For me that switches between (KDE) desktops. Do you use different virtual desktops?

Yes, I do (10 actually :smile:). For me switching virtual desktops is set to <kbd>Meta + Tab</kbd>, in line with <kbd>Meta + 1</kbd>, <kbd>Meta + 2</kbd>, etc. Shortcuts are very personal of course, very relevant: https://xkcd.com/1806/ :laughing: 

As long as it is customizable it should be good.

**Comment by pbek** [comment]
> Yes, I do (10 actually smile). For me switching virtual desktops is set to Meta + Tab, in line with Meta + 1, Meta + 2, etc. Shortcuts are very personal of course

Those aren't default (right?) but they make sense.

> very relevant: https://xkcd.com/1806/ 

Yes, great idea! :laughing: Or use a Dvorak Keyboard. :grin:

**Comment by pbek** [comment]
## 20.5.1
- new tabbing shortcuts were added
    - you can now jump to the previous or next note tab with <kbd>Alt + PgUp</kbd>
      and <kbd>Alt + PgDn</kbd>
    - you can now close the current note tab with <kbd>Ctrl + W</kbd>
    - you can now open a new note in a new tab with <kbd>Ctrl + Shift + N</kbd>
    - you can change or disable all shortcuts in the *Shortcuts settings*
    - please visit [QOwnNotes shortcuts](https://www.qownnotes.org/shortcuts/QOwnNotes)
      for a list of all shortcuts

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Airgunster** [comment]
@pbek Awesome work and feature (I was as many others missing that one), thanks sooo much!

P.S. That would be extremely useful to save tabs (i.e. on next restart of QON these tabs will still remain to be open).

**Comment by pbek** [comment]
Thank you, @Airgunster. Please open another feature request. I want to finally close this one. :grin:

**Comment by pbek** [comment]
## 20.5.4
- if the note of the current tab is renamed now the tab also will be renamed

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by tragtragtrag** [comment]
I have another feature request in connection with tabs/shortlists (but not sure if it can be implemented, this is why I don't open a new issue).

If there are many tabs open, there is not enough space for all tabs, so the not-shown tabs can be reached in the tab row only by clicking on the arrow buttons.
An alternative, more comfortable solutions would be to show more than one tab row, i.e. expand the numbers of the tab rows. Like this all tabbed notes - also if there are many notes - would be visible at once without the need to click the arrow buttons. This would facilitate my work a lot. Since only the tab view allows a manual order of the notes, I mostly use this tab-feature.

**Comment by pbek** [comment]
> An alternative, more comfortable solutions would be to show more than one tab row, i.e. expand the numbers of the tab rows.

I don't think https://doc.qt.io/qt-5/qtabwidget.html supports that, if it would support it it would be doable.

**Comment by tragtragtrag** [comment]
OK, I see, thank you. Another option would be a scrollbar, but this might also not be possible.

**Comment by pbek** [comment]
> but this might also not be possible

correct and it also would be annoying :sweat_smile:
