### ISSUE TITLE
Add Qownnotes to Nextcloud app store as external app

### ISSUE THREAD

**Issue by sunjam** [pbek/QOwnNotes#1721]
[Now possible to add Qownnotes as a third party app in the Nextcloud store so people can more easily find it](https://github.com/nextcloud/appstore/issues/95#issuecomment-621959723).

**Comment by pbek** [comment]
Thank you, I just submitted it! https://apps.nextcloud.com/apps/qownnotes
Although so far there doesn't seem to be a way to edit entries...

**Comment by pbek** [comment]
Hm, it should be possible to edit apps according to https://github.com/nextcloud/appstore/issues/670
