### ISSUE TITLE
Suggestion: Apply-Button for the Settings

### ISSUE THREAD

**Issue by abthediablo** [pbek/QOwnNotes#1722]
Especially if you are want to change the color-setting of QOwnNotes it would be helpfull to change the settings with an Apply-Button so you don't have to leave the setting-menu by pressing OK to see the changes.

#### Expected behaviour
-
#### Actual behaviour
You will leave the menu by pressing OK and if you don't agree with the settings you have to open the menu again.
#### Steps to reproduce
-
#### Output from the debug section in the settings dialog
-

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
Which "color-settings" are we talking about? The note editor color schemes? You need to restart the applications to apply all of them.

**Comment by pbek** [comment]
I will close this issue until there is more information.
