### ISSUE TITLE
Hook request: rename Note

### ISSUE THREAD

**Issue by r00tr4v3n** [pbek/QOwnNotes#1723]
Could you add a `renameNoteHook`, please?

Goal: When using the 'allow different file name setting' for yaml headers, it would be nice to keep the title in sync with the file name via script nonetheless.

**Comment by pbek** [comment]
Can you please describe in more detail

1) what this `renameNoteHook` is supposed to do
2) when it should be called by QOwnNotes
3) to be able to do what in a script

**Comment by r00tr4v3n** [comment]
1. help to keep the markdown title of the note in sync with the file name when 'allow different file name' setting is on
2. be called when the note is renamed via context menu (are there other means?) and provide the name or entire note
3. use the file name to change the markdown title via regex

**Comment by pbek** [comment]
The markdown title in the note text isn't changed in QON when a note file is renamed.
Only the note filename of a note is changed if `allow different file name setting` is off and there would be a collision with another note with the same title (and thus same filename).

**Comment by r00tr4v3n** [comment]
I see, so this would add possible qol features via script. Since QON cares about the file name when renaming one can be sure the name is valid. It would be a one way street anyway (note name -> note text)

**Comment by pbek** [comment]
> qol features

What is "qol" for you? "Quality of life"?

> Since QON cares about the file name when renaming one can be sure the name is valid. It would be a one way street anyway (note name -> note text)

Was that a observation, a question or a request? (I ask because I don't understand what you are trying to point out :smile:)

**Comment by r00tr4v3n** [comment]
> and there would be a collision with another note with the same title (and thus same filename).

Just pointing out there should be no collisions when keeping it simple (one way provider of the new file name as hook).

**Comment by pbek** [comment]
Ok, so we can close this, right?

> Goal: When using the 'allow different file name setting' for yaml headers, it would be nice to keep the title in sync with the file name via script nonetheless.

Why don't you just turn off 'allow different file name setting'?

**Comment by r00tr4v3n** [comment]
OK, that question made me wonder. I thought the setting was just checking for the first line and was necessary to be on for the the YAML header. Thanks for the input!

**Comment by pbek** [comment]
> I thought the setting was just checking for the first line and was necessary to be on for the the YAML header.

Did you read that somewhere? Because if yes that should be updated.
I made it work that frontmatters and leading `#` in the note headline are ignored when determining the file name a while ago.

**Comment by pbek** [comment]
But I think Nextcoud Notes still uses the headline as it is...

**Comment by r00tr4v3n** [comment]
It was often mentioned in issues and scripts in combination with in-note tags/headers. I must have misinterpreted it. Yes, maybe it was in combination with Nextcloud Notes.

**Comment by pbek** [comment]
If you read it in a script description in the script repository or in the source code of a script please ping me (or better change it in a pull request).

**Comment by r00tr4v3n** [comment]
Will do!
