### ISSUE TITLE
[F] Make "Remove current note" in the menu to accept some kind of note identifier

### ISSUE THREAD

**Issue by ZiluTian** [pbek/QOwnNotes#1724]
#### Expected behaviour

Remove current note will remove a selected note by some identifier (id, or path, or name) when invoked from "script.triggerMenuAction", with default being the latest note (the current behaviour)

#### Actual behaviour

Currently removing a selected note requires a separate script, which may not be as safe. Visually, one can remove note from either the menu or context menu, but context menu is not available in script service and menu action doesn't allow one to specify which note. 

#### Steps to reproduce

Remove current note in the menu

**Comment by pbek** [comment]
You cannot pass pass parameters to an action. So what are looking for? A way to delete notes from a script? What are you trying to achieve? Are operating system operations/commands not safe enough?

**Comment by pbek** [comment]
I will close this until there is more information.
