### ISSUE TITLE
"Show note in file manager" not working with Caja on Manjaro

### ISSUE THREAD

**Issue by r00tr4v3n** [pbek/QOwnNotes#1727]
QON cannot open the containing folder of a note or attachment (from orphaned media window).
I am using Caja on Manjaro.

#### Expected behaviour
- open the containing folder
#### Actual behaviour
- Dialog: "Could not display: '/home/filename.md' The location is not a folder"
#### Steps to reproduce
- right click on a note and select "Show note in file manager"

**Comment by pbek** [comment]
I haven't installed Caja anywhere, but it should be handled in:
https://github.com/pbek/QOwnNotes/blob/129dd0fb8d47ad666dd131d06b0bce3fda86b9d7/src/utils/misc.cpp#L157-L160

What does `xdg-mime query default inode/directory` output for you?

**Comment by r00tr4v3n** [comment]
`caja-folder-handler.desktop` is correct.

**Comment by r00tr4v3n** [comment]
This might be a missing feature in Caja: [issue](https://github.com/mate-desktop/caja/issues/1025)
It does require the folder path.

**Comment by r00tr4v3n** [comment]
```c++
            QDir dir = QFileInfo(path).absoluteDir();
            QString absDir=dir.absolutePath();
            proc.startDetached(
                QStringLiteral("caja"),
                QStringList{"--no-desktop", QDir::toNativeSeparators(absDir)});
```
This should do it ([pull request](https://github.com/pbek/QOwnNotes/pull/1728))

**Comment by pbek** [comment]
## 20.5.3
- fixed `Show note in file manager` for file manager Caja on Linux
  (for [#1727](https://github.com/pbek/QOwnNotes/issues/1727), thank you @r00tr4v3n)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by r00tr4v3n** [comment]
Works fine :+1:

**Comment by pbek** [comment]
Great, thank you for testing!
