### ISSUE TITLE
[Feature Request] QOwnNotes browser clipper shortcuts and the ability to do both a screenshot and a html to markdown at the same time in the same note (For archiving) 

### ISSUE THREAD

**Issue by wadbr** [pbek/QOwnNotes#1729]
Hello, first I just want to say thank you for this amazing app and the INSANE development that has gone into it, it has saved me hours of frustration! 

#### Expected behaviour
- One button to both do a screenshot (display it at the top of the note) and a html to markdown (the current normal behaviour)
- add shortcuts for these actions
#### Actual behaviour
- screenshots: both save seperatly
- shortcuts: there's one shortcut and it's "activate this plugin"
#### Why
- the text clipping does not save format (and actually sometimes misses content, but that's normal modern html weirdness) 
- having both the text and the format will be great for archiving both the text so it's searchable and the format of the site
- shortcuts are awesome :D !

(also small non-essential requests: change capture image format to PNG, it is currently in low quality JPEG, and if it is possible to do a full page scrollable screenshot that would be amazing)

**Comment by pbek** [comment]
Thank you for your kind words and your suggestion. Can you please post it on https://github.com/qownnotes/web-companion/issues.
