### ISSUE TITLE
Sticky note-tabs

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1730]
## 20.5.4
- you can now stick a note to a tab with the new action `Toggle note stickiness of current tab`
  in the *Note / Navigation* menu or by double-clicking on the tab
    - this will cause a new tab being opened automatically if you click on
      another note while in this tab
    - the stickiness status will get also restored when the note folder is
      switched or the application is started

**Comment by pbek** [comment]
@sanderboom, @Airgunster 
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
## 20.5.5
- now a tooltip is shown for note tabs to guide you how to stick and unstick notes
- the note tab sticky status will now be shown correctly if a note is double-clicked
  in the note list

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Airgunster** [comment]
@pbek, works great, thanks a lot!

**Comment by pbek** [comment]
Great, thank you for testing!
