### ISSUE TITLE
Code block line with 17 spaces indent prevents further rendering of the preview

### ISSUE THREAD

**Issue by Waqar144** [pbek/QOwnNotes#1732]
#### Expected behaviour

Code blocks line with 17 spaces indent should be rendered like normal

#### Actual behaviour

Code blocks line with 17 spaces indent don't get rendered at all
Ex:
```md
    ```
                 hello
    ```
```
will not get rendered and will prevent any further text from rendering as well.

**Comment by pbek** [comment]
I know just the man to fix that. :laughing:  :arrow_up:

**Comment by RichardBaker3020** [comment]
I ran into this bug today, if there is a Code blocks line with 17 spaces indent, all the content below won't be rendered in preview mode.

**Comment by Waqar144** [comment]
I will try to do a proper bump

**Comment by pbek** [comment]
## 22.11.0
- a preview issue with 17 spaces in code-blocks was fixed

**Comment by pbek** [comment]
> I will try to do a proper bump

awesome!

**Comment by Waqar144** [comment]
can you hard reset the commit? It's causing conflicts

**Comment by pbek** [comment]
All our diverging commits are causing conflicts. The file structure of the md4c project changed.

This commit https://github.com/qownnotes/md4c/commit/f6b41fe14c05530447e5d93d5fbabd8f293c084c is just https://github.com/mity/md4c/commit/c595c2ed0076616856634332c35a7a3c851b287c#diff-c117525877f3cea55f4757cd7f32ea258050f83a845a9e9c33ef51e7214232dd and shouldn't cause a lot of troubles...

I guess it would be best to just start with a clean https://github.com/mity/md4c/ on your side.

**Comment by Waqar144** [comment]
If you  reset the repo to the previous commit, i can push

**Comment by Waqar144** [comment]
> Hard-resetting now will break the current version of QOwnNotes.

It won' I thinkt. Just hard reset the commit then merge the following branch to master and push and then bump that in QON. https://github.com/qownnotes/md4c/tree/work/update-md4c

With the bump cmake file and qmake file needs minor changes

**Comment by Waqar144** [comment]
https://github.com/pbek/QOwnNotes/pull/2641 created. It contains the cmake/qmake changes needed to build. But the build will fail currently as the module needs to be bumped

**Comment by pbek** [comment]
@sanderboom, @davuses
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
## 22.11.1
- the Markdown to HTML converter library md4c was updated to get the latest fixes and
  improvements (for [#1732](https://github.com/pbek/QOwnNotes/issues/1732), thank you, @Waqar144)

There now is a new release, could you please test it and report if it works for you?

**Comment by sanderboom** [comment]
Works like a charm :rocket:

**Comment by pbek** [comment]
Awesome!
