### ISSUE TITLE
Notes: Manual sort order

### ISSUE THREAD

**Issue by tragtragtrag** [pbek/QOwnNotes#1734]
#### Expected behaviour
It would be very helpful if the order of the notes could be arranged manually (e.g. by drag and drop).

Example for use: Writing a book with many chapters and subchapters (in MS Word or whatever). For every chapter/subchapter I have a single note file in which I make important notes. In order to have the right sequence on the note list, I could number the note-names and sort them alphabetically. But the problem arises if I add additional/delete chapters/subchapters. Then every time I would have to rename all succeeding/preceeding chapters/subchapters. During the progress of writing, this could be very annoying. Therefore, it would be great if I could sort the order manually and if this would be saved when closing QOwnNotes.
#### Actual behaviour
The sort order option for notes is by "modification date" or "alphabetically" only.

PS: I absolutely love QOwnNotes and with the many (nearly daily!) updates it becomes even better (e.g. I like the new tab integration)! Thank you so much for your effort, I really appreciate that!

**Comment by pbek** [comment]
I'm sorry, that isn't possible and would be very hard to implement because the notes are not stored in a database but are loaded directly from your note folder.

(duplicate #973)

**Comment by tragtragtrag** [comment]
OK, I see, the missing database is the problem (or better, the great advantage of QOwnNotes...!).

Thanks for your answer and sorry for the duplicate
