### ISSUE TITLE
Question: Use of custom icons for toolbar

### ISSUE THREAD

**Issue by vortsg** [pbek/QOwnNotes#1735]
Is it possible to use custom icons for items on the toolbar. I see that there is support for **freedesktop** icons. My uses cases are generically listed below.

1. Would like to use a different set of icons
2. Change icons for a specific toolbar item

Thanks for your response.

**Comment by pbek** [comment]
Yes, freedesktop icons are supported (if you don't override the icons in the settings).
If that's not enough you could experiment with the script `Custom user interface styling` from the script repository if you can override icons of single actions with it.

**Comment by vortsg** [comment]
Thanks! I will take a look at the script and see if I can modify that for my purpose.

**Comment by pbek** [comment]
Just ask if you need anything. :grin:
