### ISSUE TITLE
[API request] file handling

### ISSUE THREAD

**Issue by r00tr4v3n** [pbek/QOwnNotes#1736]
To facilitate platform independence, it would be great to have file management for scripting available to reduce the need for external applications like nodejs just to create a file.

e. g.
```cpp
void ScriptingService::writeFile(QString filePath, QString txt, bool createParentDirs = false); 
QString ScriptingService::readFile(QString filePath); 
bool ScriptingService::fileExists(QString filePath); 
```

**Comment by pbek** [comment]
Thank you for your suggestion. Pull requests are welcome. :grin:

**Comment by r00tr4v3n** [comment]
Are you content with the method declarations?

**Comment by pbek** [comment]
Basically you already did them :laughing:

**Comment by pbek** [comment]
## 20.5.7
- added new scripting methods `fileExists` and `readFromFile` and a new parameter
  `createParentDirs` for method `writeToFile` (for [#1736](https://github.com/pbek/QOwnNotes/issues/1736), thank you @r00tr4v3n)
    - for more information please take a look at the
      [scripting documentation](https://docs.qownnotes.org/en/latest/scripting/methods-and-objects/)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
