### ISSUE TITLE
[Suggestion] Sub context menu for scripts 

### ISSUE THREAD

**Issue by r00tr4v3n** [pbek/QOwnNotes#1737]
When using multiple scripts the context menu tends to increase to two columns.
Putting them into a sub menu might be one solution. In addition, we could extend `registerCustomAction` with yet another flag to force the action in the main menu in case it is a frequently used one.
A better solution might be automatically generated display settings in the script settings but that might be exaggerate it for now. 
```
void ScriptingService::registerCustomAction(QString identifier,
                                            QString menuText,
                                            QString buttonText,
                                            QString icon,
                                            bool useInNoteEditContextMenu,
                                            bool hideButtonInToolbar,
                                            bool useInNoteListContextMenu,
                                            bool forceMainContextMenu);
```

![image](https://user-images.githubusercontent.com/6073574/81494825-f96db180-92ab-11ea-9e5a-19d7368534ca.png)

**Comment by pbek** [comment]
I think I don't understand this feature request. What is it you want to achieve?

> A better solution might be automatically generated display settings in the script settings but that might be exaggerate it for now.

What should those display settings do? Who generates them? When are they viewed?

**Comment by r00tr4v3n** [comment]
I'd like to avoid context menus with two columns.
> What should those display settings do? Who generates them? When are they viewed?

They should be automatically generated if a custom action is registered and allow to change the flags for buttons and context menus. But as I said, that might blow it out of proportion.

**Comment by pbek** [comment]
I don't like that `Scripts` sub-menu a lot, one more click. When did you get two columns?

**Comment by pbek** [comment]
I'll keep your menu as it is (I only fixed the menu separator).

## 20.5.7
- there now is a new sub-menu for custom actions from scripts in the note-edit
  context menu to prevent that too many menu items are shown on the first level
  of the menu (for [#1737](https://github.com/pbek/QOwnNotes/issues/1737), thank you @r00tr4v3n)

**Comment by r00tr4v3n** [comment]
Manjaro with dark mode and Fusion style. Weird, I could only reproduce it once just now. As if the height of a context item changes.

**Comment by r00tr4v3n** [comment]
The sub menu should be for rarely used functions. The `force main context menu` flag could be used to keep it one click less away?

**Comment by pbek** [comment]
I leave the sub-menu as it is for now.

**Comment by pbek** [comment]
Far too many parameters already...

**Comment by r00tr4v3n** [comment]
OK :)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by r00tr4v3n** [comment]
Works fine!
This would probably have been two columns:
![image](https://user-images.githubusercontent.com/6073574/81607397-e6a2cc00-93d4-11ea-8814-a1a4f1a8ec6b.png)

**Comment by pbek** [comment]
Great, thank you for testing!
You have quite some scripts going on, I like that. :grin:

**Comment by pbek** [comment]
btw. better use `bash` in your code block, not `shell` :wink:

**Comment by r00tr4v3n** [comment]
> You have quite some scripts going on, I like that. grin

Yes, some are just needed once a week but it's so great to have them!
> btw. better use bash in your code block, not shell wink
 
Thanks! Seems like even @Waqar144 can still learn something with QON :grin:

**Comment by pbek** [comment]
Did he use `shell`? (he wrote the code block syntax highlighting)

**Comment by r00tr4v3n** [comment]
That's what the quotation said.

**Comment by pbek** [comment]
`shell` works on github...
