### ISSUE TITLE
Markdown options

### ISSUE THREAD

**Issue by LionelR** [pbek/QOwnNotes#174]
In dark mode, the background color of the editor panel is white, but some elements in the editor are yellow or in light color which is not eye-candy, and the code blocks in the markdown preview panel are foreground:black, background:dark-grey, which is also not readable.
So, it would be nice to have the possibility to modify these colors, plus in the markdown preview the ability to accept the syntax-highlighting github feature : 
```javascript
var s = "JavaScript syntax highlighting";
alert(s);
```

```
```javascript
var s = "JavaScript syntax highlighting";
alert(s);
```
```

**Comment by pbek** [comment]
Thank you for reporting. Can you please make screenshots?
Keep in mind that QOwnNotes doesn't change the colors of the theme of your operating system, it just tweaks some colors that aren't touched by the theme of your operating system.

**Comment by pbek** [comment]
syntax-highlighting: if you know a small library for C++ that detects JS in code-blocks what would be doable (but not very pretty due to the limitations of QTextEdit). if not, this would have to wait until a full preview-browser integration, that currently would cause a lot of technical troubles...

**Comment by LionelR** [comment]
![capture du 2016-05-19 09 23 25](https://cloud.githubusercontent.com/assets/490118/15385787/1b10f904-1da4-11e6-84da-38e073695477.png)

On Ubuntu 14.04, Ultra-Flat theme. Switching to the default Ambiance theme doesn't change anything.

For the syntax highlighting, it's just a proposed enhancement, not a top one priority feature :) I'm not confortable with C++, but maybe this project could help : https://github.com/cloose/CuteMarkEd

**Comment by pbek** [comment]
- dark: it seems your current theme doesn't style your background dark, that's why it is white
- highlighting: Thank you for your example. CuteMarkEd uses QWebView, which is the thing I also wanted to do, but it would raise our minimum Qt requirements to 5.4, which would exclude Debian 8.0 (that uses Qt 5.3)... And the lacking printing support is an other thing (QTextEdit could serve as a workaround)...

**Comment by pbek** [comment]
until we use a full fledged browser I will mark this issue "wontfix"

**Comment by CTrauma** [comment]
"If  you know a small library for C++ "
As a matter of fact I do. I have been using Andre Simon's Highlight library from here:

Andre Simon Highlight
http://www.andre-simon.de/doku/highlight/en/screenshots.php

Along with the abandoned highlight wlx sources from here:

Jens Theeß highlight.wlx
https://web.archive.org/web/20090508044550/http://www.theess.com/highlight

To create a plugin for Double Commander http://doublecmd.sourceforge.net/ to browse source code and apply syntax highlighting. The highlight library is pretty mature and allows for a lot of tweaking to get just the look you want and includes a plugin interface for extensions written in lua. 

Here is a basic overview of the features:

http://andre-simon.de/dokuwiki/doku.php?id=en:features

I'm planning to get my C++ wlx code up on github as soon as I get the build workflow cleaned up if you are interested in a real world use case, but the docs are really good.

Just a thought on a feature I would love to see in QOwnNotes

**Comment by pbek** [comment]
Thank you for your find, @CTrauma.
As I understand it you can converter from source code to HTML with color. I'm not sure what source formats are supported. I saw some examples on <http://www.andre-simon.de/doku/highlight/en/syntax-samples.php>.

And I didn't found the license the library / tool is released under.
Do you know more, @CTrauma?

**Comment by CTrauma** [comment]
These are the languages supported: http://www.andre-simon.de/doku/highlight/en/langs.php

These are the output formats: 

  html:     HTML5
  xhtml:    XHTML 1.1
  tex:      Plain TeX
  latex:    LaTeX
  rtf:      RTF
  odt:      OpenDocument Text (Flat XML)
  ansi:     Terminal 16 color escape codes
  xterm256: Terminal 256 color escape codes
  svg:      SVG
  bbcode:   BBCode
  pango:    Pango Markup

License on this page: http://www.andre-simon.de/zip/download.php

The software is published under the GPLv3 license. You can use it for free. If the software is modified and distributed, it is required that all users get free access to the modified source code.
See the license description file COPYING included in the packages.

**Comment by pbek** [comment]
GPLv3-Lizenz, I've missed that! Thanks, @CTrauma!

**Comment by CTrauma** [comment]
If you are interested I have my initial commit done to github here https://github.com/CTrauma/highlightcommander

I still have some work to do to get Linux support in place as well as clean up the docs, but if you need a real world example usage of the highlight library it could be helpful.

**Comment by pbek** [comment]
Nice! Thank you!
