### ISSUE TITLE
Feature request: copy image directly from preview pane

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#1741]
Would it be possible to copy an image to the clipboard from the Preview panel? I see that the `Copy` option in the context menu is grayed out. 

Workflow now: see the image in the Preview panel, search in the editor panel for a word close by, click the link to the image, Gwenview opens, Edit -> Copy, and finally paste somewhere I need the image (e.g. a chat window).

**Comment by pbek** [comment]
I guess that can be implemented for local images... I'm not sure about remote (embedded) images.

**Comment by sanderboom** [comment]
> I guess that can be implemented for local images... I'm not sure about remote (embedded) images.

Awesome.

**Comment by pbek** [comment]
## 20.5.8
- you can now copy an image to the clipboard by right-clicking on it in the preview
    - this works for local and as well for remote images

**Comment by sanderboom** [comment]
Maestro! :smile: 

<img width="383" alt="image" src="https://user-images.githubusercontent.com/5956570/81833208-b9bef800-953f-11ea-84a7-236c65c307b6.png">

Importance: low -> still added in 19 hours :rocket: :smile:

**Comment by pbek** [comment]
:grin: 

The real elephant in the room is this change:

## 20.5.8
- the binary translation files were removed from the git repository, they are now
  built in all build systems (for [#1744](https://github.com/pbek/QOwnNotes/issues/1744))

We'll see how that goes. :laughing: 

There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
Can you please also test a non-english language. :grin:

**Comment by sanderboom** [comment]
Don't know about your :elephant: but copying of (local) images works great! Big feature again (at least for me) :raised_hands: 

BTW I'm not sure in what scenario you embed remote images?

OK tried QON in Dutch for the first time. Not for me, but all seems to work.

**Comment by pbek** [comment]
Great, thank you for testing!

> BTW I'm not sure in what scenario you embed remote images?

`![my image](http://server/my-remote-inage.jpg)`

**Comment by pbek** [comment]
e.g. `![](https://avatars2.githubusercontent.com/u/5956570?s=88&u=0f1c2a4e582961a2be02d25c4525310c08680b4a&v=4)`

![](https://avatars2.githubusercontent.com/u/5956570?s=88&u=0f1c2a4e582961a2be02d25c4525310c08680b4a&v=4)

:grin:

**Comment by sanderboom** [comment]
:smile: 

I just found it: the `Don't copy image to media folder` is necessary for a remote image (with preview). Nice!

**Comment by pbek** [comment]
You could have just pasted above markdown. :grin:

**Comment by pbek** [comment]
## 26.4.9

- Added **Copy image to clipboard** and **Copy image file path** actions to the
  **QLiteHtml preview** context menu when right-clicking preview images, so image
  content and the resolved local image path can be copied directly from the preview
  (for [#1741](https://github.com/pbek/QOwnNotes/issues/1741))
