### ISSUE TITLE
New editor schema: Solarized Bright

### ISSUE THREAD

**Issue by sauces1313** [pbek/QOwnNotes#1742]
[Solarized Bright - QOwnNotes-editor-schema.ini.zip](https://github.com/pbek/QOwnNotes/files/4620622/Solarized.Bright.-.QOwnNotes-editor-schema.ini.zip)

I want to submit a new editor schema.

(attached)

**Comment by pbek** [comment]
Thank you very much.

**Comment by pbek** [comment]
In your export the schema is called `Solarized Dark`, how should it be called?

**Comment by sauces1313** [comment]
Sorry about that.

Call it "Solarized Dark"

**Comment by pbek** [comment]
## 20.5.9
- added a **new editor color schema** *Solarized Dark*
  (for [#1742](https://github.com/pbek/QOwnNotes/issues/1742), thank you @sauces1313)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by sauces1313** [comment]
That was quick! Just updated, works for me.
Thanks.

**Comment by pbek** [comment]
Great, thank you for testing!
