### ISSUE TITLE
[I] Changing the name of the note alters creation date on file

### ISSUE THREAD

**Issue by heroselohim** [pbek/QOwnNotes#1743]
#### Expected behaviour

Preserve original creation date on file

#### Actual behaviour

Creation date is updated to "now" on file

#### Steps to reproduce

1. Create a note with any name
2. Change the title of the note
3. Save

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
Log was disabled.
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed May 13 08:02:05 2020`
**Version**: `20.5.7`
**Build date**: `May 11 2020`
**Build number**: `5654`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\ZZZZZ\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\[XXXX]\Dropbox\Tools Pack\Apps\Writing-Editing\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1680x1050`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `12`
**Calendar items**: `0`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\ZZZZZ\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `C:\[XXXX]\Dropbox\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\[XXXX]\Dropbox\Notes\notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

### Script `Journal entry`

**id**: `1`
**path**: `C:\Users\ZZZZZ\AppData\Roaming\PBE\QOwnNotes\scripts\journal-entry\journal-entry.qml`
**variablesJson**: 
```
{
    "defaultFolder": "journal",
    "defaultTags": "journal",
    "noteBodyTemplate": "",
    "singleJournalPerDay": true
}
```
**identifier**: `journal-entry`
**version**: `1.4.0`
**minAppVersion**: `17.11.6`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/editorWidthMode** (int): `3`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `C:/Users/ZZZZZ/Desktop`
**FileDialog/LastPath-ImportTextFiles** (QString): `C:/Users/ZZZZZ/Documents/Notes`
**FileDialog/LastPath-NoteHTMLExport** (QString): `C:/Users/ZZZZZ/Desktop`
**FileDialog/LastPath-PreviewHTMLFileExport** (QString): `C:/Users/ZZZZZ/Desktop`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-05-13T07:39:41.692`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `20`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,8,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.1,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/move-notes** (int): `16384`
**MessageBoxOverride/remove-notes** (int): `16384`
**MessageBoxOverride/remove-tags** (int): `16384`
**MessageBoxOverride/tag-notes** (int): `16384`
**MessageBoxOverride/update-and-restart** (int): `16384`
**NoteFolder-1/NoteTabNameList** (QStringList): `Wallet Crypto recuperacion 2020-05-12T21.17.46, Doom Eternal Review - 2020-05-13 749 AM, Trend y zona neutral - 2020-05-07 1014 PM, Validación de identidad y Contratos online - 2020-05-07T10.02.49`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `, , , `
**NoteHistory-1** (QVariantList): `<variant list with 51 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `50`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-customAction_journalEntry** (QString): `Ctrl+Shift+J`
**Shortcuts/MainWindow-customAction_journalEntryTomorrow** (QString): *empty*
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TagAddDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `false`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (int): `13`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `1`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `C:/[XXXX]/Dropbox/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**recentNoteFolders** (QStringList): `C:/Users/ZZZZZ/Nextcloud/Notes`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2020-05-12T21.17.46, Note 2020-05-12T20.30.07, Note 2020-05-07T22.12.07, Note 2020-05-07T14.10.26, Note 2020-05-07T10.02.49, Note 2020-05-04T11.26.57, Note 2020-04-28T10.19.49, Note 2020-04-27T14.15.32, Note 2020-04-27T10.13.30, Note 2020-04-24T14.23.48, Note 2020-04-24T12.47.26, Note 2020-04-24T12.09.18, Note 2020-04-24T12.08.44, Note 2f780164-e164-48ae-bce3-4459f0b74438, Note fb5db409-d35f-4034-bc14-7c21db5e09a0, Note d8e2be02-7d9f-49d8-a5c0-8ddfab407d82, Welcome to QOwnNotes 2020-04-23T11.03.29, Markdown Cheatsheet 2020-04-23T11.03.29, comments, Note 2020-04-23T10.20.18`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**ANDROID_HOME**: `C:\web\android-sdk`
**APPDATA**: `C:\Users\ZZZZZ\AppData\Roaming`
**backup_path**: `D:\Backups`
**ChocolateyInstall**: `C:\ProgramData\chocolatey`
**ChocolateyLastPathUpdate**: `Tue Mar  6 08:49:40 2018`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `XXXXX`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**dropbox**: `C:\[XXXX]\Dropbox`
**ENV**: `local`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\ZZZZZ`
**LOCALAPPDATA**: `C:\Users\ZZZZZ\AppData\Local`
**LOGONSERVER**: `\\XXXXX`
**NUMBER_OF_PROCESSORS**: `4`
**OneDrive**: `C:\Users\ZZZZZ\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\WinSCP\;C:\Program Files (x86)\WinMerge;C:\ProgramData\ComposerSetup\bin;C:\Users\ZZZZZ\cygwin64\bin;C:\Program Files\mingw-w64\x86_64-6.1.0-posix-seh-rt_v5-rev0\mingw64\bin;C:\Program Files\OpenVPN\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\web\php;C:\Users\ZZZZZ\AppData\Roaming\npm;C:\Users\ZZZZZ\AppData\Roaming\npm\npm;C:\web\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk1.8.0_144\bin;;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\TortoiseGit\bin;C:\HashiCorp\Vagrant\bin;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\ZZZZZ\AppData\Local\atom\bin;C:\Users\ZZZZZ\AppData\Roaming\Composer\vendor\bin;C:\Users\ZZZZZ\AppData\Local\Microsoft\WindowsApps;C:\Users\ZZZZZ\AppData\Local\Pandoc\;C:\Users\ZZZZZ\AppData\Local\Programs\Microsoft VS Code\bin`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 60 Stepping 3, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `3c03`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PROMPT**: `$P$G`
**PSModulePath**: `%ProgramFiles%\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\ZZZZZ\AppData\Local\Temp`
**TMP**: `C:\Users\ZZZZZ\AppData\Local\Temp`
**USERDOMAIN**: `XXXXX`
**USERDOMAIN_ROAMINGPROFILE**: `XXXXX`
**USERNAME**: `XXXXX`
**USERPROFILE**: `C:\Users\ZZZZZ`
**VBOX_MSI_INSTALL_PATH**: `C:\Program Files\Oracle\VirtualBox\`
**windir**: `C:\WINDOWS`
</details>

**Comment by pbek** [comment]
If the name of a note changes it will be written into a new file.

**Comment by pbek** [comment]
If you don't want the headline of the note changing the file name you can turn that off.

**Comment by pbek** [comment]
I just checked, the file is renamed in `Note::renameNoteFile`.

> Creation date is updated to "now" on file

Are you talking about the creation date or modified date?

**Comment by heroselohim** [comment]
Thought that renaming a file should only change the modified date, but the creation date is altered too. Could it be that dropbox is altering the dates?

**Comment by heroselohim** [comment]
> It's not a file rename. If the name of a note changes it will be written into a new file.

It would be fine if that's the expected behavior. It feels rare that renaming a note is considered as creating a new note on the date attributes.

Today I needed to know the creation date of a renamed note and I couldn't. Anyway it's not that important to fix this issue.

**Comment by pbek** [comment]
I was wrong, the note file is actually only renamed if the note files is renamed in the note list.

In `Note::storeNoteTextFileToDisk()` a new file is stored like I initially though. It would have too many side-effects if I try to change that, so I'll leave it as it is.

**Comment by pbek** [comment]
I felt lucky today... I hope I fixed all side effects... :grin: 

## 20.5.9
- the note files are now actually renamed if the headline of a note changes instead
  of a new note file being created

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by heroselohim** [comment]
Problem seems to persist 🤔

When saving the file only modified date is changed.

When changing the title, it changes the name of the file. Still the creation date changes and modified date too.

Testing on QOwnNotes - version 20.5.9 - AppVeyor - build 5663

**Comment by pbek** [comment]
On Linux and macOS the creation date wasn't touched for me then the file was renamed due to the headline change.

**Comment by pbek** [comment]
And is there any useful log output when you change the headline if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting `Debug` in `Options`).

**Comment by heroselohim** [comment]
Ok, I did this:
1. Deleted the log file.
2. Renamed the title of the note.
3. Saved.

Here is the log:

```
[May 15 10:04:13] [debug]: Set proxy configuration to use NO proxy
[May 15 10:04:18] [scripting]: loading script file: C:/Users/testa/AppData/Roaming/PBE/QOwnNotes/scripts/journal-entry/journal-entry.qml
[May 15 10:04:18] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[May 15 10:04:18] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
[May 15 10:04:18] [debug]: buildNotesIndex  - 'noteSubFolderId':  0
[May 15 10:04:18] [debug]: setupNoteFolderTables  - 'database version':  14
[May 15 10:04:18] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
[May 15 10:04:18] [debug]: loadNoteDirectoryList
[May 15 10:04:18] [debug]: reloadTagTree
[May 15 10:04:18] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(1)
[May 15 10:04:18] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(1)
[May 15 10:04:18] [debug]: reloadNoteSubFolderTree
[May 15 10:04:18] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(1)
[May 15 10:04:18] [debug]: reloadNoteSubFolderTree
[May 15 10:04:18] [debug]: reloadTagTree
[May 15 10:04:18] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(1)
[May 15 10:04:18] [debug]: loadNoteDirectoryList
[May 15 10:04:18] [debug]: reloadTagTree
[May 15 10:04:18] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(1)
[May 15 10:04:18] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(1)
[May 15 10:04:18] [debug]: reloadNoteSubFolderTree
[May 15 10:04:18] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(1)
[May 15 10:04:25] [debug]: handleNoteTextFileName  - 'name' was changed:  "Jueves as 2020-05-14T09.10.25"
[May 15 10:04:25] [debug]: storeNoteTextFileToDisk  - 'noteFileWasRenamed':  true
[May 15 10:04:25] [debug]: storing note file:  "Jueves as 2020-05-14T09.10.25.md"
[May 15 10:04:25] [debug]: stored note:  Note: <id>8 <name>"Jueves as 2020-05-14T09.10.25" <fileName>"Jueves as 2020-05-14T09.10.25.md" <noteSubFolderId>1 <relativePath>"Journal" <hasDirtyData>false
[May 15 10:04:25] [debug]: storeUpdatedNotesToDisk  - 'count':  1
[May 15 10:04:25] [status]: Stored 1 note(s) to disk
[May 15 10:04:25] [debug]: loadNoteDirectoryList
[May 15 10:04:25] [debug]: reloadTagTree
[May 15 10:04:25] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(1)
[May 15 10:04:25] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(1)
[May 15 10:04:25] [debug]: reloadNoteSubFolderTree
[May 15 10:04:25] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(1)

```

**Comment by pbek** [comment]
> [May 15 10:04:25] [debug]: storeNoteTextFileToDisk  - 'noteFileWasRenamed':  true

It seems the note was renamed successfully. I was hoping that wasn't the case.
I don't know what is causing the updating of the creation date on Windows, it seems to work fine on Linux and macOS.

**Comment by heroselohim** [comment]
Thanks for your time! I think it's not that important. Keep up the good work. Love this tool ✌

**Comment by pbek** [comment]
Thank you! At least the files are now renamed. Sync clients will like that more. 😁

**Comment by pbek** [comment]
I found something strange. We check if a file would be writable by trying it to create and removing it afterwards in: https://github.com/pbek/QOwnNotes/blob/d748f86a992c430aad26763b8db33a24ac375738/src/entities/note.cpp#L1493-L1513

Under Windows this seems to cause the later rename also update the the created date.

**Comment by heroselohim** [comment]
I was thinking a workaround like grab the creation date first, then do the renaming, and setting the creation date again after the file was written. But that would be just a hack to the code...

Glad you found the real problem 👏

**Comment by pbek** [comment]
Do you know a way of setting the creation date (in Qt/C++)? I don't. 😬

**Comment by pbek** [comment]
Thank you, I'll look at that.

**Comment by pbek** [comment]
Now I know why I love Qt, that Windows API is horrible...

**Comment by pbek** [comment]
## 20.6.8
- the creation date is now restored when a note gets renamed under Windows

**Comment by pbek** [comment]
That was a horrible piece of code I had to write and it took two hours to piece everything together until it seemed to work. :grimacing:

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by heroselohim** [comment]
Yes, I know the feel of the API, but I am not programming in C / C ++ for a long time.

Tested. The fix works as charm 😁 !!

**Comment by pbek** [comment]
Finally, thank you for testing! :grin:
