### ISSUE TITLE
Remove binary translation files from repository

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1744]
I'm attempting to remove the binary translation files from the repository and build them in all build systems.

**Comment by pbek** [comment]
## 20.5.8
- the binary translation files were removed from the git repository, they are now
  built in all build systems

There now is a new release, could please everyone that sees this test it and report if it works for you in different languages? :grin:

**Comment by tim77** [comment]
It works fine, but now i need to manually invoke `lrelease` during build process. Maybe we can improve this and handle by qmake macros?

- OS: `Fedora`
- Package type: `from official repo`

**Comment by tim77** [comment]
Also now i got warning in terminal output when running app:

```
Warning: Missing trigrams for languages: QSet("en_BS", "en_TT", "ru_UA", "en_JM", "en_ZM", "en_GH", "en_ZW", "en_IE", "en_DK", "en_SG", "en_MW", "en_CA", "en_PH", "en_BZ", "en_IN", "en_NZ", "en_NA", "en_AG", "en_ZA", "en_BW", "en_HK", "en_NG", "en_AU") ((null):0, (null))
```

**Comment by pbek** [comment]
> Warning: Missing trigrams for languages: QSet("en_BS", "en_TT", "ru_UA", "en_JM", "en_ZM", "en_GH", "en_ZW", "en_IE", "en_DK", "en_SG", "en_MW", "en_CA", "en_PH", "en_BZ", "en_IN", "en_NZ", "en_NA", "en_AG", "en_ZA", "en_BW", "en_HK", "en_NG", "en_AU") ((null):0, (null))

@Waqar144, is that something to get around?

**Comment by pbek** [comment]
> It works fine, but now i need to manually invoke lrelease during build process. Maybe we can improve this and handle by qmake macros?

@tim77 if you have something in mind please make a pull request.
You can also use the source packages from https://download.tuxfamily.org/qownnotes/src/ to build qownnotes, they have the binary translation files included.

**Comment by tim77** [comment]
Oh, nice to know that there is exist such sources with prebuilt, thanks for the link. It is safe to use this sources? I mean you control them and they are not 3rd-party? But i try to tinker more and maybe can help with PR. Would be really nice if they are built from sources for sure.

**Comment by pbek** [comment]
Yes, I build those source packages with https://github.com/pbek/QOwnNotes/blob/develop/build-systems/tuxfamily/build-tuxfamily-src.sh. I used tuxfamily because it is free and more reliable than sourceforge :grin: I use those packages for most of the other builds like https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=qownnotes.

**Comment by Waqar144** [comment]
> > Warning: Missing trigrams for languages: QSet("en_BS", "en_TT", "ru_UA", "en_JM", "en_ZM", "en_GH", "en_ZW", "en_IE", "en_DK", "en_SG", "en_MW", "en_CA", "en_PH", "en_BZ", "en_IN", "en_NZ", "en_NA", "en_AG", "en_ZA", "en_BW", "en_HK", "en_NG", "en_AU") ((null):0, (null))
> 
> @Waqar144, is that something to get around?

We can disable the warning I guess.

**Comment by pbek** [comment]
> We can disable the warning I guess.

Waiting for a PR... :grin:   I guess there can be removed more code in `GuessLanguagePrivate::loadModels()`

**Comment by Waqar144** [comment]
> Also now i got warning in terminal output when running app:
> 
> ```
> Warning: Missing trigrams for languages: QSet("en_BS", "en_TT", "ru_UA", "en_JM", "en_ZM", "en_GH", "en_ZW", "en_IE", "en_DK", "en_SG", "en_MW", "en_CA", "en_PH", "en_BZ", "en_IN", "en_NZ", "en_NA", "en_AG", "en_ZA", "en_BW", "en_HK", "en_NG", "en_AU") ((null):0, (null))
> ```

The warnings should have been there even before this. So I am curious as to what triggered this behaviour @tim77
