### ISSUE TITLE
[Suggestion] Script detachedProcess result

### ISSUE THREAD

**Issue by r00tr4v3n** [pbek/QOwnNotes#1746]
Scripts like the uml-renderer are great but unusable at the moment because the ui freezes for multiple seconds if you generate more than one image. (I had multiple graphs in one file and QON froze for a minute upon starting.) Caching like in the latex-math script helps but isn't good enough. The same goes for a refresh button which would just freeze as well.
The shortest solution might be a [workerscript](https://doc.qt.io/qt-5/qml-qtqml-workerscript-workerscript.html#sendMessage-method) but I was not able to get it to run with QON.

I'd like to add a script thread with a callback hook like for context menus to allow async/detached processes with results.
e. g. 
```cpp
startDetachedProcess(QString executablePath, QStringList parameters, QString callBackIdentifier);
    ………
    function onCallback(identifier, resultSet) {
       if(identifier == "genImages"){
           script.regenerateNotePreview();
       }
    }
```

**Comment by pbek** [comment]
What will be started detached? An external command? Or a function from a qml? Who starts the thread? Can you please make an example of the flow.

**Comment by r00tr4v3n** [comment]
I don't think a qml script itself would create a heavy load, rather external calls. Might be useful though for e. g. http fetcher/parser.

This was the entire flow on the script side.

```js
startDetachedProcess("/bin/latex", {"x^2", "/tmp/out.png"}, "callback-latex");
```
```cpp
// Qt
// instead of starting the process detached, create a new thread 
// and start it synchronously to retrieve the result
callCallbackInvokedForObject(scriptComponent.object, identifier);
```

```js
    function onCallback(identifier, resultSet) {
       if(identifier == "callback-latex"){
           script.regenerateNotePreview();
       }
    }
```

**Comment by pbek** [comment]
So you want that `startDetachedProcess` uses `Utils::Misc::startSynchronousProcess` in a new thread and return the output to the scripting engine via `callBackIdentifier` if `callBackIdentifier` is set?

How would that callback with `callBackIdentifier` know which process ended if multiple of with the same `callBackIdentifier` were started? I think the pid wouldn't be very useful...

**Comment by r00tr4v3n** [comment]
> So you want that `startDetachedProcess` uses `Utils::Misc::startSynchronousProcess` in a new thread and return the output to the scripting engine via `callBackIdentifier` if `callBackIdentifier` is set?

Yes.

> How would that callback with `callBackIdentifier` know which process ended if multiple of with the same `callBackIdentifier` were started? I think the pid wouldn't be very useful... Maybe also return the command and parameters...

That should be the scripter's problem? Either by the use different `callBackIdentifier`s or another `index` value for loops and such.
```js
startDetachedProcess(QString executablePath, QStringList parameters, QString callBackIdentifier, int index = 0);
…
function onCallback(identifier, index, resultSet) 
```

**Comment by r00tr4v3n** [comment]
```cpp
    /**
     * QML wrapper to start a detached process
     *
     * @param executablePath the path of the executable
     * @param parameters a list of parameter strings
     * @param identifier an id to be used in the onCallback() function (optional)
     * @param index a useful index for loops or the like (optional)
     * @return true on success, false otherwise
     */
    bool startDetachedProcess(QString executablePath, QStringList parameters, QString identifier, int index);
```

```js
    /**
     * This function is called when a script thread is done executing.
     * Hint: thread[1]==0 helps to determine if a bulk of started processes for a certain identifier is done.
     *
     * @param {QString} identifier - the provided id when calling startDetachedProcess()
     * @param {QString} resultSet - the result of the process
     * @param {QVariantList} cmd - the entire command array [0-executablePath, 1-parameters, 2-exitCode]
     * @param {QVariantList} thread - the thread information array [0-passed index, 1-remaining threads for this identifier]
     */
    function onCallback(identifier, resultSet, cmd, thread);
```

**Comment by pbek** [comment]
I had to put a little more work into it, but now it seems ok.
@Waqar144, any last thoughts on the forward declaration of `TerminalCmd`?

## 20.5.11
- the scripting command `startDetachedProcess` now has new parameters to define
  a callback identifier that can later be implemented via the new scripting hook
  `onDetachedProcessCallback` to be able to handle the output of a detached process
  in a script (for [#1746](https://github.com/pbek/QOwnNotes/issues/1746), thank you @r00tr4v3n)
    - please take a look at the documentation for [startDetachedProcess](https://docs.qownnotes.org/en/latest/scripting/methods-and-objects/#starting-an-external-program-in-the-background) and [onDetachedProcessCallback](https://docs.qownnotes.org/en/latest/scripting/hooks/#ondetachedprocesscallback) for more information

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by r00tr4v3n** [comment]
Works great!

**Comment by Waqar144** [comment]
> I had to put a little more work into it, but now it seems ok.
> @Waqar144, any last thoughts on the forward declaration of `TerminalCmd`?

Great. Let's get this going and we'll learn along the way!

**Comment by macsunmood** [comment]
@r00tr4v3n hi!
Have you tested the `resultSet` parameter?
I haven't been able to make it work yet, it returns an empty str.

**Comment by r00tr4v3n** [comment]
Sorry, I cannot test the method. Does it work in one of the script for you? Try adjusting it from there. What python command? Sounds like it returns the result to stdout instead of the calling method?

**Comment by Waqar144** [comment]
Looking at this after such a long time, I think this can be redone in a much better, without even needing threads or identifiers. Asynchrony is built into qprocess

**Comment by macsunmood** [comment]
> Sorry, I cannot test the method. Does it work in one of the script for you? Try adjusting it from there. What python command? Sounds like it returns the result to stdout instead of the calling method?

Python script simply makes a print, which is seen in the terminal (I guess, it's stdout).
Is 'resultSet' supposed to intercept the print output (what @pbek told me), or is this approach wrong?

**Comment by macsunmood** [comment]
@Waqar144 hi 👋🏻
How would you perform retrieving the python script `print()` output with `onDetachedProcessCallback()` ? Any advice?

**Comment by Waqar144** [comment]
@macsunmood can you post a min reproducible QOwnNotes script and python script? Maybe the issue is in the script

**Comment by macsunmood** [comment]
> @macsunmood can you post a min reproducible QOwnNotes script and python script? Maybe the issue is in the script

Thanks, I've managed to figure it out, the problem indeed was with the Script, i.e. a confusion with process running source directories.
Adding the use of `property string scriptDirPath` template resolved it.
