### ISSUE TITLE
Manjaro ARM aarch64 support

### ISSUE THREAD

**Issue by sunjam** [pbek/QOwnNotes#1747]
I'd like to install this on [Manjaro ARM](https://forum.manjaro.org/), which is the default operating system for the Pinebook Pro laptop.  Curious on it being accessible from the [AUR](https://aur.archlinux.org).

**Comment by pbek** [comment]
I just tried to add build targets for ARM to the Arch Build on the Open Build Service, but unfortunately that wasn't supported, but you should be able to build it yourself from the AUR.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=qownnotes#n8
