### ISSUE TITLE
Pane size switches to minimal when number of pane changes

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#175]
It goes like this:
1. Start with >2 panes;
2. Switch any pane off;
3. Change any pane size, if you don't the bug won't show up;
4. Switch back the pane, it will have minimal size.

**Comment by pbek** [comment]
Well, if you resize the panes the new sizes get stored... If you then add an other pane the layout manager decides what to do... That's no bug, that's a behaviour...

**Comment by Maboroshy** [comment]
It maybe is not a code logic bug but a usage logic one. When a user switches pane he/she expects it same size like few minutes before, without extra action to adjust the size each time. I suggest to consider storing individual sizes for 2-, 3-, 4-pane modes so that extra action would rarely be needed.

**Comment by Maboroshy** [comment]
Maybe individual sizes for 2-, 3-, 4-pane is not great idea since we don't rally need the tag pane same size as editor pane when they "exchanged".

**Comment by pbek** [comment]
Maybe individual sizes for all possible combinations of panes... I don't know...

**Comment by pbek** [comment]
On the other hand, in what practical scenario is this happening anyway more than once...

**Comment by Maboroshy** [comment]
When I'm in 3-pane and turn off say editor pane to view some notes, list and render panes relatively extend. But I don't need extended list pane, I've turned odd editor to have bigger render pane, so I change the size to make list smaller. Guess what happens when I want edit a note after that...
Maybe the solution can be having tag and list pane sizes absolute instead of relative and editor and render relatively sharing space that left.

**Comment by pbek** [comment]
We can't have any pane sized absolute. Note name widths and tag name widths can vary...

**Comment by Maboroshy** [comment]
By absolute I don't mean not changeable. 

I mean that that it's size will be store in pixels instead of screen %, so when user will switch off say editor, tags and list will still be the width user set them, and render will eat all new space. When tag is switched off, list still the same, render eat even more space. But when user switch editor back app will remember that editor/render were 60/40 and layout the space left after subtracting list pane accordingly.

**Comment by pbek** [comment]
So you propose to write a new layout manager for Qt apps. Any volunteers? :)

**Comment by Maboroshy** [comment]
Don't know anything about layout Qt classes but Dolphin file manager being also Qt app manages it's panes the way I described. I have places pane left and information pane right. Toggling any of them extends file browser without extending other panes. This panes always stay the size I've set them. 

On the other hand looks like Dolphin's panes are more like toolbars and QOwnNotes uses different kind of widgets for it's layout. Changing widget types is a hell of a job for sure. 

Seems like "won't fix".

**Comment by pbek** [comment]
Hm, splitting the file pane in Dolphin didn't always result in the same pane sizes for me...

**Comment by Maboroshy** [comment]
That's true. Splitting use different logic, but the places and info panes are always the same. They change only when whole window size change.

**Comment by pbek** [comment]
to ease your pain a bit:

In 16.05.18
- the pane sizes in the main window are now saved and restored for all 
  combinations of tag pane, edit pane, markdown pane and vertical mode 
  toggling possibilities to assure a better pane sizes experience when 
  toggling different panes
  (for [Issue #175](https://github.com/pbek/QOwnNotes/issues/175))

Please tell me how it worked out for you...

**Comment by Maboroshy** [comment]
All works great except for tags pane. It now sets to minimal even after some other pane toggle.

**Comment by Maboroshy** [comment]
Forget what I've wrote. Seems tags width simply wasn't "remembered" yet. Issue resolved!

**Comment by pbek** [comment]
Yes, there will be a state stored for every combination, so it takes a while for QOwnNotes to "learn" all your states. :)
Great, thank you.
