### ISSUE TITLE
Add 'Jump to the note's subfolder' to note context-menu

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#1754]
Follow up from: https://github.com/pbek/QOwnNotes/issues/1432

Would it be possible to add the `Jump to the note's subfolder` option to the  context-menu (contextmenu) of the note itself?

Thanks.

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
It is already in the note list context menu (#1432, like you mentioned). Are you talking about the context menu of the note edit panel? It will not get there, it hasn't anything to do with with editing the note text.

**Comment by sanderboom** [comment]
Well, as it's impossible to place the entry under a tab-context-menu, the context-menu of the edit-panel seems the only place from the current note to navigate to the note subfolder. The note folder panel is probably showing something else and an other UI element is even less suitable(?)

Besides, it's not uncommon: Sublime Text has a similar entry in the edit-panel context-menu (and JetBrains IDE's use a shortcut to jump to the current file's directory). 

Actually jumping to the subfolder and highlighting the current note in the note list panel would be even better. So when one uses subfolders and/or has a long list of notes, context is always easily available.

**Comment by pbek** [comment]
Why don't you just write a script with a custom action that shows up in the note edit context menu and use https://docs.qownnotes.org/en/latest/scripting/methods-and-objects/#jumping-to-a-note-subfolder to jump to the sub-folder.

**Comment by pbek** [comment]
> highlighting the current note in the note list panel

isn't it highlighted already? the current note is selected in the note list

**Comment by sanderboom** [comment]
> Why don't you just write a script with a custom action that shows up in the note edit context menu and use https://docs.qownnotes.org/en/latest/scripting/methods-and-objects/#jumping-to-a-note-subfolder to jump to the sub-folder.

That's my next step! But that limits the no of people that will benefit from it. If you don't think it's something that belongs to the main application, a script is still good of course for my situation :wink: 

> isn't it highlighted already? the current note is selected in the note list

True, but it only works if the subfolder for the current note is already active (only the note list panel navigates, not the subfolder panel).

It's all about getting the context back for a note that is accessed via a tab (synchronize the UI as if you would just have created the note: subfolder panel, note list panel).

**Comment by pbek** [comment]
> if you don't think it's something that belongs to the main application

that menu is already far too cluttered :grimacing: 

> True, but it only works if the subfolder for the current note is already active (only the note list panel navigates, not the subfolder panel).
> It's all about getting the context back for a note that is accessed via a tab (synchronize the UI as if you would just have created the note: subfolder panel, note list panel).

You are talking about if you click on a tab whose note is not shown in the note list (for whatever reason, there can be many)? How do you want to highlight the note in the note list if the note isn't shown?

**Comment by sanderboom** [comment]
>  If you can magic up a note tab context menu I will implement it there.

I agree the best place would be context-menu on note tab!

Qt UI element development is not one of the (many) magic powers I have :grimacing: You said it's not even possible to catch a right click on the element? 

> You are talking about if you click on a tab whose note is not shown in the note list (for whatever reason, there can be many)? How do you want to highlight the note in the note list if the note isn't show

Maybe this makes things clear:

- Journal note for today is open. Subfolder panel shows `Journal`, Note list panel shows `Journal 20200519` highligted
- Now I have an other tab open with a note in a different folder (e.g. the note: `QON Wishlist 2020` :wink: which is in the subfolder `QON`)
- I click the tab, now the UI changes to the context for this note (for me: preview panel, tags panel, navigation panel). The only parts of the UI that do not follow are: subfolder panel, note list panel. This is not a problem - I can work with the note. 
- Now I want to see what I wrote in the note `QON Wishlist 2019` note, that is in the `QON` subfolder next to the note I am currently viewing. Actually I want the subfolder panel and the note list panel to change to the context according to the note I am working on.

I can't right click on the note in the note list panel (because this is still showing the contents of my Journal subfolder). The `Jump to note subfolder` entry (on the tab, or if not possible on the note context menu) would be convenient here. It would set the subfolder panel to the subfolder for the note, and the note list panel to highlight the current note.

**Comment by pbek** [comment]
## 20.5.11
- if the tab of current note was clicked now the subfolder of the note is
  activated if that is needed to show the note in the note list

**Comment by sanderboom** [comment]
:heart_eyes:

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
I guess you already tested it. :grin:

**Comment by sanderboom** [comment]
Actually, more often than not, it does not work unfortunately. I haven't found a pattern when it succeeds/fails. I'll try to debug a bit.
