### ISSUE TITLE
Option to strip trailing spaces on save

### ISSUE THREAD

**Issue by RealOrangeOne** [pbek/QOwnNotes#1759]
#### Expected behaviour

When saving a file, add the ability to strip trailing spaces on lines, whether they have content or not

#### Actual behaviour

Spaces are left in, leading to annoying looking indenting artifacts

![image](https://user-images.githubusercontent.com/6527489/82357502-22edb200-99fd-11ea-8349-929221ba002a.png)

**Comment by pbek** [comment]
Thank you for your suggestion.

If you want to remove the highlighting of trailing spaces you can do that in the *Editor fonts & colors* settings.

**Comment by Waqar144** [comment]
Save interval is almost one second or a few seconds. It would be really annoying to see the spaces disappear after a few seonds just because you didn't type in anything intentionally.

**Comment by pbek** [comment]
> It would be really annoying to see the spaces disappear after a few seonds just because you didn't type in anything intentionally.

Ah, true. I guess that wouldn't be great. 😆

**Comment by pbek** [comment]
I'll close this until there is a better idea.

**Comment by pbek** [comment]
Btw. you could also write a script (custom action) that could remove the trailing spaces.

**Comment by bendem** [comment]
> It would be really annoying to see the spaces disappear after a few seonds just because you didn't type in anything intentionally.

Generally editors work around that by not stripping spaces on the current line.

**Comment by pbek** [comment]
> Generally editors work around that by not stripping spaces on the current line.

That would be an idea. But there is another problem, more than 1 spaces at the end of a line are signaling a line break in markdown. They also would be removed. And just to remove up to one trailing space wouldn't be confusing... How is that handled by other markdown editors?

**Comment by bendem** [comment]
> But there is another problem, more than 1 spaces at the end of a line are signaling a line break in markdown.

I have actually never heard about that feature before. I'm guessing they don't handle it at all. Users who use that probably turn off space stripping.

**Comment by pbek** [comment]
> I have actually never heard about that feature before.

It's the only way to force a line-break (like with normal text) if you don't want to use a new paragraph.

**Comment by pbek** [comment]
It was quite some work to implement that without (hopefully) breaking (too much) things.

## 20.5.11
- you can now enable a checkbox in the *Editor settings* to automatically remove
  trailing spaces from the current note text when the note is stored to disk
    - you will only see the changes once the note edit panel is refreshed to
      prevent cursor jumping while you are editing the note

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by esterabanty** [comment]
Hi

I have this issue still regardless of auto removing trailing whitespace or changing the trailing space color scheme.

I also tried tabs instead of spaces option  in the editor settings. That did not help either.


Here is a video showing the issue.


https://user-images.githubusercontent.com/86739958/124015573-72e1cb00-d9aa-11eb-86da-1e67abe79001.mp4


I am using `QOwnNotes - version 21.6.7 - GitHub Actions - build 846` (both on Windows and Linux)

**Comment by pbek** [comment]
Thank you for reporting. I'll see if I can improve that, it's a very tricky feature.

**Comment by pbek** [comment]
> I have this issue still regardless of auto removing trailing whitespace

@esterabanty, the whitespaces are removed when the note is actually stored to disk and you will not see the changes in real-time (that is not possible). You should see the changes when you switch to another note and back to current note. Does that work for you?

**Comment by esterabanty** [comment]
Hi

In that case this seems to work only if the line is fully empty (only spaces or tabs on that line) but the other kind of blocks are still visible. This seems to be a theming bug maybe then given I already set the trailing space color to be the exact same color as the background color ?


https://user-images.githubusercontent.com/86739958/124154312-fce96c80-da5a-11eb-9135-97b87f0dc41e.mp4

**Comment by pbek** [comment]
You don't have any trailing spaces in your video, only leading spaces. We are only talking about trailing spaces (spaces after something)!

Leading spaces are not removed nor can they be hidden.

**Comment by pbek** [comment]
Trailing spaces can be hidden by setting now background and foreground for them:

![image](https://user-images.githubusercontent.com/1798101/124175109-7a3dcd00-daad-11eb-9f14-d878c7fbdadc.png)

Leading spaces are marking a codeblock in markdown.
(As are trailing spaces marking a line-break.)

**Comment by esterabanty** [comment]
Thanks for clarifying, now it makes sense.

Now that you mentioned the code block from tabs, I changed the codeblock bg color to regular bg color and I do not see the blocks anymore. They are there still obviously but they are not being visually obnoxious.

thanks

**Comment by pbek** [comment]
Yes, that's a good solution to achieve what you wanted. 😉
