### ISSUE TITLE
List checkboxes do not replace bullet sign

### ISSUE THREAD

**Issue by r00tr4v3n** [pbek/QOwnNotes#1761]
A list with checkboxes keeps an additional bullet sign.

#### Expected behaviour
- [x] task

#### Actual behaviour
- - [x] task

#### Suggestion
`style="list-style-type:none;` in the `<ul>` tag should do the trick if there is a way to detect task lists beforehand.
~Unfortunately adding the style in the `<li>` tag destroys the checkbox link/href.~

**Comment by pbek** [comment]
> `style="list-style-type:none;` in the `<ul>` tag should do the trick if there is a way to detect task lists beforehand.

you can mix normal list items with "todo-list" items

**Comment by r00tr4v3n** [comment]
OK, so the `<li>` tag should be the way  to go? Turns out I missed a `"`...

**Comment by pbek** [comment]
Very tricky

**Comment by pbek** [comment]
I rewrote the parts of the todo-list parser to do the extra styling... But I wasn't able to get the indent right so far when normal list items, checked checkboxes and unchecked checkboxes are mixed. It just looks a bit ugly.

![image](https://user-images.githubusercontent.com/1798101/82496853-aa1a5300-9aed-11ea-8121-25488ff84787.png)

```
- [ ] test
    - normal text
    - [ ] test
    - [x] test
        - [ ] test
    - normal text

- [] asasddasd
- [ ] asdas
```

Mainly also because the checked and unchecked checkboxes may have different sizes.

**Comment by r00tr4v3n** [comment]
> Very tricky

As cosmetic improvements usually are :smile: 

> Mainly also because the checked and unchecked checkboxes may have different sizes.

How about same-size checkbox images as bullets instead of invisible bullets and the unicode character? [fiddle](http://jsfiddle.net/cxoahgn4/)

**Comment by pbek** [comment]
1) I wasn't able to use css classes on the `li` because they affected the sub-list items too in the preview 😬  I needed to add a `style` attribute to every `li` with a checkbox
2) Images would of course be a less performant in long lists
3) There would be different images needed for dark mode
4) If you want to showcase something please do it directly in the QOwnNotes preview, since the `QTextBrowser` is only able to show a subset of CSS and HTML (and is very quirky)

**Comment by pbek** [comment]
You can change the preview html code in a script, if you want to set it in C++ you can do it here: https://github.com/pbek/QOwnNotes/commit/03eb0832a2901f8efb3feedbb6a31747d41b4670#diff-f5d8efec5f27993af7e4b1d005d63648R702

**Comment by pbek** [comment]
Meanwhile... :grin: 

## 20.5.11
- todo list items now have a square as list-style

**Comment by r00tr4v3n** [comment]
Great, thank you!

> You can change the preview html code in a script (https://docs.qownnotes.org/en/latest/scripting/hooks/#notetomarkdownhtmlhook), if you want to set it in C++ you can do it here: [03eb083#diff-f5d8efec5f27993af7e4b1d005d63648R702](https://github.com/pbek/QOwnNotes/commit/03eb0832a2901f8efb3feedbb6a31747d41b4670#diff-f5d8efec5f27993af7e4b1d005d63648R702)

I'll have a closer look at those html-regex-converter lines. I was thinking about adding a way to resize/align images but it seems there is no unified standard in markdown, so it should probably stay in a script.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by r00tr4v3n** [comment]
So the difference is, the task bullet is now square?
![image](https://user-images.githubusercontent.com/6073574/82558507-1a68b900-9b6e-11ea-894f-e0abd713e066.png)

**Comment by pbek** [comment]
Exactly, now you have an entry point to start from if you want to improve on that.

**Comment by r00tr4v3n** [comment]
Of course! I could use the html hook to delete them again.

**Comment by pbek** [comment]
Yes, until you come up with a good styling solution.

**Comment by sanderboom** [comment]
Maybe take a look at: https://github.com/qownnotes/scripts/tree/master/export-checkboxes

Seems this is exactly what you are trying to archieve.

**Comment by r00tr4v3n** [comment]
Yes, `margin-left` was my conclusion as well. I'm just checking font size dependencies etc.

**Comment by r00tr4v3n** [comment]
@pbek This doesn't look right:

```
- lvl0
- lvl0
    - lvl1
    - lvl1
        - lvl2
        - lvl2
```

```
<ul>
<li>lvl0</li>
<li>lvl0<ul>
<li>lvl1</li>
<li>lvl1<ul>
<li>lvl2</li>
<li>lvl2</li>
</ul>
</li>
</ul>
</li>
</ul>
```

**Comment by pbek** [comment]
Why do you think it's wrong?
You have `ul`s inside `li`s, perfectly valid.

For me it looks like:

![image](https://user-images.githubusercontent.com/1798101/82696274-fb018700-9c66-11ea-8d40-7b39c35686ad.png)

**Comment by r00tr4v3n** [comment]
But the `</ul>` is in front of the `</li>`?

**Comment by pbek** [comment]
> But the </ul> is in front of the </li>?

To close the opened `<ul>`, that's how html works :grin: 

> Styles continue to be applied to bullet points which do not have any style added.

You have to get around that with CSS (if it ever works with QTextBrowser).

**Comment by r00tr4v3n** [comment]
OK, I thought it had to be nested like this.
```html
<ul>
  <li>Fruit
    <ul>
      <li>Bananas</li>
      <li>Apples
        <ul>
          <li>Green</li>
          <li>Red</li>
        </ul>
      </li>
      <li>Pears</li>
    </ul>
  </li>
  <li>Vegetables</li>
  <li>Meat</li>
</ul>
```

**Comment by r00tr4v3n** [comment]
Now I see:
```html
<ul>
  <li>Fruit
    <ul>
      <li>Bananas</li>
      <li>Apples
        <ul>
          <li>Green</li>
          <li>Red</li>
        </ul>
      </li>
      <li>Pears</li>
    </ul>
  </li>
  <li>Vegetables</li>
  <li>Meat</li>
</ul>
```

**Comment by r00tr4v3n** [comment]
The gab is weird though.
![image](https://user-images.githubusercontent.com/6073574/82699171-6a2daa00-9c6c-11ea-8076-25e0910270b6.png)

**Comment by pbek** [comment]
> The gab is weird though.

That's another QTextBrowser thing.

**Comment by pbek** [comment]
> Now I see it:

I also needed to look twice. 😁

**Comment by r00tr4v3n** [comment]
> That's another QTextBrowser thing.

These gabs are just not predictable...

**Comment by sanderboom** [comment]
These gaps are really annoying! Also:

<img width="272" alt="image" src="https://user-images.githubusercontent.com/5956570/82705581-2ccf1980-9c78-11ea-9d38-a8d5477559bb.png">

Other markdown apps do render the second part as a new list. This (and the constant jumping to the last image while editing) is why most of the time I keep the preview panel disabled unfortunately.

**Comment by Waqar144** [comment]
This can be fixed in QTextBrowser, its not a very big issue I think. Someday I might give it a try.

**Comment by r00tr4v3n** [comment]
Seems to work now (with gaps):

| no gap | gap |
|---|---|
| ![image](https://user-images.githubusercontent.com/6073574/82726756-82420f80-9ce6-11ea-9fa4-e34820591466.png)  | ![image](https://user-images.githubusercontent.com/6073574/82726775-9ede4780-9ce6-11ea-9c02-e9207c5e5a95.png) |

**Comment by pbek** [comment]
For me #1771 is looking like this:

![image](https://user-images.githubusercontent.com/1798101/82748109-add50080-9d9f-11ea-8861-50d45209f858.png)

```markdown
- normal
- normal
- [ ] 7 test
    - normal
    - normal
	- [ ] 1 test
		- [x] 123
		    - normal
			- [x] 456
		    - normal
		- [x] test
			- [ ] test 123
		    - normal
```

**Comment by Waqar144** [comment]
Ideally the normal checkboxes should work in QTextBrowser, but they don't so we have all these hacky solutions

**Comment by r00tr4v3n** [comment]
> For me #1771 is looking like this:

What font are you using?
> Ideally the normal checkboxes should work in QTextBrowser, but they don't so we have all these hacky solutions

Maybe [QtWebEngine](https://doc.qt.io/qt-5/qtwebengine-index.html) might be worth a look. It would also fix the low resolution. Maybe it's not too resource hungry...

**Comment by pbek** [comment]
> What font are you using?

Noto Sans 11, but every user uses their own fonts and sizes

> Maybe QtWebEngine might be worth a look. It would also fix the low resolution. Maybe it's not too resource hungry...

see #1421

**Comment by r00tr4v3n** [comment]
>    Noto Sans 11, but every user uses their own fonts and sizes

It's weird just one box is translucent, it's still just a character.
