### ISSUE TITLE
"The application 'QOwnNotes.app' can't be opened." on OSX Catalina 10.15.4

### ISSUE THREAD

**Issue by mliudev** [pbek/QOwnNotes#1762]
#### Expected behaviour

Application successfully opens.

#### Actual behaviour

Crash with a problem report which is sent to Apple.

#### Steps to reproduce

1. `brew cask install QOwnNotes`
2. Open QOwnNotes either through Spotlight command or opening the app in Finder.

#### Output from the debug section in the settings dialog

N/A since I can't access this dialog.

#### Relevant log output in the Log panel

N/A since I can't access this panel. However, I have attached a truncated version of the problem report sent to apple and a screenshot of the error.

Crash log:
[qownnotes_crash_log.txt](https://github.com/pbek/QOwnNotes/files/4658689/qownnotes_crash_log.txt)

Screenshot:

<img width="999" alt="Screen Shot 2020-05-20 at 2 33 49 PM" src="https://user-images.githubusercontent.com/11674155/82484299-ba0f4400-9aa7-11ea-9d36-365e9ddd4b9b.png">

**Comment by pbek** [comment]
I haven't ever tried the (3rd party) brew build. Can you please try the version from https://www.qownnotes.org/installation.

**Comment by pbek** [comment]
Looks like they are using the official build (see: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/qownnotes.rb). But just to make sure everything is alright please use the official dmg.

And if that alone doens't help please try to start QOwnNotes in a new session (see https://docs.qownnotes.org/en/latest/getting-started/cli-parameters/)

**Comment by mliudev** [comment]
When using the CLI:

```
QOwnNotes.app/Contents/MacOS/QOwnNotes --session new
2020-05-21 10:31:00.048 QOwnNotes[97818:3554615] -[NSTaggedPointerString count]: unrecognized selector sent to instance 0x21d806b8cd278c2f
2020-05-21 10:31:00.049 QOwnNotes[97818:3554615] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString count]: unrecognized selector sent to instance 0x21d806b8cd278c2f'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff31d73d07 __exceptionPreprocess + 250
        1   libobjc.A.dylib                     0x00007fff6a8fe5bf objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff31df2c97 -[NSObject(NSObject) __retain_OA] + 0
        3   CoreFoundation                      0x00007fff31cd857b ___forwarding___ + 1427
        4   CoreFoundation                      0x00007fff31cd7f58 _CF_forwarding_prep_0 + 120
        5   CoreFoundation                      0x00007fff31cb272a _CFLocaleCopyCurrentGuts + 791
        6   QtCore                              0x000000010bb9cb9f _ZNK13QSystemLocale5queryENS_9QueryTypeE8QVariant + 1279
        7   QtCore                              0x000000010bb542c9 _ZN7QLocaleC2Ev + 1113
        8   QtCore                              0x000000010bb53f1c _ZN7QLocaleC2Ev + 172
        9   QtCore                              0x000000010bb546ff _ZN7QLocaleC1Ev + 15
        10  QtCore                              0x000000010bc17cb1 _ZN9QResource18unregisterResourceEPKhRK7QString + 5057
        11  QtCore                              0x000000010bc16cb5 _ZN9QResource18unregisterResourceEPKhRK7QString + 965
        12  QtCore                              0x000000010bc2fa17 _ZN16QFileSystemEntry10isRootPathERK7QString + 2263
        13  QtCore                              0x000000010bc2f802 _ZN16QFileSystemEntry10isRootPathERK7QString + 1730
        14  QtCore                              0x000000010bc04317 _ZN9QFileInfo6existsERK7QString + 71
        15  QtCore                              0x000000010baec3c3 _ZN9QInternal17activateCallbacksENS_8CallbackEPPv + 2659
        16  QtCore                              0x000000010baec156 _ZN9QInternal17activateCallbacksENS_8CallbackEPPv + 2038
        17  QtCore                              0x000000010baed6ea _ZN12QLibraryInfo8locationENS_15LibraryLocationE + 3146
        18  QtCore                              0x000000010baecac7 _ZN12QLibraryInfo8locationENS_15LibraryLocationE + 39
        19  QtCore                              0x000000010bc34284 _ZN16QLoggingCategory14setFilterRulesERK7QString + 5492
        20  QtCore                              0x000000010bc33a84 _ZN16QLoggingCategory14setFilterRulesERK7QString + 3444
        21  QtCore                              0x000000010bc35f03 _ZN16QLoggingCategory14setFilterRulesERK7QString + 12787
        22  QtCore                              0x000000010bc32c49 _ZN16QLoggingCategory15defaultCategoryEv + 121
        23  QtCore                              0x000000010baf395a _Z17qt_message_output9QtMsgTypeRK18QMessageLogContextRK7QString + 106
        24  QtCore                              0x000000010baf38fd _Z17qt_message_output9QtMsgTypeRK18QMessageLogContextRK7QString + 13
        25  QtCore                              0x000000010bbf0dd1 _ZN6QDebugD2Ev + 97
        26  QOwnNotes                           0x0000000109eb1cb0 main + 2192
        27  libdyld.dylib                       0x00007fff6baa5cc9 start + 1
        28  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException
fish: 'QOwnNotes.app/Contents/MacOS/QO…' terminated by signal SIGABRT (Abort)
```

I get a similar message.

I'll try downloading the official build next.

**Comment by mliudev** [comment]
Tried downloading the official build. For some reason it took several refreshes before the link to download would populate under the macOS dropdown. Installed the DMG but I get the same error message as above. I'll try clearing my settings and seeing if that works.

**Comment by pbek** [comment]
Thank you for your help. Unfortunately only building QOwnNotes yourself and running it in debug mode comes into mind (https://www.qownnotes.org/installation#building). The exception seems pretty random.

**Comment by pbek** [comment]
Can you output a settings dump on the cli? see: https://docs.qownnotes.org/en/latest/getting-started/cli-parameters/

**Comment by mliudev** [comment]
> Can you output a settings dump on the cli? see: https://docs.qownnotes.org/en/latest/getting-started/cli-parameters/

I couldn't do this since any attempt to open the application resulted in the same crash.

However, I was able to build the version from Github and that seems to have worked. I think maybe some setting was broken and persisted through my attempts to uninstall and reinstall. I've attached an image of the self-built version.
<img width="685" alt="Screen Shot 2020-05-21 at 11 56 48 PM" src="https://user-images.githubusercontent.com/11674155/82629819-deaa0f80-9bbe-11ea-9289-5b227f4b1263.png">

I also did a `brew cask uninstall -f qownnotes` to see if I missed any files. I also did a `brew cleanup` and then a `brew cask install qownnotes` as an experiment. This also crashed as before.

I then tried to install the DMG downloaded from qownnotes.org but that also failed. It seems like these builds don't like my 2013 MBP.

**Comment by pbek** [comment]
Interesting, my Air is from 2014. You can also try fresh settings with another session, e.g. `--session test`.

**Comment by wilbowma** [comment]
I just upgraded to 10.15.7 and am experiencing this issue with the most recent QOwnNotes, and several prior versions. I'm trying to build it from source now.

**Comment by wilbowma** [comment]
Building from source works :/

**Comment by pbek** [comment]
Maybe macOS locked the app? Maybe you can unlock it (see https://www.qownnotes.org/installation/macos.html)

**Comment by wilbowma** [comment]
It did, but locking prevents the app from opening at all. This error occurs after unlocking and trying to launch the app.

**Comment by pbek** [comment]
Sounds like https://github.com/pyinstaller/pyinstaller/issues/4466, but that doesn't help a lot...
