### ISSUE TITLE
The current note was modified outside of this application!

### ISSUE THREAD

**Issue by yunesj** [pbek/QOwnNotes#1763]
I am frequently getting warned of modification to notes by external modifications. No such modifications are occurring (according to system calls related to filesystem activity, please see below). I am not using any extensions and the notes are stored on a local disk with no synchronization.

#### Expected behavior
QOwnNotes should not detect or warn me of an external modification unless there is one.

#### Actual behaviour

QOwnNotes is detecting and warning me of external modifications.

#### Steps to reproduce

Type and save note.

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed May 20 16:11:21 2020`
**Version**: `20.5.10`
**Build date**: `May 18 2020`
**Build number**: `5641`
**Platform**: `macosx`
**Operating System**: `macOS 10.15`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
**Settings path / key**: `/Users/jeff/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/jeff/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1440x900`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `8`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/Users/jeff/Library/Application Support/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-2`
**localPath**: `/Users/jeff/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `Learning & Research`
**database file**: `/Users/jeff/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**AKLastCheckInAttemptDate** (QDateTime): `2019-10-17T07:27:18.652`
**AKLastCheckInSuccessDate** (QDateTime): `2019-10-17T07:27:20.767`
**AKLastEmailListRequestDateKey** (QDateTime): `2020-05-14T20:02:39.180`
**AKLastIDMSEnvironment** (qlonglong): `0`
**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Country** (QString): `US`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (qlonglong): `4`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**InitialKeyRepeat** (qlonglong): `15`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**KeyRepeat** (qlonglong): `2`
**LastUpdateCheck** (QDateTime): `2020-05-20T15:34:23.321`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (qlonglong): `32`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `.SF NS Mono,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `.AppleSystemUIFont,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `.SF NS Mono,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `.AppleSystemUIFont,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/move-notes** (qlonglong): `16384`
**MessageBoxOverride/remove-notes** (qlonglong): `16384`
**MultipleSessionEnabled** (bool): `true`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): `Note 2020-05-20T12.32.34`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteHistory-1** (QVariantList): `<variant list with 21 item(s)>`
**NoteHistoryCurrentIndex-1** (qlonglong): `20`
**PKSecureElementAvailableFlagsByHost** (qlonglong): `3`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (qlonglong): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WebAutomaticSpellingCorrectionEnabled** (bool): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**_HIHideMenuBar** (bool): `false`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `false`
**appMetrics/disableAppHeartbeat** (bool): `true`
**appMetrics/disableTracking** (bool): `true`
**appMetrics/notificationShown** (bool): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (qlonglong): `1`
**currentWorkspace** (QString): `2HP7tKguZG3v`
**cursorWidth** (qlonglong): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (bool): `true`
**disableAutomaticUpdateDialog** (bool): `false`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (bool): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (qlonglong): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (qlonglong): `1024`
**imageScaleDownMaximumWidth** (qlonglong): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (qlonglong): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (qlonglong): `18`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (qlonglong): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (qlonglong): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (qlonglong): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (qlonglong): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (qlonglong): `0`
**notesPanelOrder** (qlonglong): `0`
**notesPanelSort** (qlonglong): `1`
**notesPath** (QString): `/Users/jeff/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (qlonglong): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (qlonglong): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `initial`
**restoreCursorPosition** (bool): `false`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**showMatches** (bool): `true`
**showMenuBar** (bool): `false`
**showStatusBar** (bool): `true`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (qlonglong): `0`
**tagsPanelSort** (qlonglong): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (qlonglong): `6`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**userMenuExtraStyle** (qlonglong): `1`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (qlonglong): `22222`
**workspace-2HP7tKguZG3v/name** (QString): `Full`
**workspace-2HP7tKguZG3v/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-2HP7tKguZG3v/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`

## System environment

**USER**: `jeff`
**PATH**: `/usr/bin:/bin:/usr/sbin:/sbin`
**LOGNAME**: `jeff`
**SSH_AUTH_SOCK**: `/private/tmp/com.apple.launchd.JOGK0hd7Py/Listeners`
**HOME**: `/Users/jeff`
**SHELL**: `/bin/zsh`
**__CF_USER_TEXT_ENCODING**: `0x1F5:0x0:0x0`
**TMPDIR**: `/var/folders/p3/kmmh53_s1r9f4pmzym6k3t_w0000gn/T/`
**XPC_SERVICE_NAME**: `com.PBE.QOwnNotes.7100`
**XPC_FLAGS**: `0x0`
**QT_LOGGING_RULES**: `qt.network.ssl.warning=false`

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

[May 20 17:00:20] [debug]: storing note file:  "Questions.md"
[May 20 17:00:20] [debug]: stored note:  Note: <id>3 <name>"Questions" <fileName>"Questions.md" <noteSubFolderId>1 <relativePath>"Learning" <hasDirtyData>false
[May 20 17:00:20] [debug]: storeUpdatedNotesToDisk  - 'count':  1
[May 20 17:00:20] [status]: Stored 1 note(s) to disk
[May 20 17:00:20] [debug]: notesWereModified:  "/Users/jeff/Notes/Learning/Questions.md"
[May 20 17:00:20] [debug]: Current note was modified externally!
[May 20 17:00:20] [status]: Current note was modified externally
[May 20 17:00:20] [debug]: openNoteDiffDialog  - 'changedNote':  Note: <id>3 <name>"Questions" <fileName>"Questions.md" <noteSubFolderId>1 <relativePath>"Learning" <hasDirtyData>true
[May 20 17:00:22] [status]: Overwriting external changes of: Questions.md
[May 20 17:00:22] [debug]: storing note file:  "Questions.md"
[May 20 17:00:25] [debug]: storing note file:  "Questions.md"
[May 20 17:00:25] [debug]: stored note:  Note: <id>3 <name>"Questions" <fileName>"Questions.md" <noteSubFolderId>1 <relativePath>"Learning" <hasDirtyData>false
[May 20 17:00:25] [debug]: storeUpdatedNotesToDisk  - 'count':  1
[May 20 17:00:25] [status]: Stored 1 note(s) to disk

</details>

#### Output from `fs_usage`

```
<details>
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000044   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000010   QOwnNotes   
17:00:20  open              /Users/jeff/Notes/Learning/Questions.md        0.000050   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000015   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000009   QOwnNotes   
17:00:20  lstat64           /Users/jeff/Notes/Learning/Questions.md        0.000055   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000079   QOwnNotes   
17:00:20  stat64            /Users/jeff/Notes/Learning/Questions.md        0.000022   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000030   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000048   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000010   QOwnNotes   
17:00:20  open              /Users/jeff/Notes/Learning/Questions.md        0.000057   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000083   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000013   QOwnNotes   
17:00:20  lstat64           /Users/jeff/Notes/Learning/Questions.md        0.000014   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000061   QOwnNotes   
17:00:20  stat64            /Users/jeff/Notes/Learning/Questions.md        0.000018   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000038   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000035   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000007   QOwnNotes   
17:00:20  open              /Users/jeff/Notes/Learning/Questions.md        0.000041   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000012   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000006   QOwnNotes   
17:00:20  lstat64           /Users/jeff/Notes/Learning/Questions.md        0.000009   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000029   QOwnNotes   
17:00:20  stat64            /Users/jeff/Notes/Learning/Questions.md        0.000007   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000020   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000032   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000008   QOwnNotes   
17:00:20  open              /Users/jeff/Notes/Learning/Questions.md        0.000036   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000015   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000007   QOwnNotes   
17:00:20  lstat64           /Users/jeff/Notes/Learning/Questions.md        0.000008   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000027   QOwnNotes   
17:00:20  stat64            /Users/jeff/Notes/Learning/Questions.md        0.000007   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000021   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000074   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000016   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000057   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000015   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000022   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000013   QOwnNotes   
17:00:20  open              /Users/jeff/Notes/Learning/Questions.md        0.000138   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000019   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000009   QOwnNotes   
17:00:20  lstat64           /Users/jeff/Notes/Learning/Questions.md        0.000012   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000030   QOwnNotes   
17:00:20  stat64            /Users/jeff/Notes/Learning/Questions.md        0.000011   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000026   QOwnNotes   
17:00:20    WrData[A]       /Users/jeff/Notes/Learning/Questions.md        0.000164 W QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000019   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000010   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000011   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000008   QOwnNotes   
17:00:20  lstat64           Data/Users/jeff/Notes/Learning/Questions.md    0.000040   fseventsd   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000030   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000010   QOwnNotes   
17:00:20  open              /Users/jeff/Notes/Learning/Questions.md        0.000036   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000012   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000006   QOwnNotes   
17:00:20  lstat64           /Users/jeff/Notes/Learning/Questions.md        0.000009   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000027   QOwnNotes   
17:00:20  stat64            /Users/jeff/Notes/Learning/Questions.md        0.000007   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000020   QOwnNotes   
17:00:20  getattrlist       Data/Users/jeff/Notes/Learning/Questions.md    0.000066   mds         
17:00:20  listxattr         Data/Users/jeff/Notes/Learning/Questions.md    0.000011   mds         
17:00:20  getattrlist       Data/Users/jeff/Notes/Learning/Questions.md    0.000088   mds         
17:00:20  open              Data/Users/jeff/Notes/Learning/Questions.md    0.000073   mdworker_sha
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000050   mds         
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000044   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000009   QOwnNotes   
17:00:20  open              /Users/jeff/Notes/Learning/Questions.md        0.000049   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000016   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000006   QOwnNotes   
17:00:20  lstat64           /Users/jeff/Notes/Learning/Questions.md        0.000009   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000026   QOwnNotes   
17:00:20  stat64            /Users/jeff/Notes/Learning/Questions.md        0.000007   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000021   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000040   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000009   QOwnNotes   
17:00:20  open              /Users/jeff/Notes/Learning/Questions.md        0.000045   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000015   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000008   QOwnNotes   
17:00:20  lstat64           /Users/jeff/Notes/Learning/Questions.md        0.000010   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000033   QOwnNotes   
17:00:20  stat64            /Users/jeff/Notes/Learning/Questions.md        0.000010   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000025   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000037   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000010   QOwnNotes   
17:00:20  open              /Users/jeff/Notes/Learning/Questions.md        0.000048   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000020   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000009   QOwnNotes   
17:00:20  lstat64           /Users/jeff/Notes/Learning/Questions.md        0.000010   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000067   QOwnNotes   
17:00:20  stat64            /Users/jeff/Notes/Learning/Questions.md        0.000019   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000038   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000035   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000008   QOwnNotes   
17:00:20  open              /Users/jeff/Notes/Learning/Questions.md        0.000040   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000017   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000007   QOwnNotes   
17:00:20  lstat64           /Users/jeff/Notes/Learning/Questions.md        0.000009   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000031   QOwnNotes   
17:00:20  stat64            /Users/jeff/Notes/Learning/Questions.md        0.000012   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000033   QOwnNotes   
17:00:20  stat64            /Users/jeff/Notes/Learning/Questions.md        0.000008   QOwnNotes   
17:00:20  stat64            /Users/jeff/Notes/Learning/Questions.md        0.000015   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000243   QOwnNotes   
17:00:20  stat64            /Users/jeff/Notes/Learning/Questions.md        0.000031   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000016   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000008   QOwnNotes   
17:00:20  lstat64           /Users/jeff/Notes/Learning/Questions.md        0.000007   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000026   QOwnNotes   
17:00:20  stat64            /Users/jeff/Notes/Learning/Questions.md        0.000010   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000026   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000009   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000006   QOwnNotes   
17:00:20  open              /Users/jeff/Notes/Learning/Questions.md        0.000027   QOwnNotes   
17:00:20  access            /Users/jeff/Notes/Learning/Questions.md        0.000012   QOwnNotes   
17:00:20  getattrlist       /Users/jeff/Notes/Learning/Questions.md        0.000007   QOwnNotes   
17:00:20  open              /Users/jeff/Notes/Learning/Questions.md        0.000024   QOwnNotes  
```
</details>

**Comment by pbek** [comment]
This can happen under macOS.

QOwnNotes shows this message if the current note was modified by an external process while you are editing the note and the new content of the note file differs from you have in your note in QOwnNotes...

I never was able to find out who it is, maybe spotlight. If you find something out please let me know.

If you don't want to see the message you can turn it off in the *General settings*.

**Comment by yunesj** [comment]
Hi @pbek  

I confirmed via monitoring system calls that no other process is modifying the note. See details in the OP.

**Comment by pbek** [comment]
Thank you for testing. I still need a way to reproduce that. :grimacing:

**Comment by pbek** [comment]
I tried for quite a while but wasn't able to make the same situation happen for me. :thinking: :grimacing: 

Do you get that less often if you reduce the `noteSaveIntervalTime` in the *General settings*?

**Comment by yunesj** [comment]
There's a difference in the note diff dialog, by a couple of characters.

> Do you get that less often if you reduce the noteSaveIntervalTime in the General settings?

Yes, less often, but still on occasion. However, I haven't been doing as much note taking as of late.
