### ISSUE TITLE
[I] Cannot move notes to subfolders

### ISSUE THREAD

**Issue by blefuscu** [pbek/QOwnNotes#1764]
#### Expected behaviour

1. note appears in the correct subfolder
2. note disappears from the original subfolder

#### Actual behaviour

1. note is copied into the target subfolder
2. note is not removed from the original folder

#### Steps to reproduce

1. select a note
2. right click to open context menu
3. Move notes to subfolder
4. select subfolder
5. left click

### Additional notes

1. moving and copying notes in shell and in file manager (Nemo) works without a problem.
2. permissions are correct on files and directories too
3. first appeared in remotely synchronised note directories, but verified also on local disk without any synchronisation

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[16:41:31] [warning] Could not move note: "Note 2020-05-21T16.39.50"
[16:41:31] [status] 0 note(s) were moved to note subfolder "subfolderr"
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Thu May 21 16:55:03 2020`
**Version**: `20.5.10`
**Build date**: `May 18 2020`
**Build number**: `718`
**Platform**: `linux`
**Operating System**: `Linux Mint 19.3`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.9.5`
**Qt Version (runtime)**: `5.9.5`
**Portable mode**: `no`
**Settings path / key**: `/home/REMOVED/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/REMOVED/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_GB`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: *empty*
**Notes in current note folder**: `4`
**Calendar items**: `84`
**Enabled scripts**: `9`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `de_AT, de_AT_frami, de_CH, de_CH_frami, de_DE, de_DE_frami, en_AU, en_CA, en_GB, en_US, en_ZA, es_AR, es_BO, es_CL, es_CO, es_CR, es_CU, es_DO, es_EC, es_ES, es_GT, es_HN, es_MX, es_NI, es_PA, es_PE, es_PR, es_PY, es_SV, es_US, es_UY, es_VE, fr, fr_BE, fr_CA, fr_CH, fr_FR, fr_LU, fr_MC, it_CH, it_IT, pt_BR, pt_PT, ru_RU, sk_SK`
**Language names**: `Österreichisches Deutsch (Österreich), Österreichisches Deutsch (Österreich), Schweizer Hochdeutsch (Schweiz), Schweizer Hochdeutsch (Schweiz), Deutsch (Deutschland), Deutsch (Deutschland), Australian English (Australia), Canadian English (Canada), British English (United Kingdom), American English (United States), English (South Africa), español (Argentina), español (Bolivia), español (Chile), español (Colombia), español (Costa Rica), español (Cuba), español (República Dominicana), español (Ecuador), español de España (España), español (Guatemala), español (Honduras), español de México (México), español (Nicaragua), español (Panamá), español (Perú), español (Puerto Rico), español (Paraguay), español (El Salvador), español (Estados Unidos), español (Uruguay), español (Venezuela), français, français (Belgique), français canadien (Canada), français suisse (Suisse), français (France), français (Luxembourg), français (Monaco), italiano (Svizzera), italiano (Italia), português do Brasil (Brasil), português europeu (Portugal), русский (Россия), slovenčina (Slovensko)`
**Application dictionaries path**: `/home/REMOVED/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `4`

### Note folder `test`

**id**: `4`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/REMOVED/tmp/test-notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/REMOVED/tmp/test-notes/notes.sqlite`

### Cloud connection ``

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Enabled scripts

<<REMOVED>>

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**AttachmentDialog/geometry** (QByteArray): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `true`
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `24`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**FileDialog/LastPath** (QString): `/home/REMOVED/Desktop`
**FileDialog/LastPath-InsertAttachment** (QString): `/home/REMOVED/Notes/life/stats`
**FileDialog/LastPath-InsertImage** (QString): `/home/REMOVED/Desktop`
**FileDialog/LastPath-NoteHTMLExport** (QString): `/home/REMOVED/Desktop`
**FileDialog/LastPath-NotePDFExport** (QString): `/home/REMOVED/Desktop`
**FileDialog/LastPath-PreviewHTMLFileExport** (QString): `/home/REMOVED`
**ImageDialog/disableCopying** (QString): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-05-21T16:54:05`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LinkDialog/lastSelectedFileUrl** (QString): `file:///home/REMOVED`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-2** (QStringList): `life`
**MainWindow/noteTextEdit.code.font** (QString): `DejaVu Sans,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `DejaVu Sans,16,-1,5,50,0,0,0,0,0,Book`
**MainWindow/noteTextView.code.font** (QString): `DejaVu Sans,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `DejaVu Sans,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/delete-files** (QString): `16384`
**MessageBoxOverride/log-file-cleared** (QString): `1024`
**MessageBoxOverride/move-notes** (QString): `16384`
**MessageBoxOverride/note-replace-links** (QString): `16384`
**MessageBoxOverride/readonly-mode-allow** (QString): `16384`
**MessageBoxOverride/remove-folders** (QString): `16384`
**MessageBoxOverride/remove-note-folder** (QString): `16384`
**MessageBoxOverride/remove-notes** (QString): `16384`
**MessageBoxOverride/remove-script** (QString): `16384`
**MessageBoxOverride/remove-workspace** (QString): `16384`
**MessageBoxOverride/restore-note** (QString): `16384`
**MessageBoxOverride/script-install-successful** (QString): `1024`
**MessageBoxOverride/settings-shortcut-already-assigned** (QString): `16384`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-2/NoteTabNameList** (QStringList): `kravinka`
**NoteFolder-2/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-2/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteFolder-2/allowDifferentNoteFileName** (bool): `false`
**NoteFolder-3/NoteTabNameList** (QString): `Morning note 2020-04-20T0859, Monday`
**NoteFolder-3/NoteTabStickinessList**: *empty*
**NoteFolder-3/NoteTabSubFolderPathDataList** (QString): `REMOVED`
**NoteFolder-4/NoteTabNameList** (QStringList): `Note 2020-05-21T16.39.50`
**NoteFolder-4/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-4/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteHistory-2** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistory-3** (QVariantList): `<variant list with 45 item(s)>`
**NoteHistory-4** (QVariantList): `<variant list with 1 item(s)>`
**NoteHistoryCurrentIndex-2** (int): `199`
**NoteHistoryCurrentIndex-3** (QString): `44`
**NoteHistoryCurrentIndex-4** (int): `0`
**OrphanedAttachmentsDialog/geometry** (QByteArray): `<binary data>`
**OrphanedImagesDialog/geometry** (QByteArray): `<binary data>`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PersistentScripting/MdNT/pyCommand** (QString): `python3`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExport** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-customAction_#+** (QKeySequence): *empty*
**Shortcuts/MainWindow-customAction_#-** (QKeySequence): *empty*
**Shortcuts/MainWindow-customAction_exportHTML** (QKeySequence): *empty*
**Shortcuts/MainWindow-customAction_externalNoteDiff** (QKeySequence): *empty*
**Shortcuts/MainWindow-customAction_fixListNumbers** (QKeySequence): *empty*
**Shortcuts/MainWindow-customAction_insertToc** (QKeySequence): *empty*
**Shortcuts/MainWindow-customAction_journalEntry** (QKeySequence): *empty*
**Shortcuts/MainWindow-customAction_journalEntryTomorrow** (QKeySequence): *empty*
**Shortcuts/MainWindow-customAction_mergeNotes** (QKeySequence): *empty*
**ShowSystemTray** (bool): `true`
**StartHidden** (bool): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `2`
**TodoDialog/todoListSelectorSelectedItem** (QString): `REMOVED (private tasks)`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (int): `4`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `2`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `true`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `true`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `true`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `true`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): `yyyy-MM-ddTHH:mm, dddd`
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (int): `19`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `0`
**notesPath** (QString): `/home/REMOVED/tmp/test-notes`
**notifyAllExternalModifications** (bool): `true`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `074e67fb-cca8-4c79-9e53-b9ddb2d8c965`
**recentNoteFolders** (QStringList): `/home/REMOVED
**restoreCursorPosition** (bool): `true`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**savedSearches/noteFolder-2** (QStringList): REMOVED
**savedSearches/noteFolder-3** (QStringList): REMOVED
**savedSearches/noteFolder-4** (QStringList): `Note 2020-05-21T16.39.50`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (bool): `true`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**webSocketServerService/token** (QString): `Kr8f87BZ`
**workspace-074e67fb-cca8-4c79-9e53-b9ddb2d8c965/name** (QString): `minimal`
**workspace-074e67fb-cca8-4c79-9e53-b9ddb2d8c965/noteSubFolderDockWidgetVisible** (QString): `false`
**workspace-074e67fb-cca8-4c79-9e53-b9ddb2d8c965/windowState** (QByteArray): `<binary data>`
**workspace-6f2d9e2d-1bbd-438e-a36c-30ac68e057d2/name** (QString): `preview`
**workspace-6f2d9e2d-1bbd-438e-a36c-30ac68e057d2/noteSubFolderDockWidgetVisible** (QString): `false`
**workspace-6f2d9e2d-1bbd-438e-a36c-30ac68e057d2/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 074e67fb-cca8-4c79-9e53-b9ddb2d8c965, 6f2d9e2d-1bbd-438e-a36c-30ac68e057d2`

## System environment

**USER**: `REMOVED`
**LANGUAGE**: `en_GB`
**LC_TIME**: `en_GB.UTF-8`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SHLVL**: `0`
**HOME**: `/home/REMOVED`
**DESKTOP_SESSION**: `cinnamon`
**GTK_MODULES**: `gail:atk-bridge`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**LC_MONETARY**: `nl_NL.UTF-8`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**MANDATORY_PATH**: `/usr/share/gconf/cinnamon.mandatory.path`
**QT_QPA_PLATFORMTHEME**: `qt5ct`
**LOGNAME**: `REMOVED`
**DEFAULTS_PATH**: `/usr/share/gconf/cinnamon.default.path`
**COLORFGBG**: `default;default`
**XDG_SESSION_ID**: `c2`
**SVN_EDITOR**: `vim`
**PATH**: `REMOVED`
**GDM_LANG**: `en_GB`
**PAPERSIZE**: `letter`
**LC_ADDRESS**: `nl_NL.UTF-8`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**DISPLAY**: `:0`
**LANG**: `en_GB.UTF-8`
**LC_TELEPHONE**: `nl_NL.UTF-8`
**XDG_SESSION_DESKTOP**: `cinnamon`
**XAUTHORITY**: `/home/REMOVED/.Xauthority`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/REMOVED`
**LC_NAME**: `nl_NL.UTF-8`
**SHELL**: `/bin/bash`
**QT_ACCESSIBILITY**: `1`
**GDMSESSION**: `cinnamon`
**LC_MEASUREMENT**: `nl_NL.UTF-8`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**LC_IDENTIFICATION**: `nl_NL.UTF-8`
**XDG_VTNR**: `7`
**LC_ALL**: `en_US.UTF-8`
**PWD**: `/home/REMOVED`
**XDG_DATA_DIRS**: `REMOVED`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-cinnamon:/etc/xdg`
**LC_NUMERIC**: `nl_NL.UTF-8`
**LC_PAPER**: `nl_NL.UTF-8`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**GTK_OVERLAY_SCROLLING**: `1`
**SESSION_MANAGER**: `REMOVED`
**XDG_CURRENT_DESKTOP**: `X-Cinnamon`
**GJS_DEBUG_OUTPUT**: `stderr`
**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`
**CINNAMON_VERSION**: `4.4.8`
**GIO_LAUNCHED_DESKTOP_FILE**: `/usr/share/applications/PBE.QOwnNotes.desktop`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `31179`
</details>

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue.

**Comment by pbek** [comment]
I'm sorry, that bug went in with https://github.com/pbek/QOwnNotes/commit/9b467a6d67ece68afcb654b570ee31c2ce92334e#diff-69560e71be6fc4483e10036d29839d66R326.

@Waqar144, can you please double check all your latest commits for "easter-eggs". :sweat_smile:

**Comment by pbek** [comment]
## 20.5.12
- fixed copying and moving of notes into sub-folders and note-folders that was broken by [#1749](https://github.com/pbek/QOwnNotes/pull/1749)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by blefuscu** [comment]
@pbek: Tested, works as expected on my system.

Thanks a lot for the quick fix. Very much appreciated!

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by pbek** [comment]
Thanks again for reporting! :grin:
