### ISSUE TITLE
[Support] image width

### ISSUE THREAD

**Issue by r00tr4v3n** [pbek/QOwnNotes#1766]
I'm trying to make images resizeable but I got a problem with the execution timing.
This part is called after the html hook and adds another width parameter.
https://github.com/pbek/QOwnNotes/blob/4eb9a74582733dd9bad58047f5bb5a4e3cf1a8b2/src/entities/note.cpp#L2430-L2444

I could add the width parameter at the front to mess with the regex but that's feels like a hack.
Any suggestions?

**Comment by pbek** [comment]
I could move the hook call, but it's hard to tell how many scripts that would break.

**Comment by pbek** [comment]
## 20.5.12
- the scripting hook `noteToMarkdownHtmlHook` will now be called after modifications
  to images in the note are made

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by r00tr4v3n** [comment]
Seems to work as expected, thanks!

**Comment by pbek** [comment]
Great, thank you for testing!
