### ISSUE TITLE
Encryption is missing the first line(s) in note

### ISSUE THREAD

**Issue by r3d9u11** [pbek/QOwnNotes#1773]
#### Expected behaviour
Encryption leave the first line(s) decrypted. 

#### Actual behaviour
Note should be ecrypted at all.

#### Steps to reproduce
Encrypt the note with text in first line

v20.5.12

**Comment by pbek** [comment]
The headline by default determines the filename of the note (e.g. for Nextcloud Notes), so the headline has to stay unencrypted or the note can't get a filename.

**Comment by r3d9u11** [comment]
@pbek 
Ok, thanks for clarification.
So it can be closed.
