### ISSUE TITLE
can't find notes in trash after removing the whole folder.

### ISSUE THREAD

**Issue by RichardBaker3020** [pbek/QOwnNotes#1774]
I deleted a notes folder by mistake, after that I couldn't find those notes in trash. Is there any way to restore notes deleted with whole folder?

**Comment by pbek** [comment]
I'm sorry, if you are talking about the "local QOwnNotes trash" (and don't have git or a sync-tool with backup activated) then the answer is: No

**Comment by sonulohani** [comment]
The actual behavior should be, when the note got removed locally via the application, if should put the file in trash.

**Comment by pbek** [comment]
Manually removed Notes do get to the local trash. I think we are talking about note subfolders that are removed manually inside the application. Currently the folder just gets deleted via a file system operation.
