### ISSUE TITLE
git versioning "command git init failed"

### ISSUE THREAD

**Issue by RichardBaker3020** [pbek/QOwnNotes#1776]
I set the _path to git executable_ in git versioning setting to "usr/bin/git", after that logs show` [warning] "Command '\"git\" init' failed"`, I wonder how I could get git versioning to work, thx in advance :)

**Comment by pbek** [comment]
Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting `Debug` in `Options`).

**Comment by RichardBaker3020** [comment]
QOwnNotes Debug Information
===========================

## General Info

**Platform**: `linux`
**Operating System**: `Ubuntu Core 18`
**Portable mode**: `no`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Settings

**gitCommitInterval** (int): `20`
**gitExecutablePath** (QString): `/usr/bin/git`
**gitLogCommand** (QString): *empty*

Here is log output in log panel:

```[21:44:09] [warning] "Command '\"/usr/bin/git\" init' failed"
[21:44:29] [warning] "Command '\"/usr/bin/git\" init' failed"
[21:44:49] [warning] "Command '\"/usr/bin/git\" init' failed"
[21:45:09] [warning] "Command '\"/usr/bin/git\" init' failed"
[21:45:29] [warning] "Command '\"/usr/bin/git\" init' failed"
```

**Comment by pbek** [comment]
Please see #1306, best use the PPA of QOwnNotes.

**Comment by datumbox** [comment]
@pbek I'm facing the same problem and it seems that it could be solved by including [git in the snap](https://forum.snapcraft.io/t/how-do-i-run-bash-commands-from-a-go-program-inside-a-snap/12686/2). Though not very elegant solution, it is a solution. Just wondering if you would be willing to add it on snap?

**Comment by datumbox** [comment]
@pbek I've never messed with snaps for releasing applications so I might be completely wrong here. Still with a quick look on [other open-source projects](https://github.com/evandandrea/jenkins-snap/blob/master/snapcraft.yaml), it seems you could easily do it by adding git support on the `snapcraft.yaml`'s `parts` section.

**Comment by pbek** [comment]
If the git binary is enough I'll add it. Can you please try the edge channel in a few minutes.
https://build.snapcraft.io/user/pbek/QOwnNotes

**Comment by pbek** [comment]
The build already failed, I guess it's not as easy as that...
https://build.snapcraft.io/user/pbek/QOwnNotes/1006386

**Comment by pbek** [comment]
So far nothing worked. I didn't get it running nor did I find another snapcraft.yml with a much different git integration. Please let me know if you find anything else.

**Comment by datumbox** [comment]
hey! Thanks for checking it out. Let me try to investigate a bit. I also pinged one of the Ubuntu Snap gurus to see if he has a pointer...

**Comment by pbek** [comment]
@datumbox, maybe you also want to take a look at https://github.com/muesli/gitomatic/.

**Comment by Darkle** [comment]
I think i got this working manually. Here are the steps I took on Debian Bullseye:

1. `git clone git@github.com:git/git.git`
2. cd git/
3. `autoconf`
4. `./configure --prefix=/home/username/pathforlocalusergit CFLAGS="${CFLAGS} -static"`
5. `make`
6. `make install`
7. Now add the path to the git binary to your QOwnNotes settings.

More info: https://www.lyraphase.com/wp/projects/how-to-build-git-for-a-host-with-no-compiler/
