### ISSUE TITLE
Strange heading format behaviour

### ISSUE THREAD

**Issue by ludenticus** [pbek/QOwnNotes#1777]
#### Version
20.5.12

#### Expected behaviour
Consistently format all headings

#### Actual behaviour
Some heading aren't formatted consistently when the last word is a single character. In this case, this character is displayed as «normal». It doesn't happen with every character, only some.
In my experience:

b, B, c, f, F, g, h, H, i, j, J, k, K, l, L, m, M, n, p, q, Q, r, s, t, T, v, V, w, W, x, X, z, ñ, Ñ ç, Ç, ž, Ž, ł, Ł, á, Á, é, É, í, Í, ú, Ú, ä, Ä, ë, Ë, ï, Ï, ö, Ö, ü, Ü, à, À, è, È, ì, Ì, ò, Ò, ù, Ù, æ, Æ.

#### Steps to reproduce
Type:

`# 1234566 B`

![image](https://user-images.githubusercontent.com/813198/83157365-218d4b00-a0c9-11ea-90ee-93139a5febb9.png)

Sometimes it triggers, sometimes it doesn't. But if you keep experimenting it shows again.

![image](https://user-images.githubusercontent.com/813198/83157421-2fdb6700-a0c9-11ea-8289-9395087b7a98.png)

![image](https://user-images.githubusercontent.com/813198/83157470-41247380-a0c9-11ea-859c-a0ba8f6b0a12.png)

Somewhere around 11-12 character and on it produces the same output.

![image](https://user-images.githubusercontent.com/813198/83157610-6fa24e80-a0c9-11ea-934e-6d5d2c1eb5f4.png)

**Comment by pbek** [comment]
That's a funny one... Unfortunately I wasn't able to reproduce that.
@Waqar144, do you know anything about that?

**Comment by ludenticus** [comment]
Yeah, quite funny. In order to reproduce it, the last character has to be one of the above posted, not a space.

Working on Arch/Gnome

**Comment by pbek** [comment]
I tried all kind of ways to type exactly your examples. :grimacing:

**Comment by ludenticus** [comment]
Alas! I've found the source of the issue: `Check spelling`... If I unselect it, it formats as it has to.

It is reported: `[14:15:42] [warning] Missing trigrams for languages: QSet("de_LU", "fr_BE", "fr_LU", "fr_CH", "de_BE", "it_CH", "de_CH", "de_LI", "fr_CA")`

**Comment by pbek** [comment]
Even more strange. @Waqar144?

**Comment by Waqar144** [comment]
Yes, I can reproduce it.
I will fix it soon.

**Comment by pbek** [comment]
## 20.6.0
- fix markdown heading highlighting issue (for [#1777](https://github.com/pbek/QOwnNotes/issues/1777), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by ludenticus** [comment]
As far as I can tell, it's solved. Perfect!

:1st_place_medal:

**Comment by pbek** [comment]
Great, thank you for testing!
