### ISSUE TITLE
[I] sabre/dav as CalDAV-Server not working

### ISSUE THREAD

**Issue by stratmaster** [pbek/QOwnNotes#1778]
#### Expected behaviour

The credentials for the sabre/dav CalDAV-Server should be accepted and all tasks should be fetched.

#### Actual behaviour

Although the correct credentials where given, the app gives this error: 

Warning: Calendar username and/or password incorrect ((null):0, (null))

#### Steps to reproduce

Use sabre/dav 4.1.0 (https://github.com/sabre-io/dav) and insert the correct credentials (server url, username, password)

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[21:46:43] [warning] Calendar username and/or password incorrect
[21:46:44] [warning] "QNetworkReply error 5 from url https://myserver.com/calendars/username/: " "Operation canceled"
[21:46:44] [warning] QIODevice::read (QNetworkReplyHttpImpl): device not open
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Do. Mai 28 21:47:24 2020`
**Version**: `20.5.13`
**Build date**: `May 27 2020`
**Build number**: `5695`
**Platform**: `macosx`
**Operating System**: `macOS 10.15`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1440x900`
**Screen resolution(s)**: `1440x900, 1920x1080`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `20`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `18.0.4.2`
**appVersion**: *empty*

</details>

**Comment by pbek** [comment]
Can be all kind of stuff from desktop firewall, wrong url to wrong credentials. I haven't had troubles with Nextcloud 18 (that also is using sabre/dav).

**Comment by pbek** [comment]
There should be more messages in your log (have you turned on debug logging in your debug panel?)

**Comment by pbek** [comment]
I will close this issue until there is more information.
