### ISSUE TITLE
Cant pick a folder as notes folder

### ISSUE THREAD

**Issue by elmonteanalogo** [pbek/QOwnNotes#1779]
This software is exactly what I need but I'd like to be able to select any folder as my notes folder. It seems like you're supposed to be able to just do it but I cant select anything at all in the menu that pops up to select the path to a folder. The only way to use the program is if I go with the default Nextcloud/Notes in my home folder during installation. I deleted it and basically couldnt start the program ever again, even after uninstalling entirely and downloading it again. Luckily I kept the folder in recycle bin and restored it and could use the program again.

Installed using flatpak on deepin 15.11

**Comment by pbek** [comment]
Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting `Debug` in `Options`).

And can you please explain in more detail and step by step what you did, what happened and what you expected.

btw. there also is an AppImage, if Flatpak is causing troubles for you, see https://www.qownnotes.org/installation

**Comment by lemontanalogue** [comment]
Thanks for your quick reply. I've done nothing at all really. The very first thing that happens after running the program is that it prompts you to select a folder. I've tried to select a folder and couldnt. That's basically the entire issue, it does work with the default folder it creates but cant select anything else. Ill try to install with appimage in case flatpak is the issue. In the little log panel i get this... all i did was try to browse around and select folders to no effect 

[15:30:36] [debug] cloudConnection: CloudConnection: <id>1 <name>"Predeterminado" <serverUrl>"" <username>"" <priority>1
[15:31:02] [debug] initShortcuts - 'menuBarIsVisible': true
[15:31:02] [debug] cloudConnection: CloudConnection: <id>1 <name>"Predeterminado" <serverUrl>"" <username>"" <priority>1
[15:31:02] [debug] buildNotesIndex - 'noteSubFolderId': 0
[15:31:02] [debug] setupNoteFolderTables - 'database version': 14
[15:31:02] [debug] cloudConnection: CloudConnection: <id>1 <name>"Predeterminado" <serverUrl>"" <username>"" <priority>1
[15:31:02] [debug] loadNoteDirectoryList
[15:31:02] [debug] reloadTagTree
[15:31:02] [debug] reloadTagTree - 'noteSubFolderIds': QVector(0)
[15:31:02] [debug] filterNotesByNoteSubFolders - 'noteSubFolderIds': QVector(0)
[15:31:02] [debug] reloadNoteSubFolderTree
[15:31:02] [debug] filterNotesByNoteSubFolders - 'noteSubFolderIds': QVector(0)
[15:31:02] [debug] reloadNoteSubFolderTree
[15:31:02] [debug] reloadTagTree
[15:31:02] [debug] reloadTagTree - 'noteSubFolderIds': QVector(0)
[15:31:02] [debug] loadNoteDirectoryList
[15:31:02] [debug] reloadTagTree
[15:31:02] [debug] reloadTagTree - 'noteSubFolderIds': QVector(0)
[15:31:02] [debug] filterNotesByNoteSubFolders - 'noteSubFolderIds': QVector(0)
[15:31:02] [debug] reloadNoteSubFolderTree
[15:31:02] [debug] filterNotesByNoteSubFolders - 'noteSubFolderIds': QVector(0)

Here's the output from larger debug screen

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `vie. may. 29 15:32:35 2020`
**Version**: `20.5.13`
**Build date**: `May 28 2020`
**Build number**: `721`
**Platform**: `linux`
**Operating System**: `KDE Flatpak runtime`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `TuxFamily`
**Qt Version (build)**: `5.14.2`
**Qt Version (runtime)**: `5.14.2`
**Portable mode**: `no`
**Settings path / key**: `/home/mangudai/.var/app/org.qownnotes.QOwnNotes/config/PBE/QOwnNotes.conf`
**Application database path**: `/home/mangudai/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `es_ES`
**Locale (interface)**: `en`
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `2`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_AU, en_BS, en_BZ, en_CA, en_GB, en_GH, en_IE, en_IN, en_JM, en_MW, en_NA, en_NZ, en_PH, en_TT, en_US, en_ZA, en_ZW, es_ANY, es_AR, es_BO, es_CL, es_CO, es_CR, es_CU, es_DO, es_EC, es_ES, es_GT, es_HN, es_MX, es_NI, es_PA, es_PE, es_PR, es_PY, es_SV, es_UY, es_VE`
**Language names**: `Australian English (Australia), English (Bahamas), English (Belize), Canadian English (Canada), British English (United Kingdom), English (Ghana), English (Ireland), English (India), English (Jamaica), English (Malawi), English (Namibia), English (New Zealand), English (Philippines), English (Trinidad & Tobago), American English (United States), English (South Africa), English (Zimbabwe), español de España (España), español (Argentina), español (Bolivia), español (Chile), español (Colombia), español (Costa Rica), español (Cuba), español (República Dominicana), español (Ecuador), español de España (España), español (Guatemala), español (Honduras), español de México (México), español (Nicaragua), español (Panamá), español (Perú), español (Puerto Rico), español (Paraguay), español (El Salvador), español (Uruguay), español (Venezuela)`
**Application dictionaries path**: `/home/mangudai/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `2`

### Note folder `Notes`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/mangudai/Nextcloud/Notes`
**remotePath**: *empty*
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/mangudai/Nextcloud/Notes/notes.sqlite`

## Cloud connections

### Cloud connection `Predeterminado`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Enabled scripts

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6d7d03f9-ffac-4e75-a57b-847fd4871eac`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrainingSpaces** (bool): `false`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**LastUpdateCheck** (QDateTime): `2020-05-29T15:25:57.791`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `FreeSans,14,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Sans Serif,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**NoteFolder-2/NoteTabNameList** (QStringList): `Welcome to QOwnNotes`
**NoteFolder-2/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-2/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteFolder-2/allowDifferentNoteFileName** (bool): `true`
**NoteHistory-2** (QVariantList): `<variant list with 2 item(s)>`
**NoteHistoryCurrentIndex-2** (int): `1`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `true`
**StartHidden** (bool): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `2`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `true`
**darkModeColors** (bool): `true`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `15`
**interfaceLanguage** (QString): `en`
**internalIconTheme** (bool): `true`
**itemHeight** (int): `15`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/mangudai/Nextcloud/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `true`
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (bool): `true`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Completo`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**USER**: `mangudai`
**LANGUAGE**: `es_ES`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SHLVL**: `0`
**QT4_IM_MODULE**: `fcitx`
**HOME**: `/home/mangudai`
**DESKTOP_SESSION**: `deepin`
**GIO_LAUNCHED_DESKTOP_FILE**: `/var/lib/flatpak/exports/share/applications/org.qownnotes.QOwnNotes.desktop`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**QT_LINUX_ACCESSIBILITY_ALWAYS_ON**: `1`
**QT_DBL_CLICK_DIST**: `15`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `12593`
**LOGNAME**: `mangudai`
**GTK_IM_MODULE**: `fcitx`
**XDG_SESSION_ID**: `2`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**PATH**: `/app/bin:/usr/bin`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**DISPLAY**: `:99.0`
**LANG**: `es_ES.UTF-8`
**XDG_CURRENT_DESKTOP**: `Deepin`
**XDG_SESSION_DESKTOP**: `deepin`
**XMODIFIERS**: `@im=fcitx`
**XAUTHORITY**: `/run/user/1000/Xauthority`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm/data/mangudai`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**SHELL**: `/bin/sh`
**QT_ACCESSIBILITY**: `1`
**GDMSESSION**: `deepin`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**XDG_VTNR**: `1`
**QT_IM_MODULE**: `fcitx`
**PWD**: `/home/mangudai`
**CLUTTER_IM_MODULE**: `xim`
**XDG_DATA_DIRS**: `/app/share:/usr/share:/usr/share/runtime/share:/run/host/share`
**XDG_CONFIG_DIRS**: `/app/etc/xdg:/etc/xdg`
**QT_PLUGIN_PATH**: `/app/lib64/plugins:/app/lib/plugins:/usr/share/runtime/lib/plugins`
**QML2_IMPORT_PATH**: `/app/lib64/qml:/app/lib/qml`
**GI_TYPELIB_PATH**: `/app/lib/girepository-1.0`
**GST_PLUGIN_PATH**: `/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0`
**KDE_FORK_SLAVES**: `1`
**XDG_DATA_HOME**: `/home/mangudai/.var/app/org.qownnotes.QOwnNotes/data`
**XDG_CONFIG_HOME**: `/home/mangudai/.var/app/org.qownnotes.QOwnNotes/config`
**XDG_CACHE_HOME**: `/home/mangudai/.var/app/org.qownnotes.QOwnNotes/cache`
**LD_LIBRARY_PATH**: `/app/lib:/usr/lib/x86_64-linux-gnu/GL/nvidia-418-74/lib:/usr/lib/x86_64-linux-gnu/openh264/extra`

**Comment by lemontanalogue** [comment]
Just want to add that I just installed it using the method for Debian 9 (that deepin is based on) provided in the website and its now working correctly so whatever it was it was related to the flatpak installation

**Comment by pbek** [comment]
The Debian and Flatpak version are using different settings paths, so you could start with empty settings... You can reset your settings from the CLI (see https://docs.qownnotes.org/en/latest/getting-started/cli-parameters/). I've never heard reports of problems with the file chooser in the Flatpak version, but I guess that is handled by the desktop environment, so I guess it's a Deepin + Qt + Flatpak problem.

**Comment by pbek** [comment]
I will close this issue until there is more information.
