### ISSUE TITLE
Export HTML.if using owncloud image url would be great

### ISSUE THREAD

**Issue by tanshion** [pbek/QOwnNotes#178]
Export HTML, if using owncloud image url would be great.You can remotely see page multimedia.

**Comment by pbek** [comment]
I guess you could script that yourself with the new scripting engine.
There is a function `noteToMarkdownHtmlHook` that you can use as hook.
You will find an example usage in <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/example.qml>.

But maybe you would have to publish the images first in ownCloud to be allowed to view it from anywhere...

**Comment by pbek** [comment]
I'm closing this until I get more information.
