### ISSUE TITLE
markdown-it.qml:88: TypeError: Cannot call method 'render' of undefined

### ISSUE THREAD

**Issue by alpi-ua** [pbek/QOwnNotes#1781]
Getting 
file:///home/user/.local/share/PBE/QOwnNotes/scripts/markdown-it/markdown-it.qml:88: TypeError: Cannot call method 'render' of undefined

**Comment by pbek** [comment]
Can you please move that to https://github.com/qownnotes/scripts/issues/ (and please fill out the issue template).
