### ISSUE TITLE
OBS Debian repository broken?

### ISSUE THREAD

**Issue by schiessle** [pbek/QOwnNotes#1783]
I just noticed that I can no longer update QOwnNotes from the OBS Debian Respository.

````
$ apt policy qownnotes
qownnotes:
  Installed: 20.5.13-1
  Candidate: 20.6.0-1
  Version table:
     20.6.0-1 500
        500 http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Debian_10  Packages
 *** 20.5.13-1 100
        100 /var/lib/dpkg/status
````

````
 $ sudo apt upgrade 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  qownnotes
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 3,921 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Err:1 http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Debian_10  qownnotes 20.6.0-1
  404  Not Found [IP: 130.57.72.10 80]
E: Failed to fetch http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Debian_10/./amd64/qownnotes_20.6.0-1_amd64.deb  404  Not Found [IP: 130.57.72.10 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
````

Seems like the repository announces a version which is not there yet. Browsing the repository I can't find a `qownnotes_20.6.0-1_amd64.deb`

`apt clean` and `apt updated` or `--fix-missing` didn't solved it.

**Comment by pbek** [comment]
That's really strange. The repository url seems ok, but the current package isn't there.

But https://build.opensuse.org/package/binaries/home:pbek:QOwnNotes/desktop/Debian_10 shows them all...

**Comment by pbek** [comment]
It's the same with https://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Debian_9.0/

**Comment by pbek** [comment]
I now asked in their IRC `Hi dear OBS people. Is there a problem with the deployment process? https://build.opensuse.org/package/binaries/home:pbek:QOwnNotes/desktop/Debian_10 shows the current release of QOwnNotes, but if you click "Go to download repository" that leads to https://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Debian_10/ the acual packages are from January.`

**Comment by pbek** [comment]
> afaik there was a big rollback because the main mirror had a Kernel issue and needed urgent fixing

OBS currently has "issues"... :grin:

**Comment by pbek** [comment]
see https://progress.opensuse.org/issues/67633

**Comment by schiessle** [comment]
Thanks for investigating, so let's wait a bit until OBS sorted out the issue.

**Comment by pbek** [comment]
Looks ok again, can you please test it?

**Comment by schiessle** [comment]
perfect, works again :smile:
