### ISSUE TITLE
Preview of images inserted from other drives without copying them to the media library on Windows doesn't work if the file name include space and chinese characters.

### ISSUE THREAD

**Issue by ostaith** [pbek/QOwnNotes#1787]
#### Expected behaviour
insert a image that file name include space and chinese characters, and choose "Don't copy image to media folder", hope the image can display in note preview window.

#### Actual behaviour
the image can't display in note preview.

#### Steps to reproduce
insert a image that file name include space and chinese characters, for example `test 测试.jpg`, and choose "Don't copy image to media folder",
then note preview can't display the image. just show the source code `![ffff](file:///E:/Download/test 测试.jpg)`.

**Comment by pbek** [comment]
Thank you for reporting, that seems to be a limitation of the md4c library.

@Waqar144

**Comment by pbek** [comment]
I suppose the issue is that `file:///E:/Download/test 测试.jpg` is no proper URI, since there is a space in it. It would be better to just url-encode such urls when inserting them with the image dialog.

**Comment by pbek** [comment]
## 20.6.5
- fixed preview of inserted images from another drive without copying them to the
  media library on Windows if filename has spaces in it

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
