### ISSUE TITLE
Startup speed

### ISSUE THREAD

**Issue by nivaca** [pbek/QOwnNotes#1788]
Hi,
Is there any way to speed up QOwnNotes startup?
I've resourced to have it running from system startup in order to make it open faster.
(I'm running it on Manjaro KDE and on Arch with KDE. I don't use any of the cloud options.)
Thanks and keep up the good work!

**Comment by pbek** [comment]
It opens in under 2 sec with 644 notes for me.

Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting `Debug` in `Options`).

**Comment by nivaca** [comment]
Sure:

[jun 14 11:46:21] [debug]: Set proxy configuration to use NO proxy
[jun 14 11:46:21] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[jun 14 11:46:21] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
[jun 14 11:46:22] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[jun 14 11:46:22] [debug]: updatePanelMenu  - 'updatePanelMenu'
[jun 14 11:46:22] [scripting]: loading script file: /home/nivaca/.local/share/PBE/QOwnNotes/scripts/list-maker/list-maker.qml
[jun 14 11:46:22] [scripting]: loading script file: /home/nivaca/.local/share/PBE/QOwnNotes/scripts/add-multiple-tags/add-multiple-tags.qml
[jun 14 11:46:22] [scripting]: loading script file: /home/nivaca/.local/share/PBE/QOwnNotes/scripts/disable-readonly-mode/disable-readonly-mode.qml
[jun 14 11:46:22] [debug]: buildNotesIndex  - 'noteSubFolderId':  0
[jun 14 11:46:23] [debug]: setupNoteFolderTables  - 'database version':  14
[jun 14 11:46:23] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
[jun 14 11:46:23] [debug]: loadNoteDirectoryList
[jun 14 11:46:23] [debug]: reloadTagTree
[jun 14 11:46:23] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector()
[jun 14 11:46:23] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(33, 34)
[jun 14 11:46:23] [debug]: reloadNoteSubFolderTree
[jun 14 11:46:23] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(33, 34)
[jun 14 11:46:23] [debug]: loadNoteDirectoryList
[jun 14 11:46:24] [debug]: reloadTagTree
[jun 14 11:46:24] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(33, 34)
[jun 14 11:46:24] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(33, 34)
[jun 14 11:46:24] [debug]: reloadNoteSubFolderTree
[jun 14 11:46:24] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(33, 34)
[jun 14 11:46:24] [debug]: reloadNoteSubFolderTree
[jun 14 11:46:24] [debug]: reloadTagTree
[jun 14 11:46:24] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(33, 34)
[jun 14 11:46:25] [debug]: updatePanelMenu  - 'updatePanelMenu'
[jun 14 11:46:25] [debug]: updatePanelMenu  - 'updatePanelMenu'
[jun 14 11:46:25] [debug]: updatePanelMenu  - 'updatePanelMenu'
[jun 14 11:46:25] [debug]: updatePanelMenu  - 'updatePanelMenu'
[jun 14 11:46:25] [info]: "QOwnNotes server listening on port 22222"
[jun 14 11:46:25] [debug]: on_noteTreeWidget_currentItemChanged
[jun 14 11:46:25] [debug]: setCurrentNote  - 'note':  Note: <id>114 <name>"wget list of files" <fileName>"wget list of files.md" <noteSubFolderId>9 <relativePath>"Computing" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
[jun 14 11:46:25] [debug]:  added to history:  NoteHistoryItem: <noteName>"wget list of files" <noteSubFolderPathData>"Computing" <cursorPosition>43 <relativeScrollBarPosition>0
[jun 14 11:46:32] [debug]: storeSettings  - 'noteHistoryItem':  NoteHistoryItem: <noteName>"wget list of files" <noteSubFolderPathData>"Computing" <cursorPosition>43 <relativeScrollBarPosition>0
[jun 14 11:46:33] [debug]: storeSettings  - 'noteHistoryItem':  NoteHistoryItem: <noteName>"wget list of files" <noteSubFolderPathData>"Computing" <cursorPosition>43 <relativeScrollBarPosition>0

**Comment by pbek** [comment]
Can you please also post the output from the debug settings (see issue template).

**Comment by nivaca** [comment]
Sorry, I didn't understand.

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `dom. jun. 14 11:52:08 2020`
**Version**: `20.6.5`
**Build date**: `Jun 13 2020`
**Build number**: `727`
**Platform**: `linux`
**Operating System**: `Manjaro Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.0`
**Qt Version (runtime)**: `5.15.0`
**Portable mode**: `no`
**Settings path / key**: `/home/nivaca/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/nivaca/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: `en`
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1600x900`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `759`
**Calendar items**: `0`
**Enabled scripts**: `3`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: `auto`
**Language codes**: `en_AG, en_BS, en_BW, en_BZ, en_DK, en_GB, en_GB-large, en_GH, en_HK, en_IE, en_IN, en_JM, en_NA, en_NG, en_NZ, en_SG, en_TT, en_US, en_US-large, en_ZA, en_ZW, es_ANY`
**Language names**: `English (Antigua & Barbuda), English (Bahamas), English (Botswana), English (Belize), English (Denmark), British English (United Kingdom), British English (United Kingdom) [large], English (Ghana), English (Hong Kong SAR China), English (Ireland), English (India), English (Jamaica), English (Namibia), English (Nigeria), English (New Zealand), English (Singapore), English (Trinidad & Tobago), American English (United States), American English (United States) [large], English (South Africa), English (Zimbabwe), español de España (España)`
**Application dictionaries path**: `/home/nivaca/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `3`

### Note folder `nivaca`

**id**: `3`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/nivaca/docs/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: `Uncategorised`
**database file**: `/home/nivaca/docs/Notes/notes.sqlite`

## Cloud connections

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Enabled scripts

### Script `List maker`

**id**: `2`
**path**: `/home/nivaca/.local/share/PBE/QOwnNotes/scripts/list-maker/list-maker.qml`
**variablesJson**: 
```
{
    "setLetters": "abcdefghijklmnopqrstuvwxyz",
    "setMarkers": "- • ‣"
}
```
**identifier**: `list-maker`
**version**: `0.0.2`
**minAppVersion**: `17.07.8`

### Script `Add Multiple tags`

**id**: `3`
**path**: `/home/nivaca/.local/share/PBE/QOwnNotes/scripts/add-multiple-tags/add-multiple-tags.qml`
**variablesJson**: *empty*
**identifier**: `add-multiple-tags`
**version**: `0.0.1`
**minAppVersion**: `17.06.2`

### Script `Disable read-only mode on note double-click`

**id**: `4`
**path**: `/home/nivaca/.local/share/PBE/QOwnNotes/scripts/disable-readonly-mode/disable-readonly-mode.qml`
**variablesJson**: *empty*
**identifier**: `disable-readonly-mode`
**version**: `1.0.0`
**minAppVersion**: `18.08.1`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `true`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `29`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-3bdec0ed-eb9c-424c-9c9b-b6a76e087531`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `2`
**Editor/removeTrainingSpaces** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-06-14T11:51:58.069`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-3** (QStringList): `Writing, Latin, Computing/Linux`
**MainWindow/noteTextEdit.code.font** (QString): `Ubuntu Mono,14,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Roboto,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Ubuntu Mono,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Ubuntu Mono,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/move-notes** (QString): `16384`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-3/NoteTabNameList** (QString): `wget list of files`
**NoteFolder-3/NoteTabStickinessList**: *empty*
**NoteFolder-3/NoteTabSubFolderPathDataList** (QString): `Computing`
**NoteFolder-3/allowDifferentNoteFileName** (bool): `true`
**NoteHistory-2** (QVariantList): `<variant list with 8 item(s)>`
**NoteHistory-3** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-2** (QString): `7`
**NoteHistoryCurrentIndex-3** (QString): `199`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-actionFind_notes_in_all_subfolders** (QString): `Ctrl+F`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `3`
**currentWorkspace** (QString): `d973ae1d-fcba-4de7-937f-77958dd06abe`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): `kate`
**fullyHighlightedBlockquotes** (QString): `true`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): `konsole -e ~/bin/tig.sh %notePath%`
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): `en`
**interfaceStyle** (QString): `kvantum-dark`
**internalIconTheme** (QString): `true`
**itemHeight** (QString): `23`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `true`
**noteEditIsCentralWidget** (QString): `false`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `true`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `true`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `0`
**notesPath** (QString): `/home/nivaca/docs/Notes`
**notifyAllExternalModifications** (QString): `true`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `b9756ad8-8018-4605-b233-54d8227243f1`
**recentNoteFolders** (QStringList): `/home/nivaca/Dropbox/docs/Notes, /home/nivaca/Nextcloud/Notes`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-2** (QStringList): `touchscrren, rsync sync dirs`
**savedSearches/noteFolder-3** (QStringList): `icon fix, nvidia screencasting fix, netdiscover, lksjdflk, testing, wrap paragraph, TEI date range, biblatex convert to XML, biblatex original date, biblatex date ranges, attribute to element, TEI century, linux pop sounds, ffmpeg video loop, cum histórico, mp4 to gif, no sound after resume, server, increment value, transform xml (xsl, xslt), bash transform files xsl xslt, mirror autoupdate, numerically the same, include, find consecutive duplicates, delete commit history, split video lossless, holds interest, whereupon, viewed in this light, force firefox to use kde dialogues, Permission error ssh, Scotus, install emacs from source, check system type, sublation, at that moment, seamlessly, narrowing, see dependencies, help, pose a question, _grammar quirks, This begs the question, straight quote tick, thereby therefore henec, change theme terminal, Convert DEB Packages Into Arch Linux Packages, reipsa, _vocabulario esp., cups, org do not generate TOC, where are themes stored, Correct theme, mouse cursor problem, recursve grep, vscode new tab for file, Respond yes to query, dd, autostart dir, site, signing jupyter notebooks, Convert jupyter into slides, remove "in:" in article citations, pick up on, LS Prol. q.1 sec.4, habetur propositum, to paint with a very broad brush, immediately thereafter, bookmarks, Causation - God's necessary concurrency, Natural intuitive cognitions, my .emacs, secundum quod, qownnotes arch repo, evaluate from command line, upgrade emacs from command line, Disable krunner (plasma-search), pro quanto, barking, wget list of files, folder associations, prout, check disk, git sync forked repo, downgrade, emacs global menu, no line end, resizebox, Lehmann abbreviations, KDE templates, Latín, gnupg permissions, scan disks at book, jp2, example, pacman find file package, find out local repository, check of package exists, check if machine is laptop or pc`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `true`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `actionSave_modified_notes, actionAllow_note_editing, action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, , , action_Find_text_in_note, actionReplace_in_current_note, actionShare_note`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `true`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-70336988-0ee0-43c5-aef5-32d39c30c42e/name** (QString): `full`
**workspace-70336988-0ee0-43c5-aef5-32d39c30c42e/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-70336988-0ee0-43c5-aef5-32d39c30c42e/windowState** (QByteArray): `<binary data>`
**workspace-b9756ad8-8018-4605-b233-54d8227243f1/name** (QString): `minimal`
**workspace-b9756ad8-8018-4605-b233-54d8227243f1/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-b9756ad8-8018-4605-b233-54d8227243f1/windowState** (QByteArray): `<binary data>`
**workspace-d973ae1d-fcba-4de7-937f-77958dd06abe/name** (QString): `n`
**workspace-d973ae1d-fcba-4de7-937f-77958dd06abe/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-d973ae1d-fcba-4de7-937f-77958dd06abe/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `70336988-0ee0-43c5-aef5-32d39c30c42e, b9756ad8-8018-4605-b233-54d8227243f1, d973ae1d-fcba-4de7-937f-77958dd06abe`

## System environment

**SHELL**: `/usr/bin/fish`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**LC_ADDRESS**: `es_CO.UTF-8`
**LC_NAME**: `es_CO.UTF-8`
**XDG_CONFIG_HOME**: `/home/nivaca/.config`
**DESKTOP_SESSION**: `/usr/share/xsessions/plasma`
**LC_MONETARY**: `es_CO.UTF-8`
**EDITOR**: `/usr/bin/nano`
**GTK_MODULES**: `canberra-gtk-module`
**XDG_SEAT**: `seat0`
**PWD**: `/home/nivaca`
**XDG_SESSION_DESKTOP**: `KDE`
**LOGNAME**: `nivaca`
**XDG_SESSION_TYPE**: `x11`
**OMF_PATH**: `/home/nivaca/.local/share/omf`
**XAUTHORITY**: `/home/nivaca/.Xauthority`
**HOME**: `/home/nivaca`
**LC_PAPER**: `es_CO.UTF-8`
**LANG**: `en_US.UTF-8`
**XDG_CURRENT_DESKTOP**: `KDE`
**VIRTUAL_ENV_DISABLE_PROMPT**: `1`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**LC_IDENTIFICATION**: `es_CO.UTF-8`
**USER**: `nivaca`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**VISUAL**: `vim`
**DISPLAY**: `:0`
**SHLVL**: `2`
**LC_TELEPHONE**: `es_CO.UTF-8`
**LC_MEASUREMENT**: `es_CO.UTF-8`
**XDG_VTNR**: `1`
**XDG_SESSION_ID**: `2`
**QT_LINUX_ACCESSIBILITY_ALWAYS_ON**: `1`
**MOZ_PLUGIN_PATH**: `/usr/lib/mozilla/plugins`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**JAVA_FONTS**: `/usr/share/fonts/TTF`
**LC_TIME**: `es_CO.UTF-8`
**XDG_DATA_DIRS**: `/home/nivaca/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop`
**PATH**: `/home/nivaca/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin:/home/nivaca/bin:/home/nivaca/.local/bin:/usr/local/bin:/opt/texlive/2020/bin/x86_64-linux:/home/nivaca/.gem/ruby/2.6.0/bin:/usr/lib/ccache/bin/`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**MAIL**: `/var/spool/mail/nivaca`
**_JAVA_OPTIONS**: `-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel`
**OMF_CONFIG**: `/home/nivaca/.config/omf`
**LC_NUMERIC**: `es_CO.UTF-8`
**LANGUAGE**: `en_US`
**XCURSOR_THEME**: `breeze_cursors`
**XCURSOR_SIZE**: `0`
**BROWSER**: `/usr/bin/firefox`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**KDE_FULL_SESSION**: `true`
**KDE_SESSION_VERSION**: `5`
**KDE_SESSION_UID**: `1000`
**SESSION_MANAGER**: `local/nivaca-pc:@/tmp/.ICE-unix/3740,unix/nivaca-pc:/tmp/.ICE-unix/3740`

**Comment by pbek** [comment]
Can't see anything out of place. And according to your log QON took about 3 sec until the note folder was loaded any everything was ready.
And it takes about the same time for me on Manjaro (built via AUR).  

So what is "long" for you?

**Comment by Waqar144** [comment]
> It opens in under 2 sec with 644 notes for me.

That's not completely true for non-kde systems and first startup. If Qt libs are preloaded then startup time maybe faster. Other optimizations can be explored as well,

On Ubuntu 20.04, startupt time for me is around 5 - 10 seconds at least

**Comment by nivaca** [comment]
As I had previously replied by email (but the message somehow got lost), when cold starting it can take 10s. And I'm running KDE.

**Comment by pbek** [comment]
Does it also take 10 sec if you close and open QON again?

**Comment by pbek** [comment]
I will close this issue until there is more information.
