### ISSUE TITLE
QOwnNotes not showing in Dash (Ubuntu 16.04)

### ISSUE THREAD

**Issue by polkillas** [pbek/QOwnNotes#179]
I've just installed QOwnNotes in my Ubuntu 16.04 box from the repository and it works really fine, but I've found that there is no entry in Dash (see image attached).

![workspace 1_002](https://cloud.githubusercontent.com/assets/10198216/15455538/5b111d94-2057-11e6-82c7-39f999e8b874.jpg)

**Comment by pbek** [comment]
Which repository did you use? Ubuntu Launchpad or open build service?

**Comment by pbek** [comment]
is your dash case sensitive? did you try you try `QOwnNotes`?

**Comment by polkillas** [comment]
Launchpad, ppa:pbek/qownnotes from http://www.qownnotes.org/installation

**Comment by pbek** [comment]
Is the desktop file `/usr/share/applications/QOwnNotes.desktop` present on your disk?

**Comment by polkillas** [comment]
No, it isn't. I've checked also the files installed by the package in Synaptic and it isn't there neither.

**Comment by pbek** [comment]
This is what I get for QOwnNotes 16.05.19 on Ubuntu 16.04 (kde neon):

```
/usr/bin/QOwnNotes
/usr/share/QOwnNotes/languages/QOwnNotes_de.qm
/usr/share/QOwnNotes/languages/QOwnNotes_en.qm
/usr/share/QOwnNotes/languages/QOwnNotes_es.qm
/usr/share/QOwnNotes/languages/QOwnNotes_fr.qm
/usr/share/QOwnNotes/languages/QOwnNotes_hu.qm
/usr/share/QOwnNotes/languages/QOwnNotes_it.qm
/usr/share/QOwnNotes/languages/QOwnNotes_ja.qm
/usr/share/QOwnNotes/languages/QOwnNotes_nl.qm
/usr/share/QOwnNotes/languages/QOwnNotes_pl.qm
/usr/share/QOwnNotes/languages/QOwnNotes_pt.qm
/usr/share/QOwnNotes/languages/QOwnNotes_ru.qm
/usr/share/QOwnNotes/languages/QOwnNotes_zh.qm
/usr/share/applications/QOwnNotes.desktop
/usr/share/doc/qownnotes/changelog.Debian.gz
/usr/share/doc/qownnotes/copyright
/usr/share/icons/hicolor/128x128/apps/QOwnNotes.png
/usr/share/icons/hicolor/16x16/apps/QOwnNotes.png
/usr/share/icons/hicolor/24x24/apps/QOwnNotes.png
/usr/share/icons/hicolor/256x256/apps/QOwnNotes.png
/usr/share/icons/hicolor/32x32/apps/QOwnNotes.png
/usr/share/icons/hicolor/48x48/apps/QOwnNotes.png
/usr/share/icons/hicolor/512x512/apps/QOwnNotes.png
/usr/share/icons/hicolor/64x64/apps/QOwnNotes.png
/usr/share/icons/hicolor/96x96/apps/QOwnNotes.png
/usr/share/icons/hicolor/scalable/apps/QOwnNotes.svg
/usr/share/pixmaps/QOwnNotes.png
```

What does `dpkg -L qownnotes` return for you?

**Comment by polkillas** [comment]
/usr
/usr/share
/usr/share/doc
/usr/share/doc/qownnotes
/usr/share/doc/qownnotes/changelog.Debian.gz
/usr/share/doc/qownnotes/copyright
/usr/share/icons
/usr/share/icons/hicolor
/usr/share/icons/hicolor/24x24
/usr/share/icons/hicolor/24x24/apps
/usr/share/icons/hicolor/24x24/apps/QOwnNotes.png
/usr/share/icons/hicolor/64x64
/usr/share/icons/hicolor/64x64/apps
/usr/share/icons/hicolor/64x64/apps/QOwnNotes.png
/usr/share/icons/hicolor/256x256
/usr/share/icons/hicolor/256x256/apps
/usr/share/icons/hicolor/256x256/apps/QOwnNotes.png
/usr/share/icons/hicolor/96x96
/usr/share/icons/hicolor/96x96/apps
/usr/share/icons/hicolor/96x96/apps/QOwnNotes.png
/usr/share/icons/hicolor/48x48
/usr/share/icons/hicolor/48x48/apps
/usr/share/icons/hicolor/48x48/apps/QOwnNotes.png
/usr/share/icons/hicolor/scalable
/usr/share/icons/hicolor/scalable/apps
/usr/share/icons/hicolor/scalable/apps/QOwnNotes.svg
/usr/share/icons/hicolor/32x32
/usr/share/icons/hicolor/32x32/apps
/usr/share/icons/hicolor/32x32/apps/QOwnNotes.png
/usr/share/icons/hicolor/16x16
/usr/share/icons/hicolor/16x16/apps
/usr/share/icons/hicolor/16x16/apps/QOwnNotes.png
/usr/share/icons/hicolor/128x128
/usr/share/icons/hicolor/128x128/apps
/usr/share/icons/hicolor/128x128/apps/QOwnNotes.png
/usr/share/icons/hicolor/512x512
/usr/share/icons/hicolor/512x512/apps
/usr/share/icons/hicolor/512x512/apps/QOwnNotes.png
/usr/share/applications
/usr/share/applications/QOwnNotes.desktop
/usr/share/pixmaps
/usr/share/pixmaps/QOwnNotes.png
/usr/share/QOwnNotes
/usr/share/QOwnNotes/languages
/usr/share/QOwnNotes/languages/QOwnNotes_hu.qm
/usr/share/QOwnNotes/languages/QOwnNotes_pt.qm
/usr/share/QOwnNotes/languages/QOwnNotes_zh.qm
/usr/share/QOwnNotes/languages/QOwnNotes_ru.qm
/usr/share/QOwnNotes/languages/QOwnNotes_ja.qm
/usr/share/QOwnNotes/languages/QOwnNotes_es.qm
/usr/share/QOwnNotes/languages/QOwnNotes_de.qm
/usr/share/QOwnNotes/languages/QOwnNotes_fr.qm
/usr/share/QOwnNotes/languages/QOwnNotes_it.qm
/usr/share/QOwnNotes/languages/QOwnNotes_pl.qm
/usr/share/QOwnNotes/languages/QOwnNotes_en.qm
/usr/share/QOwnNotes/languages/QOwnNotes_nl.qm
/usr/bin
/usr/bin/QOwnNotes

**Comment by pbek** [comment]
It seems that something removed `/usr/share/applications/QOwnNotes.desktop` on your system. What happens if you just re-install QOwnNotes?

**Comment by polkillas** [comment]
There is no difference when I reinstall the app.

**Comment by pbek** [comment]
I just downloaded <https://launchpad.net/~pbek/+archive/ubuntu/qownnotes/+build/9797040/+files/qownnotes_16.05.20-1ubuntu3ppa1~yakkety1_amd64.deb> directly. The desktop file is present in the package. I'm not sure if I can help you, it seems to be a problem in your system...

**Comment by pbek** [comment]
If nothing helps you could just extract the package and copy the desktop file to `/usr/share/applications/` yourself.

**Comment by pbek** [comment]
I'm closing this until I get more information.

**Comment by polkillas** [comment]
Sorry for the delay, I had a problem with my Windows dual-boot.
The desktop file was present in the package and copying it to <code>/usr/share/applications</code> made the trick. 
Also, I saw you linked the Yakkety package and I've installed it and it doesn't present this issue (I manually erased the .desktop file prior to installing this version.
Thanks for the help, pbek.

**Comment by pbek** [comment]
That's strange, because that deb file is the package that is supposed to be installed via apt-get... :)

**Comment by polkillas** [comment]
I found the probable cause: https://bugs.launchpad.net/ubuntu/+source/unity/+bug/1584422. It's a bug in Ubuntu, nothing to do with QOwnNotes.

**Comment by pbek** [comment]
Interesting, thank you for letting me know!
