### ISSUE TITLE
How to use checkbox markdown in tables?

### ISSUE THREAD

**Issue by lxy0797** [pbek/QOwnNotes#1790]
Hi Friends

I Want to use checkbox markdown in table like `| - [x]|` and I hope it show like 
![image](https://user-images.githubusercontent.com/31375257/84634336-3d477c80-af24-11ea-8446-f3bcf079b1d7.png)in preview. But it only shows what I typed in.
And I also  use the method said on [StackOverflow](https://stackoverflow.com/questions/47344571/how-to-draw-checkbox-or-tick-mark-in-github-markdown-table)
```| Task           | Time required | Assigned to   | Current Status | Finished | 
|----------------|---------------|---------------|----------------|-----------|
| Calendar Cache | > 5 hours  |  | in progress | - [x] ok?
| Object Cache   | > 5 hours  |  | in progress | [x] item1<br/>[ ] item2
| Object Cache   | > 5 hours  |  | in progress | <ul><li>- [x] item1</li><li>- [ ] item2</li></ul>
| Object Cache   | > 5 hours  |  | in progress | <ul><li>[x] item1</li><li>[ ] item2</li></ul>


- [x] works
- [x] works too
``` 
And it doesn't would either.

Can I use checkbox markdown in tables? And how to do that?

**Comment by pbek** [comment]
I'm sorry, checkboxes are only possible in lists and you can have lists in tables.

But you could write a script similar to https://github.com/qownnotes/scripts/blob/master/export-checkboxes/export-checkboxes.qml that translates `[x]` and `[ ]` to checkbox utf8 characters inside a table.

**Comment by lxy0797** [comment]
it's sad that such feature doesn't support.
but I will have a try on the script you commended.
thx.

**Comment by pbek** [comment]
md4c doesn't support it and it's far from every markdown "standard"...
