### ISSUE TITLE
Random Segfaults after 20.6.5 update from repo

### ISSUE THREAD

**Issue by CharlesCage** [pbek/QOwnNotes#1791]
I'm getting random segfaults today after update to 20.6.5 - OBS - build 727 (via repo).

Executable: QOwnNotes PID: 2852 Signal: Segmentation fault (11) Time: 6/15/20 15:09:14

Anyone else running into this?

**Comment by Waqar144** [comment]
Anything in Debug log? Debug info?

Did you do anything in particular that might have caused it? Is it reproducible? If so, can you share the steps to reproduce it?

**Comment by pbek** [comment]
And do you also get the seg faults if you run QOwnNotes in a new session (see https://docs.qownnotes.org/en/latest/getting-started/cli-parameters/)?

**Comment by pbek** [comment]
I will close this issue until there is more information.
