### ISSUE TITLE
Can't remove tabulator list indent with Shift + Tab

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1793]
You can't remove a tabulator list indent with `Shift + Tab`. If list indent are spaces then it works. If the setting `Use tab character instead of spaces` is set it also works.

```markdown
- level 1
	- level 2
	- <here you can't press Shift + Tab>
```

@Waqar144, is that anything you refactored in? :grin: 

## General Info

**Version**: `20.6.5`
**Build date**: `Jun 13 2020`
**Build number**: `727`
**Platform**: `linux`
**Operating System**: `KDE neon User Edition 5.19`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.9.5`
**Qt Version (runtime)**: `5.14.2`
**Portable mode**: `no`

**Comment by Waqar144** [comment]
> @Waqar144, is that anything you refactored in?

I don't think so. That part of the code hasn't been touched in a long time I think.

> If list indent are spaces then it works. If the setting Use tab character instead of spaces is set it also works.

Hmm... This is a bit difficult to understand. You mean it doesn't work, when we indent using tabs but setting `Use tab character instead of spaces` is not set?

**Comment by pbek** [comment]
> I don't think so. That part of the code hasn't been touched in a long time I think.

Yeah, I just checked.

> You mean it doesn't work, when we indent using tabs but setting Use tab character instead of spaces is not set?

By default 4 spaces will be used for indent. If you have a tab key as indent in the markdown file you cannot un-indent the list item in the example to level 1.

**Comment by pbek** [comment]
I need to check on `QMarkdownTextEdit::increaseSelectedTextIndention` later...

**Comment by pbek** [comment]
## 20.6.7
- you can now remove a tabulator list indent of a new list item with `Shift + Tab`
  if the setting `Use tab character instead of spaces` is disabled
