### ISSUE TITLE
unwanted links inside of code blocks

### ISSUE THREAD

**Issue by ryandbair** [pbek/QOwnNotes#1794]
If you are inside a code block and use syntax that looks like a markdown link, QOwnNotes will turn it into a link which is not expected behavior. 

For instance: 
```
def foo[A](a: A)
```
Turns "A" into a link to "a: A" in the current directory.

**Comment by pbek** [comment]
Confirmed, @Waqar144 anything we can do about that?

**Comment by Waqar144** [comment]
> Confirmed, @Waqar144 anything we can do about that?

It didn't turn into a link for me :thinking:

**Comment by pbek** [comment]
I got `def foo[A](file:///home/omega/ownCloud/Notes.bak/a:%20A)` in the preview...

**Comment by Waqar144** [comment]
> I got `def foo[A](file:///home/omega/ownCloud/Notes.bak/a:%20A)` in the preview...

Oh yes, I didnt look in the preview :laughing:

**Comment by pbek** [comment]
Inline code blocks have the same issue with `def foo[A](a: A)`. :grimacing:

**Comment by Waqar144** [comment]
> Inline code blocks have the same issue with `def foo[A](a: A)`. grimacing

putting a space between `[A]` and `(a: A)` is a temporary solution ;)

**Comment by pbek** [comment]
## 20.6.9
- fixed unwanted `def foo[A](a: A)` note link generation in code blocks in the preview
  (for [#1794](https://github.com/pbek/QOwnNotes/issues/1794), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by ryandbair** [comment]
Looks great. Thanks!

**Comment by pbek** [comment]
Great, thank you for testing!
