### ISSUE TITLE
Feature Request: Display Note Zoom/Magnification

### ISSUE THREAD

**Issue by vortsg** [pbek/QOwnNotes#1796]
I would be interested in the ability to see the magnification level currently set for the Note panel. I change the note size frequently. A couple of use cases are as follows:

1. I have multiple monitors of different resolutions and I move the QOwnNotes application between them and change the text size based on the monitor resolution. I have set sizes I like for each monitor, so knowing the current text size help me know how much I need to zoom in/out..
2. I present notes during web conferences. I typically need to increase my text size to present and then return it to my regular size after the web meeting.

In both scenarios I sometimes am interested in seeing my current size to know how much or if need to reset it. I see that the increase/decrease text size does not increase notes by a percentage, but what appears to be point size. If some information could be displayed in the **status bar** it would be helpful. Perhaps showing the points +/- in relation to the default font setting.

Thanks for considering my request.

A happy QOwnNotes User.

Steve G

**Comment by pbek** [comment]
We are talking about the note edit panel, right?
If you are using the shortcuts to increase, decrease or reset (to system default) the font size (there is no "zoom") it is shown in the status bar (and logged to the log panel).

**Comment by vortsg** [comment]
Thanks for the response. I did see that the font size is shown in the status panel on the left side, but only for a brief moment. I was looking for an easy way at a glance to determine the scaling level.

Steve G

**Comment by pbek** [comment]
Like I said, there is no "scaling level", just an absolute font size.
If you want to show it without modifying it you could write a custom action (that you assign a shortcut) that reads the setting and either...

1) show it permanently in the scripting panel
2) show it in a dialog
3) print it to the logging panel

https://docs.qownnotes.org/en/latest/scripting/

Let me know if you need any help.

**Comment by pbek** [comment]
I will close this issue until there is more information.
