### ISSUE TITLE
Import txt files from subfolders

### ISSUE THREAD

**Issue by marcoratto** [pbek/QOwnNotes#1799]
Hi,
I have a lot of txt files to import on QOwnNotes.
How can I do this ?
I don't found a function on the menu for importing on subfolder.

can you help me ?

thanks in advance

Marco

**Comment by pbek** [comment]
You can work with them right away, just move the subfolder into your note folder (or set this subfolder as your note folder if you so prefer).

**Comment by pbek** [comment]
I will close this issue until there is more information.
