### ISSUE TITLE
Note categorization with Notebooks/Tags

### ISSUE THREAD

**Issue by gnotaras** [pbek/QOwnNotes#18]
I'm not really familiar with the ownCloud notes app, so this feature request might be invalid, but do you have any plans to implement a way to categorize notes, for instance in notebooks (virtual directories) or support real filesystem directories or even implementing a tagging system? Are any of these supported by the ownCloud notes app API?

This is a nice project.

George

**Comment by pbek** [comment]
Thank you for your kind words, @gnotaras !
I am sorry, I had the implementation of tags on my todo-list for a long time, but as you assumed, the ownCloud Notes app doesn't support it and I wanted QOwnNotes to use simple files so everyone has direct access to their notes and isn't "locked" to QOwnNotes...
The only thing that is supported by QOwnNotes (but not by ownCloud Notes) are to use different folders, for example to archive notes...

**Comment by gnotaras** [comment]
Hi Patrizio, thanks for your reply.

> The only thing that is supported by QOwnNotes (but not by ownCloud Notes) are to use different folders, for example to archive notes...

Now I got how to use the _Set notes folder_ feature so as to categorize using real filesystem directories.

Let's hope the ownCloud app lets you implement more features in this area.

Again, thanks for your work!

George

**Comment by pbek** [comment]
@gnotaras thank you!
You can create and set an other notes folder with `Set notes folder`. There again you can store as many notes as you like. You can later jump back to your old notes folder with `Recent notes folders`.
If you *right click* on a note in the note list you can move or copy notes to other folders.
I, for example, created an `Archive` folder in my notes default notes folder. You can use the versioning and trash functionality of ownCloud in QOwnNotes for all folders if they all are beneath you ownCloud sync folder.

**Comment by gnotaras** [comment]
> Does this answer your question?

Certainly. Thanks for this information!

**Comment by pbek** [comment]
Great, I will close this issue until there are some other news.

**Comment by pbek** [comment]
And you made me start a *knowledge base* on http://www.qownnotes.org/Knowledge-base :)

**Comment by gnotaras** [comment]
That's great! Knowledge bases are always a good idea! :)
