### ISSUE TITLE
block quote

### ISSUE THREAD

**Issue by LionelR** [pbek/QOwnNotes#180]
Enhancement : Change the "Insert a block code" action from surrounding the text with a simple back thick to surrounding with three back-ticks, as it keeps new line formatting.

**Comment by pbek** [comment]
actually there are two types of code blocks

## first
`inline code`

## second
```
multi line
```

QOwnNotes covers the first and you can always press the shortcut three times to get the triple-ticks.
I'm still not sure if a 2nd button + menu entry + shortcut should be created...

**Comment by LionelR** [comment]
Selecting three times the same text and clicking three times the tool button is time consuming when we have many code to insert. As a workaround, the selected text could remain selected after a button click, or set a dropdown toolbar button with default action to single tick

**Comment by pbek** [comment]
I think more like: If the last character of the selected text is a newline then use the 2nd method. That sounds like a reasonable assumption to me.

**Comment by LionelR** [comment]
Great idea

**Comment by pbek** [comment]
In the future version 16.05.20:

- the `insert code block` command will now automatically use a multi-line 
  code block instead of an inline code block if a newline character is found in 
  the selected text

**Comment by pbek** [comment]
The version is now released, can you please report back if it works for you?

**Comment by LionelR** [comment]
It's perfect

**Comment by pbek** [comment]
Great, thank you ;)
