### ISSUE TITLE
Feature request : customizing the frequency of the updates

### ISSUE THREAD

**Issue by OlivierHobbes** [pbek/QOwnNotes#1800]
QON is awesome and suits most of my needs very well. 
Updates are very frequent, it is a great thing, but i'm a little annoyed by the update pop-up each time (or almost) I open the app.

I know I can disable this dialog, but it could be nice to have an option to choose the frequency. For example once a week, or once a month.

**Comment by pbek** [comment]
Thank you. :grin: 
I don't know on which operating system you are on, but if it's macOS or Windows there are package managers like https://brew.sh/ and https://chocolatey.org/ if you want to have more control over update frequency. QOwnNotes is available on both of them.

**Comment by OlivierHobbes** [comment]
I'm not sure I'm nerd enough to use chocolatey.
I will have a look on it.
