### ISSUE TITLE
[I] Custom defined Hot key for "Show Note preview panel"

### ISSUE THREAD

**Issue by ssnui** [pbek/QOwnNotes#1801]
Please paste the text from the issue assistant here. It should be already in your clipboard.

**Comment by ssnui** [comment]
#### Expected behaviour

When press the custom hot key, the preview panel shows

#### Actual behaviour

Nothing happened

#### Steps to reproduce

Go to Settings > Short cut and define the hot key for Show Preview Panel then save. After that when you press the defined hot key, nothing happened. My hot key is Ctl-Alt-V if that helps. It's used to work in early version 20.3.x.

**Comment by pbek** [comment]
Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting `Debug` in `Options`).

**Comment by pbek** [comment]
I will close this issue until there is more information.
