### ISSUE TITLE
Heading with hash <-> use a hashtag in the Note

### ISSUE THREAD

**Issue by svenson26** [pbek/QOwnNotes#1802]
In Markdown you use the hash for the headline. Like this:

`# headline`
`#no headline`

There must be a space between the hash and the headline. 
I use hashtags to tag the notes (1Writer on the iPhone uses also  hashtags to tag the Notes). 
But when use hashtag like #tag in Qownnotes, Qownnotes make a headline in the preview. 

Is this a bug oder feature? 

![Image 3](https://user-images.githubusercontent.com/67114383/85553949-fc322500-b613-11ea-95bf-80193761f2e0.png)

**Comment by pbek** [comment]
@Waqar144, is md4c rendering it this way?

**Comment by Waqar144** [comment]
> @Waqar144, is md4c rendering it this way?

Yes, We can disable it if we take out the permissive atx headers flag.

**Comment by pbek** [comment]
Does removing this flag have any other side-effects? If no, can you please remove it?

**Comment by Waqar144** [comment]
> Does removing this flag have any other side-effects? If no, can you please remove it?

Nopes,
Killing it now. :grin

**Comment by pbek** [comment]
## 20.6.10
- incorrect headings like `#headline` will now not be rendered as heading in the preview
 (for [#1802](https://github.com/pbek/QOwnNotes/issues/1802), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by svenson26** [comment]
Works great. It does what it's supposed to.
You guys are really fast. 
Thank you!!

**Comment by pbek** [comment]
Great, thank you for testing!
