### ISSUE TITLE
Quick switch to preview in the distraction free mode

### ISSUE THREAD

**Issue by stevenfang1997** [pbek/QOwnNotes#1804]
Moin moin!

#### Expected behaviour
A quick switch to view the preview of the note in the distraction free mode, so that you just need to click one button to switch between note text and preview. Like this as long as ignoring the toolbar:
![Screenshot_20200625_162035](https://user-images.githubusercontent.com/37974764/85667060-85268a80-b700-11ea-8e21-3fed03ca360c.png)

#### Actual behaviour
You have to either create a new workspace like I did, or quit the distraction free mode then use "open note in different window". "Open note in different window" allows you to quickly switch between note text and preview, but you can't edit either of them.

#### Suggestion
The new distraction free mode should merge the current distraction free mode and "open note in different window" which improves the user friendliness.

**Comment by pbek** [comment]
Wouldn't just pressing `Alt + Shift + O` in the DFM solve that if the *Note in new window dialog* would remember that is was switched to *Preview* last time. You can close that dialog with `Escape`.

**Comment by pbek** [comment]
> Do you mean switch back to the previous workspace?

No, you can't really use workspaces in the distraction free mode (DFM). I'm talking about just opening the *Open note in new window dialog* in the DFM (`Alt + Shift + O` by default, you can customize that shortcut).

> I'm using the latest AUR version and it doesn't register any shortcut by default. So Alt + Shift + O in the DFM just doesn't do anything.

No Shortcuts at all? Are you hit by #1708?

**Comment by stevenfang1997** [comment]
No shortcut at all for me. I'm on Manjaro KDE using the latest version. I think I have to click "reset to default shortcut" under settings to register default shortcuts.

**Comment by pbek** [comment]
see #1708

**Comment by pbek** [comment]
## 20.6.10
- the note tabs will now be hidden in distraction free mode
- the *Note dialog* for opening notes in a new window now remembers whether it
  showed the note text or the preview last time so you can use the dialog as
  preview in the *Distraction free mode*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by stevenfang1997** [comment]
Danke schön für das schnellen Update. Yes it works for me. It's not what I originally expected, but it's a acceptable workaround.

**Comment by pbek** [comment]
You shouldn't get distracted in the *Distraction free mode* anyway. :grin: 
Thank you for testing!
