### ISSUE TITLE
Preview in open note in different window doesn't follow the font setting

### ISSUE THREAD

**Issue by stevenfang1997** [pbek/QOwnNotes#1806]
#### Expected behaviour
I have disabled "use editor highlighting styles also for the preview" in settings so that I can set a new font for preview (Noto Serif) in settings. I expected preview in "open note in different window" also follows my preview font.

#### Actual behaviour
Preview in "open note in different window" only uses Noto Sans font which is the default editor font.

Tested it on Manjaro KDE.

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
## 20.6.11
- the *Note dialog* for opening notes in a new window can now also use custom
  preview fonts

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by stevenfang1997** [comment]
Yes it works! Thanks a lot for the quick fix!

**Comment by pbek** [comment]
Great, thank you for testing!
