### ISSUE TITLE
Feature request: make adding gentoo overlay easier

### ISSUE THREAD

**Issue by barolo** [pbek/QOwnNotes#1807]
Consider adding qownnotes-overlay to official gentoo repository list so it can be easily added via [eselect-repository](https://wiki.gentoo.org/wiki/Eselect/Repository) [ "eselect repository enable qownnotes-overlay" ]

**Comment by pbek** [comment]
I suggestions on how to do that or any work you can do in that regard?

**Comment by barolo** [comment]
Just request it [here](https://bugs.gentoo.org/enter_bug.cgi?product=Gentoo+Infrastructure&component=Gentoo+Overlays&short_desc=Add+repository:+NAME&comment=description:+%0ahomepage:+%0aowner:+%0asources:+%0afeeds:+%0a) [ you will need an account ], you can just attach repository/overlay.xml and they'll copy it over

**Comment by pbek** [comment]
And I can keep publishing to https://github.com/pbek/qownnotes-overlay?

**Comment by barolo** [comment]
> And I can keep publishing to https://github.com/pbek/qownnotes-overlay?

Yes

**Comment by pbek** [comment]
First I moved the repo to https://github.com/qownnotes/gentoo-overlay and then reported it here: https://bugs.gentoo.org/729970

**Comment by pbek** [comment]
How will the process then be to install QOwnNotes (so I later can update https://www.qownnotes.org/installation#Gentoo)?

**Comment by barolo** [comment]
user needs eselect-repository installed, then just do:
`eselect repository enable qownnotes-overlay`

that's all

**Comment by pbek** [comment]
Thank you! :grin:

**Comment by barolo** [comment]
@pbek renaming it to gentoo-overlay was unnecessary, it might be a problem even

**Comment by pbek** [comment]
A problem in what way?

**Comment by barolo** [comment]
I'm not knowledgeable enough to be certain but I think that overlay should have a distinct name, otherwise it might be confused with the main gentoo overlay.
Guys at gentoo's bugzilla will know better either way

**Comment by pbek** [comment]
The name of the overlay didn't change, only its git repository.

**Comment by barolo** [comment]
Oh, should be fine then

**Comment by pbek** [comment]
The repository is now added, can you please test if the installation works.

**Comment by pbek** [comment]
https://www.qownnotes.org/installation#Gentoo and https://github.com/qownnotes/gentoo-overlay/ were updated accordingly.

**Comment by barolo** [comment]
Great! Tested and it works. I think that you should add sudo to the commands as it's required 

```
sudo eselect repository enable qownnotes-overlay
sudo emerge --sync qownnotes-overlay && sudo emerge -av qownnotes 
```

mentioning [eselect-repository](https://wiki.gentoo.org/wiki/Eselect/Repository) might be usefull, as some might need to get up to date

**Comment by pbek** [comment]
Great, thank you for testing and the information!
