### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by Aquarian-Age** [pbek/QOwnNotes#1808]
Use KDE desktop environment
After upgrading from openSUSE 15.1 to 15.2, the following error occurs
After upgrading to Tumbleweed, I still get the same error

#### Steps to reproduce
liangzi@xuan 15 13:45 >./QOwnNotes
./QOwnNotes: symbol lookup error: /usr/lib64/qt5/plugins/sqldrivers/libqsqlite.so: undefined symbol: sqlite3_column_table_name16
~
liangzi@xuan 16 13:45 >/usr/bin/QOwnNotes
/usr/bin/QOwnNotes: symbol lookup error: /usr/lib64/qt5/plugins/sqldrivers/libqsqlite.so: undefined symbol: sqlite3_column_table_name16
~
liangzi@xuan 17 13:45 >QOwnNotes
QOwnNotes: symbol lookup error: /usr/lib64/qt5/plugins/sqldrivers/libqsqlite.so: undefined symbol: sqlite3_column_table_name16
~

liangzi@xuan 21 13:50 >ldd /usr/bin/QOwnNotes
```
        linux-vdso.so.1 (0x00007ffe11902000)
        libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007f08c7ada000)
        libQt5PrintSupport.so.5 => /usr/lib64/libQt5PrintSupport.so.5 (0x00007f08c7a6a000)
        libQt5Widgets.so.5 => /usr/lib64/libQt5Widgets.so.5 (0x00007f08c73c7000)
        libQt5X11Extras.so.5 => /usr/lib64/libQt5X11Extras.so.5 (0x00007f08c73c0000)
        libQt5Gui.so.5 => /usr/lib64/libQt5Gui.so.5 (0x00007f08c6cd0000)
        libQt5Sql.so.5 => /usr/lib64/libQt5Sql.so.5 (0x00007f08c6c92000)
        libQt5XmlPatterns.so.5 => /usr/lib64/libQt5XmlPatterns.so.5 (0x00007f08c69a1000)
        libQt5Qml.so.5 => /usr/lib64/libQt5Qml.so.5 (0x00007f08c653c000)
        libQt5WebSockets.so.5 => /usr/lib64/libQt5WebSockets.so.5 (0x00007f08c6512000)
        libQt5Network.so.5 => /usr/lib64/libQt5Network.so.5 (0x00007f08c6386000)
        libQt5Xml.so.5 => /usr/lib64/libQt5Xml.so.5 (0x00007f08c6341000)
        libQt5Core.so.5 => /usr/lib64/libQt5Core.so.5 (0x00007f08c5da0000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f08c5bc8000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f08c5bae000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f08c59e7000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f08c81e6000)
        libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007f08c59bc000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f08c59b6000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f08c5994000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f08c584d000)
        libGL.so.1 => /usr/lib64/libGL.so.1 (0x00007f08c57b4000)
        libpng16.so.16 => /usr/lib64/libpng16.so.16 (0x00007f08c576b000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f08c5751000)
        libharfbuzz.so.0 => /usr/lib64/libharfbuzz.so.0 (0x00007f08c5680000)
        libproxy.so.1 => /usr/lib64/libproxy.so.1 (0x00007f08c5660000)
        libssl.so.1.1 => /usr/lib64/libssl.so.1.1 (0x00007f08c55c9000)
        libcrypto.so.1.1 => /usr/lib64/libcrypto.so.1.1 (0x00007f08c52db000)
        libsystemd.so.0 => /usr/lib64/libsystemd.so.0 (0x00007f08c522d000)
        libdouble-conversion.so.3 => /usr/lib64/libdouble-conversion.so.3 (0x00007f08c521c000)
        libicui18n.so.67 => /usr/lib64/libicui18n.so.67 (0x00007f08c4f0f000)
        libicuuc.so.67 => /usr/lib64/libicuuc.so.67 (0x00007f08c4d23000)
        libpcre2-16.so.0 => /usr/lib64/libpcre2-16.so.0 (0x00007f08c4c78000)
        libzstd.so.1 => /usr/lib64/libzstd.so.1 (0x00007f08c4ba3000)
        libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0 (0x00007f08c4a78000)
        libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007f08c4a73000)
        libGLX.so.0 => /usr/lib64/libGLX.so.0 (0x00007f08c4a3f000)
        libGLdispatch.so.0 => /usr/lib64/libGLdispatch.so.0 (0x00007f08c4981000)
        libfreetype.so.6 => /usr/lib64/libfreetype.so.6 (0x00007f08c48bd000)
        libgraphite2.so.3 => /usr/lib64/libgraphite2.so.3 (0x00007f08c489c000)
        libmodman.so.1 => /usr/lib64/libmodman.so.1 (0x00007f08c4892000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f08c4887000)
        liblzma.so.5 => /usr/lib64/liblzma.so.5 (0x00007f08c4852000)
        liblz4.so.1 => /usr/lib64/liblz4.so.1 (0x00007f08c4831000)
        libgcrypt.so.20 => /usr/lib64/libgcrypt.so.20 (0x00007f08c470a000)
        libicudata.so.67 => /usr/lib64/libicudata.so.67 (0x00007f08c4707000)
        libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007f08c4678000)
        libbz2.so.1 => /usr/lib64/libbz2.so.1 (0x00007f08c4655000)
        libbrotlidec.so.1 => /usr/lib64/libbrotlidec.so.1 (0x00007f08c4647000)
        libgpg-error.so.0 => /usr/lib64/libgpg-error.so.0 (0x00007f08c4622000)
        libbrotlicommon.so.1 => /usr/lib64/libbrotlicommon.so.1 (0x00007f08c45ff000)
```

**Comment by pbek** [comment]
Did you also use the QOwnNotes repositories for *openSUSE Leap 15.2* and *openSUSE Tumbleweed* after your OS upgrade?

**Comment by pbek** [comment]
see: https://www.qownnotes.org/installation

**Comment by Aquarian-Age** [comment]
> Did you also use the QOwnNotes repositories for _openSUSE Leap 15.2_ and _openSUSE Tumbleweed_ after your OS upgrade?

yes

liangzi@xuan 14 14:23 >cat /etc/zypp/repos.d/home\ pbek\ QOwnNotes.repo 

```
[home_pbek_QOwnNotes]
name=QOwnNotes (openSUSE_Tumbleweed)
type=rpm-md
baseurl=https://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/openSUSE_Tumbleweed/
gpgcheck=1
gpgkey=https://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/openSUSE_Tumbleweed/repodata/repomd.xml.key
enabled=1
```

**Comment by pbek** [comment]
I can't say I've seen that problem yet. The openSUSE repositories are built with Open Build Service from openSUSE. 

Are the sqlite libraries installed?  
Are the Qt sqlite libraries installed?
Are you maybe hit by something like https://stackoverflow.com/questions/53969202/qtcreator-undefined-symbol-sqlite3-column-table-name16?

**Comment by Aquarian-Age** [comment]
> I can't say I've seen that problem yet. The openSUSE repositories are built with the Open Build Service from openSUSE.
> 
> Are the sqlite libraries installed?
> Are the Qt sqlite libraries installed?
> Are you maybe hit by something like https://stackoverflow.com/questions/53969202/qtcreator-undefined-symbol-sqlite3-column-table-name16?

```
liangzi@xuan 2 14:28 >zypper se -i sqlite

+ | akonadi-server-sqlite | akonadi server's SQlite plugin  
i+ | kdb-sqlite3-driver    | Database connectivity and creation framework - SQLite3 driver
i  | libQt5Sql5-sqlite     | Qt 5 sqlite plugin                                    
i  | libsqlite3-0          | Shared libraries for the Embeddable SQL Database Engine    
i+ | libsqlite3-0-32bit    | Shared libraries for the Embeddable SQL Database Engine     
i+ | perl-DBD-SQLite       | Self-contained RDBMS in a DBI Driver                     
i+ | php7-sqlite           | SQLite database client for PHP                          
i+ | sqlite3-devel         | Embeddable SQL Database Engine                           

```

**Comment by pbek** [comment]
Really strange. I can't even do much about how it's built on https://build.opensuse.org/package/show/home:pbek:QOwnNotes/desktop, beside the configuration like https://build.opensuse.org/package/view_file/home:pbek:QOwnNotes/desktop/qownnotes.spec?expand=1 where the sqlite libraries are included...

**Comment by pbek** [comment]
And it seems there were no troubles building:
https://build.opensuse.org/package/live_build_log/home:pbek:QOwnNotes/desktop/openSUSE_Tumbleweed/x86_64

**Comment by pbek** [comment]
@euneuber, have you seen anything like this?

**Comment by Aquarian-Age** [comment]
> Really strange. I can't even do much about how it's built on https://build.opensuse.org/package/show/home:pbek:QOwnNotes/desktop, beside the configuration like https://build.opensuse.org/package/view_file/home:pbek:QOwnNotes/desktop/qownnotes.spec?expand=1 where the sqlite libraries are included...

It may be that my local KDE environment has problems after upgrading😂

**Comment by Aquarian-Age** [comment]
Found the cause of the problem
As the link says 　https://stackoverflow.com/questions/53969202/qtcreator-undefined-symbol-sqlite3-column-table-name16　

liangzi@xuan 54 21:11 >/sbin/ldconfig -p|grep "/usr/local"| grep sqlite
        libsqlite3.so.0 (libc6,x86-64) => /usr/local/lib64/libsqlite3.so.0
        libsqlite3.so (libc6, x86-64) => /usr/local/lib64/libsqlite3.so
liangzi@xuan 61 21:14 >file /etc/ld.so.cache
/etc/ld.so.cache: Apple DiskCopy 4.2 image d.so-1.7.0, 50528256 bytes, 0x6ea50100 tag size, 0xa5 encoding, 0xa5 format

liangzi@xuan 67 21:17 >cat /etc/ld.so.conf
```text
### libsqlite3.so
# /usr/local/lib64
# /usr/local/lib
/root/lib/
include /etc/ld.so.conf.d/*.conf
# /lib64, /lib, /usr/lib64 and /usr/lib gets added
# automatically by ldconfig after parsing this file.
# So, they do not need to be listed.

```

sudo /sbin/ldconfig -f /etc/ld.so.conf

liangzi@xuan 64 21:14 >file /etc/ld.so.cache
/etc/ld.so.cache: Apple DiskCopy 4.2 image d.so-1.7.0, 50528256 bytes, 0x56990100 tag size, 0x8d encoding, 0x99 format

**Comment by pbek** [comment]
:grin:
