### ISSUE TITLE
Problem with tables

### ISSUE THREAD

**Issue by svenson26** [pbek/QOwnNotes#1809]
Hi, i have a at the moment problems with tables in the preview. Last week it works but now it doesn't show me the table in the preview.
In Typora it shows me the table.

Any idea?

### qownnotes
![Image 1](https://user-images.githubusercontent.com/67114383/85944162-42dd9300-b924-11ea-8374-e8d684533dad.jpg)

### typora
![Image 2](https://user-images.githubusercontent.com/67114383/85944163-440ec000-b924-11ea-8ccb-63f904f894a8.jpg)

**Comment by pbek** [comment]
No issue here:

![image](https://user-images.githubusercontent.com/1798101/85944355-6578a780-b936-11ea-9ee9-eae0bce89fa3.png)

Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting `Debug` in `Options`).

**Comment by pbek** [comment]
And I see the table in your screenshot, there just are no table-borders...
Maybe try this setting:

![image](https://user-images.githubusercontent.com/1798101/85944446-12ebbb00-b937-11ea-8082-266fedf8752c.png)

**Comment by svenson26** [comment]
> 
> 
> And I see the table in your screenshot, there just are no table-borders...
> Maybe try this setting:
> 
> ![image](https://user-images.githubusercontent.com/1798101/85944446-12ebbb00-b937-11ea-8082-266fedf8752c.png)

Thanks for the fast reponse.
- same problem with this activated option
- log panel doesn't show any helpful output

[Output Debug Setting](https://bin.disroot.org/?b2b14cb16eb5f323#DMfgPNtkTme6p3RrrtcN11gb9GMCKmxy95fYQgmGrneW)

**Comment by pbek** [comment]
Can't see anything unusual.
Can you please export the html of your preview (right click on the preview).

**Comment by svenson26** [comment]
Sure:

[HTML](https://bin.disroot.org/?4fa2db0e54241183#8Au57XYBTu1VEtpJXeip8P8anbJxPR7fPML466aGkYr8)

**Comment by svenson26** [comment]
<html><head><style>h1 { margin: 5px 0 20px 0; }h2, h3 { margin: 10px 0 15px 0; }table {border-spacing: 0; border-style: solid; border-width: 1px; border-collapse: collapse; margin-top: 0.5em;}th, td {padding: 2px 5px;}a { color: <b><font color="purple">FF9137</font></b>; text-decoration: none; } pre, code { font-family: "Courier New";  }pre { display: block; background-color: <b><font color="purple">f1f1f1</font></b> } code { padding: 3px; overflow: auto; line-height: 1.45em; background-color: <b><font color="purple">f1f1f1</font></b>; border-radius: 5px; color: <b><font color="purple">000000</font></b>; } .code-comment { color: <b><font color="purple">75715E</font></b>; font-style: italic;} .code-string { color: <b><font color="purple">E6DB74</font></b>;} .code-literal { color: <b><font color="purple">AE81FF</font></b>;} .code-type { color: <b><font color="purple">66D9EF</font></b>;} .code-builtin { color: <b><font color="purple">A6E22E</font></b>;} .code-keyword { color: <b><font color="purple">F92672</font></b>;} .code-other { color: <b><font color="purple">F92672</font></b>;}  </style></head><body class="preview"><h1>test</h1>
<table>
<thead>
<tr>
<th>1</th>
<th>2</th>
<th>3</th>
</tr>
</thead>
<tbody>
<tr>
<td>4</td>
<td>5</td>
<td>6</td>
</tr>
<tr>
<td>7</td>
<td>8</td>
<td>9</td>
</tr>
</tbody>
</table>
</body></html>

**Comment by pbek** [comment]
The html code looks ok and I cannot reproduce your issue under Windows neither...

**Comment by pbek** [comment]
What happens if you start QOwnNotes in a new session? See: https://docs.qownnotes.org/en/latest/getting-started/cli-parameters/

**Comment by svenson26** [comment]
> 
> 
> What happens if you start QOwnNotes in a new session? See: https://docs.qownnotes.org/en/latest/getting-started/cli-parameters/

Sorry for the late response. Thats it. Starting a new session the table works. 
So it must be a setting problem, but which setting?

**Comment by pbek** [comment]
I can't tell... Try to get everything running like you used to have it until it breaks. 😁  I'm very curious what can such an effect on the QTextBrowser...

**Comment by svenson26** [comment]
> 
> 
> I can't tell... Try to get everything running like you used to have it until it breaks. 😁 I'm very curious what can have such an effect on the QTextBrowser...

So, now I've export my setting, delete all settings and import all my exported settings again to qownnotes.
Suprise Surprise. Don't ask why 
![Image 1](https://user-images.githubusercontent.com/67114383/86026059-7c92c480-ba1e-11ea-910b-d72e17a02704.png)

**Comment by svenson26** [comment]
I got it. Its a Script that breaks the table. Its the @tag tagging in note text Script.

**Comment by pbek** [comment]
But you didn't even use a tag in your note, did you?

**Comment by svenson26** [comment]
> But you didn't even use a tag in your note, did you?

No i didn‘t use a tag in the note. It is sufficient to use a # as marker for a tag.  So in the script that # as a marker for a tag is enough.  You don't even need to tag the note
