### ISSUE TITLE
Wrong display for block code in list

### ISSUE THREAD

**Issue by LionelR** [pbek/QOwnNotes#181]
In the display pane, if the first string is a back tick immediately after a list entry point, the entry point is displayed as a block code with monospace font.
![capture du 2016-05-24 11 21 11](https://cloud.githubusercontent.com/assets/490118/15498871/bc254a24-21a1-11e6-872b-c25fbe3aa62f.png)

**Comment by pbek** [comment]
Thank you for reporting. I was already aware of that, it's a bug in the QTextEdit and I didn't find a workaround for it. It's already on my list to check when we have a fully fledged browser component as preview (which is currently not very feasible).

**Comment by pbek** [comment]
I will report back to this issue when it's possible to fix it.
