### ISSUE TITLE
Underline format shortcut

### ISSUE THREAD

**Issue by RichardBaker3020** [pbek/QOwnNotes#1811]
It seems that there is no shortcut for __underline__ format: `__underline__` , wonder if that could be added in next version. Really appreceate your excellent work :)

**Comment by pbek** [comment]
Thank you for your suggestion. Do you have a recommendation for the keyboard shortcut?

**Comment by pbek** [comment]
<kbd>Ctrl</kbd> + <kbd>U</kbd> is free...

**Comment by pbek** [comment]
## 20.7.0
- you can now press <kbd>Ctrl</kbd> + <kbd>U</kbd> to format the selected text underline

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by RichardBaker3020** [comment]
> There now is a new release, could you please test it and report if it works for you?

Just tested the latest release and shortcut works fine for me, thank you for your work:)

**Comment by pbek** [comment]
Great, thank you for testing!
