### ISSUE TITLE
Export to pdf view - image black/grey

### ISSUE THREAD

**Issue by 00tiagopolicarpo00** [pbek/QOwnNotes#1812]
Code my.md
# <center> Text Center </center>

#### Other Someting
*  Text free
* ![qownnotes-media-vxwSSl](../media/qownnotes-media-vxwSSl-181833458.png)

End Code my.md

QOwnNotes - version 20.6.11 - OBS - build 733 (deb)

When i export  to pdf view the image (color), stay black/gray, if use the export on Okular is work fine.

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Can you please post the output from the debug settings (see issue template).
Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting `Debug` in `Options`).

And can you please post a screenshot of what is seen and the markdown of your note along with the image.

**Comment by 00tiagopolicarpo00** [comment]
[qo.txt](https://github.com/pbek/QOwnNotes/files/4866215/qo.txt)

**Comment by 00tiagopolicarpo00** [comment]
![Screenshot_20200702_202051](https://user-images.githubusercontent.com/23580329/86401082-8ed06500-bca1-11ea-9491-2fffeea51d4b.png)

**Comment by 00tiagopolicarpo00** [comment]
[Note 2020-07-02T20.18.29.pdf](https://github.com/pbek/QOwnNotes/files/4866231/Note.2020-07-02T20.18.29.pdf)

**Comment by pbek** [comment]
I still don't know where you are working on (since you didn't fill out the issue template completely), but it seems you have set your printing (export is near to printing) to gray-scale in your operating system.

**Comment by 00tiagopolicarpo00** [comment]
[jul 02 20:34:27] [warning]: "Warning: noteToMarkdownHtmlHook(note, html) is deprecated, please use noteToMarkdownHtmlHook(note, html, forExport) in YAML nested tags"
[jul 02 20:34:27] [warning]: "Warning: noteToMarkdownHtmlHook(note, html) is deprecated, please use noteToMarkdownHtmlHook(note, html, forExport) in YAML tags (Epsilon Notes compatible)"
[jul 02 20:34:43] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"https://myweb.local" <username>"user01" <priority>1
[jul 02 20:34:43] [warning]: "Warning: noteToMarkdownHtmlHook(note, html) is deprecated, please use noteToMarkdownHtmlHook(note, html, forExport) in YAML nested tags"
[jul 02 20:34:43] [warning]: "Warning: noteToMarkdownHtmlHook(note, html) is deprecated, please use noteToMarkdownHtmlHook(note, html, forExport) in YAML tags (Epsilon Notes compatible)"
[jul 02 20:34:48] [warning]: "Could not enter folder tags:/."
[jul 02 20:34:48] [warning]: No node found for item that was just removed: QUrl("file:///home/user/Downloads/Tmp1/preview.html")

**Comment by pbek** [comment]
> [jul 02 20:34:27] [warning]: "Warning: noteToMarkdownHtmlHook(note, html) is deprecated, please use noteToMarkdownHtmlHook(note, html, forExport) in YAML nested tags"

update your scripts in the script repository :wink:

**Comment by 00tiagopolicarpo00** [comment]
I just update now, but pdf is equal.
output export pdf previewer:
[jul 02 20:42:11] [warning]: "Could not enter folder tags:/."
[jul 02 20:42:11] [warning]: No node found for item that was just removed: QUrl("file:///home/user/Downloads/Tmp1/preview.html")

My printer system, i have one print on my system the driver is RAW.

**Comment by pbek** [comment]
> I just update now, but pdf is equal.

Has nothing to do with the pdf... just so the warning so I mentioned it. :wink:

**Comment by pbek** [comment]
> [jul 02 20:42:11] [warning]: "Could not enter folder tags:/."
> [jul 02 20:42:11] [warning]: No node found for item that was just removed: QUrl("file:///home/user/Downloads/Tmp1/preview.html")

have no idea about those two...

**Comment by pbek** [comment]
> My printer system, i have one print on my system the driver is RAW.

something seems to force our output to grayscale...
what happens if you don't export, but print and use a pdf-printer to print to

**Comment by 00tiagopolicarpo00** [comment]
> > My printer system, i have one print on my system the driver is RAW.
> 
> something seems to force our output to grayscale...
> what happens if you don't export, but print and use a pdf-printer to print to

If print the color show on image.
[printtest.pdf](https://github.com/pbek/QOwnNotes/files/4866409/printtest.pdf)

Tks for helping

**Comment by pbek** [comment]
Great. I still wonder what if forcing the grayscale on your system, please let me know if you ever find out :wink: At least there's a working way now...
