### ISSUE TITLE
Note tab context menu

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1814]
It would be great to have a context menu for the note tabs from #1720.

**Comment by pbek** [comment]
@sanderboom, @Airgunster, @tragtragtrag

I finally found a way to make that happen...

## 20.7.1
- there now is a context menu for note tabs which allows you to toggle the note stickiness
  and to close all other note tabs

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by sanderboom** [comment]
Awesome!

> I finally found a way to make that happen...

What kind of dark magic did you have to summon for this? :mage_man: 

Does this also mean that https://github.com/pbek/QOwnNotes/issues/1754 will happen? 

[You wrote](https://github.com/pbek/QOwnNotes/issues/1754#issuecomment-630700904):
>  If you can magic up a note tab context menu I will implement it there.

:wink:

**Comment by pbek** [comment]
> What kind of dark magic did you have to summon for this? mage_man

Write my own event handling and coordinate checking where on the screen there was the click.

> Does this also mean that #1754 will happen?

Do you need still need that in the context menu? it's currently in the note list context menu and on clicking of the current note tab.

**Comment by tragtragtrag** [comment]
> @sanderboom, @Airgunster, @tragtragtrag
> 
> I finally found a way to make that happen...
> 
> ## 20.7.1
> * there now is a context menu for note tabs which allows you to toggle the note stickiness
>   and to close all other note tabs

Thank you! It seems to work perfectly. This is, again, an improvement for me! :) Now I'm only waiting for the extension of the tabs to double/triple/... rows.... :)

**Comment by sanderboom** [comment]
> Do you need still need that in the context menu? it's currently in the note list context menu and on clicking of the current note tab.

I never found that clicking the current note tab switches the Subfolders and Note list panel as I assumed you meant left-click, but I just found out that a right-click does indeed switch the panels! Just to be sure: this is how you've implemented it?

**Comment by pbek** [comment]
> Now I'm only waiting for the extension of the tabs to double/triple/... rows.... :)

Most likely not going to happen. :grimacing:

**Comment by pbek** [comment]
> I never found that clicking the current note tab switches the Subfolders and Note list panel as I assumed you meant left-click, but I just found out that a right-click does indeed switch the panels! Just to be sure: this is how you've implemented it?

A left click on the active note always changes the sub-folder for me.

I want to avoid duplicating the note list context menu in the note tab context menu...

**Comment by sanderboom** [comment]
> A left click on the active note tab always changes the sub-folder for me.

How is it possible that for me this only happens on right-click :thinking:

**Comment by pbek** [comment]
Strange
