### ISSUE TITLE
Text color of “unspecified string” on Japanese input method is too pale to read

### ISSUE THREAD

**Issue by suzusime** [pbek/QOwnNotes#1815]
#### Actual behaviour

To write Japanese text, many Japanese people (including me) use Japanese input method softwares which execute [kana-to-kanji conversion](https://en.wikipedia.org/wiki/Japanese_input_method#Kana_to_kanji_conversion). 

The process of kana-to-kanji conversion is (as I know):

1. Type kana spelling (representing the pronunciation) 
2. Select kanji text (disired text) from list
3. Finish

After stage 3, kanji text (disired text) are input to the text area and treated the same as normal Latin text.
In stage 1 or 2, however, the text are in an unique status called “unspecified string”(未確定文字列).

The problem is that in QOwnNotes (on Windows 10) text in stage 2 are displayed in pale grey and difficult to read.

QOwnNotes and Microsoft IME:
![qown_msime](https://user-images.githubusercontent.com/12910196/86504112-ea106d80-bdef-11ea-8596-83b44b3caae8.gif)

QOwnNotes and [SKKFEP](http://coexe.web.fc2.com/skkfep.html):
![qown_skkfep](https://user-images.githubusercontent.com/12910196/86504118-f694c600-bdef-11ea-9c78-1c066288dbc4.gif)

(I use Windows and don't know the behavior on other OSs.)

#### Expected behaviour

Could you display the text in the same color as normal text or add option to select color of the text on color theme settings?

For example, I will show the behaviour on Windows Notepad below.

Notepad and Microsoft IME:
![notepad_msime](https://user-images.githubusercontent.com/12910196/86504123-01e7f180-bdf0-11ea-8166-4e41fc3d7a6f.gif)

Notepad and [SKKFEP](http://coexe.web.fc2.com/skkfep.html):
![notepad_skkfep](https://user-images.githubusercontent.com/12910196/86504130-0b715980-bdf0-11ea-997f-2d105a274e49.gif)

#### Steps to reproduce

Type Japanese text using kana-to-kanji conversion systems on Windows 10.

**Comment by pbek** [comment]
I'm not sure what is causing this. Can you please try to turn off highlighting in the *Editor settings* to see if it is caused by the highlighter. There should be no coloring at all then.

**Comment by pbek** [comment]
And can you please post the output from the debug settings (see issue template).

**Comment by suzusime** [comment]
Turning **on** "Enable Markdown highlighting" and turning **on** "Highlight the current line" (as I showed above):
![qown_msime5](https://user-images.githubusercontent.com/12910196/86507349-98c5a580-be12-11ea-8f45-cec31a39e36d.gif)

Turning **on** "Enable Markdown highlighting" and turning **off** "Highlight the current line":
![qown_msime4](https://user-images.githubusercontent.com/12910196/86507377-bb57be80-be12-11ea-835f-e23fe4a6859f.gif)

Turning **off** "Enable Markdown highlighting" and turning **on** "Highlight the current line":
![qown_msime2](https://user-images.githubusercontent.com/12910196/86507096-674bda80-be10-11ea-9bc5-f460698f2b31.gif)

Turning **off** "Enable Markdown highlighting" and turning **off** "Highlight the current line":
![qown_msime3](https://user-images.githubusercontent.com/12910196/86507190-2ef8cc00-be11-11ea-8e17-252ded270f9d.gif)

<hr>

So, this issue appears to relate to "**Highlight the current line**" feature.

The debug log of the time when I typed text (with turning **off** "Enable Markdown highlighting" and turning **on** "Highlight the current line") is shown below (however, I think there is no information about the issue).

<details><summary>Expand</summary>
<pre>
[16:28:35] [debug] cloudConnection: CloudConnection: <id>1 <name>"****" <serverUrl>"https://****" <username>"****" <priority>1
[16:28:37] [debug] cloudConnection: CloudConnection: <id>1 <name>"****" <serverUrl>"https://****" <username>"****" <priority>1
[16:28:39] [debug] storing note file: "Test text.md"
[16:28:39] [debug] stored note: Note: <id>2 <name>"Test text" <fileName>"Test text.md" <noteSubFolderId>1 <relativePath>"_zatsu" <hasDirtyData>false
[16:28:39] [debug] storeUpdatedNotesToDisk - 'count': 1
[16:28:39] [status] Stored 1 note(s) to disk
</pre>
</details>

**Comment by suzusime** [comment]
I think this pale text color is for black background (as with turning off "Highlight the current line"), but in QOwnNotes with turning on "Highlight the current line" the feature to make the background black is disabled.

**Comment by pbek** [comment]
You can set the background color in the *Editor fonts and colors* settings. It is used then in `QOwnNotesMarkdownTextEdit::highlightCurrentLine()`.

**Comment by suzusime** [comment]
When I wrote

> making "current line background color" dark is workaround

I intended to say this setting can help :)

After the above inspection,  I understood that using themes whose current line background color is dark made no problem for me. 
However, I hope unspecified string are readable even with themes whose current line background color is light., someday.
(I know well that issues about input methods are difficult, much environment dependent, language-specific and with little information...)

**Comment by pbek** [comment]
>  I hope unspecified string are readable even with themes whose current line background color is light., someday.

If you find any support for it by the Qt framework please let me know. :wink: 

> I know well that issues about input methods are difficult, much environment dependent, language-specific and with little information...

Yes, they are. :smile:  And most of it depends on the used framework (Qt in this case).
