### ISSUE TITLE
Hide the code when note editing is disallowed

### ISSUE THREAD

**Issue by rocribera** [pbek/QOwnNotes#1816]
I'm creating some kind of documentation of things I want to do or go over. This is a note that I will rarely edit, so I disallowed editing for these notes. The code is still there, though. It would be cool if disallowing note editing would make it so the code of the note itself disappears and only the preview (so the output format) is shown. This way it's easier to read when needed.

I know it can be exported, but I'd like to read them inside the program itself. Haven't found a way to just show the preview except changing panel's size.

**Comment by pbek** [comment]
I'm sorry, the "code" you are talking about is the text that most people are relying on. :grin: It makes no sense to hide it in read-only mode. You can hide it by switching to a different workspace that doesn't show the note edit.

**Comment by pbek** [comment]
> Haven't found a way to just show the preview except changing panel's size.

You need to turn off central widget support in the *Panels settings*.

**Comment by pbek** [comment]
> Haven't found a way to just show the preview except changing panel's size.

There is a "preview only" layout in the *Layout settings*. That will also disable the central widget support.

**Comment by rocribera** [comment]
I'm not sure I understand what you're saying, or if you're understanding me. My idea is when disallowing note edit, have the option to make central panel here disappear and have the one at the right (preview) bigger so that's all there is to read.

I've found this central widget support, but I'd like to have this for individual notes, not having to change it constantly for every single one.

EDIT: I found the "preview only" and that works fine, but as I mentioned before it would be cool if it saved the view for every individual note if possible. Also, I enabled the preview only and when I went back to the "minimal" one, all my layout was different and I lost my code central panel, I'm trying to get it back but can't see where to enable it.

![image](https://user-images.githubusercontent.com/47631356/86514527-27d2bd80-be13-11ea-9c43-0b65b39346bd.png)

**Comment by rocribera** [comment]
Nevermind I fixed it, found the central panel again. Still, I guess my issue now comes down to be able to have a default workstation/layout for each note.

Also, completely off-topic, where can I see the markdown template? I've been trying to use `$\to$` to make an arrow but it's not working on here.

**Comment by pbek** [comment]
> Still, I guess my issue now comes down to be able to have a default workstation/layout for each note.

You could play with the noteopenhook https://docs.qownnotes.org/en/latest/scripting/hooks/#noteopenedhook if you really want to do this...

> Also, completely off-topic, where can I see the markdown template? 

What markdown template?

> I've been trying to use $\to$ to make an arrow but it's not working on here.

Since when is `$\to$` markdown?

**Comment by pbek** [comment]
> Still, I guess my issue now comes down to be able to have a default workstation/layout for each note.

And there also is a shortcut to switch to the last workspace if you want to define multiple workspaces (one with and one without note edit panel)...
