### ISSUE TITLE
[Q] Add a global search function to QON

### ISSUE THREAD

**Issue by yuxiacn** [pbek/QOwnNotes#1818]
#### General question

Hi, I found the search function of QON is limited. Only if I click the default whole directory can QON search all the notes.
If the focus is on one note in some subfolder, the search function only search the subfolder itself.
So can a global search function can be added and a global search button can be put on the toolbar?

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[21:10:17] [debug] updatePanelMenu - 'updatePanelMenu'
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sunday July 5 21:10:30 2020`
**Version**: `20.7.1`
**Build date**: `Jul  5 2020`
**Build number**: `735`
**Platform**: `linux`
**Operating System**: `Manjaro Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.0`
**Qt Version (runtime)**: `5.15.0`
**Portable mode**: `no`
**Settings path / key**: `/home/pop/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/pop/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `zh_CN`
**Locale (interface)**: `zh_CN`
**Primary screen resolution**: `1280x720`
**Icon theme**: `Papirus-Light`
**Notes in current note folder**: `11`
**Calendar items**: `0`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_US, en_US-large`
**Language names**: `American English (United States), American English (United States) [大]`
**Application dictionaries path**: `/home/pop/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`
</details>

**Comment by pbek** [comment]
No, but there is a mode where the notes and folders are in one panel. But that mode is still "work in progress".
