### ISSUE TITLE
QON fails to retrieve To Do Lists from Nextcloud

### ISSUE THREAD

**Issue by akwala** [pbek/QOwnNotes#1819]
In Linux (Kubuntu 18.04), QON fails to retrieve the To Do List. Log says *"QNetworkReply error 99 from url..." "Network access is disabled."* Nextcloud connection status in Settings reports "ok" for all. The To Do List is accessible from another app (Android).

From the debug log:

```
[Jul 06 21:42:00] [warning]: "QNetworkReply error 99 from url https://server.example.com/nextcloud/remote.php/dav/calendars/username: " "Network access is disabled."
[Jul 06 21:42:00] [warning]: QIODevice::read (QDisabledNetworkReply): device not open
```

**Comment by pbek** [comment]
Can you please post the output from the debug settings (see issue template).
And can you please explain step by step what you did.

**Comment by akwala** [comment]
Well... It's working now. I don't know what fixed it. 

Closing the issue. Will reopen if it happens again.
