### ISSUE TITLE
Extras tasks

### ISSUE THREAD

**Issue by LionelR** [pbek/QOwnNotes#182]
Would be great to have more options in tasks, specially :
- start and due date, with parametrised reminders (ie warnings 1h before start/due)
- % achievement with linked status (ie. finished = 100%)
- Repeatable reminders

**Comment by pbek** [comment]
Thank you for your suggestions. QOwnNotes relies on CalDAV on your ownCloud server as a backend. If you find out how to make that all work on CalDAV I will think about it.

**Comment by pbek** [comment]
I'm closing this until I get more information.
