### ISSUE TITLE
Dracula Schema

### ISSUE THREAD

**Issue by TheChiefMeat** [pbek/QOwnNotes#1823]
Just threw together a Dracula theme using the official colour palette:

[Dracula.zip](https://github.com/pbek/QOwnNotes/files/4921101/Dracula.zip)

**Comment by pbek** [comment]
Thank you. I'll take a look at it.

**Comment by pbek** [comment]
Looking great, thank you!

## 20.7.4
- added the **new editor color schema** *Dracula*
  (for [#1823](https://github.com/pbek/QOwnNotes/issues/1823), thank you @TheChiefMeat)

There now is a new release, could you please test it and report if it works for you?

**Comment by TheChiefMeat** [comment]
I'm actually on linux so I couldn't test the theme on my OS, but I span up a Windows VM and it appears to work fine.

**Comment by pbek** [comment]
Great, thank you for testing!

> I'm actually on linux so I couldn't test the theme on my OS

QOwnNotes has builds for a lot of Linux distros. 😁
