### ISSUE TITLE
[I] Scrollbar of note editor issue when window is maximized (in dark mode)

### ISSUE THREAD

**Issue by Katarn** [pbek/QOwnNotes#1824]
#### Expected behaviour

On Windows, if you expand the window to full screen and move the mouse cursor to the far right position of the screen, when you click the left mouse button, scrolling should occur.

#### Actual behaviour

No scrolling. Because there is a small indent between the window border and the note textarea.

#### Steps to reproduce

Just move the mouse cursor to the right border of the screen and click. Of course, the note must be large enough to have a scroll bar.

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Вт июл 14 23:23:59 2020`
**Version**: `20.7.3`
**Build date**: `Jul 12 2020`
**Build number**: `5823`
**Platform**: `windows`
**Operating System**: `Windows 8.1 (6.3)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Primary screen resolution**: `1920x1080`
</details>

![image](https://user-images.githubusercontent.com/6339978/87473242-cfc56380-c629-11ea-93db-0eedcc88beeb.png)

**Comment by pbek** [comment]
> there is a small indent between the window border and the note textarea.

Why should that be an issue?

**Comment by Katarn** [comment]
The expected behavior described above is standard for the Windows platform. QOwnNotes functions differently, as if it weren’t a native application.

The logic of such a UX is that I can not aim with the mouse cursor, but simply move it somewhere to the right, and I will definitely know that it is above the on scroll bar. With QOwnNotes it takes a long time to aim, often this takes several seconds. Constantly confusing when I write a note.

I can note that scrollbars are not the only control in Windows that works through inaccurate mouse cursor targeting. For example, the button to close the window, even with a large indent from the right edge of the screen, is nevertheless pressed. You can watch the attached video.

![close](https://user-images.githubusercontent.com/6339978/87519783-c15b6400-c68a-11ea-8ce6-bd69e5b3e626.gif)
![scroll](https://user-images.githubusercontent.com/6339978/87519765-ba345600-c68a-11ea-9d17-1c64a777ba88.gif)

**Comment by pbek** [comment]
Thank you for your explanation. Why don't you just move the cursor inside the note text edit and scroll there?

**Comment by Katarn** [comment]
I'm doing it now. But this constantly knocks me out of the stream of thoughts associated with writing a note. Especially if you switch between QOwnNotes and, say, LibreOffice or any other application for Windows - the usual controls work differently and you need to keep this in mind.

**Comment by pbek** [comment]
> the usual controls work differently and you need to keep this in mind.

I don't know if you even can "remove that margin" in fullscreen mode in Qt.
And furthermore you can position all panels manually in QOwnNotes.
Btw. what happens in "fullscreen mode" (F11)?

> The problem is further complicated by the fact that QOwnNotes has a very narrow scrollbar and it’s not easy to aim at it.

You can try to set a different interface style in the *General setting* or alter the design of the scrollbars with the `Custom user interface styling` script.

**Comment by Katarn** [comment]
As far as I understand, there are two indents here. The first indent is the note text input field itself. In the screenshots, I show that the borders of this field do not coincide with the borders of the notes tree by approximately the same distance as on the right side of the window.

At the same time, as you can see, the note tree has no indentation from the edge of the screen at all.

The second indent is inside the scrollbar. The slider is at some distance from its border.

![image](https://user-images.githubusercontent.com/6339978/87534513-cde9b780-c69e-11ea-90c1-acd7f8a28209.png)

> Btw. what happens in "fullscreen mode" (F11)?

The same as with the maximized window. Regarding indentation, nothing changes.

> You can try to set a different interface style in the General setting or alter the design of the scrollbars with the Custom user interface styling script.

As it turned out, the problem is only in the dark mode of the interface. If you use light, then the standard Windows scrollbars appear and the indents at the text input field disappear. No other settings are affected.

Can you tell me how to return the standard scrollbars in dark mode, change only their color? In a light theme, they look like this:

![image](https://user-images.githubusercontent.com/6339978/87535524-5157d880-c6a0-11ea-8fcb-8d9cebb36bf1.png)

**Comment by Katarn** [comment]
By the way, I found another such difference in the size of the buttons in the dark and light modes:

![image](https://user-images.githubusercontent.com/6339978/87535743-a1cf3600-c6a0-11ea-9bb1-2e55ba4c0fcb.png)
![image](https://user-images.githubusercontent.com/6339978/87535786-b8758d00-c6a0-11ea-8318-799d39812e6c.png)
![image](https://user-images.githubusercontent.com/6339978/87535836-cc20f380-c6a0-11ea-8767-591bd07c5f9e.png)
![image](https://user-images.githubusercontent.com/6339978/87535862-d4792e80-c6a0-11ea-9433-8b9632ce7390.png)

Is this a mistake in the dark theme or is it so conceived?

**Comment by pbek** [comment]
The dark theme sets different styles. You can overwrite all styles with the scripting engine, for example with the `Custom user interface styling` script in the script repository.

**Comment by Katarn** [comment]
Thank you, I fixed the problems with the scroll bar and button sizes with this style:

```css
QScrollBar:vertical
{
    border: 0;
    margin-left: 0;
    margin-right: 0;
    width: 20px;
}

QFrame
{
    border-right-width: 0;
    padding-bottom: 1px;
    padding-top: 1px;
}

QTabWidget::pane {
    border-right-width: 0;
    padding: 0;
}

QPushButton
{
    padding: 5px 30px;
}
```

![image](https://user-images.githubusercontent.com/6339978/87541498-0216a580-c6aa-11ea-947e-0f042acfb61f.png)
![image](https://user-images.githubusercontent.com/6339978/87541424-e8755e00-c6a9-11ea-8cc1-189a13b95229.png)
![image](https://user-images.githubusercontent.com/6339978/87541556-19ee2980-c6aa-11ea-876e-b1c396ac3a13.png)

The issue, apparently, can be closed.

**Comment by pbek** [comment]
Awesome, great job!
