### ISSUE TITLE
Apparent inconsistency between how double underscore is implemented in QOwnNotes and markdown cheatsheet.

### ISSUE THREAD

**Issue by Sorren1969** [pbek/QOwnNotes#1825]
#### Expected behaviour

Markdown cheatsheet, suggests double underscore is used as alternative to double asterisks for strong emphasis, aka bold.

#### Actual behaviour

In QOwnNotes, rendered underscore is indicated with the the following markdown __underlined__

That is a leading and trailing double underscore.

I don't have a problem with the fact that or means by underscore is implemented, but as the cheatsheet is the main form of documentation for how to use QOwnNotes markdown, I suggest the document ought to at least accurately reflect that?
 
#### Output from the debug section in the settings dialog

N/A

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
That was an added feature. You can turn the underline rendering in the preview off in the *Preview settings*.

**Comment by pbek** [comment]
But I'll remove that part from the cheatsheet, thank you for bringing it up.
