### ISSUE TITLE
Interface tweaks / alternative ideas

### ISSUE THREAD

**Issue by Derducken** [pbek/QOwnNotes#1827]
Howdy! If you remember, I'd reviewed QOwnNotes for a site and suggested some changes. You told me to come and post about them here, so... some months later, here I am :-D

This won't be a typical issue report, but just some tweaks I honestly think would improve your awesome program's UI/UX.

1. Better Navigation.
As it is, QOwnNotes feels more complicated than Evernote or even Joplin, and that's because you're trying to expose its versatility all-at-once. Why have both the typical tree-form navigation and the tags on the screen at the same time, if it's only possible to select stuff from each individually? Plus, it eats up precious screen estate. Instead, consider this:

Unify the folder-tree view with the notes. In other words, use an approach similar to how most IDEs present project folders. This will make even complex note structures, like folder > folders & notes > folders & even more notes > notes easy to navigate.

Then, do the same for tags. Present them in a similar tree-like view, with each tag being "expandable." When expanded, the notes assigned to it would be presented bellow it, folder-tree-style.

As it is, you're going for a more Explorer-like view, but in File Managers, the contents of the folders are presented in their primary view. With QOwnNotes, they're restricted to a tiny panel on the left, so the very UI structure of the app demands a somewhat different presentation approach.

2. Simplified Navigation Presentation
Take the above and simplify it further by presenting the two navigation approaches in two tabs. As in, have two tabs at the top of the left panel, one for Folders and one for Tags. Depending on which one is selected, use almost the full height of the left panel for each respective view. As mentioned above, take a look at solutions like VS Code for how that could look.

Although it might seem like a step back in versatility, it isn't: both folders and tags could still be selectable at the same time. The user could, for example, switch between views, select different notes, and merge them into one. The reason (I believe) it would be better than the current approach, simply because the user would have more real estate for managing his note structure, and have a logical representation of their actual structure on disk/in the database (notes-in-relation-to-paths), instead of seeing entries presented semi-randomly in different panels, at different spots on the screen.

Anyway, that's all for now. If you'd like to chat more about those ideas, or would like me to (try to) help with some design/graphics (not actual coding, think Photoshop, InkScape, prototyping with HTML & CSS), feel free to page me.

**Comment by pbek** [comment]
Thank you! I think this feature request would need some mockups to better understand what we are talking about. 😅

**Comment by Derducken** [comment]
Does this make any sense?

https://www.dropbox.com/s/fiw67daxddl19rc/Tree-view-notes.jpg?dl=0

**Comment by pbek** [comment]
![g7hqI8IL](https://user-images.githubusercontent.com/1798101/88257450-07817a80-ccbe-11ea-98b2-3ec0e599e57f.jpeg)

You can already turn off the panel lock and move the tag panel as tab next to the note list.
And there is a work-in-progress setting to show the note sub-folders and notes in a tree (was voted down because it's a nightmare if you have 1000s of notes and sub-folder)

**Comment by pbek** [comment]
And you can also have different workspaces with different panel layouts.

**Comment by Derducken** [comment]
Well, you were one steap ahead of me 👍 

I knew about the first feature, but didn't notice the second one was already implemented. That's precisely what I wanted!

I know it's supposed to be a work in progress, but I'll have to mention this because "it doesn't work as you state for me": after enabling the feature in Settings>Panel , the right-click menu only works for selected notes. It doesn't work for any folder, so I can't create new sub-folders or re-arrange existing ones. Is it some bug on my side, or a known problem due to the feature being experimental?

As for how this can get out of hand if you have thousands of notes, well, yes, but the same problem applies to IDEs like VSCode that use the same approach. I guess one way to semi-sidestep the problem would be by having folders auto-expand/collapse when selected.

**Comment by pbek** [comment]
Like I said, #790 is a "WIP", there is a Todo-List on the top. 😉

**Comment by Derducken** [comment]
According to the Todo-List (except if I'm looking at the wrong stuff) a context menu should appear when I clicked on either a note _or_ a sub-folder. In my case, though, it only appears when I click on notes?!? For example, in the Todo-List I see a ticked box next to "create new sub-folder via context menu", which doesn't work for me.

Am I looking at the wrong thing?

Apart from that, here's another tweak I forgot to mention (...that you've probably already implemented and I missed too):

Research Mode (Clipboard Monitoring)

Allow me to explain.

I've written a script for myself with AutoHotKey for when doing research for lengthy articles, that's proved to be a great little helper. What it does is simply, after being enabled with a hotkey press, start monitoring the Clipboard, and saving anything newly copied as a standalone TXT file note in a predefined folder. This helps when, for example, I want to quickly gather details about a product. I create a folder, set the script to "target" it, then search online for related info. Whatever I copy ends up in the product's folder, until I disable the mode with the same hotkey.

I'm not asking or expecting you implement this if you don't find it useful, especially since I can easily tweak my script to add anything newly copied to the Clipboard to its previous contents, creating a mega-clipboard of researched info, then simply paste it in a QOwnNotes note. I'm just throwing the idea on the table in case it's useful for others.

**Comment by pbek** [comment]
> According to the Todo-List (except if I'm looking at the wrong stuff) a context menu should appear when I clicked on either a note or a sub-folder. In my case, though, it only appears when I click on notes?!? For example, in the Todo-List I see a ticked box next to "create new sub-folder via context menu", which doesn't work for me.
> 
> Am I looking at the wrong thing?
> 

You should put that best to #790. Pull requests are also welcome. Implementing that feature request was and is a lot of work... 😉 

> Apart from that, here's another tweak I forgot to mention (...that you've probably already implemented and I missed too):
> 
> Research Mode (Clipboard Monitoring)
> 
> Allow me to explain.
> 
> I've written a script for myself with AutoHotKey for when doing research for lengthy articles, that's proved to be a great little helper. What it does is simply, after being enabled with a hotkey press, start monitoring the Clipboard, and saving anything newly copied as a standalone TXT file note in a predefined folder. This helps when, for example, I want to quickly gather details about a product. I create a folder, set the script to "target" it, then search online for related info. Whatever I copy ends up in the product's folder, until I disable the mode with the same hotkey.
> 
> I'm not asking or expecting you implement this if you don't find it useful, especially since I can easily tweak my script to add anything newly copied to the Clipboard to its previous contents, creating a mega-clipboard of researched info, then simply paste it in a QOwnNotes note. I'm just throwing the idea on the table in case it's useful for others.

I think I don't grasp what you are talking about. Is that a QON script you are talking about? Do you need a feature in the scripting API?

**Comment by Derducken** [comment]
No, I'm talking about a possible feature that... Well... Think of it as "a recorder for copied stuff". It could be accessible through a button, shortcut, or menu entry, and would work something like this:

1. You select a note.
2. You enable this function. It starts monitoring the clipboard. Initially does nothing more.
3. You move to other programs, like your browser, to do some research.
4. When you find something you want to note, you simply copy it to your clipboard.
5. The function "takes" it from the clipboard, adds it to the active note, clears the clipboard and goes back to waiting for the next thing to be copied to the clipboard.
6. This would remain active until you switch off the function.

**Comment by pbek** [comment]
Sounds scary. 😄 
You can script that already yourself. There is a timer in QML you can use to check the clipboard every X ms and create notes if the content of the clipboard changes.

**Comment by Waqar144** [comment]
>  because it's a nightmare if you have 1000s of notes and sub-folder)

We can get around this using threads like we did for Navigation. 

And we can do the same for multi note search (which is particularly problematic with large amounts of notes). I fixed this one locally, but the code wasn't as clean so I didn't push it. It's a quick fix, nothing complicated so I might do it soon.

**Comment by pbek** [comment]
Be my guest to do more work on the sub-folder/note tree, @Waqar144 😁

**Comment by Waqar144** [comment]
@Derducken 
 > If you'd like to chat more about those ideas, or would like me to (try to) help with some design/graphics (not actual coding, think Photoshop, InkScape, prototyping with HTML & CSS), feel free to page me.

We probably need help with the settings pages, it is often not evident what a setting will do. And we need help with the docs, particularly on how to use QOwnNotes. It's a huge software with a lot of features, so often times the features are there but people are not able to find them easily.

**Comment by Waqar144** [comment]
> Be my guest to do more work on the sub-folder/note tree, @Waqar144 😁

Maybe I will ;)
However I am wondering,wwhat would happen if a folder has 200 notes. We can expand the tree, but This would lead to a very bad and unusable interface in my opinion. 

@Derducken what do you think?

**Comment by pbek** [comment]
> However I am wondering,wwhat would happen if a folder has 200 notes.

see: because it's a nightmare if you have 1000s of notes and sub-folders 😆

**Comment by pbek** [comment]
I will close this issue until there is more information.
