### ISSUE TITLE
Release built with GitHub Actions deployed in one single GitHub Release

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1828]
For more than a week I've been working to get the releases built with GitHub Actions and deployed in one single GitHub Release (instead of spread across several GitHub Releases).

The binaries are now all 64 bit!

- Linux AppImage 64 Bit with Qt 5.14.2
- Linux Deb 64 Bit for Qt 5.14.2
- macOS DMG 64 Bit with Qt 5.14.2
- Windows ZIP file 64 Bit with Qt 5.13.2

Can you all please test the GitHub Actions release from https://github.com/qownnotes/qon-build-test/releases/tag/v20.7.4.179518815.65 and report your results at https://github.com/pbek/QOwnNotes/issues/1828! We don't want "surprises" when this is rolled out for everyone. 😬

**Comment by pbek** [comment]
@Waqar144 @sanderboom @mliudev @Airgunster @sabinomaggi @TheChiefMeat @OlivierHobbes @r00tr4v3n @Maboroshy @mlimacarlos @pmarki @elnull @chrixxxx

**Comment by pbek** [comment]
@Sorren1969  @Derducken @miguelchinn @Katarn @shlyakpavel @yuxiacn

**Comment by shlyakpavel** [comment]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/19782228/88286225-189bad00-ccf9-11ea-83b7-d78853eb82ed.png">
Unsigned image

**Comment by mlimacarlos** [comment]
I've try to test a deb package and it didn't work.

**Comment by pbek** [comment]
> Unsigned image. Everything else seems to be fine.

Thank you! But you were able to accept it in the macOS Security Settings as usual, right?

> I've try to test a deb package and it didn't work.

Thank you for confirming, I guess I will drop the deb altogether, since that's handled by the PPA and OBS.
What's about the appimage?

**Comment by Katarn** [comment]
Windows 8.1 - did not notice any problems.

**Comment by pbek** [comment]
thank you @Katarn, could you please try to insert a link `https://github.com/pbek/QOwnNotes/issues/1828` with `Ctrl + L` and check if the title was detected (to make sure https connections work).

**Comment by Waqar144** [comment]
Looking good!

**Comment by pbek** [comment]
What did you try, @Waqar144? The AppImage?

**Comment by Waqar144** [comment]
Yes

**Comment by TheChiefMeat** [comment]
Confirm the .deb file didn't want to work for me, using Kubuntu 20.04

**Comment by pbek** [comment]
Thank you, @Waqar144.
Thank you @TheChiefMeat, did the AppImage work?

**Comment by TheChiefMeat** [comment]
> Thank you, @Waqar144.
> Thank you @TheChiefMeat, did the AppImage work?

Yeah the AppImage seems to work fine.

**Comment by pbek** [comment]
Great, thank you, @TheChiefMeat.

I still need more Windows and macOS confirmations! 😁

**Comment by OlivierHobbes** [comment]
I downloaded the .zip file and the app works as expected on Windows 10.

**Comment by Airgunster** [comment]
@pbek, tested v. 20.7.4 - GitHub Actions - build 738 on macOS 10.15.6, all cool (thanks again for all your work!).

**Comment by Katarn** [comment]
> thank you @Katarn, could you please try to insert a link `https://github.com/pbek/QOwnNotes/issues/1828` with `Ctrl + L` and check if the title was detected (to make sure https connections work).

![image](https://user-images.githubusercontent.com/6339978/88335623-4e15ba00-cd3c-11ea-85f1-d2864562120b.png)

It is a little unclear, however, why the window cannot be made smaller in height.

**Comment by pbek** [comment]
Thank you @OlivierHobbes, could you please try to insert a link `https://github.com/pbek/QOwnNotes/issues/1828` with `Ctrl + L` and check if the title was detected (to make sure https connections work).

Thank you, @Airgunster!

**Comment by pbek** [comment]
Thank you for testing, @Katarn.

> It is a little unclear, however, why the window cannot be made smaller in height.

because of the content of the 2nd tab

**Comment by OlivierHobbes** [comment]
> Thank you @OlivierHobbes, could you please try to insert a link `https://github.com/pbek/QOwnNotes/issues/1828` with `Ctrl + L` and check if the title was detected (to make sure https connections work).

Yes, the title of the page is automatically added to the link

**Comment by pbek** [comment]
Thank you, @OlivierHobbes.

**Comment by pbek** [comment]
## 20.7.5
- releases for Windows and macOS are now built with GitHub Actions in 64 bit
  (for [#1828](https://github.com/pbek/QOwnNotes/issues/1828))
    - there is a macOS DMG with Qt 5.14.2 and Windows ZIP file with Qt 5.13.2 in every release
    - the updating api was adapted to use the new releases, please report any
      troubles with updating or installing
    - in addition there is a Linux AppImage 64 Bit with Qt 5.14.2

There now is a new release, could you please test it and report if it works for you on Windows and macOS (especially the update from the previous release, best not the one from this issue, but the one you had previously)?

**Comment by Maboroshy** [comment]
I've tried AppImage on my Manjaro Linux. It cached up my config but had no breeze Qt widget style, and the icons looked like badly scaled pixmaps.

**Comment by pbek** [comment]
@Maboroshy, does it look worse than with the AppImages from https://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/AppImage/?

**Comment by pbek** [comment]
By the way, https://github.com/pbek/QOwnNotes/releases/tag/v20.7.5 is now built and I was able to update to it under Windows and  macOS. 😅

**Comment by Maboroshy** [comment]
They have the same look.

**Comment by Maboroshy** [comment]
What is interesting the ODS repo AppImage has GTK+ widget style that is absent in GitHub Actions AppImage.

**Comment by pbek** [comment]
> They have the same look.

Then it's as good as it gets. 😅 In any case the AppImage is for those who can't use all other repositories, including snap and flatpak...

> What is interesting the ODS repo AppImage has GTK+ widget style that is absent in GitHub Actions AppImage.

Interesting, I use https://github.com/probonopd/linuxdeployqt for creating it...

https://github.com/pbek/QOwnNotes/blob/ccc0f2db77be877b8a3a3b6540d9fe3ff5c4d034/.github/workflows/build-release.yml#L142-L147

**Comment by OlivierHobbes** [comment]
Auto-update toward 20.7.5 worked fine on Windows 10 (including title detection with https links)

**Comment by pbek** [comment]
Great, thank you, @OlivierHobbes!

**Comment by r00tr4v3n** [comment]
AppImage looks good, https works too.

**Comment by pbek** [comment]
Thank you, @r00tr4v3n!

**Comment by pbek** [comment]
@Katarn, for you 😉 

## 20.7.6
- the note link dialog can now be resized smaller than the height needed for its 2nd tab

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it the update from 20.7.5 works for you on Windows and macOS?

**Comment by OlivierHobbes** [comment]
Update toward 20.7.6 is ok and I can resize the dialog.
Did you remove the name of link box in the URL tab on purpose ? (I don't need it since the title detection works)

**Comment by pbek** [comment]
> Update toward 20.7.6 is ok and I can resize the dialog.

thank you

> Did you remove the name of link box in the URL tab on purpose ? (I don't need it since the title detection works)

Oh damn, no. It got moved to the 2nd tab by accident.

**Comment by pbek** [comment]
Introducing regressions is also a way to test the updater. 😄 

## 20.7.7
- the name and description fields that got moved to the 2nd tab by accident were fixed in the
  note link dialog

**Comment by pbek** [comment]
@OlivierHobbes, there now is a new release, could you please test it and report if it works for you?

**Comment by OlivierHobbes** [comment]
Update checker : "There are no updates available. 20.7.6 is the latest version."

**Comment by OlivierHobbes** [comment]
It's ok now. Updated to 20.7.7. Name and description of the link are in the URL tab.

**Comment by pbek** [comment]
Great, thank you for testing!
