### ISSUE TITLE
Flatpak update not available?

### ISSUE THREAD

**Issue by Tarliman** [pbek/QOwnNotes#1829]
#### Expected behaviour

Update installed version to current version

#### Actual behaviour

Skipping: org.qownnotes.QOwnNotes/x86_64/stable is already installed

#### Steps to reproduce

Followed instructions on https://www.qownnotes.org/installation where the Download Update button in the app takes me:

There is a 3rd party Flatpak org.qownnotes.QOwnNotes on Flathub.

You can install it by typing:
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub org.qownnotes.QOwnNotes

Afterwards you should be able to run QOwnNotes with the command flatpak run org.qownnotes.QOwnNotes.

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

flatpak install flathub org.qownnotes.QOwnNotes
Looking for matches…
Skipping: org.qownnotes.QOwnNotes/x86_64/stable is already installed

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Everything seems fine on https://github.com/flathub/org.qownnotes.QOwnNotes.
Can you please post the output from the debug settings (see issue template).

**Comment by pbek** [comment]
> flatpak install flathub org.qownnotes.QOwnNotes

And why did you try to install it a 2nd time when you want to update the flatpak?

see: https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-update

**Comment by Tarliman** [comment]
I followed the installation instructions because that was what the update / download link in the application provided. Perhaps the application update button should itself be updated to point to the correct instruction page.

**Comment by Tarliman** [comment]
By ignoring the instructions given at https://www.qownnotes.org/installation, where the application Update button took me, and using instead the command flatpak update org.qownnotes.QOwnNotes, I was able to achieve update.

**Comment by pbek** [comment]
The update mechanism is agnostic about 3rd party builds.
Can you please post the output from the debug settings (see issue template), so I can see which `Release` string is set for the Flatpak.

**Comment by pbek** [comment]
> Perhaps the application update button should itself be updated to point to the correct instruction page.

Which "update button" are we talking about?

**Comment by pbek** [comment]
I will close this issue until there is more information.
