### ISSUE TITLE
20.7.6 hangs on macos

### ISSUE THREAD

**Issue by artmg** [pbek/QOwnNotes#1830]
Hi, I just accepted your upgrade from 20.7.5 to 20.7.6 but within a few seconds of starting up, it just freezes with the rainbow wheel of death. It hangs before I even get the chance to start using it. If I'm quick I can check About QOwnNotes to see the version before it locks up. 

I'm still on macOS Mojave 10.14.6, but patched up to date. This was not long after a fresh reboot so system should be relatively clean.

Downgrading manually to 20.7.5 gets me back running again. I do not know how to diagnose this issue, but if you give me a suggestion, then I can repeat the upgrade and reply here with the logs or whatever will help with this issue. Thanks

**Comment by pbek** [comment]
Thank you for reporting. Maybe macOS is mad because the Qt library and build system has changed in 20.7.5 (see #1828).

Can you please try to use the dmg from https://github.com/pbek/QOwnNotes/releases/tag/v20.7.6.

**Comment by pbek** [comment]
The strange thing is I've had similar troubles updating *to* 20.7.5. After installing the the dmg directly I had no troubles updating to 20.7.6. Did you start using QOwnNotes with version 20.7.5 on this Mac?

**Comment by artmg** [comment]
Good thinking, batman. That resolved the issue. When I installed the DMG manually from the latest release, that worked properly. Thanks!

**Comment by pbek** [comment]
🦇 Thank you for confirming, Robin, 😁

**Comment by artmg** [comment]
Ok, so although I have been using the automatic upgrade for over two years, it seemed not to work that time. Once I did the manual upgrade, it worked ok. Then I downgraded again manually and used the auto upgrade, and it ALSO worked fine. Not sure what dragging and dropping manually in the DMG did, but it seems to have sorted my install out just fine. Thanks for the rapid response.

**Comment by pbek** [comment]
I'm syncing the content of the new app to the content of the old app.
See: https://github.com/pbek/QOwnNotes/blob/72be0a0ab953ab1b784ddc31ff880786485c412b/src/scripts/macos/update.command#L62

I didn't dare to throw in a `--delete` to the rsync command in fear of a wrong destination directory causing the whole hard-disk being deleted by rsync. 😅 

If you care please report if the next update works.

**Comment by artmg** [comment]
> I didn't dare to throw in a `--delete` to the rsync command in fear of a wrong destination directory causing the whole hard-disk being deleted by rsync. 😅
> 
> If you care please report if the next update works.

_If it works? ... as opposed to trashing my PC? Not sure I'll ever dare to run an update again 😉_

Will do, Patrick. I appreciate your support.

**Comment by pbek** [comment]
> If it works? ... as opposed to trashing my PC? Not sure I'll ever dare to run an update again wink

if the destination folder somehow is set wrong a `--delete` (that removes everything that isn't in the source, this would be a good for updating the app) would delete everything in the destination folder

that's why I don't want to use it even if it would be safer for the update process...

**Comment by rakekniven** [comment]
Installing v20.8.1 using the dmg fixed it.

**Comment by pbek** [comment]
Great!
