### ISSUE TITLE
[F] Delete notes from the Nextcloud Trash

### ISSUE THREAD

**Issue by johnZ-cyber** [pbek/QOwnNotes#1833]
#### Expected behaviour

In the same way that it is possible to empty the note trash in the local repository, it could be possible to do the same with the notes that are in the nextcloud trash.

#### Actual behaviour

The notes deleted in QON go to the nextcloud trash but it is not possible to delete them permanently. Only through the nextcloud itself.

#### Steps to reproduce

Open the remote repository trash and try deleting any notes that exist there.

#### Nextcloud API 
https://docs.nextcloud.com/server/19/developer_manual/client_apis/WebDAV/trashbin.html

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
## 20.7.9
- you are now able to also delete trashed notes on your server in the trash dialog

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by johnZ-cyber** [comment]
works great! Thank you!

**Comment by pbek** [comment]
Great, thank you for testing!
