### ISSUE TITLE
[I] Broken icons in the extension for firefox 

### ISSUE THREAD

**Issue by fabianski7** [pbek/QOwnNotes#1834]
#### Actual behaviour
Using some modification script for firefox, such as ghacks/user.js (to improve security and privacy of the browser), causes the icons not to be displayed and the extension to get messy.

[Screenshot](https://plik.root.gg/file/WiQ99I0yAde9agLy/796R2w2Ia9DeEXZm/4.png)

#### Steps to reproduce

1. Open the advanced firefox preferences (`about:config`) and change the `browser.display.use_document_fonts` option from `1` to `0`
2. Disable and enable the extension

#### More information
here are some cases I found with more information about this bug and how it was fixed.

https://github.com/CTemplar/webclient/issues/508
https://github.com/ghacksuserjs/ghacks-user.js/issues/824
https://github.com/FirefoxBar/HeaderEditor/issues/46

**Comment by pbek** [comment]
Can you please open this at https://github.com/qownnotes/web-companion/issues
