### ISSUE TITLE
[I] Window state is not restored after exiting full screen mode

### ISSUE THREAD

**Issue by Katarn** [pbek/QOwnNotes#1835]
#### Expected behaviour

The main window should be maximized.

#### Actual behaviour

The main window is not in the maximized state.

#### Steps to reproduce

1. Run the application.
2. Expand the main window to full screen (maximized window state with window border).
3. Press F11 to enter full screen mode.
4. Press F11 again to return to normal mode.

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Пн июл 27 16:41:19 2020`
**Version**: `20.7.8`
**Build date**: `Jul 26 2020`
**Build number**: `742`
**Platform**: `windows`
**Operating System**: `Windows 8.1 (6.3)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `ru_RU`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `146`
**Calendar items**: `0`
**Enabled scripts**: `2`
</details>

**Comment by pbek** [comment]
> The main window is not in the maximized state.

so what happens instead?

Can you please post the full output from the debug settings (see issue template).

**Comment by pbek** [comment]
I can toggle between full-screen mode and "windowed mode" with F11 under Windows 10.

> Window state is not restored after exiting full screen mode

so what actually is your issue? are we talking about not being able to get into full screen mode or are we talking about the positions of panels after exiting full screen mode?

**Comment by Katarn** [comment]
After exiting full-screen mode, the window should be restored to its last known state, in our case, the "maximized" state. But window is in the "normal" state.

**Comment by pbek** [comment]
Now I finally see what we are talking about. I'll put it on my list to see if that can be implemented.

**Comment by pbek** [comment]
## 20.7.9
- if you minimized or maximized the application window before entering full-screen mode that state will now
  be restored after exiting full-screen mode

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by fabianski7** [comment]
The size of the panels are not being maintained when the window is modified. Maybe this has something to do with this bug?
[I tried to show it in this video](https://upload.vaa.red/859N1#M9eQdvZEwmmVeOKVJeZaqp7ISC91caQ3)

**Comment by pbek** [comment]
See #422 and similar. You can try playing around with different workspaces and the central widget setting (in *Panel settings*).

**Comment by Katarn** [comment]
Yes it works. Thank.
However, the application flickers - first in the normal window size, then changed state to maximized window size. But this is not critical.
