### ISSUE TITLE
Tab or Return from notes list does nothing

### ISSUE THREAD

**Issue by koro-xx** [pbek/QOwnNotes#1837]
In the shortcuts list https://www.qownnotes.org/shortcuts/QOwnNotes it says that "from the note list", "Tab or Return lets you edit the current note". This is not working in my system (Windows 10, QOwnNotes 20.7.9), and I don't think it ever has. Tab or enter from the notes list does nothing at all. 

#### Expected behaviour
Enter or Tab from the notes lists should move focus to the edit panel.

#### Actual behaviour
Nothing happens.

#### Steps to reproduce
Go to the notes list, in any workspace, choose a note and press enter or tab.

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fri Jul 31 19:11:14 2020`
**Version**: `20.7.9`
**Build date**: `Jul 28 2020`
**Build number**: `743`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\akoro\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Users\akoro\MyApps\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `960x540`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `649`
**Calendar items**: `0`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\akoro\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `A:\Dropbox\Sync\Notational Data`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `A:\Dropbox\Sync\Notational Data\notes.sqlite`

### Note folder `local`

**id**: `2`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `C:\Users\akoro\Desktop\notes-test`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\akoro\Desktop\notes-test\notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

### Script `custom-new-note-headline`

**id**: `1`
**path**: `A:\Dropbox\Sync\koro-config\QOwnNotes\custom-new-note-headline.qml`
**variablesJson**: *empty*

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/editorWidthMode** (int): `1`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (int): `17`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrainingSpaces** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `C:/Users/akoro/Desktop`
**FileDialog/LastPath-InsertImage** (QString): `C:/Users/akoro/Desktop`
**FileDialog/LastPath-NotePDFExport** (QString): `C:/Users/akoro/Desktop`
**FileDialog/LastPath-ScriptPath** (QString): `A:/Dropbox/Sync/koro-config/QOwnNotes`
**GlobalShortcuts/MainWindow-action_Find_note** (QString): `Alt+Shift+A`
**ImageDialog/disableCopying** (QString): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-07-31T19:06:32.777`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `30`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,7.8,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `true`
**MessageBoxOverride/readonly-mode-allow** (int): `65536`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): `carolog`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteFolder-1/allowDifferentNoteFileName** (QString): `true`
**NoteFolder-2/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 125 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 19 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `30`
**NoteHistoryCurrentIndex-2** (int): `18`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExportOrientation** (int): `0`
**Printer/NotePDFExportPageSize** (int): `4`
**Printer/NotePrinting** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `500c6890-62c2-4ee2-a400-3aeb5774190c`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `txt`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `true`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): `yyyy.MM.dd hh:mm`
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**interfaceStyle** (QString): `Fusion`
**internalIconTheme** (QString): `true`
**itemHeight** (int): `18`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `A:/Dropbox/Sync/Notational Data`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `initial`
**recentNoteFolders** (QStringList): `C:/Users/akoro/Desktop/notes-test, C:/Users/akoro/Nextcloud/Notes`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `REDACTED`
**savedSearches/noteFolder-2** (QStringList): `REDACTED`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**skipVersion** (QString): `20.5.1`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-500c6890-62c2-4ee2-a400-3aeb5774190c/name** (QString): `test`
**workspace-500c6890-62c2-4ee2-a400-3aeb5774190c/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-500c6890-62c2-4ee2-a400-3aeb5774190c/windowState** (QByteArray): `<binary data>`
**workspace-89FtwXmShQg5/name** (QString): `Minimal`
**workspace-89FtwXmShQg5/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-89FtwXmShQg5/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 500c6890-62c2-4ee2-a400-3aeb5774190c, 89FtwXmShQg5`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\akoro\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `DESKTOP-KVV0ELN`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\akoro`
**LOCALAPPDATA**: `C:\Users\akoro\AppData\Local`
**LOGONSERVER**: `\\DESKTOP-KVV0ELN`
**NUMBER_OF_PROCESSORS**: `8`
**OneDrive**: `C:\Users\akoro\OneDrive`
**OneDriveConsumer**: `C:\Users\akoro\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\PuTTY\;C:\texlive\2019\bin\win32;C:\Program Files\Git\cmd;C:\Users\akoro\AppData\Local\Microsoft\WindowsApps;C:\Program Files\CMake\bin;C:\Users\akoro\AppData\Local\atom\bin`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 142 Stepping 11, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `8e0b`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\akoro\AppData\Local\Temp`
**TMP**: `C:\Users\akoro\AppData\Local\Temp`
**USERDOMAIN**: `DESKTOP-KVV0ELN`
**USERDOMAIN_ROAMINGPROFILE**: `DESKTOP-KVV0ELN`
**USERNAME**: `akoro`
**USERPROFILE**: `C:\Users\akoro`
**windir**: `C:\WINDOWS`

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

No output.

</details>

**Comment by pbek** [comment]
For me pressing Tab or Enter in the note list puts the focus to the note edit panel (tested on Linux and macOS).
Do you have the note edit panel turned off?
Might you be able to make a video to show what happens for you?

**Comment by koro-xx** [comment]
Maybe I'm missing something obvious, but from what I understand the edit panel is on.
Here's a quick  video showing what I mean (sorry for the poor quality)
https://www.loom.com/share/37ba3dc372434032b872ec0e3a8a54a6

**Comment by pbek** [comment]
I cannot reproduce this under Windows 8.1 neither. Everything works fine.
What is the content of `A:\Dropbox\Sync\koro-config\QOwnNotes\custom-new-note-headline.qml`? (or just disable the script for testing)

Is there no log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting `Debug` in `Options`).

Does it work if you open QOwnNotes in a new session? (see https://docs.qownnotes.org/en/latest/getting-started/cli-parameters/)

**Comment by koro-xx** [comment]
The custom-new-note-headline.qml contents:

import QtQml 2.0
import com.qownnotes.noteapi 1.0

```
/**
 * This script creates a new headline with # instead of =
 * 
 * https://github.com/pbek/QOwnNotes/issues/272
 * https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/custom-new-note-headline.qml
 */
QtObject {
    function handleNewNoteHeadlineHook(headline) {
		var m = new Date();
        var text = m.getFullYear() + "." + ("0" + (m.getMonth()+1)).slice(-2) + "." + ("0" + m.getDate()).slice(-2) + " "+ ("0" + m.getHours()).slice(-2) + "." + ("0" + m.getMinutes()).slice(-2)
        return text;
    }
}
```

The behavior persists after disabling it. However, I tried starting in a clean new session and I see the expected behavior. So there's something in my settings that's doing this. I can't figure out what. The log panel produces nothing when I press enter or tab from the notes list, even with debug logs enabled...

**Comment by pbek** [comment]
Ok, great so just let me know if you find out which setting created the problem for you.

**Comment by koro-xx** [comment]
Found it!
It's the option "Allow note file name to be different from headline" in Settings->Note folders. When this is enabled, pressing enter or tab from the notes list stops doing anything.
Any idea why this happens, and any hope this can be fixed? (I normally don't use headlines so I need this option enabled to make my note file names meaningful)

**Comment by pbek** [comment]
Found it:

https://github.com/pbek/QOwnNotes/blob/beb1a75fb5585db6b4337bb065409ef3aafb9f6c/src/mainwindow.cpp#L4179-L4190

I'm sorry. 😬

**Comment by koro-xx** [comment]
Aha! Sounds like an old workaround. Do you think there's chance that this can be fixed at some point?
It seems weird that such a simple thing as changing focus should be a problem...

**Comment by pbek** [comment]
It wasn't the the changing of focus. `Return` or `Tab` also accept a note name change if you edit the note filename in the note list. 😬

**Comment by pbek** [comment]
I can do some tests or maybe find another workaround.

**Comment by pbek** [comment]
I don't have a good feeling but I will remove the workaround for now.

**Comment by koro-xx** [comment]
Great, thanks! Unfortunately I don't know how to build this in windows, but if you have a build without the workaround I can test it out.

**Comment by pbek** [comment]
## 20.8.1
- you can now also use <kbd>Tab</kbd> or <kbd>Enter</kbd> to switch from the
  note list to the note edit panel if note renaming in the note list is enabled

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by koro-xx** [comment]
Excellent! It seems to be working fine. I'll let you know if any crash happens, but so far so good.
Thanks a lot!

**Comment by pbek** [comment]
We'll see. 😅  Thank you for testing.

**Comment by pbek** [comment]
I had to attempt another fix.

## 21.10.9
- a possible crash was fixed when renaming a note directly in the note list when
  <kbd>Enter</kbd> was pressed (for [#1837](https://github.com/pbek/QOwnNotes/issues/1837))
