### ISSUE TITLE
I updated the app on a 32bit machine and now I can't open it any more

### ISSUE THREAD

**Issue by nonplayer** [pbek/QOwnNotes#1839]
What is the last version compatible with 32 bit systems? This app has been invaluable for me, but now on a win10 32bit machine, after saying yes to the latest round of updates, I cannot open it anymore. "This app can't run on your PC"

What version should I roll back to to preserve continued functioning on an older device?

**Comment by pbek** [comment]
Ah, sorry. The official release is 64bit on Windows since 20.7.5 (see #1828). I haven't been able to build the Botan-part in 32bit yet on GitHub Actions... But I still kept the 32bit Qt 5.7 build-pipeline around (mainly for Windows XP), so you could directly download the latest ZIP from https://ci.appveyor.com/project/pbek/qownnotes/build/artifacts.

**Comment by pbek** [comment]
PS: tell Boo I said hello 😄

**Comment by pbek** [comment]
PPS: What is the hardware of your 32bit Windows10? I didn't even know there is a 32bit version of Win10.

**Comment by nonplayer** [comment]
Boo says "squeak" =)

The hardware specifically is an Asus Transformer T100TA combo laptop/tablet. It's a handy little thing, running 32bit windows 10.

Thanks for the information! I was able to roll it back to a 20.5.13 build I had downloaded and archived. I'll see if getting the qt 5.7 build works. Thanks

**Comment by pbek** [comment]
> Boo says "squeak" =)

😁 

> The hardware specifically is an Asus Transformer T100TA combo laptop/tablet. It's a handy little thing, running 32bit windows 10.

ah, so that one has still a 32bit processor but runs Win10, nice

> Thanks for the information! I was able to roll it back to a 20.5.13 build I had downloaded and archived. I'll see if getting the qt 5.7 build works. Thanks

Just use the 20.8.0 release from https://ci.appveyor.com/project/pbek/qownnotes/build/artifacts...

**Comment by Waqar144** [comment]
> Ah, sorry. The official release is 64bit on Windows since 20.7.5 (see #1828). I haven't been able to build the Botan-part in 32bit yet on GitHub Actions... 

Why would it fail on 32 bit now all of a sudden I wonder

**Comment by pbek** [comment]
> Why would it fail on 32 bit now all of a sudden I wonder

because the GitHub Actions build is 64 bit now (see #1828)
