### ISSUE TITLE
Hotkeys don't make any sense (Windows)

### ISSUE THREAD

**Issue by prat0088** [pbek/QOwnNotes#184]
The hotkeys don't make any sense.  I also noticed a few other places where there appears to be non-English text even though I set my language to English.  

![2016-05-26 00_14_42-mail](https://cloud.githubusercontent.com/assets/20519/15545338/f5a0cce8-22d6-11e6-877a-c0f75b15f94b.png)

**Comment by pbek** [comment]
> The mnemonics / hotkeys don't make any sense.

In what way?

>  I also noticed a few other places where there appears to be non-English text even though I set my language to English.

What texts are non-English and in what language are they? (Can you please make some examples, show screenshots)

**Comment by prat0088** [comment]
>> The mnemonics / hotkeys don't make any sense.
> In what way?
I don't know what "Strg+Umschalt+F" means for Find Note in my screenshot.  I do know what Shift+Alt+F means.  I do not know what key combination "Strg+N" is for New Note.  It appears to be a localization bug.

Attaching a second screenshot.

![2016-05-26 08_59_04-mnemonics don t make any sense windows issue 184 pbek_qownnotes](https://cloud.githubusercontent.com/assets/20519/15559791/3bc55a42-2320-11e6-8dd8-7182082e06ea.png)

**Comment by pbek** [comment]
I overlooked that the shortcuts are labeled in German in your screenshot.
That's very strange, all the text that comes internally from Qt is in German on your system, I haven't seen that anywhere so far.
Can you please post the debug output from the settings dialog so I can try to reproduce it.

**Comment by pbek** [comment]
And which language do you have chosen in the Interface tab of the settings?

**Comment by prat0088** [comment]
App language is English.  System language is English but my system locale for non-Unicode programs is Japanese

![2016-05-26 20_56_37-region](https://cloud.githubusercontent.com/assets/20519/15573805/67b8a7d0-2384-11e6-826e-1669a536d3e2.png)
.



Here is the debug output

> QOwnNotes Debug Information
> ===========================
> 
> ## General Info
> 
> **Current Date**: `Thu May 26 20:52:57 2016`
> **Version**: `16.05.19`
> **Build date**: `May 22 2016`
> **Build number**: `1660`
> **Platform**: `windows`
> **Operating System**: `Windows 10`
> **Build architecture**: `i386`
> **Current architecture**: `x86_64`
> **Release**: `AppVeyor`
> **Qt Version (build)**: `5.5.1`
> **Qt Version (runtime)**: `5.5.1`
> 
> ## Server Info
> 
> **serverUrl**: *empty*
> **appIsValid**: `no`
> **connectionErrorMessage**: `Das Protokoll "" ist unbekannt`
> 
> ## Settings
> 
> **DistractionFreeMode/editorWidthMode**: `2`
> **DistractionFreeMode/isEnabled**: `false`
> **DistractionFreeMode/mainSplitterSizes**: `<binary data>`
> **DistractionFreeMode/menuBarGeometry**: `<binary data>`
> **DistractionFreeMode/menuBarHeight**: `21`
> **DistractionFreeMode/windowState**: `<binary data>`
> **LastUpdateCheck**: `2016-05-26T20:52:43`
> **LogDialog/criticalLog**: `true`
> **LogDialog/debugLog**: `false`
> **LogDialog/fatalLog**: `true`
> **LogDialog/geometry**: `<binary data>`
> **LogDialog/infoLog**: `false`
> **LogDialog/scriptingLog**: `true`
> **LogDialog/showAtStartup**: `false`
> **LogDialog/statusLog**: `true`
> **LogDialog/warningLog**: `false`
> **MainWindow/geometry**: `<binary data>`
> **MainWindow/mainToolBar.iconSize**: `24`
> **MainWindow/menuBarGeometry**: `<binary data>`
> **MainWindow/noteTextEdit.code.font**: `Courier,8.25,-1,5,50,0,0,0,0,0`
> **MainWindow/noteTextEdit.font**: `Calibri,11,-1,5,50,0,0,0,0,0`
> **MainWindow/noteTextView.code.font**: `Courier,8.25,-1,5,50,0,0,0,0,0`
> **MainWindow/noteTextView.font**: `Calibri,11,-1,5,50,0,0,0,0,0`
> **MainWindow/showRecentNoteFolderInMainArea**: `false`
> **MainWindow/windowState**: `<binary data>`
> **PiwikClientId**: `<hidden>`
> **ShowSystemTray**: `false`
> **SortingModeAlphabetically**: `false`
> **allowDifferentNoteFileName**: `false`
> **allowOnlyOneAppInstance**: `false`
> **appMetrics/disableAppHeartbeat**: `false`
> **appMetrics/disableTracking**: `false`
> **appMetrics/notificationShown**: `true`
> **cryptoKey**: `<hidden>`
> **currentNoteFolderId**: `1`
> **darkModeColors**: `false`
> **defaultNoteFileExtension**: `txt`
> **demoNotesCreated**: `true`
> **disableAutomaticUpdateDialog**: `false`
> **externalEditorPath**: *empty*
> **ignoreAllExternalModifications**: `false`
> **interfaceLanguage**: `en`
> **mainSplitterSizes**: `<binary data>`
> **mainSplitterState-0-1-1-0**: `<binary data>`
> **mainSplitterState-1-0-1-0**: `<binary data>`
> **mainSplitterState-1-1-1-0**: `<binary data>`
> **mainSplitterState-1-1-1-1**: `<binary data>`
> **markdownViewEnabled**: `false`
> **networking/ignoreSSLErrors**: `true`
> **networking/proxyType**: `0`
> **noteListSplitterState**: `<binary data>`
> **noteSaveIntervalTime**: `10`
> **notesPath**: `C:/Users/User/Dropbox/Notebooks/Command Center`
> **notifyAllExternalModifications**: `false`
> **ownCloud/password**: `<hidden>`
> **ownCloud/serverUrl**: *empty*
> **ownCloud/todoCalendarBackend**: `0`
> **ownCloud/todoCalendarEnabledList**: *empty*
> **ownCloud/todoCalendarEnabledUrlList**: *empty*
> **ownCloud/todoCalendarUrlList**: *empty*
> **ownCloud/userName**: *empty*
> **recentNoteFolders**: `T:/Temp/More Notes, T:/Temp/Notes`
> **tagsEnabled**: `true`
> **verticalNoteFrameSplitterState**: `<binary data>`
> **verticalPreviewModeEnabled**: `false`

**Comment by pbek** [comment]
Thank you for the information, I will see what I can do.
On a side note: QOwnNotes is also translated to Japanese, you can select the language in the interface settings.

**Comment by pbek** [comment]
Although I could not reproduce your problem on my windows box I think I may came up with a solution in version 16.05.21.
Can you please try it out when it's released?

**Comment by pbek** [comment]
16.05.21 is now released

**Comment by alfwro13** [comment]
I have just upgraded to 16.05.21 and most of my right click menu is still in German (my default is English)

**Comment by pbek** [comment]
Thank you for reporting. Can you please post a screenshot.
And what about the main menu? Any German text there?
Can you please post the `General Info` from the debug output.

**Comment by alfwro13** [comment]
![capture](https://cloud.githubusercontent.com/assets/10945277/15606638/5d686f78-2405-11e6-924a-483a8b5ef071.JPG)
![capture2](https://cloud.githubusercontent.com/assets/10945277/15606641/60e26488-2405-11e6-9a07-aaa14be7f4a9.JPG)
here you go

**Comment by alfwro13** [comment]
and the general info:
## General Info

**Current Date**: `Fri May 27 12:21:15 2016`
**Version**: `16.05.21`
**Build date**: `May 26 2016`
**Build number**: `1685`
**Platform**: `windows`
**Operating System**: `Windows 7`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.5.1`
**Qt Version (runtime)**: `5.5.1`
**Locale (system)**: `en_GB`
**Locale (interface)**: `en`
**Icon theme**: `breeze-qownnotes`

**Comment by pbek** [comment]
thank you for the feedback, I'm working on it, it's pretty tricky...

**Comment by pbek** [comment]
@alfwro13, @prat0088 can you please try the new release 16.05.22.
For some reason the Windows deployment process used a copy of the German translation file as English one, which screws up the English user interface.

**Comment by pbek** [comment]
The release worked on my test box.

**Comment by alfwro13** [comment]
Yep - I can confirm - all working fine now.
Thank you

**Comment by pbek** [comment]
Great, makes me happy! Thank you for testing!
