### ISSUE TITLE
markdown doesn't display properly between two code phrase

### ISSUE THREAD

**Issue by RichardBaker3020** [pbek/QOwnNotes#1842]
Underline, emphasis markdown doesn't display properly if it's between two code phrase, as is shown bellow:

![qownnotes-media-xqXJNt-594357424](https://user-images.githubusercontent.com/54793121/89203245-d4f14f00-d5e6-11ea-90e3-0bcb423c4db5.png)

It will dispaly properly in preview layout btw.

**Comment by pbek** [comment]
Thank you for reporting, reproduced with:

```
`test` **test** `test`
```

@Waqar144

**Comment by Waqar144** [comment]
Looking into it.

**Comment by pbek** [comment]
@Waqar144, the `Fixes pbek/QOwnNotes#1842` in the PR message automatically closes the issue if I accept the PR. 😁

**Comment by pbek** [comment]
## 20.8.2
- Bold and italic highlighting now also works between inline code blocks in the note editor
  (for [#1842](https://github.com/pbek/QOwnNotes/issues/1842), thank you @Waqar144)

**Comment by Waqar144** [comment]
> @Waqar144, the `Fixes pbek/QOwnNotes#1842` in the PR message automatically closes the issue if I accept the PR. grin

I thought it wouldn't work across two repos.

Does that mean we can close issues in other repos randomly? :rofl:

**Comment by pbek** [comment]
The one that accepts the PR (or I guess even makes the direct commit) closes it. I don't like that behavior a lot...

**Comment by pbek** [comment]
@RichardBaker3020, there now is a new release, could you please test it and report if it works for you?

**Comment by RichardBaker3020** [comment]
> @RichardBaker3020, there now is a new release, could you please test it and report if it works for you?

It works well in the new release, thanks for your  work:)

**Comment by pbek** [comment]
Great, thank you for testing!
