### ISSUE TITLE
v20.8.0 crashes on macOS 10.14.6

### ISSUE THREAD

**Issue by rakekniven** [pbek/QOwnNotes#1843]
#### Expected behaviour
QOwnNotes should start

#### Actual behaviour
It hangs a few seconds after start, the colored balls appears and nothing will happen anymore.

#### Steps to reproduce

Updated from 20.7.2 to 20.8.0 using the integrated updater

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

Cannot get the output as the UI freezes

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

Cannot get the output as the UI freezes

</details>

When starting it from Terminal I get this:

/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes 
Info: "QOwnNotes-Server arbeitet auf Port 22222" ((null):0, (null))
Segmentation fault: 11

**Comment by pbek** [comment]
Please see https://github.com/pbek/QOwnNotes/issues/1830#issuecomment-663848189 😅

**Comment by rakekniven** [comment]
Hello, I really used the search before filing a new issue :-(

**Comment by pbek** [comment]
As long as it's the same with the same solution it's ok. 😁
