### ISSUE TITLE
Syncthing sync support

### ISSUE THREAD

**Issue by r00tr4v3n** [pbek/QOwnNotes#1844]
I am currently syncing QON's note folder with Syncthing to my phone and other locations. 
Since I do not want the .git and .sync folder to update and sync with it I created symlinks for the attachments and media folder. This way I can sync a single clean notes folder.
Unfortunately symlinks are not guaranteed to work on Android and thus I cannot open attachments from notes.
How could this be solved?
1. get the symlinks to work on Android
2. forgo the symlinks and sync everything
3. setup an ignore list for Syncthing
4. add custom editable paths for the attachment/media folders
Any other ideas?

**Comment by pbek** [comment]
> Since I do not want the .git and .sync folder to update and sync 

Can't you exclude those folders in Syncthing?

**Comment by Waqar144** [comment]
I think that this be handled with syncthing only.

**Comment by r00tr4v3n** [comment]
OK, thanks.
