### ISSUE TITLE
TaskPaper support

### ISSUE THREAD

**Issue by prat0088** [pbek/QOwnNotes#185]
It would be nice to have basic TaskPaper support.  Syntax highlighting, TOC navigation, and indentation should be a good starting point.  It's popular on Mac and iOS.  Many editors that support Markdown support TaskPaper.  There are also dedicated apps.

If you aren't familiar with TaskPaper [here is a link](http://leancrew.com/all-this/2011/11/the-return-of-taskpaper/) that gives a good overview with screenshots.

**Comment by pbek** [comment]
Thank you for your suggestion.

Why do you think we would want to rewrite parts of the app to add TaskPaper support to QOwnNotes (even if there would be a component to do the highlighting)?
I don't really see a reason, an advantage and ownCloud notes doesn't support it neither...

QOwnNotes relies on <https://github.com/ali-rantakari/peg-markdown-highlight> for it's (markdown) highlighting.

**Comment by prat0088** [comment]
I suppose it comes down to philosophy about QOwnNotes.  Is it an OwnNotes client?  Then I agree if OwnNotes doesn't support taskpaper then QOwnNotes shouldn't, either (although [here](https://github.com/Fmstrat/ownnote/issues/127)'s a feature request for todos and somebody suggests taskpaper as the format).

However, I think QOwnNotes has so much potential beyond an OwnNotes client, and I see that in the writing on the [project's homepage](http://www.qownnotes.org/).  I have no desire to use OwnNotes, but I do want to use QOwnNotes to edit my my .txt, .md, and .taskpaper files on Windows and sync via Dropbox to iPhone.

* "Your notes on your hard disk and in your own cloud."
* "Plain-text file notepad with markdown support and ownCloud integration."
* "QOwnNotes is the open source (GPL) plain-text file notepad with markdown support and todo list manager for GNU/Linux, Mac OS X and Windows, that (optionally) works together with the notes application of ownCloud."

Taskpaper is a great plain-text format for lists and todos, with [nearly a dozen apps on the iOS app store](http://appshopper.com/search?search=taskpaper), vim plugins, and sublime text plugins.  Many of the iOS apps support both formats.  QOwnNotes claims to be a todo list manager and plain-text notepad.  Seems like a very natural match to me.

What parts would have to be re-written?  Could the editor not be made pluggable to support arbitrary file formats?  Then it would be a matter of finding or writing syntax highlighting support for taskpaper.

Is it because OwnNote doesn't support taskpaper that you wouldn't want to either?

**Comment by prat0088** [comment]
At the very least, could user-defined file extensions be added so that we could view .taskpaper and other plain text files that don't have the standard .txt extension?

**Comment by pbek** [comment]
No, QOwnNotes is no OwnNote client. ;)
see: <http://www.qownnotes.org/Knowledge-base/Does-QOwnNotes-support-ownNote>

QOwnNotes' task support is limited to being a CalDav frontend for ownCloud.
And I only implemented it because there was no useful alternative under Linux that I was aware of.

Tasks in notes are not supported at all and a lot of note features are tightly knit to ownCloud notes' features. Most of the interaction with the editor make markdown mandatory. QOwnNotes is no versatile text editor, there are lots of them out there. To make your wish possible QOwnNotes would have to be rewritten from scratch. 😸

**Comment by pbek** [comment]
> At the very least, could user-defined file extensions be added so that we could view .taskpaper and other plain text files that don't have the standard .txt extension?

The QOwnNotesApi ownCloud app would also needed to be modified for that (which is a pain in the bum, because of ownCloud's certification process), but it would be possible.

Please make an other feature request for this.

**Comment by pbek** [comment]
from the just released v16.05.23:
- it is now possible to add **custom note file extensions** in the settings
    - these file extensions will be recognized in the note list and you can 
      create new notes with them
    - they will also work with the ownCloud note versions and the trash feature 
      (for the latter you have to update QOwnNotesAPI on your ownCloud 
      server to version 0.4.4)

@prat0088 can you please test it and report back?

**Comment by prat0088** [comment]
Fantastic! It would still be nice to have syntax highlighting, but at least I can use QOwnNotes to view and make edits.  Thank you.

**Comment by pbek** [comment]
No problem, I hope QOwnNotesAPI gets approved again by ownCloud in the next weeks... :)
