### ISSUE TITLE
Hide folders to improve panel space usage

### ISSUE THREAD

**Issue by fabianski7** [pbek/QOwnNotes#1850]
When only one folder is configured as a note directory, the QON could hide the main folder and display only the subfolders. If you have more than one folder configured, then the current behavior would be maintained.
What do you think about this?

![image](https://user-images.githubusercontent.com/1798101/89739107-2170da80-da7e-11ea-8368-e1a6995cf4e1.png)

**Comment by pbek** [comment]
You can turn off sub-folder support for individual note folders. Is that what you are talking about?

**Comment by fabianski7** [comment]
I still intend to use the subfolders, but I only use one main folder. So this will be very useful in those cases, even more so for those who have a small monitor

**Comment by pbek** [comment]
> but I only use one main folder.

what is "one main folder"? the note-folder?
or one level sub-folders?

I still don't understand what you want to achieve, but I think there is a checkbox in the Panel settings that can help you. Play with these:

![image](https://user-images.githubusercontent.com/1798101/89739149-84627180-da7e-11ea-8cf4-b3725ac6e7a4.png)

**Comment by fabianski7** [comment]
Yes. That's exactly it. I hadn't noticed.
Maybe this could be the default behavior for when only a note folder is used. 

[Before](https://upload.vaa.red/cYwiR#iI2fluT3Cui44KBLmirmeDSLVRgve1Pd) and [after](https://upload.vaa.red/8pWAV#2ZQivdFG6qV5qiLCSJFZiZkniXAT6vS8). much better now!

**Comment by pbek** [comment]
> Yes. That's exactly it. I hadn't noticed.

great!

> Maybe this could be the default behavior for when only a note folder is used.

It's a setting there are people that prefer it one and and others the other was. I guess that shouldn't be just switched without the knowledge of the user just because today there is only one level of folders and tomorrow there are two levels... 😁

**Comment by fabianski7** [comment]
I suggested this because while I was looking in the settings if there was already the possibility to do this, I really didn't find this option or the description of it didn't make it clear enough.

I have a small monitor and this helped save space as well as making it more minimalist. I just thought it might be useful for more people if it was enabled by default, but since you disagree, then fine xD
