### ISSUE TITLE
Request for touch-and-scroll style navigation for touchscreen use

### ISSUE THREAD

**Issue by nonplayer** [pbek/QOwnNotes#1852]
Okay I admit this is an odd one, and I'm not 100% sure how to word this, but I'll give it a go. As mentioned in a previous issue, I heavily use QOwnNotes on a variety of machines, one of which is a 32bit Windows 10 tablet. One very minor annoyance I experience is that if I touch a document or preview and try to drag it up or down, instead it just highlights text. it's the only time I have to use a keyboard to navigate an otherwise touch-friendly app.

In contrast, the other text app I use is Notepad++, which works as expected with touch and drag.

If there's a possibility of adding some kind of target=document option for selection, that would be rad.

**Comment by pbek** [comment]
> One very minor annoyance I experience is that if I touch a document or preview and try to drag it up or down, instead it just highlights text.

I guess that's the way the touch events are getting interpreted in a `QTextEdit`. If you want you can try to build QOwnNotes yourself (see https://www.qownnotes.org/installation#building) and test what happens if you turn off selection altogether in the note edit and preview. I don't have a Windows touch device to test that.

> If there's a possibility of adding some kind of target=document option for selection

Can you please explain what you mean by "target=document option for selection".

**Comment by nonplayer** [comment]
Hah yeah I will try to explain, I code very very little and usually only to jury rig a script. I use QOwnNotes primarily as a doc management tool for my writing, which I do entirely in markdown. It's sinful how there are so few good Markdown writing apps, and this one's one of the best.

Basically is there a way to set the app so that a touch or click doesn't always activate the cursor at the point of click, instead only doing so if the user clicks into text, and selecting the document object itself as a default outside of that?

**Comment by pbek** [comment]
> It's sinful how there are so few good Markdown writing apps, and this one's one of the best.

Well, thank you 😁 

> Basically is there a way to set the app so that a touch or click doesn't always activate the cursor at the point of click, instead only doing so if the user clicks into text, and selecting the document object itself as a default outside of that?

I don't know, but there is a flag to disable selecting by mouse altogether (selecting by keyboard should still work). But you would need to test that flag yourself...

**Comment by nonplayer** [comment]
I'm willing to try! I dug through the config and docs, and I'm not finding this mentioned. Where/how would I enable this flag?

**Comment by pbek** [comment]
Great. 

1) Open `mainwindow.ui` in the project
2) Click on the `noteTextEdit`
3) Disable `TextSelectableByMouse`

**Comment by pbek** [comment]
Then you can build the project with `Ctrl + R`.

**Comment by pbek** [comment]
I will close this issue until there is more information.
