### ISSUE TITLE
Two hosts running QOwnNotes under same NextCloud login and path corrupts notes

### ISSUE THREAD

**Issue by adam-burns** [pbek/QOwnNotes#1853]
#### Expected behaviour
Two hosts should sync as cleanly as possible

#### Actual behaviour
Two client hosts running QOwnNotes on same NextCloud account & path corrupts notes	

#### Steps to reproduce
Run two client hosts with same NextCloud account and path configured

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed Aug 12 18:26:27 2020`
**Version**: `20.8.3`
**Build date**: `Aug  9 2020`
**Build number**: `747`
**Platform**: `linux`
**Operating System**: `Fedora 32 (Thirty Two)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.14.2`
**Portable mode**: `no`
**Settings path / key**: `/home/vortex/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/vortex/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_GB`
**Locale (interface)**: *empty*
**Primary screen resolution**: `2880x1620`
**Screen resolution(s)**: `2880x1620, 3840x2160`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `108`
**Calendar items**: `38`
**Enabled scripts**: `3`

## Server Info

**serverUrl**: `https://nextcloud.networkcommons.org`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `17.0.3.1`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `de_AT, de_BE, de_CH, de_DE, de_LI, de_LU, en_AG, en_AU, en_BS, en_BW, en_BZ, en_CA, en_DK, en_GB, en_GH, en_HK, en_IE, en_IN, en_JM, en_MW, en_NA, en_NG, en_NZ, en_PH, en_SG, en_TT, en_US, en_ZA, en_ZM, en_ZW`
**Language names**: `Österreichisches Deutsch (Österreich), Deutsch (Belgien), Schweizer Hochdeutsch (Schweiz), Deutsch (Deutschland), Deutsch (Liechtenstein), Deutsch (Luxemburg), English (Antigua & Barbuda), Australian English (Australia), English (Bahamas), English (Botswana), English (Belize), Canadian English (Canada), English (Denmark), British English (United Kingdom), English (Ghana), English (Hong Kong SAR China), English (Ireland), English (India), English (Jamaica), English (Malawi), English (Namibia), English (Nigeria), English (New Zealand), English (Philippines), English (Singapore), English (Trinidad & Tobago), American English (United States), English (South Africa), English (Zambia), English (Zimbabwe)`
**Application dictionaries path**: `/home/vortex/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/vortex/nextcloud.networkcommons.org/Personal/Notes`
**remotePath**: `Personal/Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/vortex/nextcloud.networkcommons.org/Personal/Notes/notes.sqlite`

### Cloud connection `networkcommons`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://nextcloud.networkcommons.org`
**username**: `adamb`

### Script `PGP Encryption`

**id**: `1`
**path**: `/home/vortex/.local/share/PBE/QOwnNotes/scripts/encryption-pgp/encryption-pgp.qml`
**variablesJson**: 
```
{
    "gpgPath": "/usr/bin/gpg",
    "publicKey": "F5161BD3"
}
```
**identifier**: `encryption-pgp`
**version**: `0.0.2`
**minAppVersion**: `17.05.7`

### Script `Export notes as one HTML file`

**id**: `2`
**path**: `/home/vortex/.local/share/PBE/QOwnNotes/scripts/export-notes-as-one-html/export-notes-as-one-html.qml`
**variablesJson**: *empty*
**identifier**: `export-notes-as-one-html`
**version**: `1.0.0`
**minAppVersion**: `18.03.7`

### Script `Headline depth buttons`

**id**: `3`
**path**: `/home/vortex/.local/share/PBE/QOwnNotes/scripts/headline-depth/headline-depth.qml`
**variablesJson**: *empty*
**identifier**: `headline-depth`
**version**: `0.0.2`
**minAppVersion**: `17.07.8`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `33`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `/home/vortex/Documents/Personal/Organisations/MiCT/Pocket FM/Deployment`
**FileDialog/LastPath-InsertImage** (QString): `/home/vortex/Pictures`
**FileDialog/LastPath-NoteHTMLExport** (QString): `/home/vortex/Documents/Personal/Organisations/MiCT/Pocket FM/Deployment`
**FileDialog/LastPath-NoteMarkdownExport** (QString): `/home/vortex/Documents/Personal/Organisations/MiCT/Pocket FM/Deployment`
**ImageDialog/disableCopying** (QString): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-08-12T17:46:17.486`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Monospace,14,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Sans Serif,14,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Monospace,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Sans Serif,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**MessageBoxOverride/move-notes** (QString): `16384`
**MessageBoxOverride/remove-notes** (QString): `16384`
**MessageBoxOverride/remove-todo-items** (QString): `16384`
**NoteFolder-1/NoteTabNameList** (QStringList): `2020-04-19T10.15.13 Dyne System Services, 2020-08-03T20.13.44 ISOC CN SIG Informal Meeting, Note 2020-07-25T15.07.11 Shopping List, 2020-07-17T16.53.04 The one thing with human beings is ...`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `, , , `
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `199`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `2`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Personal`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**VersionDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (bool): `false`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `27`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/vortex/nextcloud.networkcommons.org/Personal/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList** (QString): `Personal`
**ownCloud/todoCalendarEnabledList** (QString): `Personal`
**ownCloud/todoCalendarEnabledUrlList** (QString): `https://nextcloud.networkcommons.org/remote.php/dav/calendars/adamb/personal/`
**ownCloud/todoCalendarUrlList** (QString): `https://nextcloud.networkcommons.org/remote.php/dav/calendars/adamb/personal/`
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `17.0.3.1`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `resource, Note 2020-08-06T16.25.28, Note 2020-08-06T14.03.57, Note 2020-08-06T12.57.02, Note 2020-08-03T20.13.44, Note 2020-08-02T18.55.04, Note 2020-07-31T16.50.55, Note 2020-07-31T08.26.09, Note 2020-07-30T23.37.32, Note 2020-07-30T20.36.32, Note 2020-07-30T17.22.15, Note 2020-07-28T11.05.41, Note 2020-07-27T22.40.23, Note 2020-07-25T15.07.11, Jaromil, Note 2020-07-24T11.09.24, Note 2020-07-23T12.18.32, git, Note 2020-07-21T17.54.52, Note 2020-07-21T12.22.41, Note 2020-07-19T08.22.33, Note 2020-07-18T20.28.34, Note 2020-07-17T16.53.04, Note 2020-07-15T16.25.16, Note 2020-07-15T10.37.06, Note 2020-07-15T10.02.09, Note 2020-07-12T23.03.19, Note 2020-07-10T18.49.50, Note 2020-07-10T07.03.58, Note 2020-07-08T23.31.44, Note 2020-07-06T15.04.39, Note 2020-06-29T12.16.19, Note 2020-06-27T09.37.57, Note 2020-06-26T18.16.01, Note 2020-06-23T13.37.06, Note 2020-06-23T11.11.15, Note 2020-06-23T11.08.08, Note 2020-06-22T23.56.18, Note 2020-06-22T23.13.49, log, devuan, Note 2020-06-19T07.30.14, Note 2020-06-18T12.54.28, Note 2020-06-17T23.50.59, Dyne: Project: Reflow, Note 2020-06-17T09.43.27, Note 2020-06-17T09.42.33, MiCT: Proposal: IDRC: COVID-19 Global South Artificial Intelligence and Data Innovation Program, MiCT: Proposal: Internet Freedom Fund, Note 2020-06-16T13.19.36, Note 2020-06-16T09.41.26, Note 2020-06-15T16.46.53, Note 2020-06-12T23.21.21, Note 2020-06-12T17.30.18, gentoo, Note 2020-06-12T14.10.57, Note 2020-06-11T11.24.37, Note 2020-06-09T19.40.15, Note 2020-06-09T19.08.20, Note 2020-06-09T08.38.00, Note 2020-06-09T08.36.48, Evelyn, Note 2020-06-08T13.11.31, Note 2020-06-08T13.04.21, Note 2020-06-07T15.24.09, Note 2020-06-04T22.53.31, MiCT: GIZ: Burkina Faso, Note 2020-06-04T12.09.20, CNSIG: Reply to list re position, Note 2020-06-02T11.13.38, Note 2020-05-29T11.26.21, Note 2020-05-29T11.16.14, Admin: Dyne: Contract, Note 2020-05-28T12.45.28, Note 2020-05-26T11.31.43, Note 2020-05-25T12.04.15, Note 2020-05-24T15.15.21, Note 2020-05-23T23.28.51, Note 2020-05-23T17.19.19, Note 2020-05-23T14.58.31, Note 2020-05-23T09.17.03, Note 2020-05-23T09.11.59, Note 2020-05-22T20.33.52, Note 2020-05-20T10.02.08, Note 2020-05-19T09.33.18, Note 2020-05-19T07.24.41, Note 2020-05-17T16.48.01, Note 2020-05-17T12.29.03, Note 2020-05-16T13.04.21, Note 2020-05-15T14.54.58, Note 2020-05-14T11.03.36, Note 2020-05-13T14.16.14, Note 2020-05-12T18.01.42, Note 2020-05-12T14.08.23, Note 2020-05-12T11.39.10, Note 2020-05-12T09.02.38, Note 2020-05-11T17.02.56, Note 2020-05-11T10.25.45, Note 2020-05-08T22.09.49, Note 2020-05-07T22.32.40`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useUNIXNewline** (QString): `false`
**versionSplitterSizes** (QByteArray): `<binary data>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**webSocketServerService/token** (QString): `Maqnrs83`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**BASH_ENV**: `/usr/share/lmod/lmod/init/bash`
**BASH_FUNC_ml%%**: 
```
() {  eval $($LMOD_DIR/ml_cmd "$@")
}
```
**BASH_FUNC_module%%**: 
```
() {  eval $($LMOD_CMD bash "$@") && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
}
```
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**DESKTOP_SESSION**: `/usr/share/xsessions/plasma`
**DISPLAY**: `:0`
**GDK_CORE_DEVICE_EVENTS**: `1`
**GOPATH**: `/home/vortex/go`
**GTK2_RC_FILES**: `/home/vortex/.gtkrc-2.0-kde4`
**HISTCONTROL**: `ignoredups`
**HISTSIZE**: `1000`
**HOME**: `/home/vortex`
**HOSTNAME**: `siluvian2.localdomain`
**KDEDIRS**: `/usr`
**KDE_FULL_SESSION**: `true`
**KDE_SESSION_UID**: `1000`
**KDE_SESSION_VERSION**: `5`
**LANG**: `en_GB.UTF-8`
**LANGUAGE**: `en_GB`
**LESSOPEN**: `||/usr/bin/lesspipe.sh %s`
**LMOD_CMD**: `/usr/share/lmod/lmod/libexec/lmod`
**LMOD_DIR**: `/usr/share/lmod/lmod/libexec`
**LMOD_PKG**: `/usr/share/lmod/lmod`
**LMOD_ROOT**: `/usr/share/lmod`
**LMOD_SETTARG_FULL_SUPPORT**: `no`
**LMOD_VERSION**: `8.2.10`
**LMOD_sys**: `Linux`
**LOGNAME**: `vortex`
**MAIL**: `/var/spool/mail/vortex`
**MANPATH**: `/usr/share/lmod/lmod/share/man:`
**MODULEPATH**: `/etc/modulefiles:/usr/share/modulefiles:/usr/share/modulefiles/Linux:/usr/share/modulefiles/Core:/usr/share/lmod/lmod/modulefiles/Core`
**MODULEPATH_ROOT**: `/usr/share/modulefiles`
**MODULESHOME**: `/usr/share/lmod/lmod`
**PATH**: `/home/vortex/.local/bin:/home/vortex/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/vortex/go/bin`
**PWD**: `/home/vortex`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**SHELL**: `/bin/bash`
**SHLVL**: `0`
**SSH_AGENT_PID**: `2263`
**SSH_ASKPASS**: `/usr/bin/ksshaskpass`
**SSH_AUTH_SOCK**: `/tmp/ssh-1dwMfi13cbse/agent.2236`
**USER**: `vortex`
**XAUTHORITY**: `/home/vortex/.Xauthority`
**XCURSOR_THEME**: `breeze_cursors`
**XDG_CONFIG_DIRS**: `/etc/xdg:/usr/share/kde-settings/kde-profile/default/xdg`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_DATA_DIRS**: `/home/vortex/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share`
**XDG_MENU_PREFIX**: `kf5-`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_SEAT**: `seat0`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_DESKTOP**: `KDE`
**XDG_SESSION_ID**: `2`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**XDG_SESSION_TYPE**: `x11`
**XDG_VTNR**: `1`
**_**: `/usr/bin/startplasma-x11`
**SESSION_MANAGER**: `local/unix:@/tmp/.ICE-unix/2360,unix/unix:/tmp/.ICE-unix/2360`

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Can you please be a little more specific. I use the same Nextcloud account on about 20 devices...

**Comment by pbek** [comment]
And QOwnNotes doesn't do any syncing...

**Comment by adam-burns** [comment]
> Can you please be a little more specific. I use the same Nextcloud account on about 20 devices...

OK. That gives me hope. Thanks for the reply, and apologies for not being specific enough. I am running QOwnNotes on 2 laptops (both Fedora 32 with the QOwnNotes repo added). One laptop is my main working machine and on its own all works fine, in fact I have found it to be a wonderful tool. The other machine with QOwnNotes installed remains turned off for long periods of time. When I boot up the secondary then go back to my primary, some previous recent md notes have become zero length files I use git to keep a local history of my notes and at this point the git repository reports:

```
git status
fatal: .git/index: index file smaller than expected

```

I understand this is still observation based. This is the second occurrence, so in order to test or try again to log or debug, I want to be very careful about taking snapshot backups, as I have come to like and rely on this tool.

Thanks for QOwnNotes and your reply.

**Comment by pbek** [comment]
> in fact I have found it to be a wonderful tool.

thank you! 😁 

> fatal: .git/index: index file smaller than expected

Nextcloud sync doesn't sync `.git` folders (or at least it should not), I don't know what destroys your index. QOwnNotes is ignoring folders starting with `.` by default. Is there anything the in the log of the NC sync client? And is there any other tool in action that accesses the note folder?

I have a lot of computers with all kinds of Linux distributions and also macOS and Windows. Some of them are also turned on very seldomly. I haven't lost a note yet, so it would be great if you could reproduce your issue.

**Comment by adam-burns** [comment]
> > in fact I have found it to be a wonderful tool.
> 
> thank you! grin
> 
> > fatal: .git/index: index file smaller than expected
> 
> Nextcloud sync doesn't sync `.git` folders (or at least it should not), I don't know what destroys your index.

Jesus on a bicycle. That was it! For some reason the nc clients were syncing the .git directories.

No wonder it made a mess.

I believe that would be my issue, but I'll keep an eye out.

Thanks.

**Comment by pbek** [comment]
Ok, great. Let me know if you find something. 😁
