### ISSUE TITLE
Functions request

### ISSUE THREAD

**Issue by yuxiacn** [pbek/QOwnNotes#1855]
Request some functions, as following:

1. Program embedded Auto-Completion of English words. I don't know how to deal with so called plugins.

2. Global search of Keywords (including all the contents and the titles/names of sub-directory and items) . In the current versions, only the contents could be searched, while the titles/names of sub-directory and items can not be found by the search function.

3. The system tray icon looks not so nice.

file:///run/media/pop/Temp/0_Download/2_æˆªå›¾æ–‡ä»¶å¤¹/æ·±åº¦æˆªå›¾_é€‰æ‹©åŒºåŸŸ_20200816141618.png

**Comment by yuxiacn** [comment]
The github experience is awful, I don't know how to upload an image.

**Comment by yuxiacn** [comment]
![深度截图_选择区域_20200816141618](https://user-images.githubusercontent.com/67862022/90328295-e0248180-dfcd-11ea-8bda-c6e768920f5a.png)

**Comment by yuxiacn** [comment]
cAlthogh the image can be uploaded (I copyed the image to the home dir from the original one), the experience is still not good.  Can the github edit be replaced by a more functional one :-)

**Comment by pbek** [comment]
> Program embedded Auto-Completion of English words. 

You could do that with https://docs.qownnotes.org/en/latest/scripting/hooks/#autocompletionhook and your own wordlist.

@Waqar144, would it be very inperformant if we would allow that via the spell checker?

> I don't know how to deal with so called plugins.

I could help you with that.

> Global search of Keywords (including all the contents and the titles/names of sub-directory and items) . In the current versions, only the contents could be searched, while the titles/names of sub-directory and items can not be found by the search function.

In the note list you can search for note names and text in the note. In the note sub-folder list you can search for sub-folders.

> The system tray icon looks not so nice.

It almost looks the same as your other icons. I think the icon left from it doesn't fit it. 😆 There also is a setting to turn off the dark mode app/tray icon and use the regular one.

**Comment by yuxiacn** [comment]
Thanks, but I still want the auto-comletion function be integrated into the program rather than using a "hook", I still don't know how to deal with the hook. :-(

The search function I tried according to your words is OK, thanks.

By the way, a more professional/beautiful icon(s) brings better feelings to the user. I use your program everyday now :-).

**Comment by pbek** [comment]
> By the way, a more professional/beautiful icon(s) brings better feelings to the user. I use your program everyday now :-).

This dark mode icon was a contribution and I think it looks very well for a dark mode icon. It's a note with cloud in it. Feel free to contribute another icon I we'll take a look at it.

**Comment by pbek** [comment]
> I still don't know how to deal with the hook.

You could read the text of a word list with https://docs.qownnotes.org/en/latest/scripting/methods-and-objects/#reading-text-from-a-file (e.g. the one from the spell checker), then get the current word (like in the autocompletionHook example) and search for the word in the word list. Then you can return the found words in autocompletionHook.

**Comment by yuxiacn** [comment]
> > I still don't know how to deal with the hook.
> 
> You could read the text of a word list with https://docs.qownnotes.org/en/latest/scripting/methods-and-objects/#reading-text-from-a-file (e.g. the one from the spell checker), then get the current word (like in the autocompletionHook example) and search for the word in the word list. Then you can return the found words in autocompletionHook.

Ok, but I still dont understand so difficult a setting. It's no problem, but if the auto-completion function can be automatically launched with the program is better.

As your instructions, I changed to a dark mode theme, however, the system tray icon is still like this. Another icon I tried is something like a whole dark-blue icon and can not be seen clearly.

These are little problems and don't affect the daily use. If these could be imporved is better. Thank you.

![深度截图_选择区域_20200816150914](https://user-images.githubusercontent.com/67862022/90328990-74ddae00-dfd3-11ea-8a19-1723cf5e1fa1.png)

**Comment by pbek** [comment]
If you want to fix the "easy things" I'll happily wait for your pull requests. 😁

**Comment by yuxiacn** [comment]
> If you want to fix the "easy things" I'll happily wait for your pull requests.

I am not a specialist on this "easy things". These are not so easy for me :-)

**Comment by pbek** [comment]
Then I wonder how you know that they are easy at all. 😉

**Comment by pbek** [comment]
> Program embedded Auto-Completion of English words. I don't know how to deal with so called plugins.

I'll write a script, please head over to #1817.

**Comment by pbek** [comment]
> Program embedded Auto-Completion of English words. I don't know how to deal with so called plugins.

I'll write a script, please head over to #1817.
