### ISSUE TITLE
Quirk in autoremoval single quotes

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#1857]
Pressing <kbd>Backspace</kbd> after a single quote results in:

![Peek 2020-08-20 11-38](https://user-images.githubusercontent.com/5956570/90754019-a0191380-e2d9-11ea-98a9-b1c5823510ac.gif)

No biggie, but could use some finetuning :)

## General Info

**Current Date**: `do aug. 20 11:40:51 2020`
**Version**: `20.8.6`
**Build date**: `Aug 19 2020`
**Build number**: `750`
**Platform**: `linux`
**Operating System**: `Manjaro Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.0`
**Qt Version (runtime)**: `5.15.0`
**Portable mode**: `no`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `2560x1440`
**Icon theme**: `breeze-dark`
**Notes in current note folder**: `1198`
**Calendar items**: `5`
**Enabled scripts**: `7`

## Spellchecking

**Enabled**: `false`
**Selected language**: `auto`

**Comment by pbek** [comment]
@Waqar144 ? 😁

**Comment by pbek** [comment]
## 20.8.9
- fixed a problem with pressing `Backspace` after a `'` in lists
  (for [#1857](https://github.com/pbek/QOwnNotes/issues/1857), thank you @Waqar144)

**Comment by sanderboom** [comment]
Looks good! Thanks @Waqar144 :rocket:

**Comment by pbek** [comment]
Great, thank you for testing!
