### ISSUE TITLE
[I] Data loss on encrypted notes

### ISSUE THREAD

**Issue by johnZ-cyber** [pbek/QOwnNotes#1858]
#### Expected behaviour
Save encrypted notes automatically (maybe?)

#### Actual behaviour
when an encrypted note is being edited and then switching to another note without saving the previous one can result in data loss. Saving the note before going to another note solves this. 

#### Steps to reproduce
[video here](https://cryptpad.fr/file/#/3/file/aed318dc82c26b0b27a52c8bbf5314d006001782c3c2c264/)

1. Encrypt a note
2. Enter into edit mode
3. Add a text
4. Switch to another note
5. When returning to the encrypted note, the previously inserted text will have been lost

#### Additional information
https://github.com/qownnotes/scripts/issues/104

**Comment by pbek** [comment]
If the encrypted note isn't stored to disk yet and you edit it again after you switched to an other note you will see the last stored encrypted note (without the changes after the last storing). Nothing bad will happen when you don't change the text, the note will be stored correctly in the background, but if you edit the note the text is lost.

I'll try to improve that.

**Comment by pbek** [comment]
## 20.8.8
- fixed a problem where you could loose changes to an encrypted note if you switch
  to another note and back to the encrypted note and then immediately edit it again
  before the encrypted note was stored to disk

There now is a new release, could you please test it and report if it works for you?

**Comment by johnZ-cyber** [comment]
everything fine now, thank you!

**Comment by pbek** [comment]
Great, thank you for testing!
