### ISSUE TITLE
Note history vs. previous or next note

### ISSUE THREAD

**Issue by PurplePlums** [pbek/QOwnNotes#1862]
#### Expected behaviour

Navigate between notes back and forth more easily

#### Actual behaviour

In the standard panel order for navigating I need to pull down a menu and select an option, while two sorts of navigating are listed under each other and I need to pay attention to select the right one as well as taking the time of doing so - given that I am not much using shortcuts, and I would often forget which action does what and then check again, also I find it to be a bit too many actions to navigate.

#### Steps to reproduce

Select "Note", then select "Navigation" and then chose either

back in note history
forward in note history

previous note
next note

#### Output from the debug section in the settings dialog

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mo. Aug. 31 11:27:15 2020`
**Version**: `20.8.10`
**Build date**: `Aug 23 2020`
**Build number**: `754`
**Platform**: `macosx`
**Operating System**: `macOS High Sierra (10.13)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.1`
**Qt Version (runtime)**: `5.15.1`
**Portable mode**: `no`
**Settings path / key**: `/Users/amyfabijennalang/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/amyfabijennalang/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Users/amyfabijennalang/Desktop/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `de_AT`
**Locale (interface)**: `en`
**Primary screen resolution**: `2560x1440`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `306`
**Calendar items**: `0`
**Enabled scripts**: `5`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `en_GB`
**Language codes**: `de_DE_frami, en_GB, hu_HU, nl_NL`
**Language names**: `Deutsch (Deutschland), British English (United Kingdom), magyar (Magyarország), Nederlands (Nederland)`
**Application dictionaries path**: `/Users/amyfabijennalang/Library/Application Support/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Standard`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/Users/amyfabijennalang/ownCloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/Users/amyfabijennalang/ownCloud/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: `Fabijenna`

### Script `Export notes as one HTML file`

**id**: `10`
**path**: `/Users/amyfabijennalang/Library/Application Support/PBE/QOwnNotes/scripts/export-notes-as-one-html/export-notes-as-one-html.qml`
**variablesJson**: *empty*
**identifier**: `export-notes-as-one-html`
**version**: `1.0.0`
**minAppVersion**: `18.03.7`

### Script `Favorite note`

**id**: `11`
**path**: `/Users/amyfabijennalang/Library/Application Support/PBE/QOwnNotes/scripts/favorite-note/favorite-note.qml`
**variablesJson**: *empty*
**identifier**: `favorite-note`
**version**: `0.0.1`
**minAppVersion**: `17.05.6`

### Script `Image preview`

**id**: `12`
**path**: `/Users/amyfabijennalang/Library/Application Support/PBE/QOwnNotes/scripts/image-preview/image-preview.qml`
**variablesJson**: 
```
{
    "maxWidth": 640
}
```
**identifier**: `image-preview`
**version**: `1.0.1`
**minAppVersion**: `20.6.0`

### Script `Un-wrap Text`

**id**: `13`
**path**: `/Users/amyfabijennalang/Library/Application Support/PBE/QOwnNotes/scripts/unwrap/unwrap.qml`
**variablesJson**: *empty*
**identifier**: `unwrap`
**version**: `1.0.0`
**minAppVersion**: `18.04.3`

### Script `List maker`

**id**: `14`
**path**: `/Users/amyfabijennalang/Library/Application Support/PBE/QOwnNotes/scripts/list-maker/list-maker.qml`
**variablesJson**: 
```
{
    "setLetters": "abcdefghijklmnopqrstuvwxyz",
    "setMarkers": "- • ‣"
}
```
**identifier**: `list-maker`
**version**: `0.0.2`
**minAppVersion**: `17.07.8`

## Settings

**AKAI professional LLC LPK25** (QString): `1`
**AKLastCheckInAttemptDate** (QDateTime): `2020-02-25T14:11:29.770`
**AKLastCheckInSuccessDate** (QDateTime): `2020-02-25T14:11:31.775`
**AKLastEmailListRequestDateKey** (QDateTime): `2020-08-29T16:26:52.329`
**AKLastIDMSEnvironment** (qlonglong): `0`
**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Canon Inc/ Canon Digital Camera** (QString): `1`
**Compx 2/4G Receiver** (QString): `1`
**Country** (QString): `AT`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `true`
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**DistractionFreeMode/editorWidthMode** (qlonglong): `2`
**DistractionFreeMode/isEnabled** (bool): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (qlonglong): `0`
**DistractionFreeMode/menuBarVisible** (bool): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-650b75f1-ad37-4129-a0a9-7918a7a0eb24`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/centerCursor** (bool): `false`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (qlonglong): `4`
**Editor/removeTrainingSpaces** (bool): `false`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**EvernoteImportDialog/geometry** (QByteArray): `<binary data>`
**FileDialog/LastPath** (QString): `/Users/amyfabijennalang/Documents`
**FileDialog/LastPath-InsertImage** (QString): `/Users/amyfabijennalang/Desktop`
**FileDialog/LastPath-NoteHTMLExport** (QString): `/Users/amyfabijennalang/Documents`
**FileDialog/LastPath-NoteMarkdownExport** (QString): `/Users/amyfabijennalang/Documents`
**FileDialog/LastPath-NotePDFExport** (QString): `/Users/amyfabijennalang/Documents`
**FileDialog/LastPath-PreviewHTMLFileExport** (QString): `/Users/amyfabijennalang/Desktop`
**HP ENVY 4520 series** (QString): `1`
**ImageDialog/disableCopying** (bool): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**InitialKeyRepeat** (qlonglong): `25`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**KeyRepeat** (qlonglong): `2`
**LastUpdateCheck** (QDateTime): `2020-08-31T11:02:44.755`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (qlonglong): `32`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Rawfood diet/Issues, Diaries, Dissertation`
**MainWindow/noteTextEdit.code.font** (QString): `Monaco,18,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Arial,18,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Monaco,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `.SF NS Text,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**MessageBoxOverride/auto-script-update** (qlonglong): `16384`
**MessageBoxOverride/move-notes** (qlonglong): `16384`
**MessageBoxOverride/remove-folders** (qlonglong): `16384`
**MessageBoxOverride/remove-note-folder** (qlonglong): `16384`
**MessageBoxOverride/remove-notes** (qlonglong): `16384`
**MessageBoxOverride/update-and-restart** (qlonglong): `16384`
**MultipleSessionEnabled** (bool): `true`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): `QON User Guide`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteFolder-1/allowDifferentNoteFileName** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-1** (qlonglong): `195`
**PKSecureElementAvailableFlags** (qlonglong): `1`
**PKSecureElementAvailableFlagsByHost** (qlonglong): `1`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExportOrientation** (qlonglong): `1`
**Printer/NotePDFExportPageSize** (qlonglong): `3`
**SanDisk Cruzer Edge** (QString): `1`
**SanDisk Cruzer Fit** (QString): `1`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (qlonglong): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-customAction_addHighlights** (QString): *empty*
**Shortcuts/MainWindow-customAction_exportHTML** (QString): *empty*
**Shortcuts/MainWindow-customAction_favoriteNote** (QString): *empty*
**Shortcuts/MainWindow-customAction_insertText** (QString): *empty*
**Shortcuts/MainWindow-customAction_insertTranslatorText** (QString): *empty*
**Shortcuts/MainWindow-customAction_journalEntry** (QString): *empty*
**Shortcuts/MainWindow-customAction_journalEntryTomorrow** (QString): *empty*
**Shortcuts/MainWindow-customAction_pasteFromSkypeHistory** (QString): *empty*
**ShowSystemTray** (bool): `true`
**StartHidden** (bool): `false`
**SyncServicesServerWasActive** (bool): `true`
**TableDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WebAutomaticSpellingCorrectionEnabled** (bool): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `false`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (bool): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (qlonglong): `1`
**currentWorkspace** (QString): `aa4da425-54cd-4949-8149-15c005190fe7`
**cursorWidth** (qlonglong): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `true`
**darkModeColors** (bool): `true`
**darkModeIconTheme** (bool): `true`
**darkModeTrayIcon** (bool): `true`
**defaultNoteFileExtension** (QString): `txt`
**demoNotesCreated** (bool): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (bool): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (qlonglong): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `true`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (qlonglong): `1024`
**imageScaleDownMaximumWidth** (qlonglong): `1024`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (qlonglong): `11`
**interfaceLanguage** (QString): `en`
**interfaceStyle** (QString): `macintosh`
**internalIconTheme** (bool): `true`
**itemHeight** (qlonglong): `18`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (qlonglong): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (qlonglong): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `false`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (qlonglong): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (qlonglong): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (qlonglong): `0`
**notesPanelOrder** (qlonglong): `0`
**notesPanelSort** (qlonglong): `0`
**notesPath** (QString): `/Users/amyfabijennalang/ownCloud/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/ignoreNonTodoCalendars** (bool): `true`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (qlonglong): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (qlonglong): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `c86b98c2-92f4-48aa-a6a4-679aed46fc3e`
**restoreCursorPosition** (bool): `false`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2020-08-31T09.40.46, Note 2020-08-30T06.48.51, Note 2020-08-28T17.35.38, Note 2020-08-28T17.15.20, Note 2020-08-27T09.08.52, Note 2020-08-25T11.37.59, Note 2020-08-22T16.44.27, Note 2020-08-20T18.02.27, Note 2020-08-20T11.13.48, Note 2020-08-20T10.09.59, Note 2020-08-20T08.04.35, Note 2020-08-19T19.40.59, Note 2020-08-19T19.37.26, Note 2020-08-19T19.36.22, Note 2020-08-19T19.29.33, Note 2020-08-19T13.02.35, Note 2020-08-03T13.44.06, Note 2020-08-03T12.57.03, Note 2020-08-02T04.56.51, Note 2020-07-30T15.13.33, Note 2020-07-30T10.11.13, Note 2020-07-27T10.01.38, Note 2020-07-24T10.05.44, Note 2020-07-23T14.06.32, Note 2020-07-23T11.40.38, Note 2020-07-19T21.06.45, Note 2020-07-19T13.53.37, Note 2020-07-19T13.53.32, Note 2020-07-19T10.34.10, Note 2020-07-18T21.08.16, Note 2020-07-18T16.13.42, Note 2020-07-14T19.08.45, Note 2020-07-14T17.38.04, Note 2020-07-14T17.18.14, Note 2020-07-14T16.17.30, Note 2020-07-09T10.47.27, Note 2020-07-08T21.15.17, Note 2020-07-07T21.08.12, Note 2020-07-07T21.08.08, Note 2020-07-05T23.22.03, Note 2020-06-10T19.45.19, Note 2020-06-08T10.25.48, Note 2020-06-07T17.03.17, Note 2020-06-04T22.23.00, Manu, Note 2020-06-04T12.28.31, Note 2020-06-02T14.34.59, Note 2020-05-29T09.52.44, Note 2020-05-28T17.56.16, Note 2020-05-26T18.03.37, Note 2020-05-24T14.34.54, Note 2020-05-22T16.13.30, Note 2020-05-22T14.36.06, Note 2020-05-20T19.59.49, Note 2020-05-19T22.15.30, Note 2020-05-15T13.47.10, Note 2020-05-12T12.32.06, Note 2020-05-11T16.48.15, Note 2020-05-11T13.16.49, Note 2020-05-03T13.54.49, Note 2020-04-25T18.35.57, Note 2020-04-25T13.43.24, Note 2020-04-25T11.41.55, Note 2020-04-25T09.02.30, Note 2020-04-20T06.45.27, Note 2020-04-19T12.12.30, Note 2020-04-18T18.24.58, Note 2020-04-16T15.32.56, Note 2020-04-10T13.36.28, Note 2020-04-10T13.07.50, Note 2020-04-10T12.43.46, Note 2020-04-09T21.20.28, Note 2020-04-09T21.18.35, Note 2020-04-09T20.11.00, Note 2020-04-09T15.43.10, Note 2020-04-06T11.47.14, Note 2020-04-04T19.29.17, Note 2020-04-02T18.21.02, Note 2020-04-01T17.26.28, Note 2020-03-29T18.29.40, Note 2020-03-28T18.03.24, Note 2020-03-27T14.28.27, Note 2020-03-27T13.11.24, Note 2020-03-24T18.51.04, Note 2020-03-24T09.35.52, Note 2020-03-21T16.09.10, Note 2020-03-16T11.10.21, Note 2020-03-16T11.10.20, Note 2020-03-14T09.55.31, Note 2020-03-13T15.18.12, Note 2020-03-11T12.59.01, Note 2020-03-10T12.45.40, Note 2020-03-08T12.19.29, Note 2020-03-08T12.19.28, Note 2020-03-08T12.19.27, Note 2020-03-08T12.19.26, Note 2020-03-08T12.19.25, Note 2020-03-08T12.19.24, Note 2020-03-08T12.19.23, Note 2020-03-08T12.19.22`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**skipVersion** (QString): `20.5.10`
**spellCheckLanguage** (QString): `en_GB`
**systemIconTheme** (bool): `false`
**tagWasAddedToNote** (bool): `true`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (qlonglong): `0`
**tagsPanelSort** (qlonglong): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (qlonglong): `6`
**useNoteFolderButtons** (bool): `false`
**useSoftWrapInNoteEditor** (bool): `true`
**useUNIXNewline** (bool): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (qlonglong): `22222`
**workspace-aa4da425-54cd-4949-8149-15c005190fe7/name** (QString): `Minimal`
**workspace-aa4da425-54cd-4949-8149-15c005190fe7/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-aa4da425-54cd-4949-8149-15c005190fe7/windowState** (QByteArray): `<binary data>`
**workspace-b51dba04-d3e5-4d63-a499-8bf9064074f4/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-b51dba04-d3e5-4d63-a499-8bf9064074f4/windowState** (QByteArray): `<binary data>`
**workspace-c86b98c2-92f4-48aa-a6a4-679aed46fc3e/name** (QString): `Dissertation`
**workspace-c86b98c2-92f4-48aa-a6a4-679aed46fc3e/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-c86b98c2-92f4-48aa-a6a4-679aed46fc3e/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `aa4da425-54cd-4949-8149-15c005190fe7, c86b98c2-92f4-48aa-a6a4-679aed46fc3e`

## System environment

**TMPDIR**: `/var/folders/m6/hp8h5xxn4z738r441_r9tbww0000gn/T/`
**__CF_USER_TEXT_ENCODING**: `0x1F5:0x0:0x5C`
**SHELL**: `/bin/bash`
**HOME**: `/Users/amyfabijennalang`
**Apple_PubSub_Socket_Render**: `/private/tmp/com.apple.launchd.iAJ4tayB3W/Render`
**SSH_AUTH_SOCK**: `/private/tmp/com.apple.launchd.SIJWgiIjQM/Listeners`
**PATH**: `/usr/bin:/bin:/usr/sbin:/sbin`
**LOGNAME**: `amyfabijennalang`
**XPC_SERVICE_NAME**: `com.PBE.QOwnNotes.23420`
**USER**: `amyfabijennalang`
**XPC_FLAGS**: `0x0`
**QT_LOGGING_RULES**: `qt.network.ssl.warning=false`

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
So what is it what you are asking for?

**Comment by PurplePlums** [comment]
- Buttons, somewhere easy to find.
- To me the two categories aren’t expressed clearly. Basically „next/ previous“ mean roughly the same thing, semantically.

One let’s you jump to the “previous/next” note you’ve worked on and the other, if I got it right, moves up or down in the list regardless of your history of working on different files.

I would wish for a semantic disambiguation: 

Like move up and down in the list of notes.

Instead of previous/ next, for the latter is an even perfect description of moving “back and forth” in your previously opened notes...

And I tried to memorize this for some while but it keeps on being confusing.

**Comment by pbek** [comment]
> Buttons, somewhere easy to find.

You can add those buttons in the *Toolbar settings*.

> Like move up and down in the list of notes, maybe?

So what are you suggesting?
Renaming `Previous note` to `Move up in note list` and `Next note` to `Move down in note list`? 

@Waqar144, do you feel the same?

**Comment by PurplePlums** [comment]
"So what are you suggesting?
Renaming Previous note to Move up in note list and Next note to Move down in note list?"

Yes, I am suggesting that.

**Comment by PurplePlums** [comment]
"So what are you suggesting?
Renaming Previous note to Move up in note list and Next note to Move down in note list?"

Yes, I am suggesting that.

**Comment by PurplePlums** [comment]
"So what are you suggesting?
Renaming Previous note to Move up in note list and Next note to Move down in note list?"

Yes, I am suggesting that.

**Comment by PurplePlums** [comment]
"So what are you suggesting?
Renaming Previous note to Move up in note list and Next note to Move down in note list?"

Yes, I am suggesting that.

**Comment by Waqar144** [comment]
> @Waqar144, do you feel the same?

I haven't really used this feature, but to me `previous / next` seems clear enough

**Comment by PurplePlums** [comment]
It is definitely "clear" but you could name "back in history / forward in history" the same. 
I just think that it could be clearer... I'm no native speaker of English thus I'd rather give that over to those who are.

**Comment by pbek** [comment]
I guess I'm in the mood for text changes today... 😁 

## 20.9.1
- the action `Previous note` was renamed to to `Move up in note list` and the 
  action `Next note` to `Move down in note list` to make the meaning of the
  actions more clear

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by PurplePlums** [comment]
Great, it really makes me happy 😌 😆
