### ISSUE TITLE
Right click menu items (context menu) on Note list items are not evenly spaced.

### ISSUE THREAD

**Issue by iclementine** [pbek/QOwnNotes#1866]
#### Expected behaviour
Right click menu items (context menu) on Note list items are evenly spaced.

#### Actual behaviour
They are not.

#### Steps to reproduce
Use qownnotes 20.9.3 on openSUSE 15.1, set display language to Chinese, simplified or traditional is okay. Then you will find that right click menu items (context menu) on Note list items are not evenly spaced.

<img width="960" alt="qownnotes" src="https://user-images.githubusercontent.com/16222986/92741957-b898bd00-f3b1-11ea-9f5d-93069e3fadbb.png">

I am not sure when this problem starts to occur. But it does not show up when the display language is English.

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
I cannot reproduce that under KDE Neon. Looking good for me.

![image](https://user-images.githubusercontent.com/1798101/92759317-e66d0a00-f38f-11ea-82ee-e66a18e7313d.png)

Might be a openSUSE thing... How're the flatpak, snap and app image version of QOwnNotes looking?

**Comment by iclementine** [comment]
Thank you for you replay. Sorry for not making a good annotation of the screenshot. By ""not being evenly spaced", I mean some menu items' position has a small offset upwards, thus, clipping the text a littel and leave larger margin at the bottom.

<img width="1376" alt="图片" src="https://user-images.githubusercontent.com/16222986/92842182-d1d35500-f415-11ea-8fc2-3fc6dada5edc.png">

In the screenshot you posted, I also see the same offset.

<img width="869" alt="图片" src="https://user-images.githubusercontent.com/16222986/92842551-46a68f00-f416-11ea-8c92-08a676e5bd10.png">

**Comment by pbek** [comment]
Strange. That seems to be an issue with the default Qt styling. Do you also have that issue in dark mode? (QON's dark mode)
There is a script in the script repository that lets you modify the UI styling. Maybe you can find a way to get around this.

**Comment by iclementine** [comment]
Yes, you are right. I cannot reproduce it in dark mode.
Also I tried lower versions, 20.4.18, It does not have this issue even with default Qt styling.

**Comment by pbek** [comment]
Maybe it came with a newer Qt version.

**Comment by iclementine** [comment]
I am using Qt 5.9.7, openSUSE 15.1. Maybe it is related to the Qt style and QON's language package's version. Thank you.

**Comment by pbek** [comment]
There is no "language package", it just uses the usual way of how Qt apps are translated. Like I said, you could try tinker with the UI with above mentioned script.

**Comment by iclementine** [comment]
Thank you. Now I've enabled the custom-stylesheet script. I'am trying to figure out which name controls the context menu on the noteTreeWidget.

**Comment by pbek** [comment]
Could be a general thing of QMenu: https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qmenu

And if it looks ok in dark mode you could take a look at the styles from there: https://github.com/pbek/QOwnNotes/blob/develop/src/libraries/qdarkstyle/style.qss#L246

**Comment by iclementine** [comment]
I have found another case with  "some menu items have some unexpected offsets".

<img width="960" alt="qon" src="https://user-images.githubusercontent.com/16222986/92993104-f3b9fe00-f521-11ea-9c36-d20d94bc77f2.png">

So I think it's probably an error in the translation(what I previously referred to as language package) of Chinese (simplified and traditonal). I think there is an unspected `\n` in these items that show some unexpected offsets. So I checked the translation of Chinese and I did find these errors. I compared  "languages/QOwnNotes_en.ts" and "language/QOwnNotes_zh_CN.ts" and "language/QOwnNotes_zh_TW.ts"

## New note in new tab
English
<img width="453" alt="image" src="https://user-images.githubusercontent.com/16222986/92993230-7e9af880-f522-11ea-92fa-92ed9cc0d9bb.png">

zh_CN
<img width="434" alt="image" src="https://user-images.githubusercontent.com/16222986/92993288-f9641380-f522-11ea-9ea5-2d5a91f190f2.png">

## Jump to the note's subfolder
en
<img width="515" alt="image" src="https://user-images.githubusercontent.com/16222986/92993394-c8d0a980-f523-11ea-877f-8c612726058b.png">

zh-CN
<img width="462" alt="image" src="https://user-images.githubusercontent.com/16222986/92993470-63c98380-f524-11ea-8cc9-e18b22856319.png">

## 
en
<img width="501" alt="image" src="https://user-images.githubusercontent.com/16222986/92993510-bc008580-f524-11ea-9173-19e122d1f36e.png">

zh-CN
<img width="474" alt="image" src="https://user-images.githubusercontent.com/16222986/92993499-a25f3e00-f524-11ea-835e-5382badb7cd4.png">

In these 3 examples, there is a `\n` before </translation> in Chinese translation. I think it is the cause of this. And also, there are more translations in Chinese with an extra `\n`, I think it is a problem. If it is comfired, I would like to make a pull request to fix this. Is it the ordinary way to contribute to the translations of QOwnnotes.

more examples of these unexpected space.
<img width="489" alt="image" src="https://user-images.githubusercontent.com/16222986/92993594-65477b80-f525-11ea-93a6-cdabaaf3685e.png">

**Comment by pbek** [comment]
> I have found another case with "some menu items have some unexpected offsets".

Then it really could be a QMenu issue (see above).

**Comment by iclementine** [comment]
> > I have found another case with "some menu items have some unexpected offsets".
> 
> Then it really could be a QMenu issue (see above).

Thank you, and I found something strange in the translation file. Does a `\n` in the menu item affects the menu?

**Comment by pbek** [comment]
That really could be the reason for it. You could fix those line-breaks for the two languages on https://crowdin.com/project/qownnotes and also open issues in comments for those strings. (Or you can tell me your username on https://crowdin.com/ and I make you proofreader so you can approve the strings yourself)

**Comment by iclementine** [comment]
Update:

I edited the Chinese translation file and rebuild qownnotes on obs. The problem is fixed. So I am sure that this is a problem with the translation.

**Comment by pbek** [comment]
Awesome! Thank you very much for confirming! Then please: https://github.com/pbek/QOwnNotes/issues/1866#issuecomment-691470572 😀

**Comment by iclementine** [comment]
> That really could be the reason for it. You could fix those line-breaks for the two languages on https://crowdin.com/project/qownnotes and also open issues in comments for those strings. (Or you can tell me your username on https://crowdin.com/ and I make you proofreader so you can approve the strings yourself)

Thank you, I did not have a account on crowdin.com, but I would sign in for an account. 
Also, I found the translation errors that I would like to fix.

**Comment by pbek** [comment]
Wonderful, you can use your GitHub account for auth.

**Comment by iclementine** [comment]
Thank you. Also want to know "double click to stick/unstick note form tab" means? I need to understand this to translate it.
I found double cliking on a tab would toggle a mini flag on the tab title. But I don't really what understand sticking/unsticking mean?

**Comment by pbek** [comment]
Making them sticky means that the tab will not be re-used by another note when you click on another note. Rather a new tab will be opened then.

**Comment by iclementine** [comment]
Thank you. I've signed up with my github account and edited some translations. Please make me a proof reader. I am an old user of QOwnNotes and would like to contribute to it.

**Comment by pbek** [comment]
Done

**Comment by PurplePlums** [comment]
Crowdin is generally not very strict or rather not strict enough regarding any involuntary changes in style. This issue is something that I kind of expected. Thanks for sharing.

**Comment by PurplePlums** [comment]
Crowdin is generally not very strict or rather not strict enough regarding any changes in style. This issue is something that I kind of expected. Thanks for sharing.

**Comment by PurplePlums** [comment]
Crowdin is generally not very strict or rather not strict enough regarding any changes in style. This issue is something that I kind of expected. Thanks for sharing.

**Comment by iclementine** [comment]
I have checked and corrected some translation errors and formatting errors in Chinese Simplified translations. When would these changed to applied to a newer version of QOwnNotes?

(I have not correct that for Chinese Traditional, because it takes some time to do so).

**Comment by PurplePlums** [comment]
As far as I understand they will be visible at the next update, coming up shorty.

**Comment by pbek** [comment]
I'll integrate the new translations in the next release. Thank you!

**Comment by pbek** [comment]
## 20.9.5
- a great amount of translations into Chinese Simplified were fixed so the menu items are
  correctly shown again (for [#1866](https://github.com/pbek/QOwnNotes/issues/1866), thank you iclementine)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by iclementine** [comment]
> There now is a new release, could you please test it and report if it works for you?

Yes, it works for me now. Thank you!

**Comment by pbek** [comment]
Great, thank you for testing and your work!
