### ISSUE TITLE
QOwnNotes.exe detected as Trojan:Win32/Wacatac.G!ml by Windows Defender

### ISSUE THREAD

**Issue by WiperWoper** [pbek/QOwnNotes#1867]
### Expected behaviour
QOwnNotes.exe should not be detected and removed by antivirus software.
#### Actual behaviour
With the latest update, QOwnNotes.exe is being detected as Trojan:Win32/Wacatac.G!ml by Windows Defender.
#### Steps to reproduce

Update Windows antivirus definitions and QOwnNotes. 
If enabled for real-time protection, Windows Defender should have automatically removed the .exe
If trying to open it with the portable .bat, an error will say the .exe was not found.

Alternatively, just download the latest QOwnNotes.zip (SHA-256 hash: aadce225f5e111d926ea90021909218f905d8d3bf4fad57c6bdedc792e9a611d) and run a scan with Windows Defender.
#### Output from the debug section in the settings dialog

N/A

#### Relevant log output in the Log panel

N/A

**Comment by pbek** [comment]
What is "the latest update" for you and where did you get it? 
Can you please post the output from the debug settings (see issue template).

The genuine Windows binaries from https://github.com/pbek/QOwnNotes/releases are built on GitHub infrastructure.

**Comment by WiperWoper** [comment]
The app updated itself, on restart the .exe was gone. I also manually downloaded version 20.9.4 from https://github.com/pbek/QOwnNotes/releases/download/v20.9.4/QOwnNotes.zip and scanned as I mentioned, same result. I'll try to get the debug output and update asap.

**Comment by nonplayer** [comment]
I am having the same issue, came here to report it

**Comment by nonplayer** [comment]
![image](https://user-images.githubusercontent.com/5161177/92778893-6eceb900-f356-11ea-8a27-4051b86b405a.png)

**Comment by pbek** [comment]
I found a thread about something similar: https://github.com/dotnet/runtime/issues/35167

**Comment by pbek** [comment]
I can't find any malware with https://www.virustotal.com/gui/file/05fd4fc365aef176604733cfc753fc10aa06f5bb3d680c19f8f380b2d4b6bb32/detection.

**Comment by nonplayer** [comment]
I rolled back to the previous build and all was good. Ran the updater, and bam, same virus warning.

THat said, I am testing on a second _more_ secure computer, and not getting a warning.

**Comment by pbek** [comment]
Really sounds like a false positive like mentioned in https://github.com/dotnet/runtime/issues/35167.

**Comment by pbek** [comment]
I did upgrade QON to 20.9.4 on a Windows 10 Pro machine and had no complains.

**Comment by WiperWoper** [comment]
I tried again just now scanning 20.9.4 and Windows Defender is not finding anything anymore, so I assume they fixed their definitions. 20.9.5 is also working fine. Closing the issue.

**Comment by pbek** [comment]
Ok, great. Thank you for testing and reporting!
