### ISSUE TITLE
[F] Reset zoom with Control-0

### ISSUE THREAD

**Issue by wolframroesler** [pbek/QOwnNotes#1869]
#### Expected behaviour

When the user presses Control-0 (Ctrl key plus digit zero), zoom should reset to the default. For example, after enlarging font sizes with Ctrl-plus or reducing font sizes with Ctrl-minus, Ctrl-0 should reset font sizes to the defaults.

#### Actual behaviour

Ctrl-0 does nothing.

#### Steps to reproduce

1. Press Ctrl-plus. Fonts get bigger.
2. Press Ctrl-zero. Nothing happens, fonts are still big.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information

(withheld for privacy reasons. I don't think you need it for this issue.)
</details>

**Comment by wolframroesler** [comment]
Ah, it says "Reset note text size" is bound to Ctrl-/. That doesn't work for me because slash is Shift-7 on my keyboard, and Ctrl-Shift-7 does nothing. But rebinding to Ctrl-0 also does't work, it displays "Ctrl+0" in the menu now but pressing Ctrl-0 does nothing. (Clicking "Reset note text size" in the menu does work, however.)

**Comment by pbek** [comment]
I use the numerical keypad. But you can set a new shortcut in the settings.

**Comment by wolframroesler** [comment]
Probably, but I'd still like to use regular Ctrl-0, just like in any other program.

**Comment by pbek** [comment]
Ctrl+0 is used to jump to bookmark slot 0. You can try override it in the settings, but I guess that only works if the text edit doesn't have the focus.

**Comment by pbek** [comment]
## 20.9.7
- the note text bookmark slot 0 was sacrificed to allow <kbd>Ctrl</kbd> + <kbd>0</kbd>
  to reset the note text font size

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
That was some kind of safeguard for past versions of Qt. I just tested it without that code and I doesn't seem to have any troubles, so I will remove the safeguard in the next release. Thank you for bringing that up.

**Comment by pbek** [comment]
## 20.9.8
- resetting the note text font size will now not move the text cursor

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by wolframroesler** [comment]
Works as expected now. Thanks for the quick solution! You support is really outstanding.

**Comment by pbek** [comment]
Great, thank you for testing! 😁
