### ISSUE TITLE
File finder / jumper

### ISSUE THREAD

**Issue by prat0088** [pbek/QOwnNotes#187]
File jump that lets you immediately navigate to a file by searching on its name.

Behavior:

0. In QOwnNotes, use a hotkey to bring up an auto-complete drop-down.
0. Type in a partial name of a file. 
0. Press enter.
0. File opens in QOwnNotes

Examples:

* [Sublime Text](http://digisocialnet.com/content/01-blog/04-my-favorite-sublime-text-packages/filepalette.jpg)
* [VIM CTRL+P](https://github.com/kien/ctrlp.vim)
* [Visual Studio Code](http://dailydotnettips.com/wp-content/uploads/2015/05/image.png)

**Comment by pbek** [comment]
Thank you for your suggestion. Do you mean the already existing feature of `Ctrl + Shift + F`to search for a note in the current note folder, then pressing `Down` to select the note you want to open?
Or do you mean a feature to open any file, like your text editor examples does (note: QOwnNotes is no text editor and will most certainly never be)?

**Comment by pbek** [comment]
I'm temporary closing this issue now for lack of additional information, I'm not sure what you are wanting exactly. :)
