### ISSUE TITLE
[F] Zoom with Ctrl+mouse wheel

### ISSUE THREAD

**Issue by wolframroesler** [pbek/QOwnNotes#1870]
#### Expected behaviour

Rolling the mouse wheel while the Control key is pressed should zoom in and out, just like Ctrl-plus and Ctrl-minus do.

#### Actual behaviour

Rolling the mouse wheel while Ctrl is pressed scrolls the note (i. e. Ctrl is ignored).

#### Steps to reproduce

Roll the mouse wheel while holding Ctrl pressed.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Di. Sept. 15 20:07:24 2020`
**Version**: `20.8.4`
**Build date**: `Aug 13 2020`
**Build number**: `748`
**Platform**: `linux`
**Operating System**: `KDE Flatpak runtime`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `TuxFamily`
**Qt Version (build)**: `5.14.2`
**Qt Version (runtime)**: `5.14.2`
**Portable mode**: `no`
**Settings path / key**: `/home/wolfram/.var/app/org.qownnotes.QOwnNotes/config/PBE/QOwnNotes.conf`
**Application database path**: `/home/wolfram/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_GB`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1200`
**Screen resolution(s)**: `1920x1200, 1600x900`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `10`
**Calendar items**: `0`
**Enabled scripts**: `0`

More information withheld for privacy reasons.
</details>

**Comment by pbek** [comment]
Thank you for your suggestion, that currently only works in the preview.

**Comment by pbek** [comment]
## 20.9.6
- you now can increase and decrease the editor font size also with the mouse wheel
  while holding <kbd>Ctrl</kdb> pressed

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by wolframroesler** [comment]
Tried 20.9.6. Ctrl+wheel scrolls until the beginning/end of the document is reached; only then (when there's nowhere to scroll to) does it change the font size.

**Comment by pbek** [comment]
I can't reproduce that. It doesn't scroll for me if I hold Ctrl.

**Comment by pbek** [comment]
Sorry, I can reproduce it. I first tested in read-only mode where mouse zooming works out of the box.

**Comment by pbek** [comment]
The events didn't came through, I now re-implemented the feature.

## 20.9.7
- increasing and decreasing the editor font size with the mouse wheel now also works if
  not on beginning or end of note

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by wolframroesler** [comment]
Works in 2.9.7, thanks for the quick fix!

**Comment by pbek** [comment]
Great, thank you for testing!
