### ISSUE TITLE
Languages coordination

### ISSUE THREAD

**Issue by PurplePlums** [pbek/QOwnNotes#1871]
#### Expected behaviour

I'd expect that the selectable languages work just as well as the original English version, or a warning that the language might not work well enough to work with.

#### Actual behaviour

Most of the selectable languages are neither edited, nor approved.

#### Steps to reproduce

Select such a language and see if it works, if you speak that language or ask someone to trust with the issue.

#### Output from the debug section in the settings dialog

I'm not sure what I am supposed to post here.

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by PurplePlums** [comment]
Therefor I would add a label like "beta" or a similar warning before a language is selected that has not been fully approved.

**Comment by pbek** [comment]
Thank you for your suggestion. I haven't seen such a warning in any software so far. What is the user warned about? Possibly bad translations?

I wonder if I wouldn't been able to speak English I wouldn't prefer some kind of translation to not understanding a word at all...
By default QOwnNotes uses the system language, so most users wouldn't even see the language settings anyway.
And such a flag would be hard to maintain because it would have to be checked manually for every language on every release and then set for every language somewhere in the interface...

**Comment by PurplePlums** [comment]
„By default QOwnNotes uses the system language, so most users wouldn't even see the language settings anyway.“ -  Well but then if the system language is, say, Danish and the app thus  for them is presented in Danish, I would want a warning about that what they see is beta translated and to might check out the English version. I think that many people speak English and would prefer a properly speaking app. Moreover the machine translation might sufficed back when QON started but nowadays it’s more complicated and many things simply won’t make a sense.

And, yes, I totally agree with your point that any translation is better than an app that speaks a language I do not. But to assume that that would be acceptable in its full range of operating could also be a challenge and maybe not so kind, if that’s left unwritten. Just think of it, many people are dreading to have to deal with machine translation, it’s regarded as “impolite” so to speak and I know quite folks that definitely would want a hint, a mention or a warning that they’re presented machine-talk to deal with ......

It’s a question of how polite QON wants to be to these users.

And finally about how to maintain such a warning, I don’t know quite if such a script would be possible (forgive my ignorance) that removes the warning whenever a language is translated 100% AND edited 100%, but if not, we might can arrange that it’s done like once a while. I don’t know if and how that’d be possible but then I’d see how, and like to help decide if it’s worth the effort.

Also, mentioning those users who speak English but not so well and definitely would choose their own language and benefit from an update;

Otherwise maybe the Changelog could contain these infos.

Just some input, I might think another time of anything that could resolve this issue, thanks

**Comment by PurplePlums** [comment]
Well, I think that ppl should make an informed consent on whether they want do deal with a language that they might not be proficient in, like English or whether they choose a machine translated language in their app.

To measure the quality of any of the non-approved languages is difficult as well as how that specifically works for the user. 

Hence I would be a supporter of offering any or all proofread language(s) **as well as** their systems default language when installing.

Only this way could QON ensure to meet every users needs in regard of language. (Because there will be s scope of infinite combinations of how well a user speaks some language as well as what they want to make of that. 

How ever this had been handled so far, the more complex QON gets, the more important it gets to not to leave anyone behind language-wise.

And I would like to add here that most people know little about languages dnd translations, they just want the thing to work properly but that’s something that we share with building an app so I guess I can’t write that script but I would if I could.

**Comment by PurplePlums** [comment]
My suggestion would be this warning during the installation:

**"The _Danish_ version of QOwnNotes has not been approved yet. There might be incorrect translations or even faulty translation from the translators side at the moment.

Would you like to install the _English/ German (Deutsch), Persian (Farsi) ..._

edited and approved version until we’ve finished approving the Danish version, instead?**

I would strongly suggest that this text appears upon the installation dialoge somewhere, because when people are not warned about the potentially bad quality of the MT I have done on different languages, that might be irritating - they will not know the reason for any confusing incident and I think that it might be detrimental of how they possibly assess the quality of QOwnNotes all in one.

I hope this is doable.
