### ISSUE TITLE
Tab key generates tab character in Vim mode even if the "Use tab character" option is disabled

### ISSUE THREAD

**Issue by johnliu55tw** [pbek/QOwnNotes#1875]
#### Expected behaviour
In Vim mode, with the option "Use tab character instead of spaces" disabled, when I press tab key, it should generate spaces instead of tab character.

#### Actual behaviour
Pressing tab key always generates tab character in Vim mode, even when "Use tab character instead of spaces" option is disabled.

#### Steps to reproduce
1. Enable Vim mode
2. Make sure "Use tab character instead of spaces" is disabled
3. Go to editor
4. Press tab key, and it generates tab character

Thanks for the great app!

**Comment by pbek** [comment]
> Thanks for the great app!

Thank you for your kind words.

> In Vim mode, with the option "Use tab character instead of spaces" disabled, when I press tab key, it should generate spaces instead of tab character.

@Waqar144, are you using the vim mode?

**Comment by Waqar144** [comment]
> > Thanks for the great app!
> 
> Thank you for your kind words.
> 
> > In Vim mode, with the option "Use tab character instead of spaces" disabled, when I press tab key, it should generate spaces instead of tab character.
> 
> @Waqar144, are you using the vim mode?

Yes, I use vim mode. I think we need to set "expandTab" setting somehow.

**Comment by pbek** [comment]
## 20.9.9
- tab stop width and tab versus space settings are now also respected in fakevim mode
  (for [#1875](https://github.com/pbek/QOwnNotes/issues/1875), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by johnliu55tw** [comment]
Thanks for the quick release! However the issue still exists.

BTW I'm using AUR built version, not sure if that's related:
![image](https://user-images.githubusercontent.com/5047724/93956397-af7df780-fd84-11ea-8221-4214fce053b0.png)

Please let me know if I need to provide more information.

**Comment by Waqar144** [comment]
> Thanks for the quick release! However the issue still exists.

Yes, that's on me. It will work if you enable "Use Tabs" :D.
Will fix in the next release.

**Comment by pbek** [comment]
## 20.9.10
- fixed the incorrect setExpandTab setting for fakeVim (for [#1875](https://github.com/pbek/QOwnNotes/issues/1875), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by johnliu55tw** [comment]
Now it's working, thank you!

**Comment by pbek** [comment]
Great, thank you for testing!
