### ISSUE TITLE
More entries in note right-click context menu

### ISSUE THREAD

**Issue by prat0088** [pbek/QOwnNotes#188]
There are some entries that seem like they would be more natural in the right-click context menu of the note list:

* Show note in file manager
* Open note in external editor

**Comment by pbek** [comment]
Thank you for your suggestion, I guess we could do that.

**Comment by pbek** [comment]
Will be done in v16.05.24.

**Comment by pbek** [comment]
Version 16.05.24 is now released, could you please be so kind and test the new feature?
