### ISSUE TITLE
Note disappeared 

### ISSUE THREAD

**Issue by Linuxnoob01** [pbek/QOwnNotes#1884]
\\\ it reappeared don't know why

20.9.8 snapcraft 763

chrome os 84 / debian buster

I finished my note and then decided the note needed it owns subfolder and made a new subfolder in the origin folder of the note.

when i moved the notes with "move notes to..." it it dissapeared from my qownotes/computer

####Moving note to new subfolder (created after finishing the note (didnt save the note before moving).

**Comment by pbek** [comment]
Ok, then I will close this issue until there is more information. 😁
