### ISSUE TITLE
Is it necessary for socket server to listen on 0.0.0.0?

### ISSUE THREAD

**Issue by dmtrbm** [pbek/QOwnNotes#1885]
`tcp   LISTEN 0      50                           *:22222            *:*    users:(("QOwnNotes",pid=706836,fd=22))`
Would it be possible to bind it to loopback interface instead?
Thanks.

**Comment by pbek** [comment]
> Is it necessary for socket server to listen on 0.0.0.0

No, that's not necessary. I'll try to only use `QHostAddress::LocalHost` instead, hoping that this also works under Windows.

**Comment by pbek** [comment]
## 20.9.11
- the web socket server for the QOwnNotes browser extension is now only listening
  on localhost any more

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by dmtrbm** [comment]
It works. Thank you.

**Comment by pbek** [comment]
Great, thank you for testing!
