### ISSUE TITLE
Latest Update blocked as serious thread by Windows Defender

### ISSUE THREAD

**Issue by Protarios** [pbek/QOwnNotes#1887]
Update build v20.9.11 was blocked by Windows Defender as serious threat.

**Comment by pbek** [comment]
I guess we are looking at #1867 again.

**Comment by willtm** [comment]
I am also experiencing an issue with the installation of v20.9.11 on Windows 10.  Even when I try to "unblock" the .exe, I am unable to do so.

I have been updating QOwnNotes from the application interface without incident for months.  This is the first time I've had a problem with an update.

**Comment by pbek** [comment]
Does https://www.virustotal.com find anything?

There's not much that can be done about "bad heuristics" in Windows Defender, last time MS patched that problem away within days...

**Comment by willtm** [comment]
@pbek I uploaded the `QOwnNotes.exe` to [https://www.virustotal.com](https://www.virustotal.com) and got a response of `no virus engines found`.

**Comment by pbek** [comment]
Thank you. So we need to wait. 😁

**Comment by willtm** [comment]
@pbek I understand.  You update QOwnNotes frequently so rolling back to a prior version--I'm using `20.9.8`--is not an inconvenience.  All of the features I need are there! : )

**Comment by pbek** [comment]
I had no troubles with the 20.9.11 update. Seems like MS fixed it already.
