### ISSUE TITLE
[F] Enable drag and drop within Note Edit Panel

### ISSUE THREAD

**Issue by alexanderino** [pbek/QOwnNotes#1888]
#### Expected behaviour

With virtually all text editors and word processors, selecting text and dragging it to another location in the document moves it there.

#### Actual behaviour

With QOwnNotes [as of `20.9.11`], it is not possible to move selected text by dragging it to another location within the Note Edit Panel. (It is possible to drop it into another program like Notepad or LibreOffice Writer.)

The workaround is to cut and paste, but this clears the clipboard memory, which may not be always desirable.

#### Steps to reproduce

- select text with mouse (or equivalent device)
- attempt to drag and drop it to another part of the note within the Node Edit Panel — this fails
    - it is worth noting that my mouse's cursor turns into a circle with a slash, indicating that it won't work

This behaviour is consistent on Windows 10 and 8.1 (both Pro, 64-bit).

**Comment by pbek** [comment]
Thank you for your suggestion, I'll look into it on how much effort that would cost. 😉  (by the way, I use clipboard managers everywhere 😁 )

**Comment by alexanderino** [comment]
Thank you, Patrizio :slightly_smiling_face: I appreciate you investigating this. I'll also take the opportunity to thank you for creating this wonderful program.

Warm regards,

Jason

**Comment by pbek** [comment]
Thank you for your kind words! 😃

**Comment by pbek** [comment]
## 20.10.7
- it is now also possible to move text in the note text edit via drag and drop
  (for [#1888](https://github.com/pbek/QOwnNotes/issues/1888), thank you @fnkabit)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by alexanderino** [comment]
> There now is a new release, could you please test it and report if it works for you?

Hi, Patrizio. I've been dragging and dropping text in my existing MD files (including an encrypted note), and there has not been one problem or issue — it works like it should. This improves ease of use *tremendously* for me.

This issue can be considered closed from my end.

Thank you so much!

**Comment by pbek** [comment]
Great, thank you for testing!
