### ISSUE TITLE
QOwnNotes gets detected as Trojan:Win32/Woreflint.A!cl

### ISSUE THREAD

**Issue by bessw** [pbek/QOwnNotes#1889]
Windows Defender detected QOwnNotes version 20.9.11 immediately after the update as `Trojan:Win32/Woreflint.A!cl` and quarantined it.

**Comment by bessw** [comment]
Virustotal says its clean, so I think it's a false positive due to the way QOwnNotes updates itself, but still it's weird that Windows Defender didn't detect anything during the other updates.

**Comment by pbek** [comment]
Yes, see #1887
