### ISSUE TITLE
Problem installation on Linux Mint 17.3

### ISSUE THREAD

**Issue by bolbo** [pbek/QOwnNotes#189]
Hi,

I tried to install qownnotes on Linux Mint 17.3 
I followed the installation process from http://www.qownnotes.org/installation for "Older Ubuntu Linux distributions and derivatives"
Installation was ok, but when trying to launch the application I have nothing. 
If I launch the command in terminal: 
`laurent@laurent ~ $ /opt/QOwnNotes/QOwnNotes
/opt/QOwnNotes/QOwnNotes: symbol lookup error: /opt/QOwnNotes/QOwnNotes: undefined symbol: _ZN8QSysInfo17prettyProductNameEv
`

Do you have any idea to make it work ? 
Thanis

**Comment by pbek** [comment]
It seems that the default Linux Mint Qt is used instead of the the Qt 5.6. So you did install the beineri PPA and put `/opt/qt56/bin/qt56-env.sh` in your `profile`? Did you try rebooting, in case logging in and out didn't work?

**Comment by pbek** [comment]
I just tried the same on a Ubuntu 14.04 box and it worked with Qt 5.6 (I rebootet, to make sure, but logging in and out should work too).

**Comment by bolbo** [comment]
Hi @pbek 
I followed "Older Ubuntu Linux distributions and derivatives" process 
I added the line `. "/opt/qt56/bin/qt56-env.sh"` but didnt seem to work. 
I copyed this line in ~/.bashrc and rebooted. 

When I click on the shortcut to launch the program, nothing happens. 
But if in terminal I launch : `/opt/QOwnNotes/QOwnNotes` the program starts ! 

Now I can launch QOwnNotes whith terminal /opt/QOwnNotes/QOwnNotes command, not with launcher.

**Comment by pbek** [comment]
That's strange, it works for me from the launcher...
Does your launcher open `/usr/share/applications/QOwnNotes.desktop` and what is the content of that file?
I guess the problem is that you added `. "/opt/qt56/bin/qt56-env.sh"` to your bashrc and not profile. The launcher will maybe not using bash to open the app.

**Comment by bolbo** [comment]
Hello @pbek 
No the launcher runs: "/opt/QOwnNotes/QOwnNotes" 

laurent@laurent ~ $ cat /usr/share/applications/QOwnNotes.desktop
[Desktop Entry]
Name=QOwnNotes
Version=1.0
Exec=/opt/QOwnNotes/QOwnNotes
Comment=
Icon=/opt/QOwnNotes/icon.png
Type=Application
Terminal=false
StartupNotify=true
Encoding=UTF-8
Categories=TextEditor;


At my first attempt I added `. "/opt/qt56/bin/qt56-env.sh"` in .profile but it wasnt executed and `/opt/QOwnNotes/QOwnNotes` didnt event work when run in a terminal. 
Thats why i added this line in .bashrc file. Then launcher still not work, but i can use the app if I run `/opt/QOwnNotes/QOwnNotes` in a terminal (but I have to let this terminal window open if I dont want the app to stop)

**Comment by pbek** [comment]
Could it be that Linux Mint doesn't load ` ~/.profile`, that would be very unusual. You can run QOwnNotes in the background with `QOwnNotes &`.
Maybe you'll find an other way to start `/opt/qt56/bin/qt56-env.sh`  automatically...

**Comment by pbek** [comment]
Maybe this is an other way: <https://forums.linuxmint.com/viewtopic.php?t=212832>

**Comment by pbek** [comment]
Or you could try and add a new line `Terminal=true` to the desktop file, maybe the environment from your .bashrc will be loaded.

**Comment by pbek** [comment]
@bolbo, can you please try `sudo ln -s /opt/qt56 /opt/qt54`? That did the trick for me.

**Comment by pbek** [comment]
QOwnNotes looks great on Linux Mint!

![virtualbox_linux mint_29_06_2016_09_12_06](https://cloud.githubusercontent.com/assets/1798101/16443532/ad91e90a-3dd9-11e6-9e07-e2046018ee64.png)

**Comment by pbek** [comment]
Please also keep in mind that with Linux Mint 18 you can use the Ubuntu 16.04 PPAs of QOwnNotes.

**Comment by cyberfreak5725** [comment]
Can i install QOwnNotes in UBUNTU 14.04 ??

**Comment by pbek** [comment]
@cyberfreak5725 yes, see: http://www.qownnotes.org/installation#Linux

**Comment by cyberfreak5725** [comment]
thanks a lot
