### ISSUE TITLE
Search note title

### ISSUE THREAD

**Issue by koro-xx** [pbek/QOwnNotes#1890]
I am not sure if this is a feature request or if this feature exists and I can't find it, but I am trying to get the following behavior for the "note search" panel: I would like the search results to prioritize note titles (which I have configured to be different from the note header). So for instance I have a note named "note title" and another one named "123" which contains the text "note title" in its body. When I search "note title", the former should be the first result (currently, the opposite happens).
This is for example how NValt behaves on Mac OS.

Any chance of getting this? I suppose if it can't be currently done, maybe at some point it could be implemented with an option such as "prioritize titles in search results" in the settings.

**Comment by pbek** [comment]
No sorry, that's currently not possible. The sort order of the note list isn't affected at all by searching or filtering.

**Comment by pbek** [comment]
## 20.10.1
- you can now also search only in the note name
    - `n:book` or `name:book` will search for notes with `book` just in the note
      name or file name
    - for more information please take a look at the new
      [searching documentation](https://docs.qownnotes.org/en/latest/getting-started/searching/)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by koro-xx** [comment]
Excellent! This seems promising. I will use it for a while and report back.

**Comment by pbek** [comment]
Great! 😁

**Comment by 5472qaywsx** [comment]
Is the behaviour n:"note title" (with double quotes) also possible?
I've imported from Evernote, and some notes are duplicated with a " 2" (space+number two) suffix, and would like to filter this out with a name:" 2" search, but can't manage it to work. Is it a supported scenario?

**Comment by pbek** [comment]
No, that doesn't work yet. Would be nice tho... Will not be easy, but I'll take a look at it.

**Comment by pbek** [comment]
@5472qaywsx, but could you please open another feature request.

**Comment by pbek** [comment]
## 26.7.1

- The note text search now supports searching for note titles with spaces by using
  quoted name filters like `n:"note title"` (for [#1890](https://github.com/pbek/QOwnNotes/issues/1890))
