### ISSUE TITLE
[I] Cursor jumps to top line while typing

### ISSUE THREAD

**Issue by bipco** [pbek/QOwnNotes#1891]
#### Expected behaviour

Cursor stays on correct line

#### Actual behaviour

Cursor jumps to first line and typing continues there (if you don't notice)

#### Steps to reproduce

Type in note, occurs apparently randomly

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[08:06:26] [status] Stored 1 note(s) to disk
[08:06:36] [status] Stored 1 note(s) to disk
[08:06:46] [status] Stored 1 note(s) to disk
[08:06:56] [status] Stored 1 note(s) to disk
[08:07:06] [status] Stored 1 note(s) to disk
[08:07:16] [status] Stored 1 note(s) to disk
[08:07:26] [status] Stored 1 note(s) to disk
[08:07:36] [status] Stored 1 note(s) to disk
[08:07:46] [status] Stored 1 note(s) to disk
[08:07:56] [status] Stored 1 note(s) to disk
[08:08:06] [status] Stored 1 note(s) to disk
[08:08:16] [status] Stored 1 note(s) to disk
[08:08:26] [status] Stored 1 note(s) to disk
[08:08:27] [status] Current note was modified externally
[08:08:27] [status] Loading external changes from: a - Reminder.md
[08:08:36] [status] Stored 1 note(s) to disk
[08:08:37] [status] Note was modified externally: /Users/bipco/ecloud/Notes/a - Reminder.md
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mon Sep 28 08:09:01 2020`
**Version**: `20.9.11`
**Build date**: `Sep 25 2020`
**Build number**: `766`
**Platform**: `macosx`
**Operating System**: `macOS 10.15`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.1`
**Qt Version (runtime)**: `5.15.1`
**Portable mode**: `no`
**Settings path / key**: `/Users/bipco/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/bipco/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_GB`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1440x900`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `85`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://my.owndrive.com`
**appIsValid**: `no`
**notesPathExists**: `unknown`
**connectionErrorMessage**: `Unknown error`

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/Users/bipco/Library/Application Support/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `2`

### Note folder `default`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/Users/bipco/ownCloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/Users/bipco/ownCloud/Notes/notes.sqlite`

### Note folder `default`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/Users/bipco/ecloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/Users/bipco/ecloud/Notes/notes.sqlite`

### Cloud connection `eCloud`

**id**: `2`
**isCurrent**: `no`
**serverUrl**: `https://ecloud.global`
**username**: `bipco`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://my.owndrive.com`
**username**: `bipco`

## Settings

** USB DISK 2/0** (QString): `1`
**AKLastCheckInAttemptDate** (QDateTime): `2019-10-07T20:29:33.047`
**AKLastCheckInSuccessDate** (QDateTime): `2019-10-07T20:29:34.270`
**AKLastEmailListRequestDateKey** (QDateTime): `2020-09-28T08:01:12.823`
**AKLastIDMSEnvironment** (qlonglong): `0`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Amazon Kindle** (QString): `1`
**Android Android** (QString): `1`
**Canon BJC-6500** (QString): `1`
**Canon Inc/ Canon Digital Camera** (QString): `1`
**ContextMenuGesture** (qlonglong): `1`
**Country** (QString): `GB`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (qlonglong): `4`
**Editor/removeTrainingSpaces** (bool): `false`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**Fairphone 2** (QString): `1`
**Fairphone FP2** (QString): `1`
**Generic Mass storage** (QString): `1`
**Generic USB3/0-CRW** (QString): `1`
**Google Android** (QString): `1`
**Innostor PenDrive** (QString): `1`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**Kingston DataTraveler 3/0** (QString): `1`
**Kingston HyperX Savage** (QString): `1`
**LastUpdateCheck** (QDateTime): `2020-09-28T08:01:25.804`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (qlonglong): `32`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Monaco,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `.SF NS Text,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Monaco,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `.SF NS Text,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**MessageBoxOverride/remove-note** (qlonglong): `16384`
**MessageBoxOverride/remove-notes** (qlonglong): `16384`
**MessageBoxOverride/update-and-restart** (qlonglong): `16384`
**MultipleSessionEnabled** (bool): `true`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): `Shop`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteFolder-1/allowDifferentNoteFileName** (bool): `false`
**NoteFolder-2/NoteTabNameList** (QStringList): `a - Reminder`
**NoteFolder-2/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-2/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteHistory-1** (QVariantList): `<variant list with 105 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 12 item(s)>`
**NoteHistoryCurrentIndex-1** (qlonglong): `104`
**NoteHistoryCurrentIndex-2** (qlonglong): `11`
**PIXART USB OPTICAL MOUSE** (QString): `1`
**PKSecureElementAvailableFlags** (qlonglong): `1`
**PKSecureElementAvailableFlagsByHost** (qlonglong): `1`
**Pioneer Corporation Pioneer Blu-ray Drive** (QString): `1`
**PiwikClientId** (QString): `<hidden>`
**Prolific Technology Inc/ ATAPI-6 Bridge Controller** (QString): `1`
**SanDisk Cruzer Fit** (QString): `1`
**SanDisk Ultra Fit** (QString): `1`
**SanDisk Ultra USB 3/0** (QString): `1`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**Seagate FreeAgent GoFlex** (QString): `1`
**Seagate USB 2/0 Cable** (QString): `1`
**SearchEngineId** (qlonglong): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**SyncServicesServerWasActive** (bool): `true`
**TDK LoR TF10** (QString): `1`
**USBest Technology Intenso Business Line** (QString): `1`
**USBest Technology USB Mass Storage Device** (QString): `1`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**Western Digital My Passport 0748** (QString): `1`
**Western Digital My Passport 0820** (QString): `1`
**Western Digital My Passport 25E2** (QString): `1`
**Western Digital My Passport Wireless** (QString): `1`
**acceptAllExternalModifications** (bool): `true`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `false`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (bool): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**com/barebones/bbedit~01A4851B4F3FDBE49D07229D42CDED9050A90521** (QByteArray): `<binary data>`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (qlonglong): `2`
**currentWorkspace** (QString): `initial`
**cursorWidth** (qlonglong): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (bool): `false`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (bool): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (qlonglong): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (qlonglong): `1024`
**imageScaleDownMaximumWidth** (qlonglong): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (qlonglong): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (qlonglong): `18`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (qlonglong): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (qlonglong): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (qlonglong): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (qlonglong): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (qlonglong): `0`
**notesPanelOrder** (qlonglong): `0`
**notesPanelSort** (qlonglong): `1`
**notesPath** (QString): `/Users/bipco/ecloud/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (qlonglong): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (qlonglong): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `unknown`
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (bool): `false`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2020-05-17T15.46.07, Note 2020-05-03T11.59.39, Note 2020-03-28T16.47.09, Note 2020-03-17T09.33.10, Note 2020-03-14T13.12.37, Note 2020-03-06T10.03.22, Note 2020-02-21T10.12.30, Note 2020-02-21T10.05.25, Note 2019-12-09T11.04.12, Note 2019-08-15T21.19.59, Note 2019-08-06T13.09.54, Note 2019-05-23T14.17.15, Note 2019-05-21T15.18.51, Note 2019-05-19T13.33.43, Note 2019-05-19T13.32.51, Note 2019-05-19T13.31.49, Note 2019-05-19T13.17.10, Note 2019-03-02T17.30.01`
**savedSearches/noteFolder-2** (QStringList): `Note 2020-09-21T17.28.56, Note 2020-09-20T10.39.54`
**showMatches** (bool): `true`
**showMenuBar** (bool): `false`
**showStatusBar** (bool): `true`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (qlonglong): `0`
**tagsPanelSort** (qlonglong): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (qlonglong): `6`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (qlonglong): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**PWD**: `/var/folders/69/3wwxkzzj06bf83tvt2mmk2hm0000gp/T/tmp.UeToTHTw`
**USER**: `bipco`
**LANG**: `en_GB.UTF-8`
**LOGNAME**: `bipco`
**TERM**: `xterm-256color`
**PATH**: `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin`
**SHLVL**: `6`
**TERM_PROGRAM_VERSION**: `433`
**SSH_AUTH_SOCK**: `/private/tmp/com.apple.launchd.RWUxAbQH3l/Listeners`
**TERM_SESSION_ID**: `E13103D5-4E1E-4983-A504-7C9EB1C6E820`
**HOME**: `/Users/bipco`
**_**: `/usr/bin/open`
**QT_LOGGING_RULES**: `qt.network.ssl.warning=false`
**SHELL**: `/bin/bash`
**OLDPWD**: `/Users/bipco`
**__CF_USER_TEXT_ENCODING**: `0x1F6:0x0:0x2`
**TMPDIR**: `/var/folders/69/3wwxkzzj06bf83tvt2mmk2hm0000gp/T/`
**TERM_PROGRAM**: `Apple_Terminal`
**XPC_SERVICE_NAME**: `com.PBE.QOwnNotes.27564`
**XPC_FLAGS**: `0x0`
</details>

Please paste the text from the issue assistant here. It should be already in your clipboard.

**Comment by pbek** [comment]
Please see #1672 or others.
