### ISSUE TITLE
View In "Visual" Non-Markup Mode

### ISSUE THREAD

**Issue by compumatter** [pbek/QOwnNotes#1893]
I've just installed and updated the latest version of your software in Linux.

My question is this:  Is there a way to view the text / images we are entering in your editor that is typical of front end GUI and not in the Markup mode.  

I'd like to provide this to our customers as a Linux drop in for Todo lists etc but they are not using nextcloud/owncloud.  It would make an awesome list manager for Todo's or for Life.

Is that possible ?

Thanks

**Comment by pbek** [comment]
I think I don't understand the question. Is the question if you can show images in the edit panel (and not only in the preview panel)? Then the answer is no, you can't.

**Comment by compumatter** [comment]
Patrizio,

I am a novice to your software so forgive me

I was hoping the software had some wysiwig panel as an alternative to the code panel

Pictures would not be required but font sizes would

Sincerely,

Jay
	
Jay Lepore
CompuMatter
Office: 360 299 2428
Cell: 360 202 0434
Email: jay@compumatter.com
If you are satisfied with your service, please consider providing us a social media review at https://compumatter.com/reviews
...If you are not, please let me know so I can make it better

**Comment by pbek** [comment]
I'm sorry. QOwnNotes is all about plain text files and not a wysiwyg editor. 😁
