### ISSUE TITLE
AUR PKGBUILD - aspell as hard dependencies

### ISSUE THREAD

**Issue by scachemaille** [pbek/QOwnNotes#1895]
In the PKGBUILD for AUR apsell package is in the dependencies, this cause a small issue if we build qownotes on aarch64 architecture as aspell is not available in the arch repository (arch choice or aspell issue in this architecture I don't know).

There could be several workaround but I don't know the internal of qownote, like as if qownotes was built with aspell does aspell is required at runtime?

- if **aspell is  not required at runtime** if it was built with aspell

then it could be added in the `optdepends` and create a new `makedepends_x86_64` and `makedepends_i686` with aspell.

- if **aspell is required at runtime** if it was built with aspell.

just add a `depends_x86_64` and `depends__i686` with aspell

- or just put aspell in the `optdepends` with a remark that it needed at build time for aspell spell checking.

**Comment by pbek** [comment]
@Waqar144, how bad is it if aspell is not present?

**Comment by scachemaille** [comment]
it build fine.. just search a way to be able to build it on aarch64 without the need to edit the PKGBUILD.

**Comment by pbek** [comment]
Yeah, but will the spell-checker as fine...

**Comment by scachemaille** [comment]
> Yeah, but will the spell-checker as fine...
I'm not sure to understand you.

spell checking is greyed if qownotes is built without aspell.
it seens hunspell is not used on linnux built.

right now as aspell is in dependencies it failt on aarch64 as makepkg can't find aspell.

**Comment by scachemaille** [comment]
EDIT:
hunspell is used on my system.. just did not add any dictionaries installed.. 
I will try to see on my x86_64 system to remove aspell and will come back with proper solution

**Comment by Waqar144** [comment]
Qownnotes works fine without aspell. Aspell is optional and windows / mac don't have it. If you build without aspell, you will just have hunspell and everything will work as it should.

**Comment by Waqar144** [comment]
The dependency can be optional. In the build file we check for the presence of 'aspell'. And it gets enabled only if "aspell headers" are found, otherwise it is ignored during the compilation.

**Comment by pbek** [comment]
Thank you @Waqar144!
@scachemaille if you want you can propose a change in https://github.com/pbek/QOwnNotes/blob/develop/build-systems/aur/PKGBUILD with depends_x86_64 and depends__i686 as pull request.

**Comment by scachemaille** [comment]
I checked.. I'm not really on arch arm.. but manjaro.. aspell is on arch arm and I asked manjaro why it's not included.
I will close the issue..
I checked the source and if sonnet is built as static (like as for qownotes) if it's built with aspell then aspell is an mandatory at runtime. on linux it would be nice to have sonnet not static but using the library from KDE like this all plugins of sonnet would work.. and aspell could be optional but it's an other story.. ;) 

@Waqar144  don't confuse optional dependencies for runtime and optional dependencies at build..
yes aspell is optional at build time, you can build without aspell.. but then you won't be able to use aspell.
the feature is decided at build time.. not at run time.. like a plugin.

**Comment by pbek** [comment]
Thank you for checking!

**Comment by Waqar144** [comment]
> I checked the source and if sonnet is built as static (like as for qownotes) if it's built with aspell then aspell is mandatory at runtime or it will crash because it does not find the lib. on linux it would be nice to have sonnet not static but using the library from KDE like this all plugins of sonnet would work.. and aspell could be optional but it's an other story.. ;)

That would be good if we only supported Linux but unfortunately that's not the case.

If QON is built with aspell and for some unknown reason aspell wasn't found on the users system, the QON would probably just fail to start.
 
> @Waqar144 don't confuse optional dependencies for runtime and optional dependencies at build..
> yes aspell is optional at build time, you can build without aspell.. but then you won't be able to use aspell.
> the feature is decided at build time.. not at run time.. like a plugin. on arch PKGBUILD the optdepends define dependencies that add feature at runtime.

Right, if QON gets built with aspell, then aspell is a *mandaotry* runtime dependency. And if it got built, then it means aspell is available for that platform and in theory when a user installs / builds QON from AUR they *should* get those dependencies.

**Comment by scachemaille** [comment]
> Right, if QON gets form and in theory when a user installs / builds QON from AUR they should get those dependencies.
yes I understand that.. my comment was about I supposed my system did not had aspell available and I was searching a way to modify the PKGBUID without breaking other user experience etc.. then I needed to check if aspell could be optional at run time..  1st because the ARCH standard is to put all dependencies that are optional at runtime in `optdepends` and in `makedepends` if they are needed to build this optional feature and even if it's on AUR (as PKGBUID can be promoted to repository afterwards and it's better it is already following the standard). but after my search I saw that if QON is build with aspell then it become a dependency.. so the subject is close.. and I also discovered that aspell is finally availabe. then my issue is closed too.. :wink:
