### ISSUE TITLE
IOS/IPAD version?

### ISSUE THREAD

**Issue by yuxiacn** [pbek/QOwnNotes#1898]
Hi pbek,

I now use QOwnNotes veryday in different devices. Do you have a plan to develop an ios/ipad based version? Thanks.

**Comment by pbek** [comment]
No, sorry. Not very likely at the moment. 😁  That would be a completely different app. 

And there are other apps for that: https://www.qownnotes.org/getting-started/concept.html#ios

**Comment by yuxiacn** [comment]
Okay, thank you. That's no problem. I'll try CloudNotes - ownCloud Notes. But does this CloudNotes has linux version?


> No, sorry. Not very likely at the moment.  That would be a completely different app.
> 
> And there are other apps for that: https://www.qownnotes.org/getting-started/concept.html#ios

**Comment by pbek** [comment]
CloudNotes is an app to access your ownCloud / Nextcloud notes from your mobile device. QOwnNotes can use the same notes. See https://www.qownnotes.org/getting-started/concept.html#concept

**Comment by pbek** [comment]
On Linux you can use QOwnNotes.

**Comment by yuxiacn** [comment]
Okay, thanks pbek very much!

**Comment by pbek** [comment]
No problem :)
