### ISSUE TITLE
Debian install failure

### ISSUE THREAD

**Issue by ischorr** [pbek/QOwnNotes#1899]
#1486 

## Expected behaviour
Following the instructions here:  https://www.qownnotes.org/installation/debian.html#debian-10-0

Expect update to install.

#### Actual behaviour
Apt reports:
E: Malformed entry 1 in list file /etc/apt/sources.list.d/qownnotes.list (Suite)
E: The list of sources could not be read.

Looks like it's expecting a release and component name field in the sources.list, but A) the instructions provide none and B) it doesn't look like the dirs are structured to allow this

#### Steps to reproduce

Follow the steps at the link on Debian 10.

I would guess Ubuntu 20 is the same when installing a similar way, but haven't tested.

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by ischorr** [comment]
Just confirmed that Ubuntu 20 shows the same when trying to install with the OBS method.

**Comment by pbek** [comment]
Thank you for reporting.

Can you please try 

```bash
rm /etc/apt/sources.list.d/qownnotes.list
sudo bash -c "echo 'deb http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Debian_10/ /' >> /etc/apt/sources.list.d/qownnotes.list"
```

**Comment by pbek** [comment]
I think there was a ` /` missing.

**Comment by pbek** [comment]
I now also fixed that in the documentation.
