### ISSUE TITLE
User-defined font settings

### ISSUE THREAD

**Issue by gnotaras** [pbek/QOwnNotes#19]
It would be nice to let users define the fonts for the editor/viewer. The current font size is too small.

**Comment by pbek** [comment]
It should use the system font size, on what system are you using QOwnNotes?
In any case your idea is a good one, I will put it on my todo list, thank you!

**Comment by pbek** [comment]
This is now implemented in version 0.57 on <http://www.qownnotes.org/>.

**Comment by gnotaras** [comment]
Fantastic! Just tried it and I'm excited with this addition. Thanks a lot. The fact that you really care about improving this software really makes a difference. Keep up the good work!

**Comment by pbek** [comment]
@gnotaras thanks again for your invigorating words! They are making all the difference for me too!
