### ISSUE TITLE
Umlauts and other special characters show as diamond with question mark

### ISSUE THREAD

**Issue by ImVeryVeryStupid** [pbek/QOwnNotes#190]
Here's what I do:
Create file named äåæöøü.txt
Open the file in notepad and type in äåæöøü
Start QOwnNotes
The filename shows CORRECTLY on the left
Edit pane shows only diamonds
Markdown preview shows only diamonds

So basically I'm getting lots of diamonds on all notes I do with Windows notepad and dump in the notes folder. Also if I type those same characters in the QOwnNotes editor it will show äåæöøü.

Using Windows 7 with US english as language and finnish keyboard layout.

**Comment by pbek** [comment]
When I create a file with Windows Notepad the character set used is `Western (Windows 1252)`. Are you able to use a more sophisticated text editor, like <https://www.sublimetext.com>?

**Comment by pbek** [comment]
I'll close this issue now, feel free to reply to it...
