### ISSUE TITLE
Importing from Tomboy Notes

### ISSUE THREAD

**Issue by sierracircle** [pbek/QOwnNotes#1901]
Someone had opened an suggestion in the past about importing from Tomboy Notes, but they never followed up on it. I would like to re-open this suggestion.

I am among the people who have hundreds of Tomboy notes. I would love a way to import them and have the xml formatting converted.
I am attaching one note, but can add more if needed.

The file-extension for Tomboy Notes is just .note   but I changed it to .txt so it would let me add it to this commment

[15b4ee2a-2365-4271-b898-f3c3a1244422.txt](https://github.com/pbek/QOwnNotes/files/5314500/15b4ee2a-2365-4271-b898-f3c3a1244422.txt)

_Originally posted by @sierracircle in https://github.com/pbek/QOwnNotes/issue_comments/702371175_

**Comment by pbek** [comment]
This easily also could be done outside of QOwnNotes.
https://github.com/leonhandreke/tomboy-markdown might be such an example.

Did you try to use that, @sierracircle?

**Comment by sierracircle** [comment]
Thanks for the tip. I was not able to get that script to work; however, I found a different one here:
https://github.com/samba/trombone

I had to install python2 to make it work, but it converted all of my tomboy notes to an Evernote .enex file, which then was able to import to qOwnNotes.

For anyone wanting to do this, first make sure you have Python2 installed and you might want to also install python-is-python2 (you can remove that later):

`sudo apt install python2  python-is-python2`

download the trombone file from git, extract and cd into that folder:

`cd ~/Downloads/trombone-master`

```
sudo make
sudo make install
```

Then cd into the folder where your tomboy notes are:

`cd ~/.local/share/tomboy/`


Then run this:
`find ./ -type f -name '*.note' -print0 | xargs -0 trombone > EXPORT.enex`

I got a few unicode errors on a couple of my notes. I just removed those notes and ran again and it all worked. I ended up with a file called EXPORT.enex   which then imported into qOwnNotes.
During the import I unchecked all of those attributes except the creation/mod date.

**Comment by pbek** [comment]
Good idea searching for a Tomboy2Enex converter and thank you for the guide! 😁

**Comment by sierracircle** [comment]
Thank you for a wonderful note application that syncs perfectly in NextCloud!

**Comment by pbek** [comment]
Thank you for your kind words!

> thank you for the guide! grin

I'm now preparing an "import notes" page. Do you want to write a Tomboy guide there?

**Comment by sierracircle** [comment]
Yes, I will do that. Send me a link to where it will be

**Comment by pbek** [comment]
There you are: https://github.com/pbek/QOwnNotes/edit/develop/webpage/src/getting-started/importing-notes.md
