### ISSUE TITLE
[F] Full Emoji support for note names

### ISSUE THREAD

**Issue by smac89** [pbek/QOwnNotes#1904]
#### Expected behaviour

Some of my notes have emoji's beside their names, but not all of them are displayable.

#### Actual behaviour

Some of the emojis are not properly displayed.

#### Steps to reproduce

- Attempt to name a note using an emoji from emojipedia
- The emoji is displayed as a square

Example: 🤲 is not displayable

Is there a setting I am missing, which allows me to use a font that can display the emojis, or is this a limitation of the app in terms of supporting emojis?

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[21:33:12] [status] Your tasks are being loaded from your server
[21:43:12] [status] Your tasks are being loaded from your server
[21:52:47] [status] Note was modified externally: /home/chigozirim/Nextcloud/Notes/School/Project ideas/Google Captcha solver which uses native messaging to send a catcha request to our native app which s.md
[21:53:12] [status] Your tasks are being loaded from your server
[21:53:52] [status] Stored 1 note(s) to disk
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed. Oct. 14 21:33:11 2020`
**Version**: `20.10.4`
**Build date**: `Oct 15 2020`
**Build number**: `771`
**Platform**: `linux`
**Operating System**: `Linux 5.8.14-arch1-1`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.1`
**Qt Version (runtime)**: `5.15.1`
**Portable mode**: `no`
**Settings path / key**: `/home/chigozirim/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/chigozirim/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_CA`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 2560x1080`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `46`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://us.cloudamo.com`
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_CA, en_CA-large, en_US, en_US-large`
**Language names**: `Canadian English (Canada), Canadian English (Canada) [large], American English (United States), American English (United States) [large]`
**Application dictionaries path**: `/home/chigozirim/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-2`
**localPath**: `/home/chigozirim/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `🎯 Planning`
**database file**: `/home/chigozirim/Nextcloud/Notes/notes.sqlite`

### Cloud connection `NextCloud`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://us.cloudamo.com`
**username**: `noblechuk5@web.de`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `true`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `35`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-2f30b571-9e15-4762-8ed9-7f2c6862e934`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrainingSpaces** (bool): `true`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-10-14T21:03:13.020`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `16`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Products`
**MainWindow/noteTextEdit.code.font** (QString): `Space Mono,11,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Roboto,11,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Noto Sans Mono,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Noto Sans,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**NoteFolder-1/NoteTabNameList** (QStringList): `🧳Travelling after school`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): 
```
School
🎯 Planning
```
**NoteFolder-1/allowDifferentNoteFileName** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 15 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `14`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `true`
**StartHidden** (bool): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `true`
**darkModeColors** (bool): `true`
**darkModeIconTheme** (bool): `true`
**darkModeTrayIcon** (bool): `true`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `true`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `14`
**interfaceLanguage** (QString): *empty*
**interfaceStyle** (QString): `Fusion`
**internalIconTheme** (bool): `false`
**itemHeight** (int): `26`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/chigozirim/Nextcloud/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `true`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Personal, Deck: Personal`
**ownCloud/todoCalendarEnabledList** (QStringList): `Personal, Deck: Personal`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://us.cloudamo.com/remote.php/dav/calendars/noblechuk5@web.de/personal/, https://us.cloudamo.com/remote.php/dav/calendars/noblechuk5@web.de/app-generated--deck--board-3356/`
**ownCloud/todoCalendarUrlList** (QStringList): `https://us.cloudamo.com/remote.php/dav/calendars/noblechuk5@web.de/personal/, https://us.cloudamo.com/remote.php/dav/calendars/noblechuk5@web.de/app-generated--deck--board-3356/`
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (bool): `true`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (bool): `true`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (bool): `true`
**useUNIXNewline** (bool): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**SHELL**: `/usr/bin/zsh`
**XDG_CONFIG_DIRS**: `/etc/xdg`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**XDG_MENU_PREFIX**: `xfce-`
**LC_ADDRESS**: `en_CA.UTF-8`
**LC_NAME**: `en_CA.UTF-8`
**XSECURELOCK_SAVER**: `saver_xscreensaver`
**XDG_CONFIG_HOME**: `/home/chigozirim/.config`
**XSECURELOCK_FORCE_GRAB**: `1`
**DESKTOP_SESSION**: `/usr/share/xsessions/xfce`
**LC_MONETARY**: `en_CA.UTF-8`
**XSECURELOCK_SINGLE_AUTH_WINDOW**: `1`
**EDITOR**: `/usr/bin/nano`
**XSECURELOCK_PASSWORD_PROMPT**: `disco`
**GTK_MODULES**: `canberra-gtk-module:canberra-gtk-module`
**XDG_SEAT**: `seat0`
**PWD**: `/home/chigozirim`
**XDG_SESSION_DESKTOP**: `XFCE`
**LOGNAME**: `chigozirim`
**QT_QPA_PLATFORMTHEME**: `qt5ct`
**XDG_SESSION_TYPE**: `x11`
**XAUTHORITY**: `/home/chigozirim/.Xauthority`
**MOTD_SHOWN**: `pam`
**HOME**: `/home/chigozirim`
**AUTOJUMP_ERROR_PATH**: `/home/chigozirim/.local/share/autojump/errors.log`
**LANG**: `en_CA.UTF-8`
**LC_PAPER**: `en_CA.UTF-8`
**XDG_CURRENT_DESKTOP**: `XFCE`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**LC_IDENTIFICATION**: `en_CA.UTF-8`
**XSECURELOCK_AUTH_TIMEOUT**: `30`
**XSECURELOCK_SHOW_DATETIME**: `1`
**USER**: `chigozirim`
**XSECURELOCK_DEBUG_WINDOW_INFO**: `1`
**VISUAL**: `/usr/bin/subl3 --new-window --wait`
**AUTOJUMP_SOURCED**: `1`
**SHLVL**: `0`
**LC_TELEPHONE**: `en_CA.UTF-8`
**ANDROID_SDK_ROOT**: `/home/chigozirim/Libraries/android/sdk`
**LC_MEASUREMENT**: `en_CA.UTF-8`
**XDG_VTNR**: `7`
**XDG_SESSION_ID**: `2`
**MOZ_PLUGIN_PATH**: `/usr/lib/mozilla/plugins`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**LC_TIME**: `en_CA.UTF-8`
**FLUTTER_ROOT**: `/home/chigozirim/Libraries/flutter`
**ELECTRON_TRASH**: `trash-cli`
**XSECURELOCK_FONT**: `Noto Serif CJK JP`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `1`
**XDG_DATA_DIRS**: `/home/chigozirim/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/usr/share`
**PATH**: `/home/chigozirim/Libraries/flutter/bin:/home/chigozirim/Libraries/android/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/google-appengine-java/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**MAIL**: `/var/spool/mail/chigozirim`
**LC_NUMERIC**: `en_CA.UTF-8`
**OLDPWD**: `/home/chigozirim`
**SESSION_MANAGER**: `local/ArcoB:@/tmp/.ICE-unix/1181,unix/ArcoB:/tmp/.ICE-unix/1181`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**DISPLAY**: `:0.0`
</details>

**Comment by pbek** [comment]
To my knowledge you are missing the proper font to show them in your Linux distribution.

**Comment by pbek** [comment]
Does those emojis work inside the note text?

**Comment by smac89** [comment]
@pbek

> To my knowledge you are missing the proper font to show them in your Linux distribution.

I was hoping this was the case. Is there an option to change the font that controls this? I only see editor font option. Is that the one that also controls this?

> Does those emojis work inside the note text?

Yes in the nextcloud notes app, the emojis work

**Comment by pbek** [comment]
> I was hoping this was the case. Is there an option to change the font that controls this? I only see editor font option. Is that the one that also controls this?

To my knowledge those fonts add emoji characters to every font, I've those on KDE Neon, where all emojis work:

```
ii  fonts-noto-color-emoji                          0~20200408-1                                        all          color emoji font from Google
ii  fonts-symbola                                   2.60-1                                              all          symbolic font providing emoji characters from Unicode 9.0
ii  ibus-table-emoji                                1.3.9-4                                             all          ibus-table input method: Emoji
ii  ttf-ancient-fonts-symbola                       2.60-1                                              all          symbolic font providing emoji chars from Unicode 9.0 (transit. pkg)
```

> Yes in the nextcloud notes app, the emojis work

No, I mean in the note text in QOwnNotes.

**Comment by smac89** [comment]
@pbek 

> No, I mean in the note text in QOwnNotes.

No it doesn't work in the editor either

I have `noto-color-emoji` font installed, and after I switched the editor font to use it, the editor can now display emojis, but with that, the rest of the text inside the editor looks very bad with weird spacing all round the letters. Moreover, even this does not fix the issue with the emoji in the names of the notes - they are still displayed as blocks

**Comment by pbek** [comment]
Looking pretty nice here...

![image](https://user-images.githubusercontent.com/1798101/96083160-e6938480-0ebc-11eb-9962-53923e84e63e.png)

**Comment by smac89** [comment]
Hmm, could you tell me what font you're using?

Also do you think this is a system issue? I am using XFCE on Arch

**Comment by pbek** [comment]
This ones: <https://github.com/pbek/QOwnNotes/issues/1904#issuecomment-708912307>

**Comment by pbek** [comment]
> Also do you think this is a system issue? I am using XFCE on Arch
> Or maybe a Qt issue?

Both possible, do you have other Qt apps to test? Do you see Emojis in non-qt apps?

**Comment by smac89** [comment]
I guess this was just a problem I never noticed my system had until now.

After many hours of googling, I discovered a [reddit post](https://www.reddit.com/r/linux/comments/ao0mp3/how_to_better_enable_color_emojis) that helped me fix this. I just needed to add the following to my `~/.config/fontconfig/font.conf`:

```xml
<match target="pattern"> 
    <edit name="family" mode="append"> 
    <string>Noto Color Emoji</string> 
    </edit>
</match> 
```

Now emojis display properly
