### ISSUE TITLE
Also align table source on autoformat

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#1905]
The autoformat functionality for tables in QON is great, but could be improved by also aligning the content:

Right now:
```
|        |             |        |
| ------ | ---:        | ------ |
| 1      | 1           | 1      |
| 2      | 2           | 2      |
| 4      | 3           | 3      |
| longer | longer      | longer |
| longer | even longer | longer |
```

Could be: 

```
|        |             |        |
| ------ | ----------: | ------ |
| 1      |           1 | 1      |
| 2      |           2 | 2      |
| 4      |           3 | 3      |
| longer |      longer | longer |
| longer | even longer | longer |
```

## General Info

**Current Date**: `do okt. 15 15:33:51 2020`
**Version**: `20.9.11`
**Build date**: `Sep 26 2020`
**Build number**: `766`
**Platform**: `linux`
**Operating System**: `Manjaro Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.0`
**Qt Version (runtime)**: `5.15.1`
**Portable mode**: `no`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Enabled scripts**: `7`

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
## 20.10.6
- you can now also change the alignment of your markdown table by setting it in
  the table header and pressing <kbd>Ctrl</kbd> + <kbd>Space</kbd>
  (for [#1905](https://github.com/pbek/QOwnNotes/issues/1905), thank you @fnkabit)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by sanderboom** [comment]
Awesome, works great. Thanks for the quick implementation! :rocket:  @fnkabit @pbek

**Comment by pbek** [comment]
Great, thank you for testing!
