### ISSUE TITLE
Image doesn't display properly in preview mode

### ISSUE THREAD

**Issue by RichardBaker3020** [pbek/QOwnNotes#1907]
Image doesn't display properly in preview mode.

- Edit mode:

![image](https://user-images.githubusercontent.com/54793121/96361940-71de7580-115c-11eb-8c4a-e4745e77efc8.png)

- Preview mode:

![image](https://user-images.githubusercontent.com/54793121/96361949-7c990a80-115c-11eb-8467-ee6eea06046a.png)

But it can be opened in external image viewer with Ctrk - left click hotkey.

**Comment by pbek** [comment]
Thank you for reporting.
Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting `Debug` in `Options`).

**Comment by RichardBaker3020** [comment]
@pbek Turn out to be the problem of _markdown-it_ script, after disabling this script the image can be rendered properly with the original markdown renderer. 

It seems  _markdown-it_ script only supports specific image markdown format:
```
![qownnotes-media-xagnCC](file://media/qownnotes-media-xagnCC-3342373562.png)

![media-LehQCY](../media/media-LehQCY-1237789685.png)

![image](https://user-images.githubusercontent.com/54793121/96361949-7c990a80-115c-11eb-8467-ee6eea06046a.png)
```
Only the first format will be rendered correctly:

![image](https://user-images.githubusercontent.com/54793121/96363348-48c2e280-1166-11eb-9b88-c557f1b0c5bd.png)

But All three formats work with original markdown renderer.

Maybe I should report this issue to the script author?

**Comment by pbek** [comment]
I thought as much. There already is an issue: https://github.com/qownnotes/scripts/issues/77

You can subscribe to that issue.

Meanwhile, I updated the script description to use legacy media links.
