### ISSUE TITLE
Undefined symbol on Ubuntu Trusty with pre-compiled binary.

### ISSUE THREAD

**Issue by aventrax** [pbek/QOwnNotes#191]
Hi, I'm installing Qownnotes downloaded from the ufficial page:

    QOwnNotes Ubuntu Linux 64bit
    version 16.05.23 - build linux-b1687-182523
    QOwnNotes-16.05.23.deb (2 MB)
    May 27, 2016 20:25

I also installed qt56 as you suggest, but I got an error launching the application:

$ QOwnNotes 
QOwnNotes: symbol lookup error: QOwnNotes: undefined symbol: _ZN8QSysInfo17prettyProductNameEv

Any suggestion? Thanks.

**Comment by pbek** [comment]
Can you please check out #189. You might have the same problem.
