### ISSUE TITLE
Feature: Don't spell check inline code spans

### ISSUE THREAD

**Issue by Waqar144** [pbek/QOwnNotes#1911]
Currently inline code spans are checked for spellings which results in a lot of  meaningless red underlines all over the place.

### Design idea

Store inline code span information in base `MarkdownHighliter` class when we do the highlighting. Then use this information to figure out whether to spell check the current word or not.

### Cons
This will likely effect the performance a bit **if** the note is too large with hundreds of code spans.

**Comment by pbek** [comment]
Does this already work with https://github.com/pbek/qmarkdowntextedit/pull/128?

**Comment by Waqar144** [comment]
> Does [pbek/qmarkdowntextedit#128](https://github.com/pbek/qmarkdowntextedit/pull/128) already fulfill your feature request?

No, there is a small change we need to make in QON as well

**Comment by pbek** [comment]
ok

**Comment by pbek** [comment]
## 20.10.5
- inline code spans will now not be spell checked (for [#1911](https://github.com/pbek/QOwnNotes/issues/1911), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
