### ISSUE TITLE
Thank you very much for the free open source program!

### ISSUE THREAD

**Issue by s-r-grass** [pbek/QOwnNotes#1919]
Hello, thank you very much for a good program under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%B4%D1%80%D1%83%D0%B3%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B/qqwnnotes-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%B7%D0%B0%D0%BC%D0%B5%D1%82%D0%BA%D0%B0%D0%BC%D0%B8.html).

The project is interesting, so please don't abandon it!

**Comment by pbek** [comment]
Thank you for your kind words, I added your link to the reference page. 😁
