### ISSUE TITLE
Wish: compose in rich text rather than markdown

### ISSUE THREAD

**Issue by xandark** [pbek/QOwnNotes#192]
Nice program and great integration! I've been looking for something to replace the unsupported "BasKet Note Pads" from the KDE3 era. I liked that program because I could compose in rich text, the format was standard HTML files, and I could create arbitrary hierarchies of folders.

For me, I am not concerned with the format the notes are stored in. Rather, I'm looking for a fast way to make new notes. Personally, if I have to think of how to write in markdown, then that's an extra cognitive step that gets in the way of my creativity. I don't want to have to analyze why my markdown isn't perfect. 

Therefore, I would love it if QOwnNotes I could just compose in the rich text view and have the computer figure out how to convert that back into its own internal representation, that being markdown. Why shouldn't the computer do the hard work?

So if I could hide the markdown view and compose in rich text, that would be a win for me. I'll keep my eyes on this project and see how it develops. So far, so good!

**Comment by pbek** [comment]
Thank you for your kind words, @xandark!

But I don't think that "rich text" and html are suited for jotting down quick notes and I guess QOwnNotes will never do that.

That's what ownNote is doing.
please also see: <http://www.qownnotes.org/Knowledge-base/Does-QOwnNotes-support-ownNote>

If you like rich text you better stick with the ownNote webapp...

**Comment by xandark** [comment]
Hello pbek,

For editing in rich text mode, I wasn't implying to store the note data in HTML. Storing in markdown text files is perfectly fine.

As for the "quickness" of the intended use of QOwnNotes, I have to type a lot more to get a H1, and have to be more analytical about how the structure of the markup is crafted if it is to be rendered into a list or a table or a code block. That turns me into a computer parsing the markup to make sure it renders. All this slows me down when I just want to have some structure to my notes. So the idea that QOwnNotes is for "jotting down quick notes" doesn't agree with me. 

The way I see it, there's already a rich text view of the note. Why not edit there and have the computer convert that behind the scenes to markdown? I think it would be a win for you because it would increase your appeal and adoption for non-technical people. I know this because I install Kubuntu on many people's computers and they want something that just works, is intuitively understandable, and is familiar. This kind of program would be great for them but I know that if said to them that they *had to* learn a new way of writing their text to get some kind of style or structure, it would put them off.

As it is now, QOwnNotes *insists* that someone learn this new way of writing their text files.

**Comment by pbek** [comment]
Typing `# your headline` to get
# your headline
is in your eyes more work that writing `your headline`, marking the text and then format it as headline?
Markdown is no markup...
And markdown is by no means a "new way". Even GitHub is using it right now here where you are typing...

**Comment by xandark** [comment]
Okay, I'm done here. Your program is for programmers, and that's that.

**Comment by pbek** [comment]
Oh, hardly. All kind of people are using QOwnNotes daily and unfortunately only very few of them are programmers... 
If they were there would also be more code contributions. :smile: 

QOwnNotes is for people who need to jot down information very quickly and want to really own their data.

**Comment by olantrust** [comment]
There is an editor that lets you choose between text entry via html and markdown, storing the data as plain text, and interchangeable between the entry methods:
https://github.com/bevacqua/woofmark

**Comment by pbek** [comment]
I'm sorry, but it's a nodejs app...

**Comment by olantrust** [comment]
Oh ok
