### ISSUE TITLE
[F] Add option to show only notes which match all selected tags

### ISSUE THREAD

**Issue by zarlin** [pbek/QOwnNotes#1920]
#### Expected behaviour

When selecting multiple tags, the notes list shows the notes which match ALL of the selected tags (binary AND)
Ideally, this would be toggleable in the settings, and/or the behaviour can be switched by holding Alt when selecting.

#### Actual behaviour

When selecting multiple tags, the notes list shows the notes which match ANY of the selected tags (binary OR)

#### Steps to reproduce

- Select two or more tags in the tags view
- See that the notes list now contains notes which match any of those tags

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mon Oct 26 15:54:08 2020`
**Version**: `20.10.8`
**Build date**: `Oct 26 2020`
**Build number**: `775`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\Zarlin\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Portable\QOwnNotes\QOwnNotes.exe`, `--after-update`, `C:\Users\Zarlin\AppData\Local\Temp\QOwnNotes-UahlKd-updater.bat`
**Qt Debug**: `0`
**Locale (system)**: `en_NL`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `330`
**Calendar items**: `0`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\Zarlin\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `20`
**localPath**: `D:\QOwnNotes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `D:\QOwnNotes\notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

### Script `List maker`

**id**: `1`
**path**: `C:\Users\Zarlin\AppData\Roaming\PBE\QOwnNotes\scripts\list-maker\list-maker.qml`
**variablesJson**: 
```
{
    "setLetters": "abcdefghijklmnopqrstuvwxyz",
    "setMarkers": "- • ‣"
}
```
**identifier**: `list-maker`
**version**: `0.0.2`
**minAppVersion**: `17.07.8`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/editorWidthMode** (int): `4`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `false`
**Editor/autoBracketRemoval** (QString): `false`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `false`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrainingSpaces** (QString): `false`
**Editor/useTabIndent** (QString): `true`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-10-26T14:53:23.337`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,12,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `true`
**MainWindow/tagTreeWidgetExpandState-1** (QStringList): `3`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): `waterbattle analytics backend`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `Grendel`
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 140 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `139`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExportOrientation** (int): `0`
**Printer/NotePDFExportPageSize** (int): `4`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-customAction_list -** (QString): *empty*
**Shortcuts/MainWindow-customAction_list 123** (QString): *empty*
**Shortcuts/MainWindow-customAction_list abc** (QString): *empty*
**Shortcuts/MainWindow-customAction_list clear** (QString): *empty*
**Shortcuts/MainWindow-customAction_list •** (QString): *empty*
**Shortcuts/MainWindow-customAction_list ‣** (QString): *empty*
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `false`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (int): `15`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `true`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `true`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `D:/QOwnNotes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**skipVersion** (QString): `20.10.4`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `true`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**AMDRMPATH**: `C:\Program Files\AMD\RyzenMaster\`
**ANDROID_SDK_HOME**: `C:\Android`
**ANDROID_SDK_ROOT**: `C:\Android\sdk`
**APPDATA**: `C:\Users\Zarlin\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPOSER_MEMORY_LIMIT**: `-1`
**COMPUTERNAME**: `LILIYA`
**ComSpec**: `C:\Windows\system32\cmd.exe`
**destination**: `C:\Portable\QOwnNotes`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**GIT_SSH**: `C:/Windows/System32/OpenSSH/ssh.exe`
**GTK_BASEPATH**: `C:\Program Files (x86)\GtkSharp\2.12\`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\Zarlin`
**JAVA_HOME**: `C:\Android\java-se-8u41-ri`
**LOCALAPPDATA**: `C:\Users\Zarlin\AppData\Local`
**LOGONSERVER**: `\\LILIYA`
**NUMBER_OF_PROCESSORS**: `16`
**OneDrive**: `C:\Users\Zarlin\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Python38-32\Scripts\;C:\Program Files (x86)\Python38-32\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Calibre2\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\CMake\bin;C:\Android;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Inkscape\bin;C:\Program Files\Pandoc\;C:\Program Files\PuTTY\;C:\ProgramData\ComposerSetup\bin;C:\Program Files\nodejs\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\dotnet\;C:\laragon\bin\php\php-7.4.10-nts-Win32-vc15-x64;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Bluetooth Command Line Tools\bin;C:\SDKs\flutter\bin;C:\laragon\bin;C:\laragon\bin\apache\httpd-2.4.35-win64-VC15\bin;C:\laragon\bin\composer;C:\laragon\bin\git\bin;C:\laragon\bin\git\cmd;C:\laragon\bin\git\mingw64\bin;C:\laragon\bin\git\usr\bin;C:\laragon\bin\laragon\utils;C:\laragon\bin\mysql\mysql-5.7.24-winx64\bin;C:\laragon\bin\nginx\nginx-1.16.0;C:\laragon\bin\ngrok;C:\laragon\bin\nodejs\node-v12;C:\laragon\bin\notepad++;C:\laragon\bin\php\php-7.4.10-nts-Win32-vc15-x64;C:\laragon\bin\putty;C:\laragon\bin\redis\redis-x64-3.2.100;C:\laragon\bin\telnet;C:\laragon\usr\bin;C:\Users\Zarlin\AppData\Local\Yarn\config\global\node_modules\.bin;C:\Users\Zarlin\AppData\Roaming\Composer\vendor\bin;C:\Users\Zarlin\AppData\Roaming\npm;C:\Users\Zarlin\AppData\Local\Microsoft\WindowsApps;C:\Android;C:\Users\Zarlin\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Users\Zarlin\AppData\Roaming\Python\Python38\Scripts;C:\SDKs\flutter\bin;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD`
**PROCESSOR_LEVEL**: `23`
**PROCESSOR_REVISION**: `7100`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PROMPT**: `$P$G`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Intel\Wired Networking\`
**PUBLIC**: `C:\Users\Public`
**qownnotesCommand**: `C:\Portable\QOwnNotes\QOwnNotes.exe --after-update C:\Users\Zarlin\AppData\Local\Temp\QOwnNotes-UahlKd-updater.bat `
**SESSIONNAME**: `Console`
**source**: `C:\Users\Zarlin\AppData\Local\Temp\QOwnNotes-UahlKd.zip`
**SVN_EXPERIMENTAL_COMMANDS**: `shelf2`
**SystemDrive**: `C:`
**SystemRoot**: `C:\Windows`
**TEMP**: `C:\Users\Zarlin\AppData\Local\Temp`
**TMP**: `C:\Users\Zarlin\AppData\Local\Temp`
**TsuronEngine**: `D:\Projects\C++\TsuronEngine\`
**unzipCommand**: `C:\Users\Zarlin\AppData\Local\Temp\QOwnNotes-UahlKd-unzip.exe -o C:\Users\Zarlin\AppData\Local\Temp\QOwnNotes-UahlKd.zip -d C:\Portable\QOwnNotes`
**unzipExecutable**: `C:\Users\Zarlin\AppData\Local\Temp\QOwnNotes-UahlKd-unzip.exe`
**USERDOMAIN**: `LILIYA`
**USERDOMAIN_ROAMINGPROFILE**: `LILIYA`
**USERNAME**: `Zarlin`
**USERPROFILE**: `C:\Users\Zarlin`
**windir**: `C:\Windows`
**__COMPAT_LAYER**: `DetectorsMessageBoxErrors`
</details>

It should be already in your clipboard.

**Comment by pbek** [comment]
I think you are talking about #1702, right?

**Comment by zarlin** [comment]
Yep, my bad, didn't search properly.
