### ISSUE TITLE
when creating a new note, how to not show the note title? 

### ISSUE THREAD

**Issue by needhelpfulanswers-spectrumchat** [pbek/QOwnNotes#1922]
cant find in settings

**Comment by pbek** [comment]
Can you please fill out the issue template or use the issue assistant of QOwnNotes (in the *Help* menu). It's hard to know what we are talking about if you don't. 😆

**Comment by needhelpfulanswers-spectrumchat** [comment]
expected: new note has no title

actual: new note is created with title of [note + date]

**Comment by needhelpfulanswers-spectrumchat** [comment]
expected: when you start typing it should, it should start at the title

actual: typing starts at the body of note

**Comment by pbek** [comment]
Both are the way QOwnNotes works and should work. But you can modify some things with the help of the scripting engine.

**Comment by pbek** [comment]
But keep in mind that by default the headline will be used as file name.
