### ISSUE TITLE
[I] ~/.XCompose is ignored

### ISSUE THREAD

**Issue by tomatic** [pbek/QOwnNotes#1932]
#### Expected behaviour

I have a .XCompose in my home directory with the following contents:

```
include "/usr/share/X11/locale/en_US.UTF-8/Compose"
<Multi_key> <u> <e> : "ü" 00FC
<Multi_key> <U> <E> : "Ü" 00DC
<Multi_key> <a> <e> : "ä" 00E4
<Multi_key> <A> <E> : "Ä" 00C4
<Multi_key> <o> <e> : "ö" 00F6
<Multi_key> <O> <E> : "Ö" 00D6
```

I would expect QOwnNotes to load the settings in this file, i. e. that I can type `<Multi_key><o><e>` to enter an `ö`.

#### Actual behaviour

The file `~/.XCompose` is ignored by QOwnNotes, it only loads the compose key settings from `/usr/share/X11/locale/en_US.UTF-8/Compose`. So to type a `ö` I have to enter the default compose sequence `<Multi_key><o><">`.

#### Steps to reproduce

Type a custom compose key sequence from your `~/.XCompose` into a note.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `So. Nov. 1 09:08:36 2020`
**Version**: `20.10.11`
**Build date**: `Oct 28 2020`
**Build number**: `778`
**Platform**: `linux`
**Operating System**: `Ubuntu Core 18`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Snapcraft`
**Qt Version (build)**: `5.9.5`
**Qt Version (runtime)**: `5.9.5`
**Portable mode**: `no`
**Settings path / key**: `/home/thomas/snap/qownnotes/7643/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/thomas/snap/qownnotes/7643/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/snap/qownnotes/7643/usr/bin/QOwnNotes`, `-style=Breeze`, `--snap`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breeze`
**Notes in current note folder**: `18`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/home/thomas/snap/qownnotes/7643/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/thomas/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `s`
**database file**: `/home/thomas/Nextcloud/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrainingSpaces** (bool): `false`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-11-01T08:19:40`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `DejaVu Sans Mono,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Noto Sans,-1,10,255,5,2,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteDialog/tabWidgetIndex** (int): `1`
**NoteFolder-1/NoteTabNameList** (QStringList): `Tagesplan Ostsee`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `s`
**NoteFolder-1/allowDifferentNoteFileName** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 9 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `8`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (int): `24`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/thomas/Nextcloud/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**restoreCursorPosition** (bool): `true`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**savedSearches/noteFolder-1** (QString): `Note 2020-10-30T10.01.18`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**DATADIR**: `/media/thomas/bkp2go`
**__EGL_VENDOR_LIBRARY_DIRS**: `/snap/qownnotes/7643/etc/glvnd/egl_vendor.d:/snap/qownnotes/7643/usr/share/glvnd/egl_vendor.d`
**KDE_FULL_SESSION**: `true`
**LIBGL_DRIVERS_PATH**: `/snap/qownnotes/7643/usr/lib/x86_64-linux-gnu/dri`
**LD_LIBRARY_PATH**: `/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/qownnotes/7643/lib/x86_64-linux-gnu:/snap/qownnotes/7643/usr/lib/x86_64-linux-gnu::/snap/qownnotes/7643/lib:/snap/qownnotes/7643/usr/lib:/snap/qownnotes/7643/lib/x86_64-linux-gnu:/snap/qownnotes/7643/usr/lib/x86_64-linux-gnu:/snap/qownnotes/7643/usr/lib/x86_64-linux-gnu/dri`
**FONTCONFIG_PATH**: `/snap/qownnotes/7643/etc/fonts`
**LC_MEASUREMENT**: `de_DE.UTF-8`
**XDG_CONFIG_HOME**: `/home/thomas/snap/qownnotes/7643/.config`
**LC_PAPER**: `de_DE.UTF-8`
**LC_MONETARY**: `de_DE.UTF-8`
**LIBVA_DRIVERS_PATH**: `/snap/qownnotes/7643/usr/lib/x86_64-linux-gnu/dri`
**QTWEBENGINEPROCESS_PATH**: `/snap/qownnotes/7643/usr/lib/x86_64-linux-gnu/qt5/libexec/QtWebEngineProcess`
**PULSE_SERVER**: `unix:/run/user/1000/snap.qownnotes/../pulse/native`
**GST_PLUGIN_SYSTEM_PATH**: `/snap/qownnotes/7643/usr/lib/x86_64-linux-gnu/gstreamer-1.0`
**SNAP_USER_DATA**: `/home/thomas/snap/qownnotes/7643`
**LANG**: `en_US.UTF-8`
**QT_PRINTER_MODULE**: `qtubuntu-print`
**DISPLAY**: `:0`
**QTCHOOSER_NO_GLOBAL_DIR**: `1`
**XKB_CONFIG_ROOT**: `/snap/qownnotes/7643/usr/share/X11/xkb`
**SNAP_REVISION**: `7643`
**DISABLE_WAYLAND**: `1`
**GST_PLUGIN_PATH**: `/snap/qownnotes/7643/usr/lib/x86_64-linux-gnu/gstreamer-1.0`
**SNAP_ARCH**: `amd64`
**SNAP_INSTANCE_KEY**: *empty*
**XDG_VTNR**: `1`
**QT_SELECT**: `snappy-qt5`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**SSH_AUTH_SOCK**: `/tmp/ssh-arPp1CoHheKf/agent.1057`
**SNAP_REAL_HOME**: `/home/thomas`
**LC_NAME**: `de_DE.UTF-8`
**XDG_SESSION_ID**: `3`
**SNAP_USER_COMMON**: `/home/thomas/snap/qownnotes/common`
**USER**: `thomas`
**DESKTOP_SESSION**: `plasma`
**GTK2_RC_FILES**: `/etc/gtk-2.0/gtkrc:/home/thomas/.gtkrc-2.0:/home/thomas/.config/gtkrc-2.0`
**QT_QPA_PLATFORMTHEME**: `gtk3`
**PWD**: `/home/thomas`
**HOME**: `/home/thomas/snap/qownnotes/7643`
**QTCOMPOSE**: `/snap/qownnotes/7643/usr/share/X11/locale`
**SNAP_LAUNCHER_ARCH_TRIPLET**: `x86_64-linux-gnu`
**SNAP**: `/snap/qownnotes/7643`
**SSH_AGENT_PID**: `1101`
**QT_ACCESSIBILITY**: `1`
**XCURSOR_SIZE**: `24`
**SNAP_COMMON**: `/var/snap/qownnotes/common`
**XDG_SESSION_TYPE**: `x11`
**SNAP_NAME**: `qownnotes`
**GTK_PATH**: `/snap/qownnotes/7643/usr/lib/x86_64-linux-gnu/gtk-2.0`
**XDG_DATA_DIRS**: `/home/thomas/snap/qownnotes/7643/.local/share:/home/thomas/snap/qownnotes/7643:/snap/qownnotes/7643/data-dir:/snap/qownnotes/7643/usr/share:/usr/share/plasma:/usr/local/share:/usr/share:/var/lib/snapd/desktop`
**SNAP_INSTANCE_NAME**: `qownnotes`
**SNAP_DATA**: `/var/snap/qownnotes/7643`
**XDG_SESSION_DESKTOP**: `KDE`
**LC_ADDRESS**: `de_DE.UTF-8`
**QML2_IMPORT_PATH**: `/snap/qownnotes/7643/lib/x86_64-linux-gnu:/snap/qownnotes/7643/usr/lib/x86_64-linux-gnu/qt5/qml`
**TMPDIR**: `/tmp`
**LC_NUMERIC**: `de_DE.UTF-8`
**GDK_PIXBUF_MODULE_FILE**: `/home/thomas/snap/qownnotes/common/.cache/gdk-pixbuf-loaders.cache`
**LOCPATH**: `/snap/qownnotes/7643/usr/lib/locale`
**SNAP_COOKIE**: `zELa4_ttV4RzYoiPbEc5bkW4nJCAeM2K14FR2Vqq6wRa-D1KqQk4`
**QT_PLUGIN_PATH**: `/snap/qownnotes/7643/usr/lib/x86_64-linux-gnu/qt5/plugins`
**SHELL**: `/bin/bash`
**XDG_SESSION_CLASS**: `user`
**FONTCONFIG_FILE**: `/snap/qownnotes/7643/etc/fonts/fonts.conf`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**TEMPDIR**: `/tmp`
**XCURSOR_THEME**: `breeze_cursors`
**XDG_CURRENT_DESKTOP**: `KDE`
**XLOCALEDIR**: `/snap/qownnotes/7643/usr/share/X11/locale`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**BAMF_DESKTOP_FILE_HINT**: `/var/lib/snapd/desktop/applications/qownnotes_qownnotes.desktop`
**SNAP_REEXEC**: *empty*
**SHLVL**: `0`
**XDG_SEAT**: `seat0`
**LANGUAGE**: `en_US`
**GST_PLUGIN_SCANNER**: `/snap/qownnotes/7643/usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner`
**GDK_PIXBUF_MODULEDIR**: `/snap/qownnotes/7643/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders`
**GTK_RC_FILES**: `/etc/gtk/gtkrc:/home/thomas/.gtkrc:/home/thomas/.config/gtkrc`
**LC_TELEPHONE**: `de_DE.UTF-8`
**QT_QPA_PLATFORM**: `xcb`
**XDG_CACHE_HOME**: `/home/thomas/snap/qownnotes/common/.cache`
**LOGNAME**: `thomas`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**XDG_RUNTIME_DIR**: `/run/user/1000/snap.qownnotes`
**XAUTHORITY**: `/run/user/1000/.Xauthority`
**XDG_DATA_HOME**: `/home/thomas/snap/qownnotes/7643/.local/share`
**SNAP_CONTEXT**: `zELa4_ttV4RzYoiPbEc5bkW4nJCAeM2K14FR2Vqq6wRa-D1KqQk4`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**XDG_CONFIG_DIRS**: `/snap/qownnotes/7643/etc/xdg:/etc/xdg/xdg-plasma:/etc/xdg:/usr/share/kubuntu-default-settings/kf5-settings`
**PATH**: `/snap/qownnotes/7643/usr/sbin:/snap/qownnotes/7643/usr/bin:/snap/qownnotes/7643/sbin:/snap/qownnotes/7643/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`
**LC_IDENTIFICATION**: `de_DE.UTF-8`
**KDE_SESSION_UID**: `1000`
**KDE_SESSION_VERSION**: `5`
**SNAP_VERSION**: `20.10.11`
**GIO_MODULE_DIR**: `/home/thomas/snap/qownnotes/common/.cache/gio-modules`
**SNAP_LIBRARY_PATH**: `/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void`
**SESSION_MANAGER**: `local/T460:@/tmp/.ICE-unix/1171,unix/T460:/tmp/.ICE-unix/1171`
**XCURSOR_PATH**: `/snap/qownnotes/7643/data-dir/icons:/snap/qownnotes/7643/usr/share/icons`
**LC_TIME**: `de_DE.UTF-8`
</details>

**Comment by pbek** [comment]
This doesn't seem to work easily with Qt. Is this of help: https://archived.forum.manjaro.org/t/how-to-operate-xcompose-with-qt-applications/154847

**Comment by pbek** [comment]
If not you can try: https://www.google.com/search?hl=en&q=qt%20.XCompose

**Comment by pbek** [comment]
I see you are using the snap version of QOwnNotes. I also don't know if `.XCompose` work with snaps, you may also want to try the PPA or AppImage version of QOwnNotes.

**Comment by tomatic** [comment]
It works with Kate, which is a Qt app, so it doesn't look like Qt is the issue. But thanks for the pointers, will have to dive into the details of all of it. So let's assume this isn't an issue with QOwnNotes itself but rather "systemic".

**Comment by tomatic** [comment]
Just tried it with the version installed via apt and ~/.XCompose is respected. So it seems it's not a Qt issue but rather related to snaps.

**Comment by pbek** [comment]
Great, good to know. Thank you for the feedback!
