### ISSUE TITLE
CJK punctuation doesn't seperate words when selecting text with doule-click 

### ISSUE THREAD

**Issue by davuses** [pbek/QOwnNotes#1937]
CJK punctuations, like `、` `。` `《`, don't seperate words when selecting text with doule-click.

For example, double clicking text `ブロックの一つであり、統合された中国語・日本語・朝鮮語の文字における記号及び句読点（約物）が収録されている。` will select the whole sentence instead of words seperated by delimiter.

This won't happen when using punctuation in European language.

**Comment by pbek** [comment]
Thank you for reporting, that sounds like a thing the default `QPlainTextEdit` does. I don't know if there is a way around that.
