### ISSUE TITLE
Sort folders first then notes afterwards when using a combined list

### ISSUE THREAD

**Issue by OlavStornes** [pbek/QOwnNotes#1938]
When i'm using the combined list view (`settings -> panels -> "Instead of a note list use a note tree with all the subfolders"`) and sorts alphabetical, the folders gets sorted at the same logic as notes. 

#### Expected behaviour
Folders sorted and grouped, while notes are sorted underneath

#### Actual behaviour

![image](https://user-images.githubusercontent.com/25202371/98363614-8ca35c00-202f-11eb-97a1-7a96640b5937.png)

(By the way, keep up the good work! I love using QOwnNotes with nextcloud)

**Comment by pbek** [comment]
That's all "work in progress" (as the checkbox says) :) Please see https://github.com/pbek/QOwnNotes/issues/790

**Comment by pbek** [comment]
And thank you for your kind words!
