### ISSUE TITLE
After deselecting from multiple selection, last selected note is not the current node

### ISSUE THREAD

**Issue by fnkabit** [pbek/QOwnNotes#1939]
#### Steps to reproduce

1. Create two notes inside the same notes sub-folder 
2. Select both notes (CTRL + click in Note list panel)
3. Deselect one note (CTRL + click in Note list panel on note that you want to deselect)

#### Expected behaviour

When one note remains selected, that note should be the currently displayed note in the text edit and preview panels.

#### Current behaviour

The last CTRL+clicked note is the currently displayed note in the text edit and preview panels, although it is not the selected note.

**Comment by pbek** [comment]
Confirmed, thank you for the fix! (github closed the issue because you used the word "fixed" in your PR 😁 )

**Comment by pbek** [comment]
## 20.11.3
- fixed a bug where after deselecting notes from a multiple selection, the last selected
  note was not the current node (for [#1939](https://github.com/pbek/QOwnNotes/issues/1939), thank you @fnkabit)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by fnkabit** [comment]
> There now is a new release, could you please test it and report if it works for you?

Tested on 20.11.3. I can confirm that it works. Thank you !

**Comment by fnkabit** [comment]
> Confirmed, thank you for the fix! (github closed the issue because you used the word "fixed" in your PR  )

Wow. GitHub is smart.

**Comment by pbek** [comment]
> Tested on 20.11.3. I can confirm that it works. Thank you !

Great, thank you for testing!

> Wow. GitHub is smart.

I would prefer it not to be 😅
