### ISSUE TITLE
Overwriting shortcuts

### ISSUE THREAD

**Issue by guija** [pbek/QOwnNotes#194]
Atm there is no option to overwrite the default shortcuts correct? I'am using the i3 window manager for linux and many shortcuts are interferring, like `Alt+Shift+E`. Therefore it would be nice to have this option either in the settings (GUI) or in some configuration file.

**Comment by pbek** [comment]
Thank you for your suggestion. Yes, that would be nice (and a lot of work to implement).

**Comment by pbek** [comment]
I'm currently working to that feature request.

**Comment by pbek** [comment]
## 16.08.3
- there now is a new **Shortcuts** tab in the settings where you can 
  assign custom shortcuts for menu items of the main window
    - you can also search for shortcuts

**Comment by pbek** [comment]
This is also something for you, @Maboroshy. ;)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by guija** [comment]
I've testet it, haven't found any issues yet, works flawlessly! It's also nice that you can filter the shortcuts. I will close the issue.

**Comment by pbek** [comment]
Great you like it, took me some days... ;)

**Comment by guija** [comment]
I assumed that it has been a lot of work. But I think it's a major
improvement due to configurability for different environments.

Great work!

**Comment by pbek** [comment]
Thank you, that's true. ;)

**Comment by Maboroshy** [comment]
I've tested new version and it works great! Very useful UI to set shortcuts. I like the way the fallback to defaults is made.

I think it's quite a leap for the app's usability.

**Comment by pbek** [comment]
Thank you, @Maboroshy!
