### ISSUE TITLE
'Jump to' actions availability not updated

### ISSUE THREAD

**Issue by fnkabit** [pbek/QOwnNotes#1941]
#### Steps to reproduce

1. Hide some panel that is available in the 'Jump to' menu (`Window > Jump to`)
2. Jump to the panel that was just hidden (from menu action or hotkey)

#### Expected behaviour

The jump to action should be disabled for panels that are hidden.

#### Current behaviour

The jump to action is not disabled for panels that are hidden.

**Comment by pbek** [comment]
## 20.11.4
- the different *Jump to* actions in the *Windows menu* are now disabled if the panels
  they jump to are disabled (for [#1941](https://github.com/pbek/QOwnNotes/issues/1941), thank you @fnkabit)

There now is a new release, could you please test it and report if it works for you?

**Comment by fnkabit** [comment]
@pbek I can confirm it works fine on 20.11.4

**Comment by pbek** [comment]
Great, thank you for testing!
