### ISSUE TITLE
Snap does not launch on Ubuntu 20.10 Wayland

### ISSUE THREAD

**Issue by mjdubbs** [pbek/QOwnNotes#1943]
#### Expected behaviour
QOwnNotes launches

#### Actual behaviour
QOwnNotes does not launch with the following output:

```
Warning: QXcbConnection: Could not connect to display :0 ((null):0, (null))
Critical: Could not connect to any X display. ((null):0, (null))
```
AppImage works fine and Snap works fine on X

#### Steps to reproduce
Launch QOwnNotes snap on Ubuntu 20.10 Wayland, GDM 3.38.1

#### Output from the debug section in the settings dialog
N/A

#### Relevant log output in the Log panel
N/A

Please let me know how I can help figure out/test this :+1:

**Comment by pbek** [comment]
Thank you for reporting.
What platform are you using it?
Can you please try to get the output from the debug settings by using the `--dump-settings` parameter (see https://www.qownnotes.org/getting-started/cli-parameters.html).

I wonder if that is a limitation from snaps themselves.
Does the QOwnNotes snap from the edge channel work?

**Comment by pbek** [comment]
Or maybe you need to allow something so the snap can access wayland...

**Comment by mjdubbs** [comment]
by platform you mean OS? Ubuntu 20.10 Wayland, Gnome 3.38.1

I tried all the CLI options, but the only one that shows any different output is ```--clear-settings```. Which just shows:
```
Warning: Your settings are now cleared! ((null):0, (null))
Warning: QXcbConnection: Could not connect to display :0 ((null):0, (null))
Critical: Could not connect to any X display. ((null):0, (null))
```
It is a fresh install of QOwnNotes, so the settings should have been default anyway.

Permissions sounds like a good place to look. I see now an "Access to OpenGL stack" permission that I don't remember seeing before. But it is enabled by default.

edge channel has the same behavior

I tried a couple other Qt snaps on Wayland and you are right, they have similar issues.
From Vidcutter and Keepassxc
```
qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.
```

It used to work fine on 20.04, so I will do some searching to see what might have changed

**Comment by pbek** [comment]
Thank you for testing.
https://snapcraft.io/docs/desktop-interfaces says there is a `wayland` plug, but I'm not sure what will break if I start to add that.

**Comment by mjdubbs** [comment]
Just found the upstream bug report
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1897224
looks like they will revert soon

**Comment by pbek** [comment]
Ok, great. So let's wait.

**Comment by mjdubbs** [comment]
It seems like Canonical is pushing the updates for mutter and libmutter 3.38.1-2ubuntu1 to Ubuntu 20.10 which should allow snaps to launch on Wayland now, including QOwnNotes.

I just tested the update and it is working :+1:

**Comment by pbek** [comment]
Awesome, thank you for testing!
