### ISSUE TITLE
[I] Invalid query, please check the syntax. API specifications are here

### ISSUE THREAD

**Issue by 9Mad-Max5** [pbek/QOwnNotes#1944]
#### Expected behaviour

No popup warning when starting or changing a setting.
Nextcloud is with Version 13 rather old one, but I'm stuck to due to the qnap hardware.

#### Actual behaviour

Pop up windows appears about a missing connection on every start.
If I have a close look in the settings page everything is quite fine.
I guess it comes with this Qownnotes output:

[22:29:30] [warning] "QNetworkReply error 203 from url https://mydomain.net/nextcloud/ocs/v2.php/apps/files_sharing/api/v1/shares: " "Error transferring https://mydomain.net/nextcloud/ocs/v2.php/apps/files_sharing/api/v1/shares - server replied: Not Found"

#### Steps to reproduce

I guess install Nectcloud 13.X with the newest apps and the newest qownnotes api and qownnotes Desktop app.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[13:20:50] [scripting] loading script file: C:/Users/max/AppData/Roaming/PBE/QOwnNotes/scripts/external-note-open/external-note-open.qml
[13:20:54] [warning] "QNetworkReply error 203 from url https://xxx.myqnapcloud.com:8081/nextcloud/ocs/v2.php/apps/files_sharing/api/v1/shares: " "Error transferring https://xxx.myqnapcloud.com:8081/nextcloud/ocs/v2.php/apps/files_sharing/api/v1/shares - server replied: Not Found"
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mi Nov 11 13:21:29 2020`
**Version**: `20.11.4`
**Build date**: `Nov 10 2020`
**Build number**: `783`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\max\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Program Files\QOwnNotes`, `\QOwnNotes.exe`, `--after-update`, `C:\Users\max\AppData\Local\Temp\QOwnNotes-LMypnU-updater.bat`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1366x768`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `334`
**Calendar items**: `109`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: `https://xxx.myqnapcloud.com:8081/nextcloud`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `13.0.12.1`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\max\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Standard`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `C:\Users\max\Nextcloud\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\max\Nextcloud\Notes\notes.sqlite`

### Cloud connection `Standard`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://xxx.myqnapcloud.com:8081/nextcloud`
**username**: `HMaximilian`

### Script `External note open`

**id**: `1`
**path**: `C:\Users\max\AppData\Roaming\PBE\QOwnNotes\scripts\external-note-open\external-note-open.qml`
**variablesJson**: 
```
{
    "executablePath": "C:\\Program Files\\Notepad++\\notepad++.exe"
}
```
**identifier**: `external-note-open`
**version**: `1.0.0`
**minAppVersion**: `18.05.4`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrainingSpaces** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `C:/Program Files/Notepad++`
**FileDialog/LastPath-ScriptSettingsFile-external-note-open-executablePath** (QString): `C:/Program Files/Notepad++`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-11-11T13:02:35.186`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Arbeit/MS3, Arbeit`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `true`
**MessageBoxOverride/update-and-restart** (int): `16384`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): `Note 2020-11-07T22.36.14`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `NAS`
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `199`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `false`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (int): `15`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `C:/Users/max/Nextcloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Privat`
**ownCloud/todoCalendarEnabledList** (QStringList): `Privat`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://xxx.myqnapcloud.com:8081/nextcloud/remote.php/dav/calendars/HMaximilian/eec72004-9572-4aa4-ba41-c7a2f44b4d50/`
**ownCloud/todoCalendarUrlList** (QStringList): `https://xxx.myqnapcloud.com:8081/nextcloud/remote.php/dav/calendars/HMaximilian/eec72004-9572-4aa4-ba41-c7a2f44b4d50/`
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unbekannter Fehler`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `13.0.12.1`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2020-11-04T12.29.21, Note 2020-10-20T11.21.18, Note 2020-10-19T18.34.43, Note 2020-10-19T15.25.56, Note 2020-10-08T10.18.16, Note 2020-10-07T09.34.51, trakt, bnc, Note 2020-09-21T17.10.19, Note 2020-09-15T11.11.23, Note 2020-09-04T11.43.43, Note 2020-08-27T13.45.26, Note 2020-08-25T13.47.01, Note 2020-08-04T14.53.19, Note 2020-07-08T13.07.50, Note 2020-07-07T17.23.37, Note 2020-06-29T15.38.27, Note 2020-06-25T14.34.09, Note 2020-06-25T08.37.50, Note 2020-06-22T15.58.04, Note 2020-06-22T14.53.39, Note 2020-05-18T21.14.03, Note 2020-05-11T15.46.06, Note 2020-05-04T16.09.58, Note 2020-04-29T12.29.01, Note 2020-04-22T12.38.33, Note 2020-04-03T16.13.18, Note 2020-04-03T16.12.40, Note 2020-03-29T16.08.47, Note 2020-03-27T14.40.53, Note 2020-03-20T16.03.27, Note 2020-03-19T15.26.38, Note 2020-03-18T10.34.05, Note 2020-03-15T14.15.19, Note 2020-03-10T14.59.50, Note 2020-03-10T12.00.37, Note 2020-03-09T16.39.34, Note 2020-02-28T11.21.09, Note 2020-02-27T17.18.15, Note 2020-02-19T09.33.01`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**skipVersion** (QString): `20.2.4`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Hauptsymbolleiste`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `Formatierungs-Werkzeugleiste`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `Einfügen-Werkzeugleiste`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `Verschlüsselung-Werkzeugleiste`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `Fenster-Werkzeugleiste`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `Beenden - Symbolleiste`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Vollständig`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\max\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `W10max`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DcuTermAgent_Path**: `C:\Program Files (x86)\DCUTermAgent`
**destination**: `"C:\Program Files\QOwnNotes"`
**DokanLibrary1**: `C:\Program Files\Dokan\Dokan Library-1.2.0\`
**DokanLibrary1_LibraryPath_x64**: `C:\Program Files\Dokan\Dokan Library-1.2.0\lib\`
**DokanLibrary1_LibraryPath_x86**: `C:\Program Files\Dokan\Dokan Library-1.2.0\x86\lib\`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**GENICAM_CACHE_V2_4_ARCH**: `C:\Users\max\AppData\Roaming\OPTOMOTIVE Vision\GenICam_v2_4\cache`
**GENICAM_LOG_CONFIG_V2_4_ARCH**: `C:\Program Files\OptoMotive\OptoStreamSDK\GenICam_v2_4\log\config\DefaultLogging.properties`
**GENICAM_ROOT_V2_4_ARCH**: `C:\Program Files\OptoMotive\OptoStreamSDK\GenICam_v2_4`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\max`
**JD2_HOME**: `C:\Users\max\AppData\Local\JDownloader 2.0`
**LOCALAPPDATA**: `C:\Users\max\AppData\Local`
**LOGONSERVER**: `\\W10max`
**NUMBER_OF_PROCESSORS**: `4`
**OneDrive**: `C:\Users\max\OneDrive`
**OneDriveConsumer**: `C:\Users\max\OneDrive`
**OPSTR_GEV_COMMON_PATH**: `C:\Program Files\OptoMotive\OptoStreamSDK\include\opstr_c`
**OPTOSTREAM_SDK_CUSTOM_PATH**: `C:\Users\max\AppData\Roaming\OPTOMOTIVE Vision\custom`
**OPTOSTREAM_SDK_PATH**: `C:\Program Files\OptoMotive\OptoStreamSDK`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\OptoMotive\OptoStreamSDK\bin;C:\Program Files\OptoMotive\OptoStreamSDK\GenICam_v2_4\bin\Windows;C:\Program Files\OptoMotive\OptoStreamSDK\GenICam_v2_4\bin\Windows\GenApi\Generic;C:\Program Files\Git\cmd;C:\Primos\;C:\Users\max\AppData\Local\Microsoft\WindowsApps;C:\Users\max\AppData\Local\GitHubDesktop\bin;C:\Users\max\AppData\Local\Programs\Microsoft VS Code\bin`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 142 Stepping 9, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `8e09`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PROMPT**: `$P$G`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PSVKIT**: `C:\Primos\`
**PSV_OS**: `NT`
**PSV_SHM_INFO_FILE**: `C:\Primos\shm_info.dat`
**PSV_SILENT**: `1`
**PSV_SYS_HAS_CMDX**: `1`
**PUBLIC**: `C:\Users\Public`
**qownnotesCommand**: `"C:\Program Files\QOwnNotes"\QOwnNotes.exe --after-update C:\Users\max\AppData\Local\Temp\QOwnNotes-LMypnU-updater.bat `
**S3_Path64**: `C:\Dewesoft\Bin64\X3\Addons64\S3\ncfapi\bin`
**SESSIONNAME**: `Console`
**SOFT_TCMS_PATH**: `C:\Program Files (x86)\Bombardier Transportation\SoftTCMS Environment\`
**source**: `C:\Users\max\AppData\Local\Temp\QOwnNotes-LMypnU.zip`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\max\AppData\Local\Temp`
**TMP**: `C:\Users\max\AppData\Local\Temp`
**unzipCommand**: `C:\Users\max\AppData\Local\Temp\QOwnNotes-LMypnU-unzip.exe -o C:\Users\max\AppData\Local\Temp\QOwnNotes-LMypnU.zip -d "C:\Program Files\QOwnNotes"`
**unzipExecutable**: `C:\Users\max\AppData\Local\Temp\QOwnNotes-LMypnU-unzip.exe`
**USERDOMAIN**: `W10max`
**USERDOMAIN_ROAMINGPROFILE**: `W10max`
**USERNAME**: `max`
**USERPROFILE**: `C:\Users\max`
**VBOX_MSI_INSTALL_PATH**: `C:\Program Files\Oracle\VirtualBox\`
**windir**: `C:\WINDOWS`
**__COMPAT_LAYER**: `DetectorsMessageBoxErrors`
</details>

**Comment by pbek** [comment]
NC 13, that's really old. I wonder if NC 13 already has the sharing API.
So does the url https://mydomain.net/nextcloud/ocs/v2.php/apps/files_sharing/api/v1/shares exist on your server? Does your NC server have the sharing api?

Do you also get that warning dialog if you turn off NC support in the QOwnNotes settings?

**Comment by 9Mad-Max5** [comment]
No the pages gives back this 

Nextcloud
Zugriff verboten
CSRF check failed

Actually I didn't figured out how to solve it besides disabling the support and just using the folders...
Mabe because the really old file sharing app with version 1.5 don't have this api..
But in the past the Qownnotes Desktop app worked fine with those settings. Is there sth like a historical mode?

**Comment by pbek** [comment]
The share functionality is in QOwnNotes for ages...
In theory there is file sharing in NC 13, https://docs.nextcloud.com/server/13.0.0/admin_manual/configuration_files/file_sharing_configuration.html. Maybe you need to create some redirects on your server.

**Comment by 9Mad-Max5** [comment]
So the basic file sharing is enabled and installed on my Nextcloud since forever since version 9.
But it seams to me there where some big changes in the past to the fies_sharing app itself, which ass well influenced qownnotes.

**Comment by pbek** [comment]
14 month ago the sharing url was switched to `/ocs/v2.php/apps/files_sharing/api/v1/shares` (from `/ocs/v1.php/apps/files_sharing/api/v1/shares`). Does the old url work on your server?

**Comment by 9Mad-Max5** [comment]
As this:
/nextcloud/ocs/v2.php/apps/files_sharing/api/v1/
Returns this:

**Comment by pbek** [comment]
You could try creating a redirect from the new url to the old url on your server.

**Comment by 9Mad-Max5** [comment]
uff that seems to be some heavy lifting for a small benefit.
Is it maybe possible to have both routes active or to determine which is used in the Nextcloud version?

**Comment by pbek** [comment]
> uff that seems to be some heavy lifting for a small benefit.

that was supposed to be the easy way, since it's only one line more apache/nginx config. 😆 

>  Is it maybe possible to have both routes active or to determine which is used in the Nextcloud version?

Not easily without being very flakey.

**Comment by 9Mad-Max5** [comment]
Yes but I not have a reverse proxy running on this device and im not sure about the apache thing where this redirect could be placed..

**Comment by pbek** [comment]
In your Nextcloud root folder there should be a `.htaccess` with plenty of rewrite rules (if qnap is using apache for nextcloud).

**Comment by 9Mad-Max5** [comment]
Yes i found it and i see where youre going but i didn´t figured out yet the naming for a new rule

**Comment by pbek** [comment]
Maybe it's even enough if you copy your `ocs/v1.php` to `ocs/v2.php`.

**Comment by 9Mad-Max5** [comment]
ok the v2.php file already exists.
But ir is just containing this

`require_once __DIR__ . '/v1.php';
`
Im not really into php files so im not sure about what this line says...
But resseting the name of the v2 file and copying the v1 file int this place didn't helped..

**Comment by pbek** [comment]
> require_once __DIR__ . '/v1.php';

funny, that should do the same. I wonder why you can't access v2.php

so it seems the APIs are not compatible... 

doesn't NC 13 already have the web updater so you can update your NC instance?

there also is the web installer, one simple php file to install the most current NC: https://github.com/nextcloud/web-installer

**Comment by pbek** [comment]
but NC 20 does need PHP 7.2 (or even 7.3) at minimum...

**Comment by 9Mad-Max5** [comment]
Yeah this issue is already above nc 13.
Because it is the last Version which support php 5.6 and with the older version of the QNAP NAS your stuck to this infrastructur.
And as the NAS is to weak for some docker containers I'm stuck to nc 13..

**Comment by pbek** [comment]
Something tells me you need a new NAS, a small Raspberry Pi or a VPS in the internet. 😁

**Comment by 9Mad-Max5** [comment]
Yeah I know 😂.
I already have a new one here but the move from the old to the new takes some major time.
As well it took me some time to get that bloody traefik working with nextcloud in a container.
But since that day I accomplished that task I guess the only way is to disable this connection in the qownnotes app....

**Comment by pbek** [comment]
> get that bloody traefik working with nextcloud in a container.

what's your issue? traefik runs great for my containers (with let's encrypt)

>  But since that day I accomplished that task I guess the only way is to disable this connection in the qownnotes app....

would be the easiest until you get your new nas running

**Comment by 9Mad-Max5** [comment]
Yeah now it runs like a charm an updating the docker with docker-compose up is really neat. 
I even made it to run redis for the nextcloud instance but I didn't found a lot of help out there to get it up and running and/or i didn't understand it...
But well, now it's running and the merge plan gets more rescent.

**Comment by pbek** [comment]
> Yeah now it runs like a charm an updating the docker with docker-compose up is really neat.

I use watchtower to update most of my containers. 😁 

> I even made it to run redis for the nextcloud instance but I didn't found a lot of help out there to get it up and running and/or i didn't understand it...

https://docs.nextcloud.com/server/20/admin_manual/configuration_server/caching_configuration.html#id2 ?

**Comment by pbek** [comment]
I'll close this now.
