### ISSUE TITLE
[Feature request] Diary navigation pane

### ISSUE THREAD

**Issue by pablomalo** [pbek/QOwnNotes#1945]
I'm transitioning from Zim Wiki. I like the ability of QOwnNotes to manage multiple notebooks from the same Window, and I like writing in Markdown.

One feature I do like about Zim, however, is its "Journal" plugin, https://zim-wiki.org/manual/Plugins/Journal.html. It makes it easy to use Zim as a diary.

Diary pages are simple notes that are organized in a folder hierarchy like so: YYYY folder > MM folder > DD note. For instance, a note titled "12" inside a folder titled "11" inside a folder titled "2020" forms the entry for Nov. 12, 2020.

The neat thing is you can then navigate the diary using a calendar pane.

<a href="url"><img src="https://user-images.githubusercontent.com/25877142/98959116-405e8d00-2503-11eb-9bbf-17b46ebb3a66.png" width="600" ></a>

Are there any such plans for QOwnNotes? Thanks.

**Comment by pbek** [comment]
You might want to take a look at the script `Journal entry` in the script repository. It features a calendar.

**Comment by pablomalo** [comment]
Sorry to have missed that. Thank you.

**Comment by gerroon** [comment]
Hi

I do not see a Journal Entry script in the script browser. Is it removed.

**Comment by pbek** [comment]
![image](https://user-images.githubusercontent.com/1798101/104238050-4ddbb900-5459-11eb-9861-b4f167f54693.png)

**Comment by gerroon** [comment]
@pbek thanks. I restarted now I see it.

**Comment by gerroon** [comment]
Sorry to bug about this again but I do not see a calender entry for browsing the journals. Also creating journal for a certain date functionality does not seem to do anything. I do not get a date entry. However creating journal entry for today and tomorrow works.

Linux 

QOwnNotes - version 21.1.2 - GitHub Actions - build 803
Plain-text file markdown note taking with Nextcloud/ownCloud integration for GNU/Linux, macOS® and Windows® (it is written in C++/Qt®), that works together with the notes application of Nextcloud and ownCloud. 
Built on Jan 4 2021 with Qt 5.15.2.

**Comment by pbek** [comment]
Can you please open an issue at https://github.com/qownnotes/scripts/issues and follow the instructions. 😁
