### ISSUE TITLE
Qownnotes blocked again by Windows defender

### ISSUE THREAD

**Issue by animeshb** [pbek/QOwnNotes#1948]
Couple of days back I noticed this problem and let Windows defender take its action. This did not affect QOwnNotes.

Today morning I updated to the latest version and again the same issue popped up. So I told it to remove the threat. Guess what? It removed the exe itself. :-(

I have looked at #1867 and #1887.

I downloaded the zip from /releases page and this time it deleted the exe before I could even see it.

So how to avoid this? Downgrading to an older release is fine.

Just reporting!

Thank you 

#### Expected behaviour
Run as usual

#### Actual behaviour
Get blocked by Windows defender. Exe gets deleted.

#### Steps to reproduce
Update to 20.11.15

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Thank you for reporting. It's usually doesn't take long for Microsoft to improve their detection.

**Comment by pbek** [comment]
My Windows 10 Home had no issues with 20.11.5.

**Comment by pbek** [comment]
There now is a new release building, could you please test it and report if it works for you?

**Comment by animeshb** [comment]
I had run the same release from the downloaded zip and then upgraded to 20.11.16. No issues.

Closing.

**Comment by pbek** [comment]
Thank you for testing.

> Edit: changed Closing to Can be closed, since I can't close the issue.

Strange, you opened the issue, you should be able to also close it...
