### ISSUE TITLE
Search several words 

### ISSUE THREAD

**Issue by capcionista** [pbek/QOwnNotes#195]
Thank you for your amazing programme! As far as I can see, it's only possible to search the content with words that follow each other. When I type word1 word2 in the search field, only notes containing word1 word2 in this order will show up, but not word1 word3 word2.

Is there any way to change this behaviour. I would be very grateful!

**Comment by pbek** [comment]
Thank you for your kind words and your suggestion. Currently the there is no search index, because there is no database to store the notes permanently, so such searches will be slow... I will take a look how slow this would get...

**Comment by pbek** [comment]
@dh-connect had similar in mind with #138

**Comment by capcionista** [comment]
Thanks. I think the search is really the one thing where qownnotes falls short compared to other note taking applications. Are you planning to add database and search index at some point or rather not?

**Comment by pbek** [comment]
I fear that will not be possible or else QOwnNotes can't be a notepad, that stores all notes in plain text files, like advertised. Plus for a really huge amount of data it would be wise to use a database like mysql and a search backend like Apache Solr. Who would want to install all that on a Desktop computer?

Currently all note files are read into an in-memory Sqlite database for further processing...
But they all have to be re-read if for example a note gets deleted outside of QOwnNotes...

**Comment by capcionista** [comment]
Do you know how Resophnotes or nvpy handle this? They also offer storage in plain text files (although Resophnotes seems buggy to me in this point)

**Comment by pbek** [comment]
No, I don't know. You can do almost everything, even if the performance is bad, as long as there are only "a few" notes..

**Comment by capcionista** [comment]
https://github.com/cpbotha/nvpy nvpy search works well for about 3500 notes in my case.

**Comment by pbek** [comment]
Searching in QOwnNotes works well too (because it's done in-memory), but reading several 1000 large text files from a spinning disk to RAM might take a few seconds...

**Comment by capcionista** [comment]
I see.

**Comment by pbek** [comment]
in version 16.06.2
- you now can **search for multiple words** in notes
    - by default notes that contain every single word will be found, `word1 
      word2` will find all notes that are containing `word1` and `word2`
    - you can search for longer texts by using quotes, `"this word1" word2` 
      will find all notes that are containing `this word1` and `word2`

**Comment by pbek** [comment]
v16.06.2 is now released, can you please test it and report if the new features work for you

**Comment by capcionista** [comment]
I will test it

**Comment by capcionista** [comment]
It works! And for 3500 notes the still is still instaneous, much faster than e.g. nvAtom. Thank you very much, this was a crucial feature for me and I believe for many future users as well.

**Comment by capcionista** [comment]
+1

**Comment by pbek** [comment]
thank you, @capcionista 

highlighting works for one string only, I haven't found a feasible way to do more complex searches; but in theory there must be a way to do it with regular expressions...

**Comment by pbek** [comment]
from the changelog of v16.06.3
- the **highlighting** for text found by the **search for multiple words** 
  feature from version 16.06.2 now also works for those patterns

could you please test that when the new release is out?

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by dh-connect** [comment]
hey works great

**Comment by pbek** [comment]
thanks
