### ISSUE TITLE
[Feature]  Scripting: API for Inserting text at specified positions 

### ISSUE THREAD

**Issue by v3ss0n** [pbek/QOwnNotes#1950]
I am not sure we have this alrready but looking in scripting docs I haven't found it.
I am developing a script that insert or append Text at beginning or at the end of  existing markdown notes  .
I can't find an API to do that.
Since Vim Mode can move cursor to end of note / beginning of note using vim commands/shortcuts , i think the API is already there. Any pointers if not there yet , exposing those API would be cool.

**Comment by pbek** [comment]
> I am developing a script that insert or append Text at beginning or at the end of existing markdown notes .

What do you want to achieve by doing that? Writing a frontmatter? And when do you want to trigger that appending of text.

**Comment by v3ss0n** [comment]
Currently i am doing this : 

```javascript

    function websocketRawDataHook(requestType, pageUrl, pageTitle, rawData,
                                  screenshotDataUrl) {
        // we only want to handle selection requests, page requests are ignored
        if (requestType != "selection") {
            return false;
        }
        let result =`\n- ${rawData} : <${pageUrl}>\n`
        // write selected text from the page to the current note
        script.noteTextEditWrite(result)

        return true;
    }
```
Currently this appends at cursor position and if i do not place cursor well , it will mess up .
So i want to add text at the end of Document
append the link  at the end of the note:
```javascript
script.noteTextEditWrite(` ${rawData} : [refid-12312]()`)
script.noteTextEditAppendEOF(`[refid-12312](${pageUrl})`)    
```
Does it make sense?

**Comment by v3ss0n** [comment]
proposing this api:
```
script.noteTextEditWriteAt(string: text,int: position)
```
Where Position 0 = BOF , -1 = EOF

**Comment by pbek** [comment]
Sounds reasonable, that or something to set the cursor position, then it could also be used to just jump to a position or use it with insertHtmlAsMarkdownIntoCurrentNote.

**Comment by v3ss0n** [comment]
Thanks alot!
> That or something to set the cursor position
That also would work , but not sure user wants cursor position to be changed.
`insertHtmlAsMarkdownIntoCurrentNote`
 I am not clear about it , i had checked the API and it dosen't mention anything  about moving cursor. Do you mean i should replace `noteTextEditWrite` and use HTML instead?

**Comment by v3ss0n** [comment]
I see now , just tested mainWindow.insertHtmlAsMarkdownIntoCurrentNote , 
``` 
let result =`<p><br> <li> ${rawData} : <a href=${pageUrl}> </a> </li> </p>` 
mainWindow.insertHtmlAsMarkdownIntoCurrentNote(result)
```
It doesn't convert `<br>` into  line breaks , may be i am doing it wrong. 
So  what you mean changing cursor position make it able to use with any other text insertion APIs .
That could work too , I just worry that user won't want the cursor position to be changed.
What do you think API like this?
```javascript
mainWindow.goToLine(lineNumber) \\ 0 = BOF , -1 = EOF , Positive Number = Line Number
mainWindow.goTo(lineNumber,colNumber) \\ colNumber =0  (Start of Line) colNumber =-1 (end of line)
```

**Comment by pbek** [comment]
For now I will provide new scripting commands `script.noteTextEditSetCursorPosition()` and `script.noteTextEditCursorPosition()` to set the text cursor in the note text edit to a certain position and to get the current position.

> It doesn't convert <br> into line breaks , may be i am doing it wrong.

The method was implemented to convert selected html from random webpages into a somewhat usable markdown text.

This is what it does:
https://github.com/pbek/QOwnNotes/blob/648b121a794cacb8ed52f60962ee98a3776265fc/src/utils/misc.cpp#L611-L727

**Comment by pbek** [comment]
## 20.11.7
- there now are new scripting commands `script.noteTextEditSetCursorPosition()`
  and `script.noteTextEditCursorPosition()` to set the text cursor in the note
  text edit to a certain position and to get the current position
  (for [#1950](https://github.com/pbek/QOwnNotes/issues/1950))
    - for more information please take a look at the
      [scripting documentation](https://www.qownnotes.org/scripting/methods-and-objects.html#set-the-text-cursor-in-the-note-text-edit-to-a-certain-position)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by v3ss0n** [comment]
Thank you soo much , that is fastest feature requested developed , and released by main dev in history of github i think (atleast for me)! you are awesome.

**Comment by pbek** [comment]
Haha, thank you. 😁

**Comment by v3ss0n** [comment]
I am testing and is there some changes in Javascript/ECMA  version? 
let and string templates no longer works (it was working fine before.

```javascript
        var selected =`\n- ${rawData} : [REF:${uid}][${uid}]`;

```

```
03:21:48] [warning] script errors: (file:///home/nozander/Lab/scripts/companion-select-text-insert/selected-text.qml:17:23: Expected token `numeric literal' var selected =`\n- ${rawData} : [REF:${uid}][${uid}]`; ^)
[03:21:48] [status]
```

**Comment by v3ss0n** [comment]
I got it working now it seems to be problem of different packages
- pacakges from AUR repository do not have ECMA6 features , i think it compiles with ancient QT version.
- AppImage package supports ECMA6 features.

**Comment by v3ss0n** [comment]
Working pefrectly , below is the script that uses all features of the new api:

```
import QtQml 2.0
import QOwnNotesTypes 1.0

Script {
    /**
     * Writes the selected text on the webpage that was sent to QOwnNotes from
     * the browser extension into the current note
     */
    function websocketRawDataHook(requestType, pageUrl, pageTitle, rawData,
                                  screenshotDataUrl) {
        // we only want to handle selection requests, page requests are ignored
        if (requestType != "selection") {
            return false;
        };

        
        let uid = Date.now();
        let selected =`\n- ${rawData} : [REF][${uid}]`;
        let url = `\n[${uid}]: ${pageUrl}`;
        let posBefore = script.noteTextEditCursorPosition();

        // Insert Selected text after current line
        script.noteTextEditSelectCurrentLine();
        script.noteTextEditSetSelection(
            script.noteTextEditSelectionEnd() ,
            script.noteTextEditSelectionEnd() )
        script.noteTextEditWrite(selected);

        // Go to end of file and append web URL

        script.noteTextEditSetCursorPosition(-1);   
        script.noteTextEditWrite(url);

        // Go back to current editing position
        script.noteTextEditSetCursorPosition(posBefore);





        return true;
    }
}
```


results:

![image](https://user-images.githubusercontent.com/419606/99456815-5d0e2100-2958-11eb-89d1-62af62b5f67a.png)

going to share the script soon.

PS: Found a  little bug regarding  ctrl + clicking ref links  , reported.

**Comment by pbek** [comment]
Great it worked! 😁
