### ISSUE TITLE
QOwnNotes.exe PUA:Win32/Pearfoos.A!ml

### ISSUE THREAD

**Issue by bolausson** [pbek/QOwnNotes#1951]
Hej,

After the update today (through the GUI), Windows keeps to quarantine the QOwnNotes.exe file classifying it as "Potentially Unwanted Software" (PUA:Win32/Pearfoos.A!ml)

To reproduce, simply download the current release v20.11.6 and try to run the QOwnNotes.exe executable.
https://github.com/pbek/QOwnNotes/releases/download/v20.11.6/QOwnNotes.zip
![QOwnNotes-Win32-Pearfoos_2](https://user-images.githubusercontent.com/10600678/99245541-068fce00-2804-11eb-9e8e-9e0661a12935.png)

Is anyone else experiencing this?

![QOwnNotes-Win32-Pearfoos](https://user-images.githubusercontent.com/10600678/99244568-8ae15180-2802-11eb-849c-cb1322eb9a4c.png)

Greetings
Bjoern

**Comment by pbek** [comment]
Always false positive so far, see #1948 (or similar like #1887).

Does https://www.virustotal.com find anything?

There's not much that can be done about "bad heuristics" in Windows Defender, last time MS patched that problem away within days...

**Comment by bolausson** [comment]
Thanks for the quick reply... seems to be again a false positive *sigh*

![screencapture-virustotal-gui-file-640ff0008ddcc600870c2be47780cf666f436664302a13027ab15db0222d60e8-detection-2020-11-16-12_24_34](https://user-images.githubusercontent.com/10600678/99247156-d695fa00-2806-11eb-8856-d1d8b08570a9.png)

Cheers,
Bjoern
