### ISSUE TITLE
Can't make the build from src 

### ISSUE THREAD

**Issue by bemote1970** [pbek/QOwnNotes#1952]
### Expected behaviour 

Build from src without errors

#### Actual behaviour

After build it in Qt Creator

![Annotation 2020-11-17 171400](https://user-images.githubusercontent.com/74606790/99400716-594ab200-28f8-11eb-8fcf-18b32b413e0d.png)

 I get 4 errors:

> D:\QOwnNotes-20.11.6\QOwnNotes-20.11.6\src\utils\schema.h:17: error: libraries/qmarkdowntextedit/markdownhighlighter.h: No such file or directory
In file included from ../src/main.cpp:4:
../src/utils/schema.h:17:10: fatal error: libraries/qmarkdowntextedit/markdownhighlighter.h: No such file or directory
 #include <libraries/qmarkdowntextedit/markdownhighlighter.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

> :-1: error: No rule to make target 'libraries/md4c/md4c/md4c.c', needed by 'debug/md4c.o'.  Stop.

> D:\QOwnNotes-20.11.6\QOwnNotes-20.11.6\src\helpers\codetohtmlconverter.cpp:6: error: libraries/qmarkdowntextedit/qownlanguagedata.h: No such file or directory
../src/helpers/codetohtmlconverter.cpp:6:10: fatal error: libraries/qmarkdowntextedit/qownlanguagedata.h: No such file or directory
 #include "libraries/qmarkdowntextedit/qownlanguagedata.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

> D:\QOwnNotes-20.11.6\QOwnNotes-20.11.6\src\mainwindow.h:18: error: libraries/qhotkey/QHotkey/qhotkey.h: No such file or directory
In file included from ../src/mainwindow.cpp:15:
../src/mainwindow.h:18:10: fatal error: libraries/qhotkey/QHotkey/qhotkey.h: No such file or directory
 #include <libraries/qhotkey/QHotkey/qhotkey.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

![Annotation 2020-11-17 165809](https://user-images.githubusercontent.com/74606790/99400661-4637e200-28f8-11eb-952d-339b87343b70.png)

#### Steps to reproduce

Trying build QOwnNotes 20.11.6 on Qt Creator 4.13.2, Qt 5.15.1, Windows 10 x64.

**Comment by pbek** [comment]
Did you checkout the git submodules?

**Comment by bemote1970** [comment]
No, I used zip archive from Releases.

I checkout git and submodules (600mb) now and try build. It passed, thanks.

![image](https://user-images.githubusercontent.com/74606790/99407542-43d98600-2900-11eb-9c4a-03085f1d0ef7.png)

**Comment by pbek** [comment]
If you want source archives: https://www.qownnotes.org/installation/building.html#source-archive 😉 
The one with the releases are forced in by GitHub and don't have the submodules in them...
