### ISSUE TITLE
[I] Show remote trash: Nextcloud / ownCloud server connection error

### ISSUE THREAD

**Issue by rigrig** [pbek/QOwnNotes#1958]
#### Expected behaviour

Show remote trash should show the remote list of trashed notes

#### Actual behaviour

Error popup titled "Nextcloud / ownCloud server connection error"
> Cannot connect to your Nextcloud / ownCloud server! Please check your Nextcloud / ownCloud configuration.

#### Steps to reproduce

In the menu, navigate to 
Note > Trash > Show remote trash

#### Additional info

In settings the connection to Nextcloud shows all ok, and editing/synching notes works fine.   
![image](https://user-images.githubusercontent.com/2941436/99829867-29501880-2b5d-11eb-8448-f25f7b87929c.png)

#### Relevant log output in the Log panel

<details><summary>Expand</summary>
Empty lines and #comment added by hand

```
[20:18:00] [debug] updatePanelMenu - 'updatePanelMenu'
[20:18:00] [info] "QOwnNotes server listening on port 22222"
[20:18:00] [debug] on_noteTreeWidget_itemSelectionChanged
[20:18:00] [debug] setCurrentNote - 'note': Note: <id>2 <name>"done" <fileName>"done.txt" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false - 'updateNoteText': true - 'updateSelectedNote': false
[20:18:00] [debug] Loading trigrams from ":/libraries/sonnet/src/trigrams.map"
[20:18:00] [warning] Missing trigrams for languages: QSet("es_CO", "es_AR", "es_US", "es_PA", "es_MX", "it_CH", "es_EC", "es_CU", "en_AU", "es_PY", "fr_BE", "es_VE", "es_PE", "fr_LU", "es_NI", "fr_MC", "es_CL", "es_UY", "es_HN", "es_DO", "de_CH", "fr_CH", "es_BO", "es_CR", "en_CA", "es_SV", "fr_CA", "es_GT", "es_PR", "en_ZA")
[20:18:00] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_GB"
[20:18:00] [debug] Loading dictionary for "en_GB" from "/usr/share/hunspell"
[20:18:00] [debug] Created 0x555c71e19c70
[20:18:00] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "it_IT"
[20:18:00] [debug] Loading dictionary for "it_IT" from "/usr/share/hunspell"
[20:18:00] [debug] Created 0x555c71be9d90
[20:18:00] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "fr"
[20:18:00] [debug] Loading dictionary for "fr" from "/usr/share/hunspell"
[20:18:00] [debug] Created 0x555c71a428c0
[20:18:00] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "es_ES"
[20:18:00] [debug] Loading dictionary for "es_ES" from "/usr/share/hunspell"
[20:18:00] [debug] Created 0x555c7276e810
[20:18:00] [debug] cloudConnection: CloudConnection: <id>1 <name>"Tubul" <serverUrl>"https://tubul.net" <username>"richard" <priority>0
[20:18:00] [debug] added to history: NoteHistoryItem: <noteName>"done" <noteSubFolderPathData>"" <cursorPosition>0 <relativeScrollBarPosition>0
[20:18:00] [debug] on_noteTreeWidget_currentItemChanged
[20:18:00] [debug] filterNotesByTag - 'noteIdList': QVector(1, 2, 4, 5, 3, 9, 6, 7, 8)
[20:18:01] [debug] Reply from "/qownnotes/scripts/master/list-maker/info.json"
[20:18:01] [debug] Reply from info.qml request
[20:18:01] [debug] Reply from "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[20:18:01] [debug] Reply from app version test
[20:18:01] [debug] cloudConnection: CloudConnection: <id>1 <name>"Tubul" <serverUrl>"https://tubul.net" <username>"richard" <priority>0
[20:18:01] [debug] Reply from "/ocs/v2.php/apps/files_sharing/api/v1/shares"
[20:18:01] [debug] Reply from share api
[20:18:01] [debug] updateNoteShareStatusFromShare - 'status': "ok\n"
[20:18:10] [status] No script updates were found

# Now trying to open remote trash

[20:18:24] [status] Trashed notes are currently loaded from your Nextcloud / ownCloud server
[20:18:24] [debug] cloudConnection: CloudConnection: <id>1 <name>"Tubul" <serverUrl>"https://tubul.net" <username>"richard" <priority>0
[20:18:24] [debug] Reply from "/index.php/apps/qownnotesapi/api/v1/note/trashed"
[20:18:24] [debug] Reply from trash list
[20:18:24] [status] Done with loading trashed notes
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `vr nov. 20 18:17:36 2020`
**Version**: `20.11.9`
**Build date**: `Nov 20 2020`
**Build number**: `788`
**Platform**: `linux`
**Operating System**: `Linux Mint 20`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.12.8`
**Qt Version (runtime)**: `5.12.8`
**Portable mode**: `no`
**Settings path / key**: `/home/richard/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/richard/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `Mint-Y`
**Notes in current note folder**: `9`
**Calendar items**: `127`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: `https://tubul.net`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `20.0.2.2`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `de_AT, de_AT_frami, de_CH, de_CH_frami, de_DE, de_DE_frami, en_AU, en_CA, en_GB, en_US, en_ZA, es_AR, es_BO, es_CL, es_CO, es_CR, es_CU, es_DO, es_EC, es_ES, es_GT, es_HN, es_MX, es_NI, es_PA, es_PE, es_PR, es_PY, es_SV, es_US, es_UY, es_VE, fr, fr_BE, fr_CA, fr_CH, fr_FR, fr_LU, fr_MC, it_CH, it_IT, pt_BR, pt_PT, ru_RU`
**Language names**: `Österreichisches Deutsch (Österreich), Österreichisches Deutsch (Österreich), Schweizer Hochdeutsch (Schweiz), Schweizer Hochdeutsch (Schweiz), Deutsch (Deutschland), Deutsch (Deutschland), Australian English (Australia), Canadian English (Canada), British English (United Kingdom), American English (United States), English (South Africa), español (Argentina), español (Bolivia), español (Chile), español (Colombia), español (Costa Rica), español (Cuba), español (República Dominicana), español (Ecuador), español de España (España), español (Guatemala), español (Honduras), español de México (México), español (Nicaragua), español (Panamá), español (Perú), español (Puerto Rico), español (Paraguay), español (El Salvador), español (Estados Unidos), español (Uruguay), español (Venezuela), français, français (Belgique), français canadien (Canada), français suisse (Suisse), français (France), français (Luxembourg), français (Monaco), italiano (Svizzera), italiano (Italia), português (Brasil), português europeu (Portugal), русский (Россия)`
**Application dictionaries path**: `/home/richard/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-2`
**localPath**: `/home/richard/Documents/Notes`
**remotePath**: *empty*
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/richard/Documents/Notes/notes.sqlite`

### Cloud connection `Tubul`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://tubul.net`
**username**: `richard`

### Script `List maker`

**id**: `1`
**path**: `/home/richard/.local/share/PBE/QOwnNotes/scripts/list-maker/list-maker.qml`
**variablesJson**: 
```
{
    "setLetters": "abcdefghijklmnopqrstuvwxyz",
    "setMarkers": "- • ‣"
}
```
**identifier**: `list-maker`
**version**: `0.0.2`
**minAppVersion**: `17.07.8`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**DistractionFreeMode/editorWidthMode** (QString): `3`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `22`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrainingSpaces** (bool): `false`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-11-20T18:08:46.339`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Monospace,14,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Ubuntu,14,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Monospace,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Ubuntu,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/local-trash-notes-removed** (QString): `1024`
**MessageBoxOverride/remove-notes** (QString): `16384`
**NoteFolder-1/NoteTabNameList** (QStringList): `Methods vs Spells`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `Discworld`
**NoteFolder-1/allowDifferentNoteFileName** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 12 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `11`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Entertainment`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `true`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `true`
**appMetrics/disableTracking** (bool): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): `yyyy-MM-dd hh:mm`
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (int): `18`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `false`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `false`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `true`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/richard/Documents/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `20.0.2.2`
**restoreCursorPosition** (bool): `true`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2020-11-20T18.17.23, QOwnNotes Web Companion browser extension QOwnNotes`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `0`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**webSocketServerService/token** (QString): `EyESVykx`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**BROWSER**: `firefox`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**DEFAULTS_PATH**: `/usr/share/gconf/cinnamon.default.path`
**DESKTOP_AUTOSTART_ID**: `106cead55b5c17bda9160572071339060500000012150027`
**DESKTOP_SESSION**: `cinnamon`
**DISPLAY**: `:0`
**GDMSESSION**: `cinnamon`
**GDM_LANG**: `en_US`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**GTK_MODULES**: `gail:atk-bridge`
**GTK_OVERLAY_SCROLLING**: `1`
**HOME**: `/home/richard`
**LANG**: `en_US.UTF-8`
**LANGUAGE**: `en_US`
**LC_ADDRESS**: `nl_NL.UTF-8`
**LC_IDENTIFICATION**: `nl_NL.UTF-8`
**LC_MEASUREMENT**: `nl_NL.UTF-8`
**LC_MONETARY**: `nl_NL.UTF-8`
**LC_NAME**: `nl_NL.UTF-8`
**LC_NUMERIC**: `nl_NL.UTF-8`
**LC_PAPER**: `nl_NL.UTF-8`
**LC_TELEPHONE**: `nl_NL.UTF-8`
**LC_TIME**: `nl_NL.UTF-8`
**LOGNAME**: `richard`
**MANDATORY_PATH**: `/usr/share/gconf/cinnamon.mandatory.path`
**PAPERSIZE**: `a4`
**PATH**: `/home/richard/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
**PWD**: `/home/richard`
**QT_ACCESSIBILITY**: `1`
**QT_QPA_PLATFORMTHEME**: `qt5ct`
**SESSION_MANAGER**: `local/vimes:@/tmp/.ICE-unix/1215,unix/vimes:/tmp/.ICE-unix/1215`
**SHELL**: `/usr/bin/fish`
**SHLVL**: `1`
**SSH_AGENT_PID**: `1291`
**SSH_AUTH_SOCK**: `/tmp/ssh-YpA0JjnAiRZR/agent.1215`
**TERM**: `xterm-256color`
**USER**: `richard`
**WINDOWID**: `188743695`
**XAUTHORITY**: `/home/richard/.Xauthority`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-cinnamon:/etc/xdg`
**XDG_CURRENT_DESKTOP**: `X-Cinnamon`
**XDG_DATA_DIRS**: `/usr/share/cinnamon:/usr/share/gnome:/home/richard/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/richard`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_SEAT**: `seat0`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_DESKTOP**: `cinnamon`
**XDG_SESSION_ID**: `c1`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**XDG_SESSION_TYPE**: `x11`
**XDG_VTNR**: `7`
**XTERM_LOCALE**: `en_US.UTF-8`
**XTERM_SHELL**: `/usr/bin/fish`
**XTERM_VERSION**: `XTerm(353)`
</details>

**Comment by pbek** [comment]
I cannot reproduce your issue, it works fine for me with NC 20.0.2.2.
Can you please turn on debug logging (see issue template) and post the output in the Log panel again after you tried accessing the remote trash.

**Comment by rigrig** [comment]
Whoops, sorry I messed up the log. 
I updated my initial report with the log of fresh start+reproducing the issue

**Comment by rigrig** [comment]
<details><summary>Relevant Nextcloud log (only complains a bit about a deprecation warning)</summary>

```
{"reqId":"ddxSyieKmd3xlAa8IpWo","level":0,"time":"2020-11-20T19:30:14+00:00","remoteAddr":"31.20.131.213","user":"richard","app":"apporder","method":"GET","url":"/index.php/apps/qownnotesapi/api/v1/note/trashed?format=json&dir=/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9a3pre) Gecko/20070330","version":"20.0.2.2"}
{"reqId":"ddxSyieKmd3xlAa8IpWo","level":0,"time":"2020-11-20T19:30:14+00:00","remoteAddr":"31.20.131.213","user":"richard","app":"contacts","method":"GET","url":"/index.php/apps/qownnotesapi/api/v1/note/trashed?format=json&dir=/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9a3pre) Gecko/20070330","version":"20.0.2.2"}
{"reqId":"ddxSyieKmd3xlAa8IpWo","level":0,"time":"2020-11-20T19:30:14+00:00","remoteAddr":"31.20.131.213","user":"richard","app":"richdocuments","method":"GET","url":"/index.php/apps/qownnotesapi/api/v1/note/trashed?format=json&dir=/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9a3pre) Gecko/20070330","version":"20.0.2.2"}
{"reqId":"ddxSyieKmd3xlAa8IpWo","level":0,"time":"2020-11-20T19:30:14+00:00","remoteAddr":"31.20.131.213","user":"richard","app":"files_sharing","method":"GET","url":"/index.php/apps/qownnotesapi/api/v1/note/trashed?format=json&dir=/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9a3pre) Gecko/20070330","version":"20.0.2.2"}
{"reqId":"ddxSyieKmd3xlAa8IpWo","level":0,"time":"2020-11-20T19:30:14+00:00","remoteAddr":"31.20.131.213","user":"richard","app":"files_texteditor","method":"GET","url":"/index.php/apps/qownnotesapi/api/v1/note/trashed?format=json&dir=/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9a3pre) Gecko/20070330","version":"20.0.2.2"}
{"reqId":"ddxSyieKmd3xlAa8IpWo","level":0,"time":"2020-11-20T19:30:14+00:00","remoteAddr":"31.20.131.213","user":"richard","app":"maps","method":"GET","url":"/index.php/apps/qownnotesapi/api/v1/note/trashed?format=json&dir=/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9a3pre) Gecko/20070330","version":"20.0.2.2"}
{"reqId":"ddxSyieKmd3xlAa8IpWo","level":0,"time":"2020-11-20T19:30:14+00:00","remoteAddr":"31.20.131.213","user":"richard","app":"metadata","method":"GET","url":"/index.php/apps/qownnotesapi/api/v1/note/trashed?format=json&dir=/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9a3pre) Gecko/20070330","version":"20.0.2.2"}
{"reqId":"ddxSyieKmd3xlAa8IpWo","level":0,"time":"2020-11-20T19:30:14+00:00","remoteAddr":"31.20.131.213","user":"richard","app":"qownnotesapi","method":"GET","url":"/index.php/apps/qownnotesapi/api/v1/note/trashed?format=json&dir=/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9a3pre) Gecko/20070330","version":"20.0.2.2"}
{"reqId":"ddxSyieKmd3xlAa8IpWo","level":0,"time":"2020-11-20T19:30:14+00:00","remoteAddr":"31.20.131.213","user":"richard","app":"twofactor_totp","method":"GET","url":"/index.php/apps/qownnotesapi/api/v1/note/trashed?format=json&dir=/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9a3pre) Gecko/20070330","version":"20.0.2.2"}
```
</summary>

**Comment by pbek** [comment]
What does your webserver logs say? Have you configured your webserver in a way it throws an error 500 on php notices like deprecation messages?

**Comment by rigrig** [comment]
Just this: (Nextcloud runs on Apache behind an Nginx proxy)
```
==> nginx/access.log <==
31.20.131.213 - richard [20/Nov/2020:21:04:20 +0100] "GET /index.php/apps/qownnotesapi/api/v1/note/trashed?format=json&dir=/ HTTP/1.1" 200 47 "-" "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9a3pre) Gecko/20070330"

==> apache2/nextcloud/access.log <==
127.0.0.1 - richard [20/Nov/2020:21:04:20 +0100] "GET /index.php/apps/qownnotesapi/api/v1/note/trashed?format=json&dir=/ HTTP/1.0" 200 1565 "-" "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9a3pre) Gecko/20070330"
```

Those deprecation warnings also show up for a bunch of other apps which all work fine, so I don't think that is causing the problem.

**Comment by pbek** [comment]
It's a status 200, everything seems to be in best order.
You haven't set a `remotePath` for your note folder, maybe that's the issue.

**Comment by rigrig** [comment]
It was! Setting that fixed it, thanks!   
And I guess everything else seemed to work fine because the Nextcloud client was also syncing my Notes folder.

**Comment by pbek** [comment]
Great. 😁
