### ISSUE TITLE
QOwnNotes.exe identified as Windows 10 Trojan

### ISSUE THREAD

**Issue by benqrn** [pbek/QOwnNotes#1959]
I had an odd alert after I updated QOwnNotes this morning from Windows, it identified the QOwnNotes.exe binary as a trojan, "Trojan:Win32/Bearfoos.A!ml"

Was not sure where else to report this, Google says this is a generic trojan detection from Windows.  I'm confident I do not have a bad copy of QOwnNotes as it has been installed for some time now and only self-updates from its own trusted source.

**Comment by pbek** [comment]
Always false positive so far, see #1951, #1948 (or similar like #1887).

Does https://www.virustotal.com find anything?

There's not much that can be done about "bad heuristics" in Windows Defender, last time MS patched that problem away within days... I myself was never able to reproduce this in Windows 10 Home Edition, it always worked...

**Comment by benqrn** [comment]
That is what I suspected, and no, virustotal does not find anything.

Sorry, did not see those other issues, was just searching 'virus' or 'trojan'.

Thanks!
