### ISSUE TITLE
Internote links in [[brackets]]

### ISSUE THREAD

**Issue by capcionista** [pbek/QOwnNotes#196]
Probably following notational velocity, many other note taking applications use  [[brackets]] to link to notes in the same directory with the name e.g. brackets (nvALT, resophnotes, nvpy, nvatom...)
Compared to the current link format of qownnotes (which is in a way more powerful and flexible) this seems to be more light-weight and makes text easier to read.
Adopting  or at least adding this format would allow us to migrate easier to qownnotes and also to use or share notes with devices that are using other note taking software.

**Comment by pbek** [comment]
Thank you for your suggestion, but `[[brackets]]` is not a valid markdown syntax, it would get ignored by all parsers...

**Comment by pbek** [comment]
A migration script would make more sense in my eyes...

**Comment by capcionista** [comment]
Thank you for your reply. 
Unfortunately, when collaborating for Mac users sharing a knowledge base through the cloud and unwilling to give up on their notetaking software, a script can't fix it.
I'm not suggesting to necessarily replace the syntax, but adding the feature of reading [[note-name]] as well as a link would be amazing. Also, it would allow users to try (and probably switch to) your software without modifying their current database.

Apart from that, the current format "<note://notename>" slows down adding links by typing note names (without using your mouse). If [[inside double bracket links]] are not an option at all: would it be possible to simplify the current syntax to <notename> or <://notename> or the like?

**Comment by pbek** [comment]
To make `[[note-name]]` possible I would need to fork the markdown highlighter, as well as the markdown to html converter and hack them both. And then I would have to implement a new click handling for those links... I'd rather not do anything like that.

And I'm sorry, `://notename` is not a valid URL and wouldn't be recognized as such.
You are not supposed to link notes by hand, just press the hotkey for adding links and select to note.
