### ISSUE TITLE
Feature Request: Copy code block feature for single line inline code

### ISSUE THREAD

**Issue by Greggex** [pbek/QOwnNotes#1967]
I have many commands stored as single lines of inline code (i.e. surrounded by single back-ticks). It would be very useful to be able to easily copy and paste the command without the back-ticks

#### Expected behaviour

When right clicking on code surrounded by single back-ticks "Copy code block" would be available. Selecting "Copy code block" would copy the code without the back-ticks to the clipboard.

#### Actual behaviour

"Copy code block" is currently greyed out for code surrounded by single back-ticks

**Comment by pbek** [comment]
Thank you for your suggestion.
Meanwhile you could also code that yourself with the scripting engine. 😉

**Comment by pbek** [comment]
@fnkabit, `MainWindow::noteTextEditCustomContextMenuRequested` in case you want to fool around with this. 😁

**Comment by fnkabit** [comment]
@pbek I'm on it :p

**Comment by pbek** [comment]
## 20.12.0
- you can now also copy in-line code blocks in the note text edit with the context menu
  (for [#1967](https://github.com/pbek/QOwnNotes/issues/1967), thank you @fnkabit)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Greggex** [comment]
Works like a charm.
Thank you very much.

**Comment by pbek** [comment]
Great, thank you for testing!
