### ISSUE TITLE
Some suggestions for the Editor

### ISSUE THREAD

**Issue by Fischmuetze** [pbek/QOwnNotes#197]
QOwnNotes 16.06.1
Hi, thank you for this wonderful app!

Some suggestions just for the Editor 

* Option to disable colors and markdown previews in the editor
it would be really great if there was an option to show the notes as only pure text without preview any markdown modes. My "notes" contains in the most cases i.e. parts of configuration files and it's very unusual if comments marked with hash are shown in another color 

* An Option to adapt the font sizes in the editor
It's very unusual that the font sizes of some markdown items comes in another font size 

* An Option to prevent the softwrap

Other points
* Not really a good idea to place an app exit button in the center of the toolbar without an option to disable this button nor to adapt the toolbar layout 

* It is possible to add "pseudo" empty keywords (using space). not really helpful

**Comment by pbek** [comment]
Thank you for your kind words and your suggestions!

> Option to disable colors and markdown previews in the editor

Do you mean an option to disable the markdown highlighting in the editor altogether?

> An Option to adapt the font sizes in the editor

You can do that in the settings or do you mean something else?

> Not really a good idea to place an app exit button in the center of the toolbar without an option to disable this button nor to adapt the toolbar layout

The quick button is in the toolbar for technical reasons (a shortcut problem under Ubuntu Unity).
Maybe I should move it to a new toolbar (they can be turned off) and move it to the right.

> It is possible to add "pseudo" empty keywords (using space). not really helpful

I guess you mean the tags, right?

**Comment by Fischmuetze** [comment]
> Do you mean an option to disable the markdown highlighting in the editor altogether?
yes!

>You can do that in the settings or do you mean something else?
In the settings there are only options for general adapt the font sizes. But i.e. in the editor lines which "tagged" with a hash will displayed in a bigger font size as the standard font size (on OS X, but I guess also in other os versions ) ... it appears unusal for the editor part that it is using different font sizes for tagged parts
>I guess you mean the tags, right?
yes most probably I meant this ... the german UI call it "Schlagworte" and "keywords"  is a usal translation ... but "tags" is also ok

**Comment by pbek** [comment]
> In the settings there are only options for general adapt the font sizes. But i.e. in the editor lines which "tagged" with a hash the text appears in a bigger font size as the standard font size (on OS X, but I guess also in other os versions ) ... it appears unusal for the editor part that it is using different font sizes for tagged parts to highlighting them

I think you are talking about markdown headlines, like:

```
# headline 1
## headline 2
### headline 3
```

they look like:

# headline 1
## headline 2
### headline 3

They are supposed to have different font sizes.
I there would be an option to turn off markdown support in the editor altogether, would that be of help?

**Comment by Fischmuetze** [comment]
> I there would be an option to turn off markdown support in the editor altogether, would that be of help?

yes in any case it would be helpful! Thank you!

just subjective word: Imho it is very unusual to preview the markdown tagged parts in the editor pane not only by colors but also by changing the font sizes. In my opinion this is  a little bit "nonsense"  as this counteract the idea of markdown and in addition the app comes with a editor and a preview part

**Comment by Fischmuetze** [comment]
One point was missing in my suggestions:
* optional Line numbers

**Comment by pbek** [comment]
> just subjective word: Imho it is very unusual to preview the markdown tagged parts in the editor pane not only by colors but also by changing the font sizes. In my opinion this is a little bit "nonsense" as this counteract the idea of markdown and in addition the app comes with a editor and a preview part

And yet there are other who want even want more WYSIWG...
I don't think both color and font size are counter-intuitive...

> optional Line numbers

I haven't had any luck adding those so far...

**Comment by Fischmuetze** [comment]
Thank you Patrizio! Maybe there is later a possibility to implement an  highlighting adaption dialog. For me it would be very helpful to have simply an option to switch off the highlighting and to have an option to switch off the soft word wrap. Thank you very much!

**Comment by pbek** [comment]
I'll what I can do. :smile_cat:

**Comment by pbek** [comment]
for v16.06.3
- there now is a new toolbar for the quit button right of the other toolbars, 
  so this button can be disabled

**Comment by pbek** [comment]
from the v16.06.3 changelog
- you can now set the markdown highlighting interval in the interface settings
  (for [Issue #104](https://github.com/pbek/QOwnNotes/issues/104))
    - if you set it to `0` the highlighting will be disabled
      (for [Issue #197](https://github.com/pbek/QOwnNotes/issues/197))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Fischmuetze** [comment]
guess this solution could have a strange effect ....
This one sounds more logical, right?
https://forum.qt.io/topic/24960/solved-osx-menu-icons/4

best

**Comment by pbek** [comment]
now that sounds promising, I will try that for #198 
thank you!

**Comment by pbek** [comment]
from the v16.06.5 changelog:

- you now can disable the soft wrapping in the note editor and preview in the
  window menu
- you now cannot any more create empty tags

**Comment by Fischmuetze** [comment]
For the points
* option to disable highlighting
* option to disable softwrap
* prevent creation of empty tags 
this is OK

**Comment by pbek** [comment]
## 16.08.10
- there now is a checkbox in the Interface settings where you can 
  turn off the markdown highlighting
