### ISSUE TITLE
Website doesn't resize to mobile view on Mobile Firefox

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#1970]
The following shows when opening https://www.qownnotes.org/changelog.html#_20-12-0 on my Huawei Mate 20 Pro. Browser: Firefox 80.1.3.

![image](https://user-images.githubusercontent.com/5956570/100745866-30d6b380-33e0-11eb-9422-ead6020f375a.png)

**Comment by pbek** [comment]
Firefox 

![Screenshot_20201201_142854_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/1798101/100746937-ad1dc680-33e1-11eb-95e5-0321209aa81f.jpg)

Chrome

![Screenshot_20201201_071058_com.android.chrome.jpg](https://user-images.githubusercontent.com/1798101/100746986-bdce3c80-33e1-11eb-8bfb-4430dea166ca.jpg)

**Comment by pbek** [comment]
It looks like your Firefox is using some kind of desktop browser viewport...

**Comment by pbek** [comment]
Actually my Firefox is doing the same with the changelog... But it looks great in Chrome.

**Comment by sanderboom** [comment]
Result when I switch 'Desktop site' on:

![image](https://user-images.githubusercontent.com/5956570/100747697-ae9bbe80-33e2-11eb-9a12-bf411879583d.png)

![image](https://user-images.githubusercontent.com/5956570/100747714-b2c7dc00-33e2-11eb-9750-75d84cd2fe9e.png)

**Comment by pbek** [comment]
Funny, it's actually the same with the VuePress webpage: https://vuepress.vuejs.org/config/

**Comment by pbek** [comment]
I now opened https://github.com/vuejs/vuepress/issues/2723.

**Comment by pbek** [comment]
Should be fixed now, it already works for me. Can you confirm that please, @sanderboom?
