### ISSUE TITLE
Feature Request: Embedded PDF reader/open pdfs in os default reader

### ISSUE THREAD

**Issue by OtharSmirnow** [pbek/QOwnNotes#1971]
Hi,
As a note taking app it is great.
It would be great if one could put all the notes in one place, also in form of pdf's or screen shots.

Embedded reader would be the best option as it gives more options for integration, but having ability to just open files located in subfolders in external app would be great.
Right now other files then notes are not listed in notes panel.

I am using linux desktop application.

**Comment by pbek** [comment]
>  As a note taking app it is great.

Thank you. 😁 

>  It would be great if one could put all the notes in one place, also in form of pdf's or screen shots.

You can already have "attachments" in notes. All those files go into one single folder in your note folder.
You could also put files directly next to your note files (in the same directory) if you like.

> Embedded reader would be the best option as it gives more options for integration, but having ability to just open files located in > subfolders in external app would be great.

Can please you explain why it should be in the scope of a software that only shows and edits plain-text files to also show PDFs in the note list?

(Note: In theory https://doc.qt.io/qt-5/qpdfdocument.html could be used to view pdf when clicking on them in notes, but I'm not sure if that would be of a lot of value and QPdfDocument only works with Qt 5.10+)

> Right now other files then notes are not listed in notes panel.

Someone once made a fork of QOwnNotes that uses a fully fledged web browser as preview and I think also lists and shows PDF files in the note list. Maybe you can fine an issue here where we talked about it, I can't find it any more. 😅 

@Waqar144, do you remember it?

**Comment by OtharSmirnow** [comment]
Did not expected so quick answer :D 
I should have named the thread Feature Idea. As you write I am not the first one with it.

> Can please you explain why it should be in the scope of a software that only shows and edits plain-text files to also show PDFs in the note list?
I was thinking about qownnotes more like "all notes management" application. 
Maybe not note list panel, but separate panel, for those who would like it.

It's nice to have, not must have for sure.

I have nothing to add right now and not skilled enough yet to contribute it myself to the project (unfortuantely, but you cant have all)
You can close this thread as there is probably not much to add.

**Comment by pbek** [comment]
>  Maybe not note list panel, but separate panel, for those who would like it.

If PDFs are shown, then why not also MS Word, Excel, Powerpoint and many more formats? I still don't think QOwnNotes should become a "multi-format file viewer".

**Comment by Waqar144** [comment]
There was a separate fork with QWebEngineView, I dont have the link but it should be in existence even now. The thread where we discussed this idea was #1421 

>  Maybe not note list panel, but separate panel, for those who would like it.

Right now, I dont really see any space for any more panels. We already have 10 panels or something lol.

This feature request is out of scope for us in my opinion, unless we want to become emacs lol :rofl:

**Comment by pbek** [comment]
Yes, #1421 was/is our discussion, but someone really made is own fork. I just can't find it any more 😬 

Thank you, I guess I can close this then. 😁
