### ISSUE TITLE
[Feature Request] Folder Grid View

### ISSUE THREAD

**Issue by v3ss0n** [pbek/QOwnNotes#1974]
Show Grid of notes with preview up to 5 lines when Root Folder is Selected.
If main root is sleected , all its childreans are shown as grid
If sub folders are select show its childern (1 level)

#### Expected behaviour
![image](https://user-images.githubusercontent.com/419606/101205447-087add80-369c-11eb-8747-88bc8e729973.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/419606/101201787-ab305d80-3696-11eb-9723-a4955706a531.png)

#### Steps to reproduce
Click on note folder

**Comment by pbek** [comment]
Thank you for your suggestion, but I can't see that coming any time soon for a lot of reasons (starting with performance). 😅 

But there is a setting you can play with...

![image](https://user-images.githubusercontent.com/1798101/101214011-95616f00-367b-11eb-8dcb-c0dd2f6e579f.png)

**Comment by v3ss0n** [comment]
I think lazy loading will be fine for performance. I will give that a try.
