### ISSUE TITLE
The command/path for Python 3 interpreter in the script settings is not valid Please set the correct command/path.

### ISSUE THREAD

**Issue by johnmarkcesta** [pbek/QOwnNotes#1975]
I receive this error when opening notes and saving preferences. I do have the python installed.

thanks

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
QOwnNotes doesn't use python, must be a script you are using.

Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting `Debug` in `Options`).

**Comment by johnmarkcesta** [comment]
It was this one:

This script adds a toolbar button and a note list context menu item to merge multiple selected notes. Notes are merged to the first selected note or to a new note, depending on setting. Notes are merged in the order they were selected.

Dependencies:
Python 3.3+ Interpreter <https://www.python.org/downloads/>.

This script should be used with "Allow note file name to be different from headline" and "Accept all external modification of current note" options on.


I am just going to remove this script. But if you want this info to trouble shoot let me know.

Thanks,

J

**Comment by pbek** [comment]
Like it says, you need Python 3.3 for the script. 😁

**Comment by johnmarkcesta** [comment]
I know it needs python. But I had installed python. The script worked. But I would get an error message each time I loaded qnotes telling me the python path was incorrect. I couldn’t figure out what it wanted.

So I ran out of time trying to figure it out and just removed the script end uninstalled python.

Thanks for your help.

**Comment by pbek** [comment]
Ok, if you still need the script and have troubles just open an issue on the script repository github page.
