### ISSUE TITLE
Configure the navigation panel tree

### ISSUE THREAD

**Issue by lyndhurst** [pbek/QOwnNotes#1978]
Hi,

I am really enjoying the application, such a quality note manager was painfully missing in the qt environment!

This is not an issue, but a suggestion concerning the 'Navigation panel'.
I find it very useful to jump quickly within a note, but for files with deep sub sections, it can become a bit unreadable.

To mitigate this issue I was thinking that being able to control the maximum depth of the tree in the navigation panel could help. Another option could be to set the navigation tree default state as collapsed.

Thank you for your time.

**Comment by pbek** [comment]
Thank you for your suggestion and thank you for your kind words.

How many level of headings do you use? I never run in that problem. It also may vary where users place their navigation panel and how large it is.

**Comment by lyndhurst** [comment]
Usually it does not exceed 3 levels of headings, and then, the navigation panel looks fine, but I do have files with 5 to 6 levels of sub sections, and in that case it makes the panel less useful. Of course the search feature compensates that problem when the user remember the title he / she is looking for.

Also, I find that for long files, the scrolling of the navigation tree is not optimal, hence the suggestion of having the tree collapsed by default. I imagine it can allow the user looking for something specific to kind of cascade down to the desired section having a complete overview at first sight.

I allocate around 60 to 70 % of the window height to that panel, so usually, as you pointed it is fine the way it is. I do not mean to be picky ;)

**Comment by lyndhurst** [comment]
Thinking about the big file issue, I was thinking that an Expand all / Collapse all button could be a more versatile option than a default setting that locks up one choice for every situation...

**Comment by pbek** [comment]
The largest problem is that the navigation panel is regenerated all the time while you are typing and it would be very hard to track and restore what was open and what wasn't, because there is no clear reference to a headline. It's just text.

And ignoring everything over level three would also be not liked by all users. 😅

**Comment by lyndhurst** [comment]
I did not think about it, but it is true that it is regenerated all the time, I did not think about it. Of course, imposing a depth to all users would be unwise, but if an additional setting could be available, then everyone  could set it as desired.

For the collapsing idea do you think a 'collapse all' shortcut or button could be made available for punctual needs?

While we are talking about the navigation panel, correct me if I am wrong, but there is no available shortcut to focus the search field as far I looked...
