### ISSUE TITLE
"Module QtQml is not installed" on Windows 10

### ISSUE THREAD

**Issue by willtm** [pbek/QOwnNotes#1979]
#### Expected behaviour

When I attempt to encrypt a note, I expect that QOwnNotes will default to keybase since I have the keybase encryption script installed.

#### Actual behaviour

Instead of defaulting to keybase, I am given the option to enter a password twice.  This alerted me that something was wrong with the keybase encryption setup.  And when I went to check the keybase settings by going to Scripting > Script Settings > Keybase Encryption, the option to identify the path to the executable and other settings was not available.  All the displays is information about the script.  Unless I have forgotten where the keybase encryption settings should reside--entirely possible!--something is wrong.

#### Steps to reproduce

Go to Scripting > Script Settings > Keybase Encryption and the option to identify the path to the executable and other settings is not available.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Thu Dec 10 20:30:32 2020`
**Version**: `20.12.3`
**Build date**: `Dec  7 2020`
**Build number**: `794`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\wtmon\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Users\wtmon\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1200`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `38`
**Calendar items**: `0`
**Enabled scripts**: `7`

## Server Info

**serverUrl**: `http://willtmonroe.com/files`
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `en_US`
**Language codes**: `en_US`
**Language names**: `American English (United States)`
**Application dictionaries path**: `C:\Users\wtmon\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `3`

### Note folder `default`

**id**: `3`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `C:\Users\wtmon\Google Drive\notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\wtmon\Google Drive\notes\notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `http://willtmonroe.com/files`
**username**: `p35pwu`

### Script `Journal entry`

**id**: `2`
**path**: `C:\Users\wtmon\AppData\Roaming\PBE\QOwnNotes\scripts\journal-entry\journal-entry.qml`
**variablesJson**: 
```
{
    "defaultTags": "journal",
    "noteBodyTemplate": "",
    "singleJournalPerDay": true
}
```
**identifier**: `journal-entry`
**version**: `1.5.1`
**minAppVersion**: `17.11.6`

### Script `Image preview`

**id**: `3`
**path**: `C:\Users\wtmon\AppData\Roaming\PBE\QOwnNotes\scripts\image-preview\image-preview.qml`
**variablesJson**: 
```
{
    "maxWidth": 640
}
```
**identifier**: `image-preview`
**version**: `1.0.1`
**minAppVersion**: `20.6.0`

### Script `Insert Table of Contents (TOC)`

**id**: `5`
**path**: `C:\Users\wtmon\AppData\Roaming\PBE\QOwnNotes\scripts\insert-toc\insert-toc.qml`
**variablesJson**: 
```
{
    "tocTitle": "Table of Contents"
}
```
**identifier**: `insert-toc`
**version**: `0.0.3`
**minAppVersion**: `17.06.2`

### Script `Un-wrap Text`

**id**: `7`
**path**: `C:\Users\wtmon\AppData\Roaming\PBE\QOwnNotes\scripts\unwrap\unwrap.qml`
**variablesJson**: *empty*
**identifier**: `unwrap`
**version**: `1.0.0`
**minAppVersion**: `18.04.3`

### Script `Vivaldi Notes`

**id**: `11`
**path**: `C:\Users\wtmon\AppData\Roaming\PBE\QOwnNotes\scripts\vivaldi-notes\vivaldi-notes.qml`
**variablesJson**: *empty*
**identifier**: `vivaldi-notes`
**version**: `0.0.3`
**minAppVersion**: `20.11.0`

### Script `Keybase Encryption`

**id**: `12`
**path**: `C:\Users\wtmon\AppData\Roaming\PBE\QOwnNotes\scripts\encryption-keybase\encryption-keybase.qml`
**variablesJson**: *empty*
**identifier**: `encryption-keybase`
**version**: `0.0.1`
**minAppVersion**: `17.05.7`

### Script `zettelkasten`

**id**: `13`
**path**: `C:\Users\wtmon\AppData\Roaming\PBE\QOwnNotes\scripts\zettelkasten\zettelkasten.qml`
**variablesJson**: *empty*

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `true`
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**DistractionFreeMode/editorWidthMode** (int): `2`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (int): `21`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `false`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (QString): `true`
**Editor/disableCursorBlinking** (QString): `true`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (QString): `true`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `C:/Users/wtmon/AppData/Roaming/PBE/QOwnNotes/scripts/zettelkasten`
**FileDialog/LastPath-ExternalEditor** (QString): `C:/Program Files/iA Writer`
**FileDialog/LastPath-GitExecutable** (QString): `C:/Program Files/Git`
**FileDialog/LastPath-ImportTextFiles** (QString): `C:/Users/wtmon/Downloads/Readwise`
**FileDialog/LastPath-NotePDFExport** (QString): `C:/Users/wtmon/Downloads`
**FileDialog/LastPath-ScriptPath** (QString): `C:/Users/wtmon/AppData/Roaming/PBE/QOwnNotes/scripts/zettelkasten`
**FileDialog/LastPath-ScriptSettingsFile-encryption-keybase-kaybasePath** (QString): `C:/Users/wtmon/AppData/Local/Keybase`
**ImageDialog/disableCopying** (QString): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-12-10T20:01:23.812`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Calibri,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Courier New,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Calibri,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/delete-files** (int): `16384`
**MessageBoxOverride/readonly-mode-allow** (int): `16384`
**MessageBoxOverride/remove-note** (int): `16384`
**MessageBoxOverride/remove-notes** (int): `16384`
**MessageBoxOverride/remove-script** (int): `16384`
**MessageBoxOverride/script-install-successful** (int): `1024`
**MessageBoxOverride/update-and-restart** (int): `16384`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-3/NoteTabNameList** (QStringList): `Note 2020-11-29T20.33.08`
**NoteFolder-3/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-3/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteFolder-3/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-3** (QVariantList): `<variant list with 115 item(s)>`
**NoteHistoryCurrentIndex-3** (int): `114`
**OrphanedImagesDialog/geometry** (QByteArray): `<binary data>`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExportOrientation** (int): `0`
**Printer/NotePDFExportPageSize** (int): `10`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-customAction_createZettelkastenNote** (QString): *empty*
**Shortcuts/MainWindow-customAction_insertToc** (QString): *empty*
**Shortcuts/MainWindow-customAction_journalEntry** (QString): *empty*
**Shortcuts/MainWindow-customAction_journalEntryTomorrow** (QString): *empty*
**Shortcuts/MainWindow-customAction_unWrap** (QString): *empty*
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**TagAddDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**VersionDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `3`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `false`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): `C:/Program Files/iA Writer/iAWriter.exe`
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `31`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `true`
**ignoreAllExternalNoteFolderChanges** (QString): `true`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (int): `15`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `false`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `C:/Users/wtmon/Google Drive/notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `c55a63e6-aeb8-418c-8bab-7c29117508da`
**recentNoteFolders** (QStringList): `C:/Users/wtmon/Nextcloud/Notes`
**restoreCursorPosition** (QString): `false`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-3** (QStringList): `Note 2020-12-06T19.16.40, Note 2020-12-02T09.29.35, Interviewing Your Domain, Note 2020-11-29T20.33.08, Note 2020-11-25T09.07.47, Note bc4302f8-3c11-47c7-bffe-776c3ea61c91, Note 2020-10-20T09.14.02, Note 2020-10-19T21.33.36, Note cf6cfc0b-bf73-48be-a727-33ad0b1b089c, Note 2020-10-04T20.13.38, Note 2020-10-04T13.56.04, Note 2020-09-28T08.16.25, Note 2020-09-25T09.23.26, Note 2020-09-22T11.38.10, Note 2020-09-20T13.49.52, blog, Note 2020-09-20T07.19.47, Note 719171a0-28ce-4b74-bfbf-e1a939873ba8, Note 9474e1e8-99ce-48ef-8b62-1c7fcaddeb09, Note 2020-02-06T19.59.10, Note e6e64860-d3bf-46ad-ba1b-e0b3185c2cc2, Note 75dc9482-ca9b-4c95-9f8a-58d24ca0942f, Note b6e3ae08-a0f2-49c0-a373-0a4f890eec9f, Note 2020-02-04T14.37.44, Note ae8de3ea-db09-435a-8661-9a94240053c1, Note 51fd38c7-6328-4374-b0dd-1d6ed985419e, Note d034abd0-991f-4abc-8da1-d11a0b9112ae, c9f3280087ff4941b80c96569798c1a1, qownnotes web-companion Browser extension to browse bookmarks and create notes in QOwnNotes, QOwnNotes shortcuts, Note 7dde1544-a793-4cc0-bb14-275c05c36fea, Note c20b854d-66a6-4550-880f-d5d1f8599f4f, Welcome to QOwnNotes, This is a note, Markdown Showcase, Markdown Cheatsheet, 201911011451 backward design enduring understanding, 201906041038 backward design - core tasks, 201906041016 big ideas and skills, 201906031121 backward design - big ideas, 201905311049 unpacking content standards, 201905311046 problems with content standards, 201905311042 skills, 201905311025 essential questions, 201905311021 goals, 201905290839 evidence of understanding, 201905281609 coverage versus uncoverage, 201905281602 understanding versus misunderstanding, 201905281555 understanding and transfer, 201905281535 knowledge versus understanding, 201905281054 backward design summary, 201904250851 elrc 7240, 201902131155 what is a disability, 201902131103 web content accessibility standards, 201811291328 digital literacy survey lsu law, 201811210543 how to create direct instruction screencasts, 201811210516 how to create a zettel note`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**skipVersion** (QString): `20.9.11`
**spellCheckLanguage** (QString): `en_US`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (QString): `false`
**useSoftWrapInNoteEditor** (QString): `true`
**useUNIXNewline** (QString): `false`
**versionSplitterSizes** (QByteArray): `<binary data>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**webSocketServerService/token** (QString): `xVErqVyT`
**workspace-c55a63e6-aeb8-418c-8bab-7c29117508da/name** (QString): `Preview`
**workspace-c55a63e6-aeb8-418c-8bab-7c29117508da/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-c55a63e6-aeb8-418c-8bab-7c29117508da/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `false`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, c55a63e6-aeb8-418c-8bab-7c29117508da`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\wtmon\AppData\Roaming`
**ChocolateyInstall**: `C:\ProgramData\chocolatey`
**ChocolateyLastPathUpdate**: `132046511924330234`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `WILLS-FAST-LAPP`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**configsetroot**: `C:\WINDOWS\ConfigSetRoot`
**DokanLibrary1**: `C:\Program Files\Dokan\Dokan Library-1.2.2\`
**DokanLibrary1_LibraryPath_x64**: `C:\Program Files\Dokan\Dokan Library-1.2.2\lib\`
**DokanLibrary1_LibraryPath_x86**: `C:\Program Files\Dokan\Dokan Library-1.2.2\x86\lib\`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\wtmon`
**LOCALAPPDATA**: `C:\Users\wtmon\AppData\Local`
**LOGONSERVER**: `\\WILLS-FAST-LAPP`
**NUMBER_OF_PROCESSORS**: `8`
**OneDrive**: `C:\Users\wtmon\OneDrive`
**OneDriveConsumer**: `C:\Users\wtmon\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Calibre2\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile64\;C:\Program Files (x86)\Common Files\Acronis\FileProtector\;C:\Program Files (x86)\Common Files\Acronis\FileProtector64\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files\Pandoc\;C:\Program Files\MiKTeX\miktex\bin\x64\;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files\Git\cmd;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\dotnet\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Users\wtmon\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\wtmon\AppData\Local\GitHubDesktop\bin;C:\Program Files\GPAC;C:\Users\wtmon\AppData\Local\Box\Box Edit\;C:\Users\wtmon\AppData\Local\Keybase\;C:\Users\wtmon\AppData\Local\Programs\Microsoft VS Code\bin`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 142 Stepping 10, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `8e0a`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**PYTHONHOME**: `C:\Python27`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\wtmon\AppData\Local\Temp`
**TMP**: `C:\Users\wtmon\AppData\Local\Temp`
**USERDOMAIN**: `WILLS-FAST-LAPP`
**USERDOMAIN_ROAMINGPROFILE**: `WILLS-FAST-LAPP`
**USERNAME**: `wtmon`
**USERPROFILE**: `C:\Users\wtmon`
**windir**: `C:\WINDOWS`
</details>

**Comment by pbek** [comment]
Was there no error message in the log?
Can you please post the output from the debug settings (see issue template).
Did the script ever worked for you under Windows?
Does the keybase cli client throws an error when you use it in the Windows terminal?

**Comment by pbek** [comment]
But can you please open this issue at https://github.com/qownnotes/scripts/issues, like I suggested. 😅

**Comment by pbek** [comment]
(GitHub doesn't let me move the issue.)

**Comment by pbek** [comment]
Leading from https://github.com/qownnotes/scripts/issues/118.

> [06:39:18] [warning] script errors: (file:///C:/Users/wtmon/AppData/Roaming/PBE/QOwnNotes/scripts/encryption-keybase/encryption-keybase.qml:1:1: module "QtQml" is not installed import QtQml 2.0 ^)

There generally seems to be a problem with the current patch level of Windows and Qt 5.15.2 (I can reproduce them).
There are no problems on Windows 8.1.
The immediate solution for you is to fall back to https://github.com/pbek/QOwnNotes/releases/tag/v20.12.2 while I try to find out what is happening.
For some strange reason no-one else seems on the internet to have this issue...

**Comment by pbek** [comment]
@willtm, or even better try this version: https://github.com/pbek/QOwnNotes/suites/1623230644/artifacts/29855130

**Comment by pbek** [comment]
## 20.12.4
- the scripting engine was fixed for Windows 10

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
You should be able to use the QON updater, no need to download above links I mentioned.

**Comment by pbek** [comment]
If the scripts still don't work you may need to remove the `QtQml` and `QtWebSockets` folders from your QOwnNotes directory, they are not in the release any more.

**Comment by willtm** [comment]
It works!  I can use any script now, including the `keybase encryption` script.

First, I used the QON updater to update to 20.12.4 but nothing changed.  The scripts were still non-functional.

Then I removed the `QtQml` and `QtWebSockets` folders from the QOwnNotes directory as you recommended and after a restart, everything worked perfectly.

Thank you!

One more thing:  I really thought the Help > Post Questions guidance through posting issues was a nice touch.  This makes it so much easier to report issues for an end user and for you I imagine.

**Comment by pbek** [comment]
> Then I removed the QtQml and QtWebSockets folders from the QOwnNotes directory as you recommended and after a restart, everything worked perfectly.

thank you for the feedback... I don't dare to remove anything automatically from the QOwnNotes folder with the update Windows batch file because of the portable mode users. 😬 

> One more thing: I really thought the Help > Post Questions guidance through posting issues was a nice touch. This makes it so much easier to report issues for an end user and for you I imagine.

thank you, it was the plan to make things easier... but it seems hardly anyone uses this assistant 😆

**Comment by pbek** [comment]
...and thank you for reporting this issue!
