### ISSUE TITLE
OS X: Icons in menus

### ISSUE THREAD

**Issue by Fischmuetze** [pbek/QOwnNotes#198]
QOwnNotes 16.06.1, OS X 10.11.5

I would like suggest to give up the icon displaying for menu entries.

It's very unusual to have icons in menus on OS X. 
In the most cases only multi platform applications shows such behavior - but i.e. the most common apps like LibreOffice, Firefox, Thunderbird, MS Office et. etc. accept this common style rule and does not to show icons in their menus.

In addition in the dark mode of the OS X menu the icons of QOwnNotes are very ugly visible as this goes to dark grey icons on a more or less dark grey background.

**Comment by pbek** [comment]
Thank you for your suggestion, I will evaluate that.

> I would like suggest to give up the icon displaying for menu entries.

you mean generally or just in OS X?

> In addition in the dark mode of the OS X menu the icons of QOwnNotes are very ugly visible as this goes to dark grey icons on a more or less dark grey background.

as far as I know there is no dark mode in OS X or am I wrong?
can you post a screenshot?

**Comment by Fischmuetze** [comment]
> you mean generally or just in OS X?

Only in OS X

> as far as I know there is no dark mode in OS X or am I wrong?

Since OS X Yosemite  (the current version is OS X El Capitan)  there is an option to switch the color of the menu line from bright grey to a dark mode
http://www.macworld.co.uk/how-to/mac-software/turn-on-yosemites-dark-mode-on-mac-3534690/

**Comment by pbek** [comment]
I see, I will take a look at that.

**Comment by pbek** [comment]
I haven't found a way to achieve this yet.
<https://forum.qt.io/topic/68169/hiding-icons-in-menu-bar>

**Comment by pbek** [comment]
implemented in version 16.06.5

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Fischmuetze** [comment]
the homepage offers Version 16.06.5 for OS  X but the download page provides only Version 16.06.4

**Comment by pbek** [comment]
give it some time, the build monkeys were working on the caches... 🐒 
it worked for me now...

**Comment by Fischmuetze** [comment]
yes done!

**Comment by Fischmuetze** [comment]
Looks much better under OS X - great!!!
