### ISSUE TITLE
Highlighting of found occurences vanishes after switching notes

### ISSUE THREAD

**Issue by WarpEnterprises** [pbek/QOwnNotes#1980]
Search for a word.
Only notes containing this word are displayed in the search panel.
If the current note is among the found notes, all occurences are highlighted nicely (green background).
If not and I select manually a found note, there is no green highlight.
In this case the occurences cannot be spotted easily.
Expected behaviour would be to apply the highlight after selecting a note as long as a search is active.

**Comment by pbek** [comment]
So we are talking about: "Actually running the in-note search after a note is selected while search terms in the note list search are present." 
Sounds like a nice thing. Thank you for your suggestion. 😁

**Comment by pbek** [comment]
Well, but this also implies that the actual position in the notes will never be rememberd when you switch to another note in the note-list while a search term is present in the note list. I wonder how annoying that is in practice...

**Comment by pbek** [comment]
## 20.12.5
- if you are searching for text in the note list now for the search term is also
  searched inside the notes when you click on other notes in the the note list

**Comment by pbek** [comment]
Oh, while trying to implement this (and breaking other stuff in the process) I found out that this issue is not a feature request, but a regression report. 😅  #1940 broke that feature.

**Comment by WarpEnterprises** [comment]
It seems that there is already some instability in the current position when a search is active:
Open some notes in their own tabs (by doubleclicking)
Do a search in the search panel.
If you now change the notes by singleclicking in the search results the position moves to the *last* found line, not in the current note but in the note you *just left*.
I hope you can reproduce - it's difficult to describe, but I can reproduce it consistently.

BTW: Nice tool - keep up your work - little donation under way 😃

**Comment by pbek** [comment]
> #1940 broke that feature.

I hope I fixed it without new regressions. 😅 

> If you now change the notes by singleclicking in the search results the position moves to the last found line, not in the current note but in the note you just left.

I guess we are talking about #1981 in this case, right?

> BTW: Nice tool - keep up your work - little donation under way smiley

Thank you very much! 😁  So you are from Austria too? 🥳 👍🏻  (I hope that wasn't confidential 😅)

**Comment by pbek** [comment]
> I guess we are talking about #1981 in this case, right?

No, we aren't. Can you put that into a new issue please.

**Comment by WarpEnterprises** [comment]
I will check - greetings from upper🇦🇹 !

**Comment by pbek** [comment]
👍🏻 release 20.12.5 is currently building!

> greetings from upperaustria !

Greetings from currently gray-skied Graz! 🇦🇹 😁

**Comment by WarpEnterprises** [comment]
It works as expected now! (Apart from #1981, which as you wrote is another thingy).

**Comment by pbek** [comment]
Great, thank you for reporting and testing!
