### ISSUE TITLE
Searching in searchpanel moves focus to the LAST occurence

### ISSUE THREAD

**Issue by WarpEnterprises** [pbek/QOwnNotes#1981]
To reproduce: Create a longer note, "foobar" at the beginning, some lines of text, "foobar" near the end.
Search for "foobar" in the search panel.
The focus moves to the **last** occurence.
When searching with "Find in current note", the focus moves to the **first** occurence, which is what I would expect in both cases.

**Comment by pbek** [comment]
Thank you for your suggestion. I see what you are talking about. Much in the search is depending in the internal functionality of the `QPlainTextEdit` in that case, I put it on my list to see if that can be improved.

**Comment by pbek** [comment]
## 21.1.1
- now the first occurrence of the search term is found first in the note text,
  when searching for notes in the note search panel (instead of the the last
  occurrence)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by WarpEnterprises** [comment]
The search starts from top, this is OK. But the green highlighting now is gone again (#1980).

**Comment by pbek** [comment]
Thank you. I'll see if I can get around that too. 😅

**Comment by pbek** [comment]
## 21.1.2
- now the extra-selections of the search results in the note text are also
  highlighted when searching for notes in the note search panel

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by WarpEnterprises** [comment]
It works perfect 🎶 now!

**Comment by pbek** [comment]
Great, thank you for testing!
It took quite some time to find out the correct workarounds. 😅

**Comment by yunus776** [comment]
> It works perfect 🎶 now!
