### ISSUE TITLE
Please show space characters

### ISSUE THREAD

**Issue by ShuiHuo** [pbek/QOwnNotes#1983]
Don't delete spaces`　　`

[In Chinese writing habits, there will be two spaces at the beginning of each paragraph that are the same size as Chinese characters, which can make the paragraph display more clearly.](https://translate.google.cn/?sl=zh-CN&tl=en&text=在汉语书写习惯中，每个段落的开头都会有两个与汉字相同大小的空格，这能让段落显示更为清晰。)

<details>
    <summary>Original content</summary>

```
### 一、项目集是什么

　　项目集是一系列项目的集合，用于归类项目。

### 二、如何使用

#### 1. 进入项目集

　　具有项目集相关权限的产品和项目管理人员，点击左边的`项目集`链接即可进入项目集界面。

#### 2. 添加项目集

　　在项目集界面右上方找到`添加项目集`链接或在现有项目集的右侧找到`子项目集`链接，点击进入添加项目集界面。填写完相关信息之后点击保存，一个项目集添加好了。
```

</details>

| ✔ | ✘ |
|---|---|
| ![有空格](https://user-images.githubusercontent.com/7471938/101854407-73487f00-3b9c-11eb-93cc-4dbbabd1b3f1.png) | ![没有空格](https://user-images.githubusercontent.com/7471938/101854423-7c395080-3b9c-11eb-9841-f50d7b8ebdee.png) |

**Comment by PurplePlums** [comment]
I shall forward this to our Chinese translator, thank you for letting us know.

**Comment by pbek** [comment]
Can you please explain in more detail and step by step what you did, what happened and what you expected (see issue template).
And can you please post the output from the debug settings (see issue template).

**Comment by ShuiHuo** [comment]
[When I enter a paragraph that starts with two Chinese spaces, I hope to see two spaces (or indentation that occupies the width of two Chinese characters) in the preview interface.](https://translate.google.cn/?sl=zh-CN&tl=en&text=%E5%BD%93%E6%88%91%E8%BE%93%E5%85%A5%E4%B8%A4%E4%B8%AA%E4%B8%AD%E6%96%87%E7%A9%BA%E6%A0%BC%E5%BC%80%E5%A4%B4%E7%9A%84%E6%AE%B5%E8%90%BD%E6%97%B6%EF%BC%8C%E6%88%91%E5%B8%8C%E6%9C%9B%E5%9C%A8%E9%A2%84%E8%A7%88%E7%95%8C%E9%9D%A2%E4%B8%AD%E4%B9%9F%E7%9C%8B%E5%88%B0%E6%9C%89%E4%B8%A4%E4%B8%AA%E7%A9%BA%E6%A0%BC%EF%BC%88%E6%88%96%E5%8D%A0%E6%8D%AE%E4%B8%A4%E4%B8%AA%E6%B1%89%E5%AD%97%E5%AE%BD%E5%BA%A6%E7%9A%84%E7%BC%A9%E8%BF%9B%EF%BC%89%E3%80%82)

#### Expected behaviour

When I enter a paragraph beginning with two Chinese spaces (`　　`), the preview interface also has two spaces.

#### Actual behaviour

The current preview of QOwnNotes will delete the leading spaces.

#### Steps to reproduce

1. Enter a Chinese article in the editing interface.
[There is an article available here](https://pastebin.pl/view/raw/f7e13d4b)

2. Check the preview. Spaces are removed.

3. On the original source page of the article, it uses a two-character indentation.
[Click here to view the page](http://www.gov.cn/zhengce/2020-12/07/content_5567791.htm)

4. Export HTML in QOwnNotes.You can see that the article in the HTML has spaces.

![空格示例](https://user-images.githubusercontent.com/7471938/102027147-3ae3b380-3ddd-11eb-90e4-faf120e87b58.png)

**Comment by pbek** [comment]
> Check the preview. Spaces are removed.

I'm sorry, that's the way Qt's `QTextBrowser` widget renders those characters.
In the html of the preview those characters are still present.

<img width="635" alt="image" src="https://user-images.githubusercontent.com/1798101/102069229-c4a37900-3dfd-11eb-92be-1f5e5649e3d2.png">

You could write a script with the QOwnNotes scripting engine that replaces those characters with `&nbsp;` in the preview.
See: https://www.qownnotes.org/scripting/hooks.html#notetomarkdownhtmlhook

It should look something like this:

```js
import QtQml 2.0

QtObject {
    /**
     * This function is called when the markdown html of a note is generated
     *
     * It allows you to modify this html
     * This is for example called before by the note preview
     *
     * @param {Note} note - the note object
     * @param {string} html - the html that is about to being rendered
     * @param {string} forExport - true if the html is used for an export, false for the preview
     * @return {string} the modified html or an empty string if nothing should be modified
     */
    function noteToMarkdownHtmlHook(note, html, forExport) {
        // see http://doc.qt.io/qt-5/richtext-html-subset.html for a list of
        // supported css styles
        if (!forExport) {
            html = html.replace("　", "&nbsp;");
        }

        return html;
    }
}
```

**Comment by pbek** [comment]
I created a script `Chinese Space Preview` in the script repository. You can install it from there in QOwnNotes.

**Comment by ShuiHuo** [comment]
Chinese Space `　`，code is: `&#x3000;`
`&nbsp;` the width of the space is different from the Chinese space......嘤嘤嘤o(╥﹏╥)o

Temporary use is no problem, at least it is much better than no spaces (or indentation). ╮（╯＿╰）╭
Looking forward to a better solution. n(*≧▽≦*)n

 (ง •_•)ง

**Comment by pbek** [comment]
Like I said, that Chinese space gets ignored by QTextBrowser at the beginning of lines (like normal spaces).
You can play around with the replacing in https://github.com/qownnotes/scripts/blob/master/chinese-space-preview/chinese-space-preview.qml and tell me what works best for you (or make a pull request to the script directly).

**Comment by pbek** [comment]
Additionally you could also file a bug at https://bugreports.qt.io/secure/Dashboard.jspa directly.

**Comment by Waqar144** [comment]
> Additionally you could also file a bug at https://bugreports.qt.io/secure/Dashboard.jspa directly.

Which will likely not be fixed lol

**Comment by Waqar144** [comment]
I wonder what would happen if we Manual put the space in there, would it still get removed? And are we sure that md4c is not the problem here?

**Comment by pbek** [comment]
Well, the correct characters are in the HTML, as far as I remember...
