### ISSUE TITLE
Preview: Empty line when using sublist

### ISSUE THREAD

**Issue by WarpEnterprises** [pbek/QOwnNotes#1984]
A minor flaw: when using sub-lists the last main-list item has an empty line before the sub-items. This is only visible in the preview panel. Exported HTML is fine.

Testinput (the empty line shows up between "three" and "text3"):

```
* one
   - text1
* two
   - text2
* three
   - text3

Break..
```

**Comment by pbek** [comment]
I think you are talking about #1504. Right? 😁

**Comment by WarpEnterprises** [comment]
Grrr, indeed, and I *did* search before 😬

**Comment by pbek** [comment]
I nowadays use `in:title` when searching for issues to get less "noise". 😅
