### ISSUE TITLE
QOwnNotes uses multiple GB of RAM - Increases memory allocation notably as typing in large notes

### ISSUE THREAD

**Issue by polarathene** [pbek/QOwnNotes#1986]
#### Expected behaviour

Not exceeding 1GB of RAM, ideally less than 500MB when just working with plain text?

#### Actual behaviour

Typing in a note with a size of 2k lines, seems to quickly increase memory usage. 

On a new note or similar but smaller note of 100 lines, there is no noticeable increase in RAM.

Presumably some logic is reacting to my typing? (is the whole document being re-processed with each character I type for markdown syntax highlighting or something?)

#### Steps to reproduce

Fresh instance uses about 40MB.

1. Open a note with 2 thousand lines of markdown content (URLs, quotes, bold/italic text, etc).
2. Only panels are note list, folder, search and subfolder. Workspace is "Minimal", just the text input view of the note with markdown styling, no rendered document.
3. Line in note of input does not seem to matter, type out "abcdefghijklmnopqrstuvwxyz".
4. Memory usage has increased over 10MB.
5. Repeat and memory will continue to rise at this rate, eventually you'll reach multi-GB of RAM allocated to QOwnNotes.

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

## General Info

**Current Date**: `Mon Dec 14 16:06:17 2020`
**Version**: `20.12.3`
**Build date**: `Dec  8 2020`
**Build number**: `794`
**Platform**: `linux`
**Operating System**: `Manjaro Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/home/polarathene/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/polarathene/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1440x900`
**Icon theme**: `breath`
**Notes in current note folder**: `306`
**Calendar items**: `0`
**Enabled scripts**: `0`

</details>

---

Is it likely to be [related to Qt as you mentioned here](https://github.com/pbek/QOwnNotes/issues/1646#issuecomment-593062158)?

I have had this issue for quite sometime, perhaps 1-2 years, I've just not bothered to report it and instead opted to close QOwnNotes and open a new instance to free the memory up.

**Comment by pbek** [comment]
I cannot really reproduce that (on KDE Neon). I have lots of large notes (1.5k lines range) and I only manage to get my ram consumption up by a few MB and I also have the preview and the other panel on.
Do you maybe have a note folder to test with that you can share?

@Waqar144, can you reproduce that?

**Comment by polarathene** [comment]
Perhaps it's something else related to my system. I've been running Manjaro on it since late 2018 and been looking at doing a fresh install to a new disk within the next month. 

If I can reproduce the problem on the new install, I'll see if a single note that reproduces it will still reproduce the problem as the only note stored. If I can I'll prepare a more detailed reproduction case to hand over :+1: 

I assume the amount of memory increasing has something to do with whatever QOwnNotes is doing as I type, could it be related to the markdown parsing? Similar to my syntax highlighting perf issue? (which has the opposite issue, syntax highlighting at 12k matches was slow but no memory issues)

**Comment by pbek** [comment]
I dunno. I've Qt 5.15.2 here on my KDE Neon box too... But I neither had this issue on my Manjaro laptop. 😅

**Comment by Waqar144** [comment]
I am running Manjaro but never saw any spikes in memory consumption.

**Comment by pbek** [comment]
I will close this issue until there is more information.
