### ISSUE TITLE
Menus: German Text 

### ISSUE THREAD

**Issue by Fischmuetze** [pbek/QOwnNotes#199]
Suggestions for simplify and unify the texts of the menu entries in the German version. I can't compare the other language versions but I guess there are no essential differences and my suggestions will fit also for other languages.

* Entry text should start always with an uppercase char
* Since it is clear to use a notice app and to enter the "Notizen" menu it isn't necessary to repeat for each entry the word "Notiz". The word can remove which makes the menu entries faster readable.
* Menu "Schlagwort" - the name of the german entry "Notiz oder Schlagwort hinzufügen" might be confusing the user as he can only add keywords (tags) 
  Btw.1 It's unusual that a simple click on tags will remove them (without any question) instead of the expected behavior to edit them 
 Btw.2 Very long "tags" will more or less destroy the usability of the UI 
 I would suggest to split tags automatically by spaces or commas or what ever
* Menu "Bearbeiten"
 Imho the entries:
  - Aktuelle Notiz löschen
 - Notiz Version anzeigen
 - Notiz verschlüsseln 
 have to move to the "Notizen" menu as their context is a general notes context 
* Most entries placed in the "Fenster" menu are placed in the most cases in other apps in a "View"/ "Ansicht" / "Anzeige" menu

**Comment by pbek** [comment]
Thank you for your input, you are free to make suggestions here: <https://crowdin.com/project/qownnotes/invite>

**Comment by Fischmuetze** [comment]
I don't really understand how this works ... it's hard to find corresponding items. But as I saw this is more or less also not a translation issues as the countless repeats of the words like "note" is also noted in other languages

**Comment by pbek** [comment]
Which items do you have troubles finding?

**Comment by Fischmuetze** [comment]
See above: ... "Since it is clear to use a notice app and to enter the "Notizen" menu it isn't necessary to repeat for each entry the word "Notiz". The word can remove which makes the menu entries faster readable."

**Comment by pbek** [comment]
In my opinion it could address a lot of other things beside notes, like note folders, tags, etc..

**Comment by pbek** [comment]
I will close this issue until there is more information.
