### ISSUE TITLE
Is it possible to search for notes text inside them?

### ISSUE THREAD

**Issue by smac89** [pbek/QOwnNotes#1990]
This is more a question. I was wondering if there was any way to search for notes by entering text which the notes may contain.

**Comment by pbek** [comment]
You mean only the note text and not "note text or note name". No, that's not possible, but by default the note name is part of the note so it amounts to the same...

**Comment by smac89** [comment]
No I mean kinda like how `grep` works. Is there a feature within the app that lets me enter a pattern, then all the notes that contain that pattern are reported?

**Comment by pbek** [comment]
Currently these things are possible: https://www.qownnotes.org/getting-started/searching.html

**Comment by pbek** [comment]
I will close this issue until there is more information.
