### ISSUE TITLE
Updateable AppImage using AppImageLauncher

### ISSUE THREAD

**Issue by smac89** [pbek/QOwnNotes#1991]
This is a feature request.

Is it possible to make the AppImage, updateable through AppImageLauncher? The information required is found [here](https://github.com/AppImage/AppImageUpdate#update-information-overview).

Not a deal breaker. I still get notifications in the app to update to the latest, but AppImageLauncher, does not understand that this is an update to the existing application, so I have to first delete the current app, then install the new one.

**Comment by pbek** [comment]
Are those already updatable: https://build.opensuse.org/package/binaries/home:pbek:QOwnNotes/desktop/AppImage?

**Comment by pbek** [comment]
> The information required is found here.

You either seem to have to use cmake or build your app on TravisCI for this to work. Both are not the case for QON. 😬

**Comment by smac89** [comment]
@pbek 
Hmm, I think there might be a problem with those appimages.

The appimages located at `https://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/AppImage/` are very outdated, but otherwise are in fact built to be updatable.

This is the text contained in the About page of that appimage:

```
QOwnNotes - version 20.10.10 - AppImage - build 777
Plain-text file markdown note taking with Nextcloud/ownCloud integration for GNU/Linux, macOS® and Windows® (it is written in C++/Qt®), that works together with the notes application of Nextcloud and ownCloud. 
Built on Oct 27 2020 with Qt 5.6.2.
Copyright 2014-2020 by Patrizio Bekerle
www.qownnotes.org
The program is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. 
Please report issues at the QOwnNotes issue page. 
```

I guess I must have downloaded mine directly from GH-releases, which contains the actual latest, but it doesn't have update information associated with it.

https://github.com/pbek/QOwnNotes/releases

**Comment by smac89** [comment]
Please also note that Github Releases is [supported](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#github-releases) for github releases.

Here is what I ended up doing:

- I downloaded the latest AppImage from gh releases.
- I extract the contents using `./QOwnNotes-x86_64.AppImage --appimage-extract`
- Using appimagetool, I added the following as the update information:
  - `appimagetool ./squashfs-root --updateinformation "gh-releases-zsync|pbek|QOwnNotes|latest|QOwnNotes-x86_64.AppImage.zsync"`
- This created an updateable AppImage, along with the `.zsync` file.

```
➜ appimagetool ./squashfs-root --updateinformation "gh-releases-zsync|pbek|QOwnNotes|latest|QOwnNotes-x86_64.AppImage.zsync"
appimagetool, continuous build (commit 5ae4eae), build <local dev build> built on 2020-12-15 11:56:15 UTC
Using architecture x86_64
/home/chigozirim/Downloads/squashfs-root should be packaged as QOwnNotes-x86_64.AppImage
WARNING: AppStream upstream metadata is missing, please consider creating it
         in usr/share/metainfo/PBE.QOwnNotes.appdata.xml
         Please see https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps
         for more information or use the generator at http://output.jsbin.com/qoqukof.
Generating squashfs...
Parallel mksquashfs: Using 12 processors
Creating 4.0 filesystem on QOwnNotes-x86_64.AppImage, block size 131072.
[==========================================================================================================================================================================================\] 981/981 100%

Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
	compressed data, compressed metadata, compressed fragments,
	compressed xattrs, compressed ids
	duplicates are removed
Filesystem size 40141.46 Kbytes (39.20 Mbytes)
	38.02% of uncompressed filesystem size (105586.96 Kbytes)
Inode table size 5543 bytes (5.41 Kbytes)
	39.29% of uncompressed inode table size (14109 bytes)
Directory table size 3137 bytes (3.06 Kbytes)
	38.44% of uncompressed directory table size (8161 bytes)
Number of duplicate files found 29
Number of inodes 336
Number of files 225
Number of fragments 34
Number of symbolic links  1
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 110
Number of ids (unique uids + gids) 1
Number of uids 1
	root (0)
Number of gids 1
	root (0)
Embedding ELF...
Marking the AppImage as executable...
Embedding MD5 digest
zsyncmake is available and updateinformation is provided, hence generating zsync file
Success

Please consider submitting your AppImage to AppImageHub, the crowd-sourced
central directory of available AppImages, by opening a pull request
at https://github.com/AppImage/appimage.github.io
```
---

My understanding now is that if this `.zsync` file is uploaded to github releases, along with the AppImage, then this will allow the updates to be downloaded when available.

**Comment by pbek** [comment]
> The appimages located at https://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/AppImage/ are very outdated, but otherwise are in fact built to be updateable.

Strange, they should have been built:
https://build.opensuse.org/packages/desktop/job_history/home:pbek:QOwnNotes/AppImage/x86_64

But I created the github ones because I can use a new Qt version there...

> https://github.com/pbek/QOwnNotes/issues/1991#issuecomment-748392822

thank you, I'll take a look into that.

**Comment by smac89** [comment]
Just wanted to bring to your attention that the AppImages at https://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/AppImage/ are still outdated. The _about_ dialog still contains the same text as what I posted [initially](https://github.com/pbek/QOwnNotes/issues/1991#issuecomment-748384418):

```
QOwnNotes - version 20.10.10 - AppImage - build 777
Plain-text file markdown note taking with Nextcloud/ownCloud integration for GNU/Linux, macOS® and Windows® (it is written in C++/Qt®), that works together with the notes application of Nextcloud and ownCloud. 
Built on Oct 27 2020 with Qt 5.6.2.
Copyright 2014-2021 by Patrizio Bekerle
www.qownnotes.org
The program is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. 
Please report issues at the QOwnNotes issue page. 
```

Something must have happened after the Oct 27th release that has caused these AppImages to no longer receive updates

**Comment by pbek** [comment]
For me `QOwnNotes-0-Build1.1.glibc2.16-x86_64.AppImage | 22-Jan-2021 13:40 | 28M` said:

**Version**: `21.1.1`
**Build date**: `Jan  3 2021`

... which also isn't the current one, but it's not 20.10.10.

**Comment by smac89** [comment]
@pbek I use `QOwnNotes-latest-x86_64.AppImage`, which I assumed was pointing to the latest...

It looks like it is even behind the versioned file

**Comment by pbek** [comment]
Like I said, OBS is creating them. I can't control them much. I can only control those: https://github.com/pbek/QOwnNotes/releases

**Comment by pbek** [comment]
https://github.com/pbek/QOwnNotes/issues/2176 might be of interest.
