### ISSUE TITLE
Note gets truncated when decrypting before saved to disk

### ISSUE THREAD

**Issue by WarpEnterprises** [pbek/QOwnNotes#1992]
(well, it's weekend, so time for testing 😉)
**Steps to reproduce:**
Set the autosave intervall to some higher value (e.g. 600sec) so you can actually do the following.
Make a new note (or take an existing one - it does not matter).
Encrypt the note, but _do not save_ to disk.
Decrypt the note. Now it is empty.
This seems a regression introduced between 20.8.8. and 20.8.6.

**Comment by pbek** [comment]
Thank you for reporting.
Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting `Debug` in `Options`).

**Comment by pbek** [comment]
Never mind. Fixed it already. 😅 

## 20.12.8
- fixed an issue with decrypting notes after encrypting for the first time, but never saving them

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by WarpEnterprises** [comment]
Thanks - well done!

**Comment by pbek** [comment]
Great, thank you for testing. 😁
