### ISSUE TITLE
Left window setting is reset on every start / not saved permanently

### ISSUE THREAD

**Issue by bcutter** [pbek/QOwnNotes#1993]
#### Expected behaviour
Set the left window size. On next start of QOwnNotes, it is shown as configured before.

View as configured:
![grafik](https://user-images.githubusercontent.com/13799156/102691068-1edf7800-420a-11eb-812c-6d7316505d30.png)

#### Actual behaviour
On next start of QOwnNotes, the left window size is reset to a completely different size.

View as shown on next start:
![grafik](https://user-images.githubusercontent.com/13799156/102691081-2c94fd80-420a-11eb-9a8f-6958177115bb.png)

#### Steps to reproduce
Set window size. Restart QOwnNotes.

#### Output from the debug section in the settings dialog
I´ll only provide the basic data as the remaining ones contain much private information.

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sa Dez 19 14:55:24 2020`
**Version**: `20.12.5`
**Build date**: `Dec 13 2020`
**Build number**: `796`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\%username%\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\PortableApps\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1680x1050, 1600x900`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `233`
**Calendar items**: `261`
**Enabled scripts**: `1`

</details>

That´s obviously really annoying. I checked if it´s a Windows UAC issue but it´s not: application has full right access to the application folder.

**Comment by pbek** [comment]
Usually this happens when the window is resized by the operating system (or the user) and the central widget is disabled. In that case some panel will get resize (lacking a central widget that will get resized).

![image](https://user-images.githubusercontent.com/1798101/102691568-bc887680-420d-11eb-98a8-f317191e5d5c.png)

**Comment by bcutter** [comment]
Thank you very much! That wasn´t enabled before...

![grafik](https://user-images.githubusercontent.com/13799156/102691735-ea21ef80-420e-11eb-8d1e-bd0a17390356.png)

....now as it is the left panels stay where I want them to. Except for the lower part (same problem, other section and now in vertical alignment):

SHOULD:
![grafik](https://user-images.githubusercontent.com/13799156/102691880-fb1f3080-420f-11eb-9d78-7467ccdab731.png)

IS after restart:
![grafik](https://user-images.githubusercontent.com/13799156/102691884-02ded500-4210-11eb-93c0-7fe8de0c59b7.png)

Is there a magical setting for that issue, too?

**Comment by pbek** [comment]
I cannot make out exactly what you are talking about, a larger screenshot would be easier to comprehend. But not all panel placements are possible with a central widget, see https://doc.qt.io/qt-5/qmainwindow.html#qt-main-window-framework.

**Comment by bcutter** [comment]
OK, in words: the lower left panel (notes list / navigation) is lowered on restart. It should stay right below the upper left panel (notes folder).

**Comment by pbek** [comment]
What is "lower"? All panels can be placed nearly everywhere. 😅  Don't you have a screenshot? But most likely it's a restriction of when the central widget is enabled.

**Comment by bcutter** [comment]
Oh dear, how to explain better than I already did :-)

I want to avoid the current behaviour that the other panels on the left - as you can see in https://github.com/pbek/QOwnNotes/issues/1993#issuecomment-748482900 are moved when restarting QOwnNotes. How to do this? It´s a bug, not a feature, right? ;-)

**Comment by pbek** [comment]
You still didn't provide a screenshot of your full screen 😀 
Did you try dragging the panels to where you like?

**Comment by bcutter** [comment]
> 
> 
> You still didn't provide a screenshot of your full screen 😀

It´s not necessary for this issue. The relevant sections are in the screenshots above.

> Did you try dragging the panels to where you like?

That´s not the problem. The problem is they DON`T STAY where they should as soon as QOwnNotes got restarted.

You now got me? :-)

**Comment by bcutter** [comment]
In other words: how to fix (make it sticky) this part of the UI?

![grafik](https://user-images.githubusercontent.com/13799156/103040294-43718200-4573-11eb-98cd-76e77c6545e7.png)

It´s shifted to somewhere else on every restart.

**Comment by bcutter** [comment]
No solution? Last question from around X-Mas unanswered 😕🤷‍♂️

**Comment by pbek** [comment]
> You still didn't provide a screenshot of your full screen

And I'm still not sure what your issue is, maybe you can record a video.

**Comment by bcutter** [comment]
Not sure how to blur all personal information of a recorded video. Will think about a fake notes storage to provide a proper issue demonstration.
