### ISSUE TITLE
Bizzare Nextcloud Server-"Error": Invalid query, though all is markes as OK

### ISSUE THREAD

**Issue by Lumberjacker** [pbek/QOwnNotes#1996]
Hi,

I`m running a Nextcloud-Server (self-hosted), latest stable Server/Client version, several services running. Works flawless, all applications act as they should - apart from QOwnNotes. I`m using the portable Version, Nextcloud Client always running, API is installed and running. I`ve inserted all requiered Information into QOwnnotes-Form to establish the connection. Everything comes back as tested and marked as "OK" (see screenshot). So far, so good.

![querror1](https://user-images.githubusercontent.com/76580547/103226353-30bccb80-492c-11eb-9181-952a0587e650.png)

But when I press "OK" nothing happens for a few seconds until an error-window comes up (second screenshot). 

![querror2](https://user-images.githubusercontent.com/76580547/103226394-4b8f4000-492c-11eb-8de6-38fc1d4a3533.png)

When I press "Go to Settings", there are no errors indicated, all Tests are passed with OK-Results. When I press OK, the loop starts again till the End of all Time. Anybody an idea, how to solve this problem? Joplin e.g. works perfect, so do all other applications I`m using.

**Comment by pbek** [comment]
Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting `Debug` in `Options`).

**Comment by pbek** [comment]
I will close this issue until there is more information.
