### ISSUE TITLE
Question. Bookmarks in PDF

### ISSUE THREAD

**Issue by xcme** [pbek/QOwnNotes#1997]
Hi! Is there a way to add existing headers as bookmarks in exported PDF file to provide clickable content page? Some of my PDF-books have it and I tried to find similar functionality in QON but it seems it doesn't have this option yet

**Comment by pbek** [comment]
With the help of the scripting engine you can implement everything you like: https://www.qownnotes.org/scripting/hooks.html#notetomarkdownhtmlhook

In the script repository there is a script `Insert Table of Contents (TOC)`, you can try (or modify) that too.
