### ISSUE TITLE
Question. How to synchronize edit and preview panels?

### ISSUE THREAD

**Issue by xcme** [pbek/QOwnNotes#1998]
When I use QON with two panels they aren't synchronized. Sometimes I have the same line at the top in Edit panel and at the bottom in Preview panel. It would be great to have more synchronized view. How to achieve this?

Thanks.

I using QOwnNotes - version 20.12.9 - GitHub Actions - build 800

**Comment by pbek** [comment]
Do you have a screenshot / video to more explain what we are talking about?

**Comment by xcme** [comment]
![image](https://user-images.githubusercontent.com/10675508/103307724-127ccb80-4a11-11eb-8ad1-7047bf547e4c.png)

I just copied some text from markdown page from documentation. At the screen you can see there is two lines shift between editor and preview with the same panels height. And sometimes this discrepancy is much larger, and sometimes there is no difference at all. It may happen because preview panel add some empty lines and this is the reason of the shift, but it would be better to synchronize panels for the first line, wouldn't it?

**Comment by pbek** [comment]
There is no way to sync that 100% since text-size and size in the preview can differ vastly. The scrollbars positions (in percent) are just "synced".

**Comment by pbek** [comment]
If you see a way... Pull requests are welcome! 😁
