### ISSUE TITLE
dependency nvidia-331

### ISSUE THREAD

**Issue by gityeti** [pbek/QOwnNotes#2]
Hello, thanks for your work, QOwnNotes_0.15_amd64.deb works fine for me. 
Tried QOwnNotes_0.22_amd64.deb, but I can't install it because of dependency problem (nvidia-331 not installed).
 # dpkg -i QOwnNotes_0.22_amd64.deb 
Sélection du paquet qownnotes précédemment désélectionné.
(Lecture de la base de données... 259483 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de QOwnNotes_0.22_amd64.deb ...
Dépaquetage de qownnotes (0.22) ...
dpkg: des problèmes de dépendances empêchent la configuration de qownnotes :
 qownnotes dépend de nvidia-331 ; cependant :
  Le paquet nvidia-331 n'est pas installé.
 # apt-get install --simulate nvidia-331
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
Package nvidia-331 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'nvidia-331' has no installation candidate

I'm using debian testing... Thanks for your help!

**Comment by pbek** [comment]
Hm, it should work without it. I now removed it from the package and tested it in an Ubuntu 14.04 VM.
Can you please try the latest linux package and report to me if it works: <http://www.bekerle.com/content/download/73/353/version/15/file/QOwnNotes_0.22.1_amd64.deb>

Thank you very much for your feedback!

**Comment by gityeti** [comment]
Thank you for your fast answer. I could install the package 0.22.1 without any problem.
When I start QOwnNotes, it opens the window correctly. But if I try to write something in an existing note, or if I try to create a new note, the window closes immediatly. This is the output:
$ QOwnNotes
QOwnNotes: symbol lookup error: QOwnNotes: undefined symbol: _ZN6QDebugD1Ev
Is there a debug option to get more information?
$ dpkg -l qownnotes*
||/ Nom            Version   Architecture        Description
+++-=========================-=================-=================-===========
ii  qownnotes   0.22        amd64                QOwnNotes is the open source notepad, that works togethe

**Comment by gityeti** [comment]
Thank you for your fast answer. I could install the package 0.22.1 without any problem.
When I start QOwnNotes, it opens the window correctly. But if I try to write something in an existing note, or if I try to create a new note, the window closes immediatly. This is the output:
$ QOwnNotes
QOwnNotes: symbol lookup error: QOwnNotes: undefined symbol: _ZN6QDebugD1Ev
Is there a debug option to get more information?
$ dpkg -l qownnotes*
||/ Nom Version Architecture Description
+++-=========================-=================-=================-===========
ii qownnotes 0.22 amd64 QOwnNotes is the open source notepad, that works togethe
(I was surprised because of 0.22, but I installed the right one 0.22.1 - it's not writen in the description of the package...)

**Comment by pbek** [comment]
I thought I got all those debug symbols out. Linux deployment is a hell. I will work some more on it, thanks a lot for reporting!
PS: 0.22.1 is just 0.22 minus the nvidia package dependency

**Comment by pbek** [comment]
I now did a clean build which resulted in the extinction of the debug-symbols. It also worked on my test-VM. Can you please try again with:
http://www.bekerle.com/content/download/73/353/version/16/file/QOwnNotes_0.22.2_amd64.deb

Thanks a lot for your patience!

**Comment by gityeti** [comment]
Servus Patrizio,
diesmal hat's geklappt, this time (version 0.22.2) it works fine!
Thank you, great job, and very usefull.

**Comment by pbek** [comment]
Makes me happy! :) Thank you for your kind words and your patience. Have a great day!

**Comment by mckaygerhard** [comment]
i wish toprovide packages for diferents flavors of debian (and not winbuntu)...

but i ask.. this app will compile wioth qt4 4.6.3?

**Comment by pbek** [comment]
Which distribution runs exactly that version? Did you try checking out the code and firing up "qmake"?
