### ISSUE TITLE
Support Github Flavored markdown tables

### ISSUE THREAD

**Issue by LEDfan** [pbek/QOwnNotes#20]
Hi, I really like your app, and I just miss one feature.

In Github Flavored markdown you can use tables without creating them in HTML:
````
column | column
--- | ---
value | value
````
Becomes:
column | column
--- | ---
value | value

However this doesn’t work with your app. Can you add this?

Thanks

**Comment by pbek** [comment]
Hi, @LEDfan 

Thank you for your report!
QOwnNotes uses <https://github.com/hoedown/hoedown> for generating the HTML, We have to see what we can do.

**Comment by pbek** [comment]
Tables are working now in QOwnNotes v0.59 (check the webpage in 10min). Have a great day!
