### ISSUE TITLE
Dropdown menu when typing links

### ISSUE THREAD

**Issue by capcionista** [pbek/QOwnNotes#200]
A suggestion for a rather advanced feature: When typing links, it would be great to have open a dropdown menu under the cursor: e.g. when I start typing <note://win, a dropdown menu with about 5 notes starting with "win", e.g. "windows error nr x" or "windows error Nr z" ... Using my arrow keys, I can navigate through the list and choose the note name I am looking for.

This would allow users to work completely without their mouse (which usually interrupts your writing) while still feeling safe to create functioning links. When you have several hundred notes, you're probably aware of the approximate names, but not their exact title - you don't know for sure whether it's windows error nr x" or "windows error Nr x" or "windows error Nr: x".

**Comment by pbek** [comment]
Thank you for your suggestion. May I ask why you don't just press `Ctrl + L` (or `Cmd + L`)?

**Comment by capcionista** [comment]
I didn't think of it. Considering this I would primarily suggest to combine the two fields in the opening window (add link vs. type to search note) to one field, so you don't have to press TAB to start searching. The fields could be combine to one "search for notes and if no result [which will be almost always the case when I type e.g. an Internet link] take the input as link not to a note, but to a website/directory... whatever (analogous to the main search field which is also used for new note creation if the input doesn't match any note title.)

Reducing it to one single window and a dropdown menu would make it neater and smother by reducing distractions, but the Ctrl L seems sufficient to me overall.

**Comment by pbek** [comment]
With your suggestion you would have to type `<note://`... 😸

**Comment by pbek** [comment]
But I will implement the complex searches in note link menu...

**Comment by pbek** [comment]
On 2nd glance I think that searching for more than the name in that dialog might be confusing.
