### ISSUE TITLE
[F] Add Tags with a list

### ISSUE THREAD

**Issue by athrouss** [pbek/QOwnNotes#2000]
#### Expected behaviour

When I want to add a tag in a note I have to push the Add Tag button on the bottom left. Then I have to write the tag name even when the tag exists.

#### Actual behaviour

When pushing the Add Tag button use a Combo Box (with add new option) with the existing tags as to be able to select from the list, instead of writing again by hand.

#### Steps to reproduce

Add a new tag

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Τετ Δεκ 30 20:47:22 2020`
**Version**: `20.12.9`
**Build date**: `Dec 22 2020`
**Build number**: `800`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\athrouss\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\bin\QOwnNotes.exe`, `--after-update`, `C:\Users\athrouss\AppData\Local\Temp\QOwnNotes-xTaBxi-updater.bat`
**Qt Debug**: `0`
**Locale (system)**: `el_GR`
**Locale (interface)**: `el`
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1280x1024`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `29`
**Calendar items**: `104`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://roussoscloud.ddns.net`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `16.0.5.1`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\athrouss\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `προκαθορισμένο`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `D:\Documents\Nextcloud\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `Σπίτι`
**database file**: `D:\Documents\Nextcloud\Notes\notes.sqlite`

### Cloud connection `Προκαθορισμένο`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://roussoscloud.ddns.net`
**username**: `athrouss`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (int): `21`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-12-30T20:32:58.724`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Tahoma,10,-1,5,50,0,0,0,0,0,Κανονικά`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Tahoma,11,-1,5,50,0,0,0,0,0,Κανονικά`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**NoteFolder-1/NoteTabNameList** (QStringList): `Ψώνια,   __Τροχόσπιτο ψώνια__  `
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `τροχόσπιτο, τροχόσπιτο`
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 24 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `23`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (int): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Προσωπικά`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**VersionDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `false`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): `el`
**internalIconTheme** (QString): `false`
**itemHeight** (int): `15`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `D:/Documents/Nextcloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Σχολείο, Αυτοκίνητο, Προσωπικά, Personal`
**ownCloud/todoCalendarEnabledList** (QStringList): `Σχολείο, Αυτοκίνητο, Προσωπικά, Personal`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://roussoscloud.ddns.net/remote.php/dav/calendars/athrouss/test/, https://roussoscloud.ddns.net/remote.php/dav/calendars/athrouss/car/, https://roussoscloud.ddns.net/remote.php/dav/calendars/athrouss/personal/, https://roussoscloud.ddns.net/remote.php/dav/calendars/athrouss/personal-1/`
**ownCloud/todoCalendarUrlList** (QStringList): `https://roussoscloud.ddns.net/remote.php/dav/calendars/athrouss/test/, https://roussoscloud.ddns.net/remote.php/dav/calendars/athrouss/car/, https://roussoscloud.ddns.net/remote.php/dav/calendars/athrouss/personal/, https://roussoscloud.ddns.net/remote.php/dav/calendars/athrouss/personal-1/`
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `16.0.5.1`
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2019-11-09T10.37.29, Note 2019-09-14T10.19.54`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `κύρια γραμμή εργαλείων`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `γραμμή εργαλείων μορφοποίησης`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `εισάγοντας τη γραμμή εργαλείων`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `γραμμή εργαλείων κρυπτογράφησης`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `γραμμή εργαλείων παραθύρων`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `κλείστε τη γραμμή εργαλείων`
**toolbar/size** (int): `6`
**useSoftWrapInNoteEditor** (QString): `true`
**useUNIXNewline** (QString): `false`
**versionSplitterSizes** (QByteArray): `<binary data>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Ελάχιστη`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\athrouss\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `THANOS-PC`
**ComSpec**: `C:\Windows\system32\cmd.exe`
**destination**: `C:\bin`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\athrouss`
**JAVA_HOME**: `C:\Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25`
**LOCALAPPDATA**: `C:\Users\athrouss\AppData\Local`
**LOGONSERVER**: `\\THANOS-PC`
**NUMBER_OF_PROCESSORS**: `16`
**OneDrive**: `E:\Ergasies\SkyDrive`
**OneDriveConsumer**: `E:\Ergasies\SkyDrive`
**OS**: `Windows_NT`
**Path**: `D:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Embarcadero\Studio\20.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\20.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl\Win64;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GTK2-Runtime\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\Common Files\Acronis\VirtualFile\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile64\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;D:\Program Files\PuTTY\;C:\Program Files (x86)\dotnet\;C:\Users\athrouss\AppData\Local\Microsoft\WindowsApps;C:\Program Files\OpenVPN\bin;C:\Users\athrouss\.dotnet\tools;C:\Users\athrouss\.dotnet\tools;C:\Users\athrouss\AppData\Local\Microsoft\WindowsApps;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD`
**PROCESSOR_LEVEL**: `23`
**PROCESSOR_REVISION**: `7100`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PROMPT**: `$P$G`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**qownnotesCommand**: `C:\bin\QOwnNotes.exe --after-update C:\Users\athrouss\AppData\Local\Temp\QOwnNotes-xTaBxi-updater.bat `
**SESSIONNAME**: `Console`
**source**: `C:\Users\athrouss\AppData\Local\Temp\QOwnNotes-xTaBxi.zip`
**SystemDrive**: `C:`
**SystemRoot**: `C:\Windows`
**TEMP**: `C:\Users\athrouss\AppData\Local\Temp`
**TMP**: `C:\Users\athrouss\AppData\Local\Temp`
**unzipCommand**: `C:\Users\athrouss\AppData\Local\Temp\QOwnNotes-xTaBxi-unzip.exe -o C:\Users\athrouss\AppData\Local\Temp\QOwnNotes-xTaBxi.zip -d C:\bin`
**unzipExecutable**: `C:\Users\athrouss\AppData\Local\Temp\QOwnNotes-xTaBxi-unzip.exe`
**USERDOMAIN**: `THANOS-PC`
**USERDOMAIN_ROAMINGPROFILE**: `THANOS-PC`
**USERNAME**: `athrouss`
**USERPROFILE**: `C:\Users\athrouss`
**windir**: `C:\Windows`
**__COMPAT_LAYER**: `DetectorsAppHealth`
</details>

**Comment by pbek** [comment]
> Expected behaviour

> When I want to add a tag in a note I have to push the Add Tag button on the bottom left. Then I have to write the tag name even when the tag exists.

This is what you want? I'm not sure if I understand that correctly...

**Comment by pbek** [comment]
The most common ways to add tags to a note are:

1) Using the `Add tag` button, type something in, use the autocomplete
2) Search and double click on the tag in the tag tree

Plus you can use the scripting engine to add tags in any way you like.

**Comment by athrouss** [comment]
No,

My mistake. The opposite.

When we push the Add Tag button a ComboBox (with style DropDown) will pop up and the list will contain the tags that already exist. 

Then the user can select either from the list a tag or write a new one in the white field of the ComboBox.

 

Sorry for the confusion

Best Regards

Thanasis

**Comment by athrouss** [comment]
Ok,

Now I saw the double click case which is useful.

 

Thanks

**Comment by pbek** [comment]
Ok, then 2) might be your thing. 😁  I'll close this then.
