### ISSUE TITLE
Encryption for the whole database

### ISSUE THREAD

**Issue by so-ri** [pbek/QOwnNotes#2003]
Hi there!

I like QOwnNotes very much for its clean interface and easy handling. I know that you can encrypt individual notes; however, I would love it if it were possible to encrypt the whole database with a password. Besides the increased privacy, this would even make QOwnNotes usable as a password manager.

**Comment by pbek** [comment]
There is no database, just a bunch of markdown files. But you can encrypt your note folder with any 3rd party folder encryption you like.
Don't use QON as password manager. 😁  There are far better tools for that, like KeePassX, also free open source and the password database is well encrypted.
