### ISSUE TITLE
Searching notes - Display markdown heading one, not filename

### ISSUE THREAD

**Issue by cavo789** [pbek/QOwnNotes#2004]
Hello QOwnNotes

#### Expected behaviour

Is there any settings that allow to change how search results is displayed?

I'm using QOwnNotes with markdown files. By searching for a keyword, the search results window is displaying the name of files where that keyword is retrieved and that's great and fast but all I get is `readme.md` severall time...

Why? Because I'm creating a lot of folders (`home`, `work`, ...) and then subfolders and finally, in my last subfolders, I put a file called `readme.md`, exactly the same way of using if I'm creating a `wiki` on my hard disk.

So, the majority of my notes are called `readme.md`.

I need to click on all result to see his content and, oh no, not that file, and try with the next one.

So, my question is: is there a way to change how results are displayed? Best would be to extract the heading one (`# My super title`) from the note's content and display that heading and not the filename; do you think it is possible?

I fully understand it's very specific to how I use notes.

Thanks!

#### Actual behaviour

![readme](https://user-images.githubusercontent.com/355999/103454221-23b02b80-4ce2-11eb-92a7-cce0272dd4ba.png)

**Comment by pbek** [comment]
1) You could choose to also show a preview in the note list (Panels settings).
2) You could use https://www.qownnotes.org/scripting/hooks.html#handlenotenamehook to customize what is used as note name (I hope this doesn't have other implications as well).

**Comment by cavo789** [comment]
Many thanks Patrizio for the very fast answer.

I've choose for simplicity and enable showing a preview. There is something *strange* for me:

![2021-01-04_22h09_43](https://user-images.githubusercontent.com/355999/103579969-a0592a80-4ed9-11eb-9299-9e53f4d5e89f.png)

As you can see in the list of notes (bottom left), I didn't see the first line (top right) i.e. `# Bosch` which is my heading one title.

That title is very usefull of course and is the first line of my file.

Did you know why the preview isn't showing that line?

Thanks!

**Comment by pbek** [comment]
Currently the headlines are removed because they are by default the same as the note name.

**Comment by pbek** [comment]
## 21.1.2
- show main heading in the experimental note list preview if the heading is
  allowed to be different than the note name in the current note folder

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by cavo789** [comment]
WOW! INCREDIBLE! So fast, many thanks.

Right now, QOwnNotes didn't find any new release (last one is `21.1.1`), I'll try to understand how to get `21.1.2` and let you know.

**Comment by cavo789** [comment]
Should I enable something? 

Last version installed, I've quit the program twice; switch back to the English version, quit once more and no, no change in the result list

![2021-01-04_22h58_02](https://user-images.githubusercontent.com/355999/103583650-5fb0df80-4ee0-11eb-9483-a977f2fc9c8c.png)

**Comment by pbek** [comment]
I can see a `# Bosch` in the note list preview, bottom left of your screenshot.

**Comment by cavo789** [comment]
Ouch! sorry, my eyes was on the line in bold (i.e. the filename, readme here). Not see the line below.

**You're right!** The line is there; my question is well answered.

Thanks!

**Comment by pbek** [comment]
👍🏻 😉
