### ISSUE TITLE
[F] Add option to sync with WebDav server

### ISSUE THREAD

**Issue by 38569459** [pbek/QOwnNotes#2006]
#### Expected behaviour

Have option to sync with WebDav server.

#### Actual behaviour

Only have option to sync with NextCloud/OwnCloud server.

#### Steps to reproduce

Open Settings, there is no option for WebDav server.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sun Jan 3 15:16:18 2021`
**Version**: `21.1.0`
**Build date**: `Jan  3 2021`
**Build number**: `801`
**Platform**: `linux`
**Operating System**: `Arch Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/home/***/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/***/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `hicolor`
**Notes in current note folder**: `2`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/home/***/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/***/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/***/Nextcloud/Notes/notes.sqlite`

## Settings

**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/removeTrailingSpaces** (bool): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-01-03T15:11:36.884`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,13,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Sans Serif,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Sans Serif,9,-1,5,50,0,0,0,0,0`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**NoteFolder-1/NoteTabNameList** (QStringList): `Welcome to QOwnNotes`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteHistory-1** (QVariantList): `<variant list with 2 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `1`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/notificationShown** (bool): `true`
**checkSpelling** (bool): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**darkMode** (bool): `false`
**demoNotesCreated** (bool): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**dockWasInitializedOnce** (bool): `true`
**guiFirstRunInit** (bool): `true`
**initialLayoutIdentifier** (QString): `minimal`
**itemHeight** (int): `15`
**markdownHighlightingEnabled** (bool): `true`
**noteEditIsCentralWidget** (QString): `true`
**notesPath** (QString): `/home/william/Nextcloud/Notes`
**ownCloud/supportEnabled** (bool): `false`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**SHELL**: `/bin/bash`
**WINDOWID**: `192937988`
**COLORTERM**: `truecolor`
**GTK_IM_MODULE**: `fcitx`
**I3SOCK**: `/run/user/1000/i3/ipc-socket.647`
**XDG_CONFIG_HOME**: `/home/***/.config`
**XMODIFIERS**: `@im=fcitx`
**LIBVA_DRIVER_NAME**: `iHD`
**GPG_TTY**: `/dev/pts/13`
**EDITOR**: `vim`
**XDG_SEAT**: `seat0`
**PWD**: `/home/***/AUR/qownnotes`
**LOGNAME**: `***`
**XDG_SESSION_TYPE**: `tty`
**XAUTHORITY**: `/home/***/.Xauthority`
**WINDOWPATH**: `1`
**MOTD_SHOWN**: `pam`
**HOME**: `/home/***`
**LANG**: `en_US.UTF-8`
**INVOCATION_ID**: `e06af77ca439478e912630bc0d1e7810`
**DOCKER_BUILDKIT**: `1`
**XDG_SESSION_CLASS**: `user`
**TERM**: `***`
**USER**: `***`
**DISPLAY**: `:0`
**SHLVL**: `3`
**PAGER**: `most`
**QT_IM_MODULE**: `fcitx`
**XDG_VTNR**: `1`
**XDG_SESSION_ID**: `1`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**JOURNAL_STREAM**: `8:14210`
**PATH**: 
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**_**: `/usr/bin/QOwnNotes`
**OLDPWD**: `/home/***/AUR`
</details>

**Comment by pbek** [comment]
I'm sorry, but there is no syncing at all in QOwnNotes. 😁 
See: https://www.qownnotes.org/getting-started/concept.html

**Comment by mateMathieu** [comment]
That is too bad... I would love to use it that way.
Making the nextcloud sync mandatory makes the usage conditioned by that. 
Hope you would be able to add this stack soon.
Best

**Comment by pbek** [comment]
You don't need Nextcloud. Like I said, there is no syncing in QON. You can use any tool you like to sync your note files.
https://www.qownnotes.org/getting-started/concept.html#nextcloud-desktop-sync-client

There are plenty ways to sync files via webdav or even mount a webdav folder directly via fuse.

**Comment by mateMathieu** [comment]
Ok, thanks for the heads up. It just requires more work to make it work.

**Comment by pbek** [comment]
👍🏻
