### ISSUE TITLE
[F] Add option to automatically switch between workspace layouts depending on window size

### ISSUE THREAD

**Issue by fnkabit** [pbek/QOwnNotes#2007]
I would like to be able to specify that below a certain window size, use layout x, above that window size, use layout y.
For example, my use case:
* when I use QON windowed I like to use it in a **Minimal** layout, where I can only edit (others may prefer to see only the **Preview Pane** when windowed, though)
* when I maximize the window, I want to switch to **Full** layout, where I can also see the **Preview Pane**

**Comment by pbek** [comment]
Sounds like you want to implement:

- a hook that is called when the windows size / state changes
- a scripting function to switch between workspaces

**Comment by fnkabit** [comment]
> Sounds like you want to implement:
> 
> * a hook that is called when the windows size / state changes
> * a scripting function to switch between workspaces

Yes, I think so :)
Do you think it would be useful ? Can I work on it ?
Thanks !

**Comment by pbek** [comment]
Sure and sure. 😁  It would be even better if you then also write a script that allows users to switch between two workspaces in maximized / non-maximized mode.

I guess it would be great if the hook would recognize all kind of layout changes. Moving, resizing, minimizing, maximizing, full-screen, ... And also coordinates and size as parameter (or a way to fetch them).

**Comment by fnkabit** [comment]
@pbek Will start working on it ASAP.

**Comment by pbek** [comment]
Most excellent! 👍🏻

**Comment by fnkabit** [comment]
Created PR to implement a basic version of this..

**Comment by fnkabit** [comment]
Will update docs once you agree on API changes. :-)

**Comment by pbek** [comment]
I added my 2c. 😉

**Comment by pbek** [comment]
Ok, all mopping up is done 😆:

## 21.1.3
- there now are new scripting commands `mainWindow.getWorkspaceUuidList()`,
  `mainWindow.getWorkspaceUuid()` and `mainWindow.setCurrentWorkspace()` to
  access workspaces and a new hook `windowStateChangedHook` to notice window
  state changes (for [#2007](https://github.com/pbek/QOwnNotes/issues/2007), thank you @fnkabit)
  - for more information please take a look at the
    [MainWindow scripting documentation](https://www.qownnotes.org/scripting/classes.html#mainwindow)
    and the [Hook scripting documentation](https://www.qownnotes.org/scripting/hooks.html#windowstatechangedhook)
  - there also is a new script `Dynamic Workspace` in the script repository that
    you can use to toggle workspaces when you maximize the window
    
There now is a new release, could you please test it and report if it works for you?

**Comment by fnkabit** [comment]
It works. Thanks for all the reviews @pbek  !

**Comment by pbek** [comment]
Great, thank you for the nice addition and for testing! 😁
