### ISSUE TITLE
Feature: button to write name of the file as the title inside the file

### ISSUE THREAD

**Issue by giovi321** [pbek/QOwnNotes#201]
I am using a text editing app on my android device to edit the notes, which are then synced via webdav. What is annoying is that this app (and all the other apps for editing notes in files) writes the title in the name of the file but not inside the file itself like in qownnotes.
It would be useful in my opinion to add a button in QOwnNotes that simply takes the name of the file and adds it as a title in the file itseld (together with the "======" that normally appears when a new note is created).

**Comment by pbek** [comment]
Thank you for your suggestion, sounds like a good idea.

Note that there also is an option in QOwnNotes to set filenames yourself and don't automatically use the headline as filename, in case you want it the other way around...

**Comment by giovi321** [comment]
Great! I think that the default option is great: QOwnNotes names the 
files for me, I just write the title in the same field as where the note 
is written. Saves me one click!

On 09/06/2016 22:27, Patrizio Bekerle wrote:
>
> Thank you for your suggestion, sounds like a good idea.
>
> Note that there also is an option in QOwnNotes to set filenames 
> yourself and don't automatically use the headline as filename, in case 
> you want it the other way around...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/pbek/QOwnNotes/issues/201#issuecomment-225015984>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AGJR-9sM0iV7jdAHH0FFEzs62z3M36hiks5qKHcqgaJpZM4IyXNi>.
>

-- 
Giovanni Crapelli

**Comment by pbek** [comment]
Exactly, it's what the ownCloud Notes app does... I wasn't aware that MyOwnNotes for Android doesn't do that or don't you use ownCloud?

**Comment by giovi321** [comment]
I used to use it on my old device. Now on my new device it requires to 
install the certificate on the device itself, but this procedure 
disables the fingerprint reader as a safety measure (I should root the 
device). Moreover MyOwnNotes sometimes doesn't save the notes if there 
is no connection available. It does not sync the notes in the 
background, so if you get on a plane you don't have your notes updated 
(unless you opened the app before).

I am using Denkzettel together with FolderSync to manage the notes.


On 09/06/2016 22:41, Patrizio Bekerle wrote:
>
> Exactly, it's what the ownCloud Notes app does... I wasn't aware that 
> MyOwnNotes for Android doesn't do that or don't you use ownCloud?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/pbek/QOwnNotes/issues/201#issuecomment-225019931>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AGJR-6eRCxaS-oXRQD4jEKHLYoUEexYuks5qKHqXgaJpZM4IyXNi>.
>

-- 
Giovanni Crapelli

**Comment by pbek** [comment]
And what sync backend do you use for FolderSync? WebDAV from an ownCloud server?

**Comment by pbek** [comment]
for v16.06.3
- <kbd>Ctrl</kbd> + <kbd>⇧</kbd> + <kbd>H</kbd> now inserts a headline from
  the note filename at the top of the note

**Comment by giovi321** [comment]
I use ownCloud's webdav.
Thank you for implementing my suggestion!

**Comment by Maboroshy** [comment]
Could you implement a scripting function to do the same thing - add some vars to the first line, end or other parts of note text.

I've put on the wiki those crazy shell scripts to make parallel dir structure based on tags which parse file names. But I thought I can as easily make it so it wont affect note names - with hidden text like 
`[tag]: # (Tag1) (Tag2)`

I've tried to adapt the example script with no luck. Looks like it returns stuff only to file name.

**Comment by pbek** [comment]
I think I fail to grasp what you are trying to achieve.

**Comment by Maboroshy** [comment]
I'll try to be more specific (than usual :laughing:):
1) I use the example script which appends the tags to file name like [Tag]. 
2) It works very well but it changes note names shown on QOwnNotes. Which is "ok" but not a desired behaviour.
3) I use shell script which parses file names for [Tag] and make some actions based on it.
4) This shell script can parse any text so I don't really need to get [Tag] specifically from file names. I could get it from the first line of note text (with first line != name option on). So it won't be needed to alter note names.
5) There is a trick for the text which won't be rendered by markdown. `[tag]: # (Tag1) (Tag2)` won't be rendered.
6) To make it work I need to make tag-to-name example script to write [Tag] not to file name but to the first line of note.

**Comment by pbek** [comment]
Thank you for being more specific, but I still fail to see what you need :)
Maybe you can help me by forming a "user story" like:

As Maboroshy I want to ..... so that I can .....

**Comment by Maboroshy** [comment]
I want the in-app script function that would put tags to the first line of note text on note save. So I can parse the first line of note files for tags and use that data in a shell script.

Maybe that can be already done with the script. Like returning noteText instead of fileName as in example. 
Adjusting var logic and putting `return noteText` to the end didn't worked out for me. But I'm still close to zero in programming.

**Comment by pbek** [comment]
Hmmm, modifying notes on note store might cause and infinite loop of triggering and note note storing, because modifying a note triggers a note store again...

**Comment by Maboroshy** [comment]
Loop can be reduced to 2 runs if there is a "if" checks in the beginning of the script. Like
1) If the first line of the note begins with "[tag]:" and already have all tags assigned to note - stop script;
2) If the first line of the note begins with "[tag]:" but doesn't have all tags - rewrite it with new "[tag]: (...) \n" line.
3) If the first line doesn't begin with "[tag]:" insert line "[tag]: (...) \n" to the beginning so first line will become the second one.

**Comment by pbek** [comment]
I don't think that will work that way. :smile: 

Button: There now is a new release, could you please test it and report if the new feature work for you?

**Comment by Maboroshy** [comment]
What can go wrong?

**Comment by pbek** [comment]
You are suggesting to add some dirty hacks to QOwnNotes.... :)

**Comment by Maboroshy** [comment]
Dirty Hacks!? In the QOwnNotes I use!? No way! :) 

I do agree that maybe it's bad practice to implement functions that will loop unless something around them stop that loop. 

Looks like the bad part is my proposal is "on note save". Most of other hooks won't make the loop. Can it be hooked to "note.tagNames" change? As far as I remember changing tags is not considered as note change by app.

**Comment by pbek** [comment]
Anything that modifies the current note in the background will be problematic...

**Comment by Maboroshy** [comment]
I've already started to think how to get the data out of .sqlite to feed to shell script and started laughing like an evil genius. But hell with. You're right. Or I'll end up with a twisted bash driven note app of myself. The tag-to-name script does everything necessary. I'll better put energy into scripting kind of web clipper for the app.

**Comment by pbek** [comment]
Or you install Qt Creator and start working on QOwnNotes directly. ;)

**Comment by Maboroshy** [comment]
I'll check if there is "bash -> QML" on google translate. :D

**Comment by pbek** [comment]
one small step at a time...
