### ISSUE TITLE
Make Return key handle identical to Enter key in markdown editor

### ISSUE THREAD

**Issue by fnkabit** [pbek/QOwnNotes#2013]
I would like to have the Return key handle identical to the Enter key in the markdown editor.
Currently, the Enter key is 'ignored' in things like automatically adding the next bullet point.

**Comment by pbek** [comment]
Sounds like a great idea! Do you want to work on that?

**Comment by fnkabit** [comment]
Created a PR, will create PR for updating submodule once that's in.

**Comment by pbek** [comment]
## 21.1.4
- the `Return` key will now be handled the same as the `Enter` key in the note text edit
  for things like automatically creating list items (for [#2013](https://github.com/pbek/QOwnNotes/issues/2013), thank you @fnkabit)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by fnkabit** [comment]
> There now is a new release, could you please test it and report if it works for you?

Tested, it works. Thanks for the review !

**Comment by pbek** [comment]
Great, thank you for implementing and testing! 😁
