### ISSUE TITLE
Export note to pdf (preview) issue on Windows 10. The font size of the headlines is too small to see.

### ISSUE THREAD

**Issue by iseevi** [pbek/QOwnNotes#2015]
#### Expected behaviour
Expected size of fonts in pdf as it shown at the preview 
#### Actual behaviour
Font size of Headlines in pdf file too small
#### Steps to reproduce
Crate Note
Title or name by default
make some Headline (## headline1)
export as pdf (preview)
#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Вт янв 19 17:39:52 2021`
**Version**: `21.1.2`
**Build date**: `Jan  4 2021`
**Build number**: `803`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\user\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `D:\Documents\!QOwnNote\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `ru_RU`
**Locale (interface)**: `en`
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1680x1050`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `10`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\user\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `2`

### Note folder `WRK`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `D:\Documents\Folder\!NOTES`
**remotePath**: *empty*
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `TD`
**database file**: `D:\Documents\Folder\!NOTES\notes.sqlite`

### Note folder `HM`

**id**: `3`
**isCurrent**: `no`
**activeTagId**: `-1`
**localPath**: `D:\YandexDisk\DOC`
**remotePath**: *empty*
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `D:\YandexDisk\DOC\notes.sqlite`

### Cloud connection ``

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `true`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (int): `25`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `false`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): ``
**FileDialog/LastPath-InsertImage** (QString): ``
**FileDialog/LastPath-NoteHTMLExport** (QString): ``
**FileDialog/LastPath-NotePDFExport** (QString): ``
**ImageDialog/disableCopying** (QString): `true`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-01-19T17:21:39.430`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LinkDialog/lastSelectedFileUrl** (QString): `file:///D:/YandexDisk/WRK/*.xls`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `26`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-2** (QStringList): `!NOTES, 1C, DOCUMENTS`
**MainWindow/noteTextEdit.code.font** (QString): `Consolas,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Arial,12,-1,5,50,0,0,0,0,0,Обычный`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-2/NoteTabNameList** (QStringList): `Note 2021-01-13T17.03.08`
**NoteFolder-2/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-2/NoteTabSubFolderPathDataList** (QStringList): `TD`
**NoteFolder-2/allowDifferentNoteFileName** (QString): `true`
**NoteFolder-3/NoteTabNameList** (QStringList): *empty*
**NoteFolder-3/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-3/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteFolder-3/allowDifferentNoteFileName** (QString): `true`
**NoteHistory-2** (QVariantList): `<variant list with 47 item(s)>`
**NoteHistory-3** (QVariantList): `<variant list with 35 item(s)>`
**NoteHistoryCurrentIndex-2** (int): `46`
**NoteHistoryCurrentIndex-3** (int): `34`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExportOrientation** (int): `0`
**Printer/NotePDFExportPageSize** (int): `4`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**TagAddDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `true`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `2`
**currentWorkspace** (QString): `Se2mLTvNayvL`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `14`
**interfaceLanguage** (QString): `en`
**internalIconTheme** (QString): `true`
**itemHeight** (int): `18`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `0`
**notesPath** (QString): `D:/Documents/Folder/!NOTES`
**notifyAllExternalModifications** (QString): `true`
**overrideInterfaceFontSize** (QString): `true`
**ownCloud/ignoreNonTodoCalendars** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `2`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**recentNoteFolders** (QStringList): `D:/YandexDisk/DOC, D:/Documents/folder, D:/YandexDisk/WRK/NOTES_TEST, D:/tmp/NOTES_TEST2, D:/YandexDisk/WRK`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-2** (QStringList): `Note 2021-01-19T09.19.22, Note 2021-01-18T17.03.36, Note 2021-01-13T17.03.08, Note 2021-01-13T11.21.00, 2021_01_12_ToDo, 2021_01_11`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/7/items** (QStringList): `action_new_tag, actionInsert_attachment, actionInsert_table, actionInsert_code_block, actionInsert_block_quote, actionInsert_headline_from_note_filename`
**toolbar/7/name** (QString): `custom_toolbar_1`
**toolbar/7/title** (QString): `custom_toolbar_1`
**toolbar/size** (int): `7`
**useNoteFolderButtons** (QString): `false`
**useSoftWrapInNoteEditor** (QString): `true`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-Se2mLTvNayvL/name** (QString): `Полный`
**workspace-Se2mLTvNayvL/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-Se2mLTvNayvL/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Минимальный`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, Se2mLTvNayvL`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\user\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `PCNAME`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\user`
**LOCALAPPDATA**: `C:\Users\user\AppData\Local`
**LOGONSERVER**: `\\PCNAME`
**MOZ_PLUGIN_PATH**: `C:\PROGRAM FILES (X86)\FOXIT SOFTWARE\FOXIT READER\plugins\`
**NUMBER_OF_PROCESSORS**: `4`
**OneDrive**: `C:\Users\user\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\OpenVPN\bin;C:\Program Files\dotnet\;C:\Users\user\AppData\Local\Microsoft\WindowsApps;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 158 Stepping 11, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `9e0b`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\user\AppData\Local\Temp`
**TMP**: `C:\Users\user\AppData\Local\Temp`
**USERDOMAIN**: `PCNAME`
**USERDOMAIN_ROAMINGPROFILE**: `PCNAME`
**USERNAME**: `user`
**USERPROFILE**: `C:\Users\user`
**windir**: `C:\WINDOWS`

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

[янв 19 14:28:14] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[янв 19 14:28:14] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"" <serverUrl>"" <username>"" <priority>0
[янв 19 14:28:14] [debug]: buildNotesIndex  - 'noteSubFolderId':  0
[янв 19 14:28:14] [debug]: setupNoteFolderTables  - 'database version':  14
[янв 19 14:28:14] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"" <serverUrl>"" <username>"" <priority>0
[янв 19 14:28:14] [debug]: loadNoteDirectoryList
[янв 19 14:28:14] [debug]: reloadTagTree
[янв 19 14:28:14] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(3)
[янв 19 14:28:14] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(3)
[янв 19 14:28:14] [debug]: reloadNoteSubFolderTree
[янв 19 14:28:14] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(3)
[янв 19 14:28:14] [debug]: reloadNoteSubFolderTree
[янв 19 14:28:14] [debug]: loadNoteDirectoryList
[янв 19 14:28:14] [debug]: reloadTagTree
[янв 19 14:28:14] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(3)
[янв 19 14:28:14] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(3)
[янв 19 14:28:14] [debug]: reloadNoteSubFolderTree
[янв 19 14:28:14] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(3)
[янв 19 14:28:24] [debug]: storing note file:  "Note 2021-01-13T17.03.08.md"
[янв 19 14:28:24] [debug]: stored note:  Note: <id>7 <name>"Note 2021-01-13T17.03.08" <fileName>"Note 2021-01-13T17.03.08.md" <noteSubFolderId>3 <relativePath>"TD" <hasDirtyData>false
[янв 19 14:28:24] [debug]: storeUpdatedNotesToDisk  - 'count':  1
[янв 19 14:28:24] [status]: Stored 1 note(s) to disk
[янв 19 14:28:34] [debug]: storing note file:  "Note 2021-01-13T17.03.08.md"
[янв 19 14:28:34] [debug]: stored note:  Note: <id>7 <name>"Note 2021-01-13T17.03.08" <fileName>"Note 2021-01-13T17.03.08.md" <noteSubFolderId>3 <relativePath>"TD" <hasDirtyData>false
[янв 19 14:28:34] [debug]: storeUpdatedNotesToDisk  - 'count':  1
[янв 19 14:28:34] [status]: Stored 1 note(s) to disk
[янв 19 14:28:44] [debug]: storing note file:  "Note 2021-01-13T17.03.08.md"
[янв 19 14:28:44] [debug]: stored note:  Note: <id>7 <name>"Note 2021-01-13T17.03.08" <fileName>"Note 2021-01-13T17.03.08.md" <noteSubFolderId>3 <relativePath>"TD" <hasDirtyData>false
[янв 19 14:28:44] [debug]: storeUpdatedNotesToDisk  - 'count':  1
[янв 19 14:28:44] [status]: Stored 1 note(s) to disk
</details>

**Comment by pbek** [comment]
Can you please post the full output from the debug settings (see issue template).
And what is "too small"? Can you please provide an example markdown, the generated pdf and a screenshot of your preview?
Not all styles are the same in the PDF Export as in the preview... There also is a script in the script repository to control the styling of the preview and the pdf export.

**Comment by iseevi** [comment]
Editor and preview windows:
![2021-01-19_17-34-53](https://user-images.githubusercontent.com/77671742/105048482-af64de80-5a7c-11eb-9c81-894323af1c1f.png)

and this I see in pdf viewer:
![2021-01-19_17-36-12](https://user-images.githubusercontent.com/77671742/105048660-db805f80-5a7c-11eb-91dd-abd018b3beee.png)

**Comment by iseevi** [comment]
The font is too small compared to other text:
![2021-01-19_18-14-59](https://user-images.githubusercontent.com/77671742/105053715-4f713680-5a82-11eb-9d19-e17a784ef7e7.png)

**Comment by pbek** [comment]
I need more information, see https://github.com/pbek/QOwnNotes/issues/2015#issuecomment-762877224 😅

**Comment by iseevi** [comment]
I edited the message, added the full information from "Output from the debug section in the settings dialog" :-)

**Comment by pbek** [comment]
> Can you please provide an example markdown, the generated pdf 

... 😅 

Have you tried the export in a new app session (see https://www.qownnotes.org/getting-started/cli-parameters.html)?

**Comment by iseevi** [comment]
[Note 2021-01-13T17.03.08.pdf](https://github.com/pbek/QOwnNotes/files/5848150/Note.2021-01-13T17.03.08.pdf)
[Note 2021-01-13T17.03.08_clear.pdf](https://github.com/pbek/QOwnNotes/files/5848151/Note.2021-01-13T17.03.08_clear.pdf)
[Note 2021-01-13T17.03.08.txt](https://github.com/pbek/QOwnNotes/files/5848172/Note.2021-01-13T17.03.08.txt)

> Have you tried the export in a new app session (see https://www.qownnotes.org/getting-started/cli-parameters.html)?

Yes, it helps, but the reason is unclear to me, maybe I changed the font in the editor, or something else.

Thank you for your patience.

**Comment by pbek** [comment]
It's a strange issue. I can even reproduce it, but only under Windows 10, not under Linux. It's the same regardless of Qt version (I tried 5.7, 5.13 and 5.15). And I can even remove all styling from the code and it's still the same (but then everything is tiny).

**Comment by pbek** [comment]
No issues on my Windows 8.1 Dev VM... 😬

**Comment by Waqar144** [comment]
In general for good quality PDF I tend to export to html and then use the browser to create PDF because that results in better pagination.

Iwill try to find out the reason for this in windows, since I now have a windows machine with partial dev environment set up ;)

**Comment by pbek** [comment]
Awesome!

**Comment by iseevi** [comment]
That would be great!

**Comment by pbek** [comment]
@Waqar144, it's something with the QTextDocument. If I use a fresh QTextDocument in `MainWindow::exportNoteAsPDF` the sizes are ok... But of course I loose all kind of data if I do that.

**Comment by pbek** [comment]
It's the QTextDocument we get from a QTextBrowser.
It's the same issue if we use a fresh QTextBrowser before exporting and just feed the html to its QTextDocument.

```cpp
void MainWindow::exportNoteAsPDF(QTextDocument *doc) {
    QString html = doc->toHtml();
    doc = (new QTextBrowser(this))->document();
    doc->setHtml(html);
``´

**Comment by pbek** [comment]
It's the same if you use a QTextEdit instead of a QTextBrowser.

**Comment by pbek** [comment]
I think I've fixed the issue under Windows 10. I hope this doesn't break anything else in the pdf.
@iseevi, can you please test the build (the only artifact) that will be generated in https://github.com/pbek/QOwnNotes/actions/runs/510446374.

**Comment by iseevi** [comment]
Thank you @pbek, I've tested exporting all my notes and test notes with all kinds of formatting. It looks like this part of QOwnNotes is working perfectly now!

**Comment by pbek** [comment]
Great, I'll make a new release later today. Thank you for testing.

**Comment by Waqar144** [comment]
> @Waqar144, it's something with the QTextDocument. If I use a fresh QTextDocument in `MainWindow::exportNoteAsPDF` the sizes are ok... But of course I loose all kind of data if I do that.

QTextBrowser modifies the document internally, and maybe something breaks during that. Doesn't Qtextdocument have an export to pdf function directly?

**Comment by pbek** [comment]
The basis for pdf exports is a `QTextDocument`.

**Comment by Waqar144** [comment]
Someday we should move to webkit :p

Maybe build it inside QON statically 😂

**Comment by pbek** [comment]
It will be much fun getting that to work on all build systems. 🤣

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by iseevi** [comment]
Almost two days of testing, everything works well, as far as I can tell. 👍

**Comment by pbek** [comment]
Great, thank you for testing!
