### ISSUE TITLE
Option to hide beginning to of link in note-taking window

### ISSUE THREAD

**Issue by capcionista** [pbek/QOwnNotes#202]
The current link format <notes://notename> makes reading notes relatively hard for those who are not using the markdown preview:
If I am building a wiki-like note database, it would read:
 [notes://Plato] was perhaps the most important  [notes://Philosopher] in  [notes://Ancient Greek History]

It would be great to be able to hide the <directory://> part of the link in the editing window or at least display it in another color (e.g. light grey) than the rest of the link, so that doesn't distract the user.

Alternatively, let users change the markdown syntax highlighting themselves. This would also allow users to personalize the editor more to their own needs.

**Comment by pbek** [comment]
There is no way to hide something, notes are edited as plain text and to change the highlighting patterns I would have to fork the markdown highlighter and hack it to do your bidding.

> Alternatively, let users change the markdown syntax highlighting themselves.

can you please describe what you are suggesting?

**Comment by capcionista** [comment]
E.g. in the Atom Editor users can modify the syntax files themselves, which would allow me to make the programme recognize "[notes://" as a special string and then to print it in a different color (e.g. light grey) after editing the CSS

**Comment by pbek** [comment]
I'm sorry, but Atom is not based on the Electron framework, which uses JavaScript/HTML/CSS and is not compiled...
The markdown highlighting library of QOwnNotes is compiled and cannot be edited on runtime.

**Comment by capcionista** [comment]
I think if you could fork the highlighter, I could adjust the setting. The path could then be displayed as the background color, which would make the files much easier to read.

Apart from that: Is there a way to change the beginning of the links from "notes" to "n" or "I" or "l" (which are perhaps the least distracting letters?

**Comment by pbek** [comment]
The current highlight wouldn't even support partial highlighting of a matched block. 😸 
You are free to fork QOwnNotes, try what ever you like and make a pull request...
