### ISSUE TITLE
QOwnNotes deleted all my notes

### ISSUE THREAD

**Issue by swwright** [pbek/QOwnNotes#2021]
I am using QOwnNotes in the PortableApps.com suite.  I don't know how long ago QOwnNotes was added to PortableApps.  I started using QOwnNotes about a year ago, I think.  I saw this problem soon afterward, in version 20.3.7.  I'm currently running version 20.10.3.

The problem is: Every once in a while, I open QOwnNotes and it says, "Hi, welcome to QOwnNotes!  Where do you want to store your notes?".  And all the notes I've been saving in QOwnNotes are gone.

It is possible that this problem is caused by how PortableApps works. But it makes no sense to me.

#### Expected behaviour
Start PortableApps, open QOwnNotes Portable, begin editing my notes.	

#### Actual behaviour
Start PortableApps, open QOwnNotes Portable . . .  QOwnNotes displays "Welcome to QOwnNotes" window and asks where I want to keep my notes.

#### Steps to reproduce
This has happened to me a number of times in different circumstances.  I have found one thing that consistently causes it to happen: Have the Notes folder open in a Windoze File Explorer window.  Don't need to have any files open, just be LOOKING AT the Notes folder, when I start QOwnNotes.

This has also happened when I do NOT have the Notes folder open.  Happened about 10 minutes ago.  All I can think is that yesterday, I copied a couple of the notes out to the place where they will be used.  But that suggests that QOwnNotes somehow "knows" I WAS looking at its Notes folder, and spitefully decided to trash my stuff.  Makes no sense to me.

Anyway, if I stop when I see that "Welcome" window, and open the Notes folder, I can copy my notes elsewhere -- they haven't been deleted yet.  Then I can set up QOwnNotes according to my preferences, (my notes get deleted at this point), open the saved notes in vim or some other text editor, and copy/paste them one at a time back into QOwnNotes. Painful.

Some details on QOwnNotes in PortableApps:
QOwnNotes is located at PA.c\PortableApps\QOwnNotesPortable\App\QOwnNotes.
The notes are located at PA.c\PortableApps\QOwnNotesPortable\Data\QOwnNotesData\Notes.

I would like to see this fixed.  There is NO REASON why QOwnNotes should delete all my notes, just because I have the Notes folder open in WIndoze File Explorer.

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fri Jan 22 18:00:58 2021`
**Version**: `20.10.3`
**Build date**: `Oct  9 2020`
**Build number**: `770`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `yes`
**Settings path / key**: `D:/USB/WD1TB/PA.c/PortableApps/QOwnNotesPortable/App/QOwnNotes/Data/PBE/QOwnNotes.ini`
**Application database path**: `D:\USB\WD1TB\PA.c\PortableApps\QOwnNotesPortable\App\QOwnNotes\Data\QOwnNotes.sqlite`
**Application arguments**: `D:\USB\WD1TB\PA.c\PortableApps\QOwnNotesPortable\App\QOwnNotes\QOwnNotes.exe`, `--portable`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `2`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `D:\USB\WD1TB\PA.c\PortableApps\QOwnNotesPortable\App\QOwnNotes\Data\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `D:\USB\WD1TB\PA.c\PortableApps\QOwnNotesPortable\App\QOwnNotes\Data\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `D:\USB\WD1TB\PA.c\PortableApps\QOwnNotesPortable\App\QOwnNotes\Data\Notes\notes.sqlite`

## Settings

**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**LastUpdateCheck** (QDateTime): `2021-01-22T18:00:45.645`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**PiwikClientId** (QString): `<hidden>`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/notificationShown** (bool): `true`
**checkSpelling** (bool): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**darkMode** (bool): `false`
**demoNotesCreated** (bool): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**dockWasInitializedOnce** (bool): `true`
**guiFirstRunInit** (bool): `true`
**initialLayoutIdentifier** (QString): `minimal`
**itemHeight** (int): `15`
**markdownHighlightingEnabled** (bool): `true`
**noteEditIsCentralWidget** (QString): `true`
**notesPath** (QString): `Notes`
**ownCloud/supportEnabled** (bool): `false`
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**ALLUSERSAPPDATA**: `C:\ProgramData`
**ALLUSERSAPPDATA:DoubleBackslash**: `C:\\ProgramData`
**ALLUSERSAPPDATA:Forwardslash**: `C:/ProgramData`
**ALLUSERSAPPDATA:java.util.prefs**: `/C:///Program/Data`
**ALLUSERSPROFILE**: `C:\ProgramData`
**ALLUSERSPROFILE:DoubleBackslash**: `C:\\ProgramData`
**ALLUSERSPROFILE:Forwardslash**: `C:/ProgramData`
**ALLUSERSPROFILE:java.util.prefs**: `/C:///Program/Data`
**APPDATA**: `C:\Users\DLehmann\AppData\Roaming`
**APPDATA:DoubleBackslash**: `C:\\Users\\DLehmann\\AppData\\Roaming`
**APPDATA:Forwardslash**: `C:/Users/DLehmann/AppData/Roaming`
**APPDATA:java.util.prefs**: `/C:///Users///D/Lehmann///App/Data///Roaming`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `CDI-DLEHMANN-DT`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DNX_HOME**: `%USERPROFILE%\.dnx`
**DOCUMENTS**: `C:\Users\DLehmann\Documents`
**DOCUMENTS:DoubleBackslash**: `C:\\Users\\DLehmann\\Documents`
**DOCUMENTS:Forwardslash**: `C:/Users/DLehmann/Documents`
**DOCUMENTS:java.util.prefs**: `/C:///Users///D/Lehmann///Documents`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\DLehmann`
**JAVA_HOME**: `C:\Program Files\Java\jdk1.8.0_202`
**LOCALAPPDATA**: `C:\Users\DLehmann\AppData\Local`
**LOCALAPPDATA:DoubleBackslash**: `C:\\Users\\DLehmann\\AppData\\Local`
**LOCALAPPDATA:Forwardslash**: `C:/Users/DLehmann/AppData/Local`
**LOCALAPPDATA:java.util.prefs**: `/C:///Users///D/Lehmann///App/Data///Local`
**LOGONSERVER**: `\\CDI-HQ-DC1`
**NUMBER_OF_PROCESSORS**: `8`
**OneDrive**: `C:\Users\DLehmann\OneDrive`
**OS**: `Windows_NT`
**PAL:AppDir**: `D:\USB\WD1TB\PA.c\PortableApps\QOwnNotesPortable\App`
**PAL:AppDir:DoubleBackslash**: `D:\\USB\\WD1TB\\PA.c\\PortableApps\\QOwnNotesPortable\\App`
**PAL:AppDir:Forwardslash**: `D:/USB/WD1TB/PA.c/PortableApps/QOwnNotesPortable/App`
**PAL:AppDir:java.util.prefs**: `/D:///U/S/B///W/D/1/T/B///P/A/.c///Portable/Apps///Q/Own/Notes/Portable///App`
**PAL:DataDir**: `D:\USB\WD1TB\PA.c\PortableApps\QOwnNotesPortable\Data`
**PAL:DataDir:DoubleBackslash**: `D:\\USB\\WD1TB\\PA.c\\PortableApps\\QOwnNotesPortable\\Data`
**PAL:DataDir:Forwardslash**: `D:/USB/WD1TB/PA.c/PortableApps/QOwnNotesPortable/Data`
**PAL:DataDir:java.util.prefs**: `/D:///U/S/B///W/D/1/T/B///P/A/.c///Portable/Apps///Q/Own/Notes/Portable///Data`
**PAL:Drive**: `D:`
**PAL:DriveLetter**: `D`
**PAL:LastDrive**: `D:`
**PAL:LastDriveLetter**: `D`
**PAL:LastPackagePartialDir**: `\USB\WD1TB\PA.c\PortableApps\QOwnNotesPortable`
**PAL:LastPackagePartialDir:DoubleBackslash**: `\\USB\\WD1TB\\PA.c\\PortableApps\\QOwnNotesPortable`
**PAL:LastPackagePartialDir:Forwardslash**: `/USB/WD1TB/PA.c/PortableApps/QOwnNotesPortable`
**PAL:LastPackagePartialDir:java.util.prefs**: `///U/S/B///W/D/1/T/B///P/A/.c///Portable/Apps///Q/Own/Notes/Portable`
**PAL:LastPortableAppsBaseDir**: `D:\USB\WD1TB\PA.c`
**PAL:LastPortableAppsBaseDir:DoubleBackslash**: `D:\\USB\\WD1TB\\PA.c`
**PAL:LastPortableAppsBaseDir:Forwardslash**: `D:/USB/WD1TB/PA.c`
**PAL:LastPortableAppsBaseDir:java.util.prefs**: `/D:///U/S/B///W/D/1/T/B///P/A/.c`
**PAL:PackagePartialDir**: `\USB\WD1TB\PA.c\PortableApps\QOwnNotesPortable`
**PAL:PackagePartialDir:DoubleBackslash**: `\\USB\\WD1TB\\PA.c\\PortableApps\\QOwnNotesPortable`
**PAL:PackagePartialDir:Forwardslash**: `/USB/WD1TB/PA.c/PortableApps/QOwnNotesPortable`
**PAL:PackagePartialDir:java.util.prefs**: `///U/S/B///W/D/1/T/B///P/A/.c///Portable/Apps///Q/Own/Notes/Portable`
**PAL:PortableAppsBaseDir**: `D:\USB\WD1TB\PA.c`
**PAL:PortableAppsBaseDir:DoubleBackslash**: `D:\\USB\\WD1TB\\PA.c`
**PAL:PortableAppsBaseDir:Forwardslash**: `D:/USB/WD1TB/PA.c`
**PAL:PortableAppsBaseDir:java.util.prefs**: `/D:///U/S/B///W/D/1/T/B///P/A/.c`
**PAL:PortableAppsDir**: `D:\USB\WD1TB\PA.c\PortableApps`
**PAL:PortableAppsDir:DoubleBackslash**: `D:\\USB\\WD1TB\\PA.c\\PortableApps`
**PAL:PortableAppsDir:Forwardslash**: `D:/USB/WD1TB/PA.c/PortableApps`
**PAL:PortableAppsDir:java.util.prefs**: `/D:///U/S/B///W/D/1/T/B///P/A/.c///Portable/Apps`
**PAL:_IgnoreLanguage**: `false`
**PAL:_TEMP**: `C:\Users\DLehmann\AppData\Local\Temp`
**Path**: `C:\Program Files (x86)\VMware\VMware Player\bin\;C:\Program FIles\Java\jdk1.8.0_202\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;D:\MorePrograms\MinGW\bin;D:\MorePrograms\GoW\gow-0.8.0\bin;D:\MorePrograms\Unison\;C:\Program FIles\Java\jdk-11.0.4+11\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files (x86)\Acronis\CommandLineTool\;C:\Program Files\OpenVPN\bin;C:\Program Files (x86)\Microsoft Team Foundation Server 2015 Power Tools\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;;C:\Program Files (x86)\Neurotechnology\Neurotec Biometric 4.4;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Users\DLehmann\.dnx\bin;C:\Users\DLehmann\AppData\Local\Microsoft\WindowsApps;D:\MorePrograms\Fossil;D:\MorePrograms\SysinternalsSuite\;D:\MorePrograms\Unison\;C:\Users\DLehmann\AppData\Local\Microsoft\WindowsApps;C:\Users\DLehmann\AppData\Local\Pandoc\;;C:\Program Files (x86)\Common Files\Acronis\TibMounter64`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PortableApps.comDisableSplash**: `true`
**PortableApps.comDocuments**: `D:\USB\WD1TB\PA.c\Documents`
**PortableApps.comDocuments:DoubleBackslash**: `D:\\USB\\WD1TB\\PA.c\\Documents`
**PortableApps.comDocuments:Forwardslash**: `D:/USB/WD1TB/PA.c/Documents`
**PortableApps.comDocuments:java.util.prefs**: `/D:///U/S/B///W/D/1/T/B///P/A/.c///Documents`
**PortableApps.comHighContrast**: `false`
**PortableApps.comLanguageCode**: `en`
**PortableApps.comLanguageCode2**: `en`
**PortableApps.comLanguageCode2_INTERNAL**: `en`
**PortableApps.comLanguageCode3**: `eng`
**PortableApps.comLanguageCode3_INTERNAL**: `eng`
**PortableApps.comLanguageCode_INTERNAL**: `en`
**PortableApps.comLanguageGlibc**: `en_US`
**PortableApps.comLanguageGlibc_INTERNAL**: `en_US`
**PortableApps.comLanguageLCID**: `1033`
**PortableApps.comLanguageLCID_INTERNAL**: `1033`
**PortableApps.comLanguageName**: `English`
**PortableApps.comLanguageName_INTERNAL**: `English`
**PortableApps.comLanguageNSIS**: `LANG_ENGLISH`
**PortableApps.comLanguageNSIS_INTERNAL**: `LANG_ENGLISH`
**PortableApps.comLocaleCode2**: `en`
**PortableApps.comLocaleCode2_INTERNAL**: `en`
**PortableApps.comLocaleCode3**: `eng`
**PortableApps.comLocaleCode3_INTERNAL**: `eng`
**PortableApps.comLocaleglibc**: `en_US`
**PortableApps.comLocaleglibc_INTERNAL**: `en_US`
**PortableApps.comLocaleID**: `1033`
**PortableApps.comLocaleID_INTERNAL**: `1033`
**PortableApps.comLocaleName**: `ENGLISH`
**PortableApps.comLocaleWinName**: `LANG_ENGLISH`
**PortableApps.comLocaleWinName_INTERNAL**: `LANG_ENGLISH`
**PortableApps.comMusic**: `D:\USB\WD1TB\PA.c\Documents\Music`
**PortableApps.comMusic:DoubleBackslash**: `D:\\USB\\WD1TB\\PA.c\\Documents\\Music`
**PortableApps.comMusic:Forwardslash**: `D:/USB/WD1TB/PA.c/Documents/Music`
**PortableApps.comMusic:java.util.prefs**: `/D:///U/S/B///W/D/1/T/B///P/A/.c///Documents///Music`
**PortableApps.comPictures**: `D:\USB\WD1TB\PA.c\Documents\Pictures`
**PortableApps.comPictures:DoubleBackslash**: `D:\\USB\\WD1TB\\PA.c\\Documents\\Pictures`
**PortableApps.comPictures:Forwardslash**: `D:/USB/WD1TB/PA.c/Documents/Pictures`
**PortableApps.comPictures:java.util.prefs**: `/D:///U/S/B///W/D/1/T/B///P/A/.c///Documents///Pictures`
**PortableApps.comPlatformVersion**: `17.1.1.0`
**PortableApps.comVideos**: `D:\USB\WD1TB\PA.c\Documents\Videos`
**PortableApps.comVideos:DoubleBackslash**: `D:\\USB\\WD1TB\\PA.c\\Documents\\Videos`
**PortableApps.comVideos:Forwardslash**: `D:/USB/WD1TB/PA.c/Documents/Videos`
**PortableApps.comVideos:java.util.prefs**: `/D:///U/S/B///W/D/1/T/B///P/A/.c///Documents///Videos`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 94 Stepping 3, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `5e03`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\DLehmann\AppData\Local\Temp\QOwnNotesPortableTemp`
**TEMP:DoubleBackslash**: `C:\\Users\\DLehmann\\AppData\\Local\\Temp\\QOwnNotesPortableTemp`
**TEMP:Forwardslash**: `C:/Users/DLehmann/AppData/Local/Temp/QOwnNotesPortableTemp`
**TEMP:java.util.prefs**: `/C:///Users///D/Lehmann///App/Data///Local///Temp///Q/Own/Notes/Portable/Temp`
**TFSPowerToolDir**: `C:\Program Files (x86)\Microsoft Team Foundation Server 2015 Power Tools\`
**TMP**: `C:\Users\DLehmann\AppData\Local\Temp\QOwnNotesPortableTemp`
**USERDNSDOMAIN**: `CDI-HQ.COM`
**USERDOMAIN**: `CDI-HQ`
**USERDOMAIN_ROAMINGPROFILE**: `CDI-HQ`
**USERNAME**: `DLehmann`
**USERPROFILE**: `C:\Users\DLehmann`
**USERPROFILE:DoubleBackslash**: `C:\\Users\\DLehmann`
**USERPROFILE:Forwardslash**: `C:/Users/DLehmann`
**USERPROFILE:java.util.prefs**: `/C:///Users///D/Lehmann`
**VBOX_MSI_INSTALL_PATH**: `C:\Program Files\Oracle\VirtualBox\`
**VS110COMNTOOLS**: `C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\`
**VS120COMNTOOLS**: `C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\`
**VS140COMNTOOLS**: `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\`
**windir**: `C:\WINDOWS`
**QML_DISABLE_DISK_CACHE**: `true`

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
To be true I've no idea how PortableApps manages QOwnNotes.
In portable mode QON looks into the app folder for a note folder and the settings files.

Theses are the two important files you need to watch that they are not gone from your usb stick:

```
Settings path / key: D:/USB/WD1TB/PA.c/PortableApps/QOwnNotesPortable/App/QOwnNotes/Data/PBE/QOwnNotes.ini
Application database path: D:\USB\WD1TB\PA.c\PortableApps\QOwnNotesPortable\App\QOwnNotes\Data\QOwnNotes.sqlite
```

And that's your note folder:

```
D:\USB\WD1TB\PA.c\PortableApps\QOwnNotesPortable\App\QOwnNotes\Data\Notes
```

**Comment by pbek** [comment]
Btw. currently we are at 21.1.5 😉  So you more than 30 releases behind.

**Comment by swwright** [comment]
@pbek, that is interesting.  According to the PortableApps page, QOwnNotes Portable is maintained by your team in collaboration with PortableApps.com.
(https://portableapps.com/apps/office/qownnotes-portable)
I'm not sure why the PortableApps version is so far behind your release schedule.

In PortableApps, the two files you mentioned are not located where you said.  There are actually two copies: one is a default and is copied to the "active" location if it doesn't already exist there.  The other is the active copy.  In my PortableApps copy the default copies are at:
```
D:\USB\WD1TB\PA.c\PortableApps\QOwnNotesPortable\App\DefaultData\QOwnNotesData\PBE\QOwnNotes.ini
D:\USB\WD1TB\PA.c\PortableApps\QOwnNotesPortable\App\DefaultData\QOwnNotesData\QOwnNotes.sqlite
```

and the active copies are at:
```
D:\USB\WD1TB\PA.c\PortableApps\QOwnNotesPortable\Data\QOwnNotesData\PBE\QOwnNotes.ini
D:\USB\WD1TB\PA.c\PortableApps\QOwnNotesPortable\Data\QOwnNotesData\QOwnNotes.sqlite
```
The notes are, as I wrote before, at:
```
D:\USB\WD1TB\PA.c\PortableApps\QOwnNotesPortable\Data\QOwnNotesData\Notes\*.md
```

I have no idea if this discrepancy has anything to do with the problem.  I still cannot understand why JUST HAVING A WINDOW OPEN causes QOwnNotes to assume the data is corrupted and it must start over from scratch.

I can try one more thing.  I will install QOwnNotes (rather than using it as a PortableApp), and see what happens.  If the installed copy does NOT fail in the same way as the PortableApp copy, then I must take this whole matter over to PortableApps.com and see if they can explain and fix it.

**Comment by pbek** [comment]
> in collaboration with PortableApps.com.

I don't think that's the case, I haven't heard anything from anyone and have no contacts there.

> I'm not sure why the PortableApps version is so far behind your release schedule.

Maybe the one guy or girl who have maintained that QON "repository" abandoned it...

You only need one parameter to run QON in portable mode, see:

- https://www.qownnotes.org/blog/2016-09-18-Portable-mode.html
- https://www.qownnotes.org/installation/windows.html#portable-mode
