### ISSUE TITLE
Right-to-left alignment at qownnotes.org

### ISSUE THREAD

**Issue by amirkbrpr** [pbek/QOwnNotes#2025]
Hi! Is it possible to set the right-to-left alignment for Persian at https://www.qownnotes.org/fa/ ? Because the words clutter in a mixture of Persian and English words. Thanks!

**Comment by pbek** [comment]
I researched that a bit. It doesn't look like Vuepress is supporting RTL out of the box. I'll look a bit more.

**Comment by pbek** [comment]
I found a RTL theme (https://z3by.github.io/vuepress-tools/themes/vuepress-theme-default-rtl.html), but it doesn't seem you can use different themes for different locales.

The only thing I managed to sneak in for the `lang="fa"` are some RTL CSS styles.
I guess it's better than before, but I'm not sure if it's enough: https://www.qownnotes.org/fa/getting-started/overview.html

**Comment by amirkbrpr** [comment]
Great! The problem solved. Thanks!

**Comment by pbek** [comment]
Great, thank you for testing! 😁
