### ISSUE TITLE
External editing is reported even though there is not external editing in place

### ISSUE THREAD

**Issue by fthommen** [pbek/QOwnNotes#2027]
#### Problem Description

While typing in QOwnNotes (version 21.1.8, build 809, running on macOS 11 Big Sur) I am constantly bothered with notifications, that some "external editing" has happened and if I want to accept the changes (mostly w/o showing me any of these changes).  There is no external editing in place.  The notes are only opened with QOwnNotes and no other editor and they reside in a local folder which is not touched by any cloud client software.  nextCloud/Ownloud integration is not enabled (has initially been enabed, didn't work and has since been disabled in the application settings)

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed Jan 27 19:56:52 2021`
**Version**: `21.1.8`
**Build date**: `Jan 26 2021`
**Build number**: `809`
**Platform**: `macosx`
**Operating System**: `macOS 11.1`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/Users/XXXX/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/XXXX/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Users/XXXX/My Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_DE`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1440x900`
**Screen resolution(s)**: `1440x900, 1920x1200`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `4`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://XXXXXXX`
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/Users/XXXX/Library/Application Support/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/Users/XXXX/ownCloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `XXXX`
**database file**: `/Users/XXXX/ownCloud/Notes/notes.sqlite`

### Cloud connection `XXXX`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://XXXXXXXX`
**username**: `XXXX`

## Settings

**6989 Intenso Rainbow Line** (QString): `1`
**AKLastCheckInAttemptDate** (QDateTime): `2020-10-18T19:24:45.617`
**AKLastCheckInSuccessDate** (QDateTime): `2020-10-18T19:24:46.734`
**AKLastEmailListRequestDateKey** (QDateTime): `2019-02-06T22:15:06.410`
**AKLastIDMSEnvironment** (qlonglong): `0`
**ALCOR Intenso Ultra Line** (QString): `1`
**ASIX Elec/ Corp/ AX88179** (QString): `1`
**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Country** (QString): `DE`
**Creative Technology Ltd/ VF0700 Live! Cam Chat HD** (QString): `1`
**DYMO LabelWriter 450 DUO** (QString): `1`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (qlonglong): `4`
**Editor/removeTrailingSpaces** (bool): `false`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**Fairphone FP2** (QString): `1`
**Generic External** (QString): `1`
**Generic Mass Storage** (QString): `1`
**Generic Mass Storage Device** (QString): `1`
**HP OfficeJet Pro 6960** (QString): `1`
**InitialKeyRepeat** (qlonglong): `25`
**Intenso External USB 3/0** (QString): `1`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**KeyRepeat** (qlonglong): `2`
**LastUpdateCheck** (QDateTime): `2021-01-27T19:46:13.457`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (qlonglong): `32`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `.AppleSystemUIFontMonospaced,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `.AppleSystemUIFont,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `.AppleSystemUIFontMonospaced,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `.AppleSystemUIFont,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MultipleSessionEnabled** (bool): `false`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): `XXXXXXXXXXXX`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `XXXX`
**NoteHistory-1** (QVariantList): `<variant list with 15 item(s)>`
**NoteHistoryCurrentIndex-1** (qlonglong): `14`
**PKSecureElementAvailableFlagsByHost** (qlonglong): `1`
**PiwikClientId** (QString): `<hidden>`
**RICOH MP C4504ex** (QString): `1`
**SMI Corporation Intenso Ultra Line** (QString): `1`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**Seagate Expansion+** (QString): `1`
**SearchEngineId** (qlonglong): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StarTech/com USB Crash Cart Adapter** (QString): `1`
**StartHidden** (bool): `false`
**StoreJet Transcend StoreJet Transcend** (QString): `1`
**TOSHIBA External USB 3/0** (QString): `1`
**TrekStor USB-Stick CS TrekStor USB-Stick CS** (QString): `1`
**USBest Technology USB Mass Storage Device** (QString): `1`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**Verbatim STORE N GO** (QString): `1`
**WebAutomaticSpellingCorrectionEnabled** (bool): `true`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**Western Digital My Book 25EE** (QString): `1`
**_HIHideMenuBar** (bool): `false`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `false`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (bool): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**com/omnigroup/OmniGraffle6:6:2** (QByteArray): `<binary data>`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (qlonglong): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (qlonglong): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (bool): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (bool): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (qlonglong): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (qlonglong): `1024`
**imageScaleDownMaximumWidth** (qlonglong): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (qlonglong): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (qlonglong): `18`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (qlonglong): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (qlonglong): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (qlonglong): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (qlonglong): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (qlonglong): `0`
**notesPanelOrder** (qlonglong): `0`
**notesPanelSort** (qlonglong): `1`
**notesPath** (QString): `/Users/XXXX/ownCloud/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (qlonglong): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (qlonglong): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (bool): `false`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2021-01-27T18.23.59, Note 2021-01-20T18.49.49, Note 2021-01-20T18.22.05, Note 2021-01-12T22.07.33`
**showMatches** (bool): `true`
**showMenuBar** (bool): `false`
**showStatusBar** (bool): `true`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (qlonglong): `0`
**tagsPanelSort** (qlonglong): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (qlonglong): `6`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (qlonglong): `22222`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**PWD**: `/var/folders/z6/cwyqhprd73l06g1rqsqglmc80000gp/T/tmp.ovrOzwZi`
**USER**: `XXXX`
**COMMAND_MODE**: `unix2003`
**__CFBundleIdentifier**: `com.PBE.QOwnNotes`
**LOGNAME**: `XXXX`
**TERM**: `xterm-256color`
**DISPLAY**: `/private/tmp/com.apple.launchd.1TJa52ZiLH/org.macosforge.xquartz:0`
**PATH**: `//anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Little Snitch.app/Contents/Components:/opt/X11/bin`
**SHLVL**: `2`
**TERM_PROGRAM_VERSION**: `440`
**SSH_AUTH_SOCK**: `/private/tmp/com.apple.launchd.szQ8iuXsHY/Listeners`
**TERM_SESSION_ID**: `F77A8EEB-9555-4A6C-8F58-39024421EFFE`
**HOME**: `/Users/XXXX`
**_**: `/usr/bin/open`
**SHELL**: `/bin/bash`
**OLDPWD**: `/Users/XXXX`
**__CF_USER_TEXT_ENCODING**: `0x1F6:0x0:0x0`
**TMPDIR**: `/var/folders/z6/cwyqhprd73l06g1rqsqglmc80000gp/T/`
**TERM_PROGRAM**: `Apple_Terminal`
**XPC_SERVICE_NAME**: `application.com.PBE.QOwnNotes.12897859049.12898616178`
**XPC_FLAGS**: `0x0`
**QT_LOGGING_RULES**: `qt.network.ssl.warning=false`
</details>

**Comment by pbek** [comment]
That's a thing macOS often does...  see #1763 and others... Best turn off the external modification check.

**Comment by fthommen** [comment]
ok, will do.  Thank you for your quick answer.

**Comment by pbek** [comment]
@olegbc1, @netguerrilla12, @mcmc , @marisradu, @CraftingGamerTom, @nils-se, @mid1221213, @ruapho, maybe also still relevant to you...

**Comment by pbek** [comment]
## 21.11.0
- if the current note wasn't edited for a while, it is now possible again that it
  gets updated when there were small changes

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by netguerrilla12** [comment]
I appreciate you continuing to work on these issues, even if they're not high priority. Unfortunately, I've decided to not continue using QOwn Notes. QON has the best UI of all of the MD notes tools I've looked at. Period. However, there were other larger issues which I couldn't get around.The largest issues was the numerous reloads it does when I make the slightest note change. That just makes it too slow for me to use. And that was with only 5K notes imported into QON. That was less than half of my notes. I reported that issue to you elsewhere in GitHub.

**Comment by pbek** [comment]
> QON recently made a huge mess of my tagging, making over 4K notes untagged. 

I imagine that could only happen if all your notes would be gone from your note folder.... Don't you have a backup from the `notes.sqlite` in your note folder? All tags are stored there (if you don't store them inside the note).

**Comment by netguerrilla12** [comment]
Like I said, I don't know how or when it happened. I do have backups, of course. I do a full backup monthly and a differential backup every week that I don't do a full backup. But it's no longer worth the effort to me to try this figure this out. I've already moved several thousand notes to Obsidian.

**Comment by pbek** [comment]
Yeah, of course. I was just curious, because I never had any report that someone was loosing their tags.

**Comment by pbek** [comment]
I will close this issue until there is more information.

**Comment by fthommen** [comment]
fine for me.  I tested the new release and haven't seen the issue so far.  However in the meantime I switched to directly work in NextCloud (that and GitLab are the only places I have MD files) and hardly use QOwnNotes locally any more.  Thanks for your effort anyway

**Comment by pbek** [comment]
Thank you for your feedback. What are you using directly on Nextcloud, if I may ask? Nextcloud Notes?

**Comment by fthommen** [comment]
I'm simply using the [Markdown Editor app](https://apps.nextcloud.com/apps/files_markdown) :-)

**Comment by pbek** [comment]
Nice enough 😁  I myself like the "offline-experience" of a desktop application.
