### ISSUE TITLE
Shortcut for opening link

### ISSUE THREAD

**Issue by capcionista** [pbek/QOwnNotes#203]
A shortcut to open links when the cursor is on the corresponding position in the text would be helpful, so in addition to of ctrl+click something like ctrl+q to get rid of unnecessary mouse use.

**Comment by pbek** [comment]
Thank you for your suggestion.
But afterwards you would need your mouse in the browser, right? :)

**Comment by capcionista** [comment]
For internet links, of course, not for interlinks to notes, would I?

**Comment by pbek** [comment]
true

**Comment by pbek** [comment]
you now can open a link at the current cursor position with <kbd>Ctrl</kbd> + <kbd>Space</kbd> in version 16.06.4

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by pbek** [comment]
I just saw I need to add a `Meta+Space` (that gets interpreted as `Ctrl+Space`) shortcut for OS X, `Cmd+Space` will not work because of Spotlight.

**Comment by pbek** [comment]
Will be fixed in version 16.06.5.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?
