### ISSUE TITLE
[I] The "Custom user interface styling" script settings are gone

### ISSUE THREAD

**Issue by Katarn** [pbek/QOwnNotes#2035]
#### Expected behaviour

The plugin settings window should have a textarea to enter custom styles.

#### Actual behaviour

Textarea is missing

#### Steps to reproduce

1. Open the plugin settings window
2. See to right side of the window

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Чт фев 4 17:03:31 2021`
**Version**: `21.1.8`
**Build date**: `Jan 26 2021`
**Build number**: `809`
**Platform**: `windows`
**Operating System**: `Windows 8.1 Version 6.3 (Build 9600)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application arguments**: `C:\Program Files\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `ru_RU`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `171`
**Calendar items**: `0`
**Enabled scripts**: `2`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_US, ru_RU`
**Language names**: `American English (United States), русский (Россия)`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Заметки`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

### Script `Image preview`

**id**: `1`
**variablesJson**: 
```
{
    "maxWidth": 640
}
```
**identifier**: `image-preview`
**version**: `1.0.1`
**minAppVersion**: `20.6.0`

### Script `Custom user interface styling`

**id**: `2`
**variablesJson**: 
```
{
    "customStylesheet": "QScrollBar:vertical\n{\n    border: 0;\n    margin-right: 0;\n    margin-left: 0;\n    width: 20px;\n}\n\nQFrame\n{\n    border-right-width: 0;\n    padding-bottom: 1px;\n    padding-top: 1px;\n}\n\nQTabWidget::pane {\n    border-right-width: 0;\n    padding: 0;\n}\n\nQPushButton\n{\n    padding: 5px 30px;\n}"
}
```
**identifier**: `custom-stylesheet`
**version**: `0.0.1`
**minAppVersion**: `17.05.7`
</details>

This is creenshot from version 20.7.6:
![image](https://user-images.githubusercontent.com/6339978/106903684-5a2afd00-670b-11eb-936f-aba91b9421ca.png)

and this from current version 21.1.8:
![image](https://user-images.githubusercontent.com/6339978/106903873-99f1e480-670b-11eb-82f2-9dc3fe9a5fe4.png)

Also if I click on "Check for script updates", then I see in debug window:
```
[17:08:52] [scripting] loading script file: C:/Users/User/AppData/Roaming/PBE/QOwnNotes/scripts/image-preview/image-preview.qml
[17:08:52] [warning] QQmlComponent: Component is not ready
[17:08:52] [warning] script errors: (file:///C:/Users/User/AppData/Roaming/PBE/QOwnNotes/scripts/image-preview/image-preview.qml:1:1: ������ �QtQml� �� ���������� import QtQml 2.0 ^)
[17:08:52] [scripting] loading script file: C:/Users/User/AppData/Roaming/PBE/QOwnNotes/scripts/custom-stylesheet/custom-stylesheet.qml
[17:08:52] [warning] QQmlComponent: Component is not ready
[17:08:52] [warning] script errors: (file:///C:/Users/User/AppData/Roaming/PBE/QOwnNotes/scripts/custom-stylesheet/custom-stylesheet.qml:1:1: ������ �QtQml� �� ���������� import QtQml 2.0 ^)
```

The last update of the script was 4 years ago:
https://github.com/qownnotes/scripts/tree/master/custom-stylesheet

A separate problem: the link in the plugin description does not work:
http://docs.qownnotes.org/en/develop/scripting/README.html#add-a-custom-stylesheet

**Comment by pbek** [comment]
Looks like somehow your QtQml libraries have troubles.
Best download QOwnNotes again from https://www.qownnotes.org/installation/windows.html (move away your old application folder).

**Comment by Katarn** [comment]
Yes, that solved the problem. Thanks!

**Comment by pbek** [comment]
Great!
