### ISSUE TITLE
Documentation Overview List of Features arranged

### ISSUE THREAD

**Issue by Fabijenna** [pbek/QOwnNotes#2038]
I have a suggestion of how to split and arrange the features list to be easier to read.
Is it still an issue (I mean not an actual issue in the issues list, but desirable.)

Ill send pull request after discussing or aggreed on.

**Comment by Fabijenna** [comment]
This is not the intented change, just checking whether we agree on the content

**Comment by Fabijenna** [comment]
**APPEARANCE**

Dark mode theme support  

Theming support for the markdown syntax highlighting   

All panels can be placed wherever you want, they can even float or stack (fully dockable)  

Support for freedesktop theme icons, you can use QOwnNotes with your native desktop icons and with your favorite dark desktop theme  

Support for hierarchical note tagging and note subfolders   

Distraction free mode, Full-screen mode and Typewriter mode  

Differences between current note and externally changed note are showed in a dialog  

Markdown highlighting of notes and a markdown preview mode  

Vim mode  


**FEATURES:**

You can use your existing text or markdown files, **no need for an import** most of the times

Evernote import 

Compatible with the Notes application of Nextcloud / ownCloud and mobile and Nextcloud Text  

Support for sharing notes on your ownCloud / Nextcloud server 

Manage your Nextcloud / ownCloud todo lists (Nextcloud tasks or Tasks Plus / Calendar Plus) or use another CalDAV server to sync your tasks to  

Older versions of your notes can be restored from your Nextcloud / ownCloud server  

Trashed notes can be restored from your Nextcloud / ownCloud server  

External changes of note files are watched (notes or note list are reloaded)  

Optional encryption of notes (AES-256 is built in or you can use custom encryption methods like Keybase.io (opens new window) (encryption-keybase.qml (opens new window)) or PGP (encryption-pgp.qml (opens new window))) 

The **notes folder** can be freely chosen (multiple note folders can be used)   

**Sub-string searching of notes is possible** and search results are highlighted in the notes

**Browser extension** to add notes from the selected text, make screenshots or manage your bookmarks

Spellchecking support 

Portable mode for carrying QOwnNotes around on USB sticks   

**Scripting support and an online script repository** (opens new window) where you can install scripts inside the application



**LANGUAGES**

Available in many different languages like English, German, French, Polish, Chinese, Japanese, Russian, Portuguese, Hungarian, Dutch and Spanish  

Your help is very much appreciated to improve these translations or to translate QOwnNotes in more languages

**Comment by pbek** [comment]
Sounds like a good idea. But you dropped a lot of the formatting of the text. Was that on purpose?

Here is the original text:

```markdown
## Features

- The **notes folder** can be **freely chosen** (multiple note folders can be used)
- You can use your **existing text or markdown files**, no need for an import most of the times
- **Sub-string searching** of notes is possible and search results are highlighted in the notes
- **Keyboard shortcuts** are customizable
- **Scripting support** and an online [**script repository**](https://github.com/qownnotes/scripts) where you can install scripts inside the application
- [Browser extension](browser-extension.md) to add notes from the selected text, make screenshots or manage your bookmarks
- **External changes** of note files are **watched** (notes or note list are reloaded)
- Older **versions** of your notes can be **restored** from your **Nextcloud / ownCloud** server
- **Trashed notes** can be **restored** from your **Nextcloud / ownCloud** server
- **Differences** between current note and externally changed note are **showed** in a dialog
- **Markdown highlighting** of notes and a **markdown preview mode**
- [**Spellchecking**](../editor/spellchecking.md) support
- **Compatible** with the Notes application of **Nextcloud / ownCloud** and **mobile** and Nextcloud Text
- Manage your Nextcloud / ownCloud **todo lists** (**Nextcloud tasks** or **Tasks Plus** / **Calendar Plus**) or use another **CalDAV server** to sync your tasks to
- Optional **encryption** of notes (AES-256 is built in or you can use custom encryption methods like **[Keybase.io](https://keybase.io/)** ([encryption-keybase.qml](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/encryption-keybase.qml)) or **PGP** ([encryption-pgp.qml](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/encryption-pgp.qml)))
- **Dark mode theme support**
- **Theming support** for the **markdown syntax highlighting**
- All **panels can be placed wherever you want**,  they can even **float** or **stack** (fully dockable)
- Support for **freedesktop theme icons**, you can use QOwnNotes with your **native desktop icons** and with your favorite **dark desktop theme**
- Support for **hierarchical note tagging** and **note subfolders**
- Support for **sharing notes** on your **ownCloud** / **Nextcloud** server
- **Portable mode** for carrying QOwnNotes around on USB sticks
- **Vim mode**
- **Distraction free mode**, **Full-screen mode** and **Typewriter mode**
- **Evernote import**
- **Available in many different languages** like English, German, French, Polish, Chinese, Japanese, Russian, Portuguese, Hungarian, Dutch and Spanish
  - [Your help](../contributing/translation.md) is very much appreciated to improve these translations or to translate QOwnNotes in more languages
````

You you want to move the lines around without dropping formatting? 😅

**Comment by pbek** [comment]
As always you can also submit a pull requests by editing the text directly on: https://github.com/pbek/QOwnNotes/edit/develop/webpage/src/getting-started/overview.md 😉

**Comment by Fabijenna** [comment]
"you dropped a lot of the formatting of the text. Was that on purpose?" Yes, I needed the better overview from the website. ;-)

**Comment by pbek** [comment]
I think we are done here, thank you very much!
