### ISSUE TITLE
Image importing gifs results in png conversion

### ISSUE THREAD

**Issue by jjisnow** [pbek/QOwnNotes#2039]
Hi I'm trying to import gif animations via the image importing dialogue, but when I succeed, the animated gif is converted to a still png. When I import the full size gif manually by copying and posting the file and linking it via the ![title](location of file) format, it is imported full size only. I would rather be able to resize the animation. 
Can:
a. the animated gif import be fixed?
b. the animated gif be resized to something a bit smaller.

**Comment by pbek** [comment]
I'm sorry. It seems QImage can only read GIFs: https://doc.qt.io/qt-5/qimage.html#reading-and-writing-image-files
In the *General settings* there is a checkbox to resize images in general, do you have that on?

**Comment by pbek** [comment]
And yes, all images that are inserted into the media folder that way are currently stored as png: https://github.com/pbek/QOwnNotes/blob/e0675e86877b3c42e340581b8f52d2e5e7be5282/src/dialogs/imagedialog.cpp#L140

But could put them to a place of your choosing and inserting them without copying to the media folder automatically.

**Comment by jjisnow** [comment]
I couldn't find the resize images in general checkbox under the settings
menu. I found the "Scale images down when inserted into notes" checkbox
under Settings - General - Notes. This gives you a specific resolution to
scale down to, but I was hoping that it could rescale gifs for presentation.

**Comment by pbek** [comment]
Like I say, QImage can't write GIFs. 😬

**Comment by jjisnow** [comment]
Thanks for looking into it!  I'm a little confused, because a few weeks
ago, I successfully imported a gif into the note because there's a file in
the form ../media/2-1234567890.gif in the media folder with a correctly
scaled image - How are gifs added correctly into a note?

**Comment by pbek** [comment]
You should be able to insert local gifs into a note with the dialog as long you didn't tell the dialog to resize or crop it. Are you sure you resized the gif with the *Insert image* dialog?

**Comment by jjisnow** [comment]
i'm guessing i must have resized it separately.

**Comment by pbek** [comment]
Yes, I suppose so. Qt to my knowledge never had the support to write GIFs. 😁
