### ISSUE TITLE
Inline images in "media" don't follow the note moved to other folder

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#204]
When we put inline image to the note the app copies it to "media" dir and puts a relative link to note text. 

When we move the note to another note folder within the app inline images from "media" don't follow the note and relative link becomes broken.

Also it's worth mentioning that images once copied to "media" stays there even after link/note is deleted. Media gets bigger and bigger and may require manual clearing after a while.

Above things are perfectly clear from the app logic but may surprise users.

**Comment by pbek** [comment]
Thank you for making that clear. What in your eyes should happen if a note is copied and the same media files are linked from different notes? I don't know if that can be resolved automatically.... Although I have planned a function to remove orphaned media files...

**Comment by pbek** [comment]
The latter was already stated in #141.

**Comment by Maboroshy** [comment]
I know how to make it resolved automatically via shell script. 

My first thoughts for logic is:
1) Get the list of all files in media dirs for each note folder;
2) Get the list of all relative links to "media" dir for each note folder;
2) Compare link list with files list;
3) If some items missing in the files list - find the file with the same name in all folder lists and hardlink/copy the file to appropriate "media" dir;
4) If some items missing from the links list - delete the files with no links.

The "find linked files" part can be done in-app on the move note action for a specific note. This will need much less resources than the shell script.

**Comment by pbek** [comment]
sounds like a plan :)

**Comment by Maboroshy** [comment]
Ok then. I will put the shell script to wiki when I'll make it. That will do for me.

**Comment by pbek** [comment]
## 16.09.16
- you now can **delete orphaned images** in a dialog with an image preview
    - you will find a new menu entry in the edit menu to open the dialog 

There now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment]
It works but it's a bit broken.

1. While it found all special dummies I use to test same [bash-note](https://github.com/Maboroshy/Bash-note) functionality it also found 2 files that are actually used in note:
`![htu5r5u6](file:///storage/emulated/0/Android/data/com.ryeeeeee.markdownx/files/notes/Know/media/505671508.jpg)` 
`![pu2u17v5](file:///storage/emulated/0/Android/data/com.ryeeeeee.markdownx/files/notes/Know/media/936145377.jpg)`

2. Also it didn't found some files with wrong path [bash-note](https://github.com/Maboroshy/Bash-note) found, like:
`![ 0`
`этап](file://%D0%AF%D0%BF%D0%BE%D0%BD%D1%81%D0%BA%D0%B8%D0%B9%20%D0%BE%D0%BC%D0%BB%D0%B5%D1%82%20%E2%80%94%20%D1%80%D0%B5%D1%86%D0%B5%D0%BF%D1%82%20%D1%81%20%D0%BF%D0%BE%D1%88%D0%B0%D0%B3%D0%BE%D0%B2%D1%8B%D0%BC%D0%B8%20%D1%84%D0%BE%D1%82%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F%D0%BC%D0%B8%20%D0%BD%D0%B0%20Foodclub.ru_files/_1.jpg " 0 этап")`
This file is in media directory but there's no `media` in path. I guess the new line in markdown code puts new feature upside down. It took me some effort to deal with it too.

I did like the UI. I think that would be good if there'd be some `delete all` key there and maybe a path of an image starting with `media`. I have sub-folders in media, and generally feel safer when I see the path of something that I'm going to delete. But maybe that's just me.

**Comment by pbek** [comment]
Thank you for your feedback!

> 1 & 2

the system currently only detects the media links QOwnNotes generates

> delete all

you can simply do a `Ctrl + A` and delete all files (`Delete` button also works)

> path

there is currently no need for that because only the media folder is scanned (not it's subfolders), since QOwnNotes isn't using them

**Comment by pbek** [comment]
If you want to play with the regular expression, that's the line: <https://github.com/pbek/QOwnNotes/blob/6cb2b99351ef82d0cc1c5bc0019cc286a9a627c8/src/dialogs/orphanedimagesdialog.cpp#L39>

**Comment by Maboroshy** [comment]
> the system currently only detects the media links QOwnNotes generates

This limit can be overcome if you want to?

I've played with regexps more that I really wanted to. :sweat_smile:

The bash-note regexp for inline images is `!\[[^]]*] *([^)]*)`, posix basic. I think I've already posted it in some other issue. 

To use it with newline characters I had to replace new lines with spaces for parsing. 

That combination can handle almost any imaginable markdown spec link.

Next you'll need is to strip the markdown code to file link and check if its relative or absolute.

It's all there in bash-note, lines 430-485.

**Comment by pbek** [comment]
Making that work for multiple note folders and all operating systems would need some considerable work and testing I reckon... I'm open for pull requests. 😸

**Comment by Maboroshy** [comment]
As far as I know the main difference is Win `\` against posix `/` for Mac and Linux.

The main problem with pull requests for the app is that I don't know C++ and it's a steep learning curve for the first programming language to learn in free time.

I'll make a fancy UI for bash-note much faster. :smile:

**Comment by pbek** [comment]
> I don't know C++ and it's a steep learning curve

I only use it because of Qt, I'm not very fond of it neither...
But it's a good skill to have.

> I'll make a fancy UI for bash-note much faster. 

Then I've right the thing for you: <http://cmdlauncher.topbug.net/>

**Comment by Maboroshy** [comment]
It's a good skill for an IT specialist and I'm not the one. For now I've decided if I ever get enough time and energy to learn proper programming language I'll start with Python. The compiling makes fast learning C languages not that funny. You can't just type and see the result like with interpreted languages.

For GUI I was thinking about more traditional kdialog and/or zenity. Don't know if I go that route though. The user-base of my script, which is me, not really fond of GUIs.

**Comment by pbek** [comment]
> The compiling makes fast learning C languages not that funny

the compiling is the least of all troubles with C / C++ :)
far more troublesome is that you have to take care of so many things yourself...

> The user-base of my script, which is me, not really fond of GUIs.

:D
