### ISSUE TITLE
When click Ctrl-N to created a new notes and edit... after lost focus notes not saved and lost 

### ISSUE THREAD

**Issue by kenneth-ran** [pbek/QOwnNotes#2040]
Hi Sir
  I got a problem when click Ctrl-N to created a new Notes...

  and edit some content.... when i cursor switch to another place 

 I will got a not saved all content notes...

Normally it's happen when I first type heading in QOwnNotes

if I edit below content first, then 2nd go modify heading text...

won't happen this problem...

Could watch the video I recorded. thank sir !

https://user-images.githubusercontent.com/11792366/107110810-da756d80-6885-11eb-8880-cf03f33f985d.mp4

**Comment by pbek** [comment]
Thank you for reporting.
Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting `Debug` in `Options`).

**Comment by pbek** [comment]
And can you please explain in more detail and step by step what you did, what happened and what you expected.

**Comment by kenneth-ran** [comment]
Hi Sir, Here is today my error logs.
----

The original caption is "210218 - IE129 取料單用量計算-類別設定檔調整 (IE186 取料單類別設定).md"
but where i typed , preview still not update... and after i lost focus click another document and back..
noted still old content... ( can see the log show "21".. i think maybe here....)

**[二月 19 16:26:38] [debug]: stored note:  Note: <id>1 <name>"21" <fileName>"21.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false**

==== FULL LOG :

[二月 19 16:25:53] [debug]: cloudConnection:  CloudConnection: <id>2 <name>"nextcloud.freenfly.net" <serverUrl>"http://nextcloud.freenfly.net/nc" <username>"kenneth" <priority>0
[二月 19 16:25:55] [debug]: cloudConnection:  CloudConnection: <id>2 <name>"nextcloud.freenfly.net" <serverUrl>"http://nextcloud.freenfly.net/nc" <username>"kenneth" <priority>0
[二月 19 16:25:57] [debug]: cloudConnection:  CloudConnection: <id>2 <name>"nextcloud.freenfly.net" <serverUrl>"http://nextcloud.freenfly.net/nc" <username>"kenneth" <priority>0
[二月 19 16:25:58] [debug]: storing note file:  "Note 2021-02-18T15.32.40.md"
[二月 19 16:25:58] [debug]: stored note:  Note: <id>1 <name>"Note 2021-02-18T15.32.40" <fileName>"Note 2021-02-18T15.32.40.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false
[二月 19 16:25:58] [debug]: storeUpdatedNotesToDisk  - 'count':  1
[二月 19 16:25:58] [status]: Stored 1 note(s) to disk
[二月 19 16:25:58] [debug]: storeUpdatedNotesToDisk  - 'wasStripped'
[二月 19 16:25:59] [debug]: cloudConnection:  CloudConnection: <id>2 <name>"nextcloud.freenfly.net" <serverUrl>"http://nextcloud.freenfly.net/nc" <username>"kenneth" <priority>0
[二月 19 16:26:03] [debug]: cloudConnection:  CloudConnection: <id>2 <name>"nextcloud.freenfly.net" <serverUrl>"http://nextcloud.freenfly.net/nc" <username>"kenneth" <priority>0
[二月 19 16:26:08] [debug]: storing note file:  "Note 2021-02-18T15.32.40.md"
[二月 19 16:26:08] [debug]: stored note:  Note: <id>1 <name>"Note 2021-02-18T15.32.40" <fileName>"Note 2021-02-18T15.32.40.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false
[二月 19 16:26:08] [debug]: storeUpdatedNotesToDisk  - 'count':  1
[二月 19 16:26:08] [status]: Stored 1 note(s) to disk
[二月 19 16:26:08] [debug]: storeUpdatedNotesToDisk  - 'wasStripped'
[二月 19 16:26:09] [debug]: cloudConnection:  CloudConnection: <id>2 <name>"nextcloud.freenfly.net" <serverUrl>"http://nextcloud.freenfly.net/nc" <username>"kenneth" <priority>0
[二月 19 16:26:18] [debug]: storing note file:  "Note 2021-02-18T15.32.40.md"
[二月 19 16:26:18] [debug]: stored note:  Note: <id>1 <name>"Note 2021-02-18T15.32.40" <fileName>"Note 2021-02-18T15.32.40.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false
[二月 19 16:26:18] [debug]: storeUpdatedNotesToDisk  - 'count':  1
[二月 19 16:26:18] [status]: Stored 1 note(s) to disk
[二月 19 16:26:37] [debug]: cloudConnection:  CloudConnection: <id>2 <name>"nextcloud.freenfly.net" <serverUrl>"http://nextcloud.freenfly.net/nc" <username>"kenneth" <priority>0
[二月 19 16:26:38] [debug]: handleNoteTextFileName  - 'name' was changed:  "21"
[二月 19 16:26:38] [debug]: storeNoteTextFileToDisk  - 'noteFileWasRenamed':  false
[二月 19 16:26:38] [debug]: storing note file:  "21.md"
[二月 19 16:26:38] [debug]: storeNoteTextFileToDisk  - 'trashItem':  TrashItem: <id>0 <fileName>"Note 2021-02-18T15.32.40.md" <noteSubFolderId>0 <_fullNoteFilePath>"D:/Aaron_Docs/My_Notes/Note 2021-02-18T15.32.40.md" <relativePath>""
[二月 19 16:26:38] [debug]: doTrashing  - 'destinationFileName':  "D:/Aaron_Docs/My_Notes\\trash\\105"
[二月 19 16:26:38] [info]: "Renamed note-file was removed: D:/Aaron_Docs/My_Notes/Note 2021-02-18T15.32.40.md"
[二月 19 16:26:38] [debug]: stored note:  Note: <id>1 <name>"21" <fileName>"21.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false
[二月 19 16:26:38] [debug]: storeUpdatedNotesToDisk  - 'count':  1
[二月 19 16:26:38] [status]: Stored 1 note(s) to disk
[二月 19 16:26:39] [debug]: storeUpdatedNotesToDisk  - 'wasStripped'
[二月 19 16:26:39] [debug]: loadNoteDirectoryList
[二月 19 16:26:39] [debug]: reloadTagTree
[二月 19 16:26:39] [debug]: handleScriptingNotesTagUpdating
[二月 19 16:26:39] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(0)
[二月 19 16:26:40] [debug]: filterNotesByTag  - 'tags':  QVector(35)
[二月 19 16:26:40] [debug]: filterNotesByTag  - 'noteIdList':  QVector(1, 33, 45, 41, 5, 34, 4, 3)
[二月 19 16:26:40] [debug]: filterNotesByTag  - 'tags':  QVector(35)
[二月 19 16:26:40] [debug]: filterNotesByTag  - 'noteIdList':  QVector(1, 33, 45, 41, 5, 34, 4, 3)
[二月 19 16:26:40] [debug]: cloudConnection:  CloudConnection: <id>2 <name>"nextcloud.freenfly.net" <serverUrl>"http://nextcloud.freenfly.net/nc" <username>"kenneth" <priority>0
[二月 19 16:26:40] [debug]:  added to history:  NoteHistoryItem: <noteName>"21" <noteSubFolderPathData>"" <cursorPosition>4 <relativeScrollBarPosition>0
[二月 19 16:27:47] [debug]: filterNotesByTag  - 'tags':  QVector(83)
[二月 19 16:27:47] [debug]: filterNotesByTag  - 'noteIdList':  QVector(49)
[二月 19 16:27:47] [debug]: filterNotesByTag  - 'tags':  QVector(35)
[二月 19 16:27:47] [debug]: filterNotesByTag  - 'noteIdList':  QVector(1, 33, 45, 41, 5, 34, 4, 3)
[二月 19 16:27:57] [debug]: filterNotesByTag  - 'tags':  QVector(36)
[二月 19 16:27:57] [debug]: filterNotesByTag  - 'noteIdList':  QVector(33)
[二月 19 16:27:57] [debug]: filterNotesByTag  - 'tags':  QVector(35)
[二月 19 16:27:57] [debug]: filterNotesByTag  - 'noteIdList':  QVector(1, 33, 45, 41, 5, 34, 4, 3)
[二月 19 16:27:59] [debug]: cloudConnection:  CloudConnection: <id>2 <name>"nextcloud.freenfly.net" <serverUrl>"http://nextcloud.freenfly.net/nc" <username>"kenneth" <priority>0
[二月 19 16:27:59] [debug]: filterNotesByTag  - 'tags':  QVector(35)
[二月 19 16:27:59] [debug]: filterNotesByTag  - 'noteIdList':  QVector(33, 45, 41, 5, 34, 4, 3)
[二月 19 16:27:59] [debug]: reloadTagTree
[二月 19 16:27:59] [debug]: handleScriptingNotesTagUpdating
[二月 19 16:28:00] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(0)
[二月 19 16:28:08] [debug]: handleNoteTextFileName  - 'name' was changed:  "210218 - IE129 取料單用量計算-類別設定檔調整 (IE186 取料單類別設定)"
[二月 19 16:28:08] [debug]: storeNoteTextFileToDisk  - 'noteFileWasRenamed':  false
[二月 19 16:28:08] [debug]: storing note file:  "210218 - IE129 取料單用量計算-類別設定檔調整 (IE186 取料單類別設定).md"
[二月 19 16:28:08] [debug]: storeNoteTextFileToDisk  - 'trashItem':  TrashItem: <id>0 <fileName>"21.md" <noteSubFolderId>0 <_fullNoteFilePath>"D:/Aaron_Docs/My_Notes/21.md" <relativePath>""
[二月 19 16:28:08] [debug]: doTrashing  - 'destinationFileName':  "D:/Aaron_Docs/My_Notes\\trash\\106"
[二月 19 16:28:08] [info]: "Renamed note-file was removed: D:/Aaron_Docs/My_Notes/21.md"
[二月 19 16:28:08] [debug]: stored note:  Note: <id>1 <name>"210218 - IE129 取料單用量計算-類別設定檔調整 (IE186 取料單類別設定)" <fileName>"210218 - IE129 取料單用量計算-類別設定檔調整 (IE186 取料單類別設定).md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false
[二月 19 16:28:08] [debug]: storeUpdatedNotesToDisk  - 'count':  1
[二月 19 16:28:08] [status]: Stored 1 note(s) to disk
[二月 19 16:28:08] [debug]: storeUpdatedNotesToDisk  - 'wasStripped'
[二月 19 16:28:08] [debug]: loadNoteDirectoryList
[二月 19 16:28:08] [debug]: reloadTagTree
[二月 19 16:28:08] [debug]: handleScriptingNotesTagUpdating
[二月 19 16:28:08] [debug]:  difference1:  Tag: <id>35 <name>"favorite" <parentId>0
[二月 19 16:28:09] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(0)
[二月 19 16:28:09] [debug]: filterNotesByTag  - 'tags':  QVector(35)
[二月 19 16:28:09] [debug]: filterNotesByTag  - 'noteIdList':  QVector(33, 45, 41, 1, 5, 34, 4, 3)
[二月 19 16:28:09] [debug]: filterNotesByTag  - 'tags':  QVector(35)
[二月 19 16:28:09] [debug]: filterNotesByTag  - 'noteIdList':  QVector(33, 45, 41, 1, 5, 34, 4, 3)
[二月 19 16:28:10] [debug]: cloudConnection:  CloudConnection: <id>2 <name>"nextcloud.freenfly.net" <serverUrl>"http://nextcloud.freenfly.net/nc" <username>"kenneth" <priority>0
[二月 19 16:28:11] [debug]: cloudConnection:  CloudConnection: <id>2 <name>"nextcloud.freenfly.net" <serverUrl>"http://nextcloud.freenfly.net/nc" <username>"kenneth" <priority>0
[二月 19 16:28:11] [debug]: notesDirectoryWasModified:  "D:/Aaron_Docs/My_Notes"
[二月 19 16:28:11] [status]: Notes directory was modified externally
[二月 19 16:28:11] [debug]: buildNotesIndex  - 'noteSubFolderId':  0
[二月 19 16:28:11] [debug]: setupNoteFolderTables  - 'database version':  14
[二月 19 16:28:11] [debug]: cloudConnection:  CloudConnection: <id>2 <name>"nextcloud.freenfly.net" <serverUrl>"http://nextcloud.freenfly.net/nc" <username>"kenneth" <priority>0
[二月 19 16:28:11] [debug]: fetchShares  - 'url':  QUrl("http://nextcloud.freenfly.net/nc/ocs/v2.php/apps/files_sharing/api/v1/shares")
[二月 19 16:28:11] [debug]: notesWereModified:  "210218 - IE129 取料單用量計算-類別設定檔調整 (IE186 取料單類別設定).md"
[二月 19 16:28:11] [debug]: updateNoteText:  false
[二月 19 16:28:11] [debug]: setCurrentNote  - 'note':  Note: <id>1 <name>"210218 - IE129 取料單用量計算-類別設定檔調整 (IE186 取料單類別設定)" <fileName>"210218 - IE129 取料單用量計算-類別設定檔調整 (IE186 取料單類別設定).md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false  - 'updateNoteText':  false  - 'updateSelectedNote':  true
[二月 19 16:28:11] [debug]:  added to history:  NoteHistoryItem: <noteName>"210218 - IE129 取料單用量計算-類別設定檔調整 (IE186 取料單類別設定)" <noteSubFolderPathData>"" <cursorPosition>805 <relativeScrollBarPosition>0
[二月 19 16:28:17] [debug]: Reply from  "/nc/ocs/v2.php/apps/files_sharing/api/v1/shares"
[二月 19 16:28:17] [debug]: Reply from share api
[二月 19 16:28:17] [debug]: updateNoteShareStatusFromShare  - 'status':  "ok\n"
[二月 19 16:28:39] [warning]:   OpenType support missing for "PMingLiU", script 12
[二月 19 16:28:39] [warning]:   OpenType support missing for "Arial", script 12
[二月 19 16:28:39] [warning]:   OpenType support missing for "SimSun", script 12
[二月 19 16:28:39] [warning]:   OpenType support missing for "MS UI Gothic", script 12
[二月 19 16:28:39] [warning]:   OpenType support missing for "PMingLiU", script 11
[二月 19 16:28:39] [warning]:   OpenType support missing for "Arial", script 11
[二月 19 16:28:39] [warning]:   OpenType support missing for "SimSun", script 11
[二月 19 16:28:39] [warning]:   OpenType support missing for "MS UI Gothic", script 11
[二月 19 16:28:39] [warning]:   OpenType support missing for "PMingLiU", script 32
[二月 19 16:28:39] [warning]:   OpenType support missing for "Arial", script 32
[二月 19 16:28:39] [warning]:   OpenType support missing for "SimSun", script 32
[二月 19 16:28:39] [warning]:   OpenType support missing for "MS UI Gothic", script 32
[二月 19 16:28:39] [warning]:   OpenType support missing for "PMingLiU", script 13
[二月 19 16:28:39] [warning]:   OpenType support missing for "Arial", script 13
[二月 19 16:28:39] [warning]:   OpenType support missing for "SimSun", script 13
[二月 19 16:28:39] [warning]:   OpenType support missing for "MS UI Gothic", script 13
[二月 19 16:28:39] [warning]:   OpenType support missing for "PMingLiU", script 20
[二月 19 16:28:39] [warning]:   OpenType support missing for "Arial", script 20
[二月 19 16:28:39] [warning]:   OpenType support missing for "SimSun", script 20
[二月 19 16:28:39] [warning]:   OpenType support missing for "MS UI Gothic", script 20
[二月 19 16:28:40] [warning]:   OpenType support missing for "Microsoft JhengHei UI", script 12
[二月 19 16:28:40] [warning]:   OpenType support missing for "PMingLiU", script 12
[二月 19 16:28:40] [warning]:   OpenType support missing for "Arial", script 12
[二月 19 16:28:40] [warning]:   OpenType support missing for "SimSun", script 12
[二月 19 16:28:40] [warning]:   OpenType support missing for "MS UI Gothic", script 12
[二月 19 16:28:40] [warning]:   OpenType support missing for "Microsoft JhengHei UI", script 11
[二月 19 16:28:40] [warning]:   OpenType support missing for "PMingLiU", script 11
[二月 19 16:28:40] [warning]:   OpenType support missing for "Arial", script 11
[二月 19 16:28:40] [warning]:   OpenType support missing for "SimSun", script 11
[二月 19 16:28:40] [warning]:   OpenType support missing for "MS UI Gothic", script 11
[二月 19 16:28:40] [warning]:   OpenType support missing for "Microsoft JhengHei UI", script 32
[二月 19 16:28:40] [warning]:   OpenType support missing for "PMingLiU", script 32
[二月 19 16:28:40] [warning]:   OpenType support missing for "Arial", script 32
[二月 19 16:28:40] [warning]:   OpenType support missing for "SimSun", script 32
[二月 19 16:28:40] [warning]:   OpenType support missing for "MS UI Gothic", script 32
[二月 19 16:28:40] [warning]:   OpenType support missing for "Microsoft JhengHei UI", script 13
[二月 19 16:28:40] [warning]:   OpenType support missing for "PMingLiU", script 13
[二月 19 16:28:40] [warning]:   OpenType support missing for "Arial", script 13
[二月 19 16:28:40] [warning]:   OpenType support missing for "SimSun", script 13
[二月 19 16:28:40] [warning]:   OpenType support missing for "MS UI Gothic", script 13
[二月 19 16:28:40] [warning]:   OpenType support missing for "Microsoft JhengHei UI", script 20
[二月 19 16:28:40] [warning]:   OpenType support missing for "PMingLiU", script 20
[二月 19 16:28:40] [warning]:   OpenType support missing for "Arial", script 20
[二月 19 16:28:40] [warning]:   OpenType support missing for "SimSun", script 20
[二月 19 16:28:40] [warning]:   OpenType support missing for "MS UI Gothic", script 20
[二月 19 16:28:41] [debug]: cloudConnection:  CloudConnection: <id>2 <name>"nextcloud.freenfly.net" <serverUrl>"http://nextcloud.freenfly.net/nc" <username>"kenneth" <priority>0
[二月 19 16:28:44] [debug]: cloudConnection:  CloudConnection: <id>2 <name>"nextcloud.freenfly.net" <serverUrl>"http://nextcloud.freenfly.net/nc" <username>"kenneth" <priority>0
[二月 19 16:28:44] [debug]: Reply from  "/nc"
[二月 19 16:28:44] [debug]: Reply from main server url
[二月 19 16:28:46] [debug]: Reply from  "/nc/ocs/v1.php"
[二月 19 16:28:46] [debug]: Reply from ownCloud test page
[二月 19 16:28:46] [debug]: Reply from  "/nc/ocs/v1.php/cloud/capabilities"
[二月 19 16:28:46] [debug]: Reply from capabilities page
[二月 19 16:28:46] [debug]: Reply from  "/nc/index.php/apps/qownnotesapi/api/v1/note/app_info"
[二月 19 16:28:46] [debug]: Reply from app info

**Comment by pbek** [comment]
Can you please post the output from the debug settings (see issue template).
And can you please explain in more detail and step by step what you did, what happened and what you expected.
