### ISSUE TITLE
pdf and html export issues; media file name and resizing

### ISSUE THREAD

**Issue by stavpup** [pbek/QOwnNotes#2042]
Hello,

This is a sample note with an image. The note was not created with QON, but transferred from another application.
In practice we would like to migrate thousands of files like that.
One thing we notice is that because the media file is not named "qownnotes-media-xxxxxx.png" but otherwize, export to html fails to present the image to html. Although in QON it is presented fine. Imaging having to migrate thousands of notes to QON and have to rename all those images.

Second is that suppose you have a note with a large image, when printing to pdf, it does not fit A4 page size, so ideally you would want it to "shrink to fit". I don't think that there are people out there that would print notes in A3 paper size. 

Hope I am making sense :-)

[test.zip](https://github.com/pbek/QOwnNotes/files/5939251/test.zip)

**Comment by pbek** [comment]
Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting `Debug` in `Options`).

**Comment by pbek** [comment]
Don't bother, I already found it out, you forgot the `.png` in your image link `![da33bfb55d44f3cee92d9528e0c0d1d6.png](media/0c8445cc71a845f1b664db993472c94b)`.

It needs to be `![da33bfb55d44f3cee92d9528e0c0d1d6.png](media/0c8445cc71a845f1b664db993472c94b.png)`, then it works.
