### ISSUE TITLE
How to add multiple tags?

### ISSUE THREAD

**Issue by moong8te** [pbek/QOwnNotes#2044]
Hello Qownnotes community,

There are several applications that use tag systems to organize data.

Adobe Lighroom for instance uses tags to organize photos.

In lightroom you can select a single picture prepare to add a tag and simply type 

holiday , sun, beach, people, bluesky

This results in 5 individual tags beeing added to that photo that can later be searched for individually.

I would love to do the same in Qownnotes and just click "add tag" or press "alt + shift + a" just once and then type all tags I want to add with some sort of separation.

So far I did not find any documentation about this for Qownnotes and obviously adding a tag called

holiday , sun, beach, people, bluesky

would currently result in a single tag for that note instead of 5 separate tags.

In case I missed something pointing me in the right direction would be much appreciated.

Best

**Comment by pbek** [comment]
Hi there. There are several ways to add tags.

- **Note tags panel** and adding them by typing them in and pressing enter
- **Tags panel** by double clicking them
- Via the Scripting engine in any way you like

Or (in addition) you can even use a script to mange your tags as text inside your notes.

**Comment by pbek** [comment]
Plus there is a script `Add Multiple tags` in the script repository...

**Comment by moong8te** [comment]
Hello pbek,

thank you very much for your quick reply which sounds very promising.
->"Note tags panel and adding them by typing them in and pressing enter"

This solution would already be sufficient for me but so far I was not able to get it to work.
I can clearly identify the tags panel: window -> panels -> show tags panel
The input field reads "find or create tag"

To start from scratch I select "new note" from the toolbar which creates an new note with headline "note + date + time"

I then switch to the tag toolbar and type rainbow.
When I press enter I do not see this tag added.
The text remains in the typing field of the tags panel.
The list of the tags panel begins to display the number of all tagged and untagged notes as I newer used this tag before.
When I then delete rainbow and type a tag I used before it shows me all notes that have that tag again whith adding the tag to the currently active note.

I would love to just type enter type enter.... a number of tags but it seems I am doeing something wrong.

___

I then tried your script suggestion.

scripting -> find sripts.... -> add multiple tags.

After installing the script its active as can be seen by the checked box.
I also restarted QOwnnotes for possible changes to take affect.

The script tells me:"This script creates a menu item and a button with which you can add space separated tags to the current note."

Unfortunately I am not able to find the entry in any menu item or any button related to the script in the toolbars.

I also checked scripting -> custom actions, which has an arrow indicating it should expand to reveal the custom actions - which is not the case for me.

I just upgraded to 21.2.0 before trying the above.

**Comment by moong8te** [comment]
One addition 

I added a new tag by typing it into the tag panel entry field (find or create a tag)

After pressing enter for several times the tag was accepted - meaning it was added to my tags but was not added to the currently active note.

The new tag then was visible in my "tag repository" without showing a number meaning unassigned to any note.

**Comment by pbek** [comment]
> ->"Note tags panel and adding them by typing them in and pressing enter"
> This solution would already be sufficient for me but so far I was not able to get it to work.
> I can clearly identify the tags panel: window -> panels -> show tags panel
> The input field reads "find or create tag"

No no, this is the **Tags panel**, I was talking about the **Note tags panel**! 😁

**Comment by pbek** [comment]
> Plus there is a script Add Multiple tags in the script repository...

but that would be the quickest way to add a lot of tags at the same time (if you know their exact name).

**Comment by moong8te** [comment]
> > ->"Note tags panel and adding them by typing them in and pressing enter"
> > This solution would already be sufficient for me but so far I was not able to get it to work.
> > I can clearly identify the tags panel: window -> panels -> show tags panel
> > The input field reads "find or create tag"
> 
> No no, this is the **Tags panel**, I was talking about the **Note tags panel**! 😁

All right, so then this is the "notes tags panel" right?
![image](https://user-images.githubusercontent.com/71926506/107419197-cb0d5300-6b17-11eb-945c-1a0484773627.png)

When I press add tag it changes to this:
![image](https://user-images.githubusercontent.com/71926506/107419315-f132f300-6b17-11eb-80f9-2c15345ed195.png)

I can then enter a single tag, press enter and we are back to the start.
![image](https://user-images.githubusercontent.com/71926506/107419445-1b84b080-6b18-11eb-811a-83ddb0e4a277.png)

meaning I have to now either take my hands off the keyboard and click "add tag" again or I have to press "alt+shift+a"

Is this correct so far or did I just miss the shortcut you already tried to point me to?

I do understand that my original idea of the following is currently not working:
![image](https://user-images.githubusercontent.com/71926506/107420074-cac18780-6b18-11eb-8fea-22e0726f6299.png)

**Comment by moong8te** [comment]
> > Plus there is a script Add Multiple tags in the script repository...
> 
> but that would be the quickest way to add a lot of tags at the same time (if you know their exact name).

Ok so most of the time I now the tags I want to add to a note i.e. linux, configuration, wifi, wpa
I did install that script but I cannot identify the location or button to press to get the input dialog or just about anything from that script to show up in the QOwnnotes user interface.

Any chance you can point me where to look at 8-)

**Comment by pbek** [comment]
You can only enter one tag at a time in the **Note tags panel** (like the placeholder text in the edit field suggests 😉), that's why I suggested a script for you...

> Plus there is a script `Add Multiple tags` in the script repository...

...this one

**Comment by moong8te** [comment]
> You can only enter one tag at a time in the **Note tags panel** (like the placeholder text in the edit field suggests 😉), that's why I suggested a script for you...
> 
> > Plus there is a script `Add Multiple tags` in the script repository...
> 
> ...this one

Ok, understood which is why I did install the script after reading your initial post with this suggestion.
Maybe this should be too easy but for some reason it is not in my case.
Maybe my QOwnnotes workplace is mixed up or there is something else I miss.

So my simple question is after installing the script how do I run or use it to enter multiple tags?

Other then in the script description I am unable to locate the menu item or button to get started with this script.

![image](https://user-images.githubusercontent.com/71926506/107424429-eb401080-6b1d-11eb-82d5-890012c0ae23.png)

**Comment by moong8te** [comment]
Ok, reloading the scripting engine and reading the log reveals that something seems to be wrong I need to figure out first to get the add multiple tags script running.

That is why I did see no buttons or menu items after installing it:

[21:34:17] [warning] QQmlComponent: Component is not ready
[21:34:17] [warning] script errors: (file:///C:/Users/<username>/AppData/Roaming/PBE/QOwnNotes/scripts/add-multiple-tags/add-multiple-tags.qml:1:1: Modul "QtQml" is not installed import QtQml 2.0 ^)
[21:34:17] [status] The scripting engine was reloaded

**Comment by pbek** [comment]
Seems like your QtQml library is broken, best download QOwnNotes again.
With the script you should get a menu item (scripting menu) to enter tags...

**Comment by moong8te** [comment]
Hello pbek,

thank you so much.  Overwriting my QOwnnotes folder with the files from a fresh download fixed it.

add multiple tags is now showing under 

scripting -> customer actions -> add multiple tags

and works like a charm.

case closed

**Comment by pbek** [comment]
Great it worked! 😁  If you need some special handling you can do a lot with scripts https://www.qownnotes.org/scripting/ 😉
