### ISSUE TITLE
How to translate the navigation bar at qownnotes.org

### ISSUE THREAD

**Issue by amirkbrpr** [pbek/QOwnNotes#2045]
Hi,
I translated all the application and the website in my language, but I couldn't find terms of the navigation bar at qownnotes.org in Crowdin. Could you please help me to translate them because they've been left in machine translation?
Thanks,

**Comment by pbek** [comment]
Thank you very much!
The menu items are in the `config.js`, like https://github.com/pbek/QOwnNotes/blob/666eeb204c9f4ec7996521e532982b55ec4e492f/webpage/src/.vuepress/config.js#L236-L267.

A new block is needed for new languages.

**Comment by amirkbrpr** [comment]
Could you please enter these words for Persian?
Getting started: شروع
Installation: نصب
Blog:وبلاگ
Changelog: گزارش تغییرات
Contact: تماس
Donate: کمک مالی
Languages: زبان

**Comment by Fabijenna** [comment]
I’ll do it 
Thank you

**Comment by Fabijenna** [comment]
But what I find confusing is that we already uploaded Farsi and changed the config.js
![Uploading C7E7AE67-4FBE-4F39-A97A-0F21C8C26954.png…]()

**Comment by Fabijenna** [comment]
![Uploading E71ED5F5-B3F3-4133-A5B1-4D4418F18899.png…]()

**Comment by amirkbrpr** [comment]
The navigation bar wasn't in Crowdin apparently. At least, I couldn't find its terms.

**Comment by Fabijenna** [comment]
Can you please check the config.js file, and if in the Persian block everything is ok?

Amy

**Comment by amirkbrpr** [comment]
I didn't translate them. They are all machine translation. Please assign these terms:
Getting started: شروع
Installation: نصب
Blog:وبلاگ
Changelog: گزارش تغییرات
Contact: تماس
Donate: کمک مالی
Languages: زبان

Also, in the sidebar:
Getting started: شروع
Installation: نصب
Editor:ویرایشگر
Scripting: اسکریپت نویسی
Contributing: مشارکت
FAQ: سؤالات متداول
Blog: وبلاگ

**Comment by Fabijenna** [comment]
Got it. Thanks for letting us know.
I’ll change it into what you wrote, many thanks

**Comment by Fabijenna** [comment]
amirkbrpr,

please, how do you translate
„Help us improve this page!“
and
„Persian“ 
correctly into Persian?
Thank you,
Amy

**Comment by amirkbrpr** [comment]
Hi,
„Help us improve this page! : در اصلاح این صفحه ما را یاری کنید!
„Persian : فارسی

**Comment by Fabijenna** [comment]
> Hi,
> „Help us improve this page! : در اصلاح این صفحه ما را یاری کنید!
> „Persian : فارسی
> 
> With Thanks!


amirkbrpr,
Is it okay, that I take my time figuring this out, because I haven't done these updates yet very often and still need to look up stuff to do it right!?

Thank you

**Comment by amirkbrpr** [comment]
Hi,
No problem. It is up to you to do that. Whenever you need the Persian translation, I'm at your service.
Thanks,

**Comment by Fabijenna** [comment]
> Hi,
> No problem. It is up to you to do that. Whenever you need the Persian translation, I'm at your service.
> Thanks,

Could you please provide us with the translation of

![Bildschirmfoto 2021-02-18 um 11 43 36](https://user-images.githubusercontent.com/17498644/108348732-738b7900-71e2-11eb-8de3-15a6aebbfe5e.png)

**Comment by amirkbrpr** [comment]
Ask question: پرسش و پاسخ
Ask for feature: درخواست نمایه
Report bug: گزارش اشکال
Telegram Channel: کانال تلگرام
Matrix/Element.io Room: Matrix/Element.io اتاق 
Gitter Chat: چت با گیتر
IRC Channel: IRC کانال
IRC log: IRC ورود با

**Comment by Fabijenna** [comment]
Working on completing the menu bar. 
Many thanks!

**Comment by pbek** [comment]
Like mentioned in https://github.com/pbek/QOwnNotes/issues/2057#issuecomment-781281525, there currently is a reason why it's not translated. 😅
