### ISSUE TITLE
TOC in generated html not working

### ISSUE THREAD

**Issue by stavpup** [pbek/QOwnNotes#2046]
First I will post the sample markdown text

https://pastebin.com/ksuQ2prk

Next I will post the generated output of that file in html from QON

https://pastebin.com/hFtUDznH

Finally I will post the generated output of that file in html from another app

https://pastebin.com/qwrFcRd3

In the first html, the inside link in not working because it is missing the reference to the file
file:///C:/QOwnNotes/%23chapter-1

While in the second file it is present

file:///C:/QOwnNotes/Lorem%20ipsum.html#chapter-1

**Comment by pbek** [comment]
Can you please explain in more detail and step by step what you did, what happened and what you expected.

Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting `Debug` in `Options`).

**Comment by stavpup** [comment]
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Πεμ Φεβ 11 00:15:50 2021`
**Version**: `21.1.8`
**Build date**: `Jan 26 2021`
**Build number**: `809`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\stavros\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `el_GR`
**Locale (interface)**: `en`
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `6`
**Calendar items**: `0`
**Enabled scripts**: `2`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `προεπιλεγμένο`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `C:\QOwnNotes\Qown-Joplin`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\QOwnNotes\Qown-Joplin\notes.sqlite`

## Cloud connections

### Cloud connection ``

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Enabled scripts

### Script `Image preview`

**id**: `2`
**path**: `C:\Users\stavros\AppData\Roaming\PBE\QOwnNotes\scripts\image-preview\image-preview.qml`
**variablesJson**: 
```
{
    "maxWidth": 640
}
```
**identifier**: `image-preview`
**version**: `1.0.1`
**minAppVersion**: `20.6.0`

### Script `Insert Table of Contents (TOC)`

**id**: `3`
**path**: `C:\Users\stavros\AppData\Roaming\PBE\QOwnNotes\scripts\insert-toc\insert-toc.qml`
**variablesJson**: 
```
{
    "tocLinks": true,
    "tocTitle": "Table of Contents"
}
```
**identifier**: `insert-toc`
**version**: `0.0.3`
**minAppVersion**: `17.06.2`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**EvernoteImport/AttachmentImportCheckBoxChecked** (QString): `true`
**EvernoteImport/ImageImportCheckBoxChecked** (QString): `true`
**EvernoteImport/MetaDataUnCheckedList** (QStringList): `, `
**EvernoteImportDialog/geometry** (QByteArray): `<binary data>`
**FileDialog/LastPath** (QString): `C:/QOwnNotes/Qown-Joplin`
**FileDialog/LastPath-ImportTextFiles** (QString): `C:/QOwnNotes/Joplin`
**FileDialog/LastPath-NoteHTMLExport** (QString): `C:/QOwnNotes/Qown-Joplin`
**FileDialog/LastPath-NotePDFExport** (QString): `C:/QOwnNotes/Qown-Joplin`
**FileDialog/LastPath-PreviewHTMLFileExport** (QString): `C:/Users/stavros/Downloads`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-02-11T00:15:14.776`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `30`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,11,-1,5,50,0,0,0,0,0,Normalny`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,9,-1,5,50,0,0,0,0,0,Normalny`
**MainWindow/noteTextView.code.font** (QString): `Courier New,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,7.8,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**NoteFolder-1/NoteTabNameList** (QStringList): `Note 2021-02-10T23.56.26`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteHistory-1** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `199`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExportOrientation** (int): `0`
**Printer/NotePDFExportPageSize** (int): `4`
**Printer/NotePrinting** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): `en`
**internalIconTheme** (QString): `false`
**itemHeight** (int): `18`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `C:/QOwnNotes/Qown-Joplin`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `0`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**recentNoteFolders** (QStringList): `C:/QOwnNotes/Joplin, C:/Users/stavros/Nextcloud/Notes`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2021-02-10T23.56.26, Note 2021-02-10T20.01.57, Note 2021-02-09T14.23.07, Note 2021-02-09T12.09.22, Note 2021-02-07T17.11.40, Note 2021-02-07T11.05.11, Note 2021-02-03T13.27.15, Note 2021-02-03T13.09.37, Note 2021-02-03T12.34.35, Note 2021-02-03T12.08.50, Note 2021-02-03T10.40.48, Note 2021-02-02T14.42.23, Note 2021-02-02T13.34.29, Note 2021-02-02T13.27.17, Note 2021-02-02T11.47.07, Note 2021-02-02T11.43.21, 0000c40ff8824580936c9faa82e78937, 2ba30dbe7b1543ca918aeba1bcbebb40, 2ba4ee291b1f48198c3c4fc378c9097b, 2b339abafea54b6690f975d8306800e1, 2b96bcb807524bdeaba0c712755afa35, 2ae3a42a3ebc46f3be70b52c16fd3120, 2acacbf0905849fa8a9cde286b438f20, 2abcd442b84f46f48e2c481f6ad7162b, 2abc13b27540453296d9eaf486852667, 2a923945c4364ee7a7b2ef6027ad7248, 2a502f9bbd8e49e9bcc80afc28a24d77, 2a169cc770074aceb8e2484a325fb168, 2a3af5b0533740bb9d30f744d8c07a18, 2a1bfa27af514f96b66f74041bcc1fdc, 02cede0c87a34eb88972145ed0a396d9, 1fc6110861544d7d8a78c2b6027b70aa, 1fabbd71f10e43e889f27d0bd40e2f54, 1f744a8d7fb746739a42c501c0ae46a8, 1f671bea570443f1ab5bb6e698d7aac5, 1f63e4bf74d14c779a2272df5564ccf1, 1f3e13bff02144c68d8000222bf868cd, 1f0cb5207bca4ea0ae2a80880c7fba26, 1eb404047968419e963fc925139d17ee, 1e45a6e6261542a0ba691d217b402987, 1dd0d90fb7a5412fb9a45f11a58e492d, 1dcb43d48b484f9cad87bd9079e28202, 1d847989cfae4bae8654503c1e5eec26, 1d50a021170844668b83f0ef1e18787f, 1d28d2beee7349be803f0fabdb8e62c7, 1d3eebf10c3449e0b41b921079563718, 1d00c880e2694e51be0c2318cf5ded71, 1ceba42a9bfb4c6c8cd5f199ed02ee6d, 1c28914f2ab84672bc6b35ed7041a2c2, 1c3133d6518b496cbb9ee7ae0fb296ae, 1c696c150c954fc98e13899ea42a1fe7, 1c18dfd89a854f61a258002d5c7825b8, 1c17d139e90d45e9940f2c0a3d220c96, 1c8f9f6cfba849f1ae62b5f03d3eb7c2, 1c4bcb76b5f44b188424a9ef9cd935aa, 1c0bfb26a7d349748319222d37455645, 1bfa8176cfcf4fbc9422f99e6b71d5fd, 1bc3f7c85f894de59d8ee5667587b466, 1b17107601784a3cb9ed54ead6fa68ad, 1b5077089e484fa1b17ae61a509de808, 1b45f5f8705a43518afcba2523304bac, 1b28e6453b3a47d88a05656367499cce, 1b8bb9c21ae5452b999e54bd024ade46, 1b4e9d8b3503497eaa3ca73500c39aa3, 1a7830531a5e4161969f07f23b29c99d, 1a5994b013224db4b7b86b82fdecb437, 1a1ebdabadcf4b1aa7e6c4da6bc662dd, 0fca0bc217914c428b737475e90215a5, 0fa65a54026f4f8d99e951711a293f17, 0f65dd2027a044149f69699e7101c58f, 0f9adc1052284dbd9c551ac5c36dee40, 0ee42ef376044f98a19c400caa536ee4, 0ec82135626a4dd6b3895b95280d1ec1, 0ec0c5188dfe4fae9d792d4b6ef9d57b, 0ea75548be2e4c9c950437e223e8d0de, 0e94844111534585be1e9258b782cf4b, 0e597033e78247098a065e531193b2b4, 0e08956b54d54ce3b4cab6ee259ed684, 0e4509acd64840c0a9ccb49988103202, 0e86d9a07b574e4ea64fba58c7f934eb, 0e61c5e6f391420bbfb793f19d93c3d9, 0e37f08cf73a4038b026c57a65ca8d74, 0e6b5b311b1e43878e4906bf070e105e, 0e3dce35cfaf43939b4741a33e862b94, 0de6db209c654e999928d72e23a9521a, 0dba0ff61fdc47aeacffab6caf27316f, 0da629e412fe4fa9b92f54ce907cc6dc, 0da5d3edfe16434bb077e772eb28a3ea, 0d9558c2052d4928b364aa3e18ed0246, 0d9042dcc51f4a75ae446b45d2aca2d6, 0d99d9f7f0be447084e27b3fdacb5279, 0d64dff49b3e4fc993d6c41355047ed9, 0d09bc4c99f14d13b59a7756a517d4ec, 0cf1b7b6add344a7a203be461e94a012, 0cc8f7882e284df3ad0b27d929ceeca8, 0cc2ee1fc2b34d599ed5812cecc8a74e, 0ca44aab568d4e94a019a11ca3f05e89, 0c95409761824656aa70b0b03d93c11d, 0c1393285dfb4277bbb1f76ad4e0d5ef, 0c3109a19a604f50b4cb146dd28f0d8f`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Ελάχιστη`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\stavros\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `LAPTOP-B58GPTAP`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\stavros`
**LOCALAPPDATA**: `C:\Users\stavros\AppData\Local`
**LOGONSERVER**: `\\LAPTOP-B58GPTAP`
**NUMBER_OF_PROCESSORS**: `12`
**OneDrive**: `C:\Users\stavros\OneDrive`
**OneDriveConsumer**: `C:\Users\stavros\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Pandoc\;C:\Users\stavros\AppData\Local\Microsoft\WindowsApps;C:\Users\stavros\AppData\Local\Programs\MiKTeX\miktex\bin\x64\`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 158 Stepping 10, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `9e0a`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\stavros\AppData\Local\Temp`
**TMP**: `C:\Users\stavros\AppData\Local\Temp`
**USERDOMAIN**: `LAPTOP-`
**USERDOMAIN_ROAMINGPROFILE**: `LAPTOP-`
**USERNAME**: ``
**USERPROFILE**: `C:\Users\`
**windir**: `C:\WINDOWS`
