### ISSUE TITLE
emulate typora in html export (enhancement)

### ISSUE THREAD

**Issue by stavpup** [pbek/QOwnNotes#2047]
If you do and export of any sample document you can see differences (orange links instead of blue) , very lange font and narrow text column. Just use any text, it is easy to produce.

**Comment by pbek** [comment]
Can you please explain in more detail what you are talking about?

**Comment by stavpup** [comment]
![2021-02-11_192007](https://user-images.githubusercontent.com/10577035/107673561-cc1cbc80-6c9e-11eb-91c6-e2d73ed20490.jpg)

**Comment by stavpup** [comment]
![Uploading 2021-02-11_192718.jpg…]()

**Comment by stavpup** [comment]
![2021-02-11_192718](https://user-images.githubusercontent.com/10577035/107674799-076bbb00-6ca0-11eb-95b9-811f7f76f568.jpg)

**Comment by stavpup** [comment]
Different formatting and in-documents links not working :-(
