### ISSUE TITLE
[F] Replacing the need for a script to toggle checkboxes

### ISSUE THREAD

**Issue by fabianski7** [pbek/QOwnNotes#2048]
#### Expected behaviour
Toggle checkboxes with the shortcut `CTRL+Space`

#### Actual behaviour
This shortcut does a lot of cool stuff automatically, but currently triggering him in this situation (toggle to-do checkboxes) does nothing. So I think he's free 😅

There is already a script to do this, but it is not possible to define a shortcut to it, which is the point of this feature request.

Btw, thanks @sanderboom for https://github.com/qownnotes/scripts/pull/57

**Comment by sanderboom** [comment]
> There is already a script to do this, but it is not possible to define a shortcut to it, which is the point of this feature request.

You can assign a shortcut to execute the script at Settings > Shortcuts > Custom actions. I use `ctrl+shift+x`.

![image](https://user-images.githubusercontent.com/5956570/107679453-df2e8d00-6c9c-11eb-96de-0e2e79cdb138.png)

**Comment by fabianski7** [comment]
> You can assign a shortcut to execute the script at Settings > Shortcuts > Custom actions. I use ctrl+shift+x.

Thanks for the info @sanderboom. I currently use Alt+X.

But I still think it would be more useful to have this in the CTRL+Space shortcut. As an AIO tool that makes your life much easier (as it already is)

**Comment by pbek** [comment]
Thank you for your suggestion. 😉

**Comment by sanderboom** [comment]
I'm all for it :+1: :wink:

**Comment by pbek** [comment]
The script does a lot of stuff that we cannot do with Ctrl + Space because that would trigger accidentally too often. Bit I think we can attempt toggling the checkbox where the cursor is at...

**Comment by pbek** [comment]
## 21.2.1
- you now can also toggle a checkbox at the cursor position with <kbd>Ctrl + Space</kbd>
  in the note text edit

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by fabianski7** [comment]
> There now is a new release, could you please test it and report if it works for you?

as always.

Thanks!

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by sanderboom** [comment]
Great addition, but I will keep my script installed for the [multiline functionality](https://github.com/pbek/QOwnNotes/issues/1167#issuecomment-474719124) :wink:

**Comment by pbek** [comment]
Yes, of course. That can't be handled by by one single shortcut. 😉

**Comment by sanderboom** [comment]
> Yes, of course. That shouldn't be handled by by one single shortcut. 

It's the same functionality only for multiple lines at once, just like you can indent one line or all selected lines. Using a single shortcut :wink:

**Comment by pbek** [comment]
And what logic decides which of the many things Ctrl+Space can do should be done?

**Comment by sanderboom** [comment]
Ah that is what you mean by 'a single shortcut'. Yeah, that means hassle - but nothing is impossible :stuck_out_tongue_winking_eye: I don't think it a good idea to overload Ctrl+Space, so don't bother, not for me at least :wink:

**Comment by pbek** [comment]
## 21.4.5
- now toggling of checkboxes at the cursor position with <kbd>Ctrl + Space</kbd>
  also supports lists with `* [ ]`, `+ [ ]` and numbered lists, like `1. [ ]` in
  the note text edit

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Kotof** [comment]
> There now is a new release, could you please test it and report if it works for you?

Great!
Everything seems to work as it should!

**Comment by pbek** [comment]
Great, thank you for testing!
