### ISSUE TITLE
Right align numbers in columns for note-count in submodule and tag panels

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#2052]
#### Expected behaviour
Numbers are right-aligned as is common in tablular displays.

#### Actual behaviour
Numbers are left-aligned.

As mentioned on Telegram, something along the lines of the following might be a solution:

```diff
diff --git a/src/mainwindow.cpp b/src/mainwindow.cpp
index 9209aba30..933cfa0c9 100644
--- a/src/mainwindow.cpp
+++ b/src/mainwindow.cpp
@@ -8372,6 +8372,7 @@ QTreeWidgetItem *MainWindow::addTagToTagTreeWidget(QTreeWidgetItem *parent,
     item->setData(0, Qt::UserRole, tagId);
     item->setText(0, name);
     item->setText(1, linkCount > 0 ? QString::number(linkCount) : QString());
+    item->setTextAlignment(1, Qt::AlignRight)
     item->setForeground(1, QColor(Qt::gray));
     item->setIcon(0, _tagIcon);
     item->setToolTip(0, toolTip);
@@ -10636,7 +10637,7 @@ void MainWindow::on_noteTreeWidget_itemChanged(QTreeWidgetItem *item,
```

I don't have a working setup to build and test atm.

**Comment by pbek** [comment]
> Numbers are right-aligned as is common in tablular displays.

Would that really be an improvement? You would even need more horizontal space to see the numbers. In addition I think that the last column is auto-stretching, so the numbers would stick to the far right all the time...

**Comment by sanderboom** [comment]
It would be an improvement, but like I initially asked "would it be an easy fix" meaning it wouldn't justify a complete overhaul of the app :stuck_out_tongue_winking_eye: 

I finally built it and saw what you are describing. I just to add a 3rd column as a spacer to keep the numbers closer while right aligned, but for some reason that is mysterious to me, adding `item->setText(2, QString());` is not enough.

**Comment by pbek** [comment]
> It would be an improvement

It would look better, but people may complain that you need to increase the width of the panel to see single digit search results when there are also multiple-digit results, wouldn't they?

**Comment by sanderboom** [comment]
Wouldn't they überhaupt want to increase the width to see all digits? If you think people really need the width of those couple of digits it might be a bad idea. To make sure that we are talking about the same thing: 

![image](https://user-images.githubusercontent.com/5956570/107887622-a0503f80-6f07-11eb-85a1-3020cf5cc0ae.png)

Right align would be nice, but it's not that important.

**Comment by pbek** [comment]
> Wouldn't they überhaupt want to increase the width to see all digits? If you think people really need the width of those couple of digits it might be a bad idea.

Lol, I just found out `überhaupt` means the same in Dutch and German. 😆 
The problem is that one long note name (or folder or tag, all views would need to be updated) can trigger that the number is pushed out to the far right...

If you want you can try to align all the numbers to the right and tell me how it went. 😁

**Comment by sanderboom** [comment]
> Lol, I just found out überhaupt means the same in Dutch and German. :laughing: 

I know, that's why I used it :stuck_out_tongue_winking_eye: 

> The problem is that one long note name (or folder or tag, all views would need to be updated) can trigger that the number is pushed out to the far right...

I see. I initially thought it behaved like columns in that a user could set the width by dragging, possibly showing long content ending in `...`. Almost everything is draggable/adjustable in the UI but I just tried and that's not possible indeed. 

> If you want you can try to align all the numbers to the right and tell me how it went. grin

Sure, can you tell me how to get a thing column in? See:

> but for some reason that is mysterious to me, adding item->setText(2, QString()); is not enough.

**Comment by pbek** [comment]
>  Almost everything is draggable/adjustable in the UI but I just tried and that's not possible indeed.

the column headings are disabled (to save space) and the columns are auto-resized (for convenience)

> but for some reason that is mysterious to me, adding item->setText(2, QString()); is not enough.

I guess you first need to add a 3rd column in the UI-file
