### ISSUE TITLE
[Feature request] Save editor width according to workspace and non-distraction mode

### ISSUE THREAD

**Issue by ElishaDaugherty** [pbek/QOwnNotes#2053]
First I would like to thank you for the software that you and the contributors have made, it is amazing how complete and functional this program is. Sometimes I can't believe this is all free 😂

I love writing about my day in the non-distraction mode, I feel it really helps me write better. But I organize my "journal" by months, so a single note accumulates my notes about every day, and this ends up generating very large files (I love to write! did I already say that? 🤭) and the navigation panel would be very useful to navigate between them.

Suggesting this for the distraction-free mode may be a bit contradictory, since it will add a distraction to it, but I think that if it is activated and deactivated through a keyboard shortcut, it won't hurt the focus, since the user will activate it only when it is necessary to check the file structure.

Alternatively, I tried to create a specific workspace, and it was partially possible to do this, but with one major drawback: the editor width is saved globally, not per workspace, so all the others were effected and had the text field width decreased (so the space utilization is compromised).

[Here is a screenshot of how it looks](https://i.imgur.com/C5zBAmJ.png)
[And here is another one](https://i.imgur.com/alIwEo1.png) of how the editor width looks "strange" when other panels are active.

Well, I am not a developer and I have just started to study python, but facing these facts, I think there are two possible solutions (ordered by simplicity):
1. Save the editor width by workspaces
With this, the option "Only use width setting in non-distraction mode" in Settings -> Interface -> Editor could be removed. And it would make room for a new section to set the editor width only for this mode.
The setting for editor width for workspaces would be done through the menu Window -> Editor Width, and would be saved individually. This makes more sense because I had already changed this preference several times and had not seen any change in the interface, only after I realized that it is by default only for the mode without distractions.

2. Allow displaying the navigation pane in distraction-free mode via a shortcut

I hope I was able to pass on the information needed to make this clear.

Thanks!

**Comment by ElishaDaugherty** [comment]
I have edited the title and added some details to the text. after thinking about it a lot, I really think that the first suggestion is the best.

**Comment by pbek** [comment]
Thank you for your kind words! 🌞 

>  it is amazing how complete and functional this program is.

A lot of people had a lot of wishes. 😅 

> Allow displaying the navigation pane in distraction-free mode via a shortcut

You can assign a shortcut for the panel in the *Shortcuts settings* and enable it in the DFM.

Would look like this then:

<img width="968" alt="image" src="https://user-images.githubusercontent.com/1798101/107879999-6a499600-6edc-11eb-9c60-1d99ecb4cb3c.png">

**Comment by pbek** [comment]
> I love to write! did I already say that?

now that you have mentioned it... 😆

**Comment by pbek** [comment]
> Here is a screenshot of how it looks

It seems like you are using ksnip for creating screenshot, are you? 😀  I love it! Have also contributed to it... 😁 
(btw. you can paste images directly from the clipboard on github like I did above)

**Comment by ElishaDaugherty** [comment]
> You can assign a shortcut for the panel in the Shortcuts settings and enable it in the DFM

Thank you, Bekerl.
This definitely works as expected.

> It seems like you are using ksnip for creating screenshot, are you? grinning I love it! Have also contributed to it... 
(btw. you can paste images directly from the clipboard on github like I did above)

Exactly. I am migrating to linux and I am getting to know the alternatives we have around here. Thanks for the tip.

So I guess in the end what remains of this reported issue is the possibility to save the editor width according to the workspace used.

I'm still looking for an ideal setting for me in QOwnNotes, currently I've moved all panels to the left and changed the editor width to Wide, so I have the text in the center of the screen while the folders and notes are a bit on the side. I have felt very comfortable with this organization. 
I love the possibility to adapt QOwnNotes to my preferences.

The downside is that now the editor in distraction-free mode has also had its width changed. So I'll leave this issue open.

Thanks for the help. I hope you have a great week!

**Comment by pbek** [comment]
> So I guess in the end what remains of this reported issue is the possibility to save the editor width according to the workspace used.

I don't think that will happen any time soon. Then a lot more settings would need to do that too (including a way to opt in and out).

> I'm still looking for an ideal setting for me in QOwnNotes, currently I've moved all panels to the left and changed the editor width to Wide, so I have the text in the center of the screen while the folders and notes are a bit on the side. I have felt very comfortable with this organization.
> I love the possibility to adapt QOwnNotes to my preferences.
> 
> The downside is that now the editor in distraction-free mode has also had its width changed. So I'll leave this issue open.

I think I can't follow you. Are you still in DFM? The editor width setting is for the DFM only by default. Can you please make a screenshot?

> Thanks for the help. I hope you have a great week!

A great week to you too!

**Comment by ElishaDaugherty** [comment]
> I think I can't follow you. Are you still in DFM? The editor width setting is for the DFM only by default. Can you please make a screenshot?

Exactly, I disabled this to add a margin around the editor. 

![spectacle_20210215_175201](https://user-images.githubusercontent.com/77898421/107991986-86ba0100-6fb6-11eb-8cbf-5c59c5fa3842.png)

without it, the text is too long

**Comment by pbek** [comment]
But the note editor in the DFM already has a margin left and right of the text. Why don't you stay in DFM and turn on the Navigation panel there?

**Comment by ElishaDaugherty** [comment]
I only use DFM to write in my personal journal, for the other notes, I need access to the toolbar and the list of folders and notes. If I disable the option to change the width of the editor only for DFM the text gets too wide, so I would have to switch between DFM and normal mode several times for simple things.

If you don't think this is worth it, I'll close this issue and won't bother you anymore. 🙃

**Comment by pbek** [comment]
So you want to set a different "editor-width" in both DFM and Non-DFM? 😁  Maybe you should set shortcuts for the different widths, so you can jump between them easily.

**Comment by pbek** [comment]
Or you can write a script with different custom actions (https://www.qownnotes.org/scripting/methods-and-objects.html#registering-a-custom-action) to set a certain workspaces (https://www.qownnotes.org/scripting/classes.html#properties-and-methods-4) and a certain editor width (https://www.qownnotes.org/scripting/methods-and-objects.html#triggering-a-menu-action).

You can set shortcuts for custom actions.
