### ISSUE TITLE
Change order of the Welcome screen

### ISSUE THREAD

**Issue by Mannshoch** [pbek/QOwnNotes#2054]
Show at first the sync possibility for Nextcloud with the setup for it.
After that may auto-detect the Note directory in the local Nextcloud cache.
If user do not wish to sync his notes with Nextcloud, propose the `Document/Notes` directory.

#### Expected behaviour
the way I described above
#### Actual behaviour
at first you get proposed a notes directory which may not correct if using Nextcloud with self defined sync-directorys and If you do not wish to use nextcloud sync the proposed directory `Nextcloud/Notes` is not a good place.
#### Steps to reproduce
Setup the welcomescreen

**Comment by pbek** [comment]
Thank you for your suggestion.
The thing is... NC isn't necessary for QON or will be enforced by QON. Half of the user don't use NC/oC. And QON itself doesn't sync notes!
Currently on the first screen a ownCloud folder is searched, then a special handling for portable mode, then a Nextcloud folder, then a special handling for SNAPs, plus a special handling for dev builds...

I could set `~/Notes` (the Documents folder can have a lot of different names on different systems and languages) as Notes path if no ownCloud or Nextcloud paths are found... (I think I had that for a while, I can't remember why it went out)

**Comment by Mannshoch** [comment]
I would suggest this a s first choose. If user choose nextcloud at first the shis settings have to be done:
__________
Choos your setup:
 - [x] Offline
 - [ ] Sync with Nextcloud
---------
I'use several accounts on my Nextcloud. May that's the cause why it's not able to detect the directory correctly. 
On my computer Nextcloud set up the directory in `~/.config/Nextcloud/nextcloud.cfg` may you could check it there and have give a dropdown-list of proposed directories.
As far I know the Document DIR could be found in `~/.config/user-dirs.dirs`

For the record, It's the first time I set up QOwnNotes for Nextcloud. Normally I use it also local. I was also thinking about, if I use the Nextcloud app to sync files, do I need the QOwnNotesAPI app in Nextcloud or could I have my own note directory If I use the QOwnNotesAPI app. I was in the middle of a test set up on a VM machine as I where confused about how I should have to set up in QOwnNotes. I'm carefully in doing things on my data and at moment I'm not able to set up a test account on Nextcloud.

**Comment by pbek** [comment]
Currently how the things are connected is documented on https://www.qownnotes.org/getting-started/concept.html.
NC is very optional. You can sync with whatever tool you like.
"Offline" and "Sync with Nextcloud" is far too little choice (and very misleading) and in my opinion isn't important to decide in the welcome screen.

If you think https://www.qownnotes.org/getting-started/concept.html isn't clear enough you could suggest changes.
And if you want to can suggest a tutorial for multiple scenarios to make things easier for people.

**Comment by pbek** [comment]
## 21.2.2
- when setting your initial note folder and no Nextcloud or ownCloud folders are found
  now a `Notes` folder is suggested in your home directory

There now is a new release, could you please test it and report if it works for you?
