### ISSUE TITLE
Flatpack version fails to be confined in a custom directory

### ISSUE THREAD

**Issue by nidamanx** [pbek/QOwnNotes#2055]
Flatpack version fails to be confined in a custom directory

#### Expected behaviour
App confined in a chosen directory

#### Actual behaviour
App can read all the OS

#### Steps to reproduce
```
flatpak install flathub org.qownnotes.QOwnNotes
flatpak run org.qownnotes.QOwnNotes --filesystem=~/Note
```

**Comment by pbek** [comment]
I'm sorry, the flatpack version is community maintained. You could open an issue at https://github.com/flathub/org.qownnotes.QOwnNotes or try to ask @stobbsm.

**Comment by nidamanx** [comment]
Thanks. Which one are the official ways to install QOwnNotes?
In website in not clear the official and the community
Thanks

**Comment by pbek** [comment]
https://www.qownnotes.org/installation/flatpak.html says it's done by a 3rd party.

All other ways where it doesn't say it's done by a 3rd party are "official". 😁

**Comment by nidamanx** [comment]
> https://www.qownnotes.org/installation/flatpak.html says it's done by a 3rd party.
> 
> All other ways where it doesn't say it's done by a 3rd party are "official". grin

Ops, I'm very sorry. I missed it. Thanks again

**Comment by pbek** [comment]
No problem, there a plenty of ways to install QON. 😉
