### ISSUE TITLE
No translations under "Contact" in the menu bar (all in English)

### ISSUE THREAD

**Issue by Fabijenna** [pbek/QOwnNotes#2057]
#### Expected behaviour

In the menu bar all entries and pull down menues are translated into the proper languages.

#### Actual behaviour

The pull down menu in "Contact" is in English in all languages (terms aren't listed on Crowdin)

#### Steps to reproduce

* open "http://qownnotes.org"
* go to Contact in the menu bar
* find the entries under "Contact" in all languages in English instead of the proper language

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Thank you for mentioning.
I left those in English on purpose because all those communication channels should only be used in English. 😅  So there is not much use in translating the menu entries. Do you have another opinion?

**Comment by Fabijenna** [comment]
Wow, sorry, I missed this info, thanks a lot for updating me.

**Comment by Fabijenna** [comment]
No sense translating that indeed.
I’ll close in the meantime.
