### ISSUE TITLE
Question for statistics in LTR languages is cut from the first part of the question

### ISSUE THREAD

**Issue by Fabijenna** [pbek/QOwnNotes#2058]
#### Expected behaviour

The question field "How did you find out about QOwnNotes" should be readable at least regarding the beginning of the question and invite users to answer the question.

#### Actual behaviour

In the LTR (left to right) languages the question "how did you find out about QOwnNotes" is on the left side is in English, but on these pages not the end but the "How is ..." is cut off and and looks a bit off in the otherwise harmonious front page

#### Steps to reproduce

open "https://www.qownnotes.org/fa/"

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Thank you for your suggestion. 😁

**Comment by pbek** [comment]
Fixed now on https://www.qownnotes.org/fa/, thank you.
