### ISSUE TITLE
Inserting headline from note break multiple dot filename

### ISSUE THREAD

**Issue by piyo-gh** [pbek/QOwnNotes#206]
v16.06.3 build1739
Windows 10 x64

1. Add a new note. (filename is **Note 2016-06-12T10.08.18.txt**)
1. Select `Insert headline from note filename`. (filename changed to **Note 2016-06-12T10.txt**)

**Comment by pbek** [comment]
Thank you for reporting. I will take a look at that.

**Comment by pbek** [comment]
should be fixed in 16.06.4

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the fix works for you?
