### ISSUE TITLE
Global Show/Hide Shortcut hides, but can't show in Windows

### ISSUE THREAD

**Issue by josephrooks** [pbek/QOwnNotes#2061]
#### Expected behaviour

Global show/hide hotkey alternates between showing and hiding the window.

#### Actual behaviour

Global show/hide hotkey hides the window. After that, attempts to show it again quickly show the dock icon and application, but it gets minimized again immediately after.

#### Steps to reproduce

Set a global show/hide application hotkey, and try to use it to hide and then show the application again in Windows 10.

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mon Feb 22 14:29:37 2021`
**Version**: `21.2.3`
**Build date**: `Feb 19 2021`
**Build number**: `813`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2004`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\Joseph Rooks\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Program Files\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1280x1024, 1680x1050`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `375`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\Joseph Rooks\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `C:\Users\Joseph Rooks\Dropbox\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\Joseph Rooks\Dropbox\Notes\notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/editorWidthMode** (int): `2`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (int): `20`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**GlobalShortcuts/MainWindow-actionShow_Hide_application** (QString): `Ctrl+Space`
**GlobalShortcuts/MainWindow-togglePanel-noteSearchDockWidget** (QString): `Ctrl+Space`
**LastUpdateCheck** (QDateTime): `2021-02-22T14:11:10.546`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MessageBoxOverride/layoutwidget-use-layout** (int): `16384`
**MessageBoxOverride/readonly-mode-allow** (int): `16384`
**MessageBoxOverride/remove-notes** (int): `16384`
**MessageBoxOverride/update-and-restart** (int): `16384`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): `refx psp games`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteFolder-1/allowDifferentNoteFileName** (QString): `true`
**NoteHistory-1** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `199`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-actionActivate_context_menu** (QString): *empty*
**Shortcuts/MainWindow-actionAllow_note_editing** (QString): *empty*
**Shortcuts/MainWindow-actionAutocomplete** (QString): *empty*
**Shortcuts/MainWindow-actionCheck_for_updates** (QString): *empty*
**Shortcuts/MainWindow-actionClose_current_note_tab** (QString): *empty*
**Shortcuts/MainWindow-actionCopy_headline** (QString): *empty*
**Shortcuts/MainWindow-actionDelete_line** (QString): *empty*
**Shortcuts/MainWindow-actionDelete_word** (QString): *empty*
**Shortcuts/MainWindow-actionEdit_encrypted_note** (QString): *empty*
**Shortcuts/MainWindow-actionFind_action** (QString): *empty*
**Shortcuts/MainWindow-actionFind_notes_in_all_subfolders** (QString): *empty*
**Shortcuts/MainWindow-actionFormat_text_bold** (QString): *empty*
**Shortcuts/MainWindow-actionFormat_text_italic** (QString): *empty*
**Shortcuts/MainWindow-actionInsert_Link_to_note** (QString): *empty*
**Shortcuts/MainWindow-actionInsert_attachment** (QString): *empty*
**Shortcuts/MainWindow-actionInsert_block_quote** (QString): *empty*
**Shortcuts/MainWindow-actionInsert_code_block** (QString): *empty*
**Shortcuts/MainWindow-actionInsert_current_time** (QString): *empty*
**Shortcuts/MainWindow-actionInsert_headline_from_note_filename** (QString): *empty*
**Shortcuts/MainWindow-actionInsert_image** (QString): *empty*
**Shortcuts/MainWindow-actionInsert_table** (QString): *empty*
**Shortcuts/MainWindow-actionJump_to_note_list_panel** (QString): *empty*
**Shortcuts/MainWindow-actionJump_to_note_subfolder_panel** (QString): *empty*
**Shortcuts/MainWindow-actionJump_to_note_text_edit** (QString): *empty*
**Shortcuts/MainWindow-actionJump_to_tags_panel** (QString): *empty*
**Shortcuts/MainWindow-actionNew_note_in_new_tab** (QString): *empty*
**Shortcuts/MainWindow-actionNext_note** (QString): *empty*
**Shortcuts/MainWindow-actionNext_note_tab** (QString): *empty*
**Shortcuts/MainWindow-actionOpen_List** (QString): *empty*
**Shortcuts/MainWindow-actionPaste_image** (QString): *empty*
**Shortcuts/MainWindow-actionPrevious_Note** (QString): *empty*
**Shortcuts/MainWindow-actionPrevious_note_tab** (QString): *empty*
**Shortcuts/MainWindow-actionReload_scripting_engine** (QString): *empty*
**Shortcuts/MainWindow-actionReplace_in_current_note** (QString): *empty*
**Shortcuts/MainWindow-actionSave_modified_notes** (QString): *empty*
**Shortcuts/MainWindow-actionScript_repository** (QString): *empty*
**Shortcuts/MainWindow-actionSearch_text_on_the_web** (QString): *empty*
**Shortcuts/MainWindow-actionSelect_note_folder** (QString): *empty*
**Shortcuts/MainWindow-actionShare_note** (QString): *empty*
**Shortcuts/MainWindow-actionShow_note_in_file_manager** (QString): *empty*
**Shortcuts/MainWindow-actionSplit_note_at_cursor_position** (QString): *empty*
**Shortcuts/MainWindow-actionStrike_out_text** (QString): *empty*
**Shortcuts/MainWindow-actionSwitch_to_previous_workspace** (QString): *empty*
**Shortcuts/MainWindow-actionToggle_distraction_free_mode** (QString): *empty*
**Shortcuts/MainWindow-actionToggle_fullscreen** (QString): *empty*
**Shortcuts/MainWindow-actionToggle_text_case** (QString): *empty*
**Shortcuts/MainWindow-actionView_note_in_new_window** (QString): *empty*
**Shortcuts/MainWindow-action_Back_in_note_history** (QString): *empty*
**Shortcuts/MainWindow-action_Decrease_note_text_size** (QString): *empty*
**Shortcuts/MainWindow-action_DuplicateText** (QString): *empty*
**Shortcuts/MainWindow-action_Find_note** (QString): *empty*
**Shortcuts/MainWindow-action_Forward_in_note_history** (QString): *empty*
**Shortcuts/MainWindow-action_Increase_note_text_size** (QString): *empty*
**Shortcuts/MainWindow-action_New_note** (QString): *empty*
**Shortcuts/MainWindow-action_Open_note_in_external_editor** (QString): *empty*
**Shortcuts/MainWindow-action_Print_note_markdown** (QString): *empty*
**Shortcuts/MainWindow-action_Print_note_text** (QString): *empty*
**Shortcuts/MainWindow-action_Quit** (QString): *empty*
**Shortcuts/MainWindow-action_Reload_note_folder** (QString): *empty*
**Shortcuts/MainWindow-action_Remove_note** (QString): *empty*
**Shortcuts/MainWindow-action_Reset_note_text_size** (QString): *empty*
**Shortcuts/MainWindow-action_new_tag** (QString): *empty*
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `true`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `txt`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `12`
**interfaceLanguage** (QString): *empty*
**interfaceStyle** (QString): `windowsvista`
**internalIconTheme** (QString): `false`
**itemHeight** (int): `16`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `false`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `false`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `0`
**notesPath** (QString): `C:/Users/Joseph Rooks/Dropbox/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `true`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `wm5NcqeEkXsR`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `refx voicemeeter, ideax interview dot ai, refx vegan ingredients, kimsufi, audio notes, toz peppers, ssl certificate letsencrypt, refx uhc commands, refx delete ds_store files, refx minecraft seeds, certbot, 8bit Nether, My first strider, server properties, potions, refx endermite summon, refx stream notes, refx chunky, refx comics to read, 8bit, refx elite dangerous, slack fuzzymath auth codes, policeviolence, refx story matrix review, rss feeds, refx thehotdish quotes, Note 2020-05-03T12.21.37`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `false`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\Joseph Rooks\AppData\Roaming`
**asl.log**: `Destination=file`
**CAMLIBS**: `C:\Program Files\darktable\lib\libgphoto2\2.5.23`
**ChocolateyInstall**: `C:\ProgramData\chocolatey`
**ChocolateyLastPathUpdate**: `132338223130790910`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `DESKTOP`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FONTCONFIG_FILE**: `C:\Windows\fonts.conf`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\Joseph Rooks`
**IOLIBS**: `C:\Program Files\darktable\lib\libgphoto2_port\0.12.0`
**JAVA_HOME**: `C:\Program Files\Java\jdk-11.0.4`
**JD2_HOME**: `C:\Users\Joseph Rooks\AppData\Local\JDownloader 2.0`
**LOCALAPPDATA**: `C:\Users\Joseph Rooks\AppData\Local`
**LOGONSERVER**: `\\DESKTOP`
**MAGICK_HOME**: `C:\Program Files\darktable\lib\GraphicsMagick-1.3.35\modules-Q8\coders`
**MOZ_PLUGIN_PATH**: `C:\Program Files (x86)\Foxit Software\Foxit Reader\plugins\`
**NUMBER_OF_PROCESSORS**: `8`
**OneDrive**: `C:\Users\Joseph Rooks\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\VMware\VMware Player\bin\;C:\Python38\Scripts\;C:\Python38\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Java\jdk-11.0.4\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files (x86)\Touch Portal\plugins\adb\platform-tools;C:\Users\Joseph Rooks\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\Joseph Rooks\AppData\Local\Programs\Python\Python37-32\;C:\Users\Joseph Rooks\AppData\Local\Microsoft\WindowsApps;C:\Python27;C:\Python27\Scripts;C:\Users\Joseph Rooks\AppData\Local\GitHubDesktop\bin;C:\Users\Joseph Rooks\AppData\Roaming\npm;C:\Users\Joseph Rooks\AppData\Local\Microsoft\WindowsApps`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `AMD64 Family 23 Model 17 Stepping 0, AuthenticAMD`
**PROCESSOR_LEVEL**: `23`
**PROCESSOR_REVISION**: `1100`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**PYTHONHOME**: `C:\Python27`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\JOSEPH~1\AppData\Local\Temp`
**TMP**: `C:\Users\JOSEPH~1\AppData\Local\Temp`
**USERDOMAIN**: `DESKTOP`
**USERDOMAIN_ROAMINGPROFILE**: `DESKTOP`
**USERNAME**: `Joseph Rooks`
**USERPROFILE**: `C:\Users\Joseph Rooks`
**windir**: `C:\WINDOWS`
**__COMPAT_LAYER**: `RunAsAdmin DetectorsAppHealth Installer`

**Comment by pbek** [comment]
Thank you for reporting.
Does it behave it same when you turn off the tray icon in QOwnNotes?

**Comment by pbek** [comment]
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting `Debug` in `Options`).

**Comment by josephrooks** [comment]
It acts the same with the Tray Icon disabled.

This is all I see in the log file:

```
[Feb 23 22:00:30] [debug]: Global shortcut action triggered:  "actionShow_Hide_application"
[Feb 23 22:00:30] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Feb 23 22:00:30] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Feb 23 22:00:30] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Feb 23 22:00:31] [debug]: Global shortcut action triggered:  "actionShow_Hide_application"
[Feb 23 22:00:31] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Feb 23 22:00:31] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Feb 23 22:00:31] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Feb 23 22:00:31] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Feb 23 22:00:31] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Feb 23 22:00:31] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Feb 23 22:00:32] [debug]: Global shortcut action triggered:  "actionShow_Hide_application"
[Feb 23 22:00:32] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Feb 23 22:00:32] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Feb 23 22:00:32] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Feb 23 22:00:32] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Feb 23 22:00:32] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Feb 23 22:00:32] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Feb 23 22:00:37] [warning]: "A second instance of QOwnNotes was attempted to be started!"
[Feb 23 22:00:37] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Feb 23 22:00:37] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Feb 23 22:00:37] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Feb 23 22:00:38] [status]: No script updates were found
[Feb 23 22:00:41] [warning]:   OpenType support missing for "MS Shell Dlg 2", script 12
[Feb 23 22:00:41] [warning]:   OpenType support missing for "Arial", script 12
[Feb 23 22:00:41] [warning]:   OpenType support missing for "MS UI Gothic", script 12
[Feb 23 22:00:41] [warning]:   OpenType support missing for "SimSun", script 12
[Feb 23 22:00:41] [warning]:   OpenType support missing for "MS Shell Dlg 2", script 11
[Feb 23 22:00:41] [warning]:   OpenType support missing for "Arial", script 11
[Feb 23 22:00:41] [warning]:   OpenType support missing for "MS UI Gothic", script 11
[Feb 23 22:00:41] [warning]:   OpenType support missing for "SimSun", script 11
[Feb 23 22:00:41] [warning]:   OpenType support missing for "MS Shell Dlg 2", script 32
[Feb 23 22:00:41] [warning]:   OpenType support missing for "Arial", script 32
[Feb 23 22:00:41] [warning]:   OpenType support missing for "MS UI Gothic", script 32
[Feb 23 22:00:41] [warning]:   OpenType support missing for "SimSun", script 32
[Feb 23 22:00:41] [warning]:   OpenType support missing for "MS Shell Dlg 2", script 13
[Feb 23 22:00:41] [warning]:   OpenType support missing for "Arial", script 13
[Feb 23 22:00:41] [warning]:   OpenType support missing for "MS UI Gothic", script 13
[Feb 23 22:00:41] [warning]:   OpenType support missing for "SimSun", script 13
[Feb 23 22:00:41] [warning]:   OpenType support missing for "MS Shell Dlg 2", script 20
[Feb 23 22:00:41] [warning]:   OpenType support missing for "Arial", script 20
[Feb 23 22:00:41] [warning]:   OpenType support missing for "MS UI Gothic", script 20
[Feb 23 22:00:41] [warning]:   OpenType support missing for "SimSun", script 20
[Feb 23 22:00:42] [warning]:   OpenType support missing for "Segoe UI", script 20
[Feb 23 22:00:42] [warning]:   OpenType support missing for "MS Shell Dlg 2", script 20
[Feb 23 22:00:42] [warning]:   OpenType support missing for "Arial", script 20
[Feb 23 22:00:42] [warning]:   OpenType support missing for "MS UI Gothic", script 20
[Feb 23 22:00:42] [warning]:   OpenType support missing for "SimSun", script 20
```

**Comment by pbek** [comment]
It's really strange. It doesn't even work in the original QOwnNotes version 20.4.0, where this feature got introduced. There must have been changes in Windows or Qt... Linux isn't affected.

**Comment by josephrooks** [comment]
For what it's worth to anyone else having this problem, my temporary workaround is to map ctrl+space to the "Find note" feature to make that show the window, then just x out of it when I'm done (with close to tray enabled of course).

**Comment by pbek** [comment]
This took a while...

## 21.2.4
- fixed an issue with showing the application window with a global shortcut for the
  `Show/Hide application` action (for [#2061](https://github.com/pbek/QOwnNotes/issues/2061))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by josephrooks** [comment]
Looks like it works really well! Thanks.

I will note one additional little detail about the default behavior that I wish could be customized -- I'd really prefer it if the note search field was always active on showing the window, because when I do open it it's usually to search for a particular note right away.

If I should put that somewhere else though, let me know -- the issue documented here seems to be fully fixed now, many thanks :)

**Comment by pbek** [comment]
Others might just want to edit the current note. Currently the focus stays where it was before hiding the window.
Maybe it's best if you just use the `Find note` shortcut to get to the search panel.
