### ISSUE TITLE
[I] PDF export generates a blank page

### ISSUE THREAD

**Issue by helenelax** [pbek/QOwnNotes#2062]
#### Expected behaviour

When I export a note in PDF, text or preview, I get a PDF document. Same for printing in a file

#### Actual behaviour

The generated PDF is a blank page

#### Steps to reproduce

QOwnNotes - version 21.2.3 - Launchpad PPA - build 813
Ubuntu 20.04.2

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[10:50:58] [warning] QPageSetupDialog: Cannot be used on non-native printers
[10:50:58] [warning] /usr/share/icons/Faba/16x16/actions/dialog-ok.svg:112: Could not resolve property: #linearGradient4205
[10:51:00] [warning] /usr/share/icons/Faba/16x16/actions/dialog-ok.svg:112: Could not resolve property: #linearGradient4205
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `jeu. févr. 25 10:51:59 2021`
**Version**: `21.2.3`
**Build date**: `Feb 19 2021`
**Build number**: `813`
**Platform**: `linux`
**Operating System**: `Ubuntu 20.04.2 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.12.8`
**Qt Version (runtime)**: `5.12.8`
**Portable mode**: `no`
**Settings path / key**: `/home/laxenair/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/laxenair/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `fr_FR`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1366x768`
**Icon theme**: `Moka`
**Notes in current note folder**: `642`
**Calendar items**: `0`
**Enabled scripts**: `5`

## Server Info

**serverUrl**: `https://acloud.zaclys.com`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `19.0.3.1`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_US, fr, fr_BE, fr_CA, fr_CH, fr_FR, fr_LU, fr_MC`
**Language names**: `American English (United States), français, français (Belgique), français canadien (Canada), français suisse (Suisse), français (France), français (Luxembourg), français (Monaco)`
**Application dictionaries path**: `/home/laxenair/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `3`

### Note folder `par défaut`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `125`
**localPath**: `/home/laxenair/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/laxenair/Nextcloud/Notes/notes.sqlite`

### Note folder `par défaut`

**id**: `2`
**isCurrent**: `no`
**activeTagId**: `-1`
**localPath**: `/home/laxenair/Nextcloud_a/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/laxenair/Nextcloud_a/Notes/notes.sqlite`

### Note folder `par défaut`

**id**: `3`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/laxenair/Nextcloud_a/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/laxenair/Nextcloud_a/Notes/notes.sqlite`

### Cloud connection `Zaclys`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://acloud.zaclys.com`
**username**: `18367`

### Script `Custom user interface styling`

**id**: `1`
**path**: `/home/laxenair/.local/share/PBE/QOwnNotes/scripts/custom-stylesheet/custom-stylesheet.qml`
**variablesJson**: 
```
{
    "customStylesheet": "QTreeWidget#noteTreeWidget {font-family: Roboto; font-size: 14px;}"
}
```
**identifier**: `custom-stylesheet`
**version**: `0.0.1`
**minAppVersion**: `17.05.7`

### Script `Insert Table of Contents (TOC)`

**id**: `2`
**path**: `/home/laxenair/.local/share/PBE/QOwnNotes/scripts/insert-toc/insert-toc.qml`
**variablesJson**: *empty*
**identifier**: `insert-toc`
**version**: `0.0.3`
**minAppVersion**: `17.06.2`

### Script `Checkbox preview and export`

**id**: `3`
**path**: `/home/laxenair/.local/share/PBE/QOwnNotes/scripts/export-checkboxes/export-checkboxes.qml`
**variablesJson**: *empty*
**identifier**: `export-checkboxes`
**version**: `0.0.4`
**minAppVersion**: `20.6.0`

### Script `Custom note preview styling`

**id**: `4`
**path**: `/home/laxenair/.local/share/PBE/QOwnNotes/scripts/preview-styling/preview-styling.qml`
**variablesJson**: 
```
{
    "customStylesheet": "body {\n    margin: 0 auto;\n    background-color:white;\n    font-family:serif;\t\n    color: #333333; \n    max-width: 800px;\n    padding: 30px;\n    font-size: 18px;\n}\n\n\np   {\n    font-size: 14px;\n    line-height: 120%;\n    max-width: 960px;\n    font-weight: 400;\n    color: #333333;\n}\n\nh1, h2, h3, h4, h5, h6 {\n    color: #111111;\n    font-weight:bold;\n    margin-bottom:25px;\n    background-color:white;\n    border-bottom: 1px solid #CCCCCC;\n}\n\nh2, h3, h4, h5, h6 p {\n    margin-bottom: 10px;\n    margin-top: 15px;\n    padding: 0;\n}\n\nh1 {\n    margin-bottom: 10px;\n    font-size:28px;\n    padding: 0;\n    font-variant:small-caps;\n}\n\nh2 {\n    font-size:24px;\n    margin: 24px 0 6px; \n    border-bottom: 1px solid #CCCCCC;\n}\n\nh3 {\n    font-size:22px;\n}\n\nh4 {\n    font-size:20px;\n    font-variant:small-caps;\n}\n\nh5 {\n    font-size:18px;\n}\n\nh6 {\n    font-size:18px;\n    font-style:italic;\n    font-color:#3366ff;\n}\n\na {\n    color: orange;\n    margin: 0;\n    padding: 0;\n    vertical-align: baseline;\n}\n\na:hover {\n    text-decoration: blink;\n    color: green;\n}\n\na:visited {\n    color: purple;\n}\n\nul, ol {\n    padding: 0;\n    margin: 0px 0px 0px 10px;\n}\n\nul {\n    list-style-type: square;\n    list-style-position: inside;\n}\n\nli {\n     line-height:120%;    \n}\n\nli ul, li ul {\n    margin-left: 24px;\n}\n\npre {\n    padding: 0px 24px;\n    max-width: 800px;\n    white-space: pre-wrap;\n}\n\ncode {\n    font-family: Consolas, Monaco, Andale Mono, monospace;\n    line-height: 1.5;\n    font-size: 13px;\n}\n\naside {\n    display: block;\n    float: right;\n    width: 390px;\n}\n\nblockquote {\n    border-left:.5em solid #eee;\n    padding: 0 1em;\n    margin-left:0;\n    max-width: 476px;\n    font-style:italic;\n    \n}\n\nblockquote  cite {\n    font-size:14px;\n    line-height:20px;\n    color:#bfbfbf;\n   margin-left:20px;\n}\n\nblockquote cite:before {\n    content: '\\2014 \\00A0';\n}\n\nblockquote p {  \n    color: #666;\n    max-width: 460px;\n}\n\nhr {\n    width: 540px;\n    text-align: left;\n    margin: 0 auto 0 0;\n    color: #999;\n}"
}
```
**identifier**: `preview-styling`
**version**: `0.0.5`
**minAppVersion**: `20.6.0`

### Script `Indent/unindent line`

**id**: `5`
**path**: `/home/laxenair/.local/share/PBE/QOwnNotes/scripts/indent-line/indent-line.qml`
**variablesJson**: 
```
{
    "indent_spaces_number": 4
}
```
**identifier**: `indent-line`
**version**: `1.0.0`
**minAppVersion**: `19.03.2`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**AttachmentDialog/geometry** (QByteArray): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `22`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `/home/laxenair/Bureau`
**FileDialog/LastPath-InsertAttachment** (QString): `/home/laxenair/Bureau`
**FileDialog/LastPath-InsertImage** (QString): `/home/laxenair/Bureau`
**FileDialog/LastPath-NotePDFExport** (QString): `/home/laxenair/Bureau`
**ImageDialog/disableCopying** (QString): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-02-25T10:28:32.592`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Roboto,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**NoteFolder-1/NoteTabNameList** (QString): `Rentrée 2020 - Covid`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteFolder-2/NoteTabNameList** (QString): `Mini-formation - BigBlueButton`
**NoteFolder-2/NoteTabStickinessList**: *empty*
**NoteFolder-2/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteFolder-3/NoteTabNameList** (QString): `UE8 GENA - Biblio 2019-2020`
**NoteFolder-3/NoteTabStickinessList**: *empty*
**NoteFolder-3/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteHistory-1** (QVariantList): `<variant list with 30 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 139 item(s)>`
**NoteHistory-3** (QVariantList): `<variant list with 116 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `29`
**NoteHistoryCurrentIndex-2** (QString): `138`
**NoteHistoryCurrentIndex-3** (QString): `115`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExport** (QByteArray): `<binary data>`
**Printer/NotePrinting** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `3`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `17`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/laxenair/Nextcloud_a/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Erreur inconnue`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `19.0.3.1`
**recentNoteFolders**: *empty*
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `J'ai une bibliographie dans Word, est-ce que je peux l'importer dans Zotero Carrefour gestion bibliographique, societe de surveillance Premier Parallele, Rentrée 2020 - Covid, Formation Ticea, Fake news - des ressources dans Zotero, Note 2020-05-20T10.04.10, L'écosophie ou la sagesse de la nature (suivi de La belle vie) 2020-05-20T09.06.44, L'écosophie ou la sagesse de la nature (suivi de La belle vie) 2020-05-20T09.03.37, L'écosophie ou la sagesse de la nature (suivi de La belle vie), Les traces - diaporama présentation 1 heure, Utilisation Gitpitch desktop avec Docker, Note 2020-05-14T12.06.43`
**savedSearches/noteFolder-2** (QStringList): `Mini-formation - BigBlueButton, Mini-formation - Trucs et astuces sur l'ordi, Evaluation à 5 doigts, Projets : unnjour, NumEA Newsletter - Comment rentrer les URL des stages formco ?, Mini-forma, miniforma, cdi, SupAgro - Payer un intervenant, Note 2020-09-24T10.19.03, Diigo - Envoir par mail, zoom, Bonnes pratiques numérique pour l'environnement - Dossier ADEME Mag 2020, UE6 - Veille sur AAP - Pour 2020, Image Moteur de recherche Firefox, Bonnes pratiques numérique pour l'environnement - Article Linux Pratique 2020, Note 2020-09-18T14.54.41, Formations hybrides - Infographie, Certificat d'Authentification Agent - Installation VPN, Différentes manière d'hybrider une formation, Différentes manière d'hybrider un formation, FabLab édu, CDI - Mesures sanitaires au 1er septembre 2020, Note 2020-08-28T10.31.27, Marie Duflot Kremer - Loria - Algorithe débranché, DNA 2021 - Projets proposés, UE3 - Pense-bête 2021, UE3, QOwnNotes - Feuilles de style, Note 2020-08-21T11.10.11, Réseau pratiques sportives - Vandalisme wiki aout 2020, RMT climat, Etats généraux du numérique éducatif 2020, Imprimante CDI, PIX - Accompagnement du déploiement de PIX, Projets 2020-2021, EPA 2021 - Valorissation Openbadge, Réseau pratiques sportives - Tuto OpenBadge - élève - court, Réseau pratiques sportives - Tuto OpenBadge - éléve, Réseau pratiques sportives - Séminaire 2020 - Atelier réseaux sociaux, Réseau pratiques sportives - Séminaire 2020, AAP Muse - Take off 2020 - Résultats, Réseau pratiques sportives - Forum, commande`
**savedSearches/noteFolder-3** (QStringList): `Stage RS - 2021 - texte de pub, Note 2021-01-18T15.42.21, Bilan Acoustice 2020, OpenBadge - Journée scientifique 2021, NimEA - SIL directeurs, rentr, NumEA - GT droit d'auteur, Stage Outils du web - Notes pour 2021, Note 2020-12-03T11.53.40, UE3 - Pense-bête 2021, CDI - Paiement au comptant par Angélique, Journées de l'innovation 20, Projet Procédures du CDI, Note 2020-10-27T16.06.24, StageRS MSA 2021, Adresses Educagri et agriculture.gouv et GLA, Journée Intelligence collective et outils numérique - Mende 12 npvembre 2020, DNA 2021 - EPA 2 Carte interative, Note 2020-10-09T12.42.19`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `barre d'outils principale`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `barre d'outils de formatage`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `barre d'outils d'insertion`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `barre d'outils de chiffrement`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `barre d'outils de fenêtre`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quitter la barre d’outils`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**webSocketServerService/token** (QString): `Fhdd9DrZ`
**workspace-initial/name** (QString): `Complet`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`
**USER**: `laxenair`
**SSH_AGENT_PID**: `1635`
**XDG_SESSION_TYPE**: `x11`
**SHLVL**: `0`
**HOME**: `/home/laxenair`
**DESKTOP_SESSION**: `ubuntu`
**GIO_LAUNCHED_DESKTOP_FILE**: `/usr/share/applications/PBE.QOwnNotes.desktop`
**GTK_MODULES**: `gail:atk-bridge`
**GNOME_SHELL_SESSION_MODE**: `ubuntu`
**MANAGERPID**: `1448`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1001/bus`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `19646`
**IM_CONFIG_PHASE**: `1`
**LOGNAME**: `laxenair`
**_**: `/usr/bin/dbus-update-activation-environment`
**JOURNAL_STREAM**: `8:50179`
**XDG_SESSION_CLASS**: `user`
**USERNAME**: `laxenair`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**WINDOWPATH**: `2`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
**SESSION_MANAGER**: `local/helene:@/tmp/.ICE-unix/1678,unix/helene:/tmp/.ICE-unix/1678`
**INVOCATION_ID**: `41a1d24ea1614fedbbeb5c9263f6cff7`
**XDG_RUNTIME_DIR**: `/run/user/1001`
**XDG_MENU_PREFIX**: `gnome-`
**DISPLAY**: `:0`
**LANG**: `fr_FR.UTF-8`
**XDG_CURRENT_DESKTOP**: `ubuntu:GNOME`
**XAUTHORITY**: `/run/user/1001/gdm/Xauthority`
**XDG_SESSION_DESKTOP**: `ubuntu`
**XMODIFIERS**: `@im=ibus`
**SSH_AUTH_SOCK**: `/run/user/1001/keyring/ssh`
**SHELL**: `/bin/bash`
**QT_ACCESSIBILITY**: `1`
**GDMSESSION**: `ubuntu`
**GPG_AGENT_INFO**: `/run/user/1001/gnupg/S.gpg-agent:0:1`
**GJS_DEBUG_OUTPUT**: `stderr`
**QT_IM_MODULE**: `ibus`
**PWD**: `/home/laxenair`
**XDG_DATA_DIRS**: `/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-ubuntu:/etc/xdg`
</details>

**Comment by pbek** [comment]
Can you please test again in a new app session (see https://www.qownnotes.org/getting-started/cli-parameters.html), you have a lot of scripts installed...

> [10:50:58] [warning] QPageSetupDialog: Cannot be used on non-native printers

do you get a page setup dialog when you try to export a pdf?

**Comment by pbek** [comment]
I already found the culprit, it will be fixed in the next release.
Meanwhile a new settings session should work.
Thank you for reporting!

**Comment by pbek** [comment]
## 21.2.5
- fixed a problem with exporting notes as PDF or printing them for installations
  of QOwnNotes previous from version 21.2.0

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by helenelax** [comment]
Hello,
I have just installed version 21.2.5 and I can export the text and the 
preview to PDF.
That's good!


-- 
Hélène Laxenaire
Documentaliste - Formatrice Dynamiques de réseaux et outils collaboratifs
L'institut agro - école interne de Montpellier SupAgro
Institut d'Education à l'Agro-environnement de Florac
9, rue Célestin Freinet
48400 Florac
Le vendredi après-midi sur site : 04.66.65.65.55
Le reste de la semaine en télétravail : 06.16.43.28.71
-------------------------------------

Le 25/02/2021 à 16:21, Patrizio Bekerle a écrit :

**Comment by pbek** [comment]
Great, thank you for testing!
