### ISSUE TITLE
[Q] Script "@tag tagging in note text" not working?

### ISSUE THREAD

**Issue by olidie** [pbek/QOwnNotes#2064]
Hi, 

first I would like to say thank you Patrizio for this wonderful programme. Even though I have been using it for quite a while now I still manage to find useful things I did not know of before. 

Right now I am trying to figure out an issue with the script "@tag tagging in note text". I very much like having my tags within of my notes. This script is said to replace the tag database of qownnotes. Problem is that it simply does not work. None of the tags I add with default @ appear in qownnotes tag panel. 

Am I doing anything wrong? qownnotes is up to date to the newest version. 

Oli

**Comment by pbek** [comment]
Thank you for your kind words. 😁 
Best open an issue at https://github.com/qownnotes/scripts/issues and don't forget to mention the script creators.
I'll close this question here.

**Comment by pbek** [comment]
(And don't forget to fill out the rest of the issue template so someone can help you) 😉
