### ISSUE TITLE
[I] Script "@tag tagging in note text" not working

### ISSUE THREAD

**Issue by olidie** [pbek/QOwnNotes#2065]
#### Expected behaviour

After installing the "@tag tagging in note text" by @Maboroshy the in-text @tags should show up in qownnotes' tag panel.

#### Actual behaviour

@Tags do not show up in qownnotes' tag panel.

#### Steps to reproduce

Installing the "@tag tagging in note text" and therewith replacing qownnotes own tag system with in-text tags.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[14:29:30] [debug] updatePanelMenu - 'updatePanelMenu'
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fr Mrz 5 14:29:37 2021`
**Version**: `21.3.0`
**Build date**: `Mar  4 2021`
**Build number**: `816`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\olidie\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `D:\Portable\QOwnNotes\QOwnNotes.exe`, `--after-update`, `C:\Users\olidie\AppData\Local\Temp\QOwnNotes-OLhMpA-updater.bat`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: `en`
**Primary screen resolution**: `1920x1200`
**Screen resolution(s)**: `1920x1200, 1920x1080`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `82`
**Calendar items**: `0`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: `https://`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `20.0.8.1`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\olidie\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Notizen`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `C:\Users\olidie\G`
**remotePath**: *empty*
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `Outdoor`
**database file**: `C:\Users\olidie\G`

### Note folder `NTZEN_new`

**id**: `2`
**isCurrent**: `no`
**activeTagId**: `1`
**localPath**: 
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: 

### Cloud connection `Wolke`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `
**username**: `olidie`

### Script `@tag tagging in note text (experimental)`

**id**: `1`
**path**: `C:\Users\olidie\AppData\Roaming\PBE\QOwnNotes\scripts\in-note-text-tagging\in-note-text-tagging.qml`
**variablesJson**: *empty*
**identifier**: `in-note-text-tagging`
**version**: `0.0.9`
**minAppVersion**: `20.6.0`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/editorWidthMode** (int): `2`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (int): `21`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `D:/Desktop`
**FileDialog/LastPath-InsertImage** (QString): 
**FileDialog/LastPath-NoteHTMLExport** (QString): `C:/Users/olidie/
**FileDialog/LastPath-NotePDFExport** (QString): `D:/Desktop`
**ImageDialog/disableCopying** (QString): `true`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-03-05T13:34:35.561`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Reise, Outdoor`
**MainWindow/noteSubFolderTreeWidgetExpandState-2** (QStringList): `Freizeit`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,15,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,14,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `false`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MainWindow/tagTreeWidgetExpandState-1** (QStringList): *empty*
**MessageBoxOverride/update-and-restart** (int): `16384`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): `Zelt+Bivy`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `Outdoor`
**NoteFolder-1/allowDifferentNoteFileName** (QString): `true`
**NoteFolder-2/NoteTabNameList** (QStringList): `Kistenliste`
**NoteFolder-2/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-2/NoteTabSubFolderPathDataList** (QStringList): `Privat`
**NoteFolder-2/allowDifferentNoteFileName** (QString): `true`
**NoteHistory-1** (QVariantList): `<variant list with 156 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 6 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `155`
**NoteHistoryCurrentIndex-2** (int): `5`
**OrphanedImagesDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExportOrientation** (int): `0`
**Printer/NotePDFExportPageSize** (int): `4`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**TagAddDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `4fc7c0e8-caf1-4c6c-b0dd-b6502f656586`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `false`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `true`
**imageScaleDownMaximumHeight** (int): `1000`
**imageScaleDownMaximumWidth** (int): `1000`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): `en`
**internalIconTheme** (QString): `true`
**itemHeight** (int): `15`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `true`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `C:/Users/olidie/G
**notifyAllExternalModifications** (QString): `true`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/ignoreNonTodoCalendars** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `2`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVUsername** (QString): `olidie`
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unbekannter Fehler`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `20.0.8.1`
**previousWorkspace** (QString): `initial`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List, togglePanel-notePreviewDockWidget`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-4fc7c0e8-caf1-4c6c-b0dd-b6502f656586/name** (QString): `Reduziert`
**workspace-4fc7c0e8-caf1-4c6c-b0dd-b6502f656586/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-4fc7c0e8-caf1-4c6c-b0dd-b6502f656586/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Vollständig`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 4fc7c0e8-caf1-4c6c-b0dd-b6502f656586`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\olidie\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `CHEF`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**destination**: `D:\Portable\QOwnNotes`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**GST_PLUGIN_PATH**: 
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\olidie`
**LOCALAPPDATA**: `C:\Users\olidie\AppData\Local`
**LOGONSERVER**: 
**NUMBER_OF_PROCESSORS**: `8`
**OneDrive**: 
**OS**: `Windows_NT`
**Path**: 
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 60 Stepping 3, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `3c03`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PROMPT**: `$P$G`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**qownnotesCommand**: `D:\Portable\QOwnNotes\QOwnNotes.exe --after-update C:\Users\olidie\AppData\Local\Temp\QOwnNotes-OLhMpA-updater.bat `
**SESSIONNAME**: `Console`
**source**: `C:\Users\olidie\AppData\Local\Temp\QOwnNotes-OLhMpA.zip`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\olidie\AppData\Local\Temp`
**TMP**: `C:\Users\olidie\AppData\Local\Temp`
**unzipCommand**: `C:\Users\olidie\AppData\Local\Temp\QOwnNotes-OLhMpA-unzip.exe -o C:\Users\olidie\AppData\Local\Temp\QOwnNotes-OLhMpA.zip -d D:\Portable\QOwnNotes`
**unzipExecutable**: `C:\Users\olidie\AppData\Local\Temp\QOwnNotes-OLhMpA-unzip.exe`
**USERNAME**: `olidie`
**USERPROFILE**: `C:\Users\olidie`
**windir**: `C:\WINDOWS`
</details>

**Comment by pbek** [comment]
Are you sure there s there not more useful log output if you enable the log panel (see Window / Panels)?

**Comment by olidie** [comment]
Sorry, I am a total noob but I now figured out the log panel. Opened a note and added two @tags to it. This is the log: 

> [15:44:30] [status] No script updates were found
[15:44:40] [debug] storing note file: "Test_Note.md"
[15:44:40] [debug] stored note: Note: <id>1 <name>"Test_Note" <fileName>"Test_Note.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false
[15:44:40] [debug] storeUpdatedNotesToDisk - 'count': 1
[15:44:40] [status] Stored 1 note(s) to disk
[15:44:50] [debug] storing note file: "Test_Note.md"
[15:44:50] [debug] stored note: Note: <id>1 <name>"Test_Note" <fileName>"Test_Note.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false
[15:44:50] [debug] storeUpdatedNotesToDisk - 'count': 1
[15:44:50] [status] Stored 1 note(s) to disk
[15:45:00] [debug] storing note file: "Test_Note.md"
[15:45:00] [debug] stored note: Note: <id>1 <name>"Test_Note" <fileName>"Test_Note.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false
[15:45:00] [debug] storeUpdatedNotesToDisk - 'count': 1
[15:45:00] [status] Stored 1 note(s) to disk

**Comment by pbek** [comment]
Can you please reload the scripting engine (Scripting menu) and send the log afterwards.

**Comment by olidie** [comment]
Sure: 

> [15:56:28] [debug] updatePanelMenu - 'updatePanelMenu'
[15:56:28] [debug] on_noteTreeWidget_itemSelectionChanged
[15:56:28] [debug] setCurrentNote - 'note': Note: <id>1 <name>"Test_Note" <fileName>"Test_Note.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false - 'updateNoteText': true - 'updateSelectedNote': false
[15:56:28] [debug] added to history: NoteHistoryItem: <noteName>"Test_Note" <noteSubFolderPathData>"" <cursorPosition>78 <relativeScrollBarPosition>0
[15:56:28] [debug] Reply from "/qownnotes/scripts/master/in-note-text-tagging/info.json"
[15:56:28] [debug] Reply from info.qml request
[15:56:38] [status] No script updates were found
[15:56:44] [debug] updatePanelMenu - 'updatePanelMenu'
[15:56:44] [debug] updatePanelMenu - 'updatePanelMenu'
[15:56:44] [debug] updatePanelMenu - 'updatePanelMenu'
[15:56:44] [debug] updatePanelMenu - 'updatePanelMenu'
[15:56:44] [debug] updatePanelMenu - 'updatePanelMenu'
[15:56:46] [debug] updatePanelMenu - 'updatePanelMenu'
[15:56:51] [scripting] loading script file: C:/Users/olidie/AppData/Roaming/PBE/QOwnNotes/scripts/in-note-text-tagging/in-note-text-tagging.qml
[15:56:51] [warning] QQmlComponent: Component is not ready
[15:56:51] [warning] script errors: (file:///C:/Users/olidie/AppData/Roaming/PBE/QOwnNotes/scripts/in-note-text-tagging/in-note-text-tagging.qml:1:1: Modul "QtQml" ist nicht installiert import QtQml 2.0 ^)
[15:56:51] [status] The scripting engine was reloaded
[15:56:58] [debug] storing note file: "Test_Note.md"
[15:56:58] [debug] stored note: Note: <id>1 <name>"Test_Note" <fileName>"Test_Note.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false
[15:56:58] [debug] storeUpdatedNotesToDisk - 'count': 1
[15:56:58] [status] Stored 1 note(s) to disk
[15:57:08] [debug] storing note file: "Test_Note.md"
[15:57:08] [debug] stored note: Note: <id>1 <name>"Test_Note" <fileName>"Test_Note.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false
[15:57:08] [debug] storeUpdatedNotesToDisk - 'count': 1
[15:57:08] [status] Stored 1 note(s) to disk

**Comment by pbek** [comment]
I just recognized you posted your issue again here, instead of https://github.com/qownnotes/scripts/issues, but never mind now. 😆 

> [15:56:51] [scripting] loading script file: C:/Users/olidie/AppData/Roaming/PBE/QOwnNotes/scripts/in-note-text-tagging/in-note-text-tagging.qml
[15:56:51] [warning] QQmlComponent: Component is not ready
[15:56:51] [warning] script errors: (file:///C:/Users/olidie/AppData/Roaming/PBE/QOwnNotes/scripts/in-note-text-tagging/in-note-text-tagging.qml:1:1: Modul "QtQml" ist nicht installiert import QtQml 2.0 ^)

It looks like somehow your QtQml libraries have troubles.
Best download QOwnNotes again from https://www.qownnotes.org/installation/windows.html (move away your old application folder).

**Comment by olidie** [comment]
What can I say. A fresh download did the trick. Thank you Patrizio! And sorry for posting in the wrong subforum.

**Comment by pbek** [comment]
No worries, in the end it was no script issue in any way. 😁
