### ISSUE TITLE
Not reconizing changes synced from NextCloud

### ISSUE THREAD

**Issue by Greggex** [pbek/QOwnNotes#2066]
#### Expected behaviour
When notes are synced between devices via NextCloud, QOwnNotes should always show the most recent version of the file.

#### Actual behaviour
Note edits made on another instance of QOwnNotes and synced by NextCloud are not detected when the note in question is not the selected note.

#### Steps to reproduce
This scenario uses a desktop and laptop both running QOwnNotes and both synced via NextCloud.
* Create note on desktop  
* Wait for NextCloud to Sync  
* Sleep PC.  
* Make sure NextCloud has synced to laptop  
* Note not visible in QOwnNotes  (expected)
* Refresh Note Folder  
* Edit the note on the laptop  
* Make sure NextCloud has synced  then Sleep laptop
* Wake desktop - Note updates on desktop to show changes made of laptop as expected
* Navigate to a different note (on the desktop)
* Sleep Desktop
* Return to laptop and make another edit.
* Wake desktop and navigate to test note - changes made on laptop are not showing.

#### Other information 

The attached screenshot shows the note in QOwnNotes and Okular side by side.  
In the original occurrence that trigger this report I was able to see the changes in Preview but not in Edit mode. (I could not reproduce this) I was also able to get the note to eventually show the changes by navigating to other notes and returning to the note. (I wasn't able to reproduce this either).

Editing the note on the desktop permanently looses the missing changes made on the laptop.

QOwnNotes: 21.3.0
Server version: 20.0.6.1
QOwnNotesAPI version: 20.9.0
Operating System: Manjaro Linux
KDE Plasma Version: 5.21.1
KDE Frameworks Version: 5.79.0
Qt Version: 5.15.2

![Screenshot_20210309_111431 QOwnNotes](https://user-images.githubusercontent.com/75041083/110507133-c06dbb80-80cd-11eb-9af2-1692dadbb405.png)

**Comment by Greggex** [comment]
I turned on logging and the log panel then tried again. I got the "Note was modified externally...." on the log panel and the note updates made on the laptop were displayed. But subsequent attempts with logging both off and on did not update the note with the changes made on the laptop. Also, one time when I returned to the laptop, it did not show the edits made on the desktop until I Reloaded the Folder.

I've attached some extracts from the log file. Thanks for getting back to me so quickly and please let me know what else you need.
[qownnotes.log.extracts.2021-03-09.log](https://github.com/pbek/QOwnNotes/files/6110882/qownnotes.log.extracts.2021-03-09.log)

**Comment by pbek** [comment]
QON is relying on the inotify message it gets... If there are no messages it doesn't detect changes... 

> [Mar 09 13:20:14] [warning]: QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.

I never saw that one before...

**Comment by Greggex** [comment]
I dug out an old laptop and installed the latest Xubuntu. So different hardware, different base and different DE. 

I was able to get QON to miss updates simply by suspending the laptop while updating on the PC. This did not happen every single time though. Also, once QON missed an update, it would continue to ignore updates even when the laptop was awake and QON had focus. In the mean time, Thunar was showing the updates. Refreshing the note showed the updates and QON seemed to get the next update but missed the following one. (again, without intervening suspend and verified that Thunar got the update without the need to refresh).

**Comment by pbek** [comment]
Thank you for your feedback, if you turn on the log panel with debug logs enabled you can see what inotify file system events QON get.

**Comment by Greggex** [comment]
Not much to see in the logs. The log window shows "current note modified externally" only when the note gets updated. The log file shows nothing when an update is missed. The following are the log entries for a Ctrl-shift-R

[Mar 22 16:10:10] [debug]: buildNotesIndex  - 'noteSubFolderId':  0
[Mar 22 16:10:10] [debug]: setupNoteFolderTables  - 'database version':  14
[Mar 22 16:10:10] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Shared" <serverUrl>"http://server:8080" <username>"gregg" <priority>0
[Mar 22 16:10:10] [debug]: fetchShares  - 'url':  QUrl("http://server:8080/ocs/v2.php/apps/files_sharing/api/v1/shares")
[Mar 22 16:10:10] [debug]: loadNoteDirectoryList
[Mar 22 16:10:10] [debug]: reloadTagTree
[Mar 22 16:10:10] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(0)
[Mar 22 16:10:10] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(0)
[Mar 22 16:10:10] [debug]: reloadNoteSubFolderTree
[Mar 22 16:10:10] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(0)
[Mar 22 16:10:10] [debug]: No scores for "NUC 2021-03-22 8:09 A.M."
[Mar 22 16:10:10] [debug]: No scores for "NUC 2021-03-22 8:11 A.M."
[Mar 22 16:10:10] [debug]: No scores for "NUC 2021-03-22 8:56 A.M."
[Mar 22 16:10:10] [debug]: No scores for "NUC 2021-03-22 10:43 A.M."
[Mar 22 16:10:10] [debug]: No scores for "NUC 2021-03-22 10:58 A.M."
[Mar 22 16:10:10] [debug]: No scores for "NUC 2021-03-22 11:12 A.M."
[Mar 22 16:10:10] [debug]: No scores for "NUC 2021-03-22 11:22 A.M."
[Mar 22 16:10:10] [debug]: No scores for "NUC 2021-03-22 11:24 A.M."
[Mar 22 16:10:10] [debug]: No scores for "NUC 2021-03-22 11:29 A.M."
[Mar 22 16:10:10] [debug]: No scores for "NUC 2021-03-22 3:47 P.M."
[Mar 22 16:10:10] [debug]: No scores for "NUC 2021-03-22 3:48 P.M."
[Mar 22 16:10:10] [debug]: No scores for "NUC 2021-03-22 3:49 P.M."
[Mar 22 16:10:10] [debug]: No scores for "NUC 2021-03-22 4:07 P.M."
[Mar 22 16:10:11] [debug]: Reply from  "/ocs/v2.php/apps/files_sharing/api/v1/shares"
[Mar 22 16:10:11] [debug]: Reply from share api
[Mar 22 16:10:11] [debug]: updateNoteShareStatusFromShare  - 'status':  "ok\n"
[Mar 22 16:11:47] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Shared" <serverUrl>"http://server:

"NUC _timestamp_" are the lines I added to the note today.

For the last few updates, the QON saves the file after I type "NUC" and before I type ctrl-T. So the updates get sent in two stages. QON on the laptop will show the "NUC" almost immediately. But when the second update gets to the laptop, Thunar shows the time and size change, but nothing happens in QON.
