### ISSUE TITLE
Notes list is not updated when other notes in the note folder are modified externally [Win]

### ISSUE THREAD

**Issue by giovi321** [pbek/QOwnNotes#207]
Windows 7 machine running QOwnNotes 16.06.3 build 1731.
When QOwnNotes is running and is in the taskbar, if notes are edited externally they don't appear in the notes list of QOwnNotes until it is restarted.
It is very convenient to keep it running in the background as it takes one second or two to start QOwnNotes if it is not already started.

**Comment by pbek** [comment]
Thank you for reporting. 

> if notes are edited externally

do you mean if new notes are created in your active note folder?

**Comment by giovi321** [comment]
I am sorry, I was not very precise.
I actually meant when notes are created not through qownnotes.

**Comment by pbek** [comment]
I cannot reproduce this with v16.06.4 on Windows 8.1. If I create a file `test.txt` directly with Explorer in the note folder it immediately shows up in the note list in QOwnNotes.

Can you please explain what you are doing and also post the debug information from the settings dialog.

**Comment by giovi321** [comment]
Well, if I reload the note folder (ctrl+shift+r) it works. But until I exit (completely, also from the tray) QOwnNotes it doesn't refresh the list.

> QOwnNotes Debug Information
> ===========================
> 
> ## General Info
> 
> **Current Date**: `lun giu 13 20:28:14 2016`
> **Version**: `16.06.3`
> **Build date**: `Jun 11 2016`
> **Build number**: `1731`
> **Platform**: `windows`
> **Operating System**: `Windows 7`
> **Build architecture**: `i386`
> **Current architecture**: `x86_64`
> **Release**: `AppVeyor`
> **Qt Version (build)**: `5.5.1`
> **Qt Version (runtime)**: `5.5.1`
> **Locale (system)**: `it_IT`
> **Locale (interface)**: `en`
> **Icon theme**: `breeze-qownnotes`
> 
> ## Server Info
> 
> **serverUrl**: *empty*
> **appIsValid**: `yes`
> **serverVersion**: *empty*
> **appVersion**: *empty*
> 
> ## Settings
> 
> **DistractionFreeMode/isEnabled**: `false`
> **DistractionFreeMode/mainSplitterSizes**: `<binary data>`
> **DistractionFreeMode/menuBarGeometry**: `<binary data>`
> **DistractionFreeMode/menuBarHeight**: `21`
> **DistractionFreeMode/windowState**: `<binary data>`
> **LastUpdateCheck**: `2016-06-13T20:23:04`
> **LogDialog/criticalLog**: `true`
> **LogDialog/debugLog**: `false`
> **LogDialog/fatalLog**: `true`
> **LogDialog/geometry**: `<binary data>`
> **LogDialog/infoLog**: `false`
> **LogDialog/scriptingLog**: `true`
> **LogDialog/showAtStartup**: `false`
> **LogDialog/statusLog**: `true`
> **LogDialog/warningLog**: `false`
> **MainWindow/geometry**: `<binary data>`
> **MainWindow/mainToolBar.iconSize**: `24`
> **MainWindow/markdownDefaultViewMode**: `false`
> **MainWindow/menuBarGeometry**: `<binary data>`
> **MainWindow/noteTextEdit.code.font**: `Courier,8,-1,5,50,0,0,0,0,0`
> **MainWindow/noteTextEdit.font**: `MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0`
> **MainWindow/noteTextView.code.font**: `Courier,8.25,-1,5,50,0,0,0,0,0`
> **MainWindow/noteTextView.font**: `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
> **MainWindow/showRecentNoteFolderInMainArea**: `true`
> **MainWindow/windowState**: `<binary data>`
> **PiwikClientId**: `<hidden>`
> **ShowSystemTray**: `true`
> **SortingModeAlphabetically**: `false`
> **allowDifferentNoteFileName**: `false`
> **allowOnlyOneAppInstance**: `true`
> **appMetrics/disableAppHeartbeat**: `true`
> **appMetrics/disableTracking**: `true`
> **appMetrics/notificationShown**: `true`
> **cryptoKey**: `<hidden>`
> **currentNoteFolderId**: `1`
> **customNoteFileExtensionList**: *empty*
> **darkModeColors**: `false`
> **defaultNoteFileExtension**: `txt`
> **disableAutomaticUpdateDialog**: `false`
> **externalEditorPath**: *empty*
> **ignoreAllExternalModifications**: `false`
> **interfaceLanguage**: `en`
> **mainSplitterSizes**: `<binary data>`
> **mainSplitterState-0-0-0-0**: `<binary data>`
> **mainSplitterState-0-0-1-0**: `<binary data>`
> **mainSplitterState-0-0-1-1**: `<binary data>`
> **mainSplitterState-0-1-0-0**: `<binary data>`
> **mainSplitterState-0-1-1-0**: `<binary data>`
> **mainSplitterState-1-0-1-0**: `<binary data>`
> **markdownHighlightingInterval**: `100`
> **markdownViewEnabled**: `false`
> **networking/ignoreSSLErrors**: `false`
> **networking/proxyType**: `2`
> **noteEditPaneEnabled**: `true`
> **noteListSplitterState**: `<binary data>`
> **noteSaveIntervalTime**: `5`
> **notesPath**: `C:/Users/G/Notes`
> **notifyAllExternalModifications**: `false`
> **ownCloud/password**: `<hidden>`
> **ownCloud/serverUrl**: *empty*
> **ownCloud/todoCalendarBackend**: `0`
> **ownCloud/todoCalendarEnabledList**: *empty*
> **ownCloud/todoCalendarEnabledUrlList**: *empty*
> **ownCloud/todoCalendarUrlList**: *empty*
> **ownCloud/userName**: *empty*
> **savedSearches/noteFolder-1**: `Note 2016-06-13T20.27.08, Note 2016-06-10T10.58.51, Note 2016-06-09T23.49.39, Note 2016-06-09T22.20.08`
> **skipVersion**: `16.06.4`
> **tagsEnabled**: `false`
> **verticalNoteFrameSplitterState**: `<binary data>`
> **verticalPreviewModeEnabled**: `false`

**Comment by pbek** [comment]
I can't see anything unusual in your settings, it could happen because too many files are already opened somewhere (including QOwnNotes), how many notes do you have in your note folder?

**Comment by giovi321** [comment]
64

**Comment by pbek** [comment]
Maybe I found a Qt bug under Windows... Directory changes are recognized once, but not more... So far I found no way to get around that...

**Comment by pbek** [comment]
I spent several hours trying to rewrite the whole watcher system and testing it on Windows, OS X and Linux... So far I had no luck with the problem on Windows... I just got even more weirdness.

**Comment by giovi321** [comment]
Not a big deal! It's enough to use the shortcut to rescan the folder.

**Comment by pbek** [comment]
It's very annoying. I keep it on my todo list. Thanks again for reporting!

**Comment by giovi321** [comment]
Maybe you can decrease the rescan interval? Or create an option to scan at certain intervals? Just wondering...

**Comment by pbek** [comment]
there is no "scan", there are notifications from the operating system if watched files or folders change

**Comment by pbek** [comment]
a real scan would take far too long for many notes on a spinning disk
