### ISSUE TITLE
[Feature Request] Right click menu option in preview panel to open image/photo in external editor

### ISSUE THREAD

**Issue by jg55** [pbek/QOwnNotes#2072]
Once again, thanks for this amazing app. Here's a feature request suggestion. If this feature exists, I can't find it, apologies if this is a duplicate:

**[Feature Request] Right click menu option in preview panel to open image/photo in external editor**

1 - Behavior: in addition to the existing options, when you right-click on an image in the preview panel, there would be another option to edit the photo in an external editor such as GIMP or Photoshop, etc. 

2 - Once edited and saved to the exact same filename, QOwnNotes would refresh with the new image.

3 - In the preferences somewhere there would be an option where we can set the default photo editing app.

**Comment by pbek** [comment]
Thank you. 😉  You may want to look at the script `Image preview` in the script repository. 😁

**Comment by jg55** [comment]
👍 Great! I will check it out! From first glance, it also looks like it will help out with a max width feature suggestion I was thinking of writing. Looks like I need to spend some time in the script repository to see what other goodies are in there, before I post anything else. 😁

Link for future reference: https://github.com/qownnotes/scripts

Link to image-preview script: https://github.com/qownnotes/scripts/tree/master/image-preview

**Comment by pbek** [comment]
😁 👍🏻
