### ISSUE TITLE
How do I update `QOwnNotes`?

### ISSUE THREAD

**Issue by it19862** [pbek/QOwnNotes#2075]
**Questions.**
	1. How do I update the program?
	2. What did `QOwnNotes` download?
	3. Where did you download it ?

#### Expected behavior
Updating the pro-program from `QOwnNotes-21.3.1` to `QOwnNotes-21.3.2`. 

#### Actual behavior
  I went to `Help` > `Check for updates`.
  I clicked the `Update` button.
 `QOwnNotes` has started downloading.
  The download is over. 
  I restarted `QOwnNotes`. 

  I still have the original version of the program - `QOwnNotes` - 21.3.1.

#### Steps to reproduce
  Go to `Help` > `Check for updates`.
  Click the `Update` button.
 `QOwnNotes` has started downloading.
  The download is over. 
  Restart `QOwnNotes`. 

 
#### Output from the debug section in the settings dialog
 
<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Сб мар 20 15:35:50 2021`
**Version**: `21.3.1`
**Build date**: `Mar 12 2021`
**Build number**: `817`
**Platform**: `windows`
**Operating System**: `Windows 7 Version 6.1 (Build 7601: SP 1)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\admin\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\ProgramPrtbl\QOwnNotes\v21.3.1\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `ru_RU`
**Locale (interface)**: `ru`
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `7`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\admin\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `2`

### Note folder `по умолчанию`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `Z:\QOwnNotesBook\v21.3.1\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `Z:\QOwnNotesBook\v21.3.1\Notes\notes.sqlite`

### Note folder `AA_Folder`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `Z:\QOwnNotesBook\v21.3.1\AA_Folder`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `Z:\QOwnNotesBook\v21.3.1\AA_Folder\notes.sqlite`

### Cloud connection ``

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/editorWidthMode** (int): `3`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**LastUpdateCheck** (QDateTime): `2021-03-20T15:07:46.555`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-2** (QStringList): `AB_Folder, AС_Folder, AB_Folder/ABA_Folder`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MainWindow/tagTreeWidgetExpandState-2** (QStringList): *empty*
**NoteFolder-1/NoteTabNameList** (QStringList): `Note 2021-03-18T10.39.26`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteFolder-2/NoteTabNameList** (QStringList): `AA_Note`
**NoteFolder-2/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-2/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteFolder-2/allowDifferentNoteFileName** (QString): `true`
**NoteHistory-1** (QVariantList): `<variant list with 1 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 6 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `0`
**NoteHistoryCurrentIndex-2** (int): `5`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `2`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `true`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): `ru`
**internalIconTheme** (QString): `false`
**itemHeight** (int): `15`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `false`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `Z:/QOwnNotesBook/v21.3.1/AA_Folder`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `0`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**recentNoteFolders** (QStringList): `Z:/QOwnNotesBook/v21.3.1/Notes`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Главная панель инструментов`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `панель инструментов форматирования`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `панель инструментов вставки`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `панель инструментов шифрования`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `панель инструментов окна`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `Панель инструментов выхода`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Полный`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment
**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\admin\AppData\Roaming`
**COMMANDER_DRIVE**: `C:`
**COMMANDER_EXE**: `C:\Program Files\Total Commander v9.12 RC 3_nastr\TOTALCMD64.EXE`
**COMMANDER_INI**: `C:\Program Files\Total Commander v9.12 RC 3_nastr\wincmd.ini`
**COMMANDER_INSTANCE**: `1`
**COMMANDER_PATH**: `C:\Program Files\Total Commander v9.12 RC 3_nastr`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `SRV2`
**ComSpec**: `C:\Windows\system32\cmd.exe`
**EMAIL**: `e:\The Bat\mail1`
**ERLANG_HOME**: `C:\Program Files\erl8.1`
**FP_NO_HOST_CHECK**: `NO`
**GYP_MSVS_VERSION**: `2015`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\admin`
**JAVA_HOME**: `c:\Program Files\Java\jdk-13\`
**LANG**: `RU`
**LOCALAPPDATA**: `C:\Users\admin\AppData\Local`
**LOGONSERVER**: `\\SRV2`
**MAVEN_HOME **: `c:\Program Files\Maven353`
**MOZ_PLUGIN_PATH**: `C:\Program Files (x86)\Foxit Software\Foxit Reader\plugins\`
**MSMPI_BIN**: `C:\Program Files\Microsoft MPI\Bin\`
**MYSQLCONNECTOR_ASSEMBLIESPATH**: `C:\Program Files (x86)\MySQL\MySQL Connector Net 6.9.9\Assemblies\v4.5`
**NUMBER_OF_PROCESSORS**: `2`
**OneDrive**: `C:\Users\admin\OneDrive`
**OneDriveConsumer**: `C:\Users\admin\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\ActiveState Komodo Edit 12\;C:\Program Files\Microsoft MPI\Bin\;c:\WEBOpSrvr\modules\php\PHP-5.6-x64\;c:\Program Files\Maven353\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\ProgramData\AutomationBox\MouseRobot2\Application;C:\ProgramData\AutomationBox\MouseRobot2\Application\tools;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microsoft\Web Platform Installer\;c:\Program Files\Java\jdk-10\bin\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files\PuTTY\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\GitExtensions\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Nmap;E:\srw\webopsrvr\modules\php\PHP-5.5-x64\;C:\Users\admin\AppData\Local\Programs\Fiddler;C:\Users\admin\AppData\Roaming\npm;C:\Users\admin\.dotnet\tools;C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\bin;C:\ProgramPrtbl\MarkdownMonster\1.26.4.4`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 23 Stepping 10, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `170a`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Windows\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SHFBROOT**: `C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\`
**SystemDrive**: `C:`
**SystemRoot**: `C:\Windows`
**TelerikWPFDir**: `C:\Program Files (x86)\Progress\Telerik UI for WPF R1 2018\`
**TEMP**: `C:\Users\admin\AppData\Local\Temp`
**TMP**: `C:\Users\admin\AppData\Local\Temp`
**USERDOMAIN**: `srv2`
**USERNAME**: `admin`
**USERPROFILE**: `C:\Users\admin`
**VBOX_MSI_INSTALL_PATH**: `C:\Program Files\Oracle\VirtualBox\`
**VS120COMNTOOLS**: `C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\`
**VS140COMNTOOLS**: `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\`
**windir**: `C:\Windows`
**windows_tracing_flags**: `3`
**windows_tracing_logfile**: `C:\BVTBin\Tests\installpackage\csilogfile.log`

</details>
 
#### Relevant log output in the Log panel
No messages.

####  QOwnNotes.log
The text is given after the update attempt is repeated.

<details><summary>Expand</summary>

[мар 20 15:51:24] [debug]: Set proxy configuration to use NO proxy
[мар 20 15:51:26] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[мар 20 15:51:26] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"" <serverUrl>"" <username>"" <priority>0
[мар 20 15:51:26] [debug]: loadNoteDirectoryList
[мар 20 15:51:26] [debug]: reloadTagTree
[мар 20 15:51:26] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector()
[мар 20 15:51:27] [debug]: reloadNoteSubFolderTree
[мар 20 15:51:27] [debug]: loadNoteDirectoryList
[мар 20 15:51:27] [debug]: reloadTagTree
[мар 20 15:51:27] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector()
[мар 20 15:51:44] [debug]: dialogButtonClicked  - 'releaseUrl':  "https://github.com/pbek/QOwnNotes/releases/download/v21.3.2/QOwnNotes.zip"
[мар 20 15:51:57] [debug]: Reply from  "/27436491/10582b00-8810-11eb-8e02-4d37ef2b5d77"
[мар 20 15:51:57] [debug]: slotReplyFinished  - 'data.size':  39432821
[мар 20 15:51:59] [debug]: initializeWindowsUpdateProcess  - 'parameters':  ("C:\\Users\\admin\\AppData\\Local\\Temp\\QOwnNotes-sdReMV.zip", "C:\\ProgramPrtbl\\QOwnNotes\\v21.3.1", "C:\\Users\\admin\\AppData\\Local\\Temp\\QOwnNotes-sdReMV-unzip.exe")
[мар 20 15:51:59] [debug]: storeSettings  - 'noteHistoryItem':  NoteHistoryItem: <noteName>"Note 2021-03-18T18.48.40" <noteSubFolderPathData>"AB_Folder\nABA_Folder" <cursorPosition>51 <relativeScrollBarPosition>0
[мар 20 15:52:18] [debug]: Set proxy configuration to use NO proxy
[мар 20 15:52:18] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[мар 20 15:52:18] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"" <serverUrl>"" <username>"" <priority>0
[мар 20 15:52:18] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[мар 20 15:52:19] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:52:19] [debug]: buildNotesIndex  - 'noteSubFolderId':  0
[мар 20 15:52:19] [debug]: setupNoteFolderTables  - 'database version':  14
[мар 20 15:52:19] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"" <serverUrl>"" <username>"" <priority>0
[мар 20 15:52:19] [debug]: loadNoteDirectoryList
[мар 20 15:52:19] [debug]: reloadTagTree
[мар 20 15:52:19] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector()
[мар 20 15:52:19] [debug]: loadNoteDirectoryList
[мар 20 15:52:19] [debug]: reloadTagTree
[мар 20 15:52:19] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector()
[мар 20 15:52:19] [debug]: reloadNoteSubFolderTree
[мар 20 15:52:20] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:52:20] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:52:20] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:52:20] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:52:20] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:52:20] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:52:20] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:52:20] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:52:20] [info]: "QOwnNotes сервер прослушивает порт 22222"
[мар 20 15:52:20] [debug]: on_noteTreeWidget_itemSelectionChanged
[мар 20 15:52:20] [debug]: setCurrentNote  - 'note':  Note: <id>6 <name>"Note 2021-03-18T18.48.40" <fileName>"Note 2021-03-18T18.48.40.md" <noteSubFolderId>2 <relativePath>"AB_Folder/ABA_Folder" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
[мар 20 15:52:20] [debug]:  added to history:  NoteHistoryItem: <noteName>"Note 2021-03-18T18.48.40" <noteSubFolderPathData>"AB_Folder\nABA_Folder" <cursorPosition>51 <relativeScrollBarPosition>0
[мар 20 15:52:30] [status]: Обновления скрипта не найдены
[мар 20 15:52:41] [debug]: dialogButtonClicked  - 'releaseUrl':  "https://github.com/pbek/QOwnNotes/releases/download/v21.3.2/QOwnNotes.zip"
[мар 20 15:52:54] [debug]: Reply from  "/27436491/10582b00-8810-11eb-8e02-4d37ef2b5d77"
[мар 20 15:52:54] [debug]: slotReplyFinished  - 'data.size':  39432821
[мар 20 15:52:57] [debug]: initializeWindowsUpdateProcess  - 'parameters':  ("C:\\Users\\admin\\AppData\\Local\\Temp\\QOwnNotes-qyefUy.zip", "C:\\ProgramPrtbl\\QOwnNotes\\v21.3.1", "C:\\Users\\admin\\AppData\\Local\\Temp\\QOwnNotes-qyefUy-unzip.exe")
[мар 20 15:52:57] [debug]: storeSettings  - 'noteHistoryItem':  NoteHistoryItem: <noteName>"Note 2021-03-18T18.48.40" <noteSubFolderPathData>"AB_Folder\nABA_Folder" <cursorPosition>51 <relativeScrollBarPosition>0
[мар 20 15:53:08] [debug]: Set proxy configuration to use NO proxy
[мар 20 15:53:08] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[мар 20 15:53:08] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"" <serverUrl>"" <username>"" <priority>0
[мар 20 15:53:08] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[мар 20 15:53:08] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:53:08] [debug]: buildNotesIndex  - 'noteSubFolderId':  0
[мар 20 15:53:08] [debug]: setupNoteFolderTables  - 'database version':  14
[мар 20 15:53:08] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"" <serverUrl>"" <username>"" <priority>0
[мар 20 15:53:08] [debug]: loadNoteDirectoryList
[мар 20 15:53:08] [debug]: reloadTagTree
[мар 20 15:53:08] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector()
[мар 20 15:53:09] [debug]: loadNoteDirectoryList
[мар 20 15:53:09] [debug]: reloadTagTree
[мар 20 15:53:09] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector()
[мар 20 15:53:09] [debug]: reloadNoteSubFolderTree
[мар 20 15:53:09] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:53:09] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:53:09] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:53:09] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:53:09] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:53:09] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:53:10] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:53:10] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:53:10] [info]: "QOwnNotes сервер прослушивает порт 22222"
[мар 20 15:53:10] [debug]: on_noteTreeWidget_itemSelectionChanged
[мар 20 15:53:10] [debug]: setCurrentNote  - 'note':  Note: <id>6 <name>"Note 2021-03-18T18.48.40" <fileName>"Note 2021-03-18T18.48.40.md" <noteSubFolderId>2 <relativePath>"AB_Folder/ABA_Folder" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
[мар 20 15:53:10] [debug]:  added to history:  NoteHistoryItem: <noteName>"Note 2021-03-18T18.48.40" <noteSubFolderPathData>"AB_Folder\nABA_Folder" <cursorPosition>51 <relativeScrollBarPosition>0
[мар 20 15:53:13] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:53:13] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:53:13] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:53:13] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:53:13] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:53:13] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:53:13] [debug]: updatePanelMenu  - 'updatePanelMenu'
[мар 20 15:53:13] [debug]: updatePanelMenu  - 'updatePanelMenu'

</details>

![2021-03-20_15-12-03](https://user-images.githubusercontent.com/18245828/111870530-5b9c4600-8996-11eb-8fc5-cfa22d7d696a.png)

![2021-03-20_15-14-17](https://user-images.githubusercontent.com/18245828/111870533-5f2fcd00-8996-11eb-85ab-12340446c7ed.png)

**Comment by pbek** [comment]
If you pressed the update button QOwnNotes is supposed to download the latest ZIP from GitHub, start an updater batch file, quit QON, unzip the ZIP file, copy the new files into your QON directory and start QON again.

Are you sure your current user has write permissions to `C:\ProgramPrtbl\QOwnNotes\v21.3.1\`?
See: https://www.qownnotes.org/installation/windows.html

**Comment by it19862** [comment]
@pbek 
### Solution-1. Write rights.   
I don't understand it well, but it seems that there are write rights.
**Picture-1**.
![2021-03-20_20-41-04](https://user-images.githubusercontent.com/18245828/111880571-51da0900-89bd-11eb-8390-a38f21c30c13.png)


### Solution-2. Alternative solution.   
What alternative solution can be applied?
How do I make sure that the settings are not reset during the update?
I understand it this way-see description below?
Description.
- download the latest version from the link QOwnNotes_Releases_on_GitHub;
- unpack the archive;
- copy the contents to a folder `C:\ProgramPrtbl\QOwnNotes\v21.3.1\`?

**Comment by pbek** [comment]
> I don't understand it well, but it seems that there are write rights.

I'm sorry, I can't read Russian 😁 

> What alternative solution can be applied?

How do I make sure that the settings are not reset during the update?

Settings are not reset during "update".
Are you sure you didn't run QON in portable mode before? In portable mode the setting are written to the folder where you put the QON binary...
Without portable mode your settings are written to your Windows registry.

> copy the contents to a folder C:\ProgramPrtbl\QOwnNotes\v21.3.1\?

Looking good (beside that I wouldn't use a version number in the folder name).

**Comment by Addepalli-Balaji** [comment]
Hi so when you run the application as administrator and then hit update. The application updates successfully.

**Comment by pbek** [comment]
It should be enough if you have write permissions to the folder and the files in the folder (and the temporary path)...
