### ISSUE TITLE
[F] Issue/Feature Request: Remote git repositories

### ISSUE THREAD

**Issue by teotikalki** [pbek/QOwnNotes#2076]
#### Expected behaviour

Hi. I'm a happy QOwnNotes user for several years now. I use it with my own local Nextcloud installation for sync.

I have used the 'Use git to keep local history of your notes' feature since the beginning. I have noticed that syncing the .git folder is MOST of the work that my Nextcloud is actualy doing! The git folder is also (by FAR) most of my Notes foldeer itself (see below). I have long thought that the best solution to this is to allow for a remote git repository.

What I would like (Expected behaviour):

+ Each client can use QON and Nextcloud
+ Nextcloud will sync the notes folder
	+ Nextcloud will IGNORE the git folder (really all .git folders)
	+ This sync will be very fast as THOUSANDS of tiny objects will no longer be handled
+ Each client will push to a remote git repository (in my case, my local kallithea instance)

From the UI, the interface could simply be updated to:

'Use Git to keep a history of your notes?' -> Y
'Keep local git repo' or 'Enter url for remote repository'

#### Actual behaviour

```
teoti@avalon:~/Nextcloud$ du -ms Notes/
866	Notes/
```
```
teoti@avalon:~/Nextcloud$ du -ms Notes/.git
855	Notes/.git
```

I frequently have 'Conflicted copy' sync errors which I have gotten used to ignoring/dealing with by deleting the conflicted copy. I am currently having a serious issue with corruption in the git repo, which I started looking into because one or two folders have selectively stopped syncing.

#### Steps to reproduce

1. Use a git repository to backup your notes AND sync your notes folder. 
2. Wait

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sun. Mar. 21 11:33:41 2021`
**Version**: `20.9.2`
**Build date**: `Sep  3 2020`
**Build number**: `757`
**Platform**: `linux`
**Operating System**: `Debian GNU/Linux bullseye/sid`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.11.3`
**Qt Version (runtime)**: `5.12.5`
**Portable mode**: `no`
**Settings path / key**: `/home/teoti/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/teoti/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_CA`
**Locale (interface)**: *empty*
**Primary screen resolution**: `2560x1440`
**Screen resolution(s)**: `2560x1440, 3840x2160, 2560x1440, 3840x2160`
**Icon theme**: `Breeze Chameleon Dark`
**Notes in current note folder**: `722`
**Calendar items**: `18`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: `https://houseoftau.net/nextcloud`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `20.0.6.1`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `en_US`
**Language codes**: `en_US`
**Language names**: `American English (United States)`
**Application dictionaries path**: `/home/teoti/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Nextcloud-Notes`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-2`
**localPath**: `/home/teoti/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `HowTo`
**database file**: `/home/teoti/Nextcloud/Notes/notes.sqlite`

### Note folder `hestiashearth.ca`

**id**: `2`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/teoti/Clients/hestiashearth.ca/markdown`
**remotePath**: `hestiashearth.ca`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/teoti/Clients/hestiashearth.ca/markdown/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://houseoftau.net/nextcloud`
**username**: `teoti`

### Script `Sort lines`

**id**: `1`
**path**: `/home/teoti/.local/share/PBE/QOwnNotes/scripts/sort-lines/sort-lines.qml`
**variablesJson**: *empty*
**identifier**: `sort-lines`
**version**: `1.0.0`
**minAppVersion**: `18.04.3`

## Settings

**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `24`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-9c24397c-3122-4a0d-bc05-1989bdc7fa01`
**Editor/autoBracketClosing** (bool): `false`
**Editor/autoBracketRemoval** (bool): `false`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrainingSpaces** (bool): `false`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**ImageDialog/disableCopying** (QString): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-03-21T10:38:59.538`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Teoti, Hyperborea, House of Tau/Rackshasa/Maintenance, House of Tau/TLC/Hardware Selection, Clients/teoti.me, House of Tau/Rackshasa/Install Journals, Clients, House of Tau/Rackshasa/HowTo, Teotihuacanata, House of Tau/Rackshasa/Software Selection/Dev, House of Tau/Rackshasa/Software Selection/Dev/Frontend, House of Tau/Farm/Equipment, House of Tau/Rackshasa/Software Selection/Userland, House of Tau/Farm/Plants, House of Tau/Ningishzidda/Genetics, House of Tau/Ningishzidda/Psilocybe, House of Tau/Ningishzidda/Cannabis, House of Tau/TLC, House of Tau/Farm/Marketing, House of Tau/Rackshasa, House of Tau/Farm, House of Tau/Rackshasa/Software Selection, House of Tau`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Cantarell,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Cantarell,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/local-trash-notes-restored** (QString): `1024`
**MessageBoxOverride/move-notes** (QString): `16384`
**MessageBoxOverride/note-replace-links** (QString): `16384`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): `Joinery, Using Git`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): 
```
House of Tau
TLC
Hardware Selection
Woodworking, House of Tau
Rackshasa
HowTo
```
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteFolder-2/NoteTabNameList** (QString): `Germination`
**NoteFolder-2/NoteTabStickinessList**: *empty*
**NoteFolder-2/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteHistory-1** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `199`
**NoteHistoryCurrentIndex-2** (QString): `79`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-customAction_sortLinesAsc** (QKeySequence): *empty*
**Shortcuts/MainWindow-customAction_sortLinesDesc** (QKeySequence): *empty*
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Personal`
**TrashDialog/geometry** (QByteArray): `<binary data>`
**VersionDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full-vertical`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (int): `19`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `false`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/teoti/Nextcloud/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Personal, Deck: Grand Trunk Island, Deck: Personal`
**ownCloud/todoCalendarEnabledList** (QStringList): `Personal, Deck: Grand Trunk Island, Deck: Personal`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://houseoftau.net/nextcloud/remote.php/dav/calendars/teoti/personal/, https://houseoftau.net/nextcloud/remote.php/dav/calendars/teoti/app-generated--deck--board-2/, https://houseoftau.net/nextcloud/remote.php/dav/calendars/teoti/app-generated--deck--board-1/`
**ownCloud/todoCalendarUrlList** (QStringList): `https://houseoftau.net/nextcloud/remote.php/dav/calendars/teoti/personal/, https://houseoftau.net/nextcloud/remote.php/dav/calendars/teoti/app-generated--deck--board-2/, https://houseoftau.net/nextcloud/remote.php/dav/calendars/teoti/app-generated--deck--board-1/`
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `20.0.6.1`
**previousWorkspace** (QString): `initial`
**recentNoteFolders** (QString): `/home/teoti/Clients/hestiashearth.ca/markdown`
**restoreCursorPosition** (bool): `true`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2021-03-21T10.31.49, Note 2021-03-18T08.56.45, Note 2021-03-16T12.02.36, Note 2021-03-16T12.00.09, Note 2021-03-15T17.26.32, Note 2021-03-15T16.39.06, Note 2021-03-14T10.07.43, Note 2021-03-14T10.07.30, Note 2021-03-14T10.07.13, Note 2021-03-14T10.06.59, Note 2021-03-14T08.39.12, Note 2021-03-14T07.43.00, Note 2021-03-14T07.33.28, Note 2021-03-14T07.14.17, Note 2021-03-13T06.41.57, Note 2021-03-13T05.57.01, Note 2021-03-11T10.06.21, Note 2021-03-11T08.58.28, Note 2021-03-09T08.55.09, Note 2021-03-09T08.51.05, Note 2021-03-09T08.46.04, Note 2021-03-09T08.31.25, Note 2021-03-08T23.08.11, Note 2021-03-08T07.44.38, Note 2021-03-08T07.24.57, Note 2021-03-08T07.18.38, Note 2021-03-08T07.18.01, Note 2021-03-06T08.31.18, Note 2021-03-06T07.24.28, ?, Note 2021-03-05T22.01.23, Note 2021-03-05T21.55.34, Note 2021-03-05T14.19.50, Note 2021-03-01T20.36.12, Note 2021-02-28T14.17.06, Note 2021-02-28T14.11.31, Note 2021-02-28T14.06.12, Note 2021-02-28T14.04.45, Note 2021-02-28T09.54.41, Note 2021-02-28T09.43.44, Note 2021-02-28T09.42.01, Note 2021-02-28T09.41.03, Note 2021-02-28T09.39.18, Note 2021-02-28T09.35.30, Note 2021-02-28T09.34.56, Note 2021-02-28T09.33.12, Note 2021-02-28T09.31.55, Note 2021-02-28T09.30.10, Note 2021-02-28T09.29.14, Note 2021-02-28T09.27.45, Note 2021-02-28T09.25.16, Note 2021-02-25T19.36.20, Note 2021-02-25T10.19.16, Note 2021-02-24T19.31.35, Note 2021-02-24T18.36.13, Note 2021-02-24T18.07.48, Note 2021-02-24T11.57.05, Note 2021-02-24T10.45.04, Note 2021-02-22T17.18.55, Note 2021-02-22T11.26.25, Note 2021-02-21T08.06.23, Note 2021-02-20T19.33.47, Note 2021-02-20T12.20.43, Note 2021-02-18T08.40.49, Note 2021-02-18T07.51.54, Note 2021-02-12T10.39.56, Note 2021-02-12T08.15.58, Note 2021-02-10T10.13.27, Note 2021-02-09T20.40.24, Note 2021-02-09T12.41.20, Note 2021-02-09T08.02.18, Note 2021-02-09T06.58.59, Note 2021-02-08T11.11.05, Note 2021-02-07T06.40.24, Note 2021-02-06T16.44.54, Note 2021-02-04T09.51.21, Note 2021-02-02T13.26.42, Note 2021-02-02T11.02.55, Note 2021-02-01T20.53.05, Note 2021-02-01T19.25.57, Note 2021-02-01T13.21.00, Note 2021-02-01T13.19.36, Note 2021-02-01T05.15.30, Note 2021-01-31T13.37.21, Note 2021-01-31T12.44.27, Note 2021-01-30T06.45.54, Note 2021-01-29T13.43.07, Note 2021-01-22T14.44.34, Note 2021-01-11T12.02.07, Note 2020-11-16T05.29.09, Note 2020-11-15T08.39.04, Note 2020-11-15T07.48.30, Note 2020-11-15T05.22.33, Note 2020-11-13T10.33.32, Note 2020-11-12T10.08.26, Note 2020-11-10T07.48.14, Note 2020-11-10T07.40.47, Note 2020-11-10T06.37.08, Note 2020-11-03T13.38.58, Note 2020-11-03T06.58.22`
**savedSearches/noteFolder-2** (QString): `Note 2021-02-18T07.50.58`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `en_US`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**trashSplitterSizes** (QByteArray): `<binary data>`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**versionSplitterSizes** (QByteArray): `<binary data>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Full vertical`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`
**LANGUAGE**: `en_CA:en`
**USER**: `teoti`
**XDG_SESSION_TYPE**: `wayland`
**SHLVL**: `0`
**HOME**: `/home/teoti`
**DESKTOP_SESSION**: `gnome`
**GIO_LAUNCHED_DESKTOP_FILE**: `/usr/share/applications/PBE.QOwnNotes.desktop`
**GTK_MODULES**: `gail:atk-bridge`
**MANAGERPID**: `2175`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `7073`
**WAYLAND_DISPLAY**: `wayland-0`
**LOGNAME**: `teoti`
**_**: `/usr/bin/gnome-session`
**JOURNAL_STREAM**: `9:35356`
**XDG_SESSION_CLASS**: `user`
**USERNAME**: `teoti`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**PATH**: `/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`
**GDM_LANG**: `en_CA.UTF-8`
**SESSION_MANAGER**: `local/avalon:@/tmp/.ICE-unix/2307,unix/avalon:/tmp/.ICE-unix/2307`
**INVOCATION_ID**: `e0c9d4f1c0d54c90911ca1c9e487d8ac`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_MENU_PREFIX**: `gnome-`
**GNOME_SETUP_DISPLAY**: `:1`
**DISPLAY**: `:0`
**LANG**: `en_CA.UTF-8`
**XDG_CURRENT_DESKTOP**: `GNOME`
**XDG_SESSION_DESKTOP**: `gnome`
**XAUTHORITY**: `/run/user/1000/.mutter-Xwaylandauth.TNJM00`
**SSH_AGENT_LAUNCHER**: `openssh`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**SHELL**: `/bin/bash`
**QT_ACCESSIBILITY**: `1`
**GDMSESSION**: `gnome`
**GJS_DEBUG_OUTPUT**: `stderr`
**PWD**: `/home/teoti`
**XDG_DATA_DIRS**: `/home/teoti/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/`
</details>

**Comment by pbek** [comment]
Pushing to git would be nice, but git merge conflict resolution would be a nightmare.
If you don't have conflicts you could just write a script (in QON) that does a git push all x seconds (I think @sanderboom attempted such a thing once)
One other attempt to use git as sync tool was made by https://github.com/muesli/gitomatic/.
(See https://www.qownnotes.org/getting-started/concept.html#nextcloud-desktop-sync-client)

But I'd rather just rsync the notes directory (including `.git`) to somewhere (and in by case backup that "somewhere").

**Comment by pbek** [comment]
>  I'm a happy QOwnNotes user for several years now.

Makes me glad! 😁

**Comment by teotikalki** [comment]
I was only actually intending to push to git from one computer. I've considered that I could use git repositories on both (many) computers and have git do the syncing with the git directories UNsynced by Nextcloud. If the only usage is me writing notes on one device at a time the merges shouldn't be problematic (I thought?)... I actually was coming to the conclusion that the ONLY thing that should sync a git repository is git, actually.

I'll look into the other options that you mentined right now, though. Thanks for them. :)
