### ISSUE TITLE
How to make a spoiler `<details>`?

### ISSUE THREAD

**Issue by it19862** [pbek/QOwnNotes#2077]
How do I make a spoiler `<details>`?

**Analogue**
<details><summary>Expand</summary>
Custom content
</details>

**Comment by pbek** [comment]
In QON? The preview doesn't support that, if that was the question.

**Comment by quicktrick** [comment]
I implemented all the functionality of QON in VSCode. Everything works as it should: search through all files, regexes, details, etc. In Windows I made a separate VSCode environment, running it through Sandboxie. This way, it doesn't interfere with my normal VSCode work.

![Capture](https://user-images.githubusercontent.com/18548503/147848302-6302f06b-c5f7-4c9f-a89e-0b013574e726.PNG)

**Comment by pbek** [comment]
Too bad that QLiteHtml from https://github.com/pbek/QOwnNotes/pull/2345 doesn't support the `<details>` tag neither.
