### ISSUE TITLE
Question about note + image + attachment limits inside QOwnNotes

### ISSUE THREAD

**Issue by jg55** [pbek/QOwnNotes#2079]
Thanks again for working on the rename media/attachment feature request! (https://github.com/pbek/QOwnNotes/issues/2073) -- Now that the new **manage stored images files** dialog is up and running, it dawned on me that I could have thousands and thousands of images in there, not to mention thousands of notes, attachments, etc.

So I'm wondering if there are any limits in the system for numbers of notes/images/attachments and all the panels and dialogs that deal with those arrays, etc...? 

Since I'm still new to QOwnNotes, I've been testing on only about ~200, but I will get up to >1000 in a handful of months, and many thousands in the years to come.

Thanks again! QOwnNotes is fantastic!

**Comment by pbek** [comment]
QON holds all notes of a note folder in an in-memory sqlite database. Unless you have very, very little RAM that will not be a problem. If it ever does you can still use multiple note folders.
Notes will be loaded from disk to memory every time the note-folder is reloaded (e.g. when a file outside of the watched files is changed, but you can turn off automatic reloading too if you have a lot of notes and a small disk / slow cpu).

**Comment by jg55** [comment]
Sounds good, thank you!

> QON holds all notes of a note folder in an in-memory sqlite database

Does this mean that QON also holds all the media in memory too? Or just the text part of the notes and then it only loads the images when it refreshes the preview window?

**Comment by pbek** [comment]
> Does this mean that QON also holds all the media in memory too?

no

> Or just the text part of the notes and then it only loads the images of a specific note when it refreshes the preview window?

exactly

**Comment by jg55** [comment]
👍 Thank you!

**Comment by pbek** [comment]
I'll close this then...
