### ISSUE TITLE
Hide non relevant items 

### ISSUE THREAD

**Issue by Fischmuetze** [pbek/QOwnNotes#208]
In principle a "problem" for each OS, but my remarks pointed to the OS X version as I could not install successful it on my Ubuntu 14.04 (but this should not be a part of this issue item) and have no comparison to other OS versions

Non relevant items in setting should not offered if they are not effective nor relevant for the OS or the "settings situation"

- Preferences -> Interface -> General -> Checkbox App Instance
  By default under OS X each app runs in only one instance 
  So this setting is senseless

- Preferences -> Interface -> Dark mode
  Optimize colors for dark mode desktop themes
  Have no effect on OS X - so it should be set hidden for all OS's which are not supported for this setting

- not sure but imho 
  the tab Preferences -> Todo 
  should not shown if there is no valid ownCloud configuration

**Comment by pbek** [comment]
Thank you for your suggestions.

> Preferences -> Interface -> General -> Checkbox App Instance

There are ways to open more instances but not by default, so I guess you are right.

> Preferences -> Interface -> Dark mode

It does the same on every OS. Improving some colors if the OS is supporting a dark mode, I don't know if there are theme managers for OS X or if there is a dark theme for OS X.

> the tab Preferences -> Todo 

I will think about that...

**Comment by Fischmuetze** [comment]
There is no "theme" manager in OS X. Like I wrote in another issue item her: there is "only" a switch for a dark menu and dock ... on the other hand: some other apps comes with "themes" or UI mode switches independently of the OS settings - i.e. Atom editor, Komodo Edit, Firefox, Chrome etc... so there is no rule which prevents to offer an optional dark mode for QOwnNotes on OS X ...

**Comment by pbek** [comment]
those "true" dark modes leave room for endless discussions of what's best and I really don't want that... in a OS where there is theming support the user can decide what suits him or her most...
If you want to add theming support to QOwnNotes directly you are of course free to create a pull request and I will have a look at the code 😉

**Comment by pbek** [comment]
By the way, a quick search on duckduckgo revealed plenty of OS X theming software, so I guess there is a use for that checkbox after all...

**Comment by Fischmuetze** [comment]
> duckduckgo revealed plenty of OS X theming software, s

Believe me - there is no officially way to theme OS X (like GTK, KDE or Mozilla themes) 
So solutions like Flavours are not official supported by the operating system (like themes in Windows  XP, 7 nor KDE, GTK) and of course not really popular ... 

> so I guess there is a use for that checkbox after all...

If you keep it for OS X it should have an effect to the behavior of the app - but it haven't 

> If you want to add theming support to QOwnNotes directly you are of course free to create a pull request and I will have a look at the code

No this isn't a request - but I cant follow the logic of this option switch offer.
So currently I can choose a theme totally independently of the settings of the operating system just if the operating system supports different themes. But if the operating system doesn't support more than one theme than I'll haven't that choice - for me a strange logic.

I could understand - and this is also for gtk and kede environments the default way - to follow the settings like the operating system is using. So but if an app offers to using an setting which differs from the operating system setting why it's important that the operating system offers a theme support?

**Comment by Fischmuetze** [comment]
http://sites.fastspring.com/interacto/product/flavours2
Flavours 2 Lite supports OS X Yosemite ONLY. 
OS X El Capitan is NOT supported.

**Comment by pbek** [comment]
I don't know about the OS X theme software, but Qt is definitely themeable...

I guess I will play around with <https://github.com/ColinDuquesnoy/QDarkStyleSheet>

> If you keep it for OS X it should have an effect to the behavior of the app - but it haven't

for example some highlighting colors are different to match a dark background

**Comment by Fischmuetze** [comment]
> https://github.com/ColinDuquesnoy/QDarkStyleSheet

See the last screenshot ... 

Anyway, currently there is changing nothing on OS X - doesn't matter if this option is active or not

**Comment by pbek** [comment]
> See the last screenshot ...

what about it?

> Anyway, currently there is changing nothing on OS X - doesn't matter if this option is active or not

currently you have to (for some reason I don't know yet) restart the app to see the changes...

**Comment by Fischmuetze** [comment]
Patrizio I guess that's the reason for our misunderstanding. There is  currently changing nothing on OS X with or without restart, with or without on / off this switch - always the bright colors and never shown a dark UI .

**Comment by pbek** [comment]
> for example some highlighting colors are different to match a dark background

I tested it in the morning on a MacBook and it worked as it should.

> never shown a dark UI

I never said that it should do that

**Comment by Fischmuetze** [comment]
puuuuuuh ... Ok now I understand - this is only a setting for a different highlighting mode. I thought this setting is availble to switch to this mode http://www.qownnotes.org/var/bekerle/storage/images/_aliases/frontpage_slider_full/qownnotes/frontpage-slider/dark-mode-theme-support/3756-3-eng-GB/xDark-mode-theme-support.png.pagespeed.ic.DW7Qszrnz1.png
as the description wrote "Dark mode theme support"

Anyway : In this case the setting is mistakable labelled, as the control group called "Dark mode" ... I guess "Dark highlighting" or similar could prevent such misunderstandings ...

**Comment by pbek** [comment]
It is what it is, "support for dark themes". 
In the settings it says: Optimize colors for dark mode desktop themes

**Comment by Fischmuetze** [comment]
Your decision! For me the group label and the label self as too isn't the best choice

**Comment by pbek** [comment]
I plan to add an other checkbox if my "playing around" with a real dark mode bears fruits...

**Comment by pbek** [comment]
> QDarkStyleSheet

I tested it, unfortunately there would still quite some styling work to do... (including a full set of dark mode icons)

**Comment by pbek** [comment]
from v16.06.6
- you now can use a real **dark mode** on every operating system
    - turn it on in the interface settings

There now is a new release, could you please test it and report if the new features work for you?

**Comment by pbek** [comment]
from the v16.06.7 changelog
- the todo tab in the settings is now disabled if there are no ownCloud settings
- the app instance settings are now hidden on OS X since we don't need them 
  there

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Fischmuetze** [comment]
OS X 10.11.5
Todo Tab is still visible even if no ownCloud settings are configured

![bildschirmfoto 2016-06-18 um 22 37 20](https://cloud.githubusercontent.com/assets/19834496/16173563/3e1edb14-35a5-11e6-8f1d-ea32a7d1480b.jpg)

**Comment by Fischmuetze** [comment]
Also the menu bar item shows this wrong behavior
![bildschirmfoto 2016-06-18 um 22 57 36](https://cloud.githubusercontent.com/assets/19834496/16173632/155f8b58-35a8-11e6-974e-848b02912ad2.jpg)

**Comment by pbek** [comment]
The tab is disabled as it should be (with a tool-tip that indicates why) and not invisible.
