### ISSUE TITLE
[Q] is there a "switch to previous note tab" shortcut?

### ISSUE THREAD

**Issue by siran** [pbek/QOwnNotes#2080]
#### General question

is there a "switch to previous note tab" shortcut? (like alt-tab in Windows but with notes inside QON)

**Comment by pbek** [comment]
Yes, best search for the action in the *Help menu*.

**Comment by sanderboom** [comment]
The shortcuts that are available switch to the next and previous tab based on order. Would it be possible to switch tabs based on MRU (most recently used) as for example is the default in Firefox?

**Comment by sanderboom** [comment]
> that would be the "note history" (which already exists), wouldn't it?

Is that true? It seems that this will open a just closed tab for example. Which is also nice, but in an other scenario ;)

**Comment by pbek** [comment]
There pretty certainly will be no "tab history", since there already is the note history (which already is very sensitive).

**Comment by sanderboom** [comment]
> There pretty certainly will be no "tab history", since there already is the note history (which already is very sensitive).

Ah too bad. Maybe in the future :wink:
