### ISSUE TITLE
[Q] why is the log panel opening automatically everytime QON starts?

### ISSUE THREAD

**Issue by siran** [pbek/QOwnNotes#2081]
#### General question

why is the log panel opening automatically everytime QON starts? 
is there a setting I'm not aware of?

**Comment by pbek** [comment]
You can turn of panels in the Menu: Window / Panels

**Comment by siran** [comment]
This issue was happening to me ("log panel opening automatically everytime
QON starts"). I opened a 'question' and soon afterwards it magically
stopped happening so I guessed it was fixed. But apparently it's still
happening to other people.
