### ISSUE TITLE
[I] Standard Program for "file:///"

### ISSUE THREAD

**Issue by erwin-frohsinn** [pbek/QOwnNotes#2082]
#### Expected behaviour

Clicking on a link to a local dir like "file:///home/user/testdir/" should result in opening dolphin (which is defined as the standard component on my linux system)

#### Actual behaviour

This click opens baobab https://de.wikipedia.org/wiki/Baobab_(Software) instead.

#### Steps to reproduce

Create such a link within a note and click it.

#### Comment 

Your debugging aid collects more information than necessary, e.g.: 

savedSearches/noteFolder-1 (QStringList): `This is not for the public!!!`

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sa. März 27 08:48:39 2021`
**Version**: `21.3.6`
**Build date**: `Mar 26 2021`
**Build number**: `822`
**Platform**: `linux`
**Operating System**: `Ubuntu Core 18`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Snapcraft`
**Qt Version (build)**: `5.9.5`
**Qt Version (runtime)**: `5.9.5`
**Portable mode**: `no`
**Settings path / key**: `/home/xxx/snap/qownnotes/8158/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/xxx/snap/qownnotes/8158/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/snap/qownnotes/8158/usr/bin/QOwnNotes`, `--snap`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Primary screen resolution**: `2560x1080`
**Icon theme**: `breeze`
**Notes in current note folder**: `339`
**Calendar items**: `111`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://xxx.free-dyndns.de`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `20.0.8.1`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/home/user/snap/qownnotes/8158/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/xxx/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/xxx/Nextcloud/Notes/notes.sqlite`

### Cloud connection `Standard`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://xxx.free-dyndns.de`
**username**: `someone`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `/home/xxx`
**FileDialog/LastPath-NotePDFExport** (QString): `/home/xxx`
**ImageDialog/disableCopying** (QString): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-03-27T08:33:05`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Noto Sans,-1,10,255,5,2,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteHistory-1** (QVariantList): `<variant list with 129 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `128`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `8`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**TagAddDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Deck: Persönlich`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `xxx`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `24`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/xxx/Nextcloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): `xxx`
**ownCloud/todoCalendarEnabledList** (QStringList): `xxx`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://xxx.free-dyndns.de/remote.php/dav/calendars/admin/aufgaben/, 
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `20.0.8.1`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `This is not for the public!!!`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Hauptsymbolleiste`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `Formatierungs-Werkzeugleiste`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `Einfügen-Werkzeugleiste`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `Verschlüsselung-Werkzeugleiste`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `Fenster-Werkzeugleiste`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `Beenden - Symbolleiste`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**webSocketServerService/token** (QString): `xxx`
**workspace-aT9pwbeCPfWh/name** (QString): `Vollständig`
**workspace-aT9pwbeCPfWh/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-aT9pwbeCPfWh/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, aT9pwbeCPfWh`

## System environment

**__EGL_VENDOR_LIBRARY_DIRS**: `/snap/qownnotes/8158/etc/glvnd/egl_vendor.d:/snap/qownnotes/8158/usr/share/glvnd/egl_vendor.d`
**KDE_FULL_SESSION**: `true`
**LIBGL_DRIVERS_PATH**: `/snap/qownnotes/8158/usr/lib/x86_64-linux-gnu/dri`
**LD_LIBRARY_PATH**: `/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/qownnotes/8158/lib/x86_64-linux-gnu:/snap/qownnotes/8158/usr/lib/x86_64-linux-gnu:/snap/qownnotes/8158/lib:/snap/qownnotes/8158/usr/lib:/snap/qownnotes/8158/lib/x86_64-linux-gnu:/snap/qownnotes/8158/usr/lib/x86_64-linux-gnu:/snap/qownnotes/8158/usr/lib/x86_64-linux-gnu/dri`
**FONTCONFIG_PATH**: `/snap/qownnotes/8158/etc/fonts`
**LC_MEASUREMENT**: `de_DE.UTF-8`
**XDG_CONFIG_HOME**: `/home/xxx/snap/qownnotes/8158/.config`
**LC_PAPER**: `de_DE.UTF-8`
**LC_MONETARY**: `de_DE.UTF-8`
**LIBVA_DRIVERS_PATH**: `/snap/qownnotes/8158/usr/lib/x86_64-linux-gnu/dri`
**QTWEBENGINEPROCESS_PATH**: `/snap/qownnotes/8158/usr/lib/x86_64-linux-gnu/qt5/libexec/QtWebEngineProcess`
**PULSE_SERVER**: `unix:/run/user/1000/snap.qownnotes/../pulse/native`
**GST_PLUGIN_SYSTEM_PATH**: `/snap/qownnotes/8158/usr/lib/x86_64-linux-gnu/gstreamer-1.0`
**SNAP_USER_DATA**: `/home/xxx/snap/qownnotes/8158`
**LANG**: `de_DE.UTF-8`
**QT_PRINTER_MODULE**: `qtubuntu-print`
**DISPLAY**: `:0`
**QTCHOOSER_NO_GLOBAL_DIR**: `1`
**XKB_CONFIG_ROOT**: `/snap/qownnotes/8158/usr/share/X11/xkb`
**SNAP_REVISION**: `8158`
**DISABLE_WAYLAND**: `1`
**GST_PLUGIN_PATH**: `/snap/qownnotes/8158/usr/lib/x86_64-linux-gnu/gstreamer-1.0`
**SNAP_ARCH**: `amd64`
**SNAP_INSTANCE_KEY**: *empty*
**QT_SCREEN_SCALE_FACTORS**: `DisplayPort-0=1;DisplayPort-1=1;DisplayPort-2=1;HDMI-A-0=1;DVI-D-0=1;`
**XDG_VTNR**: `1`
**QT_SELECT**: `snappy-qt5`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**SSH_AUTH_SOCK**: `/tmp/ssh-EKRGxs580HOQ/agent.2224`
**SNAP_REAL_HOME**: `/home/xxx`
**LC_NAME**: `de_DE.UTF-8`
**XDG_SESSION_ID**: `3`
**SNAP_USER_COMMON**: `/home/xxx/snap/qownnotes/common`
**USER**: `xxx`
**DESKTOP_SESSION**: `plasma`
**VDPAU_DRIVER_PATH**: `/usr/lib/x86_64-linux-gnu/vdpau/`
**QT_QPA_PLATFORMTHEME**: `gtk3`
**PWD**: `/home/xxx`
**HOME**: `/home/xxx/snap/qownnotes/8158`
**QTCOMPOSE**: `/snap/qownnotes/8158/usr/share/X11/locale`
**SNAP_LAUNCHER_ARCH_TRIPLET**: `x86_64-linux-gnu`
**SNAP**: `/snap/qownnotes/8158`
**SSH_AGENT_PID**: `2268`
**QT_ACCESSIBILITY**: `1`
**SNAP_COMMON**: `/var/snap/qownnotes/common`
**XDG_SESSION_TYPE**: `x11`
**SNAP_NAME**: `qownnotes`
**GTK_PATH**: `/snap/qownnotes/8158/usr/lib/x86_64-linux-gnu/gtk-2.0`
**XDG_DATA_DIRS**: `/home/xxx/snap/qownnotes/8158/.local/share:/home/xxx/snap/qownnotes/8158:/snap/qownnotes/8158/data-dir:/snap/qownnotes/8158/usr/share:/usr/share/plasma:/usr/local/share:/usr/share:/var/lib/snapd/desktop`
**SNAP_INSTANCE_NAME**: `qownnotes`
**SNAP_DATA**: `/var/snap/qownnotes/8158`
**XDG_SESSION_DESKTOP**: `KDE`
**LC_ADDRESS**: `de_DE.UTF-8`
**QML2_IMPORT_PATH**: `/snap/qownnotes/8158/lib/x86_64-linux-gnu:/snap/qownnotes/8158/usr/lib/x86_64-linux-gnu/qt5/qml`
**TMPDIR**: `/tmp`
**LC_NUMERIC**: `de_DE.UTF-8`
**GDK_PIXBUF_MODULE_FILE**: `/home/xxx/snap/qownnotes/common/.cache/gdk-pixbuf-loaders.cache`
**LOCPATH**: `/snap/qownnotes/8158/usr/lib/locale`
**SNAP_COOKIE**: `Wv6ayfdrYnJQYKFT330Xf8NHVbuKJNddfYSaKC_vEFY4i-8KG-uM`
**QT_PLUGIN_PATH**: `/snap/qownnotes/8158/usr/lib/x86_64-linux-gnu/qt5/plugins`
**SHELL**: `/bin/bash`
**XDG_SESSION_CLASS**: `user`
**FONTCONFIG_FILE**: `/snap/qownnotes/8158/etc/fonts/fonts.conf`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**TEMPDIR**: `/tmp`
**XCURSOR_THEME**: `breeze_cursors`
**XDG_CURRENT_DESKTOP**: `KDE`
**XLOCALEDIR**: `/snap/qownnotes/8158/usr/share/X11/locale`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**BAMF_DESKTOP_FILE_HINT**: `/var/lib/snapd/desktop/applications/qownnotes_PBE.QOwnNotes.desktop`
**SNAP_REEXEC**: *empty*
**SHLVL**: `0`
**XDG_SEAT**: `seat0`
**LANGUAGE**: `de:en_US`
**GST_PLUGIN_SCANNER**: `/snap/qownnotes/8158/usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner`
**GDK_PIXBUF_MODULEDIR**: `/snap/qownnotes/8158/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders`
**LC_TELEPHONE**: `de_DE.UTF-8`
**QT_QPA_PLATFORM**: `xcb`
**XDG_CACHE_HOME**: `/home/xxx/snap/qownnotes/common/.cache`
**LOGNAME**: `xxx`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**XDG_RUNTIME_DIR**: `/run/user/1000/snap.qownnotes`
**XAUTHORITY**: `/home/xxx/.Xauthority`
**XDG_DATA_HOME**: `/home/xxx/snap/qownnotes/8158/.local/share`
**SNAP_CONTEXT**: `Wv6ayfdrYnJQYKFT330Xf8NHVbuKJNddfYSaKC_vEFY4i-8KG-uM`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**XDG_CONFIG_DIRS**: `/snap/qownnotes/8158/etc/xdg:/etc/xdg/xdg-plasma:/etc/xdg:/usr/share/kubuntu-default-settings/kf5-settings`
**PATH**: `/snap/qownnotes/8158/usr/sbin:/snap/qownnotes/8158/usr/bin:/snap/qownnotes/8158/sbin:/snap/qownnotes/8158/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`
**LC_IDENTIFICATION**: `de_DE.UTF-8`
**KDE_SESSION_UID**: `1000`
**KDE_SESSION_VERSION**: `5`
**SNAP_VERSION**: `21.3.6`
**GIO_MODULE_DIR**: `/home/xxx/snap/qownnotes/common/.cache/gio-modules`
**SNAP_LIBRARY_PATH**: `/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void`
**SESSION_MANAGER**: `local/xxx-xxx:@/tmp/.ICE-unix/2362,unix/xxx-X570:/tmp/.ICE-unix/2362`
**XCURSOR_PATH**: `/snap/qownnotes/8158/data-dir/icons:/snap/qownnotes/8158/usr/share/icons`
**LC_TIME**: `de_DE.UTF-8`
</details>

**Comment by pbek** [comment]
The settings of your operating system decide what to open for file urls. And that's different for every file-type.

For me the link `<file:///home/user>` is opened in Dolphin on my Manjaro Box.
