### ISSUE TITLE
Visual guide on editor for columns/characters

### ISSUE THREAD

**Issue by marcoXbresciani** [pbek/QOwnNotes#2083]
#### Expected behaviour
I'd love to see a (possibly configurable) vertical visual guide to know when to go to a new line, depending on local needs and conventions.
Something like the attached picture
![image](https://user-images.githubusercontent.com/48018419/112797532-d129a580-906b-11eb-858f-a748735eba84.png)

#### Actual behaviour
There is neither a configurable wrap nor a guideline for columns (text width)

#### Steps to reproduce
Open the editor.

**Comment by pbek** [comment]
@Waqar144, I guess that would be quite hard to do in a `QPlainTextEdit`, right?

**Comment by Waqar144** [comment]
I can try the visual guide, that might not be too hard. Static / Hard wrap is a pain however.

Also, there is a "editor width" setting I think, which may or may not be relevant here.

**Comment by marcoXbresciani** [comment]
> I can try the visual guide, that might not be too hard. Static / Hard wrap is a pain however.
> 
> Also, there is a "editor width" setting I think, which may or may not be relevant here.

The visual guide would be more than lovely: I actually prefer manual wrapping, so don't worry about static/hard wrap at all.
I was taking a look at the editor width: I suppose it works with soft wrap, right? I've set my preferred width, but can't understand the purpose of that option, actually...

**Comment by pbek** [comment]
>  but can't understand the purpose of that option, actually...

It was initially created for the distraction free mode. But then people started to also want it all the time, so there is an option to allow limiting the width all the time.

**Comment by marcoXbresciani** [comment]
> > but can't understand the purpose of that option, actually...
> 
> It was initially created for the distraction free mode. But then people started to also want it all the time, so there is an option to allow limiting the width all the time.

Gosh, found it... Thanks!

**Comment by Waqar144** [comment]
The visual guide is pretty straightforward to implement, in fact it is already working here. But there is a big issue, it really only works with fixed width fonts. With the rest, width calculation is just not accurate at all. You can probably already notice this with the "distraction free mode" settting as well if you use non fixed width font.

There is another way to implement this which doesn't require calculating any widths, i.e., color the text differently if it crosses a certain threshold.

**Comment by marcoXbresciani** [comment]
I won't say both ways or I'll be unpolite. :)
Personally, I'm a SW developer (sorry, haven't played enough with C++ or I even might help with QOwnNotes), so I'm using fixed width fonts actually everywhere and the vertical line seems possibly the nicest.
Also, default font is Courier New, right? Fixed width as well.
Maybe it's enough to have a on/off toggle in the settings to show/hide the line, with a note that specifies that it's best suited with fixed width fonts.

But probably the colouring is way simpler and works with every font. Up to you.

At the moment I'm writing with an eye on the cursor position to check whether I reach my width limit... Everything is an improvement. :)

**Comment by pbek** [comment]
>  Also, default font is Courier New, right?

No. Whatever the operating system sets per default. And then what the user selects.

> Fixed width as well.

No 😁

**Comment by marcoXbresciani** [comment]
Courier New... is not fixed width?! 😮

**Comment by pbek** [comment]
Courier New is not the default font.

**Comment by marcoXbresciani** [comment]
News on this? Can I help somehow? I'm fine with the line or even with colouring the text or the background...

**Comment by pbek** [comment]
No news on my side.

**Comment by Waqar144** [comment]
It's easy to just color it, would probably take 5 minutes to implement that but that's imo the wrong way to do it. We can not just keep adding things to the highlighter that don't belong there.

The right way would be to allow the scripts to do the highlighting. Then a user can do whatever they want.

**Comment by pbek** [comment]
> The right way would be to allow the scripts to do the highlighting. Then a user can do whatever they want.

I think making highlighting more customizable would be great.
@Waqar144, do you think that would slow highlighting down for those 99.5% of people who are not using the custom highlighting?

**Comment by pbek** [comment]
@marcoXbresciani, you will be able to do that with #2513.

**Comment by pbek** [comment]
## 22.4.1
- you can now add highlighting rules for the editor with the help of the new
  scripting function `script.addHighlightingRule` (for [#2513](https://github.com/pbek/QOwnNotes/issues/2513))
    - for more information please take a look at the [scripting documentation](https://www.qownnotes.org/scripting/methods-and-objects.html#adding-a-highlighting-rule-for-the-editor)

https://github.com/pbek/QOwnNotes/blob/89a13727953584bb241845c32d35db64ba7027b9/docs/scripting/examples/highlighting.qml#L9-L12

...could do the trick for you

<img width="593" alt="image" src="https://user-images.githubusercontent.com/1798101/163672690-26dd272d-f7cb-4b51-acb9-2b80be0eeb8e.png">

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by marcoXbresciani** [comment]
Good for me!
Thanks!!!

**Comment by pbek** [comment]
Great 😉
