### ISSUE TITLE
Wrong HTML comments management at beginning of file

### ISSUE THREAD

**Issue by marcoXbresciani** [pbek/QOwnNotes#2084]
#### Expected behaviour
HTML comments should be skipped as described in the [Markdown cheatsheet](https://www.qownnotes.org/getting-started/markdown.html#comments).

#### Actual behaviour
The note name is the first line of the file: `!--`.

#### Steps to reproduce
Use this file as note

```markdown
<!--
© 2021 Marco Bresciani

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved.
This file is offered as-is, without any warranty.

SPDX-FileCopyrightText: 2021 Marco Bresciani

SPDX-License-Identifier: FSFAP
-->
# Errors
```

And the create another similar note, in the same folder,  with another  title:
```markdown
<!--
© 2021 Marco Bresciani

Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved.
This file is offered as-is, without any warranty.

SPDX-FileCopyrightText: 2021 Marco Bresciani

SPDX-License-Identifier: FSFAP
-->
# Architecture
```

then in the note folder appears only one note called `!--`.

Removing the whole HTML comment the notes are properly named `Errors` and `Architecture`.

**Comment by pbek** [comment]
I haven't seen leading comments in markdown files yet. Currently only a frontmatter will be ignored in the automatic file name generation.

So at the moment you can either:

- Turn off that the first line will be the file name
- Use the scripting engine to write your own handling of file name generation

**Comment by pbek** [comment]
> HTML comments should be skipped as described in the Markdown cheatsheet.

Where does it say that?

**Comment by marcoXbresciani** [comment]
It's because of this: https://reuse.software/spec/#comment-headers

I'll try to find another way to make my notes GPL-/REUSE-compliant.

**Comment by pbek** [comment]
I can implement that with the next release.

**Comment by pbek** [comment]
## 21.3.8
- a leading html comment block in a note will now be ignored in the automatic note filename generation

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by marcoXbresciani** [comment]
Sure. Tomorrow morning I'll update and check. Thanks!!

**Comment by marcoXbresciani** [comment]
As many developers (like me) love to say...
![image](https://user-images.githubusercontent.com/48018419/112940097-ef0b0f00-912c-11eb-89ec-6e8ac3d57cc5.png)

Thank you.

**Comment by pbek** [comment]
Great, thank you for testing! 😁
