### ISSUE TITLE
Wondering about performance differences between storing QON notes on computer SSD vs NAS for very large collection of notes

### ISSUE THREAD

**Issue by jg55** [pbek/QOwnNotes#2088]
Hi QON devs and QON community -- anyone out there who has compared SSD vs NAS performance for QON for large collections of notes? 

I'm trying to figure out the best way to set up a long-term project that will eventually have 10000+ notes. It will be used on three computers (one Windows desktop, one Linux desktop, and one Linux laptop). I need to keep them all synced, but I don't want to use the cloud at all. I will use my NAS and perhaps various sync programs (such as rsync, etc.) to keep the three synced together. In my brief testing with a small collection of notes, performance differences are negligible. But I need to figure out what will happen with a *large* collection of notes.

Option 1: Store and edit the QON notes on the local SSDs of the computers, but then rsync to the NAS back and forth as needed and to the three computers to keep them all synced. So there will always be 4 copies of the notes (3 computers + 1 NAS), and theoretically, the NAS will have the "master" up-to-date version if I set up all the syncing correctly. I'll have to be careful about conflicts though. But assuming I'm consistent, this would theoretically give me the best performance, since all the files are accessed locally on the SSDs by QON.

Option 2: Store and edit the QON notes directly on the NAS... this would be the most convenient, but it might be a lot slower once I get into the many thousands of notes. I lose the advantage of local SSD storage, but it's less messy than constantly having to rsync back and forth with Option 1, plus Option 2 eliminates some human error that might cause conflicts if I don't sync properly. However, when I take the laptop with me, it won't actually have a copy of the notes since I would only access the NAS on the local network (no cloud). So I'd have to remember to make a temp copy of the notes on the laptop if I need them when I'm away from the NAS.

In both cases, the NAS has very good backup options running all the time, including versioning, so the files in either option will be safe.

So which option is the smartest way to do it long-term? If a large collection of notes performs okay off of a NAS, then maybe I'll stick with Option 2. But if there's a drastic performance difference, maybe Option 1 is best. Any thoughts? And thanks for your help!

**Comment by pbek** [comment]
The only relevant thing is how long it takes to load all notes into ram, since QON using an in-memory sqlite database for the notes.

I don't like option 2 because you depend on whether your NAS is up or not and you can't access your precious information on how to get it up again. 😉  I personally use option 1, I have my notes on my local SSD and do a rsync (of my whole home folder) to my NAS (plus a sync of the note folders via Nextcloud). On my NAS I do a backup of my backup to various places. This way I have more than 20 backups of my notes. 😅 

Any thoughts, @Waqar144?

**Comment by pbek** [comment]
You could also put a sync server on your NAS (or even better Nextcloud plus Nextcloud Notes).

**Comment by pbek** [comment]
A good setup if you want to use everything there is around QON would be described here: https://www.qownnotes.org/getting-started/concept.html

**Comment by pbek** [comment]
Don't use rsync for a two- or three-way sync! rsync is one way only! Use tools like Nextcloud sync, Syncthing, Seafile and install their server on your NAS (or a local RaspberryPi).

**Comment by jg55** [comment]
Thank you, @pbek! Appreciate all the thoughts! I'm not worried about NAS availability, it's 100% so far (of course as soon as I say that I bet it will go down just to show me who's boss). It's multi-backed up, versioned, btrfs, redundant, UPS, ECC RAM, enterprise drives, etc... so I'm happy with that part of the equation for now. Eventually I will be adding a live failover NAS too. 

For QON, I'm mainly concerned with performance considerations for tons of notes (and media, lots of media, but I know media is not directly relevant for QON since it doesn't load media). Come to think of it, that's another advantage of Option 2 (NAS approach) in my case, since I don't have to sync all that media too...

I also don't want to add on another layer like Nextcloud, but I understand the design and concept, and I can see all the advantages of the full workflow. Maybe at some point in the future, it's intriguing. But just more stuff I don't personally need right now though. I'm more of a minimalist. After all, I'm a fan of Niklas Luhmann's zettelkasten approach, and he was very effective with physical note cards and slip boxes. So QON -- as a digital zettelkasten -- is already 1000X faster than Luhmann's method. I just don't want QON to bog down with 10000+ notes, no matter what I do, but it sounds like it should be fine for me on a NAS, or either way.

One of the primary reasons I went with QON is because it is 100% universal, 100% compatible with everything, 100% no lock-in, 100% simple structure, a fully agnostic text/note IDE. (And again, kudos to you for making it that way!) So I want to keep things simple simple simple, including not having to set up or maintain an extra layer on any server, etc. I have lots of options with the way you designed QON, so thank you for making it so flexible.

As for rsync, for sync, I have profiles set up in Grsync that do what I need for now, but I was also looking into syncthing, some other options, etc.. On Windows, I use an app called SyncBackPro, which does a million things really well (but sadly is not open source, so I might replace it in the future). (And I don't use any cloud services for syncing.)

Thanks again -- I think for now I'm leaning to Option 2, but I'm going to play around with Option 1 a little more. There are lots of pros and cons to each approach. But happy to hear that performance shouldn't be too much of an issue with Option 2. And plus, I can always change approaches...

**Comment by pbek** [comment]
Best you write a script that creates a lot of text files to test the speed with your NAS and network.
Something like: https://stackoverflow.com/questions/2084832/how-can-i-create-1000-files-that-i-can-use-to-test-a-script

And you can always create different note folders if you don't want to many notes in one folder.

**Comment by jg55** [comment]
> Best you write a script that creates a lot of text files to test the speed with your NAS and network.

Great idea, thanks! Will test this out asap this week!
 
> And you can always create different note folders if you don't want to many notes in one folder.

In my case, since I'm using a zettelkasten approach, I need to have access to all the notes in the same context/notebook so I can easily link/reference between any of them. So I need to be able to handle (eventually) 10000+ notes. I'll test out performance this week and see what happens. Thanks again.

**Comment by Waqar144** [comment]
As mentioned by @pbek earlier, QON loads everything into memory upon startup, so performance, in general is not really an issue. Your startup time can be affected though. However, I have never tried anything about 1000+ notes, so I am not sure how things will be with 10000 notes. SQLite is pretty fast, so I think there will be no issues on that front but we do have a UI and a lot of controls that need to keep up with the data and if the data is in a bad format, it can slow us down. An example of this could be 10000 files in a single folder, this may slow the UI or give lags.

I am looking forward to what you find. If it's slow maybe we can do something to make it faster :)

**Comment by jg55** [comment]
> I am looking forward to what you find. If it's slow maybe we can do something to make it faster :)

Okay, I'll report back here then once I do the test. I'll probably create version 1 of the test with 5000 notes, and I'll see if I can add some links in the notes too so it's more realistic. I should probably add 5000 images too, but for now just the notes. Then I'll test both on local SSD and NAS.

**Comment by jg55** [comment]
FYI -- I decided I wanted to run a few tests today, so I created a folder with 5000 text files, split from various source text files. Each of the 5000 files has about 5KB text, so about 25MB total text.

The import process took a long time, but it managed to do it in about 140 minutes on an i9-9900K CPU. I noticed the import process start to slow down around importing 3000 notes, and by 4000 notes it was even slower.

Basically, QON can get a little laggy with 5000 notes depending on what you are doing, but in general it looks like it can handle it so far. Startup takes longer (about 7-8 seconds) on SSD (have not tested NAS yet), as well as a lag searching (since it starts the query at the first keypress) and renaming a file can cause a big lag too. But overall it's very usable once a note is loaded.

I'll test more later this week if I have more time, but I think it will work. I still need to test NAS. This is the most I can do for now. 

I do think there are some optimizations that would be nice with the search though... it immediately starts searching just on a keypress in the search field, which then causes a lag with 5000 notes, so it would be nice if it would abort the prior query and restart the query on the next keypress instead of waiting until the search completed. It's pretty obvious of a lag with this many notes. Still, it's usable with patience.

Good job guys. Glad I did this test. More when I get a chance.

P.S. BTW, I think it would be very useful to sort the search results differently... or have some options. I guess I will submit a feature request another time. When you have 5000 notes to search from, the search results would be more effective if it was sorted by number of hits since there can be so many notes that pop up, and maybe even weight the title a bit too. Anyway, more another day. Take care! Thanks again!

**Comment by pbek** [comment]
You may want to turn off the numbers of search results per note then searching will be a lot faster. 😉

**Comment by jg55** [comment]
> You may want to turn off the numbers of search results per note then searching will be a lot faster. 😉

Just tried that and indeed it speeds things up. However, it defeats the awesomeness of the search hit count. But at least there is an option to speed it up. Thanks!
