### ISSUE TITLE
[I] Move note to subfolder of the same folder

### ISSUE THREAD

**Issue by SamuXzX** [pbek/QOwnNotes#2089]
#### Expected behaviour

When right-clicking on a note and selecting "Move note to..." the list of folders and relative subfolders that appears should contain all the folders in my Qownnotes setting. Hovering on the folder that contains the note we are talking about, I'd see the subfolders of the same folder and I'd be able to move the note from a subfolder to another subfolder, all in the same folder.

#### Actual behaviour

When I click in "Move note to..." the only folder that are shown to me to choose are the other folders, without the folder I'm actually in. This means that I cannot move a note from a subfolder to another, or move the note from the root folder to a subfolder.
It seems strange to me that this doesn't work, I even looked in the past issues and I sort of recall it was possible. But I don't know what could I be setting wrong.

#### Steps to reproduce

1. Right click on a note in the note list panel.
2. Choose "Move note to..."
3. See that the options don't include the folder you are actually in.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[13:42:38] [debug] updatePanelMenu - 'updatePanelMenu'
[13:42:38] [debug] Reply from "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[13:42:38] [warning] "QNetworkReply error 301 from url /index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/Notes/&version_test=1: " "Il protocollo \"\" è sconosciuto"
[13:42:38] [debug] Reply from app version test
[13:42:38] [debug] on_noteTreeWidget_itemSelectionChanged
[13:42:38] [debug] setCurrentNote - 'note': Note: <id>12 <name>"2 La funzione filosofica" <fileName>"2 La funzione filosofica.md" <noteSubFolderId>21 <relativePath>"Elaborato 2° anno" <hasDirtyData>false - 'updateNoteText': true - 'updateSelectedNote': false
[13:42:38] [debug] Loading trigrams from ":/libraries/sonnet/src/trigrams.map"
[13:42:38] [warning] Missing trigrams for languages: QSet("en_PH", "en_BS", "en_AU", "en_BZ", "en_NA", "en_IE", "en_ZW", "en_IN", "en_NZ", "en_JM", "en_TT", "en_MW", "en_CA", "en_ZA", "en_GH")
[13:42:38] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_GB"
[13:42:38] [debug] Loading dictionary for "en_GB" from "/usr/share/hunspell"
[13:42:39] [debug] Created 0x5588580b4ab0
[13:42:39] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_US"
[13:42:39] [debug] Loading dictionary for "en_US" from "/usr/share/hunspell"
[13:42:39] [debug] Created 0x55885a1daec0
[13:42:39] [debug] No scores for "G005 #2"
[13:42:39] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_ZW"
[13:42:39] [debug] Loading dictionary for "en_ZW" from "/usr/share/hunspell"
[13:42:39] [debug] Created 0x55885a6d9770
[13:42:39] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_TT"
[13:42:39] [debug] Loading dictionary for "en_TT" from "/usr/share/hunspell"
[13:42:39] [debug] Created 0x558859949d00
[13:42:39] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_ZA"
[13:42:39] [debug] Loading dictionary for "en_ZA" from "/usr/share/hunspell"
[13:42:39] [debug] Created 0x55885b42c380
[13:42:39] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_PH"
[13:42:39] [debug] Loading dictionary for "en_PH" from "/usr/share/hunspell"
[13:42:39] [debug] Created 0x55885b984540
[13:42:39] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_NZ"
[13:42:39] [debug] Loading dictionary for "en_NZ" from "/usr/share/hunspell"
[13:42:39] [debug] Created 0x55885be46c90
[13:42:39] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_NA"
[13:42:39] [debug] Loading dictionary for "en_NA" from "/usr/share/hunspell"
[13:42:39] [debug] Created 0x55885b469c80
[13:42:39] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_MW"
[13:42:39] [debug] Loading dictionary for "en_MW" from "/usr/share/hunspell"
[13:42:39] [debug] Created 0x55885cbd6c40
[13:42:39] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_JM"
[13:42:39] [debug] Loading dictionary for "en_JM" from "/usr/share/hunspell"
[13:42:39] [debug] Created 0x55885be489b0
[13:42:39] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_IE"
[13:42:39] [debug] Loading dictionary for "en_IE" from "/usr/share/hunspell"
[13:42:39] [debug] Created 0x55885d92a050
[13:42:39] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_IN"
[13:42:39] [debug] Loading dictionary for "en_IN" from "/usr/share/hunspell"
[13:42:39] [debug] Created 0x55885e19ecc0
[13:42:39] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_GH"
[13:42:39] [debug] Loading dictionary for "en_GH" from "/usr/share/hunspell"
[13:42:40] [debug] Created 0x55885ea15050
[13:42:40] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_CA"
[13:42:40] [debug] Loading dictionary for "en_CA" from "/usr/share/hunspell"
[13:42:40] [debug] Created 0x55885f2899a0
[13:42:40] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_BZ"
[13:42:40] [debug] Loading dictionary for "en_BZ" from "/usr/share/hunspell"
[13:42:40] [debug] Created 0x55885f78b7a0
[13:42:40] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_BS"
[13:42:40] [debug] Loading dictionary for "en_BS" from "/usr/share/hunspell"
[13:42:40] [debug] Created 0x55885ffc5b70
[13:42:40] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_AU"
[13:42:40] [debug] Loading dictionary for "en_AU" from "/usr/share/hunspell"
[13:42:40] [debug] Created 0x55885816dd50
[13:42:40] [debug] No scores for "#IDE #SAT"
[13:42:40] [debug] No scores for "#2 #TRI"
[13:42:40] [debug] No scores for "G034 #SAT"
[13:42:40] [debug] No scores for "#2 #SAT"
[13:42:40] [debug] No scores for "A31/B47"
[13:42:40] [debug] No scores for "B41. "
[13:42:40] [debug] No scores for "[#IDE #REA #2]"
[13:42:40] [debug] No scores for "[#REA]"
[13:42:40] [debug] No scores for "[#ASO]"
[13:42:40] [debug] No scores for "[#2 #PRR #TRL]."
[13:42:40] [debug] No scores for "### Bird 2"
[13:42:40] [debug] No scores for "#PRR #MET #2"
[13:42:40] [debug] No scores for "758 #2 #TRI"
[13:42:40] [debug] added to history: NoteHistoryItem: <noteName>"2 La funzione filosofica" <noteSubFolderPathData>"Elaborato 2° anno" <cursorPosition>0 <relativeScrollBarPosition>0
[13:42:40] [debug] updatePanelMenu - 'updatePanelMenu'
[13:42:40] [debug] updatePanelMenu - 'updatePanelMenu'
[13:42:40] [debug] updatePanelMenu - 'updatePanelMenu'
[13:42:40] [debug] updatePanelMenu - 'updatePanelMenu'
[13:42:40] [debug] updatePanelMenu - 'updatePanelMenu'
[13:42:40] [debug] updatePanelMenu - 'updatePanelMenu'
[13:42:40] [debug] updatePanelMenu - 'updatePanelMenu'
[13:42:40] [debug] updatePanelMenu - 'updatePanelMenu'
[13:42:40] [debug] updatePanelMenu - 'updatePanelMenu'
[13:42:48] [status] Non è stato trovato alcun aggiornamento degli script
[13:43:26] [debug] updatePanelMenu - 'updatePanelMenu'
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `dom apr 4 13:43:30 2021`
**Version**: `21.3.1`
**Build date**: `Mar 16 2021`
**Build number**: `817`
**Platform**: `linux`
**Operating System**: `KDE Flatpak runtime`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `TuxFamily`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/home/samuele/.var/app/org.qownnotes.QOwnNotes/config/PBE/QOwnNotes.conf`
**Application database path**: `/home/samuele/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `it_IT`
**Locale (interface)**: `it`
**Primary screen resolution**: `1366x768`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `121`
**Calendar items**: `29`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_AU, en_BS, en_BZ, en_CA, en_GB, en_GH, en_IE, en_IN, en_JM, en_MW, en_NA, en_NZ, en_PH, en_TT, en_US, en_ZA, en_ZW, it_IT`
**Language names**: `Australian English (Australia), English (Bahamas), English (Belize), Canadian English (Canada), British English (United Kingdom), English (Ghana), English (Ireland), English (India), English (Jamaica), English (Malawi), English (Namibia), English (New Zealand), English (Philippines), English (Trinidad & Tobago), American English (United States), English (South Africa), English (Zimbabwe), italiano (Italia)`
**Application dictionaries path**: `/home/samuele/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `4`

### Note folder `Note`

**id**: `3`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/samuele/nextcloud/notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/samuele/nextcloud/notes/notes.sqlite`

### Note folder `Università`

**id**: `4`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/samuele/nextcloud/Università`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/samuele/nextcloud/Università/notes.sqlite`

### Note folder `Zettelkasten`

**id**: `5`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/samuele/nextcloud/notes (2)`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/samuele/nextcloud/notes (2)/notes.sqlite`

### Cloud connection ``

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `true`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `false`
**Editor/autoBracketRemoval** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `false`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `true`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-04-04T13:42:38.563`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Hack,10,-1,7,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Hack,10,-1,7,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/remove-note** (QString): `16384`
**MessageBoxOverride/remove-note-folder** (QString): `16384`
**NoteFolder-3/NoteTabNameList** (QString): `Situazioni interessanti`
**NoteFolder-3/NoteTabStickinessList**: *empty*
**NoteFolder-3/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteFolder-4/NoteTabNameList** (QString): `2 La funzione filosofica`
**NoteFolder-4/NoteTabStickinessList**: *empty*
**NoteFolder-4/NoteTabSubFolderPathDataList** (QString): `Elaborato 2° anno`
**NoteFolder-5/NoteTabNameList** (QString): `202103291522 Mito del dato`
**NoteFolder-5/NoteTabStickinessList**: *empty*
**NoteFolder-5/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteHistory-3** (QVariantList): `<variant list with 27 item(s)>`
**NoteHistory-4** (QVariantList): `<variant list with 35 item(s)>`
**NoteHistory-5** (QVariantList): `<variant list with 4 item(s)>`
**NoteHistoryCurrentIndex-3** (QString): `26`
**NoteHistoryCurrentIndex-4** (QString): `34`
**NoteHistoryCurrentIndex-5** (QString): `3`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-actionNext_note_tab** (QString): `Ctrl+Tab`
**Shortcuts/MainWindow-actionPrevious_note_tab** (QString): `Ctrl+Shift+Tab`
**Shortcuts/MainWindow-action_Print_note_markdown** (QString): *empty*
**Shortcuts/MainWindow-action_Print_note_text** (QString): *empty*
**Shortcuts/MainWindow-action_Quit** (QString): *empty*
**Shortcuts/MainWindow-action_Settings** (QString): *empty*
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Università`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `true`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `4`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `true`
**enableSocketServer** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): `yyyyMMddhhmm`
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): `it`
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `24`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `false`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `true`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/samuele/nextcloud/Università`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**recentNoteFolders** (QStringList): `/home/samuele/nextcloud/notes, /home/samuele/nextcloud/notes (2)`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-3** (QStringList): `Note 2021-03-25T16.56.26, Note 2021-03-21T19.28.34, Note 2021-03-19T17.38.15`
**savedSearches/noteFolder-4** (QStringList): `Note 2021-04-01T19.38.49, #IDE, Note 2021-03-31T15.46.03, Note 2021-03-31T15.43.24, Kant and Carnap`
**savedSearches/noteFolder-5** (QString): `Note 2021-03-29T15.21.57`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `false`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Barra degli strumenti principale`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `barra degli strumenti formattazione`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `barra degli strumenti "inserisci"`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `barra degli strumenti di crittografia`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `barra degli strumenti della finestra`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `esci dalla barra degli strumenti`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `true`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Minimale`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**XDG_RUNTIME_DIR**: `/run/user/1000`
**container**: `flatpak`
**J2SDKDIR**: `/usr/lib/jvm/java-16-oracle`
**USER**: `samuele`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**LC_TIME**: `it_IT.UTF-8`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `1546`
**J2REDIR**: `/usr/lib/jvm/java-16-oracle`
**SHLVL**: `0`
**HOME**: `/home/samuele`
**DESKTOP_SESSION**: `plasma`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**LC_MONETARY**: `it_IT.UTF-8`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**LOGNAME**: `samuele`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_ID**: `3`
**PATH**: `/app/bin:/usr/bin`
**DERBY_HOME**: `/usr/lib/jvm/java-16-oracle/db`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**LC_ADDRESS**: `it_IT.UTF-8`
**DISPLAY**: `:99.0`
**LANG**: `it_IT.UTF-8`
**XDG_CURRENT_DESKTOP**: `KDE`
**LC_TELEPHONE**: `it_IT.UTF-8`
**XDG_SESSION_DESKTOP**: `KDE`
**XAUTHORITY**: `/run/user/1000/Xauthority`
**SSH_AUTH_SOCK**: `/tmp/ssh-RzfZDRxVEIVT/agent.1484`
**SHELL**: `/bin/sh`
**LC_NAME**: `it_IT.UTF-8`
**QT_ACCESSIBILITY**: `1`
**LC_MEASUREMENT**: `it_IT.UTF-8`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**LC_IDENTIFICATION**: `it_IT.UTF-8`
**XDG_VTNR**: `1`
**JAVA_HOME**: `/usr/lib/jvm/java-16-oracle`
**PWD**: `/home/samuele`
**XDG_CONFIG_DIRS**: `/app/etc/xdg:/etc/xdg`
**XDG_DATA_DIRS**: `/app/share:/usr/share:/usr/share/runtime/share:/run/host/share`
**LC_NUMERIC**: `it_IT.UTF-8`
**LC_PAPER**: `it_IT.UTF-8`
**LANGUAGE**: `it:en_US`
**XCURSOR_THEME**: `breeze_cursors`
**XCURSOR_SIZE**: `24`
**QT_EXCLUDE_GENERIC_BEARER**: `1`
**MOZ_USE_XINPUT2**: `1`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**KDE_FULL_SESSION**: `true`
**KDE_SESSION_VERSION**: `5`
**KDE_SESSION_UID**: `1000`
**KDE_APPLICATIONS_AS_SCOPE**: `1`
**GTK_RC_FILES**: `/etc/gtk/gtkrc:/home/samuele/.gtkrc:/home/samuele/.config/gtkrc`
**GTK2_RC_FILES**: `/etc/gtk-2.0/gtkrc:/home/samuele/.gtkrc-2.0:/home/samuele/.config/gtkrc-2.0`
**SESSION_MANAGER**: `local/samuele-80lk:@/tmp/.ICE-unix/1622,unix/samuele-80lk:/tmp/.ICE-unix/1622`
**GI_TYPELIB_PATH**: `/app/lib/girepository-1.0`
**GST_PLUGIN_PATH**: `/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0`
**QT_PLUGIN_PATH**: `/app/lib64/plugins:/app/lib/plugins:/usr/share/runtime/lib/plugins`
**QML2_IMPORT_PATH**: `/app/lib64/qml:/app/lib/qml`
**KDE_FORK_SLAVES**: `1`
**FLATPAK_ID**: `org.qownnotes.QOwnNotes`
**PS1**: `[📦 $FLATPAK_ID \W]\$ `
**FLATPAK_SANDBOX_DIR**: `/home/samuele/.var/app/org.qownnotes.QOwnNotes/sandbox`
**XDG_DATA_HOME**: `/home/samuele/.var/app/org.qownnotes.QOwnNotes/data`
**XDG_CONFIG_HOME**: `/home/samuele/.var/app/org.qownnotes.QOwnNotes/config`
**XDG_CACHE_HOME**: `/home/samuele/.var/app/org.qownnotes.QOwnNotes/cache`
**AT_SPI_BUS_ADDRESS**: `unix:path=/run/user/1000/at-spi-bus`
</details>

**Comment by SamuXzX** [comment]
Sorry for not editing the issue, it seems I can't anymore.
Could it be because I'm using the tree-style note list panel, the last of the four options? I'm sorry for the names I use, but I'm using the italian version.

![immagine](https://user-images.githubusercontent.com/30182251/113507763-b87a2d80-954c-11eb-9d9d-0c05c68add51.png)

**Comment by pbek** [comment]
Hi! Are we talking about moving notes to a note subfolder of a different note folder? That would work very differently and isn't supported.

Or are we talking about #790? That's "work in progress" and still needs a looooot of work. 😁

**Comment by pbek** [comment]
> Sorry for not editing the issue, it seems I can't anymore.

There should be a `...` symbol in the top right corner of the issue post (aka first comment).

**Comment by SamuXzX** [comment]
> > Sorry for not editing the issue, it seems I can't anymore.
> 
> There should be a `...` symbol in the top right corner of the issue post (aka first comment).

Yeah sorry, didn't see the option in it.

> Hi! Are we talking about moving notes to a note subfolder of a different note folder? That would work very differently and isn't supported.
> 
> Or are we talking about #790? That's "work in progress" and still needs a looooot of work. grin

I'm sorry I didn't attach some useful stuff. This is what happens: it seems that the only way to move a note is with right-click and "move to". Doing it shows me a list of the note folders I have, that corresponds to the three buttons in the bottom-right corner (folder of notes panel with button style).
As you can see the list misses the one folder I already am in. Given (I may have missed the right way to do it) that such right-click>"move to" is the only way to move notes between folders and subfolders, I cannot move a note to a subfolder of the same folder I'm in.

![Peek 05-04-2021 18-55](https://user-images.githubusercontent.com/30182251/113600656-9d88e580-9640-11eb-9f3c-7507a22bb103.gif)

**Comment by pbek** [comment]
Like I said, #790 is "work in progress", best turn that mode off completely until it is (maybe) some day finished. 😉

**Comment by SamuXzX** [comment]
Understood, thank you very much

**Comment by SamuXzX** [comment]
Now I see: to move a note to a subfolder there's a completely different option.

![Peek 05-04-2021 23-06](https://user-images.githubusercontent.com/30182251/113627460-d9817200-9663-11eb-9d0c-1f4c2fe656a7.gif)
