### ISSUE TITLE
Strikethrough Markdown support

### ISSUE THREAD

**Issue by mrwhale** [pbek/QOwnNotes#209]
Small feature request. Can you please add the ability for strike through in the markdown support?

I know its not in the standard set, but would be nice

I have tried the double tilde (`~~`) around text, but in the viewer pane, it just shows as normal text

So not sure if needs feature added, or bug. Here is example

![screenshot from 2016-06-14 11-38-17](https://cloud.githubusercontent.com/assets/7307429/16028639/87375bd4-3224-11e6-8bf3-4a12a4b5e35c.png)

**Comment by pbek** [comment]
Thank you for your suggestion, but since the markdown highlighter and the markdown html converter would have to be forked and maintained for that request I'm not sure if that will happen...

**Comment by pbek** [comment]
This is in for quite a while now.
