### ISSUE TITLE
Wrong rendering of bullet list

### ISSUE THREAD

**Issue by marcoXbresciani** [pbek/QOwnNotes#2090]
#### Expected behaviour
Space between bullet points line should be the same.

#### Actual behaviour
When a nested bullet point ends a numbered list, the last point is not properly spaced.

#### Steps to reproduce
Use this sample markdown
```markdown
# 2021-04-08 Reflect on the Last Step Taken
1. What did you plan as your **Last Step**?
   * morning with XXX training course
   * working afternoon, possibly on importing products data
1. What did you **Expect**?
   * learn something about the XXX concept and the tool itself
     while understanding the practical usage
   * to proceed with product data import and application fine tuning
1. What **Actually Happened**?
   * had an ugly practical session on clicking random buttons guided by
     the trainer, with almost no idea on the why and the needs
1. What did you **Learn**?
   * XXX has a very bad training courses set, with pointless and
     quite time-wasting video courses that could become simple
     documentation on the tool itself
```

As shown in the picture (red arrow), the last bullet point is more spaced than the others.
![image](https://user-images.githubusercontent.com/48018419/114006369-ace67980-9860-11eb-9ed1-5b97cf2f5660.png)

Adding a further numbered item at the end, fixes it.
```markdown
# 2021-04-08 Reflect on the Last Step Taken
1. What did you plan as your **Last Step**?
   * morning with XXX training course
   * working afternoon, possibly on importing products data
1. What did you **Expect**?
   * learn something about the XXX concept and the tool itself
     while understanding the practical usage
   * to proceed with product data import and application fine tuning
1. What **Actually Happened**?
   * had an ugly practical session on clicking random buttons guided by
     the trainer, with almost no idea on the why and the needs
1. What did you **Learn**?
   * XXX has a very bad training courses set, with pointless and
     quite time-wasting video courses that could become simple
     documentation on the tool itself
1. useless content but then it formats properly
```
Trying with the markdown above, will fix the layout
![image](https://user-images.githubusercontent.com/48018419/114007337-8bd25880-9861-11eb-8056-01f04960455e.png)
Even adding a new line does not fix the issue:
```markdown
# 2021-04-08 Reflect on the Last Step Taken
1. What did you plan as your **Last Step**?
   * morning with XXX training course
   * working afternoon, possibly on importing products data
1. What did you **Expect**?
   * learn something about the XXX concept and the tool itself
     while understanding the practical usage
   * to proceed with product data import and application fine tuning
1. What **Actually Happened**?
   * had an ugly practical session on clicking random buttons guided by
     the trainer, with almost no idea on the why and the needs
1. What did you **Learn**?
   * XXX has a very bad training courses set, with pointless and
     quite time-wasting video courses that could become simple
     documentation on the tool itself

another useless content that does not format.
```

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `gio apr 8 12:10:26 2021`
**Version**: `21.3.9`
**Build date**: `Mar 30 2021`
**Build number**: `825`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 1909`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `yes`
**Settings path / key**: `C:/Users/marco.bresciani/QOwnNotes/Data/PBE/QOwnNotes.ini`
**Application database path**: `C:\Users\marco.bresciani\QOwnNotes\Data\QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes.exe`, `--portable`
**Qt Debug**: `0`
**Locale (system)**: `it_IT`
**Locale (interface)**: `it`
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `21`
**Calendar items**: `0`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\marco.bresciani\QOwnNotes\Data\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `C:\Users\marco.bresciani\QOwnNotes\Data\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `Kaizen Journal`
**database file**: `C:\Users\marco.bresciani\QOwnNotes\Data\Notes\notes.sqlite`

### Cloud connection ``

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

### Script `Meeting note`

**id**: `1`
**path**: `C:\Users\marco.bresciani\QOwnNotes\Data\scripts\meeting-note\meeting-note.qml`
**variablesJson**: 
```
{
    "defaultTags": "",
    "headlinePrefix": "Reflect on the Last Step Taken",
    "isAskForDateString": true,
    "noteBodyTemplate": "# Reflect on the Last Step Taken\n1. What did you plan as your **Last Step**?\n1. What did you **Expect**?\n1. What **Actually Happened**?\n1. What did you **Learn**?\n"
}
```
**identifier**: `meeting-note`
**version**: `1.4.0`
**minAppVersion**: `20.4.16`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**DistractionFreeMode/editorWidthCustom** (QString): `72`
**DistractionFreeMode/editorWidthMode** (QString): `5`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `18`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/ColorSchemes**: *empty*
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-514803c6-84ff-4da5-84a6-26c1989a49bb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (bool): `true`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`

**LastUpdateCheck** (QDateTime): `2021-04-08T11:36:45.199`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `15`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `doc`
**MainWindow/noteTextEdit.code.font** (QString): `Fira Code,7,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Fira Code,7,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Fira Code,8,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8,-1,5,50,0,0,0,0,0,Normale`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `false`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `false`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/remove-notes** (QString): `16384`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): `2021-04-08 Reflect on the Last Step Taken`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `Kaizen Journal`
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 78 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `77`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `8`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `true`
**StartHidden** (bool): `false`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `545b1943-b9aa-478d-931b-ab35e773ff4c`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `true`
**enableSocketServer** (bool): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `true`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): `yyyy-MM-dd HH:mm:ss`
**interfaceFontSize** (int): `9`
**interfaceLanguage** (QString): `it`
**internalIconTheme** (bool): `true`
**itemHeight** (int): `15`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `1`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `5`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `0`
**notesPath** (QString): `Notes`
**notifyAllExternalModifications** (bool): `true`
**overrideInterfaceFontSize** (bool): `true`
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `9h8Zw9Q7rUnL`
**restoreCursorPosition** (bool): `true`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2021-04-08T09.01.54, Note 2021-04-08T09.01.31, Note d3496b89-e7ff-4a9d-941b-f254b1c44d5c, Note 2021-04-07T09.50.54, Note 2021-04-01T14.37.08, Note 2021-04-01T14.31.19, Note 2021-04-01T08.40.12, Note 2021-03-31T08.57.26, Note 2021-03-31T08.57.16, Note 2021-03-31T08.56.36, Note 2021-03-30T08.05.24, Note 2021-03-29T10.51.39, Note 2021-03-29T10.26.59, Note 2021-03-29T10.26.21, Note 2021-03-29T10.24.54, Note 2021-03-29T10.20.36, Note 2021-03-29T10.18.52, Note 2021-03-29T09.52.51, Note 2021-03-29T09.42.41, Note 2021-03-29T09.38.46, Note 2021-03-29T09.37.54, Note 2021-03-29T09.37.19, Note 2021-03-29T09.36.40, Note 2021-03-29T09.35.45, Note 2021-03-29T09.35.26, Note 2021-03-29T08.27.33, Note 2021-03-29T08.25.02, Note 2021-03-29T08.24.03, Note 2021-03-29T08.12.05`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Barra degli strumenti principale`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `barra degli strumenti formattazione`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `barra degli strumenti "inserisci"`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `barra degli strumenti di crittografia`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `barra degli strumenti della finestra`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `esci dalla barra degli strumenti`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (bool): `false`
**useSoftWrapInNoteEditor** (QString): `false`
**useUNIXNewline** (bool): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-545b1943-b9aa-478d-931b-ab35e773ff4c/name** (QString): `Configurazione`
**workspace-545b1943-b9aa-478d-931b-ab35e773ff4c/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-545b1943-b9aa-478d-931b-ab35e773ff4c/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `545b1943-b9aa-478d-931b-ab35e773ff4c`
</details>

**Comment by pbek** [comment]
We are talking about #168, right?

**Comment by marcoXbresciani** [comment]
Gosh. I've even checked before opening it... 🤦🏻‍♂️ Yes, same, sorry.

**Comment by pbek** [comment]
No worries 😁
