### ISSUE TITLE
[Feature request] Line numbers in editor

### ISSUE THREAD

**Issue by Yoshua-chan** [pbek/QOwnNotes#2091]
I recently started using QOwnNotes and as a vim user I find it very useful that the program has vim mode.
My problem however is that the editor lacks any sort of indication of current line. I think that line numbering would be useful as the user could jump to specific line something like `54G` or jump a specific number of lines up/down using a number with `j` or `k`. I know this sort vertical movement is implemented in vim mode but without some sort of line numbering it doesn't feel like a complete feature.

**Comment by pbek** [comment]
Already suggested in #197, but I still had no luck adding them. @Waqar144?

> My problem however is that the editor lacks any sort of indication of current line. 

The current line number is indicated on the bottom right of the window.

**Comment by Waqar144** [comment]
Sure, I will give it a try. I just haven't found really necessary to have line-numbers in a note editor ;)

**Comment by pbek** [comment]
I integrated all my patches and fixes into QOwnNotes so that I can more integration work more easily. Turned off line numbers shouldn't cause any troubles now.

**Comment by pbek** [comment]
@Waqar144, your fixed colors also need fixing...

```cpp
        const QPen currentLine = QColor("#eef067");
        const QPen otherLines = QColor("#a6a6a6");
```

😅

**Comment by pbek** [comment]
## 21.7.1
- you can now turn on **line numbers** for the note editor in the *Editor settings*
  (for [#2091](https://github.com/pbek/QOwnNotes/issues/2091))
  - they cannot be used with turned off `Only use editor width setting in distraction free mode`
  - in the distraction free mode line numbers are turned off as well
  - the colors of the line number of the current line are currently only suited for dark mode

@Waqar144, thanks a lot for all your help and the implementation in *qmarkdowntextedit*!

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
And the build failures of old Qt version in <https://build.opensuse.org/package/show/home:pbek:QOwnNotes/desktop> have already started. 😆  I'll look into them tomorrow.

**Comment by proazr** [comment]
Had been wanting this for a while now. Just updated and enabled line numbers - it looks great! Thank you for all your work!

and now, if we could add bookmarks on specific line numbers in the gutter.. :stuck_out_tongue: Maybe I'll submit a feature request if one doesn't already exist :stuck_out_tongue_winking_eye:

![image](https://user-images.githubusercontent.com/51807907/124190652-a4cd5d00-da90-11eb-93cc-e375a5441f15.png)

**Comment by pbek** [comment]
Great, thank you for testing! I still need to get the colours in... (and some build fixes)

> bookmarks on specific line numbers in the gutter

bookmarks to jump to line numbers? from where? links in notes?

**Comment by Waqar144** [comment]
@pbek

This is bad:

```
QMargins QMarkdownTextEdit::viewportMargins() {
#if (QT_VERSION >= QT_VERSION_CHECK(5, 5, 0))
    return QPlainTextEdit::viewportMargins();
#else
    return QMargins();
#endif
}
```

It will break whatever values you are setting in `setPaperMargins()` and I think it might also break DFM.

**Comment by pbek** [comment]
> It will break whatever values you are setting in setPaperMargins() and I think it might also break DFM.

You mean for Qt < 5.5? We had that already in `QMargins QOwnNotesMarkdownTextEdit::viewportMargins()` in for 3.5 years. 😁

**Comment by pbek** [comment]
## 21.7.2
- the color of the current line number is now adapted if dark mode is disabled
- a build error for Qt < 5.5 was fixed

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Waqar144** [comment]
> @pbek
> 
> This is bad:
> 
> ```
> QMargins QMarkdownTextEdit::viewportMargins() {
> #if (QT_VERSION >= QT_VERSION_CHECK(5, 5, 0))
>     return QPlainTextEdit::viewportMargins();
> #else
>     return QMargins();
> #endif
> }
> ```
> 
> It will break whatever values you are setting in `setPaperMargins()` and I think it might also break DFM.

I dont have commit access or I really would just revert that.

**Comment by pbek** [comment]
> I dont have commit access or I really would just revert that.

What makes you so angry about the < Qt 5.5 fix? It doesn't change anything for Qt >= 5.5. qmarkdowntextedit didn't even build with Qt < 5.5 after the addition of line numbers.

I now even added a comment to it:
https://github.com/pbek/qmarkdowntextedit/commit/dab2246cb97d913403fa9d0d6afaef946203a808

**Comment by pbek** [comment]
And I now mentioned it in the readme: https://github.com/pbek/qmarkdowntextedit/commit/1b4b314c37500dfcd644a34f735ba0c8e485eba4

**Comment by pbek** [comment]
> And the build failures of old Qt version in https://build.opensuse.org/package/show/home:pbek:QOwnNotes/desktop have already started. laughing I'll look into them tomorrow.

All builds work again. 👍🏻

**Comment by Waqar144** [comment]
> > I dont have commit access or I really would just revert that.
> 
> What makes you so angry about the < Qt 5.5 fix? It doesn't change anything for Qt >= 5.5. qmarkdowntextedit didn't even build with Qt < 5.5 after the addition of line numbers.

Simply knowing that its broken and we are keeping that way is annoying + supporting it for no reason :man_shrugging: 

Well, nevermind I guess.


> And I now mentioned it in the readme: [pbek/qmarkdowntextedit@1b4b314](https://github.com/pbek/qmarkdowntextedit/commit/1b4b314c37500dfcd644a34f735ba0c8e485eba4)

That is incorrect as well. For qmarkdowntextedit itself, it can work pretty well with Qt 5.5 and below

**Comment by pbek** [comment]
> Simply knowing that its broken and we are keeping that way is annoying + supporting it for no reason

I don't even know how it would look like. But are we talking about QON or qmarkdowntextedit now?

> That is incorrect as well. For qmarkdowntextedit itself, it can work pretty well with Qt 5.5 and below

Do you think line numbers would work in qmarkdowntextedit below Qt 5.5 when the current margin can't be read? 🤔

**Comment by Waqar144** [comment]
Yeah, I don't see why there should be an issue (unless the app that uses it is changing its viewport margins). Other than that, it will work just fine

**Comment by pbek** [comment]
All the better, thank you!

**Comment by pbek** [comment]
I think we can close that for now, it's looking great and I didn't have any issues so far.
And we can rip out code for older Qt versions if we can't see any usage of those versions any more. 😅

**Comment by pbek** [comment]
And thanks again, @Waqar144, for the integration into qmarkdowntextedit! 👍🏻
