### ISSUE TITLE
[Q] Should Firefox browser extension sync across devices?

### ISSUE THREAD

**Issue by danieljweinberg** [pbek/QOwnNotes#2098]
#### General question

To show QOwnNotes Bookmarks in Firefox on a device where QOwnNotes is NOT running, I have to make [a socket connection](https://unix.stackexchange.com/questions/10428/simple-way-to-create-a-tunnel-from-one-local-port-to-another) to a device running it (via ssh or netcat) . Otherwise the extension returns Socket Undefined. Is Firefox sync supposed to work without establishing a socket?  Just checking if I'm missing something. Would love to view my Bookmarks easily on multiple devices.,but I understand if the above is the intended functionality so far. Thank you!

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed Apr 14 22:01:39 2021`
**Version**: `21.4.0`
**Build date**: `Apr  9 2021`
**Build number**: `826`
**Platform**: `linux`
**Operating System**: `Debian GNU/Linux 10 (buster)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.11.3`
**Qt Version (runtime)**: `5.11.3`
**Portable mode**: `no`
**Settings path / key**: `/home/daniel/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/daniel/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1680x1050`
**Icon theme**: `Tango`
**Notes in current note folder**: `9`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://_redacted_`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `20.0.8.1`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `en_US`
**Language codes**: `en_US`
**Language names**: `American English (United States)`
**Application dictionaries path**: `/home/daniel/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/daniel/Documents/qn`
**remotePath**: `notes_dw/qn`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/daniel/Documents/qn/notes.sqlite`

### Note folder `Personal`

**id**: `2`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/daniel/Documents/qn/Personal`
**remotePath**: `notes_dw/qn/Personal`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/daniel/Documents/qn/Personal/notes.sqlite`

### Note folder `CSC`

**id**: `3`
**isCurrent**: `no`
**activeTagId**: `-2`
**localPath**: `/home/daniel/Documents/qn/CSC`
**remotePath**: `notes_dw/qn/CSC`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/daniel/Documents/qn/CSC/notes.sqlite`

### Note folder `ECMC`

**id**: `4`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/daniel/Documents/qn/ECMC`
**remotePath**: `notes_dw/qn/ECMC`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/daniel/Documents/qn/ECMC/notes.sqlite`

### Cloud connection `Sandstone`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://_redacted_`
**username**: `daniel`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-04-14T21:29:24.047`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `41`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1**: *empty*
**MainWindow/noteTextEdit.code.font** (QString): `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**NoteFolder-1/NoteTabNameList** (QStringList): `zim-in-qn`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteFolder-2/NoteTabNameList** (QStringList): `personal-todo-test`
**NoteFolder-2/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-2/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteFolder-3/NoteTabNameList** (QString): `CSCtest 2021-04-13T13.08.29`
**NoteFolder-3/NoteTabStickinessList**: *empty*
**NoteFolder-3/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteFolder-4/NoteTabNameList** (QString): `vFB6eD3v`
**NoteFolder-4/NoteTabStickinessList**: *empty*
**NoteFolder-4/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteHistory-1** (QVariantList): `<variant list with 18 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 2 item(s)>`
**NoteHistory-3** (QVariantList): `<variant list with 1 item(s)>`
**NoteHistory-4** (QVariantList): `<variant list with 2 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `17`
**NoteHistoryCurrentIndex-2** (int): `1`
**NoteHistoryCurrentIndex-3** (QString): `0`
**NoteHistoryCurrentIndex-4** (QString): `1`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `2`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Personal`
**VersionDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `true`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `21`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/daniel/Documents/qn`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): `CSC, ECMC, Personal`
**ownCloud/todoCalendarEnabledList** (QStringList): `CSC, ECMC, Personal`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://calliope.home.daniel.digital/remote.php/dav/calendars/daniel/CA680F41-F7C7-48C1-AF05-5CB433D03D63/, https://calliope.home.daniel.digital/remote.php/dav/calendars/daniel/5197A380-E5F2-45E0-86A7-A26D47737468/, https://calliope.home.daniel.digital/remote.php/dav/calendars/daniel/B902F6D2-EADE-4C3F-9D03-E7DD311DCD6E/`
**ownCloud/todoCalendarUrlList** (QStringList): `_redacted_`
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `20.0.8.1`
**recentNoteFolders** (QStringList): `/home/daniel/Documents/qn/Personal, /home/daniel/Documents/qn/CSC, /home/daniel/Documents/qn/ECMC`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** _redacted_
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `en_US`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/2/name** (QString): `insertingToolbar`
**toolbar/2/title** (QString): `inserting toolbar`
**toolbar/3/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/3/name** (QString): `encryptionToolbar`
**toolbar/3/title** (QString): `encryption toolbar`
**toolbar/4/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/4/name** (QString): `windowToolbar`
**toolbar/4/title** (QString): `window toolbar`
**toolbar/5/items** (QString): `action_Quit`
**toolbar/5/name** (QString): `quitToolbar`
**toolbar/5/title** (QString): `quit toolbar`
**toolbar/6/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/6/name** (QString): `formattingToolbar`
**toolbar/6/title** (QString): `formatting toolbar`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**versionSplitterSizes** (QByteArray): `<binary data>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**webSocketServerService/token** (QString): `vFB6eD3v`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**USER**: `daniel`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `808`
**SHLVL**: `0`
**HOME**: `/home/daniel`
**DESKTOP_SESSION**: `/usr/share/xsessions/xfce`
**GTK_MODULES**: `gail:atk-bridge`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**GLADE_MODULE_PATH**: `:`
**LOGNAME**: `daniel`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_ID**: `3`
**PATH**: `/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`
**GLADE_PIXMAP_PATH**: `:`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_MENU_PREFIX**: `xfce-`
**LANG**: `en_US.UTF-8`
**XDG_CURRENT_DESKTOP**: `XFCE`
**XDG_SESSION_DESKTOP**: `XFCE`
**XAUTHORITY**: `/home/daniel/.Xauthority`
**SSH_AUTH_SOCK**: `/tmp/ssh-n3YCfi8qiWnw/agent.772`
**GLADE_CATALOG_PATH**: `:`
**SHELL**: `/bin/bash`
**QT_ACCESSIBILITY**: `1`
**XDG_VTNR**: `7`
**PWD**: `/home/daniel`
**XDG_DATA_DIRS**: `/usr/share/xfce4:/usr/local/share/:/usr/share/:/usr/share`
**XDG_CONFIG_DIRS**: `/etc/xdg`
**SESSION_MANAGER**: `local/amethyst:@/tmp/.ICE-unix/818,unix/amethyst:/tmp/.ICE-unix/818`
**DISPLAY**: `:0.0`
</details>

**Comment by pbek** [comment]
> To show QOwnNotes Bookmarks in Firefox on a device where QOwnNotes is NOT running, I have to make a socket connection to a device running it (via ssh or netcat) .

Did that work?
QOwnNotes opens the Socket on localhost only for security reasons (see #1885), maybe that's in your way.

> Otherwise the extension returns Socket Undefined.

Yes, QON needs to be running. All it does is checking your bookmark markdown files and parsing them for bookmark list items. But there is no internet required.

>  Is Firefox sync supposed to work without establishing a socket? 

You mean a sync with QOwnNotes bookmarks in markdown files? That's no sync, that's just a one way import. And yes, again you need QON to do the work. Of course you could use some other tool to put your browser bookmarks into a markdown file.

> Would love to view my Bookmarks easily on multiple devices.,but I understand if the above is the intended functionality so far. 

You need QON on every device and a mean to sync your note files, see https://www.qownnotes.org/getting-started/concept.html#nextcloud-desktop-sync-client

More info about the browser extension: https://www.qownnotes.org/getting-started/browser-extension.html

**Comment by danieljweinberg** [comment]
Making an ssh tunnel actually works perfectly! _Device1_ is running QON listening on _Port1_. _Device2_ has the Firefox extension talking to socket _Port2_, and the below command is all I had to do:

>  `user2@device2$ ssh -g -L port2:localhost:port1 -f -N user1@device1`

The extension on Device2 now shows all my bookmarks and I can view/add/edit them as if I were browsing on Device1.

Thank you for all you do and for reading my comment; now I better understand how the extension and QON fit together.  Below are 2 related ideas; I can file a feature request for either if it's relevant.

**Automatic regular import of bookmarks to QON** would be great -- I know it's not sync -- but would love to be able to add bookmarks on any device using my Firefox Sync (desktop/mobile) and then able to search in QON within bookmarks and notes. Is there already a way to schedule regular import? I recognize that QON would add duplicates of bookmarks upon re-importing, but (a) the extension seems to dedupe intelligently and (b) there are [various ways](https://unix.stackexchange.com/questions/30173/how-to-remove-duplicate-lines-inside-a-text-file) I can remove duplicate lines. Otherwise I could try [Buku](https://github.com/jarun/buku#quickstart) which seems to have the ability to do **automatic regular export**, and then I'd sync that with the Bookmarks.md QON file.

Also: is there a way to configure a **keyboard shortcut to Bookmark the current page in QON**?
Thank you!

**Comment by pbek** [comment]
> Automatic regular import of browser bookmarks to QON

That wouldn't be a good idea because that would duplicate existing bookmarks.

> automatic regular export of browser bookmarks to Markdown file

isn't that the same as your first suggestion 😅 
and why would you want to use both systems of managing bookmarks? better settle for one 😁 

> keyboard shortcut to Bookmark the current page in QON?

you can't really do such shortcuts in a Webbrowser to my knowledge, but there is a shortcut to open the extension window and then (at least in Chrome) you can use an access key to add a bookmark, see https://github.com/qownnotes/web-companion/#chrome

**Comment by pbek** [comment]
> user2@device2$ ssh -g -L port2:localhost:port1 -f -N user1@device1

yeah, I saw that you are using localhost on your stack exchange page after I posted 👍🏻

**Comment by danieljweinberg** [comment]
>  why would you want to use both systems of managing bookmarks? better settle for one 
I agree! Haha. I'm trying to piece together a way I can use Firefox on my phone and have its bookmarks get into QON, that's what this is all about.

**Comment by pbek** [comment]
> I agree! Haha. I'm trying to piece together a way I can use Firefox on my phone and have its bookmarks get into QON.

you could open the bookmark file (e.g. on Nextcloud Notes or a markdown editor) and open the links from there

**Comment by danieljweinberg** [comment]
> open the bookmark file (e.g. on Nextcloud Notes or a markdown editor) and open the links from there

Good point! 
I'll see -- that's probably easier than whatever I'm trying to mush together!

**Comment by pbek** [comment]
Syncing never is easy... 😉 
I will close this for now. But feel free to ask on...
