### ISSUE TITLE
Vim normal mode shift-left-right commands create too many tabs

### ISSUE THREAD

**Issue by joshmorel** [pbek/QOwnNotes#2099]
#### Expected behaviour

When using Vim in normal mode if I use for example `>>` I would expect 1 tab (or if "Use tab characters instead of spaces" is false, then "Indent" X spaces set in  using spaces, e.g. 2).

(on a related note, it would be great if `Tab after an unordered list character indents the list item` worked in Vim edit mode).

#### Actual behaviour

4 tabs are created.

Using tab characters:
![qownnotes-vim-shift-tab](https://user-images.githubusercontent.com/10546720/114864207-b6229980-9dbe-11eb-82ff-45d99b41e6ce.gif)

Using 2 spaces:
![qownnotes-vim-shift-spaces](https://user-images.githubusercontent.com/10546720/114864193-b02cb880-9dbe-11eb-8ffb-bb7567fcb929.gif)

#### Steps to reproduce

* Enable vim mode
* In normal mode on any line hit `>>` 

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Thu. Apr. 15 07:40:24 2021`
**Version**: `21.4.0`
**Build date**: `Apr  9 2021`
**Build number**: `826`
**Platform**: `linux`
**Operating System**: `Pop!_OS 20.04 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.12.8`
**Qt Version (runtime)**: `5.12.8`
**Portable mode**: `no`
**Settings path / key**: `/home/morel/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/morel/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_CA`
**Locale (interface)**: `en`
**Primary screen resolution**: `1600x900`
**Screen resolution(s)**: `1600x900, 1920x1080`
**Icon theme**: `Pop`
**Notes in current note folder**: `18`
**Calendar items**: `99`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://cloud.refactored.ca`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `20.0.8.1`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: `auto`
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/home/morel/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/morel/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `GNULinux`
**database file**: `/home/morel/Nextcloud/Notes/notes.sqlite`

### Cloud connection `New connection`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://cloud.refactored.ca`
**username**: `morel`

## Settings

**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `22`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `2`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `true`
**LastUpdateCheck** (QDateTime): `2021-04-15T07:38:37.706`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Fira Sans Semi-Light,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Fira Sans Semi-Light,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/move-notes** (QString): `16384`
**MessageBoxOverride/readonly-mode-allow** (QString): `16384`
**NoteFolder-1/NoteTabNameList** (QString): `test`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QString): `GNULinux`
**NoteHistory-1** (QVariantList): `<variant list with 21 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `20`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `gq2PTHkE4rpx`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableExternalDictionaries** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full-vertical`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): `en`
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `17`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `false`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/morel/Nextcloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList** (QString): `Personal`
**ownCloud/todoCalendarEnabledList** (QString): `Personal`
**ownCloud/todoCalendarEnabledUrlList** (QString): `https://cloud.refactored.ca/remote.php/dav/calendars/morel/personal/`
**ownCloud/todoCalendarUrlList** (QString): `https://cloud.refactored.ca/remote.php/dav/calendars/morel/personal/`
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `20.0.8.1`
**previousWorkspace** (QString): `QXtsRBzgwQV7`
**recentNoteFolders** (QStringList): `/home/morel/Nextcloud/Notes/Databases, /home/morel/Nextcloud/Notes/GNULinux, /home/morel/Nextcloud/Notes/Windows, /home/morel/Nextcloud/Notes/Business, /home/morel/Nextcloud/Notes/Audio, /home/morel/Nextcloud/Notes/Git`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2021-04-15T07.37.40, Note 2021-04-11T13.03.48, Note 2021-04-11T12.40.55, Note 2021-04-02T15.19.27, Note 2021-01-17T07.20.11, Note 2021-01-17T07.19.51`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `true`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-QXtsRBzgwQV7/name** (QString): `Full`
**workspace-QXtsRBzgwQV7/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-QXtsRBzgwQV7/windowState** (QByteArray): `<binary data>`
**workspace-gq2PTHkE4rpx/name** (QString): `Full vertical`
**workspace-gq2PTHkE4rpx/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-gq2PTHkE4rpx/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, QXtsRBzgwQV7, gq2PTHkE4rpx`

## System environment

**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`
**USER**: `morel`
**LANGUAGE**: `en_CA:en`
**LC_TIME**: `en_CA.UTF-8`
**SSH_AGENT_PID**: `4331`
**XDG_SESSION_TYPE**: `x11`
**SHLVL**: `0`
**HOME**: `/home/morel`
**DESKTOP_SESSION**: `pop`
**GIO_LAUNCHED_DESKTOP_FILE**: `/usr/share/applications/PBE.QOwnNotes.desktop`
**GTK_MODULES**: `gail:atk-bridge:appmenu-gtk-module`
**GNOME_SHELL_SESSION_MODE**: `pop`
**LC_MONETARY**: `en_CA.UTF-8`
**MANAGERPID**: `3052`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**LIBVIRT_DEFAULT_URI**: `qemu:///system`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `147468`
**IM_CONFIG_PHASE**: `1`
**MANDATORY_PATH**: `/usr/share/gconf/pop.mandatory.path`
**LOGNAME**: `morel`
**_**: `/usr/bin/dbus-update-activation-environment`
**JOURNAL_STREAM**: `8:55055`
**DEFAULTS_PATH**: `/usr/share/gconf/pop.default.path`
**XDG_SESSION_CLASS**: `user`
**USERNAME**: `morel`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**WINDOWPATH**: `2`
**PATH**: `/opt/mssql-tools/bin:/home/morel/bin:/home/morel/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
**PAPERSIZE**: `letter`
**SESSION_MANAGER**: `local/pop-os:@/tmp/.ICE-unix/4565,unix/pop-os:/tmp/.ICE-unix/4565`
**INVOCATION_ID**: `c522f96dc28e4ae3804783db7bd3e419`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**LC_ADDRESS**: `en_CA.UTF-8`
**XDG_MENU_PREFIX**: `gnome-`
**DISPLAY**: `:1`
**LANG**: `en_CA.UTF-8`
**LC_TELEPHONE**: `en_CA.UTF-8`
**XDG_CURRENT_DESKTOP**: `pop:GNOME`
**XAUTHORITY**: `/run/user/1000/gdm/Xauthority`
**XDG_SESSION_DESKTOP**: `pop`
**XMODIFIERS**: `@im=ibus`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**SHELL**: `/bin/bash`
**LC_NAME**: `en_CA.UTF-8`
**QT_ACCESSIBILITY**: `1`
**GDMSESSION**: `pop`
**LC_MEASUREMENT**: `en_CA.UTF-8`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**LC_IDENTIFICATION**: `en_CA.UTF-8`
**GJS_DEBUG_OUTPUT**: `stderr`
**QT_IM_MODULE**: `ibus`
**PWD**: `/home/morel`
**XDG_DATA_DIRS**: `/usr/share/pop:/home/morel/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-pop:/etc/xdg`
**LC_NUMERIC**: `en_CA.UTF-8`
**LC_PAPER**: `en_CA.UTF-8`

</details>

**Comment by pbek** [comment]
@Waqar144, any thoughts?

**Comment by pbek** [comment]
Must be a thing of the fakevim handler (taken from QtCreator). QOwnNotes is feeding it the the tab size and if to expand tabs...

**Comment by pbek** [comment]
Currently only the vim "TabStop" was set, I could also set the "ShiftWidth" (that was 8 by default) with the same value. I hope that others will not complain about that.

**Comment by pbek** [comment]
## 21.4.1
- in vim mode now also the setup indent size is used as shift width

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by joshmorel** [comment]
Perfect thanks @pbek . 

> Currently only the vim "TabStop" was set, I could also set the "ShiftWidth" (that was 8 by default) with the same value. I hope that others will not complain about that.

These are almost always set to the same value in .vimrc file or `vim:set` line at the top or bottom of a file. So I wouldn't imagine

**Comment by pbek** [comment]
Great, thank you for testing!
