### ISSUE TITLE
very long tags will destroy usability of app window

### ISSUE THREAD

**Issue by Fischmuetze** [pbek/QOwnNotes#210]
Before: 

![step1](https://cloud.githubusercontent.com/assets/19834496/16040729/bdb8926a-3231-11e6-9f86-92e682699ab0.png)

Adding of very long tags will tags - like this one - will destroy the UI by resizing the window to abnormal sizes without a chance to resize it:

"Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper.
Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam quis risus eget urna mollis ornare vel eu leo. Vestibulum id ligula porta felis euismod semper. Nullam quis risus eget urna mollis ornare vel eu leo.
Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed posuere consectetur est at lobortis. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Sed posuere consectetur est at lobortis. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.
Vestibulum id ligula porta felis euismod semper. Donec id elit non mi porta gravida at eget metus. Nullam quis risus eget urna mollis ornare vel eu leo. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Sed posuere consectetur est at lobortis."

After:
![step2](https://cloud.githubusercontent.com/assets/19834496/16040759/f9c9f53c-3231-11e6-830e-ba02935e995b.png)

**Comment by pbek** [comment]
Thank you for your report, I guess I will just shorten the name in the remove-button.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?
