### ISSUE TITLE
New feature request: Definition list

### ISSUE THREAD

**Issue by marcoXbresciani** [pbek/QOwnNotes#2100]
It would be nice to have definition lists as in https://www.markdownguide.org/extended-syntax/#definition-lists

#### Expected behaviour
Writing 
```markdown
Term
: definition
```
could be rendered as 
<dl>
  <dt>Term</dt>
  <dd>definition</dd>
</dl>

```html
<dl>
  <dt>Term</dt>
  <dd>definition</dd>
</dl>
```

#### Actual behaviour
Now
```markdown
Term
: definition
```
is rendered as

Term : definition

**Comment by pbek** [comment]
I don't think https://github.com/mity/md4c supports that, but you could implement it yourself in a script with the help of https://www.qownnotes.org/scripting/hooks.html#notetomarkdownhtmlhook.

**Comment by dohliam** [comment]
I have made a PR that adds support for this to the `scripts` repo. There is room for improvement and configurability, but the basic functionality requested by @marcoXbresciani should work.

**Comment by pbek** [comment]
It's merged now.

**Comment by pbek** [comment]
I will close this issue then until there is more information. 😁  Thank you!
