### ISSUE TITLE
[Q] Folder panel increases its size when scaledown-and-maximize the window or when unlocking-and-locking panels

### ISSUE THREAD

**Issue by SamuXzX** [pbek/QOwnNotes#2103]
#### General question

I noticed that when I reduce the size of Qownnotes' window and I maximize it again, the panel from where I choose the folder of the notes, when shown as buttons instead of a dropdown list, increases its size.

![immagine](https://user-images.githubusercontent.com/30182251/115223785-77694800-a10c-11eb-9bc7-ecc614ab9239.png)
![immagine](https://user-images.githubusercontent.com/30182251/115223867-91a32600-a10c-11eb-91e4-6387264a82e5.png)
![immagine](https://user-images.githubusercontent.com/30182251/115223896-9a93f780-a10c-11eb-98dd-7ef5c3c64cd9.png)

This happens also when I unlock the panels and then I lock them again. I did some attempts and it seems it doesn't depend on how the panels are organized in the column I have on the right.

![immagine](https://user-images.githubusercontent.com/30182251/115224081-c1eac480-a10c-11eb-81de-0a58734b099c.png)
![immagine](https://user-images.githubusercontent.com/30182251/115224150-d0d17700-a10c-11eb-8aae-ef4db40d0a68.png)

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[12:40:02] [debug] updatePanelMenu - 'updatePanelMenu'
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `lun apr 19 12:40:06 2021`
**Version**: `21.4.0`
**Build date**: `Apr 10 2021`
**Build number**: `826`
**Platform**: `linux`
**Operating System**: `KDE Flatpak runtime`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `TuxFamily`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.3`
**Portable mode**: `no`
**Settings path / key**: `/home/samuele/.var/app/org.qownnotes.QOwnNotes/config/PBE/QOwnNotes.conf`
**Application database path**: `/home/samuele/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `it_IT`
**Locale (interface)**: `it`
**Primary screen resolution**: `1366x768`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `133`
**Calendar items**: `29`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_AU, en_BS, en_BZ, en_CA, en_GB, en_GH, en_IE, en_IN, en_JM, en_MW, en_NA, en_NZ, en_PH, en_TT, en_US, en_ZA, en_ZW, it_IT`
**Language names**: `Australian English (Australia), English (Bahamas), English (Belize), Canadian English (Canada), British English (United Kingdom), English (Ghana), English (Ireland), English (India), English (Jamaica), English (Malawi), English (Namibia), English (New Zealand), English (Philippines), English (Trinidad & Tobago), American English (United States), English (South Africa), English (Zimbabwe), italiano (Italia)`
**Application dictionaries path**: `/home/samuele/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `4`

### Note folder `Notes`

**id**: `3`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/samuele/nextcloud/notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/samuele/nextcloud/notes/notes.sqlite`

### Note folder `Università`

**id**: `4`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/samuele/nextcloud/Università`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `Elaborato 2° anno`
**database file**: `/home/samuele/nextcloud/Università/notes.sqlite`

### Note folder `Zettelkasten`

**id**: `5`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/samuele/nextcloud/notes (2)`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/samuele/nextcloud/notes (2)/notes.sqlite`

### Cloud connection ``

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `true`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `false`
**Editor/autoBracketRemoval** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `false`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `true`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-04-19T12:23:09.864`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-4** (QStringList): `Elaborato 2° anno`
**MainWindow/noteTextEdit.code.font** (QString): `Hack,10,-1,7,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Hack,10,-1,7,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/issue-dialog-new-issue** (int): `16384`
**MessageBoxOverride/remove-note** (QString): `16384`
**MessageBoxOverride/remove-note-folder** (QString): `16384`
**NoteFolder-3/NoteTabNameList** (QString): `Quotes`
**NoteFolder-3/NoteTabStickinessList**: *empty*
**NoteFolder-3/NoteTabSubFolderPathDataList** (QString): `Enjoy`
**NoteFolder-4/NoteTabNameList** (QStringList): `scaletta, Note 2021-04-19T10.11.59`
**NoteFolder-4/NoteTabStickinessList**: *empty*
**NoteFolder-4/NoteTabSubFolderPathDataList** (QStringList): `Elaborato 2° anno, Elaborato 2° anno`
**NoteFolder-5/NoteTabNameList** (QString): `202010291432 LIBRO MCDOWELL, "Mente e mondo"`
**NoteFolder-5/NoteTabStickinessList**: *empty*
**NoteFolder-5/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteHistory-3** (QVariantList): `<variant list with 39 item(s)>`
**NoteHistory-4** (QVariantList): `<variant list with 42 item(s)>`
**NoteHistory-5** (QVariantList): `<variant list with 5 item(s)>`
**NoteHistoryCurrentIndex-3** (QString): `38`
**NoteHistoryCurrentIndex-4** (QString): `41`
**NoteHistoryCurrentIndex-5** (QString): `4`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-actionNext_note_tab** (QString): `Ctrl+Tab`
**Shortcuts/MainWindow-actionPrevious_note_tab** (QString): `Ctrl+Shift+Tab`
**Shortcuts/MainWindow-action_Print_note_markdown** (QString): *empty*
**Shortcuts/MainWindow-action_Print_note_text** (QString): *empty*
**Shortcuts/MainWindow-action_Quit** (QString): *empty*
**Shortcuts/MainWindow-action_Settings** (QString): *empty*
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Università`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `true`
**allowNoteEditing** (bool): `false`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `4`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): `yyyyMMddhhmm`
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): `it`
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `24`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `false`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `true`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `true`
**noteSubfoldersPanelShowNotesRecursively** (QString): `true`
**noteSubfoldersPanelShowRootFolderName** (QString): `false`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/samuele/nextcloud/Università`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**recentNoteFolders** (QStringList): `/home/samuele/nextcloud/notes, /home/samuele/nextcloud/notes (2)`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-3** (QStringList): `Note 2021-04-04T13.52.16, Note 2021-03-25T16.56.26, Note 2021-03-21T19.28.34, Note 2021-03-19T17.38.15`
**savedSearches/noteFolder-4** (QStringList): `Note 2021-04-19T12.33.34, Note 2021-04-19T10.11.59, Note 2021-04-18T13.39.39, Note 2021-04-08T17.24.48, Note 2021-04-01T19.38.49, #IDE, Note 2021-03-31T15.46.03, Note 2021-03-31T15.43.24, Kant and Carnap`
**savedSearches/noteFolder-5** (QString): `Note 2021-03-29T15.21.57`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `false`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Barra degli strumenti principale`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `barra degli strumenti formattazione`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `barra degli strumenti "inserisci"`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `barra degli strumenti di crittografia`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `barra degli strumenti della finestra`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `esci dalla barra degli strumenti`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `true`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Minimale`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**XDG_RUNTIME_DIR**: `/run/user/1000`
**container**: `flatpak`
**J2SDKDIR**: `/usr/lib/jvm/java-16-oracle`
**USER**: `samuele`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**LC_TIME**: `it_IT.UTF-8`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `1897`
**J2REDIR**: `/usr/lib/jvm/java-16-oracle`
**SHLVL**: `0`
**HOME**: `/home/samuele`
**DESKTOP_SESSION**: `plasma`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**LC_MONETARY**: `it_IT.UTF-8`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**LOGNAME**: `samuele`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_ID**: `4`
**PATH**: `/app/bin:/usr/bin`
**DERBY_HOME**: `/usr/lib/jvm/java-16-oracle/db`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**LC_ADDRESS**: `it_IT.UTF-8`
**DISPLAY**: `:99.0`
**LANG**: `it_IT.UTF-8`
**XDG_CURRENT_DESKTOP**: `KDE`
**LC_TELEPHONE**: `it_IT.UTF-8`
**XDG_SESSION_DESKTOP**: `KDE`
**XAUTHORITY**: `/run/user/1000/Xauthority`
**SSH_AUTH_SOCK**: `/tmp/ssh-qfH6u9bhdppA/agent.1833`
**SHELL**: `/bin/sh`
**LC_NAME**: `it_IT.UTF-8`
**QT_ACCESSIBILITY**: `1`
**LC_MEASUREMENT**: `it_IT.UTF-8`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**LC_IDENTIFICATION**: `it_IT.UTF-8`
**XDG_VTNR**: `1`
**JAVA_HOME**: `/usr/lib/jvm/java-16-oracle`
**PWD**: `/home/samuele`
**XDG_CONFIG_DIRS**: `/app/etc/xdg:/etc/xdg`
**XDG_DATA_DIRS**: `/app/share:/usr/share:/usr/share/runtime/share:/run/host/share`
**LC_NUMERIC**: `it_IT.UTF-8`
**LC_PAPER**: `it_IT.UTF-8`
**LANGUAGE**: `it:en_US`
**XCURSOR_THEME**: `breeze_cursors`
**XCURSOR_SIZE**: `24`
**QT_EXCLUDE_GENERIC_BEARER**: `1`
**MOZ_USE_XINPUT2**: `1`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**KDE_FULL_SESSION**: `true`
**KDE_SESSION_VERSION**: `5`
**KDE_SESSION_UID**: `1000`
**KDE_APPLICATIONS_AS_SCOPE**: `1`
**GTK_RC_FILES**: `/etc/gtk/gtkrc:/home/samuele/.gtkrc:/home/samuele/.config/gtkrc`
**GTK2_RC_FILES**: `/etc/gtk-2.0/gtkrc:/home/samuele/.gtkrc-2.0:/home/samuele/.config/gtkrc-2.0`
**SESSION_MANAGER**: `local/samuele-80lk:@/tmp/.ICE-unix/1975,unix/samuele-80lk:/tmp/.ICE-unix/1975`
**GI_TYPELIB_PATH**: `/app/lib/girepository-1.0`
**GST_PLUGIN_PATH**: `/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0`
**QT_PLUGIN_PATH**: `/app/lib64/plugins:/app/lib/plugins:/usr/share/runtime/lib/plugins`
**QML2_IMPORT_PATH**: `/app/lib64/qml:/app/lib/qml`
**KDE_FORK_SLAVES**: `1`
**FLATPAK_ID**: `org.qownnotes.QOwnNotes`
**PS1**: `[📦 $FLATPAK_ID \W]\$ `
**FLATPAK_SANDBOX_DIR**: `/home/samuele/.var/app/org.qownnotes.QOwnNotes/sandbox`
**XDG_DATA_HOME**: `/home/samuele/.var/app/org.qownnotes.QOwnNotes/data`
**XDG_CONFIG_HOME**: `/home/samuele/.var/app/org.qownnotes.QOwnNotes/config`
**XDG_CACHE_HOME**: `/home/samuele/.var/app/org.qownnotes.QOwnNotes/cache`
**AT_SPI_BUS_ADDRESS**: `unix:path=/run/user/1000/at-spi-bus`
</details>

**Comment by pbek** [comment]
QON depends on the layout management of Qt and that depends on the operating system. If you want fine control about the sizes best define a different workspace for "maximized" and toggle between them with a script and the help of https://www.qownnotes.org/scripting/hooks.html#windowstatechangedhook.

**Comment by pbek** [comment]
There are methods for dealing with workspaces in https://www.qownnotes.org/scripting/classes.html#properties-and-methods-4.

**Comment by pbek** [comment]
e.g. 

```QML
// Set 'Edit' workspace as current workspace
mainWindow.setCurrentWorkspace(mainWindow.getWorkspaceUuid("Edit"));
```
