### ISSUE TITLE
Relative links to new file in existing subfolder will create new folders instead of using the existing subfolder

### ISSUE THREAD

**Issue by ldv8434** [pbek/QOwnNotes#2106]
Hey there, I have a website that I manage using QOwnNotes (thank you for making it!) and I've encountered a strange issue regarding file creation via relative links. 

Here's my (minimized) folder structure: 
```
.
├── blog
├── pages
│   ├── example_file.md
│   ├── information
│   └── tech
└── trash
```
If I put the line `[Test file](./information/filename.md)` within example_file.md and click the link from the preview panel, it will create the following structure:
```
.
├── blog
├── pages
│   ├── example_file.md
│   ├── information
│   ├── pages
│   │   └── information
│   │       └── filename.md
│   └── tech
└── trash
```
This is only an issue when the file does not already exist. If `filename.md` is already in the existing `information` folder, then the link will work normally. 

#### Expected behaviour
When linking to a non-existent file in an existing subfolder, place the file in that subfolder.

#### Actual behaviour
A new set of subfolders matching the path from the current folder will be created relative to the subfolder of the note being linked from.

#### Steps to reproduce
- create a note within a subfolder
- create a subfolder within that subfolder 
- create a relative link `./existing_subfolder/filename.md`
- click the link in the preview window

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Apr 20 16:33:39 2021`
**Version**: `21.4.2`
**Build date**: `Apr 20 2021`
**Build number**: `828`
**Platform**: `linux`
**Operating System**: `Arch Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/home/dracula/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/dracula/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080`
**Icon theme**: `breeze`
**Notes in current note folder**: `25`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/home/dracula/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `3`

### Note folder `default`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/dracula/tmp`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/dracula/tmp/notes.sqlite`

### Note folder `removed`

**id**: `2`
**isCurrent**: `no`
**activeTagId**: `-1`
**localPath**: `/home/dracula/Documents/Personal/removed/content`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/dracula/Documents/Personal/removed/content/notes.sqlite`

### Note folder `Library Phantasmagoria`

**id**: `3`
**isCurrent**: `yes`
**activeTagId**: `-2`
**localPath**: `/home/dracula/Documents/Personal/libraryphantasmagoria/content`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: `information`
**database file**: `/home/dracula/Documents/Personal/libraryphantasmagoria/content/notes.sqlite`

### Note folder `CSEC.461`

**id**: `4`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/dracula/Documents/CSEC.461 Comp Sys Security`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/dracula/Documents/CSEC.461 Comp Sys Security/notes.sqlite`

### Note folder `CSEC.462`

**id**: `5`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/dracula/Documents/CSEC.462 Network Security and Forensics`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/dracula/Documents/CSEC.462 Network Security and Forensics/notes.sqlite`

### Note folder `PHIL.409`

**id**: `6`
**isCurrent**: `no`
**activeTagId**: `-1`
**localPath**: `/home/dracula/Documents/PHIL.409 Existentialism`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/dracula/Documents/PHIL.409 Existentialism/notes.sqlite`

### Note folder `Misc Notes`

**id**: `7`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/dracula/Documents/Personal/Misc Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/dracula/Documents/Personal/Misc Notes/notes.sqlite`

### Cloud connection ``

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `true`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `30`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/useTabIndent** (QString): `true`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `/home/dracula/Documents/PHIL.409 Existentialism`
**FileDialog/LastPath-InsertImage** (QString): `/home/dracula/Documents/Personal/libraryphantasmagoria/content/images`
**FileDialog/LastPath-NotePDFExport** (QString): `/home/dracula/Documents/PHIL.409 Existentialism`
**ImageDialog/disableCopying** (QString): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-04-20T16:32:42.831`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LinkDialog/lastSelectedFileUrl** (QString): `file:///home/dracula/Documents/Personal/libraryphantasmagoria/content/pages/tech/virtual-reality.md`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QString): `reviews`
**MainWindow/noteSubFolderTreeWidgetExpandState-3** (QStringList): `pages/reviews, pages/pages, pages`
**MainWindow/noteTextEdit.code.font** (QString): `Source Code Pro,10,-1,0,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Source Sans 3,10,-1,0,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Hack,10,-1,7,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/open-url-create-note** (QString): `16384`
**MessageBoxOverride/tag-notes** (QString): `16384`
**NoteFolder-1/NoteTabNameList**: *empty*
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList**: *empty*
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteFolder-2/NoteTabNameList**: *empty*
**NoteFolder-2/NoteTabStickinessList**: *empty*
**NoteFolder-2/NoteTabSubFolderPathDataList**: *empty*
**NoteFolder-2/allowDifferentNoteFileName** (QString): `true`
**NoteFolder-3/NoteTabNameList**: *empty*
**NoteFolder-3/NoteTabStickinessList**: *empty*
**NoteFolder-3/NoteTabSubFolderPathDataList**: *empty*
**NoteFolder-3/allowDifferentNoteFileName** (bool): `true`
**NoteFolder-4/NoteTabNameList** (QString): `team8`
**NoteFolder-4/NoteTabStickinessList**: *empty*
**NoteFolder-4/NoteTabSubFolderPathDataList** (QString): `ATTACK`
**NoteFolder-4/allowDifferentNoteFileName** (QString): `true`
**NoteFolder-5/NoteTabNameList**: *empty*
**NoteFolder-5/NoteTabStickinessList**: *empty*
**NoteFolder-5/NoteTabSubFolderPathDataList**: *empty*
**NoteFolder-5/allowDifferentNoteFileName** (QString): `true`
**NoteFolder-6/NoteTabNameList** (QString): `L10 Response`
**NoteFolder-6/NoteTabStickinessList**: *empty*
**NoteFolder-6/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteFolder-6/allowDifferentNoteFileName** (QString): `true`
**NoteFolder-7/NoteTabNameList** (QString): `Buy List`
**NoteFolder-7/NoteTabStickinessList**: *empty*
**NoteFolder-7/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteFolder-7/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 12 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 11 item(s)>`
**NoteHistory-3** (QVariantList): `<variant list with 53 item(s)>`
**NoteHistory-4** (QVariantList): `<variant list with 6 item(s)>`
**NoteHistory-6** (QVariantList): `<variant list with 18 item(s)>`
**NoteHistory-7** (QVariantList): `<variant list with 15 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `11`
**NoteHistoryCurrentIndex-2** (QString): `10`
**NoteHistoryCurrentIndex-3** (QString): `52`
**NoteHistoryCurrentIndex-4** (QString): `5`
**NoteHistoryCurrentIndex-6** (QString): `17`
**NoteHistoryCurrentIndex-7** (QString): `14`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExport** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `3`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `true`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): `yyyy-MM-dd hh:mm`
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `24`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `false`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `0`
**notesPath** (QString): `/home/dracula/Documents/Personal/libraryphantasmagoria/content`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `0`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `7d92832c-300a-4dbd-8230-fd78fe47a70d`
**recentNoteFolders** (QStringList): `/home/dracula/Documents/CSEC.461 Comp Sys Security, /home/dracula/Documents/Personal/Misc Notes, /home/dracula/tmp, /home/dracula/Documents/CSEC.462 Network Security and Forensics, /home/dracula/Documents/PHIL.409 Existentialism, /home/dracula/Documents/Personal/removed/content, /home/dracula/Documents`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `stylus_css, games, ideas, Note 2021-04-13T00.06.00, Note 2021-04-13T00.00.51, Note 2021-04-12T23.59.19`
**savedSearches/noteFolder-3** (QStringList): `Note 2021-04-13T13.34.46, Note 2021-04-13T00.31.08`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-7d92832c-300a-4dbd-8230-fd78fe47a70d/name** (QString): `Classes`
**workspace-7d92832c-300a-4dbd-8230-fd78fe47a70d/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-7d92832c-300a-4dbd-8230-fd78fe47a70d/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 7d92832c-300a-4dbd-8230-fd78fe47a70d`

## System environment

**SHELL**: `/usr/bin/zsh`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**DESKTOP_SESSION**: `plasma`
**XDG_SEAT**: `seat0`
**PWD**: `/home/dracula`
**XDG_SESSION_DESKTOP**: `KDE`
**LOGNAME**: `dracula`
**XDG_SESSION_TYPE**: `x11`
**XAUTHORITY**: `/home/dracula/.Xauthority`
**MOTD_SHOWN**: `pam`
**HOME**: `/home/dracula`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**USER**: `dracula`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**DISPLAY**: `:0`
**SHLVL**: `0`
**XDG_VTNR**: `1`
**XDG_SESSION_ID**: `2`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**MAIL**: `/var/spool/mail/dracula`
**OLDPWD**: `/home/dracula`
**CUDA_PATH**: `/opt/cuda`
**GRADLE_HOME**: `/usr/share/java/gradle`
**MKLROOT**: `/opt/intel/mkl`
**LANG**: `en_US.UTF-8`
**HG**: `/usr/bin/hg`
**GTK_MODULES**: `canberra-gtk-module`
**GTK3_MODULES**: `xapp-gtk3-module`
**_**: `/usr/bin/startplasma-x11`
**QT_SCREEN_SCALE_FACTORS**: `DP-0=1;DP-1=1;HDMI-0=1;DP-2=1;DP-3=1;DP-4=1;DP-5=1;`
**XCURSOR_THEME**: `breeze_cursors`
**XCURSOR_SIZE**: `24`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**KDE_FULL_SESSION**: `true`
**KDE_SESSION_VERSION**: `5`
**KDE_SESSION_UID**: `1000`
**KDE_APPLICATIONS_AS_SCOPE**: `1`
**GTK_RC_FILES**: `/etc/gtk/gtkrc:/home/dracula/.gtkrc:/home/dracula/.config/gtkrc`
**GTK2_RC_FILES**: `/etc/gtk-2.0/gtkrc:/home/dracula/.gtkrc-2.0:/home/dracula/.config/gtkrc-2.0`
**SESSION_MANAGER**: `local/kinbaku:@/tmp/.ICE-unix/1054,unix/kinbaku:/tmp/.ICE-unix/1054`
**KCRASH_AUTO_RESTARTED**: `1`

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>
```
[16:33:12] [debug] on_noteTextView_anchorClicked - 'url': QUrl("file:///home/dracula/Documents/Personal/libraryphantasmagoria/content/pages/./information/filename.md")
[16:33:12] [debug] fileUrlInCurrentNoteFolderToRelativePath - 'path': "/home/dracula/Documents/Personal/libraryphantasmagoria/content/pages/./information/filename.md"
[16:33:12] [debug] fileUrlInCurrentNoteFolderToRelativePath - 'canonicalFilePath': "/home/dracula/Documents/Personal/libraryphantasmagoria/content/pages/information/filename.md"
[16:33:12] [debug] fileUrlInCurrentNoteFolderToRelativePath - 'path': "/home/dracula/Documents/Personal/libraryphantasmagoria/content/pages/./information/"
[16:33:12] [debug] fileUrlInCurrentNoteFolderToRelativePath - 'canonicalFilePath': "/home/dracula/Documents/Personal/libraryphantasmagoria/content/pages/information/"
[16:33:12] [debug] buildNotesIndex - 'noteSubFolderId': 0
[16:33:12] [debug] setupNoteFolderTables - 'database version': 14
[16:33:12] [debug] cloudConnection: CloudConnection: <id>1 <name>"" <serverUrl>"" <username>"" <priority>0
[16:33:12] [debug] reloadNoteSubFolderTree
[16:33:12] [debug] filterNotesByNoteSubFolders - 'noteSubFolderIds': QVector(1)
[16:33:12] [debug] filterNotesByTag - 'noteIdList': QVector(1, 7, 2, 23, 24, 16, 8, 9, 10, 11, 14, 17, 3, 12, 18, 15, 19, 20, 13, 4, 21, 5, 22, 6)
[16:33:12] [debug] buildNotesIndex - 'noteSubFolderId': 0
[16:33:12] [debug] setupNoteFolderTables - 'database version': 14
[16:33:12] [debug] cloudConnection: CloudConnection: <id>1 <name>"" <serverUrl>"" <username>"" <priority>0
[16:33:12] [debug] reloadNoteSubFolderTree
[16:33:12] [debug] filterNotesByNoteSubFolders - 'noteSubFolderIds': QVector(10)
[16:33:12] [debug] filterNotesByTag - 'noteIdList': QVector(1, 7, 2, 23, 24, 16, 8, 9, 10, 11, 14, 17, 3, 12, 18, 15, 19, 20, 13, 4, 21, 5, 22, 6)
[16:33:12] [debug] filterNotesByNoteSubFolders - 'noteSubFolderIds': QVector(11)
[16:33:12] [debug] filterNotesByTag - 'noteIdList': QVector(1, 7, 2, 23, 24, 16, 8, 9, 10, 11, 14, 17, 3, 12, 18, 15, 19, 20, 13, 4, 21, 5, 22, 6)
[16:33:12] [debug] reloadTagTree
[16:33:12] [debug] reloadTagTree - 'noteSubFolderIds': QVector(11)
[16:33:12] [debug] storing note file: "filename.md"
[16:33:12] [status] Stored current note to disk
[16:33:12] [debug] loadNoteDirectoryList
[16:33:12] [debug] reloadTagTree
[16:33:12] [debug] reloadTagTree - 'noteSubFolderIds': QVector(11)
[16:33:12] [debug] filterNotesByNoteSubFolders - 'noteSubFolderIds': QVector(11)
[16:33:12] [debug] filterNotesByTag - 'noteIdList': QVector(25, 1, 7, 2, 23, 24, 16, 8, 9, 10, 11, 14, 17, 3, 12, 18, 15, 19, 20, 13, 4, 21, 5, 22, 6)
[16:33:12] [debug] reloadNoteSubFolderTree
[16:33:12] [debug] filterNotesByNoteSubFolders - 'noteSubFolderIds': QVector(11)
[16:33:12] [debug] filterNotesByTag - 'noteIdList': QVector(25, 1, 7, 2, 23, 24, 16, 8, 9, 10, 11, 14, 17, 3, 12, 18, 15, 19, 20, 13, 4, 21, 5, 22, 6)
[16:33:12] [debug] setCurrentNote - 'note': Note: <id>25 <name>"filename" <fileName>"filename.md" <noteSubFolderId>11 <relativePath>"pages/pages/information" <hasDirtyData>false - 'updateNoteText': true - 'updateSelectedNote': true
[16:33:12] [debug] added to history: NoteHistoryItem: <noteName>"filename" <noteSubFolderPathData>"pages\npages\ninformation" <cursorPosition>19 <relativeScrollBarPosition>0
```
</details>

**Comment by pbek** [comment]
Thank you for reporting.
I guess no one ever used this that way. 😅

**Comment by pbek** [comment]
Seems like #1918 still has some issues.

**Comment by pbek** [comment]
## 21.4.3
- fixed the creation of subfolders when clicking a note link that wasn't found
  with a note with subfolders when the current note is also in a subfolder

**Comment by ldv8434** [comment]
Tested and verified working. Thank you!

**Comment by pbek** [comment]
Great, thank you for testing!
