### ISSUE TITLE
Disabled git folder not deleted

### ISSUE THREAD

**Issue by marcoXbresciani** [pbek/QOwnNotes#2109]
When disabling the internal git for notes versioning, the .git folder is not deleted.

#### Expected behaviour
The .git folder should be deleted on disable, or at least emptied.

#### Actual behaviour
Disabling the internal git for notes versioning, the folder and its content remains.

#### Steps to reproduce
Create some notes, with git enabled.
Do something, write notes, save, ...
Disable internal git.

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `gio apr 22 08:58:28 2021`
**Version**: `21.4.3`
**Build date**: `Apr 21 2021`
**Build number**: `829`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 1909`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `yes`
**Settings path / key**: `C:/Users/marco.bresciani/QOwnNotes/Data/PBE/QOwnNotes.ini`
**Application database path**: `C:\Users\marco.bresciani\QOwnNotes\Data\QOwnNotes.sqlite`
**Application arguments**: `C:\Users\marco.bresciani\QOwnNotes\QOwnNotes.exe`, `--after-update`, `C:\Users\marco.bresciani\AppData\Local\Temp\QOwnNotes-vlFvAL-updater.bat`, `--portable`
**Qt Debug**: `0`
**Locale (system)**: `it_IT`
**Locale (interface)**: `it`
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `32`
**Calendar items**: `0`
**Enabled scripts**: `2`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\marco.bresciani\QOwnNotes\Data\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `C:\Users\marco.bresciani\QOwnNotes\Data\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `Kaizen Journal`
**database file**: `C:\Users\marco.bresciani\QOwnNotes\Data\Notes\notes.sqlite`

### Cloud connection ``

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

### Script `Note stats`

**id**: `1`
**path**: `C:\Users\marco.bresciani\QOwnNotes\Data\scripts\note-stats\note-stats.qml`
**variablesJson**: 
```
{
    "charSpaceName": "Chars",
    "readTimeName": "Reading time",
    "readTimeRate": 300,
    "wordsLeftTarget": 0,
    "wordsName": "Words"
}
```
**identifier**: `note-stats`
**version**: `0.0.2`
**minAppVersion**: `17.06.3`

### Script `Meeting note`

**id**: `2`
**path**: `C:\Users\marco.bresciani\QOwnNotes\Data\scripts\meeting-note\meeting-note.qml`
**variablesJson**: 
```
{
    "defaultFolder": "Kaizen Journal",
    "defaultTags": "",
    "headlinePrefix": "",
    "noteBodyTemplate": "<!--\n© 2021 Marco Bresciani\n\nCopying and distribution of this file, with or without modification, are\npermitted in any medium without royalty provided the copyright notice\nand this notice are preserved.\nThis file is offered as-is, without any warranty.\n\nSPDX-FileCopyrightText: 2021 Marco Bresciani\n\nSPDX-License-Identifier: FSFAP\n-->\n# Reflect on the Last Step Taken\n1. What did you plan as your **Last Step**?\n1. What did you **Expect**?\n1. What **Actually Happened**?\n1. What did you **Learn**?\n"
}
```
**identifier**: `meeting-note`
**version**: `1.4.0`
**minAppVersion**: `20.4.16`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**DistractionFreeMode/editorWidthCustom** (QString): `72`
**DistractionFreeMode/editorWidthMode** (QString): `5`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `18`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/ColorSchemes**: *empty*
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-514803c6-84ff-4da5-84a6-26c1989a49bb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (bool): `true`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**LastUpdateCheck** (QDateTime): `2021-04-22T08:40:19.403`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `15`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `doc, Kaizen Journal, Kaizen Journal/2021`
**MainWindow/noteTextEdit.code.font** (QString): `Fira Code,7,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Fira Code,7,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Fira Code,8,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8,-1,5,50,0,0,0,0,0,Normale`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `false`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `false`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `false`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/move-notes** (QString): `16384`
**MessageBoxOverride/remove-notes** (QString): `16384`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QString): `2024-04-13 Reflect on the Last Step Taken`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QString): `Kaizen Journal`
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 117 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `116`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `8`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `true`
**StartHidden** (bool): `false`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `545b1943-b9aa-478d-931b-ab35e773ff4c`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `false`
**enableWebAppSupport** (bool): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `true`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `true`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): `yyyy-MM-dd HH:mm:ss`
**interfaceFontSize** (int): `10`
**interfaceLanguage** (QString): `it`
**internalIconTheme** (bool): `false`
**itemHeight** (int): `15`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `1`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `false`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `5`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `0`
**notesPath** (QString): `Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `true`
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `545b1943-b9aa-478d-931b-ab35e773ff4c`
**restoreCursorPosition** (bool): `false`
**restoreLastNoteAtStartup** (bool): `false`
**restoreNoteTabs** (bool): `false`
**savedSearches/noteFolder-1** (QStringList): `Note 2021-04-22T08.47.32, Note 2021-04-21T16.12.21, Note 2021-04-20T09.20.43, Note 2021-04-20T09.20.30, Note 2021-04-16T11.18.11, Note 2021-04-16T10.39.08, Note 2021-04-15T13.40.43, Note 2021-04-14T10.31.35, Note 2021-04-13T09.03.05, Note 2021-04-13T09.01.44, Note 2021-04-09T08.59.53, Note 2021-04-08T09.01.54, Note 2021-04-08T09.01.31, Note d3496b89-e7ff-4a9d-941b-f254b1c44d5c, Note 2021-04-07T09.50.54, Note 2021-04-01T14.37.08, Note 2021-04-01T14.31.19, Note 2021-04-01T08.40.12, Note 2021-03-31T08.57.26, Note 2021-03-31T08.57.16, Note 2021-03-31T08.56.36, Note 2021-03-30T08.05.24, Note 2021-03-29T10.51.39, Note 2021-03-29T10.26.59, Note 2021-03-29T10.26.21, Note 2021-03-29T10.24.54, Note 2021-03-29T10.20.36, Note 2021-03-29T10.18.52, Note 2021-03-29T09.52.51, Note 2021-03-29T09.42.41, Note 2021-03-29T09.38.46, Note 2021-03-29T09.37.54, Note 2021-03-29T09.37.19, Note 2021-03-29T09.36.40, Note 2021-03-29T09.35.45, Note 2021-03-29T09.35.26, Note 2021-03-29T08.27.33, Note 2021-03-29T08.25.02, Note 2021-03-29T08.24.03, Note 2021-03-29T08.12.05`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Barra degli strumenti principale`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `barra degli strumenti formattazione`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `barra degli strumenti "inserisci"`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `barra degli strumenti di crittografia`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `barra degli strumenti della finestra`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `esci dalla barra degli strumenti`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (bool): `false`
**useSoftWrapInNoteEditor** (QString): `false`
**useUNIXNewline** (bool): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-545b1943-b9aa-478d-931b-ab35e773ff4c/name** (QString): `Configurazione`
**workspace-545b1943-b9aa-478d-931b-ab35e773ff4c/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-545b1943-b9aa-478d-931b-ab35e773ff4c/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `545b1943-b9aa-478d-931b-ab35e773ff4c`

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
QOwnNotes certainly shouldn't remove a `.git` folder (that is managed by git, not by QON) just because git-support in QON is disabled. 😁 
That would scare a lot of people.

**Comment by marcoXbresciani** [comment]
True, but even though it's Git creating its own folder, it's been QON that is using Git. 😉 I mean: it's its own internal usage and it's even hidden from (normal) users, so probably it's fine.

**Comment by pbek** [comment]
QON is using git, yes. But who else is using it? Or was it even there before QON? There are people who even sync their note folder via git (manually or e.g. via https://github.com/muesli/gitomatic/).

**Comment by marcoXbresciani** [comment]
Oky, understood.
