### ISSUE TITLE
Context menu on tray icon sometimes is missing in GTK+ DEs.

### ISSUE THREAD

**Issue by darkshram** [pbek/QOwnNotes#2111]
This is related to issue #812 

#### Expected behaviour

Tray icon in GTK+ DEs should always show right click context menu

#### Actual behavior

Context menu is shown only sometimes in GTK+ based DE. After session is closed and started again, the context menu is gone.

![Captura de pantalla_2021-04-22_14-16-51](https://user-images.githubusercontent.com/10327500/115774690-80aa1d00-a377-11eb-9c23-62aa59d1f2a4.png)

Please, note the icon **is not highlighted** when a right click is done.

Related content in ~/.xsession-errors:

```
Warning: QObject::startTimer: Timers can only be used with threads started with QThread ((null):0, (null))

(wrapper-2.0:26387): LIBDBUSMENU-GLIB-WARNING **: 12:21:31.316: Getting layout failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: No such object path '/NO_DBUSMENU'
```
When context menu appears again, this warning stops appearing in ~/.xsession-errors. But comes back ramdomly after a new GTK+ session is started.

#### Steps to reproduce

1. Start session with Xfce or MATE Desktop
2. Install Qownnotes
3. Enable the tray icon
4. Right click in the Qownnotes tray icon
5. May or may not show the context menu.
6. Close session
7. Start again the same session
8. Context menu of tray icon will not show again.

#### The strange behavior during the writing of this report

After closing and starting again several times Qownnotes to create the report of this issue, context menu came back.
![Captura de pantalla_2021-04-22_14-32-36](https://user-images.githubusercontent.com/10327500/115774852-b5b66f80-a377-11eb-9341-c1a5f3b2755c.png)

Please, note the icon is **now** **highlighted** after a right click.

The ~/.xsession-errors relevant content is the following:

```
Warning: QObject::startTimer: Timers can only be used with threads started with QThread ((null):0, (null))
```

- There were no warnings about dbus-menu.
- After a cold boot, the context menu is gone again, but comes back after several times of closing and start again Qownnotes.

The key to filx this issue is in this warning:
```
(wrapper-2.0:26387): LIBDBUSMENU-GLIB-WARNING **: 12:21:31.316: Getting layout failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: No such object path '/NO_DBUSMENU'
```
The installed dbusmenu-qt5 is 0.9.3-0.25.20160218 (same version as current Fedora and derivative distributions).

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>
## General Info

**Current Date**: `jue. abr. 22 14:24:48 2021`
**Version**: `21.4.4`
**Build date**: `Apr 22 2021`
**Build number**: `830`
**Platform**: `linux`
**Operating System**: `ALDOS 1.4.15 (Librepensador)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `TuxFamily`
**Qt Version (build)**: `5.12.10`
**Qt Version (runtime)**: `5.12.10`
**Portable mode**: `no`
**Settings path / key**: `/home/jbarrios/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/jbarrios/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `es_MX`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `62`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `es_MX`
**Language codes**: `de_AT, de_BE, de_CH, de_DE, de_LI, de_LU, en_US, es, es_AR, es_BO, es_CL, es_CO, es_CR, es_CU, es_DO, es_EC, es_ES, es_GT, es_HN, es_MX, es_NI, es_PA, es_PE, es_PR, es_PY, es_SV, es_US, es_UY, es_VE, fr_BE, fr_CA, fr_CH, fr_FR, fr_LU, fr_MC`
**Language names**: `Österreichisches Deutsch (Österreich), Deutsch (Belgien), Schweizer Hochdeutsch (Schweiz), Deutsch (Deutschland), Deutsch (Liechtenstein), Deutsch (Luxemburg), American English (United States), español de España, español (Argentina), español (Bolivia), español (Chile), español (Colombia), español (Costa Rica), español (Cuba), español (República Dominicana), español (Ecuador), español de España (España), español (Guatemala), español (Honduras), español de México (México), español (Nicaragua), español (Panamá), español (Perú), español (Puerto Rico), español (Paraguay), español (El Salvador), español (Estados Unidos), español (Uruguay), español (Venezuela), français (Belgique), français canadien (Canada), français suisse (Suisse), français (France), français (Luxembourg), français (Monaco)`
**Application dictionaries path**: `/home/jbarrios/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `predeterminado`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/jbarrios/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/jbarrios/Nextcloud/Notes/notes.sqlite`

### Cloud connection `Predeterminado`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `true`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `/home/jbarrios/Escritorio`
**FileDialog/LastPath-NoteHTMLExport** (QString): `/home/jbarrios/Escritorio`
**FileDialog/LastPath-NotePDFExport** (QString): `/home/jbarrios/Escritorio`
**LastUpdateCheck** (QDateTime): `2021-04-22T14:23:52.374`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `25`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Monospace,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Cantarell,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Monospace,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Cantarell,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**MessageBoxOverride/remove-notes** (QString): `16384`
**NoteFolder-1/NoteTabNameList** (QString): `Linphone build order`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 88 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `87`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `true`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `true`
**itemHeight** (QString): `20`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/jbarrios/Nextcloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**recentNoteFolders** (QString): `/home/jbarrios/ownCloud/Notes`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2021-04-13T21.34.31, Note 2021-04-12T17.30.22, Note 2021-04-12T10.11.41, Note 2021-04-09T19.00.02, Note 2021-03-31T02.44.59, Note 2021-01-15T18.14.40, Note 2020-06-22T09.07.36, Note 2020-05-28T11.46.36, Note 2020-05-27T13.52.08, Note 2020-05-26T09.45.32, Note 2020-05-24T16.37.50, Note 2020-05-12T03.10.26, Note 2020-03-04T18.07.00, Note 2019-12-08T02.04.17`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `es_MX`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `barra de herramientas principal`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `barra de formato`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `barra de inserción`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `barra de cifrado`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `barra de ventana`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quitar barra`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Completo`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**IMSETTINGS_INTEGRATE_DESKTOP**: `yes`
**SHELL**: `/bin/bash`
**XDG_CONFIG_DIRS**: `/etc/xdg`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**HISTCONTROL**: `ignoredups`
**XDG_MENU_PREFIX**: `xfce-`
**GTK_IM_MODULE**: `gtk-im-context-simple`
**HISTSIZE**: `5000`
**HOSTNAME**: `joel-rizen5.alcancelibre.org`
**SSH_AUTH_SOCK**: `/tmp/ssh-xrTWIkRzV9ft/agent.2132`
**MODULES_LMCONFLICT**: `python-sphinx/python3-sphinx&python-sphinx`
**_LMFILES__modshare**: `/usr/share/modulefiles/python-sphinx/python3-sphinx:1`
**XMODIFIERS**: `@im=none`
**DESKTOP_SESSION**: `xfce`
**SSH_AGENT_PID**: `2322`
**GTK_MODULES**: `canberra-gtk-module`
**XDG_SEAT**: `seat0`
**PWD**: `/home/jbarrios`
**XDG_SESSION_DESKTOP**: `xfce`
**LOGNAME**: `jbarrios`
**XDG_SESSION_TYPE**: `x11`
**MODULESHOME**: `/usr/share/Modules`
**MANPATH**: `:`
**XAUTHORITY**: `/var/run/lightdm/jbarrios/xauthority`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/jbarrios`
**GDM_LANG**: `es_MX.utf8`
**HOME**: `/home/jbarrios`
**SSH_ASKPASS**: `/usr/libexec/openssh/lxqt-openssh-askpass`
**LANG**: `es_MX.utf8`
**XDG_CURRENT_DESKTOP**: `XFCE`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**IMSETTINGS_MODULE**: `none`
**PATH_modshare**: `/bin:1:/usr/sbin:1:/lib/upstart:1:/usr/bin:1:/usr/local/sbin:1:/usr/libexec/python3-sphinx:1:/usr/share/Modules/bin:1:/usr/lib64/ccache:1:/usr/local/bin:1:/sbin:1`
**MODULEPATH_modshare**: `/usr/share/modulefiles:1:/usr/share/Modules/modulefiles:1:/etc/modulefiles:1`
**LOADEDMODULES_modshare**: `python-sphinx/python3-sphinx:1`
**TERM**: `dumb`
**LESSOPEN**: `||/usr/bin/lesspipe.sh %s`
**USER**: `jbarrios`
**MODULES_RUN_QUARANTINE**: `LD_LIBRARY_PATH LD_PRELOAD`
**PAM_KWALLET5_LOGIN**: `/var/run/user/1000/kwallet5.socket`
**LOADEDMODULES**: `python-sphinx/python3-sphinx`
**MODULES_LMCONFLICT_modshare**: `python-sphinx/python3-sphinx&python-sphinx:1`
**SHLVL**: `0`
**QT_IM_MODULE**: `xim`
**XDG_VTNR**: `1`
**XDG_SESSION_ID**: `4`
**XDG_RUNTIME_DIR**: `/var/run/user/1000`
**S_COLORS**: `auto`
**KDEDIRS**: `/usr`
**GTK3_MODULES**: `xapp-gtk3-module`
**XDG_DATA_DIRS**: `/home/jbarrios/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/usr/share`
**PATH**: `/usr/libexec/python3-sphinx:/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/lib/upstart:/home/jbarrios/.local/bin:/home/jbarrios/bin:/sbin:/usr/sbin:/home/jbarrios/.local/bin:/home/jbarrios/bin:/home/jbarrios/.local/bin`
**MODULEPATH**: `/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles`
**GDMSESSION**: `xfce`
**_LMFILES_**: `/usr/share/modulefiles/python-sphinx/python3-sphinx`
**DBUS_SESSION_BUS_ADDRESS**: `unix:abstract=/tmp/dbus-681hZfGN7K,guid=639eb6407323fed5e766d19e6080fe03`
**MAIL**: `/home/jbarrios/Maildir`
**MODULES_CMD**: `/usr/share/Modules/libexec/modulecmd.tcl`
**BASH_FUNC_ml%%**: 
```
() {  module ml "$@"
}
```
**BASH_FUNC_switchml%%**: 
```
() {  typeset swfound=1;
 if [ "${MODULES_USE_COMPAT_VERSION:-0}" = '1' ]; then
 typeset swname='main';
 if [ -e /usr/share/Modules/libexec/modulecmd.tcl ]; then
 typeset swfound=0;
 unset MODULES_USE_COMPAT_VERSION;
 fi;
 else
 typeset swname='compatibility';
 if [ -e /usr/share/Modules/libexec/modulecmd-compat ]; then
 typeset swfound=0;
 MODULES_USE_COMPAT_VERSION=1;
 export MODULES_USE_COMPAT_VERSION;
 fi;
 fi;
 if [ $swfound -eq 0 ]; then
 echo "Switching to Modules $swname version";
 source /usr/share/Modules/init/bash;
 else
 echo "Cannot switch to Modules $swname version, command not found";
 return 1;
 fi
}
```
**BASH_FUNC_module%%**: 
```
() {  unset _mlshdbg;
 if [ "${MODULES_SILENT_SHELL_DEBUG:-0}" = '1' ]; then
 case "$-" in 
 *v*x*)
 set +vx;
 _mlshdbg='vx'
 ;;
 *v*)
 set +v;
 _mlshdbg='v'
 ;;
 *x*)
 set +x;
 _mlshdbg='x'
 ;;
 *)
 _mlshdbg=''
 ;;
 esac;
 fi;
 unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" -a "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "`eval 'echo ${'$_mlv'+x}'`" ]; then
 _mlre="${_mlre:-}${_mlv}_modquar='`eval 'echo ${'$_mlv'}'`' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='`eval 'echo ${'$_mlrv':-}'`' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 eval `eval ${_mlre} /usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl bash '"$@"'`;
 else
 eval `/usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl bash "$@"`;
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 if [ -n "${_mlshdbg:-}" ]; then
 set -$_mlshdbg;
 fi;
 unset _mlshdbg;
 return $_mlstatus
}
```
**SESSION_MANAGER**: `local/unix:@/tmp/.ICE-unix/2132,unix/unix:/tmp/.ICE-unix/2132`
**PANEL_GDK_CORE_DEVICE_EVENTS**: `0`
**DISPLAY**: `:0.0`
</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>
[14:28:02] [status] No se encontraron actualizaciones de script
</details>

**Comment by pbek** [comment]
I wonder if you have the same issue when you use the AppImage, Snap or Flatpak version of QOwnNotes.
Do you have the issue also with other Qt applications?
Do you have the issue if you run QON in a new session (`--session` parameter)?

**Comment by darkshram** [comment]
No, is the only Qt application with this issue. As you can see in #812, it's something that has been around for a few years, and other users also confirmed it. I recently switched from MATE (1.24) to Xfce (4.16) and re-discovered this issue after enabling again the tray icon. Since I supposed it was a MATE Panel issue, just gave up using the tray icon until recently.

If I use `--session` right, context menu works if there was a previous session with context menu. Will make a few tests after a reboot and report findings later launching Qownnotes with two sessions. Also will make a few tests with AppImage tomorrow.

When context menu of the tray icon is fails, two things happen:

1. Right click does not highlight Qownnotes icon.
2. Shows this warning in ~/.xsession errors:
```
(wrapper-2.0:26387): LIBDBUSMENU-GLIB-WARNING **: 12:21:31.316: Getting layout failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: No such object path '/NO_DBUSMENU'
```
Obviously is related to dbusmenu on GTK+ DEs. Works perfectly in Plasma and LXQt.
