### ISSUE TITLE
CalDAV server configuration issue

### ISSUE THREAD

**Issue by amigo421** [pbek/QOwnNotes#2114]
an attempt to configure the tasks:

![image](https://user-images.githubusercontent.com/3259933/116081931-80758e80-a6a3-11eb-9fa0-eb83bf29b988.png)

the list of calendars is empty. "reload" button does no effect as well. 

the same credentials work fine with other apps , e.g. with emClient, it loads available tasks lists successfully 

debug log looks so:

> [Apr 26 14:56:54] [debug]: Set proxy configuration to use NO proxy
> [Apr 26 14:57:01] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
> [Apr 26 14:57:01] [debug]: Reply from  ""

**Comment by pbek** [comment]
Are those all log entries?
And can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.

Usually those caldav urls are a bit deeper, not only a host. Like for Nextcloud for example: `https://your.domain.com/remote.php/dav/calendars/yourusername/`

**Comment by amigo421** [comment]
there are two equal groups of messages in the log from my two attempts,

regarding the url, I used the same for emClient and for tasks.org (android) , also confirmed with my service documentation, 
![image](https://user-images.githubusercontent.com/3259933/116084406-71441000-a6a6-11eb-8abb-17f8653f2927.png)
about debug settings - let me perform a couple more tests and I'll describe this all together with the settings in next comment

**Comment by amigo421** [comment]
@pbek sent you on email (to prevent sharing private info here)

**Comment by wilbowma** [comment]
Getting the same issue. 

<details><summary>Some snippets from the debug info:</summary>

## Cloud connections
## General Info

**Current Date**: `Fri. May 7 22:54:41 2021`
**Version**: `21.5.1`
**Build date**: `May  8 2021`
**Build number**: `834`
**Platform**: `linux`
**Operating System**: `Manjaro Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/path/to/.config/PBE/QOwnNotes.conf`
**Application database path**: `/path/to/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breath2`
**Notes in current note folder**: `4`
**Calendar items**: `0`
**Enabled scripts**: `0`
### Cloud connection ``

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

</details>

<details><summary>Config screenshot</summary>

![image](https://user-images.githubusercontent.com/1133598/117528499-7b5bed80-af87-11eb-8359-c85b9f7f4618.png)

</details>

**Comment by wilbowma** [comment]
I've worked around the issue by appending my username to the caldav path. Instead of `https://caldav.*****.com`, I enter `https://caldav.***.com/user`, in addition to entering my username as normal for authentication.

This may be a result of differences between CalDAV servers. I'm using Radicale 2. I'll try to post some debugging information, as my server does work with other CalDAV clients suggesting some minor issue with the QOwnNotes client.

**Comment by pbek** [comment]
Maybe other clients are trying to guess the real url if the user didn't enter it correctly. QOwnNotes doesn't guess your real caldav url.

**Comment by amigo421** [comment]
okay , I'll also try to extract full url for my service
