### ISSUE TITLE
Pressing Caps with caps:swapescape in vim mode does not exit insert mode.  

### ISSUE THREAD

**Issue by sohamshanbhag** [pbek/QOwnNotes#2119]
#### System information

OS: Ubuntu 20.10
QOwnNotes version: version 21.4.6 - Launchpad PPA - build 832

#### Expected behaviour

Pressing Caps Lock should escape insert mode.

#### Actual behaviour

Pressing Caps Lock enables inputting uppercase characters in insert mode.

#### Steps to reproduce

Enable caps:swapescape by adding caps:swapescape to the XKBOPTIONS in /etc/default/keyboard. After modification the line should like the following

    XKBOPTIONS="caps:swapescape"

Enable vim mode. Press i to enter insert mode, press caps to (try to) exit insert mode.

#### Additional Information

This behaviour is shown in the QOwnNotes installed using the ppa on ubuntu, the flatpak version behaves correctly, i.e. Caps Lock behaves as Escape Key.

**Comment by pbek** [comment]
> Pressing Caps Lock should escape insert mode.

I'm not sure if or how Qt detects that or even should. And I don't know why the (3rd party) Flatpak version behaves that way.
Maybe you need to install some input method directly in Ubuntu for that to work and Flatpak has installed that in its confinement.

**Comment by sohamshanbhag** [comment]
It seems that the erroneous behaviour is present even without vim mode. Pressing Caps Lock allows entering uppercase characters in normal mode too. However, calibre, which is also a Qt based application, behaves correctly.

**Comment by pbek** [comment]
If you have any insight on how to teach Qt that trick, please let me know. 😉 
https://github.com/kovidgoyal/calibre/search?q=XKBOPTIONS or https://github.com/kovidgoyal/calibre/search?q=swapescape had nothing in store for me. Quick googleing didn't help neither...

**Comment by sohamshanbhag** [comment]
It seems that on my system (default ubuntu) the qtwayland5 package was not installed. Since I'm using sway, the application installed using ppa was using xwayland(i.e. running under Xorg) while the flatpak version was using wayland. Installing qtwayland5 solves this problem!

I'll close this issue.

**Comment by pbek** [comment]
That was my first suspicion, but you said that it works in Calibre.
