### ISSUE TITLE
Markdown property of first character of ordered list item applied to list number

### ISSUE THREAD

**Issue by sohamshanbhag** [pbek/QOwnNotes#2120]
#### Steps to reproduce

Open new note
Type:

    1. *Italic* text
    2. **Bold** text
    3. ~Strikethrough~ text
    4. Normal text

#### Expected behaviour

List items are not applied markdown property.

1. *Italic* text
2. **Bold** text
3. ~Strikethrough~ text
4. Normal text

#### Actual behaviour

List items are applied markdown property of first character of list

*1.* *Italic* text
**2.** **Bold** text
~3.~ ~Strikethrough~ text
4. Normal text

Check Preview Pane/Export to pdf

Edit: I'm not sure if this is the intended behaviour. If it is, please include it in the markdown cheatsheet

**Comment by pbek** [comment]
The generated HTML says:

```html
<ol>
<li><em>Italic</em> text</li>
<li><strong>Bold</strong> text</li>
<li><s>Strikethrough</s> text</li>
<li>Normal text</li>
</ol>
```

...which is all right.
That makes it one of many quirks of Qt's `QTextBrowser`... 😅

**Comment by sohamshanbhag** [comment]
Yep, now that I check it, this bug is present [https://bugreports.qt.io/browse/QTBUG-57833](upstream), and has been brought up in this repository too. I may have missed that issue when I searched if this bug had been reported previously. Great work with the application! 

I'll close this issue here.

**Comment by pbek** [comment]
Thank you! 😁
