### ISSUE TITLE
a bug with the "splitting option" 

### ISSUE THREAD

**Issue by mlaarebi** [pbek/QOwnNotes#2124]
I used the "splitting option" (in the extras menu) to split a note to several ones. It worked for the first 4 or 5 notes, but then it just erased the original note with all the information in it. 

The notes generated from the original one weren't removed, only the original one. I looked for it in the trash and in other folders but couldn't find it. It seems the note was rewritten instead of being split.

**Comment by pbek** [comment]
That shouldn't happen.
Can you reproduce this behavior on your system?

**Comment by pbek** [comment]
I just did a lot of splitting and never lost any part of the notes.
