### ISSUE TITLE
Unnecesarry space between the last list item and subitems

### ISSUE THREAD

**Issue by Yoshua-chan** [pbek/QOwnNotes#2125]
In preview QON renders ordered and unordered list in a way, that creates an empty space between a list item and it's subitems if the main item is the last item in a list. 

#### Steps to reproduce
put something like this into your note 
```markdown
## Unordered list
- item 1
  - sub 1
  - sub 2
  - sub 3
- item 2
  - sub 1
  - sub2
  - sub3

## Ordered list
1. item 1
    1. sub 1
    1. sub 2
    1. sub 3
1. item 2
    1. sub 1
    1. sub 2
    1. sub 3

```

#### Actual behaviour
As you can see in the image below, the items of the sublist has empty space if the item containing the sublist is the last item in a list
![list](https://user-images.githubusercontent.com/31251884/116825520-fab87e00-ab8f-11eb-9a4e-f0b76233f7d9.png)

However if you put an item to the main list after `item 2`, the spacing doesn't appear anymore, as shown below

![list2](https://user-images.githubusercontent.com/31251884/116825553-1facf100-ab90-11eb-9d05-b7590e0f0ba9.png)

#### Expected behaviour
There should never be additional space between an item on a list and its subitems

**Comment by pbek** [comment]
Are we talking about #168?

**Comment by Yoshua-chan** [comment]
It seems like it, I couldn't find it searching throught the issues.

**Comment by pbek** [comment]
Sadly it's an old issue and still not fixed in QTextBrowser.
I'll close this then.

**Comment by Yoshua-chan** [comment]
I found a workaround, if you put another `-` or number in the list with no content like this,
```markdown 
## Unordered list
- item 1
  - sub 1
  - sub 2
  - sub 3
- item 2
  - sub 1
  - sub2
  - sub3
-

## Ordered list
1. item 1
    1. sub 1
    1. sub 2
    1. sub 3
1. item 2
    1. sub 1
    1. sub 2
    1. sub 3
1. 
```
then the spacing disappears, and the number/bullet points don't render if there's no text. 

![listfixed](https://user-images.githubusercontent.com/31251884/116867629-cc798380-ac0d-11eb-951e-b845c3554688.png)

Sadly even though it works in QON, Nextcloud still renders it, so if you're sharing a note then those empty items are visible.

**Comment by pbek** [comment]
Yes, this should be fixed in QTextBrowser directly...
