### ISSUE TITLE
[Feature] Add shortcut to switch between editor and preview within the same workspace

### ISSUE THREAD

**Issue by Redsandro** [pbek/QOwnNotes#2132]
### Feature description

QOwnNotes has a very customizable workspace, good for a variety of preferences and advanced needs.

There is one hard limitation however: These workspaces are static, and it is becoming increasingly more popular and time saving to be able to dynamically toggle between the edit panel and the preview panel _within the same workspace,_ so you can tweak the widgets on the fly and still toggle between editing and preview.

Here is an example from Boostnote. Notice how easy it is to resize/toggle/enable widgets on the fly while still being able to switch between edit and preview.

![Peek 2021-05-09 21-43](https://user-images.githubusercontent.com/1702193/117584905-e33d4000-b10f-11eb-85af-c0bd0bdb3bd2.gif)

> **Note:** Boostnote also has a dual pane mode for classic note editing.

### What problem does it solve

This allows for a more natural note editing process. This negates the need for a [workaround](https://github.com/pbek/QOwnNotes/issues/2132#issuecomment-836003797) that hinges on maintaining two virtual workspaces for every actual workspace you want, and removes the learning curve and setup time experienced by new users. 

In fact, you don't have to learn about workspaces until you need them for advanced use cases. Since editing and viewing are now exchangeable, you can semantically simplify the preset workspaces/layouts:

- Minimal (vertical)
- Basic
- Advanced
- Advanced (dual pane)

---

(This issue has been rewritten to a feature request after learning the feature did not exist)

**Comment by pbek** [comment]
In QOwnNotes there simply are workspaces and no preview/edit view. You can use (or setup) a workspace that includes the preview panel and the edit panel. Or you can have different workspaces for edit and preview panel and switch between them. You can even script the workspace switching...

**Comment by pbek** [comment]
There also is a shortcut to switch between the last two workspaces...

**Comment by Redsandro** [comment]
The issue with switching workspaces is that any change has to be made twice. Can _"replace edit panel with preview panel or vice versa"_ also be scripted?

**Comment by Redsandro** [comment]
Not exactly. I would like to have one workspace where I can use a script to replace the edit panel with the preview panel within that workspace (see the edit in my previous comment). This way, I can have and maintain one single workspace as if there are no workspaces at all, as if I'm using a simple app like Boostnote (example below). Otherwise every time I add or remove or move or resize a widget, the interface jumps, and I'd have to make the exact same modifications to the other workspace.

I have been looking around in the scripts repository but I'm not acquainted to this language and to what level it can control the app.

![Peek 2021-05-09 21-43](https://user-images.githubusercontent.com/1702193/117584905-e33d4000-b10f-11eb-85af-c0bd0bdb3bd2.gif)

**Comment by pbek** [comment]
Workspaces are exactly for that. They are switching panels on and off (and move them around if you said so).

**Comment by Redsandro** [comment]
I think we misunderstand each other. I don't manage to do what I show above in QOwnNotes. In QOwnNotes, after changing the view workspace, switching to the editor workspace now switches back to an outdated workspace that doesn't contain the alteration I just made. I have to do everything twice. In both workspaces. This way, QOwnNotes gets in the way of my process.

For QOwnNotes to get out of the way, it would need to switch the preview _panel_ (not the workspace) to the editor panel. I understand this is not possible. Would you consider implementing this if I make a feature request?

In the meantime and/or alternatively, I'm trying to gauge if scripts have the power to _simulate_ that behavior by switching one panel off and the other panel on. Could you tell me if it's possible through scripting to literally do that:

```
IF panel.edit == VISIBLE XOR panel.preview == VISIBLE:
    IF panel.edit == VISIBLE:
        SHOW panel.preview
        HIDE panel.edit
    ELSE:
        SHOW panel.edit
        HIDE panel.preview
```

**Comment by proazr** [comment]
@Redsandro - so I've had a similar need, and here's how I have managed to get it working.

1. Create 2 workspaces named Editor & Viewer
2. Switch to the Editor workspace
3. Unlock panels and organize / position them per your liking - this step took me a while, and I ended up really liking my final setup - tags panels at the bottom, notes panels on the left, tags & outline panels on the right. Notice that there's no preview panel here. See the first screenshot below (Editor Workspace)
4. Switch to the Viewer workspace and organize the panels similar to the Editor workspace - the only change here is that we'll be adding the Preview panel in the center, and moving the Editor panel all the way towards the right edge while making it as narrow as possible - this step would be a slight compromise since it isn't possible to hide the Editor panel.
5. Lock the panels
6. Switch b/w Editor & Viewer workspaces using Alt + Shift + P

---

## Editor Workspace:

![image](https://user-images.githubusercontent.com/51807907/117593143-14fed880-b109-11eb-8c3a-3192264c7725.png)

## Viewer Workspace:

![image](https://user-images.githubusercontent.com/51807907/117593167-2ba52f80-b109-11eb-8035-6f76838e0f05.png)

**Comment by pbek** [comment]
@proazr, thank you for the tutorial! 😉 

> this step would be a slight compromise since it isn't possible to hide the Editor panel.

you can disable it if you turn off (in the settings) that it is the central widget

**Comment by Redsandro** [comment]
@proazr commented:

> @Redsandro - so I've had a similar need, and here's how I have managed to get it working.

I appreciate the step by step. Thank you! This workaround works great on my desktop. 

On my 13 inch laptop however, I work a bit at home and a bit at the office where I plug in a big monitor. It's only now I'm trying out QOwnNotes that I realize how often I resize widgets to accommodate changing screen size.

Using the same workaround, I made 4 workspaces. 2 for the big screen and 2 for the laptop screen. When I switch monitors, I select the 3rd workspace, and then the 4th workspace, and then use Alt+Shift+P for the rest of the day. Less ideal, but still happy to try this new approach.

But when I disconnected the laptop to take it to the monday meeting, I had to do the 4 clicks again. And back to my desk, again. The day isn't over, but QOwnNotes is still getting in the way because of this.

For that reason, I think it would be really helpful, and a good idea in general, to have a dedicated function in QOwnNotes, which can be attached to a custom keyboard shortcut, that switches out the preview and the code editor when only one of them is visible. /cc @pbek 

__Why add an option to switch `editor` <-> `preview`?__

1. Users don't need to learn about a workaround;
1. Conforms to [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) without impacting existing workflows;
1. You won't have to explain the concept of workspaces to new users;
1. Users won't be discouraged from changing the workspace by having to make an exact replica in the workaround workspace;
1. The default shortcut can be mentioned in the welcome note, closing this issue; :wink: 
1. New users less patient than I won't ditch QOwnNotes when they can't figure out how to switch between preview and editor.

**Comment by pbek** [comment]
In the beginning there were not workspaces and panels. But then every user wanted to define their own layout and I have to implement a lot of settings for them... So I switched to panels. Then users wanted to switch between different panel configurations, so I created workspaces (that are also scriptable)... To help new users you can choose a predefined layout when you setup QOwnNotes (and later in the settings) which creates a workspace.

The only thing missing is a single place with documentation on how to use workspaces effectively and bend them to your (very personal) needs.

**Comment by Redsandro** [comment]
Please note that I am not saying ditch workspaces. The workspaces are valuable. I think they become more valuable the longer you use QOwnNotes.

There is just one thing missing. It is relatively simple. They can't switch/toggle editor/preview within one workspace. Add that, and you're feature complete.

I did my best to work with QOwnNotes using a different workflow, and I think I explained well why this would be beneficial. Can you explain why you are reluctant to consider this feature?

**Comment by pbek** [comment]
It starts with that you cannot even turn off the edit panel without turning off the central widget support (see settings) and most of the people don't want that (because of the consequences, see settings) and use a view a with preview and edit screen together anyway.

**Comment by Redsandro** [comment]
> It starts with that you cannot even turn off the edit panel without turning off the central widget support

You mean this, right?
![image](https://user-images.githubusercontent.com/1702193/117675971-62348600-b1ad-11eb-9f21-9b5dee235ccd.png)

![image](https://user-images.githubusercontent.com/1702193/117676139-90b26100-b1ad-11eb-8766-09e82e233c7a.png)

If you're asking how to solve this problem, then my initial thoughts are:

- using the proposed editor/preview toggle should automatically turn off Central Widget Support for the editor panel; or
- implement central widget support for the preview panel as well; or
- place both the editor and the preview in a container widget and make that container the Central Widget Support. When toggling between them, the container stays taking up central space.

After all I can do this:

Window > Panel > Show Edit Panel
Window > Panel > Hide Edit Panel

And if that could be done programmatically, we're set.

> most of the people don't want that and use a view a with preview and edit screen together anyway.

Now you're saying something that I understand. :smile: 
I thought that you didn't really understand me, so I went on. But you don't think enough people care about this for it to be worth the effort. I'm not sure I agree, but say no more! I will let it go.

**Comment by Redsandro** [comment]
I had no idea it would be such a hassle. It feels so simple, as long as you don't use Central Widget Support (which I don't). An editor/preview toggle and the Central Widget Support option could be mutually exclusive to circumvent the hassle. But I promised I would let it go!

Just as a final thought, consider that the impression that _"most people don't want that"_ is based on flawed metrics because the option is not available in QOwnNotes so the demand is not measurable. I'd hypothesize that there are many people who _would_ like this, but apart from patient heroes like @proazr, they quickly move on to apps like Boostnote (17k stars), Mark Text (18k stars), Typora (closed source) and such after noticing QOwnNotes (2k stars) can't do this. Judging from their popularity, it might just be what people _in general_ want. Perhaps not existing QOwnNotes users though.

For what it's worth, I prefer QOwnNotes for many advanced features. I think it's the most advanced file-based markdown editor out there. So many features begging to be used.

But _"getting out of the way and letting me write"_ is the single most important thing to me. Of course I'm willing to compromise to a point, but maintaining two virtual workspaces for each actual workspace as a workaround and doing 4 clicks every time I want to switch is just not that. 

One note taking app that gets out of the way really good is [Mark Text](https://github.com/marktext/marktext). The edit and preview are the same! But it is _not_ WYSIWYG. :open_mouth: It's like every paragraph is a mini-editor. If Mark Text and QOwnNotes got married and had a kid, I'd want that kid as my note taking app.

I'll switch back to Boostnote or Mark Text for now, but I will be back in 4 years! :stuck_out_tongue_winking_eye:

**Comment by pbek** [comment]
QOwnNotes is for people with "special needs", like the need for a maximum of customization, low memory and cpu footprint or the need to have an app that is very un-opinionated about how note files have to look.

**Comment by Redsandro** [comment]
I will reopen this as a feature request (and edit the first post) to give people an opportunity to indicate interest through thumbs up, but feel free to ignore this until there is reason not to. :smile:
