### ISSUE TITLE
Tags get removed when split note is renamed 

### ISSUE THREAD

**Issue by proazr** [pbek/QOwnNotes#2133]
Hi @pbek! 

I noticed that when I have a note with tags and I split the note, it creates a second note with the tags retained. However, when I rename this split note, the tags get removed and the link to the split note in the original note shows up as broken. 

I am not sure if this is by design or not. 

#### Expected behaviour
It would be nice to have the tags get retained after the split note is renamed, and also have the link in the original note automatically update to point to the renamed split note. 

#### Actual behaviour
Upon renaming the split note, tags get removed and the link in the original note displays (and behaves) as broken.

#### Steps to reproduce
1. Create a note with some text
2. Position cursor at any position within the text 
3. Right click and select split note at cursor position or use the keyboard shortcut Alt + Shift + x
4. Notice that the split note has all the tags that were applied to the original note
5. Now rename the split note's header 
5. Save the split note
6. Notice that the tags disappear and the link in the original note is broken

Thank you!

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Hi, I couldn't reproduce this behavior. After I have renamed the split note the tags in that 2nd note were still present.

Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.
Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting Debug in Options).

Do you have the same behavior when you rename any other note with a tag?
