### ISSUE TITLE
Update fakevim

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#2134]
@Waqar144, I was trying to update https://github.com/pbek/FakeVim to latest from https://github.com/hluk/FakeVim.
I had to resolve some merge conflicts, but it didn't even build with cmake... And the qmake support was removed upstream. 😬

**Comment by Waqar144** [comment]
Yes, we need to reintroduce qmake support ourselves I guess.

I think instead of merging we can just replace the code and do the necessary fixes. Not sure how easy/hard it would be or even possible.

**Comment by pbek** [comment]
Do as you please. 😅

**Comment by pbek** [comment]
## 21.6.7
- the fakevim library was updated and adapted to work with qmake and cmake and integrated
  into QOwnNotes (for [#2134](https://github.com/pbek/QOwnNotes/issues/2134), thank you @Waqar144)

**Comment by pbek** [comment]
@Waqar144, @joshmorel, @sohamshanbhag, @Yoshua-chan

There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
@Waqar144, a lot o builds are failing on https://build.opensuse.org/package/show/home:pbek:QOwnNotes/desktop

**Comment by pbek** [comment]
@Waqar144, our AppVevor build for Windows XP is failing too!
https://ci.appveyor.com/project/pbek/qownnotes/builds/39766719

**Comment by pbek** [comment]
@Waqar144, our Ubuntu Launchpad build for Xenial also already failed: https://launchpadlibrarian.net/545715087/buildlog_ubuntu-xenial-amd64.qownnotes_21.6.7-1ubuntu3ppa1~xenial1_BUILDING.txt.gz

**Comment by Waqar144** [comment]
Yep, that is expected. Will take a while to get through all that ;)

**Comment by pbek** [comment]
@Waqar144, some builds on https://build.opensuse.org/package/show/home:pbek:QOwnNotes/desktop are still failing. 😅

**Comment by pbek** [comment]
AppVeyor and Launchpad went through! Great job on those! 👍🏻 😁

**Comment by Waqar144** [comment]
I will fix the AppImage build.

For the rest, I am sorry, I no longer have the time or motivation to support anything below Qt 5.9. That is what we have here in the CI and hence it is easy to check for build failures.

**Comment by pbek** [comment]
> I will fix the AppImage build.

That'd be great!
I'll see about the rest then.

For some reasons I also saw quite some usage from openSUSE 13.2 in Matomo. That's Qt 5.3, that's what I'd consider calling "ancient"...

**Comment by Waqar144** [comment]
People will keep being lazy. I am on Cent OS 7, that's very old, but has Qt 5.9 available.

> For some reasons I also saw quite some usage from openSUSE 13.2 in Matomo.

I would be surprised if anyone else is writing or updating anything over there. That's a completely dead distro since 5 years. There's no need to support it at all.

For normal distros, supporting old fedoras especially is pointless, people not upgrading over there are at fault themselves.

Another suggestion, just branch out for older versions and backport any important fixes. The rest of the code base can keep going forward and will not need to turn into a mess of #ifdefs and dirty workarounds all over the place.

**Comment by pbek** [comment]
> I would be surprised if anyone else is writing or updating anything over there. That's a completely dead distro since 5 years. There's no need to support it at all.

Could also be a corporate installation.
My main issue with the AppImage is that you can't update it easily. It would take a lot of effort to write an updater for the AppImage and those updater are always kind of brittle if anything isn't working (e.g. like with the ssl library under Windows after a Qt update).

> Another suggestion, just branch out for older versions and backport any important fixes. The rest of the code base can keep going forward and will not need to turn into a mess of #ifdefs and dirty workarounds all over the place.

CLion by default hides all code paths that will not be executed on the local system. 😆 
Keeping a different branch would be even more work imho and we'd reconsider the whole OBS publishing because there need to be different sources to build from, so there would need to be different OBS projects with repositories...

I'm really torn apart in that regard...

**Comment by pbek** [comment]
And the AppImage only works on 64bit x86!

**Comment by pbek** [comment]
And I wonder what Qt version https://code.launchpad.net/~pbek/+snap/qownnotes is using with Canonical's *Ubuntu Core 16*.

**Comment by Waqar144** [comment]
I don't think people using such old distros would even care or notice if QON stopped updating for them given they know they are living in a non-supported dead distro.

The AppImage doesn't need to be updated, it can just be replaced. 

Even if CLion hides the branches, 
- not everyone uses CLion
- it doesn't and can't hide the workarounds

Disabling is a bad idea imo. You will now have different branches in the config and other places for older Qt versions. That's more work. Old QON versions will still be there if people want to use it. 

For 32 bit x86, is that even a thing anymore? If anything isn't supported by AppImage, I would consider it very much dead given they go to great lengths to support old operating systems. 

In any case, you are the owner, so it's upto you.

**Comment by pbek** [comment]
> I don't think people using such old distros would even care or notice if QON stopped updating for them given they know they are living in a non-supported dead distro.

Ubuntu 14.04 (that we didn't even support officially because Qt < 5.3) has EOL April 2022!
Ubuntu 16.04 has EOL April 2024.

> The AppImage doesn't need to be updated, it can just be replaced.

yes, but that's a manual process... I spend a huge amount of time to write update scripts for Windows and macOS to get around the manual process.

> not everyone uses CLion

I very well know that you don't use Clion, I was just kidding you 😁 

> Disabling is a bad idea imo.

Why?

> You will now have different branches in the config and other places for older Qt versions

What different branches in the config? And what config? The ini (and other) files?

> For 32 bit x86, is that even a thing anymore? 

Note to self: We need some architecture stats... We don't have those yet.
I'm talking about ARM and other architectures.

> If anything isn't supported by AppImage, I would consider it very much dead given they go to great lengths to support old operating systems.

I haven't seen ARM AppImages yet, but snap is supporting other archtectures and I'm not sure about flatpak. Native distro support is always the best integrated experience...

> In any case, you are the owner, so it's upto you.

I don't want to revert your PRs just because they break some old Qt version. 😬  I'd rather do "graceful degradation" of those features you touched if they weren't essential.

**Comment by Waqar144** [comment]
> Ubuntu 14.04 (that we didn't even support officially because Qt < 5.3) has EOL... 

Not according to https://help.ubuntu.com/community/EOL

Disabling is a bad idea because we are intentionally breaking the app. And by config, I mean our settings. We will have conditional compilation or something to disable those features. Oh and vim is just one thing, you can't do that for core features which is already riddled with tons of ifdefs and other things. 

AppImage is native more or less I think, snap/flatpak are a bit different. I am pretty sure you can create and run an AppImage on a raspberry pi.

**Comment by Waqar144** [comment]
As I said, I no longer have the time or motivation to support abandoned Qt versions. You are the owner of the project, if you want to support older versions or not allow PRs that don't have support for older versions, that's up to you.

**Comment by pbek** [comment]
> Not according to https://help.ubuntu.com/community/EOL

Strange, https://wiki.ubuntu.com/Releases told me differently.

> Disabling is a bad idea because we are intentionally breaking the app. 

You mean because if it is discontinued then at least the old state works (as long no things need to change because things around QON change). I dunno, outside things change and need adaptation.

> I am pretty sure you can create and run an AppImage on a raspberry pi.

I'm not sure if it even would work. And you can't do that in GitHub or OBS and there are more (also ARM) architectures we currently support.

**Comment by pbek** [comment]
> I no longer have the time or motivation to support abandoned Qt versions.

I can understand that!

**Comment by pbek** [comment]
> Note to self: We need some architecture stats... We don't have those yet.

I found out we already have that. Lots or different ARM users, still some i386, no power/mips/sparc.

**Comment by pbek** [comment]
@Waqar144, it looks now like all OBS builds went through! Thank you very much!

Btw. I just managed to get a Ubuntu 16.04 GitHub build-test action with Qt 5.5.1 running!

**Comment by Waqar144** [comment]
Cool, finally!
