### ISSUE TITLE
[F] Highlight items in the navigation panel according to the position of the cursor

### ISSUE THREAD

**Issue by fabianski7** [pbek/QOwnNotes#2136]
#### Expected behaviour
Navigation panel items could be highlighted depending on the location of the mouse cursor.

<details><summary>Screenshot</summary>

![ksnip_tmp_xEasJs](https://user-images.githubusercontent.com/47755037/117728936-a50c5300-b1d9-11eb-9bc4-038d0691423c.png)

</details>

#### Actual behaviour
Currently they are already highlighted with a nice effect, but this only happens when items in the panel are clicked, the editor is ignored.

<details><summary>Screenshot</summary>

![ksnip_tmp_fswFwT](https://user-images.githubusercontent.com/47755037/117728996-b81f2300-b1d9-11eb-8328-110a397a16ec.png)

</details>

#### Additional information
I saw this behavior in the new version of the ghostwriter, and it really helps navigating large files. Since QON is an AIO solution for markdown, it would be great to have that here too 😅

https://user-images.githubusercontent.com/47755037/117729702-c1f55600-b1da-11eb-9e88-dc5828ec7dc9.mp4

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

```
**Version**: `21.4.6`
**Build date**: `Apr 26 2021`
**Build number**: `832`
**Platform**: `linux`
**Operating System**: `Arch Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
```
</details>

**Comment by fnkhz** [comment]
@pbek Do you think it would be a good idea to implement this as a script ?
I would like to start working on extending the scripting framework for this.

**Comment by pbek** [comment]
## 22.1.8
- items in the navigation panel are now highlighted according to the position of
  the cursor in the note edit panel (for [#2136](https://github.com/pbek/QOwnNotes/issues/2136), thank you @fnkhz)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by fabianski7** [comment]
I have version 21.1.8 with the auto select option enabled but it is not working.
Is it necessary to do anything else besides that?

Here is the QON debug info
https://bin.snopyta.org/?74f8eb548a1c2ddd#B75LQuga5b9kqEUXWTB9o8s2WtxEUTXVf37SGQ4wg6sr

**Comment by pbek** [comment]
If you move the text cursor in the note edit panel, then in the navigation panel the heading you currently are under is selected.

**Comment by fabianski7** [comment]
> If you move the text cursor in the note edit panel, then in the navigation panel the heading you currently are under is selected.

[yup. that's exactly what I'm doing](https://upload.vaa.red/63t2x#sNzuHlzNkvTpMbWS95cEy5lL3pGSCodB)

**Comment by fabianski7** [comment]
after writing something it actually highlights, but just moving the cursor is not enough

**Comment by fnkhz** [comment]
Works fine for me also. KDE neon here.

**Comment by pbek** [comment]
Tested on Manjaro KDE, works fine for me.

**Comment by pbek** [comment]
@fabianski7, I can't reproduce your issue on any platform. Please open a separate issue.
