### ISSUE TITLE
Feature request: add shortcut and/or entry in action menu for 'insert link to note'

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#2137]
Is there a way to preselect `Note` in this dialog:

![image](https://user-images.githubusercontent.com/5956570/117793007-1b499d80-b24c-11eb-8619-282fa6b465b6.png)

#### Expected behaviour
- ctrl-a
- insert link to note
- type and/or find note
- OK

#### Actual behaviour
- ctrl-a
- insert link
- click note
- type and/or find note
- OK

QON version `21.5.1-1`.

Thanks in advance.

**Comment by sanderboom** [comment]
Ah yes, I meant `Ctrl+Shift+A` (in my case this displays the actions popup).

>  Currently the shortest way to get to the search field in the note link tab in the dialog is pressing Shift + Tab, Right, Tab.

Would be great if this can be preselected via a separate shortcut and/or entry in the actions popup.

**Comment by pbek** [comment]
## 21.5.3
- there now is a new shortcut <kbd>Ctrl</kbd> + <kbd>⇧</kbd> + <kbd>L</kbd> that opens
  the link dialog on the tab to add a note link

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by sanderboom** [comment]
Works! Thanks for the quick fix :rocket:

**Comment by pbek** [comment]
Great, thank you for testing!
