### ISSUE TITLE
Suggestion: "Show menu bar item" (OSX)

### ISSUE THREAD

**Issue by Fischmuetze** [pbek/QOwnNotes#214]
As there is no "system tray" on OS X the description in the Window menu 
"Show in system tray" is wrong
better would be
"Show menu bar item" or similar

**Comment by Fischmuetze** [comment]
Also colored menu bar items are not really popular

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
v16.06.8:
- the menu entry `Show in system tray` was renamed to `Show menu bar item` on 
  OS X
