### ISSUE TITLE
Sync via DropBox

### ISSUE THREAD

**Issue by snakyjake1** [pbek/QOwnNotes#2141]
Request a feature to sync notes across devices using DropBox.

I also don't want to install extra software.

Especially important for users that do not have a Nextcloud server (I don't need Nextcloud, I just need to syn across devices).

**Comment by pbek** [comment]
QOwnNotes does not sync your notes and media / attachment files (not even via Nextcloud)!
File syncing is a complex endeavor, there are already great file syncing solutions out there.

see https://www.qownnotes.org/getting-started/concept.html

**Comment by pbek** [comment]
You can use any file sync tool you like to sync your note folder(s).

**Comment by Waqar144** [comment]
Qownnotes is designed to not support *any* sync solution. It just creates files like a text editor, if you want sync you can easily do that with whatever service you want (gdrive, mega, Dropbox, xyz)

Also note that we don't support next cloud sync either. We support the way it organizes things just to make Qownnotes work with nextcloud notes.

**Comment by pbek** [comment]
I guess I can close this now.
