### ISSUE TITLE
can you add more options to the Qownnotes web extension? 

### ISSUE THREAD

**Issue by mlaarebi** [pbek/QOwnNotes#2142]
When I try to save an article I end up saving the entire page with menu and comments and suggestions...

Is it possible to add some options (in the settings), so the app can only take what is inside "the article area"?
something like what "Firefox reader mode" does. Firefox does not save the article for offline reading but Qownnotes could, you're already on the right path.

And it would also be wonderful if the user can be able to only "clip" the text from the article (adding it as an option in settings), nothing else (like images).

Meaning that Qownnotes could be the perfect replacement for Pocket. And you won't need lot of work to do it, you're already near it.

**Comment by pbek** [comment]
You can already do that with the scripting engine. There is a hook for that.
https://www.qownnotes.org/scripting/hooks.html#websocketrawdatahook gets you the full html of the page, you can clip out whatever you like.
