### ISSUE TITLE
Trigger menu actions after startup from the CLI

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#2143]
It would be great to be able to trigger menu actions after startup from the CLI.

**Comment by pbek** [comment]
## 21.5.4
- there now is a new cli parameter `--action <name>` that triggers a menu action after
  the application was started (for [#2143](https://github.com/pbek/QOwnNotes/issues/2143))
    - for example `QOwnNotes --action actionShow_Todo_List` will open the todo
      list dialog after startup
    - this parameter also works with scripted custom actions 
    - for more information please take a look at
      [Trigger menu actions after startup](https://www.qownnotes.org/getting-started/cli-parameters.html#trigger-menu-actions-after-startup)

**Comment by fabianski7** [comment]
it's not working for me if QON is running. the command only open the main window

`
Warning: "Another instance of QOwnNotes was already started! You can turn off the single instance mode in the settings or use the parameter --allow-multiple-instances." ((null):0, (null))`

[settings dump](https://bin.disroot.org/?c75a449b04da5f81#9EqTC6AzyeR7xBpAvcwKfe5DazRuXfQw6xTmQpyURKdi)

**Comment by pbek** [comment]
To inject the action name into the old session is even trickier than I feared.

**Comment by pbek** [comment]
This took a while... Had to jump to many hoops.

## 21.5.5
- the cli parameter `--action <name>` that triggers a menu action after the application
  was started now also works in single application mode when the application is
  started a second time (for [#2143](https://github.com/pbek/QOwnNotes/issues/2143))

**Comment by fabianski7** [comment]
cold you bump the version on AUR for me to test?

**Comment by pbek** [comment]
It's not released yet. Tomorrow if all goes well...

**Comment by fabianski7** [comment]
Alright. I build manually. it's working now

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
Great, thank you for testing!
