### ISSUE TITLE
Unexpected behaviour of `"` and `>` characters

### ISSUE THREAD

**Issue by ldv8434** [pbek/QOwnNotes#2144]
The text cursor will not properly pass through closing quotes.   
For example (and using a pipe as a stand-in for the text cursour),   
`"The quick brown fox|"`  
will become  
`"The quick brown fox"|"`

However,  
`"The quick brown fox |"`  
will become   
`"The quick brown fox "|`

As an extension, 
`"The quick brown fox" jumped |"`
becomes
`"The quick brown fox" jumped "|`
(in other words, not creating a new matching quote)

The difference is the presence of a space between the end of a word and the existing quote mark. If the quote has no space, an extra quote is added. If there is a space before the existing quote, the cursor will pass through. This leads to a lot of delete-key-presses to remove the extra quote mark.

Working punctuation:
```
`()[]{}
```
Broken punctuation:
```
"
<> (`<` creates "<>", but `>` will not pass through regardless of leading space)
```

#### Expected behaviour

Pressing `"` at the end of a word where there is already a double-quote character in the next character space will pass-through the character instead of creating a new one. The same applies for the `>` character.

#### Actual behaviour

The character will be inserted instead. A space before the character will nullify this with `"`, but not with `>`. 

#### Steps to reproduce

1. Open QOwnNotes
2. Type a `"` or `<` character followed by some words. Do not leave a trailing space in the case of `"`.
3. Type the associated closing character `"`/`>`. The character will be inserted resulting in two of the same character.

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mon May 24 13:05:40 2021`
**Version**: `21.5.4`
**Build date**: `May 24 2021`
**Build number**: `837`
**Platform**: `linux`
**Operating System**: `Arch Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/home/dracula/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/dracula/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: `en`
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080`
**Icon theme**: `breeze`
**Notes in current note folder**: `10`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_AG, en_BS, en_BW, en_BZ, en_DK, en_GB, en_GB-large, en_GH, en_HK, en_IE, en_IN, en_JM, en_NA, en_NG, en_NZ, en_SG, en_TT, en_US, en_US-large, en_ZA, en_ZW`
**Language names**: `English (Antigua & Barbuda), English (Bahamas), English (Botswana), English (Belize), English (Denmark), British English (United Kingdom), British English (United Kingdom) [large], English (Ghana), English (Hong Kong SAR China), English (Ireland), English (India), English (Jamaica), English (Namibia), English (Nigeria), English (New Zealand), English (Singapore), English (Trinidad & Tobago), American English (United States), American English (United States) [large], English (South Africa), English (Zimbabwe)`
**Application dictionaries path**: `/home/dracula/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/dracula/tmp`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/dracula/tmp/notes.sqlite`

### Note folder `Redacted`

**id**: `2`
**isCurrent**: `no`
**activeTagId**: `-1`
**localPath**: `/home/dracula/Documents/Personal/redacted/content`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/dracula/Documents/Personal/redacted/content/notes.sqlite`

### Note folder `Library Phantasmagoria`

**id**: `3`
**isCurrent**: `no`
**activeTagId**: `-1`
**localPath**: `/home/dracula/Documents/Personal/libraryphantasmagoria/content`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/dracula/Documents/Personal/libraryphantasmagoria/content/notes.sqlite`

### Note folder `CSEC.461`

**id**: `4`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/dracula/Documents/CSEC.461 Comp Sys Security`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/dracula/Documents/CSEC.461 Comp Sys Security/notes.sqlite`

### Note folder `CSEC.462`

**id**: `5`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/dracula/Documents/CSEC.462 Network Security and Forensics`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/dracula/Documents/CSEC.462 Network Security and Forensics/notes.sqlite`

### Note folder `PHIL.409`

**id**: `6`
**isCurrent**: `no`
**activeTagId**: `-1`
**localPath**: `/home/dracula/Documents/PHIL.409 Existentialism`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/dracula/Documents/PHIL.409 Existentialism/notes.sqlite`

### Note folder `Misc Notes`

**id**: `7`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/dracula/Documents/Personal/Misc Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/dracula/Documents/Personal/Misc Notes/notes.sqlite`

### Note folder `NierAutomata`

**id**: `8`
**isCurrent**: `no`
**activeTagId**: `-1`
**localPath**: `/home/dracula/Documents/Personal/TheNierVideo`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/dracula/Documents/Personal/TheNierVideo/notes.sqlite`

### Cloud connection ``

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `30`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `false`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (bool): `false`
**Editor/useTabIndent** (bool): `true`
**Editor/vimMode** (bool): `false`
**FileDialog/LastPath** (QString): `/home/dracula/Documents/CSEC.461 Comp Sys Security`
**FileDialog/LastPath-InsertImage** (QString): `/home/dracula/Documents/Personal/libraryphantasmagoria/content/images`
**FileDialog/LastPath-NotePDFExport** (QString): `/home/dracula/Documents/CSEC.461 Comp Sys Security`
**ImageDialog/disableCopying** (QString): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-05-24T12:36:50.552`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LinkDialog/lastSelectedFileUrl** (QString): `file:///home/dracula/Documents/Personal/libraryphantasmagoria/content/pages/tech/virtual-reality.md`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `false`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `reviews`
**MainWindow/noteSubFolderTreeWidgetExpandState-3** (QStringList): `pages/reviews, pages/pages, pages`
**MainWindow/noteSubFolderTreeWidgetExpandState-7** (QStringList): `folder1, folder1/folder1, Video Ideas`
**MainWindow/noteSubFolderTreeWidgetExpandState-8** (QStringList): `chapter`
**MainWindow/noteTextEdit.code.font** (QString): `Source Code Pro,10,-1,0,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Source Sans 3,10,-1,0,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Hack,10,-1,7,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/open-url-create-note** (QString): `16384`
**MessageBoxOverride/tag-notes** (QString): `16384`
**NoteFolder-1/NoteTabNameList** (QStringList): `test`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteFolder-2/NoteTabNameList**: *empty*
**NoteFolder-2/NoteTabStickinessList**: *empty*
**NoteFolder-2/NoteTabSubFolderPathDataList**: *empty*
**NoteFolder-2/allowDifferentNoteFileName** (QString): `true`
**NoteFolder-3/NoteTabNameList** (QString): `tidbits`
**NoteFolder-3/NoteTabStickinessList**: *empty*
**NoteFolder-3/NoteTabSubFolderPathDataList** (QString): 
```
pages
other
```
**NoteFolder-3/allowDifferentNoteFileName** (QString): `true`
**NoteFolder-4/NoteTabNameList** (QString): `lab5`
**NoteFolder-4/NoteTabStickinessList**: *empty*
**NoteFolder-4/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteFolder-4/allowDifferentNoteFileName** (QString): `true`
**NoteFolder-5/NoteTabNameList** (QString): `lab5`
**NoteFolder-5/NoteTabStickinessList**: *empty*
**NoteFolder-5/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteFolder-5/allowDifferentNoteFileName** (QString): `true`
**NoteFolder-6/NoteTabNameList** (QString): `V5 Notes`
**NoteFolder-6/NoteTabStickinessList**: *empty*
**NoteFolder-6/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteFolder-6/allowDifferentNoteFileName** (QString): `true`
**NoteFolder-7/NoteTabNameList** (QString): `Notebooks`
**NoteFolder-7/NoteTabStickinessList**: *empty*
**NoteFolder-7/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteFolder-7/allowDifferentNoteFileName** (QString): `false`
**NoteFolder-8/NoteTabNameList** (QStringList): `YoRHa_Descent`
**NoteFolder-8/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-8/NoteTabSubFolderPathDataList** (QStringList): 
```
chapter
01
```
**NoteHistory-1** (QVariantList): `<variant list with 13 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 11 item(s)>`
**NoteHistory-3** (QVariantList): `<variant list with 52 item(s)>`
**NoteHistory-4** (QVariantList): `<variant list with 16 item(s)>`
**NoteHistory-5** (QVariantList): `<variant list with 5 item(s)>`
**NoteHistory-6** (QVariantList): `<variant list with 31 item(s)>`
**NoteHistory-7** (QVariantList): `<variant list with 57 item(s)>`
**NoteHistory-8** (QVariantList): `<variant list with 65 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `12`
**NoteHistoryCurrentIndex-2** (QString): `10`
**NoteHistoryCurrentIndex-3** (QString): `51`
**NoteHistoryCurrentIndex-4** (QString): `15`
**NoteHistoryCurrentIndex-5** (QString): `4`
**NoteHistoryCurrentIndex-6** (QString): `30`
**NoteHistoryCurrentIndex-7** (QString): `56`
**NoteHistoryCurrentIndex-8** (int): `64`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExport** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `true`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `false`
**enableWebAppSupport** (bool): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `true`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): `yyyy-MM-dd hh:mm`
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): `en`
**internalIconTheme** (bool): `false`
**itemHeight** (int): `24`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `false`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `0`
**notesPath** (QString): `/home/dracula/tmp`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `0`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `7d92832c-300a-4dbd-8230-fd78fe47a70d`
**recentNoteFolders** (QStringList): `/home/dracula/Documents/Personal/TheNierVideo, /home/dracula/Documents/Personal, /home/dracula/Documents/Personal/Misc Notes, /home/dracula/Documents/Personal/libraryphantasmagoria/content, /home/dracula/Documents/CSEC.461 Comp Sys Security, /home/dracula/Documents/CSEC.462 Network Security and Forensics, /home/dracula/Documents/PHIL.409 Existentialism, /home/dracula/Documents/Personal/redacted/content, /home/dracula/Documents`
**restoreCursorPosition** (bool): `true`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `stylus_css, games, ideas, Note 2021-04-13T00.06.00, Note 2021-04-13T00.00.51, Note 2021-04-12T23.59.19`
**savedSearches/noteFolder-3** (QStringList): `Note 2021-04-13T13.34.46, Note 2021-04-13T00.31.08`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckBackend** (QString): `Hunspell`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (bool): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, `
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-7d92832c-300a-4dbd-8230-fd78fe47a70d/name** (QString): `Classes`
**workspace-7d92832c-300a-4dbd-8230-fd78fe47a70d/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-7d92832c-300a-4dbd-8230-fd78fe47a70d/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 7d92832c-300a-4dbd-8230-fd78fe47a70d`

## System environment

**SHELL**: `/usr/bin/zsh`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**DESKTOP_SESSION**: `plasma`
**XDG_SEAT**: `seat0`
**PWD**: `/home/dracula`
**XDG_SESSION_DESKTOP**: `KDE`
**LOGNAME**: `dracula`
**XDG_SESSION_TYPE**: `x11`
**XAUTHORITY**: `/home/dracula/.Xauthority`
**MOTD_SHOWN**: `pam`
**HOME**: `/home/dracula`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**USER**: `dracula`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**DISPLAY**: `:0`
**SHLVL**: `0`
**XDG_VTNR**: `1`
**XDG_SESSION_ID**: `2`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**MAIL**: `/var/spool/mail/dracula`
**OLDPWD**: `/home/dracula`
**CUDA_PATH**: `/opt/cuda`
**GRADLE_HOME**: `/usr/share/java/gradle`
**MKLROOT**: `/opt/intel/mkl`
**LANG**: `en_US.UTF-8`
**HG**: `/usr/bin/hg`
**GTK_MODULES**: `canberra-gtk-module`
**GTK3_MODULES**: `xapp-gtk3-module`
**_**: `/usr/bin/startplasma-x11`
**QT_SCREEN_SCALE_FACTORS**: `DP-0=1;DP-1=1;HDMI-0=1;DP-2=1;DP-3=1;DP-4=1;DP-5=1;`
**XCURSOR_THEME**: `breeze_cursors`
**XCURSOR_SIZE**: `24`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**KDE_FULL_SESSION**: `true`
**KDE_SESSION_VERSION**: `5`
**KDE_SESSION_UID**: `1000`
**KDE_APPLICATIONS_AS_SCOPE**: `1`
**GTK_RC_FILES**: `/etc/gtk/gtkrc:/home/dracula/.gtkrc:/home/dracula/.config/gtkrc`
**GTK2_RC_FILES**: `/etc/gtk-2.0/gtkrc:/home/dracula/.gtkrc-2.0:/home/dracula/.config/gtkrc-2.0`
**SESSION_MANAGER**: `local/kinbaku:@/tmp/.ICE-unix/1082,unix/kinbaku:/tmp/.ICE-unix/1082`

</details>

#### Relevant log output in the Log panel

No relevant output

**Comment by pbek** [comment]
Do mean "unexpected" in the sense of "I want that feature, like I have for brackets"?

**Comment by pbek** [comment]
I can give you the check for `>`, I hope that doesn't break anything.

As for the `"` I'm not sure, @Waqar144, didn't that already work? Does https://github.com/pbek/qmarkdowntextedit/commit/9f9e8742f20c2b232b90c5ea12340b6d88a8d083 anything to do with it? Currently the `if last char is not space, we are at word end, no autocompletion` check is where `QMarkdownTextEdit::quotationMarkCheck` returns false for `"`.

**Comment by pbek** [comment]
## 21.5.5
- now the `>` character will also be checked at automatic bracket closing when
  it was already entered (for [#2144](https://github.com/pbek/QOwnNotes/issues/2144))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Waqar144** [comment]
The problem with these completions is that in some cases they are okay, but in others they are not.

I think < behavior was changed because it led to problems in code blocks.

That being said, one can still refine the " behavior I think. It's not perfect and hard to make it perfect because of so many variations...

**Comment by Waqar144** [comment]
> I can give you the check for `>`, I hope that doesn't break anything.
> 
> As for the `"` I'm not sure, @Waqar144, didn't that already work? Does [pbek/qmarkdowntextedit@9f9e874](https://github.com/pbek/qmarkdowntextedit/commit/9f9e8742f20c2b232b90c5ea12340b6d88a8d083) anything to do with it? Currently the `if last char is not space, we are at word end, no autocompletion` check is where `QMarkdownTextEdit::quotationMarkCheck` returns false for `"`.

This might be the reason...

**Comment by ldv8434** [comment]
> Do mean "unexpected" in the sense of "I want that feature, like I have for brackets"?

"Unexpected" in the sense of "I expected it to work the same as brackets, and the way that it works with a space but not without seemed strange". If this wasn't intended behaviour, then yes, it is a feature request. 

> There now is a new release, could you please test it and report if it works for you?

It works! Thank you!

**Comment by pbek** [comment]
Great, thank you for testing!

> This might be the reason...

@Waqar144, do you want to take a look at the `"` handling or should I close this?

**Comment by pbek** [comment]
@Waqar144?

**Comment by Waqar144** [comment]
Ah sorry ;p

I think we can close this here.

I will take a look at it but we need some clear test cases first and we can track this in `qmarkdowntextedit` directly since that is where the fixes will go.
