### ISSUE TITLE
Updater does not execute on Windows 7

### ISSUE THREAD

**Issue by Baptistou** [pbek/QOwnNotes#2148]
#### Expected behaviour

QOwnNotes should update.

#### Actual behaviour

I installed QOwnNotes on both Windows 7 and Windows 10 into the same location with the same permissions, I encounter the same issue described in #2075 on 7 but the updater works as expected on 10.

#### Steps to reproduce

1. Click on update notification at bottom right
2. Click on update button, then downloading proceeds
3. A dialog asks to restart QOwnNotes, click on OK
4. QOwnNotes closes then nothing happens

I tried to move QOwnNotes to another location but same issue. After multiple unsuccessful attempts, I noticed that all downloaded zip files are accumulated inside `AppData\Local\Temp`. However, when I executed manually `update.bat` with the 3 parameters provided in the logs, the update succeeded.

```cmd
update.bat "C:\\Users\\Baptiste Thémine\\AppData\\Local\\Temp\\QOwnNotes-Pupnqw.zip" "C:\\Baptiste\\Programmes\\QOwnNotes" "C:\\Users\\Baptiste Thémine\\AppData\\Local\\Temp\\QOwnNotes-Pupnqw-unzip.exe"
```

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `mar. mai 25 22:31:14 2021`
**Version**: `21.5.5`
**Build date**: `May 25 2021`
**Build number**: `838`
**Platform**: `windows`
**Operating System**: `Windows 7 Version 6.1 (Build 7601: SP 1)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\Baptiste Thémine\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\\Baptiste\\Programmes\\QOwnNotes`, `\QOwnNotes.exe`, `--after-update`, `update`
**Qt Debug**: `0`
**Locale (system)**: `fr_FR`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1366x768`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `20`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

***REMOVED SENSITIVE VALUE***

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\Baptiste Thémine\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Notes`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `C:\Baptiste\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Baptiste\Notes\notes.sqlite`

## Cloud connections

***REMOVED SENSITIVE VALUE***

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `true`
**DistractionFreeMode/editorWidthMode** (int): `1`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (int): `21`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/useTabIndent** (QString): `true`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `C:/Users/Baptiste Thémine/Downloads`
**FileDialog/LastPath-SettingsExport** (QString): `C:/Users/Baptiste Thémine/Downloads`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-05-25T22:17:43.721`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Courier New,9,-1,5,50,0,0,0,0,0,Normal`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Courier New,9,-1,5,50,0,0,0,0,0,Normal`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `true`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteDialog/tabWidgetIndex** (int): `0`
**NoteFolder-1/NoteTabNameList** (QStringList): `QuickNotes`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteFolder-1/allowDifferentNoteFileName** (QString): `true`
**NoteHistory-1** (QVariantList): `<variant list with 17 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `16`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**TrashDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**VersionDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `EnMVYxeCyywH`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): `yyyy-MM-dd HH:mm`
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (int): `15`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `false`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `true`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `C:/Baptiste/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Erreur inconnue`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `21.0.2.1`
**previousWorkspace** (QString): `uQVWHtX3CzHS`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Test, Note 2021-05-16T12.53.41, Note 2021-05-16T12.25.10`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, actionShow_note_in_file_manager, action_Open_note_in_external_editor, actionAllow_note_editing, actionSave_modified_notes, action_Print_note_markdown, action_Remove_note, , action_Find_note, action_Find_text_in_note, actionReplace_in_current_note, actionFind_action, , action_Reload_note_folder, actionShare_note, actionShow_versions, actionShow_trash`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `barre d'outils principale`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionFormat_text_underline, actionStrike_out_text, actionToggle_text_case`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `barre d'outils de formatage`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_note_link, actionInsert_image, actionInsert_attachment, actionInsert_headline_from_note_filename, actionInsert_current_time, actionInsert_table, actionInsert_block_quote, actionInsert_code_block`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `barre d'outils d'insertion`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `barre d'outils de chiffrement`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `barre d'outils de fenêtre`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quitter la barre d’outils`
**toolbar/size** (int): `6`
**trashSplitterSizes** (QByteArray): `<binary data>`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**versionSplitterSizes** (QByteArray): `<binary data>`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-EnMVYxeCyywH/name** (QString): `Edit`
**workspace-EnMVYxeCyywH/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-EnMVYxeCyywH/windowState** (QByteArray): `<binary data>`
**workspace-uQVWHtX3CzHS/name** (QString): `Preview`
**workspace-uQVWHtX3CzHS/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-uQVWHtX3CzHS/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `EnMVYxeCyywH, uQVWHtX3CzHS`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**AMDAPPSDKROOT**: `C:\Program Files (x86)\AMD APP\`
**APPDATA**: `C:\Users\Baptiste Thémine\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `HP-BT05092011`
**ComSpec**: `C:\Windows\system32\cmd.exe`
**destination**: `"C:\\Baptiste\\Programmes\\QOwnNotes"`
**FP_NO_HOST_CHECK**: `NO`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\Baptiste Thémine`
**LOCALAPPDATA**: `C:\Users\Baptiste Thémine\AppData\Local`
**LOGONSERVER**: `\\HP-BT05092011`
**NUMBER_OF_PROCESSORS**: `4`
**OnlineServices**: `Online Services`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Broadcom\Broadcom 802.11\Driver;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\MinGW\bin;C:\Program Files\Java\jdk1.8.0_271\bin;C:\Program Files\MKVToolNix;C:\Baptiste\Scripts;C:\Program Files\Git\cmd;C:\Users\Baptiste Thémine\AppData\Local\GitHubDesktop\bin`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PCBRAND**: `Pavilion`
**Platform**: `MCD`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `AMD64 Family 18 Model 1 Stepping 0, AuthenticAMD`
**PROCESSOR_LEVEL**: `18`
**PROCESSOR_REVISION**: `0100`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PROMPT**: `$P$G`
**PSModulePath**: `C:\Windows\system32\WindowsPowerShell\v1.0\Modules\`
**PUBLIC**: `C:\Users\Public`
**qownnotesCommand**: `"C:\\Baptiste\\Programmes\\QOwnNotes"\QOwnNotes.exe --after-update update `
**SESSIONNAME**: `Console`
**source**: `"C:\\Users\\Baptiste Thémine\\AppData\\Local\\Temp\\QOwnNotes-Pupnqw.zip"`
**SystemDrive**: `C:`
**SystemRoot**: `C:\Windows`
**TEMP**: `C:\Users\BAPTIS~1\AppData\Local\Temp`
**TMP**: `C:\Users\BAPTIS~1\AppData\Local\Temp`
**unzipCommand**: `"C:\\Users\\Baptiste Thémine\\AppData\\Local\\Temp\\QOwnNotes-Pupnqw-unzip.exe" -o "C:\\Users\\Baptiste Thémine\\AppData\\Local\\Temp\\QOwnNotes-Pupnqw.zip" -d "C:\\Baptiste\\Programmes\\QOwnNotes"`
**unzipExecutable**: `"C:\\Users\\Baptiste Thémine\\AppData\\Local\\Temp\\QOwnNotes-Pupnqw-unzip.exe"`
**USERDOMAIN**: `HP-BT05092011`
**USERNAME**: `Baptiste Thémine`
**USERPROFILE**: `C:\Users\Baptiste Thémine`
**windir**: `C:\Windows`
**windows_tracing_flags**: `3`
**windows_tracing_logfile**: `C:\BVTBin\Tests\installpackage\csilogfile.log`
</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[mai 25 21:57:40] [debug]: updatePanelMenu  - 'updatePanelMenu'
[mai 25 21:57:46] [debug]: dialogButtonClicked  - 'releaseUrl':  "https://github.com/pbek/QOwnNotes/releases/download/v21.5.5/QOwnNotes.zip"
[mai 25 21:57:59] [debug]: Reply from  "/27436491/8af77680-bd7c-11eb-8607-9c760f88b388"
[mai 25 21:58:00] [debug]: slotReplyFinished  - 'data.size':  39626015
[mai 25 21:58:04] [debug]: initializeWindowsUpdateProcess  - 'parameters':  ("C:\\Users\\Baptiste Thémine\\AppData\\Local\\Temp\\QOwnNotes-Pupnqw.zip", "C:\\Baptiste\\Programmes\\QOwnNotes", "C:\\Users\\Baptiste Thémine\\AppData\\Local\\Temp\\QOwnNotes-Pupnqw-unzip.exe")
```

</details>

**Comment by pbek** [comment]
Thank you for reporting, but I haven't a Windows 7 box laying around any more to test it. 😬 
It's hard to tell what is preventing the updater.bat execution on your system.
The updater.bat is supposed to be run in the background after 3) before QOwnNotes quits.
You could enable logging to a file in the settings and see if an error is logged before QOwnNotes quits.

**Comment by Baptistou** [comment]
> Thank you for reporting, but I haven't a Windows 7 box laying around any more to test it. :grimacing:

That is understandable as Microsoft support of Windows 7 ended this year. I see that [Windows XP is not supported anymore](https://www.qownnotes.org/fr/installation/windows.html) but I don't see any mention of Vista, 7 or 8. Could it be possible to add a *System Requirements* table to the documentation ?

> You could enable logging to a file in the settings and see if an error is logged before QOwnNotes quits.

I already enabled *logging to a file* but there is no output nor error after `initializeWindowsUpdateProcess`. I will try to investigate a little more on the next update.

**Comment by pbek** [comment]
> That is understandable as Microsoft support of Windows 7 ended this year. I see that Windows XP is not supported anymore but I don't see any mention of Vista, 7 or 8. 

The binary built on AppVeyor (see https://www.qownnotes.org/installation/windows.html#windows-xp) with an old Qt version still should work with WinXP.
And since Qt still supports Windows 7 it should also run there.

> Could it be possible to add a System Requirements table to the documentation?

There are some at https://github.com/pbek/QOwnNotes#minimum-software-requirements

> I already enabled logging to a file but there is no output nor error after initializeWindowsUpdateProcess. I will try to investigate a little more on the next update.

In the *Debug options* in the settings dialog you can also fake an old version to trigger an update.

**Comment by martinbra** [comment]
hum, I too had the same problem here, updating from 21.5.1 to 26.6.3 on windows 7.
The logs shows:
```
...
[jun 17 09:09:26] [debug]: updateNoteShareStatusFromShare  - 'status':  "ok\n"
[jun 17 09:09:47] [debug]: dialogButtonClicked  - 'releaseUrl':  "https://github.com/pbek/QOwnNotes/releases/download/v21.6.3/QOwnNotes.zip"
[jun 17 09:09:58] [debug]: Reply from  "/27436491/71ea6d00-cec5-11eb-9097-52f1be5bc6c2"
[jun 17 09:09:58] [debug]: slotReplyFinished  - 'data.size':  39625766
[jun 17 09:10:06] [debug]: initializeWindowsUpdateProcess  - 'parameters':  ("C:\\Users\\martin.meier\\AppData\\Local\\Temp\\QOwnNotes-hDCfln.zip", "C:\\Programas\\QOwnNotes", "C:\\Users\\martin.meier\\AppData\\Local\\Temp\\QOwnNotes-hDCfln-unzip.exe")
[jun 17 09:10:06] [debug]: storeSettings  - 'noteHistoryItem':  NoteHistoryItem: <noteName>"## excluir login de cliente" <noteSubFolderPathData>"SQL" <cursorPosition>1421 <relativeScrollBarPosition>0
```
And it ends here.
If i use the `initializeWindowsUpdateProcess  - 'parameters'` at the qOwnNotes folder the update works:
```
C:\Programas\QOwnNotes>update.bat "C:\Users\martin.meier\AppData\Local\Temp\QOwnNotes-hDCfln.zip", "C:\Programas\QOwnNotes", "C:\Users\martin.meier\AppData\Local\Temp\QOwnNotes-hDCfln-unzip.exe"

Aguardando 0 segundos, pressione uma tecla para continuar ...
ERRO: o processo "QOwnNotes.exe" não foi encontrado.
update.bat "C:\Users\martin.meier\AppData\Local\Temp\QOwnNotes-hDCfln.zip", "C:\Programas\QOwnNotes", "C:\Users\martin.meier\AppData\Local\Temp\QOwnNotes-hDCfln-unzip.exe"
======================================
Updating QOwnNotes in folder:
"C:\Programas\QOwnNotes"
======================================
Source archive:
"C:\Users\martin.meier\AppData\Local\Temp\QOwnNotes-hDCfln.zip"
======================================
Unzip executable:
"C:\Users\martin.meier\AppData\Local\Temp\QOwnNotes-hDCfln-unzip.exe"
======================================
Executing unzip command:
"C:\Users\martin.meier\AppData\Local\Temp\QOwnNotes-hDCfln-unzip.exe" -o "C:\Users\martin.meier\AppData\Local\Temp\QOwnNotes-hDCfln.zip" -d "C:\Programas\QOwnNotes"
======================================
Uncompressing files...
Archive:  C:/Users/martin.meier/AppData/Local/Temp/QOwnNotes-hDCfln.zip
  inflating: C:/Programas/QOwnNotes/bearer/qgenericbearer.dll

   ...

  inflating: C:/Programas/QOwnNotes/update.bat
======================================
Deleting temporary files
======================================
Starting QOwnNotes:
"C:\Programas\QOwnNotes"\QOwnNotes.exe --after-update update.bat
======================================
Pressione qualquer tecla para continuar. . .
```

So, it's an argument issue...

**Comment by pbek** [comment]
Are you sure your current user has permissions to `C:\\Programas\\QOwnNotes` without "Administrator Access"?

**Comment by Baptistou** [comment]
I did some tests again and even if I launch QOwnNotes as administrator, the updater does not execute on Windows 7.
Same result when changing the location or the permissions of the folder, so this issue does not seem to be related to permissions.

**Comment by pbek** [comment]
You would need to build QOwnNotes yourself to play more with the part that starts the updater. 😅
