### ISSUE TITLE
Feature Request: Show subdirectories on top in Note List panel

### ISSUE THREAD

**Issue by digg33** [pbek/QOwnNotes#2149]
#### Expected behaviour
When notes list panel is set to tree view, subdirectories in Notes folder are kept on top separately from files.

#### Actual behaviour
When notes list panel is set to tree view, subdirectories in Notes folder are sorted alphabetically with files, so they appear in between file entries

Personally, for me this would bring the same benefits as being able to separate files and directories in e.g. a file manager.

Thanks,
digg33

**Comment by pbek** [comment]
Are you talking about https://github.com/pbek/QOwnNotes/issues/790? You could suggest that there.

**Comment by digg33** [comment]
Hi pbek. Yes, it is closely related to the ongoing implementation of #790. I agree that the discussion can continue there. If my request is clear to you, would you consider adding it to the todo list on the top-level comment? I am going to add a comment about this there now.

Thanks,
digg33

**Comment by pbek** [comment]
Yes, I can add it to the Todo (without knowing if it will ever be implemented).
