### ISSUE TITLE
FR: Option to anchor body left when editor width set

### ISSUE THREAD

**Issue by digg33** [pbek/QOwnNotes#2151]
#### Expected behaviour
Allow anchoring the text body to the left. Simulated e.g.:
![image](https://user-images.githubusercontent.com/58906128/120482392-9c560980-c3a0-11eb-9439-87d32c64f226.png)

#### Actual behaviour
Currently when editor width is set, the text body is anchored to the centre of the panel. E.g. (editor width set to wide):
![image](https://user-images.githubusercontent.com/58906128/120482084-4f723300-c3a0-11eb-8d72-91bea9ecf9a9.png)

NOTE: Reminder that it is possible to have editor width set in both cases; normal editing and distraction-free mode. Please consider the FR for both cases.

Thanks,
digg33

**Comment by pbek** [comment]
I don't know if I like to add two more settings for something that can (almost) be achieved by resizing the panel. 🤔

**Comment by digg33** [comment]
Resizing the panel is something I did not think of which actually isn't too bad (though a bit awkward when using two horizontal panels). And I also understand not wanting to add settings for every little detail. Maybe I should close this issue as the workaround seems reasonable?

Thanks,
digg33

**Comment by pbek** [comment]
Ok, let's close this. 😁
