### ISSUE TITLE
Unable to navigate to right position with navigation panel in preview mode (panel)

### ISSUE THREAD

**Issue by RichardBaker3020** [pbek/QOwnNotes#2152]
#### Expected behaviour
Page will be navigated to the right position by clicking navigation item in both text edit mode (panel) and preview mode (panel)

#### Actual behaviour
Clicking navigation item will navigate the page to the right headers in text edit panel, but this doesn't work well in preview panel.

<details><summary>text edit panel screenshot</summary>

![image](https://user-images.githubusercontent.com/54793121/120599549-3f2e8680-c47a-11eb-9886-6383d142af91.png)

</details>

<details><summary>preview panel screenshot</summary>

![image](https://user-images.githubusercontent.com/54793121/120599623-50779300-c47a-11eb-915e-fa301c63dc70.png)

</details>

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

**Version**: `21.5.5`
**Build date**: `May 25 2021`
**Build number**: `838`
**Platform**: `linux`
**Operating System**: `Ubuntu Core 18`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Snapcraft`
**Qt Version (build)**: `5.9.5`
**Qt Version (runtime)**: `5.9.5`
**Portable mode**: `no`
**Application arguments**: `/snap/qownnotes/8360/usr/bin/QOwnNotes`, `-style=Breeze`, `--snap`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Calendar items**: `0`
**Enabled scripts**: `0`

</details>

**Comment by pbek** [comment]
Actually there is no navigation to headline in the preview at all. There only is a navigation to the headline in the edit panel and since the scrollbar percentage in the preview is synced to the edit panel (as long as the focus is in the edit panel) the scrolling in the preview panel happens that way.

**Comment by RichardBaker3020** [comment]
> Actually there is no navigation to headline in the preview at all. There only is a navigation to the headline in the edit panel and since the scrollbar percentage in the preview is synced to the edit panel (as long as the focus is in the edit panel) the scrolling in the preview panel happens that way.

Thanks for reply, is it possible to implement the navigation to headline in preview as well? It would be great to have this on qownnotes.

**Comment by pbek** [comment]
That isn't possible for two reasons

1) the scrollbar syncing would run havoc
2) since the html code of the preview is customizable it wouldn't be possible to detect the headings in many cases
