### ISSUE TITLE
[F] Disable spellcheck for encrypted notes

### ISSUE THREAD

**Issue by Katarn** [pbek/QOwnNotes#2156]
#### Expected behaviour

I expect the encrypted note should not be spellchecked because it is encrypted and consists of meaningless text. It looks ugly when the entire note is underlined with a red wavy line. I suggest not to check the spelling in the note until the decryption key is entered.

#### Actual behaviour

At the moment, if the spellcheck option is enabled, the text of the encrypted note is also checked.

#### Steps to reproduce

1. I select any encrypted note.
2. I turn on Edit > Check spelling option.
3. I see that the entire text of the note is underlined with a red wavy line.

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
## 21.6.1
- spell checking is now disabled in encrypted notes as long as the encrypted text
  is shown

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Katarn** [comment]
Works great. Thank you!

**Comment by pbek** [comment]
Great, thank you for testing!
