### ISSUE TITLE
Images should be resized to fit the page width when exporting note as pdf (preview)

### ISSUE THREAD

**Issue by pcwii** [pbek/QOwnNotes#2157]
#### Expected behaviour
- When exporting note as pdf (preview) any images should be scaled / resized to fit the margin width of the selected page size. 
#### Actual behaviour
- Large images are cropped at the margin (overrun the page) 
#### Steps to reproduce
- Use the export note as pdf (preview) with any note that has large images

**Comment by pbek** [comment]
Are we talking about #1658?

**Comment by pcwii** [comment]
Yes, it looks like we are.  I will try the recommendation in that post.
