### ISSUE TITLE
[F] Break line to long headline in navigation panel

### ISSUE THREAD

**Issue by fabianski7** [pbek/QOwnNotes#2158]
#### Expected behaviour
Display the entire headline title without having to resize the panel

#### Actual behaviour
The text is cut off and you cannot see the full title

#### Steps to reproduce
Create a headline with a big title, or create a multi-level tree ([like here](https://user-images.githubusercontent.com/47755037/121777212-7559bd80-cb80-11eb-9576-6ab2c1e4101d.png))

**Comment by pbek** [comment]
Unfortunately there is no `wordWrap` for https://doc.qt.io/qt-5/qtreewidgetitem.html like there is for https://doc.qt.io/qt-5/qlabel.html#wordWrap-prop, so that would be hard to implement.

**Comment by fabianski7** [comment]
🙄

**Comment by fabianski7** [comment]
.

**Comment by pbek** [comment]
I doubt there will ever be a way to wrap QTreeWidgetItems.
