### ISSUE TITLE
Wrong behavior during windows resizing

### ISSUE THREAD

**Issue by Fischmuetze** [pbek/QOwnNotes#216]
The app shows a strange during windows resizing.
Resize a window to a bigger width, preserved always the width of the editor pane but makes the notes list bigger or smaller . Senseless!
![1](https://cloud.githubusercontent.com/assets/19834496/16173708/3c2be77a-35aa-11e6-8a22-cead479b6696.jpg)
![2](https://cloud.githubusercontent.com/assets/19834496/16173710/3c69063c-35aa-11e6-95f7-e44f00fbe082.jpg)
![3](https://cloud.githubusercontent.com/assets/19834496/16173709/3c5f7afe-35aa-11e6-8067-25f099d14871.jpg)

**Comment by Fischmuetze** [comment]
By the way no idea which implication should have this settings 

![bildschirmfoto 2016-06-18 um 23 15 39](https://cloud.githubusercontent.com/assets/19834496/16173723/98463254-35aa-11e6-9685-26ce141e24bb.jpg)

**Comment by pbek** [comment]
The proportion between the panes are preserved (and the sizes remembered) for all permutations of visible panes. I see no fault with this behavior.

**Comment by Fischmuetze** [comment]
Thats isn't true! The behavior is ok if the markdown pane is visible but not if this pane is hided.
It seems to this wrong behavior appears only  if the option "Use vertical preview layout" is enabled and the markdown preview pane is hided. See the following screenshots

![bildschirmfoto 2016-06-18 um 23 26 38](https://cloud.githubusercontent.com/assets/19834496/16173766/553922ee-35ac-11e6-850c-fba1ea3de2c7.jpg)
![bildschirmfoto 2016-06-18 um 23 26 44](https://cloud.githubusercontent.com/assets/19834496/16173767/55673e18-35ac-11e6-9c6b-bf9c6fa9aa3d.jpg)

**Comment by pbek** [comment]
Can you please provide information what you did, what you get and what you expected in your last example?

> By the way no idea which implication should have the settings for the editor width

these settings are for the distraction free mode only (like the tool-tip states)

**Comment by Fischmuetze** [comment]
> Can you please provide information what you did,
As described. I hided the markdown preview and have enabled the Vertical preview layout. Than I resized the window (on the right side).

> what you expected in your last example?

 At least I would expect the same behavior as all panes are visible. Imho better would be to keep the width of the notes list always in the same size width the exeption if the user is change the proportions by drag the dividers

> these settings are for the distraction free mode only (like the tool-tip states)

as the distraction free mode is not really a distraction free mode I don't understand the sense of this - but anyway - not my turn

**Comment by pbek** [comment]
> Imho better would be to keep the width of the notes list always in the same size

please read #175, maybe also #141 and #145 

> as the distraction free mode is not really a distraction free mode

it was done for a user request and in (not only) my opinion works pretty well: #86

**Comment by Fischmuetze** [comment]
I can't understand this - this behavior is unusual and complete senseless ... if I resize a  window with two panes from a smaller size to a bigger size - left pane with fixed items where I can't change anything and a right pane with an editor which comes by default even with a soft wrap function - what in the hell could be my intention to resize the window? To get a bigger list or to get a more comfortable bigger editor pane?
