### ISSUE TITLE
[I] Case sensitivity for syntax highlighting inside code blocks differs between editor and preview panels

### ISSUE THREAD

**Issue by martinbra** [pbek/QOwnNotes#2161]
#### Expected behaviour

code inside tripple ticks with a language descriptor should be rendered the same way inside editor panel and preview panel.

#### Actual behaviour

If the language is written in lowercase, or if there is no defined language, the rendering of the syntax highlighting is the same.

If the language is written in uppercase, the edit panel highlight the code as if it was written in lowercase, but the preview panel ignores the language, showing no hightlight.

#### Steps to reproduce

Create a note with the content:

    ```sql
    SELECT * 
    FROM public.table
    WHERE user = (
        SELECT id_user 
        FROM public.table2 where email = 'contoso@contoso.com'
    );
    ```
    
    ```SQL
    SELECT * 
    FROM public.table
    WHERE user = (
        SELECT id_user 
        FROM public.table2 where email = 'contoso@contoso.com'
    );
    ```
    
    ```
    SELECT * 
    FROM public.table
    WHERE user = (
        SELECT id_user 
        FROM public.table2 where email = 'contoso@contoso.com'
    );
    ```
    
    
    ```python
    import this
    s = "abc" 'abc'
    a = 1 + 2 
    ```
    
    ```PYTHON
    import this
    s = "abc" 'abc'
    a = 1 + 2 
    ```
    
    ```
    import this
    s = "abc" 'abc'
    a = 1 + 2
    ```

Results in code editor:
![image](https://user-images.githubusercontent.com/29928669/122398039-df42e000-cf4f-11eb-9e22-2fe1a71a4ee3.png)

and in preview panel:
![image](https://user-images.githubusercontent.com/29928669/122398100-ecf86580-cf4f-11eb-8efa-3ef96e7f0312.png)

I'm not sure if it should be made case insensitive but given that github itself parses the keyword case insensitive, maybe we should do it too:

```sql
-- ```sql lowercase
SELECT * 
FROM public.table;
```

```SQL
-- ```SQL uppercase
SELECT * 
FROM public.table
```

```python
# ```python lowercase
import this
s = "abc" 'abc'
a = 1 + 2 
```

```PYTHON
# ```PYTHON uppercase
import this
s = "abc" 'abc'
a = 1 + 2 
```

**Comment by pbek** [comment]
@Waqar144?

**Comment by Waqar144** [comment]
I guess we should just lower case the language identifier unconditionally always. This would fix it hopefully

**Comment by pbek** [comment]
Go for it. 😁

**Comment by pbek** [comment]
## 21.6.4
- the note preview can now also highlight code blocks with uppercase identifiers

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by martinbra** [comment]
@pbek thanks, it works!
But then I have found another issue: the syntax highlighting in the preview panel only works after I edit the note. If I am just browsing around different notes the markdown is parsed correctly, but the highlighting only works after I edit the file (add a space anywhere, for instance). I tried on the previous version too, 21.6.3, and the bug was already there.

**Comment by pbek** [comment]
Great, thank you for testing!

I can't reproduce that. Can you please open another issue with more information (example notes, etc.).
