### ISSUE TITLE
[I] Assigning a shortcut to "show subfolders panel" works for hiding the panel but not for showing it.

### ISSUE THREAD

**Issue by wissssam** [pbek/QOwnNotes#2162]
#### Expected behaviour

Assigning a shortcut to "show subfolders panel" you should be able to show or hide the panel.

#### Actual behaviour

Assigning a shortcut to "show subfolders panel" is not showing the panel, but it hides it if it is already shown.
**Note**: assigning shortcuts to showing and hiding "note search" and "note list" panels works fine for me,
**Note**: I tried changing the shortcut with no success.

#### Steps to reproduce

* Assign a shortcut to "show subfolders panel" in settings
* use that shortcut to show the panel (it's not working)
* show the panel manually and try to hide it with the same shortcut (it works)

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fri Jun 18 16:09:01 2021`
**Version**: `21.6.2`
**Build date**: `Jun 13 2021`
**Build number**: `841`
**Platform**: `linux`
**Operating System**: `EndeavourOS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/home/wissam/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/wissam/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1366x768`
**Icon theme**: `breeze`
**Notes in current note folder**: `5`
**Calendar items**: `0`
**Enabled scripts**: `2`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/home/wissam/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `2`

### Note folder `default`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `-2`
**localPath**: `/home/wissam/Documents`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/wissam/Documents/notes.sqlite`

### Note folder `My Notes`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/wissam/Documents/My Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/wissam/Documents/My Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

### Script `List maker`

**id**: `7`
**path**: `/home/wissam/.local/share/PBE/QOwnNotes/scripts/list-maker/list-maker.qml`
**variablesJson**: 
```
{
    "setLetters": "abcdefghijklmnopqrstuvwxyz",
    "setMarkers": "- • ‣"
}
```
**identifier**: `list-maker`
**version**: `0.0.2`
**minAppVersion**: `17.07.8`

### Script `Text Highlights`

**id**: `9`
**path**: `/home/wissam/.local/share/PBE/QOwnNotes/scripts/text-highlights/text-highlights.qml`
**variablesJson**: 
```
{
    "backgroundColor": "#FFFF00"
}
```
**identifier**: `text-highlights`
**version**: `0.0.4`
**minAppVersion**: `20.6.0`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**DistractionFreeMode/editorWidthMode** (QString): `2`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `30`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `/home/wissam/Documents/Documents`
**FileDialog/LastPath-ImportTextFiles** (QString): `/home/wissam/Documents/Documents`
**FileDialog/LastPath-NoteHTMLExport** (QString): `/home/wissam/Documents/Documents`
**FileDialog/LastPath-NotePDFExport** (QString): `/home/wissam/Documents/Documents`
**ImageDialog/disableCopying** (bool): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-06-18T15:37:35.683`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Hack,10,-1,7,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Noto Kufi Arabic,10,-1,0,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Hack,10,-1,7,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/layoutwidget-use-layout** (QString): `16384`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QString): `Welcome to QOwnNotes`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteFolder-2/NoteTabNameList** (QStringList): `The Secret Life Of Programs`
**NoteFolder-2/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-2/NoteTabSubFolderPathDataList** (QStringList): `Books`
**NoteFolder-2/allowDifferentNoteFileName** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 3 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 32 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `2`
**NoteHistoryCurrentIndex-2** (int): `31`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExport** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-actionJump_to_navigation_panel** (QString): `Shift+F8`
**Shortcuts/MainWindow-actionJump_to_note_list_panel** (QString): `Shift+F4`
**Shortcuts/MainWindow-actionJump_to_note_subfolder_panel** (QString): `Shift+F6`
**Shortcuts/MainWindow-actionJump_to_note_text_edit** (QString): `Shift+F5`
**Shortcuts/MainWindow-actionJump_to_tags_panel** (QString): `Shift+F7`
**Shortcuts/MainWindow-togglePanel-noteListDockWidget** (QString): `F4`
**Shortcuts/MainWindow-togglePanel-noteSearchDockWidget** (QString): `F5`
**Shortcuts/MainWindow-togglePanel-noteSubFolderDockWidget** (QString): `F3`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**TagAddDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `2`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `24`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `true`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/wissam/Documents/My Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `55983095-a18c-4b84-80e9-9fd3a8cee490`
**recentNoteFolders** (QString): `/home/wissam/Documents`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2021-06-11T07.54.40, mariadb`
**savedSearches/noteFolder-2** (QStringList): `Note 2021-06-15T18.39.43, Note 2021-06-15T18.32.04, mysql, QOwnNotes Web Companion browser extension QOwnNotes, Note f3ec0618-7c9f-494a-a26d-27df6776395a, Note 3ca3e86e-53f7-42a8-93c4-830d03d7cd5d, Markdown Reference 2021-06-12T10.02.58, Markdown Reference 2021-06-12T10.02.55, Note ceddbaa0-fba8-40f0-b84e-29712667e6e3, Markdown Reference 2021-06-12T10.02.14, Markdown Reference 2021-06-12T10.02.11, Markdown Reference, 3.1 Congruence, Note f914ad22-2303-4168-8d50-e044f41b6f3e, Note e7a68467-b3ea-42a8-a42a-15edcc9a749b, Markdown Reference 2021-06-12T09.54.51, Markdown Reference 2021-06-12T09.54.32, Markdown Reference 2021-06-12T09.54.22, Note b37ddc92-df63-4b49-9f67-28e04f6d21e7, Shortcuts QOwnNotes, Note 2021-06-11T13.55.48, Note 2021-06-11T07.56.14, Note 2021-06-11T07.56.10`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QString): `action_Quit`
**toolbar/5/name** (QString): `quitToolbar`
**toolbar/5/title** (QString): `quit toolbar`
**toolbar/6/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/6/name** (QString): `windowToolbar`
**toolbar/6/title** (QString): `window toolbar`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useSoftWrapInNoteEditor** (QString): `true`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**webSocketServerService/token** (QString): `<hidden>`
**workspace-55983095-a18c-4b84-80e9-9fd3a8cee490/name** (QString): `test`
**workspace-55983095-a18c-4b84-80e9-9fd3a8cee490/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-55983095-a18c-4b84-80e9-9fd3a8cee490/windowState** (QByteArray): `<binary data>`
**workspace-KksEqfFVnaBP/name** (QString): `Full`
**workspace-KksEqfFVnaBP/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-KksEqfFVnaBP/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspace-mRn4NXwDNhmk/name** (QString): `Preview only`
**workspace-mRn4NXwDNhmk/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-mRn4NXwDNhmk/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, mRn4NXwDNhmk, KksEqfFVnaBP, 55983095-a18c-4b84-80e9-9fd3a8cee490`

## System environment

**SHELL**: `/bin/bash`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**LC_ADDRESS**: `en_US.UTF-8`
**LC_NAME**: `en_US.UTF-8`
**DESKTOP_SESSION**: `plasma`
**LC_MONETARY**: `en_US.UTF-8`
**GTK_MODULES**: `canberra-gtk-module`
**XDG_SEAT**: `seat0`
**PWD**: `/home/wissam`
**XDG_SESSION_DESKTOP**: `KDE`
**LOGNAME**: `wissam`
**XDG_SESSION_TYPE**: `x11`
**XAUTHORITY**: `/home/wissam/.Xauthority`
**MOTD_SHOWN**: `pam`
**HOME**: `/home/wissam`
**LC_PAPER**: `en_US.UTF-8`
**LANG**: `en_US.UTF-8`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**LC_IDENTIFICATION**: `en_US.UTF-8`
**USER**: `wissam`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**DISPLAY**: `:0`
**SHLVL**: `0`
**LC_TELEPHONE**: `en_US.UTF-8`
**LC_MEASUREMENT**: `en_US.UTF-8`
**XDG_VTNR**: `1`
**XDG_SESSION_ID**: `2`
**PT8HOME**: `/opt/packettracer/`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**LC_TIME**: `en_US.UTF-8`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**BROWSER**: `firefox`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**MAIL**: `/var/spool/mail/wissam`
**LC_NUMERIC**: `en_US.UTF-8`
**XCURSOR_THEME**: `breeze_cursors`
**XCURSOR_SIZE**: `24`
**KDE_FULL_SESSION**: `true`
**KDE_SESSION_VERSION**: `5`
**KDE_SESSION_UID**: `1000`
**KDE_APPLICATIONS_AS_SCOPE**: `1`
**XDG_CONFIG_DIRS**: `/home/wissam/.config/kdedefaults:/etc/xdg`
**SYSTEMD_EXEC_PID**: `1885`
**GTK_RC_FILES**: `/etc/gtk/gtkrc:/home/wissam/.gtkrc:/home/wissam/.config/gtkrc`
**GTK2_RC_FILES**: `/etc/gtk-2.0/gtkrc:/home/wissam/.gtkrc-2.0:/home/wissam/.config/gtkrc-2.0`
**SESSION_MANAGER**: `local/android:@/tmp/.ICE-unix/2014,unix/android:/tmp/.ICE-unix/2014`
</details>

**Comment by pbek** [comment]
Did you try to shortcut in your `default` note folder? Because there you have sub-folders disabled and thus you cannot use that panel.

**Comment by wissssam** [comment]
> Did you try to shortcut in your `default` note folder? Because there you have sub-folders disabled and thus you cannot use that panel.

No, I added a folder to my notes in settings and I am using it as my main notes folder
I tried the shortcut in default folder too and it didn't work like you said

**Comment by pbek** [comment]
I'll look into that.

**Comment by pbek** [comment]
Thank you, that was a regression from <https://github.com/pbek/QOwnNotes/commit/bac73f45533bd8682db4ecfc91b545c1eda5c0e8#diff-c72b037f3ac7abbd3d0ee519b6f456013a9bbf5a59df16308939320c04970447R1262>. It seems like nobody was turning the sub-folder panell off at run-time for a folder with enabled sub-folders. 😁

**Comment by pbek** [comment]
## 21.6.4
- fixed a problem when turning on the sub-folders panel after it was turned off
  for note folders with sub-folders

**Comment by pbek** [comment]
At least the setting still worked when restarting QON (and I guess also when switching workspaces).

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
>  Turning the side panels off gives me extra space for note editor and note preview

Do you use a different workspace for that view? You could define a workspace with all panels (e.g. when you need to jump to another sub-folder) and a workspace with only note editor and preview. There is a shortcut to switch between the last two workspaces.

**Comment by wissssam** [comment]
> There now is a new release, could you please test it and report if it works for you?

I tested the new release 21.6.4  and it's working thanks for that.



> Do you use a different workspace for that view? You could define a workspace with all panels (e.g. when you need to jump to another sub-folder) and a workspace with only note editor and preview. There is a shortcut to switch between the last two workspaces.

I know that I can define a workspace but using a shortcut for the switching between the last two workspaces didn't come to my mind and it is a good idea thanks again.

**Comment by pbek** [comment]
Great, thank you for testing!
You can script workspace switching (https://www.qownnotes.org/scripting/classes.html#properties-and-methods-4) and react on window state changes (https://www.qownnotes.org/scripting/hooks.html#windowstatechangedhook).
