### ISSUE TITLE
Editor width configuration not respected

### ISSUE THREAD

**Issue by marcoXbresciani** [pbek/QOwnNotes#2163]
#### Expected behaviour
When setting the editor width to, say 72 characters and DEselecting the "Only use editor width setting in distraction free mode", the editor should show all 72 characters.

#### Actual behaviour
Even expanded to have a width wide enough, using a fixed width font the editor is not properly showing all characters in the width.

#### Steps to reproduce
![image](https://user-images.githubusercontent.com/48018419/122747636-99f21b80-d28b-11eb-846e-f3418fef8a37.png)
Select a fixed width font (e.g.: Courier New, Fira Code, FreeMono, ...)

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `lun giu 21 12:24:29 2021`
**Version**: `21.6.4`
**Build date**: `Jun 20 2021`
**Build number**: `843`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 1909`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `yes`
**Settings path / key**: `C:/Users/marco.bresciani/QOwnNotes/Data/PBE/QOwnNotes.ini`
**Application database path**: `C:\Users\marco.bresciani\QOwnNotes\Data\QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes.exe`, `--portable`
**Qt Debug**: `0`
**Locale (system)**: `it_IT`
**Locale (interface)**: `en`
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `18`
**Calendar items**: `0`
**Enabled scripts**: `2`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\marco.bresciani\QOwnNotes\Data\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `C:\Users\marco.bresciani\QOwnNotes\Data\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `Random Notes`
**database file**: `C:\Users\marco.bresciani\QOwnNotes\Data\Notes\notes.sqlite`

### Cloud connection ``

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

### Script `Note stats`

**id**: `1`
**path**: `C:\Users\marco.bresciani\QOwnNotes\Data\scripts\note-stats\note-stats.qml`
**variablesJson**: 
```
{
    "charSpaceName": "Chars",
    "readTimeName": "Reading time",
    "readTimeRate": 300,
    "wordsLeftTarget": 0,
    "wordsName": "Words"
}
```
**identifier**: `note-stats`
**version**: `0.0.2`
**minAppVersion**: `17.06.3`

### Script `Meeting note`

**id**: `2`
**path**: `C:\Users\marco.bresciani\QOwnNotes\Data\scripts\meeting-note\meeting-note.qml`
**variablesJson**: 
```
{
    "defaultFolder": "Kaizen Journal",
    "defaultTags": "",
    "headlinePrefix": "",
    "isAskForDateString": false,
    "noteBodyTemplate": "<!--\n© 2021 Marco Bresciani\n\nCopying and distribution of this file, with or without modification, are\npermitted in any medium without royalty provided the copyright notice\nand this notice are preserved.\nThis file is offered as-is, without any warranty.\n\nSPDX-FileCopyrightText: 2021 Marco Bresciani\n\nSPDX-License-Identifier: FSFAP\n-->\n# Reflect on the Last Step Taken\n1. What did you plan as your **Last Step**?\n1. What did you **Expect**?\n1. What **Actually Happened**?\n1. What did you **Learn**?\n"
}
```
**identifier**: `meeting-note`
**version**: `1.4.0`
**minAppVersion**: `20.4.16`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**DistractionFreeMode/editorWidthCustom** (int): `72`
**DistractionFreeMode/editorWidthMode** (int): `5`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `18`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/ColorSchemes**: *empty*
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-514803c6-84ff-4da5-84a6-26c1989a49bb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `false`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (bool): `true`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**FileDialog/LastPath** (QString): `C:/Users/marco.bresciani/OneDrive - KERING SA/Bureau`
**FileDialog/LastPath-SchemaExport** (QString): `C:/Users/marco.bresciani/OneDrive - KERING SA/Bureau`
**LastUpdateCheck** (QDateTime): `2021-06-21T11:48:26.628`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `15`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Kaizen Journal, Kaizen Journal/2021, doc`
**MainWindow/noteTextEdit.code.font** (QString): `FreeMono,11,-1,5,50,0,0,0,0,0,Normale`
**MainWindow/noteTextEdit.font** (QString): `FreeMono,11,-1,5,50,0,0,0,0,0,Normale`
**MainWindow/noteTextView.code.font** (QString): `Fira Code,8,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8,-1,5,50,0,0,0,0,0,Normale`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `false`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `false`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `false`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/move-notes** (QString): `16384`
**MessageBoxOverride/remove-notes** (QString): `16384`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QString): `2024-04-13 Reflect on the Last Step Taken`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QString): `Kaizen Journal`
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `199`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `8`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `true`
**StartHidden** (bool): `false`
**StoredImagesDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `false`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `82e017c9-740f-4f15-8f82-3dc17d6d794a`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `false`
**enableWebAppSupport** (bool): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `true`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `true`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): `yyyy-MM-dd HH:mm:ss`
**interfaceFontSize** (int): `10`
**interfaceLanguage** (QString): `en`
**internalIconTheme** (bool): `false`
**itemHeight** (int): `15`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `1`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `false`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `false`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `5`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `0`
**notesPath** (QString): `Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `8814ee3e-b804-43c3-b8d1-02e91bb569e1`
**restoreCursorPosition** (bool): `false`
**restoreLastNoteAtStartup** (bool): `false`
**restoreNoteTabs** (bool): `false`
**savedSearches/noteFolder-1** (QStringList): `Note 2021-06-21T11.52.07, Note 2021-06-17T15.27.31, Note 2021-06-17T15.24.46, Note 2021-06-17T08.59.27, Note 2021-06-17T08.44.42, Note 2021-06-10T08.36.44, Note 2021-06-09T17.16.44, Note 2021-06-03T15.06.18, Note 2021-06-03T10.19.31, Note 2021-06-01T11.59.23, Note 2021-05-31T09.52.54, Note 2021-05-31T08.45.12, Note 2021-05-28T11.44.24, Note 2021-05-28T09.19.17, Note 2021-05-28T09.01.43, Note 2021-05-27T08.53.46, Note 2021-05-27T08.53.41, Note 2021-05-27T08.53.36, Note 2021-05-27T08.53.30, Note 2021-05-27T08.53.18, Note 2021-05-27T08.53.10, Note 2021-05-27T08.53.04, Note 2021-05-27T08.52.46, Note 2021-05-18T10.32.44, Note 2021-05-17T14.42.48, Note 2021-05-14T11.16.14, Note 2021-05-14T11.15.59, Note 2021-05-12T10.30.56, Note 2021-05-12T09.40.31, Note 2021-05-12T09.40.24, Note 2021-05-12T09.40.01, Note 2021-05-11T10.00.51, Note 2021-05-11T09.23.45, Note 2021-05-06T15.20.26, Note 2021-05-06T10.17.09, Note 2021-05-06T10.16.15, Note 2021-05-06T10.09.57, Note 2021-05-06T10.08.56, Note 2021-05-05T10.01.14, Note 2021-05-04T17.14.08, Note 2021-04-29T15.10.25, Note 2021-04-29T10.32.07, Note 2021-04-28T16.44.28, Note 2021-04-28T10.26.53, Note 2021-04-27T08.44.07, Note 2021-04-27T08.41.32, Note 2021-04-26T16.02.13, Note 2021-04-26T11.51.18, Note 2021-04-26T11.30.04, Note 2021-04-26T10.41.58, Note 7b7da6cb-78f1-4e14-8698-8f9a7f93d6e4, Note 86d288c9-2ef9-4c94-834b-8b8679b81007, Note b2412908-83f3-4f18-a418-27cb745e2abf, Note 2021-04-22T08.47.32, Note 2021-04-21T16.12.21, Note 2021-04-20T09.20.43, Note 2021-04-20T09.20.30, Note 2021-04-16T11.18.11, Note 2021-04-16T10.39.08, Note 2021-04-15T13.40.43, Note 2021-04-14T10.31.35, Note 2021-04-13T09.03.05, Note 2021-04-13T09.01.44, Note 2021-04-09T08.59.53, Note 2021-04-08T09.01.54, Note 2021-04-08T09.01.31, Note d3496b89-e7ff-4a9d-941b-f254b1c44d5c, Note 2021-04-07T09.50.54, Note 2021-04-01T14.37.08, Note 2021-04-01T14.31.19, Note 2021-04-01T08.40.12, Note 2021-03-31T08.57.26, Note 2021-03-31T08.57.16, Note 2021-03-31T08.56.36, Note 2021-03-30T08.05.24, Note 2021-03-29T10.51.39, Note 2021-03-29T10.26.59, Note 2021-03-29T10.26.21, Note 2021-03-29T10.24.54, Note 2021-03-29T10.20.36, Note 2021-03-29T10.18.52, Note 2021-03-29T09.52.51, Note 2021-03-29T09.42.41, Note 2021-03-29T09.38.46, Note 2021-03-29T09.37.54, Note 2021-03-29T09.37.19, Note 2021-03-29T09.36.40, Note 2021-03-29T09.35.45, Note 2021-03-29T09.35.26, Note 2021-03-29T08.27.33, Note 2021-03-29T08.25.02, Note 2021-03-29T08.24.03, Note 2021-03-29T08.12.05`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, `
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (bool): `false`
**useSoftWrapInNoteEditor** (QString): `false`
**useUNIXNewline** (bool): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-82e017c9-740f-4f15-8f82-3dc17d6d794a/name** (QString): `Normale`
**workspace-82e017c9-740f-4f15-8f82-3dc17d6d794a/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-82e017c9-740f-4f15-8f82-3dc17d6d794a/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `82e017c9-740f-4f15-8f82-3dc17d6d794a`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**ANDROID_HOME**: `C:\Users\marco.bresciani\AppData\Local\Android\Sdk`
**ANDROID_SDK_ROOT**: `C:\Users\marco.bresciani\AppData\Local\Android\Sdk`
**APPDATA**: `C:\Users\marco.bresciani\AppData\Roaming`
**ChocolateyInstall**: `C:\ProgramData\chocolatey`
**ChocolateyLastPathUpdate**: `132645940048868119`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `9BBPK13-ITL`
**ComSpec**: `C:\windows\system32\cmd.exe`
**COR_ENABLE_PROFILING**: `1`
**COR_PROFILER**: `{B74E4EB1-99CB-4B76-AF5F-2A0A973DC9A9}`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\marco.bresciani`
**HOST_RUNTIME_PROPERTY**: `C:\Users\marco.bresciani\Projects\host.properties`
**HYB_ENV_CODE**: `local-development`
**LOCALAPPDATA**: `C:\Users\marco.bresciani\AppData\Local`
**LOGONSERVER**: `\\CHDC5SDC001`
**NUMBER_OF_PROCESSORS**: `12`
**OneDrive**: `C:\Users\marco.bresciani\OneDrive - KERING SA`
**OneDriveCommercial**: `C:\Users\marco.bresciani\OneDrive - KERING SA`
**OS**: `Windows_NT`
**Path**: `C:\Python39\;C:\Python39\Scripts\;C:\Python27\Scripts;C:\Python27\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;c:\program files\graphicsmagick-1.3.28-q8;c:\program files\graphicsmagick-1.3.28-q16;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\IBM\Client Access\Shared;C:\Program Files (x86)\IBM\Client Access\;C:\Program Files\PowerShell\7-preview\preview;C:\Program Files\TortoiseHg\;C:\ProgramData\chocolatey\bin;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\TortoiseGit\bin;C:\Program Files\nodejs\;C:\Program Files\Amazon\AWSSAMCLI\bin\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\marco.bresciani\AppData\Local\Android\Sdk\tools;C:\Users\marco.bresciani\AppData\Local\jdk-11.0.2\bin;C:\Ruby30-x64\bin;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\marco.bresciani\AppData\Local\Microsoft\WindowsApps;C:\curl-7.68.0-win64-mingw\bin\;C:\Users\marco.bresciani\Projects\gucci\winutilities\;C:\Users\marco.bresciani\Projects\tools\;C:\Program Files\MySQL\MySQL Server 8.0\bin\;C:\Program Files (x86)\GnuWin32\bin;C:\groovy-3.0.0\bin\;C:\Program Files (x86)\FontForgeBuilds\bin;C:\apache-maven-3.6.3\bin;C:\Program Files\Graphviz\bin;C:\Users\marco.bresciani\AppData\Roaming\npm;C:\Users\marco.bresciani\.dotnet\tools;C:\Users\marco.bresciani\AppData\Local\Android\Sdk\platform-tools;C:\Users\marco.bresciani\AppData\Roaming\Python\Python39\Scripts;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW`
**POWERSHELL_DISTRIBUTION_CHANNEL**: `MSI:Windows 10 Pro`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 158 Stepping 13, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `9e0d`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PROMPT**: `$P$G`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\windows`
**TEMP**: `C:\Users\MARCO~1.BRE\AppData\Local\Temp`
**TMP**: `C:\Users\MARCO~1.BRE\AppData\Local\Temp`
**UATDATA**: `C:\windows\CCM\UATData\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77`
**USERDNSDOMAIN**: `EMEA.GUCCIGROUP.DOM`
**USERDOMAIN**: `EMEA`
**USERDOMAIN_ROAMINGPROFILE**: `EMEA`
**USERNAME**: `marco.bresciani`
**USERPROFILE**: `C:\Users\marco.bresciani`
**windir**: `C:\windows`
**QML_DISABLE_DISK_CACHE**: `true`

</details>

#### Relevant log output in the Log panel

This below appeared when selecting FreeMono font:
<details><summary>Expand</summary>
[12:28:45] [warning] DirectWrite: CreateFontFaceFromHDC() failed (Indica un errore in un file di input come un file di tipi di carattere.) for QFontDef(Family="8514oem", pointsize=8.25, pixelsize=20, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("8514oem", lfWidth=0, lfHeight=-20) dpi=96
[12:29:00] [scripting] loading script file: C:/Users/marco.bresciani/QOwnNotes/Data/scripts/note-stats/note-stats.qml
[12:29:00] [scripting] loading script file: C:/Users/marco.bresciani/QOwnNotes/Data/scripts/meeting-note/meeting-note.qml
</details>

This appeared when selecting DejaVu Sans Mono font:
<details><summary>Expand</summary>
[12:29:46] [warning] DirectWrite: CreateFontFaceFromHDC() failed (Indica un errore in un file di input come un file di tipi di carattere.) for QFontDef(Family="8514oem", pointsize=8.25, pixelsize=20, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("8514oem", lfWidth=0, lfHeight=-20) dpi=96
[12:30:06] [scripting] loading script file: C:/Users/marco.bresciani/QOwnNotes/Data/scripts/note-stats/note-stats.qml
[12:30:06] [scripting] loading script file: C:/Users/marco.bresciani/QOwnNotes/Data/scripts/meeting-note/meeting-note.qml
</details>

Similar when choosing SourceCode Pro font:

<details><summary>Expand</summary>
[12:31:06] [warning] DirectWrite: CreateFontFaceFromHDC() failed (Indica un errore in un file di input come un file di tipi di carattere.) for QFontDef(Family="8514oem", pointsize=8.25, pixelsize=20, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("8514oem", lfWidth=0, lfHeight=-20) dpi=96
[12:31:34] [scripting] loading script file: C:/Users/marco.bresciani/QOwnNotes/Data/scripts/note-stats/note-stats.qml
[12:31:34] [scripting] loading script file: C:/Users/marco.bresciani/QOwnNotes/Data/scripts/meeting-note/meeting-note.qml
</details>

**Comment by pbek** [comment]
The thing is that you can't really set an editor width in a QPlainTextEdit, you can only set a margin.
And that margin is estimated by measuring `0` characters and the current editor width.

See: https://github.com/pbek/QOwnNotes/blob/8a3f167fe28612a3a67522f84370b16305f87b4c/src/widgets/qownnotesmarkdowntextedit.cpp#L330-L375

It seems like the estimation algorithm doesn't work very well for mono-space fonts or that font in particular.

**Comment by marcoXbresciani** [comment]
Why the size of `0` instead of `M` that is (should be) the widest character?

**Comment by pbek** [comment]
> Why the size of 0 instead of M that is (should be) the widest character?

Because then the margin would be too small for all other characters.

> Also, just noted that log wrote something about "8514oem" font that is the first font in my list (don't know where it comes from, actually), but I've selected another font!

I've never seen such an error. Maybe the font dialog reported it because the font itself has an issue?

**Comment by pbek** [comment]
## 21.6.5
- when you are changing the editor font in the settings you will get now a dialog box that
  you might need to restart the application (for [#2163](https://github.com/pbek/QOwnNotes/issues/2163))
- an attempt was made to improve the editor margin calculation by searching
  for the word `mono` in the font family and handling those potentially monospaced
  fonts differently (for [#2163](https://github.com/pbek/QOwnNotes/issues/2163))

**Comment by pbek** [comment]
Should work a little bit better now if the monospaced font has the word "mono" in it. It's sad that there doesn't seem to be a way to find out more reliably if a font is monospaced.

There now is a new release, could you please test it and report if it works for you?

**Comment by marcoXbresciani** [comment]
Nope. Same behaviour, 54 characters visible choosing FreeMono or DejaVu Sans Mono font.

And still that stupid font that I can't event remove (probably installed by corporate or something):
```
[19:34:15] [warning] DirectWrite: CreateFontFaceFromHDC() failed (Indica un errore in un file di input come un file di tipi di carattere.) for QFontDef(Family="8514oem", pointsize=8.25, pixelsize=20, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("8514oem", lfWidth=0, lfHeight=-20) dpi=96
[19:34:29] [scripting] loading script file: C:/Users/marco.bresciani/QOwnNotes/Data/scripts/note-stats/note-stats.qml
```

Also, to understand if a font is monospaced, simply measure `11111111` and `99999999` widths. If they are the same...

**Comment by pbek** [comment]
Are you sure you are using the latest release?
For me for a custom width of 70 I get about 72 characters with FreeMono and about the same with Noto Sans, which is great.

![image](https://user-images.githubusercontent.com/1798101/122811136-64bbec80-d2d0-11eb-8adb-46f0f4cfe91d.png)

Maybe it's an issue that you turned soft wraps off.

> Also, to understand if a font is monospaced, simply measure 11111111 and 99999999 widths. If they are the same...

The space is the same for each character in monospaced fonts. I did my "calibration" with just `0` and tested with just zeros in the note text in different fonts and the measurements where always off regardless of what I used.

The amount of characters in that setting will never be exactly what they say, because I can only work with pixel and not with "characters".

**Comment by marcoXbresciani** [comment]
Hello @pbek I was swondering if measuring the width of 111 and 999 would help you distinguish between monospaced and other fonts, instead of looking at font name. It should be that the width in pixel, for monospaced, should be the same, regardless the string you check.

No need for the soft wraps. I've just turned off the app a couple of time, changed font again (FreeMono) and now it's working perfectly!

Thanks.

**Comment by pbek** [comment]
> I was wondering if measuring the width of 111 and 999 would help you distinguish between monospaced and other fonts, instead of looking at font name

ah, now I understand what you meant.
that's actually a great idea!

**Comment by marcoXbresciani** [comment]
Probably an even better comparison would be between `llllllll` (small caps L) or `iiiiiiii` and `MMMMMMMM` or `WWWWWWWW`. 😄

**Comment by pbek** [comment]
Yes, 0 and 1 have the same width in Noto Sans. I will use `iiiii` and `WWWWW`.

**Comment by pbek** [comment]
## 21.6.6
- the monospaced font detection was improved by comparing the width of `iiiii`
  to `WWWWW` (for [#2163](https://github.com/pbek/QOwnNotes/issues/2163))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by marcoXbresciani** [comment]
Tried setting [Fira Code](https://github.com/tonsky/FiraCode) font (monospaced, but not in the name) and it works perfectly: since it's slightly bigger then FreeMono or DejaVu Sans Mono, I obviously had to increase the editor width, but it's normal.
Perfect.

**Comment by pbek** [comment]
Great, thank you for testing and for the idea! 😁
