### ISSUE TITLE
0xc000007b

### ISSUE THREAD

**Issue by roxetak** [pbek/QOwnNotes#2164]
I have a problem to start portable QOwnNotes. 

QOwnNotesPortable.exe - Application Error

The application was unabel to start correctly (0xc000007b). Click OK to close the application.

What Can I do. I try reinstall, I try close portable applications, remove USB flash key. And again start the portable apps and QOwnNotes. Doesn´t help.

**Comment by pbek** [comment]
> The application was unabel to start correctly (0xc000007b). Click OK to close the application.

That doesn't sound like an error from QOwnNotes directly. The internet is full of reports of this error code.

1) What version of Windows do you have?
2) Where did you get QOwnNotes from?
3) What happens if you start QOwnNotes in non-portable mode?

**Comment by roxetak** [comment]
So, I think that the problem is win 10, or windows defender, cause there is a problem start any portable application. Sometimes run or start instalation of portable apps.

**Comment by pbek** [comment]
QOwnNotes doesn't have an installation.

**Comment by roxetak** [comment]
> QOwnNotes doesn't have an installation.

I know that. Thanks. Just unzip and run. :-D Exe file is only portable version. 

But I solved what I needed and want for a long time with QOwnNotes for win. I don´t need portable yet.

My problem is not problem QOwnNOtes, but portables apps, win 10 and windows defender. I think.

Thank you for your help

**Comment by pbek** [comment]
You don't need portableapps to run QOwnNotes in portable mode, just use regular QOwnNotes (in portable mode if you really need it): https://www.qownnotes.org/installation/windows.html
