### ISSUE TITLE
Looking for users who are willing to share their precious experiences with other users

### ISSUE THREAD

**Issue by Fabijenna** [pbek/QOwnNotes#2167]
We're looking for users who are willing to share their experiences with QOwnNotes, with other users. 

Few things that I'd like you to mention about yourselves, how long have you been using QOwnNotes, how did you find the Software, and what relationship you had with it so far, e.g. advanced user or freshman, tell us a little bit about yourself, and then please go into detail and present that part or feature you've been using successfully.

This https://www.youtube.com/watch?v=XSqtcndpHt8 is just an example, but we're working on more. 
Your support is very appreciated.

**Comment by pbek** [comment]
Seems like most of the users want to stay in the shadow. 😅

**Comment by Fabijenna** [comment]
> Seems like most of the users want to stay in the shadow. 😅

That's what lead me to create an anonymous survey for statistics. We could have many more questions and style it better, I think that anonymous data will help others to also step into the light.

**Comment by pbek** [comment]
In my experience >99% of people just don't care to fill out surveys. 😅

**Comment by Fabijenna** [comment]
My experience is different. I worked for Gallup years ago and I was getting tons and tons of completed interviews with up to an hour length. People like questions and I offered them some.

PR is always a bit weary, it’s better to say bye to ideas of bad outcomes.

It’s surely different from coding, and I haven’t even really started. PR’s just putting on her shoes.

**Comment by Fabijenna** [comment]
The answer to people who like to stay in the shadow but are open for giving feedback, the best way is a short survey, when they got to say something before they are ready to participate, subscribe, comment and like. (imo)
If the word survey sounds just a bit too much for "most people", let's just say "answer a very few / 8 questions. 

Get as much as possible statistical insight into the audience of QON is basic to every more powerful PR action. (imo)

**Comment by Fabijenna** [comment]
What’s your vision?

**Comment by pbek** [comment]
Vision for what?

**Comment by Fabijenna** [comment]
Well, I frequently hear what’s not according but you might try sharing your ideas or visions.

In any way. I am ready to construct whatever you wanna see, but for me it would be better if your critics came along with your expectations.

For example you said that people don’t care for surveys.

Most of all if I don’t like an idea I have immediately a better idea, it might be likewise with you.

But if you could share your whole vision for QON public talk, that’d be best. Then I can absorb it mentally and create from it. 

That could be very effective, better than I make up visions that you might not share...

PR is one kind of idea for communication that all the maintainers basically all share.

**Comment by Fabijenna** [comment]
![Bildschirmfoto 2021-07-04 um 16 21 24](https://user-images.githubusercontent.com/17498644/124397676-ace7ff80-dd11-11eb-9d08-a663f4cbdd5e.png)

**Comment by Fabijenna** [comment]
Punkt 1 an welche verschiedenen Teilöffentlichkeiten richtet sich die PR Kommunikation
Punkt 2 welche Konsistenz zwischen diesen soll dauerhaft bestehen

**Comment by pbek** [comment]
Most of the time the users have interesting ideas or are seeing interesting things elsewhere and then are posting feature requests on github. Then I'll look at them and see how feasible they are.

**Comment by Fabijenna** [comment]
Hi @Waqar144, would you like sharing the nature of your actual or future communication with users? I asked pbek the same question (above, in other words) and it'd be relevant for me to include you too. In case you'd rather not answer, I guess I figure it out somehow. Anyway, take your time please, I understand if you aren't ready, just let me know if you will think about sharing it later.

What I will do is conceptionalize a few more YouTubes with the goal of firstly representing QON along the statements you guys made, and secondly to get some qualitative responses from users too, e.g. in comments.

I want to collect a few direct responses from users via YT  along with other data at reach, and create a preliminary image of QON's target audience, e.g. redirect users to submit issues, questions, etc. In the meanwhile I can figure out more of what I probably will need to shape my message. 

Before I take any action I will share the videos etc with you for agreement.

Have a nice day!

**Comment by Fabijenna** [comment]
pls also share any oppositions or questions or constructive criticism of this approach

**Comment by Waqar144** [comment]
Hi, yes. I got your message about it as well, yesterday? I think. However, I do not have a lot of free time these so apologies.

Anyways, the nature of my communication with users ... Not really sure how best to answer that question. I would say, the only communication that happens between other users and me is on bug reports or in the Telegram group. That is all, I guess. About future, not sure but I think it will be same more or less.

**Comment by Waqar144** [comment]
About the approach, I think it's worth a try but I think a lot of users will stay in the shadows and won't even like being communicated at all however, I am not a people person, so could be totally wrong. 

In general I think for softwares PR won't really work. I think softwares get popular when the users like it and/or it's really good at what it does. However, doesn't apply for all softwares and there's definitely some marketing that needs to be done.

**Comment by Fabijenna** [comment]
I understood, @Waqar144 
I’ll not bother you with questions again, anyway thank you for instructing me about your position. 

@pbek I think that we’ve been a good team in solving problems and I’d like to continue with you in realizing my vision how to assist fulfilling some visions to support everyone to find QON. 

If you have oppositions to my idea just tell me and I’ll terminate my business around the QON job. TY for paying attention.

**Comment by pbek** [comment]
Currently the word about QOwnNotes is mainly spread by "word of mouth" and articles/posts/comments/videos from independent parties. The more followers those parties have the higher the "spike of new users". I guess open a new channel that has no followers is almost futile. That channel would have need to have followers already established to get some traction.
