### ISSUE TITLE
Subitems in ordered lists are not show correctly in the preview

### ISSUE THREAD

**Issue by alk0** [pbek/QOwnNotes#2169]
#### Expected behaviour

1. One
    1. Two
2. Three

(this or similar)

#### Actual behaviour

1. One 2. Two
2. Three

#### Steps to reproduce

```
1. One
    2. Two
3. Three
```

QOwnNotes' own documentation implicitly [mentions](https://www.qownnotes.org/getting-started/markdown.html#lists) ordered sublists.

(Tested on QOwnNotes - version 21.6.7 - AUR - build 846)

**Comment by pbek** [comment]
Thank you for reporting, I guess you are talking about how ordered sub-lists are presented in the preview (they are working fine in the editor), right?

@Waqar144, above example produces:

```html
<ol>
<li>One
2. Two</li>
<li>Three</li>
</ol>
```

Didn't that already work?

**Comment by alk0** [comment]
> I guess you are talking about how ordered sub-lists are presented in the preview (they are working fine in the editor), right?

Uhm, yes, right, it's about the preview. Technically, not all Markdown dialects/libraries support ordered sub-lists, but I hoped QOwnNotes would, since it's mentioned in the docs:

```
1. First ordered list item
2. Another item
  * Unordered sub-list.
1. Actual numbers don't matter, just that it's a number
  1. Ordered sub-list
4. And another item.

* Unordered list can use asterisks
- Or minuses
+ Or pluses
```

**Comment by pbek** [comment]
I don't remember is this worked before we started using https://github.com/mity/md4c.

> but I hoped QOwnNotes would, since it's mentioned in the docs

That was more about highlighting in the editor and automatic numbering when you enter a new line in the list. 😅

**Comment by Waqar144** [comment]
md4c usually closely follows CommonMark standard, not sure if they have plans to support this.

We didn't explicitly support it as well, it just got supported implicitly somehow.

**Comment by pbek** [comment]
> it just got supported implicitly somehow.

It did? When? How? 😁  And why not any more? 😅

**Comment by Waqar144** [comment]
I mean in the editor, I haven't checked myself if it works or not, but if it does then it wasn't intentionally implemented

**Comment by pbek** [comment]
Then I'll add a note in the QOwnNotes markdown documentation.

**Comment by pbek** [comment]
At least lists like this work:

```
- level 1
    1. test
    2. test
        - level 3
        - level 3b
- level 1b
```

**Comment by alk0** [comment]
Oh, I see. It's more a problem of CommonMark then, not even the library - `md4c` is just trying to strictly follow their (bad) specs. To compare: `pandoc` even in CommonMark mode still allows sub-lists (as it does for any other markdown flavor), `cmark` does it for all flavors, Typora with its own parser allows them, GitHub does, etc. But, for instance, `markdown-it` with its "100% CommonMark support" doesn't.
