### ISSUE TITLE
Bug: Very high load for nothing

### ISSUE THREAD

**Issue by Fischmuetze** [pbek/QOwnNotes#217]
Why is QOwnNotes using such a high load as it is an idle windows in the background?

![bildschirmfoto 2016-06-18 um 23 35 15](https://cloud.githubusercontent.com/assets/19834496/16173835/d76deb68-35ad-11e6-9c88-a907e67c1670.jpg)

**Comment by pbek** [comment]
Thank you for your report. I've never seen this before. When does that happen? Can you please post output from your log window (please enable all logs) and the debug output from your settings.

**Comment by Fischmuetze** [comment]
The log window is more or less entry ...  the high load appears also direct after the start of the app
1 entry
[12:33:17] [status] notes directory was modified externally

The operating system announced a very high load

![bildschirmfoto 2016-06-19 um 12 36 25](https://cloud.githubusercontent.com/assets/19834496/16176842/aa27132e-361a-11e6-97e5-4f851b595fb8.jpg)

Attached the debug information.
Btw. I removed the line with the geographical log entry
**com/apple/TimeZonePref/Last_Selected_City**
 - it's indecorously to collect such data for such a program ... 



QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `So. Juni 19 12:34:18 2016`
**Version**: `16.06.7`
**Build date**: `Jun 18 2016`
**Build number**: `1759`
**Platform**: `macosx`
**Operating System**: `OS X El Capitan (10.11)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.5.1`
**Qt Version (runtime)**: `5.5.1`
**Locale (system)**: `de_DE`
**Locale (interface)**: `en`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `50`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**connectionErrorMessage**: `Protocol "" is unknown`

## Settings

**646F6E7A_00000000_00000001_6E7A6361_696D6963**: `1`
**AKDeviceUnlockState**: `false`
**AppleActionOnDoubleClick**: `Minimize`
**AppleAntiAliasingThreshold**: `4`
**AppleAquaColorVariant**: `6`
**AppleHighlightColor**: `0.847059 0.847059 0.862745`
**AppleInterfaceStyle**: `Dark`
**AppleLanguages**: `de`
**AppleLocale**: `de_DE`
**AppleMeasurementUnits**: `Centimeters`
**AppleMetricUnits**: `true`
**AppleMiniaturizeOnDoubleClick**: `true`
**ApplePressAndHoldEnabled**: `false`
**AppleShowScrollBars**: `WhenScrolling`
**Country**: `DE`
**DistractionFreeMode/editorWidthMode**: `2`
**DistractionFreeMode/isEnabled**: `false`
**DistractionFreeMode/mainSplitterSizes**: `<binary data>`
**DistractionFreeMode/menuBarGeometry**: `<binary data>`
**DistractionFreeMode/menuBarHeight**: `0`
**DistractionFreeMode/windowState**: `<binary data>`
**InitialKeyRepeat**: `15`
**KeyRepeat**: `2`
**LastUpdateCheck**: `2016-06-19T12:33:05`
**LogDialog/criticalLog**: `true`
**LogDialog/debugLog**: `true`
**LogDialog/fatalLog**: `true`
**LogDialog/geometry**: `<binary data>`
**LogDialog/infoLog**: `true`
**LogDialog/scriptingLog**: `true`
**LogDialog/showAtStartup**: `true`
**LogDialog/statusLog**: `true`
**LogDialog/warningLog**: `true`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `24`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `Courier,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `.SF NS Text,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `Courier,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `.SF NS Text,13,-1,5,50,0,0,0,0,0`
**MainWindow/showRecentNoteFolderInMainArea**: `false`
**MainWindow/windowState**: `<binary data>`
**MultipleSessionEnabled**: `true`
**NSAutomaticDashSubstitutionEnabled**: `false`
**NSAutomaticQuoteSubstitutionEnabled**: `false`
**NSAutomaticSpellingCorrectionEnabled**: `false`
**NSAutomaticWindowAnimationsEnabled**: `true`
**NSDocumentSaveNewDocumentsToCloud**: `false`
**NSNavLastRootDirectory**: `~/Desktop`
**NSNavPanelExpandedSizeForOpenMode**: `{704, 438}`
**NSNavPanelExpandedSizeForSaveMode**: `{712, 510}`
**NSNavPanelExpandedStateForSaveMode**: `true`
**NSNavPanelFileLastListModeForOpenModeKey**: `2`
**NSNavPanelFileLastListModeForSaveModeKey**: `2`
**NSNavPanelFileListModeForOpenMode2**: `2`
**NSNavPanelFileListModeForSaveMode2**: `2`
**NSNavPanelSidebarKeyForOpen**: *empty*
**NSNavPanelSidebarKeyForSave**: *empty*
**NSNavRecentPlaces**: `~/ownCloud_HOME/Notes, ~/Desktop/2016-06-01 EREIGNIS, ~/Library/Mobile Documents/F2XAAD6WWR~com~app77~pwsafe/Documents, ~/Sites/inventory/libs/PHPExcel/Documentation, ~/ownCloud_HOME/Ressourcen/Backgrounds`
**NSPersonNameDefaultDisplayNameOrder**: `0`
**NSPersonNameDefaultShortNameFormat**: `0`
**NSPersonNameDefaultShouldPreferNicknamesPreference**: `0`
**NSPreferredWebServices**: *empty*
**NSTableViewDefaultSizeMode**: `1`
**NSUserDictionaryReplacementItems**: *empty*
**NSUserQuotesArray**: `„, “, ’, ’`
**NSWindow Frame NSFontPanel**: `2049 110 445 237 0 0 2560 1417 `
**NSWindowResizeTime**: `.0001`
**NavPanelFileListModeForOpenMode**: `2`
**NavPanelFileListModeForSaveMode**: `2`
**PMPrintingExpandedStateForPrint**: `true`
**PiwikClientId**: `<hidden>`
**ShowSystemTray**: `true`
**SortingModeAlphabetically**: `true`
**WebAutomaticSpellingCorrectionEnabled**: `false`
**_HIHideMenuBar**: `false`
**allowDifferentNoteFileName**: `false`
**allowOnlyOneAppInstance**: `false`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `false`
**appMetrics/notificationShown**: `true`
**com/apple/AppleModemSettingTool/LastCountryCode**: `DE`
**com/apple/ColorSync/Devices**: *empty*
**com/apple/CommonPanels/CalibrateDisplay/identifier-04272D41**: `com.apple.ColorSyncCalibrator`
**com/apple/CommonPanels/CalibrateDisplay/seed**: `-1120508567`
**com/apple/DictionaryServices**: *empty*
**com/apple/ink/framework**: *empty*
**com/apple/keyboard/fnState**: `true`
**com/apple/keyboard/modifiermapping/1452-545-0**: *empty*
**com/apple/mouse/scaling**: `1`
**com/apple/preferences/timezone/selected_city**: *empty*
**com/apple/sound/device/threshold**: `30488179`
**com/apple/springing/delay**: `0.5`
**com/apple/springing/enabled**: `true`
**com/apple/swipescrolldirection**: `false`
**com/apple/trackpad/enableSecondaryClick**: `true`
**com/apple/trackpad/fiveFingerPinchSwipeGesture**: `2`
**com/apple/trackpad/fourFingerHorizSwipeGesture**: `2`
**com/apple/trackpad/fourFingerPinchSwipeGesture**: `2`
**com/apple/trackpad/fourFingerVertSwipeGesture**: `2`
**com/apple/trackpad/momentumScroll**: `true`
**com/apple/trackpad/pinchGesture**: `true`
**com/apple/trackpad/rotateGesture**: `true`
**com/apple/trackpad/scrollBehavior**: `2`
**com/apple/trackpad/threeFingerDragGesture**: `false`
**com/apple/trackpad/threeFingerHorizSwipeGesture**: `2`
**com/apple/trackpad/threeFingerTapGesture**: `0`
**com/apple/trackpad/threeFingerVertSwipeGesture**: `2`
**com/apple/trackpad/twoFingerDoubleTapGesture**: `1`
**com/apple/trackpad/twoFingerFromRightEdgeSwipeGesture**: `3`
**com/apple/trackpad/version**: `5`
**com/apple/updatesettings_did_disable_ftp**: `true`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**customNoteFileExtensionList**: *empty*
**darkMode**: `false`
**darkModeColors**: `true`
**defaultNoteFileExtension**: `txt`
**disableAutomaticUpdateDialog**: `false`
**externalEditorPath**: *empty*
**ignoreAllExternalModifications**: `true`
**interfaceLanguage**: `en`
**mainSplitterSizes**: `<binary data>`
**mainSplitterState-0-0-1-0**: `<binary data>`
**mainSplitterState-0-0-1-1**: `<binary data>`
**mainSplitterState-0-1-1-0**: `<binary data>`
**mainSplitterState-0-1-1-1**: `<binary data>`
**mainSplitterState-1-0-1-1**: `<binary data>`
**markdownHighlightingInterval**: `0`
**markdownViewEnabled**: `false`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `0`
**noteListSplitterState**: `<binary data>`
**noteSaveIntervalTime**: `5`
**notesPath**: `/Users/steffen/ownCloud_HOME/Notes`
**notifyAllExternalModifications**: `false`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: *empty*
**ownCloud/todoCalendarBackend**: `1`
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloud/userName**: *empty*
**tagsEnabled**: `false`
**useSoftWrapInNoteEditor**: `false`
**verticalNoteFrameSplitterState**: `<binary data>`
**verticalPreviewModeEnabled**: `true`

**Comment by pbek** [comment]
> Btw. I removed the line with the geographical log entry

QOwnNotes doesn't do that... OS X collects this data in the plist file (no other OS does this). QOwnNotes simply reads all settings present in that file to generate that settings dump...

how long does the load stay so high?
does this happen every time you start QOwnNotes?
can you please try to move your `~/Library/Preferences/com.pbe.QOwnNotes.plist` away (while QOwnNotes is closed) so a new settings file will be created.

**Comment by Fischmuetze** [comment]
> QOwnNotes doesn't gather this information... 

Doesn't true as you described. This information isn't a part of  ~/Library/Preferences/com.pbe.QOwnNotes.plist 

> (no other OS does this). 

All modern OS collects data about the location (if the service is enabled)

> QOwnNotes simply reads all settings present in that file to generate that settings dump...

Might be you generate a dump of current settings of the QownNotes environment - right .. but you dump not only the plist file com.pbe.QOwnNotes.plist

This is the current content of my ~/Library/Preferences/com.pbe.QOwnNotes.plist files
As you can see the prevailing part of your dump isn't a part of the plist file 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>DistractionFreeMode.editorWidthMode</key>
	<integer>4</integer>
	<key>DistractionFreeMode.isEnabled</key>
	<false/>
	<key>DistractionFreeMode.mainSplitterSizes</key>
	<data>
	AAAA/wAAAAEAAAAFAAAAUAAAAVYAAAADAAADNQAAAFABAAAAAAEAAAABAA==
	</data>
	<key>DistractionFreeMode.menuBarGeometry</key>
	<data>
	AdnQywACAAAAAAAAAAAAAAAABTb/////AAAAAAAAAAD//////////wAAAAAAAAAACgA=
	</data>
	<key>DistractionFreeMode.menuBarHeight</key>
	<integer>0</integer>
	<key>DistractionFreeMode.windowState</key>
	<data>
	AAAA/wAAAAD9AAAAAAAABTcAAAPPAAAABAAAAAQAAAAIAAAACPwAAAABAAAAAgAAAAYA
	AAAWAG0AYQBpAG4AVABvAG8AbABCAGEAcgEAAAAA/////wAAAAAAAAAAAAAAIgBmAG8A
	cgBtAGEAdAB0AGkAbgBnAFQAbwBvAGwAYgBhAHIBAAAB0/////8AAAAAAAAAAAAAACAA
	aQBuAHMAZQByAHQAaQBuAGcAVABvAG8AbABiAGEAcgEAAAJO/////wAAAAAAAAAAAAAA
	IgBlAG4AYwByAHkAcAB0AGkAbwBuAFQAbwBvAGwAYgBhAHIBAAACyf////8AAAAAAAAA
	AAAAABoAdwBpAG4AZABvAHcAVABvAG8AbABiAGEAcgEAAANE/////wAAAAAAAAAAAAAA
	FgBxAHUAaQB0AFQAbwBvAGwAYgBhAHIAAAAEYf////8AAAAAAAAAAA==
	</data>
	<key>LastUpdateCheck</key>
	<date>2016-06-20T06:37:07Z</date>
	<key>LogDialog.criticalLog</key>
	<true/>
	<key>LogDialog.debugLog</key>
	<false/>
	<key>LogDialog.fatalLog</key>
	<true/>
	<key>LogDialog.geometry</key>
	<data>
	AdnQywACAAAAAANcAAABZwAABpAAAAPrAAADXAAAAX0AAAaQAAAD6wAAAAAAAAAACgA=
	</data>
	<key>LogDialog.infoLog</key>
	<true/>
	<key>LogDialog.scriptingLog</key>
	<true/>
	<key>LogDialog.showAtStartup</key>
	<false/>
	<key>LogDialog.statusLog</key>
	<true/>
	<key>LogDialog.warningLog</key>
	<true/>
	<key>MainWindow.geometry</key>
	<data>
	AdnQywACAAAAAAB9AAAAjgAABDEAAAQkAAAAfQAAAKQAAAQxAAAEJAAAAAAAAAAACgA=
	</data>
	<key>MainWindow.mainToolBar·iconSize</key>
	<string>24</string>
	<key>MainWindow.menuBarGeometry</key>
	<data>
	AdnQywACAAAAAAAAAAAAAAAAA7T/////AAAAAAAAAAD//////////wAAAAAAAAAACgA=
	</data>
	<key>MainWindow.noteTextEdit·code·font</key>
	<string>Lucida Grande,11,-1,5,50,0,0,0,0,0</string>
	<key>MainWindow.noteTextEdit·font</key>
	<string>Lucida Grande,11,-1,5,50,0,0,0,0,0</string>
	<key>MainWindow.noteTextView·code·font</key>
	<string>Courier,11,-1,5,50,0,0,0,0,0</string>
	<key>MainWindow.noteTextView·font</key>
	<string>.SF NS Text,11,-1,5,50,0,0,0,0,0</string>
	<key>MainWindow.showRecentNoteFolderInMainArea</key>
	<false/>
	<key>MainWindow.windowState</key>
	<data>
	AAAA/wAAAAD9AAAAAAAAA7UAAANqAAAABAAAAAQAAAAIAAAACPwAAAACAAAAAgAAAAUA
	AAAiAGYAbwByAG0AYQB0AHQAaQBuAGcAVABvAG8AbABiAGEAcgAAAAHT/////wAAAAAA
	AAAAAAAAIABpAG4AcwBlAHIAdABpAG4AZwBUAG8AbwBsAGIAYQByAAAAAk7/////AAAA
	AAAAAAAAAAAiAGUAbgBjAHIAeQBwAHQAaQBvAG4AVABvAG8AbABiAGEAcgAAAALJ////
	/wAAAAAAAAAAAAAAGgB3AGkAbgBkAG8AdwBUAG8AbwBsAGIAYQByAAAAA0T/////AAAA
	AAAAAAAAAAAWAHEAdQBpAHQAVABvAG8AbABiAGEAcgAAAARh/////wAAAAAAAAAAAAAA
	AgAAAAEAAAAWAG0AYQBpAG4AVABvAG8AbABCAGEAcgAAAAAA/////wAAAAAAAAAA
	</data>
	<key>NSFontPanelAttributes</key>
	<string>1, 0</string>
	<key>NSFontPanelPreviewHeight</key>
	<real>100</real>
	<key>NSNavLastRootDirectory</key>
	<string>~</string>
	<key>NSNavPanelExpandedSizeForOpenMode</key>
	<string>{712, 459}</string>
	<key>NSWindow Frame NSFontPanel</key>
	<string>1514 315 736 467 0 0 2560 1417 </string>
	<key>PiwikClientId</key>
	<string>5f55ef95fd2831ba</string>
	<key>ShowSystemTray</key>
	<false/>
	<key>SortingModeAlphabetically</key>
	<true/>
	<key>allowDifferentNoteFileName</key>
	<false/>
	<key>allowOnlyOneAppInstance</key>
	<true/>
	<key>appMetrics.disableAppHeartbeat</key>
	<false/>
	<key>appMetrics.disableTracking</key>
	<false/>
	<key>appMetrics.notificationShown</key>
	<true/>
	<key>cryptoKey</key>
	<integer>101027544</integer>
	<key>currentNoteFolderId</key>
	<integer>1</integer>
	<key>customNoteFileExtensionList</key>
	<array/>
	<key>darkMode</key>
	<false/>
	<key>darkModeColors</key>
	<false/>
	<key>defaultNoteFileExtension</key>
	<string>txt</string>
	<key>demoNotesCreated</key>
	<true/>
	<key>disableAutomaticUpdateDialog</key>
	<false/>
	<key>externalEditorPath</key>
	<string></string>
	<key>ignoreAllExternalModifications</key>
	<true/>
	<key>interfaceLanguage</key>
	<string>en</string>
	<key>mainSplitterSizes</key>
	<data>
	AAAA/wAAAAEAAAAFAAAAUAAAAR8AAAADAAADGwAAAFABAAAAAAEAAAABAA==
	</data>
	<key>mainSplitterState-0-0-0-0</key>
	<data>
	AAAA/wAAAAEAAAAFAAAAUAAAAPMAAAADAAADBQAAAnQBAAAAAAEAAAABAA==
	</data>
	<key>mainSplitterState-0-0-1-0</key>
	<data>
	AAAA/wAAAAEAAAAFAAAAUAAAAR8AAAADAAADGwAAAFABAAAAAAEAAAABAA==
	</data>
	<key>mainSplitterState-0-1-0-0</key>
	<data>
	AAAA/wAAAAEAAAAFAAAATQAAAPMAAAADAAADBQAAAnQBAAAAAAEAAAABAA==
	</data>
	<key>mainSplitterState-0-1-1-0</key>
	<data>
	AAAA/wAAAAEAAAAFAAAAUAAAAQUAAAADAAAB6AAAAi4BAAAAAAEAAAABAA==
	</data>
	<key>mainSplitterState-1-0-1-0</key>
	<data>
	AAAA/wAAAAEAAAAFAAAGwgAAEHIAAAADAAAudAAAAFABAAAAAAEAAAABAA==
	</data>
	<key>mainSplitterState-1-1-1-0</key>
	<data>
	AAAA/wAAAAEAAAAFAAAA3AAAAU0AAALyAAAAxwAAAFABAAAAAAEAAAABAA==
	</data>
	<key>mainSplitterState-1-1-1-1</key>
	<data>
	AAAA/wAAAAEAAAADAAAA3AAAAU0AAALyAQAAAAABAAAAAQA=
	</data>
	<key>markdownHighlightingInterval</key>
	<integer>0</integer>
	<key>markdownViewEnabled</key>
	<false/>
	<key>networking.ignoreSSLErrors</key>
	<true/>
	<key>networking.proxyType</key>
	<integer>0</integer>
	<key>noteEditPaneEnabled</key>
	<true/>
	<key>noteListSplitterState</key>
	<data>
	AAAA/wAAAAEAAAACAAADQgAAAAAB/////wEAAAACAA==
	</data>
	<key>noteSaveIntervalTime</key>
	<integer>10</integer>
	<key>notesPath</key>
	<string>/Users/steffen/ownCloud_HOME/Notes</string>
	<key>notifyAllExternalModifications</key>
	<false/>
	<key>ownCloud.password</key>
	<string>AwKcEhc=</string>
	<key>ownCloud.serverUrl</key>
	<string></string>
	<key>ownCloud.todoCalendarBackend</key>
	<integer>0</integer>
	<key>ownCloud.todoCalendarEnabledList</key>
	<array/>
	<key>ownCloud.todoCalendarEnabledUrlList</key>
	<array/>
	<key>ownCloud.todoCalendarUrlList</key>
	<array/>
	<key>ownCloud.userName</key>
	<string></string>
	<key>savedSearches.noteFolder-1</key>
	<array>
		<string>defaults</string>
	</array>
	<key>tagsEnabled</key>
	<false/>
	<key>verticalNoteFrameSplitterState</key>
	<data>
	AAAA/wAAAAEAAAAAAQAAAAABAAAAAgA=
	</data>
	<key>verticalPreviewModeEnabled</key>
	<false/>
</dict>
</plist>

**Comment by Fischmuetze** [comment]
> how long does the load stay so high?

infinity

> does this happen every time you start QOwnNotes?

On all of my 4 Macs - every time 

> can you please try to move your ~/Library/Preferences/com.pbe.QOwnNotes.plist away 
> (while QOwnNotes is closed) so a new settings file will be created.

I did it and the high load was gone BUT there is now another problem which occurs if  the app is starting.
And no: there are no special folder nor file permissions  - the Notes folder is inside of my home folder and the user have full rights
drwxr-xr-x  56 steffen  staff   1,9K 20 Jun 09:05 Notes

![bildschirmfoto 2016-06-20 um 09 11 37](https://cloud.githubusercontent.com/assets/19834496/16185947/c7c21174-36c7-11e6-839c-9766a7e41b9c.png)

There will no longer build a sqlite file

**Comment by pbek** [comment]
Can you please try to remove the note.sqlite (tags will be gone, but you don't use tags, right?) after you removed your plist file again (while QOwnNotes doesn't run).

**Comment by pbek** [comment]
> Doesn't true as you described. This information isn't a part of ~/Library/Preferences/com.pbe.QOwnNotes.plist

All the keys to fetch the settings come from `QSettings::allKeys()` <http://doc.qt.io/qt-5/qsettings.html#allKeys>.
Under OS X a lot more keys (that weren't stored by QOwnNotes) are returned by this method than under all other operating systems.

in version 16.06.8:
- under OS X now a lot of settings keys, that get added by Qt under OS X 
  will be ignored in the debug output of the settings dialog

**Comment by Fischmuetze** [comment]
strange behavior: 

History 
----
* stored the notes as well (of course the sqlite file) in
  /Users/steffen/ownCloud_Home/Note
* quit the app
* delete the preferences file
* delete the sqlite file
* restart the app
* configure that initial setup dialog
* got the error msg missing sqlite file
* no sqlite file was in the Notes folder
* quit the app again
* press the button "Clear app data and exit"
* restart the app 
* configure that initial setup dialog again
* got NO error msg missing sqlite file (No idea what this button does)
* high load was gone

BUT than

* I make the same UI settings as I has before
* high load is now back again

**Comment by pbek** [comment]
Thank you for testing. Can you reproduce what UI settings caused the high sysload?

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features (especially debug output hiding) work for you?

**Comment by Fischmuetze** [comment]
I followed my intuition, instead to try out each single setting that I changed ...
It's the refresh setting for the markdown highlighting - as you know I set it to zero ...maybe there is a loop which runs a little bit to hard?

**Comment by pbek** [comment]
That's weird, I will try to reproduce that. Thank you for testing!

**Comment by Fischmuetze** [comment]
I can reproduce this on all of my Macs

**Comment by Fischmuetze** [comment]
debug output of 16.06.8 seems to be now ok and respect the privacy

**Comment by pbek** [comment]
v16.06.11: the 100% cpu problem when disabling the markdown highlighter in the settings is now fixed

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
