### ISSUE TITLE
Copy-pasted images are scaled up, not just down

### ISSUE THREAD

**Issue by alk0** [pbek/QOwnNotes#2170]
Settings, General, [x] Scale images **down** when inserted into notes
Maximum width: 1024
Maximum height: 1024

#### Expected behaviour

Small images (not exceeding a set value) don't scale up.

#### Actual behaviour

An image is always scaled, both up and down.

#### Steps to reproduce

1. Copy image to the clipboard (GIMP, Edit, Copy visible / Firefox, right-click on an image, Copy Image / … / whatever)
2. Paste it to the note (Ctrl+V / right-click, Paste)
3. See an enlarged image, if the image was originally small
4. Check the properties of the image in the /media/ folder of the notebook, it's 1024px on one side

(Maybe I'm missing some other setting somewhere?)

Tested on QOwnNotes - version 21.6.7 - AUR - build 846

**Comment by alk0** [comment]
Follow-up:

Same happens when images are inserted via Edit, Insert, Insert Image (Ctrl+Shift+I).

More than that — if we use the "Scaling width" slider to reduce the size, let's say, to 32px, the image gets indeed scaled down, then it gets scaled up nevertheless, producing a blurry original → 32px → 1024px image.

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue.

**Comment by pbek** [comment]
## 21.6.8
- when automatic downscaling of images is enabled in the *General settings* the images
  are now not scaled up any more when they are smaller than the chosen resolution

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by alk0** [comment]
Great, seems to work as expected. (And "manual" scaling in the file dialog still works, if needed, which is also great.)

I'll have one more proposal - to (optionally) use WebP instead of PNG for downscales, I'll post it later separately, it's not something to implement without additional discussions.

And this ticket can be closed now, I guess.

**Comment by pbek** [comment]
Great, thank you for testing!

> I'll have one more proposal - to (optionally) use WebP instead of PNG for downscales, I'll post it later separately, it's not something to implement without additional discussions.

Phew, good question...
