### ISSUE TITLE
Can't add an SVG image with the "Scale images down…" option enabled

### ISSUE THREAD

**Issue by alk0** [pbek/QOwnNotes#2171]
Somewhat linked to https://github.com/pbek/QOwnNotes/issues/2170

#### Expected behaviour

Adding an SVG image produces some meaningful result with the "Scale images down when inserted to notes" enabled.

#### Actual behaviour

The dialog lets the user to choose an image, but produces a zero-sized file object in the /media/ folder (trying to scale it down and failing?)

#### Steps to reproduce

1. Settings, General, [x] Scale images down when inserted into notes, Maximum width: 1024, Maximum height: 1024
2. Ctrl+Shift+I, choose an SVG file, **do not** touch the "Scaling width" slider (assuming no conversion), click OK.
3. No image in preview
4. A zero-sized SVG in the /media/ folder

Inserting an SVG image without checking "Scale images down when inserted to notes" in the Settings seems to work OK, it just copies the file unchanged and displays it normally as expected. And using the "Scaling width" slider in the dialog seems to always produce a PNG copy of the image, as expected, I guess. (But this scenario is still affected by https://github.com/pbek/QOwnNotes/issues/2170 - the image gets rescaled twice)

Hope you can reproduce it based on my chaotic description, or I can post screenshots or record a video if needed.

**Comment by pbek** [comment]
I was able to select a [svg](https://en.wikipedia.org/wiki/Scalable_Vector_Graphics#/media/File:Bitmap_VS_SVG.svg) and saw a preview. It also got inserted as SVG. 
![image](https://user-images.githubusercontent.com/1798101/123588795-9c52f900-d7e8-11eb-8ef8-18b495573729.png)

Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.

Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting Debug in Options).

**Comment by pbek** [comment]
@Waqar144, can you reproduce this by chance?

**Comment by alk0** [comment]
Settings: (note: **without** "Scale images down…" inserting an SVG works perfectly!)

![image](https://user-images.githubusercontent.com/10332037/123638589-c6340c00-d838-11eb-9853-1622c62729e0.png)

File dialog (the image is in fact properly displayed in the preview, I just reduced the window size to make screenshots smaller, so you can't see it here):

![image](https://user-images.githubusercontent.com/10332037/123638631-d2b86480-d838-11eb-8fa8-4cd3bf1ff9f6.png)

Editor:

![image](https://user-images.githubusercontent.com/10332037/123638686-e237ad80-d838-11eb-985c-fec46eb7b127.png)

But! media/drawing.svg is **0 bytes**.

The original SVG attached below, zipped. Just created in Inkscape 1.1 before the testing, it's a box 512×512 pixels, nothing more.

[drawing.zip](https://github.com/pbek/QOwnNotes/files/6726328/drawing.zip)

There's nothing relevant in the debug log, as far as I can judge:

[Jun 28 17:43:56] [debug]: insertMedia  - 'text':  "![drawing](media/drawing.svg)\n"
[Jun 28 17:44:04] [debug]: storing note file:  "Test SVG.md"
[Jun 28 17:44:04] [debug]: stored note:  Note: <id>1 <name>"Test SVG" <fileName>"Test SVG.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false
[Jun 28 17:44:04] [debug]: storeUpdatedNotesToDisk  - 'count':  1
[Jun 28 17:44:04] [status]: Stored 1 note(s) to disk

**Comment by pbek** [comment]
For me the image was inserted...

![Screenshot_20210628_153247](https://user-images.githubusercontent.com/1798101/123644920-240b2880-d826-11eb-9524-829e9440d77d.png)

What svg did you use? Was it a remote file where you maybe have no permissions to read it (without the active browser session)?

**Comment by pbek** [comment]
I was also able to insert your `drawing.svg`.

**Comment by pbek** [comment]
Ah, now I see where that might came from. If an image is larger than your 1024px then it should get resized, but you can't write SVGs in Qt, which might result in a 0 Byte file.

In your opinion what should happen for SVGs in that instance?

1) Don't touch them?
2) Resize them and store as PNG?

I incline to option 1).

**Comment by alk0** [comment]
I'd vote for "Don't touch", I think. A safer and more reasonable option until proven otherwise.

**Comment by pbek** [comment]
## 21.6.8
- when automatic downscaling of images is enabled in the *General settings* and a too large
  SVG image is inserted into a note then it now will not get resized automatically, because
  Qt can't resize SVG images and this this would result into a 0 byte file

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by alk0** [comment]
Seems to work as discussed (or implicitly meant :)) above, the ticket can be closed, I guess.

**Comment by pbek** [comment]
Great, thank you for testing!
