### ISSUE TITLE
WebP images are not included in the "Image files" filter by default (cosmetic, low importance)

### ISSUE THREAD

**Issue by alk0** [pbek/QOwnNotes#2172]
#### Expected behaviour

When inserting an image, .webp images are shown in the file dialog by default.

#### Actual behaviour

QON seems to fully support them, but they are not shown as "Image files", one has to switch to "Any files" in the add dialog.

#### Steps to reproduce

Ctrl+Shift+I, "Select image to insert" (file dialog)

**Comment by pbek** [comment]
Thank you for your suggestion. I'm not sure if / how good the support is in older Qt versions but I'll add the extension nevertheless.

**Comment by pbek** [comment]
## 21.6.8
- the *Insert image* dialog now allows the selection of webp images by default

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by alk0** [comment]
Everything's working, thanks. I'll leave closing tickets to you.

**Comment by pbek** [comment]
Great, thank you for testing!
