### ISSUE TITLE
Changeable Default Title of Notes

### ISSUE THREAD

**Issue by genvoa** [pbek/QOwnNotes#218]
Can I somehow modify the default title of new notes?

> Note 2016-06-18T22.49.40
> ========================

**Comment by pbek** [comment]
I planed to add that as scripting function.

**Comment by pbek** [comment]
## 16.06.12
- there now is a new scripting hook `handleNewNoteHeadlineHook()`, that is 
  called before a new note is created
    - it allows you to **modify the headline of a note before it is created**
    - note that you have to take care about a unique note name, otherwise
      the new note will not be created, it will just be found in the note list
    - there is an example at
      [custom-new-note-headline.qml](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/custom-new-note-headline.qml)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by strayobject** [comment]
This script lives in the docs now, under https://github.com/pbek/QOwnNotes/blob/main/docs/scripting/examples/custom-new-note-headline.qml
