### ISSUE TITLE
Return focus to editor after switching workspaces

### ISSUE THREAD

**Issue by proazr** [pbek/QOwnNotes#2180]
Hi @pbek!  

My QN setup includes 2 workspaces - the first one includes the "Note Edit" panel and the second one includes the "Note Preview" panel. I use the default shortcut "Alt + Shift + P" to toggle between the edit and preview workspaces. This works great, but for a minor inconvenience in that the focus is not returned to the position where the cursor was at in the edit panel after switching workspaces.

- Say I am in the edit workspace and I am typing in my notes
- I use Alt + Shift + P to switch to the preview workspace
- I preview the note 
- I press Alt + Shift + P to return to the edit workspace
- The focus is no longer in the edit panel and I have to click on the line/column where I had been prior to switching workspaces

Is there a way to return the focus to the line/column upon switching workspaces?

Thank you!

**Comment by pbek** [comment]
Thank you for bringing this to my attention. This was already implemented but was broken by https://github.com/pbek/QOwnNotes/pull/2056. 😬

**Comment by pbek** [comment]
## 21.7.3
- the restoring of the focus after switching workspaces was fixed

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by proazr** [comment]
Just tried the new release and it works great! 

Thank you for fixing this so quick!

**Comment by pbek** [comment]
Great, thank you for testing!
