### ISSUE TITLE
[I] Right click "Show note git versions" does not do anything

### ISSUE THREAD

**Issue by marcusyoung** [pbek/QOwnNotes#2182]
#### Expected behaviour

Not sure as haven't seen this function working. Presumably, git versions are shown? I can confirm that git integration is working and edited versions of the note have been automatically committed.

#### Actual behaviour

Nothing happens.

#### Steps to reproduce

Right click on note and choose "show note git versions".

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed Jul 7 11:40:50 2021`
**Version**: `21.7.3`
**Build date**: `Jul  5 2021`
**Build number**: `852`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\marcu\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Users\marcu\Downloads\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `en_GB`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1200`
**Screen resolution(s)**: `1920x1200, 1080x1920`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `2`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\marcu\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `C:\Users\marcu\MyBox\qownnotes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\marcu\MyBox\qownnotes\notes.sqlite`

### Cloud connection ``

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**AttachmentDialog/geometry** (QByteArray): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (int): `21`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `C:/Users/marcu/Desktop`
**FileDialog/LastPath-InsertAttachment** (QString): `C:/Users/marcu/Desktop`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-07-07T11:27:28.622`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Fira Code,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Tahoma,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**NoteFolder-1/NoteTabNameList** (QStringList): `Welcome to QOwnNotes`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteHistory-1** (QVariantList): `<variant list with 2 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `1`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**StoredAttachmentsDialog/geometry** (QByteArray): `<binary data>`
**StoredImagesDialog/geometry** (QByteArray): `<binary data>`
**TableDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): `%notePath%`
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (int): `15`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `C:/Users/marcu/MyBox/qownnotes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `2`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `0`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**AGSDESKTOPJAVA**: `C:\Program Files (x86)\ArcGIS\Desktop10.8\`
**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\marcu\AppData\Roaming`
**ChocolateyInstall**: `C:\ProgramData\chocolatey`
**ChocolateyLastPathUpdate**: `132462148641064873`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `HP-Z2-MINI`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**EDITOR**: `C:\Program Files\Notepad++\notepad++.exe`
**FLEXLM_TIMEOUT**: `300000`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**GDAL_DATA**: `C:\PostgreSQL\11\gdal-data`
**GEODA_GDAL_DATA**: `C:\Program Files\GeoDa Software\data`
**GEODA_OGR_DRIVER_PATH**: `C:\Program Files\GeoDa Software`
**GIT_LFS_PATH**: `C:\Program Files\Git LFS`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\marcu`
**JAVA_HOME**: `C:\Program Files\Java\jdk1.8.0_221`
**LOCALAPPDATA**: `C:\Users\marcu\AppData\Local`
**LOGONSERVER**: `\\HP-Z2-MINI`
**M2_HOME**: `C:\maven`
**MAVEN_HOME**: `C:\Users\marcu`
**MAVEN_OPTS**: `-Dfile.encoding=UTF-8`
**NTERACT_EXE**: `C:\Program Files\nteract\nteract.exe`
**NUMBER_OF_PROCESSORS**: `8`
**OneDrive**: `C:\Users\marcu\OneDrive - nowtechit`
**OneDriveCommercial**: `C:\Users\marcu\OneDrive - nowtechit`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\fournova\Tower\vendor\Git\usr\bin;C:\Program Files\Notepad++\;C:\Program Files (x86)\cb2bib\;C:\Python38\Scripts\;C:\Python38\;C:\Program Files\Racket;C:\Program Files\ImageMagick-7.0.10-Q16;C:\Program Files\SumatraPDF;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\HP\HP Performance Advisor;C:\WINDOWS\System32\OpenSSH\;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\maven\bin;C:\Program Files\Crucial\Crucial Storage Executive;C:\MiKTeX\miktex\bin\x64\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Git LFS;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet\;C:\nodejs\;C:\Program Files\Pandoc\;C:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\NetSarang\Xshell 7\;C:\Program Files (x86)\NetSarang\Xftp 7\;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Git\cmd;C:\Program Files (x86)\Technology Lighthouse\PromptPal;C:\texlive\2020\bin\win32;C:\MiKTeX\miktex\bin\x64\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\NetSarang\Xftp 6\;C:\Program Files (x86)\NetSarang\Xshell 6\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\HP\HP Performance Advisor;C:\WINDOWS\System32\OpenSSH\;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\maven\bin;C:\Program Files\Crucial\Crucial Storage Executive;C:\nodejs\;C:\Program Files\Pandoc\;C:\Users\marcu\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Scapple;C:\Program Files\nteract\resources\bin\win;C:\Users\marcu\AppData\Roaming\npm;C:\Users\marcu\AppData\Local\Markdown Monster`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW`
**POSTGIS_ENABLE_OUTDB_RASTERS**: `1`
**POSTGIS_GDAL_ENABLED_DRIVERS**: `GTiff PNG JPEG GIF XYZ DTED USGSDEM AAIGrid`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 94 Stepping 3, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `5e03`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Intel\Wired Networking\`
**PUBLIC**: `C:\Users\Public`
**RTOOLS40_HOME**: `C:\rtools40`
**R_LIBS_USER**: `C:\R-library;`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\marcu\AppData\Local\Temp`
**TMP**: `C:\Users\marcu\AppData\Local\Temp`
**USERDOMAIN**: `HP-Z2-MINI`
**USERDOMAIN_ROAMINGPROFILE**: `HP-Z2-MINI`
**USERNAME**: `marcu`
**USERPROFILE**: `C:\Users\marcu`
**windir**: `C:\WINDOWS`
</details>

Please paste the text from the issue assistant here. It should be already in your clipboard.

**Comment by pbek** [comment]
Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting Debug in Options).

You have opt-in to use git for your note folder, but you haven't set a git client in the settings (and I guess you haven't any that can be found automatically).

**Comment by marcusyoung** [comment]
No log output, I'll try enabling debug logging. Git is configured and git is found. That part is working. As I said, changes are being committed.

**Comment by pbek** [comment]
> gitLogCommand

You haven't defined a command to be called to show the logs.

**Comment by marcusyoung** [comment]
Where should that be defined?

**Comment by marcusyoung** [comment]
Oh, I see now in the git versioning settings. Thanks.

**Comment by marcusyoung** [comment]
Still unable to get it working but now get an error.

I have added: `gitk %notePath%`

But get this error for the Welcome note when I right click and view git versions:

![2021-07-07_17-05-32](https://user-images.githubusercontent.com/10391966/124793308-c40f3300-df45-11eb-8250-6b284a0bb44b.png)

Similar with a one word filename:

![2021-07-07_17-11-53](https://user-images.githubusercontent.com/10391966/124794006-76df9100-df46-11eb-87b7-a7c5080f1525.png)

It works fine entering: `gitk "Welcome to QOwnNotes.md"` at the command line.

I've also tried TortoiseGit:

`TortoiseGitProc.exe /command:log /path:%notePath%`

But the note path isn't interpreted correctly and the log for the specific file isn't shown. This is the command received by TortoiseGit:

![2021-07-07_17-16-26](https://user-images.githubusercontent.com/10391966/124794626-1f8df080-df47-11eb-85c6-f5abb77c469d.png)

When I run: `TortoiseGitProc.exe /command:log /path:"Bookmark.md"` from the command line it works and the log for the file is shown. This is the command that is received by TortoiseGit:

![2021-07-07_17-18-26](https://user-images.githubusercontent.com/10391966/124795039-8e6b4980-df47-11eb-9bd6-2be3d9030c5c.png)

**Comment by pbek** [comment]
I guess you will need to add quote signs, like `gitk "%notePath%"` or just leave the note pass out at all, so just `gitk`. I myself just use `gitk` as command.

**Comment by marcusyoung** [comment]
Neither work I'm afraid. Using gitk alone gives the same errors as shown in my previous message.

**Comment by pbek** [comment]
I can't reproduce that under Linux, everything works fine. I'll need more time to test that under Windows.

**Comment by pbek** [comment]
## 21.7.4
- the execution of git log commands has been fixed for Windows

**Comment by marcusyoung** [comment]
`gitk` (and `git gui blame`) now seem to be working as expected.

Something odd if I use: `TortoiseGitProc.exe /command:log /path:%notePath%`

The forward slashes are swapped to backward slashes so it fails:

![2021-07-08_19-12-30](https://user-images.githubusercontent.com/10391966/124970954-8b905780-e020-11eb-9ad4-9e6e2edc7f0b.png)

**Comment by pbek** [comment]
Thank you for testing.
I guess that's done by [QProcess::startDetached](https://doc.qt.io/qt-5/qprocess.html#startDetached-1) and there isn't much that can be done (without running into huge amounts of complexity and more side-effect) since running the command with `cmd.exe /c` didn't seem to work any more under Windows.

You can of course use https://www.qownnotes.org/scripting/methods-and-objects.html#registering-a-custom-action to register a custom action in the note list context menu to try to run more complex operations.

**Comment by pbek** [comment]
> You can of course use https://www.qownnotes.org/scripting/methods-and-objects.html#registering-a-custom-action to register a custom action in the note list context menu to try to run more complex operations.

Or create a Windows batch file that runs TortoiseGitProc.exe with the parameters needed.
