### ISSUE TITLE
[I] Part of HTML tag visible in preview pane when using Full layout

### ISSUE THREAD

**Issue by marcusyoung** [pbek/QOwnNotes#2183]
#### Expected behaviour

No tag to be visible

#### Actual behaviour

Part of an HTML tag visible in the preview pane:

`class="preview">`

![2021-07-10_12-30-54](https://user-images.githubusercontent.com/10391966/125161608-33219d00-e17b-11eb-8b6a-13d11aa4ee2d.png)

#### Steps to reproduce

Change to full layout.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[12:32:56] [debug] updatePanelMenu - 'updatePanelMenu'
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sat Jul 10 12:33:04 2021`
**Version**: `21.7.4`
**Build date**: `Jul  8 2021`
**Build number**: `853`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\marcu\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Users\marcu\Downloads\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `en_GB`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1200`
**Screen resolution(s)**: `1920x1200, 1080x1920`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `7`
**Calendar items**: `0`
**Enabled scripts**: `3`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\marcu\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `MyNotes`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `C:\Users\marcu\MyBox\qownnotes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\marcu\MyBox\qownnotes\notes.sqlite`

### Cloud connection ``

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

### Script `Meeting note`

**id**: `2`
**path**: `C:\Users\marcu\AppData\Roaming\PBE\QOwnNotes\scripts\meeting-note\meeting-note.qml`
**variablesJson**: 
```
{
    "defaultFolder": "meetings",
    "defaultTags": "meeting",
    "headlinePrefix": "Meeting",
    "isAskForDateString": true,
    "noteBodyTemplate": "\n"
}
```
**identifier**: `meeting-note`
**version**: `1.4.0`
**minAppVersion**: `20.4.16`

### Script `@tag tagging in note text (experimental)`

**id**: `4`
**path**: `C:\Users\marcu\AppData\Roaming\PBE\QOwnNotes\scripts\in-note-text-tagging\in-note-text-tagging.qml`
**variablesJson**: 
```
{
    "putToBeginning": true,
    "tagHighlightColor": "purple",
    "tagMarker": "#"
}
```
**identifier**: `in-note-text-tagging`
**version**: `0.0.9`
**minAppVersion**: `20.6.0`

### Script `Text Highlights`

**id**: `5`
**path**: `C:\Users\marcu\AppData\Roaming\PBE\QOwnNotes\scripts\text-highlights\text-highlights.qml`
**variablesJson**: 
```
{
    "backgroundColor": "#FFFF00"
}
```
**identifier**: `text-highlights`
**version**: `0.0.4`
**minAppVersion**: `20.6.0`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**AttachmentDialog/geometry** (QByteArray): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/editorWidthMode** (int): `2`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (int): `21`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `C:/Users/marcu/MyBox/qownnotes`
**FileDialog/LastPath-GitExecutable** (QString): `C:/Git/cmd`
**FileDialog/LastPath-ImportTextFiles** (QString): `C:/Users/marcu/MyBox/qownnotes`
**FileDialog/LastPath-InsertAttachment** (QString): `C:/Users/marcu/Desktop`
**FileDialog/LastPath-NotePDFExport** (QString): `C:/Users/marcu/Desktop`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-07-10T12:28:14.722`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `TRG/Meetings, TRG`
**MainWindow/noteTextEdit.code.font** (QString): `Fira Code,11,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Tahoma,11,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MainWindow/tagTreeWidgetExpandState-1** (QStringList): `15`
**NoteFolder-1/NoteTabNameList** (QStringList): `This is a test note with epsilon.`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 52 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `51`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExportOrientation** (int): `0`
**Printer/NotePDFExportPageSize** (int): `4`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**StoredAttachmentsDialog/geometry** (QByteArray): `<binary data>`
**StoredImagesDialog/geometry** (QByteArray): `<binary data>`
**TableDialog/geometry** (QByteArray): `<binary data>`
**TagAddDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `ef2qNzhvN7VY`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): `gitk`
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): `dd.MM.yyyy hh:mm`
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `true`
**itemHeight** (int): `15`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `true`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `true`
**noteSubfoldersPanelShowRootFolderName** (QString): `false`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `0`
**notesPath** (QString): `C:/Users/marcu/MyBox/qownnotes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `2`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `0`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**previousWorkspace** (QString): `initial`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `test2, Unicard smartcard data, Note 4fda03d2-9539-41a6-8f80-d18abfe8af63, Marcus_Test, test, test1, test3, This is a test headline, Bookmarks, Note 2021-07-08T18.39.36, Note 2021-07-08T18.32.12, commit-192aa16 2021-07-08T18.25.31, Note 7d9d6d16-e8fc-4368-a257-d76cd9d80583, Note fdd43db6-027e-4aae-b3ae-da2a80337d03, Note 2021-07-07T18.06.05, Setup PostgreSQL, Postgis, pgrouting, and R, R on Debian Buster, Create spatial database, Notes, cintanotes (exported 2021-07-07_1725) 2021-07-07T17.27.46, cintanotes (exported 2021-07-07_1725), Note 5b83a412-7ba6-43e7-aadd-12912c777fc6, adrian, Note bddb99c4-39b2-481b-ac29-c1d3b4515425, Note 2021-07-07T13.28.40, Note 2021-07-07T13.22.43, Note 8242bf1f-1558-4ee1-97cb-75845299729b, Note 2021-07-07T12.28.55, Marcus Young's website Marcus Young, Marcus Young's website Marcus Young 2021-07-07T12.19.32, EBONY - West Hatch Animal Centre - Detail - rspca.org.uk - RSPCA 2021-07-07T12.16.44, EBONY - West Hatch Animal Centre - Detail - rspca.org.uk - RSPCA`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/7/items** (QStringList): *empty*
**toolbar/7/name** (QString): `custom_toolbar_1`
**toolbar/7/title** (QString): `custom_toolbar_1`
**toolbar/size** (int): `7`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**webSocketServerService/token** (QString): `<hidden>`
**workspace-cd46d360-2c4f-4ad5-972f-96e6ba924794/name** (QString): `MAY`
**workspace-cd46d360-2c4f-4ad5-972f-96e6ba924794/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-cd46d360-2c4f-4ad5-972f-96e6ba924794/windowState** (QByteArray): `<binary data>`
**workspace-ef2qNzhvN7VY/name** (QString): `Full`
**workspace-ef2qNzhvN7VY/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-ef2qNzhvN7VY/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, cd46d360-2c4f-4ad5-972f-96e6ba924794, ef2qNzhvN7VY`

## System environment

**AGSDESKTOPJAVA**: `C:\Program Files (x86)\ArcGIS\Desktop10.8\`
**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\marcu\AppData\Roaming`
**ChocolateyInstall**: `C:\ProgramData\chocolatey`
**ChocolateyLastPathUpdate**: `132462148641064873`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `HP-Z2-MINI`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**EDITOR**: `C:\Program Files\Notepad++\notepad++.exe`
**FLEXLM_TIMEOUT**: `300000`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**GDAL_DATA**: `C:\PostgreSQL\11\gdal-data`
**GEODA_GDAL_DATA**: `C:\Program Files\GeoDa Software\data`
**GEODA_OGR_DRIVER_PATH**: `C:\Program Files\GeoDa Software`
**GIT_LFS_PATH**: `C:\Program Files\Git LFS`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\marcu`
**JAVA_HOME**: `C:\Program Files\Java\jdk1.8.0_221`
**LOCALAPPDATA**: `C:\Users\marcu\AppData\Local`
**LOGONSERVER**: `\\HP-Z2-MINI`
**M2_HOME**: `C:\maven`
**MAVEN_HOME**: `C:\Users\marcu`
**MAVEN_OPTS**: `-Dfile.encoding=UTF-8`
**NTERACT_EXE**: `C:\Program Files\nteract\nteract.exe`
**NUMBER_OF_PROCESSORS**: `8`
**OneDrive**: `C:\Users\marcu\OneDrive - nowtechit`
**OneDriveCommercial**: `C:\Users\marcu\OneDrive - nowtechit`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\fournova\Tower\vendor\Git\usr\bin;C:\Program Files\Notepad++\;C:\Program Files (x86)\cb2bib\;C:\Python38\Scripts\;C:\Python38\;C:\Program Files\Racket;C:\Program Files\ImageMagick-7.0.10-Q16;C:\Program Files\SumatraPDF;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\HP\HP Performance Advisor;C:\WINDOWS\System32\OpenSSH\;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\maven\bin;C:\Program Files\Crucial\Crucial Storage Executive;C:\MiKTeX\miktex\bin\x64\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Git LFS;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet\;C:\nodejs\;C:\Program Files\Pandoc\;C:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\NetSarang\Xshell 7\;C:\Program Files (x86)\NetSarang\Xftp 7\;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Git\cmd;C:\Program Files (x86)\Technology Lighthouse\PromptPal;C:\texlive\2020\bin\win32;C:\MiKTeX\miktex\bin\x64\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\NetSarang\Xftp 6\;C:\Program Files (x86)\NetSarang\Xshell 6\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\HP\HP Performance Advisor;C:\WINDOWS\System32\OpenSSH\;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\maven\bin;C:\Program Files\Crucial\Crucial Storage Executive;C:\nodejs\;C:\Program Files\Pandoc\;C:\Users\marcu\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Scapple;C:\Program Files\nteract\resources\bin\win;C:\Users\marcu\AppData\Roaming\npm;C:\Users\marcu\AppData\Local\Markdown Monster`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW`
**POSTGIS_ENABLE_OUTDB_RASTERS**: `1`
**POSTGIS_GDAL_ENABLED_DRIVERS**: `GTiff PNG JPEG GIF XYZ DTED USGSDEM AAIGrid`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 94 Stepping 3, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `5e03`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Intel\Wired Networking\`
**PUBLIC**: `C:\Users\Public`
**RTOOLS40_HOME**: `C:\rtools40`
**R_LIBS_USER**: `C:\R-library;`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\marcu\AppData\Local\Temp`
**TMP**: `C:\Users\marcu\AppData\Local\Temp`
**USERDOMAIN**: `HP-Z2-MINI`
**USERDOMAIN_ROAMINGPROFILE**: `HP-Z2-MINI`
**USERNAME**: `marcu`
**USERPROFILE**: `C:\Users\marcu`
**windir**: `C:\WINDOWS`
</details>

 the text from the issue assistant here. It should be already in your clipboard.

**Comment by pbek** [comment]
Can you please explain in more detail and step by step what you did, what happened and what you expected.
And you have scripts enabled that might influence the preview, best turn those off for testing.

**Comment by marcusyoung** [comment]
OK, seems to have been a coincidence with the Full layout change. It is being caused by the in-note-text-tagging script. When I disable that script it goes away.

**Comment by marcusyoung** [comment]
Actually, it occurs when the tag word marker is change in the script settings to #. I was trying that to be compatible with epsilon notes that uses # for in text tags.

**Comment by pbek** [comment]
Ok, then better refer to your question to @Maboroshy in the script repository issue tracker. 😉
