### ISSUE TITLE
Find toolbar reappears in editor panel upon adding a tag

### ISSUE THREAD

**Issue by proazr** [pbek/QOwnNotes#2186]
@pbek - I made a trivial observation wherein the search toolbar reappears in the editor window upon adding a tag to the current note if there is any search term entry in the "Search or create note" panel.

#### Steps to reproduce

1. Search for a term in the "Search or create note" panel - here I'm searching for the term "today"
![image](https://user-images.githubusercontent.com/51807907/125399985-4f8e2700-e37f-11eb-87a9-978b54ff2a46.png)

2. Dismiss the search bar in the editor panel
![image](https://user-images.githubusercontent.com/51807907/125400920-7d27a000-e380-11eb-92b8-4c3533ec1b9f.png)

3, Add a tag to the note
![image](https://user-images.githubusercontent.com/51807907/125400376-cd523280-e37f-11eb-9285-facfafdb0814.png)

Upon adding a tag, the search bar reappears in the editor panel. I think that since I had previously dismissed/hidden this, it should stay hidden even after I add a new tag. 

Your thoughts please?

PS:
Here's the version I'm running. I can get you the debug info if required.

![image](https://user-images.githubusercontent.com/51807907/125400624-1f935380-e380-11eb-9f42-d94214048d7a.png)

Thanks!

**Comment by pbek** [comment]
> Dismiss the search bar in the editor panel

How did you "dismiss" the search bar?

**Comment by proazr** [comment]
I dismissed it either using the Esc key while the focus was in the editor panel or by clicking on the close button

![image](https://user-images.githubusercontent.com/51807907/125536974-d2eb29d9-3979-4703-beb3-03670d2a17af.png)

**Comment by pbek** [comment]
The searchbar in the editor panel re-appears as long there is a search term in the *Note search panel*.

**Comment by pbek** [comment]
I guess adding a tag triggered a reload of the note folder for you (you didn't provide any log output) and the search term in the *Note search panel* got activated again.
