### ISSUE TITLE
Feature request: Providing possibility to set background colour for focused controls in the Dark mode

### ISSUE THREAD

**Issue by SN-CH** [pbek/QOwnNotes#2187]
Is it possible to implement ability for users to select the desired background colour for focused objects in the Dark mode without too much efforts on part of the developers?

As of now, it is hardcoded to be orange and I can't help but feel it to be way too bright (of high contrast, if you prefer) and somewhat irritating for my not so young eyes.

![Screen-shot_2021-07-16_14-24-31](https://user-images.githubusercontent.com/42577865/125940595-ca2dac54-5626-4376-8b3b-8a54400d67d4.png)

**Comment by pbek** [comment]
Everything that can be styled in the user interface via styles in Qt can be styled via the scripting engine in QON. There already is a script `Custom user interface styling` in the script repository where you can enter those styles.

**Comment by pbek** [comment]
See https://www.qownnotes.org/scripting/methods-and-objects.html#add-a-custom-stylesheet for a reference.

**Comment by SN-CH** [comment]
Thank you very much for your answer (and even more so for the handy piece of software)!

I suppose this thread can be closed now.

**Comment by pbek** [comment]
The [style.qss](https://github.com/pbek/QOwnNotes/blob/develop/src/libraries/qdarkstyle/style.qss) of [qdarkstyle](https://github.com/pbek/QOwnNotes/blob/develop/src/libraries/qdarkstyle) might also be a good reference for styles you might want to change.

**Comment by SN-CH** [comment]
Well, I have installed the script you mentioned. I started with «:focus» and after some trials and errors I managed to find parameter responsible for setting this background colour:
`* {selection-background-color: green;}`

It works but... for the default mode only. The orange is still there in the dark mode. Somehow the latter overrides the script command.

Since I am not a programmer by any means, I would be grateful for any comments.

**Comment by pbek** [comment]
You can use a color picker to get the color of a selected item (it's `#c64a13`) and search for that code in [style.qss](https://github.com/pbek/QOwnNotes/blob/develop/src/libraries/qdarkstyle/style.qss) (which is used in dark mode). Then override those specific selectors with your new style. `*`, like you did, might have a lower priority if there are already more specific selector in place in `style.qss`.

**Comment by SN-CH** [comment]
Yes, that's exactly what I tried first. I downloaded style.qss from your link, replaced all instances (nine in total) of #c64a13 with #00ff00 and copied all the code into the script. To my surprise it did not have any visible effect in either standard or dark mode. Only then I tried * and found it working partially as I described above.

**Comment by pbek** [comment]
```css
QListView::item:selected:hover, QListView::item:selected:hover, QTreeView::item:selected:hover, QTableView::item:selected:active, QTreeView::item:selected:active, QListView::item:selected:active,  QWidget:item:selected  {
    background: green;
}
```

... worked just fine.

![image](https://user-images.githubusercontent.com/1798101/125996685-2d036b72-6546-4661-bb6c-acda5cfb510d.png)

**Comment by SN-CH** [comment]
For some reason the whole qss with new colour fails, but your excerpt does the job. Not sure why, but I am much happier with how it looks now. Thank you very much for your time!

**Comment by pbek** [comment]
Specificity is the key with CSS styles...

**Comment by pbek** [comment]
For you to play around with styles more easily... 😉 

## 21.7.7
- there now also is a `Reload script engine` button for scripts from the script
  repository in the settings dialog (for [#2187](https://github.com/pbek/QOwnNotes/issues/2187))
    - this makes it for example easier to test changes to the user interface

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by SN-CH** [comment]
Yes, it does work nicely! By the way, it is a welcome edition, because opening/closing the Settings dialogue takes some time (I bet you know about this).

I ought to say the way you treat your software users is exemplar. It is much appreciated. I wish they treat us just as nicely and effectively in commercial software support depts. The way I see it, I owe you a glass of beer, possibly, two. So, I made a small donation... next time you happen to be in a bar, get yourself a glass of your favourite brand ;-). Or, maybe, you prefer coffee...

**Comment by pbek** [comment]
Great, thank you for testing!

> because opening/closing the Settings dialogue takes some time 

The script engine (amongst a lot of other things) will be reloaded when you press `Ok` in the settings dialog, that takes time.

>  I ought to say the way you treat your software users is exemplar. It is much appreciated. I wish they treat us just as nicely and effectively in commercial software support depts.

Thank you! 😁  Commercial software vendors need to live off of their software and contracts. I don't 😅 

> So, I made a small donation... next time you happen to be in a bar, get yourself a glass of your favourite brand ;-). Or, maybe, you prefer coffee...

I just saw it, thank you very much! 🙏🏻  I prefer water. 😆
