### ISSUE TITLE
Sort order of notes

### ISSUE THREAD

**Issue by sciurius** [pbek/QOwnNotes#2188]
QOwnNotes - version 21.7.5 - OBS - build 854 - Fedora 34

I have notes that display in the following order (the ✔ is part of the note name):

✔V1
M1
V2

#### Expected behaviour

M1
✔V1 (symbol is ignored)
V2

or

M1
V2
✔V1 (symbol has a high codepoint)

#### Actual behaviour

See above. Why this order?

**Comment by pbek** [comment]
Since you haven't provided any informations about your settings I can only guess you are trying to sort notes alphabetically (which is not the default behavior). I guess sqlite is sorting the notes that way.
Why are you expecting ✔ to be ignored when sorting?

**Comment by sciurius** [comment]
Sort is set to alphabetical, ascending (default).

I'm not going to say that I'd expect ✔ to be ignored but I was surprised that it shows alphabetically first.
When I insert these three values in an SQLite table:
````
sqlite> create table note ( name text );
sqlite> insert into note values ('M1');
sqlite> insert into note values ('✔V1');
sqlite> insert into note values ('V2');
sqlite> select * from note;
M1
✔V1
V2
sqlite> select * from note order by name;
M1
V2
✔V1
sqlite> 
````

**Comment by pbek** [comment]
Actually it turns out the last say has [QTreeWidget](https://doc.qt.io/qt-5/qtreewidget.html):

https://github.com/pbek/QOwnNotes/blob/ba8eee87b6bfaaf2a2bbc9d0cb895ca01c6b0373/src/mainwindow.cpp#L2281-L2288
