### ISSUE TITLE
[I] Navigation through the panel only works if the header is not selected

### ISSUE THREAD

**Issue by fabianski7** [pbek/QOwnNotes#2192]
#### Steps to reproduce
1. Click on one of the headers
2. Move the scroll to a location where you can no longer see the previously selected header
3. Click on the header again to go back to it.

https://user-images.githubusercontent.com/47755037/126162137-2fc02140-0a0c-44e8-90ca-d63981c6b739.mp4

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

```
**Current Date**: `seg. jul. 19 09:37:31 2021`
**Version**: `21.7.9`
**Build date**: `Jul 18 2021`
**Build number**: `858`
**Platform**: `linux`
**Operating System**: `Arch Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/home/linus/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/linus/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `pt_BR`
**Locale (interface)**: `pt_BR`
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breeze`
**Notes in current note folder**: `212`
**Calendar items**: `143`
**Enabled scripts**: `5`
```

</details>

**Comment by pbek** [comment]
Qt functionality is used to jump to the position. I'll see if that can be improved.

**Comment by pbek** [comment]
It just wasn't supported yet to change the position of the cursor a 2nd time to the same position.

**Comment by pbek** [comment]
## 21.7.12
- you can now jump to the same headline multiple times in the navigation panel

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by fabianski7** [comment]
yes, it's working now. thanks!

**Comment by pbek** [comment]
Great, thank you for testing!
