### ISSUE TITLE
Navigation panel loses focus when used with keyboard

### ISSUE THREAD

**Issue by fabianski7** [pbek/QOwnNotes#2193]
#### Expected behaviour
Use keyboard arrows to jump between navigation panel headers

#### Steps to reproduce
1. Move focus to panel (F8)
2. Use any arrow (up or down) to move to the next header

The first time the arrow is pressed it will switch headers as expected, but shortly after that, focus will return to the editor and you will need to press F8 again to return focus to the panel. And again, again, again...
Changing this focus automatically doesn't make much sense because it breaks keyboard-only navigation, and changing this behavior won't prevent the user from focusing on the editor, just use the F4 shortcut.

https://user-images.githubusercontent.com/47755037/126165923-1cc59f63-2b75-4f09-917d-10a3863999d8.mp4

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

```
**Current Date**: `seg. jul. 19 09:37:31 2021`
**Version**: `21.7.9`
**Build date**: `Jul 18 2021`
**Build number**: `858`
**Platform**: `linux`
**Operating System**: `Arch Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/home/linus/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/linus/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `pt_BR`
**Locale (interface)**: `pt_BR`
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breeze`
**Notes in current note folder**: `212`
**Calendar items**: `143`
**Enabled scripts**: `5`
```

</details>

**Comment by pbek** [comment]
Maybe we can distinguish between clicking on an item and getting there via the keyboard...

**Comment by pbek** [comment]
After the cursor is set in the note text edit it automatically gets the focus. We cannot distinguish between keyboard and mouse clicks. I guess I'll just geneally set the focus back to the navigation panel after the cursor position was changed in the note text edit..

**Comment by fabianski7** [comment]
then the focus would continue to go to the editor and then back to the panel?

**Comment by pbek** [comment]
Correct.
It's easier to click again into the editor with the mouse than to get the focus back when using the keyboard.

**Comment by pbek** [comment]
## 21.7.12
- the focus will now stay in the navigation panel after using it via mouse or keyboard

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by fabianski7** [comment]
definitively! thank you so much. now i can get rid of my mouse 😂

**Comment by pbek** [comment]
Great, thank you for testing! 

> now i can get rid of my mouse

give it to the cat 😁
