### ISSUE TITLE
Include PDF and SVG files in the notes list

### ISSUE THREAD

**Issue by heluca** [pbek/QOwnNotes#2195]
Thanks for developing QOwnNotes, I find it very useful and I use it all the time to document projects, training notes, company and product research, and a journal.  This often involves handwritten notes and diagrams (I use Styluslabs Write which creates standard SVG files), and collecting PDFs for reference.  The file structure of the app is fantastic to keep everything in one place.

I can create links to these files, but the default behaviour of drag and drop moves the file to a media folder which doesn't help and creating links is tedious.

I would like it if QOwnNotes would also list PDF and SVG files it finds in the notes folder in the notes list.
Useful: When I click on these file types, the note page could simply provide a clickable link that opens the file, perhaps with some metadata and file size.
Amazing: Ability to view these files within the app.

**Comment by pbek** [comment]
Thank you and I'm sorry, they will never be in the note list, that would break the concept of QOwnNotes and there currently isn't even a PDF viewer for Qt (see #1971).

But I remember someone tried to create a fork and hacked PDFs into the list (that only worked in some cases of settings and only built on his system 😁). I can't find that link.
