### ISSUE TITLE
New editor schema: shack

### ISSUE THREAD

**Issue by LetsHaveKiddos** [pbek/QOwnNotes#2196]
[shack]
BackgroundColorEnabled_-1=true
BackgroundColorEnabled_0=false
BackgroundColorEnabled_1=true
BackgroundColorEnabled_12=false
BackgroundColorEnabled_13=false
BackgroundColorEnabled_14=false
BackgroundColorEnabled_15=false
BackgroundColorEnabled_16=false
BackgroundColorEnabled_17=false
BackgroundColorEnabled_18=false
BackgroundColorEnabled_19=true
BackgroundColorEnabled_2=true
BackgroundColorEnabled_21=true
BackgroundColorEnabled_22=true
BackgroundColorEnabled_23=true
BackgroundColorEnabled_25=true
BackgroundColorEnabled_3=false
BackgroundColorEnabled_4=true
BackgroundColorEnabled_7=false
BackgroundColorEnabled_8=false
# main
BackgroundColor_-1=@Variant(\0\0\0\x43\x1\xff\xff\x31\x31\x38\x38\x4c\x4c\0\0)
# link:
BackgroundColor_0="@Variant(\0\0\0\x43\x1\xff\xff\x30\x30==EE\0\0)"
BackgroundColor_1=@Variant(\0\0\0\x43\x1\xff\xff\x33\x33\x33\x33\x33\x33\0\0)
# header 1:
BackgroundColor_12=@Variant(\0\0\0\x43\x1\xff\xff\xeb\xeb\xeb\xeb\xf0\xf0\0\0)
BackgroundColor_13=@Variant(\0\0\0\x43\x1\xff\xff\xeb\xeb\xeb\xeb\xf0\xf0\0\0)
BackgroundColor_14=@Variant(\0\0\0\x43\x1\xff\xff\xeb\xeb\xeb\xeb\xf0\xf0\0\0)
BackgroundColor_15=@Variant(\0\0\0\x43\x1\xff\xff\xeb\xeb\xeb\xeb\xf0\xf0\0\0)
BackgroundColor_16=@Variant(\0\0\0\x43\x1\xff\xff\xeb\xeb\xeb\xeb\xf0\xf0\0\0)
# header 6:
BackgroundColor_17=@Variant(\0\0\0\x43\x1\xff\xff\xeb\xeb\xeb\xeb\xf0\xf0\0\0)
# quote:
BackgroundColor_18=@Variant(\0\0\0\x43\x1\xff\xff\xf5\xf5\xf9\xf9\xd8\xd8\0\0)
BackgroundColor_19=@Variant(\0\0\0\x43\x1\xff\xff\x33\x33\x33\x33\x33\x33\0\0)
BackgroundColor_2=@Variant(\0\0\0\x43\x1\xff\xff\x33\x33\x33\x33\x33\x33\0\0)
# horizontal rule:
BackgroundColor_21=@Variant(\0\0\0\x43\x1\xff\xff\xA1\xA1\x8C\x8C\x8B\x8B\0\0)
# table:
BackgroundColor_22=@Variant(\0\0\0\x43\x1\xff\xff\x50\x50\x56\x56\x6d\x6d\0\0)
# code:
BackgroundColor_23=@Variant(\0\0\0\x43\x1\xff\xff\x50\x50\x56\x56\x6d\x6d\0\0)
# focused line:
BackgroundColor_25=@Variant(\0\0\0\x43\x1\xff\xff\x17\x17\x1a\x1a\x26\x26\0\0)
# image:
BackgroundColor_3=@Variant(\0\0\0\x43\x1\xff\xff\xe4\xe4\xff\xff\xe4\xe4\0\0)
# code:
BackgroundColor_4=@Variant(\0\0\0\x43\x1\xff\xff\x50\x50\x56\x56\x6d\x6d\0\0)
# italic:
BackgroundColor_7=@Variant(\0\0\0\x43\x1\xff\xff\x9e\x9e\xb6\xb6\xff\xff\0\0)
# bold:
BackgroundColor_8=@Variant(\0\0\0\x43\x1\xff\xff\xdb\xdb\xf9\xf9\xe5\xe5\0\0)
Bold_12=true
Bold_13=true
Bold_14=true
Bold_15=true
Bold_16=true
Bold_17=true
Bold_8=true
FontSizeAdaption_12=200
FontSizeAdaption_13=160
FontSizeAdaption_14=130
FontSizeAdaption_16=90
FontSizeAdaption_17=90
ForegroundColorEnabled_-1=true
ForegroundColorEnabled_-1000=true
ForegroundColorEnabled_0=true
ForegroundColorEnabled_1=true
ForegroundColorEnabled_10=true
ForegroundColorEnabled_11=true
ForegroundColorEnabled_12=true
ForegroundColorEnabled_13=true
ForegroundColorEnabled_14=true
ForegroundColorEnabled_15=true
ForegroundColorEnabled_16=true
ForegroundColorEnabled_17=true
ForegroundColorEnabled_18=true
ForegroundColorEnabled_19=true
ForegroundColorEnabled_2=true
ForegroundColorEnabled_20=true
ForegroundColorEnabled_21=true
ForegroundColorEnabled_22=true
ForegroundColorEnabled_23=true
ForegroundColorEnabled_24=true
ForegroundColorEnabled_26=true
ForegroundColorEnabled_3=true
ForegroundColorEnabled_4=true
ForegroundColorEnabled_5=true
ForegroundColorEnabled_6=true
ForegroundColorEnabled_7=true
ForegroundColorEnabled_8=true
ForegroundColorEnabled_9=true
# main:
ForegroundColor_-1=@Variant(\0\0\0\x43\x1\xff\xff\xe9\xe9\xd9\xd9\xd3\xd3\0\0)
# link:
ForegroundColor_0=@Variant(\0\0\0\x43\x1\xff\xff\x84\x84\x9b\x9b\xb1\xb1\0\0)
ForegroundColor_1=@Variant(\0\0\0\x43\x1\xff\xff\xfc\xfc~~\0\0\0\0)
ForegroundColor_10=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xff\xff\0\0\0\0)
# comment:
ForegroundColor_11=@Variant(\0\0\0\x43\x1\xff\xff\x50\x50\x56\x56\x6d\x6d\0\0)
# header 1:
ForegroundColor_12=@Variant(\0\0\0\x43\x1\xff\xff\x6e\x6e\x66\x66\x8c\x8c\0\0)
# header 2:
ForegroundColor_13=@Variant(\0\0\0\x43\x1\xff\xff\x6e\x6e\x66\x66\x8c\x8c\0\0)
# header 3:
ForegroundColor_14=@Variant(\0\0\0\x43\x1\xff\xff\x6e\x6e\x66\x66\x8c\x8c\0\0)
# header 4:
ForegroundColor_15=@Variant(\0\0\0\x43\x1\xff\xff\x6e\x6e\x66\x66\x8c\x8c\0\0)
# header 5:
ForegroundColor_16=@Variant(\0\0\0\x43\x1\xff\xff\x6e\x6e\x66\x66\x8c\x8c\0\0)
# header 6:
ForegroundColor_17=@Variant(\0\0\0\x43\x1\xff\xff\x6e\x6e\x66\x66\x8c\x8c\0\0)
# quote:
ForegroundColor_18=@Variant(\0\0\0\x43\x1\xff\xff\x6c\x6c\x96\x96\xa5\xa5\0\0)
ForegroundColor_19=@Variant(\0\0\0\x43\x1\xff\xff\0\0\xaa\xaa\0\0\0\0)
ForegroundColor_2=@Variant(\0\0\0\x43\x1\xff\xff\xfc\xfc~~\0\0\0\0)
ForegroundColor_20=@Variant(\0\0\0\x43\x1\xff\xff\xe1\xe1\xe1\xe1\xe1\xe1\0\0)
# horizontal rule:
ForegroundColor_21=@Variant(\0\0\0\x43\x1\xff\xff\x31\x31\x38\x38\x4c\x4c\0\0)
# table:
ForegroundColor_22=@Variant(\0\0\0\x43\x1\xff\xff\x6c\x6c\x96\x96\xa5\xa5\0\0)
# code:
ForegroundColor_23=@Variant(\0\0\0\x43\x1\xff\xff\xe9\xe9\xd9\xd9\xd3\xd3\0\0)
# masked syntax:
ForegroundColor_24=@Variant(\0\0\0\x43\x1\xff\xff\xf1\xf1\x7e\x7e\x64\x64\0\0)
# broken link:
ForegroundColor_26=@Variant(\0\0\0\x43\x1\xff\xff\xa3\xa3\x41\x41\x42\x42\0\0)
# image:
ForegroundColor_3=@Variant(\0\0\0\x43\x1\xff\xff\x98\x98\xb7\xb7\xa4\xa4\0\0)
# code:
ForegroundColor_4=@Variant(\0\0\0\x43\x1\xff\xff\xe9\xe9\xd9\xd9\xd3\xd3\0\0)
ForegroundColor_5=@Variant(\0\0\0\x43\x1\xff\xff\xe1\xe1\xe1\xe1\xe1\xe1\0\0)
ForegroundColor_6=@Variant(\0\0\0\x43\x1\xff\xff\xe1\xe1\xe1\xe1\xe1\xe1\0\0)
# italic:
ForegroundColor_7=@Variant(\0\0\0\x43\x1\xff\xff\xe9\xe9\xd9\xd9\xd3\xd3\0\0)
# bold:
ForegroundColor_8=@Variant(\0\0\0\x43\x1\xff\xff\xe9\xe9\xd9\xd9\xd3\xd3\0\0)
# list item:
ForegroundColor_9=@Variant(\0\0\0\x43\x1\xff\xff\xf2\xf2\xb0\xb0\x8c\x8c\0\0)
Italic_7=true
Name=oomox-shack
Underline_26=true
Underline_0=true

[Export]
SchemaKey=EditorColorSchema-8ec0b6b4-ad84-4710-8b56-7971d0b263ed

# vim: set ft=dosini :

**Comment by pbek** [comment]
Thank you very much. I'll put that into the next release.

**Comment by pbek** [comment]
## 21.7.13
- added a new editor color schema *Oomox Shack* by @LetsHaveKiddos

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
