### ISSUE TITLE
Unable to move notes to other subfolders within the same note folder when using note tree.

### ISSUE THREAD

**Issue by RichardBaker3020** [pbek/QOwnNotes#2197]
#### Expected behaviour
Notes can be moved from one subfolder to another within the same folder, just like they can be moved to other folders.

#### Actual behaviour
Notes can only be moved to other folders, the folder containing the note itself and its subfolders are not listed as destination options

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

**Version**: `21.5.5`
**Build date**: `May 25 2021`
**Build number**: `838`
**Platform**: `linux`
**Operating System**: `Ubuntu Core 18`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Snapcraft`
**Qt Version (build)**: `5.9.5`
**Qt Version (runtime)**: `5.9.5`
**Portable mode**: `no`
**Application arguments**: `/snap/qownnotes/8360/usr/bin/QOwnNotes`, `-style=Breeze`, `--snap`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Calendar items**: `0`
**Enabled scripts**: `0`

</details>

**Comment by pbek** [comment]
That feature is still WIP, can you please mention that in <https://github.com/pbek/QOwnNotes/issues/790>.
