### ISSUE TITLE
Link for Notes

### ISSUE THREAD

**Issue by RaiZiStyle** [pbek/QOwnNotes#2199]
Hello, 
First of all, I'm not even sure if I post at the good place. I'm kinda new to GitHub. Sorry if I'm at the wrong place. 
But I was wondering if it's possible to create link for a note just like Joplin does. 

#### Expected behaviour
We are in **Second_Folder**, in the **Note_2**
[Link to note2]\(id:xxxxxxxxxxxxxxxx) # Create a link to jump to Note_1

Tree of Notes:
```
- General note
    - First Folder
        - Note_1
    - Second Folder
        - Note_2
```
#### Actual behaviour
Currently not possible

**Comment by pbek** [comment]
> First of all, I'm not even sure if I post at the good place. I

It's the perfect place... 😉 

There it is:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/1798101/128592897-a2fb1e9c-a6f2-4a9f-a519-25334b32f70f.png">

**Comment by RaiZiStyle** [comment]
Oh that's great 👍 Thanks

**Comment by pbek** [comment]
Great, I'll close this then. 😉
