### ISSUE TITLE
Sync issue with rootpath

### ISSUE THREAD

**Issue by Yamakasi** [pbek/QOwnNotes#22]
Hi,

Great app but there is some sync issue.

Owncloud expects Notes in / but if you want to lineup your ~/Documents etc with your userpath this does not work. I have set my Notes folder in ~/Notes and made a sync for it in the ownCloud but your desktopapp still doesn't see a mainsync folder for owncloud, but I set it.

I think this always have been an ownCloud issue as if you start syncing a userdir, all stuff in it is also sycned you don't want and you need to deselect these folders right away after adding the sync. The issue is that your app actually needs the userfolder for the rootpath to work in Owncloud so to say /Notes.

Can you look into this ?

Thanks!

**Comment by Yamakasi** [comment]
OK, some update.

It seems atht you need to set the path before the Notes path as rootpath on your local system. Even when it;s not tthe default ownCloud base dir where Notes lives in locally.

So if yo have /Owncloud/Notes set /Owncloud on your local system as Owncloud root.

**Comment by pbek** [comment]
Hi @Yamakasi , thank you for using QOwnNotes and your report.
The reason QOwnNotes needs to know the main sync folder of ownCloud is that it knows path of the notes folder on the ownCloud server (to ask for trash and file versions).

So you locally have your notes in ~/Notes? on the ownCloud server your notes on the ownCloud webpage are shown in "/Notes", right?
Do you locally sync your whole home directory or do you use selective sync?

**Comment by pbek** [comment]
Maybe this can also help you: <http://www.qownnotes.org/Knowledge-base/QOwnNotes-settings-are-reporting-a-problem-with-my-ownCloud-path>

**Comment by Yamakasi** [comment]
Hi I have all in root of my user and ownCloud dir indeed.

I do selective sync per directory, so I have multiple mapsyncs to prevent syncing checked stuff accidentally :)

Thanks for the link and the good work!

**Comment by pbek** [comment]
But you can't select different local placements of remote folders with the ownCloud sync client, can't you? (at least I didn't manage so far) so your main sync folder is really your home directory, am I right?

Thank you for your kind words!

**Comment by pbek** [comment]
Im closing this issue now.
