### ISSUE TITLE
Option for local installation only without OwnCloud?

### ISSUE THREAD

**Issue by geckolinux** [pbek/QOwnNotes#220]
Hi there,

QOwnNotes looks excellent for what I need, except that I don't want the additional complication of an OwnCloud installation. Would it be possible to make it work with just a local folder?

Thanks!

**Comment by pbek** [comment]
You don't need ownCloud at all, using ownCloud just adds extra functionality...
Does this answer your question?

**Comment by geckolinux** [comment]
Hi Patrizio, thanks for the reply. I'm not sure what I'm doing wrong then, it looks like I'm running into a bug:

![screenshot from 2016-06-20 13-39-51](https://cloud.githubusercontent.com/assets/2692138/16206316/7c3e3108-36ed-11e6-9a08-39eb9099ed48.png)

![screenshot from 2016-06-20 13-41-40](https://cloud.githubusercontent.com/assets/2692138/16206318/7e118bd8-36ed-11e6-984e-11c7a0a35e32.png)

![screenshot from 2016-06-20 13-44-31](https://cloud.githubusercontent.com/assets/2692138/16206319/804cfe32-36ed-11e6-88c4-b750ef469614.png)

**Comment by pbek** [comment]
On which platform did you install QOwnNotes? When did you get these error messages?

**Comment by geckolinux** [comment]
Hi, I'm on openSUSE Tumbleweed x86-64. The error messages appeared on the first run and all successive runs.

**Comment by pbek** [comment]
At which step in the wizard does it appear? Which folder did you use as note folder?

**Comment by pbek** [comment]
I can't reproduce this under openSUSE Leap. Were you able to finish the wizard?
If yes, can you visit the general settings and press `Clear app data and exit`?

**Comment by geckolinux** [comment]
Hi, thanks for taking a look at this.

This appears after the wizard is finished.

I tried to use the default `~/ownCloud/Notes` directory.

I tried the `Clear app data and exit`, but the same thing happens again the next time I start it after the wizard finishes.

**Comment by pbek** [comment]
Is a `~/ownCloud/Notes/notes.sqlite` present and can you open it with a sqlite client?
Could you please post your debug output from the settings dialog.

**Comment by pbek** [comment]
And can you please look if there is an active note folder set in your note folder settings.

**Comment by pbek** [comment]
Could you please test version 16.06.9 for the `/notes.sqlite` problem and post an other debug output.

version 16.06.9:
- there now is note folder information in the debug dump in the settings dialog
- a fallback for loading the note folder path to prevent `Can't write 
  to "/notes.sqlite"` errors was added
- the layout direction for the `next` button in the welcome dialog was
  changed to `left to right` again, because some operating systems showed 
  strange behaviors with `right to left`

**Comment by geckolinux** [comment]
Hi @pbek thanks again for the help.

I updated to 16.06.9, but I have the same issue.

It looks like the problem is that the `~/ownCloud/Notes/notes.sqlite` file is not getting created.

Here's the folder settings:
![screenshot from 2016-06-21 08-24-14](https://cloud.githubusercontent.com/assets/2692138/16231012/d1cc1620-3789-11e6-926e-acc72d6b0de7.png)
The `Add Folder` button does not work for some reason, so I am unable to manually add a folder.

I'm attaching the debug info. Thanks again for taking a look at this bug.

[QOwnNotes Debug Information.md.txt](https://github.com/pbek/QOwnNotes/files/325657/QOwnNotes.Debug.Information.md.txt)

**Comment by pbek** [comment]
Thank you for gathering information.
What error message did you get this time?

I think your QOwnNotes managed to get over the welcome dialog without creating a note folder.
I will try to take care of that.

**Comment by geckolinux** [comment]
Hi, I'm still getting `Unable to establish a memory database connection.` and `Unable to establish a database connection with file '/home/MYSELF/ownCloud/Notes/notes.sqlite'.
Are the folder and the file writeable?`

And a question, where is the QOwnNotes config file located? I can't seem to find it. Thanks!

**Comment by pbek** [comment]
Can you please test version 16.06.10.

- if there were no note folders found when QOwnNotes starts they now will 
  generated from the settings at the very beginning, this should prevent some 
  errors
- the packages `libQt5Sql5` and `libQt5PrintSupport5` are now required in the 
  QOwnNotes openSUSE packages

Under Linux you will find the config file here: `~/.config/PBE/QOwnNotes.conf`

**Comment by pbek** [comment]
And could you please post an other debug dump from the settings with version 16.06.10.

**Comment by geckolinux** [comment]
Hi there, thanks for the fast response. I tried deleting my `~/.config/PBE` directory and my `~/ownCloud` directory, but I'm getting the same errors. I'm attaching my debug dump and also my config file:

[QOwnNotes Debug Information.md.txt](https://github.com/pbek/QOwnNotes/files/326054/QOwnNotes.Debug.Information.md.txt)

[QOwnNotes.conf.txt](https://github.com/pbek/QOwnNotes/files/326055/QOwnNotes.conf.txt)

**Comment by pbek** [comment]
I don't understand how it is possible that you still don't have note folder... :(
And could you please check if the package `libQt5Sql5` is now installed on your system.

**Comment by geckolinux** [comment]
> the packages `libQt5Sql5` and `libQt5PrintSupport5` are now required in the QOwnNotes openSUSE packages

Oops, this got me thinking, and I fixed it. This was the missing package: `libQt5Sql5-sqlite`. Works great now. Sorry for the red herring!

**Comment by pbek** [comment]
I wonder why that package didn't get installed automatically. I'll try to take care of that. Thanks a lot for all your input!

**Comment by geckolinux** [comment]
I did have `libQt5Sql5` but not `libQt5Sql5-sqlite`. So I suspect that `libQt5Sql5-sqlite` is a "soft" (recommended) dependency of `libQt5Sql5`, and I have installation of recommended packages disabled.

**Comment by illucent** [comment]
The same issue appeared after I upgraded Fedora 27 to Fedora 28. Before this application was perfect.

**Comment by pbek** [comment]
@illucent so the `libQt5Sql5-sqlite` package was removed by the Fedora upgrade?

**Comment by illucent** [comment]
@pbek Hi! Thanks for reply! No` libQt5Sql5-sqlite` is upgraded smootly but env `LD_LIBRARY_PATH` disappeared after Fedora upgrade to version 28. 
Fixed by restoring / adding 
'LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib64:/lib:/usr/lib64:/usr/lib:/usr/local/lib64:/usr/local/lib; export LD_LIBRARY_PATH' systemc env variable.
Works perfectly again.

**Comment by pbek** [comment]
So I assume there is nothing to do for me, great. ;)

**Comment by illucent** [comment]
Thanks again. I think this is general Fedora 28 issue of `LD_LIBRARY_PATH` or `/etc/ld.so.conf` .
