### ISSUE TITLE
[I] Importing Joplin Notes with Special Characters Such as Apostrophes

### ISSUE THREAD

**Issue by netguerrilla12** [pbek/QOwnNotes#2200]
#### Expected behaviour

When importing Joplin notes with special characters (such as apostrophes), QOwnNotes should import these items correctly.

#### Actual behaviour

In the case of apostrophes the character appears as a special character after the import. Evernote notes with apostrophes appear to import fine.

#### Steps to reproduce

Import any Joplin note(s) with special characters.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[13:30:28] [debug] updatePanelMenu - 'updatePanelMenu'
[13:30:56] [debug] updatePanelMenu - 'updatePanelMenu'
[13:30:56] [debug] updatePanelMenu - 'updatePanelMenu'
[13:30:56] [debug] updatePanelMenu - 'updatePanelMenu'
[13:30:56] [debug] updatePanelMenu - 'updatePanelMenu'
[13:30:56] [debug] updatePanelMenu - 'updatePanelMenu'
[13:31:05] [debug] updatePanelMenu - 'updatePanelMenu'
[06:19:58] [debug] updatePanelMenu - 'updatePanelMenu'
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Aug 10 06:21:29 2021`
**Version**: `21.8.2`
**Build date**: `Aug  7 2021`
**Build number**: `866`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\SV1\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1360x768`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `13`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\SV1\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `10`
**localPath**: `C:\QOwnNotes\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\QOwnNotes\Notes\notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `true`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**EvernoteImport/AttachmentImportCheckBoxChecked** (QString): `true`
**EvernoteImport/ImageImportCheckBoxChecked** (QString): `true`
**EvernoteImport/MetaDataUnCheckedList** (QStringList): `, created, updated, , note-attributes/subject-date, note-attributes/latitude, note-attributes/longitude, note-attributes/altitude, note-attributes/author, note-attributes/source, note-attributes/source-application, note-attributes/application-data`
**EvernoteImportDialog/geometry** (QByteArray): `<binary data>`
**FileDialog/LastPath** (QString): `C:/Users/SV1/Downloads/Joplin/Photography`
**FileDialog/LastPath-Evernote Import** (QString): `C:/Users/SV1/Downloads`
**FileDialog/LastPath-ImportTextFiles** (QString): `C:/QOwnNotes/Notes/Test`
**FileDialog/LastPath-Joplin Import** (QString): `C:/Users/SV1/Downloads/Joplin/Photography`
**FileDialog/LastPath-NoteMarkdownExport** (QString): `C:/Users/SV1/Downloads/Joplin`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**JoplinImport/AttachmentImportCheckBoxChecked** (QString): `true`
**JoplinImport/FolderImportCheckBoxChecked** (QString): `false`
**JoplinImport/ImageImportCheckBoxChecked** (QString): `true`
**JoplinImport/MetadataImportCheckBoxChecked** (QString): `false`
**JoplinImport/TagImportCheckBoxChecked** (QString): `true`
**JoplinImportDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-08-10T05:48:50.618`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Calibri,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/tagTreeWidgetExpandState-1** (QStringList): `1, 2`
**NoteFolder-1/NoteTabNameList** (QStringList): `Synchronising your notes ðŸ”„, David Busch's Canon EOS Rebel T61300D Guide to Digital SLR Photography David D. Busch 9781681981703 Amazon.com Books`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `, `
**NoteHistory-1** (QVariantList): `<variant list with 26 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `25`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePrinting** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TagAddDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `npsLxBsgeNDz`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (int): `15`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `C:/QOwnNotes/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2021-08-06T16.06.14, Note 2021-08-06T16.05.39, Unbenannt, Images and Attachments, WordPress Installation Check List, Note 2021-08-05T09.20.41, David Busch's Canon EOS Rebel T61300D Guide to Digital SLR Photography David D, Amazon, Test Notiz, Fwd We just shipped your order!, Fwd Re Re ABEBOOKS Order 137361858, Fwd Re ABEBOOKS Order 137361858, Fwd AbeBooks Sales Order No, 000df3247ebc4551a9ad2b7233ad07a0`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-dYqYLZMC3Y5K/name** (QString): `Minimal`
**workspace-dYqYLZMC3Y5K/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-dYqYLZMC3Y5K/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspace-npsLxBsgeNDz/name** (QString): `Full`
**workspace-npsLxBsgeNDz/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-npsLxBsgeNDz/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, dYqYLZMC3Y5K, npsLxBsgeNDz`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\SV1\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `SV1`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**GOOGLE_API_KEY**: `no`
**GOOGLE_DEFAULT_CLIENT_ID**: `no`
**GOOGLE_DEFAULT_CLIENT_SECRET**: `no`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\SV1`
**LOCALAPPDATA**: `C:\Users\SV1\AppData\Local`
**LOGONSERVER**: `\\SV1`
**MACRIUM_196_AES**: `0`
**MACRIUM_196_APPENDTYPE**: `1`
**MACRIUM_196_BACKUP_TYPE**: `0`
**MACRIUM_196_COMPRESSION**: `1`
**MACRIUM_196_CURRENT_INCREMENT**: `3`
**MACRIUM_196_DIRECTORY**: `G:\Drive Images\SV1\`
**MACRIUM_196_DRIVE_PARTITION1**: `0, 0`
**MACRIUM_196_DRIVE_PARTITION2**: `0, 1`
**MACRIUM_196_DRIVE_PARTITION3**: `0, 2`
**MACRIUM_196_DRIVE_PARTITION4**: `0, 3`
**MACRIUM_196_DRIVE_PARTITION5**: `0, 4`
**MACRIUM_196_FILECOUNT**: `4`
**MACRIUM_196_FILENAME1**: `C85E30F695E4BA38-00-00.mrimg`
**MACRIUM_196_FILENAME2**: `C85E30F695E4BA38-01-01.mrimg`
**MACRIUM_196_FILENAME3**: `C85E30F695E4BA38-02-02.mrimg`
**MACRIUM_196_FILENAME4**: `C85E30F695E4BA38-03-03.mrimg`
**MACRIUM_196_FILEPATH1**: `G:\Drive Images\SV1\C85E30F695E4BA38-00-00.mrimg`
**MACRIUM_196_FILEPATH2**: `G:\Drive Images\SV1\C85E30F695E4BA38-01-01.mrimg`
**MACRIUM_196_FILEPATH3**: `G:\Drive Images\SV1\C85E30F695E4BA38-02-02.mrimg`
**MACRIUM_196_FILEPATH4**: `G:\Drive Images\SV1\C85E30F695E4BA38-03-03.mrimg`
**MACRIUM_196_IMAGEID**: `C85E30F695E4BA38`
**MACRIUM_196_INCREMENT1**: `0`
**MACRIUM_196_INCREMENT2**: `1`
**MACRIUM_196_INCREMENT3**: `2`
**MACRIUM_196_INCREMENT4**: `3`
**MACRIUM_196_INTELLIGENT**: `1`
**MACRIUM_196_MAXFILESIZE**: `500`
**MACRIUM_196_METHOD**: `2`
**MACRIUM_196_METHOD1**: `0`
**MACRIUM_196_METHOD2**: `2`
**MACRIUM_196_METHOD3**: `2`
**MACRIUM_196_METHOD4**: `2`
**MACRIUM_196_PASSWORD**: `0`
**MACRIUM_PREFIX**: `MACRIUM_196`
**NUMBER_OF_PROCESSORS**: `4`
**OneDrive**: `C:\Users\SV1\OneDrive`
**OneDriveConsumer**: `C:\Users\SV1\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Users\SV1\AppData\Local\Microsoft\WindowsApps;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 60 Stepping 3, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `3c03`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\SV1\AppData\Local\Temp`
**TMP**: `C:\Users\SV1\AppData\Local\Temp`
**USERDOMAIN**: `SV1`
**USERDOMAIN_ROAMINGPROFILE**: `SV1`
**USERNAME**: `SV1`
**USERPROFILE**: `C:\Users\SV1`
**windir**: `C:\WINDOWS`
**__COMPAT_LAYER**: `DetectorsAppHealth`
</details>

This issue seems to be intermittent. I've attached a screen shot that shows this issue.

![QON 1](https://user-images.githubusercontent.com/88498198/128866641-2e88bf85-c37f-4149-93d7-2f539fc81e63.JPG)

I've also attached the appropriate JEX file. GitHub wouldn't let me upload the JEX file so I renamed it to .ZIP.

[RPhotography.zip](https://github.com/pbek/QOwnNotes/files/6961644/RPhotography.zip)

**Comment by pbek** [comment]
I don't seem to have an issue with your JEX... (also see https://github.com/pbek/QOwnNotes/issues/2189#issuecomment-895455198)

The text is fine for me:

![image](https://user-images.githubusercontent.com/1798101/128822622-f13246d8-f26a-46c1-ab77-98ed9a0ee260.png)

And I also see the image:

![image](https://user-images.githubusercontent.com/1798101/128822753-9904ae58-ec49-4eeb-8719-0f881c8a9645.png)

**Comment by pbek** [comment]
Do you have the same issue when running QOwnNotes in a new session (see [cli-parameters](https://www.qownnotes.org/getting-started/cli-parameters.html))?

**Comment by netguerrilla12** [comment]
Yes. I ran QOwnNotes -- session test from a command prompt (in admin mode) and got the same results.

**Comment by pbek** [comment]
How do the source files from the JEX folder (you should see the id in the imported note) and the imported note file look if you open them in another editor like https://code.visualstudio.com/? And can you please post those two files here.

**Comment by pbek** [comment]
I wanted to test your export on Windows, but Windows 10 can't even extract your ZIP, says it's invalid.

**Comment by netguerrilla12** [comment]
That's very weird. Since the JEX file is (I believe) a TAR file, I simply renamed it to ZIP. I just tested it with another JEX file just now. I first renamed the JEX file to ZIP. Then I opened it with 7-Zip with no problem. I've been using 7-Zip for years. I'm wondering if the native Windows 10 zip functionality can't handle the TAR file. Maybe try opening/extracting it with 7-Zip, WinZip (I guess it's still around) or something like that.

**Comment by pbek** [comment]
Yes, it's a tar file, I put the content in a ZIP file now.
[RPhotography.zip](https://github.com/pbek/QOwnNotes/files/6977417/RPhotography.zip)

**Comment by netguerrilla12** [comment]
I just downloaded and opened that file with 7-Zip with no problem. I haven't yet had time to try the other test you asked me to try. Hopefully, I can get to it later today.

**Comment by pbek** [comment]
Don't bother testing it...
Windows needed an extra-nudge.

## 21.8.3
- UTF-8 problems on Windows with the Joplin note import were fixed

**Comment by netguerrilla12** [comment]
Nice. Thanks. I'll download that version and test it later if you're ready for me to test it.

**Comment by pbek** [comment]
There now is a new release (soon it will be built), could you please test it and report if it works for you?

**Comment by netguerrilla12** [comment]
I'd be happy to do that. Thanks for fixing this issue so quickly.

**Comment by netguerrilla12** [comment]
I think you fixed it. All the apostrophes appear correct in the right places and the image looks good. Now I just have to figure out the QON syncing component so I can stop getting the silly sync errors I'm getting with Joplin which the Joplin keeps saying don't happen.

**Comment by pbek** [comment]
Great, thank you for testing!

As for syncing, QON doesn't sync! You can use any Sync Client you like. See https://www.qownnotes.org/getting-started/concept.html

> All Notes count goes to 0

Never saw that so far. If you can reproduce that please open an issue. 😉

**Comment by netguerrilla12** [comment]
I know QON doesn't handle syncing directly which is probably smart on your part. Joplin syncing issues get reported **a lot**. Anyway, I just have to figure out the best way to handling the syncing for my QON notes. I'm somewhat familiar with NextCloud because that's what I'm using for Joplin but I'm unsure if that's the best way to go.

**Comment by pbek** [comment]
Syncing (especially for large files) is very fragile thing and worth its own app.
So do you already use a Nextcloud server? https://www.qownnotes.org/getting-started/concept.html has a diagram of all the parts QOwnNotes can use.

If you don't use Nextcloud / ownCloud you can also use things like Dropbox and use a "normal" markdown editor on your phone, instead of Nextcloud Notes. (there are some recorded on https://www.qownnotes.org/getting-started/concept.html#nextcloud-notes-mobile-app)

**Comment by pbek** [comment]
But you can also use QOwnNotes only "offline" on your desktop computer, also together with the QOwnNotes browser extension, if you want to keep your bookmarks in simple markdown files or have a web clipper.
Of course the best experience you'll have with a Nextcloud / ownCloud server.

**Comment by netguerrilla12** [comment]
Thanks for the suggestions. I do want to test the QON web clipper next. The Joplin web clipper works pretty well. As far as syncing, the reason I want to use it is so I can have my notes synced across all my devices. Syncing is one thing Evernote does very well. Joplin is so so at syncing. Yes. I do already use a Nextcloud server for Joplin.

The problem is I'm approaching the file quota on that server so I have to decide what to do about it. I think I might be able to use the same server for QON if I migrate the notes in phases and delete the Joplin notes as I complete the import for a given notebook in QON. One thing I **really** like about QON is that puts all the MD files in one note instead keeping them separate like Joplin does. So like in my photography example. there were something 16 Joplin MD files for only two notes.

**Comment by pbek** [comment]
>  I do want to test the QON web clipper next

https://www.qownnotes.org/getting-started/browser-extension.html

> The problem is I'm approaching the file quota on that server so I have to decide what to do about it. 

You can always host your own Nextcloud server. I keep one on a VPS "in the internet" and one at home. 😁  But are using Docker...

> there were something like 16 Joplin MD files for only two notes.

Joplin keeps all metadata in "markdown" files (that really aren't markdown files). That way you are even vendor-locked-in with "markdown" files. I don't like that at all.

**Comment by netguerrilla12** [comment]
That's an interesting idea. I was thinking I had to run Nextcloud "in the cloud" but I guess that's technically not true. I could host it locally and have my devices access it locally. That might be worth looking into. Thanks for the idea.

**Comment by pbek** [comment]
Just grab a Raspberry Pi or maybe you can put it on your NAS (if you have one).
I use Let's Encrypt to get TLS certs and can also access my local services from the internet by routing port 80 and 443 to my local server. 😉

**Comment by netguerrilla12** [comment]
I don't have a NAS or a Raspberry Pi. I might install it on a VirtualBox VM on a desktop machine that has some hard drive space available.

This looks like a good tutorial. https://www.how2shout.com/how-to/how-to-install-nextcloud-server-on-windows-10.html

What I'm not clear on is how I'd access the files locally. Would I use a local IP with the appropriate folder names in the WebDav configuration?

**Comment by pbek** [comment]
You could also setup Wireguard to connect to your local server from outside without exposing ports 80/443.

**Comment by pbek** [comment]
> I don't have a NAS or a Raspberry Pi.

Not yet 😁  I'd go for the latter, if you don't have a NAS. Time to hone your Linux skills. 😀 

> This looks like a good tutorial. https://www.how2shout.com/how-to/how-to-install-nextcloud-server-on-windows-10.html

I'd never bother to host such services on Windows 10! If you really must use a VM with e.g. Virtual Box and setup a Linux Distribution (like Ubuntu) there.

**Comment by pbek** [comment]
> Would I use a local IP with the appropriate folder names in the WebDav configuration?

Yes, you would need to use the IP of the box or VM it is running on. If it's a VM you would need to get it a "real" ip in your local network.

But I would really just buy a raspberry pi with a SD card and a power supply and use that as server. You can even run Docker on a Raspberry Pi 4 (if you would like to dive in that far).

**Comment by netguerrilla12** [comment]
Sounds good. Thanks.

**Comment by pbek** [comment]
If you just want file syncing and nothing else, you can also just install https://syncthing.net/ on your local computers...

**Comment by netguerrilla12** [comment]
I was aware of SyncThing. I'd forgotten about it. It might be easier to use. Thanks.

**Comment by pbek** [comment]
...but then you would miss out on all the nice things like calendars, remote trash, remote versions, ... 😀

**Comment by netguerrilla12** [comment]
Fair point. I don't care about calendars in this scenario. I've been using Google Calendar for years. I have my day job Outlook calendar synced to my Google Calendar. I also have my wife's Google Calendar synced to my Google Calendar. Remote trash could be useful. What are "remote versions?"

**Comment by pbek** [comment]
But on the other hand servers are starting at 2.69 EUR per month at https://www.netcup.eu/vserver/vps.php! I even have some 5 EUR vouchers left if you want.

I exited Google a long time ago and use Nextcloud for Calendar and Contacts...

**Comment by pbek** [comment]
> What are "remote versions?"

Nextcloud keeps version of your files. QON can access those on the server directly. See https://www.qownnotes.org/getting-started/qownnotesapi.html#what-qownnotesapi-does

**Comment by netguerrilla12** [comment]
A VPS is also a good idea. Now I've got too much to think about. :)

**Comment by pbek** [comment]
I'm sorry 😅

**Comment by pbek** [comment]
I'm self-hosting everything I can, even my mail server or bitwarden. 😁

**Comment by netguerrilla12** [comment]
Nice!

**Comment by pbek** [comment]
Let me know if you need help. 😁

**Comment by netguerrilla12** [comment]
Thanks. I appreciate that.
