### ISSUE TITLE
Flatpak out of date

### ISSUE THREAD

**Issue by andyhubbert941** [pbek/QOwnNotes#2202]
Hi

The flatpak version of QOwnNotes is currently quite out of date. I have no idea how to update it in flathub but if someone with more know-how is able to point me in the right direction I will happily do the work 

Love this project and many thanks for keeping great features and updates coming!

Current flatpak version: 21.7.5

Still appears to work and be stable on latest Ubuntu LTS (elementary OS)

**Comment by pbek** [comment]
The Flatpak repository https://github.com/flathub/org.qownnotes.QOwnNotes is community maintained. 😅   Best to open an issue on https://github.com/flathub/org.qownnotes.QOwnNotes/issues directly. 😉

**Comment by pbek** [comment]
And best ping @stobbsm directly. 😉

**Comment by pbek** [comment]
Btw. QOwnNotes has an updater for the AppImage version and you always can use the snap or PPA of QOwnNotes...
