### ISSUE TITLE
Strikeout and code inline formatting are mutually exclusive in the same line in the editor

### ISSUE THREAD

**Issue by alk0** [pbek/QOwnNotes#2205]
21.8.3

"Strikeout" and "code" inline formatting don't work at the same time in the same line in the _editor_ pane, the first used in the line takes precedence. The _preview_ is correct.

#### Expected behaviour (screenshot)

![image](https://user-images.githubusercontent.com/10332037/129406239-a9e1d852-a9ea-40d2-a4cf-0b18a498f258.png)

(^ Preview for comparison, not _exactly_ how it would/should look in the editor.)

#### Actual behaviour (screenshot)

![image](https://user-images.githubusercontent.com/10332037/129406132-d8a8db95-e672-4b7a-b627-eb94625104f9.png)

#### Steps to reproduce

```
Text highlighting:  `code`, ~~strikeout~~, `code`, ~~strikeout~~

Text highlighting:  ~~strikeout~~, `code`, ~~strikeout~~, `code`
```

**Comment by pbek** [comment]
I can't reproduce this:

![image](https://user-images.githubusercontent.com/1798101/129409261-caae3f55-7b12-49ae-9b62-9ccdd5546cd6.png)

Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.

**Comment by pbek** [comment]
Ah, now I see what you mean. 

![image](https://user-images.githubusercontent.com/1798101/129410100-cc67c201-d307-40eb-b18e-202f2d9cf41c.png)

@Waqar144, any suggestions?

**Comment by Waqar144** [comment]
Seems like a bug in the parser. Will take a look at it soon.

**Comment by pbek** [comment]
Awesome, thank you very much!

**Comment by pbek** [comment]
## 21.8.8
- fixed a problem with strikeout and code inline formatting in the same line
  (for [#2205](https://github.com/pbek/QOwnNotes/issues/2205), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by alk0** [comment]
Weird. While [package/binaries](https://build.opensuse.org/package/binaries/home:pbek:QOwnNotes/desktop/Arch_Extra) already has 21.8.8, [repositories](https://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Arch_Extra/x86_64/) still offers 21.8.7. Can you nudge it or something? If not, I'll install it from the binary zst package.

**Comment by pbek** [comment]
I started the OBS build a bit over one hour ago because it was down yesterday... Maybe it just needs some more time.

**Comment by alk0** [comment]
Ah, OK, gar kein Problem!

**Comment by pbek** [comment]
> Oh, and I can't download the binary without registering at build.opensuse.org first.

I just asked on IRC...

>  It's there now.

You mean you can install 21.8.8 from the repository, even if you can't download it directly, right?

**Comment by alk0** [comment]
> You mean you can install 21.8.8 from the repository, even if you can't download it directly, right?

Yes, I **can** update it as a regular package, having

```
[home_pbek_QOwnNotes_Arch_Extra]
SigLevel = Optional TrustAll
Server = http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Arch_Extra/$arch
```

in my `/etc/pacman.conf`. But I **can not** download the .zst from https://build.opensuse.org/package/binaries/home:pbek:QOwnNotes/desktop/Arch_Extra — "Please login to access the requested page." I can see it, but not download.

**Comment by alk0** [comment]
OK, about the formatting: works well now on normal cases, but a lot of marginal cases are inconsistent between the editor and the preview. Not critical for me, I'm used to not trusting Markdown on such cases. But it's something to be aware of.

Screenshots:

![image](https://user-images.githubusercontent.com/10332037/130200478-9f67fb87-10a6-4c4b-bb7a-301ee0a79994.png)
![image](https://user-images.githubusercontent.com/10332037/130200578-6377288f-c355-468d-a866-f0465386d821.png)

Code:

```
<!-- editor: OK; preview: OK -->
_***bold italic underlined***_

<!-- editor: no bold; preview: no bold -->
_***~bold italic underlined strikeout~***_

<!-- editor: no bold; preview: no strikeout -->
~_***bold italic underlined strikeout***_~

<!-- editor: no underline, no bold; preview: no bold -->
_***`bold italic underlined code`***_

<!-- editor: no code, no bold; preview: no bold, no strikeout -->
_***~`bold italic underlined strikeout code`~***_
```

Rendered by Github (no underline, otherwise correct):


_***bold italic underlined***_


_***~bold italic underlined strikeout~***_


~_***bold italic underlined strikeout***_~


_***`bold italic underlined code`***_


_***~`bold italic underlined strikeout code`~***_

But. As for the this particular issue (#2205), I think it can be closed now as fixed.

**Comment by pbek** [comment]
>  But I can not download the .zst from https://build.opensuse.org/package/binaries/home:pbek:QOwnNotes/desktop/Arch_Extra — "Please login to access the requested page." I can see it, but not download.

IRC said that was intended. But you can download in the repository directly. I updated the links for the webpage.

**Comment by pbek** [comment]
> OK, about the formatting: works well now on normal cases, but a lot of marginal cases are inconsistent between the editor and the preview. Not critical for me, I'm used to not trusting Markdown on such cases. But it's something to be aware of.

Those combinations are hideous. 😅 
I don't know if they would even work in the editor.
@Waqar144?

**Comment by Waqar144** [comment]
I guess it can be fixed, but I personally am not interested in doing it since these are rare and someone will always come up with some edge case that isn't being handled. No point in fixing unless it provides some real benefit. 

Strikeout isn't in commonmark even, so things can easily look broken with it.

**Comment by pbek** [comment]
I concur with @Waqar144, far too much pain and too many regressions to attempt to make that work.
