### ISSUE TITLE
Table formatting on Ctrl-Space doesn't shrink ----

### ISSUE THREAD

**Issue by alk0** [pbek/QOwnNotes#2206]
2.8.3

Table formatting on Ctrl-Space takes the divider into account, while it shouldn't. As a result, one can easily "expand" the table, but not shrink it back without editing the divider manually.

#### Expected behaviour

```
| Column 1 | Column 2                  |
| -------- | ------------------------- |
| Cell 1   | Cell 2                    |
```

Ctrl-Space (or Edit, Extra, "Autocomplete, solve equation or open URL"):

```
| Column 1 | Column 2 |
| -------- | -------- |
| Cell 1   | Cell 2   |
```

#### Actual behaviour

```
| Column 1 | Column 2                  |
| -------- | ------------------------- |
| Cell 1   | Cell 2                    |
```

Ctrl-Space:

```
| Column 1 | Column 2                  |
| -------- | ------------------------- |
| Cell 1   | Cell 2                    |
```

#### Steps to reproduce

see above

**Comment by pbek** [comment]
This functionality only adds or removes spaces. It doesn't remove other characters. So you need to remove `-------` by hand first.

**Comment by alk0** [comment]
OK, let it be. All other markdown editors that I've tried don't do it either, to be honest :) A bit annoying, but just a bit, not something critical. Let's close the issue with "Won't fix" or leave it as "Type: Support", then?

**Comment by pbek** [comment]
## 21.8.4
- in Markdown tables you now can also automatically shrink the headline
  separator columns if needed when pressing <kbd>Ctrl</kbd> + <kbd>Space</kbd>

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by alk0** [comment]
_Almost_ there. If we create a table like this

```
| h   | h   |
| --- | --- |
| c   | c   |
```

and try to "shrink" it with Ctrl-Space, it results in

```
| h | h |
| - | - |
| c | c |
```

which breaks rendering, because tables in "common" markdown extensions usually require at least 3 symbols for the divider line (can be `---` or `:-:`, for example, but not `::` or `:-` or `--` or just `-`). So, QOwnNotes' renderer doesn't treat this "overshrunk" table as a valid table either.

Sorry for annoyance, but I had to check this case. 1-symbol-wide columns can be quite common - maybe a number or a 1-letter flag or just empty:

```
|||
|:-:|---|
|||
```

(^ this one is valid)

Could you please do some additional checks to leave at least 3 symbols in the delimiter (`---`, `:--`, `--:`, `:-:`)?

**Comment by pbek** [comment]
> and try to "shrink" it with Ctrl-Space, it results in

Meh, it shouldn't shrink below 3 character. I though I had that covered already...

**Comment by pbek** [comment]
## 21.8.5
- a minimum of 3 headline separator characters are now used to produce valid
  Markdown tables when pressing <kbd>Ctrl</kbd> + <kbd>Space</kbd> in a table

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by alk0** [comment]
Uhm, waiting for an [Arch build](https://build.opensuse.org/package/binaries/home:pbek:QOwnNotes/desktop/Arch_Extra), I have a pretty weak PC here, building from source takes forever :(

**Comment by alk0** [comment]
OK, now the minimal "expandable" example is:
```
||
|-|
```

expands to:

```
|     |
| --- |
```
I'm 100% OK with that, I even like it, but, _strictly speaking_, I don't think it _should_ expand tables that are not compliant with that "3-dash rule" **_yet_**. But again, I cannot imagine any real situation where it could pose a problem (and if you don't like it, just don't hit Ctrl-Space, right?). So, my humble suggestion is to leave it as it is until someone complains again (if ever).

Otherwise, everything is just perfect. Vielen Dank!

**Comment by pbek** [comment]
QOwnNotes and GitHub are fine with 3 characters total and I couldn't even find ONE standard for it, but I added it anyway.

# QOwnNotes Changelog

## 21.8.6
- alignment characters in the headline separator line of a Markdown table are now
  not counted anymore to the minimum of 3 headline separator characters that are needed
  to produce a valid Markdown table when pressing <kbd>Ctrl</kbd> + <kbd>Space</kbd>

**Comment by pbek** [comment]
> Uhm, waiting for an Arch build, I have a pretty weak PC here, building from source takes forever :(

There are also pre-built Arch packages, snap packages, AppImages (QON can update those with the internal updater), ...
See https://www.qownnotes.org/installation/

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by alk0** [comment]
Oh, look, I see what you did, and this is not what I meant at all. `|:-:|` are fine, every other parser seems to agree on that.

I just meant that once you have a `|-|` only, it's not a "table" yet, since "tables" have at least three characters in the divider (by convention, so to say, not by any standard). So, expanding what is not yet a table seemed a bit "not strict" (but rather convenient) to me. And now I don't even think so anymore.

So, now in 21.8.6 `|:-:|` gets expanded to `|:---:|`, and I would prefer it the old way (21.8.5), without this fix, just for pure aesthetics, and because GFM and QOwnNote require no more than that. But it's not a big deal, of course.

**In short:** 21.8.5 was slightly better than 21.8.6 in my humble opinion. Anyway, the decision is yours, both are fine with me.

> There are also pre-built Arch packages

Yes, I have it configured, it just takes some time for the new build to appear there (build.opensuse.org), and it wasn't there yet at the moment of writing - this is what I meant by "waiting for an Arch build".

> and I couldn't even find ONE standard for it

JFYI, about tables:

* https://www.markdownguide.org/extended-syntax/#tables (not a standard, just a reference guide for one particular piece of software, but it does explicitly mention "three or more hyphens (---)")
* https://pandoc.org/MANUAL.html#tables (doesn't specify length anywhere)
* https://michelf.ca/projects/php-markdown/extra/#table (pandoc manual refers to this syntax, doesn't specify length either)
* https://github.github.com/gfm/#delimiter-row (doesn't really require it to be 3 chars long)

**Comment by pbek** [comment]
> I just meant that once you have a |-| only, it's not a "table" yet, since "tables" have at least three characters in the divider (by convention, so to say, not by any standard). So, expanding what is not yet a table seemed a bit "not strict" (but rather convenient) to me. And now I don't even think so anymore.

Since `|-|` isn't a column yet I think it's good that it will be expanded, so a valid table is produced (e.g. for people who don't know about the 3-dashes rule).

> https://www.markdownguide.org/extended-syntax/#tables

Yes, I saw that too. That's why I thought you meant I need at least 3 dashes in any case... I think most of the time it will not matter anyway because usually you need more than just 3 chars in your columns and I don't know how many people are even using alignments, so I guess we can stay at the way 21.8.6 does it and be save.

**Comment by pbek** [comment]
So, I'll close this for now. 😁

**Comment by pbek** [comment]
Meh, https://www.tablesgenerator.com/markdown_tables is also just using 3 chars in total. 😅

**Comment by pbek** [comment]
So, back we go... 😁 

## 21.8.7
- fall back to just counting a minimum of 3 headline separator characters in a Markdown
  table when pressing <kbd>Ctrl</kbd> + <kbd>Space</kbd>, because it looks more beautiful

There now is a new release, could you please test it and report if it works for you?

**Comment by alk0** [comment]
Yay! OK, just writing to report that I haven't found any breaking examples, everything seems to work as discussed.

**Comment by pbek** [comment]
Great, thank you for testing! 😁
