### ISSUE TITLE
Missing support for export of selected several notes into one file.

### ISSUE THREAD

**Issue by mirek967** [pbek/QOwnNotes#2207]
#### Expected behaviour
Select several notes, or select a tag.
Export selected notes into one destination file (pdf, or html)

#### Actual behaviour
Only one note can be exported at a time.
#### Steps to reproduce
always

**Comment by pbek** [comment]
You could script that in a custom action by getting the paths of the selected notes with https://www.qownnotes.org/scripting/methods-and-objects.html#getting-a-list-of-the-paths-of-all-selected-notes and put them through https://pandoc.org/

**Comment by pbek** [comment]
Or generate the html of each selected note with `toMarkdownHtml` (https://www.qownnotes.org/scripting/classes.html#note).

**Comment by pbek** [comment]
If fact I already wrote such a script. 😅  Look for `Export notes as one HTML file` in the script repository.

**Comment by pbek** [comment]
See: #871
