### ISSUE TITLE
Issues with encrypted note

### ISSUE THREAD

**Issue by RaiZiStyle** [pbek/QOwnNotes#2209]
Hello ! 
I have an issue with the encrypted notes. 
I can't edit an encrypted note because the button is gray and I can't click on "Edit an encrypted Note". 

#### Expected behaviour
1. Encryption Note
2. Reboot or what every time it's need. 
3. Edit an encrypted Note

#### Actual behaviour
1. Encryption Note
2. Reboot or what every time it's need. 
3. The "edit encrypted note" is unclickable
#### Steps to reproduce
1. Encryption Note
2. Reboot or what every time it's need. 
#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Can you please explain in more detail and step by step what you did, what happened and what you expected.

Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.

Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting Debug in Options).
