### ISSUE TITLE
Link to ownCloud files

### ISSUE THREAD

**Issue by Mornielome** [pbek/QOwnNotes#221]
I very often link to other files in my ownCloud (usally a PDF). As I am using multiple devices and OS's (Win7/Linux dualboot PC at home, Win10 at work, Linux notebook, Android phone), the files are located in very different paths. The resulting workflow isn't really pleasing, as I have to share every single file I want to link to in ownCloud via URL and copy the URL over to QOwnNotes.
My suggestion is, that this process could be automated a bit, much like when I just want to link to another note.

I am obviously using Markdown for my notes.

**Comment by pbek** [comment]
Are you talking about sharing a file in ownCloud (creating a public link) and placing it into a note?
Do you know if there is a public API by ownCloud to do this?

The other solution still is to drop the file into QOwnNotes directly, but the links created there will not be reachable by the Android client if the developers don't implement that feature...

**Comment by Mornielome** [comment]
> Are you talking about sharing a file in ownCloud (creating a public link) and placing it into a note?
Yes. Selecting files in my ownCloud directory works, but the links created aren't even reachable by machines with a different folder structure. For example the following link won't be reachable from my notebook, because the path to the ownCloud directory is different.
`For more information have a look at the [manual](file:///C:/Users/Lukas/owncloud/ownCloudUserManual.pdf).`
To deal with this I am generating public links by hand and insert those here.
I just had a quick look into the ownCloud developer manual and found, that there actually is an [API to create new shares](https://doc.owncloud.org/server/9.0/developer_manual/core/ocs-share-api.html).

**Comment by pbek** [comment]
I will take a look at the API, thanks for looking.

You should be able to link to files relatively to your note folder, like it is done for images: `![nature-h-c-768-1024-1](file://media/29931179.jpg)`
The images are placed in the `media` folder in your note folder. Does that work for you?

**Comment by Mornielome** [comment]
I just tried on my Win7 machine.

> [manual](file://../ownCloudUserManual.pdf)
> [manual](../ownCloudUserManual.pdf)

Both lines didn't work. This would certainly be a good workaround!

**Comment by pbek** [comment]
The first one already works in the preview, does it also work for you?
I would have to create a handler to make it clickable in the editor as well...

**Comment by pbek** [comment]
I'm already working on it, but it's not easy, since the first link isn't a valid URL either... I have to change a lot of stuff...

**Comment by Mornielome** [comment]
> The first one already works in the preview, does it also work for you?

No, it does not work for me.

**Comment by pbek** [comment]
That's strange. For me `[manual](file://../ownCloudUserManual.pdf)` works in the markdown preview (not in the textedit) under Windows 8.1.

**Comment by pbek** [comment]
I had to rewrite quite some things to make everything work again, I hope nothing is missing...
I've successfully tested these links und Linux, OS X and Windows 8.1:

```markdown
- [manual](file://../ownCloudUserManual.pdf)
- <file://../ownCloudUserManual.pdf>
- <note://QOwnNotes_Todo>
- [Alarmtest2](task://6aa6d1da-5975-439b-9fe9-29c0d0b70546)
- ![nature-h-c-768-1024-7](file://media/1352895271.jpg)
```

from the changelog for v16.06.11:
- relative file urls like `[manual](file://../ownCloudUserManual.pdf)` and 
  `<file://../ownCloudUserManual.pdf>` now work in the note text edit and the
   note preview

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?
