### ISSUE TITLE
Feature Request: Possibilty to pin specific notes

### ISSUE THREAD

**Issue by Saratxe** [pbek/QOwnNotes#2211]
At the moment notes will ordered by last edit. I wish to pin specific notes, so I can find them always on top of the list, even if I made several new notes.

**Comment by pbek** [comment]
The only way to do something like that would for example be when you add a tag to those notes (e.g. with a script like `Favorite note` in the script repository if you want to assign a shortcut to this action) and few all notes with that tag.

**Comment by pbek** [comment]
Like #351
