### ISSUE TITLE
Natural alphabetical ordering of note subfolders panel

### ISSUE THREAD

**Issue by szotsaki** [pbek/QOwnNotes#2212]
When you turn on alphabetical ordering of the note subfolders panel it presumably uses some kind of MSD radix sorting and ends up having the numbers following each other in non-natural ordering:

![image](https://user-images.githubusercontent.com/4254450/130310755-0f99d418-7532-4183-ad49-d07d36bf019f.png)

It would be nice to have the list ordered in a natural way (0, 1, 2, ..., 10, 20, 30, ..., 100).

Possibly it's viable to achieve with QCollator ([courtesy of SO](https://stackoverflow.com/a/36018397/4620544)):

```c++
QCollator collator;
collator.setNumericMode(true);
std::sort(entryList.begin(), entryList.end(), collator);
```

**Comment by pbek** [comment]
It's not that easy. Currently the notes are sorted by Sqlite and then (if sort alphabetically) by the QTreeWidget they are in (in `MainWindow::loadNoteDirectoryList()`). So https://doc.qt.io/qt-5/qtreewidget.html#sortItems would need to support that.

**Comment by szotsaki** [comment]
Hmm, I see. I found a [Qt ticket](https://bugreports.qt.io/browse/QTBUG-3316) about natural sort but it was closed without a fix.

Another alternative would be to [bind SQLite's collation creation](http://wiki.ozanh.com/doku.php?id=python:database:sqlite:how_to_natural_sort) to QCollator but unfortunately because of the strange nature of SQLite library in Qt [it doesn't always work](https://www.mimec.org/blog/qt-sqlite-and-locale-aware-collation).
