### ISSUE TITLE
License: GPLv2 vs. GPLv2+ (or later)

### ISSUE THREAD

**Issue by danfe** [pbek/QOwnNotes#2213]
Per `debian/copyright` it is the latter GPLv2 or later, but several source files, e.g. `mainwindow.cpp` say just _version 2 of the License._ (full stop).  So which one it is?

There are also other GPL versions' code there, I haven't looked closer, but it might affect which license the final linked program should actually conform to:
```shell
$ grep -R 'version 3 of the' qownnotes-21.8.8 | wc -l
      21
```

**Comment by pbek** [comment]
> Per debian/copyright it is GPLv2 or later, but several source files, e.g. mainwindow.cpp say just version 2 of the License. (full stop). So which one it is?

Thank you, I made that more clear in https://github.com/pbek/QOwnNotes/commit/8c865227ec231bfe42d32faabd0b7870d2342fc2. But I wouldn't care using GPLv2+ or GPLv3.

> There are also other GPL versions' code there, I haven't looked closer, but it might affect which license the final linked program should actually conform to.

I'm not really sure if you can use GPLv3 libraries in a GPLv2 application. https://gplv3.fsf.org/wiki/index.php/Compatible_licenses really told me in which direction I can use code or not.
