### ISSUE TITLE
License: GPLv2 vs. GPLv2+ (or later)

### ISSUE THREAD

**Issue by danfe** [pbek/QOwnNotes#2214]
Per `debian/copyright` it is GPLv2 or later, but several source files, e.g. `mainwindow.cpp` say just _version 2 of the License._ (full stop).  So which one it is?

There are also other GPL versions' code there, I haven't looked closer, but it might affect which license the final linked program should actually conform to:
```shell
$ grep -R 'version 3 of the' qownnotes-21.8.8 | wc -l
      21
```

**Comment by pbek** [comment]
Is this a duplicate of #2213?

**Comment by danfe** [comment]
Oh, something had probably done wrong due to my poor internet connection, having to use the proxy, etc.  Terribly sorry about this. :-(

**Comment by pbek** [comment]
No worries. 😁
