### ISSUE TITLE
Import web page

### ISSUE THREAD

**Issue by jjisnow** [pbek/QOwnNotes#2215]
Although this is a larger feature request, it would be nice to have the ability to import a webpage directly into a viewable version into QownNotes. I have an evernote account which does this nicely and provides a graphical version of the website I've clipped, but it mangles the presentation horribly upon exporting to .enex format and importing it into qownnotes.

**Comment by pbek** [comment]
The https://github.com/qownnotes/web-companion browser extension can do that... And you can even script how the content of the webpage should be inserted into QOwnNotes.

Or are you talking about something different?

**Comment by jjisnow** [comment]
I'm not sure how good the translation into markdown is. I was hoping along
the way to get a full html widget in the app to minimise the post
processing required after web clipping. I'll give it a go though

**Comment by pbek** [comment]
The QTextBrowser used for the preview in QOwnNotes is no fully-fledged Web Browser, it only can handle a sub-set of HTML.
You maybe could write a script with https://www.qownnotes.org/scripting/hooks.html#websocketrawdatahook that generates a PDF out of the HTML (https://stackoverflow.com/questions/44177555/how-to-convert-html-to-pdf-using-pandoc) and then insert the PDF as attachment (I'd need to write a scripting command for that).

**Comment by pbek** [comment]
> and then insert the PDF as attachment (I'd need to write a scripting command for that).

I just did that, in case you need it...

## 21.8.9
- there now is a new scripting function `script.insertAttachmentFile()` to insert
  an attachment file into the "attachments" folder (for [#2215](https://github.com/pbek/QOwnNotes/issues/2215))
    - for more information please take a look at the [scripting documentation](https://www.qownnotes.org/scripting/methods-and-objects.html#inserting-an-attachment-file-into-the-attachmentn-folder)
