### ISSUE TITLE
Feature idea: support for Todo.txt format

### ISSUE THREAD

**Issue by marcoXbresciani** [pbek/QOwnNotes#2218]
Hello, I'm writing here a proposal/idea for a possibly interesting feature.
Why not adding support for Todo.txt file format?
This http://todotxt.org/ is the main reference.
Since it's a plain text file, with a structured/defined layout, and a lot of libraries are already supporting it, it might not be difficult to add it.

Considering the current Todo possibilities of QOwnNotes, a starting point could be the simple import of such file, to convert/manage them with CalDav (whether possible).
  Or, instead of the import, the export of the calendar/to-do activities in Todo.txt format.

A possible full-fledged solution would be to create a "special" note that, instead of Markdown, would use Todo.txt format, maybe even with a nicer preview that could highlight the different components of each line/entry of the file.

**Comment by pbek** [comment]
I think there were similar requests in https://github.com/pbek/QOwnNotes/issues/1001 and https://github.com/pbek/QOwnNotes/issues/394.

As intriguing this may sound...

What would be the advantage of importing and exporting between caldav and todo.txt? (there maybe already exist solutions for that.) I thought the beauty of todo.txt is that you manage everything in a text file and there is already a solution for that, it's todo.txt. 😓 

Beside, the todo.txt text format has nothing to do with markdown, it would be a huge a mount of work to integrate syntax highlighting for it and very out of scope...

If I'd use todo.txt I maybe just would edit the text file with QON and let todo.txt do the rest (maybe via a script in QON).

**Comment by pbek** [comment]
If I want a reference to a todo list item in a note, I insert a link to the todo list item (the todo list dialog can do that)... But other than that, I like caldav, because it integrates into calendars and is widely understood by all kind of software (that can remind me of todo list items).

**Comment by marcoXbresciani** [comment]
Yep, right 
It's been a while I'm struggling to better learn and use todo.txt, and now that my QON is pumped up and almost perfectly configured, I was wondering how it would be to introduce that format here.
Thanks.

**Comment by pbek** [comment]
I mainly use simple checkbox lists in markdown and use linked caldav entries if I want a reminder too.
