### ISSUE TITLE
Export to PDF crashes QOwnNotes

### ISSUE THREAD

**Issue by geckolinux** [pbek/QOwnNotes#222]
Hi again, sorry for another bug report. :) Now that I got QOwnNotes working, my next step was to test the PDF export functionality, which is important for me. I tried the `Note -> Export Note as PDF (markdown)` option, but it crashes QOwnNote every time and generates an invalid PDF. From a terminal this is what I'm seeing:

``````````````````````````
QOwnNotes 
QSqlQuery::prepare: database not open
countAll :  QSqlError("", "Driver not loaded", "Driver not loaded")
QSqlQuery::prepare: database not open
store :  QSqlError("", "Driver not loaded", "Driver not loaded")

(QOwnNotes:22863): Gtk-CRITICAL **: gtk_file_chooser_default_set_current_name: assertion 'impl->action == GTK_FILE_CHOOSER_ACTION_SAVE || impl->action == GTK_FILE_CHOOSER_ACTION_CREATE_FOLDER' failed
Warning: QObject::connect: invalid null parameter ((null):0, (null))
Segmentation fault (core dumped)
``````````````````````````

Could this be another missing openSUSE dependency? Thanks for the help!

**Comment by pbek** [comment]
Are the packages from #220 installed? Especially the printsupport...

**Comment by geckolinux** [comment]
Yes, I do, but it could indeed be another missing dependency. Here's all the `libQt5` packages I have installed:

``````````````
:~> sudo zypper se -i libQt5
Loading repository data...
Reading installed packages...

S | Name                | Summary                    | Type   
--+---------------------+----------------------------+--------
i | libQt5Core5         | Qt 5 Core Library          | package
i | libQt5DBus5         | Qt 5 DBus Library          | package
i | libQt5Declarative5  | Qt 5 Quick1 Library        | package
i | libQt5Gui5          | Qt 5 GUI related libraries | package
i | libQt5Network5      | Qt 5 Network Library       | package
i | libQt5OpenGL5       | Qt 5 OpenGL Library        | package
i | libQt5PrintSupport5 | Qt 5 Print Support Library | package
i | libQt5Script5       | Qt 5 QtScript Library      | package
i | libQt5Sql5          | Qt 5 SQL related libraries | package
i | libQt5Sql5-sqlite   | Qt 5 sqlite plugin         | package
i | libQt5Svg5          | Qt 5 SVG Library           | package
i | libQt5Test5         | Qt 5 Test Library          | package
i | libQt5Widgets5      | Qt 5 Widgets Library       | package
i | libQt5X11Extras5    | Qt 5 X11 Extras Addon      | package
i | libQt5Xml5          | Qt 5 Xml Library           | package
i | libQt5XmlPatterns5  | Qt 5 XmlPatterns Library   | package
`````````````````````

**Comment by pbek** [comment]
Are there any soft dependencies for `libQt5PrintSupport5`?

**Comment by geckolinux** [comment]
No, it looks like there are no soft deps. I'll try it later on a Leap system I have to see if it acts differently.

**Comment by pbek** [comment]
`libQt5PrintSupport5` does the PDF exporting...
btw. what shows the log dialog (window menu)?

**Comment by geckolinux** [comment]
I enabled all the log categories, but when I use the Export to PDF option it only shows: `[15:32:37] [warning] QObject::connect: invalid null parameter` in the log. The print settings dialog does appear, but after that it crashes and I lose the log window.

**Comment by pbek** [comment]
I wonder what happens if you build QOwnNotes yourself... 
Care for a little test?
<http://www.qownnotes.org/installation#building>

**Comment by geckolinux** [comment]
Sure, I'll give it a try in a VM a bit later today.

**Comment by geckolinux** [comment]
Hmm, I got up to the `qmake` step. What should I do now?

```````````````
qmake-qt5
Project MESSAGE: Currently in RELEASE mode.
Project ERROR: Unknown module(s) in QT: svg qml
`````````````

**Comment by pbek** [comment]
You need packages, like `libqt5-qtbase-devel libqt5-qtdeclarative-devel libQt5Svg-devel`.
Here is the spec file I use for openSUSE:
<https://github.com/pbek/QOwnNotes/blob/develop/obs/qownnotes.spec>

Maybe you also need to set a `QTDIR` (and maybe also `PATH`), like here:
<https://github.com/pbek/QOwnNotes/blob/develop/.travis.yml>

**Comment by pbek** [comment]
I now installed GeckoLinux Cinnamon ROLLING and STATIC.
I used QOwnNotes for Tumbleweed for ROLLING and and Leap for STATIC.
Tagging, PDF-Exporting and the "one instance only" feature worked flawlessly.
Can you please try to install the latest version 16.06.10.1 of QOwnNotes (I added some more libraries for  opeSUSE).

**Comment by geckolinux** [comment]
Good work! The 16.06.10.1 update fixes the PDF export bug. Thanks!
