### ISSUE TITLE
Business organiser for translators

### ISSUE THREAD

**Issue by ghost** [pbek/QOwnNotes#2220]
#### Expected behaviour

As a translator I would professionally benefit from a way to import emails in text format into QON and organise their significant parts into several searchable fields with features like:

- Name of outsourcer / agency
- Job Number
- CAT tool or offline Format 
- if CAT tool, which, link, username, password
- if offline Format, which offline program will handle it
- language pair (e.g. EN-DE)
- Deadline
- Payables
- Instructions
- progress: open, in process, completed 

 

#### Actual behaviour

Did not figure out such a way yet

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by Fabijenna** [comment]
Did you mention earlier that importing mails into QON would be also possible? 
I handle 20-30 mails and updates on them on one day so, that would save time.

**Comment by pbek** [comment]
You can "import" almost everything with the help of the scripting engine... see https://github.com/pbek/QOwnNotes/issues/2220#issuecomment-906174793
