### ISSUE TITLE
[I] App crashed when importing a large .enex file

### ISSUE THREAD

**Issue by zzfnohell** [pbek/QOwnNotes#2221]
#### Expected behaviour

Import notes from Evernote

#### Actual behaviour

App crashed

#### Steps to reproduce

1. Click menu Note/Import/Import notes from Evernote
2. Select a large .enex file(949 MB) in "Evernote Import" dialog
3. Click the "Import Notes" button
3.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
eventvwr.msc entry:

日志名称:          Application
来源:            Application Error
日期:            2021/8/27 22:19:41
事件 ID:         1000
任务类别:          (100)
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           Jupiter
描述:
错误应用程序名称: QOwnNotes.exe，版本: 0.0.0.0，时间戳: 0x6122ace4
错误模块名称: libstdc++-6.dll，版本: 0.0.0.0，时间戳: 0x00000000
异常代码: 0x40000015
错误偏移量: 0x000000000001fce6
错误进程 ID: 0x43d0
错误应用程序启动时间: 0x01d79b4e77452c15
错误应用程序路径: D:\Applications\QOwnNotes\QOwnNotes.exe
错误模块路径: D:\Applications\QOwnNotes\libstdc++-6.dll
报告 ID: 41c900ec-4c99-4602-9f94-e452b50d3c93
错误程序包全名: 
错误程序包相对应用程序 ID: 
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-08-27T14:19:41.3741383Z" />
    <EventRecordID>455342</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Jupiter</Computer>
    <Security />
  </System>
  <EventData>
    <Data>QOwnNotes.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>6122ace4</Data>
    <Data>libstdc++-6.dll</Data>
    <Data>0.0.0.0</Data>
    <Data>00000000</Data>
    <Data>40000015</Data>
    <Data>000000000001fce6</Data>
    <Data>43d0</Data>
    <Data>01d79b4e77452c15</Data>
    <Data>D:\Applications\QOwnNotes\QOwnNotes.exe</Data>
    <Data>D:\Applications\QOwnNotes\libstdc++-6.dll</Data>
    <Data>41c900ec-4c99-4602-9f94-e452b50d3c93</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `周五 8月 27 22:34:54 2021`
**Version**: `21.8.10`
**Build date**: `Aug 22 2021`
**Build number**: `874`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\zzfno\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `D:\Applications\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `zh_CN`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `1528`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\zzfno\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `2`

### Note folder `default`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `52`
**localPath**: `E:\ProgramData\QOwnNotes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: `Program`
**database file**: `E:\ProgramData\QOwnNotes\notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**EvernoteImport/AttachmentImportCheckBoxChecked** (QString): `true`
**EvernoteImport/ImageImportCheckBoxChecked** (QString): `true`
**EvernoteImport/MetaDataUnCheckedList** (QStringList): `, `
**EvernoteImportDialog/geometry** (QByteArray): `<binary data>`
**FileDialog/LastPath** (QString): `E:/OneDrive/repos/backup/Evernote/Notebooks`
**FileDialog/LastPath-Evernote Import** (QString): `E:/OneDrive/repos/backup/Evernote/Notebooks`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-08-27T22:20:15.081`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `SimSun,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `SimSun,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/issue-dialog-new-issue** (int): `16384`
**MessageBoxOverride/remove-folders** (int): `16384`
**MessageBoxOverride/remove-notes** (int): `16384`
**MessageBoxOverride/restore-note** (int): `16384`
**NoteFolder-2/NoteTabNameList** (QStringList): *empty*
**NoteFolder-2/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-2/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteHistory-2** (QVariantList): `<variant list with 13 item(s)>`
**NoteHistoryCurrentIndex-2** (int): `12`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**StoredAttachmentsDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `2`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (int): `14`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `E:/ProgramData/QOwnNotes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `initial`
**recentNoteFolders** (QStringList): `E:/OneDrive/Documents/org/notes`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**ANDROID_EMULATOR_HOME**: `D:\msys64\home\admin\.android\`
**ANDROID_HOME**: `D:\Scoop\apps\android-sdk\current`
**APPDATA**: `C:\Users\zzfno\AppData\Roaming`
**CARGO_HOME**: `D:\Scoop\persist\rustup\.cargo`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPOSER_HOME**: `D:\Scoop\persist\composer\home`
**COMPUTERNAME**: `JUPITER`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**COQBIN**: `bin`
**DOTNET_ROOT**: `D:\Scoop\apps\dotnet-sdk\current`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**GEM_HOME**: `D:\Scoop\apps\ruby\current\gems`
**GEM_PATH**: `D:\Scoop\apps\ruby\current\gems`
**GIT_INSTALL_ROOT**: `D:\Scoop\apps\git\current`
**GOROOT**: `D:\Scoop\apps\go\current`
**HOME**: `D:\msys64\home\zzfno`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\zzfno`
**LOCALAPPDATA**: `C:\Users\zzfno\AppData\Local`
**LOGONSERVER**: `\\JUPITER`
**NUMBER_OF_PROCESSORS**: `8`
**NVM_HOME**: `D:\Scoop\apps\nvm\current`
**NVM_SYMLINK**: `D:\Scoop\persist\nvm\nodejs\nodejs`
**OneDrive**: `E:\OneDrive`
**OneDriveConsumer**: `E:\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Program Files\Wolfram Research\WolframScript\;C:\Program Files\Polyspace\R2021a\runtime\win64;C:\Program Files\Polyspace\R2021a\bin;C:\Program Files\Polyspace\R2021a\polyspace\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files\PowerShell\7\;D:\Scoop\apps\postgresql\current\bin;D:\Scoop\apps\maven\current\bin;C:\Users\zzfno\go\bin;D:\Scoop\apps\composer\current\home\vendor\bin;D:\Scoop\apps\pyenv\current\pyenv-win\shims;D:\Scoop\apps\tortoisesvn\current\bin;D:\Scoop\apps\rustup\current\.cargo\bin;D:\Scoop\apps\python\current\Scripts;D:\Scoop\apps\python\current;D:\Scoop\apps\ruby\current\bin;D:\Scoop\apps\ruby\current\gems\bin;D:\Scoop\apps\adoptopenjdk-hotspot\current\bin;D:\Scoop\shims;D:\Scoop\apps\Ghostscript\current\lib;D:\Scoop\apps\perl\current\perl\site\bin;D:\Scoop\apps\perl\current\perl\bin;D:\Scoop\apps\perl\current\c\bin;D:\Scoop\persist\nvm\nodejs\nodejs;C:\Users\zzfno\AppData\Local\Microsoft\WindowsApps;C:\Users\zzfno\AppData\Local\BypassRuntm;E:\SDK\nodejs\npm;C:\Users\zzfno\.dotnet\tools;C:\texlive\2021\bin\win32;C:\Users\zzfno\.dotnet\tools;C:\Users\zzfno\.dotnet\tools`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PGDATA**: `D:\Scoop\apps\postgresql\current\data`
**POWERSHELL_DISTRIBUTION_CHANNEL**: `MSI:Windows 10 Pro`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 60 Stepping 3, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `3c03`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PROGUARD_HOME**: `D:\Scoop\apps\android-sdk\current\tools\proguard`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**PYENV**: `D:\Scoop\apps\pyenv\current\pyenv-win`
**PYTHONUTF8**: `1`
**RUSTUP_HOME**: `D:\Scoop\persist\rustup\.rustup`
**SBCL_HOME**: `D:\Scoop\apps\sbcl\current`
**SCALA_HOME**: `D:\Scoop\apps\scala\current`
**SCOOP**: `D:\Scoop`
**SCOOP_GLOBAL**: `D:\GlobalScoopApps`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\zzfno\AppData\Local\Temp`
**TMP**: `C:\Users\zzfno\AppData\Local\Temp`
**USERDOMAIN**: `JUPITER`
**USERDOMAIN_ROAMINGPROFILE**: `JUPITER`
**USERNAME**: `zzfno`
**USERPROFILE**: `C:\Users\zzfno`
**windir**: `C:\WINDOWS`
**_NT_SYMBOL_PATH**: `srv*D:\symbols*https://msdl.microsoft.com/download/symbols`
</details>

**Comment by pbek** [comment]
If you are still with QOwnNotes, since #2711 you could now try to import large enex files (and please report how it went). 😉
