### ISSUE TITLE
Tags, keywords and note metadata.

### ISSUE THREAD

**Issue by geomule** [pbek/QOwnNotes#2222]
Hi folks,

at the bottom of [this page](https://github.com/pbek/QOwnNotes/issues/118) there is a broken link that is suppose to copy tags in the note itself i.e. so that the same tag is in the SQL database and in the note itself.

I'm trying to implement a Zettelkasten workflow in QOwnnotes and keywords (although tags and keywords are not the same thing, you can use the tag feature in QON as a surrogate of a keyword which is a fundamental pillar of Zettelkasten) a fundamental piece of the puzzle. I'm having to enter tags manually in the note as well as in the SQL database at the moment. Not very effective ...

Suggestions please?

Also note that its interesting that QOwnnotes has chosen the route of tags. Tags, from what I understand are mostly used to categorise [see here](https://theblogpress.com/what-is-the-difference-between-tags-and-keywords/); keywords are used to optimise search. In fact, when you save a bookmark in Firefox, you can add both tags and keywords. Is this something that could be considered for QON? I'm a super fan of Nextcloud so I understand the need to avoid breaking compatibility with Own/Nextcloud.

**Comment by pbek** [comment]
The file is here: https://github.com/pbek/QOwnNotes/blob/develop/docs/scripting/examples/use-tag-names-in-filename.qml

**Comment by pbek** [comment]
If you want to keep your tags inside the note files there is a scripting api for that and several scripts in the script repository are using it (search for `tag` in the script repository). This way you could also use "QOwnNotes tags" with the QOwnNotes web companion browser extension.

**Comment by pbek** [comment]
Of course you can always implement your own tagging with https://www.qownnotes.org/scripting/hooks.html#notetaggingbyobjecthook or https://www.qownnotes.org/scripting/hooks.html#notetagginghook.
