### ISSUE TITLE
Feature Request: Add modify navigation support

### ISSUE THREAD

**Issue by wsrf16** [pbek/QOwnNotes#2224]
![v2-423516c01f9cd9b5a06fc0b5c0deffb7_b](https://user-images.githubusercontent.com/11867768/132112281-533a05b6-06dd-4e4f-81a9-3b0c3045f99c.gif)

**Comment by pbek** [comment]
I completely misunderstood this feature request (for what I did now in #2225), because it had no description.

**Comment by pbek** [comment]
Are you talking about the todo list dialog or the navigation panel? The first I now did in #2225, the 2nd would be far too risky if you imply that actual note text should be moved.
