### ISSUE TITLE
Allow moving of Todo items in todo list

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#2225]
## 21.9.1
- you can now move a todo item into another todo item in the todo list dialog

**Comment by pbek** [comment]
@wsrf16, if you were talking about this in #2224, then this is now in the current release.

**Comment by wsrf16** [comment]
I am talking about navigation panel. Moving a navigation item into another one in navigation panel.

**Comment by pbek** [comment]
> Moving a navigation item into another one in navigation panel.

To achieve what?

**Comment by wsrf16** [comment]
To move paragraph by dragging navigation item.

**Comment by pbek** [comment]
Ah, ok. No, I don't think this will happen in the foreseeable future.
