### ISSUE TITLE
[I] Moving or Copying Notes not possible

### ISSUE THREAD

**Issue by hannibal72** [pbek/QOwnNotes#2226]
#### Expected behaviour

1. Right Click on a note to move or copy it to another folder or subfolder
2. Left-Mouse-Click for moving notes around-

#### Actual behaviour

1. those options appear in the right-click-menu but the sub-menues behind the right-arrow don't appear
2. Left-click just marks the notes.

#### Steps to reproduce

select a note
right click to open context menu

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[12:37:51] [warning] OpenType support missing for "MS Shell Dlg 2", script 12
[12:37:51] [warning] OpenType support missing for "Arial", script 12
[12:37:51] [warning] OpenType support missing for "MS UI Gothic", script 12
[12:37:51] [warning] OpenType support missing for "SimSun", script 12
[12:37:51] [warning] OpenType support missing for "MS Shell Dlg 2", script 11
[12:37:51] [warning] OpenType support missing for "Arial", script 11
[12:37:51] [warning] OpenType support missing for "MS UI Gothic", script 11
[12:37:51] [warning] OpenType support missing for "SimSun", script 11
[12:37:51] [warning] OpenType support missing for "MS Shell Dlg 2", script 32
[12:37:51] [warning] OpenType support missing for "Arial", script 32
[12:37:51] [warning] OpenType support missing for "MS UI Gothic", script 32
[12:37:51] [warning] OpenType support missing for "SimSun", script 32
[12:37:51] [warning] OpenType support missing for "MS Shell Dlg 2", script 13
[12:37:51] [warning] OpenType support missing for "Arial", script 13
[12:37:51] [warning] OpenType support missing for "MS UI Gothic", script 13
[12:37:51] [warning] OpenType support missing for "SimSun", script 13
[12:37:51] [warning] OpenType support missing for "MS Shell Dlg 2", script 20
[12:37:51] [warning] OpenType support missing for "Arial", script 20
[12:37:51] [warning] OpenType support missing for "MS UI Gothic", script 20
[12:37:51] [warning] OpenType support missing for "SimSun", script 20
[12:37:53] [warning] OpenType support missing for "Segoe UI", script 20
[12:37:53] [warning] OpenType support missing for "MS Shell Dlg 2", script 20
[12:37:53] [warning] OpenType support missing for "Arial", script 20
[12:37:53] [warning] OpenType support missing for "MS UI Gothic", script 20
[12:37:53] [warning] OpenType support missing for "SimSun", script 20
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `So Sep 5 12:39:50 2021`
**Version**: `21.9.1`
**Build date**: `Sep  5 2021`
**Build number**: `878`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2004`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\Holge\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `D:\PROGRAMME\QOwnNotes Programm`, `\QOwnNotes.exe`, `--after-update`, `C:\Users\Holge\AppData\Local\Temp\QOwnNotes-iTgVlZ-updater.bat`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `213`
**Calendar items**: `308`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `http://192.168.178.51/nextcloud`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `20.0.6.1`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\Holge\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Standard`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `D:\NeXtClouD 2 - DatenOrdner\Notes`
**remotePath**: *empty*
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `D:\NeXtClouD 2 - DatenOrdner\Notes\notes.sqlite`

### Note folder `QOwn Ordner lokal`

**id**: `2`
**isCurrent**: `no`
**activeTagId**: `-2`
**localPath**: `D:\Nextcloud Ordner\QOwnNotes Notizen`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `D:\Nextcloud Ordner\QOwnNotes Notizen\notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `http://192.168.178.51/nextcloud`
**username**: `Horos83NC`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/editorWidthMode** (int): `3`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (int): `21`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-4d50131d-fb68-4fc7-b93c-5d0585f184e0`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `P:/0-Inbox`
**FileDialog/LastPath-InsertImage** (QString): `P:/0-Inbox`
**FileDialog/LastPath-NotePDFExport** (QString): `C:/Users/Holge/Desktop`
**ImageDialog/disableCopying** (QString): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-09-05T12:29:42.706`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Meine Server Installationen/piHole, Meine Rezepte, Meine Server Installationen/Meine Server Installationen ab 2018, Auto 2019, Mein SmartHome`
**MainWindow/noteTextEdit.code.font** (QString): `Courier,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Linux Biolinum G,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Fixedsys,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Miriam Mono CLM,10,-1,5,75,0,0,0,0,0,Bold`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `false`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `false`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/move-notes** (int): `16384`
**MessageBoxOverride/remove-notes** (int): `16384`
**MessageBoxOverride/update-and-restart** (int): `16384`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): `piHole in Proxmox Container - Mai 2021`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `Meine Server Installationen`
**NoteFolder-1/allowDifferentNoteFileName** (QString): `true`
**NoteFolder-2/allowDifferentNoteFileName** (QString): `true`
**NoteHistory-1** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 1 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `199`
**NoteHistoryCurrentIndex-2** (int): `0`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExportOrientation** (int): `0`
**Printer/NotePDFExportPageSize** (int): `4`
**Printer/NotePrinting** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `8`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (int): `2`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Einkauf Rewe etc`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `true`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `f21ddd86-41ff-4b10-9849-8087586c1b62`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `false`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `true`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `true`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**interfaceStyle** (QString): `Fusion`
**internalIconTheme** (QString): `true`
**itemHeight** (int): `15`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `true`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `true`
**noteSubfoldersPanelShowNotesRecursively** (QString): `true`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `D:/NeXtClouD 2 - DatenOrdner/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unbekannter Fehler`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `20.0.6.1`
**previousWorkspace** (QString): `initial`
**recentNoteFolders** (QStringList): `D:/Nextcloud Ordner/Notes, D:/NC Notes Experiment, D:/Nextcloud Ordner/QOwnNotes Notizen`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `false`
**savedSearches/noteFolder-1** (QStringList): `Unifi in Proxmox LXC ab 28-08-2021, Note 2021-08-12T14.40.18, Proxmox von 25oer auf 1TB umgezogen, iobroker - Adapter Wunschliste, LOGbuch - Notfallbroker, ZIGBEE Umzug - die abschließenden Schritte und LOGbuch, Zigbee Experimente, iobroker UND Macrodroid UND HTTP Shortcuts verbinden, Jarvis Styles, Jarvis Batteridatenpunkte, Grafana Container mit InfluxDB, Note 2021-07-16T21.31.37, OpenMediaVault - OMV-2, USV-pi, NAS Wissen, Jarvis Skripting, Portainer Docker, Nextcloud von Synology löschen, LOG - Unifi, piHole in Proxmox Container - Mai 2021, RMatic - RaspberryMatic - Wissen, Raspberry SSH Buttons App, 1 A DS 918 Downgrade Ideensammlung, Syncthing Tips, ioBroker 2- die nächsten Schritte Sammlung, Jarvis Wissenssammlung, Hitze 2021 - Überlegungen, JARVIS - Ideensammlung, apc, ZIGBEE CC 2652P Flash-Anleitung, ZIGBEE - Umzug 03-2021, Kochen - Rezeptesammlung, ioBroker Blockly Brainstorming, Opple Wohnzimmer, AAA Staubsaugerkauf 2021, Lesezeichen - FF - Reste 0, Lesezeichen - FF - Reste 4 - Musik entmüllt, Lesezeichen - FF - Reste 4 - GlancR und Musik, Lesezeichen - FF - Reste 3 - Musik, Lesezeichen - FF - Reste2, Lesezeichen - FF - Reste 1, LOG - Handy Backups, Streaming Tips, VU Uno SE - Vorbereitungen und Konfiguration, VU Uno SE - Vorbereitungen, Listary Tips und Tricks, Firefox - Tipsammlung, Firefox - meine Addons, LOG - Firefox und Browser, Firefox Profile nutzen, Testnotiz, Heizprogramm von CCU zu iobroker umziehen möglich, Heizprogramm von CCU zu iobroker umziehen möglich?, LOG - Fritzbox, LOG - Smarthome allgemein, iobroker2 - Verzeichnis der iQontrol icons usw, piHole Blocklistensammlung, linux Wissen, Notfall ioBroker auf Tinkerboard - Januar 2021, piHole  virtualisiert in Proxmox-VM, Wireguard virtualisiert in Proxmox-VM, iobroker - Fixer -- FAQ und Wissen, VU Paketupdate hakt - Lösung, Proxmox  Logbuch, LOG - RMatic, Tradfri- notwendige Batterien, iobroker2 - Node updaten, iobroker 2 - Backitup Einstellungen - November 2020, LOG - pihole, WIREguard - meine Installations, PIHOLE LOG, iobroker - JSController Upgrade, Aqara 4-Tasten-Switch Wohnzimmer Sommer 2020, glancr  kalender, Kalenderadressen Nextclouds Thunderbird, Kalenderadressen Nextcloud Thunderbird, NAS und Hitze Anpassungen, NOTBETREUUNG - PACkliste, STEUER - LOG und Tips für die Erklärung 2020, Jack Ryan Romane, LOG - iobroker 2 - SKRIPTE et al, NAS MACs usw, GlancR startet nicht, Hitzeplan Wohnzimmer AVR und Fernsehen usw, pihole tips, polar v650 tip, Backup - Fahrplan, LOG - Proxmox, ioBroker  - Wissen, ioBroker 2 - Adapter Installationswellen LOG, Proxmox - gelbe HDD einbinden, Osram zu Hue umziehen, LOG - ioBroker 2, NUCs - meine Hardware, Samsung Tips, ioBroker2 - Konfig, ioBroker2 - VIS Einstellungen, ioB-zu-NUC-Umzug, iobroker2 - Neue VM Neue Glueck, Proxmox - Logbuch`
**savedSearches/noteFolder-2** (QStringList): `fob, tom`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**skipVersion** (QString): `21.3.0`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `true`
**tagsPanelHideNoteCount** (QString): `true`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, `
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Hauptsymbolleiste`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `Formatierungs-Werkzeugleiste`
**toolbar/3/items** (QStringList): `actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `Einfügen-Werkzeugleiste`
**toolbar/4/items** (QStringList): *empty*
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `Verschlüsselung-Werkzeugleiste`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `Fenster-Werkzeugleiste`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `Beenden - Symbolleiste`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (QString): `true`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**webSocketServerService/token** (QString): `<hidden>`
**workspace-f21ddd86-41ff-4b10-9849-8087586c1b62/name** (QString): `Hauptarbeitsbereich`
**workspace-f21ddd86-41ff-4b10-9849-8087586c1b62/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-f21ddd86-41ff-4b10-9849-8087586c1b62/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Vollständig`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, f21ddd86-41ff-4b10-9849-8087586c1b62`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\Holge\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `RAPTOR2K18`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**destination**: `"D:\PROGRAMME\QOwnNotes Programm"`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\Holge`
**JD2_HOME**: `C:\Users\Holge\AppData\Local\JDownloader 2.0`
**LOCALAPPDATA**: `C:\Users\Holge\AppData\Local`
**LOGONSERVER**: `\\RAPTOR2K18`
**NUMBER_OF_PROCESSORS**: `16`
**OneDrive**: `C:\Users\Holge\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Java\jre1.8.0_221\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile64\;C:\Program Files (x86)\Common Files\Acronis\FileProtector\;C:\Program Files (x86)\Common Files\Acronis\FileProtector64\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files (x86)\WinSCP\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Boxcryptor\bin\;C:\Program Files\dotnet\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Paragon Software\LinuxFS for Windows\;C:\Program Files\FileBot\;C:\Users\Holge\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Advanced Renamer;C:\Users\Holge\AppData\Local\Microsoft\WindowsApps`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD`
**PROCESSOR_LEVEL**: `23`
**PROCESSOR_REVISION**: `0802`
**PROG27B48B2C054**: `1`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PROMPT**: `$P$G`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\PowerShell\Modules\`
**PUBLIC**: `C:\Users\Public`
**qownnotesCommand**: `"D:\PROGRAMME\QOwnNotes Programm"\QOwnNotes.exe --after-update C:\Users\Holge\AppData\Local\Temp\QOwnNotes-iTgVlZ-updater.bat `
**SESSIONNAME**: `Console`
**source**: `C:\Users\Holge\AppData\Local\Temp\QOwnNotes-iTgVlZ.zip`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\Holge\AppData\Local\Temp`
**TMP**: `C:\Users\Holge\AppData\Local\Temp`
**unzipCommand**: `C:\Users\Holge\AppData\Local\Temp\QOwnNotes-iTgVlZ-unzip.exe -o C:\Users\Holge\AppData\Local\Temp\QOwnNotes-iTgVlZ.zip -d "D:\PROGRAMME\QOwnNotes Programm"`
**unzipExecutable**: `C:\Users\Holge\AppData\Local\Temp\QOwnNotes-iTgVlZ-unzip.exe`
**USERDOMAIN**: `RAPTOR2K18`
**USERDOMAIN_ROAMINGPROFILE**: `RAPTOR2K18`
**USERNAME**: `Holge`
**USERPROFILE**: `C:\Users\Holge`
**VBOX_MSI_INSTALL_PATH**: `C:\Program Files\Oracle\VirtualBox\`
**windir**: `C:\WINDOWS`
</details>

**Comment by pbek** [comment]
You can do that in the main menu.

**Comment by pbek** [comment]
Can you please make a screenshot, I cannot reproduce your issue. I can see my other sub-folders or note-folders.

**Comment by pbek** [comment]
And do you have the same issue when running QOwnNotes in a new session (see [cli-parameters](https://www.qownnotes.org/getting-started/cli-parameters.html))?

**Comment by pbek** [comment]
Looks like you are talking about the work in progress feature #790, right?
If yes, then best deposit your request there... 😉
