### ISSUE TITLE
[Feature request] todo-list checkbox

### ISSUE THREAD

**Issue by rcaneill** [pbek/QOwnNotes#2228]
Hi, thanks for the developing of QOwnNotes. I had a feature idea (I tried to find if it was already implemented, but it does not seem so).

When a todo task is inserted into a checkbox list item, and when the box is checked, it would be nice if the task would be marked as done at the same time in the caldav.

**Comment by pbek** [comment]
I often thought about this, but unfortunately there many issues with it. There are many ways the note markdown checkbox text can change and there is no way of tracking those changes. Different versions of the note could exist on different computers, all doing something to the todo list item. The todo item could even don't exist any more or the computer doesn't have access to it.

And I'm sure there are even more issues the more I look at it...

**Comment by rcaneill** [comment]
Hum I see, I had not thought of all these problems...

Thanks for your quick answer!
