### ISSUE TITLE
How to filter by tag?

### ISSUE THREAD

**Issue by geckolinux** [pbek/QOwnNotes#223]
Hi, QOwnNotes is extremely thorough and generally very intuitive. Very well done!

The only thing I don't understand is how to filter or search by tags. My intuition would tell me to click on one of my tags, and then it would filter the list of notes that have that tag. However, clicking on a tag does nothing, except for allowing me to rename the tag. Am I missing something?

Thanks for the help! Here's a screenshot too:

![screenshot from 2016-06-21 12-28-38](https://cloud.githubusercontent.com/assets/2692138/16239728/da70cc86-37ab-11e6-9954-243147868358.png)

**Comment by pbek** [comment]
Thank you for your kind words!

Tags: You are describing the way it should work and works for everyone else. :)
So you already tagged some notes, right?
I really have to install Thumbleweed, on Leap I haven't had any of all your troubles...

**Comment by geckolinux** [comment]
Huh, weird! It must be a Qt5 version difference? (I'm currently at Qt 5.6.0).

Yes, the other notes in my screenshot are tagged, but clicking on the tag tree does nothing except allowing to rename the tags.

**Comment by pbek** [comment]
Qt 5.6.0 shouldn't be an issue, I use QOwnNotes with 5.6.0 and also 5.6.1...

**Comment by pbek** [comment]
I now installed GeckoLinux Cinnamon ROLLING and STATIC.
I used QOwnNotes for Tumbleweed for ROLLING and and Leap for STATIC.
Tagging, PDF-Exporting and the "one instance only" feature worked flawlessly.
Can you please try to install the latest version 16.06.10.1 of QOwnNotes (I added some more libraries for  opeSUSE).

**Comment by geckolinux** [comment]
Hi, thanks a lot for the support. The 16.06.10.1 update fixes the PDF export bug, but not the tagging and one instance issues.

**Comment by pbek** [comment]
let's discuss that at #224

**Comment by pbek** [comment]
I will close this issue until there is more information.
