### ISSUE TITLE
[Feature Request] Loginflow for Nextcloud / ownCloud support

### ISSUE THREAD

**Issue by sunjam** [pbek/QOwnNotes#2233]
Currently login requires manually entering account credentials and generating a one-time password.

[Loginflow](https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html) SSO v1 and v2 drastically simplifies this process by allowing a user to authenticate directly against a web browser.  This lowers technical complexity and works nicely for users with two factor authentication.

No worries either way, and thank you so much for this amazing application!

**Comment by pbek** [comment]
Thank you for your concern.

Don't you need an integrated web browser to receive the token?

**Comment by sunjam** [comment]
In my experience the default web browser handles things. Has worked fine on
windows, linux, android afaik.

**Comment by pbek** [comment]
Do you have an example of a non-web app who does this?

> The client should open a webview to <server>/index.php/login/flow. Be sure to set the OCS-APIREQUEST header to true.

You cannot set a header when opening an external web browser.

> The client will register an URL handler to catch urls of the nc protocol. This is required to obtain the credentials in the final stage.

You can only do that with a web worker (means that the client has to be a web application).

**Comment by pbek** [comment]
Ah, login flow v2 could work (https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html#login-flow-v2)...

**Comment by pbek** [comment]
@sunjam, did you find a documentation if / how ownCloud supports login flow v2? I can't find anything.

**Comment by pbek** [comment]
`curl -X POST https://cloud.example.com/index.php/login/v2` doesn't seem to work on ownCloud 10.7 or 10.8 (I just tested). Too bad.

**Comment by pbek** [comment]
## 21.9.3
- You can now create an app password for your Nextcloud account automatically to 
  grant QOwnNotes access to your account by just entering the server url and 
  clicking on `Login to Nextcloud to grant access` in your *Nextcloud / ownCloud settings*
    - then just follow the instructions in your web browser until QOwnNotes can
      fetch your username and app password in the background

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
## 21.9.4
- Now a more descriptive user agent is used for the login flow to generate an
  app password on your Nextcloud server, so you can more easily spot the app
  password created for QOwnNotes

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by sunjam** [comment]
Works perfect.  Thank you.

**Comment by pbek** [comment]
Great, thank you for testing!
