### ISSUE TITLE
Feature request: auto dark/light mode (use system settings)

### ISSUE THREAD

**Issue by bcutter** [pbek/QOwnNotes#2234]
I´d like to QOwnNotes have a "Use system setting" option in Settings / Appearance.

Currently I can activate dark mode which is static. Almost all applications meanwhile adopt to system settings (Windows, iOS, ...), so if system is currently using dark/light mode the application is too.

**Comment by pbek** [comment]
By default QOwnNotes uses the colors the Operating System dictates. That works for example very well under Linux desktop environments, which even provide FreeDesktop Icon support. Unfortunately Windows doesn't support that. So there also is awareness about the Windows dark mode... But there is an open user story about dark mode "support" at https://bugreports.qt.io/browse/QTBUG-72028.

Using the "dark mode" in QOwnNotes includes more than just one decision. You can set the ui, the editor colors, the preview colors and the icons independently from each other... I really don't want to force all those settings on users just because they use the dark mode in Windows.

**Comment by pbek** [comment]
I could of course (just under Windows) check in the Windows Registry if the User has turned on the Windows dark mode and show a dialog to turn on the QON dark mode (with some other settings) when it isn't already activated.

I found something like:

```cpp
    QSettings settings("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize",QSettings::NativeFormat);
    if(settings.value("AppsUseLightTheme")==0){
...
```

**Comment by pbek** [comment]
@bcutter, what shows `HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize` in the Windows Registry Editor for you (in dark mode)?

**Comment by bcutter** [comment]
You´re right, there´re a few things to look at. For me light mode/dark mode only change two settings because those two together make a consistent overall look:
![grafik](https://user-images.githubusercontent.com/13799156/133489632-ef39f927-c25e-4e12-8d1d-cf34ae818c32.png)

BUT: It´s not "just" about an automatic switch to dark mode in QOwnNotes, it´s also about switching to light mode. So more like a full theme mode support. As people start to auto-switch Windows mode (based on sun light by using tools like "Auto Dark Mode" or "PowerToys" (feature is being implemented currently) or probably natively with next major Windows release) so it´s light mode during the day and dark mode in the night it would be _totally awesome_ if QOwnNotes could react on those changes.

1. I like the idea of the dialogue as a first step (big improvement compared to current situation!). `"We see your system is using [light|dark] mode. Would you like QOwnNotes to also switch to [light|dark] mode and restart automatically now?"` Restart should be included with "Yes/OK" button.
2. Second step could be to automatically do the mode change on startup of QOwnNotes. For this it could be useful to add a "automatically switch light/dark mode based on system settings on QOwnNotes startup" option in the settings/appearance section which is turned off by default (so only people wanting to use this feature can activate, no one gets bothered).

> 
> 
> @bcutter, what shows `HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize` in the Windows Registry Editor for you (in dark mode)?

That´s with DARK MODE active:
![grafik](https://user-images.githubusercontent.com/13799156/133489082-7c2c5f2f-9e40-4c04-9004-071303c117c5.png)

That´s with LIGHT MODE active:
![grafik](https://user-images.githubusercontent.com/13799156/133491274-0444349f-32da-4aeb-acb4-227c2c07bb48.png)

**Comment by pbek** [comment]
## 21.9.5
- under Windows 10 the application will now ask you if you want to turn on 
  dark mode if Windows is in dark mode and the application is not
    - the application will now also ask you if you want to turn off dark mode if
      Windows is in light mode and the application has dark mode turned on
    - you can remember those decisions so that the switch will be made
      automatically next time

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by bcutter** [comment]
> 
> 
> There now is a new release, could you please test it and report if it works for you?

First of all: I´m so happy to see you immediately implemented this. Awesome!

What I discovered during intensive testing:

1. QOwnNotes isn´t automatically restarted after switching mode (default dialogue ~ "A restart might be required... [OK]") but only closed. Not sure if technically possible (I believe it is because after performing an update it´s also restarted automatically).
2. The "don´t ask me again" checkbox comes up two times (so for both switching to dark as well as to light mode), which is fine.
3. After checked the "don´t ask me again" checkbox(es) there´s no option in the UI to revert that decision. I´d propose a checkbox in settings e. g. at
![grafik](https://user-images.githubusercontent.com/13799156/133676701-0fcb5bc6-61fa-4822-b7a3-607cc7faf1ff.png)
4. When the "A restart might be required... [OK]" dialogue comes up on first start of QOwnNotes after a system mode change, users might not be aware of the reason for this (maybe they were once but after some time...). If possible this message should state what has changed ("light/dark mode auto-switch").
5. What exactly is changed with dark/light mode switch seems to be pre-defined and not user selectable, which is totally fine for me (I didn´t change the status bar icon to dark mode one before but that´s fine - fully light and fully dark, I think that´s exactly what users would expect, no need to deep dive into specific selection like dark mode, dark mode icons, dark mode status bar icon).
6. Bit of a downside: the system mode is currently being checked on start of QOwnNotes. That´s already a huge improvement, really. But this way the system mode change might be undetected for a long time/at all during the day. Can we therefore use another trigger next to startup, e. g. when reverting QOwnNotes from status bar? 
![grafik](https://user-images.githubusercontent.com/13799156/133677958-c8b56f46-8567-4459-bf81-bb0286630be8.png)
![grafik](https://user-images.githubusercontent.com/13799156/133678051-a1d01d6a-2f13-4d3c-a416-2c69ef63f562.png)
At least for me that´s the way I use QOwnNotes: it´s always running. When I don´t need it I "close" (minimize to status bar area next to date/time in Windows) it and restore it by clicking that icon. I think using such triggers is way more efficient than starting to regular check for the system mode (e. g. every 15 minutes or sth.).

Me personally I´d like to see **1 + 6 (plus maybe 3)** as it improves the auto-switch feature a lot, makes it even more convenient.

**Comment by pbek** [comment]
> QOwnNotes isn´t automatically restarted after switching mode (default dialogue ~ "A restart might be required... [OK]") but only closed. Not sure if technically possible (I believe it is because after performing an update it´s also restarted automatically).

That depends if on your setting if only one app instance is allowed our not. If only one is allowed you need to restart manually because I only can quit QON after I start another instance.

> After checked the "don´t ask me again" checkbox(es) there´s no option in the UI to revert that decision. I´d propose a checkbox in settings e. g. at

You can reset all message boxes in the *General settings*.

> I didn´t change the status bar icon to dark mode one before

Yes, that icon will be changed...

https://github.com/pbek/QOwnNotes/commit/a1796f557e34ef129055ff88e24c1f28c86fcad3#diff-87e282cc259dd3a6abaa2c6a41eac675d96238a156339c2549c6aaaebd90dd27R2343

As I was saying in the beginning. There is not a simple "dark mode" in QON, it's more complex. That's why I had my concerns with this feature request.

> it of a downside: the system mode is currently being checked on start of QOwnNotes. That´s already a huge improvement, really. But this way the system mode change might be undetected for a long time/at all during the day. Can we therefore use another trigger next to startup, e. g. when reverting QOwnNotes from status bar?

What system mode are you talking about? The Windows light mode?
I wouldn't want to be forced to restart QON when I was opening it from the tray. That would be the case if someone used the "Remember the decision" option.

**Comment by pbek** [comment]
But I will mention `Keep in mind that if you apply this mode change automatically you need to restart the application every time after you start the application and the Windows mode was changed!` in the message boxes...

## 21.9.6
- now the required restart will be mentioned for the automatic mode switch under
  Windows 10

**Comment by bcutter** [comment]
> 
> 
> > QOwnNotes isn´t automatically restarted after switching mode (default dialogue ~ "A restart might be required... [OK]") but only closed. Not sure if technically possible (I believe it is because after performing an update it´s also restarted automatically).
> 
> That depends if on your setting if only one app instance is allowed our not. If only one is allowed you need to restart manually because I only can quit QON after I start another instance.

Indeed, only one app instance is allowed. So no automatic restart? :-( Not into details but... for update situations this works flawlessly - _with_ "only one app instance allowed" setting...

> > it of a downside: the system mode is currently being checked on start of QOwnNotes. That´s already a huge improvement, really. But this way the system mode change might be undetected for a long time/at all during the day. Can we therefore use another trigger next to startup, e. g. when reverting QOwnNotes from status bar?
> 
> What system mode are you talking about? The Windows light mode?
> I wouldn't want to be forced to restart QON when I was opening it from the tray. That would be the case if someone used the "Remember the decision" option.

System mode = current light/dark mode (of Windows), yes.
Well either you need to 1) see "well my system has changed to light/dark mode, why QON hasn´t already?" and 2) manually restart QON to have it adapt to the system setting - or you simply take the quite intuitive chance when reverting it from the tray. I´d strongly vote for that trigger :-D Would you need another issue to track this feature request?

**Comment by pbek** [comment]
> Indeed, only one app instance is allowed. So no automatic restart? :-( Not into details but... for update situations this works flawlessly - with "only one app instance allowed" setting...

different story, the updater writes a batch file to disk that does the updating and starts QON again... it was a huge undertaking and I don't want to invent that for every operating system reliably for those restarts...

**Comment by pbek** [comment]
> Would you need another issue to track this feature request?

Nah, I very much dislike that automatism that requires a restart. In fact I almost dislike the whole feature request because of the restart it needs...

**Comment by pbek** [comment]
The dialog that the app needs a restart, without any further explanation, is already too much confusion.

**Comment by bcutter** [comment]
> 
> 
> > Would you need another issue to track this feature request?
> 
> Nah, I very much dislike that automatism that requires a restart. In fact I almost dislike the whole feature request because of the restart it needs...

I see. If that restart wouldn´t be necessary the whole thing would be a lot smoother indeed. But I guess that´s a Qt thing. I´m still confident using a second trigger for detecting the system mode (light/dark) change would actually improve the usage a lot.

> 
> 
> The dialog that the app needs a restart, without any further explanation, is already too much confusion.

You´re right, that´s my no 4 in https://github.com/pbek/QOwnNotes/issues/2234#issuecomment-921208417. Not sure how to work around this (default dialogue without custom text?). Users knowing what they did (activate never ask again-checkbox) should be fine even for a long time, but it´s not really perfect, you´re absolutely right.

**Comment by pbek** [comment]
## 21.9.7
- there now is no need for a restart any more after an automatic dark/light mode switch under
  Windows 10 when the application starts

**Comment by pbek** [comment]
...but there will be no automatic switch during the application runtime. It would be annoying with the need for a restart and block too much other stuff (like global hotkeys and scripts that bring the application to the foreground).

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
## 21.9.9
- when you answer `No` when asked to automatically switch to dark/light mode
  under Windows 10 the answer will now really be remembered if you told the 
  dialog to do so

**Comment by bcutter** [comment]
> 
> 
> There now is a new release, could you please test it and report if it works for you?

Yes that change introduced with 21.9.7 works. Makes it a lot smoother, basically.

**Comment by pbek** [comment]
Thank you for testing. 21.9.9 will be released today 😁

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by bcutter** [comment]
> 
> 
> There now is a new release, could you please test it and report if it works for you?

Jap, works / still no new issues discovered :-)

**Comment by pbek** [comment]
Great, thank you for testing! 😁
