### ISSUE TITLE
Feature Request: Add integration with Collectives from Nextcloud

### ISSUE THREAD

**Issue by latchee** [pbek/QOwnNotes#2237]
Hi there,

First of all, thank you for making such a great app that. already, integrates with Nextcloud! :)

[Nextcloud 22](https://nextcloud.com/blog/nextcloud-22-introduces-knowledge-management/) introduced knowledge management via their new app Collectives.
[Collectives](https://apps.nextcloud.com/apps/collectives) uses markdown to create documentation page. Hence my feature request: similar as Notes, could Collectives pages be integrated with QownNotes. This would make creating documentation pages even easier.

Cheers,

**Comment by pbek** [comment]
Thank you for your kind words. :grin

How would you describe an integration? The only reason QOwnNotes can be used together with Nextcloud Notes is that Nextcloud Notes writes to simple Markdown files, like QOwnNotes does...

Collectives doesn't seem to do that, I'm I right?

**Comment by sunjam** [comment]
Yeah, Collectives would need to be accessible from the filesystem.  Right now this is treated as a feature because it doesn't depend on a person or location... it lives in the database.

Currently impossible according to https://gitlab.com/collectivecloud/collectives/-/issues/200
