### ISSUE TITLE
[I] All Notes count is 0 and Untagged Notes folder doesn't appear when first starting QON on Windows 10

### ISSUE THREAD

**Issue by netguerrilla12** [pbek/QOwnNotes#2239]
#### Expected behaviour

The All Notes folder should show the total number of notes when starting QON. The Untagged Notes folder should be visible when starting QON.

#### Actual behaviour

All Notes shows 0 for the total number of notes and the Untagged Notes folder doesn't appear when first starting QON.

#### Steps to reproduce

Start QON (any version) on Windows 10.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[14:27:29] [debug] updatePanelMenu - 'updatePanelMenu'
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed Sep 22 14:27:45 2021`
**Version**: `21.9.10`
**Build date**: `Sep 19 2021`
**Build number**: `887`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\SV1\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1360x768`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `3820`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\SV1\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `C:\Users\SV1\Sync\QOwnNotes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\SV1\Sync\QOwnNotes\notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**EvernoteImport/AttachmentImportCheckBoxChecked** (QString): `true`
**EvernoteImport/ImageImportCheckBoxChecked** (QString): `true`
**EvernoteImport/MetaDataUnCheckedList** (QStringList): `, created, updated, , note-attributes/subject-date, note-attributes/latitude, note-attributes/longitude, note-attributes/altitude, note-attributes/author, note-attributes/source, note-attributes/source-application, note-attributes/application-data`
**EvernoteImportDialog/geometry** (QByteArray): `<binary data>`
**FileDialog/LastPath** (QString): `C:/Users/SV1/Downloads/Evernote`
**FileDialog/LastPath-Evernote Import** (QString): `C:/Users/SV1/Downloads/Evernote`
**FileDialog/LastPath-ImportTextFiles** (QString): `C:/QOwnNotes/Notes/Test`
**FileDialog/LastPath-Joplin Import** (QString): `C:/Users/SV1/Downloads/Joplin`
**FileDialog/LastPath-NoteMarkdownExport** (QString): `C:/Users/SV1/Downloads/Joplin`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**JoplinImport/AttachmentImportCheckBoxChecked** (QString): `true`
**JoplinImport/FolderImportCheckBoxChecked** (QString): `false`
**JoplinImport/ImageImportCheckBoxChecked** (QString): `true`
**JoplinImport/MetadataImportCheckBoxChecked** (QString): `false`
**JoplinImport/TagImportCheckBoxChecked** (QString): `true`
**JoplinImportDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-09-22T14:20:12.410`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Calibri,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/tagTreeWidgetExpandState-1** (QStringList): `57`
**MessageBoxOverride/restore-note** (int): `16384`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): `SSL Checker`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteFolder-1/allowDifferentNoteFileName** (QString): `true`
**NoteHistory-1** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `199`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePrinting** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TagAddDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `wVw9Ynnw2u52`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): `md, txt`
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `true`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (int): `15`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `C:/Users/SV1/Sync/QOwnNotes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**recentNoteFolders** (QStringList): `C:/QOwnNotes/Notes`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `SSL Checker, What is a 2-in-1 Laptop a Guide to Convertible Laptops Lenovo US, SSL Checker 2021-09-22T12.10.05, The Ultimate Guide to LinkedIn Groups, How to Use LinkedIn Groups (the Right Way) to Build Relationships for Your Business Constant Contact, Why LinkedIn Groups Are Great and How to Build a Successful One, unison home equity reviews - Google Search, Win at Work and Succeed at Life Michael Hyatt, 16 Best Podcasts on Motivation to Help You Reach Your Goals, Note 2021-09-17T13.33.44, 20 Motivational Podcasts to Start Following in 2021, Note 2021-09-16T10.52.30, Note 2021-09-16T08.31.38, Note 2021-09-16T08.24.15, SS&C Careers - Workday, Note 2021-09-13T16.24.11, GET COMFORTABLE ON-CAMERA, Joe Rogan - Why Obese People Can't Lose Weight - YouTube, A Customer Discovered Their $350 Lego Set was Missing Pieces. The Company's Response Was Brilliant Inc.com, Note 2021-09-02T13.14.21, Using WTSQuerySessionInformation to get client computer name when running in a remote session - code - ClarionHub, How to call a function in user32.dll - questions - ClarionHub 2021-09-01T15.40.33, Clarion Online Article by Bruce Johnson, systemMetrics, you mean, Home - Fitness Professionals Marketing Your Business, Debra Walker, Note 2021-08-26T13.07.30, Get the name of the logged-in user and the workstation, Get the Environment Variables, How to call a function in user32.dll - questions - ClarionHub, Use WINAPI to get domain - code Snippets - ClarionHub, Duplicate procedure template after importing procedure from another App - questions tips - ClarionHub, lose 100 lbs - Google Search 2021-08-24T15.06.00, Infinite Banking For Business Owners - YouTube 2021-08-24T15.05.24, Life Insurance Company Ratings and Why They Matter Right Now Podcast - YouTube 2021-08-24T15.04.41, Netguerrilla's Food Diary MyFitnessPal.com, Life Insurance Company Ratings and Why They Matter Right Now Podcast - YouTube, Infinite Banking For Business Owners - YouTube, lose 100 lbs - Google Search, Is Losing 100 Lbs. in a Year Healthy and Realistic – Fat, Broke and Stupid, Home - Fit 2 Fat 2 Fit, QOwnNotes Web Companion browser extension QOwnNotes 2021-08-22T18.12.55, QOwnNotes Web Companion browser extension QOwnNotes, Note 2021-08-22T08.28.50, Note 2021-08-22T08.24.54, Note 2021-08-06T16.06.14, Note 2021-08-06T16.05.39, Unbenannt, Images and Attachments, WordPress Installation Check List, Note 2021-08-05T09.20.41, David Busch's Canon EOS Rebel T61300D Guide to Digital SLR Photography David D, Amazon, Test Notiz, Fwd We just shipped your order!, Fwd Re Re ABEBOOKS Order 137361858, Fwd Re ABEBOOKS Order 137361858, Fwd AbeBooks Sales Order No, 000df3247ebc4551a9ad2b7233ad07a0`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**webSocketServerService/token** (QString): `<hidden>`
**workspace-HMuPGGhgMHn2/name** (QString): `Preview only`
**workspace-HMuPGGhgMHn2/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-HMuPGGhgMHn2/windowState** (QByteArray): `<binary data>`
**workspace-dYqYLZMC3Y5K/name** (QString): `Minimal`
**workspace-dYqYLZMC3Y5K/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-dYqYLZMC3Y5K/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspace-npsLxBsgeNDz/name** (QString): `Full`
**workspace-npsLxBsgeNDz/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-npsLxBsgeNDz/windowState** (QByteArray): `<binary data>`
**workspace-wVw9Ynnw2u52/name** (QString): `Full`
**workspace-wVw9Ynnw2u52/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-wVw9Ynnw2u52/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, dYqYLZMC3Y5K, npsLxBsgeNDz, HMuPGGhgMHn2, wVw9Ynnw2u52`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\SV1\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `SV1`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**GOOGLE_API_KEY**: `no`
**GOOGLE_DEFAULT_CLIENT_ID**: `no`
**GOOGLE_DEFAULT_CLIENT_SECRET**: `no`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\SV1`
**LOCALAPPDATA**: `C:\Users\SV1\AppData\Local`
**LOGONSERVER**: `\\SV1`
**NUMBER_OF_PROCESSORS**: `4`
**OneDrive**: `C:\Users\SV1\OneDrive`
**OneDriveConsumer**: `C:\Users\SV1\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Users\SV1\AppData\Local\Microsoft\WindowsApps;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 60 Stepping 3, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `3c03`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\SV1\AppData\Local\Temp`
**TMP**: `C:\Users\SV1\AppData\Local\Temp`
**USERDOMAIN**: `SV1`
**USERDOMAIN_ROAMINGPROFILE**: `SV1`
**USERNAME**: `SV1`
**USERPROFILE**: `C:\Users\SV1`
**windir**: `C:\WINDOWS`
</details>

**Comment by netguerrilla12** [comment]
Screen shots of this issue
![QON 2](https://user-images.githubusercontent.com/88498198/134417182-e41169e3-68fb-4094-909a-55870c2aa2cd.JPG)
![QON 1](https://user-images.githubusercontent.com/88498198/134417186-8d172c2b-25d1-48a2-82b5-1cf20bd8169b.JPG)
.

**Comment by netguerrilla12** [comment]
I forgot to mention that if I select the menu option to "Reload notes folder" after it reloads the notes folder it will display the total number for All Notes and the Untagged Notes folder will also appear.

**Comment by pbek** [comment]
> The All Notes folder should show the total number of notes when starting QON. 

Phew, I've never seen that behavior and I don't know how I could reproduce it. 😬 

Do you have the same issue when running QOwnNotes in a new session (see [cli-parameters](https://www.qownnotes.org/getting-started/cli-parameters.html))?

> The Untagged Notes folder should be visible when starting QON.

Haven't seen that neither...
On your screenshot there is a scroll bar in the note sub-folder panel. Is that item maybe visible if you scroll down?

**Comment by pbek** [comment]
And can you maybe talk a bit about the device your are using QON? What are your hardware specs? And what disk is `C:\Users\SV1\Sync\QOwnNotes` on? SSD, Spinning Disk, some slow flaw drive?

**Comment by netguerrilla12** [comment]
I have the issue any time I start QON. The device doesn't matter. It happens on all three of my devices; a Dell desktop computer, an HP laptop, and a Surface Go tablet. C:\Users\SV1\Sync\QOwnNotes is on C: drive on all three devices. I don't know what you mean by "some slow flaw drive." The drives in the desktop and the laptop are current technology spinning drives. The drive in the Surface Go would be an SSD. C:\Users\SV1\Sync\QOwnNotes is also synced to the cloud (sync.com).

To rule out any issues with sync.com, I created a new folder on my laptop. The folder was C:\QOwnNotes\Test. Then I restarted QON. It did exactly the same thing. So it has nothing to do with sync.com.

**Comment by pbek** [comment]
Strange, I can't remember ever seeing this on Windows 10.

> "some slow flaw drive."

flash, not flaw. like a netbook.

> I tried SyncThing but it kept corrupting notes. SQLite. According to some articles I read, SyncThing has issues SQLite databases.

The notes are not stored in the SQLite database.

Do you have the same issue when running QOwnNotes in a new session (see above)?

**Comment by netguerrilla12** [comment]
Ah. Flash drive. No. I'm not using a flash drive for this. I know the notes aren't stored in the SQLite DB. I was just pointing out that SyncThing apparently has issues with SQLite DBs. That's why I switched to a different sync platform. I can't have something corrupting my notes.SQLite DB. Of course, that's not a QON issue. That's a SyncThing issue.

If I run QON in a new session I have the same issue. I didn't try the cli-parameters, though. Do you want me to try that? If so, which parameter(s) do you want me to use?

**Comment by pbek** [comment]
It's the `--session` parameter (explained in above link). But don't bother, I now was able to reproduce it.

I don't have this issue in any of my "installations", not even if I create a new note folder.
But when I use a new session I also have the issue. So I imported the settings from my 1st session and don't have the issue any more in that 2nd session. So I started a 3rd session and adapted all settings in the 2nd session by hand to match the settings from the 3rd, but still my 2nd session doesn't have the issue. Only the 3rd session has it... It really is a strange issue.

But no issues on Linux with a new session...

Thank you for bringing it to my attention.

**Comment by netguerrilla12** [comment]
You're welcome. I'm glad you were able to reproduce it. I may have some more issues to report but first I have to do some more testing to make sure I can consistently reproduce the issues and under what circumstances.

**Comment by pbek** [comment]
## 21.9.11
- an issue with the note counts initially not showing up in the *Tags panel* on
  Windows was fixed

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by netguerrilla12** [comment]
This issue is now fixed. Thanks. Like I said, I have some more issues to test. I'll report them to you once I know I can consistently reproduce the issues.

**Comment by pbek** [comment]
Great, and thank you for testing!
