### ISSUE TITLE
[I] Import from Evernote Not Importing Links in Some Cases

### ISSUE THREAD

**Issue by netguerrilla12** [pbek/QOwnNotes#2242]
#### Expected behaviour

Import from Evernote should import links as clickable links.

#### Actual behaviour

Import from Evernote isn't importing links.

#### Steps to reproduce

1. See screen shot QON 1.JPG (which I'll attach) which shows the clickable link in Evernote.
2. In QON, import the ENEX file (which I'll attach).
3. Note that the text got imported but not the clickable link.
4. See screen shot QON 2.JPG (which I'll attach). This shows the note in QON where the text appears but not the clickable link.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[15:46:28] [debug] handleNoteTextFileName - 'name' was changed: "Fwd Your 4 HIgh Value Trainings Access"
[15:46:28] [debug] storing note file: "Fwd Your 4 HIgh Value Trainings Access.md"
[15:46:33] [debug] buildNotesIndex - 'noteSubFolderId': 0
[15:46:38] [debug] setupNoteFolderTables - 'database version': 14
[15:46:40] [debug] cloudConnection: CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
[15:46:41] [debug] loadNoteDirectoryList
[15:46:46] [debug] reloadTagTree
[15:46:46] [debug] reloadTagTree - 'noteSubFolderIds': QVector(0)
[15:46:57] [debug] filterNotesByTag - 'tags': QVector()
[15:46:57] [debug] filterNotesByTag - 'noteIdList': QVector(1)
[15:47:15] [debug] on_noteTreeWidget_itemSelectionChanged
[15:47:15] [debug] setCurrentNote - 'note': Note: <id>1 <name>"Fwd Your 4 HIgh Value Trainings Access" <fileName>"Fwd Your 4 HIgh Value Trainings Access.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false - 'updateNoteText': true - 'updateSelectedNote': false
[15:47:15] [debug] added to history: NoteHistoryItem: <noteName>"Fwd Your 4 HIgh Value Trainings Access" <noteSubFolderPathData>"" <cursorPosition>0 <relativeScrollBarPosition>0
[15:54:02] [debug] doTrashing - 'destinationFileName': "C:/Users/SV1/Sync/QOwnNotes\\trash\\2626"
[15:54:02] [debug] removeNoteFile - 'trashResult': true
[15:54:02] [debug] removeNoteFile - 'this->fileName': "Fwd Your 4 HIgh Value Trainings Access.md"
[15:54:02] [debug] removeNoteFile - 'file': "C:/Users/SV1/Sync/QOwnNotes/Fwd Your 4 HIgh Value Trainings Access.md"
[15:54:03] [debug] Removed note "Fwd Your 4 HIgh Value Trainings Access"
[15:54:03] [debug] loadNoteDirectoryList
[15:54:09] [debug] reloadTagTree
[15:54:09] [debug] reloadTagTree - 'noteSubFolderIds': QVector(0)
[15:54:13] [debug] filterNotesByTag - 'tags': QVector()
[15:54:13] [debug] filterNotesByTag - 'noteIdList': QVector()
[15:54:13] [debug] filterNotesByTag - 'tags': QVector()
[15:54:13] [debug] filterNotesByTag - 'noteIdList': QVector()
[15:54:13] [debug] notesWereModified: "C:/Users/SV1/Sync/QOwnNotes/Fwd Your 4 HIgh Value Trainings Access.md"
[15:54:13] [debug] Current note was removed externally!
[15:54:13] [debug] storing note file: ""
[15:54:13] [critical] "Could not store note file: C:/Users/SV1/Sync/QOwnNotes - Error message: Access is denied."
[15:54:13] [status] Current note could not be stored to disk
[15:54:13] [debug] buildNotesIndex - 'noteSubFolderId': 0
[15:54:16] [debug] setupNoteFolderTables - 'database version': 14
[15:54:19] [debug] cloudConnection: CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
[15:54:19] [debug] setCurrentNote - 'note': Note: <id>0 <name>"" <fileName>"" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false - 'updateNoteText': false - 'updateSelectedNote': true
[15:54:19] [warning] QTextCursor::setPosition: Position '167' out of range
[15:59:24] [debug] Removed tag "RPSM - 4 High Value Trainings"
[15:59:25] [debug] reloadTagTree
[15:59:25] [debug] reloadTagTree - 'noteSubFolderIds': QVector(0)
[15:59:29] [debug] notesDirectoryWasModified: "C:/Users/SV1/Sync/QOwnNotes"
[15:59:29] [status] Notes directory was modified externally
[15:59:29] [debug] buildNotesIndex - 'noteSubFolderId': 0
[15:59:33] [debug] setupNoteFolderTables - 'database version': 14
[15:59:36] [debug] cloudConnection: CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
[15:59:36] [debug] updateNoteText: true
[15:59:36] [debug] setCurrentNote - 'note': Note: <id>0 <name>"" <fileName>"" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false - 'updateNoteText': true - 'updateSelectedNote': true
[15:59:36] [warning] QTextCursor::setPosition: Position '167' out of range
[16:02:36] [debug] updatePanelMenu - 'updatePanelMenu'
[16:02:36] [debug] updatePanelMenu - 'updatePanelMenu'
[16:02:36] [debug] updatePanelMenu - 'updatePanelMenu'
[16:02:36] [debug] updatePanelMenu - 'updatePanelMenu'
[16:02:36] [debug] updatePanelMenu - 'updatePanelMenu'
[16:02:36] [debug] updatePanelMenu - 'updatePanelMenu'
[16:02:36] [debug] updatePanelMenu - 'updatePanelMenu'
[16:02:36] [debug] updatePanelMenu - 'updatePanelMenu'
[16:03:12] [debug] updatePanelMenu - 'updatePanelMenu'
[16:03:12] [debug] updatePanelMenu - 'updatePanelMenu'
[16:03:12] [debug] updatePanelMenu - 'updatePanelMenu'
[16:03:12] [debug] updatePanelMenu - 'updatePanelMenu'
[16:03:12] [debug] updatePanelMenu - 'updatePanelMenu'
[16:03:12] [debug] updatePanelMenu - 'updatePanelMenu'
[16:03:12] [debug] updatePanelMenu - 'updatePanelMenu'
[16:03:12] [debug] updatePanelMenu - 'updatePanelMenu'
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fri Sep 24 16:08:54 2021`
**Version**: `21.9.11`
**Build date**: `Sep 24 2021`
**Build number**: `888`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\SV1\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1360x768`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `3831`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\SV1\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `C:\Users\SV1\Sync\QOwnNotes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\SV1\Sync\QOwnNotes\notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**EvernoteImport/AttachmentImportCheckBoxChecked** (QString): `true`
**EvernoteImport/ImageImportCheckBoxChecked** (QString): `true`
**EvernoteImport/MetaDataUnCheckedList** (QStringList): `, created, updated, , note-attributes/subject-date, note-attributes/latitude, note-attributes/longitude, note-attributes/altitude, note-attributes/author, note-attributes/source, note-attributes/source-application, note-attributes/application-data`
**EvernoteImportDialog/geometry** (QByteArray): `<binary data>`
**FileDialog/LastPath** (QString): `C:/Users/SV1/Downloads/Evernote`
**FileDialog/LastPath-Evernote Import** (QString): `C:/Users/SV1/Downloads/Evernote`
**FileDialog/LastPath-ImportTextFiles** (QString): `C:/QOwnNotes/Notes/Test`
**FileDialog/LastPath-Joplin Import** (QString): `C:/Users/SV1/Downloads/Joplin`
**FileDialog/LastPath-NoteMarkdownExport** (QString): `C:/Users/SV1/Downloads/Joplin`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**JoplinImport/AttachmentImportCheckBoxChecked** (QString): `true`
**JoplinImport/FolderImportCheckBoxChecked** (QString): `false`
**JoplinImport/ImageImportCheckBoxChecked** (QString): `true`
**JoplinImport/MetadataImportCheckBoxChecked** (QString): `false`
**JoplinImport/TagImportCheckBoxChecked** (QString): `true`
**JoplinImportDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-09-24T15:12:13.568`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Calibri,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/tagTreeWidgetExpandState-1** (QStringList): `9`
**MessageBoxOverride/restore-note** (int): `16384`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): *empty*
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteFolder-1/allowDifferentNoteFileName** (QString): `true`
**NoteHistory-1** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `199`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePrinting** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TagAddDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `wVw9Ynnw2u52`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): `md, txt`
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `true`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (int): `15`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `C:/Users/SV1/Sync/QOwnNotes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**recentNoteFolders** (QStringList): `C:/Users/SV1/Sync, C:/QOwnNotes/Test, C:/QOwnNotes/Notes`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `[I] Untagged Notes Count is Double What it Should be After Adding a New Note · Issue #2241 · pbek QOwnNotes, Note 2021-09-24T15.21.14, Note 2021-09-24T15.15.34, 20 BEST Evernote Alternatives and Competitors (Free Paid) in 2021, Note 2021-09-24T12.04.22, Note 2021-09-24T11.50.30, Note 2021-09-24T11.45.34, Russell Welcome - Magnetic Marketing, Group Training with Howard Giles 2021-09-23, SSL Checker, What is a 2-in-1 Laptop a Guide to Convertible Laptops Lenovo US, SSL Checker 2021-09-22T12.10.05, The Ultimate Guide to LinkedIn Groups, How to Use LinkedIn Groups (the Right Way) to Build Relationships for Your Business Constant Contact, Why LinkedIn Groups Are Great and How to Build a Successful One, unison home equity reviews - Google Search, Win at Work and Succeed at Life Michael Hyatt, 16 Best Podcasts on Motivation to Help You Reach Your Goals, Note 2021-09-17T13.33.44, 20 Motivational Podcasts to Start Following in 2021, Note 2021-09-16T10.52.30, Note 2021-09-16T08.31.38, Note 2021-09-16T08.24.15, SS&C Careers - Workday, Note 2021-09-13T16.24.11, GET COMFORTABLE ON-CAMERA, Joe Rogan - Why Obese People Can't Lose Weight - YouTube, A Customer Discovered Their $350 Lego Set was Missing Pieces. The Company's Response Was Brilliant Inc.com, Note 2021-09-02T13.14.21, Using WTSQuerySessionInformation to get client computer name when running in a remote session - code - ClarionHub, How to call a function in user32.dll - questions - ClarionHub 2021-09-01T15.40.33, Clarion Online Article by Bruce Johnson, systemMetrics, you mean, Home - Fitness Professionals Marketing Your Business, Debra Walker, Note 2021-08-26T13.07.30, Get the name of the logged-in user and the workstation, Get the Environment Variables, How to call a function in user32.dll - questions - ClarionHub, Use WINAPI to get domain - code Snippets - ClarionHub, Duplicate procedure template after importing procedure from another App - questions tips - ClarionHub, lose 100 lbs - Google Search 2021-08-24T15.06.00, Infinite Banking For Business Owners - YouTube 2021-08-24T15.05.24, Life Insurance Company Ratings and Why They Matter Right Now Podcast - YouTube 2021-08-24T15.04.41, Netguerrilla's Food Diary MyFitnessPal.com, Life Insurance Company Ratings and Why They Matter Right Now Podcast - YouTube, Infinite Banking For Business Owners - YouTube, lose 100 lbs - Google Search, Is Losing 100 Lbs. in a Year Healthy and Realistic – Fat, Broke and Stupid, Home - Fit 2 Fat 2 Fit, QOwnNotes Web Companion browser extension QOwnNotes 2021-08-22T18.12.55, QOwnNotes Web Companion browser extension QOwnNotes, Note 2021-08-22T08.28.50, Note 2021-08-22T08.24.54, Note 2021-08-06T16.06.14, Note 2021-08-06T16.05.39, Unbenannt, Images and Attachments, WordPress Installation Check List, Note 2021-08-05T09.20.41, David Busch's Canon EOS Rebel T61300D Guide to Digital SLR Photography David D, Amazon, Test Notiz, Fwd We just shipped your order!, Fwd Re Re ABEBOOKS Order 137361858, Fwd Re ABEBOOKS Order 137361858, Fwd AbeBooks Sales Order No, 000df3247ebc4551a9ad2b7233ad07a0`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**webSocketServerService/token** (QString): `<hidden>`
**workspace-HMuPGGhgMHn2/name** (QString): `Preview only`
**workspace-HMuPGGhgMHn2/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-HMuPGGhgMHn2/windowState** (QByteArray): `<binary data>`
**workspace-dYqYLZMC3Y5K/name** (QString): `Minimal`
**workspace-dYqYLZMC3Y5K/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-dYqYLZMC3Y5K/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspace-npsLxBsgeNDz/name** (QString): `Full`
**workspace-npsLxBsgeNDz/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-npsLxBsgeNDz/windowState** (QByteArray): `<binary data>`
**workspace-wVw9Ynnw2u52/name** (QString): `Full`
**workspace-wVw9Ynnw2u52/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-wVw9Ynnw2u52/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, dYqYLZMC3Y5K, npsLxBsgeNDz, HMuPGGhgMHn2, wVw9Ynnw2u52`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\SV1\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `SV1`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**GOOGLE_API_KEY**: `no`
**GOOGLE_DEFAULT_CLIENT_ID**: `no`
**GOOGLE_DEFAULT_CLIENT_SECRET**: `no`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\SV1`
**LOCALAPPDATA**: `C:\Users\SV1\AppData\Local`
**LOGONSERVER**: `\\SV1`
**NUMBER_OF_PROCESSORS**: `4`
**OneDrive**: `C:\Users\SV1\OneDrive`
**OneDriveConsumer**: `C:\Users\SV1\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Users\SV1\AppData\Local\Microsoft\WindowsApps;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 60 Stepping 3, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `3c03`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\SV1\AppData\Local\Temp`
**TMP**: `C:\Users\SV1\AppData\Local\Temp`
**USERDOMAIN**: `SV1`
**USERDOMAIN_ROAMINGPROFILE**: `SV1`
**USERNAME**: `SV1`
**USERPROFILE**: `C:\Users\SV1`
**windir**: `C:\WINDOWS`
</details>

**Comment by netguerrilla12** [comment]
Here are the screen shots and the ENEX file. I had to zip the ENEX file because GitHub wouldn't let me upload it.
![QON 1](https://user-images.githubusercontent.com/88498198/134744679-62418b07-6d86-42d4-9be2-1a7f807690e3.JPG)
![QON 2](https://user-images.githubusercontent.com/88498198/134744691-5f5d6f5d-b836-4a2c-b78c-f83b691e34ce.JPG)
[Fwd Your 4 HIgh Value Trainings Access.zip](https://github.com/pbek/QOwnNotes/files/7228618/Fwd.Your.4.HIgh.Value.Trainings.Access.zip)
.

**Comment by pbek** [comment]
This is the part of your enex file I think you are talking about:

```html
      <p>
        Rick
      </p>
      <p>
        Your &quot;4 High Value Trainings&quot; Access:
      </p>
```

No hyperlink present...

**Comment by pbek** [comment]
Ah sorry... It's the text below...

**Comment by pbek** [comment]
Harder than expected to make that possible, because of the weird xml Evernote is using. If I allow those links not to be squashed down to text other imports have regressions... 😬

**Comment by netguerrilla12** [comment]
I opened the another ENEX file to take a closer look at the XML. I see what you mean about the weird XML. (I attached a screen shot.) It would be unfortunate if you can't find a way to fix this. I still have 2K+ notes in Evernote to import into QON. That would mean I'd have to add all of those links manually. Obviously, that will be quite time consuming. I'm attempting to get everything moved from Joplin and Evernote into QON because I like it better than both.
![QON 3](https://user-images.githubusercontent.com/88498198/134775316-482e627f-c150-4669-822e-ed2cabcbd979.JPG)

**Comment by netguerrilla12** [comment]
You might be wondering why I'm having to import both Joplin and Evernote notes. I was a happy Evernote user for many years. Then they started having financial challenges. I was mostly OK with that. When they came out with their version 10, that's when the trouble began. Long story short, it hosed so much stuff I had to blow it away. Luckily, one of my devices still had a legacy version on it so that's where I kept.

**Comment by pbek** [comment]
It's not about your enex with the link. It's about the other import it breaks if I make importing that links possible because of the exec files that are double html encoded. When I double decode them your links are gone, if I don't double decode them e.g. Russian enex files break. I first need to write a lot of tests to make sure I don't break old imports... That takes time.

**Comment by netguerrilla12** [comment]
Interesting. I had no idea international translations were so involved. Like I said, I've found a work around which seems to work fairly well. I've imported several hundred notes today using that method so take your time and do what you have to do. Or don't worry about it all. I'll leave it up you.

**Comment by pbek** [comment]
And the Evernote importer is very hard to test because of the strong ties to notes that are actually stored. I'd need to rewrite many parts.

**Comment by pbek** [comment]
Took a while...

## 21.9.13
- now named links can be imported in the *Evernote import*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by netguerrilla12** [comment]
This is now fixed. Thanks.

**Comment by pbek** [comment]
Great, thank you for testing!
