### ISSUE TITLE
dark mode tag icon doesn't have red cross

### ISSUE THREAD

**Issue by gzuaps** [pbek/QOwnNotes#2243]
Hi
dark mode tag icon doesn't have red cross indicating that clicking on it will remove the tag

Thanks,

#### Expected behaviour
tag icon will indicate it can be deleted/removed
#### Actual behaviour
standard tag icon is displayed
#### Steps to reproduce
select dark mode icons

**Comment by pbek** [comment]
Which button are we talking about? Can you please make a screenshot.

**Comment by gzuaps** [comment]
Hi
Not a big issue.
It's in the tag panel, if not using dark mode then there is a red cross but dark mode has no cross

![Screenshot_20210925_153340](https://user-images.githubusercontent.com/9564478/134759875-cb5e8bfc-aee1-4743-9d62-4ffd750f2de6.png)

and if not using dark mode icons 

![Screenshot_20210925_153840](https://user-images.githubusercontent.com/9564478/134759953-aca580fe-dafd-44d8-8adf-09d7103b1037.png)

**Comment by pbek** [comment]
I'm not sure which set of settings your are using and which operating system you are on. You didn't fill out the issue template.
Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.

**Comment by pbek** [comment]
Regardless of your settings and platform I tried to improve the detection blindly...

## 21.9.12
- improved tag delete icon in dark-mode

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by gzuaps** [comment]
Thanks,  that looks good.
Sorry for not putting more information in.

**Comment by pbek** [comment]
Great, thank you for testing!
