### ISSUE TITLE
Feature request: Undone and Redo Button/Function

### ISSUE THREAD

**Issue by HDValentin** [pbek/QOwnNotes#2244]
#### Expected behaviour
If something went wrong I would love to have an undone Button

#### Actual behaviour
Something happened e.g. on a notebook by accident i marked text the with the touchpad and overwrite it with new text. So the text was unrecoverable lost. Because I haven't found a function or a button to go a step beck.

#### Steps to reproduce
Delete text in your note. It ist unrecoverable lost.

**Comment by gzuaps** [comment]
I think standard editing buttons work like ctrl-Z for undo.

**Comment by pbek** [comment]
Yes, `Ctrl + Z` works in the editor (the context menu also shows `Undo` in the editor). Plus you can use git to version your notes. Plus if you use a sync service like Nextcloud you can directly access the note file history from within QOwnNotes.

**Comment by HDValentin** [comment]
Thank you for the hint to Ctrl+Z. I am going to try this next time. When I try it now it is working perfect.

When it happened I've done one undo via the rhight click menu. 
Then it the undo in the menu disappeared. Probably a bug? 

I have my notes organised via my nextxloud. But the history is not working. I've tried that already but Qownnotes says, that there is no historiy. Message: There are no message versions at the server or the message do not exist.

**Comment by pbek** [comment]
If there is a undo step then the undo menu item is present, if there doesn't is anything to undo it is disabled.
Also keep in mind you can put the note edit panel in read-only mode!

> . I've tried that already but Qownnotes says, that there is no historiy. 

You didn't share your settings as the issue template suggested. Maybe you don't have setup your remote path correctly.

**Comment by HDValentin** [comment]
> If there is a undo step then the undo menu item is present, if there doesn't is anything to undo it is disabled.
> Also keep in mind you can put the note edit panel in read-only mode!

I had this problem several times. I was active writing in a Note.

> > . I've tried that already but Qownnotes says, that there is no historiy.
> 
> You didn't share your settings as the issue template suggested. Maybe you don't have setup your remote path correctly.

Thank you for the hint with the settings.
The serverpath was not correct.

I think we can close this.
When it happens next time that I overwrite text by accident I am going to investigate what is happening and what is possible with the versioning and Ctrl+Z.

**Comment by pbek** [comment]
Great!
