### ISSUE TITLE
Add signature to exported pdfs (preview) on each page's footer or header

### ISSUE THREAD

**Issue by pkd2989** [pbek/QOwnNotes#2246]
Hi,

I just want to ask, how can I add custom signature( name, website, logo, contact, etc) added automatically to the exported notes as pdfs(preview) on each page of the pdf.  I think this can be done with pandoc with external editing of notes, but it will be very helpful if it's there as a native feature.

Thanks

**Comment by pbek** [comment]
Hi, the native PDF export is done direct with a [QPrinter](https://doc.qt.io/qt-5/qprinter.html) from document of the QTextBrowser, that is used for the preview. I don't think there is a way to add headers and footers to it, maybe you find out more...

If you don't find out something then possibly the best way is to write a script for QOwnNotes to export the note with pandoc, like you mentioned.
