### ISSUE TITLE
Feature request: vim config file loading support

### ISSUE THREAD

**Issue by sahensley** [pbek/QOwnNotes#2247]
First off - thank you for the fantastic software :smiley:  After trying many note keeping platforms, QOwnNotes has become my favorite choice by far.

#### Expected behaviour

I'd like to purpose automatic sourcing of a QOwnNotes / Fakevim Vim config file. 

Since Fakevim has a limited subset of Vim's options, I would expect this to _not_ load the default .vimrc but instead use a name that signifies the config file is QOwnNotes/Fakevim specific, such as .qonvimrc. 

Another option, which may be easier than searching in $HOME type folders for a default file, could be specifying the file to load like the dialog in the screenshot [here](https://github.com/pbek/QOwnNotes/issues/1665#issuecomment-642440620).

I've listed my "qonvimrc" [here](https://github.com/pbek/QOwnNotes/issues/1665#issuecomment-906944161) which resolves the unexpected paste behavior noted in the thread.

#### Actual behaviour

Currently a vimrc like file can get created and manually sourced via ":source" when in VIM mode.  I do this once upon launching QOwnNotes but it would be nice to have it happen automatically.

#### Steps to reproduce

N/A - feature request

#### Output from the debug section in the settings dialog

N/A - feature request

#### Relevant log output in the Log panel

N/A - feature request

**Comment by pbek** [comment]
Thank you for your kind words. 😉 

@Waqar144, do you think this is possible? You already mentioned something in https://github.com/pbek/QOwnNotes/issues/1665#issuecomment-642440620.

**Comment by Waqar144** [comment]
yeah. We basically just have to take a path via settings and run `handleCommand("source /path/to/file")`

**Comment by sahensley** [comment]
Would it be possible to call `handleCommand()` from a script? I didn't see any script examples of doing so, but I'd be glad to attempt to create a script example if it is possible.  Or is `handleCommand()` not exposed in the API - similar to #1633?

**Comment by pbek** [comment]
Yes, I guess that would also be possible.

**Comment by pbek** [comment]
@Waqar144, do you think it would be very disadvantageous to pull the `handler` objects in `MainWindow::initFakeVim` up to the mainwindow, to allow to inject a `handler->handleCommand("command")`?

**Comment by Waqar144** [comment]
Not really.

But I think it's just better to provide a setting for this, that's the right solution. A quick solution could be to just read the vimrc file from home directory by default.

**Comment by pbek** [comment]
## 21.11.10
- when vim-mode is enabled the application will first try to load a `.vimrc.qownnotes`
  file from your home directory, and if not found it will try to load the `.vimrc` file
  to add additional configs

**Comment by Waqar144** [comment]
Great idea. No need for a setting even ;)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by sahensley** [comment]
A W E S O M E :man_dancing: 

It works wonderfully using `.vimrc.qownnotes`.  I haven't tested to see what happens if a customized `.vimrc` file with options that FakeVim doesn't support is attempted to load but I can test that later.

Here's my simple `.vimrc.qownnotes`.  

I'll look through other VIM issues and see which ones can be solved by having loading the config.  I know at least #1665 can be solved by specifying the clipboard.

```vim
set clipboard=unnamed,unnamedplus
set scrolloff=3
nnoremap j gj
nnoremap k gk
:imap jj <Esc>
```

**Comment by pbek** [comment]
Great, thank you for testing! 😁  If you find some more issues / feature requests that can be fixed by config, please let me know!

**Comment by Doomwhite** [comment]
> A W E S O M E 🕺
> 
> It works wonderfully using `.vimrc.qownnotes`. I haven't tested to see what happens if a customized `.vimrc` file with options that FakeVim doesn't support is attempted to load but I can test that later.
> 
> Here's my simple `.vimrc.qownnotes`.
> 
> I'll look through other VIM issues and see which ones can be solved by having loading the config. I know at least #1665 can be solved by specifying the clipboard.
> 
> ```viml
> set clipboard=unnamed,unnamedplus
> set scrolloff=3
> nnoremap j gj
> nnoremap k gk
> :imap jj <Esc>
> ```

Does this still work? I've tried and got no success.

**Comment by sahensley** [comment]
I just tested with the latest QOwnNotes AppImage and it worked fine. My settings are the same as the above post.

``` text
$ cat ~/.vimrc.qownnotes 
set clipboard=unnamed,unnamedplus
set scrolloff=3
nnoremap j gj
nnoremap k gk
:imap jj <Esc>
```

I went through the setup wizard, created a new folder then enabled vim mode.  Once I restarted the application, everything worked as configured in the rc file.

**Comment by Doomwhite** [comment]
> I just tested with the latest QOwnNotes AppImage and it worked fine. My settings are the same as the above post.
> 
> ```
> $ cat ~/.vimrc.qownnotes 
> set clipboard=unnamed,unnamedplus
> set scrolloff=3
> nnoremap j gj
> nnoremap k gk
> :imap jj <Esc>
> ```
> 
> I went through the setup wizard, created a new folder then enabled vim mode. Once I restarted the application, everything worked as configured in the rc file.

Could you test if the scrolloff is working as well? I got the keybindings to work.

**Comment by Doomwhite** [comment]
I'm on Windows, using QOwnNotes portable, this is my .vimrc.qownnotes in the home file.

```
set clipboard=unnamed,unnamedplus
set scrolloff=3

nnoremap Q :q<CR>
```

Unfortunately, none of those worked...

**Comment by sahensley** [comment]
Ah, I'm not sure how the portable version handles config file loading or what the home directory is set to on Windows.

https://github.com/pbek/QOwnNotes/blob/7f4dc7204b60d8ba52556c9293c54616829990f9/src/helpers/fakevimproxy.cpp#L27

Just a guess, but I have to think the RC file isn't being loaded, due to not being in the location where homeDir is expected to be at on Windows.

I think it would be worth opening a new issue to further investigate this - you may have found a new bug :smile:

**Comment by sahensley** [comment]
Few things I noticed in testing:
- clipboard - it worked on my laptop but not my desktop, both the same version of Fedora.  Probably a difference in how I have Wayland or X configured, which doesn't help you anyway on Windows.
- scrolloff behaves oddly - it works once or twice then stops working, at least on the default readme.
- I could not get the :q mapping to work, even mapping it like this - `nnoremap Q ZQ`

I don't know which features are in QOwnNotes but it is using [FakeVim](https://github.com/hluk/FakeVim). That repo may assist in tracking some things down.

**Comment by Doomwhite** [comment]
> 

That was cuz I deleted the post :P, I tested with the wrong method.

**Comment by Doomwhite** [comment]
> For some reason I can see the emails stating you got keybindings to work but not the posts on the issue. Yay computers 😄
> 
> It is loading the config then, so that's a plus. I'll check and see if scrolloff is working (on Fedora) but I do know that the clipboard mapping is working fine.

That was cuz I deleted the post :P, I tested with the wrong method.
