### ISSUE TITLE
In the table, place two lines of text in one cell

### ISSUE THREAD

**Issue by develop987** [pbek/QOwnNotes#2248]
How to place two lines of text in one cell in a table?
#### Expected behaviour
![03 10 2021_14-58-18](https://user-images.githubusercontent.com/90496895/135752848-d0027dba-3087-4fa1-b0da-70d63f555340.png)

#### Actual behaviour
![03 10 2021_15-04-14](https://user-images.githubusercontent.com/90496895/135752862-10c74c42-fd95-4add-ad55-4907e9b3cd1c.png)

**Comment by pbek** [comment]
Unfortunately this doesn't work that way in Markdown. 😅  Every line is a new row. But you could use an html break `<br>` to force a new line.

```markdown
| 111        | 2222 | 3333 | 444  |
| ---------- | ---- | ---- | ---- |
| 55<br>row2 | 666  | 777  | 8888 |
| saa        | aaa  | bbb  | cccc |
```
