### ISSUE TITLE
Do not touch files when being moved to themselves

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#2249]
#### Expected behaviour
- select notes from folder (that has subfolders)
- ~copy~ move to -> select subfolder
- notes are copied and notes that already were present in the subfolder *are left untouched*

#### Actual behaviour
- select notes from folder (that has subfolders)
- ~copy~ move to -> select subfolder
- notes are copied and notes that already were present in the subfolder are *renamed*

Part that is appended:

![image](https://user-images.githubusercontent.com/5956570/135876912-1fe66f49-89d4-4194-8f2a-db2c2c61bd96.png)

#### Steps to reproduce
`qownnotes 21.9.4-1`

Additionally: some visual feedback might be useful after moving notes (dialog)! :)

**Comment by pbek** [comment]
> notes are copied and notes that already were present in the subfolder are renamed

In my test only the copied note was renamed, when a file with the same name already existed, which is what should happen. You can even duplicate notes that way. 😉  That behavior would break with your request.

And what exactly are "notes that already were present" for you? Bit-wise the same content? Also the filename the same?
Chances files are not the same, because if you copy the notes the links to other notes and the links to media files and attachments are modified so that you can still reach the linked files.

https://github.com/pbek/QOwnNotes/blob/b07b039e51d9e318fb15abd06bfc9fe28c4f3420/src/mainwindow.cpp#L9944-L10022

**Comment by pbek** [comment]
> Additionally: some visual feedback might be useful after moving notes (dialog)! :)

It's in the status bar.
And a lot is logged to the debug log (e.g. when files get a new name) if you want high verbosity. 😉

**Comment by sanderboom** [comment]
When I select a toplevel directory, files from subdirectories are displayed. I'm not sure is this is default behavior or due to a setting. I think you should compare the `fullPath` of source and target and only proceed when inequal. Duplication won't work anymore, but a <kbd>Duplicate</kbd> function will be more descriptive anyway ;)

**Comment by pbek** [comment]
> When I select a toplevel directory, files from subdirectories are displayed.

That's a *Panels settings*.

> I think you should compare the fullPath of source and target and only proceed when unequal. 

but then you can't duplicate in the same directory... 

> Duplication won't work anymore

I had two copies of the same note (with different names) after copying to the same directory. Didn't that work for you?

**Comment by sanderboom** [comment]
> but then you can't duplicate in the same directory...

That's what I meant by 'Duplication won't work anymore' - meaning after you implement a check on whether source and destination are equal and only proceed when they are not. And after that I tried to suggest that for 'duplication' you might want to a new menu item named 'Duplicate' (name is more descriptive anyway) :)

**Comment by pbek** [comment]
And are we talking about copying or moving? Your FR title says `moved to theirself`.

**Comment by sanderboom** [comment]
> And are we talking about copying or moving? Your FR title says `moved to theirself`.

(I now see it should be themselves :thinking: )

Moving. 'moved to themselves' -> this happens because files from subdirectories are displayed. So I see a list of notes in the topdirectory, not knowing whether 1 of those is already located in a subdirectory. I move them all to a subdirectory. The ones that were already located in the subdirectory (but displayed in the list on the topdirectory) are renamed as they are *moved to themselves*.

**Comment by pbek** [comment]
Again, are we talking about **moving** notes or **copying** notes?

**Comment by pbek** [comment]
> Expected behaviour
> 
>    select notes from folder (that has subfolders)
>    copy to -> select subfolder

I never tested moving... 😅

**Comment by pbek** [comment]
## 21.10.1
- when copying or moving notes to another sub-folder now notes will not be copied
  or moved to the same sub-folder anymore

There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
That's pretty hard when the note folder gets reloaded after a move...
