### ISSUE TITLE
[NOT AN ISSUE] Quick review of QOwnNotes

### ISSUE THREAD

**Issue by geckolinux** [pbek/QOwnNotes#225]
Hi, I just wanted to leave some general feedback on QOwnNotes and why I think it's one of the best in its class:

I've been extensively researching Markdown editors with live preview and export to a formatted file such as PDF. One of the finalists is QOwnNotes:

- Can work completely offline with a folder on the local filesystem that contains .md files, no xCloud integration required.
- Automatic saves - a surprising number of similar tools require opening a document, and then saving changes before closing. If I wanted a workflow like that I would just use LibreOffice. But QOwnCloud simply saves all changes instantly, which allows me to quickly jot something down and then close it without worrying whether it was saved or not.
- Search - Surprisingly, even some of the very full-featured Markdown editors don't have search across multiple documents. QOwnNotes has instant search/filtering of document titles and their content too, and even allows regexp.
- Tag support - This is also a rare find in Markdown editors, and QOwnNotes even allows a tag hierarchy!
- List of documents - Again, if I wanted to have to open and navigate to a markdown file on my filesystem I would just use LibreOffice. But QOwnNotes has a master Notes directory, and right in the main interface it shows the available document names, and even allows switching between different folders for organization freaks like myself.
- `-` and `*` automatically appear with the <ENTER> key when working on outlines.
- Document navigator automatically creates an index based on your headings to navigate through long documents
- Allows exporting the formatted document to HTML or PDF for printing.
- Allows for linking to other document titles in QOwnNotes with `note:///name-of-title`
- NOT Electron based! Lightweight, fast, and properly packaged for most distros.

This is an extremely full-featured and well thought-out program. It definitely feels like a far better alternative to the likes of Haroopad. Thanks for creating it!

**Comment by pbek** [comment]
Thank you for making my day. I will store your review for later reference. 🎈
