### ISSUE TITLE
Quality Assurance for Translations

### ISSUE THREAD

**Issue by Fabijenna** [pbek/QOwnNotes#2252]
Actual behaviour:

Manual translation without QA is prone to have a lot of bugs, like typos, mistranslations, unedited MT (machine translation), corrupted code, and more.

Even though an SDL TRADOS Studio is among our possibilities to check and correct, I couldn't find a possible way to import Markdown files into Trados.

X-Bench depends on .itx = SDLX files, that means on Trados

Step 1: I want to find out whether these links work so that Trados becomes a possible help in QA for Translations

https://gateway.sdl.com/apex/communityknowledge?articleName=000007588
https://community.sdl.com/product-groups/translationproductivity/f/studio/28465/how-to-translate-markdown-code-blocks
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwikkaDJ1rXzAhUOC-wKHXu3AZAQFnoECBIQAQ&url=https%3A%2F%2Fdocs.rws.com%2F813470%2F727303%2Fsdl-trados-studio-2021%2Fconfiguring-markdown-file-types%3F&usg=AOvVaw2PZI0E_UVIJckheNQN2PaU
https://www.uni-heidelberg.de/md/sued/uebersetzertage2013/01_trados.pdf

I am inviting especially our valued translators to help with their experience and knowledge.

**Comment by Fabijenna** [comment]
> I've no experience there. 😅

Hi. Might be, because only the half of it needs knowledge about Studio, the rest is Github. :-)
It would be such a great improvement.

**Comment by Fabijenna** [comment]
So when you switched on QA, will QA be working for everyone so they will not be able to finish a segment unless they acted on the proper QA message?

**Comment by pbek** [comment]
I don't know, you could test with one of your many accounts. 😁

**Comment by Fabijenna** [comment]
😁
Hard to believe but I have only 1 Crowdin account... 
But you gave me an idea. 😅
