### ISSUE TITLE
Hyperlink recognition in notes

### ISSUE THREAD

**Issue by Born2Root** [pbek/QOwnNotes#2260]
#### Expected behaviour
Webadresses in notes are recognized as a hyperlink when they start with http or just with www.

#### Actual behaviour
If I insert a webadress hyperlink into my note as plain text it is only recognized as a hyperlink when it starts with http.
A plain www. adress is not recognized.
Therefore it is also not possible to simple Ctrl+Click the hyperlink to be opened in the browser.

![Unbenannt](https://user-images.githubusercontent.com/8644900/137277809-44857f50-f24e-48cf-a1fc-06b3afb91ce6.JPG)

#### Question
Is it possible for me as a user to change the behaviour in an .ini file myself?
Otherwise it would be really great if you could implement the hyperlink recognition.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Born2Root** [comment]
Great, works like a charm!
Thank's for the very fast implementation ;-)
