### ISSUE TITLE
Custom new note script causes segmentation fault on Ubuntu 20.10

### ISSUE THREAD

**Issue by pkeir** [pbek/QOwnNotes#2270]
The attached script gives a custom name and headline to a new note.

Since last week, clicking the "New note" button closes the QOwnNotes application. Opening QOwnNotes again shows the file is there, with the correct custom name, but empty: there is no headline.

I am using version 21.10.9 of QOwnNotes via snap on Ubuntu 20.10.

I enabled logging, and saw that the two main functions in the script return the expected values. I also tried removing the script, and after that, a new file is created with no problem.

I get the same issue with the AppImage version (also 21.10.9). I ran it from the command line and it reports "Segmentation fault (core dumped)" at the command line when I select "New note". (So too with launching the snap version at /snap/bin/qownnotes.)

I tried AppImage version 21.10.8 and there is no problem.

This was first discussed in a script issue at https://github.com/qownnotes/scripts/issues/142 where @pbek indicated it is a regression caused by pbek/QOwnNotes@d4c79d6.

[custom-new-note-headline.qml.txt](https://github.com/pbek/QOwnNotes/files/7379611/custom-new-note-headline.qml.txt)

**Comment by pbek** [comment]
This is a regression introduced in https://github.com/pbek/QOwnNotes/commit/d4c79d6a200e9acb648798fe5840a0ddb508788b.

Will be fixed today. Thank you for reporting.

**Comment by pkeir** [comment]
Yes, it works. Another day clocked on at the coal face for my trusty script!
