### ISSUE TITLE
Small quirks for Settings: Editor fonts & colors

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#2275]
Since you seem busy at the moment with the Settings > Editor > Editor fonts & colors... :wink: 

#### It seems that the preview does not match the outcome;
See:
![image](https://user-images.githubusercontent.com/5956570/138672941-eb1edda1-b83f-4ccc-ade6-33996c2ce1fe.png)

`Settings > Interface > Enable darkmode` does not have any influence on this.

#### Changes will be applied also when clicking 'Cancel'
Reproduce: 
- Settings > Interface > Editor > Editor fonts & colors 
- Change the color schema
- Click 'Cancel'
- Click 'Cancel' when asked to restart
- Restart QON
- Change in color schema is applied

Version: `qownnotes 21.10.12-1`

**Comment by tuxfanmatze** [comment]
Thanks for your current engagement. I had the same problem with not shown "Editor fonts & colors". Now it look again well and works!

**Comment by pbek** [comment]
Great, thank you. 😁
