### ISSUE TITLE
Mobile - Ubuntu Touch

### ISSUE THREAD

**Issue by ronbillock** [pbek/QOwnNotes#2281]
Will Qownnotes work on mobile/Ubuntu Touch? If so what needs downloaded/installed? I am wanting to sync my notes from mobile to NextCloud to laptop Qownnotes App. 

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
There now is an Android App: https://www.qownnotes.org/getting-started/qownnotes-android.html.
