### ISSUE TITLE
Color schema for underline format

### ISSUE THREAD

**Issue by RichardBaker3020** [pbek/QOwnNotes#2283]
There is no option for _underline_ format in Editor fonts & colors setting, it seems that _underline_ and _bold_ shares one style, it would be nice if underline format could have its own style setting.

![image](https://user-images.githubusercontent.com/54793121/139564568-1a6870a7-6161-419d-8166-8c7ff2844cf4.png)

**Comment by pbek** [comment]
You are selecting the default text, most settings are turned off because they can't be changed. "Underline" is available for all other settings.

**Comment by RichardBaker3020** [comment]
> You are selecting the default text, most settings are turned off because they can't be changed. "Underline" is available for all other settings.

@pbek , There's a little misunderstanding. 
There are style settings for `Text preset`, `Emphasized text` and `Strong text`, but there's no setting available for `Underline text`.

**Comment by pbek** [comment]
![image](https://user-images.githubusercontent.com/1798101/139567554-3147f7da-9f63-4cfc-b29e-9ffd01017729.png)

**Comment by pbek** [comment]
Ah, you mean a difference between underline and emphasis... I'll see if that can be styled.

**Comment by pbek** [comment]
## 21.11.0
- there now also can **style underlined text** in the *Editor color schema settings* 
  (for [#2283](https://github.com/pbek/QOwnNotes/issues/2283))
    - if a *Editor color schema* was exported now the exported file will be
      opened in the file manager 
    - if the *Bold*, *Italic* or *Underline* settings in *Editor color schema*
      was toggled now there also will be asked for a restart of the application

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by RichardBaker3020** [comment]
> There now is a new release, could you please test it and report if it works for you?

Thanks, it works! But there's a little problem with the default underline format shortcut `ctrl+u`, it will add double underscore to the text, which is actually rendered as `Strong text` instead of `Underlined text`.

**Comment by pbek** [comment]
Now that's strange, I'll look into that.

**Comment by pbek** [comment]
Ok, that seemed to be the case even before 21.11.0... And now I remember all the troubles with combinations of formatting options... 😬

**Comment by pbek** [comment]
@Waqar144, how did we intend to do "underline"? Our underline shortcut uses `__underline__`, but that seems to make troubles... In 21.11.0 I tried something with `_underline_`, which is as I now remember italic, instead of underline. 😅

**Comment by pbek** [comment]
That was before 21.11.0:

<img width="101" alt="image" src="https://user-images.githubusercontent.com/1798101/139581902-14a2be17-f929-4303-b47b-7892b288c091.png">

Now with 21.11.0 I wrongly interpreted `_italic_` as underline and gave it it's own schema option:

<img width="97" alt="image" src="https://user-images.githubusercontent.com/1798101/139581958-354cd939-f260-42a3-aa0e-fd97f032e9be.png">

**Comment by pbek** [comment]
@Waqar144, but it seems the "real" `__underline__` was broken for a longer time...

**Comment by pbek** [comment]
On GitHub `__underline__` is just bold 😆

**Comment by pbek** [comment]
## 21.11.1
- the styling of underlined text was improved

<img width="90" alt="image" src="https://user-images.githubusercontent.com/1798101/139642872-c3a8065d-a0d1-4c72-8192-8358f2688ce4.png">

I think now we are good.

**Comment by Waqar144** [comment]
Underline was I think is always just underscores (any amount) `_underline_`, but I might be forgetting how it is implemented. And yeah, I think it was never mapped to QON styles so only worked with default style.

**Comment by pbek** [comment]
But the way it's done in 21.11.1 now looks ok, do you think (the underlines come from the underline schema item)?

**Comment by Waqar144** [comment]
IIRC, the style at the end is whatever the schema tells qmarkdowntextedit. If you define bold style to appear as italic, it would do that even though the name is bold.

But for the underline, since it was never using any QON styles, it just did whatever we set its value initially.

(all of this is just from my memory, so might not be accurate ;p)

**Comment by pbek** [comment]
Much of the styling was hard-coded in qmarkdowntextedit, I changed that in the last few commits and added the Underline schema item.

**Comment by pbek** [comment]
@RichardBaker3020? Does it look ok now for you?

**Comment by RichardBaker3020** [comment]
> @RichardBaker3020? Does it look ok now for you?

It works perfectly, really appreciate your work! :)

**Comment by pbek** [comment]
Great, thank you for testing!
