### ISSUE TITLE
QOwnNote can't fetch calendars from OwnCloud 9.1

### ISSUE THREAD

**Issue by LightTemplar** [pbek/QOwnNotes#229]
Just as the title says, I can't get my calendars from my OwnCloud server. Its Version is 9.1, I think itis related, as they changed its Calendar app and the Path to CalDAV API.

**Comment by pbek** [comment]
Thank you for reporting, do you know the new path?

**Comment by LightTemplar** [comment]
/remote.php/dav/ - for both CalDAV and CardDAV.

**Comment by pbek** [comment]
Thank you, I will take care of that.

**Comment by pbek** [comment]
I just installed ownCloud 9.1.0.8 and calendar fetching worked just fine. What is different in your installation. Do you care to create a test account for me on your ownCloud instance?

**Comment by LightTemplar** [comment]
here you go:
https://temple.ocloud.de
pbek
test123

**Comment by pbek** [comment]
Thank you, it was able to use the `default` calendar and create tasks there with QOwnNotes...

Can you please post the debug output from the settings dialog?

**Comment by pbek** [comment]
btw, you might want also to install the QOwnNotesAPI app on your ownCloud server...

**Comment by LightTemplar** [comment]
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Do. Juni 23 17:19:11 2016`  
**Version**: `16.06.11`  
**Build date**: `Jun 23 2016`  
**Build number**: `187`  
**Platform**: `linux`  
**Operating System**: `Ubuntu 16.04 LTS`  
**Build architecture**: `x86_64`  
**Current architecture**: `x86_64`  
**Release**: `Launchpad PPA`  
**Qt Version (build)**: `5.5.1`  
**Qt Version (runtime)**: `5.5.1`  
**Locale (system)**: `en_GB`  
**Locale (interface)**: `en`  
**Icon theme**: `breeze-dark`  
**Notes in current note folder**: `3`  
**Enabled scripts**: `0`  

## Server Info

**serverUrl**: `https://temple.ocloud.de`  
**appIsValid**: `no`  
**connectionErrorMessage**: `Unknown error`  

## Note folders

**currentNoteFolderId**: `5`  

### default

**id**: `1`  
**activeTagId**: `2`  
**localPath**: `/media/alexander/DATA/oc_test/Notes`  
**remotePath**: `Notes`  

### OCloud.de

**id**: `3`  
**activeTagId**: `-1`  
**localPath**: `/media/alexander/DATA/Data/temple.ocloud.de/Notes`  
**remotePath**: `Notes`  

### Goals

**id**: `4`  
**activeTagId**: `-1`  
**localPath**: `/media/alexander/DATA/Data/temple.ocloud.de/Notes/Goals`  
**remotePath**: `Notes/Goals`  

### Diary

**id**: `5`  
**activeTagId**: `1`  
**localPath**: `/media/alexander/DATA/Data/temple.ocloud.de/Notes/Diary`  
**remotePath**: `Notes/Diary`  

## Settings

**DistractionFreeMode/isEnabled**: `false`  
**DistractionFreeMode/mainSplitterSizes**: `<binary data>`  
**DistractionFreeMode/menuBarGeometry**: `<binary data>`  
**DistractionFreeMode/menuBarHeight**: `32`  
**DistractionFreeMode/windowState**: `<binary data>`  
**LastUpdateCheck**: `2016-06-23T17:13:19`  
**LogDialog/showAtStartup**: `false`  
**MainWindow/geometry**: `<binary data>`  
**MainWindow/mainToolBar.iconSize**: `22`  
**MainWindow/menuBarGeometry**: `<binary data>`  
**MainWindow/noteTextEdit.code.font**: `Noto Sans,10,-1,0,50,0,0,0,0,0`  
**MainWindow/noteTextEdit.font**: `Noto Sans,13,-1,0,50,0,0,0,0,0`  
**MainWindow/noteTextView.code.font**: `Noto Sans,10,-1,0,50,0,0,0,0,0`  
**MainWindow/noteTextView.font**: `Noto Sans,10,-1,0,50,0,0,0,0,0`  
**MainWindow/showRecentNoteFolderInMainArea**: `true`  
**MainWindow/windowState**: `<binary data>`  
**PiwikClientId**: `<hidden>`  
**ShowSystemTray**: `false`  
**SortingModeAlphabetically**: `false`  
**allowDifferentNoteFileName**: `false`  
**allowOnlyOneAppInstance**: `false`  
**appMetrics/disableAppHeartbeat**: `false`  
**appMetrics/disableTracking**: `false`  
**appMetrics/notificationShown**: `true`  
**cryptoKey**: `<hidden>`  
**currentNoteFolderId**: `5`  
**customNoteFileExtensionList**: *empty*  
**darkMode**: `false`  
**darkModeColors**: `false`  
**defaultNoteFileExtension**: `txt`  
**demoNotesCreated**: `true`  
**disableAutomaticUpdateDialog**: `false`  
**externalEditorPath**: *empty*  
**ignoreAllExternalModifications**: `false`  
**interfaceLanguage**: `en`  
**mainSplitterSizes**: `<binary data>`  
**mainSplitterState-0-1-1-0**: `<binary data>`  
**mainSplitterState-1-1-0-0**: `<binary data>`  
**mainSplitterState-1-1-1-0**: `<binary data>`  
**markdownHighlightingInterval**: `200`  
**networking/ignoreSSLErrors**: `false`  
**networking/proxyType**: `2`  
**noteEditPaneEnabled**: `true`  
**noteListSplitterState**: `<binary data>`  
**noteSaveIntervalTime**: `10`  
**notesPath**: `/media/alexander/DATA/Data/temple.ocloud.de/Notes/Diary`  
**notifyAllExternalModifications**: `false`  
**ownCloud/password**: `<hidden>`  
**ownCloud/serverUrl**: `https://temple.ocloud.de`  
**ownCloud/todoCalendarBackend**: `0`  
**ownCloud/todoCalendarEnabledList**: *empty*  
**ownCloud/todoCalendarEnabledUrlList**: *empty*  
**ownCloud/todoCalendarUrlList**: *empty*  
**ownCloud/userName**: `templar`  
**recentNoteFolders**: `/media/alexander/DATA/Data/temple.ocloud.de/Notes/Goals, /media/alexander/DATA/Data/temple.ocloud.de/Notes, /media/alexander/DATA/oc_test/Notes, /media/alexander/DATA/oc_test/Notes/Tesst`  
**savedSearches/noteFolder-1**: `Note 2016-06-18T20.36.54, Note 2016-06-18T18.54.06, Note 2016-06-15T12.40.17, Note 2016-06-15T11.45.02, Note 2016-06-11T16.53.12`  
**savedSearches/noteFolder-3**: `Goal Template, test`  
**savedSearches/noteFolder-4**: `Note 2016-06-23T12.26.35`  
**savedSearches/noteFolder-5**: `Note 2016-06-23T14.09.32, Note 2016-06-23T12.53.55, Note 2016-06-23T12.43.44`  
**skipVersion**: `16.06.11`  
**tagsEnabled**: `true`  
**verticalNoteFrameSplitterState**: `<binary data>`

**Comment by LightTemplar** [comment]
I will think about QOwnNotesAPI, but a bit later - now I don't need a versions feature and access to trashed files.

**Comment by LightTemplar** [comment]
![image](https://cloud.githubusercontent.com/assets/453783/16309131/f8ea1970-3967-11e6-843f-67ffe6de804d.png)

**Comment by pbek** [comment]
I can't see anything out of order in your settings and I get the same errors because the app is not installed. What happens when you reload the calendar list in the `Todo` tab?

**Comment by LightTemplar** [comment]
Nothing, it stays empty. I've created also a "test" calendar, but there is still nothing in calendar list in the todo tab.

**Comment by LightTemplar** [comment]
could it have impact, that I had another connection to another server, with OwnCloud 8.0 before this one?

**Comment by pbek** [comment]
I don't know, what happens if you use the user `pbek`?

**Comment by LightTemplar** [comment]
Oh! You will wonder. From that user I can get calendars...

**Comment by pbek** [comment]
Maybe some migration problem? Or the way your calendars are named? Maybe you can try to create all your calendars at the `pbek` user... And if that still works import your calendar items...

**Comment by LightTemplar** [comment]
May be. I tried to delete all calendars and created one new, but there is still no result in the app.  I wrote you an E-Mail.

**Comment by pbek** [comment]
I will take a look at it tomorrow, I'm on the run right now...

**Comment by pbek** [comment]
I already tested it and it worked flawlessly with your `test` calendar.

**Comment by pbek** [comment]
Are some proxy settings in place in your network?

**Comment by LightTemplar** [comment]
No proxies, direct connection.

**Comment by pbek** [comment]
I'm out of ideas... Maybe using Wireshark to see what requests are going on... or building QOwnNotes yourself print out the response to the calendar request...

**Comment by pbek** [comment]
If you still have this problem or get it again, please visit [My calendars cannot be fetched from my ownCloud server](http://www.qownnotes.org/Knowledge-base/My-calendars-cannot-be-fetched-from-my-ownCloud-server).

**Comment by LightTemplar** [comment]
I got messages from console:
```
Info: Reply from ownCloud calendar page:  "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<d:error xmlns:d=\"DAV:\" xmlns:s=\"http://sabredav.org/ns\">\n  <s:sabredav-version>3.0.8</s:sabredav-version>\n  <s:exception>Sabre\\DAV\\Exception\\NotFound</s:exception>\n  <s:message>Node with name 'username' could not be found</s:message>\n</d:error>\n" ((null):0, (null))
Info: calendarHrefList:  () ((null):0, (null))
```
And I found the problem. It was the capitalization =)
As I entered "Username", instead of "username", all calendars was fetched =)

**Comment by pbek** [comment]
Ah, great! But you can login with "Username" to your ownCloud instance? (and QOwnNotes also said the username is ok because of that?)

**Comment by LightTemplar** [comment]
Yes, I can. Letter's case doesn't matter for login.

**Comment by pbek** [comment]
Interesting, so it just matters for caldav (and possibly also for carddav), good to know.
Can you tell me how your login is stored in your ownCloud instance? Does it say "Username" or "username"?
I want to know if the username for caldav just can be forced to "username" to prevent problems in the future...

**Comment by LightTemplar** [comment]
I think, you could show a message from server "<**s:message**></**s:message**>", if there is a error: <**d:error** "></**d:error**>
Just a suggestion, I don't know exactly, what is returned and when.

**Comment by LightTemplar** [comment]
In my OwnCloud instance there is "Username" for this particular username, and "username" for others. 
So, you can't force it :(

**Comment by pbek** [comment]
So what you want to say is, that your username is really "Username" and not "username"? Or is it "username"?

**Comment by LightTemplar** [comment]
it is really "Username" in the OwnCloud server. In the user list.
And the whole problem was, because I tried "username" in QOwnNotes.

**Comment by pbek** [comment]
Ah, so it was the other way around, thank you.
btw. could you be so kind and post a screenshot of the snap version of QOwnNotes? I would like to see how it looks. Does it look the same as when you run it from the native package?

**Comment by LightTemplar** [comment]
Snap: (https://cloud.githubusercontent.com/assets/453783/16953294/cdb085f4-4dcc-11e6-9a81-10dac53feb7a.png)
It didn't get KDE Theme, so I set "Dark Mode". 
And I couldn't get the folder Tree, though all checks were on. This, on the screenshot, and in the folder settings - "Show subfolders in the folder list"

Apt: (https://cloud.githubusercontent.com/assets/453783/16953529/a748a576-4dcd-11e6-87c6-16c3b8684ab2.png)

**Comment by pbek** [comment]
Thank you! So you are using Ubuntu 16.04 LTS with Unity as desktop, right?

**Comment by LightTemplar** [comment]
Nope. It's Kubuntu LTS 16.04, with KDE as desktop :)

**Comment by pbek** [comment]
But you are not using the breeze icon set in KDE, right?

btw. 

## 16.07.10
- there now are error messages when something went wrong while loading your 
  ownCloud todo lists in the `Todo` tab of the settings dialog

**Comment by pbek** [comment]
@LightTemplar, could you please test if you get an error message when you use the wrong username when the release is out.

**Comment by LightTemplar** [comment]
It's Oxygen icon set. I didn't pay much attention to them, though - just set it someday and forgot =)

I'll test the new version as soon it comes to repos.

**Comment by LightTemplar** [comment]
The Message Window works well!

**Comment by pbek** [comment]
great, thank you!
