### ISSUE TITLE
Feature request:  quick note open by filename

### ISSUE THREAD

**Issue by RichardBaker3020** [pbek/QOwnNotes#2290]
Would it be possible to add a _quick note open_ feature like the one in VS Code? This is a very powerful feature, you can quickly search and open a note by its name no matter what subfolder it's in, but I imagine it could be a little bit tricky to implement...

In VS Code you can open any file by its name when you type `Ctrl+P` (Quick Open), this will show you a file list so you can select one of them with arrow key and hit `Enter` to open the target in a new tab.

_find action_ (shortcut `Ctrl+Shift+A`)  is probably a very similar feature, it could jump to any action very quickly and conveniently. 
![image](https://user-images.githubusercontent.com/54793121/139880934-1b5a18fb-374d-4886-a16d-c33013da341e.png)

**Comment by pbek** [comment]
`Alt + F` already searches in all subfolders and tags (see https://www.qownnotes.org/getting-started/shortcuts.html). I even see it in your screenshot. 😉

**Comment by RichardBaker3020** [comment]
> `Alt + F` already searches in all subfolders and tags (see https://www.qownnotes.org/getting-started/shortcuts.html). I even see it in your screenshot. 

I notice that `Alt + F` actually search notes by their name as well as their content. So if you search a note whose name is quite commonly used in note text, say `object`, and you happen to have a large number of notes, then picking out the target note from a long list of results could be difficult.😂

Would it be a better idea to seperate these two functionalities so notes can be searched by name only or by content only? Or we can make results searched by name rank at top of the list.

**Comment by pbek** [comment]
You can also only search for a name, see https://www.qownnotes.org/getting-started/searching.html.

**Comment by RichardBaker3020** [comment]
> You can also only search for a name, see https://www.qownnotes.org/getting-started/searching.html.

Okay, I think I might as well go read the instructions thorougfully, thanks for your patience!

**Comment by pbek** [comment]
Those instructions are pretty scattered... 😁
