### ISSUE TITLE
Can no longer get on #qownnotes on irc.libera.chat

### ISSUE THREAD

**Issue by stevelitt** [pbek/QOwnNotes#2291]
#### Expected behaviour

Either I can /join #qownnotes, or I am given a place to ask for an invitation to join the #qownnotes channel.

#### Actual behaviour

Starting 2 days ago, when I logged into irc.libera.chat and performed /join #qownnotes , it refused and said it was a channel by invitation only. Before 2 days ago, I was able to /join #qownnotes at that server with no problem. This was using Hexchat on an up-to-date Void Linux desktop computer with 64 GB RAM and an AMD Ryzen 6 core, 12 thread processor. I tried to /join as user stevelitt, same as always. I can still l /join my other channels hosted on irc.libera.chat.

The /join attempt creates the following message:

Cannot join to channel #qownnotes (You must be invited)

#### Steps to reproduce

Using Hexchat logged in as stevelitt, or irssi logged in as slitt, perform /join #qownnotes . The result is the following message:

Cannot join to channel #qownnotes (You must be invited)

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

N/A, this does not involve QOwnNotes

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>
Cannot join to channel #qownnotes (You must be invited)

**Comment by pbek** [comment]
That's a really annoying problem of Libera.Chat, that Freenode didn't have...
From time to time Libera.Chat just "forgets" all channel settings, then I have to recover the channel manually and set everything up again. 😢 

Thank you for reporting, you should be able to join again.

**Comment by pbek** [comment]
> Starting 2 days ago, when I logged into irc.libera.chat and performed /join #qownnotes ,

I think it happens when my own user looses connection, e.g. when my "The Lounge" client restarts... But that happened about 20h ago, not 2 days ago.

**Comment by pbek** [comment]
I'm trying to execute all needed commands automatically when my connection gets up again after a server restart.
