### ISSUE TITLE
Heartbeat and tracking should be disabled by default

### ISSUE THREAD

**Issue by lifebarier** [pbek/QOwnNotes#2293]
Heartbeat and tracking should be disabled by default

**Comment by pbek** [comment]
Development prioritizing and platform support depends on it.
You can turn it off on first run of the application in the welcome dialog. If you don't turn it off it even tells you about it a 2nd time.

**Comment by lifebarier** [comment]
>Development prioritizing and platform support depends on some basic metrics.

That excuse is always bs.

On first run it is hidden - aka I can click "finish" before I reach that.
Even if there is second question about this - all tracking must be opt-in, not opt-out.

**Comment by pbek** [comment]
> On first run it is hidden - aka I can click "finish" before I reach that.

Did you press finish before you reached the end? If yes, then you would have seen the 2nd dialog.

**Comment by lifebarier** [comment]
> > On first run it is hidden - aka I can click "finish" before I reach that.
> 
> Did you press finish before you reached the end? If yes, then you would have seen the 2nd dialog.

No, because I have healthy mistrust of developers like yourself.
All tracking must be Opt-In not Opt-Out. You are betting on people just clicking "next"/"ok" without reading. Else you would ask to turn it on (no one would, and this is why you are betting on people not reading.. As I said "dick move").

**Comment by pbek** [comment]
I will lock this now for foul language, since I don't think this discussion will amount to much more than sapping my life force and motivation.
