### ISSUE TITLE
Window size/position is not remembered on macOS

### ISSUE THREAD

**Issue by ckayr** [pbek/QOwnNotes#2294]
#### Expected behaviour
QON remembers last window size and position.

#### Actual behaviour
QON opens with a default size every time (maximized in the vertical dimension). 

#### Steps to reproduce
1. Open QON
2. Resize window and adjust position on screen
3. Close and reopen QON

#### Output from the debug section in the settings dialog
N/A.
<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

I've only checked on macOS Monterey. I'm using an external monitor if that matters.

**Comment by pbek** [comment]
I cannot reproduce that on macOS 10.15 (no external monitor), position and size are remembered for me.

Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting Debug in Options).

Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.

**Comment by ckayr** [comment]
Thank you for the prompt response. I don't see anything useful in the debug log (attached).

Here's the output from the Debug section:

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mon Nov 8 22:43:18 2021`
**Version**: `21.11.3`
**Build date**: `Nov  5 2021`
**Build number**: `910`
**Platform**: `macosx`
**Operating System**: `macOS 12.0`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/Users/ckayr/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/ckayr/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Volumes/EncNotes/apps/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `715`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/Users/ckayr/Library/Application Support/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Notes`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/Volumes/EncNotes/notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/Volumes/EncNotes/notes/notes.sqlite`

## Cloud connections

### Cloud connection ``

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Enabled scripts

## Settings

**AKLastCheckInAttemptDate** (QDateTime): `2019-10-01T22:17:31.329`
**AKLastCheckInSuccessDate** (QDateTime): `2019-10-01T22:17:31.904`
**AKLastEmailListRequestDateKey** (QDateTime): `2021-03-03T23:12:48.498`
**AKLastIDMSEnvironment** (qlonglong): `0`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Country** (QString): `US`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-4d50131d-fb68-4fc7-b93c-5d0585f184e0`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (qlonglong): `4`
**Editor/removeTrailingSpaces** (bool): `false`
**Editor/showLineNumbers** (bool): `false`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**InitialKeyRepeat** (qlonglong): `25`
**KeyRepeat** (qlonglong): `2`
**LastUpdateCheck** (QDateTime): `2021-11-08T22:41:13.845`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (qlonglong): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Menlo,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Monaco,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Menlo,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `.AppleSystemUIFont,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MultipleSessionEnabled** (bool): `true`
**NoteFolder-1/NoteTabNameList** (QStringList): `Test Note`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteHistory-1** (QVariantList): `<variant list with 1 item(s)>`
**NoteHistoryCurrentIndex-1** (qlonglong): `0`
**PKSecureElementAvailableFlags** (qlonglong): `1`
**PKSecureElementAvailableFlagsByHost** (qlonglong): `1`
**PKSecureElementAvailableFlagsByHostSome** (qlonglong): `1`
**PiwikClientId** (QString): `<hidden>`
**Qualcomm CDMA Technologies MSM QHSUSB__BULK** (QString): `1`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (qlonglong): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**WebAutomaticSpellingCorrectionEnabled** (bool): `true`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**_HIHideMenuBar** (bool): `false`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `false`
**appMetrics/disableAppHeartbeat** (bool): `true`
**appMetrics/disableTracking** (bool): `true`
**appMetrics/notificationShown** (bool): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (qlonglong): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (qlonglong): `1`
**customNoteFileExtensionList** (QStringList): `md, txt`
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `true`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `txt`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (bool): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `false`
**enableWebAppSupport** (bool): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (qlonglong): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `true`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (qlonglong): `1024`
**imageScaleDownMaximumWidth** (qlonglong): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (qlonglong): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (qlonglong): `18`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (qlonglong): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (qlonglong): `2`
**newNoteAskHeadline** (bool): `true`
**noteEditIsCentralWidget** (bool): `true`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (qlonglong): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (qlonglong): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (qlonglong): `0`
**notesPanelOrder** (qlonglong): `0`
**notesPanelSort** (qlonglong): `1`
**notesPath** (QString): `/Volumes/EncNotes/notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (qlonglong): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (qlonglong): `0`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (bool): `false`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**showMatches** (bool): `true`
**showMenuBar** (bool): `false`
**showStatusBar** (bool): `true`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (qlonglong): `0`
**tagsPanelSort** (qlonglong): `0`
**todoCalendarSupport** (bool): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (qlonglong): `6`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**userMenuExtraStyle** (qlonglong): `2`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (qlonglong): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**USER**: `ckayr`
**__CFBundleIdentifier**: `com.PBE.QOwnNotes`
**COMMAND_MODE**: `unix2003`
**DISPLAY**: `/private/tmp/com.apple.launchd.0Xhaf2T5Uf/org.xquartz:0`
**LOGNAME**: `ckayr`
**PATH**: `/usr/bin:/bin:/usr/sbin:/sbin`
**SSH_AUTH_SOCK**: `/private/tmp/com.apple.launchd.Exp2mP3oKe/Listeners`
**SHELL**: `/bin/zsh`
**HOME**: `/Users/ckayr`
**__CF_USER_TEXT_ENCODING**: `0x1F7:0x0:0x0`
**TMPDIR**: `/var/folders/b4/y_9zc4yn5wj887z8cr3l0x480000gq/T/`
**XPC_SERVICE_NAME**: `application.com.PBE.QOwnNotes.2804.3037`
**XPC_FLAGS**: `0x0`
**QT_LOGGING_RULES**: `qt.network.ssl.warning=false`

[log.txt](https://github.com/pbek/QOwnNotes/files/7502643/log.txt)

**Comment by pbek** [comment]
Nothing seems out of order.

Do you have the same issue when running QOwnNotes in a new session (see [cli-parameters](https://www.qownnotes.org/getting-started/cli-parameters.html))?

I wonder if macOS is forcing the window size...

**Comment by ckayr** [comment]
Thanks. It is not reproducible with QOwnNotes --session test.

So it must be something to do with my current settings. 

I've tried clearing out everything from the Settings dialog (General -> Clear app data and exit) as well as deleting everything I could find in ~/Library related to QON. Anything else I could try?

**Comment by pbek** [comment]
Everything that is stored (beside the data in your note folder) is here:

    Settings path / key: /Users/ckayr/Library/Preferences/com.pbe.QOwnNotes.plist
    Application database path: /Users/ckayr/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite

**Comment by pbek** [comment]
Did you still have the issue after clearing the app data?

**Comment by ckayr** [comment]
Yes, I do have the problem after clearing app data too.

It makes no sense but I've kind of narrowed it down to one thing. If I check "Use note subfolders", the window size/position is lost. If I uncheck it, the app remembers the size/position correctly.

**Comment by pbek** [comment]
Amazing. I cannot even imagine how that could play a role. I've to try reproducing it next time I've access my my macBook.

**Comment by ckayr** [comment]
This is not a huge problem for me. I'll leave it up to you to close this. Thank you for this really neat app!

**Comment by pbek** [comment]
Thank you. 😁 
I'll first take a look if I can reproduce it under Catalina with sub-folders.

**Comment by pbek** [comment]
Hm, I don't have the issue on 10.15 with subfolders. 😬

**Comment by ckayr** [comment]
Thanks for checking this. I've tested this on my end as well with --session. I cannot reproduce it with subfolders if my notes are on the Mac HD but can reproduce if my notes are on a removable volume. At this point, I'm going assume that it has something to do with my environment and move my notes to the HD 😀

**Comment by pbek** [comment]
Thank you for testing! Still, it's strange...

**Comment by ckayr** [comment]
Not sure what really happened, but window sizing seems to be restored correctly with v21.11.10

**Comment by pbek** [comment]
Strange 😅
