### ISSUE TITLE
[Q] How do you actually add new Todo items?

### ISSUE THREAD

**Issue by nonplayer** [pbek/QOwnNotes#2295]
#### General question

I'm using the mac version, syncing Todo items with Nextcloud. I saw that the app could "Manage your Nextcloud / ownCloud todo lists" as mentioned on the main site, so I was hoping I could add new todo items as part of said management.

I can sync with Nextcloud and see my Todos when I open the todo menu. But nothing I seem to do is able to add new todos. There is no "add" button, and when I try to write a new todo it either does nothing at all, or instead saves over an existing one.

Am I doing something wrong? Or is this even a function?

#### Information about the application, settings and environment

**Current Date**: `Tue Nov 9 04:57:16 2021`
**Version**: `21.11.3`
**Build date**: `Nov  5 2021`
**Build number**: `910`
**Platform**: `macosx`
**Operating System**: `macOS 10.15`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`

**Comment by pbek** [comment]
![image](https://user-images.githubusercontent.com/1798101/140932335-d53fe68d-aeb8-4245-b7a9-864ec8488e1a.png)

**Comment by nonplayer** [comment]
Just tested and it works fine on a windows installation. Gonna try a reinstall on the mac.

**Comment by pbek** [comment]
It attempts to create the item on your server and syncs them back down to QOwnNotes.

Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting Debug in Options).

And can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.
