### ISSUE TITLE
MacOS Monterey: Crashes on Settings

### ISSUE THREAD

**Issue by dklueh79** [pbek/QOwnNotes#2296]
Using the Settings will crash on macOS Monterey. Even when changing to another tab, like network or nextcloud-connection. Saving is currently not possible. Clearing the config is not possible, client crashes before saving.

Crash-Report:  

```quote
 -------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               QOwnNotes [4481]
Path:                  /Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes
Identifier:            com.PBE.QOwnNotes
Version:               21.11.4 (21.11.4)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2021-11-12 21:28:08.7633 +0100
OS Version:            macOS 12.0.1 (21A559)
Report Version:        12
Bridge OS Version:     6.0 (19P548)
Anonymous UUID:        8FA5B524-F1B1-88AF-A93E-2F0CDEAC2F39

Sleep/Wake UUID:       39A7BFBE-E940-4187-A69F-729F0CF447FB

Time Awake Since Boot: 18000 seconds
Time Since Wake:       3445 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [4481]

VM Region Info: 0 is not in any region.  Bytes before following region: 4536061952
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      10e5ed000-10ebed000    [ 6144K] r-x/r-x SM=COW  ...cOS/QOwnNotes

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
```

**Comment by pbek** [comment]
I cannot reproduce this under Catalina, but it seems in https://github.com/pbek/QOwnNotes/issues/2294 there shouldn't be an issue in Monterey.

What did you change in the settings that caused a crash?

Do you have the same issue when running QOwnNotes in a new session (see [cli-parameters](https://www.qownnotes.org/getting-started/cli-parameters.html))?

**Comment by dklueh79** [comment]
I hadn't this on Catalina - but after changing on Monterey the issue is reproduce-able. I neededn't to change anything (it's not possible - the app crashes before saving anything), its enough to change between the categories on the left. Maybe from *network* to *nextcloud / own cloud*  

I tried reinstalling - the behavior is the same.

**Comment by pbek** [comment]
> I tried reinstalling - the behavior is the same.

Reinstalling doesn't change the settings. Have you tried a new session (see above)?

It seems @ckayr was able to use the app on Monterey.

**Comment by ckayr** [comment]
Yes, I didn't have any problems with modifying settings or using the app on Monterey.

@dklueh79 - Try to delete ~/Library/Preferences/QOwnNotes.plist or if you're using a session, ~/Library/Preferences/QOwnNotes-<sessionname>.plist and then re-run QON.

You may also need to remove cached preferences (see https://stackoverflow.com/questions/19303958/deleting-plist-file-does-not-reset-app-on-macos-10-9).

**Comment by ckayr** [comment]
Oh and just adding the obvious - my comment [above](https://github.com/pbek/QOwnNotes/issues/2296#issuecomment-967665417) will delete all your settings and you'll have to setup everything from scratch.

**Comment by pbek** [comment]
for testing you could just run a new session (with fresh settings): https://www.qownnotes.org/getting-started/cli-parameters.html 😉

**Comment by dklueh79** [comment]
Workaround for me: Clearing the configuration, restart of the Nextcloud API after clearing necessary.

**Comment by pbek** [comment]
> restart of the Nextcloud API after clearing necessary

with "restart" you mean you need to configure it again, right?
