### ISSUE TITLE
[Q] Note names stay at their initial name instead of the title in the content

### ISSUE THREAD

**Issue by dedeibel** [pbek/QOwnNotes#2297]
#### General question

Hi there,

I just wanted to know if this is a feature now and I have to find some setting – or maybe a bug?

The note names in the notes list stays at it's initial name "Note DATE" instead of adjusting to the title I define in the note itself. I really liked that feature, was this changed intentionally?

Thanks and please contact me if my question was unclear.

Version 21.11.4 on debian.

Thank you very much

Ben
(Benjamin Peter)

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[08:28:17] [status] Stored current note to disk
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mon Nov 15 08:28:30 2021`
**Version**: `21.11.4`
**Build date**: `Nov 12 2021`
**Build number**: `911`
**Platform**: `linux`
**Operating System**: `Debian GNU/Linux 11 (bullseye)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/home/bpeter/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/bpeter/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `2560x1440`
**Screen resolution(s)**: `2560x1440, 1440x810`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `115`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `de_BE, de_DE, de_LU, en_US`
**Language names**: `Deutsch (Belgien), Deutsch (Deutschland), Deutsch (Luxemburg), American English (United States)`
**Application dictionaries path**: `/home/bpeter/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/bpeter/Notes/qownnotes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/bpeter/Notes/qownnotes/notes.sqlite`

### Cloud connection ``

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**AttachmentDialog/geometry** (QByteArray): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (bool): `false`
**Editor/autoBracketRemoval** (bool): `false`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (bool): `true`
**Editor/showLineNumbers** (bool): `false`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**FileDialog/LastPath** (QString): `/home/bpeter/.screenlayout`
**FileDialog/LastPath-InsertAttachment** (QString): `/home/bpeter/.screenlayout`
**FileDialog/LastPath-InsertImage** (QString): `/tmp`
**FileDialog/LastPath-NoteHTMLExport** (QString): `/tmp/action doc`
**FileDialog/LastPath-NoteMarkdownExport** (QString): `/tmp`
**FileDialog/LastPath-NotePDFExport** (QString): `/tmp/action doc`
**ImageDialog/disableCopying** (QString): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-11-15T07:58:16.386`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Hack,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Roboto Medium,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Roboto Medium,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**NoteFolder-1/NoteTabNameList** (QStringList): `Note 2021-11-12T12.45.11`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteFolder-1/allowDifferentNoteFileName** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `199`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-actionDelete_line** (QKeySequence): `Ctrl+D`
**Shortcuts/MainWindow-action_DuplicateText** (QKeySequence): *empty*
**Shortcuts/MainWindow-action_Print_note_markdown** (QKeySequence): *empty*
**Shortcuts/MainWindow-togglePanel-notePreviewDockWidget** (QKeySequence): `Ctrl+Shift+P`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `true`
**appMetrics/disableTracking** (bool): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `2hZak7hW59wL`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): `md, txt`
**darkMode** (bool): `true`
**darkModeColors** (bool): `true`
**darkModeIconTheme** (bool): `true`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `false`
**enableWebAppSupport** (bool): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): `gitk`
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full-vertical`
**insertTimeFormat** (QString): `yyyy-MM-dd hh:mm`
**interfaceFontSize** (int): `15`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (int): `18`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `false`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `false`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `1`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/bpeter/Notes/qownnotes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `true`
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (int): `2`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `initial`
**restoreCursorPosition** (bool): `true`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2021-11-15T08.28.17, Note 2021-11-12T12.45.11, Note 2021-11-11T15.51.23, Note 2021-11-10T14.52.28, …REMOVED
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (bool): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, `
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (bool): `false`
**useSoftWrapInNoteEditor** (QString): `true`
**useUNIXNewline** (bool): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**workspace-2hZak7hW59wL/name** (QString): `Full vertical`
**workspace-2hZak7hW59wL/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-2hZak7hW59wL/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 2hZak7hW59wL`

## System environment

**USER**: `bpeter`
**LANGUAGE**: `en_US:en`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `1872`
**HOME**: `/home/bpeter`
**DESKTOP_SESSION**: `mate`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**GTK_MODULES**: `gail:atk-bridge:canberra-gtk-module`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**LOGNAME**: `bpeter`
**GTK_IM_MODULE**: `ibus`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_ID**: `2`
**GTK_OVERLAY_SCROLLING**: `0`
**CLUTTER_BACKEND**: `x11`
**PATH**: `/home/bpeter/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**DISPLAY**: `:0.0`
**LANG**: `en_GB.UTF-8`
**XDG_CURRENT_DESKTOP**: `MATE`
**XDG_SESSION_DESKTOP**: `mate`
**XAUTHORITY**: `/home/bpeter/.Xauthority`
**XMODIFIERS**: `@im=ibus`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm/data/bpeter`
**SHELL**: `/usr/bin/zsh`
**GDMSESSION**: `mate`
**QT_ACCESSIBILITY**: `1`
**UDEdir**: *empty*
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**XDG_VTNR**: `7`
**QT_IM_MODULE**: `ibus`
**PWD**: `/home/bpeter`
**XDG_DATA_DIRS**: `/usr/share/mate:/usr/local/share/:/usr/share/`
**CLUTTER_IM_MODULE**: `ibus`
**MATE_DESKTOP_SESSION_ID**: `this-is-deprecated`
**SESSION_MANAGER**: `local/aconbg009:@/tmp/.ICE-unix/1800,unix/aconbg009:/tmp/.ICE-unix/1800`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**QT_SCALE_FACTOR**: `1`
</details>

**Comment by pbek** [comment]
>  NoteFolder-1/allowDifferentNoteFileName (bool): true

You set that the note names can differ from the file name, that's the reason the name isn't adapted. Just turn that off in the note folder settings. 😉

**Comment by dedeibel** [comment]
Thank you, changing this setting helps.

But please note that I do not recall changing this setting.

**Comment by pbek** [comment]
Hm, nothing should change this setting on its own... Since when did it behave differently? What version did you have before 21.11.4?

**Comment by dedeibel** [comment]
I am sorry, I cannot say it exactly, one or two weeks. I am updating regularly from the repo http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Debian_11

**Comment by pbek** [comment]
Thank you. Strange. Nothing has changed with the setting for a long time. It just was on by default for a while, if you create a new note folder. I later put that back to off by default... But that was longer ago than just a few weeks and that change doesn't touch existing note folders.
