### ISSUE TITLE
Weird behavior when opening note in a new tab

### ISSUE THREAD

**Issue by RichardBaker3020** [pbek/QOwnNotes#2298]
If there are multiple notes opened, and you try to open the currently focused note in another tab (through *Open note in tab* option or double clicks), the previous note in the note history will be opened in a new tab. I think the expected behavior is no new notes will be opened instead and it stays in the currently focused note.

And If the previous note in history has already been opened in another tab, a blank tab will be opened:

![image](https://user-images.githubusercontent.com/54793121/141953939-faad5f02-a0a8-4305-b59d-631398797521.png)

![image](https://user-images.githubusercontent.com/54793121/141954036-a6fc2f3f-ad4f-4523-b80e-77f3ab688464.png)

**Comment by pbek** [comment]
I was not able to reliably reproduce this.

Can you please describe step by step what you did to reproduce this issue?

**Comment by RichardBaker3020** [comment]
A video has been uploaded, I hope this shows the steps clearly:

https://user-images.githubusercontent.com/54793121/141964489-0808db23-3f4c-4d1d-8004-f84de550bda2.mp4

**Comment by pbek** [comment]
I still didn't manage to reproduce it. I can't see how you are clicking...

Could please break it down to a text list, also describing how you click (right / left)?

**Comment by RichardBaker3020** [comment]
> I still didn't manage to reproduce it. I can't see how you are clicking...
> 
> Could please break it down to a text list, also describing how you click (right / left)?

Okay, I'll try to clarify every step.

First part of the video:
1. Let's have two notes (say A and B) open in two different tabs, and have note A in the focused tab.
2. Left click another note item (say note C) in the notes list to show note C in the focused tab, then switch back to note A by left-clicking the note item A in the list. This way we could have note C in our browsing history.
3. Now we still have A opened in the current tab, we then right click the focused note item A in the notes list and choose *Open note in tab* option in the menu. We already have A opened here and we try to open another A in a new tab.
4. However, the previously browsed note C will be opened in a new tab instead, which is an unexpected behavior because we are actually trying to open another A in tab.


Second part of the video:
1. Still have two notes (A and B) open in two different tabs, switch to the tab of note B (left-clicking the tab), then switch back to the tab of note A, so we have B in the browsing history.
2. Now try to open another A in tab by *Open note in tab* menu option in the notes list.
3. Then a blank note B will be opened in a new tab, but we're trying to open another A in tab.

**Comment by pbek** [comment]
> First part of the video:

I think you are describing the way the tab opening works in QON, since right-clicking a note already opens it in the current tab I tried to simulate an "almost normal" behavior by opening the last note in the current tab and the current note in a new tab. 😅

**Comment by pbek** [comment]
> Second part of the video:
> 1. then switch back to the tab of note A

For this issue to happen you have to click on the tabs, right? Because clicking on the note in the note list didn't trigger it for me.

**Comment by RichardBaker3020** [comment]
> 
> I think you are describing the way the tab opening works in QON, since right-clicking a note already opens it in the current tab I tried to simulate an "almost normal" behavior by opening the last note in the current tab and the current note in a new tab. sweat_smile

Okay, I think I get the point now😂. It's weird to me that right-clicking a note item will also open the note current tab. Would it be a better idea to let right-clicking only open the context menu without opening the note in tab? I think it might be more intuitive.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
Btw. in case you didn't know... By default double clicking on the note also opens a new tab.

**Comment by sahensley** [comment]
Apologies if this should be a new issue.  I am adding this as a comment here as it seems to be related to 21.11.7 and #2298.

After upgrading to version 21.11.7, I can no longer get a note to open in a tab.  Double-clicking a note does not open a tab nor does "Right-click > Open note in tab".  I attempted some basic troubleshooting of disabling Vim mode and scripts but that did not seem to make a difference.

I am running the following version of QON:
QOwnNotes - version 21.11.7 - AppImage - build 914
Built on Nov 17 2021 with Qt 5.15.2.

I also tested this on a Windows install and I encountered the same issue.

**Comment by pbek** [comment]
Thank you for pointing that out, @sahensley! This really is a regression I created with 21.11.7. 🤣  I jump to the existing tab if a new tab is requests... The current note always exist as tab. 😅  I'll try to find another way today...

**Comment by pbek** [comment]
I think I found a way to fix @RichardBaker3020 issue and note have the regression found by you, @sahensley.

## 21.11.8
- fixed a regression from 21.11.7 where notes couldn't be opened in a new tab if
  there weren't already note tabs open

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by sahensley** [comment]
I always find it amusing the random things that pop up when working on software, especially on a long-lived code base. "Why did I do it that way?" then a bit of time passes and "Oh, that's why! :grin: "

The new version is working great :tada: Thanks for the quick fix!

**Comment by pbek** [comment]
Great, thank you for testing! 😁
