### ISSUE TITLE
[Feature Request] Export to PDF

### ISSUE THREAD

**Issue by LEDfan** [pbek/QOwnNotes#23]
Hi, I'm really liking you're app :+1: .

A nice feature would be to easily export to PDF. At the moment there is no way of printing the rendered markdown.

Thanks in advance!

**Comment by pbek** [comment]
Thank you for your suggestion, that would be nice.
I will look into the matter of how much work that would be.

**Comment by pbek** [comment]
It's your lucky day, take a look at the new version 0.69. ;)

**Comment by LEDfan** [comment]
Nice! I just tested and it works like expected :).
