### ISSUE TITLE
Disable status bar option

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#230]
For now status bar is always on eating precious vertical space. In full screen editor mode I find it very distracting with the note all over my screen and that full bar just for one button and a reminder about new version most of time. Due to excellent development pace of the app that is. ;)

I propose to make option to switch status bar off including the one in full screen editor. I'd leave just a transparent "quit" button there.

**Comment by pbek** [comment]
I'm not sure if all your "proposals" are possible...

**Comment by Maboroshy** [comment]
But it's worth a try, isn't it? You know that "won't fix" don't make me cry (at least out loud).

**Comment by pbek** [comment]
We'll see. :)

**Comment by pbek** [comment]
Christmas came early this year. ;)

## 16.06.13
- there now is a checkbox to disable the status bar in the windows menu 
    - if you have disabled the status bar use the <kbd>Esc</kbd> key to leave 
      the distraction free mode, because the `leave` button is in the status bar

**Comment by Maboroshy** [comment]
Great! Waiting when new version hits AUR to test.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment]
Working good on Linux and Windows.

**Comment by pbek** [comment]
Great, thank you for testing.
