### ISSUE TITLE
'cd' into a folder in a script

### ISSUE THREAD

**Issue by ckayr** [pbek/QOwnNotes#2300]
Is it possible to do this?. I'd like to cd into the top-level note folder and run a command say 'tig'. Any process I run from a script seems to start in my home folder.  I scanned the available methods but didn't find anything suitable.

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
You need a shell to do a `cd`. Best put all your shell code into a shell script and run that.

You could put that shell script in the same folder as your qml script and get the folder with https://www.qownnotes.org/scripting/methods-and-objects.html#reading-the-path-to-the-directory-of-your-script.

**Comment by ckayr** [comment]
Sure, that'd work.

**Comment by ckayr** [comment]
Sorry, I don't know if github etiquette allows reopening issues but here goes:

What I was looking for is the equivalent of QProcess::setWorkingDirectory (poorly worded in my issue title and description - my apologies). Would it be possible to expose this as in scripting (perhaps as an additional/optional parameter to start*Process?

**Comment by pbek** [comment]
I guess that would be possible.

**Comment by pbek** [comment]
## 21.11.10
- the scripting functions `startDetachedProcess` and `startDetachedProcess` now
  have an optional parameter `workingDirectory` (for [#2300](https://github.com/pbek/QOwnNotes/issues/2300))
  - for more information please take a look at the [scripting documentation](https://www.qownnotes.org/scripting/methods-and-objects.html)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by ckayr** [comment]
Thank you! This works now.

**Comment by pbek** [comment]
Great, thank you for testing!
