### ISSUE TITLE
[I] Stuck while some sybmols appears in REGEXP search

### ISSUE THREAD

**Issue by intervisionlord** [pbek/QOwnNotes#2302]
#### Expected behaviour

Continue of editing search field

#### Actual behaviour

When some symbols appears in search field in regexp mode (like ":" or "," or "~") the programm goes in "Not responding" state totally.

#### Steps to reproduce

1. Create some note with 10-15 rows of similar data (like some lists of FQDN's or smth. else)
2. press CTRL+R
3. switch to regexp mode
4. Start to fill search field with regexp symbols (try several each time)
5. Got stuck

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Чт ноя 18 18:01:49 2021`
**Version**: `21.11.7`
**Build date**: `Nov 17 2021`
**Build number**: `914`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\Lord\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Users\Lord\AppData\Roaming\qOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `ru_RU`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `284`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://twrc.ru`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `21.0.4.1`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\Lord\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Заметки`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `D:\CLOUD\Заметки`
**remotePath**: `Заметки`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: `SRK`
**database file**: `D:\CLOUD\Заметки\notes.sqlite`

### Cloud connection `TWR`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://twrc.ru`
**username**: `intervision`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2021-11-18T17:53:04.884`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `WORK, WORK/SRK`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/move-notes** (int): `16384`
**MessageBoxOverride/remove-notes** (int): `16384`
**MessageBoxOverride/update-and-restart** (int): `16384`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): `17.11.2021 09.00-18.00`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `WORK`
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `114`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TrashDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**VersionDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): `md, txt`
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `false`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `true`
**itemHeight** (int): `15`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `D:/CLOUD/Заметки`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): `CLOUD`
**ownCloud/todoCalendarEnabledList** (QStringList): `CLOUD`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://twrc.ru/remote.php/dav/calendars/intervision/cloud/`
**ownCloud/todoCalendarUrlList** (QStringList): `https://twrc.ru/remote.php/dav/calendars/intervision/cloud/`
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Неизвестная ошибка`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `21.0.4.1`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2021-11-18T17.04.49, Note 2021-11-18T09.57.42, Note 2021-11-17T15.38.52, Note 2021-11-17T11.29.20, Note 2021-11-17T09.46.18, Note 2021-11-16T12.03.47, Note 2021-11-16T09.02.19, Note 2021-11-15T08.42.25, Note 2021-11-12T09.18.45, Note 2021-11-11T09.05.44, Note 2021-11-10T14.53.08, Note 2021-11-10T13.06.46, Note 2021-11-10T12.56.24, Note 2021-11-10T09.02.52, Note 2021-11-09T18.05.18, Note 2021-11-09T18.04.35, Note 2021-11-09T14.56.20, Note 2021-11-09T14.56.02, Note 2021-11-09T11.03.33, Note 2021-11-09T10.46.46, Note 2021-11-09T09.18.41, Note 2021-11-08T16.38.21, Note 2021-11-08T09.00.54, Note 2021-11-03T17.44.17, Note 2021-11-03T17.03.28, Note 2021-11-03T09.19.21, Note 2021-11-02T15.35.19, Note 2021-11-02T09.59.03, Note 2021-11-01T13.02.12, Note 2021-11-01T11.43.35, Note 2021-11-01T09.17.12, Note 2021-10-29T11.25.55, Note 2021-10-28T16.42.52, Note 2021-10-28T12.16.04, Note 2021-10-28T12.00.21, Note 2021-10-28T10.44.21, Note 2021-10-28T10.43.39, Note 2021-10-28T10.38.48, Note 2021-10-28T10.38.00, Note 2021-10-26T15.36.25, Note 2021-10-23T09.32.17, Note 2021-10-22T09.49.17, Note 2021-10-19T10.22.11, Note 2021-10-18T11.03.19, Note 2021-10-15T09.10.43, Note 2021-10-14T08.57.29, Note 2021-10-11T08.51.24, Note 2021-10-10T09.07.07, Note 2021-10-07T08.18.25, Note 2021-10-06T07.44.29, Note 2021-10-03T08.18.07, Note 2021-10-02T07.39.00, Note 2021-09-28T07.48.46, Note 2021-09-25T07.56.49, Note 2021-09-24T08.26.20, Note 2021-09-12T10.29.11, Note 2021-09-09T09.14.52, Note 2021-09-05T09.47.10, Note 2021-09-04T08.55.34, Note 2021-09-04T08.55.08, Note 2021-08-31T08.29.50, Note 2021-08-28T08.52.29, Note 2021-08-27T07.49.10, Note 2021-08-24T09.45.19, Note 2021-08-23T12.25.00, Note 2021-08-20T08.39.43, Note 2021-08-19T08.04.51, Note 2021-08-16T07.52.44, Note 2021-08-15T10.43.55, Note 2021-08-12T07.36.40, Note 2021-08-11T10.21.13, Note 2021-08-08T09.30.07, Note 2021-08-07T07.53.11, Note 2021-07-19T09.13.48, Note 2021-07-18T08.02.13, Note 2021-07-15T19.32.49, Note 2021-07-14T14.53.50, Note 2021-07-11T13.31.23, Note 2021-07-10T07.53.47, Note 2021-07-07T09.00.38, Note 2021-07-06T09.54.17, Note 2021-07-03T09.24.16, Note 2021-07-02T08.39.36, Note 2021-06-29T12.20.27, Note 2021-06-28T08.19.29, Note 2021-06-25T09.09.06, Note 2021-06-24T08.11.18, Note 2021-06-21T14.46.24, Note 2021-06-20T07.57.46, Note 2021-06-17T08.18.12, Note 2021-06-16T08.46.49, Note 2021-06-05T07.56.25, Note 2021-06-04T08.10.13, Note 2021-06-01T12.37.20, Note 2021-05-31T09.03.05, Note 2021-05-28T10.19.01, Note 2021-05-27T09.33.33, Note 2021-05-27T08.36.23, Note 2021-05-24T11.24.33, Note 2021-05-23T19.35.23`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**skipVersion** (QString): `21.10.9`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, `
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Главная панель инструментов`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `панель инструментов форматирования`
**toolbar/3/items** (QStringList): `actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `панель инструментов вставки`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `панель инструментов шифрования`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `панель инструментов окна`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `Панель инструментов выхода`
**toolbar/size** (int): `6`
**trashSplitterSizes** (QByteArray): `<binary data>`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**versionSplitterSizes** (QByteArray): `<binary data>`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (int): `22222`
**webSocketServerService/token** (QString): `<hidden>`
**workspace-initial/name** (QString): `Минимальный`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**AMDRMPATH**: `C:\Program Files\AMD\RyzenMaster\`
**APPDATA**: `C:\Users\Lord\AppData\Roaming`
**BESIEGE_GAME_ASSEMBLIES**: `C:/Program Files (x86)/Steam/steamapps/common/Besiege/Besiege_Data\Managed/`
**BESIEGE_UNITY_ASSEMBLIES**: `C:/Program Files (x86)/Steam/steamapps/common/Besiege/Besiege_Data\Managed/`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `LIRA`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**CV_Instance001**: `D:\WORK\CCConsole\Base`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\Lord`
**LOCALAPPDATA**: `C:\Users\Lord\AppData\Local`
**LOGONSERVER**: `\\LIRA`
**NUMBER_OF_PROCESSORS**: `12`
**OneDrive**: `C:\Users\Lord\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Touch Portal\plugins\adb\platform-tools;C:\Users\Lord\AppData\Local\Microsoft\WindowsApps;C:\Users\Lord\AppData\Local\atom\bin;C:\Users\Lord\AppData\Local\Microsoft\WindowsApps;C:\Users\Lord\.dotnet\tools`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD`
**PROCESSOR_LEVEL**: `23`
**PROCESSOR_REVISION**: `7100`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\Lord\AppData\Local\Temp`
**TMP**: `C:\Users\Lord\AppData\Local\Temp`
**USERDOMAIN**: `LIRA`
**USERDOMAIN_ROAMINGPROFILE**: `LIRA`
**USERNAME**: `Lord`
**USERPROFILE**: `C:\Users\Lord`
**windir**: `C:\WINDOWS`
**__COMPAT_LAYER**: `DetectorsAppHealth`
</details>

**Comment by pbek** [comment]
> When some symbols appears in search field in regexp mode (like ":" or "," or "~") the programm goes in "Not responding" state totally.

I wasn't able to reproduce that with any of those characters.
Can you please post an example text and an example search query?

**Comment by intervisionlord** [comment]
> 
> 
> > When some symbols appears in search field in regexp mode (like ":" or "," or "~") the programm goes in "Not responding" state totally.
> 
> I wasn't able to reproduce that with any of those characters. Can you please post an example text and an example search query?

There are some troubles to reproduce this issue because it is floating. I'll try to gather more examples for provide.

**Comment by pbek** [comment]
Ok, thank you. 😁

**Comment by intervisionlord** [comment]
Seems, that this error disappeared for some reason. I suppose that i might be reopen this issue with more details when this issue appears again.
Sry for troubling.

**Comment by pbek** [comment]
No problem 😁

**Comment by intervisionlord** [comment]
Hello again.
It seems, that i have figured out how this issue appears. And i was able to reproduse it several times.
So, first of all we need some text (ex.: 4 rows with some hostnames). After that we need to open "search and replace" tool via CTRL+R.
Then, lets insert the `$` symbol (i want to paste some text in each end of the row).
Then switch mode to "Regular expressions" and we have stuck.

**Comment by pbek** [comment]
Thank you, I can reproduce that. If you just search for the regular expression `$` (end of line), then the QRegularExpression parser uses 100%. Maybe I'll just prevent that one string.

**Comment by pbek** [comment]
It's the same with just `^` (beginning of line).

**Comment by intervisionlord** [comment]
> Thank you, I can reproduce that. If you just search for the regular expression `$` (end of line), then the QRegularExpression parser uses 100%. Maybe I'll just prevent that one string.

What if parser could perform it's checks not immediate but after regexp form lost it's focus?
I think that this would be a simple workaround - after this field lost focus considered that user finished to write regexp and it completed
(sry for my english btw)

**Comment by pbek** [comment]
That wouldn't solve the issue, wouldn't it? 😀  You could still enter `$`, then change the focus and get the issue. 😁

**Comment by pbek** [comment]
## 21.12.4
- when doing a regular expression search in a note a stuck application is now prevented
  when the user enters just start or end markers

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by intervisionlord** [comment]
Hi, thank you for fixing it. Seems it is ok now.
Much appreciated.

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by n-wissam** [comment]
> * when doing a regular expression search in a note a stuck application is now prevented
>       when the user enters just start or end markers

I have the exact same problem on QON  22.7.2 when I search for ^ or $ in regular expression mode in search and replace.

**Comment by pbek** [comment]
Can you please describe your issue?

**Comment by pbek** [comment]
Thank you for your observation. I'll improve on that!

**Comment by pbek** [comment]
## 22.7.4
- the stuck regular expression detection while searching in notes was improved
  (for [#2302](https://github.com/pbek/QOwnNotes/issues/2302#issuecomment-1184745128))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
I guess I need to find another way to detect those than by just looking for certain characters 😅

**Comment by pbek** [comment]
## 22.7.5
- prevent infinite loops in in-note regular expression searches by limiting to
  10.000 search iterations (for [#2302](https://github.com/pbek/QOwnNotes/issues/2302#issuecomment-1185769472))

**Comment by n-wissam** [comment]
To make you feel better, [Typora](https://typora.io/) also freezes when searching for ^ and $ in regex mode!

**Comment by pbek** [comment]
Next try. 😉  There now is a new release, could you please test it and report if it works for you?

**Comment by n-wissam** [comment]
> Next try. wink There now is a new release, could you please test it and report if it works for you?

Thank you very much it's working now. I am going to create an issue that I can't find more than 10000 search results in regular expressions mode. (It is only a joke)

**Comment by pbek** [comment]
I feared you would say that. 😂
