### ISSUE TITLE
QOwnNotes command-line snippet manager

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#2304]
Integration for https://github.com/qownnotes/qc.

**Comment by pbek** [comment]
## 21.11.9
- added support for the [QOwnNotes command-line snippet manager](https://github.com/qownnotes/qc)
  to execute command snippets stored in notes in QOwnNotes from the command line
  (for [#2304](https://github.com/pbek/QOwnNotes/issues/2304))
    - you can use notes with a special tag to store command snippets, which you can
      execute from the command-line snippet manager
    - for more information please visit the [Command-line snippet manager](https://www.qownnotes.org/getting-started/command-line-snippet-manager.html)

**Comment by pbek** [comment]
And the old tune again, @Waqar144 😅  The builds systems broke for older Qt versions...
https://build.opensuse.org/package/live_build_log/home:pbek:QOwnNotes/desktop/Debian_8.0/x86_64

**Comment by pbek** [comment]
@Waqar144, is this something you are maybe interested in? 😁

**Comment by Waqar144** [comment]
I see you finally put all that go learning into a project ;p

**Comment by pbek** [comment]
Believe me, I wanted to do that with QOwnNotes directly... But was virtually impossible.
So I did it separately...

Go is awesome! https://github.com/qownnotes/web-app was also done in Go 😉

**Comment by pbek** [comment]
## 21.11.11
- now whitespaces after the list characters `-` or `*` for command or bookmark
  lists are allowed
