### ISSUE TITLE
Support highlighting for [X]

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#2313]
#### Expected behaviour

Highlight `[X]` like `[x]`.

#### Actual behaviour

Screenshot:

![image](https://user-images.githubusercontent.com/5956570/143856053-14612571-abaa-495e-85bb-652ca209edf6.png)

Ignore the following diff, see pull-request instead :)

~~I created a fix, but I'm not sure in what project to commit this. I pulled the main repo and made this change.~~

```diff
diff --git a/markdownhighlighter.cpp b/markdownhighlighter.cpp
index a1e2055..efaabcb 100644
--- a/markdownhighlighter.cpp
+++ b/markdownhighlighter.cpp
@@ -1761,7 +1761,7 @@ void MarkdownHighlighter::highlightLists(const QString &text) {
         const int start = spaces + 2;
         constexpr int length = 3;
         // checked checkbox
-        if (text.at(spaces + 3) == QLatin1Char('x') &&
+        if ((text.at(spaces + 3) == QLatin1Char('x') || text.at(spaces + 3) == QLatin1Char('X')) &&
             text.at(spaces + 4) == QLatin1Char(']')) {
             setFormat(start, length, _formats[CheckBoxChecked]);
         }
```

~~Maybe my local branches are outdated... I'll look into it when I have some time.~~

In the mean time: are `[X]` supported anyway? Otherwise I'll remove that option from the `toggle-checkbox` script.

TIA.

**Comment by pbek** [comment]
## 21.12.0
- highlighting support for checkboxes list with an `X` (instead of `x`) was added
  (for [#2313](https://github.com/pbek/QOwnNotes/issues/2313), thank you @sanderboom)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
