### ISSUE TITLE
v21.11.14 - Segfault on start with files on Notes directory

### ISSUE THREAD

**Issue by AlessandroPerazzetta** [pbek/QOwnNotes#2319]
Application can't start with an already populated notes directory, segmentation fault, need to remove notes directory and create a new empty one, relaunch application and import notes from another directory with notes files, after that application run fine until close and next launch immediatly segfault.

#### Expected behaviour
Launch application and browse notes

#### Actual behaviour
Application start but immediatly close, a windows appear and fastly close.
Launching app from console the message is:

Info: "QOwnNotes server listening on port 22222" ((null):0, (null))
Segmentation fault (core dumped)

#### Steps to reproduce
Launch application with notes folder already populated, example after an upgrade from previous working version (maybe 21.11.8)

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Nov 30 17:50:10 2021`
**Version**: `21.11.14`
**Build date**: `Nov 28 2021`
**Build number**: `921`
**Platform**: `linux`
**Operating System**: `Linux Mint 20.2`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.12.8`
**Qt Version (runtime)**: `5.12.8`
**Portable mode**: `no`
**Settings path / key**: `/home/alessandro/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/alessandro/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080`
**Icon theme**: `Mint-Y`
**Notes in current note folder**: `0`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `de_AT, de_AT_frami, de_CH, de_CH_frami, de_DE, de_DE_frami, en_AU, en_CA, en_GB, en_US, en_ZA, es_AR, es_BO, es_CL, es_CO, es_CR, es_CU, es_DO, es_EC, es_ES, es_GT, es_HN, es_MX, es_NI, es_PA, es_PE, es_PR, es_PY, es_SV, es_US, es_UY, es_VE, fr, fr_BE, fr_CA, fr_CH, fr_FR, fr_LU, fr_MC, it_CH, it_IT, pt_BR, pt_PT, ru_RU`
**Language names**: `Österreichisches Deutsch (Österreich), Österreichisches Deutsch (Österreich), Schweizer Hochdeutsch (Schweiz), Schweizer Hochdeutsch (Schweiz), Deutsch (Deutschland), Deutsch (Deutschland), Australian English (Australia), Canadian English (Canada), British English (United Kingdom), American English (United States), English (South Africa), español (Argentina), español (Bolivia), español (Chile), español (Colombia), español (Costa Rica), español (Cuba), español (República Dominicana), español (Ecuador), español de España (España), español (Guatemala), español (Honduras), español de México (México), español (Nicaragua), español (Panamá), español (Perú), español (Puerto Rico), español (Paraguay), español (El Salvador), español (Estados Unidos), español (Uruguay), español (Venezuela), français, français (Belgique), français canadien (Canada), français suisse (Suisse), français (France), français (Luxembourg), français (Monaco), italiano (Svizzera), italiano (Italia), português (Brasil), português europeu (Portugal), русский (Россия)`
**Application dictionaries path**: `/home/alessandro/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `2`

### Note folder `default`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/alessandro/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/alessandro/Notes/notes.sqlite`

### Cloud connection ``

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `/home/alessandro/Notes.20211130`
**FileDialog/LastPath-ImportTextFiles** (QString): `/home/alessandro/Notes.20211130`
**FileDialog/LastPath-NoteMarkdownExport** (QString): `/home/alessandro/Notes`
**LastUpdateCheck** (QDateTime): `2021-11-30T17:49:55.299`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Monospace,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Ubuntu,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Monospace,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Ubuntu,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**NoteFolder-2/NoteTabNameList** (QString): `2FCOM_-_accounts`
**NoteFolder-2/NoteTabStickinessList**: *empty*
**NoteFolder-2/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteFolder-2/allowDifferentNoteFileName** (bool): `true`
**NoteHistory-2** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-2** (QString): `199`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `2`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**darkMode** (bool): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `1col`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `18`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/alessandro/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `0`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**recentNoteFolders**: *empty*
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-2** (QStringList): `COMMANDS`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Single column`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`
**LANGUAGE**: `en_US`
**USER**: `alessandro`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `1370`
**KIGITHUB**: `https://github.com/KiCad`
**SHLVL**: `0`
**HOME**: `/home/alessandro`
**DESKTOP_SESSION**: `cinnamon`
**GIO_LAUNCHED_DESKTOP_FILE**: `/usr/share/applications/PBE.QOwnNotes.desktop`
**GTK_MODULES**: `gail:atk-bridge`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**LC_MONETARY**: `it_IT.UTF-8`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**CINNAMON_VERSION**: `5.0.7`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `105379`
**QT_QPA_PLATFORMTHEME**: `qt5ct`
**LOGNAME**: `alessandro`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_ID**: `c2`
**GTK_OVERLAY_SCROLLING**: `1`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**PATH**: `/home/alessandro/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
**GDM_LANG**: `en_US`
**GTK3_MODULES**: `xapp-gtk3-module`
**SESSION_MANAGER**: `local/KKKKKK:@/tmp/.ICE-unix/1301,unix/KKKKKK:/tmp/.ICE-unix/1301`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**LC_ADDRESS**: `it_IT.UTF-8`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**DISPLAY**: `:0`
**LANG**: `en_US.UTF-8`
**LC_TELEPHONE**: `it_IT.UTF-8`
**XDG_CURRENT_DESKTOP**: `X-Cinnamon`
**XDG_SESSION_DESKTOP**: `cinnamon`
**XAUTHORITY**: `/home/alessandro/.Xauthority`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/alessandro`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**SHELL**: `/bin/bash`
**LC_NAME**: `it_IT.UTF-8`
**QT_ACCESSIBILITY**: `1`
**GDMSESSION**: `cinnamon`
**LC_MEASUREMENT**: `it_IT.UTF-8`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**LC_IDENTIFICATION**: `it_IT.UTF-8`
**GJS_DEBUG_OUTPUT**: `stderr`
**XDG_VTNR**: `7`
**PWD**: `/home/alessandro`
**KICAD_PATH**: `/usr/share/kicad`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-cinnamon:/etc/xdg`
**XDG_DATA_DIRS**: `/usr/share/cinnamon:/usr/share/gnome:/home/alessandro/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share`
**LC_NUMERIC**: `it_IT.UTF-8`
**LC_PAPER**: `it_IT.UTF-8`

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

[Nov 30 17:55:57] [warning]: "Removed log file: " "/home/alessandro/.local/share/PBE/QOwnNotes/QOwnNotes.log"
[Nov 30 17:56:01] [debug]: Set proxy configuration to use NO proxy
[Nov 30 17:56:05] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[Nov 30 17:56:05] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"" <serverUrl>"" <username>"" <priority>0
[Nov 30 17:56:05] [debug]: loadNoteDirectoryList
[Nov 30 17:56:05] [debug]: reloadTagTree
[Nov 30 17:56:05] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector()
[Nov 30 17:56:05] [debug]: reloadNoteSubFolderTree
[Nov 30 17:56:05] [debug]: loadNoteDirectoryList
[Nov 30 17:56:06] [debug]: reloadTagTree
[Nov 30 17:56:06] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(0)
[Nov 30 17:56:13] [debug]: storeSettings  - 'noteHistoryItem':  NoteHistoryItem: <noteName>"A_-_accounts" <noteSubFolderPathData>"" <cursorPosition>0 <relativeScrollBarPosition>0
[Nov 30 17:56:13] [debug]: storeSettings  - 'noteHistoryItem':  NoteHistoryItem: <noteName>"A_-_accounts" <noteSubFolderPathData>"" <cursorPosition>0 <relativeScrollBarPosition>0
[Nov 30 17:56:16] [Debug]: main  - 'locale':  "en"
[Nov 30 17:56:16] [Debug]: using qt5ct plugin
[Nov 30 17:56:16] [Debug]: Translation  "/usr/share/qt5/translations/QOwnNotes_en" in "" isLoaded: true , isInstalled: true
[Nov 30 17:56:16] [Debug]: Translation  "qt_en" in "/usr/share/qt5/translations" isLoaded: true , isInstalled: false
[Nov 30 17:56:16] [Debug]: Translation  "qt_en" in "/usr/bin/translations" isLoaded: false , isInstalled: false
[Nov 30 17:56:16] [Debug]: Translation  "/usr/bin/../src/languages/QOwnNotes_en" in "" isLoaded: false , isInstalled: false
[Nov 30 17:56:16] [Debug]: Translation  "/usr/bin/../languages/QOwnNotes_en" in "" isLoaded: false , isInstalled: false
[Nov 30 17:56:16] [Debug]: Translation  "/usr/bin/languages/QOwnNotes_en" in "" isLoaded: false , isInstalled: false
[Nov 30 17:56:16] [Debug]: Translation  "/usr/bin/QOwnNotes_en" in "" isLoaded: false , isInstalled: false
[Nov 30 17:56:16] [Debug]: Translation  "../src/languages/QOwnNotes_en" in "" isLoaded: false , isInstalled: false
[Nov 30 17:56:16] [Debug]: Translation  "../share/qt5/translations/QOwnNotes_en" in "" isLoaded: false , isInstalled: false
[Nov 30 17:56:16] [Debug]: Translation  "/usr/bin/../share/qt5/translations/QOwnNotes_en" in "" isLoaded: true , isInstalled: true
[Nov 30 17:56:16] [Debug]: Translation  "QOwnNotes_en" in "" isLoaded: false , isInstalled: false
[Nov 30 17:56:16] [Debug]: getDiskDatabasePath  - 'databaseFileName':  "/home/alessandro/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite"
[Nov 30 17:56:16] [Debug]: setupTables  - 'database_version':  40
[Nov 30 17:56:16] [Debug]:  HunspellClient::HunspellClient
[Nov 30 17:56:16] [Debug]:  SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_US"
[Nov 30 17:56:16] [Debug]: Loading dictionary for "en_US" from "/usr/share/hunspell"
[Nov 30 17:56:16] [Debug]: Created  0x557f0d61a750
[Nov 30 17:56:16] [debug]: Set proxy configuration to use NO proxy
[Nov 30 17:56:16] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[Nov 30 17:56:16] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"" <serverUrl>"" <username>"" <priority>0
[Nov 30 17:56:16] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[Nov 30 17:56:16] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Nov 30 17:56:16] [debug]: D-Bus system tray: yes
[Nov 30 17:56:16] [debug]: buildNotesIndex  - 'noteSubFolderId':  0
[Nov 30 17:56:16] [debug]: custom style sheet is disabled
[Nov 30 17:56:17] [info]: "QOwnNotes server listening on port 22222"
[Nov 30 17:56:17] [debug]: setupNoteFolderTables  - 'database version':  15
[Nov 30 17:56:17] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"" <serverUrl>"" <username>"" <priority>0
[Nov 30 17:56:17] [debug]: loadNoteDirectoryList
[Nov 30 17:56:17] [debug]: reloadTagTree
[Nov 30 17:56:17] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector()
[Nov 30 17:56:17] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Nov 30 17:56:17] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Nov 30 17:56:17] [debug]: loadNoteDirectoryList
[Nov 30 17:56:17] [debug]: reloadTagTree
[Nov 30 17:56:17] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector()
[Nov 30 17:56:17] [debug]: reloadNoteSubFolderTree
</details>

**Comment by pbek** [comment]
How many notes did you have?
Do you also get the crash with https://github.com/pbek/QOwnNotes/releases/download/v21.11.8/QOwnNotes-x86_64.AppImage?

**Comment by AlessandroPerazzetta** [comment]
Actually 266 notes.
Previous version probably 21.11.8 (not remember exact version from ppa:pbek/qownnotes) worked fine

**Comment by pbek** [comment]
Could you please download and test those two versions to narrow down your issue:

- https://github.com/pbek/QOwnNotes/releases/download/v21.11.8/QOwnNotes-x86_64.AppImage
- https://github.com/pbek/QOwnNotes/releases/download/v21.11.9/QOwnNotes-x86_64.AppImage

**Comment by AlessandroPerazzetta** [comment]
Tried latest appimage same behaviour (segmentation fault).
Tried 21.11.8 works fine
Tried 21.11.9 segmentation fault

**Comment by AlessandroPerazzetta** [comment]
Tried to start with 21.11.8 AppImage and directly update from inside the app to 21.11.14 and after restart segmentation fault

**Comment by pbek** [comment]
Thank you!

**Comment by pbek** [comment]
Seems like it's the same issue #2309 had.

**Comment by pbek** [comment]
One more thing. Can you please try to test again with 21.11.14 and turned off spellchecking?

**Comment by AlessandroPerazzetta** [comment]
> One more thing. Can you please try to test again with 21.11.14 and turned off spellchecking?

Tried to set false checkSpelling at .config/PBE/QOwnNotes.conf and crash at start (segfault).
Tested on 21.11.14 AppImage and ppa repository version on 2 differente installation.

**Comment by pbek** [comment]
Thank you. I'll try to get around that blindly.

## 21.12.0
- an attempt was made to fix a rare crash

**Comment by pbek** [comment]
Can you please try https://github.com/pbek/QOwnNotes/releases/download/v21.12.0/QOwnNotes-x86_64.AppImage.

**Comment by AlessandroPerazzetta** [comment]
> 

I can confirm that this version (AppImage and ppa repository) works without crashing with all previous notes.

**Comment by pbek** [comment]
Great, thank you for testing!
