### ISSUE TITLE
Documentation front page design

### ISSUE THREAD

**Issue by Fabijenna** [pbek/QOwnNotes#2320]
#### Expected behaviour
![Screenshot 2021-12-02 at 11 57 42](https://user-images.githubusercontent.com/17498644/144409835-84b6779b-0f65-41af-ace1-6c915ccc2efd.png)

#### Actual behaviour
![Screenshot 2021-12-02 at 11 57 24](https://user-images.githubusercontent.com/17498644/144409860-f1dc061d-6f2e-4fc4-b979-53d0e570fd56.png)

#### Steps to reproduce
Open http://qownnotes.org on a desktop computer.

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

Reason I post this, because it frequently occurs to me that it would be much nicer if the Quick Start button would appear upon opening the page, and not just after scrolling down. (Also some people might leave without scrolling down, idk.)

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by Fabijenna** [comment]
![Screenshot 2021-12-02 at 12 07 13](https://user-images.githubusercontent.com/17498644/144410901-94411a38-65a3-444c-9a84-901e444cfe7a.png)
![Screenshot 2021-12-02 at 12 07 06](https://user-images.githubusercontent.com/17498644/144410906-07371149-afbc-4b28-ae2e-4bc5d8dab56b.png)

**Comment by pbek** [comment]
So what is the difference that you are not expecting?

**Comment by Fabijenna** [comment]
Take a look at the pictures, please.

Can you spot the difference? 

I think the expected one looks better.

It's more "complete".

I am only speaking for my computer though.

**Comment by Fabijenna** [comment]
Oh, I must have written my comments in the wrong place so they're hidden in the markdown view.

**Comment by Fabijenna** [comment]
So, again.

I say that theQuick start is hidden now.

As expected / or prettier would be I could see the button at opening the website and wouldn't need to first scroll down to see, what is hiddenbelow.

The button should be visible at once.

Do you agree?

**Comment by Fabijenna** [comment]
It might be difficult for all kinds of computers to get that sucking in effect 

:-)

**Comment by pbek** [comment]
I cannot reproduce that. What browser(s) are you using? Do you have this issue on more browsers?

**Comment by Fabijenna** [comment]
Safari and Google Chrome

**Comment by pbek** [comment]
I can see the button on my 13" macBook in Chrome without scrolling. Maybe your viewport is smaller. But I still think that's no issue. That's the way browsers work, with a larger viewport you see more. 😅

**Comment by Fabijenna** [comment]
😂 ok 👌 thanx
