### ISSUE TITLE
[F] Consider #s before headers as masked syntax

### ISSUE THREAD

**Issue by FireFragment** [pbek/QOwnNotes#2321]
#### Expected behaviour

It would be nice, if there was an option in settings to consider `#`s preceeding atx-style headers as masked syntax and not as part of a header. 

It would allow to style `#`s differently, than the header itself.

#### Actual behaviour

As far as I know, there isn't any option to consider `#`s preceeding atx-style headers as masked syntax.

**Comment by pbek** [comment]
Can you please post some code examples and references who is using Markdown that way?

**Comment by FireFragment** [comment]
We currently have this:
![31](https://user-images.githubusercontent.com/55660550/144461843-2f78e947-f93f-43fa-90f1-1bca74203bb8.png)
I would like there was some way, to make theese `#`s gray.
Most of editors I know ([Abricotine](https://abricotine.brrd.fr/), [StackEdit](https://stackedit.io/), etc.) styles theese `#`s differently then the headers themselves.

**StackEdit:**
![32](https://user-images.githubusercontent.com/55660550/144463051-299d0080-c1f0-455c-9160-29436539699d.png)

**Comment by pbek** [comment]
@Waqar144, your opinion?

**Comment by pbek** [comment]
> Abricotine, StackEdit, etc

Haven't heard of them. The one I use (all JetBrains IDEs, VS Code, kate, ...) don't use masked syntax for the `#`s.
But that doesn't mean I oppose the idea per se...

**Comment by pbek** [comment]
Actually that even was a thing says:

![](https://raw.githubusercontent.com/pbek/QOwnNotes/develop/screenshots/screenshot.png)

@Waqar144, do you know why we stopped doing that?

**Comment by Waqar144** [comment]
It probably got lost during the rewrite of the highlighter. But I think it should be fairly easy to add it back. I did try to keep most of the masked syntaxes working, so there's likely code for it already, but probably not working for some reason

**Comment by pbek** [comment]
I'll use the "masked syntax" styling, but the size of the styling of the heading.
Looks like this:

<img width="182" alt="image" src="https://user-images.githubusercontent.com/1798101/144740129-e484a135-5a4f-42de-a27a-86cd66faec39.png">

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by FireFragment** [comment]
Works perfectly, thank you! 👍🏻

**Comment by pbek** [comment]
Great, thank you for testing!
