### ISSUE TITLE
Pasting text as attachment file

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#2327]
It would be great to be able to paste plain text as attachment file in the current note.

**Comment by pbek** [comment]
## 21.12.2
- you can now paste plain text from the clipboard into the note as text file
  attachment with <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>V</kbd>
  (for [#2327](https://github.com/pbek/QOwnNotes/issues/2327))
- links to attachments with extensions, that are used for notes are now opened
  externally instead of attempted to being opened as note (that doesn't exist)
  (for [#2327](https://github.com/pbek/QOwnNotes/issues/2327))

**Comment by szendi-attila** [comment]
This change overwrites the previous function of Ctrl + Shift + V and does not allow me to insert formatted text from the clipboard of the web browser! Any solution?

**Comment by pbek** [comment]
There are even more things that doesn't seem to work any more, for example dropping images into the edit panel. The reason is it seems Qt sees text in everything 🙈  I'll come up with a solution tomorrow.

**Comment by pbek** [comment]
## 21.12.3
- pasting of HTML as Markdown and dropping of images is now fixed again, and you
  can select if you want to paste HTML as Markdown or as text file attachment
  (for [#2327](https://github.com/pbek/QOwnNotes/issues/2327))
- opening of text file attachments now also works if note sub-folders are disabled
  (for [#2327](https://github.com/pbek/QOwnNotes/issues/2327))

There now is a new release, could you please test it and report if it works for you?

**Comment by szendi-attila** [comment]
Tested. It works perfectly! I have the image file in the media folder. I use QownNotes many hours a day. And the formatted text clipboard from the website. Thank you very much!

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by pbek** [comment]
And great that QOwnNotes is of use to you! 😁
