### ISSUE TITLE
kswapd0 spikes to 100% takes down entire server because NC /QOwnNotes sync error

### ISSUE THREAD

**Issue by yupthatguy** [pbek/QOwnNotes#2328]
#### Expected behaviour

Sync notes with NC via NC linux sync client

#### Actual behaviour

This cost me my entire weekend... ITS SEVERE... I hope someone reads this

Whether I use git version tracking or not, the NC linux client (AppImage  on Ubuntu 20.04) shows sync errors in the dialog gui when trying to sync Notes with the server.

Once that happens, on my web server `#top` shows that kswapd0 comes 100% of the CPU and disrupts every other service on the server, making the -ENTIRE- server unstable, unusable. I literally have to reboot the server, then quickly `#swapon -a && swapoff -a` in order to get my server back in functioning order.

Over this -ENTIRE- weekend (you, not happy)  I have painstakingly, tested all of my sync clients (Android, Ubuntu Native NC Sync, TBsync)... All of them work fine... However, the moment I open the NC sync client and it fails to sync notes...  the whole server gets whacked by kswapd0  consuming 100% of cpu.. 

#### Steps to reproduce
Enable git version tracking...
Generate sync error (somehow)
Open NC AppImage Linux sync client

`#top` output:

```
top - 21:48:29 up  9:40,  6 users,  load average: 76.96, 96.69, 92.90
Tasks: 274 total,   5 running, 268 sleeping,   0 stopped,   1 zombie
%Cpu(s):  2.3 us, 52.9 sy,  0.0 ni,  0.1 id, 44.7 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   3946.8 total,    105.9 free,   3755.2 used,     85.6 buff/cache
MiB Swap:   6144.0 total,      0.0 free,   6144.0 used.     17.0 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND           
   36 root      20   0       0      0      0 R  79.9   0.0 407:38.59 kswapd0           
11760 root      10 -10  116984   2264      0 D   2.7   0.1   5:08.48 AliYunDun         
30315 web2      20   0  912992 819892    868 D   1.1  20.3   0:11.34 clamscan          
27736 web2      20   0  957320 238868      0 D   0.7   5.9   0:17.25 clamscan          
  167 root      20   0    4556   2028   2028 S   0.7   0.1   4:22.09 plymouthd         
 1669 mysql     20   0 1764468   8788      0 S   0.7   0.2  29:23.99 mysqld            
 1568 root      20   0  805852    420      0 S   0.6   0.0   5:24.86 aliyun-service    
 2505 git       20   0 1374664   2020      0 D   0.6   0.0   6:51.61 gitea             
 4733 bind      20   0  263640   1712      0 S   0.4   0.0   1:13.41 named             
  871 root      20   0   23904    256      0 S   0.4   0.0   4:24.62 AliYunDunUpdate   
  184 root       0 -20       0      0      0 I   0.4   0.0   3:06.20 kworker/0:1H-kbl+ 
    1 root      20   0  172536    788    156 D   0.3   0.0   2:39.28 systemd           
 1002 root      20   0   85792    400      0 D   0.3   0.0   1:15.51 monit             
12631 root      20   0   55064    228      0 D   0.3   0.0   0:29.27 systemd-journal   
28707 web2      20   0  304788   5984   1188 D   0.3   0.1   0:05.83 php-fpm7.4   
```

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

[Dec 12 20:21:15] [debug]: Set proxy configuration to use NO proxy
[Dec 12 20:21:18] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Asiliyamama.com" <serverUrl>"https://asiliyamama.com" <username>"fathertime" <priority>1
[Dec 12 20:21:19] [debug]: Reply from  ""
[Dec 12 20:21:19] [debug]: Reply from main server url
[Dec 12 20:21:20] [debug]: Reply from  "/ocs/v1.php"
[Dec 12 20:21:20] [debug]: Reply from ownCloud test page
[Dec 12 20:21:20] [debug]: Reply from  "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[Dec 12 20:21:20] [debug]: Reply from app info
[Dec 12 20:21:20] [debug]: Reply from  "/ocs/v1.php/cloud/capabilities"
[Dec 12 20:21:20] [debug]: Reply from capabilities page
[Dec 12 20:21:21] [debug]: Set proxy configuration to use NO proxy
[Dec 12 20:21:25] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Asiliyamama.com" <serverUrl>"https://asiliyamama.com" <username>"fathertime" <priority>1
[Dec 12 20:21:25] [debug]: Reply from  ""
[Dec 12 20:21:25] [debug]: Reply from main server url
[Dec 12 20:21:26] [debug]: Reply from  "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[Dec 12 20:21:26] [debug]: Reply from app info
[Dec 12 20:21:26] [debug]: Reply from  "/ocs/v1.php"
[Dec 12 20:21:26] [debug]: Reply from ownCloud test page
[Dec 12 20:21:26] [debug]: Reply from  "/ocs/v1.php/cloud/capabilities"
[Dec 12 20:21:26] [debug]: Reply from capabilities page
[Dec 12 20:22:00] [debug]: Set proxy configuration to use NO proxy
[Dec 12 20:22:02] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Asiliyamama.com" <serverUrl>"https://asiliyamama.com" <username>"fathertime" <priority>1
[Dec 12 20:22:06] [debug]: Reply from  ""
[Dec 12 20:22:06] [debug]: Reply from main server url
[Dec 12 20:22:07] [debug]: Reply from  "/ocs/v1.php/cloud/capabilities"
[Dec 12 20:22:07] [debug]: Reply from capabilities page
[Dec 12 20:22:08] [debug]: Reply from  "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[Dec 12 20:22:08] [debug]: Reply from app info
[Dec 12 20:22:08] [debug]: Reply from  "/ocs/v1.php"
[Dec 12 20:22:08] [debug]: Reply from ownCloud test page

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

None

</details>

Three questions:
1.) what is the best way to resolve the git notes sync error?
2.) what is the best way to resolve the note sync error, in general? (git switched off)
3.) I'm new to linux server admin, how can I mitigate / prevent a simple sync error from causing kswapd0 from spiking to 100% cpu usage and taking down my whole server?

I like the app, but this weekend has not been fun... 

thx in advance

**Comment by pbek** [comment]
Are you sure you are in the right issue tracker? Do you have an issue with QOwnNotes or with the Nextcloud Desktop Sync client (https://github.com/nextcloud/desktop/issues)?

**Comment by yupthatguy** [comment]
Sorry if I am in the wrong tracker... Its just with the qownnotes sync api... wasn;t sure which tracker to post to ... figured I would cover all possible options ... 
https://i.imgur.com/bW0LZnL.png

**Comment by pbek** [comment]
The qownnotesapi doesn't sync 😉

**Comment by yupthatguy** [comment]
got it.. my bad... thanks for the pointer in the right direction. Love the app... hate this weekend.

**Comment by pbek** [comment]
Thank you! Good luck with finding the issue! And keep your spirit high!
