### ISSUE TITLE
Get path and name of current note from shell

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#233]
I'm putting part of the script that would paste part of web page (with images and stuff) selected in web browser as a markdown to currently opened note. So one can compose note by repeatedly selecting interesting page sections and pushing a keystroke. For now it works only for predefined note file.

I'm trying getting path and name of the app's current note from shell. 

My first thought was getting it from in-app script but I've read that QML is hard at passing anything to shell. It's usually done by passing data from QML to C++ part and then out.

I found the only place where the app shows current note name to the outside world - it's window title. So I've put up the script that finds the file named like the one in the window title. The problem is I can have more than one such file.

Could you implement the way to get current note full path and file name.

I think the best way it can be done is by implementing in-app script (or no script) function that output that data to environment shell variable or file (maybe to QOwnNotesrc in config dir).

**Comment by pbek** [comment]
I've tried to set an environment variable with `putenv` and `setenv` but neither was readable from the same terminal where QOwnNotes was started.

**Comment by Maboroshy** [comment]
Maybe QOwnNotesrc then. I could parse it every script activation.

**Comment by Maboroshy** [comment]
I've googled for a variable way, and everybody confirm that there's no way to export variable from a child process which is cpp in our case. 

Writing to file looks like an easy solution. But I don't think that writing something to disk on every note change is a good. It better be in RAM not on disk. 

But all that bash can get from RAM other than variables is quite exotic... 

Maybe stdout of the app? For now it's almost empty.

Don't know what is the best practice of exporting app data to the outside world. There should be some.

**Comment by pbek** [comment]
Until a good and easy way to do this doesn't come to my knowledge I will close this issue. Please let me know if you find something.
