### ISSUE TITLE
Feature request: Follow the Editor cursor on Navigation panel

### ISSUE THREAD

**Issue by quicktrick** [pbek/QOwnNotes#2331]
Could you do this as in VSCode? When I put the cursor on a line in Editor, the highlight on Navigation panel selects the corresponding section?  This is a very needed feature.

**Comment by pbek** [comment]
Like here? #2136

**Comment by quicktrick** [comment]
Sort of like that.  See [here](https://youtu.be/PpLyVv8BG3k) how it works in VSCode. There's a Follow Cursor option that you can enable/disable.

**Comment by pbek** [comment]
Is there a difference to #2136? Can't see any... 😅

**Comment by quicktrick** [comment]
> Is there a difference to #2136?

I have just read it carefully. It looks like there is no difference, you are right.

**Comment by pbek** [comment]
Ok, thank you 😁  (there's a video too)
