### ISSUE TITLE
QOwnNotes Web Companion browser extension

### ISSUE THREAD

**Issue by apopticon** [pbek/QOwnNotes#2332]
Hi -

Using the browser extension version 2021.10.0 on Brave browser. Finding this really useful! Mostly I want to just save bookmarks to QOwnNotes. 

Is there (or could there be) a hotkey for the browser extension to just add the URL to QOwnNotes. It's not even a choice on the context menu. Currently the context menu offers two choices:  "Send page to QOwnNotes" and "Create note with screenshot of visible page".  But a hotkey would be excellent!

#### Expected behaviour
Hit a hotkey, and the bookmark would be added to QOwnNotes.

#### Actual behaviour
To add the bookmark requires that you find the icon for QOwnNotes in the browser toolbar, click it to open the window, click the Plus button, click Save, then click the Close button.

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Can you please open that in https://github.com/qownnotes/web-companion/issues

**Comment by pbek** [comment]
And I'm not sure if background like https://github.com/qownnotes/web-companion/blob/3a96a8cdc81b5553d0ab1f39b9150bbd022b68ae/app/scripts/background.js#L250 jobs can even have shortcuts, have you seen an extension (with source code) doing that?
