### ISSUE TITLE
Please, add "Collapse all" option to the Navigation panel

### ISSUE THREAD

**Issue by quicktrick** [pbek/QOwnNotes#2334]
I apologize for the repetition, I have seen similar requests in #1978, #1912, etc. But since my notes contain up to 10,000 lines and a couple of hundred headings, this option is quite important to me. Please make such an option in the interface and in shortcuts. Thanks in advance!

**Comment by pbek** [comment]
The issue isn't that a "collapse all" can't be implemented, the issue is that the state of the collapsing can't be saved anywhere because the markdown file gets parsed constantly and can completely change at any time and note metadata will not really be saved anywhere... 😬

**Comment by quicktrick** [comment]
I understand everything. But the interface is supposed to be user-friendly, not developer-friendly, isn't it? :)

**Comment by pbek** [comment]
Implemented in https://github.com/pbek/QOwnNotes/issues/1912
