### ISSUE TITLE
Do not run a search before entering at least three characters

### ISSUE THREAD

**Issue by quicktrick** [pbek/QOwnNotes#2335]
Please do not run a search until the user has entered at least 3 characters. On large files, entering the first and second character in the search string gives a huge delay.

**Comment by pbek** [comment]
What search are we talking of? The search in for notes or the search in notes?

**Comment by quicktrick** [comment]
I'm sorry.  Search in the editor.

**Comment by pbek** [comment]
I'm pretty fond on searching single special characters.

On a 200k text file (but I'd never use such large notes, I split mine up in smaller files and link to them) the first character takes about 300ms. No delay on the 2nd. I wouldn't call that huge. How large are your notes and why do you like them so large?

**Comment by pbek** [comment]
And a lot of improvements were already done in #1985.

**Comment by quicktrick** [comment]
My biggest files are about 350-400k. The first character search takes about 3s. The second one is much faster, maybe those 300ms you mentioned.

Why are my files so big? It is convenient for me when all the information on one topic is placed in one file. A lot of small files, in my opinion, is worse, because there is confusion as to where to look for what. These are not my biggest files yet, I have other text files around 2MB, but I don't use them in QON.

**Comment by fnkhz** [comment]
Created a PR, if this is to be integrated.
In case this is to be integrated, for consistency, the note search should have a similar behavior maybe.

**Comment by pbek** [comment]
This needs discussion first, please see https://github.com/pbek/qmarkdowntextedit/pull/147#issuecomment-1003935882.

**Comment by Waqar144** [comment]
> My biggest files are about 350-400k. The first character search takes about 3s. The second one is much faster, maybe those 300ms you mentioned. Entering the first character gives too many matches, and it takes a long time to display them. CPU i-9 10850, 32GB, Windows 10.
> 
> Why are my files so big? It is convenient for me when all the information on one topic is placed in one file. A lot of small files, in my opinion, is worse, because there is confusion as to where to look for what. These are not my biggest files yet, I have other text files around 2MB, but I don't use them in QON.

Generally speaking seraching even a 1MB file (which is tiny), for a single char shouldn't take even 10ms. So, I will try to see where exactly are we slowing down and fix it.

**Comment by Waqar144** [comment]
Just checked why its slow, it searches everything 3 times so... :/

**Comment by pbek** [comment]
## 22.1.4
- for notes with more than 200k characters the in-note search will now wait for 250ms
  before showing the search result, so users have time to enter more search characters
  (for [#2335](https://github.com/pbek/QOwnNotes/pull/2335), thank you @fnkhz)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by quicktrick** [comment]
@pbek 

I don't really use QON anymore, I switched to VSCode. But I downloaded and tried version 22.1.4. Unfortunately, nothing has changed. Entering the first character still takes about 3s before the results are displayed. And during that time I can't enter the second character. Sorry.

**Comment by pbek** [comment]
> for notes with more than 200k characters the in-note search will now wait for 250ms
before showing the search result, so users have time to enter more search characters

@quicktrick, thank you for testing. So did you enter a 2nd character within 250ms? 😅

**Comment by quicktrick** [comment]
@pbek 

Oh, I'm sorry, I really didn't enter the second character right away.  If I enter it all at once, it works correctly. But if I then delete the second character, I have to wait for 3s before I can delete the first character.

**Comment by pbek** [comment]
Thank you for testing. 😁

**Comment by quicktrick** [comment]
@pbek

I think you can use asynchronous mode so that the interface is not blocked while the search is working.

**Comment by pbek** [comment]
I'm still open for PRs...

**Comment by pbek** [comment]
> I'm still open for PRs...

But most likely you want to do them in https://github.com/pbek/qmarkdowntextedit.
And in case you thought QOwnNotes is a web application... No, it's not. 😁

**Comment by quicktrick** [comment]
> And in case you thought QOwnNotes is a web application... No, it's not.

No, I didn't think so. For example, look [here](https://stackoverflow.com/questions/34284750/how-async-task-doesnt-block-ui), or [here](https://stackoverflow.com/questions/34284750/how-async-task-doesnt-block-ui).

**Comment by pbek** [comment]
QOwnNotes is written in C++ (with Qt), not C#. 😉

**Comment by quicktrick** [comment]
> QOwnNotes is written in C++ (with Qt), not C#

I understand that. But you can try to implement it in C++. However, it is your choice how to do what.  I am not entitled to give advice.

**Comment by Waqar144** [comment]
It doesn't matter what language it's written in, async execution is available in pretty much every widely used language.

This is why I opposed this solution, because it fixes nothing. Expecting a user to type quickly to be able to do things quickly is just broken. And make it configurable is even worse since it computers vary in execution speed and what you set once may not work very well the next time you search.

**Comment by pbek** [comment]
It's needs only one line of code to be turned off when there is a better solution. 😉 
https://github.com/pbek/QOwnNotes/commit/bb6ac887eb9a8b03b4fc18a069be2552c156b5d2#diff-4e23ca16d7623fa610040e84472562d48c505743ff2ef879f548c97040f00edbR462

**Comment by Waqar144** [comment]
Better solution? That's not a solution. 250ms? Imo, That's just arbitrary and adding more hacks on top of it isn't going to make things better. 200K is super small, it should no time to begin with.

**Comment by fnkhz** [comment]
I will do this asynchronously tomorrow and see how this works; will also fix the double search.

**Comment by Waqar144** [comment]
@fnkhz Some suggestions from me if you are trying:
- Try to make it fast enough first before making it async.
- Triple search is one big bottleneck
- Searching via textEdit is slow, the least that could be done is to search via the document interface instead.

I did a quick and dirty experiment by changing above things a couple of days back so if you want to test, I can push the code somewhere. One can also check for e.g how qt creator performs on documents of the same size and if its faster would be interesting to see what it does under the hood.

**Comment by Waqar144** [comment]
Also, imo the issue should not be closed

**Comment by Waqar144** [comment]
Also, @pbek maybe remove me from the https://www.qownnotes.org/contributing/maintainers.html since I apparently can't even reopen issues :shrug:

**Comment by pbek** [comment]
> Better solution? That's not a solution. 250ms? Imo, That's just arbitrary and adding more hacks on top of it isn't going to make things better. 200K is super small, it should no time to begin with.

No, I neither consider it a solution. It's a hack so users that are currently affected are able to type in more characters without having to wait too long. I don't like this hack. And it will be removed when there is **a** solution.

> Also, imo the issue should not be closed

I don't really like the issue `Do not run a search before entering at least three characters`, it suggests that the solution should be to not run the search until there are 3 characters, don't you think?

> Also, @pbek maybe remove me from the https://www.qownnotes.org/contributing/maintainers.html since I apparently can't even reopen issues

I'm looking periodically if GitHub already allows to assign permissions to the issue tracker, because I'd love not to be the only one who is able to do issue triaging... But there still doesn't seem to be a way.
Why don't we just open a new issue? Name it as you desire.

**Comment by Waqar144** [comment]
> I'm looking periodically if GitHub already allows to assign permissions to the issue tracker, because I'd love not to be the only one who is able to do issue triaging... But there still doesn't seem to be a way.

You can actually if you wanted, but its *your* project only I guess.
