### ISSUE TITLE
QOwnNotes on Windows 7 - 32 bit ?

### ISSUE THREAD

**Issue by rshalaev** [pbek/QOwnNotes#2337]
Is there a 32 bit version of QOwnNotes for Windows 7?

- Regarding OS Version - Installation page mentions Windows XP support, so I assume Windows 7 would be supported.
https://www.qownnotes.org/installation/windows.html

Regarding 32 bit support - window pre-build zip binary on GitHub only contains 64 bit executable/libs.
* Are there 32 bit binaries available?
* If not, would it be possible to compile QOwnNotes 32 bit version for Windows 7 manually?
* Is 32bit/Windows 7 supported, or was supported in earlier versions?

Help much appreciated!
Thank you

**Comment by pbek** [comment]
The latest Qt 5.15 still should support Windows 7 says https://doc.qt.io/qt-5/supported-platforms.html.
So you could either use the 32bit build (with the older Qt Version) for Windows XP or build it yourself (see https://www.qownnotes.org/installation/building.html)

**Comment by rshalaev** [comment]
Thank you for the quick feedback! Will try out the XP build. Merry Christmas!

**Comment by pbek** [comment]
Merry Christmas to you too! 😁 🎄
