### ISSUE TITLE
Using (some) fixed width fonts disables formatting of strong

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#2338]
It seems that using (some) fixed width fonts as default font disables formatting `**strong**` text.

Variable width font:
![image](https://user-images.githubusercontent.com/5956570/147269181-ffcbf429-8dbb-4e35-8cfa-7c17b0f93980.png)

Fixed width font:
![image](https://user-images.githubusercontent.com/5956570/147269231-3437eacf-66b4-4b54-afe7-efd0fe009f91.png)

Tested with Noto Mono, SF Mono, Jetbrains Mono and Monospace (only the latter renders correctly).

Change of Color schema does not seem to matter.

Version: `qownnotes 21.11.14-1`

**Comment by pbek** [comment]
Do those fonts even have a bold type?

**Comment by sanderboom** [comment]
Seems so:

```console
λ fc-list |grep SF-Mono |grep Bold
/usr/share/fonts/apple/SF-Mono-BoldItalic.otf: SF Mono:style=Bold Italic
/usr/share/fonts/apple/SF-Mono-SemiboldItalic.otf: SF Mono:style=Semibold Italic
/usr/share/fonts/apple/SF-Mono-Semibold.otf: SF Mono:style=Semibold
/usr/share/fonts/apple/SF-Mono-Bold.otf: SF Mono:style=Bold
λ fc-list |grep jetbrains |grep Bold |wc -l
12
```

KDE Font Management: 

- ![image](https://user-images.githubusercontent.com/5956570/147277246-f073eb23-f0af-4456-8939-01d95eb71f98.png)
- ![image](https://user-images.githubusercontent.com/5956570/147277284-8bec6217-2185-4d25-87b6-451347a8bab9.png)

Can I test this in a better way?

**Comment by pbek** [comment]
Hm, even if I give it the maximum boldness Qt offers in `Utils::Schema::Settings::setFormatStyle` it doesn't look bold in certain fonts. Seems like an issue in QPlainTextEdit. 😬

**Comment by Waqar144** [comment]
> Hm, even if I give it the maximum boldness Qt offers in `Utils::Schema::Settings::setFormatStyle` it doesn't look bold in certain fonts. Seems like an issue in QPlainTextEdit. 😬

Tried dropping the style of the font?

```
font.setStyleName(Qstring())
```

**Comment by pbek** [comment]
> Tried dropping the style of the font?

wtf, why did that fix the issue!? should that make sense!? 🤣

**Comment by pbek** [comment]
We'll give it a try...

## 22.1.2
- an issue with rendering "bold" really bold in the note edit panel when the default font
  is monospaced was fixed

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Waqar144** [comment]
> > Tried dropping the style of the font?
> 
> wtf, why did that fix the issue!? should that make sense!? 🤣

I think it's something to do with style names and how qt loads fonts. I came across this working on Kate and that's how I learned ;p

**Comment by pbek** [comment]
Thank you very much!

**Comment by sanderboom** [comment]
Awesome, it works now - thanks @Waqar144 & @pbek!

**Comment by pbek** [comment]
Great, thank you for testing! 😉
