### ISSUE TITLE
Tags from Joplin are not imported

### ISSUE THREAD

**Issue by pcause** [pbek/QOwnNotes#2344]
When I imported my joplin notes the tags were not imported.  Since the docs don't say they are not I assume they are supposed to be imported.

**Comment by pbek** [comment]
Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.

Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting Debug in Options).

Do you have an example Joplin export directory to import?

**Comment by pcause** [comment]
this was my error.  i did an export to a jex file and then unzipped and imported instead of doing a raw export from joplin.  closing this but other issue is still a problem.
