### ISSUE TITLE
[suggestion] document HTML comment tag as another way to add a comment

### ISSUE THREAD

**Issue by pcause** [pbek/QOwnNotes#2346]
I tired and an html comment tag:

can be used in the app.  It isn't displayed in the preview.  I suggest adding this to the docs as it is more portable to other markdown editors.

**Comment by pbek** [comment]
It already is: https://www.qownnotes.org/getting-started/markdown.html#comments

**Comment by pcause** [comment]
sorry, the light grey in the example makes it easy to miss
