### ISSUE TITLE
importing text file doesn't preserve line breaks

### ISSUE THREAD

**Issue by pcause** [pbek/QOwnNotes#2347]
I import a text file where each line ends in a newline.  It looks fine in the editor panel but is all wrapped in the preview panel.  Since when you import you create the imported file as oldname.md, shouldn't you fix things so that line endings where it is a newline followed by a character that isn't a newline is converted into 2 spaces and a newline?

Also, if I add txt as a recognized file extension in the General setting, could we have an option to import the file with the same extension?  This would allow me to manage text files under QOwnNotes but still preserve that they are just a txt file for other apps.  You would have to have save also preserve the .txt extension.

**Comment by pbek** [comment]
Can you please describe step by step what you did along with providing an example file?
Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.
