### ISSUE TITLE
import into non-default notes folder doesn't import tags

### ISSUE THREAD

**Issue by pcause** [pbek/QOwnNotes#2348]
started with a clean install of QOwnNotes.   Import a couple of files into "default".  I add a new notes folder.  Switch to the folder and import exported Joplin notes.  The notes are imported but the tags are not.  They do not appear at all.  Further I can't seem to add tags to the items.

If I delete the newly created notes folder and am now back to my original default folder I can import the same Joplin export and all the tags are created and match the notes.

EDIT:  The new notes folder is located in a different part of the filesystem

**Comment by pbek** [comment]
I cannot reproduce that.
Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.
Do you have example files?

**Comment by pbek** [comment]
I imported the notes from https://github.com/pbek/QOwnNotes/issues/2343 and was able to see the assigned `#covid` tags.

**Comment by pcause** [comment]
i reproduced using the same joplin export i shared for the yaml problem.  I have posted the debug info in the other issue as well.  Will see if I can get log while repeating

**Comment by pcause** [comment]
I installed the latest on linux and also windows.  the import worked on linux but not on windows.  In both cases I created a new folder in a different directory, switched to that folder, and then did the import.  on linux all tags are there but none on windows.

**Comment by pbek** [comment]
I imported the notes from #2343 under Windows 10 and e.g. `rom-hair-salons-to-gyms-experts-rank-36-activities-by-coronavirus-risk-level` had the tag `#covid`.

**Comment by pcause** [comment]
seems fixed in 22.1.3
