### ISSUE TITLE
Feature request. More convinient attached files management

### ISSUE THREAD

**Issue by kv-gits** [pbek/QOwnNotes#2354]
Now all attachments are placed in the same directory. Would like option to place files for note in special subdirectory near this note.
Example:
.../some/dir/goodnote.md
.../some/dir/goodnote_attachments/goodfile.pdf

And also dock panel for viewing/opening attached files list for current note with posibility to open explorer in that directory.

Thanks for good software!

**Comment by pbek** [comment]
I don't see that coming any time soon, it was already a huuuge amount of work to be able to do this the way it is with all the things that have to work together (e.g. when notes are moved or copied) and without storing any meta data about attachments...

Although there is a non-modal dialog to manage and insert attachments from your attachments folder...
And of course you can put attachments anywhere you like and manage them yourself.

**Comment by kv-gits** [comment]
I found there is way to place link to any file in any folder. It is rather good and no need additional features.

But non-modal dialog shows only files from main attachments directory. May be it is possible to make dock panel to manage list of links (e.g. only local) of current active note - open them, or open in explorer etc. Seems there is no much work to do that and it is pretty portable.

**Comment by pbek** [comment]
> But non-modal dialog shows only files from main attachments directory.

Of course it does 😁 

> May be it is possible to make dock panel to manage list of links (e.g. only local) of current active note - open them, or open in explorer etc. Seems there is no much work to do that and it is pretty portable.

It would be pretty hard to reliably detect all kind of urls and non-urls and all ways they can be used in markdown reliably or are you talking about "QOwnNotes attachments"?

**Comment by kv-gits** [comment]
> or are you talking about "QOwnNotes attachments"?

Yes, about them. Or all links of "file://" type.

**Comment by pbek** [comment]
Using absolute links like `file://` is "not suggested" since they will only work on your computer with your current directory structure... 😉 

Maybe the *Stored attachment* dialog could have an option to just view attachments of the current note. But then this feature would also have to be integrated in the media dialog...

**Comment by kv-gits** [comment]
Ok, I understand now, that it is little out of QON scope. I just use it with syncthing, so have no such sync issues.

**Comment by pbek** [comment]
> I just use it with syncthing, so have no such sync issues.

What sync issues are we talking about? Attachments?

**Comment by kv-gits** [comment]
I mean this "since they will only work on your computer with your current directory structure... 😉"

**Comment by pbek** [comment]
## 24.10.1
- In the *Stored image files* and the *Stored attachments* dialogs it's now possible
  to only show files of the current note (for [2354](https://github.com/pbek/QOwnNotes/issues/2354))
