### ISSUE TITLE
When I enable "instead of a note list, use a note tree" otion i lose subnote actions on right click

### ISSUE THREAD

**Issue by pcause** [pbek/QOwnNotes#2355]
I have a new, clean install.  I turn on "Instead of a note list option"

![image](https://user-images.githubusercontent.com/1071479/147880252-30852c1e-ad61-4fe3-bcf8-9caa0d396578.png)

I create a subfolder

![image](https://user-images.githubusercontent.com/1071479/147880264-cac68f71-7ef6-4f55-a4c2-6b6bef2bdc2b.png)

when I right click a note there are no sub-folder action as there are with this off

![image](https://user-images.githubusercontent.com/1071479/147880290-6499eb13-6702-4e92-8d1b-f40510439e5d.png)

turned off and get this

![image](https://user-images.githubusercontent.com/1071479/147880353-42b31b74-ca5d-42ae-919d-f67109658039.png)

Know it says work in progress. so just reporting in case you didn't know of this

**Comment by pbek** [comment]
Like shown in the screenshot, that feature is "work in progress", please see https://github.com/pbek/QOwnNotes/issues/790.

**Comment by pcause** [comment]
thanks

**Comment by DarrenSchwartz** [comment]
I think this issue should be reopened because the context munu options are still not shown in the tree view mode. Specifically, the move, copy, and jump to subfolder options are missing.  

# Tree view
![image](https://user-images.githubusercontent.com/33355526/173237352-2b17645e-2fdf-4aae-a389-426d74500d0b.png)
# Separate notes view
![image](https://user-images.githubusercontent.com/33355526/173237439-18abb650-7d12-4db6-8b68-36dd6f308395.png)

**Comment by pbek** [comment]
There already is a feature request for the whole "note tree" feature (work in progress!): #790

**Comment by DarrenSchwartz** [comment]
Understood, thanks. Just wanted to capture the specific bug around moving notes. Looks like the other thread does cover it though.

**Comment by pbek** [comment]
It is no "bug". It was simply not implemented yet...

**Comment by pbek** [comment]
## 22.6.2
- the note actions for notes in subfolders are now enabled in the note tree context
  menu if the "note tree mode" is enabled (for [#2355](https://github.com/pbek/QOwnNotes/issues/2355))

There now is a new release, could you please test it and report if it works for you?

**Comment by DarrenSchwartz** [comment]
![image](https://user-images.githubusercontent.com/33355526/176007876-8855935a-e21a-4b49-86d6-60b37a9f754f.png)

**Comment by pbek** [comment]
Something seems to be amiss with the Qt libraries under Windows, I had to pull the release back. See #2558.

**Comment by pbek** [comment]
## 22.7.0
- the build system for Windows was fixed again (for [#2558](https://github.com/pbek/QOwnNotes/issues/2558))

There now is a new release, could you please test it and report if it works for you?
