### ISSUE TITLE
Newly created bookmark note not shown 

### ISSUE THREAD

**Issue by pcause** [pbek/QOwnNotes#2356]
I use the web clipper and select bookmark all tabs.  In the app I don't see the Bookmark note at all.  If it hit refresh the folder the bookmark note appears.

**Comment by pbek** [comment]
Maybe your operating system blocks some filesystem events (the note folder normally should refresh when a file that is not watched is changed)... But links are added to the file, aren't they? Are you able to create more bookmarks with the browser extension?

**Comment by pcause** [comment]
yes, the note is there and bookmarks are added.  others are added.  I am on Win11.
