### ISSUE TITLE
[suggestion] open file target

### ISSUE THREAD

**Issue by pcause** [pbek/QOwnNotes#2357]
I'd like the "open with" in Windows to be able to open a file in QOwnNotes.  Looking at the commend line arguments if the app is started with an argument that doesn't have "--" you could assume it is a file name and tru to open and then import into current workspace.

**Comment by pbek** [comment]
That sounds like a pretty niche use-case. 😁  And it would need another argument to select a note folder to do that with and some handling when the file already exists or isn't a text file at all.

**Comment by Waqar144** [comment]
out of scope I'd say since QOwnNotes isn't a text editor and can't open a file directly and probably doesn't even need to.
