### ISSUE TITLE
does it can Instant preview ?

### ISSUE THREAD

**Issue by jesson3264** [pbek/QOwnNotes#2360]
If I insert one image, how can I preview it instantly.

**Comment by pbek** [comment]
Can you please describe step by step what you did and what you were expecting?
Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.

**Comment by jesson3264** [comment]
I want show the jpg in position of the red rectangle.
![image](https://user-images.githubusercontent.com/76934455/147994408-a3a6314a-f2e7-4f5e-8b62-c180344e113e.png)

**Comment by pbek** [comment]
Sorry, that isn't possible in the editor.

**Comment by pbek** [comment]
But you can ctrl+click or ctrl+space the image to open it
