### ISSUE TITLE
FEATURE REQUEST: Tabbed view

### ISSUE THREAD

**Issue by jackal7163** [pbek/QOwnNotes#2366]
Is it possible to get a tabbed view?  I used KeyNote and RightNote for many years and have gotten used to using tabs to segregate personal notes from business notes and various different projects and journals.  Wine is too buggy to continue using Windows software at this time and this is a feature that I seriously need. 

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Just double click on a note in the note list or use the right-click menu entry.
