### ISSUE TITLE
Managing Tasks doesn't work with Nextcloud 9.0.50

### ISSUE THREAD

**Issue by Paulikid** [pbek/QOwnNotes#237]
When I try to load my calendar list inside of QOwnNotes nothing happens. I am using the default calendar backend in the current version of Nextcloud, the default tasks app in Nextcloud is also activated.

**Comment by pbek** [comment]
Last time I checked it worked for me. Could you create me a test account on the server where it doesn't work?

**Comment by Paulikid** [comment]
I just created the test account. How do I send you the link, username and password?

**Comment by Paulikid** [comment]
I just noticed that I have failures after checking the code integrity of QOwnNotesAPI. It seems that the file I downloaded doesn't contain all files (I downloaded it from the link at apps.owncloud.com, not from github). I would have to download the files from github, All files that my installation shows "missing" are included in there. I guess that causes the issue. For now I resign using the tasks management function. I will try out when I have more time, atm I am to busy to try out.

**Comment by pbek** [comment]
For tasks you don't need QOwnNotesAPI.
What did you download? The file from <https://apps.owncloud.com/content/download.php?content=173817&id=1&tan=97970866>? There shouldn't anything be missing there, ownCloud itself created the package.

**Comment by Paulikid** [comment]
Without installed QOwnNotesAPI I am not able to choose a folder where my notes should be stored in QOwnNotes, I always get an error that no connection to my server could be established and I have to recheck my owncloud configuration inside QOwnNotes.
Yes, i downloaded the package from the link you posted. Very strange: after activating Versioning in Nextcloud I have to log off, maintenance mode starts and reconfigures the database. When I log in again I get Code Integrity errors in Nextcloud. The details page shows me missing files, e.g. ".travis.yml" or ".gitignore" and some more. These files are included in "qownnotesapi-develop.zip", but not in the package I downloaded from the link you mentioned.

**Comment by pbek** [comment]
> Without installed QOwnNotesAPI I am not able to choose a folder where my notes should be stored in QOwnNotes

yes, that's true, but that folder has nothing to do with tasks :)

the package on apps.owncloud.com was created with `make appstore_package`, it looks like that the command doesn't update the `info.xml` accordingly so it works right with signed packages... 

will be the same problem as in #238 
I will take care of that

**Comment by pbek** [comment]
@Paulikid I now re-did the app signing, can you please test again

**Comment by Paulikid** [comment]
I did the update to Nextcloud 9.0.52 just an hour ago and added qownnotesapi again. No more code integrity check errors. Thank you very much.

**Comment by pbek** [comment]
Thank you for testing. Any news on the task issues?

**Comment by Paulikid** [comment]
No news on this, still doesn't work. I just saw that User LightTemplar had the same issue (#229) and it looks like he couldn't fix it either by himself. If you are still interested I could add a test account for you on my server...

**Comment by pbek** [comment]
Thank you.
As in #229 I was able to connect to your server and create tasks in the default calendar (I tested on OS X).
Could you please post the output from the debug tab in the settings?

**Comment by Paulikid** [comment]
Here it is:

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sa. Juli 9 08:42:08 2016`  
**Version**: `16.07.3`  
**Build date**: `Jul  6 2016`  
**Build number**: `194`  
**Platform**: `linux`  
**Operating System**: `Arch Linux`  
**Build architecture**: `x86_64`  
**Current architecture**: `x86_64`  
**Release**: `AUR`  
**Qt Version (build)**: `5.7.0`  
**Qt Version (runtime)**: `5.7.0`  
**Locale (system)**: `de_DE`  
**Locale (interface)**: *empty*  
**Icon theme**: `breeze-dark-qownnotes`  
**Notes in current note folder**: `2`  
**Enabled scripts**: `0`  

## Server Info

**serverUrl**: `https://***/owncloud`  
**appIsValid**: `yes`  
**serverVersion**: `9.0.52.0`  
**appVersion**: `0.4.4`  

## Note folders

**currentNoteFolderId**: `1`  

### Standard

**id**: `1`  
**activeTagId**: `0`  
**localPath**: `/***/***/Notes`  
**remotePath**: `Notes`  

## Settings

**LastUpdateCheck**: `2016-07-09T08:41:57`  
**LogDialog/showAtStartup**: `false`  
**MainWindow/geometry**: `<binary data>`  
**MainWindow/mainToolBar.iconSize**: `22`  
**MainWindow/menuBarGeometry**: `<binary data>`  
**MainWindow/noteTextEdit.code.font**: `Courier,9,-1,5,50,0,0,0,0,0`  
**MainWindow/noteTextEdit.font**: `Sans Serif,9,-1,5,50,0,0,0,0,0`  
**MainWindow/noteTextView.code.font**: `Courier,9,-1,5,50,0,0,0,0,0`  
**MainWindow/noteTextView.font**: `,9,-1,5,50,0,0,0,0,0`  
**MainWindow/showRecentNoteFolderInMainArea**: `true`  
**MainWindow/windowState**: `<binary data>`  
**PiwikClientId**: `<hidden>`  
**ShowSystemTray**: `true`  
**SortingModeAlphabetically**: `false`  
**allowDifferentNoteFileName**: `false`  
**allowOnlyOneAppInstance**: `true`  
**appMetrics/disableAppHeartbeat**: `false`  
**appMetrics/disableTracking**: `true`  
**appMetrics/notificationShown**: `true`  
**cryptoKey**: `<hidden>`  
**currentNoteFolderId**: `1`  
**customNoteFileExtensionList**: *empty*  
**darkMode**: `true`  
**darkModeColors**: `true`  
**defaultNoteFileExtension**: `txt`  
**demoNotesCreated**: `true`  
**disableAutomaticUpdateDialog**: `false`  
**externalEditorPath**: *empty*  
**ignoreAllExternalModifications**: `true`  
**interfaceLanguage**: *empty*  
**mainSplitterSizes**: `<binary data>`  
**mainSplitterState-0-0-1-0**: `<binary data>`  
**mainSplitterState-0-1-1-0**: `<binary data>`  
**markdownHighlightingInterval**: `200`  
**markdownViewEnabled**: `false`  
**networking/ignoreSSLErrors**: `false`  
**networking/proxyType**: `2`  
**noteListSplitterState**: `<binary data>`  
**noteSaveIntervalTime**: `10`  
**notesPath**: `/***/***/Notes`  
**notifyAllExternalModifications**: `false`  
**ownCloud/password**: `<hidden>`  
**ownCloud/serverUrl**: `https://paulikid.de/owncloud`  
**ownCloud/todoCalendarBackend**: `0`  
**ownCloud/todoCalendarEnabledList**: *empty*  
**ownCloud/todoCalendarEnabledUrlList**: *empty*  
**ownCloud/todoCalendarUrlList**: *empty*  
**ownCloud/userName**: `Paulikid`  
**savedSearches/noteFolder-1**: `Note 2016-07-03T21.51.18, Note 2016-07-03T21.47.20, Note 2016-07-03T21.41.24, Note 2016-07-03T13.43.35, Note 2016-07-03T13.42.39`  
**showStatusBar**: `true`  
**tagFrameSplitterState**: `<binary data>`  
**verticalNoteFrameSplitterState**: `<binary data>`

**Comment by Paulikid** [comment]
When I create another test user I am able to connect to the server and obtain the calendar list (default calendar with that user.

**Comment by pbek** [comment]
Frankly, I have no idea. QOwnNotes did tell you your username and password are valid before you changed to the test user, right? Were you able to fetch the list of calendars in the `Todo` tab in the settings at that time?

**Comment by Paulikid** [comment]
Yes, the username and password of my default user were shown valid, but nothing happended when I tried to fetch the calendar list. After switching to my test user it worked instantly and after switching back to my default user it also worked for this account. Very strange, I have no idea what went wrong all the time, I haven't changed anything in my server's configuration. Thank you very much for your efforts, it's working now. I will delete the test account.

**Comment by pbek** [comment]
Ok thank you, I also wonder what happened...

**Comment by pbek** [comment]
If you still have this problem or get it again, please visit [My calendars cannot be fetched from my ownCloud server](http://www.qownnotes.org/Knowledge-base/My-calendars-cannot-be-fetched-from-my-ownCloud-server).
