### ISSUE TITLE
[I] Ctrl + Click on markdown image does no longer open the image in an image viewer

### ISSUE THREAD

**Issue by armbruer** [pbek/QOwnNotes#2371]
#### Expected behaviour

By pressing Ctrl + Click on ![press_here](relative_file_link) markdown images in previous versions (~1-2 weeks ago) I was able to open my image viewer with the image opened

#### Actual behaviour

Nothing happens

#### Steps to reproduce

1. Create a note
2. Take a screenshot and copy paste it into the qownnotes editor field
3. Ctrl+Click on the markdown version of the screenshot

The actual image file is created in the media folder and is shown in the preview.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fri Jan 7 10:39:53 2022`
**Version**: `22.1.4`
**Build date**: `Jan  6 2022`
**Build number**: `935`
**Platform**: `linux`
**Operating System**: `openSUSE Tumbleweed`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/home/eric/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/eric/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`, `-session`, `106531340000164154691500000026040024_1641547214_525706`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `Fluent-dark`
**Notes in current note folder**: `16`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: 
**appIsValid**: `no`
**notesPathExists**: `unknown`
**connectionErrorMessage**: `

## Spellchecking

**Enabled**: `true`
**Selected language**: `en_US`
**Language codes**: `en_US`
**Language names**: `American English (United States)`
**Application dictionaries path**: `/home/eric/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/eric/ga27vaw/notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/eric/ga27vaw/notes/notes.sqlite`

### Cloud connection 

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `
**username**: 
**accountId**: *empty*

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**Font_-1000** (QFont): `,10,-1,5,50,0,0,0,0,0`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2022-01-07T10:21:52.628`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Hack,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Hack,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `true`
**NoteFolder-1/NoteTabNameList** (QString): `Machine Learning and Security`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteHistory-1** (QVariantList): `<variant list with 9 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `8`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `24`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/eric/ga27vaw/notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): `Host cloud.armbruster-online.de not found`
**ownCloudInfo/notesPathExistsText** (QString): `unknown`
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `TODO, Note 2021-10-27T10.12.04`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `en_US`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**AUDIODRIVER**: `pulseaudio`
**CONFIG_SITE**: `/usr/share/site/x86_64-unknown-linux-gnu`
**CPU**: `x86_64`
**CSHEDIT**: `emacs`
**CVS_RSH**: `ssh`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**DEBUGINFOD_URLS**: `https://debuginfod.opensuse.org/ `
**DESKTOP_SESSION**: `/usr/share/xsessions/default`
**DISPLAY**: `:0`
**FROM_HEADER**: *empty*
**GTK2_RC_FILES**: `/etc/gtk-2.0/gtkrc:/home/eric/.gtkrc-2.0:/home/eric/.config/gtkrc-2.0`
**GTK_IM_MODULE**: `ibus`
**GTK_MODULES**: `canberra-gtk-module`
**GTK_RC_FILES**: `/etc/gtk/gtkrc:/home/eric/.gtkrc:/home/eric/.config/gtkrc`
**G_BROKEN_FILENAMES**: `1`
**G_FILENAME_ENCODING**: `@locale,UTF-8,ISO-8859-15,CP1252`
**HISTSIZE**: `1000`
**HOME**: `/home/eric`
**HOST**: `e14`
**HOSTNAME**: `e14`
**HOSTTYPE**: `x86_64`
**INPUT_METHOD**: `ibus`
**JAVA_BINDIR**: `/usr/lib64/jvm/jre-openjdk/bin`
**JAVA_HOME**: `/usr/lib64/jvm/jre-openjdk`
**JAVA_ROOT**: `/usr/lib64/jvm/jre-openjdk`
**JRE_HOME**: `/usr/lib64/jvm/java-11-openjdk-11`
**KDE_APPLICATIONS_AS_SCOPE**: `1`
**KDE_FULL_SESSION**: `true`
**KDE_SESSION_UID**: `1000`
**KDE_SESSION_VERSION**: `5`
**LANG**: `en_US.UTF-8`
**LESS**: `-M -I -R`
**LESSCLOSE**: `lessclose.sh %s %s`
**LESSKEY**: `/usr/etc/lesskey.bin`
**LESSOPEN**: `lessopen.sh %s`
**LESS_ADVANCED_PREPROCESSOR**: `no`
**LOGNAME**: `eric`
**MACHTYPE**: `x86_64`
**MAIL**: `/var/spool/mail/eric`
**MANPATH**: `/home/eric/.local/share/man:/usr/local/man:/usr/share/man`
**MANPATHISSET**: `yes`
**MINICOM**: `-c on`
**MORE**: `-sl`
**OLDPWD**: `/home/eric`
**OSTYPE**: `linux-gnu`
**PAGER**: `less`
**PATH**: `/home/eric/.local/bin:/home/eric/bin:/usr/local/bin:/usr/bin:/bin`
**PROFILEREAD**: `true`
**PWD**: `/home/eric`
**PYTHONSTARTUP**: `/etc/pythonstart`
**QEMU_AUDIO_DRV**: `pa`
**QT4_IM_MODULE**: `xim`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**QT_IM_MODULE**: `ibus`
**QT_IM_SWITCHER**: `imsw-multi`
**SHELL**: `/bin/zsh`
**SHLVL**: `0`
**SSH_AGENT_PID**: `1964`
**SSH_ASKPASS**: `/usr/libexec/ssh/ssh-askpass`
**SSH_AUTH_SOCK**: `/tmp/ssh-XXXXXXTTHKIy/agent.1891`
**SYSTEMD_EXEC_PID**: `1882`
**TERM**: `xterm`
**USER**: `eric`
**WINDOWMANAGER**: `/usr/bin/startplasma-x11`
**XAUTHLOCALHOSTNAME**: `e14`
**XAUTHORITY**: `/run/user/1000/xauth_OnMjak`
**XCURSOR_SIZE**: `24`
**XCURSOR_THEME**: `Fluent-cursors`
**XDG_CONFIG_DIRS**: `/home/eric/.config/kdedefaults:/etc/xdg:/usr/etc/xdg`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_DATA_DIRS**: `/home/eric/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/share`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_SEAT**: `seat0`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_DESKTOP**: `KDE`
**XDG_SESSION_ID**: `1`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**XDG_SESSION_TYPE**: `x11`
**XDG_VTNR**: `7`
**XKEYSYMDB**: `/usr/X11R6/lib/X11/XKeysymDB`
**XMODIFIERS**: `@im=ibus`
**XNLSPATH**: `/usr/share/X11/nls`
**XSESSION_IS_UP**: `yes`
**SESSION_MANAGER**: `local/e14:@/tmp/.ICE-unix/2253,unix/e14:/tmp/.ICE-unix/2253`
</details>

**Comment by pbek** [comment]
Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting Debug in Options).

Do you remember when that worked?

**Comment by pbek** [comment]
Bisected my way through it... @Waqar144, #2365 breaks opening images in the editor.

**Comment by pbek** [comment]
Thank you for reporting, @armbruer!

**Comment by pbek** [comment]
## 22.1.5
- opening images from the note edit was fixed (for [#2371](https://github.com/pbek/QOwnNotes/issues/2371), thank you @Waqar144)

**Comment by armbruer** [comment]
Thank you @pbek and @Waqar144 for the quick response and solving this so quickly. Can confirm this solves the issue for me.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
