### ISSUE TITLE
[I] Crashes when spell check tries to correct a word

### ISSUE THREAD

**Issue by Moonl1ghter** [pbek/QOwnNotes#2377]
Edit: Sorry for the broken English below, wrote it in a hurry.

When a word is wrongly spelled and you correct it, it should correct the word to the correct one.

#### Actual behaviour

When a word is misspelled, and you try to correct it with the build in spell checker (aspell or hunspell) the application crashes.

#### Steps to reproduce

Install QOwNotes from the AUR.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[12:02:13] [debug] updatePanelMenu - 'updatePanelMenu'

Info: "QOwnNotes server listening on port 22222" ((null):0, (null))
Warning: Missing trigrams for languages: QSet("en_SG", "en_BW", "en_JM", "nl_AW", "en_BZ", "en_IE", "nl_BE", "en_NG", "en_ZA", "en_NA", "en_ZW", "en_TT", "en_AG", "en_HK", "en_NZ", "en_IN", "en_DK", "en_GH", "en_BS") ((null):0, (null))
fish: Job 1, 'QOwnNotes' terminated by signal SIGSEGV (Address boundary error)
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `to Jan 13 12:02:35 2022`
**Version**: `22.1.6`
**Build date**: `Jan 12 2022`
**Build number**: `937`
**Platform**: `linux`
**Operating System**: `Arch Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/home/ronnie/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/ronnie/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `111`
**Calendar items**: `6`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://nextcloud.moonlighter-server.eu`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `20.0.14.2`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_AG, en_BS, en_BW, en_BZ, en_DK, en_GB, en_GB-large, en_GH, en_HK, en_IE, en_IN, en_JM, en_NA, en_NG, en_NZ, en_SG, en_TT, en_US, en_US-large, en_ZA, en_ZW, nl_AW, nl_BE, nl_NL`
**Language names**: `English (Antigua & Barbuda), English (Bahamas), English (Botswana), English (Belize), English (Denmark), British English (United Kingdom), British English (United Kingdom) [large], English (Ghana), English (Hong Kong SAR China), English (Ireland), English (India), English (Jamaica), English (Namibia), English (Nigeria), English (New Zealand), English (Singapore), English (Trinidad & Tobago), American English (United States), American English (United States) [large], English (South Africa), English (Zimbabwe), Nederlands (Aruba), Nederlands (België), Nederlands (Nederland)`
**Application dictionaries path**: `/home/ronnie/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/ronnie/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**allowDifferentNoteFileName**: `yes`
**activeNoteSubFolder name**: `Research Project 1`
**database file**: `/home/ronnie/Nextcloud/Notes/notes.sqlite`

### Cloud connection `moonlighter-server`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://nextcloud.moonlighter-server.eu`
**username**: `Ronald`
**accountId**: *empty*

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2022-01-13T12:01:33.844`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Tech, Studie, Studie/Masterclasses`
**MainWindow/noteTextEdit.code.font** (QString): `Fira Code,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Fira Code,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Noto Sans,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**NoteFolder-1/NoteTabNameList** (QString): `Meeting 12-01`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QString): 
```
Studie
Research Project 1
```
**NoteFolder-1/allowDifferentNoteFileName** (QString): `true`
**NoteHistory-1** (QVariantList): `<variant list with 37 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `36`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `0`
**TodoDialog/showDueTodayItemsOnly** (QString): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Tasks`
**VersionDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**darkMode** (QString): `false`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**interfaceStyle** (QString): `kvantum-dark`
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `33`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/ronnie/Nextcloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList** (QString): `Tasks`
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList** (QString): `https://nextcloud.moonlighter-server.eu/remote.php/dav/calendars/Ronald/start-studie/`
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `20.0.14.2`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2022-01-12T11.15.29, Note 2022-01-12T10.52.44, Note 2022-01-10T16.36.32, Note 2022-01-10T16.36.13, Note 2022-01-04T13.43.06, Note 2021-11-30T14.24.50, Note 2021-11-30T14.24.49, Note 2021-11-30T14.24.44, Note 2021-11-25T11.22.00, Note 2021-11-17T14.09.32, Note 2021-11-17T14.08.17`
**showMatches** (QString): `true`
**showMenuBar** (bool): `false`
**showStatusBar** (bool): `true`
**spellCheckBackend** (QString): `Hunspell`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**versionSplitterSizes** (QByteArray): `<binary data>`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**SHELL**: `/bin/fish`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**DESKTOP_SESSION**: `plasma`
**GTK_MODULES**: `canberra-gtk-module:appmenu-gtk-module`
**XDG_SEAT**: `seat0`
**PWD**: `/home/ronnie`
**XDG_SESSION_DESKTOP**: `KDE`
**LOGNAME**: `ronnie`
**XDG_SESSION_TYPE**: `x11`
**XAUTHORITY**: `/home/ronnie/.Xauthority`
**MOTD_SHOWN**: `pam`
**MANGOHUD**: `1`
**HOME**: `/home/ronnie`
**LANG**: `en_US.UTF-8`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**USER**: `ronnie`
**DISPLAY**: `:0`
**SHLVL**: `1`
**XDG_VTNR**: `1`
**UBUNTU_MENUPROXY**: `1`
**XDG_SESSION_ID**: `2`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**MAIL**: `/var/spool/mail/ronnie`
**LC_TIME**: `fy_NL.UTF-8`
**LC_MONETARY**: `fy_NL.UTF-8`
**LC_MEASUREMENT**: `fy_NL.UTF-8`
**XCURSOR_THEME**: `breeze_cursors`
**XCURSOR_SIZE**: `24`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**KDE_FULL_SESSION**: `true`
**KDE_SESSION_VERSION**: `5`
**KDE_SESSION_UID**: `1000`
**KDE_APPLICATIONS_AS_SCOPE**: `1`
**XDG_CONFIG_DIRS**: `/home/ronnie/.config/kdedefaults:/etc/xdg`
**SYSTEMD_EXEC_PID**: `830`
**GTK_RC_FILES**: `/etc/gtk/gtkrc:/home/ronnie/.gtkrc:/home/ronnie/.config/gtkrc`
**GTK2_RC_FILES**: `/etc/gtk-2.0/gtkrc:/home/ronnie/.gtkrc-2.0:/home/ronnie/.config/gtkrc-2.0`
**SESSION_MANAGER**: `local/archlinux-desktop:@/tmp/.ICE-unix/1178,unix/archlinux-desktop:/tmp/.ICE-unix/1178`
</details>

**Comment by pbek** [comment]
@Waqar144, I can reproduce this!

**Comment by pbek** [comment]
Possibly a regression from #2373.

**Comment by pbek** [comment]
## 22.1.7
- a crash when correcting a misspelled word was fixed (for [#2377](https://github.com/pbek/QOwnNotes/issues/2377), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Moonl1ghter** [comment]
@pbek  @Waqar144 
Just finished rebuilding it, works flawlessly now! Thank you for the quick fix, and also thank you for the great tool! Use it daily and has become quite essential for my studies.

**Comment by pbek** [comment]
Great, thank you for reporting and testing! 😉
