### ISSUE TITLE
[website] Shortcuts' key labels

### ISSUE THREAD

**Issue by noureddin** [pbek/QOwnNotes#2379]
(Context: I'm currently translating QOwnNotes' website into Arabic. The [shortcuts](https://www.qownnotes.org/getting-started/shortcuts.html) page used to detone the Shift key with <kbd>⇧</kbd> only. After I pointed out that this may be confused for <kbd>Up</kbd> by some readers, and is inconsistent with Linux and Windows who use the word "Shift" instead, it was changed to <kbd>⇧ Shift</kbd>.)

Regarding the arrow in the Shift key label on the shortcuts page, I appreciate that you introduced the word "Shift" in the label and didn't rely only on the arrow symbol. I, at first, re-translated all shortcuts with the arrow and word ("⇧ Shift"), exactly like the new label. But shortly afters I decided to go back to using the word only.

My primary reason for this is that the arrow symbol is "direction-less", so it can easily change its place if not surrounded by LTR characters on both sides. Examples include "⇧ Shift+F3" and "⌘ + ⇧ Shift + …". (At least "⌘ + Shift + E" appearing as "Shift + E + ⌘" in Arabic text is not an issue, but "Shift + E ⇧ + ⌘" is just very confusing, even if you know the rules.)

My secondary reason is that KDE actually uses only the word, "Shift", no arrows or anything. And also Windows uses (or at least used) the word only.

macOS on the other hand apparently prefers the concise "⌃⇧Q" for "Ctrl+Shift+Q": https://nektony.com/wp-content/uploads/2019/10/apple-menu.png & https://support.apple.com/en-us/HT201236
So I suggest we either use "<kbd>Cmd</kbd> + <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>N</kbd>" or "<kbd>⌘</kbd><kbd>⌃</kbd><kbd>⇧</kbd><kbd>N</kbd>" for the macOS section, regardless of the style used in other sections.

Also, KDE uses "PgUp" and "PgDown". I decided to use the full, space-less "PageUp" and "PageDown". 😅

**Comment by pbek** [comment]
While researching which notation to use I finally decided to use the same notation like https://en.wikipedia.org/wiki/Shift_key, which is `⇧ Shift`.
The same goes for page up/down: https://en.wikipedia.org/wiki/Page_Up_and_Page_Down_keys

**Comment by pbek** [comment]
> ⇧ Shift

The problem with just using one of the two characters is that more advanced users would only recognize `Shift` and less experienced users wouldn't even know what a `Shift` key is... 😅

**Comment by noureddin** [comment]
(Sorry for the late reply.)

OK. I'll translate all shift keys with `<kbd style="white-space: nowrap" dir="ltr">⇧ Shift</kbd>` then — this is how it's defined in Wikipedia (especially in the Arabic Wikipedia). 😁

And I'll use `<kbd style="white-space: nowrap" dir="ltr">Page Up</kbd>` and `<kbd style="white-space: nowrap" dir="ltr">Page Down</kbd>`, too.
(You still have two strings using "Page Dn". 😅)

I think I should also mention that I translate the arrow keys with the Arabic words, following the convention of KDE.

And I'm also "translating" <kbd>Return</kbd> with the English word <kbd>Enter</kbd>, literally, as this key is commonly referred to as "Enter" in Arabic (its translation, «مفتاح الإدخال», is little used, although generally known).

Remains only the macOS shortcuts. I suggest following the same style as the shift key: `⌘ Cmd`, `⌃ Ctrl` (that's `U+2303 UP ARROWHEAD`), and `⌥ Alt` (all surrounded by `<kbd style="white-space: nowrap" dir="ltr">` and `</kbd>`). That should apply only to the macOS section.

**Comment by pbek** [comment]
>  (You still have two strings using "Page Dn". sweat_smile)

thank you, fixed!

You decide about the Arabic string! 😅 

I updated the macOS shortcuts and am doing the kbd styling globally via css now.

**Comment by noureddin** [comment]
Thank you! :blush: 

I think this should be closed now, as all the issues were addressed (shift, page up & page down, mac shortcuts, and even kbd styling).
