### ISSUE TITLE
[Post questions] noteDirectoryWatcher watch files

### ISSUE THREAD

**Issue by clevertension** [pbek/QOwnNotes#2386]
in source code, i find that noteDirectoryWatcher watch all note in noteList, but i think it is better to only watch the opened note, so the performance can be better

**Comment by pbek** [comment]
All notes are mirrored inside the in-memory sqlite database, so they need to be watched (plus the note folder and the note sub-folders)... (see MainWindow::updateNoteDirectoryWatcher).
