### ISSUE TITLE
Missing context menu item(s) for folders? At least 'create new note'.

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#2387]
#### Expected behaviour

Right-click on a folder shows (at least) option to create a new note in that folder.

#### Actual behaviour

It does not show this option.

IIRC this was available in the application before I upgraded to the current version running: `qownnotes 22.1.7-1`

**Comment by pbek** [comment]
> IIRC this was available in the application before I upgraded to the current version running: qownnotes 22.1.7-1

really? what version was that?

@Waqar144?

**Comment by pbek** [comment]
I just bisected it... The menu entry is missing since https://github.com/pbek/QOwnNotes/commit/f9071e44abceb33a6d72aad4ab935b37fd4f45f8, @Waqar144.

**Comment by Waqar144** [comment]
Seems like you are close to a fix ;)

**Comment by pbek** [comment]
Not yet, I just found the commit yet that broke it. 😅

**Comment by pbek** [comment]
## 22.1.8
- the missing `New note` context menu entry in the note sub-folder panel was
  added again

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by sanderboom** [comment]
It's back! :+1:
