### ISSUE TITLE
In settings the font editor doesn't take the font style 

### ISSUE THREAD

**Issue by LightTemplar** [pbek/QOwnNotes#239]
As I open the font editor, it selects just the first style instead of that, what is in settings now. 
![image](https://cloud.githubusercontent.com/assets/453783/16709704/5e03b4a8-4618-11e6-9d3d-c6211231f991.png)

**Comment by pbek** [comment]
Thank you for reporting, but I wasn't able to reproduce that. It worked fine for me. Could you please post the debug output.

**Comment by pbek** [comment]
And which of the four fonts were you changing in your screenshot?

**Comment by LightTemplar** [comment]
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `So. Juli 10 10:00:35 2016`  
**Version**: `16.07.3`  
**Build date**: `Jul  6 2016`  
**Build number**: `194`  
**Platform**: `linux`  
**Operating System**: `Ubuntu 16.04 LTS`  
**Build architecture**: `x86_64`  
**Current architecture**: `x86_64`  
**Release**: `Launchpad PPA`  
**Qt Version (build)**: `5.5.1`  
**Qt Version (runtime)**: `5.5.1`  
**Locale (system)**: `en_GB`  
**Locale (interface)**: `en`  
**Icon theme**: `oxygen`  
**Notes in current note folder**: `74`  
**Enabled scripts**: `0`  

## Server Info

**serverUrl**: `https://temple.ocloud.de`  
**appIsValid**: `no`  
**connectionErrorMessage**: `Unknown error`  

## Note folders

**currentNoteFolderId**: `6`  

### default

**id**: `1`  
**activeTagId**: `-1`  
**localPath**: `/media/alexander/DATA/oc_test/Notes`  
**remotePath**: `Notes`  

### OCloud.de

**id**: `3`  
**activeTagId**: `-1`  
**localPath**: `/media/alexander/DATA/Data/temple.ocloud.de/Notes`  
**remotePath**: `Notes`  

### Goals

**id**: `4`  
**activeTagId**: `-1`  
**localPath**: `/media/alexander/DATA/Data/temple.ocloud.de/Notes/Goals`  
**remotePath**: `Notes/Goals`  

### Diary

**id**: `5`  
**activeTagId**: `-1`  
**localPath**: `/media/alexander/DATA/Data/temple.ocloud.de/Notes/Diary`  
**remotePath**: `Notes/Diary`  

### Projects

**id**: `6`  
**activeTagId**: `0`  
**localPath**: `/media/alexander/DATA/Projects`  
**remotePath**: *empty*  

## Settings

**DistractionFreeMode/isEnabled**: `false`  
**DistractionFreeMode/mainSplitterSizes**: `<binary data>`  
**DistractionFreeMode/menuBarGeometry**: `<binary data>`  
**DistractionFreeMode/menuBarHeight**: `32`  
**DistractionFreeMode/windowState**: `<binary data>`  
**LastUpdateCheck**: `2016-07-10T09:59:59`  
**LogDialog/showAtStartup**: `false`  
**MainWindow/geometry**: `<binary data>`  
**MainWindow/mainToolBar.iconSize**: `22`  
**MainWindow/menuBarGeometry**: `<binary data>`  
**MainWindow/noteTextEdit.code.font**: `Andale Mono,12,-1,0,50,0,0,0,0,0`  
**MainWindow/noteTextEdit.font**: `Noto Sans,15,-1,0,50,0,0,0,0,0`  
**MainWindow/noteTextView.code.font**: `Andale Mono,12,-1,0,50,0,0,0,0,0`  
**MainWindow/noteTextView.font**: `Noto Sans,12,-1,0,50,0,0,0,0,0`  
**MainWindow/showRecentNoteFolderInMainArea**: `true`  
**MainWindow/windowState**: `<binary data>`  
**PiwikClientId**: `<hidden>`  
**ShowSystemTray**: `false`  
**SortingModeAlphabetically**: `false`  
**allowDifferentNoteFileName**: `false`  
**allowOnlyOneAppInstance**: `false`  
**appMetrics/disableAppHeartbeat**: `false`  
**appMetrics/disableTracking**: `false`  
**appMetrics/notificationShown**: `true`  
**cryptoKey**: `<hidden>`  
**currentNoteFolderId**: `6`  
**customNoteFileExtensionList**: *empty*  
**darkMode**: `false`  
**darkModeColors**: `true`  
**defaultNoteFileExtension**: `txt`  
**demoNotesCreated**: `true`  
**disableAutomaticUpdateDialog**: `false`  
**externalEditorPath**: *empty*  
**ignoreAllExternalModifications**: `false`  
**interfaceLanguage**: `en`  
**mainSplitterSizes**: `<binary data>`  
**mainSplitterState-0-1-1-0**: `<binary data>`  
**mainSplitterState-1-1-0-0**: `<binary data>`  
**mainSplitterState-1-1-1-0**: `<binary data>`  
**markdownHighlightingInterval**: `200`  
**networking/ignoreSSLErrors**: `false`  
**networking/proxyType**: `2`  
**noteEditPaneEnabled**: `true`  
**noteListSplitterState**: `<binary data>`  
**noteSaveIntervalTime**: `10`  
**notesPath**: `/media/alexander/DATA/Projects`  
**notifyAllExternalModifications**: `false`  
**ownCloud/password**: `<hidden>`  
**ownCloud/serverUrl**: `https://temple.ocloud.de`  
**ownCloud/todoCalendarBackend**: `0`  
**ownCloud/todoCalendarEnabledList**: *empty*  
**ownCloud/todoCalendarEnabledUrlList**: *empty*  
**ownCloud/todoCalendarUrlList**: *empty*  
**ownCloud/userName**: `templar`  
**recentNoteFolders**: `/media/alexander/DATA/Data/temple.ocloud.de/Notes/Diary, /media/alexander/DATA/oc_test/Notes, /media/alexander/DATA/Data/temple.ocloud.de/Notes/Goals, /media/alexander/DATA/Data/temple.ocloud.de/Notes, /media/alexander/DATA/oc_test/Notes/Tesst`  
**savedSearches/noteFolder-1**: `Note 2016-07-02T12.59.43, Note 2016-06-23T18.15.14, Note 2016-06-18T20.36.54, Note 2016-06-18T18.54.06, Note 2016-06-15T12.40.17, Note 2016-06-15T11.45.02, Note 2016-06-11T16.53.12`  
**savedSearches/noteFolder-3**: `Goal Template, test`  
**savedSearches/noteFolder-4**: `Note 2016-06-23T12.26.35`  
**savedSearches/noteFolder-5**: `Note 2016-07-02T23.04.06, Note 2016-07-02T22.59.48, Note 2016-07-02T12.05.54, Note 2016-07-01T23.50.49, Note 2016-07-01T09.37.06, Note 2016-07-01T01.05.08, Note 2016-06-30T17.00.02, Note 2016-06-30T16.58.53, Note 2016-06-26T13.28.56, Note 2016-06-26T12.11.22, Note 2016-06-25T11.25.59, Note 2016-06-24T13.29.35, Note 2016-06-23T14.09.32, Note 2016-06-23T12.53.55, Note 2016-06-23T12.43.44`  
**savedSearches/noteFolder-6**: `Note 2016-07-09T22.45.53, Note 2016-07-09T20.44.02, Note 2016-07-01T16.15.47`  
**showStatusBar**: `true`  
**skipVersion**: `16.06.12`  
**tagFrameSplitterState**: `<binary data>`  
**tagsEnabled**: `true`  
**verticalNoteFrameSplitterState**: `<binary data>`

**Comment by LightTemplar** [comment]
It occurs by changing all Noto Sans fonts, as for Andale Mono there is only one Font Style. It doesn't matter, where the font is applied, in edits or views.

**Comment by pbek** [comment]
So you were changing the default note text edit font. If you click the font button you should see Noto Sans with size 15, what do you see in the font dialog?

**Comment by LightTemplar** [comment]
I expect, that the font style will be "regular", but it happens to be "bold italic".

**Comment by LightTemplar** [comment]
I changed the font size and was wondering, that the style became "Bold Italic" though I hadn't changed it.

**Comment by pbek** [comment]
Now I see what you mean! I hope that's not a QFontDialog bug, I will see what I can you about that. Thank you for reporting!

**Comment by pbek** [comment]
I tested a lot and couldn't fix that problem with the dialog. I now posted the question at: <https://forum.qt.io/topic/69152/qfontdialog-getfont-doesn-t-use-correct-font-style>

**Comment by LightTemplar** [comment]
Wow, I didn't expect to find a bug in Qt =)

**Comment by pbek** [comment]
After some days of testing and IRCing I was able to make a better example here: <https://forum.qt.io/topic/69348/qfontdialog-getfont-doesn-t-use-correct-font-style-when-font-of-the-font-parameter-use-tostring-and-fromstring>

**Comment by pbek** [comment]
Seems like we are affected by this bug: <https://bugreports.qt.io/browse/QTBUG-52741>
I guess we will have to wait...
