### ISSUE TITLE
Mousewheel zooming or right-clicking on the logging panel crashes application

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#2391]
@Waqar144, mouse-wheel zooming in the logging panel crashes the application.
Seems like a regression from https://github.com/pbek/QOwnNotes/commit/c48eae67c5b8173846288faddc0d3d5197b31dd6.

**Comment by pbek** [comment]
I even got a crash now while typing your name in a note... 😅  That's a sign...

**Comment by pbek** [comment]
Right-clicking in the panel also crashes the application!

**Comment by Waqar144** [comment]
Does the log panel need to be a QMarkdownEdit?

**Comment by pbek** [comment]
It uses features of QOwnNotesMarkdownTextEdit, like searching.

**Comment by Waqar144** [comment]
Anything other than searching?

**Comment by pbek** [comment]
It uses the same styling, settings, zooming, so yes.

**Comment by Waqar144** [comment]
So basically it doesn't really need to be a QMarkdowntextedit.

**Comment by Waqar144** [comment]
Just use QPlainTextEdit there and integerate the search.

**Comment by pbek** [comment]
And all settings, theming, zooming, etc.? Isn't that a lot of code duplication?

**Comment by pbek** [comment]
## 22.1.9
- potential crashes in the logging panel were fixed (for [#2391](https://github.com/pbek/QOwnNotes/issues/2391), thank you @Waqar144)
