### ISSUE TITLE
Prompt to enable note editing should also appear on paste

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#2397]
#### Expected behaviour
Show: 
![image](https://user-images.githubusercontent.com/5956570/150356046-17851ad1-838d-468e-934a-f302a0023e03.png)

when attempting to paste in protected note.

#### Actual behaviour
Dialog does not show,

#### Steps to reproduce
Disable note-editiing. Paste.

Version: `qownnotes 22.1.8-1`

**Comment by pbek** [comment]
## 22.1.9
- <kbd>Ctrl</kbd> + <kbd>V</kbd> now also triggers the dialog to enable note editing

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
