### ISSUE TITLE
Enter key dos not go to new paragraph in markdown

### ISSUE THREAD

**Issue by SBaldrick** [pbek/QOwnNotes#2398]
Hello,

I seem to have a problem with the enter key in markdown. In markdown pannel, the behaviour is normal (New line). But in the preview pannel, it looks like the "paragraph" key has not been hit, all is queued on the same line. 

I can show you a screen cap if necessary.

Thanks for your help

**Comment by pbek** [comment]
A newline in markdown isn't a line break in html (the preview). Only a new paragraph will do that (2 newlines).
Or you can enter two spaces at the end of the line (`Shift + Enter` will do that for you).

**Comment by pbek** [comment]
Also see: https://www.qownnotes.org/getting-started/markdown.html#line-breaks

**Comment by SBaldrick** [comment]
That seems to have done the trick perfectly ! Thank you !!

Although the markdown guide (your link) does say : "One newline will get you a new line in the same paragraph" which was what I'm going for. But maybe there's a subtlety there that I don't see, I'm new at this :p

**Comment by pbek** [comment]
You are right, I have no idea what that means. I'll rewrite that. Thank you.

**Comment by pbek** [comment]
> **Two newlines** will get you a **new paragraph**.

Or maybe the old markdown2html library did exactly that... 🤔

**Comment by noureddin** [comment]
Sorry for replying to a closed issue.

Honestly I see "a new line in the same paragraph" is ambiguous and can mean either a soft break (new line in the editor but not in the preview) or a hard break (new line in both).

I guess more rewording is needed. I suggest something like:

> - Single newlines inside paragraphs allow you to divide your paragraphs to more lines for easier editing, without affecting the preview; in the preview, **line breaks inside a paragraph are ignored**.

Or something like (with the next bullet):

> - You can break a paragraph into more than a single line for easier editing; they still render as a single paragraph with no breaks.
> - You can force a line break inside a paragraph by ending a line with two spaces.

But then also the first bullet would need to change to maintain parallelism (starting the sentence with `You can` or similar).

I'm just suggesting a general idea; feel free to reword better.

(Or this should be a new issue? 😅)

**Comment by pbek** [comment]
> Sorry for replying to a closed issue.

that's quite fine with me

> Honestly I see "a new line in the same paragraph" is ambiguous and can mean either a soft break (new line in the editor but not in the preview) or a hard break (new line in both).

I remember very darkly that the old markdown2hmtl library supported having a line-break in a paragraph even if that's not a markdown "standard"... I think the text should reflect what's shown in the preview...

> (Or this should be a new issue? sweat_smile)

Best a pull request 😁

**Comment by noureddin** [comment]
> I remember very darkly that the old markdown2hmtl library supported having a line-break in a paragraph even if that's not a markdown "standard"

Some Markdown implementations actually does that, like GitHub here in the issues, and Element.

> I think the text should reflect what's shown in the preview...

I agree.

> Best a pull request :grin:

No problem. :sweat_smile:
Which wording do you find better?

**Comment by pbek** [comment]
I now used https://github.com/pbek/QOwnNotes/commit/04ab49415d39aa35ab4ae6db7fe4f5a1585ed7e2. Thank you.

**Comment by noureddin** [comment]
Thank you!

But you removed the first bullet! :sweat_smile:

**Comment by pbek** [comment]
> Single newlines inside paragraphs allow you to divide your paragraphs to more lines for easier editing, without affecting the preview; in the preview, line breaks inside a paragraph are ignored.

this one? I thought that was "suggestion 1" of two... 😅  (now we know why PRs are easier to talk about 😉)

**Comment by pbek** [comment]
better just make a PR...

**Comment by noureddin** [comment]
OK. No problem. :smile:
