### ISSUE TITLE
Build RPM

### ISSUE THREAD

**Issue by LEDfan** [pbek/QOwnNotes#24]
Currently you only build .deb files. It would be great if you release a RPM of your app too.

I'm running OpenSUSE 13.2 and for me it's enough to use the `alien` tool:
````
alien -r qOwnNotes.deb
````
Then a RPM is created. Alien is AFAIK just a perl script, but you will need tools like rpmbuild.

See https://en.wikipedia.org/wiki/Alien_%28software%29 and http://joeyh.name/code/alien/ 

P.s. do you know the OpenSUSE Build service? ownCloud is using it too for both the server and client. I'm not sure if it's easier than travis tough.

**Comment by pbek** [comment]
Thank you for your suggestion! I already tried alien.

But to install the rpm you have to use the `--force` parameter to get around the permission problems like:

- file / from install of QOwnNotes-0.65-2.x86_64 conflicts with file from package filesystem-3.2-32.fc22.x86_64
- file /opt from install of QOwnNotes-0.65-2.x86_64 conflicts with file from package filesystem-3.2-32.fc22.x86_64
- file /usr from install of QOwnNotes-0.65-2.x86_64 conflicts with file from package filesystem-3.2-32.fc22.x86_64
- file /usr/share from install of QOwnNotes-0.65-2.x86_64 conflicts with file from package filesystem-3.2-32.fc22.x86_64
- file /usr/share/applications from install of QOwnNotes-0.65-2.x86_64 conflicts with file from package filesystem-3.2-32.fc22.x86_64
- file /usr/share/doc from install of QOwnNotes-0.65-2.x86_64 conflicts with file from package filesystem-3.2-32.fc22.x86_64

But as it happens I took on the challenge and made use of the openSUSE build system.
I just now finished creating the [QOwnNotes installation page](http://www.qownnotes.org/installation) for more informations.

**Comment by pbek** [comment]
Please be so kind to report any problems or suggestions for the openSUSE repository!

**Comment by LEDfan** [comment]
Great! It's working for me, except that I think the library `libqt5-qtsvg` has a wrong name. I have to "break" the installation. In openuse the library is called `libqt5svg`. 
Thanks.

**Comment by pbek** [comment]
Thanks a lot for your report, I could only test openSUSE Leap.
Unfortunately it depends on the openSUSE version how this library is called. Which distribution and version are you using? I need to make changes in the spec file.

**Comment by LEDfan** [comment]
I'm using OpenSUSE 13.2 64 bit.

**Comment by pbek** [comment]
Shouldn't be the name of the package not `libQt5Svg5`? That's what <https://software.opensuse.org/package/libQt5Svg5> is saying...

**Comment by pbek** [comment]
I now changed the spec file, can you please try to update to v0.69.1 and tell me if you get any errors and if it worked with `libQt5Svg5`.

**Comment by LEDfan** [comment]
Yes I meant `libQt5Svg5`... The package is installation fine now thanks.

**Comment by pbek** [comment]
I'm glad to hear that! Thanks a lot for your help and have a great day!
