### ISSUE TITLE
An option for debug information output like "Include private info"

### ISSUE THREAD

**Issue by LightTemplar** [pbek/QOwnNotes#240]
I don't see the point in including private info about 

- note names, 
- note paths
- folder names,
- recent note folders 
- saved searches
- Servers
- Usernames
- (hope, nothing is forgotten)

into debug info, but if by some circumstances it will be needed, I suggest to do it explicitly with an option.

**Comment by pbek** [comment]
I'm sorry. Very often exactly this information is needed, that's why it's a text dump where the user can decide what he will post on github. It's hardly possible to create a setting for every circumstance.
