### ISSUE TITLE
Configure how bullets are rendered in preview window?

### ISSUE THREAD

**Issue by baslow** [pbek/QOwnNotes#2401]
Unordered list items render in the preview pane with light gray bullets that are difficult to see on my display. I'd like to change them to a darker color. Is there any way to configure how bullets are rendered in preview?

**Comment by pbek** [comment]
There is a script in the script repository `Custom note preview styling` with which you could play around to set another color.

**Comment by pbek** [comment]
But I'm not sure how much you can style the `li` or `ul` tags... See: https://doc.qt.io/qt-5/richtext-html-subset.html

**Comment by Waqar144** [comment]
With litehtml backend this is possible (provided html allows this). I think I saw the code for it so it's probably possible.

Maybe we should add a litehtml switch or config to allow people to use it optionally. Would help in stabilizing it

**Comment by pbek** [comment]
> Maybe we should add a litehtml switch or config to allow people to use it optionally. Would help in stabilizing it

Depends if it builds with Qt 5.6 😄

**Comment by Waqar144** [comment]
Not sure, but there is only one way to find out how much stuff depends on newer Qt versions. If it's small, perhaps back porting will make sense. If you have a machine with older Qt, can you check the scope of changes that might need to be done? Or maybe use the CI for this? 

Otherwise we can always just enable it for the a required Qt version.

**Comment by pbek** [comment]
Since Qt deprecated those versions I can't really it anymore in the CI (without jumping through some major hoops)...

> Otherwise we can always just enable it for the a required Qt version.

Might be the better idea.

**Comment by Waqar144** [comment]
The Qt layer is very small anyways, so a full port might not be as hard.
