### ISSUE TITLE
Feature Request - Collapsable Headings

### ISSUE THREAD

**Issue by Born2Root** [pbek/QOwnNotes#2402]
Hi,
I have a feature request that would really improve handling of big note-files.
At the moment navigation in big note-files is only possible over the Navigation-Pane.

But it would be really cool, if the Headings could be collapsed/ extended.
Like shown in the following screenshot, where H2 is collapsed:

![grafik](https://user-images.githubusercontent.com/8644900/150501732-7e7021dc-001a-4ef2-91a0-1a88bfd19a50.png)

The behaviour could be like this:
- clicking on the little arrow or pressing a special shortcut collapses/ extends the content below the heading
- a H1 heading collapses all it's sub-content till the next H1 declaration
- a H2 heading collapses until the next H2
- and so on...

I don't know how complicated it is to implement such a feature, but it would be really cool.
Hence storing some additional status information in the markdown file itself is not possible, maybe it could be saved to a .tmp file or in the single notes metadata?

Thanks for the great tool and your work.
Best regards and have a nice weekend!

**Comment by pbek** [comment]
That would be **very** complicated to implement in the QPlainTextEdit the editor widget is based in. 😁 
And yes, (almost) no metadata is stored for notes... the note file itself is the single source of truth (in most cases).

> Thanks for the great tool and your work.

Thank you very much! 😉

**Comment by Waqar144** [comment]
I will take a stab at this in the upcoming days. Not sure when though, since we are going through some refactorings atm.

**Comment by Waqar144** [comment]
We need to add
- fold marker to the line number area
- code to find length of the current foldable region
- define what is foldable. Probably just headings are enough
- hide blocks which are child of current foldable block 
- paint some placeholder to show folded stuff
- and finally, make it configurable

**Comment by Zorziel** [comment]
In doing a little research, it looks like there's new HTML tags that support creating collapsible sections: `<details>` and `<summary>`.  

Here's Mozilla's reference for Firefox: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

Here's an example and the code in action (from https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab): 


```markdown
# A collapsible section with markdown
<details>
  <summary>Click to expand!</summary>
  
  ## Heading
  1. A numbered
  2. list
     * With some
     * Sub bullets
</details>

```

# A collapsible section with markdown
<details>
  <summary>Click to expand!</summary>
  
  ## Heading
  1. A numbered
  2. list
     * With some
     * Sub bullets
</details>

I don't know what the KHTML roadmap is for those tags but maybe this will be easier to explore than refactoring the markdown renderer itself?

**Comment by dandv** [comment]
I find the auto-fold feature in Obsidian, and the Toggle Headings in Notion, *extremely useful* for managing large notes.

Hope this can be implemented in QOwnNotes. Remembering the folded/collapsed state across sessions is not THAT important, since I'd keep QOwnNotes running continuously, but I do see a `notes.sqlite` database that could be used for that purpose.

**Comment by dandv** [comment]
For those who need collapsible headings or lists, AppFlowy supports them. However, the startup time of the app is very long compared to QOwnNotes.

PS: could this issue be reopened since it wasn't actually completed?

**Comment by sadiogo** [comment]
Would be great to have this feature in QOwnNotes!

**Comment by pbek** [comment]
That's already a thing:

<img width="2386" height="1157" alt="Image" src="https://github.com/user-attachments/assets/fc802707-ec41-4c43-90f7-a51bdcf3e1c0" />

It was done for another feature request.

**Comment by sadiogo** [comment]
This is awesome, best md editor ever!

Thanks for the prompt reply!

**Comment by pbek** [comment]
Thank you 😁
