### ISSUE TITLE
Note-links to headings don't work any more

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#2404]
@Waqar144, note-links to headings don't seem to work any more in the note edit.

E.g. `[My note](note.md#Heading1)` should jump to the heading `Heading1` in note `note.md`. Jumping to the note works, but not to the heading.

Another regression?

**Comment by pbek** [comment]
It was broken since https://github.com/pbek/QOwnNotes/commit/1e61524efa60697f5cb4c79c726b6bdfee749934.

**Comment by pbek** [comment]
Seems like you have ripped out the url fragment handling. 🙄

**Comment by Waqar144** [comment]
Not sure, works nicely here.

**Comment by pbek** [comment]
In the note edit or in the preview?

**Comment by pbek** [comment]
The whole `MainWindow::openLocalUrl` that handled url fragments was replaced by `UrlHandler(this).openUrl(urlString);` that is not url fragments... (and I don't even know what else it is not handling).

**Comment by Waqar144** [comment]
> The whole MainWindow::openLocalUrl that handled url fragments was replaced by UrlHandler(this).openUrl(urlString); that is not url fragments...

That now happens in the UrlHandler or at least it should.

**Comment by pbek** [comment]
> That now happens in the UrlHandler or at least it should.

`openUrl` doesn't even contain the word "fragment" 😓 

> In note edit of course.

what did you test? if a link with a url fragment is created (that works) or if you actually jump to the heading in the linked note (that doesn't work)?

**Comment by Waqar144** [comment]
> openUrl doesn't even contain the word "fragment"

there are more than one function now.

I tested this:

> E.g. [My note](note.md#Heading1) should jump to the heading Heading1 in note note.md. Jumping to the note works, but not to the heading.

**Comment by Waqar144** [comment]
okay, my cursor was already in the correct position, thats why

**Comment by Waqar144** [comment]
From a quick look, fragment gets initialized incorrectly. It needs to be handled for invalid url case

**Comment by pbek** [comment]
## 22.1.10
- jumping to headings from note links in the note edit panel was fixed
  (for [#2404](https://github.com/pbek/QOwnNotes/issues/2404), thank you @Waqar144)

**Comment by kg-yoda** [comment]
Doesn't work again.

Version --> QOwnNotes - version 23.11.0 - GitHub Actions - build 1061

Trying to link to a header link this `## Header` and it doesn't scroll down to where that header is located.

**Comment by pbek** [comment]
Oh no, you are right. Can you please open a new issue! Looks like it's because of pbek/qmarkdowntextedit#196!

**Comment by pbek** [comment]
But please open a new issue anyway. 
And can you please explain in more detail and step by step what you did, what happened and what you expected.
