### ISSUE TITLE
New editor schema: Orangueen

### ISSUE THREAD

**Issue by Zorziel** [pbek/QOwnNotes#2405]
I want to submit a new editor schema.

---

![image](https://user-images.githubusercontent.com/46036567/150675363-a71cb401-3313-408f-b9c3-6df3d434acc9.png)

---

# Summary
It is a dark theme, modeled initially after my Dark Gold FF theme, but modified heavily over time.  It has been my default for a while now and wanted to share it.  

# Fonts
For fonts, I am using the [SIL Open Font License (OFL)](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL&_sc=1) licensed [Orbitron](https://www.theleagueofmoveabletype.com/orbitron) and [Russo One](https://fonts.google.com/specimen/Russo+One).  

# Sample: 
## Editor Window: 
![image](https://user-images.githubusercontent.com/46036567/150675528-e2da9710-dc14-4c12-aadd-ed3e82eabab1.png)

## Preview Window: 
![image](https://user-images.githubusercontent.com/46036567/150675827-77a281c0-c57f-4320-80df-b3870087f70e.png)

[Orangueen.zip](https://github.com/pbek/QOwnNotes/files/7920313/Orangueen.zip)

**Comment by Zorziel** [comment]
added screenshots of both the editor window and the preview window

**Comment by pbek** [comment]
Thank you!

**Comment by pbek** [comment]
## 22.1.10
- added a new editor color schema *Orangueen* by @Zorziel

**Comment by Zorziel** [comment]
Confirmed that this theme is now available in QOwnNotes [22.1.10.1](https://github.com/pbek/QOwnNotes/releases/tag/v22.1.10.1).   Thank you!

![image](https://user-images.githubusercontent.com/46036567/150864358-606d61c3-f7e8-4335-b578-952054462bfc.png)

**Comment by pbek** [comment]
Thank you!
