### ISSUE TITLE
How to have a blank content default note after it's created?

### ISSUE THREAD

**Issue by ucelote-de-mar** [pbek/QOwnNotes#2411]
**DON'T READ**: I'm blind or something but couldn't find any option to change the default content of a note. I've also braved and googled everywhere but couldn't find anything related... I've spent like 30 minutes now, so really excuse me if I'm missing something so obvious.

**READ**: I just need a blank note 🦥.
![image](https://user-images.githubusercontent.com/95152045/150708030-3a58967b-f3a1-4f4d-aa73-43d9cd52c69e.png)

I'm doing `<Ctrl-A><Backspace>` to delete the default... but my joints 😿

Thanks for your amazing work 🥰

**Comment by pbek** [comment]
> I just need a blank note 

Main Menu: Note / New note
...or the top left toolbar button in your screenshot

but by default the first line will be the name of the note, so the note file is never empty... or you change that in the *General settings*
you could write a script to really get an empty file if you really must...

> Thanks for your amazing work 🥰

thank you 😁

**Comment by dohliam** [comment]
This seemed like a reasonable feature to want, and also something that should be pretty easy to implement, so I wrote [a quick script](https://github.com/dohliam/qownnotes-scripting/tree/master/scripts/blank-note) using `handleNewNoteHeadlineHook`, which you can find [here](https://github.com/dohliam/qownnotes-scripting/tree/master/scripts/blank-note).

Unfortunately though, it doesn't work. :sweat_smile: If you replace `text` with anything (even a single space or linebreak), it works fine and creates a note with a space and several line breaks, but if `text` is empty then nothing happens.

I eventually traced the problem to [this line](https://github.com/pbek/QOwnNotes/blob/develop/src/services/scriptingservice.cpp#L770) in `scriptingservice.cpp`:

```c++
        if (!text.isEmpty()) {
            return text;
        }
```

@pbek Is there any way to override this? Or perhaps another hook that would work better here? It would be nice to be able to remove the additional line breaks as well and create just a blank note, though I'm not sure if that is currently possible.

**Comment by pbek** [comment]
Maybe the easiest thing for you would just be to write an empty file with https://www.qownnotes.org/scripting/methods-and-objects.html#writing-text-to-a-file into your current note folder.

**Comment by dohliam** [comment]
@pbek That sounds like a good idea, thanks. I have updated [the script](https://github.com/dohliam/qownnotes-scripting/blob/master/scripts/blank-note/blank-note.qml) to use `writeToFile` and register a custom action instead of changing the New Note action itself. It now successfully creates a blank file in the main note folder, although for some reason jumping directly to that new file doesn't seem to be working (any idea why that might be? I tried passing both the absolute path and relative path of the new note and neither worked).

The other issue with this approach is creating the note in the correct subfolder. I notice that clicking on New Note creates a note in the current note subfolder, even if there is no note open, but I couldn't find a script function that could identify the currently selected subfolder, so not sure what the best way to reproduce this default behaviour would be.

**Comment by pbek** [comment]
Does the new file show up in the note list?
Maybe you need to do a:

```js
// Force a reload of the note list
mainWindow.buildNotesIndexAndLoadNoteDirectoryList(true, true);
```

>  I couldn't find a script function that could identify the currently selected subfolder, so not sure what the best way to reproduce this default behaviour would be.

I need to have a closer look at that.

**Comment by pbek** [comment]
## 22.2.2
- there now are new methods for the scripting class `NoteSubFolderApi` to get
  the active note subfolder and the relative and absolute path of a subfolder
  (for [#2411](https://github.com/pbek/QOwnNotes/issues/2411))
  - for more information please take a look at the
    [scripting documentation](https://www.qownnotes.org/scripting/classes.html#notesubfolder)

**Comment by pbek** [comment]
```js
                var noteSubFolderQmlObj = Qt.createQmlObject("import QOwnNotesTypes 1.0; NoteSubFolder{}", mainWindow, "noteSubFolder");
                var subFolder = noteSubFolderQmlObj.activeNoteSubFolder();
                script.log(subFolder.fullPath());
                script.log(subFolder.relativePath());
```

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by dohliam** [comment]
Wow, this is great! This API will be really useful in other scripts too, I think.

I keep getting the following error though for some reason: `TypeError: Property 'fullPath' of object NoteSubFolderApi(0x556766261200) is not a function`

**Comment by pbek** [comment]
How does your script look like and which version of QOwnNotes are you using?

**Comment by dohliam** [comment]
The script is [here](https://github.com/dohliam/qownnotes-scripting/blob/master/scripts/blank-note/blank-note.qml) and I am using the latest version of QOwnNotes (22.2.2). Is there anything else I should be including in the script in order to use `activeNoteSubFolder()` properly?

**Comment by pbek** [comment]
https://github.com/dohliam/qownnotes-scripting/blob/4733cd3ec20ae8549abc9617ae8c3f5ab78a1ebf/scripts/blank-note/blank-note.qml#L40

`subFolder` is an object, you can't just concatenate a string to an object. 😅

**Comment by dohliam** [comment]
Of course, that makes sense! :sweat_smile: 

Unfortunately, removing that obvious mistake doesn't seem to help. I get the exact same error even after removing everything else and just copying the code from your post above::

```qml
                var noteSubFolderQmlObj = Qt.createQmlObject("import QOwnNotesTypes 1.0; NoteSubFolder{}", mainWindow, "noteSubFolder");
                var subFolder = noteSubFolderQmlObj.activeNoteSubFolder();
                script.log(subFolder.fullPath());
                script.log(subFolder.relativePath());
```

Are `fullPath()` and `relativePath()` not meant to be functions perhaps?

(This is using the latest version updated today.)

**Comment by dohliam** [comment]
That's a very helpful script! I just loaded the latest version but got the same error: `TypeError: Property 'fullPath' of object NoteSubFolderApi(0x5642cd280e20) is not a function`. This happened on two different machines.

However... I happen to have a separate clean install of Manjaro that I was using to do tests for a separate bug report to do with toolbars, and the script worked perfectly fine there, so I'm going to assume that this error has something to do with my setup on the other machines. I will try to investigate further and when I have some time maybe see about doing a clean install of KDE Neon in case that makes a difference.

In the meantime I'll go ahead and file that other bug report which is a bit easier to reproduce right now. :smile:

**Comment by pbek** [comment]
Very strange, maybe some Qt package is missing?

**Comment by dohliam** [comment]
Had the chance to test this again with a fresh install of the latest KDE Neon ([User Edition](https://neon.kde.org/download)). Installed QOwnNotes following the instructions [here](https://www.qownnotes.org/installation/ubuntu.html), loaded [custom-actions.qml](https://github.com/pbek/QOwnNotes/blob/743490fcab2a99cdb1eed3a475a79b34872d59ab/docs/scripting/examples/custom-actions.qml) as a local script, ran `Show active note subfolder information` from the custom actions menu, and got the same error as before (see screenshot with error below):

![neon_subfolder](https://user-images.githubusercontent.com/9295750/153782631-f589f6a7-81cb-4b3f-99af-0c6392bfd909.png)

> Very strange, maybe some Qt package is missing?

This does make it seem like something is different about the default KDE environment in Neon and Manjaro. Not sure what it might be though...

**Comment by pbek** [comment]
Is there any useful log output when you start QOwnNotes and when you run the custom action? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting Debug in Options).

**Comment by dohliam** [comment]
Did a bit more testing with this... Strangely enough, when running QOwnNotes from the AppImage release the `custom-actions.qml` script works perfectly. But on the same system with QOwnNotes installed from the PPA, it fails again. The full debug log is below:

```
[09:02:09] [debug] updatePanelMenu - 'updatePanelMenu'
[09:02:09] [info] "QOwnNotes server listening on port 22222"
[09:02:15] [debug] Current sub folder changed
[09:02:15] [debug] reloadTagTree
[09:02:15] [debug] reloadTagTree - 'noteSubFolderIds': QVector(-1)
[09:02:16] [debug] Current sub folder changed
[09:02:16] [debug] filterNotesByNoteSubFolders - 'noteSubFolderIds': QVector(1)
[09:02:16] [debug] reloadTagTree
[09:02:16] [debug] reloadTagTree - 'noteSubFolderIds': QVector()
[09:02:18] [status] No script updates were found
[09:02:24] [scripting] customActionInvoked - noteSubFolder
[09:02:24] [warning] file:///home/neon/Downloads/custom-actions.qml:83: TypeError: Property 'fullPath' of object NoteSubFolderApi(0x561c32038b50) is not a function
```

Nothing comes up in the debug log on starting QOwnNotes though (apart from the first line above about `updatePanelMenu`). Let me know if there are any other tests I could run to help pinpoint the cause of this error!

**Comment by pbek** [comment]
Interesting. I will attempt to blindly change the way those methods are initialized and we'll see in the next release if it helps.

**Comment by pbek** [comment]
## 22.2.6
- an attempt was made to fix some `NoteSubFolderApi` methods for PPA builds
  (for [#2411](https://github.com/pbek/QOwnNotes/issues/2411))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by dohliam** [comment]
@pbek Whatever you did, it worked! :+1: Had a chance to test this on the latest Fedora as well, and it worked there too. :tada:

Now that it's possible to get the active subfolder, I was finally able to get the blank note script working. I will submit a PR to the script repo so @ucelote-de-mar can test it out!

**Comment by pbek** [comment]
Great, thank you for testing!
