### ISSUE TITLE
Main build, OBS builds, Snapcraft build, Launchpad build, Appveyor build broken

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#2415]
@Waqar144, #2410 breaks lots of OBS builds and our main build!

- https://build.opensuse.org/package/show/home:pbek:QOwnNotes/desktop
- https://github.com/pbek/QOwnNotes/runs/4927586085?check_suite_focus=true

**Comment by pbek** [comment]
Launchpad and Snap builds are down too!

**Comment by Waqar144** [comment]
Nothing big, just needs the memory include in mainwindow.

**Comment by pbek** [comment]
Damn, I hate when a build breaks that bad... I have to skip a version now or something. And I have no clue what issues #2414 will introduce...

**Comment by Waqar144** [comment]
That should actually make things harder to break, but seems like do not want it, so I can just close the PR.

You can always wait a day to see how the builds go and then release. If all is good in the github CI, all is good by me.
