### ISSUE TITLE
[I] Last few seconds of typing disappears and cursor jumps to top of buffer while typing in note

### ISSUE THREAD

**Issue by donaldsycamore** [pbek/QOwnNotes#2416]
#### Expected behaviour

While typing more text into a note, the cursor continues to advance as each character is entered.

E.g. I create a note called "Story"

and start typing Mary had a little lamb, its fleece was white as snow, and everywhere that Mary went that lamb would surely go

And the note looks like

Story
=====

Mary had a little lamb, its fleece was white as snow, and everywhere that Mary went that lamb would surely go

#### Actual behaviour

Quite often now, while typing into a note, the cursor jumps to the top of the buffer and the last bit of typing before that jump is gone.  Last time I tried to reproduce this I had to write about three paragraphs before it happened.

E.g. I create a note called "Story"

and start typing Mary had a little lamb, its fleece was white as snow, and everywhere that Mary went that lamb would surely go

And the note looks like

amb would surely goStory
=====

Mary had a little lamb, its fleece was white as snow, and ever

#### Steps to reproduce

QOwnNotes 22.1.10.1, Nextcloud 22.2.3, Windows 10, Nextcloud desktop client with Virtual Files turned on

Note that I have had this behaviour over the years without the Virtual Files feature but it happens a lot more with Virtual Files.

1.  Create a note
2.  Start typing text into the note
3.  Notice that suddenly your cursor has jumped to the top of the buffer and that the most recent text you entered has disappeared

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[14:57:06] [status] Stored 1 note(s) to disk
[14:57:13] [status] Stored 1 note(s) to disk
[14:57:24] [status] Stored 1 note(s) to disk
[14:57:33] [status] Stored 1 note(s) to disk
[14:57:43] [status] Stored 1 note(s) to disk
[14:57:51] [status] Current note was modified externally
[14:57:51] [status] Loading external changes from: Story.md
[14:57:51] [warning] QTextCursor::setPosition: Position '363' out of range
[14:57:55] [status] Stored 1 note(s) to disk
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed Jan 26 14:58:11 2022`
**Version**: `22.1.10.1`
**Build date**: `Jan 24 2022`
**Build number**: `941`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\donald\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Users\donald\Internal\QOwnNotes\QOwnNotes.exe`, `--after-update`, `C:\Users\donald\AppData\Local\Temp\QOwnNotes-csyfZL-updater.bat`
**Qt Debug**: `0`
**Locale (system)**: `en_NZ`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `786`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://nextcloud.sycamore.nz`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `22.2.3.0`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\donald\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `C:\Users\donald\Nextcloud\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: `journal`
**database file**: `C:\Users\donald\Nextcloud\Notes\notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://nextcloud.sycamore.nz`
**username**: `donald`
**accountId**: *empty*

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `C:/Users/donald/Documents`
**FileDialog/LastPath-NoteHTMLExport** (QString): `C:/Users/donald/Documents`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2022-01-26T14:33:28.828`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `KCML, KCML/Block courses, Preaching`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,12,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/update-and-restart** (int): `0`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteDialog/tabWidgetIndex** (int): `1`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): `mail server, tsb, 20211111, 20220130 Jer 1 1-10ish, 20200802 mt 14 13-21 feeding of the five thousand, all saints day, Presbytery COVID Zoom 18 Nov 2021, 20211031 mk 12 28-34`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): 
```
IT, , journal, Preaching, Preaching, Preaching
material, WPC, Preaching
```
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `199`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `true`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (int): `15`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `C:/Users/donald/Nextcloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Donald's Calendar, Intentions - Church, Deadlines - Church, Intentions - Home, Others, Deck: Personal`
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): `https://nextcloud.sycamore.nz/remote.php/dav/calendars/donald/2005dd9e-dbc4-420b-9448-15ca6089e0f3/, https://nextcloud.sycamore.nz/remote.php/dav/calendars/donald/work/, https://nextcloud.sycamore.nz/remote.php/dav/calendars/donald/business/, https://nextcloud.sycamore.nz/remote.php/dav/calendars/donald/personal/, https://nextcloud.sycamore.nz/remote.php/dav/calendars/donald/others/, https://nextcloud.sycamore.nz/remote.php/dav/calendars/donald/app-generated--deck--board-1/`
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `22.2.3.0`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Story, 20220130 Jer 1 1-10ish, 20220126, 20220125, stuff I have given WPC, 20211222, 20211216, 20211224 PJ service, 20211214, 20211225 Is 62 6-12 Christmas Day, future, 20211206, 20211205 Advent 2 PEACE play Luke 3 1-6, 20211128 Advent 1, 2021 11 22, 20211116, 20211121 Christ the King, 20211115, 20211111, branches, 20211114 Mark 13:1-8, AMPRnet, Note 2021-11-08T11.31.41, 20211107 Jn 11 32-44 All Saints, 20211101, 20211026 mission zoom, 20211031 mk 12 28-34, Matthew, Note 2021-10-19T08.37.06, hawks, Note 2021-10-18T11.50.09, 20211024 mk 10 46-52 blind bartimaeus, 20211017 mk 10 35-45, 2021 10, 20211010 mk 10 17-31, resourcing day, zoom l2, 20210919 James 3 13 - 4 8, speakers on topics, hub, lockdown 2, 20210817 The Gospel, Anna, 2021 08, hewitson ebsco, 20210808 2 Samuel 18 Absaloms fall, onaero, hiring, te kakano, 20210725 2 sam 11 1-15, esp32, 20210711 2 sam 6 1-19, parent teacher interview, 2021 07, 20210627 2 sam 1, meeting with driver, skinny 4g broadband, cf-ew74, 20200613 1 sam 15 34 - 16 13, mesh vpn, eldership, vpns, 2021 06, 20210606 1 sam 8, mcu stuff, devo, car stuff, 20210430 is 6 1-8 trinity 40b, next ministers report, 20210530 trinity sunday, music - who you say i am, scratch, 20210523 acts 2 1-21 pentecost, 202105 term 2 planning, 2021 05, 20210509 luke 2 40-52, 2021 04, 20210502 acts 8 26-40, 20210418 acts 3 11-19, CFM stuff, theology and homosexuality, 20210321 john 12 20-33, 20120321 Heb 4 14-5 10, supervision, expenses, easter 2021, 20210221 maybe 1 peter 3 18-22, lent retreat, 20200214 mark 2 2-9, 20210207 1 cor 9, 20210131 1 cor 8 w deut 18, 20210103 eph 1 3-14, timesheet, 20201207, wireless mesh, lyn, elders, burnout, grief, bill and trish armour`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**skipVersion** (QString): `20.8.7`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\donald\AppData\Roaming`
**ChocolateyInstall**: `C:\ProgramData\chocolatey`
**ChocolateyLastPathUpdate**: `132197529782936757`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `SILVER`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**destination**: `C:\Users\donald\Internal\QOwnNotes`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\donald`
**LOCALAPPDATA**: `C:\Users\donald\AppData\Local`
**LOGONSERVER**: `\\SILVER`
**MOZ_PLUGIN_PATH**: `C:\Program Files (x86)\Foxit Software\Foxit Reader\plugins\`
**NUMBER_OF_PROCESSORS**: `4`
**OneDrive**: `C:\Users\donald\OneDrive - Presbytery Central`
**OneDriveCommercial**: `C:\Users\donald\OneDrive - Presbytery Central`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\ActiveState Komodo IDE 11\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\ZeroTier\One\;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\dotnet\;C:\Program Files (x86)\PDFtk\bin\;C:\Users\donald\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\donald\AppData\Local\Programs\Python\Python38-32\;C:\Ruby26-x64\bin;C:\Users\donald\AppData\Local\Programs\Python\Launcher\;C:\Users\donald\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Nmap;C:\Users\donald\AppData\Roaming\npm;C:\Users\donald\AppData\Local\Yarn\bin;;C:\Users\donald\AppData\Local\Programs\Microsoft VS Code\bin`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 58 Stepping 9, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `3a09`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PROMPT**: `$P$G`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**qownnotesCommand**: `C:\Users\donald\Internal\QOwnNotes\QOwnNotes.exe --after-update C:\Users\donald\AppData\Local\Temp\QOwnNotes-csyfZL-updater.bat `
**SciTE_HOME**: `C:\ProgramData\SciTE`
**SciTE_USERHOME**: `C:\Users\donald\AppData\Roaming\SciTE`
**SESSIONNAME**: `Console`
**source**: `C:\Users\donald\AppData\Local\Temp\QOwnNotes-csyfZL.zip`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\donald\AppData\Local\Temp`
**TMP**: `C:\Users\donald\AppData\Local\Temp`
**unzipCommand**: `C:\Users\donald\AppData\Local\Temp\QOwnNotes-csyfZL-unzip.exe -o C:\Users\donald\AppData\Local\Temp\QOwnNotes-csyfZL.zip -d C:\Users\donald\Internal\QOwnNotes`
**unzipExecutable**: `C:\Users\donald\AppData\Local\Temp\QOwnNotes-csyfZL-unzip.exe`
**USERDOMAIN**: `SILVER`
**USERDOMAIN_ROAMINGPROFILE**: `SILVER`
**USERNAME**: `donald`
**USERPROFILE**: `C:\Users\donald`
**windir**: `C:\WINDOWS`
**WIX**: `C:\Program Files (x86)\WiX Toolset v3.11\`
</details>

**Comment by pbek** [comment]
> top of the buffer

What is the "top of the buffer"? Start of the line? Start of the paragraph? Start of the note?

**Comment by pbek** [comment]
> [14:57:51] [status] Current note was modified externally
> [14:57:51] [status] Loading external changes from: Story.md

maybe some other processes are messing with the note file...
in the *General settings* there are some checkboxes you can play with to ignore external changes or to not to restore the cursor position when a note is opened.

**Comment by pbek** [comment]
> acceptAllExternalModifications (QString): true

did you set that? that can surely interfere if an external process is updating your note all the time

**Comment by donaldsycamore** [comment]
By "top of the buffer" I mean the very start of the note, i.e. 

I've worked out I can ignore external changes .. but there should be no external changes to ignore!

I have separated out my Notes folder and am syncing it without the Virtual Files option (Nextcloud client), and the problem appears to have gone away.  So this is something wierd about the Nextcloud client.  I'll file a bug with them.

Looks like it's https://github.com/nextcloud/desktop/issues/4139 or https://github.com/nextcloud/desktop/issues/3456

**Comment by pbek** [comment]
> acceptAllExternalModifications (QString): true

then why did you set this 😁 

> or to not to restore the cursor position when a note is opened.

and you can try to uncheck this too if above didn't help

**Comment by pbek** [comment]
> acceptAllExternalModifications (QString): true

QOwnNotes has a detection if a file *really* changed, this setting might interfere if there was an external change by a sync client / etc...

**Comment by pbek** [comment]
It allows that you can write while the file underneath is changed "a bit"...
Nextcloud should make any issues.
But still my question remains: do you need "acceptAllExternalModifications"?

**Comment by donaldsycamore** [comment]
When I turn it off (and still using Nextcloud virtual files), instead of my cursor jumping around, I just get dialog boxes telling me the file has changed which is still pretty disruptive to note-writing.

**Comment by pbek** [comment]
Strange, I never had that with the Nextcloud sync client on any platform (including Windows)... Seems like something is changing more than the threshold is allowing in QOwnNotes...

Then you could at least turn off the cursor restoring...
