### ISSUE TITLE
Appimage depends on Glibc 2.27, which does not work on some older systems.

### ISSUE THREAD

**Issue by alana-glitch** [pbek/QOwnNotes#2417]
#### Expected behaviour
Downloading the appimage as described in the [documentation](https://www.qownnotes.org/installation/appimage.html) will work on a system with Glibc 2.23 (system is approximately Ubuntu 16.04), or alternatively, a note will be there that this platform is not supported.
The patch notes imply this should work:
```
support for Qt < 5.6 was dropped with version 22.1.5, that mainly means there will be no repositories anymore for Ubuntu 16.04, Debian 8.0 and some older versions of Fedora and openSUSE Linux (for #2373) 
please use the AppImage version of QOwnNotes (64bit only) if you are still on one of those Linux distributions
```

#### Actual behaviour
```
$ curl -L https://api.qownnotes.org/latest_releases/linux | jq .url | xargs curl -Lo QOwnNotes-x86_64.AppImage
$ chmod a+x QOwnNotes-*.AppImage
$ QOwnNotes-x86_64.AppImage
QOwnNotes-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_QOwnNoFLtHpa/usr/bin/../lib/libgssapi_krb5.so.2)
```
(The application does not start here and there is no further output.)

#### Steps to reproduce
See above. Have not tested on clean Ubuntu 16.04, but suspect will be the same.

```
$  ldd --version
ldd (Ubuntu GLIBC 2.23-0ubuntu11.3) 2.23

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    GalliumOS 2.1
Release:        16.04
Codename:       xenial
```

#### Output from the debug section in the settings dialog
Inaccessible

#### Relevant log output in the Log panel
Inaccessible

**Comment by alana-glitch** [comment]
This works. It gives output:
```
(QOwnNotes:11961): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine", 
(QOwnNotes:11961): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
(QOwnNotes:11961): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
(these 3 lines are repeated many times in varying orders)

Warning: Failed to find a text codec for name ISO8859-1 defaulting to locale text codec (:0, )
Warning: Could not create collator: 4 ((null):0, (null))
Warning: "Could not start QOwnNotes server on port 22222!" ((null):0, (null))
```
and the theme is a little different than before, and when I click on the menus (Notes, Edit, etc) they turn white, but that's fine, and it runs.
![Screenshot_2022-01-27_17-48-12](https://user-images.githubusercontent.com/62029416/151467812-a38f4373-5b08-4d2f-a1f7-9941f313822b.png)

**Comment by pbek** [comment]
ok, that's at least something. thank you

**Comment by Waqar144** [comment]
try setting the env var: `QT_QPA_PLATFORM_THEME=gnome` or something else and maybe that will give better looks
