### ISSUE TITLE
(issues/bug) Korean Typing in syllable order does not work.

### ISSUE THREAD

**Issue by mjxaone** [pbek/QOwnNotes#2419]
I'm excited to find a really cool note application.
I am using windows.

#### Expected behaviour
Hangul is typed in syllable order.
This is normal.

#### Actual behaviour
Hangul is typed in syllable order.
When inputting Hangul, the first typing is entered in order by dividing 'onset', 'nucleus' and 'coda'. This is normal.

However, 'onset', 'nucleus' and 'coda' are not distinguished from the second typing. Typing in syllable order does not work.

#### Steps to reproduce
Type several Korean characters.
The problem starts with the second character.

#### video
[video](https://user-images.githubusercontent.com/7800723/151619279-c9defb60-680a-4246-b526-0fc455d98cf9.mp4)

#### Output from the debug section in the settings dialog

Private

#### Relevant log output in the Log panel

<details><summary>Expand</summary>
No log related to syllable typing.
</details>

**Comment by pbek** [comment]
Might be similar to #2286 or others... (see https://github.com/pbek/QOwnNotes/issues?q=korean)

**Comment by mjxaone** [comment]
> Might be similar to #2286 or others... (see https://github.com/pbek/QOwnNotes/issues?q=korean)

Yes. It seems to be a very similar issue to issue #1495 among related issues.

**Comment by mjxaone** [comment]
A syllable typing issue has been fixed.

Settings -> Interface -> Editor -> "Highlight the current line"
When set to Off, it works normally.

![image](https://user-images.githubusercontent.com/7800723/151623669-8a6bff15-0bb3-48eb-9418-cc89a44bc544.png)

looks resolved
[video](https://user-images.githubusercontent.com/7800723/151623845-174918ce-cc65-4133-b6c4-2b74533bdcb4.mp4)

**Comment by pbek** [comment]
Ah, great! Good to know!

**Comment by Waqar144** [comment]
Can you try again with `Highlight current line` enabled, the code was revamped so the issue might be fixed now.

**Comment by mjxaone** [comment]
> Can you try again with `Highlight current line` enabled, the code was revamped so the issue might be fixed now.

I checked my mail late.

thank you
Perfectly fixed.

I'm really good with QOwnNotes.
Thank you again.

**Comment by pbek** [comment]
Great. 😁
