### ISSUE TITLE
Duplicate file listings after saving from external editor

### ISSUE THREAD

**Issue by vlanzillotta** [pbek/QOwnNotes#242]
When editing an unfocused file (not in the edit pane) from an external editor, the file list refreshes and all files are doubled in the note listing.

**Comment by pbek** [comment]
Thank you for reporting, I will look into that.

**Comment by vlanzillotta** [comment]
Only tested on OS X, BTW.

**Comment by pbek** [comment]
Should be gone in v16.07.5, thanks again for reporting.

**Comment by pbek** [comment]
There now is a new release (currently building), could you please test it and report if it works for you?

**Comment by vlanzillotta** [comment]
Still happening for me.

Here is what I did.

1. Select a note
2. Right click and edit in external editor
3. Move focus to another note
4. Edit the note from step 1 in the external editor and save

I can cmd+shift+r to refresh the list and it clear it up.

PS. This app is fantastic!

**Comment by pbek** [comment]
Strange, I could exactly reproduce your steps and didn't have that any more...
I will test on an iMac.

> PS. This app is fantastic!

I'm happy you like it! :tada:

**Comment by pbek** [comment]
Which version were you testing? :)
Travis is still not done with building 16.07.5 on OS X...

**Comment by vlanzillotta** [comment]
I pulled down the master branch and built that on OS X.

**Comment by pbek** [comment]
Smart you are... ;)

**Comment by pbek** [comment]
I did some more things for OS X in the future 16.07.6.

**Comment by pbek** [comment]
16.07.6 is now out

**Comment by vlanzillotta** [comment]
Works great!

Thanks for taking the time to make this!

**Comment by pbek** [comment]
No, thank YOU for reporting that problem!
