### ISSUE TITLE
"Don't ask again" on "allow note editing" makes the pressed key that allows it later always consumed

### ISSUE THREAD

**Issue by noureddin** [pbek/QOwnNotes#2421]
Using QOwnNotes 22.1.11.1.

#### Steps to reproduce

1. Disallow note editing (press Esc, or from the Note menu).
2. In the editor, type any letter.
3. Appears a dialog that informs you about the read-only mode and asks if you want to enable editing.
4. Tick the "Don't ask again" and press "OK".
5. Disallow note editing, again.
6. In the editor, type any letter.
7. Note editing is automatically re-enabled.

#### Expected behaviour

8. The letter you typed should appear in the editor where the cursor is.

#### Actual behaviour

8. Nothing. The letter only enables note editing but is forgotten. You have to type it again.

**Comment by pbek** [comment]
## 22.1.12
- you can now edit instantly when you disabled the read-only mode by checking
  `Don't ask again` in the dialog you get when typing in read-only mode
  (for [#2421](https://github.com/pbek/QOwnNotes/issues/2421), thank you @noureddin)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by noureddin** [comment]
It works! Thank you!

I couldn't test its behavior if "Don't ask again" wasn't selected, because I couldn't de-select it. But it should not change anyway.

**Comment by pbek** [comment]
> I couldn't de-select it

there is a button to reset all those checkboxes in the general settings

thank you for testing!

**Comment by noureddin** [comment]
It works well. Thank you!

> there is a button to reset all those checkboxes in the general settings

In my defense, "Reset message boxes" is not communicating much, and doesn't even has a tooltip. 😅

May I suggest something like `Forget all "Don't ask again" choices in message boxes` for the button or its tooltip?

> thank you for testing!

I'm glad I could be of help!

**Comment by pbek** [comment]
Good suggestion, I added a tooltip.
