### ISSUE TITLE
Escape, which disallows note editing, is unconfigurable

### ISSUE THREAD

**Issue by noureddin** [pbek/QOwnNotes#2422]
A lot of Vim users are using QOwnNotes. We instinctively hit Escape after every burst of typing. Everywhere.

When not in Vim mode, QOwnNotes is hard-coded to disallow note editing when Escape is hit.

I cannot find that anywhere in the Shortcuts settings.

I think the relevant bits are (in `QOwnNotesMarkdownTextEdit::eventFilter()`):

https://github.com/pbek/QOwnNotes/blob/478ecd3e25d8af86fef8594f58998d9150e9061d/src/widgets/qownnotesmarkdowntextedit.cpp#L1209-L1212

**Comment by pbek** [comment]
That shortcut just works in the note text edit and is no global shortcut, only the shortcuts from the main menu are configurable.

**Comment by noureddin** [comment]
That makes sense. But I think it's a kind of a global action; it can be triggered from the main menu, unlike Tab for indenting lines for example.

I think if #2421 is solved, this may not need solving. But it will trip other people, especially that it's not documented anywhere, not even the long Shortcuts page.

I think a checkbox in the Editor settings, that says "Make Escape disallow note editing" (or something similar), would do it? :thinking: 

Or better left as is?
