### ISSUE TITLE
SubFolder Bug  / Manage them  in app suggest

### ISSUE THREAD

**Issue by DarkIrata** [pbek/QOwnNotes#243]
Hi!
Activated the sub-folder function in the settings and tryed to create a few folders and added a existing note to it.

BUG:  List get refreshed but not cleared. Items are cloned. Only on freshed started QOwnNotes.
Reproduce 
> 1. Open QOwnNotes
> 2. Move Note into a SubFolder through the !Explorer!

Would it be possible to added a simple "Create Sub-Folder" / "Remove Sub-Folder" to the Rightclick Contextmenu? Oh and a "Open Explorer here" or something like that. 

// It's now working. Thought it will be in the Notes Tree. :)

**Comment by pbek** [comment]
> item duplicates

Thank you for reporting. Which operating system and which QOwnNotes version did you use?
I already fixed that for OS X in #242.

> create sub-folder

Yes, that's on my todo list ;)
Note subfolders are far from being finished.
It's a long ongoing story: #183

**Comment by DarkIrata** [comment]
Hi,
Windows 10 and QOwnNotes 16.07.6

**Comment by pbek** [comment]
I will try to reproduce it today, I couldn't a few days ago with Windows 8.1, maybe I missed something...

**Comment by pbek** [comment]
I can't reproduce it, I will try to fix it blindfolded.

**Comment by pbek** [comment]
@DarkIrata, it should be gone in version 16.07.7, can you please test that when it's released.

As for your feature request, please subscribe to #246.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by pbek** [comment]
## 16.07.8
- added an other fix to a duplicate note subfolder listing problem

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?
