### ISSUE TITLE
[I] Evernote Import: All images are moved to the end

### ISSUE THREAD

**Issue by mcatkins** [pbek/QOwnNotes#2435]
#### Expected behaviour

Heading
<image1>
text1:
<image2>
text2:
<image3>

#### Actual behaviour

Heading
text1:
text2:
<image2>
<image1>
<image3>

#### Steps to reproduce

Import a note with embedded images from evernote, via a  .enex file

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[17:56:18] [warning] Missing trigrams for languages: QSet("es_CU", "es_CR", "es_CL", "es_AR", "en_AU", "es_PY", "es_NI", "es_UY", "es_PA", "en_ZA", "it_CH", "fr_CH", "es_HN", "es_BO", "fr_LU", "es_GT", "es_US", "es_VE", "en_CA", "es_SV", "es_EC", "de_CH", "fr_MC", "es_PE", "fr_BE", "es_MX", "es_CO", "es_PR", "es_DO", "fr_CA")
[17:56:28] [status] No script updates were found
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fri Feb 4 18:00:17 2022`
**Version**: `22.1.12`
**Build date**: `Jan 30 2022`
**Build number**: `943`
**Platform**: `linux`
**Operating System**: `Linux Mint 20.3`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.12.8`
**Qt Version (runtime)**: `5.12.8`
**Portable mode**: `no`
**Settings path / key**: `/home/martin/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/martin/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_GB`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1366x768`
**Icon theme**: `Mint-Y`
**Notes in current note folder**: `102`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `de_AT, de_AT_frami, de_CH, de_CH_frami, de_DE, de_DE_frami, en_AU, en_CA, en_GB, en_US, en_ZA, es_AR, es_BO, es_CL, es_CO, es_CR, es_CU, es_DO, es_EC, es_ES, es_GT, es_HN, es_MX, es_NI, es_PA, es_PE, es_PR, es_PY, es_SV, es_US, es_UY, es_VE, fr, fr_BE, fr_CA, fr_CH, fr_FR, fr_LU, fr_MC, hi_IN, it_CH, it_IT, pt_BR, pt_PT, ru_RU`
**Language names**: `Österreichisches Deutsch (Österreich), Österreichisches Deutsch (Österreich), Schweizer Hochdeutsch (Schweiz), Schweizer Hochdeutsch (Schweiz), Deutsch (Deutschland), Deutsch (Deutschland), Australian English (Australia), Canadian English (Canada), British English (United Kingdom), American English (United States), English (South Africa), español (Argentina), español (Bolivia), español (Chile), español (Colombia), español (Costa Rica), español (Cuba), español (República Dominicana), español (Ecuador), español de España (España), español (Guatemala), español (Honduras), español de México (México), español (Nicaragua), español (Panamá), español (Perú), español (Puerto Rico), español (Paraguay), español (El Salvador), español (Estados Unidos), español (Uruguay), español (Venezuela), français, français (Belgique), français canadien (Canada), français suisse (Suisse), français (France), français (Luxembourg), français (Monaco), हिन्दी (भारत), italiano (Svizzera), italiano (Italia), português (Brasil), português europeu (Portugal), русский (Россия)`
**Application dictionaries path**: `/home/martin/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/martin/tmp/Qownnotes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/martin/tmp/Qownnotes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/removeTrailingSpaces** (QString): `false`
**EvernoteImport/AttachmentImportCheckBoxChecked** (QString): `true`
**EvernoteImport/ImageImportCheckBoxChecked** (QString): `true`
**EvernoteImport/MetaDataUnCheckedList** (QStringList): `, `
**EvernoteImportDialog/geometry** (QByteArray): `<binary data>`
**FileDialog/LastPath** (QString): `/home/martin/tmp/Evernote/Notes`
**FileDialog/LastPath-Evernote Import** (QString): `/home/martin/tmp/Evernote`
**FileDialog/LastPath-ImportTextFiles** (QString): `/home/martin/tmp/Evernote/Notes`
**FileDialog/LastPath-InsertImage** (QString): `/home/martin/tmp/Qownnotes/media`
**ImageDialog/disableCopying** (QString): `true`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**JoplinImport/AttachmentImportCheckBoxChecked** (QString): `true`
**JoplinImport/FolderImportCheckBoxChecked** (QString): `false`
**JoplinImport/ImageImportCheckBoxChecked** (QString): `true`
**JoplinImport/MetadataImportCheckBoxChecked** (QString): `true`
**JoplinImport/TagImportCheckBoxChecked** (QString): `true`
**JoplinImportDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2022-02-04T17:56:17.919`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Monospace,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Ubuntu,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Monospace,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Ubuntu,10,-1,5,50,0,0,0,0,0`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `true`
**NoteFolder-1/NoteTabNameList** (QString): `Android Apps (Old)`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteHistory-1** (QVariantList): `<variant list with 89 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `88`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**checkSpelling** (bool): `true`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**darkMode** (QString): `false`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**dockWasInitializedOnce** (QString): `true`
**guiFirstRunInit** (bool): `true`
**initialLayoutIdentifier** (QString): `minimal`
**itemHeight** (QString): `18`
**markdownHighlightingEnabled** (QString): `true`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**notesPath** (QString): `/home/martin/tmp/Qownnotes`
**ownCloud/supportEnabled** (QString): `false`
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**savedSearches/noteFolder-1** (QStringList): `mobile.android, mobile.Android, And, android, andro, Alarm_at_Sumela, alarm, Alar, Net, Software_I've_got_a_license_for, Note 2022-02-01T19.04.56, f27e56ed4d99405dbc061cbbb2587f4d, 3fbd92d2f11a42f9bf1f753155f20be8, Note 2020-12-28T17.20.44, Note 2020-12-28T17.18.18`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**tagWasAddedToNote** (QString): `true`
**webAppClientService/token** (QString): `<hidden>`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`
**LANGUAGE**: `en_GB:en`
**USER**: `martin`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `1702`
**SHLVL**: `0`
**HOME**: `/home/martin`
**DESKTOP_SESSION**: `cinnamon`
**GIO_LAUNCHED_DESKTOP_FILE**: `/usr/share/applications/PBE.QOwnNotes.desktop`
**GTK_MODULES**: `gail:atk-bridge`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**NIX_PROFILES**: `/nix/var/nix/profiles/default /home/martin/.nix-profile`
**NIX_PATH**: `/home/martin/.nix-defexpr/channels`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**CINNAMON_VERSION**: `5.2.7`
**LIBVIRT_DEFAULT_URI**: `qemu:///system`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `127607`
**MANDATORY_PATH**: `/usr/share/gconf/cinnamon.mandatory.path`
**QT_QPA_PLATFORMTHEME**: `qt5ct`
**LOGNAME**: `martin`
**XDG_SESSION_CLASS**: `user`
**DEFAULTS_PATH**: `/usr/share/gconf/cinnamon.default.path`
**XDG_SESSION_ID**: `c2`
**GTK_OVERLAY_SCROLLING**: `1`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**PATH**: `/home/martin/.nix-profile/bin:/home/martin/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
**GDM_LANG**: `en_GB`
**GTK3_MODULES**: `xapp-gtk3-module`
**SESSION_MANAGER**: `local/martin-Aspire-5742:@/tmp/.ICE-unix/1630,unix/martin-Aspire-5742:/tmp/.ICE-unix/1630`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**DISPLAY**: `:0`
**LANG**: `en_GB.UTF-8`
**XDG_CURRENT_DESKTOP**: `X-Cinnamon`
**XDG_SESSION_DESKTOP**: `cinnamon`
**XAUTHORITY**: `/home/martin/.Xauthority`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/martin`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**SHELL**: `/bin/bash`
**QT_ACCESSIBILITY**: `1`
**GDMSESSION**: `cinnamon`
**NIX_SSL_CERT_FILE**: `/etc/ssl/certs/ca-certificates.crt`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**GJS_DEBUG_OUTPUT**: `stderr`
**XDG_VTNR**: `7`
**PWD**: `/home/martin`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-cinnamon:/etc/xdg`
**XDG_DATA_DIRS**: `/usr/share/cinnamon:/usr/share/gnome:/home/martin/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop`
</details>

**Comment by pbek** [comment]
The only enex files I have have their images (e.g. `<en-media type="image/jpeg" hash="b7855d6b42515056042e9f4d64e9489c" />`) at the end of the file. Do you have an example file where that is not the case?

**Comment by mcatkins** [comment]
I would have to make one which does not include personal information. I'll
try to do that during the week.
Martin

**Comment by mcatkins** [comment]
OK, I've just gone ahead and made the example.

I've attached screen shots of the note in Evernote (the app in windows),
and in QownNotes (under Linux).
I've attached the .enex file.

NB the images are images of text - don't get confused! The important thing
is where the lines of text appear!

Thanks,
Martin

**Comment by pbek** [comment]
Attachments don't seem to work via EMail...

**Comment by mcatkins** [comment]
!

OK, here they are (I had to zip the .enex file!)

![Note in Evernote (on windows)](https://user-images.githubusercontent.com/10836640/152671809-745d6bc9-02cb-48a8-8dbe-0c33a1e9ab63.png)
![Note in QownNotes (on Linux)](https://user-images.githubusercontent.com/10836640/152671812-6c62746f-b128-4022-9955-f6516151e59b.png)
[Test in-line images.enex.zip](https://github.com/pbek/QOwnNotes/files/8009674/Test.in-line.images.enex.zip)
:

**Comment by pbek** [comment]
I now added support for in-line images too...

## 22.2.1
- the Evernote import now supports importing images and attachments in-line

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by mcatkins** [comment]
Looks great to me. Thanks!

My only question is whether it should insert a new line before each image,
to match more closely the layout of the Evernotes note.

Martin

**Comment by pbek** [comment]
I don't know... There was no extra line your enex file `<div>line 1:</div><en-media style="--en-naturalWidth:419; --en-naturalHeight:51;" hash="c0a42ed00bd603e42b196f0f141d59d9" type="image/png" />`. And the image and the text are in separate lines in the markdown... It would destroy "real" in-line images when I enforce an extra newline in front of each image.

**Comment by mcatkins** [comment]
I just tried it, and AFAICS, Evernote does not allow "real" in-line images,
so not allowing them in the import would not be losing a capability. You
can always delete the blank line afterwards to unleash QOwnNotes' ability
:-). I would prefer the imported text to match the original as much as
possible, but it is your call!

Martin

**Comment by pbek** [comment]
...newline will be added silently with the next release.

**Comment by mcatkins** [comment]
Great! Thanks for the update!
