### ISSUE TITLE
How can I edit my own  editor color schema?

### ISSUE THREAD

**Issue by Cat7102** [pbek/QOwnNotes#2436]
Can I edit the editor color schema? The color and font size in my settings are not changeable, I export the .ini file, but I don't know how to edit the .ini file. Is there any help?

**Comment by pbek** [comment]
Select a schema you like to base yours upon and click the "Copy" button. 😁

**Comment by Cat7102** [comment]
> Select a schema you like to base yours upon and click the "Copy" button. 😁

Thank you for your help!
