### ISSUE TITLE
The Latex code can't display.

### ISSUE THREAD

**Issue by Cat7102** [pbek/QOwnNotes#2437]
I added the Latex Math plugin, and try to type: $x^2$ $\alpha$, but it just shows the blank file icon like this:
![image](https://user-images.githubusercontent.com/35393296/152537324-05c53468-3620-4aee-8243-c0eac6ab4d8c.png)

I tried reloading the plugin, but still not work.

**Comment by pbek** [comment]
Can you please open that issue on https://github.com/qownnotes/scripts/issues and mention the creators of the script.
