### ISSUE TITLE
Markdown Line Break not correctly working

### ISSUE THREAD

**Issue by DarkIrata** [pbek/QOwnNotes#244]
Hi,

default Markdown Linebreaking doesn't work.
You have to double break to split them or elese it will be "Foo Bar" instead of
"Foo
Bar"

Happens on Version 16.07.6

**Comment by pbek** [comment]
Thank you for reporting, do you mean you don't see single line breaks in the preview?
I'm sorry, markdown is supposed to work that way. Or do you mean anything else?

**Comment by DarkIrata** [comment]
Looked up the specification and yeah, used to it that's many sites set 1 <enter> as single line break or double <space> Think would be nice to have it here too. Would make Installation notes easyer to write.

Otherwise i awesome tool. :+1:

**Comment by Maboroshy** [comment]
The necessity to uses double space troubles me too. But it's a part of markdown specification. So if the app render markdown in its own way notes won't be readable in other markdown apps. So if there will be some option about that, it should have a warning.

I think the perfect way is having all single line breaks auto-converted to double spaces. But it may be too much pain to implement.

**Comment by pbek** [comment]
I think it would do more damage then good to simple interpret every line break as `<br>` in html, think of all the ways where you don't want that, like lists...

The markdown to html conversion is done by hoedown.
<https://github.com/pbek/QOwnNotes/tree/develop/src/libraries/hoedown>
see: <https://github.com/hoedown/hoedown>
You can always go and ask them if the implement such thing.

Our you can implement it as a user script. That is already possible in QOwnNotes with function `noteToMarkdownHtmlHook`. see: https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/example.qml
@DarkIrata, please let me know if you write such a script. ;)
