### ISSUE TITLE
[I] Custom toolbar configurations not saved

### ISSUE THREAD

**Issue by dohliam** [pbek/QOwnNotes#2451]
Issue: Configurations and customizations of the toolbar do not persist after restart.

#### Expected behaviour

Changes such as adding and removing buttons from the toolbars should persist across sessions/restarts. New toolbars created through the toolbar settings window should have their configurations saved rather than disappearing.

#### Actual behaviour

Toolbar settings are not saved after restart. Buttons added to toolbars disappear/reset across sessions. Changes do not persist and all configurations and menus are reset after restarting.

#### Steps to reproduce

This issue can be easily reproduced on a fresh install of QOwnNotes and the latest version of Manjaro (KDE Plasma edition):

1. Install [latest Manjaro Pahvo KDE](https://manjaro.org/downloads/official/kde/).
2. Install QOwnNotes following the official Arch instructions [here](https://www.qownnotes.org/installation/arch.html).
3. Go to Settings > Scripting > Add script... > Search Script Repository and install the script [Headline depth buttons](https://github.com/qownnotes/scripts/tree/master/headline-depth) (or any script with custom actions -- this is just an example).
4. Go to Settings > Toolbars and click `New` to create a new toolbar which will be named `custom_toolbar_1` by default. In the same settings window, select `Custom Actions` from the dropdown menu on the left, choose the button from the menu labelled `#+` and click on `Insert` to add it to `custom_toolbar_1`.
5. At this point, clicking on the `Apply toolbar configuration` button does not make a difference to the result, so click it (or not).
6. Click `OK` to close the window. Observe that the new Headline depth button has been added to the toolbar at the top right.
7. Click on the `Quit` button to exit the app.
8. Restart QOwnNotes. Note that the toolbar has been reset to its previous configuration and the custom action button has disappeared.
9. Repeat with different toolbar buttons. None of them persist after a restart.

This has also been tested on KDE Neon and on several different machines with the same results. It does not seem to be possible to get the toolbar to retain any settings across restarts.

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Thu Feb 10 21:13:25 2022`
**Version**: `22.2.3`
**Build date**: `Feb 10 2022`
**Build number**: `947`
**Platform**: `linux`
**Operating System**: `Manjaro Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/home/manjaro/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/manjaro/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1024x768`
**Icon theme**: `breeze`
**Notes in current note folder**: `2`
**Calendar items**: `0`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/home/manjaro/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-2`
**localPath**: `/home/manjaro/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/manjaro/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

### Script `Headline depth buttons`

**id**: `1`
**path**: `/home/manjaro/.local/share/PBE/QOwnNotes/scripts/headline-depth/headline-depth.qml`
**variablesJson**: *empty*
**identifier**: `headline-depth`
**version**: `0.0.2`
**minAppVersion**: `17.07.8`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (bool): `false`
**Editor/showLineNumbers** (bool): `false`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**FileDialog/LastPath** (QString): `/home/manjaro/Downloads`
**FileDialog/LastPath-ScriptPath** (QString): `/home/manjaro/Downloads`
**LastUpdateCheck** (QDateTime): `2022-02-10T21:03:26.404`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Hack,10,-1,7,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Hack,10,-1,7,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**NoteFolder-1/NoteTabNameList** (QStringList): `Note 2022-02-10T21.07.29`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `test`
**NoteFolder-1/allowDifferentNoteFileName** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 2 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `1`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**enableWebAppSupport** (bool): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (int): `24`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelAutoSelect** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/manjaro/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (bool): `true`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2022-02-10T21.07.29`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/7/items** (QStringList): *empty*
**toolbar/7/name** (QString): `custom_toolbar_1`
**toolbar/7/title** (QString): `custom_toolbar_1`
**toolbar/size** (int): `7`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**HOME**: `/home/manjaro`
**LANG**: `en_US.UTF-8`
**LOGNAME**: `manjaro`
**MAIL**: `/var/spool/mail/manjaro`
**PATH**: `/home/manjaro/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin`
**SHELL**: `/bin/bash`
**SYSTEMD_EXEC_PID**: `4793`
**USER**: `manjaro`
**XDG_DATA_DIRS**: `/home/manjaro/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**DESKTOP_SESSION**: `plasma`
**DISPLAY**: `:0`
**GTK2_RC_FILES**: `/etc/gtk-2.0/gtkrc:/home/manjaro/.gtkrc-2.0:/home/manjaro/.config/gtkrc-2.0`
**GTK3_MODULES**: `xapp-gtk3-module`
**GTK_MODULES**: `canberra-gtk-module`
**GTK_RC_FILES**: `/etc/gtk/gtkrc:/home/manjaro/.gtkrc:/home/manjaro/.config/gtkrc`
**KDE_APPLICATIONS_AS_SCOPE**: `1`
**KDE_FULL_SESSION**: `true`
**KDE_SESSION_UID**: `1000`
**KDE_SESSION_VERSION**: `5`
**MOTD_SHOWN**: `pam`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**PWD**: `/home/manjaro`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**QT_LINUX_ACCESSIBILITY_ALWAYS_ON**: `1`
**SESSION_MANAGER**: `local/manjaro:@/tmp/.ICE-unix/4002,unix/manjaro:/tmp/.ICE-unix/4002`
**SHLVL**: `0`
**XAUTHORITY**: `/home/manjaro/.Xauthority`
**XCURSOR_SIZE**: `24`
**XCURSOR_THEME**: `breeze_cursors`
**XDG_CONFIG_DIRS**: `/home/manjaro/.config/kdedefaults:/etc/xdg`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_SEAT**: `seat0`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_DESKTOP**: `KDE`
**XDG_SESSION_ID**: `1`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**XDG_SESSION_TYPE**: `x11`
**XDG_VTNR**: `1`
**MANAGERPID**: `3880`
**INVOCATION_ID**: `21825150992143f4aa0b8ee207416598`
**JOURNAL_STREAM**: `8:26422`

</details>

#### Relevant log output in the Log panel

n/a

**Comment by dohliam** [comment]
_Note:_ There are several previous issues that have been raised about toolbar customization:

* [Issue #1182](https://github.com/pbek/QOwnNotes/issues/1182) - Lost Toolbar Settings after Restart
* [Issue #975](https://github.com/pbek/QOwnNotes/issues/975) - Issue with panels and toolbars resetting on restart
* [Issue #481](https://github.com/pbek/QOwnNotes/issues/481) - (macOS) Toolbar customization not persistent

This is not a duplicate of these previous issues, which for the most part seem to have been resolved by clearing settings or starting with a new profile.

For this issue, resetting, reinstalling, clearing settings etc does not resolve the problem.

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue.

**Comment by Waqar144** [comment]
reproduces, but only with actions from scripts. Builtin actions seem to retain their position across restarts

**Comment by pbek** [comment]
## 22.2.5
- toolbar configuration from actions that were generated by custom scripting actions
  are now saved correctly again (for [#2451](https://github.com/pbek/QOwnNotes/issues/2451), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by dohliam** [comment]
Fantastic! Tested and everything is working perfectly again in the new release.

Thanks so much @pbek and @Waqar144 for fixing this so quickly! :+1:

**Comment by pbek** [comment]
Great, thank you for testing!
