### ISSUE TITLE
Minor issue with lists

### ISSUE THREAD

**Issue by SBaldrick** [pbek/QOwnNotes#2453]
Hi there, I'd like to report a minor bug : 
In markdown window, I wish to continue a list already started further up the text. So here I go :
2. 

#### Expected behaviour in the preview window :  
2.

#### Actual behaviour  
1.

#### Steps to reproduce  
Begin the list with
1.  
then a paragraph that is regular text, inserted between 1. and 2.  
Then as I said, continue the list with a new heading numbered   
2. 
The preview starts again from 1.

If someone knows what the issue is...
Thx
Phil

**Comment by pbek** [comment]
I'm sorry. I don't think I understand your instruction how to reproduce your issue... 
Can you please describe step by step what you did to reproduce this issue? Maybe add a text example...

**Comment by SBaldrick** [comment]
I'll attach a screencap to make it absolutely clear :  
![Screencap](https://user-images.githubusercontent.com/98108095/153761732-8a8ee040-85f0-4f26-b352-e0343ca7bd04.png)

**Comment by pbek** [comment]
When an ordered list is shown in a web browser (or in the QTextBrowser of the preview) the browser decides the numbering of the entries. You were starting two ordered lists, so they both start with `1`.

**Comment by SBaldrick** [comment]
Fair enough. Now how do I decide what number to start with ? Is seems plain enough that I'm actually continuing a list that has begun beforehand, therefore it soesn't make sense for the browser to decide in my place... Is there sth I can do ?

**Comment by SBaldrick** [comment]
Oddly enough, on my smartphone app (nextcloud notes), the numbering is all correct. And so it is in the nextcloud web app in Firefox. Are we sure there isn't something about QOwnNotes that we could put right ?

**Comment by pbek** [comment]
I guess they are not using real ordered lists for the ordered list markdown...

If you use this markdown:

```
Ordered List Test
====

1. test

some text in between

2. test2
```

...show it in the QOwnNotes preview. Right click the preview. Export the raw html. Open that html in a browser. You will see the `<ol>` in the source code and the two `1.` in the browser.

**Comment by SBaldrick** [comment]
I did exactly what you said : 
I include the two screencaps : browser and source code. I guess the issue is : QOwnNotes does not recognize the 
`<ol` start="[2]()">

![Screenshot 2022-02-14 at 10-07-13 Screenshot](https://user-images.githubusercontent.com/98108095/153833611-7c5840b6-c9be-4f93-987a-ea72ae12b187.png)
![Capture d’écran du 2022-02-14 10-08-07](https://user-images.githubusercontent.com/98108095/153833634-303db5c8-cc54-4a4c-a006-71f595d07c5b.png)

Thanks again for looking into this... I realize it's not such a big deal, but it upsets me when softwares do not do as I tell them without apparent reason... :p

**Comment by pbek** [comment]
> <ol start="[2](https://github.com/pbek/QOwnNotes/issues/2453#issuecomment-1038833006)">

It's a QTextBrowser that does the rendering.

**Comment by SBaldrick** [comment]
Be that as it may, I want my lists to appear as I want them, there is no reason that my 2 be replaced by a 1, or I would have started a new list by writing "1". Is there anything I can do ?

**Comment by pbek** [comment]
Not easily I guess, but there is a scripting hook https://www.qownnotes.org/scripting/hooks.html#notetomarkdownhtmlhook where you could modify the html of the preview.

**Comment by SBaldrick** [comment]
Well, that's way beyond my capabilities... It didn't seem like that big a deal, I would have thought a minor update would have solved the problem... Should I file a feature request ?

**Comment by pbek** [comment]
@Waqar144, do you know if md4c can "fake" ordered lists?

**Comment by Waqar144** [comment]
no, and it won't because its upto the renderer. MD4C is doing the right thing already by putting in `start`.

**Comment by Waqar144** [comment]
However, fixed it for litehtml backend. https://github.com/pbek/QOwnNotes/pull/2455
