### ISSUE TITLE
Use UNC path in attachments

### ISSUE THREAD

**Issue by CptAFK** [pbek/QOwnNotes#2464]
I apologize for the mistakes. My English is very bad and I am not familiar with the correct design on the github.

**If use UNC paths in attachments, link don't open file.**

Attachment file by menu/edit/insert/insert attachment
`[Relative path](file://attachments/536117841-1.isb)
`
[12:29:09] [warning] ShellExecute 'file://///fileserver/ggg/nnn/dddd//MarkDown/Tasks/attachments/536117841-1.isb' failed (error 3).

If edit himself
`[Relative path](file:/attachments/536117841-1.isb)`

[12:32:04] [warning] ShellExecute 'file://///fileserver/ggg/nnn/dddd/MarkDown/Tasks/fileserver/ggg/nnn/dddd//MarkDown/Tasks/!Очередь/Договора/file:/attachments/536117841-1.isb' failed (error 3).

`good open [Full path](file:////fileserver/ggg/nnn/dddd/MarkDown/Tasks/attachments/536117841.isb)`

QOwnNotes use himself paths. 

If Notes Folder "//fileserver/ggg/nnn/dddd//MarkDown/Tasks"
On "Use note subfolders"

**In addition to these problems, there is also such an error**

if insert attachment file by menu/edit/insert/insert attachment in note by path "//fileserver/ggg/nnn/dddd/MarkDown/Tasks/Query" file copy by "//fileserver/ggg/nnn/dddd//MarkDown/Tasks/attachment" and make link bad link 
[file](file://attachments/536117841-1.isb)

correct link [file](file://../attachments/536117841-1.isb) or correct copy file by "//fileserver/ggg/nnn/dddd/MarkDown/Tasks/Query/attachment"

**Proper use of ShellExecute with UNC paths**
```
ShellExecute (0, NULL, ".", NULL, NULL, SW_MAXIMIZE); // Working directory (for this process)
ShellExecute (0, NULL, "..", NULL, NULL, SW_MAXIMIZE); // One level higher
ShellExecute (0, NULL, "\\", NULL, NULL, SW_MAXIMIZE); // Root folder for the current disk
ShellExecute (0, NULL, "\\\\server\\share\\folder", NULL, NULL, SW_MAXIMIZE); // Folder on the server
```

**Comment by pbek** [comment]
>  [Relative path](file://attachments/536117841-1.isb) 

That is no UNC path, that's a URL, isn't it? UNC paths aren't supported. As for URLs, they need to contain a full path. 😉

**Comment by CptAFK** [comment]
If Notes Folder on local disk - add Attachment file by menu/edit/insert/insert attachment - link work
If Notes Folder on shared disk - add Attachment file by menu/edit/insert/insert attachment - link error

I can take video, ok? my English very bad =(

**Comment by pbek** [comment]
You didn't fill out the issue template, it's hard to help you. 😅 

Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.

Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting Debug in Options).

I don't know how Qt handles shared folders under Windows (I assume you are working on Windows). Best mount them to a drive letter.
