### ISSUE TITLE
New editor schema: <calm and simple>

### ISSUE THREAD

**Issue by nils-se** [pbek/QOwnNotes#2465]
Hello, I want to submit a new editor schema. I just removed all backgrounds and made the headlines black. I tried Notable and found their styling to be more calm but wanted to stay with QOwnNotes. So I thought about what made Notable more "simple" and tried to work towards their style.

One added question: Is there a way to add some padding/space to the left side of the preview? All texts are quite crammed up against the left side.

And last but not least: Thanks for the app and your great work :)

[EditorColorSchema-5df709db-4bc6-41c8-af15-04413b8186fa]
BackgroundColorEnabled_-1=true
BackgroundColorEnabled_0=false
BackgroundColorEnabled_1=true
BackgroundColorEnabled_1000=false
BackgroundColorEnabled_1001=false
BackgroundColorEnabled_1002=false
BackgroundColorEnabled_1003=false
BackgroundColorEnabled_1004=false
BackgroundColorEnabled_1005=false
BackgroundColorEnabled_1006=false
BackgroundColorEnabled_11=false
BackgroundColorEnabled_12=false
BackgroundColorEnabled_13=false
BackgroundColorEnabled_14=false
BackgroundColorEnabled_15=false
BackgroundColorEnabled_16=false
BackgroundColorEnabled_17=false
BackgroundColorEnabled_18=false
BackgroundColorEnabled_19=true
BackgroundColorEnabled_2=true
BackgroundColorEnabled_21=false
BackgroundColorEnabled_22=false
BackgroundColorEnabled_23=false
BackgroundColorEnabled_25=false
BackgroundColorEnabled_28=false
BackgroundColorEnabled_3=false
BackgroundColorEnabled_4=false
BackgroundColorEnabled_8=false
BackgroundColor_-1=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0)
BackgroundColor_0=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xf8\xf8\xef\xef\0\0)
BackgroundColor_1=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xf2\xf2\xe4\xe4\0\0)
BackgroundColor_1000=@Variant(\0\0\0\x43\x1\xff\xff\xed\xed\xfc\xfc\xed\xed\0\0)
BackgroundColor_1001=@Variant(\0\0\0\x43\x1\xff\xff\xed\xed\xfc\xfc\xed\xed\0\0)
BackgroundColor_1002=@Variant(\0\0\0\x43\x1\xff\xff\xed\xed\xfc\xfc\xed\xed\0\0)
BackgroundColor_1003=@Variant(\0\0\0\x43\x1\xff\xff\xed\xed\xfc\xfc\xed\xed\0\0)
BackgroundColor_1004=@Variant(\0\0\0\x43\x1\xff\xff\xed\xed\xfc\xfc\xed\xed\0\0)
BackgroundColor_1005=@Variant(\0\0\0\x43\x1\xff\xff\xed\xed\xfc\xfc\xed\xed\0\0)
BackgroundColor_1006=@Variant(\0\0\0\x43\x1\xff\xff\xed\xed\xfc\xfc\xed\xed\0\0)
BackgroundColor_11=@Variant(\0\0\0\x43\x1\xff\xff\xaa\xaa\xf7\xf7\xff\xff\0\0)
BackgroundColor_12=@Variant(\0\0\0\x43\x1\xff\xff\xf1\xf1\xf1\xf1\xf4\xf4\0\0)
BackgroundColor_13=@Variant(\0\0\0\x43\x1\xff\xff\xf1\xf1\xf1\xf1\xf4\xf4\0\0)
BackgroundColor_14=@Variant(\0\0\0\x43\x1\xff\xff\xf1\xf1\xf1\xf1\xf4\xf4\0\0)
BackgroundColor_15=@Variant(\0\0\0\x43\x1\xff\xff\xf1\xf1\xf1\xf1\xf4\xf4\0\0)
BackgroundColor_16=@Variant(\0\0\0\x43\x1\xff\xff\xf1\xf1\xf1\xf1\xf4\xf4\0\0)
BackgroundColor_17=@Variant(\0\0\0\x43\x1\xff\xff\xf1\xf1\xf1\xf1\xf4\xf4\0\0)
BackgroundColor_18=@Variant(\0\0\0\x43\x1\xff\xff\xf5\xf5\xf9\xf9\xd8\xd8\0\0)
BackgroundColor_19=@Variant(\0\0\0\x43\x1\xff\xff\xe2\xe2\xe7\xe7\xe2\xe2\0\0)
BackgroundColor_2=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xf2\xf2\xe4\xe4\0\0)
BackgroundColor_21=@Variant(\0\0\0\x43\x1\xff\xff\xeb\xeb\xeb\xeb\xeb\xeb\0\0)
BackgroundColor_22=@Variant(\0\0\0\x43\x1\xff\xff\xf7\xf7\xf6\xf6\xff\xff\0\0)
BackgroundColor_23=@Variant(\0\0\0\x43\x1\xff\xff\xed\xed\xfc\xfc\xed\xed\0\0)
BackgroundColor_25=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xfa\xfa\xe2\xe2\0\0)
BackgroundColor_28=@Variant(\0\0\0\x43\x1\xff\xff\xeb\xeb\xeb\xeb\xeb\xeb\0\0)
BackgroundColor_3=@Variant(\0\0\0\x43\x1\xff\xff\xed\xed\xff\xff\xed\xed\0\0)
BackgroundColor_4=@Variant(\0\0\0\x43\x1\xff\xff\xed\xed\xfc\xfc\xed\xed\0\0)
BackgroundColor_8=@Variant(\0\0\0\x43\x1\xff\xff\xdb\xdb\xf9\xf9\xe5\xe5\0\0)
Bold_12=true
Bold_13=true
Bold_14=true
Bold_15=true
Bold_16=true
Bold_17=true
Bold_8=true
FontSizeAdaption_12=200
FontSizeAdaption_13=160
FontSizeAdaption_14=130
FontSizeAdaption_15=100
FontSizeAdaption_16=90
FontSizeAdaption_17=90
FontSizeAdaption_8=100
ForegroundColorEnabled_-1=true
ForegroundColorEnabled_0=true
ForegroundColorEnabled_1=true
ForegroundColorEnabled_10=true
ForegroundColorEnabled_1000=true
ForegroundColorEnabled_1001=true
ForegroundColorEnabled_1002=true
ForegroundColorEnabled_1003=true
ForegroundColorEnabled_1004=true
ForegroundColorEnabled_1005=true
ForegroundColorEnabled_1006=true
ForegroundColorEnabled_11=true
ForegroundColorEnabled_12=true
ForegroundColorEnabled_13=true
ForegroundColorEnabled_14=true
ForegroundColorEnabled_15=true
ForegroundColorEnabled_16=true
ForegroundColorEnabled_17=true
ForegroundColorEnabled_18=true
ForegroundColorEnabled_19=true
ForegroundColorEnabled_2=true
ForegroundColorEnabled_20=true
ForegroundColorEnabled_21=true
ForegroundColorEnabled_22=true
ForegroundColorEnabled_23=true
ForegroundColorEnabled_24=true
ForegroundColorEnabled_26=true
ForegroundColorEnabled_29=true
ForegroundColorEnabled_3=true
ForegroundColorEnabled_30=true
ForegroundColorEnabled_4=true
ForegroundColorEnabled_5=true
ForegroundColorEnabled_6=true
ForegroundColorEnabled_7=true
ForegroundColorEnabled_8=true
ForegroundColorEnabled_9=true
ForegroundColor_-1=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
ForegroundColor_0=@Variant(\0\0\0\x43\x1\xff\xff\xfc\xfc~~\0\0\0\0)
ForegroundColor_1=@Variant(\0\0\0\x43\x1\xff\xff\xfc\xfc~~\0\0\0\0)
ForegroundColor_10=@Variant(\0\0\0\x43\x1\xff\xff\xa3\xa3\0\0{{\0\0)
ForegroundColor_1000=@Variant(\0\0\0\x43\x1\xff\xff\xf9\xf9&&rr\0\0)
ForegroundColor_1001="@Variant(\0\0\0\x43\x1\xff\xff;;\xa2\xa2??\0\0)"
ForegroundColor_1002=@Variant(\0\0\0\x43\x1\xff\xff\x90\x90\x8b\x8btt\0\0)
ForegroundColor_1003=@Variant(\0\0\0\x43\x1\xff\xff\x63\x63mm\xef\xef\0\0)
ForegroundColor_1004=@Variant(\0\0\0\x43\x1\xff\xff\xb5\xb5||PP\0\0)
ForegroundColor_1005=@Variant(\0\0\0\x43\x1\xff\xff\xae\xae\x81\x81\xff\xff\0\0)
ForegroundColor_1006=@Variant(\0\0\0\x43\x1\xff\xff\xf9\xf9&&rr\0\0)
ForegroundColor_11=@Variant(\0\0\0\x43\x1\xff\xff\xab\xab\xab\xab\xab\xab\0\0)
ForegroundColor_12=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
ForegroundColor_13=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
ForegroundColor_14=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
ForegroundColor_15=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
ForegroundColor_16=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
ForegroundColor_17=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
ForegroundColor_18=@Variant(\0\0\0\x43\x1\xff\xff\xaa\xaa\0\0\0\0\0\0)
ForegroundColor_19=@Variant(\0\0\0\x43\x1\xff\xff\0\0\x80\x80\0\0\0\0)
ForegroundColor_2=@Variant(\0\0\0\x43\x1\xff\xff\xfc\xfc~~\0\0\0\0)
ForegroundColor_20="@Variant(\0\0\0\x43\x1\xff\xff======\0\0)"
ForegroundColor_21=@Variant(\0\0\0\x43\x1\xff\xff\x39\x39\x39\x39\x39\x39\0\0)
ForegroundColor_22=@Variant(\0\0\0\x43\x1\xff\xffNN\x18\x18\xb9\xb9\0\0)
ForegroundColor_23=@Variant(\0\0\0\x43\x1\xff\xff\0\0ll\0\0\0\0)
ForegroundColor_24=@Variant(\0\0\0\x43\x1\xff\xff\xcc\xcc\xcc\xcc\xcc\xcc\0\0)
ForegroundColor_26=@Variant(\0\0\0\x43\x1\xff\xff\xff\xffUU\0\0\0\0)
ForegroundColor_29=@Variant(\0\0\0\x43\x1\xff\xff\xbf\xbf\0\0\0\0\0\0)
ForegroundColor_3=@Variant(\0\0\0\x43\x1\xff\xff\0\0\xbf\xbf\0\0\0\0)
ForegroundColor_30=@Variant(\0\0\0\x43\x1\xff\xff\0\0~~\0\0\0\0)
ForegroundColor_4=@Variant(\0\0\0\x43\x1\xff\xff\0\0ll\0\0\0\0)
ForegroundColor_5="@Variant(\0\0\0\x43\x1\xff\xff======\0\0)"
ForegroundColor_6="@Variant(\0\0\0\x43\x1\xff\xff======\0\0)"
ForegroundColor_7=@Variant(\0\0\0\x43\x1\xff\xff\0\0WW\xae\xae\0\0)
ForegroundColor_8=@Variant(\0\0\0\x43\x1\xff\xff\0\0\x42\x42\x8a\x8a\0\0)
ForegroundColor_9=@Variant(\0\0\0\x43\x1\xff\xff\xa3\xa3\0\0{{\0\0)
Italic_7=true
Name=calm and simple
Underline_26=true
Underline_31=true

[Export]
SchemaKey=EditorColorSchema-5df709db-4bc6-41c8-af15-04413b8186fa

**Comment by pbek** [comment]
I can see no difference to the "Light" theme, only that there are no background colors. Was that your intention or is something wrong (maybe best export a file and don't post it directly inline)...

> One added question: Is there a way to add some padding/space to the left side of the preview? All texts are quite crammed up against the left side.

You can use the distraction mode margins also in non distraction free mode with a setting or you can inject CSS styles into the preview with a script.

> And last but not least: Thanks for the app and your great work :)

Thank you 😁

**Comment by nils-se** [comment]
@pbek: You are right, I only removed the backgrounds and made the headlines black instead of blue. For me it feels way more calm. But I understand if these changes are to minor to add a new theme :)

Thanks and feel free to close :)

**Comment by nils-se** [comment]
> I don't care. I just wanted to know if everything was correct (because you didn't post a file).

I couldn't add the .ini-file. github won't let me and says file-type is not supported. So I just copy pasted the ini-content. Attatched is the ini as a .txt-file :)

[calm and simple.txt](https://github.com/pbek/QOwnNotes/files/8088825/calm.and.simple.txt)

**Comment by nils-se** [comment]
> ## 22.2.7
> * added a new editor color schema _Calm and Simple_ by @nils-se
> 
> There now is a new release, could you please test it and report if it works for you?

sorry was on vacation, tested and it works, thank you :+1:

**Comment by pbek** [comment]
Great! Welcome back. 😁

**Comment by Ellipsine** [comment]
Hi :) I would like to understand : what kind of code color does QownNotes use ? For example, if I have this hex code : "#998c7c", how do I translate it for a QownNotes theme ? I am sorry for my dummy question, I made research but I did not find anything >_<

**Comment by pbek** [comment]
You can enter those color codes in the color picker...

<img width="948" alt="image" src="https://user-images.githubusercontent.com/1798101/156595895-22ca8201-ab00-426c-a2e3-82871668ca5f.png">

**Comment by Ellipsine** [comment]
I would, if it worked at home.

**Comment by pbek** [comment]
Can you please describe step by step what you did?
