### ISSUE TITLE
Javascript in code blocks treated as Java

### ISSUE THREAD

**Issue by dohliam** [pbek/QOwnNotes#2468]
Issue: Using `javascript` as the language name causes code blocks to be highlighted as Java. Using `js` highlights the code correctly.

#### Expected behaviour

Using either `js` and `javascript` should have the same effect on highlighted code.

#### Actual behaviour

`javascript` causes code to be highlighted as if it was Java, while `js` correctly highlights code as JavaScript.

#### Steps to reproduce

Paste the following code in QOwnNotes:

	```javascript
	function random(min, max) {
	   let num = Math.floor(Math.random() * (max - min)) + min;
	   return num;
	}
	```

	```js
	function random(min, max) {
	   let num = Math.floor(Math.random() * (max - min)) + min;
	   return num;
	}
	```

Screenshot showing how QOwnNotes highlights the two examples above:

![image](https://user-images.githubusercontent.com/9295750/154782881-6ed1ac98-1a20-4dbf-99a0-5d003936c7f4.png)

## Solution

This issue appears to be caused by [this line](https://github.com/pbek/QOwnNotes/blob/develop/src/helpers/codetohtmlconverter.cpp#L35) in `codetohtmlconverter.cpp`:

```cpp
        {QStringLiteral("javascript"), CodeToHtmlConverter::CodeJava},
```

It looks like this line should be changed to the following:

```cpp
        {QStringLiteral("javascript"), CodeToHtmlConverter::CodeJs},
```

If this is correct, I would be happy to submit a PR to fix the issue.

**Comment by pbek** [comment]
> If this is correct, I would be happy to submit a PR to fix the issue.

Yes, please. Looks good to me.

@Waqar144, any objections?

**Comment by Waqar144** [comment]
Good catch. +1

**Comment by pbek** [comment]
## 22.2.8
- Javascript in code blocks are now treated as Javascript instead of Java
  (for [#2468](https://github.com/pbek/QOwnNotes/issues/2468), thank you, @dohliam)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by dohliam** [comment]
Great, it looks like that fixed the preview text! However, I noticed that code is still highlighted incorrectly in the edit window (see screenshot below -- edit window is on the left, preview on the right):

![image](https://user-images.githubusercontent.com/9295750/155444174-6f359088-2aa7-4ed0-b75b-34e3ef3542a7.png)

Is syntax highlighting in the edit window handled by a different algorithm than the preview?

**Comment by pbek** [comment]
Great, thank you for testing!

> Is syntax highlighting in the edit window handled by a different algorithm than the preview?

I'm not even sure any more, @Waqar144?

**Comment by Waqar144** [comment]
Is syntax highlighting in the edit window handled by a different algorithm than the preview?

slightly, yes.
