### ISSUE TITLE
QON crashes in the scripting tab

### ISSUE THREAD

**Issue by LightTemplar** [pbek/QOwnNotes#247]
1) go to settings, scripting tab
2) make sure, you have no scripts
3) press "Add Script", then "Remove Script"
4) Go to another tab (I went to "General")
5) Crash!

**Comment by pbek** [comment]
Will be fixed in v16.07.7.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by LightTemplar** [comment]
Yes, it works now.
