### ISSUE TITLE
Add support for ruby text <ruby>

### ISSUE THREAD

**Issue by williamd1k0** [pbek/QOwnNotes#2471]
The `<ruby>` HTML element represents small annotations that are rendered above, below, or next to base text, usually used for showing the pronunciation of East Asian characters.

More technical info: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ruby

#### Expected behaviour

<blockquote>
<ruby>
漢字 <rt>かんじ</rt>
</ruby>
</blockquote>

#### Actual behaviour

<blockquote>
<ruby>
漢字かんじ
</ruby>
</blockquote>

#### Steps to reproduce

Use the following snippet to reproduce:
```html
<ruby>漢字<rt>かんじ</rt></ruby>
```

**Comment by pbek** [comment]
I don't think QTextBrowser (used for the preview) supports this tag.
I couldn't find anything if QLiteHtml supports it (@Waqar144, do you know more?)

**Comment by Waqar144** [comment]
Pretty sure we don't support it yet

**Comment by williamd1k0** [comment]
Does this help in any way?
https://smallhax.wordpress.com/2014/10/19/ruby-furigana-in-pure-css/

**Comment by pbek** [comment]
There is a script in the script repository to inject css into to preview. You can play around with that.

**Comment by williamd1k0** [comment]
I tried here and it didn't work, perhaps it doesn't support some specific css properties.
