### ISSUE TITLE
compiler failed on ubuntu 20.04 Qt 13.2 

### ISSUE THREAD

**Issue by bolunfeng** [pbek/QOwnNotes#2474]
Info: creating stash file /home/fengbolun/workspace/QOwnNotes/src/.qmake.stash
Cannot read /home/fengbolun/workspace/QOwnNotes/src/libraries/qmarkdowntextedit/qmarkdowntextedit.pri: No such file or directory
Cannot read /home/fengbolun/workspace/QOwnNotes/src/libraries/piwiktracker/piwiktracker.pri: No such file or directory
Cannot read /home/fengbolun/workspace/QOwnNotes/src/libraries/qkeysequencewidget/qkeysequencewidget/qkeysequencewidget.pri: No such file or directory
Cannot read /home/fengbolun/workspace/QOwnNotes/src/libraries/qttoolbareditor/toolbar_editor.pri: No such file or directory
Cannot read /home/fengbolun/workspace/QOwnNotes/src/libraries/qhotkey/qhotkey.pri: No such file or directory

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Please see: https://www.qownnotes.org/installation/building.html#building-from-github
