### ISSUE TITLE
Windows Store warning

### ISSUE THREAD

**Issue by StarkeEnrico** [pbek/QOwnNotes#2475]
Hi all,

if I open up QOwnNotes v22.2.8 in Windows 10 Pro 21H1, I get a popup from Windows Store to search for the App. I have attached a screenshot of the popup.
If I disable the security check in 
Windows Security -> App & browser control -> Reputation-based protection settings -> Turn off the Check apps and files .
QOwnNotes opens without this popup. I suspect this behaviour is because the exe of QOwnNotes is not signed. Please can you Code
Sign the Windows App with a valid certificate, so that I don't need to disable Windows Security features to run the App?

Best

Enrico
![image](https://user-images.githubusercontent.com/56999583/155622589-7a9e7e73-7730-4aab-9bb9-93f45de4a429.png)

**Comment by pbek** [comment]
> Please can you Code
> Sign the Windows App with a valid certificate, so that I don't need to disable Windows Security features to run the App?

As much as I'd love to have that, it's not as easy as it sounds...
And then would have to be automated into the build pipeline.
If you are volunteering to research and integrate that I'm very open for advice and pull requests.
