### ISSUE TITLE
regenerateNotePreview do not regenerate a modified image (outside QON)

### ISSUE THREAD

**Issue by Beurt** [pbek/QOwnNotes#2477]
I am working on "render-plantuml" script to introduce async generation of the diagrams. I ran into a problem with `regenerateNotePreview`

#### Expected behaviour

In the work in progress available here https://github.com/Beurt/scripts/commit/7419c19e070ad914f1955d868972c4bf841a9b3e I managed to use [`startDetachedProcess` to launch PlantUML](https://github.com/Beurt/scripts/blob/master/render-plantuml/render-plantuml.qml#L108) and [`onDetachedProcessCallback` to get a callback when the image generation is complete](https://github.com/Beurt/scripts/blob/master/render-plantuml/render-plantuml.qml#L127). To regenerate the preview (with new images) [I used `script.regenerateNotePreview();`](https://github.com/Beurt/scripts/blob/master/render-plantuml/render-plantuml.qml#L129). It was supposed to regenerate the preview with the generated images (the images are properly generated in their directory)

#### Actual behaviour

Unfortunately, the text in the preview is properly regenerated but not the image (even if the images changed in their directory). To have the correct image in the preview it is needed to type something in order to manually regenerate the preview.

The same occurs with the Scribble script.

#### Steps to reproduce

- Download and install https://github.com/Beurt/scripts/blob/master/render-plantuml/render-plantuml.qml.
- try to render a diagram  
````
```plantuml
Bob->Alice : hello
```
````
- observe that the images are not properly updated even if they are correctly generated

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `ven. févr. 25 23:08:40 2022`
**Version**: `22.2.8`
**Build date**: `Feb 23 2022`
**Build number**: `952`
**Platform**: `linux`
**Operating System**: `KDE neon User - 5.24`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AppImage`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/home/xxx/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/xxx/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/home/xxx/QOwnNotes.AppImage`
**Qt Debug**: `0`
**Locale (system)**: `fr_FR`
**Locale (interface)**: `fr`
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080`
**Icon theme**: `MyBreeze`
**Notes in current note folder**: `289`
**Calendar items**: `19`
## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/xxx/notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**allowDifferentNoteFileName**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/xxx/notes/notes.sqlite`

## Enabled scripts
A lot !

</details>

**Comment by pbek** [comment]
I will try to reproduce your issue.

**Comment by pbek** [comment]
Do you have an example where you don't need to have java and plantuml.jar?

**Comment by Beurt** [comment]
Yes of course, you are right, sorry @pbek!

Here is an example script that should work but don't work for me:

```qml
import QtQml 2.0
import QOwnNotesTypes 1.0

/**
 * This script adds a menu entry to the context menu of the note edit to refresh the preview
 */
Script {

    /**
     * Initializes the custom actions
     */
    function init() {
        script.registerCustomAction("testing-refresh", "Refresh", "Refresh", "view-preview", true, false, false);
    }

    /**
     * This function is invoked when a custom action is triggered
     * in the menu or via button
     * 
     * @param identifier string the identifier defined in registerCustomAction
     */
    function customActionInvoked(identifier) {
        if (identifier != "testing-refresh") {
            return;
        }
        // Just refresh the preview
        script.regenerateNotePreview();
        script.log(`refresh`);
    }
}

```
The script just create a button to regenerate the preview with `regenerateNotePreview`.

If I create a note with an image `![Something](any_path_to_an_image)` and I modify this image with an external editor (such as Gimp or whatever), I expect that when I press the button meant to regenerate the preview, the image is shown with the modifications I have made. For me, it doesn't work: the image shown is the original one, not the modified one.

Are you able to reproduce that?

**Comment by pbek** [comment]
The problem is that the markdown isn't changing so the images aren't loaded again.

**Comment by Beurt** [comment]
So if I really want to refresh (without changing the Markdown), I need to use a trick such as adding a trailing space, regenerate then removing the space?

**Comment by pbek** [comment]
## 22.2.10
- there now is a new scripting function `script.forceRegenerateNotePreview()` to
  force the regeneration of the note preview  (for [#2477](https://github.com/pbek/QOwnNotes/issues/2477))
    - for more information please take a look at the [scripting documentation](https://www.qownnotes.org/scripting/methods-and-objects.html#forcing-regeneration-of-the-note-preview)

**Comment by Beurt** [comment]
Thank you a lot, I will test ASAP!

**Comment by pbek** [comment]
On the other hand... Why do we need a new command...

## 22.2.10
- the scripting function `script.regenerateNotePreview()` now also regenerates the
  note preview if the note wasn't changed (for [#2477](https://github.com/pbek/QOwnNotes/issues/2477))
    - for more information please take a look at the [scripting documentation](https://www.qownnotes.org/scripting/methods-and-objects.html#regenerating-the-note-preview)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Beurt** [comment]
It seems to work perfectly! Thanks a lot!

**Comment by pbek** [comment]
Great! 😉

**Comment by Beurt** [comment]
Unfortunately, in my use case (render-plantuml script) I still have an issue that I did not foresee.

The problem is that I use `script.regenerateNotePreview();` like this:

```qml
    function onDetachedProcessCallback(callbackIdentifier, resultSet, cmd, thread) {
        if (callbackIdentifier == "plantuml-callback" + noteId) {
            // script.regenerateNotePreview();
            script.log(`refresh`);
        }
```

And it seems that when `script.regenerateNotePreview();` is ran, all the scripts are run again, so it's an endless loop!

Do you think there is a solution to refresh the preview in the hook, without running the scripts? Or just an new hook to refresh the images only?

**Comment by pbek** [comment]
You cannot tell the QTextBrowser of the preview to "refresh images". You can only input (no so) new html into the QTextBrowser to render.

And it seems you are executing the regenerateNotePreview in `noteToMarkdownHtmlHook`, which is the cause for your infinite loop. 😉

**Comment by pbek** [comment]
Maybe add something to "detect" if you really need to call regenerateNotePreview and only call it once...

**Comment by Beurt** [comment]
🤔 the idea was to run PlantUML detached to allow users continue typing while the diagram is generated. I wanted to use the callback, when PlantUML was done generating the diagram, to refresh the preview. But, I did not foresee that `script.regenerateNotePreview()` was running the scripts again thus entering an endless loop.

For the moment, I don't see any other means to check if PlantUML has generated the diagram than `onDetachedProcessCallback`. The solution is maybe to be sure to execute `script.regenerateNotePreview()` once... But, I don't know how!

**Comment by pbek** [comment]
noteToMarkdownHtmlHook will definitely be called if you run regenerateNotePreview.

**Comment by Beurt** [comment]
You are right. Maybe for such scripts (lauching async programs that modify the preview) we need a different hook? For instance a hook detecting that the user stopped typing (a pause in text flow). There is several [examples in JS](https://attacomsian.com/blog/javascript-detect-user-stops-typing), but I cannot fond one for QT.

**Comment by pbek** [comment]
what where you trying to achieve?

**Comment by Beurt** [comment]
I am trying to transform the [render-plantuml](https://github.com/qownnotes/scripts/tree/master/render-plantuml) script to make it asynchronous. Meaning, currently, when you hit a key, the script (synchronous) launch PlantUML (a java program to render diagrams) and wait for the result to let the user of QON do anything more. Thus, because it is using `startSynchronousProcess`, the user is stalled until the diagram is rendered.

I am working on a new version with a detach launch of PlantUML: the java program is rendering the diagram in background (`startDetachedProcess`), so the script let the user continue typing. At the end of the diagram render (`onDetachedProcessCallback`), I want to refresh the image inserted in the preview. This why I used `regenerateNotePreview` in the hook `onDetachedProcessCallback`. My current attempt is here : https://github.com/Beurt/scripts/blob/master/render-plantuml/render-plantuml.qml

I am yet working on flags, used with `setPersistentVariable`, to avoid entering the endless loop aforementioned.

Another solution is, to use a different hook than `noteToMarkdownHtmlHook` which can detect when the user stop typing, in order to launch PlantUML, wait for the PLantUML callback and launch the preview refresh with `regenerateNotePreview` without entering an endless loop (since we will not use `noteToMarkdownHtmlHook` anymore).

I am not sure, if my explanation is efficient!  😅

**Comment by pbek** [comment]
There is no Qt API to detect when the user stops typing... Hm, if you can detect if the generated images need refreshing you could simply regenerate the images every X seconds (only when they need to be updated).

**Comment by Beurt** [comment]
For now, I'm trying with persistent flags (and I already have an OK. results with some inconsistencies that I have to work on: https://github.com/Beurt/scripts/blob/9e782b09704d48d4bef34b7d9af39cc7ec1362e6/render-plantuml/render-plantuml.qml). If it fails to be perfect, I will explore the idea of detecting the image.

Thanks for your help!
