### ISSUE TITLE
Undo does not work after switching notes

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#2479]
#### Expected behaviour
Undo functionality is still available after switching notes.

#### Actual behaviour
Undo functionality seems lost after switching notes.

#### Steps to reproduce
Type in one note, switch notes, switch back again, try to undo. 

Not sure if this has always been the case or this is a regression.

Version `qownnotes 22.2.7-1`.

**Comment by pbek** [comment]
What where you expecting to undo after the switch?

**Comment by sanderboom** [comment]
To undo the last edits in that buffer. Like e.g. in Kate and others. But I guess there are no separate buffers for QON?

**Comment by pbek** [comment]
No, there is just the buffer of the qplaintextedit.
