### ISSUE TITLE
When creating a new note under some folder, all notes are shown for a short time

### ISSUE THREAD

**Issue by LightTemplar** [pbek/QOwnNotes#248]
1) go to some folder in the folder tree
2) press "New Note" on the toolbar
3) watch all your notes in the notes list for a second or two.
4) watch also extra redrawing of the Folder Tree

expected: the only change is a new note in the Notes List

**Comment by pbek** [comment]
The notes get reloaded if a note gets created in a subfolder (as mentioned in #183). That's a directory watcher thing of Qt and even though I'm turning it off while creating the note the watcher doesn't listen to me... I have not found a way around it. I can only turn of the watching of the base note folder...

**Comment by pbek** [comment]
And it's also one of the dreaded side-effects promised in #183 when I said I wasn't compelled to do subfolders...

**Comment by pbek** [comment]
For version 16.07.7:

I had to create a series of workarounds to make that work.
On some occasions it only works after a first note was created after QOwnNotes was started.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by LightTemplar** [comment]
Works well.
