### ISSUE TITLE
[I] Mis-spelling mark remains after adding word to dictionary

### ISSUE THREAD

**Issue by hbarel** [pbek/QOwnNotes#2480]
#### Expected behaviour

After adding a misspelled word to the dictionary, one would expect the red underline to disappear (as the word is apparently not misspelled).

#### Actual behaviour

After adding a misspelled word to the dictionary, the red underline remains under the added word, until the note is reloaded.

#### Steps to reproduce

Add any word to the dictionary.

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Mar 1 12:59:26 2022`
**Version**: `22.2.10`
**Build date**: `Feb 27 2022`
**Build number**: `954`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 1909`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `yes`
**Qt Debug**: `0`
**Locale (system)**: `en_IL`
**Locale (interface)**: *empty*
**Primary screen resolution**: `2560x1440`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `47`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `en_US`
**Language codes**: `en_US`
**Language names**: `American English (United States)`
**Application dictionaries path**: `C:\QOwnNotes\Data\dicts`
</details>

**Comment by pbek** [comment]
@Waqar144?

**Comment by Waqar144** [comment]
True, but nothing critical. 

>  until the note is reloaded.

This isn't correct I think. The change is reflected as soon as you edit the line which contained the word. The reason it isn't reflected immediately is because we don't rehighlight the block immediately after adding the word, though we can. However any edits made to the line will trigger a rehighlighting of the block.

**Comment by hbarel** [comment]
Yet, since there is no way (at least no way I know of) to just spell-check the entire note and fix the errors one by one, the best approach is to hover with the pointer/cursor over all red-lines and either correct or add them one by one. This is less fun when you cannot see what errors you added already and what still need to be looked at...

But I certainly agree that this is not critical...

**Comment by Waqar144** [comment]
Your second comment is an entirely different issue, no?

**Comment by hbarel** [comment]
No, same one. Only the fact that adding words to the dictionary does not remove their red mark until reloading or further editing.

**Comment by pbek** [comment]
## 22.3.0
- text blocks are now re-highlighted when text is added to the dictionary
  (for [#2480](https://github.com/pbek/QOwnNotes/issues/2480), thank you, @Waqar144)

**Comment by hbarel** [comment]
Works well!

Thank you.

**Comment by pbek** [comment]
Great, thank you for testing!
