### ISSUE TITLE
[I] Note preview panel shows irrelevant note

### ISSUE THREAD

**Issue by Katarn** [pbek/QOwnNotes#2482]
#### Expected behaviour

The preview panel should show the current editable note.

#### Actual behaviour

The preview panel shows the note that was being edited before this panel opens.

#### Steps to reproduce

1. Close the preview panel if it is open. Remember which note was currently displayed in it.
2. Select another note from the list of notes.
3. Open the preview panel.
4. You can see that it does not display the current editable note.

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Ср мар 2 16:02:59 2022`
**Version**: `22.2.10`
**Build date**: `Feb 27 2022`
**Build number**: `954`
**Platform**: `windows`
**Operating System**: `Windows 8.1 Version 6.3 (Build 9600)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Qt Debug**: `0`
**Locale (system)**: `ru_RU`
**Locale (interface)**: `en`
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `254`
**Calendar items**: `0`
**Enabled scripts**: `2`
</details>

**Comment by pbek** [comment]
@Waqar144, do you know anything about that?

**Comment by Waqar144** [comment]
Reproducible. A refresh is needed as soon as the preview panel is made visible again.

**Comment by pbek** [comment]
So I guess, that's a regression then.

**Comment by Katarn** [comment]
I've had this problem for many, many versions. For me, it is minor and does not cause inconvenience. But I decided to write now - a bug is a bug.

**Comment by Waqar144** [comment]
Agreed. It might easy to fix though. When we set a note, we just need to check if the "preview" is visible and refresh immediately.

**Comment by pbek** [comment]
> Are you sure it worked before? Can't think of a change which would break this

Ah, turning the preview on/off by switching workspaces did work in 2021. But directly clicking on the panel menu item didn't...

**Comment by pbek** [comment]
So a workaround is: Use two workspaces and the "Switch to previous workspace" shortcut.

**Comment by pbek** [comment]
## 22.3.0
- an issue with redrawing the preview when the preview panel is turned on manually without
  switching workspaces was fixed (for [#2482](https://github.com/pbek/QOwnNotes/issues/2482), thank you, @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Katarn** [comment]
Yes, it works great now. Thanks!

**Comment by pbek** [comment]
Great, thank you for testing!
