### ISSUE TITLE
Question about onDetachedProcessCallback

### ISSUE THREAD

**Issue by Beurt** [pbek/QOwnNotes#2483]
As you may remember, I'm working on an asynchronous version of the [render-plantuml](https://github.com/qownnotes/scripts/tree/master/render-plantuml) script.

I still have little inconsistencies in [the current version](https://github.com/Beurt/scripts/commit/9e782b09704d48d4bef34b7d9af39cc7ec1362e6): sometimes the preview is not properly refreshed.

Searching for the cause, I noticed that:

1. Because the script is using `noteToMarkdownHtmlHook`, the `startDetachedProcess` is launched several times. Hence, it is launched for every key stroke.
2.  Only the last occurrence (for the last key stroke in a raw) of `startDetachedProcess` provides a callback through `onDetachedProcessCallback`. I used timestamped callback's names with logs and noticed that all the other callbacks seem "canceled" (i.e. do not happen).

Is it a normal behavior of the couple `startDetachedProcess`/`onDetachedProcessCallback` that a command launched with `startDetachedProcess` several times, provides only one last callback (in this case for the last key stroke)?

**Comment by pbek** [comment]
Since the processes are called in the background there is no way to say which one is finished first... I still vote for a simple timer that looks every X seconds if the preview needs a refresh...

**Comment by Beurt** [comment]
Thanks for renewing your suggestion! You are probably right.

However, I think that I can say which background process finished first: because I use callbacks name with a timestamp, and I log when `startDetachedProcess` and when/if the specific callback with the same timestamp is caught by `onDetachedProcessCallback`.

While modifying a note, the result is something like:

```
[14:48:16] [scripting] launching PUML: 1-1646228896008
[14:48:17] [scripting] launching PUML: 1-1646228897256
[14:48:19] [scripting] launching PUML: 1-1646228899091
[14:48:19] [scripting] launching PUML: 1-1646228899886
[14:48:22] [scripting] entering callback: 1-1646228899886
[14:48:23] [scripting] launching PUML: 1-1646228903682
[14:48:24] [status] 1 note enregistrée sur le disque
[14:48:25] [scripting] entering callback: 1-1646228903682
```
Meaning, many background processes have no callback at all. And I wonder if it is a normal behavior.
