### ISSUE TITLE
New feature: Case of the text

### ISSUE THREAD

**Issue by telecentru** [pbek/QOwnNotes#2486]
I would like to request a feature regarding the case of the text, with corresponding shortcuts. I attach an example. Thanks
![0piXYrZcfF](https://user-images.githubusercontent.com/88895623/156600294-04569ea5-c61f-494f-9377-cdb33c4b40ba.png)

**Comment by pbek** [comment]
You can already cycle through text-cases... (Search for "case" in https://www.qownnotes.org/getting-started/shortcuts.html.)

You could write a script in a custom action if you want something special. (Just ask if you needs some pointers where to start.)

**Comment by telecentru** [comment]
That should be more than enough. Thanks.

**Comment by pbek** [comment]
great 😉
