### ISSUE TITLE
[I] Unencrypted note spell check is enabled after settings are applied

### ISSUE THREAD

**Issue by Katarn** [pbek/QOwnNotes#2487]
#### Expected behaviour

Spell checking in an unencrypted note should not be activated.

#### Actual behaviour

Spell checking in an unencrypted note is activated.

#### Steps to reproduce

1. Select any unencrypted note. I mean that the note should be encrypted, but the password for editing the encrypted note has not yet been entered.
2. Activate spell check. Previously, the following functionality was improved: #2156.
3. Open the application settings dialog.
4. Click OK button.
5. Watch as the encrypted text of the note will be underlined in red.

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Пт мар 4 13:35:21 2022`
**Version**: `22.3.0`
**Build date**: `Mar  3 2022`
**Build number**: `955`
**Platform**: `windows`
**Operating System**: `Windows 8.1 Version 6.3 (Build 9600)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Qt Debug**: `0`
**Locale (system)**: `ru_RU`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `252`
**Calendar items**: `0`
**Enabled scripts**: `2`
</details>

**Comment by pbek** [comment]
## 22.3.1
- disabling of spellchecking if the current note is encrypted now also works after
  the settings dialog was opened (for [#2487](https://github.com/pbek/QOwnNotes/issues/2487))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Katarn** [comment]
Now works fine. Thanks!

**Comment by pbek** [comment]
Great!
