### ISSUE TITLE
Audio notes with speech recognition?

### ISSUE THREAD

**Issue by LightTemplar** [pbek/QOwnNotes#249]
A big challenge and a stage growth :)

Any plans to add a possibility to dictate a note? Using free Speech recognition engines, like [CMU Sphinx](http://cmusphinx.sourceforge.net/) , [Kaldi](http://kaldi-asr.org/) or something else from [wiki list](https://en.wikipedia.org/wiki/Speech_recognition_software_for_Linux).

I have to make some notes, concentrated to inside myself. When I type them, my attention goes out and breaks the concentration :(

I would like to split this work on two stages: being concentrated dictate it, then rework and structure what I have dictated. 
By the way, if someone knows other solution for Linux, I would very very appreciate the link.

**Comment by pbek** [comment]
Try <https://mycroft.ai/>, but I guess there never will be anything that will work on all operating systems and I don't think speech recognition should be the job of software like QOwnNotes, why do you think it should?

**Comment by LightTemplar** [comment]
CMU Sphinx written on java and Kaldi works on all Unix OS and Windows. 
QON is note taking software, so I thought, an audio notes, turned into text, also notes =)

Mycroft looks interesting, but I didn't find any info about installing or compiling it.

**Comment by LightTemplar** [comment]
Looks like Mycroft is still in early development phase and not usable at all :(

**Comment by pbek** [comment]
> QON is note taking software, so I thought, an audio note, turned into text, also note =)

you can always simply create text files outside of QOwnNotes ;)

> Mycroft

try <https://github.com/MycroftAI/mycroft-core>

**Comment by LightTemplar** [comment]
https://docs.mycroft.ai/features - it's more like a computer controlling software, not a speech recognizer. What I need should be OpenSTT, also a project by Mycroft. But it's still empty: https://github.com/MycroftAI/openstt
Have you used Mycroft Core?

**Comment by pbek** [comment]
I have used it not yet but it gets mentioned a lot on the *Linux Action Show* of <http://jupiterbroadcasting.com/>.

**Comment by pbek** [comment]
Maybe this is something for you. ;)
<http://www.heise.de/developer/meldung/Googles-Cloud-Natural-Language-API-und-Speech-API-haben-nun-offenen-Beta-Status-3273860.html>

**Comment by LightTemplar** [comment]
Thanks, but I don't trust Google :(
If I would, I would use Google Keep instead of QOwnNotes with OwnCloud.

**Comment by pbek** [comment]
Good choice ;)
