### ISSUE TITLE
[website] deploying the Arabic translation

### ISSUE THREAD

**Issue by noureddin** [pbek/QOwnNotes#2494]
The website's Arabic translation is almost complete now; remains only parts of the Scripting section. I think it could be deployed now.

The [building script in package.json](https://github.com/pbek/QOwnNotes/blob/20f39c7a8f6a8ce13db8539018fac17e39c33629/webpage/package.json#L13) should RTL-ize Arabic along with Persian (replace `/fa` with `/{ar,fa}`):

```diff
-    "build": "cp ../screenshots src/.vuepress/public -R; cp ../CHANGELOG.md src/changelog.md; vuepress build src; sed -E 's/^<html /&dir=\"rtl\" /' -i `find src/.vuepress/dist/fa -name '*.html'`"
+    "build": "cp ../screenshots src/.vuepress/public -R; cp ../CHANGELOG.md src/changelog.md; vuepress build src; sed -E 's/^<html /&dir=\"rtl\" /' -i `find src/.vuepress/dist/{ar,fa} -name '*.html'`"
```

**Comment by pbek** [comment]
Awesome, we'll need translations for string like these: https://github.com/pbek/QOwnNotes/blob/20f39c7a8f6a8ce13db8539018fac17e39c33629/webpage/src/.vuepress/config.js#L192-L249

similar to: https://github.com/pbek/QOwnNotes/blob/20f39c7a8f6a8ce13db8539018fac17e39c33629/webpage/src/.vuepress/config.js#L251-L309

**Comment by pbek** [comment]
The Arabic translation was integrated into the webpage on [QOwnNotes webpage in Arabic](www.qownnotes.org/ar).

**Comment by noureddin** [comment]
I couldn't reply earlier because GitHub had issues for a few hours.

> The Arabic translation was integrated into the webpage on [QOwnNotes webpage in Arabic](https://github.com/pbek/QOwnNotes/issues/www.qownnotes.org/ar).

Thank you! :heart_eyes: :partying_face: 

---

Is this OK?

```javascript
      '/ar/': {
        selectText: 'اللغات',
        label: 'العربية',
        editLinkText: 'ساعدنا في تحسين هذه الصفحة!',
        algolia: {
          // ...
        },
        nav: [
          {
            text: 'بدء الاستخدام',
            link: utils.getNavItemForLanguage(gettingStartedNavItem, 'ar'),
          },
          {
            text: 'التثبيت',
            link: utils.getNavItemForLanguage(installationNavItem, 'ar'),
          },
          {
            text: 'سجل التغييرات',
            link: changelogNavItem,
            collapsable: true,
          },
          {
            text: 'تواصل',
            ariaLabel: 'Contact Menu',
            items: contactNavItems
          },
          {
            text: 'تبرع',
            link: utils.getNavItemForLanguage(donateNavItem, 'ar'),
          }
        ],
        sidebar: [
          {
            title: 'بدء الاستخدام',
            children: utils.getNavItemsForLanguage(gettingStartedNavItems, 'ar')
          },
          {
            title: 'التثبيت',
            children: utils.getNavItemsForLanguage(installationNavItems, 'ar')
          },
          {
            title: 'المحرر',
            children: utils.getNavItemsForLanguage(editorNavItems, 'ar')
          },
          {
            title: 'البرمجة',
            children: utils.getNavItemsForLanguage(scriptingNavItems, 'ar')
          },
          {
            title: 'المساهمة',
            children: utils.getNavItemsForLanguage(contributingNavItems, 'ar')
          },
          {
            title: 'أسئلة شائعة',
            children: utils.getNavItemsForLanguage(faqNavItems, 'ar')
          }
        ]
      },
```

---

I also noticed that the Blog is not in any translated navbar; only in English. I think it should be added, even when it's in English only (Contact is also English only, yet it's included). I think, like missing translations, a content that doesn't exists in the translated language should still be shown, in the source language (English in this case), but not omitted all together.

If Blog is to be included in the navbar of other languages, its Arabic term is `المدونة`. Thank you. 😉

**Comment by pbek** [comment]
> +    "build": "cp ../screenshots src/.vuepress/public -R; cp ../CHANGELOG.md src/changelog.md; vuepress build src; sed -E 's/^<html /&dir=\"rtl\" /' -i `find src/.vuepress/dist/{ar,fa} -name '*.html'`"

Needs more time, something is missing still
https://github.com/pbek/QOwnNotes/runs/5590388615?check_suite_focus=true#step:7:58
I had to remove if from the find command again...

**Comment by noureddin** [comment]
```
find: ‘src/.vuepress/dist/{ar,fa}’: No such file or directory
```

I think if `src/.vuepress/dist/{ar,fa}` in the find command is replaced by `src/.vuepress/dist/ar src/.vuepress/dist/fa` it should work.
Apparently the shell running this command doesn't support brace expansion.

**Comment by pbek** [comment]
> Is this OK?

best make a pull request directly, so I can see what changed...
https://github.com/pbek/QOwnNotes/blob/develop/webpage/src/.vuepress/config.js#L667

**Comment by pbek** [comment]
>  Apparently the shell running this command doesn't support brace expansion.

No, the folder `src/.vuepress/dist/ar` doesn't exist, but I don't know why...

**Comment by noureddin** [comment]
About the blog not being included in the navbar of any other language, should I open a separate issue?

**Comment by pbek** [comment]
> About the blog not being included in the navbar of any other language, should I open a separate issue?

The blog posts are not translated (I don't want to burden the translators with them), if I add a link to the English blog then the user will leave the translated page and move to the English page....

**Comment by pbek** [comment]
https://www.qownnotes.org/ar/ is now built correctly.
You can now attempt to fix issues like with the menu item in https://www.qownnotes.org/ar/installation/ubuntu.html, if that's possible 😅

**Comment by noureddin** [comment]
> The blog posts are not translated (I don't want to burden the translators with them), if I add a link to the English blog then the user will leave the translated page and move to the English page....

If the only choices are "leaving the translated pages" vs "completely omitting parts of the website in the translated pages", I think the former is a better trade-off.

Maybe we should discuss this in the room, to get input from other translators?

**Comment by noureddin** [comment]
> You can now attempt to fix issues like with the menu item in https://www.qownnotes.org/ar/installation/ubuntu.html, if that's possible

I'm using a lot of no-breaking spaces. :sweat_smile: 
I'll try to fix it.

**Comment by pbek** [comment]
> Maybe we should discuss this in the room, to get input from other translators?

I'm not sure what the correct platform would be to discuss this...
https://crowdin.com/project/qownnotes/discussions?

But what are you trying to discuss? Whether it's worth to translate all the blog posts?

**Comment by noureddin** [comment]
>  You can now attempt to fix issues like with the menu item in https://www.qownnotes.org/ar/installation/ubuntu.html, if that's possible sweat_smile

Done. :+1: 

> But what are you trying to discuss? Whether it's worth to translate all the blog posts?

I'm arguing that every language should have the same content, even if some isn't translated, so the (English) blog should be linked in the navbar. If someone is using the website in a different language, they will not notice that some content is lacking, even if they understand English.

I'm aware of the trade-off between the three options:

1. translating all blog posts
2. linking to the English blog and leaving the translated website
3. omitting the blog all together from the translated websites

I see that option 2 is actually the least bad.

**Comment by pbek** [comment]
> linking to the English blog and leaving the translated website

I think if I want to browse the webpage in my language that would rather disturb me... but this shouldn't be discussed in this issue!

**Comment by noureddin** [comment]
> I think if I want to browse the webpage in my language that would rather disturb me... but this shouldn't be discussed in this issue!

In a new issue, or in Telegram/Matrix? (I'm not sure if Crowd is active.) :sweat_smile:

**Comment by pbek** [comment]
You can start with opening a new issue, but I guess hardly any translator will see it unless you start mentioning people, like @Fabijenna and others...

**Comment by noureddin** [comment]
> You can start with opening a new issue, but I guess hardly any translator will see it unless you start mentioning people...

That's why I suggested the Telegram/Matrix; there are translators and users there.

**Comment by noureddin** [comment]
> A question directly related the Arabic translation: can [the tagline in the home page](https://crowdin.com/translate/qownnotes/26/en-ar#20617) contain a newline? And in what format? (<br>, or something else?) Because its text direction is not correct.

Actually the entire home page is not right-to-left properly; every text that mixed Arabic and English is reversed, including the footer "Made with love".

The text direction of the documents is correct, but there are other issues, e.g., the ending of `::: tip` and the Telegram link in Arabic [Overview](https://www.qownnotes.org/ar/getting-started/overview.html).

**Comment by noureddin** [comment]
Closing as the the main topic for this issue (deploying the Arabic translation to the website) is done.

Remains two issue:

1. Including the blog in the navbar of all language. I suggest including its link as "Blog (in English)" or something similar. I'll start discussion this in the Telegram/Matrix room in the morning.

2. Other issues regarding the built website (my previous comment). I'll try to fix them and make a PR, otherwise I'll open another issue detailing the problems.

Thank you. 😊

**Comment by pbek** [comment]
> A question directly related the Arabic translation: can [the tagline in the home page](https://crowdin.com/translate/qownnotes/26/en-ar#20617) contain a newline? And in what format? (<br>, or something else?) Because its text direction is not correct.

Unfortunately, it can't

**Comment by pbek** [comment]
> That's why I suggested the Telegram/Matrix; there are translators and users there.

You can always try

**Comment by pbek** [comment]
> Actually the entire home page is not right-to-left properly; every text that mixed Arabic and English is reversed, including the footer "Made with love".

If you really want to play around with the things VuePress does it almost would make sense to checkout the QOwnNotes repository and build the website yourself. Then you could play around with all the options...

Here's how to build the webpage: https://github.com/pbek/QOwnNotes/tree/develop/webpage

**Comment by noureddin** [comment]
Thank you. I just started that discussion. I hope others will chime in.

The text-direction issue was fixed shortly after my previous comment. I think it was a caching problem on the server or on my end or something. I don't really know, but it's fixed!

Remaining only the migration of the fixed strings from Crowdin to the website. :blush:
