### ISSUE TITLE
Alt Gr "converted" to Ctrl+Alt

### ISSUE THREAD

**Issue by dardoor** [pbek/QOwnNotes#2499]
When pressing AltGr+key, QOwnNotes interprets it as Ctrl+Alt+key.
So it's impossible to type a character with AltGr+key, if Ctrl+Alt+key is used for a shortcut.

Notepad++, for example, handles this correctly and treats these key combos as different inputs.

Windows 10, QOwnNotes 22.3.3

**Comment by pbek** [comment]
Could be https://bugreports.qt.io/browse/QTBUG-69317 or https://bugreports.qt.io/browse/QTBUG-83032?focusedCommentId=504202.

**Comment by dardoor** [comment]
Yeah, probably. So maybe adding `-platform windows:altgr` would fix it as they suggest.
But I'm not a programmer, so IDK.
