### ISSUE TITLE
File types

### ISSUE THREAD

**Issue by blvb** [pbek/QOwnNotes#25]
Please allow files extension htm to be compatible with Android app https://play.google.com/store/apps/details?id=com.nowsci.ownnote
and Notes on server.

**Comment by pbek** [comment]
I'm sorry, the default notes application of ownCloud is only working with plain text files.
I guess QOwnNotes will never edit html files directly since html is not very suitable to create platform agnostic content with.

**Comment by pbek** [comment]
I'll close this issue now until someone opens it again.

**Comment by LEDfan** [comment]
I'd really like to have the qownnotes support .md files. IMO it's a bid weird to have markdown files with the .txt extension. (However I understand the historical meaning of this). The notes app of ownCloud is supporting other extensions as well since October. https://github.com/owncloud/notes/pull/161

I think this is important since there are other apps which only support markdown extensions for example. (note that on Mac and windows extensions are more important than on Linux...)

**Comment by pbek** [comment]
Trust me, I'd love to use the `.md` extension!
And I will change that as soon all other parties support it.
Thanks a lot for notifying me!
Do you know if <https://itunes.apple.com/de/app/cloudnotes-owncloud-notes/id813973264?mt=8> and  <https://f-droid.org/app/org.aykit.MyOwnNotes> support it as well? (Or do you know any alternatives for OS X and Android?)

**Comment by LEDfan** [comment]
I'm quite sure the android app doesn't support it. I have no idea about the iOS app. The notes app of ownCloud creates new notes using the txt extension. Maybe it's an idea to do the same? I'll ask the android app for the same thing.

**Comment by pbek** [comment]
I would like to see `.md` as default extension, but I need full support of the other apps for that... :wink:

**Comment by pbek** [comment]
CloudNotes doesn't support markdown files. :disappointed:

**Comment by pbek** [comment]
I'm wrong! If the `.md` file has a correct name it works! Yay!
`.md` in QOwnNotes, here we come! Will not be easy tho... :smiley:

**Comment by pbek** [comment]
@LEDfan, do you know if the Android App can also do it?

**Comment by pbek** [comment]
I worked a lot on it yesterday and even had to change the API app for it. But there a still some nasty side effects... More work...

**Comment by pbek** [comment]
Finally done in the current v0.92. Could you be so kind and report back if it works like intended?

**Comment by LEDfan** [comment]
Hi, thanks again for working on this app! It's working as I expected, I only discovered a bug which I'll report in a new issue.

**Comment by pbek** [comment]
I also already found a problem with removing multiple notes...

**Comment by pbek** [comment]
@LEDfan, I will close this issue now since it is done, please don't forget to report on issue #60.

**Comment by LEDfan** [comment]
@pbek everything works perfect now, thanks!

**Comment by pbek** [comment]
Great!

**Comment by LEDfan** [comment]
@pbek I can open the files with the myownnotes on ownCloud.

**Comment by pbek** [comment]
Great news, I assume you are talking of `.md` files. On Android you mean? Or does myownnotes has a web app too?
