### ISSUE TITLE
Linux: Scrolling is unsynced when mouse cursor above edit/render pane that has no focus

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#250]
Tested on current Manjaro Linux with Plasma 5 and QT 5.6.1.

1. Turn on edit pane and render pane;
2. Click on edit pane - it's now in focus;
3. Scroll by mouse wheel with cursor above edit pane - it's synced with render pane;
4. Put cursor above render pane (no click) and scroll by mouse wheel - render pane scrolls, edit pane don't
5. Put the cursor back above edit pane - it's synced again;
6. Same vice versa. 

I've started to notice this behavior not so long time ago, maybe it's introduced by some fresh Qt update.

**Comment by pbek** [comment]
Thank you for reporting, but I'm sorry, I had to do that on purpose or otherwise the two areas would scroll each other at the same time and block all scrolls. :)

**Comment by Maboroshy** [comment]
I had my doubts about it. Good to know it's not a bug, proves very high quality of the app.

**Comment by pbek** [comment]
Side-effects can always happen... ;)
