### ISSUE TITLE
[F] Automatic selection of current note's subfolder

### ISSUE THREAD

**Issue by hbarel** [pbek/QOwnNotes#2500]
#### Expected behaviour

It could be very useful if the sub-folder of the currently-displayed note would be selected automatically when the note is displayed. (Perhaps as a configuration option?)

#### Actual behaviour

Today, when you click on a note (say, after searching for it), the only way to determine where the note is (which sub-folder), and perhaps navigate in that sub-folder, is by going to the notes-list panel, right clicking on that note, and selecting "jump to sub-folder" (not even a keyboard shortcut). It could make life very efficient if the proper sub-folder would always be selected when a note is opened.

#### Steps to reproduce

Visit a note after performing a global search, note the number of steps required to determine its sub-folder and navigate in that sub-folder.

**Comment by pbek** [comment]
There also is a tooltip on the note that shows you the sub-folder.

> It could be very useful if the sub-folder of the currently-displayed note would be selected automatically when the note is displayed. 

I think that would annoy all people who show the notes from their sub-folders recursively, don't you think? 😅

**Comment by pbek** [comment]
But you can always write a script to jump to the sub-folder (https://www.qownnotes.org/scripting/methods-and-objects.html#jumping-to-a-note-subfolder) of the current note with a custom action.

**Comment by pbek** [comment]
...or if you double-click the note: https://www.qownnotes.org/scripting/hooks.html#notedoubleclickedhook

**Comment by hbarel** [comment]
> I think that would annoy all people who show the notes from their sub-folders recursively, don't you think? 😅

Only one note is displayed at a time, so I'm not sure what the annoyance of selecting the current sub-folder stems from. It's like file managers that keep highlighting the folder of the selected file, but I don't know the application too well, so I might be missing something crucial...

> There also is a tooltip on the note that shows you the sub-folder.

> But you can always write a script to jump to the sub-folder (https://www.qownnotes.org/scripting/methods-and-objects.html#jumping-to-a-note-subfolder) of the current note with a custom action.

Once you move your hand to the mouse you can see the tool-tip, or right-click the right note and select "jump to sub-folder". My thought was on having an _immediate_ indication as you navigate between search results with the keyboard. It's odd to see a flat list of notes without immediately seeing where each one you view came from. But really, it's a matter of taste, and I fully appreciate you not relating to this use-case. :-)

**Comment by pbek** [comment]
> so I'm not sure what the annoyance of selecting the current sub-folder stems from.

If you select a sub-folder then the the filter changes to that sub-folder and that is undesirable.

you could also use https://www.qownnotes.org/scripting/hooks.html#noteopenedhook and showing the information in a scripting label https://www.qownnotes.org/scripting/methods-and-objects.html#registering-a-label

**Comment by hbarel** [comment]
>If you select a sub-folder then the the filter changes to that sub-folder and that is undesirable.

True... I haven't thought of that... :-(

> You could also use https://www.qownnotes.org/scripting/hooks.html#noteopenedhook and showing the information in a scripting label https://www.qownnotes.org/scripting/methods-and-objects.html#registering-a-label

Thanks! Definitely worth a try...

**Comment by hbarel** [comment]
Not sure if this is intentional or not, but the `noteOpenedHook` does not trigger when a note is opened not by clicking (e.g., when moving back and forth between notes with the keyboard).

Also, `activeNoteSubFolder` does not seem to reflect the sub-sub-folder of the active note, if sub-folder is currently selected. For example, if you list the notes at _/a/b_, and in that list you click a note that it at _/a/b/c_, then `activeNoteSubFolder` will appear as _/a/b_. Not sure if this is intentional or not.

**Comment by pbek** [comment]
Can you please share your script.

**Comment by pbek** [comment]
>         var subFolder = noteSubFolderQmlObj.activeNoteSubFolder();

just do this instead: `        var subFolder = noteSubFolderQmlObj.fetchNoteSubFolderById(note.noteSubFolderId);`

**Comment by hbarel** [comment]
> just do this instead: var subFolder = noteSubFolderQmlObj.fetchNoteSubFolderById(note.noteSubFolderId);

This solved all issues... Thanks! You're right, I did not note the difference between current sub-folder and sub-folder of current note...

**Comment by pbek** [comment]
Great 😁

**Comment by pbek** [comment]
Maybe you also want to contribute your script to the script repository? https://github.com/qownnotes/scripts#contributing
