### ISSUE TITLE
[I] can not copy the text in Vim mode

### ISSUE THREAD

**Issue by Shahin-rmz** [pbek/QOwnNotes#2509]
Please paste the text from the issue assistant here. It should be already in your clipboard.Hello, Thanks for this masterpiece.
I have following issue:

#### Expected behaviour

copy to clipboard either via y or Ctrl+c or Ctrl+Shift+C

#### Actual behaviour

Nothing copies to clipboard

#### Steps to reproduce

just selecting the text via Visual mode `V` and select some text and press y on keyboard. With mouse it works fine.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed Apr 6 22:51:46 2022`
**Version**: `22.4.0`
**Build date**: `Apr  4 2022`
**Build number**: `960`
**Platform**: `linux`
**Operating System**: `Ubuntu 20.04.4 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.12.8`
**Qt Version (runtime)**: `5.12.8`
**Portable mode**: `no`
**Settings path / key**: `/home/shahin/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/shahin/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `Humanity-Dark`
**Notes in current note folder**: `4`
**Calendar items**: `36`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://nextcloud.accerun.com`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `22.2.0.2`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `de-medical, de_BE, de_DE, de_DE_frami, de_LU, en-medical, en_US`
**Language names**: `Deutsch (medical), Deutsch (Belgien), Deutsch (Deutschland), Deutsch (Deutschland), Deutsch (Luxemburg), American English (medical), American English (United States)`
**Application dictionaries path**: `/home/shahin/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `5`

### Note folder `Notes_folder`

**id**: `5`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/shahin/Nextcloud2/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: `Polix`
**database file**: `/home/shahin/Nextcloud2/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://nextcloud.accerun.com`
**username**: `Shahin`
**accountId**: `Shahin`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `29`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-9c24397c-3122-4a0d-bc05-1989bdc7fa01`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (bool): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `true`
**Editor/vimMode** (QString): `true`
**FileDialog/LastPath** (QString): `/home/shahin/Desktop`
**FileDialog/LastPath-Joplin Import** (QString): `/home/shahin/Desktop/folder/09.01.2022`
**FileDialog/LastPath-NoteHTMLExport** (QString): `/home/shahin/Desktop`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**JoplinImport/AttachmentImportCheckBoxChecked** (QString): `true`
**JoplinImport/FolderImportCheckBoxChecked** (QString): `false`
**JoplinImport/ImageImportCheckBoxChecked** (QString): `true`
**JoplinImport/MetadataImportCheckBoxChecked** (QString): `true`
**JoplinImport/TagImportCheckBoxChecked** (QString): `true`
**JoplinImportDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2022-04-06T22:21:35.092`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `DejaVu Sans,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `DejaVu Sans,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteDialog/tabWidgetIndex** (QString): `0`
**NoteFolder-5/NoteTabNameList** (QString): `Reverse Proxying selfhosted`
**NoteFolder-5/NoteTabStickinessList**: *empty*
**NoteFolder-5/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteHistory-5** (QVariantList): `<variant list with 3 item(s)>`
**NoteHistoryCurrentIndex-5** (QString): `2`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `true`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `0`
**TodoDialog/showDueTodayItemsOnly** (QString): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Personal`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `5`
**currentWorkspace** (QString): `tg7gyVz7GBr6`
**cursorWidth** (QString): `1`
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `true`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `23`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `true`
**noteSubfoldersPanelShowNotesRecursively** (QString): `true`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/shahin/Nextcloud2/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Neuro, AcceRun, Programming, Vanije, MediDent(Shahin), Anil, Uni_todo, Personal`
**ownCloud/todoCalendarEnabledList** (QStringList): `Neuro, AcceRun, Programming, Vanije, MediDent(Shahin), Anil, Uni_todo, Personal`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://nextcloud.accerun.com/remote.php/dav/calendars/Shahin/neuro-1/, https://nextcloud.accerun.com/remote.php/dav/calendars/Shahin/accerun-1/, https://nextcloud.accerun.com/remote.php/dav/calendars/Shahin/programming/, https://nextcloud.accerun.com/remote.php/dav/calendars/Shahin/vanije-1/, https://nextcloud.accerun.com/remote.php/dav/calendars/Shahin/medidentshahin/, https://nextcloud.accerun.com/remote.php/dav/calendars/Shahin/anil/, https://nextcloud.accerun.com/remote.php/dav/calendars/Shahin/uni_todo/, https://nextcloud.accerun.com/remote.php/dav/calendars/Shahin/personal/`
**ownCloud/todoCalendarUrlList** (QStringList): `https://nextcloud.accerun.com/remote.php/dav/calendars/Shahin/neuro-1/, https://nextcloud.accerun.com/remote.php/dav/calendars/Shahin/accerun-1/, https://nextcloud.accerun.com/remote.php/dav/calendars/Shahin/programming/, https://nextcloud.accerun.com/remote.php/dav/calendars/Shahin/vanije-1/, https://nextcloud.accerun.com/remote.php/dav/calendars/Shahin/medidentshahin/, https://nextcloud.accerun.com/remote.php/dav/calendars/Shahin/anil/, https://nextcloud.accerun.com/remote.php/dav/calendars/Shahin/uni_todo/, https://nextcloud.accerun.com/remote.php/dav/calendars/Shahin/personal/`
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `22.2.0.2`
**previousWorkspace** (QString): `10a90809-5e24-42a6-bca9-48aa25d27472`
**recentNoteFolders**: *empty*
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-5** (QStringList): `Note 2022-04-06T13.46.38, Note 2022-04-05T13.21.21, Note 2022-04-05T13.21.17, Note 2022-04-05T13.21.10, Note 2022-04-05T13.21.03, Note 2022-04-05T13.20.56, Note 2022-04-05T13.20.47, Note 2022-04-05T13.17.29, Reverse Proxying selfhosted, Nginx Proxy Manager Docker-Compose Docu, Alle Firefox-Produkte schützen zuallererst deine Privatsphäre online — Mozilla 2022-04-05T11.27.58, Alle Firefox-Produkte schützen zuallererst deine Privatsphäre online — Mozilla`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `true`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (QString): `22222`
**webSocketServerService/token** (QString): `<hidden>`
**workspace-10a90809-5e24-42a6-bca9-48aa25d27472/name** (QString): `test`
**workspace-10a90809-5e24-42a6-bca9-48aa25d27472/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-10a90809-5e24-42a6-bca9-48aa25d27472/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspace-tg7gyVz7GBr6/name** (QString): `Full`
**workspace-tg7gyVz7GBr6/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-tg7gyVz7GBr6/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 10a90809-5e24-42a6-bca9-48aa25d27472, tg7gyVz7GBr6`

## System environment

**COMPOSE_FILE**: `/opt/redash/docker-compose.yml`
**USER**: `shahin`
**LC_TIME**: `de_DE.UTF-8`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `2781`
**SHLVL**: `0`
**XDG_CACHE_HOME**: `/home/shahin/.cache`
**QT4_IM_MODULE**: `ibus`
**HOME**: `/home/shahin`
**COMPOSE_PROJECT_NAME**: `redash`
**DESKTOP_SESSION**: `Lubuntu`
**GTK_MODULES**: `gail:atk-bridge`
**LXQT_DEFAULT_OPENBOX_CONFIG**: `/etc/xdg/xdg-Lubuntu/openbox/lxqt-rc.xml`
**LC_MONETARY**: `de_DE.UTF-8`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**MANDATORY_PATH**: `/usr/share/gconf/Lubuntu.mandatory.path`
**QT_QPA_PLATFORMTHEME**: `lxqt`
**GTK_IM_MODULE**: `ibus`
**LOGNAME**: `shahin`
**XDG_SESSION_CLASS**: `user`
**DEFAULTS_PATH**: `/usr/share/gconf/Lubuntu.default.path`
**USERNAME**: `shahin`
**XDG_SESSION_ID**: `2`
**SAL_USE_VCLPLUGIN**: `qt5`
**WINDOWPATH**: `2`
**PATH**: `/home/shahin/.local/bin:/home/shahin/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
**LC_ADDRESS**: `de_DE.UTF-8`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_MENU_PREFIX**: `lxqt-`
**DISPLAY**: `:0`
**LANG**: `en_US.UTF-8`
**LC_TELEPHONE**: `de_DE.UTF-8`
**XDG_CURRENT_DESKTOP**: `LXQt`
**XMODIFIERS**: `@im=ibus`
**XDG_SESSION_DESKTOP**: `Lubuntu`
**XAUTHORITY**: `/run/user/1000/gdm/Xauthority`
**XDG_DATA_HOME**: `/home/shahin/.local/share`
**XDG_CONFIG_HOME**: `/home/shahin/.config`
**SSH_AUTH_SOCK**: `/tmp/ssh-uWB0iXhObTIZ/agent.2706`
**SHELL**: `/bin/bash`
**LC_NAME**: `de_DE.UTF-8`
**QT_ACCESSIBILITY**: `1`
**GDMSESSION**: `Lubuntu`
**LC_MEASUREMENT**: `de_DE.UTF-8`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**LC_IDENTIFICATION**: `de_DE.UTF-8`
**QT_IM_MODULE**: `ibus`
**XDG_VTNR**: `2`
**PWD**: `/home/shahin`
**LC_ALL**: `en_US.utf8`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-Lubuntu:/etc/xdg:/etc:/usr/share`
**CLUTTER_IM_MODULE**: `ibus`
**XDG_DATA_DIRS**: `/usr/share/Lubuntu:/home/shahin/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop:/usr/share`
**LC_NUMERIC**: `de_DE.UTF-8`
**LC_PAPER**: `de_DE.UTF-8`
**QT_PLATFORM_PLUGIN**: `lxqt`
**LXQT_SESSION_CONFIG**: `session`
**BROWSER**: `Brave Web Browser`
**GTK_CSD**: `0`
**GTK_OVERLAY_SCROLLING**: `0`
**TERM**: `xterm`
</details>

**Comment by pbek** [comment]
@Waqar144, do you have any insight into copy/pasting in VIM mode?

**Comment by pbek** [comment]
I'm able to copy a line with `y` and paste it with `p`, doesn't that work for you, @Shahin-rmz?

**Comment by Shahin-rmz** [comment]
Thanks for the reply @pbek .
I am able to copy and paste inside QOwnNotes.
However, it is not possible to copy to clipboard and paste the text in other apps.
It is also not possible in vim, but I was able to config my Tmux to do that. 
It would be awesome if we can have copied text inside clipboard.

**Comment by pbek** [comment]
That would have need to be done upstream in the fakevim library: https://github.com/pbek/QOwnNotes/tree/develop/src/libraries/fakevim

**Comment by Waqar144** [comment]
It is definitely possible to copy. Just you can't use `Ctrl+C`, there is some issues with that which makes it fail in QON. Instead, select a word and then `"+y` and for pasting using the same but `p` instead of `y`.

**Comment by Shahin-rmz** [comment]
>  select a word and then `"+y` and for pasting using the same but `p` instead of `y`.


with the help of your tip, I could manage to do copy/paste and delete which pretty much covers what I wanted from Vim in QON.
Thanks

**Comment by davuses** [comment]
> It is definitely possible to copy. Just you can't use `Ctrl+C`, there is some issues with that which makes it fail in QON. Instead, select a word and then `"+y` and for pasting using the same but `p` instead of `y`.

@Waqar144 Hi, I also have some trouble copying and pasting in Vim mode. How could I paste text from clipboard into QOwnNotes? `Ctrl+V` enters into visual block, `Ctrl+Shift+V` does nothing as well.

I actually do copying and pasting quite often, typing `"+y` every time is a lot of work, I wonder if there is a way to only apply Vim's cursor moving keymap, or is there any cursor moving methods QOwnNotes provides for scripting?

**Comment by Shahin-rmz** [comment]
@davuses just press `"` and then `+` and then `p`

**Comment by davuses** [comment]
> @davuses just press `"` and then `+` and then `p` . It is not very "vim" like, but can do the job. for note taking app it enough. (personal opinion)

@Shahin-rmz Thank you, it works. But I think I'll turn off Vim mode just for now, it can be a hassle that every copying and pasting requires all these keypress. It would be wonderful if some shortcuts can be added in the future.
