### ISSUE TITLE
Links in scripting settings disabled

### ISSUE THREAD

**Issue by Adurol** [pbek/QOwnNotes#251]
__Tested:__ QOwnNotes v16.07.7 (Qt 5.7.0)
__Reproducible:__ always

__Description:__
Under `Settings` -> `Scripting` are two links, one to GitHub Issues and one to the QML examples. Booth are not usable ("on click") if no scripts are added. It's  "greyed out" as block, not only the `Name` and `Script path` option. After click on button `Add script` the links become usable (open with Browser).

__Expected behavior:__
Links should be usable, even if no scripts are present. (To click on the link to get some.)

**Comment by pbek** [comment]
Thank you for reporting. The whole pane is disabled, so they are not clickable. Maybe that should be done an other way.

**Comment by pbek** [comment]
## 16.07.8
- the informational text-block with the links to the examples is now always 
  accessible in the scripting settings tab

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Adurol** [comment]
Can open the links even if no scripts are added. Thank you.

**Comment by pbek** [comment]
Great, thank you for reporting!
