### ISSUE TITLE
Advanced (boolean) tag filtering?

### ISSUE THREAD

**Issue by p-bo** [pbek/QOwnNotes#2511]
Hello,
in its current state, app allows to select multiple tags, which results in displaying all notes, which contains at least one of tags selected
(in other words, logical OR). That is useful, but many times one needs to narrow searching a bit...

Would it be possible to consider implementing also OR and NOT operators please?

So to allow filtering by selecting tags in that way, which allow to (optionally?) express user intention regarding which of them are mandatory (AND) or not wanted (NOT as named in SQL terminology) for notes searched. OR operator (sufficient) could be default state of tag selected.

Thanks for considering this

**Comment by p-bo** [comment]
I see - only hoped to be able to get better signal/noise ratio from searching via tags results eventually...

**Comment by p-bo** [comment]
Maybe for better understanding of idea, depicted on (very awkward) mockup:

![mockup-tag_bolean_search-2](https://user-images.githubusercontent.com/12208593/162373854-8ac8be8e-57ec-4bc6-8be7-aff516b80aba.png)

Tag 1 is OR
Tag 3 is not used at all
Tag 4 is NOT
Tag 2 is AND

Would this break way the searching works to badly?

**Comment by pbek** [comment]
I don't think a lot of people would understand that UI paradigm. 😅
