### ISSUE TITLE
[F] Bookmarks

### ISSUE THREAD

**Issue by hbarel** [pbek/QOwnNotes#2515]
#### Expected behaviour

It could be super useful if the application has a bookmark feature, even if those bookmarks are not stored anywhere on disk but are entirely ephemeral.

When working with multiple notes, and even with one note, you often go back and forth, with a constant need to look up something and then return to where you were. Some editors allow you to press a key-stroke (e.g., Ctrl-F2 in UltraEdit), to set a bookmark, and then jump back to it after you navigated away using another keystroke (e.g., F2 in UltraEdit).

This application allows moving back and forth between notes in History, but this does not work within the note itself, and the History easily gets cluttered when you look up something. So it could be very useful to just be able to set an anchor and return to that anchor.

**Comment by pbek** [comment]
The shortcuts pages shows the shortcuts for the note bookmarks, if we are talking of the same kind of bookmarks.
