### ISSUE TITLE
GPG key for Arch repository is expired

### ISSUE THREAD

**Issue by Noctivivans** [pbek/QOwnNotes#2517]
Hi,
I've tried to add Arch repo to my system, but it seems that GPG key is expired:
```
[lapek ~]# gpg home_pbek_QOwnNotes_Arch_Extra.key
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa2048 2019-07-31 [SC] [expired: 2021-10-10]
      F2205FB121DF142B31450865A3BA514562A835DB
uid           home:pbek OBS Project <home:pbek@build.opensuse.org>
[lapek ~]# 
```
As a result, installation of package fails even if key is installed properly.

**Comment by pbek** [comment]
Those keys are managed by the openSUSE project, usually you just need to update the keys.

**Comment by Noctivivans** [comment]
Even with updated keys (I redownloaded key and imported to pacman database) I am still not able to install package:
```
error: qownnotes: signature from "home:pbek OBS Project <home:pbek@build.opensuse.org>" is invalid
:: File /var/cache/pacman/pkg/qownnotes-22.3.4-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
```

**Comment by pbek** [comment]
Strange, now and then issues with the key are mentioned, but often resolved with some keycache update or similar: https://github.com/pbek/QOwnNotes/issues?q=arch+in%3Atitle

**Comment by dohliam** [comment]
I ran into this same issue yesterday as well and can confirm that it is not currently possible to install QOwnNotes on the latest Manjaro following the install instructions for Arch. Both the package from OBS and the one from AUR are affected.

Coincidentally, there was a PGP signature issue with Arch packages yesterday at the same time that broke installing most things with pacman. [This thread](https://forum.manjaro.org/t/manjaro-printer-invalid-corrupted-package-pgp-signature/108948/3) and others suggested using  `sudo pacman-key --refresh-keys` and this did in fact resolve the issue for other packages, but trying to install QOwnNotes still gives the error mentioned above by @Noctivivans, so this might be unrelated.

**Comment by pbek** [comment]
There is #opensuse-buildservice on the libera.chat IRC to ask such things...
Or just go with the AppImage until openSUSE has resolved this (if they are aware of it).

**Comment by alk0** [comment]
Just my 2 groschen: same error as @Noctivivans, but for 22.**4.2**-1, with the new (?) signing key (F2205FB1…, expires: **2023**-12-05, locally signed) and after `sudo pacman-key --refresh-keys` (just in case). Latest Manjaro, fresh manjaro-keyring, too. And in fact I had it already updated to this version a few days ago, and I didn't import/sign any new keys then… I believe… not sure. But OK, let's see how the next update goes.

**Comment by pbek** [comment]
Maybe it would be the best if you report that issue in `#opensuse-buildservice` on librera.chat directly.

**Comment by alk0** [comment]
> Maybe it would be the best if you report that issue in `#opensuse-buildservice` on librera.chat directly.

Ugh… I'm afraid I'm way too shy for it - there are 200 people there, STARING at me in silence! Just some clues, in case anyone else is willing to do the quest - verifying the qownnotes-22.4.2-1-x86_64.pkg.tar.zst gives the "BAD signature", while verifying other files from the same build run results in a "Good signature" (maybe not trusted, but good). Keys used to sign are the same (F2205FB121DF142B31450865**A3BA514562A835DB**). qownnotes-22.4.2-1-x86_64.pkg.tar.zst itself seems to be in perfect order, it is quite possible to unpack it, install it manually, etc. Is there something messing with the signatures in their build chain?..

And now what's weirds - the signature downloaded yesterday is "good".

```
$ gpg --show-keys home_pbek_QOwnNotes_Arch_Extra.key
pub   rsa2048 2019-07-31 [SC] [expires: 2023-12-05]
      F2205FB121DF142B31450865A3BA514562A835DB
uid                      home:pbek OBS Project <home:pbek@build.opensuse.org>
```
Today, bad signature:

```
$ gpg --verify qownnotes-22.4.2-1-x86_64.pkg.tar.zst.sig
gpg: assuming signed data in 'qownnotes-22.4.2-1-x86_64.pkg.tar.zst'
gpg: Signature made Пн 02 мая 2022 15:17:45 +05
gpg:                using RSA key A3BA514562A835DB
gpg: BAD signature from "home:pbek OBS Project <home:pbek@build.opensuse.org>" [unknown]
```
Yesterday, good signature:
```
gpg --verify qownnotes-22.4.2-1-x86_64.pkg.tar.zst.sig.1 qownnotes-22.4.2-1-x86_64.pkg.tar.zst
gpg: Signature made Вс 01 мая 2022 20:43:44 +05
gpg:                using RSA key A3BA514562A835DB
gpg: Good signature from "home:pbek OBS Project <home:pbek@build.opensuse.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: F220 5FB1 21DF 142B 3145  0865 A3BA 5145 62A8 35DB
```
Today again, other files, good signatures:
```
$ gpg --verify home_pbek_QOwnNotes_Arch_Extra.db.tar.gz.sig
gpg: assuming signed data in 'home_pbek_QOwnNotes_Arch_Extra.db.tar.gz'
gpg: Signature made Пн 02 мая 2022 15:17:58 +05
gpg:                using RSA key A3BA514562A835DB
gpg: Good signature from "home:pbek OBS Project <home:pbek@build.opensuse.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: F220 5FB1 21DF 142B 3145  0865 A3BA 5145 62A8 35DB

$ gpg --verify home_pbek_QOwnNotes_Arch_Extra.files.sig 
gpg: assuming signed data in 'home_pbek_QOwnNotes_Arch_Extra.files'
gpg: Signature made Пн 02 мая 2022 15:17:58 +05
gpg:                using RSA key A3BA514562A835DB
gpg: Good signature from "home:pbek OBS Project <home:pbek@build.opensuse.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: F220 5FB1 21DF 142B 3145  0865 A3BA 5145 62A8 35DB
```

**Comment by pbek** [comment]
I've no idea. I'm trying a new build...

**Comment by alk0** [comment]
This time (qownnotes-22.5.0-1) everything went more or less OK after `sudo pacman -Syy` (force synchronizing the local package database, including updating external repos). The standard GUI `pamac` package manager needed one or two re-runs to pick up the changes, now everything is smooth. :+1:

**Comment by dohliam** [comment]
@alk0 Thanks for the update! Just tried again and can confirm that following the installation steps on the website after refreshing the Manjaro package database worked for me as well. Tested with a live image just to make sure. :smile:

**Comment by pbek** [comment]
Great, thank you for testing!
I will close this issue then.
