### ISSUE TITLE
Jump back to the Root folder after deleting a note

### ISSUE THREAD

**Issue by Shahin-rmz** [pbek/QOwnNotes#2519]
#### Expected behaviour
continue in the same directory

#### Actual behaviour
jumps to the root directory

#### Steps to reproduce
in subdirectory under the root delete a note
#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>
Hello,
I am really enjoying QOwnNotes.
Thanks alot.
I use QON for daily to make ZettelKasten notes and then end of the nights add them to my Wiki.
For different projects, there are different directories and sub directories in nextcloud sync folder.
If I want to delete a note under a sub directory, all the opened directorories will be closed and the cursor will jump back to the root folder.
It would be awesome if it could stays there.
Thanks

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
I cannot reproduce this.

- I change to a sub-folder
- I delete a note
- The note is gone, I'm still in that sub-folder
