### ISSUE TITLE
Settings option: tabs vs spaces

### ISSUE THREAD

**Issue by Adurol** [pbek/QOwnNotes#252]
Please offer an option to use spaces instead of tabs.

Some people prefer spaces, other tabs. QOwnNotes uses tabs by default. It would be nice if I could select (like other editors offer it too) to use tabs or spaces. And if spaces are used, how many whitespaces are inserted instead of a tab.

**Comment by pbek** [comment]
Makes sense, but will have a lot of side-effects with editor functions like auto-indent and auto-un-indent when using tabs, indenting blocks or creating lists...

**Comment by pbek** [comment]
And it would be messy if different QOwnNotes instances are configured differently...

**Comment by Adurol** [comment]
Yes. I would also think that the behavior on ownCloud would get more complicated.
