### ISSUE TITLE
[F] I would like a panel for outlines.

### ISSUE THREAD

**Issue by sinh927** [pbek/QOwnNotes#2522]
#### Expected behaviour

I sometimes want to check the hierarchy of h1,h2,h3,h4,h5 tags when I create a text.
In the preview panel, there is so much information that it is difficult to check.
Therefore, I think it would be useful to have an outline panel that displays only #,##,###,####,####,+*- items in a tree.

**Comment by pbek** [comment]
Are you talking about the *Navigation panel* (See *Window/Panels*)?
