### ISSUE TITLE
Sort by modified date fails when modified date is in the future

### ISSUE THREAD

**Issue by louwers** [pbek/QOwnNotes#2524]
Not sure if this is intended!

---

1. Set sort order to modified date.

2. Run the following command on a note.

```
touch -d "+2 days" some_note.txt 
```

3. Edit another note (say `other_note.txt`).

#### Expected behaviour

`some_note.txt` is above `other_note.txt` since it's modified date is larger.

#### Actual behaviour

`other_note.txt` jumps to the top.

#### Steps to reproduce

See above.

#### Output from the debug section in the settings dialog

NA

#### Relevant log output in the Log panel

NA

**Comment by pbek** [comment]
Yes, that was intended, the currently edited just is moved to the top when you edit it... that was a "cheap" operation, since it happens a lot.. I didn't foresee someone would try to modify notes in the future. 😆

**Comment by pbek** [comment]
...otherwise I would need to rebuild the note list every time

**Comment by louwers** [comment]
>  I didn't foresee someone would try to modify notes in the future.

Hehe this was my try at hacking in the often requested 'pin' feature. Set the modified date in the future for 'pinned' notes, and keep it there after edits with a hook.

**Comment by pbek** [comment]
Ah, that would have been a nice "hack". 😁

**Comment by pbek** [comment]
At least that "hack" should work when you reload the note folder...

Or you could try to use https://www.qownnotes.org/scripting/hooks.html#onnotestored and then do a `mainWindow.buildNotesIndexAndLoadNoteDirectoryList(false, true);` every time you change a note. But I didn't test that...
