### ISSUE TITLE
Support auto-setting dark mode on Linux with `org.freedesktop.appearance.color-scheme`

### ISSUE THREAD

**Issue by louwers** [pbek/QOwnNotes#2525]
There should be an option to use the system wide dark mode setting on startup on Linux.

`org.freedesktop.appearance.color-scheme` can be used, see:

- https://blogs.gnome.org/alexm/2021/10/04/dark-style-preference/

Watching the dark mode preference and updating it real-time would be even cooler, but this is a good fist step. 

Example apps that use it:
- Telegram Desktop: https://github.com/telegramdesktop/tdesktop/issues/17061
- Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1734934

**Comment by pbek** [comment]
This only works for Gnome, right?
And it looks like you need to use GTK to check the setting, which QOwnNotes doesn't want to depend on...

**Comment by louwers** [comment]
It should also work for KDE. See the Telegram issue. It's also an official freedesktop spec.

**Comment by pbek** [comment]
But is there a way to include this without getting GTK (or KDE) dependencies?

**Comment by louwers** [comment]
It seems that a D-Bus library is intergrated into Qt? https://doc.qt.io/qt-5/qtdbus-index.html

I can take look at some point. For myself I found the following solution, that might be helpful to other people that want to toggle dark mode automatically. My solution is GNOME specific but can probably be adapted for KDE.

There is a very nice GNOME extension called [Night Theme Switcher](https://extensions.gnome.org/extension/2236/night-theme-switcher/). You can run custom commands on toggle:

![image](https://user-images.githubusercontent.com/649392/167247498-5d012156-2e4d-4061-be2d-d727f3448f2f.png)

I run this script to modify the config and to restart QOwnNotes:

```sh
#!/usr/bin/bash

if [[ $1 = "on" ]]; then
  dark=true
elif [[ $1 = "off" ]]; then
  light=true
else
  echo "Usage: dark-mode on|off"
  exit 1
fi

replace() {
  sed -ie --follow-symlinks 's/'$1'=.*/'$1'='$2'/' "$3"
}

qon=~/.config/PBE/QOwnNotes.conf

if [[ $dark ]]; then
  replace darkMode true $qon
  replace darkModeColors true $qon
  replace darkModeIconTheme true $qon
  replace CurrentSchemaKey EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f  $qon
elif [[ $light ]]; then
  replace darkMode false $qon
  replace darkModeColors false $qon
  replace darkModeIconTheme false $qon
  replace CurrentSchemaKey EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb $qon
fi
killall QOwnNotes
if [[ $? == 0 ]]; then
  QOwnNotes &
fi
```

**Comment by pbek** [comment]
> It seems that a D-Bus library is intergrated into Qt? https://doc.qt.io/qt-5/qtdbus-index.html

hm, which also adds another Qt library dependency just for this small feature... `QT += dbus` 😬 
https://code.qt.io/cgit/qt/qtbase.git/tree/examples/dbus/chat/chat.pro?h=5.15#n1

**Comment by louwers** [comment]
@pbek The following command line argument would avoid that dependency:

```
dbus-send --session --print-reply=literal --reply-timeout=1000 --dest=org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings.Read string:'org.freedesktop.appearance' string:'color-scheme'
```

`dbus-send` should be available on all systems where D-Bus is installed. It returns

```
variant       variant          uint32 1
```

to indicate a dark-mode preference (see [here](https://github.com/flatpak/xdg-desktop-portal/blob/main/data/org.freedesktop.impl.portal.Settings.xml#L40).

**Comment by pbek** [comment]
Sounds like a nice alternative, thank you. I wonder if you are able to execute that from a flatpak or snap... 🤔

**Comment by pbek** [comment]
All I got so far when running with QProcess under Linux natively with...

```cpp
    auto parameters = QStringList() <<
                    QStringLiteral("--session") << QStringLiteral("--print-reply=literal") << QStringLiteral("--reply-timeout=1000") <<
                    QStringLiteral("--dest=org.freedesktop.portal.Desktop") << QStringLiteral("/org/freedesktop/portal/desktop") <<
                    QStringLiteral("org.freedesktop.portal.Settings.Read") << QStringLiteral("string:'org.freedesktop.appearance' string:'color-scheme'");

    QProcess process;
    process.start(QStringLiteral("dbus-send"), parameters);
```

is

`Error org.freedesktop.DBus.Error.InvalidArgs: Type of message, “(s)”, does not match expected type “`.

Other permutations of input arguments (e.g. every part is a different argument item) got me: `Error org.freedesktop.portal.Error.NotFound: Requested setting not found\n`

**Comment by louwers** [comment]
@pbek You have to separate those two strings, otherwise it is interpreting it as one string.

```
QStringLiteral("string:'org.freedesktop.appearance' string:'color-scheme'");
```

**Comment by pbek** [comment]
## 22.6.1
- under Linux (with dbus) the application will now ask you if you want to turn on 
  dark mode if your desktop environment is in dark mode and the application is not
  (for [#2525](https://github.com/pbek/QOwnNotes/issues/2525))
    - the application will now also ask you if you want to turn off dark mode if your
      desktop environment is in light mode and the application has dark mode turned on
    - you can remember those decisions so that the switch will be made
      automatically next time

**Comment by pbek** [comment]
> @pbek I think you have to separate those two strings, otherwise it is interpreting it as one string.

I had them all separate in the beginning... `sh -c` did the trick

**Comment by louwers** [comment]
Turns out there is a [GNOME bug](https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/1897) that sets the preference to 'default' when setting light as a preference!

However, the QOwnNotes feature works as advertised. :+1:

**Comment by pbek** [comment]
Great, thank you for testing!
