### ISSUE TITLE
A note isn't removed. Bulk issue :)

### ISSUE THREAD

**Issue by LightTemplar** [pbek/QOwnNotes#253]
##### 1) If I remove a note with keyboard, I see different dialog, compared to removing with mouse, clicking the corresponding icon on the panel.

_Preparing to the next two issues:_
a) Find an empty folder in QON
b) Create a note. Then next one. We have two notes.

##### 2) Acting with keyboard:
c) Use keyboard only.
d) < delete>, < space> - first note removed
e) < delete>, < space> - **nothing gone**
f) < delete>, < space> - second note at last removed

##### 3) Acting with mouse
c) Click on the one note
d) Click the "remove note" icon on the panel
e) Click "remove" in the dialog
f) Click the "remove note" icon on the panel
g) Watch there the name of the just removed in step e) note
h) Click "remove" in the dialog - **nothing happend**, because focus haven't moved to existing note.
i) Go endless to f)

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your example.

**Comment by LightTemplar** [comment]
I like helping =)

**Comment by pbek** [comment]
That's a really tricky one...

**Comment by LightTemplar** [comment]
It's my special talent to find a rare unique bugs in system =)

**Comment by pbek** [comment]
That was a hard one. Again it was some directory watcher weirdness... I had to do dozens of different attempts to create a workaround, it now should be fixed in the next release. Can you please test that.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by LightTemplar** [comment]
2) & 3) have now gone, 
1) is still here.

**Comment by pbek** [comment]
Oh, that was an issue too? Sorry. :)
What did you expect that should happen? And why is that an issue? Which button did you click?

**Comment by LightTemplar** [comment]
I think, it shouldn't matter, how I delete a note - via keyboard or via a button on the panel above
![image](https://cloud.githubusercontent.com/assets/453783/16962577/8c923682-4df2-11e6-86af-18394d4a4d50.png)
I expect always the same dialog, That, which shows the note name. If it is the same function, it should look same.

**Comment by pbek** [comment]
The button, like it says deletes the current note (regardless of the selection in the note list), so it shows the note's name as confirmation. It has also a hotkey.
The delete functionality in the note list is able to delete multiple notes.
These are two separate functionalities...
