### ISSUE TITLE
Feature request: scripting methods for cusor operation

### ISSUE THREAD

**Issue by davuses** [pbek/QOwnNotes#2533]
I've always wanted to write a script to regester custom actions for cursor movement. In the scripting document, I found two methods QOwnNotes provides with regards to cursor position or movement: `noteTextEditSetCursorPosition(int position)` and `noteTextEditCursorPosition()`.

With these two methods, I can move cursor forward or backward by 1 (or a certain number) character like this:
`script.noteTextEditSetCursorPosition(currentPosition + 1);`

But I couldn't figure out how to move cursor to next line or previous line, just as the simple `up arrow` and `down arrow` keys do, probably an extra API for getting current line number is necessary. Or even more, how to move cursor to next/previous word or block.

I know the cursor moving keymap is available in Vim mode, but I'd like to just have some shortcuts for cursor moving without having to switch to full Vim mode.

I there a way to implement these cursor moving actions just with the API currently provided by QOwnNotes that I missed out? If so, could you give me some advises how to do that? If not, it would be very nice to have some extra scripting methods for cursor movement in QOwnNotes, I think this will offer a lot of flexibility for custom cursor operation.

Thank you in advance for your help:)

**Comment by pbek** [comment]
Since you have access to the note text you could calculate pretty any position by counting how many characters each line has, can't you?

**Comment by davuses** [comment]
> Since you have access to the note text you could calculate pretty any position by counting how many characters each line has, can't you?

I don't think I can do the character counting of each line with two methods above, any sugestions what methods can do the job?

**Comment by pbek** [comment]
```js
let lineList = noteText.split("\n");

// First line
lineList[0];

// Second line
lineList[1];
```

**Comment by davuses** [comment]
> ```js
> let lineList = noteText.split("\n");
> 
> // First line
> lineList[0];
> 
> // Second line
> lineList[1];
> ```

@pbek Thank you, I did manage to achieve that. Is there a way to move cursor to next/previous word or block?

**Comment by pbek** [comment]
You could try to split the lines by word boundary `\b` with `noteLine.split("\b");` and count how many words in a line your cursor currently is.
