### ISSUE TITLE
[F] Methods to mitigate preview 'jumping' when editing

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#2535]
A certain 'jumping' is visible in the preview panel when it is updated, especially when artifacts like images/diagrams are involved. As discussed on Telegram it's unlikely that this can be solved by a way of rendering before updating the view, calculating the scroll position without the image/diagram being rendered or by not scrolling the preview at all. 

Another suggestion to lessen the jumping is to postpone the update of the preview panel e.g. 500 ms after the last edit to initiate a render, a method commonly know as 'debounce'. Ideally a setting would exist to toggle this behavior and set the nr of milliseconds. Secondly it would be useful to be able to assign a shortcut to start a render, e.g. <kbd>Ctrl</kbd>+<kbd>S</kbd>, which, in combination with disabling automatic updating of the preview, would result in updating the preview solely on request of the user.

**Comment by pbek** [comment]
Thank you.

**Comment by pbek** [comment]
Do you have a note where you can see the "jumping" that you can post?

**Comment by pbek** [comment]
> Secondly it would be useful to be able to assign a shortcut to start a render, e.g. Ctrl+S, which, in combination with disabling automatic updating of the preview, would result in updating the preview solely on request of the user.

`Ctrl + S` already stores the note...
You could just create a new workspace with no preview activated and toggle between the last two workspaces with the shortcut...

**Comment by pbek** [comment]
There will be a debounce with a setting, default on with 600ms.

**Comment by sanderboom** [comment]
A jumpy note: [Archive.tar.gz](https://github.com/pbek/QOwnNotes/files/8761875/Archive.tar.gz)

> There will be a debounce with a setting, default on with 600ms.

Awesome!

**Comment by sanderboom** [comment]
Thanks, the debounce setting works! :rocket: 

Do you have an idea why the preview panel jumps twice (I've set the debounce to 2000ms btw)?

https://user-images.githubusercontent.com/5956570/170262909-cff3247f-d97f-4106-b214-bf1763cf3d72.mp4

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by pbek** [comment]
> Do you have an idea why the preview panel jumps twice after an edit (I've set the debounce to 2000ms btw)?

Hm, maybe first the rendering with an initial scrolling, then another scrolling because there was more rendering, redrawing or loading...

**Comment by sanderboom** [comment]
> Hm, maybe first the rendering with an initial scrolling, then another scrolling because there was more rendering, redrawing or loading...

:grimacing: This is happening almost for all notes for me. What's your experience? This means double the amount of jumping.

One more thing: what about an option to update the preview on save? Maybe a checkbox that disables automatic updates and adds the update to the save function.

**Comment by pbek** [comment]
> grimacing This is happening almost for all notes for me. What's your experience? This means double the amount of jumping.

I need to observe that more

> One more thing: what about an option to update the preview on save? Maybe a checkbox that disables automatic updates and adds the update to the save function.

can you please open a new feature request where you explain what warrants the added complexity 😅
