### ISSUE TITLE
After typing in folder search field all folders are expanded

### ISSUE THREAD

**Issue by LightTemplar** [pbek/QOwnNotes#254]
I tested the new feature "you can now also create a note subfolder by typing it into the search field and pressing Return".

Typed "test", pressed "Return", and watched all folders in folder tree stayed expanded.

**Comment by pbek** [comment]
Thank you for reporting, what do you mean by `watched all folders in folder tree stayed expanded`? And was the folder created?

**Comment by LightTemplar** [comment]
The folder was created, there was no problem.
Problem is, I have hundred subfolders under Root, which are all (didn't check whether really all, but indeed most of them ) got expanded.

**Comment by pbek** [comment]
This field is also for searching, if you type characters that is matching a folder name it will be viewed. Of course then that sub-tree needs to be expanded.

I don't see a way to get around this.

**Comment by LightTemplar** [comment]
You can turn off the remembering of node states, while someone search the folder. As soon this field is emptied, you can restore the state. 
Or, if you do it different, you can remember the nodes states, before the search begins, i.e. as soon the first character is entered in the field. And as soon the field is emptied, you can restore the state

**Comment by pbek** [comment]
I will take a look at that.

**Comment by pbek** [comment]
## 16.07.12
- the expand/collapse state of the items in the note subfolder tree will not 
  be stored while searching and restored when the search field is cleared
    - after a subfolder was created by the search field it will be cleared

**Comment by LightTemplar** [comment]
Did you push it to repos? I couldn't get the version.

**Comment by pbek** [comment]
it's in the `develop` branch

**Comment by LightTemplar** [comment]
Ah ok, I'll wait then.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by LightTemplar** [comment]
They work :)
though, it takes some time before the stand is restored, but I can deal with it. 
It's much better and the subfolder search can now be used! Thank you!

**Comment by pbek** [comment]
great :)
