### ISSUE TITLE
[I] Italicized markdown characters are garbled when exporting to PDF format.

### ISSUE THREAD

**Issue by sinh927** [pbek/QOwnNotes#2541]
#### Expected behaviour

Italicized strings, when exported to PDF, should be output correctly.

#### Actual behaviour

Italic strings are garbled when exported to PDF.
The editor's content is as follows:
![image](https://user-images.githubusercontent.com/6648716/170426850-38d495c1-cfee-4787-8564-801ea0a8dbb2.png)

The contents of the exported PDF are as follows:
![image](https://user-images.githubusercontent.com/6648716/170426919-d6d8fa6f-c8af-4003-9a5e-7d4a8ac51f47.png)

#### Steps to reproduce

Export -> PDF(Preview)

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `木 5 26 15:00:26 2022`
**Version**: `22.5.2`
**Build date**: `May 16 2022`
**Build number**: `965`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Qt Debug**: `0`
**Locale (system)**: `ja_JP`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1366x768`
**Screen resolution(s)**: `1366x768, 1280x1024`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `3`
**Calendar items**: `0`
**Enabled scripts**: `0`
</details>

**Comment by pbek** [comment]
Do you have an example note to test with?
Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting Debug in Options).
Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.

**Comment by pbek** [comment]
I don't seem to have any issues...

![image](https://user-images.githubusercontent.com/1798101/170650637-b8177afd-3761-40e6-934a-e55b4615140f.png)
