### ISSUE TITLE
Render issue with indented codeblocks and lists

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#2549]
#### Expected behaviour
Use an indented codeblock after a list and have it render properly.

#### Actual behaviour

![image](https://user-images.githubusercontent.com/5956570/172052138-708cf956-5bdc-48fc-b9be-408b3564cf1e.png)

See under 'Test 2' how the list is 'broken' (it seems every `<li> ` is surrounded by a new `<ul>`) and the codeblock renders rather as inline code instead of a codeblock.

**Comment by pbek** [comment]
Is this a rendering issue or a "markdown to html" conversion issue? Can you please post your example note.

**Comment by sanderboom** [comment]
> Is this a rendering issue or a "markdown to html" conversion issue? :eyes: 

```markdown
## Test

	some code
	secondline
	
- list afterwards
- second item

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
	
## Test2

- first a list
- that will not render well
- when followed by an indented block

	some code
	secondline

- list afterwards
- second item
	
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
```

**Comment by pbek** [comment]
The HTML is generated that way:

```html
<li><p>when followed by an indented block</p>
<p>some code
secondline</p>
</li>
<li><p>list afterwards</p>
```

Seems like a limitation of the md4c library...
@Waqar144, do you know anything on that by chance?

**Comment by Waqar144** [comment]
This is as per spec I think. A code block cannot interrupt a list, list takes precedence. But it could be that I misunderstand things, see https://spec.commonmark.org/0.30/#indented-code-blocks

**Comment by pbek** [comment]
Yes, thank you, @Waqar144. Example 108 exactly did look like this scenario! I guess I'll close this then...

**Comment by sanderboom** [comment]
> Example 108 exactly did look like this scenario! I guess I'll close this then...

Yes - as per spec. Too bad, though. Thanks for looking into this.
