### ISSUE TITLE
Log window shows nothing.

### ISSUE THREAD

**Issue by LightTemplar** [pbek/QOwnNotes#255]
I had all checkboxes on, but there was nothing, when I reloaded a calendar list. I did as described here http://www.qownnotes.org/Knowledge-base/My-calendars-cannot-be-fetched-from-my-ownCloud-server
 Also nothing, when I reconnected to OwnCloud server.

Debug Info follows

**Comment by LightTemplar** [comment]
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mo. Juli 18 21:59:51 2016`  
**Version**: `16.07.9`  
**Build date**: `Jul 18 2016`  
**Build number**: `200`  
**Platform**: `linux`  
**Operating System**: `Ubuntu 16.04 LTS`  
**Build architecture**: `x86_64`  
**Current architecture**: `x86_64`  
**Release**: `Launchpad PPA`  
**Qt Version (build)**: `5.5.1`  
**Qt Version (runtime)**: `5.5.1`  
**Locale (system)**: `en_GB`  
**Locale (interface)**: `en`  
**Icon theme**: `oxygen`  
**Notes in current note folder**: `94`  
**Enabled scripts**: `0`  

## Server Info

**serverUrl**: `https://*****.ocloud.de`  
**appIsValid**: `no`  
**connectionErrorMessage**: `Unknown error`  

## Note folders

**currentNoteFolderId**: `6`  

### default

**id**: `1`  
**activeTagId**: `2`  
**localPath**: `/media/******/Notes`  
**remotePath**: `Notes`  

### OCloud.de

**id**: `3`  
**activeTagId**: `-1`  
**localPath**: `/media/********/Notes`  
**remotePath**: `Notes`  

### Goals

**id**: `4`  
**activeTagId**: `-1`  
**localPath**: `/media/*******/Notes/Goals`  
**remotePath**: `Notes/Goals`  

### Diary

**id**: `5`  
**activeTagId**: `-1`  
**localPath**: `/media/*********/Notes/Diary`  
**remotePath**: `Notes/Diary`  

### Projects

**id**: `6`  
**activeTagId**: `0`  
**localPath**: `/media/********/Projects`  
**remotePath**: *empty*  

## Settings

**DistractionFreeMode/editorWidthMode**: `2`  
**DistractionFreeMode/isEnabled**: `false`  
**DistractionFreeMode/mainSplitterSizes**: `<binary data>`  
**DistractionFreeMode/menuBarGeometry**: `<binary data>`  
**DistractionFreeMode/menuBarHeight**: `32`  
**DistractionFreeMode/windowState**: `<binary data>`  
**LastUpdateCheck**: `2016-07-18T21:50:50`  
**LogDialog/criticalLog**: `true`  
**LogDialog/debugLog**: `true`  
**LogDialog/fatalLog**: `true`  
**LogDialog/geometry**: `<binary data>`  
**LogDialog/infoLog**: `true`  
**LogDialog/scriptingLog**: `true`  
**LogDialog/showAtStartup**: `false`  
**LogDialog/statusLog**: `true`  
**LogDialog/warningLog**: `true`  
**MainWindow/geometry**: `<binary data>`  
**MainWindow/mainToolBar.iconSize**: `22`  
**MainWindow/menuBarGeometry**: `<binary data>`  
**MainWindow/noteSubFolderTreeWidgetExpandState-6**: `******************************************`  
**MainWindow/noteTextEdit.code.font**: `Andale Mono,12,-1,0,50,0,0,0,0,0`  
**MainWindow/noteTextEdit.font**: `Noto Sans,15,-1,0,50,0,0,0,0,0`  
**MainWindow/noteTextView.code.font**: `Andale Mono,12,-1,0,50,0,0,0,0,0`  
**MainWindow/noteTextView.font**: `Noto Sans,12,-1,0,50,0,0,0,0,0`  
**MainWindow/showRecentNoteFolderInMainArea**: `true`  
**MainWindow/windowState**: `<binary data>`  
**PiwikClientId**: `<hidden>`  
**ShowSystemTray**: `false`  
**SortingModeAlphabetically**: `false`  
**allowDifferentNoteFileName**: `false`  
**allowOnlyOneAppInstance**: `true`  
**appMetrics/disableAppHeartbeat**: `false`  
**appMetrics/disableTracking**: `false`  
**appMetrics/notificationShown**: `true`  
**cryptoKey**: `<hidden>`  
**currentNoteFolderId**: `6`  
**customNoteFileExtensionList**: *empty*  
**darkMode**: `false`  
**darkModeColors**: `true`  
**defaultNoteFileExtension**: `txt`  
**demoNotesCreated**: `true`  
**disableAutomaticUpdateDialog**: `true`  
**externalEditorPath**: `/usr/share/atom/atom`  
**ignoreAllExternalModifications**: `false`  
**interfaceLanguage**: `en`  
**mainSplitterSizes**: `<binary data>`  
**mainSplitterState-0-1-1-0**: `<binary data>`  
**mainSplitterState-1-0-1-0**: `<binary data>`  
**mainSplitterState-1-1-0-0**: `<binary data>`  
**mainSplitterState-1-1-1-0**: `<binary data>`  
**markdownHighlightingInterval**: `200`  
**markdownViewEnabled**: `true`  
**networking/ignoreSSLErrors**: `false`  
**networking/proxyType**: `2`  
**noteEditPaneEnabled**: `true`  
**noteListSplitterState**: `<binary data>`  
**noteSaveIntervalTime**: `10`  
**notesPath**: `/media/*********/Projects`  
**notifyAllExternalModifications**: `false`  
**ownCloud/password**: `<hidden>`  
**ownCloud/serverUrl**: `https://*********.ocloud.de`  
**ownCloud/todoCalendarBackend**: `0`  
**ownCloud/todoCalendarEnabledList**: *empty*  
**ownCloud/todoCalendarEnabledUrlList**: *empty*  
**ownCloud/todoCalendarUrlList**: *empty*  
**ownCloud/userName**: `********`  
**recentNoteFolders**: `/media/******************/Notes/Diary, /media/***********/Notes, /media/************/Notes/Goals, /media/***********/Notes, /media/*********/Notes/Tesst`  
**savedSearches/noteFolder-1**: `Note 2016-07-02T12.59.43, Note 2016-06-23T18.15.14, Note 2016-06-18T20.36.54, Note 2016-06-18T18.54.06, Note 2016-06-15T12.40.17, Note 2016-06-15T11.45.02, Note 2016-06-11T16.53.12`  
**savedSearches/noteFolder-3**: `Goal Template, test`  
**savedSearches/noteFolder-4**: `Note 2016-06-23T12.26.35`  
**savedSearches/noteFolder-5**: `Note 2016-07-17T12.03.18, Note 2016-07-02T23.04.06, Note 2016-07-02T22.59.48, Note 2016-07-02T12.05.54, Note 2016-07-01T23.50.49, Note 2016-07-01T09.37.06, Note 2016-07-01T01.05.08, Note 2016-06-30T17.00.02, Note 2016-06-30T16.58.53, Note 2016-06-26T13.28.56, Note 2016-06-26T12.11.22, Note 2016-06-25T11.25.59, Note 2016-06-24T13.29.35, Note 2016-06-23T14.09.32, Note 2016-06-23T12.53.55, Note 2016-06-23T12.43.44`  
**savedSearches/noteFolder-6**: `Note 2016-07-17T19.54.45, Note 2016-07-17T14.39.08, Note 2016-07-17T14.38.28, Note 2016-07-17T14.38.26, Note 2016-07-17T14.27.26, Note 2016-07-17T14.17.14, Note 2016-07-17T14.17.13, Note 2016-07-17T14.17.11, Note 2016-07-17T14.16.30, Note 2016-07-17T14.15.09, Note 2016-07-16T16.11.06, Note 2016-07-16T16.10.51, Note 2016-07-16T15.23.37, Note 2016-07-15T20.00.42, Note 2016-07-15T20.00.36, Note 2016-07-15T19.57.49, Note 2016-07-15T18.48.32, Note 2016-07-15T18.08.12, Note 2016-07-15T18.08.05, Note 2016-07-14T18.41.34, Note 2016-07-14T18.41.26, Note 2016-07-13T18.11.19, Note 2016-07-13T14.50.02, Note 2016-07-13T14.48.55, Note 2016-07-13T14.47.34, Note 2016-07-12T11.25.08, Note 2016-07-11T13.35.00, Note 2016-07-11T12.21.31, Note 2016-07-11T12.03.33, Note 2016-07-09T22.45.53, Note 2016-07-09T20.44.02, Note 2016-07-01T16.15.47`  
**showStatusBar**: `true`  
**skipVersion**: `16.06.12`  
**tagFrameSplitterState**: `<binary data>`  
**tagsEnabled**: `true`  
**verticalNoteFrameSplitterState**: `<binary data>`

**Comment by pbek** [comment]
But you do get messages in the log window (for example before you cleared it), don't you? They just didn't were related to the todo lists, right?
Since you use Qt 5.5.1 and there was no log that would mean that you didn't get any network reply at all from your ownCloud server, I will then need to add more debug information... Maybe there are http-redirects in place...

**Comment by pbek** [comment]
Does your https://ocloud.de/ server provide the ownCloud calendar?

**Comment by LightTemplar** [comment]
No messages at all. 
![image](https://cloud.githubusercontent.com/assets/453783/16931722/a79fe61e-4d42-11e6-8831-44e68c9318e0.png)

https://ocloud.de/ should provide the ownCloud Calendar. It is the server we tried with other Account.

**Comment by pbek** [comment]
I don't understand why you don't get any log messages at all.
And was your QOwnNotes able to connect to your ownCloud server? You had a `connectionErrorMessage: Unknown error`.

**Comment by pbek** [comment]
You could also try to install the QOwnNotes snap, since I just recognized it is build in debug mode:
<http://www.qownnotes.org/installation#snap>

You will get more debug messages there.
I just tried it with the snap and an ocloud.de account I just created, it worked great.

**Comment by LightTemplar** [comment]
I've installed snap. The log window is still empty, but as I run QON from console, I could see messages hier. 
"connectionErrorMessage: Unknown error" because there is no QOwnNotes API on the server, I guess. 

![image](https://cloud.githubusercontent.com/assets/453783/16947698/d3edcd80-4db0-11e6-80da-dd1405558959.png)

**Comment by pbek** [comment]
I have no idea why do you can't see log message in the log dialog... And I have no clue on how to find out...

Looking at #229 I see you was able to solve the problem.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by pbek** [comment]
sorry, I wanted to post my last comment to #229 ;)
