### ISSUE TITLE
How to apply HTML style? 

### ISSUE THREAD

**Issue by it19862** [pbek/QOwnNotes#2550]
How to apply HTML style? 
QOwnNotes - 22.6
  

  <style type="text/css">
        .divback {
             background: Brown; /* Цвет фона */*/
         }
  </style>
  

<body>
    <div class ="divback">
		авпвап
	</div>
</body>

![07 06 2022_00-21-13](https://user-images.githubusercontent.com/18245828/172251468-b43a8c58-ee13-4eb2-b721-d204cf4bd2cd.png)

**Comment by pbek** [comment]
The QTextBrowser only supports a limited set of html (see https://doc.qt.io/qt-5/richtext-html-subset.html). Best use the `Custom note preview styling` script from the script repository to inject styles.

**Comment by ryliejamesthomas** [comment]
Hmmm. Actually it does recognise the `background` shorthand too.

I think your problem is due to you closing the CSS comment twice `/* Цвет фона */*/`. Remove one instance of `*/` and it works
