### ISSUE TITLE
Strikethrough according to spec?

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#2555]
It seems that in QON wrapping with a single `~` results in strikethrough markup. On several other places I see `~~` is necessary. Copy/pasting from QON to another location (e.g. here on GitLab, GitHub seems to accept a single `~` as  well) leads to unexpected results.

**Comment by pbek** [comment]
Since #274 we have double tilde support. Yes, and others support single tilde too like others... Is there any fault with that in your eyes?

**Comment by sanderboom** [comment]
Ofc it's up to you in how close you want to adhere to the spec. 

I just noticed that preparing markdown in QON and copy/paste-ing to GitLab means a mismatch in rendering.

Is you deviate from the spec, a fix for the following could also be in scope https://github.com/pbek/QOwnNotes/issues/2549 😉

**Comment by pbek** [comment]
I cannot reproduce that, I used the strikeout formatting in QON, generated `~~strike~~` with it and put that into the GitLab editor:

![image](https://user-images.githubusercontent.com/1798101/173187103-53b10345-1b34-476d-8a64-a7445963ba67.png)

**Comment by pbek** [comment]
...same on GitHub

**Comment by sanderboom** [comment]
I was referring to the use of a single `~`, not the (spec valid) double. But anyway, I see that in the online version of GitLab a single `~` is also accepted. Probably a recent change and the on-premise version that I'm using is probably some updates behind. Anyway - if most are accepting a single `~` than all is good. A standard is defined by the majority consensus and not by its original spec :sweat_smile: Closing this.
