### ISSUE TITLE
Why inserted image not displayed in a note?

### ISSUE THREAD

**Issue by localsnet** [pbek/QOwnNotes#2556]
#### Expected behaviour
To display inserted image

#### Actual behaviour

Not displayed image

#### Steps to reproduce

CTRL+SHIFT+I 

#### Output from the debug section in the settings dialog

![image](https://user-images.githubusercontent.com/29016091/175601419-9209c355-2f07-4a17-8227-0ed7be95f19f.png)

<details>
I've just update to the new version, but still have problems with pasting images to notes, it not displayed, but only open image when CTRL+ CLICK on the link. How to solve it? Thks

</details>

**Comment by pbek** [comment]
I cannot see a preview in your Screenshot. Do you have it enabled?
