### ISSUE TITLE
22.6.2 won't start under Windows

### ISSUE THREAD

**Issue by pcause** [pbek/QOwnNotes#2558]
#### Expected behaviour

ap0p launches

#### Actual behaviour

I get this:

![image](https://user-images.githubusercontent.com/1071479/176004467-c746f9eb-cebd-4200-962e-97ee955d85c7.png)

#### Steps to reproduce

start the app.

#### Other

Used the zip file for Winbdows.  Win11 Insider build.  Older version works

**Comment by pbek** [comment]
Thank you for reporting! Just a few lines of source code actually changed from the last release. Something must have wrong with the Qt library. 😬

**Comment by pbek** [comment]
If I build it myself under Windows it seems to work fine.

**Comment by pcause** [comment]
OK, perhaps I found something.  I reinstalled 22.6.1 and started.  Was running but not window appeared.  Remembered that there are keys used pbe in the registry and a directory in appdata.  deleted these and started 22.6.1 and it came up.  perhaps a problem with old settings/data.  

Overwrote the 22.62.2 binary when I downloaded 22.6.1 so can't try to see if deleting those and launch 22.6.2 works

**Comment by pbek** [comment]
Even stranger, because there are no new settings in the current release. But I had the same issue with the GitHub build on Windows 10. What happens if you run QOwnNotes in a new session? See `--session` https://www.qownnotes.org/getting-started/cli-parameters.html

**Comment by pbek** [comment]
Since I tried to rebuild 22.6.1 under Windows on GitHub and the build also failed. https://github.com/pbek/QOwnNotes/actions/runs/2442538312 😬  So it really seems something is amiss in the GitHub Windows environment or Qt itself. 😬

**Comment by pbek** [comment]
I'm now quite sure it's an issue with windeployqt.

**Comment by pbek** [comment]
@Waqar144, does this ostringstream und Windows issue ring any bell for you?

**Comment by Waqar144** [comment]
sounds like a dll issue. The symbol mentioned in the error is std::basic_ostringstream which should be in the C++ standard library. Maybe that is missing? Not sure about the name of the dll, probably it's libstd++.dll or something like that.

Is the dll present on the machine where it works?

**Comment by pbek** [comment]
> Is the dll present on the machine where it works?

libstd++.dll is present in the ZiP.

I can reproduce the issue on Win10 and Win8.1 (the latter machine dind't change for a long time). Even the old builds of QON are affected if I build them again in GitHub.
The QON Windows ZIPs between 22.6.1 and 22.6.2 are identical, only the exe itself and the translation files are different.

I still think the GitHub environment or windeployqt are the culprits...

**Comment by pbek** [comment]
I found the "culprit"! It's `windows-latest` in the GitHub build process, I guess it got updated to `windows-2022` (or something else changed there). When I use `windows-2019` the build and tests run fine again and it works great under Windows 8.1! 🥳

**Comment by Waqar144** [comment]
I think we can also try to drop mingw totally and switch to msvc. That would maybe avoid such problems

**Comment by pbek** [comment]
Sounds like a good idea, I don't have much experience with Microsoft's suit tho...

**Comment by pbek** [comment]
## 22.7.0
- the build system for Windows was fixed again (for [#2558](https://github.com/pbek/QOwnNotes/issues/2558))

There now is a new release, could you please test it and report if it works for you?

**Comment by pcause** [comment]
started up just fine and was able to see my files and navigate and display a note

**Comment by pbek** [comment]
Great, thank you!
