### ISSUE TITLE
Still having difficulties to open the QOwnNotes

### ISSUE THREAD

**Issue by Shahin-rmz** [pbek/QOwnNotes#2559]
#### Expected behaviour
 To open Normally

#### Actual behaviour
QOwnNotes closes after opening or booting up computer.

#### Steps to reproduce
Just opening the app

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>
## this is Nextcloud Loggs:

[no app in context] Error: OCP\AppFramework\Db\DoesNotExistException: Did expect one result but found none when executing: query "SELECT * FROM `*PREFIX*deck_cards` WHERE `id` = :dcValue1 ORDER BY `order` ASC, `id` ASC";  at <<closure>>

 0. /var/www/html/lib/public/AppFramework/Db/QBMapper.php line 363
    OCP\AppFramework\Db\QBMapper->findOneQuery(OC\DB\QueryBuilder\QueryBuilder {})
 1. /var/www/html/custom_apps/deck/lib/Db/CardMapper.php line 140
    OCP\AppFramework\Db\QBMapper->findEntity(OC\DB\QueryBuilder\QueryBuilder {})
 2. /var/www/html/custom_apps/deck/lib/Sharing/ShareAPIHelper.php line 56
    OCA\Deck\Db\CardMapper->find("35")
 3. /var/www/html/apps/files_sharing/lib/Controller/ShareAPIController.php line 318
    OCA\Deck\Sharing\ShareAPIHelper->formatShare(OC\Share20\Share {})
 4. /var/www/html/apps/files_sharing/lib/Controller/ShareAPIController.php line 894
    OCA\Files_Sharing\Controller\ShareAPIController->formatShare(OC\Share20\Share {}, null)
 5. /var/www/html/apps/files_sharing/lib/Controller/ShareAPIController.php line 836
    OCA\Files_Sharing\Controller\ShareAPIController->getFormattedShares("Shahin", null, false, false, false, false)
 6. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Files_Sharing\Controller\ShareAPIController->getShares("false", "false", "false", "", "false")
 7. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Files_Sharin ... {}, "getShares")
 8. /var/www/html/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Files_Sharin ... {}, "getShares")
 9. /var/www/html/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main("OCA\\Files_Shar ... r", "getShares", OC\AppFramework\ ... {}, ["ocs.files_sharing.ShareAPI.getShares"])
10. /var/www/html/ocs/v1.php line 62
    OC\Route\Router->match("/ocsapp/apps/fi ... s")
11. /var/www/html/ocs/v2.php line 23
    require_once("/var/www/html/ocs/v1.php")

GET /ocs/v2.php/apps/files_sharing/api/v1/shares
from 162.158.248.72 by Shahin at 2022-06-30T20:02:59+00:00

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

Hello, 
As I have once declared the problem, I have problem with opening QOwnNotes.
You have already told me this is Nextcloud problem. In Nextcloud what I see, is just loggs related to Qownnotes. any hints where can be my problem?
Ps. If I open the app, sooner than the queries, it won't crash.

Thanks for help

**Comment by pbek** [comment]
> ## this is Nextcloud Loggs:
>
> [no app in context] Error: OCP\AppFramework\Db\DoesNotExistException: Did expect one result but found none when executing: query "SELECT * FROM *PREFIX*deck_cards WHERE id = :dcValue1 ORDER BY order ASC, id ASC"; at <>

Your Nextcloud server seem to crash because the *Nextcloud Deck* tables doesn't seem to exist. Best uninstall *Nextcloud Deck* on your server (and install it again if you really need it). That may create the necessary database tables.

>  Ps. If I open the app, sooner than the queries, it won't crash.

Can you please explain what you mean by this?

**Comment by Shahin-rmz** [comment]
With your guidance, I could disable and remove the deck app from Nextcloud.
And then I didn't have problem with QOwnNotes anymore.
After reinstalling Deck app, the Problem appears again.
It seems there is something wrong with Deck app, that I should figure out.
Thanks for help.

**Comment by pbek** [comment]
Great!
But bugs me is that you wrote that QOwnNotes closed upon startup. Your server throwing an error 500 shouldn't have any effect on QOwnNotes starting up! According to my code the Nextcloud file-share request should just fail silently in QOwnNotes...

**Comment by Shahin-rmz** [comment]
Maybe I should try to paste the logging of QOwnNotes here.
The problem is, I can't catch any loggings because it closes.
Maybe I try to do a screen record or something later on.

**Comment by pbek** [comment]
You could enable logging to a log file in the *Debug options* settings. Maybe the log file gets written before the app closes...

**Comment by pbek** [comment]
Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting Debug in Options).

**Comment by pbek** [comment]
Did any app quit because of the Nextcloud error 500 happen during that log?

> [Jul 01 11:30:23] [warning]: "QNetworkReply error 401 from url https://nextcloud.accerun.com/ocs/v2.php/apps/files_sharing/api/v1/shares: " "Error transferring https://nextcloud.accerun.com/ocs/v2.php/apps/files_sharing/api/v1/shares - server replied: Internal Server Error"

I can see this, but this doesn't seem to have caused any harm...

**Comment by Shahin-rmz** [comment]
> Did any app quit because of the Nextcloud error 500 happen during that log?

No, as far as I see, QOwnNotes is the only app that I use which closes due to problem. I have to mention that, when Deck is uninstalled, QOwnNotes does **not** have any problems.

**Comment by pbek** [comment]
> QOwnNotes does not have any problems.

Great, that's all what I wanted to know. 😁  👍🏻  Thank you!
