### ISSUE TITLE
When you enter new or changing tasks in Russian. the task is saved as "???.....????".

### ISSUE THREAD

**Issue by AlexanderSu** [pbek/QOwnNotes#256]
System - windows7 (russian), server locale - LANG=ru_RU.UTF-8

**Comment by pbek** [comment]
Thank you for reporting, that definitely worked on newer versions of Windows, can you please post some of the characters you were entering.

**Comment by pbek** [comment]
And can you please post the output from the debug tab in the settings.

**Comment by pbek** [comment]
And can you read your Language in the language list in the interface settings tab, or is that gobbled too?

**Comment by AlexanderSu** [comment]
![load](https://cloud.githubusercontent.com/assets/7478549/16961855/f402621a-4df7-11e6-88d2-76db457d982e.JPG)
Load task list -good
![after chec comlite](https://cloud.githubusercontent.com/assets/7478549/16961922/3217c194-4df8-11e6-9691-c983cb90019f.JPG)
It noted completed through the program. "Задача3"="??????3"
![add new](https://cloud.githubusercontent.com/assets/7478549/16962055/ba9127c2-4df8-11e6-84eb-09b378b34771.JPG)
Add new task "Задача4"

**Comment by AlexanderSu** [comment]
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Вт июл 19 21:38:17 2016`  
**Version**: `16.07.9`  
**Build date**: `Jul 18 2016`  
**Build number**: `1918`  
**Platform**: `windows`  
**Operating System**: `Windows 7`  
**Build architecture**: `i386`  
**Current architecture**: `x86_64`  
**Release**: `AppVeyor`  
**Qt Version (build)**: `5.5.1`  
**Qt Version (runtime)**: `5.5.1`  
**Locale (system)**: `ru_RU`  
**Locale (interface)**: *empty*  
**Icon theme**: `breeze-qownnotes`  
**Notes in current note folder**: `2`  
**Enabled scripts**: `0`  

## Server Info

**serverUrl**: `https://192.168.1.9/owncloud`  
**appIsValid**: `yes`  
**serverVersion**: `8.2.3.2`  
**appVersion**: `0.4.4`  

## Note folders

**currentNoteFolderId**: `1`  

### по умолчанию

**id**: `1`  
**activeTagId**: `0`  
**localPath**: `E:/owcloud/Notes`  
**remotePath**: `Notes`  

## Settings

**LastUpdateCheck**: `2016-07-19T21:30:20`  
**LogDialog/showAtStartup**: `false`  
**MainWindow/geometry**: `<binary data>`  
**MainWindow/mainToolBar.iconSize**: `24`  
**MainWindow/menuBarGeometry**: `<binary data>`  
**MainWindow/noteTextEdit.code.font**: `Courier New,9,-1,2,50,0,0,0,0,0`  
**MainWindow/noteTextEdit.font**: `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`  
**MainWindow/noteTextView.code.font**: `Courier New,9,-1,2,50,0,0,0,0,0`  
**MainWindow/noteTextView.font**: `,8.25,-1,5,50,0,0,0,0,0`  
**MainWindow/showRecentNoteFolderInMainArea**: `false`  
**MainWindow/windowState**: `<binary data>`  
**PiwikClientId**: `<hidden>`  
**ShowSystemTray**: `false`  
**SortingModeAlphabetically**: `false`  
**TodoDialog/geometry**: `<binary data>`  
**TodoDialog/mainSplitterState**: `<binary data>`  
**TodoDialog/showCompletedItems**: `2`  
**TodoDialog/todoListSelectorSelectedItem**: `personal`  
**allowDifferentNoteFileName**: `false`  
**allowOnlyOneAppInstance**: `true`  
**appMetrics/disableAppHeartbeat**: `false`  
**appMetrics/disableTracking**: `true`  
**appMetrics/notificationShown**: `true`  
**cryptoKey**: `<hidden>`  
**currentNoteFolderId**: `1`  
**customNoteFileExtensionList**: *empty*  
**darkMode**: `false`  
**darkModeColors**: `false`  
**defaultNoteFileExtension**: `txt`  
**disableAutomaticUpdateDialog**: `false`  
**externalEditorPath**: *empty*  
**ignoreAllExternalModifications**: `false`  
**interfaceLanguage**: *empty*  
**mainSplitterSizes**: `<binary data>`  
**mainSplitterState-0-1-1-0**: `<binary data>`  
**markdownHighlightingInterval**: `200`  
**networking/ignoreSSLErrors**: `true`  
**networking/proxyType**: `0`  
**noteListSplitterState**: `<binary data>`  
**noteSaveIntervalTime**: `10`  
**notesPath**: `E:/owcloud/Notes`  
**notifyAllExternalModifications**: `false`  
**ownCloud/password**: `<hidden>`  
**ownCloud/serverUrl**: `https://192.168.1.9/owncloud`  
**ownCloud/todoCalendarBackend**: `0`  
**ownCloud/todoCalendarEnabledList**: `personal`  
**ownCloud/todoCalendarEnabledUrlList**: `https://192.168.1.9/owncloud/remote.php/caldav/calendars/root/personal/`  
**ownCloud/todoCalendarUrlList**: `https://192.168.1.9/owncloud/remote.php/caldav/calendars/root/personal/`  
**ownCloud/userName**: `root`  
**savedSearches/noteFolder-1**: `Note 2016-07-15T07.27.15`  
**showStatusBar**: `true`  
**tagFrameSplitterState**: `<binary data>`  
**trashSplitterSizes**: `<binary data>`  
**verticalNoteFrameSplitterState**: `<binary data>`

**Comment by pbek** [comment]
Oh, tasks. Sorry, I was thinking about notes.
Thank you, does it work when you create the task in the ownCloud web-interface? And gets it synced down correctly?

**Comment by AlexanderSu** [comment]
The ownCloud web-interface- all good. When downloading - all good. After the changes, or create a new task through the program displays "???" in web-interface and program.

**Comment by pbek** [comment]
So there is a character set problem when storing tasks on the caldav server. I will take a look at that, thank you for reporting. caldav is a hell to develop with...

**Comment by pbek** [comment]
Will be fixed in 16.07.11.

**Comment by AlexanderSu** [comment]
It will be good, Thanks

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by AlexanderSu** [comment]
Now the task is stored correctly. Thanks

**Comment by pbek** [comment]
Great, thanks again for reporting!
