### ISSUE TITLE
problems in resizing images with space in filename in preview panel and in exported HTML

### ISSUE THREAD

**Issue by n-wissam** [pbek/QOwnNotes#2561]
#### Expected behaviour
Renaming images that are wider than the preview panel using `manage stored images files` shouldn't affect resizing them in preview pane or after exporting preview as pdf or HTML

#### Actual behaviour
Images that are wider than the preview panel are being resized normally to fit in the preview panel (or after exporting the preview to pdf or HTML) as usual. But after going to `manage stored images files` and renaming an image that is wider than the preview panel, this image specifically won't be resized in preview panel at all.
The image is not resized after exporting the preview to HTML too, and the image is **cropped** after exporting the preview to pdf (only the part of the image that can fit to preview panel width is exported and the rest of the image is cropped)

deleting the image in media directory and using it again or using the same image in another note doesn't help too.
renaming the same image (not using `manage stored images files`  of course) and inserting it again makes things normal as usual

#### Steps to reproduce
- create a note and add some images
- go to `edit` -->  `manage stored images files` and rename an image that is wider than the preview panel
- answer yes to the "Would you also like to rename those images in the note(s)?" question
- image is not resizable anymore
- export preview to HTML: the image is not resized proberly
- export preview to pdf: the image is not resized proberly and/or is cropped

#### Some other minor issues:
- renaming an image in `manage stored images files`  should highlight the file name only without the extention.
- using the same image in another note (using drag and drop) should not make another copy with a different name of the same image in media directory.
- using an image inside media directory in a note directory (using drag and drop) shouldn't make another copy of the same image in a different name.

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mon Jul 11 00:34:53 2022`
**Version**: `22.7.1`
**Build date**: `Jul  8 2022`
**Build number**: `971`
**Platform**: `linux`
**Operating System**: `EndeavourOS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.5`
**Qt Version (runtime)**: `5.15.5`
**Portable mode**: `no`
**Settings path / key**: `/home/wissam/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/wissam/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1366x768`
**Icon theme**: `la-capitaine`
**Notes in current note folder**: `9`
**Calendar items**: `0`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/home/wissam/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/wissam/Documents/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/wissam/Documents/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

### Script `Mermaid Diagrams`

**id**: `1`
**path**: `/home/wissam/.local/share/PBE/QOwnNotes/scripts/mermaid/mermaid.qml`
**variablesJson**: *empty*
**identifier**: `mermaid`
**version**: `0.0.4`
**minAppVersion**: `22.1.1`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `true`
**DistractionFreeMode/editorWidthMode** (QString): `2`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `23`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `/home/wissam`
**FileDialog/LastPath-NoteHTMLExport** (QString): `/home/wissam`
**FileDialog/LastPath-NotePDFExport** (QString): `/home/wissam`
**FileDialog/LastPath-PreviewHTMLFileExport** (QString): `/home/wissam`
**FileDialog/LastPath-ScriptPath** (QString): `/home/wissam`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2022-07-11T00:34:44.198`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `test, Languages, Networking`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,12,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (QString): `600`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `false`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**NoteFolder-1/NoteTabNameList** (QStringList): `CCNA, Info, CCNA Notes`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): 
```
Networking
CBT Nuggets - CCNA 200-301, Networking
CBT Nuggets - CCNA 200-301, Networking
```
**NoteFolder-1/allowDifferentNoteFileName** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 32 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `31`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExport** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**StoredImagesDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `PCfSCAW9QqbE`
**cursorWidth** (QString): `1`
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `512`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `13`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `18`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `false`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `false`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/wissam/Documents/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `true`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `0`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `LAtTZFtHV3Nv`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `test, Note 2022-07-10T20.13.28, temp, 4, Note 2022-07-09T09.36.10`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useSoftWrapInNoteEditor** (QString): `true`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (QString): `22222`
**workspace-072e9dc9-8ac5-4465-b758-9351724b22b7/name** (QString): `Edit`
**workspace-072e9dc9-8ac5-4465-b758-9351724b22b7/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-072e9dc9-8ac5-4465-b758-9351724b22b7/windowState** (QByteArray): `<binary data>`
**workspace-LAtTZFtHV3Nv/name** (QString): `Preview only`
**workspace-LAtTZFtHV3Nv/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-LAtTZFtHV3Nv/windowState** (QByteArray): `<binary data>`
**workspace-PCfSCAW9QqbE/name** (QString): `Full`
**workspace-PCfSCAW9QqbE/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-PCfSCAW9QqbE/windowState** (QByteArray): `<binary data>`
**workspace-c080838b-b85b-44f9-909e-e14abdc5de08/name** (QString): `wissam`
**workspace-c080838b-b85b-44f9-909e-e14abdc5de08/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-c080838b-b85b-44f9-909e-e14abdc5de08/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, c080838b-b85b-44f9-909e-e14abdc5de08, LAtTZFtHV3Nv, PCfSCAW9QqbE, 072e9dc9-8ac5-4465-b758-9351724b22b7`

## System environment

**SHELL**: `/bin/bash`
**XDG_CONFIG_DIRS**: `/etc/xdg`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**XDG_MENU_PREFIX**: `xfce-`
**LC_ADDRESS**: `en_AG`
**LC_NAME**: `en_AG`
**DESKTOP_SESSION**: `xfce`
**LC_MONETARY**: `en_AG`
**EDITOR**: `nano`
**GTK_MODULES**: `canberra-gtk-module:canberra-gtk-module`
**XDG_SEAT**: `seat0`
**PWD**: `/home/wissam`
**XDG_SESSION_DESKTOP**: `xfce`
**LOGNAME**: `wissam`
**XDG_SESSION_TYPE**: `x11`
**XAUTHORITY**: `/home/wissam/.Xauthority`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/wissam`
**MOTD_SHOWN**: `pam`
**HOME**: `/home/wissam`
**LANG**: `en_US.UTF-8`
**LC_PAPER**: `en_AG`
**XDG_CURRENT_DESKTOP**: `XFCE`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**LC_IDENTIFICATION**: `en_AG`
**USER**: `wissam`
**SHLVL**: `0`
**LC_TELEPHONE**: `en_AG`
**LC_MEASUREMENT**: `en_AG`
**XDG_VTNR**: `7`
**XDG_SESSION_ID**: `2`
**PT8HOME**: `/opt/packettracer/`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**LC_TIME**: `en_AG`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `1`
**GTK3_MODULES**: `xapp-gtk3-module:xapp-gtk3-module`
**XDG_DATA_DIRS**: `/usr/local/share:/usr/share`
**BROWSER**: `firefox`
**PATH**: `/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
**GDMSESSION**: `xfce`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**MAIL**: `/var/spool/mail/wissam`
**LC_NUMERIC**: `en_AG`
**SESSION_MANAGER**: `local/android:@/tmp/.ICE-unix/508,unix/android:/tmp/.ICE-unix/508`
**SSH_AUTH_SOCK**: `/tmp/ssh-XXXXXX8ekx0w/agent.570`
**SSH_AGENT_PID**: `571`
**PANEL_GDK_CORE_DEVICE_EVENTS**: `0`
**DISPLAY**: `:0.0`

**Comment by pbek** [comment]
Are we talking of #1658 or similar?

**Comment by n-wissam** [comment]
Yes the same as #1658  but only after renaming the image in `manage stored images files`, the image is no longer resized properly in preview or in exported HTML or PDF. before renaming the image everything is fine.

Does [this function](https://github.com/pbek/QOwnNotes/blob/39534722c6930ef2fcd8f4ee0c3022c9d96e2232/src/dialogs/storedimagesdialog.cpp#L402) regenerate the preview or just reload the note edit panel?

**Comment by pbek** [comment]
> create a note and add some images
> go to edit --> manage stored images files and rename an image that is wider than the preview panel
> answer yes to the "Would you also like to rename those images in the note(s)?" question
> image is not resizable anymore

I did all that and the image was resized in the preview as it did before for me...
I made the preview panel very small and the image was always resized properly.

> export preview to HTML: the image is not resized proberly

no issues there neither

> export preview to pdf: the image is not resized proberly and/or is cropped

no issues there, but the usual cut-off issue if an image is to wide

**Comment by n-wissam** [comment]
I tried multiple images and I got the same behavior
As an example I tried with this test_image.jpg file and that's what I got after and before renaming the image and after exporting to pdf too (page size A4)
Note that the upper-left corner of the image is black that's why it looks like a black image after renaming. it's not black it's just the same image cropped

![beofre rename](https://user-images.githubusercontent.com/109042485/178245842-d408ba64-7f2b-40fa-b358-d790909391e8.png)

![after rename](https://user-images.githubusercontent.com/109042485/178245866-a728f6d4-9116-445b-b7dd-401da914e838.png)

[test.pdf](https://github.com/pbek/QOwnNotes/files/9083173/test.pdf)

**Comment by pbek** [comment]
What happens if you select another note and then select the "test" note again?

**Comment by n-wissam** [comment]
Same thing. I tried that and I tried restarting QON.
The problem persists until I rename the image (not using 'manage stored images files')  and insert it again

**Comment by pbek** [comment]
I cannot reproduce that at all. Do you have a note folder with note and image where that happens to share?

**Comment by n-wissam** [comment]
I deleted configuration files and started with an empty note directory.
It turned out that the problem happens when you insert an image with a space in its name or when you rename the filename to a new name with a space in it.
So there is no problem in 'manage stored images files` I guess. the problem is with images with a space in its name.
can you reproduce that?

**Comment by n-wissam** [comment]
I started a new session for testing
I chose the note directory to be '/home/wissam/Notes' and it's an empty directory
I created a note named 'test.md'
adding any image with a space in its name makes it non-resizable. (eg: `new name.jpg` or `image 1.png`)
no problem in inserting any image without a space in its name (eg: `new_name.jpg` or `image1.png')

When inserting multiple images in a note, only the images that don't contain space in their names are resizable

here I added an image with a filename `background.jpg` and a copy of the same image with a filename `background 2.jpg`. the first image is resizable and the second is not.

![Screenshot_2022-07-11_21-46-50](https://user-images.githubusercontent.com/109042485/178336872-f3e13b66-d3ee-4d73-ba97-d0dcb6b85416.png)

**Comment by pbek** [comment]
Hah, I can reproduce it now. Thank you! That's a really funny issue.

**Comment by n-wissam** [comment]
> Hah, I can reproduce it now. Thank you! That's a really funny issue.

Well, it wasn't funny for me to guess what was really going on :smile:


It would be really nice if you consider those minor issues too.

> #### Some other minor issues:
> 
>     * renaming an image in `manage stored images files`  should highlight the file name only without the extention.
> 
>     * using the same image in another note (using drag and drop) should not make another copy with a different name of the same image in media directory.
> 
>     * using an image inside media directory in a note directory (using drag and drop) shouldn't make another copy of the same image in a different name.


Thank you!

**Comment by pbek** [comment]
## 22.7.2
- automatic resizing of images in the preview with space characters in filename is now 
  also implemented (for [#2561](https://github.com/pbek/QOwnNotes/issues/2561))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by n-wissam** [comment]
> There now is a new release, could you please test it and report if it works for you?

Thank you!

**Comment by pbek** [comment]
Great, thank you for testing!
