### ISSUE TITLE
Renaming an image in `manage stored images files`  should highlight the filename only without the extention.

### ISSUE THREAD

**Issue by n-wissam** [pbek/QOwnNotes#2562]
#### Expected behaviour
Renaming an image in `manage stored images files`  should highlight the filename only without the extension.
#### Actual behaviour
Renaming an image in `manage stored images files`  highlights the filename and the extension. So one may delete the extension when renaming the image file without noticing.
#### Steps to reproduce
Go to `edit` and then `manage stored images files` and then choose an image and rename it.
#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Jul 12 14:38:27 2022`
**Version**: `22.7.1`
**Build date**: `Jul  8 2022`
**Build number**: `971`
**Platform**: `linux`
**Operating System**: `EndeavourOS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.5`
**Qt Version (runtime)**: `5.15.5`
**Portable mode**: `no`
**Settings path / key**: `/home/wissam/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/wissam/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`, `--allow-multiple-instances`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1366x768`
**Icon theme**: `la-capitaine`
**Notes in current note folder**: `13`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/home/wissam/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/wissam/Documents/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: `CCNA Todd Lammle`
**database file**: `/home/wissam/Documents/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/isEnabled** (bool): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (int): `23`
**DistractionFreeMode/menuBarVisible** (bool): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `/home/wissam`
**FileDialog/LastPath-NotePDFExport** (QString): `/home/wissam`
**LastUpdateCheck** (QDateTime): `2022-07-12T14:21:58.955`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Networking`
**MainWindow/noteTextEdit.code.font** (QString): `Noto Sans Mono,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (QString): `600`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/note-replace-images** (QString): `16384`
**NoteFolder-1/NoteTabNameList** (QStringList): `Understanding Cisco Modules`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): 
```
Networking
CBT Nuggets - CCNA 200-301
```
**NoteHistory-1** (QVariantList): `<variant list with 7 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `6`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExport** (QByteArray): `<binary data>`
**Printer/NotePrinting** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**StoredImagesDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `18`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `false`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/wissam/Documents/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `adc747e7-3ffc-42a5-ae25-6cae0695b1de`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `false`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `true`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (QString): `22222`
**workspace-43dedf98-9388-4106-9f30-d1d3d628d33b/name** (QString): `Just Preview`
**workspace-43dedf98-9388-4106-9f30-d1d3d628d33b/noteSubFolderDockWidgetVisible** (bool): `false`
**workspace-43dedf98-9388-4106-9f30-d1d3d628d33b/windowState** (QByteArray): `<binary data>`
**workspace-adc747e7-3ffc-42a5-ae25-6cae0695b1de/name** (QString): `Markdown only`
**workspace-adc747e7-3ffc-42a5-ae25-6cae0695b1de/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-adc747e7-3ffc-42a5-ae25-6cae0695b1de/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, adc747e7-3ffc-42a5-ae25-6cae0695b1de, 43dedf98-9388-4106-9f30-d1d3d628d33b`

## System environment

**SHELL**: `/bin/bash`
**XDG_CONFIG_DIRS**: `/etc/xdg`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**XDG_MENU_PREFIX**: `xfce-`
**LC_ADDRESS**: `en_AG`
**LC_NAME**: `en_AG`
**DESKTOP_SESSION**: `xfce`
**LC_MONETARY**: `en_AG`
**EDITOR**: `nano`
**GTK_MODULES**: `canberra-gtk-module:canberra-gtk-module`
**XDG_SEAT**: `seat0`
**PWD**: `/home/wissam`
**XDG_SESSION_DESKTOP**: `xfce`
**LOGNAME**: `wissam`
**XDG_SESSION_TYPE**: `x11`
**XAUTHORITY**: `/home/wissam/.Xauthority`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/wissam`
**MOTD_SHOWN**: `pam`
**HOME**: `/home/wissam`
**LANG**: `en_US.UTF-8`
**LC_PAPER**: `en_AG`
**XDG_CURRENT_DESKTOP**: `XFCE`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**LC_IDENTIFICATION**: `en_AG`
**USER**: `wissam`
**SHLVL**: `0`
**LC_TELEPHONE**: `en_AG`
**LC_MEASUREMENT**: `en_AG`
**XDG_VTNR**: `7`
**XDG_SESSION_ID**: `2`
**PT8HOME**: `/opt/packettracer/`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**LC_TIME**: `en_AG`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `1`
**GTK3_MODULES**: `xapp-gtk3-module:xapp-gtk3-module`
**XDG_DATA_DIRS**: `/usr/local/share:/usr/share`
**BROWSER**: `firefox`
**PATH**: `/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
**GDMSESSION**: `xfce`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**MAIL**: `/var/spool/mail/wissam`
**LC_NUMERIC**: `en_AG`
**SESSION_MANAGER**: `local/android:@/tmp/.ICE-unix/504,unix/android:/tmp/.ICE-unix/504`
**SSH_AUTH_SOCK**: `/tmp/ssh-XXXXXXutrGmF/agent.566`
**SSH_AGENT_PID**: `567`
**PANEL_GDK_CORE_DEVICE_EVENTS**: `0`
**DISPLAY**: `:0.0`

</details>

**Comment by pbek** [comment]
Thank you

**Comment by pbek** [comment]
It's hard to override that QTreeWidget functionality and I don't even think it's a good idea. Most operating system use MimeTypes anyway instead of extensions and a may want to rename for example `jpeg` files to `jpg` or change the case of an extension.

**Comment by n-wissam** [comment]
Do [this](https://stackoverflow.com/questions/10825921/how-do-you-hide-file-extensions-on-a-qfilesystemmodel) and [this](https://stackoverflow.com/questions/39667510/qstyleditemdelegate-partially-select-text-of-default-qlineedit-editor) help?
