### ISSUE TITLE
Dragging and dropping an image should not make another copy of the same image with a different name in media directory.

### ISSUE THREAD

**Issue by n-wissam** [pbek/QOwnNotes#2563]
#### Expected behaviour
Dragging and dropping an image that was used before and is already stored in media directory should not make another copy of the same image with a different name
#### Actual behaviour
When dragging and dropping an image that was used previously, another copy of the same image is stored in media directory with a different name.

For example: inserting an image with a name `image.png` (using dragging and dropping) multiple times makes another copy of the same image in media directory with names: `image-1.png`, `image-2.png` ... etc

**Note**: dragging and dropping an image from media directory makes another copy of the same image with a different name in media directory too

**Comment by pbek** [comment]
I don't think that's a good idea per se. You should for example be able to add a scribble image multiple times as new copy so you are able edit it afterwards.

**Comment by pbek** [comment]
But maybe with a dialog to ask if a copy should be created or not...

**Comment by n-wissam** [comment]
> But maybe with a dialog to ask if a copy should be created or not...

I think this will be a good idea and maybe let the user type the new name too

It would be nice too to detect when pasting an image as a binary file (not as a link) to let the user type the name of the image instead of naming the file to something like `qownnotes-media-KAasrw.png`  . This is useful when taking snapshots from PDFs or copying images from a web browser and pasting them into QON.

**Comment by pbek** [comment]
There are so many ways how images can get into notes, some of them automatically import multiple images at the same time... I don't care to invent new dialogs and ways to deal with multi-image imports and refactor the dozen ways to get images into QON, while you can rename the images images easily in the stored images dialog 😁

**Comment by n-wissam** [comment]
>  I don't care to invent new dialogs and ways to deal with multi-image imports and refactor the dozen ways to get images into QON, while you can rename the images images easily in the stored images dialog grin

Fair enough
it's not a dozen ways though. it' either a binary image or not :smile: . But you are right anyway

**Comment by pbek** [comment]
## 22.7.3
- if you now add an image again to a note, and it has the same filename and is binary
  identical to an image already existing in the media folder then you will be asked if
  you want to use the existing image instead (for [#2563](https://github.com/pbek/QOwnNotes/issues/2563))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by n-wissam** [comment]
It works as expected
Thank you very much

**Comment by pbek** [comment]
Great, thank you for testing!
