### ISSUE TITLE
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

### ISSUE THREAD

**Issue by Goddard** [pbek/QOwnNotes#2564]
I run into this error in Flatpak in Kubuntu.

`ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`

Causing random crashes....

**Comment by pbek** [comment]
Best open that issue on https://github.com/flathub/org.qownnotes.QOwnNotes/issues. The flatpak is community contributed.
