### ISSUE TITLE
Preserve tabs layout (possibly for workspaces?)

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2565]
#### Expected behaviour
I have different tabs layout for projects, and I'd like to quickly switch between then : when I change the preserved layout, all the tabs on the tab panel are replaced accordingly.

#### Actual behaviour
Couldn't find any existing implementation.

Possibly, this could be a part of Workspaces as a configurable option?
Or maybe some new control can be added, similar to Workspaces, but containing tabs layouts and some other stuff, all in vibe of Projects/Views..

**Comment by pbek** [comment]
Just create a new workspace and make your ui layout changes to new workspace.

**Comment by pbek** [comment]
See https://www.qownnotes.org/blog/2021-08-25-Use-workspaces-to-manage-different-kayouts-of-the-user-interface.html

**Comment by macsunmood** [comment]
> See https://www.qownnotes.org/blog/2021-08-25-Use-workspaces-to-manage-different-kayouts-of-the-user-interface.html

Creating new workspace doesn't let me make open notes tabs arrangements (I didn't mention the case was about notes, sorry).

So, I'd like to add the option to include the notes tabs panel layouts (with open notes) into Workspaces, or possibly Projects/Views..

**Comment by pbek** [comment]
Sorry, workspaces don't open notes in tabs automatically. They are just used for preserving the panel layout, for example to switch between a workspace with and without preview panel.

**Comment by macsunmood** [comment]
> Sorry, workspaces don't open notes in tabs automatically. They are just used for preserving the panel layout, for example to switch between a workspace with and without preview panel.

I understand, so that's what my suggested new feature is all about.
Many people have projects, which not only imply similar note tags, but also their open tabs arrangements/layouts. Just as in any modern code editor/ide, like Sublime Text or VS Code..
What do you think ? :)

**Comment by pbek** [comment]
That would be a major change of the workspaces and a settings page for managing workspace with their settings. So I guess that will never happen.

**Comment by macsunmood** [comment]
> That would be a major change of the workspaces and a settings page for managing workspace with their settings. So I guess that will never happen.

Can this be implemented using Scripting? I've found the `WebSocketServer` remote control - could this provide the solution?

**Comment by macsunmood** [comment]
> There currently is no scripting API for workspaces (e.g. a hook that is executed when workspaces are switched) and note tabs (e.g. a command to load a bunch of notes as note tabs and closes the currently open notes).

It's such a pity, would be really great to have an API to control note tabs. Sessions (as a number of open tabs layout) should definitely exist as a feature for Notes app! :)

**Comment by pbek** [comment]
I don't even think QOwnNotes needs tabs. :) I'm much faster in finding what I want without them. In contrast when I write code in multiple tabs in some IDE I hardly ever work in more than one note in QON at the same time...

**Comment by macsunmood** [comment]
> I don't even think QOwnNotes needs tabs. :) I'm much faster in finding what I want without them. In contrast when I write code in multiple tabs in some IDE I hardly ever work in more than one note in QON at the same time...

Okay, so what's your workflow then for keeping the context with relevant notes? Tags and searching among them?

Say, I have several Windows virtual desktops, each with its own context, and I need to keep open notes related to them.
When switching between desktops, I'd have to manually open each note for every tag, which is totally unusable.
I also don't want to have many open instances of QOwnNotes spread over desktops, since: 1. every instance takes ram 2. accidently overwriting same note of different instances may cause file history issues;

What would be your take on such case ?

**Comment by pbek** [comment]
> Okay, so what's your workflow then for keeping the context with relevant notes? Tags and searching among them?

I usually just search for a relevant string. Most of the time I have it even in the name of the file. I just use the search. I hardly even use tags, and if just for coloring the notes in the list. If I need a reference to another note I just do a note link to that note on the top of the note. I most of the times add a back-link in those notes too.

If a *really* need to have a 2nd note open I open the the note in a different window read-only (right click on the note in the note list).
If I quickly need to navigate between points in notes I use "bookmarks" shortcuts (e.g. `Ctrl + Shift + 1`) and jump between passages that way.

I don't use different instances of QOwnNotes.

**Comment by macsunmood** [comment]
> > Okay, so what's your workflow then for keeping the context with relevant notes? Tags and searching among them?
> 
> I usually just search for a relevant string. Most of the time I have it even in the name of the file. I just use the search. I hardly even use tags, and if just for coloring the notes in the list. If I need a reference to another note I just do a note link to that note on the top of the note. I most of the times add a back-link in those notes too.
> 
> If a _really_ need to have a 2nd note open I open the the note in a different window read-only (right click on the note in the note list). If I quickly need to navigate between points in notes I use "bookmarks" shortcuts (e.g. `Ctrl + Shift + 1`) and jump between passages that way.
> 
> I don't use different instances of QOwnNotes.

Ok, I see what your workflow is, but did you get what my Windows Virtual Desktops was all about? They preserve contexts, the very sense and meaning behind having Session Layouts is for having the needed workspace for certain context. You don't always remember what you need for some task/project/context to search for it in notes -- what you need instead is already open different notes whith all the hints and appropriate infomation, as well as some stash/jottings container for the specific desktop.
I hope I've clarified what I meant, so you can see that simple search doesn't work for these needs.

Btw, wanted to thank you for your really great app, which for me stands off among many anothers! 😄  that's the reason I'm being so persistent and and scrupulous about the features -- I thought I've finally found the perfect tool, but it still doesn't cover all the crucial usecases.

**Comment by pbek** [comment]
> Ok, I see what your workflow is, but did you get what my Windows Virtual Desktops point was all about?

I know. I value your input. QOwnNotes wasn't ever relay meant to work with multiple documents at the same time, like an IDE. 😁

**Comment by macsunmood** [comment]
> > Ok, I see what your workflow is, but did you get what my Windows Virtual Desktops point was all about?
> 
> I know. I value your input. QOwnNotes wasn't ever relay meant to work with multiple documents at the same time, like an IDE. 😁

Well, what about just adding some hooks for switching command for adding/opening/closing notes? Then I'll make a scripting solution which solves this case and will share it for others with similar needs. :)

**Comment by pbek** [comment]
## 22.8.0
- a new scripting hook `workspaceSwitchedHook` was added that is called when
  workflows are switched (for [#2565](https://github.com/pbek/QOwnNotes/issues/2565))
  - please take a look at the
    [workspaceSwitchedHook documentation](https://www.qownnotes.org/scripting/hooks.html#workspaceswitchedhook)
    for more information

**Comment by pbek** [comment]
At least you can start to play with something now... The rest is rather complex.
There now is a new release, could you please test it and report if it works for you?

**Comment by macsunmood** [comment]
> At least you can start to play with something now... The rest is rather complex. There now is a new release, could you please test it and report if it works for you?

Thank you very much! I was trying to check the hook, auto-updating the app won't work. It's makes download, restarts, but the version remains old, and the title "new version available" keeps showing at the bottom panel..
![image](https://user-images.githubusercontent.com/45285672/183753505-9ec21e32-8181-4f60-a36d-fa16c53cdd26.png)

**Comment by pbek** [comment]
> But first, could you also add a method to manually switch the workspace, please? I'd like to use it to control workspaces from outer source (virtualdesktopaccessor.dll wrapper), possibly via WebSocketServer...

You can already do that, see https://www.qownnotes.org/scripting/classes.html#properties-and-methods-4.
And you can create your own websocket server, example see https://github.com/pbek/QOwnNotes/blob/develop/docs/scripting/examples/websocket-server.qml.

**Comment by macsunmood** [comment]
I don't see any method to open a specific note in tab, which I can trigger..

**Comment by pbek** [comment]
There isn't yet.

**Comment by macsunmood** [comment]
Are you planning on adding some in the foreseeable future?

As for me, I'd rather have switchable sessions with presets of tabs layouts :)

**Comment by pbek** [comment]
> Are you planning on adding some in the foreseeable future?

Definitely maybe!

>  What's more complex - to make it a decent separate feature, or to add this functionality to workspaces?

Both take a lot of time.

> I don't see any method to open a specific note in tab, which I can trigger..

That in itself is maybe a couple of hours work. But you don't know if that's all you need.

**Comment by pbek** [comment]
## 22.8.2
- you can now also open a note in a new tab if not already open with the
  scripting method `script.setCurrentNote()` (for [#2565](https://github.com/pbek/QOwnNotes/issues/2565))
  - for more information please take a look at the
    [scripting documentation](https://www.qownnotes.org/scripting/methods-and-objects.html#jumping-to-a-note)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by macsunmood** [comment]
> There now is a new release, could you please test it and report if it works for you?

No available release is visible yet..

**Comment by pbek** [comment]
Canonical broke the snap deployment. I'm working since 6 commits or so on it.

**Comment by pbek** [comment]
Still broken, with no solution. I uploaded the (not yet released) release for you here: https://ufile.io/19ghv13k (Windows release)

**Comment by macsunmood** [comment]
> Still broken, with no solution. I uploaded the (not yet released) release for you here: https://ufile.io/19ghv13k (Windows release)

Thanks, seems to work well.
Now we need to implement getting list of tagged notes from another issue :)

**Comment by student4life** [comment]
Came up across this issue when catching up on QOwnNote updates.

I work on multiple projects and I had a similar requirement as the OP.

The way I tackled it was to create and add individual Note folders for each project. When I switch to the Note folder of the relevant project, the tabs from the previous use of that project get reopened.
