### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by ghost** [pbek/QOwnNotes#2567]
#### Issue

Add arm architecture build

#### Expected behaviour

Running on apple silicon without Rosetta2

#### Actual behaviour

Can not running on apple silicon without Rosetta2

#### Steps to reproduce

Normal install on macOS

#### Output from the debug section in the settings dialog

nothing

#### Relevant log output in the Log panel

nothing

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
As long there is no option to build this on GitHub we are out of luck.

**Comment by pbek** [comment]
I'll close this in favor of #2912.
