### ISSUE TITLE
ownCloud Connection Error from OSX 10.11

### ISSUE THREAD

**Issue by dirkdirk** [pbek/QOwnNotes#257]
Short version: 
**connectionErrorMessage**: `Error downloading http://tradingtools123.com/oc/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/ - server replied: Not Acceptable`

Looks like the 'index.php' shouldn't be in there.

Yes, qownnotesapi is installed as is versions and deleted files.

Any ideas?

----------------------------------------------------------------------

Long version: 

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed Jul 20 10:36:34 2016`  
**Version**: `16.07.10`  
**Build date**: `Jul 19 2016`  
**Build number**: `1916`  
**Platform**: `macosx`  
**Operating System**: `OS X El Capitan (10.11)`  
**Build architecture**: `x86_64`  
**Current architecture**: `x86_64`  
**Release**: `Travis CI`  
**Qt Version (build)**: `5.5.1`  
**Qt Version (runtime)**: `5.5.1`  
**Qt Debug**: `0`  
**Locale (system)**: `en_US`  
**Locale (interface)**: *empty*  
**Icon theme**: `breeze-qownnotes`  
**Notes in current note folder**: `0`  
**Enabled scripts**: `0`  

## Server Info

**serverUrl**: `http://tradingtools123.com/oc`  
**appIsValid**: `no`  
**connectionErrorMessage**: `Error downloading http://tradingtools123.com/oc/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/ - server replied: Not Acceptable`  

## Note folders

**currentNoteFolderId**: `0`  

## Settings

**Country**: `US`  
**InitialKeyRepeat**: `25`  
**KeyRepeat**: `2`  
**MainWindow/mainToolBar.iconSize**: `0`  
**MainWindow/noteTextEdit.code.font**: `Monaco,10,-1,5,50,0,0,0,0,0`  
**MainWindow/noteTextEdit.font**: `.SF NS Text,13,-1,5,50,0,0,0,0,0`  
**MainWindow/noteTextView.code.font**: `Monaco,10,-1,5,50,0,0,0,0,0`  
**MainWindow/noteTextView.font**: `,13,-1,5,50,0,0,0,0,0`  
**MainWindow/showRecentNoteFolderInMainArea**: `false`  
**PiwikClientId**: `<hidden>`  
**WebAutomaticSpellingCorrectionEnabled**: `true`  
**allowDifferentNoteFileName**: `false`  
**allowOnlyOneAppInstance**: `false`  
**appMetrics/disableAppHeartbeat**: `false`  
**appMetrics/disableTracking**: `false`  
**cryptoKey**: `<hidden>`  
**customNoteFileExtensionList**: *empty*  
**darkMode**: `false`  
**darkModeColors**: `false`  
**defaultNoteFileExtension**: `txt`  
**disableAutomaticUpdateDialog**: `false`  
**externalEditorPath**: *empty*  
**ignoreAllExternalModifications**: `false`  
**interfaceLanguage**: *empty*  
**markdownHighlightingInterval**: `200`  
**networking/ignoreSSLErrors**: `true`  
**networking/proxyType**: `0`  
**noteSaveIntervalTime**: `10`  
**notesPath**: `/Users/Dirk/ownCloud/Notes`  
**notifyAllExternalModifications**: `false`  
**ownCloud/password**: `<hidden>`  
**ownCloud/serverUrl**: `http://tradingtools123.com/oc`  
**ownCloud/todoCalendarBackend**: `0`  
**ownCloud/todoCalendarEnabledList**: *empty*  
**ownCloud/todoCalendarEnabledUrlList**: *empty*  
**ownCloud/todoCalendarUrlList**: *empty*  
**ownCloud/userName**: `dirk`

**Comment by pbek** [comment]
I've never seen such an error, is it possible that you create me a test-account on your server?

**Comment by dirkdirk** [comment]
I doubt it.  I installed on my hosted account (Host Gator (which I'll never use again)) via ownCloud's web installer.

**Comment by pbek** [comment]
I meant an ownCloud account.

**Comment by pbek** [comment]
There seems some problem with the capabilities page <http://tradingtools123.com/oc/ocs/v1.php/cloud/capabilities> or with the test page <http://tradingtools123.com/oc/ocs/v1.php>, they can't be loaded properly, I cannot tell why... I'm sorry.

**Comment by dirkdirk** [comment]
OK ... thanks for trying.  Hopefully I'm the only one with this issue.  I'll be installing future versions on non-shared-hosting accounts.  I bet that's part of the issue.

**Comment by pbek** [comment]
When I try to load the todo lists I get:

```
Reply from ownCloud calendar page: "<head><title>Not Acceptable!</title></head><body><h1>Not Acceptable!</h1><p>An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.</p></body></html>"
```

Mod_Security seems to block some requests...

**Comment by dirkdirk** [comment]
Haven't tried any mobile apps yet.

**Comment by richarson** [comment]
Maybe related to this?

https://httpoxy.org/
https://owncloud.org/blog/owncloud-9-0-4-8-2-7-8-1-9-8-0-14-released/

**Comment by dirkdirk** [comment]
Tried the Updater from within my ownCloud and it does nothing.

Played with manual upgrade and can't get anywhere due to shared hosting limitations.

I'm using the [ownNote](https://apps.owncloud.com/content/show.php/ownNote+-+Notes+Application?content=168512) app for now as it needs my immediate needs.

**Comment by pbek** [comment]
You don't need QOwnNotes connecting to your ownCloud server, since the syncing is done by your ownCloud sync client anyway. QOwnNotesAPI just provides extra functionality, like accessing the note versions and the trash.
