### ISSUE TITLE
[I] Can't connect to server on mac (only)

### ISSUE THREAD

**Issue by madox85** [pbek/QOwnNotes#2570]
#### Expected behaviour

Accessing Nextcloudserver if I am trying to authenticate.

#### Actual behaviour

Error Message. Nextcloud Login Process can not be started. (Nextcloud Anmeldevorgang v2 konnte nicht gestartet werden). I already tried also to generate an app password without no success. Please note that I already was able to authenticate with different linux systems on the same server. On Telegram channel I was pleased to open an bugreport. 
Note also, that I was able to access to the server, from the same macbook with the "Nextcloud notes client app" so it is possible in general.

#### Steps to reproduce

Try to authenticate on server from up to date macbook pro 2021.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
Report will not be created by refresh. sorry.
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `So. Aug. 7 13:36:31 2022`
**Version**: `22.7.6`
**Build date**: `Jul 20 2022`
**Build number**: `976`
**Platform**: `macosx`
**Operating System**: `macOS 12.5`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/Users/xwarman/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/xwarman/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1512x982`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `119`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://nc.mdobbeck.de`
**appIsValid**: `no`
**notesPathExists**: `unknown`
**connectionErrorMessage**: `Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten.`

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/Users/xwarman/Library/Application Support/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Standard`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/Users/xwarman/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/Users/xwarman/Nextcloud/Notes/notes.sqlite`

### Cloud connection `Standard`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://nc.mdobbeck.de`
**username**: `mdk`
**accountId**: *empty*

## Settings

**AKLastEmailListRequestDateKey** (QDateTime): `2022-08-06T22:35:18.810`
**AKLastIDMSEnvironment** (qlonglong): `0`
**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Country** (QString): `DE`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (qlonglong): `4`
**Editor/removeTrailingSpaces** (bool): `false`
**Editor/showLineNumbers** (bool): `false`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2022-08-07T13:25:19.363`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (qlonglong): `32`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Menlo,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `.AppleSystemUIFont,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Menlo,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `.AppleSystemUIFont,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.refreshDebounceTime** (qlonglong): `600`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**NoteFolder-1/NoteTabNameList** (QStringList): `Argumentationshilfen`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteHistory-1** (QVariantList): `<variant list with 1 item(s)>`
**NoteHistoryCurrentIndex-1** (qlonglong): `0`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (qlonglong): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**WebAutomaticSpellingCorrectionEnabled** (bool): `true`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `false`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (bool): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (qlonglong): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (qlonglong): `1`
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (bool): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**enableWebAppSupport** (bool): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (qlonglong): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (qlonglong): `1024`
**imageScaleDownMaximumWidth** (qlonglong): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (qlonglong): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (qlonglong): `18`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (qlonglong): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelAutoSelect** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (qlonglong): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (qlonglong): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (qlonglong): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (qlonglong): `0`
**notesPanelOrder** (qlonglong): `0`
**notesPanelSort** (qlonglong): `1`
**notesPath** (QString): `/Users/xwarman/Nextcloud/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (qlonglong): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (qlonglong): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): `Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten.`
**ownCloudInfo/notesPathExistsText** (QString): `unknown`
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (bool): `false`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**showMatches** (bool): `true`
**showMenuBar** (bool): `false`
**showStatusBar** (bool): `true`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (qlonglong): `0`
**tagsPanelSort** (qlonglong): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Hauptsymbolleiste`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `Formatierungs-Werkzeugleiste`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `Einfügen-Werkzeugleiste`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `Verschlüsselung-Werkzeugleiste`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `Fenster-Werkzeugleiste`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `Beenden - Symbolleiste`
**toolbar/size** (qlonglong): `6`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (qlonglong): `22222`
**workspace-initial/name** (QString): `Vollständig`
**workspace-initial/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**USER**: `xwarman`
**__CFBundleIdentifier**: `com.PBE.QOwnNotes`
**COMMAND_MODE**: `unix2003`
**LOGNAME**: `xwarman`
**PATH**: `/usr/bin:/bin:/usr/sbin:/sbin`
**SSH_AUTH_SOCK**: `/private/tmp/com.apple.launchd.ZHTnswuCab/Listeners`
**SHELL**: `/bin/bash`
**HOME**: `/Users/xwarman`
**__CF_USER_TEXT_ENCODING**: `0x1F5:0x0:0x3`
**TMPDIR**: `/var/folders/_p/v_m2l_ls3hl4zrx67yzq15s00000gn/T/`
**XPC_SERVICE_NAME**: `application.com.PBE.QOwnNotes.952203.952206`
**XPC_FLAGS**: `0x0`
**QT_LOGGING_RULES**: `qt.network.ssl.warning=false`
</details>

**Comment by pbek** [comment]
>  connectionErrorMessage: Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten.

Strange, I wonder how that happened... But your server https://nc.mdobbeck.de does seem to have a valid SSL cert. 

Is there any useful log output if you enable the log panel (see Window / Panels) and start to the "Anmeldevorgang V2" again? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting Debug in Options).

**Comment by madox85** [comment]
HI, Thanks for your answer. I attached the log file and enabled the settings, you mentioned.

**Comment by pbek** [comment]
> HI, Thanks for your answer. I attached the log file and enabled the settings, you mentioned.

Where did you attach it?

**Comment by madox85** [comment]
To the Mail I had sent to the system

07.08.2022 18:28:01 Patrizio Bekerle ***@***.***>:

**Comment by pbek** [comment]
I don't think that works on GitHub.

**Comment by madox85** [comment]
Ok, sorry. Then I will upload it again here. 

Output from Logfile:

[Aug 07 17:09:31] [debug]: Set proxy configuration to use NO proxy
[Aug 07 17:09:33] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://nc.mdobbeck.de" <username>"mdk" <accountId>"" <priority>1
[Aug 07 17:09:33] [debug]: loadNoteDirectoryList
[Aug 07 17:09:33] [debug]: reloadTagTree
[Aug 07 17:09:33] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(0)
[Aug 07 17:09:33] [debug]: reloadNoteSubFolderTree
[Aug 07 17:09:33] [debug]: reload
[Aug 07 17:09:33] [debug]: loadNoteDirectoryList
[Aug 07 17:09:33] [debug]: reloadTagTree
[Aug 07 17:09:33] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(0)
[Aug 07 17:09:33] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://nc.mdobbeck.de" <username>"mdk" <accountId>"" <priority>1
[Aug 07 17:09:38] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://nc.mdobbeck.de" <username>"mdk" <accountId>"" <priority>1
[Aug 07 17:09:38] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://nc.mdobbeck.de" <username>"mdk" <accountId>"" <priority>1
[Aug 07 17:09:38] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://nc.mdobbeck.de" <username>"mdk" <accountId>"" <priority>1
[Aug 07 17:09:38] [debug]: Reply from  ""
[Aug 07 17:09:38] [warning]: "QNetworkReply error 6 from url https://nc.mdobbeck.de: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[Aug 07 17:09:38] [debug]: Reply from main server url
[Aug 07 17:09:38] [debug]: Reply from  "/ocs/v1.php/cloud/capabilities"
[Aug 07 17:09:38] [warning]: "QNetworkReply error 6 from url https://nc.mdobbeck.de/ocs/v1.php/cloud/capabilities: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[Aug 07 17:09:38] [debug]: Reply from capabilities page
[Aug 07 17:09:38] [debug]: Reply from  "/ocs/v1.php"
[Aug 07 17:09:38] [warning]: "QNetworkReply error 6 from url https://nc.mdobbeck.de/ocs/v1.php: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[Aug 07 17:09:38] [debug]: Reply from ownCloud test page
[Aug 07 17:09:38] [debug]: Reply from  "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[Aug 07 17:09:38] [warning]: "QNetworkReply error 6 from url https://nc.mdobbeck.de/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/Notes/: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[Aug 07 17:09:38] [debug]: Reply from app info
[Aug 07 17:09:38] [debug]: Reply from  "/remote.php/dav/calendars/mdk"
[Aug 07 17:09:38] [warning]: "QNetworkReply error 6 from url https://nc.mdobbeck.de/remote.php/dav/calendars/mdk: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[Aug 07 17:09:38] [debug]: Reply from ownCloud calendar page ""
[Aug 07 17:09:38] [debug]: Reply from  "/remote.php/dav/calendars/mdk"
[Aug 07 17:09:38] [warning]: "QNetworkReply error 6 from url https://nc.mdobbeck.de/remote.php/dav/calendars/mdk: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[Aug 07 17:09:38] [debug]: Reply from ownCloud calendar page ""
[Aug 07 17:09:43] [debug]: Set proxy configuration to use NO proxy
[Aug 07 17:09:44] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://nc.mdobbeck.de" <username>"mdk" <accountId>"" <priority>1
[Aug 07 17:09:44] [debug]: Reply from  ""
[Aug 07 17:09:44] [warning]: "QNetworkReply error 6 from url https://nc.mdobbeck.de: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[Aug 07 17:09:44] [debug]: Reply from main server url
[Aug 07 17:09:44] [debug]: Reply from  "/ocs/v1.php/cloud/capabilities"
[Aug 07 17:09:44] [warning]: "QNetworkReply error 6 from url https://nc.mdobbeck.de/ocs/v1.php/cloud/capabilities: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[Aug 07 17:09:44] [debug]: Reply from capabilities page
[Aug 07 17:09:44] [debug]: Reply from  "/ocs/v1.php"
[Aug 07 17:09:44] [warning]: "QNetworkReply error 6 from url https://nc.mdobbeck.de/ocs/v1.php: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[Aug 07 17:09:44] [debug]: Reply from ownCloud test page
[Aug 07 17:09:44] [debug]: Reply from  "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[Aug 07 17:09:44] [warning]: "QNetworkReply error 6 from url https://nc.mdobbeck.de/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/Notes/: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[Aug 07 17:09:44] [debug]: Reply from app info
[Aug 07 17:11:37] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://nc.mdobbeck.de" <username>"mdk" <accountId>"" <priority>1
[Aug 07 17:11:37] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://nc.mdobbeck.de" <username>"mdk" <accountId>"" <priority>1
[Aug 07 17:11:37] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://nc.mdobbeck.de" <username>"mdk" <accountId>"" <priority>1
[Aug 07 17:11:37] [debug]: Reply from  ""
[Aug 07 17:11:37] [warning]: "QNetworkReply error 6 from url https://nc.mdobbeck.de: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[Aug 07 17:11:37] [debug]: Reply from main server url
[Aug 07 17:11:37] [debug]: Reply from  "/ocs/v1.php/cloud/capabilities"
[Aug 07 17:11:37] [warning]: "QNetworkReply error 6 from url https://nc.mdobbeck.de/ocs/v1.php/cloud/capabilities: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[Aug 07 17:11:37] [debug]: Reply from capabilities page
[Aug 07 17:11:37] [debug]: Reply from  "/ocs/v1.php"
[Aug 07 17:11:37] [warning]: "QNetworkReply error 6 from url https://nc.mdobbeck.de/ocs/v1.php: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[Aug 07 17:11:37] [debug]: Reply from ownCloud test page
[Aug 07 17:11:37] [debug]: Reply from  "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[Aug 07 17:11:37] [warning]: "QNetworkReply error 6 from url https://nc.mdobbeck.de/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/Notes/: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[Aug 07 17:11:37] [debug]: Reply from app info
[Aug 07 17:11:37] [debug]: Reply from  "/remote.php/dav/calendars/mdk"
[Aug 07 17:11:37] [warning]: "QNetworkReply error 6 from url https://nc.mdobbeck.de/remote.php/dav/calendars/mdk: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[Aug 07 17:11:37] [debug]: Reply from ownCloud calendar page ""
[Aug 07 17:11:38] [debug]: Reply from  "/remote.php/dav/calendars/mdk"
[Aug 07 17:11:38] [warning]: "QNetworkReply error 6 from url https://nc.mdobbeck.de/remote.php/dav/calendars/mdk: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[Aug 07 17:11:38] [debug]: Reply from ownCloud calendar page ""
[Aug 07 18:09:46] [warning]: onResult  - 'network reply error':  QNetworkReply::HostNotFoundError
[Aug 07 19:13:13] [warning]: onResult  - 'network reply error':  QNetworkReply::HostNotFoundError
[Aug 07 20:40:36] [warning]: onResult  - 'network reply error':  QNetworkReply::HostNotFoundError
[Aug 07 21:48:19] [warning]: onResult  - 'network reply error':  QNetworkReply::HostNotFoundError
[Aug 08 08:20:39] [warning]: onResult  - 'network reply error':  QNetworkReply::HostNotFoundError
[Aug 08 09:26:11] [warning]: onResult  - 'network reply error':  QNetworkReply::HostNotFoundError
[Aug 08 10:28:31] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://nc.mdobbeck.de" <username>"mdk" <accountId>"" <priority>1
[Aug 08 10:28:38] [warning]: onResult  - 'network reply error':  QNetworkReply::HostNotFoundError
[Aug 08 10:29:40] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://nc.mdobbeck.de" <username>"mdk" <accountId>"" <priority>1
[Aug 08 11:45:57] [warning]: onResult  - 'network reply error':  QNetworkReply::HostNotFoundError



Output from Debug Assistent:

[17:09:09] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[17:09:09] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/ocs/v1.php/cloud/capabilities: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[17:09:09] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/ocs/v1.php: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[17:09:09] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/Notes/: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[17:09:09] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/remote.php/dav/calendars/mdk: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[17:09:09] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/remote.php/dav/calendars/mdk: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[17:09:38] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[17:09:38] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/ocs/v1.php/cloud/capabilities: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[17:09:38] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/ocs/v1.php: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[17:09:38] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/Notes/: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[17:09:38] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/remote.php/dav/calendars/mdk: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[17:09:38] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/remote.php/dav/calendars/mdk: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[17:09:44] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[17:09:44] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/ocs/v1.php/cloud/capabilities: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[17:09:44] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/ocs/v1.php: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[17:09:44] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/Notes/: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[17:11:37] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[17:11:37] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/ocs/v1.php/cloud/capabilities: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[17:11:37] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/ocs/v1.php: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[17:11:37] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/Notes/: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[17:11:37] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/remote.php/dav/calendars/mdk: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[17:11:38] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/remote.php/dav/calendars/mdk: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[18:09:46] [warning] onResult - 'network reply error': QNetworkReply::HostNotFoundError
[19:13:13] [warning] onResult - 'network reply error': QNetworkReply::HostNotFoundError
[20:40:36] [warning] onResult - 'network reply error': QNetworkReply::HostNotFoundError
[21:48:19] [warning] onResult - 'network reply error': QNetworkReply::HostNotFoundError
[08:20:39] [warning] onResult - 'network reply error': QNetworkReply::HostNotFoundError
[09:26:11] [warning] onResult - 'network reply error': QNetworkReply::HostNotFoundError
[10:28:38] [warning] onResult - 'network reply error': QNetworkReply::HostNotFoundError
[11:45:57] [warning] onResult - 'network reply error': QNetworkReply::HostNotFoundError
[11:50:35] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[11:50:35] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/ocs/v1.php/cloud/capabilities: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[11:50:35] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/ocs/v1.php: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[11:50:35] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/Notes/: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[11:50:36] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/remote.php/dav/calendars/mdk: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[11:50:36] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/remote.php/dav/calendars/mdk: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[11:50:41] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[11:50:41] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/ocs/v1.php/cloud/capabilities: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[11:50:41] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/ocs/v1.php: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
[11:50:41] [warning] "QNetworkReply error 6 from url https://nc.mdobbeck.de/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/Notes/: " "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."

**Comment by pbek** [comment]
There are lots of SSL Errors, but I had no issues starting the login process with your server https://nc.mdobbeck.de/. Very strange.

**Comment by pbek** [comment]
But I had the same issue with https://nc.mdobbeck.de on macOS. No issues on macOS with my own servers...
You seem to use Let's encrypt! I've one server with Let's encrypt and one with Cloudflare. Both are working fine... I don't know what is different with your server... Maybe some SSL setting on your server...

**Comment by pbek** [comment]
QOwnNotes is supposed to use the SSL libraries from macOS...

**Comment by pbek** [comment]
https://scan.nextcloud.com/results/d45894e4-3807-413c-b25b-c32bc47875a9 is looking good too...
