### ISSUE TITLE
Right click on not opened note falsely opens it

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2577]
#### Expected behaviour
In the notes list, if right click on some note, which is not currently opened, it should only show the context menu.

#### Actual behaviour
It opens the note in a new tab, as if left-clicked.

**Comment by pbek** [comment]
> It opens the note in a new tab, as if left-clicked.

A left click doesn't open a note in a new tab. A double-click does. A right-click neither opens a note in a new tab for me.

Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.

Can you please describe step by step what you did?

**Comment by macsunmood** [comment]
I was be not quite precise with my description: a single click opens a note in the **current** tab, not a new one. Both left- and right-click do that. Which I guess is not the intended behaviour, especially for the right click, which I think should only invoke the note context menu..

Is debug log still needed after the clarification?

**Comment by pbek** [comment]
> Both left- and right-click do that. 

Yes, that's what a QTreeWidget does.

> I think should only invoke the note context menu..

The right click will always move to that QTreeWidgetItem and then the context menu will be opened.

**Comment by macsunmood** [comment]
> > Both left- and right-click do that.
> 
> Yes, that's what a QTreeWidget does.
> 
> > I think should only invoke the note context menu..
> 
> The right click will always move to that QTreeWidgetItem and then the context menu will be opened.

But that changes the currently open note in tab to another. And the user just wanted a context menu for some note..
Should that be considered an expected behaviour?

**Comment by pbek** [comment]
> But that changes the currently open note in tab to another.

Yes, it does. But that's how a QTreeWidget is behaving. I guess one could find a way around it if one really would try and also rewrites the behavior of QOwnNotes (selected item == current note) which depends on the current behavior.
But going on the journey to implement that would be a lot of work and cause a lot of regressions.

**Comment by macsunmood** [comment]
I think it should be added to the feature improvements/fixes list anyway..

**Comment by pbek** [comment]
Only if you want to work on it. And I will not fix the regressions this change would cause. 😁

**Comment by Clozent** [comment]
I think it's worth it to keep this issue open, so that someone capable may one day fix it.
By the way, I wouldn't mind giving up some features for this, and I'm sure that I'm not the only one, so maybe make this an option in the settings?

**Comment by pbek** [comment]
It wouldn't be really a fix, it would be an added optional feature with a lot of regressions. And I'm not a big fan of those. 😅

**Comment by macsunmood** [comment]
> It wouldn't be really a fix, it would be an added optional feature with a lot of regressions. And I'm not a big fan of those. 😅

Hi! Do you think LLMs could help with the regressions problem and improve the refactoring process now?

**Comment by pbek** [comment]
I guess, if there is an llm that can understand a whole project.

**Comment by macsunmood** [comment]
> I guess, if there is an llm that can understand a whole project.

Maybe something like Code LLaMA 70b?

**Comment by pbek** [comment]
Just try it out and tell me how it went. 🤷🏻

**Comment by macsunmood** [comment]
> Maybe just try it out and tell me how it went. 🤷🏻

I would if I was skilled enough in C++ 😁
