### ISSUE TITLE
Bulk open notes with certain tag as note tabs

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2578]
#### Expected behaviour
This could be a right-click context menu option of a tag, or/and some method for custom action.

**Comment by pbek** [comment]
You are talking about "Open all notes with a certain tag as new note tabs", right?

**Comment by macsunmood** [comment]
Yes, as tabs.

**Comment by pbek** [comment]
I guess it would be better then to just open all selected notes in the note list a tabs, that would be more versatile and serve the same outcome.

**Comment by macsunmood** [comment]
Yes, for mouse interface. But for some custom triggerable action it's better to have an actual method (could have a max_tabs limiting parameter).

**Comment by pbek** [comment]
Overkill 😀

**Comment by pbek** [comment]
## 22.8.1
- you now can open all selected notes as new tabs via the note list context menu
  or the note operations button (for [#2578](https://github.com/pbek/QOwnNotes/issues/2578))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by macsunmood** [comment]
Seems to be working well, but "Open selected notes in tab" should rather be "Open selected notes in **new tabs**".
Possibly add this also for tags right-click ("Open all notes with this tag in new tabs")?

And what about custom actions? That's what's needed for sessions desktop layouts functionality (along with closing non-sticked tabs).

**Comment by pbek** [comment]
Thank you for the plural, I fixed that! But I didn't write `new` on purpose, because that's not what's happening when those notes are already opened as tabs.

> And what about custom actions? That's what's needed for sessions desktop layouts functionality (along with closing non-sticked tabs).

That's not part of this feature request.
