### ISSUE TITLE
Possible UI improvements for notes/tags lists

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2579]
#### Expected behaviour

- Add showing tags note belongs to for tooltip in the notes list. Even better - to have tooltip customizable from settings.
- Instead of "Show all notes tagged with <..>" (duplicate info already present in the list itself) show list of the first 10-20 tagged note names in tooltip of tags list, possibly sorted by added date.

**Comment by pbek** [comment]
> Add showing tags note belongs to for tooltip in the notes list. Even better - to have tooltip customizable from settings.

I fear it would take a performance toll to "gather" that information for >10k notes every time the note list is regenerated.
At least tags are rendered **strong** in the tag tree when they belong to the current note.

> Instead of "Show all notes tagged with <..>" (duplicate info already present in the list itself) show list of the first 10-20 tagged note names in tooltip of tags list, possibly sorted by added date.

Can you please add a screenshot of what we are talking about.

**Comment by macsunmood** [comment]
> Can you please add a screenshot of what we are talking about.

![image](https://user-images.githubusercontent.com/45285672/184124148-88d70ab1-987f-4477-97c1-79385ee36bc4.png)

**Comment by pbek** [comment]
Thank you.

> instead of "Show all notes tagged with <..>" (duplicate info already present in the list itself) 

Why do you you think "Show all notes tagged with <..>" is duplicate information?

> show list of the first 10-20 tagged note names in tooltip of tags list, possibly sorted by added date.

Hm, I don't see the reason this information would be so valuable, especially if the note names are very long... The tool-tip would be pretty cluttered.

**Comment by macsunmood** [comment]
> Why do you you think "Show all notes tagged with <..>" is duplicate information?
I consider it duplicate because I already see a list of tags (it could be better identifiable, but I guess the searchbox is enough), and number of notes belonging to each of them. To better word it, it's not literally duplicate, but rather redundant information for me.



> Hm, I don't see the reason this information would be so valuable, especially if the note names are very long... The tool-tip would be pretty cluttered.
