### ISSUE TITLE
Add a method to fetch a list of all notes, belonging to some tag or list of tags

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2582]
It can be implemented via scripting, but a guess it would cost some speed making it in qml js..
The function itself is implied as to be potentially frequently used.

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
## 22.8.3
- you now can fetch all notes that are linked to a tag with new scripting property
  `notes` of `TagApi` objects (for [#2582](https://github.com/pbek/QOwnNotes/issues/2582))
  - for more information please take a look at the
    [scripting documentation](https://www.qownnotes.org/scripting/classes.html#tag)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
(needs a while till it's built and the documentation is up-to-date)

**Comment by macsunmood** [comment]
> There now is a new release, could you please test it and report if it works for you?

Thank you, I've tested it. Seems to work pretty well.
Now I can bulk open multiple notes with certain tag at once! :)

**Comment by pbek** [comment]
Awesome 😊👍🏻
