### ISSUE TITLE
Organize methods by toggleable topic in the website docs "Scripting" section

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2583]
#### Expected behaviour
at:
https://www.qownnotes.org/scripting

there seem to be too much extisting methods already, quite hard to explore.. Needs more structure?
![image](https://user-images.githubusercontent.com/45285672/185391165-8ffc6850-9cda-4081-abd7-4b81e1e72489.png)

**Comment by pbek** [comment]
Good idea. Ideas as pull request are welcome.
