### ISSUE TITLE
Add "Jump to a note tag" method

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2584]
#### Expected behaviour
..so it will let to focus a certain tag in the Tags List.

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by macsunmood** [comment]
This could be the next step to implement better support for tab sessions..

**Comment by macsunmood** [comment]
> How do you want to use that in tab sessions and can you please explain this feature request in more detail?

Tab Sessions currently rely on assigning a sesssion to tags with specific pattern of naming. When switched via custom action, it should also focus the tag panel accordingly (e.g. if '[[1]]' session is opened, the '[[1]]' tag should become focused).

**Comment by pbek** [comment]
## 22.9.1
- there now is a new scripting command `mainWindow.jumpToTag(tagId)` to
  jump to a tag in the tag tree (for [#2584](https://github.com/pbek/QOwnNotes/issues/2584))
  - for more information please take a look at the
    [MainWindow scripting documentation](https://www.qownnotes.org/scripting/classes.html#mainwindow)

**Comment by macsunmood** [comment]
Great, it works well!

**Comment by pbek** [comment]
Great, thank you for testing!
