### ISSUE TITLE
Show note ID/Unique ID in the notes list hover tooltip or as an option in the right-click context menu

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2585]
#### Expected behaviour
Note ID/unique ID might be an often required entity for various scripting manipulations..

**Comment by pbek** [comment]
You could do that in a script. Nobody else needs to see the node id.

**Comment by macsunmood** [comment]
I agree, I forgot you can add context menu and message pop-up with scripting.. :D
Suggestion withdrawal.

**Comment by pbek** [comment]
Don't depend on note ids! They are ephemeral and will be re-assigned every time the note folder is reloaded!

**Comment by macsunmood** [comment]
> Don't depend on note ids! They are ephemeral and will be re-assigned every time the note folder is reloaded!

Does this apply to Unique IDs as well?

**Comment by pbek** [comment]
Which ones?

**Comment by macsunmood** [comment]
I think I may have confused what's shown in this example:
https://github.com/pbek/QOwnNotes/blob/develop/docs/scripting/examples/unique-note-id.qml

so, no unique ids exist as an app feature

**Comment by pbek** [comment]
> so, no unique ids exist as an app feature

correct, the single source of truth are the note files and their sub-folders, there is no database of notes

**Comment by macsunmood** [comment]
> correct, the single source of truth are the note files and their sub-folders, there is no database of notes

then, aren't tags the database related to notes?

**Comment by pbek** [comment]
> then, aren't tags the database related to notes?

I'm not sure I understand your question. Tags are stored in a sqlite database, yes. Alternatively you can use the script api to persist them anywhere you like.
