### ISSUE TITLE
Add `qon://` custom protocol (URI Scheme)

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2586]
#### Expected behaviour
..so we can open notes and trigger custiom actions by URI link from anywhere outside the app.

**Comment by pbek** [comment]
Why would that be needed and how should that be achieved on all platforms?

**Comment by macsunmood** [comment]
You can register protocols on windows and linux, not sure about apple (I think it's surely possible).
It's needed, first of all, to reference notes/tags from anywhere. For instance, you have a link in Notion/Obsidian/etc., which you click and it opens/focuses QOwnNotes with the desired note/tag.

**Comment by macsunmood** [comment]
Here are some notes on the protocol registering subject: https://developer.shotgridsoftware.com/af0c94ce/

**Comment by macsunmood** [comment]
Here are some notes on how Obsidian implements the URI scheme/protocol: https://help.obsidian.md/Advanced+topics/Using+obsidian+URI

**Comment by pbek** [comment]
> Here are some notes on how Obsidian implements the URI scheme/protocol: https://help.obsidian.md/Advanced+topics/Using+obsidian+URI

But still Obsidian is a browser based app (Electron).

> which you click and it opens/focuses QOwnNotes with the desired note/tag.

Both notes and note folders are ephemeral, of what use are links to them?

**Comment by macsunmood** [comment]
> But still Obsidian is a browser based app (Electron).
protocol handlers can be registered for any type of app (if that's what you meant).
It even has nice intergration with Qt:
![image](https://user-images.githubusercontent.com/45285672/185609296-d0bff453-2ae0-436b-9649-bad430a79956.png)

> Both notes and note folders are ephemeral, 
So are many digital items, such as note files, websites, etc.. or I don't get what you mean..
> of what use are links to them?
so to be able to easily integrate any info to outer knowledge bases/resources. It's better to have an option to link something, even if the link would sometimes come off as broken (as with websites, right?), than no to, in my opinion.

**Comment by pbek** [comment]
Inside QOwnNotes the application tries to refactor links to notes, media files and attachments when notes are for example moved or renamed. This will not happen outside the application. I don't see the point of an external link to a note that is not persistent. HTTP URLs are supposed to work in the future too (or at least redirect to another URL). If QOwnNotes would use a central database with unique IDs for notes such URLs would make more sense.

**Comment by macsunmood** [comment]
> If QOwnNotes would use a central database with unique IDs for notes such URLs would make more sense.

And are you planning on making such functionality?

**Comment by pbek** [comment]
> And are you planning on making such functionality?

No, that's no "functionality", it's a re-concepting of the app and makes no sense for QOwnNotes :) Everything is based on simple files and not a database.
