### ISSUE TITLE
Add 'close note' method

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2592]
#### Expected behaviour

- a `closeNote` method should close tab with a given Note.

Along with 'Fetch a list of all notes with tag(s)' (https://github.com/pbek/QOwnNotes/issues/2582),  "Jump to a note tag" (https://github.com/pbek/QOwnNotes/issues/2584), as well as already existing 'Set current note' features, this would allow making full Tabs Sessions support.

**Comment by pbek** [comment]
What use would such a function have?

**Comment by macsunmood** [comment]
> What use would such a function have? 

It will allow to switch different sets of tabs layouts (Workspaces or Sessions)

**Comment by pbek** [comment]
How would you know which tabs are open?

**Comment by macsunmood** [comment]
> How would you know which tabs are open?

Maybe keep a list of current open notes, or a corresponding attribute should be added to the NoteApi?

**Comment by pbek** [comment]
All those take a long time to implement (for one single user 😉). But feel feel to open a feature request...

**Comment by macsunmood** [comment]
What else needed to open a feature request besides this existing issue?

**Comment by macsunmood** [comment]
So, can this issue be labeled as a feature request, or another one should be created ?

**Comment by pbek** [comment]
Yes

**Comment by pbek** [comment]
It's a bit tricky. There will more like an API to close a note tab at a specific index (0 ... n).

**Comment by pbek** [comment]
## 22.8.4
- there now is a new scripting command `mainWindow.removeNoteTab(index)` to
  close a note tab on a specific index (for [#2592](https://github.com/pbek/QOwnNotes/issues/2592))
  - for more information please take a look at the
    [MainWindow scripting documentation](https://www.qownnotes.org/scripting/classes.html#mainwindow)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by macsunmood** [comment]
Thank you! It works pretty well, but now I need a way to retrieve a list of all open tabs containing their notes.
Maybe some `Q_PROPERTY` for `MainWindow` as by analogy `Q_PROPERTY(QQmlListProperty<NoteApi> notes)` exists for `TagApi`?

**Comment by pbek** [comment]
You could create a feature request, but with the APIs I created over the last weeks for you are already able to close all open tabs and load a new set of tabs when the workspace is changed. So I'm eagerly awaiting a first version of a script as pull request on https://github.com/qownnotes/scripts 😉
