### ISSUE TITLE
Release v22.8.2 got reported a ?false? positive with Win32/Beareuws.A!ml by windows defender

### ISSUE THREAD

**Issue by devz3r0** [pbek/QOwnNotes#2593]
#### Expected behaviour
Update and working
#### Actual behaviour
Windows defender deletes the .exe with the message that Win32/Beareuws.A!ml was found.
#### Steps to reproduce
update Qoownnotes
#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>
 	Name: Program:Win32/Beareuws.A!ml
 	ID: 256596
 	Schweregrad: Hoch
 	Kategorie: Einstellungsveränderer
 	Pfad: file:_E:\DL\QOwnnotes\QOwnNotes\QOwnNotes.exe
 	Erkennungsursprung: Lokaler Computer
 	Erkennungstype: FastPath
 	Erkennungsquelle: Echtzeitschutz
 	Benutzer: DEVZERO\devzero
 	Prozessname: C:\Users\devzero\AppData\Local\Temp\QOwnNotes-rzPboh-unzip.exe
 	Sicherheitsversion: AV: 1.373.645.0, AS: 1.373.645.0, NIS: 1.373.645.0
 	Modulversion: AM: 1.1.19500.2, NIS: 1.1.19500.2
</details>

To get it working again downgrade to 22.8.1

**Comment by pbek** [comment]
Happens from time to time that signatures are detected wrongly. We can only wait. Builds are done on GitHub directly.

**Comment by devz3r0** [comment]
And what triggers that? The Nextcloud module?

**Comment by pbek** [comment]
I'm closing this since that release is long obsolete...
