### ISSUE TITLE
Add a method to retrieve a list of all open tabs

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2597]
#### Expected behaviour

Create a method to retrieve a list of all open tabs, with contained notes.
There should be a way to keep some sticked (or whitelisted) notes unclosed, as some notes might be shared between different workspaces and should remain untouched when switching.

Maybe some `Q_PROPERTY` for `MainWindow` as by analogy `Q_PROPERTY(QQmlListProperty<NoteApi> notes)` exists for `TagApi`?

**Comment by pbek** [comment]
Thank you for your suggestion. I'm not sure yet if that even could be accomplished in one single API command.

**Comment by macsunmood** [comment]
What about tags indexlist as for beginning? Since one already exists somewhere in the source.

**Comment by macsunmood** [comment]
> > Since one already exists somewhere in the source.
> 
> Which do you mean?

The one used for `mainWindow.removeNoteTab()`

**Comment by pbek** [comment]
There is no list in that method. A tab will be removed directly.

**Comment by pbek** [comment]
No...

https://github.com/pbek/QOwnNotes/blob/cabe4304cb978ed1a08babcaac93b3baa66aab67/src/mainwindow.cpp#L11924

**Comment by pbek** [comment]
I'll wait for your qml script alpha version before I attempt to implement this by hand.

**Comment by macsunmood** [comment]
> I'll wait for your qml script alpha version before I attempt to implement this by hand. Currently you are the only person that wants all those APIs and they are a lot of work to implement, write documentation, translate documentation in many languages, ...

Here's an alpha pr: https://github.com/qownnotes/scripts/pull/172

**Comment by pbek** [comment]
Thank you

**Comment by pbek** [comment]
I made my comments...

**Comment by macsunmood** [comment]
So, currently the closing of all Tabs consequently only works with time interval, otherwise it leads to crash.
Can you please investigate whether anything can be done about it?

**Comment by pbek** [comment]
Can you please prepare a script along with a test note folder that crashes the application?

**Comment by macsunmood** [comment]
@pbek there was a small inaccuracy from my side: this issue is related to **opening** the Tabs consequently, **not closing**. And it currently leads to **nothing happening**. So, you can't consequently open many tabs at once, only with a time interval.
Obviously, bulk opening of tabs is an obligatory feature.

Anyways, here's a script code, that implements consequent opening of many tabs, as it should be if everything worked.
It also contains the old timer-leveraging part, which is commented, and it's followed by the new part.
You can test it with any existing Tab Sessions tag containing more than 1 note.
It's not that big, so I'll embed it right here:

```
import QtQml 2.0
import QOwnNotesTypes 1.0


Script {
    function init() {
        // Search for all tags titled according to Tab Sessions naming rule
        // and register related custom actions for each of them
        let searched_tags = script.searchTagsByName("[[");
        for (let i = 0; i < searched_tags.length; i++) {
            let tag_name = searched_tags[i]
            if (tag_name.startsWith('[[') && tag_name.endsWith(']]')) {
                // fetch the first tag object with an appropriate name
                let tag_obj = script.getTagByNameBreadcrumbList([tag_name], false);
                // create related custom action with button
                let session_name = tag_name.replace('[[', '').replace(']]', '');
                script.registerCustomAction(`switchToTabSession_${session_name}`, `Switch to Tab Session: ${session_name}`, tag_name);
            }
        }

        script.registerCustomAction("closeAllNoteTabs", "Close all note tabs", "Close All Tabs");
    }

    function customActionInvoked(identifier) {
        if (identifier.startsWith("switchToTabSession")) {
            let desktop_tag = `[[${identifier.replace('switchToTabSession_', '')}]]`;
            
            // Retrieve the tag object related to the Tab Session
            let tag_obj = script.getTagByNameBreadcrumbList([desktop_tag], false);
            let tag_notes = tag_obj.notes

            if (tag_notes.length === 0) {
                script.log(`No notes for tag ${desktop_tag} !`);
                return
            }
            
            // Close all currently opened note tabs
            while (mainWindow.removeNoteTab(0)) { }

            // Then, open all the tag-related notes <---(OLD IMPLEMENTATION)
            // let i = 0;
            // let callBack = () => {
            //     // script.log(`Opening note ${i}: ${tag_notes[i]}`);
            //     script.setCurrentNote(tag_notes[i], true);
            //     if (i === 0) {
            //         mainWindow.removeNoteTab(0)  // needs to be done because of weird behaviour!
            //     }
            // }
            // let stopConditionFunc = () => {
            //     i++;
            //     return (i === tag_notes.length)
            // }
            // timer.triggerUntil(1, callBack, stopConditionFunc)


            // Then, open all the tag-related notes <---(NEW: NO TIME INTERVAL)
            for (let i = 0; i === tag_notes.length; i++) {
                script.setCurrentNote(tag_notes[i], true);
                if (i === 0) {
                    mainWindow.removeNoteTab(0)  // needs to be done because of weird behaviour!
                }
            }

             // Focus related tag in the tag list
            mainWindow.jumpToTag(tag_obj.id)
        }
            
        else if (identifier === "closeAllNoteTabs") {
            // Close all opened note tabs
            while (mainWindow.removeNoteTab(0)) { };
        }
    }

    property QtObject timer: Timer {
        function triggerUntil(delayTime, callBack, stopConditionFunc, finalCallBack) {
            timer.triggered.connect(callBack);
            timer.triggered.connect(function release() {
                if (stopConditionFunc()) {
                    timer.stop();
                    timer.triggered.disconnect(callBack);
                    timer.triggered.disconnect(release);
                    if (finalCallBack) { finalCallBack() }
                }
            });
            
            timer.repeat = true
            timer.interval = delayTime;
            timer.start();
        }
    }
}
```

**Comment by macsunmood** [comment]
> > for (let i = 0; i === tag_notes.length; i++)
> 
> This loop doesn't lead to anything, you need to write `for (let i = 0; i < tag_notes.length; i++)`, then it opens all tabs for me.

It really does work now. Somehow i overlook it, sorry.

The speed is better this way, but it's still not instant and does it switching the App window title consequently.
Is it possible to make bulk opening of multiple tabs at once, as a method, rather than performing loop opening in script?

**Comment by pbek** [comment]
>  mainWindow.removeNoteTab(0) // needs to be done because of weird behaviour!

Close? You are using that in `switchToTabSession`.
I can "close" (technically you can't close the last tab, because then there wouldn't be an active note) and open all tabs without that line.

> Is it possible to make bulk opening of multiple tabs at once, as a method, rather than performing loop opening in script?

Not at the moment. And it would have the same effect as in the script.

**Comment by macsunmood** [comment]
> Close? You are using that in `switchToTabSession`. I can "close" (technically you can't close the last tab, because then there wouldn't be an active note) and open all tabs without that line.

By "close" I mean "get rid of all previous tabs after switching to the new ones".
Without that line you will always end up with one opened tab from the previous tabs session. 

> Not at the moment. And it would have the same effect as in the script.
So, the only way is to modify the Qt tabs source? No other way?

**Comment by pbek** [comment]
>  Without that line you will always end up with one opened tab from the previous tabs session.

Since there always is one note open this sounds valid.

> So, the only way is to modify the Qt tabs source? No other options?

Everything can be done with enough effort. Qt also is only implemented in C++... I'm open for reasonable pull requests.

**Comment by macsunmood** [comment]
I dug around, what was the problem there, and as far as I remember, it was connected with the failure of another way to replace all tabs, with the use of `setCurrentNote()`

Here's the code, which doesn't work as supposed:
```
// Close all currently opened note tabs
while (mainWindow.removeNoteTab(0)) { }

// First, replace the single open tab with the tag-related tab with index=0
script.setCurrentNote(tag_notes[0], true)

// Then, open all the tag-related notes (NO TIME INTERVAL)
for (let i = 1; i < tag_notes.length; i++) {
    script.setCurrentNote(tag_notes[i], true);
}
```

After closing all tabs but the last one, it won't replace it.
I believe, that's where the `weird` thing then came from.

**Comment by pbek** [comment]
Why don't you just open all tabs as usual with:

```qml
for (let i = 1; i < tag_notes.length; i++) {
    script.setCurrentNote(tag_notes[i], true);
}
```

...and then close the first tab with:

```qml
mainWindow.removeNoteTab(0)
```

Wouldn't that work?

**Comment by pbek** [comment]
I had good results with that too:

```qml
            // First, replace the single open tab with the tag-related tab with index=0
            script.setCurrentNote(tag_notes[0])

            // Focus related tag in the tag list
            mainWindow.jumpToTag(tag_obj.id)

            // Then, open the rest tag-related notes, starting from index=1
            for (let i = 1; i < tag_notes.length; i++) {
                script.setCurrentNote(tag_notes[i], true);
            }
```

No `true` that would open a new tab in the first `script.setCurrentNote`!

**Comment by pbek** [comment]
## 22.9.2
- there now is a new scripting command `mainWindow.getNoteTabNoteIdList()` to get
  a list of note ids that are opened in tabs (for [#2597](https://github.com/pbek/QOwnNotes/issues/2597))
  - for more information please take a look at the
    [MainWindow scripting documentation](https://www.qownnotes.org/scripting/classes.html#mainwindow)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by macsunmood** [comment]
> I had good results with that too:
> 
> ```qml
>             // Close all currently opened note tabs
>             while (mainWindow.removeNoteTab(0)) { }
> 
>             // First, replace the single open tab with the tag-related tab with index=0
>             script.setCurrentNote(tag_notes[0])
> 
>             // Focus related tag in the tag list
>             mainWindow.jumpToTag(tag_obj.id)
> 
>             // Then, open the rest tag-related notes, starting from index=1
>             for (let i = 1; i < tag_notes.length; i++) {
>                 script.setCurrentNote(tag_notes[i], true);
>             }
> ```
> 
> No `true` that would open a new tab in the first `script.setCurrentNote`!

Thanks for clarification, but sorry, this doesn't work, even without `true`. It still leaves one tab from the previous Tab Session when you switch between them - that's how it works for me.
So, my guess is `script.setCurrentNote(tag_notes[0])` simply doesn't work, if right after `while (mainWindow.removeNoteTab(0)) { }`.

**Comment by macsunmood** [comment]
> Why don't you just open all tabs as usual with:
> 
> ```qml
> for (let i = 0; i < tag_notes.length; i++) {
>     script.setCurrentNote(tag_notes[i], true);
> }
> ```
> 
> ...and then close the first (wrong) tab with:
> 
> ```qml
> mainWindow.removeNoteTab(0)
> ```
> 
> Wouldn't that work?

This won't work either. It closes one extra tab, replaces what's not to be replaced.. Check for yourself, switching between Tab Sessions, or opening the same session over and over..

**Comment by macsunmood** [comment]
> There now is a new release, could you please test it and report if it works for you?

Thanks, it seems to work well and return list of IDs.
Is it possible to map open tabs indexes to their related notes IDs ?

**Comment by pbek** [comment]
>  Is it possible to map open tabs indexes to their related notes IDs ?

yes, that's the list you'll get from the command

e.g.
tab 0 =>  note id 17
tab 1 => note id 23
...
