### ISSUE TITLE
Tags context menu small corrections

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2598]
#### Expected behaviour
 Rename "Remove tags", "Move tags to..." to "Remove tag(s)", "Move tag(s) to..."

![image](https://user-images.githubusercontent.com/45285672/187198830-b8fe4822-0b71-4c0d-a6ba-c443298f3fdb.png)

**Comment by pbek** [comment]
Why in your eyes do you think that would be necessary?

**Comment by macsunmood** [comment]
> Why in your eyes do you think that would be necessary?

If I select only single tag, "Remove tags" would seem wierd. It's actually a little confusing when using, especially for the first time.

**Comment by pbek** [comment]
> since you already have "Add tag" and "Rename tag" in the upper.

They are really for one tag, all with plural are for "n" tags.

**Comment by macsunmood** [comment]
> They are really for one tag, all with plural are for "n" tags.

But what if you select only one single tag? In such cases, it's usually written as "(s)".

**Comment by macsunmood** [comment]
@pbek 
Moreover, in the dialogue menu it's already shown as "tag(s)", unlike the Tag list context menu.
![image](https://user-images.githubusercontent.com/45285672/189524149-05596e7a-c272-48c5-8c8f-7d3b4cc202dd.png)

**Comment by macsunmood** [comment]
I have to say, I'm still experiencing confusion when stumbling upon "Rename tags" / "Rename notes", when right-clicking on a single tag/note, yet with Notes panel as well..
![image](https://user-images.githubusercontent.com/45285672/197539266-4b89107f-3d4f-4ba6-8fb5-2adde82c42da.png)

**Comment by macsunmood** [comment]
Can we just change "Remove notes" to "Remove note(s)", "Remove tags" to "Remove tag(s)", in order to prevent confusion? 🙂
