### ISSUE TITLE
Bug: opening note in an existing tab doesn't work if there's only a single open note

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2599]
Opening note in an existing tab (instead of new one) doesn't seem to work if there's only a single open note. So, there's no way to replace the last remaining note with some new.

Replacing the current note (if there are no note tabs any more) with `setCurrentNote()` using `asTab = false` won't do the job.

**Comment by pbek** [comment]
So basically setCurrentNote doesn't work for you? That is used in multiple scripts and I had no issues with it...
Do you have a script example?

**Comment by macsunmood** [comment]
Sorry, the bug turned out to be something different, so let me close this issue for now.
