### ISSUE TITLE
Editting note in DesktopApp gives differ error

### ISSUE THREAD

**Issue by Yamakasi** [pbek/QOwnNotes#26]
When I edit a note in QownNotes and my ownCloudClient syncs the QownNotes app popup a windows there there is difference between the server and QownNotes.

I understand why this happens, both clients want to syn the changes in the Notes folder in your Owncloud home folder.

How to fix this ?

**Comment by pbek** [comment]
QOwnNotes just reloads your current note without asking if it was externally changed and you didn't modify it in QOwnNotes for at least one minute.
But if you did edit your note with QOwnNotes recently (under one minute) you will get prompted because it would be really bad if you are writing something down and suddenly everything is gone because ownCloud (or some other sync system) overwrites your note file.

Do you edit your notes on the server and with QOwnNotes at the same time?

**Comment by Yamakasi** [comment]
No, I edit them only on my Client, desktop using the desktopApp.

I sync username/Docments to Documents where Notes is in username/Documents and Notes lives in the root of the user in Owncloud.

Great app tho!!

**Comment by pbek** [comment]
Thank you for your kind words, @Yamakasi !

So there is just one QOwnNotes (you didn't start more than one, did you?) and the ownCloud sync client.

Usually that doesn't make any problems.
You could try to play with the "note save interval time" setting in the *General* tab of the settings.

**Comment by Yamakasi** [comment]
Your welcome, and a Happy 2016 too!

Ad the Notes folder needed to be in a owncloud share I did that, so it should be fine indeed.

I can play with that for sure. It would also be nice to be able to remve the old paths from the menu, clear some cache or so.

Would it also be possible to sync the settings into a hidden file in the Notes folder ? in that case we can connect with only the username/password and server the time after as been setup. Maybe an idea.

**Comment by pbek** [comment]
A happy year 2016 too you too!

You mean you want to clear the "Recent notes folders" history? That would be nice indeed. I will implement that. Thank you!

Regarding the settings file... There are things in there that possibly shouldn't be held in the cloud. And every computer needs some different settings. And you can have multiple note folders, it would be inconvenient to lose the settings every time you change them... What are you trying to achieve by storing the settings in the notes folder?

**Comment by pbek** [comment]
Coming in version 0.71: you can now clear the recent note folders history in the settings

**Comment by pbek** [comment]
Version 0.71 is out now where you can clear the recent note folders history in the settings.
<http://www.qownnotes.org/installation>

**Comment by Yamakasi** [comment]
Nice! thanks!

**Comment by pbek** [comment]
Maybe Microsoft integrates OpenSSL into Windows one day. :)

**Comment by pbek** [comment]
I will close this issue until there are any news from you.
