### ISSUE TITLE
Inline images orientation doesn't match shown by other apps

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#260]
I wanted to put photos made by my Android phone to a note. In KDE's Dolphin photo has a portrait orientation, but in the app markdown render I see it rotated to landscape. 

My guess is that the phone puts current orientation to image EXIF. Image itself is not rotated. Apps rotate the photo based on the EXIF data to show it correctly. Almost all do, but markdown render is not among them.

Can it be resolved or it's an upstream code limitation?

**Comment by pbek** [comment]
That would be a limitation of the QTextEdit since we only generate a HTML `img` tag in QOwnNotes...
