### ISSUE TITLE
snap version panels shown/positiioned are not saved

### ISSUE THREAD

**Issue by Goddard** [pbek/QOwnNotes#2600]
I'm using the snap version of qownnotes.  I removed a few of the panels I don't need and now when Qownnotes loads up it shows no panels except the list of folders/sub-folders.

I can add them back through the menu, but if I close and re-launch the app it doesn't show the panels.

#### Expected behaviour
save panels shown/position

#### Actual behaviour
always loads with no panels except the folders/sub-folders

#### Steps to reproduce
Install snap and remove all panels and close, then open and add panels back and close.  Open again and panels aren't there.

QOwnNotes - version 22.8.4 - Snapcraft - build 981

**Comment by pbek** [comment]
I don't see why the snap should behave differently, do you also have this issue with e.g. the AppImage?

**Comment by Goddard** [comment]
Just reporting a bug.  I will have a look.  Love the app.

Thanks

**Comment by pbek** [comment]
Thank you 😁
