### ISSUE TITLE
True offline mode

### ISSUE THREAD

**Issue by Gitoffthelawn** [pbek/QOwnNotes#2602]
I recently tried QOwnNotes for the first time by "installing" v22.8.1 via the PortableApps.com platform.

First, I would like to congratulate everyone involved on what looks like an excellent cross-platform application.

Although this application offers cloud sync functionality, I would likely want to use it entirely offline.  As such, I went into the application's Settings UI and disabled all cloud-related options.  Specifically, I disabled cloud support, heartbeat & app metrics (sorry!), calendar support, the socket server, and web application support.

Even after doing all this, QOwnNotes tries to access the internet via TCP to a remote IP address (port 443) when it launches.

Is this a bug?  If so, it will be good to fix it.  If not, what QOwnNotes settings are required to prevent it from attempting to access the network and internet?

**Comment by pbek** [comment]
> Although this application offers cloud sync functionality

No, it doesn't 😅 see the Nextcloud settings dialog or https://www.qownnotes.org/getting-started/concept.html#nextcloud-desktop-sync-client.

> Even after doing all this, QOwnNotes tries to access the internet via TCP to a remote IP address (port 443) when it launches.

There is a request to https://api.qownnotes.org/ to check for updates on GitHub.

> Is this a bug? If so, it will be good to fix it. If not, what QOwnNotes settings are required to prevent it from attempting to access the network and internet?

No, it's a feature. I only want to support the latest version of QOwnNotes in my meager spare time for free.
If you don't want that best for example create a local host entry for `api.qownnotes.org` to redirect DNS requests to localhost. Or use a firewall to block the requests.

**Comment by pbek** [comment]
..or fork the project and rip out the updater. That would work too.

**Comment by Gitoffthelawn** [comment]
Thanks for your reply.  I totally understand having limited spare time *(me too!)* and only wanting to support the latest version.

What about adding a checkbox to the settings page with the heartbeat & app metrics checkboxes: *"Opt out of automatic update checks. Absolutely no support is provided for anything except the latest version!"*?

**Comment by pbek** [comment]
Might be a great idea for a fork you could start.

**Comment by Gitoffthelawn** [comment]
I'll think about a fork, but at least initially, it seems like overkill for a small modification. 😄

**Comment by Gitoffthelawn** [comment]
Looking forward to bots with emotions. ;)

**Comment by mYnDstrEAm** [comment]
Came here to create the same issue. A current workaround is to sandbox the app with [firejail](https://github.com/netblue30/firejail/) (install it and the profiles then run `firejail QOwnNotes`) and run `echo "net none" >>  ~/.config/firejail/QOwnNotes.local`.

Could you please fix this and allow for a true offline mode?

It wouldn't be a large change but it's a very important one for an app that people use for private notes. Things like that just introduce security vulnerabilities too. It would be best if there was a simple option "Offline mode" by which you can disable all the many options for Internet connectivity (not all of them are easy to find), but that's probably beyond this issue. Probably most other note-taking apps are offline by default or have that as a feature.

If you are concerned about people using old versions and creating issues here:
* most people would leave this option enabled and
* you could require people to specify their version when creating new issues here (and just tell them to check again with the latest version if it's an old version)
* longer-term it would be best if you add this to repos which provide updates, such as a/the Debian repository (that's a separate issue) - this would also make it easier for people to find (learn about) this software and to (quickly) update it

It's really important and easy to implement, please solve this.

**Comment by pbek** [comment]
If you want a complete network block (whatever the use-case for that is... a lot of functionality in QOwnNotes uses the internet) best use something to locally block the traffic. I certainly will not rip that out for anyone or go through the ordeal to implement a setting for all those things. firejail sounds a great idea to me.

**Comment by tredondo** [comment]
@mYnDstrEAm: OpenSnitch is great for just this purpose: deny any network requests from a given binary.
