### ISSUE TITLE
docs: where for default time format

### ISSUE THREAD

**Issue by GarryFlemings** [pbek/QOwnNotes#2603]
This PR affects only file _webpage/src/editor/time-formats.md_ and adds only one sentence there.

The added sentence tells readers where they should place the result of using this page.

Maybe there's a need to remove the preceding sentence.

If that preceding sentence refers to a syntax useable at other than the location my sentence points to, maybe that sentence is fine as it is.

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Are we talking about a future PR you are working on? 😀

**Comment by GarryFlemings** [comment]
PR #2605.

Feel free to delete this issue! (blush 😊) 😁

**Comment by pbek** [comment]
Thank you. 😁
