### ISSUE TITLE
Searching for all notes containing a certain word

### ISSUE THREAD

**Issue by DagNygren** [pbek/QOwnNotes#2604]
#### Expected behaviour
I think this is the best MD editor out there and it has been very useful, but I haven't found a way to search through all notes finding a certain string or word. Grepping the Notes directory is quite tedious.

**Comment by pbek** [comment]
The note search panel should be visible be default. Can you please post a screen shot.

**Comment by DagNygren** [comment]
The search only seems to search in the names of the notes. Not inside the notes.

**Comment by pbek** [comment]
No, it searches in the whole text. See https://www.qownnotes.org/getting-started/searching.html

**Comment by DagNygren** [comment]
Is there a setting for this. If I enter a text that for sure is found inside some notes but not in the title of anyone it will create a new note with the search word as title ??

**Comment by pbek** [comment]
You are a few hundred releases behind! That's why it makes a lot of sense to fill out the issue template when posting issues. 😁 
Maybe install the most current version (22.9.0) and try that one first: https://www.qownnotes.org/installation/ 😉

**Comment by DagNygren** [comment]
Now at 22.5.3. No difference in behaviour. Can see 4 different search fields. Subfolder, Tag, Note and navigation item. None of them looks for text inside all notes

**Comment by DagNygren** [comment]
Ahh. Now I got it! "Note search" is incremental and I should **NOT** press return to perform the search - Then he will create a new note. So it does work - Just not the way I expected :-)

**Comment by pbek** [comment]
Yes, it searches while you are typing. 😉
