### ISSUE TITLE
Microsoft Defender Anti-Virus found threats

### ISSUE THREAD

**Issue by GarryFlemings** [pbek/QOwnNotes#2606]
#### Expected behaviour

Continued availability of QOwnNotes.

#### Actual behaviour

QOwnNotes.exe gets deleted, apparently for having a virus or other undesired software.

Up until a week or so ago, I hadn't seen this. I was using a QOwnNotes version I downloaded from you in Aug 2022. I ignored the little note that said version 22.9.0 was available.

Once I experienced the problem, I downloaded 22.9.0. The one time I double-clicked QOwnNotes.exe, Microsoft alerted and deleted QOwnNotes.exe.

My copy of QOwnNotes hadn't changed since August when this problem started. Maybe I got a new version of Microsoft _Virus & Threat Protection_?

There are a couple of ways for me to respond. My ISP gives out free copies of McAfee. I uninstalled it during some problem-solving and hadn't gotten around to installing again. I plan to install that. It'll (as I understand) disable _Virus & Threat Protection_; hopefully it'll also do a more competent job of detecting threats.

At the same time, maybe it's important to you to know your code is getting this "welcome".

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Always false positive so far, see #1951, #1948, #1959, #2593...
QOwnNotes is built and released on GitHub from source.

Does https://www.virustotal.com/ find anything?

There's not much that can be done about "bad heuristics" in Windows Defender, last time MS patched that problem away within days... I myself was never able to reproduce this in Windows 10, it always worked...

**Comment by GarryFlemings** [comment]
Yup. I assumed false positive from the start.

I tried https://www.virustotal.com/. Of course, all but four options reported _undetected_; the remaining four couldn't run.

I installed McAfee (which I'd been meaning to do anyway). My problem went away. All good. Closing the Issue. Thanks.
