### ISSUE TITLE
The Arch repository on Opensuse is out of date (latest version 22.6.1)

### ISSUE THREAD

**Issue by evmcl** [pbek/QOwnNotes#2608]
Just a heads up that the repository for Arch builds hasn't seen an update since Qownnotes version 22.6.1 on June 19.

https://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Arch_Extra/x86_64/

Thanks.

**Comment by pbek** [comment]
Yes, the Arch OBS build system seems to be broken. It has unresolved packages (see https://build.opensuse.org/package/show/home:pbek:QOwnNotes/desktop).

**Comment by pbek** [comment]
On Libera.Chat there is an IRC support channel `#opensuse-buildservice`, maybe someone can give insight why Arch builds are broken. Other than that there is the AUR, but I simple use the AppImage.

**Comment by evmcl** [comment]
I'm okay with using AUR. Might want to remove the instructions for using that repository from the web-site though if it is defunct.

**Comment by pbek** [comment]
I'll add a warning.

**Comment by pbek** [comment]
I updated https://www.qownnotes.org/installation/building.html.
