### ISSUE TITLE
build start error, 0xc000007b

### ISSUE THREAD

**Issue by sgfcz** [pbek/QOwnNotes#2609]
i use software:
windows 10.0.19043.1889
qt 5.11.3
mingw 53_32
qt create 
cmake 3.18.6
i use release model build , build in the folder QOwnNotes-22.9.0/build/src, but i can't to open the exe, computer show me the error, **but it can run the qt create build**
i wanna ask need some setting or how to fix the error
thanks
![image](https://user-images.githubusercontent.com/43927011/190052068-f6bc59b2-6300-4601-b003-1207462bccab.png)
![image](https://user-images.githubusercontent.com/43927011/190052093-2da410ea-46b8-414c-a423-7ad0c1f00109.png)
![image](https://user-images.githubusercontent.com/43927011/190052116-169a0867-3637-4130-bd1a-7a6e5c9ab801.png)

**Comment by sgfcz** [comment]
need to add the qt mingw include/bin/lib folder to environment variables

**Comment by sgfcz** [comment]
but why release zip verion not need?

**Comment by sgfcz** [comment]
beasuse build use the vs version?

**Comment by pbek** [comment]
I've not a lot of experience building on Windows other than with Qt creator and qmake directly or the way I do it here with https://github.com/pbek/QOwnNotes/blob/develop/.github/workflows/build-release.yml or on AppVeyor like that https://github.com/pbek/QOwnNotes/blob/develop/appveyor.yml.

> but why release zip version not need?

which release zip? the one with the binary? you don't need that for building...

>  but i can't to open the exe, computer show me the error

what does it say in English?

**Comment by sgfcz** [comment]
> 

Haha，for give me ， my english is terrible。this building .yml file need some softward or way?
The **release zip** is this zip file, int the zip file QOwnNotes.exe can open,  but me build QOwnNotes.exe can't double click to open(qt create building can open), i think because me install the C++ VS environment , but in the cmake build for mingw, so i can't open the build QOwnNotes.exe,then add the mingw bin/lib/inculde into environment variables. magic, i can open the build QOwnNotes.exe version. so , i think the question  because need some dll or lib. 
Maybe the win version need some dll , but not in the zip file.
it need system environment  dll or lib, i guess
![image](https://user-images.githubusercontent.com/43927011/190537502-a3cd4521-0529-4e96-a656-6fe9eb04aa61.png)
![image](https://user-images.githubusercontent.com/43927011/190539096-967db196-f36d-4441-9de7-6bcd45b802df.png)

**Comment by pbek** [comment]
You need Qt to build QOwnNotes.
Best use QtCreator, it will also install Qt for you. See https://www.qownnotes.org/installation/building.html.

**Comment by sgfcz** [comment]
> You need Qt to build QOwnNotes. Best use QtCreator, it will also install Qt for you. See https://www.qownnotes.org/installation/building.html.

yes，qt or clion is best way
