### ISSUE TITLE
Straight double "quote" marks don't appear in Markdown rendered output

### ISSUE THREAD

**Issue by geckolinux** [pbek/QOwnNotes#261]
Hello, I'm really glad to see the very active development of QOwnNotes, it's working very well for my needs.

I noticed a bug where straight double quote marks `"` don't appear in the Markdown rendered output, both in the preview pane and in exported PDFs.

Thanks a lot!

**Comment by pbek** [comment]
Thank you for your kind words and reporting!
That must be some feature (?) of the hoedown library. I will see if there can be done anything about it.

**Comment by pbek** [comment]
Quotes were translated to `<q>` tags, I now turned that off for version 16.07.13.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by geckolinux** [comment]
Works perfect now. Thanks very much!

**Comment by pbek** [comment]
Great!
