### ISSUE TITLE
Sort list by Created Date

### ISSUE THREAD

**Issue by avtraino** [pbek/QOwnNotes#2610]
I searched the GitHub issues to make sure this isn't a duplicate, and I couldn't find anything. 

I love the feature that allows sorting the list by Last Modified Date, but I often find that it would be useful to have the option to sort by Created Date. I think that would even be my default sort if it was available. 

Would this be an easy addition or would it cause a ton of regressions that I haven't imagined? 

Thanks for all the hard work making such a great tool!

**Comment by pbek** [comment]
Thank you for your kind words (in your long title 😉).
Yes, you are right. That would involve a lot of changes and lots of regressions. 🤣

**Comment by macsunmood** [comment]
I second this feature. Can it ever be implemented in theory? :)

**Comment by pbek** [comment]
I guess. But I will not spend like 15h doing it or even want the added complexity. 😁

**Comment by macsunmood** [comment]
> I guess. But I will not spend like 15h doing it or even want the added complexity. 😁

Is it possible to implement with scripting using Script Panel and notes hrefs ?
