### ISSUE TITLE
Un-natural alphabetical sorting in Note List Panel

### ISSUE THREAD

**Issue by Wallboy** [pbek/QOwnNotes#2614]
Hello,

I like to use a single "Note List" panel with the "show all notes in subfolders" and "use a note tree" settings, along with sorting notes alphabetically.

My note names in each subfolders have names such as:
```
1-note1.md
2-note2.md
3-note3.md
```
The issue is when you get to above 10-note10.md, the it sorts like the following:
```
1-note1.md
10-note10.md
11-note11.md
2-note2.md
3-note3.md
...
9-note9.md
```
This is different to how Windows sorts files in folders. I was expecting to see sorting as you would more naturally expect it:
```
1-note1.md
2-note2.md
3-note3.md
...
9-note9.md
10-note10.md
11-note11.md
```
Is there any way to get this type of alphabetical sorting behavior?

Thanks!

**Comment by pbek** [comment]
No, sorry. There is no way. Best use a prefix like `001`.
