### ISSUE TITLE
[F] 🖼 picture in distraction less mode 

### ISSUE THREAD

**Issue by DiViNeCH** [pbek/QOwnNotes#2615]
#### Expected behaviour

Show Picutres while in "Distraction Less Mode"

#### Actual behaviour

Does show the link of the picture.

#### Steps to reproduce

Great tool, just starting to use it. Used cherry tree before, but I like this app whay more!

Vielen Dank!

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Thank you for your kind words. 😁 
But I'm sorry, it's still the same like in https://github.com/pbek/QOwnNotes/issues/1254#issuecomment-517548542. 😉

**Comment by DiViNeCH** [comment]
Oh, I'm sorry....

Am Fr., 30. Sept. 2022 um 09:02 Uhr schrieb Patrizio Bekerle <
***@***.***>:
