### ISSUE TITLE
[I] Internal Server Error when connecting to Nextcloud on startup

### ISSUE THREAD

**Issue by ptandler** [pbek/QOwnNotes#2616]
#### Expected behaviour

I expect that the connection to the nextcloud works if all the checks return "ok"

#### Actual behaviour

On each start and when saving the settings, an error message appears: "Nextcloud / ownCloud server error: **internal server error**. Please check the Nextcloud / ownCloud settings"

![Screenshot_20220930_105421](https://user-images.githubusercontent.com/934595/193237704-fc0ce266-ade9-456e-bf08-0ed61dcfda33.png)

But all the checks say "ok" ...? Would be helpful if there's a check that indicate what's failing.

![Screenshot_20220930_105506](https://user-images.githubusercontent.com/934595/193237734-5852177b-e124-4fb9-9295-defa24e0239b.png)

#### Steps to reproduce

Hm, for me it happens _always_, but I guess the issue is related to my nextcloud configuration ...?

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[11:00:05] [warning] "QNetworkReply error 401 from url https://(myNextcloud)/ocs/v2.php/apps/files_sharing/api/v1/shares: " "Error transferring https://(myNextcloud)/ocs/v2.php/apps/files_sharing/api/v1/shares - server replied: Internal Server Error"
[11:00:41] [warning] "QNetworkReply error 401 from url https://(myNextcloud)/ocs/v2.php/apps/files_sharing/api/v1/shares: " "Error transferring https://(myNextcloud)/ocs/v2.php/apps/files_sharing/api/v1/shares - server replied: Internal Server Error"
[11:02:26] [status] Die Aufgaben werden von Ihrem Server geladen


From the log file:

[Sept 30 11:00:01] [debug]: Set proxy configuration to use NO proxy
[Sept 30 11:00:05] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[Sept 30 11:00:05] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"(myNextcloud)" <serverUrl>"https://(myNextcloud)
" <username>"(username)" <accountId>"(username)" <priority>1
[Sept 30 11:00:05] [debug]: buildNotesIndex  - 'noteSubFolderId':  0
[Sept 30 11:00:05] [debug]: setupNoteFolderTables  - 'database version':  15
[Sept 30 11:00:05] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"(myNextcloud)" <serverUrl>"https://(myNextcloud)
" <username>"(username)" <accountId>"(username)" <priority>1
[Sept 30 11:00:05] [debug]: fetchShares  - 'url':  QUrl("https://(myNextcloud)/ocs/v2.php/apps/files_sharing/api/v1/shares")
[Sept 30 11:00:05] [debug]: loadNoteDirectoryList
[Sept 30 11:00:05] [debug]: reloadTagTree
[Sept 30 11:00:05] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(2)
[Sept 30 11:00:05] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(2)
[Sept 30 11:00:05] [debug]: reloadNoteSubFolderTree
[Sept 30 11:00:05] [debug]: reload
[Sept 30 11:00:05] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(2)
[Sept 30 11:00:05] [debug]: reloadNoteSubFolderTree
[Sept 30 11:00:05] [debug]: reload
[Sept 30 11:00:05] [debug]: loadNoteDirectoryList
[Sept 30 11:00:05] [debug]: reloadTagTree
[Sept 30 11:00:05] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(2)
[Sept 30 11:00:05] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(2)
[Sept 30 11:00:05] [debug]: reloadNoteSubFolderTree
[Sept 30 11:00:05] [debug]: reload
[Sept 30 11:00:05] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(2)
[Sept 30 11:00:05] [debug]: Reply from  "/ocs/v2.php/apps/files_sharing/api/v1/shares"
[Sept 30 11:00:05] [warning]: "QNetworkReply error 401 from url https://(myNextcloud)/ocs/v2.php/apps/files_sharing/api/v1/share
s: " "Error transferring https://(myNextcloud)/ocs/v2.php/apps/files_sharing/api/v1/shares - server replied: Internal Server Err
or"
[Sept 30 11:00:05] [debug]: Reply from share api
[Sept 30 11:00:05] [debug]: updateNoteShareStatusFromShare  - 'status':  "failure\n"

...

[Sept 30 11:00:18] [debug]: Reply from  "/ocs/v1.php/cloud/capabilities"
[Sept 30 11:00:18] [debug]: Reply from capabilities page
[Sept 30 11:00:18] [debug]: Reply from  ""
[Sept 30 11:00:18] [debug]: Reply from main server url
[Sept 30 11:00:18] [debug]: Reply from  "/ocs/v1.php"
[Sept 30 11:00:18] [debug]: Reply from ownCloud test page
[Sept 30 11:00:19] [debug]: Reply from  "/ocs/v1.php/cloud/capabilities"
[Sept 30 11:00:19] [debug]: Reply from capabilities page
[Sept 30 11:00:19] [debug]: Reply from  "/ocs/v1.php"
[Sept 30 11:00:19] [debug]: Reply from ownCloud test page
[Sept 30 11:00:19] [debug]: Reply from  "/ocs/v1.php"
[Sept 30 11:00:19] [debug]: Reply from ownCloud test page
[Sept 30 11:00:19] [debug]: Reply from  "/ocs/v1.php/cloud/capabilities"
[Sept 30 11:00:19] [debug]: Reply from capabilities page
[Sept 30 11:00:19] [debug]: Reply from  "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[Sept 30 11:00:19] [debug]: Reply from app info
[Sept 30 11:00:20] [debug]: Reply from  ""
[Sept 30 11:00:20] [debug]: Reply from main server url
[Sept 30 11:00:20] [debug]: Reply from  "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[Sept 30 11:00:20] [debug]: Reply from app info
[Sept 30 11:00:20] [debug]: Reply from  ""
[Sept 30 11:00:20] [debug]: Reply from main server url
[Sept 30 11:00:20] [debug]: Reply from  "/remote.php/dav/calendars/(username)"

...

[Sept 30 11:00:20] [debug]: Reply from  "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[Sept 30 11:00:20] [debug]: Reply from app info
[Sept 30 11:00:28] [debug]: Set proxy configuration to use NO proxy
[Sept 30 11:00:30] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"(myNextcloud)" <serverUrl>"https://(myNextcloud)" <username>"(username)" <accountId>"(username)" <priority>1
[Sept 30 11:00:30] [debug]: Reply from  ""
[Sept 30 11:00:30] [debug]: Reply from main server url
[Sept 30 11:00:30] [debug]: Reply from  "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[Sept 30 11:00:30] [debug]: Reply from app info
[Sept 30 11:00:30] [debug]: Reply from  "/ocs/v1.php"
[Sept 30 11:00:30] [debug]: Reply from ownCloud test page
[Sept 30 11:00:31] [debug]: Reply from  "/ocs/v1.php/cloud/capabilities"
[Sept 30 11:00:31] [debug]: Reply from capabilities page
[Sept 30 11:00:38] [debug]: Set proxy configuration to use NO proxy
[Sept 30 11:00:41] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[Sept 30 11:00:41] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"(myNextcloud)" <serverUrl>"https://(myNextcloud)" <username>"(username)" <accountId>"(username)" <priority>1
[Sept 30 11:00:41] [debug]: buildNotesIndex  - 'noteSubFolderId':  0
[Sept 30 11:00:41] [debug]: setupNoteFolderTables  - 'database version':  15
[Sept 30 11:00:41] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"(myNextcloud)" <serverUrl>"https://(myNextcloud)" <username>"(username)" <accountId>"(username)" <priority>1
[Sept 30 11:00:41] [debug]: fetchShares  - 'url':  QUrl("https://(myNextcloud)/ocs/v2.php/apps/files_sharing/api/v1/shares")
[Sept 30 11:00:41] [debug]: loadNoteDirectoryList
[Sept 30 11:00:41] [debug]: reloadTagTree
[Sept 30 11:00:41] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(2)
[Sept 30 11:00:41] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(2)
[Sept 30 11:00:41] [debug]: reloadNoteSubFolderTree
[Sept 30 11:00:41] [debug]: reload
[Sept 30 11:00:41] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(2)
[Sept 30 11:00:41] [debug]: reloadNoteSubFolderTree
[Sept 30 11:00:41] [debug]: reload
[Sept 30 11:00:41] [debug]: loadNoteDirectoryList
[Sept 30 11:00:41] [debug]: reloadTagTree
[Sept 30 11:00:41] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(2)
[Sept 30 11:00:41] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(2)
[Sept 30 11:00:41] [debug]: reloadNoteSubFolderTree
[Sept 30 11:00:41] [debug]: reload
[Sept 30 11:00:41] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(2)
[Sept 30 11:00:41] [debug]: Reply from  "/ocs/v2.php/apps/files_sharing/api/v1/shares"
[Sept 30 11:00:41] [warning]: "QNetworkReply error 401 from url https://(myNextcloud)/ocs/v2.php/apps/files_sharing/api/v1/shares: " "Error transferring https://(myNextcloud)/ocs/v2.php/apps/files_sharing/api/v1/shares - server replied: Internal Server Error"
[Sept 30 11:00:41] [debug]: Reply from share api
[Sept 30 11:00:41] [debug]: updateNoteShareStatusFromShare  - 'status':  "failure\n"
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fr. Sept. 30 11:11:07 2022`
**Version**: `22.9.2.1`
**Build date**: `Sep 27 2022`
**Build number**: `984`
**Platform**: `linux`
**Operating System**: `Linux Mint 20.3`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.12.8`
**Qt Version (runtime)**: `5.12.8`
**Portable mode**: `no`
**Settings path / key**: `$HOME/.config/PBE/QOwnNotes.conf`
**Application database path**: `$HOME/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `19`
**Calendar items**: `10`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `(MyOwnNextcloud)`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `24.0.5.1`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `de_AT, de_AT_frami, de_BE, de_CH, de_CH_frami, de_DE, de_LU, en_AU, en_CA, en_GB, en_US, en_ZA, es_AR, es_BO, es_CL, es_CO, es_CR, es_CU, es_DO, es_EC, es_ES, es_GT, es_HN, es_MX, es_NI, es_PA, es_PE, es_PR, es_PY, es_SV, es_US, es_UY, es_VE, fr, fr_BE, fr_CA, fr_CH, fr_FR, fr_LU, fr_MC, it_CH, it_IT, pt_BR, pt_PT, ru_RU`
**Language names**: `Österreichisches Deutsch (Österreich), Österreichisches Deutsch (Österreich), Deutsch (Belgien), Schweizer Hochdeutsch (Schweiz), Schweizer Hochdeutsch (Schweiz), Deutsch (Deutschland), Deutsch (Luxemburg), Australian English (Australia), Canadian English (Canada), British English (United Kingdom), American English (United States), English (South Africa), español (Argentina), español (Bolivia), español (Chile), español (Colombia), español (Costa Rica), español (Cuba), español (República Dominicana), español (Ecuador), español de España (España), español (Guatemala), español (Honduras), español de México (México), español (Nicaragua), español (Panamá), español (Perú), español (Puerto Rico), español (Paraguay), español (El Salvador), español (Estados Unidos), español (Uruguay), español (Venezuela), français, français (Belgique), français canadien (Canada), français suisse (Suisse), français (France), français (Luxembourg), français (Monaco), italiano (Svizzera), italiano (Italia), português (Brasil), português europeu (Portugal), русский (Россия)`
**Application dictionaries path**: `$HOME/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `$HOME/(path)/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: `Schule`
**database file**: `$HOME/(path)/Notes/notes.sqlite`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `true`
**DistractionFreeMode/editorWidthMode** (QString): `2`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `true`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**EvernoteImport/AttachmentImportCheckBoxChecked** (QString): `true`
**EvernoteImport/ImageImportCheckBoxChecked** (QString): `true`
**EvernoteImport/MetaDataUnCheckedList** (QStringList): `, `
**EvernoteImportDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2022-09-30T11:08:04.837`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Hack,9,-1,7,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Titillium Web,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Hack,9,-1,7,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Titillium Web,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (QString): `600`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**NoteFolder-1/NoteTabNameList** (QString): `Mittagessen (BBS)`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QString): `Schule`
**NoteHistory-1** (QVariantList): `<variant list with 17 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `16`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `true`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `0`
**TodoDialog/showDueTodayItemsOnly** (QString): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Deck: ...`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): `ddd dd.MM.yyyy`
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**interfaceStyle** (QString): `Breeze`
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `29`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `$HOME/(myNextcloud)/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): `...`
**ownCloud/todoCalendarEnabledList** (QStringList): `...`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://(myNextcloud)/remote.php/dav/calendars/(username)/app-generated--deck--board-1/, https://(myNextcloud)/remote.php/dav/calendars/(username)/app-generated--deck--board-2/, https://(myNextcloud)/remote.php/dav/calendars/(username)/app-generated--deck--board-3/`
**ownCloud/todoCalendarUrlList** (QStringList): `https://(myNextcloud)/remote.php/dav/calendars/(username)/app-generated--deck--board-1/, https://(myNextcloud)/remote.php/dav/calendars/(username)/app-generated--deck--board-2/, https://(myNextcloud)/remote.php/dav/calendars/(username)/app-generated--deck--board-3/`
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unbekannter Fehler`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `24.0.5.1`
**previousWorkspace** (QString): `6bded7c7-fb91-4e27-8e0f-bcd121c26b27`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2022-09-16T21.28.25, Note 2022-09-10T17.32.49, Note 2022-09-04T16.57.24, Note 2022-09-04T11.12.37, QOwnNotes Web Companion browser extension QOwnNotes`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Hauptsymbolleiste`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `Formatierungs-Werkzeugleiste`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `Einfügen-Werkzeugleiste`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `Verschlüsselung-Werkzeugleiste`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `Fenster-Werkzeugleiste`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `Beenden - Symbolleiste`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `true`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (QString): `22222`
**webSocketServerService/token** (QString): `<hidden>`
**workspace-6bded7c7-fb91-4e27-8e0f-bcd121c26b27/name** (QString): `Vollständig`
**workspace-6bded7c7-fb91-4e27-8e0f-bcd121c26b27/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-6bded7c7-fb91-4e27-8e0f-bcd121c26b27/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 6bded7c7-fb91-4e27-8e0f-bcd121c26b27`

## System environment

**MYTMP**: `/tmp/p`
**LANGUAGE**: `de_DE`
**USER**: `(username)`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**LC_TIME**: `de_DE.UTF-8`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `2191`
**SHLVL**: `0`
**HOME**: `$HOME`
**DESKTOP_SESSION**: `plasma`
**HOMEBREW_PREFIX**: `/home/linuxbrew/.linuxbrew`
**GTK_MODULES**: `gail:atk-bridge`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**LC_MONETARY**: `de_DE.UTF-8`
**CHROME_EXECUTABLE**: `brave-browser`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**LIBVIRT_DEFAULT_URI**: `qemu:///system`
**MANDATORY_PATH**: `/usr/share/gconf/plasma.mandatory.path`
**INFOPATH**: `/home/linuxbrew/.linuxbrew/share/info:`
**LOGNAME**: `(username)`
**XDG_SESSION_CLASS**: `user`
**DEFAULTS_PATH**: `/usr/share/gconf/plasma.default.path`
**XDG_SESSION_ID**: `c2`
**PATH**: `/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$HOME/.local/share/umake/bin:$HOME/.local/bin:$HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:$HOME/src/flutter/bin:$HOME/.yarn/bin`
**GDM_LANG**: `de_DE`
**HOMEBREW_CELLAR**: `/home/linuxbrew/.linuxbrew/Cellar`
**PAPERSIZE**: `a4`
**GTK3_MODULES**: `xapp-gtk3-module`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**LC_ADDRESS**: `de_DE.UTF-8`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**DISPLAY**: `:0`
**LANG**: `de_DE.UTF-8`
**XDG_CURRENT_DESKTOP**: `KDE`
**LC_TELEPHONE**: `de_DE.UTF-8`
**XDG_SESSION_DESKTOP**: `plasma`
**XAUTHORITY**: `$HOME/.Xauthority`
**MOZ_USE_XINPUT2**: `1`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/(username)`
**SSH_AUTH_SOCK**: `/tmp/ssh-1clwk07LvvyE/agent.2088`
**SHELL**: `/bin/zsh`
**LC_NAME**: `de_DE.UTF-8`
**QT_ACCESSIBILITY**: `1`
**GDMSESSION**: `plasma`
**LC_MEASUREMENT**: `de_DE.UTF-8`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**LC_IDENTIFICATION**: `de_DE.UTF-8`
**XDG_VTNR**: `7`
**PWD**: `$HOME`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-plasma:/etc/xdg`
**XDG_DATA_DIRS**: `/usr/share/plasma:$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share`
**WINEARCH**: `win32`
**HOMEBREW_REPOSITORY**: `/home/linuxbrew/.linuxbrew/Homebrew`
**LC_NUMERIC**: `de_DE.UTF-8`
**LC_PAPER**: `de_DE.UTF-8`
**MANPATH**: `/home/linuxbrew/.linuxbrew/share/man:`
**QT_SCREEN_SCALE_FACTORS**: `eDP-1=1;HDMI-1=1;`
**XCURSOR_THEME**: `breeze_cursors`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**KDE_FULL_SESSION**: `true`
**KDE_SESSION_VERSION**: `5`
**KDE_SESSION_UID**: `1000`
**SESSION_MANAGER**: `local/zenbook:@/tmp/.ICE-unix/2268,unix/zenbook:/tmp/.ICE-unix/2268`
</details>

**Comment by pbek** [comment]
> Hm, for me it happens always, but I guess the issue is related to my nextcloud configuration ...?

Yes, that looks like a Nextcloud issue. What are the log entries there for the "internal server error"?

**Comment by kdoteu** [comment]
I came across the same error an tackled it down to a NC Problem.
For further information: https://github.com/nextcloud/deck/issues/3464#issuecomment-1370575570
Disabling the Nextcloud Deck App solved the issue for me. But its only a quick fix.

**Comment by ptandler** [comment]
> I came across the same error an tackled it down to a NC Problem. For further information: [nextcloud/deck#3464 (comment)](https://github.com/nextcloud/deck/issues/3464#issuecomment-1370575570) Disabling the Nextcloud Deck App solved the issue for me. But its only a quick fix.

Thanks for sharing! Disabling Deck App really fixed it for me as well. Lucky, that we currently don't use Deck anyway.
