### ISSUE TITLE
Notes stop saving while editing

### ISSUE THREAD

**Issue by N-Upchurch** [pbek/QOwnNotes#2617]
While editing a note with the editor panel next to the preview panel, at some point the preview panel will no longer update as changes are made within the edit panel. After this occurs, when closing QOwnNotes, or switching to a new note and re-opening the note, no changes made since the preview window stopped updating are present.

Here is a recording of the behavior: 
![QOwnNotes](https://user-images.githubusercontent.com/8893713/193877193-f0abcb9c-c690-4230-a6c3-1118a59b813d.gif)

#### Expected behaviour
When editing a note, changes continue to be saved and rendered in the preview panel.

#### Actual behaviour
At some point, the preview panel will stop rendering changes and no further changes to the file will be saved.

#### Steps to reproduce
1. Open QOwnNotes with the subfolders, note list, edit, and preview panels visible.
2. Right click in the subfolders panel and click New Note.
3. Edit the title of the new note
4. Begin composing the rest of your note
5. At some point, you should notice the preview panel no longer reflecting your changes. Note -> Save Modified Notes will not save these changes either. 
6. Upon restarting QOwnNotes or switching to and from another note, you will see that no changes have been saves since the preview panel stopped rendering updates. 

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Oct 4 10:23:13 2022`
**Version**: `22.9.2`
**Build date**: `Sep 27 2022`
**Build number**: `984`
**Platform**: `linux`
**Operating System**: `KDE Flatpak runtime`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `TuxFamily`
**Qt Version (build)**: `5.15.6`
**Qt Version (runtime)**: `5.15.6`
**Portable mode**: `no`
**Settings path / key**: `/home/[USER]/.var/app/org.qownnotes.QOwnNotes/config/PBE/QOwnNotes.conf`
**Application database path**: `/home/[USER]/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Notes in current note folder**: `255`
**Calendar items**: `31`
**Enabled scripts**: `9`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `en_US`
**Language codes**: `en_AU, en_BS, en_BZ, en_CA, en_GB, en_GH, en_IE, en_IN, en_JM, en_MW, en_NA, en_NZ, en_PH, en_TT, en_US, en_ZA, en_ZW`
**Language names**: `Australian English (Australia), English (Bahamas), English (Belize), Canadian English (Canada), British English (United Kingdom), English (Ghana), English (Ireland), English (India), English (Jamaica), English (Malawi), English (Namibia), English (New Zealand), English (Philippines), English (Trinidad & Tobago), American English (United States), English (South Africa), English (Zimbabwe)`
**Application dictionaries path**: `/home/[USER]/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-2`
**localPath**: `/home/[USER]/Documents/Notes`
**remotePath**: *empty*
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: `Python`
**database file**: `/home/[USER]/Documents/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

### Script `YAML nested tags`

**id**: `1`
**path**: `/home/[USER]/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/scripts/yaml-nested-tags/yaml-nested-tags.qml`
**variablesJson**: 
```
{
    "tagHierarchySeparator": ".",
    "useDashesForClosing": true
}
```
**identifier**: `yaml-nested-tags`
**version**: `0.0.6`
**minAppVersion**: `20.6.0`

### Script `Mermaid Diagrams`

**id**: `3`
**path**: `/home/[USER]/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/scripts/mermaid/mermaid.qml`
**variablesJson**: *empty*
**identifier**: `mermaid`
**version**: `0.0.4`
**minAppVersion**: `22.1.1`

### Script `Image preview`

**id**: `4`
**path**: `/home/[USER]/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/scripts/image-preview/image-preview.qml`
**variablesJson**: 
```
{
    "maxWidth": 640
}
```
**identifier**: `image-preview`
**version**: `1.0.1`
**minAppVersion**: `20.6.0`

### Script `Wiki Links`

**id**: `5`
**path**: `/home/[USER]/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/scripts/wiki-links/wiki-links.qml`
**variablesJson**: *empty*
**identifier**: `wiki-links`
**version**: `0.0.1`
**minAppVersion**: `20.6.0`

### Script `YAML tags (Epsilon Notes compatible)`

**id**: `6`
**path**: `/home/[USER]/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/scripts/epsilon-notes-tags/epsilon-notes-tags.qml`
**variablesJson**: *empty*
**identifier**: `epsilon-notes-tags`
**version**: `0.0.5`
**minAppVersion**: `20.6.0`

### Script `Pandoc Export`

**id**: `7`
**path**: `/home/[USER]/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/scripts/pandoc-export/pandoc-export.qml`
**variablesJson**: *empty*
**identifier**: `pandoc-export`
**version**: `0.0.1`
**minAppVersion**: `21.12.0`

### Script `Insert Table of Contents (TOC)`

**id**: `8`
**path**: `/home/[USER]/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/scripts/insert-toc/insert-toc.qml`
**variablesJson**: *empty*
**identifier**: `insert-toc`
**version**: `0.0.3`
**minAppVersion**: `17.06.2`

### Script `Custom note preview styling`

**id**: `9`
**path**: `/home/[USER]/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/scripts/preview-styling/preview-styling.qml`
**variablesJson**: 
```
{
    "customStylesheet": "h2 {margin-left: 20px;}\nh3 {margin-left: 40px;}\nh4 {margin-left: 60px;}"
}
```
**identifier**: `preview-styling`
**version**: `0.0.5`
**minAppVersion**: `20.6.0`

### Script `Toggle checkbox`

**id**: `10`
**path**: `/home/[USER]/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/scripts/toggle-checkbox/toggle-checkbox.qml`
**variablesJson**: 
```
{
    "multipleLinesMethod": "cycleIndividually"
}
```
**identifier**: `toggle-checkbox`
**version**: `1.2.0`
**minAppVersion**: `19.3.2`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/editorWidthMode** (QString): `1`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `36`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`

**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `false`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`

**LastUpdateCheck** (QDateTime): `2022-10-04T09:52:22.363`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`

**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (QString): `600`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/linux-dark-mode** (QString): `65536`
**MessageBoxOverride/move-notes** (QString): `16384`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`

**NoteHistory-1** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `199`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `true`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `0`
**TodoDialog/showDueTodayItemsOnly** (QString): `0`

**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `true`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `8c8ac4dd-4c90-4562-9c0a-e901cc4135d9`
**cursorWidth** (QString): `1`

**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `false`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `30`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `false`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `false`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `0`
**notesPath** (QString): `/home/[USER]/Documents/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `2`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`

**ownCloud/todoCalendarCalDAVUsername** (QString): `[USER]`
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`

**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `fe11b39c-b104-48d0-9030-251773cd118d`
**recentNoteFolders** (QString): `/home/[USER]/Notes`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `false`
**spellCheckLanguage** (QString): `en_US`
**systemIconTheme** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/7/items**: *empty*
**toolbar/7/name** (QString): `custom_toolbar_1`
**toolbar/7/title** (QString): `custom_toolbar_1`
**toolbar/size** (QString): `7`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (QString): `22222`
**workspace-8c8ac4dd-4c90-4562-9c0a-e901cc4135d9/name** (QString): `View / Edit`
**workspace-8c8ac4dd-4c90-4562-9c0a-e901cc4135d9/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-8c8ac4dd-4c90-4562-9c0a-e901cc4135d9/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `8c8ac4dd-4c90-4562-9c0a-e901cc4135d9`

## System environment

**XDG_RUNTIME_DIR**: `/run/user/1000`
**container**: `flatpak`
**AT_SPI_BUS_ADDRESS**: `unix:path=/run/flatpak/at-spi-bus`
**CUDA_PATH**: `/opt/cuda`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/flatpak/bus`
**DEBUGINFOD_URLS**: `https://debuginfod.archlinux.org`
**DESKTOP_SESSION**: `plasma`
**DISPLAY**: `:0`
**FLATPAK_ID**: `org.qownnotes.QOwnNotes`
**FLATPAK_SANDBOX_DIR**: `/home/[USER]/.var/app/org.qownnotes.QOwnNotes/sandbox`
**GI_TYPELIB_PATH**: `/app/lib/girepository-1.0`

**GRADLE_HOME**: `/usr/share/java/gradle`
**GST_PLUGIN_PATH**: `/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0`
**GTK2_RC_FILES**: `/etc/gtk-2.0/gtkrc:/home/[USER]/.gtkrc-2.0:/home/[USER]/.config/gtkrc-2.0`
**GTK3_MODULES**: `xapp-gtk3-module`
**GTK_MODULES**: `canberra-gtk-module`
**GTK_RC_FILES**: `/etc/gtk/gtkrc:/home/[USER]/.gtkrc:/home/[USER]/.config/gtkrc`
**HOME**: `/home/[USER]`
**INVOCATION_ID**: `e304872ab8b44a57bdcb9d1c57dc5169`
**JOURNAL_STREAM**: `8:33964`
**KDE_APPLICATIONS_AS_SCOPE**: `1`
**KDE_FORK_SLAVES**: `1`
**KDE_FULL_SESSION**: `true`
**KDE_SESSION_UID**: `1000`
**KDE_SESSION_VERSION**: `5`
**LANG**: `en_US.UTF-8`
**LC_ADDRESS**: `en_US.UTF-8`
**LC_IDENTIFICATION**: `en_US.UTF-8`
**LC_MEASUREMENT**: `en_US.UTF-8`
**LC_MONETARY**: `en_US.UTF-8`
**LC_NAME**: `en_US.UTF-8`
**LC_NUMERIC**: `en_US.UTF-8`
**LC_PAPER**: `en_US.UTF-8`
**LC_TELEPHONE**: `en_US.UTF-8`
**LC_TIME**: `en_US.UTF-8`
**LD_LIBRARY_PATH**: *empty*
**LOGNAME**: `[USER]`
**MAIL**: `/var/spool/mail/[USER]`
**MANAGERPID**: `1165`
**MOTD_SHOWN**: `pam`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**PATH**: `/app/bin:/usr/bin`
**PS1**: `[📦 $FLATPAK_ID \W]\$ `
**PWD**: `/home/[USER]`
**QML2_IMPORT_PATH**: `/app/lib64/qml:/app/lib/qml`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**QT_LINUX_ACCESSIBILITY_ALWAYS_ON**: `1`
**QT_PLUGIN_PATH**: `/app/lib64/plugins:/app/lib/plugins:/usr/share/runtime/lib/plugins`
**SESSION_MANAGER**: `local/Lab-ManjaroKDE:@/tmp/.ICE-unix/1247,unix/Lab-ManjaroKDE:/tmp/.ICE-unix/1247`
**SHELL**: `/bin/sh`
**SHLVL**: `0`
**SYSTEMD_EXEC_PID**: `1446`
**USER**: `[USER]`
**XAUTHORITY**: `/run/flatpak/Xauthority`

**XDG_CACHE_HOME**: `/home/[USER]/.var/app/org.qownnotes.QOwnNotes/cache`
**XDG_CONFIG_DIRS**: `/app/etc/xdg:/etc/xdg`
**XDG_CONFIG_HOME**: `/home/[USER]/.var/app/org.qownnotes.QOwnNotes/config`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_DATA_DIRS**: `/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share`
**XDG_DATA_HOME**: `/home/[USER]/.var/app/org.qownnotes.QOwnNotes/data`
**XDG_SEAT**: `seat0`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_DESKTOP**: `KDE`
**XDG_SESSION_ID**: `2`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**XDG_SESSION_TYPE**: `x11`
**XDG_STATE_HOME**: `/home/[USER]/.var/app/org.qownnotes.QOwnNotes/.local/state`
**XDG_VTNR**: `1`
**__EGL_EXTERNAL_PLATFORM_CONFIG_DIRS**: `/etc/egl/egl_external_platform.d:/usr/lib/x86_64-linux-gnu/GL/egl/egl_external_platform.d:/usr/share/egl/egl_external_platform.d`

</details>

**Comment by pbek** [comment]
I can only imagine a sync client blocking the note markdown....

If that's not the case you could try run QOwnNotes in another session with another note folder and without scripts and so on, see https://www.qownnotes.org/getting-started/cli-parameters.html.

And then you could try the AppImage if you have the same issue there. See https://www.qownnotes.org/installation/appimage.html
The flatpak is community maintained.

**Comment by N-Upchurch** [comment]
Thanks for the advice; I am using SyncThing to sync my notes folder. When I disable watch / watching the file for changes in the SyncThing GUI, and set the sync interval to a long time, I cannot replicate the issue. 

I assume then that the note is unable to be updated after SyncThing notices a change, and syncs the file. I am able to save the same files post sync in other programs.

It would be nice to be able to use the watch feature on my notes folder; do you have any ideas as to why QOwnNotes is unable to continue auto-saving the document after it is synced? I would like to experiment further to see if I can get it working.

**Comment by pbek** [comment]
Maybe SyncThing is write locking while syncing or makes the file read-only. Other sync tool like the Nextcloud Sync Client or Dropbox don't have that issue. Maybe you can play around in the *General Settings* with the note save interval or trying to ignore all external note folder changes.

**Comment by pbek** [comment]
QOwnNotes sets the UI to read-only if the note file is read-only. People make read-only note files so they don't change them by accident...

**Comment by pbek** [comment]
Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting Debug in Options).
