### ISSUE TITLE
"Export selected text as PDF" and "Print selected text" broken

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#2618]
#2373 broke the exporting the selected text (as preview or plain text) and print selected text features. Now the whole document is exported instead of the selected text.

**Comment by pbek** [comment]
@Waqar144, it seems like you simply have taken code from the "export the whole note" feature and replaced the original code with it so you can refactor those parts more easily... 😅

**Comment by pbek** [comment]
I'll re-implement those four parts, I hope no other regressions will creep up from those January PRs. 😅

**Comment by Waqar144** [comment]
No its the same
