### ISSUE TITLE
Settings-screen shows "version 0 too low" for QOwnNotesAPI when using Nextcloud 10 beta

### ISSUE THREAD

**Issue by Paulikid** [pbek/QOwnNotes#262]
I decided to test the Nextcloud 10 Beta today and I noticed that QOwnNotes detects server version 9.1.0.13 and QOwnNotesAPI version 0. 
The "versions app", "deleted files app" and "notes folder" info in the Owncloud-settings inside of QOwnNotes shows "unknown".

**Comment by pbek** [comment]
That mast be the same problem like <https://github.com/pbek/qownnotesapi/issues/3>. Can you please try that sql statement and report back.

**Comment by Paulikid** [comment]
Yes, that did it. Many thanks!

**Comment by pbek** [comment]
Great! I've no idea why ownCloud / Nextcloud did this...

**Comment by pbek** [comment]
This is now fixed in Nexcloud 11, see <https://github.com/nextcloud/server/issues/2572>.
