### ISSUE TITLE
Add ability to toggle between [Edit panel] and [Note preview panel] via shortcut / menu button

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2620]
Currently no straight way to perform such a basic action.

**Comment by pbek** [comment]
Those things always are solved with workspaces. And there is a button to toggle between the last two.

**Comment by macsunmood** [comment]
> Those things always are solved with workspaces. And there is a button to toggle between the last two.

Workspaces is not a good solution because some minor changes to one WP won't reflect in the other. This creates a need to perform a lot of extra unnecessary actions.
Quick switch between Edit/Preview shortcut is a basic function for a Markdown app, so I consider it essential.

**Comment by pbek** [comment]
What are we talking about? Jumping to a panel or turning panels on/off?

**Comment by macsunmood** [comment]
> What are we talking about? Jumping to a panel or turning panels on/off?

For the generic side of the question - it's about switching between Edit/Preview in the current panel, be it changing the current panel rendering type, or instant replacement of one panel with another. 
I think, both button and a shortcut for this action are essential.

**Comment by pbek** [comment]
You should be able to do that with workspaces and that's the way it was supposed to be (after I first 5 different layouts with all kind of switches, because different users thought their layout should be THE layout)... But so far I wasn't able to put direct shortcuts on user generated workspaces.

**Comment by macsunmood** [comment]
> You should be able to do that with workspaces and that's the way it was supposed to be (after I first 5 different layouts with all kind of switches, because different users thought their layout should be THE layout)... But so far I wasn't able to put direct shortcuts on user generated workspaces.

I still don't quite get, why can't you have simply a shortcut/menu action to replace current Edit-panel with Preview-panel...
When the user wants to quickly glance what the rendered version looks like, without the need to resize the window, switch to different layout, look between 2 panels, etc.

You currently can't easily implement this. Almost every mature markdown app has this basic functionality..

**Comment by pbek** [comment]
You can already assign shortcuts to the items in the *Window / Panels* menu. You can also script the triggering of multiple menu actions with https://www.qownnotes.org/scripting/methods-and-objects.html#triggering-a-menu-action.

**Comment by macsunmood** [comment]
> You can already assign shortcuts to the items in the _Window / Panels_ menu. You can also script the triggering of multiple menu actions with https://www.qownnotes.org/scripting/methods-and-objects.html#triggering-a-menu-action.

Can you please elaborate on how to implement **replacing** of the Editing-panel with the Preview-panel?
I currently can't find a way to switch off the Editing-panel, nor to place the Preview-panel instead of it...

**Comment by macsunmood** [comment]
> https://www.qownnotes.org/faq/preview-without-edit.html

Sorry, I couldn't find actioned related to "Show note edit panel" and "Show note preview panel" in the `mainwindow.ui`, to trigger them..

**Comment by pbek** [comment]
> You can do that by turning off that the note edit panel is the central widget in the Panel settings.

that's the important line

**Comment by pbek** [comment]
And if you have found that, you need to use (look at) the source, Luke:

https://github.com/pbek/QOwnNotes/blob/4d15711510fe732ba299138918465b280504d596/src/mainwindow.cpp#L1360-L1363

**Comment by macsunmood** [comment]
> > You can do that by turning off that the note edit panel is the central widget in the Panel settings.
> 
> that's the important line

I did turn it off, yes.

> And if you have found that, you need to use (look at) the source, Luke:
> 
> https://github.com/pbek/QOwnNotes/blob/4d15711510fe732ba299138918465b280504d596/src/mainwindow.cpp#L1360-L1363

I was looking for it in the `mainwindow.ui`, searching for keywords as it's mentioned in the [Scripting doc](https://www.qownnotes.org/scripting/methods-and-objects.html#triggering-a-menu-action):
![image](https://user-images.githubusercontent.com/45285672/201521500-97e46ce4-4634-4e6c-8de5-3e32d0d266eb.png)

So, this doc probably needs some updating..

Still, I have yet to find what I'm looking for.. The closest thing I've found is `"actionShow_all_panels"`.

**Comment by pbek** [comment]
The actions that are generated dynamically are not in the ui file. The ui files are static.

**Comment by macsunmood** [comment]
> The actions that are generated dynamically are not in the ui file. The ui files are static.

So, are the actions I need `togglePanel-Edit` and `togglePanel-Preview` ?

**Comment by pbek** [comment]
➡️ `MainWindow::initDockWidgets()`
