### ISSUE TITLE
Won't start, error message: "Could not connect to display / Could not load the Qt platform plugin 'xcb'"

### ISSUE THREAD

**Issue by mernamer** [pbek/QOwnNotes#2623]
#### Expected behaviour:
QOwnNotes starts when run after install. 

#### Actual behaviour
Error message:
> Warning: could not connect to display  (:0, )
>Info: Could not load the Qt platform plugin "xcb" in "" even though it was found. (:0, )
>Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
>
>Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
 (:0, )

#### Steps to reproduce
- Followed install instructions for Raspbian 11 [here](https://www.qownnotes.org/installation/raspberry-pi-os.html#raspbian-9-0)
- Followed instructions [here](https://www.qownnotes.org/installation/) to start the first time.

Attempting on Raspberry Pi B+ (armv61) running Raspbian 11 (bullseye), thought the older board or having to run in 32 bit could be issues, but just didn't see that in the documentation, sorry if I missed.

#### logs

NA, didn't get that far and couldn't find anything relevant in /var/log and subdirectories, but can look elsewhere if anyone has ideas.

**Comment by pbek** [comment]
I had it running on a Raspberry Pi 3 for some time...

There isn't a built for armv6l for Raspbian 11, I've tried to enable it, but I'm not sure if it will build (or even show up on OBS). I've also enabled the aarch64.

**Comment by pbek** [comment]
aarch64 built, but OBS doesn't seem to support armv6l for Raspbian 11 any more.
