### ISSUE TITLE
[I] + [F] ISSUE with Rendering of Preview, when Editing/Navigating within the Note + FEATURE REQUESTS

### ISSUE THREAD

**Issue by Cho-Chang** [pbek/QOwnNotes#2625]
Hi, @pbek!

First, thank you for this wonderful app. 

I'd like to report an issue, and request some features as well. 

### Position of Text in Preview Pane does not correspond to Position of cursor in the Edit Pane

Following GIF illustrates this:

![1](https://user-images.githubusercontent.com/85818525/196018832-2567f126-71f2-45ac-b2e2-307ea4a3e802.gif)

#### Actual Behaviour
Everytime I edit the Note, and want to view the output, I have to scroll up or down a fair bit in the Preview Pane. 

This happens primarily when Note has
1. Images
2. Tables

#### Expected Behaviour
Preview Pane renders the same Paragraph/Text that is
1. being edited, or 
2. being accessed through Navigation Panel

### 1. All Tabs View
Please Consider adding a Button that shows all the Open Tabs in a vertical Dropdown/Panel. It would be very helpful for those of us who have tons of Notes open at once.

Ex, Firefox has a button like this:

![3](https://user-images.githubusercontent.com/85818525/196019362-7c5941d7-1de4-4f0e-9f6e-bb8aaa4bd965.gif)

### 2. Tab Scroll Behaviour

Presently, when scrolling over Tabs, Previous or Next tab is selected right away:

![5](https://user-images.githubusercontent.com/85818525/196019719-c2f4e55e-8d95-4243-9bf9-76c474a1593a.gif)

Please Consider it making something like this, such that one can view all the tabs when scrolling, and Tab is selected only when it is clicked on (Ex from Sublime Text): 

![2](https://user-images.githubusercontent.com/85818525/196019349-0282f0a3-1b7f-4303-a6b5-61c71ceae4a6.gif)

### 3. Keyboard Shortcuts for Switching Between Panels

Please consider adding Keyboard Shortcuts for switching between Panels, when they are displayed in Tabs. Ex:

![6](https://user-images.githubusercontent.com/85818525/196019803-7e29faa6-1778-4ecb-bfcd-74438d84ca6c.png)

It would be nice to have a Shortcut, say CTRL+TAB, for switching between Note List and Navigation Panel here.

**Comment by pbek** [comment]
> First, thank you for this wonderful app.

Thank you. 😁 
It's better to split such things they are different feature requests.

> 1. Position of Text in Preview Pane does not correspond to Position of cursor in the Edit Pane

Yes, that's the way it is. The two panels are just "linked" by their calculated scrollbar percentage position. There's no known way to improve on that.

> 1. All Tabs View

Sounds like a thing QTabBar should have.

> 2. Tab Scroll Behaviour

That's also a behavior of the QTabBar of Qt... 

For the last two: I don't know if anyone want's to implement their own tab bar. Sounds like a lot of work.

> It would be nice to have a Shortcut, say CTRL+TAB, for switching between Note List and Navigation Panel here.

There are already shortcuts to access the navigation panel and the note list. In my opinion it makes more sense to use the shortcuts of the panels directly.

**Comment by Cho-Chang** [comment]
Regarding the Issue, vNote (https://github.com/vnotex/vnote), does a good job of synchronizing Positions of Preview Pane and Editing Pane. 

I have no Programming knowledge, so forgive my ignorance, but could QOwnNotes's behaviour in that regard be modeled on vNote?

**Comment by pbek** [comment]
Looks like a WYSIWYG editor for me, isn't it? Or do they have an editor and a preview, like QOwnNotes?

**Comment by Cho-Chang** [comment]
It does have separate Editor and Preview. With the same note:

![2](https://user-images.githubusercontent.com/85818525/197314987-7bb19b7d-157f-4127-b55a-96749ca85755.gif)

**Comment by pbek** [comment]
Any ideas how they are linking the markdown to the HTML?

**Comment by Cho-Chang** [comment]
I'm a dummy when it comes to Programming :)

I did some digging around; Could it be somewhere here? - https://github.com/vnotex/vnote/blob/master/src/widgets/viewwindow.h

**Comment by pbek** [comment]
More like <https://github.com/vnotex/vnote/blob/master/src/widgets/markdownviewwindow.cpp>, but unfortunately there are no code comments at all about that...

**Comment by pbek** [comment]
@Waqar144, can you make anything out of it?

**Comment by Waqar144** [comment]
For correct synced scrolling, percentage will not work always.

Generally the amount of single steps in a scrollbar is equal to the number of lines in the document. This information can be used to implement correct synced scrolling. Our preview usually has less number of lines than the editor because of markdown conversion so this needs to be taken into account.

**Comment by Cho-Chang** [comment]
@tamlok Could you please help with this? 

How does VNote synchronize position of Scrollbar in Preview Pane and Edit Pane, when they are rendered side-by-side?

**Comment by Cho-Chang** [comment]
VNote probably uses Line numbers for syncing Editor and Preview

Commit in which they added Editor-Preview Split View: https://github.com/vnotex/vnote/commit/6b1f00880ea8496c177ae22ea0563d5e75f7996c#diff-cd9648114ece43ee613a39a919663c9ae4699705fff9869ee53340cfe0508499

Could be Relevant:
1. https://github.com/vnotex/vnote/blob/master/src/widgets/editors/markdownvieweradapter.cpp#L101
2. https://github.com/vnotex/vnote/blob/master/src/widgets/editors/markdownvieweradapter.h#L104
3. https://github.com/vnotex/vnote/blob/master/src/widgets/markdownviewwindow.cpp#L173

PS: I hope me mentioning another project here repeatedly is not inappropriate. Just that it is also QT based, and does this thing better than QON.
