### ISSUE TITLE
Note does not update or notify on external modification

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#2626]
I switched from syncing via NextCloud to syncing via Syncthing. While testing I noticed that QON does not reload a displayed note on external changes. 

The log panel shows

```
[10:15:52] [status] Notes directory was modified externally
```

Switching to an other note and back displays the updated content. 

Behavior is the same regardless `Notify about all external modifications of the current note` is ticked or not. 

Version: `qownnotes 22.10.1-1`.

**Comment by sanderboom** [comment]
Sometimes it seems that Syncthing is creating a new file instead of updating the current.

> When you reload the note folder the current note should also be updated. That's what I do even for Nextcloud because I don't trust the inotify events a lot. 

Aha :sweat_smile:  :+1:

**Comment by pbek** [comment]
> Sometimes it seems that Syncthing is creating a new file instead of updating the current.
> 

Yes, something to that extend. It would be very hard to keep track of that...

**Comment by Helium314** [comment]
@pbek 
When trying to watch a single file (synced with Syncthing) with inotifywait, there is only an change found when the `attrib` event is included. I have no idea how things work in QOwnNotes, but maybe a similar thing could be done.
Syncthing seems to create a new temporary file and then probably renames it.

**Comment by pbek** [comment]
>  Syncthing seems to create a new temporary file and then probably renames it.

Yes, I guess that slips through... It's not the old note file any more.
