### ISSUE TITLE
not found - notes path found on server

### ISSUE THREAD

**Issue by jbeltran73-2** [pbek/QOwnNotes#2627]
Hello, thank you for your support. 

#### Expected behaviour
Backup and/or show the notes at NextCloud server away from Local

#### Actual behaviour
The app at Note/Settings/Nextcloud shows me this:

![image](https://user-images.githubusercontent.com/55049032/196265852-d762f1cc-5b47-44cf-bda8-51dc06ce8788.png)

I'll reply myself as I've found it.

**Comment by jbeltran73-2** [comment]
The problema was that I didn't add in the Nextcloud desktop Synch the folder from Qownnote to be sync,.  This is the first step.
![image](https://user-images.githubusercontent.com/55049032/196270785-14a5359d-14a7-4ed9-bddb-28f2deddb9a2.png)

The second step that I had to take was to add this folder in the settings in Qownnote as I show here in the second screenshot. 

![image](https://user-images.githubusercontent.com/55049032/196270961-64d990f3-cf6f-433f-8ce2-7391e3550b52.png)

As you can see in the field "Path on your Nextcloud /owncloud server. 
There I selected the folder already created in Nextcloud in the previous step. 

Cheers

**Comment by pbek** [comment]
So did you find the setting now? 😁

**Comment by pbek** [comment]
to make sure...

## 22.10.2
- the connection test in the *Nextcloud / ownCloud* settings now also shows the notes path
  on the server that is being checked (for [#2627](https://github.com/pbek/QOwnNotes/issues/2627))
  - a tooltip with information about where to find the path was also added to the text

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by jbeltran73-2** [comment]
Hi there and sorry for the late reply, I was travelling. 
![image](https://user-images.githubusercontent.com/55049032/197059581-131c70d5-0669-44d6-9f72-66ffc0d5108e.png)

Awesome, it does. 
That was fast. 
Thank you!

**Comment by pbek** [comment]
Great, makes it more clear.
(Happy traveling when you are traveling again. 😁 )
