### ISSUE TITLE
[Feature request] Opening text documents without importing them and without changing the file extension to .md

### ISSUE THREAD

**Issue by mYnDstrEAm** [pbek/QOwnNotes#2628]
It would be very useful if you could open and edit text documents with QOwnNotes directly, instead of having to import and copy them first.

For example you may want to leave your documents where they are now (for example because you organized them in file system structures). Then you could also QOwnNotes as a text editor, including when you want to make a quick small change to an existing file. A key feature that I think is critical for a note-taking app is that it allows opening any plaintext files with the right click context menu or double click (otherwise one would have to constantly switch between the note taking app and the text editor which both have tabs defeating a main purpose of it).

The file extension wouldn't get changed to .md despite allowing for markdown syntax and formatting, this would allow opening notes without a file extension as well as with the .txt extension.

This would be enormously useful and somebody probably asked about it earlier but I couldn't find it. I thought QOwnNotes would have this feature before I found out that it doesn't (if I haven't missed something)...many other note-taking apps have this feature.

Lastly, opening notes with right click->open with QOwnNotes could and should then also become possible, strangely that isn't yet possible.

If you don't think this feature (or these features) should be enabled by default, then please make it an option in the settings.

#### Expected behaviour
Allow editing notes in their current location by default when opening files from within QOwnNotes or opening files with QOwnNotes via the right click Open with context menu.

#### Actual behaviour
Copies notes to the configured path /home/username/dir/Notebooks, changes the file extension if it's not already .md and can't open any plaintext files via right click.

**Comment by mYnDstrEAm** [comment]
Maybe the title could be changed to something more like "Enable support for notes / plaintext files outside of configured note folders" (this may or may not require changing some option in the config...the default could stay exactly the same and/or notes outside of note folders could lack some features or get displayed differently somehow).

**Comment by pbek** [comment]
Like I said, all of the core functionality depends on note folders... But you can enable subfolders and spread your note folder wider... QOwnNotes is nothing what commonly is known as "Markdown editor".
