### ISSUE TITLE
wrong note is opened if note name is not unique across folders

### ISSUE THREAD

**Issue by jd666** [pbek/QOwnNotes#263]
I assume the internal structures do not use the path information.
Similar: the sqlite DB uses the filename without path in the noteTagLink table.

**Comment by pbek** [comment]
Yes, that is still on my to do list.

**Comment by pbek** [comment]
## 16.07.13
- added more support for same note names in different note subfolders
    - there still has to be done more here

**Comment by pbek** [comment]
## 16.07.14
- did a lot of improvements for support of same note names in different 
  note subfolders and general note storing, loading, tagging and
  renaming
- added support for tagging in note subfolders

@jd666, @Maboroshy, @LightTemplar, there now is a new release, could you please test it and report if the new features work for you?

**Comment by pbek** [comment]
I already found a huge problem, tagging doesn't work any more without note sub folders... more side effects, more work... :(

**Comment by pbek** [comment]
## 16.07.15
- tagging of notes in non-subfolder mode is working again 
- if showing of note subfolders is turned off in the settings the 
  active note subfolder will now be reset to prevent problems

**Comment by pbek** [comment]
## 16.08.0
- tagging, removing tags, moving and copying multiple notes in note 
  subfolders now works correctly if notes with the same name exist 
  in other note subfolders

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?
