### ISSUE TITLE
Preview fails to render code block completely

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#2631]
#### Markdown:

````
#### Timezone

```
sander@ubuntu:~$ sudo timedatectl
               Local time: Sat 2022-10-22 15:24:56 UTC
           Universal time: Sat 2022-10-22 15:24:56 UTC
                 RTC time: Sat 2022-10-22 15:24:56
                Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```
````

#### Result:

![image](https://user-images.githubusercontent.com/5956570/197358665-62be68b7-e0b2-4401-864c-17748325fdbc.png)

#### Version 
`qownnotes 22.10.1-1`

**Comment by pbek** [comment]
Thank you!

@Waqar144, any ideas?

**Comment by pbek** [comment]
It seems if you use exactly 17 spaces before some text in a code block all the following text is removed from it.

**Comment by Waqar144** [comment]
Right. ;p

Guess we were bound to hit this issue at some point

**Comment by pbek** [comment]
What did we try to do with those 17 characters, I just can remember vaguely...

**Comment by Waqar144** [comment]
We didn't really do anything IIRC. Also I dont exactly remember whether the bug is in QON or md4c though, perhaps an update will resolve the issue.

**Comment by pbek** [comment]
But this was the issue: https://github.com/mity/md4c/issues/124

**Comment by Waqar144** [comment]
Do you have a branch? Also this issue is a dupe of another

**Comment by Waqar144** [comment]
https://github.com/pbek/QOwnNotes/issues/1732 original

**Comment by pbek** [comment]
> Do you have a branch? 

No, I only started to play with the cmakefile and the qmake project file.

> #1732 original

thank you

**Comment by pbek** [comment]
I'll move on to #1732.

**Comment by pbek** [comment]
> As a first step we can update the subproject and then bump it here.

It will break the build, so I only checked out the other repository locally.

**Comment by pbek** [comment]
>  I'll fix the issue directly.

@Waqar144, nevertheless if you are able to get the new version of md4c in it would be awesome! 😁
