### ISSUE TITLE
regular expression support

### ISSUE THREAD

**Issue by GarryFlemings** [pbek/QOwnNotes#2632]
#### Prior issue(s) close to this one

For #466, the prime concern was searching in the preview pane. I'm interested in searching in the "Note edit" pane via Ctrl+F.

I'm using QOwnNotes version 22.9.0 on a current Win 10 computer.

#### Expected behaviour

Situation: My notes have many instances of dates in a OneNote format (MM/DD/YYYY). I prefer them in YYYY-MM-DD format. It would be great if I could do that with regular expressions.

I tried Ctrl+F (Find) and put an appropriate formula in the "Find:" field; I successively found each date I wanted to change.

I put "$3-$1-$2" in the "Replace:" box. Those references are to the succession of values (MM, DD, and YYYY) in the OneNote format.

I expected to see "YYYY-MM-DD" (including substitutions) after clicking the "Replace" button.

#### Actual behaviour

My dates were replaced literally by the string "$3-$1-$2"; no substitutions.

#### Steps to reproduce

* Ctrl+F
* In the "Find:" field: ([\d]{4})
  * Identifies a four-digit string and "captures" it for future use.
* In the "Replace:" field: $1
  * Refers to the first captured field. In this example, that's the *only* captured field.
* Click the search icon to find the year ("2022"). Click the "Replace" button.

Note that QOwnNotes changes the "2022" to (literally) "$1".

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

All entries in the log output about QOwnNotes indicated a note was successfully stored.

</details>

**Comment by pbek** [comment]
Were you on IRC yesterday and maybe didn't wait for an answer? 😁 
Did you try this answer by @Waqar144?

![image](https://user-images.githubusercontent.com/1798101/197376446-0ee4ef73-55cf-455c-96a8-c7a033fda224.png)

**Comment by GarryFlemings** [comment]
@Waqar144: Perfect! That works. Thanks lots for sharing.
@pbek: I stuck around on IRC for some time after your note, but Waqar's note wasn't there when I closed it. Thanks for this posting.

As to this ticket:

* If there's a rightful place in the documentation to demonstrate this existing capability, perhaps this ticket can be the motivator for adding this. (Or maybe it's there; I couldn't find it.)
* If there's a rightful place in the open source code on Github and there's no author to tweak it, I'm a volunteer as that author. Please point me the right place; I'll get you a nomination change.
* If this is in the category "obvious enough we don't want to bloat the documentation", I'm with you to close this ticket.

Thanks lots.

**Comment by pbek** [comment]
Currently there only is a page for searching for notes (https://www.qownnotes.org/getting-started/searching.html), but not searching in notes.
