### ISSUE TITLE
The trashed notes sorting is weird

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2633]
For cyrillic UI in OS (Win10), while having English UI in QOwnNotes the program makes some weird sorting for the trashed notes (the default "Trashed" sorting):
![image](https://user-images.githubusercontent.com/45285672/198011860-683266da-d968-48dc-af71-b75282242c13.png)

e.g. you can see October placed right above (hence, after) August, and then September goes..
The logic behind placing July between two Septembers at the top is also incomprehensible.

**Comment by pbek** [comment]
Strange, I can't reproduce that. The date column has a timestamp as number in the background which is used for sorting.

**Comment by pbek** [comment]
Do you have the same issue in English?

**Comment by macsunmood** [comment]
> Do you have the same issue in English?

Unfortunately, I don't have english in OS, and don't know anybody who has. Is this field undoubtely based on internal OS date representations?

**Comment by pbek** [comment]
I mean in qownnotes.

**Comment by macsunmood** [comment]
> I mean in qownnotes.

I'm using English interface in the app. The Trashed column appears in cyrillic.

**Comment by pbek** [comment]
Ah, local time formatting.
Anyway, should matter since the integer timestamps are compared in the sorting. Mine seem to be in perfect order:

![image](https://user-images.githubusercontent.com/1798101/198519248-17ef7792-54f7-4228-a1a0-857a405b0413.png)

![image](https://user-images.githubusercontent.com/1798101/198519328-060c29aa-200f-4e9e-a644-f6130b7c8c8a.png)

**Comment by macsunmood** [comment]
> Ah, local time formatting. Anyway, should matter since the integer timestamps are compared in the sorting. 

I guess you meant "should**n't** matter" ?
I don't get why local time formatting affects the timestamps - it is not possible..

**Comment by pbek** [comment]
I don't have a Russian Windows to try to reproduce that. 😅 

I wonder what these integers are set to on your system:

https://github.com/pbek/QOwnNotes/blob/8746a40428804030dc096ecea719c5210db17bf5/src/dialogs/localtrashdialog.cpp#L22-L26

**Comment by macsunmood** [comment]
> I wonder what these integers are set to on your system:
> 
> https://github.com/pbek/QOwnNotes/blob/8746a40428804030dc096ecea719c5210db17bf5/src/dialogs/localtrashdialog.cpp#L22-L26

Please, elaborate what I should do to check that out.

**Comment by pbek** [comment]
Building QOwnNotes yourself after adding some debug messages.
