### ISSUE TITLE
Right clicking certain areas (Todo, Issues form) closes application

### ISSUE THREAD

**Issue by linkp** [pbek/QOwnNotes#2634]
#### Expected behaviour

Right click does not close/crash application

#### Actual behaviour

Right click closes/crashes application

#### Steps to reproduce

1. Open Todo list
2. Select a todo list item
3. Right click in the list pane
4. QOwnNotes closes unexpectedly

While attempting to generate this report using the recommended Help Menu item, I right clicked to fix a misspelled word, and QOwnNotes closed unexpectedly. I was able to duplicate that result as well.

I am omitting the debug info requested as it will require some efforts to sanitize private data, and it is not particularly relevant to the scenario, as determined by the Help Menu symptom being reproducible on the v22.10.2 AppImage version on a GRML Live Linux session.

**Comment by pbek** [comment]
I'm sorry, I can't reproduce your issue. If I right click a todo item I get the context menu. Hard to tell what's happening without more information.

**Comment by linkp** [comment]
I, too, get a contextual menu item when I right click a list entry on the item list in the left pane. A right click inside the right pane is what triggers the application closing for me. It's actually been occurring for quite some time. I usually avoid right clicking in that pane until I forget and it happens again some time, which occurred today. I found no similar open or closed issue and figured it was worth reporting.

This is also happening if I right click inside any of the three bottom dialog boxes the Issue Assistant from the Help menu (Expected behaviour/Actual behaviour/Steps to reproduce). That was what I was able to reproduce in the AppImage on a GRML Live CD (to rule out my openSUSE Leap 15.4 environment).

When launching QOwnNotes from the CLI, `[1]    18260 segmentation fault (core dumped)  QOwnNote` is displayed when the application closes unexpectedly due to the right click. Does any of this information help at all?

**Comment by pbek** [comment]
> A right click inside the right pane is what triggers the application closing for me.

Hah, I can reproduce that. Thank you very much!

**Comment by pbek** [comment]
@Waqar144, looks like another January blooper 😅 
Since https://github.com/pbek/QOwnNotes/commit/c48eae67c5b8173846288faddc0d3d5197b31dd6 `QOwnNotesMarkdownTextEdit::onContextMenu` depends on `mainWindow` which isn't always set in a lot of cases...

**Comment by Waqar144** [comment]
I think everything should use the `MainWindow::instance()` instead of setMainWindow which is just error prone. The instance is always there

**Comment by pbek** [comment]
Thank you very much!

**Comment by pbek** [comment]
## 22.10.3
- a crash when right-clicking on the textedit in dialogs like the todo list dialog
  and the issue dialog was fixed (for [#2634](https://github.com/pbek/QOwnNotes/issues/2634))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by linkp** [comment]
It is resolved for me in QOwnNotes - version 22.10.3 - OBS - build 988. Many thanks!

**Comment by pbek** [comment]
Great. Thank you for testing it!
