### ISSUE TITLE
Adding QtQuick support for QML Scripting under Windows

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2636]
Currently there's not support for QtQuick in QML Scripting under Windows.

Can this help ?
https://stackoverflow.com/questions/53160127/windeployqt-module-qtquick-not-installed

**Comment by macsunmood** [comment]
@pbek do you think it is possible to add QtQuick support to QON and make it work for scripting?

**Comment by pbek** [comment]
I guess it's a matter of DLL files. To test the `--qmldir` parameter you could create your own "release" (on GitHub) by forking this repository and changing this call in the `master` branch (triggers the release build):

https://github.com/pbek/QOwnNotes/blob/70e8aec4567917a404d3ed7c6500367feb1826cb/build-systems/github/windows/build-zip.ps1#L29
