### ISSUE TITLE
Prevent populating the trash with duplicate junk

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2637]
When renaming an existing file (hence, changing it's main header), the app manages to creates several files (along the process of renaming) with the intermediate name versions, then puts them all into local trash.

Why not make some workaround (like just waiting more if it's the title line being edited) to prevent populating the trash with duplicate junk?

**Comment by pbek** [comment]
I guess that would mean keeping track of all changes in notes and prevent automatically saving those notes... Not easy to implement nor would I feel safe with it as user. And when does the application decide that it is "ok" to finally store the note?

Other mitigations would be to increase the automatic save time or just to turn off that the name of the file will be set automatically.
You can also turn off the local trash.

**Comment by macsunmood** [comment]
> I guess that would mean keeping track of all changes in notes and prevent automatically saving those notes...

Can't you just detect when the user's editing the line, corresponding to the filename ?

**Comment by pbek** [comment]
The filename can even be generated with a script. Only after saving the renaming takes place

**Comment by macsunmood** [comment]
> The filename can even be generated with a script. Only after saving the renaming takes place

Ok, I mean, the line which is responsible for the subsequent renaming of the file. Why not detect when user's editing it? Or am I missing something here?

**Comment by pbek** [comment]
No it's not that easy, basically the note needs to be parsed every time including scripts. And then the global mechanism to save notes would be needed to be delayed, which I don't want to. And then when does the application decide that it is "ok" to finally store the note?

**Comment by macsunmood** [comment]
> And then when does the application decide that it is "ok" to finally store the note?

The file shouldn't be saved until some sufficient time's passed after the last change of the header..
And if the title is always automatically assigned anyway, than a file is already being always parsed and tracked for change in the first header line, isn't it the case?

**Comment by pbek** [comment]
No, it's not always the first header line.

**Comment by macsunmood** [comment]
> No, it's not always the first header line.

What else? From what I've tested, the first heading of the file becomes the file name..
