### ISSUE TITLE
[I] Sub Folder / Title List panels don't remember their heights

### ISSUE THREAD

**Issue by bruceg** [pbek/QOwnNotes#2640]
#### Expected behaviour

When restarting QOwnNotes, I would like the left two panels, containing the sub folder and note title listings, to retain the same dimensions as when it was last open.

#### Actual behaviour

The sub folder listing always resets to a small box size, in which I cannot fit my list of sub folders.

#### Steps to reproduce

Click and drag on the dividing line between the two left boxes to change their size and then restart QOwnNotes.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sat. Oct. 29 22:21:17 2022`
**Version**: `22.10.3`
**Build date**: `Oct 29 2022`
**Build number**: `988`
**Platform**: `linux`
**Operating System**: `Arch Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.6`
**Qt Version (runtime)**: `5.15.6`
**Portable mode**: `no`
**Settings path / key**: `/home/bruce/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/bruce/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_CA`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `158`
**Calendar items**: `67`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://REDACTED`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `24.0.6.1`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: `auto`
**Language codes**: `en_CA, en_CA-large`
**Language names**: `Canadian English (Canada), Canadian English (Canada) [large]`
**Application dictionaries path**: `/home/bruce/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `3`

### Note folder `default`

**id**: `3`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/bruce/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `2`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `yes`
**activeNoteSubFolder name**: `Datadog`
**database file**: `/home/bruce/Nextcloud/Notes/notes.sqlite`

### Cloud connection ``

**id**: `1`
**isCurrent**: `no`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

### Cloud connection `untroubled.org`

**id**: `2`
**isCurrent**: `yes`
**serverUrl**: `REDACTED`
**username**: `Bruce`
**accountId**: *empty*

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `false`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `true`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**EvernoteImport/AttachmentImportCheckBoxChecked** (QString): `true`
**EvernoteImport/ImageImportCheckBoxChecked** (QString): `true`
**EvernoteImport/MetaDataUnCheckedList** (QStringList): `, , note-attributes/subject-date, note-attributes/latitude, note-attributes/longitude, note-attributes/altitude, note-attributes/author, note-attributes/source, note-attributes/source-url, note-attributes/source-application, note-attributes/reminder-order, note-attributes/reminder-time, note-attributes/reminder-done-time, note-attributes/place-name, note-attributes/content-class, note-attributes/application-data`
**EvernoteImportDialog/geometry** (QByteArray): `<binary data>`
**FileDialog/LastPath** (QString): `/home/bruce`
**FileDialog/LastPath-Evernote Import** (QString): `/home/bruce`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2022-10-29T22:12:11.861`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/move-notes** (QString): `16384`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-3/NoteTabNameList** (QString): `Judging Chair comments`
**NoteFolder-3/NoteTabStickinessList**: *empty*
**NoteFolder-3/NoteTabSubFolderPathDataList** (QString): `Camera Club`
**NoteFolder-3/allowDifferentNoteFileName** (QString): `true`
**NoteHistory-3** (QVariantList): `<variant list with 129 item(s)>`
**NoteHistoryCurrentIndex-3** (QString): `128`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**VersionDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `3`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `17`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `false`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `true`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `0`
**notesPath** (QString): `/home/bruce/Nextcloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `2`
**ownCloud/todoCalendarDisplayNameList** (QString): `Personal`
**ownCloud/todoCalendarEnabledList** (QString): `Personal`
**ownCloud/todoCalendarEnabledUrlList** (QString): `https://nextcloud.untroubled.org/remote.php/dav/calendars/Bruce/personal/`
**ownCloud/todoCalendarUrlList** (QString): `https://REDACTED/remote.php/dav/calendars/Bruce/personal/`
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `24.0.6.1`
**previousWorkspace** (QString): `waKfCuAQVUQM`
**recentNoteFolders** (QString): `/home/bruce/.local/share/QOwnNotes/untroubled.org`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-3** (QStringList): `Judging Chair comments, Book Club, Challenge Notes, Challenge review notes, 2022 Reading, Summer Fun Events, AGM Report Notes, Survey Questions, Forte Repair Notes, Router configuration, New Instance Setup, Internet Packages, Laptop RAM, Camera Gear Suitcase, Speaker Stands, NYC Trip To Do, NYC Packing List, Interest in CAPA Judging Course, Kat, Board Meeting Notes, Active SIGs, Bank Account Info, Submit to reddit diysound, rustc ICE, Vector TODO, Note 2021-09-14T09.02.13`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**versionSplitterSizes** (QByteArray): `<binary data>`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-a7kLPs98kQgg/name** (QString): `Full`
**workspace-a7kLPs98kQgg/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-a7kLPs98kQgg/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspace-waKfCuAQVUQM/name** (QString): `Minimal`
**workspace-waKfCuAQVUQM/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-waKfCuAQVUQM/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, a7kLPs98kQgg, waKfCuAQVUQM`

## System environment

**SHELL**: `/usr/bin/fish`
**XDG_CONFIG_DIRS**: `/etc/xdg`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**XDG_MENU_PREFIX**: `xfce-`
**PERLLIB**: `/home/bruce/perl`
**LIBOVERLAY_SCROLLBAR**: `0`
**DESKTOP_SESSION**: `xfce`
**EDITOR**: `vim`
**GTK_MODULES**: `canberra-gtk-module:canberra-gtk-module`
**XDG_SEAT**: `seat0`
**PWD**: `/home/bruce`
**XDG_SESSION_DESKTOP**: `xfce`
**LOGNAME**: `bruce`
**XDG_SESSION_TYPE**: `x11`
**XAUTHORITY**: `/home/bruce/.Xauthority`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/bruce`
**MOTD_SHOWN**: `pam`
**HOME**: `/home/bruce`
**LANG**: `en_CA.UTF-8`
**XDG_CURRENT_DESKTOP**: `XFCE`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**USER**: `bruce`
**SHLVL**: `0`
**BASH_ENV**: `/home/bruce/.bashrc`
**XDG_VTNR**: `7`
**XDG_SESSION_ID**: `2`
**XDG_RUNTIME_DIR**: `/run/user/500`
**DEBUGINFOD_URLS**: `https://debuginfod.archlinux.org `
**XDG_DATA_DIRS**: `/usr/local/share:/usr/share:/var/lib/snapd/desktop:/usr/share`
**PATH**: `/home/bruce/.cargo/bin:/home/bruce/bin:/home/bruce/dev/spac:/usr/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin:/home/bruce/src/go/bin`
**GDMSESSION**: `xfce`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/500/bus`
**MAIL**: `/var/spool/mail/bruce`
**SESSION_MANAGER**: `local/rangerone:@/tmp/.ICE-unix/1553,unix/rangerone:/tmp/.ICE-unix/1553`
**GNOME_KEYRING_CONTROL**: `/run/user/500/keyring`
**SSH_AUTH_SOCK**: `/run/user/500/keyring/ssh`
**DISPLAY**: `:0.0`
</details>

**Comment by pbek** [comment]
Since you can drag all panels around I'm not sure what layout you are using without a screenshot 😁 
But I can't reproduce that if we are talking about panels that are stacked vertically.

**Comment by bruceg** [comment]
Of course, that would help. I am using the "Minimal" layout.

However, I just upgraded from 22.10.3 to 22.11.1 on Arch Linux, and can no longer reproduce the problem. So I guess the problem has now been solved.

**Comment by pbek** [comment]
Great 😊👍🏻
