### ISSUE TITLE
Request: Add keyboard remap option for "Move to beginning / end of line" on a Mac

### ISSUE THREAD

**Issue by nonplayer** [pbek/QOwnNotes#2643]
This isn't a bug report but a request. The home and end keys in the mac version seem to be hard coded. I'm a Windows user who is forced to use a Mac for work. The default Mac implementation of Home and End keys were aggravating to me, so I followed this article to change them: https://discussions.apple.com/thread/251108215?login=true

This fix works for every app on my Mac, except for QOwnNotes, which still enforces Home and End to move to top and bottom of a document, respectively.

I looked to see if it was mappable in the keybinds, but did not see it. I would like to remap it so they function as normally expected to function on every other non-Mac system. It would be cool to see such a function in a future build. Thank you!

If it matters, I am using QOwnNotes 22.11.1

**Comment by pbek** [comment]
Partly duplicate with #1593.

**Comment by nonplayer** [comment]
Thanks. I note that I did search for this first but didn't see that other one somehow.

Anyway as it currently works, using QOwnNotes on a Mac with a full keyboard tends to be just a bit aggravating. It's my go-to editor and note app on Windows, no question about it. But oof, that Home/End mismatch are so jarring. I suspect I'm going to just have to temporarily resort to using nextcloud notes in a browser while on this Mac, although that's not ideal.

Anyway thanks for commenting.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by nonplayer** [comment]
Thank you for looking into this! Unfortunately after updating to 22.11.2, the home/end keys still don't perform as expected. CMD+left/right moves to start/end of line, respectively, but Home/End still move to top/bottom.

I tried two different keyboards on it to confirm.

**Comment by pbek** [comment]
That's bad, then the keys you pressed are not named `Qt::Key_Home` and `Qt::Key_End`. I wonder what key codes the mac keyboard sends...

**Comment by nonplayer** [comment]
If it helps somehow, this is the trick I used to remap the keys on the system level: https://discussions.apple.com/thread/251108215?login=true

```\mkdir -p $HOME/Library/KeyBindings
echo '{
/* Remap Home / End keys to be correct */
"\UF729" = "moveToBeginningOfLine:"; /* Home */
"\UF72B" = "moveToEndOfLine:"; /* End */
"$\UF729" = "moveToBeginningOfLineAndModifySelection:"; /* Shift + Home */
"$\UF72B" = "moveToEndOfLineAndModifySelection:"; /* Shift + End */
"^\UF729" = "moveToBeginningOfDocument:"; /* Ctrl + Home */
"^\UF72B" = "moveToEndOfDocument:"; /* Ctrl + End */
"$^\UF729" = "moveToBeginningOfDocumentAndModifySelection:"; /* Shift + Ctrl + Home */
"$^\UF72B" = "moveToEndOfDocumentAndModifySelection:"; /* Shift + Ctrl + End */
}' > $HOME/Library/KeyBindings/DefaultKeyBinding.dict
```

Ever since putting that dict file in that location, the home/end keys function more like Windows/Linux expectations.

**Comment by pbek** [comment]
I already knew that config. I now even revitalized my macbook, just to find out that it doesn't even have Home and End keys...

**Comment by pbek** [comment]
## 22.11.3
- an issue with selecting with the <kbd>Home</kbd> and <kbd>End</kbd> keys
  was fixed (for [#2643](https://github.com/pbek/QOwnNotes/issues/2643))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by nonplayer** [comment]
That works now! Excellent!

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by pbek** [comment]
> Love it!

Great! :) Is https://github.com/pbek/QOwnNotes/issues/1593#issuecomment-1304544704 also working for you?

**Comment by pbek** [comment]
See you on day 3 then :)

**Comment by pbek** [comment]
Thank you for testing!
