### ISSUE TITLE
[F] Allow Images to be rendered without requiring Alt-Text

### ISSUE THREAD

**Issue by Cho-Chang** [pbek/QOwnNotes#2644]
Presently, QON only renders those Images in Preview Pane that are placed inside '/media' folder, within Root folder, and referenced with

`![](media/Some-Image.png)`

However, some External Editors used to edit a Note place Images in Folders named differently than 'media'.

Please consider allowing images to be rendered as long as they are placed in a Sub-Folder within the Note's root folder, and referenced with

`![](Some-Folder-Name/Some-Image.png)`

This would ~be~ help in Interoperability of notes between different Editors.

**Comment by pbek** [comment]
Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.
Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting Debug in Options).

**Comment by Cho-Chang** [comment]
I posted the request a bit prematurely, without doing due diligence. QON does render images placed in other folders. 

However, it does not render images which do not have ALT-TEXT specified.

So, image is rendered if referenced with: 
`![Alt-Text](Some-Folder-Name/Some-Image.png)`

Not, if referenced with:
`![](Some-Folder-Name/Some-Image.png)`

So, I guess request should be: **Allow Images to be rendered without requiring Alt-Text**.

Nothing of note in Debug data:

```
[00:08:36] [debug] setCurrentNote - 'note': Note: <id>1 <name>"QOwnNotes Clipper" <fileName>"QOwnNotes Clipper.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false - 'updateNoteText': true - 'updateSelectedNote': true
[00:08:37] [debug] added to history: NoteHistoryItem: <noteName>"QOwnNotes Clipper" <noteSubFolderPathData>"" <cursorPosition>6098 <relativeScrollBarPosition>1
[00:09:29] [debug] storing note file: "QOwnNotes Clipper.md"
[00:09:29] [debug] stored note: Note: <id>1 <name>"QOwnNotes Clipper" <fileName>"QOwnNotes Clipper.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false
[00:09:29] [debug] storeUpdatedNotesToDisk - 'count': 1
[00:09:29] [status] Stored 1 note(s) to disk
```

**Comment by Cho-Chang** [comment]
Updating Issue Title to reflect the New Request

**Comment by pbek** [comment]
## 22.11.3
- Markdown images with no `alt` image text are now shown in the preview
  (for [#2644](https://github.com/pbek/QOwnNotes/issues/2644))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Cho-Chang** [comment]
> There now is a new release, could you please test it and report if it works for you?

It does! Thanks a ton!

**Comment by pbek** [comment]
Great, thank you for testing!
