### ISSUE TITLE
Bug: Search prompt in note won't clear up after cancelling the global search

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2645]
#### Expected behaviour
If you cancel global search (e.g. with `Esc`), it clears the prompt up.

#### Actual behaviour
When attempting to perform a global search (with mouseclick, `Ctrl+Shift+F` or `Alt+F`) and entering some keyword..
![image](https://user-images.githubusercontent.com/45285672/199964739-841d3115-aeba-418d-a62d-f155d2f80cee.png)
..and then cancelling it (clicking the "clear" minibutton or hitting the `Esc` key)
![image](https://user-images.githubusercontent.com/45285672/199965478-d0aaad89-c0b7-4543-be22-fb725ed6c209.png)

you'd expect to have the corresponding note search input to be cleared up as well, which doesn't happen:

![image](https://user-images.githubusercontent.com/45285672/199964388-84c3ef5c-314e-49f8-9445-34f838218408.png)

![image](https://user-images.githubusercontent.com/45285672/199968807-fd80e11f-0e50-4652-ba49-1b8a854342d7.png)

So you'll keep browsing the note with this search junk remainder and you'll have to manually clear up the input box in order to get rid of it.
I guess, this is nothing of an expected behaviour.

**Comment by pbek** [comment]
No, that was intended.

**Comment by pbek** [comment]
## 22.11.3
- the in-note search panel is now closed automatically when the text in the
  note-search panel is cleared (for [#2645](https://github.com/pbek/QOwnNotes/issues/2645))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by macsunmood** [comment]
Thanks, seems to work well.

**Comment by pbek** [comment]
Great, thank you for testing!
