### ISSUE TITLE
Make only certain language files (localizations) be downloaded strictly on request

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2648]
Why have almost 17mb QON + 6mb Qt of many language files one will never use, and have them being downloaded on every app update, especially for portable version?..

**Comment by pbek** [comment]
Could you provide a little more context please...

**Comment by macsunmood** [comment]
> Could you provide a little more context please...

Sure, in a portable version (I guess it's the same for the installed one) there are many language files (> than 20 of UI translations) for the languages most people won't need and will never use. This applies both for Qt translations and QON interface as far as I can understand.

I think there's no need to keep all of them and the particular language file should be downloaded only on request (as with updating the app, for example), when the user chooses to use certain language.

**Comment by pbek** [comment]
Sounds like the complete opposite of #2602. 😁  
QOwnNotes automatically uses the language file of the system language, so users can understand the user interface...
So best write a script to remove the stuff you don't need.

**Comment by macsunmood** [comment]
So, do you think a portable app should contain all the possible languages within it's distribution ? I highly doubt so..
