### ISSUE TITLE
Add ability to rename custom schemas in the Settings

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2649]
You can Delete custom schema, but you can't Rename it...

**Comment by pbek** [comment]
You could export and import it again.

**Comment by macsunmood** [comment]
> You could export and import it again.

Well, one can, but it would still be a workaround, not a normal part of the basic user interface with a "Rename" button along with "Remove"..

**Comment by pbek** [comment]
That would increase the minimum width of the user interface (specially in language where words are pretty large). Just press the `Copy` button and give it a new name.

**Comment by macsunmood** [comment]
..or you can arrange the buttons in 2 rows like this:

```
| Copy | | Rename | | Export |
         | Remove | | Import |
```
