### ISSUE TITLE
Double quotes don't work

### ISSUE THREAD

**Issue by mlinchitstest** [pbek/QOwnNotes#265]
You cant use paired double quotes for some reason.
`"test"` is displayed as `test`

It would be nice if you got double quotes to work—people use them all the time. It would also be nice if double quotes were properly "slanted* in the mardown preview/html output.

currently you have to escape them every time you want to use them. I don't think quotes are a special character in markdown, so why aren't they get displayed?

**Comment by pbek** [comment]
please see #261
