### ISSUE TITLE
Change Toolbars UI buttons captions

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2650]
For the sake of clarity, rename buttons from "+ New" and "- Remove" to, say. "+ New Toolbar" and "- Remove Toolbar", because it's not obvious what's exactly added/removed.
![image](https://user-images.githubusercontent.com/45285672/200138090-c7c1466e-1f39-4267-ad84-48eb035e1cc8.png)

**Comment by pbek** [comment]
Hm, there is a tooltip on the buttons...

**Comment by macsunmood** [comment]
When starting to use and trying to do something in that part of the Settings, there's a bunch of confusion at first. This also happened the second time to me personally, when I tried again after a month or so.. 
And the tooltips are so unobvious that I didn't even know they exist until you mentioned them here..

**Comment by pbek** [comment]
Tooltips... Usually that's the first thing I'm looking for.

**Comment by macsunmood** [comment]
> Tooltips... Usually that's the first thing I'm looking for.

I'd rarely meet an app with tooltips for buttons in the settings..
You currently have left-side "+ Insert" / "- Remove" and bottom "+ New" / "- Remove".
![image](https://user-images.githubusercontent.com/45285672/200302335-ec923553-eb33-402a-9fa1-52cd304d5b15.png)

This is confusing.

**Comment by pbek** [comment]
Maybe directly post a request upstream at https://github.com/Skycoder42/QHotkey/issues?

**Comment by macsunmood** [comment]
> Maybe directly post a request upstream at https://github.com/Skycoder42/QHotkey/issues?

Sorry, what's the relation between this and global hotkeys?

**Comment by pbek** [comment]
Sorry, wrong library :)
This is the one: https://gitlab.com/mattbas/Qt-Toolbar-Editor
