### ISSUE TITLE
Add an ability to define "Find tag" shortcut to the Settings

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2651]
There's currently no straight way to get to the "Find tag" input prompt. To achieve this, one must first jump to the tags panel (F7) and then press Shift + Tab. 
Which is too detour workaround.

**Comment by pbek** [comment]
The question remains, isn't that good enough...

**Comment by macsunmood** [comment]
> The question remains, isn't that good enough...

Well, I consider it too detour workaround, making the app less user-friendly. I really doubt many of the users would come up with the clunky workflow you've mentioned, and would be willingly use it, while there are direct shortcuts to other "Find"-s..
