### ISSUE TITLE
[I] Not sure how to reattach panels back into main QoN window

### ISSUE THREAD

**Issue by Weej1** [pbek/QOwnNotes#2652]
Hallo @pbek and all, 

Been sometime since I last reported...anything. So breaking the habit now! Love the auto report system you implemented but still thought it would be nice to add at least an introduction paragraph - hope you have a good rest of your week! 

#### Expected behaviour

I recently installed a script for word counting (note stats) I was trying to rearrange where the panel showed up when it just popped out as a separate window.  I now cannot find a way to reattach the panel back into the main QoN window. I'm on Kubuntu 22.04. I expected that by dragging the separated panel back into QoN it would automatically re-attach itself into one of the 'hotzones' for panels. But it does not do this and just acts like an independent application window.

#### Actual behaviour

Scripting panel popped out of QoN window - not sure how to re-attach back in as it does not seem to do it automatically when hovering panel/window onto panel areas. This is what it currently looks like: 

![image](https://user-images.githubusercontent.com/6381159/200919449-286ad9fa-50ba-457d-856e-4250adc02a3e.png)

#### Steps to reproduce

Install Note stat script on Kubuntu 22.04. 
Remove scripting panel from main window by either dragging it out or clicking a button . You will now have a separate Script window. 
Struggle to re-attach said window back into main window.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[01:28:06] [warning] Wayland does not support QWindow::requestActivate()
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Kam Nov 10 01:59:28 2022`
**Version**: `22.11.4`
**Build date**: `Nov  5 2022`
**Build number**: `993`
**Platform**: `linux`
**Operating System**: `Ubuntu 22.04.1 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.15.3`
**Qt Version (runtime)**: `5.15.3`
**Portable mode**: `no`
**Settings path / key**: `/home/tiny/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/tiny/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1366x768`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `406`
**Calendar items**: `0`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `en_US`
**Language codes**: `en_US`
**Language names**: `American English (United States)`
**Application dictionaries path**: `/home/tiny/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/media/tiny/xfat-data/mega-tinyxl8000/personal/markdown`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/media/tiny/xfat-data/mega-tinyxl8000/personal/markdown/notes.sqlite`

### Note folder `work`

**id**: `2`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/media/tiny/xfat-data/mega-tinyxl8000/work/markdown`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/media/tiny/xfat-data/mega-tinyxl8000/work/markdown/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

### Script `Note stats`

**id**: `1`
**path**: `/home/tiny/.local/share/PBE/QOwnNotes/scripts/note-stats/note-stats.qml`
**variablesJson**: 
```
{
    "charSpaceName": "Chars",
    "readTimeName": "Reading time",
    "readTimeRate": 300,
    "wordsName": "Words"
}
```
**identifier**: `note-stats`
**version**: `0.0.2`
**minAppVersion**: `17.06.3`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `30`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/ColorSchemes** (QString): `EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_-1** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_0** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_1** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_1000** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_1001** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_1002** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_1003** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_1004** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_1005** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_11** (QString): `false`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_12** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_13** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_14** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_15** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_16** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_17** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_18** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_19** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_2** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_21** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_22** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_23** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_24** (QString): `false`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_25** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_28** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_3** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_4** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_8** (QString): `false`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColorEnabled_9** (QString): `false`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_-1** (QColor): `#d3d7cf`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_0** (QColor): `#fafafa`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_1** (QColor): `#fff2e4`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_1000** (QColor): `#eaebea`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_1001** (QColor): `#eaebea`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_1002** (QColor): `#eaebea`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_1003** (QColor): `#eaebea`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_1004** (QColor): `#eaebea`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_1005** (QColor): `#eaebea`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_11** (QColor): `#aaf7ff`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_12** (QColor): `#e4c395`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_13** (QColor): `#729fcf`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_14** (QColor): `#a5b6bd`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_15** (QColor): `#babdb6`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_16** (QColor): `#f1f1f4`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_17** (QColor): `#f1f1f4`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_18** (QColor): `#fce94f`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_19** (QColor): `#e2e7e2`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_2** (QColor): `#fff2e4`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_21** (QColor): `#ebebeb`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_22** (QColor): `#f7f6ff`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_23** (QColor): `#eaebea`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_24** (QColor): `#ffffff`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_25** (QColor): `#fffdef`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_28** (QColor): `#ebebeb`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_3** (QColor): `#ffffff`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_4** (QColor): `#eaebea`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/BackgroundColor_8** (QColor): `#dbf9e5`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/Bold_12** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/Bold_13** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/Bold_14** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/Bold_15** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/Bold_16** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/Bold_17** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/Bold_18** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/Bold_24** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/Bold_8** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/FallbackSchema** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/FontSizeAdaption_-1** (QString): `110`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/FontSizeAdaption_12** (QString): `140`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/FontSizeAdaption_13** (QString): `130`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/FontSizeAdaption_14** (QString): `120`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/FontSizeAdaption_15** (QString): `110`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/FontSizeAdaption_16** (QString): `100`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/FontSizeAdaption_17** (QString): `90`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/FontSizeAdaption_24** (QString): `80`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/FontSizeAdaption_8** (QString): `100`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_-1** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_0** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_1** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_10** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_1000** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_1001** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_1002** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_1003** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_1004** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_1005** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_11** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_12** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_13** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_14** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_15** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_16** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_17** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_18** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_19** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_2** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_20** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_21** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_22** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_23** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_24** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_26** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_3** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_4** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_5** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_6** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_7** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_8** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColorEnabled_9** (QString): `true`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColor_-1** (QColor): `#003039`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColor_0** (QColor): `#0f5955`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColor_1** (QColor): `#fc7e00`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColor_10** (QColor): `#a3007b`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColor_1000** (QColor): `#f92672`
**EditorColorSchema-c4ed4da5-8535-4bf7-8b91-70e55ad9f8be/ForegroundColor_1001** (QString): `@Variant(

**Comment by pbek** [comment]
What happens if you drag it e.g. between the *Note search* and *Note list* panel? Doesn't it try to snap there (it does for me)?

**Comment by pavel-kolesnikov** [comment]
I will answer. On Wayland the main window ignores the panel's window movement over it.
So there's no way the detached panel could be attached back to the window.

**Comment by pbek** [comment]
I tried to reproduce that in Wayland (KDE Plasma 6), but I could not. The panels snapped just fine...

**Comment by pavel-kolesnikov** [comment]
Please see the attached video.
[Запись экрана_20240410_175656.webm](https://github.com/pbek/QOwnNotes/assets/170665/009337e4-b60c-48cf-a756-4a0984f28415)

**Comment by pbek** [comment]
Hm, almost looks like an issue of your desktop environment with Qt apps. 🤔

**Comment by pavel-kolesnikov** [comment]
If it does not steal the focus (e.g. popup window is still dragged by mouse & no normal window decoration present) the drag-and-drop works. If the panel detaches into separate KDE window - it is sealed there, cannot reattach.

If there be an UI button or a shortcut to reset layout to saved version, or reattach the panel forcibly, the problem be less prominent for me.

**Comment by pbek** [comment]
It's not KDE, it's just Qt. 😉
Hm, you could create a new workspace and then attempt to do your changes, then you can fall back to the old layout.

**Comment by pavel-kolesnikov** [comment]
OK. I just would not move the panels :D

**Comment by pbek** [comment]
I wonder if you have the same issue with other Qt apps in your desktop environment...

**Comment by pavel-kolesnikov** [comment]
actually, I had none which use detachable panels. Or they caused no issues.
Any ideas, what can I use to check?

чт, 11 апр. 2024 г., 20:55 Patrizio Bekerle ***@***.***>:

**Comment by pbek** [comment]
To be true, nothing comes to mind. Not many apps go to that extent to make the UI customizable... 🤔
