### ISSUE TITLE
Clear search input on Esc when in the notes list

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2653]
There currently nothing happening when hitting Esc key while being in the notes list, if there is any search input.
The user should be able to cancel current search after browsing the focused notes list panel.

**Comment by pbek** [comment]
## 22.11.5
- if you press <kbd>Escape</kbd> in the note list now the search text in the note search
  input will be cleared (for [#2653](https://github.com/pbek/QOwnNotes/issues/2653))

**Comment by macsunmood** [comment]
Thanks, seems to work well!

**Comment by pbek** [comment]
Great, thank you for testing!
