### ISSUE TITLE
Suggestion for Enhancing the UX for using QOwnNotes for Right-to-Left Languages

### ISSUE THREAD

**Issue by TheBlueQuasar** [pbek/QOwnNotes#2654]
Hello there,
QOwnNotes currently does support rendering text from right-to-left. However, as a user who has notes both in right to left languages, as well as left to right languages, the user experience could get much better. The notes aren't rendered based on the language they're written in, and so **for every time I need to jump from one language to another – one RTL and the other LTR - I have to manually change the rendering direction from the settings. This is not very convenient since it's difficult and time-consuming.**
So I have some suggestions for making the experience better for users who use both RTL and LTR notes:

Few apps do render markdown based on its language, I've only come across Nextcloud notes for Android and Joplin that seamlessly render markdown from right to left if it's written in such language. If such feature can be implemented, it would be fantastic.
But assuming it might not be easy or might depend on used backends, there are still things that massively improve the UX in this scenario. I believe that can be done by making the text rendering direction from the settings more accessible. I can think of either **a keyboard shortcut** for _View text right to left (RTL)_ or a **toolbar item** that could be added to the toolbar from the toolbars section in the settings. This could virtually eliminate all the hassle of changing the settings from the settings menu every time.

QOwnNotes is such great app in every other regard in my opinion, thanks to you and the contributors for providing such a clean and powerful app.

**Comment by pbek** [comment]
Are we talking about the note editor?

It should be able to handle LTR and RTL together, doesn't it @Waqar144?

**Comment by pbek** [comment]
<img width="729" alt="image" src="https://user-images.githubusercontent.com/1798101/201306616-993b6830-19a7-419a-960f-2520a8a803c8.png">

As for the preview... That doesn't work, you can only set it to RTL in the settings.

**Comment by pbek** [comment]
@noureddin, @amirkbrpr do you have any issues?

**Comment by TheBlueQuasar** [comment]
@pbek Thanks for your quick reply!
 I meant for the markdown preview. I understand, but could something like a keyboard shortcut or toolbar item be made available for changing the RTL rendering? That will make it so easy to turn on RTL rendering, that the experience would be virtually as good as can be for user who have notes both in LTR and RTL languages.

**Comment by pbek** [comment]
Ah, ok, the preview.
All that checkbox in the settings does is setting a `body {text-align: right; direction: rtl;}` as CSS style in the html of the preview.
You can even write a script set/unset such a style in a custom action on which you can put a shortcut on.

https://www.qownnotes.org/scripting/methods-and-objects.html#registering-a-custom-action

you can inject html into the preview with:
https://www.qownnotes.org/scripting/hooks.html#notetomarkdownhtmlhook

**Comment by pbek** [comment]
You could submit such a script to the public script repository: https://github.com/qownnotes/scripts#contributing

**Comment by pbek** [comment]
You could even play around with the preview if there is a better way than to bluntly set `<style>body {text-align: right; direction: rtl;}</style>`...

**Comment by amirkbrpr** [comment]
@pbek Hi Patrizio, I'm not sure about the app, but the right-to-left alignment is not supported on the website.

**Comment by Waqar144** [comment]
> It should be able to handle LTR and RTL together, doesn't it @Waqar144?

With some caveats, yes. In the preview it is more difficult. I wonder if litehtml backend handles it better.

**Comment by pbek** [comment]
> @pbek Hi Patrizio, I'm not sure about the app, but the right-to-left alignment is not supported on the website.

about the webpage, I opened: https://github.com/pbek/QOwnNotes/issues/2656

**Comment by TheBlueQuasar** [comment]
> Ah, ok, the preview. All that checkbox in the settings does is setting a `body {text-align: right; direction: rtl;}` as CSS style in the html of the preview. You can even write a script set/unset such a style in a custom action on which you can put a shortcut on.
@pbek The scripting idea does sound interesting. But unfortunately, I cannot implement any of those, I have no knowledge of coding. 
Having a dedicated shortcut or toolbar button for the `body {text-align: right; direction: rtl;}` you described, sounds like a more viable solution and easier to implement. So if it isn't difficult to implement that in the future releases, I would greatly appreciate it if you or any of the contributors to the application code could do that. Still, the decision on whether to implement and include it (and whether it would be a useful feature) is, of course, up to you.

**Comment by noureddin** [comment]
The editor handles the direction and alignment intuitively: any paragraph starting with a letter (after any spaces/numerals/punctuation) takes the direction and alignment defined for it (RTL for Perso-Arabic letters, LTR for Latin).

The preview is a standard HTML viewer, which is always LTR unless explicitly declared otherwise. To include a paragraph or list items or other elements in it, I simply use

```html
<div dir="rtl">
```

… surrounded by newlines before these items, and usually close it with `</div>` surrounded by newline. This is equivalent to the CSS snippet above, but this can be applied more granularly.

I'll try to make a script that, when enabled, sets `dir="rtl"` on any element whose first character with strong direction is RTL, to be similar to how Q*TextEdit handles them (as far as I can 😅).
