### ISSUE TITLE
Show filename in the Tab tooltip

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2655]
Instead of not very useful (this should really belong to help/docs/tips, etc.):
![image](https://user-images.githubusercontent.com/45285672/201335595-c8b52d3b-e0a4-4c9f-914e-e3fe2d56db72.png)

It's better to place the note filename to the Tab tooltip.
It would be even better, to have the user define in the Settings what info to show in the tooltip.

**Comment by pbek** [comment]
> Instead of not very useful (this should really belong to help/docs/tips, etc.):

Where should that exactly be in your opinion? I didn't really see a good place to mention the stickiness. This seemed to be the best place.

> It's better to place the note filename to the Tab tooltip.

You can just hover the item in the note-list.

**Comment by macsunmood** [comment]
> Where should that exactly be in your opinion? I didn't really see a good place to mention the stickiness. This seemed to be the best place.
Well, the same as with shortcuts: you can mention it both in the Cheatsheet on the website and in the Menu action item for Current Tab, for instance.

> You can just hover the item in the note-list.
I knew you'll say this :) You can't always easily seek it, since if the current tabs' note doesn't belong to the focused tag, in won't be listed in the Note List (I guess, it's the same with the subfolders)

**Comment by pbek** [comment]
I think you are a perfect candidate for the *Scripting panel* to show all the information about the current note that your heart desires. 😀

**Comment by macsunmood** [comment]
> I think you are a perfect candidate for the _Scripting panel_ to show all the information about the current note that your heart desires. 😀 There already is a word count script that uses it.

This won't be a simplification of the UX and usability (which quick tooltip actually is), but rather a complication (panel needs to be turned on, it takes space, etc.)

The script for note info could be made, but not for this particular aspect regarding the Tooltip.
