### ISSUE TITLE
Webpage doesn't RTL for fa/ar any more

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#2656]
https://www.qownnotes.org/fa/ and https://www.qownnotes.org/ar/ doen't have the `dir="rtl"` any more.

**Comment by pbek** [comment]
..should have been set in <https://github.com/pbek/QOwnNotes/blob/develop/webpage/package.json#L13>

**Comment by pbek** [comment]
Strage, I can see the `dir="rtl"` now!

**Comment by pbek** [comment]
@amirkbrpr, can you see the text in RTL on the ar/fr webpages now?

**Comment by amirkbrpr** [comment]
It doesn't work for Arabic, too.

**Comment by pbek** [comment]
Looks fine to me:

![image](https://user-images.githubusercontent.com/1798101/201471502-212e4a90-82fa-4d42-b270-c67307e60993.png)

How does it look to you?

**Comment by amirkbrpr** [comment]
Everything is fine now. Thanks so much!

**Comment by pbek** [comment]
I've no idea what was wrong. The tag was missing, then it was there. But the container runs since more than one day..
