### ISSUE TITLE
Markdown sometimes misinterprets single quotes

### ISSUE THREAD

**Issue by GarryFlemings** [pbek/QOwnNotes#2657]
#### Relevant file
[t.txt](https://github.com/pbek/QOwnNotes/files/9997732/t.txt)

#### Expected behaviour

preview looks like:
![image](https://user-images.githubusercontent.com/14095071/201498786-76a7892a-9e43-4075-b077-a1c82167e767.png)

This first image is the preview pane with "relevant file" in the source frame, except that "bash" is removed from the opening back-tick line for the first code block.

Perhaps that "bash" and a single quote are both necessary for the unwanted condition.

Two code blocks have green background. Three areas of normal text have white background.

#### Actual behaviour

preview looks like:
![image](https://user-images.githubusercontent.com/14095071/201498733-4fc8a6c0-44b4-4013-b8e0-8bbdf722fd6a.png)

This second image is a screenshot with "relevant file" in the source frame, including the "bash" on the opening back-tick line for the first code block.

In the QOwnNotes preview pane on my screen:

* In the first code block, the rendering appears may use two font weights in the word "We're". The first three characters (ending with the single quote) seem slightly heavier. The last two characters (after the single quote) seem lighter.
* The green background delimiting the first code block starts as expected (before "We're") and ends with the opening back-tick line for the second code block (before "I'm"). Thus, it erroneously includes the "next text" line.
* The line "I'm a code block." shows without the green background (that is, outside a code block).
* The second code block starts with the ending back-ticks of the second block in source and continues to the end of file. The "last text" line should not be in the code block.

The condition is troubling because the source frame shows a more accurate rendering than the preview pane. In a note with many code blocks, possibly many blocks of text are mischaractized (normal text looking as though in a code block and vice versa).

#### Alternative steps I've considered

I learned more about this condition in creating this write-up. I had not noticed the relevance of "bash". Without that, this was baffling.

Workaround: Now that I know the effect of "bash", I can stop using it. The only thing it does for me is highlight relevant bash words in a different color. For the code blocks I'm working with, those highlights are of very limited value. I can remove such annotations; I'll probably be entirely okay.

If those annotations are more important to other segments of your users, it might be worth estimating the time required to change the condition (or even implementing a change).

Absent changing the condition somehow, perhaps we'd want to add something about it in the documentation.

**Comment by pbek** [comment]
I'm sorry, I'm not sure what this issue is report is about. I think your examples got lost in the markdown formatting. Do you maybe have an example markdown file with some explanation what is rendered incorrectly in the preview?

**Comment by GarryFlemings** [comment]
Sigh. They say an author's responsibility is not to be understandable, but to be impossible to misunderstand. I failed that higher standard; your query is entirely understandable.

The example Markdown file is the one in the "relevant file" section. You didn't and couldn't know that because GitHub provided you with no way to see the source file. My bad. I replaced that part of the Issue with an upload of the text file. I suspect your download will solve all problems. Please let me know.

If you paste that text file into the QOwnNotes application, I hope the other two sections will make better sense.

Thanks for your patience.

**Comment by pbek** [comment]
Thank you for your example and your elaborate writing style! 😁 
There are ways to fence the code on github, like leading with 4 spaces. 😉 

@Waqar144, did you see this...

    first text
    
    ```bash
    We're in a code block.
    ```
    
    
    next text
    
    ```
    I'm a code block.
    ```
    
    last text

... produces:

![image](https://user-images.githubusercontent.com/1798101/201595306-2f41b092-447d-444b-bf1a-de16a6f4ff48.png)

**Comment by Waqar144** [comment]
#2659 PR

However, if you are not writing bash, then probably it is a good idea to not put `bash` with the code block.

**Comment by pbek** [comment]
@Waqar144, will you fix the PR or should I? https://github.com/pbek/QOwnNotes/actions/runs/3460256746/jobs/5776603664#step:19:4539

**Comment by Waqar144** [comment]
pushed a fix

**Comment by pbek** [comment]
## 22.11.6
- a preview issue with quotes in code blocks was fixed
  (for [#2657](https://github.com/pbek/QOwnNotes/issues/2657), thank you, @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
@Waqar144, unfortunately your change still breaks a lot of build system, like https://build.opensuse.org/package/live_build_log/home:pbek:QOwnNotes/desktop/openSUSE_Leap_42.3/x86_64

**Comment by Waqar144** [comment]
Indeed, but its just crazy.

**Comment by pbek** [comment]
@Waqar144 
```
[   57s] helpers/codetohtmlconverter.cpp: In static member function 'static int CodeToHtmlConverter::highlightStringLiterals(StringView, QChar, QString&, int)':
[   57s] helpers/codetohtmlconverter.cpp:450:57: error: no match for 'operator[]' (operand types are 'const QStringRef' and 'int')
[   57s]      if (!input.isEmpty() && i >= input.length() && input[input.length() - 1] == QLatin1Char('\n')) {
[   57s]                                                          ^
```

**Comment by pbek** [comment]
`QStringRef::operator[](int position)` was introduced in Qt 5.7...

**Comment by GarryFlemings** [comment]
I tried all I could think to do to break it. It passed every test.

🏆 

You guys fixed this and did it very quickly! I feel guilty this isn't part of the reason you're on payroll somewhere!

**Comment by pbek** [comment]
Hehe. Thank you for testing. 😁
