### ISSUE TITLE
Clicking folder displays a random (?) note.

### ISSUE THREAD

**Issue by xpufx** [pbek/QOwnNotes#2658]
When using Folders, clicking a folder name brings up a note. The note is not one of the ones in the folder. I can't determine how it's picked but it's always the same note per folder. So not really random random.

It actually looks like a bunch of notes in order from a particular -but not first or last or otherwise special- folder. The notes themselves are at the bottom of that folder.

I am not sure if this behavior is expected since there's a feature to go to the next previous note and the navigation pane does not seem to try to keep in sync with that.

QOwnNotes - version 22.11.5 - TuxFamily - build 994
Running on opensuse tumbleweed.

**Comment by pbek** [comment]
I'm not sure what we are talking about.

Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.

Can you please describe what you expected, what the actual behavior was and step by step what you did (and maybe share a screenshot)?

**Comment by xpufx** [comment]
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mon Nov 14 09:32:14 2022`
**Version**: `22.11.5`
**Build date**: `Nov 11 2022`
**Build number**: `994`
**Platform**: `linux`
**Operating System**: `KDE Flatpak runtime`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `TuxFamily`
**Qt Version (build)**: `5.15.6`
**Qt Version (runtime)**: `5.15.6`
**Portable mode**: `no`
**Settings path / key**: `/home/MYUSERNAME/.var/app/org.qownnotes.QOwnNotes/config/PBE/QOwnNotes.conf`
**Application database path**: `/home/MYUSERNAME/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `2560x1440`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `67`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://next.MYDOMAIN.com`
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_AU, en_BS, en_BZ, en_CA, en_GB, en_GH, en_IE, en_IN, en_JM, en_MW, en_NA, en_NZ, en_PH, en_TT, en_US, en_ZA, en_ZW`
**Language names**: `Australian English (Australia), English (Bahamas), English (Belize), Canadian English (Canada), British English (United Kingdom), English (Ghana), English (Ireland), English (India), English (Jamaica), English (Malawi), English (Namibia), English (New Zealand), English (Philippines), English (Trinidad & Tobago), American English (United States), English (South Africa), English (Zimbabwe)`
**Application dictionaries path**: `/home/MYUSERNAME/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Notes`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/MYUSERNAME/Documents/Syncthing/Notes`
**remotePath**: *empty*
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: `Work`
**database file**: `/home/MYUSERNAME/Documents/Syncthing/Notes/notes.sqlite`

## Cloud connections

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://next.MYDOMAIN.com`
**username**: `o@MYDOMAIN.com`
**accountId**: `o@MYDOMAIN.com`

## Enabled scripts

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/editorWidthMode** (QString): `2`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (bool): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `/home/MYUSERNAME/Downloads/simplenotes`
**FileDialog/LastPath-ImportTextFiles** (QString): `/home/MYUSERNAME/Downloads/simplenotes`
**LastUpdateCheck** (QDateTime): `2022-11-14T09:29:41.619`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Hack,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Hack,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (QString): `600`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/move-notes** (QString): `16384`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteDialog/tabWidgetIndex** (int): `0`
**NoteFolder-1/NoteTabNameList** (QString): `test`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteHistory-1** (QVariantList): `<variant list with 11 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `10`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `true`
**enableSocketServer** (QString): `false`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `true`
**itemHeight** (QString): `18`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `true`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `0`
**notesPath** (QString): `/home/MYUSERNAME/Documents/Syncthing/Notes`
**notifyAllExternalModifications** (QString): `true`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**recentNoteFolders** (QStringList): `/home/MYUSERNAME/Documents/Notes, /home/MYUSERNAME/Nextcloud/Documents/Notes`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2022-11-13T19.24.53, Note 2022-11-12T19.20.24, Note 2022-11-12T19.18.12, Note 2022-11-12T19.17.46`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `true`
**useUNIXNewline** (QString): `true`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**XDG_RUNTIME_DIR**: `/run/user/1000`
**container**: `flatpak`
**AT_SPI_BUS_ADDRESS**: `unix:path=/run/flatpak/at-spi-bus`
**AUDIODRIVER**: `pulseaudio`
**CPU**: `x86_64`
**CSHEDIT**: `emacs`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/flatpak/bus`
**DESKTOP_SESSION**: `plasma5`
**DISPLAY**: `:0`
**FLATPAK_ID**: `org.qownnotes.QOwnNotes`
**FLATPAK_SANDBOX_DIR**: `/home/MYUSERNAME/.var/app/org.qownnotes.QOwnNotes/sandbox`
**FROM_HEADER**: *empty*
**GDMFLEXISERVER**: `/usr/libexec/lightdm/gdmflexiserver`
**GDMSESSION**: `plasma5`
**GDM_LANG**: `en_US.utf8`
**GI_TYPELIB_PATH**: `/app/lib/girepository-1.0`
**GST_PLUGIN_PATH**: `/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0`
**GTK2_RC_FILES**: `/etc/gtk-2.0/gtkrc:/home/MYUSERNAME/.gtkrc-2.0:/home/MYUSERNAME/.config/gtkrc-2.0`
**GTK_IM_MODULE**: `cedilla`
**GTK_MODULES**: `canberra-gtk-module`
**GTK_RC_FILES**: `/etc/gtk/gtkrc:/home/MYUSERNAME/.gtkrc:/home/MYUSERNAME/.config/gtkrc`
**G_BROKEN_FILENAMES**: `1`
**G_FILENAME_ENCODING**: `@locale,UTF-8,ISO-8859-15,CP1252`
**HISTSIZE**: `1000`
**HOME**: `/home/MYUSERNAME`
**HOST**: `t480s`
**HOSTNAME**: `t480s`
**HOSTTYPE**: `x86_64`
**INVOCATION_ID**: `78b3711f89b746ad831696d49c109614`
**JAVA_BINDIR**: `/usr/lib64/jvm/jre-openjdk/bin`
**JAVA_HOME**: `/usr/lib64/jvm/jre-openjdk`
**JAVA_ROOT**: `/usr/lib64/jvm/jre-openjdk`
**JOURNAL_STREAM**: `8:32108`
**JRE_HOME**: `/usr/lib64/jvm/java-11-openjdk-11`
**KDE_APPLICATIONS_AS_SCOPE**: `1`
**KDE_FORK_SLAVES**: `1`
**KDE_FULL_SESSION**: `true`
**KDE_SESSION_UID**: `1000`
**KDE_SESSION_VERSION**: `5`
**LANG**: `en_US.utf8`
**LC_TIME**: `en_US.UTF-8`
**LD_LIBRARY_PATH**: *empty*
**LESS**: `-M -I -R`
**LESSCLOSE**: `lessclose.sh %s %s`
**LESSKEY**: `/usr/etc/lesskey.bin`
**LESSOPEN**: `lessopen.sh %s`
**LESS_ADVANCED_PREPROCESSOR**: `no`
**LIBVA_DRIVER_NAME**: `iHD`
**LOGNAME**: `MYUSERNAME`
**MACHTYPE**: `x86_64`
**MAIL**: `/var/mail/MYUSERNAME`
**MANAGERPID**: `2289`
**MANPATH**: `/usr/local/man:/usr/share/man`
**MANPATHISSET**: `yes`
**MINICOM**: `-c on`
**MORE**: `-sl`
**OLDPWD**: `/home/MYUSERNAME`
**OSTYPE**: `linux-gnu`
**PAGER**: `less`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**PATH**: `/app/bin:/usr/bin`
**PROFILEREAD**: `true`
**PS1**: `[📦 $FLATPAK_ID \W]\$ `
**PWD**: `/home/MYUSERNAME`
**PYTHONSTARTUP**: `/etc/pythonstart`
**QEMU_AUDIO_DRV**: `pa`
**QML2_IMPORT_PATH**: `/app/lib64/qml:/app/lib/qml`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**QT_IM_MODULE**: `xim`
**QT_IM_SWITCHER**: `imsw-multi`
**QT_PLUGIN_PATH**: `/app/lib64/plugins:/app/lib/plugins:/usr/share/runtime/lib/plugins`
**SESSION_MANAGER**: `local/t480s:@/tmp/.ICE-unix/2434,unix/t480s:/tmp/.ICE-unix/2434`
**SHELL**: `/bin/sh`
**SHLVL**: `0`
**SSH_AGENT_PID**: `2380`
**SSH_ASKPASS**: `/usr/libexec/ssh/ssh-askpass`
**SSH_AUTH_SOCK**: `/tmp/ssh-XXXXXXqEHYXt/agent.2307`
**SYSTEMD_EXEC_PID**: `2541`
**TERM**: `xterm`
**USER**: `MYUSERNAME`
**VENDOR**: `suse`
**WINDOWMANAGER**: `/usr/bin/startplasma-x11`
**XAUTHLOCALHOSTNAME**: `t480s`
**XAUTHORITY**: `/run/flatpak/Xauthority`
**XCURSOR_SIZE**: `24`
**XCURSOR_THEME**: `breeze_cursors`
**XDG_CACHE_HOME**: `/home/MYUSERNAME/.var/app/org.qownnotes.QOwnNotes/cache`
**XDG_CONFIG_DIRS**: `/app/etc/xdg:/etc/xdg`
**XDG_CONFIG_HOME**: `/home/MYUSERNAME/.var/app/org.qownnotes.QOwnNotes/config`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_DATA_DIRS**: `/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share`
**XDG_DATA_HOME**: `/home/MYUSERNAME/.var/app/org.qownnotes.QOwnNotes/data`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/MYUSERNAME`
**XDG_SEAT**: `seat0`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_DESKTOP**: `plasma5`
**XDG_SESSION_ID**: `3`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**XDG_SESSION_TYPE**: `x11`
**XDG_STATE_HOME**: `/home/MYUSERNAME/.var/app/org.qownnotes.QOwnNotes/.local/state`
**XDG_VTNR**: `7`
**XKEYSYMDB**: `/usr/X11R6/lib/X11/XKeysymDB`
**XMODIFIERS**: `@im=local`
**XNLSPATH**: `/usr/share/X11/nls`
**XSESSION_IS_UP**: `yes`
**__EGL_EXTERNAL_PLATFORM_CONFIG_DIRS**: `/etc/egl/egl_external_platform.d:/usr/lib/x86_64-linux-gnu/GL/egl/egl_external_platform.d:/usr/share/egl/egl_external_platform.d`

**Comment by xpufx** [comment]
![Screenshot_20221114_093741](https://user-images.githubusercontent.com/25581961/201592559-7540a190-fa84-4415-b0e4-f3e83587cd8c.png)

Above please pay attention to the structure of the Journal folder.

![Screenshot_20221114_093655](https://user-images.githubusercontent.com/25581961/201592647-94562066-9e26-4316-9036-cb7864b8877c.png)

Now when I click the Journal folder, this note called "SUPERBOX" comes up. You will notice that this note is NOT in the Journal folder at all. 

![Screenshot_20221114_093717](https://user-images.githubusercontent.com/25581961/201593385-ddaf6ec1-11df-4ae0-bd5e-97544da76530.png)


When I click the next folder in the hierarchy, another note comes up, which also is not in the Journal folder.

![Screenshot_20221114_093729](https://user-images.githubusercontent.com/25581961/201593015-38437981-1685-469a-aed5-3df308b1dbb0.png)


The note called 12.Nov.2022 is the only actual note in the Journal folder hierarchy.

![Screenshot_20221114_094955](https://user-images.githubusercontent.com/25581961/201593843-f7c670db-55b0-4c27-99b3-f1515958adc5.png)

Finally. The Uncategorized directory where the notes being displayed are actually located.

**Comment by pbek** [comment]
> enableNoteTree (QString): true

I guess you are talking about the experimental #790 (WIP)... That feature is not done at all. 😉

**Comment by xpufx** [comment]
> > enableNoteTree (QString): true
> 
> I guess you are talking about the experimental #790 (WIP)... That feature is not done at all. wink

Thanks for the pointer. I turned off "Instead of a note list use a note tree with all the subfolders" in the settings and now it less nice but  acts a lot more predictably. Thanks.
