### ISSUE TITLE
Ini Code Block Syntax Highlighting not styled correctly

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#2667]
@Waqar144, the value part doesn't seem to be formatted as code block, was that on purpose?

    ```ini
    test1=test2
    ``` 

![image](https://user-images.githubusercontent.com/1798101/203067743-289b6604-11af-45d9-843f-86f12abe258c.png)

**Comment by Waqar144** [comment]
probably a bug

**Comment by Waqar144** [comment]
https://github.com/pbek/qmarkdowntextedit/pull/175

**Comment by pbek** [comment]
Thank you very much, works great!

**Comment by pbek** [comment]
## 22.11.7
- a highlighting issue with ini code blocks was fixed
  (for [#2667](https://github.com/pbek/QOwnNotes/issues/2667), thank you, @Waqar144)

**Comment by pbek** [comment]
@Waqar144, I still got this strange issue tho...

![image](https://user-images.githubusercontent.com/1798101/203253487-b0904948-3498-46e5-a25a-fc49edc9331a.png)

**Comment by pbek** [comment]
I opened #2670 for that.
