### ISSUE TITLE
How to transfer QOwnNotes settings to a new computer?

### ISSUE THREAD

**Issue by nonplayer** [pbek/QOwnNotes#2668]
Just a question. I backed up my whole system then reinstalled my OS (Windows 10) after a hardware upgrade. I copied over the older QOwnNotes folder, hoping it would save all my settings, but unfortunately opening it is like a new install. I had a _lot_ of customization to my settings that I'd rather not have to manually add back (font choices, etc). How do I transfer those? Where are they stored on the hard disk?

**Comment by pbek** [comment]
You can try exporting them in the General Settings. Or you could export the Registry Tree on Windows. Or you could just stay in Portable Mode (but that's too late for you).

**Comment by nonplayer** [comment]
I thought was a portable mode install. And none of the settings transferred.

**Comment by pbek** [comment]
There is no "install" of portable mode. You simply use a cli parameter to activate it. In portable mode all the settings are in the folder QOwnNotes is run from.

**Comment by nonplayer** [comment]
And now when I download the portable mode, it seems to detect the new, wrong install settings already. That's really weird. How do I make it not do that? Keeping settings in the registry is not something I want to do, because it makes backups and transfers unnecessarily complicated. I thought I had been running in Portable mode for years. Is there a way to switch over?

**Comment by pbek** [comment]
Just look in the "Portable mode" settings on how to use it.

**Comment by pbek** [comment]
> Is there a way to switch over?

Export and import settings in QOwnNotes.

**Comment by nonplayer** [comment]
I found https://www.qownnotes.org/blog/2016-09-18-Portable-mode.html#portable-mode

It says:

> On Windows there is a QOwnNotesPortable.exe in your release path to start QOwnNotes in portable mode.

There is no such file in the windows zip I just now downloaded from this project. Only the batch file. I have run the exe from the dos prompt with the extension but it doesn't make a difference

![image](https://user-images.githubusercontent.com/5161177/203106007-41a7440b-43da-49d5-a8c9-eb910b900ac7.png)

**Comment by pbek** [comment]
> On Windows there is a QOwnNotesPortable.exe in your release path to start QOwnNotes in portable mode.

the exe was dropped years ago because of constant virus false positives, just use my documentation link

**Comment by nonplayer** [comment]
> Or https://www.qownnotes.org/installation/windows.html#portable-mode

This works better. Thanks.

**Comment by pbek** [comment]
the exe just executed QOwnNotes with the parameter

**Comment by nonplayer** [comment]
Just a note, your website search is linking the user to outdated information:

![image](https://user-images.githubusercontent.com/5161177/203107282-b7751dfa-be88-4094-9698-d11ec0692977.png)

That blog post is the first result, might be good to remove or update it.

**Comment by pbek** [comment]
Well, that's a >6y old Blog post, not the documentation! :) But I mentioned it there now...

**Comment by nonplayer** [comment]
Thanks for the assist!
