### ISSUE TITLE
Quotes are not formatted

### ISSUE THREAD

**Issue by GoustiFruit** [pbek/QOwnNotes#2669]
In the editor panel, quotes are formatted according to the color scheme.
But they aren't in the preview panel (only "tabbed", no front or background color is applied)

![Screenshot_20221122_120141](https://user-images.githubusercontent.com/52235969/203298122-06b02bc0-dfbd-4444-a159-c21a48ec0851.png)

**Comment by pbek** [comment]
Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.

**Comment by pbek** [comment]
And what quotes are we talking about? Do you have an example?

**Comment by pbek** [comment]
You are using...
![image](https://user-images.githubusercontent.com/1798101/203308812-264fecb5-8394-48ac-bd1a-2d3b17f304ba.png)
...aren't you?

**Comment by pbek** [comment]
Currently that feature is just implemented for the **Editor** and doesn't work together with the *Use editor highlighting styles also for the preview* setting of the Preview.

**Comment by pbek** [comment]
I can attempt to do an (incomplete) implementation of overriding all styles inside a blockquote.

**Comment by GoustiFruit** [comment]
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `mar. nov. 22 15:53:32 2022`
**Version**: `22.11.7`
**Build date**: `Nov 21 2022`
**Build number**: `996`
**Platform**: `linux`
**Operating System**: `Linux 6.0.9-arch1-1`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.7`
**Qt Version (runtime)**: `5.15.7`
**Portable mode**: `no`
**Settings path / key**: `/home/gousti/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/gousti/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`, `--allow-multiple-instances`
**Qt Debug**: `0`
**Locale (system)**: `fr_FR`
**Locale (interface)**: *empty*
**Primary screen resolution**: `2560x1440`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `31`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: `auto`
**Language codes**: `en_AG, en_BS, en_BW, en_BZ, en_DK, en_GB, en_GB-large, en_GH, en_HK, en_IE, en_IN, en_JM, en_NA, en_NG, en_NZ, en_SG, en_TT, en_US, en_US-large, en_ZA, en_ZW, fr_BE, fr_CA, fr_CH, fr_FR, fr_LU`
**Language names**: `English (Antigua & Barbuda), English (Bahamas), English (Botswana), English (Belize), English (Denmark), British English (United Kingdom), British English (United Kingdom) [grand], English (Ghana), English (Hong Kong SAR China), English (Ireland), English (India), English (Jamaica), English (Namibia), English (Nigeria), English (New Zealand), English (Singapore), English (Trinidad & Tobago), American English (United States), American English (United States) [grand], English (South Africa), English (Zimbabwe), français (Belgique), français canadien (Canada), français suisse (Suisse), français (France), français (Luxembourg)`
**Application dictionaries path**: `/home/gousti/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Mes notes`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/gousti/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `yes`
**activeNoteSubFolder name**: `Idées`
**database file**: `/home/gousti/Notes/notes.sqlite`

## Cloud connections

### Cloud connection `Par défaut`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

## Enabled scripts

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/ColorSchemes**: *empty*
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `true`
**Editor/showLineNumbers** (QString): `true`
**Editor/useTabIndent** (QString): `true`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `/home/gousti/Documents/JOP`
**FileDialog/LastPath-ImportTextFiles** (QString): `/home/gousti/Documents/JOP`
**FileDialog/LastPath-Joplin Import** (QString): `/home/gousti/Documents/JOP`
**JoplinImport/AttachmentImportCheckBoxChecked** (QString): `true`
**JoplinImport/FolderImportCheckBoxChecked** (QString): `true`
**JoplinImport/ImageImportCheckBoxChecked** (QString): `true`
**JoplinImport/MetadataImportCheckBoxChecked** (QString): `false`
**JoplinImport/TagImportCheckBoxChecked** (QString): `true`
**JoplinImportDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2022-11-22T15:52:22.772`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Entraînement vélo, Yunohost - Fujitsu Lifebook S6420 - Freebox, QOwnNotes, Joplin, MarkDown`
**MainWindow/noteTextEdit.code.font** (QString): `Source Code Pro,10,-1,0,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,11,-1,0,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Hack,10,-1,7,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (QString): `600`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/insert-media-use-existing-image** (QString): `16384`
**MessageBoxOverride/move-notes** (QString): `16384`
**MessageBoxOverride/remove-folders** (QString): `16384`
**MessageBoxOverride/remove-notes** (QString): `16384`
**NoteFolder-1/NoteTabNameList** (QString): `Idées diverses et variées`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QString): `Idées`
**NoteFolder-1/allowDifferentNoteFileName** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 70 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `69`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `true`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `23`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `0`
**notesPath** (QString): `/home/gousti/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `0c31122026c1472597640f61f76a3d85, c8ead703ea64499795dd8b6d440b1e83, 147d4d1866834727b39a7096c7753b13, 143e24072bdf45b19dbc60e5abc2e6d7, 90dd479de5a649079dbdd56db3fc2947, 42f69e58083442ea9f6b5241e2525408, 7e03aa1aea6d42be837a9d7b1b8231fd, 6dfc85cc1d5a4bf3bb077ae4e2f48cb4, 1dd617b7f27f49cdb628b83b54a06920`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `barre d'outils principale`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `barre d'outils de formatage`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `barre d'outils d'insertion`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `barre d'outils de chiffrement`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `barre d'outils de fenêtre`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quitter la barre d’outils`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Interface minimale`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**BROWSER**: `firefox`
**EDITOR**: `nano`
**HOME**: `/home/gousti`
**LANG**: `fr_FR.UTF-8`
**LC_ADDRESS**: `fr_FR.UTF-8`
**LC_IDENTIFICATION**: `fr_FR.UTF-8`
**LC_MEASUREMENT**: `fr_FR.UTF-8`
**LC_MONETARY**: `fr_FR.UTF-8`
**LC_NAME**: `fr_FR.UTF-8`
**LC_NUMERIC**: `fr_FR.UTF-8`
**LC_PAPER**: `fr_FR.UTF-8`
**LC_TELEPHONE**: `fr_FR.UTF-8`
**LC_TIME**: `fr_FR.UTF-8`
**LOGNAME**: `gousti`
**MAIL**: `/var/spool/mail/gousti`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin`
**QT_QPA_PLATFORMTHEME**: `qt5ct`
**QT_STYLE_OVERRIDE**: `kvantum`
**SHELL**: `/bin/bash`
**SYSTEMD_EXEC_PID**: `885`
**USER**: `gousti`
**XDG_DATA_DIRS**: `/home/gousti/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**DESKTOP_SESSION**: `plasma`
**DISPLAY**: `:0`
**GTK2_RC_FILES**: `/etc/gtk-2.0/gtkrc:/home/gousti/.gtkrc-2.0:/home/gousti/.config/gtkrc-2.0`
**GTK3_MODULES**: `xapp-gtk3-module`
**GTK_MODULES**: `canberra-gtk-module`
**GTK_RC_FILES**: `/etc/gtk/gtkrc:/home/gousti/.gtkrc:/home/gousti/.config/gtkrc`
**HISTCONTROL**: `ignoreboth:erasedups`
**KDE_APPLICATIONS_AS_SCOPE**: `1`
**KDE_FULL_SESSION**: `true`
**KDE_SESSION_UID**: `1000`
**KDE_SESSION_VERSION**: `5`
**MOTD_SHOWN**: `pam`
**PAGER**: `most`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**PWD**: `/home/gousti`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**SESSION_MANAGER**: `local/PC-JB:@/tmp/.ICE-unix/836,unix/PC-JB:/tmp/.ICE-unix/836`
**SHLVL**: `0`
**VISUAL**: `nano`
**XAUTHORITY**: `/home/gousti/.Xauthority`
**XCURSOR_SIZE**: `24`
**XCURSOR_THEME**: `Breeze_Snow`
**XDG_CONFIG_DIRS**: `/home/gousti/.config/kdedefaults:/etc/xdg`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_SEAT**: `seat0`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_DESKTOP**: `KDE`
**XDG_SESSION_ID**: `1`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**XDG_SESSION_TYPE**: `x11`
**XDG_VTNR**: `1`
**MANAGERPID**: `702`
**INVOCATION_ID**: `73ed568bdddb4824b34718cbfad03352`
**JOURNAL_STREAM**: `8:23118`
**LANGUAGE**: *empty*

**Comment by pbek** [comment]
## 22.11.8
- an attempt was made to override styles inside blockquotes in the preview
  when blockquotes are fully highlighted in the note editor

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by GoustiFruit** [comment]
I'm very new to QOwnNotes as well as using MarkDown, I'm impressed at how quickly you reply (and fix the glitches :-)).
Seems to work ! 👍

![Screenshot_20221123_183757](https://user-images.githubusercontent.com/52235969/203614057-13ecbf24-e9e3-40a1-aad1-908551847509.png)


PS: I installed it on an Arch based distribution (Arcolinux, thanks to the Chaotic-Aur repo), but as the last version wasn't updated yet in the AUR, I switched to the AppImage...

**Comment by pbek** [comment]
Great, thank you for testing!

> but as the last version wasn't updated yet in the AUR,

strange, it was immediately (and still is) on https://aur.archlinux.org/packages/qownnotes

**Comment by GoustiFruit** [comment]
It was not, at the time I tried: maybe there is a slight delay between the AUR sources.
Anyway, I'm fine with the AppImages because I install them in my home, and whenever I need to reinstall my system (distro-hopping :-p), those are already working about of the box.
