### ISSUE TITLE
[Feature Request] Folder type in script settings.

### ISSUE THREAD

**Issue by bvn9ne** [pbek/QOwnNotes#2672]
Like the title says, I would like to be able to select a folder (for outputting) much like the file type. Sorry if I didn't do this correctly.

**Comment by pbek** [comment]
We are talking about a folder settings type for https://www.qownnotes.org/scripting/methods-and-objects.html#registering-script-settings-variables

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
