### ISSUE TITLE
[F] Allow Intermediate Font Sizes

### ISSUE THREAD

**Issue by Cho-Chang** [pbek/QOwnNotes#2674]
Please consider allowing choice of Intermediate Font sizes in Note Editor. 

Ex, 10.5, 11.5, etc

**Comment by pbek** [comment]
What would be the use case?

https://doc.qt.io/qt-5/qfont.html#setPointSizeF is not supported on all platforms and I haven't seen anything using float font sizes.

**Comment by Cho-Chang** [comment]
Nothing specific. Just that with some fonts, difference between Text size is quite noticeable at n, and n+1 font sizes. 

Ex, with Dejavu Sans Mono

![1](https://user-images.githubusercontent.com/85818525/204637906-bdb81f55-5abb-4235-9dac-d8ffe652ee18.png)
![2](https://user-images.githubusercontent.com/85818525/204637916-114f97fc-6ee2-4646-a138-945c9259e5c5.png)

Here, 10px is difficult to read, but 11px is too large. 10.5px would have been perfect here.
