### ISSUE TITLE
[Help/Feature Request] Run Command Line Options in Background

### ISSUE THREAD

**Issue by Cho-Chang** [pbek/QOwnNotes#2677]
I want to export all my Notes as PDF, every `n` Hours, with a bash script.

`QOwnNotes --action action_Export_note_as_PDF_markdown`

Above command Exports the Current note, yet opens an additional window while doing so. If Multiple instances are disallowed, it still brings up the Print dialog in the current Instance.

What I want to do is: 
1. **Export multiple Notes as PDF** (all Notes present in currently selected Note folder), with a bash script running in background
2. **Without any sort of Interface with the Application** (No Print Dialog)

Is there any way to go about doing this? 

If not, would it be possible to support Parameters like

`--background` or `--no-window`, to run the app in background
`--print default` or something like that, to Print with default settings
`--print all` or similar, to print all notes in current folder
`--output "Insert Location Here"`, to specify output location

**Comment by pbek** [comment]
Phew, QOwnNotes never was meant to work as CLI and also not in the background... There isn't even a scripting engine available until the main UI loads it. And you cannot pass CLI parameters to the scripting engine...

**Comment by pbek** [comment]
Is this really a job QOwnNotes needs to do or rather something you can do with some other tools, like pandoc? Notes are simple Markdown files after all...

**Comment by pbek** [comment]
Fork QOwnNotes and make it into an cli export tool that uses the same style settings? 😁 

> it won't be similar to QOwnNotes' Export Style

You could just copy the CSS from an export of a RAW HTML of the preview (right click on it).

**Comment by Cho-Chang** [comment]
I'm a doofus when it comes to Programming, so Fork is not a realistic option 😄. 

I was able to make use of one of md->html utilities, along with QON's embedded CSS.

**Comment by pbek** [comment]
> I was able to make use of one of md->html utilities, along with QON's embedded CSS. 

Great! 😁
