### ISSUE TITLE
Feature request: Multiline Editing

### ISSUE THREAD

**Issue by habedi77** [pbek/QOwnNotes#2678]
I was wondering if it is possible to add multiline / column editing to QOwnNotes, similar to one in [Notepad++](https://npp-user-manual.org/docs/editing/)
![](https://npp-user-manual.org/docs/images/columnMode.gif)

Any comments?

**Comment by pbek** [comment]
Unfortunately nothing the QPlainTextEdit can do.

**Comment by Waqar144** [comment]
It is possible to implement this with QPlainTextEdit,

**Comment by pbek** [comment]
@Waqar144, do you have that much time again already? 😆

**Comment by Waqar144** [comment]
atm, not really and if I do it, it will be in a separate library that can be reused. But point is, it _is_ possible.

**Comment by pbek** [comment]
In software virtually everything is possible. The question is if it's feasible to implement it.

**Comment by Waqar144** [comment]
I am not sure what you mean or are asking. Not everything is possible always, even in software world. Though this particular feature can be implemented with QPlainTextEdit.

**Comment by pbek** [comment]
I was referring to my "Unfortunately nothing the QPlainTextEdit can do.", which is true. There is no flag "enable this", or is it (and I wasn't aware of it, then my apologies). Other than that I think everything can be implemented within a few man-years, even if that would be a re-implementation. 😆  In this case I don't know how much effort would be needed.

**Comment by Waqar144** [comment]
Yes in that way you are right. There is no simple toggle available to enable this feature. Implementing this would be a lot of effort for sure. QtCreator has done it already so its code can be reused, but even doing that is not simple.

**Comment by pbek** [comment]
> QtCreator has done it already so its code 

Oh, I didn't even know that. I never was a big fan of multiple cursors, so I didn't pay much attention to that feature in QtCreator.
