### ISSUE TITLE
QOwnNotes freezes if the editor is resized to a very small width

### ISSUE THREAD

**Issue by Waqar144** [pbek/QOwnNotes#2679]
- Have both preview and editor open side by side
- Drag the splitter handle to make the editor smaller . At some point QOwnNotes will freeze.

This is easily triggerable if you try to tile the window to one side of the screen.

**Comment by pbek** [comment]
I wasn't able to reproduce that. Did you manage to get it smaller than that? (because I wasn't able to)

<img width="271" alt="image" src="https://user-images.githubusercontent.com/1798101/205271253-9447a93c-c9d2-4d41-951e-e54cc65314fe.png">

**Comment by Waqar144** [comment]
Yes, smaller than that. Right border touches the line number area. And my editor is on the left side, not sure if it matters

**Comment by Waqar144** [comment]
Maybe the debug panel at the bottom or something else is preventing it from becoming smaller

**Comment by pbek** [comment]
I removed the debug panel now, still couldn't go smaller.... maybe the horizontal scrollbar blocked it?
Did you find out what caused the freeze?

**Comment by Waqar144** [comment]
Its the setViewportMargins() in setPaperMargins() function. It causes an endless loop of resizeEvents being sent to the editor leading to a freeze. So far I haven't found a way to fix it and don't really understand fully why exactly so many resize events are being sent.

**Comment by Waqar144** [comment]
https://user-images.githubusercontent.com/7696024/205283540-3b5322eb-fdd7-46d2-96b4-a8472d1490ae.mp4

**Comment by pbek** [comment]
Weird... Even weirder I cannot even get it that small.

**Comment by pbek** [comment]
Shall we just give it a min-size if you can't find the reason for the events?

**Comment by Waqar144** [comment]
Yes, but not sure if it will fix the issue. Will need to try this

**Comment by pbek** [comment]
The problem is the minimumSize I can enter is independent of the zoom level of the desktop environment. So 200 for one user can look different than for another user.

**Comment by pbek** [comment]
Haha, now that I set the width of the minimumSize down to 50 I'm able to resize the panel smaller than I was before and I can reproduce the UI freeze. 😆 But it takes no CPU for some reason...

**Comment by Waqar144** [comment]
yeah, but that is easily fixable. Just multiply by the scale factor

> The problem is the minimumSize I can enter is independent of the zoom level of the desktop environment. So 200 for one user can look different than for another user.

That is easily fixable, just multiply by scale factor

**Comment by Waqar144** [comment]
just tested, no change. Still freezing

**Comment by pbek** [comment]
> That is easily fixable, just multiply by scale factor

I think more like "dividing" instead of "multiplying" , don't you think?
Is there an easy way to get the scale factor on all platforms without calculating?

> just tested, no change. Still freezing

strange... I scale to 150% with my High-DPI screen...  does it work if you go to 120 (from 80)?

**Comment by Waqar144** [comment]
Bigger value works, but this is not a fix really. Its working around the actual issue

**Comment by Waqar144** [comment]
usually just multiply by devicePixelRatio. If you divide it will become even smaller.

**Comment by pbek** [comment]
> Bigger value works, but this is not a fix really. Its working around the actual issue

yes it is

> devicePixelRatio

How do you get the devicePixelRatio without resort getting the env var QT_DEVICE_PIXEL_RATIO? (would that work on other platforms or Wayland?)

> usually just multiply by devicePixelRatio. If you divide it will become even smaller.

but that would mean I need to set something like 53 so I get to (almost) 80... would mean your number is 53 if you have a devicePixelRatio of 1 (what's your ratio?)

**Comment by Waqar144** [comment]
I am not sure I understand what you are trying to achieve / want to do.

Every widget has a device pixel ratio method

**Comment by pbek** [comment]
Ah, now I see.
https://doc.qt.io/qt-5/qpaintdevice.html#devicePixelRatioF
I was searching on application level.

Ok, `ui->noteEditTabWidget->devicePixelRatioF()` says I have `1.5`. You suggested I need to multiply something with it. What base value do you suggest then? Since 80 as end value was ok for me I think the base value would be 53 or something if we talking about multiplying. But that would mean your end-value is 53 since you have a devicePixelRatioF of `1`(at least I think so), or am I misdirected?

**Comment by pbek** [comment]
That's why I was suggesting dividing (by 1.5 in my case) a bigger value, like 120.
For me `120 / 1.5 = 80`.

**Comment by Waqar144** [comment]
Generally no one does that afaik i.e., you scale to your desktop size, but dont do the opposite. Also still unsure what you are trying to accomplish

**Comment by Waqar144** [comment]
Generally no one does that afaik i.e., you scale to your desktop size, but dont do the opposite. Also still unsure what you are trying to accomplish.. 

Besides that, don't you think its wrong to just _work around_ and not even try to fix the actual problem?

**Comment by pbek** [comment]
Yes, a fix would be far better.

**Comment by pbek** [comment]
I'm doing debugging inside `QOwnNotesMarkdownTextEdit::setPaperMargins`, which seems to be the "culprit" when it does a `setViewportMargins` which seems to cause another QResizeEvent.

But when I do a `geometry().width()` inside it and resize the panel it reports the correct width (e.g. 156) and next time (more resizing by hand) it reports like 1701, then again the correct value and then a far to high value... I've no idea where that comes from. It's hard to add a limit to setPaperMargins when a wrong width is reported. 😬

**Comment by Waqar144** [comment]
Right, I tried that as a well and failed. Removing the line number area width from setviewportmargins() fixes the freeze..

**Comment by pbek** [comment]
Doing anything with lineNumberArea didn't seem to help me... I don't even have the line numbers turned on.

**Comment by pbek** [comment]
I'll do the workaround until there is a better solution...

**Comment by pbek** [comment]
## 22.12.0
- a minimum width for the note edit is now defined to prevent freezes when it is
  resized too small in desktop environments where there is no minimum width of
  the scrollbar dial that would prevent resizing the panel so small

**Comment by Waqar144** [comment]
> I'll do the workaround until there is a better solution...

Why? Is there some emergency? And that doesn't even work. Even for that min width fix there is a bettter way! Does it really hurt your ego to create a PR? I am spending time to solve this issue, but I guess fuck it.

**Comment by pbek** [comment]
Where comes the anger from? If you find a better fix meanwhile even the better, I'll merge it then.

**Comment by Waqar144** [comment]
That doesn't fix the problem. It doesn't work here, but I guess all is good if it works for you. You can push it, who can stop you. Yes, there is a better way to specify min size, more correctly, never mind though. It's annoying when you continue to ignore anyone else's opinion and just push whatever you want to master, even when something is under discussion and when I am spending my time on solving it. But I am done with this, do as you see fit.

**Comment by pbek** [comment]
Why are you so angry today? If there is an issue with the workaround just report it. I just wanted a temporary workaround until there is a better fix. I don't want QOwnNotes to freeze on some desktop environment themes. No harm was done.

**Comment by Waqar144** [comment]
Reread what I wrote, it includes the answer to your question. Since obviously you find no problems with anything, I don't think there's any point in continuing this. And this is not just today, you continue to do this repeatedly which makes me think that collaboration with you is just pointless, you just do what you want whenever you want. So why should I bother to create PRs/issues/anything, I can do it the way I want for myself.

**Comment by pbek** [comment]
I can reproduce it when I set a minimumSize. But I respect your choice.

**Comment by pbek** [comment]
> But when I do a geometry().width() inside it and resize the panel it reports the correct width (e.g. 156) and next time (more resizing by hand) it reports like 1701, then again the correct value and then a far to high value... I've no idea where that comes from. It's hard to add a limit to setPaperMargins when a wrong width is reported. grimacing

This only seem to happen to me (along with the whole issue) if a "central widget" is set. If I turn that off the width is reported correctly and there is no freeze for me.

**Comment by pbek** [comment]
Yes, thank you. I was using something that takes the lineNumAreaWidth() in consideration (when they are enabled) too, but as long there are completely wrong width reported it's hard to really fix or set anything... 😬

**Comment by Waqar144** [comment]
I don't think the problem is in setPaperMargins at all, so it can't be fixed there. Blocking the call is useless regardless of what width is reported. You can even remove the call to setPaperMargins from resizeEvent and it will still happen.

**Comment by pbek** [comment]
I guess I'll be rolling with `minimumSizeHint` then, seems to work fine...

**Comment by pbek** [comment]
## 22.12.1
- the setting of the minimum width for the note edit was improved to take the width of the
  line number area into account (for [#2679](https://github.com/pbek/QOwnNotes/issues/2679))
