### ISSUE TITLE
image resize?

### ISSUE THREAD

**Issue by mlinchitstest** [pbek/QOwnNotes#268]
perhaps we could get a simple image resize option when we add images to the note? this would be a great feature imo. You don't have to update the markdown parser—just resize the actual picture file.

**Comment by pbek** [comment]
I will take a look how complex that would be.

**Comment by pbek** [comment]
## 16.10.9
- you can now choose to scale images down when inserted into notes in
  the general settings
    - you can set a maximum height and width of the images

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?
