### ISSUE TITLE
list sequence number after image 

### ISSUE THREAD

**Issue by rjiang9** [pbek/QOwnNotes#2682]
Env: Mac M1 - ventura 13.0.1

I have a list like this:

<img width="482" alt="image" src="https://user-images.githubusercontent.com/7293118/206269570-7b9ae697-98e6-4c1b-8a89-4f17a4c61b10.png">

But I got the note looks like this:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/7293118/206270136-82cd85a2-84a0-4472-abfd-77b0cb03c2a3.png">

If there way to make the sequence number continued after images like it was before the image?

Thanks,

**Comment by pbek** [comment]
How does the raw html look that you can export in the preview?

**Comment by rjiang9** [comment]
@pbek it looks the raw html is ok. 


<img width="425" alt="image" src="https://user-images.githubusercontent.com/7293118/206301656-b598d31c-5139-4a60-938c-7d1878f42c42.png">

**Comment by pbek** [comment]
Those are two separate `<ol>` tags, the QTextBrowser of the preview doesn't seem to support the `start="6"` (I didn't even know such an attribute exists).
