### ISSUE TITLE
Questions after reading source code

### ISSUE THREAD

**Issue by WDMdanila** [pbek/QOwnNotes#2683]
Hi everyone!

Thank you for great tool, wanted to help somehow in development so started reading source code to get familiar with it and had several questions:
- there are lot of default one-line getters/setters. Is that a convention or is there some reason for such structure? It seems like in most of places getter/setter pair could be replaced with simple call to member variable (instead of calling `object.setVariable(newValue);` we could just `object.variable = newValue;`). Removing default getters/setters could greatly reduce code bloat and improve readability and if some additional behavior would be needed - option to add getter/setter is always there
- have you thought about package manager like `conan`?
- have you thought about code formatting tools? Currently different parts of sources are formatted differently

Sorry for writing it here, for some reason there is problem with Telegram and I am unable to send a message there :(

**Comment by pbek** [comment]
Thank you for your concern with the code base!

>    there are lot of default one-line getters/setters. Is that a convention or is there some reason for such structure? It seems like in most of places getter/setter pair could be replaced with simple call to member variable (instead of calling object.setVariable(newValue); we could just object.variable = newValue;). Removing default getters/setters could greatly reduce code bloat and improve readability and if some additional behavior would be needed - option to add getter/setter is always there

Sometimes setters or getters also do some addition stuff, I don't know if it's worth to migrate that all without breaking anything. If you want you can check how often something else is done with the variable...

>    have you thought about package manager like conan?

https://conan.io/? haven't seen that one in the wild yet. what do you want to use it for? publishing QOwnNotes or fetching external dependencies (which there currently are none but those directly added via git-submodule)

>    have you thought about code formatting tools? Currently different parts of sources are formatted differently

yes, that's a pain... do you have one in mind? downside of doing that to the current code-base would be loosing all the git blame status...

**Comment by WDMdanila** [comment]
> Sometimes setters or getters also do some addition stuff, I don't know if it's worth to migrate that all without breaking anything. If you want you can check how often something else is done with the variable...

I have started such refactor here: https://github.com/WDMdanila/QOwnNotes/tree/refactor/getters_setters touching only getters/setters without any additional logic

> https://conan.io/? haven't seen that one in the wild yet. what do you want to use it for? publishing QOwnNotes or fetching external dependencies? (which there currently are none but those directly added via git-submodule)

Conan could be used for fetching external dependencies, for example: https://conan.io/center/botan . It is really easy to setup and control versions used as all libraries and their versions are in one config file, as well as then there is no need for having `libraries` directory in `src`

> yes, that's a pain... do you have one in mind? downside of doing that to the current code-base would be loosing all the git blame status...

At work we use [uncrustify](https://github.com/uncrustify/uncrustify) together with [pre-commit](https://pre-commit.com/) but even some simple `clang-format` should suffice. Loss of git blame is unfortunate, that is true, but I guess this information still could be retrieved from commits before beautifying (would not be so comfortable to do so, but still possible)

Will try to provide some examples of integration of QOwnNotes with conan after finishing getters/setters cleanup

**Comment by pbek** [comment]
> I have started such refactor here: https://github.com/WDMdanila/QOwnNotes/tree/refactor/getters_setters touching only getters/setters without any additional logic

Usually such PRs come with lots of regressions, some of them not found for a year 😆  I wish there would be a (free) QWidget UI end2end test tool for Qt...

> Conan could be used for fetching external dependencies, for example: https://conan.io/center/botan . It is really easy to setup and control versions used as all libraries and their versions are in one config file, as well as then there is no need for having libraries directory in src

The price would be that everyone (contributes) and everywhere (build systems on many platforms and architectures) another 3rd party would be needed to build the app. As nice as having a package manager sounds to me, I don't know if I currently have the time to make and support that transition.

> Will try to provide some examples of integration of QOwnNotes with conan after finishing getters/setters cleanup

Yes, please thank you.

@Waqar144, any thoughts about above points?

**Comment by Waqar144** [comment]
We are using qmake as our primary build system which I think (not sure) will make it difficult to use conan and besides that it is yet another dependency.

For the getters and setters, it might make sense to remove them in some places yes. But in cases like `entities` which are exposed to QML, it would make more sense to remove `NoteApi` and expose the entities directly to QML via Q_PROPERTY/Q_GADGET. Q_PROPERTY can then use those getters/setters.

Agreed on formatting, precommit can be used for it for sure. Git blame is not an issue at all. Git support `git-blame-ignore-revs` which you can use to ignore specific revisions.

**Comment by pbek** [comment]
> Git supports git-blame-ignore-revs which you can use to ignore specific revisions.

true, but with no IDE integration 😅  (I'd really love that in the CLion)

> But in cases like entities which are exposed to QML, it would make more sense to remove NoteApi and expose the entities directly to QML via Q_PROPERTY/Q_GADGET. Q_PROPERTY can then use those getters/setters.

Intriguing, but I don't even think it's possible to get rid of those classes and I guess that would break most of the existing scripts any use has running.

**Comment by Waqar144** [comment]
> true, but with no IDE integration sweat_smile (I'd really love that in the CLion)

Not sure about CLion, it is smart so I assume it will work with it. In Kate for e.g., I just do `git config blame.ignoreRevsFile /path/to/file` once in a repo and it just works after that.

**Comment by pbek** [comment]
> With end to end tools e.g., squish, it can sometimes be even more difficult so even if it was free I doubt we would have anymore tests than we have now.

I'd love to have Squish, but that's all commercial... 😞  But I don't know how "entropy tolerant" Squish is 😅

**Comment by Waqar144** [comment]
Trust me, working with Squish is not that fun and involves writes tons of python code.

**Comment by pbek** [comment]
I feared as much...
