### ISSUE TITLE
Not able to remove alarm date for todo item

### ISSUE THREAD

**Issue by WDMdanila** [pbek/QOwnNotes#2684]
#### Expected behaviour

Unchecking `Reminder` checkbox and saving should remove `Due date` from todo item

#### Actual behaviour

It does not, reminder remains set and can not be removed

#### Steps to reproduce

Create todo item, add reminder, try to remove it.

#### Possible solution

This issue can be fixed quickly and easily:

In `else` branch of `TodoDialog::on_reminderCheckBox_clicked` we can clear both `currentCalendarItem.alarmDate` and `ui->reminderDateTimeEdit`

In `CalendarItem::generateNewICSData` we can add `else` branch to `if(alarmDate.isValid())` with:
```c++
icsDataHash.remove(QStringLiteral("DUE"));
icsDataKeyList.removeAll(QStringLiteral("DUE"));
```

**Comment by pbek** [comment]
Phew, thank you, you are right. But that of course did already work. I wonder what broke it...

**Comment by pbek** [comment]
...auto-closed by PR

**Comment by WDMdanila** [comment]
Bug should be fixed in PR, or is there some process that you follow usually?

**Comment by pbek** [comment]
Usually I let the issue-opener test the fix... but in this case you also opened a PR, so you can close it if you want or you can wait for the next release.

**Comment by WDMdanila** [comment]
No problem, guess there is no need to keep issue open, closing it
