### ISSUE TITLE
md4c libraries could be used as a system instead of a bundled one

### ISSUE THREAD

**Issue by david-geiger** [pbek/QOwnNotes#2686]
hi,

I'm the qownnotes Mageia Linux packager, I see that md4c libraries are used in this project but are bundled into it while some distribution, like us, provides a system one.

So is it possible to make qownnotes build with a md4c system as an option like botan?

Regards,
David

**Comment by pbek** [comment]
> So is it possible to make qownnotes build with a md4c system as an option

I don't know if we can trust a random version of the libraries, we maintain our own fork of md4c.
Opinions, @Waqar144?

> like botan?

Botan is integrated too and no external library.

**Comment by pbek** [comment]
And even then, I hardly think the binary size would shrink a lot if md4c would be external...

**Comment by david-geiger** [comment]
Ok perfect, I understand

For botan there is a build option "USE_SYSTEM_BOTAN"  in the botan.pri file ans also in the CMakeLists.txt file.

Thanks a lot!

**Comment by pbek** [comment]
> For botan there is a build option "USE_SYSTEM_BOTAN" in the botan.pri file ans also in the CMakeLists.txt file.

Ah, good to know that this actually works. Thank you!
