### ISSUE TITLE
Can't modify how tables and quotes are rendered

### ISSUE THREAD

**Issue by NicolasWladyslaw** [pbek/QOwnNotes#2688]
Hi Patrizio,

Thanks for your great app.

I've been trying to modify the way how tables are rendered in the preview. I would like to get rid of the cell spacing/double lines basically. I believe I should use the **border-collapse** CSS property which I found in https://doc.qt.io/qt-5/richtext-html-subset.html. I've modified the **Custom note preview styling script** in different ways but I haven't got a clue about Qt and CSS and it just never worked.

I would like also to add a **vertical line** next to quotes but I didn't find much in https://doc.qt.io/qt-5/richtext-html-subset.html.

Have you got any idea how I could manage to do that ?

**Comment by pbek** [comment]
No, sorry. You are always limited to the subset you mentioned above...
The only route you could go is modifying the generated html directly or the markdown before the html is rendered.

See:
- https://www.qownnotes.org/scripting/hooks.html#notetomarkdownhtmlhook
- https://www.qownnotes.org/scripting/hooks.html#prenotetomarkdownhtmlhook

**Comment by NicolasWladyslaw** [comment]
I've had a look at **example.qml** and the other scripts but I'm kinda lost with modifying **noteToMarkdownHtmlHook** and **preNoteToMarkdownHtmlHook**.
When I add the following to **Custom note preview styling** nothing much happens but the background color DOES change to light pink :
```
blockquote {
  border-left: thick solid #4CAF50;
  background: #FFEDED;
}
```
However the following does nothing with tables :
```
table {
border-collapse: collapse
}
```

**Comment by pbek** [comment]
I guess you did 😁  `border-collapse` is mentioned. I think `border-collapse: collapse` will already be applied in QOwnNotes, what did the raw preview html export say?

**Comment by NicolasWladyslaw** [comment]
I exported some notes as html and it looked nearly perfect actually except that every word is bold.
I've slightly modified the script :
```
blockquote {
  border-left: thick solid #4CAF50;
  background: #FFEDED;
  padding: 20px;
}

table, th, td, tr {
  border: 1px solid black;
  border-collapse: collapse
}
```

This what the preview looks like as an html export :

![test-html](https://user-images.githubusercontent.com/64907666/209243227-d5615323-c382-41f5-a08a-8614ff446918.png)

And as a PDF export :

![test-pdf](https://user-images.githubusercontent.com/64907666/209243276-dd8a5966-ccc5-4171-b610-5d20cade2ab3.png)

This is the raw preview html export :
```
<html><head><meta charset="utf-8"/><style>h1 { margin: 5px 0 20px 0; }h2, h3 { margin: 10px 0 15px 0; }img { max-width: 100%; }pre { background-color: #f1f1f1; border-radius: 5px; padding: 10px; }pre > code { padding: 0; }table {border-spacing: 0; border-style: solid; border-width: 1px; border-collapse: collapse; margin-top: 0.5em;}th, td {padding: 2px 5px;}a { color: #FF9137; text-decoration: none; } pre, code { font-family: "Nimbus Mono PS [UKWN]"; font-weight: normal;  }pre { display: block; background-color: #f1f1f1; white-space: pre-wrap } code { padding: 3px; overflow: auto; line-height: 1.45em; background-color: #f1f1f1; border-radius: 5px; color: #000000; } .code-comment { color: #75715E; font-style: italic;} .code-string { color: #E6DB74;} .code-literal { color: #AE81FF;} .code-type { color: #66D9EF;} .code-builtin { color: #A6E22E;} .code-keyword { color: #F92672;} .code-other { color: #F92672;} body { font-family: "Ubuntu Light"; font-weight: normal; font-size: 12pt; } mark {background-color:#FFA500;}blockquote {
  border-left: thick solid #4CAF50;
  background: #FFEDED;
  padding: 20px;
}

table, th, td, tr {
  border: 1px solid black;
  border-collapse: collapse
}</style></head><body class="export"><h1>Test</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. Proin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. Duis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. Ut in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit.</p>
<blockquote>
<p>Blockquote
Ut velit mauris, egestas sed, gravida nec, ornare ut, mi. Aenean ut orci vel massa suscipit pulvinar. Nulla sollicitudin. Fusce varius, ligula non tempus aliquam, nunc turpis ullamcorper nibh, in tempus sapien eros vitae ligula. Pellentesque rhoncus nunc et augue. Integer id felis. Curabitur aliquet pellentesque diam. Integer quis metus vitae elit lobortis egestas. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi vel erat non mauris convallis vehicula. Nulla et sapien. Integer tortor tellus, aliquam faucibus, convallis id, congue eu, quam. Mauris ullamcorper felis vitae erat. Proin feugiat, augue non elementum posuere, metus purus iaculis lectus, et tristique ligula justo vitae magna.</p>
</blockquote>
<p>Aliquam convallis sollicitudin purus. Praesent aliquam, enim at fermentum mollis, ligula massa adipiscing nisl, ac euismod nibh nisl eu lectus. Fusce vulputate sem at sapien. Vivamus leo. Aliquam euismod libero eu enim. Nulla nec felis sed leo placerat imperdiet. Aenean suscipit nulla in justo. Suspendisse cursus rutrum augue. Nulla tincidunt tincidunt mi. Curabitur iaculis, lorem vel rhoncus faucibus, felis magna fermentum augue, et ultricies lacus lorem varius purus. Curabitur eu amet.</p>
<table>
<thead>
<tr>
<th>this</th>
<th>is</th>
<th>a</th>
<th>test</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td>a</td>
<td>b</td>
<td>c</td>
<td>d</td>
</tr>
<tr>
<td>this</td>
<td>is</td>
<td>a</td>
<td>test</td>
</tr>
</tbody>
</table>
</body></html>
```

**Comment by pbek** [comment]
> except that every word is bold

strange, maybe it's the font that looks that way?

**Comment by NicolasWladyslaw** [comment]
It was the font indeed ! The html export looks great now.
Have you got any idea why the html export looks as intended but not the preview and what could I do about it ?

**Comment by pbek** [comment]
Don't know. Maybe the PDF Application renders it differently? Shouldn't be the case tho...

**Comment by NicolasWladyslaw** [comment]
Sorry I meant the preview in QOwnNotes.

**Comment by NicolasWladyslaw** [comment]
i.e. the preview pane.

**Comment by pbek** [comment]
That I cannot say. It totally depends on the QTextBrowser.
