### ISSUE TITLE
[F] Inline image support

### ISSUE THREAD

**Issue by bbkane** [pbek/QOwnNotes#2689]
#### Expected behaviour

When typing,  headers/italics/other markup get emphasized.  Images likewise get highlighted,  but unlike other markup,  it's not possible to see the content of the image from the editor. This request is to show images inline beneath the highlighted image link text.  I think this request is a subset of https://github.com/pbek/QOwnNotes/issues/1662 ,  but I thought I'd break it out into its own issue due to its importance to me :)

#### Actual behaviour

You can only see the link in the editor,  not the image content.

#### Steps to reproduce

Create an image link.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sun Dec 18 09:56:19 2022`
**Version**: `22.12.3`
**Build date**: `Dec 14 2022`
**Build number**: `1002`
**Platform**: `macosx`
**Operating System**: `macOS 12.3`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/Users/bbkane/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/bbkane/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1680x1050`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `2`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/Users/bbkane/Library/Application Support/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/Users/bbkane/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/Users/bbkane/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

## Settings

**AKLastCheckInAttemptDate** (QDateTime): `2019-10-19T14:52:08.975`
**AKLastCheckInSuccessDate** (QDateTime): `2019-10-19T14:52:09.604`
**AKLastEmailListRequestDateKey** (QDateTime): `2020-04-24T14:52:30.620`
**AKLastIDMSEnvironment** (qlonglong): `0`
**Canon MF240 Series** (QString): `1`
**Country** (QString): `US`
**EPSON ET-3750 Series** (QString): `1`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/removeTrailingSpaces** (bool): `false`
**HP DeskJet 3700 series** (QString): `1`
**HP OfficeJet Pro 8710** (QString): `1`
**Hewlett Packard MFP M477fdn** (QString): `1`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2022-12-18T09:40:37.548`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/mainToolBar.iconSize** (qlonglong): `32`
**MainWindow/noteTextEdit.code.font** (QString): `Menlo,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `.AppleSystemUIFont,16,-1,5,50,0,0,0,0,0`
**NXP PTN5002** (QString): `1`
**PKSecureElementAvailableFlagsByHost** (qlonglong): `3`
**PKSecureElementAvailableFlagsByHostSome** (qlonglong): `3`
**PiwikClientId** (QString): `<hidden>`
**Realtek BillBoard Device** (QString): `1`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**Seagate Expansion** (QString): `1`
**Texas Instruments TUSB3410 Boot Device** (QString): `1`
**VIA Technologies Inc/ USB 2/0 BILLBOARD** (QString): `1`
**WebAutomaticSpellingCorrectionEnabled** (bool): `true`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**allowNoteEditing** (bool): `true`
**appMetrics/notificationShown** (bool): `true`
**checkSpelling** (bool): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (qlonglong): `1`
**currentWorkspace** (QString): `initial`
**darkMode** (bool): `false`
**demoNotesCreated** (bool): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**dockWasInitializedOnce** (bool): `true`
**guiFirstRunInit** (bool): `true`
**initialLayoutIdentifier** (QString): `minimal`
**itemHeight** (qlonglong): `18`
**markdownHighlightingEnabled** (bool): `true`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**notesPath** (QString): `/Users/bbkane/Notes`
**ownCloud/supportEnabled** (bool): `false`
**restoreCursorPosition** (bool): `false`
**showMenuBar** (bool): `false`
**showStatusBar** (bool): `true`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**USER**: `bbkane`
**__CFBundleIdentifier**: `com.PBE.QOwnNotes`
**COMMAND_MODE**: `unix2003`
**LOGNAME**: `bbkane`
**PATH**: `/usr/bin:/bin:/usr/sbin:/sbin`
**SSH_AUTH_SOCK**: `/private/tmp/com.apple.launchd.rct2nZmDHo/Listeners`
**SHELL**: `/bin/zsh`
**HOME**: `/Users/bbkane`
**__CF_USER_TEXT_ENCODING**: `0x1F5:0x0:0x0`
**TMPDIR**: `/var/folders/3t/t48_4ckj5yscz5h5zdpr5glm0000gn/T/`
**XPC_SERVICE_NAME**: `application.com.PBE.QOwnNotes.27098541.27098544`
**XPC_FLAGS**: `0x0`
**QT_LOGGING_RULES**: `qt.network.ssl.warning=false`
</details>

**Comment by pbek** [comment]
Are we talking about #1254?

**Comment by bbkane** [comment]
Yes, this does seem to be a duplicate of #1254. Not sure how I missed that when I searched!
