### ISSUE TITLE
option to toggle between editor and preview?

### ISSUE THREAD

**Issue by mlinchitstest** [pbek/QOwnNotes#269]
would be handy IMO—often you don't have enough space for the double pane and need just one pane. Currently you have to toggle each pane separately, or open the "distraction free mode". Seems awkward for certain use case.

**Comment by pbek** [comment]
Why you don't just use the the vertical preview layout?

**Comment by mlinchitstest** [comment]
Because my laptop monitor is not big enough to display tags, notes, editor, and preview in one window. Even on big monitors, it makes the window take up the whole screen, which is bad for looking at other stuff while youre writing.

Great work though—yours is already by far the best personal wiki software, despite being very new and not even trying to be a wiki! Heck—someday it can an even become a full-blown personal wiki like [wikipad](http://wikidpad.sourceforge.net), but with support for mediawiki markup and without the complicated interface.

**Comment by pbek** [comment]
Thank you for your kind words.

Wiki: Since there is no database (and there also shouldn't be any) that is storing the notes and the references between them and note file-names could change that currently wouldn't work very well. :)

**Comment by pbek** [comment]
> Because my laptop monitor is not big enough to display tags, notes, editor, and preview in one window. 

You could use the *vertical preview layout* and toggle the preview with it's keyboard shortcut. The *vertical preview layout* was created for small screens...

Is there a reason why that wouldn't work for you?

**Comment by Maboroshy** [comment]
+1 for request. I thought about such toggle button many times. I mostly don't use editor and render panes both on the screen and toggling between them takes several well aimed clicks. Vertical layout is like it's made for a 4:3 screen, not very useful with 15" 16:9 for me.

PS I was a user of wikidpad before QOwnNotes. I find the later much better if you need a note application. C++ against Python makes a big difference too.

**Comment by pbek** [comment]
## 16.08.1
- you can now toggle between the note edit mode and the preview with
  <kbd>Alt</kbd> + <kbd>⇧</kbd> + <kbd>P</kbd>

**Comment by Maboroshy** [comment]
Could you add a toolbar button for that. Maybe as the separate toolbar. I'd put it to some special place since it'd be the most used button for me.

**Comment by pbek** [comment]
I think that button would be too confusing... I'd rather not have one, don't you like shortcuts?

**Comment by Maboroshy** [comment]
I don't really, especially with more than 2 buttons. And <kbd>Alt</kbd> + <kbd>⇧</kbd> + <kbd>P</kbd> is all over the place. How do you press  <kbd>⇧</kbd> + <kbd>P</kbd> with one hand? Need some finger yoga course or something.  :sweat_smile:

Of course I can bind another keys to emulate this shortcut. QOwnNote has all the F-keys free to bind.

It's a pity that there's no toolbar customization like the KDE apps have, that'd solve this kind or issues.

**Comment by Maboroshy** [comment]
... I've just thought that to have keyboard shortcut to switch panes there's no need to change anything in QOwnNotes. I always could emulate two shortcuts with one key.

But it was a toolbar button I was posting about. Don't know what @mlinchitstest asked for though.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment]
I've tested new keyboard shortcut and it worked... after some tinkering.

I have to say it was the first time I've tested shortcuts in the app. And I've realized that  <kbd>⇧</kbd> is <kbd>Shift</kbd> and not the arrow key as I thought at first. So my comment above about this shortcut is kind of stupid. I'm sorry for that. I need to sleep more and post less.

The real issue though is that I had to turn off my keyboard layout switching to use any <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>Any</kbd> shortcuts. I use <kbd>Alt</kbd> + <kbd>Shift</kbd> to switch keyboard layout which I think is default for Plasma 5 and Windows. On my Linux machine <kbd>Shift</kbd> + <kbd>Any</kbd> does nothing more than layout switching, no matter what I press after them. 

I fear key emulation won't help with that.

**Comment by pbek** [comment]
Fear not, @Maboroshy. I'm currently working on #194. ;)

**Comment by nitingupta910** [comment]
I'm using version 19.4.2 but I don't see an option/keyboard-shortcut to toggle between editor and preview. All I do is open preview side-by-side. 

Is it still possible to toggle preview instead of opening side-by-side?

**Comment by akshat46** [comment]
> ## 16.08.1
> * you can now toggle between the note edit mode and the preview with
>   Alt + ⇧ + P

I think this might be broken now. Unless, <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>p</kbd> has been changed to something else? I am using a variation of single column setup and for me it just switches editor panel's size between two sizes while being the editor panel in both the states. Preview mode never shows up. 
Also couldn't find this shortcut in the settings.

btw great app! I switched from an electron based notes app and I love how lightweight this is.

**Comment by pbek** [comment]
That information is obsolete. Meanwhile there are workspaces, where you can define what to view. And there is a shortcut to toggle between the last and current workspace. And you can use the scripting engine to switch workspaces.

> btw great app! I switched from an electron based notes app and I love how lightweight this is.

thank you! yes, lightweight it is! 😁
