### ISSUE TITLE
Rendering of Table Columns, when using Line Breaks

### ISSUE THREAD

**Issue by Cho-Chang** [pbek/QOwnNotes#2694]
Column Width in Table does not Respond to Width of Text, when Line Breaks are used

Without Line Break

![2023-01-01_22-50](https://user-images.githubusercontent.com/85818525/210179814-9e250677-917b-45fa-9ad2-c074e5547e36.png)

![2023-01-01_22-50_1](https://user-images.githubusercontent.com/85818525/210179820-3ed68dc8-549d-48a7-a750-c349d65a8d84.png)

With Line Break:

![2023-01-01_23-06](https://user-images.githubusercontent.com/85818525/210179924-36a49aa4-9a7e-4137-8140-909c745e7c16.png)

![1](https://user-images.githubusercontent.com/85818525/210179949-4c79bcc5-173a-4331-a941-4385fe2b6d78.png)

Is this Expected Behaviour? If yes, is it possible to alter it in any way? (through, Custom Note Preview Script?)

**Comment by pbek** [comment]
Are you talking about the preview? That's how Qt's QTextBrowser renders it. Hard to tell if something is different for you, with you the things asked for in the issue template, an example markdown file and the html exported from the preview.

**Comment by pbek** [comment]
But it looks like an up-stream issue. The html code looks ok. But Markdown tables weren't really meant to be multi-line imo.

**Comment by Cho-Chang** [comment]
Yeah, the Preview (and, by Extension PDF Export)

> Hard to tell if something is different for you

Don't think its something on my end

[Example.zip](https://github.com/pbek/QOwnNotes/files/10331854/Example.zip)

> Markdown tables weren't really meant to be multi-line imo.

Expected this, yet decided to try my luck :D
