### ISSUE TITLE
PDF Export: Page Margins

### ISSUE THREAD

**Issue by Cho-Chang** [pbek/QOwnNotes#2695]
Page Margins in PDF Export currently default back to `2.96 mm`, when any value below 2.96 is set. Would it be possible to have a lower value for Margins?

Inability to set lower value adds a good 4-5 Additional Pages in the PDF, when exporting Large Notes (~100 Pages in PDF)

![2023-01-01_22-54](https://user-images.githubusercontent.com/85818525/210180265-06f60014-34a3-42fc-9a92-0076dca80402.png)

**Comment by pbek** [comment]
Hard to tell which system you are one (see issue template) but often everything related to printing (and exporting for that manner) is tied to a printer. Usually the operating system dictates what settings can be made in such a dialog.

**Comment by Cho-Chang** [comment]
Ah yes, realized that QON had indeed been using 0.00mm as margin. I had mistaken mm for cm, and hence, overestimated the impact of reducing it to 0.00 (and, overlooked the subtle change in Margin for PDF Export). It is indeed defined by OS. Sorry for opening this one.
