### ISSUE TITLE
Tag for web clipped note is not set to the tag from the settings

### ISSUE THREAD

**Issue by Flashwalker** [pbek/QOwnNotes#2697]
Don't know bug or feature

UPD: edited:
If I select a tag in the QOwnNotes tags panel to show notes only by that tag, and then i web clip some content in browser via extension, i get a new note in QOwnNotes tagged with a tag which was selected in the tags panel before clipping., but not with the tag i set in the Browser extension settings.

#### Expected behaviour
Tag for web clipped note set from settings

#### Actual behaviour
Tag for web clipped note set to the tag selected in tags panel

#### Steps to reproduce
1. set the tag for Browser extension in settings
2. choose some tag in tags panel and choose the note
3. web clip some content

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

QOwnNotes - version 23.1.0 - Launchpad PPA - build 1003

</details>

**Comment by pbek** [comment]
> set the tag for Browser extension in settings
> choose some tag in tags panel and choose the note

In which tag panel? the web extension or QOwnNotes...
I think I don't understand the question or your reasoning? The browser extension doesn't set tags in notes. The tag you choose in the QOwnNotes settings is just for finding notes with bookmarks in them...

> web clip some content

**Comment by Flashwalker** [comment]
> In which tag panel? the web extension or QOwnNotes...

QOwnNotes

**Comment by Flashwalker** [comment]
The translation of the settings seems to have misled me. I thought that the tag set in Browser extension settings would be added to the web-clipped note.  
It looks like it would be added to the bookmark for the extension, isn't it?

**Comment by Flashwalker** [comment]
But behavior still as above:
> If I select a tag in the QOwnNotes tags panel to show notes only by that tag, and then i web clip some content in browser via extension, i get a note tagged with a tag which was selected in the tags panel.

Don't know bug or feature

**Comment by pbek** [comment]
The explanation of how it works is in the same settings dialog, isn't it? :)

**Comment by Flashwalker** [comment]
> The explanation of how it works is in the same settings dialog, isn't it? :)

i meant: *am i right?

**Comment by pbek** [comment]
If you want some special functionality (like setting some tags) you could use https://www.qownnotes.org/scripting/hooks.html#websocketrawdatahook to script it.

**Comment by Flashwalker** [comment]
> If you want some special functionality (like setting some tags) you could use https://www.qownnotes.org/scripting/hooks.html#websocketrawdatahook to script it.

Thanks.
