### ISSUE TITLE
Finding notes by cyrillic text with spaces splits text by backslashes `\` after each character

### ISSUE THREAD

**Issue by Flashwalker** [pbek/QOwnNotes#2698]
When I try to find notes by cyrillic text with spaces in the find bar on the side panel, I get a text with backslashes `\` after each character.

Hereis it:
find query in the find bar in a side panel:
![ghj](https://user-images.githubusercontent.com/2188215/211186597-177466ef-9703-49f2-8d7b-dedf1fd12a57.png)

find query in the find bar in a note (edit) panel:
![dxfcvgbn](https://user-images.githubusercontent.com/2188215/211186620-efcce0d6-6288-4a04-ae3e-68fd5d5424f1.png)

It's automaticaly set to regexp search in a note (edit) panel.

#### Expected behaviour
imho, we don't need so many backslashes

#### Actual behaviour
backslashes after each character in the find bar in a note (edit) panel.

#### Steps to reproduce
1. try to find notes by cyrillic query with spaces in the find bar on the side panel

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

QOwnNotes - version 23.1.0 - Launchpad PPA - build 1003
</details>

**Comment by pbek** [comment]
It looks like the Cyrillic characters are detected as characters that need to be escaped in the search query.

**Comment by pbek** [comment]
But I can't reproduce your issue. It works fine for me...
![image](https://user-images.githubusercontent.com/1798101/211193340-f30d80db-fb83-4b4d-b7b1-6794b10f83d9.png)

**Comment by Flashwalker** [comment]
> It looks like the Cyrillic characters are detected as characters that need to be escaped in the search query.

Yeap

**Comment by Flashwalker** [comment]
> But I can't reproduce your issue. It works fine for me...

try to add spaces beetwen words to the query

**Comment by pbek** [comment]
Then the search searches for two words (one OR the other), that too worked for me. What were you trying to achieve?

**Comment by Flashwalker** [comment]
well...
if i search e.g. "`кто они`" in side panel
it turens to `(\к\т\о|\о\н\и)` regexp search in note edit panel
and i get matches like: "`кто`", "`они`", "`продуктов`"
while i'm expecting to get not-regexp match: "`кто они`"

**Comment by pbek** [comment]
There is a documentation page on how you can query for strings with multiple words.

**Comment by pbek** [comment]
https://www.qownnotes.org/getting-started/searching.html

**Comment by Flashwalker** [comment]
Okay.
