### ISSUE TITLE
OpenSSL installed on windows 10, Qownnotes doesn't see it ?

### ISSUE THREAD

**Issue by Yamakasi** [pbek/QOwnNotes#27]
I have installed the minimal version of the recommended OpenSSL package but QuownNotes doesn't see it.

What do I wrong on Windows 10 ? Another machhine with OpenVPN doesn't complain and is OK.

**Comment by pbek** [comment]
Which version of OpenSSL do you use and where did you get it from?

There are multiple sources, like:
<http://slproweb.com/products/Win32OpenSSL.html>
<http://www.indyproject.org/Sockets/fpc/OpenSSLforWin64.EN.aspx>
<http://www.heise.de/download/win32-openssl-7de82034858cda1cf3d6e624a0954d2b-1451915824-2647316.html>

Which Windows version does your other computer use?

**Comment by Yamakasi** [comment]
Hi,

The link you have set in the destopapp.

Both run Windows 10.

**Comment by pbek** [comment]
Which version of OpenSSL did you use? The first one: `Win32 OpenSSL v1.0.2e Light`? Did you try other versions from the page?
And did you try other versions of OpenSSL like mentioned above?

**Comment by Yamakasi** [comment]
Hi,

No I need to test the other ones, but I have a quick response.

I used the 64 bits Light version.

**Comment by pbek** [comment]
Yes, please try an other one... Or maybe uninstall the old one, rebooting and trying to install a new one... It's really strange that it works on one computer and not on the other...

**Comment by pbek** [comment]
Regarding your SSL problem...
I just installed OpenSSL (`Win32 OpenSSL v1.0.2e Light` from <http://slproweb.com/products/Win32OpenSSL.html>) on a Windows 10 box. I let the installer copy the DLLs to the system directory (that's important). After I restarted QOwnNotes I could connect to my https Server.

Are the OpenSSL DLLs in your system directory?

**Comment by pbek** [comment]
Version 0.76 of QOwnNotes has now the OpenSSL DLLs included, you may want to try this version.

**Comment by Yamakasi** [comment]
Good work! thanks!

2016-01-09 14:04 GMT+01:00 Patrizio Bekerle <notifications@github.com>:

**Comment by pbek** [comment]
Does SSL now work on both of your computers? :)

**Comment by Yamakasi** [comment]
Need to check the Windows one without it tomorrow! Thanks for the heads up
about it!

2016-01-09 22:29 GMT+01:00 Patrizio Bekerle <notifications@github.com>:

**Comment by pbek** [comment]
+1

**Comment by Yamakasi** [comment]
OK, I installed the new package and all checks are OK but it's doesn't sync
yet.

I need to investigate why.

But the SSL checks are good!

2016-01-09 22:44 GMT+01:00 Patrizio Bekerle <notifications@github.com>:

**Comment by pbek** [comment]
So far so good. :)
What isn't syncing? Your todo items?
Because the notes are relying on the ownCloud sync client to sync.

**Comment by Yamakasi** [comment]
The notes was what I saw that fast, the machine is syncing Docs tho. Need
to check tomorrow (again!)!

2016-01-11 19:15 GMT+01:00 Patrizio Bekerle <notifications@github.com>:

**Comment by pbek** [comment]
Are you using ownCloud?

**Comment by Yamakasi** [comment]
Sure I do :) Other Machines work, one older QownNotes install on W10 and
one OSX tested working so far. One W10 not working with the latest package.

2016-01-11 22:01 GMT+01:00 Patrizio Bekerle <notifications@github.com>:

**Comment by pbek** [comment]
Do you get any messages when you start QOwnNotes on the command line?

**Comment by Yamakasi** [comment]
It works now. I have placed the Notes folder outside of the local Documents folder on this machine also and made a seperate Sync for the Notes folder.

Seems to be the solution every time.

**Comment by pbek** [comment]
Great! I'll close this issue. Feel free to open an other issue if you come across anything again!
