### ISSUE TITLE
minor: clicking on a footnote does not jump to the footnote

### ISSUE THREAD

**Issue by mlinchitstest** [pbek/QOwnNotes#270]
i think generally internal links are not supported in the preview pane. So when you click on a footnote [^1]

the viewer wont jump to:
[^1]: footnote 1

**Comment by pbek** [comment]
Markdown to HTML conversion is done by <https://github.com/hoedown/hoedown> and it doesn't seem to support it right night. `HOEDOWN_EXT_FOOTNOTES` is already turned on and footnotes like this already work:

```
Here's an inline link to [Google](http://www.google.com/). Here's a
reference-style link to [Google][1]. Here's a very readable link to
[Yahoo!][yahoo].

  [1]: http://www.google.com
  [yahoo]: http://www.yahoo.com/
```

You can also experiment by altering the generated html code for the preview in a Script.
You might take a look at `function noteToMarkdownHtmlHook` in 
<https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/example.qml>.

Please let me know if you find a solution.

**Comment by N-Upchurch** [comment]
Was footnote support ever implemented by hoedown? Footnote references (see below) are not displayed as links in QOwnNotes, and the footnotes themselves run together in the preview.

```
Banana[^1]
[^1]: A squishy yellow fruit
```
![image](https://user-images.githubusercontent.com/8893713/215569092-ba03ab45-004c-4832-9f90-1c86262fc44b.png)

**Comment by pbek** [comment]
We use md4c for a while, no support for that too.

**Comment by N-Upchurch** [comment]
Got it. Looks like there is [a feature request from three years ago](https://github.com/mity/md4c/issues/106) for footnote support in md4c.

**Comment by pbek** [comment]
Not much going on there 😁

**Comment by Beurt** [comment]
> Not much going on there grin

There was an issue about this (<https://github.com/pbek/QOwnNotes/issues/270>). I think that, in the preview, this is something a script can do.

On the editor side, scripting would require to be able to capture clicks on a specific string  to implements the jump to the note.
