### ISSUE TITLE
Line wrapping in the codeblock 

### ISSUE THREAD

**Issue by lindXdeep** [pbek/QOwnNotes#2701]
#### Expected behaviour

when the text wrapping is enabled in the editor and preview views - so that the code text does not wrap in the codeblock.

#### Actual behaviour

when the text wrapping is enabled in the editor and preview views, - then wrapping text code in the codeblock.

#### Steps to reproduce

all time

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

not

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

not

</details>

**Comment by lindXdeep** [comment]
Most of all, the editor lacks that when the text wrapping is enabled in the editor and preview views - so that the code text does not wrap in the codeblock.

This is implemented in Typora and etc.

This is the one thing that bring severe inconvenience, because when large parts of code merge into one mess.
Conversely, if disabled the text wrapping, then it becomes impossible to read plain text, that out of codeblock.

Is it possible to make, that the text does not wrapping in the code block?

**Comment by pbek** [comment]
Can you please provide an example text and describe step by step what you did and what you expected (best with a screenshot)?

**Comment by Waqar144** [comment]
This is a won't fix. What you're seeing is expected behavior. 

We don't do text layouting ourselves, so this is not in our hands.
