### ISSUE TITLE
Page template, for create prefilled page.

### ISSUE THREAD

**Issue by cezarovidiu** [pbek/QOwnNotes#271]

**Comment by pbek** [comment]
When would that page template be used?

**Comment by pbek** [comment]
There already is a script for custom note names: <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/custom-new-note-headline.qml>

**Comment by cezarovidiu** [comment]
Where to put the customization file in the folder qownnotes

**Comment by pbek** [comment]
If you are talking of the `.qml` files, it doesn't matter. You can configure that in the scripts settings.

**Comment by cezarovidiu** [comment]
thank you

**Comment by pbek** [comment]
I think you also need to pay attention to the latest changes of #272.
