### ISSUE TITLE
Password Not Valid Prompt for encrypted notes despite providing the correct password

### ISSUE THREAD

**Issue by codeRetard** [pbek/QOwnNotes#2710]
I use QOwnNotes for making notes which are stored both locally, and some of them are also synced to my online shared cloud storage provider pCloud for years now. 

The notes which are synced with the pCloud shared directory are accessed from different offices by other installations of QOwnNotes, but never at the same time.

Naturally some of the the notes are encrypted, which are usually accessed and edited through the use of the edit encrypted note feature of the application. All the encryption passwords are kept in a password manager.

One such note was working just fine until the day before yesterday, but when being accessed today the application is prompting a "It seems that you password is not valid" message despite the encryption password being copied and pasted from the password manger, as opposed to manual entry.

pCloud keeps a rather inconsistent series of past versions of all files synced to it. The latest available version fro recovery of this specific note has been for more than two weeks ago on Jan 9th, 2023. When recovered the note can be opened using the same password from the password manager.

The problem is I have entered very important notes ever since Jan 9th that I cannot lose. I was wondering if you can help me figure this out somehow, I really need to have those notes back

#### Expected behaviour

Edit / Decrypt encrypted note through the use of the menu bar buttons on the top menu

#### Actual behaviour

I receive a prompt saying: "It seems that you password is not valid"

#### Output from the debug section in the settings dialog

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed Jan 25 08:43:19 2023`
**Version**: `23.1.1`
**Build date**: `Jan 17 2023`
**Build number**: `1004`
**Platform**: `linux`
**Operating System**: `openSUSE Tumbleweed`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AppImage`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/home/taker/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/taker/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/home/taker/Apps/QOwN/QOwnNotes-x86_64.AppImage`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080`
**Icon theme**: `breeze`
**Notes in current note folder**: `82`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `en_US`
**Language codes**: `en_US`
**Language names**: `American English (United States)`
**Application dictionaries path**: `/home/taker/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-2`
**localPath**: `/home/taker/pCloudOffline/My Corner/Documents/OwnN`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `yes`
**activeNoteSubFolder name**: `Personal`
**database file**: `/home/taker/pCloudOffline/My Corner/Documents/OwnN/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `true`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `/home/taker/pCloudOffline/My Corner/Backups/QOwN/Settings`
**FileDialog/LastPath-SettingsExport** (QString): `/home/taker/pCloudOffline/My Corner/Backups/QOwN/Settings`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2023-01-25T08:14:46.338`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Personal-Projects, Personal`
**MainWindow/noteTextEdit.code.font** (QString): `Hack,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Hack,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (QString): `600`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): `Live-Observations-1-21-2023, Live-Observations`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): 
```
Personal, Personal
CuntWatch
```
**NoteFolder-1/allowDifferentNoteFileName** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 7 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `6`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `true`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `5d4e5c58-484f-4f67-a297-12cf17b8eb54`
**cursorWidth** (QString): `1`
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full-vertical`
**insertTimeFormat** (QString): `hh:mm`
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `18`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `false`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `50`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/taker/pCloudOffline/My Corner/Documents/OwnN`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `qvB6EPNheZQZ`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QString): `Note 2022-12-20T11.00.39`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `en_US`
**systemIconTheme** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionSave_modified_notes, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (QString): `22222`
**workspace-5d4e5c58-484f-4f67-a297-12cf17b8eb54/name** (QString): `Full-Parallel`
**workspace-5d4e5c58-484f-4f67-a297-12cf17b8eb54/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-5d4e5c58-484f-4f67-a297-12cf17b8eb54/windowState** (QByteArray): `<binary data>`
**workspace-X93cMFTdfcax/name** (QString): `Preview only`
**workspace-X93cMFTdfcax/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-X93cMFTdfcax/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspace-qvB6EPNheZQZ/name** (QString): `Full vertical`
**workspace-qvB6EPNheZQZ/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-qvB6EPNheZQZ/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, X93cMFTdfcax, qvB6EPNheZQZ, 5d4e5c58-484f-4f67-a297-12cf17b8eb54`

## System environment

**HOME**: `/home/taker`
**LANG**: `en_US.UTF-8`
**LOGNAME**: `taker`
**PATH**: `/home/taker/bin:/usr/local/bin:/usr/bin:/bin`
**SHELL**: `/bin/bash`
**SYSTEMD_EXEC_PID**: `2234`
**USER**: `taker`
**XDG_DATA_DIRS**: `/home/taker/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_CONFIG_DIRS**: `/home/taker/.config/kdedefaults:/etc/xdg:/usr/local/etc/xdg:/usr/etc/xdg`
**AUDIODRIVER**: `pulseaudio`
**CONFIG_SITE**: `/usr/share/site/x86_64-pc-linux-gnu`
**CPU**: `x86_64`
**CSHEDIT**: `emacs`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**DEBUGINFOD_URLS**: `https://debuginfod.opensuse.org/`
**DESKTOP_SESSION**: `/usr/share/xsessions/plasma5`
**DISPLAY**: `:0`
**FROM_HEADER**: *empty*
**GPG_TTY**: `not a tty`
**GTK2_RC_FILES**: `/etc/gtk-2.0/gtkrc:/home/taker/.gtkrc-2.0:/home/taker/.config/gtkrc-2.0`
**GTK_IM_MODULE**: `cedilla`
**GTK_MODULES**: `canberra-gtk-module`
**GTK_RC_FILES**: `/etc/gtk/gtkrc:/home/taker/.gtkrc:/home/taker/.config/gtkrc`
**GUESTFISH_INIT**: `\e[1;34m`
**GUESTFISH_OUTPUT**: `\e[0m`
**GUESTFISH_PS1**: `\[\e[1;32m\]><fs>\[\e[0;31m\]`
**GUESTFISH_RESTORE**: `\e[0m`
**G_BROKEN_FILENAMES**: `1`
**G_FILENAME_ENCODING**: `@locale,UTF-8,ISO-8859-15,CP1252`
**HISTSIZE**: `1000`
**HOST**: `localhost.localdomain`
**HOSTNAME**: `localhost.localdomain`
**HOSTTYPE**: `x86_64`
**JAVA_BINDIR**: `/usr/lib64/jvm/jre-openjdk/bin`
**JAVA_HOME**: `/usr/lib64/jvm/jre-openjdk`
**JAVA_ROOT**: `/usr/lib64/jvm/jre-openjdk`
**JRE_HOME**: `/usr/lib64/jvm/java-11-openjdk-11`
**KDE_APPLICATIONS_AS_SCOPE**: `1`
**KDE_FULL_SESSION**: `true`
**KDE_SESSION_UID**: `1000`
**KDE_SESSION_VERSION**: `5`
**LESS**: `-M -I -R`
**LESSCLOSE**: `lessclose.sh %s %s`
**LESSKEY**: `/usr/etc/lesskey.bin`
**LESSOPEN**: `lessopen.sh %s`
**LESS_ADVANCED_PREPROCESSOR**: `no`
**LIBVA_DRIVER_NAME**: `iHD`
**MACHTYPE**: `x86_64-suse-linux`
**MAIL**: `/var/mail/taker`
**MANPATH**: `/usr/local/man:/usr/share/man`
**MANPATHISSET**: `yes`
**MINICOM**: `-c on`
**MORE**: `-sl`
**OSTYPE**: `linux`
**PAGER**: `less`
**PROFILEREAD**: `true`
**PWD**: `/home/taker`
**PYTHONSTARTUP**: `/etc/pythonstart`
**QEMU_AUDIO_DRV**: `pa`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**QT_IM_MODULE**: `xim`
**QT_IM_SWITCHER**: `imsw-multi`
**SESSION_MANAGER**: `local/localhost.localdomain:@/tmp/.ICE-unix/2175,unix/localhost.localdomain:/tmp/.ICE-unix/2175`
**SHLVL**: `0`
**SSH_AGENT_PID**: `2087`
**SSH_ASKPASS**: `/usr/libexec/ssh/ssh-askpass`
**SSH_AUTH_SOCK**: `/tmp/ssh-XXXXXXXehA2X/agent.2021`
**TERM**: `xterm`
**VENDOR**: `suse`
**WINDOWMANAGER**: `/usr/bin/startplasma-x11`
**XAUTHLOCALHOSTNAME**: `localhost.localdomain`
**XAUTHORITY**: `/run/user/1000/xauth_WMxpIU`
**XCURSOR_SIZE**: `24`
**XCURSOR_THEME**: `breeze_cursors`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_SEAT**: `seat0`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_DESKTOP**: `KDE`
**XDG_SESSION_ID**: `3`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**XDG_SESSION_TYPE**: `x11`
**XDG_VTNR**: `7`
**XKEYSYMDB**: `/usr/X11R6/lib/X11/XKeysymDB`
**XMODIFIERS**: `@im=local`
**XNLSPATH**: `/usr/share/X11/nls`
**XSESSION_IS_UP**: `yes`
**MANAGERPID**: `1996`
**INVOCATION_ID**: `5f58261f2600445089c28095d7b32140`
**JOURNAL_STREAM**: `8:36938`
**APPIMAGE**: `/home/taker/Apps/QOwN/QOwnNotes-x86_64.AppImage`
**ARGV0**: `/home/taker/Apps/QOwN/QOwnNotes-x86_64.AppImage`
**APPDIR**: `/tmp/.mount_QOwnNoX5ZHEf`
**OWD**: `/home/taker/Apps/QOwN`

**Comment by pbek** [comment]
I fear that pCloud might have corrupted the data, then any password you would have tried would be invalid. Do you have a backup of the file?
