### ISSUE TITLE
Support atx-style headers

### ISSUE THREAD

**Issue by minthemiddle** [pbek/QOwnNotes#272]
Now that filename and note header can be different, it would be very convenient if QOwnNotes gave the option to use _atx-style_ headers (`#`, `##`, ...) instead of _setext_.

**Comment by pbek** [comment]
There already is a script for custom note headlines: https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/custom-new-note-headline.qml

Does that work for you?

**Comment by minthemiddle** [comment]
Scripting seems the way to go, but unfortunately that does not work.

(1) Changing the script to my liking

```
    function handleNewNoteHeadlineHook() {
        var date = new Date();
        return "# " + date.toISOString();
    }
}
```
(2) Creating a new note
(3) Here is what you get

```
# 2016-07-30T14:22:06.412Z
==========================
```

The other problem I'm facing:

When I search for something that does not exist and create a note from there, this script is being ignored.

**Comment by pbek** [comment]
I guess I will put that on my todo list.

**Comment by pbek** [comment]
## 16.08.0
- the scripting hook `handleNewNoteHeadlineHook()` now has a parameter
  to pass the text that would be used to create the headline
    - the hook will now also be called when using the search line edit 
    - if you are using the hook you have to add the parameter to the
      function in your script, so that the scripting engine will find
      your function call
    - if the headline text was modified by the hook no underline 
      characters `===` will be added automatically, you have to do that
      in your script
    - take a look at the updated example at
      [custom-new-note-headline.qml](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/custom-new-note-headline.qml)
    - you now can use the hook to create your own headline styles, 
      for example using `# headline` instead of `headline`, followed by
      `==========`
        - if you are doing this don't forget to allow the note
          headline to be different from the note filename in the
          general settings

@genvoa, be also aware of these changes

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by minthemiddle** [comment]
Yes, that works flawless now. Superb!

**Comment by pbek** [comment]
Great, thank you for testing!
