### ISSUE TITLE
Notes icon to stylesheet

### ISSUE THREAD

**Issue by Arty2** [pbek/QOwnNotes#2724]
Proposing to move the notes' icon to the theme stylesheets, so that they can be restyled by each theme.
Currently the icon has a blue-gray color and this may or may not work well with different background colors.

e.g. lines 662, 1967, 2167 https://github.com/pbek/QOwnNotes/blob/230c2b40dbe0f32edb3fbcd1a96dbd5ec6abcb24/src/mainwindow.ui#L662

Perhaps this can also apply to other UI icons such as tags, folders etc. Several other icons and cursors are already configurable with QCSS.

**Comment by pbek** [comment]
I'm not sure if everything could be styled by stylesheets, especially icons in rows in a QTreeWidget. You would need to do more experiments. See https://github.com/pbek/QOwnNotes/issues/2723#issuecomment-1420362512 for a link to examples and the Qt documentation.

**Comment by pbek** [comment]
The stylesheets also would need to support inline SVGs (if you want to research that).
