### ISSUE TITLE
Folding URLs in Markdown hyperlinks and images

### ISSUE THREAD

**Issue by Arty2** [pbek/QOwnNotes#2725]
Proposing a a feature to display the URLs in Markdown hyperlinks “folded”, so that they expand on click / focus. This would make documents with many links less cluttered visual.

This is the approach of MarkdownEditing plugin for SublimeText:
![image](https://user-images.githubusercontent.com/3519269/217034423-d8730966-2ecd-4584-b52d-69933e86f790.png)

Possibly related to #2126 and technically hard to implement due to render constrains.
Congrats for making such a feature complete and customizable tool; currently in the process of switching tools and enjoying it!

**Comment by pbek** [comment]
> Possibly related to https://github.com/pbek/QOwnNotes/issues/2126 and technically hard to implement due to render constrains.

Yes and yes. 😆  I don't really want to rip QPlainTextEdit apart for such things. 😅 

> Congrats for making such a feature complete and customizable tool; currently in the process of switching tools and enjoying it!

Thank you, especially the "switching tools" part is important for me... I don't even want to be locked in into tools where I was involved in. 😁
