### ISSUE TITLE
QOwnNotes hides notes which differ only in letter case

### ISSUE THREAD

**Issue by Morganlej** [pbek/QOwnNotes#2727]
#### Expected behaviour

Dont hide notes of different case!
It is OK to hinder users to create them due to problems on some systems
https://github.com/pbek/QOwnNotes/issues/1988
But a solution should be designed to not disrupt.

#### Actual behaviour

Introduced by issue 1988

If user have notes with names that differ only in case like "note", "Note", "NOTE", only one is displayed - QOwnNotes hides the rest from the user!

This is blocking us from updating this app in our distro.
https://bugs.mageia.org/show_bug.cgi?id=30240#c6

#### Steps to reproduce

1) In a version earlier than 20.12.7, create notes with names "note", "Note", "NOTE"
  (or create such named files by other means)
2) Update to current version
3) See QOwnNotes do not list "Note" nor "NOTE"

They are still there, and a workaround is for user to use i.e Nextcloud file browser to rename them.
Problem is, user need to know this bug.

**Comment by pbek** [comment]
Hah, interesting find. Thank you. I'll look into that! Maybe I was trying to get around issues with filesystems that make no difference between cases...

**Comment by Morganlej** [comment]
Thank you for the quick response :)
I will try to remember to check your progress here now and then.

**Comment by pbek** [comment]
You are right, the change in the in-memory notes database was made for #1988.

**Comment by pbek** [comment]
>  It is OK to hinder users to create them due to problems on some systems

The question is, how... 🤔  In the past I found no way to tell what the filesystem of the note folder supports. Note filenames are created automatically from the note text or chosen manually or even altered by scripts...
If the filesystem (NTFS in the case of #1988) doesn't support cases... Files get simply overwritten if the name is "similar".

Any suggestions?

**Comment by Morganlej** [comment]
Keep hindering uses creating filenames that may conflict, per #1988

But still display all already existing files.

- is that possible?

**Comment by Morganlej** [comment]
Read-only, and if user tries to edit/save, dialogue to choose another name?

**Comment by pbek** [comment]
> dialogue to choose another name?

That wouldn't be possible, see: *Note filenames are created automatically from the note text (most of the time in places where no user-interaction is possible)*

**Comment by Morganlej** [comment]
Hm. I know only little about this program and am no programmer either.

Trying: When user opens a file with "conflicting" name, immediately pop up a dialog to tell him to edit the note text first line, and tell him why, and do not save file until OK

**Comment by Morganlej** [comment]
Actually, testing in current version I see you already have some same-filename avoiding mechanism.

If i have file "note" and open a new note and only enter text "note" it gets saved as "note 1". Yet another gets saved as "note 2"

_Maybe this can be utilised to allow opening the "conflicting" files, and they get automatically saved with an added number by that already existing mechanism?_

**Comment by pbek** [comment]
> Trying: When user opens a file with "conflicting" name, immediately pop up a dialog to tell him to edit the note text first line, and tell him why, and do not save file until OK

There are many ways how notes are opened only some are manual. This wouldn't work in most of the cases and the first line is only ONE way how note file names are determined (and that even can be turned off).

**Comment by pbek** [comment]
> If i have file "note" and open a new note and only enter text "note" it gets saved as "note 1". Yet another gets saved as "note 2"

that currently is the way things work

> Maybe this can be utilised to allow opening the "conflicting" files, and they get automatically saved with an added number by that already existing mechanism?

that still is a manual process (hidden somewhere), nobody expects such a dialog
And I (as user) don't know (or care) what is "allowed" on my filesystem...

**Comment by Morganlej** [comment]
Thinking about https://github.com/pbek/QOwnNotes/issues/1988
IIRC about problems i read years ago (seldom using MSWindows anymore), such filename character case problems was due to backward compatibility with 8.3 tyep filename (8 char plus dot plus three char).  But if a filename is longer than  that this problem will not strike.  (If i am correct (DO CHECK) an alternate solution to 1988 would be to make sure filenames are always long enough not to create that hidden alternate shortname that modern MSWindows create, and thus avoids that MS-made problem.

**Comment by pbek** [comment]
> make sure filenames are always long enough

any suggestions how that should work when the user is in (almost) full control about the filename? (keep https://github.com/pbek/QOwnNotes/issues/2727#issuecomment-1420458944 in mind, there are many ways filenames can be altered)

**Comment by Morganlej** [comment]
**Anyway, quick test of Explorer on Windows7:**
1) create "abc.txt" - OK
2) create "Abc.txt" - dialogue suggest "Abc (2).txt", I accept.  
3) create "ABC.txt" - dialogue suggest "ABC (3).txt", I accept.  
Result: files "abc.txt", "Abc (2).txt", "Abc (3).txt"

Note the the main part is exactly as user wanted, the program only add numbers.
What if QOwnNotes do the same number adding when necessary - with or without asking?

_It should do this regardless of operating or file system, as files may be synced between._

**Comment by DavidWHodgins** [comment]
This is a database design issue.

Currently one table is being used with two fields. The  note name  and the note text with the note name being used
as a unique key. The table can be stored with the backend being  files or database entries.

Using the notename as a key leads to two issues. Some backends allow mixed case, some do not. In additon the notename can be altered which requires either a rename or a copy/delete depending on the backend.

There are two standard ways of avoiding such issues.
1. Use a sequential number as the key, or generate a random string to use as the key.  Requires either checking
the db for what the last used key was or storing the last used key somewhere (making sure it's kept in sync with
the db).
2.  Use a random string as the key.  Requires checking the db to ensure the newly generated string has not already
been used.

The application would then use two tables. One with the generated key and the note name, and one with the generated
key and the note text.

If using a file system there would be one directory for each table with the generated keys used for the file names within
those directories and the note name/text as the contents. If using a  db, the generated key would be used as the unique key in the two tables.

As part of changing the database design, every future update should check to see if the existing db used the new
design or not, and convert the database to the new design. This should be included in every update as the user may
have skipped versions.

**Comment by DavidWHodgins** [comment]
I should add, since the backend may any type of file system, the key should be limited to 11 characters acceptable as a
fat12  file name (Upper case letters A–Z, Numbers 0–9), since the key is used as the filename when not using a db.

**Comment by pbek** [comment]
May I ask with database and table you are talking about (and where do you get your information from)?

I think we shouldn't focus so much about the implementation details in the beginning, but rather on the "how not to break things for case-insensitive filesystems while being case-sensitive".

I for my part don't have an issue with the case-insensitiveness, I wouldn't dare using "Note.md" and "note.md" together, even on Linux, my main operating system. I want my sensitive data to be portable...
