### ISSUE TITLE
Ubuntu-18.04 GitHub Images were removed!

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#2728]
See: https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/

This was executed just now.
Snap and AppImage building is affected.

**Comment by pbek** [comment]
Snaps can't be built with Ubuntu > 18.04, see https://github.com/samuelmeuli/action-snapcraft/pull/23

**Comment by pbek** [comment]
## 23.3.1
- the whole **AppImage build process was re-invented** because the necessary
  Ubuntu 18.04 build system will vanish from GitHub with the end of March

The Snapcraft part isn't working yet...

**Comment by Beurt** [comment]
Hi, 

> ## 23.3.1
> 
>     * the whole **AppImage build process was re-invented** because the necessary
>       Ubuntu 18.04 build system will vanish from GitHub with the end of March
> 

Unfortunately, since 23.3.1, I cannot update the Appimage.

While trying to update I have the error:

> Your QOwnNotes executable '/tmp/.mount_QOwnNo1w0Hij/AppRun.wrapped' is not writeable! It must be writeable by the current user in order to be updated.



![Screenshot_20230313_173944](https://user-images.githubusercontent.com/12588136/224767884-297a7c00-b50e-4c6e-b37c-e7f0d34a9b23.png)

<details><summary>Expand Logs</summary>

```log
[mars 13 17:43:47] [debug]: loadNoteDirectoryList
[mars 13 17:43:47] [debug]: reloadTagTree
[mars 13 17:43:47] [debug]: handleScriptingNotesTagUpdating
[mars 13 17:43:47] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(1)
[mars 13 17:43:47] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(1)
[mars 13 17:43:47] [debug]: reloadNoteSubFolderTree
[mars 13 17:43:47] [debug]: reload
[mars 13 17:43:48] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(1)
[mars 13 17:43:48] [debug]: reloadNoteSubFolderTree
[mars 13 17:43:48] [debug]: reload
[mars 13 17:43:49] [debug]: loadNoteDirectoryList
[mars 13 17:43:49] [debug]: reloadTagTree
[mars 13 17:43:49] [debug]: handleScriptingNotesTagUpdating
[mars 13 17:43:49] [debug]: Reply from  "/ocs/v2.php/apps/files_sharing/api/v1/shares"
[mars 13 17:43:49] [debug]: Reply from share api
[mars 13 17:43:49] [debug]: updateNoteShareStatusFromShare  - 'data':  "…"
[mars 13 17:43:49] [debug]: updateNoteShareStatusFromShare  - 'status':  "ok"
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'dataElements.count()':  5
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'shareType':  "3"
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'itemType':  "folder"
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'shareType':  "3"
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'itemType':  "file"
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'shareType':  "3"
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'itemType':  "file"
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'shareType':  "3"
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'itemType':  "file"
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'shareType':  "3"
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'itemType':  "file"
[mars 13 17:43:49] [debug]: updateNoteShareStatusFromFetchAll  - 'data':  "…"
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'dataElements.count()':  5
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'shareType':  "3"
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'itemType':  "folder"
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'shareType':  "3"
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'itemType':  "file"
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'shareType':  "3"
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'itemType':  "file"
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'shareType':  "3"
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'itemType':  "file"
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'shareType':  "3"
[mars 13 17:43:49] [debug]: updateNoteShareStatus  - 'itemType':  "file"
[mars 13 17:43:49] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(1)
[mars 13 17:43:49] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(1)
[mars 13 17:43:49] [debug]: reloadNoteSubFolderTree
[mars 13 17:43:49] [debug]: reload
[mars 13 17:43:50] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(1)
[mars 13 17:43:54] [debug]: dialogButtonClicked  - 'releaseUrl':  "https://github.com/pbek/QOwnNotes/releases/download/v23.3.2/QOwnNotes-x86_64.AppImage"
[mars 13 17:43:55] [debug]: Reply from  "/github-production-release-asset-2e65be/27436491/a3aa9b27-2f12-41e1-8166-de346ee8b57b"
[mars 13 17:43:55] [debug]: slotReplyFinished  - 'data.size':  45864128
[mars 13 17:43:55] [debug]: initializeLinuxUpdateProcess  - 'filePath':  "/tmp/QOwnNotes-dOvVWz.AppImage"
[mars 13 17:43:55] [debug]: initializeLinuxUpdateProcess  - 'appPath':  "/tmp/.mount_QOwnNo1w0Hij/AppRun.wrapped"
```
</details>

I'm using an Ubuntu fork (KDE Neon), the Appimage is sitting in a sub-directory of the `/home`, which is on a btrfs partition. No rights have changed since the last QON update.

**Comment by pbek** [comment]
- **Application arguments**: `/tmp/.mount_QOwnNoaBCNlq/AppRun.wrapped`
    - that's the wrong path reported in the application by `argv[0]`!
- **APPIMAGE**: `/home/omega/Downloads/QOwnNotes-x86_64.AppImage`
    - looks good
- **ARGV0**: `/home/omega/Downloads/QOwnNotes-x86_64.AppImage`
    - looks good too

**Comment by pbek** [comment]
## 23.3.3
- unfortunately since 23.3.1 the **AppImage reports the wrong application path**, because
  of that update mechanism fails, this **should (could) be fixed** after this release

**Comment by pbek** [comment]
@Beurt, can you please try to download and run 23.3.3, enable the version faking checkbox (see screenshot) and try the update mechanism?

![image](https://user-images.githubusercontent.com/1798101/224810228-cb2da012-b107-47f1-843a-05553ab2c4bd.png)

**Comment by pbek** [comment]
https://github.com/pbek/QOwnNotes/releases/download/untagged-8e2cc554b2340f4477fe/QOwnNotes-x86_64.AppImage

**Comment by probonopd** [comment]
>  deployment tool by @probonopd (that unfortunately only seems to work on Ubunutu 18.04)

By policy, `linuxdeployqt` tries to ensure that all AppImages produced using it will run on the oldest still-supported Ubuntu version. As Ubuntu 18.04 ‘Bionic Beaver’ is reaching End of Standard Support this May, `linuxdeployqt` will then be updated to allow using the then oldest still-supported Ubuntu version, which will be 20.04.

**Comment by pbek** [comment]
Thank you, @probonopd! I love probonopd/linuxdeployqt, fixes all kind of issues I now had to get around in many weeks (since I wasn't able to get a Ubuntu18 container actually running with everything the actions need) in:
 
https://github.com/pbek/QOwnNotes/blob/331bf10e0b6c107144cb63423360a739ecaf1960/.github/workflows/build-release.yml#L118-L143

But I do build in Ubuntu 20.04 now!

**Comment by pbek** [comment]
> ~https://github.com/pbek/QOwnNotes/releases/download/untagged-8e2cc554b2340f4477fe/QOwnNotes-x86_64.AppImage~
> 
> https://github.com/pbek/QOwnNotes/releases/download/v23.3.3/QOwnNotes-x86_64.AppImage

@Beurt, updating the AppImage seems to work for me again.

**Comment by Beurt** [comment]
Sorry @pbek for the late answer!

I tried v23.3.3 and faking the update works fine! Thank you!

**Comment by pbek** [comment]
Great, thank you!

**Comment by pbek** [comment]
Finally...

## 23.3.4
- the **amd64 Snap build process was re-invented**, because the necessary
  Ubuntu 18.04 build system will vanish from GitHub with the end of March
