### ISSUE TITLE
Tree view for sub-folders shows wrong note content in folders beyond the first one.

### ISSUE THREAD

**Issue by chaosdrop** [pbek/QOwnNotes#2730]
![Folder showing last note from previous folder](https://user-images.githubusercontent.com/3247343/217364133-60d53d2a-b9a0-4a2b-9f2c-4f0784116919.jpg)

When the tree view is enabled all folders beyond the first folder show the last note of the previous folder, instead of the first note of their own folder. 

Folder <--- [shows "Note a" content when selected]
- Note a
- Note b
Folder 2 <--- [shows "Note b" content when selected, should show "Note c" content.]
- Note c
- Note d

**Comment by pbek** [comment]
Looks like you are talking about the work in progress feature #790, right?
If yes, then best deposit your request there... 😉
