### ISSUE TITLE
Tree view discussion/queston

### ISSUE THREAD

**Issue by chaosdrop** [pbek/QOwnNotes#2731]
Since it's listed as an "in progress" feature, but is a key feature of my current note taking program that I am jumping ship from I was wondering if you would like feedback from me on expected/most desired features & bugs or if you already have a vision in mind and would rather not be overly pestered about it until it's finished.

**Comment by pbek** [comment]
Looks like you are talking about #790, right?
I've currently not a lot of ambition for that (huge) feature.
#1304 and #2728 are consuming my time.
