### ISSUE TITLE
Sudden constant server disconnects, app no longer usable, no changes on my end.

### ISSUE THREAD

**Issue by roo-punch** [pbek/QOwnNotes#2733]
Hello, I tried submitting via help menu but next button remained greyed out. 

#### Expected behaviour

Qownnotes app has been running fine for over a year without issue. On the settings page for Nextcloud instance, connection details are filled out, and connection status shows ok. I should be able to create / modify notes and have changes synced back to nextcloud.

#### Actual behaviour
When typing into a note, a pop up interrupts saying "Server error: internal server error, check your confiugration". It leads to the settings page. I am able to successfully connect to my nextcloud instance. I click ok, and then the issue repeats as soon as I start editing a note.

#### Steps to reproduce
Unsure, on my end it is simply editing a note

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

[Feb 12 12:16:47] [debug]: Set proxy configuration to use NO proxy
[Feb 12 12:16:48] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[Feb 12 12:16:48] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"nextcloud" <serverUrl>"https://nextcloudurl.com" <username>"nextcloud" <priority>0
[Feb 12 12:16:48] [debug]: buildNotesIndex  - 'noteSubFolderId':  0
[Feb 12 12:16:49] [debug]: setupNoteFolderTables  - 'database version':  15
[Feb 12 12:16:49] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"nextcloud" <serverUrl>"https://nextcloudurl.com" <username>"nextcloud" <priority>0
[Feb 12 12:16:49] [debug]: fetchShares  - 'url':  QUrl("https://nextcloudurl.com/ocs/v2.php/apps/files_sharing/api/v1/shares")
[Feb 12 12:16:49] [debug]: loadNoteDirectoryList
[Feb 12 12:16:49] [debug]: reloadTagTree
[Feb 12 12:16:49] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(1)
[Feb 12 12:16:49] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(1)
[Feb 12 12:16:49] [debug]: reloadNoteSubFolderTree
[Feb 12 12:16:49] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(1)
[Feb 12 12:16:49] [debug]: reloadNoteSubFolderTree
[Feb 12 12:16:49] [debug]: loadNoteDirectoryList
[Feb 12 12:16:49] [debug]: reloadTagTree
[Feb 12 12:16:49] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(1)
[Feb 12 12:16:49] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(1)
[Feb 12 12:16:49] [debug]: reloadNoteSubFolderTree
[Feb 12 12:16:49] [debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  QVector(1)
[Feb 12 12:16:52] [debug]: Reply from  "/ocs/v2.php/apps/files_sharing/api/v1/shares"
[Feb 12 12:16:52] [warning]: "QNetworkReply error 401 from url https://nextcloudurl.com/ocs/v2.php/apps/files_sharing/api/v1/shares: " "Error transferring https://nextcloudurl.com/ocs/v2.php/apps/files_sharing/api/v1/shares - server replied: Internal Server Error"
[Feb 12 12:16:52] [debug]: Reply from share api
[Feb 12 12:16:52] [debug]: updateNoteShareStatusFromShare  - 'status':  "failure\n"
[Feb 12 12:16:54] [debug]: Set proxy configuration to use NO proxy
[Feb 12 12:16:55] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"nextcloud" <serverUrl>"https://nextcloudurl.com" <username>"nextcloud" <priority>0
[Feb 12 12:16:55] [debug]: Set proxy configuration to use NO proxy
[Feb 12 12:16:57] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"nextcloud" <serverUrl>"https://nextcloudurl.com" <username>"nextcloud" <priority>0
[Feb 12 12:16:57] [debug]: Reply from  ""
[Feb 12 12:16:57] [debug]: Reply from main server url
[Feb 12 12:16:57] [debug]: Reply from  ""
[Feb 12 12:16:57] [debug]: Reply from main server url
[Feb 12 12:16:59] [debug]: storing note file:  "pricing 2021-10-13T20.33.58.txt"
[Feb 12 12:16:59] [debug]: stored note:  Note: <id>43 <name>"pricing 2021-10-13T20.33.58" <fileName>"pricing 2021-10-13T20.33.58.txt" <noteSubFolderId>1 <relativePath>"Onsales" <hasDirtyData>false
[Feb 12 12:16:59] [debug]: storeUpdatedNotesToDisk  - 'count':  1
[Feb 12 12:16:59] [status]: Stored 1 note(s) to disk
[Feb 12 12:16:59] [debug]: Reply from  "/ocs/v1.php"
[Feb 12 12:16:59] [debug]: Reply from ownCloud test page
[Feb 12 12:17:00] [debug]: Reply from  "/ocs/v1.php/cloud/capabilities"
[Feb 12 12:17:00] [debug]: Reply from capabilities page
[Feb 12 12:17:02] [debug]: Reply from  "/ocs/v1.php"
[Feb 12 12:17:02] [debug]: Reply from ownCloud test page
[Feb 12 12:17:02] [debug]: Reply from  "/ocs/v1.php/cloud/capabilities"
[Feb 12 12:17:02] [debug]: Reply from capabilities page
[Feb 12 12:17:03] [debug]: Reply from  "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[Feb 12 12:17:03] [debug]: Reply from app info
[Feb 12 12:17:05] [debug]: Reply from  "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[Feb 12 12:17:05] [debug]: Reply from app info

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.

But it looks like your Nextcloud server is producing internal server errors with its share api. You should check the error log on your Nextcloud server.

**Comment by roo-punch** [comment]
Hey. Thanks for the response. I did have a look at nextcloud error log and am not seeing anything stand out.

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mon Feb 13 14:45:13 2023`
**Version**: `21.6.1`
**Build date**: `Jun  7 2021`
**Build number**: `840`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\roopunch\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Users\roopunch\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080, 800x480, 1920x1080, 1920x1080, 1920x1080, 1920x1080, 1920x1080`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `139`
**Calendar items**: `441`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://nextcloudurl.com`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `25.0.3.2`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\roopunch\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `E:\Nextcloud\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `Onsales`
**database file**: `E:\Nextcloud\Notes\notes.sqlite`

## Cloud connections

### Cloud connection `nextcloud`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://nextcloudurl.com`
**username**: `nextcloud`

## Enabled scripts

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `true`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**LastUpdateCheck** (QDateTime): `2023-02-13T14:43:36.447`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `14`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,7,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Consolas,8,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (int): `600`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): `onsales 2023-01-25T11.42.37`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `Onsales`
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `199`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TrashDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `txt`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): `ddd MMMM d yy hh:mm`
**interfaceFontSize** (int): `9`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (int): `14`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `1`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `E:/Nextcloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `true`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `25.0.3.2`
**recentNoteFolders** (QStringList): `C:/Users/roopunch/Notes`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2023-01-25T11.42.37, Note 2023-01-11T11.43.04, Note 2022-12-28T10.59.47, Note 2022-12-14T12.44.06, Note 2022-12-07T16.34.06, Note 2022-11-30T14.47.15, router, Note 2022-11-16T14.14.29, Note 2022-11-09T08.29.50, Note 2022-11-02T11.42.56, Note 2022-10-26T14.25.16, Note 2022-10-19T15.30.48, Note 2022-10-12T14.29.54, Note 2022-10-05T15.30.28, Note 2022-09-28T12.20.08, Note 2022-09-28T12.20.05, Note 2022-09-23T12.46.10, Note 2022-09-21T12.30.44, Note 2022-09-19T17.12.07, Note 2022-09-19T05.15.56, Note 2022-09-18T17.04.00, Note 2022-09-15T10.48.26, Note 2022-09-14T11.36.39, Note 2022-09-07T14.33.12, Note 2022-08-31T16.28.58, Note 2022-08-24T14.50.57, Note 2022-08-22T18.59.25, Note 2022-08-17T11.22.06, Note 2022-08-10T11.49.52, Note 2022-08-03T11.17.30, Note 2022-08-01T22.50.03, Note 2022-07-27T09.43.21, Note 2022-07-20T06.18.58, Note 2022-07-12T16.06.56, Note 2022-07-11T11.14.02, Note 2022-07-06T13.05.54, Note 2022-06-29T07.54.33, Note 2022-06-22T05.14.42, Note 2022-06-15T09.17.33, Note 2022-06-09T06.57.08, Note 2022-06-08T09.17.42, Note 2022-06-08T07.20.56, Note 2022-06-03T00.03.56, Note 2022-06-01T06.25.15, Note 2022-05-25T11.50.04, Note 2022-05-19T21.38.11, Note 2022-05-18T16.02.43, Note 2022-05-15T14.24.06, Note 2022-05-11T08.57.53, Note 2022-04-29T12.27.47, Note 2022-04-27T09.00.06, Note 2022-04-19T07.49.04, Note 2022-04-13T06.16.02, Note 2022-04-06T05.57.09, Note 2022-04-01T13.16.08, Note 2022-03-16T09.40.54, Note 2022-03-15T11.25.33, Note 2022-03-09T18.24.57, Note 2022-03-09T18.24.50, Note 2022-03-09T07.33.03, Note 2022-02-28T12.01.54, Note 2022-02-22T15.11.14, Note 2022-02-16T07.32.32, Note 2022-02-15T13.38.16, Note 2022-02-09T10.00.51, Note 2022-02-02T07.11.39, Note 2022-01-26T07.45.02, Note 2022-01-22T17.47.58, Note 2022-01-18T11.44.17, Note 2022-01-12T06.40.49, Note 2022-01-06T20.45.49, Note 2021-12-14T07.00.39, Note 2021-12-07T06.35.01, Note 2021-12-01T08.20.02, Note 2021-11-24T10.46.07, Note 2021-11-16T09.29.25, Note 2021-11-10T06.17.25, Note 2021-11-03T10.10.19, Note 2021-10-27T06.30.37, Note 2021-10-20T06.10.58, Note 2021-10-13T20.33.58, Note 2021-10-13T10.42.50, Note 2021-10-10T09.45.29, Note 2021-10-07T16.02.49, Note 2021-10-06T14.12.34, Note 2021-10-06T13.02.31, Note 2021-09-29T11.03.44, Note 2021-09-23T10.31.20, Note 2021-09-15T09.14.12, Note 2021-09-08T11.38.03, Note 2021-09-01T10.59.43, Note 2021-09-01T10.59.35, Note 2021-08-25T10.06.46, Note 2021-08-18T13.49.41, Note 2021-08-16T12.18.42, Note 2021-08-14T21.38.00, Note 2021-08-11T22.13.50, Note 2021-08-11T11.59.37, Note 2021-08-11T07.22.44, Note 2021-08-11T07.21.30`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `forroopunchingToolbar`
**toolbar/2/title** (QString): `forroopunching toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**trashSplitterSizes** (QByteArray): `<binary data>`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\roopunch\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `roopunch-RIG`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**GPU_FORCE_64BIT_PTR**: `0`
**GPU_MAX_ALLOC_PERCENT**: `100`
**GPU_MAX_HEAP_SIZE**: `100`
**GPU_SINGLE_ALLOC_PERCENT**: `100`
**GPU_USE_SYNC_OBJECTS**: `1`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\roopunch`
**LOCALAPPDATA**: `C:\Users\roopunch\AppData\Local`
**LOGONSERVER**: `\\roopunch-RIG`
**NUMBER_OF_PROCESSORS**: `36`
**OneDrive**: `C:\Users\roopunch\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;"C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\;";C:\Program Files (x86)\Intel\Intel(R) Memory And Storage Tool\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\DTN\IQFeed;C:\Program Files\PuTTY\;C:\Users\roopunch\anaconda3;C:\Users\roopunch\anaconda3\Library\mingw-w64\bin;C:\Users\roopunch\anaconda3\Library\usr\bin;C:\Users\roopunch\anaconda3\Library\bin;C:\Users\roopunch\anaconda3\Scripts;C:\Users\roopunch\AppData\Local\Microsoft\WindowsApps;C:\Users\roopunch\anaconda3\pkgs;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 85 Stepping 4, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `5504`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\roopunch\AppData\Local\Temp`
**TMP**: `C:\Users\roopunch\AppData\Local\Temp`
**USERDOMAIN**: `roopunch-RIG`
**USERDOMAIN_ROAMINGPROFILE**: `roopunch-RIG`
**USERNAME**: `roopunch`
**USERPROFILE**: `C:\Users\roopunch`
**windir**: `C:\WINDOWS`

**Comment by pbek** [comment]
Can't see anything standing out in your config.

But your log says:
```
[Feb 12 12:16:52] [warning]: "QNetworkReply error 401 from url https://nextcloudurl.com/ocs/v2.php/apps/files_sharing/api/v1/shares: " "Error transferring https://nextcloudurl.com/ocs/v2.php/apps/files_sharing/api/v1/shares - server replied: Internal Server Error"
```

There really should be a log entry on your NC server for this `Internal Server Error`...

**Comment by roo-punch** [comment]
Thanks for prodding me to look again. Think I found the relevant log entry. 

`[no app in context] Error: OCP\AppFramework\Db\DoesNotExistException: Did expect one result but found none when executing: query "SELECT * FROM `*PREFIX*deck_cards` WHERE `id` = :dcValue1 ORDER BY `order` ASC, `id` ASC";  at <<closure>>

 0. /snap/nextcloud/33587/htdocs/lib/public/AppFramework/Db/QBMapper.php line 362
    OCP\AppFramework\Db\QBMapper->findOneQuery()
 1. /var/snap/nextcloud/33587/nextcloud/extra-apps/deck/lib/Db/CardMapper.php line 140
    OCP\AppFramework\Db\QBMapper->findEntity()
 2. /var/snap/nextcloud/33587/nextcloud/extra-apps/deck/lib/Sharing/ShareAPIHelper.php line 56
    OCA\Deck\Db\CardMapper->find()
 3. /snap/nextcloud/33587/htdocs/apps/files_sharing/lib/Controller/ShareAPIController.php line 320
    OCA\Deck\Sharing\ShareAPIHelper->formatShare()
 4. /snap/nextcloud/33587/htdocs/apps/files_sharing/lib/Controller/ShareAPIController.php line 917
    OCA\Files_Sharing\Controller\ShareAPIController->formatShare()
 5. /snap/nextcloud/33587/htdocs/apps/files_sharing/lib/Controller/ShareAPIController.php line 859
    OCA\Files_Sharing\Controller\ShareAPIController->getFormattedShares()
 6. /snap/nextcloud/33587/htdocs/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Files_Sharing\Controller\ShareAPIController->getShares()
 7. /snap/nextcloud/33587/htdocs/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController()
 8. /snap/nextcloud/33587/htdocs/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch()
 9. /snap/nextcloud/33587/htdocs/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()
10. /snap/nextcloud/33587/htdocs/ocs/v1.php line 63
    OC\Route\Router->match()
11. /snap/nextcloud/33587/htdocs/ocs/v2.php line 23
    require_once("/snap/nextcloud/33587/htdocs/ocs/v1.php")

GET /ocs/v2.php/apps/files_sharing/api/v1/shares
from 192.168.1.5 by nextcloud at 2023-02-14T12:24:35+00:00`

**Comment by pbek** [comment]
I guess a good place to get nextcloud help is https://help.nextcloud.com/.

**Comment by pbek** [comment]
I've no idea why a `DoesNotExistException` produces an Internal Server Error on your NC server...

**Comment by roo-punch** [comment]
Yep, looks like some others may be experiencing same issue, potentially relating to Deck app, but surfacing using QOwnNotes. Will try to pin it down over there, thanks for your help.
