### ISSUE TITLE
How to hide the black square in front of the checkbox?

### ISSUE THREAD

**Issue by rjiang9** [pbek/QOwnNotes#2736]
This happens on both Win 10 and MacBook:

<img width="57" alt="image" src="https://user-images.githubusercontent.com/7293118/219486912-2ac980a0-e42c-42a5-acd1-86dc0ef8cac1.png">

My question is: is it possible to hide the black square in front of a checkbox?

Thanks

**Comment by pbek** [comment]
I'm not sure. You can try via the `Custom note preview styling` script in the script repository to set the bullet style of the list to none.

**Comment by rjiang9** [comment]
Thank you so much @pbek ! For this help and the great progam. 

<img width="88" alt="image" src="https://user-images.githubusercontent.com/7293118/219822667-5af34fa9-474c-44af-afb4-bde5b558fcd9.png">

**Comment by rjiang9** [comment]
For anybody who may wonder about how to do:
Go to 'Scripting settings'->Scripting and install the script @pbek mentioned and no further configuration need and it works:

<img width="404" alt="image" src="https://user-images.githubusercontent.com/7293118/219822810-5a442cd5-f3b2-4f69-a3a0-7fecbccf575d.png">

**Comment by pbek** [comment]
Ah, there's that script too. Even better 😁👍🏻 have fun
