### ISSUE TITLE
Enable and expose strikethrough in interface

### ISSUE THREAD

**Issue by olantrust** [pbek/QOwnNotes#274]
~~Strikethrough~~ seems to appear somewhere in the code - using "~~".
But it doesn't appear to work.
Also, a shortcut key and a button in the interface would be useful for many.

**Comment by pbek** [comment]
## 16.08.0
- <kbd>Alt</kbd> + <kbd>⇧</kbd> + <kbd>S</kbd> now adds the `~~`
  characters to symbolize a strikeout of the selected text
    - strikeout now works in the markdown preview

But I can't show that in the text editor right now, <https://github.com/hoedown/hoedown> doesn't seem to mark them correctly.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by olantrust** [comment]
Great, thanks.
Can't test at the moment, but will when able.
