### ISSUE TITLE
[I] navigation nesting

### ISSUE THREAD

**Issue by p-thor** [pbek/QOwnNotes#2741]
#### Expected behaviour

When adding hash to format the navigation menu if you have ## and below it an item with #### it should just show it as a nested item.  the "one on layer three"  Should show below Second

#### Actual behaviour

"one on layer three" Shows above it on the first navigation item with ###.

#### Steps to reproduce

bug with nesting
========================
**menu wrong nesting**
#### one on layer three

**menu correct nnesting**
#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `vr mrt. 3 10:51:51 2023`
**Version**: `23.3.0.1`
**Build date**: `Mar  2 2023`
**Build number**: `1016`
**Platform**: `linux`
**Operating System**: `Ubuntu 22.10`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.15.6`
**Qt Version (runtime)**: `5.15.6`
**Portable mode**: `no`
**Settings path / key**: `/home/p-thor/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/p-thor/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: `en`
**Primary screen resolution**: `2560x1440`
**Screen resolution(s)**: `2560x1440, 2560x1440, 2560x1440`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `28`
**Calendar items**: `37`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: `https://files.dainathor.com`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `25.0.3.2`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `en_GB`
**Language codes**: `el_GR, en_AU, en_CA, en_GB, en_US, en_ZA, nl, nl_AW, nl_BE, nl_NL, nl_SR`
**Language names**: `Ελληνικά (Ελλάδα), Australian English (Australia), Canadian English (Canada), British English (United Kingdom), American English (United States), English (South Africa), Nederlands, Nederlands (Aruba), Nederlands (België), Nederlands (Nederland), Nederlands (Suriname)`
**Application dictionaries path**: `/home/p-thor/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `2`

### Note folder `default`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/p-thor/Documents`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/p-thor/Documents/notes.sqlite`

### Note folder `nextcloud`

**id**: `3`
**isCurrent**: `no`
**activeTagId**: `-1`
**localPath**: `/home/p-thor/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/p-thor/Nextcloud/Notes/notes.sqlite`

### Cloud connection `New connection`

**id**: `2`
**isCurrent**: `no`
**serverUrl**: `https://files.dainathor.com`
**username**: `p-thor`
**accountId**: *empty*

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://files.dainathor.com`
**username**: `p-thor`
**accountId**: *empty*

### Script `Wiki Links`

**id**: `1`
**path**: `/home/p-thor/.local/share/PBE/QOwnNotes/scripts/wiki-links/wiki-links.qml`
**variablesJson**: 
```
{
    "wikilinksBackgroundColor": "#FFFF00",
    "wikilinksForegroundColor": "#ff832b",
    "wikilinksHideSubfolder": true,
    "wikilinksLowerCase": true,
    "wikilinksRemoveSpaces": true,
    "wikilinksReplaceSpacesSymbol": "-",
    "wikilinksSanitizeFilename": true
}
```
**identifier**: `wiki-links`
**version**: `0.0.1`
**minAppVersion**: `20.6.0`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**ImageDialog/disableCopying** (QString): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2023-03-03T10:43:57.701`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-2** (QStringList): `xforce, My Mods/SpecialK, D&D, D&D/stories, IRA, sofia__data, sofia__data/eff, sofia_audio_data, BlackmagicDesign/DaVinci Resolve/Fusion`
**MainWindow/noteSubFolderTreeWidgetExpandState-3** (QStringList): `home/network, D&D/oneshots, D&D/stories, werk, home, games, YouTube, D&D`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (QString): `600`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/command-failed** (QString): `1024`
**MessageBoxOverride/copy-notes** (QString): `16384`
**MessageBoxOverride/move-notes** (QString): `16384`
**MessageBoxOverride/notes-copied** (QString): `1024`
**MessageBoxOverride/readonly-mode-allow** (QString): `16384`
**MessageBoxOverride/remove-notes** (QString): `16384`
**MessageBoxOverride/script-install-successful** (QString): `1024`
**MessageBoxOverride/tag-notes** (QString): `16384`
**NoteFolder-2/NoteTabNameList** (QString): `Tarokkka`
**NoteFolder-2/NoteTabStickinessList**: *empty*
**NoteFolder-2/NoteTabSubFolderPathDataList** (QString): 
```
D&D
Curse of Strahd
```
**NoteFolder-2/allowDifferentNoteFileName** (QString): `false`
**NoteFolder-3/NoteTabNameList**: *empty*
**NoteFolder-3/NoteTabStickinessList**: *empty*
**NoteFolder-3/NoteTabSubFolderPathDataList**: *empty*
**NoteFolder-3/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-2** (QVariantList): `<variant list with 53 item(s)>`
**NoteHistory-3** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-2** (QString): `52`
**NoteHistoryCurrentIndex-3** (QString): `199`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePrinting** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**ServerBookmarksImportDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**VersionDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `2`
**currentWorkspace** (QString): `7hsuzSbENe8w`
**cursorWidth** (QString): `1`
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): `en`
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `17`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `0`
**notesPath** (QString): `/home/p-thor/Documents`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `25.0.3.2`
**previousWorkspace** (QString): `initial`
**recentNoteFolders** (QString): `/home/p-thor/Nextcloud/Notes`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-2** (QStringList): `Note 2023-03-03T10.40.41, Note 2023-03-01T08.39.56, Note 2023-02-26T18.37.43, the r, Note 2022-05-01T09.49.08, Note 2022-04-30T14.17.04, Note 2022-02-27T14.22.54, Note 2020-05-17T08.40.56`
**savedSearches/noteFolder-3** (QStringList): `Note 2022-12-27T13.30.52, Note 2022-12-27T13.30.30, Note 2022-12-27T12.41.26, Note 2022-12-27T12.39.46, Note 2022-12-27T12.17.58, episodes, Note 2022-12-17T13.53.35, Note 2022-12-10T11.31.08, Note 2022-10-30T09.37.57, Note 2022-10-30T09.36.25, Note 2022-10-22T09.18.12, Note 2022-10-16T09.30.00, Note 2022-10-16T07.54.26, Note 2022-10-13T07.11.15, Note 2022-09-19T19.19.01, Note 2022-09-07T15.14.44, Note 2022-08-12T18.42.33, Note 2022-08-06T17.29.55, Note 2022-06-22T10.49.05, Note 2022-06-19T21.39.47, Note 2021-12-29T13.44.21, Note 2021-10-12T18.07.47, Note 2021-09-19T12.43.57, Note 2021-05-22T08.35.49, Note 2021-05-14T21.59.11, Note 2021-05-14T21.58.41, Note 2021-05-11T19.01.26, Note 2021-05-08T22.09.09, Note 2021-05-01T12.12.02, Note 2021-04-29T15.16.12, Note 2021-04-29T10.50.46, Note 2021-04-26T21.24.57, Note 2021-04-26T09.58.13, Note 2021-04-22T06.36.05, Note 2021-04-17T14.25.34, Note 2021-04-17T13.47.36, Note 2021-04-17T13.47.14, Note 2021-04-17T13.45.06, Note 2021-04-04T14.52.42, Note 2021-03-04T10.19.04, Note 2021-02-05T07.28.33, Note 2021-02-03T16.52.30, Note 2021-01-31T10.50.19, Note 2021-01-17T13.33.15, Note 2021-01-16T10.54.09, wdh, Note 2020-12-06T12.45.30, Note 2020-12-04T13.38.02, Note 2020-11-27T12.50.14, Note 2020-11-25T16.45.45, Note 2020-11-15T12.11.16, Note 2020-11-13T07.46.35, Note 2020-11-05T19.10.11, Note 2020-10-19T21.18.48, Note 2020-09-23T19.20.11, Note 2020-05-20T17.23.57, Note 2020-05-20T16.29.53`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**skipVersion** (QString): `22.9.1`
**spellCheckLanguage** (QString): `en_GB`
**startInReadOnlyMode** (QString): `false`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, `
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `true`
**versionSplitterSizes** (QByteArray): `<binary data>`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (QString): `22222`
**webSocketServerService/token** (QString): `<hidden>`
**workspace-7hsuzSbENe8w/name** (QString): `Full`
**workspace-7hsuzSbENe8w/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-7hsuzSbENe8w/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `false`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 7hsuzSbENe8w`

## System environment

**HOME**: `/home/p-thor`
**LANG**: `en_US.UTF-8`
**LANGUAGE**: `en`
**LC_ADDRESS**: `nl_NL.UTF-8`
**LC_IDENTIFICATION**: `nl_NL.UTF-8`
**LC_MEASUREMENT**: `nl_NL.UTF-8`
**LC_MONETARY**: `nl_NL.UTF-8`
**LC_NAME**: `nl_NL.UTF-8`
**LC_NUMERIC**: `nl_NL.UTF-8`
**LC_PAPER**: `nl_NL.UTF-8`
**LC_TELEPHONE**: `nl_NL.UTF-8`
**LC_TIME**: `nl_NL.UTF-8`
**LOGNAME**: `p-thor`
**PATH**: `/home/p-thor/.local/bin:/home/p-thor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin`
**SHELL**: `/bin/bash`
**SYSTEMD_EXEC_PID**: `5377`
**USER**: `p-thor`
**XDG_DATA_DIRS**: `/usr/share/gnome:/home/p-thor/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop`
**XDG_RUNTIME_DIR**: `/run/user/1490200001`
**GTK_MODULES**: `gail:atk-bridge`
**QT_ACCESSIBILITY**: `1`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1490200001/bus`
**DEBUGINFOD_URLS**: `https://debuginfod.ubuntu.com `
**DEFAULTS_PATH**: `/usr/share/gconf/gnome.default.path`
**DESKTOP_SESSION**: `gnome`
**DISPLAY**: `:1`
**GDMSESSION**: `gnome`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**GPG_AGENT_INFO**: `/run/user/1490200001/gnupg/S.gpg-agent:0:1`
**IM_CONFIG_PHASE**: `1`
**KRB5CCNAME**: `KCM:`
**LIBVIRT_DEFAULT_URI**: `qemu:///system`
**MANDATORY_PATH**: `/usr/share/gconf/gnome.mandatory.path`
**PAPERSIZE**: `a4`
**PWD**: `/home/p-thor`
**QT_IM_MODULE**: `ibus`
**SESSION_MANAGER**: `local/beauregard.thuis.dainathor.com:@/tmp/.ICE-unix/5358,unix/beauregard.thuis.dainathor.com:/tmp/.ICE-unix/5358`
**SHLVL**: `0`
**SSH_AGENT_LAUNCHER**: `openssh`
**SSH_AUTH_SOCK**: `/run/user/1490200001/keyring/ssh`
**USERNAME**: `p-thor`
**WINDOWPATH**: `2`
**XAUTHORITY**: `/run/user/1490200001/gdm/Xauthority`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-gnome:/etc/xdg`
**XDG_CURRENT_DESKTOP**: `GNOME`
**XDG_MENU_PREFIX**: `gnome-`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_DESKTOP**: `gnome`
**XDG_SESSION_TYPE**: `x11`
**XMODIFIERS**: `@im=ibus`
**_**: `/usr/bin/dbus-update-activation-environment`
**MANAGERPID**: `5144`
**INVOCATION_ID**: `dcd8dc6d4709433e99a3c309cfbd089f`
**JOURNAL_STREAM**: `8:72849`
**GJS_DEBUG_OUTPUT**: `stderr`
**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`
**GIO_LAUNCHED_DESKTOP_FILE**: `/usr/share/applications/PBE.QOwnNotes.desktop`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `158296`
</details>

**Comment by p-thor** [comment]
![image](https://user-images.githubusercontent.com/915380/222689616-6e76b82b-e331-4b30-80d7-8f7ef8f176d7.png)

A screenshot of the outcome. The left navigation is wrong on the top part of this note

**Comment by pbek** [comment]
Can you please quote your examples (so that we can see the markdown text) and please describe what you expected, what the actual behavior was?

**Comment by pbek** [comment]
> The left navigation is wrong on the top part of this note

You mean when you are lacking a h3 and so there is no connection from h2 to h4? That's currently not supported, is there are reason you want "wrong markup" to be supported? 😁

**Comment by pbek** [comment]
It would be very quirky and flaky to attempt to force that into:

https://github.com/pbek/QOwnNotes/blob/60cb8dcc255053cf19f4783f3e2df06ae63a66fd/src/widgets/navigationwidget.cpp#L160-L170

**Comment by p-thor** [comment]
> > The left navigation is wrong on the top part of this note
> 
> You mean when you are lacking a h3 and so there is no connection from h2 to h4? That's currently not supported, is there are reason you want "wrong markup" to be supported? grin

Document formatting wise having a lower heading makes more sense and form a document design standpoint it is not a "wrong" thing.  
I would have thought that the menu would follow the flow of the document and not some rule set on the formatting.
It  is a minor issue so if too hard I can live with it.
