### ISSUE TITLE
NextCloud note sharing images don't work & updating note content issue

### ISSUE THREAD

**Issue by skylord123** [pbek/QOwnNotes#2748]
Want to share my notes with team mates but none of my images are coming over. Also whenever I make changes to a note the shared link does not update and still shows old content.

If you are logged in and view the note using the NextCloud notes viewer the images load fine. This is not available to "guests" that are accessing it via a shared link.

Is there any way to get these issues resolved and get a decent integration with NextCloud?

#### Expected behaviour

When I write a note, it uploads to NextCloud, and I share it via the button in QOwnNotes to get a link. When I go to the link the images should render on the note correctly.

Also updating the note, letting it sync, and re-viewing the shared link still shows the old content. Unchecking the share checkbox in QOwnNotes and re-sharing does nothing, still old content. I would expect the note to update when it syncs over.

#### Actual behaviour

Fails to load the images. Instead I get an error from NextCloud stating `Failed to load ../media/qownnotes-media-dvuMln.png` like so:

![image](https://user-images.githubusercontent.com/3412313/225123152-2f6f1c4a-1ef3-45a2-b606-8212b628f9a7.png)

Also updating a note does not update the content on the shared link even when you re-share it.

#### Steps to reproduce

Reproduce image issue (use a snapshot of your display so image is stored in clipboard):
1) Create a note in QOwnNotes and add an image
2) Wait for NC to sync it
3) share it
4) view it and get sad your images wont load

Reproduce updating content issue:
1) Create note
2) sync it
3) create share link
4) view share link
5) update the note and wait for sync again
6) refresh the shared link and old content still displays
7) uncheck the share link from QOWNNotes
8) re-share the file and get a link
9) still old content displays

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Mar 14 14:15:25 2023`
**Version**: `22.11.6`
**Build date**: `Nov 15 2022`
**Build number**: `995`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\skylar.sadlier\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Users\skylar.sadlier\OneDrive - Scientific Games Corporation\Documents\programs\qownnotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1200`
**Screen resolution(s)**: `1920x1200, 1920x1080, 1920x1200`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `47`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://nextcloud.home.skylar.tech:443`
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\skylar.sadlier\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `C:\Users\skylar.sadlier\OneDrive - Scientific Games Corporation\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: `Meetings`
**database file**: `C:\Users\skylar.sadlier\OneDrive - Scientific Games Corporation\Notes\notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://nextcloud.home.skylar.tech:443`
**username**: `skylar.sg`
**accountId**: `skylar.sg`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2023-03-14T14:12:07.641`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,13,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,7.875,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (int): `600`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/readonly-mode-allow** (int): `16384`
**MessageBoxOverride/share-sync-information** (int): `1024`
**MessageBoxOverride/windows-dark-mode** (int): `16384`
**NoteFolder-1/NoteTabNameList** (QStringList): `2022-08 August, 2023-03 March`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `- Work Log -, - Work Log -`
**NoteHistory-1** (QVariantList): `<variant list with 50 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `49`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `300`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (int): `15`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `false`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `C:/Users/skylar.sadlier/OneDrive - Scientific Games Corporation/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `gMUg3eBemugu`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2023-03-14T13.55.39, Note 2023-03-14T11.35.27, Note 2023-03-13T13.51.05, Note 2023-03-01T14.01.26, Note 2023-02-16T12.34.53, Note 2023-02-06T13.45.26, Note 2023-01-30T10.38.33, 2023-01 January 2023-01-30T10.06.23, Note 2023-01-03T08.30.43, Note 2022-12-08T12.51.44, Note 2022-12-07T13.54.47, Note 2022-12-01T12.11.50`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (int): `22222`
**workspace-5DBEQKCam2ed/name** (QString): `Minimal`
**workspace-5DBEQKCam2ed/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-5DBEQKCam2ed/windowState** (QByteArray): `<binary data>`
**workspace-G4Vu2aK6v5kf/name** (QString): `Preview only`
**workspace-G4Vu2aK6v5kf/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-G4Vu2aK6v5kf/windowState** (QByteArray): `<binary data>`
**workspace-gMUg3eBemugu/name** (QString): `Full`
**workspace-gMUg3eBemugu/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-gMUg3eBemugu/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 5DBEQKCam2ed, G4Vu2aK6v5kf, gMUg3eBemugu`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\skylar.sadlier\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `LCND2381KLK`
**ComSpec**: `C:\Windows\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\skylar.sadlier`
**LOCALAPPDATA**: `C:\Users\skylar.sadlier\AppData\Local`
**LOGONSERVER**: `\\ATLWSGLDC02`
**NUMBER_OF_PROCESSORS**: `16`
**OneDrive**: `C:\Users\skylar.sadlier\OneDrive - Scientific Games Corporation`
**OneDriveCommercial**: `C:\Users\skylar.sadlier\OneDrive - Scientific Games Corporation`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Windows\CCM;C:\Windows\CCM;C:\Windows\CCM;C:\Windows\CCM;C:\Windows\CCM;C:\Windows\CCM;C:\Windows\CCM;C:\Windows\CCM;C:\Windows\CCM;C:\Program Files (x86)\Pulse Secure\VC142.CRT\X64\;C:\Program Files (x86)\Pulse Secure\VC142.CRT\X86\;C:\Program Files (x86)\Common Files\Pulse Secure\TNC Client Plugin\;C:\Program Files\Docker\Docker\resources\bin;C:\Users\skylar.sadlier\AppData\Local\Microsoft\WindowsApps;C:\Users\skylar.sadlier\AppData\Local\JetBrains\Toolbox\scripts;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 141 Stepping 1, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `8d01`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\Windows`
**TEMP**: `C:\Users\SKYLAR~1.SAD\AppData\Local\Temp`
**TMP**: `C:\Users\SKYLAR~1.SAD\AppData\Local\Temp`
**USERDNSDOMAIN**: `AD.SCIGAMES.COM`
**USERDOMAIN**: `sgames`
**USERDOMAIN_ROAMINGPROFILE**: `sgames`
**USERNAME**: `skylar.sadlier`
**USERPROFILE**: `C:\Users\skylar.sadlier`
**windir**: `C:\Windows`
**ZES_ENABLE_SYSMAN**: `1`

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>
[14:08:47] [status] Stored 1 note(s) to disk

</details>

**Comment by skylord123** [comment]
It would be nice if there was a way for me to tell QOwnNotes to save images/files to the same directory as the note and use a relative link to that same directory. I wonder if it is breaking because nextcloud doesn't understand `../media`

**Comment by skylord123** [comment]
So I did a test on my example document and added a new line and saved it, waited for sync, and checked the shared link and still showing old version. Decided to open it in NextCloud as my logged in user and get this view:
![image](https://user-images.githubusercontent.com/3412313/225128375-50e8a48d-096d-48cd-ad17-12f63988e13f.png)

Yeah I would expect this if I opened it in NextCloud web and then updated it in QOwnNotes while the web view was still open. This was opened several minutes after the change though, so why is it telling me it's modified? If I open something in NextCloud I want the most recent version always.

I am on latest NextCloud and QOwnNotes plugin version. This is strange.

**Comment by pbek** [comment]
Are we talking about two different things here? Can you please split your issue up in two if that's the case, otherwise it's hard to keep track of what we are talking. 😁

**Comment by pbek** [comment]
Sidenote: Previously Nextcloud Notes had their "proprietary" way of referencing images (I implemented that in QOwnNotes too then to be at least able to view images inserted by Nextcloud Notes). Now I see they can handle normal image links, which make me very happy! 🌞 

> share it
> view it and get sad your images wont load

Are we talking about something Nextcloud does or QOwnNotes? The note is shared on your Nextcloud Server and the Nextcloud Preview can't show images, right? Maybe best open an issue there?

**Comment by pbek** [comment]
>  update the note and wait for sync again

That's also a very annoying issue (?) of Nextcloud, QOwnNotes doesn't have anything to do with it. When you share a Markdown file on Nextcloud the generated HTML seems to get cached, the cache updates very seldomly, this drives me mad. 😅  I hardly use that feature for this reason.

**Comment by pbek** [comment]
> The note is shared on your Nextcloud Server and the Nextcloud Preview can't show images, right? 

Yes, you simply don't seem to have the permissions to those images... Best open a feature request on https://github.com/nextcloud/server/issues. But I guess that will be hard to handle...

When you export an HTML of a note in QOwnNotes I generate in-line version of the images and embed them into the note directly. I guess that would work better in this case too...
