### ISSUE TITLE
Todo-List as window pane

### ISSUE THREAD

**Issue by pascal-niklaus** [pbek/QOwnNotes#275]
It would be nice to have the TODO list as Window pane, visible permanently, rather than in a modal dialog.

**Comment by pbek** [comment]
I'm not sure if what would work right now, a lot of things would clash if we would do that at the moment...

**Comment by pbek** [comment]
I'd rather would create a mode to execute QOwnNotes API where just the todo list dialog is shown, but maybe even that would have too many side effects since they would use the same database and settings...

**Comment by OrlandoRichards** [comment]
How about letting the task list window stay open without blocking focus from the main editor window? That way you could have them both open at the same time.

**Comment by pbek** [comment]
I've yet not managed to open a non-modal window from the main window.

**Comment by pbek** [comment]
I still think the todo dialog is to big for a panel. It would only make sense to break it apart and have different panels for the todo list and the edit area. But there wouldn't be a shortcut any more to turn it on optionally, what would annoy people. And it would only make sense if the edit area would be hidden if no todo item is selected (and that would mess with the current workspace concept). Any suggestions?

Meanwhile...

## 16.10.10
- the todo dialog is not modal any more and doesn't hinder you from 
  using the application main window 
    - you can also open as many todo dialogs as you want now

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by pbek** [comment]
I will close this issue until there is more information.

**Comment by aphirst** [comment]
I'm waiting for the next release of nextcloud before I can fully test, but I'm keen to try out QOwnNotes with my own nextcloud instance AND the integrated CalDAV TODO list functionality. I think what I and @pascal-niklaus have in mind for our desired workflows is quite similar, and once I'm up and running will report back on how the overall experience is.
