### ISSUE TITLE
[Feature request] Implement case insensitive notes search for non-ascii letters

### ISSUE THREAD

**Issue by kovdan01** [pbek/QOwnNotes#2750]
Not an issue, but a feature request. 

Currently, when searching for notes containing specific text in Cyrillic alphabet, the search is performed in a case sensitive manner. For Latin letters, case-insensitive search works properly. It would be nice to implement the same behavior for some wide-spread non-Latin alphabets, since case-sensitive search is unhandy in 99% of use cases.

Also, it's interesting that note sub folder search is case insensitive for both Latin and Cyrillic letters, so it might be enough to just use the same functionality for notes search.

**Comment by pbek** [comment]
Are we talking about #1590?

**Comment by kovdan01** [comment]
Yes, sorry for a duplicate! I was unable to find the issue you mentioned by my own :)
