### ISSUE TITLE
Cannot update the appimage 23.3.3 → 23.3.4

### ISSUE THREAD

**Issue by Beurt** [pbek/QOwnNotes#2751]
Hi,

Unfortunately I have again troubles to update QON appimage form 23.3.3 to 23.3.4.

#### Expected behaviour

I clic on Update and QON restarts updated.

#### Actual behaviour

I clic on Update and it is the old version of QON that restarts, proposing the update again.

#### Steps to reproduce

1. Get QON 23.3.3
2. wait for the update to 23.3.4 window to appears
3. clic on update (and confirm the restart)
4. QON restarts, but it is still v. 23.3.3. The update window appears again.

**Comment by pbek** [comment]
Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.

**Comment by Beurt** [comment]
Oh sorry! Here it is:

<details><summary>My debug info</summary>
</details>

**Comment by pbek** [comment]
It's strange. I can't get any error or something...

old process:

```
[März 18 09:38:19] [debug]: initializeLinuxUpdateProcess  - 'filePath':  "/tmp/QOwnNotes-LGVVcv.AppImage"
[März 18 09:38:19] [debug]: initializeLinuxUpdateProcess  - 'appPath':  "/home/omega/Downloads/QOwnNotes-x86_64.AppImage"
```

new process:

```
[März 18 09:38:26] [Debug]: main  - 'locale':  "en"
[März 18 09:38:26] [Debug]: Translation  "/usr/share/qt5/translations/QOwnNotes_en" in "" isLoaded: true , isInstalled: true
[März 18 09:38:26] [Debug]: Translation  "qt_en" in "/tmp/.mount_QOwnNoKQQowZ/usr/translations" isLoaded: false , isInstalled: false
[März 18 09:38:26] [Debug]: Translation  "qt_en" in "/tmp/.mount_QOwnNoKQQowZ/usr/bin/translations" isLoaded: false , isInstalled: false
```

**Comment by pbek** [comment]
After looooong testing I found out the AppImage was indeed updated but the old was was started when restarting the application!

**Comment by pbek** [comment]
## 23.3.5
- another AppImage update issue that came with the changes from
  [#2728](https://github.com/pbek/QOwnNotes/issues/2728) should now be fixed
  (for [#2751](https://github.com/pbek/QOwnNotes/issues/2751))

**Comment by pbek** [comment]
## 23.3.6
- AppImage updater test release (for [#2751](https://github.com/pbek/QOwnNotes/issues/2751))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
Please use https://github.com/pbek/QOwnNotes/releases/download/v23.3.5/QOwnNotes-x86_64.AppImage and make the update. I was able to successfully update to 23.3.6! 🥳 😅

**Comment by Beurt** [comment]
I am very sorry I was AFK and I did not provide any help!

Thank you very much the update 23.3.5 → 23.3.6 went smoothly! It seems to work now!

**Comment by pbek** [comment]
Thank you very much!
