### ISSUE TITLE
Word count and character count

### ISSUE THREAD

**Issue by hermenet** [pbek/QOwnNotes#2753]
I am also using QOwnNotes for academic writing in humanities. It lacks footnotes, and I've found a provisional workaround for that.
However, what I miss more is an indicator for the word count and character count per note and folder. Is there any GUI implementation of the wc command?  
Thanks.

**Comment by pbek** [comment]
Best search for "Note stats" in the script repository.

**Comment by Beurt** [comment]
> It lacks footnotes, and I've found a provisional workaround for that.

How did you do for the footnotes?

**Comment by hermenet** [comment]
> How did you do for the footnotes?
My solution is entirely provisional. I use notes (one numbered note per footnote) and link to those notes from the main document (the main note).
Pros: more concentration on the main text; more consistency of units (the main text and single footnotes); every footnote has its number, which helps with cross-references. 
Cons: Footnotes' text is not included in word and character counts; there must be a more thoroughgoing final typesetting.

**Comment by Beurt** [comment]
Thank you for your explanation!

And why don't you use Pandoc/Github footnote Markdown? (<https://pandoc.org/MANUAL.html#footnotes>)

**Comment by Beurt** [comment]
> I've no experience with Markdown footnotes. sweat_smile

There was an issue about this (https://github.com/pbek/QOwnNotes/issues/270). I think that, in the preview, this is something a script can do.

On the editor side, scripting would require to be able to capture clicks on a specific string to implements the jump to the note.
