### ISSUE TITLE
[Q] All my notes are disapperaed behind this How Can i restored them back?

### ISSUE THREAD

**Issue by AliRazaCloudways** [pbek/QOwnNotes#2759]
![image](https://user-images.githubusercontent.com/129114462/228055308-fa21bf9b-a615-4af6-8c17-94c309365dc3.png)

**Comment by AliRazaCloudways** [comment]
Can someone please help if there's any reversible thing on Qownnotes available?

**Comment by pbek** [comment]
Could you please provide the information asked for in the issue template to give more context.

**Comment by AliRazaCloudways** [comment]
Actually, I've no idea what you're talking about. All my text messages are hidden under this encrypted file.
![image](https://user-images.githubusercontent.com/129114462/228056640-f1845aeb-2c31-417f-b843-a3697ab04172.png)

**Comment by AliRazaCloudways** [comment]
I just accidentally hit a button or something happens from the keyboard.

**Comment by AliRazaCloudways** [comment]
Is there any option to restore from the previous date?

**Comment by AliRazaCloudways** [comment]
Hello Pbek, 

Please let me know if there's still anything I can share with you.

**Comment by AliRazaCloudways** [comment]
Can you please check if there's any possible workaround to have all my texts back? @pbek

**Comment by pbek** [comment]
Can you please describe what you expected, what the actual behavior was and step by step what you did?

Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.
