### ISSUE TITLE
Comments in italic

### ISSUE THREAD

**Issue by igorp74** [pbek/QOwnNotes#2765]
Comments turned into Italic style in **preview panel**

**Expected behavior**
Comments in code blocks,  in **preview panel**, should be non-italic. Same as in in **edit panel.**

**Actual behavior** 
Comments in code blocks  in **preview panel**,  are italic as opposite how they are represent in **edit panel.**

**Pictures:**
https://quip.com/U1MXAnbfcJAc/QON-Comments

Kind regards,
Igor

**Comment by igorp74** [comment]
Example Markdown

# Python - list flattening


***

## 🌐 Sources

* [pythonpool.com](https://www.pythonpool.com/flatten-list-python/)

## 💡 Example

```python
# Example list
l = [[5,8,7,1,[8,7,[11,22,9],9,8,7,3], 2, 3], [3,2,7,1,4, 5, 6], [7], [8, 9]]


# 1st With DataFrme flatten
from pandas.core.common import flatten
print(list(set(flatten(l))))


# 1st-B With DataFrme flatten
import pandas as pd
print(list(set(pd.core.common.flatten(l))))


# 2nd With generator
def flatten(items):
    for x in items:
        if isinstance(x, list) and not isinstance(x, (str, bytes)):
            yield from flatten(x)
        else:
            yield x

print(list(set(flatten(l))))
```

**Comment by pbek** [comment]
Hard to copy that example when already interpreted... 😅  Best use some fences, like https://www.qownnotes.org/getting-started/markdown.html#_4-spaces-fence

**Comment by pbek** [comment]
And can you please describe what you expected, what the actual behavior was and step by step what you did?

**Comment by pbek** [comment]
Thank you 😉

**Comment by igorp74** [comment]
Hope it helps...

**Comment by pbek** [comment]
Thank you. Meanwhile if you want to get more insight into what actually is shown in the preview you can export and examine the HTML of it by right-clicking on the preview panel.

**Comment by pbek** [comment]
@Waqar144, do you think that this was intentional?

**Comment by Waqar144** [comment]
No, The converter just sets the class for a particular piece of code. The formatting is determined by the css corresponding to that class which could be the reason this happens
```c++
        case Comment:
            return QStringLiteral("<span class=\"code-comment\">") % escapeString(str) %
                   QStringLiteral("</span>");
```

**Comment by Waqar144** [comment]
Seems like its enforced:
```
    codeStyleSheet += QStringLiteral(" .code-comment { color: #75715E; font-style: italic;}");
```

**Comment by igorp74** [comment]
After upgrading to the latest version, I can confirm italic comments (no matter what settings were) are gone.
Now it works as expected.

Kind regards,
Igor
