### ISSUE TITLE
Cant start flatpak

### ISSUE THREAD

**Issue by Tealk** [pbek/QOwnNotes#2766]
#### Expected behaviour

Program starts

#### Actual behaviour

Program does not start

#### Steps to reproduce

1) flatpak install org.qownnotes.QOwnNotes
2) run org.qownnotes.QOwnNotes.

#### Output from console

```
$ flatpak run org.qownnotes.QOwnNotes
Warning: Unable to find dictionary for "de_DE" in path "/usr/share/runtime/locale/de/share/de/hunspell/de_DE" (:0, )
$
```

**Comment by pbek** [comment]
That Repository is Community maintained, can you please open an issue on FlatHub directly

**Comment by Tealk** [comment]
Where should I create the issue there?
Other flatpacks work, just not the program. Therefore, I thought that I post the error here.

Flatpak is the simplest means for an arch system

**Comment by pbek** [comment]
See https://www.qownnotes.org/installation/flatpak.html

**Comment by Tealk** [comment]
> See https://www.qownnotes.org/installation/flatpak.html

But nowhere is there a link where an issue should be written.

**Comment by pbek** [comment]
There was a link to the Flatpak page.
On Flatpak all build config is hosted on https://github.com/flathub. The flathub community created https://github.com/flathub/org.qownnotes.QOwnNotes for QOwnNotes, so https://github.com/flathub/org.qownnotes.QOwnNotes/issues would be a good place.

But since you are on Arch I wonder why you are favoring Flathub over the AUR anyway... 😉

**Comment by pbek** [comment]
Btw. I had no issues running QOwnNotes with `flatpak run org.qownnotes.QOwnNotes`...

**Comment by pbek** [comment]
Do you have the same issue when running QOwnNotes in a new session (see [cli-parameters](https://www.qownnotes.org/getting-started/cli-parameters.html))?

**Comment by Tealk** [comment]
> Do you have the same issue when running QOwnNotes in a new session (see [cli-parameters](https://www.qownnotes.org/getting-started/cli-parameters.html))?

with this i could start a new session, even if i still get some warnings

```
flatpak run org.qownnotes.QOwnNotes  --session test
Info: "QOwnNotes-Server arbeitet auf Port 22222" ((null):0, (null))
Warning: Missing trigrams for languages: QSet("en_AU", "en_JM", "en_TT", "en_ZA", "en_MW", "en_NZ", "de_CH", "en_PH", "en_BZ", "en_IE", "en_IN", "en_CA", "en_NA", "en_GH", "en_BS", "en_ZW") ((null):0, (null))
Warning: Unable to find dictionary for "de_AT" in path "/usr/share/runtime/locale/de/share/de/hunspell/de_AT" ((null):0, (null))
Warning: Unable to find dictionary for "de_DE" in path "/usr/share/runtime/locale/de/share/de/hunspell/de_DE" ((null):0, (null))

** (QOwnNotes:2): WARNING **: 12:30:15.764: atk-bridge: get_device_events_reply: unknown signature
```

**Comment by pbek** [comment]
> ** (QOwnNotes:2): WARNING **: 12:30:15.764: atk-bridge: get_device_events_reply: unknown signature

Dunno, never saw that...
Maybe ask your searchengine: https://html.duckduckgo.com/html?q=%22atk%2Dbridge%3A%20get_device_events_reply%3A%20unknown%20signature%22

Or try any of the other ways to install QOwnNotes... e.g. the AUR (like you should on Arch 😉)

**Comment by Tealk** [comment]
> the AUR

the cooking process lasts but about aur with QOwnNotes very very long :(
