### ISSUE TITLE
Open too much sessions

### ISSUE THREAD

**Issue by clusterice** [pbek/QOwnNotes#277]
In Onwcloud 9.1 the current sessions are visible. I see there a lot of sessions (>10) with Mozilla/5.0. I tested each of my clients and i saw that QOwnNotes open these sessions. The sessions will be closed after 24 hours by Owncloud. In my opinion this is a bug.

Thanks

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Di. Aug 9 08:22:54 2016`
**Version**: `16.08.2`
**Build date**: `Aug  6 2016`
**Build number**: `1985`
**Platform**: `windows`
**Operating System**: `Windows 10`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.5.1`
**Qt Version (runtime)**: `5.5.1`
**Qt Debug**: `0`
**Locale (system)**: `de_CH`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `3`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `xxxxxx`
**appIsValid**: `yes`
**serverVersion**: `9.1.0.15`
**appVersion**: `0.4.4`

## Note folders

**currentNoteFolderId**: `1`

### Standard

**id**: `1`
**activeTagId**: `0`
**localPath**: `C:/Users/xxxx/Notes`
**remotePath**: `Notes`

## Settings

**LastUpdateCheck**: `2016-08-09T08:22:31`
**LogDialog/showAtStartup**: `false`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `24`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/showRecentNoteFolderInMainArea**: `false`
**MainWindow/windowState**: `<binary data>`
**PiwikClientId**: `<hidden>`
**ShowSystemTray**: `false`
**SortingModeAlphabetically**: `false`
**TodoDialog/geometry**: `<binary data>`
**TodoDialog/mainSplitterState**: `<binary data>`
**TodoDialog/showCompletedItems**: `0`
**TodoDialog/todoListSelectorSelectedItem**: `xxxx`
**allowDifferentNoteFileName**: `false`
**allowOnlyOneAppInstance**: `false`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `false`
**appMetrics/notificationShown**: `true`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**customNoteFileExtensionList**: *empty*
**darkMode**: `false`
**darkModeColors**: `false`
**defaultNoteFileExtension**: `md`
**demoNotesCreated**: `true`
**disableAutomaticUpdateDialog**: `false`
**externalEditorPath**: *empty*
**ignoreAllExternalModifications**: `false`
**interfaceLanguage**: *empty*
**mainSplitterSizes**: `<binary data>`
**mainSplitterState-0-1-1-0**: `<binary data>`
**markdownHighlightingInterval**: `200`
**networking/ignoreSSLErrors**: `false`
**networking/proxyType**: `2`
**noteListSplitterState**: `<binary data>`
**noteSaveIntervalTime**: `10`
**notesPath**: `C:/Users/xxxx/Notes`
**notifyAllExternalModifications**: `false`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: `xxxx`
**ownCloud/todoCalendarBackend**: `0`
**ownCloud/todoCalendarEnabledList**: `xxxx`
**ownCloud/todoCalendarEnabledUrlList**: xxxx
**ownCloud/todoCalendarUrlList**: xxxx
**ownCloud/userName**: `xxxx`
**savedSearches/noteFolder-1**: `Note 2016-08-06T10.58.10`
**showStatusBar**: `true`
**tagFrameSplitterState**: `<binary data>`
**verticalNoteFrameSplitterState**: `<binary data>`

**Comment by pbek** [comment]
Thank you for reporting. What kind of sessions are you talking about? Can you please give me more information about them? And where do you see them and what is their relationship with QOwnNotes?

**Comment by clusterice** [comment]
I deactivated each of my sync clients on all computers and tested each individually until I found QOwnNotes wich initiates these sessions. 

In the personal settings in Ownlcoud 9.1 you will see all your open sessions (Screenshot).

![owncloudqownnotes](https://cloud.githubusercontent.com/assets/8361047/17506945/0b144c46-5e0d-11e6-81bd-8b9d00e73493.png)

**Comment by pbek** [comment]
I don't know how to prevent this. When making API requests to an ownCloud server you are supposed to provide username and password via http auth. I guess that leaves an open session (as in an entry in an internal table in ownCloud and not an open browser session, if you thought that was the case). I think that's just a log of what was accessing your ownCloud server and I think that's a good thing to see.

I can't do anything about that, do you have any suggestions?

Here is the API controller: <https://github.com/pbek/qownnotesapi/blob/develop/controller/noteapicontroller.php>

**Comment by clusterice** [comment]
Ok. Thank you. Maybe there is something in the Owncloud 9.1 documentation because they changed a lot in session handling and application authentication. 

Unfortunately I don't know the Owncloud API.

**Comment by pbek** [comment]
If you find something out, please let me know.

**Comment by clusterice** [comment]
I found a solution to get the session list readable. When you define a application password for QOwnNotes and use the application credentials in QOwnNotes the synchronizations appear only once under applications in the user menu.

Thanks for this nice project!

**Comment by pbek** [comment]
That's an interesting find, thank you for your feedback!
