### ISSUE TITLE
[I] Decoding (and preview) of links with brackets

### ISSUE THREAD

**Issue by marcoXbresciani** [pbek/QOwnNotes#2771]
#### Expected behaviour

For `[Link](https://www.qownnotes.org/it/)` the preview is a clickable
`Link` text.
See [Link](https://www.qownnotes.org/it/)

For `[[Bracketed Link](https://www.qownnotes.org/it/)]` the preview is a
clickable `Bracketed Link` text, surrounded by brackets.
See [[Bracketed Link](https://www.qownnotes.org/it/)]

For `[[Link with brackets]](https://www.qownnotes.org/it/)` the preview
is a clickable `[Link with brackets]` text.

#### Actual behaviour

For `[Link](https://www.qownnotes.org/it/)` the preview is a clickable
`Link` text.
See [Link](https://www.qownnotes.org/it/)

For `[[Bracketed Link](https://www.qownnotes.org/it/)]` the preview is a
clickable `Bracketed Link` text, surrounded by brackets.
See [[Bracketed Link](https://www.qownnotes.org/it/)]

For `[[Link with brackets]](https://www.qownnotes.org/it/)` the preview
is a `Link with brackets` text immediately followed (no space) by a
clickable `https://www.qownnotes.org/it/` text surrounded by parentheses.
See [[Link with brackets]](https://www.qownnotes.org/it/)

#### Steps to reproduce

Use these link to see how they are previewed in QOwnNotes, in a GitHub
Gist or even on https://dlaa.me/markdownlint/

# Test

[Link](https://www.qownnotes.org/it/)

[[Bracketed Link](https://www.qownnotes.org/it/)]

[[Link with brackets]](https://www.qownnotes.org/it/)

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `gio apr 13 11:17:06 2023`
**Version**: `23.4.3`
**Build date**: `Apr 13 2023`
**Build number**: `1028`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `yes`
**Settings path / key**: `C:/Users/marco.bresciani/Chiavetta/QOwnNotes/Data/PBE/QOwnNotes.ini`
**Application database path**: `C:\Users\marco.bresciani\Chiavetta\QOwnNotes\Data\QOwnNotes.sqlite`
**Application arguments**: `C:\Users\marco.bresciani\Chiavetta\QOwnNotes\QOwnNotes.exe`, `--after-update`, `C:\Users\marco.bresciani\AppData\Local\Temp\QOwnNotes-AZCoZH-updater.bat`, `--portable`
**Qt Debug**: `0`
**Locale (system)**: `it_IT`
**Locale (interface)**: `it`
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 3840x2160`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `22`
**Calendar items**: `0`
**Enabled scripts**: `2`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\marco.bresciani\Chiavetta\QOwnNotes\Data\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `C:\Users\marco.bresciani\Chiavetta\QOwnNotes\Data\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\marco.bresciani\Chiavetta\QOwnNotes\Data\Notes\notes.sqlite`

### Cloud connection ``

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

### Script `Note stats`

**id**: `1`
**path**: `C:\Users\marco.bresciani\Chiavetta\QOwnNotes\Data\scripts\note-stats\note-stats.qml`
**variablesJson**: 
```
{
    "charSpaceName": "Chars",
    "readTimeName": "Reading time",
    "readTimeRate": 300,
    "wordsName": "Words"
}
```
**identifier**: `note-stats`
**version**: `0.0.2`
**minAppVersion**: `17.06.3`

### Script `highlight`

**id**: `2`
**path**: `C:\Users\marco.bresciani\Chiavetta\QOwnNotes\Data\highlight.qml`
**variablesJson**: *empty*

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/editorWidthCustom** (QString): `72`
**DistractionFreeMode/editorWidthMode** (QString): `5`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `18`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/ColorSchemes**: *empty*
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-73f1d368-1021-46b7-8df7-11e5957e6ed9`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `true`
**Editor/showLineNumbers** (QString): `true`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath-ScriptPath** (QString): `C:/Users/marco.bresciani/Chiavetta/QOwnNotes/Data`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**JoplinImport/AttachmentImportCheckBoxChecked** (QString): `true`
**JoplinImport/FolderImportCheckBoxChecked** (QString): `true`
**JoplinImport/ImageImportCheckBoxChecked** (QString): `true`
**JoplinImport/MetadataImportCheckBoxChecked** (QString): `true`
**JoplinImport/TagImportCheckBoxChecked** (QString): `true`
**JoplinImportDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2023-04-13T10:36:49.817`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `17`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Input,11,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Input,11,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Input,11,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Input,11,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `false`
**MainWindow/noteTextView.refreshDebounceTime** (QString): `600`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `false`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/move-notes** (QString): `16384`
**MessageBoxOverride/remove-notes** (QString): `16384`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `199`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExportOrientation** (QString): `0`
**Printer/NotePDFExportPageSize** (QString): `4`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**StoredImagesDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `b6636bd7-f245-4781-ac2a-e46bab618805`
**cursorWidth** (QString): `1`
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `false`
**disableSavedSearchesAutoCompletion** (QString): `true`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `true`
**enableSocketServer** (QString): `false`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `true`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `true`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): `yyyy-MM-dd HH:mm:ss`
**interfaceFontSize** (QString): `10`
**interfaceLanguage** (QString): `it`
**internalIconTheme** (QString): `true`
**itemHeight** (QString): `17`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `1`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `false`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `true`
**networking/ignoreSSLErrors** (QString): `false`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `5`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `true`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `0`
**notesPath** (QString): `Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `82e017c9-740f-4f15-8f82-3dc17d6d794a`
**restoreCursorPosition** (QString): `false`
**restoreLastNoteAtStartup** (QString): `false`
**restoreNoteTabs** (QString): `false`
**savedSearches/noteFolder-1** (QStringList): `Note 2021-12-22T08.30.24, Note 2021-12-15T15.39.09, Note 2021-12-03T11.33.11, Note 2021-11-08T08.47.26, Note 2021-10-11T17.22.39, Note 2021-09-20T10.25.55, Note 2021-09-17T11.11.18, Note 2021-09-16T15.05.58, Note 2021-09-13T10.48.09, Note 2021-09-03T09.23.16, Note 2021-09-01T12.17.03, Note 2021-08-26T17.13.29, Note 2021-08-23T16.12.04, Note 2021-08-23T16.07.02, Note 2021-08-23T09.08.00, Note 2021-08-17T14.53.52, Note 2021-08-09T15.12.32, Note 2021-08-05T09.30.46, Note 2021-07-21T10.32.13, Note 2021-07-15T10.31.47, Note 2021-07-15T10.07.41, Note 2021-07-14T11.41.35, Note 2021-07-13T11.18.18, Note 2021-07-13T08.43.48, Note 2021-07-09T18.17.10, Note 2021-07-08T15.59.08, Note 2021-07-08T09.22.38, Note 2021-07-08T09.20.41, Note 2021-07-08T08.55.52, Note 2021-07-08T08.44.36, Note 2021-07-08T08.43.55, Note 2021-07-08T08.39.22, Note 2021-07-07T18.04.31, Note 2021-07-07T17.44.20, Note 2021-07-07T17.41.40, Note 2021-07-07T17.41.00, Note 2021-07-07T15.01.39, Note 2021-07-07T14.17.35, Note 2021-07-07T09.40.17, Note 2021-07-05T15.52.09, Note 2021-07-02T14.00.33, Note 2021-07-02T11.07.25, Note 2021-07-02T08.41.00, Note 2021-06-28T18.16.27, Note 2021-06-25T16.49.31, Note 2021-06-25T14.24.45, Note 2021-06-24T11.28.41, Note 2021-06-21T11.52.07, Note 2021-06-17T15.27.31, Note 2021-06-17T15.24.46, Note 2021-06-17T08.59.27, Note 2021-06-17T08.44.42, Note 2021-06-10T08.36.44, Note 2021-06-09T17.16.44, Note 2021-06-03T15.06.18, Note 2021-06-03T10.19.31, Note 2021-06-01T11.59.23, Note 2021-05-31T09.52.54, Note 2021-05-31T08.45.12, Note 2021-05-28T11.44.24, Note 2021-05-28T09.19.17, Note 2021-05-28T09.01.43, Note 2021-05-27T08.53.46, Note 2021-05-27T08.53.41, Note 2021-05-27T08.53.36, Note 2021-05-27T08.53.30, Note 2021-05-27T08.53.18, Note 2021-05-27T08.53.10, Note 2021-05-27T08.53.04, Note 2021-05-27T08.52.46, Note 2021-05-18T10.32.44, Note 2021-05-17T14.42.48, Note 2021-05-14T11.16.14, Note 2021-05-14T11.15.59, Note 2021-05-12T10.30.56, Note 2021-05-12T09.40.31, Note 2021-05-12T09.40.24, Note 2021-05-12T09.40.01, Note 2021-05-11T10.00.51, Note 2021-05-11T09.23.45, Note 2021-05-06T15.20.26, Note 2021-05-06T10.17.09, Note 2021-05-06T10.16.15, Note 2021-05-06T10.09.57, Note 2021-05-06T10.08.56, Note 2021-05-05T10.01.14, Note 2021-05-04T17.14.08, Note 2021-04-29T15.10.25, Note 2021-04-29T10.32.07, Note 2021-04-28T16.44.28, Note 2021-04-28T10.26.53, Note 2021-04-27T08.44.07, Note 2021-04-27T08.41.32, Note 2021-04-26T16.02.13, Note 2021-04-26T11.51.18, Note 2021-04-26T11.30.04, Note 2021-04-26T10.41.58, Note 7b7da6cb-78f1-4e14-8698-8f9a7f93d6e4, Note 86d288c9-2ef9-4c94-834b-8b8679b81007, Note b2412908-83f3-4f18-a418-27cb745e2abf`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**startInReadOnlyMode** (QString): `false`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Remove_note, action_Find_text_in_note, actionReplace_in_current_note, , actionFormat_text_bold, actionFormat_text_italic, actionFormat_text_underline, actionStrike_out_text`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Barra degli strumenti principale`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `barra degli strumenti formattazione`
**toolbar/3/items** (QStringList): `actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `barra degli strumenti "inserisci"`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `barra degli strumenti di crittografia`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `barra degli strumenti della finestra`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `esci dalla barra degli strumenti`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useSoftWrapInNoteEditor** (QString): `true`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (QString): `22222`
**workspace-b6636bd7-f245-4781-ac2a-e46bab618805/name** (QString): `Standard`
**workspace-b6636bd7-f245-4781-ac2a-e46bab618805/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-b6636bd7-f245-4781-ac2a-e46bab618805/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `b6636bd7-f245-4781-ac2a-e46bab618805`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**ANDROID_HOME**: `C:\Users\marco.bresciani\AppData\Local\Android\Sdk`
**ANDROID_SDK_ROOT**: `C:\Users\marco.bresciani\AppData\Local\Android\Sdk`
**APPDATA**: `C:\Users\marco.bresciani\AppData\Roaming`
**ChocolateyInstall**: `C:\ProgramData\chocolatey`
**ChocolateyLastPathUpdate**: `132645940048868119`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**COR_ENABLE_PROFILING**: `1`
**COR_PROFILER**: `{B74E4EB1-99CB-4B76-AF5F-2A0A973DC9A9}`
**destination**: `C:\Users\marco.bresciani\Chiavetta\QOwnNotes`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**GYP_MSVS_VERSION**: `2015`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\marco.bresciani`
**HYB_ENV_CODE**: `local-development`
**JAVA_HOME**: `C:\Program Files\Java\jdk1.8.0_241`
**LOCALAPPDATA**: `C:\Users\marco.bresciani\AppData\Local`
**LOGONSERVER**: `\\FRPARDC001`
**NUMBER_OF_PROCESSORS**: `12`
**NVM_HOME**: `C:\Users\marco.bresciani\AppData\Roaming\nvm`
**NVM_SYMLINK**: `C:\nodejs`
**OS**: `Windows_NT`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**portable**: `--portable`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 158 Stepping 13, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `9e0d`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PROMPT**: `$P$G`
**PSModulePath**: `%ProgramFiles%\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**QML_DISABLE_DISK_CACHE**: `true`
**qownnotesCommand**: `C:\Users\marco.bresciani\Chiavetta\QOwnNotes\QOwnNotes.exe --after-update C:\Users\marco.bresciani\AppData\Local\Temp\QOwnNotes-AZCoZH-updater.bat --portable`
**source**: `C:\Users\marco.bresciani\AppData\Local\Temp\QOwnNotes-AZCoZH.zip`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\MARCO~1.BRE\AppData\Local\Temp`
**TMP**: `C:\Users\MARCO~1.BRE\AppData\Local\Temp`
**unzipCommand**: `C:\Users\marco.bresciani\AppData\Local\Temp\QOwnNotes-AZCoZH-unzip.exe -o C:\Users\marco.bresciani\AppData\Local\Temp\QOwnNotes-AZCoZH.zip -d C:\Users\marco.bresciani\Chiavetta\QOwnNotes`
**unzipExecutable**: `C:\Users\marco.bresciani\AppData\Local\Temp\QOwnNotes-AZCoZH-unzip.exe`
**USERNAME**: `marco.bresciani`
**USERPROFILE**: `C:\Users\marco.bresciani`
**windir**: `C:\WINDOWS`
**ZES_ENABLE_SYSMAN**: `1`
</details>

**Comment by pbek** [comment]
> Expected behaviour

I'm not sure what should be "expected" here, since those are not part of the original "spec" (https://daringfireball.net/projects/markdown/syntax)...
Thoughts, @Waqar144?

**Comment by Waqar144** [comment]
One can expect that sure, but there are a lot more cases. Our markdown link parsing is rather basic compared to some other things and IIRC the reasoning was that we expect the user to put in "sane" links. So `[Link with brackets](link)` is sane but you can add more brackets in there probably as many as you like and it would be valid according to the markdown spec but not sane.

**Comment by pbek** [comment]
Yes, I personally also wouldn't use links that are not "sane", they would just confuse and distract me...
