### ISSUE TITLE
[BUG] The script repository doesn't show any scripts any more

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#2772]
The script repository doesn't show any scripts any more.

Internal the GitHub search API returns: `{\"message\":\"Requires authentication\",\"errors\":[{\"message\":\"Must be authenticated to access the code search API\",\"resource\":\"Search\",\"field\":\"q\",\"code\":\"invalid\"}],\"documentation_url\":\"https://docs.github.com/rest/reference/search#search-code\"}"`

The reason for that are changes in the GitHub search API: https://github.blog/changelog/2023-03-10-changes-to-the-code-search-api/
Basically the search API can't be accessed without authentication any more.

This can be tested on the terminal:

```bash
curl "https://api.github.com/search/code?q=+in:file+language:json+repo:qownnotes/scripts&page=1"
```

## Solution

~~- [ ] QOwnNotes needs some way to input and store a generated GitHub access token (<https://github.com/settings/tokens>).~~
~~- [ ] QOwnNotes needs to send this token with all search requests.~~

- [x] Create workflow that creates an index of the metadata of all scripts on https://github.com/qownnotes/scripts/
- [x] Integrate that index into QOwnNotes

**Comment by pbek** [comment]
@flexid2000, @mamo2021

**Comment by pbek** [comment]
## 23.4.4
- the **script repository integration was rewritten**, because GitHub now demands
  an access token for the code search API and has a harsh quota on the amounts of
  searches per person (for [#2772](https://github.com/pbek/QOwnNotes/issues/2772))
  - an index will now be generated on the [Script Repository on GitHub](https://github.com/qownnotes/scripts),
    which can be accessed by QOwnNotes without using the code search API of GitHub
  - script searches, installs and updates are now **much faster**, because only
    one single request is made
  - all scripts are now **shown instantly**, instead of needing to search for
    a script and browse multiple pages
  - scripts are now **searched while typing** in the search bock, instead of
    only when pressing <kbd>Enter</kbd>

**Comment by pbek** [comment]
@flexid2000, @mamo2021
There now is a new release, could you please test it and report if it works for you?

**Comment by flexid2000** [comment]
Great! Works. Thanx.

**Comment by pbek** [comment]
Great, thank you for testing!
It was a lot of work. 😅

**Comment by pbek** [comment]
## 23.4.6
- the **manual and automatic script update** process now also works again after the script
  repository integration re-implementation (for [#2772](https://github.com/pbek/QOwnNotes/issues/2772))
