### ISSUE TITLE
[FEATURE] change the color of the horizontal rule ("---") for dark mode

### ISSUE THREAD

**Issue by GarryFlemings** [pbek/QOwnNotes#2773]
##### PC

(No updates available on Windows Update.)
Edition	Windows 10 Home
Version	22H2
Installed on	‎5/‎20/‎2021
OS build	19045.2846
Experience	Windows Feature Experience Pack 120.2212.4190.0

##### QOwnNotes

updated today, v 23.4.5

#### Is your feature request related to a problem? Please describe.

It'd be great for the horizontal rule ("---") to be more visible in dark mode. For me, it looks like this:

![image](https://user-images.githubusercontent.com/14095071/232883693-b3e8ce96-7516-4288-9d28-9c02ecd9ca41.png)

The left side is Markdown. The right side is rendering.

The horizontal rule is rendered in a faintly darker grey (or maybe black).

#### Describe the solution you'd like

A lighter color for the horizontal rule.

#### Describe alternatives you've considered

* White is better.
* The same color as the default text might be better yet.

**Comment by pbek** [comment]
Best check out https://github.com/pbek/QOwnNotes/issues/2272#issuecomment-947871989.

**Comment by GarryFlemings** [comment]
Duplicate indeed!
