### ISSUE TITLE
[FEATURE] Lighten some text in dark mode.

### ISSUE THREAD

**Issue by GarryFlemings** [pbek/QOwnNotes#2774]
#### PC

(No updates available on Windows Update.)
Edition Windows 10 Home
Version 22H2
Installed on ‎5/‎20/‎2021
OS build 19045.2846
Experience Windows Feature Experience Pack 120.2212.4190.0

#### QOwnNotes

updated today, v 23.4.5

### Steps to reproduce

I'm shy to be confident this is a "bug"; that's your call. I'll say maybe.

* Operate in dark mode via _Note_ > _Settings_ > _Interface_ > _Enable dark mode_, checked

![image](https://user-images.githubusercontent.com/14095071/232899362-f48d0046-1ef5-49b5-abeb-b4ccb53a0225.png)

The box checked is in the top right. Some of the click-path is on the left.

### Current behaviour, dark mode

![image](https://user-images.githubusercontent.com/14095071/232902680-51e71c22-c41a-4674-980d-95177ee8adae.png)

Note the dark text in the

* "Search for language" box at the top of the language list (middle column).
* Second and last checkboxes (right column).

Probably, these greys are too dark; I doubt they pass accessibility checks. You'll find other examples.

Contrast with the light mode appearance below.

### Current behaviour, light mode

![image](https://user-images.githubusercontent.com/14095071/232902008-469649ff-8fb5-417d-82dd-bda2a8612a4a.png)

Maybe these greys are little light; they may not pass accessibility checks.

#### Horizontal rule

dark

![image](https://user-images.githubusercontent.com/14095071/232909580-7a6f5c7e-8790-425b-8f86-727d144f9f1a.png)

The left column is Markdown script. The right column is corresponding rendering.

At first look, the horizontal rule may appear to be absent on the right. It's there; there's very little contrast with the background.

light

![image](https://user-images.githubusercontent.com/14095071/232911675-320122d1-0199-4e6e-8537-7b0c64888ac9.png)

#### Menu bar

Intermittently, the menu bar goes a little foul in switching between dark and light.

dark

![image](https://user-images.githubusercontent.com/14095071/232909375-d9234470-156b-4dfb-8a89-43ba70eeaad1.png)

light

![image](https://user-images.githubusercontent.com/14095071/232907687-d419759d-84d4-4f06-9912-81c1346c3877.png)

There's not enough detail on this last one. Sorry. I noticed it and included it. I didn't take enough time to fully investigate.

Mine is only one vote: The dark mode is easier on the eyes in a dark room and the light mode is more functional here (and maybe always).

**Comment by pbek** [comment]
You can do all those changes with the "Custom preview styling" script and maybe then propose those changes here.
As example for putting that into an own script there is a script "Black mode" in the script repository.

**Comment by GarryFlemings** [comment]
Seems like another duplicate. 😁
