### ISSUE TITLE
support Markdown definition lists

### ISSUE THREAD

**Issue by thilop** [pbek/QOwnNotes#2777]
It would be nice to be able to use definition list, like HTML supports.

They are described here https://www.markdownguide.org/extended-syntax/#definition-lists

```
First Term
: This is the definition of the first term.

Second Term
: This is one definition of the second term.
: This is another definition of the second term.
```

One could also use unordered lists, but that really is another beast.

**Comment by Waqar144** [comment]
Yep, as far as I can see its not supported.

**Comment by anmsh** [comment]
There is a plugin called definition lists. Seems to work. Please try it. https://github.com/qownnotes/scripts/tree/master/definition-lists

**Comment by anmsh** [comment]
Outputs this markup:

```
<dl>
  <dt>First Term</dt>
  <dd>This is the definition of the first term.</dd>
</dl>
<dl>
  <dt>Second Term</dt>
  <dd>This is one definition of the second term.</dd>
  <dd>This is another definition of the second term.</dd>
</dl>
```

**Comment by pbek** [comment]
Great finding. 😁
