### ISSUE TITLE
Installation instructions for Debian are wrong

### ISSUE THREAD

**Issue by sseide** [pbek/QOwnNotes#278]
The first command to add the repository to the sources list is wrong - only echo is executed as root, the stdout redirection is done as the normal shell user and therefor fails to write the new sources file.

Change the command to:
<pre>
sudo bash -c "echo 'deb http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Debian_8.0/ /' >> /etc/apt/sources.list.d/qownnotes.list"
</pre>

**Comment by pbek** [comment]
Thanks a lot for letting me know and your help! I just changed the instructions on <http://www.qownnotes.org/installation>.
