### ISSUE TITLE
[FEATURE] Support for Forth Language Highlighting

### ISSUE THREAD

**Issue by 0x3508A** [pbek/QOwnNotes#2780]
#### Is your feature request related to a problem? Please describe.
I am a Forth language enthusiast and an avid user of QOwnNotes. 
While writing my notes for Forth language, I noticed that there was no highlighting for the Forth source code.
I wish to request for support to add this facility in future release of QOwnNotes.

#### Describe the solution you'd like
I wish that the Forth language keywords and symbols to be highlighted.

#### Describe alternatives you've considered
There is possibility to add custom CSS for the generated HTML.
But output generated the QOwnNotes does not recognize the Forth programming language.
Hence such highlighting can't be applied.

#### Additional context
I have already requested for the merge of a pull request on https://github.com/pbek/qmarkdowntextedit/pull/184
Wish to add support for the same here.

#### Output from the debug section in the settings dialog

Not Applicable

**Comment by 0x3508A** [comment]
Please update the `pbek/qmarkdowntextedit` sub-module. My integration build is failing.
If I can do this on my fork, kindly guide me for the same.

**Comment by pbek** [comment]
I did.

**Comment by 0x3508A** [comment]
Thanks for taking the pull request and guiding me.

One thing I wish to do is to keep updating `qmarkdowntextedit` on my fork.
To build and test the QOwnNotes binary.
However, I found setting up of the full environment on my PC to be quite difficult.
Hence I am using the Dev workspace feature of Github to create a virtual environment to edit.
This environment has capability to commit and pull changes from any branch.
I wish to request guidance on how I can perform an actual build in this virtual environment.
From the look of things its a Ubuntu Linux environment.
Kindly guide me on this.

**Comment by pbek** [comment]
Thank you for your effort!

>  However, I found setting up of the full environment on my PC to be quite difficult.

Difficult to install or difficult to configure?

>   I wish to request guidance on how I can perform an actual build in this virtual environment.

I never tried that, is that even possible with a free GitHub account? To my understanding (paying) companies can give a build env to their employees. Let me know if you find out more! Would be interesting. 😁 

Nowadays I work mostly on NixOS (and sometimes KDE Neon, based on Ubuntu).

**Comment by 0x3508A** [comment]
Thanks for updating. Sure, I will update my own notes and check.

You are right setting up Qt and build is bit out of my league.
Anything possible using VS Code and some direct installs it would be easier.
Yesterday I tried installing Qt, there are so many options so I paused there.
I am still working on this.

**Comment by 0x3508A** [comment]
Just checked some part of comment highlighting does work.
![image](https://user-images.githubusercontent.com/124862084/236248223-449c5719-397a-4307-bbfb-88ac898313e9.png)

Looks like this still need more enhancement to the https://github.com/pbek/qmarkdowntextedit
It means I need to get a working Qt build setup. Else sending pull request would be tough.
Request your kind guidance again for the the way ahead.

**Comment by pbek** [comment]
Under Linux you just would need to install a bunch of packages and are ready to go. Under windows you could either download QtCreator from Qt directly or use https://www.msys2.org/ and install the Qt packages from there.

qmake
make

Should do it then on the terminal.

**Comment by 0x3508A** [comment]
Thanks for your guidance.
I have successfully installed Windows QT distribution for `Qt 6.2.4 (MinGW 11.2.0 64-bit)`.
Using that I am able to build the QOwnNotes.

Its is a very round about process to setup the toolchain.
One needs to create a user account to access Qt tools.
There were a few important packages missing in the default install.
**Qt 5 Compatibility Module** and **Qt Websockets**
Once they were installed the build worked fine.

-----

I would love to explore the **MSYS2** path as well sometime.
Since, it would greatly reduce the need to mess around with the Windows system configuration and multiple tool installations.

-----

For specific to Windows QT build I had to add the following to `.gitignore` :
```gitignore
/src/Makefile.*
/src/debug/
/src/object_script.*
/src/release/
/src/mocinclude.*
```

Kindly confirm if this is alright.

-----

I wish to begin modification to `src\libraries\qmarkdowntextedit`.
This would allow to directly modify the Forth highlight in the editor.
It would then be possible to add these modifications and build back QOwnNotes.

Kindly let me know if this would be right way to move forward.

**Comment by pbek** [comment]
> I would love to explore the MSYS2 path as well sometime.
> Since, it would greatly reduce the need to mess around with the Windows system configuration and multiple tool installations.

I only let me demonstrate the installation of the tools and build process of QOwnNotes my a friend (and Maintainer of msys) two days ago. Seems to work quite well...

> Kindly confirm if this is alright.

I don't mind. Those path are affected by the parameters you put to qmake....

>  It would then be possible to add these modifications and build back QOwnNotes.
> Kindly let me know if this would be right way to move forward.

You are on the right track.
