### ISSUE TITLE
[BUG] Failed to start in Ubuntu 23.04

### ISSUE THREAD

**Issue by gizmaa** [pbek/QOwnNotes#2783]
#### Expected behaviour
Normal start

#### Actual behaviour
No GUI or notification of failure is created.

- Ubuntu 23.04 (installed a few days ago)
- X11 used instead of Wayland
- QOwnNotes version 23.5.2, snap version installed via the store

Starting via the command line returns errors

#### Command Line Output

> (QOwnNotes:37610): Gtk-WARNING **: 13:46:22.606: Theme parsing error: gtk.css:1413:23: 'font-feature-settings' is not a valid property name
> 
> (QOwnNotes:37610): Gtk-WARNING **: 13:46:22.609: Theme parsing error: gtk.css:3286:25: 'font-feature-settings' is not a valid property name
> 
> (QOwnNotes:37610): Gtk-WARNING **: 13:46:22.610: Theme parsing error: gtk.css:3748:23: 'font-feature-settings' is not a valid property name
> Gtk-Message: 13:46:22.638: Failed to load module "canberra-gtk-module"
> Gtk-Message: 13:46:22.639: Failed to load module "canberra-gtk-module"
> Warning: Qt: Session management error: Could not open network socket (:0, )
> Fontconfig warning: FcPattern object weight does not accept value [0 205)
> Segmentation fault (core dumped)

**Comment by pbek** [comment]
Strange, haven't seen any of these errors before...
Does the PPA, flatpak or AppImage work on your system?
https://www.qownnotes.org/installation/

**Comment by pbek** [comment]
Yes, best try the PPA if it suits you. Your error could be some kind of snap confinement problem, which I cannot fix anyway...

**Comment by george2781** [comment]
Had the same issue so I decided to remove the snap version and install the PPA version and it works, only issue is the border around the windows are white despite me using dark theme, but I've lived with worse before so I'm not too bothered.

**Comment by pbek** [comment]
There is a script for styling the ui.

**Comment by mjdubbs** [comment]
I had this same issue with the snap in 23.04.

I fixed it following advice from [here](https://github.com/keshavbhatt/olivia/issues/95#issuecomment-774747492)

``
`rm ~/.cache/fontconfig/*
fc-cache -r
```

**Comment by martin-schell** [comment]
Hello, the workarround of @mjdubbs fixed the problem on my system with Ubuntu 23.04 and QOwnNotes as Snap, too. Thank you very much.
