### ISSUE TITLE
[SUPPORT] Find/Replace newline char

### ISSUE THREAD

**Issue by vdraceil** [pbek/QOwnNotes#2785]
#### Question

Is there a way to find & replace the newline `\n` character?
With regex, I can only use `\s` but that matches all space chars.
`\n` doesnt seem to work in any mode - plain-text/whole-word/regex

I want to replace multi-newline chars with one newline char. Essentially, optimizing my note's newline spacing.

**Comment by pbek** [comment]
Best do that in plain JavaScript as a script.
You most likely don't even need a regexp, you could do that with split too, like in:
https://github.com/qownnotes/scripts/blob/c8e289596813632be92384d46f7130c012f1abed/sort-lines/sort-lines.qml#L29

But there are plenty examples with regexp too in the script repository.

If you want you can also contribute your script, see https://github.com/qownnotes/scripts/tree/master#contributing. 😉
