### ISSUE TITLE
Settings window opened from assitant on first run is too small

### ISSUE THREAD

**Issue by sseide** [pbek/QOwnNotes#279]
after installation (debian package) and starting QOwnNotes for the first time the assistent gives the possibility to configure owncloud and the network settings. Pressing one of these two buttons (step 2 and 3) opens a new window to configure the settings.

This new window is only something around 5x5 pixels large and must be manually enlarged to see the content. Please specify an fitting min width and heigth while opening the settings window from the assistant. The missing size only affects the first-run-wizard.

Debian Linux 64Bit XFCE desktop environment

**Comment by pbek** [comment]
Thank you for reporting, it seems like XFCE allows resizing a window smaller than its widgets allow it to be. I will try to take care about that...

**Comment by pbek** [comment]
I can't find anything that could cause this, is there an other dialog that has the same problem?
Could you try to move your `~/.config/PBE/QOwnNotes.conf` away while QOwnNotes is closed and try if the welcome dialog is still small this time?

**Comment by sseide** [comment]
I have not found any other dialog in the program which is to small, all others are fine.

And it is not the welcome dialog themself - this is fine. But on Step 2 from the welcome dialog after pressing the button the new dialog with the OwnCloud settings and on step 3 the new dialog with the network settings - these are to small.

Opening the settings dialog later on from within the program via the menu entry the size is fine.

What did you mean with "is still small this time"? Is there any update or something? currently running v16.08.2. I moved the config away and same thing happend again. The settings dialogs are to small when opened from the welcome dialog

**Comment by pbek** [comment]
> And it is not the welcome dialog themself

So the settings dialog is too small, right?
But it is not too small when you open it a 2nd time (without clearing the settings).
Is anything else too small?

> What did you mean with "is still small this time"?

I just wanted to know if you can reproduce that a 2nd time.
No need to do that now in this case.

**Comment by sseide** [comment]
> >  And it is not the welcome dialog themself
> So the settings dialog is too small, right?
Yes.

> But it is not too small when you open it a 2nd time (without clearing the settings).

Just restarting with a fresh install (config removed):
-> Start QOwnNotes 
-> First page of welcome Dialog (fine) -> press Next
-> Second page of welcome dialog (fine) 
-> Open Owncloud settings (dialog to small)
    -> making some changes in the settings -> pressing OK to close settings dialog
-> Open Owncloud settings again (dialog to small) (and so one)
-> Next page in welcome dialog -> Open network settings (dialog to small)
    -> opening Network settings here behaves the same as Owncloud settings on 2 page of welcome dialog. 

-> Press finish to close welcome dialog
-> New dialog with info about "usage tracking" appears
-> pressing "Open settings" -> new dialog to small (same as with owncloud settings)
-> pressing "OK" to close "usage tracking"

In the main program opening the menu "note" -> "settings" -> Settings dialog is fine, size as large as needed. Opening the settings this way the gui is working as exprected.
 
> Is anything else too small?
No, everything else is fine.

> > What did you mean with "is still small this time"?
> I just wanted to know if you can reproduce that a 2nd time.
This happened on two different computers (both are Debian 64Bit/ XFCE)

Thanks

**Comment by pbek** [comment]
## 16.08.3
- fixed a problem with XFCE where the settings dialog had a geometry
  of 1x1 pixels
    - additionally now the geometry of all dialogs will be saved when 
      the window is resized and restored when the dialog is opened

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by sseide** [comment]
Thanks a lot - works as expected now.

**Comment by pbek** [comment]
Great!
