### ISSUE TITLE
[DISTRO] Please add OpenSUse Leap 15.5 to your supported Linus distros

### ISSUE THREAD

**Issue by euneuber** [pbek/QOwnNotes#2790]
Open Suse Leap 15.4 is nearing End Of Life (estimated November 2023), migration to 15.5 has begun...

Please add a repo tailored to 15.5 for downloading and upgrading your wonderful QOwnNotes program!

**Comment by pbek** [comment]
Thank you, I did now. It is currently building on https://build.opensuse.org/package/show/home:pbek:QOwnNotes/desktop.

**Comment by euneuber** [comment]
Thank you! I#m already using it!
