### ISSUE TITLE
Backticks are not filtered in navigation list

### ISSUE THREAD

**Issue by patvdv** [pbek/QOwnNotes#2791]
#### Expected behaviour

When using backticks in any markdown header line, the resulting preview of the navigation list does not filter the backticks. Other markup like italic or bold IS filtered out correctly in preview mode

#### Actual behaviour

* Backticks should be shown in edit mode: OK
* Backticks should be filtered in preview mode: NOK

#### Steps to reproduce

See screenshots:
**edit mode**:
![edit-mode](https://github.com/pbek/QOwnNotes/assets/12430107/312492e0-f244-41aa-b145-d1178513a497)

**preview mode**:
![preview-mode](https://github.com/pbek/QOwnNotes/assets/12430107/62d2c381-e7db-4e05-8c46-23abf9db9fa6)

**Comment by pbek** [comment]
I think I still don't get what we are talking about.

![image](https://github.com/pbek/QOwnNotes/assets/1798101/3678a7e3-bbf0-45b9-9acb-f4afefe3030e)

The Navigation panel does not generate HTML out of Markdown... Or are you talking about the preview?

Can you please describe what you expected, what the actual behavior was, and step by step what you did?

**Comment by patvdv** [comment]
Hi,

I made a mistake in assuming bold and italic were being stripped out. My eyes were deceiving me. The behaviour is indeed consistent for all markup. My apologies for that. However: I don't see the logic in displaying markup as raw markdown in the navigation panel. It is quite distracting, IMHO a navigation list of plain text makes more sense to me. Would it be possible to make this optional?

**Comment by pbek** [comment]
Do you consider using code block in headlines "good-practice"? I don't know if I've seen anyone doing that. Would also would look ugly when you link to a headline...

And it possibly would be hard on the CPU of slower computers if a Markdown parser would be fired up a few 100 times for a few 100 headlines each time something changes in the note. 🤔

**Comment by pbek** [comment]
Opinions, @Waqar144?

**Comment by Waqar144** [comment]
We should only strip them out if we can render it according to the markdown syntax. Otherwise it can be misleading imo

**Comment by pbek** [comment]
Yes, good point. We still would need to interpret the headings, "kind of"... Otherwise, we would remove single `*`, `~` or `_` to...

**Comment by patvdv** [comment]
> Do you consider using code block in headlines "good-practice"? I don't know if I've seen anyone doing that. Would also would look ugly when you link to a headline...
> 
> And it possibly would be hard on the CPU of slower computers if a Markdown parser would be fired up a few 100 times for a few 100 headlines each time something changes in the note. 🤔

I use it all the time in technical notes. When referring to _host names_ for example I prefer these to be indicated by a `monospace` type. Wikis typically have a preformatted markup for this, like a double single quote in Dokuwiki or the tripe single quote in Mediawiki. The backtick is the only way to achieve this in markdown AFAIK. And it does work! But cannot comment on the (CPU) efficiency.

**Comment by patvdv** [comment]
> 

No, they don't. Most wiki have their own markup language with often commonalities. I just the example for the sake of a comparison only. 

For me this is not a major issue, consider it a nice to have for the future. IMHO, it makes sense to see the markup in the navigation panel when working in an _edit_ layout. Likewise, it would make sense to show a rendered navigation panel when the app is in a preview-only mode. I am not sure how to resolve this consistently as you can have an edit & preview panel in the same workspace of course. I prefer to keep them separate to save screen space.

**Comment by pbek** [comment]
There is now "preview only mode"... Workspaces are complete free to generate.
I wanted to try to strip the characters, but it's not easy to do that without stripping too many, so one would need to write a pseudo Markdown parser to only strip those of formattings and then strip the correct white spaces between the words, like in:

```markdown
## test * test

## test ~ test
```

**Comment by pbek** [comment]
Something like this:

![image](https://github.com/pbek/QOwnNotes/assets/1798101/78abc1a3-f7e6-4fd9-a7b6-75500c42e89c)

**Comment by patvdv** [comment]
> ## 23.6.5
> 
>     * **Markdown is now stripped** out of the heading text in the **navigation panel** to
>       improve readability (for [#2791](https://github.com/pbek/QOwnNotes/issues/2791))
> 
> 
> There now is a new release, could you please test it and report if it works for you?

Hi,

I installed the new release and it looks perfect to me. Many thanks for the fix! Perhaps to consider for other users: making this feature optional or not. For me it would certainly be the default to have the markup filtered in the navigation panel.

**Comment by pbek** [comment]
Thank you for testing!
Is don't really see a reason to make this optional, since Markdown syntax in the navigation is pretty distracting (as it is in the heading itself, in my opinion 😅).
