### ISSUE TITLE
[BUG] Windows Defender classifies version 23.6.5 as malware

### ISSUE THREAD

**Issue by scharmach** [pbek/QOwnNotes#2793]
![grafik](https://github.com/pbek/QOwnNotes/assets/9080980/339f3db8-e31a-46e9-a4bd-ccd82424f233)

**Comment by pbek** [comment]
Windows Defender is prone to false positives. Is any other scanner reporting the same issue?

**Comment by scharmach** [comment]
I've searched for a Windows Defender update and it's now no longer detected, also not by any other scanner:

https://www.virustotal.com/gui/file/9116602196fe8474a027cbeb8fd1179c29258c13d41cc1573e111cd545b26ba3

This issue can be closed.
