### ISSUE TITLE
[BUG] "Search or create note" field trims spaces

### ISSUE THREAD

**Issue by szotsaki** [pbek/QOwnNotes#2796]
1. Create a document which contains `abcdefgh`
2. Search for whitespace issues, like ` a  `
3. Paste the above into the global search bar "Search or create note" field

The global search shows you the newly created document with number "1" as the number of matches. When clicking into it, the local search shows up telling that the requested expression cannot be found.

It'd be nice if the two search fields (global and local) would behave like each other.

Version: 23.6.6

**Comment by pbek** [comment]
Try `"a "`, see https://www.qownnotes.org/getting-started/searching.html

> It'd be nice if the two search fields (global and local) would behave like each other.

They have different jobs.
