### ISSUE TITLE
[BUG] Nextcloud connection error

### ISSUE THREAD

**Issue by HHZZUUJH** [pbek/QOwnNotes#2797]
QOwnNotes 23.6.6
[Nextcloud Hub 4](https://nextcloud.com/) (26.0.2)
QOwnNotesAPI

Hello, in the settings /Nextcloud OwnCloud connection to the Nextcloud server works fine. I can also select the note folder on the Nextcloud server correctly. But if I want to reload the note folder (synchronize) I get the error message: Nextcloud /ownCloud server error: Invalid quera, please check the syntx. Please check your Nextcloud settings.

Thank you. Bets regards.

**Comment by pbek** [comment]
Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting Debug in Options).

And can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.

**Comment by pbek** [comment]
And what logs do you get on your Nextcloud server?

**Comment by HHZZUUJH** [comment]
good day and many thanks

QOwnNotes debug

log with Warning


"QNetworkReply error 203 from url https://www.myServer.de/ocs/v2.php/apps/files_sharing/api/v1/shares: " "Error transferring https://www.myServer.de/ocs/v2.php/apps/files_sharing/api/v1/shares - server replied: Not Found"

logs on Nextcloud server

[PHP] Fehler: Using ${var} in strings is deprecated, use {$var} instead at /....../www/nxc/3rdparty/scssphp/scssphp/src/Compiler.php#3491

GET /index.php/apps/theming/theme/light.css?plain=0&v=0d9bc57f
from Server-IP by user at 2023-07-09T08:21:19+00:00

[qownnotesapi] Fatal: Error: Failed opening required '/........./www/nxc/apps/qownnotesapi/appinfo/application.php' (include_path='/......./www/nxc/3rdparty/pear/archive_tar:/......./www/nxc/3rdparty/pear/console_getopt:/......../www/nxc/3rdparty/pear/pear-core-minimal/src:/......../www/nxc/3rdparty/pear/pear_exception:/......./www/nxc/apps') at <<closure>>

0. <<closure>>
   OC\Autoloader->load("OCA\\QOwnNotesAPI\\AppInfo\\Application")
1. /....../www/nxc/lib/private/AppFramework/Bootstrap/Coordinator.php line 129
   class_exists("OCA\\QOwnNotesAPI\\AppInfo\\Application")
2. /......../www/nxc/lib/private/AppFramework/Bootstrap/Coordinator.php line 90
   OC\AppFramework\Bootstrap\Coordinator->registerApps(["files","activi ... "])
3. /......./www/nxc/lib/base.php line 692
   OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
4. /......./www/nxc/lib/base.php line 1169
   OC::init()
5. /......./www/nxc/remote.php line 119
   require_once("/......../www/nxc/lib/base.php")

**Comment by HHZZUUJH** [comment]
ATTENTION ..myServer.de... is not a real URL, please do not call it. I just put that without thinking.

**Comment by pbek** [comment]
Hard to tell without you sharing your settings... (see https://github.com/pbek/QOwnNotes/issues/2797#issuecomment-1627481588)

Have you tried restarting your Nextcloud server, could be an autoloader issue.

> "Error transferring ..../ocs/v2.php/apps/files_sharing/api/v1/shares - server replied: Not Found"

Hard to tell too, maybe you have set up paths incorrectly?

**Comment by pbek** [comment]
👍🏻
