### ISSUE TITLE
[SUPPORT] Source Download for v23.7.0 is missing from tuxfamily

### ISSUE THREAD

**Issue by TimB87** [pbek/QOwnNotes#2798]
Hi @pbek 

The source tar ball is missing for the latest release [1]. Can you please add it? :)

Thanks a lot and have a great start into the week!
Best,
Tim

 [1] https://download.tuxfamily.org/qownnotes/src/

**Comment by pbek** [comment]
I still can't, the upload server is down...

**Comment by pbek** [comment]
We'll switch to GitHub releases for hosting...

**Comment by pbek** [comment]
Closed for #2799.
