### ISSUE TITLE
Windows 7 - Connection error message: Unable ti init SSL Context:

### ISSUE THREAD

**Issue by Pisoko** [pbek/QOwnNotes#28]
Hey pbek,

I've got an issue until connecting to my owncloud with your windows client:

`Connection error message: Unable ti init SSL Context:`

OpenSSL 1.0.2e (64bit) is installed. (from heiße.de)

________________________________________________
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fr Jan 8 08:39:53 2016`
**Version**: `0.74`
**Build date**: `Jan  7 2016`
**Build number**: `726`
**Platform**: `windows`
**Release**: *empty*
**Platform**: `windows`
**Qt Version**: `5.4.2`

## Server Info

**serverUrl**: `https://oc.ufz.de`
**appIsValid**: `no`
**connectionErrorMessage**: `Unable to init SSL Context: `

## Settings

**MainWindow/geometry**: `<binary data>`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.font**: `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/windowState**: `<binary data>`
**ShowSystemTray**: `false`
**SortingModeAlphabetically**: `false`
**cryptoKey**: `<hidden>`
**mainSplitterSizes**: `<binary data>`
**noteSaveIntervalTime**: `10`
**notesPath**: `C:/Users/alber/testpilotcloud/Notes`
**notifyAllExternalModifications**: `false`
**ownCloud/localOwnCloudPath**: `C:/Users/alber/testCloud/Notes`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: `https://oc.ufz.de`
**ownCloud/todoCalendarBackend**: `0`
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloud/userName**: `alber`
**recentNoteFolders**: `C:/Users/alber/ownCloud/Notes, `

**Comment by pbek** [comment]
Hi @Pisoko ! Thank you for your report!
Did you install OpenSSL? Sadly this is necessary on Windows (it's mentioned in the settings).

**Comment by Pisoko** [comment]
OpenSSL 1.0.2e (64bit) is installed. (from heiße.de)

**Comment by pbek** [comment]
Oh, sorry. I totally overread that! I will see if I can reproduce that problem locally...

**Comment by Pisoko** [comment]
if you need a testaccount on my cloud..let me know.

**Comment by Pisoko** [comment]
Mayb it's a firewall problem.. do you need other ports then 80/443?

**Comment by pbek** [comment]
I just installed OpenSSL (`Win32 OpenSSL v1.0.2e Light` from <http://slproweb.com/products/Win32OpenSSL.html>) on a Windows 10 box. I let the installer copy the DLLs to the system directory (that's important). After I restarted QOwnNotes I could connect to my https Server.

Are the OpenSSL DLLs in your system directory?

Port 80/443 should be enough...
If you give me an account I can test it on your server too...

**Comment by pbek** [comment]
Now I did the same on a Windows 7 box, again there was a `libssl32.dll` in `C:\Windows\SysWOW64` and I could connect to my ownCloud server via https.

**Comment by Pisoko** [comment]
Ok.. libssl32.dll is in C:\Windows\SysWOW64 but it doesn't work.

Try it yourself pls:
`owncloud.ufz.de`
`qbek`
`77G&jCt&$d6E`

**Comment by pbek** [comment]
It did work for me under Windows 7.

## Server Info

**serverUrl**: `https://owncloud.ufz.de`
**appIsValid**: `yes`
**serverVersion**: `8.1.4.2`
**appVersion**: `0.4.1`

Are the other DLLs also in place? `libeay32.dll`, `libssl32.dll`, `ssleay32.dll`

**Comment by Pisoko** [comment]
yes of cause :/

**Comment by pbek** [comment]
Can you please try to copy `libeay32.dll`, `libssl32.dll` and `ssleay32.dll` to your QOwnNotes folder (where the `QOwnNotes.exe` is). It also worked for me that way when they aren't in the Windows system folder.

**Comment by Pisoko** [comment]
Oh man.. I am sry.. I simply have to restart windows after that OpenSSL-Installation. Now it works fine. ;) THX!

**Comment by pbek** [comment]
That's great! I'm glad it now works.
Just for the protocol, so you didn't have to (and didn't have) copy `libeay32.dll`, `libssl32.dll` and `ssleay32.dll` to your QOwnNotes directory?

**Comment by Pisoko** [comment]
I don't.. they still in C:\Windows\SysWOW64

**Comment by pbek** [comment]
Ok, great! I think I will include the OpenSSL library in the future, it's too much of a hassle to install it by hand. ownCloud also includes the OpenSSL library with their desktop client.
