### ISSUE TITLE
Change colors default for syntax highlights and preview

### ISSUE THREAD

**Issue by vpistis** [pbek/QOwnNotes#280]
Would be a great enhancement if it were possible to manage colors syntax and colors preview.
This is a screenshot of my QOwnNotes installation (inot macos) where colors are not so pretty:
![schermata 2016-08-09 alle 17 10 11](https://cloud.githubusercontent.com/assets/1496665/17521612/3838ec80-5e54-11e6-89ce-4e873754ccc4.png)

**Comment by pbek** [comment]
It seems you have the dark mode colors enabled in the interface settings.

**Comment by vpistis** [comment]
thank you...is the "optimize colors..." that is checked now it's better :)

In any way the default colors theme are not so pretty for me :) ...if there is a way to change it manually into some files, for me it's ok :)

**Comment by pbek** [comment]
This is currently only possible in the source code: <https://github.com/pbek/QOwnNotes/blob/develop/src/widgets/qownnotesmarkdowntextedit.cpp#L46>

Maybe there will be some other way to do this in the future, I'll keep your issue for reference.

**Comment by vpistis** [comment]
ok thanx

**Comment by pbek** [comment]
I'm currently working on this... ;)

**Comment by vpistis** [comment]
thanx :-)

**Comment by pbek** [comment]
after five days of work...

## 16.08.19
- finally there are configurable **editor color schemes**
  (for [Issue #280](https://github.com/pbek/QOwnNotes/issues/280))
    - there are two default schemes called `Default` and `Dark` that
      are mimicking the current default mode and the dark mode colors
    - you can create as many schemes as you like by copying and
      modifying them
    - you can change the foreground color, background color, bold state,
      italic state and underline state
    - you can export schemes to files and import them again from 
      these files
        - if you come up with a good and proven color theme, that should
          be included by default, please let me know 

There now is a new release, could you please test it and report if the new features work for you?

**Comment by pbek** [comment]
And it is probably worth knowing that you can change the html code of the preview (and thus the CSS to modify how everything looks like) in a script. Take a look at `noteToMarkdownHtmlHook` in <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/example.qml>

**Comment by richarson** [comment]
Nice!
Probably solarized themes will be popular but I don't know if I can make them, I suck at creative work :)

**Comment by pbek** [comment]
Take your time. :)

**Comment by vpistis** [comment]
wow...very nice thank you so much :)

**Comment by pbek** [comment]
;)

**Comment by pbek** [comment]
## 16.08.20
- more editor color scheme improvements
    - you are now able the adapt the font size for each highlighting item
        - you will be able to see the adapted font size in the item preview
    - the highlighting items were reordered
    - the schema `Default` was renamed to `Light`

There now is a new release, could you please test it and report if the new features work for you?

@Dreadeath, this may also be of interest for you
