### ISSUE TITLE
Sync tags with Nextcloud Notes' categories

### ISSUE THREAD

**Issue by zyll71** [pbek/QOwnNotes#2800]
I'm tagging my notes on QOwnNotes to bring in some order. However, the tags don't show up in Nextcloud Notes.
The closest thing that Nextcloud Notes seems to have are the categories. Having the tags and categories sync would be a great help in keeping notes organizes cross-platform.

**Comment by pbek** [comment]
Those categories are just sub-folders, you can enable them in QOwnNotes in the note folder settings.
