### ISSUE TITLE
SQLite DB file showing as note

### ISSUE THREAD

**Issue by zyll71** [pbek/QOwnNotes#2801]
#### Expected behaviour
SQLite DB file hidden / not considered a note

#### Actual behaviour
SQLite DB file shows as a note
![image](https://github.com/pbek/QOwnNotes/assets/59997333/7b3037d1-f966-4b0b-8fab-da91d77850c7)

#### Steps to reproduce
Open QOwnNotes - version 21.10.14 on OpenSuSe Tumbleweed with 

QOwnNotes - version 21.10.14
Operating System: openSUSE Tumbleweed 20230710
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.10
Kernel Version: 6.3.9-1-default (64-bit)
Graphics Platform: X11

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed Jul 12 12:36:30 2023`
**Version**: `21.10.14`
**Build date**: `Oct 27 2021`
**Build number**: `905`
**Platform**: `linux`
**Operating System**: `openSUSE Tumbleweed`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Self-build`
**Qt Version (build)**: `5.15.10`
**Qt Version (runtime)**: `5.15.10`
**Portable mode**: `no`
**Settings path / key**: `/home/zulliger/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/zulliger/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `2560x1440`
**Icon theme**: `breeze`
**Notes in current note folder**: `165`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://zyll.ch/nextcloud`
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `de_CH`
**Language codes**: `de_CH, de_DE, en_US, fr, fr_CH, fr_FR, it_IT, lo_LA`
**Language names**: `Schweizer Hochdeutsch (Schweiz), Deutsch (Deutschland), American English (United States), français, français suisse (Suisse), français (France), italiano (Italia), ລາວ (ລາວ)`
**Application dictionaries path**: `/home/zulliger/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-2`
**localPath**: `/home/zulliger/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/zulliger/Nextcloud/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://zyll.ch/nextcloud`
**username**: `zulliger`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/vimMode** (QString): `false`
**LastUpdateCheck** (QDateTime): `2023-07-12T12:15:07.885`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Hack,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Hack,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**MainWindow/tagTreeWidgetExpandState-1**: *empty*
**MessageBoxOverride/tag-removed-from-notes** (QString): `1024`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-0/NoteTabNameList**: *empty*
**NoteFolder-0/NoteTabStickinessList**: *empty*
**NoteFolder-0/NoteTabSubFolderPathDataList**: *empty*
**NoteFolder-1/NoteTabNameList** (QString): `Vereinsturnier`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `199`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePrinting** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TrashDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `785ac48e-2035-4190-b67b-c23b5357c661`
**cursorWidth** (QString): `1`
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**insertTimeFormat** (QString): `yyyy-MM-dd hh:mm`
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `23`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `false`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `false`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/zulliger/Nextcloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `093727c8-a0d4-4b15-be68-018485c5a6d8`
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2023-06-30T22.01.42, Note 2023-06-04T17.36.10, Note 2023-06-04T16.27.25, Note 2023-05-30T13.14.03, Note 2023-05-01T11.03.26, Note 2023-04-19T18.10.44, Note 2023-04-15T18.52.00, Note 2023-02-23T17.23.37, Note 2023-02-21T20.17.54, Note 2023-02-20T20.00.37, Note 2023-02-06T21.13.26, Note 2023-01-30T18.13.55, Note 2022-12-15T17.26.10, Note 2022-11-28T20.41.32, Note 2022-11-27T00.05.24, Note 2022-11-17T12.14.54, Note 2022-11-17T10.36.51, Note 2022-11-10T14.49.03, Note 2022-11-10T14.47.18, Note 2022-10-31T17.49.55, Note 2022-10-29T22.36.33, Note 2022-10-25T18.28.03, Note 2022-10-09T12.31.32, Note 2022-09-19T16.52.47, Note 2022-08-17T22.33.09, Note 2022-07-15T20.01.17, Note 2022-06-22T08.47.14, Note 2022-06-21T20.31.32, Note 2022-06-14T20.08.54, Note 2022-05-23T20.04.23, Note 2022-05-17T16.16.28, Note 2022-05-04T09.53.34, Note 2022-04-19T13.46.36, Note 2022-04-08T17.50.33, Note 2022-04-08T13.55.39, Note 2022-04-05T22.18.35, Note 2022-03-28T17.20.47, Note 2022-03-21T18.12.25, Note 2022-03-17T00.37.25, Note 2022-03-17T00.13.45, Note 2022-02-02T13.47.38, Note 2022-01-24T14.00.41, Note 2022-01-14T22.19.13, Note 2022-01-11T21.48.27, Note 2022-01-07T03.13.27, Note 2022-01-04T03.13.57, Note 2021-12-16T13.56.11, Note 2021-12-06T22.40.57, Note 2021-11-09T17.10.15, Note 2021-11-08T18.32.08, Note 2021-08-24T23.51.28, Note 2021-07-23T00.35.17, Note 2021-07-18T22.46.48, Note 2021-07-08T14.39.10, Note 2021-06-22T17.29.58, Note 2021-05-26T00.35.05, Note 2021-04-28T00.57.37, Note 2021-04-21T11.54.52, Note 2021-03-29T17.36.11, Note 2021-03-10T21.07.19, Note 2021-03-01T00.59.18, Note 2021-02-09T00.09.20, Note 2021-02-06T14.05.43, Note 2021-02-03T17.55.03, Note 2021-01-27T02.17.57, Note 2021-01-26T22.52.21, Note 2021-01-11T19.31.19, Note 2020-11-28T15.06.34, Note 2020-11-12T18.13.04, Note 2020-11-07T09.48.59, Note 2020-10-30T16.47.53, Note 2020-09-27T13.36.22, Note 2020-09-01T20.51.57, Note 2020-04-01T22.09.52, Note 2020-03-29T18.34.26, Note 2020-03-17T11.44.41, Note 2020-02-04T22.11.00, Note 2020-01-29T21.00.33, Note 2020-01-27T21.24.00, Note 2020-01-20T14.12.00, Note 2020-01-15T23.40.42, Note 2018-10-23T21.25.20, UpSpin Daten, Note 2018-05-16T12.13.26, Note 2018-05-08T09.47.07, Note 2018-05-07T14.26.03, JTBD Bestehender Job, Note 2018-04-24T08.57.35, Note 2018-04-10T16.07.41, Note 2018-03-16T10.08.58, Note 2018-02-27T09.06.36, Note 2018-02-26T10.46.19, Note 2018-02-26T10.45.52, Note 2018-02-23T15.24.23, Note 2018-02-19T14.26.52, Note 2018-02-19T14.23.53, Note 2018-02-19T10.09.52, Note 2018-02-19T09.54.14, Note 2018-01-13T09.47.42`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `de_CH`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**trashSplitterSizes** (QByteArray): `<binary data>`
**useUNIXNewline** (QString): `false`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-093727c8-a0d4-4b15-be68-018485c5a6d8/name** (QString): `minimal`
**workspace-093727c8-a0d4-4b15-be68-018485c5a6d8/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-093727c8-a0d4-4b15-be68-018485c5a6d8/windowState** (QByteArray): `<binary data>`
**workspace-785ac48e-2035-4190-b67b-c23b5357c661/name** (QString): `full`
**workspace-785ac48e-2035-4190-b67b-c23b5357c661/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-785ac48e-2035-4190-b67b-c23b5357c661/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `785ac48e-2035-4190-b67b-c23b5357c661, 093727c8-a0d4-4b15-be68-018485c5a6d8`

## System environment

**HOME**: `/home/zulliger`
**LANG**: `en_CH.UTF-8`
**LOGNAME**: `zulliger`
**PATH**: `/home/zulliger/.local/bin:/home/zulliger/bin:/usr/local/bin:/usr/bin:/bin:/snap/bin:/home/zulliger/.local/bin/.`
**SHELL**: `/bin/bash`
**SYSTEMD_EXEC_PID**: `2093`
**USER**: `zulliger`
**XDG_DATA_DIRS**: `/home/zulliger/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_CONFIG_DIRS**: `/home/zulliger/.config/kdedefaults:/etc/xdg:/usr/local/etc/xdg:/usr/etc/xdg`
**AUDIODRIVER**: `pulseaudio`
**CONFIG_SITE**: `/usr/share/site/x86_64-pc-linux-gnu`
**CPU**: `x86_64`
**CSHEDIT**: `emacs`
**CVS_RSH**: `ssh`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**DEBUGINFOD_URLS**: `https://debuginfod.opensuse.org/`
**DESKTOP_SESSION**: `plasma5`
**DISPLAY**: `:0`
**FROM_HEADER**: *empty*
**GPG_TTY**: `not a tty`
**GTK2_RC_FILES**: `/etc/gtk-2.0/gtkrc:/home/zulliger/.gtkrc-2.0:/home/zulliger/.config/gtkrc-2.0`
**GTK_IM_MODULE**: `ibus`
**GTK_MODULES**: `canberra-gtk-module`
**GTK_RC_FILES**: `/etc/gtk/gtkrc:/home/zulliger/.gtkrc:/home/zulliger/.config/gtkrc`
**G_BROKEN_FILENAMES**: `1`
**G_FILENAME_ENCODING**: `@locale,UTF-8,ISO-8859-15,CP1252`
**HISTSIZE**: `1000`
**HOST**: `Tulkas`
**HOSTNAME**: `Tulkas`
**HOSTTYPE**: `x86_64`
**INPUT_METHOD**: `ibus`
**JAVA_BINDIR**: `/usr/lib64/jvm/java/bin`
**JAVA_HOME**: `/usr/lib64/jvm/java`
**JAVA_ROOT**: `/usr/lib64/jvm/java`
**JDK_HOME**: `/usr/lib64/jvm/java`
**JRE_HOME**: `/usr/lib64/jvm/java`
**KDE_APPLICATIONS_AS_SCOPE**: `1`
**KDE_FULL_SESSION**: `true`
**KDE_SESSION_UID**: `1000`
**KDE_SESSION_VERSION**: `5`
**LANGUAGE**: `en_US`
**LC_TIME**: `C`
**LESS**: `-M -I -R`
**LESSCLOSE**: `lessclose.sh %s %s`
**LESSKEY**: `/usr/etc/lesskey.bin`
**LESSOPEN**: `lessopen.sh %s`
**LESS_ADVANCED_PREPROCESSOR**: `no`
**MACHTYPE**: `x86_64-suse-linux`
**MAIL**: `/var/mail/zulliger`
**MANPATH**: `/usr/local/man:/usr/share/man`
**MANPATHISSET**: `yes`
**MINICOM**: `-c on`
**MORE**: `-sl`
**OSTYPE**: `linux`
**PAGER**: `less`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**PROFILEREAD**: `true`
**PWD**: `/home/zulliger`
**PYTHONSTARTUP**: `/etc/pythonstart`
**QEMU_AUDIO_DRV**: `pa`
**QT4_IM_MODULE**: `xim`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**QT_IM_MODULE**: `ibus`
**QT_IM_SWITCHER**: `imsw-multi`
**QT_SCREEN_SCALE_FACTORS**: `DVI-D-1=1.5;HDMI-1=1.5;HDMI-2=1.5;DP-1=1.5;DP-2=1.5;`
**SDK_HOME**: `/usr/lib64/jvm/java`
**SESSION_MANAGER**: `local/Tulkas:@/tmp/.ICE-unix/2068,unix/Tulkas:/tmp/.ICE-unix/2068`
**SSH_AGENT_PID**: `1991`
**SSH_ASKPASS**: `/usr/libexec/ssh/ssh-askpass`
**SSH_AUTH_SOCK**: `/tmp/ssh-XXXXXXbE9QSz/agent.1910`
**TERM**: `xterm`
**VENDOR**: `suse`
**WINDOWMANAGER**: `/usr/bin/startplasma-x11`
**XAUTHLOCALHOSTNAME**: `Tulkas`
**XAUTHORITY**: `/tmp/xauth_WDDPWH`
**XCURSOR_SIZE**: `24`
**XCURSOR_THEME**: `breeze_cursors`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_SEAT**: `seat0`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_DESKTOP**: `KDE`
**XDG_SESSION_ID**: `3`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**XDG_SESSION_TYPE**: `x11`
**XDG_VTNR**: `2`
**XKEYSYMDB**: `/usr/X11R6/lib/X11/XKeysymDB`
**XMODIFIERS**: `@im=ibus`
**XNLSPATH**: `/usr/share/X11/nls`
**XSESSION_IS_UP**: `yes`
**MANAGERPID**: `1890`
**INVOCATION_ID**: `f0c734ce6f594179bfa858792a0ca86f`
**JOURNAL_STREAM**: `8:14277`

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
I've never seen that before.
Can you please hover with your mouse over the `notes` item in your note list to show the filename? Or right-click and copy the full path of the file...
