### ISSUE TITLE
[BUG] Ordered List number should be updated if a list item is removed from the middle of the list

### ISSUE THREAD

**Issue by vinaykharayat** [pbek/QOwnNotes#2803]
#### Expected behaviour
Ordered List number should be updated if a list item is removed from the middle of the list

#### Actual behaviour
The ordered List doesn't update numbers.
For example
From the list with item 1,2,3,4, I removed item number 3. 
The list should be 1.2.3 but it will stay at 1,2,4

#### Steps to reproduce

Create a ordered list.
1. List item 1
2. List item 2
3. List item 3
4. List item 4
Remove any item from the middle let's say I removed number 3.
The list should be 1.2.3 but it will stay at 1,2,4

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
It would be very devastating if QOwnNotes would alter your note while you are typing, trying to interpret what you did, destroying your note in the process...
If you want to attempt to reorder the Markdown of ordered lists, there is a script you can try: https://github.com/qownnotes/scripts/tree/master/fix-list-numbers (you'll also find it in the script repository).

**Comment by maninthemiddle01** [comment]
Thank you for the script recommendation, and I understand the caution against automatically altering note content. However, the process of manually updating list numbers, particularly in long lists, can be quite laborious and prone to errors. Additionally, when inserting a new item into the middle of an ordered list, the subsequent numbers do not automatically adjust to reflect the change, which can lead to inaccuracies in the list order.

Markdown is designed to streamline the note-taking process, and having to manually renumber lists seems counterintuitive to this goal. Automating the reordering of list numbers would enhance productivity and maintain the integrity of the ordered list structure.

Additionally, most modern text editors and note-taking apps handle the automatic renumbering of lists, so users may expect this behavior as a standard feature. Implementing this could also improve the experience for users migrating from other platforms, making QOwnNotes more user-friendly and competitive.

To mitigate concerns about altering text, perhaps this functionality could be introduced as an optional feature that users can enable or disable according to their preference. This way, those who value the automatic update of list numbers can benefit from it, while others who prefer full control over their text can continue as is.

I believe incorporating such a feature, with careful consideration of user control and preference settings, could offer a balanced solution that addresses both ease of use and content integrity concerns.

**Comment by pbek** [comment]
No, I'm still of the opinion that this will do a lot of harm. It wouldn't even be easy to not do that inside code blocks or just pasted text that isn't supposed to be markdown or simply during typing...
Please use a script and press a shortcut.
But if you are daring enough to want to do it automatically, you can always go crazy with https://www.qownnotes.org/scripting/hooks.html#onnotestored and execute a mechanism of your choosing every time the note gets saved. You can also contribute such a script to the script repository if you want.
