### ISSUE TITLE
freshcode.club page is showing obsolete version of QOwnNotes

### ISSUE THREAD

**Issue by luzpaz** [pbek/QOwnNotes#2806]
[![freshcode.club entry](https://repology.org/badge/version-for-repo/freshcode/qownnotes.svg)](https://repology.org/project/qownnotes/versions)

http://freshcode.club/projects/qownnotes

The entry has a lock: 

![Screenshot_20230727_104344](https://github.com/pbek/QOwnNotes/assets/4140247/e0e778b3-9527-459f-8a0f-8638790a6b4e)

Is it possible to unlock in order to bring it up to date ?

**Comment by pbek** [comment]
I found in my notes how I did log in, but I get the same error message as you on http://freshcode.club/submit/qownnotes.

**Comment by luzpaz** [comment]
There are intentionally no user accounts on freshcode.club, but this prerequisite also helps eschew spam submissions. | Or alternatively a per-project password.
-- | --

> Logins may fail if you specified a raw password
instead of an hash for the `lock` field. Don't worry, such plain text
passwords will be reencrypted twice per day. So please just try later.
-- If your login using an OpenID fails, please take care to add or
remove the trailing `/` slash. Matching is rather strict and doesn't
check for IRL equivalence at the moment. -- If everything else fails,
please just send a mail to info@…

----

Shall we send an email to info@freshcode.club ?

**Comment by pbek** [comment]
I just flagged it for moderation with our issue.

**Comment by luzpaz** [comment]
bump

**Comment by pbek** [comment]
I never got any answer back

**Comment by luzpaz** [comment]
bummer
