### ISSUE TITLE
[FEATURE] Custom main accent

### ISSUE THREAD

**Issue by chromer030** [pbek/QOwnNotes#2807]
#### Is your feature request related to a problem? Please describe.
No.

#### Describe the solution you'd like
Option to set a custom accent instead of just orange color.

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Are we talking about those colors?

![image](https://github.com/pbek/QOwnNotes/assets/1798101/5c75c665-d57f-41b0-8693-3458a515d595)

You can change all of them...

**Comment by chromer030** [comment]
Thanks for your response, the UI accent color for all menus and panels are changeable from this setting ?

**Comment by pbek** [comment]
For that best search for `Custom user interface styling` in the script repository.

**Comment by chromer030** [comment]
OK then, Thanks very much for this useful software.
feel free to close the issue.

**Comment by pbek** [comment]
Great, thank you. 😁

**Comment by pbek** [comment]
If you have created a script for changing those colors, feel free to share it on https://github.com/qownnotes/scripts!
