### ISSUE TITLE
One column view: Search bar on top, notes list and detail below

### ISSUE THREAD

**Issue by minthemiddle** [pbek/QOwnNotes#281]
One of the few things were [NVAlt](http://brettterpstra.com/projects/nvalt/) still has an advantage over `QOwnNotes` is when you place it aside another program and thus have a non-fullsize view. Say you are reading a PDF on the left side of your screen and are trying to make notes on the other half in markdown.

`NVAlt` has a 1-column layout and puts the search bar on top, notes list below and the text editor on the bottom. This way you get a full width text editor. `QOwnNotes` still has a two-column layout which means for me that often notes' titles are cut off because I need to enlarge the editor window on the right and still it feels so much smaller than on `NVAlt`. Yes, you have less notes in your list, but I guess that most are like me and use the search bar extensively and barely look up notes in the list.

How about an option or view `1-column` or `minimal` view such as `NVAlt` has by default?

Here is how the smaller window looks in `NVAlt`:
![201404041021_startup](https://cloud.githubusercontent.com/assets/1950766/17556744/c0b8324e-5f14-11e6-85e8-83647a56b969.png)

And here is `QOwnNotes`:

![qownnotes 16 08 0 2016-08-10 16 11 17](https://cloud.githubusercontent.com/assets/1950766/17556835/2fd3df02-5f15-11e6-8f70-1eb6b2c6d965.png)

**Comment by pbek** [comment]
You mean just the note list and the note edit on top of each other?

**Comment by minthemiddle** [comment]
Yes, and the search bar on top of everything. That basically would be it.

**Comment by pbek** [comment]
I guess that would come with some side effects. If the users don't mind them, I'll see what I can do...

**Comment by minthemiddle** [comment]
If it's just another view option and people are aware of the side effects (one could list them here and in the logs), I think everyone should be okay. It'd be a question of preference then only.

**Comment by pbek** [comment]
## 16.08.6
- there now is a **one column minimal mode**, like NVAlt has
    - you can activate it in the window menu
    - it turns off the navigation pane, the tag pane and the preview 
      pane and puts the edit pane beyond the note list
    - the setting will be remembered when you exit the app
    - entering the distraction free mode turns the one column mode off

There now is a new release, could you please test it and report if the new features work for you?

**Comment by minthemiddle** [comment]
It works as expected in OSX, have not yet tested it on Windows and Linux.

**Comment by pbek** [comment]
Great, tell me when you have. ;)

**Comment by pbek** [comment]
@minthemiddle, any news on that?

**Comment by minthemiddle** [comment]
I could just test `16.08.9` on Windows 10 and could not spot any difficulties. Works as expected.

**Comment by pbek** [comment]
great, thank you!
