### ISSUE TITLE
[FEATURE] Add Debian 12 repo

### ISSUE THREAD

**Issue by sbstn87** [pbek/QOwnNotes#2811]
Hi,

since Debian 12 has been released some time ago, could you perhaps add Debian 12 repo to the OBS?

**Comment by pbek** [comment]
- there now is a software repository for **Debian Linux 12.0**
  - please visit the [Debian installation page](https://www.qownnotes.org/installation#Debian)
    for instructions

**Comment by sbstn87** [comment]
I have added the repo and successfully installed QOwnNotes on Debian 12 - it starts without any issues. Thank you.

**Comment by pbek** [comment]
Great, thank you for testing!
