### ISSUE TITLE
[BUG] Undo history is lost when switching between notes

### ISSUE THREAD

**Issue by kyeastmood** [pbek/QOwnNotes#2814]
#### Expected behaviour

Editing history (undo/redo) should still be available after switching to another note and then going back to the original note. This a normal behavior of most editors supporting opening multiple files.

There should also be undo/redo actions in the Edit menu.

#### Actual behaviour

Editing history is lost after switching notes.

Additionally, there are no undo/redo actions in the application's Edit menu.

#### Steps to reproduce

Edit a note, open another note and then go back to the previous note. You won't be able to undo previous opearions.

**Comment by pbek** [comment]
Im sorry, that's not supported by the framework. As soon as a new text is set in Qt's qplaintextedit the undo history is lost.

**Comment by kyeastmood** [comment]
Hi, thanks for your reply. It seems it's indeed not supported by QPlainTextEdit nor QTextDocument. It could be probably implemented by using [Qt Undo Framework](https://doc.qt.io/qt-5/qundo.html), subclassing QPlainTextEdit and handle low level events by reimplementing some [protected functions](https://doc.qt.io/qt-5/qplaintextedit.html#reimplemented-protected-functions). But I understand it would be too much for now.
