### ISSUE TITLE
[BUG] It's not possible to dock a floating panel back to the main window

### ISSUE THREAD

**Issue by kyeastmood** [pbek/QOwnNotes#2815]
#### Expected behaviour

It should be possible to dock floating panels (shown in separate windows) back to the main window.

#### Actual behaviour

When a panel is detached from the main window and is displayed as a separate window it seems not to be possible to dock it back to the main window.

#### Steps to reproduce

Undock a panel from the main window and try to dock it back.

**Comment by pbek** [comment]
I can't reproduce that. I simply let it snap in below another panel...

**Comment by pbek** [comment]
What layout do you have? Do you have a video of the process?

**Comment by kyeastmood** [comment]
I noticed it happens only in a Wayland session. With X11 it works, although it sometimes crashes.

**Comment by kyeastmood** [comment]
My system is Debian stable with KDE/Plasma/Qt5.

**Comment by pbek** [comment]
I only have X11 everywhere and never had any issues under KDE Plasma Qt5 and Qt6 (KDE Neon / NixOS).

**Comment by robert7k** [comment]
I can reproduce this on Wayland with the most recent version of QOwnNotes.

Workaround to get the panels docked in the main menu: switch to an X11 session, dock the panels, go back to wayland.
