### ISSUE TITLE
[EDITOR SCHEMA] Atom Mellow Dark

### ISSUE THREAD

**Issue by davuses** [pbek/QOwnNotes#2817]
#### Schema name

Atom Mellow Dark

#### Screenshot

<img width="705" alt="image" src="https://github.com/pbek/QOwnNotes/assets/54793121/d3b7b5cd-b6b8-4555-b8e3-57b504a38cfc">

**Preview mode:**

<img width="821" alt="image" src="https://github.com/pbek/QOwnNotes/assets/54793121/cd13b8ea-2a49-4eae-9d00-5c59eece7522">

#### Schema file

[Atom Mellow Dark.zip](https://github.com/pbek/QOwnNotes/files/12410176/Atom.Mellow.Dark.zip)

**Comment by pbek** [comment]
Beautiful! Thank you very much!

**Comment by davuses** [comment]
> Beautiful! Thank you very much!

You're welcome! I hope people will like it as well

**Comment by pbek** [comment]
I'm sure! 😁

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by davuses** [comment]
> There now is a new release, could you please test it and report if it works for you?

It works perfectly, thank you!

**Comment by pbek** [comment]
Great, thank you for testing!
