### ISSUE TITLE
[I] Tag counter does not add counter of subtags

### ISSUE THREAD

**Issue by Adspectus** [pbek/QOwnNotes#2819]
Please paste the text from the issue assistant here. It should be already in your clipboard.#### Expected behaviour

When using subtags, notes that contain a tag and any subtag, are counted at the tag level.

#### Actual behaviour

The tag counter does not reflect the sum of subtags.

#### Steps to reproduce

Create 2 notes, one note with tags "a" and "b", another with tags "a" and "c". "b" and "c" are subtags of tag "a". All counters show count 1, but tag "a" should show count 2.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[11:26:52] [debug] updatePanelMenu - 'updatePanelMenu'
[11:26:52] [debug] Reply from "/remote.php/dav/calendars/uwe/nochntest/"
[11:26:52] [debug] Reply from ownCloud calendar todo list page
[11:26:52] [debug] Reply from "/remote.php/dav/calendars/uwe/nochntest/0AC4072D-71FB-40DE-BC67-ED74DCEC768E.ics"
[11:26:52] [debug] Reply from ownCloud calendar item ics page
[11:26:52] [debug] Reply from "/remote.php/dav/calendars/uwe/nochntest/0973F501-72C3-4FD6-B99E-A68BD07FB859.ics"
[11:26:52] [debug] Reply from ownCloud calendar item ics page
[11:26:52] [debug] Reply from "/remote.php/dav/calendars/uwe/nochntest/BEB811D1-FFDF-4820-99D7-08C6AB6F76BD.ics"
[11:26:52] [debug] Reply from ownCloud calendar item ics page
[11:26:52] [debug] Reply from "/remote.php/dav/calendars/uwe/nochntest/9766E2F6-7D72-4C2B-9B37-952CAE2962E8.ics"
[11:26:52] [debug] Reply from ownCloud calendar item ics page
[11:26:52] [debug] Reply from "/remote.php/dav/calendars/uwe/nochntest/EBB3B497-0C26-4DA9-A2B4-62041D462995.ics"
[11:26:52] [debug] Reply from ownCloud calendar item ics page
[11:26:52] [debug] Reply from "/remote.php/dav/calendars/uwe/nochntest/6F5A46F7-C4E9-44FA-9717-2492B7E5B00D.ics"
[11:26:52] [debug] Reply from ownCloud calendar item ics page
[11:26:52] [debug] Reply from "/remote.php/dav/calendars/uwe/nochntest/624609F1-0D7B-4966-94C1-EFD4DC0BF2D2.ics"
[11:26:52] [debug] Reply from ownCloud calendar item ics page
[11:26:59] [debug] getBoards - 'url': QUrl("https://cloud.uwe-gehring.de/index.php/apps/deck/api/v1.1/boards?details=true")
[11:27:00] [debug] cloudConnection: CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://cloud.uwe-gehring.de" <username>"uwe" <accountId>"uwe" <priority>1
[11:27:00] [debug] Reply from ""
[11:27:00] [debug] Reply from main server url
[11:27:00] [debug] Reply from "/ocs/v1.php/cloud/capabilities"
[11:27:00] [debug] Reply from capabilities page
[11:27:00] [debug] Reply from "/ocs/v1.php"
[11:27:00] [debug] Reply from ownCloud test page
[11:27:00] [debug] Reply from "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[11:27:00] [debug] Reply from app info
[11:27:02] [status] Keine Skript-Aktualisierungen gefunden
[11:27:18] [debug] getBoards - 'url': QUrl("https://cloud.uwe-gehring.de/index.php/apps/deck/api/v1.1/boards?details=true")
[11:27:18] [debug] cloudConnection: CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://cloud.uwe-gehring.de" <username>"uwe" <accountId>"uwe" <priority>1
[11:27:19] [debug] Reply from ""
[11:27:19] [debug] Reply from main server url
[11:27:19] [debug] Reply from "/ocs/v1.php/cloud/capabilities"
[11:27:19] [debug] Reply from capabilities page
[11:27:19] [debug] Reply from "/index.php/apps/qownnotesapi/api/v1/note/app_info"
[11:27:19] [debug] Reply from app info
[11:27:19] [debug] Reply from "/ocs/v1.php"
[11:27:19] [debug] Reply from ownCloud test page
[11:27:20] [debug] getDiskDatabasePath - 'databaseFileName': "/home/uwe/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite"
[11:27:20] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "de_CH_frami"
[11:27:20] [debug] Loading dictionary for "de_CH_frami" from "/usr/share/hunspell"
[11:27:20] [debug] Created 0x55e0a741f450
[11:27:20] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_ZA"
[11:27:20] [debug] Loading dictionary for "en_ZA" from "/usr/share/hunspell"
[11:27:20] [debug] Created 0x55e0a9521ab0
[11:27:20] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_CA"
[11:27:20] [debug] Loading dictionary for "en_CA" from "/usr/share/hunspell"
[11:27:20] [debug] Created 0x55e0a9a55470
[11:27:20] [debug] SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_AU"
[11:27:20] [debug] Loading dictionary for "en_AU" from "/usr/share/hunspell"
[11:27:20] [debug] Created 0x55e0a9f1a210
[11:27:41] [debug] Set proxy configuration to use NO proxy
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fr. Aug. 25 11:32:03 2023`
**Version**: `23.8.0`
**Build date**: `Aug  4 2023`
**Build number**: `1048`
**Platform**: `linux`
**Operating System**: `Ubuntu 20.04.6 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.12.8`
**Qt Version (runtime)**: `5.12.8`
**Portable mode**: `no`
**Settings path / key**: `/home/uwe/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/uwe/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Primary screen resolution**: `3440x1440`
**Icon theme**: `Yaru`
**Notes in current note folder**: `4`
**Calendar items**: `39`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://cloud.uwe-gehring.de`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `26.0.5.1`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `de_AT, de_AT_frami, de_CH, de_CH_frami, de_DE, de_DE_frami, en_AU, en_CA, en_GB, en_US, en_ZA`
**Language names**: `Österreichisches Deutsch (Österreich), Österreichisches Deutsch (Österreich), Schweizer Hochdeutsch (Schweiz), Schweizer Hochdeutsch (Schweiz), Deutsch (Deutschland), Deutsch (Deutschland), Australian English (Australia), Canadian English (Canada), British English (United Kingdom), American English (United States), English (South Africa)`
**Application dictionaries path**: `/home/uwe/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Standard`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/uwe/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/uwe/Notes/notes.sqlite`

### Cloud connection `Standard`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://cloud.uwe-gehring.de`
**username**: `uwe`
**accountId**: `uwe`
**Nextcloud Deck boardId**: `0`
**Nextcloud Deck stackId**: `0`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**CloudConnection-1/nextcloudDeckEnabled** (QString): `true`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `true`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (bool): `false`
**Editor/showLineNumbers** (bool): `false`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2023-08-25T11:26:51.086`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.refreshDebounceTime** (int): `600`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MainWindow/tagTreeWidgetExpandState-1** (QStringList): `1`
**MessageBoxOverride/calendar-cache-emptied** (QString): `1024`
**MessageBoxOverride/remove-todo-items** (QString): `16384`
**MessageBoxOverride/share-sync-information** (QString): `1024`
**NoteFolder-1/NoteTabNameList** (QString): `Einzubringende Themen`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QString): `Sportschifffahrt`
**NoteFolder-1/allowDifferentNoteFileName** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 9 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `8`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `0`
**TodoDialog/showDueTodayItemsOnly** (QString): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Sportschifffahrt`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**autoReadOnlyMode** (bool): `false`
**autoReadOnlyModeTimeout** (int): `30`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**enableWebAppSupport** (bool): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): `dddd, dd. MMMM yyyy HH:mm:ss t`
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (int): `17`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `false`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelAutoSelect** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `true`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/uwe/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/ignoreNonTodoCalendars** (QString): `true`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): `https://caldav.fastmail.com/dav/calendars/user/uwe@imap.cc/`
**ownCloud/todoCalendarCalDAVUsername** (QString): `uwe@imap.cc`
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unbekannter Fehler`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `26.0.5.1`
**restoreCursorPosition** (bool): `true`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2023-08-25T10.52.22, Note 2023-08-21T17.55.23`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**startInReadOnlyMode** (bool): `false`
**systemIconTheme** (bool): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (bool): `true`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `Hauptsymbolleiste`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `Formatierungs-Werkzeugleiste`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `Einfügen-Werkzeugleiste`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `Verschlüsselung-Werkzeugleiste`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `Fenster-Werkzeugleiste`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `Beenden - Symbolleiste`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Vollständig`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`
**USER**: `uwe`
**SSH_AGENT_PID**: `8807`
**XDG_SESSION_TYPE**: `x11`
**SHLVL**: `0`
**HOME**: `/home/uwe`
**DESKTOP_SESSION**: `ubuntu`
**GIO_LAUNCHED_DESKTOP_FILE**: `/usr/share/applications/PBE.QOwnNotes.desktop`
**GTK_MODULES**: `gail:atk-bridge`
**GNOME_SHELL_SESSION_MODE**: `ubuntu`
**MANAGERPID**: `8626`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1001/bus`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `55799`
**IM_CONFIG_PHASE**: `1`
**MANDATORY_PATH**: `/usr/share/gconf/ubuntu.mandatory.path`
**LOGNAME**: `uwe`
**_**: `/usr/bin/dbus-update-activation-environment`
**JOURNAL_STREAM**: `8:59774`
**DEFAULTS_PATH**: `/usr/share/gconf/ubuntu.default.path`
**XDG_SESSION_CLASS**: `user`
**USERNAME**: `uwe`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**WINDOWPATH**: `2`
**PATH**: `/home/uwe/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/texlive/2023/bin/x86_64-linux:/snap/bin`
**SESSION_MANAGER**: `local/Caboto:@/tmp/.ICE-unix/8844,unix/Caboto:/tmp/.ICE-unix/8844`
**INVOCATION_ID**: `16bbee11da1d44b8b5e21f4ab9494e03`
**XDG_RUNTIME_DIR**: `/run/user/1001`
**XDG_MENU_PREFIX**: `gnome-`
**DISPLAY**: `:0`
**LANG**: `de_DE.UTF-8`
**XDG_CURRENT_DESKTOP**: `ubuntu:GNOME`
**DESKTOP_MODE**: `1`
**XAUTHORITY**: `/run/user/1001/gdm/Xauthority`
**XDG_SESSION_DESKTOP**: `ubuntu`
**XMODIFIERS**: `@im=ibus`
**SSH_AUTH_SOCK**: `/run/user/1001/keyring/ssh`
**SHELL**: `/bin/bash`
**HOST**: `caboto`
**QT_ACCESSIBILITY**: `1`
**GDMSESSION**: `ubuntu`
**GPG_AGENT_INFO**: `/run/user/1001/gnupg/S.gpg-agent:0:1`
**GJS_DEBUG_OUTPUT**: `stderr`
**QT_IM_MODULE**: `ibus`
**PWD**: `/home/uwe`
**XDG_DATA_DIRS**: `/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-ubuntu:/etc/xdg`
</details>

**Comment by pbek** [comment]
I am not in front of a computer, but there should be a setting for that.

**Comment by Adspectus** [comment]
Thanks for your prompt answer, but there is no setting for this - at least I could not find one.

**Comment by pbek** [comment]
There is a search bar in the settings dialog.

**Comment by Adspectus** [comment]
Yes, I know, and I can see some tag related settings, the closest one is to disable the counter completely.

**Comment by Adspectus** [comment]
![Screenshot_2023-08-25-19-58-16](https://github.com/pbek/QOwnNotes/assets/8707493/abd6fc30-7613-4465-9f41-0aaeb79178c3)

**Comment by pbek** [comment]
The cumulative numbers are shown if you use this:

![image](https://github.com/pbek/QOwnNotes/assets/1798101/c4a173d2-6534-4730-9769-b93441447c9e)

**Comment by Adspectus** [comment]
You might think I am an idiot, and maybe indeed I am, but thats what I have set at first. From the screenshot, it is not completely visible, but I have only two notes (except the default ones), one is tagged with "SCHo" and "Schulungen", the other with "SCHo" and "Vorstand". Hence, I would expect, that the counter on "SCHo" would be 2. Unfortunately, due to the bad UI the tags in the lower left corner are not completely visible. This screenshot is from Ubuntu 20, but I am also using it on a MacBook, where the same problem occurs and the tag panel in the lower left corner is even worse visible. And yes, I just updated the application on both computers to the most recent version.

![Screenshot_2023-08-26-12-06-35](https://github.com/pbek/QOwnNotes/assets/8707493/7516516e-8d8c-4959-89af-dc86bad5551e)

**Comment by Adspectus** [comment]
I did some further tests and have noted, that only the subtag which is added last to a tag increases the counter of the tag as well.

**Comment by pbek** [comment]
The feature of cumulative viewing of note in sub-tags was user-contributed... I'll have to look deeper in how the counts in the tag list are calculated in that mode.

**Comment by pbek** [comment]
Or maybe the counting was contributed, I can't even remember anymore 😁

**Comment by pbek** [comment]
Those features are involved: #137 and #1709

**Comment by pbek** [comment]
@Waqar144, are there any chances #1960 (with for example https://github.com/pbek/QOwnNotes/commit/b9bb160a6ec421f88793861c62d6db9d6330ab5e) had any influence on the note counting with the feature to also show the notes of sub-tags? I can't bisect those commits on NixOS anymore. 🙈

**Comment by pbek** [comment]
Yes, unfortunately, #1960 seems to have broken the counting if `taggingShowNotesRecursively` is turned on... 😬

**Comment by pbek** [comment]
## 23.9.0
- when all notes of a tag, including the notes of their child-tags are shown in the
  note list the numbers of notes per tag are now calculated correctly in the tag tree

**Comment by Adspectus** [comment]
I tested it and it works like expected both on Ubuntu and MacOS

**Comment by pbek** [comment]
Great, thank you for testing!
