### ISSUE TITLE
Cannot reset shortcut keys

### ISSUE THREAD

**Issue by piyo-gh** [pbek/QOwnNotes#282]
After assigning a new shortcut key, I cannot reset to default.
'Reset to default key' button doesnot work.

- Open settings -> shortcuts.
- Assign a new shortcut key and click 'ok'.
- Open settings -> shortcuts again.
- Click 'Reset to default key' button and click 'ok'.

Windows 10 Pro x64

**Comment by pbek** [comment]
Interesting, works under OS X and Linux. I will take a look at that, thank you for reporting!

**Comment by pbek** [comment]
Correction, it seems it didn't work anywhere. It's now fixed in 16.08.5, that was just released. Does it now work for you?

**Comment by pbek** [comment]
@piyo-gh, any news on that?
