### ISSUE TITLE
[BUG] Windows detects a Trojan horse virus in v23.8.2

### ISSUE THREAD

**Issue by obridgem** [pbek/QOwnNotes#2820]
#### Expected behaviour

I upgraded to v23.8.2 and expected the upgrade to go smoothly; the updater runs and then I can open QOwnNotes without issue.

#### Actual behaviour

I upgraded to v23.8.2 and expected then when I tried to open QOwnNotes, it was not on my computer.
Windows detected a Trojan horse virus on v23.8.2 and it removed the file from my computer.

![qownnotes v23 8 2 windows trojan horse](https://github.com/pbek/QOwnNotes/assets/46221361/da8321c7-720f-41ae-9125-6f5b908f8cf8)

#### Steps to reproduce

1. Download the v23.8.2 zip file: https://github.com/pbek/QOwnNotes/releases/download/v23.8.2/QOwnNotes.zip
2. Unzip the file on your computer.
3. Run the portable app version: QOwnNotesPortable.bat
4. Windows will detect the trojan horse and block the execution. Then, the file QOwnNotes.exe will be removed from the folder.

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Windows now and then get false positives. Did you try an actual virus scanner?

**Comment by obridgem** [comment]
I understand.
I didn't try an actual virus scanner because the file is already deleted from my computer by Windows as soon as I try to open it.
I have downloaded the previous version of QOwnNotes from GitHub and will skip this version.
Maybe there is nothing that you can do about it, but I just thought you might like to know that Windows is automatically blocking and deleting the QOwnNotes.exe file as soon as it's opened, since this might affect other people as well.

**Comment by BloomingAzaleas** [comment]
Confirm same Win Def Trojan detection.
Edition	Windows 10 Pro for Workstations
Version	22H2
Installed on	‎11/‎4/‎2020
OS build	19045.3393
Experience	Windows Feature Experience Pack 1000.19044.1000.0

**Comment by pbek** [comment]
After a few days Microsoft usually sorts their issue out

**Comment by bcutter** [comment]
> After a few days Microsoft usually sorts their issue out

...until then others (here, raising hands) run into this. Weird false positive.

![grafik](https://github.com/pbek/QOwnNotes/assets/13799156/aae62027-81a1-4152-b745-eae3f154faad)

![grafik](https://github.com/pbek/QOwnNotes/assets/13799156/4b1234ab-9e98-4d7e-a148-bf6bafddc340)

**Comment by nonplayer** [comment]
Happened again to me just now. This happens like every 4th or 5th time I update the software and it's getting somewhat frustrating. Every time I have to go into Defender, reverse the action, and then _once again_ restore all my shortcuts which Windows oh so helpfully decided to delete for me. This is the only of the four markdown editing apps that I use which has this problem.

I get that these are false positives, but given that it happens so often, there has to be something about the app that is triggering it. Is there not perhaps some way to get MS to recognize this as a legitimate app for good, and prevent these from ever happening again?

**Comment by pbek** [comment]
If anyone finds a way, please let me know. The binaries are all built here on GitHub.

**Comment by chessmango** [comment]
https://superuser.com/a/1417342 seems to detail almost the same setup - the `!ml` suffix implies it's machine learning-related, which appears to make things a little stickier.
Looks like: https://www.microsoft.com/en-us/wdsi/filesubmission - could someone seeing this issue report a false positive here? I don't have any Windows machines or I'd do so :sweat_smile:

**Comment by Monolith86** [comment]
after loading the Russian dictionary from the program menu, windows defender showed this
![Screenshot_1](https://github.com/pbek/QOwnNotes/assets/125505177/6dd22ed2-8740-48d3-a696-8c4c37d05516)
![Screenshot_2](https://github.com/pbek/QOwnNotes/assets/125505177/c1292c92-c354-45da-895b-a3618fec6e72)

**Comment by bcutter** [comment]
Jap, same for latest 23.9.1 release. So annoying.

![grafik](https://github.com/pbek/QOwnNotes/assets/13799156/624c940a-f627-4849-ba7b-8a31d16bd06e)

**Comment by pbek** [comment]
I just tried to update on a win10 box and had no issues.

**Comment by pbek** [comment]
Oh, and now the app is gone 😂 now I know why I don't use windows 😅

**Comment by pbek** [comment]
But it seems you can restore those files from quarantine

**Comment by bcutter** [comment]
> But it seems you can restore those files from quarantine

It's not a "you can". It's a "you must". Every time... -.-

**Comment by pbek** [comment]
I hope Microsoft gets their defender under control soon.

**Comment by BloomingAzaleas** [comment]
Version 23.10.0  passes several days of MS Defender scans. Likely resolved.

Regards.

**Comment by pbek** [comment]
Thank you for the feedback!

**Comment by bcutter** [comment]
Well... simply NO. Still bugging me, see:

![grafik](https://github.com/pbek/QOwnNotes/assets/13799156/6154d957-d740-4cfe-9c5a-499f432df5f7)

**Comment by pbek** [comment]
There is nothing to be done, beside nagging Microsoft about their heuristics...
