### ISSUE TITLE
[SUPPORT] Save linked images in subfolders?

### ISSUE THREAD

**Issue by greyfence** [pbek/QOwnNotes#2822]
I was very happy to stumble across QOwnNotes and am trying to make it work with my existing work method.

To that end: currently when I paste an image into a note the image is saved in a sub folder beneath the folder I'm creating the note in.  This allows all the content for certain types of notes to stay with the note itself.  

How can I replicate that in QOwnNotes?  I only see a common 'media' folder.  I'm certainly willing to learn scripting to make it work.

Thanks

**Comment by pbek** [comment]
Yes, if you paste an image, it is moved to the `media` folder at the root of your note folder.

You could put your images manually to a place you like and insert it directly via the `Insert image` action from the main menu. You can select that you don't want to copy the image from there...

Furthermore, you could try writing a script using https://www.qownnotes.org/scripting/methods-and-objects.html#accessing-the-clipboard when pasting something.

Or you could use https://www.qownnotes.org/scripting/hooks.html#insertmediahook to intercept when you are inserting media in general...

**Comment by greyfence** [comment]
Updating text and re-inserting it into the clipboard would work.  How about writing the image file to a specific folder after updating the link on the clipboard?  I see the ScriptingService::writeToFile() function but it specifically mentions saving text to a file.  Can this function also be used to write binary information (i.e. an image) as well?

**Comment by pbek** [comment]
That could work, best just try.
