### ISSUE TITLE
[SUPPORT] Save using same extension?

### ISSUE THREAD

**Issue by greyfence** [pbek/QOwnNotes#2823]
Is there a setting to have QOwnNotes save the note with the same extension as the original note?  I have text files with various extensions in my folders and would like them to keep their original extensions even after editing.

**Comment by pbek** [comment]
Just add the extension:

![image](https://github.com/pbek/QOwnNotes/assets/1798101/9a8dc125-b6b5-4bbd-875f-17d30c6a733c)
