### ISSUE TITLE
Please add support for mermaid diagramming tool [FEATURE] 

### ISSUE THREAD

**Issue by dlhpp** [pbek/QOwnNotes#2824]
#### Describe the solution you'd like
Please add support for mermaid diagramming tool

#### Describe alternatives you've considered
I'm currently using Dendron with the mermaid plugin and it works great.   Just google on "mermaid diagram" - it's a markdown based diagramming tool that can do erd's, sequence diagrams and more.  

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
There is a script for that in the script repository.
Or just get it from here: https://github.com/qownnotes/scripts/tree/master/mermaid
