### ISSUE TITLE
[BUG] Installed and used for 30 minutes and closed.  When I reopened the file qownnotes.exe was gone.  Windows says it's a virus.

### ISSUE THREAD

**Issue by dlhpp** [pbek/QOwnNotes#2825]
My problem is that I want to use this software at work.   

If there is even a hint that it might be a trojan or virus I won't be able to use it and might get in big trouble for downloading it.   Therefore I cannot use it at home either and have to stick with Dendron which is not quite as nice but at least I can use mermaid with Dendron.

**Comment by pbek** [comment]
Are you talking about #2820?
