### ISSUE TITLE
Set into Distraction Free Mode and cannot exit it (also need help with subfolders)[SUPPORT] 

### ISSUE THREAD

**Issue by Sacred-Sticks** [pbek/QOwnNotes#2827]
Basically, I just downloaded the program and started playing around and trying to figure it out. Couldn't find how to enable the subfolders panel but I did turn on  distraction free mode. Now it's stuck on and I don't know how to disable it. I tried closing and reopening the program, turning the computer off and on again, and even deleting and redownloading the program with no luck. All I have is a tiny window in the middle that shows the text, but I need full functionality.

I also need help with subfolders. I want to store all my notes in a "Notes" folder, but I want to categorize my notes within the program. I want to be able to create new folders in the program, and then create new markdown documents in those folders. I'm brand new to note taking software so I really don't know what I'm doing, sorry if these questions are really dumb.

**Comment by pbek** [comment]
> Couldn't find how to enable the subfolders panel but I did turn on distraction free mode.

Note folder settings

> Couldn't find how to enable the subfolders panel but I did turn on distraction free mode. 

- Same shortcut you used to activate it
- or `Escape` key
- or button on the bottom right

> but I want to categorize my notes within the program

if you don't want to use sub-folders (like I do) just use tags

Or just use sub-folders. or use sub-folders and tags together 😁
