### ISSUE TITLE
[Q] how to clone note to note

### ISSUE THREAD

**Issue by zeyadelkholyttt** [pbek/QOwnNotes#2829]
Please paste the text from the issue assistant here. It should be already in your clipboard.#### General question

i use qownnote for note taking so i have a folder for days task are there a way to clone my daily to do list to the week task or check if all item in my daily to do in my week list 
i just need something clone my items in daily list to one file and edit it if something changed in the daily list
for more explanation i need something like syncthing or links in linux (i didn't know if there are something in the official app or in the scripts but i need it)

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `الخميس سبتمبر 7 19:10:04 2023`
**Version**: `23.6.5`
**Build date**: `Jun 22 2023`
**Build number**: `1042`
**Platform**: `linux`
**Operating System**: `Void Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `TuxFamily`
**Qt Version (build)**: `5.15.7`
**Qt Version (runtime)**: `5.15.7`
**Portable mode**: `no`
**Settings path / key**: `/home/zod/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/zod/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`, `/usr/bin/QOwnNotes`, `/usr/bin/QOwnNotes`, `--allow-multiple-instances`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1366x768`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `4`
**Calendar items**: `0`
**Enabled scripts**: `4`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `en_US`
**Language codes**: `ar, en_US`
**Language names**: `العربية, American English (United States)`
**Application dictionaries path**: `/home/zod/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/zod/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: `101 by days`
**database file**: `/home/zod/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

### Script `Toggle checkbox`

**id**: `1`
**path**: `/home/zod/.local/share/PBE/QOwnNotes/scripts/toggle-checkbox/toggle-checkbox.qml`
**variablesJson**: 
```
{
    "checkboxCharacterUppercase": true,
    "multipleLinesMethod": "cycleIndividually"
}
```
**identifier**: `toggle-checkbox`
**version**: `1.3.0`
**minAppVersion**: `19.3.2`

### Script `Order checkboxes`

**id**: `2`
**path**: `/home/zod/.local/share/PBE/QOwnNotes/scripts/order-checkboxes/order-checkboxes.qml`
**variablesJson**: *empty*
**identifier**: `order-checkboxes`
**version**: `1.1.1`
**minAppVersion**: `19.3.2`

### Script `Custom note preview styling`

**id**: `3`
**path**: `/home/zod/.local/share/PBE/QOwnNotes/scripts/preview-styling/preview-styling.qml`
**variablesJson**: 
```
{
    "customStylesheet": "h2 {margin-left: 20px;}\nh3 {margin-left: 40px;}\nh4 {margin-left: 60px;}\nul:first-child  li:before { content:\"\\2713\\0020\"; }  /* OR */\nul:nth-child(2) li:before { content:\"\\2714\\0020\"; }  /* OR */\nul:last-child   li:before { content:\"\\2611\\0020\"; }\nul { list-style-type: none; }"
}
```
**identifier**: `preview-styling`
**version**: `0.0.5`
**minAppVersion**: `20.6.0`

### Script `Latex Math`

**id**: `4`
**path**: `/home/zod/.local/share/PBE/QOwnNotes/scripts/latex-math/latex-math.qml`
**variablesJson**: 
```
{
    "customPreamble": "\\newcommand{\\mycmd}[1]{\\bf \\underline{#1}}",
    "executable": "/usr/bin/klatexformula",
    "formulaBgColor": "-",
    "formulaColor": "#000000",
    "formulaPrefix": "\\bf ",
    "settingDPI": 600,
    "settingImageSize": 16,
    "usepackages": "amsmath,amssymb,amsfonts"
}
```
**identifier**: `latex-math`
**version**: `0.0.6`
**minAppVersion**: `20.8.0`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `true`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2023-09-07T18:25:33.628`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Hack,10,-1,0,75,0,0,0,0,0,Bold`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Hack,10,-1,7,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (QString): `600`
**MainWindow/noteTextView.rtl** (QString): `true`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**NoteFolder-1/NoteTabNameList** (QString): `Note 2023-09-07T11.56.36`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QString): 
```
100 TODO's
101 by days
```
**NoteHistory-1** (QVariantList): `<variant list with 9 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `8`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-customAction_toggleCheckbox** (QString): `Alt+Z`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `true`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**interfaceStyle** (QString): `kvantum`
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `26`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/zod/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/ignoreNonTodoCalendars** (QString): `true`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `1`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2023-09-07T11.56.36, Note 2023-09-07T10.57.01, Note 2023-09-07T10.55.48, Note 2023-09-04T14.47.28`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `en_US`
**startInReadOnlyMode** (QString): `false`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**KDE_APPLICATIONS_AS_SCOPE**: `1`
**SHELL**: `/bin/zsh`
**DBUS_STARTER_ADDRESS**: `unix:path=/tmp/dbus-6VStUT7mx4,guid=dd91dda2eb97132821c20f7d64f8393a`
**XCURSOR_SIZE**: `24`
**NIX_SSL_CERT_FILE**: `/etc/ssl/certs/ca-certificates.crt`
**XDG_CURRENT_DESKTOP**: `KDE`
**DISPLAY**: `:0`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**DESKTOP_SESSION**: `plasma`
**SESSION_MANAGER**: `local/magma:@/tmp/.ICE-unix/1519,unix/magma:/tmp/.ICE-unix/1519`
**GTK2_RC_FILES**: `/etc/gtk-2.0/gtkrc:/home/zod/.gtkrc-2.0:/home/zod/.config/gtkrc-2.0`
**KDE_SESSION_UID**: `1000`
**MOTD_SHOWN**: `pam`
**LC_TIME**: `ar_EG.UTF-8`
**PATH**: `/home/zod/.nix-profile/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin`
**OLDPWD**: `/home/zod`
**XDG_VTNR**: `7`
**XDG_DATA_DIRS**: `/home/zod/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share`
**MAIL**: `/var/mail/zod`
**XDG_SESSION_TYPE**: `x11`
**XCURSOR_THEME**: `Dracula-cursors`
**LANGUAGE**: `en_US`
**XDG_SESSION_ID**: `1`
**KDE_FULL_SESSION**: `true`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/tmp/dbus-6VStUT7mx4,guid=dd91dda2eb97132821c20f7d64f8393a`
**XDG_SEAT**: `seat0`
**GTK_RC_FILES**: `/etc/gtk/gtkrc:/home/zod/.gtkrc:/home/zod/.config/gtkrc`
**MOZ_PLUGIN_PATH**: `/usr/lib/mozilla/plugins`
**XAUTHORITY**: `/tmp/xauth_VafCjr`
**USER**: `zod`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**DBUS_STARTER_BUS_TYPE**: `session`
**KDE_SESSION_VERSION**: `5`
**JAVA_HOME**: `/usr/lib/jvm/java-1.8-openjdk`
**NIX_PROFILES**: `/nix/var/nix/profiles/default /home/zod/.nix-profile`
**SHLVL**: `0`
**PWD**: `/home/zod`
**LC_COLLATE**: `C`
**LANG**: `en_US.UTF-8`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**XDG_CONFIG_DIRS**: `/home/zod/.config/kdedefaults:/etc/xdg`
**_**: `/usr/bin/dbus-launch`
**HOME**: `/home/zod`
**LOGNAME**: `zod`
</details>

**Comment by pbek** [comment]
If you want to copy files semi automaticaly best do that with a shell script. If you want to create a note from a template there is a script called meeting note... Hope that helps, I quite frankly didn't understand all processes you need to happen at the same time. 😅

**Comment by zeyadelkholyttt** [comment]
> If you want to copy files semi automaticaly best do that with a shell script. If you want to create a note from a template there is a script called meeting note... Hope that helps, I quite frankly didn't understand all processes you need to happen at the same time. 😅

i understand that it doesn't more clear to me 😂. but what i need to do is something like note link but when i can preview and edit in the page which i made the link in.

**Comment by pbek** [comment]
You can only edit the current note.

**Comment by zeyadelkholyttt** [comment]
> You can only edit the current note.

if there is no way to make me edit it are there any way to make the link have review in the page which i have link in?

**Comment by pbek** [comment]
I think I don't understand this sentence. 😅

**Comment by zeyadelkholyttt** [comment]
> I think I don't understand this sentence. 😅

![Sep08::221817](https://github.com/pbek/QOwnNotes/assets/88236856/2921d4dc-b9a3-4c5c-80ed-cb5f0fe4ee28)

like this link but i just need preview of it without clicking on it

**Comment by pbek** [comment]
No, that is not possible
