### ISSUE TITLE
Save pane size when toggling between editor and preview 

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#283]
I've stated using the #269 toggling between editor and preview feature and there's something that can make it work more seamless, neater.

The app now saves the pane sizes for each pane combination. So "editor only" and "preview only" are different combinations with different pane sizes. 

It looked ok when the user had to toggle between these combinations in several stages. But with new one key action the editor/preview pane size jumps on each toggle. User can make the panes even manually but it's not fast and will last only till the first change.

I think that toggling between editor and preview key should also transfer the size of the editor/preview pane and save it as if user have set it. Normal pane toggling won't be altered by that.

It sounds like it won't require many new code.

**Comment by pbek** [comment]
Can you please describe the current behavior and then the desired behaviour?

**Comment by pbek** [comment]
Because the pane sizes will be saved, you just have to resize the panes to your liking in every of the two modes...

**Comment by Maboroshy** [comment]
Lets call toggling between editor and preview key a "swapping" for the ease of understanding different kinds of "toggling".

Yes, the sizes can be resized manually, as I wrote in paragraph 3 of my post. But it's not easy since you don't see two panes at the same time and it's about some precision. 

You have to swap panes many times to adjust it. And then if you need to change the size you'll have to do it again. Turned on tag pane? It's another combination so you'll have to do it all over again for it.

So the current behavior: 
press swap key - combination changes - size changes.
Desired one for me: 
press swap key - combination changes - size of editor pane have the same size as preview pane you've just swapped, new size saved to combination;
but toggle panes the old way without swapping - combination changes - size changes.

There are variables for each pane for each combination, right? So the idea is to make something like that on swap key press: 
```
temp_size_var=current_editor_pane_size_var
swap panes 
current_preview_pane_size_var=temp_size_var
```

**Comment by pbek** [comment]
The thing is, the toggle button is a button that just presses the two other buttons accordingly. It has no status. And the panes have different settings (or to be precise, the splitters), it would be very messy to try to get the right settings out out of the different splitters and simulate that behavior.

And what would be the improvement over the current functionality?

**Comment by Maboroshy** [comment]
The improvement would be the ergonomics and visual quality of pane swapping function, so it will grow over being two button pressing thing.

Is far as I understand it's not about getting settings of different splitter, more about getting settings of the first splitter from the right side.

But I do understand that the whole swapping thing maybe not that popular to put energy in it. And there's nothing really broken in it to fix.

**Comment by pbek** [comment]
I'm sorry, but manipulating the splitters directly is a nightmare and will cause all kinds of side effects.
