### ISSUE TITLE
[BUG] Experimental Note List Panel setting causes subfolders to be treated as random(?) notes

### ISSUE THREAD

**Issue by Hate9** [pbek/QOwnNotes#2832]
#### Expected behaviour
When the experimental note list panel setting is enabled, clicking on a subfolder does not open a note.

#### Actual behaviour
When the experimental note list panel setting is enabled, clicking on a subfolder acts as though an apparently random note in the folder containing the subfolder were selected, showing it in the editor panel.

#### Steps to reproduce
- Create a new notebook
- Enable the experimental setting (there's only the one)
- Create a subfolder
- Create a note in the main folder
- Select the folder
- Observe

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fri. Sep. 8 00:27:25 2023`
**Version**: `23.9.0`
**Build date**: `Aug 31 2023`
**Build number**: `1051`
**Platform**: `linux`
**Operating System**: `EndeavourOS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.10`
**Qt Version (runtime)**: `5.15.10`
**Portable mode**: `no`
**Settings path / key**: `/home/mabel/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/mabel/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_CA`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080, 1920x1080`
**Icon theme**: `Breeze-Round-Chameleon Dark Icons`
**Notes in current note folder**: `621`
**Calendar items**: `0`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/home/mabel/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `2`

### Note folder `notes`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/mabel/notes`
**remotePath**: *empty*
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**allowDifferentNoteFileName**: `yes`
**activeNoteSubFolder name**: `notes`
**database file**: `/home/mabel/notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

### Script `Wiki Links`

**id**: `1`
**path**: `/home/mabel/.local/share/PBE/QOwnNotes/scripts/wiki-links/wiki-links.qml`
**variablesJson**: 
```
{
    "wikilinksBackgroundColor": "#FFFF00",
    "wikilinksForegroundColor": "#ff832b",
    "wikilinksHideSubfolder": true,
    "wikilinksLowerCase": true,
    "wikilinksRemoveSpaces": true,
    "wikilinksReplaceSpacesSymbol": "-",
    "wikilinksSanitizeFilename": true
}
```
**identifier**: `wiki-links`
**version**: `0.0.1`
**minAppVersion**: `20.6.0`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (bool): `false`
**Editor/showLineNumbers** (bool): `false`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**LastUpdateCheck** (QDateTime): `2023-09-08T00:16:57.719`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Codelia Ligatures,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Codelia,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Codelia Ligatures,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Codelia,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.refreshDebounceTime** (int): `600`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**NoteFolder-2/NoteTabNameList** (QStringList): `QuickNote`
**NoteFolder-2/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-2/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteFolder-2/allowDifferentNoteFileName** (bool): `true`
**NoteHistory-2** (QVariantList): `<variant list with 14 item(s)>`
**NoteHistoryCurrentIndex-2** (int): `13`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `true`
**appMetrics/disableTracking** (bool): `true`
**appMetrics/notificationShown** (QString): `true`
**autoReadOnlyMode** (bool): `false`
**autoReadOnlyModeTimeout** (int): `30`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `2`
**currentWorkspace** (QString): `P2FAVhsSUA7z`
**cursorWidth** (int): `1`
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `true`
**enableSocketServer** (bool): `true`
**enableWebAppSupport** (bool): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (int): `17`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelAutoSelect** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/mabel/notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `xuNgV9d9cuVy`
**recentNoteFolders** (QString): `/home/mabel/Notes`
**restoreCursorPosition** (bool): `true`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**startInReadOnlyMode** (bool): `false`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (int): `22222`
**webSocketServerService/token** (QString): `<hidden>`
**workspace-P2FAVhsSUA7z/name** (QString): `Full`
**workspace-P2FAVhsSUA7z/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-P2FAVhsSUA7z/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `P2FAVhsSUA7z`

## System environment

**BROWSER**: `firefox`
**EDITOR**: `nano`
**HOME**: `/home/mabel`
**LANG**: `en_CA.UTF-8`
**LOGNAME**: `mabel`
**MAIL**: `/var/spool/mail/mabel`
**PATH**: `/home/mabel/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/mabel/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
**SHELL**: `/bin/bash`
**USER**: `mabel`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**NIX_REMOTE**: `daemon`
**NIX_PATH**: `nixpkgs=/nix/var/nix/profiles/per-user/mabel/channels/nixpkgs:/nix/var/nix/profiles/per-user/mabel/channels`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**DEBUGINFOD_URLS**: `https://debuginfod.archlinux.org`
**DESKTOP_SESSION**: `plasma`
**DISPLAY**: `:0`
**DOTNET_BUNDLE_EXTRACT_BASE_DIR**: `/home/mabel/.cache/dotnet_bundle_extract`
**DOTNET_ROOT**: `/usr/share/dotnet`
**GTK2_RC_FILES**: `/etc/gtk-2.0/gtkrc:/home/mabel/.gtkrc-2.0:/home/mabel/.config/gtkrc-2.0`
**GTK_MODULES**: `canberra-gtk-module:appmenu-gtk-module`
**GTK_RC_FILES**: `/etc/gtk/gtkrc:/home/mabel/.gtkrc:/home/mabel/.config/gtkrc`
**KDE_APPLICATIONS_AS_SCOPE**: `1`
**KDE_FULL_SESSION**: `true`
**KDE_SESSION_UID**: `1000`
**KDE_SESSION_VERSION**: `5`
**LD_PRELOAD**: `/usr/lib/hax11/$LIB/hax11.so`
**MOTD_SHOWN**: `pam`
**NIX_PROFILES**: `/nix/var/nix/profiles/default /home/mabel/.nix-profile`
**NIX_SSL_CERT_FILE**: `/etc/ssl/certs/ca-certificates.crt`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**PWD**: `/home/mabel`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**RACK_DIR**: `/usr/share/vcvrack`
**SESSION_MANAGER**: `local/mabel-endeavouros-linux:@/tmp/.ICE-unix/1048,unix/mabel-endeavouros-linux:/tmp/.ICE-unix/1048`
**UBUNTU_MENUPROXY**: `1`
**XAUTHORITY**: `/tmp/xauth_wsCliE`
**XCURSOR_SIZE**: `24`
**XCURSOR_THEME**: `Vimix-cursors`
**XDG_CONFIG_DIRS**: `/home/mabel/.config/kdedefaults:/etc/xdg`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_SEAT**: `seat0`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_DESKTOP**: `KDE`
**XDG_SESSION_ID**: `2`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**XDG_SESSION_TYPE**: `x11`
**XDG_VTNR**: `2`
**__GL_YIELD**: `usleep`
**MANAGERPID**: `968`
**INVOCATION_ID**: `f6bd0f11220b43a3be51c25c6c4984c9`
**JOURNAL_STREAM**: `8:22240`
**SYSTEMD_EXEC_PID**: `1105`
**MEMORY_PRESSURE_WATCH**: `/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/session.slice/plasma-plasmashell.service/memory.pressure`
**MEMORY_PRESSURE_WRITE**: `c29tZSAyMDAwMDAgMjAwMDAwMAA=`

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[Sep 08 00:30:08] [debug]: Set proxy configuration to use NO proxy
[Sep 08 00:30:09] [scripting]: loading script file: /home/mabel/.local/share/PBE/QOwnNotes/scripts/wiki-links/wiki-links.qml
[Sep 08 00:30:09] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[Sep 08 00:30:09] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <accountId>"" <priority>1
[Sep 08 00:30:09] [debug]: loadNoteDirectoryList
[Sep 08 00:30:09] [debug]: reloadTagTree
[Sep 08 00:30:09] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(0)
[Sep 08 00:30:09] [debug]: reloadNoteSubFolderTree
[Sep 08 00:30:09] [debug]: reload
[Sep 08 00:30:09] [debug]: loadNoteDirectoryList
[Sep 08 00:30:10] [debug]: reloadTagTree
[Sep 08 00:30:10] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector(0)
[Sep 08 00:30:11] [debug]: on_noteTreeWidget_itemSelectionChanged
[Sep 08 00:30:11] [debug]: setCurrentNote  - 'note':  Note: <id>3 <name>"recomp-intro" <fileName>"recomp-intro.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
[Sep 08 00:30:11] [debug]:  added to history:  NoteHistoryItem: <noteName>"recomp-intro" <noteSubFolderPathData>"" <cursorPosition>0 <relativeScrollBarPosition>0
[Sep 08 00:30:11] [debug]: Current sub folder changed
[Sep 08 00:30:11] [debug]: on_noteTreeWidget_itemSelectionChanged
[Sep 08 00:30:11] [debug]: setCurrentNote  - 'note':  Note: <id>48 <name>"note143" <fileName>"note143.md" <noteSubFolderId>1 <relativePath>"notes" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
[Sep 08 00:30:11] [debug]: Switching note subfolder
[Sep 08 00:30:11] [debug]: Current sub folder changed
[Sep 08 00:30:11] [debug]:  added to history:  NoteHistoryItem: <noteName>"note143" <noteSubFolderPathData>"notes" <cursorPosition>0 <relativeScrollBarPosition>0
[Sep 08 00:30:12] [debug]: Current sub folder changed
[Sep 08 00:30:12] [debug]: on_noteTreeWidget_itemSelectionChanged
[Sep 08 00:30:12] [debug]: setCurrentNote  - 'note':  Note: <id>59 <name>"note79" <fileName>"note79.md" <noteSubFolderId>1 <relativePath>"notes" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
[Sep 08 00:30:12] [debug]: Switching note subfolder
[Sep 08 00:30:12] [debug]:  added to history:  NoteHistoryItem: <noteName>"note79" <noteSubFolderPathData>"notes" <cursorPosition>0 <relativeScrollBarPosition>0
[Sep 08 00:30:13] [debug]: on_noteTreeWidget_itemSelectionChanged
[Sep 08 00:30:13] [debug]: setCurrentNote  - 'note':  Note: <id>2 <name>"QuickNote" <fileName>"QuickNote.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
[Sep 08 00:30:13] [debug]: Switching note subfolder
[Sep 08 00:30:13] [debug]: Current sub folder changed
[Sep 08 00:30:13] [debug]:  added to history:  NoteHistoryItem: <noteName>"QuickNote" <noteSubFolderPathData>"" <cursorPosition>946 <relativeScrollBarPosition>0
[Sep 08 00:30:54] [debug]: on_noteTreeWidget_itemSelectionChanged
[Sep 08 00:30:54] [debug]: setCurrentNote  - 'note':  Note: <id>3 <name>"recomp-intro" <fileName>"recomp-intro.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
[Sep 08 00:30:54] [debug]:  added to history:  NoteHistoryItem: <noteName>"recomp-intro" <noteSubFolderPathData>"" <cursorPosition>0 <relativeScrollBarPosition>0
[Sep 08 00:30:55] [debug]: on_noteTreeWidget_itemSelectionChanged
[Sep 08 00:30:55] [debug]: setCurrentNote  - 'note':  Note: <id>4 <name>"old todo" <fileName>"old todo.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
[Sep 08 00:30:55] [debug]:  added to history:  NoteHistoryItem: <noteName>"old todo" <noteSubFolderPathData>"" <cursorPosition>0 <relativeScrollBarPosition>0
[Sep 08 00:30:55] [debug]: on_noteTreeWidget_itemSelectionChanged
[Sep 08 00:30:55] [debug]: setCurrentNote  - 'note':  Note: <id>5 <name>"community interested buyers" <fileName>"community interested buyers.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
[Sep 08 00:30:55] [debug]:  added to history:  NoteHistoryItem: <noteName>"community interested buyers" <noteSubFolderPathData>"" <cursorPosition>0 <relativeScrollBarPosition>0
[Sep 08 00:30:56] [debug]: on_noteTreeWidget_itemSelectionChanged
[Sep 08 00:30:56] [debug]: setCurrentNote  - 'note':  Note: <id>6 <name>"sequences subway surfer" <fileName>"sequences subway surfer.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
[Sep 08 00:30:56] [debug]:  added to history:  NoteHistoryItem: <noteName>"sequences subway surfer" <noteSubFolderPathData>"" <cursorPosition>0 <relativeScrollBarPosition>0
[Sep 08 00:30:57] [debug]: Current sub folder changed
[Sep 08 00:30:57] [debug]: on_noteTreeWidget_itemSelectionChanged
[Sep 08 00:30:57] [debug]: setCurrentNote  - 'note':  Note: <id>58 <name>"note71" <fileName>"note71.md" <noteSubFolderId>1 <relativePath>"notes" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
[Sep 08 00:30:57] [debug]: Switching note subfolder
[Sep 08 00:30:57] [debug]: Current sub folder changed
[Sep 08 00:30:57] [debug]:  added to history:  NoteHistoryItem: <noteName>"note71" <noteSubFolderPathData>"notes" <cursorPosition>0 <relativeScrollBarPosition>0
[Sep 08 00:30:57] [debug]: Current sub folder changed
[Sep 08 00:30:57] [debug]: on_noteTreeWidget_itemSelectionChanged
[Sep 08 00:30:57] [debug]: setCurrentNote  - 'note':  Note: <id>57 <name>"Look into local locator and that one PR to see how" <fileName>"Look into local locator and that one PR to see how.md" <noteSubFolderId>1 <relativePath>"notes" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
[Sep 08 00:30:57] [debug]: Switching note subfolder
[Sep 08 00:30:57] [debug]:  added to history:  NoteHistoryItem: <noteName>"Look into local locator and that one PR to see how" <noteSubFolderPathData>"notes" <cursorPosition>0 <relativeScrollBarPosition>0
[Sep 08 00:30:58] [debug]: Current sub folder changed
[Sep 08 00:30:58] [debug]: on_noteTreeWidget_itemSelectionChanged
[Sep 08 00:30:58] [debug]: setCurrentNote  - 'note':  Note: <id>48 <name>"note143" <fileName>"note143.md" <noteSubFolderId>1 <relativePath>"notes" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
[Sep 08 00:30:58] [debug]: Switching note subfolder
[Sep 08 00:30:58] [debug]:  added to history:  NoteHistoryItem: <noteName>"note143" <noteSubFolderPathData>"notes" <cursorPosition>0 <relativeScrollBarPosition>0
[Sep 08 00:30:58] [debug]: Current sub folder changed
[Sep 08 00:30:58] [debug]: on_noteTreeWidget_itemSelectionChanged
[Sep 08 00:30:58] [debug]: setCurrentNote  - 'note':  Note: <id>47 <name>"note101" <fileName>"note101.md" <noteSubFolderId>1 <relativePath>"notes" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
[Sep 08 00:30:58] [debug]: Switching note subfolder
[Sep 08 00:30:58] [debug]:  added to history:  NoteHistoryItem: <noteName>"note101" <noteSubFolderPathData>"notes" <cursorPosition>0 <relativeScrollBarPosition>0
```

</details>

**Comment by pbek** [comment]
I guess you are talking about #790, best add that there...

**Comment by Hate9** [comment]
Ah, yes. Sorry, I didn't see that earlier.
