### ISSUE TITLE
[I] numbered list  with text between two points

### ISSUE THREAD

**Issue by SBaldrick** [pbek/QOwnNotes#2834]
#### Expected behaviour

An example is more efficient than a long dry speech : 

I type : 
1. number one
2. number two

The preview says : 
1. number one
2. number two. 

But when I type : 
1. number one
some text in between
3. number two
some text in between... 
4. etc... 

I expect the preview to follow my input of numbered list. Inserting a regular block of text between two points seems to reset the numbered list to zero, even though I explicitely and with no ambiguous terms entered the right numbers.

#### Actual behaviour

The preview says : 
1. number one

some text in between

1. number two  

some text in between

1. number three

#### Steps to reproduce

just a regular numbered list with some text insterted in between

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `ven. sept. 8 22:22:42 2023`
**Version**: `23.9.0`
**Build date**: `Aug 31 2023`
**Build number**: `1051`
**Platform**: `linux`
**Operating System**: `KDE Flatpak runtime`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub`
**Qt Version (build)**: `5.15.10`
**Qt Version (runtime)**: `5.15.10`
**Portable mode**: `no`
**Settings path / key**: `/home/phil/.var/app/org.qownnotes.QOwnNotes/config/PBE/QOwnNotes.conf`
**Application database path**: `/home/phil/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `fr_FR`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `Mint-Y`
**Notes in current note folder**: `69`
**Calendar items**: `43`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://acloud7.zaclys.com`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `24.0.6.1`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: `auto`
**Language codes**: `en_AU, en_BS, en_BZ, en_CA, en_GB, en_GH, en_IE, en_IN, en_JM, en_MW, en_NA, en_NZ, en_PH, en_TT, en_US, en_ZA, en_ZW, fr_BE, fr_CA, fr_CH, fr_FR, fr_LU, fr_MC`
**Language names**: `Australian English (Australia), English (Bahamas), English (Belize), Canadian English (Canada), British English (United Kingdom), English (Ghana), English (Ireland), English (India), English (Jamaica), English (Malawi), English (Namibia), English (New Zealand), English (Philippines), English (Trinidad & Tobago), American English (United States), English (South Africa), English (Zimbabwe), français (Belgique), français canadien (Canada), français suisse (Suisse), français (France), français (Luxembourg), français (Monaco)`
**Application dictionaries path**: `/home/phil/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `par défaut`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/phil/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `yes`
**activeNoteSubFolder name**: `Terminale`
**database file**: `/home/phil/Nextcloud/Notes/notes.sqlite`

### Cloud connection `Par défaut`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://acloud7.zaclys.com`
**username**: `28482`
**accountId**: `28482`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**AttachmentDialog/geometry** (QByteArray): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `19`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `false`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `/home/phil/Bureau`
**FileDialog/LastPath-PreviewHTMLFileExport** (QString): `/home/phil/Bureau`
**ImageDialog/disableCopying** (QString): `true`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2023-09-08T22:14:14.063`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `EPO, Séquences, Séquences/Terminale, Fac, Séquences/1ere`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,12,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Ubuntu,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Gill Sans,14,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (QString): `600`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `false`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/share-sync-information** (QString): `1024`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QString): `Tle G Trinity College`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QString): 
```
Séquences
Terminale
```
**NoteFolder-1/allowDifferentNoteFileName** (QString): `true`
**NoteHistory-1** (QVariantList): `<variant list with 163 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `162`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePrinting** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `0`
**TodoDialog/showDueTodayItemsOnly** (QString): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Personnel`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `true`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `0e2562f8-5f5b-432d-8e70-e1a7157a1d31`
**cursorWidth** (QString): `1`
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `16`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `1`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/phil/Nextcloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Erreur inconnue`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `24.0.6.1`
**previousWorkspace** (QString): `initial`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2023-09-02T10.32.12, Note 2023-09-02T10.16.05, Note 2023-08-31T18.08.53, Note 2023-08-31T18.08.00, Note 2023-08-29T15.17.54, Note 2023-08-28T23.17.11, Note 2023-08-27T19.28.03, Note 2023-08-23T19.32.13, Note 2023-08-09T14.54.26, Note 2023-07-09T12.43.47, Note 2023-07-05T21.21.05, Note 2023-07-05T19.04.51, Note 2023-06-12T16.24.19, Note 2023-06-12T09.08.04, Note 2023-05-28T19.17.24, Note 2023-05-01T17.00.26, Note 2023-04-03T17.18.47, Note 2023-03-16T11.17.48, Note 2023-03-08T15.28.18, Note 2023-02-07T17.15.51, Note 2023-02-02T17.17.46, Note 2023-01-29T15.27.14, Note 2023-01-14T16.24.08, Note 2023-01-07T15.48.07, Note 2023-01-07T12.16.01, Note 2023-01-03T18.54.40, Note 2023-01-01T17.57.41, Note 2022-12-07T18.31.33, Note 2022-11-25T23.23.01, Note 2022-11-03T12.17.35, Note 2022-10-20T09.11.51, Note 2022-10-18T16.21.26, Note 2022-10-18T15.50.39, Note 2022-10-18T15.31.27, Note 2022-10-18T15.06.45, Note 2022-10-18T14.58.45, Note 2022-10-18T14.39.36, Note 2022-10-18T14.24.33, Note 2022-10-18T14.05.50, Note 2022-10-18T13.56.33, Note 2022-10-18T13.29.26, Note 2022-10-18T13.23.58, Note 2022-10-18T13.04.51, Note 2022-10-18T10.14.38, Note 2022-10-18T10.03.00, Note 2022-10-16T11.35.45, Note 2022-10-10T09.10.47, Note 2022-09-16T12.20.43, Note 2022-08-26T13.36.30, Note 2022-07-21T18.32.54, Note 2022-06-28T16.20.45, Note 2022-06-13T14.47.52, Note 2022-06-06T20.21.58, Note 2022-05-31T22.32.04, Note 2022-05-24T18.09.33, Note 2022-05-15T20.12.03, Note 2022-05-03T18.32.09, Note 2022-02-14T10.02.31, Note 2022-01-31T21.30.48, Note 2022-01-30T09.40.41, Note 2022-01-17T20.05.44`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `barre d'outils principale`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `barre d'outils de formatage`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `barre d'outils d'insertion`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `barre d'outils de chiffrement`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `barre d'outils de fenêtre`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quitter la barre d’outils`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (QString): `22222`
**workspace-0e2562f8-5f5b-432d-8e70-e1a7157a1d31/name** (QString): `General`
**workspace-0e2562f8-5f5b-432d-8e70-e1a7157a1d31/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-0e2562f8-5f5b-432d-8e70-e1a7157a1d31/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `0e2562f8-5f5b-432d-8e70-e1a7157a1d31`

## System environment

**XDG_RUNTIME_DIR**: `/run/user/1000`
**container**: `flatpak`
**AT_SPI_BUS_ADDRESS**: `unix:path=/run/flatpak/at-spi-bus`
**CINNAMON_VERSION**: `5.8.4`
**CLUTTER_IM_MODULE**: `ibus`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/flatpak/bus`
**DESKTOP_SESSION**: `cinnamon`
**DISPLAY**: `:99.0`
**FLATPAK_ID**: `org.qownnotes.QOwnNotes`
**FLATPAK_SANDBOX_DIR**: `/home/phil/.var/app/org.qownnotes.QOwnNotes/sandbox`
**GDMSESSION**: `cinnamon`
**GDM_LANG**: `fr_FR`
**GIO_LAUNCHED_DESKTOP_FILE**: `/var/lib/flatpak/exports/share/applications/org.qownnotes.QOwnNotes.desktop`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `41319`
**GI_TYPELIB_PATH**: `/app/lib/girepository-1.0`
**GJS_DEBUG_OUTPUT**: `stderr`
**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**GST_PLUGIN_PATH**: `/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0`
**GTK3_MODULES**: `xapp-gtk3-module`
**GTK_IM_MODULE**: `ibus`
**GTK_MODULES**: `gail:atk-bridge`
**HOME**: `/home/phil`
**KDE_FORK_SLAVES**: `1`
**LANG**: `fr_FR.UTF-8`
**LANGUAGE**: `fr_FR`
**LD_LIBRARY_PATH**: *empty*
**LOGNAME**: `phil`
**PATH**: `/app/bin:/usr/bin`
**PS1**: `[📦 $FLATPAK_ID \W]\$ `
**PWD**: `/home/phil`
**QML2_IMPORT_PATH**: `/app/lib64/qml:/app/lib/qml`
**QT_ACCESSIBILITY**: `1`
**QT_IM_MODULE**: `ibus`
**QT_PLUGIN_PATH**: `/app/lib64/plugins:/app/lib/plugins:/usr/share/runtime/lib/plugins`
**QT_QPA_PLATFORMTHEME**: `qt5ct`
**SESSION_MANAGER**: `local/phil-VivoBook-ASUSLaptop-X513UA-M513UA:@/tmp/.ICE-unix/1230,unix/phil-VivoBook-ASUSLaptop-X513UA-M513UA:/tmp/.ICE-unix/1230`
**SHELL**: `/bin/sh`
**SHLVL**: `0`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**USER**: `phil`
**XAUTHORITY**: `/run/flatpak/Xauthority`
**XDG_CACHE_HOME**: `/home/phil/.var/app/org.qownnotes.QOwnNotes/cache`
**XDG_CONFIG_DIRS**: `/app/etc/xdg:/etc/xdg`
**XDG_CONFIG_HOME**: `/home/phil/.var/app/org.qownnotes.QOwnNotes/config`
**XDG_CURRENT_DESKTOP**: `X-Cinnamon`
**XDG_DATA_DIRS**: `/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share`
**XDG_DATA_HOME**: `/home/phil/.var/app/org.qownnotes.QOwnNotes/data`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/phil`
**XDG_SEAT**: `seat0`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_DESKTOP**: `cinnamon`
**XDG_SESSION_ID**: `c2`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**XDG_SESSION_TYPE**: `x11`
**XDG_VTNR**: `7`
**XMODIFIERS**: `@im=ibus`
**__EGL_EXTERNAL_PLATFORM_CONFIG_DIRS**: `/etc/egl/egl_external_platform.d:/usr/lib/x86_64-linux-gnu/GL/egl/egl_external_platform.d:/usr/share/egl/egl_external_platform.d`
</details>

**Comment by pbek** [comment]
There is a new list started for each block. You'd need to put your whole list item in one line

**Comment by SBaldrick** [comment]
I know, and what if I don't want to ? What if my 1. is a paragraph title and I feel like writing the paragraph in a new block before moving on to point 2. ? 
The fact is, my point 2 becomes point 1 in the QOwnNotes preview, and it's slightly annoying. I see no reason why my number 2 should become a number 1.
Other fact : on the Nextcloud notes app (web or android), the preview does respect what I typed in. So I'm absolutely convinced the QOwnNotes app is capable of doing it as well !

**Comment by pbek** [comment]
> The fact is, my point 2 becomes point 1 in the QOwnNotes preview

In Markdown to HTML transformation, those numbers get translated to ordered lists.
And in ordered lists in HTML the HTML rendered (e.g. the web browser) decides the numbers.
Unfortunately, that's the way ordered lists in HTML work. 

Even here on GitHub

```
1) test
1) test
1) test
```

becomes:

1) test
1) test
1) test

**Comment by pbek** [comment]
Or what Markdown did you actually use? Best use a code block to give an example, which will not be interpreted by GitHub.

**Comment by pbek** [comment]
And to better understand what HTML is generated in your preview, you can right-click it and export and examine the generated HTML.

**Comment by SBaldrick** [comment]
Thanks for the tip ! 
Believe it or not, the generate HTML respects the original numbers I have typed in. There is no reset of the numbered list because of an intermediary block of text. 

The problem seems to be specific the the QOwnNotes software.

**Comment by pbek** [comment]
It's hard to look at it without a Markdown example and the generated HTML.
And in the end it's all about what https://doc.qt.io/qt-6/qtextbrowser.html is capable of.

**Comment by SBaldrick** [comment]
I'll show you a screenshot of the QOwnNotes app and the generated HTML. Does that help ?

![Capture d’écran du 2023-09-09 11-59-38](https://github.com/pbek/QOwnNotes/assets/98108095/71c0dbc7-9739-4924-a65c-80bc739b90a9)
[Test.html.zip](https://github.com/pbek/QOwnNotes/files/12565484/Test.html.zip)

**Comment by pbek** [comment]
```
<ol start="3">
<li>My third point.<br>
Oh wait... something is wrong in the preview.... let's try with the...</li>
<li>number 4<br>
That is REALLY annoying !!!</li>
</ol>
```

The QTextBrowser doesn't support `ol start="3"`, so it starts at 1)

**Comment by SBaldrick** [comment]
Okay and could someone pull a few strings, include a bit of coding magic so that the QTextBrowser supports it ? Doesn't sound like too big a deal...

**Comment by pbek** [comment]
You can always try to open an issue on https://bugreports.qt.io/secure/Dashboard.jspa

**Comment by SBaldrick** [comment]
So I understand that the preview is a sort of "brick" in the software that is actually developped by a third party... 
Well, thank you for your input and your help, I've just done what you suggested. 
Best regards

**Comment by pbek** [comment]
The actual HTML rendering is done by that component.
