### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by salamelek** [pbek/QOwnNotes#2837]
I use the Slovenian keyboard layout and thus to type "[" i have to hit alt-f. The only problem is that this opens up a menu on the side (screenshot 1). I have tried to edit the shortcut (screenshot 2), but i think it's considered a "main shortcut" and thus it's ignoring it. I can still type the "[" character, but i have to either change keyboard or copy and paste it.

Screenhot 1
![image](https://github.com/pbek/QOwnNotes/assets/78343078/ec304c12-7a06-489e-9c97-772da8255827)

Screenshot 2
![image](https://github.com/pbek/QOwnNotes/assets/78343078/6a341532-936d-48a4-8e73-0dad3b64b0e5)

**Comment by pbek** [comment]
What was ignored? Setting another shortcut or later when you tried it?
Have you tried using a different shortcut that can't be misinterpreted? Something with a function key maybe...

**Comment by salamelek** [comment]
The new shortcut for "Find notes in all tags / subfolder" was ignored. 
The default shortcut is alt-f, which is also the combinations of keys for the "[" character on the Slovenian keyboard. 
I have tried setting it to Ctrl-Alt-f, and it works. Even thought it works, when i press alt-f it also opens the "Find notes in all tags / subfolder" option. 
Long story short, i can't type "[" because the editor detects it as a shortcut instead of a character press.

(I am on windows 10)

**Comment by pbek** [comment]
I can't reproduce that. If I change the one shortcut to `Ctrl + Shift + F8` then that shortcut works for me. `Alt + F` does nothing then... Can you please also try to set the shortcut to `Ctrl + Shift + F8`?

**Comment by pbek** [comment]
Out of curiosity, your keyboard has an `AltGr` key, like the German keyboard, right?
Do you get your `[` when you press `AltGr + F`?

**Comment by salamelek** [comment]
Yea, exactly. When i press `AltGr + F` the editor opens that menu in screenshot 1. Instead of `[`. In the previous messages i was referring to `AltGr` as `Alt`. 
When i changed the shortcut to `Ctrl + Shift + F8`, the same exact thing happened.

**Comment by pbek** [comment]
Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.

**Comment by salamelek** [comment]
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `pon. sep. 11 12:48:53 2023`
**Version**: `23.8.2`
**Build date**: `Aug 26 2023`
**Build number**: `1050`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\samue\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `sl_SI`
**Locale (interface)**: `en`
**Primary screen resolution**: `2560x1440`
**Screen resolution(s)**: `2560x1440, 1680x1050`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `16`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_GB, en_US, it_IT, sl_SI`
**Language names**: `British English (United Kingdom), American English (United States), italiano (Italia), slovenščina (Slovenija)`
**Application dictionaries path**: `C:\Users\samue\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Notes`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `C:\Users\samue\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**allowDifferentNoteFileName**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\samue\Notes\notes.sqlite`

### Note folder `new folder`

**id**: `2`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `C:\Users\samue\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\samue\Notes\notes.sqlite`

## Cloud connections

### Cloud connection `Privzeto`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

## Enabled scripts

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (int): `21`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `true`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**LastUpdateCheck** (QDateTime): `2023-09-11T12:48:16.988`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Projects, Projects/submarine`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (int): `0`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `true`
**MessageBoxOverride/layoutwidget-use-layout** (int): `16384`
**MessageBoxOverride/local-trash-notes-removed** (int): `1024`
**MessageBoxOverride/move-notes** (int): `16384`
**MessageBoxOverride/remove-note-folder** (int): `16384`
**MessageBoxOverride/windows-dark-mode** (int): `16384`
**NoteFolder-1/NoteTabNameList** (QStringList): `notes`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): 
```
Projects
mega_epic_game
```
**NoteFolder-1/allowDifferentNoteFileName** (QString): `true`
**NoteFolder-2/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 25 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `24`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-actionFind_notes_in_all_subfolders** (QString): `Ctrl+Shift+F8`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**autoReadOnlyMode** (QString): `false`
**autoReadOnlyModeTimeout** (int): `30`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `ZyFP8dBz4gVM`
**cursorWidth** (int): `1`
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): `en`
**internalIconTheme** (QString): `false`
**itemHeight** (int): `15`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyHostName** (QString): `salamelek.rikis.net`
**networking/proxyNeedsAuth** (QString): `true`
**networking/proxyPassword** (QString): `<hidden>`
**networking/proxyPort** (int): `8080`
**networking/proxyType** (int): `2`
**networking/proxyUser** (QString): `riki`
**newNoteAskHeadline** (QString): `true`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `0`
**notesPath** (QString): `C:/Users/samue/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `2`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `99C5a4d87Hwf`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `testing, Ena, New note, Nice note, Test, Test note 2, Note 2023-09-05T16.40.37, Testing note, Note 2023-09-05T16.33.48`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**spellCheckLanguage** (QString): `auto`
**startInReadOnlyMode** (QString): `false`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (int): `22222`
**workspace-99C5a4d87Hwf/name** (QString): `Minimal`
**workspace-99C5a4d87Hwf/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-99C5a4d87Hwf/windowState** (QByteArray): `<binary data>`
**workspace-ZyFP8dBz4gVM/name** (QString): `Full`
**workspace-ZyFP8dBz4gVM/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-ZyFP8dBz4gVM/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Polno`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 99C5a4d87Hwf, ZyFP8dBz4gVM`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**AMDRMPATH**: `C:\Program Files\AMD\RyzenMaster\`
**AMDRMSDKPATH**: `C:\Program Files\AMD\RyzenMasterSDK\`
**APPDATA**: `C:\Users\samue\AppData\Roaming`
**BESIEGE_GAME_ASSEMBLIES**: `D:/steam/steamapps/common/Besiege/Besiege_Data\Managed/`
**BESIEGE_UNITY_ASSEMBLIES**: `D:/steam/steamapps/common/Besiege/Besiege_Data\Managed/`
**ChocolateyInstall**: `C:\ProgramData\chocolatey`
**ChocolateyLastPathUpdate**: `132843181543155550`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `MAIN-SALAM-PC`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\samue`
**LOCALAPPDATA**: `C:\Users\samue\AppData\Local`
**LOGONSERVER**: `\\MAIN-SALAM-PC`
**NUMBER_OF_PROCESSORS**: `16`
**OneDrive**: `C:\Users\samue\OneDrive`
**OneDriveConsumer**: `C:\Users\samue\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Users\samue\AppData\Local\Programs\Python\python-3.11.1\Scripts;C:\Users\samue\AppData\Local\Programs\Python\python-3.11.1;C:\Program Files\Java\jdk-14\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Calibre2\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Mitov\Visuino;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\samue\Desktop\platform-tools;C:\Users\samue\adb-fastboot\platform-tools;C:\Users\samue\AppData\Local\Microsoft\WindowsApps;C:\Users\samue\AppData\Local\Programs\Python\Python38-32;C:\Users\samue\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\samue\AppData\Local\atom\bin;C:\Users\samue\AppData\Roaming\npm;C:\Users\samue\AppData\Local\GitHubDesktop\bin;C:\adb;C:\Users\samue\AppData\Local\Microsoft\WindowsApps;C:\Users\samue\AppData\Local\Programs\Python\Python38-32;C:\Users\samue\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\samue\AppData\Local\atom\bin;C:\Users\samue\AppData\Roaming\npm;C:\Users\samue\AppData\Local\GitHubDesktop\bin`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD`
**PROCESSOR_LEVEL**: `23`
**PROCESSOR_REVISION**: `7100`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\samue\AppData\Local\Temp`
**TMP**: `C:\Users\samue\AppData\Local\Temp`
**USERDOMAIN**: `MAIN-SALAM-PC`
**USERDOMAIN_ROAMINGPROFILE**: `MAIN-SALAM-PC`
**USERNAME**: `samue`
**USERPROFILE**: `C:\Users\samue`
**VBOX_HWVIRTEX_IGNORE_SVM_IN_USE**: `1`
**windir**: `C:\WINDOWS`

**Comment by salamelek** [comment]
Yes, that worked. Thanks for your time and sorry for the trouble.
