### ISSUE TITLE
[BUG] Strange behaviour with non breaking spaces 

### ISSUE THREAD

**Issue by Beurt** [pbek/QOwnNotes#2839]
#### Bug description

In French, we use a lot of non breaking spaces. And QON has a strange behaviour with them. I attached a test file that contains the two most used non breaking spaces.

[test.md](https://github.com/pbek/QOwnNotes/files/12582917/test.md)

it just contains the following markdown text:

```md
---
title: non breaking space test
headingDivider: 1
--- 


# Test 1 classic NBSP


`+00A0   NO-BREAK SPACE`

+00A0   NO-BREAK SPACE


# Test 2 Narrow


`U+202F   NARROW NO-BREAK SPACE`

U+202F   NARROW NO-BREAK SPACE
```

When you open the file with a text editor such as kwrite you can see (the first type of) non breaking spaces. You can also use <https://apps.timwhitlock.info/unicode/inspect?s=> to identify them.

In kwrite (screenshot):

![Screenshot of the file opened in kwrite showing the basic non breaking spaces](https://github.com/pbek/QOwnNotes/assets/12588136/148883ff-8a2b-41b6-8d5d-d74786f6cdf6)

If I put this file in my note folder, and modify it with QON (e.g. adding a word somewhere), the **non breaking spaces vanish from the QON saved file** (we can check it with kwrite or the aforementioned website).

I am using QON 23.9.2 on Linux KDE Neon (Ubuntu Jammy) and all my scripts are deactivated.

#### Steps to reproduce

1. copy the example file to the note folder
2. edit it in QON
3. wait for auto-save or save it in QON
4. check for non breaking spaces in the file with another tool (I.e. kwrite)

Can anyone reproduce this?

**Comment by Beurt** [comment]
More informations:

I made a script that highlight specific characters (such as non breaking spaces) in QON editor panel: https://github.com/qownnotes/scripts/tree/master/characters-highlight

And it is working fine: when I add a non breaking space such as Unicode U+00A0, the character is properly highlighted in the editor panel.

Highlights of the non breaking spaces in the editor panel (Screenshot):

![Screenshot of the QON editor panel showing highlighted non breaking spaces](https://github.com/pbek/QOwnNotes/assets/12588136/3e0d025e-6d6e-46d3-b876-89e68bc7b183)

But, not saved in the file (if I check the file with kwrite or other tools the non breaking space is just a basic space).

File saved, reopen with kwrite, where the non breaking spaces are gone (Screenshot):

![Screenshot of kwrite, showing the file without non breaking spaces](https://github.com/pbek/QOwnNotes/assets/12588136/b10a3326-72ee-4d12-a340-7b144f068a32)

So, in my understanding, the non breaking spaces are indeed present in the editor panel of QON (hence correctly highlighted), but are not saved in the file on the disk. They are lost during the save mechanism.

**Comment by pbek** [comment]
The note files are stored as text file if the setting `useUNIXNewline` is not used:

https://github.com/pbek/QOwnNotes/blob/9d8989e882a211d108bff4a325f88f3f1f5e732d/src/entities/note.cpp#L1369-L1371

UTF-8 is used:

https://github.com/pbek/QOwnNotes/blob/9d8989e882a211d108bff4a325f88f3f1f5e732d/src/entities/note.cpp#L1423

**Comment by pbek** [comment]
If you want to try to debug when those characters are lost (will be a bit hard because you can't output them directly) those areas are a good start. Or maybe just removing some code and how the note is stored... Or maybe another character set?

**Comment by pbek** [comment]
I'll look into it.

**Comment by pbek** [comment]
`noteTextEdit->document()->toRawText()` seems to break a lot, starting with the filename... 🙈

**Comment by pbek** [comment]
I'm giving up on this, I already spend too much time on getting around this. <https://doc.qt.io/qt-6/qtextdocument.html#toPlainText> says the non-breaking spaces are filtered. But if you use `toRawText()` all `QRegularExpressions` are broken.

**Comment by Beurt** [comment]
I am very sorry for the time spent on that issue. And thank you!

I may be have a last idea. Since `toRawText()` cannot be used, is it possible to transform `U+00A0` into `&nbsp;` before `toPlainText` (or any other operation that transform non breaking spaces into basic spaces) and afterward transform it back to `U+00A0`? Maybe it is too much?

**Comment by Beurt** [comment]
That is unfortunate! I am wondering how the other QT editors (such as kwrite) are managing this.

Unfortunately, I cannot figure out how I can compensate this problem with a script since every modifications (for instance adding automagicaly the missing nbsp) will be wiped when the text is fetched for any further treatment.

:crying_cat_face:

**Comment by Beurt** [comment]
:thinking: Reading the `toPlainText()` doc I am wondering: Is it possible to do a `toRawText()` then managing/escaping the *special* characters (U+00A0, U+2029, U+2028) and then doing a `toPlainText()`? Again, it is maybe impossible or too much for a single missing char.

**Comment by pbek** [comment]
Only it someone finds out why all QRegularExpressions are not matching any more.

**Comment by pbek** [comment]
@Waqar144, have you any experience what Kate did?

**Comment by Waqar144** [comment]
Kate doesn't use QPlainTextEdit, and it stores the text separately and renders it hence it doesn't suffer from this issue.

It would be weird if all regular expressions are not matching anymore, there is nothing special about this text, it's a normal QString after all. So is there any particular regex that doesn't match? Also, it may be enough to just use toRawText when storing the note text on disk.

**Comment by pbek** [comment]
Thank you for the clarification.
For example, all the regular expressions that check determine the name of the note. That resulted in the whole note being the name. Characters like `\n` didn't match anymore. It's really weird.

So e.g. everything in:

https://github.com/pbek/QOwnNotes/blob/9d8989e882a211d108bff4a325f88f3f1f5e732d/src/entities/note.cpp#L1557-L1656

**Comment by Waqar144** [comment]
what if you set the `QRegularExpression::UseUnicodePropertiesOption` option? Does it help?

**Comment by pbek** [comment]
> what if you set the QRegularExpression::UseUnicodePropertiesOption option? Does it help?

I just tried, it didn't help

**Comment by pbek** [comment]
I've created a branch to test if you want to play around with it: https://github.com/pbek/QOwnNotes/tree/feature/toRawText-testing

**Comment by pbek** [comment]
## 26.7.4

- Fixed **non-breaking spaces** like `U+00A0` and `U+202F` being converted to
  regular spaces when notes were edited and saved (for [#2839](https://github.com/pbek/QOwnNotes/issues/2839))

**Comment by pbek** [comment]
@Beurt, there now is a new release, could you please test it and report if it works for you?

**Comment by Beurt** [comment]
Hi, Thank you very much to keep working on this issue!

Apparently

 It seems OK. I tested, test.md, and it works fine:

<img width="590" height="861" alt="Image" src="https://github.com/user-attachments/assets/bb910767-0467-499a-814e-d8edb420cc50" />.

I will test further with real life example and tell you if there is an issue.

**Comment by Beurt** [comment]
The U+00A0 seems not available for the scripts thought. For instance:  https://github.com/qownnotes/scripts/tree/master/characters-highlight cannot detect it (it still flawlessly detects U+202F).

<img width="537" height="937" alt="Image" src="https://github.com/user-attachments/assets/0b5d882a-94e3-4035-9925-49529b200e05" />

**Comment by pbek** [comment]
Hm, with the current code path, `script.addHighlightingRule("[" + charactersList + "]", "", 28)` should be able to highlight both U+00A0 and U+202F.

There could also just be differences in Qt versions... ️🤷🏻

A useful quick test would be to bypass the script setting and literal invisible character entirely:

```qml
script.addHighlightingRule("\\x{00A0}", "", 28);
script.addHighlightingRule("\\x{202F}", "", 28);
```

If `\\x{00A0}` works, the problem is the script setting/literal value. If it still does not work while `\\x{202F}` does, then it is likely in the editor/highlighter/runtime path.

**Comment by pbek** [comment]
And thank you for testing the saving!
