### ISSUE TITLE
Search text in all notes

### ISSUE THREAD

**Issue by vpistis** [pbek/QOwnNotes#284]
I think it's a helpful enhancement the implementation of a search function that search text in all notes :)

I don't find it in QOwnNotes.

thanx

**Comment by pbek** [comment]
Which "all notes" are you talking about? You can already search for notes in the note search/create line edit, or am I missing something?

**Comment by vpistis** [comment]
yes, i'm sorry, it found text into all notes.
But if you press return a new note is created, also if the text is correctly highlighted...
I see only at this moment that the text searched is highlighted, before i seen only the new note created.
IMHO this is misleading but now I know this is the beaviour

**Comment by minthemiddle** [comment]
Here is an example. Let's say you have two notes with the relevant keywords `repeat` and `find` in it. Just type in your search keyword in the search bar on the top left and get a filtered list of the notes containing your searchword. Go on the notes and you will get highlights of your search keyword.

![qon-search](https://cloud.githubusercontent.com/assets/1950766/17593251/8e16293c-5fe5-11e6-9045-17b060b58802.gif)

**Comment by pbek** [comment]
I think I still fail to understand what behavior you want to be changed. ;)

**Comment by minthemiddle** [comment]
Me neither. When you type something in and there are notes in your list, you know that you have a result. If the list is empty, your keyword was not found. If you type enter, a new note will be created. There is nothing misleading, IMHO.

**Comment by vpistis** [comment]
ok now I know how it works :)
I know I must not press the return key if I do not want to create a new note :)
Normally, IMHO, when someone press return in text search box, only the search function must be  executed, also into instant real time search functions.
...but is only MHO and now in my town is too hot to think correctly :P
thanx a lot for your work :)

**Comment by pbek** [comment]
I don't think I can help you at the moment. :)
You can use the `down` or `Tab` key to get to the note list.

**Comment by vpistis** [comment]
ok, thanx..
...last question about text search :)
is possible to search text into all note folders instead of just into the current note folder?

**Comment by pbek** [comment]
It only works in the current note folder. But it works in all not subfolders of that note folder.
