### ISSUE TITLE
[BUG] Markdown preview pane - Indentation increases when font size decreases, oposite of expected behavior

### ISSUE THREAD

**Issue by o-l-a-v** [pbek/QOwnNotes#2842]
#### Expected behaviour

Indentation, for instance with bullet point lists, should decrease when decreasing the font size.

#### Actual behaviour

Identation increases when making the font smaller, oposite of what I'd expect.

https://github.com/pbek/QOwnNotes/assets/6450056/cc070dad-ec4b-4c5b-8824-5ac7d2251309

This is with application version v23.9.2, Windows 11 22621.2134.

#### Steps to reproduce

CTRL + scroll on markdown pane, notice that indentation increases when font size decreases.

#### Output from the debug section in the settings dialog

Not relevant.

#### Relevant log output in the Log panel

Not relevant.

**Comment by o-l-a-v** [comment]
Correction: It looks like indentation increases due to the bullet point becoming smaller (less wide), but it looks like identation for when the text starts stays constant.

**Comment by o-l-a-v** [comment]
Looks like https://github.com/pbek/QOwnNotes/issues/1504 already covers this, sorry.

**Comment by o-l-a-v** [comment]
On futher reading it looks like the issue I opened here hasn't been covered it, so I'm reopening. Sorry for the noise.

**Comment by pbek** [comment]
The rendering of the preview is done by Qt's https://doc.qt.io/qt-6/qtextbrowser.html, and I can't do much about it.

Your issue could also be operating system specific or font specific...
I can't reproduce that on Linux (NixOS) with KDE Plasma with Noto Sans. 
The bullet points always stay the same.
Have you tried other fonts?

**Comment by o-l-a-v** [comment]
Sorry for the late reply.

In the screen recording I use Roboto as regular font, and Consolas as code font.

I tested now with Roboto ( https://fonts.google.com/specimen/Roboto ) as regular font, Roboto Mono ( https://fonts.google.com/specimen/Roboto+Mono ) as code font: Same behavior.

One more observation I did not see at the time I reported this issue, visiable in the screen recording:

* CTRL + scroll in the **code window** changes regular font size of the preview window.
* CTRL + scroll in the **preview window** changes just the headings font size in the preview window.

**Comment by o-l-a-v** [comment]
Just installed QOwnNotes with Flatpak on a VM running Pop!_OS 22.04, got v23.9.2.

With the default, out of the box settings in regards to fonts and color schemas, I see the same behavior there, with Fira Sans and Fira Mono as the fonts: 

In the preview pane: The bigger the font size, the closer the bullet points are to the edge.

Small font:

![image](https://github.com/pbek/QOwnNotes/assets/6450056/dc74132b-fd90-4730-8ec3-80ff435289cf)

Big font:

![image](https://github.com/pbek/QOwnNotes/assets/6450056/5b6c41ae-144e-452e-8634-25ca0287da76)

**Comment by pbek** [comment]
If you export the raw HTML from the preview, you can see that the `font-size` is changing when you "zoom". But it's not rendered by the QTextBrowser...

@Waqar144, can you remember anything about that?

**Comment by pbek** [comment]
> not taking effect?

Yes, the font-size style doesn't seem to take effect...
