### ISSUE TITLE
[SUPPORT] 

### ISSUE THREAD

**Issue by MattPampolina** [pbek/QOwnNotes#2846]
#### Question

Hello, I was wondering if there is a  way to escape out of a pipe in a markdown table. An entry with a pipe is throwing off my table and not sure how to fix. Any help would be greatly appreciated!

Thanks,
Matt

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
A backslash escapes it.
