### ISSUE TITLE
[FEATURE] Recursive search

### ISSUE THREAD

**Issue by patvdv** [pbek/QOwnNotes#2848]
Hi,

I don't know if this has been requested before but one thing I sorely miss in the application is the ability to do a full-text search within all **children** of a note folder, meaning sub-folders and the notes in these sub-folders. Perhaps this is already possible and I am missing the trick?

This is for example perfectly possible in the Notes app of Nextcloud.

**Comment by pbek** [comment]
All notes that are shown in the note list are searched.
So if you select just one note subfolder then that folder is searched.
But in the panels settings you can choose to show all notes of the subfolders of subfolders as well.

**Comment by patvdv** [comment]
Hi,

Indeed, that solves my issue. I wasn't aware of the particular option in the settings. Thanks for the quick reply! I will close the request.

**Comment by pbek** [comment]
Great! Have fun! 😁
