### ISSUE TITLE
[BUG] note becomes blank 0kb and no history for no reason

### ISSUE THREAD

**Issue by SophieTamara** [pbek/QOwnNotes#2849]
#### Expected behaviour
Just opening a note (with lots of content on which I worked many time in the past weeks / months) in Qownnotes to read and edit it - synced with Nextcloud

#### Actual behaviour
When opening the note in Qownnotes, it's blank. 
When checking in Nextcloud in online interface, it's 0kb and has no version history except for the current one. 

#### Steps to reproduce
Not sure... That's the second time it happens to me on 2 different notes. Both had a lot of content in it. 
One had an emoticon in the name 
One might have had an image in it, but not sure. 
I also had an older version of Qownnotes. I just updated it...

**Comment by pbek** [comment]
Can you reproduce that issue somehow (reliably)? Maybe by using a similar note?
Emojis in the name shouldn't be an issue, as long as the file system of your operating system support them.

**Comment by SophieTamara** [comment]
I have no idea how to reproduce it. I just know that it happened after having not worked on the note for a long time (weeks?  months?), then opening it, making a small change, closing the app, and then reopening it (maybe the next day or week) to find it blank. I'll pay attention to some more common behaviour if it happens again in the future.

**Comment by pbek** [comment]
Haven't seen such an issue yet.

**Comment by SophieTamara** [comment]
I have more information to share about the issue now. I just retrieved an older version from 4 months ago of my lost note that got blank in nextcloud, but it's definitely not the last version I worked on before I lost it. When I open Qownnotes on my Desktop, and I click on version history, first it tells me that it is downloading the history from the nextcloud server (in the footer of the Qownnotes screen), then it shows some versions older than 4 months ago (see first screen shot). So I guess some versions might be available somewhere on my nextcloud server. But when I go on the online nextcloud platform, I see no version history in the details of the note (see second screen shot) except for the current 0Kb version. However when I click on Activity, I see 2 older version, including one from 3 months ago (see third screen shot)! That doesn't match the history versions I see on Qownnotes, that are from 4 months ago... And when I click on the 3 months old one on nextcloud online platform, it opens the blank current version. I am not sure if that would be an issue on the nextcloud side, the server side or the Qownnotes side...
![Capture d’écran, le 2023-09-26 à 11 42 42](https://github.com/pbek/QOwnNotes/assets/103660199/2adba739-bb3c-453d-ac2c-c58cf50226dc)
![Capture d’écran, le 2023-09-26 à 11 43 11](https://github.com/pbek/QOwnNotes/assets/103660199/e903a71f-103c-4838-9929-c8a868202300)
![Capture d’écran, le 2023-09-26 à 11 43 01](https://github.com/pbek/QOwnNotes/assets/103660199/1e441c50-6205-4df8-9e6d-6bbd8d21db0c)

**Comment by pbek** [comment]
The QOwnNotesAPI Nextcloud App just reads the internal API from Nextcloud. Are you sure you are looking at the same file in QOwnNotes and your Nextcloud instance?

**Comment by SophieTamara** [comment]
Yes I am looking at the same file, I am sure. However, I might have had a note with the same name that I discarded long time ago... But not 100% sure if the name was exactly the same.

**Comment by pbek** [comment]
I have no way of knowing. 😅

**Comment by SophieTamara** [comment]
This issue happened again... This time, 3 notes went blank. The last versions I was able to retrieve for all of them are from 3 days ago (dec 2) and I lost all the content (a lot!) I worked on for the past 3 days. A BLANK conflicted version was created for 2 of them, and both of their "non conflicted" version show content from 3 days ago. 
The third note just went fully blank and didn't create a conflicted version. I was also able to retrieve a version from 3 days ago for that one and lost everything I worked within these 3 days...

I am trying to figure out what could be the reason why this happens: 
- I just saw that a new version of Qownnotes came out 2 weeks ago and I havn't updated it yet. Same happened last time. My Qownnotes app wasn't up to date (I didn't receive notification for an update...). 
- All of these notes were long notes with a lot of content. 
- No emoticon in the name this time, but the one note that went fully blank with no conflicted version was named "-Idéation et Réflexions" so maybe the dash caused a problem (?)
- I might have modified these notes when I had a poor internet connection (or none)...

**Comment by pbek** [comment]
> I just saw that a new version of Qownnotes came out 2 weeks ago and I havn't updated it yet. Same happened last time. My Qownnotes app wasn't up to date (I didn't receive notification for an update...).

Have you turned that dialog off? (You didn't share your settings)

Maybe the file system of your operating system is causing issues... Or something with the Nextcloud Sync Client?

**Comment by SophieTamara** [comment]
I don't recall turning that dialog off. Where is that setting?
Indeed I am not able to update my OS as I have an old Mac (2013).I am stuck at the 11.7.10 Big Sur OS version.

**Comment by SophieTamara** [comment]
I don't recall turning that dialog off. Where is that setting? 
Indeed I am not able to update my OS as I have an old Mac (2013).I am stuck at the 11.7.10 Big Sur OS version

**Comment by pbek** [comment]
> I don't recall turning that dialog off. Where is that setting?

You should always see a small message on the bottom right of the main window if there is an update.
Other than that: In the *General settings*, you can reset the message boxes and enable the update dialog.
