### ISSUE TITLE
[I] Typing fancy quotes on Mac with Alt-[ and Alt-Shift-[ does not work

### ISSUE THREAD

**Issue by nok-ko** [pbek/QOwnNotes#2854]
#### Expected behaviour

On Mac, pressing `Alt-[` and `Alt-Shift-[` in the editor should produce the `“` and `”` characters at the cursor’s position.

(This is standard behaviour on Mac, where most keyboard layouts allow users to type other, special characters by holding Alt and pressing the relevant key.)

#### Actual behaviour

The first time `Alt-[` is pressed, a square bracket is produced. Subsequent keypresses produce open quotes, as expected. Likewise, the first time `Alt-Shift-[` is pressed, a curly bracket is typed, but a closing quote on subsequent keypresses.

Disabling the “Enable automatic closing of brackets and markdown formatting characters” option in the settings menu (Settings → Interface → Editor) restores expected behaviour.

Also, when the caret in the editor has a non-whitespace character on its right, quotes can be typed normally.

#### Steps to reproduce

- Use Mac
- Use the “ABC — Extended” keyboard layout
- Open any note or markdown text input
- Try to type a `“` or `”` character with `Alt-[` or `Alt-Shift-[`
- The wrong character is typed

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[14:00:02] [status] Stored 1 note(s) to disk
[14:00:02] [status] Notes directory was modified externally
[14:00:02] [status] Stored 1 note(s) to disk
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mon Sep 18 14:00:13 2023`
**Version**: `23.9.4`
**Build date**: `Sep 15 2023`
**Build number**: `1055`
**Platform**: `macosx`
**Operating System**: `macOS 13.3`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/Users/nokko/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/nokko/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_CA`
**Locale (interface)**: *empty*
**Primary screen resolution**: `2560x1440`
**Screen resolution(s)**: `2560x1440, 1440x900`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `8`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/Users/nokko/Library/Application Support/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/Users/nokko/nokkonotes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: `200 | Work`
**database file**: `/Users/nokko/nokkonotes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

## Settings

**AKLastEmailListRequestDateKey** (QDateTime): `2023-09-18T00:27:19.416`
**AKLastIDMSEnvironment** (qlonglong): `0`
**AKLastLocale** (QString): `en_CA`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Country** (QString): `CA`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/centerCursor** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (qlonglong): `4`
**Editor/removeTrailingSpaces** (bool): `false`
**Editor/showLineNumbers** (bool): `false`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `true`
**InitialKeyRepeat** (qlonglong): `15`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**KB_DoubleQuoteOption** (QString): `“abc”`
**KB_SingleQuoteOption** (QString): `‘abc’`
**KB_SpellingLanguage** (QVariantMap): *empty*
**KeyRepeat** (qlonglong): `2`
**LastUpdateCheck** (QDateTime): `2023-09-18T13:54:33.855`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (qlonglong): `32`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Menlo,14,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Helvetica Neue,17,-1,5,25,0,0,0,0,0,Light`
**MainWindow/noteTextView.code.font** (QString): `Menlo,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `.AppleSystemUIFont,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.refreshDebounceTime** (qlonglong): `600`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**NoteFolder-1/NoteTabNameList** (QStringList): `Welcome to QOwnNotes, TypeScript + React in the Connector`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `, 200 | Work`
**NoteHistory-1** (QVariantList): `<variant list with 12 item(s)>`
**NoteHistoryCurrentIndex-1** (qlonglong): `11`
**PKSecureElementAvailableFlagsByHostSome** (qlonglong): `3`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (qlonglong): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**TISRomanSwitchState** (qlonglong): `0`
**WebAutomaticSpellingCorrectionEnabled** (bool): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `false`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (bool): `true`
**autoReadOnlyMode** (bool): `false`
**autoReadOnlyModeTimeout** (qlonglong): `30`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (qlonglong): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (qlonglong): `1`
**darkMode** (bool): `true`
**darkModeColors** (bool): `true`
**darkModeIconTheme** (bool): `true`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (bool): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (bool): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**enableWebAppSupport** (bool): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (qlonglong): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (qlonglong): `1024`
**imageScaleDownMaximumWidth** (qlonglong): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (qlonglong): `11`
**interfaceLanguage** (QString): *empty*
**interfaceStyle** (QString): `macintosh`
**internalIconTheme** (bool): `false`
**itemHeight** (qlonglong): `18`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (qlonglong): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelAutoSelect** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (qlonglong): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (qlonglong): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (qlonglong): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (qlonglong): `0`
**notesPanelOrder** (qlonglong): `0`
**notesPanelSort** (qlonglong): `1`
**notesPath** (QString): `/Users/nokko/nokkonotes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (qlonglong): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (qlonglong): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**restoreCursorPosition** (bool): `false`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2023-09-18T13.41.00, Note 2023-09-18T12.04.25, Note 2023-09-18T10.54.55, Note 2023-09-18T10.54.22, Note 2023-09-16T00.26.06, Note 2023-09-16T00.23.59`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**startInReadOnlyMode** (bool): `false`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (qlonglong): `0`
**tagsPanelSort** (qlonglong): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (qlonglong): `6`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (qlonglong): `22222`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**__CFBundleIdentifier**: `com.apple.Terminal`
**TMPDIR**: `/var/folders/10/bs81410s5174pgwj6svb9bbh0000gn/T/`
**XPC_FLAGS**: `0x0`
**TERM**: `xterm-256color`
**DISPLAY**: `/private/tmp/com.apple.launchd.056X8xEeEN/org.xquartz:0`
**SSH_AUTH_SOCK**: `/private/tmp/com.apple.launchd.EGM70aSacr/Listeners`
**XPC_SERVICE_NAME**: `0`
**TERM_PROGRAM**: `Apple_Terminal`
**TERM_PROGRAM_VERSION**: `447`
**TERM_SESSION_ID**: `560AA90F-7020-48E2-963B-6645FA761E5D`
**SHELL**: `/bin/zsh`
**HOME**: `/Users/nokko`
**LOGNAME**: `nokko`
**USER**: `nokko`
**PATH**: (Redacted, sorry.)
</details>

**Comment by pbek** [comment]
I currently lack access to a Mac to test that.

> Disabling the “Enable automatic closing of brackets and markdown formatting characters” option in the settings menu (Settings → Interface → Editor) restores expected behaviour.

So maybe just disable the setting could solve your issue, or am I misunderstanding something?

**Comment by nok-ko** [comment]
> I currently lack access to a Mac to test that.
> 
> > Disabling the “Enable automatic closing of brackets and markdown formatting characters” option in the settings menu (Settings → Interface → Editor) restores expected behaviour.
> 
> So maybe just disable the setting could solve your issue, or am I misunderstanding something?

It’s a workaround, but I think ideally this shouldn’t happen regardless of the setting. I included it in case it helped pinpoint the issue.

I may try to fix the issue over the weekend and submit a PR.

**Comment by pbek** [comment]
> I may try to fix the issue over the weekend and submit a PR.

Awesome! 😁

**Comment by pbek** [comment]
This is a good place to start looking if there needs to be done something macOS-specific:

https://github.com/pbek/qmarkdowntextedit/blob/3209ba2f408365cb9a2fe402da676bcc2779f548/qmarkdowntextedit.cpp#L658

**Comment by MickGe** [comment]
Hi,

It is not only on _MacOS_. On _Fedora_ with french variant layout, nothing happens with <kbd>altGr</kbd>+<kbd>w</kbd> for french opening double quotes : `«`, nor the closing one `»`.

**Comment by pbek** [comment]
On my German layout, `AltGr + w` gives me the character `ſ` under Linux (NixOS Plasma). I don't know if those are blocked by Qt or trigger something else 😬

**Comment by MickGe** [comment]
Oh sorry, it should be <kbd>altGr</kbd>+<kbd>x</kbd> and <kbd>altGr</kbd>+<kbd>x</kbd> for `«` and `»`.

If I manage to understand something in the code, I'll let you know… But don't wait for me!

Anyway, thank you for the time you spend on _QOwnNotes_.

**Comment by pbek** [comment]
Thank you and thank you!

**Comment by MickGe** [comment]
On _MacOS_, angle double quotes is ok. Thank you!

On _Fedora_, it should come from a _flatpak_ issue: https://github.com/flatpak/flatpak/issues/5585.
