### ISSUE TITLE
[FEATURE] Integrating Argdown support

### ISSUE THREAD

**Issue by hydralisk98** [pbek/QOwnNotes#2855]
## Is your feature request related to a problem?
No. It really is just a suggestion of something to integrate / support in QOwnNotes. Nothing more.

## Describe the solution you'd like
I would like to know if [Argdown](https://argdown.org/) was already supported and if it wasn't, have such or similar functionality integrated into the program.

## Describe alternatives you've considered
It is perfectly fine if it is not added, I don't mind much. But at least a acknowledgement about the matter would be great.

**Comment by pbek** [comment]
Are you talking about showing such diagrams in the preview?
You could attempt something similar like https://github.com/qownnotes/scripts/blob/master/mermaid/mermaid.qml (using a web-service to generate an image) or https://github.com/qownnotes/scripts/blob/master/latex-math/latex-math.qml (locally creating an image) in a script.

**Comment by pbek** [comment]
Let me know if you need any help and maybe contribute the script to https://github.com/qownnotes/scripts 😉

**Comment by pbek** [comment]
> have such or similar functionality integrated into the program.

There is a script for [Mermaid](https://mermaid.js.org).

**Comment by hydralisk98** [comment]
Sounds decent thanks. I was thinking of something around the lines of [Argument Maps](https://en.wikipedia.org/wiki/Argument_map) for philosophical and research explainer purposes but this is good enough for me I think. TYSM!
