### ISSUE TITLE
[BUG] Incomplete import from Evernote - no body text

### ISSUE THREAD

**Issue by AlanCDavis-GH** [pbek/QOwnNotes#2856]
#### Expected behaviour
Import of Evernote .enex file creates relatively faithful representation of original 
Evernote Mac 10.60.4
QOwnNotes 23.9.4 Mac

#### Actual behaviour
Import creates entry for each note, including front-matter if selected. It adds image links for all images to every note in the default folder. It doesn't include any of the body text from the original.

#### Steps to reproduce
Export single note or notebook from Evernote to .enex.
Select Note / Import / Import from Evernote
Select front-matter to include
Select Import

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>
[basic.enex.txt](https://github.com/pbek/QOwnNotes/files/12679385/basic.enex.txt)
[basic.md](https://github.com/pbek/QOwnNotes/files/12679388/basic.md)

**Comment by pbek** [comment]
[basic.enex.txt](https://github.com/pbek/QOwnNotes/files/12679385/basic.enex.txt) [basic.md](https://github.com/pbek/QOwnNotes/files/12679388/basic.md)

**Comment by pbek** [comment]
Hm, enex file looks ok, need to do more tests... The other exports I have still work.

**Comment by pbek** [comment]
Qt's XML parser trips over the white spaces in front of the `<![CDATA[`. I can't find anything about if using white spaces in front of it is out of the XML spec... 🤔

**Comment by pbek** [comment]
Since there are valid characters in front of the `<![CDATA[` (the white spaces) those characters are parsed correctly.

**Comment by pbek** [comment]
I'll try to get around that without losing the ability to import older enex exports.

**Comment by pbek** [comment]
## 23.9.5
- an issue with importing the content of notes from Evernote with the `evernote-export4`
  format was fixed (for [#2856](https://github.com/pbek/QOwnNotes/issues/2856))

**Comment by AlanCDavis-GH** [comment]
Excellent! Thanks - I'll pull the update and try it out.


Alan C. Davis ***@***.***
----
Where am I going, and what am I doing in this handbasket? 

    On Thursday, September 21, 2023 at 02:52:24 PM EDT, Patrizio Bekerle ***@***.***> wrote:  
 
 


23.9.5
   
   - an issue with importing the content of notes from Evernote with the evernote-export4   
format was fixed (for #2856)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by AlanCDavis-GH** [comment]
I've installed the new release and successfully imported the .enex file. Thank you for getting the update out so quickly!
Alan C. Davis ***@***.***
----
Where am I going, and what am I doing in this handbasket? 

    On Friday, September 22, 2023 at 02:10:59 AM EDT, Patrizio Bekerle ***@***.***> wrote:  
 
 


There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
Oh, and thanks a lot for your generous donation!
