### ISSUE TITLE
[BUG] Evernote import chokes on '[[' and/or ']]'

### ISSUE THREAD

**Issue by AlanCDavis-GH** [pbek/QOwnNotes#2858]
#### Expected behaviour
On evernote import, ']]' to be parsed and rendered correctly

NOTE : this is not a show-stopper for my use, just an annoyance.
Workaround is to remove offending notes from the .enex file or edit source note and re-export
#### Actual behaviour
Import stops, application becomes unresponsive

#### Steps to reproduce
release 23.9.5

#### Output from the debug section in the settings dialog
<details><summary>Expand</summary>

[Sep 22 14:36:59] [debug]: parseNote  - 'content':  "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!DOCTYPE en-note SYSTEM \"http://xml.evernote.com/pub/enml2.dtd\">\n<en-note style=\"word-wrap: break-word; -webkit-nbsp-mode: space; -webkit-line-break: after-white-space;\">\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">16 Oct 2013</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><br/></div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">start 9am</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">end 7pm</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">10hrs</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">start 9:40</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">end 1am</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">3.5hrs</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><br/></div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">import biz.neustar.sipix.download.LNPDataType;</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">lnpDataType.getTransactionID in DownloadHandler.java</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><br/></div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">in LNPDownload-test-client.jar</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"> 6592 Tue Mar 03 17:27:12 EST 2009 biz/neustar/sipix/download/LNPDataType.class</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><br/></div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">Where is source for LNPDownload-test-client.jar?</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><br/></div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">wmrs billing started failing 10/13<br/></div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">MMIS-253</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">praveen conversation</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"> was rsync'd from old server</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"> will send new acct/passwd for temp use</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">data files exist on stixpprwb1:/opt/data/NTS_CDR/Billing</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"> sftp them to the ftp server when process is available</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><br/></div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">3.2.2 item 4</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"> notify at&amp;t : who/how?</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><br/></div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">REQ0047557 - datacenter rename stixppdb1 to stenpctdb1 </div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><br/></div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">yyyyyyy/xxxxxx</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">Server Name: “ftp.neustar.com”</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">Directory: &quot;/psftfin/production/inbound/&quot;</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">User ID: “zzzzzz”</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><br/></div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">host ftp.neustar.com</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">ftp.neustar.com is an alias for stihftp1.va.neustar.com.</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">stihftp1.va.neustar.com has address xxx.xxx.xxx.xxx</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><span style=\"font-size: medium;\"><b>REQ0047603 - open fw hole : done</b></span></div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><span style=\"font-size: medium;\"> updated /usr/local/app/WMRS/CDR_Process/CDR_Billing*.py w/ new server,user,passwd</span></div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><span style=\"font-size: medium;\"> </span><br/></div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"/>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">Bridge info for 10/19 starting at 1AM EST</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">Local number = 703-464-4242</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">Toll Free = 1-866-858-8807</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"/>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">Conference Pass code = 2222</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">Your Pin code should be your 4 digit office extension.  If for some reason your Pin code does not work please notify the NOC and you can use the guest PIN 1111</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"/>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">When enter the main bridge you can move to the breakout session by hitting *93 (and your groups breakout number).</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">To move back into the main bridge hit *93 0</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">Network Shared = 4 (OPTION 4)</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><br/></div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\">http://rsdashboard.va.neustar.com/wiki/images/5/54/LNP_WebService_Request_And_Responses.txt</div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><br/></div>\n<div><span style=\"border-collapse: separate; color: rgb(0, 0, 0); font-family: Calibri; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-border-horizontal-spacing: 0px; -webkit-border-vertical-spacing: 0px; -webkit-text-decorations-in-effect: none; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; font-size: medium;\"><br/>\nWorkaround : Set the same starting transaction ID but request a range of 25k transactions 1 time only.</span></div>\n<div><span style=\"border-collapse: separate; color: rgb(0, 0, 0); font-family: Calibri; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-border-horizontal-spacing: 0px; -webkit-border-vertical-spacing: 0px; -webkit-text-decorations-in-effect: none; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; font-size: medium;\"> This will get a large enough block of transactions downloaded that they will get LNPData.</span></div>\n<div><span style=\"border-collapse: separate; color: rgb(0, 0, 0); font-family: Calibri; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-border-horizontal-spacing: 0px; -webkit-border-vertical-spacing: 0px; -webkit-text-decorations-in-effect: none; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; font-size: medium;\"> They should only request this large block 1 time and then return to their normal processing parameters.</span></div>\n<div><span style=\"border-collapse: separate; color: rgb(0, 0, 0); font-family: Calibri; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-border-horizontal-spacing: 0px; -webkit-border-vertical-spacing: 0px; -webkit-text-decorations-in-effect: none; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; font-size: medium;\"><br/></span></div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><span style=\"font-family: Calibri; font-size: medium;\">Solution :  Correct their software to always use the NextTransactionID field when they receive a 200 / OK response code, even if there is no LNPData in the response.</span><br/></div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><span style=\"font-family: Calibri; font-size: medium;\"><br/></span></div>\n<span style=\"border-collapse: separate; color: rgb(0, 0, 0); font-family: 'Lucida Grande'; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-border-horizontal-spacing: 0px; -webkit-border-vertical-spacing: 0px; -webkit-text-decorations-in-effect: none; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; font-size: medium;\"><span style=\"color: rgb(51, 51, 51); line-height: 14px;\">&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt; <br style=\"word-wrap: break-word; text-rendering: optimizelegibility;\"/>\n&lt;soapenv:Envelope xmlns:soapenv=&quot;<a href=\"http://schemas.xmlsoap.org/soap/envelope/\" title=\"http://schemas.xmlsoap.org/soap/envelope/\" style=\"word-wrap: break-word; text-rendering: optimizelegibility; border-bottom-width: 1px; border-bottom-style: dashed; border-bottom-color: initial; text-decoration: none;\">http://schemas.xmlsoap.org/soap/envelope/</a>&quot;&gt; <br style=\"word-wrap: break-word; text-rendering: optimizelegibility;\"/>\n&lt;soapenv:Body&gt; <br style=\"word-wrap: break-word; text-rendering: optimizelegibility;\"/>\n&lt;dow:LNPDownloadResponse xmlns:dow=&quot;<a href=\"http://www.neustar.biz/lnp/download\" title=\"http://www.neustar.biz/lnp/download\" style=\"word-wrap: break-word; text-rendering: optimizelegibility; border-bottom-width: 1px; border-bottom-style: dashed; border-bottom-color: initial; text-decoration: none;\">http://www.neustar.biz/lnp/download</a>&quot;&gt; <br style=\"word-wrap: break-word; text-rendering: optimizelegibility;\"/>\n&lt;dow:ResponseCode&gt;200&lt;/dow:ResponseCode&gt;&lt;dow:ResponseText&gt;OK&lt;/dow:ResponseText&gt; <br style=\"word-wrap: break-word; text-rendering: optimizelegibility;\"/>\n&lt;dow:ResponseMessage&gt;LNP data download successfully&lt;/dow:ResponseMessage&gt; <br style=\"word-wrap: break-word; text-rendering: optimizelegibility;\"/>\n&lt;dow:ResponseTimestamp&gt;2013-10-15T23:35:00.762Z&lt;/dow:ResponseTimestamp&gt; <br style=\"word-wrap: break-word; text-rendering: optimizelegibility;\"/>\n&lt;dow:LastTransactionID&gt;942526805&lt;/dow:LastTransactionID&gt; <br style=\"word-wrap: break-word; text-rendering: optimizelegibility;\"/>\n&lt;dow:NextTransactionID&gt;942527805&lt;/dow:NextTransactionID&gt; <br style=\"word-wrap: break-word; text-rendering: optimizelegibility;\"/>\n&lt;/dow:LNPDownloadResponse&gt; <br style=\"word-wrap: break-word; text-rendering: optimizelegibility;\"/>\n&lt;/soapenv:Body&gt; <br style=\"word-wrap: break-word; text-rendering: optimizelegibility;\"/></span></span>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><span style=\"color: rgb(51, 51, 51); font-family: 'Lucida Grande'; line-height: 14px; font-size: medium;\">&lt;/soapenv:Envelope&gt; </span><span style=\"font-family: Calibri; font-size: medium;\"><br/></span></div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><span style=\"color: rgb(51, 51, 51); font-family: 'Lucida Grande'; line-height: 14px; font-size: medium;\"><br/></span></div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><span style=\"color: rgb(51, 51, 51); font-family: 'Lucida Grande'; line-height: 14px; font-size: medium;\"><br/></span></div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><span style=\"color: rgb(51, 51, 51); font-family: 'Lucida Grande'; line-height: 14px; font-size: medium;\">curl -d /tmp/sipix -k <u style=\"word-wrap: break-word; text-rendering: optimizelegibility;\"><a href=\"https://sipix12-cte-lnp.neustar.biz/sipix_si_lnp/services/LNPDownload\" title=\"https://sipix12-cte-lnp.neustar.biz/sipix_si_lnp/services/LNPDownload\" style=\"word-wrap: break-word; text-rendering: optimizelegibility; border-bottom-width: 1px; border-bottom-style: dashed; border-bottom-color: initial; text-decoration: none;\">https://sipix12-cte-lnp.neustar.biz/sipix_si_lnp/services/LNPDownload</a></u></span><span style=\"color: rgb(51, 51, 51); font-family: 'Lucida Grande'; line-height: 14px; font-size: medium;\"><br/></span></div>\n<pre>\n&lt;LNPDownloadRequest xmlns=&quot;<a href=\"http://www.neustar.biz/lnp/download\">http://www.neustar.biz/lnp/download</a>&quot;&gt;\n  &lt;Context&gt;test&lt;/Context&gt;\n  &lt;LastTransactionID&gt;157&lt;/LastTransactionID&gt;\n  &lt;MaxNumberOfRecords&gt;1&lt;/MaxNumberOfRecords&gt; \n</pre>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><span style=\"font-family: monospace; white-space: pre; font-size: medium;\">&lt;/LNPDownloadRequest&gt;</span><span style=\"color: rgb(51, 51, 51); font-family: 'Lucida Grande'; line-height: 14px; font-size: medium;\"><br/></span></div>\n<div style=\"font-family: &quot;Courier&quot;; font-size: 13px; font-style: normal; font-weight: normal;\"><span style=\"font-family: monospace; white-space: pre; font-size: medium;\"><br/></span></div>\n<div style=\"font-size: 12px !important; line-height: 15px !important;\">\n<div>&lt;?xml version='1.0' encoding='utf-8'?&gt;</div>\n<div>&lt;soapenv:Envelope xmlns:soapenv=&quot;<a href=\"http://www.w3.org/2003/05/soap-envelope\">http://www.w3.org/2003/05/soap-envelope</a>&quot;]]\n<![CDATA[>"

Text snippet containing offending element
<?xml version='1.0' encoding='utf-8'?>
<soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"]] > 
  <soapenv:Body>
    <ns0:some_operation xmlns:ns0="http://some_ns_uri"/>
  </soapenv:Body>
</soapenv:Envelope>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
> On evernote import, ']]' to be parsed and rendered correctly

I'm not sure if I understand your issue.

Do you maybe have an enex file to demonstrate it? And maybe a screenshot on what the text should look like?

**Comment by AlanCDavis-GH** [comment]
I'm attaching a reproducer
[bad-input.enex.txt](https://github.com/pbek/QOwnNotes/files/12706764/bad-input.enex.txt)

**Comment by pbek** [comment]
Hm, https://codebeautify.org/xmlvalidator says:

```
Error : InvalidTag
Line : 101
Message : Closing tag 'content' is expected inplace of 'div'. 
```

**Comment by pbek** [comment]
https://www.w3schools.com/xml/xml_validator.asp and https://www.xmlvalidation.com are complaining on it too...

**Comment by pbek** [comment]
## 23.9.7
- Evernote notes with malformed XML will now stop the import process when importing
  them in the Evernote import (for [#2858](https://github.com/pbek/QOwnNotes/issues/2858))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by AlanCDavis-GH** [comment]
Release 23.9.7 works as expected. Thank you for including the title of the malformed note. That will make it much easier to find and remove the offending item.

**Comment by pbek** [comment]
Great, thank you for testing.
Maybe there is a way to open issues for Evernote?
