### ISSUE TITLE
[BUG] media and attachments tags are added to other notes in folder

### ISSUE THREAD

**Issue by AlanCDavis-GH** [pbek/QOwnNotes#2859]
#### Expected behaviour
In Evernote import, attachments and media are only referenced by notes that contain them in source

#### Actual behaviour
Attachments and/or media included in the first item imported (from a notebook export enex) are referenced in all following notes and files are duplicated in the attachments and media folders.

#### Steps to reproduce
Import Evernote notebook export enex file that has either attachments or media elements. 

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

See attached file zip file
log
.md
.enex
media files
[debug.zip](https://github.com/pbek/QOwnNotes/files/12704114/debug.zip)

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Thank you. Yes, it seems only `Write Better Python Code With These 10 Tricks | by Yong Cui, Ph.D. | Aug, 2020 | Towards Data Science` should contain the images.

**Comment by pbek** [comment]
I think attachments might have the same issue, do you maybe have an export with attachments too?

**Comment by pbek** [comment]
## 23.9.6
- an issue with duplicate imported media files and attachments when importing notes
  from Evernote was fixed (for [#2859](https://github.com/pbek/QOwnNotes/issues/2859))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by AlanCDavis-GH** [comment]
23.9.6 looks good for media and attachments - thanks!

**Comment by pbek** [comment]
Great, thank you for testing!
