### ISSUE TITLE
Image not shown on windows

### ISSUE THREAD

**Issue by bgommers** [pbek/QOwnNotes#286]
As a user, when I add an image to a note the image is not shown in the "markdown preview" on my Windows 8 computer.
![2016-08-12_07-42-08](https://cloud.githubusercontent.com/assets/20984295/17614005/e4033236-6062-11e6-9411-24db50b53a92.jpg)
When I open the same note on my Debian 8 system the image is shown in the "markdown preview".

The image should be shown in the "markdown preview" on Windows 8 also.

**Comment by pbek** [comment]
Thank you for reporting. Strange, this already worked... I will take a look at that.

**Comment by pbek** [comment]
No problems under Windows 8.
Are you sure the media file is present on your Windows 8 system?

![virtualbox_windows 8](https://cloud.githubusercontent.com/assets/1798101/17615276/6c115022-606d-11e6-925c-aac9dac663a3.png)

**Comment by bgommers** [comment]
Strange. The problem is solved on my computer. I order to make it work I re-entered several settings.

The "Note folder path" was set to "C:/Users/???/ownCloud\Notes". After resetting the "Note folder path" it is changed to "C:\Users\???\ownCloud\Notes" and images are presented after a restart of QOwnNotes.

Thanks for this great tool. I will continue playing around with it. Good chance that I will starting using it for my daily notes (instead of MS OneNote).

**Comment by pbek** [comment]
note folder: strange, I don't know what could have caused this

Thank you for your kind words! :)
