### ISSUE TITLE
[BUG] characters in evernote imports incorrectly parsed as markdown (should be escaped)

### ISSUE THREAD

**Issue by AlanCDavis-GH** [pbek/QOwnNotes#2860]
#### Expected behaviour
Strings in evernote imported notes that match markdown should be escaped or wrapped in 'preformatted' markdown on import

#### Actual behaviour
At least some strings get imported "bare" and are then seen as markdown in preview

#### Steps to reproduce
Reproducer for H1 and indent markdown attached
A bash comment in the input is about 1/2 way down the note, a python cli prompt is the last line.
[embedded-markdown.enex.txt](https://github.com/pbek/QOwnNotes/files/12706807/embedded-markdown.enex.txt)

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Doesn't sound like a bug, more like a missing feature.
But I'm not sure how to detect all Markdown syntax reliably when they are not marked as, e.g. code block in the enex...

> A bash comment in the input is about 1/2 way down the note, a python cli prompt is the last line.

In Evernote everything is HTML, it's hard to put that back into Markdown.

Suggestions?

**Comment by AlanCDavis-GH** [comment]
This isn’t a showstopper for me. I understand the difficulty of writing a parser for arbitrary input and trying to manage all the edge cases. Maybe just adding something to the documentation that warns of possible mis-formatting where the export contains text that will be seen as markdown would be appropriate.Sent from my iPhoneOn Sep 23, 2023, at 12:16 PM, Patrizio Bekerle ***@***.***> wrote:﻿
Doesn't sound like a bug, more like a missing feature.
But I'm not sure how to detect all Markdown syntax reliably when they are not marked as, e.g. code block in the enex...

A bash comment in the input is about 1/2 way down the note, a python cli prompt is the last line.

In Evernote everything is HTML, it's hard to put that back into Markdown.
Suggestions?

**Comment by pbek** [comment]
Hm, there isn't really a documentation for the Evernote import yet, beside https://www.qownnotes.org/getting-started/importing-notes.html#evernote. Do you care to start a more elaborate one to document your experiences?
