### ISSUE TITLE
[SUPPORT] Clicking on the note tab bar fails to locate notes in note subfolders panel after doing a notes search

### ISSUE THREAD

**Issue by davuses** [pbek/QOwnNotes#2861]
#### Question

If multiple note tabs are opened in QOwnNotes, the app will locate the corresponding note in both _note subfolders panel_ and _note list panel_ when switching between notes tabs. This could be done either by clicking on the note tab bar or using the keyboard  shortcut.

However, after performing a note searching (Find notes in all tags / subfolders via shortcut `Alt+F`), switching between  note tabs no longer maintains the note's location in the _note subfolders panel_ . I have to click on one of the subfolders in _note subfolders panel_ to bring back this functionality.

This issue is also observed after selecting the _All notes_ folder in the _note subfolders panel_.

I wonder if this issue is expected?

#### Expected Behavior:

The expected behavior is that, even after performing a note search or selecting the "All notes" folder in the _note subfolders panel_, clicking on a note tab bar  should continue to locate the corresponding note in the note subfolder panel

#### Steps to Reproduce

1.  Open multiple note tabs in QOwnNotes.
2.  Perform a note search using the "Find notes in all tags / subfolders" shortcut Alt+F.
3.  Switch between note tabs.
4.  Observe that the note's location in the note subfolder panel is not maintained.
5.  Additionally, observe the same behavior when selecting the "All notes" folder in the note subfolder panel.

**Comment by pbek** [comment]
> The expected behavior is that, even after performing a note search or selecting the "All notes" folder in the note subfolders panel, clicking on a note tab bar should continue to locate the corresponding note in the note subfolder panel

Are we really talking about the note subfolder panel? There are no notes located in that panel. Or am I misunderstanding something?

If you are talking about the note list...
The note list can only show and highlight notes that are in the note list. If you search for notes and the notes opened in tabs are not in the search results, then they can't be shown in the note list.

**Comment by davuses** [comment]
@pbek Actually it's the parent folder of the opened note that is located in subfolders panel, sorry for the confusion. 

Here's an example screenshot : 

<img width="264" alt="image" src="https://github.com/pbek/QOwnNotes/assets/54793121/599621bf-da3a-477a-af21-c1d08dc1eeb5">

**Comment by pbek** [comment]
Then can you then please reframe what the issue was and why you would expect to happen?

**Comment by davuses** [comment]
> Then can you then please reframe what the issue was and why you would expect to happen?

What I expect to happen is that, when switching between notes tab, the parent folder of the note will be located in the subfolders panel. As I described in the issue, the is not happening after doing a notes search via shortcut Alt+F

**Comment by pbek** [comment]
But that would affect the search, wouldn't it?

And the question is more general: Should switching to another note tab set the current note subfolder to the subfolder of the note of the tab.

That would have implications, for example, where a new note is created or what is shown in the note list.

**Comment by davuses** [comment]
> And the question is more general: Should switching to another note tab set the current note subfolder to the subfolder of the note of the tab.

This is actually how QownNotes behaves currently. When you switch to another note tab, the software automatically sets the current note subfolder to match the subfolder of the note displayed in the tab.

**Comment by pbek** [comment]
Tricky...
That's the current behavior when a new current note is set:

https://github.com/pbek/QOwnNotes/blob/711e817d2624dec3289a52bbb373f30ab0b36635/src/mainwindow.cpp#L3682-L3686

Searching for notes in all subfolders with `Alt + F` might trigger `_showNotesFromAllNoteSubFolders`.

https://github.com/pbek/QOwnNotes/blob/711e817d2624dec3289a52bbb373f30ab0b36635/src/mainwindow.cpp#L10031-L10044

**Comment by pbek** [comment]
I could overrule that in https://github.com/pbek/QOwnNotes/blob/711e817d2624dec3289a52bbb373f30ab0b36635/src/mainwindow.cpp#L11473.

**Comment by pbek** [comment]
## 23.9.7
- the `All notes` selection in the subfolder panel will now be unset when
  clicking a note tab, so that the subfolder of a note can be selected
  (for [#2861](https://github.com/pbek/QOwnNotes/issues/2861))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by davuses** [comment]
@pbek  I've tested the new release, and it works well for me. Thank you for the update and your efforts in making the software even better!

**Comment by pbek** [comment]
Great, thank you for testing! 😉 
I hope this change makes sense to everyone.

**Comment by dru982** [comment]
I just updated to 23.9.7 and I noticed a change in behaviour.  See below.  Is the new behaviour related to this change and can the behaviour be reverted back?

Previous behaviour:
Two tabs open. TabA and TabB.
TabA is viewing notes in "All notes".
Switch to TabB.
Switch back to TabA.
Subfolders panel still has "All notes" selected.

New behaviour:
Two tabs open. TabA and TabB.
TabA is viewing notes in "All notes".
Switch to TabB.
Switch back to TabA.
Subfolders panel does not have "All notes" selected, instead parent folder of note is selected.

If I'm browsing notes in "All notes" and I change to another tab and back, I would like to continue browsing through "All notes" in the original tab.

**Comment by pbek** [comment]
> I hope this change makes sense to everyone.

@davuses, I guess that counts as "no". Do you have any arguments for your case over @dru982's case?

**Comment by davuses** [comment]
Could we consider making this feature optional? That way, users can choose to enable it if they'd like to keep it.

**Comment by pbek** [comment]
I really dislike adding more "one person likes it different" settings. 😆

**Comment by pbek** [comment]
## 23.10.0
- there now is a setting for the feature to unset the `All notes` selection in
  the subfolder panel when clicking a note tab in the *Panels settings*
  (for [#2861](https://github.com/pbek/QOwnNotes/issues/2861))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by davuses** [comment]
@pbek Thank you! Having an option for this feature is fantastic. I do find the new behavior more intuitive because I don't have to click a subfolder every time. I'll test it when I get home.
