### ISSUE TITLE
[SUPPORT] Folders and more

### ISSUE THREAD

**Issue by mpinsley** [pbek/QOwnNotes#2863]
Hi,

I am brand new to QOwnNotes

I downloaded it, and put it on my windows computer

One of the things I wanted to do is to bring in my notes from Evernote. I exported Evernote and then imported into QNote

I didn't realize that I should have created a new folder for the Evernote notes, so now they are all in the default folder

1. I tried created a new folder, but I am not seeing the folder on any of the left hand menus
2. I do see the folder in a dropdown, but it doesn't seem to do anything
3. How do I create folders and subfolders in order to put my Evernotebooks into a similar structure.
4. When exporting an importing the next evernote note book. Should I first create the folder, 
5. If so, how do I import into that new folder

Here is what I see
https://capture.dropbox.com/4rtqchNRnLODx8Eq

The second set of questions
1. The dropdowns do not seem to stay open when I click on them the close before I can make a selection
2. Is there a way to change that?

The third set of questions
1. Is there a way to show line numbers, similar to what is on GitHub
2. If so how do I turn that on

The fourth set,
1. If I want to download documents from github or have github as my main repository
2. What do I need to do
3. I don't currently use Git  I am assuming I would have to down load that?
6. If so is there a video you could recommend

Thanks

**Comment by pbek** [comment]
> I didn't realize that I should have created a new folder for the Evernote notes, so now they are all in the default folder

Yes, all notes are imported to the note folder, but you can just right-click them and move them to another subfolder, image and attachment links will be adapted.

**Comment by pbek** [comment]
> The dropdowns do not seem to stay open when I click on them the close before I can make a selection

please elaborate on that

> Is there a way to show line numbers, similar to what is on GitHub

yes, search for "line numbers" in the settings

> If I want to download documents from github or have github as my main repository

I'm not sure on what do you want to achieve? Pushing all your notes to git? The note folder is just a folder with Markdown files, you can do that with git tools?
And you can download and copy other Markdown files from GitHub as much as you like...

**Comment by mpinsley** [comment]
Thank you. I put together a short video to show you what I mean by the drop down and the folders

https://www.loom.com/share/27a408278c4541a783098466f4702f10?sid=8f6fe055-d3cb-44bb-a1e5-1be6eee12322

On the git, I have never used it before. So maybe I am just asking a silly question. I saw there was some set up in the tool, but I am not sure what I am setting up. I use github to keep documents. I am not a programmer. I am just using it a a depository of markdown files

So is there something I should be doing there?


> > The dropdowns do not seem to stay open when I click on them the close before I can make a selection
> 
> please elaborate on that
> 
> > Is there a way to show line numbers, similar to what is on GitHub
> 
> yes, search for "line numbers" in the settings
> 
> > If I want to download documents from github or have github as my main repository
> 
> I'm not sure on what do you want to achieve? Pushing all your notes to git? The note folder is just a folder with Markdown files, you can do that with git tools? And you can download and copy other Markdown files from GitHub as much as you lik

**Comment by mpinsley** [comment]
Also, please note in the video, I don't have this section
https://capture.dropbox.com/mQCIQhWccwvknAR2

**Comment by pbek** [comment]
> Also, please note in the video, I don't have this section

You need to turn on subfolders for your note folder. Best search for "subfolder" in the settings.

**Comment by pbek** [comment]
> https://www.loom.com/share/27a408278c4541a783098466f4702f10?sid=8f6fe055-d3cb-44bb-a1e5-1be6eee12322

Hm, are you (or your mouse) double-clicking on the drop-boxes? Drop-boxes don't close on themselves, usually.
Are you sure you that you are actually using different folders in your two note folders? You never shared your settings dump in this issue...

Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.

> On the git, I have never used it before. So maybe I am just asking a silly question. I saw there was some set up in the tool, but I am not sure what I am setting up. I use github to keep documents. I am not a programmer. I am just using it a a depository of markdown files

Git is not easy to understand. Are you sure you want to go through all the troubles learning it? 😁  Best use Dropbox to sync your note files to, you already seem to use Dropbox.

**Comment by mpinsley** [comment]
Ok I must admit,  I must be an idiot, as I searched. I saw the three areas where subfolders are. But I can not figure out how to create a folder and a subfolder.

Did I turn this on correctly? It said experimental

https://capture.dropbox.com/Qhjrk7jdlOvRDdax


I am okay using Dropbox, but what I like about github is the ability to go backwards in time. Does dropbox have that facility? For now, I can live without it.

Here is the dump. I am not double-clicking on the mouse. . For whatever reason, it keeps closing

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed Sep 27 23:05:15 2023`
**Version**: `23.9.7`
**Build date**: `Sep 24 2023`
**Build number**: `1058`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\mpins\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Users\mpins\Google Drive\Applications\Qnotes\QOwnNotes.exe`, `C:\Users\mpins\Google Drive\Applications\Qnotes\QOwnNotes.exe`, `--allow-multiple-instances`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: `en`
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `268`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\mpins\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `C:\Users\mpins\Google Drive\Private\QnotesDocs`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\mpins\Google Drive\Private\QnotesDocs\notes.sqlite`

### Note folder `Race 2023`

**id**: `2`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `C:\Users\mpins\Google Drive\Private\QnotesDocs`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**allowDifferentNoteFileName**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\mpins\Google Drive\Private\QnotesDocs\notes.sqlite`

## Cloud connections

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

## Enabled scripts

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `true`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**EvernoteImport/AttachmentImportCheckBoxChecked** (QString): `true`
**EvernoteImport/ImageImportCheckBoxChecked** (QString): `true`
**EvernoteImport/MetaDataUnCheckedList** (QStringList): `, `
**EvernoteImportDialog/geometry** (QByteArray): `<binary data>`
**FileDialog/LastPath** (QString): `C:/Users/mpins/Downloads`
**FileDialog/LastPath-Evernote Import** (QString): `C:/Users/mpins/Downloads`
**FileDialog/LastPath-ImportTextFiles** (QString): `C:/Users/mpins/Downloads`
**FileDialog/LastPath-NoteMarkdownExport** (QString): `C:/Users/mpins/Downloads`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2023-09-27T22:57:13.616`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `30`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,7.8,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (int): `600`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**NoteFolder-1/NoteTabNameList** (QStringList): `Activist groups and others for race 1 2023-09-26T17_49_30, huge`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `, `
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteFolder-2/allowDifferentNoteFileName** (QString): `true`
**NoteHistory-1** (QVariantList): `<variant list with 37 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `36`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**autoReadOnlyMode** (QString): `false`
**autoReadOnlyModeTimeout** (int): `30`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `true`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): `en`
**internalIconTheme** (QString): `false`
**itemHeight** (int): `18`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `true`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `C:/Users/mpins/Google Drive/Private/QnotesDocs`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2023-09-27T22.52.38, Mark, Legal Defamation, LVHN Update Board (3)`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**startInReadOnlyMode** (QString): `false`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (int): `22222`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\mpins\AppData\Roaming`
**asl.log**: `Destination=file`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `LAPTOP-76BMI4HN`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**EFC_8376**: `1`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\mpins`
**LOCALAPPDATA**: `C:\Users\mpins\AppData\Local`
**LOGONSERVER**: `\\LAPTOP-76BMI4HN`
**NUMBER_OF_PROCESSORS**: `8`
**OneDrive**: `C:\Users\mpins\OneDrive`
**OneDriveConsumer**: `C:\Users\mpins\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\Pandoc\;C:\Program Files\MiKTeX\miktex\bin\x64\;C:\Program Files\MiKTeX\miktex\bin\;C:\Users\mpins\AppData\Local\Microsoft\WindowsApps;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 140 Stepping 1, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `8c01`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\mpins\AppData\Local\Temp`
**TMP**: `C:\Users\mpins\AppData\Local\Temp`
**USERDOMAIN**: `LAPTOP-76BMI4HN`
**USERDOMAIN_ROAMINGPROFILE**: `LAPTOP-76BMI4HN`
**USERNAME**: `mpins`
**USERPROFILE**: `C:\Users\mpins`
**windir**: `C:\WINDOWS`
**ZES_ENABLE_SYSMAN**: `1`
**__COMPAT_LAYER**: `DetectorsAppHealth`

**Comment by pbek** [comment]
> Did I turn this on correctly? It said experimental

subfolders are not experimental, just the feature to show subfolders and notes in the same panel

>  isShowSubfolders: yes

your settings say you have turned them on

> Did I turn this on correctly?

yes

> Here is the dump. I am not double-clicking on the mouse. . For whatever reason, it keeps closing

I'm sorry, I've never seen this and I can't explain it 😅 

> I am okay using Dropbox, but what I like about github is the ability to go backwards in time. Does dropbox have that facility? For now, I can live without it.

I'm pretty sure Dropbox has file versioning. Nextcloud has (and the versioning of Nextcloud is supported by QOwnNotes)!
Git works pretty differently, the versioning is not file-based, it's repository-based. And you need to take care of conflicts yourself!

**Comment by mpinsley** [comment]
Ok so if I have subfolders and folders turned on how do i use them. I want to have the subfolders first so that I can import my Evernote files

https://capture.dropbox.com/7v7eUqV0czHJvZDi

**Comment by pbek** [comment]
There is no subfolder import in the Evernote importer, if that was the question... I don't know how folders are implemented in Evernote.

**Comment by mpinsley** [comment]
Apologies for any confusion earlier. To clarify my query: I'm capable of exporting a folder individually from Evernote. My intention is to subsequently establish a corresponding folder in QownNotes where I can import all contents originally housed in the Evernote folder.

However, I’m encountering challenges with establishing and organizing folders and subfolders within QownNotes. I've provided a visual representation of my dilemma in a video linked at the end of our previous conversation thread. If you could take a moment to review this, it illustrates the specific issues I’m experiencing. Your insights on how to efficiently structure and import my folders from Evernote to QownNotes would be immensely appreciated.

**Comment by pbek** [comment]
The Evernote import imports the notes to the note folder itself. You need to move them to note subfolders after the import. does that answer your question

**Comment by mpinsley** [comment]
Ok so just to be clear
1. There is no way to pull evernote file directly into a sub-folder, I must first import them into the main folder and then move them to the sub folder?
2. If 1 is true, is there a way to sort by import date so i don't have to make sure I am not importing notes that I want to keep in th remain folder
3.  Can you explain these 4 section. I really don't understand number 4 as when I change the dropdown nothing seems to happen
https://capture.dropbox.com/pYEFk3NEuM5Rlgh5

**Comment by pbek** [comment]
> There is no way to pull evernote file directly into a sub-folder, I must first import them into the main folder and then move them to the sub folder?


Yes, I just tested. But I can change it, so it would import into the current sub-folder.

> Can you explain these 4 section. I really don't understand number 4 as when I change the dropdown nothing seems to happen https://capture.dropbox.com/pYEFk3NEuM5Rlgh5

You have setup two note folders, but they point to the same physical folder `localPath: C:\Users\mpins\Google Drive\Private\QnotesDocs`.

**Comment by pbek** [comment]
## 23.10.0
- notes are now imported to the current note subfolder in the Evernote and Joplin
  import instead of the root folder (for [#2863](https://github.com/pbek/QOwnNotes/issues/2863))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
