### ISSUE TITLE
[FEATURE] Search for Notes (Folders should be open to show found notes)

### ISSUE THREAD

**Issue by ElfQrin** [pbek/QOwnNotes#2868]
When you search for notes, the notes located inside a folder aren't shown, only the closed folders that contains them are shown. Such folders should be open and list the corresponding notes inside.

**Comment by pbek** [comment]
Can you please describe what you expected, what the actual behavior was, and step by step what you did?

**Comment by ElfQrin** [comment]
#### Steps to reproduce

- Click on Search or create note.
- Enter a string of text.

#### Expected behaviour

- A list of notes matching the searched string are listed in the note panel.
- If a note is contained inside a folder/subfolder, it's shown under its path with all folders open.

#### Actual behaviour
- A list of notes matching the searched string, and closed folders containing notes matching the searched string, are listed in the note panel.

**Comment by pbek** [comment]
Are you maybe also talking about #2844? I can't reproduce this.

**Comment by ElfQrin** [comment]
No, it's not a duplicate of #2844 .

I'm adding a screenshot.

![qownnotes_search_for_note_2023-10-03](https://github.com/pbek/QOwnNotes/assets/18285483/f534ee98-2f7c-4658-92b3-d06c3dd883c5)

As you can see, I'm looking for the string "character".

The Note panel now correctly shows all the notes containing the matching string, and the folders containing notes with the matching string, but such folders are closed, so that you can't see the actual notes. I expect that all matching folders and subfolders are open to reveal the matching notes inside.
Also, the folder "Refs" that contains 0 matching notes it shouldn't be listed.

**Comment by pbek** [comment]
Why should the note search also search the subfolders?
They have their own search bar (that you have turned off) 

![image](https://github.com/pbek/QOwnNotes/assets/1798101/0672e760-bff5-411f-b834-f06e52ba6e41)

Or are you talking about https://github.com/pbek/QOwnNotes/issues/790? You haven't shared your settings.

**Comment by ElfQrin** [comment]
> Why should the note search also search the subfolders? They have their own search bar (that you have turned off)

I don't know why it should, but as you can see in my screenshot, it already does. Only it doesn't expand subfolders, which is what I'd like it to do.

> Or are you talking about #790? You haven't shared your settings.

That said, while I'm specifically interested on the search function, it may be in fact related to #790 


By the way, not that I'd actually need it, but "Show Subfolder panel" (which I understand is the one in your screenshot) is grayed out in my Window / Panels menu.


I'm attaching my settings.

[Dark_elf.zip](https://github.com/pbek/QOwnNotes/files/12791496/Dark_elf.zip)
[QOwnNotes-settings.zip](https://github.com/pbek/QOwnNotes/files/12791497/QOwnNotes-settings.zip)

**Comment by pbek** [comment]
> noteSubfoldersPanelDisplayAsFullTree=true

Yes, you have. So, best deposit your wishes in #790.

Btw. don't post your settings export! They may contain secrets! Use the dump from the Debug Settings

**Comment by pbek** [comment]
## 26.3.4

- Added more improvements to the note list search and filtering in note tree mode
  for [#790](https://github.com/pbek/QOwnNotes/issues/790))
  - In note tree mode, searching in the note list now hides folders that don't
    match and don't contain matching notes in their subtree, while keeping
    parent folders visible for matching note names or note content, and
    expanding visible folders so matching results are uncollapsed
    (for [#2868](https://github.com/pbek/QOwnNotes/issues/2868))
  - In note tree mode, note and folder search now always searches across all
    folders instead of only the currently selected folder
    (for [#2868](https://github.com/pbek/QOwnNotes/issues/2868))
  - Fixed note tree mode not refreshing the note/folder tree after selecting a
    folder cleared the search text, so hidden items are now shown again
    (for [#2868](https://github.com/pbek/QOwnNotes/issues/2868))
