### ISSUE TITLE
Disable menu bar option

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#287]
I've already asked that for status bar. Now it's menu bar turn.

Most KDE apps allow to disable menu bar and I'm used to having it off to gain some vertical space.

Could you implement toggling menu bar with a keyboard shortcut.
<kbd>Control</kbd>+ <kbd>M</kbd> is the shortcut KDE apps use.

**Comment by pbek** [comment]
When using Unity (that is using no menu bar in the app) none of the shortcuts worked any more because I guess they are bound to the visibility of their action items somewhere (seems like a Qt thing). That was also the reason why I move so much stuff to the toolbar, so that at least there the action was "visible"...

I don't know what will happen if I turn of the menu bar.

**Comment by pbek** [comment]
I tested it, shortcuts don't work if they are not present in the toolbar when the menu bar is disabled...

**Comment by Maboroshy** [comment]
Pity. Interesting how KDE devs got it running.

**Comment by pbek** [comment]
That's an excellent question, please let me know if you find something!

**Comment by Maboroshy** [comment]
Ok, you've asked for this yourself. :sunglasses: 

1) You can hide menu like you did for distraction free mode - by setting it's size to 0 without hiding it.

2) Looks like key you bind shortcuts to QMenu widget. That's why when widget is gone it takes its shortcuts as well. 

You can let Qshortcuts deal with them instead of Qmenu, so they won't be gone with Qmenu. 

Bad thing is to have shortcuts shown in menus like they are now may require some extra work with overrides.

**Comment by pbek** [comment]
1) Oh, so **I** already found a workaround for that. How nice. :) Thanks a lot for reminding me! :D 
2) Qt binds shortcuts to QAction items, that are added to QMenu item. I can't get around that. Like you said, shortcuts wouldn't be shown in menus and the kind.

But I could hide the menu by setting the width to 0... 
Too bad that still doesn't work in Unity, where the menu is really hidden...

**Comment by Maboroshy** [comment]
Maybe this will help:
https://forum.qt.io/topic/58093/does-shortcut-context-qt-widgetshortcut-action-in-menu-disable-shortcut 
http://stackoverflow.com/questions/1894395/in-qt-how-to-show-keyboard-shortcuts-in-menu-but-disable-them

**Comment by pbek** [comment]
...you mean to be really able to have the menu invisible (instead of just hiding it) for e.g. Unity?

**Comment by Maboroshy** [comment]
Yep.

**Comment by pbek** [comment]
I wonder if all KDE apps (or the framework) has to do the same to make shortcuts work in Unity...

**Comment by Maboroshy** [comment]
That's hard to tell for me. Their code is quite spread. Maybe they have kind of a shared library for that.

**Comment by pbek** [comment]
2) I now made a workaround for #288

**Comment by pbek** [comment]
## 16.08.9
- all **shortcuts** from the main menu should now also **work** if your
  desktop environment doesn't show the main menu bar (like **Unity** does)
- there now is a new shortcut <kbd>Ctrl</kbd> + <kbd>⇧</kbd> + 
  <kbd>M</kbd> to **hide the main menu bar** 
  - if the menu bar is hidden a new button will be added to the window 
    toolbar to show the main menu bar again

There now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment]
No new version in AUR yet.

**Comment by pbek** [comment]
AUR didn't let me to access the repository. :( public key error

**Comment by pbek** [comment]
I posted my troubles in the forum.

https://bbs.archlinux.org/viewtopic.php?pid=1647364

Help is appreciated...

**Comment by pbek** [comment]
Seems like it's a problem of AUR, there are others with the same issue... You could always use the binary OBS repository meanwhile. ;)

**Comment by Maboroshy** [comment]
This whole issue made me add your repository at last. No more compiling!

I've tested the feature and it works good. The app now looks cool and minimalistic like other apps on my machine do. 

With new key resign feature I've put everything I need to F-keys and disabled the toolbar altogether. Good the menu toggle can be rebind too. I've put it to <kbd>Esc</kbd>.

Using toolbar for toggling however can be pain:
I've switch off the menu and did some work. Now I want to get to settings. I push the button on toolbar and it's all good. I've changed the setup and won't need the menu for another month or two. How do I switch it off? Oh, I've used the button on the toolbar. No, it's not there. Ok where could the switch of thing be...

And since, like I said, I will use the menu next time after a month, I will get over all of it again, I won't really become used to it. Good thing I have <kbd>Esc</kbd> key for that!

By the way don't know if it's a bug or not but there is <kbd>Control</kbd>+<kbd>+</kbd> keys for making font larger. 

The fact is there's no simple <kbd>+</kbd> since it's a <kbd>=</kbd> key. <kbd>+</kbd> is <kbd>Shift</kbd>+<kbd>=</kbd> really. 
So it's a <kbd>Control</kbd>+<kbd>Shift</kbd>+<kbd>=</kbd> for a larger font. 

Good thing now can reassign it to <kbd>Control</kbd>+<kbd>=</kbd>

**Comment by Maboroshy** [comment]
I've didn't think it could be any cooler but it can. 

I have a mouse with some extra buttons. But Linux don't really like too much buttons, so I've bind them to keyboard shortcuts. Like <kbd>Control</kbd>+<kbd>W</kbd> to close tabs in browser. 

And I can now bind this keys to QOwnNotes actions. So I use the button I close tabs with to toggle edit/render now. These latest feature are very cool!

**Comment by pbek** [comment]
Soon you will buy a gaming keyboard and mouse just to have more shortcuts for QOwnNotes. :)

**Comment by ajashton** [comment]
Could the keyboard shortcut be a toggle? I don't think there's a way to turn the menu back on if the toolbar is also hidden.

**Comment by Maboroshy** [comment]
It's a toggle actually. I've binded it to <kbd>Esc</kbd> and use it as a toggle with no toolbar enabled.

**Comment by ajashton** [comment]
Strange.. it wasn't working for me, but after restarting the application it's working fine. Nevermind.
