### ISSUE TITLE
[EDITOR SCHEMA] Dark Elf

### ISSUE THREAD

**Issue by ElfQrin** [pbek/QOwnNotes#2870]
#### Schema name
Dark Elf

#### Schema file

[Dark_elf.zip](https://github.com/pbek/QOwnNotes/files/12783080/Dark_elf.zip)
[QOwnNotes-settings.zip](https://github.com/pbek/QOwnNotes/files/12783081/QOwnNotes-settings.zip)
![QOwnNotes_schema_DarkElf_2023](https://github.com/pbek/QOwnNotes/assets/18285483/604725ec-7431-4524-b910-80f021b18c50)

**Comment by ElfQrin** [comment]
It's still a dark theme. Some colors are different from the default dark theme, and some font size are smaller (Headers).

Also, I don't know if it counts, the panel layout may be useful for someone.

**Comment by pbek** [comment]
> It's still a dark theme. Some colors are different from the default dark theme, and some font size are smaller (Headers).

The changes are just minimal, but thank you for bothering. 😁 

> Also, I don't know if it counts, the panel layout may be useful for someone.

Unfortunately, you can't really import a panel layout.
