### ISSUE TITLE
[Q] How can I always search for sentences exactly how I type them

### ISSUE THREAD

**Issue by FunkeymonkeyTTR** [pbek/QOwnNotes#2871]
#### General question

Currently if I try search for multiple words separated by a space it will try search for each individual word in a document, I need to change this default behaviour so it searches for the exact sentence I type, it bothers the hell out of me but I don't know what to look for. I know you can start a search with some punctuation to enable this but I always forget what characters to use so I really need to change the default

**Comment by pbek** [comment]
This is what is supported: https://www.qownnotes.org/getting-started/searching.html
