### ISSUE TITLE
[Q] Is there a setting to enable mixed text directions (RTL and LTR) for the preview panel?

### ISSUE THREAD

**Issue by sikmo** [pbek/QOwnNotes#2873]
I know there is an option to switch the whole preview panel to RTL mode, but is there a way for it to have mixed directions? Basically, if the text in a paragraph starts with a RTL language character (e.g Arabic or Hebrew), that paragraph gets displayed as RTL in the preview panel?  
  
AS a note, the editor panel handles mixed directions well. Also, surrounding the paragraph with \<div dir="rtl"> seems to work and the preview handles the mixed directions well, but can this be done automatically?

**Comment by pbek** [comment]
No, sorry. It's exactly the same as with HTML and CSS, the `dir="rtl"` needs to be set. 😬
