### ISSUE TITLE
[SUPPORT] 

### ISSUE THREAD

**Issue by jynxf** [pbek/QOwnNotes#2879]
#### Question
I get a database connection error when starting the application, or when changing settings

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Oct 17 12:21:46 2023`
**Version**: `23.10.1`
**Build date**: `Oct 12 2023`
**Build number**: `1060`
**Platform**: `linux`
**Operating System**: `KDE Flatpak runtime`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub`
**Qt Version (build)**: `5.15.10`
**Qt Version (runtime)**: `5.15.10`
**Portable mode**: `no`
**Settings path / key**: `/home/john/.var/app/org.qownnotes.QOwnNotes/config/PBE/QOwnNotes.conf`
**Application database path**: `/home/john/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_GB`
**Locale (interface)**: *empty*
**Primary screen resolution**: `3440x1440`
**Icon theme**: `breeze`
**Notes in current note folder**: `165`
**Calendar items**: `40`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://awesempro.dedyn.io`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `26.0.5.1`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_AU, en_BS, en_BZ, en_CA, en_GB, en_GH, en_IE, en_IN, en_JM, en_MW, en_NA, en_NZ, en_PH, en_TT, en_US, en_ZA, en_ZW`
**Language names**: `Australian English (Australia), English (Bahamas), English (Belize), Canadian English (Canada), British English (United Kingdom), English (Ghana), English (Ireland), English (India), English (Jamaica), English (Malawi), English (Namibia), English (New Zealand), English (Philippines), English (Trinidad & Tobago), American English (United States), English (South Africa), English (Zimbabwe)`
**Application dictionaries path**: `/home/john/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/run/user/1001/doc/b277bf44/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: `Dev`
**database file**: `/run/user/1001/doc/b277bf44/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://awesempro.dedyn.io`
**username**: `john`
**accountId**: `john`
**Nextcloud Deck boardId**: `0`
**Nextcloud Deck stackId**: `0`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**CloudConnection-1/nextcloudDeckEnabled** (QString): `true`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (bool): `true`
**Editor/showLineNumbers** (bool): `false`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `true`
**FileDialog/LastPath** (QString): `/run/user/1001/doc/c8eb9474`
**FileDialog/LastPath-InsertImage** (QString): `/run/user/1001/doc/c8eb9474`
**ImageDialog/disableCopying** (QString): `true`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2023-10-17T12:18:39.219`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Noto Sans Mono,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Noto Sans Mono,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.refreshDebounceTime** (int): `600`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/move-notes** (QString): `16384`
**NoteFolder-1/NoteTabNameList**: *empty*
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList**: *empty*
**NoteHistory-1** (QVariantList): `<variant list with 15 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `14`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `true`
**StartHidden** (bool): `false`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `0`
**TodoDialog/showDueTodayItemsOnly** (QString): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Deck: Personal`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**autoReadOnlyMode** (bool): `false`
**autoReadOnlyModeTimeout** (int): `30`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `1`
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `true`
**enableSocketServer** (bool): `true`
**enableWebAppSupport** (bool): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): `yyyy-MM-dd hh:mm`
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (int): `24`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelAutoSelect** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**noteSubfoldersPanelTabsUnsetAllNotesSelection** (bool): `false`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/run/user/1001/doc/b277bf44/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/ignoreNonTodoCalendars** (QString): `true`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Personal, Todo, Online, Dev, Nextcloud, Linux, Deck: Personal, Deck: House, Deck: Garden, Deck: Pension, Deck: Computing, Deck: Stuff, Deck: Opot, Deck: Money`
**ownCloud/todoCalendarEnabledList** (QStringList): `Personal, Todo, Online, Dev, Nextcloud, Linux, Deck: Personal, Deck: House, Deck: Garden, Deck: Pension, Deck: Computing, Deck: Stuff, Deck: Opot, Deck: Money`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://awesempro.dedyn.io/remote.php/dav/calendars/john/personal/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/todo/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/online/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/dev/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/nextcloud/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/linux/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/app-generated--deck--board-1/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/app-generated--deck--board-2/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/app-generated--deck--board-3/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/app-generated--deck--board-4/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/app-generated--deck--board-5/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/app-generated--deck--board-6/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/app-generated--deck--board-7/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/app-generated--deck--board-8/`
**ownCloud/todoCalendarUrlList** (QStringList): `https://awesempro.dedyn.io/remote.php/dav/calendars/john/personal/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/todo/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/online/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/dev/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/nextcloud/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/linux/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/app-generated--deck--board-1/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/app-generated--deck--board-2/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/app-generated--deck--board-3/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/app-generated--deck--board-4/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/app-generated--deck--board-5/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/app-generated--deck--board-6/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/app-generated--deck--board-7/, https://awesempro.dedyn.io/remote.php/dav/calendars/john/app-generated--deck--board-8/`
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `26.0.5.1`
**previousWorkspace** (QString): `796f9F3N5fLS`
**restoreCursorPosition** (bool): `true`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2023-10-17T11.43.02, Note 2023-10-17T11.36.50`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**startInReadOnlyMode** (bool): `false`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (int): `6`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (int): `22222`
**workspace-796f9F3N5fLS/name** (QString): `Minimal`
**workspace-796f9F3N5fLS/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-796f9F3N5fLS/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 796f9F3N5fLS`

## System environment

**XDG_RUNTIME_DIR**: `/run/user/1001`
**container**: `flatpak`
**AT_SPI_BUS_ADDRESS**: `unix:path=/run/flatpak/at-spi-bus`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/flatpak/bus`
**DESKTOP_SESSION**: `plasma`
**FLATPAK_ID**: `org.qownnotes.QOwnNotes`
**FLATPAK_SANDBOX_DIR**: `/home/john/.var/app/org.qownnotes.QOwnNotes/sandbox`
**GDK_CORE_DEVICE_EVENTS**: `1`
**GDMSESSION**: `plasma`
**GDM_LANG**: `en_GB.UTF-8`
**GI_TYPELIB_PATH**: `/app/lib/girepository-1.0`
**GST_PLUGIN_PATH**: `/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0`
**GTK2_RC_FILES**: `/home/john/.gtkrc-2.0-kde4`
**GTK_IM_MODULE**: `gtk-im-context-simple`
**GTK_RC_FILES**: `/etc/gtk/gtkrc:/home/john/.gtkrc:/home/john/.config/gtkrc`
**HOME**: `/home/john`
**IMSETTINGS_INTEGRATE_DESKTOP**: `yes`
**IMSETTINGS_MODULE**: `none`
**INVOCATION_ID**: `2545554d3b414629a8ab5ecab3345e28`
**JOURNAL_STREAM**: `8:31251`
**KDE_APPLICATIONS_AS_SCOPE**: `1`
**KDE_FORK_SLAVES**: `1`
**KDE_FULL_SESSION**: `true`
**KDE_SESSION_UID**: `1001`
**KDE_SESSION_VERSION**: `5`
**LANG**: `en_GB.UTF-8`
**LANGUAGE**: *empty*
**LC_MEASUREMENT**: `C`
**LC_MONETARY**: `fr_FR.UTF-8`
**LD_LIBRARY_PATH**: *empty*
**LOGNAME**: `john`
**MANAGERPID**: `1939`
**PATH**: `/app/bin:/usr/bin`
**PLASMA_USE_QT_SCALING**: `1`
**PS1**: `[📦 $FLATPAK_ID \W]\$ `
**PWD**: `/home/john`
**QML2_IMPORT_PATH**: `/app/lib64/qml:/app/lib/qml`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**QT_IM_MODULE**: `xim`
**QT_PLUGIN_PATH**: `/app/lib64/plugins:/app/lib/plugins:/usr/share/runtime/lib/plugins`
**QT_WAYLAND_FORCE_DPI**: `96`
**SESSION_MANAGER**: `local/unix:@/tmp/.ICE-unix/2416,unix/unix:/tmp/.ICE-unix/2416`
**SHELL**: `/bin/sh`
**SSH_ASKPASS**: `/usr/bin/ksshaskpass`
**SSH_AUTH_SOCK**: `/run/user/1001/ssh-agent.socket`
**SYSTEMD_EXEC_PID**: `2472`
**TERM**: `dumb`
**USER**: `john`
**USERNAME**: `john`
**WAYLAND_DISPLAY**: `wayland-0`
**XAUTHORITY**: `/run/user/1001/xauth_IwwBSI`
**XCURSOR_SIZE**: `24`
**XCURSOR_THEME**: `breeze_cursors`
**XDG_ACTIVATION_TOKEN**: `kwin-23`
**XDG_CACHE_HOME**: `/home/john/.var/app/org.qownnotes.QOwnNotes/cache`
**XDG_CONFIG_DIRS**: `/app/etc/xdg:/etc/xdg`
**XDG_CONFIG_HOME**: `/home/john/.var/app/org.qownnotes.QOwnNotes/config`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_DATA_DIRS**: `/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share`
**XDG_DATA_HOME**: `/home/john/.var/app/org.qownnotes.QOwnNotes/data`
**XDG_MENU_PREFIX**: `kf5-`
**XDG_SEAT**: `seat0`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_DESKTOP**: `plasma`
**XDG_SESSION_ID**: `2`
**XDG_SESSION_TYPE**: `wayland`
**XDG_STATE_HOME**: `/home/john/.var/app/org.qownnotes.QOwnNotes/.local/state`
**XDG_VTNR**: `2`
**XKB_DEFAULT_LAYOUT**: `es`
**XMODIFIERS**: `@im=none`
**__EGL_EXTERNAL_PLATFORM_CONFIG_DIRS**: `/etc/egl/egl_external_platform.d:/usr/lib/x86_64-linux-gnu/GL/egl/egl_external_platform.d:/usr/share/egl/egl_external_platform.d`
**force_s3tc_enable**: `true`

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

[12:18:46] [warning] QSqlDatabasePrivate::database: unable to open database: "unable to open database file Error opening database"
[12:18:46] [warning] QSqlQuery::prepare: database not open
[12:18:46] [warning] noteHasTags : QSqlError("", "Unable to fetch row", "No query")

repeated a lot
</details>

**Comment by pbek** [comment]
Does it work when you clear your settings or try to use a different session?
See https://www.qownnotes.org/getting-started/cli-parameters.html

**Comment by jynxf** [comment]
Thank you for getting back so quickly!

Using a different session worked. This involved choosing a different notes
folder, which I let it create.

I think the reason there was a problem was that the folder I had originally
chosen was a symbolic link. I removed the symbolic link and used an actual
directory, and the problem didn't reoccur. (I did first try to simply
choose the directory linked to, but this was automatically replaced by a
/run path, which wasn't what I wanted.)

I would have preferred to use the symbolic link, as I try to keep data on a
separate device, but it's not a big issue, and everything is now working.

Thanks again

**Comment by pbek** [comment]
There shouldn't be an issue with symlinks. But I'm not sure how Flatpaks are handling this...

**Comment by jynxf** [comment]
I had a look at Flatpak, and it looks like it's simply a permissions
problem.

While the symlink was in my home directory, it pointed to somewhere
outside, which meant that Flatpak wouldn't allow access. (I'm not totally
sure about how this works, as notes were being saved, it was just the
database access that was causing a problem.)

The fix for me is to give Flatpak access to the physical location for
QOwnNotes, and now I can use the symlink:

cd
mkdir /mnt/Data/home/john/Notes/
ln -s /mnt/Data/home/john/Notes/ .
sudo flatpak override org.qownnotes.QOwnNotes
*--filesystem=/mnt/Data/home/john*

I can then choose the Notes folder in my home directory within QOwnNotes.

Thanks for your help with this
John

**Comment by pbek** [comment]
Ah, great!
