### ISSUE TITLE
Keyboard shortcuts only work when toolbar is visible

### ISSUE THREAD

**Issue by dwu** [pbek/QOwnNotes#288]
It seems that since the configurable keyboard shortcuts feature was introduced (which is great, by the way) keyboard shortcuts only work when the toolbar is visible.

Tested on 16.08.8 on Linux.

**Comment by pbek** [comment]
Thank you for your report and your kind words!

Which window manager are you using?

When using Unity (that is using no menu bar in the app) none of the shortcuts worked any more because I guess they are bound to the visibility of their action items somewhere (seems like a Qt thing). That was also the reason why I move so much stuff to the toolbar, so that at least there the action was "visible"...

Did it really work before the new configurable shortcuts were introduced?

**Comment by dwu** [comment]
You're right. Thanks for the hint!

I've recently switched to Unity on my laptop which happened roughly at the same time as the customizable keyboard settings was introduced.

Removing the global application menu for QT applications solves the issue.

**Comment by pbek** [comment]
> Removing the global application menu for QT applications solves the issue

What do you mean by that? Is there anything I can do? I'd love to...

**Comment by pbek** [comment]
Ah, you meant removing it in Unity... I need a fix where the shortcuts still work when no menu bar and no toolbar is present. :)

**Comment by dwu** [comment]
Yes, that would be the perfect solution. However, working around the issue by disabling Unity's global menu for QT applications is perfectly fine... at least for me. Thanks for the quick response!

**Comment by pbek** [comment]
If I find a solution I'll let you know. Of course you are welcome to research yourself and let me know. There must be a way. I think KDE made their menu bar also turn-off-able...

**Comment by pbek** [comment]
## 16.08.9
- all shortcuts from the main menu should now also work if your desktop
  environment doesn't show the main menu bar (like Unity does)

@dwu, could you please test that when the new version comes out.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by dwu** [comment]
Tested on Ubuntu 16.04.1 with Unity. Works perfectly. Thanks for the incredibly quick fix! :)

For future reference, the issue with keyboard shortcuts for QT applications not working in Unity is due to appmenu-qt5 automatically hiding the original QMenuBar and was [reported at Ubuntu's bugtracker](https://bugs.launchpad.net/appmenu-qt5/+bug/1380702) years ago (more details in comments [#6](https://bugs.launchpad.net/appmenu-qt5/+bug/1380702/comments/6) and [#8](https://bugs.launchpad.net/appmenu-qt5/+bug/1380702/comments/8)). It's a pity they still continue to install and enable appmenu-qt5 by default.

**Comment by pbek** [comment]
Oh man, that's really a pitty... Thank you for letting me know!
