### ISSUE TITLE
[FEATURE] Center preview (like in distraction-free mode)

### ISSUE THREAD

**Issue by mrvruj** [pbek/QOwnNotes#2882]
Hi, I was wondering if there was an easy way to have centered text for previewing markdown, much like how ctrl-shift-d shows a centered editor panel. Or perhaps it would be easier to just have a way to toggle between editor and preview in distraction-free mode? 

Thank you for creating such a wonderful program -- truly has met all of my notetaking needs. Not sure how to put a bounty on this request (or if those are even allowed), but more than happy to put 20$ down for it.

**Comment by pbek** [comment]
Thank you for your kind words...

I'm not sure what you mean by "centered text for previewing markdown", like a fixed size of the content of the preview?
You can play with the preview CSS styling if you want to. There is a script in the script repository to do that...

**Comment by mrvruj** [comment]
I will take a look at the scripts, thanks for the tip.

[Here is an illustration of what I mean.](https://imgur.com/a/ZfY78nF)

The first screencap is distraction-free mode, which by default is an editor. The second screencap is a preview panel with nothing else. I would like the preview to be centered in the same way that the editor is centered in distraction-free mode. Hopefully I explained that well.

**Comment by pbek** [comment]
This doesn't seem to do anything. Maybe some other styling works...

```css
body.preview { max-width: 100px; }
```

**Comment by mrvruj** [comment]
I will continue to play with it. Do you know where to find the .css for the distraction-free mode? Maybe that will give me some hints. 

Thanks for the really prompt replies!

**Comment by pbek** [comment]
Yes, the editor and preview work complety different.

**Comment by mrvruj** [comment]
I suppose I can live without it. It is not a big deal and probably too much headache for such a small feature. If you figure out an easy way to get it done, however, I would much appreciate. Donated 10$ via PayPal -- cheers!

**Comment by pbek** [comment]
Thank you for your donation!

There are other CSS styles you can try to apply to the `body`, like `padding` and `margin`.
And with https://www.qownnotes.org/scripting/hooks.html#notetomarkdownhtmlhook you can directly change the HTML of the preview to get the size down to where you want to.
