### ISSUE TITLE
[FEATURE]  Non-markdown mode

### ISSUE THREAD

**Issue by mercifulboss** [pbek/QOwnNotes#2883]
#### Is your feature request related to a problem? Please describe.
I am not big into markdown but I need a well organized app for research projects/thesis papers and there is no alternative to scrivener on linux that has the same level of organization. Admittedly it can be run through wine but its annoying and I'd prefer something native.

Also, sometimes I'm in a hurry and don't want my text to look messy with all the markdown. In short it would be nice to see a "non markdown mode".

#### Describe the solution you'd like
I'd like a "non-markdown mode" where markdown is turned off and the program acts like libreoffice/MS word in terms of its word processing capabilities (highlighting, underlining, changing font, bolding, size, etc) without using markdown while keeping every other feature of the app.

Would this be possible?

**Comment by pbek** [comment]
In short...
Yes, you can turn off Markdown in the settings (but for me, Markdown is the way that my notes don't look messy)
No, QOwnNotes does support WYSIWYG and most likely never will (on purpose).

**Comment by mercifulboss** [comment]
> In short... Yes, you can turn off Markdown in the settings (but for me, Markdown is the way that my notes don't look messy) No, QOwnNotes does support WYSIWYG and most likely never will (on purpose).

Hello,

Thank you for your reply. Why will QOwnNotes never support WYSIWYG? It could be quite useful feature for students that just want to quickly add and format notes for assignments and stuff :)

**Comment by pbek** [comment]
See https://github.com/pbek/QOwnNotes/issues/909 and others. 😁
