### ISSUE TITLE
[FEATURE] spaces in the name of the note being respected and not changed for "-"

### ISSUE THREAD

**Issue by moshpirit** [pbek/QOwnNotes#2885]
#### Is your feature request related to a problem? Please describe.
1. We cannot use [[connectors]] from notes made in other editors like Logseq, because they use spaces, QON doesn't, so when I try to open a page "this is a named page", it creates another one called "this-is-a-named-page" instead. That's annoying.
2. If we want spaces we need to manually rename them, which is, once again, annoying.
3. it looks way much better with spaces, and aesthetics are important for software that is supposed to be used daily.

#### Describe the solution you'd like
include spaces as a valid option for the names of the notes created with QON.

**Comment by pbek** [comment]
There is https://www.qownnotes.org/scripting/hooks.html#handlenotetextfilenamehook, where you can control the filename of the note.

(sorry, I thought I have already commented on this yesterday)

**Comment by moshpirit** [comment]
Hi, thanks @pbek for replying! I've just seen your comment. I'm not sure of how this link can help me with my question, maybe it is too technical for me.

**Comment by pbek** [comment]
Means you can (only) change that behavior with help of the scripting engine. 😉
