### ISSUE TITLE
[FEATURE] recurring TODOs

### ISSUE THREAD

**Issue by cip123** [pbek/QOwnNotes#2891]
#### Describe the solution you'd like
I think it would be useful to schedule recurring tasks. I would like to be reminded to create invoices every 1st of the month for example.

**Comment by pbek** [comment]
To my knowledge, CalDAV (what QOwnNotes is using as backend for todo lists) can't do that for todo items. Nextcloud Tasks can't do it either, nor can Nextcloud Deck.

**Comment by pbek** [comment]
You can only do that for "real" Calendar items via CalDAV.
