### ISSUE TITLE
[SUPPORT] Questions re flatpak version

### ISSUE THREAD

**Issue by wpfan1000** [pbek/QOwnNotes#2892]
Hi I would like to use flatpak to install QOwnNotes 
But I notice at:
https://flathub.org/apps/org.qownnotes.QOwnNotes
That the app is not Verified by flathub
The concern then becomes that the version of QOwnNotes on flathub is a fork and the code may have been messed with and not safe.
Could you please:
- Let me know if you consider the flatpak version as being safe
- Consider working with flathub to get the flatpak version verified
Thanks ahead of time

**Comment by pbek** [comment]
Unfortunately I can't apply for verification, because I didn't initially put the app on Flathub...

**Comment by pbek** [comment]
Best open an issue on https://github.com/flathub/org.qownnotes.QOwnNotes/issues directly.

**Comment by wpfan1000** [comment]
Thank you very much for replying so quickly and letting me know flatpak pulls directly from github repo :)

**Comment by wpfan1000** [comment]
I did see after I posted here that you prefer flatpak issues to be posted with flathub - sorry about that
