### ISSUE TITLE
[BUG] Cannot dock floating window on Fedora (Flatpak)

### ISSUE THREAD

**Issue by bgoodmansf** [pbek/QOwnNotes#2894]
QOwnNotes version 23.10.1 (Flatpak)
Fedora 38

After un-docking the Note Tags panel, it is not possible to re-dock the panel.

I do not see this problem running on Windows 11. Only on Fedora 38.

#### Expected behaviour
Be able to dock the Note Tags panel.

#### Actual behaviour
Main window does not allow re-dock anywhere.

#### Steps to reproduce
Enable Note Tags panel. Drag panel out of docked position. Drag to edge of main window.

**Comment by pbek** [comment]
Is this something like #2815?
I've not really a way to test the flatpak, if that's a flatpak specific issue then it would be best to report it on https://github.com/flathub/org.qownnotes.QOwnNotes/issues.

**Comment by bgoodmansf** [comment]
Yes, I think it is identical to #2815. (I didn't see that because it had been closed)

I was using a Wayland session. When I tried with X11, it seemed to work fine. So I suspect this is a Wayland issue rather than a Flatpak issue.

**Comment by pbek** [comment]
Must be a Qt thing with Wayland then I guess...

**Comment by xorander00** [comment]
I'm running into this issue too on Hyprland. It's almost certainly a Wayland/XWayland issue. Messing around with window rules to see if there's a workaround for this.  
  
It would be nice though to be able to right-click a an undocked panel and have an option to re-dock it in the main window. Though this doesn't really solve the issue of how to handle dragging and dropping windows within the main window (e.g. re-arranging panels). As soon as a panel is dragged, it becomes undocked and so can't be placed back in the main window.

**Comment by pbek** [comment]
I don't know if it's possible in Qt to automatically re-dock it.

**Comment by Scrath1** [comment]
I have the same problem on EndeavorOS with Wayland. I installed the program from the [AUR](https://aur.archlinux.org/packages/qownnotes).
