### ISSUE TITLE
[BUG] Allow all note editing text should not invert

### ISSUE THREAD

**Issue by bgoodmansf** [pbek/QOwnNotes#2895]
The "Allow all note editing" command in the Notes menu changes to "Disallow all note editing" when it is checked. This is semantically wrong. Both display indicate that note editing is not allowed.

Note that a similar problem occurs with the tooltip for the icon in the toolbar.

#### Expected behaviour
"Allow all note editing" should continue to display "Allow all note editing" when checkbox is checked.

#### Actual behaviour
"Allow all note editing" command in the Notes menu changes to "Disallow all note editing" when it is checked.

#### Steps to reproduce
Check the "Allow all note editing" item in the Notes menu.

**Comment by pbek** [comment]
I think that stems from #866 to prevent confusion.
