### ISSUE TITLE
Link to heading not working properly

### ISSUE THREAD

**Issue by kg-yoda** [pbek/QOwnNotes#2896]
### Expected behaviour

When I click on a link to some heading it should open the linked note and scroll down to the appropriate heading.
What I want to achieve is to have some text on one note link to an image in another note.

### Actual behaviour

Only opens the note and doesn't scroll to the heading.

### Steps to reproduce

1. I created two empty notes. 
2. In one note I wrote some text.
3. In the other note I created headings by typing `## Heading` and one line below them I inserted an image by clicking the "Insert image" icon from the toolbar. I did that several times, so I have multiple images with multiple headings above them.
4. I selected some text from my first note.
5. I clicked on the "Insert text link" icon on the toolbar and went to the "Note" tab on the newly opened window.
6. I selected the correct note that contains my images with headings above them.
7. In the displayed list of headings I double clicked the appropriate one for the text I initially selected in **step 4.** (For example if the selected text was about mitochondria I had to choose the heading which would bring me to the image of it.)
8. I went to preview mode and clicked on the newly made link expecting it to scroll down to my image when in reality it only opened the note with the images.

### Additional information
Version: QOwnNotes - version 23.11.0 - GitHub Actions - build 1061

**Comment by pbek** [comment]
What is preview mode for you?
The jumping only works in the note text edit.

**Comment by kg-yoda** [comment]
Hi,

Sorry I should have been more clear, the preview mode is a workspace I created which basically just has the "Preview only" layout.

To further investigate this I made two test notes where in one of them I had the link and in the other I had a bunch of headings and new lines just to fill the note so the scrollbars appear. 
I created a link for the last heading in the note and like you said it jumps to the heading when I'm in the `Note edit` panel in my "edit" workspace. However, switching to my "Preview only" workspace and interacting with the link in the `Note preview` panel it does still jump to the last heading, but not directly on it, there is still some manual scrolling required to reveal the target heading.

Apart from that, for my actual goal to link text to images what I think is happening (*this is just speculation*) is that when I interact with the link in my "Preview only" workspace it does actually jump to the correct heading, however it does that before the images are actually rendered. So when the images load in it obviously creates a vertical overflow and scrollbars appear and the result of that is that the link appears to not work as it didn't jump to the new location of the heading after the images rendered in.

**Again I emphasize that this is just my theory. I dunno what can be happening...**

I don't know if there is some other way to link text to images, so far this linking to heading is the only workaround I found so I really want it to work.

Anyways, I forgot to thank you for even responding and trying to help, so thank you!

**Comment by pbek** [comment]
The headline linking relies on the note text edit, even if it's invisible, and the scrollbars "percentages" of the preview are matched in the preview. Images and so on could skew the result.

**Comment by kg-yoda** [comment]
Okay, should I close the issue then?

**Comment by pbek** [comment]
I guess we should.
