### ISSUE TITLE
[F] Being able to change image size

### ISSUE THREAD

**Issue by luisyaxmedrano** [pbek/QOwnNotes#2898]
#### Expected behaviour

Being able to change the size of an image, specially in Editor Mode. But since preview of images is not able to be seen in Editor Mode, then at least in Preview Mode.

#### Actual behaviour

No option to change size of images.

#### Steps to reproduce

One of the options is that from the settings you could put a standard size for images. Another is being able to change it from the preview mode. Another would be to show the preview image from the Editor Mode, and change it there.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
I'm not sure what we are talking about...

- Changing the actual image file size?
- Resizing height / width of the image file?
- Changing how the image is shown in the preview?
  - Currently, it resizes with the width of the preview panel.

**Comment by luisyaxmedrano** [comment]
It would be either the second or third option. (Is it too problematic to ask for both? it probably is) Anyway, the fact that right now the image resizes to the width of the preview panel can give a very weird view of the notes. Specially after using several images in a single note. So being able to change the size  at least in the preview panel (height and width) would be a very useful tool to customize the way every image looks and improve the overall look of notes.

**Comment by pbek** [comment]
2) You can do a lot in the "Insert image" dialog when inserting the image
3) There really is no good-supported way to do that in Markdown. There is a hook in the markdown engine where you can control how the preview is generated from the markdown, and one hook to control the HTML afterward.

And you can use image HTML tags like `<img width="300" src="file:///home/user/Nextcloud/Notes/media/491154026.png">` directly (with a full path to the image).

**Comment by pbek** [comment]
Btw. you can see what HTML is used in the preview by right-clicking on it and exporting it.

**Comment by pbek** [comment]
## 26.3.25

- Added support for **Markdown image dimensions** using curly-brace attribute
  syntax like `![alt text](image.png){ width=300 height=200 }`; the attributes
  are rendered with masked syntax in the editor and are applied to the preview,
  including the QLiteHtml preview, where they overrule the automatic image
  width sizing; the small inline image preview in the editor is also shown
  when the image tag with dimension attributes is the last item in the block
  (for [#2898](https://github.com/pbek/QOwnNotes/issues/2898))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
