### ISSUE TITLE
Feature Request: Directory Categories Organization

### ISSUE THREAD

**Issue by mlimacarlos** [pbek/QOwnNotes#29]
Hi, i'm very impressed with this software. It is cool and very simple to use.

If is possible i would like to divide in directories for organize notes. I think this helps to better organize ideas. 

tks
Marcos

**Comment by pbek** [comment]
Thank you, @mlimacarlos for your kind words and your suggestion. It currently is possible to have more than one notes folder. I tried to explain it here:
http://www.qownnotes.org/Knowledge-base/How-to-use-the-Set-notes-folder-feature-to-categorize-notes-using-real-filesystem-directories

Does this answer your question?

**Comment by mlimacarlos** [comment]
Hi pbek, 
No. I understanding that it is possible.
I think in a tree view for directories from root diretory notes on left side. If i set one directory i lost other directories view.

tks for response,
Regards 
Marcos

**Comment by pbek** [comment]
Your suggestion would maybe be nice, but problematic since neither ownCloud notes nor the iOS and Android clients are supporting this right now. For now the list needs to be plain to assure compatibility.

Thank you for your thoughts!

Kind regards,
Patrizio
