### ISSUE TITLE
Feature Request: Split note here

### ISSUE THREAD

**Issue by minthemiddle** [pbek/QOwnNotes#290]
Sometimes you want to split the content of one note. Right now I have to cut and paste to a new note for that. A feature that would come handy would be to be able to `split note here` which would automatically create a note below the marker.

**Comment by pbek** [comment]
You mean like this?

- `Ctrl + Shift + End` to mark the whole content from the current position to the end of the note
- `Ctrl + N` to create a new note
- `Ctrl + V` to paste the content

**Comment by minthemiddle** [comment]
Yes, this behaviour, but with one keystroke.

**Comment by pbek** [comment]
## 16.08.11
- there now is a new shortcut <kbd>Alt</kbd> + <kbd>⇧</kbd> + <kbd>X</kbd>
  to **split the current note** into two notes at the current cursor position
  - the name of the current note plus the current timestamp will be
    used as name for the new note
  - the new note will be tagged with the same tags as the old note

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by pbek** [comment]
## 16.08.12
- when splitting notes a link to the new note will be added at the 
  end of the old note 

(this is not released yet)

**Comment by Maboroshy** [comment]
It is at least second request for running some sequence of present key shortcuts by a single key. Maybe there should be in-app scripting function for this if people don't want to use proper external instruments for these kind of things.

**Comment by pbek** [comment]
This new feature does more that running a few shortcuts in a series.

**Comment by Maboroshy** [comment]
I know. You did a great job polishing it to perfect. But as you've stated earlier the request was basically making 3 shortcuts with one key.

Maybe the function can save you from such requests in future. Maybe I'm wrong and you don't need that kind of saving. I use `xdotool` for this kind of things anyway. On Windows there's an Eventghost app that can do all kinds of weird stuff.

**Comment by pbek** [comment]
I'm with your second though. Their are more than enough great tools for doing this job, no need to integrate that again. ;)
