### ISSUE TITLE
[BUG] Pressing buttons "Insert Test Link", "Insert Image" or "Insert Current time" modifies encrypted note, making note broken.

### ISSUE THREAD

**Issue by UA-koval** [pbek/QOwnNotes#2904]
Any button from "Inswerting toolbar" such as "Insert Test Link", "Insert Image" or "Insert Current time" modifies encrypted notes text. After this, note can no longer be opened.

#### Expected behaviour
When trying to insert anything, nothing happens.

#### Actual behaviour
Insert happens, directly over encrypted text, breaking it.  

After this operation, attempting to open note with correct password gives error "Wrong Password"
#### Steps to reproduce
1. Create a note
2. Encrypt it
3. Press "Insert Current Time" button on toolbar "Insert Toolbar"
4. Press "Edit Encrypted Note" button
5. Input correct password

**Comment by pbek** [comment]
Ah, nice. Directly after encrypting a note, you can still use the menu actions to insert something. Only typing is prohibited. This only works directly after creating a new encrypted note.
Thank you!

**Comment by pbek** [comment]
> This only works directly after creating a new encrypted note.

Actually adding something works also for already encrypted notes...
The handling of the actions is only implemented for the "read-only" mode...
That would be more of a new feature then, needs some rethinking.

**Comment by pbek** [comment]
## 23.11.3
- if the current note is encrypted, read-only or the doesn't exist any more now
  some menu actions are also disabled to prevent writing to the note text edit

There now is a new release, could you please test it and report if it works for you?
