### ISSUE TITLE
[BUG] Theming, dark mode - Black text on dark background in "Note search"

### ISSUE THREAD

**Issue by o-l-a-v** [pbek/QOwnNotes#2907]
## Problem

With default dark mode theme, the "note search" has black text when the window is active.

When window is active:

<img width="320" alt="image" src="https://github.com/pbek/QOwnNotes/assets/6450056/7c63a291-01cc-455b-a582-2927b4e5acf3">

</br>

When window is inactive:

<img width="322" alt="image" src="https://github.com/pbek/QOwnNotes/assets/6450056/61706329-b523-476e-a5f7-fc2ca780bf69">

## Env

* OS: Windows 11 23H2
* Version: 23.11.2

**Comment by pbek** [comment]
That's strange, I can't reproduce that on my system...

![image](https://github.com/pbek/QOwnNotes/assets/1798101/f1f7b178-36e7-4fb3-812f-a5c5bfc9b5f4)

Do you see that in other search bars, like for tags, subfolders or the settings?

**Comment by o-l-a-v** [comment]
Yeah, I can't reproduce on my other Windows 11 machine, strange. Will try to reproduce and get back to this issue.

**Comment by o-l-a-v** [comment]
I haven't been able to reproduce on other machines, will close the issue and reopen it if I manage to reproduce it in the future.
