### ISSUE TITLE
[FEATURE] Adjustable width in distraction free mode

### ISSUE THREAD

**Issue by o-l-a-v** [pbek/QOwnNotes#2908]
### Is your feature request related to a problem? Please describe.

Distraction free mode is very narrow IMO.

### Describe the solution you'd like

Adjustable width in distraction free mode. I'd like to set an absolute width no matter what text size I choose, say 90%?

### Describe alternatives you've considered

None. I searched doc and GitHub issues, found no relevant info about this.

#### Windows 11 23H2
* QOwnNotes v23.11.2
* Environmental variables in user context:
  * QT_AUTO_SCREEN_SCALE_FACTOR = 0
  * QT_SCALE_FACTOR = 1.5

#### Pop!_OS 22.04

* QOwnNotes v23.11.2 from Flathub.
* No environmental variables.

### Output from the debug section in the settings dialog

Don't think there were any relevant info there. Didn't bother to include it because there's information there I don't want to expose publicly.

#### Windows 11

<img width="1278" alt="image" src="https://github.com/pbek/QOwnNotes/assets/6450056/88a67c41-b0cd-4ee1-a484-7ba1e2912214">

#### Pop!_OS 22.04

<img width="1273" alt="image" src="https://github.com/pbek/QOwnNotes/assets/6450056/bd5da096-2f19-4cbb-8379-d6a27d35576d">

**Comment by pbek** [comment]
There is a setting one menu item below the distraction free mode for that. 😉

**Comment by o-l-a-v** [comment]
Roger that, so "editor width" also applies for "distraction free mode". :)
