### ISSUE TITLE
[Q] Is there a way to change distance between text lines?

### ISSUE THREAD

**Issue by SN-CH** [pbek/QOwnNotes#2909]
I'd like to have possibility to increase the distance between two lines of text in md-files or in all files (have it, say, 1,5 or 2 of standard distance). I installed the extension «Custom user interface styling» and added the following lines (one-by-one):
```
QMarkdownTextEdit { lineHeight: 1.5; }
QTextEdit { lineHeight: 1.5; }
```
No dice for me. Am I missing something? Or can't it be done at all?

**Comment by pbek** [comment]
Not a lot of styles are possible, did you read through https://www.qownnotes.org/scripting/methods-and-objects.html#add-a-custom-stylesheet?

**Comment by pbek** [comment]
And there are #2030 and #1011...

**Comment by pbek** [comment]
Yes, currently we are a bit out of luck with the line height...
Thank you for your kind words! 😉
