### ISSUE TITLE
Switch files shortcut like vs code

### ISSUE THREAD

**Issue by gal064** [pbek/QOwnNotes#2910]
#### Is your feature request related to a problem? Please describe.
Switching between notes is a chumbersome process. 

#### Describe the solution you'd like
Most code editors has a very easy flow to switch between files. E.g. vscode has a shortcut (cmd + p) to simply type the file name, path or content, and an auto complete form with all relevent files is shown. Then you can simply choose the relevant file with the up and down arrows 

Here is what I suggest (this is similar to vscode)
1. Hitting a shortcut opens a popup text box
2. Typing in the textbox has autocomplete
3. This popup is fully keyboard controlled. Hitting the shortcut immediately let's you type into the box. Arrow keys to choose the note from the autocomplete, enter to open note and esc to close.
4. [optional] Autocomplete search works by file name, path and content of the file
5. [optional] Autocomplete shows you both the file name, path and if search matches inner content the inner content
6. [optional] inputing a note name without a match and pressing enter will create a note

**Comment by pbek** [comment]
> Hitting a shortcut opens a popup text box
> Typing in the textbox has autocomplete
> This popup is fully keyboard controlled. Hitting the shortcut immediately let's you type into the box. Arrow keys to choose the note from the autocomplete, enter to open note and esc to close.

Hm, it almost works that way already...

`Ctrl + Shift + F` (you can configure the shortcut) jumps to the search input field. While typing, you can see which notes there are left. There also is a history of notes you already open (as autocomplete).

With the `Down` key you switch to the note list.


> [optional] inputing a note name without a match and pressing enter will create a note

That also already works.

**Comment by pbek** [comment]
> [optional] Autocomplete search works by file name, path and content of the file

You can already search in all tags / folders...

**Comment by gal064** [comment]
> You can already search in all tags / folders...

How do I do that? I may be missing something, but when I use the search option, it only searches in the current folder, not across folders

**Comment by gal064** [comment]
Thanks!
