### ISSUE TITLE
[BUG] App Won't Start -- Could not find the Qt platform plugin "wayland" in ""

### ISSUE THREAD

**Issue by Sullux** [pbek/QOwnNotes#2911]
#### Expected behaviour

App starts.

#### Actual behaviour

App fails to start.

#### Steps to reproduce

In Ubuntu 22.04, having never installed any version of qownnotes:

```bash
sudo add-apt-repository ppa:pbek/qownnotes-qt6
sudo apt-get update
sudo apt-get install qownnotes
```

In order to see output, run with:

```bash
QOwnNotes
```

#### Output in Console

```
Warning: Could not find the Qt platform plugin "wayland" in "" (:0, )
Fatal: This application failed to start because no Qt platform plugin could be initialized.
Reinstalling the application may fix this problem.
 (:0, )
Aborted (core dumped)
```

#### Comments

I don't know what Qt is. I have never used QOwnNotes before and would like to give it a try. I searched for hours and was guided towards various possible solutions, none of which worked. Things I tried included:

```bash
sudo apt install python3-pip
pip install numpy
pip install opencv-python==4.3.0.38
sudo apt install qtwayland5
sudo apt install -y qtcreator qtbase5-dev qt5-qmake cmake
```

As a software engineer, what this _looks_ like (knowing nothing about Qt) is possibly a missing environment variable or a missing plugin folder since the error message suggests that it is looking for plugins in an empty string.

I may just bail on this and try to install v5, but I figured it would be helpful to give you this feedback. Hope this is useful as you work towards stabilizing this version.

**Comment by pbek** [comment]
Are you using wayland? What happens after a `sudo apt -y install qt6-wayland`?
