### ISSUE TITLE
[SUPPORT] Title bar color doesn't change when dark mode enabled (regardless of system settings), Windows 10

### ISSUE THREAD

**Issue by lanmi42** [pbek/QOwnNotes#2913]
#### Question

When I enable dark more, everything but the title bar changes color:

![image](https://github.com/pbek/QOwnNotes/assets/62254569/70f57b6a-5203-4cb0-bdeb-6bf87600f2f3)

Is there a way to change the title bar from within the app? If not, then maybe this should be labeled a bug?

There's a kind of workaround in system settings, but it requires that I set the title bar accent color for all apps. This is not ideal because it messes up other apps (title bar does not match the rest of the dark theme of an app).

How it should work (in my opinion) - when I enable dark mode, the title bar should change color as well, and it should match the rest of the dark theme.

OS: Windows 10 (19045.3693)
Ownnotes version: 23.11.3

Please let me know if I need to provide more details.

**Comment by pbek** [comment]
To my knowledge, the look of the title bar is not in control of the application, the operating system is in control of it.

**Comment by lanmi42** [comment]
From the apps I use on Windows, Firefox and Notepad++ have the intended behavior.

Particularly Notepad++ had the same issue and they resolved it - https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10696. Unfortunately, I wasn't able to dig up what the actual fix was.

I did find this though - https://stackoverflow.com/a/70821543, seems like it's exactly what we need this case. What do you think?

**Comment by pbek** [comment]
> I did find this though - https://stackoverflow.com/a/70821543, seems like it's exactly what we need this case. What do you think?

Interesting, it's a config file one could create. Did you try to create it?

**Comment by pbek** [comment]
Maybe you can also try to run `QOwnNotes.exe -platform windows:darkmode=1`, like mentioned on https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5 for Qt 5.

But this all is very Windows specific...

**Comment by lanmi42** [comment]
Tried creating conf file - no change, tried launching with arguments - no change, title bar remains light in both cases.

As to why is quite a bit from my know how, but if there's anything else you'd like me to try please let me know.

**Comment by pbek** [comment]
I also didn't have luck with adding `qputenv("QT_QPA_PLATFORM", "windows:darkmode=1");` or `qputenv("QT_QPA_PLATFORM", "windows:darkmode=2");` to the source code...

**Comment by lanmi42** [comment]
What about the proposed solution under "The Qt 6.5 Way" in https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5 ?

Or is that Windows 11 specific?

**Comment by pbek** [comment]
> What about the proposed solution under "The Qt 6.5 Way" in https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5 ?

To my understanding this was only about QML, we don't use QML for the user interface, we are using QWidget.

**Comment by lanmi42** [comment]
Again, way out of my know how, found this - https://stackoverflow.com/questions/48256772/dark-theme-for-qt-widgets, which leads to https://github.com/ColinDuquesnoy/QDarkStyleSheet. Might be useful.

But in any case, it's not a deal breaker, and it doesn't seem to be affecting a lot of users.

Thank you for replying, and feel free to close this ticket.

**Comment by pbek** [comment]
We have dark stylesheets for the widgets, what you want is styling of the title bar. 😉
