### ISSUE TITLE
[FEATURE] Additional color schemes for internal and external links

### ISSUE THREAD

**Issue by Bufetr** [pbek/QOwnNotes#2914]
It would be very useful, in order to distinguish, to add two extra color schemes in the "Editor fonts and Colors" option menu, each one for internal and external links.

The internal links could be recognized when they start with note:// and the external links with their URI schemes, like http://, https://, mailto://, ftp:// for start, as mentioned in <https://en.wikipedia.org/wiki/List_of_URI_schemes>.

Thank you!

**Comment by pbek** [comment]
## 26.3.25

- Added a new highlighter state **Link (internal)** for internal note links
  (like `[text](note.md)`, `<note.md>` and `note://` links) in the editor font
  and color settings; this allows styling internal note links differently from
  regular external links in the note text edit and the preview; the **Link**
  state is used as a fallback if the new state is not configured in the color schema;
  bare legacy `note://` links (e.g. `note://Note_2018_06_26T22_11_10`) that are
  written without angle brackets are now also rendered as clickable links in the
  preview and styled with the internal link color
  (for [#2914](https://github.com/pbek/QOwnNotes/issues/2914))

**Comment by pbek** [comment]
## 26.4.2

- Changed the built-in `Light` editor color schema so internal note links now use
  `#fc8f00` as foreground color and `#fff8ef` as background color
  (for [#2914](https://github.com/pbek/QOwnNotes/issues/2914))
