### ISSUE TITLE
[I] Settings are deleted after reset

### ISSUE THREAD

**Issue by gal064** [pbek/QOwnNotes#2916]
#### Expected behaviour

When reloading the app following a change in settings that requires a reload (eg add a dictionary),  everything's working

#### Actual behaviour

Settings are reset,  I see the wizard screen again and settings start from scratch.

I see these in the terminal window
Warning: libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))
Warning: libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))
Warning: libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))
Warning: libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))
Warning: libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))
Warning: libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))
Warning: libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))
Warning: libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))
Warning: libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))
Warning: libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))
Warning: libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))
Warning: libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))
Warning: libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))
Warning: libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null)

Last login: Mon Dec 11 11:05:24 on ttys021
/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes ; exit;                    
/Users/aaa :/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes ; exit;
Warning: "Removed database file: " "/Users/aaa/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite" (:0, )

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

#### Steps to reproduce

1. Open QT settings
2. Change a setting that requires reset (example - add a dictionary or change the "Ask for title when creating a new note" in the general settings screen)
3. App asks you to reload for settings to work - Accept

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mon Dec 11 11:34:48 2023`
**Version**: `23.11.3`
**Build date**: `Nov 23 2023`
**Build number**: `1064`
**Platform**: `macosx`
**Operating System**: `macOS 13.5`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Application arguments**: `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1512x982`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `641`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `en_US`
**Language codes**: `en_US`
**Language names**: `American English (United States)`
**Application dictionaries path**: `/Users/aaa/Library/Application Support/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `2`

### Note folder `default`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `9`
**localPath**: `/Users/aaa/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/Users/aaa/Notes/notes.sqlite`

### Note folder `default`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/Users/a/Downloads/untitled folder`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/Users/aaa/Downloads/untitled folder/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

## Settings

**AKLastEmailListRequestDateKey** (QDateTime): `2023-12-11T09:20:32.655`
**AKLastIDMSEnvironment** (qlonglong): `0`
**AKLastLocale** (QString): `en_US`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Country** (QString): `US`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (qlonglong): `4`
**Editor/removeTrailingSpaces** (bool): `false`
**Editor/showLineNumbers** (bool): `false`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**KB_DoubleQuoteOption** (QString): `“abc”`
**KB_SingleQuoteOption** (QString): `‘abc’`
**KB_SpellingLanguage** (QVariantMap): *empty*
**LastUpdateCheck** (QDateTime): `2023-12-11T11:29:42.853`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (qlonglong): `32`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Menlo,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `.AppleSystemUIFont,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Menlo,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `.AppleSystemUIFont,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.refreshDebounceTime** (qlonglong): `600`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**NoteFolder-1/NoteTabNameList** (QStringList): `Modern JavaScript Explained For Dinosaurs`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): 
```
2 - Personal
Deep dives
```
**NoteHistory-1** (QVariantList): `<variant list with 2 item(s)>`
**NoteHistoryCurrentIndex-1** (qlonglong): `1`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (qlonglong): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**TISRomanSwitchState** (qlonglong): `1`
**WebAutomaticSpellingCorrectionEnabled** (bool): `true`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `false`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (bool): `true`
**autoReadOnlyMode** (bool): `false`
**autoReadOnlyModeTimeout** (qlonglong): `30`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (qlonglong): `2`
**currentWorkspace** (QString): `initial`
**cursorWidth** (qlonglong): `1`
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (bool): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (bool): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**enableWebAppSupport** (bool): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (qlonglong): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (qlonglong): `1024`
**imageScaleDownMaximumWidth** (qlonglong): `1024`
**initialLayoutIdentifier** (QString): `preview-only`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (qlonglong): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (qlonglong): `18`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (qlonglong): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelAutoSelect** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (qlonglong): `2`
**newNoteAskHeadline** (bool): `true`
**noteEditIsCentralWidget** (bool): `false`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (qlonglong): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (qlonglong): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (qlonglong): `0`
**noteSubfoldersPanelTabsUnsetAllNotesSelection** (bool): `false`
**notesPanelOrder** (qlonglong): `0`
**notesPanelSort** (qlonglong): `1`
**notesPath** (QString): `/Users/aaa/Downloads/untitled folder`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (qlonglong): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (qlonglong): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (bool): `false`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**showMatches** (bool): `true`
**showMenuBar** (bool): `false`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `en_US`
**startInReadOnlyMode** (bool): `false`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (qlonglong): `0`
**tagsPanelSort** (qlonglong): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (qlonglong): `6`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (qlonglong): `22222`
**workspace-initial/name** (QString): `Preview only`
**workspace-initial/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**USER**: `aaa`
**COMMAND_MODE**: `unix2003`
**__CFBundleIdentifier**: `com.PBE.QOwnNotes`
**PATH**: `/usr/bin:/bin:/usr/sbin:/sbin`
**LOGNAME**: `aaa`
**SSH_AUTH_SOCK**: `/private/tmp/com.apple.launchd.XcVIFB8oEi/Listeners`
**HOME**: `/Users/aaa`
**SHELL**: `/bin/zsh`
**TMPDIR**: `/var/folders/6v/cx63y9nd4q9d_f3b3x9nvct80000gn/T/`
**__CF_USER_TEXT_ENCODING**: `0x1F5:0x0:0x0`
**XPC_SERVICE_NAME**: `application.com.PBE.QOwnNotes.67986993.67987118`
**XPC_FLAGS**: `0x0`
**QT_LOGGING_RULES**: `qt.network.ssl.warning=false`
</details>

**Comment by pbek** [comment]
> Open QT settings

Do you mean "QOwnNotes settings"?

>  Warning: "Removed database file: " "/Users/aaa/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite" (:0, )


That's not a message from QOwnNotes. Is anything else on your system deleting the file?

**Comment by gal064** [comment]
When I restart QOwnNotes after a change in settings a terminal window is opened. This is where the message is coming from, so I'd be surprised if it's unrelated to QOwnNotes

![image](https://github.com/pbek/QOwnNotes/assets/50427415/4ee5f46d-3740-42ab-8016-d84d80f3685e)

**Comment by pbek** [comment]
You can search for it in the source code yourself: https://github.com/search?q=repo%3Apbek%2FQOwnNotes%20%22Removed%20database%20file%22&type=code

The same goes for everything after that warning ("Saving session..." and so on). That's not from QOwnNotes too...

**Comment by gal064** [comment]
Yep understood but it's a window that launched following me launching QOwnNotes. My guess is that it comes from a 3p library you import or related to how Mac handles the software.

**Comment by gal064** [comment]
OK so not sure what's going on. Great software, btw. Seems like it only happens when I change settings that require reset, so for now I just won't change them. But it does happen consistently

Where are the settings stored?

**Comment by pbek** [comment]
Thank you. 😉
You can see the path in the debug settings. 
Currently there should only be two ways to reset the settings, with a CLI parameter and with a button in the general settings

**Comment by antoine-prrn** [comment]
I have exactly the same problem on an Apple M1 chip. When I change some settings in QOwnNotes the settings are deleted and I lose my current configuration.
