### ISSUE TITLE
[BUG] Notes list view resets when changing note name

### ISSUE THREAD

**Issue by discapes** [pbek/QOwnNotes#2924]
Hi! This app is really good, I just noticed one problem that occurs ofter: when I change the name of a note (by editing the first line), and then save it, the note list panel resets. What I mean is that it scrolls to the top, and categories collapse/uncollapse randomly. This makes it hard to keep track of where I am. I'm using the experimental feature.

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Looks like you are talking about the work in progress feature https://github.com/pbek/QOwnNotes/issues/790, right?
Hard to tell, you could try to turn off external modifications in the *General settings*...

**Comment by discapes** [comment]
Yes, that's the feature I mean. Although, even when not using the experimental feature, the note list and folder list both scroll up, but it's not as severe because the collapsed-status of the folder's don't change. 

I tried these options, but they didn't change anything:
![image](https://github.com/pbek/QOwnNotes/assets/48839377/48273ecd-6871-49b4-a1a4-bd23b349676d)

**Comment by discapes** [comment]
I traced the problem to the function `void NoteSubFolderTree::onItemExpanded(QTreeWidgetItem *item) {` in line 252 of notesubfoldertree.cpp not getting called when using the experimental mode

**Comment by discapes** [comment]
Weird, since it gets connected with these:
```
    connect(this, &QTreeWidget::itemExpanded, this, &NoteSubFolderTree::onItemExpanded);
    connect(this, &QTreeWidget::itemCollapsed, this, &NoteSubFolderTree::onItemExpanded);
```
and they work in the normal mode
