### ISSUE TITLE
[FEATURE] Add icon for "Show Note preview panel"

### ISSUE THREAD

**Issue by o-l-a-v** [pbek/QOwnNotes#2926]
#### Is your feature request related to a problem? Please describe.

Not related to a problem.

#### Describe the solution you'd like

Would be great if the "Show Note preview panel" could have an icon too.

I add this as a button to the "mainToolBar" toolbar, but it looks a bit out of place being the only toggle/button without an icon.

#### Describe alternatives you've considered

Setting and learning a hotkey/shortcut.

#### Additional context

<img width="1280" alt="image" src="https://github.com/pbek/QOwnNotes/assets/6450056/c299cae0-4b6f-4733-821e-0265da90212a">

#### Output from the debug section in the settings dialog

Not relevant.

**Comment by pbek** [comment]
You are "not supposed" to put that in the toolbar. Usually you would add a new workspace where you define the desired layout (e.g. with preview, you could even move panels) and switch between the workspace with and without preview. 😉

**Comment by o-l-a-v** [comment]
I've checked out workspaces and I agree that it seems like a better approach, thanks @pbek. :)
