### ISSUE TITLE
[BUG] "Find:" opens when toggling note preview panel on or off if any text in the "Note search panel"

### ISSUE THREAD

**Issue by o-l-a-v** [pbek/QOwnNotes#2927]
#### Expected behaviour

If I have any text in the "note search panel", and I've closed "Find:" inside current open note, I don't expect "Find:" to reopen if I toggle the preview panel on or off.

#### Actual behaviour

"Find:" inside current open note opens again when toggling preview panel on or off.

#### Steps to reproduce

Screen recording: https://youtu.be/i51KVv2BcIE

#### Output from the debug section in the settings dialog

Not relevant?

#### Relevant log output in the Log panel

Not relevant.

**Comment by pbek** [comment]
As long there is some text in the note search panel, a lot of interactions can trigger the note searching, which also includes opening the "in-note search".

But like mentioned in https://github.com/pbek/QOwnNotes/issues/2926#issuecomment-1864375969, you should rather use workspaces.

**Comment by o-l-a-v** [comment]
After trying workspaces it seems like a better way of toggling preview on/off, I agree. :)

But I still consider this unwanted behavior. If you don't just close the issue.

**Comment by pbek** [comment]
I just looked at it, the note-filtering will be triggered on purpose whenever a panel is toggled in case some panels would need trigger filtering.

https://github.com/pbek/QOwnNotes/blob/3cd56c6c35d46c9c183acf1fb68a02546bc2d0c8/src/mainwindow.cpp#L1417

I don't know if it's worth thinking through which panels wouldn't need to trigger the filtering just for such a minor edge case...

**Comment by o-l-a-v** [comment]
Observed behavior from other editors is that only CTRL + F / opening "Find" should open it, nothing else.

**Comment by pbek** [comment]
QOwnNotes is not an editor. 😁 

When the note search panel is used, the search text will be also searched inside the current note (with the search widget inside the note editor).

**Comment by o-l-a-v** [comment]
Sorry, "plain-text file notepad and todo-list manager". 🙂

Alright then, I guess I'll have to adapt to that.
