### ISSUE TITLE
[SUPPORT] Is there a way to completely disable the "read-only" feature from ever activating?

### ISSUE THREAD

**Issue by nonplayer** [pbek/QOwnNotes#2930]
The amount of times the "read-only" flag gets tripped for me is somewhat maddening. I've removed the button from my toolbar and disabled the default shortcut for "disallow all note editing," and yet it still seems to flip on seemingly at random. Sometimes I start up the program and a document is read-only. Sometimes it will switch seemingly in the middle of typing up some notes. I feel like I've searched the app inside out and upside down and cannot figure out why this keeps happening.

I'm sure many people use it, but I have never once needed it, and it's only ever caused me frustration. If there is some way to just disable that feature once and for all I can die a happy man.

**Comment by pbek** [comment]
Best look in the *General settings*. 😉

**Comment by nonplayer** [comment]
Sadly "Start application in read-only mode" is the first thing I ever un-checked. It's still un-checked.

I just updated thinking maybe I'm hitting a bug, and of course Windows again deleted it. Argh.

**Comment by pbek** [comment]
But also need to uncheck the checkbox after that do disable the auto-read-only mode!

**Comment by nonplayer** [comment]
They are both already unchecked.

**Comment by pbek** [comment]
Then there are only two ways that you can't edit the file... You are pressing escape (while typing?) or the file gets read-only by some other process (maybe something that syncs?)

**Comment by nonplayer** [comment]
This is getting really weird. I have disabled the Alt-Shift-E shortcut completely. I have unchecked both boxes in the General settings. And yet multiples times in this current editing session, I've accidentally fat-fingered some unknown multi-key combo and get the "Note editing is disabled" message, and I look down and lo and behold, the read-only icon is back in the lower-right corner. This time at least it gave me the "Do not ask again" option, and I checked it and said yes, but I still don't know why it would have popped up in the first place if I have the option otherwise disabled by the settings detailed above.

What else in the code makes this happen? I can't find any other shortcut to disable that seems relevant to the issue.

**Comment by nonplayer** [comment]
> Then there are only two ways that you can't edit the file... You are pressing escape (while typing?) and enter the read-only mode or the file gets read-only by some other process (maybe something that syncs?)

That's gotta be it: the escape key. How do I make it not do that? I am a heavy escape key user. I would really like it to not assume I want to go read-only just because I tapped a single commonly-tapped key on my keyboard.

**Comment by pbek** [comment]
> That's gotta be it: the escape key. How do I make it not do that? I am a heavy escape key user. I would really like it to not assume I want to go read-only just because I tapped a single commonly-tapped key on my keyboard.

Hm, there is no way to get out of that... The escape key first turns off the find dialog, then it turns off note editing. What are you using the Escape key for?

**Comment by nonplayer** [comment]
I'd really appreciate an option to disable that. I'm using the Escape key for backing out of things and de-selecting text. 40+ years of computer-ing have burned universal expectations of escape key usage into muscle memory. I'm honestly more than a little surprised to see this happen, I had assumed everyone who prefers keyboard usage to mouse used ESC that way as well.

For a bit more explanation, escape has been commonly used as the "back out" or "cancel selection" key for many apps for decades. It behaves this way in every other text editor, note taker, WYSIWYG web form, and word processor I've ever used (Notepad, Notepad++, VSCode, Word, etc), which is probably why this unique take on it confounds me so much. I've never before had an app enforce a locking function to the escape key, so that at least explains the confusion.

It'd be super awesome if this could be considered for a change or (even better) made into a toggle-able option in a future release.

**Comment by pbek** [comment]
Hm, that would currently be a "one user" use-case checkbox and one more option in the already cluttered *General settings*.

**Comment by nonplayer** [comment]
That is really disappointing. I'm not understanding why this feature is bound to something as common as the Escape key, it's just a very unusual design choice, especially since there is already a completely separate hotkey that does the same thing, which _can_ be changed in the keymappings menu. Even something as simple as putting it as a mapping option in the Keymaps would be fantastic.

It's seriously maddening enough that I'll probably switch away from using the app entirely if I can't change, remap, or disable it.

**Comment by pbek** [comment]
Besides you being disappointed... On the dialog that you get when you press a key in the editor in read-only mode, did you ever check "don't ask me again" and then clicked "Yes"? That should fix most of your inconveniences, doesn't it?

**Comment by nonplayer** [comment]
Good question. On the surface yeah, it works well enough for this need. This'll do for now, thanks.

But the trade-off for this work-around is that now the read-only option is made completely inaccessible (at least until I choose to reset all the hidden messages). In my own use case, cool, I don't need it, I much prefer locking that down at a filesystem permissions level instead. But now there's the conundrum of not knowing if this might cause other complications in the future. Making that key mapping accessible would eliminate that possibility.
