### ISSUE TITLE
The "YAML nested tags" script breaks formatting and causing text lost in preview 

### ISSUE THREAD

**Issue by kostoms** [pbek/QOwnNotes#2932]
#### Expected behaviour

Expected behaviour: code blocks are not processed by YAML scripts.

#### Actual behaviour

When "YAML nested tags" script enabled, creating note with code block containing row "..." followed by any another row does lead to the issue preview being broken while YAML definitions not expected inside code blocks and contents of code blocks is expected to be shown as is.

#### Steps to reproduce

While having "YAML nested tags" script enabled, create note with contents like below and check preview (the row "..." followed by any another row does lead to the issue, this is not expected in the code block )

~~~md
---
title: Try this with script "YAML nested tags" enabled

---

This is a test note

```sh
$ cat test.txt
...
$
```
~~~

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
No specific debug ouput was observed
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

Note, I've tried it in Windows as well

## General Info

**Current Date**: `Wed Dec 27 18:50:58 2023`
**Version**: `23.12.4`
**Build date**: `Dec 27 2023`
**Build number**: `1069`
**Platform**: `linux`
**Operating System**: `Armbian 23.11.1 jammy`
**Build architecture**: `arm64`
**Current architecture**: `arm64`
**Release**: `Self-build`
**Qt Version (build)**: `6.2.4`
**Qt Version (runtime)**: `6.2.4`
**Portable mode**: `no`
**Settings path / key**: `/home/******/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/******/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/home/******/bin/qownnotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080`
**Icon theme**: `Adwaita`
**Notes in current note folder**: `13`
**Calendar items**: `0`
**Enabled scripts**: `39`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/home/******/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `2`

### Note folder `default`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `92`
**localPath**: `/home/kostos/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/******/notes.sqlite`

### Note folder `QOwnNotes`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/******/******/notes.QOwnNotes`
**remotePath**: `notes.QOwnNotes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `yes`
**activeNoteSubFolder name**: `Permissions`
**database file**: `/home/******/******/notes.QOwnNotes/notes.sqlite`

Sorry too much info to obfuscate.. Deleting the rest
</details>

**Comment by pbek** [comment]
Is this a script related issue? Then best open it in the script repository.

**Comment by kostoms** [comment]
> Is this a script related issue? Then best open it in the script repository.
OK, created [#214](https://github.com/qownnotes/scripts/issues/214#issue-2058193271) there,
I was not sure because noticed the issue after upgrading from 23.11.00 to 23.12.04, but it seems reproducing in  23.11.00 as well.
