### ISSUE TITLE
[FEATURE] Releases SHA256 file: Add file name of the ZIP

### ISSUE THREAD

**Issue by o-l-a-v** [pbek/QOwnNotes#2938]
The SHA256 file included in the release is missing the name of the ZIP file for commands like `sha256sum --check QOwnNotes.zip.sha256` to work.

Its' content is currently:

```
fb95c0816e2efc32d631b0f2b9fb555359b7c73cdaf810d70dd84c8ecbc8c594

```

But it'd preferably be:

```
fb95c0816e2efc32d631b0f2b9fb555359b7c73cdaf810d70dd84c8ecbc8c594 *QOwnNotes.zip

```

**Comment by pbek** [comment]
When did they have the filename included?
I'm not sure if I should change that, otherwise other scripts/systems that depend on the current form might break.

**Comment by o-l-a-v** [comment]
Oh, maybe I should've added this as a feature request instead. AFAIK they never did.

I'd expect the file to work as any other `.sha256` file, for instance created by `sha256sum --binary *`.

**Comment by pbek** [comment]
> When did they have the filename included?

see:
https://github.com/pbek/QOwnNotes/blob/2e1198b676bb74ae7d0e3d1fd9935c5225a5a718/build-systems/github/build-github-src.sh#L75-L77

**Comment by pbek** [comment]
The source code checksums were more meant to directly feed into env vars of external build systems...
I can't simply change the format of the file now.
I could only create new additional files.

**Comment by o-l-a-v** [comment]
Roger that. Then it's probably not worth the effort to implement it, but that's up to you to decide.

**Comment by pbek** [comment]
I don't mind...

## 24.1.2
- in new releases, the source code `tar.xz` file will now also have a `.sha256sum`
  and a `.sha512sum` file, that is compatible with `sha256sum` and `sha512sum`   
  (for [#2938](https://github.com/pbek/QOwnNotes/issues/2938))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by o-l-a-v** [comment]
Thanks @pbek. I was actually interested in having it for the Windows ZIP file, as I use [HashCheck](https://github.com/idrassi/HashCheck) to validate the checksum if checksum is available. And it failed with the `.zip.sha256` as the `.sha256` file does not include the file name the checksum belongs to. I was just making sure thats how checksum checking on Linux works as well, thus I reported this feature request with an example from Linux.

**Comment by pbek** [comment]
Oh. I'm not sure if that tool exists in the GitHub Windows images.
If you want to play around with the CI yourself and come up with a working command that doesn't break the release script you can create a pull request. 😁 

You will need to add a line after those:

https://github.com/pbek/QOwnNotes/blob/6f562243c8fed966c321eb23b3d90768ec190b33/build-systems/github/windows/build-zip.ps1#L40

https://github.com/pbek/QOwnNotes/blob/902a0af5a3b954a3f158e35617e2c6950752310f/build-systems/github/windows/build-zip-qt6.ps1#L47

And a similar block after those:

https://github.com/pbek/QOwnNotes/blob/3f33f8cea2e2d4aef502c89a9412cfb1480858c5/.github/workflows/build-release.yml#L317-L325

https://github.com/pbek/QOwnNotes/blob/5a869c2fa9cbb332f53b78a1c642f160299a405a/.github/workflows/build-release-qt6.yml#L326-L330

**Comment by pbek** [comment]
I guess we can close this now.
