### ISSUE TITLE
How do I increase the size of check boxes using KDE plasma [SUPPORT] 

### ISSUE THREAD

**Issue by bdika** [pbek/QOwnNotes#2939]
#### I have tried changing fonts and sizes without much luck. See below

MONTH END TODO LIST
Before Midnight Previous Month
☐ Update Nick's Gnucash Books with Stock Prices
☑ Update Spreadsheet with Mortgage Balances, Credential RRSP and TFSA data and Nat and Jeff's RRSP Balances

Any help is much appreciated.

I cannot use Qownnotes unless I solve this issue. I am not a programmer but a long time user of linux.

Thanks.

bdika

**Comment by pbek** [comment]
Are you talking about the HTML preview of notes?

The checkboxes should resize if you increase the font-size, for example, with `Ctrl + Plus`.
It least it does for me under KDE Plasma.

**Comment by bdika** [comment]
Thanks pbek.

That works but it increases everything in the window. I would like to increase the size of the checkboxes relative to the text. Does it take css or is there a script I can add that might do that for me?

Sorry if I was not more specific in my first post.

Thanks again.

Bill Dika

**Comment by pbek** [comment]
There is a script in the script repository where you can add CSS styles to the preview. Maybe there is a CSS selector supported you can use for the checkbox (like `input[type=checkbox]`).

**Comment by bdika** [comment]
Thanks pbek, I really appreciate your help.

I am not clear on how to implement your suggestion but will keep trying.

Bill

**Comment by pbek** [comment]
Trickier than I thought:

- Install script "Custom note preview styling" from script repository inside QOwnNotes
- Set following style

```CSS
li[style*="list-style-type:square"] a {
    font-size: 40px;
}
```

**Comment by pbek** [comment]
Glad it worked. 😉
