### ISSUE TITLE
Feature Request: api blueprint syntax

### ISSUE THREAD

**Issue by vpistis** [pbek/QOwnNotes#294]
[api blueprint](https://apiblueprint.org/) is very like mardown syntax but with some extra good feature for api design.
Is possible to integrate in QOwnNotes?
TX

**Comment by pbek** [comment]
Integrate where and what? Blueprint seems to be for web APIs. QOwnNotes is a desktop app...

**Comment by vpistis** [comment]
Integrate a syntax highlight and a preview engine into QOwnNotes.
API Blueprint is a language like markdown, but with more features very usefull to write apis documentation, and also notes :)

From the web site of [api blueprint](https://apiblueprint.org/)

> With API Blueprint you can quickly design and prototype APIs to be created or document and test already deployed mission-critical APIs.

This is a piece of code markdown-like:
```
# Data Structures

## Blog Post (object)
+ id: 42 (number, required)
+ text: Hello World (string)
+ author (Author) - Author of the blog post.

## Author (object)
+ name: Boba Fett
+ email: fett@intergalactic.com
```

Obviously is not an essential feature for QOwnNotes :)

**Comment by pbek** [comment]
Thank you for your suggestion and your insights, but currently QOwnNote will only support markdown. Doing otherwise would be a major rewrite from the ground up and I don't see the need for it yet. ;)
