### ISSUE TITLE
Nextcloud stoped syncinf, all settings on green

### ISSUE THREAD

**Issue by poltpolt** [pbek/QOwnNotes#2943]
Hi
Recently nextcloud sync stopped working, maybe it's related to the fact that I started using 2faa? 
How can I gather logs?
![obraz](https://github.com/pbek/QOwnNotes/assets/9408405/596b66d8-af10-41b7-a41e-f86113d38944)

**Comment by pbek** [comment]
By "Nextcloud Sync" do you mean the [Nextcloud Desktop Sync client](https://github.com/nextcloud/desktop)? That's not part of QOwnNotes. 😁 
Maybe just do a login again in the Sync Client...

**Comment by poltpolt** [comment]
I mean qownnotes notes sync with nextcloud via the option provided.
Or is it required to run next cloud desktop client additionally for the folder where notes are stored?

**Comment by pbek** [comment]
> I mean qownnotes notes sync with nextcloud via the option provided.

There is no such thing (as the settings dialog states on the right).

Also see https://www.qownnotes.org/getting-started/concept.html or https://www.qownnotes.org/getting-started/qownnotesapi.html#what-qownnotesapi-doesn-t-do.

>  Or is it required to run next cloud desktop client additionally for the folder where notes are stored?

Exactly. 😉
