### ISSUE TITLE
[I] Using Copy to.. of Move to.. does not move media files and does not alter the url location of the media links

### ISSUE THREAD

**Issue by codesnippy** [pbek/QOwnNotes#2948]
#### Expected behaviour

I have 2 note folders 1 I work in the other is a imported version of a Joplin setup.

I am trying to move / copy notes between the note folders from within QOwnNotes.
I expected to .md files and assigned media file would get moved / copied to the other note folder

#### Actual behaviour

It will move / copy the .md file but the media assigned to it will not be moved / copied nor is the URL to the media folder altered in the .md file that gets moved.

#### Steps to reproduce

have 2 note folders setup.
Select a note from a subfolder from one note folder. Right click on it choose Move note to... of Copy note to... Choose new location in other note folder and subfolder.

If you change to the moved of copied note folder the .md file is there but it does not link to the correct location of the media. nor did it move / copy the media file to the other note folder media folder.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `vr jan. 26 16:56:19 2024`
**Version**: `24.1.4`
**Build date**: `Jan 19 2024`
**Build number**: `1075`
**Platform**: `linux`
**Operating System**: `KDE Flatpak runtime`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub`
**Qt Version (build)**: `5.15.10`
**Qt Version (runtime)**: `5.15.10`
**Portable mode**: `no`
**Settings path / key**: `/home/wouter/.var/app/org.qownnotes.QOwnNotes/config/PBE/QOwnNotes.conf`
**Application database path**: `/home/wouter/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080`
**Icon theme**: `breeze`
**Notes in current note folder**: `10383`
**Calendar items**: `178`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `25.0.13.2`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_AU, en_BS, en_BZ, en_CA, en_GB, en_GH, en_IE, en_IL, en_IN, en_JM, en_MW, en_NA, en_NZ, en_PH, en_TT, en_US, en_ZA, en_ZW`
**Language names**: `Australian English (Australia), English (Bahamas), English (Belize), Canadian English (Canada), British English (United Kingdom), English (Ghana), English (Ireland), English (Israel), English (India), English (Jamaica), English (Malawi), English (Namibia), English (New Zealand), English (Philippines), English (Trinidad & Tobago), American English (United States), English (South Africa), English (Zimbabwe)`
**Application dictionaries path**: `/home/wouter/.var/app/org.qownnotes.QOwnNotes/data/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `2`

### Note folder `default`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `-1`
**localPath**: `/home/wouter/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/wouter/Notes/notes.sqlite`

### Note folder `Notebook`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/wouter/Documents/Notebook`
**remotePath**: `document/Notebook`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: `wiki.polycount.com`
**database file**: `/home/wouter/Documents/Notebook/notes.sqlite`

### Cloud connection `

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://`
**username**: ``
**accountId**: ``

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**CloudConnection-1/nextcloudDeckEnabled** (QString): `false`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `/home/wouter/Downloads/joplin 2`
**FileDialog/LastPath-Joplin Import** (QString): `/home/wouter/Downloads/joplin 2`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**JoplinImport/AttachmentImportCheckBoxChecked** (bool): `true`
**JoplinImport/FolderImportCheckBoxChecked** (bool): `true`
**JoplinImport/ImageImportCheckBoxChecked** (bool): `true`
**JoplinImport/MetadataImportCheckBoxChecked** (bool): `false`
**JoplinImport/TagImportCheckBoxChecked** (bool): `true`
**JoplinImportDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2024-01-26T16:00:51.532`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Computer/Blender/Topology Guides, Computer/Programming, Computer/Blender, Computer`
**MainWindow/noteSubFolderTreeWidgetExpandState-2** (QStringList): `Joplin, Joplin/Computer, Joplin/Computer/Blender, Joplin/Computer/Blender/Topology Guides`
**MainWindow/noteTextEdit.code.font** (QString): `Hack,10,-1,7,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Hack,10,-1,7,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (QString): `600`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/copy-notes** (int): `16384`
**MessageBoxOverride/move-notes** (int): `16384`
**MessageBoxOverride/notes-copied** (int): `1024`
**MessageBoxOverride/share-sync-information** (QString): `1024`
**NoteFolder-1/NoteTabNameList** (QStringList): *empty*
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteFolder-2/NoteTabNameList** (QStringList): *empty*
**NoteFolder-2/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-2/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteHistory-1** (QVariantList): `<variant list with 44 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 26 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `43`
**NoteHistoryCurrentIndex-2** (int): `25`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**StoredAttachmentsDialog/geometry** (QByteArray): `<binary data>`
**StoredImagesDialog/geometry** (QByteArray): `<binary data>`
**TableDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `0`
**TodoDialog/showDueTodayItemsOnly** (QString): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `calandar`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**autoReadOnlyMode** (QString): `false`
**autoReadOnlyModeTimeout** (QString): `30`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (int): `2`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `24`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**noteSubfoldersPanelTabsUnsetAllNotesSelection** (QString): `false`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/wouter/Documents/Notebook`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): `calandar, Boodschappen lijst, Vuilnis, Grumpie, Personal (Willeke Scholten), Deck: Personal, Deck: Godot, Deck: Agile Board, Deck: Agile Development, Deck: Bug Tracking, Deck: Learning, Deck: Project Based Learning, Deck: Blender, Deck: Fractals`
**ownCloud/todoCalendarEnabledList** (QStringList): `calandar, Boodschappen lijst, Vuilnis, Grumpie, Personal (Willeke Scholten), Deck: Personal, Deck: Godot, Deck: Agile Board, Deck: Agile Development, Deck: Bug Tracking, Deck: Learning, Deck: Project Based Learning, Deck: Blender, Deck: Fractals`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): ``
**ownCloud/todoCalendarUrlList** (QStringList): ``
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `25.0.13.2`
**recentNoteFolders** (QStringList): `/home/wouter/Notes`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Carver controle items, Note 2024-01-26T15.08.13`
**savedSearches/noteFolder-2** (QStringList): `Note 2024-01-26T15.38.42, Note 2024-01-26T12.57.42`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**startInReadOnlyMode** (QString): `false`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**XDG_RUNTIME_DIR**: `/run/user/1000`
**container**: `flatpak`
**AT_SPI_BUS_ADDRESS**: `unix:path=/run/flatpak/at-spi-bus`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/flatpak/bus`
**DEBUGINFOD_URLS**: `https://debuginfod.debian.net`
**DESKTOP_SESSION**: `plasma`
**DISPLAY**: `:0`
**FLATPAK_ID**: `org.qownnotes.QOwnNotes`
**FLATPAK_SANDBOX_DIR**: `/home/wouter/.var/app/org.qownnotes.QOwnNotes/sandbox`
**GI_TYPELIB_PATH**: `/app/lib/girepository-1.0`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**GST_PLUGIN_PATH**: `/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0`
**GTK2_RC_FILES**: `/etc/gtk-2.0/gtkrc:/home/wouter/.gtkrc-2.0:/home/wouter/.config/gtkrc-2.0`
**GTK3_MODULES**: `xapp-gtk3-module`
**GTK_MODULES**: `gail:atk-bridge`
**GTK_RC_FILES**: `/etc/gtk/gtkrc:/home/wouter/.gtkrc:/home/wouter/.config/gtkrc`
**HOME**: `/home/wouter`
**INVOCATION_ID**: `fc6bc89340654886a2b7a10a3bf0dedb`
**JOURNAL_STREAM**: `8:28194`
**KDE_APPLICATIONS_AS_SCOPE**: `1`
**KDE_FORK_SLAVES**: `1`
**KDE_FULL_SESSION**: `true`
**KDE_SESSION_UID**: `1000`
**KDE_SESSION_VERSION**: `5`
**LANG**: `en_US.UTF-8`
**LANGUAGE**: `en_US:en`
**LC_MEASUREMENT**: `nl_NL.UTF-8`
**LC_MONETARY**: `nl_NL.UTF-8`
**LC_TIME**: `nl_NL.UTF-8`
**LD_LIBRARY_PATH**: *empty*
**LOGNAME**: `wouter`
**MANAGERPID**: `1745`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**PATH**: `/app/bin:/usr/bin`
**PS1**: `[📦 $FLATPAK_ID \W]\$ `
**PWD**: `/home/wouter`
**QML2_IMPORT_PATH**: `/app/lib64/qml:/app/lib/qml`
**QTWEBENGINE_DICTIONARIES_PATH**: `/usr/share/hunspell-bdic/`
**QT_ACCESSIBILITY**: `1`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**QT_PLUGIN_PATH**: `/app/lib64/plugins:/app/lib/plugins:/usr/share/runtime/lib/plugins`
**SESSION_MANAGER**: `local/tpe560-01:@/tmp/.ICE-unix/1899,unix/tpe560-01:/tmp/.ICE-unix/1899`
**SHELL**: `/bin/sh`
**SSH_AGENT_PID**: `1839`
**SSH_AUTH_SOCK**: `/tmp/ssh-XXXXXXdvBE2e/agent.1785`
**SYSTEMD_EXEC_PID**: `1941`
**USER**: `wouter`
**XAUTHORITY**: `/run/flatpak/Xauthority`
**XCURSOR_SIZE**: `24`
**XCURSOR_THEME**: `breeze_cursors`
**XDG_CACHE_HOME**: `/home/wouter/.var/app/org.qownnotes.QOwnNotes/cache`
**XDG_CONFIG_DIRS**: `/app/etc/xdg:/etc/xdg`
**XDG_CONFIG_HOME**: `/home/wouter/.var/app/org.qownnotes.QOwnNotes/config`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_DATA_DIRS**: `/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share`
**XDG_DATA_HOME**: `/home/wouter/.var/app/org.qownnotes.QOwnNotes/data`
**XDG_SEAT**: `seat0`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_DESKTOP**: `KDE`
**XDG_SESSION_ID**: `4`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**XDG_SESSION_TYPE**: `x11`
**XDG_STATE_HOME**: `/home/wouter/.var/app/org.qownnotes.QOwnNotes/.local/state`
**XDG_VTNR**: `7`
**__EGL_EXTERNAL_PLATFORM_CONFIG_DIRS**: `/etc/egl/egl_external_platform.d:/usr/lib/x86_64-linux-gnu/GL/egl/egl_external_platform.d:/usr/share/egl/egl_external_platform.d`
</details>

**Comment by pbek** [comment]
Do you maybe have an example note folder where that happens? Maybe the media files aren't detected.

**Comment by codesnippy** [comment]
[Notes.zip](https://github.com/pbek/QOwnNotes/files/14403717/Notes.zip)

This is a example note folder I have the problems with. It is originally imported from Joplin by QOwnNotes

**Comment by pbek** [comment]
It was hard to find any Markdown image link pointing to a local file in your files.
And even those were very wonky `[![06641d8902db43418a42a1fb0d3c12e1](../../../media/06641d8902db43418a42a1fb0d3c12e1.jpg)](http://wiki.polycount.com/wiki/File:Topo_larking-nose.jpg)`. I'm not sure those can be detected properly. But the media files were even copied, but the image links stayed the same...

**Comment by pbek** [comment]
## 26.3.24

- Updated **Copy note to** and **Move note to** (cross-note-folder operations)
  so that media images and attachment files are now also copied to the destination
  note folder's `media/` and `attachments/` directories respectively, and the
  links inside the moved/copied note are rewritten to point to the correct
  locations at the root of the destination note folder; previously the `.md`
  file was moved but linked files were left behind and URLs were not updated
  (for [#2948](https://github.com/pbek/QOwnNotes/issues/2948))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
