### ISSUE TITLE
[FEATURE] shortcut for up and down navigation in subfolders and tags

### ISSUE THREAD

**Issue by joomlafun** [pbek/QOwnNotes#2949]
Hi,

First off : Not enough said : your software rocks ! I try to promote it to my surrounding, people don't know how much they need it for proper organization until they use it !

Feature request : 
As there is a shortcut to ascend or descend in the notes, this would be handy for subfolders and tags folders.

I know the arrows can be used though but you know those past gamer habit of using the left side of the keyboard :)

**Comment by pbek** [comment]
In the `Help` menu, click `Find action`. Search for `up` or `move up`. 😉

**Comment by pbek** [comment]
> First off : Not enough said : your software rocks ! I try to promote it to my surrounding, people don't know how much they need it for proper organization until they use it !

Hehe, thank you very much! 🚀

**Comment by joomlafun** [comment]
> In the `Help` menu, click `Find action`. Search for `up` or `move up`. 😉

Thanks but what I meant is that you cannot set up a custom shortcut for this like there is for note navigation for example.

**Comment by pbek** [comment]
Why can't you? `move up` in the `Shortcut` settings. Does a custom shortcut not work there? It does work for me!

**Comment by joomlafun** [comment]
Yes you can move up and down in the note panel with a shortcut but there is no shortcut to move up/down in the subfolder

![image](https://github.com/pbek/QOwnNotes/assets/63743077/a68f5d12-29f7-4788-b37e-6d66d46d4211)

**Comment by pbek** [comment]
Ah, sorry. Now I see.

**Comment by pbek** [comment]
## 24.2.0
- there are now new menu items in the *Note / Navigation* menu to move up/down in
  the subfolder and tag list (for [#2949](https://github.com/pbek/QOwnNotes/issues/2949))
  - those menu items are only enabled if their respective panels are visible
  - you can set shortcuts for them in the *Shortcuts settings*

There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
> It is a game changer honestly, I got s and d binded for notes switching, e and and f for tabs, g h for tags, it is so comfortable !

I couldn't decide on default shortcuts. 😅
Great that it worked, thank you for testing! 🥳 

There is https://www.qownnotes.org/contributing/donate.html if you desperately want to donate something. 😊
