### ISSUE TITLE
Does not remember that tag window was open after restart

### ISSUE THREAD

**Issue by mrbiber** [pbek/QOwnNotes#295]
version 16.08.12 - Launchpad PPA - build 219

- activate one column mode 
- show tag window
- close QOwnNotes
- open QOwnNotes

expected: view is restored as it was when the application was closed
actual: tag window is not opened

Thank you!

**Comment by pbek** [comment]
Well, when entering one column mode (happens at startup if you have enabled it) the tag panel will be disabled. I'm not sure if that's good or not...

**Comment by pbek** [comment]
But I guess I will do something about it...

**Comment by pbek** [comment]
## 16.08.13
- when in *one column mode* the other panes will not be hidden when 
  QOwnNotes is restarted
    - they only will be hidden when the mode is manually entered

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by mrbiber** [comment]
Yes, it works (although the main note window does not stay maximized across the whole area across restarts). Thank you!

**Comment by pbek** [comment]
Thank you for testing.

> note window does not stay maximized across the whole area across restarts

is it usual for an application to do that?

**Comment by mrbiber** [comment]
What I mean is that I use the mouse to move the right border of the note input window to the right end of the main application window (so that no unused grey space is visible any more). On restart, the note input window is again less wide than the available space, leaving some unused grey space. I don't mean that the main app window is maximized or not - I am just talking about the size of the note input window *within* the main application window.

**Comment by pbek** [comment]
Could you please make some screenshots before and after the restart?

**Comment by mrbiber** [comment]
![bildschirmfoto vom 2016-08-19 16-41-05](https://cloud.githubusercontent.com/assets/1094714/17813469/c7f8cb5e-662b-11e6-845c-c17bf6b943b1.png)
![bildschirmfoto vom 2016-08-19 16-40-52](https://cloud.githubusercontent.com/assets/1094714/17813470/c81e234a-662b-11e6-860a-52cbc0e9d2d3.png)

**Comment by mrbiber** [comment]
The lower image is before the restart, sorry

**Comment by pbek** [comment]
When and how did you get the grey area before the restart? I cannot even manage to produce such an area and it shouldn't be possible...

**Comment by pbek** [comment]
And what desktop environment are you using? Ubuntu?

**Comment by pbek** [comment]
@mrbiber, I can't reproduce that under Unity. Can you please provide the steps to get the grey area on the right?

**Comment by mrbiber** [comment]
OK, it took me a while to figure out how to do it. To reproduce with a fresh profile:

- maximize window
- deactivate MD preview
- select vertical preview layout
- activate one column-mode

(as a bonus bug: if you then deactivate vertical preview layout, the one-column-mode is also deactivated, even though the menuitem remains checked)

**Comment by pbek** [comment]
I will take a look at that...

**Comment by pbek** [comment]
should be fixed in the next release, thank you for reporting and testing!

## 16.08.17
- fixed a problem with the one column mode while in vertical preview layout mode

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by mrbiber** [comment]
Yes, thank you!

**Comment by pbek** [comment]
great, thank you for testing!
