### ISSUE TITLE
[SUPPORT] Massive notes cause lag in operation

### ISSUE THREAD

**Issue by Frozen1084** [pbek/QOwnNotes#2951]
I imported 8000+ notes from Evernote (Evernote export file 250MB), and the operation of QOwnNotes became very laggy (it takes several seconds to switch from one note to another), almost to the point of unusable.

Is this because QOwnNotes can't work well with massive notes, or is it a problem with Evernote export data?

I tried switching from Evernote to QOwnNotes about a year ago, and the 7000 notes were just as laggy then as they are now.
In Evernote, there is no difference in operation between 100 notes and 10,000 notes.

v24.1.5
win10_64

**Comment by pbek** [comment]
You can try to turn of things in the note list in the settings. It depends on disk speed, settings, scripts and so on, hard to tell without settings dump and debug log. If your note folder is reloaded that certainly could take long if the system can't handle it. I've note folders with 1000 notes and no issues.
