### ISSUE TITLE
[BUG] Qt6 PPA version on Ubuntu 22.04 won't start

### ISSUE THREAD

**Issue by o-l-a-v** [pbek/QOwnNotes#2964]
I wanted to test the future, so I went ahead and installed the Qt6 version of QOwnNotes according to:

* https://www.qownnotes.org/blog/2023-02-03-Test-Qt6-version-of-QOwnNotes-from-a-new-PPA-for-Ubuntu-Linux.html
* https://www.qownnotes.org/installation/ubuntu.html#qownnotes-qt6-preview

But it wouldn't start. I tried to reinstall it after doing a `sudo apt remove --purge qownnotes`, but it still wouldn't start.

I then tried to start it from the terminal with `/usr/bin/QOwnNotes` (as I have the Snap and Flatpak version of the Qt5 / regular too, and `qownnotes` is redirected to `/snap/bin/qownnotes`) and got the following:

```
Warning: Could not find the Qt platform plugin "xcb" in "" (:0, )
Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
 (:0, )
Aborted (core dumped)
```

<hr>

To make sure OS/env specific stuff doesn't break the Qt6 version while testing, would it be useful to package it too as an app image? And/or as a beta channel in Snapcraft?

**Comment by pbek** [comment]
> Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Hm, never tried it on Pop!_OS, I only used KDE Neon, based on Ubuntu 22.04. Maybe Pop!_OS does something a bit different, or different Qt6 libraries... Could you maybe try to build it on Pop!_OS with Qt6? E.g. with QtCreator or on the CLI (https://www.qownnotes.org/installation/building.html).

> AppImage

I already managed to build a Qt6 AppImage (it was a PITA).
Can you access the artifacts on https://github.com/pbek/QOwnNotes/actions/runs/7941452139? It's too big to upload here...
I'm not sure this link will work when I'm not around: https://wormhole.app/x7vm4#Nfst16j-oWeq5Zqzga-cNQ

**Comment by o-l-a-v** [comment]
The AppImage with Qt6 started up fine, so might be something Pop!_OS related then.

<img width="1237" alt="image" src="https://github.com/pbek/QOwnNotes/assets/6450056/b64182e4-9fb7-4e5b-a45a-1fdbfd62894f">

I'll see if I got time to try to compile it later today. But the VM disk space is full, have to expand it first. Which is a bit of work when using LUKS.

**Comment by pbek** [comment]
> The AppImage with Qt6 started up fine, so might be something Pop!_OS related then.

Seems like...
Thank you for testing.
Btw. how did download it now? Can you access the artifacts of the build?

> Which is a bit of work when using LUKS.

Haha, I just did the same for a VM, also wit LUKS. Fun time, fun time, ... 😆 

> Edit: Will have to go deeper than I have time for today to get Qt installed and try to compile.

And you need lots of disk space 😅. I'm spoiled by how easy I can do such things on NixOS nowadays...
But you even **can** use nix as package manager under Ubuntu. 😉 The nix package of QOwnNotes is Qt 6.6.1 😉

**Comment by o-l-a-v** [comment]
> Btw. how did download it now? Can you access the artifacts of the build?

I could access the artifacts from the action, but only when signed in. :)

> And you need lots of disk space 😅. I'm spoiled by how easy I can do such things on NixOS nowadays...
> But you even can use nix as package manager under Ubuntu. 😉 The nix package of QOwnNotes is Qt 6.6.1 😉

Hmm, interesting. Lots to learn. :)

**Comment by o-l-a-v** [comment]
Actually, the Qt6 version won't start on a fresh Ubuntu 22.04 install either, with the same error.

<img width="769" alt="image" src="https://github.com/pbek/QOwnNotes/assets/6450056/5a0c7847-7e65-4bfd-96e3-99d6837c036b">

**Comment by pbek** [comment]
> > Btw. how did download it now? Can you access the artifacts of the build?
> 
> I could access the artifacts from the action run, which was pretty neat. 🙂

Ok, so you can just with your regular user permissions. That's great, thank you!

> 
> > And you need lots of disk space 😅. I'm spoiled by how easy I can do such things on NixOS nowadays...
> > But you even can use nix as package manager under Ubuntu. 😉 The nix package of QOwnNotes is Qt 6.6.1 😉
> 
> Hmm, interesting. Lots to learn. 🙂

I transitioned a while ago and never looked back! I really love the declarative aspect of it, now I can have the binary exact same installation including all important settings on all of my machines! A dream that came true, wasn't really able to do that with Ansible.

**Comment by o-l-a-v** [comment]
Tested again with a new clean install of Ubuntu 22.04 and 24.04. Installation of QOwnNotes Qt6 from PPA works in 24.04, but in 22.04 the error now has one more warning about missing Qt plugins:

```bash
ubnt@ubnt:~$ QOwnNotes
Info: Warning: Ignoring WAYLAND_DISPLAY on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway. (:0, )
Warning: Could not find the Qt platform plugin "xcb" in "" (:0, )
Warning: Could not find the Qt platform plugin "wayland" in "" (:0, )
Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
 (:0, )
Aborted (core dumped)
ubnt@ubnt:~$
```

**Comment by pbek** [comment]
Maybe this helps:

This error indicates that your Qt application is having trouble finding the necessary platform plugins to run on your Ubuntu system. Here are some steps to resolve this:

1. Install Qt dependencies:
```bash
sudo apt-get update
sudo apt-get install libqt5gui5 libxcb-xinerama0
```

2. Install XCB and Wayland plugins:
```bash
sudo apt-get install libqt5xcbqpa5 qt5-default qtwayland5
```

3. If you're using X11, set the platform explicitly:
```bash
export QT_QPA_PLATFORM=xcb
```

4. If you're using Wayland, set the platform:
```bash
export QT_QPA_PLATFORM=wayland
```

5. Verify Qt installation:
```bash
qtchooser -print-env
```

The warning suggests two potential issues:
- Missing Qt platform plugins
- Potential library path configuration problem

The first two commands install the core Qt libraries and plugins. The platform export helps Qt find the correct display server plugin.

**Comment by o-l-a-v** [comment]
On Ubuntu 22.04 following two packages could not be installed.

```bash
ubnt@ubnt:~$ sudo apt install libqt5xcbqpa5
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libqt5xcbqpa5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libqt5gui5:i386 libqt5gui5 libqt5gui5-gles

E: Package 'libqt5xcbqpa5' has no installation candidate
ubnt@ubnt:~$ sudo apt install qt5-default
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package qt5-default is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'qt5-default' has no installation candidate
ubnt@ubnt:~$ 
```

Then installed Qt6 PPA version. Then did:

```bash
ubnt@ubnt:~/Desktop$ export QT_QPA_PLATFORM=xcb
ubnt@ubnt:~/Desktop$ QOwnNotes
Warning: Could not find the Qt platform plugin "xcb" in "" (:0, )
Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
 (:0, )
Aborted (core dumped)
ubnt@ubnt:~/Desktop$
```

**Comment by o-l-a-v** [comment]
Maybe this is related?

* <https://askubuntu.com/questions/1335184/qt5-default-not-in-ubuntu-21-04>

> The 21.04 is based on Debian bullseye, which does not have qt5-default package in [the repository](https://packages.debian.org/search?suite=all&searchon=names&keywords=qt5-default). I reported a [bug to launchpad about missed qt5-default package](https://pad.lv/1926802).

>
> There is a way is to install [all dependencies of qt5-defalt package](https://packages.ubuntu.com/groovy/qt5-default) with
>
> `sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools`
> and then try to compile your application.

**Comment by pbek** [comment]
I forgot about the Qt6 aspect...

These warnings indicate that your Qt application is having trouble finding the necessary platform plugins to run on your Ubuntu Linux system. Here are some steps to resolve this issue:

1. Install Required Packages:
```bash
sudo apt update
sudo apt install libgl1-mesa-glx libxcb-xinerama0 qt6-base-dev
```

2. Install XCB and Wayland Plugins:
```bash
sudo apt install libqt6gui6 libqt6xcbqpa6 qt6-wayland
```

3. Verify Qt Installation:
```bash
qtchooser -list-versions
qt6-qmake --version
```

4. Set Platform Explicitly:
You can force the Qt application to use a specific platform by setting the environment variable:
```bash
# For X11
export QT_QPA_PLATFORM=xcb

# For Wayland
export QT_QPA_PLATFORM=wayland
```

5. Additional Troubleshooting:
- Ensure you have the correct Qt development libraries installed
- Check that your Qt installation matches your application's build configuration
- Verify that the application was compiled with the correct Qt version

**Comment by pbek** [comment]
For me, just doing a `sudo apt install libqt6gui6 qt6-wayland` solved the issue!

**Comment by pbek** [comment]
I'll add that to https://github.com/pbek/QOwnNotes/blob/aa4e595933b3f50e0b7f5ddb6c41e70febe07d27/ubuntu-launchpad/qt6/control#L13

**Comment by o-l-a-v** [comment]
`sudo apt install libqt6gui6 qt6-wayland` was not sufficient for XCB. But it worked on Wayland. 😊

I also tried the first search results saying to install `libxcb-cursor0` and `libxcb-xinerama0`, but it was already installed.

After installing `qt6-base-dev` too, it worked.

**Comment by o-l-a-v** [comment]
I thought installing all that's included with `qt6-base-dev` was a bit too much. So I tried some of the packages it included. Found out that following package did the trick for XCB: `qt6-qpa-plugins`.

**Comment by o-l-a-v** [comment]
🤔

I ran it from the terminal with "QOwnNotes" as command.

**Comment by pbek** [comment]
Ok, I'll add the platform library too, just to make sure.

## 24.12.2
- The Qt Wayland and platform libraries were added to the Qt6 Ubuntu PPA, so the
  repository works out of the box on Ubuntu 22.04 (for [#2964](https://github.com/pbek/QOwnNotes/issues/2964))

**Comment by pbek** [comment]
There now is a new release, could you please test i andrepot fit wokso yu?

**Comment by o-l-a-v** [comment]
Success. 😎 Ubuntu 22.04, clean install, just added xRDP for RDP from Windows. So used XCB, not Wayland.

<img width="616" alt="image" src="https://github.com/user-attachments/assets/6ccf9867-04c3-4cce-8f53-17660500cd2e">

**Comment by pbek** [comment]
Awesome, thank you for testing!

**Comment by pbek** [comment]
Are you still on Ubuntu 22.04 or are you already on 24.04 or newer? For the latter, could you please try QOwnNotes 25.5.10 from the Qt6 repository and report is scripting is working? 🙏🏻 I had to redo that completely.
See https://github.com/pbek/QOwnNotes/issues/3267#issuecomment-2895547266.

**Comment by o-l-a-v** [comment]
I still run Pop!_OS based on 22.04. Can try later this evening, if I remember to. 😊

**Comment by pbek** [comment]
Thank you!

**Comment by o-l-a-v** [comment]
Had a 24.04 VM, clean install in december, just updated it and rebooted then did:

```bash
sudo add-apt-repository ppa:pbek/qownnotes-qt6
sudo apt-get update
sudo apt-get install qownnotes
QOwnNotes
```

It started without problems. I installed the "Insert Table of Contents (TOC)" script. It worked too. 😊

![Image](https://github.com/user-attachments/assets/c5c08a04-26aa-4569-8837-84eb41a4350c)

**Comment by pbek** [comment]
Awesome, thank you very much!
