### ISSUE TITLE
[SUPPORT] how do filenames work?

### ISSUE THREAD

**Issue by gituser23234235234887** [pbek/QOwnNotes#2966]
#### Question
when I edit a file, first line gets chosen as filename, how do I stop this? what are the rules for filenames being chosen? anyway to choose filenames only when making and renaming files?

**Comment by pbek** [comment]
You can tell QOwnNotes to not use a fixed file name, in the *Note folder* settings. Then you can edit the filename afterward.

Or you can use a scripting hook to choose your own filename: https://www.qownnotes.org/scripting/hooks.html#handlenotetextfilenamehook
