### ISSUE TITLE
[BUG] obsidian imports all appear on one line

### ISSUE THREAD

**Issue by gituser23234235234887** [pbek/QOwnNotes#2967]
#### Expected behaviour
when I copy all my obsidian md files over, the preview panel should display each line on its own line.
#### Actual behaviour
it displays newlines as spaces, and I have to put `\` at the end of all lines except the last one
#### Steps to reproduce
bring md files over from obsidian

**Comment by pbek** [comment]
> it displays newlines as spaces, and I have to put \ at the end of all lines except the last one

Yes, this is how Markdown works. But you can even turn off Markdown if you don't like the way newlines are handled in Markdown.

Or you can force newlines with two spaces at the end of a line:
https://www.qownnotes.org/getting-started/markdown.html#line-breaks

Normally you just use two newlines.

**Comment by pbek** [comment]
Yes, and you can always create a new script for the rest.
