### ISSUE TITLE
[FEATURE] Shortcut to select everything in the current line.

### ISSUE THREAD

**Issue by eduardo-architect** [pbek/QOwnNotes#2968]
There's a very useful feature in several editors that is a key binding that selects all within a line, sometimes also called, expand selection to line.

This is very useful and productive, when editing notes, and speeds up everything. Just go to the line, press a key combination, and voila!

Would it be possible to implement on QOwnNotes?

**Comment by pbek** [comment]
I guess you could just write a script with a custom action with https://www.qownnotes.org/scripting/methods-and-objects.html#select-the-current-line-in-the-note-text-edit.

**Comment by pbek** [comment]
And then best create a pull request on https://github.com/qownnotes/scripts 😉
