### ISSUE TITLE
[F] Tabs without Note Editor

### ISSUE THREAD

**Issue by TheMarkovian** [pbek/QOwnNotes#2969]
#### Expected behaviour

Show tabs for different opened notes while the note edit panel is hidden/closed in a workspace. I regularily use a preview-only workspace to browse my notes and reference multiple notes simultaneously. Unfortunately, I can't use the tab functionality that way.

#### Actual behaviour

Tabs are linked to the note edit panel and are therefore inaccessible if the note edit panel is hidden in a workspace.

**Comment by pbek** [comment]
Hm, i don't think this will work technically, since all the panels can be placed anywhere and the tabs are bound to the note edit panel. So previews can be tabbed as part of notes 🤔

**Comment by TheMarkovian** [comment]
My first instinct was to resize the edit panel to only show the tabs, but it wont let me!

**Comment by pbek** [comment]
> Maybe another approach is a setting toggle that duplicates the tabs above the preview panel?

The tabs are part of the note edit panel, so it needs to be visible. The preview only reacts to the really "current note". There only can be one current note. The tabs are just an "illusion" that there can be multiple current notes...

**Comment by TheMarkovian** [comment]
Thanks for responding to my odd request! I discovered QOwn two months ago and it is everything I've ever needed in a notes application. This one thing just forced me to change my operating procedure, so I took the step to inquire about a change.

Final, hopefully easier, suggestion. Would it be possible to make the editor panel as resizable as the preview panel is? The preview panel can be shrunk to just a small horizontal bar, but the editor cant be shrunk to smaller than half a screen. If the editor would allow me to do the same, I would just do that and use the editor tabs without its panel dominating half the screen.

**Comment by pbek** [comment]
In the Panels settings you can turn off that it is the central widget, that might help.

**Comment by TheMarkovian** [comment]
The central widget option was already turned off. The first screenshot below shows the minimum height of the edit panel. The second the minimum height of the preview panel. Width is resizable without problems.

![afbeelding](https://github.com/pbek/QOwnNotes/assets/64398690/a3f6e03d-6ebd-4346-bfcf-0224702e54d4)

![afbeelding](https://github.com/pbek/QOwnNotes/assets/64398690/d3a5e4f2-f74b-48b7-91c7-2704a12f8c3b)

**Comment by Kvcd12** [comment]
Create a Workspace.  Enable Unlock panels from the Windows menu.  "Separate" the Note preview panel from the application.  Manually maximize the Note preview panel.  Thus, the panel appears to be over or floating above the application.  I wasn't sure  if everything would snap back into place if one chose another Workspace, but it does.  And choosing the new Workspace automatically separates the Note preview panel and floats it over the application.

![Note Preview Float](https://github.com/pbek/QOwnNotes/assets/50029431/39ee4771-ec65-4493-af60-bc202cb2b997)

**Comment by TheMarkovian** [comment]
This works and solves the issue for me. Thanks!
