### ISSUE TITLE
Scriptable output format

### ISSUE THREAD

**Issue by wolkenschieber** [pbek/QOwnNotes#297]
QOwnNotes is a great tool for managing notes. For me one application scenario is, writing code review remarks in a note. After the review is done, I convert the markdown file to wiki syntax and post the result in some media wiki artikle. The conversion is done using [Pandoc](http://pandoc.org).

Is it possible to automate this conversion process using a script?

**Comment by pbek** [comment]
Thank you for your kind words.
You could call an external command every time a note was stored.
There is an example here: <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/execute-command-after-note-update.qml>

Does that answer your question?

**Comment by wolkenschieber** [comment]
Kind of. But actucally I want some button for this task. When the button is pressed the conversion should be done, and afterward an editor should be opened. 
On save could do the conversion, but I'd still have to find the file and open it.

Thanks for your reply.

**Comment by Maboroshy** [comment]
You can write a small shell script and bind it to a keyboard shortcut with DE tools or X-server tools.

**Comment by pbek** [comment]
Scriptable buttons / menu entries would be nice, I'll have to look more into that...

**Comment by wolkenschieber** [comment]
That would be great. Another idea is to integrate the pandoc library. Then you could export to numerous formats.

**Comment by pbek** [comment]
It would need to run on Linux, OS X and Windows, with no further dependencies. And sadly, to my knowledge, that's not the case.

**Comment by wolkenschieber** [comment]
That's a shame. Pandoc seems to be available for all three platforms. The binaries are easy to find, but the library isn't. I also found it only as a package in the ubuntu repository.

Nevertheless a scriptable button would rock.

**Comment by pbek** [comment]
Pandoc is written in Haskell. ;)

**Comment by pbek** [comment]
There will be custom actions in v16.08.16!

**Comment by pbek** [comment]
## 16.08.16
- you are now able to define custom actions that will be shown as menu 
  entry in the scripting menu and optionally in the toolbar as button
    - there is an example for opening the current note with KWrite
      and to create a new note with a custom text at
      [custom-actions.qml](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/custom-actions.qml)
    - there is a small documentation about the function
      `registerCustomAction` and other functions in the
      [scripting documentation](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/README.md#register-a-custom-action)
    - you can also assign shortcuts for your custom actions in the 
      shortcut settings
- added new methods to the scripting engine
    - you can now also get the full file path of the current note
      with `script.currentNote().fullNoteFilePath`
    - you can now register a custom action with `script.registerCustomAction()`
    - you can now create a new note with `script.createNote()`
    - you can now access the clipboard with `script.clipboard()`
    - take a look at the [scripting documentation](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/README.md)
      for more information
- there now is a new example to create a note from a 5pm email with a 
  custom action at
  [note-from-5pm-mail.qml](https://github.com/pbek/QOwnNotes/tree/develop/doc/scripting/note-from-5pm-mail.qml)

@wolkenschieber, you should now be able to create a qml script to launch your pandoc export! Could you please be so kind and report your experiences.

**Comment by pbek** [comment]
16.08.16 is now released...

**Comment by wolkenschieber** [comment]
Wow. Great to hear, that the feature is now available. I'll write my conversion script and report back.

**Comment by Maboroshy** [comment]
Looks like you've made another leap in app functionality. Getting current note path is the most interesting for me. 

I remember when this app was when I first joined this hub. Seeing it developing so fast is great. It has twice more github stars now since I joined. 

I've tested kwrite example so far and it works good.

**Comment by pbek** [comment]
@wolkenschieber, great thank you!

**Comment by pbek** [comment]
@Maboroshy, since you are posting so many feature requests there's no other way than the app being improved! ;)

> How to assign icon to a toolbar button?

It would be no problem to add a parameter to assign a freedesktop theme icon, but of course that would only work under Linux.

**Comment by pbek** [comment]
## 16.08.17
- when creating custom action buttons you now can define a button icon
  from your freedesktop theme icons or a local file 
    - for more information please take a look at the 
      [registerCustomAction documentation](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/README.md#register-a-custom-action)

**Comment by wolkenschieber** [comment]
@pbek, The implemenation of the button was really easy. The api is straightforward and the examples are cover many use cases. 
For the conversion button, I basically just changed some parameters from the examples:
[Button doing the MediaWiki conversion](https://gist.github.com/wolkenschieber/e0f5172a7aaacd8e177c587e73f0b1d9)

**Comment by pbek** [comment]
@wolkenschieber, great job!

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by wolkenschieber** [comment]
I've just received 16.08.17. The feature works nicely. I can also set a custom button!

**Comment by pbek** [comment]
Great, thank you for testing!
