### ISSUE TITLE
AppImage problem

### ISSUE THREAD

**Issue by dukester** [pbek/QOwnNotes#2970]
I DLed the AppImage and got the following:

```
QOwnNotes-x86_64.AppImage
/tmp/.mount_QOwnNoOpJXPk/AppRun.wrapped: symbol lookup error: /tmp/.mount_QOwnNoOpJXPk/AppRun.wrapped: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructEmc, version Qt_5
```
System:
  Kernel: 4.9.235-antix.1-amd64-smp arch: x86_64 bits: 64 compiler: gcc v: 8.3.0 clocksource: tsc
    available: hpet,acpi_pm parameters: BOOT_IMAGE=/boot/vmlinuz-4.9.235-antix.1-amd64-smp
    root=UUID=ce1bd296-39c1-4bd7-a96c-a1150bb6cad1 ro quiet
  Desktop: Fluxbox v: 1.3.7 vt: 7 dm: SLiM v: 1.3.6 Distro: antiX-19.3_x64-full Manolis Glezos
    15 October 2020 base: Debian GNU/Linux 11 (bullseye)

**Comment by pbek** [comment]
Could be, that the kernel is older than the Ubuntu 18.04 appimage allows. Did you try the Debian repository?

**Comment by dukester** [comment]
> Did you try the Debian repository?
I did - and I ran into dependency problems. That's why I gave the AppImage a shot - thinking that it might be like a pre-built binary.

**Comment by pbek** [comment]
AppImages need a certain base level version of locally installed libraries... In this case, the minimum glibc version and so on of Ubuntu 18.04.

**Comment by pbek** [comment]
But I wonder why the Debian 11 repository didn't work for you...
