### ISSUE TITLE
[I] Todos and NextCloud

### ISSUE THREAD

**Issue by Elwood4415** [pbek/QOwnNotes#2971]
Please paste t#### Expected behaviour

When I connect QOwnnotes to NextCloud tasks in the Qownnotes settings menu, it will remember the connection.

#### Actual behaviour

After a period of time (it varies), or accessing the settings menu later, Qownnotes forgets the connection to NextCloud, and I must reset it.

#### Steps to reproduce

Open the settings menu
Select the todo tab
Connect Qownnotes to NextCloud
Select the task list
Close menu
Use Qownnotes for a while and/or reopen the settings menu
Click on the todo tab from the menu bar
It will tell you that the todo settings are not set

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fri Feb 23 20:43:34 2024`
**Version**: `24.2.5`
**Build date**: `Feb 17 2024`
**Build number**: `1082`
**Platform**: `linux`
**Operating System**: `Debian GNU/Linux 12 (bookworm)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.15.8`
**Qt Version (runtime)**: `5.15.8`
**Portable mode**: `no`
**Settings path / key**: `/home/hank/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/hank/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080`
**Icon theme**: `Papirus-mxblue-darkpanes`
**Notes in current note folder**: `5`
**Calendar items**: `4`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: `https://liv.nl.tab.digital`
**appIsValid**: `no`
**notesPathExists**: `unknown`
**connectionErrorMessage**: `Error transferring https://liv.nl.tab.digital/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/Notes/ - server replied: Not Found`

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_GB, en_US`
**Language names**: `British English (United Kingdom), American English (United States)`
**Application dictionaries path**: `/home/hank/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/hank/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `yes`
**activeNoteSubFolder name**: `Journal`
**database file**: `/home/hank/Nextcloud/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://liv.nl.tab.digital`
**username**: `hank@iname.com`
**accountId**: `hank@iname.com`

### Script `Journal entry`

**id**: `1`
**path**: `/home/hank/.local/share/PBE/QOwnNotes/scripts/journal-entry/journal-entry.qml`
**variablesJson**: 
```
{
    "defaultTags": "journal",
    "noteBodyTemplate": "",
    "singleJournalPerDay": true
}
```
**identifier**: `journal-entry`
**version**: `1.6.0`
**minAppVersion**: `20.4.16`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (bool): `false`
**Editor/showLineNumbers** (bool): `false`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2024-02-23T20:28:33.436`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Sermons`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,10.5,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10.5,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.refreshDebounceTime** (int): `600`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**NoteFolder-1/NoteTabNameList** (QStringList): `Journal 20240223`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `Journal`
**NoteFolder-1/allowDifferentNoteFileName** (bool): `true`
**NoteHistory-1** (QVariantList): `<variant list with 11 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `10`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-customAction_journalEntry** (QKeySequence): `Ctrl+Alt+J`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (int): `0`
**TodoDialog/showDueTodayItemsOnly** (int): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Tasks`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**autoReadOnlyMode** (bool): `false`
**autoReadOnlyModeTimeout** (int): `30`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `hc2yVDknN5Fp`
**cursorWidth** (int): `1`
**darkMode** (bool): `false`
**darkModeColors** (bool): `false`
**darkModeIconTheme** (bool): `false`
**darkModeTrayIcon** (bool): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**enableWebAppSupport** (bool): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (int): `11`
**interfaceLanguage** (QString): *empty*
**interfaceStyle** (QString): `gtk2`
**internalIconTheme** (bool): `false`
**itemHeight** (int): `22`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelAutoSelect** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `true`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `0`
**noteSubfoldersPanelTabsUnsetAllNotesSelection** (bool): `false`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `/home/hank/Nextcloud/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Tasks`
**ownCloud/todoCalendarEnabledList** (QStringList): `Tasks`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://liv.nl.tab.digital/remote.php/dav/calendars/hank@iname.com/tasks/`
**ownCloud/todoCalendarUrlList** (QStringList): `https://liv.nl.tab.digital/remote.php/dav/calendars/hank@iname.com/tasks/`
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): `Error transferring https://liv.nl.tab.digital/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/Notes/ - server replied: Not Found`
**ownCloudInfo/notesPathExistsText** (QString): `unknown`
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (bool): `true`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2024-02-23T18.12.59, Note 2024-02-23T18.06.15`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**startInReadOnlyMode** (bool): `false`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `true`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShare_note, , actionShow_Todo_List, customAction_journalEntry, customAction_journalEntryTomorrow, customAction_journalEntryDate`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/7/items** (QStringList): *empty*
**toolbar/7/name** (QString): `custom_toolbar_1`
**toolbar/7/title** (QString): `custom_toolbar_1`
**toolbar/size** (int): `7`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (int): `22222`
**workspace-F6tvFRD8sF4g/name** (QString): `Minimal`
**workspace-F6tvFRD8sF4g/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-F6tvFRD8sF4g/windowState** (QByteArray): `<binary data>`
**workspace-hc2yVDknN5Fp/name** (QString): `Full`
**workspace-hc2yVDknN5Fp/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-hc2yVDknN5Fp/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, F6tvFRD8sF4g, hc2yVDknN5Fp`

## System environment

**QT_SCALE_FACTOR**: `1`
**USER**: `hank`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `3067`
**QT_PLATFORMTHEME**: `gtk2`
**HOME**: `/home/hank`
**DESKTOP_SESSION**: `xfce`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**GTK_MODULES**: `canberra-gtk-module:gail:atk-bridge`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/tmp/dbus-j9emeKzyZR,guid=a7105954a33bd3d0fbc6694465d902ae`
**QT_QPA_PLATFORMTHEME**: `gtk2`
**LOGNAME**: `hank`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_ID**: `1`
**PATH**: `/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`
**GDM_LANG**: `en_US.UTF-8`
**PAPERSIZE**: `letter`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_MENU_PREFIX**: `xfce-`
**DISPLAY**: `:0`
**LANG**: `en_US.UTF-8`
**XDG_CURRENT_DESKTOP**: `XFCE`
**XDG_SESSION_DESKTOP**: `xfce`
**XAUTHORITY**: `/home/hank/.Xauthority`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm/data/hank`
**SSH_AUTH_SOCK**: `/tmp/ssh-XXXXXXp1AWt0/agent.2967`
**SHELL**: `/bin/bash`
**GDMSESSION**: `xfce`
**QT_ACCESSIBILITY**: `1`
**QT_LOGGING_RULES**: `qt.qpa.xcb.warning=false`
**XDG_VTNR**: `7`
**PWD**: `/home/hank`
**XDG_DATA_DIRS**: `/usr/share/xfce4:/home/hank/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share`
**XDG_CONFIG_DIRS**: `/etc/xdg`
**QT_PLATFORM_PLUGIN**: `gtk2`
**SESSION_MANAGER**: `local/Lenovo-1:@/tmp/.ICE-unix/2967,unix/Lenovo-1:/tmp/.ICE-unix/2967`
**PANEL_GDK_CORE_DEVICE_EVENTS**: `0`
**GIO_LAUNCHED_DESKTOP_FILE**: `/usr/share/applications/PBE.QOwnNotes.desktop`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `43653`
</details>

he text from the issue assistant here. It should be already in your clipboard.

**Comment by pbek** [comment]
Hm, currently I can see that the Calendar settings are present in your configuration.
How do the settings look when the settings are "forgotten"?

**Comment by Elwood4415** [comment]
Thank you for responding so quickly, but I am not sure I understand your question.  The task calendar is simply unchecked. I am attaching a screen shot. The steps I used: I opened Qownnotes, clicked on Settings, then ToDo and the task list was checked. I closed settings, clicked on the Task button on the toolbar, the list opened with my tasks listed. I closed that, clicked on settings, then ToDo, and saw the window as shown in the attached screenshot--with the task calendar unchecked.

![Screenshot_2024-02-24_00-46-42](https://github.com/pbek/QOwnNotes/assets/87457335/1fe0ee8b-db28-458a-90e6-f9adfbe838f8)

**Comment by pbek** [comment]
Hm, strange. I wonder if there was a connection error to the server when the calendar list could not be loaded...
Are there any logs when that happend?

Is there any useful log output if you enable the log panel (see Window / Panels)?
Please make sure you also enable debug logging in the log panel by right-clicking on the panel and selecting `Debug` in `Options`.

Nowadays, I only use Nextcloud Deck with the QOwnNotes integration for it. Much more comfortable and less annoying than CalDAV...

**Comment by Elwood4415** [comment]
I wasn't sure how to attach the log data, so I put it into a text file and I am attaching it to this message. Hope it helps. 

I am open to using Nextcloud Deck, but I wasn't aware of it until you mentioned it. I activated it in the Nextcloud settings in Qownnotes, but I don't know what to do after that. I don't see anyway to access the cards I have set in Nextcloud.

Also, I have read about QownnotesAPI, but I am totally confused about that. I have downloaded it, but I don't know what to do after that--how or where to install it. And I haven't been able to find any instructions that explain it on my level (which is pretty basic). I don't know if that is part of my problem or not.

I very much appreciate your assistance, and welcome any guidance you can offer. But, as I said earlier, I am at a pretty basic level and need simple directions. Thank you.

[QOwnNotes Log.txt](https://github.com/pbek/QOwnNotes/files/14399663/QOwnNotes.Log.txt)

**Comment by pbek** [comment]
> I am open to using Nextcloud Deck, but I wasn't aware of it until you mentioned it. I activated it in the Nextcloud settings in Qownnotes, but I don't know what to do after that. I don't see anyway to access the cards I have set in Nextcloud.

You can create deck cards and insert the link to it into the note (search in the main menu) with a shortcut.

> Also, I have read about QownnotesAPI, but I am totally confused about that. I have downloaded it, but I don't know what to do after that--how or where to install it. And I haven't been able to find any instructions that explain it on my level (which is pretty basic). I don't know if that is part of my problem or not.

It's explained on the settings page and https://www.qownnotes.org/getting-started/qownnotesapi.html.

> [QOwnNotes Log.txt](https://github.com/pbek/QOwnNotes/files/14399663/QOwnNotes.Log.txt)

Can't see anything special in it...
