### ISSUE TITLE
[BUG] Text between two wildcards in code block in bullet point list gets stylized

### ISSUE THREAD

**Issue by o-l-a-v** [pbek/QOwnNotes#2972]
Text between two wildcards inside separate inline code blocks gets stylized as italic, but only in the editor pane.

QOwnNotes v24.2.5 on Windows.

#### Expected behaviour

Editor:

```markdown
* This `*` is a `*` test
```

Preview:

* This `*` is a `*` test

#### Actual behaviour

![image](https://github.com/pbek/QOwnNotes/assets/6450056/632c342b-d9a8-475a-ae32-7b2d8f98c689)

#### Steps to reproduce

Shown above.

#### Output from the debug section in the settings dialog

No crash, so not relevant?

#### Relevant log output in the Log panel

No crash, so not relevant?

**Comment by pbek** [comment]
Thank you for reporting.

@Waqar144, have you seen this? 😊

**Comment by Waqar144** [comment]
No, but its a bug the qmarkdowntextedit

**Comment by pbek** [comment]
Do you think it is feasible to fix?

**Comment by Waqar144** [comment]
Yes, should be a relatively simple fix I think.

**Comment by pbek** [comment]
Awesome, do you care to fix it? 🥳🎉😊

**Comment by pbek** [comment]
## 24.3.5
- Now text between two asterisks in in-line code blocks in a bullet point list gets
  highlighted correctly (for [#2972](https://github.com/pbek/QOwnNotes/issues/2972), thank you, @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by o-l-a-v** [comment]
Great. Yup, seems to work.

<img width="185" alt="image" src="https://github.com/pbek/QOwnNotes/assets/6450056/f24f1298-4e4c-4e5b-95a9-4a37302bf80a">

**Comment by pbek** [comment]
Great, thank you for testing!
