### ISSUE TITLE
[FEATURE] Show previous path in "note folder not found" error message

### ISSUE THREAD

**Issue by abraxas86** [pbek/QOwnNotes#2975]
#### Is your feature request related to a problem? Please describe.
When the application is unable to locate your notes folder, it throws the following message: 

> Your note folder was not found any more! Do you want to select a new one?

It never shows the old path, and I'm not sure if the path will be overwritten if I select "Yes" and give it a new location.  The problem is that sometimes my drive orders get messed up due to removable media and cloud storage.  If I could see what the path used to be, I'd be able to relocate it without issue.

#### Describe the solution you'd like
I'd like if the error message provided the former path, or gave the option to view the former path.

#### Describe alternatives you've considered
I can't really think of an alternative other than trying to figure out what file extension the application uses so I can dive into my storage locations to manually locate the files.

**Comment by pbek** [comment]
https://github.com/pbek/QOwnNotes/blob/56b949b5c59d939e21d320899b4455acc244ec46/src/main.cpp#L261-L265

Sounds like a good, idea. Thank you.

**Comment by abraxas86** [comment]
> https://github.com/pbek/QOwnNotes/blob/56b949b5c59d939e21d320899b4455acc244ec46/src/main.cpp#L261-L265
> 
> Sounds like a good, idea. Thank you.

No, thank you!  I was able to find my files in the end, I was smart when I made the folder (for once lmao).

I'll see what I can do to patch it in there.  I suspect the harder part may be figuring out how to git properly 😅

I guess if I fork it, fix it, push it, and then create a pull request?

**Comment by pbek** [comment]
Yes, you can 😉

**Comment by pbek** [comment]
## 24.3.0
- in the `Note folder not found!` dialog, the missing note folder path will now be shown

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by abraxas86** [comment]
Worked like a charm!  Thanks.  Sorry for not doing it myself - been crazy busy with stuff at work trying to race a deadline.  Once this storm has passed, I have some ideas on how we might be able to make that error even better.  I won't be able to get started on that for another week or two, though.

**Comment by pbek** [comment]
Great, thank you for testing!
No problem. 😉
