### ISSUE TITLE
[I] can't follow [[wiki linked]] file links that have spaces

### ISSUE THREAD

**Issue by cedardocster** [pbek/QOwnNotes#2978]
#### Expected behaviour

I have the wiki links script activated.    
  
If I click on [[any link with spaces in the filename]] it should either navigate to that note or start a new note by that name

#### Actual behaviour

instead I get a popup "Note was not found, create new note 'any-link-with-spaces-in-the-filename'?"

#### Steps to reproduce

activate Wiki links script.  [[LinksWithNo-Spaces]] are correctly navigated to but not the above scenario

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sun. Mar. 3 11:46:23 2024`
**Version**: `24.2.6`
**Build date**: `Mar  1 2024`
**Build number**: `1083`
**Platform**: `linux`
**Operating System**: `Ubuntu Core 22`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Snapcraft`
**Qt Version (build)**: `5.15.3`
**Qt Version (runtime)**: `5.15.3`
**Portable mode**: `no`
**Settings path / key**: `/home/david/snap/qownnotes/11241/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/david/snap/qownnotes/11241/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/snap/qownnotes/11241/usr/bin/QOwnNotes`, `-style=Breeze`, `--snap`
**Qt Debug**: `0`
**Locale (system)**: `en_CA`
**Locale (interface)**: *empty*
**Primary screen resolution**: `3840x2160`
**Screen resolution(s)**: `3840x2160, 1050x1680`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `9785`
**Calendar items**: `0`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `en_US`
**Language codes**: `en_US`
**Language names**: `American English (United States)`
**Application dictionaries path**: `/home/david/snap/qownnotes/11241/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/david/SyncthingFolders/ZettlrMarkor`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/david/SyncthingFolders/ZettlrMarkor/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

### Script `Wiki Links`

**id**: `1`
**path**: `/home/david/snap/qownnotes/11241/.local/share/PBE/QOwnNotes/scripts/wiki-links/wiki-links.qml`
**variablesJson**: 
```
{
    "wikilinksBackgroundColor": "#FFFF00",
    "wikilinksForegroundColor": "#ff832b",
    "wikilinksHideSubfolder": true,
    "wikilinksLowerCase": true,
    "wikilinksRemoveSpaces": true,
    "wikilinksReplaceSpacesSymbol": "-",
    "wikilinksSanitizeFilename": true
}
```
**identifier**: `wiki-links`
**version**: `0.0.1`
**minAppVersion**: `20.6.0`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/removeTrailingSpaces** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2024-03-03T11:38:30.883`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MessageBoxOverride/linux-dark-mode** (QString): `16384`
**MessageBoxOverride/note-replace-links** (QString): `65536`
**MessageBoxOverride/open-url-create-note** (QString): `65536`
**NoteFolder-1/NoteTabNameList** (QStringList): `2024-03-03,  [[2024-03-01|Fri 01 Mar 2024]]`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `, `
**NoteHistory-1** (QVariantList): `<variant list with 15 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `14`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**checkSpelling** (bool): `true`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**dockWasInitializedOnce** (QString): `true`
**guiFirstRunInit** (bool): `true`
**initialLayoutIdentifier** (QString): `full`
**itemHeight** (QString): `23`
**markdownHighlightingEnabled** (QString): `true`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**notesPath** (QString): `/home/david/SyncthingFolders/ZettlrMarkor`
**ownCloud/supportEnabled** (QString): `false`
**savedSearches/noteFolder-1** (QString): `2024-03-03`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `en_US`
**webAppClientService/token** (QString): `<hidden>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**SHELL**: `/bin/bash`
**SESSION_MANAGER**: `local/HPe:@/tmp/.ICE-unix/38336,unix/HPe:/tmp/.ICE-unix/38336`
**QT_ACCESSIBILITY**: `1`
**__EGL_VENDOR_LIBRARY_DIRS**: `/var/lib/snapd/lib/glvnd/egl_vendor.d:/snap/qownnotes/11241/etc/glvnd/egl_vendor.d:/snap/qownnotes/11241/usr/share/glvnd/egl_vendor.d`
**SNAP_REVISION**: `11241`
**XDG_CONFIG_DIRS**: `/snap/qownnotes/11241/etc/xdg:/etc/xdg/xdg-ubuntu-xorg:/etc/xdg`
**SSH_AGENT_LAUNCHER**: `gnome-keyring`
**XDG_MENU_PREFIX**: `gnome-`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**GTK_IM_MODULE**: `ibus`
**SNAP_REAL_HOME**: `/home/david`
**SNAP_USER_COMMON**: `/home/david/snap/qownnotes/common`
**QTCOMPOSE**: `/snap/qownnotes/11241/usr/share/X11/locale`
**FONTCONFIG_PATH**: `/snap/qownnotes/11241/etc/fonts`
**LANGUAGE**: `en_CA:en`
**MANDATORY_PATH**: `/usr/share/gconf/ubuntu-xorg.mandatory.path`
**GNOME_SHELL_SESSION_MODE**: `ubuntu`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**XDG_DATA_HOME**: `/home/david/snap/qownnotes/11241/.local/share`
**XDG_CONFIG_HOME**: `/home/david/snap/qownnotes/11241/.config`
**XCURSOR_PATH**: `/snap/qownnotes/11241/data-dir/icons:/snap/qownnotes/11241/usr/share/icons`
**SNAP_INSTANCE_KEY**: *empty*
**XMODIFIERS**: `@im=ibus`
**DESKTOP_SESSION**: `ubuntu-xorg`
**GDK_PIXBUF_MODULE_FILE**: `/home/david/snap/qownnotes/common/.cache/gdk-pixbuf-loaders.cache`
**BAMF_DESKTOP_FILE_HINT**: `/var/lib/snapd/desktop/applications/qownnotes_qownnotes.desktop`
**GTK_MODULES**: `gail:atk-bridge`
**ZEITGEIST_DATA_PATH**: `/home/david/.local/share/zeitgeist`
**SNAP_EUID**: `1000`
**PWD**: `/home/david`
**LOGNAME**: `david`
**XDG_SESSION_DESKTOP**: `ubuntu-xorg`
**QT_QPA_PLATFORMTHEME**: `gtk3`
**XDG_SESSION_TYPE**: `x11`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**SYSTEMD_EXEC_PID**: `2984141`
**GIT_COMMITTER_NAME**: `QOwnNotes`
**XAUTHORITY**: `/run/user/1000/gdm/Xauthority`
**TEMPDIR**: `/tmp`
**SNAP_CONTEXT**: `HBNZFpt1vR04ZG18FKsWJULnTy6gKz8fauZY1n2GSef-IP2DaZbR`
**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`
**WINDOWPATH**: `2`
**GST_PLUGIN_SCANNER**: `/snap/qownnotes/11241/usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner`
**GIT_EXEC_PATH**: `/snap/qownnotes/11241/usr/lib/git-core`
**HOME**: `/home/david/snap/qownnotes/11241`
**USERNAME**: `david`
**LANG**: `en_CA.UTF-8`
**XDG_CURRENT_DESKTOP**: `ubuntu:GNOME`
**QTWEBENGINEPROCESS_PATH**: `/snap/qownnotes/11241/usr/lib/x86_64-linux-gnu/qt5/libexec/QtWebEngineProcess`
**SNAP_ARCH**: `amd64`
**SNAP_INSTANCE_NAME**: `qownnotes`
**SNAP_USER_DATA**: `/home/david/snap/qownnotes/11241`
**DISABLE_WAYLAND**: `1`
**TMPDIR**: `/tmp`
**INVOCATION_ID**: `2f9d45478ced4b4a8dea07d6318389a9`
**SNAP_LAUNCHER_ARCH_TRIPLET**: `x86_64-linux-gnu`
**MANAGERPID**: `25238`
**SNAP_REEXEC**: *empty*
**GIT_AUTHOR_EMAIL**: `snap@qownnotes.git`
**SNAP_UID**: `1000`
**QT_QPA_PLATFORM**: `xcb`
**XDG_CACHE_HOME**: `/home/david/snap/qownnotes/common/.cache`
**QT_PRINTER_MODULE**: `qtubuntu-print`
**GJS_DEBUG_OUTPUT**: `stderr`
**GIT_COMMITTER_EMAIL**: `snap@qownnotes.git`
**XDG_SESSION_CLASS**: `user`
**GTK_PATH**: `/snap/qownnotes/11241/usr/lib/x86_64-linux-gnu/gtk-2.0`
**XLOCALEDIR**: `/snap/qownnotes/11241/usr/share/X11/locale`
**DEFAULTS_PATH**: `/usr/share/gconf/ubuntu-xorg.default.path`
**USER**: `david`
**GIT_TEMPLATE_DIR**: `/snap/qownnotes/11241/usr/share/git-core/templates`
**SNAP**: `/snap/qownnotes/11241`
**SNAP_COMMON**: `/var/snap/qownnotes/common`
**SNAP_VERSION**: `24.2.6`
**DISPLAY**: `:1`
**SHLVL**: `1`
**GDK_PIXBUF_MODULEDIR**: `/snap/qownnotes/11241/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders`
**LOCPATH**: `/snap/qownnotes/11241/usr/lib/locale`
**SNAP_LIBRARY_PATH**: `/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void`
**SNAP_COOKIE**: `HBNZFpt1vR04ZG18FKsWJULnTy6gKz8fauZY1n2GSef-IP2DaZbR`
**QT_IM_MODULE**: `ibus`
**LIBGL_DRIVERS_PATH**: `/snap/qownnotes/11241/usr/lib/x86_64-linux-gnu/dri`
**SNAP_DATA**: `/var/snap/qownnotes/11241`
**GST_PLUGIN_PATH**: `/snap/qownnotes/11241/usr/lib/x86_64-linux-gnu/gstreamer-1.0`
**QML2_IMPORT_PATH**: `/snap/qownnotes/11241/usr/lib/x86_64-linux-gnu/qt5/qml`
**LD_LIBRARY_PATH**: `/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/qownnotes/11241/lib:/snap/qownnotes/11241/usr/lib:/snap/qownnotes/11241/usr/lib/x86_64-linux-gnu:/snap/qownnotes/11241/usr/lib/x86_64-linux-gnu/dri`
**XDG_RUNTIME_DIR**: `/run/user/1000/snap.qownnotes`
**QTCHOOSER_NO_GLOBAL_DIR**: `1`
**GST_PLUGIN_SYSTEM_PATH**: `/snap/qownnotes/11241/usr/lib/x86_64-linux-gnu/gstreamer-1.0`
**EMAIL**: `snap@qownnotes.git`
**FONTCONFIG_FILE**: `/snap/qownnotes/11241/etc/fonts/fonts.conf`
**SNAP_NAME**: `qownnotes`
**JOURNAL_STREAM**: `8:53988444`
**XDG_DATA_DIRS**: `/home/david/snap/qownnotes/11241/.local/share:/home/david/snap/qownnotes/11241:/snap/qownnotes/11241/data-dir:/snap/qownnotes/11241/usr/share:/usr/share/ubuntu-xorg:/usr/share/gnome:/home/david/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop`
**GIT_AUTHOR_NAME**: `QOwnNotes`
**PATH**: `/snap/qownnotes/11241/usr/sbin:/snap/qownnotes/11241/usr/bin:/snap/qownnotes/11241/sbin:/snap/qownnotes/11241/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`
**GDMSESSION**: `ubuntu-xorg`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**VDPAU_DRIVER_PATH**: `/var/lib/snapd/lib/gl/vdpau`
**QT_PLUGIN_PATH**: `/snap/qownnotes/11241/usr/lib/x86_64-linux-gnu/qt5/plugins`
**GIO_MODULE_DIR**: `/home/david/snap/qownnotes/common/.cache/gio-modules`
**QT_SELECT**: `snappy-qt5`
**PULSE_SERVER**: `unix:/run/user/1000/snap.qownnotes/../pulse/native`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `3252184`
**XKB_CONFIG_ROOT**: `/snap/qownnotes/11241/usr/share/X11/xkb`
**GIO_LAUNCHED_DESKTOP_FILE**: `/var/lib/snapd/desktop/applications/qownnotes_qownnotes.desktop`
</details>

**Comment by pbek** [comment]
Can you please open that issue on https://github.com/qownnotes/scripts/issues?

And can you please mention the authors of the script, like advised in the issue template there?
You will find the authors in the *Script repository*.
Don't forget to use the `@` symbol to mention them.
