### ISSUE TITLE
[FEATURE] ask about first line file rename when picking non default note folder

### ISSUE THREAD

**Issue by cedardocster** [pbek/QOwnNotes#2979]
#### Is your feature request related to a problem? Please describe.
- I almost rage-quit Qownnotes because I add new items to the top of my daily note files. I'd think I was in 2024-03-05.md and then all of a sudden I was in - [ ] remember the milk!  I'd go back to Obsidian after a WTF moment for a while, then try again. I finally realized there was a method to the madness (thought it was a glitch at first) so I started looking for a solution. For non-date-notes I often have a YAML (I think that's what they're called) heading, so all those notes would be renamed "---"

#### Describe the solution you'd like
- when a new folder is chosen (especially if not empty) there should be a pop up to turn off "rename as first line"
- perhaps when picking a new folder the software could pick 100 random files to check if the filenames currently match the first line and only ask if any of them don't match

#### Describe alternatives you've considered
- change my entire notes system (a hundred bash scripts and 10,000 notes so far)? No thank you

#### Additional context
- as there are a lot of different plain text note systems out there your bound to get a lot of shoppers kicking the tires from other systems - the easier you make the transition the more will stick

**Comment by pbek** [comment]
Like already mentioned in the chat... There is a setting you might want to look at:

![image](https://github.com/pbek/QOwnNotes/assets/1798101/8aec59ff-a608-4679-8f7f-05839cbe0478)
