### ISSUE TITLE
ToDo List - Unable to find ownCloud Calendar

### ISSUE THREAD

**Issue by iliesh** [pbek/QOwnNotes#298]
QOwnNotes can not find calendars for Todo settings if format of authenticated user contain . (dot). For example **name.surname**
![qownnotes](https://cloud.githubusercontent.com/assets/14953151/17830511/609c191a-66d6-11e6-8a24-10a576f842af.JPG)

## General Info
**Version**: `16.08.14`
**Build date**: `Aug 19 2016`
**Build number**: `2058`
**Platform**: `windows`
**Operating System**: `Windows 10`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.5.1`
**Qt Version (runtime)**: `5.5.1`
**Qt Debug**: `0`
**Locale (interface)**: `en`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `14`
**Enabled scripts**: `0`

## Server Info
**appIsValid**: `yes`
**serverVersion**: `9.1.0.15`
**appVersion**: `0.4.4`

**Comment by pbek** [comment]
I please need more information about your owncloud settings from the debug output (everything from `ownCloud/*`).
And did you select which calendars you want to sync in the todo settings?

**Comment by iliesh** [comment]
> did you select which calendars you want to sync in the todo settings?
Not, i did not - because there are not calendars available. (In owncloud framework calendar module are activated and there are default calendar.)

**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: `https://myserver.com`
**ownCloud/todoCalendarBackend**: `0`
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloud/userName**: `user.name`

**Comment by pbek** [comment]
Are you sure you have typed in your user name with the correct case? ownCloud's webdav api is case sensitive.

**Comment by pbek** [comment]
In #229 there were discussed similar problems...
And is there any useful output in the log window?

**Comment by iliesh** [comment]
I found the issue, and there is how i solved:
We are using external users from LDAP servers, and by default username are created from the **UUID attribute**. Changing "**Internal Username Attribute**:" on Expert Settings to **sAMAccountName** - solved the issue, now i'm able to see calendars on Todo Settings.
Thank You pbek for your help and for prompt answer.

**Comment by pbek** [comment]
Thank you for posting your solution!

**Comment by pbek** [comment]
Great to hear!
