### ISSUE TITLE
[SUPPORT] Need help installing QOwnNotes

### ISSUE THREAD

**Issue by zbh0005** [pbek/QOwnNotes#2983]
#### Question
Hello, I just need help installing QOwnNotes on my Windows 11 system. I am a beginner, and when reading the installation page I am confused because it says to unzip the folder from GitHub anywhere. I unzipped in my documents folder and then looked for the QOwnNotes.exe as directed on the installation page. However, I couldn't find any such file. I don't want to build it myself, I am just trying to use base functionality.

**Comment by Kvcd12** [comment]
Did you download from here:

https://github.com/pbek/QOwnNotes/releases

Did you download this file:  QOwnNotes.zip

**Comment by zbh0005** [comment]
Yes I downloaded that zip and extracted all files

**Comment by pbek** [comment]
Maybe your Windows defender got rid of the exe...

**Comment by zbh0005** [comment]
Okay I found my issue, I downloaded the wrong zip file. I thought I had downloaded the QOwnNotes.zip, but in reality I had downloaded Source Code (zip). Thank you for your help!

**Comment by pbek** [comment]
Gereat 😉
