### ISSUE TITLE
[BUG] Doesn't want to connect to Nextcloud

### ISSUE THREAD

**Issue by Johnephen** [pbek/QOwnNotes#2984]
#### Expected behaviour
I used the procedure that tells you to integrate Nextcloud. There I solved it with the web link and everything completed itself. Seemed to work straight away, even with my reversed proxy. Then it should actually sync the notes with Nextcloud.
#### Actual behaviour
just gives me the error and the website (https://mysite.com/ocs/v2.php/apps/files_sharing/api/v1/shares) says "Access prohibited: CSRF check failed"
[23:16:57] [warning] "QNetworkReply error 203 from url https://mysite.com/ocs/v2.php/apps/files_sharing/api/v1/shares: " "Error transferring https://mysite.com/ocs/v2.php/apps/files_sharing/api/v1/shares - server replied: Not Found"

#### Steps to reproduce
Platform: Windows 11
URL via reverse proxy and Cloudflare
Registration/access between QOwnNotes and NC took place automatically via NC
via the top bar the “Share note”

#### Output from the debug section in the settings dialog
[23:16:57] [warning] "QNetworkReply error 203 from url https://nextcloud.johnipgerman.site/ocs/v2.php/apps/files_sharing/api/v1/shares: " "Error transferring https://nextcloud.johnipgerman.site/ocs/v2.php/apps/files_sharing/api/v1/shares - server replied: Not Found"
<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
> Access prohibited: CSRF check failed

That's weird, I don't know why your Nextcloud is asking for a CSFR token there. QOwnNotes is just using the AppPassword, that was generated with the Nextcloud Login Flow for everything. Maybe ask in the Nextcloud Discourse?

**Comment by pbek** [comment]
Are your notes stored on your Nextcloud server? Do you have the correct folder set-up (you didn't share your settings).

**Comment by Johnephen** [comment]
Please excuse my problems. I had fundamental problems installing Nextcloud. That's why in the future I will simply mirror the data via Syncthings or Gitlab. It's not the intended solution, but I think it will work better for me this way. Thanks again for addressing this so quickly.

**Comment by pbek** [comment]
I wonder what the problems were, you seemed knowledgeable to me about the fundamentals of how to run a web server.
