### ISSUE TITLE
[FEATURE] "Preview only mode" - Make editor pane a panel that can be disabled

### ISSUE THREAD

**Issue by o-l-a-v** [pbek/QOwnNotes#2985]
#### Is your feature request related to a problem? Please describe.

No, not really a problem.

#### Describe the solution you'd like

I was looking for a way to hide the note edit pane / panel, but couldn't find it.

It would be great if the editor pane too could be considered a panel like all other panels.

<img width="677" alt="image" src="https://github.com/pbek/QOwnNotes/assets/6450056/2cdfe019-7475-4a56-92df-339be7cb5691">

Workflows it could enable:

* Go through existing notes from the note folder and search panels to the left, with only the preview pane to the right.
* Preview only mode, no other active panels.

#### Describe alternatives you've considered

None so far.

#### Output from the debug section in the settings dialog

Not a bug/crash/error, so no logs needed.

**Comment by pbek** [comment]
I think what you are looking for is the checkbox to turn off the central widget (that's the editor panel) in the settings

**Comment by o-l-a-v** [comment]
Ahh. So first:

* Note -> Settings -> Interface -> Panels -> Note edit panel: Disable "Use the note edit panel as fixed central widget to be resized if the window or other panels are resized".

Then the note edit panel appears as any other panel in Windows -> Panels.

**Comment by pbek** [comment]
Exactly... 😉
