### ISSUE TITLE
[FEATURE] VCS trackable configuration file separate from note history, window positions, etc.

### ISSUE THREAD

**Issue by zacstewart** [pbek/QOwnNotes#2989]
I like to keep all my system configs in Git so that I can easily keep my setup uniform across multiple workstations. Regarding QOwnNotes I have to repeatedly configure things like my preferred date format. I would like to track QOwnNotes.conf, but upon doing so I realized that it's leaking information about the contents of my notes through history. I think it would be a good idea if things that you configure via the Settings window were separated from other kinds of data, like note history.

**Comment by pbek** [comment]
I don't know what OS you are using (you haven't filled out the issue template), but since you are using dotfiles, I guess it's not Windows. 😉

Would be hard to split settings or even decide what to go where or to invent some translation layer that would work on different computers...

That's why I created a "portable-mode" (see settings), but it's mainly used by Windows people. Everything is relative to the path of the executable.

**Comment by pbek** [comment]
I myself am using QOwnNotes on 10+ computers, but I never felt the need for shared configuration. I even have different needs on how QOwnNotes should look or behave on every machine...

**Comment by pbek** [comment]
I can't see any real GUI desktop app in https://github.com/zacstewart/dotfiles... I haven't seen any desktop app attempting to do a thing that you wish for yet, but I'm curious since I use NixOS and Home-Manager myself (https://github.com/pbek/nixcfg). So I always try to max out declarativeness . 😉

**Comment by zacstewart** [comment]
Yeah most of my dotfiles are for sure CLI-related. I use both Arch and macOS. It might be infeasible, but I thought I'd throw it out there. If it was feasible I would be willing to give it a shot myself. I love QOwnNotes and use it all day every day. I'd love to be a contributor.

**Comment by pbek** [comment]
I think I even created a workaround to make the portable-mode work with AppImages in:

https://github.com/pbek/QOwnNotes/blob/73ff92af86676334d9c9ecd684be0a4c56ce4c42/src/utils/misc.cpp#L899-L904
