### ISSUE TITLE
Too many releases

### ISSUE THREAD

**Issue by RobertSmits** [pbek/QOwnNotes#299]
Ok I like regular releases en well maintained software,
but everyday a new release is just too much.
Definitely when there is no auto updater on windows.
Every time I open the program I get the new update available popup.

Is it possible to limit the releases to 1/month with the exception of security updates?

Or make a beta channel for the daily builds and a stable channel that gets updated once a month.

**Comment by pbek** [comment]
I'm sorry for the inconvenience. There are no beta or stable channels, because QOwnNote is using a rolling release cycle. But of course you can disable the update dialog in the settings. You will still get a small notification on the bottom right of the app that you can click when you feel like it.

**Comment by minthemiddle** [comment]
Actually I love the speed of how fast new features and bug fixes are being implemented in `QON` by @pbek. If you do not want to get bugged by the update window, go to `Settings > General` and unselect the `Show Updates Window` box.
