### ISSUE TITLE
[FEATURE] Edit Notes in a Second Window

### ISSUE THREAD

**Issue by maninthemiddle01** [pbek/QOwnNotes#2991]
As of my understanding, in QOwnNotes, there seems to be no direct way to edit a note in a second window. The shortcut `Ctrl + Shift + O` is designed to open the note in an external application, and the only other option for multitasking within the application is to open notes in new tabs. This limitation hinders workflow efficiency, especially for users who rely on multiple monitors or prefer to organize their workspace with separate windows.

## Suggested Feature
I propose the implementation of a feature that allows users to open and edit notes in a second window within QOwnNotes itself. This could potentially be activated by a new keyboard shortcut or an option in the right-click context menu of a note.

## Use Case
This feature would greatly benefit users who:
- Work with multiple monitors and wish to view and edit different notes simultaneously.
- Prefer to separate different tasks or topics into different windows for better organization.
- Need to compare or edit different notes side by side without the constraint of tab switching.

## Current Workarounds
As of now, users have to rely on either opening notes in different tabs within the same QOwnNotes window or using the `Ctrl + Shift + O` shortcut to open notes in an external application. Both methods are not ideal for quick comparisons or multitasking within the application.

Thank you for considering this feature request.

**Comment by pbek** [comment]
Sorry, there only can be one "current note" in QOwnNotes.
Although you can open several notes in different read-only windows.
And there are note tabs (read/write).

**Comment by pbek** [comment]
If it's only about a diff, you can select multiple notes to be sent to an external diff tool, like kdiff3.

**Comment by maninthemiddle01** [comment]
Thank you for your answer. It's not only about the diffs, my use case is that I also copy and paste things from one note to the other, so a split view with editing capabilities would be quite handy
