### ISSUE TITLE
[FEATURE] Export .html with relative links to create an interlinked knowledge base

### ISSUE THREAD

**Issue by netlimpopo** [pbek/QOwnNotes#2993]
#### Problem 
I use the script "Export all notes to website" to create a Doku-wiki for my students. I am always frustrated when I try to move my exported .html documents. Why? Exporting to .html uses static absolute fullpath links. 

For each link, I have to change the base folder.  Everytime I am planning to move my wiki, I have to manipulate it with VSC or Notepad in order to send them to pupils or collegues. Students can not move the files, without instructions to Notepad++ or VSC etc. In order to send it to collegues
Problem: the in-build Export function of QN only provides absolute links. Hence it is indepentent from the script implementation

#### Solution
Should not be too hard I hop? QN already establishes relative Markdownlinks. During export to .html these links are changed to absolute html paths. 
Stackedpro.io, Ghostwriter, dillinger.io all export with relative links in comparism. 
Solution: Add an option to export the .html with relative links. Also leave the current export mode for different cases

#### Describe alternatives you've considered
I copy the markdown file to stackeditpro.io,.... copy the generated html for single files.  
I use Zim to export a static html site. 

#### Additional context
Other Markdown editors also offer the option of simple html or formated html. 
Absolute paths are better for designing websites, as malicious redirecting to other sites can be limited (alsways redirects to the main domain). 
But as QN is designed for knowledge management rather then webdesign, I guess relative links would be a valuable addition.

**Comment by pbek** [comment]
It looks like what you are looking for is a static site generator, that is using Markdown files as source.

Demands to a static site generator a pretty high these days (Menus, Design, Search, SEO, ...) and there a real good one out already, like Hugo, Jekyll, VuePress, MKDocs, ...

I personally also use QOwnNotes to write blog entries for the QOwnNotes webpage, which is then generated from the Markdown files in VuePress...

I use static site generators for a lot of sites, the source is always a bunch of Markdown files.

**Comment by pbek** [comment]
E.g. https://www.mkdocs.org/ can also build you a local search index for your local knowledge base.

**Comment by netlimpopo** [comment]
Thank you for the suggestions and the tip! 
I agree static site generators are the next step and are a fanastic tool, which I have to dive deeper into. For the average user, they are rather cumbersome to set up first though. 

On the other hand in my workflow I use Zim and also Obsidian to quickly export my notes with one click export button. Both create movable websites very fast. Zim I can use in portable mode on any computer at work, same as with QN.
 This is especially useful for small projects to send them to students, where no big project page is needed or the site changes during the process of the work a bit. 
I thought I mention it, because QN is 97% there, as the "export as website" script is incredibly powerful and I pefer QN over Obsidian or Zim.  I think setting up a static site generator is quite for the advanced user and I dont always have my own Computer and my setup with me, in contrast to the .md or .zim files chilling in the cloud and portable Programms. 
Anyway, this is just food for thought, and speaking as an average QN user. 
I will stop ranting about it now lol. 
Thanks for this great programme and your time.

**Comment by netlimpopo** [comment]
P.s. I Know githubpages and stuff is also quite simplento set up. 😅

**Comment by pbek** [comment]
>  Thanks for this great programme and your time.

Thank you 😉

> During export to .html these links are changed to absolute html paths.

No, they already were for the preview...
But even if they wouldn't, what would links to `.md` files help you?

Anyway, you can do anything you dream of to the HTML with https://www.qownnotes.org/scripting/hooks.html#notetomarkdownhtmlhook and `forExport` set to true.

If you can come up with something useful to you, be sure to create a PR in https://github.com/qownnotes/scripts 😉
