### ISSUE TITLE
[FEATURE] Progress bar and/or tags for Todo's

### ISSUE THREAD

**Issue by Akselmo** [pbek/QOwnNotes#2998]
#### Is your feature request related to a problem? Please describe.
I like to use tags and progress in todos, so I would like to have those exposed
in the todo editor.

#### Describe the solution you'd like
Basically a slider for todo progress, input for comma separated tags, and change
the priority to spinbox or something i think.

#### Describe alternatives you've considered
I can change these from nextcloud or calendar apps directly but it seems those values
are overwritten when modified from qownnotes.

#### Additional context
I would not mind helping out with this and trying to create the feature(s) myself! :)

**Comment by Akselmo** [comment]
My problem with the deck for now is that I can't move items between boards from Qownnotes (unless I've missed something?)

But yeah I totally understand. I can give it a look myself at some point and see how much pain it is lol.


> Thank you for working on KDE. 😉 I'm a bit of a KDE fanboy myself. 😉

And thank you for using KDE stuff! :)

**Comment by Akselmo** [comment]
Hello, I think I got it to work, at least for me it seems to work nicely :) https://github.com/pbek/QOwnNotes/pull/3006

No tag support, just progress, which is good enough for my usecase.

**Comment by Akselmo** [comment]
Meanwhile I started the progress bar thing, i will look also into the tag support.

Considering we just read the tags from the incoming file, save them somewhere, expose a input field that allows editing them and then send them modified onwards, it should be relatively simple (famous last words), especially since we don't necessarily need to save them to the database at all.

Seems tags are just comma separated list of items `CATEGORIES:tag1,tag2` 

Honestly if progress bar is too much effort to get work well enough, tag system would also work for me, as I can then use tags to indicate the progress of the item (TODO, WAITING, CANCELED, DOING...). For me that would probably be even more useful than progress bar.

Of course would be cool to have both, but again if progress is too difficult and messy, tags will suffice for my usecase.

I'll start hacking on it and see how much effort it will be. :)

**Comment by Akselmo** [comment]
Alright, I did not make pull request yet but here's the tags support commit https://github.com/Akselmo/QOwnNotes/commit/73aabe291dfa6f40fa002389f513f296cc312ee4

Very similar and I had no issues, especially compared to progress bar.

I wonder if the input field should be something different? Something like the note tag system is, or drop down with input field or something.. 

![image](https://github.com/pbek/QOwnNotes/assets/13801236/3d989136-8d73-408d-85b7-807f1cb15b29)

**Comment by Akselmo** [comment]
I made a PR for the tags support. https://github.com/pbek/QOwnNotes/pull/3007

It should be much simpler to review. :)

**Comment by pbek** [comment]
> Edit: Seems the tags have to be saved to the database after all?

Why do you think so?

**Comment by Akselmo** [comment]
> > Edit: Seems the tags have to be saved to the database after all?
> 
> Why do you think so?

Seems the tags are loaded from the database instead when clicking on todo. It uses the uuid to search the todo item from the database and creates new calendar item based on whatever is in the database. During the initial sync everything is loaded from caldav and then all the info is placed to database.

... While writing this, I just realised the ics data is also saved to database. I can pull the information from there, which should make things much easier and I do not need to save the tags to database after all.

Seems I just needed to talk to someone to figure it out :joy:

**Comment by Akselmo** [comment]
No problem at all, thanks for the patience with reviewing. This app is now *perfect* for my workflow! :smile:

**Comment by Akselmo** [comment]
Aaaaa, oh no, last minute bug sneaked in!

At `tododialog.cpp` where I added the qt version check, there is `"."` but it should be `","`!

Line 834 and 836

**Comment by pbek** [comment]
Release is already out...

**Comment by pbek** [comment]
Please create another pull request.

**Comment by Akselmo** [comment]
Done, apologies again.. 

https://github.com/pbek/QOwnNotes/pull/3012

**Comment by pbek** [comment]
## 24.4.4
- Tag support for multiple tags was fixed for tasks in the *Todo dialog*
  (for [#2998](https://github.com/pbek/QOwnNotes/issues/2998), thank you, @Akselmo)

There now is a new release, could you please test it and report if it works for you?

**Comment by Akselmo** [comment]
Yup, all good on my end! :tada:

**Comment by pbek** [comment]
Great, thank you for testing (and thank you for the sponsor 😉)!
