### ISSUE TITLE
[FEATURE] Haiku support

### ISSUE THREAD

**Issue by win8linux** [pbek/QOwnNotes#2999]
#### Is your feature request related to a problem? Please describe.
QOwnNotes at the moment requires X11 on `UNIX` platforms, due to some libraries it needs. This prevents it from being compiled and run on Haiku.

#### Describe the solution you'd like
QOwnNotes and its libraries have Haiku support added, wherever necessary.

#### Describe alternatives you've considered
QOWnNotes and its libraries make use of [Xlibe](https://github.com/waddlesplash/xlibe), a compatibility layer for X11.

#### Additional context
Initial investigation suggests that aside from the main app, QHotkey specifically needs to have Haiku support written for it. Aside from not typically having X11, Haiku is otherwise usually considered a Unix/Unix-like platform. The Nextcloud client was recently ported to Haiku, spurring an initial attempt at getting QOwnNotes to compile and run on this OS.

**Comment by pbek** [comment]
I guess then you'd first need to open a feature request at https://github.com/Skycoder42/QHotkey, because other than that QOwnNotes mostly depends on Qt...

**Comment by win8linux** [comment]
Right, thanks! On another note, it seems that the future of QHotkey itself may be in question:
https://github.com/Skycoder42/QHotkey/issues/90

**Comment by pbek** [comment]
No Wayland support in QHotkey anyway... but the global shortcuts still work in X11
