### ISSUE TITLE
database connection

### ISSUE THREAD

**Issue by bottag** [pbek/QOwnNotes#30]
Hi. By starting the application, I get following error: unable to establish a database connection. This application needs SQLite support. I'm on MINT 17.3. Thanks.

**Comment by pbek** [comment]
Hello, @bottag ! Thank you for your report!

That's correct, QOwnNotes needs the QtSql and sqlite.

Did you use the Ubuntu PPA (I don't know if that even works under Linux Mint) or the Ubuntu deb-Package?

**Comment by bottag** [comment]
I used standalone deb-package (ppa doesn't work on mint)

**Comment by pbek** [comment]
In version 0.77 `libqt5sql5-sqlite` was added to the dependencies for the Ubuntu PPA build and the Ubuntu deb-package. It will take some minutes to build and be deployed. Can you please report back afterwards if it worked for you?
And thanks a lot again for the report!

**Comment by bottag** [comment]
Sorry, doesn't work :-(
Same message at the start. I've checked if the lib is installed: OK

**Comment by pbek** [comment]
Is the package `libsqlite3-0` also installed?

**Comment by bottag** [comment]
yes it is

**Comment by pbek** [comment]
I'm already downloading Linux Mint 17.3 and will take a look.

**Comment by pbek** [comment]
What terminal-output do you get if you run `QOwnNotes` on a terminal?

**Comment by bottag** [comment]
QDir::mkpath: Empty or null file name (and then window popup)

**Comment by pbek** [comment]
I got that too. It's really strange, Qt can't find a path to write to unter Linux Mint. I'll see what I can do.

**Comment by bottag** [comment]
Ok. But don't spend all your sunday on this problem !

**Comment by pbek** [comment]
Oh, I'm sorry. I just saw that Linux Mint 17.3 only has Qt 5.2.1 included. QOwnNotes needs at least Qt 5.3. You currently will not be able to run QOwnNotes. :(
I guess Linux Mint 18 will include a never version.

**Comment by bottag** [comment]
I installed how here described: https://www.reddit.com/r/linuxmint/comments/3skasc/notepadqq_you_are_using_an_old_version_of_qt_521/
Doesn't work too :-(
Ok will wait 6 months.

**Comment by pbek** [comment]
Which version of Qt is `qtdiag` showing you?

**Comment by bottag** [comment]
OK I solved this ! Using this tutorial (without the command line specific for PhotoQt): http://photoqt.org/down?popup=mint 

It works AFTER I reboot the computer. Now it work :-)

**Comment by pbek** [comment]
So it really was a problem with Qt. That's great!
Don't hesitate to report other problems and ideas.

**Comment by pbek** [comment]
Thank you again for the report. I now updated http://www.qownnotes.org/installation with instructions for older Ubuntu Linux distributions and derivatives!
