### ISSUE TITLE
Selection of some text works strange

### ISSUE THREAD

**Issue by LightTemplar** [pbek/QOwnNotes#300]
Very strange selection behavior. I recorded video from screen. It is attached with the note here:
[QOC Selection.zip](https://github.com/pbek/QOwnNotes/files/429145/QOC.Selection.zip)

It all done with keyboard only, with Shift+Up or Shift+Down keys. 

It happens only on this text, therefore I have also attached it.

**Comment by pbek** [comment]
Thank you for reporting, I watched the video. So what's the issue (expected behavior versus current behavior)? :)

**Comment by LightTemplar** [comment]
The problem ist, I can't select the whole text with Shift+Down - at some moment of cursor movement the begin of selection resets to the begin of line, though I don't unpress the Shift key.
I expect to select the whole text moving cursor with Shift+Down.

**Comment by pbek** [comment]
Do you mean the problem when you reach the last line and still press Shift+Down the text becomes unselected? (The same with Shift+Up and the top of the note)

It seems that's a feature clash with `if you are in the last line and press cursor down the cursor will now jump to the end of the line (for jd6661 on the IRC channel)` in v16.08.12.

**Comment by LightTemplar** [comment]
Nope, not the last line. A few lines at the end. I try to select a few bottom lines of the text provided. This issue happens only with this text, and I don't know why.

**Comment by pbek** [comment]
I can reproduce that under Linux. Very interesting, maybe I can find something out.

**Comment by pbek** [comment]
The problem was gone for me after I fixed the issue I mentioned. Will be released with v16.08.17...

## 16.08.17
- fixed a problem with selecting text

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by LightTemplar** [comment]
Perfect! It works now :)

**Comment by pbek** [comment]
Great, thank you!
