### ISSUE TITLE
[FEATURE] Highlight the same words that are marked by the user

### ISSUE THREAD

**Issue by ewrvp7lv7** [pbek/QOwnNotes#3002]
Please, could you make automatic colour selection of the same character sets as user selected ones. 
This, for example, makes it easier to analyse hashes. An example is shown in the picture below.

![Screenshot from 2024-04-08 20-53-37](https://github.com/pbek/QOwnNotes/assets/36769374/a03a3219-4f8c-4162-a11f-f1a933c9fac6)

<details><summary>Expand</summary>
QOwnNotes - version 23.1.1 - AppImage - build 1004

</details>

**Comment by pbek** [comment]
I'm not sure if I understand your request. 😅

Can you please describe what you expected, what the actual behavior was, and step by step what you did? (see issue template)

**Comment by ewrvp7lv7** [comment]
Sorry. This handy function is available in many editors, for example, VSC. 
Please, imagine, we have five very similar lines. We can select the top line with the mouse. Then we can see which row matches exactly the top row. Because the other rows differ from the top row by the characters that are highlighted in crimson. 

![Screenshot from 2024-04-10 02-00-05](https://github.com/pbek/QOwnNotes/assets/36769374/c1a322b0-e3e5-43a4-9d0f-08640d16bdde)
Below we have highlighted the right part of the second line with the mouse.
![Screenshot from 2024-04-10 02-08-45](https://github.com/pbek/QOwnNotes/assets/36769374/79cafd8c-fc01-46e8-a135-b4d95d1577e2)

**Comment by pbek** [comment]
Hm, to be hard on the CPU when done in real-time.
And I only know of one way to highlight text in the QPlainTextEdit and that is used by the search already... 🤔
