### ISSUE TITLE
Misbehaviour of show tag panel button/menu item 

### ISSUE THREAD

**Issue by L-R-S** [pbek/QOwnNotes#301]
When clicking this button (or clicking appropriate menu item) wrong panels are showed or hided.

**Comment by pbek** [comment]
I can't reproduce that. Can you please be more specific on how to reproduce that problem and can you please post the output of the debug tab in the settings.

**Comment by pbek** [comment]
And please define what "wrong" is in your eyes.

**Comment by pbek** [comment]
I will close this issue until there is more information.
