### ISSUE TITLE
[FEATURE] DrawIO integration

### ISSUE THREAD

**Issue by patvdv** [pbek/QOwnNotes#3010]
#### Is your feature request related to a problem? Please describe.

Not related to a problem and I know this a big ask. But here it is anyway. 

#### Describe the solution you'd like

I would love to see an integration with **DrawIO** (diagrams.net) via a plugin(?), allowing diagrams to be natively displayed - and if possible - edited in QON. My reference is the availability and use of the DrawIO plugin in the Atlassian Jira & Confluence suites, e.g.: https://www.drawio.com/doc/drawio-confluence-cloud.

Here is how it could potentially work from a conceptual point of view:

- Storage: add the DrawIO object as an attachment to a note.
- Rendering: in the QON Preview mode, the drawing is rendered as a native DrawIO diagram. Or alternatively, as an on-the-fly generated image of the drawing (png, svg, ...)
- Editing: 
  * Allow the DrawIO object to be edited *outside* QON, either using the native desktop client or via diagrams.net.
  * -OR- allow the DrawIO object edited *inside* QON using the plugin. This would be by far the hardest and most complicated part. I don't even know if there is public code available for this but there seem to be quite a lot of exiting 3rd party integrations already: https://www.drawio.com/integrations.

#### Describe alternatives you've considered

None, IMHO DrawIO is the Visio of the FOSS world. For many it is a cornerstone in technical documentation.

#### Additional context

None, but in my experience a visual often speaks louder than a 1000 words.

**Comment by pbek** [comment]
Since the preview isn't a fully fledged browser, that integration would be clunky at best, if ever attempted. 😬
And would be far from the Markdown spec... 

But lots could already be done with the scripting engine, e.g. like:

- https://github.com/qownnotes/scripts/tree/master/latex-math
- https://github.com/qownnotes/scripts/tree/master/paste-latex-image
- https://github.com/qownnotes/scripts/tree/master/mermaid

... or similar

**Comment by pbek** [comment]
OOT: Oh, thank you for the sponsorship. 😁

**Comment by patvdv** [comment]
> Since the preview isn't a fully fledged browser, that integration would be clunky at best, if ever attempted. 😬 And it would be far away from the Markdown spec...
> 
> But lots could already be done with the scripting engine, e.g. like:
> 
>     * https://github.com/qownnotes/scripts/tree/master/latex-math
> 
>     * https://github.com/qownnotes/scripts/tree/master/paste-latex-image
> 
>     * https://github.com/qownnotes/scripts/tree/master/mermaid
> 
> 
> ... or similar

On the markdown spec: I would advocate to extend it with a special notation, something like:

`![plugin:drawio:param1:param2]
`
etc

I know that it would break _compliancy_ with markdown standards but it wouldn't break functionality as the markdown would simply not resolve in other editors. It would also be a way to allow for future extensions still. Such an QON-only feature would also be an additional reason to use QON, and not another tool.

**Comment by pbek** [comment]
> On the markdown spec: I would advocate to extend it with a special notation, something like

Can you please elaborate what "extending the spec" means for you?

There is no architecture for such plugins in QOwnNotes, no coloring either, and neither the highlighter nor md4c (for the preview) would support them. And the preview itself is also no browser.

But with https://www.qownnotes.org/scripting/hooks.html#prenotetomarkdownhtmlhook and https://www.qownnotes.org/scripting/hooks.html#notetomarkdownhtmlhook you can already parse that in a script and interpret it in whatever way...

**Comment by pbek** [comment]
And I almost forgot, there is https://www.qownnotes.org/scripting/methods-and-objects.html#adding-a-highlighting-rule-for-the-editor if you want to add a rule to the highlighter of the editor.

**Comment by 77nnit** [comment]
But with https://www.qownnotes.org/scripting/hooks.html#prenotetomarkdownhtmlhook and https://www.qownnotes.org/scripting/hooks.html#notetomarkdownhtmlhook you can already parse that in a script and interpret it in whatever way...

OT: is there any way to leverage the HTML DOM API inside the QtQML scripts? I understand that there's no browser to support the API, but maybe some Qt library? I see that in the scripting examples HTML is parsed using regexes, and that is not really practical. It's a shame that you can't access the traversing methods and properties when you have an HTML at hand!

**Comment by pbek** [comment]
> OT: is there any way to leverage the HTML DOM API inside the QtQML scripts? 

You would need a real browser to interpret that, and you can't just pull in one that works on every platform in a script and show it somehow... But you can use JS libraries in a QML, I added a way to include JS files, and people did in the script repository.
