### ISSUE TITLE
[BUG]  qownnotes padlock to decrypt inactive

### ISSUE THREAD

**Issue by antonio24073** [pbek/QOwnNotes#3011]
Hi,

1. I always used qownnotes in linux in many distros, my actual is Arch. I used the encrypt and decrypt from the 3 padlocks in the tools bar.

But I went to do a dual bot with windows, and I was syncing the notes with nextcloud.  

After it, the padlock to decrypt stucks inactive.  as if it hadn't been encrypted before... the encryption option can be used and encrypted twice

#### Expected behaviour

decrypt notes

#### Actual behaviour

decrypt stucks inactive

#### Steps to reproduce

 dual bot with windows, and I was syncing the notes with nextcloud.  

#### Output from the debug section in the settings dialog

I don't know

#### Relevant log output in the Log panel

I don't know

Please I have many customers passwords encrypted that I use to work.

Thank you

**Comment by pbek** [comment]
The notes can be decrypted regardless of the platform. If something modified the encrypted note text you will not able to decrypt it anymore, you can just rely on backups. Shouldn't your Nextcloud server have multiple versions of the note file?

**Comment by pbek** [comment]
> I used the encrypt and decrypt from the 3 padlocks in the tools bar

Just a side node, you are not supposed to decrypt the note! 😉
See the message of the decrypt dialog:

```
Your note will be decrypted and stored as plain text again. Keep in mind that the unencrypted note will possibly be synced to your server and sensitive text may be exposed!
Do you want to decrypt your note?
```

You are rather supposed to *Edit the encrypted note*.

**Comment by antonio24073** [comment]
Hi, thank you for your fast reply.
I do not remember of to change the note.
I checked again and only some notes are affected. I can replace. 
But I noted that there is an option: Use git to keep a local history of your notes. 
Is there some documentation about this? I searched and nothing.

**Comment by pbek** [comment]
There is not much about it. It just uses git to commit your changes to the git repo in your note folder...

I wrote some things up in https://github.com/pbek/QOwnNotes/blob/main/webpage/src/getting-started/git-versioning.md, should show up on the webpage soon ™️.

**Comment by pbek** [comment]
https://www.qownnotes.org/getting-started/git-versioning.html
