### ISSUE TITLE
[BUG] QOwnNotes 24.4.0 has immediate segfault on FreeBSD 13.2

### ISSUE THREAD

**Issue by chriswells0** [pbek/QOwnNotes#3013]
#### Expected behaviour

QOwnNotes launches to the main window.

#### Actual behaviour

App prints the following messages, and no window is shown:

> Warning: QMetaMethod::invoke: Unable to handle unregistered datatype 'LogWidget::LogType' ((null):0, (null))
> Segmentation fault (core dumped)

The first line above prints 991 times.

#### Steps to reproduce

Simply run `QOwnNotes` from a terminal.

Note that `QOwnNotes --session test` successfully opens the welcome dialog (I didn't go further). Maybe it's a setting?

#### Output from the debug section in the settings dialog

Settings dump: [dump-settings.txt](https://github.com/pbek/QOwnNotes/files/15096953/dump-settings.txt)

#### Relevant log output in the Log panel

N/A?

#### Additional Info

This issue didn't happen on 23.12.4, but it did happen on 24.3.5. I also updated hundreds of other packages at the same time (first quarter upgrades). If it would help to know the before and after versions for any dependencies, I can provide that.

**Comment by pbek** [comment]
> Note that QOwnNotes --session test successfully opens the welcome dialog (I didn't go further). Maybe it's a setting?

Then it's a setting for sure, because that's all that argument is doing, providing a way to have a different/fresh set of settings without the need of removing the current settings.

**Comment by pbek** [comment]
Of course a setting shouldn't crash the app, but you can try to use another session to walk your way up again until you can reproduce what actually was causing it...

**Comment by pbek** [comment]
No, that's safe. Only things relevant for those notes are stored there. Sync clients may also write in the same directory...

**Comment by chriswells0** [comment]
The problem starts when I add a script. I tried each of the 3 that I use, and they all caused it:

- Insert text button
- List maker
- a custom script

Both of the ones from the script repository did warn that I'm on an unsupported platform, but I believe (could be wrong) that's always been the case.

**Comment by pbek** [comment]
So scripts in general... 🤔
I think you really would need to build qownotes yourself in debug mode and run a debugger to see what's causing it, I'm too inexperienced with FreeBSD...

https://www.qownnotes.org/installation/building.html

**Comment by chriswells0** [comment]
Is there a way to disable the scripts for my regular session without access to the GUI?
