### ISSUE TITLE
[I] LaTeX math script generates empty icons instead of images

### ISSUE THREAD

**Issue by TomWaisberg** [pbek/QOwnNotes#3016]
#### Expected behaviour

Create and render images of math expressions written in LaTeX (when between $ $)

#### Actual behaviour

Doesn't render the images, leaves empty white icons

#### Steps to reproduce

Write any LateX expression in QOwnNotes between two $

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sun Apr 28 16:28:30 2024`
**Version**: `24.4.4`
**Build date**: `Apr 24 2024`
**Build number**: `1094`
**Platform**: `macosx (cocoa)`
**Operating System**: `macOS 11.7`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/Users/tw/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/tw/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_IL`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1440x900`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `5`
**Calendar items**: `0`
**Enabled scripts**: `1`
**Database drivers**: `QSQLITE, QODBC, QODBC3, QPSQL, QPSQL7`

## Server Info

**serverUrl**: `https://use09.thegood.cloud`
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_US, he_IL`
**Language names**: `American English (United States), עברית (ישראל)`
**Application dictionaries path**: `/Users/tw/Library/Application Support/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `2`

### Note folder `default`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `1`
**localPath**: `/Users/tw/Desktop/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/Users/tw/Desktop/Notes/notes.sqlite`

### Note folder `default`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `1`
**localPath**: `/Users/tw/Desktop/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/Users/tw/Desktop/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://use09.thegood.cloud`
**username**: `tom.waisberg@gmail.com`
**accountId**: `tom.waisberg@gmail.com`

### Script `Latex Math`

**id**: `1`
**path**: `/Users/tw/Library/Application Support/PBE/QOwnNotes/scripts/latex-math/latex-math.qml`
**variablesJson**: 
```
{
    "customPreamble": "\\newcommand{\\mycmd}[1]{\\bf \\underline{#1}}",
    "executable": "/usr/bin/klatexformula",
    "formulaBgColor": "-",
    "formulaColor": "#000000",
    "formulaPrefix": "\\bf ",
    "settingDPI": 600,
    "settingImageSize": 16,
    "usepackages": "amsmath,amssymb,amsfonts"
}
```
**identifier**: `latex-math`
**version**: `0.0.6`
**minAppVersion**: `20.8.0`

## Settings

**AKLastEmailListRequestDateKey** (QDateTime): `2024-04-28T00:04:14.032`
**AKLastIDMSEnvironment** (qlonglong): `0`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Country** (QString): `IL`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (qlonglong): `4`
**Editor/removeTrailingSpaces** (bool): `false`
**Editor/showLineNumbers** (bool): `false`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2024-04-28T16:26:41.950`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (qlonglong): `32`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `.AppleSystemUIFontMonospaced,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Trebuchet MS,13,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `.AppleSystemUIFontMonospaced,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `.AppleSystemUIFont,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.refreshDebounceTime** (qlonglong): `600`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**NoteFolder-2/NoteTabNameList** (QStringList): `Financials Devlog (#11) Title WIP My Game FLOPPED. . . Or Did It?`
**NoteFolder-2/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-2/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteHistory-2** (QVariantList): `<variant list with 2 item(s)>`
**NoteHistoryCurrentIndex-2** (qlonglong): `1`
**PKSecureElementAvailableFlagsByHost** (qlonglong): `3`
**PKSecureElementAvailableFlagsByHostSome** (qlonglong): `3`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (qlonglong): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**WebAutomaticSpellingCorrectionEnabled** (bool): `true`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `false`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (bool): `true`
**autoReadOnlyMode** (bool): `false`
**autoReadOnlyModeTimeout** (qlonglong): `30`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (qlonglong): `2`
**currentWorkspace** (QString): `initial`
**cursorWidth** (qlonglong): `1`
**darkMode** (bool): `true`
**darkModeColors** (bool): `true`
**darkModeIconTheme** (bool): `true`
**darkModeTrayIcon** (bool): `true`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (bool): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**enableWebAppSupport** (bool): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (qlonglong): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (qlonglong): `1024`
**imageScaleDownMaximumWidth** (qlonglong): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (qlonglong): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (bool): `false`
**itemHeight** (qlonglong): `18`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (qlonglong): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelAutoSelect** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (qlonglong): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (qlonglong): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (qlonglong): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (qlonglong): `0`
**noteSubfoldersPanelTabsUnsetAllNotesSelection** (bool): `false`
**notesPanelOrder** (qlonglong): `0`
**notesPanelSort** (qlonglong): `1`
**notesPath** (QString): `/Users/tw/Desktop/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/supportEnabled** (bool): `false`
**ownCloud/todoCalendarBackend** (qlonglong): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (qlonglong): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (bool): `false`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**showMatches** (bool): `true`
**showMenuBar** (bool): `false`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**startInReadOnlyMode** (bool): `false`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (qlonglong): `0`
**tagsPanelSort** (qlonglong): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (qlonglong): `6`
**useNoteFolderButtons** (bool): `false`
**useUNIXNewline** (bool): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (qlonglong): `22222`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**__CFBundleIdentifier**: `com.apple.Terminal`
**TMPDIR**: `/var/folders/48/78vbgc9x0v9786ntksh1k28r0000gn/T/`
**XPC_FLAGS**: `0x0`
**LaunchInstanceID**: `F3B45740-2E71-49E9-8209-C496DDF93E32`
**TERM**: `xterm-256color`
**SSH_AUTH_SOCK**: `/private/tmp/com.apple.launchd.H11ozRFLSR/Listeners`
**SECURITYSESSIONID**: `186a8`
**XPC_SERVICE_NAME**: `0`
**TERM_PROGRAM**: `Apple_Terminal`
**TERM_PROGRAM_VERSION**: `440`
**TERM_SESSION_ID**: `6E6E9CC9-2BDB-4655-9B6C-4F87DA43FA04`
**SHELL**: `/bin/zsh`
**HOME**: `/Users/tw`
**LOGNAME**: `tw`
**USER**: `tw`
**PATH**: `/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands`
**SHLVL**: `1`
**PWD**: `/Users/tw`
**OLDPWD**: `/Users/tw`
**LC_CTYPE**: `UTF-8`
**_**: `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**__CF_USER_TEXT_ENCODING**: `0x1F5:0x0:0x0`
**QT_LOGGING_RULES**: `qt.network.ssl.warning=false`
</details>

**Comment by TomWaisberg** [comment]
in the terminal I'm getting a stream of the following warnings:
`"Warning: libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))"`
The empty images look like this: 
<img width="677" alt="Screen Shot 2024-04-28 at 16 31 39" src="https://github.com/pbek/QOwnNotes/assets/68729153/a9462fb4-61f6-4edf-a497-e35d2efc6201">

**Comment by pbek** [comment]
>  "Warning: libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))"

You can ignore those...

Have you opened an issue at https://github.com/qownnotes/scripts/issues?
This does not look like an QOwnNotes issue.
