### ISSUE TITLE
[SUPPORT] Opening a link to a note from scripting panel?

### ISSUE THREAD

**Issue by Akselmo** [pbek/QOwnNotes#3017]
Hi!

I have been doing my own little script for this app that lists notes tagged with `journal`, parses through the text to show any open checkboxes or added `task://` items and adds a link to the note.

However since the links are just `<a href="/path/to/note.md">Link</a>` Qownnotes doesnt know that it could open the file in itself.

Is there any way I can make the note url open in qownnotes? 

If it's limitation in scripting panel, can I create my own panel with the scripts that can use reqular QML elements?

Here's link to the script if you're curious, it's still work in progress though: https://codeberg.org/akselmo/qownnotes-scripts/src/branch/main/tasklist.qml

**Comment by pbek** [comment]
So what is your script doing to list notes? Are you changing the output of the preview (there it should be possible more easily)?

> If it's limitation in scripting panel, can I create my own panel with the scripts that can use reqular QML elements?

The capability of that panel is pretty limited. You can open web-links there, but not internal links handled by QOwnNotes internally. But it would be possible to implement that in QOwnNotes with https://doc.qt.io/qt-6/qlabel.html#linkActivated 🤔

**Comment by pbek** [comment]
## 24.4.5
- [Scripting labels](https://www.qownnotes.org/scripting/methods-and-objects.html#registering-a-label)
  now support external links as well as internal links to notes, tasks, deck cards, etc.
  (for [#3017](https://github.com/pbek/QOwnNotes/issues/3017))
  - For more information about what's supported see
    [Setting the text of a registered label](https://www.qownnotes.org/scripting/methods-and-objects.html#setting-the-text-of-a-registered-label)

**Comment by pbek** [comment]
You might get a grasp of what's supported now by taking
a look at [URL handling](https://github.com/pbek/QOwnNotes/blob/964acf69b6382f8ee8252c640c5048f8f4644622/src/utils/urlhandler.cpp#L16-L75).

**Comment by Akselmo** [comment]
Wow that was fast! Awesome! :joy: 

But yeah it's basically a list like this

```
NoteNameThatIsLink
- [ ] markdown checkbox
- [ ] another
```

And I list them all in scripting panel

![image](https://github.com/pbek/QOwnNotes/assets/13801236/a3baf75a-30b0-455b-828e-619705e95e29)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
> Wow that was fast! Awesome! 😂 Thank you!

It was more tricky than I thought...

**Comment by Akselmo** [comment]
I'll give it a try tomorrow if I can't today, I'll keep you posted :)

**Comment by Akselmo** [comment]
Okay, had time to try it after all. Works perfectly for my usecase, many thanks!

**Comment by pbek** [comment]
Awesome, thank you for testing 😁
