### ISSUE TITLE
[BUG] Line count font size does not resize with text

### ISSUE THREAD

**Issue by o-l-a-v** [pbek/QOwnNotes#3019]
#### Expected behaviour

Using QOwnNotes v24.5.0 (and earlier versions) on Windows 11 23H2 (22631.3447) and [Cascadia Mono font (free by Microsoft)](https://github.com/microsoft/cascadia-code) for both regular and code text.

If resizing text/zoom and this line height, line count font size should resize too so it does not get cut/capped.

#### Actual behaviour

![image](https://github.com/pbek/QOwnNotes/assets/6450056/82161706-0dd7-4cb4-b493-115161467a05)

#### Steps to reproduce

Resize (CTRL + scroll down / out) and watch the line count fon't size not following.

#### Output from the debug section in the settings dialog

Not relevant.

#### Relevant log output in the Log panel

Not relevant.

**Comment by pbek** [comment]
Phew, good question. But the line height could be in a different font which then still would get cut...
But I wouldn't consider that a bug. 🤔

**Comment by o-l-a-v** [comment]
It's a visual glitch, as in does not look to be intended, thus I submit-ed it as a bug.

Font should resize to whatever line space is available so it does not get cut?

**Comment by pbek** [comment]
> Font should resize to whatever line space is available so it does not get cut?

That's not something that can be done easily (if at all) in a QWidget application.

**Comment by o-l-a-v** [comment]
> That's not something that can be done easily (if at all) in a QWidget application.

Setting font size in line counter given a zoom level on change of zoom is not easy either? Match font size in the editor?

**Comment by pbek** [comment]
I still need to look at that, but since every line could have a different font face and size (unlike in kate) and doesn't need to be in monotype, like the line numbers, changing something there might not make a lot of sense all the time...

**Comment by pbek** [comment]
## 24.5.1
- In the note editor, the line-number font size will now grow with the editor font size

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by o-l-a-v** [comment]
Yeah, was waiting for the Windows release to be build. Looks much better, the characters scale and are not clipped anymore, thanks. 🙂

For lines where content scales to beyond 100%, what would be your thought about centering the line count vertically? Screenshot of current behavior:

<img width="457" alt="image" src="https://github.com/pbek/QOwnNotes/assets/6450056/e08af8af-bf5c-4857-b45b-c4d086e1f83a">
