### ISSUE TITLE
Navigation (note structure) pane doesn't see header with a link as header

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#302]
`# Header [link](http://url)` is considered as header by editor and render. It won't appear in navigation (note structure) pane though.

**Comment by pbek** [comment]
Yes, I'm already aware of that. The syntax highlighter creates two blocks out of that and that can't be detected by the navigation pane. I don't know if I can fix that...

**Comment by pbek** [comment]
I implemented a workaround.

## 16.08.18
- the navigation pane can now also show unrecognized headlines, like `# Header [link](http://url)`

**Comment by Maboroshy** [comment]
Can't test new version. Updating from your arch repository ends with `error: failed retrieving file 'qownnotes-16.08.17-1-x86_64.pkg.tar.xz' from download.opensuse.org : Maximum file size exceeded`

I said bad things about digital signature for about a week but updated the app, not anymore.

**Comment by pbek** [comment]
Now that's a bummer, I hope they sort that out soon.
For some reason the download from <https://build.opensuse.org/package/binary/home:pbek:QOwnNotes/desktop?arch=x86_64&filename=qownnotes-16.08.17-1-x86_64.pkg.tar.xz&repository=Arch_Extra> works...

**Comment by pbek** [comment]
And can you please try that key:
<http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Arch_Extra/x86_64/home_pbek_QOwnNotes_Arch_Extra.key>

I've got it from <http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Arch_Extra/x86_64/>.

**Comment by pbek** [comment]
I updated <http://www.qownnotes.org/installation#Arch> in the hope that that key works! Thank you for reporting and testing, @Maboroshy!

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by pbek** [comment]
Thank you for testing!
