### ISSUE TITLE
[FEATURE] Make text highlighting themeable too

### ISSUE THREAD

**Issue by o-l-a-v** [pbek/QOwnNotes#3021]
#### Is your feature request related to a problem? Please describe.

Would be great if text highligting/selecting was themeable too.

I've updated the built-in Dracula theme with the color codes from the official palette ( <https://draculatheme.com/contribute#color-palette> ), I have plans to commit it soon. But I noticed that the color used when highlighting text is not themeable.

<img width="601" alt="image" src="https://github.com/pbek/QOwnNotes/assets/6450056/345fec1f-3efd-40ad-9302-cb1cc07128d7">

#### Describe the solution you'd like

Make text highlighting themeable too.

#### Describe alternatives you've considered

None yet.

#### Additional context

I've already added a screenshot.

#### Output from the debug section in the settings dialog

Not relevant.

**Comment by pbek** [comment]
You could do that already with a script.

https://www.qownnotes.org/scripting/methods-and-objects.html#add-a-custom-stylesheet

https://github.com/pbek/QOwnNotes/blob/db8a0e4cc68399ab0250e67b4091beba844f1183/src/libraries/qdarkstyle/style.qss#L50-L51

**Comment by pbek** [comment]
> The feature request is about making that themeable too, as is changing dynamically with the theme.

Hm, since this technically is something completely different (QML CSS Styles) from all the edit styles (QTextCharFormat in the highlighter), it will not easy to implement... 🤔

> Setting QWidget background-color also sets background color of the editor.

yes, it's the background-color... selection-background-color should work tho...

> Some places in the source code it's says QListView twice, probably a bug? 

The CSS selectors are different 😉

> Everything action related to script engine when running on Windows freezes up for many seconds.

Hm, really? Haven't heard any complaints from people using the script engine under Windows. 🤔

**Comment by o-l-a-v** [comment]
> Hm, since this technically is something completely different (QML CSS Styles) from all the edit styles (QTextCharFormat in the highlighter), it will not easy to implement... 🤔 I'm not sure if I want to pull those settings into theming...

Roger roger.

> yes, it's the background-color... selection-background-color should work tho...

Ok. I experimented with making the whole theme of QOwnNotes look Dracula-ish, but that will be hard if editor background can't be different from the "frame" background.

> The CSS selectors are different 😉

The **exact** same appears twice on the same line, is what Im' saying. Example:

* <https://github.com/pbek/QOwnNotes/blob/db8a0e4cc68399ab0250e67b4091beba844f1183/src/libraries/qdarkstyle/style.qss#L995>
* "**QListView::item:!selected:hover**, **QListView::item:!selected:hover**, QTreeView::item:!selected:hover  {"

I guess the second one should've been `QTableView::item:!selected:hover`? 🙂

> Hm, really? Haven't heard any complaints from people using the script engine under Windows. 🤔

I can make an issue on it and try to get some relevant debug info when I got time.

**Comment by pbek** [comment]
> Ok. I experimented with making the whole theme of QOwnNotes look Dracula-ish, but that will be hard if editor background can't be different from the application "frame" background.

Can't you use a CSS selector for just the editor? Something like `QMarkdownTextEdit`...

> I guess the second one should've been QTableView::item:!selected:hover? 🙂

Why do you think so?
It's more like an upstream question...

> I can make an issue on it and try to get some relevant debug info when I got time.

👍️

**Comment by o-l-a-v** [comment]
> Can't you use a CSS selector for just the editor? Something like QMarkdownTextEdit...

Hmm, probably. But then the lines between script and theme are blurred, as in the script is doing some of the work a theme is supposed to do. At that point it would almost be better to include the whole theme in the script.

> Why do you think so? It's more like an upstream question...

Sorry, wrong assumption on my part. Just thought defining the exaxt same thing twice is redundant.

**Comment by pbek** [comment]
> But then the lines between script and theme are blurred, as in the script is doing some of the work a theme is supposed to do. 

What you are doing is UI-Theming and that's what you can do with the scripting engine 😉

> At that point it would almost be better to include the whole theme in the script.

Good question how hard that would be, to make that scriptable. 🤔
