### ISSUE TITLE
[BUG] List Dot on the left side when in RTL mode in the preview window

### ISSUE THREAD

**Issue by IdoKeren** [pbek/QOwnNotes#3025]
#### Expected behaviour
List dots show on the right side of the text 

#### Actual behaviour
The dots show on the left side in the preview window.
In the editor, the "minus" sign of the list shows on the correct side (right)
![image](https://github.com/pbek/QOwnNotes/assets/71383536/6de3a2c3-a92d-469d-becc-2188c73ac0d5)
![image](https://github.com/pbek/QOwnNotes/assets/71383536/b2bc5984-8d70-42e9-bfeb-6f827c5031f6)

#### Steps to reproduce
Change to RTL and use the list markdown

**Comment by pbek** [comment]
You haven't shared your settings... I guess you have enabled RTL for the preview, have you?
If it doesn't work than the upstream QTextBrowser, that is used for the preview, doesn't support it...

But you can also try the script https://github.com/qownnotes/scripts/tree/master/autodetect-text-direction from the script repository first.

**Comment by IdoKeren** [comment]
Yes RTL was enabled, I will try the script, but doesn't it only toggle the RTL setting?

**Comment by pbek** [comment]
See https://github.com/qownnotes/scripts/blob/master/autodetect-text-direction/info.json#L9

**Comment by IdoKeren** [comment]
Thanks! it's working

**Comment by pbek** [comment]
Awesome 😁
