### ISSUE TITLE
[I] "Move notes to subfolder..." does not stay in folder but jumps to root folder

### ISSUE THREAD

**Issue by digisus** [pbek/QOwnNotes#3028]
#### Expected behaviour

When moving an item from any current folder to a sub folder, I expect that - after the move is complete - to remain in the current folder.

#### Actual behaviour

After the move is complete, the application jumps to the root folder.

#### Steps to reproduce

- Create a hierarchy of folders and sub folders and populate them with notes
- Go to any sub folder, right-click a note and choose [Move notes to subfolder...] to move it to another folder
- After the move, you find yourself in the root folder every time.

Related suggestion:
Rename the menu-item to just [Move...] as it is shorter and implies any target folder, not just a subfolder.
The same renaming can be done for [Copy...] as well.

#### Debug info

**Current Date**: `Fr. Mai 10 20:09:42 2024`
**Version**: `24.5.1`
**Build date**: `May  5 2024`
**Build number**: `1097`
**Platform**: `linux (xcb)`
**Operating System**: `Ubuntu 22.04.4 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.15.3`
**Qt Version (runtime)**: `5.15.3`
**Portable mode**: `no`

**Comment by pbek** [comment]
I can't reproduce that, when I move a note to another subfolder I stay in the same folder... Maybe the note folder gets reloaded for you... Or maybe you are using an experimental feature?

Can you please post the output from the *Debug settings* in the settings dialog? You just need to paste it here.
And is there any useful log output if you enable the log panel (see Window / Panels)?
Please make sure you also enable debug logging in the log panel by right-clicking on the panel and selecting `Debug` in `Options`.
The issue dialog in the help menu can help you with all of that.
