### ISSUE TITLE
A True Tree-Like Pane

### ISSUE THREAD

**Issue by buckwangs** [pbek/QOwnNotes#303]
Currently in version 16.08.17 build 224 you have up to 3 different panes (folders, files and navigation of sections) that can truly be just one pane. Currently, it's not at all intuitive at first and is quite jarring until you know what's happening.

Also, using a mouse, the current setup requires you move it quite a bit to go from checking one file, to checking another folder to jumping to a section. It's a whole lot of mouse moving (probably more than should be necessary).

It is in my humble opinion that a single pane would be more intuitive, easier to remember and easier to navigate. Instead of having 3 panes and jumping from one pane to another, you have an option for a single true tree-like pane that looks like this.

```
  NoteFolder 1
  NoteFolder 2
  NoteFolder 3
    NoteFolder 3.1
    Note X
      Section 1 
      Section 2
  NoteFolder 4
    Note Y
      Section 1
      ...
```

At the moment, qownnotes has some fantastic opportunity ahead of it. I hope to see this implemented. Thank you for considering :)

**Comment by pbek** [comment]
Thank you for your suggestion. I already tried to implement that (tree of subfolders + notes) as part of the note subfolder implementation and a lot of users advised me not to do it, so I want back to the current view. I think they are right, it wasn't pleasant to work with. Beside that it would be a horror to implement and maintain next to the "no-subfolders" option that is the default.

So I'm sorry, I don't think QOwnNotes will have that any time soon. :(

**Comment by buckwangs** [comment]
Interesting, I'm pretty surprised to be honest. I'll get used to it I suppose. Keep up the good work :+1:

**Comment by pbek** [comment]
Please head over to #790 for an update on a note tree in the note list panel.
