### ISSUE TITLE
[BUG]  xml formatting in markdown

### ISSUE THREAD

**Issue by IvoLimmen** [pbek/QOwnNotes#3032]
Since I wanted to post an image I used GitHub directly. I am using version 23.11.0. on Ubuntu 23.10. Kernel: Linux QSD 6.5.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Fri Apr 26 11:23:57 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

#### Expected behaviour
I was expecting to see the same text just in different colors.

#### Actual behaviour
![image](https://github.com/pbek/QOwnNotes/assets/196375/bd3a706a-9645-49a6-97dd-f258695bc1d7)

#### Steps to reproduce

Paste the following into a note:
```
<properties>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>        
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
</properties>
```

#### Output from the debug section in the settings dialog

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fri May 24 08:33:49 2024`
**Version**: `23.11.0`
**Build date**: `Oct 31 2023`
**Build number**: `1061`
**Platform**: `linux`
**Operating System**: `Ubuntu 23.10`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.15.8`
**Qt Version (runtime)**: `5.15.10`
**Portable mode**: `no`
**Settings path / key**: `/home/ivo/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/ivo/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `2560x1440`
**Screen resolution(s)**: `2560x1440, 1920x1080`
**Icon theme**: `Papirus`
**Notes in current note folder**: `75`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_AU, en_CA, en_GB, en_US, en_ZA, fr, fr_BE, fr_CA, fr_CH, fr_FR, fr_LU, fr_MC, nl, nl_AW, nl_BE, nl_NL, nl_SR`
**Language names**: `Australian English (Australia), Canadian English (Canada), British English (United Kingdom), American English (United States), English (South Africa), français, français (Belgique), français canadien (Canada), français suisse (Suisse), français (France), français (Luxembourg), français (Monaco), Nederlands, Nederlands (Aruba), Nederlands (België), Nederlands (Nederland), Nederlands (Suriname)`
**Application dictionaries path**: `/home/ivo/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-2`
**localPath**: `/home/ivo/Nextcloud/Notes/notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/ivo/Nextcloud/Notes/notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-c061a447-35ef-41b5-8b4a-80ff7f7d448d`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2024-05-24T08:23:48.427`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,13,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Cantarell,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Cantarell,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (QString): `600`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MessageBoxOverride/readonly-mode-allow** (QString): `16384`
**MessageBoxOverride/remove-notes** (QString): `16384`
**NoteFolder-1/NoteTabNameList** (QString): `Maven`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteHistory-1** (QVariantList): `<variant list with 67 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `66`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**autoReadOnlyMode** (QString): `false`
**autoReadOnlyModeTimeout** (QString): `30`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `preview-only`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `19`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `false`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**noteSubfoldersPanelTabsUnsetAllNotesSelection** (QString): `false`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `0`
**notesPath** (QString): `/home/ivo/Nextcloud/Notes/notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `nSEGA2u7Zmcr`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `lsof, Note 2024-03-12T12.18.11, Note 2024-01-15T13.57.13, Note 2023-10-09T11.38.44, X509TrustManager`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**startInReadOnlyMode** (QString): `false`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspace-nSEGA2u7Zmcr/name** (QString): `Preview only`
**workspace-nSEGA2u7Zmcr/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-nSEGA2u7Zmcr/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, nSEGA2u7Zmcr`

## System environment

**HOME**: `/home/ivo`
**LANG**: `en_US.UTF-8`
**LC_ADDRESS**: `en_IE.UTF-8`
**LC_IDENTIFICATION**: `en_IE.UTF-8`
**LC_MEASUREMENT**: `en_IE.UTF-8`
**LC_MONETARY**: `en_IE.UTF-8`
**LC_NAME**: `en_IE.UTF-8`
**LC_NUMERIC**: `en_IE.UTF-8`
**LC_PAPER**: `en_IE.UTF-8`
**LC_TELEPHONE**: `en_IE.UTF-8`
**LC_TIME**: `en_IE.UTF-8`
**LOGNAME**: `ivo`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin`
**SHELL**: `/usr/bin/zsh`
**SYSTEMD_EXEC_PID**: `4092`
**USER**: `ivo`
**XDG_DATA_DIRS**: `/home/ivo/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**GTK_MODULES**: `gail:atk-bridge`
**QT_ACCESSIBILITY**: `1`
**QTWEBENGINE_DICTIONARIES_PATH**: `/usr/share/hunspell-bdic/`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**DESKTOP_SESSION**: `gnome`
**GDMSESSION**: `gnome`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**OLDPWD**: `/home/ivo`
**PAPERSIZE**: `a4`
**PWD**: `/home/ivo`
**QT_IM_MODULE**: `ibus`
**SESSION_MANAGER**: `local/QSD:@/tmp/.ICE-unix/4054,unix/QSD:/tmp/.ICE-unix/4054`
**SHLVL**: `0`
**SSH_AGENT_LAUNCHER**: `openssh`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**USERNAME**: `ivo`
**XDG_CURRENT_DESKTOP**: `GNOME`
**XDG_MENU_PREFIX**: `gnome-`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_DESKTOP**: `gnome`
**XDG_SESSION_TYPE**: `wayland`
**XMODIFIERS**: `@im=ibus`
**_**: `/usr/bin/gnome-session`
**MANAGERPID**: `3824`
**INVOCATION_ID**: `1eda0b01fdf94d0b84f0e86d54f32be0`
**JOURNAL_STREAM**: `8:39737`
**GJS_DEBUG_OUTPUT**: `stderr`
**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`
**GNOME_SETUP_DISPLAY**: `:1`
**DISPLAY**: `:0`
**XAUTHORITY**: `/run/user/1000/.mutter-Xwaylandauth.GJTQO2`
**WAYLAND_DISPLAY**: `wayland-0`
**GIO_LAUNCHED_DESKTOP_FILE**: `/usr/share/applications/PBE.QOwnNotes.desktop`
**XDG_ACTIVATION_TOKEN**: `gnome-shell/QOwnNotes/4092-1-QSD_TIME1551383`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `21703`

#### Relevant log output in the Log panel

Log panel only showed that it saved the file.

[May 24 08:35:33] [debug]: Set proxy configuration to use NO proxy
[May 24 08:35:33] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[May 24 08:35:33] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <accountId>"" <priority>1
[May 24 08:35:33] [debug]: loadNoteDirectoryList
[May 24 08:35:33] [debug]: reloadTagTree
[May 24 08:35:33] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector()
[May 24 08:35:33] [debug]: reloadNoteSubFolderTree
[May 24 08:35:33] [debug]: reload
[May 24 08:35:33] [debug]: loadNoteDirectoryList
[May 24 08:35:33] [debug]: reloadTagTree
[May 24 08:35:33] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector()
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "shell" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "shell" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "xml" 15
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "xml" 15
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "shell" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "shell" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "shell" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:34] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "shell" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "shell" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "xml" 15
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "xml" 15
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "shell" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "shell" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "shell" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:43] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: storing note file:  "Maven.md"
[May 24 08:35:44] [debug]: stored note:  Note: <id>1 <name>"Maven" <fileName>"Maven.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false
[May 24 08:35:44] [debug]: storeUpdatedNotesToDisk  - 'count':  1
[May 24 08:35:44] [status]: Stored 1 note(s) to disk
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "shell" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "shell" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "xml" 15
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "xml" 15
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "shell" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "shell" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "shell" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:44] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "shell" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "shell" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "xml" 15
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "xml" 15
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "shell" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "shell" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "shell" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:46] [debug]: Code block of lang detected: "" 0
[May 24 08:35:49] [debug]: storing note file:  "Maven.md"
[May 24 08:35:49] [debug]: stored note:  Note: <id>1 <name>"Maven" <fileName>"Maven.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false
[May 24 08:35:49] [debug]: storeUpdatedNotesToDisk  - 'count':  1
[May 24 08:35:49] [status]: Stored 1 note(s) to disk
[May 24 08:36:30] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <accountId>"" <priority>1
[May 24 08:36:42] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <accountId>"" <priority>1

**Comment by pbek** [comment]
Did you try xml code blocks, instead of just plain text code blocks?

    ```xml

**Comment by IvoLimmen** [comment]
Changing the hint for formatting (xml, shell, etc.) does result in different colors but the weird text remains

**Comment by pbek** [comment]
See #2952.
