### ISSUE TITLE
[FEATURE] Shortcut for switching from ltr to trl and dynamic one  

### ISSUE THREAD

**Issue by Popx1** [pbek/QOwnNotes#3033]
#### Is your feature request related to a problem? Please describe.
Yes , i ues arabic some times in my notes

#### Describe the solution you'd like
like a shortcut key for switching to one and another
and a options for dynamic thing
or every note has it own way of typing

**Comment by pbek** [comment]
If you use Arabic text in your notes, it should be automatically RTL, because that's what those characters automatically are doing. The preview is a different thing, because in HTML that needs to be done manually... The script `Autodetect Text Direction` in the script repository helps with that.
