### ISSUE TITLE
[FEATURE][USABILITY] Switching between INS/OVR mode in QOwnNotes

### ISSUE THREAD

**Issue by nalsuriv** [pbek/QOwnNotes#3034]
#### Issue

QOwnNotes always edits notes in the 'Insert' mode, i.e., if one wants to _add_ something to previously written text, they can place a cursor wherever they wish, and type in the missing text.

However, if one wants to _replace_ the previously written text, they are limited to using the [Backspace] and [Delete] keys, which don't allow for the 'Overtype' mode (immediate character-for-character replacement), readily available in many plain-text editors, even the ones not as feature-rich as QOwnNotes.

#### Proposed solution

QOwnNotes note editor needs to react to the pressing of the [Insert] key the same way other text editors behave (Kate, Notepadqq, etc.), and switch between INS/OVR modes accordingly.

#### Considered alternatives

I considered editing my "draft" text files with regular text editors before working with them in QOwnNotes, but it is too cumbersome and disrupts my note-taking process, as QOwnNotes does contain its own text editor, albeit missing this rather useful feature for those of us who prefer treating their notes as a palimpsest, scrubbing and typing over the old text contents as needed.

**Comment by pbek** [comment]
In Kate it's called "Overwrite Mode", but I haven't researched how they are doing it in a QPlainTextEdit.

**Comment by pbek** [comment]
And doing that in QOwnNotes will clash with the cursor width setting. So if someone would implement that in QOwnNotes, extra attention would need to be paid to that setting.

**Comment by nalsuriv** [comment]
Having grepped through the Kate sources, there is no such thing as "QPlainTextEdit". There is, however, a class named "QTextEdit". Also, as far as I can tell, there is no explicitly defined cursor width for the overwrite mode, which leads me to believe it gets redefined not within the editor itself, but within some underlying Qt library. That would mean that no matter the width of the character-to-be-replaced, the cursor width adjusts automatically so as to underline all of it (which can be proven by feeding the editor a mix of single-width characters (letters and numbers) and double-width characters (Kanji, CJK).

**Comment by pbek** [comment]
QOwnNotes uses a `QPlainTextEdit` and there is just https://doc.qt.io/qt-6/qplaintextedit.html#overwriteMode-prop, that can be utilized.

**Comment by pbek** [comment]
## 24.5.9
- When you now press `Insert`, in the note text edit, overwrite mode will be toggled 
  to directly allow overwriting the current text (for [#3034](https://github.com/pbek/QOwnNotes/issues/3034))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by nalsuriv** [comment]
Works as intended, thank you! Closing the issue as resolved.

**Comment by nalsuriv** [comment]
Works as intended, thank you! Closing the issue as resolved.

**Comment by pbek** [comment]
Great, thank you for testing!
