### ISSUE TITLE
[ Ctrl + insert ] does not copy selected text

### ISSUE THREAD

**Issue by MCP-LTS** [pbek/QOwnNotes#3038]
Hello!

In the note text edit panel [ Ctrl + insert ] does not work because ctrl set the cursor to hand to click and open a link based on that page about shortcuts
```
https://www.qownnotes.org/getting-started/shortcuts.html#linux-windows
In the note text edit panel
Ctrl + Click on a link to open it
```

#### Expected behaviour
[ Ctrl + insert ] to copy selected text
#### Actual behaviour
presses just the insert button since control makes the pointer a hand to expect to click on a link

i have 
QOwnNotes - version 24.6.0 - OBS - build 1107
on debian 12

**Comment by pbek** [comment]
I didn't even know that shortcut exists.
When did it work?

**Comment by pbek** [comment]
## 24.6.1
- When using the `Insert` key in the note text edit to toggle overwrite mode, it
  now will be made sure that no modifier key is pressed (for [#3038](https://github.com/pbek/QOwnNotes/issues/3038))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by MCP-LTS** [comment]
it works as expected perfect! thank you! :partying_face:

**Comment by MCP-LTS** [comment]
it works as expected perfect! thank you! 🥳

**Comment by pbek** [comment]
Great, thank you for testing! 😁
