### ISSUE TITLE
[SUPPORT] Newbie's questions

### ISSUE THREAD

**Issue by Virgus** [pbek/QOwnNotes#3042]
Hello @pbek and thanks for this great tool.
I just discovered QOwnNotes and I'm facing two very basic needs which I'm not able to find answers for.

In this issue you mentioned enabling "breaks: true" to see the effects of "two spaces and a new line" to show a markup white line.
https://github.com/pbek/QOwnNotes/issues/1062#issuecomment-436777153

I'm struggling to make this work, any test I've done so far fails, for such a basic thing.
Is there something I should enable ? Where should I write the "breaks: true" setting ? In which config file ?

The second question is just an advise about what is/are the suggested external viewer/viewers under MS Windows.

Thanks and have a nice day,
V.

BTW Is there an hotkey to toggle between edit panel and preview panel ? I'm now working with the two panels open, but I would be nice to have also only the preview panel when reading files. That's why I'm asking for a suggested external viewer...

**Comment by pbek** [comment]
Thank you for your kind words!

> In this issue you mentioned enabling "breaks: true" to see the effects of "two spaces and a new line" to show a markup white line.
> https://github.com/pbek/QOwnNotes/issues/1062#issuecomment-436777153

Markdown-it isn't used for HTML generation for quite a while anymore.

But the two spaces do work... 
Can you please describe what you expected, what the actual behavior was, and step by step what you did?

And can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it?

> The second question is just an advise about what is/are the suggested external viewer/viewers under MS Windows.

Viewer in what way? Editing Markdown files? VScode would do...

> BTW Is there an hotkey to toggle between edit panel and preview panel ? I'm now working with the two panels open, but I would be nice to have also only the preview panel when reading files. That's why I'm asking for a suggested external viewer...

Usually you would create a workspace with the preview and one without it. And then use the shortcut to switch to the previous workspace. 😉

**Comment by Virgus** [comment]
Thanks @pbek for your prompt reply !

> Usually you would create a workspace with the preview and one without it. And then use the shortcut to switch to the previous workspace. 😉

It worked beautifully, I created three workspaces: Edit, Dual Panel and Preview and it's perfect now.
![20240617_221841_Screenshot_QOwnNotes](https://github.com/pbek/QOwnNotes/assets/6388217/06f44b0c-cabd-4878-8b0b-298f16899c0d)

> But the two spaces do work... Can you please describe what you expected, what the actual behavior was, and step by step what you did?

I'm under Win10 and the two spaces seem not to work on my setup.
Here two screenshots of my latest test: in the first one I added <br> after the title section, in the second one there's a sequence of Shift+Enter followed by Enter, but nothing changes on the preview pane.
![20240617_221257_Screenshot_QOwnNotes br](https://github.com/pbek/QOwnNotes/assets/6388217/ff0f4d00-d870-4f91-9fe3-30acf73b6296)
![20240617_221319_Screenshot_QOwnNotes shift+enter](https://github.com/pbek/QOwnNotes/assets/6388217/1a2e9755-81a2-4bef-88d5-c13478991f10)
 
> And can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the _Debug_ section of it?

Sure, please find them in the attached text file.
[Debug info.txt](https://github.com/user-attachments/files/15877040/Debug.info.txt)

> Viewer in what way? Editing Markdown files? VScode would do...

With the Workplaces toggling solution I solved, but is there a Markdown viewer only app to your knowledge ? Like a light pdf viewer, maybe a portable app, so you can visualize markdown documents "on the fly" or share your documents with others easily ?

Thanks again, talk to you soon,
V.

**Comment by Kvcd12** [comment]
It appears you want to create several blank lines between the content.

I typically use `<br/>`.  And that appears to be working in your example.

A discussion:

Create two blank lines in Markdown

https://stackoverflow.com/questions/20543454/create-two-blank-lines-in-markdown

The Preview itself gives one a good idea what it will look like.  If others have a Markdown editor, they probably have a preview, so you could just send them the Markdown file.  If others don't ... PDF.  From the menu:  Note - Export - Export note as PDF (preview).

**Comment by pbek** [comment]
> I'm under Win10 and the two spaces seem not to work on my setup.

Can you please post an example Markdown text, that you used? I can make them out in your screenshot.
Have you turned off highlighting of trailing spaces?

Otherwise, try this:

```markdown
Line1  
Line2
```

>  Like a light pdf viewer, maybe a portable app, so you can visualize markdown documents "on the fly" or share your documents with others easily ?

I'm not using Windows that often. 😊
QOwnNotes also shows a preview on the fly, you can export them as PDF or HTML and you can share them directly via your Nextcloud instance.

**Comment by Virgus** [comment]
Hello @Kvcd12 thanks for the link to the stackoverflow discussion.

Dear @pbek I just tried copy and pasting your two lines and here is the result:
![20240620 QOwnNotes Line1Line2](https://github.com/pbek/QOwnNotes/assets/6388217/173c2725-eb1f-451b-a1b8-97be518fd9a2)

In this second screenshot I added other lines and tried removing the two trailing spaces.
Is it normal that line feeds are converted to spaces unless there are two spaces before CRLF ?
I tried also to add blank lines by using the methods in the stackoverflow discussions.
![20240620 QOwnNotes Line1Line9](https://github.com/pbek/QOwnNotes/assets/6388217/8109e7c2-5605-44e6-8447-a55997f734ee)

This is the text I've been using (after Line2 I tried adding one single space)
`
Line1
Line2 
Line3  
Line4
Line5  
Line6
` `  
` `  
Line7

$~$

Line8  
Line9
`

**Comment by pbek** [comment]
> Dear @pbek I just tried copy and pasting your two lines and here is the result:

everything looks as it should 👍️

>  Is it normal that line feeds are converted to spaces unless there are two spaces before CRLF ?

yes, that's how Markdown works 😊

only by using two newlines you get a new paragraph, for a newline you need two spaces and a newline

**Comment by pbek** [comment]
GitHub uses their own "flavor" of Markdown. Yes, they handle line breaks differently.

If you want to enforce multiple lines, you'd need to do something like this:

```Markdown
line1

&nbsp;

line2
```

Or use other HTML (e.g. `<br`). Markdown wasn't meant to do that...

**Comment by Virgus** [comment]
Thanks again @pbek I'm closing the support ticket.
Have a nice weekend,
V.

**Comment by pbek** [comment]
You too!
