### ISSUE TITLE
ideas for improvements after some use

### ISSUE THREAD

**Issue by DoTheEvo** [pbek/QOwnNotes#305]
* **focus on going for single view on a note instead of having two panes/panels** 
I am not sure how most people use it, but default is to see the note in raw text form and also the markdown pretty view next to it. It feels redundant and space consuming and general feel of downgrade creeps in if you are coming to qownnotes from an application that has single view, where you get rich text with highlights and formating, and also editing functionality.
Alt+Shift+P for toggling between edit/preview is the life saver for me in this regard, but seems like it got the second seat when theres not even toolbar button for it. Also one issue it has is that the width changes, since they are different widndows at different widths. So single good improvement would be that toggle would not behave like close current / show the other one. But instead get widths to match aso its feels better switching.

* **mouse shortcuts**
I personally can make do without dedicated shorctucs in preferences. As I use easystroke, to send some keystroke on side or middle button press when inside set application... so when I am in qowownnotes and I press middle click, the application receives ctrl+shit+P and toggles edit/preview we talked about. But more noobie users might welcome ability to bind mouse buttons.

* **adding hotkeys for focusing search fields**
I would like to bind ctrl+F to a function where *search or create note* field gets focused and also *All notes* subfolder is selected - Just basic new hotkey called - "search all notes" 
This would also require current function of ctrl+F to be in the shortcuts preferences to be set to something else, which I believe currently is not. Though it is on the toolbar - *Find text in current note*
oh btw it does not work in preview mode, maybe its by design

* **interactive checkboxes in preview mode?**
[they are handy](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments), while in text form its clear what they mean. So in preview you would be able to cycle through checked/unchecked on click, while the text would go for squares with x or without x. They are not standard on github readme pages, but I think qownnotes would only benefit from them, while the files themselves would stay fine

**Comment by pbek** [comment]
Thanks a lot for your thoughts.

> focus on going for single view on a note instead of having two panes/panels 

The widths (the status of the splitters) are managed by the layout manager, but QOwnNotes saves the status of of certain permutations of mode states so you should only have to do it once for each mode...

Sinde mode was were QOwnNotes started. But then lots of people were demanding the current mode. Later I build a "single mode emulation" back in...

> mouse shortcuts

Are you sure it's wise to build that into QOwnNotes? There are plenty of tools providing that functionality...

> search field

I don't think we can just give up the current binding for Ctrl + F just to create an other convenience action.
There currently is Ctrl+Shift+F to get to the search field...

> checkboxes

sorry, that's not possible at the moment, see #235

**Comment by DoTheEvo** [comment]
>The widths (the status of the splitters) are managed by the layout manager, but QOwnNotes saves the status of of certain permutations of mode states so you should only have to do it once for each mode...

seems to be true, once adjusted it does not run away on its own if I change window size, or move across different monitors... still if it could be more seemless without fear that you gonna have to re-adjust if you move something to read long caption or some stuff like that... but thats minor

>Sinde mode was were QOwnNotes started. But then lots of people were demanding the current mode. Later I build a "single mode emulation" back in...

those people are wrong ;)

>Are you sure it's wise to build that into QOwnNotes? There are plenty of tools providing that functionality...

well, if theres solution then its not needed I guess, and probably not many people are looking to bind extra mouse buttons


>I don't think we can just give up the current binding for Ctrl + F just to create an other convenience action.

not give up, just give ability to change in settings

>There currently is Ctrl+Shift+F to get to the search field...

yes, but it ends up searching only in the current subfolder.
Adding new bindable shortuct that would jump to recently created *All notes* subfolder and then focus the search input... that would allow workflow of qownnotes to be:

1. I need to find that one note I know have
2. launch qownnote
3. press *currently non existing shortcut*
4. write search term
5. navigate around with arrows to get to what you want

that 3rd step is missing currently, I need to grab my mouse and click. I am not some vim fanatic that does everything by keyboard shortcut, but search everything I miss

**Comment by pbek** [comment]
> not give up, just give ability to change in settings

you can already assign shortcuts for both actions in the settings, just search for "find"

**Comment by DoTheEvo** [comment]
I see, ctrl+F is there, same as ctrl+shift+F, but I have problem doing the jump to all notes "subfolder" with keyboard

**Comment by pbek** [comment]
For that there is no action yet. I can implement an action...

**Comment by DoTheEvo** [comment]
would greatly appreciate if it there was also a single hotkey for combo of actions.
Jump to all notes and put of the focus on find note
would be called for example:
`Find in all notes - undefined key`

**Comment by pbek** [comment]
## 16.08.20
- if you have note subfolders activated for a note folder there now is
  a new menu entry `Find notes in all subfolders` in the note menu
    - triggering it jumps to `All notes` in the note subfolder tree 
      and triggers a `Find note`

**Comment by DoTheEvo** [comment]
Thnx, will test as soon as its out

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by DoTheEvo** [comment]
awesome, shit works nicely and I dig the new settings layout

**Comment by pbek** [comment]
Great, thank you for testing. :)
