### ISSUE TITLE
[SUPPORT] API Requests

### ISSUE THREAD

**Issue by ibahnasy** [pbek/QOwnNotes#3054]
Why the desktop app keep sending requests to:

```
api.qownnotes.org

p.qownnotes.org
```

**Comment by pbek** [comment]
> api.qownnotes.org

API for update check.

> p.qownnotes.org

API for metrics.

**Comment by ibahnasy** [comment]
But I already disabled metrics:

![image](https://github.com/pbek/QOwnNotes/assets/19417705/dc974372-5b80-4374-9c33-1579f5fa0110)

**Comment by ibahnasy** [comment]
Alright, I disabled the heartbeat and it stopped that request.
Thanks.
