### ISSUE TITLE
[Q] How to use AI feature?

### ISSUE THREAD

**Issue by 200890234** [pbek/QOwnNotes#3055]
#### General question

I have already filled in the Groq api keys, but I don't know what to do next. How can I use it?

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sun Jul 14 22:25:23 2024`
**Version**: `24.6.3`
**Build date**: `Jun 16 2024`
**Build number**: `1110`
**Platform**: `windows (windows)`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `yes`
**Settings path / key**: `E:/QOwnNotes/Data/PBE/QOwnNotes.ini`
**Application database path**: `E:\QOwnNotes\Data\QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes.exe`, `--portable`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `13`
**Calendar items**: `0`
**Enabled scripts**: `1`
**Database drivers**: `QSQLITE, QODBC, QODBC3, QPSQL, QPSQL7`

**Comment by pbek** [comment]
Like mentioned in that settings dialog, install scripts using the AI scripting commands. 😉 Or write some more scriots.

**Comment by pbek** [comment]
## 24.7.2
- It was made more clear in the settings dialog how the AI integration can be used
