### ISSUE TITLE
Import via URLs and Sync via URLs (Feature Request)

### ISSUE THREAD

**Issue by mangoose20026** [pbek/QOwnNotes#3056]
Syncing: Adding documents to the software using URLs.

Access via Link: Add files by importing from a URL, including direct links to files stored in Dropbox or Google Drive shared folders.
Have shared folder link is available in internet as public shared folder link which has many documents. We can only access documents via the shared link. Don't have credentials to login into the app itself.

Example,
Shared folder in Dropbox via link
Shared folder in GoogleDrive via link
Shared folder via Syncthing (https://syncthing.net/)

Need support direct syncing of documents/text from shared folders in Dropbox or Google Drive by simply providing a link. sync documents directly from a URL or a cloud service without the need of credentials.

Note, we cannot write back to shared folder...It is a read-only shared folder.

**Comment by pbek** [comment]
I'm not sure what this issue is about... Is this a feature request or a question? Either of those I don't understand. 😊

**Comment by mangoose20026** [comment]
Sorry, this is a feature request and not a question.

**Comment by pbek** [comment]
But what is the feature request about?

**Comment by mangoose20026** [comment]
I have text files which can be placed in any website folder or cloud storage. I will make the file as read-only or folder as read-only. any user with the folder link should be able to sync with QOwnNotes without any login or credentials

so looking for sync option from direct folder link or cloud storage folder link

need a way in QOwnnotes , so that i will share the url in website so that everyone can install QOwnnotes in their pc or mobile or tab and sync with my folder link. 

Access via Link: Add files by importing from a URL, including direct links to files stored in Dropbox or Google Drive shared folders.
Have shared folder link is available in internet as public shared folder link which has many documents. We can only access documents via the shared link. Don't have credentials to login into the app itself.

Example,
Shared folder in Dropbox via link
Shared folder in GoogleDrive via link
Shared folder via Syncthing (https://syncthing.net/)

Need support direct syncing of documents/text from shared folders in Dropbox or Google Drive by simply providing a link. sync documents directly from a URL or a cloud service without the need of credentials.

Note, we cannot write back to shared folder...It is a read-only shared folder.

**Comment by pbek** [comment]
How and **why** do you think QOwnNotes should talk to all those sync services?
There is no integration to any of those services in QOwnNotes...

**Comment by mangoose20026** [comment]
QOwnNotes has all the awesome features except sync features above. It would be great if you kindly consider and add them.

**Comment by pbek** [comment]
QOwnNotes does not sync to any services, not even Nextcloud. That's what sync clients are for. Why should all the complexity of each sync client be reimplemented in QOwnNotes, when you already have installed those clients anyway?

**Comment by pbek** [comment]
If it's just about using some api to get a file link... I guess you could do that in the scripting engine.

**Comment by mangoose20026** [comment]
Is it possible to add a script in this issue to pull the files from a specific website link which only has the text files and the steps where to use that script in desktop QOwnnotes after installation. Please advise and will follow the same...

Basically want to have the data shared with many, so that everyone uses QOwnnotes and pull the files from the server.

**Comment by pbek** [comment]
> Basically want to have the data shared with many, so that everyone uses QOwnnotes and pull the files from the server.

Isn't that what a sync service is for? Share a special note folder (or just one sub-folder) with many people on your sync service, and you would have just that...

**Comment by mangoose20026** [comment]
i am not technical but help me with how easily we can achieve...so don't know much difference so i put whatever i know ....please forgive if something is wrong or ignorant....

i want to share a folder in internet, users should be able to sync always without pulling every time...whenever i add new files it should get added/updated.

**Comment by pbek** [comment]
I don't know of any sync service supports "publicly sharing a folder in the internet". Usually, you need to have an account on that sync service for every user you want to share to. And then you can share a folder to those people. What sync service do you use, and who do you want to share the folder to?

**Comment by mangoose20026** [comment]
Below are the few ways i would like to share the folder to QOwnNotes so that they can paste the link and pull the files via a textbox and button

1. I have a website with huge text files in a folder which i will update it frequently. (ex: www.textfiles.com/articles). The articles folder will have huge text files.
2. I will have a folder in my google drive which has the articles folder where i will update the text files frequently. I will share the folder shared link to the users so that they can pull the files or sync in QOwnNotes.
3. Similarly i can have similar kind of folder with shared in Dropbox etc.,

Advantages:
1. The user will have one time configuration in their QOwnNotes if such a option is provided
2. They will sync from any of the above source
3. It would be great if multiple source can be configured

What if the above is NOT available?
1. They need to remember the URL everytime
2. They need to download the files locally
3. They need to delete the content 
4. They need to re-import to QOwnNotes

All these 4 steps can be avoided by the end user.

**Comment by pbek** [comment]
I think that will never be possible with QOwnNotes... It's far too much of a personal, very special workflow. 😆

**Comment by mangoose20026** [comment]
Please kindly consider it would be used by many..

**Comment by pbek** [comment]
I'm sorry, this is by design not in scope of qownnotes.

**Comment by mangoose20026** [comment]
Is it possible to provide a text box and pull button anywhere in config to pull .txt files (find and replace existing ones)....

**Comment by pbek** [comment]
Hm, you have https://www.qownnotes.org/scripting/methods-and-objects.html#registering-script-settings-variables. There is a `selection`. 

And you can use https://www.qownnotes.org/scripting/methods-and-objects.html#starting-an-external-program-and-wait-for-the-output to run a program and use the output.

**Comment by mangoose20026** [comment]
Is it possible to make as an UI human readable choice? the program would be used by many who may not have or don't know  much of technical stuff. They can choose and import...Please let me know

**Comment by pbek** [comment]
I still fail to grasp what you are talking about or why do you think this has anything to do with the core of qownnotes. Those scripting commands are meant to be used by someone to write a script to extend the functionality of the application, exactly what you want to do, as far as I get it
