### ISSUE TITLE
[FEATURE] Create List of  AIModels dynamic from API (and configurable)

### ISSUE THREAD

**Issue by aendes** [pbek/QOwnNotes#3057]
Hello,

with the release of openai "gpt-4o-mini", maybe it would be a good feature to create the list of AI - Models dynamic.

The API "https://api.openai.com/v1/models" gives a list of available models.

It would be a great feature to make the list configurable:
For example, get the list of all available models per API and let the user configure which model to use in the GUI.

Thanks for your great work

Aendes

**Comment by pbek** [comment]
Hm, the models are currently hard-coded in `OpenAiService::initializeBackends()`, which will be called every time the OpenAiService is initialized... Calling a remote API would potentially hold up the whole process. 🤔

It would be almost easier to do that in the scripting engine, like in:

https://github.com/qownnotes/scripts/blob/9541dabb2f1510059828889b396e6c7e449bf887/ollama-integration/ollama-integration.qml#L32-L45

**Comment by pbek** [comment]
...or maybe in the settings dialog (which also takes more work).

**Comment by pbek** [comment]
## 24.7.3
- `gpt-4o-mini` was added to the list of available OpenAI models

There now is a new release, could you please test it and report if it works for you?

**Comment by aendes** [comment]
Yes. Thanks for your great work. Everything works like expected.
