### ISSUE TITLE
[FEATURE] Lists buttons & keyboard shortcuts

### ISSUE THREAD

**Issue by Nico7as** [pbek/QOwnNotes#3059]
#### Is your feature request related to a problem? Please describe.
I'm always frustrated when [...]
I'm listing things in bulk, just by typing unformatted lists of things, without any bullet point or checkbox.
Then when I want to format them, I have to add a " - " or " - [ ] " manually at the begining of every line.

#### Describe the solution you'd like
I wish there were a button, or a right-click option to transform a selection of several lines in bullet lists, numeroted lists, or checkbox lists.

First, I'd type : 
Item 1
Item 2
Item 3

Then, by selecting and clicking on a button, or a kb shortcut, I'd get

- Item 1
- Item 2
- Item 3

or

1. Item 1
2. Item 2
3. Item 3

or 

- [ ] Item 1
- [ ] Item 2
- [ ] Item 3

#### Describe alternatives you've considered
Typing elsewere, copy and paste.

**Comment by pbek** [comment]
There is a script for that in the script repository. 😉

**Comment by Nico7as** [comment]
> There is a script for that in the script repository. 😉

Thanks, I'm not yet familiar with the script system provided by QOwnNotes.
I've found and installed them, seems to do the job.

I still believe that is basic functionality that should be present in the base application.
Just like the function and buttons are present this this basic Github text editor.

**Comment by pbek** [comment]
Part of the core app now.
