### ISSUE TITLE
Add monochromic icon

### ISSUE THREAD

**Issue by Dreadeath** [pbek/QOwnNotes#306]
Hello. 

I think it is a good idea to add possibility to change tray icon, to the white one specifically. In GNOME 3 dark blue icon is barely seen. Also theming thing will be really nice feature

Cheers :)

**Comment by pbek** [comment]
Thank you for your suggestion, do you already have a certain icon in mind (or prepared)?
Theming (for the editor and later the preview) is coming in #280.

**Comment by pbek** [comment]
## 16.08.19
- finally there are configurable **editor color schemes**
    - there are two default schemes called `Default` and `Dark` that
      are mimicking the current default mode and the dark mode colors
    - you can create as many schemes as you like by copying and
      modifying them
    - you can change the foreground color, background color, bold state,
      italic state and underline state
    - you can export schemes to files and import them again from 
      these files
        - if you come up with a good and proven color theme, that should
          be included by default, please let me know 

There now is a new release, could you please test it and report if the new features work for you?

**Comment by pbek** [comment]
btw. this is the icon we would need a "light" version of: <https://github.com/pbek/QOwnNotes/blob/develop/src/images/icons/scalable/apps/QOwnNotes.svg>

**Comment by pbek** [comment]
## 16.08.20
- you can now enable a dark mode system tray icon in the interface settings

There now is a new release, could you please test it and report if the new features work for you?

**Comment by Dreadeath** [comment]
Yes! Great, thanks! :)

**Comment by pbek** [comment]
Thank you for testing!

**Comment by Maboroshy** [comment]
I've made some monochromic icon for dark theme. How do I test it? Which icon the app uses for tray?

**Comment by pbek** [comment]
You would have to build QOwnNotes from source and overwrite the PNG.

I've created this SVG: <https://github.com/pbek/QOwnNotes/blob/develop/src/images/icon-dark.svg>
And then exported this PNG to use as tray icon in dark mode: <https://github.com/pbek/QOwnNotes/blob/develop/src/images/icon-dark.png>

**Comment by Maboroshy** [comment]
I've added new dark icon as the pull request. It's the first one for me so I could mess something up. Tell me what you think. It was the first icon making experience for me so there's a room for improvement.

Also I haven't understood what the svg one dark icon for since the app uses png one for tray.

**Comment by pbek** [comment]
It's looking nice, great job! I will have to test it tomorrow. Is there a reason you did the png a little bit smaller than the original?

We need a vector graphic (as svg is) to get it in other resolutions if there is need for them.

**Comment by Maboroshy** [comment]
I've initially tried original size, but it looked little too big in my plasma tray, so I've used the size similar to other small icons of breeze pack.

**Comment by pbek** [comment]
## 16.09.4
- added a new monochromic tray icon (thanks a lot @Maboroshy)

There now is a new release, could you please test it and report if the new features work for you?

**Comment by pbek** [comment]
@Maboroshy, your icon is looking great in 16.09.4. ;) thanks a lot again!

**Comment by Maboroshy** [comment]
All the credit to original icon author I just tweaked his work a bit.
