### ISSUE TITLE
[BUG] Last but one item of Unordered list shown as a header

### ISSUE THREAD

**Issue by vinyatu** [pbek/QOwnNotes#3061]
In editor panel, a single last dash in unordered list is treated as several "------" which denotes H2 header in Mardown. To my limited knowledge, this behaviour is not up to Mardown standards.

#### Expected behaviour
- unordered list item 1
- unordered list item 2
-
#### Actual behaviour
- unordered list item 1
### unordered list item 2
-
#### Steps to reproduce
Just leave a single dash of unordered list empty - it transformes the previous line to H2 header in editor, but not in preview panel.
#### Output from the debug section in the settings dialog
This bug is confirmed on different platforms and different versions of Windows and Linux, so no point of posting debug info here.
#### Discussion
One might argue that you should never leave the last item of unordered list empty. This objection may have merit, but not for people who migrate from other note-taking tools, which may have different standards for unordered lists.

**Comment by pbek** [comment]
Could you please provide an example in Markdown in a code block, so we can actually see what you are talking about? 😊

**Comment by pbek** [comment]
And maybe a screenshot...

**Comment by vinyatu** [comment]
Steps to reproduce were wrong, sorry for that. Actual steps to reproduce this bug:
1) create a file with .md extention in your Notes directory
2) open this file with external editor such as ne, mc-edit, vim etc.
3) enter following markdown code
``` markdown
- unordered item 1
- unordered item 2
-

```
4) save the note
5) open new note in QON
![screenshot](https://raw.githubusercontent.com/vinyatu/qon/main/qonlist.png)

**Comment by pbek** [comment]
@Waqar144, this concerns the highlighter. Do you think you can fix that? It only happens when the note is opened, not during editing itself.

**Comment by Waqar144** [comment]
Yep

**Comment by pbek** [comment]
Thank you very much!

**Comment by pbek** [comment]
## 24.8.0
- A highlighting issue in malformed unordered lists was fixed
  (for [#3061](https://github.com/pbek/QOwnNotes/issues/3061), thank you, @Waqar144) 
  
There now is a new release, could you please test it and report if it works for you?

**Comment by vinyatu** [comment]
Yes, this bug seems to be gone. Thank you.

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by vinyatu** [comment]
Vinyatu kindly asks to solve this issue, as it's sort of critical for him.

**Comment by pbek** [comment]
Maybe @Waqar144 can find a solution, but I need to also find a solution to test it with Qt 5.14.2.
Other than that, pull requests are welcome, @vinyatu, since it's critical to him.

**Comment by vinyatu** [comment]
QubesOS may work better than NixOS with devbox, but it's kind of slow and resource-hungry, so generally vinyatu doesn't recommend it. What's the big deal with Qt6 - can't we release 2 versions of QON (Qt5 and Qt6) simultaneously?

**Comment by pbek** [comment]
> What's the big deal with Qt6 - can't we release 2 versions of QON (Qt5 and Qt6) simultaneously?

Well, that's the deal: https://github.com/pbek/QOwnNotes/actions/runs/10221164104 (see failed builds)
I'm trying to do release builds for Qt6 for a long time now... Plus, every other build system needs to be rewritten and tested everywhere...

**Comment by vinyatu** [comment]
Pull request is ready: https://github.com/pbek/qmarkdowntextedit/pull/209
It's untested, so whether it works or not is unknown.
Sorry for this low-level effort, but at least it's a strart.

**Comment by Waqar144** [comment]
> https://github.com/pbek/QOwnNotes/actions/runs/10221164104 (see failed builds)

Not very hard to fix, except for the snap one which I don't understand. For windows, there is no reason to be using mingw, msvc should be used instead or at least a newer mingw which has full c++17 support. MacOS seems like a qmake issue.

**Comment by pbek** [comment]
The regular Qt6 builds, like in https://github.com/pbek/QOwnNotes/actions/runs/10221164105 then would also need fixing.

**Comment by vinyatu** [comment]
It's kind of sad that QON is still on Qt5 four years after Qt6 release - especially taking into the account this software name. vinyatu appreciates Waqar144's efforts to build QON with Qt6, but these builds seem to have a problem with SQL drivers, while pbek's builds run fine on Linux. vinyatu would like to offer help with transitioning to Qt6 (as it could possibly solve a host of problems), but it is prohibitively difficult for him to do so, since his country seems to be denied Qt service for a while.

**Comment by pbek** [comment]
I made some Builds already work a while ago, but they stopped working again after github's infrastructure changed

**Comment by pbek** [comment]
But nevertheless, all the Launchpad, Obs, freebsb, aur, slackware,... Und release would also need to change. And there are a lot!

**Comment by pbek** [comment]
## 24.8.3
- A highlighting issue in malformed unordered lists was fixed again, while not
  breaking settext headers for Qt 5.15.2 (for [#3061](https://github.com/pbek/QOwnNotes/issues/3061)
  and [#3065](https://github.com/pbek/QOwnNotes/issues/3065))

There now is a new release, could you please test it and report if it works for you?

**Comment by vinyatu** [comment]
That's a partial success, thank you. However, there's one more issue left unnoticed
``` markdown
- unordered list item
	- unordered list subitem
-
```
This produces an header both on Windows QON version 24.8.5 Built on Aug 13 2024 with Qt 5.15.2
and on Linux QON 24.8.5 AppImage Built on Aug 13 2024 with Qt 6.5.0
Should we open a new issue? Or do you believe this to be a normal markdown processing?

**Comment by pbek** [comment]
So you are using a Tab character (`\t`) as indent. Please open a new issue.
