### ISSUE TITLE
[BUG] Syntax Highlighting Error

### ISSUE THREAD

**Issue by rcrx** [pbek/QOwnNotes#3065]
The 24.8 update broke syntax highlighting in the editor panel for H1 and H2 headers using the 
```
header 1
========
```
and 
```
header 2
--------
```
format.

**Comment by pbek** [comment]
I can't reproduce this issue.
Can you please explain in more detail and step by step what you did, what happened and what you expected?

@Waqar144, do you see anything amiss?

**Comment by Waqar144** [comment]
works here

**Comment by rcrx** [comment]
I was using the version 24.7.3 appimage and was prompted that an update was available. I followed the prompt to update to version 24.8. After updating, header levels 1 and 2 as described above were no longer highlighted in the editor window. They are rendered in plain text rather than large text with the appropriate header coloration.

**Comment by rcrx** [comment]
They are rendered as expected in the note preview panel.

**Comment by pbek** [comment]
Can you please post an example Markdown file and maybe a screenshot?

And can you please post the output from the debug settings that you can copy when you get to the settings dialog in QOwnNotes and head over to the *Debug* section of it?

Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and selecting Debug in Options).

**Comment by pbek** [comment]
I tested with Qt 5.15.14 and Qt 6.7.2...

**Comment by rcrx** [comment]
```
Note 2024-08-01T13.46.16
========================

example file
```

**Comment by rcrx** [comment]
Actual result:

![Screenshot_2024-08-01_13-47-40](https://github.com/user-attachments/assets/e8924770-2cce-44ed-b39c-0f058cc4e777)

**Comment by rcrx** [comment]
Qt Version is `5.15.2`

**Comment by pbek** [comment]
I still can't reproduce that... 🤔

And can you please post the output from the debug settings that you can copy when you get to the settings dialog in QOwnNotes and head over to the Debug section of it?

Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and selecting Debug in Options).

**Comment by vinyatu** [comment]
This new bug is confirmed on version 24.8.0 of QON build with Qt 5.15.2 both on Windows and Linux. As it's clearly connected to vinuyatu's previosly closed issue, he is sorry for not testing it right away. The only excuse is that he simply never uses such headings.

**Comment by vinyatu** [comment]
So just 2 cents to compensate: no messages of interest in Log panel with debug enabled. Same for debug settings, nevertheless lines common for both platforms are attached.
[diff.txt](https://github.com/user-attachments/files/16473296/diff.txt)

**Comment by pbek** [comment]
What in hell changed between 5.15.2 and 5.15.14?
I didn't manage to build the app with Qt 5.15.2 or 5.14.2 locally. 😬

@Waqar144, do you have any idea what is broken?

All I can do for now is taking the change back in QOwnNotes.

**Comment by Waqar144** [comment]
>  I didn't manage to build the app with Qt 5.15.2 or 5.14.2 locally. 😬

What do you mean? There should be some error that tells what went wrong

**Comment by pbek** [comment]
> What do you mean? There should be some error that tells what went wrong

To be more precise, I was not able to build the app under NixOS using older versions of Qt using devbox to debug the issue... But I could reproduce the regression by running the AppImage.

**Comment by pbek** [comment]
@Waqar144, do you have a way to build with Qt <= 5.15.2 or guess what happened?

**Comment by Waqar144** [comment]
Only if I build that Qt version myself. 

Also, there is no reason to use an older minor version of Qt 5.15 I think so why not use the latest?

**Comment by pbek** [comment]
The two problems are:

1) There is an issue with the highlighter in Qt 5.15.2 that is not reproducible in Qt 5.15.14
2) The newest Qt 5 version I can build with on GitHub in the releases is Qt 5.15.2.

**Comment by pbek** [comment]
Until we find a solution for https://github.com/pbek/qmarkdowntextedit/pull/206...

## 24.8.2
- The highlighting changes from [#3061](https://github.com/pbek/QOwnNotes/issues/3061)
  where reverted, because they break highlighting of certain heading 1 and 2 in Qt 5.15.2

**Comment by pbek** [comment]
I was able to build with Qt 5.15.3 and already found the issue with the highlighter. 🥳  I'll patch it in the evening.

**Comment by pbek** [comment]
## 24.8.3
- A highlighting issue in malformed unordered lists was fixed again, while not
  breaking settext headers for Qt 5.15.2 (for [#3061](https://github.com/pbek/QOwnNotes/issues/3061)
  and [#3065](https://github.com/pbek/QOwnNotes/issues/3065))

There now is a new release, could you please test it and report if it works for you?

**Comment by rcrx** [comment]
I tried 24.8.3 and received this error message: "Unable to establish a memory database connection"

![Screenshot_2024-08-05_15-12-07](https://github.com/user-attachments/assets/e660c326-0bcc-4147-a20f-6dbbda1e15b2)

I was unable to add directories in the note folder settings.

**Comment by pbek** [comment]
Omg, what release from where did you try?

**Comment by rcrx** [comment]
It was the appimage downloaded from the update prompt

**Comment by pbek** [comment]
I can reproduce that!
Something from the Qt6 release PRs must have had side effects! 😱 @Waqar144?

**Comment by pbek** [comment]
The Windows release is working too. Very strange.

**Comment by Waqar144** [comment]
There wasn't anything in there code related so very unlikely. The botan.pri file change is the only thing that affects the code.

**Comment by pbek** [comment]
I can't find anything either. Seems like something in https://github.com/linuxdeploy/linuxdeploy/releases/tag/continuous or https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/tag/continuous is broken!

@rcrx, can you please open a new issue for the broken 24.8.3 AppImage.

Meanwhile, I'm taking down the AppImage and replacing it with the 24.8.2 AppImage, so that https://api.qownnotes.org/ is not broken.

**Comment by rcrx** [comment]
There is a new issue #3073 for 24.8.3
