### ISSUE TITLE
Start hidden

### ISSUE THREAD

**Issue by Dreadeath** [pbek/QOwnNotes#307]
Is there a way to start QOwnNotes hidden to tray?

**Comment by pbek** [comment]
So far only if your desktop environment (like KDE) does it by itself, if you tell it to do so.

**Comment by pbek** [comment]
## 16.09.1
- there now is an option in the windows menu to start the application 
  hidden when the tray icon is shown

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Dreadeath** [comment]
Yes, it is working, thank you! :)
