### ISSUE TITLE
[BUG] Incorrect creation / removal of notes and sub-folders when in Experimental Note Tree Mode 

### ISSUE THREAD

**Issue by HendersonSoftworks** [pbek/QOwnNotes#3072]
#### Expected behavior
Clicking directory tree node changes application directory context to that directory tree node. 

Application should know commands are being directed towards sub-folders if they are selected.

#### Actual behavior
App directory context only changes when clicking on a note. Nothing happens when clicking on sub-folders, so commands effect the last selected note.

#### Steps to reproduce
**Deletion issue:**
1. Enable experimental note tree mode
2. Select directory node (notice preview panel still has contents of last node)
4. Press Del key, last note will be deleted

**Note creation issue:**
1. Enable experimental note tree mode
2. Create new sub-folder tree node (notice preview panel still has contents of last node)
4. Press CTRL+N, note will be created in the last selected directory, not the new directory

<details><summary>Expand</summary>

Absolutely love this application! It's been a game-changer for me, so thanks for all your hard work!

I'm a tree-mode user, so am aware that my issue is due to this experimental feature. The application doesn't seem to change which directory / tree node is currently selected unless you click on a note. This makes it easy to delete notes, when you really wanted to delete a directory. Similarly, if you want to create a new note, clicking on the sub-directory doesn't change the directory where the application is currently set, meaning that the newly created note is some other directory you were looking at.  

</details>

**Comment by pbek** [comment]
Looks like you are talking about the work in progress feature #790, right?
If yes, then it would be the best to deposit your request there... 😉

**Comment by pbek** [comment]
Hm, it's not happening all the time that the note is created in the wrong folder. 🤔
But there was another report at #3108.

**Comment by pbek** [comment]
## 24.9.6
- The note selection when selecting a note subfolder in the experimental
  [note tree mode](https://github.com/pbek/QOwnNotes/issues/790) was fixed
  (for [#3072](https://github.com/pbek/QOwnNotes/issues/3072))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
