### ISSUE TITLE
[BUG] 24.8.3 appimage database connection

### ISSUE THREAD

**Issue by rcrx** [pbek/QOwnNotes#3073]
The 24.8.3 appimage provides this error message: "Unable to establish a memory database connection"

![Screenshot_2024-08-05_15-12-07](https://github.com/user-attachments/assets/e660c326-0bcc-4147-a20f-6dbbda1e15b2)

I was unable to add directories in the note folder settings.

**Comment by pbek** [comment]
Thank you. This continues the discussion started in https://github.com/pbek/QOwnNotes/issues/3065#issuecomment-2269761477

**Comment by pbek** [comment]
I'm trying to fall back to linuxdeploy 1-alpha-20240109-1 in https://github.com/pbek/QOwnNotes/actions/runs/10255400539. The build should produce an artifact with the AppImage.

**Comment by pbek** [comment]
The AppImage built there did work for me!
I uploaded it to the current release.
Could you please test https://github.com/pbek/QOwnNotes/releases/download/v24.8.3/QOwnNotes-x86_64.AppImage.

**Comment by rcrx** [comment]
@pbek Seems to work for me, too

**Comment by pbek** [comment]
Phew, thank you for all the testing!
While we are at it, could you please also test this Qt6 AppImage: https://github.com/pbek/QOwnNotes/actions/runs/10255635396/artifacts/1778137135 (do you have permissions to download it?)

**Comment by pbek** [comment]
@Waqar144, for me the Qt6 AppImage works now! I fixed the linuxdeploy issue for the Qt6 build, along with the Qt5!
@rcrx, could you maybe use the Qt6 AppImage from now on to test if you have issues?

**Comment by pbek** [comment]
Qt6 AppImage issues are best reported here: #3074

**Comment by pbek** [comment]
The issue was resolved with https://github.com/linuxdeploy/linuxdeploy/issues/291#issuecomment-2277267381.
