### ISSUE TITLE
[FEATURE] KSyntaxHighlighting

### ISSUE THREAD

**Issue by pa-0** [pbek/QOwnNotes#3078]
#### Is your feature request related to a problem? Please describe.

As far as I know, currently `QownNotes` syntax highlighting support is hard-coded and not extensible (albeit supporting **more** than just a few languages).  Still, I see a few issues/requests for syntax highlighting support for other languages... 

So, I have been thinking about possible solutions or workarounds.  This is less of a feature request, and more an attempt to pick the maintainers' brains and get the general temperature of the room:

#### Describe the solution you'd like

What are your thoughts on [**KSyntaxHighlighter**](https://api.kde.org/frameworks/syntax-highlighting/html/index.html)? 

<hr><h3>❝</h3> <h3 align="justify">

... a stand-alone implementation of the cross-platform [Kate editor](https://kate-editor.org/) syntax highlighting engine. It's meant as a building block for text editors as well as for simple highlighted text rendering (e.g. as HTML), supporting both integration with a custom editor as well as a ready-to-use `QSyntaxHighlighter` sub-class.[^1]   

</h3><h3 align="right">❞</h3><hr><h3><code>KSyntaxHighlighter</code> overview</h3>

#### **Featureful:** 
Natively supports syntax highlighting for <strong><ins>300+ already defined syntaxes...!!</ins></strong>.

#### **Easy integration with apps built on QT framework:**
   Both **`C++` and `QML` [API's](https://api.kde.org/frameworks/syntax-highlighting/html/namespaceKSyntaxHighlighting.html)** are already exposed / provided
  
#### **Actively maintained:** 
  As a standalone (separate from Kate editor) library [here](https://invent.kde.org/frameworks/syntax-highlighting)

####  **User-Customizable and Extensible:**
- **[Syntax Definition files](https://docs.kde.org/stable5/en/kate/katepart/highlight.html#:~:text=create%20syntax%20definitions.-,How%20it%20Works,-Whenever%20you%20open)** in `XML` format and stored in user's home/profile directory so new language support can be added simply by dropping new definition files in that same folder.
- **[Color themes](https://invent.kde.org/poa/syntax-highlighting#color-theme-files)** also customizable via user-defined config files stored in the `JSON` format.

[^1]: [`KSyntaxHighlighter`'s _README.md_](https://invent.kde.org/frameworks/syntax-highlighting/-/blob/master/README.md?ref_type=heads)

**Comment by pbek** [comment]
The main questions that come to mind are:

- Does it build with qmake **and** CMake?
- Does it also build on Windows, macOS, FreeBSD, ...?
- How can all the features of the highlighter of https://github.com/pbek/qmarkdowntextedit/ and the quirks added by QOwnNotes be integrated?
- Should it be integrated into https://github.com/pbek/qmarkdowntextedit/ (which would be a major external dependency) or QOwnNotes directly (which also would be a major external dependency)?

**Comment by poa00** [comment]
Valid points.

>The main questions that come to mind are:

* Does it build with qmake **and** CMake?
  Cmake: definitely - qmake: I'll take a look at the logs and find out.

* Does it also build on Windows, macOS, FreeBSD, ...?
 Yes to all 3 (in addiiton to android apparently)

* How can all the features of the highlighter of https://github.com/pbek/qmarkdowntextedit/ and the quirks added by QOwnNotes be integrated?
 Kate's implementation could be revealing, at least for the editor implementation.  After work today, I will see if I can find any qt-based apps that have implemented it in markdown preview pane - though I believe kate has an extension that does that as well.  It couldn't hurt to review the source of those apps at least as a starting point to get some idea of best approach.  As far as quirks, that will also require a follow-up.
 
* Should it be integrated into https://github.com/pbek/qmarkdowntextedit/ (which would be a major external dependency) or QOwnNotes directly (which also would be a major external dependency)?
 
 What has been the approach up until now for enhancements / new features?  Have you been pushing major changes there first and then integrating into QownNotes that way?

**Comment by pbek** [comment]
> What has been the approach up until now for enhancements / new features? Have you been pushing major changes there first and then integrating into QownNotes that way?

Everything that is for general use goes into qmarkdowntextedit (that's why I extracted it as a component from the get-go).
Everything that is specific to QOwnNotes goes into QOwnNotes.

And of course I forgot one other point:

- The old highlighting schemes need to work

**Comment by poa00** [comment]
Still at work, but FYI just came across this so it might be informative/educational at least

### [vnote](https://github.com/vnotex/vnote) implements KSyntaxHighlighter:
- looks like it builds with `cmake` primarily though I did see some references to `qmake` during a very cursory review while on my lunch break
- cross-platform: mac (`dmg`) / linux (`appimage`) /windows (`exe`/`zip`)
- Built on qt5/c++ (for Win7 compatibility) and qt6 /c++ note-taking application 
- main editor components are hosted at [vtextedit](https://github.com/vnotex/vtextedit) (including - i believe - the plain-text editor, wysiwyg markdown editor and markdown preview) 
- `.gitmodules` for vtextedit:
  ```gitmodules
  [submodule "src/libs/syntax-highlighting"]
	path = libs/syntax-highlighting
	url = https://github.com/vnotex/syntax-highlighting.git
  [submodule "src/libs/hunspell"]
	path = libs/hunspell
	url = https://github.com/vnotex/hunspell.git
  [submodule "src/libs/sonnet"]
	path = libs/sonnet
	url = https://github.com/vnotex/sonnet.git
  ...

**Comment by pbek** [comment]
Hah, nice. 😉

Btw. @Waqar144, surely has opinions, since he works on kate.

**Comment by pa-0** [comment]
I know! When I was researching yesterday, I noticed a shoutout/thank you to him.  From what I read on the homepage for kate, I got the distinct impression that they were able to port it to qt6 thanks to him.  Pretty awesome how much he contributes to the community.

**Comment by Waqar144** [comment]
It is possible but it will be a _lot_ of work. Firstly KSyntaxHighlighting doesnot support qmake so that will need to be figured out first. Also, KSyntaxHighlighting themes are much bigger than the ones in QOwnNotes (which is essentially 5 colors). So QOwnNotes will need to somehow extend its UI to allow modifying those themes. Integerating KSH in the code would be simple I think.

Alternatively, QOwnNotes can be extended so that it takes a list of keywords from a file which allow the users to add more languages without having to modify the code.

**Comment by Waqar144** [comment]
Another big blocker would be that KSyntaxHighlighting doesn't support Qt5 at all.

**Comment by pbek** [comment]
> I know! When I was researching yesterday, I noticed a shoutout/thank you to him. From what I read on the homepage for kate, I got the distinct impression that they were able to port it to qt6 thanks to him. Pretty awesome how much he contributes to the community.

Yes, he is pretty awesome! 😉

**Comment by pbek** [comment]
> Another big blocker would be that KSyntaxHighlighting doesn't support Qt5 at all.

Ah, I didn't even think about that on my list!

**Comment by pa-0** [comment]
Ahh

> > Another big blocker would be that KSyntaxHighlighting doesn't support Qt5 at all.
> 
> Ah, I didn't even think about that on my list!

AHH, ok.  I don't doubt that, @Waqar144, you are the expert here given your involvement on kate.  I missed that lack of compatibility when looking at the repo -- Actually, my assumption was that, even if the current build of the syntax highlighting engine doesn't support qt5, the commit history / issues seem to indicate that the syntax highlighting engine has been used in kate for a few years now (before the port to qt6) so getting qt5 compatibility was just a matter of using an earlier release of the engine.

Regardless, taking a step back, what are your personal views on syntax highlighting?  In other words, does your vision for the future of QownNotes include syntax highlighting for several languages? many languages? Is it something you care about / would like to see? 

If the answer is yes, does your vision for the future of QownNotes include syntax highlighting for several languages? many languages?  I think that's something to consider.  If its really not at all important to either of you, then maybe best to leave it be for now (at least until some easier approach to implementation is developed or found in the future)?
