### ISSUE TITLE
[FEATURE] Would it be feasible to add an option to enable hanging indent for deeper list levels in the editor?

### ISSUE THREAD

**Issue by nonplayer** [pbek/QOwnNotes#3083]
#### Describe the solution you'd like

I suspect this may not even be possible due to tooling constraints, but on the slim chance it is, I figured I'd ask. It would be pretty neat if there could be an option to enable a "hanging" indent on list items in the editor pane. To clarify, an option to make it so that the user can make it so their lists look kinda like either of the following:

```
- Level 1 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc commodo
  feugiat elit eget consectetur. Phasellus facilisis lobortis arcu
  - Level 2 in mollis erat tristique at. Curabitur ornare ultrices mollis. Pellentesque congue 
    tellus lorem, non lobortis sem luctus sed. Duis sagittis laoreet mauris non
    - Level 3 congue. Aliquam erat volutpat. Nunc pellentesque posuere aliquet. Nunc 
      sed tincidunt nulla. 
```

or

```
- Level 1 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc commodo
feugiat elit eget consectetur. Phasellus facilisis lobortis arcu
  - Level 2 in mollis erat tristique at. Curabitur ornare ultrices mollis. Pellentesque congue 
  tellus lorem, non lobortis sem luctus sed. Duis sagittis laoreet mauris non
    - Level 3 congue. Aliquam erat volutpat. Nunc pellentesque posuere aliquet. Nunc 
    sed tincidunt nulla. 
```

But preferably the first set. Anyway I totally understand if this is not at all possible, but wanted to check.

**Comment by pbek** [comment]
I don't think you can define different indents for each soft-wrap line in a QPlainTextEdit...
And even if it would be possible, it would be super messy to get that indent right every time while parsing the content and trying to imagine how much space it should take.

So I'd say the answer is "No".

**Comment by nonplayer** [comment]
Ah dang. Thanks for the info!
