### ISSUE TITLE
[EDITOR SCHEMA] Everforest Dark (Hard)

### ISSUE THREAD

**Issue by eburakova** [pbek/QOwnNotes#3088]
#### Everforest Dark Hard

My implementation of the beloved [Eveforest theme (Dark Hard)](https://github.com/sainnhe/everforest/). Light variant is coming!

#### Screenshot

![image](https://github.com/user-attachments/assets/c4c105a7-5622-4bc1-a25b-fb71df22aaee)
![image](https://github.com/user-attachments/assets/e60857be-59f6-44c6-b813-6f5bb9524b64)

#### Schema file (`.ini`)

[Everforest_Dark_Hard.zip](https://github.com/user-attachments/files/16732507/Everforest_Dark_Hard.zip)

**Comment by pbek** [comment]
Thank you!

**Comment by pbek** [comment]
I'll put it into the next release. 😉

**Comment by eburakova** [comment]
Nice, thanks! Please, note the [light variant](https://github.com/pbek/QOwnNotes/issues/3089) as well. 

Cheers!

**Comment by pbek** [comment]
I'll name the schema `Everforest Hard Dark`, instead of `Everforest` so there is no confusion.

**Comment by pbek** [comment]
## 24.8.6
- Added a **new editor color schema** *Everforest Hard Dark* by @eburakova
  (for [#3088](https://github.com/pbek/QOwnNotes/issues/3088))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by eburakova** [comment]
Yes, it works beautifully!

**Comment by eburakova** [comment]
Both themes are now included into the releaze and display as intended.

**Comment by pbek** [comment]
Thank you very much for your contribution!
Are you using QOwnNotes for your work in science? 😊

**Comment by eburakova** [comment]
Actually, not (yet) really! 

I just learned about this program from a Youtuber - [ByDefault](https://youtu.be/XRpHIa-2XCE?si=YhD2SnfPk8fhE9MI&t=477). After his video, I installed it, played around, didn't find my default desktop theme and decided to implement it, because why not. 

Since storage in plain text is not such a priority for me, I mostly use AppFlowy for personal notetaking right now. But I may incorporate QOwnNotes into my other workflows soon. 

By the way, he was really not fond of green schemes. Sorry, ByDefault.

**Comment by pbek** [comment]
> I just learned about this program from a Youtuber - [ByDefault](https://youtu.be/XRpHIa-2XCE?si=YhD2SnfPk8fhE9MI&t=477). After his video, I installed it, played around, didn't find my default desktop theme and decided to implement it, because why not: you made it straightforward!

Nice, so already contributed even before really using the app! 😁 Thank you!
I like ByDefault's video, he really took his time to do an in-depth test of a lot of note-taking applications!

> Since storage in plain text is not such a priority for me, I mostly use AppFlowy for personal notetaking right now, and just VSCode for work. I am also a Gnomie, so Qt apps always look a bit off on my desktop. But I may incorporate QOwnNotes into my other workflows soon.

I didn't even know AppFlowy before. Does an Electron app not also looking off in Gnome? 😁 But I know what you mean. 😉
For me, Markdown (or simple plain-text files in general) were very important, so I'm not locked in into an application (not even my own 😆).

> By the way, this guy ByDefault was really not fond of green schemes. Sorry, ByDefault.

Your implementation of the theme is really serene and peaceful and looks beautiful. 😌
