### ISSUE TITLE
NC 9.1. - app installs but does not show in system

### ISSUE THREAD

**Issue by alphamat** [pbek/QOwnNotes#309]
I have seen your great app & would like to use it.

I have installed/activated the app via apps everything run with any issue or error in log during this step - but the app isn't shown in apps menu or in another way findable in system, i can just see it is activated but nowhere findable - server also checked, app was downloaded & is in the correct folder - nothing in server logs with an error about it

Or is there something addtional to do that the app gets working with Nextcloud ? 

NC 9.1 (10) - apache 2.4 - Debian 8 - PHP 7

Thank you in advance ;-)

**Comment by pbek** [comment]
Thank you for your kind words.

Which app did you try to install?
<https://apps.owncloud.com/content/show.php?content=168497>?

QOwnNotes is a desktop app, meant to run on your desktop, not on your server.
It shouldn't even show up in your ownCloud app section (at least that's what is does on ownCloud).

Please head over to <http://www.qownnotes.org/installation#Debian> to install it on Debian.

Does this answer your question?

**Comment by alphamat** [comment]
okkkkkk that mean that the "app" in OC/NC from the link (https://apps.owncloud.com/content/show.php?content=168497?) is just an connection/extension between the desktop app and OC/NC notes app ? (https://github.com/owncloud/notes)

**Comment by pbek** [comment]
There is a connector app at <https://apps.owncloud.com/content/show.php/QOwnNotesAPI?content=173817> to add additional functionality to QOwnNotes.

QOwnNotes should not be visible in nextCloud, if it is they are ignoring the `minVersion` and `maxVersion` settings.
QOwnNotes creates notes that can be edited with <https://github.com/owncloud/notes>.

see: <http://www.qownnotes.org/>

**Comment by alphamat** [comment]
Thank you very much for your clarification & more infos about it ;-)
