### ISSUE TITLE
[I] Debian 12: apt-get update; apt-get upgrade to version 24.9.0-1 leads to error "unexpected size" 

### ISSUE THREAD

**Issue by ssie4273** [pbek/QOwnNotes#3093]
#### Expected behaviour

on Debian 12 the update from version 24.8.6-1 to version 24.9.0-1 should work via the "normal" Debian update procedure:
apt-get update
apt-get upgrade

#### Actual behaviour

Sceanrio: Debian 12 system. 
qownnotes is successfully added into etc/apt/sources.list.d/qownnotes.list
previous updates executed well with apt-get update and apt-get upgrade

**BUT**: when updating to version 24.9.0-1 the filesize seems to differ from the metadate records for this package. 
As a result apt is refusing to execute and update any further.
See error output below:

Holen:1 http://ftp.gwdg.de/pub/opensuse/repositories/home%3A/pbek%3A/QOwnNotes/Debian_12  qownnotes 24.9.0-1 [4.451 kB]
Fehl:1 http://ftp.gwdg.de/pub/opensuse/repositories/home%3A/pbek%3A/QOwnNotes/Debian_12  qownnotes 24.9.0-1
  Datei hat eine unerwartete Größe (4450200 != 4450620). Eventuell läuft gerade eine Spiegel-Synchronisierung? [IP: 134.76.12.6 80]
  Hashes of expected file:
   - SHA256:785d5043bbb5952129a0de4922dc924ca3947c0e84b5e862eb88e6d49aa66505
   - SHA1:a0363cadd9aff57e977a40bf48ad46925befb618 [weak]
   - MD5Sum:7b5f7e901dd8cc7d5f78d87260516221 [weak]
   - Filesize:4450620 [weak]
E: Fehlschlag beim Holen von http://ftp.gwdg.de/pub/opensuse/repositories/home%3A/pbek%3A/QOwnNotes/Debian_12/amd64/qownnotes_24.9.0-1_amd64.deb Datei hat eine unerwartete Größe (4450200 != 4450620). Eventuell läuft gerade eine Spiegel-Synchronisierung? [IP: 134.76.12.6 80]
   Hashes of expected file:
    - SHA256:785d5043bbb5952129a0de4922dc924ca3947c0e84b5e862eb88e6d49aa66505
    - SHA1:a0363cadd9aff57e977a40bf48ad46925befb618 [weak]
    - MD5Sum:7b5f7e901dd8cc7d5f78d87260516221 [weak]
    - Filesize:4450620 [weak]

#### Steps to reproduce

To update to version 29.9.0-1 execute:
apt-get update
apt-get upgrade

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `So. Sept. 1 11:15:17 2024`
**Version**: `24.8.6`
**Build date**: `Aug 23 2024`
**Build number**: `1121`
**Platform**: `linux (wayland)`
**Operating System**: `Debian GNU/Linux 12 (bookworm)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.15.8`
**Qt Version (runtime)**: `5.15.8`
**Portable mode**: `no`
**Settings path / key**: `/home/name/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/name/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `15`
**Calendar items**: `3`
**Enabled scripts**: `0`
**Database drivers**: `QSQLITE, QMARIADB, QMYSQL, QMYSQL3`
</details>

**Comment by ssie4273** [comment]
I repeated the update once again (after multiple tries). The hash value is OK now. apt is updating correctly.
--> closing this issue.

**Comment by pbek** [comment]
Hm maybe some cache that didn't expire. 🤔
