### ISSUE TITLE
[FEATURE] Join lines shortcut

### ISSUE THREAD

**Issue by maqp** [pbek/QOwnNotes#3095]
#### Is your feature request related to a problem?

Fluent editing is crucial to good note taking. The JetBrains IDEs have a fantastic tool, that once one gets accustomed to, is really hard to live without. 

Pressing <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>J</kbd> performs something called [join lines](https://www.jetbrains.com/help/resharper/Joining_Lines.html) that 

1. Moves the caret to the end of the line
2. Adds one space character in front of the caret
3. Moves the line below the caret to the line with the caret, after the space character from step 2.

#### Describe the solution you'd like

Pretty much identical feature with assignable hotkey.

#### Describe alternatives you've considered
Writing notes with PyCharm but that's anything but ideal.

#### Additional context

`None`

**Comment by pbek** [comment]
This sounds like something that can be done with the scripting engine. Did you already look in the script repository?

**Comment by maqp** [comment]
Oh I can? Great I'll try to implement it this week and share it here. Many thanks!

**Comment by pbek** [comment]
Awesome! Here is the guide for contributing a script: https://github.com/qownnotes/scripts?tab=readme-ov-file#contributing
