### ISSUE TITLE
[BUG] Segfault on Ubuntu 22.04

### ISSUE THREAD

**Issue by jacklenox** [pbek/QOwnNotes#3096]
Somewhat baffled because the issue I'm having seems largely the same as the one outlined in #2937, but I'm definitely running the latest version and still having problems. I'm on Ubuntu 22.04, and have tried installing both from the repository and building the program myself.

Error as follows after trying to run `./QOwnNotes` from the terminal, or `QOwnNotes` after installing from repository:

```
Info: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway. (:0, )
[1]    442686 segmentation fault  ./QOwnNotes
```

If I try `QT_QPA_PLATFORM=wayland ./QOwnNotes`, I get:

```
Info: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway. (:0, )
Warning: QSocketNotifier: Can only be used with threads started with QThread (:0, )
[1]    440994 segmentation fault  QT_QPA_PLATFORM=wayland ./QOwnNotes
```

Other diagnostic stuff:

```
> ./QOwnNotes --version
QOwnNotes 24.9.0
```

If I run a test session, `./QOwnNotes --session test`,  I get the app's welcome dialog.

**Comment by pbek** [comment]
It's hard to reproduce that without your system...
Do you have the same issue with the AppImage, Flatpak or Snap?

**Comment by jacklenox** [comment]
Thanks for the quick response. I've tried installing via the PPA, and also building the application myself, which is how I have it currently. I haven't tried the other methods yet as I'd rather build it myself. Will give the alternatives a go later.

**Comment by pbek** [comment]
Have you used QOwnNotes before, or did it never work?
Do CPI parameters work (https://www.qownnotes.org/getting-started/cli-parameters.html).

**Comment by ced75** [comment]
Thanks for your answer. I've been using QOwnNotes for a long time.
The segfault is quite new, since version 24.11.1.
I have tested different AppImage versions, and the error seem to occur with versions 24.11 (.0 and .1), but version 24.10.1 works fine.

**Comment by ced75** [comment]
After a fresh reinstall and a full reboot, QOwnNotes works fine again, in version 24.11.1.
Hard to say what was the exact cause of this error... 
Sorry for the disturbance.
Kind regards.
