### ISSUE TITLE
[FEATURE] Unexpected action following right arrow key press in search field 

### ISSUE THREAD

**Issue by pkeir** [pbek/QOwnNotes#3097]
In the QOwnNotes search field ("Search or create note"), if I type a word, and then press the left arrow/cursor key, the cursor moves left as expected, so I can add or delete a letter. But if I press the right arrow key, the cursor disappears, and I seem now to be moving the narrow list of files containing the search term right, and then left. On pressing right key, could the cursor instead behave as when pressing the left key.

I am using Ubuntu 24.04. QOwnNotes - version 23.10.1 - AppImage - build 1060. This may be a bug. I'm not certain.

**Comment by pbek** [comment]
It's a feature:

https://github.com/pbek/QOwnNotes/blob/6e2afc87cf5ad8515f313ff82fc9815160009f3f/src/mainwindow.cpp#L4186-L4188

**Comment by pkeir** [comment]
I see. Do you think it's a better feature than moving the cursor to the right? Isn't tab enough? Tab is indeed a common key for shifting between fields; but not the right arrow key?

**Comment by pbek** [comment]
It changed from `Down` to `Right` with the introduction to the feature to auto-complete the search term (because `Down` was needed to navigate the list). But I couldn't yet find a reason my `Tab` isn't enough.

**Comment by pbek** [comment]
## 24.9.2
- In the note search line edit, the `Right` arrow key will not make the focus
  jump to the note list anymore, the `Tab` key is enough to do that

**Comment by pkeir** [comment]
Many thanks!

**Comment by pbek** [comment]
To be true, I also found it kind of annoying. But I never spend the effort to research why I did it. 😁

**Comment by pkeir** [comment]
I had no idea where control had gone. I would eventually reach for the mouse, and click somewhere :)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pkeir** [comment]
It works! QOwnNotes is now better than ever!

**Comment by pbek** [comment]
Great, thank you for testing!
😉
