### ISSUE TITLE
[FEATURE] Add Exponents/The ability to write in superscript and subscript

### ISSUE THREAD

**Issue by Jobe-Thompson** [pbek/QOwnNotes#3098]
#### Is your feature request related to a problem? Please describe.
I love QOwnNotes and and use it for all my personal note taking. I'd like to try using it to write my essays, however when I write, I need to add source numbers after pieces of information. Usually I would put the source number of the information surrounded by square brackets in superscript.

#### Describe the solution you'd like
Simple syntax to write superscript and subscript, for example typing the caret symbol before and after text for superscript (example: ^superscript text here^).

#### Describe alternatives you've considered
I have tried linking that specific piece of information to a heading in a different note, however the syntax for this visually distracts from the rest of the essay while writing and is also cumbersome to add while writing.

**Comment by pbek** [comment]
There is nothing in (proper) Markdown to support that, so the md4c library, used for the preview, isn't support that.
But the `QTextBrowser` widget of the preview is supporting the `<sup>` HTML tag, so you could either just use this or write a script in QOwnNotes that converts some special syntax of your choosing to a `<sup>` tag in the preview with https://www.qownnotes.org/scripting/hooks.html#notetomarkdownhtmlhook.

![image](https://github.com/user-attachments/assets/580f38b3-f499-4dbd-a8b9-6c4e279dac74)

**Comment by Jobe-Thompson** [comment]
Alright I will give that a try thank you for the help
