### ISSUE TITLE
QOwnNotes cannot be found in Windows 11 Installed Apps to be re-installed

### ISSUE THREAD

**Issue by lbtbs** [pbek/QOwnNotes#3099]
I downloaded the .zip installation file of QOwnNotes but I selected the minimal workspace layout on the first startup after installation and couldn't find out how to change the layout (add folders and tags panels). So I wanted to re-install QOwnNotes. 
My issue is that QOwnNotes cannot be found in Windows 11 Installed Apps to be uninstalled.
In Control Panel / Programs / Uninstall a program, it cannot be found as well.
In Windows registry it can be found, but when deleting Windows says something like Windows cannot delete all properties and QOwnNotes.exe remains there afterward.
Revo Uninstaller cannot find QOwnNotes as well.
So I just removed / deleted the whole QOwnNotes folder, unpacked the .zip file and re-installed it but the selection of three workspaces didn't appear on the first startup as it was before.

**Comment by pbek** [comment]
There is no installation (see https://www.qownnotes.org/installation/windows.html).
But there is a button in the *General settings* to remove all settings.
