### ISSUE TITLE
idea for better folderhandling in QOwnNotes

### ISSUE THREAD

**Issue by Pisoko** [pbek/QOwnNotes#31]
Hey qbek,
my owncloudcustomers have many notesfolders to handle with.
Look at my little selfmade picture:
![recent_notes_folder](https://cloud.githubusercontent.com/assets/11957656/12262666/800f94d0-b929-11e5-9faf-89dab2ca3bd1.png)

The idea is, that you can change your recent folder without opening the menubar.
What do you make of it?

Greez Pi

**Comment by pbek** [comment]
Such a thing would be possible. I'll put a note on my todo list.

**Comment by pbek** [comment]
And in v0.78 you will be able to set the size of the menu bar icons manually. ;)

**Comment by pbek** [comment]
from the v0.78 change log:

- you can now jump to all visited note folders with a select box above the notes list (for [Issue #31](https://github.com/pbek/QOwnNotes/issues/31))
    - this select box is turned off by default and can be turned on in the general settings

please tell me if it is what you expected

**Comment by Pisoko** [comment]
That's it. THX :+1:

**Comment by pbek** [comment]
:bowtie:
