### ISSUE TITLE
character escapes issue

### ISSUE THREAD

**Issue by gt945** [pbek/QOwnNotes#310]
\\(?0\\\\d{2}\\\\)  shows (?0\\d{2}\\) 
\\\\(?0\\\\d{2}\\\\) shows \\(?0\\\\d{2}\\) 
does it correct?

**Comment by pbek** [comment]
Can you please describe what you are talking about?

**Comment by gt945** [comment]
sorry, my mistake.

Version: QOwnNotes - version 16.08.18 - AUR - build 225
In editor , input \\(?0\\\\d{2}\\\\) , preview shows (?0\\d{2}\\) 
input \\\\(?0\\\\d{2}\\\\),  preview shows \\(?0\\\\d{2}\\)

**Comment by pbek** [comment]
That seems the work of the [Howdown](https://github.com/hoedown/hoedown) markdown to html converter in `Note::toMarkdownHtml`. If you put the text in <html>`</html> characters it the slashes aren't removed.

**Comment by pbek** [comment]
I updated the library to 3.0.7, but that didn't help neither. It could be a "feature". If you want to file an issue with them feel free to do so: <https://github.com/hoedown/hoedown/issues>

**Comment by pbek** [comment]
I now posted an issue: <https://github.com/hoedown/hoedown/issues/200>

**Comment by pbek** [comment]
Your issue with the backspace if a markdown markdown feature to escape special characters (see above issue). So everything seems in order. But thank you for reporting anyway. ;)
