### ISSUE TITLE
[BUG] Highlighting of settext headings broken for heading starting with strings like 0.0

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#3101]
@Waqar144, your PR https://github.com/pbek/qmarkdowntextedit/pull/206, that you did for [#3061](https://github.com/pbek/QOwnNotes/issues/3061) and [#3065](https://github.com/pbek/QOwnNotes/issues/3065) for version 24.8.3 is breaking highlighting for certain headings:

![image](https://github.com/user-attachments/assets/f53165b3-c2cc-4693-9045-d1756c96b55b)

```markdown
Note 2c
======

00.00 Index
=======

00.00 Index
-----------

0. Word
-------------

0.0 Word
-------------


Heading 1
=====

Heading 2
-----------
```

It was still working in the commit before https://github.com/pbek/QOwnNotes/commit/91edd13880656e16e9bef7e376404a1c4e2ed5ab.

**Comment by Waqar144** [comment]
should be easy to fix, just need to check there is a space after `.` or `)`

**Comment by pbek** [comment]
Great, does that mean you can fix it? 😊

**Comment by pbek** [comment]
Thank you!

**Comment by pbek** [comment]
I'll take a hit at it myself.

**Comment by pbek** [comment]
## 24.9.4
- An issue with the ordered list detection in the heading highlighting was fixed
  (for [#3101](https://github.com/pbek/QOwnNotes/issues/3101), thank you, @Waqar144)

**Comment by pbek** [comment]
@esrevinue
There now is a new release, could you please test it and report if it works for you?
