### ISSUE TITLE
[FEATURE]  Add a tooltip to markdown links

### ISSUE THREAD

**Issue by AlphaHot** [pbek/QOwnNotes#3106]
#### Is your feature request related to a problem? Please describe.
I tend to get annoyed when I can't see where a link is directing me, which means I have to keep checking the editor.

#### Describe the solution you'd like
A potential improvement could be a tooltip like the one found at https://html.spec.whatwg.org/multipage/dom.html#attr-title.
```html
<a href="https://en.wikipedia.org/wiki/IPv6" title="https://en.wikipedia.org/wiki/IPv6"">…
```
This tooltip could display relevant information about the link, giving users a clearer idea of what to expect before clicking.

#### Describe alternatives you've considered
There are none.

#### Additional context
![image](https://github.com/user-attachments/assets/fd173c5d-e892-48f8-95e2-56309a617236)

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info
**Version**: `24.7.3`
**Build date**: `Jul 21 2024`
**Build number**: `1114`
**Platform**: `linux (xcb)`
**Operating System**: `Ubuntu Core 22`
**Current architecture**: `x86_64`
**Qt Version (runtime)**: `5.15.3`
</details>

**Comment by pbek** [comment]
I guess you are talking about the preview...
That would be nice, but I haven't seen support for that in https://github.com/mity/md4c. 😬

**Comment by pbek** [comment]
> [**Playground**](https://test.org/ title="Tooltip")

This link doesn't seem to work with md4c. Or does it for you?

> But why is the closing tag </a> of the link not highlighted in orange? A bug?

There is no highlighting for HTML!
The first part was just detected as link with `<some link>`.
