### ISSUE TITLE
[FEATURE] Android App would be nice

### ISSUE THREAD

**Issue by RandomBloke85** [pbek/QOwnNotes#3107]
Hello

I love QOwnNotes. Thank you for developping such a fantastic app.

I would like to use it on all my Linux and Android devices. That would make me stick to it, but having it on my Desktop/Laptop and not on my Phone/Tablet is just too cumbersome. I know that there're other apps like Nextcloud Notes for the mobile devices, but they're not an option.

Thank you

**Comment by pbek** [comment]
Thank you for your kind words, but I guess nothing much has changed since #806.

**Comment by pbek** [comment]
There now is an Android App: https://www.qownnotes.org/getting-started/qownnotes-android.html.
