### ISSUE TITLE
Update tag tree view

### ISSUE THREAD

**Issue by m-wim** [pbek/QOwnNotes#311]
When is the tag tree view updated? I just added a new tag to a note that was put in the list but its counter was not shown? And I created a new sub-tag via context menu which did also not appear until restart

**Comment by pbek** [comment]
It is usually triggered by an automatic refresh of the note list because of the modification of the database file. Do you have the watching for note folder modifications turned off in the settings? You could also refresh the list with ctrl  + shift + R. But it rather should work automatically.

**Comment by m-wim** [comment]
I switched the note folder modifications setting. But that did not change the behaviour. (Its not about the notes but about the tags - on Windows 10)

**Comment by m-wim** [comment]
ctrl + shift + R updates the counter

**Comment by m-wim** [comment]
ctrl + shift + R shows also new sub-tags

**Comment by pbek** [comment]
I will try to reproduce that...

**Comment by pbek** [comment]
I guess that's a regression from the latest note folder list reloading optimization, the tag tree doesn't get reloaded because the notes didn't change. Thanks again for reporting!

## 16.09.2
- fixed the tag tree reloading if a tag is added to or removed from a
  note in the note edit oder via bulk tagging

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by m-wim** [comment]
16.09.3: works

**Comment by pbek** [comment]
thank you for testing!
