### ISSUE TITLE
[SUPPORT] Can I host the app in rasperrypi 

### ISSUE THREAD

**Issue by TwilightTechie** [pbek/QOwnNotes#3113]
Hey All,

I have a Raspberrypi which I can access from anywhere from the world  and it is hosted in public domain. Can I host my QOwnNotes in RaspberryPi ?

**Comment by pbek** [comment]
You can, https://www.qownnotes.org/installation/raspberry-pi-os.html

But I wouldn't call it "host", since QOwnNotes is a desktop application. 😉
