### ISSUE TITLE
[FEATURE] Shortcut to expand/collapse current subfolder tree

### ISSUE THREAD

**Issue by joomlafun** [pbek/QOwnNotes#3114]
Hi,

It is great that you may navigate between folders with a shortcut, it would even be greater if you could expand and collapse the current folder to see/hide its subfolders.

If I may suggest a practical behaviour it would be :
1°collapses the current tree of the parent folder 
2°if you press again, it will collapse the current tree of the new parent 
3° and so on until you reach the top of the tree

What do you think about such shortcuts?

**Comment by pbek** [comment]
Are we talking about the *Subfolder panel*? Can't you do that all with the cursor keys?

**Comment by joomlafun** [comment]
Yes the _subfolder panel_. Good to know the cursor keys are usable for this thanks.

I must say though that all my navigation shortcuts are at the left of the keyboard and I must not be the only one working with a videogame like hand position : left hand laying on the left part of the keyboard and the right hand on the mouse.

I bound 'd' to go down  's' to go up to navigate through subfolders, it would be convenient to have a key next to it to expand/collapse folder in order to avoid leaving tree branches open

**Comment by pbek** [comment]
The other letters are reserved for jumping to items starting with that letter.

**Comment by joomlafun** [comment]
I don't mind using a shortcut with a combination of keys. Like shift + e or shift + c

**Comment by pbek** [comment]
The cursor keys are sufficient.

**Comment by joomlafun** [comment]
alt, meta.. can be used as shortcuts. But ok I understand not everything can be an option in Qownnote and may have impact on other elements.

Thanks anyway for reviewing this feature request
