### ISSUE TITLE
[SUPPORT] Path to current file in status bar gets truncated / capped

### ISSUE THREAD

**Issue by o-l-a-v** [pbek/QOwnNotes#3117]
#### Question

Path to current open file shown in the status bar, bottom left, gets truncated / capped.

![image](https://github.com/user-attachments/assets/9f650a51-354d-4017-9955-dfc2e41889cf)

Is there a way to get this field wider? I have a lot of free space available in that bottom bar.

This happens on 2x computers with Windows 11 23H2, with QOwnNotes v24.9.6 and many previous versions (not a recent change).

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Hm, how much width can be used in the status bar is handled by Qt. Seems like that doesn't work as well under Windows as under Linux. 🤔

https://github.com/pbek/QOwnNotes/blob/37ea28bc19e8ecb6575ae5cd8c4169ea8f06d516/src/mainwindow.cpp#L3093-L3094

**Comment by o-l-a-v** [comment]
Found that it works better if:

* No env settings to override Qt settings
* Settings -> Interface
  * Toolbar icon size: 18
  * List and tree item height: 14px
  * Interface font size: 12px

**Comment by pbek** [comment]
🤞🏻🤞🏻
