### ISSUE TITLE
[FEATURE]  Limit size of file to open / ignore files / CLI switch to not load recent files

### ISSUE THREAD

**Issue by metakeule** [pbek/QOwnNotes#3118]
#### Is your feature request related to a problem? Please describe.

I save also other files than the markdown files that should be opened by qownnotes in the same repository. there was a very big TXT file (18 MB), I accidently did click on. then QOwnnotes did not react anymore and since it wants to reload the last files, it does not start anymore.

If I remove the settings of sqlite file, all my settings are gone. I use the portable mode. 
I tried to mess with the QOwnNotes.ini, but it did not help either.

#### Describe the solution you'd like

Have a default limit for filesizes and maybe don't try to treat txt files as markdown files (I can perfectly open the file in Notepad++ for example).

#### Describe alternatives you've considered

Have a CLI switch to don't reload the last files would also be helpfull in any case

**Comment by pbek** [comment]
The settings item you were looking for would be `ActiveNoteHistoryItem`.
But there is also the setting `restoreLastNoteAtStartup` you could disable.

**Comment by pbek** [comment]
Of course, you also just could have renamed the text file before starting QOwnNotes. 😉

**Comment by metakeule** [comment]
> The settings item you were looking for would be `ActiveNoteHistoryItem`. But there is also the setting `restoreLastNoteAtStartup` you could disable.

The point is that a commandline flag on startup would be nice, so you don't need to mess with the ini file.

**Comment by metakeule** [comment]
> Of course, you also just could have renamed the text file before starting QOwnNotes. 😉

Yeah, there you got me. But what if somebody just not hit the mouse at the right point and does not know that the file is too large? However after an update to the latest version, it would open the file after 15 minutes on a fast system...

**Comment by metakeule** [comment]
The file in question has some very long lines with just equal signs (======...) in case this helps.....

**Comment by pbek** [comment]
## 24.9.8
- You can now set the **maximum note file size** in the *Panels settings* to prevent
  the loading of very large notes (for [3118](https://github.com/pbek/QOwnNotes/issues/3118))
  - Default is 1 MB

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by metakeule** [comment]
works perfectly

**Comment by pbek** [comment]
Great, thank you for testing!
