### ISSUE TITLE
[F] Show date of release next to version string in update form

### ISSUE THREAD

**Issue by rakekniven** [pbek/QOwnNotes#3119]
#### Expected behaviour

Show date of release next to version string in update form

#### Actual behaviour

Only the version string is shown

#### Steps to reproduce

Open QOwnNotes and check for updates.

<img width="897" alt="Bildschirmfoto 2024-09-07 um 21 44 10" src="https://github.com/user-attachments/assets/09d52f0d-469f-49d7-b412-42bd0d035681">

**Comment by pbek** [comment]
Sorry, that result comes straight from https://api.qownnotes.org, which parses it from the changelog. And the headings in the changelog parsed by many processes and cannot change.

Why is the exact date important, anyway? You already know the year and month.
