### ISSUE TITLE
[FEATURE] OneNote sync

### ISSUE THREAD

**Issue by tim-gromeyer** [pbek/QOwnNotes#3123]
#### Is your feature request related to a problem? Please describe.
I know this is a big one. But I would love to sync my notes with OneNote. There isn't any real note taking app on Linux that supports this.

#### Describe the solution you'd like
OneNote sync

#### Describe alternatives you've considered
Only having my notes on my mobile phone

**Comment by pbek** [comment]
QOwnNotes does no syncing at all. It relies on external sync clients, like the Nextcloud Desktop Client.

**Comment by tim-gromeyer** [comment]
Oh, my bad. Might it be possible to implement is as a plugin? I could develop an api for that...

**Comment by tim-gromeyer** [comment]
I think I have the knowledge for it, but hardly any time

**Comment by pbek** [comment]
QOwnNotes is just reading files from a directory, that's all you need to sync. You don't need QOwnNotes for doing that.

**Comment by tim-gromeyer** [comment]
I guess we can close this then
