### ISSUE TITLE
[FEATURE] MediaWiki sync

### ISSUE THREAD

**Issue by yarons** [pbek/QOwnNotes#3125]
#### Is your feature request related to a problem? Please describe.
I can't synchronize my notes automatically without additional tools.

#### Describe the solution you'd like
Allow collaboration through MediaWiki (Possibly also via GitHub Wiki).

#### Describe alternatives you've considered
Copy/Paste manually.

**Comment by pbek** [comment]
> Allow collaboration through MediaWiki

How would that look?

Are there no external tools that sync between Markdown files (because that's what QOwnNotes creates) and MediaWiki?

**Comment by yarons** [comment]
Hmmm not exactly:
https://gramps.discourse.group/t/converting-github-markdown-to-mediawiki-articles/2477/5

I've been searching for a desktop MediaWiki editor for a long time now, there are some initiatives but most of them are unusable or Wikipedia specific.

**Comment by pbek** [comment]
So what do you think QOwnNotes could do and why?

**Comment by yarons** [comment]
I think this offering can combine the power and stability of MediaWiki as a collaboration platform with the power, stability and usability of QOwnNotes.

It's about creating a new value, MediaWiki can't work offline efficiently while it's a well known strength for QOwnNotes.

There are several scenarios:
1. Select an existing Wikipedia article, allowing to edit it offline and sync it back with conflict resolution.
2. Define a namespace for your user/team and let QOwnNotes manage it for you including conflict resolution.

This way the user can manage personal notes and notebooks which are in fact Wiki articles (either public on Wikipedia or private in a MediaWiki instance).

Thank you and sorry for the late reply.

**Comment by pbek** [comment]
I don't think that would work at all, the Syntax of MediaWiki is completely different from Markdown. 🤔

**Comment by yarons** [comment]
So what about GitHub Wiki?

**Comment by yarons** [comment]
GitHub Wiki is using markdown as well:
https://docs.github.com/en/communities/documenting-your-project-with-wikis

GitHub Pages is a great idea, thank you :)
