### ISSUE TITLE
[Q] Creating keyboard macros

### ISSUE THREAD

**Issue by DYankee** [pbek/QOwnNotes#3126]
#### General question

I'm looking for a way to add a macro or script to insert text and move the cursor. For example pressing ctrl+numberPad_1 inserts the text <sub></sub> and moves the cursor between the HTML tags. Is this possible in QOwnNotes and if so can someone point me in the right direction.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed Oct 9 12:59:02 2024`
**Version**: `24.1.4`
**Build date**: `Jan 29 2024`
**Build number**: `1075`
**Platform**: `linux`
**Operating System**: `Arch Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.12`
**Qt Version (runtime)**: `5.15.15`
**Portable mode**: `no`
**Settings path / key**: `/home/z-geary/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/z-geary/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `C`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `60`
**Calendar items**: `0`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: `https://cloud.gearyhs.com`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `29.0.3.4`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `en_US`
**Language codes**: `en_US`
**Language names**: `American English (United States)`
**Application dictionaries path**: `/home/z-geary/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/z-geary/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: `PHY-T 101`
**database file**: `/home/z-geary/Notes/notes.sqlite`

### Cloud connection `home-server`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://cloud.gearyhs.com`
**username**: `zpgeary@gmail.com`
**accountId**: `admin`

### Script `test`

**id**: `1`
**path**: `/home/z-geary/code/q-scripts/test.qml`
**variablesJson**: *empty*

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `19`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-d239b269-8440-4d31-b0e7-78da882d0ac7`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `/home/z-geary/code/q-scripts`
**FileDialog/LastPath-ScriptPath** (QString): `/home/z-geary/code/q-scripts`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2024-10-09T12:18:14.704`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `com-220`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,12,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Sans Serif,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Sans Serif,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (QString): `600`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**NoteFolder-1/NoteTabNameList** (QString): `Forces`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QString): `PHY-T 101`
**NoteHistory-1** (QVariantList): `<variant list with 98 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `97`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**autoReadOnlyMode** (QString): `false`
**autoReadOnlyModeTimeout** (QString): `30`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `false`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `14`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**noteSubfoldersPanelTabsUnsetAllNotesSelection** (QString): `false`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/z-geary/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `29.0.3.4`
**previousWorkspace** (QString): `38ff9283-90ea-4eda-a5b1-3a4b1e1cfacc`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2024-10-08T14.14.23, Note 2024-10-07T12.10.42, Note 2024-10-02T10.58.24, Note 2024-10-01T14.29.47, Note 2024-10-01T14.26.20, Note 2024-09-30T10.54.24, Note 2024-09-26T15.24.48, Note 2024-09-26T14.45.05, Note 2024-09-23T10.16.16, Note 2024-09-19T15.18.28, Note 2024-09-18T10.27.28, Note 2024-09-11T12.10.22, Note 2024-09-11T11.03.41, Note 2024-09-10T14.09.15, Note 2024-09-09T17.09.04, Note 2024-09-09T17.08.27, Note 2024-09-09T12.17.43, Note 2024-09-05T14.05.18, Note 2024-08-29T14.08.17, Note 2024-08-28T12.53.17, Note 2024-08-28T12.10.33, Note 2024-08-28T10.12.41, Note 2024-08-27T13.59.08, Note 2024-08-26T12.13.04, Note 2024-08-26T12.12.39, Note 2024-08-26T10.09.21, Note 2024-05-05T17.57.36, Note 2024-04-24T14.15.47, Note 2024-04-22T13.41.29, Note 2024-04-22T13.38.05, Note 2024-04-15T13.35.50, Note 2024-04-01T14.11.53, Note 2024-03-27T14.17.49, Note 2024-03-27T13.39.46, Note 2024-03-25T14.44.16, Note 2024-03-25T14.10.26, Note 2024-03-25T10.02.18, Note 2024-03-11T14.16.40, Note 2024-03-11T13.29.30, Note 2024-03-11T13.29.00, Note 2024-03-04T13.26.06, Note 2024-02-26T14.06.14, Note 2024-02-26T13.49.13, Note 2024-02-26T13.36.32, Note 2024-02-19T14.33.43, Note 2024-02-19T13.37.05, Note 2024-02-19T13.29.25, Note 2024-02-19T10.07.55, Note 2024-02-12T14.36.57, Note 2024-02-12T13.30.56, Note 2024-02-07T14.32.02, Note 2024-02-05T14.03.12, Note 2024-02-05T13.32.57, Note 2024-02-05T09.22.06, Note 2024-02-01T01.40.51, Note 2024-01-31T10.10.16, Note 2024-01-31T09.49.50, Note 2024-01-31T09.47.56, Note 2024-01-30T22.51.12, Note 2024-01-29T13.25.01, Note 2024-01-29T09.34.55, Note 2024-01-29T09.34.13`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckBackend** (QString): `Hunspell`
**spellCheckLanguage** (QString): `en_US`
**startInReadOnlyMode** (QString): `false`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (QString): `22222`
**workspace-38ff9283-90ea-4eda-a5b1-3a4b1e1cfacc/name** (QString): `test`
**workspace-38ff9283-90ea-4eda-a5b1-3a4b1e1cfacc/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-38ff9283-90ea-4eda-a5b1-3a4b1e1cfacc/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 38ff9283-90ea-4eda-a5b1-3a4b1e1cfacc`

## System environment

**SHELL**: `/bin/zsh`
**LESS**: `R`
**ANSIBLE_CONFIG**: `/home/z-geary/.config/ansible/ansible.cfg`
**MATHEMATICA_HOME**: `/usr/share/Wolfram/Documentation/14.1/en-us`
**NOTMUCH_CONFIG**: `/home/z-geary/.config/notmuch-config`
**LESS_TERMCAP_se**: `[0m`
**LESS_TERMCAP_so**: `[01;44;33m`
**SSH_AUTH_SOCK**: `/tmp/ssh-XXXXXXMcdDI6/agent.705`
**XDG_DATA_HOME**: `/home/z-geary/.local/share`
**CREDENTIALS_DIRECTORY**: `/run/credentials/getty@tty1.service`
**XDG_CONFIG_HOME**: `/home/z-geary/.config`
**MEMORY_PRESSURE_WRITE**: `c29tZSAyMDAwMDAgMjAwMDAwMAA=`
**ANDROID_SDK_HOME**: `/home/z-geary/.config/android`
**KODI_DATA**: `/home/z-geary/.local/share/kodi`
**SSH_AGENT_PID**: `710`
**EDITOR**: `nvim`
**XDG_SEAT**: `seat0`
**PWD**: `/home/z-geary`
**UNISON**: `/home/z-geary/.local/share/unison`
**LOGNAME**: `z-geary`
**QT_QPA_PLATFORMTHEME**: `gtk2`
**XDG_SESSION_TYPE**: `tty`
**SYSTEMD_EXEC_PID**: `591`
**_**: `/usr/bin/QOwnNotes`
**AWT_TOOLKIT**: `MToolkit wmname LG3D`
**XAUTHORITY**: `/home/z-geary/.Xauthority`
**TERMINAL**: `st`
**WINDOWPATH**: `1`
**MOTD_SHOWN**: `pam`
**GTK2_RC_FILES**: `/home/z-geary/.config/gtk-2.0/gtkrc-2.0`
**HOME**: `/home/z-geary`
**LANG**: `C.UTF-8`
**TMUX_TMPDIR**: `/run/user/1000`
**WINEPREFIX**: `/home/z-geary/.local/share/wineprefixes/default`
**HISTFILE**: `/home/z-geary/.local/share/history`
**_JAVA_AWT_WM_NONREPARENTING**: `1`
**CARGO_HOME**: `/home/z-geary/.local/share/cargo`
**PYTHONSTARTUP**: `/home/z-geary/.config/python/pythonrc`
**MEMORY_PRESSURE_WATCH**: `/sys/fs/cgroup/system.slice/system-getty.slice/getty@tty1.service/memory.pressure`
**INVOCATION_ID**: `89ca2dc24dc448c289f39033ee19dd77`
**MBSYNCRC**: `/home/z-geary/.config/mbsync/config`
**WGETRC**: `/home/z-geary/.config/wget/wgetrc`
**GOMODCACHE**: `/home/z-geary/.cache/go/mod`
**XDG_CACHE_HOME**: `/home/z-geary/.cache`
**ELECTRUMDIR**: `/home/z-geary/.local/share/electrum`
**XDG_SESSION_CLASS**: `user`
**TERM**: `linux`
**LESS_TERMCAP_mb**: `[1;31m`
**LESS_TERMCAP_me**: `[0m`
**LESS_TERMCAP_md**: `[1;36m`
**ZDOTDIR**: `/home/z-geary/.config/zsh`
**LESSOPEN**: `| /usr/bin/highlight -O ansi %s 2>/dev/null`
**USER**: `z-geary`
**DICS**: `/usr/share/stardict/dic/`
**XINITRC**: `/home/z-geary/.config/x11/xinitrc`
**SUDO_ASKPASS**: `/home/z-geary/.local/bin/dmenupass`
**DISPLAY**: `:0`
**LESS_TERMCAP_ue**: `[0m`
**SHLVL**: `4`
**INPUTRC**: `/home/z-geary/.config/shell/inputrc`
**LESS_TERMCAP_us**: `[1;32m`
**MOZ_USE_XINPUT2**: `1`
**XDG_VTNR**: `1`
**XDG_SESSION_ID**: `1`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**TERMINAL_PROG**: `st`
**DEBUGINFOD_URLS**: `https://debuginfod.archlinux.org `
**SQLITE_HISTORY**: `/home/z-geary/.local/share/sqlite_history`
**BROWSER**: `librewolf`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/z-geary/.local/bin:/home/z-geary/.local/bin/statusbar:/home/z-geary/.local/bin/cron`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**FZF_DEFAULT_OPTS**: `--layout=reverse --height 40%`
**PASSWORD_STORE_DIR**: `/home/z-geary/.local/share/password-store`
**MAIL**: `/var/spool/mail/z-geary`
**_JAVA_OPTIONS**: `-Dawt.useSystemAAFontSettings=on`
**OLDPWD**: `/home/z-geary`
**GOPATH**: `/home/z-geary/.local/share/go`
</details>

**Comment by pbek** [comment]
I use and really like https://espanso.org/.
But of course, you could also write a custom action and add text with https://www.qownnotes.org/scripting/methods-and-objects.html#write-text-to-the-note-text-edit.

**Comment by DYankee** [comment]
Thanks for pointing me in the right direction. I thought It might be somthing I could do with a custom action. I just missed the setting to hotkey custom actions the last time I looked.
