### ISSUE TITLE
Renaming a note breaks links

### ISSUE THREAD

**Issue by gesellkammer** [pbek/QOwnNotes#313]
When a note is renamed, links pointing to that note are broken

`QOwnNotes - version 16.09.2 - Launchpad PPA - build 230`

**Comment by pbek** [comment]
Thank you for reporting, that is a well known issue without an solution. I think @Maboroshy tried to fix that with a script already, maybe he can help you.

**Comment by pbek** [comment]
I'm currently trying to come up with something. An option to search and replace the note link in all notes (on one's own risk).

**Comment by pbek** [comment]
## 16.09.3
- when renaming a note in QOwnNotes and a link to that note was found in
  other notes there now a dialog will be opened to ask if you want to
  rename the urls to the note in all found notes
  - this works if the note was renamed by modifying the first line of
    the note or (if you turned that on) by changing the note name in
    the note list

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment]
[Bash-note](https://github.com/Maboroshy/Bash-note) of mine doesn't trace note moving/renaming yet so it's good that you've implemented this feature.

**Comment by pbek** [comment]
Does the feature work for you, @Maboroshy?

**Comment by Maboroshy** [comment]
It works but it has some bugs I was expecting having dealt with links replacements.

If you have 2 links: `<note://test>` and `<note://test_123>` and rename `test` note to `test1` this new feature will also change `<note://test_123>` link to `<note://test1_123>` and break it.

**Comment by pbek** [comment]
You are right, it currently does what it says, replacing text. Maybe we should replace an other text, like one with `<>` and `()` enclosures?

**Comment by Maboroshy** [comment]
Yep, that was the begging that get me to `!\[[^]]*] *([^)]*)` for an in-line image link.

**Comment by pbek** [comment]
## 16.09.4
- the automatic note link url renaming method of v16.09.3 will now not
  just search for the url but trying to detect markdown links

**Comment by gesellkammer** [comment]
That works fine, thanks!

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?
