### ISSUE TITLE
[macos] Graphical glitch in Markdown highlighting settings

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#3130]
It seems like Qt5 has a small issue with `QFrames` with `NoFrame` that should take no space under macOS. It looks like it still takes one pixel around the widget.

![image](https://github.com/user-attachments/assets/e83a8cd2-0995-4b52-b59b-9672348ddd59)

**Comment by pbek** [comment]
The `QFrame` was needed to disable the 2nd checkbox. Since there is only one item in the `QFrame` I could enable/disable that directly too...

**Comment by pbek** [comment]
## 24.10.2
- A small graphical glitch on macOS in the *Markdown highlighting settings* was fixed

**Comment by pbek** [comment]
@markus-barta, there now is a new release, could you please test it and report if it works for you?

**Comment by markus-barta** [comment]
@pbek thanks, works fine 
![Screenshot 2024-10-14 at 07 51 54](https://github.com/user-attachments/assets/65957406-85d4-4f9b-b9a9-211efd8546f8)

**Comment by pbek** [comment]
Great, thank you for testing!
