### ISSUE TITLE
[BUG] Show note in file manager button doesn't respect system default

### ISSUE THREAD

**Issue by ArkitectNaut** [pbek/QOwnNotes#3132]
#### Expected behaviour

Open the user's prefered file manager app (in my case Directory Opus)

#### Actual behaviour

Opens the windows file explorer. This behaviour is also true for the right-click method menu.

#### Steps to reproduce

Have different system file manager, click 'Show note in file manager' button on the toolbar. Same behaviour with right-clicking the file and selecting the 'Show note in file manager' option

**Comment by pbek** [comment]
So far, no better way to implement that on Windows crossed my path:

https://github.com/pbek/QOwnNotes/blob/09a9d8a74891df1d69f5ed1126555f794116678b/src/utils/misc.cpp#L113-L149

Suggestions and pull requests are welcome.

**Comment by pbek** [comment]
But of course you can write a script using a custom action and open any application with the path of the note, see https://www.qownnotes.org/scripting/methods-and-objects.html.
