### ISSUE TITLE
[SUPPORT] Add note conversion tool "jimmy" to website

### ISSUE THREAD

**Issue by marph91** [pbek/QOwnNotes#3133]
#### Question

Hi, I'm currently developing [jimmy](https://github.com/marph91/jimmy), a tool to convert from various note formats to Markdown. The converted Markdown is [compatible with QOwnNotes](https://marph91.github.io/jimmy/import_instructions/#qownnotes).

Would you consider a PR for adding it to the ["Importing notes" page](https://www.qownnotes.org/getting-started/importing-notes.html#importing-notes) of the QOwnNotes website?

**Comment by pbek** [comment]
> Hi, I'm currently developing [jimmy](https://github.com/marph91/jimmy), a tool to convert from various note formats to Markdown. The converted Markdown is [compatible with QOwnNotes](https://marph91.github.io/jimmy/import_instructions/#qownnotes).

Awesome! Many people were waiting for such a tool!
Btw. QOwnNotes only stores images in `media`, the attachments go to `attachments`.

Are https://github.com/marph91/jimmy?tab=readme-ov-file#supported-apps the apps where it supports export AND import? I wasn't sure about that.

> Would you consider a PR for adding it to the ["Importing notes" page](https://www.qownnotes.org/getting-started/importing-notes.html#importing-notes) of the QOwnNotes website?

Sure!

**Comment by pbek** [comment]
Since you don't (yet?) have an import for Evernote enex files... Someone could use QOwnNotes as bridge to get Markdown from Evernote and then use Jimmy to transfer the notes to another application.

**Comment by pbek** [comment]
> https://marph91.github.io/jimmy/formats/qownnotes/

You also take tags out of the SQLite database? Marvelous!

> https://marph91.github.io/jimmy/import_instructions/#qownnotes

Are you also writing tags to the SQLite database?

**Comment by pbek** [comment]
A Jimmy packages would be a nice addition to https://github.com/NixOS/nixpkgs/tree/master. 😉

**Comment by marph91** [comment]
> Awesome! Many people were waiting for such a tool!
> Btw. QOwnNotes only stores images in media, the attachments go to attachments.

Thanks for the kind words :)

Storing in separate folders is not yet supported, but I will add it.

> Are https://github.com/marph91/jimmy?tab=readme-ov-file#supported-apps the apps where it supports export AND import? I wasn't sure about that.

> Since you don't (yet?) have an import for Evernote enex files... Someone could use QOwnNotes as bridge to get Markdown from Evernote and then use Jimmy to transfer the notes to another application.

> Are you also writing tags to the SQLite database?

The conversion is only one way. From the note formats to Markdown and from Markdown to the apps listed at https://marph91.github.io/jimmy/import_instructions/. Writing all the note formats would be (too) much effort. Maybe at some time in the future :smile: 

I didn't add Evernote yet, because most apps have a well-working Evernote import already (QOwnNotes, Joplin, Obsidian). It would be still a good addition.

> A Jimmy packages would be a nice addition to https://github.com/NixOS/nixpkgs/tree/master. 😉

I'm not a NixOS user. So not sure if I would be able to test and maintain it. (I'm a simple Ubuntu guy.) I will add it to the list of ideas anyway. Or rather it's already added (https://github.com/marph91/jimmy/issues/18) :smile:

**Comment by pbek** [comment]
> Storing images and other attachments in separate folders is not yet supported, but I will add it.

Great! 😊

> I didn't add Evernote yet, because most apps have a well-working Evernote import already (QOwnNotes, Joplin, Obsidian). It would be still a good addition.

Evernote crippled their export lately, you can now only export 100 notes at a time. Pretty annoying, because QOwnNotes was able to import pretty large enex files (XML).

> I'm not a NixOS user. So not sure if I would be able to test and maintain it. (I'm a simple Ubuntu guy.) I will add it to the list of ideas anyway. Or rather it's already added (https://github.com/marph91/jimmy/issues/18) 😄

**Every** good application needs to be on nixpkgs! 😆

**Comment by marph91** [comment]
> Are you also writing tags to the SQLite database?

Sorry, missed that. I would rather not write to the sqlite DB from an external app, as it could be corrupted. Currently, the only option to include tags (and other metadata) is via yaml front matter. The tags could be imported to QOwnNotes in a post processing step. Like in the `epsilon-notes-tags` plugin: https://github.com/qownnotes/scripts/issues/79. I will check if this works.

> Evernote crippled their export lately, you can now only export 100 notes at a time. Pretty annoying, because QOwnNotes was able to import pretty large enex files (XML).

Yeah, not sure what they are doing. I think Evernote had a really large user base, but now I see so many users wanting to leave and use other apps.

**Comment by pbek** [comment]
> Currently, the only option to include tags (and other metadata) is via yaml front matter. 

Ah, nice! So you also were aware of the scripting hook and the scripts!

> now I see so many users wanting to leave and use other apps.

...since you need to pay now

**Comment by marph91** [comment]
> Ah, nice! So you also were aware of the scripting hook and the scripts!

Both "yaml tag" scripts (https://github.com/qownnotes/scripts/tree/master/epsilon-notes-tags and https://github.com/qownnotes/scripts/tree/master/yaml-nested-tags) use yaml only partially. I. e. they store the tags in a space separated string instead of a yaml list. I adapted the generated front matter in jimmy to get it working for now and will test a bit more.
