### ISSUE TITLE
[I] Cannot re-attach a detached Navigation panel to the panels on the left

### ISSUE THREAD

**Issue by digisus** [pbek/QOwnNotes#3135]
#### Expected behaviour

When I detached the Navigation (or any) panel from the left side, I should be able to reattach it by hovering it over the panels and get a visual reaction to then be able to "drop" the panel in there.

#### Actual behaviour

The panels on the left side do not react at all when I rag/hover the detached navigation panel over them. This does not work no matter whether the panels on the left side are locked or unlocked. I made a short screencast (7MB) and will see whether/how I can upload it.

#### Steps to reproduce

1) Show the navigation panel: WIndow > Panels > Show Navigation Panel
2) Detach it from the left side by clicking the window button next to the close button.
3) Now you can place the free-floating navigation panel any where on the screen.
4) Now, try to reattach the navigation panel to the left side by dragging it over the other panels...
5) The free floating navigation panel also does not have a window button to reattach it, but only {minimize, maximize, close}.
6) ???

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[10:36:06] [warning] Wayland does not support QWindow::requestActivate()
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Do. Okt. 24 10:36:13 2024`
**Version**: `24.10.2`
**Build date**: `Oct 13 2024`
**Build number**: `1133`
**Platform**: `linux (wayland)`
**Operating System**: `Debian GNU/Linux trixie/sid`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.15.8`
**Qt Version (runtime)**: `5.15.13`
**Portable mode**: `no`
**Settings path / key**: `/home/USER/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/USER/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1200`
**Screen resolution(s)**: `1920x1200, 1920x1200, 1536x960`
**Icon theme**: `Adwaita`
**Notes in current note folder**: `77`
**Calendar items**: `9`
**Enabled scripts**: `1`
**Database drivers**: `QSQLITE`

## Server Info

**serverUrl**: `https://nxNNNNN.your-storageshare.de`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `29.0.5.1`
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `ar, ar_AE, ar_BH, ar_DZ, ar_EG, ar_IN, ar_IQ, ar_JO, ar_KW, ar_LB, ar_LY, ar_MA, ar_OM, ar_QA, ar_SA, ar_SD, ar_SY, ar_TN, ar_YE, be_BY, bg_BG, bs_BA, ca, ca_ES, ca_ES-valencia, ckb_IQ, cs_CZ, da_DK, de_AT, de_BE, de_CH, de_DE, de_LI, de_LU, el_GR, en_GB, en_US, eo, es, es_AR, es_BO, es_CL, es_CO, es_CR, es_CU, es_DO, es_EC, es_ES, es_GT, es_HN, es_MX, es_NI, es_PA, es_PE, es_PR, es_PY, es_SV, es_UY, es_VE, et_EE, eu, eu_ES, eu_FR, fa, fa_IR, fr, fr_BE, fr_CA, fr_CH, fr_FR, fr_LU, fr_MC, ga-IE, ga_IE, gl_ES, gu_IN, he, he-IL, he_IL, hi_IN, hr_HR, hu_HU, id_ID, is_IS, it_CH, it_IT, kk_KZ, kmr_Latn, ko, ko_KR, ku_SY, ku_TR, lt_LT, lv_LV, ml_IN, nb_NO, ne_NP, nl, nl_AW, nl_BE, nl_NL, nl_SR, nn_NO, pl_PL, pt_BR, pt_PT, ro_RO, ru_RU, si_LK, sk, sk_SK, sl_SI, sq_AL, sr_Latn_RS, sr_ME, sr_RS, sv_FI, sv_SE, te_IN, th_TH, uk, uk_UA, vi_VN`
**Language names**: `العربية, العربية (الإمارات العربية المتحدة), العربية (البحرين), العربية (الجزائر), العربية (مصر), العربية (مصر), العربية (العراق), العربية (الأردن), العربية (الكويت), العربية (لبنان), العربية (ليبيا), العربية (المغرب), العربية (عُمان), العربية (قطر), العربية (المملكة العربية السعودية), العربية (السودان), العربية (سوريا), العربية (تونس), العربية (اليمن), беларуская (Беларусь), български (България), bosanski (Bosna i Hercegovina), català, català (Espanya), català (Espanya) [valencia], کوردیی ناوەندی (عێراق), čeština (Česko), dansk (Danmark), Österreichisches Deutsch (Österreich), Deutsch (Belgien), Schweizer Hochdeutsch (Schweiz), Deutsch (Deutschland), Deutsch (Liechtenstein), Deutsch (Luxemburg), Ελληνικά (Ελλάδα), British English (United Kingdom), American English (United States), esperanto, español de España, español (Argentina), español (Bolivia), español (Chile), español (Colombia), español (Costa Rica), español (Cuba), español (República Dominicana), español (Ecuador), español de España (España), español (Guatemala), español (Honduras), español de México (México), español (Nicaragua), español (Panamá), español (Perú), español (Puerto Rico), español (Paraguay), español (El Salvador), español (Uruguay), español (Venezuela), eesti (Eesti), euskara, euskara (Espainia), euskara (Espainia), فارسی, فارسی (ایران), français, français (Belgique), français canadien (Canada), français suisse (Suisse), français (France), français (Luxembourg), français (Monaco), Gaeilge (IE), Gaeilge (Éire), galego (España), ગુજરાતી (ભારત), עברית, עברית (IL), עברית (ישראל), हिन्दी (भारत), hrvatski (Hrvatska), magyar (Magyarország), Indonesia (Indonesia), íslenska (Ísland), italiano (Svizzera), italiano (Italia), қазақ тілі (Қазақстан), kmr_Latn, 한국어, 한국어 (대한민국), kurdî (Tirkiye), kurdî (Tirkiye), lietuvių (Lietuva), latviešu (Latvija), മലയാളം (ഇന്ത്യ), norsk bokmål (Norge), नेपाली (नेपाल), Nederlands, Nederlands (Aruba), Nederlands (België), Nederlands (Nederland), Nederlands (Suriname), norsk nynorsk (Noreg), polski (Polska), português (Brasil), português europeu (Portugal), română (România), русский (Россия), සිංහල (ශ්‍රී ලංකාව), slovenčina, slovenčina (Slovensko), slovenščina (Slovenija), shqip (Shqipëri), srpski (Srbija), srpski (Crna Gora), српски (Србија), svenska (Finland), svenska (Sverige), తెలుగు (భారతదేశం), ไทย (ไทย), українська, українська (Україна), Tiếng Việt (Việt Nam)`
**Application dictionaries path**: `/home/USER/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Notes`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-2`
**localPath**: `/home/USER/Documents/NC/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `2`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `yes`
**activeNoteSubFolder name**: `A Private`
**database file**: `/home/USER/Documents/NC/Notes/notes.sqlite`

### Cloud connection `XXXXX`

**id**: `2`
**isCurrent**: `yes`
**serverUrl**: `https://nxNNNNNN.your-storageshare.de`
**username**: `XXX`
**accountId**: `XXX`
**Nextcloud Deck boardId**: `0`
**Nextcloud Deck stackId**: `0`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `no`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

### Script `New note namer`

**id**: `1`
**path**: `/home/USER/.local/share/PBE/QOwnNotes/scripts/new-note-namer/new-note-namer.qml`
**variablesJson**: *empty*
**identifier**: `new-note-namer`
**version**: `0.0.1`
**minAppVersion**: `17.06.2`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**CloudConnection-2/nextcloudDeckEnabled** (QString): `true`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging**: *empty*
**DistractionFreeMode/editorWidthMode** (QString): `2`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2024-10-24T10:17:59.092`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `24`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QString): `4 Write`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Cantarell,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Cantarell,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (QString): `600`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/move-notes** (QString): `16384`
**MessageBoxOverride/readonly-mode-allow** (QString): `16384`
**MessageBoxOverride/remove-notes** (QString): `16384`
**NoteFolder-1/NoteTabNameList** (QStringList): `Test, TODO, OPc 03 Bifi`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `A Private, A Private, 4 WritePieces`
**NoteFolder-1/allowDifferentNoteFileName** (QString): `true`
**NoteHistory-1** (QVariantList): `<variant list with 90 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `89`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**WebSocketTokenDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**ai/groq/apiKey** (QString): `<hidden>`
**ai/openai/apiKey** (QString): `<hidden>`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**autoReadOnlyMode** (QString): `false`
**autoReadOnlyModeTimeout** (QString): `30`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**darkMode** (QString): `false`
**darkModeColors** (QString): `false`
**darkModeIconTheme** (QString): `false`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `19`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**noteSubfoldersPanelTabsUnsetAllNotesSelection** (QString): `false`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `0`
**notesPath** (QString): `/home/USER/Documents/NC/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `2`
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Personal, Deck: Personal`
**ownCloud/todoCalendarEnabledList** (QStringList): `Personal, Deck: Personal`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://XXXXXXX/`
**ownCloud/todoCalendarUrlList** (QStringList): https://XXXXXXX
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): `Unknown error`
**ownCloudInfo/notesPathExistsText** (QString): `yes`
**ownCloudInfo/serverVersion** (QString): `29.0.5.1`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `XXXXXXX`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**showStatusBarNotePath** (QString): `true`
**showStatusBarRelativeNotePath** (QString): `false`
**spellCheckLanguage** (QString): `auto`
**startInReadOnlyMode** (QString): `false`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/1/name** (QString): `formattingToolbar`
**toolbar/1/title** (QString): `formatting toolbar`
**toolbar/2/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/2/name** (QString): `insertingToolbar`
**toolbar/2/title** (QString): `inserting toolbar`
**toolbar/3/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/3/name** (QString): `encryptionToolbar`
**toolbar/3/title** (QString): `encryption toolbar`
**toolbar/4/items** (QStringList): `actionEnable_AI, actionAiBackendComboBox, actionAiModelComboBox`
**toolbar/4/name** (QString): `aiToolbar`
**toolbar/4/title** (QString): `AI toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/7/items** (QString): `action_Quit`
**toolbar/7/name** (QString): `quitToolbar`
**toolbar/7/title** (QString): `quit toolbar`
**toolbar/size** (QString): `7`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (QString): `22222`
**webSocketServerService/token** (QString): `<hidden>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**HOME**: `/home/op`
**LANG**: `en_US.UTF-8`
**LC_ADDRESS**: `de_CH.UTF-8`
**LC_IDENTIFICATION**: `de_CH.UTF-8`
**LC_NAME**: `de_CH.UTF-8`
**LC_TELEPHONE**: `de_CH.UTF-8`
**LOGNAME**: `op`
**PATH**: `/home/op/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`
**SHELL**: `/bin/bash`
**USER**: `op`
**XDG_DATA_DIRS**: `/usr/share/gnome:/home/op/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**GTK_MODULES**: `gail:atk-bridge`
**QT_ACCESSIBILITY**: `1`
**QTWEBENGINE_DICTIONARIES_PATH**: `/usr/share/hunspell-bdic/`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**DESKTOP_SESSION**: `gnome`
**GDMSESSION**: `gnome`
**GDM_LANG**: `en_US.UTF-8`
**IM_CONFIG_PHASE**: `1`
**LC_MEASUREMENT**: `de_CH.UTF-8`
**LC_MONETARY**: `de_CH.UTF-8`
**LC_NUMERIC**: `de_CH.UTF-8`
**LC_PAPER**: `de_CH.UTF-8`
**LC_TIME**: `de_CH.UTF-8`
**PWD**: `/home/op`
**SHLVL**: `0`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**USERNAME**: `op`
**XDG_CURRENT_DESKTOP**: `GNOME`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_DESKTOP**: `gnome`
**XDG_SESSION_TYPE**: `wayland`
**MANAGERPID**: `2190`
**INVOCATION_ID**: `4d741b9cd19f425dafaa4f7ac0fd431b`
**JOURNAL_STREAM**: `9:15214`
**SYSTEMD_EXEC_PID**: `2336`
**MEMORY_PRESSURE_WATCH**: `/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/app-gnome\x2dsession\x2dmanager.slice/gnome-session-manager@gnome.service/memory.pressure`
**MEMORY_PRESSURE_WRITE**: `c29tZSAyMDAwMDAgMjAwMDAwMAA=`
**QT_IM_MODULE**: `ibus`
**XMODIFIERS**: `@im=ibus`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**XDG_MENU_PREFIX**: `gnome-`
**SESSION_MANAGER**: `local/x1:@/tmp/.ICE-unix/2336,unix/x1:/tmp/.ICE-unix/2336`
**GNOME_SETUP_DISPLAY**: `:1`
**DISPLAY**: `:0`
**XAUTHORITY**: `/run/user/1000/.mutter-Xwaylandauth.TQDVV2`
**WAYLAND_DISPLAY**: `wayland-0`
**DESKTOP_AUTOSTART_ID**: `1060cad3e5412560a1172975787687641900000023360020`
**GIO_LAUNCHED_DESKTOP_FILE**: `/home/op/.config/autostart/PBE.QOwnNotes.desktop`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `2562`
**XCURSOR_SIZE**: `24`
**XCURSOR_THEME**: `Adwaita`
</details>

**Comment by digisus** [comment]
Short screencast to illustrate:

https://github.com/user-attachments/assets/7e0638e0-694f-4a13-b717-60c01c6d0fd9

**Comment by pbek** [comment]
Duplicate of #3109?
I was never able to reproduce that. 😬
