### ISSUE TITLE
[BUG] Indented tables don't get formatted right on the editor view

### ISSUE THREAD

**Issue by 77nnit** [pbek/QOwnNotes#3137]
#### Expected behaviour
When creating a table that is *indented* relative to the paragraph (2 spaces in front of each row of the table) it should rendered as any other unindented table, just the left margin increased by a tab width.

#### Actual behaviour
The table is rendered correctly in the preview window, but this is not the case for the editor window.

![2024-10-28- 0001](https://github.com/user-attachments/assets/b8de03b5-91f6-4e98-97c3-1cfd732f73e2)

#### Steps to reproduce
1. Create a table and check that it is rendered correctly on editor and on preview.
2. Add 2 spaces in front of each table line on the editor.
3. Table formattig on preview is fine, but on editor view is broken

#### Output from the debug section in the settings dialog
No isseus are reported by debugger

#### Relevant log output in the Log panel
No output

**Comment by pbek** [comment]
Hm, where have you found that this should be supported?

**Comment by 77nnit** [comment]
Nowhere, I just expected that editor and preview should behave similarly. 

Should I have classified the issue differently?

**Comment by pbek** [comment]
The Markdown to HTML transformation is done by https://github.com/mity/md4c. Seems like they support leading spaces up to 3... I don't know why.

**Comment by pbek** [comment]
## 24.10.4
- Markdown tables can now be indented with up to three spaces to match the behavior
  of the preview (for [#3137](https://github.com/pbek/QOwnNotes/issues/3137))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by 77nnit** [comment]
Sure! It works. Probably it supports up to three spaces because after four it gets parsed as a codeblock. 

Here's the test result:
![Indented tables test](https://github.com/user-attachments/assets/d0a2d0aa-f2bd-4bd7-9177-bf4d838a9835)

Here's my test's markdown:

Normal table

| id  | key  | value   |
| --- | ---- | ------- |
| 1   | key1 | value 1 |

   Indented Table only does not get rendered as indented

   | id  | key  | value   |
   | --- | ---- | ------- |
   | 1   | key1 | value 1 |
  
- Unless it is below a list item (the line in between can be empty)

  | id  | key  | value   |
  | --- | ---- | ------- |
  | 1   | key1 | value 1 |


- Single indentation
  - Double indentation (with 4 spaces or more): in the editor the table gets rendered as 4 spaces codeblock, but it's fine.
 
    | id  | key  | value   |
    | --- | ---- | ------- |
    | 1   | key1 | value 1 |


- Single indentation
  - Double indentation (with 4 spaces)
    - Triple indentation (with 6 spaces)   
 
      | id  | key  | value   |
      | --- | ---- | ------- |
      | 1   | key1 | value 1 |

**Comment by pbek** [comment]
## 24.10.5
- The capturing of indented Markdown tables was improved (for [#3137](https://github.com/pbek/QOwnNotes/issues/3137))

**Comment by pbek** [comment]
## 24.12.2
- The automatic Markdown table formatter now supports trimming tables with
  leading spaces (for [#3137](https://github.com/pbek/QOwnNotes/issues/3137))
