### ISSUE TITLE
Feature request: automatic updates for Mac

### ISSUE THREAD

**Issue by markandrewj** [pbek/QOwnNotes#314]
Hello,

I am giving QOwnNotes a go, and so far I am enjoying it. I setup an instance of ownCloud just to try it. I think it would be strong as a stand alone app too. It feels like a balance of something between org-mode and Evernote. It fits great into my workflow. QOwnNotes being based on plain text files and working well offline is great for me.

I currently use QOwnNotes for Mac and Linux. It is really great to see lots of development, however the update process for Mac is a little annoying with all the updates. It is much easier to do 'apt upgrade' in Ubuntu. As a future suggestion I think it would be great to incorporate https://sparkle-project.org/ or make a QOwnNotes a brew package for easy upgrading.

**Comment by markandrewj** [comment]
I noticed there is an open issue for this so I am closing it adding moving my comments over to the existing ticket.

**Comment by pbek** [comment]
thank you ;)

**Comment by pbek** [comment]
Thank you for your kind words, but Sparkle is written in Objective-C / Swift. QOwnNotes is written in Qt.

**Comment by markandrewj** [comment]
I know it's not typical but you are supposed to be able to mix obj-c into Qt.

Here is an example of using Sparkle with Qt. http://www.discoversdk.com/knowledge-base/using-sparkle-in-qt

**Comment by pbek** [comment]
Sounds nice, thank you. I wonder if that would ever work with Travis CI (where the release building is done) and best with both qmake and cmake.

**Comment by pbek** [comment]
I'll move to #102.

**Comment by markandrewj** [comment]
I am just going to post the last bit of this conversation here, I don't want to just post the tail end to the other ticket. I am not sure what the process would be, as I have not compiled Qt with obj-c under Travis. However, currently Sparkle is using Travis CI https://travis-ci.org/sparkle-project. There is also this project that was made as part of mendeley https://github.com/Mendeley/Update-Installer, it has been a long time since I have used mendeley though so I don't remember how smooth the update process was for it.
