### ISSUE TITLE
[Q] Is the "new note" template configurable?

### ISSUE THREAD

**Issue by BsNoSi** [pbek/QOwnNotes#3142]
A new note has this standard entry
```
Note 2024-10-29T14.30.24
========================
↓
```
where ↓ is the cursor position.

Is it possible to configure this to

``` 
# ↓time stamp
```

( Only a "nice to have", because I prefer # instead of =… for level 1 headlines and always replace the time stamp with a explaining headline)

**Comment by pbek** [comment]
You either can use https://www.qownnotes.org/scripting/hooks.html#handlenotenamehook to determine the note name or write your own custom action with https://www.qownnotes.org/scripting/methods-and-objects.html#registering-a-custom-action to create a note and set the cursor position.

**Comment by BsNoSi** [comment]
🤔 I see – its not a template, its coded. Which is o.k. for me but it means a much higher attempt to achieve that, opening on the other hand a vast field of further possibilities.

At the moment, because of other time comsuming reasons, I have to keep this in mind because the training effort will be more time-consuming as modifying a template.

The links are helpful 🙏
