### ISSUE TITLE
[BUG] ? Font Size → Find Action

### ISSUE THREAD

**Issue by BsNoSi** [pbek/QOwnNotes#3143]
I can adjust the font size in settings → extremely helpful, a big hand for that

Maybe it slipped through:

① Font is increased as I hoped for ✔
② Listing of actions is shown with “micro font” 😧

A larger font can be displayed in the drop-down menu itself (shortcuts), which is why this seems to be a bug (to me).

![image](https://github.com/user-attachments/assets/c9bc93ae-e2f2-45ac-8d27-730ba698be12)

**Comment by pbek** [comment]
Can you please explain in more detail and step by step what you did, what happened and what you expected?

Can you please post the output from the *Debug settings* in the settings dialog? You just need to paste it here.
And is there any useful log output if you enable the log panel (see Window / Panels)?
Please make sure you also enable debug logging in the log panel by right-clicking on the panel and selecting `Debug` in `Options`.
The issue dialog in the help menu can help you with all of that.

**Comment by BsNoSi** [comment]
There where no special steps:

In Settings → Interface »List and tree item height« is set to 34px, »interface font size« to 22px, which is VERY nice on a 4K screen with only 125% zoom level. (Severeal restarts, open program, a.s.o.)

After given hint from you, I tried this (and it took I while, to acknowledge, what was irritating me):

menu → help → find actions: Drop down opens like shown above.

**Comment by pbek** [comment]
It's really stressful for me to sieve through everything you write, and find out what you were doing and what you are trying to tell me. 😅

Ok, let's try again. 
Can you please use the issue assistant in the *Help* menu? It helps you write an issue report.

**Comment by BsNoSi** [comment]
I wonder if an extensive log file would help anyway to reduce your stress. 👉 I do not want you to have any because of me. 
I would define that as a (little but possibly more persistent) bug but with a lower priority. How low is your decision.  

Perhaps a short question will help you to concretize “my problem” faster/better:

Why is using the listed actions (left side) in the drop down the system font size instead of the font size, given in settings and used in the dropdown for the hotkey description (right side)?

> To be honest, I have no idea, why my bug message is labeled with “support” (can not remember, that I set this).

**Comment by pbek** [comment]
Did you read the text when you opened this issue on <https://github.com/NixOS/nixpkgs/issues/new?assignees=&labels=0.kind%3A+bug&projects=&template=bug_report.md&title=>? It explains how to open an issue, what information is important and the structure of the information.

**Comment by BsNoSi** [comment]
🤔 Behaves QOwnNotes on your PC different → description of text has same size as hotkeys in »Find Action« list?

To behave as constructive as possible, I transferred the information into an issue, generated with the QOwnNotes function:  https://github.com/pbek/QOwnNotes/issues/3145
