### ISSUE TITLE
[FEATURE] Searching for "A" AND "B"

### ISSUE THREAD

**Issue by BsNoSi** [pbek/QOwnNotes#3144]
As described here 
https://www.qownnotes.org/getting-started/searching.html 
multiple words are searched for with an OR condition.

For targeting a note in a huge notebook probably AND will be more efficient to match notes having all given elements.

Currently, only inside a single note regex is supported. But, to be honest, a lookahead regex for example 
```
(?=.*\bfirst\b)(?=.*\bQsecond\b)
``` 
is not handy for frequent use.

AND would be a great support for fast matching fitting note.

Maybe It can be triggered by "A: …" aligning to "N: …" for notebook title.

**Comment by pbek** [comment]
Yes, it would be great. 
But it's *very* hard to do that in the SQLite in-memory note-database, and the current code that spreads over many methods is already very complex. And the complete syntax of the search terms would need some rethinking and reimplementation.

**Comment by BsNoSi** [comment]
🤔 o.k. – I assumed that the Markdown notes on the disk were being searched.
Maybe a solution could be, to offer *extended* search, doing it within the notebook folder on disk, comparable to file search of (as an example) notepad++ regex search.

👉 This is currently my workaround, which is a bit cumbersome ...
