### ISSUE TITLE
[I] Wrong Font Size in Action List

### ISSUE THREAD

**Issue by BsNoSi** [pbek/QOwnNotes#3145]
#### Expected behaviour

All text in action list (Help → Action list) has the font size, defined in program settings.

#### Actual behaviour

The description of actions has system font size, hotkey uses font size defined in Note → Settings → Interface → Interface → »font size« (22px) and »List and tree item height« (34 px).

#### Steps to reproduce

Increase font size in settings, open help → Action list

![image](https://github.com/user-attachments/assets/c9bc93ae-e2f2-45ac-8d27-730ba698be12)

② action description → system font
① menu font and all other: as set in settings.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[12:12:56] [info] "QOwnNotes-Server arbeitet auf Port 22222"
[12:12:57] [status] Keine Skript-Aktualisierungen gefunden
[12:13:48] [status] Notizverzeichnis wurde extern verändert
[12:17:19] [status] Notizverzeichnis wurde extern verändert
[12:17:20] [status] Notizverzeichnis wurde extern verändert
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mi Okt 30 14:50:45 2024`
**Version**: `24.10.4`
**Build date**: `Oct 28 2024`
**Build number**: `1135`
**Platform**: `windows (windows)`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\Norbert\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Tools\QOwnNotes\QOwnNotes.exe`, `C:\Tools\QOwnNotes\QOwnNotes.exe`, `C:\Tools\QOwnNotes\QOwnNotes.exe`, `--allow-multiple-instances`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Primary screen resolution**: `3840x2160`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `451`
**Calendar items**: `3`
**Enabled scripts**: `3`
**Database drivers**: `QSQLITE, QODBC, QODBC3, QPSQL, QPSQL7`

## Server Info

**serverUrl**: `https://xxxxx`
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `de_DE_frami, en_GB`
**Language names**: `Deutsch (Deutschland), British English (United Kingdom)`
**Application dictionaries path**: `C:\Users\Norbert\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Notizen`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `C:\Tools\Notizen\NC-Sync`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: `OffSiteEdit`
**database file**: `C:\Tools\Notizen\NC-Sync\notes.sqlite`

### Cloud connection `Standard`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://xxxxx`
**username**: `xxxxx`
**accountId**: *empty*

### Script `Markdown-it markdown parser`

**id**: `1`
**path**: `C:\Users\Norbert\AppData\Roaming\PBE\QOwnNotes\scripts\markdown-it\markdown-it.qml`
**variablesJson**: 
```
{
    "customStylesheet": "",
    "options": "{\n    html:         true,        // Enable HTML tags in source\n    //xhtmlOut:     false,        // Use '/' to close single tags (<br />)\n    breaks:       true,        // Convert '\\n' in paragraphs into <br>\n    //langPrefix:   'language-',  // CSS language prefix for fenced blocks\n    linkify:      true,        // autoconvert URL-like texts to links\n\n    // Enable some language-neutral replacements + quotes beautification\n    typographer:  true,\n\n    // Double + single quotes replacement pairs, when typographer enabled,\n    // and smartquotes on. Could be either a String or an Array.\n    //\n    // For example, you can use '«»„“' for Russian, '„“‚‘' for German,\n    // and ['«\\xA0', '\\xA0»', '‹\\xA0', '\\xA0›'] for French (including nbsp).\n    //quotes: '\\u201c\\u201d\\u2018\\u2019', /* “”‘’ */\n\n    // Highlighter function. Should return escaped HTML,\n    // or '' if the source string is not changed and should be escaped externaly.\n    // If result starts with <pre... internal wrapper is skipped.\n    //\n    // function (/*str, lang*/) { return ''; }\n    //\n    //highlight: null,\n\n    //maxNesting:   100            // Internal protection, recursion limit\n}",
    "useDeflistPlugin": true
}
```
**identifier**: `markdown-it`
**version**: `1.4`
**minAppVersion**: `20.6.0`

### Script `Custom note preview styling`

**id**: `2`
**path**: `C:\Users\Norbert\AppData\Roaming\PBE\QOwnNotes\scripts\preview-styling\preview-styling.qml`
**variablesJson**: 
```
{
    "customStylesheet": "@supports (font-variation-settings:normal){html{font-family:'Commissioner', sans-serif;font-variation-settings:\"wght\" 380 \"FLAR\" 0 \"VOLM\" 0 \"slnt\" 0;font-display:swap;text-rendering:optimizeLegibility;}\nstrong{font-weight:normal;font-variation-settings:\"wght\" 700,\"FLAR\" 100, \"VOLM\" 100;}\nem{font-style:normal;padding:0;font-variation-settings:\"wght\" 400,\"slnt\" -10, \"FLAR\" 50, \"VOLM\" 50;}\nstrong em, em strong, dt em,article > p:first-of-type em{font-variation-settings:\"wght\" 550,\"slnt\" -10,\"FLAR\" 50, \"VOLM\" 50;}\n}\nhtml{font-display:swap;text-rendering:optimizeLegibility;color:#444;//font-size:1.15rem;//  line-height:1.45;lang:\"de\"}\nbody{color:#444;}\n@media only screen{body{margin:0 auto;padding:30px;padding-bottom:100px;max-width:42em;font-size:clamp(0.8em,2vw,1.5em);}\n}\na{color:#336699;}\nh1,h2,h3,h4,h5,h6{color:#336699;position:relative;margin-top:1rem;margin-bottom:1rem;font-weight:bold;line-height:1.5;cursor:text;}\nh1:hover a.anchor,h2:hover a.anchor,h3:hover a.anchor,h4:hover a.anchor,h5:hover a.anchor,h6:hover a.anchor{text-decoration:none;}\nh1 tt,h1 code{font-size:inherit;}\nh2 tt,h2 code{font-size:inherit;}\nh3 tt,h3 code{font-size:inherit;}\nh4 tt,h4 code{font-size:inherit;}\nh5 tt,h5 code{font-size:inherit;}\nh6 tt,h6 code{font-size:inherit;}\nh1{font-size:2.25em;line-height:1.2;}\nh2{font-size:1.75em;line-height:1.225;}\nh3{font-size:1.5em;line-height:1.43;}\nh4{font-size:1.25em;}\nh5{font-size:1em;}\nh6{font-size:1em;}\np,ul,ol,dl,table{margin:0.8em 0;}\np{hyphens:auto;hyphenate-limit-chars:6 2 2;hyphenate-limit-lines:2;hyphenate-limit-last:always;hyphenate-limit-zone:8%;text-align:justify;text-align-last:none;orphans:3;widows:4;line-height:1.35em;}\nem{font-style:italic;font-variation-settings:\"wght\" inherit,\"FLAR\" 80,\"VOLM\" 80;padding:0 0.15em}\nli>ol,li>ul{margin:0 0;}\nhr{height:2px;padding:0;margin:16px 0;background-color:#e7e7e7;border:0 none;overflow:hidden;box-sizing:content-box;}\nli p.first{display:inline-block;}\nul,ol{padding-left:30px;}\nul:first-child,ol:first-child{margin-top:0;}\nul:last-child,ol:last-child{margin-bottom:0;}\ncode{background-color:#f3f4f4;padding:0 2px 0 2px;}\ndt{font-weight:bold;font-variation-settings:\"wght\" 700,\"FLAR\" 100,\"VOLM\" 100;font-size:1.05em;padding-top:.2em;}\ndd{padding-left:1em}\n\n@media print{html{font-size:13px;}\npre{page-break-inside:avoid;word-wrap:break-word;}\n}\nsub{font-size:0.75em;vertical-align:0.0em}\nsup{font-size:0.75em;vertical-align:0.3em}\nblockquote{padding:0 0 0 1rem;display:grid;grid-template-columns:100%;grid-gap:0;color:#444;}\nblockquote{border-left:0.5rem solid #00AA00;border-radius:0 0.3rem 0.3rem 0;}\nblockquote blockquote{margin:-0.3rem -0.3rem -0.3rem -1.55rem;border-left:0.6rem solid #FFBB00;}\nblockquote blockquote blockquote{margin:-0.3rem -0.3rem -0.3rem -1.6rem;border-left:0.7rem solid #DD0000;}\nblockquote ul,blockquoteol{padding-left:2rem;}\nblockquote ul>ul,blockquote ol>ol,blockquote ol>ul,blockquote ul>ol{border-left:none;}\nblockquote table{display:block;padding:1em;width:100%;border-bottom:none;}\nblockquote tbody{border-bottom:1px solid #336699;}\ntable{margin:0 0 0.3em 0;padding:0;border-bottom:1px solid #336699;border-collapse:collapse;width:100%;}\nth,td{padding:0.3em;}\nth{background-color:#336699;color:#fdfdfd;;border:1px solid #336699;}\ntr td{border-left:1px solid #336699;border-right:1px solid #336699;}\ntr:nth-child(odd){background-color:#D1E8FF;}\ntd{vertical-align:top;}\np:first{font-weight:bold}\n"
}
```
**identifier**: `preview-styling`
**version**: `0.0.5`
**minAppVersion**: `20.6.0`

### Script `Export notes as one HTML file`

**id**: `3`
**path**: `C:\Users\Norbert\AppData\Roaming\PBE\QOwnNotes\scripts\export-notes-as-one-html\export-notes-as-one-html.qml`
**variablesJson**: *empty*
**identifier**: `export-notes-as-one-html`
**version**: `1.0.0`
**minAppVersion**: `18.03.7`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**CloudConnection-1/nextcloudDeckBoardId** (int): `1`
**CloudConnection-1/nextcloudDeckEnabled** (QString): `false`
**CloudConnection-1/nextcloudDeckStackId** (int): `1`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging**: *empty*
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**DistractionFreeMode/editorWidthCustom** (int): `64`
**DistractionFreeMode/editorWidthMode** (int): `1`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (int): `36`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `false`
**Editor/autoBracketRemoval** (QString): `false`
**Editor/centerCursor** (bool): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (QString): `true`
**Editor/showLineNumbers** (QString): `true`
**Editor/useTabIndent** (QString): `true`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `D:/temp`
**FileDialog/LastPath-Joplin Import** (QString): `F:/Joplin`
**FileDialog/LastPath-NotePDFExport** (QString): `D:/temp`
**FileDialog/LastPath-PreviewHTMLFileExport** (QString): `D:/temp`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**JoplinImport/AttachmentImportCheckBoxChecked** (QString): `true`
**JoplinImport/FolderImportCheckBoxChecked** (QString): `true`
**JoplinImport/ImageImportCheckBoxChecked** (QString): `true`
**JoplinImport/MetadataImportCheckBoxChecked** (QString): `false`
**JoplinImport/TagImportCheckBoxChecked** (QString): `true`
**JoplinImportDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2024-10-30T14:13:55.918`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `30`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Entwicklung/Screenshot, Bücher, Entwicklung, Notizen, Artikel`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,16,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Fira Code Medium,15,-1,5,57,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Courier New,12,-1,5,50,0,0,0,0,0,Standard`
**MainWindow/noteTextView.font** (QString): `Commissioner Flair,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (int): `1000`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `false`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/windows-light-mode** (int): `65536`
**NoteBookmark1** (NoteHistoryItem): `<binary data>`
**NoteBookmark2** (NoteHistoryItem): `<binary data>`
**NoteBookmark6** (NoteHistoryItem): `<binary data>`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteDialog/tabWidgetIndex** (int): `0`
**NoteFolder-1/NoteTabNameList** (QStringList): `Bilder mit Zoom`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): 
```
Entwicklung
OffSiteEdit
```
**NoteHistory-1** (QVariantList): `<variant list with 99 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `98`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExportOrientation** (int): `0`
**Printer/NotePDFExportPageSize** (int): `4`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-actionFind_action** (QString): *empty*
**Shortcuts/MainWindow-actionInsert_text_link** (QString): *empty*
**Shortcuts/MainWindow-action_Open_note_in_external_editor** (QString): `Alt+X`
**Shortcuts/MainWindow-customAction_exportHTML** (QString): *empty*
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**StoredImagesDialog/geometry** (QByteArray): `<binary data>`
**TableDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (int): `0`
**TodoDialog/showDueTodayItemsOnly** (int): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Deck: Persönlich`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**ai/groq/apiKey** (QString): `<hidden>`
**ai/openai/apiKey** (QString): `<hidden>`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**autoReadOnlyMode** (QString): `false`
**autoReadOnlyModeTimeout** (int): `30`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `2`
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `false`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): `C:\Program Files\Typora\Typora.exe`
**fullyHighlightedBlockquotes** (QString): `true`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): `dd.MM.yyyy hh:mm`
**interfaceFontSize** (int): `22`
**interfaceLanguage** (QString): *empty*
**interfaceStyle** (QString): `Windows`
**internalIconTheme** (QString): `true`
**itemHeight** (int): `34`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**maxNoteFileSize** (int): `1048576`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `60`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `1`
**noteSubfoldersPanelTabsUnsetAllNotesSelection** (QString): `false`
**notesPanelOrder** (int): `1`
**notesPanelSort** (int): `1`
**notesPath** (QString): `C:/Tools/Notizen/NC-Sync`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `true`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `040be292-ff43-43b4-a234-58ed527afa85`
**recentNoteFolders** (QStringList): `C:/Tools/Notizen`
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2024-10-30T10.03.41, Note 2024-10-29T14.30.24, QOwnnotes einrichten, Note 2024-10-29T06.57.17, Note 2024-10-28T13.56.28, Note 2024-10-28T10.59.55, Note 2024-10-28T06.45.39, Note 2024-10-27T17.38.06, Note 2024-10-27T15.49.39, OffSiteEdit`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**showStatusBarNotePath** (QString): `true`
**showStatusBarRelativeNotePath** (QString): `false`
**spellCheckLanguage** (QString): `auto`
**startInReadOnlyMode** (QString): `false`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `true`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/1/name** (QString): `formattingToolbar`
**toolbar/1/title** (QString): `Formatierungs-Werkzeugleiste`
**toolbar/2/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/2/name** (QString): `insertingToolbar`
**toolbar/2/title** (QString): `Einfügen-Werkzeugleiste`
**toolbar/3/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/3/name** (QString): `encryptionToolbar`
**toolbar/3/title** (QString): `Verschlüsselung-Werkzeugleiste`
**toolbar/4/items** (QStringList): *empty*
**toolbar/4/name** (QString): `aiToolbar`
**toolbar/4/title** (QString): `KI-Toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `Fenster-Werkzeugleiste`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `Beenden - Symbolleiste`
**toolbar/7/items** (QStringList): `action_Quit`
**toolbar/7/name** (QString): `quitToolbar`
**toolbar/7/title** (QString): `Beenden - Symbolleiste`
**toolbar/size** (int): `7`
**useNoteFolderButtons** (QString): `false`
**useSoftWrapInNoteEditor** (QString): `true`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): *empty*
**webSocketServerService/bookmarksTag** (QString): `Browsernotiz`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (int): `22222`
**workspace-040be292-ff43-43b4-a234-58ed527afa85/name** (QString): `- Vorschau`
**workspace-040be292-ff43-43b4-a234-58ed527afa85/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-040be292-ff43-43b4-a234-58ed527afa85/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `+ Vorschau`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 040be292-ff43-43b4-a234-58ed527afa85`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\Norbert\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `xxxx`
**ComSpec**: `C:\windows\system32\cmd.exe`
**configsetroot**: `C:\windows\ConfigSetRoot`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\Norbert`
**LOCALAPPDATA**: `C:\Users\Norbert\AppData\Local`
**LOGONSERVER**: `\\xxxx`
**NUMBER_OF_PROCESSORS**: `16`
**OneDrive**: `C:\Users\Norbert\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Embarcadero\Studio\23.0\bin;C:\Program Files (x86)\Embarcadero\Studio\23.0\bin64;C:\Entwicklung\Studio\23.0\bin;C:\Entwicklung\Studio\23.0\bin64;C:\Entwicklung\Embarcadero\Studio\23.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\23.0\Bpl;C:\Entwicklung\Embarcadero\Studio\23.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\23.0\Bpl\Win64;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files\AdoptOpenJDK\jdk-8.0.242.08-hotspot\bin;C:\Entwicklung\Studio\22.0\bin;C:\Entwicklung\Studio\22.0\bin64;C:\Program Files (x86)\Embarcadero\Studio\22.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\22.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\22.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\22.0\Bpl\Win64;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Entwicklung\Windows\Kits\10\Windows Performance Toolkit\;C:\Entwicklung\Git\cmd;C:\PHP8;C:\Program Files\WireGuard\;C:\texlive\2023\bin\windows;C:\Program Files\Wondershare\Wondershare DemoCreator (Deutsch);C:\Program Files\Wondershare\Wondershare DemoCreator (Deutsch);C:\Program Files\Wondershare\Wondershare DemoCreator (Deutsch);C:\Program Files\NVIDIA Corporation\NVIDIA app\NvDLISR;C:\Users\Norbert\AppData\Local\Microsoft\WindowsApps;;C:\Users\Norbert\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Norbert\AppData\Local\Pandoc\`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 167 Stepping 1, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `a701`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\windows`
**TEMP**: `C:\Users\Norbert\AppData\Local\Temp`
**TMP**: `C:\Users\Norbert\AppData\Local\Temp`
**USERDOMAIN**: `xxxx`
**USERDOMAIN_ROAMINGPROFILE**: `xxxxx`
**USERID**: `Norbert-172.30.176.1`
**USERNAME**: `Norbert`
**USERPROFILE**: `C:\Users\Norbert`
**windir**: `C:\windows`
**ZES_ENABLE_SYSMAN**: `1`
**ZKA_SIG_HOME**: `C:\Program Files (x86)\REINER SCT\cyberJack`
</details>

**Comment by pbek** [comment]
I still don't understand your sentences, but at least the issue title now makes more sense. 😅

This is what I came up on my own:

If you are overriding the interface font size in the *Interface settings*, the action names in the "Find action" dialog still are using the system font size.

Is this what you were trying to report?

**Comment by pbek** [comment]
Thank you for reporting. I saw that the `CommandBar` is implemented in a way where for some reason Qt is not applying the global styling. I will implement a manual setting of the font size.

**Comment by BsNoSi** [comment]
First: This is it.

I beg your indulgence. I have been using QOwnNotes for 2/3 days now as a switcher from Joplin. Many questions are running through my brain like a tornado, blocking my clear thinking. Of course, this is also reflected in my requests. For me, they are absolutely clear, but that is of little use for you. The irregular requirement of writing in English will do the rest…

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by BsNoSi** [comment]
Wow. I do not know a single commercial company fixing bugs with a comparable speed.
An impressive argument for using the issue-tool of QOwnNotes (`Help` → `Post Questions …`).
![image](https://github.com/user-attachments/assets/01cfdaa3-a79d-4fcb-a279-0e9e4b0f6c3f)

**Comment by pbek** [comment]
Great, thank you for testing!

> Wow. I do not know a single commercial company fixing bugs with a comparable speed.

The power of passion! 😆 But it took a while to get around the problem.

**Comment by BsNoSi** [comment]
To be honest, I did not expect a fast fix of that. To me, it looked like a »very deep inside code« side effect, which is usually very hard (or with tremendous effort or both) to fix. 👏

**Comment by pbek** [comment]
It was even hard to locate where to fix it and how.

**Comment by BsNoSi** [comment]
I can imagine that (I'm looking for a similar effect in one of my own projects).
