### ISSUE TITLE
[I] Autohotkey Inserts a crumpled

### ISSUE THREAD

**Issue by BsNoSi** [pbek/QOwnNotes#3149]
#### Expected behaviour

Usage of [Autohotkey](https://autohotkey.com/) as in any other application.

#### Actual behaviour

If an insert phrase contains symbols ( 😉 🤣 🙆 … ) the input is crumbled (s. video).

> Currently, insertion of symbols seems to be only possible with external editor or with clipboard.

https://github.com/user-attachments/assets/d508ed61-e70d-4561-b7a0-057c5e73343d

#### Steps to reproduce

1. Install Autohotkey.
2. Define replacement phrases
	- →   :?*:,zg::✔    ; this will work
	- →   :?*:..blink::😉  ; this will crumble
3. Reload Autohotkey script
3. Open Note and try autohotkey shortcuts

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[08:32:21] [debug] updatePanelMenu - 'updatePanelMenu'
[08:32:21] [debug] currentLocalPath - 'currentLocalPath': "C:/Tools/Notizen/NC-Sync"
[08:32:21] [debug] Code block of lang detected: "\r" 0
[08:32:21] [debug] Code block of lang detected: "\r" 0
[08:32:21] [debug] cloudConnection: CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://xx.xxx.de" <username>"xxxx" <accountId>"" <priority>1
[08:32:21] [debug] updatePanelMenu - 'updatePanelMenu'
[08:32:21] [debug] currentLocalPath - 'currentLocalPath': "C:/Tools/Notizen/NC-Sync"
[08:32:21] [debug] Code block of lang detected: "\r" 0
[08:32:21] [debug] Code block of lang detected: "\r" 0
[08:32:21] [debug] cloudConnection: CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://xx.xxx.de" <username>"xxxx" <accountId>"" <priority>1
[08:32:21] [debug] currentLocalPath - 'currentLocalPath': "C:/Tools/Notizen/NC-Sync"
[08:32:27] [debug] currentLocalPath - 'currentLocalPath': "C:/Tools/Notizen/NC-Sync"
[08:32:27] [debug] Code block of lang detected: "\r" 0
[08:32:27] [debug] Code block of lang detected: "\r" 0
[08:32:27] [debug] cloudConnection: CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://xx.xxx.de" <username>"xxxx" <accountId>"" <priority>1
[08:32:28] [debug] currentLocalPath - 'currentLocalPath': "C:/Tools/Notizen/NC-Sync"
[08:32:28] [debug] Code block of lang detected: "\r" 0
[08:32:28] [debug] Code block of lang detected: "\r" 0
[08:32:28] [debug] cloudConnection: CloudConnection: <id>1 <name>"Standard" <serverUrl>"https://xx.xxx.de" <username>"xxxx" <accountId>"" <priority>1
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `So Nov 3 08:41:57 2024`
**Version**: `24.10.5`
**Build date**: `Oct 30 2024`
**Build number**: `1136`
**Platform**: `windows (windows)`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\xxxx\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Tools\QOwnNotes\QOwnNotes.exe`, `C:\Tools\QOwnNotes\QOwnNotes.exe`, `--allow-multiple-instances`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Primary screen resolution**: `3840x2160`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `453`
**Calendar items**: `3`
**Enabled scripts**: `3`
**Database drivers**: `QSQLITE, QODBC, QODBC3, QPSQL, QPSQL7`

## Server Info

**serverUrl**: `https://xx.xxx.de`
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: `auto`
**Language codes**: `de_DE_frami, en_GB`
**Language names**: `Deutsch (Deutschland), British English (United Kingdom)`
**Application dictionaries path**: `C:\Users\xxxx\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Notizen`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `C:\Tools\Notizen\NC-Sync`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Tools\Notizen\NC-Sync\notes.sqlite`

### Cloud connection `Standard`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://xx.xxx.de`
**username**: `xxxx`
**accountId**: *empty*

### Script `Markdown-it markdown parser`

**id**: `1`
**path**: `C:\Users\xxxx\AppData\Roaming\PBE\QOwnNotes\scripts\markdown-it\markdown-it.qml`
**variablesJson**: 
```
{
    "customStylesheet": "",
    "options": "{\n    html:         true,        // Enable HTML tags in source\n    //xhtmlOut:     false,        // Use '/' to close single tags (<br />)\n    breaks:       true,        // Convert '\\n' in paragraphs into <br>\n    //langPrefix:   'language-',  // CSS language prefix for fenced blocks\n    linkify:      true,        // autoconvert URL-like texts to links\n\n    // Enable some language-neutral replacements + quotes beautification\n    typographer:  true,\n\n    // Double + single quotes replacement pairs, when typographer enabled,\n    // and smartquotes on. Could be either a String or an Array.\n    //\n    // For example, you can use '«»„“' for Russian, '„“‚‘' for German,\n    // and ['«\\xA0', '\\xA0»', '‹\\xA0', '\\xA0›'] for French (including nbsp).\n    //quotes: '\\u201c\\u201d\\u2018\\u2019', /* “”‘’ */\n\n    // Highlighter function. Should return escaped HTML,\n    // or '' if the source string is not changed and should be escaped externaly.\n    // If result starts with <pre... internal wrapper is skipped.\n    //\n    // function (/*str, lang*/) { return ''; }\n    //\n    //highlight: null,\n\n    //maxNesting:   100            // Internal protection, recursion limit\n}",
    "useDeflistPlugin": true
}
```
**identifier**: `markdown-it`
**version**: `1.4`
**minAppVersion**: `20.6.0`

### Script `Custom note preview styling`

**id**: `2`
**path**: `C:\Users\xxxx\AppData\Roaming\PBE\QOwnNotes\scripts\preview-styling\preview-styling.qml`
**variablesJson**: 
```
{
    "customStylesheet": "@supports (font-variation-settings:normal){html{font-family:'Commissioner', sans-serif;font-variation-settings:\"wght\" 380 \"FLAR\" 0 \"VOLM\" 0 \"slnt\" 0;font-display:swap;text-rendering:optimizeLegibility;}\nstrong{font-weight:normal;font-variation-settings:\"wght\" 700,\"FLAR\" 100, \"VOLM\" 100;}\nem{font-style:normal;padding:0;font-variation-settings:\"wght\" 400,\"slnt\" -10, \"FLAR\" 50, \"VOLM\" 50;}\nstrong em, em strong, dt em,article > p:first-of-type em{font-variation-settings:\"wght\" 550,\"slnt\" -10,\"FLAR\" 50, \"VOLM\" 50;}\n}\nhtml{font-display:swap;text-rendering:optimizeLegibility;color:#444;//font-size:1.15rem;//  line-height:1.45;lang:\"de\"}\nbody{color:#444;}\n@media only screen{body{margin:0 auto;padding:30px;padding-bottom:100px;max-width:42em;font-size:clamp(0.8em,2vw,1.5em);}\n}\na{color:#336699;}\nh1,h2,h3,h4,h5,h6{color:#336699;position:relative;margin-top:1rem;margin-bottom:1rem;font-weight:bold;line-height:1.5;cursor:text;}\nh1:hover a.anchor,h2:hover a.anchor,h3:hover a.anchor,h4:hover a.anchor,h5:hover a.anchor,h6:hover a.anchor{text-decoration:none;}\nh1 tt,h1 code{font-size:inherit;}\nh2 tt,h2 code{font-size:inherit;}\nh3 tt,h3 code{font-size:inherit;}\nh4 tt,h4 code{font-size:inherit;}\nh5 tt,h5 code{font-size:inherit;}\nh6 tt,h6 code{font-size:inherit;}\nh1{font-size:2.25em;line-height:1.2;}\nh2{font-size:1.75em;line-height:1.225;}\nh3{font-size:1.5em;line-height:1.43;}\nh4{font-size:1.25em;}\nh5{font-size:1em;}\nh6{font-size:1em;}\np,ul,ol,dl,table{margin:0.8em 0;}\np{hyphens:auto;hyphenate-limit-chars:6 2 2;hyphenate-limit-lines:2;hyphenate-limit-last:always;hyphenate-limit-zone:8%;text-align:justify;text-align-last:none;orphans:3;widows:4;line-height:1.35em;}\nem{font-style:italic;font-variation-settings:\"wght\" inherit,\"FLAR\" 80,\"VOLM\" 80;padding:0 0.15em}\nli>ol,li>ul{margin:0 0;}\nhr{height:2px;padding:0;margin:16px 0;background-color:#e7e7e7;border:0 none;overflow:hidden;box-sizing:content-box;}\nli p.first{display:inline-block;}\nul,ol{padding-left:30px;}\nul:first-child,ol:first-child{margin-top:0;}\nul:last-child,ol:last-child{margin-bottom:0;}\ncode{background-color:#f3f4f4;padding:0 2px 0 2px;}\ndt{font-weight:bold;font-variation-settings:\"wght\" 700,\"FLAR\" 100,\"VOLM\" 100;font-size:1.05em;padding-top:.2em;}\ndd{padding-left:1em}\n\n@media print{html{font-size:13px;}\npre{page-break-inside:avoid;word-wrap:break-word;}\n}\nsub{font-size:0.75em;vertical-align:0.0em}\nsup{font-size:0.75em;vertical-align:0.3em}\nblockquote{padding:0 0 0 1rem;display:grid;grid-template-columns:100%;grid-gap:0;color:#444;}\nblockquote{border-left:0.5rem solid #00AA00;border-radius:0 0.3rem 0.3rem 0;}\nblockquote blockquote{margin:-0.3rem -0.3rem -0.3rem -1.55rem;border-left:0.6rem solid #FFBB00;}\nblockquote blockquote blockquote{margin:-0.3rem -0.3rem -0.3rem -1.6rem;border-left:0.7rem solid #DD0000;}\nblockquote ul,blockquoteol{padding-left:2rem;}\nblockquote ul>ul,blockquote ol>ol,blockquote ol>ul,blockquote ul>ol{border-left:none;}\nblockquote table{display:block;padding:1em;width:100%;border-bottom:none;}\nblockquote tbody{border-bottom:1px solid #336699;}\ntable{margin:0 0 0.3em 0;padding:0;border-bottom:1px solid #336699;border-collapse:collapse;width:100%;}\nth,td{padding:0.3em;}\nth{background-color:#336699;color:#fdfdfd;;border:1px solid #336699;}\ntr td{border-left:1px solid #336699;border-right:1px solid #336699;}\ntr:nth-child(odd){background-color:#D1E8FF;}\ntd{vertical-align:top;}\np:first{font-weight:bold}\n"
}
```
**identifier**: `preview-styling`
**version**: `0.0.5`
**minAppVersion**: `20.6.0`

### Script `Export notes as one HTML file`

**id**: `3`
**path**: `C:\Users\xxxx\AppData\Roaming\PBE\QOwnNotes\scripts\export-notes-as-one-html\export-notes-as-one-html.qml`
**variablesJson**: *empty*
**identifier**: `export-notes-as-one-html`
**version**: `1.0.0`
**minAppVersion**: `18.03.7`

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**CloudConnection-1/nextcloudDeckBoardId** (int): `1`
**CloudConnection-1/nextcloudDeckEnabled** (QString): `false`
**CloudConnection-1/nextcloudDeckStackId** (int): `1`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `false`
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**DistractionFreeMode/editorWidthCustom** (int): `64`
**DistractionFreeMode/editorWidthMode** (int): `1`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (int): `36`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6d7d03f9-ffac-4e75-a57b-847fd4871eac`
**Editor/autoBracketClosing** (bool): `false`
**Editor/autoBracketRemoval** (bool): `false`
**Editor/centerCursor** (bool): `true`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `false`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (int): `4`
**Editor/removeTrailingSpaces** (bool): `true`
**Editor/showLineNumbers** (bool): `false`
**Editor/useTabIndent** (bool): `true`
**Editor/vimMode** (bool): `false`
**FileDialog/LastPath** (QString): `D:/temp`
**FileDialog/LastPath-Joplin Import** (QString): `F:/Joplin`
**FileDialog/LastPath-NotePDFExport** (QString): `D:/temp`
**FileDialog/LastPath-PreviewHTMLFileExport** (QString): `D:/temp`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**JoplinImport/AttachmentImportCheckBoxChecked** (QString): `true`
**JoplinImport/FolderImportCheckBoxChecked** (QString): `true`
**JoplinImport/ImageImportCheckBoxChecked** (QString): `true`
**JoplinImport/MetadataImportCheckBoxChecked** (QString): `false`
**JoplinImport/TagImportCheckBoxChecked** (QString): `true`
**JoplinImportDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2024-11-03T08:34:39.696`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `30`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Entwicklung/Screenshot, Artikel, Notizen, Zu Hause, Bücher`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,20,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Droid Sans,19,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Courier New,12,-1,5,50,0,0,0,0,0,Standard`
**MainWindow/noteTextView.font** (QString): `Commissioner Flair,12,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.refreshDebounceTime** (int): `1000`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `false`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**MessageBoxOverride/windows-light-mode** (int): `65536`
**NoteBookmark1** (NoteHistoryItem): `<binary data>`
**NoteBookmark2** (NoteHistoryItem): `<binary data>`
**NoteBookmark6** (NoteHistoryItem): `<binary data>`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteDialog/tabWidgetIndex** (int): `0`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QStringList): `Autohotkey destroyed`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteHistory-1** (QVariantList): `<variant list with 161 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `160`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExportOrientation** (int): `0`
**Printer/NotePDFExportPageSize** (int): `4`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-actionFind_action** (QKeySequence): *empty*
**Shortcuts/MainWindow-actionInsert_text_link** (QKeySequence): *empty*
**Shortcuts/MainWindow-action_Open_note_in_external_editor** (QKeySequence): `Alt+X`
**Shortcuts/MainWindow-customAction_exportHTML** (QKeySequence): *empty*
**ShowSystemTray** (bool): `false`
**StartHidden** (bool): `false`
**StoredImagesDialog/geometry** (QByteArray): `<binary data>`
**TableDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (int): `0`
**TodoDialog/showDueTodayItemsOnly** (int): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Deck: Persönlich`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**ai/groq/apiKey** (QString): `<hidden>`
**ai/openai/apiKey** (QString): `<hidden>`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/disableAppHeartbeat** (bool): `true`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (QString): `true`
**autoReadOnlyMode** (bool): `false`
**autoReadOnlyModeTimeout** (int): `30`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `2`
**darkMode** (bool): `true`
**darkModeColors** (bool): `true`
**darkModeIconTheme** (bool): `true`
**darkModeTrayIcon** (bool): `true`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (bool): `false`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**enableWebAppSupport** (bool): `false`
**externalEditorPath** (QString): `C:\Program Files\Typora\Typora.exe`
**fullyHighlightedBlockquotes** (bool): `true`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `false`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (int): `1024`
**imageScaleDownMaximumWidth** (int): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): `dd.MM.yyyy hh:mm`
**interfaceFontSize** (int): `22`
**interfaceLanguage** (QString): *empty*
**interfaceStyle** (QString): `Windows`
**internalIconTheme** (bool): `true`
**itemHeight** (int): `34`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (bool): `true`
**maxNoteFileSize** (int): `1048576`
**navigationPanelAutoSelect** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (int): `60`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (int): `1`
**noteSubfoldersPanelTabsUnsetAllNotesSelection** (bool): `false`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `0`
**notesPath** (QString): `C:/Tools/Notizen/NC-Sync`
**notifyAllExternalModifications** (bool): `true`
**overrideInterfaceFontSize** (bool): `true`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `040be292-ff43-43b4-a234-58ed527afa85`
**recentNoteFolders** (QStringList): `C:/Tools/Notizen`
**restoreCursorPosition** (bool): `true`
**restoreLastNoteAtStartup** (bool): `true`
**restoreNoteTabs** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2024-11-03T07.58.22, Note 2024-11-02T14.11.25, Note 2024-11-02T08.47.37, duckduck, Note 2024-11-02T07.38.12, Note 2024-10-30T10.03.41, Note 2024-10-29T14.30.24, QOwnnotes einrichten, Note 2024-10-29T06.57.17, Note 2024-10-28T13.56.28, Note 2024-10-28T10.59.55, Note 2024-10-28T06.45.39, Note 2024-10-27T17.38.06, Note 2024-10-27T15.49.39, OffSiteEdit`
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**showStatusBarNotePath** (bool): `true`
**showStatusBarRelativeNotePath** (bool): `false`
**spellCheckLanguage** (QString): `auto`
**startInReadOnlyMode** (bool): `false`
**systemIconTheme** (bool): `false`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideNoteCount** (bool): `false`
**tagsPanelHideSearch** (bool): `true`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (bool): `false`
**toolbar/1/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/1/name** (QString): `formattingToolbar`
**toolbar/1/title** (QString): `Formatierungs-Werkzeugleiste`
**toolbar/2/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/2/name** (QString): `insertingToolbar`
**toolbar/2/title** (QString): `Einfügen-Werkzeugleiste`
**toolbar/3/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/3/name** (QString): `encryptionToolbar`
**toolbar/3/title** (QString): `Verschlüsselung-Werkzeugleiste`
**toolbar/4/items** (QStringList): *empty*
**toolbar/4/name** (QString): `aiToolbar`
**toolbar/4/title** (QString): `KI-Toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `Fenster-Werkzeugleiste`
**toolbar/6/items** (QStringList): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `Beenden - Symbolleiste`
**toolbar/7/items** (QStringList): `action_Quit`
**toolbar/7/name** (QString): `quitToolbar`
**toolbar/7/title** (QString): `Beenden - Symbolleiste`
**toolbar/size** (int): `7`
**useNoteFolderButtons** (bool): `false`
**useSoftWrapInNoteEditor** (QString): `true`
**useUNIXNewline** (bool): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): *empty*
**webSocketServerService/bookmarksTag** (QString): `Browsernotiz`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (int): `22222`
**workspace-040be292-ff43-43b4-a234-58ed527afa85/name** (QString): `- Vorschau`
**workspace-040be292-ff43-43b4-a234-58ed527afa85/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-040be292-ff43-43b4-a234-58ed527afa85/windowState** (QByteArray): `<binary data>`
**workspace-a15eded2-68e5-4887-911a-433fc724d616/name** (QString): `- Editor`
**workspace-a15eded2-68e5-4887-911a-433fc724d616/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-a15eded2-68e5-4887-911a-433fc724d616/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `+ Vorschau`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, 040be292-ff43-43b4-a234-58ed527afa85, a15eded2-68e5-4887-911a-433fc724d616`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\xxxx\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `xxxx21`
**ComSpec**: `C:\windows\system32\cmd.exe`
**configsetroot**: `C:\windows\ConfigSetRoot`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\xxxx`
**LOCALAPPDATA**: `C:\Users\xxxx\AppData\Local`
**LOGONSERVER**: `\\xxxx21`
**NUMBER_OF_PROCESSORS**: `16`
**OneDrive**: `C:\Users\xxxx\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Embarcadero\Studio\23.0\bin;C:\Program Files (x86)\Embarcadero\Studio\23.0\bin64;C:\Entwicklung\Studio\23.0\bin;C:\Entwicklung\Studio\23.0\bin64;C:\Entwicklung\Embarcadero\Studio\23.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\23.0\Bpl;C:\Entwicklung\Embarcadero\Studio\23.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\23.0\Bpl\Win64;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files\AdoptOpenJDK\jdk-8.0.242.08-hotspot\bin;C:\Entwicklung\Studio\22.0\bin;C:\Entwicklung\Studio\22.0\bin64;C:\Program Files (x86)\Embarcadero\Studio\22.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\22.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\22.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\22.0\Bpl\Win64;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Entwicklung\Windows\Kits\10\Windows Performance Toolkit\;C:\Entwicklung\Git\cmd;C:\PHP8;C:\Program Files\WireGuard\;C:\texlive\2023\bin\windows;C:\Program Files\Wondershare\Wondershare DemoCreator (Deutsch);C:\Program Files\Wondershare\Wondershare DemoCreator (Deutsch);C:\Program Files\Wondershare\Wondershare DemoCreator (Deutsch);C:\Program Files\NVIDIA Corporation\NVIDIA app\NvDLISR;C:\Users\xxxx\AppData\Local\Microsoft\WindowsApps;;C:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\xxxx\AppData\Local\Pandoc\`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 167 Stepping 1, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `a701`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\windows`
**TEMP**: `C:\Users\xxxx\AppData\Local\Temp`
**TMP**: `C:\Users\xxxx\AppData\Local\Temp`
**USERDOMAIN**: `xxxx21`
**USERDOMAIN_ROAMINGPROFILE**: `xxxx21`
**USERNAME**: `xxxx`
**USERPROFILE**: `C:\Users\xxxx`
**windir**: `C:\windows`
**ZES_ENABLE_SYSMAN**: `1`
**ZKA_SIG_HOME**: `C:\Program Files (x86)\REINER SCT\cyberJack`
</details>

**Comment by BsNoSi** [comment]
Autohotkey uses for the basic shortcuts "sendkey" to the keyboard buffer. I can also use the clipboard for pasting, but defining shortcuts to use the clipboard needs higher efforts.

Additionally, Autohotkey allows coding complex operations, which I am using, too.

Espanso is new to me (thanks for hint). I will take a look, as soon as I have an impression, I will give feedback, if it might be a "workaround" for me.

**Comment by pbek** [comment]
> Could you be so kind, trying this with Espanso:

For me, espanso replaces it to `😉`.

**Comment by BsNoSi** [comment]
🤔 This is interesting. But, while typing my reply, I have an idea. ⏳

**Comment by BsNoSi** [comment]
Because it is obviously no QOwnNotes issue → cloesd.
