### ISSUE TITLE
SSL Handshake failed

### ISSUE THREAD

**Issue by marohds** [pbek/QOwnNotes#315]
Cannot connect with self signed SSL certificate.
The error "SSL Handshake failed". 
¿Is there anyway to bypass this error by accepting this SSL Certificate?
Thanks!

**Comment by pbek** [comment]
Take a look at the network settings. There is a checkbox to ignore SSL errors.

**Comment by pbek** [comment]
But I'd rather get a certificate at <https://letsencrypt.org/>.

**Comment by marohds** [comment]
Got a new certificate with letsencrypt.org and all went ok!

Thanks

**Comment by pbek** [comment]
Great! ;)
