### ISSUE TITLE
[SUPPORT]  QT6 still via PPA or is the main repo now qt6?

### ISSUE THREAD

**Issue by RussH** [pbek/QOwnNotes#3151]
#### Question
Hi, the documentation still points *buntu users (I'm on KDE Neon testing ) to a seperate ppa to install;
https://www.qownnotes.org/installation/ubuntu.html

but my Neon qt6 packages are too new and installation fails. Is the main repo now the qt6 repository?

**Comment by pbek** [comment]
The main ppa is qt5. Which repo did you use?

**Comment by RussH** [comment]
you're right, should have included all the info;

I tried ppa:pbek/qownnotes-qt6, but it's failing on Neon testing with;

> The following packages have unmet dependencies:
>  qownnotes : Depends: qt6-websockets-abi (= 6.4.2) which is a virtual package, provided by:
>                       - libqt6websockets6 (6.4.2-3build2) provides qt6-websockets-abi=6.4.2, but 6.8.0-0zneon+24.04+noble+stable+build7 is installed

I assume it's a packaging issue in the deb, as v6.8.0 > 6.4.2, but the package is specifically looking for  6.4.2 version of qt6-websockets-abi.

**Comment by pbek** [comment]
Seems like KDE Neon deviated a lot from Ubuntu LTS with Qt6. I was daily driving KDE Neon for a long time, but switched to NixOS two years ago.

The packages from the Qt6 PPA is built with those files: https://github.com/pbek/QOwnNotes/blob/aa4e595933b3f50e0b7f5ddb6c41e70febe07d27/ubuntu-launchpad/qt6

Launchpad decides the Qt6 version of the respective Ubuntu distribution version. ️🤷🏻
