### ISSUE TITLE
[BUG] Incorrect spelling of Portuguese languages in the "Manage dictionaries" menu.

### ISSUE THREAD

**Issue by camemb3rt** [pbek/QOwnNotes#3152]
#### Expected behaviour
Language names should be spelt correctly in the "Manage dictionaries" menu.

#### Actual behaviour
Portuguese and Portuguese (Brazilian) are spelt "Portugese"  in the "Manage dictionaries" menu.

#### Screenshots
![image](https://github.com/user-attachments/assets/e7bfde54-881f-44e5-ae20-23dc250ba80c)

**Comment by pbek** [comment]
Oh, thank you very much!

**Comment by pbek** [comment]
I wonder why nobody saw that. 😊
Will be fixed in the next release.

**Comment by pbek** [comment]
If you also want to help translating the application to those two languages, https://crowdin.com/project/qownnotes is fun to use. 😉

**Comment by camemb3rt** [comment]
I'll definitely look into it. 
Thanks.
