### ISSUE TITLE
[Q] Shortcut “Find everywhere”?

### ISSUE THREAD

**Issue by BsNoSi** [pbek/QOwnNotes#3154]
#### General question

Menu → Note → Fine notes in all tags/subfolders does exactly, what it says: It searches _the folder I am in_.

I am missing a shortcut for »Find notes everywhere« regardless of the current position.

Which is different to (required two actions) “select All notes” → “Find notes in all tags/subfolders”: It does not create an empty note in the current folder, it only returns “no match”, if so. 

“No match” does not imply (for me), that it requires creation of a note named with the searched words. First hand it only says, that for these word(s) there is no match anywhere.

»Search everywhere« is my primarily requirement of finding information in my notes. Despite all the advantages, which is why I switched from Joplin to QOwnNotes, finding notes “anywhere” was “intuitive” in Joplin (except chosen shortcut `STRG` `P`, that lists all notes with hits in a dropdown).  

I am currently creating a lot of meaningless empty notes in folders that have no connection to the search, because I am used to `Enter` a string…

**Comment by pbek** [comment]
`Find notes in all tags/subfolders` should search text in all notes, regardless of tag or subfolders. Does it not for you?

**Comment by BsNoSi** [comment]
At least with the options I have discovered so far, it doesn't work. I tried to describe it in a short video:

https://github.com/user-attachments/assets/50ed2014-d15e-4151-97e3-88c6aded29df

**Comment by pbek** [comment]
So the searching in "All notes" work. And what was the issue? 😁
There even is a shortcut for that, `Alt + F`.

![image](https://github.com/user-attachments/assets/49dd9cf0-5f3b-476c-95af-579b1887f376)

**Comment by BsNoSi** [comment]
`Alt` `F` opens the `Fenster` menu in German interface. I know, I can change the shortcut, but:
Choosing "Find notes in all tags/subfolders" from the menu sets the input cursor into the field, as I use in the video, with the same result as in the video. → Result depends on current position inside the folder tree.

**Comment by pbek** [comment]
No it's not the same. The action also selects "All notes" in the tag and sub-folder panel.

**Comment by BsNoSi** [comment]
A VERY slightly detail: Using this, in my folder list is no selection. I interpreted this as "no change". I changed some shortcuts to make it suitable to the German interface (ALT STRG F , Note search ALT STRG SHIFT F).

Thank you VERY helpful hint.
