### ISSUE TITLE
[BUG]  Path to Git Reverts to Something Different on App Restart

### ISSUE THREAD

**Issue by pa-0** [pbek/QOwnNotes#3156]
Everytime I start QownNotes, I check the Git Versioning menu in Settings, and find that the path has changes from what I initially selected (Git's default installation path) to the following:

```
C:/Users/<MY-USERNAME>/portable/QOwnNotes/Data/../../../../../Program Files/Git/cmd/git.exe
```

Not sure if this is by design.

```
QownNotes version:   latest version in Portable Mode
OS Version:          Windows 11 Enterprise 64-bit
Build number:        22631.4317
```

Also, (let me know if you'd like me to create a separate issue for this), so far I've updated QownNotes maybe 3 times) and each version had the same performance issues.  Whether in the Settings menu, or just in the editor typing, it seems like some looping process causes the app to hang.  I assume it's a looping process, because it happens consistently in intervals that are spread apart evenly (or at least feel as though they are).

I'm using an intel i7 with i believe 32GB of RAM, so this definitely is not something I experience across all apps.  Even bloated electron apps run fine, so I'm surprised this is an issue with something as lightweight as Q. I'm hoping it's not an issue with Defender (this is a corporate laptop).

**Comment by pbek** [comment]
> Everytime I start QownNotes, I check the Git Versioning menu in Settings, and find that the path has changes from what I initially selected (Git's default installation path) to the following:

You haven't provided any information about your system (see issue template).
It looks like you are in portable mode, have you tried if you also have the issue without portable mode?

> Whether in the Settings menu, or just in the editor typing, it seems like some looping process causes the app to hang.

Can you please open a different issue, providing the full information of the issue template? 😉
