### ISSUE TITLE
[BUG] Note edit panel view restoring

### ISSUE THREAD

**Issue by polovik** [pbek/QOwnNotes#3157]
#### Expected behaviour
"Note preview" (or "Note edit") panel remembers its width after the application restart.

#### Actual behaviour
After upgrading Ubuntu distribution from 22.04 to 24.04 I faced with incorrect restoring view (especially width) of Note preview/edit panel.
I cleared settings, but this didn't help.
Before Ubuntu upgrading I had a problem with incorrect restoring view (height) of Note list and Navigation panels. But now their heights are restored correctly.

#### Steps to reproduce
1. Set desired width of Note edit panel
2. Close QOwnNotes
3. Open QOwnNotes
4. "Note edit" panel width has been reduced
5. After several restarts "Note edit" panel width becomes about half of display horizontal resolution.

#### Screenshots

The application view before closing:
![Screenshot from 2024-11-14 12-05-36](https://github.com/user-attachments/assets/ba5c782b-9f33-4123-a6df-c63f420bca56)

The application view after first restart:
![Screenshot from 2024-11-14 12-05-49](https://github.com/user-attachments/assets/41a334da-dfd3-4ddd-9a76-37d632661d9e)

The application view after second restart:
![Screenshot from 2024-11-14 12-05-59](https://github.com/user-attachments/assets/dd566830-74cc-4d07-b584-4f5e5b9f1fc5)

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Thu Nov 14 12:13:35 2024`
**Version**: `24.11.2`
**Build date**: `Nov 13 2024`
**Build number**: `1139`
**Platform**: `linux (xcb)`
**Operating System**: `Ubuntu 24.04.1 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.15.13`
**Qt Version (runtime)**: `5.15.13`
**Portable mode**: `no`
**Settings path / key**: `/home/polovik/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/polovik/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `63`
**Calendar items**: `0`
**Enabled scripts**: `0`
**Database drivers**: `QSQLITE, QODBC, QODBC3`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_AU, en_CA, en_GB, en_US, en_ZA, ru_RU, sr_Latn_RS, sr_ME, sr_RS`
**Language names**: `Australian English (Australia), Canadian English (Canada), British English (United Kingdom), American English (United States), English (South Africa), русский (Россия), srpski (Srbija), srpski (Crna Gora), српски (Србија)`
**Application dictionaries path**: `/home/polovik/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/polovik/mega/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/polovik/mega/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging**: *empty*
**DistractionFreeMode/editorWidthCustom** (QString): `200`
**DistractionFreeMode/editorWidthMode** (QString): `3`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `27`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `/home/polovik/mega/Notes/work`
**FileDialog/LastPath-ImportTextFiles** (QString): `/home/polovik/mega/Notes/work`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2024-11-14T12:12:57.961`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `30`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `DejaVu Sans Mono,18,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Ubuntu Sans,18,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Ubuntu Sans,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (QString): `600`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `false`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**NoteFolder-1/NoteTabNameList** (QString): `Welcome to QOwnNotes`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QString): *empty*
**NoteHistory-1** (QVariantList): `<variant list with 21 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `20`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**ai/groq/apiKey** (QString): `<hidden>`
**ai/openai/apiKey** (QString): `<hidden>`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**autoReadOnlyMode** (QString): `false`
**autoReadOnlyModeTimeout** (QString): `30`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `preview-only`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `22`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**maxNoteFileSize** (QString): `1033216`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `false`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `false`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `false`
**noteSubfoldersPanelSort** (QString): `0`
**noteSubfoldersPanelTabsUnsetAllNotesSelection** (QString): `false`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/polovik/mega/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `vicenza SNMP, PE-3404 Berg Hortimotive, Matlab, io-link porting to STM32, gitlab - CI, docker, Code style, elvas - Lubrication, meetup - elvas, newport`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**showStatusBarNotePath** (QString): `true`
**showStatusBarRelativeNotePath** (QString): `false`
**spellCheckLanguage** (QString): `auto`
**startInReadOnlyMode** (QString): `false`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/1/name** (QString): `formattingToolbar`
**toolbar/1/title** (QString): `formatting toolbar`
**toolbar/2/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/2/name** (QString): `insertingToolbar`
**toolbar/2/title** (QString): `inserting toolbar`
**toolbar/3/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/3/name** (QString): `encryptionToolbar`
**toolbar/3/title** (QString): `encryption toolbar`
**toolbar/4/items** (QStringList): `actionEnable_AI, actionAiBackendComboBox, actionAiModelComboBox`
**toolbar/4/name** (QString): `aiToolbar`
**toolbar/4/title** (QString): `AI toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/7/items** (QString): `action_Quit`
**toolbar/7/name** (QString): `quitToolbar`
**toolbar/7/title** (QString): `quit toolbar`
**toolbar/size** (QString): `7`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Preview only`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**SHELL**: `/bin/bash`
**SESSION_MANAGER**: `local/PolovikHP:@/tmp/.ICE-unix/3601,unix/PolovikHP:/tmp/.ICE-unix/3601`
**QT_ACCESSIBILITY**: `1`
**COLORTERM**: `truecolor`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-ubuntu:/etc/xdg`
**NVM_INC**: `/home/polovik/.nvm/versions/node/v16.20.2/include/node`
**HISTCONTROL**: `ignoreboth`
**XDG_MENU_PREFIX**: `gnome-`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**LC_ADDRESS**: `en_GB.UTF-8`
**GNOME_SHELL_SESSION_MODE**: `ubuntu`
**LC_NAME**: `en_GB.UTF-8`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**MEMORY_PRESSURE_WRITE**: `c29tZSAyMDAwMDAgMjAwMDAwMAA=`
**XMODIFIERS**: `@im=ibus`
**DESKTOP_SESSION**: `ubuntu`
**LC_MONETARY**: `en_GB.UTF-8`
**GTK_MODULES**: `gail:atk-bridge`
**PWD**: `/home/polovik`
**XDG_SESSION_DESKTOP**: `ubuntu`
**LOGNAME**: `polovik`
**XDG_SESSION_TYPE**: `x11`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**SYSTEMD_EXEC_PID**: `3644`
**MC_TMPDIR**: `/tmp/mc-polovik`
**XAUTHORITY**: `/run/user/1000/gdm/Xauthority`
**WINDOWPATH**: `2`
**MC_SID**: `8771`
**HOME**: `/home/polovik`
**USERNAME**: `polovik`
**IM_CONFIG_PHASE**: `1`
**LANG**: `en_US.UTF-8`
**LC_PAPER**: `en_GB.UTF-8`
**LS_COLORS**: `rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:*~=00;90:*#=00;90:*.bak=00;90:*.crdownload=00;90:*.dpkg-dist=00;90:*.dpkg-new=00;90:*.dpkg-old=00;90:*.dpkg-tmp=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:*.swp=00;90:*.tmp=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:`
**XDG_CURRENT_DESKTOP**: `ubuntu:GNOME`
**MEMORY_PRESSURE_WATCH**: `/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/session.slice/org.gnome.Shell@x11.service/memory.pressure`
**VTE_VERSION**: `7600`
**GNOME_TERMINAL_SCREEN**: `/org/gnome/Terminal/screen/a39275a8_0b31_472e_bd45_b63452f4f347`
**QTWEBENGINE_DICTIONARIES_PATH**: `/usr/share/hunspell-bdic/`
**STM32_PRG_PATH**: `/opt/STM32CubeProgrammer/bin`
**NVM_DIR**: `/home/polovik/.nvm`
**LESSCLOSE**: `/usr/bin/lesspipe %s %s`
**XDG_SESSION_CLASS**: `user`
**LC_IDENTIFICATION**: `en_GB.UTF-8`
**TERM**: `xterm-256color`
**LESSOPEN**: `| /usr/bin/lesspipe %s`
**USER**: `polovik`
**GNOME_TERMINAL_SERVICE**: `:1.130`
**DISPLAY**: `:1`
**SHLVL**: `2`
**NVM_CD_FLAGS**: *empty*
**GSM_SKIP_SSH_AGENT_WORKAROUND**: `true`
**LC_TELEPHONE**: `en_GB.UTF-8`
**QT_IM_MODULE**: `ibus`
**LC_MEASUREMENT**: `en_GB.UTF-8`
**PAPERSIZE**: `a4`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**DEBUGINFOD_URLS**: `https://debuginfod.ubuntu.com `
**LC_TIME**: `en_GB.UTF-8`
**XDG_DATA_DIRS**: `/usr/share/ubuntu:/usr/share/gnome:/home/polovik/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop`
**PATH**: `/home/polovik/.nvm/versions/node/v16.20.2/bin:/home/polovik/.cargo/bin:/home/polovik/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/polovik/bin`
**GDMSESSION**: `ubuntu`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**NVM_BIN**: `/home/polovik/.nvm/versions/node/v16.20.2/bin`
**LC_NUMERIC**: `en_GB.UTF-8`
**_**: `/usr/bin/QOwnNotes`

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

$ QOwnNotes
Info: "QOwnNotes server listening on port 22222" ((null):0, (null))
Warning: Missing trigrams for languages: QSet("en_AU", "sr_ME", "en_ZA", "en_CA") ((null):0, (null))
Warning: QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0 ((null):0, (null))

</details>

**Comment by pbek** [comment]
>  noteEditIsCentralWidget (QString): false

This is the way it works if there is no "central widget". Best turn it on again in the panels settings.

**Comment by polovik** [comment]
@pbek  Thank you a lot, it works!
