### ISSUE TITLE
[SUPPORT] Font color

### ISSUE THREAD

**Issue by DutchPete** [pbek/QOwnNotes#3160]
#### Question
I want to change the font color of the body text. In _Settings > Editor fonts and colors_  you can only choose a themed color schema, but the foreground and background colors on the right of that schema field are greyed out. Is there any way to access them?

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Copy the color schema and adapt the colors...

**Comment by DutchPete** [comment]
Thank you!
