### ISSUE TITLE
[SUPPORT] Using my synched MEGA set-up

### ISSUE THREAD

**Issue by DutchPete** [pbek/QOwnNotes#3162]
#### Question
I have pre-existing notes that I want to use in QON. Those notes are in a parent directory "MEGA", which synchs with the cloud @ mega.nz.

In QON's _Settings > Note folders_  I want to change the *Note folder path* to the MEGA folder on my computer. Is there any technical or other reason from a QON point of view that I should not do so?

**Comment by pbek** [comment]
> Is there any technical or other reason from a QON point of view that I should not do so?

No 😊

**Comment by DutchPete** [comment]
Thank you.
