### ISSUE TITLE
[SUPPORT] 

### ISSUE THREAD

**Issue by DutchPete** [pbek/QOwnNotes#3164]
#### Question
I have a note with a number of headings. When I edit that note, QON clones a new one from it, but with the name of the 1st header, and that cloned note becomes the active one. I cannot understand it because in the settings I have this one unchecked:

![image](https://github.com/user-attachments/assets/c4c32fba-6723-42e8-9ae7-97d00b7a8d8c)

What am I doing wrong?

Furthermore, when I tried to eliminate the cloned note from the notes list pane, OMG I accidentally deleted some of the real notes too!! I cannot locate them because they are not in my OS's rubbish bin. Please tell me if QON keeps a separate rubbish bin or if they are deleted for good.

**Comment by pbek** [comment]
Can you please describe what you expected, what the actual behavior was, and step by step what you did? Please provide an example Markdown text.

**Comment by DutchPete** [comment]
So, I have a number of notes and used the one at the bottom of the list:
![step0](https://github.com/user-attachments/assets/3bc12f4e-97d0-4402-b90b-a882eb265003)

The is what the edit pane looks like this:

![step1](https://github.com/user-attachments/assets/3c31f395-c1d1-4f31-b20f-e302bebc9b35)

The gap between 1.1 and 1.2 is not as big as it seems, I have pixelated the content on the screenshot.

Then I added 2 empty lines above 1.2:

![step2](https://github.com/user-attachments/assets/6840726d-f849-4b21-a188-c508c1ef8fdd)

And "1. STANDARD ACTIVITIES", a clone of the original, was added to the top of the list:

![step1a](https://github.com/user-attachments/assets/37ed0ad3-805a-4ade-88ae-182f3fd64c18)

Then I wanted to delete "1. STANDARD ACTIVITIES" from the list, so I hit the "Delete" key on my keyboard. But because the cursor, i.e. the focus, was still on the note content, the original note was deleted. I hit the "Delete" key a couple of times more before I realized my stupidity.

**Comment by pbek** [comment]
And what was the question now? 😁

**Comment by DutchPete** [comment]
The same 2 questions as before:

* how can I avoid that clone being made?
* where did my deleted originals disappear to, or rather, where can I recover them from?

**Comment by pbek** [comment]
Great it worked. 😉
