### ISSUE TITLE
[SUPPORT] Journal entry script

### ISSUE THREAD

**Issue by DutchPete** [pbek/QOwnNotes#3165]
#### Question
I installed the script, with this format `{YYYY-MM-DD}`. I would line this format, taking today's date as an example: `2024-11-26, Tue, wk48`. Is that format available or is a feature request needed for that?

**Comment by pbek** [comment]
Can you please open an issue on https://github.com/qownnotes/scripts/issues and mention the authors of the script? You will find the authors in the *Script repository*.
