### ISSUE TITLE
[BUG] Amended color schema for block quotes does not work

### ISSUE THREAD

**Issue by DutchPete** [pbek/QOwnNotes#3166]
#### Expected behaviour

I copied the Solarized Light color schema and amended the _Text preset_ to a dark blue. I set the block quote text color to orange. So, I would expect the body text to be dark blue, while a block quote text should be orange, in Preview mode too.

![image](https://github.com/user-attachments/assets/6cedbf2d-fde2-4006-829a-d624f0505008)

#### Actual behaviour

The block quote text is also dark blue in both modes.

![image](https://github.com/user-attachments/assets/4a8335df-3cc9-4dc2-afe3-3bc0e1edddcc)

In the screenshot the top arrow is regular text, the lower arrow is block quote text. The black text is bold text but is not relevant here.

Even if I uncheck the foreground color box for the _Text preset_, which means the body text becomes black (after relaunching QON), the block quote text also becomes black.

I also changed the font family and size for block quotes:

![image](https://github.com/user-attachments/assets/d86f8b44-6627-4f4b-93cf-d028fe397dd2)

![image](https://github.com/user-attachments/assets/366a424f-f49f-4ae1-9c5e-8e3ebf1bec68)

but in both Edit and Preview modes the text is unaffected:

![image](https://github.com/user-attachments/assets/c212e89b-afb2-4e6f-92f4-0afe333b5b08)

In Edit mode, an open checkbox is red, a closed one is green, as per the settings. In Preview mode, however, both are blue, although the closed one has a green tick.

OTOH, emphasized text does appear as grey in both modes, as per the settings. Both internal and external links appear  as light blue, as per the settings.

I have not checked other color settings to see if the bug affects them.

#### Steps to reproduce
1. Copy an existing color schema
2. Adjust the foreground color for _Text preset_ and *Block quote*
3. Relaunch QON

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

What part of that very long Debug output do you want me to post here?

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Works fine for me:

![image](https://github.com/user-attachments/assets/587d15c6-f37d-4ed4-bb08-4e1ad4222717)


Did you see this setting?

![image](https://github.com/user-attachments/assets/71473ad6-f836-4f51-91c7-316550e4c9c3)

**Comment by DutchPete** [comment]
Ahhh, I had not seen that. Checking the box means amending the block quote in terms of color, font family and font size works now. Thank you very much.

BTW, I amended the title  – added the words “block quotes” – to make it a real reflection of the issue.
