### ISSUE TITLE
[SUPPORT] Media folder = creation of duplicates, why?

### ISSUE THREAD

**Issue by DutchPete** [pbek/QOwnNotes#3167]
#### Question
Each time I add an image from my image folder, QON adds a copy to a media folder it created itself. I find it silly to have duplicates of images, or of any file for that matter.

Is there a way to force QON to use my images folder instead of an unasked for media folder?

**Comment by pbek** [comment]
> Is there a way to force QON to use my images folder instead of an unasked for media folder?

No

**Comment by DutchPete** [comment]
Thank you.
