### ISSUE TITLE
[FEATURE] only note preview as workspace

### ISSUE THREAD

**Issue by bluelupo** [pbek/QOwnNotes#3169]
Is it possible to implement a function in QOwnnotes that only displays the note preview in the workspace, without the note editor and without the navigation pane? There is a button on the toolbar that opens the note in another window, but I find this method inconvenient to see only the preview. It would be ideal for me if I could create a workspace that only contains the note preview. 

Greetings
Michael

**Comment by pbek** [comment]
![image](https://github.com/user-attachments/assets/e44ce21c-af81-4447-8285-42f4f40ce2fc)
