### ISSUE TITLE
Smartwatch app

### ISSUE THREAD

**Issue by L-R-S** [pbek/QOwnNotes#317]
Especially for Samsung Gear S :) I got one – can help testing/translating.

**Comment by pbek** [comment]
That would basically be an app that can read and write text files via WebDAV to an ownCloud server. There are no real bounds to QOwnNotes.
I don't think I will have the time to get into Samsung Gear development any time soon. If I really would have the time I would go for Ubuntu Touch first... Or even iOS and Android...
