### ISSUE TITLE
[BUG] AppImage Qt5 and Qt6 requires libfuse2 to be installed on clean Ubuntu 22.04 and 24.04 - Add to doc?

### ISSUE THREAD

**Issue by o-l-a-v** [pbek/QOwnNotes#3173]
I just tested both the Qt5 and the Qt6 AppImage from v24.12.1, but both fails with error:

```text
lopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
```

I found this error by running the AppImages with:

```bash
QT_DEBUG_PLUGINS=1 ./QOwnNotes-x86_64-Qt6.AppImage
```

In following issue:

* <https://github.com/AppImage/AppImageKit/issues/1225>

Which leeds to:

* <https://docs.appimage.org/user-guide/troubleshooting/fuse.html#the-appimage-tells-me-it-needs-fuse-to-run>

We learn that QOwnNotes AppImages requires libfuse2 to be installed.

After:

```bash
sudo apt install libfuse2
```

both AppImages starts.

---

This could maybe be added to the docs? If this is wanted and "Up for grabs" I can add a PR. 😊

* <https://github.com/pbek/QOwnNotes/blob/main/webpage/src/installation/appimage.md>

**Comment by pbek** [comment]
Yeah, maybe good to mention. I did so in https://github.com/pbek/QOwnNotes/commit/221960166d4b5bec81df26334f3e1c2dddca29e2. Thank you.
