### ISSUE TITLE
[SUPPORT] Simple question

### ISSUE THREAD

**Issue by DutchPete** [pbek/QOwnNotes#3176]
#### Question

Patrizio, I want to make a donation. I would like to make a direct payment via a bank transfer:
* transfers between EU banks are free
* the receiving party gets the money in their account within 1 working day
* the receiving party does not pay anything, unlike with a PayPal transaction.

Since, like me, you live in an EU country, could you give me a bank account number to make the transfer to? I need the IBAN and exact name of the account.

If you don't want to publish it here, you can email it to me: ngungu.chileshi@proton.me

**Comment by pbek** [comment]
Thank you very much. I sent you an email!

**Comment by DutchPete** [comment]
You did not give me the full, correct name of the account.

**Comment by pbek** [comment]
"Patrizio Bekerle", like shown on my profile or my email reply address. 😊

**Comment by DutchPete** [comment]
Donation made.
