### ISSUE TITLE
[FEATURE] Automatically auto-format markdown tables

### ISSUE THREAD

**Issue by DutchPete** [pbek/QOwnNotes#3177]
#### Is your feature request related to a problem? Please describe.

It is not really a problem, just an inefficiency.
As described in your [blog post](https://www.qownnotes.org/blog/2021-08-21-Auto-format-markdown-tables.html), to auto-format a table you have to hit <kbd>CTRL</kbd>+<kbd>Space</kbd>.

#### Describe the solution you'd like

Have QON auto-format automatically as soon as you edit a table?

#### Describe alternatives you've considered

None

**Comment by pbek** [comment]
> Have QON auto-format automatically as soon as you edit a table?

I don't like to modify the note text automatically while typing, QOwnNotes usually doesn't do that (unless someone writes or uses a script that does it).
And that operation possibly moves around the cursor.

**Comment by DutchPete** [comment]
If you look at VNote, it does it remarkably well.

But if you think it is not a good idea, then i'll continue with the manual method.

**Comment by pbek** [comment]
If QOwnNotes starts to do automatic destructive operation on the Markdown files, I'll come back to this.

**Comment by DutchPete** [comment]
What do you mean by " automatic destructive operation on the Markdown files"?
And why would QON suddenly start doing that?

**Comment by pbek** [comment]
"destructive" as in "operations on the text file that cause the change of the text in the text file".

**Comment by DutchPete** [comment]
VNote also supports code blocks but has implemented it.
Anyway, I shan't argue this any longer – I am no expert and you have your reasons. As it is, the manual method is not really a problem, so I can live with it 😀

**Comment by DutchPete** [comment]
See what you think about this ChatGPT proposal.

Since you'd like the automatic formatting of tables to happen without manual intervention and without affecting the body text or code blocks, we’ll aim for a solution that can continuously monitor and format tables in the background without requiring an extra key press. 

### Approach with Continuous Script (Automatic Table Formatting)

Although QOwnNotes doesn't have a built-in "auto-format after every edit" feature, we can try to build a script that continuously checks for table changes and formats them automatically. This solution can be set up to run periodically and only modify the table syntax, leaving the body text and code blocks untouched.

Here’s an example of how you might set this up in QOwnNotes using JavaScript to trigger a periodic table formatting function:

### Example Script:

1. **Basic Concept**: 
   - Use a JavaScript script to periodically check for changes in the note content.
   - When a table is found, format it (adjust column alignment and ensure proper Markdown syntax).
   - The script should avoid modifying non-table sections (body text, code blocks, etc.).

2. **Script Logic**:
   - Check the note's content for tables (Markdown-style tables).
   - Ignore sections marked as code blocks.
   - Format the table by aligning columns.
   - Reapply the formatted content back to the note.

Here’s a potential script:

```javascript
// Function to format tables in Markdown, leaving code blocks intact
function formatTableInMarkdown(content) {
    // Regular expression to identify a table (excluding code blocks)
    const tableRegex = /\n(?!```)(\|[^\n]+(\n\|[^\n]+)*\|)\n/g;
    
    // Format the table content by adjusting column alignment
    return content.replace(tableRegex, (match) => {
        let tableLines = match.split("\n").map(line => line.trim());
        
        // Align the columns
        let formattedLines = tableLines.map(line => {
            let columns = line.split('|').map(col => col.trim());
            return `| ${columns.join(' | ')} |`;  // Ensure consistent spacing around columns
        });
        
        // Join the formatted lines back together with newlines
        return formattedLines.join("\n");
    });
}

// Function to format content, leaving body text and code blocks unaffected
function formatNoteTables() {
    let note = app.getActiveNote();  // Get the current note
    let content = note.getContent();  // Get the current content

    // Apply table formatting (ignore code blocks)
    let formattedContent = formatTableInMarkdown(content);

    // Set the formatted content back into the note
    note.setContent(formattedContent);
}

// Set an interval to check for tables every few seconds and auto-format them
setInterval(() => {
    formatNoteTables();  // Run the table formatting function
}, 5000);  // Check every 5 seconds (adjust as necessary)
```

### Key Features of This Script:
1. **Avoids Code Blocks**: The regular expression (`/```/`) avoids formatting text inside code blocks. So it will not interfere with your code.
2. **Automatic Formatting**: This script runs every 5 seconds and automatically looks for tables to format. You can adjust the frequency (5000 ms = 5 seconds) as needed.
3. **Table Formatting**: It ensures that each table in the note is well-aligned with proper Markdown syntax. It formats tables consistently, aligning columns and making sure the pipe characters (`|`) are well-spaced.
4. **Body Text is Left Unchanged**: The script only focuses on Markdown tables, so the body text and other content (like headings or bullet points) remain untouched.

### How to Use:
1. Open the **Scripting Console** in QOwnNotes (via `Ctrl + Shift + P` and typing `Scripting Console`).
2. Paste the script into the console.
3. Start the script, and it will automatically begin running, periodically formatting tables without you needing to manually press any keys.

### Things to Note:
- **Performance**: Since the script runs every few seconds, if you have a very large document, it might have a small performance overhead. You can reduce the interval if needed, or limit the script to only run when you’re actively editing a note.
- **Customization**: This script assumes that all tables are in Markdown format. If you're using other formats, you may need to adjust the regular expression or parsing logic accordingly.

This approach should provide you with automatic table formatting without interfering with the rest of the content in your notes, similar to the behavior you mentioned in VNote. Let me know if you need further adjustments!

**Comment by pbek** [comment]
Have you tested your code in a script yet?

**Comment by DutchPete** [comment]
No, because I don't know how to do that.
With the other 2 pre-existing scripts it was easy because all I did was on my computer replace the original `.qml` files with the new one, close QON and relaunch it then test it.

With this one there is no pre-existing script.

**Comment by pbek** [comment]
See https://www.qownnotes.org/scripting/

![image](https://github.com/user-attachments/assets/cfefe9a0-828d-4fbe-b056-6725c6e0fd33)

**Comment by DutchPete** [comment]
I added the code in a text editor and saved in in my Downloads folder as `auto-format-tables`.
Then I added it as a local script, as per your instruction, but on the settings page in QON, it shows a comment in red: `There were script errors: file:///home/user1/Downloads/auto-format-tables.qml:9 Expected a qualified name id `.

What is meant by a “qualified name”?

**Comment by pbek** [comment]
Scripts need to look like this:

```js
import QtQml 2.0
import QOwnNotesTypes 1.0

Script {
    /**
     * Will be run when the scripting engine initializes
     */
    function init() {
        script.log("Hello world!");
    }
}
```

You could try putting everything in the `init` function.

**Comment by DutchPete** [comment]
I tried that and the code does not work. Meanwhile I tried variations on that code, but no luck.
So, I shall abandon this feature request and keep doing the adjustment manually.
