### ISSUE TITLE
[FEATURE] Embeds/transclusions

### ISSUE THREAD

**Issue by DutchPete** [pbek/QOwnNotes#3178]
#### Is your feature request related to a problem? Please describe.
A topic I address can consist of pieces of details spread over various notes.

#### Describe the solution you'd like
I like to be able to embed the spread out pieces all combined in 1 note to see the whole story.

#### Describe alternatives you've considered
The previous note-taking app I used was Obsidian, which has that feature. While Obsidian is an impressive app, I prefer the plainness combined with sophistication of QON. Furthermore, I cannot stand the moderators on Obsidian's Discord channel: they take their role so seriously to the point that they are on the border of being tyrannical, resulting in a toxic atmosphere.

**Comment by pbek** [comment]
I'm not sure I get what you were asking for. 🤔 Could you please provide more context? 

You can link to other notes and you can show back links to notes.

You can also tag notes.

**Comment by pbek** [comment]
There is nothing in Markdown that supports that. 🤔

But you can implement whatever you want in the preview with the help of https://www.qownnotes.org/scripting/hooks.html#notetomarkdownhtmlhook and e.g. https://www.qownnotes.org/scripting/methods-and-objects.html#fetching-a-note-by-its-file-name.

**Comment by DutchPete** [comment]
> There is nothing in Markdown that supports that. 🤔

Obsidian, Logseq, Roam Research and other markdown apps support it. I don't know enough about how they do it, but from your comment I gather they must have gone off the markdown track.

If you prefer to stay on the markdown track, no problem, I understand.

**Comment by pbek** [comment]
Like I said above, with the scripting engine it's not very hard to just load a note by e.g. name that you write into the markdown with any syntax you like and then show it in the preview.

**Comment by DutchPete** [comment]
I am not really interested in loading a note, what  want is to show a paragraph from another note. I don't know if you know what I mean.

**Comment by pbek** [comment]
> Let's say I also have note2 that consists of 5 paragraphs, and the text of paragraph 4 I want to be shown in note1, just like you do with the image.

What did you want to show then?

**Comment by DutchPete** [comment]
Just like it says in your quote: I want the text of a paragraph that is in note2 to be shown in note1.
The same way you show in a note an image that is in an image folder. The image stays in the image folder, but is projected, as it were, in the note.

So, the paragraph from note2 stays in note2, but it is projected in note1. If I want make a change in the paragraph, I go to note2, make the change, and it will show up in the projection (i.e. the embed) in note1.

What I am asking is not unusual as a number of major note-taking apps support it.

The advantage is that you can combine parts of text from different notes into a new note. And those parts can be used as many times as one likes in different notes. Furthermore, any change to the original paragraph will be shown in all the projection (= embeds/transclusions) of that paragraph.

**Comment by pbek** [comment]
> What I am asking is not unusual as a number of major note-taking apps support it.

I've never seen that anywhere integrated in Markdown. Do you have some documentation links or similar?

What I hear you saying is, you want to show part of a note in another note, right? So you need to load note2 in note1 and filter some text out of note2 to show it somewhere in note1 in the preview, right? And maybe also show a link to that paragraph of note2. 

All that could be done with the scripting engine.

**Comment by DutchPete** [comment]
> What I hear you saying is, you want to show part of a note in another note, right?

Correct.

> So you need to load note2 in note1 and filter some text out of note2 to show it somewhere in note1 in the preview, right?

I don't think that is how it works. The way it is done in Obsidian is that a 6-character alphanumeric code prepended with a `^` is assigned to the paragraph when the user wants to embed it, in my example in note2.

Then in note1 the user links to the code assigned to paragraph in note2, which is prepended with a `!`, just like for an image.

So, the link syntax in note1 is `![any-name](path/to/note2#^123abc)`. In other words, the 6-character code is referred to as if it is a heading. I don't know what the function of the `^` is.

**Comment by pbek** [comment]
Where does this 6-character alphanumeric code come from? Does Obsidian keep a database of all those, along with the notes?

> So, the link syntax in note1 is `![any-name](path/to/note2#^123abc)`. In other words, the 6-character code is referred to as if it is a heading. I don't know what the function of the ^ is.

You could still parse the `![any-name](path/to/note2#^123abc)` and replace it with some other text from the reference in the script. ️🤷🏻  People are already parsing a lot of special syntax already in the script repository.

**Comment by DutchPete** [comment]
The 6-character code is generated when the user clicks to start an embed; there is no pre-existing database. A user can even manually make up a 6-char code themselves, as long as it is unique within the vault  – that is Obsidian's term for what is called the note folder in QON. Each vault the user has unique 6-char codes.

This is the right-click context menu. In this example I right-clicked in note2:
![image](https://github.com/user-attachments/assets/c7bfa1a2-a5ce-457b-bef8-0ab9ee01a563)

to embed this paragraph in note1:
![image](https://github.com/user-attachments/assets/3ccb282d-e11d-4206-afdd-e37bf8db7195)

After clicking on "Copy block embed", a 6-char code is generated by Obsidian in note2:
![image](https://github.com/user-attachments/assets/6363b469-dddf-4ce0-8d3c-56f7d64de833)
in this case `^3803ka`. This would also have happened if I would have clicked on "Copy link to block".

That block of text is embedded in note1:
![image](https://github.com/user-attachments/assets/e21e1123-333b-4da0-8e0e-22a222a6a3ff)
Note: `![](<../Pasted image 20241212130735.png>)` is hidden in Obsidian's Live Preview.

The text of that block can only be amended in note2.

This is an explanation of what is described on Obsidian's [help page](https://help.obsidian.md/Linking+notes+and+files/Embed+files). My explanation is limited by my lack of coding knowledge.

You state:
> You could still parse the `![any-name](path/to/note2#^123abc)` and replace it with some other text from the reference in the script. ️🤷🏻 People are already parsing a lot of special syntax already in the script repository.

Like I mentioned before in another thread, I don't know anything about coding, nor about parsing. So, perhaps it is best to leave it at that, I'll live without embeds. Perhaps 1 day someone else will feel the need to embed and write a script that they might publish, in which case I'll be able to use it.

**Comment by pbek** [comment]
Thank you for the explanation.
Yes, it seems they are storing the 6-character code in a database along with the text of the note. That is something QOwnNotes doesn't do that. The only reference are the actual Markdown files themselves. That way you can work on your notes with every application you like all the time and there is no "vendor lock-in".

**Comment by DutchPete** [comment]
Yes, of course the 6-char codes are stored **after** they are generated, not beforehand, which is what I thought you meant.

> That is something QOwnNotes doesn't do that. 

OK, good to have cleared that up. So, if you agree we can now close this feature request.

**Comment by pbek** [comment]
Yes 😁
But scripting is an option! 😉

**Comment by DutchPete** [comment]
I know scripting is an option but only for those who know how to script.
Cheers.

**Comment by DutchPete** [comment]
Like I mentioned to you before, I don't have the time to learn, and, TBH, I don't have the inclination to learn, I have never been a computer/software nerd. To me both are tools to be used  – I don't want to have to be a mechanic to be able to drive a car. I buy a new car, have it serviced, fill it up with gasoline and have the tyres checked, but I never look under the hood.
