### ISSUE TITLE
[FEATURE] Ignoring absent Note-Folders

### ISSUE THREAD

**Issue by Tearony** [pbek/QOwnNotes#3179]
Instead of prompting you to select another folder, the active notes folder should just switch to the next existing folder.

Alternative: give a warning "folder not available, switch to..."

**Comment by pbek** [comment]
A little more context, please. 😉

Can you please describe what you expected, what the actual behavior was, and step by step what you did?

**Comment by Tearony** [comment]
I am using VeraCrypt and have a notefolder in an encrypted Volume. If the last selected Folder is not found, I am asked to select an alternative Folder and i cannot open the program and use another folder without selecting.

What I did:
1. Use a Notefolder, that is on a VeraCrypt Volume
2. close QOwnNotes (not changing the notefolder)
3. disconnect VeraCrypt Volume
4. Open QOwnNotes

What I get:
![grafik](https://github.com/user-attachments/assets/d1a67f50-8ba8-4852-b24c-607377a3a91d)
(Path to note folder is black)

If I press No / Nein, QOwnNotes closes
If I press Yes I can change the notefolder

What I would like to get:
Either just a warning and then being able to use another notefolder
Or just by default (if the folder isn't found) going to a specific notefolder

**Comment by pbek** [comment]
So you have multiple note folders? (You never shared the settings dump, like advised in the issue template.)

**Comment by pbek** [comment]
It's a bit tricky, because the note folder references are stored in a database and that check is done even before those tables are loaded... 🤔

**Comment by pbek** [comment]
## 24.12.3
- If the current note folder doesn't exist anymore during the start of the
  application, now the first existing one will be selected (for [#3179](https://github.com/pbek/QOwnNotes/issues/3179))
  - If there was only one note folder, the user needs to select a new path
  - When the application is already running and a note folder was removed outside
    the application, the user will now get a warning that the path doesn't exist
    anymore and is not able to select that note folder

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Tearony** [comment]
Downloaded it and it worked so far,

What I tried:
Using my existing notes-folder that is in a VeraCrypt Container, closing QOwnNotes, disconnecting the container and reopening QOwnNotes
Also tried creating a new folder on an external USB device (I know it shouldn't be different) and it worked to

Thats what I was searching for, thank you very much

**Comment by pbek** [comment]
Great it works! 😊

**Comment by pbek** [comment]
## 24.12.4
- The welcome wizard will now be shown again when the application runs for the first time,
  this was a regression from 24.12.3 (for [#3179](https://github.com/pbek/QOwnNotes/issues/3179))
