### ISSUE TITLE
[SUPPORT] Custom CSS

### ISSUE THREAD

**Issue by DutchPete** [pbek/QOwnNotes#3182]
#### Question
I want to reduce the font size in table: is there a way to add custom CSS to QOwnNotes?

**Comment by pbek** [comment]
Yes, there is. Search for `styling` in the script repository.

**Comment by DutchPete** [comment]
I am sorry, I don't see it. Here are the 2 styling option pages:

**Interface**
![image](https://github.com/user-attachments/assets/f8146979-544a-41a2-801e-6a3d3dc3dfdf)

and

**Preview**
![image](https://github.com/user-attachments/assets/4895c7be-3c57-4fab-83d7-f59c9577ad6d)

There is nothing about CSS.

**Comment by pbek** [comment]
No, in the script repository.

![image](https://github.com/user-attachments/assets/01751b88-0e85-4cfa-b67c-88197d953dd4)

**Comment by DutchPete** [comment]
OK, thanks Patrizio. My apologies for not reading your initial reply accurately.
