### ISSUE TITLE
[SUPPORT] Toolbar: icons are white, what is "Full"?

### ISSUE THREAD

**Issue by DutchPete** [pbek/QOwnNotes#3183]
#### Question
How can I make them non-white so they are visible?

Is it possible to get rid of that "Full" thing?

![image](https://github.com/user-attachments/assets/a7a15e42-42c0-45d1-8dda-3ccdebda29d4)

**Comment by pbek** [comment]
Can you please post the output from the debug settings that you can copy when you get to the settings dialog in QOwnNotes and head over to the *Debug* section of it?

**Comment by DutchPete** [comment]
The *Debug* section is huuuuge: do you want all of it? If so, should I compress it and attach that file?
If not, which section do you want specifically?

**Comment by pbek** [comment]
The GitHub issue template when you open a new issue tells you all about it. 😊 The issue assistant also does it for you.
It's put in a nice "details" tag then so you can slide the info open in the issue. But now here, just paste the content...

**Comment by DutchPete** [comment]
Figured it out. The checkbox indicated was checked; unchecking it did the trick.
