### ISSUE TITLE
[SUPPORT] Justify text in preview

### ISSUE THREAD

**Issue by DutchPete** [pbek/QOwnNotes#3186]
#### Question
I tried various CSS code options but none work. ChatGPT seems to think QON uses a special HTML rendering engine.

In any case, a simple selector like `#preview` or `#notepreview does not work`.

**Comment by pbek** [comment]
Did you look if that's even supported by the QTextBrowser component of the preview? (see script description)

**Comment by DutchPete** [comment]
No, I did not because I was not aware of it, nor do I even know what it means.
But from your question I deduce that justifying text is not possible, correct?
