### ISSUE TITLE
QOwnNotes crashes, cannot restart without system reboot

### ISSUE THREAD

**Issue by gpe5280** [pbek/QOwnNotes#319]
I keep QOwnNotes open all day for days at a time - it's that important to my work (so, many thanks for developing this fine application.) Every so often, it crashes without error message or warning. I cannot discern a pattern. When that happens, I cannot restart the app. The only solution I've found is to reboot the system. This suggests there is something hanging around in memory or perhaps on disk that is preventing restart. Attempts to start from the command line are unsuccessful and show no error.

Any suggestions for how I might begin to troubleshoot this issue?

System: Xubuntu 16.04

**Comment by pbek** [comment]
Thank you for your kind words!

About your crash... Wow, I never heard of something like that before.
If you run it from the command line, do you get any useful error message when it crashes and when you want to restart it again?

**Comment by pbek** [comment]
If that doesn't lead to anything you could install the debug symbols from <https://launchpad.net/~pbek/+archive/ubuntu/qownnotes/+build/10742246> and then try to get any useful information out of your crash.

Our you could even build QOwnNotes yourself and take a look what happens when it crashes:
<http://www.qownnotes.org/installation#building>

**Comment by gpe5280** [comment]
Running...
`$ QOwnNotes`
...simply returns me to the command prompt. Likewise...
`$ ps aux | grep QOwn*`
...shows nothing.
I'll install the debug symbols and report back.

**Comment by gpe5280** [comment]
Looks like the debug symbols are already installed.
`# apt install qownnotes-dbgsym
Reading package lists... Done
Building dependency tree       
Reading state information... Done
qownnotes-dbgsym is already the newest version (16.09.6-1ubuntu3ppa1~xenial1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
`
If this is the case where might I look for information regarding the crash or failures to restart? I can find no references in the syslog to qownnotes.

**Comment by pbek** [comment]
You can use gdb to get some output:

```
$ gdb QOwnNotes
r
(wait for segfault)
bt full
```

**Comment by gpe5280** [comment]
OK. It's running.
```
Starting program: /usr/bin/QOwnNotes 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffec444700 (LWP 3910)]
[New Thread 0x7fffdf455700 (LWP 3911)]
[New Thread 0x7fffde841700 (LWP 3912)]
[Thread 0x7fffde841700 (LWP 3912) exited]
...
```
I'll report back when a crash occurs. It could be a few days.

**Comment by pbek** [comment]
Ok, great!

**Comment by pbek** [comment]
Meanwhile you could also post your settings so I can skim them for abnormalities.

**Comment by pbek** [comment]
Any new crash so far?

**Comment by pbek** [comment]
I will close this issue until there is more information.
