### ISSUE TITLE
Transfer this repository (and other QOwnNotes related) into the QOwnNotes organization

### ISSUE THREAD

**Issue by Neustradamus** [pbek/QOwnNotes#3195]
Dear @pbek, @QOwnNotes team,

Can you move your "QOwnNotes" repositories into the @QOwnNotes GitHub organization?

List:
- https://github.com/pbek?tab=repositories&q=QOwnNotes&type=&language=&sort=

After transfers, redirections will be here, no lost.

Thanks in advance.

**Comment by pbek** [comment]
Nah, sorry. Not yet. That's a large move and lots of stuff needs to change then, even when you think "redirections will be here".

> Thanks in advance.

Why do you think you are entitled that I do that?

**Comment by Neustradamus** [comment]
@pbek: Like I have said, the project has already a good place, the @QOwnNotes organization, and it is already good to have several repositories into. All QOwnNotes repositories at a same place will be better to have several places.

After the main source code, this repository, transfer, redirections will be here, no lost example of previous transfers:

- https://github.com/nerzhul/ocsms -> https://github.com/nextcloud/ocsms
- https://github.com/tigaseinc/tigase-server -> https://github.com/tigase/tigase-server
- https://github.com/boothj5/profanity -> https://github.com/profanity-im/profanity
- https://github.com/asciimoo/searx -> https://github.com/searx/searx
- ...

Old links, issues, PRs, tags, releases, and all others are redirected correctly without any problems.

In more:
- https://github.com/nerzhul/ocsms/releases/tag/2.2.0 -> https://github.com/nextcloud/ocsms/releases/tag/2.2.0
- ...

I have already done for several projects perfectly.

Please reopen my ticket and please do it, for example, you can start with old repositories to test, and to confirm my serious ;)

Thanks in advance.

**Comment by Neustradamus** [comment]
@pbek: I wish you a Happy New Year 2025!

Have you progressed on this ticket?

Thanks in advance.
