### ISSUE TITLE
Subfolders not shown in List

### ISSUE THREAD

**Issue by dasmaetthes** [pbek/QOwnNotes#320]
I activated in Settings option to include sub-folders but they aren't shown in the note list, as well as notes inside this folder

**Comment by pbek** [comment]
I just tried that and it worked. Have you enabled the tag / subfolder pane?

**Comment by dasmaetthes** [comment]
Oh thanks, this I option I somehow missed.
Well one more panel, wouldn't it possible to have a tree with folders and notes to get it together in one panel would save a lot of space and keep the application more simple see also my advice in [321]

**Comment by pbek** [comment]
Thank you for your suggestion. In the beginning I tried to do it that way (tree with subfolders), but there were people with 1000+ notes in a subfolder so we quickly discarded that view and the subfolder tree was born. I think it works out well.
