### ISSUE TITLE
Application get's overloaded

### ISSUE THREAD

**Issue by dasmaetthes** [pbek/QOwnNotes#321]
Hey,
I'm using this application already very long time in the beginning it was very simple but useful one with time it got  of course also a lot of new features. But actually there are a lot of functions and settings. Not more this simple app it was in the beginning. And not comparable to tomboy which I find is kept simple but whit a lot of functions.

It's just my personal opinion but you maybe should make a step back and keep it more simple. I know other users would say no it would be even better when it gets new functions. 

Maybe it would be nice to find a way in the middle. Which would make everyone happy.

**Comment by pbek** [comment]
So what is your suggestion?

**Comment by dasmaetthes** [comment]
IMHO clean the UI
- combine the note editor and preview, markdown characters should be in a light colour just like in server app
- split the toolbar, one is over the folder/tags/note panels with add, delete, search, forward, backward etc. buttons which you need for all notes. An other one additional for those who want show it with note features to add bold, italic, pictures, encrypt etc. this could be also placed in context menu
- make it modularly encryption, advanced export and tasks could be add-ins, IMHO specially task has nothing to do with notes, it belongs in separate application or calendar application

**Comment by pbek** [comment]
> combine the note editor and preview

what do you mean by "combine"?

> markdown characters should be in a light colour just like in server app

please create a editor schema, export it and attach it here if you have a suggestion

> split the toolbar

aren't they already splitted enough? or do you have concrete suggestions?
you can place them wherever you want by dragging them

> context menu

wouldn't it get cluttered for including functions that just simple add some characters? using the shortcuts would rather be suggested...

> make it modularly encryption

you mean like entering a custom command for encrypting and decrypting a note? that could be integrated into the scripting engine, if that is what you are talking about

> advanced export

what do you mean by this? there really isn't anything to export, the notes are just simple markdown files in folders... and can export notes in any way you like via the scripting engine

> IMHO specially task has nothing to do with notes

other people are even ask me to integrate it more, like in #275
currently you can link tasks in notes, which is super-handy
for me tasks and notes go pretty hand in hand

**Comment by dasmaetthes** [comment]
> combine the note editor and preview
> what do you mean by "combine"?
> 
> markdown characters should be in a light colour just like in server app
> please create a editor schema, export it and attach it here if you have a suggestion
> 
> split the toolbar
> aren't they already splitted enough? or do you have concrete suggestions?
> you can place them wherever you want by dragging them

I hope the pictures would explain it better

![ui_suggestion_1](https://cloud.githubusercontent.com/assets/8776718/18542502/88e0bf98-7b2b-11e6-8a7a-a98959fd3877.png)
![ui_suggestion_2](https://cloud.githubusercontent.com/assets/8776718/18542501/88e0b5c0-7b2b-11e6-950a-22f1b36efd41.png)

> wouldn't it get cluttered for including functions that just simple add some characters? using the shortcuts would rather be suggested...

Yeah maybe you are right it would be, I just thought it could be useful if you have deactivated the toolbar and need add something where you forgot the markdown syntax, it would be faster/easier then instead of activate toolbar add the syntax deactivate toolbar

With modularly I mean that you have  add-ons/ add-ins:
- one for the encryption function
- one/several  for the export as pdf/markdown/html
- one for the task
Who needs one of this function can activate it in settings.

**Comment by pbek** [comment]
Thank you for your illustration.

> toolbar placement

I don't think Qt let us put a toolbar there, but you can put single toolbars on the left side (vertically) and you can enable/disable them with a context menu

> markdown syntax

I'm sorry <https://github.com/ali-rantakari/peg-markdown-highlight> doesn't allow that...

> It would be faster/easier then instead of activate toolbar, add the syntax, deactivate toolbar

but you can always use it via the main menu

> one for the encryption function

just turn off the encryption toolbar and you don't see anything of it (but there still are three menu items in the `Edit` menu)

> one/several for the export as pdf/markdown/html

are the main menu entries bothering you so much? or are you talking about new ways to export notes as "extensions" (because that already works)?

> one for the task

you mean to disable them? they currently are very integrated into QOwnNotes...

**Comment by Maboroshy** [comment]
QOwnNotes have a lot features. But they don't hold you to run it as a really minimalistic app. 

I run it that way at my job. No menu, no status bar, no toolbar. Just note list and editor on the screen. But I still can use some fancy features as tags, sub-folders and scripting at my home in the very same app.

I also don't use half of the features the app has. Like OwnCloud integration that is a core feature of the app. But having it in the settings doesn't make my experience worse. That "half" is different for all of us.

**Comment by pbek** [comment]
Exactly, @Maboroshy. The vast majority of new features resulted from feature requests by users. :grin:

**Comment by pbek** [comment]
I will close this issue until there is more information / insight.
