### ISSUE TITLE
Tablet mode suport

### ISSUE THREAD

**Issue by dasmaetthes** [pbek/QOwnNotes#322]
I'm using QOwnNotes on a Windows 10 Tablet, it would be nice if the application would support touch-screens better
meaning:
 - open keyboard when I tap into edit panel
 - keyboard shouldn't hide the lower text parts in edit panel (panel should change size and become scrollable)
 - the entries of the note list should be a bit higher that it would be easier to tap on a note

**Comment by pbek** [comment]
Thank you for your suggestions, but until someone provides me with such a device I will not be able to look into it. And I don't think I can control your virtual keyboard...

**Comment by dasmaetthes** [comment]
Okay maybe it's to specific. For the keyboard there must be some API from MS but don't know if it works together with QT. However, it would be nice at least if it would be possible in settings to change the high of items in note/folder/tag list.

**Comment by pbek** [comment]
> it would be nice at least if it would be possible in settings to change the high of items in note/folder/tag list

I will take a look at that

**Comment by pbek** [comment]
## 16.09.9
- you can now set and reset the item height of the tree widgets and
  lists of the main window in the interface settings
    - this is handy if you are using QOwnNotes on a touch display
- there now is a button to reset the toolbar size in the interface settings

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by dasmaetthes** [comment]
Works fine. But the item height of navigation list/tree isn't changed, should it be like this? However for me this isn't important.

**Comment by pbek** [comment]
We can change that too, you didn't mention it so far.

**Comment by dasmaetthes** [comment]
I wouldn't need this. Thank you

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by dasmaetthes** [comment]
Thank you, for me it works fine.

**Comment by pbek** [comment]
Great, thank you!

**Comment by pbek** [comment]
@dasmaetthes I think #381 could be interesting for you

**Comment by pbek** [comment]
you can now modify the styling of the user interface
