### ISSUE TITLE
[Question] Is there a specific reason the tags are stored outside the notes themselves ?

### ISSUE THREAD

**Issue by yvesle** [pbek/QOwnNotes#323]
Hi
In my eyes the beauty of keeping notes in text files is the portability it allows,  making the notes as much application agnostic as possible.
Storing tags outside the notes goes against that principle so I guess there must be a good reason and I wonder what that is.
Playing with the tag functionnality it seems that dealing with renaming the tags would be a lot less practical. Am I right ? Maybe an item for the Knowledge base ?

**Comment by pbek** [comment]
Yes, making all operation on tags that are currently possible would be really painful to do. Plus the notes of the users need to be modified, not all users like that. Everyone treat their note differently and especially the structure of their files, I don't really want to invade there... 
Tags are kind of an "addon" to the notes... Many users are using subfolders too for structuring their notes.

If you have to write something for the knowledge base you can do so here: <https://github.com/pbek/QOwnNotes/wiki>

**Comment by pbek** [comment]
What is your opinion on how that should be handled?

**Comment by yvesle** [comment]
Thank you for the explanation. In my view the tags would be contained in the notes itself with a Markdown compatible format (ie: not interpreted) anywhere in the doc. 
Renaming the tag would be akin to do a search and replace across all the files. 

You rightly pointed out that that would change the timestamp of the files and that could cause problems if you rely on it for ordering. But if you do not change them, that might cause problem for any synchronisation/backup solution you may be using... Maybe adding only X seconds to the timestamps ?
Tricky one indeed.

**Comment by pbek** [comment]
No everyone is using the markdown highlighting, there are also people who are using plain text files without markdown. And there are so many opinions, for example some think the tags belong to the file name or to the headline. So I put them into a sqlite database with references to note filenames...

**Comment by pbek** [comment]
## 17.09.6
- added the first alpha version of external note tagging support via the 
  scripting engine (for [Issue #323](https://github.com/pbek/QOwnNotes/issues/323), [Issue #338](https://github.com/pbek/QOwnNotes/issues/338), [Issue #379](https://github.com/pbek/QOwnNotes/issues/379), [Issue #472](https://github.com/pbek/QOwnNotes/issues/472), [Issue #530](https://github.com/pbek/QOwnNotes/issues/530) and [Issue #603](https://github.com/pbek/QOwnNotes/issues/603))
    - as soon as a script is activated that implements the new function
      `noteTaggingHook` note tagging will be handled by that function
    - please install the script [note-tagging.qml](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/note-tagging.qml)
      to test the basic functionality and report in [Issue #530](https://github.com/pbek/QOwnNotes/issues/530).
        - your internal tag database and your notes might get modified 
        - don't use this script on your production note folder, please make a 
          copy of it and test it there!
    - following features should already work via the QOwnNotes user interface
        - initially importing tags like `@tag` from your notes and overwriting
          your current tag assignment
            - you will not loose your tags tree, just the former assignment to notes
            - you can still move tags into other tags
            - if more than one tag has the same name in your tag tree the 
              first hit will be assigned
        - adding a tag to a note will add the tag to the note text        
        - removing a tag from a note will remove the tag from the note text
        - removing of tags in the tag list will remove those tags from your notes
        - renaming of tags in the tag list will rename those tags in your notes
        - bulk tagging of notes in the note list will add those tags to your notes
        - bulk removing of tags from notes in the note list will remove those 
          tags from your notes
    - for more information please take a look at the [scripting documentation](http://docs.qownnotes.org/en/develop/scripting/README.html#noteTaggingHook)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you with the script [note-tagging.qml](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/note-tagging.qml)?
