### ISSUE TITLE
Change preview font

### ISSUE THREAD

**Issue by Redsandro** [pbek/QOwnNotes#325]
Just installed from repo on Linux Mint 18. How do I change that (terrible) default font?

![image](https://cloud.githubusercontent.com/assets/1702193/18616720/15f1f43c-7dc1-11e6-9314-852d9e69d09c.png)

**Comment by pbek** [comment]
That default font must be a Linux mint thing. QOwnNote takes what the OS proposes. You can change it in the interface settings. Does that answer your question?

**Comment by Redsandro** [comment]
@pbek Yes! I have looked through the settings and only saw the styling options for the editor. Now I've looked again and see that the font selector is at the bottom of the interface settings window.

Sorry for not searching better. Thanks!

PS - I see it just takes the first font in the list. Which in my case is a terrible font. :laughing:

**Comment by pbek** [comment]
It takes whatever font is picked by default by the preview text browser as default.

**Comment by Redsandro** [comment]
No, I mean it works perfectly now that I selected a normal font. But on first install, the preview font was set to the first font in my font list. This is the first time I even see this font, honestly. 

I have not experienced any trouble in any app. Mint works fine with Qt apps.

**Comment by pbek** [comment]
Did you take the QOwnNotes settings file from an other system where the font was already set to a font that your current system hasn't installed? Because on first startup the default font that the system decides fit for the preview text browser is taken...

**Comment by Redsandro** [comment]
Nope. I had never heard of QOwnNotes before. Was looking for non-electron note taking apps with markdown support and just installed it today.

The system decided the editor font and the code font fine, but something is apparently incompatible with the way Linux Mint proposes the preview font.

**Comment by pbek** [comment]
If you want to start all over again (to be able to send me the settings from the debug settings page, so I can analyse them) you can press `Clear app data and exit` in the general settings.

This is where the font is set if none was in the settings, works on every operating system I came across so far...
<https://github.com/pbek/QOwnNotes/blob/develop/src/mainwindow.cpp#L1692>

**Comment by Redsandro** [comment]
Can you tell me where settings are stored? I can rename it, and rename it back after I give you the debug settings.

**Comment by Redsandro** [comment]
Found it. There are two different directories.

`~/.local/share/PBE/QOwnNotes` and `~/.config/PBE/QOwnNotes.conf`

Is only the latter one config?

**Comment by pbek** [comment]
Under Linux `~/.config/PBE/QOwnNotes.conf` for the settings and `~/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite` for the internal database.

**Comment by pbek** [comment]
Backup both before you clear. (Or rename both files)

**Comment by Redsandro** [comment]
Okay, I think I found how to recreate the bug.

If you clear settings and restart, quickly go past the wizard and start the app, everything works fine.

Here is the debug output:

---

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sun Sep 18 22:27:38 2016`
**Version**: `16.09.10`
**Build date**: `Sep 18 2016`
**Build number**: `238`
**Platform**: `linux`
**Operating System**: `Ubuntu 16.04 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.5.1`
**Qt Version (runtime)**: `5.5.1`
**Portable mode**: `no`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `hicolor`
**Notes in current note folder**: `4`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**serverVersion**: *empty*
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/redsandro/ownCloud/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**activeNoteSubFolder name**: *empty*

## Settings

**Editor/CurrentSchemaKey**: `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**LastUpdateCheck**: `2016-09-18T22:26:36`
**MainWindow/mainToolBar.iconSize**: `24`
**MainWindow/noteTextEdit.code.font**: `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `Noto Sans,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `Noto Sans,9,-1,5,50,0,0,0,0,0`
**PiwikClientId**: `<hidden>`
**SettingsDialog/geometry**: `<binary data>`
**WelcomeDialog/geometry**: `<binary data>`
**appMetrics/notificationShown**: `true`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**disableAutomaticUpdateDialog**: `true`
**itemHeight**: `19`
**notesPath**: `/home/redsandro/ownCloud/Notes`
**showMenuBar**: `true`
**showStatusBar**: `true`

---

However, if during the wizard you press this button:

![image](https://cloud.githubusercontent.com/assets/1702193/18618885/1e0afb44-7df0-11e6-9e3a-c906f86413d2.png)

Then close settings, finish the wizard and start the app, __then__ the font is messed up.

Here is the debug info:

---

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sun Sep 18 22:32:30 2016`
**Version**: `16.09.10`
**Build date**: `Sep 18 2016`
**Build number**: `238`
**Platform**: `linux`
**Operating System**: `Ubuntu 16.04 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.5.1`
**Qt Version (runtime)**: `5.5.1`
**Portable mode**: `no`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `hicolor`
**Notes in current note folder**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**connectionErrorMessage**: *empty*

## Note folders

**currentNoteFolderId**: `0`

## Settings

**Editor/CurrentSchemaKey**: `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**MainWindow/noteTextEdit.code.font**: `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `Noto Sans,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `monospace,9,-1,2,50,0,0,0,0,0`
**PiwikClientId**: `<hidden>`
**SettingsDialog/geometry**: `<binary data>`
**WelcomeDialog/geometry**: `<binary data>`
**appMetrics/notificationShown**: `true`
**cryptoKey**: `<hidden>`
**notesPath**: `/home/redsandro/ownCloud/delme`

---

As you can see, the `noteTextView.font` is missing if you open the network settings in the wizard first.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Redsandro** [comment]
@pbek The problem is fixed. :+1:

**Comment by pbek** [comment]
Thank you for reporting and testing!
