### ISSUE TITLE
How to enable encryption?

### ISSUE THREAD

**Issue by Redsandro** [pbek/QOwnNotes#326]
I see it mentioned as a feature, but I can't find any such option in settings (nor was it asked in the wizard after installation).

On the website screenshots, I see notes about encryption, but my installation came with these notes:

![image](https://cloud.githubusercontent.com/assets/1702193/18616880/5b86a7b0-7dc4-11e6-9282-79486b263af7.png)

Perhaps this feature is not yet available on the Linux repository?

**Comment by pbek** [comment]
Please take a closer look at the `Edit` menu. There also are a few buttons for it in the encryption toolbar.
Does that answer your question?

**Comment by Redsandro** [comment]
Oh yes there it is. Sorry again for being ignorant. I didn't mean to. I guess some features are in different places than where I would intuitively expect them to be.

This feature is a bit less friendly than I had imagined. It's not transparent; you need the password every time.

Here's how I'd like to see something similar:

* Wizard asks for a global encryption password
* Hashed password is stored as encryption key in configuration file
* Key is used to transparently encrypt/decrypt _all_ notes stored on your computer
* Notes folder can now be safely synced with Dropbox

**Comment by pbek** [comment]
The configuration file is just stored locally, not synced and the configuration format different under every operating system (and that would just be one of several problems). I think you are better off encrypting your note folder with one of the plenty 3rd party encryption tools like TrueCrypt or VeraCrypt. The encryption QOwnNotes offers is just to lock away single notes...

**Comment by pbek** [comment]
I will close this issue until there is more information.

**Comment by Redsandro** [comment]
@pbek 
> The configuration file is just stored locally, not synced and the configuration format different under every operating system (and that would just be one of several problems).

I think you misunderstand me. It doesn't matter what the configuration looks like or where it's stored. We don't want the encryption key to be synced with the encrypted notes!

I mean that enc/decryption happens transparently on _all_ notes. The (hashed) key is stored locally in the configuration. This means when the cloud is hacked, _all_ notes are unreadable. Now if your computer is hacked, that's a different story. But you should always lock your screen when you walk away from your computer anyway. (And have your home encrypted.)

**Comment by pbek** [comment]
What do you mean by "all notes? All notes you manually encrypted with QOwnNotes?
There are people who want to be asked for the password every time (after e.g. 10min).
And having different passwords for notes enables you to share an encrypted note with someone else...

**Comment by Redsandro** [comment]
> What do you mean by "all notes?

All notes, literally. Ignoring the manual encryption function for a moment. All notes, so they are stored encrypted on your drive/cloud/storage. You never have to type a password because it's stored in your config, and you never have to worry about accidentally _not_ encrypting a note with sensitive information.

This is the kind of security that benefits you _constantly_. Massive amounts of data are stolen from the cloud all the time. Every year another record. Sharing an encrypted note however, how often do you do that?

Of course, if you're seriously wondering how to implement this without losing your custom note encryption function, it's not hard. Just leave the option in. If you custom-encrypt a note, don't master-encrypt it. Then if the program cannot decrypt the note using the configured password, it knows it was custom encrypted.

**Comment by pbek** [comment]
You cannot search in encrypted notes and if you encrypt all notes you cannot read them in the ownCloud notes app or the iOS / Android note apps or anywhere else... The notes would be completely locked to QOwnNotes, no one really wants that, I guess. ;) QOwnNotes is still a plain text file notepad.

**Comment by Redsandro** [comment]
> You cannot search in encrypted notes

Of course you can. It's a matter of programming. EFS in Windows encrypts files. NTFS can compress files. And you can still search them, because compression/encryption is transparent.

What you (probably) do now is

```
For each note:
    open()
    search()
    close()
```

What you do then is

```
For each note:
    open()
        if encrypted:
            decrypt()
    search()
    close()
```

> you cannot read them in the ownCloud notes app or the iOS / Android note apps

You are right. So people who care about that wouldn't use this feature. They also shouldn't take notes with sensitive data like server ip addresses or login credentials to sessions.

> The notes would be completely locked to QOwnNotes, no one really wants that, I guess.

Well, except everyone I know. My colleagues and I all have our own note taking apps for personal development notes. I have hundreds of notes for non-shared personal use. If we want to share a note, we use Trello or Google Docs or Keep.

> QOwnNotes is still a plain text file notepad.

And it would still be. Except with an option to transparently encrypt all notes.

---

If you don't want this and/or don't care about this, fair enough. We can drop it. But if you mention problems that aren't really problems, I will debunk them. :smile: 

I mean it in a good way tho. Just looking to upgrade Tomboy (multiplatform, worth checking out) with something small-footprint with a markdown backend and built-in encryption so I can store (sensitive) notes in the cloud. Which ironically is OwnCloud, but might as well be Dropbox.

**Comment by pbek** [comment]
Decrypting all notes takes much time, especially since several attempts have to be made because there were several methods to do it in QOwnNotes. And if one has 1000+ notes reading all notes takes far too long.

Is Tomboy capable of encrypting all notes? I guess Tomboy isn't storing them in single, plain-text files...

I still don't see the point since ownCloud / Nextcloud is offering server side encryption... and on other cloud storage providers it would just be best to store the notes in an encrypted container. I don't see any advantage in encrypting every markdown file. What's the point in having markdowns files then?

**Comment by Redsandro** [comment]
> Is Tomboy capable of encrypting all notes?

No. That's why I am looking to upgrade to something that supports encryption (and markdown) :stuck_out_tongue_winking_eye: 

> I guess Tomboy isn't storing them in single, plain-text files

Yes they are. Some kind of annoying xml format (because tomboy exists for long). You can convert them to markdown.

> ownCloud / Nextcloud is offering server side encryption.

Yes, but

* Only if you have a custom server. A lot of 3rd party services don't offer this (yet).
* This is not secure. If the cloud is hacked, hackers _still_ get your data.  
From the [OwnCloud blog](https://owncloud.org/blog/how-owncloud-uses-encryption-to-protect-your-data/):  

> “Encryption and decryption always occurs __on the server side__. [..] However, this method of encryption also means that __the server administrator can intercept your data__.”

So some businesses don't allow us to use this.

> it would just be best to store the notes in an encrypted container

This has many drawback. That's why file-based encryption was invented over disk-based-encryption (as used in containers).

> What's the point in having markdowns files then?

Exactly the same as now. Portability. Except to be kept private and for internal purposes. Plus, advanced editing capabilities that surpasses basic formatting.

**Comment by pbek** [comment]
Beside all other problems with encrypting all notes... How is ownCloud Notes, CloudNote, MyOwnNotes or any other 3rd party app supposed to read those notes?

**Comment by Redsandro** [comment]
They are not! There are no other problems, except this one:

> there were several methods to [encrypt notes] in QOwnNotes. 

And even that one has a solution, if you want to.

> And if one has 1000+ notes reading all notes takes far too long.

This is simply not true. Entire laptops run on encrypted file systems.

---

Syncing is a feature, not mandatory. There are plenty of people who care about taking notes, care about markdown, care about encryption, but _don't_ care about OwnCloud or other apps.

There are two groups of people. You seem to persist that these groups of people are mutually exclusive. But they can both be served by a feature you turn on or off.

There are no technical problems. Just perception of problems.

Anyway, I answered that question before, so I think we better agree to disagree. Your app has a lot of potential, and being a compact multi-platform markdown note taking app makes it quite unique. The trick is to make it as usable as possible, not to restrict it to a specific workflow if that workflow is not compromised by the option for another one.

I really like the app. It looks good. I will play around with it some more, but I'm leaning towards using laverna.cc. It has transparent encryption, markdown and sync. The only downside is that it's a browser app and I'm not a fan. I also like markdown.io (you should check out how it syncs left and right pane - the text at the top of the view is always lined up - very nice) but it has no encryption and is a browser app too.

**Comment by pbek** [comment]
Please keep me posted when you find the ideal app, I'm curious what technologies it uses.

**Comment by Redsandro** [comment]
:+1:

**Comment by cablop** [comment]
> This is simply not true. Entire laptops run on encrypted file systems.

They work before the encryption loads before the operative system loads or before exposing the file system to the operative system. But...

... what you mentioned allowed me to think of this possible solutions:

1. Make a VeraCrypt/TrueCrypt container with a QOwnNotes inside in portable mode. That way the QOwnNotes transparently access your private notes. In fact, event the app itself became private, secret. You share the container to the cloud if desired.
2. Use a mechanism of your operative system, like EncFS for Linux or EFS for Windows. They are not containers, they encrypt data in the place it reside. They can be configured to run when you log in your system's session, becomming transparent to QOwnNotes or any other application. You can even use them on top of underlying OS encryption, at a performance cost, tho.
3. Use VeraCrypt, BitLocker, DiskCryptor for a secure partition/volume on your device.
4. Use Cryptomator, BoxCryptor, CryFS or BoxWrap. It seems they work pretty much like EncFS, but they are 3rd party tools.

**Comment by cablop** [comment]
> Syncing is a feature, not mandatory. There are plenty of people who care about taking notes, care about markdown, care about encryption, care about syncing with cloud storage, but **don't** care about 3rd party apps having to read the notes.

In that regard, you can simply go with a service that goes with client-to-client encryption with zero knowledge policy. The downside of this approach is, if you lose your password, you are done, the provider cannot help you recover your data, because they can't simply access it.

At the moment i can only think of two, SpiderOak and Mega.

SpiderOak is prety old and well known for that feature among being a tool for syncing and backup. You can give it a try. That end-to-end encryption is one of their flag features.

Mega is the sucessor of MegaUpload, in some sense. Despite the controversy around this project, you can trust in one thing, the people behind it wants to be **honestly unaware** of what you place on the cloud, they don't want to be responsbile of the content of your data on the servers or be prosecuted as one of them was.

**Comment by Redsandro** [comment]
For a little while I had the location where notes symlink to the unlocked mount of an ecryptfs directory. The ecryptfs directory was then shared with dropbox.

Now I use Boostnote (not Boostnote Next) with the notes stored on an encrypted library on a self-hosted Seafile instance.

**Comment by Redsandro** [comment]
> Please keep me posted when you find the ideal app, I'm curious what technologies it uses.

@pbek I reread this entire conversation, and while I understand myself from the past, I feel like I've been coming off a bit strong in my communication and I apologize for that.

In order to keep you posted: For years I have been using [Boostnote](https://github.com/BoostIO/Boostnote) and even contributed minor but important patches. The good thing is that you can have different storage configurations for every notebook at the same time. So usually I have three notebooks on my computer. 

1. Local, for locally stored notes. 
2. Work, for notes synced with Nextcloud and shared with colleagues that also use Boostnote.
3. Private. Synced peer to peer using [Syncthing](https://syncthing.net/).

The bad thing is that the weird `cson` format keeps you locked into Boostnote. But the multiple active storage folder feature is strong, very strong. You can use external and dedicated sync and encryption tools.

The one thing that has been bugging me is that I can't use the Nextcloud Notes app and consequently the Android Notes app because of this `cson` format.

With the discovery of Syncthing I no longer need the note encryption discussed 5 years ago, because I can securely sync private notes. And with "Boostnote.next" moving away from self contained markdown notes even further, I'm starting to look elsewhere again.

And thus I remember that QOwnNotes had a similar feature: Different storage locations. But you could only use one active location at a time. So I had to give QOwnNotes another try. It looks really nice. The active location selector seems unchanged though. Would you consider the ability to have all Note Folders visible in the Note List Panel? So they can all be searched at the same time? You wouldn't actively have to switch between note sources and search in every source individually.

Here is a screenshot of Boostnote with multiple note sources:
![image](https://user-images.githubusercontent.com/1702193/117509903-5a959700-af8b-11eb-9dcc-75385b8c0ce8.png)

**Comment by pbek** [comment]
Welcome back. 😁 
No, sorry. The different note folders are still there for a reason (to keep notes, certain settings and so on separated and the memory footprint low). You can use note subfolders in a note folder if you want to have more folders.

If you really want to have your "sub-folders" spread across different locations you could also sym-link them together in one note folder.

**Comment by pbek** [comment]
I also do some symlinks in one note folder, had no issues with it.
