### ISSUE TITLE
Selecting multiple sub-folders/tags to view notes in all of these sub-folders/tags

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#327]
There's a multiple selection available for tags and sub-folders but it's not connected to the note list. 

I think that selecting multiple sub-folders/tags should show a list of all notes for them in note list pane. It's logically expected behaviour and also a cool feature to have.

Can't say I really do need it personally, but that may open some interesting note grouping possibilities for guys with many notes.

**Comment by pbek** [comment]
Currently there only can be one "selected tag" or "selected subfolder" and a lot of pieces of code depend on that selection in their operation. I don't think how wise it would be to mingle with that. It would be an awesome amount of work for sure...

Is there a use case for such a scenario?

**Comment by Maboroshy** [comment]
My user case:
I was rearranging notes migrating to sub-folder structure and wanted to move all notes with several tags to specific sub-folder. Logically I've tried to select multiple tags with no avail. So I had to go through each tag, select all notes and move them with context menu. 

With proposed feature that would be N times faster, with N = number of tags. 

But this feature is not something I'd use on a daily or maybe even weekly basis.

**Comment by livmion** [comment]
Hi all,

Actually that’s my typical way to use tags and how it works in other similar softwares, like Zotero or Zim. I use them in my daily work and I think this would be very useful to help finding the right note refered specifically to a sub-subject between many others with a similar thema.

**Comment by bepolymathe** [comment]
Hello,

I agree with that. I often search for notes that mix several criteria (meeting + david + barcelona) ... To do this by selecting several tags would be great to find the right note.
In my case, this would be a daily use

**Comment by milan-rusev** [comment]
+1 for that. It would be awesome to show the notes from all selected tags and all selected folders.

**Comment by SuryaLuna** [comment]
:+1:  !!! PLEASE implement this :-)
I have the hope, that I found with QOwnNotes a software which fits my need almost completely, it's great!- but without this feature, the software would be useless for me...
Thanks a lot in advance :-)
(I need it especially for the tags)

**Comment by iolivier87** [comment]
I need this feature too. Displaying matches between subtags and subfolders is very important to me.
I'm waiting for it impatiently in order to use QOwnNotes !
Thanks

**Comment by zorglups** [comment]
Oh yes !
Please let me select tags 'a' and 'b' to show only the notes that do have BOTH tags 'a' AND 'b'.
This makes the tag meaningful and allow a really powerful search approach (ala taglocity).

**Comment by pbek** [comment]
@Waqar144 did it for sub-folders. That leaves the tags. :grin:

**Comment by Waqar144** [comment]
> @Waqar144 did it for sub-folders. That leaves the tags. grin

Maybe a new issue for that could be more motivating :rofl:

**Comment by pbek** [comment]
## 19.12.1
- you now can select multiple note sub-folders to filter notes
  (for [#327](https://github.com/pbek/QOwnNotes/issues/327), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by msbentley** [comment]
I'm not sure if this is the expected behaviour, but if I select multiple sub-folders, everything looks good. But when I _de-select_ one of them, in some cases the selection seems not to work. See the following:

![Peek 2019-12-05 13-37](https://user-images.githubusercontent.com/1671065/70236058-74162c00-1764-11ea-987c-e636b0a81038.gif)

**Comment by Waqar144** [comment]
Hi thanks for reporting.

Can you tell me what your current note sub-folder settings (in panel settings) are?

**Comment by msbentley** [comment]
Is it these setting you need?

![image](https://user-images.githubusercontent.com/1671065/70237254-11725f80-1767-11ea-8173-f78d028da1a6.png)

BTW I'm selected and de-selecting with ctrl+click, in case that makes a difference...

**Comment by Waqar144** [comment]
> BTW I'm selected and de-selecting with ctrl+click, in case that makes a difference...

Reproduced.
Thanks.

Usually deselecting to one folder is done with a simple click. Doing it with a Ctrl + Click is causing this.

But if you have 3 or more folder in selection, you can deselect one of them with ctrl + click and that should work fine.

**Comment by msbentley** [comment]
OK, understood now - thanks! With the caveat above, I can of course work with it, but I find it a bit confusing that if one is deselecting several folders with ctrl-click, you end up with the case of the highlighted folder selection not matching the note list.

**Comment by pbek** [comment]
> Usually deselecting to one folder is done with a simple click. Doing it with a Ctrl + Click is causing this.

@Waqar144 maybe do the same like you did for tags today? :grin:

**Comment by pbek** [comment]
## 19.12.2
- you now can select multiple note tags to filter notes
  (for [#327](https://github.com/pbek/QOwnNotes/issues/327), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Waqar144** [comment]
> > Usually deselecting to one folder is done with a simple click. Doing it with a Ctrl + Click is causing this.
> 
> @Waqar144 maybe do the same like you did for tags today? grin

Great idea!
will do in a minute

**Comment by pbek** [comment]
## 19.12.3
- fixed deselection of multi folder selection (for [#327](https://github.com/pbek/QOwnNotes/issues/327), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by msbentley** [comment]
Works perfectly, thanks a lot @pbek and @Waqar144!

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by pbek** [comment]
We had to revert the last fix because of #1489.

## 19.12.4
- fixed deselection of multi folder selection again (for [#327](https://github.com/pbek/QOwnNotes/issues/327), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
## 19.12.14
- made some performance improvements when changing the current note item
  (for [#327](https://github.com/pbek/QOwnNotes/issues/327), thank you @Waqar144)
