### ISSUE TITLE
[Feature] Edit in preview 

### ISSUE THREAD

**Issue by Redsandro** [pbek/QOwnNotes#328]
I've been trying out this app for the day, and it's pretty sweet! :+1: 

One thing I'm really missing though is the ability to edit the formatted version of the notes. For example quick edit a typo, add a line of text, or format a selection as bold or italics. Currently I have to open the editor view, or switch to the editor view. I would like to just type directly on the preview.

Two related bugs:

Opening the editor pane next to the preview to make a fix causes both panes to jump back to the top, so I have to search where I wanted to make an edit.

Switching to the editor view in stead works, but switching back to the preview causes a jump to the top, so I have to search where I was reading.

If we could do simple editing in the preview itself and only need the actual editor for more advanced markdown, I think QOwnNotes would be a good replacement for Tomboy Notes, which I have been using for 10 years but has always been too limited in formatting.

The preview could then be just the view, and the editor could be the markdown editor for advanced editing.

**Comment by pbek** [comment]
The only thing that this switching currently does is turning on pane off and the other pane on. I will take a look if that can be improved.

Changes in the preview would promptly being overwritten by the markdown, no changes will be feeded back into the markdown edit. If you want a rich note editor, I think QOwnNotes may not the way to go for you. See also <http://www.qownnotes.org/Knowledge-base/Does-QOwnNotes-support-ownNote>.

**Comment by Redsandro** [comment]
I understand that's how it is now. I'm proposing a bi-directional edit flow. It has not really anything to do with changing the richness of the formatting, but more with the usability.

You can see here what I mean. Type something in both panes: https://leeoniya.github.io/redactor-js/

**Comment by pbek** [comment]
I'm sorry, I can't see that coming for QOwnNotes.
But I can see a "scroll to current cursor position after switching back to the edit view" feature.

**Comment by Redsandro** [comment]
> I can see a "scroll to current cursor position after switching back to the edit view" feature.

Great! Also a _"scroll preview back to editors' cursor position after switching back to preview"_  feature?

> I'm sorry, I can't see that coming for QOwnNotes.

Too bad. I think it would add considerable usability. Because you can't really read notes and make edits without a hassle, which means effectively you spend all your time in the editor view and never actually use the preview.

Out of curiosity, is it because you?

* Don't know how?
* Don't want to?
* Are depending on an upstream library that handles the panes? (if so, which one?)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Redsandro** [comment]
@pbek 
> There now is a new release, could you please test it and report if the new features work for you?

Oh yes, they don't jump anymore. Nice! :+1: 

You do notice the rounding errors when switching repetitively, but the jumping is gone, making it a lot easier to use.

---

> to name a few reasons...

I know there are challenges, but that's the fun and usability bonus. For example, for note taking, we don't need to be able to _paste_ rich content. We just need to be able to type words and fix typos.

If for example the cursor in the preview can be synced with the cursor in the (hidden or not) editor, any typed letters can be inserted at both cursors, and a redraw of the html is not necessary.

> people will start pasting rich text

Don't allow pasting of rich text. :smile:

**Comment by pbek** [comment]
Thank you for testing.
But I still don't think rich text editing will come any time soon. 😉

**Comment by Redsandro** [comment]
> I still don't think rich text editing will come any time soon. :wink:

Fair enough. Too bad I don't speak C++. I'm a node developer but this is the kind of tool I _don't_ want in Electron. 100MB + loadtimes. QOwnNotes is a lot more compact. :joy: 

Ideally I would not need the editor to write simple notes with very basic formatting, and only whip out the markdown source for advanced editing. This back and forth switching distracts from productivity.

But I will try for a while. :)

**Comment by pbek** [comment]
You will learn ;)
