### ISSUE TITLE
Edit and Window need a shortcut

### ISSUE THREAD

**Issue by Redsandro** [pbek/QOwnNotes#329]
I find myself pressing Alt+W and Alt+E, but it doesn't work like in other software.
Only N̲ote and H̲elp have shortcut keys defined.

![image](https://cloud.githubusercontent.com/assets/1702193/18618466/ad331ecc-7de7-11e6-91e8-8dc06bcb9ee5.png)

Please add shortcuts for W̲indow and E̲dit too, as they are pretty universal. :smile:

**Comment by pbek** [comment]
Usually the operating system decides that access keys for menus. Which operating system are you using?

**Comment by Redsandro** [comment]
Linux Mint 18 (AKA Ubuntu 16.04). Every other program seems to do this, so I am not sure it's the operating system. Here is an example:

![image](https://cloud.githubusercontent.com/assets/1702193/18618753/5625edfc-7ded-11e6-8d47-881c5f819f26.png)

I do remember in some widget toolkits you need to define the key in the label, like `&Window`. Perhaps the translations for the English language do not have the `&`.

**Comment by pbek** [comment]
I stopped defining the `&` because operating systems (or desktop environments) seem to ignore them or set them if not set. Translators tend to get confused by them... It seems Linux Mint handles that differently (I'm on Ubuntu too, but with KDE), so I will add the missing two for the main menu.

**Comment by Redsandro** [comment]
Great! :+1:

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Redsandro** [comment]
@pbek all menu items have shortcuts now. :+1: 

Thanks.

**Comment by pbek** [comment]
Great! Thank you for testing.
