### ISSUE TITLE
cannot open database

### ISSUE THREAD

**Issue by wayneward** [pbek/QOwnNotes#33]
hi i tried to install ive added the ppa, i get this when i try to launch see attached also in a terminal it says 
QDir::mkpath: Empty or null file name
![workspace 1_103](https://cloud.githubusercontent.com/assets/11428255/12514236/2f523824-c11a-11e5-9da2-b16909d3d303.png)

**Comment by pbek** [comment]
Hi @wayneward , thank you for your report!
From your other issue I assume you are using Ubuntu 14.04.
Which version of Qt are you using? QOwnNotes needs at least Qt 5.3 (which isn't included in Ubuntu 14.04). Did you install 3rd party Qt libraries, like `ppa:beineri/opt-qt551-trusty`?

**Comment by wayneward** [comment]
i got it working i just added the full stop on the on the env - logged out and back in and added the api to own cloud and it works just testing now 
here is a biggy - because its a qt app can we roll a click package and submit it to the ubuntu touch.. or will this not work ? as this on the ubuntu touch phone / tablet would be amazing just what its missing ? can it be built armhf from qt builder and run on arm?

**Comment by pbek** [comment]
So far I only found out that you personally have to request building of arm packages on Launchpad, but I yet don't know if click-builds are possible with it... Do you have any experience with Ubuntu Touch packaging?

**Comment by wayneward** [comment]
Ive built a couple of webapps and tested them on the phone and them 
added them to the store and they work on the phone
im wondering if i run the buid from source will it create a package for 
armhf and i install on ubuntu touch?

Wayne

**Comment by pbek** [comment]
Are there qt-dev packages on Ubuntu Touch? And I wonder if the ownCloud sync client is available for ubuntu touch...

**Comment by pbek** [comment]
I assume this issue can now be closed, please just reopen it if there was something else.
