### ISSUE TITLE
Some icons don't display correctly

### ISSUE THREAD

**Issue by michael-rowe** [pbek/QOwnNotes#331]
Hi there

First of all, thanks for a great app. I've been trying to find something to replace Evernote for ages and this seems to tick (almost) all the boxes I need.

Secondly, I've noticed that the icons in the toolbar seem to come from two different icon sets (see attached screenshot). I'm running Ubuntu 16.04 with arc-dark theme and Paper icon set.

Regards,
Michael
![selection_001](https://cloud.githubusercontent.com/assets/5689764/18645745/ad830a3c-7eae-11e6-9504-f5de8dc74d43.jpg)

**Comment by pbek** [comment]
Thank you for your kind words! I like to have all notes in folders. ^_^

QOwnNotes uses free desktop theme icons, if your theme has no icon of a certain kind it falls back to the bundled (Breeze) icons.

Does that answer your question?

**Comment by michael-rowe** [comment]
Thanks for the quick response. I have Breeze installed but only some of the displayed icons are from that set. Is there a way to "force" QownNotes to use Breeze only?

**Comment by pbek** [comment]
I'm not aware of a way to do that without removing the theme icon for every icon in QOwnNotes. Every free desktop theme can define a fallback, you could define that in the theme file of your theme, like in <https://github.com/pbek/QOwnNotes/blob/develop/src/icons/qownnotes/index.theme>. I wonder why they didn't do that if they theme has not all theme icons...

**Comment by pbek** [comment]
But I'm not sure to what icon set you should define it. I wonder how other applications handle this...

**Comment by pbek** [comment]
What happens to the icons if you enable the dark mode in the interface settings of QOwnNotes?

**Comment by michael-rowe** [comment]
As far as I can tell, enabling dark mode does nothing to the UI or the icons. Don't stress about this. The icons that display are fine...I can easily see what they do. It's not like they're completely missing.

**Comment by pbek** [comment]
So the desktop theme has highest priority. If I find a way to turn theme icons off, I'll let you know.

**Comment by michael-rowe** [comment]
Just to let you know, the icons change to the proper icons when Dark mode is enabled (I didn't know that the app needs to be restarted for this change to happen...and it's taken me this long to restart it). When I switch back to the Light mode then the icons change back. Again, not serious, just wanted to let you know that Dark mode does change the icons.

**Comment by pbek** [comment]
> the icons change to the proper icons when Dark mode is enabled

Thank you for letting me know, I will take a look at this.
Just to confirm, in dark mode you see dark mode icons (kind of inverted), right?

> maybe you could include some text in the option that alerts the user

There already is a tooltip for that...

**Comment by michael-rowe** [comment]
Yes, the dark mode icons appear in dark mode, and they're all from the same icon set. When I switch back to Light mode, the icons seem to come from two different sets.

**Comment by pbek** [comment]
ok, thank you!

**Comment by pbek** [comment]
## 16.10.1
- there now is a new checkbox `Use internal icon theme instead of system
  icon theme` in the interface settings

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by michael-rowe** [comment]
Thanks, the icons show up perfectly with the new setting enabled.

**Comment by pbek** [comment]
Great, thank you for confirming!
