### ISSUE TITLE
Disable usage tracking dialog is not translatable.

### ISSUE THREAD

**Issue by piyo-gh** [pbek/QOwnNotes#333]
It seems that there is no translation entry for *Disable usage tracking* dialog.

![qownnotes_2016-09-18_21-53-26q](https://cloud.githubusercontent.com/assets/18474085/18777091/55bba7e4-81a8-11e6-9f48-1cdb43e83f63.png)

**Comment by pbek** [comment]
You are right! Thank you for reporting! The strings can now be translated.

**Comment by pbek** [comment]
## 16.09.14
- added some missing translations

There now is a new release, could you please test it and report if the new features work for you?
