### ISSUE TITLE
RTL support 

### ISSUE THREAD

**Issue by yousufinternet** [pbek/QOwnNotes#335]
Hi, 
Is there any way to add a RTL (right to left) text in the mark down format? , I have no problem displaying RTL text (Arabic, Hebrew, Persian..etc) correctly in the editor, but the RTL text appears LTR in the md viewer, so my current setup is hiding the md viewer, and using the editor only.

**Comment by pbek** [comment]
Can you please post an arabic (or something else with RTL) note, so I have something to test with.

**Comment by pbek** [comment]
I think I managed to do it myself.

## 16.09.16
- added RTL support for the markdown preview
    - you can turn it on in the interface settings

**Comment by yousufinternet** [comment]
Sure, Thanks for the quick reply! 

مرحباً هذه ملاحظة تجريبية this is a test note   شكراً لفريق كـأون نوت 

It's not showing currectly here on this site either. 
this behaviour becomes especialy troubling when having LTR text in between the RTL text. 

you can see in the screenshot the deffirence between the display in the md preview pane and the editor, the correct display is the editor. 

![screenshot from 2016-09-27 18-44-00](https://cloud.githubusercontent.com/assets/9606220/18880994/7458bfec-84e2-11e6-80db-e3aa3fe39ba2.png)
![screenshot from 2016-09-27 18-43-48](https://cloud.githubusercontent.com/assets/9606220/18881002/78ec1a86-84e2-11e6-847a-32fc2da6f90b.png)

Thanks in advance

**Comment by yousufinternet** [comment]
Hey thank you very much. 
but I was thinking about something more "automatic", because I also have many LTR notes, and it might be just a little bit annoying to swich the view every time for each note. 
but if it is not possible this is very ok with me, and thank you very much for the quick help.

**Comment by pbek** [comment]
I had to set specific CSS styles in the note view (`text-align: right; direction: rtl;`), like it has to be done in a webpage. I currently see no way how that could be detected.

**Comment by pbek** [comment]
If you find some Qt and/or HTML/CSS specific information, please let me know.

**Comment by yousufinternet** [comment]
Thats ok.
 
I think in Qt you can add buttons for making the text RTL or LTR while editing the note. 

I used to use everpad (Evernote thirdparty linux client), and I had to tweak their note editor by adding the following code: 

            (QWebPage.SetTextDirectionLeftToRight,
                ['format-text-direction-ltr', 'everpad-text-direction-ltr']),
            (QWebPage.SetTextDirectionRightToLeft,
                ['format-text-direction-rtl', 'everpad-text-direction-rtl']),

to the editing toolbar to show RTL and LTR buttons while editing the note, if that is possible here it would be great too.

**Comment by pbek** [comment]
You would want to click a RTL button for ever note with RTL text? It would be far more convenient to do that automatically.

**Comment by yousufinternet** [comment]
No, I want to be able to write RTL notes or RTL paragraphs whithin notes, when I view these notes later they would appear RTL just like any other mark down formating stored in the note. 

I guess nothing automatic could be done for my previous notes, or it is a bit complicated.

**Comment by pbek** [comment]
I could only imagine that maybe you can find some magic CSS style (that is also supported by QTextBrowser) that is able to detect that automatically. Surely you can't be the first with that problem.

**Comment by yousufinternet** [comment]
I will do more research when I find time :) 

I found some interesting things on this link

http://stackoverflow.com/questions/2258028/rtl-in-markdown

**Comment by pbek** [comment]
Thank you, QTextBrowser doesn't support JavaScript... :/

Meanwhile there is the new release of QOwnNotes...

**Comment by pbek** [comment]
I will close this issue until there is more information.
