### ISSUE TITLE
Possibility to import TomBoy Notes?

### ISSUE THREAD

**Issue by Weej1** [pbek/QOwnNotes#336]
TomBoy Notes is a note taking app primarily meant for GNOME and therefore Linux however it's been ported to windows too. It's great for what it is - basically a modular sticky note look alike with a basic Wiki-ish Syntax. However since it hasn't been worked on in a few years (largely being superseded by Gnotes..which just doesnt work well with DropBox - an issue that TomBoy also shares but not as badly) I thought it was high-time I ported all my notes over to something that *is* being worked on and is cloud friendly (No guesses here ;) ). All the notes are in an XML format however, since I saw the evernote importer I decided to request one for TomBoy Notes too.

While on that there's also CherryTree which saves notes in XML too. However that's probably for another issue ticket :smile: .

**Comment by pbek** [comment]
I guess there are *some* more Evernote users out there... :)
Can you please post some example notes that are using common formattings / features, so I can take a look at the format.

**Comment by pbek** [comment]
I will close this issue until there is more information.

**Comment by sierracircle** [comment]
Not sure if this is still an open idea, but I am amongst the people who have hundreds of Tomboy notes. I would love a way to import them and have the xml formatting converted.
I am attaching one note, but can add more if needed.

[15b4ee2a-2365-4271-b898-f3c3a1244422.txt](https://github.com/pbek/QOwnNotes/files/5314500/15b4ee2a-2365-4271-b898-f3c3a1244422.txt)
