### ISSUE TITLE
setting to dump attachments in the same folder as the note (portability)

### ISSUE THREAD

**Issue by mlinchitstest** [pbek/QOwnNotes#337]
the current behavior is incompatible with almost every markdown editor out there, which support either absolute paths or relative paths so long as the file is in the same folder. they dont support ```file://media/attachment.png```, only ```file:/attachment.png```. A separate media foder may help keep things tidy, but it doesn't help portability. Would you consider adding an option to just dump the attachments into the same folder as the note?

**Comment by pbek** [comment]
Thank you for your suggestion, but currently a lot depends on it that we have a distinct media folder. And `file:/attachment.png` wouldn't event be recognized as url by Qt's QUrl.
