### ISSUE TITLE
Autokey substitution different for Qownnotes

### ISSUE THREAD

**Issue by MBuchaus** [pbek/QOwnNotes#339]
I use Autokey.py3 in arch.  It fills many needs and works great across the system.  I do however notice weirdness with Qownnotes. When using this script
<pre>
from datetime import datetime
output = "{:%H:%M}".format(datetime.now())
keyboard.send_keys(output)
</pre>
Qownnotes will repeatedly place a semicolon where a colon is intended.
the time is substituted  to  something like  10;11 
Where the rest of the system will show   10:11   

Would anyone have any insight on this.  Every other text editor vim gvim  atom sublime kedit kate gedit etc.  replace with the '  :  '

**Comment by pbek** [comment]
> Qownnotes will repeatedly place a semicolon where a colon is intended.

Can you please explain what exactly you are talking about?:)

**Comment by MBuchaus** [comment]
Autokey is a abbreviation expansion prog for linux  like  textexpander.   when i type ttime<space> it replaces the text with the current time of day.   this works correctly through the rest of the system..  it does work correctly in qon as well but in the editor it puts a ; for the :   repeatably   I have just been going back and replacing the ; with : but that defeats the purpose for the productivity increase that autokey is intended to provide.  
The script in the prev post is python by the way.   I have another subst that reacts the same way with : and ;  it's not a blocker or anything.. but I'm stumped with trying to figure out why it's happening.   and Only happening in QON.

**Comment by pbek** [comment]
> it replaces the text with the current time of day

...like `Ctrl + T` does in QOwnNotes?
plus I guess you could also do that with the QOwnNotes scripting engine...

> with : and ; 

that doesn't ring a bell for me, I've no idea what that might happen

**Comment by MBuchaus** [comment]
Well I learned a new key shortcut.. Nice.  Never looked that one up..  ahh yeah it does full date and time.  I guess I could script up just the time and assign it to the same key..   that key doesn't work throughout the rest of the system though..   Nice thought.

**Comment by pbek** [comment]
<http://www.qownnotes.org/shortcuts/QOwnNotes> is your friend. ;)

**Comment by pbek** [comment]
And this is just for you too:

## 16.09.17
- there a now is a new scripting method `script.noteTextEditWrite(text)`
  to write text to the note text edit
    - for more information please take a look at the 
      [noteTextEditWrite documentation](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/README.md#write-text-to-the-note-text-edit)
- there a now is a new scripting method `script.noteTextEditSelectedText()`
  to read the selected text from the note text edit
    - for more information please take a look at the 
      [noteTextEditSelectedText documentation](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/README.md#read-the-selected-text-in-the-note-text-edit)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you (if you are using the new scripting methods)?

**Comment by pbek** [comment]
I will close this issue until there is more information.
