### ISSUE TITLE
also tried to build with QT 

### ISSUE THREAD

**Issue by wayneward** [pbek/QOwnNotes#34]
i get the attached screen shot im on ubuntu 14.04 
and must be missing a devel package ive had to install quite a lot to get to this stage
![workspace 1_104](https://cloud.githubusercontent.com/assets/11428255/12514902/99bd9250-c11d-11e5-84de-e0d37dfc3bc1.png)

**Comment by pbek** [comment]
Hi @wayneward , thank you for your report!

Did you follow the instructions on how build QOwnNotes on <http://www.qownnotes.org/installation>? It looks like you didn't checkout the git submodules or did I miss to mention something?

**Comment by pbek** [comment]
I assume this issue can now be closed, please just reopen it if there was something else.
