### ISSUE TITLE
Swap sub-panes in "tag-pane under navigation pane" mode

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#340]
I'm using "tag-pane under navigation pane" mode most of the time now and having note list on the top and sub-folders on the bottom is frustrating a bit. Tag/sub-folders are grouping methods so they logically should be to the left or to the top of the items they group.

Could you swap tag/sub-folders and note list/navigation for this mode?

**Comment by pbek** [comment]
Isn't that mode then doing something completely different?

**Comment by Maboroshy** [comment]
What you mean?

**Comment by pbek** [comment]
Is you were saying, the mode is called "tag-pane under navigation pane" and was created for a user request <https://www.reddit.com/r/linux/comments/4xto4y/4_open_source_alternatives_to_evernote/#thing_t1_d6jlppu> in version 16.08.15.

**Comment by Maboroshy** [comment]
I'm not quite sure that the user is about having tags specifically below the note list. More about having all in the same pane. 

It's just against typical UI patterns having it at the bottom. Try using this mode for a while, if that won't feel awkward for you then I'm wrong.

I'm not insisting on keeping old mode name. :grin:

**Comment by pbek** [comment]
I'm trying to get the original feature requester's consent at <https://www.reddit.com/r/linux/comments/4xto4y/4_open_source_alternatives_to_evernote/d860gce>

**Comment by pbek** [comment]
The big question is, are you more focused on your notes (they currently are on top) or on your tags (you want them at the top along with the note folders)... After the change the order would be: note sub-folders, tags, note folder selector (if turned on), note list, navigation

**Comment by Maboroshy** [comment]
Personally I don't think that the top of the screen gets more focus than the bottom.

It's the center of the screen that gets more focus, it's where the note text is. Anything at the sides is barely a focus point, especially on modern wide screens. So for me both halves of the side pane gets same amount of focus.

The thing is most of the app users use left-to-right direction writing systems. That means that they expect items on the left to lead items on the right and items at the top to lead items at the bottom. 

That's why having higher level list at the bottom feels awkward - you always expect to see changes below it or to the right of it. Anything other is extra work for the brain. It's not that much of a work but you do it every time you use UI.

**Comment by pbek** [comment]
## 16.10.0
- the menu entry `Show tag pane under navigation pane` was replaced by
  `Show note list under tag pane` where note list and tag pane are swapped

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment]
Works great. Feels more natural now.

**Comment by pbek** [comment]
I'm happy if you are happy. :smile_cat: Thank you for testing!
