### ISSUE TITLE
Rendering problems in the preview

### ISSUE THREAD

**Issue by michael-rowe** [pbek/QOwnNotes#341]
This is something that I only noticed recently when I went to the markdown notes you include in the default install. Have a look at the screenshots attached and let me know if this is how the markdown is supposed to render in the preview window. It's pretty unreadable.

As far as I know, I haven't changed anything that would affect this and I can't find a setting anywhere to adjust how certain elements are rendered.

![selection_001](https://cloud.githubusercontent.com/assets/5689764/18948002/a26b3d16-8635-11e6-82e5-aefb4b4663d5.jpg)
![selection_002](https://cloud.githubusercontent.com/assets/5689764/18948010/a9492a62-8635-11e6-82c5-c816a9a01f01.jpg)

**Comment by pbek** [comment]
It seems you have `Optimize preview colors for dark mode desktop themes` turned on in the interface settings. You guess you want to turn that off.

Does that answer your question?

**Comment by michael-rowe** [comment]
Thank you. All sorted.

**Comment by pbek** [comment]
Great ;)
