### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by JoseVacas** [pbek/QOwnNotes#342]
Hi, I have found that for some versions CPU usage is very high

**Comment by pbek** [comment]
What are "some versions"? When is the CPU usage high?

**Comment by JoseVacas** [comment]
For five or six days ago.I could not see the version number

**Comment by JoseVacas** [comment]
[http://pix.toile-libre.org/upload/original/1475149134.png](http://pix.toile-libre.org/upload/original/1475149134.png)

**Comment by pbek** [comment]
How long does it need 100% cpu? Are you using ownCloud tasks with QOwnNotes? Do you get anything in the log dialog? Can you please post the dump from the debug settings.

**Comment by JoseVacas** [comment]
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `jue. sept. 29 15:30:23 2016`
**Version**: `16.09.17`
**Build date**: `Sep 28 2016`
**Build number**: `245`
**Platform**: `linux`
**Operating System**: `Ubuntu 16.04.1 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.5.1`
**Qt Version (runtime)**: `5.5.1`
**Portable mode**: `no`
**Qt Debug**: `0`
**Locale (system)**: `es_ES`
**Locale (interface)**: `es`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `21`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**serverVersion**: *empty*
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `predeterminado`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/jose/configuraciones/documentos/qownnotes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**activeNoteSubFolder name**: *empty*

## Settings

**AboutDialog/geometry**: `<binary data>`
**DistractionFreeMode/isEnabled**: `false`
**DistractionFreeMode/mainSplitterSizes**: `<binary data>`
**DistractionFreeMode/menuBarGeometry**: `<binary data>`
**DistractionFreeMode/menuBarHeight**: `0`
**DistractionFreeMode/windowState**: `<binary data>`
**Editor/CurrentSchemaKey**: `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**LastUpdateCheck**: `2016-09-29T15:29:36`
**LinkDialog/geometry**: `<binary data>`
**LogDialog/showAtStartup**: `false`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `24`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `Ubuntu,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl**: `false`
**MainWindow/showRecentNoteFolderInMainArea**: `false`
**MainWindow/windowState**: `<binary data>`
**PasswordDialog/geometry**: `<binary data>`
**PiwikClientId**: `<hidden>`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**ShowSystemTray**: `false`
**SortingModeAlphabetically**: `false`
**UpdateDialog/geometry**: `<binary data>`
**allowDifferentNoteFileName**: `false`
**allowOnlyOneAppInstance**: `false`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `false`
**appMetrics/notificationShown**: `true`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**customNoteFileExtensionList**: *empty*
**darkMode**: `true`
**darkModeColors**: `true`
**darkModeTrayIcon**: `false`
**defaultNoteFileExtension**: `md`
**demoNotesCreated**: `true`
**disableAutomaticUpdateDialog**: `false`
**externalEditorPath**: *empty*
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**interfaceLanguage**: `es`
**itemHeight**: `19`
**mainSplitterSizes**: `<binary data>`
**mainSplitterState-0-0-1-0**: `<binary data>`
**mainSplitterState-0-1-0-0**: `<binary data>`
**mainSplitterState-0-1-1-0**: `<binary data>`
**markdownHighlightingInterval**: `200`
**markdownViewEnabled**: `true`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `0`
**noteEditPaneEnabled**: `true`
**noteListSplitterState**: `<binary data>`
**noteSaveIntervalTime**: `10`
**notesPath**: `/home/jose/configuraciones/documentos/qownnotes`
**notifyAllExternalModifications**: `false`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: *empty*
**ownCloud/todoCalendarBackend**: `0`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloud/userName**: *empty*
**recentNoteFolders**: `/home/jose/ownCloud/Notes`
**savedSearches/noteFolder-1**: `Note 2016-09-27T09.19.45, Note 2016-09-20T11.22.16, Note 2016-09-05T11.44.41, Note 2016-08-31T10.41.11, Note 2016-08-20T19.27.08, Note 2016-08-18T13.59.24, Note 2016-08-18T12.28.14, Note 2016-08-13T11.57.12, Note 2016-08-13T01.51.03, Note 2016-08-08T01.11.45, Note 2016-08-04T14.28.56, Note 2016-08-02T07.39.41, Note 2016-08-01T12.04.22, Note 2016-07-27T21.17.40, Note 2016-07-25T16.44.28, Note 2016-07-25T09.03.52, Note 2016-07-15T15.28.03, Note 2016-07-14T10.09.30, Note 2016-07-12T20.48.06`
**showMenuBar**: `false`
**showStatusBar**: `true`
**skipVersion**: `16.09.15`
**tagFrameSplitterState**: `<binary data>`
**verticalNoteFrameSplitterState**: `<binary data>`

**Comment by JoseVacas** [comment]
When i open QownNotes from Terminal, i get this out.
`Warning: QFSFileEngine::open: No file name specified ((null):0, (null))
`

**Comment by pbek** [comment]
How long does it need 100% cpu and when does that happen? Do you get anything in the log dialog?

**Comment by JoseVacas** [comment]
From the start

**Comment by pbek** [comment]
Can you please answer all questions? :) So far I have no clue what's happening.

**Comment by JoseVacas** [comment]
Sorry for my English. Where can i find the logs?

**Comment by pbek** [comment]
In the menu, Window / Log window. Please turn anything on and restart QOwnNotes...

**Comment by JoseVacas** [comment]
The log shows nothing.

**Comment by pbek** [comment]
Hm, I'm not sure I can help you...

The only thing that comes into mind is that you use gdb to start QOwnNotes and see if you can get something out of it like in <https://github.com/pbek/QOwnNotes/issues/319>

You could also try to build QOwnNotes yourself: <http://www.qownnotes.org/installation#building>

**Comment by JoseVacas** [comment]
Ok. Thanks. I'll try something.

**Comment by pbek** [comment]
Just let me know if you can find something out!
