### ISSUE TITLE
USE_SYSTEM_BOTAN broken

### ISSUE THREAD

**Issue by chronitis** [pbek/QOwnNotes#344]
The source tree includes support for using external libbotan instead of the vendored copy, but setting `USE_SYSTEM_BOTAN=1` currently breaks the build, since the `#ifdef` block this option enables doesn't contain enough header includes. Fixed by:

```
--- a/libraries/botan/botan.h
+++ b/libraries/botan/botan.h
@@ -22,6 +22,8 @@
 #include <botan/pubkey.h>
 #include <botan/rsa.h>
 #include <botan/ui.h>
+#include <botan/pbkdf2.h>
+#include <botan/sha160.h>
 #else
 
 #include <QtGlobal>
```

**Comment by pbek** [comment]
Which source tree includes support for using external libbotan? What build breaks?
If you want to propose changes would you please care to post a pull request and explain why you want it changed?

**Comment by chronitis** [comment]
Sorry, the original report was a bit unclear.

`src/libraries/botan/botan.pri` checks a qmake variable `USE_SYSTEM_BOTAN`, and if set tries to link against the system version of `libbotan` instead of compiling the copy of `libbotan` contained in that directory.

However, if you set the variable and try and build the project (`qmake; make` on a system with botan headers available) you get a bunch of undefined symbol errors - the above patch adds the missing headers to the list used when `USE_SYSTEM_BOTAN` is set - I'll make a pull request.

**Comment by pbek** [comment]
Very interesting. As far as I remember I took the pre-assembled botan library from qtcreator, seems like they will have the same problem then! ;) Thank you for reporting and fixing!
