### ISSUE TITLE
Your CalDAV server didn't reply anything!

### ISSUE THREAD

**Issue by treborxy** [pbek/QOwnNotes#346]
I want to store tasks on a caldav - server (baikal). When trying to connect with it, QOwnnotes responds with "Your CalDAV server didn't replay anything!". What am I doing wrong?
![auswahl_045](https://cloud.githubusercontent.com/assets/19653937/19016224/5a82db18-8814-11e6-8c62-555308275441.png)

**Comment by pbek** [comment]
Did you use an url where the CalDAV server returns a list of calendars? I would need a test account to validate that...

**Comment by treborxy** [comment]
Hi Patricio,
I sent a mail to patrizio@bekerle.com - thanx a lot!
Robert

**Comment by pbek** [comment]
When I tried to use the credentials you sent with basic auth in Postman to test the PROPFIND-requests I got this as response:

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
    <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
    <s:message>No digest authentication headers were found</s:message>
    <s:sabredav-version>1.8.7</s:sabredav-version>
</d:error>
```

Does your server support basic auth?
And something else, the url you sent me was `http://dav...`, but in your screenshot you used `https://`. I didn't get any response with https...

**Comment by pbek** [comment]
In case you want to try the requests yourself: <https://www.getpostman.com/>

**Comment by treborxy** [comment]
Yes, baikal supports basic auth. 

Sorry, https:// is right of course. 

Up to now I used a self-signed certificate, which might have caused problems. Now I switched to a certificate by "Let's Encrypt", but for me it doesn't work still: first errormessage is 'Username or Password wrong', next message like show in my first screenshot.

Could you please test again with this non-self-signed-certificate?

**Comment by pbek** [comment]
Sorry, no change. I still get `No digest authentication headers were found` with https in Postman.

**Comment by pbek** [comment]
I will close this issue until there is more information.
