### ISSUE TITLE
Notes disappering

### ISSUE THREAD

**Issue by mlinchitstest** [pbek/QOwnNotes#347]
Sometimes, notes are not saved after you close the program.  Seems to happen when you use subfolders. Kinda weird and hard to diagnose. I don't really know where to look. Where are the log and preferences files stored. Checked appdata on Windows, can't see anything there. Had this happen about 6 times last month. (using QOwnNotes - version 16.09.6, earlier versions had the same problem)

**Comment by pbek** [comment]
So are notes disappearing (like the issue name says) or are notes not stored? Can you please post the dump of your debug settings. How are you closing the app?

**Comment by mlinchitstest** [comment]
Not stored. The app closed normally.

**Comment by pbek** [comment]
Can you please post the dump of your debug settings. Please describe how you are closing the app.

**Comment by mlinchitstest** [comment]
sorry to be stupid, but how?

**Comment by pbek** [comment]
examples may be

- I press keyboard shortcut XYZ
- I click in the Note-menu and click XYZ
- I click on the X on the top right of the window

And can you please post the dump of your debug settings so that I finally may be able to reproduce what you are doing.

**Comment by mlinchitstest** [comment]
I mean how would you obtain the dump? (Closing the window is not a problem)

**Comment by pbek** [comment]
Settings / Debug

**Comment by pbek** [comment]
And I didn't suppose that closing QOwnNotes was a problem, I want to know from you HOW you closed it when the notes wasn't stored.

**Comment by mlinchitstest** [comment]
I just close it via the x on the window border
https://gist.github.com/mlinchitstest/e3ca8f6b18df98cc4e3caa7b81e2825e

**Comment by pbek** [comment]
I see you are using an old version of QOwnNotes, can you please update to the latest version and try to reproduce your problem again.

**Comment by pbek** [comment]
So far I wasn't able to reproduce your problem under Windows 10 with note subfolders.
But I see you are showing the system tray icon. If you click "X" in that mode the app will not be closed but just minimized to the system tray. Are you sure you have quite the app?

I see your note save interval is 1 sec. That's a bit low. What happens if you turn that up to 5 sec?

**Comment by mlinchitstest** [comment]
> I see your note save interval is 1 sec. That's a bit low. What happens if you turn that up to 5 sec?

I think that may be the answer. I guess the closing issue is something to look at too. Thing is — this happens so rarely that it's hard to diagnose.

**Comment by pbek** [comment]
I will close this issue until there is more information. ;)

**Comment by mlinchitstest** [comment]
no problem
