### ISSUE TITLE
Paste a note on any program into right click option

### ISSUE THREAD

**Issue by ycofr** [pbek/QOwnNotes#349]
Hi !
Is there any chance to Qownnotes to have same features like this module ?
https://addons.mozilla.org/fr/firefox/addon/clippings/
Paste any notes (text+image) on any program (shell, firefox etc ? )

Thanks for your time

**Comment by pbek** [comment]
Can you please describe in more detail what you are expecting?

**Comment by ycofr** [comment]
For example to answer me for more details, you have just to right click on mouse, looking for your note "describe more" When you click on you have your full note paste. Clippings do this but only on firefox and thunderbird. I am looking for this on any program like terminal for example (cross platform)
You can test clippings https://addons.mozilla.org/fr/firefox/addon/clippings/ 
![test](https://cloud.githubusercontent.com/assets/22642165/19144740/9b94ca2c-8bab-11e6-9d12-a067801e8839.jpg)

**Comment by pbek** [comment]
And where does QOwnNotes come into play? If you are talking about creating new notes from a Web Browser, that most probably will not work (as already discussed in #330).

**Comment by ycofr** [comment]
I'm talking about fast respond, fast command, pre-filled form, made on QOwnnotes. Ok, for thanks for your time.

**Comment by pbek** [comment]
Are you talking about the ability to create new notes with a button / menu entry? Or filling custom text into existing notes? (both already works)

**Comment by ycofr** [comment]
Not really : existing notes to form, with right clicks mouse. If you have firefox, test clippings module to really see what i'm talking about.

**Comment by pbek** [comment]
I think I still don't understand what you are talking about. :)
There are no forms in QOwnNotes.
Or do you want a Firefox extension that takes its data from notes to fill out data in html forms in Firefox? That wouldn't have much to do with QOwnNotes, since the notes are simple markdown files...

**Comment by ycofr** [comment]
Arf, my english is not enought good.
Saves and manages frequently-entered text for later pasting into web page forms, txt etc.

Have a right click mouse on any program with list of qOwnNote note
to paste quickly

**Comment by pbek** [comment]
That sounds like a new standalone app what hasn't much to do with QOwnNotes (because it could access the note files directly) and it wouldn't be easy to do that platform independently. I don't know if you can hijack the operating systems context menu... Every operating system handles that differently...

**Comment by pbek** [comment]
Sorry I was of not much service.
