### ISSUE TITLE
Would it be possible to integrate GIT as backup service?

### ISSUE THREAD

**Issue by fourtytwo** [pbek/QOwnNotes#350]
Right now i basically have my  ~/QownNotes folder tracked by git. And i constantly push it etc... wouldn't it be great if in addition to ownCloud you could also use Git?

**Comment by pbek** [comment]
That's an idea I already had a while ago. :) But basically on would have to implement a fully fledged git client, with merging, conflict management and so on to achieve this. That's a bit of an overkill.

But you could do a lot with the already implemented scripting engine.
<https://github.com/pbek/QOwnNotes/tree/develop/doc/scripting>

You could for example create a timer (visit <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/example.qml>) that does a commit, push and pull once in a while. You can call the git client with the `startDetachedProcess` command.

For some special commands you want to execute you could create a custom action (<https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/custom-actions.qml>) that creates some buttons to press for you.

What do you think? Are you up to the challenge?

**Comment by pbek** [comment]
I will close this issue until there is more information.
