### ISSUE TITLE
Adding the ability to Star or Favourite notes

### ISSUE THREAD

**Issue by michael-rowe** [pbek/QOwnNotes#351]
I've just imported all 800 of my notes from Evernote (thank you again for adding this feature) and now I'd like to add something like shortcuts to the notes that I use most often.

Evernote had a feature where you could Star notes, which added them to a list that is a bit like bookmarks for notes. I know that this would be possible to do now by tagging the note but I think it would be awesome if the toolbar had a Star icon that you could quickly use to mark a note as one that you want access to quickly.

The interface could work a bit like how Chrome bookmarks work. Just a thought...

**Comment by pbek** [comment]
Yes, there really are tags for that. Maybe it would be enough to implement a scripting-method where you can add a tag to the current note. Then you could create a custom action (as button in the toolbar, you also can add a keyboard shortcut to it) to add a "starred" tag.

How does that sound to you?

**Comment by Maboroshy** [comment]
I add "!" to beginning of a note name, so it's always on top of the list. Pity it doesn't work for sub-folders since they show unsorted.

**Comment by michael-rowe** [comment]
I think that I can make do with maboroshy's suggestion of renaming commonly used notes for now. If you want to add the scripting option to a to do list for later that would be cool, but not essential.

**Comment by pbek** [comment]
You would need to sort the notes alphabetically to make this work.

**Comment by Maboroshy** [comment]
I'm not that clever when it comes to QML but what should I put to in-app script to rename a note?

**Comment by pbek** [comment]
What is it you are trying to achieve?

**Comment by Maboroshy** [comment]
Custom action script to add star to a note name for Michael.

**Comment by pbek** [comment]
... by renaming the note? Don't you want to use a "star" tag?

**Comment by michael-rowe** [comment]
I thought that it would as a "star" or "favourite" tag.

**Comment by pbek** [comment]
What are we currently talking about? :)

**Comment by michael-rowe** [comment]
I was just saying that if you're going to make a script that does something to highlight a note as being important, it should add a tag to the note rather than rename it. 

Or am I missing something?

**Comment by pbek** [comment]
Yes, a script that adds a tag was my suggestion. A command to add tags has still to be implemented.

**Comment by Maboroshy** [comment]
Tagging is not a highlighting, it's putting note to kind of a list. I mean you can't quickly pick tagged note out of all notes list. But you can pick a specifically "renamed" one.

**Comment by pbek** [comment]
If you really want to go the renaming route...
<https://github.com/pbek/QOwnNotes/tree/develop/doc/scripting>
There is a command to get the current note and from that you can get it's path. And then you could call a linux command to rename the file. But I'm not sure if just renaming the note file will resolve your wishes...

**Comment by michael-rowe** [comment]
I thought you would search for ”Starred" notes, which would filter the notes with that tag.

**Comment by Maboroshy** [comment]
I knew external command route but hoped to get cross-platform solution. But since Michael goes for tagging linux-only solution will do for me, it's even more favourable for me.

**Comment by Maboroshy** [comment]
It took me quite a lot of time but I still haven't figured out how to pass multiple command arguments to `script.startDetachedProcess`. 

I tried 
```
var arguments = fullFileName + " " + newFileName;
script.startDetachedProcess("mv", [arguments]);
```
```
arguments: [fullFileName,newFileName];
script.startDetachedProcess("mv", [arguments]);
```
No avail. 
Can't figure out correct syntax from your and QML docs.

**Comment by pbek** [comment]
What's about:

```JavaScript
var arguments = [fullFileName, newFileName];
script.startDetachedProcess("/bin/mv", arguments);
```

**Comment by Maboroshy** [comment]
That did it! I still too dumb to understand why var is assigned as array but I can live with that.

However launching the script brings up "current note deleted" dialog which is immune to "don't track" options. I also have to manually refresh note list for new (renamed) note to appear. That's too much for one click action I wanted to make.

**Comment by pbek** [comment]
> That did it! I still too dumb to understand why var is assigned as array but I can live with that.

the system command takes an array for the parameters and it makes it easier to escape certain parameters

> immune to "don't track" options

if the current note is gone something **has** to happen :)

**Comment by Maboroshy** [comment]
I understand about using array but I was surprised it's made by `var`. I thought it's a `list` thing in QML.

The logic is correct, but that means no `mv` in scripts. There's still `handleNoteTextFileNameHook` route left but it won't be as straightforward. I need to figure out how to force the hook with available script actions.

**Comment by pbek** [comment]
> I understand about using array but I was surprised it's made by var. I thought it's a list thing in QML.

It's just JavaScript.

> handleNoteTextFileNameHook

You cannot call a hook in a script. Unfortunately I've yet no idea what would make your endeavor easier without some major changes in QOwnNotes...

**Comment by Maboroshy** [comment]
I'll cease for renaming with "!' then. Ability to prepend note names with different markers with a single click looked promising though. At least I can use gained experience to pass current note file name to Bash-note.

**Comment by pbek** [comment]
## 16.10.5
- added a new scripting method `tagCurrentNote()` to tag the current note
    - there is an example for creating a custom action to add a tag
      `favorite` to the current note at
      [favorite-note.qml](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/favorite-note.qml)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by pbek** [comment]
## 25.12.5

- Added ability to **mark notes as favorite** (for [#351](https://github.com/pbek/QOwnNotes/issues/351))
  - Right-click on a note and select "Mark as favorite" or "Unmark as favorite"
  - Favorite notes are displayed with a star icon in the note tree widget
  - Favorite notes are automatically positioned at the top of the note list
  - Favorite status is stored per note folder in local settings
  - The feature uses subfolder path and filename to identify notes (persistent across restarts)
  - Works with all sorting modes (alphabetical, by date)
  - **Automatic migration**: When a note is moved, renamed, or its headline changes
    (triggering auto-rename), favorite status is preserved
  - **Automatic cleanup**: When a note is deleted, it's removed from the favorites list
  - **Periodic cleanup**: Non-existent notes are automatically removed from favorites on note list refresh

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you? In case anyone is still here.... 😊
