### ISSUE TITLE
Reset note text size also resets default font size to 9

### ISSUE THREAD

**Issue by piyo-gh** [pbek/QOwnNotes#353]
How to reproduce:
1. Choose `Settings / Editor fonts & colors / Default font`.
1. Set default font size to 16. (for example) and click OK.
1. Choose `Window / Reset note text size`.
1. Choose `Settings / Editor fonts & colors / Default font` again.

Result:
Default font size is reset to 9.
Note editor font size is changed to 9.

Expected result:
Default font size should not be reset to 9.
Note editor font size keeps 16.

**Comment by pbek** [comment]
Thank you for reporting, but what you are describing is the expected behaviour. The note default text size should be reseted. Why do you think otherwise?

**Comment by piyo-gh** [comment]
Oh, thank you for explanation.
Then closed.
