### ISSUE TITLE
Database location when running portable

### ISSUE THREAD

**Issue by CTrauma** [pbek/QOwnNotes#354]
If I run QOwnNotes with the --portable switch I can't set my notes location outside of the install location.

So if I have my notes stored in a sub directory of my OwnCloud sync folder, which is located on another drive, QOwnNotes tries to concatenate the local Data directory path with the path to my OwnCloud sync folder and fails to be able to read the sqlite db file.

Is this intentional? I expected the path to the notes folder to be absolute and not relative.

**Comment by CTrauma** [comment]
as an FYI I'm using this client to sync 
https://github.com/naderi/owncloud-client-portable

**Comment by CTrauma** [comment]
By the look of the code here:

https://github.com/pbek/QOwnNotes/blob/fa929e9dc5930d5e9db64e97ad52f542a4e93692/src/utils/misc.cpp#L341

this looks to be how it is designed to work, in that case can we get a checkbox to force the path to be absolute to allow notes paths outside of the portable install?

**Comment by pbek** [comment]
> Is this intentional? I expected the path to the notes folder to be absolute and not relative.

I'm sorry, this is intentional. Otherwise the portable mode makes no sense because if you are carrying QOwnNotes plus its notes on an usb stick and the drive letter (e.g. in Windows) changes every time your notes will not be found.

**Comment by pbek** [comment]
Why do you want to use portable mode with absolute paths? Why do you use the portable mode?

**Comment by CTrauma** [comment]
I use portable mode because I don't want to write to APPDATA and store all my data on my external drive. All the applications I use I have set up the same way. I'm using the portable edition of the OwnCloud sync client to sync to a folder on a truecrypt volume whose drive letter never changes and is where I store all my data which then gets synced though a personal VPN running on a raspberry Pi to my home NAS. Any time I need a static drive letter I either create a truecrypt volume or use subst to create it. This is the same way that I use EverNote and CherryTree.

I just had a successful build of QOwnNotes with mingw64 on Windows so I can add the feature myself, but I just thought I would ask first if it was by design before I go mucking about in the code. I still think there is a use case where someone would want to keep all settings information local to the install and have their notes elsewhere, even if it is not on another drive. Also my USB drive letter has not changed in about 10 years because I intentionally set it, so that bit doesn't effect me.

**Comment by CTrauma** [comment]
I ended up adding a  --abs_notes_path switch that I can check in prependPortableDataPathIfNeeded and it works like a charm

```
QString Utils::Misc::prependPortableDataPathIfNeeded(QString path) {
    if (isInPortableMode() && !isUsingAbsNotesPath()) {
```

**Comment by pbek** [comment]
Sounds like a good solution. Do you want to create a pull requests? If you do, could you please name that parameter something like `--use-absolute-notes-path`?

**Comment by CTrauma** [comment]
Sure.. I'll clean it up a bit and make sure the fallback to false works correctly and after using it for a few days I'll create a PR..

**Comment by pbek** [comment]
Awesome! :) And great job coming up with your own solution! 👍
