### ISSUE TITLE
Internal Links

### ISSUE THREAD

**Issue by steckerhalter** [pbek/QOwnNotes#355]
Would be nice if you could support internal anchor links similar to Github: https://gist.github.com/asabaylus/3071099

As a workaround I tried using html links like so:

```html
<a href="#log">Goto Log</a>
<a name="log">My Log</a>
```

But clicking one the link does nothing although I think it should go to the ref, or not?

**Comment by pbek** [comment]
Thank you for your idea, but currently such links are neither supported by <https://github.com/ali-rantakari/peg-markdown-highlight>, <https://github.com/hoedown/hoedown> nor the QTextBrowser component. :/

**Comment by steckerhalter** [comment]
@pbek allright, and how about the plain html example? shouldn't this at least work?

**Comment by pbek** [comment]
That wouldn't work in the QTextBrowser that is used to display the html. If you want you can play around with the html code, so you can test what might work. You could use a script like: <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/preview-styling.qml>
