### ISSUE TITLE
Headlines format

### ISSUE THREAD

**Issue by binerf** [pbek/QOwnNotes#356]
Hi,

I'd like to know if it's possible to modify headlines format by default by adding indent for specific headlines (ex headline1, headline2, etc...) or, better, by adding number (ex: 1., 1.1, 1.1.1, etc...).

Sometimes, I feel chapters are not enough apparent...

Thank you in advance.

**Comment by pbek** [comment]
If the question is if we can add indent in the note edit, the answer is: no, the markdown highlighter isn't capable of doing this right now

Was that your question? :)

**Comment by binerf** [comment]
Rather in preview window where file is rendered :-)

**Comment by pbek** [comment]
You could modify the html (and stylesheets) of the output with the scripting engine.

Please take a look at `function noteToMarkdownHtmlHook(note, html)` in <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/example.qml>.

You could for example add some custom stylesheets for the `<h2>`, `<h3>`, ... tags.

Does that already answer your question?

**Comment by pbek** [comment]
If you was able to create a nice script to format your output please let us know! :sun_with_face:

**Comment by binerf** [comment]
I guess it should answer to my question but, sorry for this stupid question, how or where should I put this file (modified for my purpose) ?

**Comment by pbek** [comment]
There are no stupid questions. ;)
You can put it anywhere you like, since you have to add it in the scripting settings in QOwnNotes.

**Comment by binerf** [comment]
Looks working !
Now, I'll update it to render as desired.

Thank you !!!

**Comment by binerf** [comment]
Is there any current qml file which I can work on as template ?

**Comment by pbek** [comment]
Great! No, just create a new qml file like `preview-styling.qml`.

**Comment by binerf** [comment]
I'm trying to update the qml but doesn't work. Here my code:
```
[...]
	return html.replace("<h2 id=\"toc_2\">", "<h2 id=\"toc_2\">&nbsp;&nbsp;");
	return html.replace("<h3 id=\"toc_3\">", "<h3 id=\"toc_3\">&nbsp;&nbsp;&nbsp;&nbsp;");
[...]
```
One single line return `html.replace `works, 2 lines do nothing.

**Comment by pbek** [comment]
What qml did you try to update?

`return` exits the function and returns the string you was attaching. The 2nd `return` will never be executed.

Try `return html.replace("<h2 id=\"toc_2\">", "<h2 id=\"toc_2\">&nbsp;&nbsp;").replace("<h3 id=\"toc_3\">", "<h3 id=\"toc_3\">&nbsp;&nbsp;&nbsp;&nbsp;");`

**Comment by binerf** [comment]
My test qml file called test.qml :-)

I try your suggestion.

Thank you for your quick reply !!

**Comment by binerf** [comment]
Okay, so I've a strange behaviour.
I've created `test.qml ` in my home dir and added this script in qownnotes settings.
In this file, I've added the line below:
```
[...]
	return html.replace("<h2 id=\"toc_2\">", "<h2 id=\"toc_2\">&nbsp;&nbsp;").replace("<h3 id=\"toc_3\">", "<h3 id=\"toc_3\">&nbsp;&nbsp;&nbsp;&nbsp;").replace("<h4 id=\"toc_4\">", "<h4 id=\"toc_4\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
[...]
```
And now, when I modify a note, qownnotes crashes with a beautiful 
`Segmentation fault (core dumped)`

**Comment by pbek** [comment]
Can you please post the complete content of your qml.

**Comment by binerf** [comment]
import QtQml 2.0
import com.qownnotes.noteapi 1.0
import com.qownnotes.tagapi 1.0

/**
 * This script is a generic example of some functions that will be called by QOwnNotes
 */
QtObject {
    /**
     * This is called when the script is loaded by QOwnNotes
     */
    function init() {
        script.log("Script init");
    }
    
    /**
     * This function is called when a note gets stored to disk
     * You cannot modify stored notes, that would be a mess since 
     * you are most likely editing them by hand at the same time
     * 
     * @param {NoteApi} note - the note object of the stored note
     */
    function onNoteStored(note) {
        script.log("fileName was stored!");
        script.log(note.id);
        script.log(note.name);
        script.log(note.fileName);
        
        // tagNames() returns a list of all tag names
        var tagNameList = note.tagNames();
        script.log(tagNameList);
    }
    
    /**
     * This function is called when a note gets stored to disk if
     * "Allow note file name to be different from headline" is enabled 
     * in the settings
     * 
     * It allows you to modify the name of the note file
     * Return an empty string if the file name of the note should 
     * not be modified
     * 
     * @param {NoteApi} note - the note object of the stored note
     * @return {string} the file name of the note
     */
    function handleNoteTextFileNameHook(note) {
        script.log(note.id);
        script.log(note.name);
        script.log(note.fileName);
        
        // tagNames() returns a list of all tag names
        var tagNameList = note.tagNames();
        script.log(tagNameList);
        
        // don't actually change anything
        return "";
    }
    
    /**
     * This function is called when the markdown html of a note is generated
     * 
     * It allows you to modify this html
     * This is for example called before by the note preview
     * 
     * @param {NoteApi} note - the note object
     * @param {string} html - the html that is about to being rendered
     * @return {string} the modfied html or an empty string if nothing should be modified
     */
    function noteToMarkdownHtmlHook(note, html) {
        script.log("noteToMarkdownHtmlHook was called");
        
        // show a custom headline and a horizontal ruler on top of the preview
        //return html.replace("h1>", "h1>        1     Custom preview for note " + note.name + "</h1><hr />");
	return html.replace("<h2 id=\"toc_2\">", "<h2 id=\"toc_2\">&nbsp;&nbsp;").replace("<h3 id=\"toc_3\">", "<h3 id=\"toc_3\">&nbsp;&nbsp;&nbsp;&nbsp;").replace("<h4 id=\"toc_4\">", "<h4 id=\"toc_4\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");

    }
    
    /**
     * This function is called when media file is inserted into the note
     * If this function is defined in multiple scripts, then the first script that returns a non-empty string wins
     * 
     * @param fileName string the file path of the source media file before it was copied to the media folder
     * @param mediaMarkdownText string the markdown text of the media file, e.g. ![my-image](file://media/505671508.jpg)
     * @return string the new markdown text of the media file
     */
    function insertMediaHook(fileName, mediaMarkdownText) {
        script.log("mediafile was inserted: " + fileName);
        return "";
    }
    
    /**
     * This function is called when html or a media file is pasted to a note with `Ctrl + Shift + V`
     * 
     * @param text text of the QMimeData object
     * @param html html of the QMimeData object
     * @returns the string that should be inserted instead of the text from the QMimeData object
     */
    function insertingFromMimeDataHook(text, html) {
        script.log("text was pasted: " + text);
        return "";
    }
    
    /**
     * This starts a timer that triggers two seconds
     */
    property QtObject timer: Timer {
        interval: 2000
        repeat: true
        running: true
        
        property int count: 0
        
        onTriggered: {
            count++;
            script.log("count = " + count);
            
            var note = script.currentNote();
            if (note) {
                script.log(note.id);
                script.log(note.name);
                script.log(note.fileName);
                
                // the tags property returns a list of assigned tag objects
                var tags = note.tags;
                
                // print out all tag names
                for (var i in tags) {
                    var tag = tags[i];
                    script.log(tag.name);
                }
                
                // tagNames() returns a list of all tag names
                var tagNameList = note.tagNames();
                script.log(tagNameList);
            }
        }
    }
}

**Comment by binerf** [comment]
```
import QtQml 2.0
import com.qownnotes.noteapi 1.0
import com.qownnotes.tagapi 1.0

/**
 * This script is a generic example of some functions that will be called by QOwnNotes
 */
QtObject {
    /**
     * This is called when the script is loaded by QOwnNotes
     */
    function init() {
        script.log("Script init");
    }
    
    /**
     * This function is called when a note gets stored to disk
     * You cannot modify stored notes, that would be a mess since 
     * you are most likely editing them by hand at the same time
     * 
     * @param {NoteApi} note - the note object of the stored note
     */
    function onNoteStored(note) {
        script.log("fileName was stored!");
        script.log(note.id);
        script.log(note.name);
        script.log(note.fileName);
        
        // tagNames() returns a list of all tag names
        var tagNameList = note.tagNames();
        script.log(tagNameList);
    }
    
    /**
     * This function is called when a note gets stored to disk if
     * "Allow note file name to be different from headline" is enabled 
     * in the settings
     * 
     * It allows you to modify the name of the note file
     * Return an empty string if the file name of the note should 
     * not be modified
     * 
     * @param {NoteApi} note - the note object of the stored note
     * @return {string} the file name of the note
     */
    function handleNoteTextFileNameHook(note) {
        script.log(note.id);
        script.log(note.name);
        script.log(note.fileName);
        
        // tagNames() returns a list of all tag names
        var tagNameList = note.tagNames();
        script.log(tagNameList);
        
        // don't actually change anything
        return "";
    }
    
    /**
     * This function is called when the markdown html of a note is generated
     * 
     * It allows you to modify this html
     * This is for example called before by the note preview
     * 
     * @param {NoteApi} note - the note object
     * @param {string} html - the html that is about to being rendered
     * @return {string} the modfied html or an empty string if nothing should be modified
     */
    function noteToMarkdownHtmlHook(note, html) {
        script.log("noteToMarkdownHtmlHook was called");
        
        // show a custom headline and a horizontal ruler on top of the preview
        //return html.replace("h1>", "h1>        1     Custom preview for note " + note.name + "</h1><hr />");
	return html.replace("<h2 id=\"toc_2\">", "<h2 id=\"toc_2\">&nbsp;&nbsp;").replace("<h3 id=\"toc_3\">", "<h3 id=\"toc_3\">&nbsp;&nbsp;&nbsp;&nbsp;").replace("<h4 id=\"toc_4\">", "<h4 id=\"toc_4\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");

    }
    
    /**
     * This function is called when media file is inserted into the note
     * If this function is defined in multiple scripts, then the first script that returns a non-empty string wins
     * 
     * @param fileName string the file path of the source media file before it was copied to the media folder
     * @param mediaMarkdownText string the markdown text of the media file, e.g. ![my-image](file://media/505671508.jpg)
     * @return string the new markdown text of the media file
     */
    function insertMediaHook(fileName, mediaMarkdownText) {
        script.log("mediafile was inserted: " + fileName);
        return "";
    }
    
    /**
     * This function is called when html or a media file is pasted to a note with `Ctrl + Shift + V`
     * 
     * @param text text of the QMimeData object
     * @param html html of the QMimeData object
     * @returns the string that should be inserted instead of the text from the QMimeData object
     */
    function insertingFromMimeDataHook(text, html) {
        script.log("text was pasted: " + text);
        return "";
    }
    
    /**
     * This starts a timer that triggers two seconds
     */
    property QtObject timer: Timer {
        interval: 2000
        repeat: true
        running: true
        
        property int count: 0
        
        onTriggered: {
            count++;
            script.log("count = " + count);
            
            var note = script.currentNote();
            if (note) {
                script.log(note.id);
                script.log(note.name);
                script.log(note.fileName);
                
                // the tags property returns a list of assigned tag objects
                var tags = note.tags;
                
                // print out all tag names
                for (var i in tags) {
                    var tag = tags[i];
                    script.log(tag.name);
                }
                
                // tagNames() returns a list of all tag names
                var tagNameList = note.tagNames();
                script.log(tagNameList);
            }
        }
    }
}
```

**Comment by pbek** [comment]
I created a working example of what you were trying to achieve: <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/preview-styling.qml>

**Comment by binerf** [comment]
Much much more clear !!!

Thank you very much !!!

**Comment by pbek** [comment]
No problem. :) Keep on scripting!
