### ISSUE TITLE
Images not being displyed on Note Viewer

### ISSUE THREAD

**Issue by Servh37** [pbek/QOwnNotes#357]
Hi all,

I have and issue when i attached / insert an image to my notes it dose not display in the note viewer it just displays a small image of a paper. 

dose anyone know how to fix this all is this normal?

just on a side not it dose copy the image to my owncloud/notes folder/media

Regards

**Comment by pbek** [comment]
How do you attach the image?
And can you please post the image so I can try to add it like did?

**Comment by Servh37** [comment]
Hi @pbek 

I attached the image by clicking on the insert image and selection the image below.
and it does copy the file to the media folder.

![3659](https://cloud.githubusercontent.com/assets/20963053/19331164/ca076ba2-912e-11e6-8844-b9b2f8021469.PNG)

**Comment by pbek** [comment]
Thank you. Can you please also post the dump from your debug settings, so I can take a closer look.

**Comment by pbek** [comment]
I inserted your image the same way to a note and it was displayed correctly in the note preview.
In the note I had a `![ca076ba2-912e-11e6-8844-b9b2f8021469](file://media/83512381.PNG)`.

 Can you please also post the dump from your debug settings.

**Comment by Servh37** [comment]
Hi @pbek 

Please see below debug file.

[QOwnNotes Debug Information.zip](https://github.com/pbek/QOwnNotes/files/526281/QOwnNotes.Debug.Information.zip)

**Comment by pbek** [comment]
## 16.10.4
- fixed an image preview problem and problem with the notes path under Windows

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Servh37** [comment]
Hi @pbek,

I have just updated to the new version and it is now working thank you for the quick response.

Just on a side note love the software and please keep it up will be a long user of the software i even use tit on ubuntu.

**Comment by pbek** [comment]
Great you like it. :) Thank you for reporting and testing!
