### ISSUE TITLE
qownnotes doesn't start on kubuntu 16.04

### ISSUE THREAD

**Issue by tiny6996** [pbek/QOwnNotes#359]
I open the application from the menu. The icon appears on my task bar for a moment then disappears. I will post the termninal output once I figure out how to run the program from the CLI

**Comment by pbek** [comment]
it's `QOwnNotes` on the cli

**Comment by pbek** [comment]
On a sidenote I also run it on KDE Neon (Ubuntu)...

**Comment by tiny6996** [comment]
it seemed to be an issue with my icon theme because the process would hang with one of the two following messages 

Warning: Invalid Type= "scalable" line for icon theme:  "/usr/share/icons/Dalisha/256x256/actions/" ((null):0, (null))

or 
Warning: Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix-Circle/16/panel/" ((null):0, (null))

**Comment by pbek** [comment]
That's interesting, never heard of such one before...
There's also a checkbox in the settings to force to use the internal theme (breeze icons) in QOwnNotes if you want to keep your old theme outside of QOwnNotes.
