### ISSUE TITLE
Support for configurable remote path per note folder

### ISSUE THREAD

**Issue by bugzy** [pbek/QOwnNotes#36]
In settings > ownCloud the user seems to be required to enter a path to the "main ownCloud sync folder." The problem, however, is that I do not use ownCloud in the same way as a typical dropbox user. That is, I do not sync my entire ownCloud account using a special root directory. 
ownCloud allows users to sync a preexisting local directory to an online one without requiring a special root folder. I am not sure if my explanation is understandable, but if you do understand it, is there anyway to have QOwnNotes do its thing without requiring a "main ownCloud sync folder." In essence, is there a way to complete a QOwnNote setup with all the good stuff by simply pointing to my local notes folder which is the only thing that is actually synced?

**Comment by pbek** [comment]
Hi @bugzy ,

thank you for your report!
QOwnNotes needs to know where the Notes are located on your ownCloud server.

I try to describe this process here: <http://www.qownnotes.org/Knowledge-base/QOwnNotes-settings-are-reporting-a-problem-with-my-ownCloud-path>

In you case you could try to select the folder above your Notes folder.
Does this already help you?

**Comment by bugzy** [comment]
@pbek Selecting the folder above my Notes folder works since the hierarchy online is /notes. Thanks. 

Correct me if I am wrong, but I guess what you are trying to do with that field is calculate the folder hierarchy in the cloud, but I am wondering if there isn't an alternative way of taking care of that issue [1]. 

A few of thoughts come to mind:

1. I am not sure that the selection of the hierarchy should be in the "settings," especially since users are allowed to switch notes directories. The problem being that things fail when two notes directories do not have the same hierarchy/path. In order to fix that issue, the user will need to change setting each time the notes collection is switches.

2. A better solution may be having the user select a local and remote path whenever a new notes directory/collection is created.
     
3. That is, when a user selects new notes folder, have the user also enter/select the matching online path by querying webdav (which you seem to be doing for the todo list.)

4. This method gives the added benefit of not having to name my local notes folder the same name that I name the owncloud folder (Note: if they are different names they fail.)

5. Essentially, I am thinking you can implement the pairing of online to local notes paths the same way that the owncloud client pairs local to online sync paths.

I hope this does not sound rude and is helpful in improving the application. I am not sure if to close this issue, so I will leave that decision to you. 
Thanks again. 


[1] http://www.qownnotes.org/Knowledge-base/QOwnNotes-settings-are-reporting-a-problem-with-my-ownCloud-path

**Comment by pbek** [comment]
Setting one main ownCloud path works great as long as all note folders are in the ownCloud path and one doesn't use selective sync. The ownCloud notes path doesn't support more than the one Notes folder anyway. But you are right, if selective sync is used it would be great to choose a remote folder for each local folder.
I can put that on my todo list, but it will be no easy task. If you want you can open a feature request issue.

**Comment by pbek** [comment]
@bugzy, this is now implemented in the just released version 1.2.8. Can you please be so kind and report if it works for you.

**Comment by bugzy** [comment]
sure thing. will let you know in a day or two

**Comment by pbek** [comment]
in version 1.3.4 you can also select your note folder on your ownCloud server directly
