### ISSUE TITLE
Notes not displaying when move between folders

### ISSUE THREAD

**Issue by Servh37** [pbek/QOwnNotes#360]
Hi @pbek 

i have just found another but for you in Version 16.10.4

when you have other folders if you move from the folder to other All notes or form Notes folder and then go back another folder it does not display the notes 

i found a work around by clicking on the notes folder that no being display close the Application and reopen and it will display the notes again.

debug log attached.
[QOwnNotes Debug Information.zip](https://github.com/pbek/QOwnNotes/files/528771/QOwnNotes.Debug.Information.zip)

Regards

**Comment by pbek** [comment]
Thank you for reporting. Can you please describe what you did, what you were expecting and what happened instead.

**Comment by Servh37** [comment]
Hi @pbek,

Please see the information below that you have requested. 

**what i did**
i Created a new Notes folder  and added notes to the folder, oncce i added the notes to the new folder a clicked on All notes and i was not able to see the notes list in all folders 
**what i was expecting**
i was expecting that when switching between folders. i would be able to see the all the notes within that folder.

**what happened instead**
when i move from the new folder to All notes or Note Folder  i was not able to see any notes in the notes list.

**Comment by pbek** [comment]
When you say "folder", do you mean "note folder" or "subfolders in a note folder" (the checkbox when configuring note folders)?

**Comment by Servh37** [comment]
Sorry @pbek  i mean note folder or All Notes not sub-folders i have not tested that if theirs any issue there.

**Comment by pbek** [comment]
Note folders doesn't interact with each other. There is no way to view all notes from all note folders. If you need that you can use note subfolders in a note folder.

**Comment by Servh37** [comment]
HI @pbek,

i have tryed creating 2 subfolders and when i change between the 2 subfolders im the notes and not being displayed. to get them to display i have to select the folder and then close the appliaciton and reopen to display them.

Regards

**Comment by pbek** [comment]
Can you please in more detail what you did and post the dump from the debug settings. I will try to reproduce it.

**Comment by Servh37** [comment]
Hi @pbek,

very sorry for this but i just have worked out that this is my mistake and it is working as it should now, i did know i had a filter enable and this was causing the notes not to be displayed when move to over folders

you can close this now is a user error 

Sorry for wasting your time on this.

Regards

**Comment by pbek** [comment]
I'm glad it worked out.
Helping someone never is a waste of time!

Have a great day!
