### ISSUE TITLE
Styling and border

### ISSUE THREAD

**Issue by lepascalou** [pbek/QOwnNotes#361]
Hello,

I'm trying to style the rendering of blockquotes and tables via the styling hook, and it seems that "border" has no effect at all.
For exemple I have this in file styling.qml : 
```
...
function noteToMarkdownHtmlHook(note, html) {
    var stylesheet = "blockquote {border: 1px solid #333; color: #ababab; margin-left: 1em; padding-left: 1em;}";
...
```

Is there a way to see which styling elements are supported by this method?

**Comment by pbek** [comment]
A `QTextBrowser` (derived from `QTextEdit`) is used for the preview.
This is what is supported: <http://doc.qt.io/qt-5/richtext-html-subset.html>

**Comment by pbek** [comment]
see also #164

**Comment by lepascalou** [comment]
@pbek thank you!
