### ISSUE TITLE
How do I install on shared hosting? 

### ISSUE THREAD

**Issue by wallyreport** [pbek/QOwnNotes#362]
My shared hosting distro is cloud linux. It is supposed to be compatible with Red Hat. But I cannot use the rpm command. Also, I do not have an "owncloud" directory, only "ownclouddata"

**Comment by pbek** [comment]
QOwnNotes is a desktop program, you are not supposed to install it on your server.
You can use ownCloud notes to view the notes on the web.

Does that (kind of) answer your question?

**Comment by pbek** [comment]
I will close this issue until there is more information.
