### ISSUE TITLE
Make shortcuts more customizeable?

### ISSUE THREAD

**Issue by steckerhalter** [pbek/QOwnNotes#363]
I have configured Emacs key bindings in GNOME and they work across most programs I use (for example here in the browser).

I found that for example <kbd>C-e</kbd> works in QOwnNotes (goes to the end of the line). Seems like this combo is not obstructed and the Emacs keyboard scheme picks it up.

But when I reassign **bold** to something else I can still not use <kbd>C-b</kbd> to move to the left. Other combos like <kbd>C-a</kbd> are hardcoded to "select all text" and cannot be reassigned at all.

Do you think this could be improved? I want to avoid having to use the arrow keys to move around since that puts unnecessary strain on the ankles.

**Comment by pbek** [comment]
I guess every single function you wish for would have to be reimplemented and put into a menu. And that only would work in a single text edit, for example the note edit. And I don't think that would change the operating system's default assignment in menus like the context menu or any other widget.

If you have found any more Qt-specific information, please let me know.

**Comment by steckerhalter** [comment]
@pbek could you give me a hint where I would have to disable shortcuts completely in the code? I expect that since `C-e` works now, the other combos would also work if qownnotes does not interfere with the shortcuts via QT. From there I could then look into other options on dealing with this issue.

**Comment by pbek** [comment]
Which shortcuts do you want to disable?

**Comment by steckerhalter** [comment]
Just all the shortcuts, I imagine there is some facility to customize shortcuts in QT so I'd like to turn that off so QT just does what it normally does.

**Comment by pbek** [comment]
One would have to loop through all menu items and disable shortcuts of their actions, then search all other actions in the code and turn their shortcuts off as well. As for the shortcuts that come from the OS, like `Ctrl + C`, I've no idea.
