### ISSUE TITLE
Image/ Photo clean up 

### ISSUE THREAD

**Issue by Servh37** [pbek/QOwnNotes#364]
Hi @pbek ,

Is there any way when a image  is removed to also remove the image from the folder just as a clean up task? instead of it just staying there and you have to remove it manually?  

Regards

**Comment by pbek** [comment]
There is a menu entry in the edit menu for removing them. Cheers, Patrizio

**Comment by Servh37** [comment]
thank you @pbek 

Is there any way for a future enhancement i there a way to automate this ?

**Comment by pbek** [comment]
That was talked about a lot in various issues here, it's too dangerous and not even possible very easily because notes can be created or modified externally.

**Comment by Servh37** [comment]
That's understandable i see where your coming from.

**Comment by pbek** [comment]
The compromise was the manual tool. ^_^
