### ISSUE TITLE
load new or overwrite

### ISSUE THREAD

**Issue by krueuw** [pbek/QOwnNotes#365]
if I change a note on my smartphone, a messagebox appears on my desktop: load new from harddisk or overwrite on harddisk (here in the german version). I think it is in this situation not clear enough what must I do to save my changed version from smartphone. 
Better: accept changes from extern? Yes or No
better still: show both versions with timestamp, difference and source, than choose one with no question or labels - only click on the text.

regards and tx  krueuw

**Comment by pbek** [comment]
Thank you for your suggestion!

**Comment by pbek** [comment]
## 16.11.4
- when the current note was modified externally the note diff dialog now
  just ask whether to `Accept external changes?`
    - selecting `No` now really causes external changes to be
      overwritten by the text in the note text edit

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?
