### ISSUE TITLE
panel in Windows menu : add check/uncheck box for all panel

### ISSUE THREAD

**Issue by bdouxx** [pbek/QOwnNotes#366]
There is no easy way to manage panels.

for example:
Show log panel: In "windows" menu we can only add 
subfolder panel :  Only in "note/setting/Note folder" if checked "Show subfolder in note list"
Tag panel : In "windows" menu we can only add with "show all panels"

In "windows" menu , it can be cool to have a submenu with checkbox for activate/desactivate each panel.

edit: I found what I want with a right click on icon bar, but it's not really natural.

**Comment by pbek** [comment]
> I found what I want with a right click on icon bar, but it's not really natural.

Yes, that is the default behavior of Qt.

So can you please re-frame your question / suggestion. :smile_cat:

**Comment by bdouxx** [comment]
I think that add a sub-menu in "Windows" menu with a checkbox for each panel can be a good idea.
Icon bar must be only a shortcut for actions, and not the only way to do this action

**Comment by pbek** [comment]
I planned to do that in the future. Thank you for your suggestion.

**Comment by pbek** [comment]
## 16.10.8
- added a new `Panels` menu to the windows menu for showing and hiding panels

**Comment by pbek** [comment]
## 16.10.8
- added a new `Toolbars` menu to the windows menu for showing and hiding toolbars

@Maboroshy might rejoice too ;)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment]
Works for me.

**Comment by pbek** [comment]
Great, thank you!

**Comment by bdouxx** [comment]
work for me too. Thanks

Just a remark. I think you can simplify text.
Windows/panels
  /show subfolder panel
  /show tags panel
  /show notes Search panel
  /...

In others programs ( as dolphin in linux kde) it's
Windows/panels
  /folders
  /informations
  /...

**Comment by pbek** [comment]
@bdouxx thank you for testing. The names come from the panel headlines when the panels are unlocked.
