### ISSUE TITLE
OpenSUSE Tumbleweed Dependency problem: libQt5Declarative5

### ISSUE THREAD

**Issue by Atheror** [pbek/QOwnNotes#367]
**OpenSUSE Tumbleweed** Dependency problem **libQt5Declarative5** following http://www.qownnotes.org/installation instructions:
```
Problem: nothing provides libQt5Declarative5 needed by qownnotes-16.10.5-1.1.x86_64
Solution 1: do not install qownnotes-16.10.5-1.1.x86_64
Solution 2: break qownnotes-16.10.5-1.1.x86_64 by ignoring some of its dependencies
```

**Comment by pbek** [comment]
That's interesting. Nothing changed there for a long time. Thank you for reporting.

The packages seems still to be here, but not for Tumbleweed.
<https://software.opensuse.org/package/libQt5Declarative5>

I wonder if <https://software.opensuse.org/package/libqt5-qtdeclarative> is the new package...

**Comment by pbek** [comment]
After three failed attempts with the build config that was now breaking the other SUSE distros I came to this error message:

```
Problem: qownnotes-16.10.5-4.1.x86_64 requires libQt5Core.so.5(Qt_5.7)(64bit), but this requirement cannot be provided
  uninstallable providers: libQt5Core5-5.7.0-1.2.x86_64[openSUSE_tumbleweed_repository]
```

Which is even more strange, because I've `libQt5Core` installed. Are you able to install QOwnNotes?

**Comment by Atheror** [comment]
Sorry, not even tried to install
Solution 1, Not to install because the risk  of break qownnotes. 
I tried to find the library but isnt there for tumbleweed as you see.

**Comment by Atheror** [comment]
Oh sorry, I didnt even tried to install without dependencies and cant find that library, as you can see, it is not available for tumbleweed.

**Comment by Atheror** [comment]
I will try again on a new fresh installation of tumbleweed.

**Comment by pbek** [comment]
Which library wasn't found? `libQt5Core`?

**Comment by Atheror** [comment]
libQt5Declarative5

**Comment by pbek** [comment]
Strange, I removed the dependency for `libQt5Declarative5` for Tumbleweed and added `libqt5-qtdeclarative` instead...
<https://build.opensuse.org/package/view_file/home:pbek:QOwnNotes/desktop/qownnotes.spec?expand=1>

**Comment by fifh** [comment]
FYI, same issue and same message regarding libQt5Declarative5 with OpenSuse Leap 42.2.
It could be problematic : with this message, when I tried to install qOwnNotes, I didn't even try to ignore the dependencies (solution 2). But I am dependent of qOwnNotes now :-)
Hopefully I found this issue, tried again and selected the solution 2, and it works !
The problem is that many people won't maybe even try, like me.

**Comment by pbek** [comment]
If there's anything I can do please let me know!

**Comment by pbek** [comment]
You'll find the OBS builds here: <https://build.opensuse.org/package/show/home:pbek:QOwnNotes/desktop#>

**Comment by putt1ck** [comment]
Installing on Tumbleweed, more or less up-to-date, using install instructions for Tumbleweed from http://www.qownnotes.org/installation - get 

Problem: nothing provides libQt5Declarative5 needed by qownnotes-16.11.17-1.1.x86_64

In addition there's no provider of libqt5-qtdeclarative in the standard repos, but there is a libqt5-qtdeclarative-tools, which I installed as a test and had no impact on the reported issue. Searching for packages that mention "declarative" gets me a LibQtQuick5 that describes itself as Qt 5 Declarative Library, and was already installed. Related?

**Comment by pbek** [comment]
Yes, they are related.

This is the build spec that is used by openSUSE 13.2, Tumbleweed and Leap: <https://build.opensuse.org/package/view_file/home:pbek:QOwnNotes/desktop/qownnotes.spec?expand=1>

The other openSUSE distributions are using `libQt5Declarative5`... so there is a `libQtQuick5` for Tumbleweed? I don't understand why `libQt5Declarative5` is asked for, I removed that.

**Comment by pbek** [comment]
I need to fix that tumbleweed if-clause and we will try `libQtQuick5` then. I'll make an other release today.

**Comment by pbek** [comment]
@putt1ck can you please tell me what `cat /var/lib/pkgconfig/gnome-bluetooth-1.0.pc | grep Version | sed 's/Version: //'` returns on your computer. Is `/var/lib` your lib-directory?

I found that code:

```
%define gnome_bluetooth_version %(cat %{_libdir}/pkgconfig/gnome-bluetooth-1.0.pc | grep Version | sed 's/Version: //')
%define is_tumbleweed %(%if %{?suse_version} == 1310 && %{?gnome_bluetooth_version} == 3.12.0 ; echo 1 || echo 0) 
```

**Comment by putt1ck** [comment]
/var/lib/pkgconfig doesn't exist. Nearest package by name is gnome-bluetooth2 but it's just a translation file i.e.: /usr/share/locale-bundle/en_GB/LC_MESSAGES/gnome-bluetooth2.mo

**Comment by pbek** [comment]
Thank you for testing, I'll go with `%if 0%{suse_version} > 1320` now.

**Comment by pbek** [comment]
@putt1ck, there now is a new release building, could you please test it and report if it works for you?

**Comment by putt1ck** [comment]
Done - installs no errors, thanks :)

**Comment by pbek** [comment]
Wonderful! Thank you for testing and helping!

**Comment by fifh** [comment]
Unfortunately not for me (Leap 42.2), qownnotes-16.11.18-1.1.x86_64 still requires libQt5Declarative5, that is not provided by any package.

**Comment by pbek** [comment]
Thank you for reporting, @fifh. I really wonder when the new Package was introduced and which `%{?suse_version}` I should test for...

**Comment by pbek** [comment]
It's even possible that `libQtQuick5` will work for all versions, I will try that in the next release!

**Comment by pbek** [comment]
@fifh, I created a 16.11.18.1 release for testing `libQtQuick5`, does it now install for you?

**Comment by fifh** [comment]
Congratulations ! It works ! Thanks !

**Comment by pbek** [comment]
Thank you for testing!
