### ISSUE TITLE
Toolbar issues

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#368]
Here's what I've found testing new toolbar customization feature. 

Settings UI:
-  Buttons in the middle are very wide and far form each other. That means big distances for eyes and mouse without any gain.
- Available and toolbar action columns are not labelled which makes new user confused for a few moments. Same with insert/remove buttons, maybe left/right would be better.
- All the above = take a look at KDE UI, like the one of Dolphin.
- The folder names from note folder section can be added but they won't appear on toolbar. Similar workspaces name work. 
- Folder names in the section tend to multiply. Looks a change of workspace causes it.
- You can't assign icon to a "name". I do understand that change icon UI is a hell for cross-platform app though. Good thing I know of endless Unicode tables. But please add icon to "Select note folder" item! It's the only "normal" item which has none.
- Separator icon is little weird. Maybe it'd be better same as on the list - "--- Separator ---".

Appearance:
- Some buttons, specifically the ones with drop-down like folders and workspaces are removed when app language (localization) is changed.
- Lock panels button is "pressed" when panels are locked. Pretty logical. But while the panels are mostly locked seeing "pressed" button all the time is distracting. Maybe it'd better be "Unlock panels" button.
- Reload folder and reload scripting engine have the same icon. I propose change the scripting one to `step_object_LinearMotor.svg` from the Breeze set.
- Maybe it's time to ditch quite toolbar since it was there for a rare special purpose and you now have that covered.

Custom actions:
- Reloading scripts don't reload toolbars, so dead custom action buttons will still be on toolbar.
- When you've thought that that's how it should be, app restart will remove all custom action buttons from toolbar. And they won't come back when you'll add the script back.
- When tinkering with custom actions their toolbar like to pop-up on active workspace even when it was disabled before. Maybe it should always be but be empty when there's no actions.

But overall very good and very useful.

**Comment by pbek** [comment]
Thank you for your elaborative feedback,

**Comment by pbek** [comment]
> Folder names in the section tend to multiply. Looks a change of workspace causes it.

Which folder names are you talking about and when happens this?

**Comment by Maboroshy** [comment]
Here it is. There's only two folders. They multiply on workspace change, maybe on other actions.
![screenshot_20161023_215029](https://cloud.githubusercontent.com/assets/19194063/19628623/40d164b2-9973-11e6-9ccb-1099fc78943a.png)

**Comment by pbek** [comment]
Most interestingly they don't multiply in the real menu outside...

**Comment by pbek** [comment]
## 16.10.9
- reloading the script engine in the script settings now also stores the
  enabled state of the script engine 
- the custom actions will be loaded correctly to the custom action
  toolbar when leaving the settings dialog with the `Ok` button

**Comment by pbek** [comment]
> Folder names in the section tend to multiply. Looks a change of workspace causes it.

I fixed that, but I didn't manage to make them work in the toolbars so I disabled them in the toolbar editor combo box

> Some buttons, specifically the ones with drop-down like folders and workspaces are removed when app language (localization) is changed.

Are you talking about combo boxes in the toolbars? Can you please describe what you did, what happened and what you expected?

**Comment by Maboroshy** [comment]
1. Make new custom toolbar (or use existing one)
2. Add some items with drop-down menus there, like new Panels and Toolbars items from Window menu (not their sub-items).
3. There are buttons with with drop-down menus on the toolbar.
4. Change localization (language) of the app. Restart the app for it to make effect.
5. The buttons are dead and empty now.

**Comment by pbek** [comment]
Did you really have to change the language to get this problem?
I added the workspace menu as combo box and after a restart it was gone... I guess I will have to disable some menu actions too...

**Comment by Maboroshy** [comment]
You're right, changing language is not required.

**Comment by Maboroshy** [comment]
> I guess I will have to disable some menu actions too...

Pity, having folders selector as a toolbar button with drop-down menu was a good alternative to combox. Since you're going to get all "folder" items out of toolbars the only possibility left is a custom action for which would run external command to "press" key shortcut set for selecting folder.

**Comment by pbek** [comment]
## 16.11.4
- the `Lock panels` menu entry was renamed to `Unlock panels`, got a new
  icon and now acts accordingly
- the icon for the `Reload scripting engine` menu entry was changed to
  make it different from the icon of `Reload note folder`
