### ISSUE TITLE
Sub-folders sorting mode

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#369]
Looks like sub-folders are sorted by date rather than by name like the tags do. That makes them jump back and forth and doesn't permits the tricks like starting sub-folder name with "!" to put it to the first line. 

I'm not sure sorting by date is useful for a note app and propose sorting by name, same as tags.

**Comment by pbek** [comment]
Tags are also sorted by date by default. This way the most recently modified sub-folder sits on top.

**Comment by Maboroshy** [comment]
Tags should be sorted by names too then. :smile:

**Comment by bdouxx** [comment]
There is an option to sort tag "by date" or "Alphabetical" can you add the same option for Subfolder?

I use QOwnNotes to stock all my cli command example, and it's more easy to find  what I want when it's sort "Alphabetical"

**Comment by pbek** [comment]
I will look into that.

**Comment by DenisRybin** [comment]
Just vote for sort folders feature, really needed.

**Comment by pbek** [comment]
Pull requests are welcome...

**Comment by pbek** [comment]
## 17.05.12
- a lot of work was done by @derboblan for the note list, tag tree and note
  subfolder panel, a big thank you for that
	- there now is a new page *Panels* in the *Settings dialog*
	- you can configure the sort order of the note list, tag tree and note
	  subfolder panel
	- sorting tags by last use is now possible
	- counting used tags in sub folders was also fixed
	- there are options to hide the search bar for tags and note subfolders
	- for note subfolders there are options to show the root folder name, to
	  display the note subfolders as tree with a root element and to show the
	  full path in the tree

There now is a new release, could you please test it and report if it works for you?

**Comment by Maboroshy** [comment]
I've tried the new features, and they are top notch! Just what the app needs. Great job @derboblan!

I like new "hide search" feature too. I like too keep the app minimalistic, so I've hided everything. But I've encountered an issue with note create/search, which is note list pane issue really. It has no "create new note" in context menu. Sub-folder list have both "create sub-folder" and "create note", and note list doesn't have anything. 

Maybe "create note" better move to the note list context menu with the "enter name" pop-up, like the one sub-folder has.

**Comment by pbek** [comment]
But you can create notes with `Ctrl+N`, can't you?

**Comment by Maboroshy** [comment]
I do, also there's a toolbar button. I just post all the inconsistencies I find in app's UI. If remember correctly, now it has 5 times "stars" there were when I first joined this hub. I want it to have 5 times more! :sunglasses:

**Comment by pbek** [comment]
:smile:

**Comment by pbek** [comment]
:rofl:, @derboblan. I just found out that you set the default sort order to alphabetically, instead of "by date". Phew...

**Comment by pbek** [comment]
I fixed that now in 17.12.1...
