### ISSUE TITLE
Gentoo overlay for QOwnNotes

### ISSUE THREAD

**Issue by internethering** [pbek/QOwnNotes#37]
Hi, 

in your releases the folder src/libraries/qmarkdowntextedit/ is empty, but it should include https://github.com/pbek/qmarkdowntextedit

why? I'm maintain for gentoo the qownnotes ebuilds in my overlay https://github.com/internethering/hering-overlay - It is inconsistent to provide static versions of qownnotes and pull the qmarkdowntextedit sources via git at instalation time. Alternativly please provide qmarkdowntextedit releases with same release scheme like QOwnNotes too.

thanks

**Comment by internethering** [comment]
see https://github.com/internethering/hering-overlay/blob/master/app-office/qownnotes/qownnotes-0.84.ebuild :)

**Comment by pbek** [comment]
Hi Richard,

great news!
I'm happy to hear that QOwnNotes gets build for Gentoo!

About qmarkdowntextedit, I guess you didn't checkout the submodules, please visit <http://www.qownnotes.org/installation> and take a look at **Building QOOwnNotes**.

Is there anything I can help you with?

The source code in the `master` branch is meant to be used by build services. 
You will find the version number in <https://github.com/pbek/QOwnNotes/blob/master/src/version.h>.
Of course you can also use the releases, like you did.

Do you have to trigger the build manually or can you use a GitHub hook to trigger your build process when anything changed in the QOwnNotes repository? Are you building locally or is there a build service for Gentoo?

Cheers, Patrizio

**Comment by pbek** [comment]
I just realized that submodules aren't included in the GitHub source code archives. That's bad, I have to see if I can do anything about that...

**Comment by internethering** [comment]
My goal is to get the ebuild in the main portage tree. Another thing is not so good: You named the last release linux-b830-131546 but version is 0.84 - I've to edit the ebuild if I want to push a new version. See line 11 at the ebuild. It would be better to name the release linux-0.84: Then it is enough to do:

```
cp qownnotes-0.74.ebuild qownnotes-0.84.ebuild
ebuild qownnotes-0.84.ebuild digest
```

Then I can try to get the ebuild in the main portage tree ;)

**Comment by pbek** [comment]
Thank you for your effort, Richard!

About the problem with git submodules in archives... GitHub uses `git archive` to create their archives and git doesn't include submodules with this command. There is little I can do about that... How bad would it be to keep the extra `git clone` in the build script?

About the release name.... There are various reasons for the long name because of troubles with Travis CI in combination with GitHub. GitHub automatically creates them when pushing a release and they were never meant to be automatically processed directly. I use the GitHub API to show download links on the webpage.
Is it possible that you fetch the code directly with it `git clone` from the `master` branch of the git repository in the build script?
The Travis CI release archives also have some Travis CI specific changes in them, an other reason for not using them directly.

When will the build process be triggered and how would portage handle that?

**Comment by internethering** [comment]
`git clone` is only allowed in <package>-9999.ebuilds. The version 9999 marks ebuilds, which fetch  from the master branch. But these packages will not be updated at normal system updates. If you wan't qownnotes updates your have to reemerge. This is unpopular for people who want use automatically the newest software, one of the advantages of a rolling release distribution.

By providing ebuilds for every release, the users get the updtes too. But in normal ebuilds there should never be fetched sources from master. There is no certainty that the package will build in an half year too: for example you change the library and qownotes 0.84 doesn't compile anymore. 

In my own overlay I can do what I want but with these restrictions qownnotes has no chance to get part of the official portage tree. It is my desire, but not so important for me :) 

The problem with the release names is, that no distribution can integrate your great software because they can't automate the fetch process. 

It's your choice: easy developing or providing a good service for the (debian|ubuntu|gentoo|...) maintainers and have so the chance to get part of the distributions ;)

**Comment by pbek** [comment]
You are right, fetching `master` directly isn't good neither. I need to learn more about Gentoo packaging...
So generally a new `.ebuild` file has to be created by every release? And every `.ebuild` file has to remain and should be buildable. In addition a `Manifest` file has to be maintained.
The users of the repository uses this `.ebuild` files to build the software him/herself. Am I right so far?

**Comment by internethering** [comment]
> So generally a new .ebuild file has to be created by every release? 
right. in most cases (usual minor-updates) is it enough to copy the latest ebuild: cp <package>-2.5.5.ebuild <package>-2.5.6.ebuild
The Manifest contains checksum amongst other things to provide security against compromised mirrors
> And every .ebuild file has to remain and should be buildable. In addition a Manifest file has to be maintained.
like debian testing new ebuilds get testing keywords. older ebuilds have stable keywords. older minor version get often deleted. more informations: https://devmanual.gentoo.org/keywording/

for example in the future qt6 comes out and you switch the dependency. then I would keep old qt5 based versions so lang as qt5 ist in portage tree too. this is a good example for the need of keeping older ebuilds. at the moment I delete older versions of qownnotes in my overlay, when the newest ebuild works fine

> The users of the repository uses this .ebuild files to build the software him/herself. Am I right so far?

Right. 

Some more official informations https://devmanual.gentoo.org/ebuild-maintenance/index.html - overlays like mine are more liberally :)

**Comment by pbek** [comment]
Ok, great. So it would make the most sense if I would maintain a repository myself as part of my build / deploy chain... Is it good practice to do that in a git repository, possibly even the current QOwnNotes repository?

**Comment by pbek** [comment]
I think you answered the 2nd questions with <https://github.com/internethering/hering-overlay/blob/master/README.md>. So I guess a new repository would be best.

**Comment by pbek** [comment]
Is it mandatory to create a `Manifest` file like <https://github.com/internethering/hering-overlay/blob/master/app-office/qownnotes/Manifest> and if yes, do you create it by hand or what tool(s) do you use? (possibly anything that is available on Ubuntu)

**Comment by pbek** [comment]
And does your `app-office/qownnotes` repository already work? I wasn't able to install `qownnotes` with emerge after following your instructions on a Gentoo live CD.

![virtualbox_gentoo](https://cloud.githubusercontent.com/assets/1798101/12674163/b47d4cc0-c681-11e5-8a26-8b3216426935.png)

**Comment by pbek** [comment]
I got an error after `emerge --sync`:

![virtualbox_gentoo_2](https://cloud.githubusercontent.com/assets/1798101/12674639/a30d5a90-c684-11e5-9209-433b2a5fb21a.png)

trying other git repo urls didn't help

**Comment by internethering** [comment]
hey, delete the /usr/local/portage/hering-overlay and do the emerge --sync again. The Manifest-file is created by `ebuild <package>.ebuild digest`. See `man ebuild`

If you want to maintain the ebuilds for your own, create a seperate git repository for it. You should let add this to the gentoo's overlay list: https://bugs.gentoo.org/show_bug.cgi?id=567272

**Comment by pbek** [comment]
Ah, thank you! I already found a preinstalled Gentoo VM image. I will try to make it work there and then report back!

**Comment by pbek** [comment]
Can it be considered *good practice* if I checkout a certain git tag and fetch that tag's submodules to build the application?

**Comment by internethering** [comment]
Next problem with fetching sources via git at installation: you can't perform offline installation. emerge has the -f flag, so you can fetch the archives. Then you don't need internet for the emerge process ;)

**Comment by pbek** [comment]
Thank you, good point!

**Comment by pbek** [comment]
Is it possible (and still considered *good practice*) to download two (or more) archives to build a package or is only one allowed?

**Comment by internethering** [comment]
yes, this is no problem, see: https://devmanual.gentoo.org/ebuild-writing/variables/index.html#src_uri
see also https://devmanual.gentoo.org/ebuild-writing/functions/src_unpack/ about unpacking.

**Comment by pbek** [comment]
Great, then we can simply download certain tag-archives of the main repo and the submodule(s). Thanks!

**Comment by pbek** [comment]
I have still problems with your overlay: `qt5`
Do you have any ideas what I have missed? I didn't find anything "on the internet"...
Do I have to add an other overlay manually, that provides `qt5`?

![virtualbox_gentoo 201512 kde-4 64bit _07_02_2016_09_00_41](https://cloud.githubusercontent.com/assets/1798101/12871414/6512d66a-cd79-11e5-8513-c02bdd8cf252.png)

**Comment by pbek** [comment]
I'm still out in the dark here, @internethering ;) I'd love to maintain a gentoo overlay.

**Comment by suhr** [comment]
It requires you to enable `qt5` flag instead of just requiring qt5 dependencies.
I have no idea why would someone write a ebuild this way.
Also, git tags like `linux-b1119-064549` are not very helpful.

**Comment by pbek** [comment]
What would be the *best practice* for a QOwnNotes `.ebuild` file, @suhr?

Regarding the tag... I know. :/ the reason I had to do this is because Travis does the building and tagging, and if GitHub is down at the wrong time then the tag is blocked when I rebuild the same build (because of the GitHub troubles)... This is the reason I want to maintain an own overlay for Gentoo. And so far I tried like 15 times and failed in the process. :)

**Comment by suhr** [comment]
> What would be the best practice for a QOwnNotes .ebuild file?

Drop qt5 flag and specify qt5 dependencies directly, provide both versioned ebuild and 9999 one.

>  This is the reason I want to maintain an own overlay for Gentoo. And so far I tried like 15 times and failed in the process. :) 

It's dangerous to go alone! Fork [this](https://github.com/suhr/qownnotes-overlay).

**Comment by pbek** [comment]
You are my hero, @suhr!

Since the package from `SRC_URI` isn't complete anyway is it possible to drop it all along and go straight for this?

```bash
git clone https://github.com/pbek/QOwnNotes.git -b THE_ID_I_WILL_USE
cd QOwnNotes
git submodule update --init
```

**Comment by suhr** [comment]
You can *technically* do this... But I'm not quite sure if it's a good idea.
Maybe better download submodules as archives instead? But this would require specifying submodules ids as well.

**Comment by pbek** [comment]
Yes, I could specify ids as well.

After too more hours I'm still stuck with error message after trying to install from <https://github.com/pbek/qownnotes-overlay> with `sudo emerge app-office/qownnotes`

![virtualbox_gentoo 201512 kde-4 64bit _29_02_2016_17_05_49](https://cloud.githubusercontent.com/assets/1798101/13400155/c955d0ac-df06-11e5-90f2-b6adf0945131.png)

**Comment by suhr** [comment]
Are you on `amd64` (without `~`)? Look at https://wiki.gentoo.org/wiki/Knowledge_Base:Accepting_a_keyword_for_a_single_package
Also, the ebuild actually should also have `~x86` in keywords too.

**Comment by pbek** [comment]
I now did a `echo "=app-office/qownnotes-1.1.0 ~amd64" >> /etc/portage/package.accept_keywords` and I'm building qownnotes! Thanks a lot!

Now I have something to work with.

Is there a tool to generate the `Manifest` with all the hashes? Ideally one that works on Ubuntu too...

**Comment by pbek** [comment]
Unfortunately the build failed after some minutes. :disappointed: 

```
PCRE auto-detection... ()
x86_64-pc-linux-gnu-g++ -c -O2 -pipe -O2 -Wall -W -fPIC  -I. -I/usr/include/mysql -I/var/tmp/portage/dev-qt/qtsql-5.4.2/work/qtbase-opensource-src-5.4.2/mkspecs/linux-g++ -o pcre.o pcre.cpp
x86_64-pc-linux-gnu-g++ -Wl,-O1 -Wl,--as-needed -Wl,-O1 -o pcre pcre.o   -L/usr/lib64/mysql -lpcre16 
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lpcre16
collect2: error: ld returned 1 exit status
Makefile:83: recipe for target 'pcre' failed
gmake: *** [pcre] Error 1
PCRE disabled.
PCRE support cannot be enabled due to functionality tests!
 Turn on verbose messaging (-v) to /var/tmp/portage/dev-qt/qtsql-5.4.2/work/qtbase-opensource-src-5.4.2/configure to see the final report.
 If you believe this message is in error you may use the continue
 switch (-continue) to /var/tmp/portage/dev-qt/qtsql-5.4.2/work/qtbase-opensource-src-5.4.2/configure to continue.
 * ERROR: dev-qt/qtsql-5.4.2::gentoo failed (configure phase):
 *   configure failed
 * 
 * Call stack:
 *     ebuild.sh, line   90:  Called src_configure
 *   environment, line 2731:  Called qt5-build_src_configure
 *   environment, line 2329:  Called qt5_base_configure
 *   environment, line 2447:  Called die
 * The specific snippet of code:
 *       "${S}"/configure "${conf[@]}" || die "configure failed";
 * 
 * If you need support, post the output of `emerge --info '=dev-qt/qtsql-5.4.2::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-qt/qtsql-5.4.2::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/dev-qt/qtsql-5.4.2/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-qt/qtsql-5.4.2/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-qt/qtsql-5.4.2/work/qtbase-opensource-src-5.4.2'
 * S: '/var/tmp/portage/dev-qt/qtsql-5.4.2/work/qtbase-opensource-src-5.4.2'

>>> Failed to emerge dev-qt/qtsql-5.4.2, Log file:

>>>  '/var/tmp/portage/dev-qt/qtsql-5.4.2/temp/build.log'

 * Messages for package dev-qt/qtsql-5.4.2:

 * ERROR: dev-qt/qtsql-5.4.2::gentoo failed (configure phase):
 *   configure failed
 * 
 * Call stack:
 *     ebuild.sh, line   90:  Called src_configure
 *   environment, line 2731:  Called qt5-build_src_configure
 *   environment, line 2329:  Called qt5_base_configure
 *   environment, line 2447:  Called die
 * The specific snippet of code:
 *       "${S}"/configure "${conf[@]}" || die "configure failed";
 * 
 * If you need support, post the output of `emerge --info '=dev-qt/qtsql-5.4.2::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-qt/qtsql-5.4.2::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/dev-qt/qtsql-5.4.2/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-qt/qtsql-5.4.2/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-qt/qtsql-5.4.2/work/qtbase-opensource-src-5.4.2'
 * S: '/var/tmp/portage/dev-qt/qtsql-5.4.2/work/qtbase-opensource-src-5.4.2'

 * GNU info directory index is up-to-date.

!!! existing preserved libs:
>>> package: dev-libs/libpcre-8.38
 *  - /usr/lib64/libpcre16.so.0
 *  - /usr/lib64/libpcre16.so.0.2.6
 *      used by /usr/lib64/libQt5Core.so.5.4.2 (dev-qt/qtcore-5.4.2)
Use emerge @preserved-rebuild to rebuild packages using these libraries

 * IMPORTANT: 8 config files in '/etc' need updating.
 * See the CONFIGURATION FILES section of the emerge
 * man page to learn how to update config files.

 * IMPORTANT: 18 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.
```

**Comment by suhr** [comment]
Well, qt overlay is well-known to be broken (I am still waiting for fixing [#566196](https://bugs.gentoo.org/show_bug.cgi?id=566196)).
Build `libpcre` with `pcre16` use flag.

> Is there a tool to generate the Manifest with all the hashes?

Sure, it's called [`ebuild`](https://devmanual.gentoo.org/eclass-reference/ebuild/) (there's also `repoman manifest` to do it per overlay).

**Comment by pbek** [comment]
> Well, qt overlay is well-known to be broken (I am still waiting for fixing #566196).

:smile_cat: 

> Build libpcre with pcre16 use flag.

Can you please give instructions for someone who is not familiar with Gentoo and who isn't seemingly getting a grip on it. :grimacing: 

> Sure, it's called ebuild (there's also repoman manifest to do it per overlay).

So I guess I have to do it by hand, since both tools aren't available in the Ubuntu repository, I execute all the packaging scripts on Ubuntu.

**Comment by suhr** [comment]
> Can you please give instructions for someone who is not familiar with Gentoo and who isn't seemingly getting a grip on it.

I guess, `USE=pcre16 emerge -1 libpcre` should work.

> So I guess I have to do it by hand, since both tools aren't available in the Ubuntu repository, I execute all the packaging scripts on Ubuntu.

Well, the [manifest format](https://wiki.gentoo.org/wiki/Repository_format/package/Manifest) is pretty straightforward.

**Comment by pbek** [comment]
> I guess, USE=pcre16 emerge -1 libpcre should work.

I think you meant `env USE=pcre16 emerge -1 libpcre`, I'm building qownnotes again... We'll see. :)

> Well, the manifest format is pretty straightforward.

Thank you. Are you supposed to keep all ebuild files in `app-office/qownnotes` and thus create a line in the `Manifest` for every archive like you did for `qownnotes-1.1.0.tar.gz`?

**Comment by suhr** [comment]
> Are you supposed to keep all ebuild files in `app-office/qownnotes` and thus create a line in the Manifest for every archive like you did for `qownnotes-1.1.0.tar.gz`?

Yep.

**Comment by pbek** [comment]
Omg, we did it! After several weeks of struggles I build QOwnNotes on Gentoo. :D
Now it only can get better! Thank you for your great support so far, @suhr!

![virtualbox_gentoo 201512 kde-4 64bit _29_02_2016_18_43_12](https://cloud.githubusercontent.com/assets/1798101/13403253/6b68cb6c-df14-11e5-9d47-ba7e27bf2b1e.png)

**Comment by pbek** [comment]
How is detected which ebuild file has the latest version?
I did a `emerge --sync`, where the new `qownnotes-1.1.0.1.ebuild` was found and an `emerge app-office/qownnotes` where the old `qownnotes-1.1.0.ebuild` was built and installed.

**Comment by suhr** [comment]
According to http://www.funtoo.org/Ebuild_Version_Encoding, `1.1.0.1 > 1.1.0`.
But better to just use `x.y.z` versions.

**Comment by pbek** [comment]
Hm, I had to remove your ebuild files so that the new version was detected.
And I have to do a `echo "=app-office/qownnotes-1.1.0.2 ~amd64" >> /etc/portage/package.accept_keywords` for each version, that's annoying.

After I introduced version 1.1.0.3, I had to remove the old version again to make it work... :(

**Comment by suhr** [comment]
https://wiki.gentoo.org/wiki/Handbook:X86/Portage/Branches
Stable gentoo is the way too stable.

**Comment by pbek** [comment]
If that's a problem only I have encountered or other users will be able to fix it themselves I'm not concerned.

But I still have the versioning problem...
btw., what is the `*-9999.ebuild`file for?

**Comment by suhr** [comment]
> btw., what is the *-9999.ebuildfile for?

To build the freshest version from git. Btw, there's a bug in 9999 ebuild, it should use the `develop` branch.
Add `EGIT_BRANCH="develop"` to the ebuild.

**Comment by pbek** [comment]
Ok, thank you. Right now I have to get the *detection of the latest version in the overlay* going...

**Comment by pbek** [comment]
Version 1.1.1 is now out and it was found by `emerge`.
@suhr could you be so kind and try out my installation instructions to see if I did anything wrong / stupid.
<http://www.qownnotes.org/installation#Gentoo>

**Comment by suhr** [comment]
> if I did anything wrong / stupid

Yes. `overlay.xml` is not in the repo just because, it allows you to do `layman -f -a qownnotes-overlay -o https://raw.githubusercontent.com/pbek/qownnotes-overlay/master/overlay.xml` (you need to have layman installed, but anyone already have it installed).
Then you just do `emerge qownnotes`. :smiley:

**Comment by pbek** [comment]
I tried that several times yesterday, but `emerge` never find `qownnotes`.
If you say it should work I will add it to the instructions. :smiley:

**Comment by pbek** [comment]
I now updated <http://www.qownnotes.org/installation#Gentoo>, thank you.

**Comment by internethering** [comment]
:+1: I removed Qownnotes from my overlay.

**Comment by pbek** [comment]
I struggled for weeks to make that happen. :stuck_out_tongue_winking_eye:

**Comment by internethering** [comment]
This should work without problems:

```
layman -d qt
emerge -qvuDN @world
emerge -qv qownnotes
```
;)

**Comment by pbek** [comment]
Thank you, if you like you can do a pull request directly to <https://github.com/pbek/QOwnNotes/blob/develop/build-systems/gentoo/qownnotes.ebuild>

**Comment by pbek** [comment]
@suhr, @internethering, did the update to v1.1.2 work for you on Gentoo?

**Comment by suhr** [comment]
Yep, it works fine.

**Comment by pbek** [comment]
Makes me happy. I will close this issue for the time being. Thanks a lot for helping!

**Comment by pbek** [comment]
@internethering and @suhr: QOwnNotes will now be built from a source archive (like it should be) in the Gentoo overlay (and not from git repositories).

Could you please confirm that the build process still works? (there were some library changes too). 

My Gentoo didn't let me download from the overlay because of SSL errors and I don't know how to tell emerge how to ignore them.

**Comment by suhr** [comment]
Yes, it compiles.

**Comment by pbek** [comment]
Great to hear, thank you! Please notify me if there are troubles in 16.05.4.
