### ISSUE TITLE
Crashing on Mac OS 10.12

### ISSUE THREAD

**Issue by minthemiddle** [pbek/QOwnNotes#371]
When trying to close `QON`, the app repeatedly crashes with [this error message](https://ghostbin.com/paste/bxsm5)

OS: Mac OS Sierra 10.12
QON: 16.10.6

**Comment by pbek** [comment]
Thank you for reporting. I coudn't reproduce that. Can you please try to enable the log panel and turn off all logging checkboxes and try again. If that helped can you please test which checkbox did the crashing.

**Comment by minthemiddle** [comment]
Switching logs off solves the problem. I tried all single checkboxes, neither did cause the problem. Probably a combination of them, but could not find them (as there are quite a few combinations).

**Comment by pbek** [comment]
Can you still reproduce the problem when you turn them all on?

**Comment by minthemiddle** [comment]
Yes, it crashes with all on.

**Comment by pbek** [comment]
Can you please test all variants of turning one off?

**Comment by minthemiddle** [comment]
No luck with all combinations of one off. Two off gives too many options for a quick test.

**Comment by pbek** [comment]
Ok, thank you.

**Comment by pbek** [comment]
## 16.10.8
- tried to fix some logging problems that could cause a crash when the
  app quits under OS X

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by minthemiddle** [comment]
Do not get errors with new release!

**Comment by pbek** [comment]
So it doesn't crash when all logging checkboxes are turned on and you quit the application?

**Comment by minthemiddle** [comment]
Exactly.

**Comment by pbek** [comment]
Perfect, thank you!
