### ISSUE TITLE
QOwnNotes Error with NTFS ( SNAPS )

### ISSUE THREAD

**Issue by Amourspirit** [pbek/QOwnNotes#372]
For **QOwnNotes** 16.10.7

I am working on settng up two compters with dual boot. **Windows** and **Ubunu** 16.04.

Each of the two  systems have a ntfs partition share between **Ubuntu** and **Windows**. When booting into Ubuntu both system mount the ntfs partition on startup ( via fstab )

I system one I install **QOwnNotes** via snap. I was getting the error  
```
Unable to establish a database connection with file '/home/paul/Cloud/Notes/notes.sqlite'.
Are the folder and the file writeable?  
```

The Cloud folder is on a mounted ntfs partition.

On system two **QOwnNotes** was also installed with snap.  
The Cloud folder was on ext4 partition. Everyting worked as expected.

To fix error on system one removed the **QOwnNotes** *snap* install and then installed the *ppa* version. When QOwnNotes was installed from *PPA* everyting worked fine.

On system two I moved the Cloud folder to the mounted ntfs partition and adjusted the **QOwnNotes** to match the new location. Once the Notes were on the ntfs partition I got the error again  
```
Unable to establish a database connection with file '/home/paul/Cloud/Notes/notes.sqlite'.
Are the folder and the file writeable?
```

I removed the *snap* install on system two and installed the *PPA* version and all worked well again.

I just wanted to post this issue to let other know if they are having an issue.

My NTFS partions are mounted with specific ownership/permissions  as follows  
`UUID=?????????? /media/d_drive ntfs defaults,auto,uid=1000,gid=1000,umask=002 0 0`

See Alos: [HOWTO: Mount NTFS partitions with specific ownership/permissions](https://ubuntuforums.org/showthread.php?t=1604251)

**Comment by pbek** [comment]
Thank you for reporting, but I guess that's a snapd confinement problem. Maybe you can file an issue with them directly...

From the snapd GitHub page: If you have found an issue with the application, please [file a bug](https://bugs.launchpad.net/snappy/+filebug) on the [bugs list on Launchpad](https://bugs.launchpad.net/snappy/).

A unrelated question: do the snap version and the PPA version of QOwnNotes look the same for you? (could you post a screenshot in case you have the snap version still installed?)

**Comment by Amourspirit** [comment]
pbek, sorry the snap version has been removed from my systems for the time being. I did not spend much working with the snap version other than troubleshooting. Although I did not notice any differences.

**Comment by pbek** [comment]
@Amourspirit, thank you for your feedback. I'm asking because under KDE snapped and non-snapped applications are looking quite different...

Concerning the NTFS problem, please let me know if there's something I can do (if you'll ever find out)...

**Comment by Amourspirit** [comment]
Bug has been [posted](https://bugs.launchpad.net/snappy/+bug/1635925) on [bugs list on Launchpad](https://bugs.launchpad.net/snappy/).

**Comment by pbek** [comment]
Ok, thank you. I subscribed to it.

**Comment by Amourspirit** [comment]
I re-installed the snap version temporarly to get the info for the Bug post on Lanuchpad so I was able to get a screen shot.

Screen shot of QOwnNotes installed via snap
![Screenshot](http://storage1.static.itmages.com/i/16/1023/h_1477211255_6647445_5f352b76f3.png)

**Comment by Amourspirit** [comment]
Screen shot of QOwnNotes installed via ppa on same computer as above
![Screenshot](http://storage3.static.itmages.com/i/16/1023/h_1477212035_8769412_e56c8f79d0.png)

**Comment by pbek** [comment]
Ok, same problem under Unity... Thank you for the screenshots!
