### ISSUE TITLE
Offline Mode

### ISSUE THREAD

**Issue by dasmaetthes** [pbek/QOwnNotes#373]
Would be nice if QOwnNotes would also work offline with just a local note folder.

I get the error: "NotizOrdner Datenbank kann nicht geöffnet werden"

**Comment by pbek** [comment]
This error message has nothing to do with some online resource. What else does the error message say? 

Can you please post the output from the debug settings.

**Comment by dasmaetthes** [comment]
"Kann keine Verbindung zur Datenbank mit der Datei 'C:/Users/Me/ownCloud/Notes' herstellen. Sind der Ordner oder die Datei beschreibbar?"

It seems to be a problem with the setup assistent. There I set the folder 'C:/Users/Me/Documents/Notes' and he finds the stored notes inside there. However when I go now to the settigns he has a tottaly other folder 'C:/Users/Me/ownCloud/Notes'
If I set in settings again the folder 'C:/Users/Me/Documents/Notes' it works all fine.

**Comment by pbek** [comment]
Which version of QOwnNotes are you using?
Can you reproduce that problem be setting up QOwnNotes again? Just yesterday I set a note folder in the settings dialog and it worked...

**Comment by pbek** [comment]
I just reset my data under Windows and did a new QOwnNotes setup with a non-default notes folder. Worked flawlessly...

**Comment by dasmaetthes** [comment]
I use version 16.10.08 and can reproduce it each time I setting QOwnNotes up again.

**Comment by pbek** [comment]
Can you please describe what you are doing?

**Comment by dasmaetthes** [comment]
Tested it now again, reset my data and also deleted the note folder. Now it worked without any problems.

**Comment by pbek** [comment]
Great, tell me when there is a problem again. ;)
