### ISSUE TITLE
Auto Update for Windows

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#376]
Since a week I'm working on an auto updater for Windows... Very hard labor.
My progress is in this feature branch: <https://github.com/pbek/QOwnNotes/commits/feature/auto-update>

**Comment by Siedlerchr** [comment]
Thanks for your effort! I will check out the branch

**Comment by pbek** [comment]
Don't run the code yet. ;)

**Comment by pbek** [comment]
from the changelog...

## 16.11.0
- there are now **automatic updates** for **Windows**
    - in the update dialog you will see a new `Update` button
    - if you press it the latest version of QOwnNotes will be downloaded
      and an updater script will uncompress the ZIP file to the folder
      where you were running QOwnNotes from
    - all temporary files for the update will be deleted
    - after the update QOwnNotes will be started again
        - QOwnNotes will be started in potable mode again if it was in
          portable mode before
- there is a new `Debug options` page in the settings
    - use the checkbox `Fake old version number to trigger update` and
      click `Check for updates` in the `Help` main menu to test the
      update process so you can provide feedback

There now is a new release, could you please test it and report if the new features work for you?

**Comment by pbek** [comment]
I had to pull the release down... There are some DLL problems. :(

**Comment by pbek** [comment]
If anyone can help, this is the release: <https://ci.appveyor.com/api/buildjobs/2g7511soao83xgu1/artifacts/appveyor%2FQOwnNotes.zip>

**Comment by Siedlerchr** [comment]
I will try it out

Am 02.11.2016 5:26 nachm. schrieb "Patrizio Bekerle" <
notifications@github.com>:

**Comment by pbek** [comment]
I think I've got it now, can you please try the zip from <https://ci.appveyor.com/project/pbek/qownnotes/build/windows-b2425/artifacts> (when the build is done in a few minutes)?

**Comment by Siedlerchr** [comment]
It works!
And when I click check for updates, it says: You are using the latest
version :)



2016-11-02 17:58 GMT+01:00 Patrizio Bekerle <notifications@github.com>:

**Comment by pbek** [comment]
Did you enable `Fake old version number to trigger update`?

**Comment by Siedlerchr** [comment]
Okay, I tested it  now with Fake Update.
The update itself works, but the console windows stay open after update: (Win 7 x64)
In the console windows I get the following outputt:

```
X:\TEMP\QOwnNotes-DM8948-updater.bat X:\TEMP\QOwnNotes-DM8948.zip "X:\Progr
les\QOwnNotes" X:\TEMP\QOwnNotes-DM8948-unzip.exe
======================================
Updating QOwnNotes in folder:
"X:\Program Files\QOwnNotes"
======================================
Source archive:
X:\TEMP\QOwnNotes-DM8948.zip
======================================
Unzip executable:
X:\TEMP\QOwnNotes-DM8948-unzip.exe
======================================
Executing unzip command:
X:\TEMP\QOwnNotes-DM8948-unzip.exe -o X:\TEMP\QOwnNotes-DM8948.zip -d "X:\P
m Files\QOwnNotes"
======================================
Uncompressing files...
Archive:  X:/TEMP/QOwnNotes-DM8948.zip
error:  cannot delete old X:/Program Files/QOwnNotes/bearer/qgenericbearer.
error:  cannot delete old X:/Program Files/QOwnNotes/bearer/qnativewifibear
l
error:  cannot delete old X:/Program Files/QOwnNotes/D3Dcompiler_47.dll
error:  cannot delete old X:/Program Files/QOwnNotes/iconengines/qsvgicon.d
error:  cannot delete old X:/Program Files/QOwnNotes/imageformats/qdds.dll
error:  cannot delete old X:/Program Files/QOwnNotes/imageformats/qgif.dll
error:  cannot delete old X:/Program Files/QOwnNotes/imageformats/qicns.dll
error:  cannot delete old X:/Program Files/QOwnNotes/imageformats/qico.dll
  inflating: X:/Program Files/QOwnNotes/imageformats/qjp2.dll
error:  cannot delete old X:/Program Files/QOwnNotes/imageformats/qjpeg.dll
  inflating: X:/Program Files/QOwnNotes/imageformats/qmng.dll
  inflating: X:/Program Files/QOwnNotes/imageformats/qsvg.dll
  inflating: X:/Program Files/QOwnNotes/imageformats/qtga.dll
  inflating: X:/Program Files/QOwnNotes/imageformats/qtiff.dll
  inflating: X:/Program Files/QOwnNotes/imageformats/qwbmp.dll
  inflating: X:/Program Files/QOwnNotes/imageformats/qwebp.dll
  inflating: X:/Program Files/QOwnNotes/libeay32.dll
  inflating: X:/Program Files/QOwnNotes/libEGL.dll
  inflating: X:/Program Files/QOwnNotes/libgcc_s_dw2-1.dll
error:  cannot delete old X:/Program Files/QOwnNotes/libGLESV2.dll
  inflating: X:/Program Files/QOwnNotes/libssl32.dll
  inflating: X:/Program Files/QOwnNotes/libstdc++-6.dll
  inflating: X:/Program Files/QOwnNotes/libwinpthread-1.dll
  inflating: X:/Program Files/QOwnNotes/opengl32sw.dll
  inflating: X:/Program Files/QOwnNotes/platforms/qwindows.dll
  inflating: X:/Program Files/QOwnNotes/printsupport/windowsprintersupport.

  inflating: X:/Program Files/QOwnNotes/QOwnNotes.exe
  inflating: X:/Program Files/QOwnNotes/QOwnNotesPortable.bat
  inflating: X:/Program Files/QOwnNotes/QOwnNotes_ar.qm
  inflating: X:/Program Files/QOwnNotes/QOwnNotes_de.qm
  inflating: X:/Program Files/QOwnNotes/QOwnNotes_en.qm
  inflating: X:/Program Files/QOwnNotes/QOwnNotes_es.qm
  inflating: X:/Program Files/QOwnNotes/QOwnNotes_fr.qm
  inflating: X:/Program Files/QOwnNotes/QOwnNotes_hu.qm
  inflating: X:/Program Files/QOwnNotes/QOwnNotes_it.qm
  inflating: X:/Program Files/QOwnNotes/QOwnNotes_ja.qm
  inflating: X:/Program Files/QOwnNotes/QOwnNotes_nl.qm
  inflating: X:/Program Files/QOwnNotes/QOwnNotes_pl.qm
  inflating: X:/Program Files/QOwnNotes/QOwnNotes_pt.qm
  inflating: X:/Program Files/QOwnNotes/QOwnNotes_ru.qm
  inflating: X:/Program Files/QOwnNotes/QOwnNotes_zh.qm
error:  cannot delete old X:/Program Files/QOwnNotes/Qt5Core.dll
  inflating: X:/Program Files/QOwnNotes/Qt5Gui.dll
error:  cannot delete old X:/Program Files/QOwnNotes/Qt5Network.dll
  inflating: X:/Program Files/QOwnNotes/Qt5PrintSupport.dll
  inflating: X:/Program Files/QOwnNotes/Qt5Qml.dll
  inflating: X:/Program Files/QOwnNotes/Qt5Sql.dll
  inflating: X:/Program Files/QOwnNotes/Qt5Svg.dll
error:  cannot delete old X:/Program Files/QOwnNotes/Qt5Widgets.dll
  inflating: X:/Program Files/QOwnNotes/Qt5Xml.dll
  inflating: X:/Program Files/QOwnNotes/Qt5XmlPatterns.dll
  inflating: X:/Program Files/QOwnNotes/sqldrivers/qsqlite.dll
  inflating: X:/Program Files/QOwnNotes/sqldrivers/qsqlmysql.dll
  inflating: X:/Program Files/QOwnNotes/sqldrivers/qsqlodbc.dll
  inflating: X:/Program Files/QOwnNotes/sqldrivers/qsqlpsql.dll
  inflating: X:/Program Files/QOwnNotes/ssleay32.dll
  inflating: X:/Program Files/QOwnNotes/translations/qt_ca.qm
  inflating: X:/Program Files/QOwnNotes/translations/qt_cs.qm
  inflating: X:/Program Files/QOwnNotes/translations/qt_de.qm
  inflating: X:/Program Files/QOwnNotes/translations/qt_fi.qm
  inflating: X:/Program Files/QOwnNotes/translations/qt_fr.qm
  inflating: X:/Program Files/QOwnNotes/translations/qt_he.qm
  inflating: X:/Program Files/QOwnNotes/translations/qt_hu.qm
  inflating: X:/Program Files/QOwnNotes/translations/qt_it.qm
  inflating: X:/Program Files/QOwnNotes/translations/qt_ja.qm
  inflating: X:/Program Files/QOwnNotes/translations/qt_ko.qm
  inflating: X:/Program Files/QOwnNotes/translations/qt_lv.qm
  inflating: X:/Program Files/QOwnNotes/translations/qt_ru.qm
  inflating: X:/Program Files/QOwnNotes/translations/qt_sk.qm
  inflating: X:/Program Files/QOwnNotes/translations/qt_uk.qm
======================================
Deleting temporary files
======================================
Starting QOwnNotes:
"X:\Program Files\QOwnNotes"\QOwnNotes.exe --after-update X:\TEMP\QOwnNotes
48-updater.bat
======================================
Drücken Sie eine beliebige Taste . . .
```

**Comment by pbek** [comment]
Thank you for testing. I guess the space in the folder name did mess things up a bit. QOwnNotes didn't start up automatically after the update, am I right?

What I don't understand is why several files could not be overwritten... I wonder if QOwnNotes.exe was still open for a while and blocked the delete by having the DLLs loaded... QOwnNotes did close while the script was running, did it?

And 3rd question, was you able to start QOwnNotes again after updating?

**Comment by pbek** [comment]
btw. you were downgrading QOwnNotes, because the current version isn't released yet, so you will need to download the link I posted again...

**Comment by Siedlerchr** [comment]
Forget my log above. 
It seems I had accidentally two instances open...
I re did all and now it works correct. QownNotes restarts fine. Only the console windows stays open.
I can close it  manually and QOwnNotes stays open, so I guess it's just a commetic thing.

Thanks for the great feature!

**Comment by pbek** [comment]
Thank you for testing.

> I can close it manually and QOwnNotes stays open, so I guess it's just a cosmetic thing.

I tried to get around that for an hour... I wasn't able to start QOwnNotes in the background from a script. You can take a look at the batch file if you like, you'll find it in your QOwnNotes application folder: `update.bat`. If you find a solution please let me know. I will release the Windows version.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by pbek** [comment]
@Siedlerchr was you able to update to 16.11.1 with the update button?

**Comment by Siedlerchr** [comment]
Auto Update works fine now :+1: 
And I will see if there is a solution with the bat file.

**Comment by pbek** [comment]
Great! I already had macOS build hell with homebrew's Qt library the whole day. I'm working on the macOS updater... :)

**Comment by sgiuliari** [comment]
I have installed qOwnNotes in a custom directory under c:\Program Files (x86)\qOwnNotes using Windows 10 Home.

Once the updater ask me to 'Update and restart' every time I get the ``error:  cannot delete old C:/Program Files (x86)/qOwnNotes/QOwnNotes_fr.qm`` error (even the original window was closed and the updater is the only one still open.

Do you have any clues how to fix the problem?

```
C:\Users\steph\AppData\Local\Temp\QOwnNotes-U12552-updater.bat C:\Users\steph\AppData\Local\Temp\QOwnNotes-U12552.zip "C:\Program Files (x86)\qOwnNotes" C:\Users\steph\AppData\Local\Temp\QOwnNotes-U12552-unzip.exe
======================================
Updating QOwnNotes in folder:
"C:\Program Files (x86)\qOwnNotes"
======================================
Source archive:
C:\Users\steph\AppData\Local\Temp\QOwnNotes-U12552.zip
======================================
Unzip executable:
C:\Users\steph\AppData\Local\Temp\QOwnNotes-U12552-unzip.exe
======================================
Executing unzip command:
C:\Users\steph\AppData\Local\Temp\QOwnNotes-U12552-unzip.exe -o C:\Users\steph\AppData\Local\Temp\QOwnNotes-U12552.zip -d "C:\Program Files (x86)\qOwnNotes"
======================================
Uncompressing files...
Archive:  C:/Users/steph/AppData/Local/Temp/QOwnNotes-U12552.zip
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/bearer/qgenericbearer.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/bearer/qnativewifibearer.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/D3Dcompiler_47.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/iconengines/qsvgicon.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/imageformats/qdds.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/imageformats/qgif.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/imageformats/qicns.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/imageformats/qico.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/imageformats/qjpeg.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/imageformats/qsvg.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/imageformats/qtga.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/imageformats/qtiff.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/imageformats/qwbmp.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/imageformats/qwebp.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/libeay32.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/libEGL.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/libgcc_s_dw2-1.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/libGLESV2.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/libssl32.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/libstdc++-6.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/libwinpthread-1.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/opengl32sw.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/platforminputcontexts/qtvirtualkeyboardplugin.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/platforms/qwindows.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/printsupport/windowsprintersupport.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/qmltooling/qmldbg_debugger.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/qmltooling/qmldbg_inspector.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/qmltooling/qmldbg_local.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/qmltooling/qmldbg_native.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/qmltooling/qmldbg_profiler.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/qmltooling/qmldbg_quickprofiler.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/qmltooling/qmldbg_server.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/qmltooling/qmldbg_tcp.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/QOwnNotes.exe
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/QOwnNotesPortable.bat
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/QOwnNotes_ar.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/QOwnNotes_de.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/QOwnNotes_en.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/QOwnNotes_es.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/QOwnNotes_fr.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/QOwnNotes_hu.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/QOwnNotes_it.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/QOwnNotes_ja.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/QOwnNotes_nl.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/QOwnNotes_pl.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/QOwnNotes_pt.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/QOwnNotes_ru.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/QOwnNotes_zh.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/Qt5Core.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/Qt5Gui.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/Qt5Network.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/Qt5PrintSupport.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/Qt5Qml.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/Qt5Quick.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/Qt5Sql.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/Qt5Svg.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/Qt5Widgets.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/Qt5Xml.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/Qt5XmlPatterns.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/scenegraph/softwarecontext.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/sqldrivers/qsqlite.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/sqldrivers/qsqlmysql.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/sqldrivers/qsqlodbc.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/sqldrivers/qsqlpsql.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/ssleay32.dll
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/translations/qt_ca.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/translations/qt_cs.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/translations/qt_de.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/translations/qt_fi.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/translations/qt_fr.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/translations/qt_he.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/translations/qt_hu.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/translations/qt_it.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/translations/qt_ja.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/translations/qt_ko.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/translations/qt_lv.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/translations/qt_pl.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/translations/qt_ru.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/translations/qt_sk.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/translations/qt_uk.qm
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/unzip.exe
error:  cannot delete old C:/Program Files (x86)/qOwnNotes/update.bat
======================================
Deleting temporary files
======================================
Starting QOwnNotes:
"C:\Program Files (x86)\qOwnNotes"\QOwnNotes.exe --after-update C:\Users\steph\AppData\Local\Temp\QOwnNotes-U12552-updater.bat
======================================
Drücken Sie eine beliebige Taste . . .
C:\Program Files (x86)\qOwnNotes>
```

**Comment by pbek** [comment]
@sgiuliari I'm not sure if that are permission problems or something else.
In `C:/Program Files (x86)/qOwnNotes/update.bat` you should find the batch file that is used to update QOwnNotes. If turn on the version number faking in the `Debug options` settings you can do an other update (in case you already have updated manually).

You could try to run the `unzip.exe` as administrator with `runas` and report if that helped.
see: [runas documentation](https://technet.microsoft.com/en-us/library/cc771525(WS.10).aspx)

**Comment by pbek** [comment]
Does it work if you put QOwnNotes to an other directory outside `C:/Program Files (x86)`?

**Comment by Siedlerchr** [comment]
Make also sure that you don't have the explorer open in the directory.
Regarding  the directory try starting the program as admin

Am 16.11.2016 10:13 vorm. schrieb "Patrizio Bekerle" <
notifications@github.com>:

**Comment by sgiuliari** [comment]
I copied the folder from ``c:\Program Files (x86)`` to ``c:\temp``

The update process worked for ``c:\temp`` so I assume there is a problem with access rights in program folder.

Is there a msi installer available for qOwnNotes which maybe could prevent the problem?

**Comment by pbek** [comment]
No, there is no msi. I'm open to contributions if it can be integrated with Appveyor.
Has anyone played around with the `updater.bat` yet?

**Comment by sgiuliari** [comment]
Maybe it would be a good idea to inform Windows users at the installation page not to use a folder inside ``c:\Program Files (x86)`` or ``c:\Program Files``?

**Comment by pbek** [comment]
I will surely do that if there is no other solution.

**Comment by sgiuliari** [comment]
Maybe for the time being till another solution is found?

just for notice: I now have to relocate three instances of qOwnNotes as I have installed it on every system - so an information on the installation page would be highly appreciated ;-)

**Comment by pbek** [comment]
I now added more information to <http://www.qownnotes.org/installation#Windows>, thank you for the suggestion.

**Comment by sgiuliari** [comment]
superb :)

I have read the additional paragraph and yes - now it's more clear

Thank you ^^

**Comment by FBachofner** [comment]
On Windows XP I have the same issues [error deleting certain files + updater fails to close (when an update is successful)]

Invariably, relaunching QOwnNotes after a failed update allows the next update attempt (the one which just failed) to succeed.

I recognize XP is EOL, but the source of the problem is probably the same.  I'll look at the .bat file at my earliest convenience.

On my (and clients) various Linux machines (Mostly Mint 18.1 and a few Ubuntu), updates via the PPA work just fine!  :-)

**Comment by pbek** [comment]
If someone can improve the script we would all be happy... :)

**Comment by huckepick** [comment]
I am new to QOwnNotes and I try to use it as a replacement for ResophNotes which is not under active development anymore.

my environment looks like this:
- Windows 10
- current version(s) of QOwnNotes, f.e. 17.09.04
- QOwnNotes lives in a folder my user can write
- I generally run QOwnNotes in portable mode

I face the problem that the Auto Update ALWAYS FAILS when I run in portable mode.
Updater runs, throws "error:  cannot delete old", reruns in portable mode and starts the old version of QOwnNotes.
Nothing updates.
Even if run several times in a row.
I even started QOwnNotes from the admin console.

my solution:
- run QOwnNotes.exe (normal mode)
- run update via dialogue
- update succeeds instantly (although run with the same user like before)
- run QOwnNotesPortable.bat
- QOwnNotes is updated and runs just fine in portable mode
- ... weird ...

**Comment by pbek** [comment]
That's weird, does anyone else here has this problem?
@huckepick is QOwnNotes closed while the update script is running? (can you check that in the task manager)

**Comment by huckepick** [comment]
Good point.
That seems to be the reason!

I didn't pay enough attention to it, even browsing through the comments above.

Version : 17.10.1

The Updater doesn't seem to wait till QOwnNotes is closed.
I tried it several times now with the debugging option of fake version number activated.

# observation

## updating while running as portable version
- QOwnNotes stays open for the whole time while updater script runs
- only after the script is done, QOwnNotes gets closed
- QOwnNotes does not reboot now

## updating while running as non-portable version
- QOwnNotes stays open for a very short time while updater script already runs
- QOwnNotes gets closed quite quickly while updater runs
- QOwnNotes reboots

I think the problem is that the updater should somehow make sure that QOwnNotes is closed before update starts.
I can't tell why the portable version doesn't get closed or why it closes so slowly but I can reproduce this behaviour again and again.

**Comment by pbek** [comment]
> QOwnNotes stays open for the whole time while updater script runs

now that's strange, does anyone else also have that phenomenon?

**Comment by pbek** [comment]
@huckepick I added a `taskkill /IM QOwnNotes.exe` to the updater script, but you will not get the new script until after the next update, so please add those lines to your `updater.bat` (same directory as `QOwnNotes.exe`) before you update.

See: <https://github.com/pbek/QOwnNotes/commit/6cddd38a6cef213b587fbf77867fd2c75f7c9453#diff-4700d9ae71fb74f791e5b2ecc6f68479>

For me that did the trick in portable-mode.

## 17.10.2
- the `updater.bat` in Windows now kills the `QOwnNotes.exe` process when the
  application is updated because it doesn't seem to end in portable mode

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by huckepick** [comment]
Update in portable mode works now :-)

Thumbs up!

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by huckepick** [comment]
"portable version not closing" behavior had returned in 17.10.4 but it's gone again in 17.10.5

**Comment by pbek** [comment]
nothing changed in that script since 17.10.2...
