### ISSUE TITLE
Enable math mode in hoedown

### ISSUE THREAD

**Issue by Siedlerchr** [pbek/QOwnNotes#377]
First of all, thanks for the great work :+1: 

I noticed that hoedown is used as markdown parser. It would be nice if you could enable the math support.
According to this wiki entry, it seems to be just a simple flag.
https://github.com/cben/mathdown/wiki/math-in-markdown#hoedown

Best Regards
siedlerchr

**Comment by pbek** [comment]
> First of all, thanks for the great work :+1:

Thank you for your kind words.

> HOEDOWN_EXT_MATH

I will test that. I'm not sure if the markdown to html converter will support it...

**Comment by pbek** [comment]
`HOEDOWN_EXT_MATH` was already enabled.

**Comment by pbek** [comment]
## 16.11.1
- enabled `HOEDOWN_EXT_MATH_EXPLICIT` in hoedown

`HOEDOWN_EXT_MATH_EXPLICIT` neither doesn't seem to do anything...

**Comment by pbek** [comment]
There now is a new release, could you please test it and see if HOEDOWN_EXT_MATH_EXPLICIT does anything for you?

**Comment by Siedlerchr** [comment]
Thanks. As far as I see it, from the hoedown site it is correct, when I compare the output to https://github.com/hoedown/hoedown/pull/114 

If I draw the correct conclusions, it now only needs MathJax or a similar lib which then renders the output on the html side.

**Comment by pbek** [comment]
MathJax is "a JavaScript display engine for mathematics that works in all browsers". QOwnNotes doesn't use a browser (see #164) for the preview. So that will have to wait until QOwnNotes does.
