### ISSUE TITLE
Note taking features suuggestion

### ISSUE THREAD

**Issue by Wacek** [pbek/QOwnNotes#378]
First of all thanks for the soft, I am not a programmer but I am using Qown notes for my studies as a planner, daily note taker, because of its portability, flexiblity and multiplatformity.
I have some suggestions for niche features regarding notetaking, not expecting all to be implemented, but even one of these would be great for me:
- grouping notes by colour. As for person with good visual memory it would help me to have an option to organize notes by diffrerent header colour in the left pane. Tested this in some (very few, don't actually know why so few) notetaking soft and it really works
- note nesting like a tree or stem. That means an option to structurize notes on the left pane in a tree fashion X>Y and  Z > Y to Q> Z to R etc
- allow importing mind mapping images from Freemind or Freeplane (not a necessity since these can be exported to jpeg, but helpfull)
- an option to link to a text file or audio file from within the note which launches the player or text editor like LibreOffice or other system program for a particualar  extension (don't know if that is possible, just a suggestion)
Anyway thanks for the soft, it is great already :)
- Unicode sign selector would be of great help, since sometimes I need a partucular unicode sign and this requires going to external app, copying then pasting into Qown

**Comment by pbek** [comment]
Thanks a lot for your suggestions!

> grouping notes by colour. 

that sounds like a good suggestion. maybe assigning tags a color, that would be doable...
what should be colored that way in your opinion?

> note nesting

often discussed here, it makes no sense to use a tree if people are having 1000+ notes in a note sub-folder

> importing

I don't know any of these services, are there specs for the format? no one asked about an import for them before. 
QOwnNotes is using simple plain text markdown files anyway...

> audio

I'm not sure yet if that should be done in a plain text file note application :)
So you are suggesting some kind of voice memos?

> unicode sign selector

do you have an example where that is done?
in which way should this be integrated in your opinion (how should that look like)?

**Comment by Wacek** [comment]
- colouring everything is not necessary, just a title in the lower left pane, and possibbly the same tittle in the note body would be enough, but I am fine with every similar option
- to me nesting makes even more sense if you have loads of notes. The reason is - obviously not every note needs tree since not every note is related to any of the other. But to show that relation for some of  them - thus making them standing out of the mass - for that tree would be useful. In other words tree should not be obligatory - just an option to show that some of the notes are somehow related
- Yes I expected that since mind mapping is not a mass used sofware. Because I am not a programmer
I am not sure if theres any full specs available, I have managed to found something here
http://freeplane.sourceforge.net/wiki/index.php/Current_Freeplane_File_Format
http://freeplane.sourceforge.net/wiki/index.php/New_Freeplane_File_Format_(Proposal)
Try also the sample files which are included after the installation in the main program directory
http://www.freeplane.org/wiki/index.php/Main_Page
It would be nice to have it, but because I know it is not very popular I don't count on that feature very much, just asking..
- I am using voice memos,  yes so I just thought it would be great if i could place them within the actual note itself - just some kind of link to the audio file which would trigger the player to play the audio, or libreoffice writer, or calc maybe..
- this unicode sign map is used in many text editors try for rexample libreoffice - writer - insert special character, or some kind of character map or anything similar, it is useful when one occasionally writes somethin which involves rare scripts or characters - it would just be handy not having to invoke any other external app but it is not a must have
BabelMap is probably the most extended program of this kind that I am aware - I am certainly not asking for such a swiss knife, but having at least some of the signs like Cyrillic, or Middle Eastern Scripts at hand when needed
http://www.babelstone.co.uk/Software/BabelMap.html
I don't have any clear idea how it should look, just asking whether you would consider it useful - i suppose it would require selector for any of system installed unicode fonts, and then an ability to copy a particular sign to the body of the text

**Comment by pbek** [comment]
> colouring everything is not necessary, just a title in the lower left pane, and possibbly the same tittle in the note body would be enough, but I am fine with every similar option

I'm working on assigning a color to tags. The question is what to do with that color...
Using the color the tag in the tag tree as foreground color (or as background color)?
Coloring even the note in the note list? (problem: multiple tags can be assigned to one note)

> nesting

What do you mean by relation between notes? And what do these relations have to to with a note tree?
Currently you can view the note subfolders and the tags in a tree. And the notes in a list...
Note trees wouldn't be convenient to work with when having a lot of notes in a folder...

> mind mapping

How should mind maps be "translated" to plain text notes?

> voice memos

why libreoffice writer or calc?

> unicode sign map

I will see if I can find out how to do such a thing in Qt...
(If you find something please let me know)

**Comment by Wacek** [comment]
- Ok finally I got used to the terminolgy so now I hope to be more clear:
My original idea was to have cloured only that what you call tags + note list (all that is in the left pane, only that, nothing more whether it would be text only, or bacground whichever is easier). Colouring the note edit areas (middle + right pane) is not needed.
If you can colour only tags, not note list - that is fine as well.
- nesting
Note tree allows for showing basic relations between notes ie the fact that contents of note B stemm from contents of note A like here
http://www.ubuntugeek.com/wp-content/uploads/2009/03/tuxcards.gif
But why do you insist on having all of the notes in a tree, why not just 2, 3, 10 or whatever is needed (the rest may be keept in folders like today). Is that necessary?
What I understand by a tree:
NOTE A (general)
|---- Note B (stemms from A) --- Note C (also stemms from A)
|--------- Note D (stemms from B which stemms from A) etc
Unrelated Folder
Unrelated Folder
Note E
Unrelated Folder
|--- Note X, Y, Z in that folder
Note F
|---Note G which stemms from F etc
unrelated folder with hundreds of notes 
And so on..
-- "mind mapping"
I don't know i was hoping that since you allow jpegs and pngs in the note, mind maps could be as well, I dont know much about coding, if you think this can't be done, I just drop the request
"why libreoffice writer or calc?"
Why not? Its a popular and free format, I am working a lot on them, if that is too much just disregard it, it is only my "wishful thinking".
Thx

**Comment by pbek** [comment]
> contents of note B stemm from contents of note A 

note subfolder are just folders in your filesystem, notes are just markdown files. I think I don't understand what you mean by relations between the notes... you can't have the same note in more than one folder. That's what tags are for...
And if notes and note subfolders would be in one tree and there is a subfolder with 1000 notes the tree will get pretty unusable...

> mind maps

notes are just plain text files... mind maps are not part of that scheme...

> libreoffice

I thought you were still talking about audio files...
As I was saying... QOwnNotes are just markdown files... you can convert (and strip down) every other text format... embedding libreoffice files makes not much sense for that...

**Comment by pbek** [comment]
## 16.11.5
- you can now **assign a color to tags**
    - multiple tags can be selected to assign a color to or to disable
      the color
    - the color will be used as background color of the tag items in the
      tag tree and of the notes in the note list
    - if multiple tags with colors are assigned to a note then the color
      of the first tag with a color is used for the note 

There now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment]
I guess by "nesting notes" @Wacek wants wiki-style note structure. I've used Wikidpad that has that instead of traditional folder-note structure. The idea is the note 1 that has a link to note 2 in it's text is a "parent" of note 2, and not 2 is it's "child". Wikidpad parses all note links and creates a tree of notes "relations". That's a different note structure to the one used in QOwnNotes.

Audio files can be run from a link inside note, like `[I'm an audio](file://media/audio/note.mp3)`. QOwnNotes does that on my system. What it can't do is automatically insert that link when user drops an audio file to the note editor.

Unicode sign map for several needed signes can be made as a toolbar with `script.noteTextEditWrite` custom actions with no changes to the app code.

**Comment by pbek** [comment]
@Maboroshy thank you for your comments on that! Yes, QOwnNotes uses folders (or/and) tags for structuring...

**Comment by Maboroshy** [comment]
It can theoretically also use wiki-style structure with a separate panel for that kind of structure but that would require a lot of work to implement brand new parsing and structuring engine. 

The gain is invasion to wiki-style note app "market" but it's a long way to match strong players there like Zim or Wikidpad.

**Comment by Maboroshy** [comment]
The color tagging works for me, and it's a quite cool feature.

**Comment by pbek** [comment]
I think so too, thank you for testing @Maboroshy!

**Comment by pbek** [comment]
- as for voice notes
	- that would need the Qt multimedia library and I'm not sure anyone would actually expect voice notes in a plain text note app so I will let this feature rest for now
- unicode sign map
    - I haven't found any widget or something for that. I've only found <https://www.kde.org/applications/utilities/kcharselect/> which is very nice. I wouldn't expect less from a character map. But that's a whole different (KDE) project and I don't think it's worth the time to write something similar for QOwnNotes...
	- <http://doc.qt.io/qt-5/qtwidgets-widgets-charactermap-example.html> would be too little to be useful. The critical part would be a search and some kind of structuring to find characters

**Comment by pbek** [comment]
On a funny side-note... KCharSelect was developed by a friend of mine a loooong time ago. :smile:

**Comment by pbek** [comment]
I will close this issue until there is more information.

**Comment by pbek** [comment]
@Wacek feel free to share more ideas! I quite like the colored tags / notes! :wink:

**Comment by pbek** [comment]
## 16.11.7
- the tag color of the note will now be updated correctly if a tag is
  removed from the current note

**Comment by pbek** [comment]
and beside above:

- when creating a new tag in the tag tree by right-clicking on a tag and
  clicking `Add tag` the tag will now be shown in the tag tree
- you can now also create tags in the tag tree by right-clicking on the
  `All notes` or `Untagged notes` items and selecting `Add tag`
