### ISSUE TITLE
Feature request: Global Search

### ISSUE THREAD

**Issue by dynobo** [pbek/QOwnNotes#38]
It would be very useful, if I could search through full texts of _all_ my notes in the current notes folder with one search. I have really many notes and it would be faster if I don't have to browse them...

Thanks a lot for your application!!!! :)

**Comment by dynobo** [comment]
Sorry, I noticed I used an old version, and this feature is already implemented. :-))))

**Comment by pbek** [comment]
Wow, you must have had a **very** old version. :grin:
