### ISSUE TITLE
older file-versions not found on Server

### ISSUE THREAD

**Issue by demlak** [pbek/QOwnNotes#380]
Hi,
as described on IRC:
I'm using QOwnNotes since several Months. QOwnNotes-Api is installed, and updating files worked since begin.
I never needed to check older file-versions.. but now i needed to. QOwnNotes does not find any file-versions of any note. in owncloud itself i can see/find the file versions.

----
debug information:
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mi. Nov. 9 08:27:27 2016`
**Version**: `16.11.6`
**Build date**: `Nov  7 2016`
**Build number**: `263`
**Platform**: `linux`
**Operating System**: `Arch Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.7.0`
**Qt Version (runtime)**: `5.7.0`
**Portable mode**: `no`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Icon theme**: `breeze`
**Notes in current note folder**: `42`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `http://my-domain.name/oc`
**appIsValid**: `yes`
**serverVersion**: `8.2.2.2`
**appVersion**: `16.09.0`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/run/media/demlak/FREEBIRD/_OC/Notes`
**remotePath**: `notes`
**isShowSubfolders**: `no`
**activeNoteSubFolder name**: *empty*

### Note folder `/run/media/demlak/FREEBIRD/_OC/Notes`

**id**: `2`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/run/media/demlak/FREEBIRD/_OC/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**activeNoteSubFolder name**: *empty*

### Note folder `/run/media/demlak/FREEBIRD/_OC`

**id**: `3`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/run/media/demlak/FREEBIRD/_OC`
**remotePath**: *empty*
**isShowSubfolders**: `no`
**activeNoteSubFolder name**: *empty*

### Note folder ``

**id**: `4`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: *empty*
**remotePath**: *empty*
**isShowSubfolders**: `no`
**activeNoteSubFolder name**: *empty*

## Settings

**AboutDialog/geometry**: `<binary data>`
**DistractionFreeMode/menuBarGeometry**: `<binary data>`
**DistractionFreeMode/menuBarHeight**: `30`
**DistractionFreeMode/windowState**: `<binary data>`
**Editor/CurrentSchemaKey**: `EditorColorSchema-6033d61b-cb96-46d5-a3a8-key`
**LastUpdateCheck**: `2016-11-09T08:13:59`
**LogWidget/showAtStartup**: `false`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `22`
**MainWindow/markdownDefaultViewMode**: `false`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `Courier,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `Noto Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `Courier,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `Noto Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl**: `false`
**NoteDiffDialog/geometry**: `<binary data>`
**PiwikClientId**: `<hidden>`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**ShowSystemTray**: `false`
**SortingModeAlphabetically**: `false`
**allowDifferentNoteFileName**: `false`
**allowOnlyOneAppInstance**: `false`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `true`
**appMetrics/notificationShown**: `true`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**currentWorkspace**: `b76d5aa1-2504-47da-ae86-key`
**customNoteFileExtensionList**: *empty*
**darkMode**: `false`
**darkModeColors**: `false`
**darkModeTrayIcon**: `false`
**defaultNoteFileExtension**: `txt`
**demoNotesCreated**: `true`
**disableAutomaticUpdateDialog**: `true`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: *empty*
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**interfaceLanguage**: *empty*
**internalIconTheme**: `false`
**itemHeight**: `24`
**markdownHighlightingInterval**: `200`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `2`
**noteSaveIntervalTime**: `10`
**notesPath**: `/run/media/demlak/FREEBIRD/_OC/Notes`
**notifyAllExternalModifications**: `false`
**ownCloud/localOwnCloudPath**: `/run/media/demlak/FREEBIRD/_OC`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: `http://my-domain.name/oc`
**ownCloud/todoCalendarBackend**: `0`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/todoCalendarEnabledList**: `deleted-for-privacy`
**ownCloud/todoCalendarEnabledUrlList**: `deleted-for-privacy`
**ownCloud/todoCalendarUrlList**: `deleted-for-privacy`
**ownCloud/userName**: `deleted-for-privacy`
**previousWorkspace**: *empty*
**recentNoteFolders**: `/run/media/demlak/FREEBIRD/_OC/_notes, /run/media/demlak/FREEBIRD/_OC`
**savedSearches/noteFolder-1**: `Note 2016-11-03T13.15.44, Note 2016-10-21T02.01.59, Note 2016-10-12T14.43.40, Note 2016-10-06T20.03.27, Note 2016-10-06T12.47.02, Note 2016-09-27T17.52.36, Note 2016-09-09T20.26.34, Note 2016-09-03T23.35.19, Note 2016-08-30T15.52.27, Note 2016-08-18T16.55.33, Note 2016-07-27T00.41.38, Note 2016-07-04T14.04.26, Note 2016-06-29T14.45.14, Note 2016-06-15T09.36.10, Note 2016-06-14T12.28.05`
**showMenuBar**: `true`
**showStatusBar**: `true`
**skipVersion**: `1.0.1`
**trashSplitterSizes**: `<binary data>`
**versionSplitterSizes**: `<binary data>`
**workspace-b76d5aa1-2504-47da-ae86-key/name**: `default`
**workspace-b76d5aa1-2504-47da-ae86-key/noteSubFolderDockWidgetVisible**: `true`
**workspace-b76d5aa1-2504-47da-ae86-key/windowState**: `<binary data>`
**workspaces**: `b76d5aa1-2504-47da-ae86-key`

## System environment

**XDG_VTNR**: `1`
**CSF_XmlOcafResource**: `/opt/opencascade/src/XmlOcafResource`
**PAM_KWALLET5_LOGIN**: `/tmp/kwallet5_demlak.socket`
**XDG_SESSION_ID**: `c2`
**SSH_AGENT_PID**: `834`
**SHELL**: `/bin/bash`
**CSF_StandardDefaults**: `/opt/opencascade/src/StdResource`
**CSF_XSMessage**: `/opt/opencascade/src/XSMessage`
**GS_LIB**: `/home/demlak/.fonts`
**GTK_MODULES**: `canberra-gtk-module`
**KDE_FULL_SESSION**: `true`
**XDG_SESSION_CLASS**: `user`
**ANT_HOME**: `/usr/share/apache-ant`
**USER**: `demlak`
**LD_LIBRARY_PATH**: `/opt/opencascade/lib`
**CSF_StandardLiteDefaults**: `/opt/opencascade/src/StdResource`
**CASROOT**: `/opt/opencascade`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**SSH_AUTH_SOCK**: `/tmp/ssh-GdnCMUbbFkge/agent.833`
**CSF_UnitsDefinition**: `/opt/opencascade/src/UnitsAPI/Units.dat`
**MOZ_PLUGIN_PATH**: `/usr/lib/mozilla/plugins`
**CSF_STEPDefaults**: `/opt/opencascade/src/XSTEPResource`
**DESKTOP_SESSION**: `/usr/share/xsessions/plasma`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/usr/lib/jvm/default/bin:/opt/opencascade/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
**MAIL**: `/var/spool/mail/demlak`
**MMGT_CLEAR**: `1`
**CSF_IGESDefaults**: `/opt/opencascade/src/XSTEPResource`
**HG**: `/usr/bin/hg`
**XDG_SESSION_TYPE**: `x11`
**PWD**: `/home/demlak`
**CSF_GraphicShr**: `/opt/opencascade/lib/libTKOpenGl.so`
**CSF_EXCEPTION_PROMPT**: `1`
**KDE_SESSION_UID**: `1000`
**LANG**: `de_DE.UTF-8`
**CSF_PluginDefaults**: `/opt/opencascade/src/StdResource`
**CSF_LANGUAGE**: `us`
**SSH_ASKPASS**: `/usr/bin/ksshaskpass`
**HOME**: `/home/demlak`
**XDG_SEAT**: `seat0`
**SHLVL**: `1`
**KDE_SESSION_VERSION**: `5`
**XCURSOR_THEME**: `breeze_cursors`
**CSF_UnitsLexicon**: `/opt/opencascade/src/UnitsAPI/Lexi_Expr.dat`
**LOGNAME**: `demlak`
**XDG_SESSION_DESKTOP**: `KDE`
**XDG_DATA_DIRS**: `/usr/share:/usr/share:/usr/local/share`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**CSF_XCAFDefaults**: `/opt/opencascade/src/StdResource`
**DISPLAY**: `:0`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**CSF_MDTVTexturesDirectory**: `/opt/opencascade/src/Textures`
**XDG_CURRENT_DESKTOP**: `KDE`
**PAM_KWALLET_LOGIN**: `/tmp/kwallet_demlak.socket`
**XAUTHORITY**: `/home/demlak/.Xauthority`
**CSF_SHMessage**: `/opt/opencascade/src/SHMessage`
**_**: `/usr/bin/kwrapper5`
**SESSION_MANAGER**: `local/groot:@/tmp/.ICE-unix/911,unix/groot:/tmp/.ICE-unix/911`
**LANGUAGE**: *empty*
**QSG_RENDER_LOOP**: *empty*
**QMLSCENE_DEVICE**: `false`

**Comment by pbek** [comment]
You are currently using the note folder `default`, is the `remotePath` of your notes folder realy `notes` (and not `Notes`)? Locally use seem to use `Notes`.

**Comment by demlak** [comment]
local and remote paths beginning with a capital letter.. same folder.. writing is possible.. files get allways updated.. and synced..
i did not edit any path-info on debug output...

just for info: local path is a mounted ntfs drive.. i don't know, if this is relevant..

**Comment by pbek** [comment]
In your current setting you are using `notes`, please try to change the `Path on your ownCloud server` setting in the note folder settings to `Notes`, you should also be able to select the folder on your server directly from there!

**Comment by demlak** [comment]
works now.. thx a lot

**Comment by pbek** [comment]
Great! Best remove all note folders you don't need in QOwnNotes.
