### ISSUE TITLE
Font and panel color

### ISSUE THREAD

**Issue by Dreadeath** [pbek/QOwnNotes#381]
Is there a way to change font and size of notes and menu names? The same goes to color of panels and borders. I did not found this values in theme editor or Interface section.

**Comment by pbek** [comment]
You can change the note fonts in the `Editor fonts & colors` settings.

As for the rest, you can't change them yet... I could brew that in via the scripting engine if you are up to the task to change stylesheets like <https://github.com/pbek/QOwnNotes/blob/develop/src/libraries/qdarkstyle/style.qss> for the dark theme.

If yes, you can take <http://doc.qt.io/qt-5/stylesheet.html> as reference how to style it.

What do you think? Want to post an example what you like to change as stylesheet?

**Comment by Dreadeath** [comment]
I meant notes' titles, it is too small. As for colors, I see that it is #302F2F I want to change apparently everywhere. And I did not find anything useful related to fonts. So if it could be changable somehow easy, that would be great :)

**Comment by pbek** [comment]
Where are the note titles too small? Can you maybe provide a screenshot?

**Comment by Dreadeath** [comment]
Here, below "search or create n..."
https://github.com/pbek/QOwnNotes/blob/develop/screenshots/screenshot.png

**Comment by pbek** [comment]
So you are talking about the note title in the note list? That would be doable with styles I mentioned in my first comment.

**Comment by Dreadeath** [comment]
Yes, exactly.

**Comment by pbek** [comment]
## 16.11.8
- you can now set **custom stylesheets** to **change the look of QOwnNotes**
  with the help of the new scripting method `script.addStyleSheet()`
  (for [Issue #381](https://github.com/pbek/QOwnNotes/issues/381))
    - there is an example for adding custom stylesheets at
      [custom-stylesheet.qml](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/custom-stylesheet.qml)
    - take a look at the
      [scripting documentation](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/README.md#add-a-custom-stylesheet)
      for more information
    - you can get the object names from the `*.ui` files, for example
      [mainwindow.ui](https://github.com/pbek/QOwnNotes/blob/develop/src/mainwindow.ui)
    - take a look at [Style Sheet Reference](http://doc.qt.io/qt-5/stylesheet-reference.html)
      for a reference of what styles are available

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by pbek** [comment]
@Dreadeath the example already contains the styles to change the note list font and text size. Let me know if you need more help feel free to post your script.

**Comment by Dreadeath** [comment]
I was able to change font size with it, thank you :) Will try to play around it more.

**Comment by pbek** [comment]
Tell me if you need help. ;)
