### ISSUE TITLE
Seems somethings like drop-downs do not work on the third-monitor of a triple-head

### ISSUE THREAD

**Issue by 2devnull** [pbek/QOwnNotes#382]
Moved window to laptop (works), move window to external monitor 1 (works), move window to external monitor 2 (do not work). Not really sure what else other than the drop-downs and menu bar drop downs do not work.

**Comment by pbek** [comment]
Thank you for your report, but I don't think there is something I can do about it. It sounds like an issue of your operating system (which are you using?), possible together with Qt. And I don't have a tripple screen setup at hand to test more...

**Comment by 2devnull** [comment]
I am using Ubuntu 16.04. Yes, it is weird, that it is the only app I have that is not responsive on the 3rd screen. Will check another Qt app and report back.

**Comment by pbek** [comment]
Yes, please check.

**Comment by pbek** [comment]
I will close this issue until there is more information.
