### ISSUE TITLE
fix left panel size

### ISSUE THREAD

**Issue by bdouxx** [pbek/QOwnNotes#383]
Hi,

There is 3 verticals "panels" inQOwnNotes  
In my left "panel" there is only menu( navigation, subfolder,..), so when I resize the full windows I don't want this "panel" reduce or enlarge automatically.
I need a fixed size for this panels, and an automatically adaptation for other.

what do you think about this idea?

**Comment by pbek** [comment]
All the resizing is done by the layout manager and it's extremely hard to influence it.
What if you simply create an other workspace for fullscreen mode?

**Comment by pbek** [comment]
I will close this issue until there is more information.

**Comment by bdouxx** [comment]
I put menu panel to the right, and I have less problem, the resize is better.

**Comment by pbek** [comment]
Great!
