### ISSUE TITLE
Connects to OwnCloud but doesn't sync

### ISSUE THREAD

**Issue by aljawaid** [pbek/QOwnNotes#384]
Hello

Just found QON and think it's a very good quick application.  After installing I am running it form the folder I extracted to as it never created an icon or any files in c:/program files in windows 10.  Not sure if it is meant to be like that.

Anyhow, the main issue is that it successfully connects to owncloud but does not sync anything.  I created a note folder on OC and it never synced to QON.  I created some notes in QON on my pc and it never synced back.  On my lapatop - a third device - the same happens.  The folders are all checked.

What am I doing wrong?

The below information is from my pc.  I have owncloud setup on my shared hosting domain.  I am trying to run QON on my laptop too.

I also get this warning in the log:
`[12:42:57] [warning] libpng warning: iCCP: known incorrect sRGB profile`

And this also in the log:
`[12:43:00] [info] Reply from ownCloud calendar page: "<?xml version=\"1.0\"?>\n<d:multistatus xmlns:d=\"DAV:\" xmlns:s=\"http://sabredav.org/ns\" xmlns:cal=\"urn:ietf:params:xml:ns:caldav\" xmlns:cs=\"http://calendarserver.org/ns/\">\n <d:response>\n <d:href>/XXX.co.uk/cloud/remote.php/caldav/calendars/XXX/</d:href>\n <d:propstat>\n <d:prop>\n <d:resourcetype>\n <d:collection/>\n </d:resourcetype>\n </d:prop>\n <d:status>HTTP/1.1 200 OK</d:status>\n </d:propstat>\n <d:propstat>\n <d:prop>\n <d:displayname/>\n <s:getctag/>\n <cal:supported-calendar-component-set/>\n </d:prop>\n <d:status>HTTP/1.1 404 Not Found</d:status>\n </d:propstat>\n </d:response>\n <d:response>\n <d:href>/XXX.co.uk/cloud/remote.php/caldav/calendars/XXX/personal/</d:href>\n <d:propstat>\n <d:prop>\n <d:resourcetype>\n <d:collection/>\n <cal:calendar/>\n </d:resourcetype>\n <d:displayname>Personal</d:displayname>\n <cal:supported-calendar-component-set>\n <cal:comp name=\"VEVENT\"/>\n <cal:comp name=\"VTODO\"/>\n </cal:supported-calendar-component-set>\n </d:prop>\n <d:status>HTTP/1.1 200 OK</d:status>\n </d:propstat>\n <d:propstat>\n <d:prop>\n <s:getctag/>\n </d:prop>\n <d:status>HTTP/1.1 404 Not Found</d:status>\n </d:propstat>\n </d:response>\n <d:response>\n <d:href>/XXX.co.uk/cloud/remote.php/caldav/calendars/XXX/inbox/</d:href>\n <d:propstat>\n <d:prop>\n <d:resourcetype>\n <d:collection/>\n </d:resourcetype>\n </d:prop>\n <d:status>HTTP/1.1 200 OK</d:status>\n </d:propstat>\n <d:propstat>\n <d:prop>\n <d:displayname/>\n <s:getctag/>\n <cal:supported-calendar-component-set/>\n </d:prop>\n <d:status>HTTP/1.1 404 Not Found</d:status>\n </d:propstat>\n </d:response>\n <d:response>\n <d:href>/XXX.co.uk/cloud/remote.php/caldav/calendars/XXX/outbox/</d:href>\n <d:propstat>\n <d:prop>\n <d:resourcetype>\n <d:collection/>\n </d:resourcetype>\n </d:prop>\n <d:status>HTTP/1.1 200 OK</d:status>\n </d:propstat>\n <d:propstat>\n <d:prop>\n <d:displayname/>\n <s:getctag/>\n <cal:supported-calendar-component-set/>\n </d:prop>\n <d:status>HTTP/1.1 404 Not Found</d:status>\n </d:propstat>\n </d:response>\n</d:multistatus>\n"`

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sun Nov 13 12:43:50 2016`
**Version**: `16.11.9`
**Build date**: `Nov 13 2016`
**Build number**: `2493`
**Platform**: `windows`
**Operating System**: `Windows 10`
**Build architecture**: `i386`
**Current architecture**: `i386`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.7.0`
**Qt Version (runtime)**: `5.7.0`
**Portable mode**: `no`
**Qt Debug**: `0`
**Locale (system)**: `en_GB`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `5`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://web48.secure-secure.co.uk/XXX.co.uk/cloud`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `9.1.0.15`
**appVersion**: `16.09.0`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `My Notes`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `D:/XXX/QOwnNotes`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**activeNoteSubFolder name**: *empty*

## Settings

**AboutDialog/geometry**: `<binary data>`
**Debug/fakeOldVersionNumber**: `false`
**Debug/fileLogging**: `false`
**DistractionFreeMode/editorWidthMode**: `2`
**Editor/CurrentSchemaKey**: `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**EvernoteImportDialog/geometry**: `<binary data>`
**LastUpdateCheck**: `2016-11-13T12:29:40`
**LogWidget/criticalLog**: `true`
**LogWidget/debugLog**: `false`
**LogWidget/fatalLog**: `true`
**LogWidget/infoLog**: `true`
**LogWidget/scriptingLog**: `true`
**LogWidget/statusLog**: `true`
**LogWidget/warningLog**: `true`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `24`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl**: `false`
**PiwikClientId**: `<hidden>`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**ShareDialog/geometry**: `<binary data>`
**ShowSystemTray**: `true`
**SortingModeAlphabetically**: `false`
**StartHidden**: `true`
**TodoDialog/geometry**: `<binary data>`
**TodoDialog/mainSplitterState**: `<binary data>`
**TodoDialog/showCompletedItems**: `0`
**TodoDialog/todoListSelectorSelectedItem**: `Personal`
**UpdateDialog/geometry**: `<binary data>`
**WelcomeDialog/geometry**: `<binary data>`
**allowDifferentNoteFileName**: `true`
**allowOnlyOneAppInstance**: `false`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `true`
**appMetrics/notificationShown**: `true`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**currentWorkspace**: `7f7ff799-efba-42a9-955a-0adfe4817fa0`
**customNoteFileExtensionList**: *empty*
**darkMode**: `true`
**darkModeColors**: `true`
**darkModeTrayIcon**: `true`
**defaultNoteFileExtension**: `txt`
**demoNotesCreated**: `true`
**disableAutomaticUpdateDialog**: `false`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: *empty*
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**imageScaleDown**: `false`
**imageScaleDownMaximumHeight**: `1024`
**imageScaleDownMaximumWidth**: `1024`
**interfaceLanguage**: *empty*
**internalIconTheme**: `true`
**itemHeight**: `15`
**markdownHighlightingInterval**: `0`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `2`
**noteSaveIntervalTime**: `10`
**notesPath**: `D:/XXX/QOwnNotes`
**notifyAllExternalModifications**: `false`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: `https://web48.secure-secure.co.uk/XXX.co.uk/cloud`
**ownCloud/todoCalendarBackend**: `0`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: `https://web48.secure-secure.co.uk/XXX.co.uk/cloud/remote.php/caldav/calendars/XXX/personal/`
**ownCloud/userName**: `XXX`
**previousWorkspace**: `b717429b-f684-4b07-b3bc-9597beb7f44f`
**savedSearches/noteFolder-1**: `Note 2016-11-12T10.45.06, Note 2016-11-12T09.10.56, Note 2016-11-12T09.06.21, Note 2016-11-11T21.43.08`
**showMenuBar**: `true`
**showStatusBar**: `true`
**toolbar/1/items**: `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name**: `mainToolBar`
**toolbar/1/title**: `main toolbar`
**toolbar/2/items**: `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInset_code_block`
**toolbar/2/name**: `formattingToolbar`
**toolbar/2/title**: `formatting toolbar`
**toolbar/3/items**: `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name**: `insertingToolbar`
**toolbar/3/title**: `inserting toolbar`
**toolbar/4/items**: `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name**: `encryptionToolbar`
**toolbar/4/title**: `encryption toolbar`
**toolbar/5/items**: `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name**: `windowToolbar`
**toolbar/5/title**: `window toolbar`
**toolbar/6/items**: `action_Quit`
**toolbar/6/name**: `quitToolbar`
**toolbar/6/title**: `quit toolbar`
**toolbar/size**: `6`
**workspace-7f7ff799-efba-42a9-955a-0adfe4817fa0/name**: `Home`
**workspace-7f7ff799-efba-42a9-955a-0adfe4817fa0/noteSubFolderDockWidgetVisible**: `true`
**workspace-7f7ff799-efba-42a9-955a-0adfe4817fa0/windowState**: `<binary data>`
**workspace-b717429b-f684-4b07-b3bc-9597beb7f44f/name**: `XXX`
**workspace-b717429b-f684-4b07-b3bc-9597beb7f44f/noteSubFolderDockWidgetVisible**: `true`
**workspace-b717429b-f684-4b07-b3bc-9597beb7f44f/windowState**: `<binary data>`
**workspaces**: `b717429b-f684-4b07-b3bc-9597beb7f44f, 7f7ff799-efba-42a9-955a-0adfe4817fa0`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\XXX\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `XXX-HOST`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**destination**: `"D:\XXX\Website\Website Software\ownCloud\_Software\QOwnNotes"`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\XXX`
**LOCALAPPDATA**: `C:\Users\XXX\AppData\Local`
**LOGONSERVER**: `\\IMRAN-HOST`
**NUMBER_OF_PROCESSORS**: `2`
**OS**: `Windows_NT`
**Path**: `C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Skype\Phone\;C:\Users\XXX\AppData\Local\Microsoft\WindowsApps;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_IDENTIFIER**: `x86 Family 6 Model 42 Stepping 7, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `2a07`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**PROMPT**: `$P$G`
**PSModulePath**: `C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\`
**PUBLIC**: `C:\Users\Public`
**qownnotesCommand**: `"D:\XXX\Website\Website Software\ownCloud\_Software\QOwnNotes"\QOwnNotes.exe --after-update C:\Users\XXX\AppData\Local\Temp\QOwnNotes-rZ8884-updater.bat `
**SESSIONNAME**: `Console`
**source**: `C:\Users\XXX\AppData\Local\Temp\QOwnNotes-rZ8884.zip`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\XXX\AppData\Local\Temp`
**TMP**: `C:\Users\XXX\AppData\Local\Temp`
**unzipCommand**: `C:\Users\XXX\AppData\Local\Temp\QOwnNotes-rZ8884-unzip.exe -o C:\Users\XXX\AppData\Local\Temp\QOwnNotes-rZ8884.zip -d "D:\XXX\Website\Website Software\ownCloud\_Software\QOwnNotes"`
**unzipExecutable**: `C:\Users\XXX\AppData\Local\Temp\QOwnNotes-rZ8884-unzip.exe`
**USERDOMAIN**: `XXX-HOST`
**USERDOMAIN_ROAMINGPROFILE**: `XXX-HOST`
**USERNAME**: `XXX`
**USERPROFILE**: `C:\Users\XXX`
**windir**: `C:\WINDOWS`

**Comment by pbek** [comment]
Hi, @aljawaid, thank you for trying QOwnNotes. :)
As for now there is no installer. You can unzip the QOwnNotes folder where ever you like.
As for the syncing. The note syncing is done by your ownCloud sync client (or whatever you like for syncing)... The notes are plain text files.

Does that answer your questions?

**Comment by aljawaid** [comment]
Thank you but then why is it not syncing from OC to QON? It says connection is fine.


From: Patrizio Bekerle
Sent: Sunday, 13 November 2016 17:47
To: pbek/QOwnNotes
Reply To: pbek/QOwnNotes
Cc: IJ; Mention
Subject: Re: [pbek/QOwnNotes] Connects to OwnCloud but doesn't sync (#384)



Hi, @aljawaid<https://github.com/aljawaid>, thank you for trying QOwnNotes. :)
As for now there is no installer. You can unzip the QOwnNotes folder where ever you like.
As for the syncing. The note syncing is done by your ownCloud sync client (or whatever you like for syncing)... The notes are plain text files.

Does that answer your questions?

-

**Comment by pbek** [comment]
QOwnNotes isn't supposed to sync your notes, the ownCloud sync client does that. QOwnNotes just handles the access to trashed notes, note versions and note sharing.

**Comment by aljawaid** [comment]
I'm very confused, please help me understand?

I have text notes (in a dedicated folder) saved on owncloud.
I install QOwnNotes
**Notes created in QON don't upload to OC folder and vice-versa?**

**Comment by pbek** [comment]
When you ran QOwnNotes for the first time you have chosen a folder where it should put in the notes. This folder is supposed to be in inside your ownCloud folder so that the sync client syncs it.
If you want to view the notes in the web you can install the ownCloud notes client (as stated on the webpage and in the ownCloud settings).
