### ISSUE TITLE
Todo - Can't save

### ISSUE THREAD

**Issue by dxerw** [pbek/QOwnNotes#385]
Heya,

I am using a CalDAV server for calendar, connection is working and stuff (I can see the calendars) but when I open the todo list I can't see any items and I can't add/save any new ones. The save option is greyed out.

Any ideas what is going on?

Thanks!

**Comment by dxerw** [comment]
It seems like you just have to press enter in order to save/add a new note and not the save button.. My bad -.-"

**Comment by pbek** [comment]
I'm not entirely sure what you did, but I'm glad you solved your issue. :)
