### ISSUE TITLE
Feature request: Import CalDAV task as note

### ISSUE THREAD

**Issue by Letterus** [pbek/QOwnNotes#387]
I'm using QOwnNotes for a while and due to your immense development activities now it's nicely embedded into my workflow using OS X.

One improvement would make it even better to use for me:
When I'm working outside/mobile I'm used to take notes using my 2Do app/the CalDAV based repository. I can view this task (containing the note) nicely using the tasks view of QOwnNotes. But to import the note into my file based repository I have to copy and paste title und text of the task. It would be more convenient if I could just click "Import as note" (and then "remove") at the view of the task.

**Comment by pbek** [comment]
If you are referring to the OS X updater, I quite like it myself too. :)

So you want to have an `Import as note` button in the todo dialog that creates the current task as note, am I correct?

**Comment by Letterus** [comment]
Yep! :-)

**Comment by pbek** [comment]
## 16.11.10
- there now is a new button `Import as note` in the todo dialog that imports the current todo item as new note

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Letterus** [comment]
Hm, I'd like to, but 16.11.9 does not show any available update yet.

**Comment by Letterus** [comment]
Now the update was shown.

And importing works! Very great feature again. Thanks a lot! 👍:-)

**Comment by pbek** [comment]
Great to hear!
