### ISSUE TITLE
Scripting hook for opening a note

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#389]
I want the app to export current note file name to external file so I could use it in a shell script.

Currently I can do that using custom action button or with `onNoteStored` hook. But it would be much better to use something like `onNoteOpen` hook.

Could you implement a hook for opening a note?

**Comment by pbek** [comment]
You are kind of able to do this even now with a timer like on the bottom of the script <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/example.qml>.

**Comment by Maboroshy** [comment]
I'll have to check if a current note changed every N seconds and then run external command. Considering most of the time the app is minimized to tray that doesn't look like a good use of CPU time to me. Though it's possible.

**Comment by pbek** [comment]
Just thinking, because creating a hook for you and documenting it properly is tedious work and takes about an hour. ;)

**Comment by Maboroshy** [comment]
I can do with an undocumented one. My experience with documenting tells it can take more time then coding.

**Comment by pbek** [comment]
If there is no example and all it's still much work and will be usable only by you. :stuck_out_tongue_winking_eye: 

Why don't you learn to code anyway? :smirk_cat: The world would have much to profit from it!

**Comment by Maboroshy** [comment]
I do learn but I learn Python for now. And sadly I have not yet started to rewrite my script on it to make it crossplatform, which looks like an appropriate first project.

**Comment by pbek** [comment]
Next you learn PyQt and then C++ with Qt. Bingo! 😸

**Comment by pbek** [comment]
## 16.11.12

- added a new scripting hook `noteOpenedHook(note)` that is called every
  time a note is opened
- added some documentation for all scripting hooks to the
  [scripting documentation](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/README.md)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment]
All works for me. That will allow me to integrate my shell script better. I'm going to include some qml's in the next release at last.

**Comment by pbek** [comment]
Great! ;)
