### ISSUE TITLE
Qt UI does not follow KDE's icon set  on Fedora 23

### ISSUE THREAD

**Issue by xenithorb** [pbek/QOwnNotes#39]
![snapshot2](https://cloud.githubusercontent.com/assets/10273878/12703633/f08a12ee-c815-11e5-8c4b-d2c57b5aac38.png)

I have breeze-dark set as my icon theme for obvious reasons, and you can see that the icon set being use is the default breeze theme.

**Comment by pbek** [comment]
Hi @xenithorb, thank you for your report!
So far QOwnNotes doesn't follow any icon set, it has it's own icons. I just borrowed various Breeze SVG icons from KDE as icons for QOwnNotes.
A full set of dark themed icons would be great...

**Comment by pbek** [comment]
It was quite some work, but I did it.

In v0.97 QOwnNote now uses default **freedesktop theme icons**
  - for Windows and OS X there is a bundled fallback theme with Breeze icons 
    that will be used when the operating system hasn't a theme set
  - this allows the usage of QOwnNotes with **dark system themes**

Could you be so kind and test v0.97 when it is out.

**Comment by pbek** [comment]
v0.97 is out now. :grin:

**Comment by xenithorb** [comment]
![qownnotes_icons_fixed](https://cloud.githubusercontent.com/assets/10273878/12983950/a228c440-d0b9-11e5-9351-05e0e65289bf.png)

Works great, Thanks for your hard work!

**Comment by pbek** [comment]
Perfect, thank you!
Although I have to do a workaround for OS X... No icons at all at the moment even tho it worked on my Macbook while developing...

**Comment by pbek** [comment]
Can you please verify that it still works in v0.98 and that the search bar in the note text edit (`Ctrl + F`) also uses theme icons?

**Comment by xenithorb** [comment]
![qownnotes_icons_fixed3](https://cloud.githubusercontent.com/assets/10273878/13009446/66fcdf26-d16a-11e5-9627-3f9af0158b78.png)

The icons are of the correct type, but the "search backward" placement is right-aligned and z-indexed below the scrollbar

**Comment by pbek** [comment]
Thank you for reporting back. Oh, what would I give if I could fix that issue with a CSS z-index, but that problem lies much deeper...

**Comment by pbek** [comment]
I finally found a fix for that, will be in the next version. Thank you for pushing me. ;)
