### ISSUE TITLE
ubuntu16.04 中文无法输入

### ISSUE THREAD

**Issue by lujob** [pbek/QOwnNotes#392]
ubuntu16.04 中文无法输入

**Comment by pbek** [comment]
Could you please explain that in English.

**Comment by lujob** [comment]
ubuntu16.04 Unable to enter Chinese(无法输入中文)

**Comment by pbek** [comment]
Can you please explain in more detail and step by step what you did, what happened and what you expected.

**Comment by lujob** [comment]
Use deb, or snap, installed QOwnNotes, can not switch the Chinese input method, but can not enter the Chinese input method. The answer from the Internet search, the problem is probably QT bug, resulting in the Chinese input problem.
The above content is google online translation

**Comment by pbek** [comment]
@LiangWei88 can you use the Chinese input method? @piyo-gh do you have similar problems in Japanese? I ask in case anyone of you is using QOwnNotes under Ubuntu 16.04.

**Comment by lujob** [comment]
The problem with @ piyo-GH is not the same, his problem is to adjust the size of the font, this I have not tried.
My question is to install the application, the use of the process, can only enter English, can not enter Chinese. But the original use of other text editor or text input tool But the Chinese can show,

**Comment by pbek** [comment]
I wasn't comparing any issue of @piyo-gh with your issue, I just asked if he has similar problems in Japanese. :smile_cat:

**Comment by lujob** [comment]
Sorry, translation software translates into meaning misunderstanding

**Comment by Maboroshy** [comment]
Does other Qt applications like Kwrite or Kate have similar problems?

**Comment by pbek** [comment]
Yes, good question!

**Comment by pbek** [comment]
I will close this issue until there is more information.
