### ISSUE TITLE
Frontmatter - yaml

### ISSUE THREAD

**Issue by JLKM** [pbek/QOwnNotes#393]
Really nice project, this. Going a long way at the road of turning markdown files into the next way of building databases (after SQL and NoSQL). To get a little further it would be really nice to have the ability to add your own frontmatter at the top. Have testet with yaml, but got the following filename: ---.md 
Frontmatter might also be the way to kick out the SQlite dependency for handling tags and todos.
Furthermore an opening for fronmatter would make the files directly usable for a static site generator (SSG) and QOwnNotes would suddenly become a kind of admin or editorial SSG-frontend. This could tear down old walls and replace them with a bridge between note-taking and site generating.

**Comment by pbek** [comment]
Thank you for your suggestion! Are you talking about something like <https://jekyllrb.com/docs/frontmatter/>? Currently there is a scripting hook to modify the html that will be shown in the preview or html export. It also is possible to define custom actions to run external programs or do that every time a note is modified.

Can you please explain in more detail what you are thinking of and/or maybe show some examples?

**Comment by JLKM** [comment]
Your example with frontmatter/yaml is spot on. Yaml is in my knowledge the most widespread way of writing frontmatter in markdown documents.
Frontmatter is meta-data, square and simple, and it makes possible for markdown documents to be self-contained and selv-explanatory. At the same time you get rid of any dependency (SQlite etc.).
It would be an great feature for your system to offer "inside-tags" like:
---
tags:
- Tag1
- Tag2
---
These tags would then be reusable in a static site generator. And you would be able to move markdown-files between folders in QOwnNotes without lossing tags - due to the dependency on the folder based SQlite-file.
But have I missed something? Is it possible to do most of all this now by tweaking a little?

**Comment by pbek** [comment]
Tagging in notes as note-text was discussed several times (last time at #379) and beside that it would overthrow the current tagging system and that everyone has different opinions on how the text should look like, I still don't like the idea of QOwnNotes programmatically editing the user's notes...

Was that the tweaking you were talking about?

**Comment by JLKM** [comment]
As goes for [#379](https://github.com/pbek/QOwnNotes/issues/379) I don't suggest any in-content tagging like `# something`. Frontmatter is in-file, yes, but it's per definition outside content. It's an add-on - not supposed to be shown anywhere.
I don't se any need for programmatically changes in the markdown files with yaml-frontmatter. On contrary. The tag-based navigation in QOwnNotes could be build on a traversal of the yaml-tags in frontmatter. No write - only read.
Tags, any meta-data for that matter, outside the markdown is a showstopper for me. Sorry.
In most other areas QOwnNotes seems to be a frontrunner in terms of file-system-as-a-database.

**Comment by pbek** [comment]
So who should interpret the Frontmatter then and what are you expecting that QOwnNotes should do?

**Comment by pbek** [comment]
Even just entering your proposed Frontmatter code would currently mess up the markdown highlighter and the preview (as well as any other markdown editor that anyone would use to few their files) and would contradict the "first line is a headline and used as filename" rule, that is used most often.

**Comment by pbek** [comment]
Although something like that would at least not be misinterpreted by the markdown parser and the preview:

```
<!---
tags:
- Tag1
- Tag2
--->
```

Leaves the question open what exactly should happen when such a piece of text is found...

**Comment by JLKM** [comment]
My suggestion aims at integrating note-taking and site generators. Only real frontmatter is capable of doing that. So the hack with `=====` above won't work.
1. It should right away be possible to YAML-enable QOwnNotes just by suppressing everything between `---` and `---` from being evaluated to create the file name.
2. In the long run it should also be possible to replace the SQlite-based tags with tags retrieved from the documents `tags:`-tag.
- Implementing the former would make QOwnNotes a fine note-taking/site generating admin tool.
- Omplementing the latter would in my opinion take QOwnNotes to a new level of modern, open content management, where noone seems to be today.

**Comment by pbek** [comment]
- Can you please define what "real frontmatter" is for you? And how a note should look like in your opinion?
- So you are aiming for people who want to call an external site-generator that can interpret a frontmatter and use QOwnNotes as editor to edit their pages?
    - What would be the job of QOwnNotes (beside not getting screwed up because of the violated markdown syntax in the note editor and preview)?

About replacing the SQLite database.. I guess about 99% of the users would like to add tags with a click.

And for the 1% that want to use tags in the note file (despite the fact that everyone has their own opinion on how these tags should be placed in the text file) the note would be needed to be parsed every time the user types in some new text and the tag assignment for the whole note folder (with possibly 1000s of notes) would be needed to be regenerated...
Of course all interactions with tags in the user interface would need to change too, because no tags can be added in the interface...
Am I correct?

**Comment by JLKM** [comment]
A self-containg and self-explaining markdown document - example:
```
---
author: Jan Larsen
category: markdown
tags:
  - note-taking
  - static site generators
type: note
---
# Let's fusion note-taking and site generating
I might really write a lot here, but you should be spared from that for the time being...
```
On second thought:
Your SQlite-tags can easily co-exits with a YAML-enabled version of QOwnNotes.
In my view first priority would be, that a YAML frontmatter is allowed in the markdown documents, and that it doesn't affect the generated file name. Second priority (optional) might be, that your SQlite-tags gets extracted automatically from the reserved `tags:` key in YAML on save.
Each one should be doable, and the result would be awesome.

**Comment by pbek** [comment]
To allow a frontmatter block, like you suggested I would need to write my own markdown + frontmatter parser and highlighter, plus adapting the the markdown2html converter to hide the frontmatter block.

But it's already possible to allow other first lines than the headline. You can turn that on in the general settings.

**Comment by JLKM** [comment]
Ups. I missed that Setting/general: Allow note file name to be different from headline
Now I get file names like this: "Note 2016-11-24T12.07.36", and that's OK.
Furthermore the options in your newly built-in scripting system seem countless. It's possible to [rename filenames](https://github.com/pbek/QOwnNotes/commit/55ab43003f73d4833de0462554004efe9ee42168) and even [push fixed tags to SQlite on save](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/favorite-note.qml)
So I suspect, it might also be possible to search YAML-tags and push them to SQlite. At least I'll dig into that.
The scripting-feature in QOwnNotes seems quite powerfull. So I'm still in.
Thank you for your advice, and keep up the good work.

**Comment by pbek** [comment]
Yes, you can add tags to the current note via script. Please let me know with what scripting-solution you came up with! I guess you would still need a command to remove all tags of the current note...

**Comment by pbek** [comment]
just for reference: #323 was also about in-note tags

@JLKM: did you already come up with something great? in the latest release of QON I rewrote the highlighter from scratch... will make us more flexible in the future...
@jd666, your markdown tables are implemented too now ;)
