### ISSUE TITLE
ToDo.txt support

### ISSUE THREAD

**Issue by mimf** [pbek/QOwnNotes#394]
I wonder if Todo.txt support would be something you'd be interested in doing.

The idea behind todo.txt can be seen here: http://todotxt.com/

**Comment by pbek** [comment]
Can you please define what "Todo.txt support" means for you and how it should integrate into QOwnNotes (without breaking anything already existing).

**Comment by Maboroshy** [comment]
That would be good. But I don't see how it integrates with the app without being app-in-app. There are some dedicated apps to manage ToDo.txt.

**Comment by mimf** [comment]
yes, there are some apps to manage todo.txt. However, I found them all to be.. less than ideal (atleast on linux, haven't tried anything else). QOwnNotes is pretty good at what it does, perhaps it could also be pretty good at managing todo.txts. 

So, what I define by "todo.txt support":
- Support to search/add/organize by project(#) and context (@);
- Support to re-organize by priority (In todo.txt, priority is handled by adding a letter to the task, for example (A) or (C));

And that's basically it I suppose. The "rules" for todo.txt are here: https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format

**Comment by pbek** [comment]
@mimf 

> Support to open/edit .txts;

This already works.

> Support to search/add/organize by project(#) and context (@);

How do you define `search/add/organize`? you can already search for text and add text...

> Support to organize by priority (In todo.txt, priority is handled by adding a letter to the task, for example (A) or (C));

What is "organizing" for you?
And how should integrate that all into the current app without being an app-in-app, like @Maboroshy mentioned?

**Comment by Maboroshy** [comment]
> Support to search/add/organize by project(#) and context (@);
Support to organize by priority (In todo.txt, priority is handled by adding a letter to the task, for example (A) or (C));

That can be done on a text level with a small script. What OS do you use?

**Comment by mimf** [comment]
I'm still thinking how to do this.. Honestly, I don't think qownnotes is the right software for this kind of task. I was thinking something along the lines of having checkboxes to mark tasks as done, a box to add tasks, so on and so forth, but again, bad idea.

You can close this. Sorry for the trouble!

**Comment by pbek** [comment]
Unfortunately checkboxes are not supported by QTextEdit...
I'll close the issue unless someone comes up with an idea.

**Comment by gerroon** [comment]
Hi

Is it still the case that QTextEdit does not support checkboxes like Github markdown can do?

thanks

**Comment by pbek** [comment]
You can simulate checkboxes with a script from the script repository.

**Comment by gerroon** [comment]
thanks I will check it out
