### ISSUE TITLE
Ideas on features to implement or enhance

### ISSUE THREAD

**Issue by sardinas9** [pbek/QOwnNotes#395]
Hello Patrizio!

I would like to submit to your consideration some ideas of features to implement or enhance in QOwnNotes. Those are some of the things that I miss the most in my daily work with the application.

- The possibility to send selected text from another application directly to a open note in QON at the background in order to avoid stop reading to select and copy text, switch to QON window, paste the text and switch back to the previous application to continue reading.

- The possibility to return to the line I was working on in a previous note without having to scrolling down from the beginning when working with two or more notes simultaneously.  (Remember cursor position in note history)

 - The possibility to add Sentence Case and Proper Case to the existing upper and lower case formatting. The options can be cycled through with the same keyboard shortcut (Ctrl+Shift+U).

- The possibility to change the highlight color of search results in the light schema. 

Thank you for you great work!

**Comment by pbek** [comment]
Thanks a lot for your suggestions and for your kind words!

> The possibility to send selected text from another application directly to a open note in QON at the background in order to avoid stop reading to select and copy text, switch to QON window, paste the text and switch back to the previous application to continue reading.

I'm not sure if that's technically possible. Do you know an application that does such a thing?

> The possibility to return to the line I was working on in a previous note without having to scrolling down from the beginning when working with two or more notes simultaneously. (Remember cursor position in note history)

That already works, the note history saves the cursor position and the note bookmarks do so as well.
See <http://www.qownnotes.org/shortcuts/QOwnNotes> for the shortcuts.

> The possibility to add Sentence Case and Proper Case to the existing upper and lower case formatting. The options can be cycled through with the same keyboard shortcut (Ctrl+Shift+U).

Can you please make examples for the two cases?

> The possibility to change the highlight color of search results in the light schema.

I'm not sure if the color can be changed by Qt. Maybe via Stylesheets. If that's the case you could already modify the color like in this example: <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/custom-stylesheet.qml>

**Comment by pbek** [comment]
And can you do me a favor and create different feature requests for all your three (or 4 if you wanted more from the 2.) remaining requests. I find them all interesting.

**Comment by sardinas9** [comment]
- I created a separate feature request for 1 (text capture) and 3 (change case). 
- I didn't knew the no 2 Remember cursor position in note history) was already done Thanks for that! 
- I have reviewed the docs at https://github.com/pbek/QOwnNotes/tree/develop/doc/scripting. Sadly I don't have any programming experience and it's very confusing to me. Sorry abou that.

**Comment by pbek** [comment]
Ok, for reference: Your feature requests are #396 and #397.
Please also create a feature request for your 4. suggestion, it needs to checked if that is technically possible.
