### ISSUE TITLE
Add Sentence case and Proper (Start) case 

### ISSUE THREAD

**Issue by sardinas9** [pbek/QOwnNotes#396]
Add Sentence Case and Proper Case to the existing upper and lower case formatting. The options can be cycled through with the same keyboard shortcut (Ctrl+Shift+U).

“Sentence Case”. This capitalises the first letter of each sentence, and converts the rest of the text to lower case. So the first letter after every full stop is automatically converted into a capital letter.

“Proper Case” or Start case (initial caps) A simplified variant of title case that capitalises all words, including articles, prepositions, and conjunctions (So Every Word Has Its First Letter Capitalised Like This).  Title Case would be preferred but I suppose is more difficult to implement because of the exclusion of  articles, prepositions, and conjunctions. 

I got the definitions from here: http://caseconverter.com/ and here https://en.wikipedia.org/wiki/Letter_case

**Comment by pbek** [comment]
Thank you for the idea and the information.

**Comment by quailiff** [comment]
How does this look? [quailiff/QOwnNotes/tree/feature/text-manipulation](https://github.com/quailiff/QOwnNotes/tree/feature/text-manipulation)

**Sentence case**

![sentence-case-1](https://cloud.githubusercontent.com/assets/16974626/26562939/1083100e-4499-11e7-80e4-a9b02f54afa6.png)

**becomes:**

![sentence-case-2](https://cloud.githubusercontent.com/assets/16974626/26562942/10927350-4499-11e7-87b2-293a2039d63c.png)

---

**Start case**

![start-case-1](https://cloud.githubusercontent.com/assets/16974626/26562941/10910b5a-4499-11e7-996d-34bdc5761fad.png)

**becomes:**

![start-case-2](https://cloud.githubusercontent.com/assets/16974626/26562940/10913670-4499-11e7-9335-9eae57618df2.png)

**Comment by pbek** [comment]
@quailiff this already looks great, good job there! Do you see a way to integrate this two new menu entries into the old `Toggle text case` functionality so that it rotates through all available text cases (including your two new one). We don't really want new menu entries. 😄

**Comment by quailiff** [comment]
Yes, makes sense - all I need to do is compare the text with the sentence-cased and start-cased versions of itself to see what the next appropriate case conversion is. Will look at that tonight!

**Comment by pbek** [comment]
Great, I'm looking forward to it! :party:

**Comment by quailiff** [comment]
Just thinking aloud...Not all strings will have distinct lowercase, uppercase, sentence case, and start case transformations. In order to determine the next appropriate transformation without relying on some sort of state tracker (what's the last transformation we used), we'll need to identify distinct transformation sequences.

If we arrange the transformations in the following order...

1. lowercase
2. UPPERCASE
3. Start Case
4. Sentence case

We can obtain the following transformation sequences:

- Trivially, strings that don't contain any cased characters have only one transformation.
- `a` :arrow_right: `A` ➡️ `a` (2 distinct transformations; start case and sentence case elided)
- `1a` ➡️ `1A` ➡️ `1a` (2 distinct transformations; start case and sentence case elided)
- `a a` :arrow_right: `A A` :arrow_right: `A a` :arrow_right: `a a` (3 distinct transformations; start case elided)
- `ab` ➡️ `AB` ➡️ `Ab` ➡️ `ab` (3 distinct transformations; sentence case elided)
- `1a a` ➡️ `1A A` ➡️ `1a A` ➡️ `1a a` (3 distinct transformations; sentence case elided)
- `ab a` ➡️ `AB A` ➡️ `Ab A` ➡️ `Ab a` ➡️ `ab a` (4 distinct transformations; nothing elided)

Will need to think about whether there are any other transformation sequences.

**Comment by pbek** [comment]
If detecting the state is to complex you could track the state for a distinct position in the note and amount of selected characters (just track these two extra parameters along with the case-state). This way you can start with the first state if an other text is selected...

**Comment by quailiff** [comment]
I added the function `QString Utils::Misc::cycleTextCase(QString text)`. **All the below to say that I think it works properly - it passes the seven test cases below.**

Examining the possible combinations of `Lower == Upper == Start == Sentence`, `Lower == Upper == Start && Lower != Sentence`, etc. - if I did the math correctly:

- There is 1 combination where all four are equivalent
- There are 4 combinations where *only* three are equivalent (4 choose 3)
- There are 6 combinations where *only* two are equivalent (4 choose 2)
- There is 1 combination where none are equivalent
- 1 + 6 + 4 + 1 = 12

There are seven actual possibilities out of the twelve above; therefore, there are seven test cases. These are 1, 4, 5, 8, 10, 11, and 12 in the table below.
 
```
| #|Lower|Upper|Start|Sentence|           Equivalencies           |
|==|=====|=====|=====|========|===================================|
| 1|1    |     |     |        |Lower == Upper == Start == Sentence|
| 2|     |     |     |        |Lower == Upper == Start            |
| 3|     |     |     |        |Lower == Upper == Sentence         |
| 4|1a   |1A   |     |        |Lower == Start == Sentence         |
| 5|a    |A    |     |        |Upper == Start == Sentence         |
| 6|     |     |     |        |Lower == Upper                     |
| 7|     |     |     |        |Lower == Start                     |
| 8|1a a |1A A |1a A |        |Lower == Sentence                  |
| 9|     |     |     |        |Upper == Sentence                  |
|10|a a  |A A  |     |A a     |Upper == Start                     |
|11|aa   |AA   |Aa   |        |Start == Sentence                  |
|12|a aa |A AA |A Aa |A aa    |                                   |
```
 
Of the remaining five:
 
`2`: `Lower == Upper` implies that `Lower == Upper == Start == Sentence` (necessarily a subset of 1)
`3`: `Lower == Upper` implies that `Lower == Upper == Start == Sentence` (necessarily a subset of 1)
`6`: `Lower == Upper` implies that `Lower == Upper == Start == Sentence` (necessarily a subset of 1)
`7`: I can't think of an example where `Lower == Start && Start != Sentence`; I think that perhaps `Lower == Start` implies that `Start == Sentence`
`9`: I can't think of an example where `Upper == Sentence && Start != Sentence`; I think that perhaps `Upper == Sentence` implies that `Start == Sentence`

**Comment by quailiff** [comment]
**Two other decisions to be made related to sentence case:**

1. Should the menu item name now be changed from "Toggle text case" to "Cycle text case"?
2. What kind of behaviour would users expect of `toSentenceCase()` - what's the "sane default?"

I wrote the `toSentenceCase()` function to split sentences *only* after `.?!`. This means that:

```
a sentence with a hard line
break in the middle.

a sentence that doesn't end with a period
a separate, unrelated sentence
```

will be transformed into:

```
A sentence with a hard line
break in the middle.

A sentence that doesn't end with a period
a separate, unrelated sentence
```

The alternative would be to treat every line-break as sentence-ending:

```
a sentence with a hard line
break in the middle.

a sentence that doesn't end with a period
a separate, unrelated sentence
```

would be transformed into:

```
A sentence with a hard line
Break in the middle.

A sentence that doesn't end with a period
A separate, unrelated sentence
```

**Comment by pbek** [comment]
This looks nicely done, great job. I will test it today!

**Comment by pbek** [comment]
Superbly done, @quailiff. I love your implementation, you showed a lot of skill! I renamed the menu entry according to your suggestion.

**Comment by pbek** [comment]
## 17.06.0
- you can now cycle through text cases of the selected text instead of just 
  toggling uppercase and lowercase with the shortcut <kbd>Ctrl</kbd> +
  <kbd>⇧</kbd> + <kbd>U</kbd>
    - you now can also use *proper case* and *sentence case*
    - this was superbly done by @quailiff, a big thank you

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by quailiff** [comment]
Awesome, thanks!

**Comment by pbek** [comment]
A big thank you to you!

**Comment by repsorp** [comment]
Hi, 

"Cycle Text Case" `Ctrl+Shift+U` shortcut doesn't work for me (the only shortcut that doesn't work)
Trying to assign a new one doesn't work either
I did not find any duplicate of this shortcut in the system shortcuts
"Cycle Text Case" if selected from menu works fine

![Image](https://github.com/user-attachments/assets/b06d56b5-ddaa-4785-9e7b-dac69b4a25dc)

```
General Info
Current Date: Sat Jun 28 22:47:07 2025
Version: 25.6.5
Build date: Jun 23 2025
Build number: 1196
Platform: linux (wayland)
Operating System: Ubuntu 24.04.2 LTS
Build architecture: x86_64
Current architecture: x86_64
Release: Launchpad PPA Qt6
Qt Version (build): 6.4.2
Qt Version (runtime): 6.4.2
Portable mode: no
```

**Comment by pbek** [comment]
Can you please try opening QOwnNotes in a new session, see https://www.qownnotes.org/getting-started/cli-parameters.html and open a new issue, @repsorp?
