### ISSUE TITLE
Send selected text to QOwnNotes

### ISSUE THREAD

**Issue by sardinas9** [pbek/QOwnNotes#397]
Hello Patrizio.

Send selected text from another application directly to a open note in QON at the background in order to avoid stop reading to select and copy text, switch to QON window, paste the text and switch back to the previous application to continue reading.

I know of one application than can partially do the job:

Info-Base http://freeware.persoft.ch/program_en.htm. 
Pros: You can select and copy text and then redirect the clipboard content to Info-base with a custom shortcut (Ctrl-Alt+Q by default). 
Cons: It creates a new note for each entry  (not optional) and pops up to foreground in each capture (Intrusive).

**Comment by pbek** [comment]
We would at least need #44 to create such a thing. And I still am in dispute with myself if I want all the problems #44 might cause because of usage of private APIs and so on...

**Comment by Maboroshy** [comment]
[Bash-note](https://github.com/Maboroshy/Bash-note) does that on Linux. Current release sends selected text and parts of webpages including images to predefined note. Sending to currently opened note is implemented in test build and will be in the next release. It's possible to use several shortcuts to send text to different predefined notes.

**Comment by richarson** [comment]
If it gives an idea, Basket (http://basket.kde.org/) has a global shortcut to paste clipboard to current note/basket, here's a screenshot:

![screenshot_20161127_212417](https://cloud.githubusercontent.com/assets/1638444/20653190/12612c94-b4e8-11e6-8f51-c39134a9a085.png)

**Comment by richarson** [comment]
Which is exactly what #44 is about... should have checked before posting :)

**Comment by pbek** [comment]
Thank you for your find @richarson. Basket is a KDE program and KDE is handling the global shortcuts for it. I would _really_ love to just write KDE software and don't have to reinvent a lot of wheels...

**Comment by richarson** [comment]
Yeah, I know, and a KDE 4 program at that.

There's [KGlobalAcces](https://inqlude.org/libraries/kglobalaccel.html) but it probably depends on too much extra stuff. right?

https://api.kde.org/frameworks/kglobalaccel/html/kglobalaccel-dependencies.html

**Comment by pbek** [comment]
Yes, that's all done by the KDE libraries...

**Comment by bepolymathe** [comment]
@Maboroshy Very interresting bash-note.

And for curious, i use [save to file](https://addons.mozilla.org/fr/firefox/addon/save-text-to-file/?src=userprofile) to capture some web citation in txt format in my qownnotes directory. No totally useful solution but it works.

**Comment by Maboroshy** [comment]
I'm currently rewriting bash-note in Python. It will be much better and cross-platform. Hope I'll start uploading some parts of it to QON script repository soon.

Txt is a good thing, but I like bringing pictures with text.

**Comment by bepolymathe** [comment]
Oh super. I will wait for that !
And, yes only txt is limitation in my workflow...

**Comment by pbek** [comment]
You may want to test https://github.com/pbek/QOwnNotes/issues/44, more coming soon

**Comment by pbek** [comment]
## 20.3.9
- you can now also manage **global keyboard shortcuts** in the *Shortcuts settings*
  (for [#44](https://github.com/pbek/QOwnNotes/issues/44))
    - there you can set a global shortcut to every action of the main menu,
      including custom scripting actions
    - you can also search for global shortcuts in the `Search for shortcut` line edit
    - by default there are no global shortcuts activated

With that in place you can now easily write a script in QOwnNotes to create a new note and paste text from the clipboard. https://docs.qownnotes.org/en/latest/scripting/methods-and-objects/ is your friend.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
