### ISSUE TITLE
Notes Preview - Right Aligned

### ISSUE THREAD

**Issue by kuruptfp** [pbek/QOwnNotes#398]
Is there a setting I'm missing. My Notes Preview is showing everything on the right side.

**Comment by pbek** [comment]
Do you have `View text right to left` enabled in the `Preview fonts` settings?

**Comment by pbek** [comment]
If not...
Can you please post the output from the debug settings.

**Comment by kuruptfp** [comment]
That was it.. Sorry couldn't didnt' know that I clicked that. Great program by the way.

**Comment by pbek** [comment]
Thank you, @kuruptfp!
