### ISSUE TITLE
Change the highlight color of search results in the light schema

### ISSUE THREAD

**Issue by sardinas9** [pbek/QOwnNotes#399]
Change the highlight color of search results in the light schema.

**Comment by pbek** [comment]
I copied the text from #395:

I'm not sure if the color can be changed by Qt. Maybe via Stylesheets. If that's the case you could already modify the color like in this example: https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/custom-stylesheet.qml

It needs to checked if that is technically possible.

**Comment by pbek** [comment]
This script does the trick:

```javascript
import QtQml 2.0

/**
 * This script adds custom styles to the application
 * 
 * You can get the object names from the *.ui files, for example
 * https://github.com/pbek/QOwnNotes/blob/develop/src/mainwindow.ui
 * 
 * Take a look at http://doc.qt.io/qt-5/stylesheet-reference.html for
 * a reference of what styles are available.
 */
QtObject {
    /**
     * Adds custom styles
     */
    function init() {
        // add a custom stylesheet to increase font size in the note list and set a font
        script.addStyleSheet("QTextEdit {selection-color: white; selection-background-color: black;}");
    }
}
```

Does that answer your question?

**Comment by sardinas9** [comment]
The script works great!

Thanks Patrizio!

On 12/7/2016 12:20 PM, Patrizio Bekerle wrote:

This script does the trick:

import QtQml 2.0

/**
 * This script adds custom styles to the application
 *
 * You can get the object names from the *.ui files, for example
 * https://github.com/pbek/QOwnNotes/blob/develop/src/mainwindow.ui
 *
 * Take a look at http://doc.qt.io/qt-5/stylesheet-reference.html for
 * a reference of what styles are available.
 */
QtObject {
    /**
     * Adds custom styles
     */
    function init() {
        // add a custom stylesheet to increase font size in the note list and set a font
        script.addStyleSheet("QTextEdit {selection-color: white; selection-background-color: black;}");
    }
}

Does that answer your question?

**Comment by pbek** [comment]
Great ;)

**Comment by sardinas9** [comment]
Hello!
I put the script in a sub folder in the QON Data folder (I use portable mode).  The script works ok if QON uses an absolute path to the script file. It's possible to use a relative path to the script files in the same way we do with the notes folders? 
Thanks!

**Comment by pbek** [comment]
Will be a bit tricky. Please open an other issue for that.

**Comment by bcutter** [comment]
Finally - I meanwhile love QOwnNotes - but the search text highlight (what? where? I can´t see!) made me going crazy. Just wanted to say THANK YOU guys, and the script works perfectly.

**Comment by pbek** [comment]
Great to hear! 😁

Am 24.06.2017 21:51 schrieb "bcutter" <notifications@github.com>:
