### ISSUE TITLE
too high requeriments gcc 4.8 vs 4.4 at least!

### ISSUE THREAD

**Issue by mckaygerhard** [pbek/QOwnNotes#4]
this app could not be installabe in redhat 5 and 6 and in debian squeeze or minor little lightweith ditributions that still use gcc 4.4 and 4.5

this due usage of too newer standar of C++ 

headers file does not permit initializations in c++ standar for gcc << 4.8:

```
mainwindow.h:61: error: ISO C++ forbids declaration of ‘HGMarkdownHighlighter’ with no type
mainwindow.h:61: error: expected ‘;’ before ‘*’ token
mainwindow.h:63: error: ISO C++ forbids initialization of member ‘noteTextEditIsInEditMode’
mainwindow.h:63: error: making ‘noteTextEditIsInEditMode’ static
mainwindow.h:63: error: ISO C++ forbids in-class initialization of non-const static member ‘noteTextEditIsInEditMode’

```

**Comment by mckaygerhard** [comment]
and this are not solved with adition of -std=c++99 due newer inclusion of version 11 in gcc 4.8

**Comment by pbek** [comment]
My build process calls `qmake QOwnNotes.pro -r -spec linux-g++-64`. Does this do anything useful on your system?

**Comment by mckaygerhard** [comment]
the last problem are not qmake call related, its about using newer C++ standar that permits initialize an var in the headers.. this was introduced in gcc 4.8 and newer

**Comment by mckaygerhard** [comment]
a solution its do not init any value in the jheaders and only do it in the c sources..

**Comment by pbek** [comment]
can you prepare a git pull request?

**Comment by mckaygerhard** [comment]
Not yet, later because i have some more errors, I can make one in a week because I'm too busy with my work, i'll made a pull and i hope solves almost all breaks agains the C++99 standard

**Comment by TtuxX** [comment]
Hello @pbek 
Thanks for your awesome work and very useful client !

Just to let you known that I am also experiencing the same error message that @mckaygerhard when trying to build your client relase 0.22(.2) on Debian 7.0:
`WARNING: Failure to find: libraries/hoedown/html_blocks.h`

When I try to install the Ubuntu 14.* x64 `.deb` on Debian 7.0, I also have a `libstdc++6-4.8-dbg` dependancy error.

Thanks again for your great project :)

**Comment by mckaygerhard** [comment]
i have already that erro in my work-in-progress @TtuxX and try to fix also..  the problem for solve the library its related to generation on the qmake command ... u must run inside the src for debian

**Comment by TtuxX** [comment]
@mckaygerhard I red the `README.md` instructions, thanks, actually that's not the problem as I get this error being in the `/src` folder.

**Comment by pbek** [comment]
@TtuxX, thank you for your kind words! I just fixed some warnings and removed the libstdc++6-4.8-dbg dependency (libstdc++6 was added instead) from the Debian package. How does it work for you now?

**Comment by TtuxX** [comment]
@pbek You are welcome !! Your application is great! :)

Thanks to your dependencies requirement changes I can now completely run the `qmake QOwnNotes.pro -r -spec linux-g++-64` command. The output message is: `Project MESSAGE: RELEASE!`

Unfortunately compilation fails when running `make`:
~~~
/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h
/usr/bin/uic-qt4 notediffdialog.ui -o ui_notediffdialog.h
/usr/bin/uic-qt4 aboutdialog.ui -o ui_aboutdialog.h
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_WEBKIT -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -Ilibraries -I. -I. -o main.o main.cpp
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_WEBKIT -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -Ilibraries -I. -I. -o mainwindow.o mainwindow.cpp
mainwindow.cpp: In member function ‘void MainWindow::loadNoteDirectoryList()’:
mainwindow.cpp:128:15: error: ‘QSignalBlocker’ does not name a type
mainwindow.cpp:131:19: error: ‘QSignalBlocker’ does not name a type
mainwindow.cpp: In member function ‘void MainWindow::notesWereModified(const QString&)’:
mainwindow.cpp:205:31: error: ‘QSignalBlocker’ does not name a type
mainwindow.cpp:226:31: error: ‘QSignalBlocker’ does not name a type
mainwindow.cpp:250:31: error: ‘QSignalBlocker’ does not name a type
mainwindow.cpp: In member function ‘void MainWindow::storeUpdatedNotesToDisk()’:
mainwindow.cpp:307:15: error: ‘QSignalBlocker’ does not name a type
mainwindow.cpp: In member function ‘void MainWindow::setCurrentNote(Note, bool)’:
mainwindow.cpp:425:15: error: ‘QSignalBlocker’ does not name a type
mainwindow.cpp:433:15: error: ‘QSignalBlocker’ does not name a type
mainwindow.cpp: In member function ‘void MainWindow::setNoteTextEditMode(bool)’:
mainwindow.cpp:593:15: error: ‘QSignalBlocker’ does not name a type
mainwindow.cpp: In member function ‘void MainWindow::on_searchLineEdit_returnPressed()’:
mainwindow.cpp:763:19: error: ‘QSignalBlocker’ does not name a type
make: *** [mainwindow.o] Error 1
~~~

**Comment by pbek** [comment]
Thank you, @TtuxX ! ;)
So far QOwnNotes needs QT 5, it seems you are using QT 4. :/ QSignalBlocker was introduced in Qt 5.3.

**Comment by mckaygerhard** [comment]
i cannot find equivalent code (at my level of knowled) for the qt5 changes, i cannot port to qt4.6 the app...

**Comment by TtuxX** [comment]
@pbek @mckaygerhard Yeah I'm running the default provided QT. Hmm... it's ok, I guess most users do run on some more actual distros than Wheezzy-like ones. ^^ QT 5 is officially available in Debian Jessie's repos and can be installed on Wheezzy using some tricks. Gotta install it

**Comment by pbek** [comment]
@TtuxX, you could always download QT 5 at <http://www.qt.io/download-open-source/>

**Comment by TtuxX** [comment]
I thought about installing QT 5 from wheezzy-backports repo but finally installed it from the website, then built it using the QT 5 `qmake`. I now have Qownnotes working perfectly :)
@mckaygerhard What do you think about listing the minimal software requirements needed to build Qownnotes in the `Readme` file ? Like specifying that it needs at least QT 5.3

**Comment by pbek** [comment]
Great to hear, @TtuxX 
The minimum software requirements are a good idea, I added some now.

**Comment by mckaygerhard** [comment]
i do not use wheeze or jeese, there are so slow (so far slow), i use custom squeeze that are not shiped with qt5 and compile and install qt5 will crappy the system, qt4 gives me better performence, loading less components widgets in the version library..

in any case, thanks any way.. i'll only use the notes app from web in my company.
