### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by Dalan94** [pbek/QOwnNotes#40]
I would like to translate QOwnNote in french but I don't find guideline in your project. I know how to translate a Qt project but I don't know how to include it in the build system. Could you provide the basis of the internationalization ? Thanks.

**Comment by pbek** [comment]
Thank you very much for your offer, @Dalan94 
It will be a major task to make every string translation-able! :grin: 
I have put that on my todo list, but it will possibly take a while.

**Comment by pbek** [comment]
For a start it wasn't that hard to get a translation file for the UI and the texts that already have translation support.
Here is your translation file:
<https://github.com/pbek/QOwnNotes/blob/develop/src/languages/QOwnNotes_fr.ts>

Are you familiar with Qt linguist?
You could create a pull request for your translation, then you will get the credit for your effort!
Thanks a lot again!

**Comment by Dalan94** [comment]
Yes I know QtLinguist and I can translate the text that already have translation support.
I am also a developer and I'm a little familiar with Qt so I can help you making all the strings translatable.

**Comment by pbek** [comment]
That's awesome! Just give me a call if you need anything!
Please make your pull requests to the `develop` branch.
Thanks a lot!

I will start a German translation then (after I figure out how to test it).

**Comment by Dalan94** [comment]
Ok.
To use the translation you need this code in the main.cpp:
```CXX
QString locale = QLocale::system().name().section('_', 0, 0);
QTranslator translator;
translator.load(QString("../languages/QOwnNotes_") + locale);
a.installTranslator(&translator);
```
But the path to the translation must be change because it's not the same after installing QOwnNote.

**Comment by pbek** [comment]
In my case the path was even `translator.load("../src/languages/QOwnNotes_" + locale);`, because the binary has to find the `.qm` files. And now I realize the `.qm` files have to be deployed along with the binary... It will be a lot of fun to integrate and test that in in the 10 or so build/package/deploy systems I maintain... :grin:

**Comment by Dalan94** [comment]
Yes it's complicated. I think that the best solution is using this `translator.load(QString("languages/QOwnNotes_") + locale);`.

And for the Linux installation, the binary and the translations will be in /usr/share/QOwnNote and in /usr/bin a script like this
```bash
cd /usr/share/QOwnNote
./QOwnNote
```

When you use QtCreator you can change the working directory during the execution in the project settings so it's not a problem.

I use this in [my own project](https://git.framasoft.org/Dalan94/Csuper) and it work well :)

**Comment by pbek** [comment]
Csuper has a nice logo. :smile: 
I have several challenges. I need it getting to work in my local Qt Creator (with qmake), in CLion (with cmake) and on 10+ build systems. :grinning:

**Comment by pbek** [comment]
In v0.88 the translation support in the different repositories should work pretty well. I will test after I release it.

**Comment by Dalan94** [comment]
OK, fine.
I'm working on the french translation and making all the strings translatable.
I will create a pull request when it will be finished (this evening or tomorrow).

**Comment by pbek** [comment]
Awesome, you are the best! I'm looking forward to your pull request!

**Comment by pbek** [comment]
The German translation (the few strings I translated so far) works really well in v0.88!

**Comment by calis2002** [comment]
I can help you with German translation if there is a need for.

**Comment by pbek** [comment]
That's great! I gladly accept your offer, @calis2002 !
Are you yet familiar with Qt linguist?
The translation file we need to translate is this one: https://github.com/pbek/QOwnNotes/blob/develop/src/languages/QOwnNotes_de.ts

A big thank you!

**Comment by pbek** [comment]
In v0.89 it will be possible to select the interface language in the settings, currently QOwnNotes uses the system language.

**Comment by calis2002** [comment]
No, unfortunately not. I'm very new to programming. Just got a little bit C# and PHP knowledge in the last months.

**Comment by pbek** [comment]
Good job! You should be even able to see the dialog if you have checked out the source code. Are you by chance familiar with GitHub and git so you can checkout a fork of the QOwnNotes source code to make your changes and create a pull request?

**Comment by pbek** [comment]
Thank you again, @calis2002 for your great contribution, it will be released today!

@Dalan94 in case you need more information. I now tried to write a "mini tutorial" here: <http://www.qownnotes.org/Knowledge-base/How-can-I-help-to-translate-QOwnNotes>

**Comment by calis2002** [comment]
@pbek no problem. I'm happy to contribute something to such a great project ;)

The mini tutorial is a great idea. But maybe you can add the translators somewhere in the Readme.md instead of creating an issue for every language. It would give you/us a better overview who translates what language.

**Comment by pbek** [comment]
Thank you for your kind words, @calis2002 ! :wink: 
Yes, I will definitely make a list somewhere too, but it's more about the "first contact".
The issues will be needed for troubleshooting in the beginning and I also don't want a single issue for all translations because that will end in notification fatigue for the good hearted translators. :smile:

**Comment by calis2002** [comment]
Ok, good Point ;)

**Comment by pbek** [comment]
Thanks a lot for your contributions! :tada: Please feel free to maintain and update your translations with further pull requests!
