### ISSUE TITLE
LaTeX support

### ISSUE THREAD

**Issue by mimf** [pbek/QOwnNotes#400]
Hey there!

Have you thought about supporting LaTeX, namely math-mode? Zim has an extension for latex-support (http://zim-wiki.org/manual/Help/Export/LaTeX.html) if you want to check it out..

**Comment by pbek** [comment]
I don't think that would work easily on all platforms...
If they are just creating images you could run an external command to create such an image with the QON script engine and show it in the preview. You could do that for example every time the preview is rendered like in this script: <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/preview-styling.qml>

Is this of help for you?

**Comment by pbek** [comment]
This is the command you need to execute a program: <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/README.md#starting-an-external-program-and-wait-for-the-output>

**Comment by mimf** [comment]
I'm not sure how that link helps me, sorry. I'm out of my element here. What I would like is the ability to render mathjax in QOwnTools. But perhaps that's too demanding. I really don't know, I'm asking here..

**Comment by pbek** [comment]
Is mathjax a javascript library? QOwnNotes doesn't use a fully blown browser for the preview, so this can't be done currently, I'm sorry.

**Comment by xephon2** [comment]
👍 for math support. Technical info: https://github.com/cben/mathdown/wiki/math-in-markdown

**Comment by pbek** [comment]
nice compendium!

**Comment by pbek** [comment]
You now could now convert Latex code to an image with a script, see #499.

**Comment by RoyiAvital** [comment]
I think he asks for MathJax support.
Namely ability to us LaTeX for math in MarkDown.

You can see how it is done in [StackEdit](https://github.com/benweet/stackedit) for example using `$ <LaTeX Code> $`.

Adding MathJax Support for MarkDown is easy and would benefit many.

**Comment by alxlg** [comment]
@pbek hi there, I've found a Qt based note taking app that uses Markdown and LaTeX for math, it even displays formulas inline (see image below). It's named VNote: https://github.com/tamlok/vnote
Maybe it worth a look? Also for inspiration for other features.

![](https://raw.githubusercontent.com/tamlok/vnote/master/screenshots/_vnotemaini_1525154456_1561295841.png)

**Comment by pbek** [comment]
@alxlg, thank you! I certainly haven't seen that one before!

**Comment by kundeng** [comment]
What is the status of this feature?  qownnotes seems more polished in many things except this.

**Comment by pbek** [comment]
No news here and no plans to implement it. 😸
