### ISSUE TITLE
windows 10 gui won't start

### ISSUE THREAD

**Issue by kuruptfp** [pbek/QOwnNotes#401]
Program is running in the task manager the gui won't start. Extracted to a few places with the same result. Disabled Anti-virus with same result. Any ideas?

**Comment by pbek** [comment]
I've tested the latest release just yesterday under Windows 10 and I had no such problem.
Where did you extracted it to?
Maybe you can try the portable mode (use the `QOwnNotesPortable.bat` to try)?
Is it the first time you run QOwnNotes on this computer?

**Comment by kuruptfp** [comment]
Interesting enough it worked using the portable.bat
I opened and set it up the first time on this machine a few days ago and it worked fine. Opening the 2nd time and after no longer brought up the gui.

I had it extracted to my documents folder & desktop. Both producing same results.

Thanks

**Comment by pbek** [comment]
I'm sorry, I never heard of something link that. If you really want to know what's going on you could build QOwnNotes yourself and open it in the debugger. See: <http://www.qownnotes.org/installation#building>

Just ping me if you need help.
