### ISSUE TITLE
gentoo :  warning about DESCRIPTION in ebuild file 

### ISSUE THREAD

**Issue by bdouxx** [pbek/QOwnNotes#402]
Hi

I order to remove obsolete ebuild in https://github.com/pbek/qownnotes-overlay
I have clone our repo and remove all ebuild before version 16.11.13
and launch command to update manifest :
   repoman manifest
   repoman --digest=y -d full

but there are warning:
RepoMan scours the neighborhood...
>>> Creating Manifest for qownnotes-overlay.git/app-office/qownnotes
  DESCRIPTION.toolong           5
   app-office/qownnotes/qownnotes-16.11.13.ebuild: DESCRIPTION is 83 characters (max 80)
   app-office/qownnotes/qownnotes-16.11.14.ebuild: DESCRIPTION is 83 characters (max 80)
   app-office/qownnotes/qownnotes-16.11.15.ebuild: DESCRIPTION is 93 characters (max 80)
   app-office/qownnotes/qownnotes-16.11.16.1.ebuild: DESCRIPTION is 93 characters (max 80)
   app-office/qownnotes/qownnotes-16.11.17.ebuild: DESCRIPTION is 93 characters (max 80)

Can you reduce DESCRIPTION in your script and create a new qownnotes-16.11.17-r1.ebuild with this revision, and eventually remove obsolete package?

If you want I can make a pull request i you repo with you new DESCRIPTION.

**Comment by pbek** [comment]
Thank you for reporting, I will reduce the description in my ebuild template.

Concerning the old packages, are they suppose to be remove or should they stay there?
<https://github.com/pbek/qownnotes-overlay/tree/master/app-office/qownnotes>

**Comment by bdouxx** [comment]
If there is no major update with risk of bug, I think less than 4 versions is ok, or 1or 2 month.
for example there is : 
4 versions for libreoffice
3 versions for firefox, kdenlive,...
2 versions for vlc

**Comment by pbek** [comment]
I see no point in not releasing if people are waiting for some feature. 😸

**Comment by pbek** [comment]
Ah, you meant "leaving in the directory"...

**Comment by pbek** [comment]
I now cleared out old releases and decreased the description in the new 16.11.17 release. Does it work for you? If the `Manifest` needs also to be modified please make a pull request.

**Comment by pbek** [comment]
Can we close this issue now?

**Comment by bdouxx** [comment]
hi
OK for me.
You can close
