### ISSUE TITLE
CalDAV connection fails when LDAP authentication is used

### ISSUE THREAD

**Issue by cornercase** [pbek/QOwnNotes#403]
When trying to setup tasks in QOwnNotes, the automated setup for the default calendar fails when a user's login name is authenticated in LDAP. It occurs because their UID doesn't match their login name (compare oc_users.uid to oc_ldap_user_mapping.owncloud_name in database).

Manually setting the calendar base URL that represent's a user's oc_ldap_user_mapping.owncloud_name and specifying their regular username and password for login in the "Other CalDAV server" settings is a functioning work around, but it would be best if this was automatically detected and handled.

![error screenshot](https://cloud.githubusercontent.com/assets/712008/20729162/e437c55e-b64e-11e6-96ef-27bfb5e94ea3.png)

![caldav workaround](https://cloud.githubusercontent.com/assets/712008/20729098/ab6e1958-b64e-11e6-89ce-acc142522725.png)

Example URL of calendar for user in created from LDAP authentication:
https://base_owncloud_domain/remote.php/dav/calendars/234098ad-34dc-9928-7920-52b5cd344a7c/

Example URL of calendar for user with native owncloud authentication:
https://base_owncloud_domain/owncloud/remote.php/dav/calendars/testuser/

**Comment by pbek** [comment]
Thank you for reporting. Too bad I have no ownCloud/Nextcloud server with LDAP around to test anything, maybe you could provide a test user somewhere?

And how should QOwnNotes detect the UID `234098ad-34dc-9928-7920-52b5cd344a7c`?

**Comment by cornercase** [comment]
I will set up a test user on my server and send details tomorrow. I'll also
suggest an implementation strategy once I've had a chance to read through
the code.

On November 29, 2016 4:49:20 PM EST, Patrizio Bekerle <
notifications@github.com> wrote:


>
> Thank you for reporting. Too bad I have no ownCloud/Nextcloud server with
LDAP around to test anything, maybe you could provide a test user somewhere?
>
> And how should QOwnNotes detect the UID
234098ad-34dc-9928-7920-52b5cd344a7c?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
<https://github.com/pbek/QOwnNotes/issues/403#issuecomment-263710408>, or
mute the thread

**Comment by pbek** [comment]
Thank you, but if the implementation really also has to be done in QOwnNotesAPI it will probably too much work.

**Comment by pbek** [comment]
I will close this issue until there is more information.

**Comment by cornercase** [comment]
Sorry for the extremely slow response.  I have enabled a few test users and will send details to the email address listed on your Github page.

Also, I found LDAP functionality that allows nextcloud usernames to be mapped to an LDAP attribute on creation.  Presumably, if setup such that the username matches the uid of an LDAP user, this problem wouldn't occur.  I'll be testing and getting back you.

**Comment by pbek** [comment]
I played around with the accounts, but I didn't get a working CalDAV connection to your server.
I tried CalDAV URLs like <https://owncloud.YOURSERVER.net/owncloud/remote.php/dav/>, auth always failed.

Did you play around with tools like <https://www.getpostman.com/>?

**Comment by cornercase** [comment]
When working with an LDAP user on CalDAV, I always have to use URLs of the form:
>https://owncloud.<domain>/owncloud/remote.php/dav/principals/users/<owncloud username>/ 

where the owncloud username is identical to the LDAP UUID while the username specified for login is the LDAP UID.  You can get that link if you go to Calendar->Settings->iOS/OS X Caldav Address.

With Postman, I was able to get successful auth by using the iOS/OSX link and cookie data from a browser session, though I haven't figures out how to send username and password yet.

**Comment by pbek** [comment]
Please let me know if you have any luck with the auth... ;)
