### ISSUE TITLE
Scripting questions

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#404]
I'm maybe going to ask some dumb questions here.

As far as I've understood, the QOwnNotes script is a QML file, that can have only one QtObject consisting of several functions.

My script has 3 functions: `noteOpenedHook(note)`, `init()` and `customActionInvoked(identifier)`. They use one same variable.

How can I set this variable in a single place in the script? If I try to set it before functions or QtObject, the scripts becomes invalid. Having the variable in each function works, but it's not very useful for editing.

**Comment by pbek** [comment]
There are no dump questions. :)

Take a look at <http://stackoverflow.com/questions/7515598/can-we-declare-global-variable-in-qml-file>.
We are already doing this in the timer at <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/example.qml>.

Does this already answer your question, my dear @Maboroshy?

**Comment by Maboroshy** [comment]
Nah, that would be too easy. You may reconsider your statement about dumb questions.

Lets try on examples. I've tried to insert that property thing to the script below. Why does the app refuse to run it?
```
import QtQml 2.0
import com.qownnotes.noteapi 1.0

QtObject {
    
    property var BashNote:"/storage/emulated/0/notes/bash-note";
    
    function noteOpenedHook(note) {
        var replaceCommand = "0,/^clipnote_inbox_file_name=/{s|^clipnote_inbox_file_name=.*|clipnote_inbox_file_name='" + note.fullNoteFilePath + "'|}";
        var arguments = ["-i",replaceCommand,BashNote];
        script.startDetachedProcess("sed", arguments);
    }
}
```

**Comment by Maboroshy** [comment]
Yes it does. Thanks. I haven't dig that property var must start form the lower case at the first time.

**Comment by pbek** [comment]
Good to know, thank you.
