### ISSUE TITLE
Apply all external modifications of the current note option

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#405]
With the help of a new scripting hook I've implemented adding clipboard content to a currently opened note. But the app is not really happy I'm doing something behind it's back.

With current options it either notifies on every change, either don't show changes until I refresh the folder. 

Could you implement a subject option, like an "yes for all" mode. Maybe with appropriate warning if needed. So the app would simply refresh the note if it detects external changes.

I use 1 second save interval and edit notes on one device at a time, so data loss will hardly occur.

**Comment by pbek** [comment]
How does your script look like?

**Comment by Maboroshy** [comment]
Oh, the get current note part is quite basic:
```
import QtQml 2.0
import com.qownnotes.noteapi 1.0

QtObject {

    property var bashNote:"/storage/emulated/0/notes/bash-note";

    function noteOpenedHook(note) {
        var replaceCommand = "0,/^clipnote_inbox_file_name=/ s|^clipnote_inbox_file_name=.*|clipnote_inbox_file_name='" + note.fullNoteFilePath + "'|";
        var arguments = ["-i",replaceCommand,bashNote];
        script.startDetachedProcess("sed", arguments);
    }
}
```
It sets inbox note setting inside Bash-note to current note. Little ugly, but I'm yet to fully unserstand, how `startDetachedProcess` works with arguments.

There are also custom actions. I've also stated to experiment with QtQuick GUI, not sure I'll use it though, command line is enough for me.

**Comment by Maboroshy** [comment]
By the way the script above sometimes goes infinite loop for some reason I'm yet to find out.

**Comment by pbek** [comment]
I'm not sure what you are doing and what you are intending to do. :)
When are you accessing the clipboard?
There is a scripting command for it: <https://github.com/pbek/QOwnNotes/tree/develop/doc/scripting#accessing-the-clipboard>

And you are really modifying a note that just opened? This could maybe trigger an other note opening process...

**Comment by Maboroshy** [comment]
The only thing I do is get current note file name with path outside of the app and place it into my shell script file. As simple as that. 

All clipboard logic (more like "selected text" logic really) is done by the shell script. For now I think that, till you don't need a cross-platform code, using Qt for clipboard handling brings little gain and many extra code and limitations. It's easier to "talk" to X-server directly.

I'll put a safety check to resolve the loop.

**Comment by pbek** [comment]
So in this script you are just storing the filename of the current note to a file?

And yet I still fail to realize what you need and why? 😸

**Comment by Maboroshy** [comment]
> So in this script you are just storing the filename of the current note to a file?

Yes and then the bigger shell script puts the selected text into that note when I press a key shortcut.

I think I've put too much detail and distract you. The script has nothing to do with the issue.

The issue is: I modify currently opened notes externally, and I just want to have kind of "yes for all" in "current note modified" dialog, so the app would just refresh the note without asking.

**Comment by pbek** [comment]
refresh "the note" or "this an all other notes" without asking?
this would go into conflict with other settings in the general settings tab...
what is the purpose of your script?
do you need to replace the currents text or just add text to the note at the cursor position (because for the latter there also is a scripting method)

**Comment by Maboroshy** [comment]
The script adds text to the top or to the bottom of a file, which is a currently opened note. This script is used mostly when app is out of focus, while user is using browser or other app selecting text and adding text to the file by a key shortcut.

**Comment by pbek** [comment]
So you want a checkbox `Always accept external changes`?

**Comment by Maboroshy** [comment]
Yep.

**Comment by pbek** [comment]
## 16.12.3
- you can now choose `Always accept external changes in the future` when your
  current note got modified externally and the diff dialog pops up
    - you can reset that checkbox in the general settings

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment]
The new feature works. Using external apps with QOwnNotes is much more natural now.

But once you turn "apply" on it's stuck till app restart. Changing to "ignore" won't work right away, it's still in "apply" mode till app restart.

Also, with "apply" mode on, notifications about note changes doesn't pop-up, which is the right behaviour to me. But "notify" can still be on. 
You've made "ignore" and "apply" two-way options, but I think that "notify" is the third mode which can't be combined with those two.

Personally I think that external changes handling is complete with the new feature.

**Comment by pbek** [comment]
Thank you for testing, I will try to reproduce the first and take care of the 2nd.

**Comment by pbek** [comment]
> But once you turn "apply" on it's stuck till app restart. Changing to "ignore" won't work right away, it's still in "apply" mode till app restart.

Are you sure that you edited to the note within one minute **in QOwnNotes**, otherwise the dialog wouldn't even come up...

**Comment by pbek** [comment]
Meaning the note will always get updated if the note wasn't edited in QOwnNotes for one minute.

**Comment by pbek** [comment]
## 16.12.4
- all three settings about external modifications of the current note in the 
  general settings are now mutual exclusive

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment]
All works, thanks!

**Comment by pbek** [comment]
Great!

**Comment by zjusutao** [comment]
20.1.11
The issue comes out again.
"Accept all external modifications of the current note" is checked, but doesn't work.
When a note is modified by another editor or Nextcloud, the note can not reload automaticly. I have to reload manually using shift+command+R.

**Comment by pbek** [comment]
This checkbox only prevents the dialog that asks if you want to accept modifications. If you are not getting that dialog that checkbox has nothing to do with what you are describing.

It can has a number of reasons.
1) you turned off external modification checking
2) your operating system doesn't send the proper filesystem events
