### ISSUE TITLE
Problems with NextCloud 11 beta2

### ISSUE THREAD

**Issue by little-curiosity** [pbek/QOwnNotes#406]
Hi,
I encountered a problem with logging in into NextCloud 11 beta2 using the latest version of QOwnNotes on MacOS (16.12.1) (please see attached image)
![error message](https://cloud.githubusercontent.com/assets/14838243/20869792/7fe5fd98-ba7a-11e6-95b0-03aa3514435c.png).
QOwnNotes recognized the server, the QNotesAPI app on the server but kept telling me that my username and password are not correct (I'm certain that it was the right password and username). It did not occur with the current stable version of NextCloud 10.
Could you investigate on the issue? Would it be something to do with the beta version of the NextCloud instances?
Thanks a lot,
Best regards,
Giang-Son
PS: Thank you for the great program. I learnt about NextCloud and Markdown through QOwnNotes and I could not be happier finding my solutions of having self-hosted note taking solution.

**Comment by pbek** [comment]
Thank you for your kind words.

What happens when you now try to access the trash in QOwnNotes?
Do you get any log message when you turn on the log panel?
Could you please create a test account for me to test on?

**Comment by little-curiosity** [comment]
When I accessed the trash in QOwnNotes, it said "There are no trashed notes on the server" and when I tried to change a note and checked the version function of QOwnNotes, it showed the other versions on the NextCloud server. So, there seemed to be a connection with the server through the QOwnNotes API but it is somehow unstable. After QOwnNotes crashed (it crashed quite often recently, both on Mac and Windows, which I guess because of the NextCloud transition?), I opened it again and then it complained about the problems with connection to NextCloud and also with the CalDAV (the error message is: "Error message from your CalDAV server: Principle with name users not found).
I created a test user account for you, how I can send it to you? Probably not a best idea to post the credentials here.

**Comment by pbek** [comment]
Can you please send me a macOS crash log and enable the logging to file in the debug settings and send me a log after a crash.
You'll find my email address on my github profile page.

> Principle with name users not found

are you sure you entered your username (and password) in the right text-case?
you aren't using ldap on NC, are you?

**Comment by pbek** [comment]
I got the same error message when connecting to your server:

`Reply from ownCloud calendar page: "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<d:error xmlns:d=\"DAV:\" xmlns:s=\"http://sabredav.org/ns\">\n <s:sabredav-version>3.2.0</s:sabredav-version>\n <s:exception>Sabre\\DAV\\Exception\\NotFound</s:exception>\n <s:message>Principal with name users not found</s:message>\n</d:error>\n"`

Is there anything in the nextcloud.log when you get this error message?

> os x crash log

Thank you for the log. What were you doing when it crashed? And which version did you use?

**Comment by pbek** [comment]
## 16.12.1
- fixed a crash that could occur when closing the settings dialog immediately 
  after opening it, while the ownCloud connection test is still running

**Comment by pbek** [comment]
## 16.12.1
- fixed problems with note sharing, note versions and the note trash with Nextcloud 11

It should now work on your server (it worked with my account).
Although storing tasks is still broken, they also modified CalDAV on NC11.

**Comment by pbek** [comment]
I case you want to test tasks too you can install the tasks app in your Nextcloud directory with `git clone https://github.com/nextcloud/tasks.git apps/tasks` on your server.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by little-curiosity** [comment]
Thanks for the updated version, at least it did not crash so often like before. The crashes usually happened when I just closed the program (happening in both Windows and Mac). I still can not have the problem of wrong account and/or password on my own server (the credentials worked with other apps like NextCloud clients for Mac and Windows or in iOS).

**Comment by pbek** [comment]
> The crashes usually happened when I just closed the program 

Do you have a macOS crash log?

> I still can not have the problem of wrong account and/or password on my own server

Can you please explain what you mean?

**Comment by little-curiosity** [comment]
I just sent you the newest crash long.

> I still can not have the problem of wrong account and/or password on my own server.

Sorry, I mistyped. What I meant was the problem with the wrong credentials still persist even with the latest release. I fully uninstalled the program (using the AppCleaner.app) and reinstalled QOwnNotes but it did not solve the problem.

**Comment by pbek** [comment]
> I just sent you the newest crash long.

Am I correct that you had the log panel open?
What did you do before the crash?

> wrong credentials

That's strange. It works with the user you gave me. Is there any other error message you get?
What happens when you try to share a note (what error message do you get)?

btw. you should go with a https://letsencrypt.org/ SSL certificate...

**Comment by pbek** [comment]
I copied your mail:
When I tried to share a note, QOwnNotes complained about wrong credentials. I also tried to use the «test» user credentials that I made for you but it also did not work. I started to think that there is something wrong with my Mac mini. I will try again with my Windows machine at work tomorrow. Also I basically did not do anything except closing the error messages and quit the program when it crashed. But with the new version, it’s getting more stable now.

About Let’s Encrypt thing, I have two NASes, both recently integrated the Let’s Encrypt function but I never managed to get the certificates as there is something with the port 80 making both of them could not communicate with Let’s Encrypt server. I tried to whitelist it on my router but it somehow still did not work. I will probably try it again using certbot with the MacOS when I have more time (also I’m not really a developer myself and just start learning a bit about Linux and shell for my job).

**Comment by pbek** [comment]
I just tried using the test user under macOS and it also worked for me... 
So did it crash when you disabled the log panel or later when you quit the app?
By which means did you quit the app? (keyboard shortcut, exit menu entry, ...)

**Comment by pbek** [comment]
And do you still get errors in the ownCloud settings or is all green?

**Comment by pbek** [comment]
About the CalDAV thing, I created an issue at <https://github.com/nextcloud/server/issues/2552>. They upgraded SabreDAV, the friendly devs at NC are currently looking into the matter...

**Comment by little-curiosity** [comment]
Thanks a lot for the updates. It's working now on my side, not really sure what was the problem before. You can close this issue I guess.

**Comment by pbek** [comment]
Ok, great. Thanks again for reporting and testing!

**Comment by pbek** [comment]
## 16.12.3
- fixed a problem with saving tasks in Nextcloud 11.0 RC 1

**Comment by pbek** [comment]
## 17.01.2
- since the support for legacy **CalDAV** URLs in **Nextcloud 11** is still 
  broken support for the new URLs was added and will now used by default (if the 
  application is re-installed)
    - the legacy URLs will be supported as well
    - switch to the new setting in the *Todo setting* if you have troubles 
      with Nextcloud 11
    - ownCloud 9 seems to support the new CalDAV URLs as well
