### ISSUE TITLE
Issue: Editor Color Scheme Reset On Close/Open

### ISSUE THREAD

**Issue by Omnicraft** [pbek/QOwnNotes#407]
I've just recently started using QOwnNotes on **Mac OS Sierra** after using on Archlinux for several months.

#### Issue On Mac
Every time I open QOwnNotes, my editor color scheme reverts to black and white. Currently, I correct this issue by deleting my scheme and re-importing a previously exported copy of my scheme.

####### Before Reset
![screen shot 2016-12-05 at 11 36 49 am](https://cloud.githubusercontent.com/assets/24393029/20893282/3e1b73a6-badf-11e6-8540-ff2b4130ab0a.png)

####### After Reset
![screen shot 2016-12-05 at 11 35 50 am](https://cloud.githubusercontent.com/assets/24393029/20893268/2f56b506-badf-11e6-96ff-7a73c6f1db9e.png)

**Comment by pbek** [comment]
So you created two schemes, selected one and it reverts back to the other? Am I understanding correctly?

**Comment by pbek** [comment]
Can you please post the output from the debug settings.

**Comment by pbek** [comment]
Nice looking schema btw. want me to include it in QOwnNotes?

**Comment by Omnicraft** [comment]
I created the scheme in the first pic and saved it via export to .ini file. The next time I launched the program I was met with the color scheme in the second pic. When I go to editor color preferences, my theme is still selected but the colors are lost. I tried switching between the included schemes and back to mine but nothing short of re-importing will restore the color scheme. The issue repeats every time I launch the program. I'll turn on debug and post it with my scheme in a bit.

**Comment by richarson** [comment]
@Omnicraft please share your scheme, it looks really nice!

**Comment by pbek** [comment]
Did you export the schema on an other installation of QOwnNotes?
Can you please post the output from the **debug settings** from all installations.

**Comment by pbek** [comment]
I tried all kind of things, copying a schema, modifying it, exporting it, importing it... Never had a problem.

**Comment by Omnicraft** [comment]
Here's the scheme, I'm glad you like it. Also feel free to include it. I only wish it would apply to the preview pane as well ;-)
[AnalyticalYellow.ini.zip](https://github.com/pbek/QOwnNotes/files/632374/AnalyticalYellow.ini.zip)
I created it on this same Mac. The issue happens every time I exit and then relaunch QowNotes, anytime I'm using a scheme that did not come with the program. I never had any issues on Linux across multiple distros and computers.

Here's the log file:
[QOwnNotes.log.zip](https://github.com/pbek/QOwnNotes/files/632377/QOwnNotes.log.zip)

**Comment by pbek** [comment]
> I only wish it would apply to the preview pane as well ;-)

there is a scripting method to alter the stylesheets, you could play around with that...

> AnalyticalYellow.ini.zip

interesting, there were two schema in the ini and when I tested it under macOS it was only black and white... did you create the schema on macOS or on Linux?

**Comment by Omnicraft** [comment]
Now that I think of it, I may have made an earlier version of the schema in linux and moved it over to the mac version. I'll have access to the Mac on Wednesday, I'll try recreating the schema from scratch to see if it corrects the issue.

I've attached the earlier schema from my linux install.
[DarkishYellow.zip](https://github.com/pbek/QOwnNotes/files/633068/DarkishYellow.zip)

**Comment by Omnicraft** [comment]
Alright so I reproduced the issue: Saving over a previously exported schema.ini file results in the double schema file as the file seems to be appended instead of completely overwritten. What is interesting is that importing and applying this dual schema file works after the program has been opened but always results in black and white color after a relaunch.

**Comment by Omnicraft** [comment]
Here the proper schema file
[AnalyticalYellow.zip](https://github.com/pbek/QOwnNotes/files/633086/AnalyticalYellow.zip)

**Comment by pbek** [comment]
and does it work if you remove the old schema file first and then export and import it?

**Comment by Omnicraft** [comment]
yes: the problem only occurs when I export to an existing file and confirm that I want to overwrite the file. Changing the name or saving in another folder results in a clean export and no issues.

**Comment by pbek** [comment]
So this issue is resolved if the file is removed before exporting?
Then I will clear it before an export. Thanks a lot for finding out!

**Comment by Omnicraft** [comment]
no problem! Thanks for making a great program!

**Comment by pbek** [comment]
## 16.12.1
- fixed a problem with exporting font color schemas to a file that already exists
- added the new dark font color schema *AnalyticalYellow* (thank you, @Omnicraft)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Omnicraft** [comment]
Tested Successfully:

After the update; I made a copy on an included theme and saved over the analytical theme.ini file and can confirm that the file was cleared and that the new theme data was written to the file.

**Comment by pbek** [comment]
Great, thank you for reporting, testing and sharing your color schema!
