### ISSUE TITLE
[Q] Why opened document will be changed its modified date without any editing ? 

### ISSUE THREAD

**Issue by piyo-gh** [pbek/QOwnNotes#408]
When I open a document, the modified date of the opened document will be modified without any editing. 

In my short test, the documents which don't contain header 1 (`====`) nor header 2 (`----`) don't change their modified date when I open it.  
But the documents which contain header 1 (`====`) or header 2 (`----`) change their modified date when I open it. 

Is this an intended behavior ?   
Thanks,

**Comment by pbek** [comment]
Thank you for reporting. Doesn't sound intended...
On which platform did you see that?
Did you get a `Stored 1 note(s) to disk` log entry?

**Comment by pbek** [comment]
Can you please post the output from the debug settings.

**Comment by piyo-gh** [comment]
Windows 10 x64
QOwnNotes 16.12.0 portable mode

I checked all logging option ON, but there was no log for this.

**Comment by pbek** [comment]
So was the note-file really modified? What did Explorer say?

**Comment by piyo-gh** [comment]
![test2](https://cloud.githubusercontent.com/assets/18474085/20922565/ee20fff2-bbeb-11e6-9cff-5191daf2b609.gif)

----

![test](https://cloud.githubusercontent.com/assets/18474085/20922575/fe4a69fe-bbeb-11e6-9e7c-513171a56af3.gif)

----
I installed a new instance at different folder and made 2 document.
Everytime ehrn I click a document title on note list, it moved to the top of list.
So, the same result.
The other hand, pre-installed 3 documents (Welcome to QOwnNotes.md, Markdown Cheatsheet.md, Markdown Showcase.md) didn't change modified date. Strange enough but I don't know why.

**Comment by pbek** [comment]
So the files don't change?
Do you also get this phenomenon in non-portable mode?
Do you use scripts, subfolders or tags?
Can you please post the output from the debug settings.

**Comment by piyo-gh** [comment]
> Markdown Showcase.md

Yes, Itried just now with newly installed instance.
So, all settings are default. No subfolder and no tags.
I only made 2 notes.
Thant's all things which I did.

----

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `火 12 6 20:16:36 2016`
**Version**: `16.12.0`
**Build date**: `Dec  3 2016`
**Build number**: `2576`
**Platform**: `windows`
**Operating System**: `Windows 10`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.7.0`
**Qt Version (runtime)**: `5.7.0`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\ooo\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Qt Debug**: `0`
**Locale (system)**: `ja_JP`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `5`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `C:\Users\ooo\ownCloud\Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\ooo\ownCloud\Notes\notes.sqlite`

## Settings

**Debug/fakeOldVersionNumber**: `false`
**Debug/fileLogging**: `false`
**Editor/CurrentSchemaKey**: `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing**: `true`
**Editor/autoBracketRemoval**: `true`
**LastUpdateCheck**: `2016-12-06T20:16:27`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `24`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `MS UI Gothic,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `MS UI Gothic,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl**: `false`
**PiwikClientId**: `<hidden>`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**ShowSystemTray**: `false`
**SortingModeAlphabetically**: `false`
**WelcomeDialog/geometry**: `<binary data>`
**allowDifferentNoteFileName**: `false`
**allowOnlyOneAppInstance**: `false`
**appMetrics/disableAppHeartbeat**: `true`
**appMetrics/disableTracking**: `true`
**appMetrics/notificationShown**: `true`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**currentWorkspace**: `3a6b4e42-f4c9-4e62-88df-7403720e3453`
**customNoteFileExtensionList**: *empty*
**darkMode**: `false`
**darkModeColors**: `false`
**darkModeTrayIcon**: `false`
**defaultNoteFileExtension**: `md`
**demoNotesCreated**: `true`
**disableAutomaticUpdateDialog**: `false`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: *empty*
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**imageScaleDown**: `false`
**imageScaleDownMaximumHeight**: `1024`
**imageScaleDownMaximumWidth**: `1024`
**interfaceLanguage**: *empty*
**internalIconTheme**: `false`
**itemHeight**: `14`
**markdownHighlightingEnabled**: `true`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `2`
**noteSaveIntervalTime**: `10`
**notesPath**: `C:/Users/ooo/ownCloud/Notes`
**notifyAllExternalModifications**: `false`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: *empty*
**ownCloud/todoCalendarBackend**: `0`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/userName**: *empty*
**previousWorkspace**: *empty*
**savedSearches/noteFolder-1**: `Note 2016-12-06T20.13.49, Note 2016-12-06T20.13.48`
**showMenuBar**: `true`
**showStatusBar**: `true`
**workspace-3a6b4e42-f4c9-4e62-88df-7403720e3453/name**: `default`
**workspace-3a6b4e42-f4c9-4e62-88df-7403720e3453/noteSubFolderDockWidgetVisible**: `true`
**workspace-3a6b4e42-f4c9-4e62-88df-7403720e3453/windowState**: `<binary data>`
**workspaces**: `3a6b4e42-f4c9-4e62-88df-7403720e3453`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\ooo\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `CAT`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\ooo`
**LOCALAPPDATA**: `C:\Users\ooo\AppData\Local`
**LOGONSERVER**: `\\CAT`
**NUMBER_OF_PROCESSORS**: `4`
**OS**: `Windows_NT`
**Path**: `C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Users\ooo\AppData\Local\Microsoft\WindowsApps;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 94 Stepping 3, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `5e03`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PROMPT**: `$P$G`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\ooo\AppData\Local\Temp`
**TMP**: `C:\Users\ooo\AppData\Local\Temp`
**USERDOMAIN**: `CAT`
**USERDOMAIN_ROAMINGPROFILE**: `CAT`
**USERNAME**: `ooo`
**USERPROFILE**: `C:\Users\ooo`
**VS140COMNTOOLS**: `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\`
**windir**: `C:\WINDOWS`

**Comment by piyo-gh** [comment]
> The other hand, pre-installed 3 documents (Welcome to QOwnNotes.md, Markdown Cheatsheet.md, Markdown Showcase.md) didn't change modified date. Strange enough but I don't know why.

I found a difference.
Line ending of these 3 notes are Unix style (LF). But once I modified these notes, line ending will be changed to DOS style (CRLF), and will be changed the modified date.

So, as I wrote at the opening post, this problem will be caused by heading, (`====`) and (`----`), and DOS style (CRLF) line ending.
It never happen without heading, (`====`) and (`----`).
It never happen on Linux and MacOS.

**Comment by pbek** [comment]
I finally managed to reproduce that on one Windows installation.

**Comment by avalx** [comment]
It looks like the same problem I have.

As for information I also have some CRLF problems when editing notes first on Windows and than on Linux/Android. Here is the link of the issue: https://github.com/owncloud/notes/issues/246

**Comment by pbek** [comment]
Ok, then please wait for the next release of QOwnNotes. ;)

**Comment by pbek** [comment]
## 16.12.2
- fixed a problem with line feeds under Windows where notes will move up to 
  the top in the note list even when not actively edited

There now is a new release, could you please test it and report if the new features work for you?

**Comment by piyo-gh** [comment]
It works now. Great.
Thank you. I appreciate it.

**Comment by pbek** [comment]
Awesome, thank you for reporting and testing!

**Comment by avalx** [comment]
Yes, it works now. Thanks!

**Comment by pbek** [comment]
Thank you for testing, @avalx!

**Comment by avalx** [comment]
I would just like to report that there is still a problem with "invalid filename" - as per https://github.com/owncloud/notes/issues/246  . The only thing that was fixed was this particular issue for QOwnNotes (#408 - changing modified dates without editing). I'm sorry for confusion :(.

**Comment by pbek** [comment]
Can you please explain in more detail and step by step what you did, what happened and what you expected. Or is this not the concern of QOwnNotes?

**Comment by avalx** [comment]
It looks like a bug on the server app side: https://github.com/nextcloud/notes/pull/31

**Comment by pbek** [comment]
Ok, then it has nothing to do with QON for now... ;)

**Comment by pbek** [comment]
FYI @avalx: all kind of line-feeds are converted to `\n` in QON, I don't know how that is handled in oC Notes, because Windows uses CRLF by default...

**Comment by avalx** [comment]
Yeah, I know this is a nightmare we have to still live with after all these years .... :(

**Comment by pbek** [comment]
The one thing I **really** don't understand is why Windows Notepad is still the same crappy editor like 25 years ago! :smile_cat:
