### ISSUE TITLE
Why the demo notes show again and again?

### ISSUE THREAD

**Issue by LiangWei88** [pbek/QOwnNotes#41]
every time i creat a new folder
I have to remove these 3 demo again and again
it is not normal

**Comment by pbek** [comment]
Hi, @LiangWei88 

Yes, that was intentional. Is this behavior too confusing in your eyes? Do you create a lot of notes folders?

**Comment by LiangWei88** [comment]
The first time I run the programme, I think the demo notes are normal.
I remove them, and they show up again, but there is no explication for that.
So I think it is an sync error or a bug.
After search in google, I know it is because I don't have any note yet.

There are 2 problems.
1, no tips or explication, maybe the user will think this is a bug, and just leave.
2, every time I create new folder, the demos show up automatically, every time I clean up a folder, the demos show up again. and if I remove them, they will show again because there are no other note.

The first time show the tutorial is useful, but after that, the create-remove routine is just pointless.
Or maybe it is a necessary feature, and I have misunderstanding?

**Comment by pbek** [comment]
I think you are right, I will come up with something in the next version.
Thank you for your input!
I will notify you then...

**Comment by LEDfan** [comment]
I must agree with the user above. I also don't like that the demo notes always show up again. However I like when they show up the first time you use the app, until you delete them. Maybe it would be the best to have a global value in the conf file which indicates if the user have deleted the notes. (if deleted in one folder don't show them in other folders)

**Comment by pbek** [comment]
In v0.88 the demo notes will only be created once. (so for existing users one last time :grin:)
Can you two be so kind and report report back if it works as intended when the new version is out? Thanks a lot!

**Comment by pbek** [comment]
v0.88 is out

**Comment by LiangWei88** [comment]
I try it. the demo no more exist. Thanks.
(It is not like you said before that show one last time. there is just not demo note any more)

by the way, If you add version number to each releases file, the user can easily find out if it use the latest version or not.

and how can I contribute for chinese tranlation for this progamme?

**Comment by LEDfan** [comment]
I can confirm this is fixed! Thanks again.

**Comment by pbek** [comment]
Thank you, @LEDfan and @LiangWei88!

- version number: I had to struggle with the limitations of the build system. Can you please open an other issue and I will see what I can do.
- translation: That's great! Thanks a lot! Can you please open an other issue where we can discuss what you'll need.

**Comment by pbek** [comment]
@LiangWei88 the OS X dmg and Ubuntu deb files, that are created by Travis CI now have the version number in the filename. I had no success with the Windows ZIP yet. If that is still important to you please open an other issue for it.

**Comment by LiangWei88** [comment]
I created issue 46.
You anwser me there already.
That's fine, I found it.
Thanks ^_^

**Comment by pbek** [comment]
:+1:
