### ISSUE TITLE
Not able to add Subfolders dispears 

### ISSUE THREAD

**Issue by Servh37** [pbek/QOwnNotes#410]
Hi,

I have added the Subfolders panel, when i tryed to creat a new folder it dispears  and does not create the subfolder.

[QOwnNotes Debug.txt](https://github.com/pbek/QOwnNotes/files/635417/QOwnNotes.Debug.txt)

**Comment by pbek** [comment]
Did you enable sub-folders for your note folder in the note folder settings?

**Comment by Servh37** [comment]
Hi @pbek,

Sorry i missed the tick box after i reinstall the application.

Regards

**Comment by pbek** [comment]
No problem ;)
