### ISSUE TITLE
Note gets changed status without changing anything

### ISSUE THREAD

**Issue by avalx** [pbek/QOwnNotes#411]
I'm using the latest version of QOwnNotes and have noticed strange behavior for some notes lately. For some of the notes (not all, mainly the old ones that I haven't touched for a while) when I just click them in the "Note list" window, the note immediately jumps to the beginning of the list as it was changed. I did not type or even click in the "Note edit" window. Also the note in the owncloud folder gets new modified date. I'm not sure but I think this was not happening a couple of versions ago.

Could you please check if this is something to be dealt with in the application or is it server issue?

**Comment by pbek** [comment]
Can you please take a look at #408 if it is the same problem.

**Comment by pbek** [comment]
Or do you have this problem under Linux?

**Comment by avalx** [comment]
Yes it looks like the same problem as you mentioned. I also added some info regarding my other CRLF problem.

**Comment by pbek** [comment]
thank you
