### ISSUE TITLE
Relative path to script files

### ISSUE THREAD

**Issue by sardinas9** [pbek/QOwnNotes#412]
Hello!
I put the script in a sub folder in the QON Data folder (I use portable mode). The script works ok if QON uses an absolute path to the script file. It's possible to use a relative path to the script files in the same way we do with the notes folders?
Thanks!

**Comment by pbek** [comment]
I'll see what I can do.

**Comment by pbek** [comment]
## 16.12.4
- **scripts** now also work with a path relative to the data directory in 
  **portable mode**
- if you select a new script path for a script in the script settings the 
  directory of your current script will be selected
    - in portable mode the data directory will be selected if no script path 
      was set yet
- the **path to an external editor** will now also be stored relative to the 
  data directory in **portable mode**
    - if you select a path and no path was set yet the data directory 
      will now be selected

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by sardinas9** [comment]
Everything works OK. Thanks!
Thanks also for implement the relative path to an external editor. I think now all path settings are fully portable.

**Comment by pbek** [comment]
Great, thank you for testing.
