### ISSUE TITLE
problem with updates

### ISSUE THREAD

**Issue by sardinas9** [pbek/QOwnNotes#413]
Hello Patrizio
I have never been able to update from  the internal update button. I get this error:
![update-ssl-error](https://cloud.githubusercontent.com/assets/20257711/21073669/8efee598-bebb-11e6-9a1e-b737dac2848d.png)
I don't  know if this could be a windows security issue, a network setting issue  or is related to QON. 
Can you take a look into it?
Thanks!

**Comment by pbek** [comment]
Very interesting. QON is downloaded directly from GitHub...
What happens when you turn off SSL errors in QON?

**Comment by sardinas9** [comment]
I turned off Ignore SSL error and still got the same screen.

**Comment by pbek** [comment]
Do you use ownCloud with QON where you connect to a https server? If yes, does that connection work?

Maybe the QON-bundled OpenSSL library doesn't work for you.
You could try to fetch it directly from here: <http://slproweb.com/products/Win32OpenSSL.html>
also see: <http://stackoverflow.com/questions/18894056/error-creating-ssl-context-qt#18917240>

**Comment by sardinas9** [comment]
I use QON Offline.
I will do what you suggest.

**Comment by sardinas9** [comment]
Thank you for point me in the right direction!

I downloaded this file (https://indy.fulgan.com/SSL/openssl-1.0.2j-i386-win32.zip) from a link at the stackoverflow page (your second suggestion) and replaced the **libeay32.dll** and **ssleay32.dll** files that came with QON with the new files. I triggered a fake update and worked just fine.

![succesful update](https://cloud.githubusercontent.com/assets/20257711/21076782/aa661244-bf0a-11e6-854e-a75e5ed78097.png)

I'll wait the next QON actual update for a definitive test.

Thanks again!

**Comment by pbek** [comment]
I'll keep that in mind in case someone else has problems too.
Thank you for testing.

**Comment by pbek** [comment]
## 16.12.5
- updated the OpenSSL DLLs to 1.0.2j to prevent problems on some Windows installations

... otherwise you would downgrade your DLLs with every update

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if an other update works after updating to 16.12.5?

**Comment by sardinas9** [comment]
Hello!
It didn't work with the real update.
![real](https://cloud.githubusercontent.com/assets/20257711/21084254/1e91d1e0-bfd7-11e6-93a4-62ab8ab543a4.png)
I update QON manually.
It worked again triggering a fake update

![fake](https://cloud.githubusercontent.com/assets/20257711/21084257/221cf808-bfd7-11e6-801a-9e145001d3d0.png)

**Comment by pbek** [comment]
Of course the first update didn't work, your DLLs were downgraded with your last fake-update to 16.12.4. :)

**Comment by pbek** [comment]
It will work from now on, thank you for testing.
