### ISSUE TITLE
Integrity check of Nextcloud app fails

### ISSUE THREAD

**Issue by jurgenhaas** [pbek/QOwnNotes#414]
Just installed the latest app on Nextcloud 10.0.2 and get a warning about a failed integrity check for the following three files of qownnotesapi:

- .travis.yml
- README.md
- appinfo/info.xml

Is that something that could be fixed in another release?

**Comment by pbek** [comment]
Thank you for reporting. How did you install QOwnNotesAPI?
NC 11 will use the signed release package directly from the NC app store.

**Comment by jurgenhaas** [comment]
I've downloaded the archive which is linked on nextcloud app store, extracted that and copied that into the app directory

**Comment by pbek** [comment]
NC 10 still uses the ownCloud app store and the ownCloud signature.

You could either use the ownCloud app store package (that is ownCloud signed) or checkout the master branch from GitHub, I ownCloud-signed it just now.

<https://github.com/pbek/qownnotesapi/>

Does that solve your problem?

**Comment by jurgenhaas** [comment]
That's a bit confusing as the Nextcloud app store suggests that there is a version for NC 10:

![2016-12-11 19 30 39 screen](https://cloud.githubusercontent.com/assets/1475675/21082261/72e3e782-bfd8-11e6-947e-c3f9f4ab98be.jpg)

I have now downloaded the master branch and copied that to the apps directory as is, now getting other errors:

- Missing files
  - .editorconfig
  - build/artifacts/appstore/qownnotesapi.tar.gz
- Extra file
  - screenshot.png

**Comment by pbek** [comment]
Thank you for reporting, I will create a new release for Nextcloud as well.

**Comment by pbek** [comment]
There now is a new release at <https://apps.nextcloud.com/apps/qownnotesapi>.
Could you please test it and confirm that the integrity check succeeds.

**Comment by jurgenhaas** [comment]
This is great, all the warnings are gone. Thanks @pbek for your support.

**Comment by pbek** [comment]
Thank you for reporting and testing!
