### ISSUE TITLE
Masked syntax highlighting issue

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#415]
I like the new "masked" highlighting feature. But it acts little weird with inline links and images with no title, like `[](file://link)` or `![](file://image)`:

`[title](file://link)` - `[]` and link are masked
`[](file://link)` - `[]` is not highlighted, link is not masked
`![title](file://image)` - `![]` and image link are masked
`![](file://image)` - `![]` is masked, link is not masked

**Comment by pbek** [comment]
As for 1), 3) and 4), they are intentional. I only highlight the most important information and mask the rest. So the most important information catches the eye. I find that very useful. :)

As for 2), that was never supported. What sense does this link make?

**Comment by pbek** [comment]
btw. I got my inspiration from <https://app.classeur.io/>

**Comment by pbek** [comment]
But for you I can add highlighting for `[](file://link)` ;)

**Comment by pbek** [comment]
## 16.12.8
- urls with empty title like `[](file://link)` are now also highlighted

... so your happiness is increased ;)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment]
I was more worried that some notes of mine with "mixed" syntax look inconsistent than about `[](file://link)`.

`[](file://link)` logically should be all greyed out since it's a hidden text that can be used for unrenderable comments.

**Comment by pbek** [comment]
For me it's more logical to highlight the information with the greatest value, in case of `[](file://link)` there is no other information than the url, so I highlight it...

**Comment by Maboroshy** [comment]
I agree. But there must be consistency, a pattern the user can become used with and spend less his attention. 

What's the syntax highlighting is for? 

The first is to quickly take out the syntax of the same type out of the wall of text. You've had that with the previous basic highlighting. Images are green, links are orange. 

The second is to quickly understand the logic of the syntax elements. That's what the new "masked" highlighting is supposed to do. All syntax with green are images, there's green title part and grey link part. You look at image syntax and understand, where's the title, without thinking about it. 

Now, you have title that is green but it can also be the link that is green. Imagine, you have a mixed syntax note, or many notes with different syntax that are converted from a web pages with some sick bash script, like I do. Can you understand where's the link part without thinking? Is it grey, no it's the green this time... Can you see all image links without title at one glance?

It like using an IDE that highlights a function green if it has no arguments, and highlighting it grey and an arguments green if it has. 

The "greatest value" of  `[](file://link)` is not the url but the fact that's it's unrenderable. So either it's accidentally broken, and the user needs to understand it and do something, either it's deliberate - to exclude it from rendering.

**Comment by pbek** [comment]
I'm sorry, but I can't follow where you are getting to.
Can please provide examples of what you are talking about.
And why does the user care if `[](file://link)` is unrenderable. QON does no markdown syntax checks... `file://link` is a link and it can be Ctrl+Clicked in the editor.

**Comment by Maboroshy** [comment]
I'll try with an example.

Which one looks more consistent and logical?

![default](https://cloud.githubusercontent.com/assets/19194063/21237226/7ceaf850-c317-11e6-8047-041f868c916c.png)

**Comment by pbek** [comment]
Thank you for the example, now I understand what you meant. But I still prefer the first one, because I'm not interested in the link if I set a title (like when it actually was linked in preview).
The 2nd one is distracting me again, but at least not like before I made the changes..

**Comment by pbek** [comment]
Plus I want to be able to see the link if there is no title.
