### ISSUE TITLE
Please remove poll banner: it renders small screens useless

### ISSUE THREAD

**Issue by mvhconsult** [pbek/QOwnNotes#416]
This banner blocks the website completely on smaller screens, and the close star is invisible. Please remove or auto remove at small screens

**Comment by pbek** [comment]
What is a "small screen" to you, it already isn't shown under 780px screen width? What device and browser are you using?
Can you please post a screenshot.

**Comment by mvhconsult** [comment]
This is a brand new laptop with 1920x1080. See screenshot

![161215_qownnotes](https://cloud.githubusercontent.com/assets/10559457/21218242/18937650-c2b0-11e6-8e6f-f6b5a5cd29c2.jpg)

**Comment by pbek** [comment]
That looks like a Polldaddy-problem, I'll see if I can do something about that. Thank you for reporting.

**Comment by pbek** [comment]
I now reduce the height of the poll dialog if the height of the browser window is to small and I hide it if it's far too small. Thanks again for letting me know.
Does it now work on your Laptop?

**Comment by mvhconsult** [comment]
Yes, the poll popup now leaves enough space on top for the [x] to show.
Solved for me.

**Comment by pbek** [comment]
Great, thank you!
