### ISSUE TITLE
Annoying password prompt when editing encrypted note

### ISSUE THREAD

**Issue by Olhur** [pbek/QOwnNotes#42]
Hi!
I have recently started to use built-in encrypted notes. Everything is fine till I start editing them, which is a big pain in the ass, since every minute or so the password prompt shows up and requires me to type the password in (which is not a short password...). Also, I can still read the note, so this is not protecting the content in any way (which would be highly appreciated in case of sudden afk). So, is there a possibility of enhancing that functionality, or at least a temporary solution? :)

Didn't want to sound too grumpy though, thanks for the app development! ;)

Best regards,
Filip

**Comment by pbek** [comment]
Thank you for your kind words, @Olhur :grin: 

The current functionality should be that the crypto key gets expired after 10min if the note wasn't edited meanwhile. One minute doesn't seem right. Could you please provide me the output of the Debug tab in the settings?

What would be the desired functionality of the "enhancement"?

**Comment by Olhur** [comment]
```
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `pon. lut 1 10:59:46 2016`
**Version**: `0.86`
**Build date**: `Jan 31 2016`
**Build number**: `86`
**Platform**: `linux`
**Operating System**: `Manjaro Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `openSUSE Build Service`
**Qt Version**: `5.5.1`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**connectionErrorMessage**: *empty*

## Settings

**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `22`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.font**: `Noto Sans,10,-1,0,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `Noto Sans,10,-1,0,50,0,0,0,0,0`
**MainWindow/windowState**: `<binary data>`
**ShowSystemTray**: `false`
**SortingModeAlphabetically**: `false`
**cryptoKey**: `<hidden>`
**mainSplitterSizes**: `<binary data>`
**noteSaveIntervalTime**: `10`
**notesPath**: `/home/olhur/ownCloud/Notes`
**recentNoteFolders**: `/home/olhur/ownCloud, `
**skipVersion**: `0.86`
```

Hopefully that helps in any way, but I can't see it having any data that can be useful ;) 

I think the time between prompts varies a little, but can't tell for sure. 

Best regards!
Filip

**Comment by pbek** [comment]
You you leave the encrypted note editor or are you just typing while the password dialog appears?
I assume you are using ownCloud to sync the notes, are you?
I can reproduce it under Manjaro, I will see if I can reproduce it also on my Ubuntu development rig.

Btw. do you work under KDE on Manjaro? And if yes, do you get a tray icon for the ownCloud sync client? (because I don't and I couldn't make it work)

**Comment by Olhur** [comment]
I have tried that and it's not because of the idle state, it often shows 
up when I am actively typing.
Yes, I do use ownCloud to sync, and in KDE they tray icon is there, but 
hidden under the ^ (everything is being synced up properly so far).

Best regards!
Filip

**Comment by pbek** [comment]
Now I'm kind of embarrassed, the icon is really where you just told me... Oh the things I tried to fix a problem that didn't existed. :laughing: Thanks a lot!

I will try to reproduce the password problem on Ubuntu later today. Thank you for your help.

**Comment by pbek** [comment]
It really was a bug with the crypto key expiration.
Now the crypto key will expire after 10min without editing the note, like planned! The fix will be released with v0.87 of QOwnNotes (which I guess will be out today).
Thanks again for the report!

Can you then please report back if everything works smoothly for you?

**Comment by Olhur** [comment]
Sure thing, waiting for the release then! Thank you so much :)

**Comment by pbek** [comment]
Version 0.87 is currently building, you will be able to test it very soon.
Thanks for your patience!

**Comment by Olhur** [comment]
From what I have tested, the problem has vanished. Thanks! ;)

**Comment by pbek** [comment]
great, thank you! :wink:
