### ISSUE TITLE
Workspace doesn't keep the layout

### ISSUE THREAD

**Issue by tiagogala** [pbek/QOwnNotes#420]
The workspace doesn't save the layout when i do "maximize window". 
When I maximize the window, the leftmost column becomes too big - It might be more useful to keep the leftmost column always the same size (because there is no advantage on making it bigger when maximizing) and scale the width of the edit + preview columns/panels.
See the screenshots:
1. Normal size 
![b](https://cloud.githubusercontent.com/assets/1774170/21220157/822a125a-c2af-11e6-86b5-3b9b58ae1648.png)

2. Maximized
![a](https://cloud.githubusercontent.com/assets/1774170/21220156/822832a0-c2af-11e6-85af-b538d4869bbf.png)

**Comment by pbek** [comment]
Thank you for your suggestion, but since everyone can use any layout he / she wants and it's extremely hard to override anything the layout manager does when changing the size of the main window the best solution will be you create an other workspace, that you could use when you maximize the window.

**Comment by pbek** [comment]
When I find a better solution, I'll let you know...

**Comment by Aisbergg** [comment]
There is an easy workaround for this problem. While the default left column awkwardly stretches the panels, a custom created column will do the job just fine. Simply move all your panels form the left column to a new column directly next to it. Once done you have the same layout as before, but without the annoying resizing behaviour.

**Comment by pbek** [comment]
I wonder what the new columns does differently...

**Comment by pbek** [comment]
The only programmatic approach to this that I found was to make one area the "central area" of the `QMainWindow`, what would get resized if the windows is resized. But beside the tricky programming to allowing that as an option that area couldn't be moved around as usual...

**Comment by pbek** [comment]
...or to create a menu with all panels and checkboxes to allow to lock the horizontal size down manually, but that also would be unhandy in daily use because then you cannot resize those columns manually while onle panel in that column is size-locked

**Comment by pbek** [comment]
## 18.04.1
- there now is a new checkbox in the *Panels settings* to use the note edit
  panel as fixed central widget to be **resized** if the **window** or other
  **panels** are **resized** (for [#420](https://github.com/pbek/QOwnNotes/issues/420))
    - for new installations of QOwnNotes this will be enabled by default
    - for running sessions of QOwnNotes this will be disabled by default
    - if this is disabled you are able to create more complex panel layouts,
      but all panels will be resized if the window is resized

**Comment by pbek** [comment]
@vegatron, @vanleo2001, @msbentley, @schittli, @tiagogala, @Aisbergg 

There now is a new release, could you please test it and report if it works for you?

**Comment by msbentley** [comment]
Thanks @pbek that works great - I reset my settings to get rid of the "hack" described above, and now it works perfectly!

**Comment by pbek** [comment]
Great, thank you for testing! It took quite a while to get that working! :sweat_smile:

**Comment by vanleo2001** [comment]
Thanks @pbek  that works, but "Tags Panel" change to right side, it's ugly.

**Comment by pbek** [comment]
@vanleo2001 I guess you didn't do a new installation, right?
Technically it was in the right panel. All panels are movable (that's what they are for).
Why don't you just move it to a place you like?

**Comment by pbek** [comment]
Maybe you want to play around with https://github.com/pbek/QOwnNotes/issues/2007#issuecomment-758827767 from version 21.1.3.
