### ISSUE TITLE
sidebar resize problemwindow maximize problem

### ISSUE THREAD

**Issue by vegatron** [pbek/QOwnNotes#422]
hi,

there is a problem, when resizing the application window the sidebar gets wider and wider until it takes half of the window size, as shown in the images 

before resizing :
![image](https://cloud.githubusercontent.com/assets/187431/21244485/86c768ea-c326-11e6-9124-13d00c8f3b1b.png)

after resizing the window, left sidebar gets larger 
![image](https://cloud.githubusercontent.com/assets/187431/21244493/913ba192-c326-11e6-835b-7b6f17066136.png)

after setting it back to original size then maximizing the window the sidebar takes half of the screen size
![image](https://cloud.githubusercontent.com/assets/187431/21244566/ede96e56-c326-11e6-9e0b-7924c4077cd2.png)

thanks , I enjoy using your program 👍

**Comment by pbek** [comment]
I'm sorry, there is no "side bar" since everyone can choose his own layout.
I was talking about that just yesterday at #420. ;)

I'm happy that you like QON. ;)

**Comment by xuzhao9** [comment]
I tried the workaround (move all the panels form the left column to a new column directly next to it) and it works like a charm. Thanks for pointing to the original ticket!

**Comment by pbek** [comment]
Great! ;)

**Comment by pbek** [comment]
Please see https://github.com/pbek/QOwnNotes/issues/420 for information of a new behavior!
