### ISSUE TITLE
Multiple shortcut parts after every opening of settings dialogue

### ISSUE THREAD

**Issue by lachmanfrantisek** [pbek/QOwnNotes#424]
Thank you for very nice application, but I've found a small bug. 

After every opening of settings dialogue, there appears another set of shortcut parts (`Help`, `Open chat`, `Edit`,...). Even if the `Shortcut` option has not been selected.

Not sure if it can be related to this change: [fixed a problem where the shortcuts were not viewed in the settings](https://github.com/pbek/QOwnNotes/commit/258d41504af42d2d53c27812bde22e6b5575a6f6).

Linux Mint 18 64bit, QOwnNotes 16.12.9

Thanks for your work.

**Comment by pbek** [comment]
Thank you for your kind words and for your report!

> After every opening of settings dialogue, there appears another set of shortcut parts (Help, Open chat, Edit,...). Even if the Shortcut option has not been selected.

Where do you see that?

**Comment by pbek** [comment]
Found out myself, thanks again for reporting. It was a regression from the memory optimization changes...

## 16.12.10
- fixed a problem with duplicate shortcut items in the shortcut settings after opening the settings dialog multiple times

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by lachmanfrantisek** [comment]
Yes, it works as expected.

Thank you for such a quick correction. Can I close an issue?

**Comment by pbek** [comment]
Thank you for testing!
