### ISSUE TITLE
Use failure/success colors from Qt theme instead of hard-coded

### ISSUE THREAD

**Issue by Crendgrim** [pbek/QOwnNotes#426]
A minor suggestion:

The settings panel uses hard-coded colors in the ownCloud/Nextcloud connection dialog. It would be nice if the colors set in the Qt theme (`ForegroundNegative`, `ForegroundNeutral`, `ForegroundPositive`) were used instead if this is possible, as pure red clashes with some color schemes.

**Comment by pbek** [comment]
Sounds like a good idea. Thank you.

**Comment by pbek** [comment]
> ForegroundNegative, ForegroundNeutral, ForegroundPositive

I can't find such constants anywhere in Qt, where did you get the names from? Do you have more information?

**Comment by pbek** [comment]
I will close this issue until there is more information.
