### ISSUE TITLE
Auto-closing "*" for bold syntax issue with auto-closing on 

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#428]
I have the auto-closing syntax feature on. I wanted to enter a `**bold**` syntax by typing. After I typed `**` the "seems to closing" single `*` appeared. After I typed another `*`another single `*` appeared.

Currently it's impossible input bold syntax by typing without deleting some extra `*`.

**Comment by pbek** [comment]
I guess you did that at the start of the line, right? If you don't do that at the start of the line it works as expected.
The problem is that a `*` at the start of the line is also a list character and thus no 2nd `*` is added.
I'll find a way around that without annoying anyone.

**Comment by Maboroshy** [comment]
Yes it was start of the line. Isn't a space required after a `*` for it to be a list marker?

**Comment by pbek** [comment]
Yes, what about it?

**Comment by Maboroshy** [comment]
Well, as you've posted, The app thinks `*` at the start of the line is a list character and doesn't consider it a part of `**bold**` syntax. But markdown has `*_` is a list, with a space. Bold and italics syntax mostly doesn't have space between `*` and the next letter. 

Maybe that's the key to distinguish these syntax types. If it ain't `*_` at the beginning of a line, than it's an opening for bold or italics.

**Comment by pbek** [comment]
But the decision if a 2nd `*` should be added has to be made before the user enters the space. I'll find an other workaround.

**Comment by pbek** [comment]
Puh... It was very tricky to make all cases work (especially also the automatic cursor placement).

## 16.12.12
- the automatic bracket-closing of the `*` character now also works if used in
  markdown lists that start with a `* ` and when used in normal text at the 
  start of the line after the 2nd `*`

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment]
`*` in the list works. But I couldn't get it working at the beginning of the line. One space from the beginning - works, at the beginning of the line - doesn't. It stats working only after third `*` at the beginning of the line and not in a helpful way.

**Comment by pbek** [comment]
It isn't supposed to "work" at the beginning of a line, because a `*` can also be the start of a list. I try to compensate with adding a 2nd `*` when you close the first "strong-tag".

**Comment by Maboroshy** [comment]
But if it's `**` than it's surely not a list but a **bold** opening. Why not add closing `**` right away?

**Comment by pbek** [comment]
I'll look into that.

**Comment by pbek** [comment]
## 16.12.13
- bold markdown tags will now also be closed at the beginning of a line after
  the 2nd `*` was entered (because after the first `*` it could still be a list)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment]
All works.

**Comment by pbek** [comment]
Thank you for testing!
