### ISSUE TITLE
Dark Colour Scheme does not update foreground/background colours

### ISSUE THREAD

**Issue by polarathene** [pbek/QOwnNotes#429]
I am using Manjaro KDE with Breeze Light, when choosing to use the `Dark` colour scheme in settings for the editor, foreground/background colours are not updated. Restarting QOwnNotes does not help like it does when forcing the dark theme for the entire app(not what I want).

![bug_qownnotes_dark_cscheme](https://cloud.githubusercontent.com/assets/5098581/21418223/974391c2-c884-11e6-9772-b6aeb8e2bf25.png)
![bug_qownnotes_dark_cschemesetngs](https://cloud.githubusercontent.com/assets/5098581/21418267/dc1218f0-c884-11e6-9c38-6c032d2b66bc.png)

**Comment by pbek** [comment]
I guess there are some checkboxes in the Interface settings in the box `Dark mode` that you want might to check, I'm I right?

**Comment by pbek** [comment]
You have to do that because Breeze Light uses light backgrounds on its own.
Does this fix your problem?

**Comment by polarathene** [comment]
@pbek I mentioned in my post that I had tried dark mode/theme with no problem. I want to keep the Breeze Light theme but have the editor pane to respect the colour scheme set (Dark) for black background and white foreground.

Something like this:
![markdown_haroopad](https://cloud.githubusercontent.com/assets/5098581/21418783/80c6f872-c888-11e6-8aa2-8d11a55fb712.png)

**Comment by pbek** [comment]
You would need to turn off the dark mode then and manually set the background color of the note edit the way you like with stylesheets in a script.

See <http://docs.qownnotes.org/en/develop/scripting/README.html#add-a-custom-stylesheet> for documentation about the command you need.

The style you want to modify in a script like <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/custom-stylesheet.qml> is `#noteTextEdit`.

Does that help?

**Comment by polarathene** [comment]
@pbek I can give that a go but would have thought the point of the colour scheme having background/foreground colour options would be enforced instead of overwritten by the system theme? 

Would it not make sense to run that logic when applying the colour scheme regardless? Is there a use case where that is bad/undesirable for a user to use the colourschemes background/foreground? I'd think that would be more niche as the colour schemes don't look right with the different(at least opposite) bg/fg than the scheme intended.

**Comment by pbek** [comment]
I'm not sure I'm able to follow your thoughts. :)
Can you please explain in more detail and step by step what you did, what happened and what you expected.

**Comment by polarathene** [comment]
See my settings page, I use the dark colour scheme. My KDE theme is Breeze Light, standard/default with KDE install. I wanted to have dark colour scheme apply properly withouot force dark mode or change to Breeze Dark. It should work with Breeze Light for the toolbar like shown, only editor pane shouold be affected by colour scheme like settings suggest. Notice that it says background is black and foreground is white? See the preview in settings? Then on editor pane after apply, colour scheme work except background is white and foreground(text) is black, wrong way and now editor pane look wrong, not like preview in settings.

You suggest a fix with a script, but I think this is expected functionality. If you can force background/foreground to use colour from colour scheme so it looks like preview, I believe everyone want this, why would they want it to look like my screenshot? The screenshot from Haroopad shows what I expect, dark editor pane, light preview pane, Breeze Light theme(it does not have nice toolbar and other panes like QOwnNotes unfortunately, however you can see from menu bar that it is still light theme which is good).

1. In KDE set theme to Breeze Light
2. Install QOwnNotes and change colour scheme from `Light` to `Dark`.
3. Markdown will look like my screenshot, mix of light/dark...broken.
4. Should look similar to 3rd picture(Haroopad), dark colour scheme for editor pane, everything else unaffected.

**Comment by pbek** [comment]
Thank you for your very elaborate explanation.
May I ask why you think that everyone expects the dark mode to tool like in your screenshot? You are the first to ask for that look and really a lot of users are using the dark mode...

**Comment by richarson** [comment]
@pbek Maybe most people use dark mode with a dark theme?
I also think it's odd that when you apply dark mode the background stays white, but never though of opening an issue about it :)

For example, if I select the beautiful AnalyticalYellow scheme:

![qownnotes_1](https://cloud.githubusercontent.com/assets/1638444/21432849/1acadea8-c84c-11e6-810c-dd9f0b516409.png)

This is how it looks in light mode:

![qownnotes_2](https://cloud.githubusercontent.com/assets/1638444/21432880/4504bfa4-c84c-11e6-9b92-18d222137e9e.png)

And this in dark mode:

![qownnotes_3](https://cloud.githubusercontent.com/assets/1638444/21432888/51d0197c-c84c-11e6-9178-908c3cdf3a46.png)

For contrast, this is Light color scheme with dark mode on (which also looks odd):

![qownnotes_4](https://cloud.githubusercontent.com/assets/1638444/21432911/70894a50-c84c-11e6-905a-90b51389ab5d.png)

So I guess @polarathene has a point in that the background of the text editor should follow the color scheme and not the program's theme.

That said, I don't know how hard it is to make the text editor to follow the color scheme's background so I leave that decision to you @pbek  :)

**Comment by pbek** [comment]
> make the text editor to follow the color scheme's background

You mean the background color of the `Text preset` schema item? I will take a look into that.

**Comment by richarson** [comment]
Yes, sorry, that's what I meant.

**Comment by polarathene** [comment]
@pbek Exactly what @richarson showed with pictures. 

Nothing against dark mode that works great, but mixing light colour scheme with dark mode or dark colour scheme with light theme(Breeze Light), does not look like expected given settings preview.

**Comment by pbek** [comment]
@richarson, thank you for letting me know in a simple sentence what @polarathene was talking about. :) It was actually a great idea!
@polarathene, sorry for understanding completely what you were talking about.

## 16.12.12
- the foreground and background color of the note text edit will now be taken
  from the *Text preset* highlighting item, so you can use dark highlighting 
  schemas even if you are not in dark mode
    - it's now also possible to override these colors in a script if you 
      specify the css selector, for example with
      `script.addStyleSheet("QTextEdit#noteTextEdit {background-color: red;}");`

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by richarson** [comment]
Working great! :+1:

**Comment by polarathene** [comment]
After changing the settings and restarting the app it works great! Thank you so much, hugely appreciated! :)

**Comment by pbek** [comment]
Great! Thank you for testing and merry Christmas! ;)
