### ISSUE TITLE
Start in Markdown mode

### ISSUE THREAD

**Issue by dasmaetthes** [pbek/QOwnNotes#43]
It would be nice to have the possibility in Settings to make the Markdown mode as standard view .

**Comment by pbek** [comment]
I will look into that.

**Comment by dasmaetthes** [comment]
Hey,
I made a fork and wanted to implement this function.
I'm stocked now in reading and ablly the settings when application is started.
Isn't the function MainWindow::readSettingsFromSettingsDialog() called on start?
How you set the old settings when application is started?

**Comment by pbek** [comment]
Yes, it will be called in `MainWindow::readSettings()`. What is it that you are struggling with?

**Comment by dasmaetthes** [comment]
I implemented an option in settings dialogue where you can set if it should start in edit or markdown mode. and created a pull request. (But I never worked with internationalization, so may the string isn't translation-able)
It first seemed like the settings wasn't read, but I just missed that setNoteTextEditMode() was called after again.

**Comment by pbek** [comment]
Great job! :+1: 
I just did some rework on your pull requests. Now all is fine. :grin:
