### ISSUE TITLE
Shortcuts do delete line or word

### ISSUE THREAD

**Issue by raczkow** [pbek/QOwnNotes#432]
I started to use QOwnNotes about month ago I I found it a great application. I moved my markdown notes from Atom, and one of the most feature I miss from it are shift+del shortcut to delete whole line and ctrl+del shortcut to delete whole word. Is it possible to implement this in QOwnNotes?

**Comment by pbek** [comment]
Thank you for your kind words. I'll take a look into that.

**Comment by pbek** [comment]
Currently `Ctrl + Backspace` is deleting a word.

**Comment by pbek** [comment]
## 16.12.14
- you can now delete the current line in the note text edit with <kbd>Alt</kbd> + <kbd>Backspace</kbd> (or <kbd>⌘</kbd> + <kbd>Backspace</kbd> under macOS)
- you can now delete the current word in the note text edit with <kbd>Ctrl</kbd> + <kbd>Backspace</kbd> (or <kbd>Alt</kbd> + <kbd>Backspace</kbd> under macOS)

**Comment by pbek** [comment]
of course you are free to set other shortcuts in the settings

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by raczkow** [comment]
Wooow. That was fast!
Works like a charm. Thank you.

**Comment by pbek** [comment]
Great, thank you for testing.

**Comment by pbek** [comment]
Note that you change the shortcuts in the settings.

**Comment by sanderboom** [comment]
Posting here on request of @pbek.

When I 'Delete line' the cursor moves up. Is it possible to make this behave like other editors and have the cursor stay on the same linenumber?

Thanks for looking into this!

**Comment by raczkow** [comment]
+1 :-)

**Comment by pbek** [comment]
## 17.08.2
- the `Delete line` function now only deletes the text to the beginning of 
  the line and not the whole line to mimic the behavior of other text editors

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by sanderboom** [comment]
@pbek Thanks for the fast implementation! We are _almost_ there ;) 

- `Delete line` should remove the contents + the `\n` on that line
- The cursor should stay on that linenumber (which now displays the content of the line _below_ the line that got removed)

Implementing it like this will also make sure that when deleting an empty line, only the `\n` will be removed, the cursor will stay the the same position and the content of the line below the deleted line will be moved up. In the current situation the latter is not true: now the cursor moves up a line. This should not happen :)

Hope this clarifies. I could also do a quick movie. If you run any editor (e.g. sublime text or atom) you can also look at how it's implemented there.

Thanks!

**Comment by pbek** [comment]
I was mimicking the *delete line* behavior of Sublime text...

**Comment by sanderboom** [comment]
> I was trying to mimick the delete line behavior of Sublime text...

Well, you almost got it ;)

See my explanation above for the (small) difference.

**Comment by pbek** [comment]
For me `Shift + Ctrl + K` in Sublime Text doesn't remove the `\n` of the line if it deleted text from it...
What in particular should be changed in your opinion? (and why)

**Comment by sanderboom** [comment]
I hope we are talking about the same thing. I'm using ST3.

 A gif is worth a thousand words ;)

![peek 2017-08-17 22-25](https://user-images.githubusercontent.com/5956570/29432250-2ee6e804-839b-11e7-9bd3-965d37bd98e8.gif)

**Comment by pbek** [comment]
## 17.08.7
- the `Delete line` function now *pulls the text from the bottom up*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by sanderboom** [comment]
Sounds good! Will check as soon the package for ArchLinux is available  :+1:

**Comment by pbek** [comment]
AUR was just updated, in case you are using that...

**Comment by sanderboom** [comment]
```
aur/qownnotes           17.08.6-1        17.08.7-1                     
```
That was quick. Installing now...

**Comment by sanderboom** [comment]
Thanks for thequick update. I don't know if I see the new behavior,  but `Delete line` now works like:

![peek 2017-08-21 18-47](https://user-images.githubusercontent.com/5956570/29529921-e201ac9a-86a1-11e7-889c-f831656e23b0.gif)

- At first `Delete line` does not delete the `\n`, only the text
- When the line is empty, `Delete line` does delete `\n`, but moves the caret to the end of the line above. It should stay where it was. The line below should have come up.

Again, I hope we are discussing the same thing!?

Thanks for all the effort :100:

**Comment by sanderboom** [comment]
BTW it might be an idea to show how it works on your install - maybe I've messed up my version. [Peek](https://github.com/phw/peek) is a handy tool for making animated `.gif`s (if you are on linux).

**Comment by pbek** [comment]
Strange, the cursor wasn't supposed to go to the end of the line and it didn't when I tested it. I'll take a look at that. Thanks for the link!

**Comment by pbek** [comment]
I just tested on Manjaro via AUR and it worked as it should, are you sure you've got the correct version installed already?

**Comment by sanderboom** [comment]
This is weird:
```
λ pacman -Q |grep qownnotes
qownnotes 17.08.7-1
```

and

![image](https://user-images.githubusercontent.com/5956570/29534261-a024fb9c-86b5-11e7-9fe4-19ce672263ce.png)

:grimacing: 

I had to suspend while `pacaur` was downloading. My bet is that this is the cause. Will install again.

**Comment by sanderboom** [comment]
Works flawless in the new version, thanks for all the effort man!

**Comment by pbek** [comment]
Finally, thank you for testing! :)
