### ISSUE TITLE
code blocks being improperly processed..

### ISSUE THREAD

**Issue by CTrauma** [pbek/QOwnNotes#433]
I'm trying to add a code block for some shell scripting and the following line

```
advscan -c advscan.rc -R -t -v < romlist_mame_0.180.lst > romchk.log 2>&1
```

Which becomes:

advscan -c advscan.rc -R -t -v [ romlist_mame_0.180.lst > romchk.log 2](note://_romlist_mame_0)&1 

In the rendered side..

**Comment by pbek** [comment]
Thank you for reporting, seems to be an issue with the markdown library <https://github.com/hoedown/hoedown>.

**Comment by pbek** [comment]
It's a problem introduced with #266.

**Comment by pbek** [comment]
## 16.12.13
- note links like `<my note.md>` will now only be translated to real note 
  links in the preview if the linked note was found in the current note folder

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?
