### ISSUE TITLE
(macOS) Command+Backspace should work like in other applications

### ISSUE THREAD

**Issue by mpodshivalin** [pbek/QOwnNotes#434]
In any application that I've used in macOS (Notes, Pages, Sublime Text, Microsoft Word), Command+Backspace deletes everything stating from the cursor position to the beginning of the line. 
I think this is a system function, however in QOwnNotes editor this combination doesn't do anything.

It is very convenient to delete lines this way. An alternative would be to select text using the mouse and then press backspace, or to press Shift+Command+Left arrow and then backspace - this is not so convenient for an app that is largely a text editor.

This is of course not an important bug, but I use this key combination a lot and would be glad if this was fixed, maybe it is easy considering that it is a system key combitation.

Other than this small Mac issue, this application is great - I've tested 40+ notes applications and QOwnNotes is a clear winner, especially with advanced ownCloud support. Thank you!

**Comment by pbek** [comment]
Thank you for your kind words.

That should be handled by the QTextEdit widget and `Ctrl + Backspace` works under Linux. I'll test it under macOS.

**Comment by pbek** [comment]
## 16.12.14
- you can now delete the current line in the note text edit with <kbd>Alt</kbd>
  + <kbd>Backspace</kbd> (or <kbd>⌘</kbd> + <kbd>Backspace</kbd> under macOS)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by mpodshivalin** [comment]
Everything works perfectly now. Thank you for your help!

**Comment by pbek** [comment]
Great, thank you for testing!
