### ISSUE TITLE
(macOS) diff contains \n characters

### ISSUE THREAD

**Issue by mpodshivalin** [pbek/QOwnNotes#435]
Maybe I don't know something that I should, but when I look at the note history, sometimes I see \n characters where the new line should have been (image is in the attachment).

<img width="1064" alt="issue" src="https://cloud.githubusercontent.com/assets/16121630/21484039/526d85b4-cb9d-11e6-81e9-2a4601930f5f.png">

Notes are stored correctly and there are no problems with that - they look normal in Note text tab.

I've googled diff images and couldn't find with these symbols - usually they have standard line breaks, but maybe I'm wrong.

Maybe this issue is related to #98 - it's not game breaking, but sometimes I see this window while working with a note only with differences in \n characters

**Comment by pbek** [comment]
`\n` is a line break, is there anything wrong with it? Is your complaint about the diff dialog or the fact that something is different in your notes?

**Comment by mpodshivalin** [comment]
My complaint is about writing `\n` instead of showing the actual line break. I've worked with other diff utilities (in SourceTree, FileMerge, etc), and none of them show `\n` - they show an an actual line break.

<img width="582" alt="diff" src="https://cloud.githubusercontent.com/assets/16121630/21488717/05e2b91a-cbf4-11e6-8b85-d44217c49551.png">

Left image - how it works now, right image - how I want it to work :)

The function itself works fine, no bugs in saving notes. I just thought that this behaviour can be counter-intuitive (especially for non-programmers). If this is an intended functionality, please mark this 'issue' as closed.

**Comment by pbek** [comment]
Thank you for explaining. This is an intended functionality of the diff library <https://github.com/pbek/QOwnNotes/tree/develop/src/libraries/diff_match_patch>. There are different types of line break.

**Comment by pbek** [comment]
Sorry, I first thought we were talking about the note diff dialog, when a note was modified externally...
But we are talking about the ownCloud version dialog...
I now attempted to match the behavior of the note diff dialog by showing a `¶` character instead of `\n`.

**Comment by pbek** [comment]
## 16.12.14
- now a `¶` character, followed by a new line is used instead of a `\n` to signal a line break in the diffs of the note versions dialog

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by mpodshivalin** [comment]
Just updated, now everything works as I wanted. Thank you for you help.

**Comment by pbek** [comment]
Great, thank you for testing!
