### ISSUE TITLE
(macOS) Icons in dark mode are hard to see

### ISSUE THREAD

**Issue by mpodshivalin** [pbek/QOwnNotes#436]
Dark mode looks great on Windows:
<img width="1276" alt="windows" src="https://cloud.githubusercontent.com/assets/16121630/21484525/1a860074-cba5-11e6-9357-27ca09ba69a9.png">

But it looks different on macOS:
<img width="1280" alt="mac" src="https://cloud.githubusercontent.com/assets/16121630/21484530/293386f0-cba5-11e6-9159-fd7c48cebb7f.png">

Colors are grey and buttons are considerably harder to see - they should be white (like on Windows).

Mac screenshot is made on MacBook **Retina** - maybe this is connected the problem.

I can test fixes on two Mac devices (MacBook Retina and iMac not retina) if this will help.

**Comment by pbek** [comment]
Thank you for reporting, but that was already reported and I narrowed it down to a deployment problem with Qt. There is an open Qt bug for it. Meanwhile there's nothing we can do about it...
