### ISSUE TITLE
Principal with name users not found

### ISSUE THREAD

**Issue by smikanl** [pbek/QOwnNotes#440]
Today I installed a fresh nextcloud. I installed calendar and tasks and this works fine. I can connect with qOwnnotes to create notes and sync them with nextcloud.

I also want to sync my todolist wit QOwnnotes, but when I go to the settings in QOwnnotes and select tasks, I cannot receive any calendars and get the following error: Principal with name users not found.

Is there a way how to solve this issue?

Thanks for the great software. I love it.

Smika

**Comment by pbek** [comment]
Thank you for your kind words. I guess you are using NC 11. You will have to wait until NC 11.0.1, where they fixed the bug. See: <https://github.com/nextcloud/server/issues/2552>

**Comment by smikanl** [comment]
Thanks for the quick reply. I use version 11, I will wait for 11.0.1. Thanks

**Comment by pbek** [comment]
It should already be in their master branch, in case you want to use the git version of NC...

**Comment by smikanl** [comment]
thanks again. I installed it with git (branch stable11) and everything is working fine now.

Thanks for the great support and software.

**Comment by pbek** [comment]
Thank you for testing and your feedback!

**Comment by pbek** [comment]
## 17.01.2
- since the support for legacy **CalDAV** URLs in **Nextcloud 11** is still 
  broken support for the new URLs was added and will now used by default (if the 
  application is re-installed)
    - the legacy URLs will be supported as well
    - switch to the new setting in the *Todo setting* if you have troubles 
      with Nextcloud 11
    - ownCloud 9 seems to support the new CalDAV URLs as well
