### ISSUE TITLE
High CPU usage in background on macOS

### ISSUE THREAD

**Issue by mpodshivalin** [pbek/QOwnNotes#441]
For some reason, QOwnNotes uses CPU when in background on two of my macs:
<img width="912" alt="screen shot 2016-12-29 at 16 56 21" src="https://cloud.githubusercontent.com/assets/16121630/21545926/6299a7c8-cdec-11e6-9576-1e989db1e12a.png">

What I've tried:

- Reboot mac and do not start anything except for QOwnNotes
- Test with ownCloud running
- Test without ownCloud running (or even without internet connection)

Log shows this:

```
[Dec 29 16:53:44] [status]: Your tasks are being loaded from your server
[Dec 29 16:57:15] [status]: Notes directory was modified externally
[Dec 29 16:57:42] [status]: Notes directory was modified externally
```

Yes, it shows that directory was modified, but there are only two such messages and CPU usage spikes are much more frequent.

This problem does not affect user experience, but it greatly affects battery consumption.

Maybe I can help by performing some specific testing?

**Comment by pbek** [comment]
Thank you for reporting.
Can you please post the output from the debug settings.
How many notes do you have in your note folder and does your Mac has an ssd?

**Comment by mpodshivalin** [comment]
I've attached the output from the debug settings.

Right now I have a total of 37 notes (and a total of 10 folders).

One Mac has an SSD, and another has HDD.

Maybe I can help by testing in portable mode, so that we can be sure the problem is not related to ownCloud syncing and settings?

[debug info.txt](https://github.com/pbek/QOwnNotes/files/677557/debug.info.txt)

**Comment by pbek** [comment]
Can you remove the ownCloud server url from your settings so that the todo items are not loaded...
And were you writing a note? How large is it?

**Comment by mpodshivalin** [comment]
I've just removed calendars and ownCloud URL - unfortunately it didn't help. The problem occurs since I start the application, I think it doesn't matter if the note is being edited or not. Currently my Notes folder size is 300 Kb.
Also I created a new Mac user, signed in, installed QOwnNotes, didn't configure ownCloud settings and the issue was still there - there were no notes.

**Comment by pbek** [comment]
That's strange, no notes? I can't reproduce this on my macBook.

**Comment by mpodshivalin** [comment]
Does you MacBook has macOS Sierra?
Maybe the problem is that I currently use El Capitan, which is previous version of macOS.
I can try to reproduce this bug in the latest version macOS, and if there won't be any problems, then the issue is not worth fixing.

**Comment by pbek** [comment]
I've Sierra...

**Comment by mpodshivalin** [comment]
I've just tested this on friend's MacBook with El Capitan - he has the same problem. On the other hand, I've launched macOS Sierra in VirtualBox and there were no problems - no background activity.

**Comment by pbek** [comment]
That's strange, I've no idea what should be the difference with El Capitan...

On an unrelated matter: May I ask which instructions you followed to get macOS running in Virtual Box? I haven't achieved that in a while...

**Comment by mpodshivalin** [comment]
There are a lot of already installed macOS Virtual Machines for VMware - you can download them from the Pirate Bay and immediately open in VMware player (which is free). AND it's possible in most cases to open VMware image in VirtualBox - VMware's Virtual Machine hard drive is in vmdk format which VirtualBox can open: http://techathlon.com/how-to-run-a-vmdk-file-in-oracle-virtualbox/

This is even legal as long as you run it on Apple hardware. Other hardware should work, but some people have experienced problems with this for example when using AMD processor. The easisest way is to download and try. So

1. Download ready macOS VMware Virtual Machine
2. Create a new Virtual Machine in VirtualBox, but use existing hard drive image from VMware VM.

**Comment by pbek** [comment]
Thank you!
