### ISSUE TITLE
Showing subfolders panel is not easy

### ISSUE THREAD

**Issue by szotsaki** [pbek/QOwnNotes#443]
- Window > Panels > Show subfolders panel does nothing;
- Can only be activated by right clicking on Tabs and selecting Subfolders.

**Comment by pbek** [comment]
Did you have enabled note sub-folders in the note folder settings?

**Comment by szotsaki** [comment]
No, I haven't. Turning that on solves the issue, thank you for the tip.

However, I think it should be more obvious why the menu entry doesn't do anything. Probably, it should be disabled as well as the right click menu entry.

**Comment by pbek** [comment]
It has to be possible to activate and deactivate the pane because you can have multiple note folders, each with different "show note sub-folder" settings.
