### ISSUE TITLE
Creating a new note hides the Subfolder dock

### ISSUE THREAD

**Issue by szotsaki** [pbek/QOwnNotes#445]
1. Open the subfolder dock
2. Do one of the following inside it:
   - Right click on "Note folder" > New Subfolder > Enter a name > Press Enter
   - Select Note > New note
3. Both actions hide the Subfolder dock. The first one doesn't properly create a new one with the entered name.

**Comment by pbek** [comment]
Did you have enabled note sub-folders in the note folder settings?

**Comment by szotsaki** [comment]
Probably the same issue as #443. See my https://github.com/pbek/QOwnNotes/issues/443#issuecomment-269783518 there.
