### ISSUE TITLE
Moving the current note to a different sub-folder makes it read-only

### ISSUE THREAD

**Issue by szotsaki** [pbek/QOwnNotes#446]
1. Create a new note and then a new sub-folder
2. Add some content to the note
3. Right click on the note's name and move it to the new sub-folder

Now, it cannot be edited in the Note edit panel until a different note is selected.

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue.

**Comment by pbek** [comment]
## 16.12.16
- when the current note is moved to a different note sub-folder the current note
  will now be unset, like when it is moved to a different note folder

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by szotsaki** [comment]
Thank you, it works. The only thing I noticed that when I moved the last note out of a sub-folder, an empty document remained. When I wrote something inside, it got lost when I switched to an other note.

**Comment by pbek** [comment]
thank you for testing, I will try to reproduce that...

**Comment by pbek** [comment]
## 17.01.0
- improved on setting the note text edit to be readonly if the last note from a 
  note folder or note sub-folder was removed or moved somewhere else or when
  there is no visible note to view

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by szotsaki** [comment]
Thank you, it works fine!

**Comment by pbek** [comment]
Great, thank you for testing!
