### ISSUE TITLE
QOwnNotes with Owncloud issues

### ISSUE THREAD

**Issue by Rowabi** [pbek/QOwnNotes#447]
I'm trying to replace evernote with QownNotes and Owncloud. So far I got a working setup with QOwnnotes on the PC and an owncloud 9.1.3 installation. I have managed to get my notes synched with a documents folder within ownnotes. 
However I have the following issues I can't get solvedafter hours fiddling with the installations:
1. In owncloud I get all Notes dumped into one folder. There is no possibility to use Tags or search through the notes. 
2. I have not found a way to get my QOwnnotes into the OwnCloud Notes section. 
How is this done? 
Is there a way to use the groups together with the Tags from QOwnnotes?
3. Synching with mobile devices seems to require synching with the Notes section which currently isn't working either. I understand that this is is an issue for the providers of the Apps.
Is there maybe a description somewhere from someone that has set this up and has this working properly?
Thanks for any hints to point me in the right direction.

**Comment by pbek** [comment]
> When creting a note in Owncloud you can put the note to a group or define a new group. I was hoping this could be mapped to the QOwnNotes tags.

no, that's not supported

> But notes in owncloud are stored in .htm format, in QOwnNotes all my notes are stored as .md files. Is there a way to make owncloud Notes to use and display .md files as well?

Are you sure we are talking about the ownCloud Notes app and not ownNote? QOwnNotes does not support ownNote. see: <http://www.qownnotes.org/Knowledge-base/Does-QOwnNotes-support-ownNote>

**Comment by Rowabi** [comment]
Sorry, I'm totally confused now. I thought to be able to synch with mobile devices I need to setup ownnote. 
What do I need on my owncloud installation to work with the qOwnNotes. 
My qOwnNotes folder gets perfectly synched with ownloud in the dcuments structure. But how can I edit or work with them in owncloud. I guess I'm missing an essential step here.

**Comment by pbek** [comment]
In the first paragraph on <http://www.qownnotes.org/> the ownCloud Notes application is linked.
A bit lower the iOS and Android applications you can use are linked.

**Comment by pbek** [comment]
There also is a link in the QOwnNotes settings dialog...

**Comment by pbek** [comment]
I now also linked it on <http://www.qownnotes.org/Knowledge-base/Does-QOwnNotes-support-ownNote>.

**Comment by Rowabi** [comment]
Thanks for your patience and pointing me in the right direction.
Now thngs work together. The lack of structure within owncloud has been mentioned in many posts here. This is really a pity with many notes. 
One last question. Is there a way to standardize the file format?
Notes creates .txt files (I found no way to configure this app and specify a file format)

**Comment by pbek** [comment]
Yes, ownCloud Notes is creating txt-file, but it can read md-files too. If you want you can configure QOwnNotes to create txt-files instead md-files...

**Comment by Rowabi** [comment]
Thanks. I'll continue experimenting and find out what's best tehn.
thanks for your assitance!

**Comment by pbek** [comment]
Happy experimenting! ;)
