### ISSUE TITLE
Skripting: Qownnote as "preprocessor" for static website generators?

### ISSUE THREAD

**Issue by widolf** [pbek/QOwnNotes#448]
First of all: THANKS for QOwnNotes! I actually switched completely and dropped all other note taking apps! 
Second: a prosperous new year to pbek and his project!

Using QOwnNotes with nc/oc made me thinking one step further, but since I am not a developer I'd need some advice. 
One could consider any file"note.md" as the precursor of a website to be delivered by the system of your choice. Let's take [Grav](https://getgrav.org/) as an example (there are others - I know ...). Grav digests "note.md", if [some requirements are met](https://learn.getgrav.org/content/content-pages).

So, I am wondering if anyone has already been trying to skript an export from QOwnNotes to be synced to ones webserver using the synctool of ones choice?
The skripts I have seen so far, seem to extract tags already, but I have no idea how to handle the folder structures etc and how to "pre-pend" the page file with the header information e.g. 

The above idea does not seem limited to Grav of course, but would imho add a new layer of usability to QOwnNotes.

Thanks!

**Comment by pbek** [comment]
Thank you for your kind words, also to you all the best for 2017!
You could write a custom action to generate the html (see <http://docs.qownnotes.org/>).
