### ISSUE TITLE
Freezing every few seconds when typing

### ISSUE THREAD

**Issue by eriteric** [pbek/QOwnNotes#449]
on OSX 10.11.6
When typing a note it freezes/pauses every few seconds to save and do its thing. Don't have any scripts active, is connected to a nextcloud from within qOwnNotes preferences and is using a notes folder synced via the owncloud app.

Debug: https://gist.github.com/eriteric/a6e40f59a52363a6a4b4fef815920fed

**Comment by pbek** [comment]
What was printed in the log pane?
Do you have an SSD or a spinning disk?
How large is the note you are editing?
You have a lot of notes in your note folder, maybe that's an issue when something modifies the note folder externally and it gets reloaded in QON. Could you please try with an empty note folder and see if you still have the same problem.

**Comment by eriteric** [comment]
1. Log pane: 
```
[10:26:58] [status] Stored 1 note(s) to disk
[10:26:58] [status] Notes directory was modified externally
```
2. PCIe-based SSD
3. Very small note being edited, same results when creating a new note
4. I think so. When trying a new empty notes folder, not connected to nextcloud or anything, and creating a note - the log will say the same `Stored 1 note(s) to disk` but no freezing.

**Comment by eriteric** [comment]
Set back to the correct folder and..
Same results with: Pausing synchronization in the OwnCloud file sync app
The freezing is less frequent when the qOwnNotes connection to nextcloud is disabled

**Comment by pbek** [comment]
> Notes directory was modified externally

all notes will be read from disk, this definitely takes time for 2k+ notes! you only could turn off that check altogether in the general settings...

**Comment by eriteric** [comment]
Ok I see it now thanks, in Settings -> General. I simply set the save interval time to a higher number.
