### ISSUE TITLE
Android APP http urls / non https

### ISSUE THREAD

**Issue by demlak** [pbek/QOwnNotes#45]
Hi,
for sure we all know, wh https is better than http... but not all of us use https (because of...)...
so.. desktop app on linux and windows support to use http links.. but android app not... why?

please enable support for non https links in android app..

thx a lot

**Comment by pbek** [comment]
Hi, @demlak 
Which Android app are you referring to?
...because I'm not the author of one :smile:

**Comment by demlak** [comment]
oh.. i thought you are... because of linking directly to it:
https://f-droid.org/repository/browse/?fdid=org.aykit.MyOwnNotes

my fault... now i see their github link there =)
thx anyway =)

**Comment by pbek** [comment]
That's right, I'm only linking for reference.

It really would be great to offer the "full" stack, containing desktop, web and mobile apps at the same time, but I'm already working like a madman on the desktop part. :wink: 

I'll close this issue now unless you want to write an Android app... :wink:

**Comment by pbek** [comment]
There now is an Android App: https://www.qownnotes.org/getting-started/qownnotes-android.html.
