### ISSUE TITLE
Single formatting characters get deleted

### ISSUE THREAD

**Issue by Crendgrim** [pbek/QOwnNotes#454]
When trying to put only a single character that's also used for formatting on a line and trying to enter a newline, the editor gets confused.

For `+`, `-` and `*`, it removes the character. `_` and backtick do not cause problems.

Additionally, only for `*`, if you enter a space and then the asterisk, it will suggest a second asterisk. Pressing enter now results in the second, suggested one staying. For the other problematic characters, leading whitespace simply gets removed (i.e. using them in a pre-formatted/code environment).

Expected behavior would be the single keys staying where they are.

**Comment by pbek** [comment]
Can you please explain in more detail and step by step what you did, what happened and what you expected.

**Comment by Crendgrim** [comment]
I'm on a new line. I enter one of the three characters mentioned, let's use `+`. My line looks like this (`¦` denotes the cursor):
```
+¦
```
I press `Enter`. This happens:
```
¦
```
What I expected:
```
+
¦
```

When coupled with whitespace in the beginning:
```
    +¦
```
becomes
```
¦
```
instead of
```
    +
¦
```

**Comment by pbek** [comment]
This is intended behavior. You can just press enter if you want to stop writing list items and the empty list item will be removed.

**Comment by Crendgrim** [comment]
Okay, fair enough if it's a design decision. It does also happen in code blocks, though, which I think would still be unwanted behavior.

**Comment by pbek** [comment]
Every editor feature is unaware of markdown code blocks and I certainly don't want to implement a setting for each and every of them to toggle that... :smile_cat:
