### ISSUE TITLE
The syntax highlighter ignores code blocks in favor of lists

### ISSUE THREAD

**Issue by Crendgrim** [pbek/QOwnNotes#455]
If a line in a code block starts with a `-` or `+`, the syntax highlighter gets confused and tries to highlight this line as a list. The preview correctly displays it as part of the code block.

An example would be a small calculation:

```
       100
     +  20
     = 120
```
The second line is not displayed as part of the code. It does not matter whether tabs or spaces are used for indentation, nor does it matter how far indented the line is.

**Comment by pbek** [comment]
Technically a `+` with leading spaces is a list, the preview interprets it the same way.
Can you please just use the code block 3 ticks...

**Comment by Crendgrim** [comment]
Oh, I used those code blocks here on Github but didn't realize QOwnNotes would support them as well. That's a good workaround, at least.
Still, the syntax highlighter and the render preview disagree on what this line is: https://i.imgur.com/vM0KYWq.png

**Comment by pbek** [comment]
I can't see what your markdown text looks like in the screenshot.
