### ISSUE TITLE
CSS styling preview text through scripting

### ISSUE THREAD

**Issue by CTrauma** [pbek/QOwnNotes#456]
I've read all the docs I can find and looked at the examples and I can't seem to get selectors to work as I expect.

For example, lets say I want to have all my h1 headers to be colored orange in the preview window. I would expect the following qml script to work.
```
import QtQml 2.0
/**
 * This script adds custom styles to the application
 *
 * You can get the object names from the *.ui files, for example
 * https://github.com/pbek/QOwnNotes/blob/develop/src/mainwindow.ui
 *
 * Take a look at http://doc.qt.io/qt-5/stylesheet-reference.html for
 * a reference of what styles are available.
 */
QtObject {
    /**
     * Adds custom styles
     */
    function init() {

        script.addStyleSheet("QTextEdit#noteTextView h1 {color: #FF9137;};");
    }
}
```

But it doesn't work.  If I remove the 'h1' from the selector all the text in the preview window is colored orange, so I'm guessing there is something wrong with my selector syntax but I can't figure out what.

I have been following this documentation..
http://doc.qt.io/qt-5/richtext-html-subset.html
http://docs.qownnotes.org/en/develop/scripting/README.html#add-a-custom-stylesheet

Is this possible to do? What would the correct syntax be?

**Comment by pbek** [comment]
The stylesheets you are working with are for styling the user interface, not for styling the html that is viewed. You want to modify the html inside the preview and add CSS styles there.

see: <http://docs.qownnotes.org/en/develop/scripting/README.html#notetomarkdownhtmlhook> and the example <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/preview-styling.qml>

Does that answer your question?

**Comment by pbek** [comment]
The style you want to inject would be `h1 {color: #FF9137;}`.

**Comment by pbek** [comment]
I now made that more clear at <http://docs.qownnotes.org/en/develop/scripting/README.html#add-a-custom-stylesheet>. Thank you for mentioning...

**Comment by CTrauma** [comment]
Worked perfectly.. I knew I was missing something basic, thanks..

**Comment by pbek** [comment]
Great! ;)

**Comment by onesentforth** [comment]
I'm trying to change the styling of code spans and code blocks in the preview pane? Which html element should I use to style them?

I have tried "code," "pre," "codespan," and "codeblock" with no luck.

**Comment by onesentforth** [comment]
Thanks for the quick reply.
It's rendered as <code>, but when I try styling the font color in CSS, it does not work. It does, however, allow me to change the font-weight property. It seems that the font color and background color are somehow non-editable for code blocks.

**Comment by pbek** [comment]
I had no troubles using:

```css
code { color: red }
```

my code blocks had red text

**Comment by pbek** [comment]
btw. in case you didn't know: there is a script `Custom note preview styling` in the script repository where you can add those styles directly

**Comment by onesentforth** [comment]
Got it to work... had to include the paragraph tag as well.

`p code { color: green }`

**Comment by pbek** [comment]
Ok, since I don't know how your html code looks (what scripts you are using for generating the html) it should be ok. :)
