### ISSUE TITLE
Table styling

### ISSUE THREAD

**Issue by CTrauma** [pbek/QOwnNotes#457]
Is it possible for a table to have a border?

docs say:

table Supports the following attributes: border, bgcolor (Qt color names or #RRGGBB), cellspacing, cellpadding, width (absolute or relative), and height.

But no matter how I style it I can't get a border using...

I'm referencing these docs for the version of  Qt I'm building against:

https://doc-snapshots.qt.io/qt5-5.6/richtext-html-subset.html

That would make me think I could style it with

```
table {border-color: black; border-style: solid;}
```

**Comment by pbek** [comment]
try using `border-width: 1px`...
<https://developer.mozilla.org/en-US/docs/Web/CSS/border>

**Comment by CTrauma** [comment]
hrmm `border-width` is not listed as an available CSS property in Text Widgets, but I'll give it a try..

**Comment by CTrauma** [comment]
that worked.. huzzah.. would have been nice if they had put that in the docs here:

https://doc-snapshots.qt.io/qt5-5.6/richtext-html-subset.html#table-cell-attribute

I wonder what else isn't documented..

**Comment by CTrauma** [comment]
Just adding this here.. this seems to be a better reference

http://doc.qt.io/qt-5.6/stylesheet-reference.html

**Comment by pbek** [comment]
I will link to <http://doc.qt.io/qt-5/richtext-html-subset.html> in the documentation and the example script...

**Comment by pbek** [comment]
If you want you edit the pages add the link yourself as pull request. ;)

- <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/preview-styling.qml>
- <http://docs.qownnotes.org/en/develop/scripting/README.html#notetomarkdownhtmlhook>

**Comment by pbek** [comment]
I now did it myself.
