### ISSUE TITLE
Importing .html notes

### ISSUE THREAD

**Issue by redsky0** [pbek/QOwnNotes#459]
Hi, I was looking to move from Wiznote (very similar to Evernote) to QOwnNotes.

I see QOwnNotes does .html exporting of notes. Luckily, Wiznote can also export .html.

However, I only see importing of Evernote .enex as an option, is there an option I'm missing to import .html?

Short of that, is there an easy to use batch converter of .html to .md that you can recommend? My technical skills are relatively limited.

Thanks!

**Comment by pbek** [comment]
Currently you can paste html from a web-browser to a note...
It generally would make more sense if you would use a tool like <http://pandoc.org/> to convert html files to markdown...

**Comment by redsky0** [comment]
Thanks, I had a look at this earlier and will probably go down this route. 

If anyone else is interested, I believe the link below has the .bat script to process a directory using pandoc, although I have yet to try it myself:

http://stackoverflow.com/questions/27852067/batch-convert-files-with-pandoc-in-windows****

**Comment by pbek** [comment]
Thank you. Please tell us about your experiences afterwards.
