### ISSUE TITLE
where to find the current version number?

### ISSUE THREAD

**Issue by LiangWei88** [pbek/QOwnNotes#46]
Hello, Where can I find the version I am using?
I want to compare to the latest version 
and know if I use the newest one

**Comment by pbek** [comment]
Which version are you referring to? The version of QOwnNotes? You can check if there is an update with `Help / Check for updates`. In the about dialog you also find the version number.

**Comment by LiangWei88** [comment]
Thanks that ok
I found it

**Comment by pbek** [comment]
:+1:
