### ISSUE TITLE
Add spellcheck support

### ISSUE THREAD

**Issue by geiseri** [pbek/QOwnNotes#460]
This is a big feature for me since my spelling is horrible.  While this is not an issue locally, when I share notes to others I find my spelling errors embarrassing.  I have implemented this feature with QTextEditor and hunspell in a few places so in theory I could offer a patch.  I would just want to see what the authors interest is in this.  Thanks!

**Comment by pbek** [comment]
Yes, I'm interested and there even is an open feature request for it #125 (let's head over there).
But so far I've failed to integrate any solution, since it has to work on Linux, macOS and Windows and with both qmake and cmake.
