### ISSUE TITLE
Instant Crash

### ISSUE THREAD

**Issue by Gryphus1ne** [pbek/QOwnNotes#461]
Hi,
I just came across an issue that I don't fully understand. It seems to be a character limit, yet when I swap out the text for a string of 1's of the same length, it's fine. I thought it may have have been file size, but there are larger files in the same folder. So I'm a bit confused.

You should be able to replicate it by importing the attached file and copy/pasting the last line once or twice. Using build 17.01.2.

[Note 2017-01-05T18.54.13.txt](https://github.com/pbek/QOwnNotes/files/688783/Note.2017-01-05T18.54.13.txt)

**Comment by pbek** [comment]
I had no problem with the content of your note.

Can you please post the output from the debug settings.
Did you have any output in the log panel?

**Comment by pbek** [comment]
I can only reproduce it under Windows, not under Linux and macOS.
Unfortunately I couldn't make the QtCreator debugger work under Windows, I tried to get it working for an hour now, it just gets stuck at various places (even without the prepared note)... :(

Do you have a QtCreator installed by chance?

same problem as #471

**Comment by pbek** [comment]
## 17.01.4
- fixed a crash under Windows when entering an opening `<` with a lot of text
  after it, but no closing `>`

I close this issue here now, in #471 there was more feedback.

**Comment by pbek** [comment]
There now is a new release, could you please test it now works for you?

**Comment by Gryphus1ne** [comment]
Apologies for not getting back.

I had looked for a log file when I posted but couldn't find it. I didn't realize I had to enable it.

17.01.4 has fixed the issue, thank you. Sorry I couldn't be more help.

**Comment by pbek** [comment]
Great, thank you for testing! ;)
