### ISSUE TITLE
Unable to create todo from QOwnNotes when starting up

### ISSUE THREAD

**Issue by Jomiwe** [pbek/QOwnNotes#462]
(Version Info at the end)
Hi all, 
in my environment, it is not possible to create new todos, if I have not assigned at least a first existing todo.
Walkthrough:
1. Start up QOwnNotes
2. Create a new note or use an existing one
3. Place cursor in your text
4. Use "Todo List" Icon
5. Type in the name of a NEW todo item (upper left field in dialog)
6. Type in subject (upper right field)
7. Set reminder
8. Write in more text in body
9. Buttons "Save", "Delete" and "Note..." are all greyed and not working.

If I first use an existing todo and place it into my note, there are no more problems, even creating new todos afterwards.
There are no problems using existing todos from my Owncloud installation, like changing and completing them.
Thanks for this brilliant piece of software and your support.

Michael

## General Info

**Current Date**: `Fr Jan 6 10:21:20 2017`
**Version**: `17.01.2`
**Build date**: `Jan  5 2017`
**Build number**: `2701`
**Platform**: `windows`
**Operating System**: `Windows 10`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.7.1`
**Qt Version (runtime)**: `5.7.1`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `G:\UserData\Jomiwe\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Program Files (x86)\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `2`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: 
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `9.1.0.15`
**appVersion**: `16.09.0`

**Comment by pbek** [comment]
Thank you for your kind words!

Did you press `Return` after step 5 to create the new todo item?

**Comment by Jomiwe** [comment]
Thanks for your quick help.
I already recognized this some 30 minutes later after posting my issue. Sorry for that.
So, again it was a PEBKAC, a Problem Existing Between Keyboard And Chair.
Maybe I should contribute a documentation on working with todos. Where should I send my work to?
Cheers and keep on with your respectable work!

**Comment by pbek** [comment]
You could create a new restructuredText file in <https://github.com/pbek/QOwnNotes/tree/develop/doc> and I will link to it in den index file. It will then be visible at <http://docs.qownnotes.org/>. Thanks a lot!
