### ISSUE TITLE
"Image as link" markdown syntax highlighting

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#463]
Pandoc converts "images as link" to a `[![name](image)](link)` constructs.

At first I thought that it's a misbehaviour. But looks like it's a valid markdown, and the app renders it correctly.

Maybe it's worth to add support for such syntax to the highlighting engine.

**Comment by pbek** [comment]
I haven't seen such a link before. :) Should we highlight it as a link?

**Comment by Maboroshy** [comment]
For me it's an image first, link second. I'd go for an image.

**Comment by pbek** [comment]
## 17.01.3
- image links like `[![name](image)](link)` and `[![](image)](link)` will now
  also be highlighted

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment]
Everything works. Thanks.
