### ISSUE TITLE
Note modified  in subolder disappears in QOwnNotes

### ISSUE THREAD

**Issue by Rowabi** [pbek/QOwnNotes#464]
I thougth that the advantage of storing notes as textfiles is that they can be edited anywhere. 
However, I stored a note in a subfolder and then modified the note in owncloud documents (not Notes, since no Subfolder Support available). After synch the modified note disappears on my desktop client. If I move the modified note back to the main folder in owncloud, it reappears in QOwnNotes again. Is this a bug?

**Comment by pbek** [comment]
Did the ownCloud sync client remove your note on your desktop computer?

**Comment by Rowabi** [comment]
Sorry, I cannot repeat this behaviour. 
Currently this works fine.
