### ISSUE TITLE
Limit on Evernote  Enex Import?

### ISSUE THREAD

**Issue by Rowabi** [pbek/QOwnNotes#465]
I have imported 25 Notes successfully with QOwnNotes. Now if I try to import any Enex-File (with 1 note or several notes) I get the message, that the note(s) where imported successfully. But the notes are not in QOwnNotes nor in the directory. 
What am I missing here?

**Comment by pbek** [comment]
What did you do differently in your first 25 notes import and your 2nd import?
The limit is the amount of RAM you have available because the whole XML file is read into memory...

**Comment by Rowabi** [comment]
The only difference is, that the first Import was a coupld of days ago. In the meantime there where two SW updates of QOwnNotes I have installed.
Windows Taskmanager reports 1.1 GB free RAM. difficult to fill with notes.

**Comment by pbek** [comment]
No changes that would cause this come to mind...
Can you still import these 25 notes to an other note folder?

**Comment by Rowabi** [comment]
No. An already successfully imported filed doesn’t work either.

I found the option to log debug informations. 

I get this info in the:

[Jan 08 08:54:44] [critical]: "Das System kann den angegebenen Pfad nicht finden."

(Although I changed the language back to German the error message is German) 

Translated: „The System cannot find the specified path“.

Which path could be wrong?

Thanks

**Comment by pbek** [comment]
...the path of your selected enex file. I now add that path to the error message in the next release.

**Comment by pbek** [comment]
So which file did you try to import? It should now be logged...

**Comment by philiptruax** [comment]
I've got this issue when importing some of my notes too. Debug log outputs the following. 
`[Jan 11 12:12:56] [critical]: "The filename, directory name, or volume label syntax is incorrect."`

I've got an HTML export as well as an ENEX to compare against. I'm running the latest version of the software.

I've got 333 notes importing and only 272 make it into QON despite getting a success message
![importdialog](https://cloud.githubusercontent.com/assets/11514343/21860168/707d7bce-d7fd-11e6-99f9-c828d8c791b7.JPG)
After import
![notespresent](https://cloud.githubusercontent.com/assets/11514343/21860178/79864c14-d7fd-11e6-9cdd-7dd4711af195.JPG)

Here's the raw log file. I'm going to see if I can get just the files that aren't imported into their own ENEX to upload. 
[QOwnNotes.txt](https://github.com/pbek/QOwnNotes/files/699666/QOwnNotes.txt)

**Comment by philiptruax** [comment]
I'm noticing that almost all of the notes that can't be imported have symbols in the title like ? | or # I should have it shortly for you to test against.

**Comment by philiptruax** [comment]
Here's a file of just notes that won't import. It appears to import the image assets but not the notes or text themselves. 
[WontImport.zip](https://github.com/pbek/QOwnNotes/files/699750/WontImport.zip)

**Comment by pbek** [comment]
Yes, it seems the note files can't be created because the file names (headline = filename) are not allowed in your file-system.
I'll see if I can do something about that...

**Comment by pbek** [comment]
For me (under Linux, KDE Neon) the importer said 46 notes were imported and it seems all notes were present... Did no note of the WontImport.enex work for you?

**Comment by pbek** [comment]
## 17.01.6
- under Windows some characters that are asking for troubles are now removed 
  from the title at the Evernote import

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by philiptruax** [comment]
Most of the notes import properly. The only ones I can confirm do not open properly are both titled -

`A simple shell script to quickly / easily install "pacaur" on archlinux`

Everything else appears exactly as it does in Evernote.

**Comment by pbek** [comment]
So I guess I will add `/`, `\`, `'` and `"`...

**Comment by Rowabi** [comment]
Tried the latest Version. Unfortunaltey no change to the imort problem.

**Comment by pbek** [comment]
@Rowabi, I'm sorry, you never posted an other log 9 days ago...

**Comment by pbek** [comment]
## 17.01.7
- under Windows some more characters that are asking for troubles are now 
  removed from the title at the Evernote import

**Comment by philiptruax** [comment]
@pbek has 17.01.7 been released? I'm not seeing it in the release logs and QON says I'm at the latest version. Just want to make sure you're not waiting on me for a response and testing.

**Comment by pbek** [comment]
Sorry, it's not released yet, I'll try to on the weekend.

**Comment by philiptruax** [comment]
No worries, mate. I appreciate everything you do and the gift you've given us in QON. Just wanted to make sure I didn't miss something.

**Comment by pbek** [comment]
The last two weeks really were a bucket of pain. :frowning_face:

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by philiptruax** [comment]
All of the files that should appear do appear. There are some that do not, but I do not believe it's the same issue and I believe is corruption/duplication in the ENEX itself as Evernote has issue with these notes as well and the titles are exactly the same. I think this issue can be closed.

**Comment by pbek** [comment]
Great, thank you for testing!
