### ISSUE TITLE
Find in current note functionality

### ISSUE THREAD

**Issue by onelittlehope** [pbek/QOwnNotes#466]
The default panels in QOwnNotes are:

- Tags
- Note search
- Note folder
- Note list
- Navigation
- Note edit
- Note tags
- Note preview

That setup is great for creating, editing and managing notes.

Once you have your collection of notes, you want to be able to reference them in an easy to digest manner. The following panel setup is great for doing that:

- Tags
- Note search
- Note folder
- Note list
- Navigation
- Note preview

I saw that with the use of "Workspaces", I can setup a default "Edit" workspace and another "View only" workspace to have an easy way to switch between using QOwnNotes for reference and for managing notes. Handily, QOwnNotes even remembers what the last used workspace was when the application was closed and restores to that workspace when the application is re-opened. Neat!

Would it be possible to implement:
- ~~~"Find in current note" functionality in the "Note preview" panel? Without this, we can't search for content in the note being previewed.~~~ Update: I just noticed that the "Note search" panel allows you search in notes providing you've got the note you are interested in selected. Which is more than sufficient. Ack. I keep creating new notes by accidentally pressing Enter in the "Note search" panel.
- In both the "Note preview" and "Note edit" panels, can the "Find in current note" functionality expose a checkbox to toggle between plain text search and regular expression search?

**Comment by pbek** [comment]
Can you please rephrase your feature request. You can already search your current note with regular expressions.

**Comment by onelittlehope** [comment]
>You can already search your current note with regular expressions.

Yes, I saw that you can search the current note by:

- Pressing Ctrl+F to bring up the "Find in current note" panel
- Hitting the "Replace text" button to bring up the "Replace text" panel
- Changing the "Mode" combo box to "Regular expression" and then clicking the "Replace text" button to toggle off the "Replace text" panel


When you use QOwnNotes to read through your notes, it is easier to read your notes if the "Note edit" panel is not present and you are simply viewing notes in the "Note preview" panel.


In the screenshot you can see I've setup a workspace called "Read only" which doesn't have the "Note edit" panel open. In that workspace, I can't hit Ctrl + F to search the note. I can however, enter text into the "Note search" panel on the left and search through that.

![screenshot_20170107_225333](https://cloud.githubusercontent.com/assets/3677874/21745969/ec8330d2-d52e-11e6-9bc1-4641887824d4.png)

I didn't try to use regular expressions in the "Note search" panel until your response. I can confirm that it does indeed support regular expressions. Neat! :-)

However, I found an issue when trying to enter a regular expression. I'll create another github issue for that.

This issue can be closed since I can work around not being able to search using Ctrl + F and instead will just use the "Note search" panel for searches.

**Comment by pbek** [comment]
Great. :)

**Comment by pbek** [comment]
Since 17.12.0 you can now also search in the preview. ;)
