### ISSUE TITLE
QSqlQuery::prepare: database not open

### ISSUE THREAD

**Issue by onelittlehope** [pbek/QOwnNotes#467]
When starting up QOwnNotes for the first time, the following is logged to stdout after the installation wizard finishes:

```
QSqlQuery::prepare: database not open
countAll :  QSqlError("", "Driver not loaded", "Driver not loaded")
QSqlQuery::prepare: database not open
store :  QSqlError("", "Driver not loaded", "Driver not loaded")
```

To reproduce:
- Replicate a clean start by ensuring no previous configs exist: `rm -rf ~/ownCloud/ .config/PBE/ .local/share/PBE/`
- Start: `QOwnNotes`
- In the "Welcome to QOwnNotes" installation wizard, leave everything as defaults and click "> Next" twice and after clicking the "Finished" button, you will see the above messages output to stdout.

**Comment by pbek** [comment]
Thank you for reporting. I will see if I can reproduce that...

**Comment by pbek** [comment]
## 17.01.4
- fixed two database errors when using QOwnNotes for the first time

**Comment by pbek** [comment]
There now is a new release, could you please test it now works for you?

**Comment by onelittlehope** [comment]
I confirm that the messages no longer appear and the matter is fixed.

**Comment by pbek** [comment]
Great, thank you for testing!
