### ISSUE TITLE
Abnormal cpu/memory usage when searching for text using Note search panel

### ISSUE THREAD

**Issue by onelittlehope** [pbek/QOwnNotes#469]
To reproduce:

- Replicate a clean start by ensuring no previous configs exist: `rm -rf ~/ownCloud/ .config/PBE/ .local/share/PBE/`
- Start: `QOwnNotes`
- Enter the following text in the "Note search" panel: `I will search for the string` it also happens with: `^_` (where _ = space character)

![issue](https://cloud.githubusercontent.com/assets/3677874/21746132/9c286a62-d533-11e6-9273-9151eafc1e99.gif)

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue under Linux. I couldn't under macOS...

**Comment by pbek** [comment]
I neither can reproduce this on KDE Neon.

**Comment by onelittlehope** [comment]
Is there a debug build I can use to help narrow down the issue? I looked at the source code and I wasn't sure whether a search is carried out against a SQLite DB (which is hanging) or whether its a regex search which is hanging. If you could confirm what components are involved in doing a Note search (source file + function), I can then check whether the versions of libraries involved are sufficiently different to cause the behaviour.

I can reproduce this consistently in Windows 10 + Linux if I type in `^_` (where _ = space character) in to the "Note search" panel.

I just updated to QOwnNotes 17.01.3 on both Linux and Windows 10 and the issue was reproducible by:

- Switching to the "full" workspace
- Entering `^_` (where _ = space character) into the "Note search" panel.

Ps. Thank you for implementing the Ctrl+F (Find in note) functionality in the "Note preview" panel and for putting the two default workspaces as "full" / "minimal".

**Comment by pbek** [comment]
I guess it will search for "everything not a space", that could take a while... :)

**Comment by pbek** [comment]
> Ps. Thank you for implementing the Ctrl+F (Find in note) functionality in the "Note preview" panel

there is no Ctrl+F for it, but the search panel also shows results in the preview

**Comment by pbek** [comment]
## 17.01.4
- fixed an issue with the note search getting stuck when searching for `^ ` or `  ` (just spaces)

**Comment by pbek** [comment]
There now is a new release, could you please test it now works for you?

**Comment by onelittlehope** [comment]
I confirm that entering `^ ` no longer hangs QOwnNotes and causes it to use 100% cpu and lots of memory. The issue is fixed. Thanks.

**Comment by pbek** [comment]
Great, thank you for testing!
