### ISSUE TITLE
How to translate it to and other language?

### ISSUE THREAD

**Issue by LiangWei88** [pbek/QOwnNotes#47]
I want to contribute and translate the QOwnNote to Chinese.
How can I start?

**Comment by pbek** [comment]
Thanks a lot for your support!

I created a translation file for *Chinese*: <https://github.com/pbek/QOwnNotes/blob/develop/src/languages/QOwnNotes_cn.ts>

Later I will write a tutorial.
Meanwhile I guess this would be the best guide:

- Create a fork of [QOwnNotes on GitHub](https://github.com/pbek/QOwnNotes/) and `git clone` your fork on your computer
- Install [Qt Linguist](http://qt-apps.org/content/show.php/Qt+Linguist+Download?content=89360) to easily translate text
- Open the translation file from your fork with Qt Linguist (for example `QOwnNotes_de.ts`) and translate the text with it
	- The translation files are located here: <https://github.com/pbek/QOwnNotes/blob/develop/src/languages>
- Commit and push your changes to your fork of QOwnNotes and create a pull request for your changes.
	- This way you can take credit for your valuable contribution!
	- Please make sure you are working in the `develop` branch and make your pull request to that branch.

Is that explanation too technical?

**Comment by pbek** [comment]
I now tried to write a "mini tutorial" here: <http://www.qownnotes.org/Knowledge-base/How-can-I-help-to-translate-QOwnNotes>

**Comment by pbek** [comment]
Thanks a lot for your contribution. :tada: Please feel free to maintain and update your translation with further pull requests!

**Comment by Zack-83** [comment]
Hallo, in the above page the link to Qt linguist is broken.
Anyway I joined the project on Crowdin: it was easy :)

**Comment by pbek** [comment]
Thank you for mentioning, I removed that whole part now (since it's obsolete).

Sticking to https://docs.qownnotes.org/en/latest/contributing/translation/ would be best. :wink:
