### ISSUE TITLE
Feature: Open an existing md file?

### ISSUE THREAD

**Issue by polarathene** [pbek/QOwnNotes#470]
I have an existing markdown file(.md extension) that I opened with my file browser and selected QOwnNotes as the application. It didn't seem to have any effect and instead presented me with my last workspace/note in use. It doesn't appear to be a supported feature in the menu dialogs to open by file either.

Would it be possible to import a note from the file system or open one into a "scratch"/temporary note that is not saved into my own notes/database? QOwnNotes is pretty great for viewing and editing markdown content and would be great to use files such as for open-source projects, documentation or other use cases where the content belongs in a file elsewhere and not the regular location used for notes created in the application.

If you feel that is outside the scope of QOwnNotes and I should use another app for these markdown files that's perfectly ok too :)

**Comment by pbek** [comment]
I'm sorry, QOwnNotes isn't meant as markdown viewer... I think there are much better solutions for that. QOwnNotes relies on note files in note folders.

**Comment by refack** [comment]
> I'm sorry, QOwnNotes isn't meant as markdown viewer or editor... I think there are much better solutions for that. QOwnNotes relies on note files in note folders.

Since I like your interface very much, please give a recommendation for a "better markdown viewer or editor"

**Comment by pbek** [comment]
@refack under Linux I use: <https://remarkableapp.github.io/linux.html>

**Comment by Beurt** [comment]
Hello,

Since QON grew up as being the best Markdown Editor, are you still sure you won't enable the possibility to edit any md file from any directory?

**Comment by pbek** [comment]
Thank you. No, I don't think QON is the best markdown editor, it was always meant to be an "IDE" for note taking with markdown. 😁 
Using note folders as base is an integral part of QON, so currently I don't think it will ever mutate to a general Markdown Editor.

**Comment by Schnyarf** [comment]
But doesn't the Alt+Shift+O menu already essentially function as a mature, minimal MD editor/viewer? I think it would be really nice if you could open MD files with QON in that small editor. And if said file is in one of the user's note folders, it could simply open it in a new tab.

From a UX perspective I personally find it awkward being able to browse through all my MD files in a file manager but not be able to double-click and open them in the *main application that I edit them in*. Just food thought.

**Comment by Beurt** [comment]
I just discovered Alt+Shift+O, it is great!

**Comment by pbek** [comment]
Thant is just a view, not an editor...

**Comment by Schnyarf** [comment]
Oh, I didn't even realize that lol. Still, would be a nice feature IMO .^.
