### ISSUE TITLE
List depth > 5 not shown

### ISSUE THREAD

**Issue by Braintelligence** [pbek/QOwnNotes#473]
When writing a list the preview renderer doesn't show list depth > 5.
Here's a test to reproduce:

```
- Test1
	- Test2
		- Test3
			- Test4
				- Test5
					- Test6
						- Test7
							- Test8

No list anymore at Test 6
```

**Comment by pbek** [comment]
I'm sorry, I guess that's a limitation of <https://github.com/hoedown/hoedown>. If that's important for you you could file an issue at their issue page and keep me informed.

**Comment by Braintelligence** [comment]
No, it's not important for me, I guess...
I found some other markdown issues and probably will move on to another markdown editor, even though losing the tag functionality is sad.

Thank you anyway 😸.

**Comment by pbek** [comment]
QON was never meant to be a markdown editor and I myself don't use it as a markdown editor. ;)

**Comment by Braintelligence** [comment]
Markdown-Notetaking app? 😛

**Comment by pbek** [comment]
Plain-text file notepad with markdown support and oC / NC integration. :smirk_cat:

**Comment by motey** [comment]
Looks like an QOwnNotes issue,
https://github.com/hoedown/hoedown/issues/210#issuecomment-277428795

**Comment by pbek** [comment]
The nesting level was 16, I didn't thought that would be exceeded that easily. But on nearer inspection each level of the list takes two more levels. I will increase the limit to 32.
Thank you for your research, @motey!

**Comment by pbek** [comment]
## 17.02.6
- the maximum tag nesting level of the html preview was increased to 32 to 
  allow more levels of list items than six

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by motey** [comment]
![grafik](https://cloud.githubusercontent.com/assets/1006417/22918431/a66b5e16-f28a-11e6-94ff-1dff1cd33252.png)
Depth up to 10 is now supported. Good enough for me! Thx a lot!

**Comment by pbek** [comment]
Great, thank you for testing!
