### ISSUE TITLE
Hook when the note is save

### ISSUE THREAD

**Issue by smaguilarRTI** [pbek/QOwnNotes#474]
Hi all,

I would like to have a hook which is called when a note is save into disk.

Is it something planned? or easy to do?

Thanks a lot in advance

Best regards

Sebas

**Comment by pbek** [comment]
What are you trying to script?

I'm wondering that @Maboroshy didn't already request such a hook...
Currently there only is <http://docs.qownnotes.org/en/develop/scripting/README.html#handlenotetextfilenamehook>.

**Comment by pbek** [comment]
There already is such a hook and it's not documented (I've no idea why I forgot that, I will write something).

You'll find an example here: <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/execute-command-after-note-update.qml>

**Comment by pbek** [comment]
Even that example is deprecated, try this:

```JavaScript
import QtQml 2.0

/**
 * This script will execute an external program every time a note was written to the disk
 */
QtObject {
    /**
     * This function is called when a note gets stored to disk
     * You cannot modify stored notes, that would be a mess since 
     * you are most likely editing them by hand at the same time
     * 
     * @param {NoteApi} note - the note object of the stored note
     */
    function onNoteStored(note) {
        // execute an external program
        // try not to alter the note file or QOwnNotes will try to update 
        // the file every time you change the note
        script.startDetachedProcess("/path/to/my/program", [note.fileName]);
        
        script.log("program was executed for file: " + note.fileName);
    }
}
```

**Comment by smaguilarRTI** [comment]
Hi Patrizio,

My idea is to send the tasks to an external Task manager when the note is saved.

**Comment by pbek** [comment]
Then above example will work great for you. Let me know if you run in any troubles and post your script if you like! ;)

**Comment by Maboroshy** [comment]
> I'm wondering that @Maboroshy didn't already request such a hook...

You must be kidding. That request in #161 kind of started the whole scripting thing. :sunglasses:

**Comment by pbek** [comment]
I didn't find it because it had no "hook" in it. :) And there was no documentation. :)
