### ISSUE TITLE
"Delete current word/line" always triggers in editor pane

### ISSUE THREAD

**Issue by Crendgrim** [pbek/QOwnNotes#476]
If you select an input field that is not the main editor (note search, tag search, add tag dialog) and want to clear the input, the commonly used shortcut is Ctrl+Backspace. This, however, deletes the current word in the opened note (at cursor position in the editor view). The same applies to "delete current line" (Alt+Backspace).

Expected result would be as every other application behaves: Ctrl+Backspace acts on the currently selected input field, not somewhere else.

Also, probably related: When entering something in the "add tag" dialog, a number of matching suggestions is displayed. They cannot be selected by <tab>, but only by pressing arrow down.

**Comment by philiptruax** [comment]
This behavior is the same in box linux and Windows 7. 

Steps to reproduce. 
1. Click inside the markdown editor between a line of text.
2. Click inside the tag search or note search
3.  Press Ctrl+Backspace

The text in the editor is deleted.

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue.

**Comment by pbek** [comment]
Currently that is a shortcut that only works in the note edit, you could try to assign an other shortcut...

**Comment by pbek** [comment]
## 17.02.2
- if the shortcuts for deleting the current line or word isn't used in the 
  note text edit now the default shortcuts will be delegated to the widget 
  with the focus

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Crendgrim** [comment]
It now works as expected, thank you!

**Comment by pbek** [comment]
Thank you for testing!
