### ISSUE TITLE
[debug] "No carrier" in log every 10 seconds

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#477]
The app puts messages like `[22:13:25] [debug] "No carrier"` to log every 10 seconds. Not very informative. I've turned off all the scripts - no avail. 

Don't remember this behaviour a month ago, when I was also debugging some scripts with the log on.

I don't use in-app cloud integration if it matters.

**Comment by pbek** [comment]
I've no idea how to reproduce that...

**Comment by Maboroshy** [comment]
What's `No carrier` is about. When did it came from?

**Comment by Maboroshy** [comment]
And what function has 10 seconds time-out? Not my note change save timer for sure.

**Comment by Maboroshy** [comment]
Looks like todo list integration uses 10 sec timer. Can it say 'No carrier' for some reason? I tried to randomly change some it's options with no success.

**Comment by pbek** [comment]
Maybe your note save interval?

**Comment by pbek** [comment]
I've no idea what the "no carrier" message means...

**Comment by Maboroshy** [comment]
I'll just turn off debug massages altogether.

**Comment by pbek** [comment]
do you use a debug build of QOwnNotes? you shouldn't even be able to get debug messages in a release build...

**Comment by Maboroshy** [comment]
I use build from AUR.

**Comment by pbek** [comment]
I don't get debug messages there... What does `Qt Debug` say in the debug settings? It says `0` for me...

**Comment by Maboroshy** [comment]
Says 0 for me too. Yet I get these massages.
