### ISSUE TITLE
Link to note in subfolder

### ISSUE THREAD

**Issue by gesellkammer** [pbek/QOwnNotes#478]
The title says it: it seems to not be possible to link to a note in a subfolder.

Using version 17.01.5

Thanks!

**Comment by pbek** [comment]
Yes, that's right. The links themselves can only link to a note that is visible in the note list and the link dialog only shows notes from the current note sub-folder. Changing that would be a tremendous amount of work and then the next issue would be that users would move notes or rename note sub-folders and the links would break again... So currently I keep my fingers of it.

**Comment by pbek** [comment]
@Snousmoumryk, @gesellkammer, @Maboroshy I rewrote a lot of parts of the note linking to make that possible now

## 18.09.1
- **note links** will now also jump to notes in **other note sub-folders**
    - first only the current note sub-folder will be searched, if the note wasn't
      found there all note sub-folders will be searched
    - if the linked note was in another note sub-folder the current note 
      sub-folder will be changed to that note sub-folder
    - the note link dialog now shows notes of all note sub-folders
    - highlighting of note links if they are broken also works over all note sub-folders
    - automatically updating links when notes are renamed should now also work
      across note-subfolders 

There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
Great, thank you for testing!
