### ISSUE TITLE
Color schema does not reflect on the export file (pdf, html)

### ISSUE THREAD

**Issue by stavpup** [pbek/QOwnNotes#480]
Changing the color of links from orange (weird anyway) to blue, changes in the file but the exported file (pdf, html) has the orange color

ubuntu 16.10 !

**Comment by pbek** [comment]
If you are talking about the preview, you can modify styles with a script <http://docs.qownnotes.org/en/develop/scripting/README.html#notetomarkdownhtmlhook>.

Does that answer your question?

**Comment by stavpup** [comment]
I have corrected the bug report..

**Comment by pbek** [comment]
What "bug" do you want to report? The color schema on the settings page `Editor fonts & colors` is working for the editor. The preview (along with the html or pdf export) has nothing to do with the editor they use a different technology...

**Comment by pbek** [comment]
Can you please explain in more detail and step by step what you did, what happened and what you expected.

**Comment by stavpup** [comment]
Sure, of course. Lets start from the beginning. I have a note. In the note I have a few links (e.g. www.google.com). The links appear in orange color. I go to settings/editor/
editor fonts and colors, to change the color schema. But the color schema (light) does not let me change the Link color to orange. Ok, so I use the "copy" to make a new "Light (copy) color schema. That worked and I changed the link color to blue. So I figure that if I export the note to pdf, the link will be blue. It turns out that the link stayed orange like the original color schema.

I just tried the same thing in a windows machine and I got blue links. I will test it again in my ubuntu machine at home.

**Comment by pbek** [comment]
Which menu entry did you press to export the note as PDF? There are two.

**Comment by stavpup** [comment]
Note/export/ export as pdf (markdown) and note/export/ export as html (markdown).
Actually I just tried it and the link is orange again :-( on a windows machine.

**Comment by pbek** [comment]
These exports use the html from the preview (has nothing to do with the highlighting in the editor). You can modify it with the example I posted above...

Does that answer your question?

**Comment by stavpup** [comment]
Yes It does. The editor has nothing to do with the export options and the options to change those have not been exposed to the GUI..

**Comment by pbek** [comment]
Exactly. :)

**Comment by pbek** [comment]
See https://github.com/pbek/QOwnNotes/issues/430 for more information...
