### ISSUE TITLE
(macOS) Toolbar customization not persistent

### ISSUE THREAD

**Issue by corvid123** [pbek/QOwnNotes#481]
OS X 10.9.5
I used Preferences/Interface/Toolbars to add a button to toggle preview panel to the insertingToolbar. The button was added, but was not persistent. The button will disappear after 
1) closing and reopening QOwnNotes;
2) entering and then leaving Distraction Free mode;
3) toggling Toolbar off then on again.

Seems related to this closed issue:  https://github.com/pbek/QOwnNotes/issues/452

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue.

**Comment by pbek** [comment]
Does it work with other buttons you add to a toolbar?

**Comment by corvid123** [comment]
I just added two other buttons to the main toolbar: Export Note as PDF (text), and Show Navigation Panel.
Export Note was persistent, no problems.
Show Navigation stuck around after Distraction Free was toggled on/off, stuck around after toggling Toolbar, but disappeared after exiting/restarting the app.

**Comment by corvid123** [comment]
This time I added three buttons from the Panels area to the Main Toolbar: Subfolders, Navigation, and Preview. Toggling Distraction Free Mode and Show Toolbar worked fine, but all three buttons disappeared after exit/restart.

I haven't tried them all, but buttons from other categories seem to work ok.
It may only be the buttons from the Panels category.

**Comment by pbek** [comment]
Took me over an hour to get it working without breaking something else (at least I hope so)...

**Comment by pbek** [comment]
## 17.01.6
- you can now use the panel toggle menu items in your toolbars

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by corvid123** [comment]
yes, or course. I will check and report later.

**Comment by corvid123** [comment]
Seems fixed.Works fine so far at this end.

**Comment by pbek** [comment]
Great, thank you for testing!
