### ISSUE TITLE
(macOS) AutoUpdate fails

### ISSUE THREAD

**Issue by corvid123** [pbek/QOwnNotes#482]
OS X 10.9.5
AutoUpdate script fails to update. Must download dmg and install manually.
Sorry, I neglected to copy text from terminal. I will update this issue with the error message.

**Comment by pbek** [comment]
In the debug settings there is an option to fake an old version to trigger an update again.

**Comment by corvid123** [comment]
`Last login: Sun Jan 15 13:04:30 on console
------ $ /var/folders/42/5xvvktpn4k5bdcbpk31867k80000gp/T/QOwnNotes-Updater-QZO747.command ; exit;
QOwnNotes macOS updater script

usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
Created temporary directory 
Downloading https://github.com/pbek/QOwnNotes/releases/download/macosx-b2715-152553/QOwnNotes-17.01.5.dmg...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   598    0   598    0     0    177      0 --:--:--  0:00:03 --:--:--   177
100 16.6M  100 16.6M    0     0  1675k      0  0:00:10  0:00:10 --:--:-- 3013k
hdiutil: attach: missing image argument
Usage:	hdiutil attach [options] <image>
	hdiutil attach -help
Syncing /QOwnNotes.app to applications folder
building file list ... 
rsync: link_stat "/QOwnNotes.app" failed: No such file or directory (2)
0 files to consider

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-42/rsync/main.c(992) [sender=2.6.9]
hdiutil: detach: no device name specified
Usage:	hdiutil detach [options] <devname>
	hdiutil detach -help
Removing temporary files...
rm: /QOwnNotes.dmg: No such file or directory
usage: rmdir [-p] directory ...
usage: rmdir [-p] directory ...
Starting QOwnNotes...
Removing temporary script...
logout

[Process completed]`

**Comment by pbek** [comment]
It seems some commands work differently on 10.9. Unfortunately I have no means to test it on 10.9.
If you want to play around with it and try to make it also work with 10.9 you should find the script <https://github.com/pbek/QOwnNotes/blob/develop/src/scripts/macos/update.command> in your QOwnNotes.app.

**Comment by corvid123** [comment]
Thank you. I did wonder if it was a difference between Mavericks and Sierra. I understand resolving a quirk on an older version of the os is not a priority. I will take a look at the script, but the manual update is no big deal for the time being.

**Comment by pbek** [comment]
Ok. ;) 
I will close this issue until there is more information.
