### ISSUE TITLE
Exponential duplicated "customNoteFileExtensionList" setting

### ISSUE THREAD

**Issue by Lioric** [pbek/QOwnNotes#483]
Every time the "General" panel of the settings is selected (if a custom file extension has been added previously to the file extension list) it seem the custom file extensions are loaded from the config file and added to the panel list without checking if they have been already loaded (in memory?), resulting in duplicated entries that grows exponentialy (hundreds after just a few times)

Tested with latest 17.01.6

**Comment by pbek** [comment]
Thank you for reporting, I will take a look at that.

**Comment by pbek** [comment]
I guess that might be a regression from the settings dialog optimizations...

**Comment by pbek** [comment]
## 17.01.7
- fixed a problem with duplicate custom note file extensions in the general settings
    - the same extension now also can't be added twice

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
