### ISSUE TITLE
question: how to manually save?

### ISSUE THREAD

**Issue by damko** [pbek/QOwnNotes#484]
Is there a way to disable the automatic saving and do it using a shortcut?

**Comment by pbek** [comment]
No, sorry. It's not meant to work that way... :)

**Comment by pbek** [comment]
I maybe could add a shortcut to trigger saving all edited notes. You could then increase the auto-save-interval. Would that be of help, @damko?

**Comment by pbek** [comment]
If not, I might do it for @Crendgrim.

**Comment by pbek** [comment]
## 17.01.10
- you can now save modified notes also manually with the shortcut <kbd>Ctrl</kbd> + <kbd>S</kbd>

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
