### ISSUE TITLE
No option to turn off confirmation dialog boxes

### ISSUE THREAD

**Issue by Karig-zz** [pbek/QOwnNotes#485]
I'm using QOwnNotes 17.01.7 on Linux.

Whenever I add a tag to multiple notes (not through the "Add tag" button for adding a tag to the current note, but by selecting two or more notes, right-clicking, and selecting "Tag selected notes with"), I have to click "OK" on a confirmation dialog:

`Tag selected notes:`
`Tag 1 selected notes with [tag name]?`
`[--Tag--] [--Cancel--]`

If I have a lot of notes to add tags to, this gets annoying after a while.

(Removing a note also triggers a request for confirmation.)

Would you consider adding a "Confirmations" page to the "Options" dialog box with a checkbox for "Ask for confirmation when tagging notes" (and maybe one for "Ask for confirmation when removing notes")?

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by SuryaLuna** [comment]
Hello,
I fully agree with Karig-zz :+1:

**Comment by pbek** [comment]
## 17.12.0
- there is now a checkbox `Don't ask again!` for most confirmation message 
  boxes and a checkbox `Don't show again!` for most information message boxes
  to override the answer for all future prompts of that message boxes
    - the message boxes will not be shown again until you reset the override
    - you can reset all overrides in the *General settings*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
