### ISSUE TITLE
New lines in Nextcloud

### ISSUE THREAD

**Issue by jkalousek** [pbek/QOwnNotes#487]
When I crate new note in NextCloud I can see it exactly same in MyOwnNotes on Android and in QOwnNotes. But as soon as I edit this note or create it in first place in QON, in NC web interfrace it adds line breaks.
So for example:
```
test
test

test
```
Will become:
```
test

test


test

```

It seams that somewhere in the process it adds maybe windows line breaks? Which are not accepted in NextCloud Notes. I assume this because when I open the txt in windows notepad it looks like:
`testtesttest`

But as soon as I edit it with QON it will become in notepad
```
test
test

test
```

I hope I explain it clearly enough. (editing in Android App doesn't cause any problems and line breaks stay same no mater what)

**Comment by pbek** [comment]
What NC "web interface" did you use to edit the note in the web?
QON just uses the `\n` character and removes the `\r` character from windows to make the note files compatible on all operating systems and for oC Notes.

```cpp
text.replace(QRegExp("(\\r\\n)|(\\n\\r)|\\r|\\n"), "\n");
```

Maybe it's something your oC / NC sync tool adds?

**Comment by pbek** [comment]
Did you already use a "hex-editor" to check how your note files actually look like?

**Comment by jkalousek** [comment]
Note created in NC "Notes app" (https://github.com/nextcloud/notes - that's what I mean by web interface)
has in place of new lines \n (x0a)
Notes save by QON has \r\n (x0dx0a)
According to PSPad in Hex mode.

My version of QON is 17.01.7

**Comment by jkalousek** [comment]
Ok Step by step once again.
New note in NC Notes app (Web):
```
test
test

test
```
HEX:
![note_nc](https://cloud.githubusercontent.com/assets/8996764/22174217/35d28f8a-dfd9-11e6-9a76-3a434674ae9a.PNG)

Open the note in QON and adding one line "test" so note is looking like:
```
test
test

test
test
```
Closing QON, result in HEX:
![note_qon](https://cloud.githubusercontent.com/assets/8996764/22174226/71d29566-dfd9-11e6-8a1f-932d18921676.PNG)

**Comment by pbek** [comment]
So NC Notes doesn't get along with Windows Line Feeds?
What happens when you create a note with Windows Notepad?

I just found out that QON currently uses Windows Line Feeds under Windows when storing a note, despite that they are removed by the regular expression... If I'm going to change that I have to create a setting for it...

**Comment by jkalousek** [comment]
When I use Windows notepad for creating a note its same story again, it creates both \r\n so there are additional lines in NC.

**Comment by pbek** [comment]
I'll see what I can do.

**Comment by jkalousek** [comment]
Maybe it's also question to NC guys, rendering \r\n as two separate line breakers doesn't seem to be standard.

**Comment by pbek** [comment]
## 17.01.8
- you can now set that notes are stored with UNIX newline characters instead 
  of the native newline characters in the *General settings*
    - you can use this for example under Windows if you have troubles with 
      newlines in the ownCloud / Nextcloud notes app

There now is a new release, could you please test it and report if the new features work for you?

**Comment by jkalousek** [comment]
Seem to work perfectly, thank you!

**Comment by pbek** [comment]
Great, thank you for testing!
