### ISSUE TITLE
Images and headers in markdown cause preview to be off

### ISSUE THREAD

**Issue by szotsaki** [pbek/QOwnNotes#488]
1.) Open a new note and insert a really long text there (from e.g. lipsum.com)
2.) Insert some h1 headers randomly in the text
3.) Insert a picture somewhere at the end of the text five or six times below each other
4.) Scroll down both in the editor and the preview
5.) Hit an Enter several times for new lines, start typing (while hitting Enters) and notice how the preview is off compared to the editor

**Comment by pbek** [comment]
I'm sorry, the scrollbars are synced by percentage of positions and not by content (since I've found no way to do this). Since images take almost no space in markdown the absolute position can be off in the preview...

**Comment by szotsaki** [comment]
Hmm, that's unfortunate. Just after inserting three smaller pictures in a note and still in the 10th line of the editor, the preview pane always jumps back to the very top as soon as I start typing.

**Comment by pbek** [comment]
I'm all open for pull requests...

**Comment by szotsaki** [comment]
Some extra info for the archive:

[StackEdit](https://stackedit.io/editor) is an online markdown editor which more or less correctly handles images. In its [scrollSync.js](https://stackedit.io/res/extensions/scrollSync.js) I see they build a list of sections and with the help of that they try to synchronise the preview pane with the editor.

**Comment by pbek** [comment]
Thank you for the info, but currently QOwnNotes doesn't use a fully fledged browser for the preview...

**Comment by szotsaki** [comment]
Yes, I know; I just wrote it because of the idea (which is language-independent :) ) how they achieved that.

**Comment by mahibi** [comment]
Any news on this? Unfortunately this problem keeps me away from using qownnotes. I remember that Atom-Editor had some Plugins that tried to achieve this. I know Atom is js, but maybe there are some useable ideas..

**Comment by pbek** [comment]
No news and no fully fledged browser for still the same reasons...
