### ISSUE TITLE
Automatically encode images with base64

### ISSUE THREAD

**Issue by korteke** [pbek/QOwnNotes#491]
Hi,
(Feature request) 

Is it possible to add base64 encoding to images when exporting to HTML.

Use case: Usually I make notes with QOwnNotes, but sometimes I have to export them to the Atlassian Confluence. In Confluence I use HTML macro so notes without images works just fine, but when there is images on the notes I have to manually upload those to the Conflu.

So one more export option "Export note as HTML with encoding" or something like that.

**Comment by pbek** [comment]
Exporting them base64 encoded makes sense, thank you for your suggestion.
Can Confluence handle div containers with base64 encoded images as CSS-style?

**Comment by pbek** [comment]
Or are we talking about real img tags, like

```
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAADSCAMAAABThmYtAAAAXVB">
```

**Comment by pbek** [comment]
I even consider making this the new export, without a new menu entry...

**Comment by korteke** [comment]
It seems that it can handle both.
```
<style>
div.imgtest {
        background:  url(data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7)
    	no-repeat
    	left center;
  	padding: 0px  5px 20px;
}
</style>

</head><body>
<div class="imgtest">
Test test
</div>
</body></html>
```
and

```
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAADSCAMAAABThmYtAAAAXVB">
```

**Comment by pbek** [comment]
thank you

**Comment by pbek** [comment]
## 17.01.9
- when exporting a note as html the images are now base64 encoded and included
  inside the html

There now is a new release, could you please test it and report if the new features work for you?

**Comment by korteke** [comment]
That was quick :) I will test it after the Travis has compiled version for Mac OS X.

**Comment by pbek** [comment]
Travis for OS X is slow today... ;)

**Comment by pbek** [comment]
Did it work?

**Comment by korteke** [comment]
I think that I already commented on this, but apparently not. But yes, it worked :)

There is issues with Confluence if the picture is very large, because I tested one image which had almost 300k character on one string when it was decoded to base64. Conflu was Little bit sluggish :)

**Comment by pbek** [comment]
Thank you for testing!
