### ISSUE TITLE
Mobile version needed

### ISSUE THREAD

**Issue by Czester0** [pbek/QOwnNotes#492]
qownnote program is very good but also need a good program for mobile devices.

I tested Notes and MyOwnNotes and it can not be used. No tags, no search, no pin to start the program. In the Notes is very easy to accidentally delete a memo by slide - is unacceptable.

Maybe someone has an idea ...

**Comment by pbek** [comment]
I heared there are people that are using Neutrinote.

**Comment by Czester0** [comment]
OK. Reading the description looks better but I can not check. I have an android 4.1 :( and it requires 4.4

**Comment by Maboroshy** [comment]
I think [Epsilon Notes](https://play.google.com/store/apps/details?id=com.ekartoyev.enotes&hl=en) is the best for Android now. No QOwnNotes tagging of course, but on par with the features, even beyond par with some.

**Comment by pbek** [comment]
I will close this issue until there is more information.

**Comment by pbek** [comment]
There now is an Android App: https://www.qownnotes.org/getting-started/qownnotes-android.html.
