### ISSUE TITLE
QOwnNotes crashes

### ISSUE THREAD

**Issue by Matze78** [pbek/QOwnNotes#494]
I have this document:

http://pastebin.com/ixKRGCZf

When I continue writing this document, QOownNotes crashes:

> QOwnNotes.exe funktioniert nicht mehr. Das Programm wird aufgrund eines Problems nicht richtig ausgeführt. Das Programm wird geschlossen und Sie werden benachrichtigt, wenn eine Lösung verfügbar ist.

 Maybe it has something to do with the size of the document. It crashes with the Windows and the Linux version.

To reproduce the crash, you can copy and paste the same sentence multiple times ( ca. 50 - 100 times).

It crashes, when QOwnNotes saves the file to disk:

Log Panel:

> [status] 1 Notiz auf Datenträger gespeichert

**Comment by pbek** [comment]
Thank you for reporting.
I could reproduce your issue, but the crash seems to occur in the regular expression implementation of Qt or the operating system itself, so I'm not sure I can do anything about it...

**Comment by Matze78** [comment]
Thank you for your answer. 

So I hope this problem does not occur in my other text notes as well.
Is there a chance to see, what exactly triggers the crash in my text?

Btw, I really like QOwnNotes. It has all the features, I need for collecting and managing my notes.

**Comment by pbek** [comment]
Thank you for your kind words.

> Is there a chance to see, what exactly triggers the crash in my text?

I'm sorry, I don't know... There are just some references to a pcre c-file, over and over again...

**Comment by pbek** [comment]
If you find out, please let me know!

**Comment by Matze78** [comment]
There must be a problem with the hyper links when the text ist longer.

When I delete (!) this link:

`[selbsterfüllende Prophezeihung](https://de.wikipedia.org/wiki/Selbsterf%C3%BCllende_Prophezeiung): `

QOwnNote crashes.

When I want to change this link: 

`http://www.buch.de/shop/home/artikeldetails/k_ein_gespuer_fuer_zahlen/barbara_oakley/EAN9783864157806/ID42769884.html`

to

`[http://www.buch.de/shop/home/artikeldetails/k_ein_gespuer_fuer_zahlen/barbara_oakley/EAN9783864157806/ID42769884.html]`

 QOwnNote crashes.

Then I tried the following: 

I generated a longer text, with 10.000 words. http://www.loremipsum.de/ and copied it 
to a new file.

When I write something like `[www.test.de](test)` QOwnNote crashes.

**Comment by pbek** [comment]
Hm, maybe a regular expression is running wild... Thank you for your observation.

**Comment by pbek** [comment]
I found the regular expression that causes this and I rewrote it.

**Comment by pbek** [comment]
## 17.01.10
- fixed a crash that can happen with long notes with malformed urls

**Comment by stavpup** [comment]
This is a crash on two windows machines, maybe irrelevant

(http://pastebin.com/jnbw2YL1)

The note test is 86.546 works, 640.164 characters.

**Comment by pbek** [comment]
Lets wait for 17.01.10...

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by stavpup** [comment]
Working ok on Ubuntu, tomorrow I will test on windows. Now I am going to try React OS if that's ok !

**Comment by pbek** [comment]
Great, thank you for testing! Let me know if anything is amiss...

**Comment by stavpup** [comment]
QOwnNotes work on React OS too. That is cool. Although there are a lot of issues related to React OS of course...

**Comment by pbek** [comment]
Nice, good to know. I never tested it on React OS. ;)

**Comment by stavpup** [comment]
Here it is..
https://ibin.co/3A97weB8eKOq.jpg

**Comment by pbek** [comment]
So it even works with Wine... :)

**Comment by stavpup** [comment]
I forgot about Wine, although ReactOs uses Wine libraries, I will try it in Wine too.
I noticed that the ubuntu binary has QT 5.6.1 and windows binary has QT 5.7.1. So maybe when something is working on Ubuntu, it may break in Windows..
17.01.10 is working ok on windows too..

**Comment by Matze78** [comment]
Yes, it works perfectly. Thank you for your fast fix and great work.

**Comment by pbek** [comment]
Great, thank you for testing!
