### ISSUE TITLE
Filter by multiple tags

### ISSUE THREAD

**Issue by ricardoseriani** [pbek/QOwnNotes#496]
Hi

Please, there is any way that I can filter by 2 or more tags, for example, supose that I have the following tags:
* project
* todo
* ideas

And I have the following notes with tags applied:
* Redesign (Project)
* Log all queries (Project, Todo)
* Change database (Project, Idea)

What I wanna is to filter like this:
* tag:project
  * "Redesign"
  * "Log all queries"
  * "Change database"
* tag:project,todo
  * "Log all queries"
* tag:project,idea
  * "Change database"

Thanks in advance

**Comment by pbek** [comment]
There is an open feature request for that at #327.

**Comment by SuryaLuna** [comment]
:+1:  !!! PLEASE implement this :-)
I have the hope, that I found with QOwnNotes a software which fits my need almost completely, it's great!- but without this feature, the software would be useless for me...
Thanks a lot in advance :-)
