### ISSUE TITLE
Moving notes to a subfolder gives warning that it was removed outside of this application

### ISSUE THREAD

**Issue by smsm1** [pbek/QOwnNotes#498]
On Mac OS X

NextCloud sync setup

Steps the reproduce:
* Create subfolder
* Select note in Note folder
* Move note into subfolder and confirm move
* Get the following warning even so you've just confirmed the action: "Current note was removed outside of this application!"

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue.

**Comment by pbek** [comment]
## 17.01.11
- fixed a warning that might trigger when notes are moved to an other note subfolder

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by smsm1** [comment]
This problem is still occurring on 17.01.11 on my Mac.

**Comment by pbek** [comment]
I guess we need even more macOS workarounds... Which version of macOS do you use?

**Comment by smsm1** [comment]
I'm on 10.12.4 (beta) on this machine. I could try on my other mac which has a slightly older version of the OS.

**Comment by pbek** [comment]
## 17.01.12
- added more fixes for a warning that might trigger when notes are moved to an 
  other note subfolder in macOS

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by smsm1** [comment]
Tested, and it's now working. Thanks for the quick fix.

**Comment by pbek** [comment]
Great, thank you for testing!
