### ISSUE TITLE
Scripting: Add downloadUrlToMedia()?

### ISSUE THREAD

**Issue by pirogoeth** [pbek/QOwnNotes#499]
Similar to [ScriptingService::downloadUrlToString](https://github.com/pbek/QOwnNotes/blob/develop/src/services/scriptingservice.cpp#L684), but instead, download the file to the media folder and return the URL. Would this be possible?

EDIT: Sorry, wrote this quickly - want to add some clarification. 
The big use case I see is, for example, generating LaTeX-formatted images from the selected text. This is actually really easy as you can `GET http://latex.codecogs.com/gif.latex?\frac{1}{1+sin(x)}` which will return an image. It would then be trivial to download that image and store it to the media directory and replace the currently selected text with an inline image tag.

**Comment by pbek** [comment]
Sounds like a nice idea.

**Comment by pbek** [comment]
Phew, took a few hours...

## 17.01.12
- there now is a new script function `script.downloadUrlToMedia("http://image.url");`
  to allow you to download an url to the media folder and return the media url
  or the markdown image text
    - there is an example at [paste-latex-image.qml](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/paste-latex-image.qml)
    - for more information please take a look at the [scripting documentation](http://docs.qownnotes.org/en/develop/scripting/README.html#downloading-an-url-to-the-media-folder)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pirogoeth** [comment]
Oh dang, that was quick! Thanks @pbek! I've tested it out and it works very well. Much appreciated! :)

I'm absolutely loving QOwnNotes so far - thank you for your work on this wonderful software :)

**Comment by pbek** [comment]
Thank you for your help and thanks a lot for your donation! :smile:

**Comment by debapratimsaha** [comment]
The image is getting stored with `.latex` extension and nothing shows up in the note. I can't even open the `.latex` file in any image viewer.

May be it is due to the url String parsing done in `Note::downloadUrlToMedia`, which splits based on '.' and the last dot for say 'http://latex.codecogs.com/gif.latex?\frac{1}{1+cos(x)}' is '.latex'. Can we fix this so that it exports an image in say .gif or .png?

**Comment by pbek** [comment]
There are countless extensions beside gif and png... 
Usually the operating system should detect the mime type of a file regardless of its extension.
Which operating system are you using?
Which mime type does your downloaded file have? (under linux there is the `mimetype` command to check this)

**Comment by debapratimsaha** [comment]
I'm on Windows 8. Looks like the downloaded file is empty. I have a cygwin shell, I found the `mimetype` to be `inode/x-empty`.

I'm doing the following:
1. Copy the formula to clipboard, say `\frac{1}{1+cos(x)}`
2. Scripting > Custom Actions > Paste Latex Image
3. A blank little white page shows up in the note.

**Comment by pbek** [comment]
Does downloading of other images work in a script?

**Comment by pbek** [comment]
I just tried what you did under Windows and the image got downloaded and added to the note as `![media-CR5684](file://media/18979.latex)` and worked in the preview.

**Comment by debapratimsaha** [comment]
For me the file is downloaded as empty and nothing shows in the preview (obviously). 

I'm not familiar with any other script to download other URL images. To add the script to the interface, all I did was to point to the `paste-latex-image.qml` file (from the git doc example):
* Settings > Scripting > paste-latex-image.qml

**Comment by pbek** [comment]
Can you please post the output from the debug settings.
And is there any useful log output if you enable the log widget?

**Comment by debapratimsaha** [comment]
>[Feb 22 02:28:51] [scripting]: loading script file: G:/<blah-blah>/QOwnNotes/scripts/paste-latex-image.qml
[Feb 22 02:29:01] [status]: Stored 1 note(s) to disk
[Feb 22 02:29:21] [status]: Stored 1 note(s) to disk
[Feb 22 02:29:34] [warning]: libpng warning: iCCP: known incorrect sRGB profile
[Feb 22 02:29:34] [warning]: libpng warning: iCCP: known incorrect sRGB profile

**Comment by pbek** [comment]
nothing interesting...

Can you please post the output from the debug settings.

**Comment by debapratimsaha** [comment]
I'm attaching the Debug Information. Not sure if this helps.

[QOwnNotes Debug Information.pdf](https://github.com/pbek/QOwnNotes/files/795127/QOwnNotes.Debug.Information.pdf)

**Comment by pbek** [comment]
I can't see anything that is out of place... Can you open <http://latex.codecogs.com/gif.latex?\frac{1}{1+cos(x)}> in a browser?
Does the script work if you modify it to download an other image from the internet?

**Comment by debapratimsaha** [comment]
> Can you open http://latex.codecogs.com/gif.latex?\frac{1}{1+cos(x)} in a browser?

Yes, it shows a pic with the formula.

> Does the script work if you modify it to download an other image from the internet?

I tried this by changing the URL in the qml file (and commenting out the var for latex formula), what I found was the image that was downloaded was that of the URL instead of the actual image pointed to by the URL.

**Comment by pbek** [comment]
> what I found was the image that was downloaded was that of the URL instead of the actual image pointed to by the URL.

can you please explain that a bit more :)

**Comment by debapratimsaha** [comment]
>can you please explain that a bit more :) 

Sorry about the confusion, please ignore that. I missed the quotations around the image URL, hence was getting only the URL text as image. Now it seems to work. So back to your earlier question:

>Does the script work if you modify it to download an other image from the internet? 

Yes. It works. The script can download an image from a URL and include it.

**Comment by pbek** [comment]
I'm sorry, I've no idea why your Windows system doesn't download the Latex image and mine does. :/
