### ISSUE TITLE
Insertion point moves on autosave

### ISSUE THREAD

**Issue by oygevalt** [pbek/QOwnNotes#500]
I create a note, leave it, come back and start working on it again. When the note autosaves, the insertion point goes back to the end of the text that was there the last time I left the note, right in the middle of me typing.
Mac OS X 10.9.5 -- QOwnNotes standalone (no ownServer), v17.01.10

**Comment by pbek** [comment]
Thank you for reporting.
Can you please post the output from the debug settings and the output from the log panel.
I couldn't reproduce this under macOS 10.12...

**Comment by oygevalt** [comment]
Log:
[00:34:08] [status] Stored current note to disk
[00:34:22] [status] Stored 2 note(s) to disk
[00:34:23] [status] Notes directory was modified externally
[00:34:23] [status] Stored 1 note(s) to disk
[00:34:52] [status] Stored 1 note(s) to disk
[00:34:53] [status] Notes directory was modified externally
[00:35:22] [status] Stored 1 note(s) to disk
[00:35:23] [status] Notes directory was modified externally
[00:35:23] [status] Stored 1 note(s) to disk

I opened the log and created a new note.  Typing was fine for the first autosave at 34:23. Between 34:23 and 35:22 I went to another note, then came back to the new note and started typing away. At 35:23 the insertion point went to the end of the text when I previously left the note, and my typing continued from that point.

The only thing different that I can tell is that I changed the default folder (localpath) to something under “Documents”.

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fri Jan 27 00:42:54 2017`
**Version**: `17.01.10`
**Build date**: `Jan 25 2017`
**Build number**: `2739`
**Platform**: `macosx`
**Operating System**: `OS X Mavericks (10.9)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.5.1`
**Qt Version (runtime)**: `5.5.1`
**Portable mode**: `no`
**Settings path / key**: `/Users/&&&&&/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/&&&&&/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `10`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yesnoapp/product-typeproduct-typeothermacapp/platformplatformGeneral/notesPathnotesPathTravis CI--snapSnapcraft--port`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/Users/&&&&&/Documents/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/Users/&&&&&/Documents/Notes/notes.sqlite`

## Settings

**AboutDialog/geometry**: `<binary data>`
**Country**: `US`
**Debug/fakeOldVersionNumber**: `false`
**Debug/fileLogging**: `false`
**Editor/CurrentSchemaKey**: `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing**: `true`
**Editor/autoBracketRemoval**: `true`
**LastUpdateCheck**: `2017-01-27T00:28:47`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `32`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `Monaco,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `Lucida Grande,14,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `Monaco,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `.Lucida Grande UI,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl**: `false`
**NoteDiffDialog/geometry**: `<binary data>`
**PiwikClientId**: `<hidden>`
**SGTRecentFileSearches**: *empty*
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**ShowSystemTray**: `false`
**SortingModeAlphabetically**: `false`
**WebAutomaticSpellingCorrectionEnabled**: `false`
**WelcomeDialog/geometry**: `<binary data>`
**acceptAllExternalModifications**: `false`
**allowDifferentNoteFileName**: `false`
**allowOnlyOneAppInstance**: `false`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `false`
**appMetrics/notificationShown**: `true`
**com/omnigroup/OmniOutlinerPro3:3:2**: `<binary data>`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**currentWorkspace**: `a4988ac7-886f-4a89-8330-4a0b1b0c512b`
**customNoteFileExtensionList**: *empty*
**darkMode**: `false`
**darkModeColors**: `false`
**darkModeTrayIcon**: `false`
**defaultNoteFileExtension**: `txt`
**demoNotesCreated**: `true`
**disableAutomaticUpdateDialog**: `false`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: *empty*
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**imageScaleDown**: `false`
**imageScaleDownMaximumHeight**: `1024`
**imageScaleDownMaximumWidth**: `1024`
**insertTimeFormat**: *empty*
**interfaceLanguage**: *empty*
**internalIconTheme**: `false`
**itemHeight**: `18`
**markdownHighlightingEnabled**: `true`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `2`
**noteSaveIntervalTime**: `30`
**notesPath**: `/Users/&&&&&/Documents/Notes`
**notifyAllExternalModifications**: `false`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: *empty*
**ownCloud/todoCalendarBackend**: `3`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloud/userName**: *empty*
**previousWorkspace**: `9d11f6c7-cdba-4a1e-bbad-833a8131f2cd`
**savedSearches/noteFolder-1**: `Note 2017-01-27T00.34.08, Note 2017-01-27T00.29.02, Note 2017-01-26T16.40.48, Note 2017-01-26T15.01.04, Note 2017-01-26T14.07.49, Note 2017-01-26T14.01.56, Note 2017-01-26T13.50.08`
**showMenuBar**: `false`
**showStatusBar**: `true`
**toolbar/1/items**: `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name**: `mainToolBar`
**toolbar/1/title**: `main toolbar`
**toolbar/2/items**: `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name**: `formattingToolbar`
**toolbar/2/title**: `formatting toolbar`
**toolbar/3/items**: `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name**: `insertingToolbar`
**toolbar/3/title**: `inserting toolbar`
**toolbar/4/items**: `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name**: `encryptionToolbar`
**toolbar/4/title**: `encryption toolbar`
**toolbar/5/items**: `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name**: `windowToolbar`
**toolbar/5/title**: `window toolbar`
**toolbar/6/items**: `action_Quit`
**toolbar/6/name**: `quitToolbar`
**toolbar/6/title**: `quit toolbar`
**toolbar/size**: `6`
**useUNIXNewline**: `false`
**workspace-9d11f6c7-cdba-4a1e-bbad-833a8131f2cd/name**: `full`
**workspace-9d11f6c7-cdba-4a1e-bbad-833a8131f2cd/noteSubFolderDockWidgetVisible**: `true`
**workspace-9d11f6c7-cdba-4a1e-bbad-833a8131f2cd/windowState**: `<binary data>`
**workspace-a4988ac7-886f-4a89-8330-4a0b1b0c512b/name**: `minimal`
**workspace-a4988ac7-886f-4a89-8330-4a0b1b0c512b/noteSubFolderDockWidgetVisible**: `true`
**workspace-a4988ac7-886f-4a89-8330-4a0b1b0c512b/windowState**: `<binary data>`
**workspaces**: `9d11f6c7-cdba-4a1e-bbad-833a8131f2cd, a4988ac7-886f-4a89-8330-4a0b1b0c512b`

## System environment

**PATH**: `/usr/bin:/bin:/usr/sbin:/sbin`
**TMPDIR**: `/var/folders/8n/n3sk7bnn25b1z7742nry62z40000gn/T/`
**SHELL**: `/bin/bash`
**HOME**: `/Users/&&&&&`
**USER**: `&&&&&`
**LOGNAME**: `&&&&&`
**SSH_AUTH_SOCK**: `/tmp/launch-3Yub2B/Listeners`
**Apple_PubSub_Socket_Render**: `/tmp/launch-z6sABi/Render`
**DISPLAY**: `/tmp/launch-mM0akb/org.macosforge.xquartz:0`
**__CHECKFIX1436934**: `1`
**__CF_USER_TEXT_ENCODING**: `0x1F5:0:0`
**QT_LOGGING_RULES**: `qt.network.ssl.warning=false`

**Comment by oygevalt** [comment]
I reset the app (clear app data and exit) and started it again with all the defaults, including "ownCloud/Notes/" in my user root folder. Same crazy thing. Including the "Notes directory modified externally" message.

**Comment by pbek** [comment]
I still can't reproduce this effect on my Mac... :/

**Comment by oygevalt** [comment]
Weird. The only thing I can think of is that one of the changes mentioned for 17.01.10 is "when opening notes the cursor position inside the note will now be restored to the position when the note was last visited in the current session". To my naive eyes, this seems to be related to the issue I'm experiencing. When the autosave takes place, it seems to think it's revisiting the note at a time before any new editing took place.

**Comment by pbek** [comment]
macOS always handles things a bit "differently", especially older versions... Unfortunately I don't have an old version of macOS to test with... Maybe I just create a setting.

**Comment by oygevalt** [comment]
I'm going to delete all files and try a reinstall. Maybe it's because I started with the app in a subfolder of the Applications folder. I'll let you know tomorrow if there's any change. Thanks for your attention!

**Comment by pbek** [comment]
## 17.01.11
- you now can disable the restoring of the cursor position in the *General settings*

**Comment by oygevalt** [comment]
I reproduced it on another machine running 10.11. (Haven't upgraded to Sierra yet.) I was able to stop the behavior by checking the "Ignore all external modifications of current note" and "Ignore all external note folder changes" boxes in General Preferences. It probably is something "different" with the macOS not worth digging into. It's a workaround, but the issue seems to be resolved. Thanks again for your attention!

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by oygevalt** [comment]
That did the trick. Thank you very much!

**Comment by pbek** [comment]
thank you for testing!

**Comment by shaununderwood** [comment]
Excellent! I was about to raise that as an issue.

**Comment by pbek** [comment]
it's now turned off by default for macOS too...
