### ISSUE TITLE
Insert image feature broke

### ISSUE THREAD

**Issue by szotsaki** [pbek/QOwnNotes#501]
With the latest release when I try to insert an image (Ctrl+Shift+I), only its link (like `media://0210123.png`) gets inserted not the entire reference (like `![test](media://0210123.png)`).

**Comment by pbek** [comment]
Thank you for reporting, might be a regression from #499.

**Comment by pbek** [comment]
## 17.01.13
- fixed the image link that is inserted when using the *Insert image* menu entry

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by szotsaki** [comment]
Thank you, it works!

**Comment by pbek** [comment]
Thank you for testing!
