### ISSUE TITLE
Image insertion dialogue doesn't remember previous directory

### ISSUE THREAD

**Issue by szotsaki** [pbek/QOwnNotes#502]
Ctrl+Shift+I dialogue (and perhaps the others as well) should remember the last used directory.

**Comment by pbek** [comment]
Thank you for your suggestion, currently none of the file dialogs remember the last chosen directory.

**Comment by pbek** [comment]
## 17.01.13
- the directory of the previously selected file will now be remembered for a lot of file dialogs
    - the last directory of each dialog will be remembered separately
    - if no directory was set the last directory path of any dialog will be used
    - if there still is no readable path the home directory will be chosen

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by szotsaki** [comment]
Thank you, it works!

**Comment by pbek** [comment]
Thank you for testing!
