### ISSUE TITLE
Reverse sort order

### ISSUE THREAD

**Issue by dtougas** [pbek/QOwnNotes#504]
It would be really nice to be able to have a way to reverse the sort order of notes. I like to sort my notes by name, but when I do that, the notes I want easy access to always end up at the bottom of the list. Being able to reverse that would be a great feature.

**Comment by pbek** [comment]
>  I like to sort my notes by name, but when I do that, the notes I want easy access to always end up at the bottom of the list.

Can you please explain in more detail and step by step what you did, what happened and what you expected.

**Comment by dtougas** [comment]
This is not a bug, but a feature request.

What I do is go to **Notes -> Sort -> Alphabetical** to change the sort order. This works perfectly.

What I would like to be able to do is have a way to reverse the sort order.

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by Maboroshy** [comment]
As sorting came up, I can't keep myself from "bumping" #369.

**Comment by pbek** [comment]
#369 would be quite some work...

Sorting notes by name, desc is doable.
Sorting notes by date, asc would be a lot of work.

**Comment by pbek** [comment]
## 17.02.0
- you now can sort or notes also alphabetically descending

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by dtougas** [comment]
I am not seeing the MacOS version of the release yet, but will be happy to check it out when it is available.

**Comment by pbek** [comment]
Travis CI has/had troubles with the macOS build system...

**Comment by dtougas** [comment]
Just installed the latest build. The name sort ascending/descending works perfectly, thank you very much!

**Comment by pbek** [comment]
Today I finally made it run with Qt 5.8, I will create an official release later...
Thank you for testing!

**Comment by dtougas** [comment]
Excellent, I look forward to trying it out. Thank you very much for your hard work!

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by dtougas** [comment]
Downloaded and tested. Yes, the latest build works good too.

**Comment by pbek** [comment]
Great, thank you for testing!
