### ISSUE TITLE
Tables rendered without borders

### ISSUE THREAD

**Issue by BlackRavener** [pbek/QOwnNotes#507]
Preview pane renders tables without any borders and without any padding between table cells. This makes tables very difficult to read. A quick fix would probably be enforcing borders on all tables by default and adding one space padding between columns.

A more advanced solution would be allowing users to pre-configure in settings how to render tables. I suggest below parameters:
1. Make header text bold or not
2. Header text color
3. Header background color
4. Table text color
5. Padding between cells (or rather content of a cell and a cell wall)
6. Enable / disable cell borders (i.e. whether to render borders or not). Optionally, set border style, such as single line, thick line, dotted line, double line, etc.

**Comment by pbek** [comment]
Thank you for your suggestion. If you want to play around with that, please see: #457

**Comment by pbek** [comment]
Please let me know if you manage to create a better styling. I might add your CSS code to QOwnNotes.
