### ISSUE TITLE
todo, calendar settings etc

### ISSUE THREAD

**Issue by stavpup** [pbek/QOwnNotes#508]
I don't know if this is a bug, feature, enhancement or question etc.  
Usually when we think about a todo (list), it is a list like that
https://www.danielbranch.com/wp-content/uploads/2012/03/todo_list_template_jpg11.jpg
to make a shopping list or important stuff to remember. I don't know if a todo list can be
implemented in Qownnotes.

On the other hand Qownnotes has a todo feature which is "todo" inside a calender like a CalDav server.
It is more or less things to do during the week, or month etc but usually we call that a schedule or a calendar.
To call that "todo" maybe acurate but means less that a calendar or schedule..

**Comment by pbek** [comment]
The "todo list" feature of QOwnNotes consists of accessing Todo-items (that's the caldav name) on a caldav server. Does that answer your question? :)
