### ISSUE TITLE
Inserting an image twice next to each other doesn't work

### ISSUE THREAD

**Issue by szotsaki** [pbek/QOwnNotes#509]
1. Insert an image into a new line
2. Insert a new image next to the previous one

The second image will be just a small "image-not-found" style placeholder. If you press Enter between them, that will fix it.

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue. But it might be a problem with <https://github.com/hoedown/hoedown>.

**Comment by pbek** [comment]
I was able to fix it myself...

## 17.02.1
- fixed the preview of images if there are more than one in the same line

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by szotsaki** [comment]
Thank you for the fix, it works!

**Comment by pbek** [comment]
Great, thank you for testing!
