### ISSUE TITLE
list points indented in 6th iteration just disapear in render view

### ISSUE THREAD

**Issue by motey** [pbek/QOwnNotes#511]
QOwnNotes Notepad Version version 17.02.1 - AppVeyor - build 2787 @ Windows 10
**How to reproduce:**
make a list with 8 bulletpoints and make every following point a child of previous point by tab indent (* \t -> tab)
```
* 1
\t* 2
\t\t* 3
\t\t\t* 4
\t\t\t\t* 5
\t\t\t\t\t* 6
\t\t\t\t\t\t* 7
\t\t\t\t\t\t\t* 8
```

Expected Result in render view:
```
• 1 
    • 2 
        • 3 
            • 4 
                • 5 
                    • 6 
                        • 7 
                            • 8 
```
Actual result:
```
• 1 
    • 2 
        • 3 
             • 4 
                 • 5 
```

**Comment by pbek** [comment]
Thank you for reporting, please see: #473
