### ISSUE TITLE
Export to CSV via custom script

### ISSUE THREAD

**Issue by Florentin68** [pbek/QOwnNotes#512]
I would like to export lines matched in a note by specific regex to a CSV file via custom script (QML). I'm new to QML but I've read I can write in a file via QtQuick.
When I add `import QtQuick 2.3` (or 2.0) at the beginning of my QML file, QON tells me the module is not installed.
Can you help me please?

**Comment by pbek** [comment]
I don't know if QtQuick can do that, by are you bothering to do that in QML? It surely would be easier to write a shell script (or python or ruby script) and (if you need to) call that from QON in a custom action...

**Comment by pbek** [comment]
example: <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/custom-actions.qml>

**Comment by Florentin68** [comment]
Thank you, you're right it will be much easier!
