### ISSUE TITLE
Avoid illegal characters in file name on Windows

### ISSUE THREAD

**Issue by praxiq** [pbek/QOwnNotes#513]
QOwnNotes automatically renames the file on disk to the title at the top of the note. This can cause a problem if the title contains illegal characters. To reproduce on Windows:

1. Create a new note.
2. Put whatever content you want into the note.
3. Add a question mark in the note's title.

At this point, the note is deleted from the disk completely, and all content in it is lost - definitely not the expected behavior!

Illegal characters should be stripped from the title when naming the text file. 

Solution #1: Characters illegal on any (common) platform could be stripped on *all* platforms, so that syncing is straightforward. Easiest to implement, least confusing, and not a major limitation for anyone. This would be my preference.

Solution #2: Only characters illegal on the given platform can be stripped. People who only use Linux won't be held back by Windows file name restrictions. If they try to sync a file with illegal characters to a Windows machine, that might cause problems - but that's not QOwnNotes' fault, as QOwnNotes doesn't handle syncing anyway.

Solution #3: Illegal characters can be encoded in some way, like in URLs, making the file name less readable but ensuring that the note name within the QOwnNotes app (which comes from the decoded file name) matches the note title exactly

**Comment by pbek** [comment]
The main problem (beside that ownCloud also doesn't allow certain characters) is that that's not mainly a platform problem, but a file system problem. And since QON doesn't know the file system it can't do much about it...

**Comment by praxiq** [comment]
Hmm...

Well to start with, if saving a file fails, it'd be good to catch the error and report it to the user, giving the user a chance to change their title, rather than to fail silently and lose the note.

Even after that, it would still be nice to filter illegal characters from file names. Just because certain characters are invalid in a file name on my file system doesn't mean I shouldn't be allowed to use it in the title inside the note itself. I would like to be able to to title a note "Filesystem research: which characters are valid?" and have it safely save to disk, perhaps as "Filesystem research which characters are valid.txt"

You can handle *most* issues on *most* filesystems very simply: just remove the following characters from filenames: `/ ? < > \ : * | " ^`

You might also consider removing leading and trailing spaces (not illegal, but probably not desirable), and cutting off filenames after, say, 200 characters (QOwnNotes running portably off of a flash drive might be on a FAT filesystem with path length limitations).

**Comment by pbek** [comment]
Note saving is none-interactive and I'm not sure if there even is a proper error... Plus it also possible tools like ownCloud sync are simply removing files they can't handle externally.

Finding a common denominator might be hard, since FAT has a lot more restrictions than most of the other file systems...

Although removing some more characters in `Note::cleanupFileName` is no problem.

**Comment by pbek** [comment]
The question is how much it will annoy users of file systems where your character excluding suggestion works and now have their note filenames changed, which will make troubles when they are linking to these files in other programs or server software...

**Comment by praxiq** [comment]
True... Maybe you could assume Windows users are on NTFS (banning the characters mentioned above), Mac OS users are on HFS (Banning only the `:`), and rename accordingly? This will be true most of the time, and on the rare occasions it's false won't cause much of a problem for most users.

Or you could do this: if saving the file fails, try to limit the file name according to the rules above, and if it fails again, then report the error to the user - the failure must be caused by something else.

**Comment by pbek** [comment]
We cannot assume anything. Windows users might use NTFS, FAT or FAT32 (e.g. for USB sticks in portable mode) or they mount a file share... The same goes for Linux and macOS.
We would need different rules for every common file system, make it selectable per note folder and someone would first need to research the allowed (or disallowed) characters for each file system.

I guess we would need NTFS, FAT16, FAT32, HFS+, ext4, reiserfs, XFS and btrfs... (did I miss something?)
Do you volunteer for the research, @praxiq? :smile_cat:

**Comment by praxiq** [comment]
I think the easiest solution that assumes nothing is simply: if the save fails, strip *all* characters that are illegal on *any* common filesystem and try again.

**Comment by pbek** [comment]
So what characters are illegal on any common filesystem?

**Comment by praxiq** [comment]
Strip non-printable characters; leading and trailing spaces; and these: `/ \ | < > ? * % : " ^`

That covers NTFS. HFS+, the FAT filesystems, and all posix-compatible filesystems only ban a subset of those, so that should cover everything. (posix-compatible filesystems, i.e. most of the ones you'll find on linux, only ban forward slash and null characters.)

I assume you're not interested in supporting old systems that require 8.3 filenames :)
