### ISSUE TITLE
Inserted closing bracket should absorb itself as input

### ISSUE THREAD

**Issue by polarathene** [pbek/QOwnNotes#514]
I had a look at [this issue](https://github.com/pbek/QOwnNotes/issues/386)/feature and understand it is opt-out. I don't mind it and sometimes it's nice to have, but what annoys me is when I type out links `[text](link)` the insertion can sometimes be unhelpful.

- `[` -> `[ ]`
- `[test]` - now you either have to adjust cursor breaking typing flow or accept the redundant closing bracket as it is not removed when you type your own to keep typing flow causing `[test]()]`
- At this point I normally paste the link in with **ctrl+v**, I have to delete that extra bracket from before which also requires adjusting my cursor. 
- I would need to do this at the end regardless to continue typing more text after the link as typing `)` would have the same problem :)

Perhaps I should just disable the feature, just thought I would mention this scenario as it does not seem intuitive or beneficial to anyone to not fix? Pressing the closing bracket key when the closing bracket is the character to the right of the cursor should either move the cursor forward one character or delete/insert the same character(whichever method works :) ).

**Comment by pbek** [comment]
I don't think I grasp what exactly you are struggling with. :)
I would type `[`, then I would write / paste the description, then type `(` and write / paste the url. Done.

**Comment by polarathene** [comment]
> I would type [, then I would write / paste the description, then type ( and write / paste the url. Done.

`[` -> `[]` -> `[test]` -> `[test(]` -> `[test()]` -> `[test(link)]`

This is what you described would happen when you type what you said with auto bracket. If you want to avoid that you need to either press right arrow key, click after the `]` or press `]` and then press delete key before or after you type the `(link)`. You need to then do the same if you want to keep typing more text after the link.

**Comment by pbek** [comment]
Sorry, I forgot to tell you I used `End` after writing the description...
But I still don't see your point. If you don't like that bracket-thing you can always turn it off...

**Comment by polarathene** [comment]
I like it, just a little annoying when typing a link. In other editors I've used they've worked as I described, typing the closing bracket basically moves the cursor forward a character instead of inserting another closing bracket. Reaching for end or arrow key breaks typing flow.

It's fine if you do not feel it's worth supporting :) Just wanted to mention it as it was bothering me personally this past week typing links, felt like a bug to me.

**Comment by pbek** [comment]
> typing the closing bracket basically moves the cursor forward a character instead of inserting another closing bracket

Haha, now I finally understand what you are talking about :)
Why didn't use just write that one sentence instead of everything else? :D

I will evaluate how hard that would be to implement...

**Comment by pbek** [comment]
## 17.02.3
- the bracket closing feature now also just moves the cursor to the right if a
  closing bracket is typed at the position of a closing bracket if there is a
  matching opening bracket
    - this works for `)`, `]` and `}`

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by polarathene** [comment]
Works perfectly 👍 

Thanks for such a quick update :)

**Comment by pbek** [comment]
Great, thank you for testing!
