### ISSUE TITLE
Only one instance of QOwnNotes

### ISSUE THREAD

**Issue by jkalousek** [pbek/QOwnNotes#515]
Is there way that you could prevent of running multiple instances of QON on Windows?

Because I have configured app so that when I close it it goes to System tray, but then when I launch it again from desktop, it launches another separate instance. It would be better if there could be only one instance running in any given time and if you try to launch it again it will just reuse already launched instance.

I notice this because I edited note in one instance and than I quickly launched another instance and edited same note and then suddenly note disappeared which I assume was caused by some conflict between two instances (I didn't manage to reproduce this behavior again but unless there is very specific reason that you want to be able to launch multiple instances, default should be only one - in my opinion).

**Comment by jkalousek** [comment]
Sorry i didn't notice there already is this option in settings. I think that it should be ticked by default...

**Comment by pbek** [comment]
Mutex locking can cause problems, so it's not on by default.
