### ISSUE TITLE
App hangs up after resume

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#517]
After some update, QOwnNotes or my linux system, the app started to hang up after system resume. Tray icon is there, and it would produce a context menu after about a 30 seconds after right-click, but that's it. No left-click reaction.

Sometimes dead app is burning one CPU core at 100%. 

Most times app can't be restated after process killing until system restart. It needs further investigation, maybe it's related to the signal I send to kill it.

Debug log get 2-3 `[warning]: QObject::disconnect: Unexpected null parameter` before hang up. Also it once got right after `QObject::disconnect`:
``` 
[warning]: onResult  - 'reply error':  QNetworkReply::NetworkError(UnknownNetworkError)
[debug]: QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once QUrl("https://p.qownnotes.org/piwik.php?idsite=5&_id=92642a3d99b9fc29&cid=92642a3d99b9fc29&url=http://QOwnNotes/&rec=1&apiv=1&res=1600x900&ua=Mozilla/5.0 (Manjaro Linux, x86_64; ru-ru) PiwikTracker/0.1 (Qt/5.7.1 )&lang=ru-ru&dimension3=0&dimension2=ru_RU&dimension1=17.01.14&dimension7=Manjaro Linux (x86_64)&dimension9=AUR&ping=1")
```
Also my log is full of `[debug]: "Unexpected reply signature: got \"\", expected \"a{sv}\""`, don't know if it's related.

I also made some Qt updates on my system about the time all this started, so it can be some Qt regression. Maybe it's related to me switching to Wi-fi on my machine, I used wired LAN before.

How can I debug it further to outline the code causing hang ups?

**Comment by pbek** [comment]
Doesn't ring any bell... Haven't changed anything network related for a long time. Maybe a Qt 5.8 thing in combination with the network resume? I've still Qt 5.7.1 on Manjaro... Which Qt version do you use now?

**Comment by Maboroshy** [comment]
Same Qt 5.7.1 on Manjaro Stable. 

Network problems are weird, because I don't use anything "network" in the app. And I don't see any KDE apps suffer from this.

Some deep debugging tricks?

**Comment by pbek** [comment]
Maybe KDE has some detection of network changes that normal Qt doesn't have...
Does QON get stuck every time you resume?
But of course it could also be something unrelated to networking...
So far nothing comes to mind. :/

**Comment by Maboroshy** [comment]
Not every time, about 1 of 2 or 1 of 3.
Stuck is one problem, but I'm mostly unable to restart the app after killing it's process. 
Bad thing the app doesn't give any feedback to cli whatsoever, so I don't really know why it's not starting.

I'll instigate network thing in a while, I hope getting back wired connection at the weekend at see if the  problem is gone. But, as I've said, I don't use app's network-related features, only sending usage data. I use btsync and mounted nfs directories without any issues.

Will turning usage data off make the app "immune" to my system's network capabilities? Or it will still try making something out of Qt network?

**Comment by pbek** [comment]
> Will turning usage data off make the app "immune" to my system's network capabilities? Or it will still try making something out of Qt network?

Only update checks once an hour are left...
I'm using my Manjaro Laptop also with only Wifi. No troubles there...

**Comment by Maboroshy** [comment]
My Manjaro is custom built. For example I use Connman instead of default Network manager.

Tried disabling usage data send. Suspended yesterday with the app running, it's wasn't running on resume, nothing special in log.

I'll make some more testing with wired connection. Maybe try to learn some Qt debugging. I'll reopen this bug if I find anything useful.
