### ISSUE TITLE
long link does not appear in note preview

### ISSUE THREAD

**Issue by stavpup** [pbek/QOwnNotes#518]
This long link

https://earthquake.usgs.gov/earthquakes/map/#{"autoUpdate"%3A["autoUpdate"]%2C"basemap"%3A"terrain"%2C"feed"%3A"30day_m25"%2C"listFormat"%3A"default"%2C"mapposition"%3A[[41.4509614012039%2C12.0794677734375]%2C[43.78299262890581%2C14.859008789062502]]%2C"overlays"%3A["plates"]%2C"restrictListToMap"%3A["restrictListToMap"]%2C"search"%3Anull%2C"sort"%3A"newest"%2C"timezone"%3A"utc"%2C"viewModes"%3A["list"%2C"map"%2C"settings"]%2C"event"%3Anull}

If I add  <>, the link disappears from the note preview

<https://earthquake.usgs.gov/earthquakes/map/#{"autoUpdate"%3A["autoUpdate"]%2C"basemap"%3A"terrain"%2C"feed"%3A"30day_m25"%2C"listFormat"%3A"default"%2C"mapposition"%3A[[41.4509614012039%2C12.0794677734375]%2C[43.78299262890581%2C14.859008789062502]]%2C"overlays"%3A["plates"]%2C"restrictListToMap"%3A["restrictListToMap"]%2C"search"%3Anull%2C"sort"%3A"newest"%2C"timezone"%3A"utc"%2C"viewModes"%3A["list"%2C"map"%2C"settings"]%2C"event"%3Anull}>

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue.

**Comment by pbek** [comment]
It seems that <https://github.com/hoedown/hoedown> treats strings with `<something"something>` as html tags. It would be best if you escape your `"` as `%22` when using them in `<>` links.
Links like `[Latest Earthquakes](https://earthquake.usgs.gov/earthquakes/map/#{"autoUpdate"%3A["autoUpdate"]%2C"basemap"%3A"terrain"%2C"feed"%3A"30day_m25"%2C"listFormat"%3A"default"%2C"mapposition"%3A[[41.4509614012039%2C12.0794677734375]%2C[43.78299262890581%2C14.859008789062502]]%2C"overlays"%3A["plates"]%2C"restrictListToMap"%3A["restrictListToMap"]%2C"search"%3Anull%2C"sort"%3A"newest"%2C"timezone"%3A"utc"%2C"viewModes"%3A["list"%2C"map"%2C"settings"]%2C"event"%3Anull})` are working too...
