### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by Olhur** [pbek/QOwnNotes#52]
Hi there!
Since I am an active user of your app, I would love to contribute, at first by making Polish translation ;) So please prepare a file to be edited. Thanks!

Best regards,
Filip

**Comment by pbek** [comment]
You make my day! Here you go: <https://github.com/pbek/QOwnNotes/blob/develop/src/languages/QOwnNotes_pl.ts>

Cheers, Patrizio

**Comment by pbek** [comment]
Here I wrote some lines about translating QOwnNotes: <http://www.qownnotes.org/Knowledge-base/How-can-I-help-to-translate-QOwnNotes>

**Comment by Olhur** [comment]
Question regarding style: when I cannot put a shortcut letter in the menu entry (ie. Quit translates to "Wyjście" in Polish, no way to make Q a shortcut this way), what is preferred? "Wyjście [Q]"? "Wyjście [q]"? Or just skipping it?

**Comment by pbek** [comment]
Thank you for reminding me!
- please just set obvious key bindings like `Ctrl + Q` to translated and don't translate them
- you can set the `&` handlers as you like in `&Quit`

**Comment by pbek** [comment]
Thanks a lot for your contribution. :tada: Please feel free to maintain and update your translation with further pull requests!
