### ISSUE TITLE
Text replacement is not considered as regexp

### ISSUE THREAD

**Issue by szotsaki** [pbek/QOwnNotes#521]
1. Write some text into the editor field which contains `AA_BB`
2. Open Find & Replace dialogue and select regular expression matching
3. Replace `_` to new line (`\n`).

`_` will be replaced to the literal `\n`, not a new line.

**Comment by pbek** [comment]
Yes, the replacement string is escaped. The regular expression is just for searching.

**Comment by pbek** [comment]
And it seems you cannot even to that with <http://doc.qt.io/qt-5/qstring.html#replace-11>, I'm sorry.
