### ISSUE TITLE
Data loss while switching between notes during header refresh

### ISSUE THREAD

**Issue by szotsaki** [pbek/QOwnNotes#522]
Preconditions: 
* Have two longer markdown texts with `=======`-style headers on the top. 
* Headers must totally differ from each other and 
* the content should be easily distinguishable.

1. Copy the first text into a new note
2. Wait until the note name (in the list on the left side) gets refreshed with the header name
3. Paste the second text into a new note
4. Now, quickly, append some random string to the `=====` header and before the note's name gets refreshed, switch to the first note. Try switching back, modify headers and switch again. Try also Alt+Tabbing.

The result: when note-switching occurs during note-name refresh, for some reason, the second note fully gets replaced by the first one, resulting in data loss. Interestingly, the second note's header will also be the same as the first one's but with the current dateTtime appended.

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue.

**Comment by pbek** [comment]
Currently I'm not able to reproduce this again (a lot changes were made in the app meanwhile). Are you still able to reproduce it, @szotsaki?

**Comment by szotsaki** [comment]
Unfortunately, I still can reproduce it relatively easily mostly as described in the very first comment.

How to reproduce easier:
- Have two, really big notes with a lot of text and many pictures (40+) inside.
- Create a copy from both of them on the file system and let their filenames be the same just prepend "ALTERNATIVE_" to them
- Quickly iterate between the alternatives back-and-forth with mouse in the note search panel. You'll notice a tiny lag in the application until a note is fully loaded.
- Now, just start typing random gibberish very quickly into the active note while continuing the switching between them.

After a bit of time, you'll see that the notes got a new name and a new content.

OS: I'm using QOwnNotes on Linux.

**Comment by pbek** [comment]
Thank you for testing!

**Comment by photonxp** [comment]
Here is how I could reproduce this problem:

#### STEP 1:
Create 3 notes. 
The first two notes are default new note:
-    "Note 2018-01-03T20.30.20"
-    "Note 2018-01-03T21.07.30"

The third note is a large note:
-    "largenote..2018-01-03T21.16.45"

#### STEP 2:
Then change the title/name section of the third note (large note). 
Meanwhile switch between the first two notes with cursor to change current item. Do this step early enough before the third note (large note) is stored into the disk.

Now the third note is quite likely to be replaced by one of the first two default notes. Also a new time-stamp would be appended.

I'm kind of curious about what would happen if two or more notes were edited at the same time? Would they be updated by queue or concurrently?

#### Relevant log output (from STEP 2):
[Jan 03 21:21:58] [debug]: currentItemChanged  Note: <id>399 <name>"Note 2018-01-03T21.07.30" <fileName>"Note 2018-01-03T21.07.30.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false
[Jan 03 21:21:58] [debug]:  added to history:  NoteHistoryItem: <noteName>"Note 2018-01-03T21.07.30" <noteSubFolderPathData>"" <cursorPosition>4 <relativeScrollBarPosition>0
[Jan 03 21:21:59] [debug]: currentItemChanged  Note: <id>2 <name>"Note 2018-01-03T20.30.20" <fileName>"Note 2018-01-03T20.30.20.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false
[Jan 03 21:21:59] [debug]:  added to history:  NoteHistoryItem: <noteName>"Note 2018-01-03T20.30.20" <noteSubFolderPathData>"" <cursorPosition>4 <relativeScrollBarPosition>0
[Jan 03 21:22:00] [debug]: handleNoteTextFileName  - 'name' was changed:  "largenote.. werer 2018-01-03T21.16.45"
[Jan 03 21:22:00] [debug]: storing note file:  "largenote.. werer 2018-01-03T21.16.45.md"
[Jan 03 21:22:00] [info]: "Renamed note-file was removed: /home/test/data_mnt/opt_user/wonCloud/Notes/largenote.. 2018-01-03T21.16.45.md"
[Jan 03 21:22:00] [debug]: stored note:  Note: <id>400 <name>"largenote.. werer 2018-01-03T21.16.45" <fileName>"largenote.. werer 2018-01-03T21.16.45.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false
[Jan 03 21:22:00] [debug]: storeUpdatedNotesToDisk  - 'count':  1
[Jan 03 21:22:00] [status]: Stored 1 note(s) to disk
[Jan 03 21:22:01] [debug]: reloadTagTree
[Jan 03 21:22:01] [debug]: currentItemChanged  Note: <id>399 <name>"Note 2018-01-03T21.07.30" <fileName>"Note 2018-01-03T21.07.30.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false
[Jan 03 21:22:01] [debug]:  added to history:  NoteHistoryItem: <noteName>"largenote.. werer 2018-01-03T21.16.45" <noteSubFolderPathData>"" <cursorPosition>4 <relativeScrollBarPosition>0
[Jan 03 21:22:01] [debug]:  added to history:  NoteHistoryItem: <noteName>"Note 2018-01-03T21.07.30" <noteSubFolderPathData>"" <cursorPosition>4 <relativeScrollBarPosition>0
[Jan 03 21:22:05] [debug]: currentItemChanged  Note: <id>400 <name>"largenote.. werer 2018-01-03T21.16.45" <fileName>"largenote.. werer 2018-01-03T21.16.45.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>true
[Jan 03 21:22:05] [debug]:  added to history:  NoteHistoryItem: <noteName>"largenote.. werer 2018-01-03T21.16.45" <noteSubFolderPathData>"" <cursorPosition>4 <relativeScrollBarPosition>0
**[Jan 03 21:22:10] [debug]: handleNoteTextFileName  - 'name' was changed:  "Note 2018-01-03T20.30.20"
[Jan 03 21:22:10] [debug]: storing note file:  "Note 2018-01-03T20.30.20 2018-01-03T21_22_10.md"
[Jan 03 21:22:10] [info]: "Renamed note-file was removed: /home/test/data_mnt/opt_user/wonCloud/Notes/largenote.. werer 2018-01-03T21.16.45.md"**
[Jan 03 21:22:10] [debug]: stored note:  Note: <id>400 <name>"Note 2018-01-03T20.30.20 2018-01-03T21_22_10" <fileName>"Note 2018-01-03T20.30.20 2018-01-03T21_22_10.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false
[Jan 03 21:22:10] [debug]: storeUpdatedNotesToDisk  - 'count':  1
[Jan 03 21:22:10] [status]: Stored 1 note(s) to disk
[Jan 03 21:22:11] [debug]: reloadTagTree

**Comment by pbek** [comment]
I was playing around a lot in `MainWindow::storeUpdatedNotesToDisk`, but so far I can't get a grip on that issue (it's not even easy to trigger it).

**Comment by pbek** [comment]
I'll add a debug output when `MainWindow::loadNoteDirectoryList` is called to see if that maybe is also related in release 18.01.1.

**Comment by pbek** [comment]
Most interesting also is that `Note 2018-01-03T20.30.20` wasn't even the last note you clicked, @photonxp. I got the same behavior after trying a while...

**Comment by photonxp** [comment]
Yeah, that does.

Although I'm not sure what could be the cause of this problem and also I have little knowledge about cpp or QT, according to:
1. What I can understand in and out of QOwnNotes/src/widgets/navigationwidget.cpp
2. Discussions on stackoverflow about qt-asynchronous-display-with-asynchronous-qfilesystemmodel[link: https://stackoverflow.com/questions/25321060/qt-asynchronous-display-with-asynchronous-qfilesystemmodel] 

I think at least some of the following new features might be required:
1. A multi-thread model that allows updateing/querying db in a thread or switching between different treads. This way a user could move on to the next note before operations on the current note is completed.
2. A thread pool model that allows a maximum thread number by default and reuse of threads, along with other needed functions. This way a user could return to previous note even if there're unfinished operations on the previous note.
3. A reload button that allows users to manually reload the current note. This is only needed if there are concerns that other threads or objects might be working on current note.
4. A notification to tell users that [The current note is outdated. Use reload button to refresh.] or [There are unfinished operations on the current note]. This way a user could better understand the feature 3.

Either of the features could be some stuff to work on, so right now I'll just shorten the [note save interval time] and wait for the note to finish its storing to the disk.

**Comment by pbek** [comment]
@photonxp, thank you for your investigation, but the `NavigationWidget` isn't involved at all, it's just for jumping around inside the current note. The event didn't trigger for me.

**Comment by pbek** [comment]
it seem `this->currentNote` will not even be set, I hoped that was the problem

**Comment by pbek** [comment]
## 19.2.2
- fixed lost note after changing its title and switching to another note
  (for [#522](https://github.com/pbek/QOwnNotes/issues/522) and
  [#1142](https://github.com/pbek/QOwnNotes/issues/1142), a big thank you to @liulex)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
