### ISSUE TITLE
Display two notes next to each other?

### ISSUE THREAD

**Issue by michael-rowe** [pbek/QOwnNotes#523]
Hi Patrizio

Is there any way to display two different notes next to each other? I often work between 2-3 sets of notes, moving content between them for my writing. Is there currently a way to do that, and if not, would it be difficult to implement?

Thanks again for the work you do.

Keep well,
Michael

**Comment by pbek** [comment]
If it's just for viewing you can right click on the note in the note list: *Open note in a view*
Other than that you could open a 2nd instance of QON, but often that's not a very good idea...
Or open the note in a text editor (also via QON).

**Comment by michael-rowe** [comment]
OK, great. That should work. I'm usually copying from one note into another, so Open in a view works. Thanks.
