### ISSUE TITLE
Issues with fetchNoteByFileName scripting function

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#524]
I'm still on a rampage to make in-app script to "pin" or "star" notes as in #351. 
I've made one but stuck in the very end with `fetchNoteByFileName` scripting functions.
It puts `TypeError: Property 'fetchNoteByFileName' of object ScriptingService(0xf8c650) is not a function` to log and dies. And I don't think I use it any different than in examples. Most stuff I found in the net about this error is about invocation of QML functions from C++, which is way above my head. 

Here is the script, I can't get last two lines to work:
```qml
import QtQml 2.0
import com.qownnotes.noteapi 1.0

/*
 * This script implements custom action buttons to prepend current note name with a special (or any other) 
 * unicode symbols so the note will be "pinned" on top of the list with "alphabetical sorting" on.
 * You can use different symbols, one at a time, to "pin" notes. 
 * That allows to make kind of hierarchy of pinned notes.
 * 
 * Notes can be "unpinned" by using same symbol second time.
 * 
 * This script should be used with "Allow note file name to be different from headline", 
 * "Accept all external modification of current note", "Sort by -> Alphabetical" options on.
 * 
 * Some unicode symbols can be unavailable in font set used in your systems.
 */

QtObject {
    
    /// Put different symbols to prepend note name here, as much of them as you like.
    property var symbol:["★", "❗", "⚑", "✔"]
        
    /// Each symbol will get own button to add it to selected note name.
    function init() {
        for (var n = 0; n < symbol.length; n++) {
        script.registerCustomAction(n, "Mark note with " + symbol[n], symbol[n])
        }
    }
    
    /// Each symbol uses single algorithm to prepend note name with it.
    function customActionInvoked(n) {
        
        /// Get note data
        var note = script.currentNote()
        var fullFileName = note.fullNoteFilePath
        var fileName = note.fileName
        var filePath = fullFileName.replace(fileName,"")
        
        /* Delete symbol if note is "pinned" by it.
         * Or prepend "unpinned" note with that symbol. 
         * Or "repin" note with the new symbol. */
        if (fileName.substring(0,2) == symbol[n] + " ") {
           var newFileName = fileName.substring(2) 
        } 
        else if (symbol.indexOf(fileName.substring(0,1)) != -1 && fileName.substring(1,2) == " ") {
            var newFileName = symbol[n] + " " + fileName.substring(2)
        }
        else {
            var newFileName = symbol[n] + " " + fileName
        }
        
        /* Since QOwnNotes doesn't allow to delete notes with scripting yet, 
         * rename the note file by a system's native command with a new "prepended" name. 
         * Use different commands for Windows and POSIX systems. */
        var arguments = [fullFileName,filePath + newFileName]
        
        if (script.platformIsWindows()) {
            var moveCommand = "move"
        } else {
            var moveCommand = "mv"
        }
        
        script.log("Note " + fileName + " marked with " + symbol[n])
        script.startDetachedProcess(moveCommand, arguments)
        
        /// Set "pinned" note as current.
        var pinnedNote = script.fetchNoteByFileName(newFileName)
        script.setCurrentNote(pinnedNote)
    }
}
```

**Comment by pbek** [comment]
What's the content of `newFileName` in your test? On which platform did you run the script?

**Comment by Maboroshy** [comment]
For now I've tested the script only on GNU/Linux.

```
fileName = note.fileName
newFileName = symbol[n] + " " + fileName
```
So `newFileName` is the name of renamed note without path, like `! test.md`.

I've put `var pinnedNote = script.fetchNoteByFileName("123.md")` instead of 
`var pinnedNote = script.fetchNoteByFileName(newFileName)` with no avail.

**Comment by pbek** [comment]
What happens if you use `var pinnedNote = script.fetchNoteByFileName("123.md", -1)`?

**Comment by Maboroshy** [comment]
Same error: `TypeError: Property 'fetchNoteByFileName' of object ScriptingService(0x18aa500) is not a function`

**Comment by pbek** [comment]
I just tried your script and it works wonderful under KDE Neon. It adds the nifty characters in front of the filename. Well done!

**Comment by pbek** [comment]
**Operating System**: `KDE neon User Edition 5.9`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Self-build`
**Qt Version (build)**: `5.7.1`
**Qt Version (runtime)**: `5.7.1`

**Comment by Maboroshy** [comment]
The renaming part works, but it should also make renamed note current one. And that I cannot do without fetching for it.

**Comment by pbek** [comment]
I don't get any error messages under KDE Neon and macOS, but the script doesn't seem to do anything on macOS.

**Comment by Maboroshy** [comment]
Does current note changes to renamed one in KDE Neon? I mean not the deleted one stuck in render, but a renamed note selected in the note list.
Looks like macOS didn't like the my trick with renaming note files by `mv` shell command as `startDetachedProcess`. I thought it would work, since UNIXes also use `mv` command.
I could work around it if there'd be `deleteNote` scripting function. I could delete old note and create a new renamed one with same text without external processes.

**Comment by pbek** [comment]
Under KDE Neon the note gets renamed but I get the message box that the current note got removed.

**Comment by Maboroshy** [comment]
That's normal. You've implemented "accept all changes" option to deal with that, and comment in my script says it'd better be on. 

`startDetachedProcess` move command trick also doesn't work in Windows. I'll try to work it out. 

I got out why I had this error and it's quite dumb - I used the early app version of the app where `fetchNoteByFileName` wasn't implemented yet. :astonished: 

Sorry for time wasted.

**Comment by pbek** [comment]
>  I used the early app version of the app where fetchNoteByFileName wasn't implemented yet. 

priceless! :rofl:

**Comment by pbek** [comment]
But feel free to make a pull request with the script to <https://github.com/pbek/QOwnNotes/tree/develop/doc/scripting> if you want to showcase it.

**Comment by Maboroshy** [comment]
I never stop to amaze myself. :dizzy_face:
I'll pull it in when I'll work all the bugs out.
And I'm already thinking about making a reminder script, so expect some scripting function request. :sunglasses: Nothing big though.
