### ISSUE TITLE
Unable to connect to Nextcloud 11.0.1

### ISSUE THREAD

**Issue by vve1505** [pbek/QOwnNotes#525]
Receive the following message:

`Connection error message: Error downloading https://nextcloud/remote.php/webdav/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/Notes/ - server replied: Internal Server Error`

I have downloaded and enabled the qownNotesapi app in NC 11.0.1

**Comment by pbek** [comment]
Are you sure you entered the correct url to your Nextcloud server?
Can you please post the output from the debug settings.

**Comment by vve1505** [comment]
Here's the output. I'm using the correct url - all my other apps reference this same url.
[QOwnNotes Debug Information.txt](https://github.com/pbek/QOwnNotes/files/794041/QOwnNotes.Debug.Information.txt)

**Comment by pbek** [comment]
Which apps are that? Apps that are using WebDAV? Can you please try to remove "/remote.php/webdav" from the URL. And if that doesn't help also remove the index.php part.

**Comment by vve1505** [comment]
That was it. Sorry about that - I thought I had to use the full webdav URL.
It's working now.

**Comment by pbek** [comment]
Great it works now... ;)
