### ISSUE TITLE
Icons in dark mode too dark

### ISSUE THREAD

**Issue by dh-connect** [pbek/QOwnNotes#531]
I set up the dark mode on my mac, the only thing that I don't like about it is that you can hardly see the icons, can you somehow change the color of the icons ? I couldn't find a setting for that.

Thank you

![grafik](https://cloud.githubusercontent.com/assets/10463926/23534980/799e2dc6-ff89-11e6-958d-7741ad09d08e.png)

**Comment by pbek** [comment]
Thank you for reporting, this is a known (and already reported Qt problem). see #436
