### ISSUE TITLE
Open last used note

### ISSUE THREAD

**Issue by szotsaki** [pbek/QOwnNotes#532]
When I re-open QOwnNotes I'd like to continue from where I stopped last time. Therefore, it would be good to have the ability to

- open the last used note (if it still exists) and then
- jump to the cursor position of the last time.

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
It was a lot more work than I thought, but now it works...

## 17.03.3
- after starting QOwnNotes now the last note along with your cursor and 
  scrollbar position will be restored
    - if that fails the first note in the note list will be opened

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by szotsaki** [comment]
Thank you, it works!

**Comment by pbek** [comment]
Great, thank you for testing!
