### ISSUE TITLE
Converting a page 4 times to HTML kills performance

### ISSUE THREAD

**Issue by szotsaki** [pbek/QOwnNotes#537]
1. Have a long markdown page with full of images. When you try to edit it, you notice that performance is laggy.
2. Create a script with the following content: 
```
import QtQml 2.0
import com.qownnotes.noteapi 1.0
import com.qownnotes.tagapi 1.0

QtObject
{
   function noteToMarkdownHtmlHook(note, html)
   {  
      console.log("HtmlConvert");
   }
}
```
3. Turn on debug view and the debug logging.
4. Insert at the and of your note a singe letter `a` and leave the cursor there (don't click anywhere for 10 seconds).
5. Notice that the `HtmlConvert` text is displayed four times.

Probably this and other, related mechanisms cause that typing is a bit painful in longer markdown documents with many images.

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your find.

**Comment by pbek** [comment]
## 17.03.2
- the generated preview html will now be cached to increase performance when 
  editing large notes

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by szotsaki** [comment]
Thank you, it works!

**Comment by pbek** [comment]
Thank you for testing!
