### ISSUE TITLE
[Feature Request] Multiple blank lines

### ISSUE THREAD

**Issue by polarathene** [pbek/QOwnNotes#542]
Would it be possible to support multiple blank lines? Perhaps this goes against the Markdown spec you use. For some documents I want to format with 2 blank lines before the next line of text, only 1 line is supported.

**Comment by pbek** [comment]
If you are talking about the preview, try to enter `<br />`.
Does that answer your question?

**Comment by polarathene** [comment]
Yes thanks that works :)

**Comment by pbek** [comment]
Great ;)

**Comment by pbek** [comment]
If you want a button fror that you can create one yourself with a custom action.
<http://docs.qownnotes.org/en/develop/scripting/README.html#registering-a-custom-action>
