### ISSUE TITLE
Having many images in a note slows down editing

### ISSUE THREAD

**Issue by szotsaki** [pbek/QOwnNotes#545]
1. Have a note with many (10-15) PNG images inside which are distributed equally within chapters.
2. Start typing at the end of the note.

You'll notice that typing is really slow, sluggish.

After I created a Callgrind log just for typing, it turned out that somehow PNG conversion is the cause of this.

Please, take a look at the attached image file gained from the callgrind log which shows that `QImage::load` causes a massive slow-down which indicates loading and decoding many image files every half second is expensive:

![qownnotes](https://cloud.githubusercontent.com/assets/4254450/23833979/a6049612-074e-11e7-93d0-c4100fcbc82c.png)

**Comment by pbek** [comment]
Thank you for reporting, but if loading the big PNGs is the problem (which is done by Qt) I'm not sure if I can improve that...

**Comment by Maboroshy** [comment]
Maybe that's not directly on subject, but you can use thumbnails instead of images.

Right now app has two modes for inserting media: full-size or fixed small-resize.
You can use mixed mode which will show small-size but store full-size as a link.

It can be implemented two ways: 
1) The transparent way - the app will insert `[![](/file://small.png)](file://full.png)` instead of just `![](file://full.png)`. It is easily scriptable, but will require some shell job I can't do on OS other than Linux.
2) The big way - the link is `![](file://full.png)` but the app renders `[![](/file://small.png)](file://full.png)` instead. And it can detect the the view pane size and render `medium`, `large` or even `full` instead of fixed `small`.

It won't solve the Qt problems but may ease big PNGs problem a bit.

**Comment by Waqar144** [comment]
@pbek
@szotsaki 

Is this still an issue?

I tried with about 50 images(png), it smooth but there's a very tiny lag(almost unnoticeable).

**Comment by pbek** [comment]
Using above 2.1MB image causes sluggishness for me while typing if I have turned the preview on.

- I didn't manage to embed an image in a link like: `[![](media/2040656525.png)](../../Downloads/a6049612-074e-11e7-93d0-c4100fcbc82c.png)`. The "small" image was shown but clicking it got me a `Malformed url` error. If there is a way to fix that we would also start to (optionally?) create smaller versions of images.
- Maybe there also is a way to just show a resized version in the preview in real-time? But that could also be slow...

**Comment by Waqar144** [comment]
> Using above 2.1MB image causes sluggishness for me while typing if I have turned the preview on.
> 
>     * I didn't manage to embed an image in a link like: `[![](media/2040656525.png)](../../Downloads/a6049612-074e-11e7-93d0-c4100fcbc82c.png)`. The "small" image was shown but clicking it got me a `Malformed url` error. If there is a way to fix that we would also start to (optionally?) create smaller versions of images.

>     * Maybe there also is a way to just show a resized version in the preview in real-time? But that could also be slow...

Image processing is really CPU hungry. Doing that every second might not be very wise I think and it probably wouldn't fix the lag.

We can run the preview in a background thread, that would fix the lag.

**Comment by pbek** [comment]
> We can run the preview in a background thread, that would fix the lag.

I already had that on my todo list, big images might be a good use case for QtConcurrency.

**Comment by pbek** [comment]
Another thing is also the preview of remote images... they will currently be downloaded every time the preview refreshes. Maybe we can cache them as long as the user stays with the current note.

**Comment by pbek** [comment]
Meanwhile at least remote images are cached for the current note, see https://github.com/pbek/QOwnNotes/issues/1244#issuecomment-581021926

**Comment by Waqar144** [comment]
The performance should be a lot better now with the new library. The performance issue with loading lots of large images

**Comment by Waqar144** [comment]
@pbek this issue is now fixed

**Comment by pbek** [comment]
Great, then I'll close this now.
