### ISSUE TITLE
Support anchors in Markdown

### ISSUE THREAD

**Issue by jd666** [pbek/QOwnNotes#547]
#### Expected     
Support for anchors as laid out in https://gist.github.com/asabaylus/3071099
```
Link to an [anchor](#this-is-an-anchor)
...

## This is an anchor
```                                                                                                                                                                

#### Actual 
Unable to detect the URI-scheme of "#this-is-an-anchor".

**Comment by jd666** [comment]
Github Flavored Markdown:
-    punctuation marks will be dropped
-    leading white spaces will be dropped
-    upper case will be converted to lower
-    spaces between letters will be converted to -
see also http://stackoverflow.com/questions/6695439/how-to-link-to-a-named-anchor-in-multimarkdown/7015050#7015050

**Comment by pbek** [comment]
Thank you for your suggestion, I would add support to the highlighter when <https://github.com/hoedown/hoedown> will support it too for the preview...
You could ask them if you want, please notify me if they do support it.

**Comment by jd666** [comment]
Requested from upstream: https://github.com/hoedown/hoedown/issues/213
