### ISSUE TITLE
Tag filter number showing wrong values

### ISSUE THREAD

**Issue by Shinryuken** [pbek/QOwnNotes#548]
Hi,

I was testing with a clean istance of QOwnNotes and noticed that the app is indicating 3 notes having the tag "stock" but i have only 2. I could send you the zipped contents if needed.

![immagine](https://cloud.githubusercontent.com/assets/26417187/23917693/8d139830-08f0-11e7-9e6e-c55630fca8c6.png)

Thanks for you very useful app.

**Comment by pbek** [comment]
Thank you for reporting, does it still show these number if you restart QOwnNotes?
Can you please post the files in your note folder.

**Comment by Shinryuken** [comment]
Yes, problem persists if i restart QOwnNotes.

Sure, i'm attaching the files. I forgot to mention that i'm using portable mode

[Notes.zip.txt](https://github.com/pbek/QOwnNotes/files/842592/Notes.zip.txt)

I'm attaching it with .txt extension file because github does not like it as zip for some reason

**Comment by pbek** [comment]
There is an empty entry that is linked to the tag in your `notes.sqlite`, I'll see what I can do about that...

**Comment by pbek** [comment]
## 17.03.6
- broken links between notes and tags are now automatically removed when the 
  tag tree is reloaded

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Shinryuken** [comment]
Hi pbek, i made some test with the new version and the problem didn't happened, moreover, the tag number now shows the correct value.

I will let you know if issue reappears.

I think that can be closed, thanks.

**Comment by pbek** [comment]
Great, thank you for testing!
