### ISSUE TITLE
Filter notes with multiple tags selected (request)

### ISSUE THREAD

**Issue by Shinryuken** [pbek/QOwnNotes#549]
Hi,

i would like to suggest, a new functionality that allows the user to restrict the tag search by selecting multiple tags. When more than a tag is selected, only the notes containing all the selected tags will be displayed (each one of them).

This could be useful when you attach several tags to new notes and you have a lot of them.

**Comment by pbek** [comment]
Thank you for your suggestion, I guess that would be #327.

**Comment by SuryaLuna** [comment]
:+1:  !!! PLEASE implement this :-)
I have the hope, that I found with QOwnNotes a software which fits my need almost completely, it's great!- but without this feature, the software would be useless for me...
Thanks a lot in advance :-)
