### ISSUE TITLE
Feature request: Let QOwnNotes support reStructruedText format (rst)

### ISSUE THREAD

**Issue by hysci** [pbek/QOwnNotes#561]
Both Markdown and reStructuredText format are support by GitLab. It is suggested to support reStructuredText format in QOwnNotes.

**Comment by hysci** [comment]
Both Markdown and reStructuredText format are support by GitLab. It is suggested to support reStructuredText format in QOwnNotes.

**Comment by pbek** [comment]
Thank you for your suggestion. I'm sorry, QOwnNotes is strongly tailored to Markdown, to change that would be a tremendous amount of work. I can't see that happen in any near future.

Of course you can write whatever text you like in your notes and even implement your own preview with the help of `pandoc` and <http://docs.qownnotes.org/en/develop/scripting/README.html#notetomarkdownhtmlhook> in a custom script.

**Comment by hysci** [comment]
What I suggest is not fully supporting rst format (i.e., let all button that is specific for md grammer fits rst grammer), but a simple text editor and rst preview. Is it possible to consider put that function in the roadmap? Thanks very much.

**Comment by pbek** [comment]
I guess that would be several 100h of work. Since the developer (me) doesn't like rst a lot and would have to write his own parser, preview, command integration, etc I don't see that coming... 😄

**Comment by pbek** [comment]
Don't forget, this is a C++ / Qt application, not a Electron web application (where there exists a library for almost everything). ;) GitLab runs in the web... 😺

**Comment by silopolis** [comment]
Hi, that was my first interrogation when I discovered your great app because as a Pythonista, I have lots of docs and notes in rst format... A little sad to learn QOwnNotes is so deeply tight to Markdown, you could have written its own documentation in QOwnNotes and would have brought a very nice and featureful alternative to ReText...
Anyway, congratulations and thanks for the great work

**Comment by pbek** [comment]
Thank you for your kind words, @silopolis!
You could turn off syntax highlighting altogether and use it just as text editor... but of course highlighting would be nice

**Comment by silopolis** [comment]
>
> You could turn off syntax highlighting altogether and use it just as text
> editor... but of course highlighting would be nice
>
Or convert my rst archive to md ! But then have to find something to
replace Sphinx...

**Comment by pbek** [comment]
https://readthedocs.org/ (that uses sphinx) can also handle markdown some way, I wonder how they did it
