### ISSUE TITLE
Feature request: Let QOwnNotes Support Seafile Server

### ISSUE THREAD

**Issue by hysci** [pbek/QOwnNotes#562]
Currently QOwnNotes only supports owncloud/nextcloud, but another powerful open source platform named Seafile is not supported. That server is widely used and located at: https://github.com/haiwen/seafile

**Comment by pbek** [comment]
Thank you for your suggestion. The reason for the ties to ownCloud / Nextcloud is the [Notes](https://apps.nextcloud.com/apps/notes) application. QOwnNotes uses notes in the way the Notes app does and has some extra functionality around it, but does no syncing itself. You need the desktop sync client for that.
You can use whatever sync service you want, also the one from Seafile.
Does that answer your question or did you have something else in mind?
