### ISSUE TITLE
Import notes from Synology Note Station (.nsx file)

### ISSUE THREAD

**Issue by ank0m** [pbek/QOwnNotes#563]
Right now I have thousands of note within my Synology Diskstation (Note Station). But as I love the lightweight way of QOwnNotes and the fast and easy sync via my selfhosted Nextcloud I want to move all my notes to QOwnNotes.

It would be amazing if there will be a way to import them.

**Comment by pbek** [comment]
The notes in QOwnNotes are just simple markdown / text files. Is there no way to export notes from Note Station?

**Comment by ank0m** [comment]
It's possible to export single notebbooks  to a .nsx file.

**Comment by pbek** [comment]
I guess that will not help a lot. :) You would need to find some software that can export all notes to textfiles...

**Comment by Maboroshy** [comment]
Maybe .nsx have some proper plain text structure inside, that can be converted by a simple script. 
Also looks like notes are stored in Sqlite3 database which can be ripped directly.
I can try to check it out to write some bash script since I have Synology Diskstation, but anything I'll come up with will only work on Linux.

**Comment by ank0m** [comment]
@Maboroshy so far that sounds very interesting. A Linux solution is OK to me as I'm using Ubuntu on my notebook.

**Comment by pbek** [comment]
@Maboroshy, awesome. You are the master of scripts! 👏  😄

**Comment by Maboroshy** [comment]
Ok then, I'll put note station on my DS and see what I can do.

**Comment by ank0m** [comment]
Woohoo, I'm so excited \o/

**Comment by Maboroshy** [comment]
These .nsx file is a zip archive with csv text files and all attached media inside.
The csv files are quite readable with note data and what looks like html content. 
Here's the test note I used, I've put line breaks for readability:
```
{"attachment":{"_poskKxdKf2Kt7SC5PHYlow":{"ext":"png",
"height":1600,
"md5":"64976bcde61bf473591a3ceccc6efd97",
"name":"checked1600.png",
"ref":"MTQ5MjcwOTAzMjE2N2NoZWNrZWQxNjAwLnBuZw==",
"rotate":true,"size":30510,
"thumb":"thumb_1024_64976bcde61bf473591a3ceccc6efd97",
"thumb_size":26861,"type":"image","width":1600}},
"brief":"1\n\t2\n\t3\n\n4\n\t5\n\t6\n\n7\n\t8\n\t9\n",
"content":"<div><img class=\"syno-notestation-image-object\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" border=\"0\" width=\"400\" ref=\"MTQ5MjcwOTAzMjE2N2NoZWNrZWQxNjAwLnBuZw==\" adjust=\"true\" /></div><div><table style=\"width: 240px; height: 90px;\"><tbody><tr><td style=\"width: 78.25px;\"><i>1</i></td><td style=\"width: 71.75px;\"><i>2</i></td><td style=\"width: 75px;\"><i>3</i></td></tr><tr><td style=\"width: 78.25px;\"><i>4</i></td><td style=\"width: 71.75px;\"><i>5</i></td><td style=\"width: 75px;\"><i>6</i></td></tr><tr><td style=\"width: 78.25px;\"><i>7</i></td><td style=\"width: 71.75px;\"><i>8</i></td><td style=\"width: 75px;\"><i>9</i></td></tr></tbody></table></div>",
"ctime":1492708999,
"encrypt":false,
"mtime":1492709123,
"parent_id":"1024_6857E64C79032C31BFA7EBCB9B6F45EBCCADA96F8183E0C156CE3585E1BEEB995AD316060926501FBE983E898DD8ABD2",
"tag":["test tag"],
"thumb":"_poskKxdKf2Kt7SC5PHYlow","title":"Note 2"}
```
I'll parse the csv and convert html content to markdown with pandoc. Keep in mind that markdown is lighter than html, so there can be some format loss in complex notes.

I think I'll be able to get:
- note name;
- assigned tags;
- text;
- inline images;
- tables converted to plain text.

I can also get note/image thumbnails, but not sure they'll be of any use.
Also I'm not yet sure what to do with note tags. I'll get to that later.

**Comment by ank0m** [comment]
Wow, thanks for your commitment.

If I only get the plain text of my notes that's content enough. The notes in my Note Station only include text and are tagged. But it doesn't hurt if I'll lose that tag informations

**Comment by Maboroshy** [comment]
[Check this](https://github.com/Maboroshy/Note-Station-to-markdown/tree/master).

**Comment by ank0m** [comment]
@Maboroshy you did an faboulus job, thank you so much.

Checked it and I'm quite happy with the result(s). A couple of notes I didn't know of contained a pic, most of them were exported correctly and two or three errors were thrown that the pic couldn't be found.

But hey, who cares.

I'm so happy that have 99.8% of my notes was exported into an .md file. Now I'm  able, without copy'n'paste, to use them within QOwnNotes.

**Comment by pbek** [comment]
Great job @Maboroshy, the script magician! :)

**Comment by Maboroshy** [comment]
I'm glad it worked.
I've had the same problem with attached images during testing. Even put it "known issues" in readme. 
In my case the attached image files had not been exported by Note Station. They had proper names and were not any different from other attachments, so I don't know why this happens. It's beyond my control, so I made informative error messages.

**Comment by Maboroshy** [comment]
I've made in-app script that was supposed to tag notes based on data stored in file name and rename the note removing that data. 

The issue is the note renamed by an in-app script losses assigned tags. Not just when I rename it a hard way by running external `mv`, but also when I use `handleNoteTextFileNameHook`.

I think I won't be able to properly pass tags from file names, unless @pbek will make renaming hook work like in-app renaming, preserving tags.

I can switch to storing tags in text instead, but I think file names are more convenient.

Here is the script:
```qml
import QtQml 2.0
import com.qownnotes.noteapi 1.0

QtObject {
    
    function noteOpenedHook(note) {
        
        var tagsList = note.fileName.match(/^\[(.*?)\].*/)
        
        if (tagsList) {
            
            var tags = tagsList[1].split(",")
            
            for (var n = 0; n < tags.length; n++) {
                script.tagCurrentNote(tags[n])    
                script.log("Note tagged with " + tags[n])
            }
            
//          var filePath = note.fullNoteFilePath.replace(note.fileName,"")
//          var newFileName = note.fileName.replace(/^\[.*?\] */,"")
            
//          var arguments = [note.fullNoteFilePath,filePath + newFileName]
//          script.startSynchronousProcess("mv", arguments, "") 
       } 
    }
    
    function handleNoteTextFileNameHook(note) {
        return note.name.replace(/^\[.*?\] */,"");
    }
}
```

**Comment by pbek** [comment]
@Maboroshy, which renaming hook do you mean?

**Comment by Maboroshy** [comment]
handleNoteTextFileNameHook

**Comment by ank0m** [comment]
@Maboroshy I changed your script, so that tags won't be written into the titles anymore because that was to much of information.

**Comment by pbek** [comment]
@Maboroshy according to `Note::storeNoteTextFileToDisk()` name changes by `handleNoteTextFileNameHook` should preserve tags.

**Comment by Maboroshy** [comment]
True. Looks like I just can't make all the hooks properly act together. 

Right now I'm trying to force `handleNoteTextFileNameHook` to run after `noteOpenedHook` tagged the note.
Tagging does not trigger it, `script.noteTextEditWrite` gives `QTextCursor::setPosition: Position '35' out of range`, and "touching" the note made the script loop.

Maybe I should go for the tag in text instead, much less headache.

**Comment by pbek** [comment]
handleNoteTextFileNameHook is called when a note (any note) is store, noteOpenedHook is called when the current note is set. the former can certainly trigger the latter...

what are you trying to achieve?

**Comment by Maboroshy** [comment]
I want to rename the note after tagging it by `noteOpenedHook`.

**Comment by Maboroshy** [comment]
Anyway I'll change the script to store tags in note text. Renaming files with in-app scripting is quite hard for now and not worth the hassle.

**Comment by pbek** [comment]
Quite hard indeed!

**Comment by Maboroshy** [comment]
I've modified the shell script and added QON script to import tags from note text. I think I'm done with this issue. 

Here is the script for QON:
```qml
import QtQml 2.0
import com.qownnotes.noteapi 1.0

QtObject {
    
    function noteOpenedHook(note) {
        
        var tagsList = note.noteText.match(/^Tags: .+/)
        
        if (tagsList) {
            
            var tags = tagsList[0].replace("Tags: ","").split(",")
            
            for (var n = 0; n < tags.length; n++) {
                script.tagCurrentNote(tags[n].trim())    
            }
            
            script.startSynchronousProcess("sed", ["-i","/^Tags: /d",note.fullNoteFilePath], "")
            script.startSynchronousProcess("sed", ["-i","/./,$!d",note.fullNoteFilePath], "")
       } 
    }
}
```

**Comment by pbek** [comment]
That looks like one amazing script!

**Comment by ank0m** [comment]
Thank you @Maboroshy you are a wizard.

**Comment by Maboroshy** [comment]
[nsx2md script](https://github.com/Maboroshy/Note-Station-to-markdown/tree/master) is now written on Python, so it can be used on Windows, Mac and Linux now.

**Comment by pbek** [comment]
@Maboroshy, you are a man of many talents!

**Comment by kleindiek** [comment]
Great work!

Any plan to include timestamps (creation date, modification date) into the markdown files?

**Comment by Maboroshy** [comment]
I've uploaded the new version. There are now options to insert time stamps, which are disabled by default. You can enable them in script's text.

**Comment by kleindiek** [comment]
Thanks for your fast reaction - works flawlessly.

How can I add YYYY-MM-DD in front of each note name?

Am 28. September 2017 um 19:28 schrieb Maboroshy <notifications@github.com>:

I've uploaded the new version. There are now options to insert time stamps, which are disabled by default. You can enable them in script's text.

**Comment by Maboroshy** [comment]
You want to add creation time or modification time?

**Comment by kleindiek** [comment]
Creation time.

**Comment by Maboroshy** [comment]
Uploaded new version with `creation_date_in_filename` option, which is disabled by default.

**Comment by thankstipscom** [comment]
I know this isn't directly related to the original post here, but I figured if you'd done a lot of the work already maybe it would help.
I'm looking for a way of running a script that to hit the sqlite db in Synology Notestation that just grabs any notes with images in month x and grabs only the image....renames it to this format

2018-02-16-<noteTitle>.png

and saves it to a folder on the nas.

Essentially.. when im out and i buy something I want an easy quick application that I can open up, put a title on and snap a photo and have it send direct to my nas. Notestation has direct connection to our phones and lets photos and titles.

I don't want to rely on Synology being around forever so I want to be able to once a month take all images from the notebook and back the raw images up in a folder i can read outside of notestation.

**Comment by Maboroshy** [comment]
What kind of help do you need? 

nsx2md script I made doesn't work with Notestation db, only with exported nsx files. So I don't have a ready working solution for your use case. The shortest way is enhance my script so it would add note creation or modification time to the name of attached files.

If you want direct access to db you'll have to start from the scratch.

**Comment by wxpiero** [comment]
have anyone tried to import a 300MB size <5.2_5966>notestation backup file into DSM6.1?failed all the time

**Comment by pbek** [comment]
Sounds like a lot of ram would be needed to do that. Maybe that's the problem.

**Comment by Maboroshy** [comment]
I wrote the script but I don't use Note Station other than for testing it. You can always switch to markdown and QOwnNotes. :wink:

**Comment by Vytautas759** [comment]
Hello Maboroshy! 

Your script looks to be salvation for me. I want to get out from Note Station as it appeared to be very limited in functionality (e. g. I cannot print several note at once, etc.). 
But when I run your script I get error message which stops it:

File "C:\xxxx\nsx2md.py", line 130, in <module>
    for attachment_id in note_data.get('attachment', ''):
TypeError: 'NoneType' object is not iterable

It's on Windows 10.

Those notebooks, which do not have pictures, are exported well.

Please help me:)

**Comment by Maboroshy** [comment]
I've just uploaded new version that should resolve the issue.

**Comment by Vytautas759** [comment]
Thank you very much! You saved me!!!
