### ISSUE TITLE
Feature request: Moving paragraph one up or down

### ISSUE THREAD

**Issue by L-R-S** [pbek/QOwnNotes#569]
Will be nice and helpful if will be possible to move paragraphs one up and down. Like in Kate (Ctrl + Shift + ↑/↓) or Libre Office (Ctrl + Alt + ↑/↓).

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by Maboroshy** [comment]
It looks like a request for a proper note text editing by scripting engine to me. ;-)

**Comment by quailiff** [comment]
![move_text_up_down](https://cloud.githubusercontent.com/assets/16974626/26664085/00d7795e-465d-11e7-9a4b-b4e506c234cf.png)

I was able to get this working at [quailiff/feature/text-manipulation](https://github.com/quailiff/QOwnNotes/tree/feature/text-manipulation) (click [here](https://github.com/pbek/QOwnNotes/compare/develop...quailiff:feature/text-manipulation) to see changes against pbek/develop). Comments:

- So far, I have only tested this on Linux (not Windows or macOS).
- I can probably combine the logic in each function into one function (maybe in Utils::Misc) that accepts the offset to move the current selection (negative to move up and positive to move down).
- I was only able to get the application to call `on_actionMove_text_up_one_line_triggered` and `on_actionMove_text_down_one_line_triggered` to work by adding two new menu items as shown above. When I removed the menu items, the shortcuts didn't work and there is no other way to trigger the functions. Maybe shortcuts can be set in the constructor? However, if there are no menu items, will it still be possible to customize the shortcuts in the Settings dialog?
- It looks like I can only use [`QTextDocument::toPlainText()`](https://doc.qt.io/qt-5/qtextdocument.html#toPlainText), which replaces "some" (whatever that means) Unicode characters with ASCII.
- **The worst problem with this approach:** Moving text blocks up and down works. However, I use [`QTextEdit::setPlainText`](https://doc.qt.io/qt-5/qtextedit.html#setPlainText) to update the text, which erases the undo history.

**Comment by pbek** [comment]
Hey, great you took on an other challenge, @quailiff!
New menu entries would be ok in that case, I guess. In the worst we can think about creating a submenu for such operations.
Hmmm, maybe you can try using the text cursor and select the text block, then removing the selected text, moving the cursor one text block above/below and insert the text again. That would surely keep the history and you don't need `toPlainText`. There should be plenty of examples of how to work with the text cursor in `mainwindow.cpp`.

**Comment by quailiff** [comment]
I actually just tried using `QTextCursor::select` and `QTextCursor::insertText` as suggested [here](http://www.qtcentre.org/threads/43268-Setting-Text-in-QPlainTextEdit-without-Clearing-Undo-Redo-History); however, while this approach keeps the "Undo" option available, invoking Undo from the context menu or via keyboard shortcut doesn't do anything except move the cursor a couple lines up.

```cpp
    // Set the new text
    c.select(QTextCursor::Document);
    c.insertText(lines.join("\n"));
```

Tomorrow, I will look for other things to try.

**Comment by pbek** [comment]
You can for example take a look at `MainWindow::insertMedia` on how I worked with cursors.

**Comment by quailiff** [comment]
As it turns out, this snippet

```cpp
    // Set the new text
    c.select(QTextCursor::Document);
    c.insertText(lines.join("\n"));
```

doesn't break Undo - when the text doesn't contain any headlines. This is the same issue raised in #520.

See: [`quailiff/feature/break-undo`](https://github.com/quailiff/QOwnNotes/tree/feature/break-undo)

```cpp
void MainWindow::on_actionBreak_Undo_triggered() {
    QMarkdownTextEdit* textEdit = activeNoteTextEdit();
    QTextCursor c = textEdit->textCursor();
    c.movePosition(QTextCursor::StartOfLine);
    c.insertText("# This headline broke Undo ");
}
```

**Comment by pbek** [comment]
Ah, so it was #520... An other unsolved mystery.

**Comment by penCsharpener** [comment]
This would be a nice feature in deed. I'm used to it from Visual Studio or VS Code (Alt + arrow keys). Since there are three different ways of doing the same thing it would be good to be able to change the shortcuts. 

Also in the editors above you can move a line with the carret or selection in it. If the selection covers multiple lines it moves all the lines that have a selection. Moving a paragraph would be the selection of multiple lines.

**Comment by pbek** [comment]
## 19.12.2
- you can now move paragraphs up/down with <kbd>Ctrl + Shift + ↑/↓</kbd>
  (for [#569](https://github.com/pbek/QOwnNotes/issues/569), thank you @Waqar144)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
