### ISSUE TITLE
Customise headlines

### ISSUE THREAD

**Issue by andrademfg** [pbek/QOwnNotes#571]
Hi Patrizio! I've tried to change the default headlines of new notes to get the date in format yyyyMMddHHmm (without : , - or any other character), no underlines, and, if possible, to keep the cursor in the same line so I immediately add a title. I've tried to modify the template you've uploaded (custom-new-note-headline.qml), but I didn't get any result. The reason: I don't know which part of the script I have to change and how to write the instruction for the date in that format (I did it without any problem for the ctrl-t shortcut).

If you could provide some more detailed instructions, I'd be really grateful.

Cheers,
Federico (code-illiterate historian)

**Comment by pbek** [comment]
Hello Federico,

did you also run across this example, where I create a "meeting note" with a date in its name?
<https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/meeting-note.qml>

You would have to play around with:

```javascript
var m = new Date();
 var headline = "Teammeeting " + m.getFullYear() + "-" + ("0" + (m.getMonth()+1)).slice(-2) + "-" + ("0" + m.getDate()).slice(-2);
```

Play around with it and post your result.
Maybe also @Maboroshy (our local script guru) can be of some help.

**Comment by pbek** [comment]
The above example is for creating a new button and menu entry to create a custom note on demand.

The example <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/custom-new-note-headline.qml> is for changing the headline of every newly created note.

**Comment by andrademfg** [comment]
I'd really like to change the headline of every newly created note, that's why I tried first with https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/custom-new-note-headline.qml

However, I tried modifying the "meeting note" example, since it had a line for dates. So I changed it a bit as follows:
 
`var headline = m.getFullYear() + ("0" + (m.getMonth()+1)).slice(-2) + ("0" + m.getDate()).slice(-2) + ("0" + (m.getHours()+1)).slice(-2) + ("0" + (m.getMinutes()+1).slice(-2));`

I got this:

20170503148
====================

I pasted the code in custom-new-note-headline.qml in line 21, replacing the original code, and I got an error. 

I don't know how to get hours and minutes in two-digit format (I just tried to copy the code of days and months, but it doesn't work) and still don't know how to get rid of the underline.

Thanks for your patience!
Federico

**Comment by pbek** [comment]
I tried this and it works:

```javascript
var headline = m.getFullYear() + ("0" + (m.getMonth()+1)).slice(-2) + ("0" + m.getDate()).slice(-2) + ("0" + m.getHours()).slice(-2) + ("0" + m.getMinutes()).slice(-2);
```

Which underline do you mean? The markup headline?
Can you please post your whole script.

**Comment by andrademfg** [comment]
This is the "meeting note" example as I have it. And yes, I want to eliminate the markup headline. Sorry for the inconveniencies, this is embarrasing.

```
import QtQml 2.0
import com.qownnotes.noteapi 1.0

/**
 * This script creates a menu item and a button to create or jump to the current date's meeting note
 */
QtObject {
    /**
     * Initializes the custom action
     */
    function init() {
        script.registerCustomAction("meetingNote", "Create or open a meeting note", "Meeting", "document-new");
    }

    /**
     * This function is invoked when a custom action is triggered
     * in the menu or via button
     *
     * @param identifier string the identifier defined in registerCustomAction
     */
    function customActionInvoked(identifier) {
        if (identifier != "meetingNote") {
            return;
        }

        // get the date headline
        var m = new Date();
        var headline = m.getFullYear() + ("0" + (m.getMonth()+1)).slice(-2) + ("0" + m.getDate()).slice(-2) + ("0" + (m.getHours()+1)).slice(-2) + ("0" + (m.getMinutes()+1).slice(-2));

        var fileName = headline + ".md";
        var note = script.fetchNoteByFileName(fileName);

        // check if note was found
        if (note.id > 0) {
            // jump to the note if it was found
            script.log("found meeting note: " + headline);
            script.setCurrentNote(note);
        } else {
            // create a new meeting note if it wasn't found
            // keep in mind that the note will not be created instantly on the disk
            script.log("creating new meeting note: " + headline);
            script.createNote(headline);

            // tag the current note
            script.tagCurrentNote("meeting");
            script.tagCurrentNote("fuf");
        }
    }
}

```

**Comment by andrademfg** [comment]
And this is my poor attempt of modifying the custom-new-note-headline.qml


```
import QtQml 2.0
import com.qownnotes.noteapi 1.0

/**
 * This script is an example how to modify the headline of new notes
 */
QtObject {
    /**
     * This function is called before a note note is created
     *
     * It allows you to modify the headline of the note before it is created
     * Note that you have to take care about a unique note name, otherwise
     * the new note will not be created, it will just be found in the note list
     *
     * You can use this method for creating note templates
     *
     * @param headline text that would be used to create the headline
     * @return {string} the headline of the note
     */
    function handleNewNoteHeadlineHook(headline) {
        `var headline = m.getFullYear() + ("0" + (m.getMonth()+1)).slice(-2) + ("0" + m.getDate()).slice(-2) + ("0" + (m.getHours()+1)).slice(-2) + ("0" + (m.getMinutes()+1).slice(-2));`

        // add the underline
        for (var i = 0; i < (text.length - 1); i++) {
            underline += "=";
        }

        return text + underline;
    }
}

```

**Comment by pbek** [comment]
This should work:

```javascript
import QtQml 2.0
import com.qownnotes.noteapi 1.0

/**
 * This script creates a menu item and a button to create a custom note
 */
QtObject {
    /**
     * Initializes the custom action
     */
    function init() {
        script.registerCustomAction("customNote", "Create a note", "Meeting", "document-new");
    }

    /**
     * This function is invoked when a custom action is triggered
     * in the menu or via button
     *
     * @param identifier string the identifier defined in registerCustomAction
     */
    function customActionInvoked(identifier) {
        if (identifier != "customNote") {
            return;
        }

        // get the date headline
        var m = new Date();
        var headline = m.getFullYear() + ("0" + (m.getMonth()+1)).slice(-2) + ("0" + m.getDate()).slice(-2) + ("0" + m.getHours()).slice(-2) + ("0" + m.getMinutes()).slice(-2);

        script.createNote(headline);
    }
}
```

It creates a new note with just the date in it.
No newlines at the end... Of course you might want to add some if you like...

**Comment by andrademfg** [comment]
This is flawless! It works perfectly!

Thanks a lot!

**Comment by pbek** [comment]
I'm glad it helped! :smiley: 
You could add a shortcut to the script in the settings.

**Comment by pkeir** [comment]
I've just started with QOwnNotes, and I'm delighted. I found this issue after searching for how to change the headline of every newly created note. I noticed the link above is dead, but found the file referenced is now located at: [https://github.com/pbek/QOwnNotes/blob/develop/docs/content/scripting/examples/custom-new-note-headline.qml](https://github.com/pbek/QOwnNotes/blob/develop/docs/content/scripting/examples/custom-new-note-headline.qml).

I used that file to create my own variant, to create a less numerical heading based on the date and time, for example `Friday, September 4th 2020 (14:44:16)`. For newcomers, you start with `Notes > Settings > Scripting > Add script...`; and must then reload the scripting engine with each edit (shortcut `CTRL+SHIFT+S`). Scripts are basically JavaScript, but QOwnNotes' convention is to use the file extension: `.qml`. This is the script I created:

```javascript
import QtQml 2.0
import QOwnNotesTypes 1.0

QtObject {
    /**
     * @param default headline text that would be used to create the headline
     * @return {string} the headline of the note
     */
    function handleNewNoteHeadlineHook(headline) {

        var m = new Date();
        var days = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
        var months = ['January','February','March','April','May','June','July','August','September','October','November','December'];
        var dayNums = ['','1st','2nd','3rd','4th','5th','6th','7th','8th','9th','10th','11th','12th','13th','14th','15th','16th','17th','18th','19th','20th','21st','22nd','23rd','24th','25th','26th','27th','28th','29th','30th','31st'];

        var day    = days[ m.getDay() ];
        var month  = months[ m.getMonth() ]; 
        var dayNum = dayNums[ m.getDate() ];  
        var date   = day + ', ' + month + ' ' + dayNum + ' ' + m.getFullYear();
        var time   = m.getHours() + ':' + m.getMinutes() + ':' + m.getSeconds();
        var text   = date + ' (' + time + ')\n'; 

        var underline = "";

        // add the underline
        for (var i = 0; i < (text.length - 1); i++) {
            underline += "=";
        }

        return text + underline;             
    }
}
```

Keep up the good work!

**Comment by pbek** [comment]
@pkeir, great you found the scripting engine useful. 😁 

If you want to contribute scripts that may be of use to others feel free to do so at https://github.com/qownnotes/scripts.

> but QOwnNotes' convention is to use the file extension: .qml

It's JavaScript in [Qt QML files](https://doc.qt.io/qt-5/qtqml-index.html). 😉 

You'll find a lot more scripting resources at https://docs.qownnotes.org/en/develop/scripting/.

**Comment by pkeir** [comment]
My script above creates nice headlines...but terrible file names. I work on Linux, and very much try to avoid filenames with spaces in them (for example I often prefer to search files like these from the command line). As the files created from my script are based on the headline, they have spaces in them. I do like the headlines with spaces though. Can they be different? Is it possible to script the headline *and* the filename?

**Comment by pbek** [comment]
Well, there is https://www.qownnotes.org/scripting/hooks.html#handlenotetextfilenamehook

**Comment by pkeir** [comment]
Perfect! You are a great reminder as to why a project's community support is so important. I enabled my "Allow note file name to be different from headline" setting, and all is good with my updated script. Here it is:

```javascript
import QtQml 2.0
import QOwnNotesTypes 1.0

QtObject {
   /** 
    * @param default headline text that would be used to create the headline 
    * @return {string} the headline of the note 
    */ 
  function handleNewNoteHeadlineHook(headline) {  

    var m = new Date();     
    var days = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
    var months = ['January','February','March','April','May','June','July','August','September','October','November','December'];
    var dayNums = ['','1st','2nd','3rd','4th','5th','6th','7th','8th','9th','10th','11th','12th','13th','14th','15th','16th','17th','18th','19th','20th','21st','22nd','23rd','24th','25th','26th','27th','28th','29th','30th','31st'];
 
    var day    = days[ m.getDay() ];     
    var month  = months[ m.getMonth() ];     
    var dayNum = dayNums[ m.getDate() ];     
    var date   = day + ', ' + month + ' ' + dayNum + ' ' + m.getFullYear();    
    var time   = m.toLocaleTimeString();     
    var text   = date + ' (' + time + ')\n';     
 
    var underline = "";     
 
    // add the underline     
    for (var i = 0; i < (text.length - 1); i++) {     
      underline += "=";       
    }     
 
    return text + underline;     
  }  

  /**
   * This function is called when a note gets stored to disk if
   * "Allow note file name to be different from headline" is enabled
   * in the settings
   *
   * It allows you to modify the name of the note file
   * Keep in mind that you have to care about duplicate names yourself!
   *
   * Return an empty string if the file name of the note should
   * not be modified
   *
   * @param {NoteApi} note - the note object of the stored note
   * @return {string} the file name of the note
   */
  function handleNoteTextFileNameHook(note) {   
 
    var m = new Date();     
    var days = ['sun','mon','tue','wed','thu','fri','sat'];     
    var months = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oc','nov','dec'];
    var dayNums = ['','01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31'];
 
    var day    = days[ m.getDay() ];     
    var month  = months[ m.getMonth() ];     
    var dayNum = dayNums[ m.getDate() ];     
    var date   = day + '-' + dayNum + '-' + month + '-' + m.getFullYear();     
    var time   = m.toLocaleTimeString();     
    time = time.replace(/\s+/g, '-'); // remove space between time and "GMT"   
    var text   = date + '-' + time;     
 
    return text;     
  }   
}
```

**Comment by pbek** [comment]
Great it worked out! 🥳
