### ISSUE TITLE
Feature request: Import/export formats

### ISSUE THREAD

**Issue by Letterus** [pbek/QOwnNotes#573]
QOwnNotes is that good, simple and effective it became my main cross platform productivity tool.

Short time ago I detected I could further improve my workflow using MultiMarkdown and pandoc. Using these tools I could create an outline (OmniOutliner -> opml), convert it to markdown using pandoc, fill the outline with text (reexport and -import to and from opml in case I want to change a documents structure) and then export the whole text to LibreOffice odt file for further editing and finishing using MultiMarkdown.
(I used MultiMarkdown because it supports footnotes which pandoc does not.)

Why am I writing this? It would be nice if I could import and export from and to those pandoc formats directly from QOwnNotes.

I'm thinking of: You tell QOwnNotes where to find the pandoc binary and when you've done this, there appear two new menu items for import and export providing a dialog (or submenu) where I can select the format. What do you think about it?

(I was speaking of pandoc - I don't know if the integration of MultiMarkdown would be easier. Maybe you could ship/compile MultiMarkdown with QOwnNotes?)

### Markdown to Open Document Text using MultiMarkdown
`multimarkdown -t odf ~/MyText.md > MyText.odt`

### Markdown to OPML using MultiMarkdown
`multimarkdown -t opml MyOutline.md > MyOutline.opml`

### OPML to Markdown using pandoc
`pandoc --from=opml --to=markdown_mmd --atx-headers MyOutline.opml > MyOutline.md`

### Markdown to Open Document Text using panding
`pandoc --from=markdown_mmd --to=odt MyText.md -o MyText`

**Comment by pbek** [comment]
That's why I integrated the scripting engine. ;)
You can do that all yourself with a custom action: <http://docs.qownnotes.org/en/develop/scripting/README.html#registering-a-custom-action>

...accessing the current note: <http://docs.qownnotes.org/en/develop/scripting/README.html#getting-the-current-note>

I'm happy to help you with scripts and @Maboroshy is our local scripting guru.

**Comment by Letterus** [comment]
Uh, yep. That makes sense. Thanks for that hint. I'm gonna do this once. ;-)

**Comment by pbek** [comment]
Be sure to let me know how it went!

**Comment by pbek** [comment]
I will close this issue until there is more information.
