### ISSUE TITLE
macOS: App bundle does not contain QtQuick

### ISSUE THREAD

**Issue by Letterus** [pbek/QOwnNotes#575]
It seems macdeployqt includes frameworks depending on given qml files. Currently QtQuick is not included.

See http://stackoverflow.com/questions/20895398/cant-deploy-qt-quick-app-to-mac-osx. Maybe there is a way to include all frameworks a qml script might need currently?

**Comment by pbek** [comment]
I'm sorry, QOwnNotes doesn't need QtQuick to work and I don't want to bundle or to require the user to install it  on every platform when it's not needed.

**Comment by Letterus** [comment]
Ok, I'll try to add it on my own. But this will render the scripting engine useless to others that might want to use it and are not able to compile QOwnNotes themselves?

**Comment by pbek** [comment]
No other script is using QtQuick so far. @Maboroshy's script was the first to use QtQuick to show a dialog and he was using it on Manjaro (I suppose). I'm not sure if that's reason enough to include such a huge package to every installation of QOwnNotes...

**Comment by pbek** [comment]
And if we add QtQuick we have to add all other QtQuick related libraries too... And there are a lot of them...  :frowning_face:

**Comment by pbek** [comment]
So far QOwnNotes is a pure Widget-app, without any QtQuick scenes...

**Comment by Letterus** [comment]
Hm, I see. Then… maybe you could add a native word count? Bundling and compiling QOwnNotes with QtQuick for such a small function would be quite a big thing. ;-)

**Comment by pbek** [comment]
I did something better:

## 17.05.1
- there now is a new scripting command to show an information message box
  `script.informationMessageBox()`
    - for more information please take a look at the
      [scripting documentation](http://docs.qownnotes.org/en/develop/scripting/README.html#showing-an-information-message-box)
