### ISSUE TITLE
QOwnNotes fails with: relocation error: QOwnNotes: symbol _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

### ISSUE THREAD

**Issue by Flashwalker** [pbek/QOwnNotes#577]
#### Expected behaviour
`QOwnNotes` just works out of the box! (has repo with backported dependencies)

#### Actual behaviour
On Linux Mint 17 (14.04 Trusty), after installing full qt57 from `ppa:beineri/opt-qt571-trusty` and made symlink: `sudo mv /opt/qt56 /opt/qt56.56; sudo ln -s /opt/qt57 /opt/qt56`, and after setting env: `source /opt/qt57/bin/qt57-env.sh` and after installing [qownnotes_17.05.1-1_i386](http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/xUbuntu_15.10/i386/qownnotes_17.05.1-1_i386.deb) when running `QOwnNotes` it fails with:

```
QOwnNotes: relocation error: QOwnNotes: symbol _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```

 After googling i found:

* https://stackoverflow.com/questions/36816570/glibcxx-3-4-21-not-defined-in-file-libstdc-so-6-with-link-time-reference
* https://gist.github.com/beci/2a2091f282042ed20cda
* https://askubuntu.com/questions/777803/apt-relocation-error-version-glibcxx-3-4-21-not-defined-in-file-libstdc-so-6

After installing packages from Xenial repos:

```
sudo dpkg -i --auto-deconfigure libstdc++6_5.4.0-6ubuntu1~16.04.4_i386.deb gcc-5-base_5.4.0-6ubuntu1~16.04.4_i386.deb cpp-5_5.4.0-6ubuntu1~16.04.4_i386.deb
```

`QOwnNotes` starts and works. But some dependencies might be broken (in my case it's:  flush, gnote. libassimp3, pdf2djvu, sqlitebrowser). And, i think, it can cause unpredictable behavior for system (so do backup before: `sudo apt-get download --allow-unauthenticated libstdc++6 gcc-5-base gcc-5 cpp-5`)  
But one more thing: now, against qownnotes_16.09.17-1ubuntu3ppa1~vivid1_i386 version, in dark theme mode the editing field is not dark themed.

#### Steps to reproduce

* On Linux Mint 17 (Ubuntu 14.04 Trusty)
```
sudo add-apt-repository ppa:beineri/opt-qt571-trusty
wget http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/xUbuntu_15.10/Release.key -O - | sudo apt-key add -
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/xUbuntu_15.10/ /' >> /etc/apt/sources.list.d/qownnotes.list"
update
sudo apt-get install qt57-meta-full qownnotes
sudo mv /opt/qt56 /opt/qt56.56
sudo ln -s /opt/qt57 /opt/qt56
source /opt/qt57/bin/qt57-env.sh
QOwnNotes
```

#### Output from the debug section in the settings dialog
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `сб мая 6 03:51:53 2017`
**Version**: `17.05.1`
**Build date**: `May  4 2017`
**Build number**: `331`
**Platform**: `linux`
**Operating System**: `Ubuntu 14.04.5 LTS`
**Build architecture**: `i386`
**Current architecture**: `i386`
**Release**: `OBS`
**Qt Version (build)**: `5.4.2`
**Qt Version (runtime)**: `5.7.1`
**Portable mode**: `no`
**Settings path / key**: `/home/user/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/user/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `ru_RU`
**Locale (interface)**: `ru`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `124`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `notes`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/user/Documents/notes`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/user/Documents/notes/notes.sqlite`

### Note folder ``

**id**: `2`
**isCurrent**: `no`
**activeTagId**: `-1`
**localPath**: *empty*
**remotePath**: *empty*
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/notes.sqlite`

### Note folder `notes2`

**id**: `3`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/user/Documents/notes2`
**remotePath**: *empty*
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/user/Documents/notes2/notes.sqlite`

## Settings

**AboutDialog/geometry**: `<binary data>`
**ActiveNoteHistoryItem**: *empty*
**Debug/fakeOldVersionNumber**: `false`
**Debug/fileLogging**: `true`
**DistractionFreeMode/editorWidthMode**: `1`
**DistractionFreeMode/menuBarGeometry**: `<binary data>`
**DistractionFreeMode/menuBarHeight**: `24`
**DistractionFreeMode/windowState**: `<binary data>`
**Editor/CurrentSchemaKey**: `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing**: `true`
**Editor/autoBracketRemoval**: `true`
**LastUpdateCheck**: `2017-05-06T03:49:40`
**LinkDialog/geometry**: `<binary data>`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `16`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `Sans,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl**: `false`
**MainWindow/showNotesFromAllNoteSubFolders**: `true`
**NoteSortOrder**: `0`
**PiwikClientId**: `<hidden>`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**ShowSystemTray**: `false`
**SortingModeAlphabetically**: `false`
**StartHidden**: `false`
**WelcomeDialog/geometry**: `<binary data>`
**acceptAllExternalModifications**: `false`
**allowDifferentNoteFileName**: `false`
**allowOnlyOneAppInstance**: `true`
**appMetrics/disableAppHeartbeat**: `true`
**appMetrics/disableTracking**: `true`
**appMetrics/notificationShown**: `true`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**currentWorkspace**: `d6419ed5-7558-4e66-97fd-48c0e952c51b`
**customNoteFileExtensionList**: *empty*
**darkMode**: `false`
**darkModeColors**: `false`
**darkModeTrayIcon**: `true`
**defaultNoteFileExtension**: `md`
**demoNotesCreated**: `true`
**disableAutomaticUpdateDialog**: `true`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: `textadept`
**gitCommitInterval**: `30`
**gitExecutablePath**: *empty*
**gitLogCommand**: *empty*
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**imageScaleDown**: `false`
**imageScaleDownMaximumHeight**: `1024`
**imageScaleDownMaximumWidth**: `1024`
**insertTimeFormat**: *empty*
**interfaceLanguage**: `ru`
**internalIconTheme**: `true`
**itemHeight**: `17`
**markdownHighlightingEnabled**: `true`
**networking/ignoreSSLErrors**: `true`
**networking/proxyHostName**: `127.0.0.1`
**networking/proxyNeedsAuth**: `false`
**networking/proxyPassword**: `<hidden>`
**networking/proxyPort**: `127`
**networking/proxyType**: `3`
**networking/proxyUser**: *empty*
**noteSaveIntervalTime**: `10`
**notesPath**: `/home/user/Documents/notes`
**notifyAllExternalModifications**: `true`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: *empty*
**ownCloud/supportEnabled**: `false`
**ownCloud/todoCalendarBackend**: `1`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloud/userName**: *empty*
**previousWorkspace**: `98840265-b52b-4f5c-8c6f-937cfca44feb`
**recentNoteFolders**: `, /home/user/Documents/notes2, /home/user/QOwnNotes/Notes`
**restoreCursorPosition**: `true`
**savedSearches/noteFolder-1**: `Note 2017-04-29T04.54.36, Note 2017-04-29T04.51.30, Note 2017-04-29T04.50.30, Note 2017-04-29T04.47.55, Note 2017-04-29T04.47.41, Note 2017-04-29T04.47.06, Note 2017-04-29T04.45.21, Note 2017-04-29T04.44.50, Note 2017-04-29T04.43.55, Note 2017-04-29T04.17.14, Note 2017-04-29T04.16.36, Note 2017-04-29T04.15.36, Note 2017-04-29T04.13.59, Note 2017-04-29T04.08.15, Note 2017-04-29T04.07.37, Note 2017-04-29T04.06.37, Note 2017-04-29T04.05.50, Note 2017-04-29T04.04.35, Note 2017-04-29T04.04.12, Note 2017-04-29T04.03.28, Note 2017-04-29T04.01.28, Note 2017-04-29T03.59.46, Note 2017-04-29T03.33.47, Note 2017-04-29T03.33.08, Note 2017-04-29T03.32.47, Note 2017-04-29T03.29.30, Note 2017-04-29T03.28.49, Note 2017-04-29T03.27.48, Note 2017-04-29T03.26.12, Note 2017-04-29T03.26.00, Note 2017-04-29T03.25.30, Note 2017-04-29T03.25.14, Note 2017-04-29T03.24.21, Note 2017-04-29T03.23.54, Note 2017-04-29T03.21.47, Note 2017-04-29T03.20.11, Note 2017-04-29T03.19.17, Note 2017-04-29T03.18.05, Note 2017-04-29T03.17.47, Note 2017-04-29T01.49.54, Note 2017-04-29T01.49.42, Note 2017-04-29T01.49.16, Note 2017-04-29T01.46.58, Note 2017-04-29T01.46.39, Note 2017-04-29T01.46.28, Note 2017-04-29T01.46.08, Note 2017-04-29T01.45.43, Note 2017-04-29T01.44.54, Note 2017-04-29T01.44.42, Note 2017-04-29T01.44.21, Note 2017-04-29T01.42.33, Note 2017-04-29T01.41.33, Note 2017-04-29T01.40.45, Note 2017-04-29T01.40.13, Note 2017-04-29T01.36.44, Note 2017-04-29T01.36.11, Note 2017-04-29T01.34.09, Note 2017-04-29T01.17.55, Note 2017-04-28T01.18.13, Note 2017-04-13T04.48.22`
**savedSearches/noteFolder-2**: `Note 2017-04-12T02.03.03, Note 2017-04-12T02.01.44, Note 2017-04-12T01.59.24, Note 2017-04-12T01.55.21, Note 2017-04-12T01.52.40, Note 2017-04-11T09.35.45, Note 2017-04-11T09.35.03, Note 2017-04-11T09.32.45, Note 2017-04-11T09.27.23, Note 2017-04-11T09.26.48, Note 2017-04-11T09.22.51, Note 2017-04-11T09.11.07, Note 2017-04-11T09.10.09, Note 2017-04-11T09.05.35, Note 2017-04-11T09.04.27, Note 2017-04-11T08.12.04, Note 2017-04-11T08.09.57, Note 2017-04-11T08.05.56, Note 2017-04-11T08.04.35, Note 2017-04-11T08.03.25, Note 2017-04-11T08.02.02, Note 2017-04-11T07.59.57, Note 2017-04-11T07.57.32, Note 2017-04-11T07.53.46, Note 2017-04-11T07.49.45, Note 2017-04-11T07.43.48, Note 2017-04-11T07.33.10, Note 2017-04-11T07.30.48, Note 2017-04-05T20.22.20, Note 2017-04-02T16.48.04, Note 2017-04-02T16.45.48, Note 2017-04-02T03.23.24, Note 2017-04-02T03.20.38, Note 2017-04-02T03.18.17, Note 2017-04-02T03.10.37, Note 2017-04-02T03.07.51, Note 2017-04-02T03.04.36, Note 2017-04-02T02.59.27, Note 2017-04-02T02.57.45, Note 2017-04-02T02.54.49, Note 2017-04-02T02.53.59, Note 2017-04-02T02.52.35, Note 2017-04-02T02.47.23, Note 2017-04-02T02.44.49, Note 2017-04-02T02.40.25, Note 2017-04-02T02.39.01, Note 2017-04-02T02.36.19, Note 2017-04-02T02.30.28, Note 2017-04-02T02.28.09, Note 2017-04-02T02.17.09, Note 2017-01-05T20.49.21, Note 2017-01-05T20.43.59, Note 2017-01-05T20.40.41, Note 2017-01-05T20.38.39, Note 2017-01-05T20.00.22, Note 2017-01-05T19.59.49, Note 2017-01-05T19.56.21, Note 2017-01-05T19.51.51, Note 2017-01-05T19.50.36, Note 2017-01-05T19.47.53, Note 2017-01-05T19.46.58, Note 2017-01-05T19.45.40, Note 2017-01-05T19.42.00, Note 2017-01-05T19.37.59, Note 2017-01-05T19.36.18, Note 2017-01-05T19.29.58, Note 2017-01-05T19.27.33, Note 2017-01-05T19.26.22, Note 2017-01-05T08.24.14, Note 2017-01-05T08.18.34, Note 2017-01-05T06.16.00`
**savedSearches/noteFolder-3**: `Note 2017-01-05T12.01.00, Note 2017-01-05T11.23.16`
**showMenuBar**: `true`
**showStatusBar**: `true`
**toolbar/1/items**: `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name**: `mainToolBar`
**toolbar/1/title**: `Главная панель инструментов`
**toolbar/2/items**: `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name**: `formattingToolbar`
**toolbar/2/title**: `панель инструментов форматирования`
**toolbar/3/items**: `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name**: `insertingToolbar`
**toolbar/3/title**: `панель инструментов вставки`
**toolbar/4/items**: `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name**: `encryptionToolbar`
**toolbar/4/title**: `панель инструментов шифрования`
**toolbar/5/items**: `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name**: `windowToolbar`
**toolbar/5/title**: `панель инструментов окна`
**toolbar/6/items**: `action_Quit`
**toolbar/6/name**: `quitToolbar`
**toolbar/6/title**: `Панель инструментов выхода`
**toolbar/size**: `6`
**useUNIXNewline**: `false`
**workspace-98840265-b52b-4f5c-8c6f-937cfca44feb/name**: `минимальный`
**workspace-98840265-b52b-4f5c-8c6f-937cfca44feb/noteSubFolderDockWidgetVisible**: `true`
**workspace-98840265-b52b-4f5c-8c6f-937cfca44feb/windowState**: `<binary data>`
**workspace-d6419ed5-7558-4e66-97fd-48c0e952c51b/name**: `на весь экран`
**workspace-d6419ed5-7558-4e66-97fd-48c0e952c51b/noteSubFolderDockWidgetVisible**: `true`
**workspace-d6419ed5-7558-4e66-97fd-48c0e952c51b/windowState**: `<binary data>`
**workspaces**: `d6419ed5-7558-4e66-97fd-48c0e952c51b, 98840265-b52b-4f5c-8c6f-937cfca44feb`

## System environment

**XDG_VTNR**: `7`
**INFINALITY_FT_AUTOHINT_HORIZONTAL_STEM_DARKEN_STRENGTH**: `10`
**UDEdir**: *empty*
**XDG_SESSION_ID**: `1`
**SSH_AGENT_PID**: `15129`
**CLUTTER_IM_MODULE**: `xim`
**rvm_bin_path**: `/usr/share/rvm/bin`
**GPG_AGENT_INFO**: `/tmp/gpg-jvfgfj/S.gpg-agent:3407:1`
**GEM_HOME**: `/home/user/.rvm/gems/ruby-2.3.0`
**SHELL**: `/bin/bash`
**INFINALITY_FT_AUTOHINT_VERTICAL_STEM_DARKEN_STRENGTH**: `25`
**INFINALITY_FT_BOLD_EMBOLDEN_X_VALUE**: `0`
**TERM**: `xterm-256color`
**XDG_SESSION_COOKIE**: `8288b715b0334cf99be115df545f422a-1493466837.12237-198689771`
**IRBRC**: `/usr/share/rvm/rubies/ruby-2.3.0/.irbrc`
**GTK2_RC_FILES**: `/usr/share/themes/Numix-dark/gtk-2.0/gtkrc:/home/user/.gtkrc-2.0.mine`
**PERL5LIB**: `/home/user/perl5/lib/perl5:/home/user/perl5/lib/perl5:`
**QTDIR**: `/opt/qt57`
**GNOME_KEYRING_CONTROL**: `/run/user/1000/keyring-qveNdc`
**MY_RUBY_HOME**: `/usr/share/rvm/rubies/ruby-2.3.0`
**PERL_MB_OPT**: `--install_base "/home/user/perl5"`
**SWT_GTK3**: `0`
**GTK_MODULES**: `gtk-vector-screenshot`
**INFINALITY_FT_CONTRAST**: `15`
**USER**: `user`
**INFINALITY_FT_GRAYSCALE_FILTER_STRENGTH**: `0`
**LD_LIBRARY_PATH**: `/opt/qt57/lib/i386-linux-gnu:/opt/qt57/lib:`
**QT_ACCESSIBILITY**: `1`
**LS_COLORS**: `rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:`
**_system_type**: `Linux`
**rvm_path**: `/usr/share/rvm`
**SSH_AUTH_SOCK**: `/tmp/ssh-y3I3AIaJp9s8/agent.15128`
**INFINALITY_FT_FRINGE_FILTER_STRENGTH**: `0`
**INFINALITY_FT_BRIGHTNESS**: `-10`
**INFINALITY_FT_USE_VARIOUS_TWEAKS**: `true`
**INFINALITY_FT_GAMMA_CORRECTION**: `1000 80`
**rvm_prefix**: `/usr/share`
**PATH**: `/opt/qt57/bin:/home/user/bin:/home/user/perl5/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/heroku/bin:/home/user/bin:/home/user/perl5/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/heroku/bin:/home/user/.rvm/gems/ruby-2.3.0/bin:/home/user/.rvm/gems/ruby-2.3.0@global/bin:/usr/share/rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/rvm/bin`
**MAIL**: `/var/mail/user`
**QT_IM_MODULE**: `xim`
**PWD**: `/home/user`
**XMODIFIERS**: `@im=fcitx`
**EDITOR**: `vim`
**INFINALITY_FT_FILTER_PARAMS**: `11 22 38 22 11`
**LANG**: `ru_RU.UTF-8`
**GNOME_KEYRING_PID**: `3068`
**INFINALITY_FT_STEM_SNAPPING_SLIDING_SCALE**: `0`
**INFINALITY_FT_USE_KNOWN_SETTINGS_ON_SELECTED_FONTS**: `false`
**INFINALITY_FT_WINDOWS_STYLE_SHARPENING_STRENGTH**: `0`
**INFINALITY_FT_CHROMEOS_STYLE_SHARPENING_STRENGTH**: `0`
**_system_arch**: `i386`
**INFINALITY_FT_AUTOHINT_SNAP_STEM_HEIGHT**: `0`
**INFINALITY_FT_STEM_ALIGNMENT_STRENGTH**: `0`
**_system_version**: `17`
**HISTIGNORE**: `pwd:&:ls:[bf]g:exit`
**rvm_version**: `1.27.0 (latest)`
**XDG_SEAT**: `seat0`
**HOME**: `/home/user`
**SHLVL**: `2`
**INFINALITY_FT_BOLD_EMBOLDEN_Y_VALUE**: `0`
**GNOME_DESKTOP_SESSION_ID**: `default`
**PERL_LOCAL_LIB_ROOT**: `/home/user/perl5:/home/user/perl5:`
**LOGNAME**: `user`
**CUR_WIDTH**: `71`
**INFINALITY_FT_GLOBAL_EMBOLDEN_Y_VALUE**: `0`
**QT4_IM_MODULE**: `xim`
**GEM_PATH**: `/home/user/.rvm/gems/ruby-2.3.0:/home/user/.rvm/gems/ruby-2.3.0@global`
**DBUS_SESSION_BUS_ADDRESS**: `unix:abstract=/tmp/dbus-Q28vKkLMlA,guid=1694b617c0f840d2428b734459047edb`
**INFINALITY_FT_STEM_FITTING_STRENGTH**: `0`
**PKG_CONFIG_PATH**: `/opt/qt57/lib/pkgconfig:`
**GTK_CSD**: `1`
**LESSOPEN**: `| /usr/bin/lesspipe %s`
**INFINALITY_FT_AUTOHINT_INCREASE_GLYPH_HEIGHTS**: `false`
**TEXTDOMAIN**: `im-config`
**DISPLAY**: `:0.0`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**INFINALITY_FT_GLOBAL_EMBOLDEN_X_VALUE**: `0`
**GTK_IM_MODULE**: `xim`
**RUBY_VERSION**: `ruby-2.3.0`
**NO_AT_BRIDGE**: `1`
**LESSCLOSE**: `/usr/bin/lesspipe %s %s`
**_system_name**: `Mint`
**TEXTDOMAINDIR**: `/usr/share/locale/`
**PERL_MM_OPT**: `INSTALL_BASE=/home/user/perl5`
**XAUTHORITY**: `/home/user/.Xauthority`

#### Relevant log output (you have to enable the log widget)

```
[may 06 03:49:44] [warning]: onResult  - 'reply error':  1
```

### Crutches that makes QOwnNotes work for me again:

```
sudo add-apt-repository ppa:beineri/opt-qt571-trusty
wget http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/xUbuntu_15.10/Release.key -O - | sudo apt-key add -
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/xUbuntu_15.10/ /' >> /etc/apt/sources.list.d/qownnotes.list"
update
sudo apt-get install qt57-meta-full qownnotes gcc-5 g++-5
sudo mv /opt/qt56 /opt/qt56.56
sudo ln -s /opt/qt57 /opt/qt56
source /opt/qt57/bin/qt57-env.sh
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1 --slave /usr/bin/g++ g++ /usr/bin/g++-5
sudo dpkg -i --auto-deconfigure libstdc++6_5.4.0-6ubuntu1~16.04.4_i386.deb gcc-5-base_5.4.0-6ubuntu1~16.04.4_i386.deb cpp-5_5.4.0-6ubuntu1~16.04.4_i386.deb
QOwnNotes
```

**Comment by pbek** [comment]
Thank you for the research! I can't really do much about the way the packages are built on the Open Build Service and the 15.10 packages are not meant to work with 14.04.

You could go with the deb package provided at <http://www.qownnotes.org/installation#Linux>, that should work. It was built on 12.04...

But wouldn't it be easier if you go with the snap package of QOwnNotes (since there should be snap support under 14.04)?
<http://www.omgubuntu.co.uk/2017/02/install-snap-apps-ubuntu-14-04>

**Comment by Flashwalker** [comment]
Thanks.
Actually i found easy way:
Just download `libstdc++6_5.4.0-6ubuntu1~16.04.4_i386.deb`, unpack `.so` lib file to `libstdc++.so.6` to `~/lib` directory, and then just run like this: `LD_LIBRARY_PATH=~/lib:$LD_LIBRARY_PATH QOwnNotes`

**Comment by pbek** [comment]
Thank you for letting me know.
