### ISSUE TITLE
Problem with API version ?

### ISSUE THREAD

**Issue by lmjst** [pbek/QOwnNotes#580]
Hi,
 I don't understand the error message about API version. I've de-activated and reinstalled it in my owncloud but t does'nt change the problem :
Error messages on opening qownnotes :
Please consider updating your QOwnNotesAPI app on your server, your app version 0 is too low and may cause troubles in QOwnNotes.

ownCloud server error: Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services. DEBUG OUTPUT:
Please check your ownCloud configuration.

And the setting panel says :
The connection was made successfully!
Server version: 9.0.9.1
QOwnNotesAPI version: 0

In my owncloud I have activated :
 QOwnNotesAPI 17.3.0

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `ven. mai 12 01:03:41 2017`
**Version**: `17.05.3`
**Build date**: `May  9 2017`
**Build number**: `333`
**Platform**: `linux`
**Operating System**: `Ubuntu 16.04.2 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.5.1`
**Qt Version (runtime)**: `5.5.1`
**Portable mode**: `no`
**Settings path / key**: `/home/dd/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/dd/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `fr_FR`
**Locale (interface)**: `en`
**Icon theme**: `Humanity`
**Notes in current note folder**: `3`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://d.org/owncloud`
**appIsValid**: `yes`
**notesPathExists**: `unknown`
**serverVersion**: `9.0.9.1`
**appVersion**: `0`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Notes`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/dd/Documents/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/dd/Documents/Notes/notes.sqlite`

## Settings

**AboutDialog/geometry**: `<binary data>`
**ActiveNoteHistoryItem**: *empty*
**Debug/fakeOldVersionNumber**: `true`
**Debug/fileLogging**: `true`
**Editor/CurrentSchemaKey**: `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing**: `true`
**Editor/autoBracketRemoval**: `true`
**EvernoteImportDialog/geometry**: `<binary data>`
**FileDialog/LastPath**: `/home/dd/Documents/Notes`
**FileDialog/LastPath-EvernoteImport**: `/home/dd/Documents/Notes`
**LastUpdateCheck**: `2017-05-12T01:00:53`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `24`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `Sans,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `Sans,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl**: `false`
**MainWindow/showNotesFromAllNoteSubFolders**: `true`
**NoteSortOrder**: `0`
**PiwikClientId**: `<hidden>`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**ShowSystemTray**: `false`
**SortingModeAlphabetically**: `false`
**UpdateDialog/geometry**: `<binary data>`
**WelcomeDialog/geometry**: `<binary data>`
**acceptAllExternalModifications**: `false`
**allowDifferentNoteFileName**: `false`
**allowOnlyOneAppInstance**: `false`
**appMetrics/disableAppHeartbeat**: `true`
**appMetrics/disableTracking**: `true`
**appMetrics/notificationShown**: `true`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**currentWorkspace**: `be24a6b5-843c-4511-a689-e3b467471f17`
**customNoteFileExtensionList**: `nnex`
**darkMode**: `false`
**darkModeColors**: `false`
**darkModeTrayIcon**: `false`
**defaultNoteFileExtension**: `md`
**demoNotesCreated**: `true`
**disableAutomaticUpdateDialog**: `true`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: *empty*
**gitCommitInterval**: `30`
**gitExecutablePath**: *empty*
**gitLogCommand**: *empty*
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**imageScaleDown**: `true`
**imageScaleDownMaximumHeight**: `1024`
**imageScaleDownMaximumWidth**: `1024`
**insertTimeFormat**: *empty*
**interfaceLanguage**: `en`
**internalIconTheme**: `false`
**itemHeight**: `16`
**markdownHighlightingEnabled**: `true`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `2`
**noteSaveIntervalTime**: `10`
**notesPath**: `/home/dd/Documents/Notes`
**notifyAllExternalModifications**: `false`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: `https://d.org/owncloud`
**ownCloud/supportEnabled**: `true`
**ownCloud/todoCalendarBackend**: `3`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/todoCalendarEnabledList**: `d`
**ownCloud/todoCalendarEnabledUrlList**: `https://d.org/owncloud/remote.php/dav/calendars/d/`
**ownCloud/todoCalendarUrlList**: `https://d.org/owncloud/remote.php/dav/calendars/d/, https://d.org/owncloud/remote.php/dav/calendars/d/, https://d.org/owncloud/remote.php/dav/calendars/d/deccaldavzoho/`
**ownCloud/userName**: `d`
**previousWorkspace**: `95d2fcdd-1ddc-4b7f-98a3-02eee5b418b1`
**recentNoteFolders**: `/home/dd/ownCloud/Notes`
**restoreCursorPosition**: `true`
**savedSearches/noteFolder-1**: `Note 2017-03-22T23.30.05, Note 2017-01-31T22.43.23, Note 2017-01-21T19.01.32, Note 2017-01-21T17.43.01`
**showMenuBar**: `true`
**showStatusBar**: `true`
**skipVersion**: `17.03.2`
**toolbar/1/items**: `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name**: `mainToolBar`
**toolbar/1/title**: `main toolbar`
**toolbar/2/items**: `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name**: `formattingToolbar`
**toolbar/2/title**: `formatting toolbar`
**toolbar/3/items**: `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name**: `insertingToolbar`
**toolbar/3/title**: `inserting toolbar`
**toolbar/4/items**: `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name**: `encryptionToolbar`
**toolbar/4/title**: `encryption toolbar`
**toolbar/5/items**: `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name**: `windowToolbar`
**toolbar/5/title**: `window toolbar`
**toolbar/6/items**: `action_Quit`
**toolbar/6/name**: `quitToolbar`
**toolbar/6/title**: `quit toolbar`
**toolbar/size**: `6`
**useUNIXNewline**: `false`
**workspace-95d2fcdd-1ddc-4b7f-98a3-02eee5b418b1/name**: `complet`
**workspace-95d2fcdd-1ddc-4b7f-98a3-02eee5b418b1/noteSubFolderDockWidgetVisible**: `true`
**workspace-95d2fcdd-1ddc-4b7f-98a3-02eee5b418b1/windowState**: `<binary data>`
**workspace-be24a6b5-843c-4511-a689-e3b467471f17/name**: `minimal`
**workspace-be24a6b5-843c-4511-a689-e3b467471f17/noteSubFolderDockWidgetVisible**: `true`
**workspace-be24a6b5-843c-4511-a689-e3b467471f17/windowState**: `<binary data>`
**workspaces**: `95d2fcdd-1ddc-4b7f-98a3-02eee5b418b1, be24a6b5-843c-4511-a689-e3b467471f17`

## System environment

**USER**: `dd`
**LANGUAGE**: `fr_FR`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `2826`
**SHLVL**: `0`
**HOME**: `/home/dd`
**DESKTOP_SESSION**: `cinnamon`
**QT_LINUX_ACCESSIBILITY_ALWAYS_ON**: `1`
**GTK_MODULES**: `gail:atk-bridge`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**DBUS_SESSION_BUS_ADDRESS**: `unix:abstract=/tmp/dbus-yYeA25JJum,guid=82f44512d34d607a565b44a35911d3c6`
**QT_QPA_PLATFORMTHEME**: `appmenu-qt5`
**MANDATORY_PATH**: `/usr/share/gconf/cinnamon.mandatory.path`
**LOGNAME**: `dd`
**DEFAULTS_PATH**: `/usr/share/gconf/cinnamon.default.path`
**XDG_SESSION_ID**: `c2`
**GTK2_MODULES**: `overlay-scrollbar`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
**GDM_LANG**: `fr_FR`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**DISPLAY**: `:0`
**LANG**: `fr_FR.UTF-8`
**XDG_SESSION_DESKTOP**: `cinnamon`
**XAUTHORITY**: `/home/dd/.Xauthority`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/dd`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**SHELL**: `/bin/bash`
**QT_ACCESSIBILITY**: `1`
**GDMSESSION**: `cinnamon`
**XDG_VTNR**: `7`
**PWD**: `/home/dd`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-cinnamon:/etc/xdg`
**XDG_DATA_DIRS**: `/usr/share/cinnamon:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**QT_STYLE_OVERRIDE**: `gtk`
**GTK_OVERLAY_SCROLLING**: `1`
**SESSION_MANAGER**: `local/dd:@/tmp/.ICE-unix/2769,unix/dd:/tmp/.ICE-unix/2769`
**XDG_CURRENT_DESKTOP**: `X-Cinnamon`
**GJS_DEBUG_OUTPUT**: `stderr`
**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`
**CINNAMON_VERSION**: `3.0.7`
**GIO_LAUNCHED_DESKTOP_FILE**: `/home/dd/.local/share/applications/QOwnNotes-d225308c-126e-11e7-af12-340286f75576.desktop`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `29544`
**QT_IM_MODULE**: `compose`

**Comment by pbek** [comment]
I guess it's the same like here: https://github.com/pbek/QOwnNotes/issues/262
Please see if that resolves your problem.

**Comment by lmjst** [comment]
It did thanks. But I still have the error (ownCloud server error: Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services. DEBUG OUTPUT: Please check your ownCloud configuration)
and the notes are not synchronised although I've disabled the calendar/todo options.

**Comment by pbek** [comment]
I wonder why CaldDAV is not working for you...
