### ISSUE TITLE
QOwnNotes terminates silently

### ISSUE THREAD

**Issue by Flashwalker** [pbek/QOwnNotes#581]
After i was nave to kill X session, cause it was hang, and relogin to desktop i found what can't start QOwnNotes. Program was terminated silently with no errors with exit code `0` each time i tried to start it.

In short, I found what removing the line: `allowOnlyOneAppInstance=true` from config file makes it work again for me.

#### Expected behaviour
Program tells me wtf happened till dieing

#### Actual behaviour
QOwnNotes was terminates silently until i removed `allowOnlyOneAppInstance=true` line from config file

#### Steps to reproduce
Hmm... I was type: <kbd>Ctrl + Alt + Backspace</kbd> to kill X server, and after relogin was tried to start QOwnNotes

#### Output from the debug section in the settings dialog
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `вс мая 14 05:30:45 2017`
**Version**: `17.05.3`
**Build date**: `May  9 2017`
**Build number**: `333`
**Platform**: `linux`
**Operating System**: `Ubuntu 14.04.5 LTS`
**Build architecture**: `i386`
**Current architecture**: `i386`
**Release**: `OBS`
**Qt Version (build)**: `5.4.1`
**Qt Version (runtime)**: `5.7.1`
**Portable mode**: `no`
**Settings path / key**: `/home/user/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/user/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `ru_RU`
**Locale (interface)**: `ru`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `19`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Note folders

**currentNoteFolderId**: `4`

### Note folder `notes1`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `-1`
**localPath**: `/home/user/Documents/notes1`
**remotePath**: *empty*
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/user/Documents/notes1/notes.sqlite`

### Note folder `notes2`

**id**: `3`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/user/Documents/notes2`
**remotePath**: *empty*
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/user/Documents/notes2/notes.sqlite`

### Note folder `notes`

**id**: `4`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/user/Documents/notes`
**remotePath**: *empty*
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/user/Documents/notes/notes.sqlite`

## Settings

**AboutDialog/geometry**: `<binary data>`
**ActiveNoteHistoryItem**: *empty*
**Debug/fakeOldVersionNumber**: `false`
**Debug/fileLogging**: `true`
**DistractionFreeMode/editorWidthMode**: `1`
**DistractionFreeMode/isEnabled**: `false`
**DistractionFreeMode/menuBarGeometry**: `<binary data>`
**DistractionFreeMode/menuBarHeight**: `19`
**DistractionFreeMode/windowState**: `<binary data>`
**Editor/ColorSchemes**: `EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378`
**Editor/CurrentSchemaKey**: `EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378`
**Editor/autoBracketClosing**: `true`
**Editor/autoBracketRemoval**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColorEnabled_-1**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColorEnabled_0**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColorEnabled_1**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColorEnabled_12**: `false`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColorEnabled_13**: `false`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColorEnabled_14**: `false`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColorEnabled_15**: `false`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColorEnabled_16**: `false`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColorEnabled_17**: `false`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColorEnabled_18**: `false`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColorEnabled_19**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColorEnabled_2**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColorEnabled_21**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColorEnabled_22**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColorEnabled_23**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColorEnabled_3**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColorEnabled_4**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColorEnabled_7**: `false`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColorEnabled_8**: `false`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColor_-1**: `#201f1f`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColor_0**: `#333333`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColor_1**: `#333333`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColor_12**: `#ebebf0`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColor_13**: `#ebebf0`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColor_14**: `#ebebf0`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColor_15**: `#ebebf0`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColor_16**: `#ebebf0`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColor_17**: `#ebebf0`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColor_18**: `#f5f9d8`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColor_19**: `#333333`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColor_2**: `#333333`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColor_21**: `#444444`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColor_22**: `#3e3e44`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColor_23**: `#1a1a1a`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColor_3**: `#646356`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColor_4**: `#1a1a1a`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColor_7**: `#9eb6ff`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/BackgroundColor_8**: `#dbf9e5`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/Bold_12**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/Bold_13**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/Bold_14**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/Bold_15**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/Bold_16**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/Bold_17**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/Bold_8**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/FontSizeAdaption_12**: `120`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/FontSizeAdaption_13**: `110`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_-1**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_0**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_1**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_10**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_11**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_12**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_13**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_14**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_15**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_16**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_17**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_18**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_19**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_2**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_20**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_21**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_22**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_23**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_24**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_3**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_4**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_5**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_6**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_7**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_8**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColorEnabled_9**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_-1**: `#c6c6c6`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_0**: `#fa680c`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_1**: `#fc7e00`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_10**: `#ffff00`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_11**: `#398246`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_12**: `#fdc109`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_13**: `#e3ae09`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_14**: `#c49509`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_15**: `#ad8609`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_16**: `#9d7b09`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_17**: `#8a6c09`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_18**: `#bc3838`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_19**: `#00aa00`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_2**: `#fc7e00`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_20**: `#e1e1e1`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_21**: `#fc970a`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_22**: `#d88109`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_23**: `#d95a0b`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_24**: `#747474`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_3**: `#fdad09`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_4**: `#d95a0b`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_5**: `#e1e1e1`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_6**: `#e1e1e1`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_7**: `#fdc109`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_8**: `#e3ae09`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/ForegroundColor_9**: `#ffff00`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/Italic_18**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/Italic_7**: `true`
**EditorColorSchema-31445cf4-4834-4d5e-bf90-b031fdff4378/Name**: `AnalyticalYellow (My)`
**FileDialog/LastPath**: `/home/user/Desktop`
**FileDialog/LastPath-SaveDebugInfo**: `/home/user/Desktop`
**LastUpdateCheck**: `2017-05-14T05:29:35`
**LinkDialog/geometry**: `<binary data>`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `17`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `Monospace,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl**: `false`
**MainWindow/showNotesFromAllNoteSubFolders**: `false`
**NoteDialog/geometry**: `<binary data>`
**NoteSortOrder**: `0`
**PiwikClientId**: `<hidden>`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**ShowSystemTray**: `false`
**SortingModeAlphabetically**: `false`
**StartHidden**: `false`
**TagAddDialog/geometry**: `<binary data>`
**WelcomeDialog/geometry**: `<binary data>`
**acceptAllExternalModifications**: `false`
**allowDifferentNoteFileName**: `false`
**appMetrics/disableAppHeartbeat**: `true`
**appMetrics/disableTracking**: `true`
**appMetrics/notificationShown**: `true`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `4`
**currentWorkspace**: `d6419ed5-7558-4e66-97fd-48c0e952c51b`
**customNoteFileExtensionList**: *empty*
**darkMode**: `true`
**darkModeColors**: `true`
**darkModeTrayIcon**: `true`
**defaultNoteFileExtension**: `md`
**demoNotesCreated**: `true`
**disableAutomaticUpdateDialog**: `true`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: `textadept`
**gitCommitInterval**: `30`
**gitExecutablePath**: *empty*
**gitLogCommand**: *empty*
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**imageScaleDown**: `false`
**imageScaleDownMaximumHeight**: `1024`
**imageScaleDownMaximumWidth**: `1024`
**insertTimeFormat**: *empty*
**interfaceLanguage**: `ru`
**internalIconTheme**: `true`
**itemHeight**: `20`
**markdownHighlightingEnabled**: `true`
**networking/ignoreSSLErrors**: `true`
**networking/proxyHostName**: `127.0.0.1`
**networking/proxyNeedsAuth**: `false`
**networking/proxyPassword**: `<hidden>`
**networking/proxyPort**: `127`
**networking/proxyType**: `2`
**networking/proxyUser**: *empty*
**noteSaveIntervalTime**: `10`
**notesPath**: `/home/user/Documents/notes`
**notifyAllExternalModifications**: `true`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: *empty*
**ownCloud/supportEnabled**: `false`
**ownCloud/todoCalendarBackend**: `1`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloud/userName**: *empty*
**previousWorkspace**: `98840265-b52b-4f5c-8c6f-937cfca44feb`
**recentNoteFolders**: `/home/user/Documents/notes1, /home/user/Documents/notes2, /home/user/QOwnNotes/Notes`
**restoreCursorPosition**: `true`
**savedSearches/noteFolder-1**: `Note 2017-05-13T06.34.50, Note 2017-05-11T19.41.26, Note 2017-05-11T18.55.28, Note 2017-05-06T05.26.13, Note 2017-05-06T05.25.52, Note 2017-04-29T04.54.36, Note 2017-04-29T04.51.30, Note 2017-04-29T04.50.30, Note 2017-04-29T04.47.55, Note 2017-04-29T04.47.41, Note 2017-04-29T04.47.06, Note 2017-04-29T04.45.21, Note 2017-04-29T04.44.50, Note 2017-04-29T04.43.55, Note 2017-04-29T04.17.14, Note 2017-04-29T04.16.36, Note 2017-04-29T04.15.36, Note 2017-04-29T04.13.59, Note 2017-04-29T04.08.15, Note 2017-04-29T04.07.37, Note 2017-04-29T04.06.37, Note 2017-04-29T04.05.50, Note 2017-04-29T04.04.35, Note 2017-04-29T04.04.12, Note 2017-04-29T04.03.28, Note 2017-04-29T04.01.28, Note 2017-04-29T03.59.46, Note 2017-04-29T03.33.47, Note 2017-04-29T03.33.08, Note 2017-04-29T03.32.47, Note 2017-04-29T03.29.30, Note 2017-04-29T03.28.49, Note 2017-04-29T03.27.48, Note 2017-04-29T03.26.12, Note 2017-04-29T03.26.00, Note 2017-04-29T03.25.30, Note 2017-04-29T03.25.14, Note 2017-04-29T03.24.21, Note 2017-04-29T03.23.54, Note 2017-04-29T03.21.47, Note 2017-04-29T03.20.11, Note 2017-04-29T03.19.17, Note 2017-04-29T03.18.05, Note 2017-04-29T03.17.47, Note 2017-04-29T01.49.54, Note 2017-04-29T01.49.42, Note 2017-04-29T01.49.16, Note 2017-04-29T01.46.58, Note 2017-04-29T01.46.39, Note 2017-04-29T01.46.28, Note 2017-04-29T01.46.08, Note 2017-04-29T01.45.43, Note 2017-04-29T01.44.54, Note 2017-04-29T01.44.42, Note 2017-04-29T01.44.21, Note 2017-04-29T01.42.33, Note 2017-04-29T01.41.33, Note 2017-04-29T01.40.45, Note 2017-04-29T01.40.13, Note 2017-04-29T01.36.44, Note 2017-04-29T01.36.11, Note 2017-04-29T01.34.09, Note 2017-04-29T01.17.55, Note 2017-04-28T01.18.13, Note 2017-04-13T04.48.22`
**savedSearches/noteFolder-3**: `Note 2017-01-05T12.01.00, Note 2017-01-05T11.23.16`
**savedSearches/noteFolder-4**: `Note 2017-05-14T02.26.24, Note 2017-05-13T13.14.54, Note 2017-05-12T21.29.51, Note 2017-05-12T21.29.27, Note 2017-05-12T21.28.51, Note 2017-05-12T21.27.20, Note 2017-05-12T21.26.25, Note 2017-05-12T21.25.57, Note 2017-05-12T21.25.27, Note 2017-05-12T21.25.03, Note 2017-05-12T21.24.12, Note 2017-05-12T21.21.42, Note 2017-05-12T21.20.32, Note 2017-05-12T21.19.51, Note 2017-05-12T21.17.40, Note 2017-05-12T20.23.22, Note 2017-05-12T17.38.18`
**showMenuBar**: `true`
**showStatusBar**: `true`
**tagWasAddedToNote**: `true`
**toolbar/1/items**: `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name**: `mainToolBar`
**toolbar/1/title**: `Главная панель инструментов`
**toolbar/2/items**: `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name**: `formattingToolbar`
**toolbar/2/title**: `панель инструментов форматирования`
**toolbar/3/items**: `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name**: `insertingToolbar`
**toolbar/3/title**: `панель инструментов вставки`
**toolbar/4/items**: `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name**: `encryptionToolbar`
**toolbar/4/title**: `панель инструментов шифрования`
**toolbar/5/items**: `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name**: `windowToolbar`
**toolbar/5/title**: `панель инструментов окна`
**toolbar/6/items**: *empty*
**toolbar/6/name**: `quitToolbar`
**toolbar/6/title**: `Панель инструментов выхода`
**toolbar/size**: `6`
**useUNIXNewline**: `false`
**workspace-98840265-b52b-4f5c-8c6f-937cfca44feb/name**: `минимальный`
**workspace-98840265-b52b-4f5c-8c6f-937cfca44feb/noteSubFolderDockWidgetVisible**: `true`
**workspace-98840265-b52b-4f5c-8c6f-937cfca44feb/windowState**: `<binary data>`
**workspace-d6419ed5-7558-4e66-97fd-48c0e952c51b/name**: `на весь экран`
**workspace-d6419ed5-7558-4e66-97fd-48c0e952c51b/noteSubFolderDockWidgetVisible**: `true`
**workspace-d6419ed5-7558-4e66-97fd-48c0e952c51b/windowState**: `<binary data>`
**workspaces**: `d6419ed5-7558-4e66-97fd-48c0e952c51b, 98840265-b52b-4f5c-8c6f-937cfca44feb`

## System environment

**XDG_VTNR**: `7`
**INFINALITY_FT_AUTOHINT_HORIZONTAL_STEM_DARKEN_STRENGTH**: `10`
**UDEdir**: *empty*
**XDG_SESSION_ID**: `1`
**SSH_AGENT_PID**: `12311`
**CLUTTER_IM_MODULE**: `xim`
**rvm_bin_path**: `/usr/share/rvm/bin`
**GPG_AGENT_INFO**: `/tmp/gpg-fTeJBv/S.gpg-agent:20289:1`
**GEM_HOME**: `/home/user/.rvm/gems/ruby-2.3.0`
**INFINALITY_FT_BOLD_EMBOLDEN_X_VALUE**: `0`
**SHELL**: `/bin/bash`
**INFINALITY_FT_AUTOHINT_VERTICAL_STEM_DARKEN_STRENGTH**: `25`
**TERM**: `linux`
**XDG_SESSION_COOKIE**: `8288b715b0334cf99be115df545f422a-1494710662.627748-1303997665`
**IRBRC**: `/usr/share/rvm/rubies/ruby-2.3.0/.irbrc`
**PERL5LIB**: `/home/user/perl5/lib/perl5:/home/user/perl5/lib/perl5:`
**QTDIR**: `/opt/qt57`
**GNOME_KEYRING_CONTROL**: `/run/user/1000/keyring-0Nxv6Q`
**MY_RUBY_HOME**: `/usr/share/rvm/rubies/ruby-2.3.0`
**PERL_MB_OPT**: `--install_base "/home/user/perl5"`
**GTK_MODULES**: `gtk-vector-screenshot`
**SWT_GTK3**: `0`
**INFINALITY_FT_CONTRAST**: `15`
**INFINALITY_FT_GRAYSCALE_FILTER_STRENGTH**: `0`
**USER**: `user`
**LD_LIBRARY_PATH**: `/opt/qt57/lib/i386-linux-gnu:/opt/qt57/lib:`
**QT_ACCESSIBILITY**: `1`
**_system_type**: `Linux`
**rvm_path**: `/usr/share/rvm`
**SSH_AUTH_SOCK**: `/tmp/ssh-rEWzrZTlt1Lb/agent.12310`
**INFINALITY_FT_FRINGE_FILTER_STRENGTH**: `0`
**INFINALITY_FT_BRIGHTNESS**: `-10`
**INFINALITY_FT_USE_VARIOUS_TWEAKS**: `true`
**INFINALITY_FT_GAMMA_CORRECTION**: `1000 80`
**rvm_prefix**: `/usr/share`
**PATH**: `/opt/qt57/bin:/home/user/bin:/home/user/perl5/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/heroku/bin:/home/user/bin:/home/user/perl5/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/heroku/bin:/home/user/.rvm/gems/ruby-2.3.0/bin:/home/user/.rvm/gems/ruby-2.3.0@global/bin:/usr/share/rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/rvm/bin`
**MAIL**: `/var/mail/user`
**QT_IM_MODULE**: `xim`
**PWD**: `/home/user`
**XMODIFIERS**: `@im=fcitx`
**EDITOR**: `vim`
**INFINALITY_FT_FILTER_PARAMS**: `11 22 38 22 11`
**LANG**: `ru_RU.UTF-8`
**GNOME_KEYRING_PID**: `20030`
**INFINALITY_FT_USE_KNOWN_SETTINGS_ON_SELECTED_FONTS**: `false`
**INFINALITY_FT_STEM_SNAPPING_SLIDING_SCALE**: `0`
**INFINALITY_FT_WINDOWS_STYLE_SHARPENING_STRENGTH**: `0`
**_system_arch**: `i386`
**INFINALITY_FT_CHROMEOS_STYLE_SHARPENING_STRENGTH**: `0`
**INFINALITY_FT_AUTOHINT_SNAP_STEM_HEIGHT**: `0`
**INFINALITY_FT_STEM_ALIGNMENT_STRENGTH**: `0`
**_system_version**: `17`
**rvm_version**: `1.27.0 (latest)`
**HOME**: `/home/user`
**SHLVL**: `0`
**XDG_SEAT**: `seat0`
**INFINALITY_FT_BOLD_EMBOLDEN_Y_VALUE**: `0`
**GNOME_DESKTOP_SESSION_ID**: `default`
**PERL_LOCAL_LIB_ROOT**: `/home/user/perl5:/home/user/perl5:`
**CUR_WIDTH**: `71`
**INFINALITY_FT_GLOBAL_EMBOLDEN_Y_VALUE**: `0`
**LOGNAME**: `user`
**GEM_PATH**: `/home/user/.rvm/gems/ruby-2.3.0:/home/user/.rvm/gems/ruby-2.3.0@global`
**DBUS_SESSION_BUS_ADDRESS**: `unix:abstract=/tmp/dbus-scgJaULLMv,guid=8d016516c4d66ceea8a0f7d65917798c`
**QT4_IM_MODULE**: `xim`
**INFINALITY_FT_STEM_FITTING_STRENGTH**: `0`
**PKG_CONFIG_PATH**: `/opt/qt57/lib/pkgconfig:`
**GTK_CSD**: `1`
**INFINALITY_FT_AUTOHINT_INCREASE_GLYPH_HEIGHTS**: `false`
**TEXTDOMAIN**: `im-config`
**DISPLAY**: `:0.0`
**INFINALITY_FT_GLOBAL_EMBOLDEN_X_VALUE**: `0`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**GTK_IM_MODULE**: `xim`
**NO_AT_BRIDGE**: `1`
**RUBY_VERSION**: `ruby-2.3.0`
**_system_name**: `Mint`
**TEXTDOMAINDIR**: `/usr/share/locale/`
**PERL_MM_OPT**: `INSTALL_BASE=/home/user/perl5`
**XAUTHORITY**: `/home/user/.Xauthority`

#### Relevant log output (you have to enable enable the log widget)
```
...
[мая 14 03:53:44] [status]: На диск сохранено 1 заметок
[мая 14 04:20:49] [warning]: QFSFileEngine::open: No file name specified
[мая 14 04:20:49] [warning]: QFSFileEngine::open: No file name specified
[мая 14 04:20:49] [warning]: QFSFileEngine::open: No file name specified
[мая 14 04:20:49] [warning]: QFSFileEngine::open: No file name specified
[мая 14 04:20:49] [warning]: QFSFileEngine::open: No file name specified
[мая 14 04:20:49] [warning]: QFSFileEngine::open: No file name specified
[мая 14 04:20:49] [warning]: QFSFileEngine::open: No file name specified
[мая 14 04:20:49] [warning]: QFSFileEngine::open: No file name specified
[мая 14 04:20:49] [warning]: QFSFileEngine::open: No file name specified
[мая 14 04:20:49] [warning]: QFSFileEngine::open: No file name specified
[мая 14 04:20:49] [warning]: QFSFileEngine::open: No file name specified
[мая 14 04:20:49] [warning]: QFSFileEngine::open: No file name specified
[мая 14 04:20:49] [warning]: QFSFileEngine::open: No file name specified
[мая 14 04:20:49] [warning]: QFSFileEngine::open: No file name specified
[мая 14 04:20:49] [warning]: QFSFileEngine::open: No file name specified
[мая 14 04:20:49] [warning]: QFSFileEngine::open: No file name specified
[мая 14 04:20:49] [warning]: QFSFileEngine::open: No file name specified
[мая 14 04:20:49] [warning]: QFSFileEngine::open: No file name specified
[мая 14 04:24:05] [warning]: The X11 connection broke: I/O error (code 1)
```

**Comment by pbek** [comment]
On very rare occasion `allowOnlyOneAppInstance` seems to do that on some systems. It may have to do with the system having problems with the mutex that is created to make sure the app can't be executed an other time. I cannot reproduce that because it depends on the target system.

If you want to experiment it in the source code you can take a look at <https://github.com/pbek/QOwnNotes/blob/develop/src/main.cpp#L276> (look out for `SingleApplication`).

**Comment by pbek** [comment]
That's the library used: <https://github.com/pbek/QOwnNotes/tree/develop/src/libraries/singleapplication>
