### ISSUE TITLE
Gentoo: doesn't compile with FEATURES="distcc"

### ISSUE THREAD

**Issue by internethering** [pbek/QOwnNotes#582]
Hey, I'm using distcc (https://wiki.gentoo.org/wiki/Distcc) and compilation fails with this error:

```
aboutdialog.cpp:(.text+0x1dd): undefined reference to `QIcon::fromTheme(QString const&)'
collect2: error: ld returned 1 exit status
distcc[9239] ERROR: compile (null) on localhost failed
```

Here is the complete build.log: https://paste.pound-python.org/show/Rgk3oYc12Inf4LChOxDr

If I disable distcc, than it compiles fine :)

**Comment by pbek** [comment]
Is there anything I can do about it or something you want to commit as pull-request?

**Comment by pbek** [comment]
I will close this issue until there is more information.
