### ISSUE TITLE
Menu position when using QOwnNotes on second monitor

### ISSUE THREAD

**Issue by ryliejamesthomas** [pbek/QOwnNotes#584]
I've been keeping QOwnNotes pinned to my second monitor, and have recently noticed some odd menu behaviour.

I experimented with--not sure of the work for it, but--split monitor setup, where the second it higher than the first, like this:

![screenshot_area_16-05-17_22-42-56-1](https://cloud.githubusercontent.com/assets/25972447/26106499/6ea9f7e8-3a89-11e7-85aa-3a9cd9023b9a.png)

QOwnNotes is on 'Monitor', and I notice that when I select any of the menu items (Note, Edit, Tag, etc.) the menu doesn't appear up top of the screen, but down the bottom, aligned with the top of the 'Laptop' monitor (but still on 'Monitor' when QOwnNotes is).

Imagemagick doesn't seem to want to capture the screen when I've got the menus open, but I hope that's clear.

When the displays are not configured as split it works as expected.

It may be an XFCE problem, but I haven't noticed it in any other programs.

**Comment by pbek** [comment]
I'm sorry, I haven't seen that anywhere yet. Maybe it's an Qt issue on XFCE. QOwnNotes is only using the default Qt menu system...
Do you use an other Qt or KDE application to see if it works there?

**Comment by ryliejamesthomas** [comment]
Just downloaded something, and it appears to be a QT-on-XFCE problem.

Feel free to close this issue.

**Comment by pbek** [comment]
I've no problem under KDE on a multi-monitor setup. ;)
