### ISSUE TITLE
WebEngine

### ISSUE THREAD

**Issue by 0ldbie** [pbek/QOwnNotes#585]
Do you plan to implement QT WebEngine ot full featured web page render? It will be very useful -- store notes in html+css and making it from www.

**Comment by pbek** [comment]
Yes, I want to do that in the future... But right now we need to support Qt 5.2 and QtWebEngine (Qt 5.4+) is only usable (printing support, etc.) in current versions of Qt. And of course QOwnNotes would need a lot more memory, cpu and diskspace if we use QtWebEngine...
