### ISSUE TITLE
monospace font customization

### ISSUE THREAD

**Issue by elnull** [pbek/QOwnNotes#59]
Is it possible to add an option to customize monospace font?

**Comment by pbek** [comment]
You can select the fonts for the note edit view and the markdown view. What that what you were looking for?

**Comment by elnull** [comment]
I'm looking for possibility to change monospace font face in markdown viewer.
Also it would be helpful that source code in editor will be written with monospace font.

**Comment by pbek** [comment]
I think I fail to understand your question. You can select every font you want in the **general settings**.

**Comment by pbek** [comment]
Or do you mean to select the font of individual parts of the markdown highlighting?

**Comment by elnull** [comment]
Yes, parts of text wrapped in backtick quotes (`) and blocks of source code are looking better when written with monospace font. Your markdown viewer is using monospace font in that case. So can you add an on option to change font face for that case?

**Comment by pbek** [comment]
I also had such a thing in mind. It's still on my (very long) todo list. :smile: 
Thank you for your reminder. I will keep it as reference and will notify you in this issue on the progress.

**Comment by pbek** [comment]
In v0.95 code in the Markdown edit will now use the `Courier` font, could you be so kind and report if everything was to your liking when the version is released?

**Comment by pbek** [comment]
Version 0.95 is now out.

**Comment by elnull** [comment]
I checked 0.95 and found that editor now use monospace font where it should be. It looks much more comfortable. Thank you. Can you also add an option to change monospace font face?

**Comment by pbek** [comment]
Yes, I have planed that for the future.

**Comment by pbek** [comment]
In the current version 0.96 you can now select a code font and reset each font. Can you please be so kind and report back if it works as intended.

**Comment by elnull** [comment]
It works for me. Thank you for support.

**Comment by elnull** [comment]
There is small issue left. New font face applies to editor but viewer still uses only Courier.

**Comment by pbek** [comment]
The viewer has his own fonts. I'll see what I can do.
What country are you from (or what language/s do you speak)? Maybe you want to consider a translation of QOwnNotes. :wink: 
<http://www.qownnotes.org/Knowledge-base/How-can-I-help-to-translate-QOwnNotes>

**Comment by pbek** [comment]
Because you did such a great job with the Russian translation and delivered valuable insights I now implemented that the code font in the note Markdown view can be configured in the settings (with the help of some QFont to CSS magic). :smile_cat: 
It will be shortly released with **version 1.0**.

Can you please be so kind and report back how it worked out for you.

**Comment by elnull** [comment]
I checked new version. All font customizations are working fine. Thank you for support!

**Comment by pbek** [comment]
You are very welcome! Thank you for your translation and your continuous effort!
