### ISSUE TITLE
Feature request: display of notes in a panel with folders

### ISSUE THREAD

**Issue by Aquinary** [pbek/QOwnNotes#590]
Hi.
Now notes are displayed in a separate panel.
Sometimes it happens not really convenient. It would be very desirable to have an opportunity to open the folder and to see the dropdown list of the existing notes from below... not in a separate panel, and directly under the folder.
Thanks for attention :)

**Comment by pbek** [comment]
I'm sorry, that usually doesn't work for a lot of notes in a subfolder and was discussed in several issues, I just found #303.

**Comment by pbek** [comment]
Please head over to #790 for an update on a note tree in the note list panel.
