### ISSUE TITLE
Markdown math

### ISSUE THREAD

**Issue by andreasjacobsen93** [pbek/QOwnNotes#593]
Would it be possible to add markdown handling of math, like:
$$x_{1,2} = \frac{-b \pm \sqrt{b^2-4ac}}{2b}.$$
$$a^2 + b^2 = c^2$$
etc.

**Comment by pbek** [comment]
Most unlikely, please see #377 and #400.
But there is a script for pasting Latex code as an image in the scripting repository if that would fit your needs.
