### ISSUE TITLE
Expose creation/updated date/time via scripting API

### ISSUE THREAD

**Issue by msbentley** [pbek/QOwnNotes#599]
I may have missed this in the docs, but are the note creation and update times available anywhere via the scripting API? I couldn't see it in the NoteApi object. I was hoping to make a first foray into the world of QOwnNote scripting by making a simple script that displays some note info including the creation date, updated date, folder etc.

**Comment by pbek** [comment]
It would probably best to take that from the note file directly. You could do that with your operating system's tools or wait till I put something together...

**Comment by pbek** [comment]
## 17.06.2
- there are now new properties for notes in the scripting engine `fileCreated` and `fileLastModified` 
  - you can use the methods from [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) to work with these date properties
  - for more information please take a look at the [scripting documentation](http://docs.qownnotes.org/en/develop/scripting/README.html#note)

**Comment by msbentley** [comment]
Great! Does this take the info directly from the files, or is it also stored in the database? 

A related issue is whether it may be possible to set these attributes when importing Evernote files. There is obviously a lot of "information" in the created/updated dates of my notes, which is given in the .enex file and I was wondering if this could be preserved...

**Comment by pbek** [comment]
The information is initially loaded from the note files and then stored to the in-memory note database.
This database is rebuilt every time QOwnNotes starts or when the note folder gets updated...
So we can't store information from the Evernote entries there... The only persistent artifact is the note markdown file.

**Comment by msbentley** [comment]
OK, understood. I guess I could use a script to spawn `touch`, for example, and set the modified time of the file according to a list generated from my .exex or similar.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by msbentley** [comment]
That works great, many thanks! It did raise a question, though... Can QON have >1 script widget for output? I was basically wondering if one could create multiple panels to display different content, docked at different places in the QON window.

Also, is there a way to define the order in which scripts are run - at the moment it looks like the order they have in the "Your scripts" list? (e.g. I have two scripts triggering on noteOpenedHook, and judging by the order of output in the script widget they run in the order of the list).

**Comment by pbek** [comment]
No, there is just one widget (it's a lot of work to code one that does everything we need it to do) but you can with as many scripts to it as you like...

No, currently you can't change the order in the UI, but there already is a `priority` column in the `script` table in your QOwnNotes sqlite database. You could change the priority there... ;)
`ORDER BY priority ASC, id ASC`

**Comment by msbentley** [comment]
Great, thanks!
