### ISSUE TITLE
Crash while opening an empty note

### ISSUE THREAD

**Issue by TtuxX** [pbek/QOwnNotes#6]
Qownnotes (0.22 at least) seems to crash when trying to open an empty note (with file content size = 0 bytes), and does not even start if the first note of the list is an empty one.

Crash log:
`qownnotes: libraries/hoedown/buffer.c :98 : hoedown_buffer_grow:  the assertion « buf && buf->unit » has failed.`

Empty files can be opened as long as their sizes are superior to 0 bytes.
It might be worth adding a condition/check to make it more flexible in front of such situations.

Can anyone confirm this bug ?
@pbek

**Comment by pbek** [comment]
Thank you for reporting @TtuxX ! I will see if I can reproduce the bug.

**Comment by pbek** [comment]
This issue should be fixed now, thank you again for mentioning it, @TtuxX!
