### ISSUE TITLE
Segmentationfault

### ISSUE THREAD

**Issue by LEDfan** [pbek/QOwnNotes#60]
Hi, I get a segmentation fault when switching between notes folders.

## Steps to reproduce:
 1. open qownnotes
 2. select another notes folder from the recent folder list (`Note` -> `Recent notes folder`)
 3. open a note in this folder
 4. go back to the older folder via the same menu option
 
Now sometimes I get a segmenation fault but not always....

**Comment by pbek** [comment]
Hm, I couldn't reproduce that crash. Which operating system are you using?

**Comment by pbek** [comment]
I cannot reproduce this on OS X 10.11, Manjaro Linux 15.12 and Ubuntu Linux 15.10.

**Comment by pbek** [comment]
Do you have a stack trace of your seg fault?

**Comment by LEDfan** [comment]
````
(gdb) run
Starting program: /usr/bin/QOwnNotes 
Got object file from memory but can't read symbols: File truncated.
Missing separate debuginfos, use: zypper install qownnotes-debuginfo-0.92-1.1.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffeb51a700 (LWP 5627)]
[New Thread 0x7fffdb776700 (LWP 5629)]
[Thread 0x7fffdb776700 (LWP 5629) exited]
[New Thread 0x7fffdb776700 (LWP 5630)]
[Thread 0x7fffdb776700 (LWP 5630) exited]
[New Thread 0x7fffdb776700 (LWP 5631)]
[New Thread 0x7fffda8ee700 (LWP 5632)]
Detaching after fork from child process 5633.
[New Thread 0x7fffd8c8d700 (LWP 5634)]
[Thread 0x7fffd8c8d700 (LWP 5634) exited]
[New Thread 0x7fffd8c8d700 (LWP 5635)]
[Thread 0x7fffd8c8d700 (LWP 5635) exited]
[New Thread 0x7fffd8c8d700 (LWP 5636)]
[New Thread 0x7fffcbfff700 (LWP 5637)]
[New Thread 0x7fffcb7fe700 (LWP 5638)]
replyFinished error:  "Connection refused" 

replyFinished error:  "Connection refused" 

replyFinished error:  "Connection refused" 

replyFinished error:  "Connection refused" 

[New Thread 0x7fffca7f9700 (LWP 5639)]
replyFinished error:  "Connection refused" 

[New Thread 0x7fffc9a14700 (LWP 5640)]
[Thread 0x7fffc9a14700 (LWP 5640) exited]
[New Thread 0x7fffc9a14700 (LWP 5641)]
[Thread 0x7fffc9a14700 (LWP 5641) exited]
Detaching after fork from child process 5642.
[New Thread 0x7fffc9a14700 (LWP 5663)]
[Thread 0x7fffc9a14700 (LWP 5663) exited]
replyFinished error:  "Connection refused" 

[New Thread 0x7fffc9a14700 (LWP 5664)]
[Thread 0x7fffc9a14700 (LWP 5664) exited]
replyFinished error:  "Connection refused" 

[New Thread 0x7fffc9a14700 (LWP 5665)]
[Thread 0x7fffc9a14700 (LWP 5665) exited]
replyFinished error:  "Connection refused" 

replyFinished error:  "Connection refused" 

[New Thread 0x7fffc9a14700 (LWP 5666)]
[Thread 0x7fffc9a14700 (LWP 5666) exited]
[New Thread 0x7fffc9a14700 (LWP 5667)]
[Thread 0x7fffc9a14700 (LWP 5667) exited]
replyFinished error:  "Connection refused" 

[New Thread 0x7fffc9a14700 (LWP 5669)]
[Thread 0x7fffc9a14700 (LWP 5669) exited]
[New Thread 0x7fffc9a14700 (LWP 5671)]
[Thread 0x7fffc9a14700 (LWP 5671) exited]
replyFinished error:  "Connection refused" 

[New Thread 0x7fffc9a14700 (LWP 5672)]
[Thread 0x7fffc9a14700 (LWP 5672) exited]
[New Thread 0x7fffc9a14700 (LWP 5673)]
[Thread 0x7fffc9a14700 (LWP 5673) exited]
replyFinished error:  "Connection refused" 

[New Thread 0x7fffc9a14700 (LWP 5674)]
[Thread 0x7fffc9a14700 (LWP 5674) exited]
replyFinished error:  "Connection refused" 

[New Thread 0x7fffc9a14700 (LWP 5675)]
replyFinished error:  "Connection refused" 

[Thread 0x7fffc9a14700 (LWP 5675) exited]
[New Thread 0x7fffc9a14700 (LWP 5676)]
[Thread 0x7fffc9a14700 (LWP 5676) exited]
replyFinished error:  "Connection refused" 

[New Thread 0x7fffc9a14700 (LWP 5677)]
[Thread 0x7fffc9a14700 (LWP 5677) exited]
replyFinished error:  "Connection refused" 

[New Thread 0x7fffc9a14700 (LWP 5678)]
[Thread 0x7fffc9a14700 (LWP 5678) exited]
[Thread 0x7fffcbfff700 (LWP 5637) exited]
[New Thread 0x7fffcbfff700 (LWP 5680)]
[Thread 0x7fffcbfff700 (LWP 5680) exited]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6dabe3b in QTextLayout::additionalFormats() const ()
   from /usr/lib64/libQt5Gui.so.5
(gdb) quit
A debugging session is active.

	Inferior 1 [process 5623] will be killed.

Quit anyway? (y or n) y
```
This is the only information I can provide by running the program via `gdb`. I guess I should compile it with debug info.However most of the time I can't reproduce this error.

I'm running `OpenSUSE 13.2`

**Comment by pbek** [comment]
Can you please provide the first block (General Info) of the **QOwnNotes Debug Information** from the settings dialog?

**Comment by LEDfan** [comment]
Oh. I just found a crucial step in reproducing the error!
New steps:
1. open qownnotes
2. create a new note in the current active notes folder
3. change the notes folder to a new directory
4. the just created note will appear in the just selected notes folder. (This is a bug maybe?) and a older note will note be showed
5. delete the note
6. change the folder again, now sometimes a segmenation fault will occur 

````
## General Info

**Current Date**: `zo feb. 7 09:20:24 2016`
**Version**: `0.93`
**Build date**: `Feb  7 2016`
**Build number**: `93`
**Platform**: `linux`
**Operating System**: `openSUSE 13.2 (Harlequin) (x86_64)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version**: `5.4.2`
````

**Comment by pbek** [comment]
Thank you.
I can reproduce the bug with just created note in the switched folder. (I'm already trying to get a hold of that one) But I still can make it crash...
I'm testing under `openSUSE Leap 42.1 (x86_64)` with v0.93 now...

**Comment by pbek** [comment]
Version 0.94 is out now where I fixed the problem with a wrong note showing up after you change your note folder. Can you please confirm if this is now working for you and if this fix also had an impact on your seg fault.

**Comment by LEDfan** [comment]
The bug with the wrong note showing up is solved as far I can see. But I still get some segmenation faults now and then. But I can't reproduce them all the time.

**Comment by pbek** [comment]
You don't by any chance care to install Qt Creator and run QOwnNotes in debug mode to see what command crashed it? That would be a tremendous help!

There you would find instructions: <http://www.qownnotes.org/installation#building>
Of course you can install qt creator directly with zypper...

**Comment by pbek** [comment]
There are now debug info RPMs for Open Leap for QOwnNotes. Would you mind installing it and then see if you can get a stack trace of the crash.

<https://build.opensuse.org/package/binaries/home:pbek:QOwnNotes/desktop?repository=openSUSE_13.2>

**Comment by pbek** [comment]
:question: :smiling_imp:

**Comment by LEDfan** [comment]
Hi, I installed the debuginfo package. (Good that you provide this now, in OpenSUSE there are a lot of packages like this). And now when I use your notes app I run it from a terminal however I don't encounter any segfaults anymore.

I'm quite sure it was caused by changing folder in combination with the bug that was fixed above.

Congrats with your 1.0 release! BTW will you be using semantic versioning?

**Comment by pbek** [comment]
Thank you for checking and your congratulations. :smile_cat: 
About the semantic versioning... I planned to continue with 1.0.1 up to 1.0.9 and then 1.1... But now that you mention it, the third part would be the patch version, what wouldn't be true... Hm, any ideas?
