### ISSUE TITLE
Option to set cursor to note title in new notes

### ISSUE THREAD

**Issue by msbentley** [pbek/QOwnNotes#601]
When I create a new note (usually by keyboard shortcut) the first thing I typically want to do is add the title. Currently the cursor is positioned after the automatically generated title. It would be great to have an option which either (a) does not insert an auto title, but positions the cursor above the '===' separator or (b) inserts but also selects the title. In either case my desired workflow would be 

1. hit ctrl+n, 
2. type title, 
3. hit pgdn/end to move to the body and continue typing.

I understand there are issues of unique filenames here, but I guess this is already handled? At least if I try to create a duplicate name now it looks like QON appends the date/time string to my name to make it unique?

**Comment by pbek** [comment]
You can set the headline in a script, did you take a look at: <http://docs.qownnotes.org/en/develop/scripting/README.html#handlenewnoteheadlinehook>?

**Comment by pbek** [comment]
You could also write a custom action to create your note all by yourself with <http://docs.qownnotes.org/en/develop/scripting/README.html#creating-a-new-note>.

**Comment by msbentley** [comment]
Thanks, I'll take a look at those!

**Comment by pbek** [comment]
Also keep in mind that you can press `Ctrl+Shift+F` to get to the note search bar and enter the title of your new note there (and then press `Return` to create that note), that's basically what you want. `Ctrl+N` is for quickly creating a new note and immediately start to write down what was on your mind.
