### ISSUE TITLE
Feature request: Different tag system

### ISSUE THREAD

**Issue by ClarkeCC** [pbek/QOwnNotes#603]
I really like Bear (http://www.bear-writer.com/faq/Tags%20&%20Linking/Nested%20Tags/) and Zim Wiki (http://zim-wiki.org/manual/Help/Tags.html) tags. They can use # or @ in the text it self to make a tag. You can also easily pick and search which tags you would like to filter.

**Comment by Maboroshy** [comment]
I guess it can be done by scripting. The script can find all the `#` and `@` stuff and add/remove appropriate tags.

**Comment by Maboroshy** [comment]
The hard part is that it would also have to add/remove `#` or `@` for a tag added/removed the old way. That can't be done without some direct note file altering dependency, as far as I know. But still possible.

**Comment by pbek** [comment]
Yes, this would be the 5th or 6th request for a different way of tagging (and all requests are different). :) Should best be done with the scripting engine. :) If we need anything in the scripting engine for that you can write a feature request for that...

**Comment by pbek** [comment]
## 17.09.6
- added the first alpha version of external note tagging support via the 
  scripting engine (for [Issue #323](https://github.com/pbek/QOwnNotes/issues/323), [Issue #338](https://github.com/pbek/QOwnNotes/issues/338), [Issue #379](https://github.com/pbek/QOwnNotes/issues/379), [Issue #472](https://github.com/pbek/QOwnNotes/issues/472), [Issue #530](https://github.com/pbek/QOwnNotes/issues/530) and [Issue #603](https://github.com/pbek/QOwnNotes/issues/603))
    - as soon as a script is activated that implements the new function
      `noteTaggingHook` note tagging will be handled by that function
    - please install the script [note-tagging.qml](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/note-tagging.qml)
      to test the basic functionality and report in [Issue #530](https://github.com/pbek/QOwnNotes/issues/530).
        - your internal tag database and your notes might get modified 
        - don't use this script on your production note folder, please make a 
          copy of it and test it there!
    - following features should already work via the QOwnNotes user interface
        - initially importing tags like `@tag` from your notes and overwriting
          your current tag assignment
            - you will not loose your tags tree, just the former assignment to notes
            - you can still move tags into other tags
            - if more than one tag has the same name in your tag tree the 
              first hit will be assigned
        - adding a tag to a note will add the tag to the note text        
        - removing a tag from a note will remove the tag from the note text
        - removing of tags in the tag list will remove those tags from your notes
        - renaming of tags in the tag list will rename those tags in your notes
        - bulk tagging of notes in the note list will add those tags to your notes
        - bulk removing of tags from notes in the note list will remove those 
          tags from your notes
    - for more information please take a look at the [scripting documentation](http://docs.qownnotes.org/en/develop/scripting/README.html#noteTaggingHook)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you with the script [note-tagging.qml](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/note-tagging.qml)?
