### ISSUE TITLE
Scripting limitations

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#604]
I'm hacking hard to prepare my old "pin note" script for pulling in to repository. It's not that complex script. Basically all it does is renaming a note. But, since scripting engine does not allow it, that becomes hacky. 

What I did is renaming current note file externally by OS. And it worked but had a side effect - since renamed file is a new note, it loses tag data. I decided to fix this before pulling the script in.

It supposed to be easy. Fetch for a new note after renaming and tag it with the tags of the old one. But we only have a function to tag current note. Jumping to new note haven't worked out, because new note must be in the list to jump to it. The list refreshes only after the script runs out. I've tried putting the sleep timer before jumping, to give the app time to refresh the list, but it doesn't. It sleeps with the timer, the script runs out, and then it refreshes the list. So currently you can't make the note externally and jump to it within one script.

I didn't give up. If OS can't properly make new note, the app can. But it turned out the `script.createNote` is quite an ancient thing. It doesn't allow to name a note file.

So the only way to overcome current limitations is working directly with tag data in db, which expands the dependency list. Don't know yet how the app would like something messing it's internals.

The summary:
1) Inability to directly alter note properties is the source of hacky workarounds.
2) Scripting functions should allow working with notes other than current, working with many notes. That is also a must for my nsx2md import script. The script is all good but tagging.
3) The "visibility in the list" requirement limits the scripting. You can't work with externally created notes. You can't work with notes in other sub-folders.
4) "Create new note" function needs some love.

**Comment by pbek** [comment]
I'm not sure what we can do about all that and what to do. Some of it are hard limitations at the moment and some would be really hacky to change...

**Comment by Maboroshy** [comment]
Maybe I just want too much. I've tried changing tag data directly in db, and looks like the app doesn't mind. So maybe I should go that route and reduce using QML to extracting folder/note data only.

Basically all that messing with internal requires is folder reload to see the changes. I'm yet to understand all the triggers app has to force a reload. Maybe there should be a function for forcing folder reload, perfectly the one that would also enable next lines of script to use reloaded data.

**Comment by pbek** [comment]
Didn't modifying the database already trigger a reload?

**Comment by pbek** [comment]
## 17.06.3
- the MainWindow is now exposed for scripting as variable `mainWindow`
  - you can use `mainWindow.buildNotesIndexAndLoadNoteDirectoryList(true, true)`
    to force a reload of the note list
  - for more information please take a look at the
    [scripting documentation](http://docs.qownnotes.org/en/develop/scripting/README.html#MainWindow)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Maboroshy** [comment]
The new function works! I can jump to externally create note file now.
The mainWindow thing looks powerful. I'll need to take a look what else is it up too.

**Comment by pbek** [comment]
I probably have to make methods accessible by the scripting engine first if you need more things than currently documented.

**Comment by Maboroshy** [comment]
I was hacking for several hours to use your tag SQL queries in python. 
I've managed to transfer tag from one note to another at last. Had some evil laugh. :smiling_imp:

**Comment by pbek** [comment]
Those laughs are the best, you conquered your data. :)
