### ISSUE TITLE
Feature request: Integration of ToDos and sync to TaskWarrior

### ISSUE THREAD

**Issue by Protarios** [pbek/QOwnNotes#606]
It would be wonderful to have ToDos directly integrated and parsed/updated from Notes.
And the perfect addition would be integration with Task Warrior.
I think this idea partially matched with what Issue #550 requests.

Let me explain a bit more in detail what I am thinking of:
The idea is to have a ToDo written in a syntax aligned to TaskWarrior directly inside the note.
Something like:
task://Name of task +tag +due:tomorrow 
Project i of the task is ideally is automatically set to the notes name

This would then be both displayed in preview with a checkbox and automatically parsed and both added to the ToDo list of QOwnNotes and TaskWarrior.
I think I would be a good idea to update the task automatically with additional info, like project name and taskwarrior ID (and maybe unique identifier)
task://17 Name of task +tag +due:2017-06-12 uuid:8ad2e3db-914d-4832-b0e6-72fa04f6e331

The task should afterwards be synced by the program. So if you check as done or modify in the ToDo list, or it is checked as done or updated in Taskwarrior the Code inside the note should be updated:
task://17 done Name of task +tag +due:2017-08-17 uuid:8ad2e3db-914d-4832-b0e6-72fa04f6e331

I used a similar feature (without Taskwarrior integration) in the Mac App Notebooks before, that really shows a perfect example of note and ToDo list integration and makes working with ToDos so great.

**Comment by pbek** [comment]
I don't think that would be possible easily...

QOwnNotes exclusively uses data from an external CalDAV source. The local data gets constantly wiped out. No local tasks are ever created, they are directly created on the CalDAV server and then synced from there...

**Comment by Maboroshy** [comment]
As far as I've understood you want to parse note text and send Taskwarrior commands based on parse results. And you want commands you send to Taskwarrior also altering specific note.

The only thing you really need from QON is "this note is changed" signal. There's a scripting hook for that. 

You'll need a "middle man" external app/script, that would get signals from both apps, store note-task binding, do some simple logics, change note texts and send some commands to Taskwarrior.

I don't see anything that needs to be implemented to QOwnNotes to do it.

**Comment by pbek** [comment]
I will close this issue until there is more information.
