### ISSUE TITLE
Program doesn't start with setting files [fedora 25, KDE]

### ISSUE THREAD

**Issue by KramVell** [pbek/QOwnNotes#608]
If I execute this program first time or after deleting of config files `rm -rf ~/ownCloud/ ~/.config/PBE/ ~/.local/share/PBE/`, it works normal. But when I execute it second time, I can see it in processes (top), but top doesn't show a processor activity for this process and nothing happends. A window of the program doesn't appear. 

How to repeat this bug:
1. Install QOwnNotes on Fedora 25 from repository  http://www.qownnotes.org/installation points to.
2. Execute the program and do first steps (OwnCload wasn't used)
3. Close the program.
4. Execute it again.

My OS is Fedora 25 linux with KDE desktop.

**Comment by pbek** [comment]
Which Desktop theme do you use?

Am 14.06.2017 5:56 Nachm. schrieb "Pavel Kramer" <notifications@github.com>:

**Comment by KramVell** [comment]
Breeze transparent dark (and Papirus Dark icon theme) . I can try other themes.

**Comment by pbek** [comment]
I'm glad if works now. There seems to be a problem with Qt working with themes with broken theme file.
