### ISSUE TITLE
Disallow file names with restricted characters

### ISSUE THREAD

**Issue by szotsaki** [pbek/QOwnNotes#610]
When I create a note, its heading will be the file name. However, there are some restricted file names and disallowed characters. Two on Linux, many more on Windows.

Please,
* remove forbidden characters from the file name and
* substitute the file names where the title contains only a reserved Windows word (like `CON`).

Here is a [comprehensive Wikipedia article](https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations) about it.

**Comment by pbek** [comment]
As discussed in #513 QOwnNotes doesn't know which filesystems (could even be more than one) the user is using in a note folder and even if it does there are too many to support all different restrictions. How would you handle that?

**Comment by pbek** [comment]
I will close this issue until there is more information.
