### ISSUE TITLE
Question about tag db queries

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#611]
I'm into hacking db internals by external scripts. I try sticking to SQL queries used in your `src/entities/tag.cpp
` for mimicking the way app works.

I run the query for renaming a note:
```sql
UPDATE noteTagLink 
SET note_file_name = :newFileName 
WHERE note_file_name = :oldFileName AND note_sub_folder_path = :noteSubFolderPath
```
The first run works right. Yet the second one wastes all the note's tags.
There must something buried deep in the code that I've missed. The db is quite plain. I can't understand what inconsistencies the app finds, minding the first run is always successful.

Could you give some insights.

**Comment by pbek** [comment]
What parameters do you set on the first run and which on the second?

**Comment by Maboroshy** [comment]
I was working on "pin note", so first run was with:
`:newFileName = '! test note', :oldFileName='test note', :note_sub_folder_path='test'`
the second was opposite:
`:newFileName = 'test note', :oldFileName='! test note', :note_sub_folder_path='test'`

**Comment by pbek** [comment]
Maybe you can use a `SELECT` query instead on an `UPDATE` query before your 2nd part to check which notes would be affected by your update.

**Comment by Maboroshy** [comment]
I'm sorry, but the reason, as usual, have nothing to do with the subject. 
It was the `mainWindow.buildNotesIndexAndLoadNoteDirectoryList(true, true)` in my script. It was chewing that tags!
Also sometimes it refreshes file renaming only 5 seconds after it occurs. Delays doesn't help.

And I'm still having hard time for fetching renamed note after it.

**Comment by pbek** [comment]
It is indeed a tricky matter. If the note folder gets modified (and that will happen when the sqlite database is updated and its temporary files might get written) the note folder will get reloaded...

**Comment by Maboroshy** [comment]
The thing is the, as far as I know, the folder will get reloaded only after the script code will run, no matter if there's a 15 second sleep at the last line. So I can't fetch for newly created note until the script's finished. 
The `mainWindow.buildNotesIndexAndLoadNoteDirectoryList(true, true)` between renaming and fetching was supposed to resolve this issue. And it did the first time I've tried it. Yet I can't make it work properly now.

**Comment by pbek** [comment]
What happens when your linked tags get "chewed"? Are they removed? Why should buildNotesIndexAndLoadNoteDirectoryList do this?

**Comment by Maboroshy** [comment]
I asked myself the last questions more than once.

The tags are removed after `buildNotesIndex...`, there are no entries in the db.

My guess, which is based on nothing really, that there's a some kind of race condition created by my script, `buildNotesIndex...` and/or refresh, that occurs automatically after script's finished. Something must be triggering `Tag::removeBrokenLinks()` or some other garbage clear function at the wrong time. What surprises me that putting in delay timers, even long ones, didn't help.

Here's my beta code:
<details>
  <summary>QML Script</summary>

```qml
import QtQml 2.2
import QOwnNotesTypes 1.0

/* This script is tested only on GNU/Linux, it's not tested on OSX and won't work on Windows.
 * If you know how to make it properly rename note files in Windows feel free to make a pull request.
 * 
 * This script implements custom action buttons to prepend current note name with a special (or any other) 
 * unicode symbols so the note will be "pinned" on top of the list with 'alphabetical sorting' on.
 * You can use different symbols, one at a time, to 'pin' notes. 
 * That allows to make kind of hierarchy of pinned notes.
 * 
 * Notes can be "unpinned" by using same symbol second time.
 * 
 * Since the script actually creates a new note with the same content assigned tags won't be saved.
 * 
 * This script should be used with "Allow note file name to be different from headline",
 * "Accept all external modification of current note', 'Sort by -> Alphabetical" options on. */

Script {

    property string scriptDirPath
    property string pyBin
    property string symbol
    property string fetch
    
    property variant settingsVariables: [
        {
            'identifier': 'symbol',
            'name': '"Pin" symbols',
            'description': 'Put a symbols that will prepend note name.\n' +
                           'Better use emoticon-like unicode characters. Spaces and commas are ignored.',
            'type': 'string',
            'default': '★ ⚑ ✔',
        },
        {
            'identifier': 'pyBin',
            'name': 'Command/path to run Python 3 Interpreter',
            'description': "Put a path to to Python 3 interpreter here, if default settings doesn't work.",
            'type': 'file',
            'default': 'python',
        }
    ]

    /// Symbols are sorted, so buttons are in the same order symbols will be in the note list.
    property string pool: symbol.split('').sort().join('')
    
    function init() {

        /// Fetch for Python 3 interpreter binary path
        var pyVer = script.startSynchronousProcess(pyBin, '-V', '').toString()

        if (pyVer.indexOf('Python 3') == '-1') {
            script.informationMessageBox("Can't run Python 3 interpreter.\n" +
                                         'Please set the correct path in script settings.',
                                         'Pin note script')
        }
        else { script.log(pyVer + 'found.') }

        /// Each symbol will get own button to add it to selected note name.
        for (var n = 0; n < pool.length; n++) {
            if (pool[n] != ' ' && pool[n] != ',') {
            script.registerCustomAction(n, 'Mark note with ' + pool[n], pool[n])
            }
        }
    }

        function delay(duration) { // In milliseconds
        var timeStart = new Date().getTime()
        while (new Date().getTime() - timeStart < duration) {
            // Do nothing
        }
        // Duration has passed
    }

    /// Each symbol uses single algorithm to prepend note name with it.
    function customActionInvoked(n) {
        
        if (pool.indexOf(pool[n]) == -1) {
            exit(1)
        }
        
        /// Get some note data
        var note = script.currentNote()
        script.log('fr: ' + note.fullNoteFilePath)

        var noteName = note.fileName.replace(/\.[^/.]+$/, '')
        script.log('nm: ' + noteName)

        /* Delete symbol if note is "pinned" by it.
         * Or prepend "unpinned" note with that symbol.
         * Or "repin" note with the new symbol. */
        if (noteName.substring(0,2) == pool[n] + ' ') {
           var newName = noteName.substring(2)
        }
        else if (pool.indexOf(noteName.substring(0,1)) != -1 && noteName.substring(1,2) == ' ') {
            var newName = pool[n] + ' ' + noteName.substring(2)
        }
        else {
            var newName = pool[n] + ' ' + noteName
        }

        /// Rename the note file by a Python script with a new "prepended" name.
        var pyScriptPath = scriptDirPath + script.dirSeparator() + 'rename_note.py'
        var output = script.startSynchronousProcess(pyBin, [pyScriptPath, note.fullNoteFilePath, script.currentNoteFolderPath(), newName], '')
        script.log(output)
      //  delay(1000)
      //  mainWindow.buildNotesIndexAndLoadNoteDirectoryList(true, true)
      //  delay(1000)

        script.log('to: ' + newName)
        script.setCurrentNote(script.fetchNoteByFileName(newName))
    }
}
```
</details>

<details>
  <summary>rename_note.py</summary>

```python
import sys
import qon

qon.Note(sys.argv[1], sys.argv[2]).name = sys.argv[3]
```
</details>
<details>
  <summary>qon.py</summary>

```python
import os
import sqlite3


def fetch_folder_from(path):
    while True:
        if 'notes.sqlite' in os.listdir(path):
            return path
        else:
            if path == os.path.dirname(path):  # path is root
                break
            else:
                path = os.path.dirname(path)


class Note:
    def __init__(self, note_path, folder_path=''):
        if not os.path.isfile(note_path):
            raise OSError('Specified note file not found.')

        self.path = note_path
        self.file_name = os.path.basename(self.path)
        self.ext = os.path.splitext(self.file_name)[1]
        self.dir = os.path.dirname(self.path)

        if folder_path:
            self.folder = folder_path
        else:
            self.folder = fetch_folder_from(note_path)

        self.subfolder = self.dir.replace(self.folder, '')[1:]


    @property
    def name(self): return os.path.splitext(self.file_name)[0]

    @name.setter
    def name(self, new_name):
        db = sqlite3.connect(self.folder + os.sep + 'notes.sqlite')
        cursor = db.cursor()
        cursor.execute('''UPDATE noteTagLink 
                          SET note_file_name = ?
                          WHERE note_file_name = ? AND note_sub_folder_path = ?''',
                       (new_name, self.name, self.subfolder))
        db.commit()
        db.close()

        new_note_path = self.dir + os.sep + new_name + self.ext
        os.rename(self.path, new_note_path)
        print(self.name + ' renamed to ' + new_name)
        self.__init__(new_note_path, self.folder)


    text = property()

    @text.getter
    def text(self):
        with open(self.path, 'r') as note_file:
            print('Got the text from ' + self.path)
            return note_file.read()

    @text.setter
    def text(self, new_text):
        with open(self.path, 'w') as note_file:
            print('Put new text to ' + self.path)
            note_file.write(new_text)


    tags = property()

    @tags.getter
    def tags(self):
        db = sqlite3.connect(self.folder + os.sep + 'notes.sqlite')
        cursor = db.cursor()
        cursor.execute('''SELECT t.name FROM tag t 
                          JOIN noteTagLink l ON t.id = l.tag_id
                          WHERE l.note_file_name = ? AND l.note_sub_folder_path = ? 
                          ORDER BY t.priority ASC, t.name ASC''',
                       (self.name, self.subfolder))
        tags = [ tag[0] for tag in cursor.fetchall() ]

        db.close()
        print('Tags of {} are {}'.format(self.path, tags))
        return tags
```
</details>
`
  
The thing I don't yet understand is what `buildNotesIndex...` is. I mean, some runs with it ended up leaving note list with old note name, while the file name was already renamed by a script. Running `buildNotesIndex...` didn't help. Using `refresh folder` didn't help. But changing folder and going back synced it up again. `buildNotesIndex...` and `refresh` are somehow different than folder change. While, logically, they should do mostly the same thing.

**Comment by pbek** [comment]
Do you first rename your notes and then re-tag them? Because otherwise `Tag::removeBrokenLinks()` will remove the tag-links.

**Comment by Maboroshy** [comment]
I did the bad "otherwise" thing. I'll do do some tests.

**Comment by Maboroshy** [comment]
If there's anything changed after I swapped renaming and tagging, I had not noticed it. 
Most of the times list and file go out of sync. On the second run tags got chewed up again.

**Comment by pbek** [comment]
What was it you want to achieve? Renaming the file of the current note (without tags getting lost)?

**Comment by Maboroshy** [comment]
I want to control tags for any note, including the ones created while the script is running.

"Pin note" script is mostly a first test. `qon.py` is supposed to be kind of QON "bindings" to python.
So first step is renaming (creating) a note and transferring tag data. 

Next step is enhancing "Note-Station-to-markdown" script to import tag data to the app. That means that it should create 100 notes, possibly in different sub-folders, and tag them by a single run.

The funny thing is I myself ceased using tags altogether. But, if there are tags, good scripts should be able to handle them any way required.

**Comment by pbek** [comment]
You are very crafty!
Would something like `addTag`  and `removeTag` for a note object help? How would you load the note objects? With `fetchNoteByFileName`?

**Comment by Maboroshy** [comment]
I'm gone to enjoy some Greek sun. We'll continue in July.

**Comment by pbek** [comment]
Sounds great, have fun!

**Comment by Maboroshy** [comment]
I'm back, sunburned and motivated.

About your questions. 

A setter for "tag" property of note object is planned. It will be easy to implement using tag db queries you've already written, so I'm not rushing for it. I want to debug writing to tag db with note object's "name" property setter, which includes renaming tag db query.

QML script runs the python script providing `script.currentNote()` result as one of command line arguments. Note object is generated based on provided path.

After the python part completed (note file is renamed, tag db is corrected accordingly) I need the app to jump to newly "created" note, so the user would get seamless action - note is renamed (created) but it's still the current one.

That's where I need `fetchNoteByFileName`. But I can't work out externally creating a note and fetching for it in one script.

**Comment by pbek** [comment]
You are back already? Time flies, I hope you had a great time in Greece!

Does a method from <http://docs.qownnotes.org/en/develop/scripting/README.html#mainwindow> help?

**Comment by Maboroshy** [comment]
A bit of Greece is good for everybody.

I wrote the story of my complex relationship with this method above. 
The summary: it chews tags of newly created note; the app's note list and file system often go out of sync.

**Comment by pbek** [comment]
I don't even know if / what I could do to help you in the scripting engine...

**Comment by Maboroshy** [comment]
I'll think some more about. For now everything I come up with looks too hacky.
