### ISSUE TITLE
"Note folder" is strange

### ISSUE THREAD

**Issue by QuAzI** [pbek/QOwnNotes#612]
![_2017-06-18_15 42 21](https://user-images.githubusercontent.com/1897605/27260782-51f5afca-543d-11e7-8b20-79841d7c8286.png)

If "Note folder" is required please use different icon and remove "Remove selected folders" option from menu.

**Comment by pbek** [comment]
@derboblan, was that a thing you did?

**Comment by pbek** [comment]
@QuAzI, did you play with the *Panels* options in the settings? Maybe the tree view is better for you...

**Comment by QuAzI** [comment]
Oh, yes, it is better. But why it is not used by default and shows strange virtual folders? It is confuse me

**Comment by pbek** [comment]
@QuAzI originally the issue that people had was that showing it as tree with the name as root used up more screen space, but I guess we can make it default nevertheless...

## 17.07.6
- *Show root folder name* and *Display note subfolders as full tree* in the
  *Panels settings* are now set by default
