### ISSUE TITLE
Support formulas and diagrams (flow, sequence)

### ISSUE THREAD

**Issue by QuAzI** [pbek/QOwnNotes#617]
Qt example: https://github.com/weijiaming/QtCreator-Markdown-Editor-Plugin

**Comment by pbek** [comment]
Thank you for your suggestion, but I'm sorry, the QTextEdit currently used for the preview can't view such elements that. The Qt library seems to use JS libraries to generate the html code in a WebView.

Although you could write scripts to insert something as an image if you like to.
