### ISSUE TITLE
Integrate documentation into the project

### ISSUE THREAD

**Issue by QuAzI** [pbek/QOwnNotes#618]
Right now documentation placed in web site. But it is better to save documentation near the software. 
Move documentation inside QOwnNotes repo and distribute with software. By default add documentation subfolder to "Help" note folder and move into it "Markdown Cheatsheet", "Markdown Showcase" and "Welcome to QOwnNotes".
* Users will see how they can use your software to write documentation by example
* Documentation will be saved in repo and in software distributive. 
  * Documentation will be saved! Event if site will be closed.
  * Sometimes (in the way as example) users have no Internet connection (and documentation in Web as result)

**Comment by pbek** [comment]
Thank you for your suggestion, but why would that be better than documentation in the web, where it can be edited and expanded? Or am I misunderstanding something? You want a new note sub-folder with documentation markdown files?

**Comment by pbek** [comment]
I will close this issue until there is more information.
