### ISSUE TITLE
Is there a way to disable the media folder and image numbering ?

### ISSUE THREAD

**Issue by Weej1** [pbek/QOwnNotes#623]
Hi, 
A long time (mostly) silent user of QoN and a big time lover of it! 
This isn't a bug per se but is it possible to disabled the media folder and the 12321412451235.png numbering that QoN automatically does? 

I ask this because I actually use QoN for work. Documentation/guides to be exact.  Everything in QoN works fine but when it comes to exporting, I switch to another Markdown editor called Typora (although I use actually 4 different MD editors). All of these editors have these very clean and beautiful looking themes made from HTML/CSS and people who read the documents respond positively to them. (clean to read, easy on the eyes etc) 

the problem arises when I open up AnyNameGuide.md in these other Markdown editors. It's actually split into 2 issues:

1. I frequently have to clean up the links like 
`\![002-Speedtest-Go-Button]\(file://media/1211720176.jpg)` to e.g. `\![002-Speedtest-Go-Button]\(./SomeFolder-Resources/images/009-Speedtest-Go-Button.jpg)`

2. as you've noticed in point#1 - I also have to rename the file to something descriptive. This is done mainly for my students - each file I make in QoN has to go through this process where I create 'SomeGuide.txt' in QoN and then I open it up in typora/laverna/skrifa etc and then rearrange everything to` ./SomeGuide-Resources/images` `./SomeGuide-Resources/video`  `./SomeGuide-Resource/audio`

Then I place each respective media type into their folder for that particular markdown document. and then I number each file per respective folder so images will be `001-PressTheGoButton.jpg`, `002-WaitForNameDialogBox.jpg`, `003-`...etc

Videos folder will be same, it will begin with `001-[insertDescriptiveNameForClip].webM` etc , same with Audio. 

Honestly I wouldnt even use the other apps if I had an easy way to export to Doc/PDF with a clean theme - however since I need to share the resource files with students also - I go through this process with every note. 

I know this is long and thank you for reading this far - but any help or guidance I'll appreciate. Hope I'm not being too "demandy" :) 

edit: whoops, didn't realize that Github would render my fake image links properly, fixed now!

**Comment by pbek** [comment]
Are you talking about an other format to handle media file like in #266? There are a lot of troubles doing that and I haven't succeeded in getting links with non-urls to work. So I think you might be out of luck here...

**Comment by Weej1** [comment]
Hi ! Thanks so much for the quick response. 
I'm a little unclear about what you mean by "handle media file" - 

I read through #266 but it seems more about being against file:// and media:// - and how it renders/previews etc. (although in #266 there *is* mention of absolute/relative links which is more what on what I'm inquiring about.) 

So just to clarify , I have no issues with how QoN renders / previews images etc. I only have issues with the current system of QoN shoving images into the media folder and then renaming those images into  SomeLargeNumber.jpg.  

I was wondering if there was an option (or if its possible for a way to implement the option) to disable that system  and put in an image directly located in a folder of my choosing with a file name of my choosing. 

( so again, instead of `file://media/1231414512.png` can I have it as `file://home/MyUsername/Work/Documents/Pictures/010-SomeDescriptiveNameofPic.png` or even just `./Pictures/010-SomeDescriptiveNameofPic.png` (assume that the .txt/.md is in 'Documents' Folder here so the link is relative to where note is).

**Comment by pbek** [comment]
I see what you mean now. It's hard to ensure a name that is unique for all note subfolders of a note folder and that works on all file systems and in an URL. Plus there isn't even a filename all the time, for example if image-data is pasted from the clipboard. The image has to be in the media folder so it gets synced by sync clients and QOwnNotes can find it.

In theory I could use something like `file://media/<random-numer>-<original-filename>.jpg`, but I might even get into troubles across different filesystems with that. I could remove everything but `[a-zA-Z0-9\-_`. Would that help?

Or you could always write a script that renames your files according to the description in the markdown image "tag".

**Comment by Weej1** [comment]
Im so sorry I should've have specified - the name of filenames are pre-made by me manually outside of QoN. 
All I really am asking is... well this -->  https://drive.google.com/open?id=0B7iSCtA1UT9DdTM4bXJoaTZmQVU 

While it would totally rock to have QoN number the file for me (i.e. if my file is called `./Pictures/ClickThisButton.png` - it would be wonderful if QoN can change that to `./Pictures/001-ClickThisButton.png`) Im not completely sure how feasible it would be for you.

**Comment by pbek** [comment]
I'm sorry, I can't support a full path (like in your video), see #266. And the `Pictures` path isn't possible neither. Neither are arbitrary numbers, like 001, 002, 003... (see my above comment).

**Comment by pbek** [comment]
You could do well if you write a script that replaces the image urls in your notes and in the `Media` folder if you want to take care of them yourself.

**Comment by Weej1** [comment]
Ah too bad, I dont mind trying out scripting but wouldn't that mean I have to first paste the link into QoN which would automatically rename the file from 001-whatever.png to 12513415.png and move it to the /media/ folder? In which case I dont see how the script will "know" which file goes where unless I manually tell it "12513415.png is 001-whatever.png" which is already what I'm doing . Or is there something I'm missing?

**Comment by pbek** [comment]
And you can always just use image-links like `![My custom image](file://Pictures/MyCustomName.jpg)` to embed an image `Pictures/MyCustomName.jpg` relative to your note-folder.

**Comment by pbek** [comment]
Just put your image into your `Pictures` folder inside the note-folder and enter the urls manually...

**Comment by Weej1** [comment]
wait.. I can?? That'd be great! Can I do that by Dragging and Dropping the image onto my note? Because that would pretty much what I need! I'm perfectly fine with `![My custom image](file://Pictures/MyCustomName.jpg)'

**Comment by pbek** [comment]
You can also use absolute paths like `![My custom image](file:///home/user/ownCloud/Notes/test01/MyCustomName.jpg)`.

**Comment by Weej1** [comment]
O crap - guess I posted too late - so manual is the only way to achieve this ? 
Because I just took drag n Drop for granted. what you're describing is Exactly what I' need but was hoping to not type out the whole string manually. Just drag n drop without having my image go to /media/ and without it being renamed 12345678.png

**Comment by pbek** [comment]
If you need more control you try to use a script like in <https://docs.qownnotes.org/en/develop/scripting/README.html#insertmediahook>. There is an example here: <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/example.qml#L75>. I think that could work for you.

If not maybe with: <https://docs.qownnotes.org/en/develop/scripting/README.html#insertingfrommimedatahook>

**Comment by pbek** [comment]
`insertMediaHook` works if you drag & drop a file, I just tested it. Of course you need to build the markdown tag you want to enter in your note yourself.

**Comment by pbek** [comment]
a function like

```JavaScript
    function insertingFromMimeDataHook(text, html) {
        return "my url: " + text;
    }
```

would paste a test like `my url: file:///home/user/ownCloud/Notes/test01/MyCustomName.jpg` into your note if you drop that file into QOwnNotes. Be aware that no file-copying is done.

**Comment by Weej1** [comment]
Hmm the example and insertmediahook seems to be what I need but I'm a little lost since it looks like what I'm asking the script is Already doing!

I mean if fileName = filepath of the source BEFORE it was copied to media folder and If mediaMarkdownText just adds all the markdown for the image string (which i assume is ![filename](file://) etc

Then according to that QoN should already be doing what I need with the insertMediaHook function! I dont see the part where it copies to media folder and changes fileName from original to number. 

As you can tell I've never scripted in this QML so I'm lost. Thanks for being so speedy and patient. 

```
 /**
     * This function is called when media file is inserted into the note
     * If this function is defined in multiple scripts, then the first script that returns a non-empty string wins
     * 
     * @param fileName string the file path of the source media file before it was copied to the media folder
     * @param mediaMarkdownText string the markdown text of the media file, e.g. ![my-image](file://media/505671508.jpg)
     * @return string the new markdown text of the media file
     */
    function insertMediaHook(fileName, mediaMarkdownText) {
        script.log("mediafile was inserted: " + fileName);
        return "";
}


```

**Comment by pbek** [comment]
I wrote you an example script: [paste-full-url.zip](https://github.com/pbek/QOwnNotes/files/1111314/paste-full-url.zip)
You have to extract the archive and add the qml-script in the *Scripting settings*.

**Comment by pbek** [comment]
The script currently pastes everything you drop into QOwnNotes as image link.

**Comment by Weej1** [comment]
Sweet Christmas! What kind of wizard are you?? I was still typing up how I was unable to get your above snippet to work and then you post 2 message WITH the solution! Thank you so so much!  This is exactly what I was asking about! 

On another note I noticed in the script repository an option to use  'Custom note preview styling' - does this mean that if I export to PDF it will do so with that same CSS styling? Also where would I place the CSS files? 



 ---Outdated Comment since you fixed this ---
Hmm I'm not able to get the script snippet you gave ( insertingFromMimeDataHook one) running but I'm probably not using it properly - I guess I'll try this after work -

**Comment by Weej1** [comment]
I'm not sure how to close this issue - since you pretty much fixed it! :<

**Comment by pbek** [comment]
> What kind of wizard are you?

:)

> On another note I noticed in the script repository an option to use 'Custom note preview styling' - does this mean that if I export to PDF it will do so with that same CSS styling? Also where would I place the CSS files?

Those questions might answer themselves if you install the script. :)
And yes, the pdf export also uses those styles (to the extend it is supported by the Qt library).

**Comment by pbek** [comment]
You can also add that styling inside your script, see: <http://docs.qownnotes.org/en/develop/scripting/README.html#notetomarkdownhtmlhook>

**Comment by pbek** [comment]
@Weej1, be sure to star QOwnNotes if you like it. :)
And if you write a great script and want to share it with everyone you can do here: <https://github.com/qownnotes/scripts>

**Comment by Weej1** [comment]
Starred! and I'll definitely do that (i.e. share any scripts , of worth)  - looking at QML seriously now Once again thanks for Everything!

**Comment by pbek** [comment]
<http://docs.qownnotes.org/en/develop/scripting/README.html> is your friend. ;)

**Comment by pbek** [comment]
For reference, I commited the script here: <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/paste-full-image-url.qml>

**Comment by pbek** [comment]
Could you please head over to #266 to test and comment on the new features.
