### ISSUE TITLE
Error on "open note with external editor" with Atom

### ISSUE THREAD

**Issue by vanleo2001** [pbek/QOwnNotes#625]
1.   I  use win 7 x64, QOwnNotes 17.07.0. The default markdown editor is Atom x32 version. If I click  note with "external editor", Atom will crash, only Atom x64 version can run.

2.   As the default external editor, Atom x64 can run, but it can not auto open the current note.

**Comment by pbek** [comment]
I'm not sure what Atom supports or doesn't support (for example to add a filename as parameter to open it). What happens if you define Atom distinctly in QOwnNotes as external editor?
What happens if you define an other editor in QOwnNotes as external editor?

**Comment by vanleo2001** [comment]
finnally, I try to set atom as default markdown editor, let "settings--path to external editor" empty, that's ok.  But if I write in "settings--path to external editor" with Atom path, Atom can run but can't auto open current note.

**Comment by pbek** [comment]
I'm not sure what you did and how Atoms opens files that are added as parameter. If you want to do something special (like setting special parameters for Atom) you can do so in a script.

You will need these:
- <http://docs.qownnotes.org/en/develop/scripting/README.html#starting-an-external-program-in-the-background>
- <http://docs.qownnotes.org/en/develop/scripting/README.html#registering-a-custom-action>

Does this help a bit?

**Comment by vanleo2001** [comment]
I see. The error is in Atom, not you.
Run the following script is ok:

```
import QtQml 2.0
import QOwnNotesTypes 1.0

/**
 * This script is an example for creating custom actions, that can be invoked 
 * via menu entries and buttons
 */
QtObject {
    /**
     * Initializes the custom actions
     */
    function init() {
        // create a menu entry "Open with KWrite" with a button "KWrite"
        script.registerCustomAction("RuninAtom", "Open with Atom", "Atom");
    }

    /**
     * This function is invoked when a custom action is triggered
     * in the menu or via button
     * 
     * @param identifier string the identifier defined in registerCustomAction
     */
    function customActionInvoked(identifier) {
        script.log("customActionInvoked - " + identifier);

        switch (identifier) {
            // open the current note with KWrite
            case "RuninAtom":
                var note = script.currentNote();
                var fileName = note.fullNoteFilePath;
                script.startDetachedProcess("C:\\Users\\Home\\AppData\\Local\\atom\\app-1.18.0\\atom.exe",fileName);
                break;
        }
    }
}
```

change
` script.startDetachedProcess("C:\\Users\\Home\\AppData\\Local\\atom\\app-1.18.0\\atom.exe",fileName);`
to
` script.startDetachedProcess("C:\\Users\\Home\\AppData\\Local\\atom\\atom.exe",fileName);`
Then app Atom can not auto open current note.

Thanks a lot.

**Comment by pbek** [comment]
Nice script! Great it worked. :)
