### ISSUE TITLE
How Enable Code Highlight and tweak Style of Editor?

### ISSUE THREAD

**Issue by UltimateRandom** [pbek/QOwnNotes#626]
I really like this program, i already managed to edit the UI but now I looked through all the options but i don't find a way to enable highlighting for block codes like js,css,php. Also how can i edit the css of the editor, basically i want to add some margins so the text is in the center and is far easier to read, also make a full background to the code blocks since they look weird with the deafult. 

_Original_

<img width="940" alt="one" src="https://user-images.githubusercontent.com/20800791/27982544-27f6da04-637a-11e7-817d-8d03a5fc869f.png">

_Target_

<img width="960" alt="two" src="https://user-images.githubusercontent.com/20800791/27982554-5e55998c-637a-11e7-95cf-ead2dd369b04.png">

Any help is appreciated

**Comment by UltimateRandom** [comment]
OFF
If somebody wants to put this in some wiki or readme, there is a super way of changing the program UI style:
- Install the script "Custom user interface styling" 
- Change the css in this template: https://github.com/pbek/QOwnNotes/blob/develop/src/libraries/qdarkstyle/style.qss
- Copy all and paste in Script Custom Stylesheet textbox.

That basically works and it's super easy, you just need basic knowledge of css. For now i made this very quick searching colors and replacing them, but i guess it's better to just copy just what you moded 😃

**Comment by pbek** [comment]
You created a nice looking theme, if you want to share it you can export it. ;)
I'm sorry, there currently is no way to "turn on code highlighting". QOwnNotes is a Qt app, there is no library for that. I've written the markdown highlighter myself (and it was very painful).

**Comment by UltimateRandom** [comment]
Ok, what about the style of the editor? can that be changed? not the highlighting, that's ok, but it would be awesome if a margin can be added to center text and full background for the block codes. 

Here is the theme from the screenshoot: 


[Dark (Copy).txt](https://github.com/pbek/QOwnNotes/files/1133224/Dark.Copy.txt)

**Comment by pbek** [comment]
Thank you for the export. Do you have a name for your theme?

> Ok, what about the style of the editor? can that be changed? not the highlighting, that's ok, but it would be awesome if a margin can be added to center text and full background for the block codes.

I'm sorry, if you don't manage to do that with the styles you found out about above it's harder to do. And the last time I added margins in the text (headline) it even introduced a Qt bug. The undo doesn't work any more...

**Comment by UltimateRandom** [comment]
Ok no problem, thanks for the quick answers. 

> Do you have a name for your theme?

Dark Material suits for the colors i guess 😄

**Comment by pbek** [comment]
Thank you, I will add it to the next release!

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by UltimateRandom** [comment]
Yes it's working great 👍

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by Creling** [comment]
It is pretty.
But, how can i get such style?
copy everything in Dark (Copy).txt doest work

**Comment by pbek** [comment]
> But, how can i get such style?

Can you please explain in more detail and step by step what you did, what happened and what you expected.

**Comment by noraj** [comment]
@UltimateRandom There is now [KSyntaxHighlighting](https://api.kde.org/frameworks/syntax-highlighting/html/) supporting more than 300 different syntax.
Can you re-open the issue?

PS: [Vnote](https://tamlok.github.io/vnote/) is just doing it with HighLight.js rendering engine.
