### ISSUE TITLE
Accidentally hid the top global menu(file,view,edit)

### ISSUE THREAD

**Issue by DroWnThePoor** [pbek/QOwnNotes#628]
I have accidentally disabled the "local" menu on Ubuntu 16.04, File Edit View etc.. How can I bring it back?

**Comment by pbek** [comment]
Please search for `menu` in <http://www.qownnotes.org/shortcuts/QOwnNotes>. ;)

**Comment by DroWnThePoor** [comment]
Thank you, somehow I missed that.
On Fri, Jul 14, 2017 at 12:26 AM, Patrizio Bekerle <notifications@github.com> wrote:

Please search for menu in http://www.qownnotes.org/shortcuts/QOwnNotes. ;)
