### ISSUE TITLE
keybord key "delete" only deletes current note if multiple are selected

### ISSUE THREAD

**Issue by calis2002** [pbek/QOwnNotes#63]
Select multiple notes on the left panel and press delete on your keyboard.

Expected behavior: QOwnNotes should remove all selected notes.
Actual behavior: QOwnNotes removes only the last selected note.

![2016-02-07__08_53_27](https://cloud.githubusercontent.com/assets/4539953/12871397/7f868542-cd78-11e5-9204-b56b9f1e9c3f.png)

**Comment by pbek** [comment]
Yes, I guess that would make sense. :grin: Thank you for the report!

**Comment by pbek** [comment]
Done, will be released with version 0.94. Can you be so kind and report back then if everything felt good for you.

**Comment by pbek** [comment]
Version 0.94 is out now.

**Comment by calis2002** [comment]
Thanks, its fixed!

**Comment by pbek** [comment]
Great! Thank you!
