### ISSUE TITLE
Menu - Show TODO List crashes application

### ISSUE THREAD

**Issue by QuAzI** [pbek/QOwnNotes#630]
Application v17.07.2 crashes after Right click in tray "Show TODO list - cancel" without any messages.

OS: Windows 7 SP1 AMD64 EN

**Comment by pbek** [comment]
I can't reproduce that issue, it works for me. Does anyone else have this issue? Does the dialog work for you if you open it with the menu entry in the `Todo` menu?

**Comment by pbek** [comment]
@QuAzI, can you please post your debug output.

**Comment by QuAzI** [comment]
Main window must be hidden to reproduce. If main window visible - all fine.
I clean log file before test and reproduce - no data about crash in log.

```
[Jul 14 22:54:22] [warning]: "Removed log file: " "C:/Users/yar/AppData/Roaming/PBE/QOwnNotes/QOwnNotes.log"
[Jul 14 22:54:24] [status]: Stored 1 note(s) to disk
[Jul 14 22:55:46] [status]: Stored 1 note(s) to disk

```

**Comment by pbek** [comment]
I still can't reproduce it.

I meant the output from the debug settings (like stated in the issue template).

**Comment by QuAzI** [comment]
Do you mean debug information ?

[QOwnNote debug informations.txt](https://github.com/pbek/QOwnNotes/files/1149617/QOwnNote.debug.informations.txt)

**Comment by pbek** [comment]
I kind of was able to reproduce it now under Windows (but nowhere else).

## 17.07.3
- when opening the todo list dialog from the system tray the main window of 
  QOwnNotes will be brought to the foreground too to prevent crashes under
  Windows

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by QuAzI** [comment]
Yes, new version doesn't crash.

**Comment by pbek** [comment]
Thank you for reporting and testing.
