### ISSUE TITLE
Settings window size wrong

### ISSUE THREAD

**Issue by QuAzI** [pbek/QOwnNotes#631]
Screen resolution 1920x1080 but it is too small to see "Ok", "Cancel" buttons in settings

![2017-07-14_22-53-04_bbge1yvo](https://user-images.githubusercontent.com/1897605/28228684-29aa5790-68e8-11e7-95f6-28aaf2ca32ee.png)

**Comment by pbek** [comment]
I'm not sure if I can get a hold on that. Qt is deciding a lot of the sizes...

**Comment by pbek** [comment]
## 17.07.3
- dialog windows are now maximized if it looks like that they don't fit on
  the current screen the first time they were opened

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
Be aware that you would have to wipe your QOwnNotes settings in the *General settings* to test this.

**Comment by QuAzI** [comment]
Can't retest because window save size from last time. How can I reset this option for test but without reset other options?

**Comment by pbek** [comment]
Since you are using windows the settings are stored in the registry. You could search for something with `SettingsDialog` and delete the geometry settings.

**Comment by pbek** [comment]
You should be able to read the settings group of your settings in the registry from your *Debug settings*.
