### ISSUE TITLE
panel sidebar not keep width size

### ISSUE THREAD

**Issue by vanleo2001** [pbek/QOwnNotes#633]
As I know, width of sidebar should  keep its size. But I find the panel (left) sidebar can't do it.  After several exchange between max and restore QOwnNotes window , the width of panel sidebar will be the half of all the window.  
width of panel sidebar in sequence
1
![snap735](https://user-images.githubusercontent.com/12027772/28243769-219d1552-6a09-11e7-9c35-cc73422bf373.jpg)
2
![snap736](https://user-images.githubusercontent.com/12027772/28243767-218bf83a-6a09-11e7-99a3-875cc0beb4bb.jpg)
3
![snap737](https://user-images.githubusercontent.com/12027772/28243771-220c1e3e-6a09-11e7-88ba-b295782452c1.jpg)
4
![snap738](https://user-images.githubusercontent.com/12027772/28243768-2195a54c-6a09-11e7-8652-7ace782f10b6.jpg)
5
![snap739](https://user-images.githubusercontent.com/12027772/28243770-21a69b5e-6a09-11e7-8d3a-778345965c59.jpg)

**Comment by pbek** [comment]
I'm sorry, please see #422 and #420 (maybe the latter has a workaround for you).

**Comment by pbek** [comment]
Please see https://github.com/pbek/QOwnNotes/issues/420 for information of a new behavior!
