### ISSUE TITLE
About line breaks

### ISSUE THREAD

**Issue by vanleo2001** [pbek/QOwnNotes#634]
##  Can you add “GFM line breaks” option in preview?
I know that is two break lines as new line in standard markdown  syntax. Also I know One break line could be as a new line  in GFM ( Github-flavored Markdown ). Can you add this option to do it in preview? 

## multilines break with "paste html and media"
When I paste html content with shoutcut "ctrl-shift-v", I can find many break lines more than two. As you know, multi break lines just as ONE NEW LINE. So can you tidy them?

**Comment by pbek** [comment]
> Can you add “GFM line breaks” option in preview?

markdown to html conversion is done by an external library, I haven't found a way to do this yet

> multilines break with "paste html and media"

I'll take a look

**Comment by pbek** [comment]
## 17.07.6
- replacing multiple line breaks when pasting html into a note with `Ctrl + Shift + V`

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by vanleo2001** [comment]
Tell the truth, I am not satisfied with the new version.
The test url is  https://www.yahoo.com/gma/sean-spicer-resigns-white-house-press-secretary-164505561--abc-news-topstories.html

The "paste the html or media" function in QON is
![snap620](https://user-images.githubusercontent.com/12027772/28497776-3c93ef26-6fc1-11e7-8bea-d6f022b30c40.jpg)

The same function in atom with "markdown writer" plugin is 
![snap619](https://user-images.githubusercontent.com/12027772/28497790-761b1120-6fc1-11e7-90de-d639f7822a0d.jpg)
It is what I expect.

**Comment by pbek** [comment]
Maybe you should have posted an example before and specify more clearly what you expected. ;)

**Comment by vanleo2001** [comment]
Below is the origin html in browser.
![snap625](https://user-images.githubusercontent.com/12027772/28498038-c0274e7c-6fc7-11e7-940e-4ac85d5f952d.jpg)

I expect the note preview  is  just as same as shown in browser , and the note text is readable and  tidy. You can see the line breaks are cleaned up in QON
![snap624](https://user-images.githubusercontent.com/12027772/28498051-202e52a2-6fc8-11e7-97e6-7014206f0875.jpg)

**Comment by pbek** [comment]
You have great ambitions. Do you care to lay hands on the sourcecode of QOwnNotes? I would assist you.

**Comment by vanleo2001** [comment]
Yes, please！

**Comment by pbek** [comment]
Great! You can play around with the html to markdown converting in `src/utils/misc.cpp`,
 see: <https://github.com/pbek/QOwnNotes/commit/02a2f8a82c7f5e945953876aa54d66053e39cc37>

**Comment by vanleo2001** [comment]
in `src/utils/misc.cpp`

`QString Utils::Misc::htmlToMarkdown(QString text) `

add code?
```
text.replace(QRegularExpression(
            "<p.*?>(.+?)</p>",
            QRegularExpression::CaseInsensitiveOption), "\n\n\\1\n\n");
```

**Comment by pbek** [comment]
looking good, if you want to make a pull request (to get the recognition for your contribution) please do so

**Comment by pbek** [comment]
I added it now myself.

## 17.07.7
- added paragraph recognition for the pasting of html-code
  (for [Issue #643](https://github.com/pbek/QOwnNotes/issues/643), thank you @vanleo2001)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
