### ISSUE TITLE
Search highlight is very light gray on white background

### ISSUE THREAD

**Issue by szotsaki** [pbek/QOwnNotes#636]
On Windows when you search for a string (Ctrl+F) the initially highlighted word is barely distinguishable among the others because the highlight colour is light gray on white. Possibly, because the editor text box is out of focus. When I click into, it turns to blue.

**Comment by pbek** [comment]
Those colors are normally set by the operating system. I'm not sure if I can do anything about them...

**Comment by pbek** [comment]
## 17.07.4
- under Windows the selection background color in the note text edit is now set 
  to a light blue if not in dark mode to prevent visibility problems when
  searching text

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by szotsaki** [comment]
Thank you, it works!

**Comment by pbek** [comment]
Great, thank you for testing!
