### ISSUE TITLE
Ctrl+F persists the hand cursor

### ISSUE THREAD

**Issue by szotsaki** [pbek/QOwnNotes#637]
When I press `Ctrl` the cursor changes from arrow to hand. When I press `F` afterwards (so `Ctrl+F`) the search bar opens and the cursor sticks in "hand mode" even after the search bar is closed.

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue.

**Comment by pbek** [comment]
## 17.07.4
- the mouse-cursor will now be set to a beam-cursor when pressing `Ctrl + F` 
  to reset the pointing-hand-cursor that was set by pressing `Ctrl`

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by szotsaki** [comment]
For `Ctrl+F` it's fixed, but for e.g. `Ctrl+R` it shows the previous behaviour. I think a more general approach is needed to switch back when releasing `Ctrl`.

**Comment by pbek** [comment]
> I think a more general approach is needed to switch back when releasing Ctrl.

that was already in place, but it depends who gets the event

**Comment by pbek** [comment]
## 17.07.6
- the mouse-cursor will now be set to a beam-cursor when pressing `Ctrl + R` 
  to reset the pointing-hand-cursor that was set by pressing `Ctrl`

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by szotsaki** [comment]
Tested with 07.07.6:

* Ctrl+R still doesn't work, unfortunately.
* Ctrl+Shift+T and Ctrl+Shift+O, when you press `Esc` after a dialogue window (built-in "No selected Todo lists" and  Windows' what to associate the .md file) pops up, still show the previous behaviour.

**Comment by pbek** [comment]
I can't reproduce both issues under Linux, where did you test that?

**Comment by szotsaki** [comment]
Now, I'm under Windows 7.

**Comment by pbek** [comment]
Phew, it had to rewrite a lot of stuff for Windows, it simply didn't work. seemed to be a Qt bug...
Should work now in the develop branch (or <https://ci.appveyor.com/project/pbek/qownnotes/build/windows-b3116/artifacts>). do you care to give it a go and test it?

**Comment by szotsaki** [comment]
I tested the .zip file downloadable from that URL on Windows and it works, thank you!

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
## 17.07.7
- fixed more problems with resetting the mouse cursor after pressing 'Ctrl' 
  for Windows
