### ISSUE TITLE
noteToMarkdownHtmlHook() ignores img width styles

### ISSUE THREAD

**Issue by szotsaki** [pbek/QOwnNotes#640]
I have the following scriptlet which tries to modify the size of images by replacing all the previous style sheets with this one:

```
import QtQml 2.0

QtObject {
    function noteToMarkdownHtmlHook(note, html) {
        var stylesheet = 'img {width: 20px; height: 20px; max-width: 100px; max-height: 100px;}';
        html = html.replace(/<style>.*<\/style>/, "<style>" + stylesheet + "</style>");
		
        return html;
    }
}
```

When you show the preview of a really big image in the preview pane, the image should appear as either 20×20 px or around 100×100 px (depending on Qt's styling support). However, the size of the image doesn't change.

If it's not possible to do this (maybe because of `getMaxImageWidth()`), please indicate this fact in the documentation of `noteToMarkdownHtmlHook()`.

**Comment by pbek** [comment]
Have you checked what css styles are supported on <http://doc.qt.io/qt-5/richtext-html-subset.html>?

**Comment by szotsaki** [comment]
Yes, it says for `img` `width` and `height` attributes are supported.

**Comment by pbek** [comment]
You could experiment by adding html code for test images with different styles and attributes with the help of `noteToMarkdownHtmlHook` to see what would work or not.

**Comment by pbek** [comment]
I will close this issue until there is more information. Please also see #639.
