### ISSUE TITLE
Interpretation of markdown syntax in "edit note" panel

### ISSUE THREAD

**Issue by bepolymathe** [pbek/QOwnNotes#643]
Hi,

I don't really understand why i have such different visual interpretation of the markdown in "edit note" panel ? I try to manage a big document document with bibliography in footnote...

![capture du 2017-07-25 16-19-53](https://user-images.githubusercontent.com/29939805/28576994-badb1388-7155-11e7-8b02-3eb203807c29.png)

But, when i produce an export, no problem. 

Regards !

**Comment by pbek** [comment]
I'm not sure how I can help you. I guess you are using a lot of "tags" that are not supported.

**Comment by bepolymathe** [comment]
Yet nothing extraordinary. Only the classic markdown syntax as mentioned here: https://github.com/pbek/QOwnNotes/blob/develop/src/demonotes/Markdown%20Cheatsheet.md
Maybe a qt side problem?
I am using fedora 26 (gnome desktop). 
But I remain faithful to qownotes which has many other advantages ... And I start my first scripts to see ... I keep you informed ;)

**Comment by pbek** [comment]
You only posted a screenshot but not the actual text, so I can't try it out. And I also don't know how you setup your editor styles. One thing I can see is that you are nesting some symbols that could be interpreted as something else.

**Comment by bepolymathe** [comment]
Just for test, i send you an email. 
Thanks ;)

**Comment by pbek** [comment]
Interestingly I don't have the issue what the part is detected as headline, but I think the blocks are parsed as reference links because of the `[xxx]: yyy` structure and the because `yyy` contains an url.

**Comment by bepolymathe** [comment]
Yes, you are right, the problem comes from the links.

**Comment by pbek** [comment]
## 17.07.7
- fixed an issue with the highlighting of special cases of the references of 
  reference links

**Comment by bepolymathe** [comment]
Oh, that's great !
Thank you.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by bepolymathe** [comment]
For the moment it's the qownnotes-17.07.6-1.1.x86_64 version in the repo for fedora. 
I test it when 17.07.7 arrive.

**Comment by bepolymathe** [comment]
Hi @pbek 
I confirm it works for me with 17.07.7 version. Thank you.

**Comment by pbek** [comment]
Great, thank you for testing!
