### ISSUE TITLE
Insertion of link

### ISSUE THREAD

**Issue by bepolymathe** [pbek/QOwnNotes#646]
Hello,

A quick message for a suggestion. When you insert a link with Ctrl + L (or by the menu), you get `<link>` or `[] (link) `depending on the url ...

I explain myself in image ...

![link1](https://user-images.githubusercontent.com/29939805/28678457-c2ee4116-72f0-11e7-99c4-8aeed555938a.png)

![link2](https://user-images.githubusercontent.com/29939805/28678462-c74cfd2e-72f0-11e7-9e76-4c361ed0b30b.png)

![link 3](https://user-images.githubusercontent.com/29939805/28678469-cca85d7c-72f0-11e7-9b26-da5fe05b3d89.png)

![link 4](https://user-images.githubusercontent.com/29939805/28678478-d0d6b736-72f0-11e7-942e-20981220f17e.png)

Do you think it will be possible that Qownnotes recognizes "www.link.com" and "link.com" as full url?

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by bepolymathe** [comment]
Moreover, I also notice as a consequence that the preview of the `<www.google.com>` link does not work (in preview panel). Users, you have to add `https:// `at the beginning of link for see it.

**Comment by pbek** [comment]
Yes, they have. `<www.google.com>` is no URL, it could be all kind of stuff, like a file. ;)

**Comment by pbek** [comment]
## 17.07.9
- when entering an url in the link-dialog with <kbd>Ctrl + L</kbd> that is 
  missing a`://` then `http://` will automatically added in front of the url

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by bepolymathe** [comment]
Woawww 👏... @pbek Do you take breaks from time to time? 😏
Ok, no problem, i test it when new release arrive in fedora depo...

**Comment by pbek** [comment]
I take brakes every day! :)

**Comment by bepolymathe** [comment]
Hi @pbek, it strange i can't upgrade qownnotes from the fedora repo. 
`dnf info qownnotes` reply that there are 2 versions in the repo 17.07.7 and 17.07.9
Could you check this ?
Thank in advance

**Comment by bepolymathe** [comment]
No, that's fine. I found the solution. 
And it works for ilnk insertion ;)

**Comment by pbek** [comment]
Ah, great. Thank you for testing.
The Fedora packaging is done by OBS: <https://build.opensuse.org/package/binaries/home:pbek:QOwnNotes/desktop?repository=Fedora_26>

**Comment by bepolymathe** [comment]
Hi @pbek 
I just spotted a problem I had not seen the first time.
The insertion of external link (to Internet) works very well but it has destabilized the functioning of the internal links (towards another note).
If I try to create a link to another note, I simply get `<http: //> `that is the part of code added ...
There must be a problem somewhere. Could you check on your side?
Have a good day.

**Comment by pbek** [comment]
Oh, it really is broken now. Thank you for finding out!

**Comment by bepolymathe** [comment]
Damned. Good luck for the repair.

**Comment by pbek** [comment]
## 17.08.1
- fixed linking of notes in the link dialog

**Comment by bepolymathe** [comment]
That's great !

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
