### ISSUE TITLE
[plugin] My html syntax highlight plugin for you

### ISSUE THREAD

**Issue by Anleitungen** [pbek/QOwnNotes#647]
Hello everyone,

because I really need some kind of syntax highlight in QOwnNotes I wrote my own plugin. And because I like to share, here it is:

```
import QtQml 2.0

/**
 * This includes prettify.js syntax highlight in html exports
 */
QtObject {
    property string prettifySyntaxhighlight;

    // register your settings variables so the user can set them in the script settings
    property variant settingsVariables: [
        {
            "identifier": "prettifySyntaxhighlight",
            "name": "CDN Url",
            "description": "Please enter the CDN Url to prettify.js:",
            "type": "text",
            "default": "https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js",
        },
    ];

    /**
     * This function is called when the markdown html of a note is generated
     * 
     * It allows you to modify this html
     * This is for example called before by the note preview
     * 
     * @param {NoteApi} note - the note object
     * @param {string} html - the html that is about to being rendered
     * @return {string} the modfied html or an empty string if nothing should be modified
     */
    function noteToMarkdownHtmlHook(note, html) {
        html = html.replace("body>", "body><script src='" + prettifySyntaxhighlight + "'></script>");
        
        html = html.replace("<pre>", "<pre class='prettyprint '\>");
        html = html.replace("<pre>", "<pre class='prettyprint '\>");  
        html = html.replace("<pre>", "<pre class='prettyprint '\>");  
        html = html.replace("<pre>", "<pre class='prettyprint '\>");  
        html = html.replace("<pre>", "<pre class='prettyprint '\>");  
        html = html.replace("<pre>", "<pre class='prettyprint '\>");  

        html = html.replace("<code>", "<code class='prettyprint '\>");  
        html = html.replace("<code>", "<code class='prettyprint '\>");
        html = html.replace("<code>", "<code class='prettyprint '\>");
        html = html.replace("<code>", "<code class='prettyprint '\>");
        html = html.replace("<code>", "<code class='prettyprint '\>");
        html = html.replace("<code>", "<code class='prettyprint '\>");
    
        return html;
    }
}
```

Just save it somewhere for example as **prettifyJsSyntaxHighlight.qml** and get some nice syntax highlighting.

Currently it uses the google prettify.js library because this library is really good at recognizing the currently used syntax. You are able to set any cdn source url within the settings page.

Todo:
Because I've never programmed in gt before I was not able to loop through the whole html content to replace all <pre> with <pre class='prettyprint'> so I decided to replace 6 occurrence for now...
**If someone is able to include for example QtRegEx and could add some kind of a loop, it would be awesome if he/she could share it.**

Also I really miss a life preview (in QOwnNotes)... is there any change to include a small html browser? If not: is there any way to use a regular Browser with some kind of auto reload on note save (to prevent the need to export it manually on every change)?

Greetings
Marco

**Comment by bepolymathe** [comment]
That's interesting. Thanks for sharing...

**Comment by pbek** [comment]
Thank you for sharing!

> Also I really miss a life preview (in QOwnNotes)

Have you already enabled the note preview panel?
But be aware that our current preview is a QTextEdit and unable to interpret javascript!

> Because I've never programmed in gt before I was not able to loop through the whole html content to replace all

If you use regular expressions in your replace and make use of the `g` modifier to replace all occurrences you can achieve that. I did that for example in <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/note-from-jira-issue.qml>.
<https://regex101.com> will also help you.

If you want you can add the improved version of your script to <https://github.com/qownnotes/scripts> as pull request.

> is there any change to include a small html browser? 

not yet, html browsers are not "small" :)

> If not: is there any way to use a regular Browser with some kind of auto reload on note save (to prevent the need to export it manually on every change)?

maybe there is a browser plugin to watch changes in an html page and reload the page if there are changes?

any thoughts @Maboroshy?

**Comment by pbek** [comment]
I will close this issue until there is more information.
