### ISSUE TITLE
New theme

### ISSUE THREAD

**Issue by bepolymathe** [pbek/QOwnNotes#648]
Hi,

Here's a theme I'm using right now that could be useful to some of you.

> [EditorColorSchema-8f324af7-8070-41e5-a707-52f20ae176e9]
> BackgroundColorEnabled_-1=true
> BackgroundColorEnabled_0=true
> BackgroundColorEnabled_1=true
> BackgroundColorEnabled_11=false
> BackgroundColorEnabled_12=true
> BackgroundColorEnabled_13=true
> BackgroundColorEnabled_14=true
> BackgroundColorEnabled_15=true
> BackgroundColorEnabled_16=true
> BackgroundColorEnabled_17=true
> BackgroundColorEnabled_18=true
> BackgroundColorEnabled_19=true
> BackgroundColorEnabled_2=true
> BackgroundColorEnabled_21=true
> BackgroundColorEnabled_22=true
> BackgroundColorEnabled_23=true
> BackgroundColorEnabled_24=false
> BackgroundColorEnabled_3=true
> BackgroundColorEnabled_4=true
> BackgroundColorEnabled_8=false
> BackgroundColorEnabled_9=true
> BackgroundColor_-1=@Variant(\0\0\0\x43\x1\xff\xff\xee\xee\xee\xee\xec\xec\0\0)
> BackgroundColor_0=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xf8\xf8\xef\xef\0\0)
> BackgroundColor_1=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xf2\xf2\xe4\xe4\0\0)
> BackgroundColor_11=@Variant(\0\0\0\x43\x1\xff\xff\xaa\xaa\xf7\xf7\xff\xff\0\0)
> BackgroundColor_12=@Variant(\0\0\0\x43\x1\xff\xff\xf1\xf1\xf1\xf1\xf4\xf4\0\0)
> BackgroundColor_13=@Variant(\0\0\0\x43\x1\xff\xff\xf1\xf1\xf1\xf1\xf4\xf4\0\0)
> BackgroundColor_14=@Variant(\0\0\0\x43\x1\xff\xff\xf1\xf1\xf1\xf1\xf4\xf4\0\0)
> BackgroundColor_15=@Variant(\0\0\0\x43\x1\xff\xff\xf1\xf1\xf1\xf1\xf4\xf4\0\0)
> BackgroundColor_16=@Variant(\0\0\0\x43\x1\xff\xff\xf1\xf1\xf1\xf1\xf4\xf4\0\0)
> BackgroundColor_17=@Variant(\0\0\0\x43\x1\xff\xff\xf1\xf1\xf1\xf1\xf4\xf4\0\0)
> BackgroundColor_18=@Variant(\0\0\0\x43\x1\xff\xff\xfc\xfc\xe9\xe9OO\0\0)
> BackgroundColor_19=@Variant(\0\0\0\x43\x1\xff\xff\xe2\xe2\xe7\xe7\xe2\xe2\0\0)
> BackgroundColor_2=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xf2\xf2\xe4\xe4\0\0)
> BackgroundColor_21=@Variant(\0\0\0\x43\x1\xff\xff\xeb\xeb\xeb\xeb\xeb\xeb\0\0)
> BackgroundColor_22=@Variant(\0\0\0\x43\x1\xff\xff\xf7\xf7\xf6\xf6\xff\xff\0\0)
> BackgroundColor_23=@Variant(\0\0\0\x43\x1\xff\xff\xea\xea\xeb\xeb\xea\xea\0\0)
> BackgroundColor_24=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0)
> BackgroundColor_3=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0)
> BackgroundColor_4=@Variant(\0\0\0\x43\x1\xff\xff\xea\xea\xeb\xeb\xea\xea\0\0)
> BackgroundColor_8=@Variant(\0\0\0\x43\x1\xff\xff\xdb\xdb\xf9\xf9\xe5\xe5\0\0)
> BackgroundColor_9=@Variant(\0\0\0\x43\x1\xff\xff\xba\xba\xbd\xbd\xb6\xb6\0\0)
> Bold_12=true
> Bold_13=true
> Bold_14=true
> Bold_15=true
> Bold_16=true
> Bold_17=true
> Bold_24=true
> Bold_8=true
> FontSizeAdaption_12=140
> FontSizeAdaption_13=130
> FontSizeAdaption_14=120
> FontSizeAdaption_15=110
> FontSizeAdaption_16=100
> FontSizeAdaption_17=90
> FontSizeAdaption_24=80
> FontSizeAdaption_8=100
> ForegroundColorEnabled_-1=true
> ForegroundColorEnabled_0=true
> ForegroundColorEnabled_1=true
> ForegroundColorEnabled_10=true
> ForegroundColorEnabled_11=true
> ForegroundColorEnabled_12=true
> ForegroundColorEnabled_13=true
> ForegroundColorEnabled_14=true
> ForegroundColorEnabled_15=true
> ForegroundColorEnabled_16=true
> ForegroundColorEnabled_17=true
> ForegroundColorEnabled_18=true
> ForegroundColorEnabled_19=true
> ForegroundColorEnabled_2=true
> ForegroundColorEnabled_20=true
> ForegroundColorEnabled_21=true
> ForegroundColorEnabled_22=true
> ForegroundColorEnabled_23=true
> ForegroundColorEnabled_24=true
> ForegroundColorEnabled_3=true
> ForegroundColorEnabled_4=true
> ForegroundColorEnabled_5=true
> ForegroundColorEnabled_6=true
> ForegroundColorEnabled_7=true
> ForegroundColorEnabled_8=true
> ForegroundColorEnabled_9=true
> ForegroundColor_-1=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
> ForegroundColor_0=@Variant(\0\0\0\x43\x1\xff\xff\x34\x34\x65\x65\xa4\xa4\0\0)
> ForegroundColor_1=@Variant(\0\0\0\x43\x1\xff\xff\xfc\xfc~~\0\0\0\0)
> ForegroundColor_10=@Variant(\0\0\0\x43\x1\xff\xff\xa3\xa3\0\0{{\0\0)
> ForegroundColor_11=@Variant(\0\0\0\x43\x1\xff\xff\xab\xab\xab\xab\xab\xab\0\0)
> ForegroundColor_12=@Variant(\0\0\0\x43\x1\xff\xff\0\0\x31\x31nn\0\0)
> ForegroundColor_13=@Variant(\0\0\0\x43\x1\xff\xff\0\0\x31\x31nn\0\0)
> ForegroundColor_14=@Variant(\0\0\0\x43\x1\xff\xff\0\0\x31\x31nn\0\0)
> ForegroundColor_15=@Variant(\0\0\0\x43\x1\xff\xff\0\0\x31\x31nn\0\0)
> ForegroundColor_16=@Variant(\0\0\0\x43\x1\xff\xff\0\0\x31\x31nn\0\0)
> ForegroundColor_17=@Variant(\0\0\0\x43\x1\xff\xff\0\0\x31\x31nn\0\0)
> ForegroundColor_18=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
> ForegroundColor_19=@Variant(\0\0\0\x43\x1\xff\xff\0\0\x80\x80\0\0\0\0)
> ForegroundColor_2=@Variant(\0\0\0\x43\x1\xff\xff\xfc\xfc~~\0\0\0\0)
> ForegroundColor_20="@Variant(\0\0\0\x43\x1\xff\xff======\0\0)"
> ForegroundColor_21=@Variant(\0\0\0\x43\x1\xff\xff\x39\x39\x39\x39\x39\x39\0\0)
> ForegroundColor_22=@Variant(\0\0\0\x43\x1\xff\xffNN\x18\x18\xb9\xb9\0\0)
> ForegroundColor_23=@Variant(\0\0\0\x43\x1\xff\xff\0\0\x80\x80\0\0\0\0)
> ForegroundColor_24=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
> ForegroundColor_3=@Variant(\0\0\0\x43\x1\xff\xffrr\x9f\x9f\xcf\xcf\0\0)
> ForegroundColor_4=@Variant(\0\0\0\x43\x1\xff\xff\0\0\x80\x80\0\0\0\0)
> ForegroundColor_5="@Variant(\0\0\0\x43\x1\xff\xff======\0\0)"
> ForegroundColor_6="@Variant(\0\0\0\x43\x1\xff\xff======\0\0)"
> ForegroundColor_7=@Variant(\0\0\0\x43\x1\xff\xff\xc1\xc1}}\x11\x11\0\0)
> ForegroundColor_8=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
> ForegroundColor_9=@Variant(\0\0\0\x43\x1\xff\xff\xa3\xa3\0\0{{\0\0)
> Italic_7=true
> Name=bepolymathe-light
> Underline_18=true
> 
> [Export]
> SchemaKey=EditorColorSchema-8f324af7-8070-41e5-a707-52f20ae176e9

In theory, you just have to copy / paste into a text editor and save the file to `name.ini`
Then import the file into the QownNotes theme editor. If somebody can test it...
Enjoy
Good night

**Comment by pbek** [comment]
Thank you! I will test and add it.

**Comment by pbek** [comment]
## 17.08.0
- added a new editor color schema *Bepolymathe Light* (thank you @bepolymathe)

**Comment by bepolymathe** [comment]
thanks to you ;-)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by bepolymathe** [comment]
Hi @pbek 

I test it with the new release 17.08.0 - OBS - build 362 ... but it don't work. 

![capture du 2017-08-01 08-39-06](https://user-images.githubusercontent.com/29939805/28812418-f120bc74-7694-11e7-9c7b-2ac43085b89f.png)

**Comment by pbek** [comment]
Please describe "don't work".

**Comment by bepolymathe** [comment]
If I select the theme, the colors do not load. On the other hand, police and emphases seem to be taken into account.
I keep looking more precisely... after a second coffee ;)

**Comment by pbek** [comment]
I didn't see any colors neither. Maybe that information got destroyed with the posting of your ini. Can you please rename your exported ini to `.txt` so that you can upload the file to GitHub (or upload it somewhere else).

**Comment by pbek** [comment]
What did you export?
Your schema, or the broken schema I added? :)

We need your original one, that you pasted in GitHub.

**Comment by bepolymathe** [comment]
I have exported the original file (which works at home) ...
Here it is without renaming it (in .ini)
[Bépolymathe-light.ini](https://framadrop.org/r/m4jYlQ-Jqp#pZNt4Bd45oyhPzooPdxWXWTHSasz4nmk75oi+AfyCQw=)

And if i copy/paste here (like the first time) 

> [EditorColorSchema-8f324af7-8070-41e5-a707-52f20ae176e9]
BackgroundColorEnabled_-1=true
BackgroundColorEnabled_0=true
BackgroundColorEnabled_1=true
BackgroundColorEnabled_11=false
BackgroundColorEnabled_12=true
BackgroundColorEnabled_13=true
BackgroundColorEnabled_14=true
BackgroundColorEnabled_15=true
BackgroundColorEnabled_16=true
BackgroundColorEnabled_17=true
BackgroundColorEnabled_18=true
BackgroundColorEnabled_19=true
BackgroundColorEnabled_2=true
BackgroundColorEnabled_21=true
BackgroundColorEnabled_22=true
BackgroundColorEnabled_23=true
BackgroundColorEnabled_24=false
BackgroundColorEnabled_3=true
BackgroundColorEnabled_4=true
BackgroundColorEnabled_8=false
BackgroundColorEnabled_9=true
BackgroundColor_-1=@Variant(\0\0\0\x43\x1\xff\xff\xee\xee\xee\xee\xec\xec\0\0)
BackgroundColor_0=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xf8\xf8\xef\xef\0\0)
BackgroundColor_1=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xf2\xf2\xe4\xe4\0\0)
BackgroundColor_11=@Variant(\0\0\0\x43\x1\xff\xff\xaa\xaa\xf7\xf7\xff\xff\0\0)
BackgroundColor_12=@Variant(\0\0\0\x43\x1\xff\xff\xf1\xf1\xf1\xf1\xf4\xf4\0\0)
BackgroundColor_13=@Variant(\0\0\0\x43\x1\xff\xff\xf1\xf1\xf1\xf1\xf4\xf4\0\0)
BackgroundColor_14=@Variant(\0\0\0\x43\x1\xff\xff\xf1\xf1\xf1\xf1\xf4\xf4\0\0)
BackgroundColor_15=@Variant(\0\0\0\x43\x1\xff\xff\xf1\xf1\xf1\xf1\xf4\xf4\0\0)
BackgroundColor_16=@Variant(\0\0\0\x43\x1\xff\xff\xf1\xf1\xf1\xf1\xf4\xf4\0\0)
BackgroundColor_17=@Variant(\0\0\0\x43\x1\xff\xff\xf1\xf1\xf1\xf1\xf4\xf4\0\0)
BackgroundColor_18=@Variant(\0\0\0\x43\x1\xff\xff\xfc\xfc\xe9\xe9OO\0\0)
BackgroundColor_19=@Variant(\0\0\0\x43\x1\xff\xff\xe2\xe2\xe7\xe7\xe2\xe2\0\0)
BackgroundColor_2=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xf2\xf2\xe4\xe4\0\0)
BackgroundColor_21=@Variant(\0\0\0\x43\x1\xff\xff\xeb\xeb\xeb\xeb\xeb\xeb\0\0)
BackgroundColor_22=@Variant(\0\0\0\x43\x1\xff\xff\xf7\xf7\xf6\xf6\xff\xff\0\0)
BackgroundColor_23=@Variant(\0\0\0\x43\x1\xff\xff\xea\xea\xeb\xeb\xea\xea\0\0)
BackgroundColor_24=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0)
BackgroundColor_3=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0)
BackgroundColor_4=@Variant(\0\0\0\x43\x1\xff\xff\xea\xea\xeb\xeb\xea\xea\0\0)
BackgroundColor_8=@Variant(\0\0\0\x43\x1\xff\xff\xdb\xdb\xf9\xf9\xe5\xe5\0\0)
BackgroundColor_9=@Variant(\0\0\0\x43\x1\xff\xff\xba\xba\xbd\xbd\xb6\xb6\0\0)
Bold_12=true
Bold_13=true
Bold_14=true
Bold_15=true
Bold_16=true
Bold_17=true
Bold_24=true
Bold_8=true
FontSizeAdaption_12=140
FontSizeAdaption_13=130
FontSizeAdaption_14=120
FontSizeAdaption_15=110
FontSizeAdaption_16=100
FontSizeAdaption_17=90
FontSizeAdaption_24=80
FontSizeAdaption_8=100
ForegroundColorEnabled_-1=true
ForegroundColorEnabled_0=true
ForegroundColorEnabled_1=true
ForegroundColorEnabled_10=true
ForegroundColorEnabled_11=true
ForegroundColorEnabled_12=true
ForegroundColorEnabled_13=true
ForegroundColorEnabled_14=true
ForegroundColorEnabled_15=true
ForegroundColorEnabled_16=true
ForegroundColorEnabled_17=true
ForegroundColorEnabled_18=true
ForegroundColorEnabled_19=true
ForegroundColorEnabled_2=true
ForegroundColorEnabled_20=true
ForegroundColorEnabled_21=true
ForegroundColorEnabled_22=true
ForegroundColorEnabled_23=true
ForegroundColorEnabled_24=true
ForegroundColorEnabled_3=true
ForegroundColorEnabled_4=true
ForegroundColorEnabled_5=true
ForegroundColorEnabled_6=true
ForegroundColorEnabled_7=true
ForegroundColorEnabled_8=true
ForegroundColorEnabled_9=true
ForegroundColor_-1=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
ForegroundColor_0=@Variant(\0\0\0\x43\x1\xff\xff\x34\x34\x65\x65\xa4\xa4\0\0)
ForegroundColor_1=@Variant(\0\0\0\x43\x1\xff\xff\xfc\xfc~~\0\0\0\0)
ForegroundColor_10=@Variant(\0\0\0\x43\x1\xff\xff\xa3\xa3\0\0{{\0\0)
ForegroundColor_11=@Variant(\0\0\0\x43\x1\xff\xff\xab\xab\xab\xab\xab\xab\0\0)
ForegroundColor_12=@Variant(\0\0\0\x43\x1\xff\xff\0\0\x31\x31nn\0\0)
ForegroundColor_13=@Variant(\0\0\0\x43\x1\xff\xff\0\0\x31\x31nn\0\0)
ForegroundColor_14=@Variant(\0\0\0\x43\x1\xff\xff\0\0\x31\x31nn\0\0)
ForegroundColor_15=@Variant(\0\0\0\x43\x1\xff\xff\0\0\x31\x31nn\0\0)
ForegroundColor_16=@Variant(\0\0\0\x43\x1\xff\xff\0\0\x31\x31nn\0\0)
ForegroundColor_17=@Variant(\0\0\0\x43\x1\xff\xff\0\0\x31\x31nn\0\0)
ForegroundColor_18=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
ForegroundColor_19=@Variant(\0\0\0\x43\x1\xff\xff\0\0\x80\x80\0\0\0\0)
ForegroundColor_2=@Variant(\0\0\0\x43\x1\xff\xff\xfc\xfc~~\0\0\0\0)
ForegroundColor_20="@Variant(\0\0\0\x43\x1\xff\xff======\0\0)"
ForegroundColor_21=@Variant(\0\0\0\x43\x1\xff\xff\x39\x39\x39\x39\x39\x39\0\0)
ForegroundColor_22=@Variant(\0\0\0\x43\x1\xff\xffNN\x18\x18\xb9\xb9\0\0)
ForegroundColor_23=@Variant(\0\0\0\x43\x1\xff\xff\0\0\x80\x80\0\0\0\0)
ForegroundColor_24=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
ForegroundColor_3=@Variant(\0\0\0\x43\x1\xff\xffrr\x9f\x9f\xcf\xcf\0\0)
ForegroundColor_4=@Variant(\0\0\0\x43\x1\xff\xff\0\0\x80\x80\0\0\0\0)
ForegroundColor_5="@Variant(\0\0\0\x43\x1\xff\xff======\0\0)"
ForegroundColor_6="@Variant(\0\0\0\x43\x1\xff\xff======\0\0)"
ForegroundColor_7=@Variant(\0\0\0\x43\x1\xff\xff\xc1\xc1}}\x11\x11\0\0)
ForegroundColor_8=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
ForegroundColor_9=@Variant(\0\0\0\x43\x1\xff\xff\xa3\xa3\0\0{{\0\0)
Italic_7=true
Name=B\xe9polymathe-light
Underline_18=true

[Export]
SchemaKey=EditorColorSchema-8f324af7-8070-41e5-a707-52f20ae176e9

**Comment by pbek** [comment]
This ini-file works. Pasting the content previously destroyed the colors. Thanks.

**Comment by bepolymathe** [comment]
Maybe an effect of github quotation syntax...

**Comment by pbek** [comment]
You can add code blocks in GitHub in markdown like this:

```ini
Italic_7=true
Name=B\xe9polymathe-light
Underline_18=true
```
see: <https://help.github.com/articles/creating-and-highlighting-code-blocks/>

**Comment by bepolymathe** [comment]
Ok ;)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by bepolymathe** [comment]
It works for me, no problem.

**Comment by pbek** [comment]
Great, thank you for testing!
