### ISSUE TITLE
About script panel 

### ISSUE THREAD

**Issue by bepolymathe** [pbek/QOwnNotes#649]
Hello,

A suggestion.
When I change the settings (theme or new script), qownnotes automatically restarts itself with the script panel enabled ... while I have disabled it.
It is not very serious but if we could not reload the panel when reloading the scripts, it would be perfect for me.
But perhaps it is more complicated than I imagine.
Beautiful day.

**Comment by pbek** [comment]
Could it be that you have a script enabled writes to the script panel? Could you please post the output of the debug settings (like stated in the issue template :smile_cat:).

**Comment by bepolymathe** [comment]
Ok. Yes, I'm a little undisciplined. 😋
Informations in debug setting are :
> 
## General Info

**Current Date**: `lun. juil. 31 10:04:48 2017`
**Version**: `17.07.9`
**Build date**: `Jul 29 2017`
**Build number**: `361`
**Platform**: `linux`
**Operating System**: `Fedora 26 (Workstation Edition)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.7.1`
**Qt Version (runtime)**: `5.7.1`
**Portable mode**: `no`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `fr_FR`
**Locale (interface)**: *empty*
**Icon theme**: `Adwaita`
**Enabled scripts**: `6`

## Enabled scripts

### Script `Note stats`

**id**: `1`
**path**: `/home/manu/.local/share/PBE/QOwnNotes/scripts/note-stats/note-stats.qml`
**variablesJson**: 
```
{
    "charNoSpaceLeftName": "",
    "charNoSpaceLeftTarget": 0,
    "charNoSpaceName": "Sans espace",
    "charSpaceLeftName": "Reste",
    "charSpaceLeftTarget": 220000,
    "charSpaceName": "Caractères",
    "paragraphsLeftTarget": 0,
    "readTimeName": "Temps de lecture",
    "readTimeRate": 250,
    "wordsLeftTarget": 0,
    "wordsName": "Mots"
}
```
**identifier**: `note-stats`
**version**: `0.0.2`
**minAppVersion**: `17.06.3`

### Script `Insert text button`

**id**: `4`
**path**: `/home/manu/.local/share/PBE/QOwnNotes/scripts/insert-text/insert-text.qml`
**variablesJson**: 
```
{
    "buttonIcon": "insert-text.svg",
    "buttonName": "Commentaire",
    "menuName": "Insérer un commentaire",
    "text": "[Commentaire]: # ()"
}
```
**identifier**: `insert-text`
**version**: `0.0.1`
**minAppVersion**: `17.05.8`

### Script `External note diff`

**id**: `7`
**path**: `/home/manu/.local/share/PBE/QOwnNotes/scripts/external-note-diff/external-note-diff.qml`
**variablesJson**: 
```
{
    "executablePath": "meld"
}
```
**identifier**: `external-note-diff`
**version**: `0.0.1`
**minAppVersion**: `17.07.8`

### Script `Custom note preview styling`

**id**: `9`
**path**: `/home/manu/.local/share/PBE/QOwnNotes/scripts/preview-styling/preview-styling.qml`
**variablesJson**: 
```
{
    "customStylesheet": "h2 {margin-left: 20px;}\nh3 {margin-left: 40px;}\nh4 {margin-left: 60px;}"
}
```
**identifier**: `preview-styling`
**version**: `0.0.1`
**minAppVersion**: `17.05.7`


Do you need something else ?

**Comment by pbek** [comment]
`note-stats` uses the script panel, if you disable the script it shouldn't happen again...
Does that work for you?

**Comment by bepolymathe** [comment]
Oh, i make a mistake. You're right for script panel and `note-stats`. I need this panel ;)
It's the Custom Actions Toolbar which appears... It's `insert text button` the problem... and i find solution. Just leave empty `name of the button` and `icon of the button`... and it not charging the toolbar. 
Sorry for the inconvenience.

**Comment by pbek** [comment]
:+1:
