### ISSUE TITLE
Plurals in translation.

### ISSUE THREAD

**Issue by elnull** [pbek/QOwnNotes#65]
I'm trying to translate application to Russian in linguist.
When I translate phrases with plurals linguist complains
"Translation does not contain the necessary %n place marker."
I think you should replace "%1" in source phrases with plurals to "%n".

**Comment by pbek** [comment]
Thats great! Thanks a lot for your effort! I guess I will look into that on Saturday... 
First I have to do some workarounds for the OS X icon problem...
Of course you can make the changes yourself if you want and create a pull request. (But please tell me if you do so, so I don't do the same)

**Comment by pbek** [comment]
you should now have plural translations on the `develop` branch

**Comment by elnull** [comment]
I didn't find any errors in this version.
