### ISSUE TITLE
[Enhancement] Unlimited collapsible lists mode

### ISSUE THREAD

**Issue by pax** [pbek/QOwnNotes#650]
I'm a big fun of _collapsible lists_ – where you can add content to an item without cluttering your view [Worfowy](https://workflowy.com/) has a pretty good implementation, but it's a relatively closed system.
 
![wflowy](https://user-images.githubusercontent.com/116795/28772317-817d2a52-75ee-11e7-8b1e-eedd2dc0c173.gif)

See also:  [Checkvist](https://checkvist.com), [Dynalist](https://dynalist.io).

**Comment by pbek** [comment]
Thank you for your suggestion, but I'm sorry, the QTextEdit currently used for the preview can't view such content and neither can it interpret JS.
