### ISSUE TITLE
Updated QOwnNotes 

### ISSUE THREAD

**Issue by meliboo** [pbek/QOwnNotes#654]
Hello, 

I updated QOwnNotes to 17.08.1 and I lost my configuration such as  tags and workspaces. I was able to import my notes but I had to reconfigure everything from the beginning. There was one thing though, after the update I couldn't find the .exe file on the folder I had to re-extract the zip file. 

Thanks.

**Comment by pbek** [comment]
Thank you for reporting, but I cannot see why that should have happend. The update had only two minor fixes...

**Comment by bepolymathe** [comment]
Please post the output from the debug section in the settings dialog.

**Comment by pbek** [comment]
I will close this issue until there is more information.
