### ISSUE TITLE
New script "share by email"

### ISSUE THREAD

**Issue by bepolymathe** [pbek/QOwnNotes#655]
Hello,

I wrote a little script to share a note by mail using mail application (like a attachment). In my case (fedora, thunderbird), it works. Could you test @pbek and @Maboroshy ?
[Here to download](https://framadrop.org/r/nnvpHr1UR9#2SVAE5bEAVanQ0DuFPH1XQ7YUyXJ4NYjMXByw9mECd8=)
It's a quite basic... maybe you want complete ;)

**Comment by pbek** [comment]
Such a script is a great idea!
Can you please open that issue in <https://github.com/qownnotes/scripts/issues> and then create a pull request. ;)
The script doesn't seem to work with `kmail`, it opens just a *new email* window but the note is not attached. KMail needs to bin run with `kmail --attach`, but that doesn't work with your script, can you please add a new settings field to add parameters (and create a pull request).

**Comment by pbek** [comment]
And you may want to state in your `info.json` that users have to choose their mail client in the script settings (if you haven't already). 👍

**Comment by bepolymathe** [comment]
Ok. I try to make this. It's the first script in my life ;)

**Comment by pbek** [comment]
You are doing a great job!

**Comment by pbek** [comment]
Just post a link to the new issue here if you have created it...

**Comment by bepolymathe** [comment]
completely copied from yours ;) [here](https://github.com/qownnotes/scripts/tree/master/external-note-diff)

**Comment by bepolymathe** [comment]
Ok --» [#8](https://github.com/qownnotes/scripts/issues/8)

**Comment by pbek** [comment]
oh, I was lazy :)
