### ISSUE TITLE
Write returns to the first character

### ISSUE THREAD

**Issue by bepolymathe** [pbek/QOwnNotes#656]
It is strange but when I start QownNotes (at computer startup), I have a latency time (5 minutes approximately) during which the input text "jumps" on a regular basis to the first character of the title. 
I am in the process of writing... and suddenly, I find myself typing in the title. 
It is unmanageable. Only since today. 
Debug info after this message :

> QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `mer. août 2 21:09:05 2017`
**Version**: `17.08.1`
**Build date**: `Aug  1 2017`
**Build number**: `363`
**Platform**: `linux`
**Operating System**: `Fedora 26 (Workstation Edition)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.7.1`
**Qt Version (runtime)**: `5.7.1`
**Portable mode**: `no`
**Settings path / key**: `/home/manu/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/manu/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `fr_FR`
**Locale (interface)**: *empty*
**Icon theme**: `Adwaita`
**Notes in current note folder**: `24`
**Enabled scripts**: `6`

## Server Info

**serverUrl**: `https://cloud.indie.host`
**appIsValid**: `no`
**notesPathExists**: `unknown`
**connectionErrorMessage**: `Unknown error`

## Note folders

**currentNoteFolderId**: `2`

### Note folder `Mes notes`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/manu/SpiderOak Hive/Mes Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/manu/SpiderOak Hive/Mes Notes/notes.sqlite`

### Script `Note stats`

**id**: `1`
**path**: `/home/manu/.local/share/PBE/QOwnNotes/scripts/note-stats/note-stats.qml`
**variablesJson**: 
```
{
    "charNoSpaceLeftName": "",
    "charNoSpaceLeftTarget": 0,
    "charNoSpaceName": "Sans espace",
    "charSpaceLeftName": "Reste",
    "charSpaceLeftTarget": 220000,
    "charSpaceName": "Caractères",
    "paragraphsLeftTarget": 0,
    "readTimeName": "Temps de lecture",
    "readTimeRate": 250,
    "wordsLeftTarget": 0,
    "wordsName": "Mots"
}
```
**identifier**: `note-stats`
**version**: `0.0.2`
**minAppVersion**: `17.06.3`

### Script `Insert text button`

**id**: `4`
**path**: `/home/manu/.local/share/PBE/QOwnNotes/scripts/insert-text/insert-text.qml`
**variablesJson**: 
```
{
    "buttonIcon": "",
    "buttonName": "",
    "menuName": "Insérer un commentaire",
    "text": "[Commentaire]: # ()"
}
```
**identifier**: `insert-text`
**version**: `0.0.1`
**minAppVersion**: `17.05.8`

### Script `External note diff`

**id**: `7`
**path**: `/home/manu/.local/share/PBE/QOwnNotes/scripts/external-note-diff/external-note-diff.qml`
**variablesJson**: 
```
{
    "executablePath": "meld"
}
```
**identifier**: `external-note-diff`
**version**: `0.0.1`
**minAppVersion**: `17.07.8`

### Script `Custom note preview styling`

**id**: `9`
**path**: `/home/manu/.local/share/PBE/QOwnNotes/scripts/preview-styling/preview-styling.qml`
**variablesJson**: 
```
{
    "customStylesheet": "h2 {margin-left: 20px;}\nh3 {margin-left: 40px;}\nh4 {margin-left: 60px;}"
}
```
**identifier**: `preview-styling`
**version**: `0.0.1`
**minAppVersion**: `17.05.7`

### Script `Weather stats`

**id**: `11`
**path**: `/home/manu/.local/share/PBE/QOwnNotes/scripts/weather-stats/weather-stats.qml`
**variablesJson**: 
```
{
    "city": "Paris"
}
```
**identifier**: `weather-stats`
**version**: `0.0.3`
**minAppVersion**: `17.06.4`

### Script `sharebyemail`

**id**: `12`
**path**: `/home/manu/SpiderOak Hive/Qownnotes/sharebyemail/sharebyemail.qml`
**variablesJson**: 
```
{
    "executablePath": "thunderbird"
}
```

## Settings

**AboutDialog/geometry**: `<binary data>`
**ActionDialog/geometry**: `<binary data>`
**ActiveNoteHistoryItem**: *empty*
**Debug/fakeOldVersionNumber**: `false`
**Debug/fileLogging**: `true`
**DistractionFreeMode/editorWidthMode**: `2`
**DistractionFreeMode/isEnabled**: `false`
**DistractionFreeMode/menuBarGeometry**: `<binary data>`
**DistractionFreeMode/menuBarHeight**: `28`
**DistractionFreeMode/windowState**: `<binary data>`
**Editor/ColorSchemes**: *empty*
**Editor/CurrentSchemaKey**: `EditorColorSchema-8f324af7-8070-41e5-a707-52f20ae176ea`
**Editor/autoBracketClosing**: `true`
**Editor/autoBracketRemoval**: `true`
**FileDialog/LastPath**: `/home/manu/Images`
**FileDialog/LastPath-ExternalEditor**: `/usr/bin`
**FileDialog/LastPath-InsertAttachment**: `/home/manu/Bureau`
**FileDialog/LastPath-InsertImage**: `/home/manu/Images`
**FileDialog/LastPath-NoteHTMLExport**: `/home/manu/Bureau`
**FileDialog/LastPath-NoteMarkdownExport**: `/home/manu/Bureau`
**FileDialog/LastPath-NotePDFExport**: `/home/manu/Bureau`
**FileDialog/LastPath-SchemaExport**: `/home/manu/Bureau`
**FileDialog/LastPath-ScriptPath**: `/home/manu/SpiderOak Hive/Qownnotes/sharebyemail`
**FileDialog/LastPath-ScriptSettingsFile--executablePath**: `/bin`
**FileDialog/LastPath-ScriptSettingsFile-selected-markdown-to-bbcode-pandocPath**: `/usr/bin`
**LastUpdateCheck**: `2017-08-02T21:03:11`
**LinkDialog/geometry**: `<binary data>`
**LogWidget/criticalLog**: `true`
**LogWidget/debugLog**: `true`
**LogWidget/fatalLog**: `true`
**LogWidget/infoLog**: `true`
**LogWidget/scriptingLog**: `true`
**LogWidget/statusLog**: `true`
**LogWidget/warningLog**: `true`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `20`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `DejaVu Sans Mono,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `Cantarell,19,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `Monospace,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `Cantarell,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl**: `false`
**MainWindow/showNotesFromAllNoteSubFolders**: `true`
**NoteDialog/geometry**: `<binary data>`
**PasswordDialog/geometry**: `<binary data>`
**PiwikClientId**: `<hidden>`
**ScriptRepositoryDialog/geometry**: `<binary data>`
**ScriptRepositoryDialog/mainSplitterState**: `<binary data>`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**ShareDialog/geometry**: `<binary data>`
**ShowSystemTray**: `true`
**StartHidden**: `false`
**TableDialog/geometry**: `<binary data>`
**TodoDialog/geometry**: `<binary data>`
**TodoDialog/mainSplitterState**: `<binary data>`
**TodoDialog/showCompletedItems**: `0`
**TodoDialog/todoListSelectorSelectedItem**: `Personnel`
**UpdateDialog/geometry**: `<binary data>`
**WelcomeDialog/geometry**: `<binary data>`
**acceptAllExternalModifications**: `true`
**allowDifferentNoteFileName**: `false`
**allowOnlyOneAppInstance**: `false`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `false`
**appMetrics/notificationShown**: `true`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `2`
**currentWorkspace**: `55d01381-8171-49b3-8a4d-ae92b021db30`
**customNoteFileExtensionList**: *empty*
**darkMode**: `false`
**darkModeColors**: `true`
**darkModeTrayIcon**: `true`
**defaultNoteFileExtension**: `md`
**demoNotesCreated**: `true`
**disableAutomaticUpdateDialog**: `true`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: `/usr/bin/rstudio`
**gitCommitInterval**: `30`
**gitExecutablePath**: *empty*
**gitLogCommand**: *empty*
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**imageScaleDown**: `false`
**imageScaleDownMaximumHeight**: `1024`
**imageScaleDownMaximumWidth**: `1024`
**insertTimeFormat**: `le dd.MM.yyyy à hh:mm`
**interfaceLanguage**: *empty*
**internalIconTheme**: `false`
**itemHeight**: `24`
**markdownHighlightingEnabled**: `true`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `2`
**noteSaveIntervalTime**: `10`
**noteSubfoldersPanelDisplayAsFullTree**: `false`
**noteSubfoldersPanelHideSearch**: `false`
**noteSubfoldersPanelOrder**: `0`
**noteSubfoldersPanelShowFullPath**: `false`
**noteSubfoldersPanelShowRootFolderName**: `false`
**noteSubfoldersPanelSort**: `1`
**notesPanelOrder**: `0`
**notesPanelSort**: `1`
**notesPath**: `/home/manu/SpiderOak Hive/Mes Notes`
**notifyAllExternalModifications**: `false`
**ownCloud/ignoreNonTodoCalendars**: `true`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: `https://cloud.indie.host`
**ownCloud/supportEnabled**: `true`
**ownCloud/todoCalendarBackend**: `3`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: `https://framagenda.org/remote.php/dav/`
**ownCloud/todoCalendarCalDAVUsername**: `eporte`
**ownCloud/todoCalendarEnabledList**: `Personnel, Professionnel`
**ownCloud/todoCalendarEnabledUrlList**: `https://cloud.indie.host/remote.php/dav/calendars/bepolymathe@indie.host/personal/, https://cloud.indie.host/remote.php/dav/calendars/bepolymathe@indie.host/travail/`
**ownCloud/todoCalendarUrlList**: `https://cloud.indie.host/remote.php/dav/calendars/bepolymathe@indie.host/personal/, https://cloud.indie.host/remote.php/dav/calendars/bepolymathe@indie.host/travail/`
**ownCloud/userName**: `bepolymathe@indie.host`
**previousWorkspace**: `55d01381-8171-49b3-8a4d-ae92b021db30`
**recentNoteFolders**: `/home/manu/SpiderOak Hive/Qownnotes/Scripts, /home/manu/SpiderOak Hive/Mes Notes/Projets, /home/manu/SpiderOak Hive/Injep/Projets, /home/manu/SpiderOak Hive/Mes_Notes`
**restoreCursorPosition**: `true`
**savedSearches/noteFolder-2**: `À propos du projet de recherche (nicolas), Note 2017-08-01T21.44.40, Test 4, Note 2017-08-01T15.19.10, Test 1i, Test, Questions en suspend, Note 2017-07-31T13.55.08, Test 3, Test 2, Test 1, Note 2017-07-28T22.22.51, Note 2017-07-28T15.46.28, Setsui, Terrain, test, Éducation populaire et numérique, essai , Nouvelle notes, Programmation / Numéros, France volontaire, Délais, Annexe "terrain", Cartographie, Les références pour la sitographie  2017-07-24T19.36.35, Rapport "éducation populaire et numérique", Note 2017-07-24T14.34.55, Note 2017-07-24T13.38.18, Note 2017-07-22T21.42.14, Note 2017-07-22T21.39.13, Note 2017-07-22T21.38.25, Note 2017-07-22T21.29.16, Note 2017-07-22T21.27.50, Note 2017-07-22T21.22.53, Note 2017-07-22T21.22.20, Note 2017-07-22T21.20.23, Perspectives pour le GD, Introduction au cahiers 48, Note 2017-07-20T13.00.26`
**showMenuBar**: `true`
**showStatusBar**: `false`
**tagWasAddedToNote**: `true`
**tagsPanelHideSearch**: `false`
**tagsPanelOrder**: `0`
**tagsPanelSort**: `0`
**toolbar/1/items**: `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name**: `mainToolBar`
**toolbar/1/title**: `barre d'outils principale`
**toolbar/2/items**: `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name**: `formattingToolbar`
**toolbar/2/title**: `barre d'outils de formatage`
**toolbar/3/items**: `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name**: `insertingToolbar`
**toolbar/3/title**: `barre d'outils d'insertion`
**toolbar/4/items**: `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name**: `encryptionToolbar`
**toolbar/4/title**: `barre d'outils de chiffrement`
**toolbar/5/items**: `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name**: `windowToolbar`
**toolbar/5/title**: `barre d'outils de fenêtre`
**toolbar/6/items**: `action_Quit`
**toolbar/6/name**: `quitToolbar`
**toolbar/6/title**: `quitter la barre d’outils`
**toolbar/size**: `6`
**useUNIXNewline**: `false`
**workspace-160ecfac-e727-41ab-9504-1d1998d1b6af/name**: `Tous les panneaux`
**workspace-160ecfac-e727-41ab-9504-1d1998d1b6af/noteSubFolderDockWidgetVisible**: `true`
**workspace-160ecfac-e727-41ab-9504-1d1998d1b6af/windowState**: `<binary data>`
**workspace-39430fbb-2a98-4361-b371-0e8215e4719a/name**: `Texte+TOC`
**workspace-39430fbb-2a98-4361-b371-0e8215e4719a/noteSubFolderDockWidgetVisible**: `false`
**workspace-39430fbb-2a98-4361-b371-0e8215e4719a/windowState**: `<binary data>`
**workspace-55d01381-8171-49b3-8a4d-ae92b021db30/name**: `Optimum`
**workspace-55d01381-8171-49b3-8a4d-ae92b021db30/noteSubFolderDockWidgetVisible**: `false`
**workspace-55d01381-8171-49b3-8a4d-ae92b021db30/windowState**: `<binary data>`
**workspaces**: `160ecfac-e727-41ab-9504-1d1998d1b6af, 55d01381-8171-49b3-8a4d-ae92b021db30, 39430fbb-2a98-4361-b371-0e8215e4719a`

## System environment

**LANG**: `fr_FR.UTF-8`
**GDM_LANG**: `fr_FR.UTF-8`
**HISTCONTROL**: `ignoredups`
**HOSTNAME**: `pc-de-manu`
**USERNAME**: `manu`
**XDG_VTNR**: `2`
**XDG_SESSION_ID**: `2`
**USER**: `manu`
**DESKTOP_SESSION**: `gnome`
**PWD**: `/home/manu`
**HOME**: `/home/manu`
**JOURNAL_STREAM**: `9:33158`
**XDG_SESSION_TYPE**: `wayland`
**XDG_DATA_DIRS**: `/home/manu/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/`
**XDG_SESSION_DESKTOP**: `gnome`
**LOADEDMODULES**: *empty*at
**MAIL**: `/var/spool/mail/manu`
**SHELL**: `/bin/bash`
**XDG_CURRENT_DESKTOP**: `GNOME`
**XDG_SEAT**: `seat0`
**SHLVL**: `1`
**MODULEPATH**: `/etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles`
**GDMSESSION**: `gnome`
**LOGNAME**: `manu`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**PATH**: `/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/manu/.local/bin:/home/manu/bin`
**MODULESHOME**: `/usr/share/Modules`
**HISTSIZE**: `1000`
**LESSOPEN**: `||/usr/bin/lesspipe.sh %s`
**BASH_FUNC_module%%**: 
```
() {  eval `/usr/bin/modulecmd bash $*`
}
```
**BASH_FUNC_scl%%**: 
```
() {  local CMD=$1;
 if [ "$CMD" = "load" -o "$CMD" = "unload" ]; then
 eval "module $@";
 else
 /usr/bin/scl "$@";
 fi
}
```
**QT_IM_MODULE**: `ibus`
**XMODIFIERS**: `@im=ibus`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**XDG_MENU_PREFIX**: `gnome-`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**SESSION_MANAGER**: `local/unix:@/tmp/.ICE-unix/1634,unix/unix:/tmp/.ICE-unix/1634`
**DISPLAY**: `:0`
**WAYLAND_DISPLAY**: `wayland-0`
**DESKTOP_AUTOSTART_ID**: `10b79486ac6b53b4150170058498075600000016340025`
**GIO_LAUNCHED_DESKTOP_FILE**: `/home/manu/.config/autostart/QOwnNotes.desktop`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `2178`

**Comment by pbek** [comment]
That seems to happen on some systems, but no one could ever find out why. There is a checkbox to restore the current cursor position when opening a note in the *General settings*. Please try to turn it of and report of it then works for you.

**Comment by bepolymathe** [comment]
Yes, it looks like better turning off the checkbox.

**Comment by pbek** [comment]
:+1:

**Comment by bepolymathe** [comment]
false joy. Since this morning, I have the same phenomenon while the box is unchecked.... very strange

**Comment by pbek** [comment]
Is some other process changing the notes outside of QOwnNotes? What does the log panel say? You could try ignoring all external note changes in the *General settings*.

**Comment by bepolymathe** [comment]
Thanks for the reply. Is it that this could not be a synchronization conflict between the duration of the recording (every 10 seconds for me) and the synchronization by the client Nextcloud (automatic)...

**Comment by pbek** [comment]
## 17.08.8
- added a fix by @SmartBlug for the sporadic cursor-jumping to the top in the
  note edit (for #689)

There now is a new release, could you please test it and report if it works for you if you enable checkbox to restore the current cursor position when opening a note in the General settings again?

**Comment by bepolymathe** [comment]
It doesn't work for me.

> ## System environment

**LANG**: `fr_FR.UTF-8`
**GDM_LANG**: `fr_FR.UTF-8`
**HISTCONTROL**: `ignoredups`
**HOSTNAME**: `pc-de-manu`
**USERNAME**: `manu`
**XDG_VTNR**: `2`
**XDG_SESSION_ID**: `4`
**USER**: `manu`
**DESKTOP_SESSION**: `gnome`
**PWD**: `/home/manu`
**HOME**: `/home/manu`
**JOURNAL_STREAM**: `9:511493`
**XDG_SESSION_TYPE**: `wayland`
**XDG_DATA_DIRS**: `/home/manu/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/`
**XDG_SESSION_DESKTOP**: `gnome`
**LOADEDMODULES**: *empty*
**MAIL**: `/var/spool/mail/manu`
**SHELL**: `/bin/bash`
**XDG_CURRENT_DESKTOP**: `GNOME`
**XDG_SEAT**: `seat0`
**SHLVL**: `1`
**MODULEPATH**: `/etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles`
**GDMSESSION**: `gnome`
**LOGNAME**: `manu`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**PATH**: `/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/manu/.local/bin:/home/manu/bin`
**MODULESHOME**: `/usr/share/Modules`
**HISTSIZE**: `1000`
**LESSOPEN**: `||/usr/bin/lesspipe.sh %s`
**BASH_FUNC_module%%**: 
```
() {  eval `/usr/bin/modulecmd bash $*`
}
```
**BASH_FUNC_scl%%**: 
```
() {  local CMD=$1;
 if [ "$CMD" = "load" -o "$CMD" = "unload" ]; then
 eval "module $@";
 else
 /usr/bin/scl "$@";
 fi
}
```
**QT_IM_MODULE**: `ibus`
**XMODIFIERS**: `@im=ibus`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**XDG_MENU_PREFIX**: `gnome-`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**SESSION_MANAGER**: `local/unix:@/tmp/.ICE-unix/11620,unix/unix:/tmp/.ICE-unix/11620`
**GIO_LAUNCHED_DESKTOP_FILE**: `/usr/share/applications/QOwnNotes.desktop`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `8150`
**DISPLAY**: `:0`
**WAYLAND_DISPLAY**: `wayland-0`
**GJS_DEBUG_OUTPUT**: `stderr`
**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`

**Comment by pbek** [comment]
thank you for testing!

**Comment by pbek** [comment]
## 17.08.10
- fixed a problem with the note history when notes with the same name were 
  present in different note subfolders
- added a fix by @SmartBlug for the issue of jumping cursors for some users

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
