### ISSUE TITLE
Log window is filled with same XCB warning.

### ISSUE THREAD

**Issue by Magicloud** [pbek/QOwnNotes#657]
#### Expected behaviour
No warnings, no errors.
#### Actual behaviour
`QXcbConnection: XCB error: 8 (BadMatch), sequence: 14535, resource id: 77595616, major code: 130 (Unknown), minor code:3`
#### Steps to reproduce
KDE Neon. Start application, send it to another desktop, maximize the window.
#### Output from the debug section in the settings dialog
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Thu Aug 3 12:59:41 2017`
**Version**: `17.08.1`
**Build date**: `Aug  1 2017`
**Build number**: `363`
**Platform**: `linux`
**Operating System**: `Ubuntu 16.04.3 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.5.1`
**Qt Version (runtime)**: `5.9.1`
**Portable mode**: `no`
**Settings path / key**: `/home/local/ANT/shida/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/local/ANT/shida/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `1`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://magicloud.chickenkiller.com`
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/local/ANT/shida/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/local/ANT/shida/Notes/notes.sqlite`

## Settings

**ActiveNoteHistoryItem**: *empty*
**Debug/fakeOldVersionNumber**: `false`
**Debug/fileLogging**: `false`
**Editor/CurrentSchemaKey**: `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing**: `true`
**Editor/autoBracketRemoval**: `true`
**LastUpdateCheck**: `2017-08-03T12:54:56`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `22`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `Noto Mono,20,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font**: `Inziu Iosevka SC,20,-1,5,63,1,0,0,0,0,Bold Italic`
**MainWindow/noteTextView.code.font**: `Noto Mono,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `Inziu Iosevka SC,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl**: `false`
**PiwikClientId**: `<hidden>`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**ShowSystemTray**: `false`
**WelcomeDialog/geometry**: `<binary data>`
**acceptAllExternalModifications**: `false`
**allowDifferentNoteFileName**: `false`
**allowOnlyOneAppInstance**: `true`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `false`
**appMetrics/notificationShown**: `true`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**currentWorkspace**: `1b73579c-6c23-44a1-b880-b774280e31d7`
**customNoteFileExtensionList**: *empty*
**darkMode**: `true`
**darkModeColors**: `true`
**darkModeTrayIcon**: `true`
**defaultNoteFileExtension**: `md`
**demoNotesCreated**: `true`
**disableAutomaticUpdateDialog**: `true`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: *empty*
**gitCommitInterval**: `30`
**gitExecutablePath**: *empty*
**gitLogCommand**: *empty*
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**imageScaleDown**: `false`
**imageScaleDownMaximumHeight**: `1024`
**imageScaleDownMaximumWidth**: `1024`
**insertTimeFormat**: *empty*
**interfaceLanguage**: *empty*
**internalIconTheme**: `false`
**itemHeight**: `23`
**markdownHighlightingEnabled**: `true`
**networking/ignoreSSLErrors**: `false`
**networking/proxyType**: `2`
**noteSaveIntervalTime**: `10`
**noteSubfoldersPanelDisplayAsFullTree**: `true`
**noteSubfoldersPanelHideSearch**: `false`
**noteSubfoldersPanelOrder**: `0`
**noteSubfoldersPanelShowFullPath**: `false`
**noteSubfoldersPanelShowRootFolderName**: `false`
**noteSubfoldersPanelSort**: `0`
**notesPanelOrder**: `0`
**notesPanelSort**: `0`
**notesPath**: `/home/local/ANT/shida/Notes`
**notifyAllExternalModifications**: `true`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: `https://magicloud.chickenkiller.com`
**ownCloud/supportEnabled**: `false`
**ownCloud/todoCalendarBackend**: `3`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloud/userName**: `magicloud`
**previousWorkspace**: `bfff0772-e9f4-4f27-b30b-3b4b01a6c00c`
**restoreCursorPosition**: `false`
**savedSearches/noteFolder-1**: `Note 2017-08-02T13.17.00, Note 2017-07-31T14.25.29`
**showMenuBar**: `true`
**showStatusBar**: `true`
**tagsPanelHideSearch**: `false`
**tagsPanelOrder**: `0`
**tagsPanelSort**: `0`
**toolbar/1/items**: `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name**: `mainToolBar`
**toolbar/1/title**: `main toolbar`
**toolbar/2/items**: `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name**: `formattingToolbar`
**toolbar/2/title**: `formatting toolbar`
**toolbar/3/items**: `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name**: `insertingToolbar`
**toolbar/3/title**: `inserting toolbar`
**toolbar/4/items**: `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name**: `encryptionToolbar`
**toolbar/4/title**: `encryption toolbar`
**toolbar/5/items**: `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name**: `windowToolbar`
**toolbar/5/title**: `window toolbar`
**toolbar/6/items**: `action_Quit`
**toolbar/6/name**: `quitToolbar`
**toolbar/6/title**: `quit toolbar`
**toolbar/size**: `6`
**useUNIXNewline**: `false`
**workspace-1b73579c-6c23-44a1-b880-b774280e31d7/name**: `minimal`
**workspace-1b73579c-6c23-44a1-b880-b774280e31d7/noteSubFolderDockWidgetVisible**: `true`
**workspace-1b73579c-6c23-44a1-b880-b774280e31d7/windowState**: `<binary data>`
**workspace-bfff0772-e9f4-4f27-b30b-3b4b01a6c00c/name**: `full`
**workspace-bfff0772-e9f4-4f27-b30b-3b4b01a6c00c/noteSubFolderDockWidgetVisible**: `true`
**workspace-bfff0772-e9f4-4f27-b30b-3b4b01a6c00c/windowState**: `<binary data>`
**workspaces**: `bfff0772-e9f4-4f27-b30b-3b4b01a6c00c, 1b73579c-6c23-44a1-b880-b774280e31d7`

## System environment

**KDE_FULL_SESSION**: `true`
**GS_LIB**: `/home/local/ANT/shida/.fonts`
**PAM_KWALLET5_LOGIN**: `/run/user/1420086752/kwallet5.socket`
**USER**: `shida`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `3332`
**SHLVL**: `0`
**XCURSOR_SIZE**: `0`
**HOME**: `/home/local/ANT/shida`
**OLDPWD**: `/home/local/ANT/shida`
**DESKTOP_SESSION**: `/usr/share/xsessions/plasma`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**QT_LINUX_ACCESSIBILITY_ALWAYS_ON**: `1`
**KDE_SESSION_VERSION**: `5`
**DBUS_SESSION_BUS_ADDRESS**: `unix:abstract=/tmp/dbus-WAOZGEunkp,guid=e7b08f2fb4812df9b5dc5aa259814fc4`
**MANDATORY_PATH**: `/usr/share/gconf//usr/share/xsessions/plasma.mandatory.path`
**LOGNAME**: `shida`
**GTK_IM_MODULE**: `xim`
**_**: `/usr/bin/ssh-agent`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**XDG_SESSION_CLASS**: `user`
**DEFAULTS_PATH**: `/usr/share/gconf//usr/share/xsessions/plasma.default.path`
**XDG_SESSION_ID**: `4`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`
**XDG_RUNTIME_DIR**: `/run/user/1420086752`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**XCURSOR_THEME**: `Breeze_Snow`
**DISPLAY**: `:0`
**LANG**: `en_US.UTF-8`
**XDG_CURRENT_DESKTOP**: `KDE`
**XAUTHORITY**: `/home/local/ANT/shida/.Xauthority`
**XDG_SESSION_DESKTOP**: `KDE`
**XMODIFIERS**: `@im=ibus`
**SSH_AUTH_SOCK**: `/tmp/ssh-fKhH8rm03F6h/agent.3287`
**SHELL**: `/usr/bin/zsh`
**QT_ACCESSIBILITY**: `1`
**GPG_AGENT_INFO**: `/home/local/ANT/shida/.gnupg/S.gpg-agent:0:1`
**XDG_VTNR**: `7`
**QT_IM_MODULE**: `ibus`
**PWD**: `/home/local/ANT/shida`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-/usr/share/xsessions/plasma:/etc/xdg`
**XDG_DATA_DIRS**: `/usr/share//usr/share/xsessions/plasma:/usr/local/share/:/usr/share/`
**QT_QUICK_CONTROLS_STYLE**: `org.kde.desktop`
**KDE_SESSION_UID**: `1420086752`
**SESSION_MANAGER**: `local/u3c404f0e2ca957f9e7c8:@/tmp/.ICE-unix/3442,unix/u3c404f0e2ca957f9e7c8:/tmp/.ICE-unix/3442`
**QSG_RENDER_LOOP**: *empty*

**Comment by pbek** [comment]
Thank you for reporting. Yes, that seems to happens on some Linux systems. It's a warning that Qt throws and there seems no apparent solution for it.

**Comment by pbek** [comment]
On my KDE Neon system for example I don't get this warning...

**Comment by Magicloud** [comment]
Thanks for the reply. Also sometimes the warning could be "badwindow" instead of "badmatch".

**Comment by pbek** [comment]
The only thing that I was able to find out was that it it's a Qt "thing" and may be related to the X-server or other stuff, like in <https://bugreports.qt.io/browse/QTBUG-48453> and <http://eric.riverbankcomputing.narkive.com/CQPFy9pT/lots-of-qxcbconnection-xcb-error-8-errors>

I don't think it's a thing I can fix...
I will close this issue until there is more information.
