### ISSUE TITLE
Edition pointer returns to note beginning

### ISSUE THREAD

**Issue by Florentin68** [pbek/QOwnNotes#659]
While I'm typing, the edition pointer frequently gets back to the beginning (title) of the note

I'm having this problem on two out of three of my QOwnNotes installations.

**Comment by pbek** [comment]
please see #656

**Comment by Florentin68** [comment]
Sorry, I haven't found this topic.

**Comment by pbek** [comment]
no problem, did it help you?

**Comment by Florentin68** [comment]
I'll try this evening...

**Comment by pbek** [comment]
## 17.08.8
- added a fix by @SmartBlug for the sporadic cursor-jumping to the top in the note edit (for #689)

There now is a new release, could you please test it and report if it works for you if you enable checkbox to restore the current cursor position when opening a note in the General settings again?

**Comment by Florentin68** [comment]
It was ok for me by disabling the parameter until today.
I re-enabled the parameter after updating to 17.08.8 (linux) but the problem happens again.

**Comment by pbek** [comment]
Thank you for testing!

**Comment by SmartBlug** [comment]
Hi Florentin68,
Could you send me your Debug Information (in Settings/Debug), 
Could you also enable "logging to file" (in Settings/Debug/Debug Options) and send me the log ?
I'll try to reproduce and solve your bug too.
You explained that it's working on 2 out of 3 of your installations... all Linux with exact same parameters  ?
Are you using any sync like owncloud or nextcloud ?
Thanks,

**Comment by pbek** [comment]
## 17.08.10
- fixed a problem with the note history when notes with the same name were 
  present in different note subfolders
- added a fix by @SmartBlug for the issue of jumping cursors for some users

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Florentin68** [comment]
## 17.09.0

I've just tried again and until now I don't get the problem anymore.
Thank you!

**Comment by pbek** [comment]
Great, thank you for testing!
