### ISSUE TITLE
Notes path NOT found on server debian 8 oc 8.2.2.2

### ISSUE THREAD

**Issue by itsharrie** [pbek/QOwnNotes#66]
Hi pbek,
I have trouble connecting QOwnnNotes to my owncloud server.
On clicking 'connect to owncloud server', the 'connection status' gives me 7 times OK, however the 'notes path found on server' says 'not found'.

- QOwnNotesAPI 0.4.2 is installed on the server.
- On owncloud I have the app 'Notes 2.0.0' installed and enabled.
- In the Owncloud 'Files' app directory 'Notes' is present containing a note I made in the 'Notes' app.

I cannot figure out what I missed to get QOwnNotes find the notes path on the server.
Could you please help?
Thanks!

itsharrie

**Comment by pbek** [comment]
Hi, @itsharrie ,

can you please provide me with the debug output from the settings dialog (debug tab).

Cheers, Patrizio

**Comment by pbek** [comment]
And maybe this article will help to: http://www.qownnotes.org/Knowledge-base/QOwnNotes-settings-are-reporting-a-problem-with-my-ownCloud-path

**Comment by itsharrie** [comment]
Hi Patrizio,

Here is the debug output you asked for.
Hope it helps you find the problem.

Thanks,
Harrie

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fri Feb 12 19:46:06 2016`
**Version**: `0.98`
**Build date**: `Feb 12 2016`
**Build number**: `98`
**Platform**: `linux`
**Release**: `OBS`
**Qt Version**: `5.3.2`

## Server Info

**serverUrl**: `https://192.168.0.102`
**appIsValid**: `yes`
**serverVersion**: `8.2.2.2`
**appVersion**: `0.4.2`

## Settings

**GAnalytics-cid**: `<hidden>`
**LastUpdateCheck**: `2016-02-12T19:45:41`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `24`
**MainWindow/markdownDefaultViewMode**: `true`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `Courier,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `Cantarell,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `Cantarell,11,-1,5,50,0,0,0,0,0`
**MainWindow/showRecentNoteFolderInMainArea**: `true`
**MainWindow/windowState**: `<binary data>`
**ShowSystemTray**: `false`
**SortingModeAlphabetically**: `false`
**TodoDialog/geometry**: `<binary data>`
**TodoDialog/mainSplitterState**: `<binary data>`
**TodoDialog/showCompletedItems**: `0`
**TodoDialog/todoListSelectorSelectedItem**: `harrie`
**appMetrics/disableTracking**: `true`
**appMetrics/notificationShown**: `true`
**cryptoKey**: `<hidden>`
**defaultNoteFileExtension**: `txt`
**demoNotesCreated**: `true`
**interfaceLanguage**: *empty*
**mainSplitterSizes**: `<binary data>`
**noteSaveIntervalTime**: `10`
**notesPath**: `/home/harrie/hdata/system/info/qownnotes`
**notifyAllExternalModifications**: `true`
**ownCloud/localOwnCloudPath**: `/`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: `https://192.168.0.102`
**ownCloud/todoCalendarBackend**: `0`
**ownCloud/todoCalendarEnabledList**: `harrie, haven`
**ownCloud/todoCalendarEnabledUrlList**: `https://192.168.0.102/remote.php/caldav/calendars/harrie/harrie/, https://192.168.0.102/remote.php/caldav/calendars/harrie/haven/`
**ownCloud/todoCalendarUrlList**: `https://192.168.0.102/remote.php/caldav/calendars/harrie/harrie/, https://192.168.0.102/remote.php/caldav/calendars/harrie/haven/`
**ownCloud/userName**: `harrie`
**recentNoteFolders**: `/home/harrie/hdata`

**Comment by itsharrie** [comment]
Hi Patrizio,

In the Settings screen there is a button called 'select main ownCloud sync folder'. Below it there is an input field called 'main ownCloud sync folder'. However, I had to select the **location (path) of** the main sync folder instead, for the connection to work.
So, I think it may be better to use the label 'location of main local ownCloud sync folder'.
This would also make it clear that it is the location of the main ownCloud sync folder on the local computer (it took me a while to realize).
Hope you find this a useful comment.

By the way, my compliments for the 8 stage connection status display. Helped me quickly make the connection (after forgetting to enable QOwnNotesAPI on the server).
Thanks!

Harr

**Comment by pbek** [comment]
Thank you for your kind words an your suggestion. I renamed the button now. I was searching for a better wording for a long time.
I assume it works now, so I will close the issue.

Cheers, Patrizio

**Comment by itsharrie** [comment]
Patrizio,

I still have the problem as described above.
I sent you the debug output, could you have a look at it?
Thanks!

Harrie

**Comment by pbek** [comment]
Are you sure about your notesPath? It usually should be something like `/home/username/ownCloud/Notes`. And your localOwnCloudPath would then be `/home/username/ownCloud`, provided that you don't use selective sync. Did you have a chance to read the knowledge base article I posted above?

**Comment by itsharrie** [comment]
Patrizio,

I have a local main sync folder for owncloud called **hdata** and it is located in the root directory **/** (linux).
I assume that my localOwnCloudPath is **/hdata**.
The **path of** the localOwnCloudPath should be therefore directory **/**.
If I fill-in **/hdata** I get the message 'note path (/home/harrie/hdata/system/info/qownnotes) not in ownCloud path'. You seem to presume that the local sync folder is located in /home/harrie.
If I fill-in **/** (root directory) then it finds **hdata** and I do not get this error message.

The other problem remains: 'notes path found on server' shows 'not found'.
Do you see any hints in the following debug output, or do you have any other ideas about what's causing this problem?
Sorry for mixing two issues...
Thanks again!

Harrie

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fri Feb 12 22:47:14 2016`
**Version**: `0.98`
**Build date**: `Feb 12 2016`
**Build number**: `98`
**Platform**: `linux`
**Release**: `OBS`
**Qt Version**: `5.3.2`

## Server Info

**serverUrl**: `https://192.168.0.102`
**appIsValid**: `yes`
**serverVersion**: `8.2.2.2`
**appVersion**: `0.4.2`

## Settings

**GAnalytics-cid**: `<hidden>`
**LastUpdateCheck**: `2016-02-12T22:18:42`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `24`
**MainWindow/markdownDefaultViewMode**: `true`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `Courier,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `Cantarell,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `Cantarell,11,-1,5,50,0,0,0,0,0`
**MainWindow/showRecentNoteFolderInMainArea**: `true`
**MainWindow/windowState**: `<binary data>`
**ShowSystemTray**: `false`
**SortingModeAlphabetically**: `false`
**TodoDialog/geometry**: `<binary data>`
**TodoDialog/mainSplitterState**: `<binary data>`
**TodoDialog/showCompletedItems**: `0`
**TodoDialog/todoListSelectorSelectedItem**: `harrie`
**appMetrics/disableTracking**: `true`
**appMetrics/notificationShown**: `true`
**cryptoKey**: `<hidden>`
**defaultNoteFileExtension**: `txt`
**demoNotesCreated**: `true`
**interfaceLanguage**: *empty*
**mainSplitterSizes**: `<binary data>`
**noteSaveIntervalTime**: `10`
**notesPath**: `/home/harrie/hdata/system/info/qownnotes`
**notifyAllExternalModifications**: `true`
**ownCloud/localOwnCloudPath**: `/`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: `https://192.168.0.102`
**ownCloud/todoCalendarBackend**: `0`
**ownCloud/todoCalendarEnabledList**: `harrie, haven`
**ownCloud/todoCalendarEnabledUrlList**: `https://192.168.0.102/remote.php/caldav/calendars/harrie/harrie/, https://192.168.0.102/remote.php/caldav/calendars/harrie/haven/`
**ownCloud/todoCalendarUrlList**: `https://192.168.0.102/remote.php/caldav/calendars/harrie/harrie/, https://192.168.0.102/remote.php/caldav/calendars/harrie/haven/`
**ownCloud/userName**: `harrie`
**recentNoteFolders**: `/home/harrie/h

**Comment by pbek** [comment]
Do you use *selective sync* (of the ownCloud client)? Does the ownCloud notes app find the notes you create in QOwnNotes?

**Comment by itsharrie** [comment]
Patrizio,
Yes, I am using selective sync, I guess.
Notes made with QOwnNotes do not appear in the Ntes app in owncloud.
Harrie

**Comment by pbek** [comment]
QOwnNotes doesn't sync your note, you need the ownCloud sync client to do that for you. Did you sync your `/Notes` folder from your ownCloud server to your local desktop computer? Can you see the text files from the ownCloud notes app on your desktop computer?

**Comment by itsharrie** [comment]
Patrizio,
That did it!
It now works fine!
Thanks a lot for a great app!
Harrie

**Comment by pbek** [comment]
Thank you for your kind words. What did you finally do to make it work?

**Comment by itsharrie** [comment]
I created a folder '/home/harrie/Notes' and I set it to sync with the
'Notes' folder on ownCloud (using the ownCloud desktop client). Then I
changed the field 'main ownCloud sync folder' (on the Settings dialog of
QOwnNotes) to '/home/harrie'. That did it.

I was confused due to the fact that /home/harrie is not my 'main
ownCloud sync folder', i.e. I do not sync all contents of my home folder
with ownCloud. I use selective sync instead. 
Because QOwnNotes requires a connection with the ownCloud server, I did
not expect that syncing the notes folder must be set in the ownCloud
desktop client explicitly.

Possible solution (for both standard and selective sync)
In the Settings dialog:
      * Change button label 'select main ownCloud sync folder' to
        'Select local notes folder (synced with ownCloud "Notes"
        folder)'
      * Change field label 'main ownCloud sync folder:' to 'Local notes
        folder:'
      * Now, let the user select the local notes folder and store this
        path into variable 'notesPath' (see debug info).

Using standard sync, the path in my case, would be:
'/home/harrie/ownCloud/Notes'
Using selective sync, the path in my case  would be
'/home/harrie/Notes', because I put the notes folder there myself.

I would, if possible, not use the variable 'ownCloud/localownCloudPath'
anymore, because it does not really exist in case of selective sync.

Hope I could be of any help!

Harrie

**Comment by pbek** [comment]
Thank you for your report!
There already is an issue for requesting better support for selective sync of ownCloud.
issue #36

To make every notes folder remotely and locally configurable will be quite some work.
It's still on my todo list.
I'll close this issue now, you can subscribe to issue issue #36 if you want.

**Comment by pbek** [comment]
@itsharrie, you can now use selective sync with the just released version 1.2.8. Can you please be so kind and report if it works for you.

**Comment by dspaan** [comment]
I know this is 2 years later but can someone give me a guide on how to sync my notes with owncloud and also share them with someone via owncloud? I read posts above but don't know if these instructions apply anymore. I tried a lot but can't get it to work. My ownclound server folder is set to https://myserver/owncloud.

First i got an error that i didn't have a Notes folder so i created one in my main owncloud tree. This synced to my local windows folder D:\ownCloud\Notes so i went to settings > note files and set the path to local notes folder the same as D:\ownCloud\Notes.

But i'm getting an error when i want to share a note?

edit: It's working now, i had to wait till the note was uploaded to owncloud before i could share it. Is there a way to do some more advanced sharing? Like i want to share all notes in a certain category or folder or with tag with another Owncloud user?

**Comment by pbek** [comment]
> Like i want to share all notes in a certain category or folder or with tag with another Owncloud user?

to my knowledge that isn't possible with owncloud/nextcloud, the current share feature just uses the servers share feature...

but you could copy all those note files in one folder and try to share that folder...
