### ISSUE TITLE
How do I relaunch/bring to front the existing window?

### ISSUE THREAD

**Issue by nikhilw** [pbek/QOwnNotes#660]
I have a simple question. I have been using 'show in system tray' option, so when I close the window it goes back to system tray and I can open it by clicking the tray icon. I would like to bring it to front with a command or key-press combination. Ex: Super+a should bring the window to front.
I am unable to find a command line flag that says reuse open window. If I launch 'QOwnNotes' it launches a new instance, `QOwnNotes --help` or `-h` are launching new instance. `man QOwnNotes` has nothing to show. I could not find a shortcut in 'shortcuts' option either.
 
How can I launch qownnotes in the same window from command line, essentially just bringing it to front from system tray?

**Comment by pbek** [comment]
Did you check `Only allow one app instance at the same time` in the *General settings*? That could help you out if your OS or desktop environment doesn't handle that already.

Does that answer your question?

**Comment by nikhilw** [comment]
Yes! I knew there must be something.. Superb.. It worked. Thanks..
I have come to be a fan of this notes app, I am surprised that even when I was actively looking fro this, with these exact features, I took so long to find it. This project should get more focus!

**Comment by pbek** [comment]
Feel free to promote it wherever you like and to visit <http://www.qownnotes.org/Knowledge-base/How-can-I-get-involved-with-QOwnNotes>! :smile_cat: 
btw. you can use the search-function in the settings, but I'm not sure if that would have helped you in this case...

**Comment by pbek** [comment]
## 17.08.2
- when `Show in system tray` will be checked in the *Window menu* then the 
  user will now receive a notification if `Allow only one app instance` isn't 
  enabled in the settings

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by nikhilw** [comment]
Just checked, the popup did show up. You guys are superb! I did send tips to all Linux sites I follow, seems none have taken it to actual post in the last week; except for one which replied that they had already posted about QOwnNotes in a previous list-post and I likely had missed it. :(

One thing regarding the pop-up, there is a typo in the text; it says "You way want to", instead of "You may want to"; you may want to fix that! :D

**Comment by pbek** [comment]
> One thing regarding the pop-up, there is a typo in the text; it says "You way want to", instead of "You may want to"; you may want to fix that! :D

Thank you, will be fixed in the next release!
