### ISSUE TITLE
Translation enhancements.

### ISSUE THREAD

**Issue by elnull** [pbek/QOwnNotes#67]
I translated app to [Russian](https://drive.google.com/file/d/0B3bW9z-roCCkZlJlemY1ck9qck0/view?usp=sharing).
There are pair issues with text in my opinion.
1. Language names in selection box should be written in native script so that user always could read it in his own language. I made an example in my translation.
2. In my opinion, there are some strings that shouldn't be translated at all. I marked them in my translation with comment "translation is not needed".

**Comment by pbek** [comment]
Awesome, thanks a lot! I will create the new selection and update the build scripts tomorrow. Do you want to create a pull request for the file to take GitHub credit for it?
I think you are right about 1) and 2), I will take a look at that tomorrow!

**Comment by elnull** [comment]
No, I don't want to create pull request.

**Comment by pbek** [comment]
Ok, then I will simply use your file and mention you in the change log.

**Comment by pbek** [comment]
Your Russian translation and your two suggestions are now implemented and will be released with version 0.99! A big thank you!

**Comment by pbek** [comment]
Version 0.99 should be out in a few minutes.

**Comment by pbek** [comment]
Please be so kind and report back if everything looks ok to you.

**Comment by elnull** [comment]
I've updated translation up to version 0.99. There are left some strings that shouldn't be translated. I marked them in my translation with comment "translation is not needed".

**Comment by pbek** [comment]
Thank you, I already spotted that. I will search the corresponding places in the source code.

**Comment by pbek** [comment]
I now disabled the translation for all but one of your suggested spots. 
I guess it would be better to let "Error Message" in the settings dialog translatable.
Thanks a lot for your help, @elnull!
