### ISSUE TITLE
New theme colored                       

### ISSUE THREAD

**Issue by bepolymathe** [pbek/QOwnNotes#675]
Hi,

I just adapt a new theme for a friend who need contrast... I share it.
[Download .ini](https://framadrop.org/r/sHD8HQxRi-#lbLhk0ZS5QS8DpbyXgSAAZIWtGeQvVv1We5zdb71RPg=)

**Comment by pbek** [comment]
Thank you, I will integrate it in the next release.

**Comment by pbek** [comment]
## 17.08.5
- added a new editor color schema *Bepolymathe Colorize* (thank you @bepolymathe)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by bepolymathe** [comment]
It works for me. No problem.

**Comment by pbek** [comment]
Thank you for testing!
