### ISSUE TITLE
Feature request: multi-term search in file names

### ISSUE THREAD

**Issue by abaco** [pbek/QOwnNotes#678]
It's currently possible to search for multiple space-separated terms in the file *contents*, but not in the file *names*. So e.g. searching for "one two" would find `one two three.md` but not `one and two.md`.

A multi-term search would allow you to put categories/tags in the file names, as described e.g. [here](http://bettermess.com/plain-text-primer-nvalt-101/). As far as I understand Notational Velocity and nvALT can do that. I don't know about the implementation effort, but from the user's perspective it shouldn't be a problem to see additional search results.

**Comment by pbek** [comment]
Search for `one two`, that would find your note with both words in the headline or are you talking about something else?

**Comment by abaco** [comment]
I'm talking about the file name, also when "Allow note file name to be different from headline" is enabled.

**Comment by pbek** [comment]
Ok, that wouldn't work currently.

**Comment by pbek** [comment]
took a while, but now just for you:

## 17.08.6
- you can now also search for filenames of notes in the note search line-edit, 
  instead of just for note-text

**Comment by abaco** [comment]
It works beautifully, many many thanks!!

It amazes me that QOwnNotes has all the features I need, and I'm only using a tiny part of its capabilities. I think it's great that you don't follow the (overrated) "scratch your own itch" or "do one thing and do it well" maxims. Keep up the great work! 👏

**Comment by pbek** [comment]
Thank you. I "scratched my own itch" in the first release of QOwnNotes. :) This was the 368th release...
