### ISSUE TITLE
Creating a Zettelkasten template

### ISSUE THREAD

**Issue by lvvvvvl** [pbek/QOwnNotes#679]
First of all, thank you for such a wonderful program. I can see the immense effort and thought that is going into such a great tool. 

I recently discovered the [Zettelkasten](http://zettelkasten.de/posts/overview/) method of taking notes and QOwnNotes is exactly perfect for this.

I'm trying to create a template for my notes and discovered the 'action script' feature which seems to be the way to go.

I found the demo custom script template for meeting notes and although I have no clue about javascript I'd like to modify it for this purpose. This is what I got but it doesn't seem to work:

```
import QtQml 2.0
import QOwnNotesTypes 1.0

/**
 * This script is an example for creating custom actions, that can be invoked 
 * via menu entries and buttons
 */
QtObject {
    /**
     * Initializes the custom actions
     */
    function init() {
        // create a menu entry "Create meeting note" with a button and a freedesktop theme icon
        script.registerCustomAction("createMeetingNote", "Create meeting note", "Meeting note", "task-new");
    }

    /**
     * This function is invoked when a custom action is triggered
     * in the menu or via button
     * 
     * @param identifier string the identifier defined in registerCustomAction
     */
    function customActionInvoked(identifier) {
        script.log("customActionInvoked - " + identifier);

        switch (identifier) {
            // create a new note with a custom content
            case "createMeetingNote":
                var date = new Date();
                // create the headline
				var text = m.getDate() + ("0" + (m.getMonth()+1)).slice(-2) + ("0" + m.getFullYear()).slice(-2) + ("0" + (m.getHours()+1)).slice(-2) + ("0" + (m.getMinutes()+1).slice(-2)) + Title + "\n";
                var underline = "";

                // add the underline for the headline
                for (var i = 0; i < (text.length - 1); i++) {
                    underline += "-";
                }

                // add some text to our meeting note
                text += underline + "\n\n Note\n\n\n#keywords\n\n### Cf\n\n---\n\n### References\n\n";

                // create a new note
                script.createNote(text);
                break;
        }
    }
}
```

Essentially the Zettel method follows this structure:

```
**1708170958 Improve the structure of essays by rewriting**

Benjamin Franklin improved his writing skill by re-writing other author's articles (Isaacson 2004, p. 28):

* Take notes when reading on single scraps of paper. (Like in the reading workflow for a Zettelkasten)
* Shuffle the notes sometimes
* When the original content is forgotten, write an essay based on your notes and compare to the original
* Sometimes try to write in verse instead

Cf. <http://www.earlyamerica.com/lives/franklin/chapt1/>

#writing #essay #practice #zettelkasten

---
References:

Walter Isaacson (2004):  Benjamin Franklin. An American Life, New York and London and Toronto and Sydney: Simon and Schuster Paperbacks.
```

How would I go about replicating this? So that the headline follows the same date structure (ddMMyyhhmm) alongside with sections fo confering, keywords and referencing?

Thank you once again for such a versatile little tool.

**Comment by pbek** [comment]
Thank you for your kind words. :)

What did you expect your script to do and what did happen?
Did you get an error message in the log panel or in the script settings?

**Comment by lvvvvvl** [comment]
No problem Patrizio. 

Essentially I expected the script to create a new note with the headline:

> 1708170958 Title

and then fill out the body text after with:

> Note
> 
> #keywords
> 
> ### C.f
> 
> ### References

So that I could quickly populate those fields similar to the example of Benjamin Franklin. 

When I click the 'Create meeting note' action button nothing seems to happen. Before I edited the action script, it was working perfectly for creating action notes. I'm running version 17.08.05. 

Though it could be also great to offer a Zettelkasten script in the repository for everyone as after the author [Ryan Holiday](https://ryanholiday.net/the-notecard-system-the-key-for-remembering-organizing-and-using-everything-you-read/) revealed his research technique many are trying to adopt a digital version of the system but there's no functional and regularly updated windows software apart from yours.

**Comment by pbek** [comment]
If you turn on the log panel you would see the warning `ReferenceError: m is not defined` ;)

**Comment by lvvvvvl** [comment]
Maybe that might be a correlated issue because when I click "Show Log" or the "show log panel" through "Find Action" nothing happens either. This program is a standalone exe right, no installation required?

What part of the script would I go about to define 'm'?

**Comment by pbek** [comment]
try

```javascript
import QtQml 2.0
import QOwnNotesTypes 1.0

/**
 * This script is an example for creating custom actions, that can be invoked 
 * via menu entries and buttons
 */
QtObject {
    /**
     * Initializes the custom actions
     */
    function init() {
        // create a menu entry "Create Zettelkasten note" with a button and a freedesktop theme icon
        script.registerCustomAction("createZettelkastenNote", "Create Zettelkasten note", "Zettelkasten note", "task-new");
    }

    /**
     * This function is invoked when a custom action is triggered
     * in the menu or via button
     * 
     * @param identifier string the identifier defined in registerCustomAction
     */
    function customActionInvoked(identifier) {
        script.log("customActionInvoked - " + identifier);

        switch (identifier) {
            // create a new note with a custom content
            case "createZettelkastenNote":
                var m = new Date();
                // create the headline
                var text = m.getFullYear() + ("0" + (m.getMonth()+1)).slice(-2) + ("0" + m.getDate()).slice(-2) + ("0" + m.getHours()).slice(-2) + ("0" + m.getMinutes()).slice(-2) + ("0" + m.getSeconds()).slice(-2) + " Title\n";

                var underline = "";

                // add the underline for the headline
                for (var i = 0; i < (text.length - 1); i++) {
                    underline += "-";
                }

                // add some text to our Zettelkasten note
                text += underline + "\n\n Note\n\n\n# keywords\n\n### Cf\n\n---\n\n### References\n\n";

                // create a new note
                script.createNote(text);
                break;
        }
    }
}
```

**Comment by pbek** [comment]
> Maybe that might be a correlated issue because when I click "Show Log" or the "show log panel" through "Find Action" nothing happens either. This program is a standalone exe right, no installation required?

maybe you have resized it somehow and can't see it

**Comment by lvvvvvl** [comment]
Awesome, that fixed it!

One more thing. How would I structure it so that the date appears ddMMyyhhmm instead of the current display?

And is there anyway to write the keywords in the script text so that the #keyword markdown doesn't create a H1 entry?

**Comment by pbek** [comment]
> How would I structure it so that the date appears ddMMyyhhmm instead of the current display?

you have to order the parts in `var text = m.getFullYear() + ("0" + (m.getMonth()+1)).slice(-2) + ("0" + m.getDate()).slice(-2) + ("0" + m.getHours()).slice(-2) + ("0" + m.getMinutes()).slice(-2) + ("0" + m.getSeconds()).slice(-2) + " Title\n";` around

> And is there anyway to write the keywords in the script text so that the #keyword markdown doesn't create a H1 entry?

Can you please explain in more detail what you are talking about? :)

**Comment by bepolymathe** [comment]
Interesting method.

**Comment by bepolymathe** [comment]
How you imagine to use it with Qownnotes ?

**Comment by abaco** [comment]
@lvvvvvl I think it's best to leave the `#` for markdown formatting. The guys at [zettelkasten.de](http://zettelkasten.de/posts/intratextual-tags/) use a `§` for tags; [others](http://bettermess.com/plain-text-primer-nvalt-101/) use a `@`.

If you *really* need hashes (say, you want to copy-paste them to twitter) you can enclose the tags section in triple backquotes:
```
``` <- this stars a code block
#writing #essay #practice #zettelkasten
``` <- and this ends it
```

**Comment by lvvvvvl** [comment]
@pbek You're a legend! Thanks so much 👍 

@bepolymathe Well essentially the Zettel method was a paper index card box each assigned with unique id's to cross reference each note and thereby create an idea 'cluster' or group that would aid in making memory connections, creativity and writing easy Outlines. Qownnotes is perfect for this purpose when wanting a digital version of this as I can automatically generate id's for each note using the script above based on the date, it allows interlinking notes, search is great, it saves everything in separate plain text files using markdown (which prevents me from being 'locked in' by the software and easily transferable in the future is needed) and I can easily backup the notes folder through Dropbox. 

@abaco That's a good point, I think I'll use the `@` instead :)

**Comment by blausand** [comment]
Of course, i'd expect QOwnNotes to recognize and parse the tags and adopt them to the Tags section.

**Comment by pbek** [comment]
I will close this issue now.
