### ISSUE TITLE
New theme "Mountain"

### ISSUE THREAD

**Issue by bepolymathe** [pbek/QOwnNotes#680]
Just for fun, a new theme build during a coffee break.
[Download here](https://framadrop.org/r/IVUTtwvr_f#NYh9vutVYcdWZTgGsLz22b5pYW6XqzTKKIP8IxumnQw=)

**Comment by pbek** [comment]
Thank you, I will include it! :)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by bepolymathe** [comment]
It works.

**Comment by pbek** [comment]
Great, thank you for testing!
