### ISSUE TITLE
Arc colorscheme/theme

### ISSUE THREAD

**Issue by johanson** [pbek/QOwnNotes#687]
Something that fits the popular arc-dark theme. Maybe someone finds it useful.

[arc.ini.txt](https://github.com/pbek/QOwnNotes/files/1237016/arc.ini.txt)

**Comment by pbek** [comment]
Thank you for your theme, I will add it to the next release!

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by johanson** [comment]
Awesome, got it with the update and it works. Thank you for the great project.
Don't need to worry now when installing QOwnNotes on my other machines!

**Comment by pbek** [comment]
Thank you for your contribution!

**Comment by Viperoo** [comment]
Nice theme!
