### ISSUE TITLE
A firefox user script to enhance converting HTML to markdown

### ISSUE THREAD

**Issue by vanleo2001** [pbek/QOwnNotes#692]
In [String length limit with "ctrl-shift-v" #645](https://github.com/pbek/QOwnNotes/issues/645), I mentioned when using copy function in firefox, some line breaks will be auto inserted into html source in clipboard. If it is converted to markdown when using "paste html and media" function in QOwnNotes, these line breaks will also present. So I write a greasemonkey user script to remove it. This script will romove unnecessary white space also.

Please enjoy it from https://github.com/vanleo2001/Copy-Helper-for-QOwnNotes-script

**Comment by pbek** [comment]
Thank you for stepping in, @vanleo2001!

**Comment by pbek** [comment]
btw. didn't the fixes from version 17.08.0 in #645 work for you?

**Comment by vanleo2001** [comment]
Yes, it works. In fact, this user script DOES convert HTML to markdown all except <img> tag. QON will convert <img> and download images into local "media" folder.

**Comment by pbek** [comment]
Ah, I see. So the user-script is preparing markdown for QON. Nice.

**Comment by pbek** [comment]
I'll close this now, if you want you can create a page at <https://github.com/pbek/QOwnNotes/wiki>.
