### ISSUE TITLE
Bug: Code and preview out of sync

### ISSUE THREAD

**Issue by yodayeti** [pbek/QOwnNotes#695]
Since the last update (?) code and preview pane do not get synchronized anymore.

**Comment by pbek** [comment]
I can't reproduce that on any machine of mine. Can you please provide some more information (for example the information requested in the issue template).

**Comment by Maboroshy** [comment]
Can't reproduce too. Remember you focus on the pane you're scrolling by clicking it. If you're scrolling pane that is out of focus, it will scroll, but won't sync, as you may be writing something in the focused one.

**Comment by bepolymathe** [comment]
Can't reproduce too.

**Comment by pbek** [comment]
Oh, I thought we were talking about the content of the preview, but scrolling works too for me... if the edit panel has focus, like @Maboroshy pointed out!

**Comment by yodayeti** [comment]
After restart cannot reproduce anymore.
