### ISSUE TITLE
Scrolling by touch swipes

### ISSUE THREAD

**Issue by avkoch** [pbek/QOwnNotes#696]
Hello!
I've migrated to QOwnNotes from OneNote about 3 month ago, and I almost totally satisfied by program and it's functionality. But one thing upsets me. I can scroll text swiping up and down in OneNote, I can scroll in browser and even MS Notepad supports this way. But in QOwnNotes I can only select text.
In my everyday work I use ASUS T100 - Windows tablet with attachable keyboard and use simultaneously keyboard and touchscreen.
I admit the possibility that someone prefers select texts, but can you at least make it switchable?

**Comment by pbek** [comment]
I'm sorry I'm not sure if there is a way to achieve this easily in a Qt QWidget application and I currently have no way of testing it, since I don't own a touch enabled computer.

Do you know an other Qt QWidget application where that works?

**Comment by avkoch** [comment]
Unfortunately, I didn't found any apps which is known as using QWidget. May be you can suggest someone.
Another way is learn QT and submit appropriate code into project by myself :)

**Comment by pbek** [comment]
I will close this issue until there is more information. ;)
