### ISSUE TITLE
QOwnNotes cannot open notes folder in GNOME gvfs

### ISSUE THREAD

**Issue by janhenke** [pbek/QOwnNotes#7]
GNOME 3 integrates Owncloud access, so there is no need to run the Linux client. The Owncloud files are available via a gvfs folder.

Currently opening that folder produces a segfault. Opening QOwnNotes again, it works.

**Comment by pbek** [comment]
Is that gvfs folder mounted into the regular filesystem? QOwnNotes can only read and write to regular files. Although I never tested gvfs folder so far...

**Comment by janhenke** [comment]
It is mounted on access as far as I experienced so far. It crashes the first time you lunch QOwnNotes and you select the gvfs folder.
After the first run it does not crash any more. But if the gvfs is not mounted before starting QOwnNotes, no notes are visible. If the gvfs is mounted already, it seems to work.

**Comment by pbek** [comment]
Maybe the "mount on access" is the problem, who knows what happens meanwhile...
The notes are loaded into a in-memory sqlite database, when the program starts or the folder is changed. 
Would take a while to reproduce this error...

**Comment by janhenke** [comment]
Well it should work with it. I am not fully up to date with the file system APIs, maybe you can register for an event when the folder is available for read? To me it looks like currently you are trying to read from the folder before it is fully mounted.

**Comment by pbek** [comment]
You would have to tell me where the app segfaults by running the built source code in Qt Creator yourself...

**Comment by janhenke** [comment]
No, building myself from source should not be required. By the way I noticed the Debian package declares dependencies on some -dbg packages, please either drop that or supply debugging symbols yourself.

Anyway the stack trace from gdb:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6fb9afb in QObject::connect(QObject const*, char const*, QObject const*, char const*, Qt::ConnectionType) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
(gdb) bt full
#0  0x00007ffff6fb9afb in QObject::connect(QObject const*, char const*, QObject const*, char const*, Qt::ConnectionType) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#1  0x0000000000410653 in MainWindow::loadRecentNoteFolderListMenu() ()
No symbol table info available.
#2  0x0000000000410adb in MainWindow::storeRecentNoteFolder(QString const&) ()
No symbol table info available.
#3  0x00000000004112f4 in MainWindow::selectOwnCloudFolder() ()
No symbol table info available.
#4  0x0000000000411d01 in MainWindow::readSettings() ()
No symbol table info available.
#5  0x000000000041274a in MainWindow::MainWindow(QWidget*) ()
No symbol table info available.
#6  0x000000000040ca3b in main ()
No symbol table info available.
```

**Comment by pbek** [comment]
I had the debug packages is because some people had problems without them... really a strange thing...
thank you for the dump

**Comment by janhenke** [comment]
What kind of problems? It really should work without it. The packages just contain the symbols of the libraries. Any application should not require them.

**Comment by pbek** [comment]
They were always shown as dependencies in the release build when checking with ldd, and some had problems without them. I already tried to find out what is the cause of this...
