### ISSUE TITLE
Need support for Tamil Language - Very Oldest and Famous Language

### ISSUE THREAD

**Issue by jkathir** [pbek/QOwnNotes#702]
For tamil fonts, please go through the following steps

1. Download http://www.azhagi.com/  software which is the tamil editor like
microsoft word
2. Type the text in different font like choosing in microsoft word
3. You can see the font as well as the text
4. Make sure the text is being supported

Fonts for your kind reference: 

1. http://www.azhagi.com/freefonts.html#top1
2. http://tamil.indiatyping.com/index.php/download-tamil-font
3. http://www.freetamilfont.com/

**Comment by pbek** [comment]
There is no font included in QOwnNotes, you can select every font that is installed on your system in in the editor settings. Does this solve your problem?

**Comment by jkathir** [comment]
I need to check. Meanwhile i would like you to test with those fonts as you might be the right person to do it. Thank you.

**Comment by pbek** [comment]
I will close this question until there is more information.
