### ISSUE TITLE
Offer option for always auto referencing changed hyperlinks

### ISSUE THREAD

**Issue by yodayeti** [pbek/QOwnNotes#706]
Please add an option which allows to always auto change hyperlinks to notes whose titles get changed. In other words, allow to disable to confirmation dialogue and just always keep references healthy.

**Comment by pbek** [comment]
Thank you for your suggestion.I guess that's pretty much #485.

**Comment by pbek** [comment]
All dialogs would need to be re-implemented from scratch with that functionality... No trivial task... ;)

**Comment by pbek** [comment]
## 17.12.0
- there is now a checkbox `Don't ask again!` for most confirmation message 
  boxes and a checkbox `Don't show again!` for most information message boxes
  to override the answer for all future prompts of that message boxes
    - the message boxes will not be shown again until you reset the override
    - you can reset all overrides in the *General settings*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
