### ISSUE TITLE
Expose QTextCursor to scripting

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#707]
There are several requests for advanced actions in QTextEdit: 
#672 for changing headline levels
#569 fo moving paragraphs
there was some request for list formatting
also I want to do outline style notes, that may be the first step to resolving #550 

Mostly any of these can be done with `script.noteTextEditSelectedText()` and `script.noteTextEditWrite()`. But manually selecting text elements is not the way to do it. It'd be much better if user could simply put cursor to text element, say `# Headline`, press assigned key, like <kbd>Tab</kbd>, and have `## Headline` in place. Or press something like <kbd>Control</kbd> + <kbd>↑</kbd> and move whole block up in structure.

To do that script should be able to select the paragraph where cursor is, delete text, move cursor relatively and block-aware, then write text.

I've looked through [QTextCursor documentation](http://doc.qt.io/qt-5/qtextcursor.html). I haven't worked with it yet, so maybe I'm wrong, but looks like this class is powerful enough to do any of these with ease. Could you expose it to scripting engine altogether, rather than just reading selection and writing text.

**Comment by pbek** [comment]
I'm not sure if that can be done, but I will test it.

**Comment by pbek** [comment]
In theory the whole `mainWindow` is exposed, if you look into <https://github.com/pbek/QOwnNotes/blob/282b204b01cb0de2b7bae80115650501000f20e6/src/services/scriptingservice.cpp>, but I think it will not work anyway because QML can't handle something like a `QTextCursor`...

**Comment by Maboroshy** [comment]
[Exposing Attributes of C++ Types to QML doc](http://doc.qt.io/qt-5/qtqml-cppintegration-exposecppattributes.html) says "any functionality that is appropriately exposed by a QObject-derived class is accessible from QML code".
It also says "... if a class is to be used in a way that requires the engine to access additional type information — for example, if the class itself is to be used as a method parameter or property, or if one of its enum types is to be used in this way — then the class may need to be registered".

Getting to QTextCursor from mainWindow, if it's possible, can be painful. There are about 4-5 nesting classes between them, if understood correctly.

**Comment by pbek** [comment]
I even exposed `noteTextEdit`, in theory you should be able to do something like `noteTextEdit.textCursor()` in a script.

**Comment by Maboroshy** [comment]
I'll do some tests.

**Comment by Maboroshy** [comment]
Scripting can see noteTextEdit. `JSON.stringify(noteTextEdit)` and `JSON.stringify(noteTextEdit.document)` showed all the properties. I could not get noteTextEdit.textCursor like that yet. Only empty strings in log. May I'm doing something wrong. I'll continue poking it.

**Comment by pbek** [comment]
Can you access the properties of the [QTextDocument](http://doc.qt.io/qt-5/QTextDocument.html)?

Oh my god, I just found out QPlainTextEdit (much more performant) can use syntax highlighter as well, highlighting was the whole reason I used QTextEdit...

**Comment by pbek** [comment]
In case you want to test it, I did some quite interesting stuff in...

## 17.09.1
- the `QMarkdownTextedit`, which is used in all markdown text-edits is now based
  on`QPlainTextEdit` instead of `QTextEdit`, which should result in **improved
  rendering speed** for large notes
    - this will improve the note text edit, log panel, version dialog, trash 
      dialog, todo dialog, settings dialog, note dialog and note history dialog
- you can now choose different **interface styles** in the *Interface settings* 
  to change the look of the application's interface and its controls
    - the style will be previewed instantly if you select an other style
    - if you select `Automatic` you will be prompted to restart the application
- the snap-packaged version of QOwnNotes will now automatically use the `Fusion`
  interface style, which dramatically improves the styling of the user interface

**Comment by ludenticus** [comment]
I've tried the interface style > Adwaita (which is my default theme), and it goes perfect.

One side observation: when I select a header from the navigation menu, it highlights the  corresponding text under the editor; however, the viewer doesn't move. This is not a problem while editing, but only if you have a workspace, say with viewer & navigation.

**Comment by pbek** [comment]
It doesn't update because the note text edit doesn't have the focus. But I guess that can be dealt with, please open an other issue.

**Comment by Maboroshy** [comment]
New UI features work for me. Interface styling, text edit widget, all good. Breeze still the best for me. I should look deeper into that styling feature, maybe I can make margins between panes smaller with it to give the app more modern look.

Great that there is more performance in already one of the fastest markdown apps available.

> Can you access the properties of the QTextDocument?

`JSON.stringify(noteTextEdit.document)` showed me properties for QTextDocument, but looks like that stopped working after the fresh update. Now only `JSON.stringify(noteTextEdit)` works.
`JSON.stringify(noteTextEdit.textCursor)` doesn't work either.

I can't check QTextDocument directly, because I don't yet know the instance name app use. 

Maybe I can't go down to properties that are objects itself due to that tip in the docs I mentioned:
"... if a class is to be used in a way that requires the engine to access additional type information — for example, if the class itself is to be used as a method parameter or property, or if one of its enum types is to be used in this way — then the class may need to be registered".

I'm not sure I understand Qt or object-oriented programming enough to completely understand it though.

**Comment by pbek** [comment]
Thank you for the feedback!

> JSON.stringify(noteTextEdit.document) showed me properties for QTextDocument, but looks like that stopped working after the fresh update. 

Strange, according to <http://doc.qt.io/qt-5/qplaintextedit.html#document> it should be still a QTextDocument.

I register it here: <https://github.com/pbek/QOwnNotes/blob/76e1fdbe85b2a2bafc485d50d37b7c0be61add48/src/mainwindow.cpp#L861>

Some other things are done here: <https://github.com/pbek/QOwnNotes/blob/76e1fdbe85b2a2bafc485d50d37b7c0be61add48/src/services/scriptingservice.cpp#L41>

**Comment by pbek** [comment]
@Maboroshy, the first place is also the quickest way to test to expose objects in the scripting engine (if you want to try some out)
