### ISSUE TITLE
Markdown highlight issue

### ISSUE THREAD

**Issue by elnull** [pbek/QOwnNotes#71]
There is a small issue with code highlight in editor mode.

These two test blocks are highlighting as code

http://pastebin.com/pcEuHkq2

while two others are not

http://pastebin.com/eCS8KtQY

**Comment by pbek** [comment]
Yes, as soon as there is an empty line in the code, it isn't highlighted any more.
I'll see if I can do something about that in the hoedown parser...

**Comment by pbek** [comment]
I fixed that now in the markdown highlighter.
will look like that in version 1.0.1...

![screenshot-code](https://cloud.githubusercontent.com/assets/1798101/13053483/03254d24-d405-11e5-92d4-e1aeefe37426.png)

**Comment by elnull** [comment]
I checked new version. Thank you for fix.

**Comment by pbek** [comment]
Are you always building from source yourself or just for testing purposes? :smile_cat: What OS are you using, if I may ask.

**Comment by elnull** [comment]
I'm building from source just for testing. Sometimes I build software when upstream version doesn't fulfil my needs. I'm using Ubuntu and Debian.

**Comment by pbek** [comment]
Good man, building from source FTW :grin: 
Debian & Ubuntu, at least I have those repositories covered... :wink:
