### ISSUE TITLE
The search textbox is cleared after remove note

### ISSUE THREAD

**Issue by jefersonsv** [pbek/QOwnNotes#718]
The keyword typed should be held even after the action of remove note.

Unfortunatelly after remove one note the search text box is cleared.

Step to reproduce:
1 - Type any keywork to find a note
2 - Right click in any note
3 - Click "Remove Notes" and confirm "Remove"
The search input text is cleared.

**Comment by pbek** [comment]
I'm sorry, I can't reproduce that. I doesn't clear the search box for me.
Please fill out the full issue template.

**Comment by bepolymathe** [comment]
I have the same behaviour on linux. Deleting a note resets the search. The search box becomes empty.

**Comment by pbek** [comment]
I haven't found a system where I have this phaenomenon...

**Comment by pbek** [comment]
I will close this issue until there is more information.
