### ISSUE TITLE
Allow the new version popup dialog to be disabled

### ISSUE THREAD

**Issue by robled** [pbek/QOwnNotes#72]
In the case of users who install QOwnNotes via their package manager, this popup should be something they can disable so that they can get updates through normal means.

**Comment by calis2002** [comment]
Or even better check if installed via package manager and if yes don't show popup window AND settings for it at all.

**Comment by pbek** [comment]
but then there also is no changelog display, with often important messages...
I will think of something...

**Comment by pbek** [comment]
For version 1.0.2 I've implemented this behavior:

- you can now disable the automatic update dialog in the settings
    - for self-build versions of QOwnNotes or versions from repositories 
      the automatic update dialog is disabled by default
- in any case you will get a flat button on the bottom right if there is an 
  update available

How does that sound?

**Comment by robled** [comment]
Sounds great, thanks!

**Comment by pbek** [comment]
v1.0.2 is out now ;)

**Comment by pbek** [comment]
I'll close that issue now.
