### ISSUE TITLE
How to deploy qownnotes on linux?

### ISSUE THREAD

**Issue by CJSoldier** [pbek/QOwnNotes#729]
I can handle it via windoployqt.exe on win7. On ubuntu, I tried to copy all dependent .so file to some directory and export several envionment variables just as [this article said](https://lemirep.wordpress.com/2013/06/01/deploying-qt-applications-on-linux-and-windows-3/). When I copy all those files to other pc, I can run qownnotes, but some icon disappeared and I can't input any character.

**Comment by pbek** [comment]
Do you want to deploy all Qt libraries as well? You could try to create a snap package like I did here: <https://git.launchpad.net/~pbek/qownnotes-snap/tree/snapcraft.yaml>

**Comment by CJSoldier** [comment]
Sorry pbek, I can't open the link. My browser reads
> OOPS-c13cf799a36de01069caadcdd4631dba

Actually I just want to make my compiled qownnotes easily used by others on ubuntu. In windows we just copy a directory contains .exe file to others. I don't know how to accomplish that in linux.

I realized that maybe I can't package all QT libraries because of QT's license. If I make a snap package, can I copy it directly to others to install?

**Comment by pbek** [comment]
Can you read <https://git.launchpad.net/~pbek/qownnotes-snap/tree>?

> Actually I just want to make my compiled qownnotes easily used by others on ubuntu. 

You can also create a DEB-Package, like I do via TravisCI in <https://github.com/pbek/QOwnNotes/blob/develop/.travis.yml>.

Do you have so many changes that are not of interest to other users? What did you change? (Do you have a repository online?)

> If I make a snap package, can I copy it directly to others to install?

Yes. You can also experiment with AppImages. Like I use it here: <https://build.opensuse.org/package/binaries/home:pbek:QOwnNotes/desktop?repository=AppImage>

**Comment by CJSoldier** [comment]
No, I don't even have any changes,qownnotes is excellent and I'll recommend it to my friends. I don't have a repository online either.
I asked many people, they don't know how to  deploy app on linux. Thanks pbek, I'll try to make a snap package.

**Comment by pbek** [comment]
Why do you want to bother to create your own repository then? :laughing: 

If you don't even have changes I suppose you could derive from my launchpad repository: <https://launchpad.net/~pbek/+archive/ubuntu/qownnotes>, or if that's not possible from <https://build.opensuse.org/package/show/home:pbek:QOwnNotes/desktop>.

**Comment by pbek** [comment]
> I asked many people, they don't know how to deploy app on linux.

you really mean "deploy" and not "install", right?

**Comment by CJSoldier** [comment]
I'm sorry to say "deploy", I want to say "package" at first, but I'm not really sure. I don't want to deploy an app to a repository, oh my god, why would I say "deploy". I just want to compile a QT program, and then copy it to others to use. I don't expect he has already installed QT,so I expect he could execute a program directly. Does it call package or install?

**Comment by pbek** [comment]
`package` would be ok (if it's a package) :)
Might I ask why you get into the packing-hassle when you don't have any changes?

**Comment by CJSoldier** [comment]
I'm just curious about  how to package a program on linux in case that I will modify source code someday. :)

**Comment by pbek** [comment]
Then search in the repository for `snap`, `obs` and `launchpad`. You might find some treasures there... It took me many weeks (full-time) to get everything you see on <http://www.qownnotes.org/installation> working.

**Comment by CJSoldier** [comment]
Thank you for your hard working, pbek.

**Comment by pbek** [comment]
It also started with curiosity. :smiley: Let me know if you need anything...
