### ISSUE TITLE
Last symbol is not highlighted

### ISSUE THREAD

**Issue by elnull** [pbek/QOwnNotes#73]
In some strange case last symbol of line may not highlight correctly.
Here is an example of such note http://pastebin.com/w5McBRHq

![1455616399](https://cloud.githubusercontent.com/assets/169721/13072871/9a8d1e06-d4ac-11e5-8bdd-a8fdfbe65135.png)

**Comment by pbek** [comment]
Thank you for the report.
There are some characters, that are troubling the highlighter, in this case it's the `»`.
I will see if I can get hold on that.

**Comment by pbek** [comment]
Meanwhile please keep reporting if you find other characters, that do the same.

**Comment by pbek** [comment]
I finally did it. It will be fixed in version 1.0.2. Please be so kind to tell me if it worked for you and thank you for reporting such stuff!

**Comment by elnull** [comment]
This issue was resolved. Thank you for fix!

**Comment by pbek** [comment]
Great! Thank you too!
