### ISSUE TITLE
the table  about md

### ISSUE THREAD

**Issue by qux-bbb** [pbek/QOwnNotes#730]
#### The table of md cannot display appropriatly，can we improve it？

**Comment by pbek** [comment]
Can you please explain in more detail and step by step what you did, what happened and what you expected.

**Comment by qux-bbb** [comment]
The  appropriate displaying should be:  

|a|b|c|
|---|---|---|
|aa|bb|cc|

But QOwnNotes display it without outlines.

**Comment by pbek** [comment]
You can install the script *custom note preview styling* and style it all you like (or is possible).

**Comment by qux-bbb** [comment]
It's difficult to define a table displaying by custom note preview styling.

**Comment by pbek** [comment]
Anything you need help with?

**Comment by qux-bbb** [comment]
Emmm, Wish someone can help me out.

**Comment by pbek** [comment]
Maybe you should formulate a question someone could help you with... :smile_cat: 

Did you already read the the description of the script *custom note preview styling* and went to <http://doc.qt.io/qt-5/richtext-html-subset.html>?

You can also try to use the *Markdown-it markdown parser* script, maybe you like its rendering more.

**Comment by qux-bbb** [comment]
I use the  ` custom note preview styling`, but the dispalying is odd.
My custom code is:  
<pre>
table, tr, th, td{border-collapse:collapse;}
table, tr, th, td{border-width: 1px;}
table, tr, th, td{border-style: solid;}
table, tr, th, td{border-color: red;}
</pre>  
But the `table, tr, th, td{border-collapse:collapse;}` cannot work.

**Comment by pbek** [comment]
are borders supported by QTextEdit?

**Comment by qux-bbb** [comment]
I write this:
<pre>
| a | b | c |
|---|---|---|
| aa | bb | cc |
| aaa | bbb | ccc |
</pre>
My custom code is:
<pre>
table, tr, th, td{border-collapse:collapse;}
table, tr, th, td{border-width: 1px;}
table, tr, th, td{border-style: solid;}
table, tr, th, td{border-color: red;}
</pre>
But it displays like this:
![display](http://ww2.sinaimg.cn/large/0060lm7Tly1fk7nxplgs1j302j01v0hb.jpg)  

I think it means some of those custom code is working, but some not.

**Comment by pbek** [comment]
what are you expecting to see?
did you check on <http://doc.qt.io/qt-5/richtext-html-subset.html>? no `border-collapse` there...

**Comment by qux-bbb** [comment]
What I want to see is this：
![expect](http://ww2.sinaimg.cn/large/0060lm7Tly1fk7okjnxwqj303x02ndfl.jpg
)  
`border-collapse`  is not in  the supported lists.  
How should  I  do to get what I want?

**Comment by pbek** [comment]
Then I guess there currently is no way to get this...
You can always search the internet if someone else has done it: <https://duckduckgo.com/?q=qtextedit+border-collapse&t=canonical&ia=web>

**Comment by qux-bbb** [comment]
Thanks for your help.

**Comment by pbek** [comment]
Somewhere in the future we may have a fully fledged browser as preview (with all its advantages and disadvantages).
