### ISSUE TITLE
App crash on note folder reload

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#731]
Looks like I've localized the app crash I've been getting while testing #530. And it has nothing to do with the scripting. Tested with no scripts enabled.

#### Steps to reproduce  
1. In empty folder create 1 note in folder's root and 1 sub-folder.
2. Select the note.
3. Hit "reload note folder". Looks ok.
4. Select empty sub-folder. Note list is empty, note's text is still there. 
5. Hit "reload note folder". App crashes silently.

**Comment by pbek** [comment]
I'll see if I get that too...

**Comment by pbek** [comment]
I got it too, but the crash seemed to appear in the log-widget, which doesn't help a lot.

**Comment by pbek** [comment]
## 17.10.0
- fixed a crash with empty note-subfolders and manual reloading of the note folder

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Maboroshy** [comment]
I can't reproduce the bug in new version.

**Comment by pbek** [comment]
Great, thank you for testing!
