### ISSUE TITLE
windowToolbar not editable in settings menu

### ISSUE THREAD

**Issue by huckepick** [pbek/QOwnNotes#734]
I want to remove buttons from the windowToolbar but it es grayed out and not editable.

Is there a reason for that which I don't see?

**Comment by pbek** [comment]
I'm sorry that menu will be tampered with at run-time. You could turn that toolbar off and add your own toolbar with the buttons you need.

**Comment by pbek** [comment]
Does that answer your question?

**Comment by huckepick** [comment]
Good point. That will do!
