### ISSUE TITLE
feature suggestion : visually highlight dead note:// link and create new note when dead link is ctrl + clicked

### ISSUE THREAD

**Issue by huckepick** [pbek/QOwnNotes#736]
I come from the world of ResophNotes, NotationalVelocity, NvALT, nvpy, ...

All of them implement the following features which - in my view - would be great to have in QOwnNotes.

a)
I think it is very convenient that dead note:// links are visually highlighted.
A typical way would be a dashed underline and maybe additionally a red font.

b)
It is also very convienient to be able to create a new (WANTED) note when a dead link is ctrl + clicked.
The name of the new note would be exactly the one given in the link.

**Comment by pbek** [comment]
Thank you for your suggestion.
a) for that would be needed to check all note every time one changes a note, that's not very performant
b) that may be convenient

**Comment by huckepick** [comment]
You may be right and maybe it's not that easy to implement.

a)
I guess you simply need:
- a list of all existing note identifiers at all times - which you probably have already
- and you only need to check the note which is focused at the moment after it changed - which you probably have to do already in order to update the highlighting

(another advantage of this feature:
- if you accidentally deleted a note, changed the note identifier, broke a link by deleting a character - you will be able to notice it 
)

b)
One could argue that this very feature is quite helpful in itself, even without the highlighting.
On the other hand, clicking it, expecting to be forwarded to an existing note, and surprisingly creating a note would be somewhat strange for the user.
I think it's still worth a try but maybe in order to prevent that surprise it would be good to check whether the linked note already exitsts and if it doesn't you would show a dialog like "This note doesn't exist yet. Do you want to create it?".

(another advantage of this feature:
- Creating new non-orphan notes gets easier and you save several steps. Currently you have to create a new note. Then you have to go to the note you want to link from. Then you insert a note link. With the new feature you simply write a link into the note you want to link from, click-create, and you are done.
)

**Comment by pbek** [comment]
@huckepick, @DendrocoposMajor, @Alex-Intection

## 18.03.9
- you can now choose to create a new note when clicking on a "broken" note-link in the note edit or the preview

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Alex-Intection** [comment]
> src/mainwindow.cpp

```
originalFileName = Utils::Misc::toStartCase(
                    originalFileName.replace("_", " "));
```

As far as i understand this you convert it to StartCase -> first letter capitalize. Can you leave this out, or is it needed for your app to work?

> Thank you for your kind words! :)

As a developer i always think we need to give some respect back to others :-)

**Comment by pbek** [comment]
> As far as i understand this you convert it to StartCase -> first letter capitalize. Can you leave this out, or is it needed for your app to work?

Without it it's all lower-case.

> As a developer i always think we need to give some respect back to others :-)

I see, a fellow developer! Nice. :)

**Comment by pbek** [comment]
that was quite a piece of work, I hope there are no regressions ;)

## 18.03.10
- broken note-links are now highlighted in the note edit
    - there is a new entry `Broken link` in the *Color schema* settings where
      you can change the styling

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by huckepick** [comment]
I tested the features and they work fine.
Sorry for my late reply.

**Comment by pbek** [comment]
Great, thank you for testing! ;)
