### ISSUE TITLE
lazy update of markdown highlighting

### ISSUE THREAD

**Issue by huckepick** [pbek/QOwnNotes#737]
# Version
17.10.1

# how to reproduce
- write text without formatting
- go into line below and write one dash
-> text gets highlighted as header
- delete dash
-> text is still highlighted as header

- moving cursor position or editing the note elsewhere does not update the highlighting
- the text gets displayed as normal unformatted text when:
a) switching notes back and forth
b) deleting the linebreak directly at the end of the text

# expected behaviour
- correct update of the markdown highlighting after note edit, probably with some delay on purpose but no need to switch notes or delete linebreaks

# question
Is that a bug or is this intended?

**Comment by pbek** [comment]
Currently that's the way the Qt highlighting works and I have not found a way around this.
