### ISSUE TITLE
Option to start minimized

### ISSUE THREAD

**Issue by ftiede** [pbek/QOwnNotes#738]
Currently QOwnNotes starts with a window which is a bit annoying when starting it while logging in to a session. An option to start the software minimized, probably to the systray if configured, would be great.

**Comment by pbek** [comment]
Please take a closer look at the *Windows* menu. ;)

**Comment by ftiede** [comment]
Sorry, I expected it somewhere in Settings, not in Windows. My apologies.

**Comment by pbek** [comment]
Sorry for the inconsistency.
