### ISSUE TITLE
Ask for note name when creating new note

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#740]
On new tag or new note sub-folder creation app asks for a name. But it doesn't do that when creating new note. User has to rename new note in most cases. I propose to fix this inconsistency by showing same "ask for name" dialog when creating new note by button or by context menu.

**Comment by pbek** [comment]
Nah, the whole reason I created QOwnNotes was to create a note very quickly without asking for a name! :laughing: That was the main feature of the very first release.

If you want a name just enter it in the note search line-edit and press enter...

**Comment by pbek** [comment]
And you always can open a dialog in a script with the hook that set the note name...

**Comment by Maboroshy** [comment]
`handleNewNoteHeadlineHook` works only for headline. It doesn't change new note name if headline = name option is off.
Using `handleNoteTextFileNameHook` will require some very hacky solutions I rather not implement.

**Comment by pbek** [comment]
Can't you live with the shortcut to get to the search line-edit and enter the name there?

**Comment by Maboroshy** [comment]
I can, but it looks kind of anachronism in the current UI. There are options to disable search lines for all panes, and I do enable all of them. I like to use as minimalistic UI as possible. And, as I've stated earlier, all other nameable items ask for name when created by context menu. But main item - note doesn't.

**Comment by pbek** [comment]
Asking for a note name would defy the main reason I wrote QOwnNotes.

**Comment by Maboroshy** [comment]
Fair enough. Could you add parameter to `handleNewNoteHeadlineHook` so it would also effect note file name.

**Comment by Maboroshy** [comment]
Nah, won't work this way, since it returns note text.

**Comment by pbek** [comment]
## 17.10.3
- you now can enable in the *General settings* that the shortcut to create new 
  notes asks for a headline of the note instead of generating the headline 
  automatically

**Comment by pbek** [comment]
in addition just for you:

## 17.10.3
- there now is a new scripting command `script.inputDialogGetText` to open a
  input dialog with a line edit
    - for more information please take a look at [Opening an input dialog with a line edit](http://docs.qownnotes.org/en/develop/scripting/README.html#opening-an-input-dialog-with-a-line-edit)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Maboroshy** [comment]
It asks for a note name and creates note with that name ... but it creates `Note 2017-10-09...` and jumps to it at the same time.

**Comment by pbek** [comment]
> creates note with that name ... but it creates Note 2017-10-09.

which of the two is it then?
It didn't do that for me, do you have any script enabled that might interfere?

**Comment by Maboroshy** [comment]
It creates two notes: one that with the given name and headline, other with default name and headline.
I disabled all the scripts and restarted the app. Same result.

**Comment by pbek** [comment]
That's strange, I will take a look at the code tomorrow.

**Comment by pbek** [comment]
## 17.10.4
- fixed that a 2nd note is created if the non-automatic headline for new 
  notes is enabled

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by ludenticus** [comment]
17.10.3 was producing two notes, but it is now fixed in 17.10.4

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by Maboroshy** [comment]
I confirm. Everything works properly now. Thanks for this feature. I think it makes the app more consistent.

I posted into wrong issue at first. :dizzy_face:

**Comment by pbek** [comment]
As always, your wish is my command. :smile_cat:

(me too) :fearful:
