### ISSUE TITLE
subfolder panel not available on MacOSX

### ISSUE THREAD

**Issue by antoineschmitt** [pbek/QOwnNotes#741]
Title says it all : the subfolder panel (to create and list subfolders of the main Notes Folder) is not available in the MacOSX version (QOwnNotes - version 17.10.2). I looked for it everywhere and it is not there. Any reason ?

Sorry if this was already addressed, but I did not find any reference to this issue anywhere..
Thanks !

**Comment by pbek** [comment]
Did you enable subfolder support for the note folder?

**Comment by antoineschmitt** [comment]
! No, I did not, I did not see it. Now I did it (in Preferences->Notes Folder), and it works fine, thanks !
I would advise to enable this option by default, as it is quite hidden.. ;-)
Thanks !

**Comment by pbek** [comment]
Subfolders are not really supported by the Nextcloud Notes app...

**Comment by SeriousM** [comment]
> Did you enable subfolder support for the note folder?

... well, I searched for 20 minutes to find the setting

> I would advise to enable this option by default

That's right!

> Subfolders are not really supported by the Nextcloud Notes app...

What do you mean by saying that?
Does that mean that when I want to have synced notes, I can't use subfolders?

**Comment by pbek** [comment]
> Does that mean that when I want to have synced notes, I can't use subfolders?

I think you now can use them but Notes shows all files flat in a list...

**Comment by SeriousM** [comment]
> did you try searching for sub-folder in the search-bar in the settings dialog?

no, I assumed that this is a standard behavior and was just searching for the folder-panel in the menu.
