### ISSUE TITLE
Note links to notes, which name includes only digits, doesn't work

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#748]
Note links to notes, which name includes only digits, doesn't work.

Names that include digits and punctuation marks work.

**Comment by pbek** [comment]
Thank you for reporting, I will look into that.

**Comment by pbek** [comment]
That was a tricky one, the numbers got converted to an ip-address by QUrl...

**Comment by pbek** [comment]
I made a workaround for the note edit, in the preview there is currently no way to make them work because I only get a QUrl (with the ip-address) back...

**Comment by pbek** [comment]
## 17.10.5
- fixed links to notes whose names only consist of numbers when `Ctrl`-clicking
  them in the note text edit, in the preview there is currently no way to make
  them work

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Maboroshy** [comment]
All works the same way as you've posted.

**Comment by pbek** [comment]
Great, thank you for testing!
