### ISSUE TITLE
Make the updater less intrusive

### ISSUE THREAD

**Issue by zingmars** [pbek/QOwnNotes#751]
This is more of a request than a bug report, but please, make the auto-updater less intrusive. Right now it's seriously making me consider turning off automatic updating.

The problem is that when QOwnNotes finds an update, it pops up a dialogue saying that there's an update. That's good and all, but the problem is that it will take focus, meaning that if you're playing a video game or watching a movie (especially in exclusive fullscreen mode) you will now need get up and alt+tab back which can be quite an annoyance especially when the application gets an update what seems to be every other day (I'm not saying frequent updates are a bad thing, but combined with the intrusive pop-up, it can get a bit annoying).

Perhaps a better option would be to instead show the dialogue when QOwnNotes is opened from tray or otherwise properly focused. I certainly think that would be better UX than the current system.

Note: I'm using Windows 10.

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
The focus stealing did not happen for me under Windows 8, but I tried something to prevent occasions of it...

## 17.10.7
- tried to prevent some occasions of focus stealing of the automatic update dialog

**Comment by pbek** [comment]
There now is a new release, can you please update and test it after the next update.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by zingmars** [comment]
Yup, the window popped up in the background this time. I'll test tomorrow if it steals focus from full-screen video games or not, but so far it seems to be working.

**Comment by pbek** [comment]
There is a setting in the *Debug settings* to fake an old version number, in case you want to test after updating...

**Comment by zingmars** [comment]
Sorry for taking so long to get back to you.

Yup, works just fine. Thanks!

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by zingmars** [comment]
@pbek Hi, the issue appears to be back (though in a different form). When the updater pops up, it also unhides QOwnNotes, which is pretty annoying if you had it on full screen and only have 1 monitor.

**Comment by pbek** [comment]
Are you talking about https://github.com/pbek/QOwnNotes/issues/1514?

**Comment by zingmars** [comment]
I suppose that was the issue that introduced this behaviour, but this "fix" is the kind that makes me disable the update dialogue altogether.

> Windows seems to quit the application when the update dialog is closed while the application is hidden

And yet it worked just fine before the fix (app is hidden, update window pops up, doesn't matter how it's closed - updated or not - QOwnNotes survives in tray). Somehow I feel like this is the wrong conclusion.

**Comment by zingmars** [comment]
Oh nevermind, it happens if the window is closed using the Windows' close button, while I always hid it to tray by clicking on the tray button. Wouldn't it be possible to make the close window button do the same thing clicking on tray icon does?

**Comment by pbek** [comment]
> but this "fix" is the kind that makes me disable the update dialogue altogether.

there is nothing wrong with disabling the automatic opening, you still will see the new version in the status bar

> Wouldn't it be possible to make the close window button do the same thing clicking on tray icon does?

Even attempting to do that would have so many side effects.

**Comment by pbek** [comment]
> Even attempting to do that would have so many side effects.

basically I only get a "close" event... and there are many sources and many different reasons for that event...

I guess I close this now. :grimacing:
