### ISSUE TITLE
Translation to Brazilian Portuguese 

### ISSUE THREAD

**Issue by mlimacarlos** [pbek/QOwnNotes#76]
Hi, 

  I want to help to translate to brazilian portuguese. 

Regards, 
Marcos

**Comment by pbek** [comment]
That's awesome, thank you Marcos!
I will prepare you a translation file!

**Comment by pbek** [comment]
I hope this will help:
http://www.qownnotes.org/Knowledge-base/How-can-I-help-to-translate-QOwnNotes

**Comment by pbek** [comment]
And here is your translation file, thank you for your help!
https://github.com/pbek/QOwnNotes/blob/develop/src/languages/QOwnNotes_pt.ts

**Comment by mlimacarlos** [comment]
Tks. I will translate QownNotes soon.

**Comment by pbek** [comment]
:party:

**Comment by mlimacarlos** [comment]
Ok. I've finished translation.

**Comment by pbek** [comment]
Awesome! Thanks a lot. There were merge conflicts, I commented on your pull request.

**Comment by mlimacarlos** [comment]
Ok. I create a new pull request with file translated.

**Comment by pbek** [comment]
Your translation will be integrated in version 1.0.3. Thanks a lot for the great work!

**Comment by pbek** [comment]
Version 1.0.3 is out now. Thanks again for your effort and please feel free to maintain your translation in the future! :smile_cat:
