### ISSUE TITLE
Generate Table Of Contents

### ISSUE THREAD

**Issue by toindev** [pbek/QOwnNotes#761]
As a user, I would like to insert a Markdown table of content in my note, similar to the navigation panel. I often use QOwnNotes as a Markdown editor for my READMEs, and it is a pain to create the table by hand and update it for the long ones.

e.g.,
```
* [Introduction] (#introduction) to refer to #Introduction
```

(Hi there, and kudos for your work, QOwnNotes has quickly become one of my power tools!)

**Comment by pbek** [comment]
Thank you for your kind words. You can do that with the scripting engine: <http://docs.qownnotes.org/en/develop/scripting/README.html> (try a custom action that writes text to your note)

If you need help, @Maboroshy or I can help.

**Comment by pbek** [comment]
If you create a nice script you can make a pull request to <https://github.com/qownnotes/scripts>, so that everyone can make use of your creation.

**Comment by toindev** [comment]
I'll have a look at it then, thanks.

**Comment by pbek** [comment]
It's basically:

- get the text from current note
- parse it for the headline structure
- generate TOC text
- put it at the cursor position in the current note

**Comment by DutchPete** [comment]
I am verrrry interested in this too, I use ToC's a lot because a number of my notes tend to be long with headings. There is a script in the repository called insert-toc.qml, which I have installed but it does not do anything. I don't know anything about scripting, but maybe this script can be used as a basis?

**Comment by pbek** [comment]
https://github.com/qownnotes/scripts/tree/master/insert-toc should do what you need. It registers a custom action (see in the Scripting menu) to insert a TOC.

If you want navigation you might want to use the navigation panel.

**Comment by DutchPete** [comment]
The script only adds the words "Table of Contents", but does not actually add the ToC to the page.

**Comment by pbek** [comment]
Talking to the author directly always is the best option.

**Comment by toindev** [comment]
@DutchPete The script works for me. Could you open an issue on the [script repo](https://github.com/qownnotes/scripts/issues/new) and add the content of a note with the problem (don't forget to escape it as code, or it will be interpreted by GitHub :D ) ?

**Comment by pbek** [comment]
And please write down what you actually did and what you were expecting...

**Comment by DutchPete** [comment]
@toindev: I don't know what you mean by "escape it as code" as I am not at all familiar with the Github terminology - sorry ;-(

I just tried it again, and it works: clicking on the TOC button adds a TOC to the page.
1 feature that is missing, essential IMO, is that the TOC headings should be linked to the headings of the note, so that clicking on them takes you to that header.

**Comment by DutchPete** [comment]
@pbek:
there are markdown editors that are able to generate a TOC in the note made up of headers linked to the headers in the page, e.g. Typora. In Typora typing [toc] generates such a linked TOC. I don't know what the code is. But you could do something like that. In any case, for me personally an unlinked TOC is useless, so in the absence of a linked TOC I will continue to use the Navigator.

**Comment by toindev** [comment]
@DutchPete 'escape as code' is a MarkDown term, not GitHub specific. It means what you'll write will be shown literally, at not interpreted as Markdown. There is even an 'insert code' button in the GitHub edit box. It allows you write an example: `#This is a Markdown **example**`

@pbek There is no standard yet, but the usage is similar to my original request. The syntax is recognized in GitHub and GitLab for example, which are my primary use cases for the feature. I'll have a look at the script to add it. The links wouldn't work within QownNotes, but with the Nav Pane, it's a non-issue.
