### ISSUE TITLE
Symantec whitelisting request

### ISSUE THREAD

**Issue by giovi321** [pbek/QOwnNotes#762]
I propose to submit application for whitelisting QOwnNotes in Symantec antivirus products.
QOwnNotes is infact treated as a potential threat as it is not used by enough users known to symantec, therefore is blocked and in some corporate systems it is not allowed to whitelist it.

The link I was given in order to file the application for whitelisting is the following:
https://submit.symantec.com/false_positive/

**Comment by pbek** [comment]
Thank you for mentioning. So did you whitelist it already? I don't use that virus scanner (or any under Linux for that matter) :)

**Comment by pbek** [comment]
I will close this issue until there is more information.
