### ISSUE TITLE
Feature request: multi-window or multi-tab editing

### ISSUE THREAD

**Issue by cornercase** [pbek/QOwnNotes#765]
Is there a way to open a second QOwnNote window or have a second tab with open file with an easy way to switch between them?  It is often useful to have two note buffers open at once.  In some cases, using the "previous note/next note" functionality is undesirable and doesn't work well for mouse-based workflows.  An example is when I am keeping a list of items that are related while taking notes on a lecture.  I take notes chronologically but would also like to group certain topics logically as well.

**Comment by pbek** [comment]
I'm sorry, QOwnNotes will hardly ever be a MDI-application, that would mean a total rewrite. Although you could use the `--session <sessionname>` parameter to start completely different sessions of QOwnNotes.
And you can open multiple read-only views of notes...

**Comment by Dubidubiduu** [comment]
Maybe there could be a Button to open a read-only window which starts qownnotes with another sessionname and a read only attribute?

Or maybe it could be helpful to open one note in two windows, so you're not editing different files at the same time, but one. Just in case the file handling would be the problem.

**Comment by pbek** [comment]
You can write a script for QOwnNotes (and assign it a shortcut) that runs QOwnNotes again with the session parameter. In this new instance you can just set the readonly mode.

see: http://docs.qownnotes.org/en/develop/scripting/README.html#starting-an-external-program-in-the-background
