### ISSUE TITLE
Feature request: Multiple cursors

### ISSUE THREAD

**Issue by cornercase** [pbek/QOwnNotes#766]
As with Emacs multiple cursors, SublimeText, etc, it would be great to have multi-line editing.  I often copy/paste poorly formatted lists into QOwnNotes and would love to not have to switch to my text editor to do the cleanup or edit the lines individually.

**Comment by pbek** [comment]
I'm sorry, I haven't yet seen a way to get multiple cursors in a Qt app. If you have any information please let me know...

**Comment by lucknaumann** [comment]
@pbek FYI - KDE's Kate now supports multiple cursors.

**Comment by ArmanNisch** [comment]
+1 this would a pretty fantastic quality of life improvement.
