### ISSUE TITLE
"Show in system tray" in Settings window

### ISSUE THREAD

**Issue by Ev-Evans** [pbek/QOwnNotes#769]
I am really loving this program!

I would like to suggest the Settings window would include a toggle for "Show in system tray", maybe under "Interface" right next to "Enable dark mode tray icon".
(I just spent more than five minutes looking to enable/disable "Show in system tray", to finally find it (again) under Window > Show > Show in system tray. To me, this is not a very logical place for this toggle, at least not if this is the only place to change this setting.)

**Comment by pbek** [comment]
Thank you for your kind words and your suggestion, I'll take a look at it.
btw. there are search functions for the menu and as well for the settings dialog.

**Comment by pbek** [comment]
Wow, "moving" that settings proves to be very complicated... A lot has to go on in the background to make that happen.

**Comment by pbek** [comment]
## 17.11.4
- the settings to show the system tray icon and to start the application hidden 
  if the system tray icon is enabled were moved from the main menu to the 
  *Interface settings*
    - if the user enables the system tray icon the setting to only start one 
      instance of the application will also be enabled automatically if you are
      on Linux or Windows (macOS does that by itself)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
## 17.11.5
- changed `System tray` text in the *Interface settings* on macOS to `Menu bar`

**Comment by Ev-Evans** [comment]
A bit late, but yes, it works! Thank you for your trouble.

I would not have thought it would be so complicated since it was already an existing setting.

**Comment by pbek** [comment]
Great, thank you for testing!
