### ISSUE TITLE
Dark mode tray icon in Taskbar

### ISSUE THREAD

**Issue by Ev-Evans** [pbek/QOwnNotes#770]
Having the Dark mode tray icon enabled, the icon in the Taskbar is still the 'regular' icon.
![screenshot - 08-11-17 14_52_18](https://user-images.githubusercontent.com/33421619/32558798-f845316a-c4a5-11e7-807a-6523328cc15b.jpg)

I think it would be nice if it were possible to set both icons to dark mode, which is more consistent and looks more clean.

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
Did you enable the dark tray icon in the *General settings*?

**Comment by Maboroshy** [comment]
I think he mean the "task" icon, the one at the main taskbar rather than tray.

**Comment by pbek** [comment]
I'm not sure if I can even change that at runtime...

**Comment by pbek** [comment]
## 17.11.1
- if the setting to use a dark-mode system-tray icon is activated the 
  application-icon will also be set to the dark-mode icon
    - the setting was renamed to `Enable dark mode application icon and tray icon`

**Comment by pbek** [comment]
...although this had no effect on the icon in my KDE task bar. I guess the icon from the dektop-file is used there...

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Ev-Evans** [comment]
Yes, I meant the one on the main taskbar indeed, thank you @Maboroshy.

And yes, it works in the new release, now seeing the dark mode icon for both!
![screenshot - 12-11-17 19_59_57](https://user-images.githubusercontent.com/33421619/32702255-6808b526-c7e4-11e7-9ee1-41c52159ef47.jpg)

I also noticed the icon on the top left has changed as well, which I like, so no need to change it if you ask me, but I am not sure if this is an intended or known effect, so just pointing it out:
![screenshot - 12-11-17 19_57_24](https://user-images.githubusercontent.com/33421619/32702246-3a364640-c7e4-11e7-824d-950afcde5cb3.jpg)

**Comment by pbek** [comment]
Ah, great so that was only a KDE Taskbar thing...
Yes, the icon on the top left is the application window icon, that changed the icon in the task bar for you.
