### ISSUE TITLE
suggestion: +/- checkboxes

### ISSUE THREAD

**Issue by jcw** [pbek/QOwnNotes#775]
An idea from the "Bear" app on macOS/iOS:

* normal list entries start with `*`
* an unchecked item starts with `-`
* a checked item starts with `+`

In other words, `-` items show as unchecked boxes, clicking on them turns them into `+` items, and vice versa. As far as I can tell, this is compatible with Markdown and is very clear even when viewed as plain text. Great for check-lists which don't need the full per-item ToDo treatment via CalDav.

**Comment by pbek** [comment]
I'm sorry, that's not possible. See #235.
