### ISSUE TITLE
Tracking is not disabled

### ISSUE THREAD

**Issue by gerroon** [pbek/QOwnNotes#781]
I am using it on Debian Testing via suse repository.

Everytime my mouse is moving around  or open the settings pane or when I switch to this app Qownnotes makes queries. See yourself

 [proxychains] Strict chain  ...  127.0.0.1:8111  ...  p.qownnotes.org:443  ...  OK

Usage tracking is disabled in the settings.

This is really not cool.

thanks

**Comment by pbek** [comment]
Are you sure you turned it off? (the heartbeat too?) Without you providing the output of the debug settings I can't tell...

**Comment by pbek** [comment]
You can review the code yourself too: <https://github.com/pbek/QOwnNotes/blob/9635934252e70f8812abfff6b905e73b7bfaf649/src/services/metricsservice.cpp>

**Comment by pbek** [comment]
I will close this issue until there is more information.
