### ISSUE TITLE
Feature request: read-only mode

### ISSUE THREAD

**Issue by nivaca** [pbek/QOwnNotes#787]
I usually visit old notes only for reference purposes. Thus, I don't want to change any of the contents of those notes, and usually I do by mistake.
I would really find useful a read-only switch to disable any changes.

Thanks. Keep up the great work!

**Comment by pbek** [comment]
Thank you for your kind words and your suggestion. I think it already was asked for, you could basically just hide the note-edit-panel, but a real read-only mode would be nice too...

**Comment by Maboroshy** [comment]
Sounds like a workspace with all "damaging" item hidden.

**Comment by pbek** [comment]
I'm thinking about a mode where you just cannot edit the note text and notes will not get stored...
I wonder if adding or removing tags should be disabled too...
I certainly don't want to tamper with every panel and menu entry of QOwnNotes, I just want to prevent direct editing of notes.

Any suggestions?

**Comment by nivaca** [comment]
I have no strong thoughts either way. Whatever is the easiest and less disturbing to the overall scheme, I guess. Thanks!

**Comment by pbek** [comment]
## 17.11.5
- there now is a new item in the *Edit menu* to allow note editing (on by default) 
    - it can be toggled with a keyboard shortcut <kbd>Alt</kbd> + <kbd>⇧</kbd> + <kbd>E</kbd>
    - if turned off you cannot enter text into the note text edit and a lot 
      of menu- and toolbar-items to edit the note are turned off too

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by nivaca** [comment]
Great. It works fine for me. Is there a toolbar button available?
Thanks!

**Comment by pbek** [comment]
Great, thank you for testing!

> Is there a toolbar button available?

see above: there also in a new button in the Main toolbar if you reset your toolbars ;)
...or you can add it manually

**Comment by nivaca** [comment]
Oh, brilliant. I found it. Thanks!

**Comment by pbek** [comment]
Great ;)

**Comment by bpg168** [comment]
> Thank you for your kind words and your suggestion. I think it already was asked for, you could basically just hide the note-edit-panel, but a real read-only mode would be nice too...

How to hide the note-edit-panel? I am not able to find the Note- EDIT panel in the panel section. Version 18.09.5

**Comment by bpg168** [comment]
Did it.
Thanks :)
