### ISSUE TITLE
Add Proxy support

### ISSUE THREAD

**Issue by knobhead** [pbek/QOwnNotes#79]
Hi,

now that is one private-cloud enabled note-taking application to my likings :) Good work! :+1: 

But could you add the usual options to specify a HTTPS proxy? I'd need that in my corporate network...

Thanks!

**Comment by pbek** [comment]
Thank you for your kind words, @knobhead 

Would be doable, but will be quite some work implementing all the option...

**Comment by knobhead** [comment]
Hi @pbek, 

Thanks for your quick reply! Unfortunately, I can't help with the code. While searching on potential workarounds on this issue I noticed that some QT applications seem to adhere to environment variables for proxy settings (`http_proxy=10.0.0.1:8080`, `http_proxy=<host>:<port>`). Might this be a starting point? This can be used in restricted Windows environments, too, most likely with a `.CMD` file.

>  On a side note: note syncing itself is done by the ownCloud client (that supports proxies)

Oops, didn't get that one! Will look into that.

Cheers!

**Comment by pbek** [comment]
Thank you for your hint.
As far as I have seen Qt can also use the default OS settings for proxies, but that doesn't work on every OS... I'll have to investigate more.

**Comment by pbek** [comment]
Will be made happen in v1.0.6.

**Comment by pbek** [comment]
v1.0.6 is now out. @knobhead, can you please be so kind and test if it works for you. :smile_cat:

**Comment by knobhead** [comment]
Works like a charm here (Win7), both with system settings and own settings in QOwnNotes! Thanks!

**Comment by pbek** [comment]
Great! It took a while to get a proxy server going to test it myself. :grin:
