### ISSUE TITLE
Right click on notes should not switch to that note

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#797]
**Expected behavior**
When right-clicking a note in the 'Note-list panel' the context menu should be shown, but the currently active note should still be the note that was active before right-clicking.

**Current behavior**
The right-clicked-note becomes the active note.

**Reason**
I often want to insert a link to the right-clicked note in the currently active note. I right-click the note, and I use 'Copy link to the note clipboard' (see: #747). It would be great if the note I was working in stayed active while doing this.

If this a big change to how QON works, this use-case is probaly too specific and not worth the hassle. If it's a 'quicky' I think it would be a nice change in terms of usability (and more consistent with other apps).

**Comment by pbek** [comment]
I'm sorry, currently some features are relying on that behavior and I'm not even sure if it could be turned off in Qt, so I'll close this request.

**Comment by sanderboom** [comment]
Ok, good to know.
