### ISSUE TITLE
Keyboard Shortcut Suggestions

### ISSUE THREAD

**Issue by knobhead** [pbek/QOwnNotes#80]
I'd like to suggest three more, OS-independent keyboard shortcuts:

* <kbd>Ctrl</kbd>+<kbd>PgUp</kbd> – go to next note in note list (down) 
* <kbd>Ctrl</kbd>+<kbd>PgDn</kbd> – go to previous note in note list (up) 
* and a keyboard shortcut to switch from editing a note to the note list (up) (with the current note being focused). I'm open to <kbd>key</kbd> suggestions here :-)

What do you think?

**Comment by pbek** [comment]
I will look into that, thank you for your suggestion!

**Comment by pbek** [comment]
I implemented the functionality for the first two shortcuts in v1.0.6 (also works while notes are filtered).
@knobhead, can you please be so kind and confirm they work for you.

As for the third shortcut, there already is almost similar functionality.
I updated http://www.qownnotes.org/shortcuts/QOwnNotes to make it more clear.
You can jump to the search bar and then get to the note list from there...
Does that work for you?

**Comment by knobhead** [comment]
Cool! Thanks! Works like a charm here and helps me a lot.
I think I can live with the searchbar-workaround.

Cheers

**Comment by pbek** [comment]
Thank you for the ideas! :smile_cat:
