### ISSUE TITLE
QOwnNotes for Android

### ISSUE THREAD

**Issue by SuryaLuna** [pbek/QOwnNotes#806]
Hello,
I need to watch my Notes in Android and to edit them (minimalistic editing with only text-editing is good enough).

The Android-App should additionally be able:

- Formatted text, lists, tables (per markdown in QOwnNotes)
- Pictures, which I inserted in QOwnNotes, should be shown in the notes
- Links to other notes should be visible & clickable- then I could navigate between linked notes forward & backward
- I'd like to be able, to open attachments, which I inserted in QOwnNotes
- Tags in the notes from QOwnNotes should be visible in the notes in the Android-App. And I want to be able to search for notes per multiple-tags-search

Is this all possible? If yes, which programs and which Android-Apps do I need? And how to do that? I never made something with clouds, so I don know anything.... My QOwnNotes runs on Linux Mint 17.
I'll give you a big kiss, if you could give me a detailed how-to, step-by-step :-)
THANKS in advance!!!
.

My English is not so good, because of that I write the same in german- in hope, I'll get a german answer. I'll understand a complicated how-to in german much better.
Ich möchte in Android meine in QOwnNotes erstellten Notizen sehen & zumindest minimal bearbeiten (nur Textbearbeitung reicht) können.
Außerdem:

- Formatierter Text, Listen, Tabellen (per Markdown in QOwnNotes)
- Bilder, die ich in QOwnNotes eingefügt habe, sollen in den jeweiligen Notizen sichtbar sein
- Links zu anderen QOwnNotes-Notizen sollen sichtbar & nach Möglichkeit auch anklickbar sein, sodass ich zwischen den beiden miteinander verlinkten Notizen hin- & her wechseln kann
- Anhänge, die ich in QOwnNotes eingefügt habe, möchte ich in der Android-App öffnen können
- Tags in den QOwnNotes-Notizen sollen in der Android-App in den Notizen sichtbar sein & ich möchte in der Android-App nach Notizen per Multipler-Tagsuche suchen können.

DICKES DANKESCHÖN im Voraus!!!

**Comment by pbek** [comment]
I'm sorry. There is no Android version of QOwnNotes that could do all those things. The only thing that you can hope for is formatting text... Most note apps that work with plain text files are pretty rudimentary.

I personally use Writer+ (for viewing notes) and Synchronize Ultimate (for syncing).

**Comment by SuryaLuna** [comment]
Noooo, please no....!
I'm still hoping.... Maybe there is a possible workaround....
I saw the App "ownNote" ([https://play.google.com/store/apps/details?id=com.nowsci.ownnote](url).
They say, one can upload pictures in the notes in this App. But I don't know, if I would have to upload every single picture in every single note in the App. Or if the pictures, I inserted in the notes in QOwnNotes are visible without doing anything else (after syncing).
And I couldn't find out, if there are other Android-Apps, they could do these things.
And I couldn't find out, if this "ownNote" works with OwnCloud or with Nextcloud.
Or maybe I could upload all my notes to Dropbox (or something similar) and watch them with all mentioned features with any kind of Android-App?
And I don't know how to install and set up this OwnCloud / Nextcloud- already I asked google- but most of the detailed how-tos are in english...
PLEASE tell me, that there is a workaround... ;-)

**Comment by pbek** [comment]
There is no "workaround" that I'm aware of. If you don't care about privacy and how and where your notes are stored and locked in you could try Evernote...

**Comment by Maboroshy** [comment]
Epsilon notes can do everything except tags. To make QON relative links work you should paste simmering like the following to preprocessor in settings:
```
file://media
/storage/emulated/0/notes/media
file://attachments
/storage/emulated/0/notes/attachments
```
There are ways to make tags usable, but they are not straightforward.

**Comment by Kamechel** [comment]
Hi @SuryaLuna,
I found another app called Notes a few weeks ago and I am using it since. It says 
> View and edit notes on Nextcloud 

and it seems this is pretty much what it's doing. 
You can find Notes on [F-Droid](https://f-droid.org/packages/it.niedermann.owncloud.notes/)

**Comment by zingmars** [comment]
Aren't NextCloud and OwnCloud still API-compatible still? I know that the Android/Desktop apps still sync just fine with either and most plugins maintain compatibility with both just fine. Either way, the NextCloud Notes app (https://github.com/stefan-niedermann/nextcloud-notes) uses in NextCloud's notes app (https://github.com/nextcloud/notes) in the background. OwnCloud also has one (https://github.com/owncloud/notes), but it isn't updated apparently. Can't say if any of the new stuff not being present breaks the Android app though.

>And I couldn't find out, if this "ownNote" works with OwnCloud or with Nextcloud.
ownNote at this point is dead right now - https://github.com/Fmstrat/ownnote
You can get it to work on newer versions of *cloud, but you need to manually change the max version numbers in the configuration. There is a fork targetted specifically towards nextcloud that seems to be more active - https://github.com/brantje/nextnote (though not by much).

There's also "MyOwnNotes" that only targets OwnCloud -  https://github.com/aykit/MyOwnNotes

Sadly, I don't think any of them reach the complexity of QOwnNotes.

**Comment by pbek** [comment]
QOwnNotes is bound to Nextcloud Notes.

**Comment by pbek** [comment]
@krueuw in what ways is Joplin incompatible to QOwnNotes?

**Comment by pbek** [comment]
@krueuw have you actually looked how Joplin works internally (for example if you sync with a folder)? It generates proprietary files with all kind of non-markdown information and a generated filename like `524be592ff55491d93b4386bbb0a1e34.md`. Even the notebooks are stored that way... Joplin depends on that information. QOwnNotes / Nextcloud Notes work completely different.

**Comment by krueuw** [comment]
From the user's perspective, neither is ideal. Here is the stable mobile access is missing for at least Owncloud (Nextcloud I do not have), there you can not even change the font size. Because you want a combination.

**Comment by pbek** [comment]
> Here is the stable mobile access is missing

that's painfully true :disappointed: Joplin has an advantage there, because it's a web-app and syncs directly with sync services (although it stores its data in its own file-format).

> there you can not even change the font size. Because you want a combination.

what do you mean by this?

**Comment by Maboroshy** [comment]
@krueuw, doesn't Epsilon notes fills your needs? It even has tagging compatible with QON by a script.

**Comment by Maboroshy** [comment]
I use Resilio Sync for that. It doesn't wait long to update the notes. 
There's no shortage of file sync apps, from peer-to-peer to cloud clients.

**Comment by pbek** [comment]
I didn't even know they had an Android Client. How hard does it go on the battery?

**Comment by Maboroshy** [comment]
Drains a little but nothing major.

**Comment by pbek** [comment]
Nice!

**Comment by krueuw** [comment]
@ Pbek: The Joplin desktop client has such a tiny fixed font size that I can hardly see anything on my 4k 50 "display.

**Comment by pbek** [comment]
> The Joplin desktop client has such a tiny fixed font size that I can hardly see anything on my 4k 50 "display.

Too bad that they blocked shortcuts like `Ctrl + Plus` to zoom (it's a Chromium browser after all).
Maybe you should just file a feature request to set the zoom-level of the Electron app...

**Comment by machinekoder** [comment]
Joplin looks excellent, I think I'm moving as well. Sorry, QOwnCloud. I have tried so many options over the years, Emacs Org-Mode, Zim, Laverna, Evernote, QOwnNotes, nothing satisfied my requirements so far. Let's see if Joplin does.

**Comment by pbek** [comment]
Recently I fell in love with https://play.google.com/store/apps/details?id=it.niedermann.owncloud.notes for Android.

**Comment by pbek** [comment]
Yes, or Nextcloud.

**Comment by slidingshade** [comment]
And what about tags compatibility with QOwnNotes?

**Comment by pbek** [comment]
@slidingshade, non of them are of course. But you could play around with the script `@tag tagging in note text (experimental)` or write your own tagging script to be compatible with other apps...

**Comment by slidingshade** [comment]
Found interesting [implementation](https://github.com/Collateapp/CollateFileFormat) of tags in the note text. The author of Collate Notes application uses YAML at the beginning of a file for tags and other metadata.

**Comment by pbek** [comment]
You would be able to implement such a mechanism with the help of <http://docs.qownnotes.org/en/develop/scripting/README.html#notetagginghook>.

**Comment by slidingshade** [comment]
Is there any similar mechanism (scripting?) to change the way of inserting attachments? For instance, I'd like to save attachments with original names in the folder named something like .name_of_the_note in the same directory where the note is.

**Comment by pbek** [comment]
You can directly link to them with "Insert link". Or you could write a script with the help of the file open dialog scripting function.

**Comment by cablop** [comment]
But... well... QON works independently from the ownCloud/NextCloud services, and of all alternatives it is the one i like the most. Unlike Joplin, the other app i liked the most, QON supports filtering by multiple tags at the same time and kind of opening multiple notes at the same time.

I am dying to be able to use it from the mobile, cause mobile is becomming a nice replacement of the desktop, it is a real computer in your pocket. If i want a note taking app to assistme in my daily work, and maybe daily life, why not, QON has a lot of features Joplin doesn't. And being QT, dudes, it is much better on performance than Joplin is.

Joplin on the other hand has two very very good features... 1: It works everywhere, literally, everywhere. 2: It is not tied to a specific provider. You can go Dropbox, Mega, ResilioSync, etc. I know, i know, we can do the same with QON, but not in mobile, and moving the notes to oC or NC just because there's not a mobile client sounds really wrong.

A final word... aren't a lot of QT libraries portable to Android? Cannot someone pick the code and make a client? If i had the money and time, i would gladly do it, but sadly that'snot the case at this moment.

**Comment by cablop** [comment]
About a text editor. After testing so many i went with QuickEdit Text Editor. It is weird it is not mentioned as a MD editor out there in the wild. But it is and it does even have preview.

**Comment by Waqar144** [comment]
> I am dying to be able to use it from the mobile, cause mobile is becomming a nice replacement of the desktop, it is a real computer in your pocket. If i want a note taking app to assistme in my daily work, and maybe daily life, why not, QON has a lot of features Joplin doesn't. And being QT, dudes, it is much better on performance than Joplin is.

Thanks a lot for your words. We are working hard to keep the performance good.

> Joplin on the other hand has two very very good features... 1: It works everywhere, literally, everywhere. 2: It is not tied to a specific provider. You can go Dropbox, Mega, ResilioSync, etc. I know, i know, we can do the same with QON, but not in mobile, and moving the notes to oC or NC just because there's not a mobile client sounds really wrong.

From all my time here and what I understand, QON has a very different philosophy i.e., to give the user complete freedom with regards to their notes. You are not locked in, you can delete QON anytime and switch over to some other app quickly. That's all possible because QON is just a text editor which loads all your files at startup.

Personally I use Markor, with a tiny smb sync app on android. You press one button and all your notes are synced(provided you are on the same network). And markor works pretty well with QON.

> A final word... aren't a lot of QT libraries portable to Android? Cannot someone pick the code and make a client? If i had the money and time, i would gladly do it, but sadly that'snot the case at this moment.

It is portable, I am pretty sure of that. The 'core' library can easily be used to create an android app with QML. Though a lot of other UI features would probably need to be rewritten in QML.

**Comment by pbek** [comment]
Yes, QOwnNotes is all about choice and freedom regarding how you want to handle your notes. You can use the markdown files with every other application you want.

**Comment by cablop** [comment]
> Personally I use Markor, with a tiny smb sync app on android. You press one button and all your notes are synced(provided you are on the same network). And markor works pretty well with QON.

Markor, ok, thanks. I'll give it a look. Can we handle the tags with it? This is a real thing i'm missing in Android while using my editor.

> Yes, QOwnNotes is all about choice and freedom regarding how you want to handle your notes. You can use the markdown files with every other application you want.

Yes, that part i also like so much about QON. In fact that helped me a lot in testing many different methods for sharing the notes across devices. In the end i went with Resilio Sync and another way to periodically backup all notes from one of the PCs. But... without being able to query notes by tags on Android the experience is incomplete.

> It is portable, I am pretty sure of that. The 'core' library can easily be used to create an android app with QML. Though a lot of other UI features would probably need to be rewritten in QML.

Those are good news... so, there are ways to make an Android client, maybe with not all features, but at least tagging and being able to query by tags.

Really the tags and querying by tags is the part that is killing me now on mobile, i am heavily depending on them to manage the information.

**Comment by Waqar144** [comment]
I think Epsilon Notes has tags. Markor is pure folders.

You don't even need QON core library for Android app. Just an SQLite reader that can read QON db(for tags). The rest is just folders.

**Comment by pbek** [comment]
> The 'core' library can easily be used to create an android app with QML. 

... you just need to put some 500h of work in it and boooooom, you are done. :laughing:

**Comment by r3d9u11** [comment]
@pbek Hello.
I've just installed NextCloud Notes on my Android.
I've created test notes via QOwnNotes on my PC and some notes via NextCloud Notes in my Android.

My they can't be synchronized.

Connection is OK:
![image](https://user-images.githubusercontent.com/15020827/82765017-eaded880-9e1b-11ea-810b-fcbaf47d0147.png)

Do you have any ideas?

**Comment by pbek** [comment]
> As I understand right, synchronization on the Nextcloud's client side.

correct, syncing is done by the NC sync client

https://docs.qownnotes.org/en/latest/getting-started/concept/

**Comment by r3d9u11** [comment]
@pbek 
Ok, I've found doc, which described "Nextcloud/ownCloud Inegration settings". 

https://www.qownnotes.org/Knowledge-base/QOwnNotes-settings-are-reporting-a-problem-with-my-ownCloud-path

**Comment by pbek** [comment]
Maybe someone should "move" that to https://docs.qownnotes.org (like the rest of the knowledge base), pull requests are welcome. :grin:

**Comment by opqriu** [comment]
If you're okay with TXT mode, you can use JotterPad.

https://play.google.com/store/apps/details?id=com.jotterpad.x

**Comment by artmg** [comment]
This has been a very active thread since it was closed in in 2017, but for anyone who found this through a search engine the answers on the [project front page](https://github.com/pbek/QOwnNotes#qownnotes) currently suggest _neutriNotes_ or [Markor](https://f-droid.org/packages/net.gsantner.markor/). 

Now, where's that .  **[ Close, Really! ]** . button 🙄

**Comment by pbek** [comment]
> pls tell do neutribotes or markor support syncronisation with the qownnotes??

qownnotes doesn't sync any note files. you can use what every file sync tool you like...

**Comment by Shadeclan** [comment]
I use Print(Notes) on my android phone (available from the F-Droid "[IzzyOnDroid repository](https://apt.izzysoft.de/fdroid/index/apk/com.printnotes.printnotes)).  From there, I can either sync with my NextCloud instance from my phone and then with QOwnNotes on my computer or I can use [SyncThing](https://syncthing.net/) to sync files directly between my phone and my computer.  Print(Notes) and QOwnNotes both read the same file format although Print(Notes) doesn't have all the features of QOwnNotes.

**Comment by pbek** [comment]
Thank you, I will mention [Print(Notes)](https://github.com/RoBoT095/printnotes) in the documentation!

**Comment by pbek** [comment]
There now is an Android App: https://www.qownnotes.org/getting-started/qownnotes-android.html.
