### ISSUE TITLE
How do I sync with mobile?

### ISSUE THREAD

**Issue by enoch85** [pbek/QOwnNotes#81]
Hi!

Thanks for a great app. I love the fact that you update it continuously.

What I wonder is how to sync from mobile. It's not obvious what address you should put in the field. Right now I have `https://example.se/remote.php/caldav` I've also tried with `/webdav` at the end but with no luck - it says connection error.

**Comment by pbek** [comment]
Hi @enoch85,

thank you for your kind words!

What do you mean by *sync from mobile*?
If you mean the QOwnNotes settings for the ownCloud server, you have just use `https://example.se`.

**Comment by enoch85** [comment]
I mean syncing with the [Andoid app](https://play.google.com/store/apps/details?id=org.aykit.MyOwnNotes)

Using just the main address gives me: `Not getting correct JSON from Server. Settings correct?`

**Comment by pbek** [comment]
Sorry, I'm not the developer of the Android app. :smile_cat: 
You may want to file an issue at https://github.com/aykit/MyOwnNotes/issues

**Comment by enoch85** [comment]
But your software is compatible with the app, right?

**Comment by pbek** [comment]
Yes, both apps can read the same note files.

**Comment by enoch85** [comment]
Ok, case closed then. But if someone have information on how to sync, please write here.

**Comment by pbek** [comment]
There now is an Android App: https://www.qownnotes.org/getting-started/qownnotes-android.html.
