### ISSUE TITLE
External markdown editor fails to load images.

### ISSUE THREAD

**Issue by mtibbi** [pbek/QOwnNotes#810]
When you try to edit a QON note using the button **"Open note in external editor"**, images are not loaded into the note preview of external editor. 

I think this problem is related to QON syntax.

Markdown standard syntax for inline images follows the below format:
\!\[Alt text](/path/to/img.jpg)

but the syntax generated by **"Insert image button"** in QON is something like this:
\!\[Alt text](file://path/to/img.jpg)

For example, the below line code fails to load image to external editor.
\!\[media-YH6396](file://media/26800.jpeg "Title")

But, if we replace **"file://"** by  **"./"** in the line code, as shown below, the image will be loaded. 
\!\[media-YH6396](./media/26800.jpeg "Title")

The dot in front of slash is required to denote current directory.

**Comment by pbek** [comment]
please see #266
