### ISSUE TITLE
Support two factor authentication with nextcloud

### ISSUE THREAD

**Issue by tarioch** [pbek/QOwnNotes#811]
After installing and enabling 2 factor authentication QOwnNotes is no longer able to connect to the QOwnNotesApi.

Error: Connection error message: The host requires authentification

**Comment by pbek** [comment]
As far as I know you have to visit your personal settings in NC, head to *Security* and create an App-PIN for QOwnNotes.

**Comment by tarioch** [comment]
Stupid me, that's it.
