### ISSUE TITLE
Feature suggestion: lock encrypted notes

### ISSUE THREAD

**Issue by UgoYak** [pbek/QOwnNotes#815]
Hi there, new user or QOwnnotes here, enjoying the software ;)

I wondered if will be possible to have an option to lock the edition of the notes while they are encrypted. 

This is merely for prevent the modification of the content of the encrypted string since if you alter him accidentally -by adding a single character, by example- and later you try to decrypt them, you get the -correct- message: "It seems that your password is not valid!".

Of course, when you select the option "Edit encrypted note" this "lock" will be disabled.

Just that, thanks for your work!

**Comment by pbek** [comment]
Thank you for your suggestion and your kind words. ;)

**Comment by pbek** [comment]
## 18.06.0
- encrypted notes are now read-only in the editor unless you are using
  *Edit encrypted note* or you are decrypting it

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
