### ISSUE TITLE
Provide a plaintext mode without any markdown rendering

### ISSUE THREAD

**Issue by robled** [pbek/QOwnNotes#82]
In "Edit" mode, some amount of markdown is rendered.  In some cases the user may prefer not to use markdown at all.  My use case is to store the following text file as a note for reference:

https://gist.github.com/robled/99b935c33194725789cb

If you paste the above text into a note some of the sections will be rendered green, others bold, others italics.  It's possible that I may have a missed a config option somewhere, but for this type of use case I would prefer an option for plain text only.

**Comment by pbek** [comment]
Do you want a setting that can turn off the markdown support for the whole application?

It would be much easier to encapsulate your text in a code block like that:
\`\`\`
your text
\`\`\`

**Comment by robled** [comment]
If there was an option to disable Markdown globally I would probably use it.  I store so much plaintext as notes, so I could benefit from that as a default for myself.

One idea would be to have a plaintext tab next to the Markdown tab to allow users to easily see the plaintext without having to insert ``` manually.

**Comment by pbek** [comment]
Hm, I'm not sure if viewing and maintaining an other tab with a text edit would be a great solution...
And disabling the whole markdown support for a few text-only notes doesn't seem a good choice either.

How is that handled by the mobile apps and the web app?

**Comment by robled** [comment]
The mobile and web apps appear to be rendering markdown as well.  I guess I'm just looking for a self-hosted open source GitHub Gist type of feature.  This kind of thing is certainly more useful on a desktop app than on the web or mobile apps.

**Comment by pbek** [comment]
So what do you propose?

**Comment by robled** [comment]
Perhaps a toggle-able menu option/toolbar item to "render as plaintext" that will just insert the ``` marks at the head and tail ends.  This way the state of this setting would be saved on a per-note basis.

**Comment by pbek** [comment]
What would keep you to just enter a \` character yourself (actually you just need one, not three)?
Or what is the benefit of the button? Just entering \`\`?

**Comment by pbek** [comment]
Maybe entering \`\` and moving the cursor between the two characters, like the "Insert code" button here on GitHub? Maybe with a hotkey <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>C</kbd>?

**Comment by pbek** [comment]
I have this implemented now in version 1.0.4.

**Comment by robled** [comment]
Thank you!  I will try this out once 1.0.4 hits the Arch Linux AUR.

**Comment by pbek** [comment]
Version 1.0.4 is out now.

**Comment by robled** [comment]
Works great, thanks!  I like the toolbar icon too.

**Comment by pbek** [comment]
Great you like it ;)
