### ISSUE TITLE
Feature suggestion: Ever considered markdeep?

### ISSUE THREAD

**Issue by crvio** [pbek/QOwnNotes#821]
Hi there
I just wanted to know if you have ever heard of [markdeep](http://casual-effects.com/markdeep/) and how (un)likely is it to be supported in the future.
I've used it and its really helpful in the writing of notes which require more features.
One of the most important features is the latex math support, but it has loads of other features.
Have look at [the demo](http://casual-effects.com/markdeep/features.md.html). I just think it's awesome.
Btw, thanks for this great software.

**Comment by pbek** [comment]
Thank you for your suggestion and your kind words, but since QOwnNotes is written in C++ / Qt and the markdeep library seems to be written in JS for the browser it is unlikely that QOwnNotes will support it.
