### ISSUE TITLE
Suggestion: More visible formatting for blockquote text in Note Edit pane

### ISSUE THREAD

**Issue by clintonthegeek** [pbek/QOwnNotes#822]
Hello!

I hardly ever look at my notes in the note preview view. I enjoy seeing the blue italics and blue bold text of the raw text files in the note edit pane. I use QOwnNotes more as a fancy text editor than a Markdown creator.

Sometimes I use the five-spaces formatting for blockquotes just to make them turn green. But I'd like an option to have the > blockquote symbol turn the entire blockquote red (or whatever formatting is selected). That way it will pop out more. I frequently quote books and want the quotes to be easily differentiated from what I write, but I'd like to use the proper formatting for that.

Can this be easily implemented?

**Comment by pbek** [comment]
I guess you are talking about the note editor, and not the preview, right?

**Comment by pbek** [comment]
And you are talking about colorizing it like with a code-block?

**Comment by pbek** [comment]
Took quite a while to allow options in the highlighter but now it's done...

## 18.01.1
- there now is a new checkbox in the *Editor settings* to fully highlight blockquotes
  instead of just the `>`

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by bepolymathe** [comment]
It works for me. Great enhancement for big document... 👏

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by ludenticus** [comment]
Great improvement!

**Comment by clintonthegeek** [comment]
Ooh I'm excited, thanks pbek! Looks like the PPA build system will have the binary ready for me tomorrow. But this will help my workflow a lot. Thanks!!

**Comment by clintonthegeek** [comment]
Okay the build system at Launchpad was down for the latest Spectre and Meltdown kernel patches, finally got the upgrade. It's perfect thanks!

**Comment by pbek** [comment]
Yeah, it was down because of the latest Intel-problems...

**Comment by clintonthegeek** [comment]
I thought I was safe because my i7 is ten years old, before the Management Engine thing... wah wah! Guess I'm eyeballing AMD for the next upgrade. :)

**Comment by pbek** [comment]
phew, it took me the last two releases to fix major problems on Windows that the new blockquote-feature introduced...
