### ISSUE TITLE
statistical linguistic data 

### ISSUE THREAD

**Issue by Fabijenna** [pbek/QOwnNotes#823]
is what I would need from a text editor
is that something you can imagine to have?

**Comment by pbek** [comment]
There already is a script `Note stats` in the script repository, that was done by @Maboroshy. Is that what you are looking for?

**Comment by Fabijenna** [comment]
thank you, I mean parsing and semantic tagging.

**Comment by pbek** [comment]
You could talk to @Maboroshy if it makes sense to expand <https://github.com/qownnotes/scripts/blob/master/note-stats/note-stats.qml> or maybe create an own script to do all the parsing. It should all be possible in the scripting engine.

**Comment by Fabijenna** [comment]
ok thanks

**Comment by Maboroshy** [comment]
Semantic tagging is little more complicated than a word counter. I'm absolutely sure it cannot be implemented as a simple in-app script. There should be some serious software that will process text data externally, maybe neural network. The in-app script would only pass the text file path to that software and show results in QON.

**Comment by Fabijenna** [comment]
I see, thank you very much.

**Comment by Fabijenna** [comment]
I guess I'd opt for a simple one. Yet to see.
