### ISSUE TITLE
Extend syntax to support other media types

### ISSUE THREAD

**Issue by Lucas-Steinmann** [pbek/QOwnNotes#825]
Hello,

I would like to make a suggestion to extend the syntax.

The goal of the extension is to be able to display other media types inline without breaking compatibility with other applications. 
One use case could be "inline display of latex formulas".
Other use cases are conceivable.

The basic syntax extension I would suggest would be an extension of the markdown image syntax:

    ![Alternative Text](path/to/image)

to 

    ![Alternative Text](path/to/cached_image){mediatype:mediastring}

e.g.

    ![f(x): R -> R](path/to/cached_image){latex:f(x): \\mathbb\{R\} -> \\mathbb\{R\}}

The behaviour of an editor **supporting the syntax** and **supporting the media type** should then be:
 - render and display the content in the curly braces
 - cache the rendered output in an image file
    - either at the specified location
    - or generate a unique (random) image file name and place it in a cache folder using that name. (e.g. `media/`)
 - don't display the alternative text

The behaviour of an editor **supporting the syntax** but **not supporting the media type** should then be:
  - display the cached image
  - don't display the alternative text or the text in the curly braces

Editors which **do not support the syntax** but **support images** would display:
  - the cached image
  - the text in the curly braces

Surely making such a general syntax, only makes sense when other apps would at some point also jump in and support this syntax. But until then, this extension would not break the display in other apps and other apps could even see the rendered content through the cached image.

The first question would be if something like this could be merged at some point.
This is not a completely finished idea but I would love to here some input from others.

I hope I was able to make my point.
If not, feel free to ask and I will try to enhance my description.

Thank you for reading.

**Comment by pbek** [comment]
That sounds like a lot of changes you would want to make to QOwnNotes (that haven't a lot to do with the way QOwnNotes is supposed to work). I'd rather would like it more if you'd extend the scripting api and do your modifications there (if possible).

**Comment by photonxp** [comment]
It is said that there're other [desktop editors available to support Latex](https://github.com/cben/mathdown/wiki/math-in-markdown#r-studio-r-markdown-v2), which might worth a try.

**Comment by Lucas-Steinmann** [comment]
Thank you. I will look at the API and see if I have some idea to implement something which achieves the same functionality and will look for alternatives intermittently.

**Comment by pbek** [comment]
Everything you need is in <http://docs.qownnotes.org/en/develop/scripting/README.html> and <https://github.com/pbek/QOwnNotes/blob/develop/src/services/scriptingservice.cpp>.

**Comment by pbek** [comment]
I will close this issue until there is more information.
