### ISSUE TITLE
Shortcuts for "search forward" and "search backward"?

### ISSUE THREAD

**Issue by elcste** [pbek/QOwnNotes#827]
If you open the note find bar (Edit → Find in current note), there are buttons to keep searching for the same text with the tooltips "search forward" and "search backward". AFAICT, these buttons don't have keyboard shortcuts by deafult or that can be added in Settings → Shortcuts. (On Mac and GTK+ desktops, I'd expect <kbd>command</kbd>/<kbd>control</kbd>+<kbd>G</kbd> and <kbd>command</kbd>/<kbd>control</kbd>+<kbd>shift</kbd>+<kbd>G</kbd>.)

Thanks for the great notes app!

#### Output from the debug section in the settings dialog
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue. Jan. 9 08:43:21 2018`
**Version**: `18.01.0`
**Build date**: `Jan  1 2018`
**Build number**: `409`
**Platform**: `linux`
**Operating System**: `Ubuntu 17.10`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.9.1`
**Qt Version (runtime)**: `5.9.1`
**Portable mode**: `no`
**Settings path / key**: `/home/alexander/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/alexander/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `29`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/home/alexander/notes`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/alexander/notes/notes.sqlite`

## Settings

**AboutDialog/geometry**: `<binary data>`
**ActionDialog/geometry**: `<binary data>`
**ActiveNoteHistoryItem**: *empty*
**Debug/fakeOldVersionNumber**: `false`
**Debug/fileLogging**: `false`
**DistractionFreeMode/isEnabled**: `false`
**DistractionFreeMode/menuBarGeometry**: `<binary data>`
**DistractionFreeMode/menuBarHeight**: `28`
**DistractionFreeMode/windowState**: `<binary data>`
**Editor/CurrentSchemaKey**: `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing**: `false`
**Editor/autoBracketRemoval**: `false`
**Editor/highlightCurrentLine**: `false`
**LastUpdateCheck**: `2018-01-09T08:03:12`
**LinkDialog/geometry**: `<binary data>`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `24`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `Source Code Pro,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `Source Sans Pro,12,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `monospace,11,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `Source Sans Pro,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl**: `false`
**MainWindow/showNotesFromAllNoteSubFolders**: `true`
**NoteDiffDialog/geometry**: `<binary data>`
**PiwikClientId**: `<hidden>`
**SearchEngineId**: `0`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**Shortcuts/MainWindow-actionInsert_Link_to_note**: `Ctrl+Shift+L`
**Shortcuts/MainWindow-actionInsert_attachment**: `Ctrl+Shift+O`
**Shortcuts/MainWindow-action_Find_note**: `Ctrl+L`
**Shortcuts/MainWindow-action_Find_text_in_note**: `Ctrl+F`
**Shortcuts/MainWindow-action_Open_note_in_external_editor**: `Ctrl+Shift+E`
**Shortcuts/MainWindow-togglePanel-notePreviewDockWidget**: `Ctrl+M`
**ShowSystemTray**: `false`
**StartHidden**: `false`
**WelcomeDialog/geometry**: `<binary data>`
**acceptAllExternalModifications**: `false`
**allowDifferentNoteFileName**: `false`
**allowNoteEditing**: `true`
**allowOnlyOneAppInstance**: `true`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `false`
**appMetrics/notificationShown**: `true`
**closeTodoListAfterSave**: `false`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**currentWorkspace**: `5fc809ad-f691-49ee-a10d-cb01dcf242dc`
**cursorWidth**: `1`
**customNoteFileExtensionList**: *empty*
**darkMode**: `false`
**darkModeColors**: `false`
**darkModeTrayIcon**: `false`
**defaultNoteFileExtension**: `md`
**demoNotesCreated**: `true`
**disableAutomaticUpdateDialog**: `true`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: *empty*
**gitCommitInterval**: `30`
**gitExecutablePath**: *empty*
**gitLogCommand**: *empty*
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**imageScaleDown**: `false`
**imageScaleDownMaximumHeight**: `1024`
**imageScaleDownMaximumWidth**: `1024`
**insertTimeFormat**: `yyyy-MM-dd HH:mm`
**interfaceLanguage**: *empty*
**internalIconTheme**: `true`
**itemHeight**: `22`
**markdownHighlightingEnabled**: `false`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `2`
**newNoteAskHeadline**: `false`
**noteSaveIntervalTime**: `10`
**noteSubfoldersPanelDisplayAsFullTree**: `true`
**noteSubfoldersPanelHideSearch**: `false`
**noteSubfoldersPanelOrder**: `0`
**noteSubfoldersPanelShowFullPath**: `false`
**noteSubfoldersPanelShowNotesRecursively**: `false`
**noteSubfoldersPanelShowRootFolderName**: `true`
**noteSubfoldersPanelSort**: `0`
**notesPanelOrder**: `0`
**notesPanelSort**: `0`
**notesPath**: `/home/alexander/notes`
**notifyAllExternalModifications**: `false`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: *empty*
**ownCloud/supportEnabled**: `false`
**ownCloud/todoCalendarBackend**: `3`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloud/userName**: *empty*
**previousWorkspace**: `58e895a4-c9e9-401d-9b8c-fe668f110779`
**recentNoteFolders**: `/home/alexander/Nextcloud/Notes`
**restoreCursorPosition**: `true`
**savedSearches/noteFolder-1**: 
```
dal broc, gigantes, freegal, computing, A faire, Note 2017-12-28T19.17.50, gifts, kwriteconfig5 --file kwinrc --group ModifierOnlyShortcuts --key Meta ""
ReplyForward
MailELCSTE
Compose
Save
Folders
, recipes, books, Æ, kde, ab, film, music, wishlist, 2017 election, pie~ven, coconut, www, web, 2017-10, lol, falkon, out+about, test, jazz, ma, snap, books to read, recipes to try, 2017-10-06, 2017-10-06 to8, Note 2017-09-30T11.09.31, Note 2017-09-23T14.03.35, Note 2017-09-23T09.01.04, Test, qupzilla, Note 2017-02-26T17.47.21, Note 2017-02-26T16.41.16
```
**showMenuBar**: `true`
**showStatusBar**: `false`
**taggingShowNotesRecursively**: `false`
**tagsPanelHideSearch**: `true`
**tagsPanelOrder**: `0`
**tagsPanelSort**: `0`
**toolbar/1/items**: `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name**: `mainToolBar`
**toolbar/1/title**: `main toolbar`
**toolbar/2/items**: `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name**: `formattingToolbar`
**toolbar/2/title**: `formatting toolbar`
**toolbar/3/items**: `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name**: `insertingToolbar`
**toolbar/3/title**: `inserting toolbar`
**toolbar/4/items**: `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name**: `encryptionToolbar`
**toolbar/4/title**: `encryption toolbar`
**toolbar/5/items**: `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name**: `windowToolbar`
**toolbar/5/title**: `window toolbar`
**toolbar/6/items**: `action_Quit`
**toolbar/6/name**: `quitToolbar`
**toolbar/6/title**: `quit toolbar`
**toolbar/size**: `6`
**useUNIXNewline**: `false`
**workspace-58e895a4-c9e9-401d-9b8c-fe668f110779/name**: `full`
**workspace-58e895a4-c9e9-401d-9b8c-fe668f110779/noteSubFolderDockWidgetVisible**: `true`
**workspace-58e895a4-c9e9-401d-9b8c-fe668f110779/windowState**: `<binary data>`
**workspace-5fc809ad-f691-49ee-a10d-cb01dcf242dc/name**: `minimal`
**workspace-5fc809ad-f691-49ee-a10d-cb01dcf242dc/noteSubFolderDockWidgetVisible**: `true`
**workspace-5fc809ad-f691-49ee-a10d-cb01dcf242dc/windowState**: `<binary data>`
**workspaces**: `58e895a4-c9e9-401d-9b8c-fe668f110779, 5fc809ad-f691-49ee-a10d-cb01dcf242dc`

## System environment

**USER**: `alexander`
**LANGUAGE**: `en_US`
**LC_TIME**: `en_AU.UTF-8`
**XDG_SEAT**: `seat0`
**COMPIZ_CONFIG_PROFILE**: `mate`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `1407`
**SHLVL**: `0`
**HOME**: `/home/alexander`
**DESKTOP_SESSION**: `mate`
**GTK_MODULES**: `unity-gtk-module:gail:atk-bridge:canberra-gtk-module:unity-gtk-module`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**LC_MONETARY**: `en_AU.UTF-8`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**UBUNTU_MENUPROXY**: `1`
**MANDATORY_PATH**: `/usr/share/gconf/mate.mandatory.path`
**QT_QPA_PLATFORMTHEME**: `gtk2`
**LOGNAME**: `alexander`
**DEFAULTS_PATH**: `/usr/share/gconf/mate.default.path`
**GTK_OVERLAY_SCROLLING**: `0`
**XDG_SESSION_ID**: `c1`
**PATH**: `/home/alexander/bin:/home/alexander/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
**GDM_LANG**: `en_US`
**MOZ_GTK_TITLEBAR_DECORATION**: `client`
**PAPERSIZE**: `a4`
**LC_ADDRESS**: `en_AU.UTF-8`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**DISPLAY**: `:0`
**LANG**: `en_US.UTF-8`
**XDG_CURRENT_DESKTOP**: `MATE`
**LC_TELEPHONE**: `en_AU.UTF-8`
**MOZ_USE_XINPUT2**: `1`
**XDG_SESSION_DESKTOP**: `mate`
**XAUTHORITY**: `/home/alexander/.Xauthority`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/alexander`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**LC_NAME**: `en_AU.UTF-8`
**SHELL**: `/bin/bash`
**QT_ACCESSIBILITY**: `1`
**GDMSESSION**: `mate`
**LC_MEASUREMENT**: `en_AU.UTF-8`
**LC_IDENTIFICATION**: `en_AU.UTF-8`
**XDG_VTNR**: `7`
**PWD**: `/home/alexander`
**XDG_DATA_DIRS**: `/usr/share/mate:/usr/share/mate:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-mate:/etc/xdg`
**LC_NUMERIC**: `en_AU.UTF-8`
**LC_PAPER**: `en_AU.UTF-8`
**MATE_DESKTOP_SESSION_ID**: `this-is-deprecated`
**SESSION_MANAGER**: `local/elcste:@/tmp/.ICE-unix/1320,unix/elcste:/tmp/.ICE-unix/1320`

**Comment by pbek** [comment]
Thank you for your kind words!

There are shortcuts. Please look for `In the note text edit panel` in http://www.qownnotes.org/shortcuts/QOwnNotes.

Does that answer your question?

**Comment by elcste** [comment]
Yes, thanks. I'm not sure how I missed that. 

Is there any chance they could be made configurable, like most other shortcuts? If so, that is my suggestion :-D

**Comment by pbek** [comment]
Those shortcuts are not bound to menu-actions, because they are intercepted inside the text-edit-widgets. It would be very hard to make them configurable...

**Comment by elcste** [comment]
Fair enough. Thanks for the explanation. If it really bugs me, I can change it and recompile ;-)

**Comment by pbek** [comment]
Of course. Please do let me know if you find a good solution!
