### ISSUE TITLE
problem on WinXP

### ISSUE THREAD

**Issue by FBachofner** [pbek/QOwnNotes#828]
I run QOwnNotes on both Linux and Windows XP

Today I updated to 18.01.2 on the XP machine and I get the following error:

"The procedure entry point CancelIoEx could not be located in the dynamic link library KERNEL32.dll."

I recognize this may be a limit for Windows XP in moving QOwnNotes to QT 5.9.2.

**_If so_**, is there a place where I can download a binary of 18.01.1 (which worked fine on my remaining XP installation) so I do not need to run the updater many times?  [ is https://github.com/pbek/QOwnNotes/releases/download/windows-b3421/QOwnNotes.zip  the definitive source? ]

**_If NOT_**, please advise on what I may need to do to get 18.01.2 to work on XP.

Thanks in advance and also for your wonderful ongoing work!

**Comment by pbek** [comment]
Thank you for your kind words!
Oh, I think you are right. Qt 5.8+ doesn't seem to support Windows XP.

https://forum.qt.io/topic/78011/the-procedure-entry-point-cancelioex-could-not-be-located-in-the-dynamic-link-library-kernel32-dll

For now I would stick to this release: https://ci.appveyor.com/project/pbek/qownnotes/build/windows-b3415/artifacts

I'm not sure if I can come up with something for XP users...
Meanwhile you can also build QOwnNotes yourself: https://www.qownnotes.org/installation

**Comment by pbek** [comment]
You could also fork QOwnNotes, change the Qt version back in <https://github.com/pbek/QOwnNotes/blob/develop/appveyor.yml> and build it on AppVeyor yourself.

**Comment by pbek** [comment]
## 18.01.3
- QOwnNotes is now also built with Qt 5.7 to allow Windows XP users to still use it
    - although you have to seek out the latest `master` build from [AppVeyor](https://ci.appveyor.com/project/pbek/qownnotes/history) yourself, choose the Qt 5.7 environment and download the artifact

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by FBachofner** [comment]
Hi Patrizio:

I couldn't sleep well tonight and went into my office . . .  and saw this as my "reward."  Wow, thanks!

OK, I downloaded the latest QT 5.7-based artifact.  It extracts properly and runs!

In Help / About QOwnNotes  it reports:

"QOwnNotes - version 18.01.3 - AppVeyor - build 3441
<snip>
Built on Jan 13 2018 with Qt 5.7.1."

I'll keep you posted on any issues I might experience.  I assume that going forward I will need to manually update whenever you might choose to release another Qt 5.7.1 version?  Totally OK by me, of course; this is only a _very_ slight inconvenience to those of us who need or want to maintain an XP system!

**Comment by FBachofner** [comment]
Curious, why did you earlier recommend build 3415 and not build 3421?

FYI, 3421 seemed to work fine on XP.

**Comment by pbek** [comment]
> I'll keep you posted on any issues I might experience. 

thank you!

> I assume that going forward I will need to manually update whenever you might choose to release another Qt 5.7.1 version?

yes, you have
Every version will also be released in Qt 5.7, but you have to download it manually from Appveyor. I also put that information into the Installation guide for Windows.

> Curious, why did you earlier recommend build 3415 and not build 3421?

there were some Windows troubles with that release

**Comment by FBachofner** [comment]
Hi Patrizio:

18.01.4 -- i.e. Build 3444 built on QT 5.7 from artifacts at
https://ci.appveyor.com/project/pbek/qownnotes/build/windows-b3444

Seems to work well on Windows XP

Thanks for keeping the QT 5.7 version alive for a while longer!  :-)

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by FBachofner** [comment]
Hi Patrizio:


18.02.0 b3449 continues to work on XP when using the QT 5.7 Appveyor 
artifact download.

Thanks!

**Comment by pbek** [comment]
Great! Thanks

**Comment by FBachofner** [comment]
18.02.2 b3471 continues to work on XP when using the QT 5.7 Appveyor artifact download.

This is with the exception of the new local trash feature which I also mention at issue #674

**Comment by FBachofner** [comment]
18.03.1.1 - QT 5.7 AppVeyor - build 3504

Continues to work nicely on XP.  Trash still doesn't work.  Will post info to issue #674

**Comment by FBachofner** [comment]
18.03.5 - QT 5.7 AppVeyor - build 3523
Continues to work nicely on XP

Most other issues seem resolved.  I have entered a minor additional enhancement suggestion at #866 related to: Edit / "allow note editing"

**Comment by FBachofner** [comment]
18.03.6 - QT 5.7 AppVeyor - build 3526
Continues to work nicely on XP

Thanks for incorporating my "allow note editing" enhancement suggestion! Details at #866

**Comment by FBachofner** [comment]
I've been successfully continuing to use the QT 5.7 AppVeyor - versions through build 3591 (i.e. QON v. 18.05.2 )

I just tried downloading build 3600 and the QT 5.7 AppVeyor - version of this build is no longer available.

Is this by design, limitation or an oversight?

Thanks in advance for your response Patrizio!

**Comment by pbek** [comment]
How sad, the builds all failed because qmake wasn't found. 
According to https://www.appveyor.com/docs/build-environment/#qt Qt 5.7 is still supported.
I'm trying a rebuild at: https://ci.appveyor.com/project/pbek/qownnotes/build/job/4ju8occ49o4m0n18

**Comment by pbek** [comment]
3 days ago it still worked...

**Comment by pbek** [comment]
Damn, they really dropped Qt 5.7 support: https://github.com/appveyor/ci/issues/2291

**Comment by FBachofner** [comment]
Thanks Patrizio!

I am impressed with your efforts and dedication to keeping XP support alive.

It will be interesting to see how they respond.  My guess is they will say "no."

**Comment by pbek** [comment]
We'll see...

**Comment by FBachofner** [comment]
Hi Patrizio

I see that you asked them again yesterday for an update.  Thanks!

**Comment by FBachofner** [comment]
Hi Patrizio

Is there any hope for reactivating support for the QT 5.7 version?

Those QT 5.7-based appveyor builds have been failing for about 50 (or more) build versions now.

**Comment by FBachofner** [comment]
I just added a comment there, giving some context as to why this is important for me and some of my clients, at least.

Thanks again!

**Comment by pbek** [comment]
Thank you! :clap:

**Comment by FBachofner** [comment]
Hi Patrizio ( @pbek )

I see ( https://github.com/appveyor/ci/issues/2502 ) that you are still working on this issue.  I really appreciate it.

Hopefully you will have a solution soon.

**Comment by pbek** [comment]
I think you need a completely different build stack for Qt 5.7 they way AppVeyor is currently providing it. :(

**Comment by FBachofner** [comment]
Hi Patrizio:

re: "completely different build stack" -- does that mean you would need to reconfigure your build process or actually get a different set of development tools?

**Comment by pbek** [comment]
I get a lot of weird errors I have never seen before and wasn't able to get around so far... (like in  https://ci.appveyor.com/project/pbek/qownnotes/build/windows-b3699/job/e8pm2dwkxmjat3bp)

**Comment by FBachofner** [comment]
Hi Patrizio:

I just saw in the change log for the 18.07.4 update that you are still trying to work on a solution.

Thank you!  :-)

**Comment by FBachofner** [comment]
Hi Patrizio:

I just saw in the change log for the 18.07.4 update that you are still trying to work on a solution.

Thank you!  :-)

**Comment by pbek** [comment]
No, that were some unrelated problems with even older Qt versions. The age of the Qt version isn't the problem here. It's the build service AppVeyor, that doesn't provide a build environment QOwnNotes needs any more.

**Comment by FBachofner** [comment]
Hi Patrizio:

Is there any progress with the old QT versions?

We are very close to giving up hope on getting updated hardware drivers for some legacy equipment and can't (maybe ever) move at least a couple PCs to Windows 10 (at least until the old equipment fails and can't be repaired).

These few machines are networked only internally and QOwnNotes is quite helpful to the users involved.

Is there anything further I can do to help you with the QT issue?

Thanks in advance.

**Comment by pbek** [comment]
It's no Qt issue, QOwnNotes is still compatible down to Qt 5.3 (if you want to build it yourself). It's a build-system issue. The build environment AppVeyor is offering for Qt 5.7 is very different than the one we are using for current Qt versions. And that issue is currently not sorted out...

**Comment by FBachofner** [comment]
Thank you Patrizio!

I think I better understand your issue now.

I just made another comment at https://github.com/appveyor/ci/issues/2502

Perhaps Appveyor will respond with some help.

**Comment by pbek** [comment]
## 18.12.3
- the Qt 5.7 build for Windows XP is now working again
    - seek out the latest master build from [AppVeyor](https://ci.appveyor.com/project/pbek/qownnotes/history),
      choose the *Qt 5.7 environment* and download the *artifact*

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by FBachofner** [comment]
Hi Patrizio:

>     * the Qt 5.7 build for Windows XP is now working again

**Bravo**!!

The new build seems to work _great_ on XP (that said, I have not **_yet_** tested all the features added since the last XP-compatible build).  [ I will shortly install on the other machines I referenced -- and report back if there are any problems. ]

Funny thing -- I could not post to GitHub from my own XP computer.  GH have locked out (even just slightly) older versions of Firefox (ESR notwithstanding).

**Comment by FBachofner** [comment]
@pbek 

I'm really sorry I did not point out the thread https://github.com/appveyor/ci/issues/2502 on August 13!!

I (wrongly / badly) assumed you were monitoring it.

Anyway, you have XP back up and running.  I am sure a number of people will be very happy with this!

**Comment by pbek** [comment]
Actually I was monitoring it, but I didn't realize the new issue was about to including it. :)
