### ISSUE TITLE
Slowing down with @tag script

### ISSUE THREAD

**Issue by bepolymathe** [pbek/QOwnNotes#834]
Hi,
For a few days now, I have had a slowdown while inserting a tag with the script of @Maboroshy  activated. 
https://github.com/qownnotes/scripts/tree/master/in-note-text-tagging
I didn't change any of the parameters. Do you have the same behavior?

**Comment by pbek** [comment]
The script didn't change for three month.
Do you now have a lot and/or large notes? Because parsing all notes does take time...

**Comment by bepolymathe** [comment]
118 notes not too big.

**Comment by pbek** [comment]
What happens if you just use half of your notes or if you write in the tags
by hand?

**Comment by pbek** [comment]
I will close this issue until there is more information.
