### ISSUE TITLE
Feature request pop up window to comment on text

### ISSUE THREAD

**Issue by wisdomlight** [pbek/QOwnNotes#836]
Hi all
OSX has Ulysses Markdown texteditor - its similar to Qownnotes [Qownnotes much better...;-)]

It has a feature allowing you to select a word or words by putting the word/s in some sort of brackets and then a pop up window appears. you can put text in that pop up and then once you close it the word/s are highlighted. 
pressing them and the pop up pops back and you can read your comments on these specific word/s

When i used Ulysses it was a feature i used a lot

cheers

**Comment by pbek** [comment]
I'm sorry, it would be very hard to store a reference to selected text because there is no other information stored than the text in the note-text-files.
