### ISSUE TITLE
[feature request] Side notes 

### ISSUE THREAD

**Issue by wisdomlight** [pbek/QOwnNotes#837]
Sometimes when you are in a follow of writing you have a mini indea you want to capture.

Maybe a feature for when i focused mode - it may be nice to have an option for little sticky notes at the side bars - which can be toggled on/off 

cheers

**Comment by pbek** [comment]
Which side-bar do you mean?
You can open multiple notes but only read-only...

**Comment by wisdomlight** [comment]
When you are writing in focused mode the text is at the centre of the window and it has two sides of empty columns.
which obviously helps for concentration.
but it will be nice if there you could have the option of sticky notes for ideas you'd like to develop later. 
Maybe these sticky notes could become notes in their own right?

**Comment by pbek** [comment]
I'm sorry, right now editing more than one note at the same time would mess up things considerably.

**Comment by wisdomlight** [comment]
well it was just a thought.

I love Qownnotes!!! Great job!

**Comment by pbek** [comment]
Thank you for your kind words!
The main reason for QOwnNotes was to be able to take notes in simple text-files, that can be synced across devices without being locked into a service or software.

**Comment by wisdomlight** [comment]
I see that is fine.
and it works great!
really a lot of improvement since i first installed it.
cheers

**Comment by pbek** [comment]
I wish you a mindful rest of your day. _/\_
