### ISSUE TITLE
[feature request] markdown enhancement

### ISSUE THREAD

**Issue by wisdomlight** [pbek/QOwnNotes#838]
Would it be possible to add two markd down options

inline commetn - for example you put  a ++then you right a text and finish with ++ and everything between the ++ ++ is considered as inline comment???

comments for example at the beginning of a line you put %% and this indicates that everythign else is a comment

its helpful when writning and wanting to put little comment especially if shared with others but also if you want to comment on your own work.

cheers

**Comment by pbek** [comment]
Thank you for your suggestion. What standard would that syntax be following? Hm, the 3rd party html-converter doesn't understand that either...

**Comment by wisdomlight** [comment]
OK mate, 
I am no developer etc
Really all I am doing is conveying my experience with Ulysses form OSX.
So it worked there but how they did it I do not know.
Again I am quite happy with Qwn as is.
I am sure you have much more important stuff to do than just these kind of little things.

Cheers

**Comment by pbek** [comment]
Thanks a lot for sharing your experience!
The standard for comments in markdown in still only `<!-- I am a comment -->` (html comments), which isn't very convenient, but we shouldn't deviate too much from it. If you find any other "standard" please let me know.
