### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by Dalan94** [pbek/QOwnNotes#84]
I see that you add tracking in QOwnNotes. I understand that this may help you to improve the software but I have some remarks:

* You use Google Analytics which is a good tools but it's horrible about privacy
* This option is set by default, it could be a good idea to ask the user if he (yes or no) want to use the tracking instead of tell him that he can disable it in the settings
* Even if I disable the tracking, the software send datas using the function `sendHeartbeat()` and maybe using others because WireShark catch some traffic to qownnotes.org and google-analytics.com
* You seem to really discourage people to disable the tracking while it's understandable to not want to send data to anybody, especially Google

**Comment by pbek** [comment]
Yes, Google Analytics is a tremendous help for getting feedback on what is going on and as we are typing here Google Analytics is tracking our every movements on GitHub, like (I guess) on 99% of all webpages...
And yes, Google Analytics hasn't the best reputation, simply because of Google's size. 

Do you have a better proposition than our good old data hog?

**Comment by Dalan94** [comment]
The problem is that on website we can use some tools to block Google Analytics (I personally block all request with [Privacy Badges](https://www.eff.org/privacybadger)) when we don't want to send all our online life to Google.

And currently we can't block all the request in QOwnNotes because even if we say to QOwnNote to not send data, it send at least one request. So there is a problem.

An alternative to Google Analytics is [Piwik](https://piwik.org/) which is an free and open source self hosted software. I never used it, I only know the name so I don't know if it is great or not.

**Comment by pbek** [comment]
Thank you for raising my attention, @Dalan94. The topic gave me an almost sleepless night. :cat: Everything is a bit hazy today...

The Google analytics request you are referring to will be mentioned `sendHeartbeat` request, it's a simple "someone is using QOwnNotes. Hurray, the developer got a little bit happier" request. I can make a setting for that too.
The qownnotes.org request is from the update service to check if there is a new version of QOwnNotes.

Thank you for Piwik, it was already on my radar, but I haven't tried an own installation yet and I'm not sure how well it works for non-websites. I will investigate more.

**Comment by pbek** [comment]
In addition to the new checkbox that disables the heartbeat I have implemented a button that leads to the general settings for the app metrics notification for version 1.0.3. Will that be satisfactory?

**Comment by Dalan94** [comment]
Sorry I didn't want you to have a sleepless night…

I perfectly understand the job of `sendHeartbeat` but it also send the message to Google that this IP address use QOwnNotes so… The checkbox work perfectly and I have no longer request to Google Analytics.

The request to qownnotes.org is necessary but why do you need to send the GAnalytics-cid, the buildCpuArchitecture… ? The only necessary things to send is the version. And it will be great if you also provide the code of the API of your server on Github :)

The button button that leads to the general settings for the app metrics notification suits me.

**Comment by pbek** [comment]
I can bind the GAnalytics-cid to the metrics checkbox... 
As for the buildCpuArchitecture, how do you think all the QOwnNotes Linux repositories and build systems (that were weeks of work to create and evolve) came into live?
Hm, for the API of the webpage I would have to restructure the whole project and possibly change the URLs too, what would render the old update checks useless. And who would know if I really use it. Basically I ask GitHub and compile some information.

**Comment by pbek** [comment]
Version 1.0.3 is out now.

**Comment by pbek** [comment]
After playing around with a Piwik installation and writing a Qt Library for it I can announce for version 1.0.5 that Google Analytics was removed in favor of Piwik.

**Comment by gerroon** [comment]
I stopped using qownnotes for this tracking reasons but I appreciate that you stop using GA. The reason I hate GA is that before you track the user, GA tracks you and the user. Anyway you seem to be done with it which is a progress.

**Comment by pbek** [comment]
Well, GA was quite a long time ago...

**Comment by pbek** [comment]
> And it will be great if you also provide the code of the API of your server on Github :)

@Dalan94, the day has come: https://github.com/qownnotes/api (it was quite some work) 😅
