### ISSUE TITLE
No updates for Ach/Manjaro 32 bit

### ISSUE THREAD

**Issue by maras** [pbek/QOwnNotes#843]
QOwnNotes warn about new version, but after sudo pacman -Syyu there is no updates. After doing sudo pacman -Syy qownnotes I see: qownnotes-17.11.2-1 is newest. 

I did all as in instructions for Arch pacman and I am on Manjaro x32. Maybe 32 bit is the problem? But there is archlinux-x32 project and Manjaro x32 branch. Is there any chance that there will be 32 bit version of QOwnNote for Arch/Manjaro?

Thank you for this wonderfull program :).

**Comment by pbek** [comment]
I'm sorry, OBS seems to currently have troubles building the 32bit versions for Arch.
https://build.opensuse.org/package/show/home:pbek:QOwnNotes/desktop

You could switch to the AUR... I use it to build QOwnNotes on Manjaro...

Also keep in mind that it seems Arch is dropping 32 bit support altogether ;)
