### ISSUE TITLE
Rename Notes according to the tags

### ISSUE THREAD

**Issue by Offerel** [pbek/QOwnNotes#846]
I would like to ask, if there is a way to rename a note according to the tags, i give for this note?

For example, my note has currently the name "testnote.md" and it has no tags yet. When i add for example  the tags "mobil",  "android" and "command", the note should be renamed automatically to "testnote[mobil android command].md".

Maybe this could be done with the scripting, but i don't know, how i can do this.

**Comment by pbek** [comment]
Yes, you could do that with a script like https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/use-tag-names-in-filename.qml.

I think @Maboroshy has done something similar...

**Comment by Offerel** [comment]
Ohhh that looks great. Im only on my mobile phone currently, but I will try this tomorrow. If that works, it makes note naming compatible with TagSpaces. I use the same naming in my notes plug-in for Roundcube, available in my repo here at GitHub. QownNotes is the perfect companion for this plug-in on the desktop.

**Comment by pbek** [comment]
Please tell us what you came up with. ;)

**Comment by Offerel** [comment]
Ok, currently i have the following code for my ccript (attached here). It adds 2 custom functions to the toolbar, "Get Tag's" and "Set Tag's". The first one reads a note filename, extracts the tags and add this tags as new tags to the current note.

But i have problems with the second script function. This should get the tags of the current note and rename the note file according to this tags. I use on windows the normale "move" command. It works on the commandline when i try `move '\c:\path\to\old_notefile.md' '\c:\path\to\new_notefile.md'`. But not with the script. I get only `[warning] startSynchronousProcess - 'process.waitForStarted' returned false ` in the scripting protocol window but the note isnt renamed/moved. Or does `script.startSynchronousProcess` not work under Windows? I have currently no other idea, how i could rename a note...

[note-tagging.qml.txt](https://github.com/pbek/QOwnNotes/files/1716315/note-tagging.qml.txt)

**Comment by pbek** [comment]
I think you need a shell to execute `mv` or `move` like I had to do here: <https://github.com/pbek/QOwnNotes/blob/63a2380080af845696357b29a2cbaa2cdbdd1ce1/src/utils/git.cpp#L152>

You will need to run this via `cmd.exe`.
@Maboroshy, didn't have similar problems?

**Comment by Offerel** [comment]
Ahh. thx for that tip. It works now with 
```
arguments = ["/C","move",script.toNativeDirSeparators(fileName),script.toNativeDirSeparators(path) + newName];
script.startSynchronousProcess("cmd.exe", arguments, "");
```
The note is renamed. But also the current tags are cleared after renaming. Is there a way to preserve the currents tags or should i run after renaming my first script?

**Comment by pbek** [comment]
Great that it works now!

> preserver the current tags

That will not be easy, you would need to modify the sqlite database where the tags are stored...
Was there a reason you didn't went the `handleNoteTextFileNameHook` route for modifying the note filename?

**Comment by Offerel** [comment]
Honestly, I suspect that I cannot use `handleNoteTextFileNameHook` in my case.  
If I understand the concept of hooks correctly, they are triggered automatically. In the case of handleNoteTextFileNameHook, even if a note is modified, the note is automatically saved.
But in my case, the note has not been changed, so it is not saved automatically and the hook will not be executed.
Instead of this, I mark the unmodified note and click on "set tags"in the toolbar. Only if I click on the button the note should be renamed.

Or did I misunderstand something and I can use that hook also when i click on the button and rename the note without loosing the current tags?

**Comment by pbek** [comment]
No, you are right. `handleNoteTextFileNameHook` only will be called when the note text is modified.

And <http://docs.qownnotes.org/en/develop/scripting/README.html#notetagginghook> will also not help you much if you want to modify the note filename...

**Comment by Offerel** [comment]
Great. 

Ok, i will now cleanup the script a little bit. Afterwards i commit it to my GitHub account and send you a link. Many thanks for your help and that wonderful application. Personally, I didn't like Nextcloud, but this application is great.

**Comment by pbek** [comment]
Thank you for your kind words.
Yes, there's no need to use Nextcloud, using it is just a "plus". ;)

**Comment by Offerel** [comment]
One last question: is there a way to get the info, if a user clicked OK or canceled the message box with 
`script.informationMessageBox("The text I want to show", "Some optional title");`
I have tried with 
`var erg = script.informationMessageBox("The text I want to show", "Some optional title");` but erg is everytime empty. Standard Javascript confirm() does not work.

Background is, that i would give the user a choice, to cancel the action or to execute it.

**Comment by pbek** [comment]
No, I'm sorry. The `informationMessageBox` can't do that. But you can create a feature request for a `QMessageBox::question` scripting command.

**Comment by Offerel** [comment]
Ok. many thx. I will do that. BTW: I have added the current script at https://github.com/Offerel/roundcube_primitivenotes/blob/master/helper/QOwnNotes/note-tagging.qml

I haven't tested this with Linux yet. I can do this at the weekend, since i have no PC with Linux and a GUI currently, only a small headless Raspberry Pi for server purposes. But i can setup a Ubuntu VM at the weekend. I didn't have a Mac for testing. Maybe someone can test and change the script on the Mac.
