### ISSUE TITLE
[question] OneNote import strategy?

### ISSUE THREAD

**Issue by 1xPdd** [pbek/QOwnNotes#848]
Hey, recently discovered QOwnNotes, which I'm really liking. Thanks for the great software.

I was wondering if anyone had ideas as to how I might import all my old OneNote notebooks. I noticed there is an importer for Evernote but no mention here of OneNote. I'd really like liberate my notes from Microsoft's hands. Has anyone already worked through this that can lend some advice?

**Comment by pbek** [comment]
I've no idea on how OneNote treats its data or if you can export it. Is there an export?

You could also try to get your data into Evernote and export it there like <https://discussion.evernote.com/topic/90721-how-to-migrate-onenote-notes-to-evernote/> or find a tool like <https://jirka-mayer.github.io/onenote-to-markdown/> to convert your data to markdown files (that will be used by QOwnNotes).

**Comment by pbek** [comment]
(And thank you for your kind words!)

**Comment by 1xPdd** [comment]
OneNote can export notebooks as OneNote Packages, PDF, and XPS. I don't know about the internal format but I'd imagine it's some sort of XML, similar to other office formats.

Hmm. Hadn't thought of importing notes into Evernote. I don't have an account; I'll try to spin up a VM and see if I can get it to import my notebooks there first. The markdown converter looks interesting but I'm not very eager to upload my notes to the cloud.

Thanks!

**Comment by pbek** [comment]
If you create me an "OneNote Package" with a few representational notes I can take a look at it...

**Comment by 1xPdd** [comment]
OK. I no longer have it or Windows (just notes from a few years ago), but I should be able to figure out how to do that.

**Comment by pbek** [comment]
I will close this issue until there is more information.
