### ISSUE TITLE
Feature enhancement: Todo Reminder Time

### ISSUE THREAD

**Issue by vsc42** [pbek/QOwnNotes#856]
When entering a todo reminder date and time, it is difficult to set the time given one has to modify the hour and minutes where on OS-X this is a tedious process. Perhaps a different input scheme would prevent having to get the cursor in just the right location and backspace over the number prior to entering the desired hour or minutes.

**Comment by pbek** [comment]
Currently the http://doc.qt.io/qt-5/qdatetimeedit.html is used as picker.
I just tested it on macOS and didn't grasp the tedious part. :)

Can you please describe in more details what you are disliking.

**Comment by pbek** [comment]
I will close this issue until there is more information.
