### ISSUE TITLE
UX improvments

### ISSUE THREAD

**Issue by suhr** [pbek/QOwnNotes#86]
This one:
* Add [UberWriter](http://uberwriter.wolfvollprecht.de/)-style distraction free UI. No buttons or menu, just pure text editing
* Add a button to show/hide the sidebar
* Make search bar [auto]hideable
* Make menu bar hideable
* ~~Add an option to choose the default header style (`#` instead of `===`)~~
* Enlarge default font size (make it at least 12)

**Comment by pbek** [comment]
Thank you for your suggestions!

I will install UberWriter to see how Wolf has done it.
Are your suggestions 2, 3 and 4 relating to UberWriter features?
As for 5: you can use what you want, but I advice against using `#` because that would go into your filename. ownCloud notes (and thus also QOwnNotes) uses the first line as file name.
As for 6, the font size the operating system suggests is used as default font size, you change change it in the settings. Each OS has it own choices about font face and size.

**Comment by suhr** [comment]
> Are your suggestions 2, 3 and 4 relating to UberWriter features?

This is related to hiding distracting UI elements, also some customization (why do I need a menu bar when there's a toolbox?). When you write a long note, you want to focus on the text only. You don't use the sidebar. You don't use search bar. You write text.

Another distraction free markdown editor is [ghostwriter](http://wereturtle.github.io/ghostwriter/). It shares the same idea: clean up the UI to make you focus on the text.

**Comment by LEDfan** [comment]
I fully agree with @suhr. Personally I don't use any of the icons in the toolbar. This is the same for almost all software I use, except 3-4 buttons I really need. (Like in thunderbird, `get messages`, `new message`, `addressbook` etc, IDE where I just have to press the build/run button etc).

I would also autohide the search bare and only show it by using CTRL-F or something like that. 

@jancborchardt do you know this app? We need you here for some advice :smiley:.

**Comment by pbek** [comment]
I will definitely look into that! Thank you for the great suggestions @suhr, and thanks a lot for the ghostwriter reference! I will have a look into its hunspell integration as well, something I wanted to try to make work for a long time but wasn't a trivial task...

**Comment by suhr** [comment]
On `#` headers:

> As for 5: you can use what you want

Yes, but when you create a note it inserts `===` header.

**Comment by pbek** [comment]
Using `===` is so far the only way to get all all other characters out of the headline, that is currently the file name. Is your #87 about this issue? If yes, ye shouldn't talk about this in two different issues. :smile_cat:

**Comment by pbek** [comment]
Would it make sense to hide all UI elements at once with one button (& shortcut) or would it be better to have a different menu entry / button for each of the UI elements?

**Comment by pbek** [comment]
In version 1.0.8 you can now enter a distraction free mode with a new button in the toolbar.
You can also toggle it with <kbd>Ctrl</kbd> + <kbd>⇧</kbd> + <kbd>D</kbd>.
What do you think about it?

**Comment by suhr** [comment]
> What do you think about it?

This is nice! But it needs some padding, there's too few empty space and the text is too wide.

**Comment by pbek** [comment]
Thank you, I will add more padding in v1.1.1.

**Comment by pbek** [comment]
v1.1.1 is out now, @suhr. How does the padding look for you?

**Comment by suhr** [comment]
Well, I expected more padding. Do you know, how firefox reader mode looks like? Or web blog themes [like on Medium](https://medium.com/@sdboyer/so-you-want-to-write-a-package-manager-4ae9c17d9527). Or even github comments. Ghostwriter have different options for padding, but all of them add a lot of it, also they constant text width.
Also, you should not pad scrollbar, it should look like in your browser: on the right and with full length.

**Comment by pbek** [comment]
I'll see what I can do. Thank you for the suggestions.

**Comment by suhr** [comment]
This may be useful: http://graphicdesign.stackexchange.com/questions/13724/recommended-column-width-for-text-reading-digital-vs-printed

**Comment by pbek** [comment]
:+1:

**Comment by pbek** [comment]
The notes in the distraction free mode will now have a viewport width of 60 `O` characters in v1.1.2. The viewport will resize automatically if the width of the window changes. How does that sound for you, @suhr?

**Comment by suhr** [comment]
Nice. But make an option to choose between 60, 80 and 95 (100?) characters width. Different users may have different preferences (for example, I use “wide” editor width in ghostwriter, which is ~100 characters).

**Comment by pbek** [comment]
@suhr, I've done that too now. Version 1.1.2 is out now, what do you think?

**Comment by suhr** [comment]
Great! Now distraction-free mode looks like it should look.
(“Medium” width is a bit too wide (~10 characters wider than ghostwriter “Wide”) though. But instead “Narrow” have almost the perfect width)

Customizable ordinary UI might be a nice feature too, but I believe it's not very important. You probably could also improve styles of both rendered and not rendered markdown, but I have little knowledge/experience on that, so I can't help here. I can cast @wereturtle though.

Feel free to close this issue if you want to.

**Comment by pbek** [comment]
Thanks for the feedback, I used your 60/80/100 suggestions. Lets leave it there for now, you can open a new issue if you have any more insights after using it for a while.
