### ISSUE TITLE
Tag collision for notes with the same file name but different extensions

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#864]
I was tinkering with tag db and found out it doesn't know extension of tagged notes. That means, and proved by test, notes with the same file name share tags. Also tagged notes counter counts such notes as one. It's a rare use case though.

**Comment by pbek** [comment]
using the same file name with different extensions isn't advice to do in
QOwnNotes

**Comment by pbek** [comment]
In the tagging information the the extension isn't stored. That dates back to the time where it wasn't even possible to show two notes with the same filename (but different extensions) in the note list... And thus the extension had to be omitted to assure both files (you didn't know which file would be listed) are tagged.
Even now it can be problematic to use the same filenames.

I guess we'll leave it the current way to not to brake a lot of stuff...
