### ISSUE TITLE
context menu enchancement suggestion

### ISSUE THREAD

**Issue by FBachofner** [pbek/QOwnNotes#866]
I just noticed the feature:
Edit / Extra / Autocomplete, solve equation or open URL (Ctrl+Space)

This is _great_!

It would be easier to "discover," however, if right-clicking a URL in a note presented a context menu with a similar option [ i.e. "Open URL (Ctrl+Space)" ]

I am not yet sure how the autocomplete or solve equation features work, so those may not be appropriate for a context menu . . .

Of course now that I know about Ctrl+Space I am set, but others might also "look" for such a feature in the context menu . . .

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
## 18.03.3
- the menu entry to autocomplete, solve equations or open URLs of the
  *Edit/Extra* menu was also added to the context menu of the note text edit
- the context menu options of the note text edit now also works for encrypted
  notes while editing them

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by FBachofner** [comment]
Thanks for incorporating this suggestion in 18.03.3

**_Unfortunately_**, while the context menu now includes this useful feature (and it works), **_I can no longer add any text in QOwnNotes_**.

This is true for existing notes and for new notes (which I _can_ create).

I have just installed:
- QOwnNotes - version 18.03.4 - AppVeyor - build 3520
- Built on Mar 8 2018 with Qt 5.7.1

This is on Windows XP.  I will test on Linux tomorrow, assuming an update pushes through my repository . . .

**Comment by pbek** [comment]
> Unfortunately, while the context menu now includes this useful feature (and it works), I can no longer add any text in QOwnNotes.

Have you turned off `Allow note editing` in the *Edit* menu?

**Comment by FBachofner** [comment]
Hi Patrizio:

Yes, that was it, thanks!  [ I must have mouse-slipped when testing trash / remove note one day ]

Here's a useability suggestion (and because the "fix" was not really apparent from the menus -- I was looking in settings).

This is a _toggle_, so how about:

"**_Allow_** all note editing" as menu text if note editability is **_off_**.

"**_Disable_** all note editing" as menu text if note editability is **_on_**.

Alternatively you could have a checkmark or other visual indicator such as red / green icon.

Also take note, I am suggesting adding the word "all" to the menu.  I had always assumed this feature was to disable editing a **_single_** note and that was a main reason it was not in global settings.

Thanks for your consideration and continued excellent work!

**Comment by pbek** [comment]
Thank you for your suggestion, to convert the checkbox in the menu (that is also present in the main toolbar for new installations or if you reset the toolbar) would defy the "on/off" feature of said button in the toolbar, but I can add the word `all`.

**Comment by pbek** [comment]
And maybe I will move the menu entry to some other place.

**Comment by FBachofner** [comment]
I see now one issue I had with identifying this as a toggle feature: I run QON in dark mode.

In dark mode the "allow note editing" menu icon seems to be no different regardless of state (i.e. on or off).  The toolbar icon is better (it has a thin outline when editing _is_ allowed).

If there is any way to change the color of the icon depending on state that might be easier to identify?

Also, again -- rather than a checkbox, I think it would be superior to change the menu text (and/or tooltip text in the case of the toolbar button) to show what will happen (i.e. something like "allow" when state is off, "disable" when state is on).

I'm not sure how that would "defy the 'on/off' feature" -- but maybe I am misunderstanding you . . .

**Comment by pbek** [comment]
## 18.03.6
- the `Allow note editing` menu item was moved to the `Note` menu
    - the text was changed to `Allow all note editing` if note editing is 
      disabled and `Disallow all note editing` if note editing is enabled

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by FBachofner** [comment]
Thank you!

It works on XP / QT 5.7 -- just as you describe.

Will test on one of Linux machines tonight or tomorrow.

Icon on dark theme is still "just" outlined.  Some people might prefer a more distinct visual cue.  Now that I know it's there, it's not really a big issue.

**Comment by pbek** [comment]
Thank you for testing.

> Icon on dark theme is still "just" outlined.

I don't know if that can be changed easily.

**Comment by nathan2423** [comment]
I can't get any of the builds that should work to work on Appveyor to produce an XP version.  Is there any way someone can point me to a "last known working XP copy"?

**Comment by FBachofner** [comment]
Hi @nathan2423

The last known good version for Windows XP is:  version 18.05.2 - AppVeyor - build 3591

If you can not download from AppVeyor, perhaps I can post a copy for you somewhere.

Good luck.


Felix

**Comment by pbek** [comment]
Should be that one: https://github.com/pbek/QOwnNotes/releases/tag/windows-b3591

**Comment by pbek** [comment]
We need volunteers that would build for XP 😬
