### ISSUE TITLE
Feature: "Add Scribble" Button

### ISSUE THREAD

**Issue by woodworker** [pbek/QOwnNotes#869]
i know i can just add images to QOwnNotes and they will be copied into the notes folder
but i really like the feature of OneNote to be able to add a scribble in a very fast way and
i would also like to have a feature like this in QOwnNotes
and i think the easiest way would be something like this

#### Idea

A button that creates a empty (transparent?) png of configurable size in the media folder
maybe name it after the current file and add a number for uniqness
adds it to the current position in markdown
and opens a configurable image editor so i can draw immediately in the right file and i just need to save and would be done

**Comment by pbek** [comment]
Thank you for your suggestion.

**Comment by pbek** [comment]
In theory you should be able to that yourself with the scripting engine and the help of a web-service that can create images.

Downloading an url to the media folder: http://docs.qownnotes.org/en/develop/scripting/README.html#downloading-an-url-to-the-media-folder

**Comment by pbek** [comment]
## 18.03.2
- there now is a new scripting function `script.insertMediaFile()` to insert a
  media file into the media folder
    - for more information please take a look at the [scripting documentation](http://docs.qownnotes.org/en/develop/scripting/README.html#inserting-a-media-file-into-the-media-folder)
- there now is a new scripting function `script.regenerateNotePreview()` to
  regenerate the note preview
    - for more information please take a look at the [scripting documentation](http://docs.qownnotes.org/en/develop/scripting/README.html#inserting-a-media-file-into-the-media-folder)
- the *checkbox* properties for the *script settings variables* did get a `text`
  attribute for the checkbox text along with the `description` now used for the
  description text
    - for more information please take a look at the [scripting documentation](http://docs.qownnotes.org/en/develop/scripting/README.html#registering-script-settings-variables)
- there now is a new script `Scribble` in the *Scripting repository* to insert a
  scribble image to the media-folder, that will be edited by an external image
  editor

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
@Maboroshy, new shiny scripting functions ;)

**Comment by Maboroshy** [comment]
Not yet sure what to do with them. Call it a creative crisis. :smiley:

**Comment by pbek** [comment]
Well, I did https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/scribble.qml with it. :)

**Comment by woodworker** [comment]
works like a treat - exactly what i wanted

**Comment by pbek** [comment]
Great, thank you for testing!
