### ISSUE TITLE
Incorrect note name when # header is used

### ISSUE THREAD

**Issue by suhr** [pbek/QOwnNotes#87]
While

```
Example
=======
```

yields `Example` as the note name, 

```
# Example
```

yields `# Example`.

UPDATE: also add an option to choose the default header style (`#` instead of `===`)

**Comment by pbek** [comment]
Are you referring to the HTML rendered markdown? I think that's how markdown is supposed to work. Even the GitHub editor behaves the same, you can test it in the comment field.
And I advice against using a `#` in the note headline (aka. name), see #86.

**Comment by suhr** [comment]
> ownCloud notes (and thus also QOwnNotes) uses the first line as file name

So this is a ownCloud related issue. Well, can this be fixed for people that use QOwnNotes without ownCloud?

**Comment by pbek** [comment]
Are we still talking about the html rendering of ` # Example` or are we talking about the file-names of the notes? We should create a different issue for the latter.

**Comment by suhr** [comment]
About both sidebar note names and file names.

**Comment by pbek** [comment]
So I summize we are _not_ talking about how ` # Example` is rendered in the markdown view, correct?
And your proposition is to make a special setting (since the ownCloud notes web-app and the mobile clients are not supporting your wish yet) to remove leading `#` from file names...
Hm... that wouldn't make the headline of the note a unique identifier any more, because one could use `# Example`, `## Example`, `### Example`... QOwnNote currently renames the file and the headline if the name isn't unique in the current folder. Any ideas?

**Comment by suhr** [comment]
The only top level header is `# Example`, so the only possible collision is between `#` and `===` headers.

**Comment by pbek** [comment]
Although still a collision...

**Comment by pbek** [comment]
QOwnNotes v1.1 will now allow the usage of `# ` markdown headlines as note title. I have have not seen any side effects. Please be so kind and report back and troubles when 1.1 is out, @suhr.

**Comment by pbek** [comment]
v1.1 is out now

**Comment by suhr** [comment]
Looks good, thanks.

**Comment by pbek** [comment]
In the just released version 16.05.5...

- you can new use a new setting in the general settings to **allow that the 
  note file name is different from the note headline**
    - this allows you to keep your old note files regardless of what the content
      of them is
    - the note name will also be found in the note search
    - you are able to **rename your note files** by double-clicking on the note 
      name in the note list
        - renaming will fail if there already exists a note with the same name
        - some characters are also not allowed in the file name, they will be 
          removed automatically
    - be aware of that ownCloud notes needs the note file name to be the same 
      as the note headline

In case this is something for you could you please test this new feature and report back?
