### ISSUE TITLE
Option to disable automatic updates

### ISSUE THREAD

**Issue by dimqua** [pbek/QOwnNotes#870]
Can you please add an option to disable checks for updates on Windows?

**Comment by pbek** [comment]
There already is an option to do that in the settings.

**Comment by dimqua** [comment]
Do you mean "Don't show the update dialog automatically"? It does not prevent automatic checks for updates, I always see _new version available_ in the right bottom corner of the program.

**Comment by pbek** [comment]
> I always see new version available in the right bottom corner of the program.

And rightfully so. :grin:

**Comment by pbek** [comment]
If you dislike it so much you could try to play around with the `Custom user interface styling` script or turn off the status bar altogether.

**Comment by dimqua** [comment]
@pbek I don't care about UI, but about unwanted network connections. Of course, I can block connections to www.qownnotes.org just to prevent update checks, but I think it's too much.

**Comment by pbek** [comment]
If you want to tinker with the update manager, this is the place: <https://github.com/pbek/QOwnNotes/blob/develop/src/services/updateservice.cpp>

**Comment by ExceptionGit** [comment]
@pbek Why you add "AppHeartbeat" if can't set "UpdateMode" to "Manual". Anyway i can't run you app without unwanted network connections in private network..

**Comment by pbek** [comment]
I think I fail to understand your question.

**Comment by ExceptionGit** [comment]
I just want to completely disable the update check with a button in the UI or in the .ini file. :fire::fire_engine:

**Comment by pbek** [comment]
See https://github.com/pbek/QOwnNotes/issues/870#issuecomment-372447338

**Comment by o-l-a-v** [comment]
I'd also like this feature, would be useful when using a package manager for installing and updating QOwnNotes.
