### ISSUE TITLE
Linux Mint 18.3 QOwnNotes does not work

### ISSUE THREAD

**Issue by wisdomlight** [pbek/QOwnNotes#878]
Expected behavior - Menu - QownNotes - Open window - type text

Actual behavior - Menu - QownNotes - window opens briefly and closes down.

That's it.
suggestions?

**Comment by pbek** [comment]
Try an other session `QOwnNotes --session test`, an other thing could be a broken icon theme that you are using.

**Comment by wisdomlight** [comment]
`QOwnNotes -session test` works so that's fine
Except I'd rather use it normally from my menu. 
Is there a fix? or should i uninstall and then re install?

**Comment by pbek** [comment]
If that works it means some of your settings are causing it and you can reset them. There is an other parameter for doing that (use --help).

**Comment by wisdomlight** [comment]
Thank you it works now.
for your attention - it used to work fine but once i did the last upgrade something went wrong.
Any how - I fixed it now and its all good.
Cheers

**Comment by pbek** [comment]
Great! ;)

**Comment by pbek** [comment]
> for your attention - it used to work fine but once i did the last upgrade something went wrong.

there were no significant changes in the last update
