### ISSUE TITLE
Feature Request: Asciidoc Support for QOwnNotes

### ISSUE THREAD

**Issue by chuckf** [pbek/QOwnNotes#881]
I would like to see Asciidoc support in QOwnNotes as I find it a more powerful markup the Markdown. 

(I am not a coder, so telling me to do the integration myself is not an option)

**Comment by pbek** [comment]
I'm sorry, QOwnNotes is based on markdown. You would need to be more specific what you mean by "support". :)

**Comment by pbek** [comment]
I will close this issue until there is more information.

**Comment by djalmajr** [comment]
For support, I think he wants the addition of syntax highlight and the preview on the side. It would be a nice addition to app (as well as the "support" to reStructuredText).

**Comment by pbek** [comment]
You cannot simply "add" that "support" without rewriting the whole application. :smile:
