### ISSUE TITLE
It crashes if exit without save manually in win7

### ISSUE THREAD

**Issue by vanleo2001** [pbek/QOwnNotes#886]
I find QON will crash if I exit this app without save manually in win7. It happens from QON ver 17 -- now 18.04.1.

### Reproduce:
1.  I have **no** ownCloud or Nextcloud installed. 
2.  In settings -> General -> note save interval time, I set a big number, such as 900 sec.
![snap760](https://user-images.githubusercontent.com/12027772/38360479-df15de4e-38fc-11e8-9333-9c7a58692799.jpg)

3.  Now run QON, create a new note, type some words in edit, then exit app. It will show a crash nag.
4. If I save notes manually, then exit app, it's OK.

I guess it may be caused in  "writing memory database  to harddisk for autosaving unsaved note when exit "

**Comment by vanleo2001** [comment]
It crashes when I click the close button (right upper position)  directly. But if I use ctrl+q to exit, it works ok.

Below is a gif animation for screen capture. 
![aaa](https://user-images.githubusercontent.com/12027772/38362267-c1e029be-3902-11e8-944c-b2406969ab03.gif)

**Comment by pbek** [comment]
I also tried the close button and didn't get a crash. :/

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it "works" for you now by any chance?

**Comment by vanleo2001** [comment]
I test, it works OK!

**Comment by pbek** [comment]
No, really? No crash any more? It was a complete shot in the dark.
