### ISSUE TITLE
Suggest：Whether you can directly edit cloud files, and increase the file open permissions, do not need to encrypt

### ISSUE THREAD

**Issue by innki** [pbek/QOwnNotes#889]
Hope you can add convenient security for this software

**Comment by pbek** [comment]
Can you please be more specific.

**Comment by pbek** [comment]
No problem at all. :)
Yes, first and foremost QOwnNotes is an application to edit simple plain-text markdown files in a local folder. If you want to encrypt that whole folder or hard disk partition it would be best to use a 3rd party encryption tool.
