### ISSUE TITLE
Feature request: Delete orphaned attachments

### ISSUE THREAD

**Issue by cryptoluks** [pbek/QOwnNotes#895]
Hi,

first of all: thank you for developing such a nice app! I fall in love with it. :-)

I did not find a possibility to delete unused attachments. For images you can do Edit > Extra > Delete orphaned image files. Or did I miss something?

Thank you very much.

**Comment by pbek** [comment]
Thank you for your kind words and your suggestion. ;)

**Comment by pbek** [comment]
## 18.07.5
- there now is a new menu entry to **manage orphaned attachments** in the
  `Edit / Extra` menu
    - you can view information about the attachment, add the attachment to the
      current note, remove the attachment, open the attachment with an 
      associated application or open the folder of the attachment

**Comment by pbek** [comment]
@rakekniven, @cryptoluks 

There now is a new release, could you please test it and report if it works for you?

**Comment by rakekniven** [comment]
Updater doesn't show me v18.07.5. Do I have to install manually?

**Comment by pbek** [comment]
Does it still not show?

**Comment by pbek** [comment]
I just found out I have a small issue in the detection of attachment links, I'll fix that.

**Comment by rakekniven** [comment]
Updater found it and I will test as soon as you say "start" :-)

**Comment by pbek** [comment]
You can already test it but there will be too many items in the list.

**Comment by rakekniven** [comment]
Yes, confirmed. Waiting for next release.

**Comment by pbek** [comment]
## 18.07.6
- fixed attachment detection and link generation in the new dialog to manage
  orphaned attachments (for [#895](https://github.com/pbek/QOwnNotes/issues/895))

the new release is currently building (in queue), should be done soon

**Comment by pbek** [comment]
any news?

**Comment by rakekniven** [comment]
Looks good. I only have a few attachments, but first tests are successful.

**Comment by pbek** [comment]
Great, thank you for testing!
