### ISSUE TITLE
Feature request: Tagging enhancement

### ISSUE THREAD

**Issue by Flashwalker** [pbek/QOwnNotes#896]
1. Add several tags to the note at once, via string separated by commas
2. Add tag to note by double click on tag in tags panel
3. Button or menu item for copy all tags attached to note to clipboard
4. Button or menu item for copy all tags attached to note to another note
5. Selectable tags as text in note's tags field (separated by spaces or commas)
6. Insert tag to note text field by drag-and-drop

**Comment by pbek** [comment]
1) you could do that with the scripting engine, there is a command to assign tags to the current note and a command to get a dialog to enter text (http://docs.qownnotes.org/en/develop/scripting/README.html#opening-an-input-dialog-with-a-line-edit)

2) I guess that could be done
3) you could do that with the scripting engine
4) combination of 1) and 3)?
5) you could do that with the scripting engine
6) I don't want to enable drag and drop for a lot of reasons...

beside all that, maybe you want to check out the script `@tag tagging in note text (experimental)` in the script repository...

just ask if you need help with scripts

**Comment by pbek** [comment]
> just ask if you need help with scripts

or @Maboroshy is up for new challenges ;)

**Comment by Flashwalker** [comment]
Thanks for pointing me, i'll try to script.

**Comment by pbek** [comment]
Great, be sure to let me know what you came up with! ;)

**Comment by Flashwalker** [comment]
For now just made add-multiple-tags.qml script: http://ix.io/18IG

**Comment by Flashwalker** [comment]
ok, i'll do it.

**Comment by pbek** [comment]
## 18.04.5
- double-clicking on a tag now assigns the tag to the current note

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
