### ISSUE TITLE
Markdown view ignores line breaks

### ISSUE THREAD

**Issue by janhenke** [pbek/QOwnNotes#9]
Opening any any note in the editor view produces correct formatting. Switching to the Markdown view for the same note, all line breaks are no longer displayed and the whole formatting is broken.

**Comment by pbek** [comment]
Did you try using it on a local filesystem? Under which OS did you get this behavior?

**Comment by janhenke** [comment]
Note files are on the local file system. I see the same behaviour with both Linux and Windows.

**Comment by pbek** [comment]
Ah, now I know what you mean. In Markdown a line break does not result in a line break, you have to use two ore more spaces and a line break.
http://daringfireball.net/projects/markdown/syntax#p

**Comment by janhenke** [comment]
Well QOwnNotes has the bad habit of removing blank lines. So leaving two empty lines is currently not possible.

**Comment by pbek** [comment]
I can't reproduce this behaviour on Win7. :(
But can you do two spaces and a line break?

**Comment by janhenke** [comment]
Why two spaces? A blank line is enough to split one paragraph from the next. Quoting from the above link:
```
A paragraph is simply one or more consecutive lines of text, separated by one or more blank lines.
```
Blank really means a line break immediately followed by another line break. That must work.

QOwnNotes must not remove any blank lines from the note. Do not mistaken my issues, I like the application, just trying to improve it.

**Comment by pbek** [comment]
QOwnNotes doesn't remove blank lines in the edit view, at least not under Windows 7, Mac and Linux. Do you have that problem under Linux too?

**Comment by janhenke** [comment]
I had it happen yesterday, but I cannot yet reproduce it reliable yet. I will keep an eye on it and report back if I notice a pattern which triggers this behaviour.
