### ISSUE TITLE
New Version notification not completly visible

### ISSUE THREAD

**Issue by calis2002** [pbek/QOwnNotes#90]
In Windows 10 the new version notification in the statusbar is not completly visible.
![2016-02-20__12_07_58](https://cloud.githubusercontent.com/assets/4539953/13196307/c8cf08e4-d7ca-11e5-8fff-89a6618b0fb5.png)

**Comment by pbek** [comment]
And it is obviously not on the right side... I love it :)
Thank you for the report!

**Comment by pbek** [comment]
Will be fixed in 1.0.4. Thanks again for the report!

**Comment by pbek** [comment]
Version 1.0.4 is out now.

**Comment by pbek** [comment]
Version 1.0.5 is out now, can you see the update notice button on the right side now?

**Comment by pbek** [comment]
In case you haven't installed v1.0.4, this is the link to 1.0.4 for Windows:
https://github.com/pbek/QOwnNotes/releases/download/windows-b1064/QOwnNotes.zip

**Comment by calis2002** [comment]
Problem solved, keep up the good work +1

**Comment by pbek** [comment]
Thank you for reporting and testing, have a great evening!
