### ISSUE TITLE
Cant edit any note in Qwnotes

### ISSUE THREAD

**Issue by lbwl** [pbek/QOwnNotes#900]
Hi,
if I start QOwnNotes I can see the Notes but I can’t edit them. There is no cursor and no highlight of the selected line in the edit window.
I have 2 folders, both of them local on my computer and I have write access to them. I can create new notes. I can edit the Notes in an external editor. 
Is there an option to set QOwnNotes in a read only mode? Where are the Settings stored? Can I reset all settings?
I use 
QOwnNotes - version 18.04.4 - AppVeyor - build 3573
Windows 10 pro Version 1709 (Build 16299.371)

**Comment by pbek** [comment]
Is `Disallow all note editing` active in the `Note` menu?

**Comment by pbek** [comment]
>  Where are the Settings stored?

check the debug settings, it's printed there

> Can I reset all settings?

yes, in the settings

**Comment by lbwl** [comment]
> Is Disallow all note editing active in the Note menu?
Thank you very much! I haven’t seen the "Disallow all note editing" Option.
Maybe I hit the shortcut Alt+Shift+E.
Sorry I already thought it was such a simple problem.

> Can I reset all settings?
> yes, in the settings
There it is, under Note Settings General on the right site "Clear app data and exit"
Sorry again and thank You for your kind response!

**Comment by pbek** [comment]
No problem. :) I'm happy I could help (so easily). Have a great day!

**Comment by pbek** [comment]
## 18.04.5
- if note editing was disabled now a notification dialog will open if you start 
  typing in the note edit
    - in addition a button with the text `Read-only` will be viewed in the 
      status bar if note editing is disabled
    - you can click this button to enable note editing again

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by lbwl** [comment]
The new release works fine with me. Many Thanks! Now, even I notice
immediately what's going on and where I can change the setting :)

Bergisches Wasser- und Umweltlabor der BTV-GmbH
Schützenstr. 34, 42281 Wuppertal

Geschäftsleitung bwl
Dr. Heinz-Günther Preis

Geschäftsführung BTV-GmbH
Dipl.-Ök. Claudia Fischer
Andreas Schwarberg
Prof. Dr. Thomas Hoffmann
Rolf Menzel

Amtsgericht Wuppertal HRB 11057

Sind Sie nicht der bestimmungsgemäße Empfänger dieser E-Mail,
benachrichtigen Sie bitte den Absender, indem Sie auf diese Nachricht
antworten.


>>> Patrizio Bekerle <notifications@github.com> 29.04.2018 09:04 >>>
There now is a new release, could you please test it and report if it
works for you?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
( https://github.com/pbek/QOwnNotes/issues/900#issuecomment-385230717)
, or mute the thread
(

**Comment by pbek** [comment]
great :) thank you for testing!
