### ISSUE TITLE
Allow for Storing Attached Files in a per Note Sub Folder

### ISSUE THREAD

**Issue by mangebjl** [pbek/QOwnNotes#901]
I occasionally write documentation in QOwnNotes. The note, together with any images, I then pass to a Static Site Generator (SSG) to produce a navigatable html document. This works quite well. However, one improvement that I can see would be if there was a way to store the attached images together with the Note. 

As it is now, all images are stored in the media folder in the Notes root folder.  This means that if I have many notes with images in them, they will be all mixed up, and it will prevent me from being able to just take the note and paste it into the SSG. 

I checked if by using Notes folders there would be a media folder for each sub folder, because that could actually cover my needs. As this wasn't the case, my proposal is therefore the following: 

Make it possible to store any images added to a note in a folder in the closest root folder. Images should be relatively linked to this folder. It would also be good if it was possible to keep the name of the file intact.

Example structure:
* Notes Root (Note Folder Path)
* Media
    * Note 1 Image.jpg
    * Note 2 Image.jpg
* Note 1
* Note 2
* My Special Notes
    * Media
        * My Special Note 1 Image.jpg
        * My Special Note 2 Image.jpg
    * My Special Note 1
    * My Special Note 2

Thanks for considering this!

**Comment by pbek** [comment]
I'm sorry, that would break a lot of things and would be hard to change. :/

**Comment by mangebjl** [comment]
Sorry to hear that, but thanks anyway for an excellent tool :)

**Comment by pbek** [comment]
Thank you very much. ;)
