### ISSUE TITLE
Feature Request: add script noteTextEditReplace

### ISSUE THREAD

**Issue by vanleo2001** [pbek/QOwnNotes#902]
In QON qml script, noteTextEditWrite will append the text. But I need a script noteTextEditReplace, which can replace all the text in current note. Can you add it?

**Comment by pbek** [comment]
You could to that by using `writeToFile` to write to the `currentNote().fullNoteFilePath`. The note text you can find in `currentNote().noteText`. And you can replace text with `text = text.replace(/your text/gm, "replaced text");`.

**Comment by pbek** [comment]
## 18.05.0
- there now is a new scripting command `script.noteTextEditSelectAll()` to 
  select all text in the note text edit
    - you can use this together with `script.noteTextEditWrite()` to overwrite
      the whole text of the current note
    - for more information please take a look at the [scripting documentation](http://docs.qownnotes.org/en/develop/scripting/README.html#select-all-text-in-the-note-text-edit)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
