### ISSUE TITLE
Feature request: Sort selected text

### ISSUE THREAD

**Issue by wiktor2200** [pbek/QOwnNotes#903]
Hello, I've recently found QOwnNotes and I'm still discovering new features. 
There is one, which I cannot see and which I find very useful i.e. **sorting selected text** (under button or right-click etc.). 
In Atom there is such extension named: [sort-lines](https://atom.io/packages/sort-lines) there are gif which shows main concept.

**Comment by pbek** [comment]
You can do this with a script with http://docs.qownnotes.org/en/develop/scripting/README.html#read-the-selected-text-in-the-note-text-edit and http://docs.qownnotes.org/en/develop/scripting/README.html#write-text-to-the-note-text-edit in a custom action (http://docs.qownnotes.org/en/develop/scripting/README.html#registering-a-custom-action).

**Comment by wiktor2200** [comment]
The following week, I'm in :)

**Comment by pbek** [comment]
Be sure to let us know what you came up with! ;)

**Comment by wiktor2200** [comment]
I've written this script and created pull request in repo [scripts](https://github.com/pbek/scripts). :)
I hope my code/feature will be helpful for more users. :)

**Comment by pbek** [comment]
looking great, thank you!
