### ISSUE TITLE
Link to local files in windows dont work with space and () in file name

### ISSUE THREAD

**Issue by magicnemo** [pbek/QOwnNotes#908]
Hi,

I'm using QOwnNote 18.05.2 in Windows 10. I'm using links to local files in my text files a lot (for work).

**File name that Don't work** (Bug)
[link](file:///Z:\iPad Filofax\Metric_Ecosystem_v3_design_(1).pdf)
[link](file:///Z:\iPad Filofax\Metric Ecosystem v3 design (1).pdf)

**File name that Work**
[link](file:///Z:\iPad Filofax\Metric_Ecosystem_v3_design.pdf)

**When Comparing to opening the fyle in "Typora" Windows Markdown program**
[link](Z:\iPad Filofax\Metric Ecosystem v3 design (1).pdf)
It works in Typora.

**Summary:**
All links above work directly in Typora, and the one I prefer, to minimize extra text when making links, would be this kind. (Supported by e.g. Typora)
   [link](Z:\iPad Filofax\Metric Ecosystem v3 design (1).pdf)

**Comment by pbek** [comment]
Spaces in URLs have to be "escaped", please try using `%20` instead of spaces.

**Comment by pbek** [comment]
Did you use the *Insert link* or *Insert attachment* to insert the links?

**Comment by magicnemo** [comment]
I wrote the links myself in text. 

If i try "insert link" for file "Z:\iPad Filofax\Metric Ecosystem v3 design (1).pdf" I get:
   <http://"Z:\iPad Filofax\Metric Ecosystem v3 design (1).pdf">

altering above link doesnt work either e.g. 
    <file:///Z:\iPad Filofax\Metric%20Ecosystem%20v3%20design%20(1).pdf>
neither does 
    [link](file:///Z:\iPad Filofax\Metric%20Ecosystem%20v3%20design%20(1).pdf)

**Comment by magicnemo** [comment]
Sorry forgot %20 in the befinning of the path

Don't work: 
[link](file:///Z:\iPad%20Filofax\Metric%20Ecosystem%20v3%20design%20(1).pdf)

Now Works: 
<file:///Z:\iPad%20Filofax\Metric%20Ecosystem%20v3%20design%20(1).pdf>

**Comment by pbek** [comment]
You didn't escape all spaces (and there are possibly even more characters to escape). Please try *Insert link* to see how it should be done.

**Comment by pbek** [comment]
Great :)

**Comment by magicnemo** [comment]
ok. this one works, <file:///Z:\iPad%20Filofax\Metric%20Ecosystem%20v3%20design%20(1).pdf>
However still not using []() syntax

**Comment by pbek** [comment]
> However still not using syntax

what syntax do you mean?

**Comment by magicnemo** [comment]
The text keeps disappearing when i write here :)  The manual syntax of [ ] ( ) <- Hope its visible now

**Comment by magicnemo** [comment]
I.e. [link](file:///Z:\iPad%20Filofax\Metric%20Ecosystem%20v3%20design%20(1).pdf)

**Comment by magicnemo** [comment]
[ link ] ( file:///Z:\iPad%20Filofax\Metric%20Ecosystem%20v3%20design%20(1).pdf )
(without spaces)

**Comment by pbek** [comment]
are you talking about linking non-urls? then please see: #266

**Comment by magicnemo** [comment]
ok

**Comment by pbek** [comment]
or do you still have troubles with `[link] (file:///Z:\iPad%20Filofax\Metric%20Ecosystem%20v3%20design%20(1).pdf)`?

**Comment by magicnemo** [comment]
still trouble that it wont open. If i open the text file in external Editor "Typora" it opens directly

**Comment by pbek** [comment]
> Please try *Insert link* to see how it should be done.

did you already do that?

**Comment by magicnemo** [comment]
If i try insert link from menu, i get < http://"Z:\iPad Filofax\Metric Ecosystem v3 design (1).pdf" >. Altering it 
to < file:///Z:\iPad%20Filofax\Metric%20Ecosystem%20v3%20design%20(1).pdf > works.

But writing it as 
[ link ]( file:///Z:\iPad%20Filofax\Metric%20Ecosystem%20v3%20design%20(1).pdf )
do not work

**Comment by magicnemo** [comment]
[ link]
( file:///Z:\iPad%20Filofax\Metric%20Ecosystem%20v3%20design%20(1).pdf )

**Comment by magicnemo** [comment]
Ah sorry i pasted path in "Insert file" text box, when I choose file picker is writes correct syntax ditrectly i.e.  < file:///Z:/iPad%20Filofax/Metric%20Ecosystem%20v3%20design%20(1).pdf >

**Comment by pbek** [comment]
Please use *Insert link* and choose the file to link to (there is a button on the top right of the dialog). And please use the markdown code "markup" if you want to post your urls here on GitHub. :)

**Comment by pbek** [comment]
ah, you already found that dialog :)

**Comment by magicnemo** [comment]
ok :)

**Comment by pbek** [comment]
I cannot reproduce that, for me a link like `<file:///home/user/folder/test.txt>` is created and that link works.

**Comment by KraxelHuber** [comment]
I made a mistake. I can confirm that it is working properly.

**Comment by pbek** [comment]
great ;)

**Comment by tobias-hammerschmidt** [comment]
Still having issues with file urls on windows in `QOwnNotes - version 18.11.5 - AppVeyor - build 3958`.
I'm using file urls to unc paths like this: `file://///server/path_a/path_b/path%20with%20spaces/`. Opening this link in a browser works fine however when clicking within the preview window of QOwnNotes nothing happens. When enabling debugging I can see the following lines in the error log:
```
[Nov 22 13:54:03] [debug]: on_noteTextView_anchorClicked  - 'url':  QUrl("file://///server/path_a/path_b/path with spaces/")
[Nov 22 13:54:03] [debug]: QOwnNotesMarkdownTextEdit  openUrl  - 'urlString':  "file://///server/path_a/path_b/path with spaces/"
[Nov 22 13:54:03] [debug]: QMarkdownTextEdit  openUrl  - 'urlString':  "file://///server/path_a/path_b/path with spaces/"
[Nov 22 13:54:03] [warning]: ShellExecute 'file://///server/path_a/path_b/path with spaces/' failed (error 3).
```
Looks like the escaped spaces are getting replaced by real spaces before opening.

**Comment by pbek** [comment]
Can anyone else confirm this issue?

**Comment by tobias-hammerschmidt** [comment]
Just checked the behavior for net shares - if I create a net share for the unc path and open the url like this `file:///Z:/path_b/path%20with%20spaces/` (where `Z:` is `//server/path_a/`) opening from within QOwnNotes works! Also in the log the urls are shown with real spaces and not percent-encoded. So looks like this only affects unc paths.

**Comment by tobias-hammerschmidt** [comment]
Finally resolved after reading https://social.msdn.microsoft.com/Forums/windowsapps/en-US/48ea2ff7-fab6-4484-ab12-9307399cf47e/shellexecute-with-long-32k-unc-path-how-do-that-on-windows-7?forum=windowsgeneraldevelopmentissues - if the url for the unc path is given as `file://///?/UNC/server/path_a/path_b/path%20with%20spaces/` opening the link from QOwnNotes works. Maybe you can add this information to the documentation?

**Comment by pbek** [comment]
I had no troubles with `<file:///C:/Users/myuser/Downloads/library%20with%20space/URL%20Test.pdf>`.
But `<file://vboxsvr/Virtual_Box_Shared/QOwnNotes%20(2)/URL%20Test.pdf>` didn't seem to work, maybe it's just a limitation of `QDesktopServices::openUrl` or the Windows API itself...

How did you put the link into your notes? With the link dialog?

**Comment by tobias-hammerschmidt** [comment]
I've manually entered the file url. I also verified that the url is correct by opening it in chrome as well as in the windows run dialog. At least in QT4 there seems to be special handling for unc paths: https://bugreports.qt.io/browse/QTBUG-13359?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true. If I drop 3 of the 5 slashes after the protocol spec the preview window in QOwnNotes automatically inserts the location of the notes folder in front of the server path so `file://server/path_a/path_b/path%20with%20spaces/` becomes `file:///C:/QOwnNotes_notes_folder/server/path_a/path_b/path%20with%20spaces/`.

**Comment by CptAFK** [comment]
Attachment file by menu/edit/insert/insert attachment
`[Relative path](file://attachments/536117841-1.isb)`

> [12:29:09] [warning] ShellExecute 'file://///file3/home/appiis/kravtsov.aleksandr/MarkDown/Tasks/attachments/536117841-1.isb' failed (error 3).

If edit himself
`[Relative path](file:/attachments/536117841-1.isb)
`
> [12:32:04] [warning] ShellExecute 'file://///file3/home/appiis/kravtsov.aleksandr/MarkDown/Tasks/file3/home/appiis/kravtsov.aleksandr/MarkDown/Tasks/!Очередь/Договора/file:/attachments/536117841-1.isb' failed (error 3).


`good open [Full path](file:////file3/home/appiis/kravtsov.aleksandr/MarkDown/Tasks/attachments/536117841.isb)`
