### ISSUE TITLE
Allow code block feature to wrap existing text when selected

### ISSUE THREAD

**Issue by robled** [pbek/QOwnNotes#91]
It may be the case that a user has already inserted some code or plaintext into their note and would like to easily wrap that text with the code block tick marks.  Perhaps when there is selected text the "Insert Code Block" button/shortcut could wrap the selected text with tick marks.  

This feature would work similarly to the "Insert Code" feature in this bug tracker form here on Github.

**Comment by pbek** [comment]
That's a great idea, I QOwnNotes does already the same with the *insert link* feature.

**Comment by pbek** [comment]
will be released with version 1.0.5

**Comment by pbek** [comment]
v1.0.5 is out now

**Comment by pbek** [comment]
I will close this issue now, @robled. Please feel free to open it again if you have anything to add.
