### ISSUE TITLE
18.05.2: Workspaces: saving or reloading does not work

### ISSUE THREAD

**Issue by schittli** [pbek/QOwnNotes#910]
Good evening,
thank you for your great work on QOwnNotes!, you have brought great ideas into life :-)

#### Expected behaviour
1. We define a Layout, e.g. the middle Column has ~75% of the screen, the right Column (Note preview) has about ~10%
2. We save a new Workspace and name it e.g. "Editing"
3. We define another Layout, e.g. the middle Column has ~10% of the screen, the right Column (Note preview) has about ~75%
4. We save a new Workspace and name it e.g. "Preview"
5. If we switch between both Workspaces using `Shift Alt P`, then the Layout changes between both settings

#### Actual behaviour
- If we press `Shift Alt P`, then the toolbar displays the changed Workspace name, but the column widths don't change.
- Sometimes, different Worksapce settings do change the colum widths, but it looks a little bit random.

#### Steps to reproduce
See _Expected behaviour_

#### Output from the debug section in the settings dialog
I guess it is not necessary

**Comment by pbek** [comment]
I think you maybe got it wrong, if you create a new workspace it is created with the current layout properties. So your Editing and Preview workspaces currently have the same layout properties... 
You changed Preview with step 3 and  then added a new workspace with the current properties....

**Comment by pbek** [comment]
And thank you for your kind words!

**Comment by schittli** [comment]
**Thank you very much, @pbek for your clarification!**
actually (maybe), it's a pity that a workspace doesn't also save the size of the layout elements because I continuously resize them (mostly, I manually change the column widths, sometimes the height).

**Comment by pbek** [comment]
> it's a pity that a workspace doesn't also save the size of the layout elements 

which layout elements do you mean?

**Comment by schittli** [comment]
I use Window Layout Manager e.g. in Visual Studio and they save everything related to the visible window items. Translated to QOwnNotes it would mean that a user:
- show/hide the desired panels
- places the panels in three QOwnNotes main columns and set the Panel heights
- at last, the user resizes the widths of the three QOwnNotes main columns

If the user saves this configuration (=Workspace) and later reloads it, the all Panels are hidden/shown as saved and all positions/sizes are restored, so that it looks exactly as it was saved before.

This is the reason why I expected that the three QOwnNotes main columns widths are saved in a workspace (My left column contains panels like Subfolders, Tags, Navigation, the middle column is the editing column, and my right column has the preview panel).

This concept does not need that QOwnNotes has to guess the best width for each column, it can just re-apply the saved settings.

But QOwnNotes would still need some logic if a Workspace is reloaded on a monitor with a different screen size. Maybe, it would be enough to save the Column widths / Panel heights as percentages, so that the relations are restored. 

And the users could still create additional workspaces, one for each screen size :-)

**Comment by pbek** [comment]
I'm not sure I can follow you...
Currently everything (most of it) is stored in the current workspace when you are changing something..

**Comment by schittli** [comment]
> I'm not sure I can follow you...

Hmmm..., I have the same question :-):
In my initial post, I explained that I had created two different layouts and saved each one in its own Workspace, this time I use a graphical representation :-)

1. Move the panels and columns, so that they look like this:
#### Editing Workspace:
```
+--------------------+
|___|          |     |
|___|          |_____|
|   |          |     |
+--------------------+
```
2. Save this Configuration: Window » Workspaces » Add new Workspace. Name: Editing
3. Move the panels and columns, so that they look like this:
#### Reading Workspace:
```
+--------------------+
|   |      |         |
|___|      |_________|
|   |      |         |
+--------------------+
```
4. Save this Configuration: Window » Workspaces » Add new Workspace. Name: Reading

5. Switch between both Workspaces
Nothing happens, the widths of the 3 main columns don't change.
Therefore, I guess that QOwnNotes does not save (or does not re-apply onload) the size of the Panels.

Or, `Add new Workspace` does mean something else :-)

**Comment by pbek** [comment]
Please see by comment above:

> I think you maybe got it wrong, if you create a new workspace it is created with the current layout properties. So your Editing and Preview workspaces currently have the same layout properties...
You changed Preview with step 3 and then added a new workspace with the current properties....

In your case you only have to do your last example in this order:
2, 1, 4, 3, 5

that's all
