### ISSUE TITLE
[Feature Request] Local history

### ISSUE THREAD

**Issue by jaltek** [pbek/QOwnNotes#917]
Hi,

first of all: What a great piece of software. Thanks for that!

I've tested the option "Use git to keep a local history of your notes" (which works flawlessly) and the way I understood it QOwnNotes checks every 30 sec. for changes and then commits them to to the git repo, right?

Well, it would be nice to have the history of the single notes local (by using the local git repo) in order to not rely on a Nextcloud installation.

Keep up the good work!

Cheers!

**Comment by pbek** [comment]
Thank you for your kind words.

> the way I understood it QOwnNotes checks every 30 sec. for changes and then commits them to to the git repo, right?

that's right

> Well, it would be nice to have the history of the single notes local (by using the local git repo) in order to not rely on a Nextcloud installation.

If you have configured a git client you can right click on the note in the note list to view the version. Was that your question?

**Comment by jaltek** [comment]
:man_facepalming: Sorry. I totally missed the configuration section "General => Git versioning".
Nevertheless: I configured the path to gitk to ```/usr/bin/gitk``` but do not have a new option in the right-click context menu.

(Using your openSUSE version - 18.05.6 - OBS - build 443)

**Comment by pbek** [comment]
I cannot reproduce that. Are you sure you have git versioning turned on for the current note folder?

**Comment by jaltek** [comment]
Yes. I can see the ```.git``` folder inside as well the recent commits from QOwnNotes:

```
commit 8c55a0cfbe2cb3d37972603e8d5b7751db43d84c (HEAD -> master)
Author: jaltek <***>
Date:   Tue May 22 10:12:44 2018 +0200

    QOwnNotes commit

commit 9e9077b375ad1bbe1b414ce1b34c14328f1558b2
Author: jaltek <***>
Date:   Tue May 22 10:09:05 2018 +0200

    QOwnNotes commit

commit 636acf9aa8643d3d45ba43edfe980504add05641
Author: jaltek <***>
Date:   Tue May 22 10:05:53 2018 +0200

    QOwnNotes commit

```

**Comment by pbek** [comment]
The menu entry in the note-list says `Show note git versions`.

**Comment by pbek** [comment]
Can please you send your settings from the *Debug settings* and a screenshot of your note-list context menu?

**Comment by jaltek** [comment]
Sure:

![selection_183](https://user-images.githubusercontent.com/359552/40352234-9eab5344-5dae-11e8-9636-130254ed6bb4.jpg)


## Settings

**AboutDialog/geometry**: `<binary data>`
**ActiveNoteHistoryItem**: *empty*
**Debug/fakeOldVersionNumber**: `false`
**Debug/fileLogging**: `false`
**Editor/CurrentSchemaKey**: `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing**: `true`
**Editor/autoBracketRemoval**: `true`
**Editor/editorWidthInDFMOnly**: `true`
**Editor/highlightCurrentLine**: `true`
**LastUpdateCheck**: `2018-05-22T10:47:16`
**LocalTrashDialog/geometry**: `<binary data>`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `22`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `Hack,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font**: `Noto Sans,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font**: `Hack,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font**: `Noto Sans,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.rtl**: `false`
**MainWindow/showNotesFromAllNoteSubFolders**: `true`
**MessageBoxOverride/tag-notes**: `16384`
**PiwikClientId**: `<hidden>`
**SearchEngineId**: `2`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**ShowSystemTray**: `false`
**StartHidden**: `false`
**WelcomeDialog/geometry**: `<binary data>`
**acceptAllExternalModifications**: `false`
**allowDifferentNoteFileName**: `false`
**allowNoteEditing**: `true`
**allowOnlyOneAppInstance**: `false`
**appMetrics/disableAppHeartbeat**: `true`
**appMetrics/disableTracking**: `true`
**appMetrics/notificationShown**: `true`
**closeTodoListAfterSave**: `false`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**currentWorkspace**: `43a19e9e-cf51-4cfa-a54a-e006d04fa729`
**cursorWidth**: `1`
**customNoteFileExtensionList**: *empty*
**darkMode**: `false`
**darkModeColors**: `false`
**darkModeTrayIcon**: `false`
**defaultNoteFileExtension**: `md`
**demoNotesCreated**: `true`
**disableAutomaticUpdateDialog**: `true`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: *empty*
**fullyHighlightedBlockquotes**: `false`
**gitCommitInterval**: `30`
**gitExecutablePath**: *empty*
**gitLogCommand**: `/usr/bin/gitk`
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**imageScaleDown**: `false`
**imageScaleDownMaximumHeight**: `1024`
**imageScaleDownMaximumWidth**: `1024`
**insertTimeFormat**: *empty*
**interfaceLanguage**: *empty*
**internalIconTheme**: `false`
**itemHeight**: `24`
**localTrash/autoCleanupDays**: `30`
**localTrash/autoCleanupEnabled**: `true`
**localTrash/supportEnabled**: `true`
**localTrashSplitterSizes**: `<binary data>`
**markdownHighlightingEnabled**: `true`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `2`
**newNoteAskHeadline**: `false`
**noteEditIsCentralWidget**: `true`
**noteSaveIntervalTime**: `10`
**noteSubfoldersPanelDisplayAsFullTree**: `true`
**noteSubfoldersPanelHideSearch**: `false`
**noteSubfoldersPanelOrder**: `0`
**noteSubfoldersPanelShowFullPath**: `false`
**noteSubfoldersPanelShowNotesRecursively**: `false`
**noteSubfoldersPanelShowRootFolderName**: `true`
**noteSubfoldersPanelSort**: `0`
**notesPanelOrder**: `0`
**notesPanelSort**: `1`
**notesPath**: `/home/jaltek/Documents/Notes`
**notifyAllExternalModifications**: `false`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: *empty*
**ownCloud/supportEnabled**: `false`
**ownCloud/todoCalendarBackend**: `3`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloud/userName**: *empty*
**previousWorkspace**: `0d65e4ed-6ae3-4115-828e-2e7fe82fc240`
**restoreCursorPosition**: `true`
**savedSearches/noteFolder-1**: `Note 2018-05-22T10.48.31, Note 2018-05-22T10.00.01, Note 2018-05-22T09.17.17`
**showMenuBar**: `true`
**showStatusBar**: `true`
**tagWasAddedToNote**: `true`
**taggingShowNotesRecursively**: `false`
**tagsPanelHideSearch**: `false`
**tagsPanelOrder**: `0`
**tagsPanelSort**: `0`
**toolbar/1/items**: `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name**: `mainToolBar`
**toolbar/1/title**: `main toolbar`
**toolbar/2/items**: `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name**: `formattingToolbar`
**toolbar/2/title**: `formatting toolbar`
**toolbar/3/items**: `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name**: `insertingToolbar`
**toolbar/3/title**: `inserting toolbar`
**toolbar/4/items**: `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name**: `encryptionToolbar`
**toolbar/4/title**: `encryption toolbar`
**toolbar/5/items**: `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name**: `windowToolbar`
**toolbar/5/title**: `window toolbar`
**toolbar/6/items**: `action_Quit`
**toolbar/6/name**: `quitToolbar`
**toolbar/6/title**: `quit toolbar`
**toolbar/size**: `6`
**useUNIXNewline**: `false`
**workspace-0d65e4ed-6ae3-4115-828e-2e7fe82fc240/name**: `full`
**workspace-0d65e4ed-6ae3-4115-828e-2e7fe82fc240/noteSubFolderDockWidgetVisible**: `true`
**workspace-0d65e4ed-6ae3-4115-828e-2e7fe82fc240/windowState**: `<binary data>`
**workspace-43a19e9e-cf51-4cfa-a54a-e006d04fa729/name**: `minimal`
**workspace-43a19e9e-cf51-4cfa-a54a-e006d04fa729/noteSubFolderDockWidgetVisible**: `true`
**workspace-43a19e9e-cf51-4cfa-a54a-e006d04fa729/windowState**: `<binary data>`
**workspaces**: `0d65e4ed-6ae3-4115-828e-2e7fe82fc240, 43a19e9e-cf51-4cfa-a54a-e006d04fa729`

**Comment by pbek** [comment]
I'm sorry, I also need the settings from the `Note folders` headline in the *Debug settings* (can you please post the whole content).

**Comment by jaltek** [comment]
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue May 22 10:51:05 2018`
**Version**: `18.05.6`
**Build date**: `May 21 2018`
**Build number**: `443`
**Platform**: `linux`
**Operating System**: `openSUSE Tumbleweed`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.10.0`
**Qt Version (runtime)**: `5.10.0`
**Portable mode**: `no`
**Settings path / key**: `/home/jaltek/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/jaltek/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze`
**Notes in current note folder**: `4`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: `unknown`
**connectionErrorMessage**: `Protocol "" is unknown`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `1`
**localPath**: `/home/jaltek/Documents/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/jaltek/Documents/Notes/notes.sqlite`

## Enabled scripts

## Settings

**AboutDialog/geometry**: `<binary data>`
**ActiveNoteHistoryItem**: *empty*
**Debug/fakeOldVersionNumber**: `false`
**Debug/fileLogging**: `false`
**Editor/CurrentSchemaKey**: `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing**: `true`
**Editor/autoBracketRemoval**: `true`
**Editor/editorWidthInDFMOnly**: `true`
**Editor/highlightCurrentLine**: `true`
**LastUpdateCheck**: `2018-05-22T10:47:16`
**LocalTrashDialog/geometry**: `<binary data>`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `22`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `Hack,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font**: `Noto Sans,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font**: `Hack,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font**: `Noto Sans,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.rtl**: `false`
**MainWindow/showNotesFromAllNoteSubFolders**: `true`
**MessageBoxOverride/tag-notes**: `16384`
**PiwikClientId**: `<hidden>`
**SearchEngineId**: `2`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**ShowSystemTray**: `false`
**StartHidden**: `false`
**WelcomeDialog/geometry**: `<binary data>`
**acceptAllExternalModifications**: `false`
**allowDifferentNoteFileName**: `false`
**allowNoteEditing**: `true`
**allowOnlyOneAppInstance**: `false`
**appMetrics/disableAppHeartbeat**: `true`
**appMetrics/disableTracking**: `true`
**appMetrics/notificationShown**: `true`
**closeTodoListAfterSave**: `false`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**currentWorkspace**: `43a19e9e-cf51-4cfa-a54a-e006d04fa729`
**cursorWidth**: `1`
**customNoteFileExtensionList**: *empty*
**darkMode**: `false`
**darkModeColors**: `false`
**darkModeTrayIcon**: `false`
**defaultNoteFileExtension**: `md`
**demoNotesCreated**: `true`
**disableAutomaticUpdateDialog**: `true`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: *empty*
**fullyHighlightedBlockquotes**: `false`
**gitCommitInterval**: `30`
**gitExecutablePath**: *empty*
**gitLogCommand**: `/usr/bin/gitk`
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**imageScaleDown**: `false`
**imageScaleDownMaximumHeight**: `1024`
**imageScaleDownMaximumWidth**: `1024`
**insertTimeFormat**: *empty*
**interfaceLanguage**: *empty*
**internalIconTheme**: `false`
**itemHeight**: `24`
**localTrash/autoCleanupDays**: `30`
**localTrash/autoCleanupEnabled**: `true`
**localTrash/supportEnabled**: `true`
**localTrashSplitterSizes**: `<binary data>`
**markdownHighlightingEnabled**: `true`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `2`
**newNoteAskHeadline**: `false`
**noteEditIsCentralWidget**: `true`
**noteSaveIntervalTime**: `10`
**noteSubfoldersPanelDisplayAsFullTree**: `true`
**noteSubfoldersPanelHideSearch**: `false`
**noteSubfoldersPanelOrder**: `0`
**noteSubfoldersPanelShowFullPath**: `false`
**noteSubfoldersPanelShowNotesRecursively**: `false`
**noteSubfoldersPanelShowRootFolderName**: `true`
**noteSubfoldersPanelSort**: `0`
**notesPanelOrder**: `0`
**notesPanelSort**: `1`
**notesPath**: `/home/jaltek/Documents/Notes`
**notifyAllExternalModifications**: `false`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: *empty*
**ownCloud/supportEnabled**: `false`
**ownCloud/todoCalendarBackend**: `3`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloud/userName**: *empty*
**previousWorkspace**: `0d65e4ed-6ae3-4115-828e-2e7fe82fc240`
**restoreCursorPosition**: `true`
**savedSearches/noteFolder-1**: `Note 2018-05-22T10.48.31, Note 2018-05-22T10.00.01, Note 2018-05-22T09.17.17`
**showMenuBar**: `true`
**showStatusBar**: `true`
**tagWasAddedToNote**: `true`
**taggingShowNotesRecursively**: `false`
**tagsPanelHideSearch**: `false`
**tagsPanelOrder**: `0`
**tagsPanelSort**: `0`
**toolbar/1/items**: `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name**: `mainToolBar`
**toolbar/1/title**: `main toolbar`
**toolbar/2/items**: `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name**: `formattingToolbar`
**toolbar/2/title**: `formatting toolbar`
**toolbar/3/items**: `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name**: `insertingToolbar`
**toolbar/3/title**: `inserting toolbar`
**toolbar/4/items**: `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name**: `encryptionToolbar`
**toolbar/4/title**: `encryption toolbar`
**toolbar/5/items**: `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name**: `windowToolbar`
**toolbar/5/title**: `window toolbar`
**toolbar/6/items**: `action_Quit`
**toolbar/6/name**: `quitToolbar`
**toolbar/6/title**: `quit toolbar`
**toolbar/size**: `6`
**useUNIXNewline**: `false`
**workspace-0d65e4ed-6ae3-4115-828e-2e7fe82fc240/name**: `full`
**workspace-0d65e4ed-6ae3-4115-828e-2e7fe82fc240/noteSubFolderDockWidgetVisible**: `true`
**workspace-0d65e4ed-6ae3-4115-828e-2e7fe82fc240/windowState**: `<binary data>`
**workspace-43a19e9e-cf51-4cfa-a54a-e006d04fa729/name**: `minimal`
**workspace-43a19e9e-cf51-4cfa-a54a-e006d04fa729/noteSubFolderDockWidgetVisible**: `true`
**workspace-43a19e9e-cf51-4cfa-a54a-e006d04fa729/windowState**: `<binary data>`
**workspaces**: `0d65e4ed-6ae3-4115-828e-2e7fe82fc240, 43a19e9e-cf51-4cfa-a54a-e006d04fa729`

## System environment

**GS_LIB**: `/home/jaltek/.fonts`
**KDE_FULL_SESSION**: `true`
**LC_ALL**: `en_US.UTF-8`
**PILOTPORT**: `usb:`
**HOSTTYPE**: `x86_64`
**LC_MEASUREMENT**: `de_DE.UTF-8`
**XAUTHLOCALHOSTNAME**: `jaltek`
**LESSCLOSE**: `lessclose.sh %s %s`
**LC_MONETARY**: `de_DE.UTF-8`
**XKEYSYMDB**: `/usr/X11R6/lib/X11/XKeysymDB`
**LANG**: `de_DE.UTF-8`
**WINDOWMANAGER**: `/usr/bin/startkde`
**LESS**: `-M -I -R`
**DISPLAY**: `:0`
**JAVA_ROOT**: `/usr/java/latest`
**HOSTNAME**: `jaltek`
**CONFIG_SITE**: `/usr/share/site/x86_64-unknown-linux-gnu`
**CSHEDIT**: `emacs`
**EDITOR**: `joe`
**AUDIODRIVER**: `pulseaudio`
**GPG_TTY**: `not a tty`
**LESS_ADVANCED_PREPROCESSOR**: `no`
**COLORTERM**: `1`
**JAVA_HOME**: `/usr/java/latest`
**ALSA_CONFIG_PATH**: `/etc/alsa-pulse.conf`
**MACHTYPE**: `x86_64-suse-linux`
**XDG_VTNR**: `7`
**QEMU_AUDIO_DRV**: `pa`
**SSH_AUTH_SOCK**: `/tmp/ssh-PHtMVSeQ2uAh/agent.7042`
**MINICOM**: `-c on`
**QT_SYSTEM_DIR**: `/usr/share/desktop-data`
**OSTYPE**: `linux`
**XDG_SESSION_ID**: `2`
**USER**: `jan`
**PAGER**: `less`
**DESKTOP_SESSION**: `/usr/share/xsessions/plasma5`
**LC_COLLATE**: `de_DE.UTF-8`
**QT4_IM_MODULE**: `ibus`
**GOPATH**: `/home/jaltek/go`
**MORE**: `-sl`
**PWD**: `/home/jaltek`
**SSH_ASKPASS**: `/usr/lib/ssh/ssh-askpass`
**HOME**: `/home/jaltek`
**GOROOT**: `/usr/lib64/go/1.9`
**LC_CTYPE**: `en_US.UTF-8`
**SSH_AGENT_PID**: `7320`
**HOST**: `jaltek`
**XNLSPATH**: `/usr/share/X11/nls`
**XDG_SESSION_TYPE**: `x11`
**XDG_DATA_DIRS**: `/home/jaltek/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share`
**XDG_SESSION_DESKTOP**: `KDE`
**NNTPSERVER**: `news`
**PROFILEREAD**: `true`
**LC_NUMERIC**: `de_DE.UTF-8`
**GTK_MODULES**: `canberra-gtk-module`
**FROM_HEADER**: *empty*
**LC_TYPE**: `en_US.UTF-8`
**MAIL**: `/var/spool/mail/jaltek`
**LESSKEY**: `/etc/lesskey.bin`
**TERM**: `xterm`
**SHELL**: `/bin/bash`
**XDG_SESSION_CLASS**: `user`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**QT_IM_MODULE**: `ibus`
**XMODIFIERS**: `@im=ibus`
**XCURSOR_THEME**: `breeze_cursors`
**XDG_CURRENT_DESKTOP**: `KDE`
**PYTHONSTARTUP**: `/etc/pythonstart`
**SHLVL**: `1`
**XDG_SEAT**: `seat0`
**LANGUAGE**: `en_US`
**G_FILENAME_ENCODING**: `@locale,UTF-8,ISO-8859-15,CP1252`
**MANPATH**: `/usr/local/man:/usr/share/man`
**XSESSION_IS_UP**: `yes`
**OOO_FORCE_DESKTOP**: `gnome`
**LOGNAME**: `jan`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XAUTHORITY**: `/home/jaltek/.local/share/sddm/.Xauthority`
**PHPBREW_ROOT**: `/opt/phpbrew`
**INPUT_METHOD**: `ibus`
**JRE_HOME**: `/usr/java/latest/jre`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**XDG_CONFIG_DIRS**: `/etc/xdg`
**PATH**: `/home/jaltek/bin:/usr/local/bin:/usr/bin:/bin:/usr/lib/mit/sbin:/home/jaltek/go/bin:/home/jaltek/.gem/ruby/2.2.0/bin`
**JAVA_BINDIR**: `/usr/java/latest/bin`
**KDE_SESSION_UID**: `1000`
**KDE_SESSION_VERSION**: `5`
**SDL_AUDIODRIVER**: `pulse`
**GOOS**: `linux`
**QT_IM_SWITCHER**: `imsw-multi`
**G_BROKEN_FILENAMES**: `1`
**HISTSIZE**: `1000`
**CPU**: `x86_64`
**GOARCH**: `amd64`
**PHPBREW_LOOKUP_PREFIX**: *empty*
**CVS_RSH**: `ssh`
**LESSOPEN**: `lessopen.sh %s`
**GTK_IM_MODULE**: `ibus`
**LC_TIME**: `de_DE.UTF-8`
**BASH_FUNC_mc%%**: 
```
() {  . /usr/share/mc/mc-wrapper.sh
}
```
**_**: `/usr/bin/kwrapper5`
**SESSION_MANAGER**: `local/jaltek:@/tmp/.ICE-unix/7610,unix/jaltek:/tmp/.ICE-unix/7610`

**Comment by pbek** [comment]
> isUseGit: no

it seems git support is disabled for your note folder

**Comment by jaltek** [comment]
:thinking: Yes. I swear it was enabled. Otherwise there wouldn't be any commits?!

What a shame. Sorry. Maybe I should just go back to bed then :)

**Comment by pbek** [comment]
> Otherwise there wouldn't be any commits?!

maybe you have disabled it for testing? :)

> Maybe I should just go back to bed then :)

sleep always helps :) have a great night!

**Comment by pbek** [comment]
On the other hand it's almost noon in Heidelberg. :)

**Comment by jaltek** [comment]
11:20 a.m. yes :D. Thanks a lot for your help.
Maybe I just got out of bed on the wrong side.

**Comment by pbek** [comment]
No problem. :)
