### ISSUE TITLE
Website needs HTTPS

### ISSUE THREAD

**Issue by rugk** [pbek/QOwnNotes#918]
Why you should always use HTTPS (no matter whether the site is static etc.):
* https://doesmysiteneedhttps.com/
* IT security specialist: https://scotthelme.co.uk/still-think-you-dont-need-https/
* Google: https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https

**Comment by pbek** [comment]
There is a https://www.qownnotes.org/
The short answer why I don't redirect all http-requests is because of QOwnNotes update-checks on old versions of QOwnNotes... Of course I could play around with apache-rules...

**Comment by rugk** [comment]
Well… how old are these "old versions"? Should not they have been upgraded already?

**Comment by pbek** [comment]
Years old. I neither can force users to upgrade QOwnNotes nor force them to upgrade their Linux distributions to have newer versions of Qt (that support redirects in web-requests).

**Comment by rugk** [comment]
So which distros are affected?

**Comment by pbek** [comment]
For not having redirects? All Qt versions below Qt 5.6... (so that's also Ubuntu 16.04 with Qt 5.5) Why is that important for you to know?

**Comment by rugk** [comment]
Well… to see how old they are… So 16.04 LTS is supported until 2021-04… Holy cow, that's a long time.

So yes, better do some Apache tricks. E.g. you can set the HSTS header and redirect the front page only (i.e. `/`) to HTTPS.

**Comment by pbek** [comment]
https is done by cloudflare, I cannot set a HSTS header

**Comment by rugk** [comment]
Of course you can set a HSTS Header on Cloudflare, they support it with a button or so there. Also the redirect, I guess.

**Comment by pbek** [comment]
Those settings are for all sub-domains of a domain and for all paths on that sub-domain. I don't want neither of these...

**Comment by pbek** [comment]
## 18.05.7
- despite users having problems in the past with fetching the update request 
  via SSL are we trying to use https for the update request again
    - the QOwnNotes webpage <http://www.qownnotes.org> will now also be 
      automatically redirected to <https://www.qownnotes.org>

**Comment by pbek** [comment]
There now is a new release. ;)
