### ISSUE TITLE
installation crashed Microsoft office

### ISSUE THREAD

**Issue by howpure** [pbek/QOwnNotes#921]
after installation of QOwnNotes my Microsoft office does not open anymore.
How can I clearly un-install QOwnNotes? There is no uninstall.exe or something ...

**Comment by pbek** [comment]
There is no "installation"... It's just a bunch of files in the folder where you un-zipped the zip-file... you can just remove the folder if you think that this really causes the problem... you can also remove the settings of QOwnNotes in the settings dialog.

**Comment by howpure** [comment]
Thank you for your quick reply. Unfortunately this does not repair Microsoft Office :-(

**Comment by howpure** [comment]
I know, but it´s the only thing I changed on my PC.

**Comment by pbek** [comment]
If you find anything concrete please let me know.
