### ISSUE TITLE
Pasting HTML using CTRL+SHIFT+V problem

### ISSUE THREAD

**Issue by wiktor2200** [pbek/QOwnNotes#922]
Hello!
I've a problem with pasting html content which include code and especially the "<", ">" and "&" characters.
When I use CTRL+SHIFT+V paste I get it formatted, but these characters are replaced by:
```
> with &gt;
< with &lt;
& with &amp;
```
I've also checked all keyboard writable characters and only for these 3 problem occurred.
Is it a bug? Or some kind of problem with html to markdown parsing which can't be fixed in easy way?

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by wiktor2200** [comment]
I've tested new version and it works great now. Thanks for quick response :)
