### ISSUE TITLE
open several notes in new windows

### ISSUE THREAD

**Issue by dh-connect** [pbek/QOwnNotes#93]
Would it be possible to open notes in several windows? because I would like to work on several notes at the same time, e.g. copy and paste within 2 notes, at the moment you loose the position in a certain note, when you jump from note A to note B, so I use a texteditor besides the notes window at the moment, it would make the work esier to stay within qownnotes

**Comment by pbek** [comment]
At this point would be very hard to switch to a MDI-interface.

Although it is possible to use the *note history* to jump back and forth between notes you are editing. see: <http://www.qownnotes.org/shortcuts/QOwnNotes> 
You can also use the 4th and 5th mouse button for moving in the history.

Additionally you can also bookmark positions in notes. You will find the shortcuts on above page too.

Does this help you?

**Comment by pbek** [comment]
A 3rd thing you can do is starting QOwnNotes multiple times. :grin:

**Comment by dh-connect** [comment]
how can you start it multiple times? I'm working with a mac

**Comment by pbek** [comment]
Oh, I think OS X prevents that... But there still are bookmarks and the note history. Would they be of any help for you?

**Comment by dh-connect** [comment]
hm no not really, but it works to copy the app to another folder and rename it, then you can open it a second app, so that you can work with 2 windows even on different screens

**Comment by pbek** [comment]
This should work too:
http://osxdaily.com/2011/05/11/multiple-instances-application-mac/

**Comment by dh-connect** [comment]
oh thanks works great, this way I don't have to update more than 1 app

**Comment by pbek** [comment]
I will close this issue until we come up with anything else.
