### ISSUE TITLE
Rename Linux .desktop file

### ISSUE THREAD

**Issue by ludenticus** [pbek/QOwnNotes#933]
The Wayland compositor requires to change the desktop file name in order to map the window icon. So, instead of `QOwnNotes.desktop`, it has to be `PBE.QOwnNotes.desktop`, as `PBE` is the [`organizationDomain`](http://doc.qt.io/qt-5/qcoreapplication.html#organizationDomain-prop). See the porting changes [here](https://blog.martin-graesslin.com/blog/2015/07/porting-qt-applications-to-wayland/).

**Comment by pbek** [comment]
Thank you for mentioning, I'm not sure what renaming it has for existing installations.

**Comment by stobbsm** [comment]
Where as flatpak requires icons and desktop files to be in the reverse dns format of "org.qownnotes.QOwnNotes".
Not having an icon issue in the flatpak on fedora 28 wayland.

**Comment by pbek** [comment]
> Where as flatpak requires icons and desktop files to be in the reverse dns format of "org.qownnotes.QOwnNotes".

what needs to be done?

>  Not having an icon issue in the flatpak on fedora 28 wayland.

you don't have issues?

**Comment by pbek** [comment]
I hope this doesn't make troubles...

## 18.06.2
- the desktop file `QOwnNotes.desktop` was renamed to `PBE.QOwnNotes.desktop`
  for the Wayland compositor (for [#933](https://github.com/pbek/QOwnNotes/issues/933))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
@cal2195 from which repository do you have QOwnNotes installed and do you get two menu entries for QOwnNotes? On KDE Neon it seems I now have two, one for the snap, one for the launchpad installation.

**Comment by cal2195** [comment]
I'm on a Mac atm, but I use it on my Arch machine at home! I'll have a check later, although I'm using i3 there.

**Comment by pbek** [comment]
Ok, thank you @cal2195. I assume you are using the AUR too then.

**Comment by ludenticus** [comment]
In gnome-shell I can add QON to the dash as a `Favorite`. It launches the program, but then it shows another instance. I think that this kind of issue was solved in Xorg via WMClass, but it changed in Wayland. I found out something regarding the Application ID. Let me see if I can post some info.

**Comment by ludenticus** [comment]
BTW, I used to install it via AUR, but now I found that archlinuxcn has binaries and I avoid the hassle of compiling. ;)

**Comment by pbek** [comment]
> It launches the program, but then it shows another instance.

what other instance? is it started a 2nd time? you can turn that off in the QON settings

**Comment by ludenticus** [comment]
I customized the `.desktop` file icon and app name, like [this](https://imgur.com/wLCcj8S). Under the gnome-shell search dash there is no other QON app. Picked as favorite, the dock shows my selected icon/name. However, after launching it  (either via dash, dock or terminal), this option is ignored and, instead, the «regular» QOwnNotes .desktop file is [shown](https://imgur.com/rYlGTFL). That's what I meant when speaking about another «instance». I'm not sure whether this is a QON issue or a qt/Wayland issue.

**Comment by pbek** [comment]
Maybe your dash shows some icon from inside the application? I guess that's a "feature" of the dash...

**Comment by pbek** [comment]
Great, Gnome seems to need the old desktop file name. See: #1019
