### ISSUE TITLE
Translating QOwnNotes into Chinese Traditional (zh_TW)

### ISSUE THREAD

**Issue by abev66** [pbek/QOwnNotes#934]
I'm traslating QOwnNotes into Chinese Traditional (Taiwan) (zh_TW). 

I'm basically try to translate it on my local computer with Lokalize. (I forked it to my github and working on develop branch)

But just I noticed this string:
`<html><head/><body><p>If you want to help to translate QOwnNotes or update an existing translation please read: <a href="http://www.qownnotes.org/Knowledge-base/How-can-I-help-to-translate-QOwnNotes">How can I help to translate QOwnNotes?</a></p></body></html>`

So I read the article and I realized I should translate it on Crowdin. 

But I have already finished about 57% (615/1075).

Is there any way to import .ts file on Crowdin or I have to put the strings on Crowdin manually?

Sorry about that.

**Comment by pbek** [comment]
Thanks a lot for your effort. I'm currently trying to add the Language to Crowdin, so I can test if there is a way to import the texts. `Chinese Traditional, Taiwan` doesn't exist on Crowdin and I can't add the language because `zh-TW` already seems to exist. <https://support.crowdin.com/api/language-codes/> tells me that is `Chinese Traditional`. It's already activated on <https://crowdin.com/project/qownnotes/zh-TW#> for QOwnNotes.

Does that seem correct to you?
Can you post the your translation file so I can try to upload it?

**Comment by abev66** [comment]
[QOwnNotes_zh_TW.txt](https://github.com/pbek/QOwnNotes/files/2083166/QOwnNotes_zh_TW.txt)

Yes, you're correct. It's Chinese Traditional. GitHub not allow me to upload .ts file so I changed the file extension to .txt

**Comment by pbek** [comment]
It worked, for some reason it shows me almost 100% translated.
https://crowdin.com/translate/qownnotes/1/en-zhtw

Does that look right to you?

Could you please register at Crowdin and tell me your username so I can make you proofreader of the translation.

**Comment by abev66** [comment]
I think it shows 100% is due to the unfinished translation strings is include the original English string in that file. I removed them. It may correct this issue.
[QOwnNotes_zh_TW.txt](https://github.com/pbek/QOwnNotes/files/2083282/QOwnNotes_zh_TW.txt)

My Crowdin ID is `abev66`. Thanks a lot for your help.

**Comment by pbek** [comment]
Thank you Crowdin for the **undo** functionality!
It did work, https://crowdin.com/project/qownnotes/zh-TW shows 59%.
I made you proofreader now, https://crowdin.com/translate/qownnotes/1/en-zhtw is all yours to translate and proofread (and accept new translations).

**Comment by abev66** [comment]
Thanks for your help. It's 100% now.

**Comment by pbek** [comment]
Wow, great work! Thanks a lot. It will be integrated in the next release!

**Comment by pbek** [comment]
## 18.06.2
- added new **Chinese Traditional translation** (for [#934](https://github.com/pbek/QOwnNotes/issues/934), a big thank you to @abev66)
    - the current translation `Chinese` is now named `Chinese Simplified`

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by abev66** [comment]
Thank you, it works for me :100:

**Comment by pbek** [comment]
Thank you again for your translation!
