### ISSUE TITLE
More options for tasks ?

### ISSUE THREAD

**Issue by bepolymathe** [pbek/QOwnNotes#936]
Hi @pbek 

I ask myself a question. 
Would it be worth considering an improvement in QON's "tasks" function? 
1. It would be very interesting to be able to integrate "tags" into tasks (because these "tags" allow several people to work on the same nextcloud instance in my case). 
2. It would be interesting to be able to select a date and time for the start of the task (and not only for the reminder). 

What do you say? Are there any technical problems with Caldav?
[The integration of tasks in the calendar could soon happen](https://github.com/nextcloud/calendar/issues/28) and it would be nice to have more options. But maybe it's a lot of work.

**Comment by pbek** [comment]
I'm sorry. CalDav is a big mess and every client implements different values for the same feature. I don't plan to spend any more time in CalDav debugging for every Client and Server and all their combinations. :/
