### ISSUE TITLE
Snap Issue - no printer mount

### ISSUE THREAD

**Issue by benyanke** [pbek/QOwnNotes#938]
Not sure if this is the correct repository to issue a ticket for the snap package, but it seems the system's printers are not mounted into the snap.

Not sure if this is possible with snaps, but just wanted to bring it up in case it was just a simple oversight and not architectural limitation.

**Comment by pbek** [comment]
I'm not sure if that's possible. This are the interfaces in snaps: https://docs.snapcraft.io/reference/interfaces

Do you get an error message?

**Comment by benyanke** [comment]
Not an error, just no printers listed.

**Comment by benyanke** [comment]
I see `cups-control`, I assume that's the interface you'd want? 

```
cups-control | Can access cups control socket which gives privileged access to configure printing.
```

I've not written a linux desktop app before, so I won't be a ton of help here, but just wanted to pass this along.

**Comment by pbek** [comment]
I can try adding it. But I guess you actually are not configuring the printers...

**Comment by pbek** [comment]
## 18.06.2
- added `cups-control` to he snap version of QOwnNotes to possibly enable 
  support for printing to printers (for [#938](https://github.com/pbek/QOwnNotes/issues/938))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by benyanke** [comment]
No luck post-upgrade.

**Comment by pbek** [comment]
Can you please try this: `snap connect libreoffice:cups-control :cups-control`
from https://askubuntu.com/questions/958708/libreoffice-snap-package-doesnt-list-the-system-printers

**Comment by benyanke** [comment]
That worked! Is that a permanent workaround, or just a debugging step?

**Comment by pbek** [comment]
I think you only have to do that once if you haven't installed the application again. Should work out the box for new installations. Do you care to try to re-install and tell me if it still works?
