### ISSUE TITLE
Strip markdown from first line when creating filename

### ISSUE THREAD

**Issue by cbrown1** [pbek/QOwnNotes#939]
Filename creation based on first line of note should do something like (python code for demonstration):

    file_name = first_line.strip("# ")

This would allow formatting like:

    ## Title

Instead of being restricted to:

    Title
    =====

**Comment by pbek** [comment]
Then some people might complain that they can't use a `#` in their note filename :)

But you can do that in a script, please see: http://docs.qownnotes.org/en/develop/scripting/README.html#handlenotetextfilenamehook

**Comment by cbrown1** [comment]
As written, the strip function will only strip leading pound signs and spaces. Given the prominence of this formatting convention in markdown and the reliance of qownnotes on markdown, this doesn't seem like much of a burden to users. But just my opinion.

**Comment by pbek** [comment]
I already strip `# ` from the beginning of the filename. Doesn't that work for you? (or do you have activated that the note filename can differ from the headline?)
