### ISSUE TITLE
You should be able to create a .md file

### ISSUE THREAD

**Issue by mu-stash** [pbek/QOwnNotes#94]
Files created are currently .txt
Many applications recognise and handle .md automatically. There is also a markdown app in owncloud (that I have not tested yet).
So, to be able to select the .md extension in settings would be much appreciated.
Thank you.

**Comment by pbek** [comment]
We had that request a while ago, it already got implemented. Just take a look at the *General* tab in the settings. Does that solve your issue?

**Comment by mu-stash** [comment]
I guess I only needed an update.

I was using: QOwnNotes - version 0.79 - Ubuntu Linux - build 79
I am now using: QOwnNotes - version 1.0.6 - Launchpad PPA - build 106

Thank you for this quick answer, you can close this issue.

**Comment by pbek** [comment]
Ok great, a glimpse at <http://www.qownnotes.org/changelog/QOwnNotes> also helps very often.
