### ISSUE TITLE
Conflict between "hide menu" and full screen exit

### ISSUE THREAD

**Issue by bepolymathe** [pbek/QOwnNotes#941]
I just noticed a strange behaviour. 

When I want to hide the menu I use the shortcut "Ctl-Maj + M". When the menu is hidden, if I then switch to full screen "Ctl-Alt + D" and return to the normal state, the shortcut "Ctl-Maj + M" to display the menu no longer works. 

@pbek can you reproduce?

**Comment by pbek** [comment]
You I could reproduce that.
It seems a size problem of the menu. I'll put that on my list...
Thank you for reporting.

**Comment by bepolymathe** [comment]
Thanks

**Comment by pbek** [comment]
## 18.06.3
- fixed menu bar visibility after leaving the *distraction free mode* if it 
  was invisible when entering it

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by bepolymathe** [comment]
It works fine for me.

**Comment by pbek** [comment]
Great, thank you for testing!
