### ISSUE TITLE
Tags in "tag selected notes with..." context menu are not sorted

### ISSUE THREAD

**Issue by Maboroshy** [pbek/QOwnNotes#947]
That's it. After tag number becomes big the menu is useless.

**Comment by pbek** [comment]
Thank you for your suggestion. (maybe you should also use multiple levels of tags to structure them a bit) ;)

**Comment by Maboroshy** [comment]
True. But sorting is king! :stuck_out_tongue_closed_eyes:

**Comment by pbek** [comment]
currently the tags were sorted by created date

**Comment by pbek** [comment]
## 18.06.6
- tags in the `tag selected notes with...` context menu of the note list are
  now sorted by name (for [#947](https://github.com/pbek/QOwnNotes/issues/947))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Maboroshy** [comment]
Works as expected. Thanks!

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by Maboroshy** [comment]
Note tags panel context menu "Move tags to..." also has this issue.

**Comment by pbek** [comment]
Which issue?

**Comment by pbek** [comment]
The "issue" that it doesn't work like you would like it to work? :D

**Comment by Maboroshy** [comment]
> Which issue?

Tags are not sorted by name. That make it inconsistent with latest update and unusable for big number of tags.

> The "issue" that it doesn't work like you would like it to work? :D

Absolutely. I'm a user, we are always like that, you know. :smiley: 
All the guys that remember creation date of their 50 tags are for current sorting mode.

**Comment by pbek** [comment]
Consider my eyes are rolling now. :)

**Comment by pbek** [comment]
## 18.06.7
- tags in the `Move tag to...` context menu of the tag list are now sorted by name

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Maboroshy** [comment]
Works

**Comment by pbek** [comment]
Great, thank you for testing!
