### ISSUE TITLE
Working with multiple notes user interface

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#949]
Here is the input of @Maboroshy, from feature request #946.

I see QON UI structure like this:
Preview pane = to view content, not change it, safe for read-only mode;
Editor pane = to change content, unsafe for read-only mode.

So in multi-note mode:
Preview pane = grid of notes without interactive elements, tells user he selected multiple notes, but keeps him sure he can't alter them, he is a relaxed reader;
Editor pane = `N notes selected` to tell user he selected multiple notes, and buttons which alter notes, if user uses editor pane, he's ready to change something.

And both panes would fit nicely to vertical or horizontal layouts.

Also selecting 2 notes could make preview pane to divide and show both of them. Editor pane would simply go to multi-note mode.

![screenshot_20180623_223632](https://user-images.githubusercontent.com/19194063/41813015-fdc98008-7735-11e8-966c-e1a5ed32e1ec.png)

**Comment by Maboroshy** [comment]
There is not much new here.

Note card list widget - custom, but not really complex. 

Note card widget - that one is very important, it should be very user-customizable and have at least two modes - small for the list and big for previews and maybe some representations that may be implemented later. I still didn't get it right for big mode. It should be A4 sheet size since it's a good metaphor for a note, but I don't know what to do with long note titles.

Editor pane multi-note stand-in widget is very simple without integration into toolbar customization, and little more complex with one. Also there's new scripting function for custom actions on multiple notes.

Preview pane multi-note stand-in is mostly a layout management of note cards widget depending on pane size.

**Comment by Maboroshy** [comment]
I continue tinkering with mock ups. By the way I do them in Qt Designer, sometimes a hacky way though. 
But all of these are Qt widgets.

![screenshot_20180624_104628](https://user-images.githubusercontent.com/19194063/41817040-ebf1566a-779b-11e8-806c-1df7a9a57ae9.png)

**Comment by Maboroshy** [comment]
These note list selection is dreadful, I need to so something about it.

**Comment by Maboroshy** [comment]
While working on topic like this I always have a temptation to do it myself... on PyQt, with blackjack and everything scriptable. But it took you 3 years to get to the app to this level. Not sure I can pull off. I admire your commitment.

**Comment by pbek** [comment]
It often amazes me too how much work it actually was... The build systems alone! There a projects with 10 times the likes and 100 times the community that only still have deb files for download only. :)

**Comment by pbek** [comment]
## 18.07.3
- there now is a new checkbox in the *Panel settings* to show the notes in 
  in the note list with a preview
    - this feature is still experimental and implementation is not finished yet
    - manual renaming of the note name via the context menu is already implemented

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Maboroshy** [comment]
Works for me. Looks like a lot of job done!

Here is what I've found:
1. I have a lag between sub-folder/tag click and note list refresh - about 1 second. Both old and new mode. Not sure if it was introduced by latest changes, but it's the first time I really noticed it. An electron-like feeling I don't remember having before.
2. Having no item delimiters makes a new list very hard to read.
3. The selection effect looks fancy, but it's hard to see and unexpected as it's unique inside and outside of the app.
4. The icon looks out of place, sure it's on your todo list.

**Comment by Maboroshy** [comment]
Funny thing. Since I have YAML front matter in all the notes. All previews show:
```
---
tags:
...
```

By the way, I've turned off tag parsing script for testing, so it haven't affected lag.

**Comment by pbek** [comment]
> I have a lag between sub-folder/tag click and note list refresh - about 1 second. Both old and new mode. Not sure if it's introduced by latest changes, but it's the first time I really notice it. An electron-like feeling I don't remember having before.

I can't reproduce that with my 600 notes on Manjaro

> The selection effect looks fancy, but it's hard to see and unexpected as it's unique inside and outside of the app.

I cannot get that better currently, since the preview widgets in the list don't have a selection effect at all

> The icon looks out of place, sure it's on your todo list.

I need that area for a selection effect :/ I'm not sure if I can get around that...

> Funny thing. Since I have YAML front matter in all the notes previews show:

I don't know how to handle such customizations

**Comment by Maboroshy** [comment]
> I can't reproduce that with my 600 notes on Manjaro

I've found out that it's a cost of having 100 tags. It has nothing to do with new version. A coincidence. Sorry.

**Comment by pbek** [comment]
Phew, working on regressions because of the new preview is tough enough. ;)

**Comment by pbek** [comment]
but 100 tags are not very many... I wonder what causes the lag for you.

**Comment by Maboroshy** [comment]
My guess is: going through sub-folders/tags triggers a note counters refresh, that causes lag. 
Maybe there's some db job going on.

**Comment by pbek** [comment]
there has to be something in the log

**Comment by Maboroshy** [comment]
I will be able to check it no earlier than tomorrow evening.

**Comment by Maboroshy** [comment]
My log mostly says
```
[debug]: handleScriptingNotesTagUpdating
[debug]: reloadTagTree  - 'noteSubFolderIds':  (13)
[debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  (23)
[debug]: reloadTagTree[debug]: handleScriptingNotesTagUpdating
[debug]: reloadTagTree  - 'noteSubFolderIds':  (23)
[debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  (19)
[debug]: reloadTagTree
[debug]: handleScriptingNotesTagUpdating
[debug]: reloadTagTree  - 'noteSubFolderIds':  (19)
[debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  (14)
[debug]: reloadTagTree
[debug]: handleScriptingNotesTagUpdating
[debug]: reloadTagTree  - 'noteSubFolderIds':  (14)
[debug]: filterNotesByNoteSubFolders  - 'noteSubFolderIds':  (11)
[debug]: reloadTagTree
[debug]: handleScriptingNotesTagUpdating
[debug]: reloadTagTree  - 'noteSubFolderIds':  (11)
```

**Comment by pbek** [comment]
nothing fancy

**Comment by pbek** [comment]
## 18.07.8
- when selecting multiple notes the note edit widget will now be hidden and 
  the amount of selected notes will be shown

**Comment by pbek** [comment]
## 18.08.5
- if you select multiple notes you now can use the new `Note operations...` 
  button in in the area where the note edit normally is displayed to do 
  operations on multiple notes

**Comment by pbek** [comment]
@Maboroshy, there now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
## 18.08.7
- if you now **select multiple notes** a **small preview** of those notes will be 
  viewed in the preview panel
    - you can click on the headlines of those notes to jump to the note
    - only the first 40 selected notes will be shown to not decrease the 
      performance when selecting a lot of notes

**Comment by pbek** [comment]
I will close this issue until there is more information.

**Comment by pbek** [comment]
## 18.08.8
- improved preview of multiple notes (for [#949](https://github.com/pbek/QOwnNotes/issues/949))
    - implemented correct breaking of lines
    - fixed preview of note text that was interpreted as html
    - removed empty lines
    - showing 5 lines instead of 3
    - lines are truncated at 80 characters

**Comment by Maboroshy** [comment]
I really like new multi-note preview. Simple and useful. Better than my first ideas. 
For some reason, when I click a headline of note in multi preview, app cannot find any and asks if I want to create one.

**Comment by pbek** [comment]
> I really like new multi-note preview. Simple and useful. Better than my first ideas.

Thank you, it was quite some work. :)

>  For some reason, when I click a headline of note in multi preview, app cannot find any and asks if I want to create one.

Hm... Might that come from a setting or a note-name script?

**Comment by Maboroshy** [comment]
Nope. I have everything off for testing. 

I found that it happens when I have "All notes" set as a sub-folder.

**Comment by pbek** [comment]
What does the log say?

**Comment by Maboroshy** [comment]
Nothing specific

```
[debug]: on_noteTreeWidget_currentItemChanged
[debug]: setCurrentNote  - 'note':  Note: <id>27 <name>"Five Invaluable Techniques to Improve Regex Performance" <fileName>"Five Invaluable Techniques to Improve Regex Performance.md" <noteSubFolderId>3 <relativePath>"IT/Coding" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
[debug]:  added to history:  NoteHistoryItem: <noteName>"Five Invaluable Techniques to Improve Regex Performance" <noteSubFolderPathData>"IT\nCoding" <cursorPosition>0 <relativeScrollBarPosition>0
[debug]: on_noteTreeWidget_currentItemChanged
[debug]: setCurrentNote  - 'note':  Note: <id>63 <name>"Automated Tests in Python" <fileName>"Automated Tests in Python.md" <noteSubFolderId>4 <relativePath>"IT/Coding/Python" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
[debug]:  added to history:  NoteHistoryItem: <noteName>"Automated Tests in Python" <noteSubFolderPathData>"IT\nCoding\nPython" <cursorPosition>0 <relativeScrollBarPosition>0
[debug]: on_noteTextView_anchorClicked  - 'url':  QUrl("note://Automated_Tests_in_Python@")
```

The last line says app uses `note://` link to jump to one of selected notes. As far as I remember it's incompatible with sub-folders. Looks like that's the cause of the issue.

**Comment by pbek** [comment]
that looks ok:
`[debug]: on_noteTextView_anchorClicked  - 'url':  QUrl("note://Automated_Tests_in_Python@")`

I've no troubles using the note links in subfolders but if "All notes" is set it doesn't work. Interesting... But the links seem to work in notes...

**Comment by pbek** [comment]
I see now. Links to notes in other than the current note subfolder doesn't work... That is also affecting that list of notes in the preview... (regardless of the `All notes` selection)

**Comment by pbek** [comment]
## 18.08.11
- the **Find action** dialog now searches for every entered word on in `and`-fashion
  (for [#1007](https://github.com/pbek/QOwnNotes/issues/1007))
    - all menu items that have all of the entered words (or parts of them) in 
      the name or tooltip will be shown
- attempted to fix a reloading of the notes list problem on some installations
  after importing notes from Evernote (for [#1006](https://github.com/pbek/QOwnNotes/issues/1006))
## 18.08.11
I now "invented" now links like `noteid://note-1234` that will jump to the note with id `1234` directly.

## 18.08.11
- when selecting multiple notes clicking on the headlines of the selected 
  notes in the note preview will now jump to the note when using subfolders and
  `All notes` was selected even if the note wasn't in the same note subfolder

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by Maboroshy** [comment]
Works for me. Notes with the same name in different sub-folders also cause no issues.
