### ISSUE TITLE
Translating QOwnNotes

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#95]
I'm happy to announce that we now have a Crowdin account as an alternative way of translating QOwnNotes.
<https://crowdin.com/project/qownnotes/>

Please feel encouraged to create or update your translations there if that's easier for you!
The community is depending on your great work!
I've updated: http://www.qownnotes.org/Knowledge-base/How-can-I-help-to-translate-QOwnNotes

ping: @calis2002 @LiangWei88  @Dalan94 @Olhur @elnull @mlimacarlos 

@LiangWei88, the Chinese translation shows up on Crowdin with an iso code `zh` (I said `zn` before, sorry), not `cn` that we are using. Do you know if `zn` would be correct, I would fix that in QOwnNotes if that's the case.

**Comment by LiangWei88** [comment]
We use cn or zh for chinese translation.
Cn is short for china/chinese in english.
Zh is short for china/chinese in chinese (zhong).
But use zn for chinese is very rare for me.
I am sure we don't use it in mainland china,
but I am not sure in Taiwan or Hongkong.

**Comment by pbek** [comment]
Thank you for your answer, @LiangWei88. I found other references to `zh-CN`, maybe it's really better the migrate our translation file from `QOwnNotes_cn.ts` to `QOwnNotes_zn.ts`. Or we start using the `zh-CN` iso code in the file names...

**Comment by calis2002** [comment]
:+1: very good idea to use crowdin.
btw German is at 100% again ;)

**Comment by pbek** [comment]
Thank you @calis2002! I still have to come up with a solution to merge translations on GitHub and Crowdin without destroying anything. :smile_cat:

**Comment by pbek** [comment]
@LiangWei88 if your computer's system language is Chinese, did you have to select `Chinese` in QOwnNotes as language to see the Chinese user interface or was it detected by the `Automatic` setting?

**Comment by pbek** [comment]
@LiangWei88, I renamed  `QOwnNotes_cn.ts` to `QOwnNotes_zh.ts`. The new strings are now translatable on <https://crowdin.com/project/qownnotes>.

**Comment by Fabijenna** [comment]
nl is being created

**Comment by pbek** [comment]
You are simply the best, @Fabijenna ! :smile_cat: 
I added *Dutch* on https://crowdin.com/project/qownnotes, if you want to translate it there.

**Comment by LiangWei88** [comment]
@pbek My computer's system language is Chinese, QOwnNotes language was detected by the Automatic setting.

**Comment by pbek** [comment]
@LiangWei88, pre version 1.0.7 or with version 1.0.7 (or newer), because in v1.0.7 I changed the language file to  `QOwnNotes_zh.ts`

**Comment by LiangWei88** [comment]
@pbek I download it yesterdau, I am not sure it is windows-b1106 or windows-b1103

**Comment by pbek** [comment]
Then everything should be ok! Thank you, @LiangWei88!
Glory awaits you at <https://crowdin.com/translate/qownnotes/1/en-zhcn> :smile_cat:

**Comment by mlimacarlos** [comment]
I like it! I made the other traslations to portuguese brazilian. I always been avaliable for add this translation. Its a pleasure.

**Comment by pbek** [comment]
Great job! Thank you, @mlimacarlos! I will release it with version 1.2.0.

**Comment by Fabijenna** [comment]
Hi Cici, 
kann das irgendwie aus bitte, ich konnte die Notifications nicht abstellen
DANKE!!!!!!!!
;)

 --- --- --- --- --- --- ---



adLang.media.services
www.amylang.jimdo.com
skype:amydlang


Date: Tue, 15 Mar 2016 11:15:16 -0700

**Comment by pbek** [comment]
@Fabijenna, please try the *Unsubscribe* button on the right in this issue.

**Comment by mlimacarlos** [comment]
Hi @pbek , 

 There is some words with error. I correct this term in crowdin but i cant see in app. How can we solve this?

**Comment by pbek** [comment]
Did you actually suggest a new translation or did you just comment on it? I can't see any changes in the translation, just your comments.
The translation will only be in the app after you are changing the translation, I approve it, I download it from the Crowdin server, re-created the binary translation files, create a new build, make a release and you download the release and open the new version of QOwnNotes. :)

Or did you build QOwnNotes yourself?
Then you may have forgot to do a `lrelease QOwnNotes.pro` in the `src` directory.
(See: <http://www.qownnotes.org/Knowledge-base/How-can-I-help-to-translate-QOwnNotes>)

**Comment by pbek** [comment]
@calis2002 Germany is longing for your translation. :) And most of the non-English speaking users of QOwnNotes are from Germany...

Glory awaits you at: <https://crowdin.com/translate/qownnotes/1/en-de> :grin:

**Comment by calis2002** [comment]
Currently very bussy but i'm sure i find some time today evening :blush:

**Comment by pbek** [comment]
You are my hero! :smile_cat:

**Comment by pbek** [comment]
@Olhur, @LiangWei88, there is sooooo much new text in QOwnNotes. Do you care to give it some love? :)

**Comment by fmakowski** [comment]
@pbek sure, I will take care of Polish translation today's afternoon, 
have a nice day! ;)


W dniu 12.08.2016 o 10:43, Patrizio Bekerle pisze:

**Comment by pbek** [comment]
That's music to my ears, @fmakowski! :)

<https://crowdin.com/translate/qownnotes/1/en-pl>

Have a great day yourself!

**Comment by richarson** [comment]
Hey, I didn't know there was this thread!

I made a comment on the Spanish translation, I'm not familiar with Crowdin so I'm not sure how it works, but I'll try to help with the missing strings :)

**Comment by pbek** [comment]
Thanks a lot, @richarson!
