### ISSUE TITLE
Windows application is blocked by Windows Defender SmartScreen

### ISSUE THREAD

**Issue by biva** [pbek/QOwnNotes#954]
Windows application is blocked by Windows Defender SmartScreen. Is it possible to correct this?

**Comment by pbek** [comment]
I guess Microsoft likes all apps signed by them (which the QOwnNotes binaries aren't)...
But you can get around that for example by https://www.pcworld.com/article/3197443/windows/how-to-get-past-windows-defender-smartscreen-in-windows-10.html

Does that answer your question?

**Comment by biva** [comment]
Thanks for your answer: indeed, it needs to be signed. It also gives confidence to the users. Is it possible to make QOwnNotes signed?

**Comment by pbek** [comment]
I don't know how much that would cost and if that's even possible in the current build chain.

**Comment by biva** [comment]
I found some information, but it goes beyond my skills :(
- https://blogs.msdn.microsoft.com/ie/2011/03/22/smartscreen-application-reputation-building-reputation/
- https://blogs.msdn.microsoft.com/ie/2012/08/14/microsoft-smartscreen-extended-validation-ev-code-signing-certificates/
- https://feedback.smartscreen.microsoft.com/smartscreenfaq.aspx
I don't think you have to pay anything to Microsoft

**Comment by pbek** [comment]
Don't you need a Windows App Store submission? QOwnNotes doesn't even have a installation routine...

**Comment by pbek** [comment]
I will close this until there is more information.
