### ISSUE TITLE
How to manage attachments of notes

### ISSUE THREAD

**Issue by rakekniven** [pbek/QOwnNotes#957]
I have some notes with attached files like pdfs.
Notes are working fine but now I came to the questions "how to manage these attachments?".

Are related attachments are deleted when deleting a note with attachments?
What if a attachment is used in many notes (>1)?

If there is no menu to manage attachments can I just delete attachments from folder?

Version 18.07.0

**Comment by pbek** [comment]
The attachments are all in the media folder.
And as of deleting, there is a feature request: https://github.com/pbek/QOwnNotes/issues/895

Does that answer your question?

**Comment by rakekniven** [comment]
Yes, this answers half of it :-)

Until feature request is not implemented:
Can I just delete attachments from folder?

**Comment by pbek** [comment]
> Can I just delete attachments from folder?

of course, if you are sure no note links to it (you could search for the name of the file without extension)

**Comment by rakekniven** [comment]
Ok.

@pbek Feel free to close this or the other issue and we stay with one.

**Comment by rakekniven** [comment]
> you could search for the name of the file without extension

How to search for in all notes. Just found the option to search in one note.

**Comment by rakekniven** [comment]
@pbek Have you seen my question in last posting?

**Comment by pbek** [comment]
Oh, sorry. I haven't. You can search in all note in the search bar in note list panel.

**Comment by rakekniven** [comment]
Oh, it does work on my mac. Tried it today at work on windows and did not succeed.

btw. Then we should change wording. It says "Search or create note".
It does not say "Search in all notes or create note". Am I right?

**Comment by pbek** [comment]
> Tried it today at work on windows and did not succeed.

can you please try again :)

> It does not say "Search in all notes or create note"

why do you think this needs to be added (the text would get longer than the text field for people)?

**Comment by rakekniven** [comment]
I checked menu entries and found "search in current note".

"Search or create note" does not say that search is global IMHO.

For sure I will try again.
