### ISSUE TITLE
Can't install qownnotes

### ISSUE THREAD

**Issue by Lentz92** [pbek/QOwnNotes#968]
Hello.
I used to use qownnotes on manjaro KDE. but now i chose to reinstall manjaro and try with gnome, now i can't install qownnotes.

When try to build it with git clone, everything works till the last part. when i use qmake it says:
Info: creating stash file /home/lentz/QOwnNotes/src/.qmake.stash
Project MESSAGE: Currently in RELEASE mode.
Empty filename passed to function
Empty filename passed to function
Empty filename passed to function
Empty filename passed to function
Empty filename passed to function
Empty filename passed to function
Empty filename passed to function

And then when i use make command:
bash: make: command not found

I then tried to use the installation for arch linux, and after setting up the repository, i try to use the pacman -Syy qownnotes command i end up with

error: failed retrieving file 'qownnotes-18.07.2-1-x86_64.pkg.tar.xz' from download.opensuse.org : Maximum file size exceeded
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.

Anyone who can help? :-)

**Comment by pbek** [comment]
I can see the file on the open build service: https://build.opensuse.org/package/binary/home:pbek:QOwnNotes/desktop/Arch_Extra/x86_64/qownnotes-18.07.2-1-x86_64.pkg.tar.xz

But couldn't you just try to install it from the AUR?

**Comment by Lentz92** [comment]
Still gives me issues.

Info: creating stash file /tmp/yaourt-tmp-lentz/aur-qownnotes/src/qownnotes-18.07.2/.qmake.stash
Project MESSAGE: Currently in RELEASE mode.
Empty filename passed to function
Empty filename passed to function
Empty filename passed to function
Empty filename passed to function
Empty filename passed to function
Empty filename passed to function
Empty filename passed to function
/tmp/yaourt-tmp-lentz/aur-qownnotes/./PKGBUILD: line 25: make: command not found
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build qownnotes.
==> Restart building qownnotes ? [y/N]
==> ------------------------------

**Comment by pbek** [comment]
from the looks of it you don't have the `make` command installed to build packages...

**Comment by pbek** [comment]
`pacman -S base-devel` should install those tools

**Comment by pbek** [comment]
I will close this issue until there is more information.
