### ISSUE TITLE
No feedback from UI while getting versions or deleted notes

### ISSUE THREAD

**Issue by Letterus** [pbek/QOwnNotes#97]
## Steps to reproduce:
1. (Select a note)
2. Click the icon to fetch versions of the note or deleted notes many times

## Expected behavior
1. The icon is blocked while the application is fetching information from the server and as long as no other note is selected.
2. The user is seeing a signal indicating the app is doing something.
3. The wanted information is then shown once.

## Actual behavior
1. User gets no feedback from the UI.
2. Information are fetched multiple times.
3. Information are shown in many windows which suddenly pop up.

**Comment by pbek** [comment]
Thank you for your report, @Letterus!
I will look into this matter.

**Comment by pbek** [comment]
This is now implemented in the new version 1.1.3. Please be so kind and report back if everything works fine.

**Comment by Letterus** [comment]
Getting deletes notes works nicely. Versions of notes as well, but I would expect the "get versions" icon to be disabled when no note is selected. Instead it fetches the versions of the last selected note currently. Eventually this might be confusing (f.e. when the last time of having selected a note is some days ago).

**Comment by pbek** [comment]
Thank you for reporting back.
Do you have a note visible in the note edit area while you have no note selected? Some note is always open your have you removed all notes?

**Comment by Letterus** [comment]
Yes. Alright. One note is open. Then this makes sense. The other icons work the same way. ;-)

**Comment by pbek** [comment]
Ok, great! :)
