### ISSUE TITLE
Windows portable mode / custom folder doesn't work

### ISSUE THREAD

**Issue by wpa1160** [pbek/QOwnNotes#971]
I have downloaded QOwnNotes to D:\QOwnNotes and launched with **QOwnNotes.exe --portable**.

QOwnNotes proposes D:/QOwnNotes/Data/Notes for storing and I manually browse to folder C:/Temp (which is also shown in the text field). After clicking through the wizard and the finish button I'll get an error message (free translated from German):

_Cannot connect to the database with filename 'D:/QOwnNotes/Data/C:/Temp/notes.sqlite'._

After dismissing the error I'll correct the wrong folder within the settings but if I close QOwnNotes and launch again in portable the loop begins again.

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue.

**Comment by pbek** [comment]
>  I manually browse to folder C:/Temp

you are not even supposed to use folders outside to the place where QOwnNotes sits, that's the reason for the portable mode... :) the note path is relative to the path of where QOwnNotes is placed

**Comment by pbek** [comment]
## 18.07.4
- under Windows it is now checked if user chose a different drive for the note 
  folder in the welcome dialog in portable mode

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by wpa1160** [comment]
That did the trick, works now as expected.

For explanation: The use on a bunch of systems is still portable but I sync only the changed files back and forth on the USB key. This affects other portable apps as well and doing it that way I only have to keep track of one folder on all systems.

Thanks for your fast addressing of the issue!

**Comment by pbek** [comment]
Great, thank you for testing!
