### ISSUE TITLE
Mac OS X: Error message "file changed externally" while typing when OwnCloud client app is used

### ISSUE THREAD

**Issue by Letterus** [pbek/QOwnNotes#98]
## Steps to reproduce

Use Mac OS X 10.11.3 and OwnCloud client 2.1.1. Edit a note within the OwnCloud sync directory.

1. Set interval to save file to 10 or 15 seconds.
2. Edit the note continuously (error does not happen when you pause typing in the moment the OwnCloud client syncs).

## Expected behavior
The error message "file changed externally" is only shown when the file was actually changed externally.

## Actual behavior
The error message "file changed externally" is shown even though there are no changes from other apps or users. In the version diff the last character typed (or deleted) is shown as conflicting.

## Assumption
It seems the OwnCloud client app is saving the file before/while syncing OR the OwnCloud client app is changing anything of the note file which is interpreted as "saving" by QOwnNotes.

**Comment by pbek** [comment]
Thank you for your report, @Letterus!
QOwnNotes gets notified by the filesystem if a file (case 1) or something in the directory (case 2) was modified. QOwnNotes then additionally checks if the content of the file differs before firing up the diff-dialog. So far I wasn't able to reproduce this behavior reliably.

**Comment by Letterus** [comment]
Ok, thanks for answering. I experienced similar weird problems when I used the Seafile client - there one problem was that I am using OS X Server where my home dir is mounted via network volume. Maybe OS X/the sync apps do some weird file modification on such networked volumes. I'm gonna retest this issue on a regular OS X device/user with regular home dir.

**Comment by pbek** [comment]
Every now and then I even get a directory change triggered which for QOwnNotes can also mean that a note was deleted externally so all the notes have to be re-read. Only happened under OS X so far...

**Comment by Letterus** [comment]
It is definitely a problem of the ownCloud client (or of the Qt API they use - the Seafile client behaves the same way). There are some changes on the corresponding file (or dir) when the client is syncing it. I was experiencing this issue very often because I used an external storage on the server side. This way the sync process had a good portion more latency which I could type in between and thus change the file while it was synced. Since I changed the Notes directory to local server directory this issue occurs very seldom. I suppose because of the shorter latency.

(To be true this is one of the reasons I stopped using ownCloud for productional use after a month or so of testing. Using it only for Notes and similar stuff now. For me the sync process seems to be implemented insufficient on too many levels.)

**Comment by pbek** [comment]
Watching files and directories for changes is handled by <http://doc.qt.io/qt-5/qfilesystemwatcher.html>.

I wonder if ownCloud 9.0 fixes some of your other sync issues...

**Comment by pbek** [comment]
In version 1.2.4 you should see a status message on the bottom telling you why the note diff dialog was opened.

**Comment by Letterus** [comment]
Yep. It's only opened when "note file was modified externally". The diff dialog is not popping up when the dir was changed. As it is changed by the Seafile client (probably), I don't know how fix it. I think I will open an issue for the Seafile client.

Maybe you could add an option to ignore external changes always? That would reduce interruptions while working/typing.

**Comment by pbek** [comment]
QOwnNotes only shows the diff dialog if the content of the note and the content of the file differs so there must be some differences...
I don't think ignoring external changes is a good idea, one might modify a note elsewhere (for example while the other computer is at sleep) and QOwnNotes will never recognize the change...

**Comment by Letterus** [comment]
In my case that would be fine because Seafile would detect the conflict and save a copy of the file.

**Comment by pbek** [comment]
How would seafile detect a conflict if it syncs the text file to the computer and QOwnNotes overwrites it with a old version of the note afterwards? There never would be a conflict in my eyes.

**Comment by Letterus** [comment]
Hm, you might be correct. :-) Think I'll have to test if there are some more further checks implemented.

**Comment by pbek** [comment]
It would be great to know the binary difference between an externally modified note and the note in QOwnNotes, so I can ignore it there. Maybe you can catch a note file before and after it was updated by seafile...

**Comment by praxiq** [comment]
just want to point out that I haven't been using seafile or owncloud but I've still been getting these messages on OSX. My notes folder is stored in a dropbox folder, fwiw. It usually comes up while I'm typing, and it highlights the last few letters I've typed as the difference between the file on disk and the file I'm editing. (I'm trying to reproduce it deliberately right now but I can't.... will let you know if I figure out anything more.)

**Comment by pbek** [comment]
Thank you for letting me know! So it's not a thing with ownCloud sync, but with OS X and/or Qt under OS X...

**Comment by pbek** [comment]
I will close this issue until there is more information.
