### ISSUE TITLE
Note couldn't be saved for it's edited content after upgrading to ver. 18.08.2 build 464

### ISSUE THREAD

**Issue by photonxp** [pbek/QOwnNotes#987]
#### System:
Both Ubuntu 16 and Debian 8

#### Package:
qownnotes/xenial,now 18.08.2-1ubuntu3ppa1~xenial1

#### Expected behavior         
Note could be saved after it's edited 

#### Actual behavior           
Today I updated QownNotes. Then I found the edited content couldn't be saved either for a newly created note or an existing old note. This happened on both Ubuntu 16 and Debian 8.

#### Steps to reproduce
Here is how I could reproduce it:
- Create one new note with no new content
- The new note would be stored, there would be added log in the log file [ see below ]
- Add some text content to the newly created note, or change the title of the note
- The note wouldn't be stored, with no new log written to the log file

#### Output from the debug section in the settings dialog

> **Current Date**: `Sat Aug 11 21:49:22 2018`
> **Version**: `18.08.2`
> **Build date**: `Aug  7 2018`
> **Build number**: `464`
> **Platform**: `linux`
> **Operating System**: `Ubuntu 16.04.5 LTS`
> **Build architecture**: `x86_64`
> **Current architecture**: `x86_64`
> **Release**: `Launchpad PPA`
> **Qt Version (build)**: `5.5.1`
> **Qt Version (runtime)**: `5.5.1`
> **Portable mode**: `no`
> **Application arguments**: `QOwnNotes`
> **Qt Debug**: `0`
> **Locale (system)**: `en_US`
> **Locale (interface)**: *empty*
> **Icon theme**: `ubuntu-mono-dark`
> **Notes in current note folder**: `1836`
> **Enabled scripts**: `0`
> 

#### Relevant log output in the Log panel
Log content for the newly created note with no content:

> [Aug 11 20:59:41] [debug]: storing note file:  "Note 2018-08-11T20.59.41.md"
> [Aug 11 20:59:41] [status]: Stored current note to disk
> [Aug 11 20:59:41] [debug]: loadNoteDirectoryList
> [Aug 11 20:59:43] [debug]: reloadTagTree
> [Aug 11 20:59:44] [debug]: reloadTagTree  - 'noteSubFolderIds':  (-1)
> [Aug 11 20:59:46] [debug]: setCurrentNote  - 'note':  Note: <id>1835 <name>"Note 2018-08-11T20.59.41" <fileName>"Note 2018-08-11T20.59.41.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  true
> [Aug 11 20:59:46] [debug]:  added to history:  NoteHistoryItem: <noteName>"Note 2018-08-11T20.59.41" <noteSubFolderPathData>"" <cursorPosition>0 <relativeScrollBarPosition>0

Log content after the note is edited:
[NOTHING_NEW_HERE]

**Comment by pbek** [comment]
Thank you for reporting, I will try to reproduce your issue.

**Comment by pbek** [comment]
## 18.08.3
- fixed a problem with automatically storing modified notes (for [#987](https://github.com/pbek/QOwnNotes/issues/987))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by photonxp** [comment]
Yeah, it works now for 18.08.3. That's a quick fix and thanks a lot.

**Comment by pbek** [comment]
Great, thank you for testing! ;)
