### ISSUE TITLE
Performance headwind on start of QOwnnotes. Optimization feasible?

### ISSUE THREAD

**Issue by photonxp** [pbek/QOwnNotes#988]
As the number of Notes increase, the starting process of QOwnnotes could take more time day after day. For me, that could be more than 10 seconds.

For example, the start-up log for my QOwnnotes:

> [Aug 12 21:50:08] [debug]: Set proxy configuration to use NO proxy
> [Aug 12 21:50:08] [debug]: initShortcuts  - 'menuBarIsVisible':  false
> [Aug 12 21:50:08] [debug]: initShortcuts  - 'menuBarIsVisible':  false
> [Aug 12 21:50:08] [debug]: buildNotesIndex  - 'noteSubFolderId':  0
> [Aug 12 21:50:09] [debug]: setupNoteFolderTables  - 'database version':  13
> [Aug 12 **21:50:09**] [debug]: **loadNoteDirectoryList**
> [Aug 12 **21:50:11**] [debug]: reloadTagTree
> [Aug 12 21:50:12] [debug]: reloadTagTree  - 'noteSubFolderIds':  (-1)
> [Aug 12 **21:50:13**] [debug]: **loadNoteDirectoryList**
> [Aug 12 **21:50:15**] [debug]: reloadTagTree
> [Aug 12 21:50:16] [debug]: reloadTagTree  - 'noteSubFolderIds':  (-1)
> [Aug 12 21:50:17] [debug]: reloadNoteSubFolderTree
> [Aug 12 21:50:17] [debug]: reloadTagTree
> [Aug 12 **21:50:18**] [debug]: **reloadTagTree**  - 'noteSubFolderIds':  (-1)
> [Aug 12 **21:50:20**] [debug]: reloadTagTree
> [Aug 12 21:50:21] [debug]: reloadTagTree  - 'noteSubFolderIds':  (-1)
> [Aug 12 21:50:22] [debug]: on_noteTreeWidget_currentItemChanged
> [Aug 12 21:50:22] [debug]: setCurrentNote  - 'note':  Note: <id>1 <name>"Note 2018-08-12T21.49.42" <fileName>"Note 2018-08-12T21.49.42.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
> [Aug 12 21:50:22] [debug]:  added to history:  NoteHistoryItem: <noteName>"Note 2018-08-12T21.49.42" <noteSubFolderPathData>"" <cursorPosition>0 <relativeScrollBarPosition>0
> 

So I was wondering if it was possible and plausible to do something so that QOwnnotes could drive faster on start-up. 

I looked around the code a little bit and noticed some sql statements might have the potential to be optimized. Say, the sql in **NoteFolder::fetchAll()** in [notefolder.cpp](https://github.com/pbek/QOwnNotes/blob/0230dce00b4c48c7b886f6d8ed1de601b643f960/src/entities/notefolder.cpp#L199):
```
QList<NoteFolder> NoteFolder::fetchAll() {
    QSqlDatabase db = QSqlDatabase::database("disk");
    QSqlQuery query(db);
    ...
    query.prepare("SELECT * FROM noteFolder ORDER BY priority ASC, id ASC");
    ...
```

Several things to note here:
  *   Connection pools for the db object. 
      * With connection pools, it's possible to reuse the connections among fetches hence no need to create the db objects repeatedly. I'm not sure if the db object is reused or created repeatedly in QSqlDatabase::database()   
   *  Composite index. 
      * If a composite index could be created on the table noteFolder, the query might run faster than "order by" multiple columns. 

Anyway, it's hard to say how much performance could be gained in all by doing sql optimization like this, or if there are better ways to do it, but it seems like one of the places to mark up for later considerations.

**Comment by pbek** [comment]
For most people the noteFolder tables has just one entry... I'm not sure of optimization really helps in that case. :) In my experience the most time is spent reading all note files and putting them into the in-memory note table... For 1000+ notes that can take some time. And it has to be redone every time an unrecognized note folder change occurs...

**Comment by photonxp** [comment]
As for the the in-memory note table... 

My first thought was to split the one large table into smaller tables, just as splitting one large piece of paper into smaller pages of paper. On start-up just load one smaller table instead of all the smaller tables. Also load different smaller tables(pages) dynamically on the requests of user operations such as mouse scrolling or scroll-bar moving. 

But that sounds quite challenging technically.

**Comment by pbek** [comment]
Do you really think an in-memory table is a bottle neck? In my experience reading 1000 files took most of the time... Reading (for example searching in all notes in the table) is lightning fast...

**Comment by photonxp** [comment]
Yeah I get it now. All the notes should be loaded into the memory at the start of QOwnnotes, and that means a lot of operations on note files with disk I/O. If just load a few sections of all the note files at the beginning, there could be logic problems in later usage of QOwnnotes.

So a practical way to start QOwnnotes is to start it as a server. It's better not not stop/restart QOwnnotes unless problems occur or when necessary. Switching from old-fashioned HDD to modern SSD disk is also helpful. 

However in my opinion a better structure of node table in memory could still help in other ways. Memory operations takes time, such as insertion/deletion/update of a single note. The difference and potential benefits are especially obvious if someone has to frequently create/delete/update notes, as editors would usually do.  Though this kind of optimization is somehow another issue, not related to start-up problem directly.

**Comment by pbek** [comment]
I will close this issue until there is more information or there are things that can be done.
