### ISSUE TITLE
Feature request: Support a keyboard shortcut to print a note

### ISSUE THREAD

**Issue by Letterus** [pbek/QOwnNotes#99]
Currently you have to use the menu if you want to print a note.

Proposal: Support keyboard shortcuts like Command/Ctrl-P and Command/Ctrl-Shift-P to print text or markdown of a note.

**Comment by pbek** [comment]
Thank you for your report, @Letterus!
I'm sure we can do that. :)

**Comment by pbek** [comment]
Done. It will be released with version 1.1.3.

**Comment by pbek** [comment]
This is now implemented in the new version 1.1.3. Please be so kind and report back if everything works fine.

**Comment by Letterus** [comment]
Works nicely. Thank you!

**Comment by pbek** [comment]
Ok, great!
