### ISSUE TITLE
How to regenerate the sqlite file?

### ISSUE THREAD

**Issue by RavenTheDev** [pbek/QOwnNotes#991]
After my installation broke and I re-installed it, I have configured QOwnNOtes again to point to my local Notes Folder, synced with NextCloud but it is only showing extremely old notes that were synced to the "Notes" section of my NextCloud instance.

How can I get it to recognise and re-upload the Notes that I have already created?

**Comment by pbek** [comment]
QOwnNotes doesn't sync note. Please see https://www.qownnotes.org/Knowledge-base/Why-isn-t-QOwnNotesAPI-syncing-my-notes

Does this answer your question?

**Comment by RavenTheDev** [comment]
Hey, unfortunately not. 

Basically i have my notes set to save to Raven > NextCloud > Notes.

In this folder I can see all the most recent, up to date notes that I have created. Upon installing QOwnNotes on my machine again after a re-install, i re-downloaded that folder from NextCloud but pointing my QOwnNotes client to set that folder as the Notes Folder, it seems to connect to my NextCloud instance and load up old notes from long long ago.

What I am attempting to do is get it to simply reload the folder I have set and show all notes that are listed under HTML or MD format.

**Comment by pbek** [comment]
Since you didn't fill out the issue template I can only guess...
Where does your note folder point to? (Settings dialog)

**Comment by RavenTheDev** [comment]
Nevermind! I figured it out just now! I had setup a custom extension of 'html' so that my server can auto grab the files and render them, and had not added it back into the new installation. Therefore it would only show .md files, and it was ignoring the .html files.

Sorry!
