### ISSUE TITLE
Minimize/Maximize shortcut

### ISSUE THREAD

**Issue by Galactia** [pbek/QOwnNotes#992]
Hi there, I just installed QOwnNotes a couple of days ago and I love it.

I've been looking for a way to minimize to try and and maximize it via a global shortcut and I cannot find it in the program.

Is it possible? If not, I would really like this to be implemented if possible to acelerate the workflow. Thank you for your work on QOwnNotes.

**Comment by pbek** [comment]
Thank you for your kind words. Please see #44.

**Comment by Galactia** [comment]
Ok, I guess that meas it can´t/wont be implemented?

**Comment by Galactia** [comment]
Found a workaround, with an external software. Thanks.

**Comment by pbek** [comment]
Did you find the setting to allow only one app instance. It will open the app window if you run it again then.

**Comment by pbek** [comment]
> Ok, I guess that meas it can´t/wont be implemented?

so far I found no secure way to do it
