### ISSUE TITLE
Feature request: Option to interpret single new line as </br>

### ISSUE THREAD

**Issue by geckolinux** [pbek/QOwnNotes#995]
Hi there, thanks a ton for the power and flexibility of QOwnNotes.

I was wondering if there could be an option to interpret a single new line as though it were an HTML `</br>`. I personally find this behavior more intuitive for creating bullet/numbered lists. I also frequently need line breaks in my notes that are *not* paragraph breaks.

I know this request is probably not 100% legitimate Markdown, but even GitHub's spin on Markdown allows what I'm requesting:

![1](https://user-images.githubusercontent.com/2692138/44346274-2c7a6c80-a45b-11e8-8d81-5f485ab8c268.png)
----------------
![2](https://user-images.githubusercontent.com/2692138/44346286-3308e400-a45b-11e8-9784-a76a5476ae76.png)
----------------

Thanks a lot for considering this!

**Comment by geckolinux** [comment]
Wow, very nice. That does indeed do the trick. Thanks a lot!

**Comment by pbek** [comment]
Great! ;) And thank you for your work on https://geckolinux.github.io/!

**Comment by pbek** [comment]
Does the OBS build of QOwnNotes work well on it?

**Comment by geckolinux** [comment]
Thanks a lot for saying so!

> Does the OBS build of QOwnNotes work well on it?
Yep, since GeckoLinux is built from openSUSE (and Packman) packages, it is 100% compatible with openSUSE.

**Comment by pbek** [comment]
> Yep, since GeckoLinux is built from openSUSE (and Packman) packages, it is 100% compatible with openSUSE.

Great! Do you build QOwnNotes yourself (via OBS) or do you use my repository?

**Comment by geckolinux** [comment]
Hi again! Sorry for the slow reply. I use your packages directly, they work great.

**Comment by pbek** [comment]
Great! ;)
