### ISSUE TITLE
How to turn on Todo feature

### ISSUE THREAD

**Issue by nima87** [pbek/QOwnNotes#999]
Hi Patrizio,
I want to use Todo feature, though I don't know what it looks like. I went to this page: https://owncloud.org/download/ and downloaded the **ownCloud desktop client for Windows** and installed it. Running it a window appeared asking a server address. I searched the Qownnotes documentation for help, but I couldn't find _any_. There are some hints in the OwnCloud/NextCloud section in the settings, but I don't understand it. Should I download OwnCloud or NextCloud or both?
Would you please guide me regarding the steps I should take and the programs I have to download to turn on the Todo feature? My OS is Windows 7.
Thanks.

**Comment by pbek** [comment]
You will need a Nextcloud or ownCloud server to use the todo feature. They can be either hosted on your own server or you use a hosted one... E.g. on [Digital Ocean](https://www.digitalocean.com/features/one-click-apps/owncloud/?refcode=a46a4d6212ea)

Does this answer your question?

**Comment by nima87** [comment]
I want use todo feature on my own computer, that is I don't want to host it on a web server on the internet. That was possibly one of the reasons I wrote **I though I don't know what it looks like**. So if there is the possibility of using it only through a web-server the I don't have any more question. But if I can use my computer as server for todo feature I still need to be instructed through the steps.

**Comment by pbek** [comment]
> I want to use todo feature on my own computer, that is I don't want to host it on a web server on the internet.

I'm sorry, that's not possible. QOwnNotes only acts as a CalDav client for CalDav-servers.
Installing one on Windows might be tricky...

**Comment by pbek** [comment]
You might want to use services like https://portknox.net/en

**Comment by nima87** [comment]
Thank you Patrizio.

**Comment by pbek** [comment]
Hope it helped a bit. :)

**Comment by pbek** [comment]
Sure.
